### PR TITLE
Hosting configuration: poll Atomic transfer status when loading the page (v2)

### LINKED ISSUE #72371: [Bug]: UI gets stuck after activating hosting features
### Quick summary

When I activate hosting features, the page gets stuck on the “Please wait while we activate the hosting features.“ message. Hosting features seem to be activated, but the page doesn't reload.

### Steps to reproduce

1. Create a site with a Business plan
2. Navigate to Settings -> Hosting Configuration
3. Activate hosting features and confirm domain change

### What you expected to happen

The page reloads after the process is done.

### What actually happened

"Please wait while we activate the hosting features." is displayed all the time.

### Browser

Google Chrome/Chromium

### Context

_No response_

### Platform (Simple, Atomic, or both?)

Atomic

### Other notes

_No response_

### Reproducibility

Intermittent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

After some time, I can refresh page manually.

### PR DESCRIPTION
**Pull request by mpkelly**
Closes https://github.com/Automattic/wp-calypso/issues/72371
Related https://github.com/Automattic/wp-calypso/pull/77112 (I ported this original PR to the latest trunk and made some small improvements along the way)

## Proposed Changes

* Make sure the `/hosting-config` UI updates correctly when the Atomic transfer completes ( see https://github.com/Automattic/wp-calypso/issues/72371)
* When transferring, make the client-side status polling mechanism robust enough to survive a hard page refresh. 
* Now that the polling mechanism can pick up existing jobs, there does not seem to be a good reason to lock them into this page until the job is complete. I have removed the "click outside" logic in this PR. We still might want to include this. I would like @aidvu's input here, as they added the original restriction. 

## Testing Instructions

There's been quite a few changes to boolean logic so there are two main things to test:

1. The state of `/hosting-config` for various plan + site type combos
2. The robustness of the Atomic transfer mechanism. See https://github.com/Automattic/wp-calypso/issues/72371 for inspiration. In short, it should be fine to go to another page and come back or do a hard refresh. The process should always complete and not get stuck. 

First, try this feature on prod and see that the process is broken and gets stuck. In my tests, it completed occasionally but mostly did not until I refreshed the page.  

Next, test viewing `/hosting-config` when you have:
 
**A Free site**: 
       * should see the upsell
       * should not see the activation banner
       * features should be masked

image
    
**a Creator plan but haven't gone Atomic**
       * You should see an activation banner but no upsell
       * Feature cards should be masked and unusable

image
 
**an Atomic site**:
        * upsell should be gone
        * The activation banner should be gone 
        * All features should be unmasked and usable
        
Screenshot 2567-01-05 at 13 56 12
      
* **Test upgrading a Free plan to Creator**
       * should initially be like **A Free site** above
       * Then, when the process completes, it should be like **an Atomic site** above

* General robustness. We are polling the server for updates and should handle a refresh. Do your best to try and break it. 

[screen-capture (9).webm](https://github.com/Automattic/wp-calypso/assets/6851384/3c4e1a89-680f-404d-8f09-bf18021ccab0)

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: client/my-sites/hosting/main.js [hunk 1]
```diff
@@ -184,207 +183,174 @@ const SidebarCards = ( { isBasicHostingDisabled } ) => {
...
+		enabled: transferRefetchEnabled,
+	} );
+
+	const isSiteAtomic =
+		transferStatus === transferStates.COMPLETE || transferStatus === transferStates.COMPLETED;
+
+	if ( endStates.includes( transferStatus ) && transferRefetchEnabled ) {
+		// the result won't chnage so no need to call the API
+		setTransferRefetchEnabled( false );
 	}
```
Comment (zaguiini) [inline client/my-sites/hosting/main.js]: Do we need a state here? I believe we can make a simple boolean variable instead. We can potentially inline this inside the `enabled` prop in `useAtomicTransferQuery` usage:

```ts
const transferRefetchEnabled = ! hasSftpFeature && ! endStates.includes( transferStatus )
```

File: client/my-sites/hosting/main.js [hunk 2]
```diff
@@ -184,207 +183,174 @@ const SidebarCards = ( { isBasicHostingDisabled } ) => {
...
-							icon="globe"
+		const failureNotice = transferStatus === transferStates.ERROR && (
+			<Notice
+				status="is-error"
+				showDismiss={ false }
+				text={ translate( 'There was an error activating hosting features.' ) }
+				icon="bug"
+			/>
+		);
+		if ( ! isSiteAtomic && hasSftpFeature && ! isTransferring && transferStatus !== undefined ) {
```
Comment (zaguiini) [inline client/my-sites/hosting/main.js]: It feels weird to have `! isTransferring && transferStatus !== undefined`. Can we consolidate these two variables, or use only one of them?

File: client/my-sites/hosting/main.js [hunk 3]
```diff
@@ -184,207 +183,174 @@ const SidebarCards = ( { isBasicHostingDisabled } ) => {
...
+	 *  1. The site does not have the Atomic feature.
+	 *  2. The site is Atomic, is not transferring, and doesn't have advanced hosting features.
+	 * Otherwise, we show the activation notice, which may be empty.
+	 */
+	const shouldShowUpgradeBanner =
+		! hasAtomicFeature || ( ! isTransferring && ! hasSftpFeature && ! isWpcomStagingSite );
+	const banner = shouldShowUpgradeBanner ? getUpgradeBanner() : getAtomicActivationNotice();
 
-		const isBusinessTrial = isMigrationTrial || isHostingTrial;
+	const isBusinessTrial = isMigrationTrial || isHostingTrial;
```
Comment (zaguiini) [inline client/my-sites/hosting/main.js]: I think we can use the selector here, just to avoid having duplicate logic around.

File: client/state/automated-transfer/constants.ts [hunk 4]
```diff
@@ -15,6 +15,7 @@ export const transferStates = {
 	BACKFILLING: 'backfilling',
 	RELOCATING: 'relocating_switcheroo',
 	COMPLETE: 'complete',
+	COMPLETED: 'completed', // there seems to be two spellings for this state
```
Comment (zaguiini) [inline client/state/automated-transfer/constants.ts:18]: 🤦

**Review by zaguiini — COMMENTED** [review]
I tested on three different tabs:

### The first one kicks off the transfer
The tab that kicked off the transfer **did not** update to reflect the successful transfer to Atomic :x:

### The second one was open before the transfer was initiated

The tab that was opened before the transfer started **did not**:
- update to reflect the transfer in progress state :x:
- update to reflected the transfer successful state :x:

### The third one was opened after the transfer was initiated

The tab that was open _while_ the transfer was in progress **did update** to reflect the successful transfer to Atomic ✅ 

---

The video below demonstrates the testing. Another thing from the video is that after I kicked off the transfer, I had to wait five seconds until I saw the transferring notice. I guess that's because of the polling interval, but could we refetch automatically after starting to transfer?

https://github.com/Automattic/wp-calypso/assets/26530524/eb826f32-d3fb-4d6e-bac2-1a91c0487b22

**Comment by danielbachhuber** [comment]
Without looking at the code too deeply, would it make sense to reconcile this implementation with https://github.com/Automattic/wp-calypso/pull/83545?

**Comment by mpkelly** [comment]
@zaguiini, thanks for the great review. There is some redundancy in the logic that I will tidy up. Some renaming or aliasing will also make the code easier to read. 

>The tab that kicked off the transfer did not update to reflect the successful transfer to Atomic ❌

This surprised me because I worked on this across a couple of days and never encountered any issues - the process was always completed. I used a single Chrome tab; otherwise, it was the same as the video. I will take another look today. 

> The second one was open before the transfer was initiated

I didn't plan to support this and even made the polling mechanism short-circuit if the first response was an end state. It's easy to support if we're cool with a polling mechanism that keeps running. 

I will address some of your comments and tag you when ready for a re-review.

File: client/my-sites/hosting/main.js (hunk 1 above)
Comment (mpkelly) [reply client/my-sites/hosting/main.js]: Thanks for suggesting this. We can't use `transferStatus` here because it comes from `useAtomicTransferQuery`, which also receives the `transferRefetchEnabled` during initialisation. If I switch to the code below (which I think is what you mean), I get a `ReferenceError: Cannot access 'transferStatus' before initialization`. 

But anyway, I think we should not disable refetching, so we can support the other scenarios you tested, like tabs that were opened before activation. 

```ts
	const { isTransferring, transferStatus } = useAtomicTransferQuery( siteSlug, {
		refetchInterval: 5000,
		enabled: endStates.includes( transferStatus ) && hasSftpFeature,
	} );
```

File: client/state/automated-transfer/constants.ts (hunk 4 above)
Comment (mpkelly) [reply client/state/automated-transfer/constants.ts:18]: Right. I ported this from your original PR and have not fully investigated it yet. When a site has SSH enabled, the API returns `complete`, which was the original enum. Maybe we don't need this. I will try to answer that before we merge this PR.

File: client/my-sites/hosting/main.js (hunk 2 above)
Comment (mpkelly) [reply client/my-sites/hosting/main.js]: Having `! isTransferring` was unnecessary, so I have removed that.

File: client/my-sites/hosting/main.js (hunk 3 above)
Comment (mpkelly) [reply client/my-sites/hosting/main.js]: I introduced `isSiteOnBusinessTrial` to simplfy things. I kept "Business" as it could add a lot of renaming noise and a revert seems likely based on current name-change performance.

**Comment by mpkelly** [comment]
[screen-capture (11).webm](https://github.com/Automattic/wp-calypso/assets/6851384/6c897446-c447-4805-8575-ee5f14e59edc)

@zaguiini and anyone else using a browser other than Chrome, please retest. The test scenarios https://github.com/Automattic/wp-calypso/pull/85937#pullrequestreview-1806313609 should all be working now. If you check the video at around 36 seconds, you will see the banner change briefly. I have found it hard to fix this issue, and I am eager to get this out as it's quite broken in prod. Maybe we can fix this in a follow-up PR?

**Comment by zaguiini** [comment]
>It's easy to support if we're cool with a polling mechanism that keeps running.

I don't think it'd hurt. Hard to imagine someone keeping that tab open forever, but even harder to think of someone that will have two HC tabs open in pre-transfer state 🤔

File: client/state/atomic-transfer/use-atomic-transfer-query.ts [hunk 5]
```diff
@@ -0,0 +1,70 @@
...
+	transferStates.FAILURE,
+	transferStates.ERROR,
+	transferStates.REVERTED,
+];
+
+export function useAtomicTransferQueryQueryKey( siteSlug ) {
+	return [ 'sites', siteSlug, 'atomic', 'transfers', 'latest' ];
+}
+
+export const useAtomicTransferQuery = (
```
Comment (zaguiini) [inline client/state/atomic-transfer/use-atomic-transfer-query.ts:33]: I wonder if we need to define this hook since several mechanisms already exist:
- [`useAtomicTransfer`](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/checkout/checkout-thank-you/marketplace/use-atomic-transfer.tsx#L16) hook
- [`WithAtomicTransfer` HOC](https://github.com/Automattic/wp-calypso/blob/trunk/client/sites-dashboard/components/with-atomic-transfer.tsx#L40) (has a different hook inside)
- [an automated transfer handler](https://github.com/Automattic/wp-calypso/blob/trunk/client/state/data-layer/wpcom/sites/automated-transfer/status/index.js#L47) (this is what `hosting/main.js` is using currently)

Seems like we could also unify these solutions.

File: client/my-sites/hosting/main.js [hunk 6]
```diff
@@ -184,207 +176,173 @@ const SidebarCards = ( { isBasicHostingDisabled } ) => {
...
-							status="is-info"
-							showDismiss={ false }
-							text={ activationText }
-							icon="sync"
-						/>
-					</>
-				);
-			}
+	const isSiteAtomic =
+		transferStatus === transferStates.COMPLETE || transferStatus === transferStates.COMPLETED;
```
Comment (zaguiini) [inline client/my-sites/hosting/main.js:207]: Does that necessarily mean the site is Atomic? There are several ways to check if the site is Atomic, not necessarily relying on the transfer status:
- `is_automated_transfer` site option
- `is_wpcom_atomic` site option (seems to be the most reliable and tied to WPCOM)

File: client/state/atomic-transfer/use-atomic-transfer-query.ts [hunk 7]
```diff
@@ -0,0 +1,70 @@
...
+			isTransferring: false,
+			transferStatus: undefined,
+		};
+	}
+
+	if ( failureReason ) {
+		// Will happen for new sites when no transfer exists: a 404 is returned
+		// by the API which becomes failureReason in React Query
+		return {
+			transferStatus: transferStates.NONE,
```
Comment (zaguiini) [inline client/state/atomic-transfer/use-atomic-transfer-query.ts:54]: I'm assuming the request returns a successful status even if there was an error during the transfer. Can we double-check it?

**Review by zaguiini — COMMENTED** [review]
All three scenarios described in my previous testing worked this time 👍

I didn't manage to reproduce the flick you reported, weird.

File: client/my-sites/hosting/main.js (hunk 6 above)
Comment (mpkelly) [reply client/my-sites/hosting/main.js:207]: The `complete[d]` state does mean the site is Atomic. If you revert the site, that also uses a transfer, which changes the status to `reverted`.  There will be no transfer if the site is Simple and never went Atomic. If an error happens, the status will be `error`. There are some other states in `transferStates` to cover other scenarios. 

There are other flags that require a different query, whereas we get the final status + interim status updates via this one query.

File: client/state/atomic-transfer/use-atomic-transfer-query.ts (hunk 7 above)
Comment (mpkelly) [reply client/state/atomic-transfer/use-atomic-transfer-query.ts:54]: The HTTP response code is `200`. However, the payload looks like this:

```json
{
    "body": {
        "code": "no_transfer_record",
        "message": "Transfer record not found for blog `227821875`",
        "data": {
            "status": 404
        }
    },
    "status": 404,
    "headers": {
        "Allow": "GET"
    }
}
```
And React Query parses it to:

```js
{
  "status": "loading",
  "fetchStatus": "fetching",
  "isLoading": true,
  "isSuccess": false,
  "isError": false,
  "isInitialLoading": true,
  "dataUpdatedAt": 0,
  "error": null,
  "errorUpdatedAt": 0,
  "failureCount": 3,
  "failureReason": {
    "path": "/sites/mk9287907.wordpress.com/atomic/transfers/latest",
    "apiNamespace": "wpcom/v2",
    "method": "GET",
    "apiVersion": "1.1",
    "query": "",
    "callback": "207c6f39-c612-448f-acde-7684177e1f48",
    "supports_args": true,
    "supports_error_obj": true,
    "supports_progress": true,
    "name": "NotFoundError",
    "statusCode": 404,
    "status": 404,
    "message": "Transfer record not found for blog `227821875`",
    "code": "no_transfer_record",
    "data": {
      "status": 404
    }
  },
  "errorUpdateCount": 0,
  "isFetched": false,
  "isFetchedAfterMount": false,
  "isFetching": true,
  "isRefetching": false,
  "isLoadingError": false,
  "isPaused": false,
  "isPlaceholderData": false,
  "isPreviousData": false,
  "isRefetchError": false,
  "isStale": true
}
```

File: client/state/atomic-transfer/use-atomic-transfer-query.ts (hunk 5 above)
Comment (mpkelly) [reply client/state/atomic-transfer/use-atomic-transfer-query.ts:33]: We can surely tidy these up. I think `use-atomic-transfer.tsx` could be simplified by using the same hook we're adding here.

I think unification can be done as a separate PR as it will only delay this longer. Daniel posted another PR we can consider for unification, too.

**Comment by mpkelly** [comment]
FYI, I am going to get these tests passed and add any more I think we need. 

Screenshot 2567-01-09 at 11 48 40

File: client/state/atomic-transfer/use-atomic-transfer-query.ts (hunk 7 above)
Comment (zaguiini) [reply client/state/atomic-transfer/use-atomic-transfer-query.ts:54]: We could revisit this as a follow-up.

File: client/state/atomic-transfer/use-atomic-transfer-query.ts (hunk 5 above)
Comment (zaguiini) [reply client/state/atomic-transfer/use-atomic-transfer-query.ts:33]: We could revisit this as a follow-up.

File: client/my-sites/hosting/main.js (hunk 6 above)
Comment (zaguiini) [reply client/my-sites/hosting/main.js:207]: Ok. I'm still skeptical about data derivation (Atomic meaning the site has transfer state), but it worked in testing, so why not try it as the feature was broken for a while.

I'm considering a case where the transfer was made a while ago and the transfer record has been cleaned up. In this case there won't be a transfer. So WDYT of adding `|| site.options.is_wpcom_atomic` as a final check at the end, just to be sure?

**Review by zaguiini — COMMENTED** [review]
I like the progress of this PR. Once the tests are here and we can verify that it will work forever with no regressions, we can go ahead and merge this.

**Comment by mpkelly** [comment]
> I like the progress of this PR. Once the tests are here and we can verify that it will work forever with no regressions, we can go ahead and merge this.

@zaguiini I fixed the tests locally, and it's building now. Take a look at my commits. The `inquiring` and `conflicts` states don't seem to be used by the server, but when I removed them, they broke the activate page, so I just added them back as end states, which is what the test expected.

**Comment by mpkelly** [comment]
I think tests are still failing because of this. I will fix it tomorrow. 

```
 console.error
      Warning: An update to InlineSupportLink inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
```

**Review by zaguiini — APPROVED** [review]
Looks good to me. Once the test passes, feel free to merge 👍

**Comment by mpkelly** [comment]
The build is still failing. 🤔 I disabled the main test file I am working with, and the build still fails. So, I'm hoping this rebase will fix it. 

Screenshot 2567-01-10 at 11 34 36

>   A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.
