### PR TITLE
Jetpack Connect: Login URL

### LINKED ISSUE #5246: Jetpack Connect: Login with a 2FA-enabled account
When you attempt to connect a Jetpack site, and during authorization, you login with a 2FA enabled WordPress account, query parameters are lost, and the authorization fails.

This happens in the new flow AND the current, existing flow!

Here are the steps to reproduce on the current flow: https://github.com/Automattic/jetpack/issues/3465

And on the new flow:
- disconnect a Jetpack site
- log out of wpcom
- while logged in to wp-admin of your Jetpack site with an account that has an a8c email, click 'Connect Jetpack'
- click 'Already have an account? Sign in'
- sign in with a 2FA account
- You should get this error when you click 'Approve'

screen shot 2016-05-06 at 7 18 03 am

props to @jeffgolenski for reporting

### PR DESCRIPTION
**Pull request by roccotripaldi**
This PR will fix #5246 

To test:
- On this branch, go to calypso.localhost:3000/jetpack/connect while logged out of WordPress.com
- Enter URL of unconnected Jetpack site to start the connection process
- On the sign up screen, click 'Already have an account? Log in'
- Login with a 2FA enabled account, and verify your 2FA
- Ensure that the connection completes after verification

CC: @johnHackworth @ebinnion

### CODE REVIEW

**Comment by beaulebens** [comment]
Following the above instructions, with this branch applied, the 2FA connection flow works for me.

File: client/state/jetpack-connect/reducer.js [hunk 1]
```diff
@@ -118,7 +118,7 @@ export function jetpackConnectAuthorize( state = {}, action ) {
 			return Object.assign( {}, state, { autoAuthorize: false } );
 		case SERIALIZE:
 		case DESERIALIZE:
-			return {};
+			return state;
```
Comment (johnHackworth) [inline client/state/jetpack-connect/reducer.js]: are we sure that we want to persist the state of the authorization? is there any reason we need to persist anything? because having in account that most of the info stored there have a quite short TTL, it can have some odd effects once it's stale

Comment (roccotripaldi) [inline client/state/jetpack-connect/reducer.js]: I think we should, because if we don't, we lose the information when someone switches between wpcom accounts, or goes from logged out to logged in.  
If we do decide to persist, we should clear the state after authorization as well.

Comment (johnHackworth) [inline client/state/jetpack-connect/reducer.js]: oh, that's a good point :+1:

**Comment by johnHackworth** [comment]
I think this is ready :shipit:

File: client/state/jetpack-connect/reducer.js (hunk 1 above)
Comment (ebinnion) [inline client/state/jetpack-connect/reducer.js]: I've already been experiencing some weird side effects that I believe are related to this.

For example: If I authorize a user, and then shortly after unlink and try to reauthorize again, I get something that looks like this:

screen shot 2016-05-17 at 2 56 43 pm

Note, the disabled button and the "Returning to your site" text. This is shown immediately to me after I try to reauthorize.

I am able to fix the issue but clearing the `calypso_store` in indexed DB and attempting to reauthorize, which leads me to believe it's due to stale state.

Comment (roccotripaldi) [inline client/state/jetpack-connect/reducer.js]: thanks for the report. I will whip up a PR that does some garbage collection.
