### PR TITLE
Layout Selector: Fix blank layout selection on existing page

### LINKED ISSUE #39174: Page Layouts: Switching to Blank Template Doesn't Work
#### Steps to reproduce
1. Starting at URL: Any Page on a site with template-first theme (TFT) (such as Maywood)
2. Click `Change Layout`
3. Select `Use Blank layout`

#### What I expected
Be switched to `Blank`, just like it happens with any other Layout

#### What happened instead
Page remains with the previous Layout and only in the right-side panel under `Page Layout` it reads `Blank`.

#### Screenshot / Video

PageLayoutsBlankBug

#### Context / Source
#dogfooding #manual-testing

### PR DESCRIPTION
**Pull request by apeatling**
Fixes #39174

#### Changes proposed in this Pull Request

* On an existing page with a layout already selected, using the sidebar to change the selected layout to "Blank" will empty out the editor. Previously when selecting blank and returning to the editor the blocks from the existing layout remained.

#### Testing instructions

* Create a new page and select a layout other than blank.
* Using the document sidebar in Gutenberg, select the "Change Layout" button.
* Select the "Blank" layout in the selector, and insert it.
* Confirm that all blocks from the previous template have been removed in the editor.

### CODE REVIEW

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js [hunk 1]
```diff
@@ -136,7 +136,16 @@ class PageTemplateModal extends Component {
 		// Only overwrite the page title if the template is not one of the Homepage Layouts
 		const title = isHomepageTemplate ? null : this.getTitleByTemplateSlug( slug );
 
-		// Skip inserting if there's nothing to insert.
+		// Check to see if this is a blank template selection
+		// and reset the template if so.
+		if ( 'blank' === slug ) {
```
Comment (michaeldcain) [inline apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: Not a blocker, but this can be run before [the `isHomepageTitle` and  `getBlocksByTemplateSlug()` bits](https://github.com/Automattic/wp-calypso/pull/39204/files#diff-a664d83ace51cb87304bf656c9e9f303R132) to return earlier, since we're not using those variables.

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js [hunk 2]
```diff
@@ -136,7 +136,16 @@ class PageTemplateModal extends Component {
...
+			this.props.insertTemplate( '', [] );
```
Comment (michaeldcain) [inline apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: Just noting that this leaves the page title to whatever is currently set - it doesn't clear it. I _think_ that's fine.

Comment (apeatling) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: I originally cleared the title, but it felt wrong, especially if the user has already added a custom title of their own.

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js (hunk 1 above)
Comment (apeatling) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: Good catch, I can move this, then I'll merge. 👍
