### PR TITLE
Purchases Page: Refactor existing code for function PurchaseMetaPrice with suggestions

### LINKED ISSUE #67133: Purchases Page: Refactor existing code for function PurchaseMetaPrice with suggestions
### Quick summary

1. Use only early returns rather than reassigning period so that it's clear what each block's priority is.
2. Don't assume that the default term is "yearly"; if we cannot figure out the term in any other way, maybe display nothing at all and/or throw an error.
3. Only use bill_period_label if none of the other conditions is found (ie: only if plan.term does not exist, etc.).
4. Add unit tests to cover different products (marketplace, plans with different terms, one time purchases, transfers, included purchases, etc.) and verify their term is what is expected.

### Steps to reproduce

Nothing to reproduce, this is related to refactor to avoid future bugs

### What you expected to happen

Nothing but code refactor

### What actually happened

This is the result of outcomes from the below Issues:
1. #64923
2. #66025

### PR DESCRIPTION
**Pull request by spraveenitpro**
#### Proposed Changes

- [x] Use only early returns rather than reassigning period so that it's clear what each block's priority is.
- [x]  Don't assume that the default term is "yearly"; if we cannot figure out the term in any other way, maybe display nothing at all and/or throw an error.
- [x]  Only use bill_period_label if none of the other conditions is found (ie: only if plan.term does not exist, etc.).
- [x]  Add unit tests to cover different products (marketplace, plans with different terms, one time purchases, transfers, included purchases, etc.) and verify their term is what is expected.

Fixes #67133

#### Testing Instructions:

* As it is a Refactor, it should not change anything so ensure that the usual functionality described below on the purchases page just works as expected.
* Goto this page `/purchases/subscriptions/:site/:purchaseID` , if the purchase is billed `per year`/`per month`/`per week`/`per day` then it should under the price column as `$price/period` where period is one of `year/month/week/day`  
* If the purchase is a domain that came free with the plan then you should see `Free with plan` under the price column 
* For DIFM products, purchase a DIFM product [from here](https://wordpress.com/do-it-for-me/), now on the purchases page, we should see the one-time fee mentioned followed by the `(one-time)` keyword 
* This PR also includes 7 tests for the various kind of products purchased, so please ensure that there are no failing tests.

### CODE REVIEW

**Comment by sirbrillig** [comment]
I think this accidentally ended up with a merge commit. It probably needs a rebase.

File: client/me/purchases/manage-purchase/purchase-meta.jsx [hunk 1]
```diff
@@ -284,52 +283,53 @@ function PurchaseMetaPrice( { purchase } ) {
 		return translate( 'Free with Plan' );
 	}
 
-	if ( purchase.billPeriodLabel ) {
-		switch ( purchase.billPeriodLabel ) {
-			case 'per year':
-				period = translate( 'year' );
```
Comment (sirbrillig) [inline client/me/purchases/manage-purchase/purchase-meta.jsx:290]: When the previous statements here were reassigning `period`, the one that took priority was the _last_ assignment, but the`getPeriod()` function returns early instead, meaning that the one that will take priority will be the _first_ assignment. So in order to preserve the same logic, you'll need to reverse the order of the conditions inside the function.

To explain better, let's say (this is an unlikely example but it could happen) that `purchase.billPeriodLabel` is `'per month'` and `plan.term` is `TERM_BIENNIALLY`. Before your changes, first `period` would be set to `'year'` on line 290, then it would be set to `'two years'` on line 307. After your changes, line 290 would return `'year'` instead, totally ignoring `plan.term`.

File: client/me/purchases/manage-purchase/purchase-meta.jsx [hunk 2]
```diff
@@ -284,52 +283,53 @@ function PurchaseMetaPrice( { purchase } ) {
...
-				break;
+		if ( isEmailMonthly( purchase ) ) {
+			return translate( 'month' );
 		}
-	}
 
-	if ( isEmailMonthly( purchase ) ) {
-		period = translate( 'month' );
-	}
+		throw new Error( 'An unexpected error occured' );
```
Comment (sirbrillig) [inline client/me/purchases/manage-purchase/purchase-meta.jsx]: Even though we hope that this never happens, it might be a good idea to give more context in this error message so that it's easier to track down if we ever see it in the wild.

Maybe something like, "Failed to get a billing term for '${productSlug}'".

File: client/me/purchases/manage-purchase/purchase-meta.jsx [hunk 3]
```diff
@@ -228,7 +228,6 @@ function PurchaseMetaPrice( { purchase } ) {
 	const translate = useTranslate();
 	const { productSlug, productDisplayPrice } = purchase;
 	const plan = getPlan( productSlug ) || getProductFromSlug( productSlug );
-	let period = translate( 'year' );
```
Comment (sirbrillig) [inline client/me/purchases/manage-purchase/purchase-meta.jsx:231]: Before this change, if no period could be found, it defaulted to `'year'`. After this change you'll get a fatal error if it could not determine the term. Was it intentional to change that behavior?

File: client/me/purchases/manage-purchase/test/purchase-meta.js [hunk 4]
```diff
@@ -0,0 +1,269 @@
...
+			<ReduxProvider store={ store }>
+				<PurchaseMeta
+					hasLoadedPurchasesFromServer={ true }
+					purchaseId={ 1 }
+					siteSlug="test"
+					isDataLoading={ false }
+				/>
+			</ReduxProvider>
+		);
+		expect( screen.getByText( /year/ ) ).toBeInTheDocument();
```
Comment (sirbrillig) [inline client/me/purchases/manage-purchase/test/purchase-meta.js]: Maybe this regexp should be more specific? Right now it will also match `two year`. How about something like `/\/ year\b/`?

File: client/me/purchases/manage-purchase/test/purchase-meta.js [hunk 5]
```diff
@@ -0,0 +1,269 @@
...
+			<ReduxProvider store={ store }>
+				<PurchaseMeta
+					hasLoadedPurchasesFromServer={ true }
+					purchaseId={ 1 }
+					siteSlug="test"
+					isDataLoading={ false }
+				/>
+			</ReduxProvider>
+		);
+		expect( screen.getByText( /month/ ) ).toBeInTheDocument();
```
Comment (sirbrillig) [inline client/me/purchases/manage-purchase/test/purchase-meta.js]: Same here. This could match the string `bimonthly` (even though that's not something we have right now). Can it be more specific?

File: client/me/purchases/manage-purchase/test/purchase-meta.js [hunk 6]
```diff
@@ -0,0 +1,269 @@
...
+			<ReduxProvider store={ store }>
+				<PurchaseMeta
+					hasLoadedPurchasesFromServer={ true }
+					purchaseId={ 1 }
+					siteSlug="test"
+					isDataLoading={ false }
+				/>
+			</ReduxProvider>
+		);
+		expect( screen.getByText( /week/ ) ).toBeInTheDocument();
```
Comment (sirbrillig) [inline client/me/purchases/manage-purchase/test/purchase-meta.js]: Same here. How about `/\/ week\b/`?

File: client/me/purchases/manage-purchase/test/purchase-meta.js [hunk 7]
```diff
@@ -0,0 +1,269 @@
...
+			<ReduxProvider store={ store }>
+				<PurchaseMeta
+					hasLoadedPurchasesFromServer={ true }
+					purchaseId={ 1 }
+					siteSlug="test"
+					isDataLoading={ false }
+				/>
+			</ReduxProvider>
+		);
+		expect( screen.getByText( /day/ ) ).toBeInTheDocument();
```
Comment (sirbrillig) [inline client/me/purchases/manage-purchase/test/purchase-meta.js]: Same here.

File: client/me/purchases/manage-purchase/test/purchase-meta.js [hunk 8]
```diff
@@ -0,0 +1,269 @@
...
+				<PurchaseMeta
+					hasLoadedPurchasesFromServer={ true }
+					purchaseId={ 1 }
+					siteSlug="test"
+					isDataLoading={ false }
+				/>
+			</ReduxProvider>
+		);
+
+		//screen.debug();
```
Comment (sirbrillig) [inline client/me/purchases/manage-purchase/test/purchase-meta.js]: This looks like a debugging line left in accidentally.

File: client/state/purchases/selectors/get-purchases.js [hunk 9]
```diff
@@ -10,6 +10,6 @@ import 'calypso/state/purchases/init';
  * @returns {Array} Purchases
  */
 export const getPurchases = createSelector(
-	( state ) => createPurchasesArray( state.purchases.data ),
-	( state ) => [ state.purchases.data ]
```
Comment (sirbrillig) [inline client/state/purchases/selectors/get-purchases.js]: Even though there's nothing wrong with it, we can probably remove this change (I think) now that your tests are providing `purchases.data`. That will simplify the diff.

**Review by sirbrillig — COMMENTED** [review]
Great work on those tests. I just have a few suggestions.

File: client/me/purchases/manage-purchase/purchase-meta.jsx (hunk 1 above)
Comment (spraveenitpro) [reply client/me/purchases/manage-purchase/purchase-meta.jsx:290]: That makes sense. Let me have this done!.

File: client/me/purchases/manage-purchase/purchase-meta.jsx (hunk 3 above)
Comment (spraveenitpro) [reply client/me/purchases/manage-purchase/purchase-meta.jsx:231]: Yes, you gave that as a suggestion [in this PR](https://github.com/Automattic/wp-calypso/pull/67021#pullrequestreview-1089313385)

`Don't assume that the default term is "yearly"; if we cannot figure out the term in any other way, maybe display nothing at all and/or throw an error.`

Based on the above suggestions, I decided to display an error. Let me know if that behaviour needs to be changed. @sirbrillig

Comment (sirbrillig) [reply client/me/purchases/manage-purchase/purchase-meta.jsx:231]: Ah, right. I forgot about that. And it's even written in the PR description!

File: client/me/purchases/manage-purchase/test/purchase-meta.js (hunk 4 above)
Comment (spraveenitpro) [reply client/me/purchases/manage-purchase/test/purchase-meta.js]: Completely Agreed

**Review by sirbrillig — COMMENTED** [review]
This looks really good! I don't have time to fully test it right now but I'll take care of that next week. Nice work!

**Review by sirbrillig — APPROVED** [review]
The code looks good and in my testing, the price rendered correctly!

**Comment by sirbrillig** [comment]
This was [reverted](https://github.com/Automattic/wp-calypso/pull/70522) because it was causing [errors in non-EN languages](https://github.com/Automattic/wp-calypso/issues/70515). The reason is subtle. It's not actually a problem with this PR; the bug is already present in the code but it was exposed by this PR.

One of the conditions in `PurchaseMetaPrice` uses the `billPeriodLabel` to find out what term to display:

https://github.com/Automattic/wp-calypso/blob/8c8dd24c263f77d06a31198bb1acc6d4ddaf1a54/client/me/purchases/manage-purchase/purchase-meta.jsx#L287-L302

However, this will _never work in non-en languages_ because the `billPeriodLabel` is localized. The result is that products which do not match the other conditions in the component will fall back to the default term of `yearly`:

https://github.com/Automattic/wp-calypso/blob/8c8dd24c263f77d06a31198bb1acc6d4ddaf1a54/client/me/purchases/manage-purchase/purchase-meta.jsx#L231

This has apparently gone unnoticed ever since the bug was introduced in https://github.com/Automattic/wp-calypso/pull/65006 earlier this year.

In this PR, we intentionally removed the fallback and replaced it with a thrown error to prevent bugs exactly like this from being possible. However, since it only occurred in non-en locales and only for very specific products, we did not catch it while testing.

We can re-create this PR and find a new way to handle Marketplace products.
