### PR TITLE
Plans (Storage): Enable storage selection for current plan, and other fixes/refactors

### LINKED ISSUE #90905: Plans Grid: Storage Add-on Dropdown not displaying for spotlight plan
### Quick summary

There used to be a dropdown that allowed users to purchase storage add-ons for creator / entrepreneur spotlight plans in the plans grid. Something changed and the dropdown is no longer rendered.

Was this intentional? If not, the dropdown should be rendered again.

Screenshot 2024-05-13 at 2 30 44 PM

### Steps to reproduce

1. Ensure no storage add-ons have been applied to the site.
2. If the site doesn't have a creator or entrepreneur plan, purchase one.
3. Navigate to `/plans`
4. Verify that the spotlight creator / entrepreneur plan doesn't render a storage add-on dropdown, and only shows a storage capacity label of "50GB"

### What you expected to happen

There should be a dropdown in the spotlight plan which allow the user to purchase storage add-ons for their current plan.

### What actually happened

No dropdown is rendered

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### LINKED ISSUE #90947: Plans: Plan price not updated when storage option selected if a storage add-on previously purchased
### Quick summary

When having purchased a storage add-on (e.g. 50GB) and going to `/plans/[site]`, then selecting any storage option for one of the higher tier plans will not update the price of the respective plan.

Screenshot 2024-05-21 at 5 47 12 PM

### Steps to reproduce

1. Create a site on the `Creator` plan
2. Go to `/add-ons` and purchase a 50GB storage upgrade
3. Go to `/plans/[site]` and select any of the options in the dropdown for the Entrepreneur plan
4. Confirm that the price of the Entrepreneur plan no longer reflects the change

### What you expected to happen

Either the storage option NOT being available for selection (if any issues with it) or the price of the Entrepreneur (higher tier) plan to reflect the storage option's price.

### What actually happened

The price did not get updated

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### LINKED ISSUE #90949: Plans: Storage volume rendered for spotlight plan not reflecting purchased storage
> @jeyip do we have an issue for the storage shown for spotlight/current plan not reflecting the real/actual storage after additional storage purchased? e.g. this is what's shown for a site on a Creator plan that I just purchased additional 150GB storage through the add-ons page (shouldn't it be `200`, and not `50`?):
> 
> Screenshot 2024-05-21 at 3 49 41 PM

_Originally posted by @chriskmnds in https://github.com/Automattic/wp-calypso/issues/90664#issuecomment-2122569325_

### LINKED ISSUE #91047: Plans (Storage): Wrong values and broken CTA on upgrade plan in admin when storage previously purchased
### Quick summary

When purchasing one of the storage add-ons for a `Creator` site and going to `/plans/[site]`, the values shown in the storage dropdown for the upgrade plan (e.g. Entrepreneur) will show wrong/ambiguous storage volumes and lead to malformed CTA (with items in cart not permissible for purchase).

With a site on Creator + 50GB additional storage purchased: (`100GB` selection should really be `150GB`, and `150GB` should be `200GB`):

Screenshot 2024-05-23 at 2 33 02 PM

This is due to a couple of reasons and also points to some intricacies in the implementation:

1. There is a presumably hard restriction that only a single storage purchase is permissible (so storage selection shouldn't really be shown in this case). This needs some clarity, as the error shown during checkout is that additional storage should be higher than what was previously purchased.
2. Irrespective of restriction, the storage upgrade volume rendered for the selections should be an addition/accumulation over the site's storage, not a static value. This can easily manifest itself when we allow selections for comparison, or loosen the restriction, or extend the storage limits on a site (so purchasing an additional 100GB over previous 50GB is allowed), or in regressions like the above spilling into the UI

### Steps to reproduce

1. Create a site on the Creator plan
2. Go to `/add-ons/[site]` and purchase a 50GB storage upgrade
3. Go to `/plans/[site]` and select any of the options in the dropdown for the Entrepreneur plan

### What you expected to happen

1. No storage selections be shown for upgrading to Entrepreneur
2. Whatever renders to reflect an addition to existing storage of a site, not static/default values

### What actually happened

Wrong values rendered altogether: "upgrade to 100GB" when the site's already on 100GB

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by chriskmnds**
Fixes https://github.com/Automattic/wp-calypso/issues/90905 (start of the pit)
Fixes https://github.com/Automattic/wp-calypso/issues/90947
Fixes https://github.com/Automattic/wp-calypso/issues/90949
Fixes https://github.com/Automattic/wp-calypso/issues/91047
Based on https://github.com/Automattic/wp-calypso/pull/90989

## Proposed Changes

- Enables showing the storage dropdown selector for the current plan in spotlight
- Renders the combined storage volume for the site/plan when a storage add-on has been purchased
- Renders the combined storage volume in the dropdown selections (as a fallback in case of similar regressions to https://github.com/Automattic/wp-calypso/issues/91047)
- Some refactors to clean up the code a bit, start moving things into their own folder (there are enough pieces to storage logic that merit its own little space in the package). We will follow-up with more refactors down the line, consolidate and centralise more of the logic, avoid repeating things across Comparison & Features Grid, etc.

### Media

Screenshot 2024-05-30 at 10 15 44 AM

Screenshot 2024-05-30 at 10 11 59 AM

Screenshot 2024-05-30 at 10 13 12 AM

### Needs Clarity

The remaining parts (to my mind) that need clarity:

1. I am going by the assumption that we show the updated/full storage for the site under the current plan after a purchase upgrade. This should align with what we want to do with the new Spotlight designs: p9Jlb4-bSl-p2
2. Should the price of the plans in the grid when a storage upgrade has been purchased reflect the new overall cost to the user? Before a purchase, we update the yearly prices in the grid to reflect the additional cost of extra storage - should this not be the case after the purchase? e.g.:

**On current plan:**

with the 100GB storage shown, should the price be `70.96` and not `25`?

Screenshot 2024-05-23 at 3 07 01 PM

**On upgrade plan (Entrepreneur):**

with the 100GB storage shown, should the price be `90.96` and not `45`?

Screenshot 2024-05-23 at 3 11 08 PM

## Why are these changes being made?

Addresses all of https://github.com/Automattic/wp-calypso/issues/90905, https://github.com/Automattic/wp-calypso/issues/90947, https://github.com/Automattic/wp-calypso/issues/90949, https://github.com/Automattic/wp-calypso/issues/91047

## Testing Instructions

- Go to `/start/plans` and confirm storage selection and rendering works as before
- Create a site and go to `/plans/[site]` and confirm the same
- Confirm the current/spotlight plan allows for selecting/purchasing additional storage
- Purchase 50GB additional storage and revisit `/plans/[site with extra storage]`
    - Confirm the media above: 
        - the total storage reflected in the storage label rendered for plans that allow storage upgrades
        - storage selection no longer enabled
        - (optional - the fallback) remove the `storageAddOn.purchased` constraints from the code and reload. The selectors for current and Entrepreneur plans should show selection that reflects what the site would have upgraded to, as outlined in https://github.com/Automattic/wp-calypso/issues/91047 (so 150GB and 200GB, instead of 100GB and 150GB)

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by chriskmnds** [comment]
@jeyip @southp can we please give this a thorough round of testing to see if it's heading in the right direction? Lots more refactors can come on top, but if the functionality is improved, then we may consider merging some version.

One possible venue (depending on what we decide in the `Needs Clarity` section, would be to show the extended storage description in the label e.g. with the green letters, if the plan price is going to reflect the additional cost after purchase e.g. instead of `100GB` (as in the media above), to show `100GB + 45.96/month` (like in the dropdown options) - assuming we update the prices to be `90.96`, etc.

**Comment by southp** [comment]
Thanks for working on this, @chriskmnds . People say that one stone two birds is good, we've got 4 birds(bugs) here :D 

> I am going by the assumption that we show the updated/full storage for the site under the current plan after a purchase upgrade. This should align with what we want to do with the new Spotlight designs: p9Jlb4-bSl-p2

Sounds good to me. To close the loop here, I've left similar sentiment here: https://github.com/Automattic/wp-calypso/issues/90949#issuecomment-2129109272. 

> Should the price of the plans in the grid when a storage upgrade has been purchased reflect the new overall cost to the user? Before a purchase, we update the yearly prices in the grid to reflect the additional cost of extra storage - should this not be the case after the purchase? 

There is a related issue here: https://github.com/Automattic/wp-calypso/issues/86154, just that the behavior seems to have changed at some points. Given the cited new design spotlight design above, showing a combined price makes the most sense to me.

**Comment by southp** [comment]
Hmm, wait. one more case I recalled is to toggle to the longer term when we have purchased a storage add-on:

https://github.com/Automattic/wp-calypso/assets/1842898/cd8a7d24-ebce-4e5b-b2a9-885b210885f6

In this case, the total storage is incorrectly resetted to 50G. However, what's more problematic is that I don't really know how we can ever combine the price in the reasonable way since the storage add-ons are only available in the annual term :/ @niranjan-uma-shankar also once raised that here: Automattic/martech#2614.

For the time being, maybe showing them as a separate price, e.g. something like "+x / month, billed annually" along side the storage volume label. It's not pretty, but at least it conveys correct info. @vinimotaa @chriskmnds what do you think? 🤔

**Comment by chriskmnds** [comment]
> For the time being, maybe showing them as a separate price, e.g. something like "+x / month, billed annually" along side the storage volume label. It's not pretty, but at least it conveys correct info. @vinimotaa @chriskmnds what do you think? 🤔

@southp  I'm definitely on board with that, for the time being. It's also a little weird to be showing the updated prices only for the "storage-upgradable" plans (cause that's kinda the reality - you cannot have more storage on the others, so it may even be more confusing to be updating **all** the plan prices, as the alternative).

**Comment by chriskmnds** [comment]
> In this case, the total storage is incorrectly resetted to 50G. However, what's more problematic is that I don't really know how we can ever combine the price in the reasonable way since the storage add-ons are only available in the annual term :/

Good point @southp. I feel "not resetting it to 50GB" (without additional fixes) would be equally incorrect. You are looking at 2-year price/features comparison, and the storage is technically a 1-year concern. So it either needs be weirdly smart about it (and equally confusing to the user) or clarified down to detail that the "100GB, plus whatever cost" is only for the first year. So something like `50GB (plus 50GB for the first year at $123/month)`, etc.

**Comment by jeyip** [comment]
Hi folks! Sorry I missed this on Friday. Going to check out the PR and respond after dinner tonight 🙂

**Comment by jeyip** [comment]
Testing out the branch now 👀

**Comment by jeyip** [comment]
## Testing
### Requirements

For each of the flows listed below:
- Go to /start/plans and confirm storage selection and rendering works as before
- Create a site and go to /plans/[site] and confirm the same
- Confirm the current/spotlight plan allows for selecting/purchasing additional storage
- Purchase 50GB additional storage and revisit /plans/[site with extra storage]

Flows:
- [x] /start
- [ ] /setup/newsletter
- [x] /plans

### Browsers
- [x] Chrome

**Comment by jeyip** [comment]
I agree with what has been laid out so far between Christos and James.

> would be to show the extended storage description in the label e.g. with the green letters, if the plan price is going to reflect the additional cost after purchase e.g. instead of 100GB (as in the media above), to show 100GB + 45.96/month (like in the dropdown options) - assuming we update the prices to be 90.96, etc.

Yes making a distinction between the cost of the add-on and the cost of the plan for spotlight plans makes a lot of sense to me, especially if it aligns with future designs.

> Should the price of the plans in the grid when a storage upgrade has been purchased reflect the new overall cost to the user? Before a purchase, we update the yearly prices in the grid to reflect the additional cost of extra storage - should this not be the case after the purchase?

The concern to me is the user mistakenly believing that they have to pay $x more for the plan because of their add-on. Not sure if this is the best way to handle things, but I wonder if we could also this update the storage label in this case. Something denoting that the upgraded storage would be carried over to their new plan

File: packages/plans-grid-next/src/components/storage/hooks/use-storage-string-from-feature.ts [hunk 1]
```diff
@@ -0,0 +1,91 @@
+import {
+	FEATURE_1GB_STORAGE,
+	FEATURE_6GB_STORAGE,
+	FEATURE_13GB_STORAGE,
+	FEATURE_50GB_STORAGE,
+	FEATURE_200GB_STORAGE,
+	FEATURE_50GB_STORAGE_ADD_ON,
```
Comment (jeyip) [inline packages/plans-grid-next/src/components/storage/hooks/use-storage-string-from-feature.ts:7]: `NB:`

It's unfortunate that my initial technical implementation of add-ons relying on feature slugs is spreading a bit more 😕

In the past, we've talked about `FEATURE_50GB_STORAGE_ADD_ON` and `FEATURE_100GB_STORAGE_ADD_ON` being a misnomer. The add-on is _not_ a feature, and at the very least, it should just be `50GB_STORAGE_ADD_ON`. I know there's a lot more to refactor beyond that, but since we're starting to taking a closer look at this part of the code again, let me know if you think renaming might help with any confusion. I'm happy to set up a PR if we'd like.

Comment (chriskmnds) [reply packages/plans-grid-next/src/components/storage/hooks/use-storage-string-from-feature.ts:7]: Good thinking @jeyip 

Let's come back to this later and figure out the best way forward. I'm wondering if we can skip a "meaningful" slug for this altogether and just go with how storage add-ons work (a combination of `PRODUCT_1GB_SPACE` & `quantity`). So in a way finding a solution that won't need to enumerate/define the options via slugs. Then for the state store we could just store the index of the item selected, not the slug (and whether add-on).

Comment (chriskmnds) [reply packages/plans-grid-next/src/components/storage/hooks/use-storage-string-from-feature.ts:7]: > It's unfortunate that my initial technical implementation of add-ons relying on feature slugs is spreading a bit more 😕

Not at all! I can only feel sympathetic seeing the complexity around this. The problem is deep, and we also didn't exactly have time to "breathe" at the time. 😎

**Comment by jeyip** [comment]
I finally got some other time sensitive work off my plate p1717030570883619/1715880961.253219-slack-C06QNEKS4NN :D Going to take a cloesr look at this PR tonight

File: packages/plans-grid-next/src/components/comparison-grid/index.tsx [hunk 2]
```diff
@@ -638,18 +667,7 @@ const ComparisonGridFeatureGroupRowCell: React.FunctionComponent< {
...
-							storageOptions={ gridPlan.features.storageOptions }
-							onStorageAddOnClick={ onStorageAddOnClick }
-							priceOnSeparateLine
-						/>
-					) : (
-						<StorageButton className="plan-features-2023-grid__storage-button" key={ planSlug }>
-							{ getStorageStringFromFeature( defaultStorageOption?.slug || '' ) }
-						</StorageButton>
-					) }
+					{ storageJSX }
```
Comment (jeyip) [inline packages/plans-grid-next/src/components/comparison-grid/index.tsx:647]: Thanks for making the nested conditionals more readable 👍

**Comment by chriskmnds** [comment]
> I finally got some other time sensitive work off my plate p1717030570883619/1715880961.253219-slack-C06QNEKS4NN :D Going to take a cloesr look at this PR tonight after dinner

Thanks @jeyip @southp

I pushed some changes that will/should handle showing the added cost next/under the label when the storage is upgraded (but keep the plan price the same). Some images:

Screenshot 2024-05-30 at 10 11 59 AM

Screenshot 2024-05-30 at 10 13 12 AM

The changes don't fiddle with the 2/3-year plans situation. The storage gets reset in that case and is not selectable. We'll need to revisit and decide on that. For an intermediate solution, we could ship the same functionality for those. I think best to address those in a separate PR. Also the new designs for spotlight will need to address that one way or another.

File: packages/plans-grid-next/src/components/comparison-grid/index.tsx (hunk 2 above)
Comment (chriskmnds) [reply packages/plans-grid-next/src/components/comparison-grid/index.tsx:647]: doing a lot more of this in https://github.com/Automattic/wp-calypso/pull/91196 and likely others on top

**Review by jeyip — COMMENTED** [review]
After taking a closer look at the PR, everything seems reasonable so far, and I don't have any concerns with the direction the code is going. I also appreciate the general improvements to readability along the way.

I see that recent changes were pushed with regards to storage label pricing. I will test these updates first thing in the morning 🙂

**Comment by chriskmnds** [comment]
@jeyip Rebased and updated. So it should be all ready now (we did some refactors to storage-options component in trunk). worth double-checking the mobile views. I'm done with this for today - will carry on tomorrow 😅

File: packages/plans-grid-next/src/components/storage/hooks/use-storage-string-from-feature.ts [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+		case FEATURE_1GB_STORAGE:
+			return translate( '1 GB' );
+		case FEATURE_6GB_STORAGE:
+			return translate( '6 GB' );
+		case FEATURE_13GB_STORAGE:
+			return translate( '13 GB' );
+		case FEATURE_50GB_STORAGE:
+			/**
+			 * TODO: Don't do this here. Diverge and show the version with the green pricing next
+			 */
```
Comment (chriskmnds) [inline packages/plans-grid-next/src/components/storage/hooks/use-storage-string-from-feature.ts:51]: Fine now. we may come back to this component later

File: packages/plans-grid-next/src/components/storage/components/plan-storage-label.tsx [hunk 4]
```diff
@@ -0,0 +1,72 @@
...
+import { usePlansGridContext } from '../../../grid-context';
+import useIsLargeCurrency from '../../../hooks/use-is-large-currency';
+import useStorageStringFromFeature from '../hooks/use-storage-string-from-feature';
+
+interface Props {
+	storageOption: StorageOption;
+	planSlug: PlanSlug;
+}
+
+const ELIGIBLE_PLANS_FOR_STORAGE_UPGRADE = [ PLAN_BUSINESS, PLAN_ECOMMERCE ];
```
Comment (chriskmnds) [inline packages/plans-grid-next/src/components/storage/components/plan-storage-label.tsx:20]: this needs to be revisited and centralized differently. it might actually just be redundant actually

**Comment by jeyip** [comment]
## Testing
### Requirements

For each of the flows listed below:
- Verified header price and billing timeframe price when a storage add-on is selected
- Verified large currency formatting with IDR
- Verified that storage add-ons are only available for yearly plans
- Ensured that a plan could be purchased
- Spot checked desktop and mobile
- Spot checked the spotlight plan on the /plans page

Flows:
- [x] /start
- [ ] /setup/free
- [ ] /start/onboarding-pm
- [ ] /plans

### Browsers
- [x] Chrome

**Comment by jeyip** [comment]
Rerunning what appear to be flakey E2E specs

**Review by jeyip — APPROVED** [review]
Tests well and behaves as discussed in the PR description -- we can get these changes into production and continue building on work here in follow-up PRs

**Comment by chriskmnds** [comment]
Thank you again @jeyip ! I will ship this now and move things into follow-ups. 

> This is already present in production. IDR header pricing overflows borders in comparison grid at certain screen resolutions when storage add-on is selected ( Ex. screen width of 883 px in the /start page )

Interesting. Not sure what to do about this now since the price text is already reduced. We could explore a couple of options (switch the view to tablet or otherwise even smaller text 😬 )

> Not necessary to resolve right now, and something we can easily update in a future PR. There appears to be a lot of extra empty space for the spotlight plan dropdown menu. It seems like we could let menu width be dynamically sized by its content

Noticed. I'll port this to a new issue and work it out in a follow up.

I'm just glad it works at some level right now. More to come! I'll take this up as a bit of a side project to keep improving.

**Comment by chriskmnds** [comment]
>> Not necessary to resolve right now, and something we can easily update in a future PR. There appears to be a lot of extra empty space for the spotlight plan dropdown menu. It seems like we could let menu width be dynamically sized by its content
> 
> Noticed. I'll port this to a new issue and work it out in a follow up.

@jeyip https://github.com/Automattic/wp-calypso/issues/91333

**Comment by niranjan-uma-shankar** [comment]
@chriskmnds @jeyip Since there's ongoing work to improve the Storage dropdown presentation, I'm bumping to notice that the storage dropdown is missing on the comparison grid in the offerings experiment `treatment` view. Check pau2Xa-5Sh#comment-15574 for details.
