### PR TITLE
Pre-commit: Do not prettier + add dirty files

### LINKED ISSUE #17039: Do not modify the staging area on commit
When using the new `/** @format */` facility to format files on commit, _all changes in staged files will be wholesale commited_.

Within [`pre-commit-hook.js`](https://github.com/Automattic/wp-calypso/blob/e178f2fa6e2948f3b08b060bd644033ce42de04c/bin/pre-commit-hook.js#L55) is the following, which _adds these files to your commit_:

```js
execSync( `git add ${ file }` );
```

I do my best to keep a clean and coherent commit history, and with the power of `git` I can usually do a pretty good job. That doesn't mean the way I actually build things is just as clean. It usually isn't.

That means I often patch my commits together with `git add -p` or `git reset -p` until I feel that they are coherent and represent a logical step.

Here are two commits that I crafted recently, only to have my care and attention to detail ignored by the pre-commit hook:
* 154605862deb5284aa15ac5319123bc407b3c4e8
* f6bc33a3bbe6c432dbc3f8418be63c607965dc7f

I feel pretty strongly that native `git` behavior should not be significantly modified by our commit hooks, and we violate that right now.

The hook was introduced in #16394 

#### Steps to reproduce
1. Open a file with `/** @format */` directive.
1. Make 2 changes in the file.
1. Stage one of the changes (`git add -p`).
1. Commit `git commit -m 'test'`.
1. Notice that the file is now clean because all of the changes were committed.

#### What I expected

Staged changes are committed, unstaged changes are not.

#### What happened instead

Complete files are committed, regardless of staging.

/cc @samouri

### PR DESCRIPTION
**Pull request by sirreal**
When a prettier flagged file is partially staged and commited, the pre-commit hook will run prttier and commit the whole file (#17039). This breaks workflows that rely on partial commits.

This PR includes the following changes:

* Do not take action if `prettier` does not need to format files.
* Do not `prettier` or `git add` dirty files.
* ~Minor: extract unified `shouldFormat` utility function from `pre-commit` and `reformat-files`~ moved to #18991 

~If there is significant discussion about the approach I've take to ignore dirty files for the pre-commit `prettier`, I'm happy to factor out the other bits into a separate PRs.~

## Testing
1. Make some changes to the repo (at least two independent changes to 1 file).
1. Partially commit the file `git add -p $FILE`, pick `y`es and `n`o for different patches. You may need to `s`plit them if the changes are adjacent.
1. Make changes that adhere to prettier formatting and that _do not_. Dirty files that are already prettier formatted do not cause problems.
1. run `git ci`.
1. When the pre-commit script runs on your partially staged (dirty) file, does it abort the `prettier` + `git add`? 👍 

## Feedback 🙏 

* How's the messaging? Colors?
* Do we want to auto-run `prettier`, but not commit? It seems safest just to not touch the file.
* Rather than a per file message, should we should a big warning at the end like:
  > You're have committed the following files which are flagged for auto-formatting but *are not* correctly formatted and cannot be auto-formatted by the commit because they have unstaged changes:
  > * …
  > 
  > Try running `npm run reformat-files` and try ammending the previous commit before you push

Fixes #17039

### CODE REVIEW

File: bin/pre-commit-hook.js [hunk 1]
```diff
@@ -20,45 +28,51 @@ console.log(
...
-
 // run prettier for any files in the commit that have @format within their first docblock
 files
-	.map( file => path.join( __dirname, '../', file ) )
-	.forEach( file => {
-		const text = fs.readFileSync( file, 'utf8' );
+	.map( file => [ file, path.join( __dirname, '../', file ) ] )
+	.forEach( ( [ file, fullPath ] ) => {
+		if ( dirtyFiles.has( fullPath ) ) {
+		}
```
Comment (dmsnell) [inline bin/pre-commit-hook.js]: is this empty block a typo?

**Comment by dmsnell** [comment]
Interesting problem - we definitely shouldn't be committing an entire file when we've explicitly instructed `git` not to. Seems like that's a good win either way.

Can you help me understand - in this PR are we reading and processing changed files in a way we weren't previously? I'd hate to accidentally slow down the commit process when we maybe don't need to. Maybe it's just the shuffle of code _and_ the new behaviors which is confusing me - it might be good to propose the refactorings first _then_ the new behaviors…

Good catch and good work - that must have been frustrating to try and figure out why your partial commits were broken!

File: bin/pre-commit-hook.js [hunk 2]
```diff
@@ -20,45 +28,51 @@ console.log(
...
-};
-
 // run prettier for any files in the commit that have @format within their first docblock
 files
-	.map( file => path.join( __dirname, '../', file ) )
-	.forEach( file => {
-		const text = fs.readFileSync( file, 'utf8' );
+	.map( file => [ file, path.join( __dirname, '../', file ) ] )
+	.forEach( ( [ file, fullPath ] ) => {
+		if ( dirtyFiles.has( fullPath ) ) {
```
Comment (jsnajdr) [inline bin/pre-commit-hook.js]: Why do you need to compare the full paths here? Even the relative paths (i.e., direct output of `git diff`) should be comparable to each other, shouldn't they?

File: bin/pre-commit-hook.js (hunk 1 above)
Comment (sirreal) [reply bin/pre-commit-hook.js]: Yes! Cleaned up, thanks!

**Comment by sirreal** [comment]
I've extracted the `shouldFormat` part of this PR to #18991 which should make the relevant parts of this PR clearer.

File: bin/pre-commit-hook.js (hunk 2 above)
Comment (sirreal) [reply bin/pre-commit-hook.js]: In 84fe0dd I made a change to parse `git diff` in one consistent way, always to absolute paths.

You're right that it shouldn't matter whether path comparison is relative or absolute as long as they're the same.

I've gone with absolute paths everywhere because that's what was used for the file reading/writing. Some absolute path lookup could be avoided, but I suspect that has little benefit.

**Comment by samouri** [comment]
@sirreal: is it possible to run prettier on just the staged portion of the file?

**Comment by sirreal** [comment]
> is it possible/desirable to run prettier on just the staged portion of the file?

I don't think so. I've partially `prettier`ed files using `vim-prettier`, but it treats the part as if it were a complete document so indentation starts at 0, the `/** @format */` is added at the start of the section, etc. Not ideal. I don't know whether prettier has any smart way to _parse_ a whole file but only operate on a small part.

**Comment by jsnajdr** [comment]
> is it possible/desirable to run prettier on just the staged portion of the file?

It would probably be doable if we really wanted to, but I'd rather avoid it. It has a potential to leave the unstaged changes in a conflicting state -- messing up with my carefully crafted patches.

**Comment by sirreal** [comment]
@dmsnell Sorry, I didn't get back to all your feedback before 🙂 

> in this PR are we reading and processing changed files in a way we weren't previously?

I think the tradeoffs here should make the pre-commit quicker overall:
* ➕  There is an additional `git diff` and processing to check dirty files.
* ➖  We skip writes when prettier output has no changes (lifted from `reformat-files`, this improvement is independent).
* ➖  Skip executing `prettier` and subsequent writes for dirty files.

At the moment, this PR _does_ continue to read files that are known to be dirty to check for the `@format` flag and show a message. This could be skipped if we don't want to show a message for dirty files that should have prettier applied.

> I'd hate to accidentally slow down the commit process when we maybe don't need to. Maybe it's just the shuffle of code and the new behaviors which is confusing me - it might be good to propose the refactorings first then the new behaviors…

It should be clearer what's relevant in this PR now, if anything I'd expect this to be quicker and still has some room for improvement if needed.

**Comment by sirreal** [comment]
> I wish that the message […] showed just the project path `client/my-sites/...`

@jsnajdr I'm not sure why the path operation was in there at all, I removed it in 40af97b and just let everything use relative paths and it seems to work fine and report things relative to the repo root. Please give the change a test run both from the root and different subdirectories.

@samouri Does 40af97b seem safe?

**Comment by jsnajdr** [comment]
@sirreal I just tested the relative path version and it works great -- even if my cwd is different from the project root. :ship:

**Comment by sirreal** [comment]
Thanks for the feedback everyone!
