### PR TITLE
Prevent getSiteFragment from thinking plugin name is site

### LINKED ISSUE #42971: Plugin search defaults to site ID when plugin starts with a number
When trying to access plugins in https://wordpress.com/plugins, plugins that start with a number in their name/URL are taken as the site ID number and therefore the plugin doesn't load. 

#### Steps to reproduce

1. Starting at URL: https://wordpress.com/plugins
2. Search for plugins like:
404 to 301 (https://wordpress.org/plugins/404-to-301/) or 404 to Homepage (https://wordpress.org/plugins/404-to-homepage/). 

It will redirect it to (respectively):
https://wordpress.com/plugins/404-to-301?site=404
https://wordpress.com/plugins/404-to-homepage?site=404

3. You will notice the URL flickers and the plugin page doesn't load

#### What I expected
 To access the plugin site https://wordpress.com/plugins/404-to-homepage
or https://wordpress.com/plugins/404-to-301

#### Screenshot / Video

https://d.pr/v/Ct0aou
https://d.pr/v/9cUHm4

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

This fixes a bug which caused calypso routing to believe that plugin names which start with a number are site IDs.

The underlying cause is that when looking for a site ID in the URL, `getSiteFragment` uses `parseInt` on the url fragment before testing to see if it's an integer. However, `parseInt('404-hello')` will return `404`, so this test is not very helpful.

In this PR I add a regexp test as well that looks to see if the url fragment contains any non-numeric characters before letting us test the number.

#### Testing instructions

- Visit http://calypso.localhost:3000/plugins/404-to-301
- Make sure the page loads successfully and you see a single plugin
- Visit http://calypso.localhost:3000/plugins
- Make sure the page loads successfully and you see a list of plugins
- Visit http://calypso.localhost:3000/plugins/example.com (but replace example.com with your site id)
- Make sure the page loads successfully and you see a list of plugins

Fixes https://github.com/Automattic/wp-calypso/issues/42971

### CODE REVIEW

File: client/lib/route/path.ts [hunk 1]
```diff
@@ -58,9 +58,12 @@ export function getSiteFragment( path: URLString ): SiteSlug | SiteId | false {
 
 	// Check last and second-to-last piece for numeric site ID
 	for ( let i = 2; i > 0; i-- ) {
-		const piece = parseInt( pieces[ pieces.length - i ], 10 );
-		if ( Number.isSafeInteger( piece ) ) {
-			return piece;
+		const piece = pieces[ pieces.length - i ];
+		// We can't just do parseInt because some string look like numbers, eg: '404-hello'
+		const isNumber = String( piece ).match( /\D/ ) === null;
```
Comment (jsnajdr) [inline client/lib/route/path.ts:63]: I think the following (equivalent in terms of the result) syntax conveys the intent a bit better:
```js
const isNumber = /^\d+$/.test( piece );
```
`RegExp.test` returns a boolean instead of the full match structure we don't need, and converts `piece` to a string automagically.

**Review by jsnajdr — APPROVED** [review]
Looks good! Suggested one improvement that you might use if your taste is the same as mine in this regard 🙂

File: client/lib/route/path.ts (hunk 1 above)
Comment (sirbrillig) [reply client/lib/route/path.ts]: Perfect. Thanks!
