### PR TITLE
Close Account: rework the available options so user can close account with Atomic site

### LINKED ISSUE #57399: [Bug]: Unable to close account due to active subscription.
### Quick summary

Encountered this during routine Pre-Release automation testing when attempting to close an account created via the `domain-only` flow.

### Steps to reproduce

prereq. enable store sandbox.

1. navigate to `/start/domain`
2. search for and select a domain.
3. select to `buy only the domain`.
4. fill out details as needed on the checkout screen.
5. click on `My Sites` on top left once purchase is complete.
6. click on `Manage domain`.
7. cancel domain.
8. navigate to `/me`.
9. close account.

### What you expected to happen

User is taken to `/me/account/closed` then to another page confirming account closure.

### What actually happened

User is shown an error banner while in `/me/account/closed` that states:
`Sorry, there was a problem closing your account. Please contact support.`

User account cannot be closed.

### Context

Automated end to end tests.

### Browser

_No response_

### Simple/Atomic

Simple

### Other notes

TeamCity run: https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Pre_Release/6894490?buildTab=artifacts#%2Fscreenshots;%2Ftrace

User id: 213176213

image

Unsure if related but the following error appears in the browser console:

```
Uncaught (in promise) Error: Failed to load script "//stats.wp.com/w.js?63"
    S https://wordpress.com/calypso/evergreen/95961.ed848d323199a2c574c6.min.js:1
    s https://wordpress.com/calypso/evergreen/95961.ed848d323199a2c574c6.min.js:1
    T https://wordpress.com/calypso/evergreen/95961.ed848d323199a2c574c6.min.js:1
    ts https://wordpress.com/calypso/evergreen/95961.ed848d323199a2c574c6.min.js:1
    l https://wordpress.com/me/account/close:28
    js https://wordpress.com/calypso/evergreen/95961.ed848d323199a2c574c6.min.js:1
    l https://wordpress.com/me/account/close:28
    js https://wordpress.com/calypso/evergreen/entry-main.9e6eff9f231b77b9b6bf.min.js:2
    l https://wordpress.com/me/account/close:28
    <anonymous> https://wordpress.com/calypso/evergreen/entry-main.9e6eff9f231b77b9b6bf.min.js:2
    O https://wordpress.com/me/account/close:28
    <anonymous> https://wordpress.com/calypso/evergreen/entry-main.9e6eff9f231b77b9b6bf.min.js:2
    a https://wordpress.com/me/account/close:28
    <anonymous> https://wordpress.com/calypso/evergreen/entry-main.9e6eff9f231b77b9b6bf.min.js:2
```

### Reproducibility

Once

### Severity

One

### Available workarounds?

No but the platform is still usable

### Workaround details

Unsure of the true impact - first time this issue has been observed in manual and automated testing.

For the user affected by this issue, they are not able to close their account and must contact support.

### PR DESCRIPTION
**Pull request by mpkelly**
Fixes #57399
Related to #65636

#### Proposed Changes

Users should be able to close accounts with Atomic sites without needing to contact support. This change enables that. Now, if the user has an Atomic site, they need to remove the purchase and then wait for the site to be removed, and then they can close the account themselves; previously, their only option was to contact support. 

There is a small window where the user has to wait to completely close their account but this is still an improvement on what currently exists. A [second PR](https://github.com/Automattic/wp-calypso/pull/65636/#issuecomment-1189032726) will follow that will allow the user to speed up the deletion of the Atomic site and reduce the time of this window. 

#### Testing Instructions

1. Create or reuse a user account with an Atomic site
2. Go to `/me/account` and scroll to the bottom and choose "Close your account permanently"
3. You should see the following:
image
4. Click "Manage purchases" and cancel all purchases you have
5. Return to `/me/account/close` and you should see the text `We are still in the process of removing one or more of your sites. This process normally takes 15-20 minutes. Once removal is completed, you should be able to close your account from this page.`
6. If you wait approx. 5 minutes then refresh your Atomic site should have been deleted and you should be able to close your account as normal:
image
7. You should complete the close account process and confirm you can fully close your account:
image

You can repeat the account closure process for a user with a simple site with no purchases. For this, you should see the content in the screenshot for step 6 above. 

#### Pre-merge Checklist

Complete applicable items on this checklist **before** merging into trunk. Inapplicable items can be left unchecked.

Both the PR author and reviewer are responsible for ensuring the checklist is completed.

- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in [Simple](P9HQHe-k8-p2-p2), [Atomic](P9HQHe-jW-p2-p2), and [self-hosted Jetpack sites](PCYsg-g6b-p2-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [] Are we memoizing when appropriate (for expensive computations)? More info in [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md) and [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors)
- [ ] Have we sent any new strings [for translation](PCYsg-1vr-p2-p2) ASAP?

### CODE REVIEW

**Comment by mpkelly** [comment]
I will take a look at the e2e test failures.

Edit. Rebased and those passed.

File: client/me/account-close/test/main.js [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+	it( 'Shows Manage purchases button when refundable purchases exist', () => {
+		render(
+			<ReduxProvider store={ createTestStore( true, true ) }>
+				<AccountSettingsClose />
+			</ReduxProvider>
+		);
+		expect( screen.queryByTestId( 'manage-purchases-button' ) ).toBeInTheDocument();
+	} );
+
+	it( 'Tells user to wait if Atomic site is being deleted', () => {
```
Comment (daledupreez) [inline client/me/account-close/test/main.js]: Nit: It may be more accurate to describe this case as "Tells user to wait if they still have an Atomic site" -- despite us showing the message because we're waiting, the actual driving condition is that the user still has an Atomic site.

This is not blocking, and pretty minor.

File: client/me/account-close/test/main.js [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+						user_id: 1,
+						product_slug: 'premium_theme',
+					},
+				],
+			},
+			sites: {
+				items: {
+					'www.test.com': {
+						ID: 'www.test.com',
+						URL: 'http://www.test.com',
```
Comment (daledupreez) [inline client/me/account-close/test/main.js]: Two minor notes:
1. We strongly prefer not to prefix sites with `www`, so it would be better to go with `test.com` (or maybe `example.com` as a starting point)
2. I believe the `ID` is normally an integer

As above, not blocking but might be good to tighten up.
```suggestion
					'example.com': {
						ID: '1234',
						URL: 'http://example.com',
```

**Review by daledupreez — APPROVED** [review]
Thanks for the neat cleanup and the inclusion of the tests! I tested this on the main branch and against the live branch, and everything looks good to me. I had some minor comments on the test, but they aren't blocking.

### Screenshots from testing

#### Account close screen before the changes

Screenshot 2022-07-25 at 14 56 03

#### Account close screen with purchases and Atomic site

Screenshot 2022-07-25 at 14 56 11

#### Account close screen with Atomic site and no purchases

Screenshot 2022-07-25 at 15 00 00

#### Account close screen after Atomic site has been reverted to a Simple site and without any purchases

Screenshot 2022-07-25 at 15 01 39

File: client/me/account-close/test/main.js (hunk 1 above)
Comment (mpkelly) [reply client/me/account-close/test/main.js]: Ok, done

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7455705

Thank you @mpkelly for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7455705).
