### PR TITLE
Stats: Allow showing stats for "Home page / Archives"

### LINKED ISSUE #60563: "Home page / Archive" stats show "We don't have that post on record yet" when using a posts/archive homepage
### Quick summary

This appears to be a recent issue – one user that reported it mentioned noticing this change within the past week or so.

When the homepage is set as a "posts page" (blog archive), it is displayed on `/stats/day/{site}` as *Home page / Archives`. Clicking on that entry should bring up the insights for the site's homepage, but instead leads to a possibly invalid URL: 

`https://wordpress.com/stats/post/0/{site}`

There is no stats information shown there, just a warning that `We don't have that post on record yet.`

**Note: I wasn't able to reproduce this on a test site due to delays in stats recording. Unsure if this is theme-specific. Unsure if this applies to atomic.**

### Steps to reproduce

1. Navigate to My Site > Appearance > Customize > Homepage Settings and set the homepage to be a "posts page." (Ideally, this should be done on a site which has used a posts page for some time and has had traffic.)
2. View the homepage to ensure there is traffic/stats to record.
3. Wait for "Home page / Archives" to appear under "Posts & Pages" at My Site > Stats.
4. Click on "Home page / Archives."

### What you expected to happen

This page should show stats for the site's archive homepage.

### What actually happened

You are instead led to this URL: `https://wordpress.com/stats/post/0/{site}`
Possibly because there isn't a post with ID `0`, no stats are displayed and the message `We don't have that post on record yet.` displays instead.

Markup 2022-01-27 at 12 05 28

### Context

4720094-zen

Initially mentioned by @liviopv in p1642511428116000-slack-C03TY6J1A

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Unsure.

### Browser, operating system and other notes

_No response_

### Reproducibility

_No response_

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by aidvu**
#### Proposed Changes

The latest posts homepage is tracked with a post_id of 0,
so we need to change some things to allow querying stats for it.

Also add some checks to disable stuff for the home page, and
just show stats.

#### Testing Instructions

- Find a blog that has latest posts set as homepage
- Visit `/stats/day/{$blog}` for the chosen blog
- Click on "Home page / Archives"
- See stats

Previous behavior: 
- Only shows `We don't have that post on record yet.`

Depends on D82314-code.

Fixes https://github.com/Automattic/wp-calypso/issues/60563

### CODE REVIEW

File: client/components/data/query-post-stats/index.jsx [hunk 1]
```diff
@@ -16,7 +16,7 @@ function QueryPostStats( { siteId, postId, fields } ) {
 	const memoizedFields = useMemoCompare( fields, ( a, b ) => a?.join() === b?.join() );
 
 	useEffect( () => {
-		if ( siteId && postId ) {
+		if ( siteId && typeof postId === 'number' ) {
```
Comment (aidvu) [inline client/components/data/query-post-stats/index.jsx]: Non-integers will fail on the backend anyway. This one allows querying for `post_id = 0` which is a special case for stats. We can also do `postId > -1`. Both are fine by me.

File: client/components/data/query-posts/index.jsx [hunk 2]
```diff
@@ -30,7 +30,7 @@ const request = ( siteId, postId, query ) => ( dispatch, getState ) => {
 		return;
 	}
 
-	if ( ! isRequestingSitePost( state, siteId, postId ) ) {
+	if ( ! isRequestingSitePost( state, siteId, postId ) && postId > 0 ) {
```
Comment (aidvu) [inline client/components/data/query-posts/index.jsx:33]: Post IDs are positive integers.

File: client/components/data/query-post-stats/index.jsx [hunk 3]
```diff
@@ -16,7 +16,7 @@ function QueryPostStats( { siteId, postId, fields } ) {
 	const memoizedFields = useMemoCompare( fields, ( a, b ) => a?.join() === b?.join() );
 
 	useEffect( () => {
-		if ( siteId && postId ) {
+		if ( siteId && postId > -1 ) {
```
Comment (aidvu) [inline client/components/data/query-post-stats/index.jsx:19]: Homepage with latest posts is special case (0) for stats.

File: client/my-sites/stats/site.jsx [hunk 4]
```diff
@@ -155,7 +155,7 @@ class StatsSite extends Component {
 				description={ translate(
 					'Changing your site from private to public helps people find you and get more visitors. Don’t worry, you can keep working on your site.'
 				) }
-				disableCircle="true"
+				disableCircle={ true }
```
Comment (aidvu) [inline client/my-sites/stats/site.jsx:158]: housekeeping
