### PR TITLE
Domains: allow searches to include underscores and show correct message for single invalid characters

### LINKED ISSUE #19502: Domain Search Results: searching for _ addresses or special symbols shows wrong error message
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains/add/ (or https://wordpress.com/start and navigate to domains step)
2. Seach for a term with an underscore
3. Search for a special symbol by itself

#### What I expected

An informative error message

#### What happened instead

`Sorry, there was a problem processing your request. Please try again in a few minutes.
`

#### Browser / OS version

Chrome macOS

#### Screenshot / Video

underscore

special character

#### Context / Source
 #reallife #dogfooding

### PR DESCRIPTION
**Pull request by alisterscott**
Fixes #19502

**Current** 

when a customer enters an underscore in a domain search term or a single invalid character like $%! the customer will see:

underscore

special character

**This PR**

Treats underscores which are invalid as same as dashes which are valid:

screen shot 2017-11-06 at 2 07 47 pm

It also fixes the single special character error: 

screen shot 2017-11-06 at 2 08 35 pm

### CODE REVIEW

**Comment by alisterscott** [comment]
It would be nice to have unit tests around these - I'm not sure how to add them though

**Comment by klimeryk** [comment]
Fixes https://github.com/Automattic/wp-calypso/issues/16763

File: client/lib/domains/registration/availability-messages.js [hunk 1]
```diff
@@ -20,6 +20,10 @@ function getAvailabilityNotice( domain, error ) {
 
 	const tld = getTld( domain );
 
+	if ( error.error ) {
```
Comment (klimeryk) [inline client/lib/domains/registration/availability-messages.js]: Good catch, though I think this should be fixed in the caller, more precisely here: https://github.com/Automattic/wp-calypso/blob/e3d5a722cf1e6d303d70f2f37f601028164f3a86/client/components/domains/register-domain-step/index.jsx#L459. `error.error` should just be passed directly to this function there.

Comment (alisterscott) [reply client/lib/domains/registration/availability-messages.js]: Thanks, I have fixed this 👍

**Comment by alisterscott** [comment]
@klimeryk thanks for the review: I made the update needed and it tests well now, would you mind having a quick look again to make sure what I did was ok. I can merge this first thing tomorrow (Brisbane time)

**Comment by klimeryk** [comment]
Thanks - that's exactly what I had in mind 👍

**Comment by apeatling** [comment]
@alisterscott  Can you merge this one please?
