### PR TITLE
Fix goals step showing up again after a partner theme purchased on newish sites

### LINKED ISSUE #100246: Onboard: Goals step show up again after a partner theme purchase
### Context and steps to reproduce

Originating from https://github.com/Automattic/wp-calypso/issues/99459

Adding a demo here:

https://github.com/user-attachments/assets/6bf987b0-43a2-404e-895f-f6552b527919

Note: I chose to skip that page, but when I don't, I get these:

https://github.com/user-attachments/assets/61d0641b-0b84-4223-b5e4-bc05da1b3de2

### Site owner impact

Between 20% and 60% of the total website/platform users

### Severity

Moderate

### What other impact(s) does this issue have?

Platform revenue

### If a workaround is available, please outline it here.

_No response_

### Platform

Simple, Atomic

### PR DESCRIPTION
**Pull request by p-jackson**
Fixes #100246

## Proposed Changes

* Clear `wpcom_signup_complete_destination` before purchasing partner theme

This allows the default post checkout behaviour for partner themes to run i.e. transferring to atomic

## Why are these changes being made?

See https://github.com/Automattic/wp-calypso/issues/100246#issuecomment-2689789201

In short the signup flow stores it's post-checkout destination in a cookie. If the user purchases a partner theme from `/themes` within 24 hours of the site being created, then that cookie will still be there. The cookie will override the post-checkout behaviour.

Deleting the cookie when we know the user wants to purchase a partner theme might not be an elegant fix, but it fixes the user's problem.

## Testing Instructions

* Create a new site with `/setup/onboarding`, or start with a simple site that's under 24 hours old
* Head to `/themes/:siteSlug` purchase a partner theme along with business plan (e.g. STAX)
* Complete checkout
* Post checkout there should be a progress bar while the site goes atomic
* Now test it with a site that started with a premium plan
* Now test it with a simple site that has business plan already
* Now test it with a brand new user

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/state/themes/actions/add-external-managed-theme-to-cart.tsx [hunk 1]
```diff
@@ -107,6 +108,11 @@ export function addExternalManagedThemeToCart( themeId: string, siteId: number )
 			.forCartKey( cartKey )
 			.actions.addProductsToCart( cartItems )
 			.then( () => {
+				// If there's been a site created recently then this cookie will still contain
+				// the post-checkout destination from that site-creation flow. We don't want
+				// that flow's destination to be used here.
+				clearSignupDestinationCookie();
```
Comment (zaguiini) [inline client/state/themes/actions/add-external-managed-theme-to-cart.tsx:114]: Interesting. I thought of a similar solution, but instead of doing it here, I thought of doing it as part of the chain of `Promises` in the `site-setup` flow's `exitFlow` callback. This way, the user won't ever enter that specific flow again 🤔 But maybe your solution makes more sense as the user might go through different flows, and the same scenario could happen.

Comment (p-jackson) [reply client/state/themes/actions/add-external-managed-theme-to-cart.tsx:114]: Yeah that's what I was thinking. Maybe there last completed flow was `/newsletter` or `/new-hosted-site`. We'd have to add `clearSignupDestinationCookie()` to the end of all of these flows.

Comment (zaguiini) [reply client/state/themes/actions/add-external-managed-theme-to-cart.tsx:114]: @alshakero, here's another clear case where we can use your state persistence solution. If the state were bound to a key, then this bug wouldn't happen, as we wouldn't be dealing with dirty cookies 🤷🏻

Comment (p-jackson) [reply client/state/themes/actions/add-external-managed-theme-to-cart.tsx:114]: Agreed. Whatever issue this signup-destination-cookie was being used as a bandaid for, hopefully it can better fixed by explicit state management.
