### PR TITLE
WooCommerce: Fix some UI issues with the product edit view

### LINKED ISSUE #15645: WooCommerce: ProductVariationTypesForm key error
The following error is seen upon the editing of an existing product:

`warning.js:36 Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `ProductVariationTypesForm`. See https://fb.me/react-warning-keys for more information.
    in div (created by ProductVariationTypesForm)
    in ProductVariationTypesForm (created by ProductFormVariationsCard)
    in div (created by ProductFormVariationsCard)
    in div (created by FoldableCard)
    in div (created by Card)
    in Card (created by FoldableCard)
    in FoldableCard (created by ProductFormVariationsCard)
    in ProductFormVariationsCard (created by Localized(ProductFormVariationsCard))
    in Localized(ProductFormVariationsCard) (created by ProductForm)
    in div (created by ProductForm)
    in ProductForm (created by ProductUpdate)
    in main (created by Main)
    in Main (created by ProductUpdate)
    in ProductUpdate (created by Localized(ProductUpdate))
    in Localized(ProductUpdate) (created by Connect(Localized(ProductUpdate)))
    in Connect(Localized(ProductUpdate))
    in Provider`

To Replicate:

1. Visit store-enabled site.
2. Go to Products List
3. Select a product, it will bring up the edit page.
4. Inspect JS console and see error.

I think this has to do with a manufactured uid that is given to attributes/variation types upon creation. But these don't exist for a product received via the API.

### PR DESCRIPTION
**Pull request by justinshreve**
Fixes #15645, #15696, #15646.

This PR fixes a few issues with the product form when loading it in edit product mode:

* It fixes images not always loading in the image component.
* It fixes the product description not loading, by not loading the TinyMCE instance until we are ready.
* A minor (non-breaking) JS warning with variation types form.

To Test:
* Note that during these steps, when visiting the add and edit routes, you will need to refresh until #14609 is resolved.
* Edit a product that you know has a description.
* Make sure that the product description loads in.
* Edit a product with no description, and make sure TinyMCE loads.
* Go to add a new product and make sure TinyMCE loads.
* Edit a product with images, and make sure the images load in.
* Edit a variation with images, and make sure the images load in.

### CODE REVIEW

File: client/extensions/woocommerce/app/products/product-form-variations-table.js [hunk 1]
```diff
@@ -203,7 +201,7 @@ class ProductFormVariationsTable extends React.Component {
 						</thead>
 						<tbody>
 							{ this.renderBulkRow() }
-							{ variations.map( ( v ) => this.renderVariationRow( v ) ) }
+							{ variations.map( ( v, i ) => this.renderVariationRow( v, i ) ) }
```
Comment (ryelle) [inline client/extensions/woocommerce/app/products/product-form-variations-table.js]: Could do `variations.map( this.renderVariationRow )` instead
