### PR TITLE
fix(media-library): add 'source' to media library list key

### LINKED ISSUE #46380: Media: No media in library when switching source from Pexels
This might be an edge case, but here's the issue I encountered and was able to reproduce on two simple sites.

#### Steps to reproduce

1. Create a new post or page. Add image block and click _Select source > Media Library._
2. In the media modal, click in the top left corner to change source and select _Pexels free photos_.
3. Now click on in the top left corner again and switch back the source to _Media Library_.
4. Note there are no images displayed.
5. I also had an intermittent issue where closing the editor and then opening it again would not clear up the issue - the media library was still empty. In that case, reloading the page would fix it. This did not happen every time though.

#### What I expected
I expected to see the images in my media library when I switch back to that image source.

#### Browser / OS version
Chrome 85.0 / macOS 10.15.6

#### Screenshot / Video
5r8k3dneNg

### PR DESCRIPTION
**Pull request by flootr**
#### Changes proposed in this Pull Request

* Add `source` param to the `<MediaLibraryList />` `key` prop

The above makes sure that we use a different component instance for different sources and reset any internal values which are stored by the `ScrollHelper` which is itself used by `<InfiniteList />` component.

During debugging I noticed, that certain scroll values didn't reset when the media source changed which is necessary to trigger a (re)fetch of media items. You can see a hint of this on the screenshot below, or follow the provided screen capture in #46380 and look closely at the scrollbar.

Screenshot 2020-10-19 at 15 16 31

The list of media items was cleared when switching to Pexels. However, as the the list component didn't update and therefore the scroll values which indicate we should refetch items (e.g. when the size of the thumbnail changes) weren't updated the list of media library items is empty when we switch back to the media library.

#### Testing instructions

* (on [calypso.live](https://calypso.live/?branch=fix/media-library-list-key)) open a post using the block editor and insert an image block
* Hit _Select Image_ > _Media Library_
* Now choose the largest size for thumbnails on the top right
  * if you're on the largest size on load make sure to change it but then leave it at the largest size again
* Make sure all items are loaded
* Now switch to Pexels and make sure you get the correct _"emtpy"_ view
* Switch back to the media library and make sure items are loaded

Also follow the instructions mentioned in #46380

- This is how it should **NOT** look like: https://d.pr/v/fltO4x
- This is how it **should** look like: https://d.pr/v/iKRREJ

Fixes #46380

### CODE REVIEW

**Review by wp-desktop — DISMISSED** [review]
WordPress Desktop CI Failure for job "wp-desktop-mac".

@flootr please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/927523). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

**Comment by cathymcbride** [comment]
#46380 Looks fixed to me! But it looks like desktop and mobile builds are failing?

File: client/my-sites/media-library/content.jsx [hunk 1]
```diff
@@ -358,6 +358,14 @@ export class MediaLibraryContent extends React.Component {
 			return this.renderConnectExternalMedia();
 		}
 
+		const listKey = [
+			'list-',
```
Comment (tyxla) [inline client/my-sites/media-library/content.jsx:362]: Nit: we can remove the trailing `-` here, because we'll get another one coming from the `join( '-' )` below.

**Review by tyxla — APPROVED** [review]
Works well for me 👍  Just left a minor suggestion. Feel free to 🚢  either way.

File: client/my-sites/media-library/content.jsx (hunk 1 above)
Comment (flootr) [reply client/my-sites/media-library/content.jsx:362]: You're right! I'll add that and then :shipit:

**Review by wp-desktop — DISMISSED** [review]
WordPress Desktop CI Failure for job "wp-desktop-mac".

@flootr please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/928285). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.
