### PR TITLE
Check if the Jetpack AI and Stats have tiers before showing tiered text

### LINKED ISSUE #38237: Jetpack AI: Legacy Plans Display Only 1 Available Request
### Impacted plugin

Jetpack

### Quick summary

If a user has a legacy Jetpack AI Assistant plan (without a specific tier), the WordPress.com Plans display only shows the site as having 1 request available

### Steps to reproduce

1. Add a Jetpack AI Assistant plan without a tier
2. Visit https://wordpress.com/me/purchases
3. See that the plan shows "(1 requests per month)"

### A clear and concise description of what you expected to happen.

The plan should not show a limit

### What actually happened

Annotation on 2024-07-08 at 10-12-26

Annotation on 2024-07-08 at 10-13-12

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

_No response_

### LINKED ISSUE #38238: Jetpack Stats: Legacy Commercial Plans Show 1 View Available
### Impacted plugin

Jetpack

### Quick summary

When a user has a legacy Jetpack Stats Commercial package (before tiers), the plan displays as only having "1 views per month" on WordPress.com

### Steps to reproduce

1. Add a Jetpack Stats Commercial plan (without tiers)
2. View the plan at https://wordpress.com/me/purchases

### A clear and concise description of what you expected to happen.

The views should show as unlimited or not be displayed

### What actually happened

Annotation on 2024-07-08 at 10-35-03

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by robertsreberski**
## Proposed Changes

Ensure that Jetpack AI and Stats plans support tiers before showing tiered text ("x requests per month") on /me/purchases

## Why are these changes being made?

* User can see "1 requests per month" information for Jetpack AI legacy plans on /me/purchases
CleanShot 2024-07-09 at 15 53 08@2x

## Testing Instructions

* Add legacy Jetpack AI and Stats Commercial subscriptions to any of your sites via SA
* Go to /me/purchases (on Calypso Live link) and make sure that the subscription has name "Jetpack AI" - without mentioning any requests

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/lib/purchases/index.ts [hunk 1]
```diff
@@ -253,7 +253,12 @@ export function getDisplayName( purchase: Purchase ): TranslateResult {
 	const { productName, productSlug, purchaseRenewalQuantity } = purchase;
 	const jetpackProductsDisplayNames = getJetpackProductsDisplayNames( 'full' );
 
-	if ( isJetpackAISlug( purchase.productSlug ) && purchase.purchaseRenewalQuantity ) {
+	if (
+		isJetpackAISlug( purchase.productSlug ) &&
+		purchase.purchaseRenewalQuantity &&
+		purchase.priceTierList &&
+		purchase.priceTierList.length > 0
```
Comment (CodeyGuyDylan) [inline client/lib/purchases/index.ts]: Possible improvement that I think should work the same
```suggestion
		purchase.priceTierList?.length > 0
```

**Review by CodeyGuyDylan — APPROVED** [review]
Works well when testing!

File: client/lib/purchases/index.ts (hunk 1 above)
Comment (robertsreberski) [reply client/lib/purchases/index.ts]: The thing is typescript doesn't allow for direct comparison of `undefined` and numbers. What could work though is the below 🤔 What do you think?
```suggestion
		! purchase.priceTierList?.length
```

**Comment by robertsreberski** [comment]
Hey @CodeyGuyDylan! The PR escalated as we've realized the same bug is also impacting Jetpack Stats. I've updated the PR to take care of this change as well.

**Review by CodeyGuyDylan — APPROVED** [review]
Tested on Stats and AI legacy plans and confirmed there was no request or view limit being shown. Also tested on current AI and Stats plans and confirmed that the request/view limit is shown correctly. LGTM!
