### PR TITLE
Reader Refresh - fullpost stats fix

### LINKED ISSUE #8300: Reader full_post stats audit: ensure that refreshed full post fires same analytics events as the existing full post
We're replacing the full post view with a new shinier version.

Before launch, we need to ensure that all the existing analytics events are also fired in the new version.

### PR DESCRIPTION
**Pull request by samouri**
Stats to fix:

1. [x] calypso_reader_article_closed 
1. [X] calypso_reader_full_post_like_button_clicked --> This shouldn't have existed
1. [x] calypso_reader_related_post_clicked -->{ `calypso_reader_related_post_from_same_site_clicked`, `calypso_reader_related_post_from_other_site_clicked` }
1. [X] calypso_reader_related_post_site_clicked -- This never worked
1. [x] calypso_reader_author_link_clicked 
1. [x] calypso_reader_feed_link_clicked 

Fixes #8300.

### CODE REVIEW

**Comment by samouri** [comment]
Do we want one, none, or both?

- calypso_reader_full_post_like_button_clicked
- calypso_reader_article_liked ?

**Comment by samouri** [comment]
Questions:

1. what does this mean: `Consider whitelisting reader track calypso_reader_author_link_clicked`?
1. do we want to have a different event for when `RelatedPostsFromSameSite` and `RelatedPostsFromOtherSites` are clicked.
1. what is the intended difference between `calypso_reader_full_post_like_button_clicked` and `calypso_reader_article_liked`.   Right now `calypso_reader_full_post_like_button_clicked` only occurs when a like was triggered via keyboard shortcut.  this is easy to modify.

Other than those questions I have a few small questions which can be found in TODOs in the code.

File: client/blocks/reader-full-post/action-links.jsx [hunk 1]
```diff
@@ -7,7 +7,8 @@ import React from 'react';
  * Internal dependencies
  */
 import CommentButton from 'blocks/comment-button';
-import LikeButton from 'reader/like-button';
+//import LikeButton from 'reader/like-button'; // TODO why reader/like-button vs. blocks/like-button ?
```
Comment (bluefuton) [inline client/blocks/reader-full-post/action-links.jsx]: `reader/like-button` is a simple wrapper around `blocks/like-button` that fires our like/unlike stats (e.g. `calypso_reader_article_liked`).

File: client/blocks/reader-related-card-v2/index.jsx [hunk 2]
```diff
@@ -94,18 +95,21 @@ export function RelatedPostCard( { post, site, onPostClick = noop, onSiteClick =
 	const classes = classnames( 'reader-related-card-v2', {
 		'has-thumbnail': !! featuredImage
 	} );
+  // TODO what is the difference between post.URL and getPostUrl( post )
```
Comment (bluefuton) [inline client/blocks/reader-related-card-v2/index.jsx]: `post.URL` gives the external link to the post on the origin site.

`getPostUrl()` gives the URL to the post within Reader, e.g. /read/feeds/123/posts/123. `getReaderPostUrl()` might have been a better name for it :)

**Comment by bluefuton** [comment]
Good questions @samouri!

1. There's a tracks event whitelist called `tracksRailcarEventWhitelist` you can add events to in `reader/stats.js`. A railcar is an extra object added to a post on the API side to help us identify it.

2. Sounds like a good plan!

3. Not sure on that one. Any ideas @blowery?

4. Yep - as the CSS warning is unrelated to what you're fixing, I think that's best tackled in a separate PR.

5. Copy pasta is delicious.

**Comment by blowery** [comment]
> what is the intended difference between calypso_reader_full_post_like_button_clicked and calypso_reader_article_liked. Right now calypso_reader_full_post_like_button_clicked only occurs when a like was triggered via keyboard shortcut. this is easy to modify.

Sounds like an oversight. The keyboard shortcut should fire the same event, likely with a `event_source` property set to `keyboard`.

File: client/blocks/reader-related-card-v2/index.jsx (hunk 2 above)
Comment (samouri) [inline client/blocks/reader-related-card-v2/index.jsx]: thanks for the info!

File: client/blocks/reader-full-post/action-links.jsx (hunk 1 above)
Comment (samouri) [inline client/blocks/reader-full-post/action-links.jsx]: 👍

**Comment by samouri** [comment]
What I did:

1. split up `calypso_reader_related_post_clicked` into two separate events:
     1. `calypso_reader_related_post_from_same_site_clicked`
     1. `calypso_reader_related_post_from_other_site_clicked`
1. found/fixed a new missing stat: `calypso_reader_feed_link_clicked`  (when a side-bar site was clicked instead of the author)
1. `calypso_reader_full_post_like_button_clicked` --> `calypso_reader_article_liked ` etc.
1. whitelisted new events

**Comment by bluefuton** [comment]
Looks good to me! Verified all the events above 🚢
