### PR TITLE
Conditionally set billing subheader for annual and biennial plans

### LINKED ISSUE #54355: Plans: Update text for two-year plans
### Steps to reproduce the behavior

1. Add a two year plan to your test site via SA or through the normal checkout flow. In my example I am using a two year Premium plan.
2. Visit https://wordpress.com/plans
3. Note the pricing on this page shows a monthly breakdown price based on the breakdown of our two year plans (this makes sense, since we're on a two year plan currently), but the text indicates "per month billed annually".

#### What I expected to happen
I expected to see the wording written something like "per month, billed once per two years", because the price shown reflects this. This is not the price breakdown that is equivalent to our one year annual plan.

#### What actually happened
We found text indicating that the pricing was reflective of our annual plan, and the pricing shown was reflective of our two year plan.

### Context
This was found during pod testing and discussed in Slack (p1625579934450000-slack-C02BEP610).

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Screen Shot 2021-07-06 at 9 58 31 AM

### PR DESCRIPTION
**Pull request by jjchrisdiehl**
#### Changes proposed in this Pull Request

The billing subheader was written just for annual plans and is not accurate on biennial plans.

Before, biennial plan showed 'billed annually':
image

After, biennial plan correctly shows 'billed every two years':
image

#### Testing instructions

Test the bug:
* Add plan to checkout
* Change to two year plan
* Proceed through checkout
* Go to https://wordpress.com/plans/[site]
* See billing subheader is stating as 'billed annual'

Test the fix:
* Do the above steps with this PR
* Verify that two year plan shows 'billed every two years' in billing subheader

Fixes #54355

### CODE REVIEW

File: client/my-sites/plan-features/header.jsx [hunk 1]
```diff
@@ -248,10 +249,22 @@ export class PlanFeaturesHeader extends Component {
...
+		) {
 			return translate( 'billed annually' );
 		}
 
+		if (
+			( isInSignup || isLoggedInMonthlyPricing ) &&
+			! isMonthlyPlan &&
+			planMatches( planType, { group: GROUP_WPCOM, term: TERM_BIENNIALLY } )
+		) {
+			return translate( 'billed every two years' );
```
Comment (a8ci18n) [inline client/my-sites/plan-features/header.jsx:265]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **25** times:
`translate( '/month, billed every two years' )` *ES Score: 10*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/test/biyearly-text)

**Review by sirbrillig — APPROVED** [review]
Looks good. Tested in a pairing session.

**Comment by DavidRothstein** [comment]
I'm seeing a noticeable misalignment of the tooltip on the plans page here (tested in Chrome)... anyone else?

Before:

tooltip-before


After:

tooltip-after

Otherwise, looks good to me!

**Comment by DavidRothstein** [comment]
I guess I should mention that the above is specifically in the situation where you visit the plans page and have an existing plan (that's when the tooltip appears).  And I know that we are thinking of getting rid of that tooltip entirely in another issue anyway.

**Comment by jjchrisdiehl** [comment]
> I guess I should mention that the above is specifically in the situation where you visit the plans page and have an existing plan (that's when the tooltip appears). And I know that we are thinking of getting rid of that tooltip entirely in another issue anyway.

The tooltip was initially problematic when the text string reached a certain character length as seen here:

image

We added `display: flex` to give this section room to grow for longer strings, but admittedly it is not a perfect solution.

Perhaps we could run this by a designer for a better solution?

**Comment by jjchrisdiehl** [comment]
Added `align-items:baseline` to `.plan-features__header-timeframe` which resulted in a better alignment:

image

**Comment by sirbrillig** [comment]
Looks like that fixes the issue that @DavidRothstein was describing (I think):

Screen Shot 2021-07-23 at 11 37 20 AM

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6276515

Thank you @jjchrisdiehl for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6276515).
