### PR TITLE
Persist sidebar state from Calypso to User calypso_preferences.

### LINKED ISSUE #46645: Collapse Sidebar: keep the same state across wp-admin / calypso
#### Steps to reproduce
**Scenario 1**
1. Starting at URL: wp-admin
2. Collapse the sidebar
3. Click a calypso link (eg Posts)
_Result: The sidebar is expanded_

**Scenario 2**
1. Starting at URL: wp-admin
2. Click a calypso link (eg Posts)
3. Collapse the sidebar
4. Click a wp-admin link (eg Settings)
_Result: The sidebar is expanded_

#### What I expected
I expect that the collapse status of the sidebar is consistent when navigating in calypso <-> wp-admin.

#### Suggested solution
**Scenario 1**
1. When in wp-admin, add a querystring in each calypso Url (eg `https://wordpress.com/posts/cpapazoglousandbox.wordpress.com?sidebar-collapsed=1`) declaring the sidebar status. The status is saved in a `wp-settings-` cookie by the `setUserSetting` function in `wp-admin/js/common.js`
2. Landing in calypso use the above querystring so that we update the state accordingly and let `getSidebarIsCollapsed` return the correct result.

**Scenario 2**
1. When in calypso, add a querystring in each wp-admin Url (eg `https://cpapazoglousandbox.wordpress.com/wp-admin/options-general.php?sidebar-collapsed=1`) declaring the sidebar status. The status can be retrieved from `getSidebarIsCollapsed` selector.
2. Landing in wp-admin use the above querystring so that we trigger a click in `#collapse-button` 

We have also a separate task for persisting the state in Calypso #51703

### Progress
- [x] **Calypso:** Save/  read sidebar state to / from `calypso_preferences` User attribute (https://github.com/Automattic/wp-calypso/pull/51785)
- [x] **WP Admin:** Read sidebar state in WP Admin for SIMPLE sites https://github.com/Automattic/jetpack/pull/19520
- [x] **WP Admin:** Save WP Admin state to `calypso_preferences` User attribute https://github.com/Automattic/jetpack/pull/19520
- [x] **WPCOMSH:** Read sidebar state in WP Admin for ATOMIC sites  673-gh-Automattic/wpcomsh

### PR DESCRIPTION
**Pull request by cpapazoglou**
#### Changes proposed in this Pull Request

* Save sidebar state to calypso_preferences.
* Read sidebar state from calypso_preferences.

#### Testing instructions

* Click "Collapse menu"
* Make sure the sidebar collapses
* Inspect the indexed DB and check that `"redux-state-[USER_ID]:preferences"` object has a key `sidebarCollapsed: true`
* Click "Collapse menu" again
* Reload the Indexed DB values and inspect that `"redux-state-[USER_ID]:preferences"` object has a key `sidebarCollapsed: false`
* Click "Collapse menu" again
* Reload the page, make sure that the sidebar remains collapsed
* Click on Switch Site or Site Card or Nudges, make sure the sidebar expands
* Reload the Indexed DB values and inspect that `"redux-state-[USER_ID]:preferences"` object has a key `sidebarCollapsed: false`

If reviewed in conjunction with https://github.com/Automattic/jetpack/pull/19520, you may also check that SIMPLE sites and Calypso are in sync (There is PR pending for propagating the preference to Atomic sites).

Fixes #46645

### CODE REVIEW

**Comment by cpapazoglou** [comment]
The way that WP Admin works makes it difficult to retrieve the **updated** sidebar state.

**How it works?**
1. User visits `/wp-admin`
2. User clicks "Collapse Menu"
3. A cookie is added / updated `wp-settings-USERID`
4. User refreshes the page, `wp_user_settings()` runs and saves the cookie values to DB

So until (4), the value is not available to the backend. If you open an incognito window you will notice that the sidebar states will be out of sync.

That said, I think we will need to do an ajax request to the backend and update the calypso_preferences

File: client/my-sites/sidebar-unified/collapse-sidebar.jsx [hunk 1]
```diff
@@ -16,21 +16,23 @@ import PropTypes from 'prop-types';
...
+
 	return (
 		<SidebarItem
 			className="collapse-sidebar__toggle"
-			onNavigate={
-				sidebarIsCollapsed
-					? () => reduxDispatch( expandSidebar() )
-					: () => reduxDispatch( collapseSidebar() )
-			}
+			onNavigate={ () => onNavigate() }
```
Comment (tjcafferkey) [inline client/my-sites/sidebar-unified/collapse-sidebar.jsx]: We can remove the additional callback here

```suggestion
			onNavigate={ onNavigate }
```

File: client/my-sites/current-site/index.jsx [hunk 2]
```diff
@@ -39,13 +39,12 @@ class CurrentSite extends Component {
 		anySiteSelected: PropTypes.array,
 		forceAllSitesView: PropTypes.bool,
 		sidebarIsCollapsed: PropTypes.bool,
-		expandSidebar: PropTypes.func.isRequired,
 		isNavUnificationEnabled: PropTypes.bool.isRequired,
 	};
 
 	switchSites = ( event ) => {
 		if ( this.props.isNavUnificationEnabled && this.props.sidebarIsCollapsed ) {
```
Comment (tjcafferkey) [inline client/my-sites/current-site/index.jsx:46]: Since this code is also used in the `render()` method I wonder if it will be more DRY and readable to move it to it's own method:

```js
unifiedNavSidebarIsCollapsed = () => {
	return this.props.isNavUnificationEnabled && this.props.sidebarIsCollapsed;
}
```

**Review by tjcafferkey — CHANGES_REQUESTED** [review]
I also tested it in conjunction with https://github.com/Automattic/jetpack/pull/19520 and it works great.

Just a few minor comments.

File: client/my-sites/current-site/index.jsx (hunk 2 above)
Comment (cpapazoglou) [reply client/my-sites/current-site/index.jsx:46]: Excellent point! Done e524308

File: client/my-sites/sidebar-unified/collapse-sidebar.jsx (hunk 1 above)
Comment (cpapazoglou) [reply client/my-sites/sidebar-unified/collapse-sidebar.jsx]: Done e524308

**Review by tjcafferkey — APPROVED** [review]
Tests well and LGTM! 👍🏻
