### PR TITLE
Store shipping: Fixed fulfillment & labels

### LINKED ISSUE #19157: Store shipping: Fixes for fulfillment & labels
@DanReyLop @marcinbot 

Sorry I missed this UX interaction feedback during label implementation. 

1. During setup, if the user enables shipping labels, they should not be able to Save the Shipping settings page unless they have a payment method save. We should throw an error on Save that says "A payment method is required to print shipping labels."

2. If a user has not set up a payment method and already has a store up and running, then what? We should add a notice in the dashboard and on the orders page so that they know what to do. Note the fulfill button in the design on the orders page. Both of these cards use a highlighted warning card as seen here: https://wpcalypso.wordpress.com/devdocs/design/cards. Excuse the rough nature of these mockups. 

Dashboard page: 
screen shot 2017-10-25 at 1 29 30 pm

Order page: 
screen shot 2017-10-25 at 1 21 53 pm

3. Should printing a label should be enabled on Canceled orders? Currently: 
screen shot 2017-10-25 at 10 55 27 am

4. The ellipsis button drop up is meant for more than one item. During testing, it looks like a tooltip and not like its something you actually have to click on: 

screen shot 2017-10-25 at 11 00 18 am

Instead, we should pull out that link as a text link: 

screen shot 2017-10-25 at 12 27 43 pm

### PR DESCRIPTION
**Pull request by marcinbot**
Fixes #19157 

To test:
* if you have label payments setup on your site you might have to disable and reinstall WCS in WP-Admin to clear them
* attempt to save the shipping settings with labels enabled, but no payment method. You should see an error notice 54d690a
* with labels enabled and no payment method (default state after fresh install) you should see a notice at the top of the dashboard and order pages acca890
* after you save the shipping settings with labels and payment method, no notices should appear
* the print label button should not appear on cancelled orders 8b72255
* the "fulfill without a label" control should appear as a link instead of in a popover menu

### CODE REVIEW

File: client/extensions/woocommerce/app/dashboard/manage-no-orders-view.js [hunk 1]
```diff
@@ -99,6 +100,7 @@ class ManageNoOrdersView extends Component {
 	render = () => {
 		return (
 			<div className="dashboard__manage-no-orders">
+				<LabelsSetupNotice />
```
Comment (DanReyLop) [inline client/extensions/woocommerce/app/dashboard/manage-no-orders-view.js]: Does it make sense in this page though? The user haven't even received any orders yet at this point.

File: client/extensions/woocommerce/app/order/order-fulfillment/index.js [hunk 2]
```diff
@@ -159,7 +159,10 @@ class OrderFulfillment extends Component {
 			'is-placeholder': wcsEnabled && ! labelsLoaded,
 		} );
 
-		if ( ! isShippable && ( ! wcsEnabled || ( labelsLoaded && hideLabels ) ) ) {
+		if (
```
Comment (DanReyLop) [inline client/extensions/woocommerce/app/order/order-fulfillment/index.js]: This logic is getting out of hand. Would you mind trying to clarify this `if` (and the next one) either breaking it into multiple, separate conditions, or at least adding comments? For example, `if( 'cancelled' ) return null;` can be its own condition, no need to pile it with the other ones.

File: client/extensions/woocommerce/app/dashboard/manage-no-orders-view.js (hunk 1 above)
Comment (kellychoffman) [reply client/extensions/woocommerce/app/dashboard/manage-no-orders-view.js]: +1. This should only be added to the dashboard with orders present.

Comment (marcinbot) [reply client/extensions/woocommerce/app/dashboard/manage-no-orders-view.js]: Removed in 51229cc

File: client/extensions/woocommerce/app/order/order-fulfillment/index.js (hunk 2 above)
Comment (marcinbot) [reply client/extensions/woocommerce/app/order/order-fulfillment/index.js]: I agree, I hope I managed to make it clearer in 47da5c6

**Comment by kellychoffman** [comment]
Can the link + button be on a separate line on smaller screens? Currently: 

screen shot 2017-10-26 at 10 50 39 am

**Comment by kellychoffman** [comment]
> Can the link + button be on a separate line

I meant this layout:

Order needs to be fulfilled
[Fulfill without printing a labe](#)l [Print label & fulfill]

**Comment by kellychoffman** [comment]
We have a winner! Thanks, Marcin.

File: client/extensions/woocommerce/app/order/order-fulfillment/index.js [hunk 3]
```diff
@@ -144,34 +144,32 @@ class OrderFulfillment extends Component {
...
+		const showLabels =
+			wcsEnabled && labelsLoaded && labelsEnabled && hasLabelsPaymentMethod && ! orderCancelled;
+		const labelsLoading = wcsEnabled && ! labelsLoaded && ! orderCancelled;
 
-		if (
-			! isShippable &&
-			( ! wcsEnabled || ( labelsLoaded && hideLabels ) || 'cancelled' === order.status )
-		) {
+		if ( orderFinished && ! labelsLoading && ! showLabels ) {
 			return null;
```
Comment (DanReyLop) [inline client/extensions/woocommerce/app/order/order-fulfillment/index.js]: `if ( orderCancelled )` must also return `null`. Since `orderFinished` is `true` when the order is cancelled, this case _may_ be covered in this conditional, but that requires some mental gymnastics.
