### PR TITLE
Sites Management Page: Fix mshots loader to show our custom loader

### LINKED ISSUE #67340: Site Thumbnail: Don't accidentally show mShots loading image when mShot URL updates
If you already have `/sites` loaded and make a change to one of your sites, the incremented `site.last_updated` will cause a new mShot to be generated.

However, when the mShot is generated, the mShots loading image will display:

image

What should be displaying is the site icon overlaid on a blurred background with the loading state applied.

Discovered while working on #67337

See conversation in p1662136092517739-slack-C0347E545HR

```diff
diff --git a/client/sites-dashboard/components/sites-site-item-thumbnail.tsx b/client/sites-dashboard/components/sites-site-item-thumbnail.tsx
index 49e715a40e..324750e836 100644
--- a/client/sites-dashboard/components/sites-site-item-thumbnail.tsx
+++ b/client/sites-dashboard/components/sites-site-item-thumbnail.tsx
@@ -25,8 +25,8 @@ export const SiteItemThumbnail = ( { site, ...props }: SiteItemThumbnailProps )
 	let siteUrl = site.URL;
 	if ( site.options?.updated_at ) {
 		const updatedAt = new Date( site.options.updated_at );
-		updatedAt.setMinutes( 0 );
-		updatedAt.setSeconds( 0 );
+		// updatedAt.setMinutes( 0 );
+		// updatedAt.setSeconds( 0 );
 		siteUrl = addQueryArgs( siteUrl, {
 			v: updatedAt.getTime() / 1000,

 
```

**Steps to reproduce**
1. Apply the patch above.
2. Navigate to `/sites` in your local environment.
3. Observe a site thumbnail appear as expected for your site.
4. With `/sites` open in one window, make an edit to a Site Editor page in the FSE.
5. Switch back to the `/sites` page.
6. Wait for a moment for the data to refresh.
7. Once the data refreshes and `site.last_updated` is incremented, observe the mShots loading image appear.

### PR DESCRIPTION
**Pull request by vykes-mac**
#### Proposed Changes

* check mshots image intrinsic with to ensure it conforms to the expected responsive image size. Loaded image should be the expected size we passed in.

#### Testing Instructions

- See issue https://github.com/Automattic/wp-calypso/issues/67340 for instructions

####Before
image

####After 
image

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to https://github.com/Automattic/wp-calypso/issues/67340

### CODE REVIEW

File: packages/components/src/site-thumbnail/use-mshots-img.tsx [hunk 1]
```diff
@@ -99,8 +105,8 @@ export const useMshotsImg = (
 		imgProps: {
 			onLoad,
 			onError,
+			srcSet,
 			src: mshotUrl,
-			srcSet: ! isLoading ? srcSet : '',
```
Comment (vykes-mac) [inline packages/components/src/site-thumbnail/use-mshots-img.tsx:113]: @danielbachhuber This fix the issue where the image request happens twice because of how we set the srcset here.

**Review by p-jackson — APPROVED** [review]
Nice! It's fixed the issue for me

**Review by danielbachhuber — APPROVED** [review]
Works great! Thanks for your help with this, @vykes-mac

Also, I discovered that editing the `updated_at` value directly makes this way easier to test 😄 

image

**Comment by p-jackson** [comment]
> Also, I discovered that editing the `updated_at` value directly makes this way easier to test 😄

lol yes 😅 I always forget to test this way!

File: packages/components/src/site-thumbnail/use-mshots-img.tsx [hunk 2]
```diff
@@ -69,18 +69,27 @@ export const useMshotsImg = (
 
 			setIsLoading( true );
 
+			// Loaded image natural width should conform to sizes passed in.
+			const hasExpectedImageDimensions = sizes.some(
+				( size ) => size.width === event.currentTarget.naturalWidth
+			);
```
Comment (sejas) [inline packages/components/src/site-thumbnail/use-mshots-img.tsx:75]: Very smart!, I like it!
