### PR TITLE
Themes: Obtain theme info from canonical source

### LINKED ISSUE #10895: Current Theme Bar: Remove `-wpcom` suffix on Jetpack sites
On a Jetpack site, if a theme was installed from WP.com, it is suffixed with `-wpcom`. While #10526 fixed most of the logic handling, our 'Current Theme' bar still points to `-wpcom`-suffixed themes, while it really should remove that suffix to be consistent with the '...' menu's 'Info' item.

### LINKED ISSUE #11038: Themes: on Jetpack sites when trying a .com theme it jumps briefly in the "Uploaded" list
cap-

Steps to reproduce:

* Open a Jetpack site (on Staging/Horizon)
* Open Themes
* Find a free .com theme at the top, tap ••• and select "Try & Customize"
* Notice it briefly shows up in the top list

It's expected to not show up: .com themes always stay as .com themes (i.e. they are filtered out from the top list).

/ht @lamdayap @richardmuscat

### PR DESCRIPTION
**Pull request by ockham**
Add a new `getCanonicalTheme` selector, which uses theme info from WP.com and WP.org before resorting to the (Jetpack) site the theme is found on. This allows us to remove the [merging of WP.org theme info into JP theme objects](https://github.com/Automattic/wp-calypso/blob/c983d62865b5a9ffe6bf7482d69316cd94a2b607/client/state/themes/selectors.js#L62-L65); the latter requires us to tune the `normalizeWporgTheme` a bit.

Leveraging the technique described in the previous paragraph, this PR then goes on to remove the `-wpcom` suffix in `getActiveTheme` (instead of `isActiveTheme`). Moving this logic one level deeper fixes the Current Theme Bar and Thanks Modal.

Also, this PR removes `receiveTheme` from the `installTheme` action to fix #11038.

Interestingly, we don't need to change error handling in the theme sheet: since `getCanonicalTheme` will try to fetch from WP.com, WP.org, and the given site in order, we will only end up with a `null` result if the theme isn't present on any. This means we only need to check if there was an error fetching from the given site. (What makes things slightly less intuitive, but doesn't rebut this argument, is that the given `siteId`, for a non Jetpack site, can be `wpcom`.)

To test:
* _This is a rather invasive change, so be sure to test the showcase thoroughly!_
* Check that the currently active theme is still handled and displayed correctly everywhere:
  * Themes List (blue highlight, options in '...' menu)
  * Current Theme Bar (theme name displayed? links point to the right destinations?)
  * Thanks Modal
  * Theme Sheet -- CTA button
  * Theme Preview
  * Be sure to cover activation of a previously not installed theme on a JP site.
* Verify that this PR fixes #10895 and #11038.

### CODE REVIEW

**Comment by ockham** [comment]
Seems like this breaks the thanks modal during activation of a WP.com theme on a Jetpack site. Will look into it.

**Comment by ockham** [comment]
Hmm. Maybe this just shift the suffix frontier. The reason seems to be that the thanks modal tries to `getTheme`, now using the unsuffixed ID, while the Redux subtree contains the suffixed one.

**Comment by ockham** [comment]
I'm not sure if we should push things any further using this approach. This keeps coming back as a problem, so maybe it's time to just fully expose suffixed themes as different.

I think we can still solve activation elegantly -- Jetpack install/activate just adds the suffix, and if we keep it everywhere, the thanks modal will continue to work.

If we want to determine whether a theme is a WP.com one, we need a more reliable way than `!! getTheme( state, 'wpcom', themeId )` (because that won't find the suffixed themeId, as [explained here](https://github.com/Automattic/wp-calypso/pull/11089#issuecomment-276837708)). Instead, we need some piece of information that carries over. So maybe it's time to give `theme_uri` a try, at least in combination with `isJetpackSite()`. That'll cover JP sites; we can iterate to find a solution that includes AT.

**Comment by seear** [comment]
> maybe it's time to just fully expose suffixed themes as different.

Yep, agree. Let's acknowledge that wpcom themes on jetpack sites (not AT) will have the suffix, and expose it in URLs.

**Comment by ockham** [comment]
As discussed on Slack, I'll try a different approach and query the `wpcom` subtree with the unsuffixed theme.

**Comment by ockham** [comment]
The algorithm I have in mind is roughly the following:

* If theme is a WP.com theme, use theme info from WP.com (i.e. `getTheme( state, 'wpcom', themeId )`)
* If theme is a WP.org theme, use theme info from WP.org (i.e. `getTheme( state, 'wporg', themeId )`)
* Otherwise, use theme info from JP site's subtree (i.e. `getTheme( state, siteId, themeId )`)

This needs to be done in various places:
* Thanks Modal
* Current Theme Bar
* Theme Sheet
so there should probably be some helper for it.

Furthermore, query components must be used accordingly. Finally, to make things more consistent/less confusing, this will allow us to remove the [merging of WP.org theme info into JP theme objects](https://github.com/Automattic/wp-calypso/blob/c983d62865b5a9ffe6bf7482d69316cd94a2b607/client/state/themes/selectors.js#L62-L65).

**Comment by ockham** [comment]
> so there should probably be some helper for it.

Probably a convenience selector and query component -- maybe even replacing the old `getTheme` and `QueryTheme` with convenience versions, and calling the old one(s) `getRawTheme`...

**Comment by seear** [comment]
This is shaping up nicely. If we get the list filtering right (which will need `theme_uri`) we should be able to continue to not need `theme_uri` in `getThemeInfoFromOriginalSource`.

File: client/state/themes/selectors.js [hunk 1]
```diff
@@ -44,29 +44,28 @@ export const getTheme = createSelector(
...
-		return {
-			...theme,
-			...pick( wporgTheme, [ 'demo_uri', 'download', 'taxonomies' ] )
-		};
+		return manager.getItem( themeId );
 	},
 	( state ) => state.themes.queries
 );
 
+export function getThemeInfoFromOriginalSource( state, siteId, themeId ) {
```
Comment (seear) [inline client/state/themes/selectors.js]: Wondering if this could be `getCanonicalTheme`? The logic does mirror the similarly named query component.

Comment (ockham) [inline client/state/themes/selectors.js]: Jinx: b1f18d4 😄

**Comment by ockham** [comment]
Okay, this PR now includes the changes discussed in the comments. I've updated the PR desc and would appreciate another round of reviews. Since it's quite invasive, please give it some good testing (suggested shortlist in PR desc). cc @folletto

**Comment by folletto** [comment]
Tasks checked on Chrome:

1. Themes List → has blue highlight for active theme — ✅ 
2. Themes List → shows all the options in the ••• menu (com) — ✅ 
3. Themes List → shows all the options in the ••• menu (jetpack) — ✅ 
4. Current Theme Bar → theme name displayed — ✅ 
5. Current Theme Bar → links point to the right destinations — ✅ 
6. Activate Theme → Thanks Modal (check buttons and links) — ✅ 
7. Theme Sheet → pick button — ⚠️ 
8. Theme Preview working — ✅  
9. Jetpack site → activate .com theme — ✅ 

**7. Theme Sheet → pick button**

Opening _directly_ the sheet throws a lot of errors without site specified, and with a site specified just doesn't load, it flashes the right content, then reverts to the loading state ([screen shot](https://cloud.githubusercontent.com/assets/4389/23065368/14e4ff62-f50d-11e6-82ad-e92e9e063c48.png)).

Checking more, it seems the errors are all over, not just the sheet.

**Comment by ockham** [comment]
@folletto Thanks for testing, and good spot. Pushed a commit to fix the issue, can you try again?

**Comment by folletto** [comment]
Tasks checked on Chrome:

1. Themes List → has blue highlight for active theme — ✅ 
2. Themes List → shows all the options in the ••• menu (com) — ✅ 
3. Themes List → shows all the options in the ••• menu (jetpack) — ✅  
4. Current Theme Bar → theme name displayed — ✅ 
5. Current Theme Bar → links point to the right destinations — ✅ 
6. Activate Theme → Thanks Modal (check buttons and links) — ✅ 
7. Theme Sheet → pick button — ✅ 
8. Theme Preview working — ✅ 
9. Jetpack site → activate .com theme — ✅ 
10. Jetpack site → theme doesn't jump up in the top list — ✅ 

---

Everything seems working.

I'm however getting this error in the console still, seems unrelated but doesn't show in production... so I don't know.

screen shot 2017-02-17 at 13 25 39

**Comment by ockham** [comment]
@folletto I remember I saw those for a while, too. I think they're unrelated, and for me, they disappeared after I cleared IndexedDB, so you might want to try that.

Aside, I noticed a propType warning for the multi-site sheet. I'll push a commit shortly to fix it.

**Comment by folletto** [comment]
> after I cleared IndexedDB, so you might want to try that.

Confirmed.

**Comment by seear** [comment]
I think we could remove use of `siteIdOrWpcom` from the theme sheet with this PR, by making `siteId` optional when calling the canonical query and selector?

Continued use of `siteIdOrWpcom` lets us have a neat implementation such as [this](https://github.com/Automattic/wp-calypso/pull/11330/files#diff-870d9a4747b5402166090bd61bc7b207R64), but I feel removing as many uses of this idiom as possible would be less confusing in the long run.

**Comment by ockham** [comment]
> I think we could remove use of `siteIdOrWpcom` from the theme sheet with this PR, by making `siteId` optional when calling the canonical query and selector?

Yeah, I was on the fence about this. Initially, I thought we'd be compromising on separated concerns, but now that I think about it again, I think we wouldn't 😄 

> Continued use of `siteIdOrWpcom` lets us have a neat implementation such as [this](https://github.com/Automattic/wp-calypso/pull/11330/files#diff-870d9a4747b5402166090bd61bc7b207R64), but I feel removing as many uses of this idiom as possible would be less confusing in the long run.

+1 to that, yeah.

File: client/components/data/query-canonical-theme/index.jsx [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+
+/**
+ * Internal dependencies
+ */
+import QueryTheme from 'components/data/query-theme';
+import { isWpcomTheme, isWporgTheme } from 'state/themes/selectors';
+
+const QueryCanonicalTheme = ( { siteId, themeId, isWpcom, isWporg } ) => (
+	<div>
+		<QueryTheme themeId={ themeId } siteId="wpcom" />
```
Comment (budzanowski) [inline client/components/data/query-canonical-theme/index.jsx]: If I understand correctly if `isWpcom` is `true` we do not need to render `QueryTheme` for wpcom, so maybe a guard would be useful. Same for org.

Comment (ockham) [inline client/components/data/query-canonical-theme/index.jsx]: Hmm. My take here was that normally, we wouldn't know initially, so `isWpcom` (and `isWporg`) would default to falsey; and even after rendering the query component, I thought it wouldn't hurt (and maybe make for a stabler behavior) to keep them around. The individual `QueryTheme` components won't re-render as long as their props don't change, so they shouldn't impact performance negatively.

Maybe we really need to check `getCanonicalTheme`, and bail early if it returns falsey? :thinking:

Comment (ockham) [inline client/components/data/query-canonical-theme/index.jsx]: (Bail before rendering the individual `QueryTheme` components, I mean.)

Comment (ockham) [inline client/components/data/query-canonical-theme/index.jsx]: Tricky. I guess checking `getCanonicalTheme` doesn't make that much sense either, since we can't know if the theme exists at all...

Comment (budzanowski) [inline client/components/data/query-canonical-theme/index.jsx]: I don't think that it is worth investigating given the fact that it works the way it is now and that there will be no re-render.

File: client/state/themes/actions.js [hunk 3]
```diff
@@ -423,8 +423,14 @@ export function installTheme( themeId, siteId ) {
...
 		return wpcom.undocumented().installThemeOnJetpack( siteId, themeId )
-			.then( ( theme ) => {
-				dispatch( receiveTheme( theme, siteId ) );
+			.then( ( /* theme */ ) => {
+				// We do not `dispatch( receiveTheme( theme, siteId ) )` here because
+				// in our UI, themes from WP.com (and WP.org) are already present in
+				// a separate list, and we do not want to duplicate them.
+				// Arguably, this is too tightly coupled to our UI, but because pagination,
+				// it's easier to filter _before_ storing themes in ThemeQueryManager than
+				// when fetching themes from it.
```
Comment (ockham) [inline client/state/themes/actions.js]: I'll remove the lower half, which is a bit over-specific here. The upper half I'd like to keep around just so no-one feels the urge to add that back in a couple of months.

File: client/state/themes/selectors.js [hunk 4]
```diff
@@ -44,30 +44,28 @@ export const getTheme = createSelector(
...
+ * and multiple screenshots, and a preview URL) first, then WP.org (which has a
+ * preview URL), then the given JP site.
+ *
+ * @param  {Object}  state   Global state tree
+ * @param  {Number}  siteId  Jetpack Site ID to fall back to
+ * @param  {String}  themeId Theme ID
+ * @return {?Object}         Theme object
+ */
+export function getCanonicalTheme( state, siteId, themeId ) {
+	const source = find( [ 'wpcom', 'wporg', siteId ], s => getTheme( state, s, themeId ) );
```
Comment (budzanowski) [inline client/state/themes/selectors.js]: Could we just 
`return getTheme( state, 'wpcom', themeId ) ||
    getTheme( state, 'wporg', themeId ) || 
    getTheme( state, siteId, themeId );`

Comment (budzanowski) [inline client/state/themes/selectors.js]: With proper formatting ofc.

Comment (ockham) [inline client/state/themes/selectors.js]: Hmm... Doesn't read that much nicer to me TBH 😄

File: client/components/data/query-canonical-theme/index.jsx (hunk 2 above)
Comment (ockham) [inline client/components/data/query-canonical-theme/index.jsx]: I had another idea how we could do this. I'll push a commit shortly...

File: client/state/themes/selectors.js (hunk 4 above)
Comment (budzanowski) [inline client/state/themes/selectors.js]: Sure. `getTheme` will work with undefined without a problem so `find` is OK. And my suggestion saves one call to `getTheme` but that may be in fact unnecessary optimization.

Comment (ockham) [inline client/state/themes/selectors.js]: (Specifically, I'd like to have some sort of loop here in order to not repeat typing `getTheme()` needlessly.)

**Comment by ockham** [comment]
Reverting the alternative `QueryCanonicalTheme` implementation since it was complicating things.
