### PR TITLE
Post Editor: Prevent error loading posts with certain slug sequences

### LINKED ISSUE #17572: Editor: "Malformed" slugs prevent loading
This looks like a case of calling `decodeURI` and/or `decodeURIComponent` without wrapping it in a try / catch block.

#### Steps to reproduce

1. Starting at URL: https://wordpress.com/post/ (choose a site if your user has more than one)
2. Enter a post title with in invalid UTF sequence -- for example `%e42`
3. Click `Publish`

#### What I expected
For the post to be published without error

#### What happened instead
The post is published, but I'm met with an error in the console:
`Uncaught URIError: URI malformed`
...and the editor hangs. The `Update` button (formerly `Publish`) is indicating progress & `Saving...` shows in the upper left:

screen shot 2017-08-28 at 4 33 15 pm

If you navigate back to `/posts`, the post will appear without incident, but if you click `Edit` (or browse to the edit URL directly), the post content never loads and the console shows the same error.

### PR DESCRIPTION
**Pull request by jblz**
"Malformed" character sequences in post slugs are preventing loading because the slugs are [passed](https://github.com/Automattic/wp-calypso/blob/ba56bddbe087af6ec000dd2f9f85eeda77f13c50/client/state/posts/selectors.js#L434) through [`decodeURI`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI) which throws under certain circumstances.

This adds a utility function to `lib/url` called `decodeURIIfValid` which wraps `decodeURI` in a try / catch block.

Since `decodeURIComponent` is subject to the same error and is used in various places across the codebase, an analog called `decodeURIComponentIfValid` is added here as well.

Fixes #17572

#### Run automated tests

`npm run test-client client/state/posts/`

#### Manually test

* Starting at URL: `/post/` (choose a site if your user has more than one)
* Enter a post title with in invalid UTF sequence -- for example `%e42`
* Click `Publish`

The post should be published without error.

* Starting at URL: `/posts/` (choose a site if your user has more than one)
* Locate the post you just created
* Click `Edit`

The post editor should be loaded without error.

### CODE REVIEW

File: client/lib/url/index.js [hunk 1]
```diff
@@ -180,7 +180,41 @@ function omitUrlParams( url, paramsToOmit ) {
...
 }
 
+/**
+ * Wrap decodeURI in a try / catch block to prevent `URIError` on invalid input
+ * @param  {String} encodedURI URI to attempt to decode
+ * @return {String}            Decoded URI (or passed in value on error)
+ */
+function decodeURIIfValid( encodedURI ) {
+	if ( ! ( isString( encodedURI ) || has( encodedURI, 'toString' ) ) ) {
+		throw new Error( 'Invalid input' );
```
Comment (gwwar) [inline client/lib/url/index.js]: What's the purpose for throwing here? We don't appear to be handling this case in the selector.

**Comment by lancewillett** [comment]
@jblz Ready to merge this one?

File: client/lib/url/index.js (hunk 1 above)
Comment (jblz) [reply client/lib/url/index.js]: @gwwar the thought was to prevent unexpected behavior when providing a non-string to `decodeURI` & `decodeURIComponent`.  For example: 
```
> x = {};
> decodeURIComponent(x);
"[object Object]"
> y = null;
> decodeURI( y );
"null"
```

Since there's no type checking & no error thrown, invalid usage will be potentially masked.

You're right, though. The case isn't checked for in the calling selector (where `postSlug` has the potential to be `undefined`). 

What if, instead of throwing, these helpers just return an empty string on non-string input?

Comment (gwwar) [reply client/lib/url/index.js]: Thanks for the context @jblz! Your suggestion sounds reasonable to me.
