### PR TITLE
Editor: Prevent blank screen when pressing back button

### LINKED ISSUE #20484: Editor and Preview: Editor back button loads blank screen
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/view/sporadicthoughts.net (or, you know, for your site)
2. Click the write button in the masterbar
3. Once the editor loads, click the back arrow in the top-left
4. You'll wind up looking at a blank screen

#### What I expected
I expected to be back at the `/view/` screen.

#### What happened instead
A blank screen loaded

#### Browser / OS version
Latest Safari and latest OS X

#### Screenshot / Video
screen shot 2017-12-04 at 5 05 36 pm

### PR DESCRIPTION
**Pull request by frontdevde**
## This PR
- prevents an issue where a blank screen was showing after the back button was pressed
- fixes #20484 reported by @shaunandrews 

## Issue & fix
The issue was caused by an error being thrown in `TinyMCEDropZone`. On `componentWillUnmount` there are three `editor.dom.unbind(editor.getWin(), 'event', this.replaceEvent )` calls that try to unbind attached events. This fails as `editor.dom.win`, which the functions are trying to get via `editor.getWin()`, is `null` at the point the functions are being called.

The reason `editor.dom.win` is `null`, is that the `componentWillUnmount` function in `TinyMCEDropZone` gets called after the editor has already been removed via the `destroyEditor()` (see `tinymce/index.js`). At that point, there is probably no need anymore to unbind any events. 

Not sure if there are other `TinyMCEDropZone` use cases where the editor doesn't get destroyed or gets removed after `TinyMCEDropZone`. Therefore going to fix this issue by wrapping the unbind functions in a check for `editor.dom.win` being available.

## How to test

1. Use the calypso.live link below or check out locally
2. Go to: https://wordpress.com/view/yoursitename
3. Click the write button in the Masterbar
4. Once the editor loads, click the back arrow in the top-left
5. You should be back at the `/view/` screen

**Before** 

screen shot 2017-12-04 at 20 15 24

**After**

screen shot 2017-12-04 at 20 14 38

### CODE REVIEW

**Comment by shaunandrews** [comment]
Working great for me now! Thanks!

**Comment by alisterscott** [comment]
Tests well - thanks

File: client/components/tinymce/plugins/media/drop-zone.jsx [hunk 1]
```diff
@@ -48,10 +48,12 @@ class TinyMCEDropZone extends React.Component {
 
 	componentWillUnmount() {
 		const { editor } = this.props;
-		editor.dom.unbind( editor.getWin(), 'dragenter', this.redirectEditorDragEvent );
 		window.removeEventListener( 'dragleave', this.stopDragging );
-		editor.dom.unbind( editor.getWin(), 'dragleave', this.stopDragging );
-		editor.dom.unbind( editor.getWin(), 'dragover', this.fakeDragEnterIfNecessary );
+		if ( editor.getWin() ) {
```
Comment (lamosty) [inline client/components/tinymce/plugins/media/drop-zone.jsx]: I think we don't even need this; see #20499.

Comment (frontdevde) [reply client/components/tinymce/plugins/media/drop-zone.jsx]: Like I stated in the PR description, I only added this check in case there are any use cases where the editor doesn't get destroyed or gets removed after `TinyMCEDropZone`. If you're confident that that won't be the case, then I'm confident to go with your approach of simply deleting the unbind code.
