### PR TITLE
Stats: Include a post nudge on last post summary components on sites with no posts

### LINKED ISSUE #5290: Stats: Latest Post Peformance stuck in loading for sites with no posts
With the new redux approach taken in #5008 - it seems we may have introduced a regression to the Latest Post Performance component.  When viewing the insights page on a site that has no posts, the component perpetually shows the loading status:

stats_ _wordpress_com

I believe in the prior approach, we would hide the component if no post was returned by the API.  An alternate fix would be to include a post nudge when no post is found like we do on the post listing page:

blog_posts_ _let_s_pull_together_ _wordpress_com

/cc @youknowriad

### PR DESCRIPTION
**Pull request by youknowriad**
This should fix #5290 

The following nudge is displayed on sites with no posts.

capture d ecran 2016-05-09 a 19 22 40

**Testing instructions**
The component can have different states : 
 - The site have no posts but we're refreshing the query results => in this case the text is hidden
 - The site have no posts and the query is not requesting => we display the nudge
 - The site have posts => we display the stats and the post title

cc @timmyc

### CODE REVIEW

File: client/my-sites/stats/post-performance/index.jsx [hunk 1]
```diff
@@ -70,14 +73,12 @@ const StatsPostPerformance = React.createClass( {
...
 
 	render() {
-		const { site, query, post, loading } = this.props;
+		const { site, query, post, isRequesting } = this.props;
 		const postTime = post ? this.moment( post.date ) : this.moment();
-		const cardClass = classNames( 'stats-module', 'stats__latest-post-summary', 'is-site-overview', {
-			'is-loading': loading,
-			'is-hidden': ! loading && ! post
-		} );
+		const cardClass = classNames( 'stats-module', 'stats__latest-post-summary', 'is-site-overview' );
```
Comment (timmyc) [inline client/my-sites/stats/post-performance/index.jsx]: I think retaining the loading state/class here is still worthwhile to show that a network request is in-progress.

**Comment by timmyc** [comment]
Left a comment that I think we do need to maintain the loading state - see the following screen grabs:

__Loading site with no posts__
no-post

__Loading site with post__
has-post

/cc @jancavan for a design review as well.

File: client/my-sites/stats/post-performance/index.jsx (hunk 1 above)
Comment (youknowriad) [inline client/my-sites/stats/post-performance/index.jsx]: the two classes were only used to hide content on loading state, I replaced those with "ifs" to make a code less confusing.

**Comment by youknowriad** [comment]
@timmyc Tks for the review, I'll take a look at how to keep the loading state until the post stat finished the initial loading.

**Comment by youknowriad** [comment]
@timmyc I've reuse the StatsModulePlaceholder component while loading (this displays a spinner after some milliseconds) to stay consistent with all the stats UI. Is this ok ?

File: client/my-sites/stats/post-performance/index.jsx [hunk 2]
```diff
@@ -112,12 +113,31 @@ const StatsPostPerformance = React.createClass( {
...
+							</div>
+						) : null
+					}
+					{ ! post && ! isRequesting
+						? (
+							<div className="module-content-text is-empty-message is-error">
+								<p className="is-empty-message">
+									{ this.translate( 'You haven\'t published any posts yet.' ) }
+								</p>
+								<p>
```
Comment (jancavan) [inline client/my-sites/stats/post-performance/index.jsx]: Is it possible to use a <button> here since it's an action and looks like a button?

**Comment by jancavan** [comment]
This looks good. One minor comment: there's too much padding above the button and too little below it. Something like this would be good:

screenshot-2016-05-11-09 45 59

Should we also add an event to this button?

File: client/my-sites/stats/post-performance/index.jsx (hunk 2 above)
Comment (youknowriad) [inline client/my-sites/stats/post-performance/index.jsx]: I'm sorry, it's certainly my "english", but I've not understood what you mean ?

**Comment by youknowriad** [comment]
@jancavan I've just fixed the padding.

capture d ecran 2016-05-11 a 19 20 55

File: client/my-sites/stats/post-performance/index.jsx [hunk 3]
```diff
@@ -112,12 +113,31 @@ const StatsPostPerformance = React.createClass( {
...
+									<a href={ newPostUrl } className="button is-primary">
```
Comment (jancavan) [inline client/my-sites/stats/post-performance/index.jsx]: Sorry, Github stripped out the word `<button>`.

Is it possible to use `<button>` here instead of `<a>` since it's an action and not just a link?

Comment (youknowriad) [inline client/my-sites/stats/post-performance/index.jsx]: Actually, It's is just a link. There's nothing done here apart going to the "new post" page.

File: client/my-sites/stats/post-performance/index.jsx [hunk 4]
```diff
@@ -70,14 +74,13 @@ const StatsPostPerformance = React.createClass( {
...
+		const loading = ! site || isRequesting;
 		const postTime = post ? this.moment( post.date ) : this.moment();
-		const cardClass = classNames( 'stats-module', 'stats__latest-post-summary', 'is-site-overview', {
-			'is-loading': loading,
-			'is-hidden': ! loading && ! post
-		} );
+		const cardClass = classNames( 'stats-module', 'stats-post-performance', 'is-site-overview' );
 
-		const summaryUrl = post ? '/stats/post/' + post.ID + '/' + this.props.site.slug : '#';
+		const newPostUrl = site ? '/post/' + site.ID : '/post';
```
Comment (timmyc) [inline client/my-sites/stats/post-performance/index.jsx]: we should use the `site.slug` for this URL.

File: client/my-sites/stats/post-performance/index.jsx [hunk 5]
```diff
@@ -112,12 +116,31 @@ const StatsPostPerformance = React.createClass( {
...
+						) : null
+					}
+					{ ! loading && ! post
+						? (
+							<div className="module-content-text is-empty-message is-error">
+								<p className="stats-post-performance__no-posts-message">
+									{ this.translate( 'You haven\'t published any posts yet.' ) }
+								</p>
+								<div className="stats-post-performance__start-post">
+									<a href={ newPostUrl } className="button is-primary">
```
Comment (timmyc) [inline client/my-sites/stats/post-performance/index.jsx]: I think @jancavan had brought this up in a prior comment, but perhaps we can just utilize the [button component](https://github.com/Automattic/wp-calypso/tree/master/client/components/button) here.

**Comment by timmyc** [comment]
@youknowriad couple more minor tweaks noted above, but this is functionally working great for me. If we could address those two items and do a rebase then I'd love to get this merged in.

**Comment by jancavan** [comment]
Are we adding an event to this button @timmyc?

**Comment by timmyc** [comment]
@jancavan as in dropping some tracks or GA events?  Might be valuable to do so.

**Comment by jancavan** [comment]
@timmyc yup, a Tracks event would be great.

**Comment by youknowriad** [comment]
@timmyc I've just updated the PR. About the `Button` I thought @jancavan was talking about the html `button` tag instead of the component. my bad. I've also added a track event. 

Let me know if there's anything else :)

File: client/my-sites/stats/post-performance/style.scss [hunk 6]
```diff
@@ -0,0 +1,7 @@
+.stats-post-performance__start-post {
+	padding-bottom: 26px;
+}
+
+.stats-post-performance__no-posts-message {
+	margin-bottom: 1em;
```
Comment (jancavan) [inline client/my-sites/stats/post-performance/style.scss]: Is there a reason why this is using `em` and the other one is in `px`? Perhaps just use `px` for both for consistency? I think `14px` will do.

Comment (youknowriad) [inline client/my-sites/stats/post-performance/style.scss]: Actually, there is a reason. This overrides a parent "em" margin and I found that using "ems" keeps the spacing good no matter the font-size of the message. 

That said, I can still use px if you prefer :).

Comment (jancavan) [inline client/my-sites/stats/post-performance/style.scss]: Well, you could retain `em` if need be, but I wasn't sure why it's two different units instead of just using one or the other.

Comment (youknowriad) [inline client/my-sites/stats/post-performance/style.scss]: Just upated to `px` to get a consensus here :)

**Comment by youknowriad** [comment]
@timmyc I took all the remarks into account. I rebased. I think the tests are failing because github is experimenting some issues right now. I would love to see this merged :)

**Comment by jancavan** [comment]
Design LGTM 👍

**Comment by timmyc** [comment]
LGTM too.  Thanks again @youknowriad
