### PR TITLE
Fix header text on domain/plans step

### LINKED ISSUE #67599: The domain step in /start has “Back to Sites” back button. It should have the flow title and WP logo
### Details

Add header texts for tailored flows on domain / plans step

### Checklist

_No response_

### Related

_No response_

### PR DESCRIPTION
**Pull request by renancarvalho**
## Proposed Changes

Add Tailored flow header on domain and plans step

Before:
image

Now:
image

## Testing Instructions

- Pull this branch and run yarn start
- Go to `/setup/intro?flow=link-in-bio` or `/setup/intro?flow=newsletter`
- Navigate until the domain step 
- Check if the Flow name is present as the header 

Related to #67599
Fixes #67599

### CODE REVIEW

File: client/signup/main.jsx [hunk 1]
```diff
@@ -728,6 +728,12 @@ class Signup extends Component {
 		}
 	}
 
+	getPageTitle() {
+		if ( this.props.flowName.toLowerCase() === LINK_IN_BIO_FLOW ) {
+			return 'Link in Bio';
+		}
+		return this.props.flowName;
+	}
```
Comment (arcangelini) [inline client/signup/main.jsx]: This is already accessible in `this.props.pageTitle` [I set it up in the flow-pure.js](https://github.com/Automattic/wp-calypso/blob/52dbafe48d5392d04920e9d6271b4e2bce8e1063/client/signup/config/flows-pure.js#L137-L139)

File: client/signup/main.jsx [hunk 2]
```diff
@@ -762,6 +768,7 @@ class Signup extends Component {
 								flowName: this.props.flowName,
 								stepName: this.props.stepName,
 							} }
+							pageTitle={ this.getPageTitle() }
```
Comment (arcangelini) [inline client/signup/main.jsx:770]:
```suggestion
							pageTitle={ this.props.pageTitle }
```

Also, may need something to hide this if the nav buttons are present

Markup 2022-09-11 at 19 53 31

File: client/signup/tailored-flow-processing-screen/style.scss [hunk 3]
```diff
@@ -7,6 +7,10 @@
 		.signup-header {
 			z-index: 1;
 
+			h1 {
+				text-transform: capitalize;
+			}
+
```
Comment (arcangelini) [inline client/signup/tailored-flow-processing-screen/style.scss]: Since the page title is set, you likely won't need this also.

**Review by arcangelini — CHANGES_REQUESTED** [review]
Looks good! Just a couple comments and it seems like theres a mashup when viewing non-tailored flows.

File: client/signup/main.jsx (hunk 1 above)
Comment (renancarvalho) [reply client/signup/main.jsx]: Perfect Tony! Thank you, will be addressed on the next commit 🎖️

File: client/signup/main.jsx (hunk 2 above)
Comment (renancarvalho) [reply client/signup/main.jsx:770]: Good catch! thanks!

File: client/signup/tailored-flow-processing-screen/style.scss (hunk 3 above)
Comment (renancarvalho) [reply client/signup/tailored-flow-processing-screen/style.scss]: Removed indeed! next commit has the fix. Thank you.

File: client/signup/main.jsx (hunk 2 above)
Comment (escapemanuele) [reply client/signup/main.jsx:770]: Do we want to show the page title in every flow, if no back buttons are present? 
If so I think we can use `pageTitle={ this.props.pageTitle }`, otherwise it'd be good to maintain the check that @renancarvalho added :)

Comment (renancarvalho) [reply client/signup/main.jsx:770]: I think it is the other way around, we just show the page title for tailored flow( LiB and NL ), the 'normal' is the back button which has two 'versions' one 'back to sites' and the other one just 'back'. ( just kept the original behaviour )

@alshakero how do you think it should be?

**Review by arcangelini — APPROVED** [review]
Perfecto!

File: client/signup/main.jsx (hunk 2 above)
Comment (alshakero) [reply client/signup/main.jsx:770]: We shouldn't touch any other flows. Flows are A/B tested to the punctuation levels, we can't just change stuff. Let's keep the check.

**Review by alshakero — APPROVED** [review]
LGTM! Addressed the question below.
