### PR TITLE
Domains: Use ISO8601 format for dates

### LINKED ISSUE #13301: Domains: Dates in localized formats interfere with domain warnings
#### Steps to reproduce
1. Have a non-English locale (for example, `it`).
2. Buy a domain.
3. Go to Domain Management after the initial 72 hours.

#### What I expected
No notices - the DNS should have propagated by now.

#### What happened instead
A notice is still shown - the localized date is not parsed correctly.

#### Context / Source
#user-report

Hattip to @dromero20 for the report!

### PR DESCRIPTION
**Pull request by klimeryk**
Previously, we've returned localized strings from the backend for those dates. This had several disadvantages, the biggest being: messing up the parsing with non-en locales and missing the time part of the registration date.

Now, we use the ISO8601 format that should prevent those issues. We rely on i18n-calypso to provide locale-specific date format, that's accurate for the current locale, not just USA.

To keep everything consistent, I've made sure that we keep the `moment` versions in memory (they are more developer friendly and there's no reason to re-create them from strings every time we want to format or compare a date), but store the raw strings in redux.

### Testing
Requires `D5304-code` on the backend to introduce the 1.2 version of the endpoint.
Check out Domain Management section in Calypso for any differences in dates between the new endpoint and the old one.
Make sure that the domain warnings are shown when needed (and not when not needed ;)).

Be sure to test using non-`en` locale too.

Before (`en`):
screen shot 2017-04-25 at 12 40 49

After (`en`) - spoiler: there should be no difference:
screen shot 2017-04-25 at 12 41 06

Before (`pl`) - this is a weird format for a Polish locale - we don't capitalize the months like that and the month is missing declension:
screen shot 2017-04-25 at 12 37 20

After (`pl`) - looking good now:
screen shot 2017-04-25 at 12 36 49

Fixes #13301

### CODE REVIEW

**Comment by klimeryk** [comment]
@umurkontaci Could you please help me figure out why this test is failing? https://github.com/Automattic/wp-calypso/blob/15e15c2ee3ae54a0628978dceccfe2eb61735c0f/client/my-sites/upgrades/domain-management/edit/test/mapped-domain.js#L55-L66
I'm sure I'm missing some magic invocation or something, but for the ~~love~~ hate of JavaScript, I can't figure out what exactly is missing/changed there.

**Comment by umurkontaci** [comment]
I'm guessing you are mocking it out way too late. Mocking should go on line #35, inside `useMockery`:

https://github.com/Automattic/wp-calypso/blob/15e15c2ee3ae54a0628978dceccfe2eb61735c0f/client/my-sites/upgrades/domain-management/edit/test/mapped-domain.js#L35

File: client/state/sites/domains/selectors.js [hunk 1]
```diff
@@ -65,12 +65,14 @@ export function getDecoratedSiteDomains( state, siteId ) {
 		return {
 			...domain,
 
-			// Add registration moment from registrationDate
```
Comment (aidvu) [inline client/state/sites/domains/selectors.js]: Isn't this whole chunk here to avoid storing `moment` dates? This can probably just go away, because as far as I can see, you won't have any of the `...Date` variables here?

File: client/state/sites/domains/test/fixture.js [hunk 2]
```diff
@@ -17,7 +17,7 @@ export const SITE_ID_SECOND = 77203074;
 
 // testing primary-domain
 export const DOMAIN_PRIMARY = {
-	autoRenewalDate: 'February 7, 2017',
```
Comment (aidvu) [inline client/state/sites/domains/test/fixture.js]: Do we need these?

File: client/lib/domains/assembler.js [hunk 3]
```diff
@@ -37,8 +37,7 @@ function createDomainObjects( dataTransferObject ) {
 			privateDomain: domain.private_domain,
 			pendingTransfer: domain.pending_transfer,
 			registrar: domain.registrar,
-			registrationDate: domain.registration_date,
```
Comment (aidvu) [inline client/lib/domains/assembler.js]: Maybe we should store all dates, and then use them in the decorator to turn them into `moment` objects?

File: client/my-sites/upgrades/domain-management/edit/mapped-domain.jsx [hunk 4]
```diff
@@ -117,4 +117,5 @@ const MappedDomain = React.createClass( {
 	}
 } );
 
+export { MappedDomain };
```
Comment (gwwar) [inline client/my-sites/upgrades/domain-management/edit/mapped-domain.jsx]: This can just be `export MappedDomain`; or `export const MappedDomain = //...` above

Comment (aidvu) [inline client/my-sites/upgrades/domain-management/edit/mapped-domain.jsx]: I didn't do it above because the `linter` would start crying. :sob: If I remove the brackets `linter` cries again. :sob:

File: client/my-sites/upgrades/domain-management/edit/test/mapped-domain.js [hunk 5]
```diff
@@ -26,7 +27,8 @@ describe( 'mapped-domain', () => {
 				name: 'neverexpires.com',
 				expirationMoment: null
 			},
-			settingPrimaryDomain: false
+			settingPrimaryDomain: false,
+			translate: identity
```
Comment (gwwar) [inline client/my-sites/upgrades/domain-management/edit/test/mapped-domain.js]: We can actually set this in the MappedDomain component
```jsx
getDefaultProps() {
    return {
        translate: identity
    };
}
```

Comment (aidvu) [inline client/my-sites/upgrades/domain-management/edit/test/mapped-domain.js]: This would be better if someone would use the other `export`, but now that I think about it, would be better if we didn't set it in there, so no one would use it `unlocalized`. :D

File: client/my-sites/upgrades/domain-management/edit/mapped-domain.jsx (hunk 4 above)
Comment (gwwar) [inline client/my-sites/upgrades/domain-management/edit/mapped-domain.jsx]: Whoops, you're correct here on the `export { MappedDomain };` syntax.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export

The top line linter complains about the `React.createClass` usage if we modify the line 👍  So perfectly fine to avoid here.

File: client/my-sites/upgrades/domain-management/edit/test/mapped-domain.js (hunk 5 above)
Comment (gwwar) [inline client/my-sites/upgrades/domain-management/edit/test/mapped-domain.js]: But this one is totally optional, since it looks like we're stubbing a lot of stuff here.

File: client/state/sites/domains/selectors.js (hunk 1 above)
Comment (klimeryk) [inline client/state/sites/domains/selectors.js]: You're mistaking the two assemblers - the Redux one (https://github.com/Automattic/wp-calypso/blob/master/client/state/sites/domains/assembler.js) and the.. umm.. reflux (or whatever was hip back then) one (https://github.com/Automattic/wp-calypso/blob/master/client/lib/domains/assembler.js).

For the Redux one, we keep the raw dates, because that's what we want to store in the tree/offline/etc. But when fetching the domain, we want to decorate them with the `moment` versions, because those are more developer-friendly, plus we usually convert them to those anyway.

For the old assembler, it's the same idea as with the above decorator, but since we don't store it anywhere, we can expose the `moment` versions without the need for an explicit decorator. And I'm sure you agree that we don't need the raw versions of dates if we have the `moment` ones.

File: client/state/sites/domains/test/fixture.js (hunk 2 above)
Comment (klimeryk) [inline client/state/sites/domains/test/fixture.js]: Yes, they're used by these tests: https://github.com/Automattic/wp-calypso/blob/4b685bbddf086e8841dc5fc1a909519da079d0fa/client/state/sites/domains/test/selectors.js#L28 Those tests, apparently compare `DOMAIN_PRIMARY` and `REST_API_SITE_DOMAIN_FIRST`. Honestly, I don't see the point of such tests, but :man_shrugging: They were there before, I modified them according to the changes in the rest of the PR.

File: client/lib/domains/assembler.js (hunk 3 above)
Comment (klimeryk) [inline client/lib/domains/assembler.js]: See my comment above: https://github.com/Automattic/wp-calypso/pull/13365#discussion_r113791430

File: client/my-sites/upgrades/domain-management/edit/mapped-domain.jsx [hunk 6]
```diff
@@ -110,10 +111,11 @@ const MappedDomain = React.createClass( {
...
 			<VerticalNavItem path={ path }>
-				{ this.translate( 'DNS Records' ) }
+				{ this.props.translate( 'DNS Records' ) }
 			</VerticalNavItem>
 		);
 	}
 } );
 
-module.exports = MappedDomain;
+export { MappedDomain };
```
Comment (klimeryk) [inline client/my-sites/upgrades/domain-management/edit/mapped-domain.jsx]: I'm grateful that this fixes the test but.... _why_? 😅 Wasn't the whole idea of `localize` that it eased testing? Maybe it's the test that should be fixed? (though, I can't see how either :/)

Comment (gwwar) [inline client/my-sites/upgrades/domain-management/edit/mapped-domain.jsx]: We test the pure components, because it makes things much easier to test, and we're not interested in testing the whole system together (we have full e2e tests for that) just the behavior of that UI component. I think http://ericnish.io/blog/how-to-unit-test-react-redux-components/ is a decent write up on the reasoning behind this. 

If folks think this test is not useful, consider removing it and maybe replacing it with a cleaner unit test, or a new e2e test in https://github.com/Automattic/wp-e2e-tests

File: client/state/sites/domains/selectors.js (hunk 1 above)
Comment (aidvu) [inline client/state/sites/domains/selectors.js]: 🙇 Thanks for the explanation! Missed the fact that those aren't used for the same data. :(

File: client/my-sites/upgrades/domain-management/edit/mapped-domain.jsx (hunk 6 above)
Comment (klimeryk) [inline client/my-sites/upgrades/domain-management/edit/mapped-domain.jsx]: Thanks for the link, @gwwar - now I understand the reason better. My biggest beef with this is that it adds an export that is essentially only useful for testing (and should actually not be used for anything else). But I guess we've got to make compromises sometimes :)
Thanks again! 🙇

Comment (aidvu) [inline client/my-sites/upgrades/domain-management/edit/mapped-domain.jsx]: If it extended the class, you could one line it. `export const MappedDomain`. Easier to get along with I guess. :)
