### PR TITLE
Composite checkout: Hide alternate email when G Suite is not in cart

### LINKED ISSUE #44426: Checkout: Editing email address in checkout results in old and new addresses being shown
#### Steps to reproduce

1. For a site you already own, go to Manage -> Domains and click on "Add a domain to this site".
2. Search for and select a domain.
3. Proceed to checkout.
4. In the checkout page, click on the "Edit" button next to Contact Information.
5. Update your email address and click on Continue.

#### What I expected
I expected the new email address to appear.

#### What happened instead
Both the old _and_ new addresses were shown.
Before:
Screenshot 2020-07-24 at 15 06 54
After:
Screenshot 2020-07-24 at 15 07 13

#### Browser / OS version
Chrome 84 on MacOS.

#### Context / Source

#manual-testing

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

Since the `alternateEmail` field is only used by G Suite (see https://github.com/Automattic/wp-calypso/pull/35920), there's no need to display it when a G Suite product is not currently in the cart. (See also https://github.com/Automattic/wp-calypso/pull/43403 which fixed a tangential issue.)

This PR does the following:

1. Hides the `alternateEmail` field from the contact form inactive step summary when a G Suite product is not in the cart. (Previously it would also be shown if a domain product was in the cart. This new behavior matches old checkout.)
2. Stops pre-populating the `alternateEmail` field. In order to pre-populate the `alternateEmail` field when G Suite is in the cart, we were setting its initial value to match the `email` field's value, if the latter was set and the former was not. 
3. Sends either `email` or `alternateEmail` to the validation endpoint. Previously, we were only sending `alternateEmail`.
4. Displays validation errors for `email` in addition to those from `alternateEmail` on the alternate email field if the validation fails (but only if `alternateEmail` is not edited, in which case it would instead only display `alternateEmail` errors).
5. Hides address and telephone contact info in the summary if a domain product is not in the cart.

Fixes #44426

#### Testing instructions

Testing a plan without a domain or G Suite:

- Add a plan to your cart.
- Visit checkout.
- In the checkout page, click on the "Edit" button next to Contact Information.
- Fill out the postal code and country and click "Continue".
- Verify that the contact step summary shows the postal code and country.

Testing a domain without G Suite:

- For a site you already own, go to Manage -> Domains and click on "Add a domain to this site".
- Search for and select a domain.
- Proceed to checkout.
- In the checkout page, click on the "Edit" button next to Contact Information.
- Update your email address and click on "Continue".
- Verify that only the new email address is shown in the inactive contact information step.

Testing G Suite with a domain:

- Add a G Suite product to your cart with a domain (you can do this by just removing and re-adding the domain which will bring up the G Suite product screen before checkout).
- Verify that the contact information step displays the "Email" field but not the "Alternate email" field.
- Try setting the email field to an address that matches the domain you're registering (eg: for the domain `example.com`, set the address to `me@example.com`).
- Click "Continue" and verify that you receive an error that the email address domain cannot match the domain.
- Change the email address to not match the domain.
- Click "Continue" and verify that you move on to the next step.

Testing G Suite alternate email: 

- Clear your cart.
- For a domain you already own, add a G Suite product to your cart (so that there is no domain in your cart) and visit checkout.
- Verify that the contact information step display no email field (unless your saved email field is invalid).
- Click "Continue" and verify that you move on to the next step.
- Somehow force the saved email field to be invalid. You can do this by applying D47627-code and then customizing the email address to match the domain in your cart.
- Visit checkout again.
- Verify that the contact information step displays the empty "Alternate email" field.
- Click "Continue" and verify that you receive an error that the email address domain cannot match the domain.
- Enter an email address that still matches the domain.
- Click "Continue" and verify that you receive an error that the email address domain cannot match the domain.
- Change the email address to not match the domain.
- Click "Continue" and verify that you move on to the next step.

### CODE REVIEW

**Comment by stephanethomas** [comment]
I had a first look to these changes, they look good to me. I'll do proper testing tomorrow.

**Comment by stephanethomas** [comment]
I was able to test it successfully. I've only noticed that in the following case:

> * Somehow force the saved email field to be invalid. This is tricky. Ask me for help if you need to.
> * Visit checkout again.
> * Verify that the contact information step displays the empty "Alternate email" field.
> * Click "Continue" and verify that you receive an error that the email address domain cannot match the domain.

We display an error which references the `Email` field, not the `Alternate Email` one:

screenshot

I'm also curious, why don't we show an `This field is required.` error instead since that field is actually empty?

**Comment by sirbrillig** [comment]
> We display an error which references the Email field, not the Alternate Email one:

Yes, that was intentional, but maybe it's not ideal. I'd be happy to use a different approach if you can come up with one.

What's happening is: when you submit the validation, we submit `alternateEmail` if it is not empty; otherwise we submit `email`. If `email` is invalid, then the server replies with an error that you saw about `"Email"` being invalid. Unfortunately, there is no email field, so the user would probably be very confused if they saw the "Please fix highlighted fields" error and there was no highlighted field. To try to remedy this, I've made it so that if there is no `alternateEmail` error in the response, but there is an `email` error, we display the `email` error on the "Alternate email" field, since that's where the user needs to take action. The error message itself comes directly from the server, so it unfortunately reads "Email" and not "Alternate email".

> I'm also curious, why don't we show an This field is required. error instead since that field is actually empty?

This is because we are just displaying the error given to us by the server. `alternateEmail` is actually _not_ required; only one of `email` or `alternateEmail`, so that error message would be misleading from the standpoint of the API. This would be easier, probably, if G Suite required `alternateEmail` to be set. This is actually how it works in composite checkout without this PR: we just assume that `alternateEmail` must always be filled in, so we always show the field and we make it required. However, to make it easier on the user so they don't have to type their email address again, we pre-fill the field with the `email` value. Unfortunately, this is partly what's causing the bug in #44426 because now G Suite users have both email addresses saved in their cached domain contact details, they will both be displayed by the summary if they differ, and there's no way when purchasing a domain to change your `alternateEmail`.

**Comment by stephanethomas** [comment]
Thank you for taking the time to clarify how the logic works Payton 🙇‍.

> The “Email” field cannot use any of the domain names you plan to register.

I wanted to also note that this error message is a bit confusing, given that in our case the domain has been registered before.

> Yes, that was intentional, but maybe it's not ideal. I'd be happy to use a different approach if you can come up with one.

We could update the error messages returned by the server to no longer mention field names, e.g.:

> This field cannot use any of the domain names you plan to register.

But this is not going to help with the issue I've just mentioned. However, one potential solution to address that could be to validate the `email` property sent to the server with `Alternate_Email_Address_Validator` instead of `Email_Address_Validator`.

I'm about to leave for summer holidays so you may want to ping @olaseni if you need a review. I hope this approach will work but if not feel free to merge your changes until we find the time to figure out a more proper solution. Finally, I'm going to ping @eltongo to mention the sort of validation issues we could improve while working on Titan.

**Comment by sirbrillig** [comment]
Rebased to fix conflicts. I think your suggestions are good ones! They'd make the user experience more clear, but they are mostly back-end solutions, so in the interest of fixing the issue of users seeing multiple email addresses appear that they cannot edit, I'm going to see if we can merge this soon.

**Comment by sirbrillig** [comment]
Failing e2e tests seem all unrelated.

File: client/components/domains/contact-details-form-fields/managed-contact-details-form-fields.jsx [hunk 1]
```diff
@@ -321,12 +323,24 @@ export class ManagedContactDetailsFormFields extends Component {
...
 	renderAlternateEmailFieldForGSuite() {
+		let customErrorMessage = this.props.contactDetailsErrors?.alternateEmail;
+		// We also show 'email' field errors because this field will only be shown
+		// if email is invalid (and email will not be shown) so we should show
+		// those errors somewhere. However, only show them if the `alternateEmail`
+		// has not been entered.
+		if (
+			! customErrorMessage &&
+			this.props.contactDetailsErrors?.email &&
+			! this.props.contactDetails?.alternateEmail?.length > 0
```
Comment (tyxla) [inline client/components/domains/contact-details-form-fields/managed-contact-details-form-fields.jsx:334]: @sirbrillig did you mean:

```
this.props.contactDetails?.alternateEmail?.length === 0
```

or:

```
! this.props.contactDetails?.alternateEmail?.length
```

In the current form, this will luckily work, but only because the integer there gets implicitly converted to a boolean, and that seems to correspond to the expected result here 😉

Comment (sirbrillig) [reply client/components/domains/contact-details-form-fields/managed-contact-details-form-fields.jsx:334]: It was a while ago, but I think this was intentional. Here's the possible states:

- `! 'foo@example.com'.length > 0` (evaluates to false, meaning alternate email is set, so we should not show any email field errors)
- `! ''.length > 0` (evaluates to true, meaning alternate email is not set, so we should show any email field errors)
- `! undefined > 0` (evaluates to true, meaning alternate email is not set, so we should show any email field errors)

`this.props.contactDetails?.alternateEmail?.length === 0` would not cover the third case because `undefined === 0` is false.

`! this.props.contactDetails?.alternateEmail?.length` does look like it would cover all the cases. I thought there was some reason I didn't use it here, but at the moment I can't think of why.

Worth noting that a lot of this (certainly awkward) logic should be going away with https://github.com/Automattic/wp-calypso/issues/45336
