### PR TITLE
Store Orders: Check if shipping value is NaN, display empty input

### LINKED ISSUE #21976: Store: New/Edit Order: "Sticky" Zero in Shipping Input
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/store/order/{DOMAIN}
2. Click in the shipping field
3. Attempt to backspace over the zero (or whatever amount was in the existing order) in order to enter an update shipping cost (e.g. 5)
4. In the case of a new order, the zero cannot be deleted until another digit (e.g. a 5) is entered first
5. In the case of editing an existing order, deleting all the digits in the original shipping cost causes a zero to appear in the field which cannot be deleted until another digit (e.g. a 5) is present.

sticky-zero

Also happens when editing an order.

### PR DESCRIPTION
**Pull request by ryelle**
Fixes #21976  – In the create/edit mode, the shipping value is forced to zero even when the input value is `''`. This was due to how the input displayed `NaN`, the result from `getOrderShippingTotal`. This fix detects that `NaN`, which is caused by erasing the shipping input, and displays the empty string - as the user would expect when they hit delete.

To test:

- Start a new order: `/store/order/:site`
- Click into the shipping input
- Delete the value
- It should delete 👍 

You can enter in other values, and delete those too.

### CODE REVIEW

File: client/extensions/woocommerce/app/order/order-details/table.js [hunk 1]
```diff
@@ -7,7 +7,7 @@ import PropTypes from 'prop-types';
 import classnames from 'classnames';
 import Gridicon from 'gridicons';
 import { localize } from 'i18n-calypso';
-import { every, find, findIndex, get, noop } from 'lodash';
+import { every, find, findIndex, get, noop, isNaN } from 'lodash';
```
Comment (allendav) [inline client/extensions/woocommerce/app/order/order-details/table.js]: Minor. I tend to alphabetize imports
