### PR TITLE
Recent feed - add specific routes for selected sub items.

### LINKED ISSUE #99166: Reader: Own blog disappears from sidebar
### Context and steps to reproduce

I'm not sure if this bug is present for others. Here are the steps I take:
 
1. Visit the feed for your own blog
2. Go to WordPress.com
3. Click on the Reader
4. See that your blog disappears from the sidebar

https://github.com/user-attachments/assets/8e7b1523-d711-4b0e-8b26-7fac94452116

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Moderate

### What other impact(s) does this issue have?

_No response_

### If a workaround is available, please outline it here.

_No response_

### Platform

_No response_

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
Related to # https://github.com/Automattic/wp-calypso/issues/100074 and may also resolve https://github.com/Automattic/wp-calypso/issues/99166 

## Proposed Changes

Adds routes for specific site selections in the readers recent stream. This enables the reader and browser "back" buttons to not overlook these selections. This also means when navigating back to the reader at /reader the user will always see the "all" selection by default, and not immediately funneled into a sub-selection based on their previous activity in a different reader session.

* Selecting an individual item in recent will now use the route `reader/recent/:feed_id`, the all selection will continue to use `/reader` as it has for ages.
* Sets the selected feed in state from the following/main component based on the route param feed id.
* No longer sets the selected feed in state from the sidebar, this instead now directs to the new routes.
* Removes persistence from the selected recent feed state, as this is no longer necessary or useful given the new route handling.

Note - at first I wondered if it would make sense to pull out the redux state for the selected recent feed here and handle everything via the routes. However, it seems that the state is still useful for us to connect this information easily in different areas/components that need it. It seems like it would be messier to update all those places to evaluate the route and path than just continue reading this store. The handoff between route and state at the highest level component feels like a good balance.

BEFORE

AFTER

## Why are these changes being made?

* Back buttons were made present in these streams, but this highlighted that these stream selections were overlooked by back navigation. Adding routes creates a more consistent experience.
* The change that visiting /reader will always show the "all" selection and no longer enforce a sub-selection based on previous reader sessions is also seen as a UX improvement and also gets rid of another potential bug as noted here https://github.com/Automattic/wp-calypso/issues/99166

## Testing Instructions

* Visit the /reader
* select a stream outside of Recent, such as "Discover".
* Under the "Recent" submenu, now select into a few different sub options (individual recent feeds).
* Press the "back" button. Verify the individual recent streams are now respected in the back navigation and no longer jump all the way to back to "Discover" (or whichever other feed you were on before them).
* Navigate away from the reader ("W" Icon in top left) and navigate back to the reader via the top toolbar. Verify you are seeing the "all" recent feed and not a sub selection.
* Test around these feed selections and try to find any other regressions.

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/state/reader-ui/sidebar/reducer.js [hunk 1]
```diff
@@ -45,14 +45,14 @@ export const openOrganizations = withPersistence( ( state = [], action ) => {
 	return state;
 } );
 
-export const selectedRecentSite = withPersistence( ( state = null, action ) => {
+export const selectedRecentSite = ( state = null, action ) => {
```
Comment (Addison-Stavlo) [inline client/state/reader-ui/sidebar/reducer.js:48]: It no longer seems necessary to have persistence for this or bloat the persisted data, since the individual route will communicate and set the initial selection now.

**Review by DustyReagan — APPROVED** [review]
This works well for me, and I didn't find any regressions.
