### PR TITLE
Redirect users to /domains/add when cart is cleared in EmailUpsell flow.

### LINKED ISSUE #84228: Going back from checkout empty cart assumes you still have items in your cart.
### Quick summary

Going back from checkout and emptying cart for purchasing domain takes you back to a page that expects you have domain still in the cart. 

### Steps to reproduce

When I tried to purchase a domain, before checkout I got an upsell page asking to setup email or google. I skipped it. When I got to the checkout, I wanted to go back to double check the upsell offers. 

I clicked the back button on the top right of the site, (not browser back button).  I get message "You are about to leave checkout with items in your cart". I clicked "Empty cart". 

I am then returned to the upsell page that was trying to get me to addon email or google to the domain. However, now if I actually try to add those things I get errors. 
Trying to add email "We have removed Professional Email for 'mycoolestsiteintheworld5.blog' from your cart because the domain is not connected to your site"
Trying to add google "Sorry, Google Workspace cannot be added to this domain. The domain name servers are not pointing to WordPress.com."
Skip goes back to checkout "You have no items in your cart".

### What you expected to happen

When I go back from the cart the page I go back to should know that I emptied the cart and not offer me options that just result in errors.

### What actually happened

I couldn't purchase the domain or the addons offered without going back an extra step and trying to add the domain again from the start.

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by StevenDufresne**
Fixes: #84228

## Proposed Changes
When a user clears their cart at checkout after coming from the domainEmail upsell flow, they encounter an error when attempting to add an email after being redirected there.

This PR updates `leaveCheckout` to return users to `/domain/add` if they have cleared their cart and are coming from the Email Upsell flow.

### Changes:
 - Pass a new optional property `userHasClearedCart` to `leaveCheckout` to determine whether the user has chosen to clear their cart.
 - Add `getCloseURL` function to encapsulate `closeUrl` logic.
    -  Add regex to determine if previousPath was the email upsell path and return to `/domain/add` if users have cleared their cart.

## Why are these changes being made?

Ideally, we wouldn't need to add flow-specific logic to `leaveCheckout`. It would be best to redirect users who arrive on `/domains/add/{domain}/email/{site}` before rendering the page. 

Currently when users clear their cart, we call [replaceProductsInCart](https://github.com/Automattic/wp-calypso/blob/0e13e0f7405b0ee040247f6e7f488e1a2a8c44e0/client/layout/masterbar/checkout.tsx#L80) and immediately redirect the user. Often, users arrive at their next route before the cart has fully cleared. We therefore can't simply check the cart early and redirect. They EmailUpsell view will flash.

We therefore have three choices:
- Run `replaceProductsInCart` synchronously, then check cart on upsell page load.
- Suspend rendering the email upsell view until cart actions have all resolved.
- Direct users in leaveCheckout.

### Run `replaceProductsInCart` synchronously

Unfortunately, this doesn't work because users will see the empty cart state flash before they are redirected.

### Suspend rendering the email upsell

This approach is more predictable and how other pages in upsells flows work. However, this will introduce more delays in rendering the page. As it is, the email upsell page loads fast and is snappy. This is a much better experience for upsells. We don't want users to wait for an upsell they may not want.

### Direct users in leaveCheckout [Implemented in this PR]

I went with this approach. If feels like the quickest win that doesn't add delays in the purchase flow or introduce any large refactors. 

It isn't without some compromise though. 

I decided to use a regex to determine if the users came from the domain flow. I considered using [domainAddEmailUpsell](https://github.com/Automattic/wp-calypso/blob/0e13e0f7405b0ee040247f6e7f488e1a2a8c44e0/client/my-sites/domains/paths.js#L91) but since we don't have access to `context.params` to determine the domain the were adding, I didn't see an easy way to compare the URLs. There may be a way to do it with the flow name but that also requires access to `context` or maybe there's a way to get the context?

There's also one use case that isn't handled. If a user clears their cart but makes their way back to the upsell page, they will get an error if they add an email. I don't think that use case would be common and I'm not convinced we need to handle it.

## Testing Instructions

Using an account with no domain yet.

**Test Emptying Cart**
1. From `Upgrade->Domains` click "Just search for a domain"
2. Add Domain
3. Skip email upsell
4. At checkout, click "X" and empty cart
5. Confirm you are redirected to `/domains/add`

**Test Leave Items in Cart**
1. From `Upgrade->Domains` click "Just search for a domain"
2. Add Domain
3. Skip email upsell
4. At checkout, click "X" and leave items
5. Confirm you are on the email upsell page.

**Test Add Plan flow, empty cart**
1. From `Upgrade->Plans` click "Upgrade" on a plan
2. At checkout, click "X" and empty cart
3. Expect to be back on the plan page

Re-run the test but choose "Leave Items" in cart, expect the same result.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by sirbrillig — COMMENTED** [review]
This looks like an elegant solution! Thanks for all the research on the different alternatives. I was wondering, since this seems to focus on leaving checkout using the masterbar close button, does this same bug exist if you remove the product from your cart manually in checkout (which also [redirects away](https://github.com/Automattic/wp-calypso/blob/dad8aa0f04b8ab81c475a8c7f0d820c2556b1052/client/my-sites/checkout/src/hooks/use-remove-from-cart-and-redirect.ts#L10) if it's the last cart item)?

**Comment by StevenDufresne** [comment]
Aha! Thanks for catching that. I've fixed that in https://github.com/Automattic/wp-calypso/pull/98519/commits/7ee93659041b0cf64eff108dbaf2ea09972d1e0b.

File: client/layout/masterbar/checkout.tsx [hunk 1]
```diff
@@ -54,12 +54,13 @@ const CheckoutMasterbar = ( {
 	const { responseCart, replaceProductsInCart } = useShoppingCart( cartKey );
 	const [ isModalVisible, setIsModalVisible ] = useState( false );
 
-	const closeAndLeave = () =>
+	const closeAndLeave = ( userHasClearedCart: boolean = false ) =>
```
Comment (sirbrillig) [inline client/layout/masterbar/checkout.tsx]: This is relatively minor but I think a better API here would be to use object destructuring so this can be a "named" variable. That way instead of `closeAndLeave(true)` you'd see `closeAndLeave({userHasClearedCart:true})` which is much more readable, especially since the property's effect is not obviously related to closing checkout. In addition, it leaves open the option to pass more named variables in the future if we need to.

**Review by sirbrillig — APPROVED** [review]
Looks good! I made one request for the API of `closeAndLeave` but it's not a blocker.

File: client/layout/masterbar/checkout.tsx (hunk 1 above)
Comment (StevenDufresne) [reply client/layout/masterbar/checkout.tsx]: That makes sense. I'll update.
