### PR TITLE
Fix woo express login url

### LINKED ISSUE #88604: [WooExpress flow] User is redirected to WP login page when user is not login
### Quick summary

User is redirected to WP login page when user is not login, but it should redirect user to Woo's login page.

### Steps to reproduce

1. Go to https://woo.com/
2. Log in 
3. Go to wordpress.com and log out
4. Go to https://woo.com/start/#/installation
5. Click on "Try Woo Express for free"

### What you expected to happen

Should be redirected to Woo's login page

### What actually happened

I was redirected to WP login page

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by chihsuan**
Related to https://github.com/Automattic/woocommerce.com/pull/19925
Fixes  https://github.com/Automattic/wp-calypso/issues/88604

## Proposed Changes

* When user is not logged in, redirect user to Woo login page, instead of WP login page.

## Testing Instructions

1. Check out https://github.com/Automattic/woocommerce.com/pull/19925 on your local wccom environment.
2. Go to https://woocommerce.test/
2. Log in woo.com
3. Go to wordpress.com and log out
4. Go to https://woo.com/start/#/installation
5. Click on "Try Woo Express for free"
6. Observe that you are redirected to Woo login page
7. Log in and confirm you're redirect to woo express loading screen.
8. Please test around this issue.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/landing/stepper/declarative-flow/trial-wooexpress-flow.ts [hunk 1]
```diff
@@ -76,40 +73,18 @@ const wooexpress: Flow = {
...
-		const getStartUrl = () => {
-			let hasFlowParams = false;
-			const flowParams = new URLSearchParams();
-			const queryParams = new URLSearchParams();
-
-			if ( vendorId ) {
-				queryParams.set( 'vid', vendorId );
-			}
-
-			if ( aff ) {
```
Comment (rjchow) [inline client/landing/stepper/declarative-flow/trial-wooexpress-flow.ts:88]: the `aff` and `vid` params aren't handled in `login()` so I'm guessing they're deprecated?

**Review by rjchow — APPROVED** [review]
tests well, left a clarification

File: client/landing/stepper/declarative-flow/trial-wooexpress-flow.ts (hunk 1 above)
Comment (chihsuan) [reply client/landing/stepper/declarative-flow/trial-wooexpress-flow.ts:88]: Nope 😅  I thought they were appended to redirect_to. Just fixed it in b8395594cd8e24c43ea38cb62e00b2601f77d25d

**Review by ilyasfoo — APPROVED** [review]
> Go to https://woo.com/start/#/installation

Just to clear this up, do you mean woo.com or woocommerce.test? If the latter, it was redirecting me to the [old login screen](https://github.com/Automattic/wp-calypso/assets/3747241/4573490a-d876-4180-bdbb-3091ec401132) (non-passwordless). 

It also has this weird bug where the login link is broken:

https://github.com/Automattic/wp-calypso/assets/3747241/6fbab7be-8c13-4433-a492-7b0980af31cb

Otherwise, this is testing well per instructions, pre-approving! 🚢

**Comment by chihsuan** [comment]
> > Go to https://woo.com/start/#/installation
> 
> Just to clear this up, do you mean woo.com or woocommerce.test? If the latter, it was redirecting me to the [old login screen](https://github.com/Automattic/wp-calypso/assets/3747241/4573490a-d876-4180-bdbb-3091ec401132) (non-passwordless).
> 
> It also has this weird bug where the login link is broken:


It's the latter. Nice catch! Fixed in 82ca01154f6bab27d45d2108b2e1e975260c78f8.
