### PR TITLE
Editor: Update publish messaging to be consistent with updating.

### LINKED ISSUE #22778: Editor: publish confirmation should show post permalink at time of publish (not site home URL)
#### Steps to reproduce
1. Starting at URL: /posts
2. Create a new post.
3. Publish it — and note the URL to your site in the success message.
4. Now update the post — and note the URL is now the post permalink.

#### What I expected
To be able to click the success message link and go directly to the post permalink the first time I publish the post.

#### What happened instead
When publishing a post for the first time, the post publish link sends me to my home URL (website root).

Then, every time after that, when I update the post, the link sends me to to the post permalink.

Can we make the first save also point to the permalink?

#### Screenshot / Video

First time — the link point to `https://lancetest35.wordpress.com/`:
screen shot 2018-02-23 at 16 05 30

Aften an edit, the link points to `https://lancetest35.wordpress.com/2018/02/23/new-post-number-355/`:
screen shot 2018-02-23 at 16 05 59

#### Context / Source

Found via #reallife #dogfooding aka "wine tasting" by @johnmaeda. Thanks JM for #livesharing and #flowsharing your experiences.

### PR DESCRIPTION
**Pull request by michaeldcain**
Fixes #22778.

This makes sure that the link in the publish notification links directly to the published item. It also consolidates translation strings, renames the notification Tracks events, and cleans up the tests.

screen shot 2018-03-06 at 3 04 52 pm

**To test:**
- For a preview-able site, when publishing a post, custom post type, or page, a preview should be shown and the success notice should match the following:
 - Post: `Post published on [post link]{Site name}[/post link]!`
 - Custom Post Type: `{Post type} published on [post link]{Site name}[/post link]!`
 - Page: `Page published on [page link]{Site name}[/page link]! [new page link]Add another page[/new page link].`

### CODE REVIEW

File: client/post-editor/editor-notice/index.jsx [hunk 1]
```diff
@@ -122,62 +122,44 @@ export class EditorNotice extends Component {
...
+								postLink: <a href={ postUrl } onClick={ this.handlePillExternalClick } />,
+							},
+							comment:
+								'Editor: Message displayed when a post of a custom type is published, with a link to the published post.',
+						}
+					);
 				}
 
-				return translate( 'Post published on {{siteLink/}}!', {
+				return translate( 'Post published! {{postLink}}Visit post{{/postLink}}.', {
```
Comment (a8ci18n) [inline client/post-editor/editor-notice/index.jsx]: Hi! I've found a possible matching string that has already been translated **19** times:
`translate( 'Post updated! {{postLink}}Visit post{{/postLink}}.' )` *ES Score: 13*

Help me improve these suggestions: react with :thumbsdown: if the suggestion doesn't make any sense, or with :thumbsup: if it's a particularly good one (even if not implemented).

File: client/post-editor/editor-notice/index.jsx [hunk 2]
```diff
@@ -122,62 +122,44 @@ export class EditorNotice extends Component {
...
-								>
-									{ site.title }
-								</a>
-							),
-						},
-						comment:
-							'Editor: Message displayed when a post of a custom type is published, with a link to the site it was published on.',
-					} );
+					return translate(
+						'%(typeLabel)s published! {{postLink}}Visit %(typeLabel)s{{/postLink}}.',
```
Comment (a8ci18n) [inline client/post-editor/editor-notice/index.jsx]: Hi! I've found a possible matching string that has already been translated **18** times:
`translate( '%(typeLabel)s updated! {{postLink}}Visit %(typeLabel)s{{/postLink}}.' )` *ES Score: 22*

Help me improve these suggestions: react with :thumbsdown: if the suggestion doesn't make any sense, or with :thumbsup: if it's a particularly good one (even if not implemented).

**Comment by nylen** [comment]
Elsewhere in that file:

```
handlePillExternalClick = () => {
 	this.props.recordTracksEvent( 'calypso_editor_pill_site_external_click' );
 };
```

Should we change this to a new event, like `calypso_editor_pill_view_post_click`?  (I guess this was named this way because our noticed used to be `pill`s but they're not anymore).

File: client/post-editor/editor-notice/index.jsx [hunk 3]
```diff
@@ -122,62 +122,45 @@ export class EditorNotice extends Component {
...
 						},
-						comment:
-							'Editor: Message displayed when a page is published, with a link to the site it was published on.',
+						comment: 'Editor: Message displayed when a page is published, with a link to the page.',
 					} );
 				}
 
 				if ( 'post' !== type && typeLabel ) {
-					return translate( '%(typeLabel)s published on {{siteLink/}}!', {
+					return translate( '%(typeLabel)s published on {{postLink/}}!', {
```
Comment (a8ci18n) [inline client/post-editor/editor-notice/index.jsx]: :ok: This change is safe, we'll keep the existing 21 translations.

File: client/post-editor/editor-notice/index.jsx [hunk 4]
```diff
@@ -122,62 +122,45 @@ export class EditorNotice extends Component {
 				}
 
 				if ( 'page' === type ) {
-					return translate( 'Page published on {{siteLink/}}! {{a}}Add another page{{/a}}', {
+					return translate( 'Page published on {{pageLink/}}! {{a}}Add another page{{/a}}', {
```
Comment (a8ci18n) [inline client/post-editor/editor-notice/index.jsx]: :ok: This change is safe, we'll keep the existing 19 translations.

File: client/post-editor/editor-notice/index.jsx [hunk 5]
```diff
@@ -84,135 +85,57 @@ export class EditorNotice extends Component {
...
-								</a>
-							),
-						},
-						comment:
-							'Editor: Message displayed when a post of a custom type is published, with a link to the site it was published on.',
-					} );
-				}
-
-				return translate( 'Post published on {{siteLink/}}!', {
+				return translate( '%(typeLabel)s published on {{postLink/}}!', {
```
Comment (a8ci18n) [inline client/post-editor/editor-notice/index.jsx]: Hi! I've found a possible matching string that has already been translated **21** times:
`translate( '%(typeLabel)s published on {{siteLink/}}!' )` *ES Score: 12*

Help me improve these suggestions: react with :thumbsdown: if the suggestion doesn't make any sense, or with :thumbsup: if it's a particularly good one (even if not implemented).

**Comment by mattsherman** [comment]
> Should we change this to a new event, like calypso_editor_pill_view_post_click? (I guess this was named this way because our noticed used to be pills but they're not anymore).

Seems like a good idea. Just need to make sure current event name isn't used in any funnels.

File: client/post-editor/editor-notice/index.jsx [hunk 6]
```diff
@@ -84,135 +85,57 @@ export class EditorNotice extends Component {
...
-				if ( 'page' === type ) {
-					return translate( 'Publishing of page failed.' );
-				}
-
-				if ( 'post' !== type && typeLabel ) {
-					return translate( 'Publishing of %(typeLabel)s failed.', { args: { typeLabel } } );
-				}
-
-				return translate( 'Publishing of post failed.' );
+				return translate( 'Publishing of %(typeLabel)s failed.', { args: { typeLabel } } );
```
[the remark this answers is not in the document]
Comment (mattsherman) [reply client/post-editor/editor-notice/index.jsx]: It would be nice to have consistency in the capitalization of type labels in Calypso.

[the remark this answers is not in the document]
Comment (michaeldcain) [reply client/post-editor/editor-notice/index.jsx]: I agree. I'm going to force capitalization in this case.

**Comment by michaeldcain** [comment]
>Seems like a good idea. Just need to make sure current event name isn't used in any funnels.

Made sure that both of the events weren't being used in funnels. Renamed them to be a little more clear.

File: client/post-editor/editor-notice/index.jsx [hunk 7]
```diff
@@ -84,135 +85,59 @@ export class EditorNotice extends Component {
...
+							a: <a href={ `/page/${ site.slug }` } onClick={ this.handleAddPagePromptClick } />,
 						},
-						comment:
-							'Editor: Message displayed when a post of a custom type is published, with a link to the site it was published on.',
+						comment: 'Editor: Message displayed when a page is published, with a link to the page.',
 					} );
 				}
 
-				return translate( 'Post published on {{siteLink/}}!', {
+				return translate( '%(typeLabel)s published on {{postLink/}}!', {
```
Comment (a8ci18n) [inline client/post-editor/editor-notice/index.jsx]: Hi! I've found a possible matching string that has already been translated **21** times:
`translate( '%(typeLabel)s published on {{siteLink/}}!' )` *ES Score: 12*

Help me improve these suggestions: react with :thumbsdown: if the suggestion doesn't make any sense, or with :thumbsup: if it's a particularly good one (even if not implemented).

File: client/post-editor/editor-notice/index.jsx [hunk 8]
```diff
@@ -84,135 +85,59 @@ export class EditorNotice extends Component {
...
-						},
-						comment:
-							'Editor: Message displayed when a page is published, with a link to the site it was published on.',
-					} );
-				}
-
-				if ( 'post' !== type && typeLabel ) {
-					return translate( '%(typeLabel)s published on {{siteLink/}}!', {
-						args: { typeLabel },
+					return translate( 'Page published on {{pageLink/}}! {{a}}Add another page{{/a}}', {
```
Comment (a8ci18n) [inline client/post-editor/editor-notice/index.jsx]: Hi! I've found a possible matching string that has already been translated **19** times:
`translate( 'Page published on {{siteLink/}}! {{a}}Add another page{{/a}}' )` *ES Score: 10*

Help me improve these suggestions: react with :thumbsdown: if the suggestion doesn't make any sense, or with :thumbsup: if it's a particularly good one (even if not implemented).

File: client/post-editor/editor-notice/index.jsx [hunk 9]
```diff
@@ -84,135 +85,59 @@ export class EditorNotice extends Component {
...
-					} );
-				}
-
-				if ( 'post' !== type && typeLabel ) {
-					return translate( '%(typeLabel)s scheduled for %(formattedPostDate)s!', {
-						args: { typeLabel, formattedPostDate },
-						comment:
-							'Editor: Message displayed when a post of a custom type is scheduled, with the scheduled date and time.',
-					} );
+					return translate( '%(typeLabel)s scheduled!', { args: { typeLabel } } );
```
Comment (mattsherman) [inline client/post-editor/editor-notice/index.jsx]: When does this scenario exist? When is `site` false? (Same comment holds for similar cases.)

Comment (michaeldcain) [reply client/post-editor/editor-notice/index.jsx]: That's a great question - I'm not aware of a scenario, but wonder if it could be some sort of edge-case fallback for Jetpack or maybe the desktop app.

Comment (mattsherman) [reply client/post-editor/editor-notice/index.jsx]: Hmm. If we are going to leave it in, would be nice to keep the timestamp in the notice. I'd say to add that back in for now and we can look at totally removing this case in the future once we do some more testing to see when/if this scenario ever actually occurs.

Comment (michaeldcain) [reply client/post-editor/editor-notice/index.jsx]: Good point… with the switch to `PostLink`, a lot of these messages don't utilize the site prop. I've removed the unnecessary ones.
