### PR TITLE
Fixed magic link flow when there was a transition from email user to wpcom user

### LINKED ISSUE #84048: Seamless Migration: replace login message with W logo
Context: pdDOJh-2qY-p2#comment-1976

It doesn't make sense to show that we're logging you into WP.com, so let's just show the W logo.

### PR DESCRIPTION
**Pull request by JuanLucha**
Fixes https://github.com/Automattic/wp-calypso/issues/84048

### The Problem

When an email user does certain operations, like confirming a blog subscription, we create an account for them using a magic link. That operation is synchronous and lasts several seconds (something we want to improve in other PR), but it's performed only once per user. The problem was that, during those seconds, the screen showed 3 different things: a white screen, a welcome message that didn't make much sense to the user then, and a WordPress logo in the middle of the screen.

### The Solution 

Instead of seeing those 3 phases, the user will see only one during the whole process: the WordPress logo that we show when loading Calypso.

## Testing Instructions

1. Apply this PR and start the application.
2. In an incognito window, go to a blog you want to subscribe to and enter an email not attached to any WPCom user.
3. Check your mail for the confirmation email. Copy the link in the `Confirm now` button:
Screenshot 2023-11-09 at 21 46 22
5. From that link, extract the `redirect_to` parameter and change `https://wordpress.com` for `calypso.localhost:3000`.
6. Paste that modified link into the incognito window. You will see the WordPress logo in the middle of the screen for several seconds and then be redirected to the final site.

A good regression test would be testing that login with magic link still works:
1 . With Calypso running in localhost, go to wordpress.com and click Login:
Screenshot 2023-11-09 at 21 50 39
2 . Click on "Email me a login link":
.
Screenshot 2023-11-09 at 21 51 44

4. Enter the email for one of your WPCom accounts and request the link.

5. Check your mail for the confirmation email. Copy the link in the `Login to WordPress.com` button:

Screenshot 2023-11-09 at 21 53 49

6. From that link, extract the `redirect_to` parameter and change `https://wordpress.com` for `calypso.localhost:3000`.

7. Paste that modified link into the incognito window. You should be logged into Calypso.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: client/login/magic-login/handle-emailed-link-form.jsx [hunk 1]
```diff
@@ -254,6 +255,11 @@ class HandleEmailedLinkForm extends Component {
 			);
 		}
 
+		// transition is a GET parameter for when the user is transitioning from email user to WPCom user
+		if ( isFetching || transition ) {
```
Comment (TimBroddin) [inline client/login/magic-login/handle-emailed-link-form.jsx:259]: Will this not show the logo too when it's fetching and transition isn't set?

**Comment by simison** [comment]
> That operation is synchronous and lasts several seconds

BTW have you looked at what takes time there?

I hope removing the few default subscriptions would speed it up little.

**Comment by TimBroddin** [comment]
I tested it and I got a W logo & there were no regressions. I'm still wondering why the `isFetching || transition` check is needed though.

File: client/login/magic-login/handle-emailed-link-form.jsx (hunk 1 above)
Comment (JuanLucha) [reply client/login/magic-login/handle-emailed-link-form.jsx:259]: Yes, and I think that's cool too: no white screen for anyone?

**Review by TimBroddin — APPROVED** [review]

**Comment by JuanLucha** [comment]
> > That operation is synchronous and lasts several seconds
> 
> BTW have you looked at what takes time there?
> 
> I hope removing the few default subscriptions would speed it up little.

Yeah, that's my second step 👍
