### PR TITLE
Editor: fix page.replace call to use proper CPT edit path.

### LINKED ISSUE #6463: Editor: Publishing/saving a CPT causes URL to change to /post/:site/:id
Pick a site with Jetpack testimonials (or another custom post type) enabled:

1. Starting at URL: http://calypso.localhost:3000/edit/jetpack-testimonial/yourgroovysite.wordpress.com
2. Enter a title or some content, and click Publish
3. Observe that the editor URL changes from `/edit/jetpack-testimonial/` to `/post/`

image

In that screenshot I was testing on another branch but also verified the bug on wpcalypso with both a WP.com and Jetpack site.

Also, on subsequent page loads, the editor will load the post title and content from either `/post/:site/:id` or `/edit/jetpack-testimonial/:id`.  I'd expect the first route to redirect to the second route when Calypso detects the correct post type.

### PR DESCRIPTION
**Pull request by timmyc**
Fixes #6463.  Currently when an auto-save, or an update occurs on a custom post type in the editor, a call to `page.replace` is issued with an incorrect edit path.  This causes all sorts of frustration in the history stack, not to mention to developers testing CPTs in the editor.

This branch updates the logic of `lib/posts/utils#getEditURL` to be aware of the proper CPT edit path, and adds some tests.

__To Test__
- Edit an existing CPT in the editor, click update.  Note the URL should not change and you can hard refresh
- Create a new CPT post in the editor, add a title or some content, after the auto save fires note that the URL path is correct for the CPT.  Issue a hard refresh to double check
- Follow the same steps with a post and a page to ensure all is normal there too

Test live: https://calypso.live/?branch=fix/editor/6463

### CODE REVIEW

File: client/lib/posts/utils.js [hunk 1]
```diff
@@ -14,7 +15,13 @@ var postNormalizer = require( 'lib/post-normalizer' ),
...
 
 	getEditURL: function( post, site ) {
-		return `/${post.type}/${site.slug}/${post.ID}`;
+		let basePath = '';
+
+		if ( ! includes( [ 'post', 'page' ], post.type ) ) {
+			basePath = '/edit';
+		}
+
+		return `${basePath}/${post.type}/${site.slug}/${post.ID}`;
```
Comment (blowery) [inline client/lib/posts/utils.js]: might consider `encodeURIComponent` on each part, just in case. Seems like they're all safe (except maybe `post.type`?) but it would future proof against changes. Not really critical.

File: client/post-editor/post-editor.jsx [hunk 2]
```diff
@@ -848,8 +841,9 @@ const PostEditor = React.createClass( {
 		this.props.receivePost( post );
 
 		// make sure the history entry has the post ID in it, but don't dispatch
+		const site = this.props.sites.getSite( post.site_ID );
 		page.replace(
-			basePath + '/' + this.props.sites.getSite( post.site_ID ).slug + '/' + post.ID,
+			utils.getEditURL( post, site ),
```
Comment (aduth) [inline client/post-editor/post-editor.jsx]: Can we use the [`getEditorPath` selector](https://github.com/Automattic/wp-calypso/blob/b7297c732f7fbc8651a16219e1a1db10f2699de9/client/state/ui/editor/selectors.js#L68-L86)? I'd rather not duplicate the logic if we can avoid it.

**Comment by timmyc** [comment]
Using the selector approach in 04d5bcc.  I have left the updates to `posts/utils` since this method is still in use in other places:

```
client/my-sites/draft/index.jsx
152:			editPostURL = utils.getEditURL( post, site );

client/my-sites/posts/post.jsx
331:			return utils.getEditURL( post, site );
382:					editURL={ utils.getEditURL( this.props.post, site ) }

client/post-editor/post-editor.jsx
510:				page.redirect( utils.getEditURL( post, site ) );

client/reader/post-options/index.jsx
147:			editUrl = PostUtils.getEditURL( post, site.toJS() );
```

File: client/post-editor/post-editor.jsx [hunk 3]
```diff
@@ -849,7 +843,7 @@ const PostEditor = React.createClass( {
 
 		// make sure the history entry has the post ID in it, but don't dispatch
 		page.replace(
-			basePath + '/' + this.props.sites.getSite( post.site_ID ).slug + '/' + post.ID,
+			this.props.editPath,
```
Comment (aduth) [inline client/post-editor/post-editor.jsx]: Huh, I'm really surprised this works, since the logic to update the post ID after saving a new post is only a few lines above here. I would have thought that the prop here wouldn't have been updated until the next tick. Despite this, stepping through in the debugger shows that in-fact the prop is updated in realtime after the call to `this.props.setEditorPostId` . Wonder how that it is?

https://cloudup.com/cRKIECbNlKl

Comment (aduth) [inline client/post-editor/post-editor.jsx]: On an unrelated note, you've shortened this sufficiently that it'd probably be fine on a single line.

**Comment by aduth** [comment]
Followed the logic a bit and found that Redux `connect` re-renders synchronously after the dispatch, updating the props before reaching `page.replace`. Admittedly I'm still a bit perplexed at this, but I can confirm that this works as expected for posts and custom post types.

**Comment by timmyc** [comment]
Ha I was just doing the same.  It does appear there are multiple render calls in `post-editor` that occur before the flux callback is executed:

edit_testimonial_ _testingtimmy2_wordpress_com_ _wordpress_com

**Comment by aduth** [comment]
Maybe we shouldn't depend on this behavior? https://github.com/reactjs/react-redux/issues/291#issuecomment-185706321

**Comment by timmyc** [comment]
> Maybe we shouldn't depend on this behavior?

Seems fair.  So take out the `page.replace` logic and detect changes of `props.editPath` in `componentWillReceiveProps` and call `page.replace` there?

**Comment by aduth** [comment]
>So take out the `page.replace` logic and detect changes of `props.editPath` in `componentWillReceiveProps` and call `page.replace` there?

Yeah, this seems more reliable to me.

Wonder if that could also allow us to remove this:

https://github.com/Automattic/wp-calypso/blob/433a2ea/client/post-editor/post-editor.jsx#L507-L510

This redirects to the correct `/page` path if trying to access page type via `/post` prefix after loading the post. This should probably apply to custom post types as well anyways.

Might want to think about which page option is the best in this case though (`page.replace` as we have it here doesn't add a history entry IIRC?).

**Comment by timmyc** [comment]
@aduth I moved the logic in e57e2e3.  I also explored the redirect you noted above.  If it is okay with you I'd like to tackle that in a follow-up PR.  Some interesting issues there with regards to [setting type](https://github.com/Automattic/wp-calypso/blob/master/client/post-editor/controller.js#L118) in the state tree based off the `context` path.

**Comment by aduth** [comment]
>If it is okay with you I'd like to tackle that in a follow-up PR.

Sounds reasonable.

This looks to be working well 👍
