### PR TITLE
TokenField: Fixes a usability/accessibility issue with maxLength

### LINKED ISSUE #3951: People: should be able to use keyboard to navigate to username list even after adding more than 10
#### Steps to reproduce
1. Add 10 usernames to the username list. It's ok if they are not valid:
screen shot 2016-03-10 at 11 01 13 am
2. Try to use your mouse click on the username list to add your cursor to any place in the list, see that you are not able to do it
3. Try to tab into the list using the keyboard, see that you are not able to do it

#### What I expected
I'd like to be able to use my keyboard to remove usernames that are not valid, instead of using the 'X'. This will also help with making this page more accessible.

It's ok if I'm not able to type out more users above 10, but the cursor should work for deleting users using the backspace key and moving between them using arrows. For example each user above 10 could be automatically deleted, similar to when if the same user is typed twice, they are deleted:
same-user-deleted

#### Browser / OS version
Chrome 48.0 on OSX
Safari 9.0.1
Firefox 44.0.2 on OSX

### PR DESCRIPTION
**Pull request by ebinnion**
Fixes #3951

Previously, when we disabled the TokenInput, we used the default "disabled" prop. But, this broke the ability to use keyboard shortcuts to move the input and remove tokens.

This PR suggests disabling the ability to add a token by removing the onChange event from TokenInput when maxLength has been reached. This allows us to still use the keyboard to remove tokens even after hitting maxLength.

To test:
- Checkout `update/token-field-input-disabled`
- Go to `/people/new/$site`
- Add 10 tokens (does not matter if they error or not)
- After the 10th token, you should not be able to add another one, *but* you should be able to use the left/right arrow keys to navigate between tokens and then hit `delete` to remove a token

cc @aduth and @lezama for review

### CODE REVIEW

File: client/components/token-field/index.jsx [hunk 1]
```diff
@@ -172,14 +172,22 @@ var TokenField = React.createClass( {
...
 		const { maxLength, value } = this.props;
+
+		let props = {
+			ref: 'input',
+			key: 'input',
+			disabled: this.props.disabled
+		};
+
+		if ( ! ( maxLength && value.length >= maxLength ) ) {
+			props = Object.assign( {}, props, {
```
Comment (aduth) [inline client/components/token-field/index.jsx]: You could skip an object clone by assigning directly into the object.

```js
Object.assign( props, {
```

File: client/components/token-field/token-input.jsx [hunk 2]
```diff
@@ -49,9 +49,11 @@ var TokenInput = React.createClass( {
 	},
 
 	_onChange: function( event ) {
-		this.props.onChange( {
-			value: event.target.value
-		} );
+		if ( 'function' === typeof this.props.onChange ) {
```
Comment (aduth) [inline client/components/token-field/token-input.jsx]: Is this condition necessary? There's a default prop noop for `onChange`.

File: client/components/token-field/index.jsx [hunk 3]
```diff
@@ -172,14 +172,22 @@ var TokenField = React.createClass( {
...
+				value: this.state.incompleteTokenValue,
```
Comment (aduth) [inline client/components/token-field/index.jsx]: Technically we could still pass this value in, yeah? I ask only because I was trying to grok the intent of this assignment, and eventually came to the conclusion that it's to prevent the `onChange` handler from being specified when `maxLength` is reached. If the code reflected this, I think it'd be easier to understand at a glance.

**Comment by aduth** [comment]
A few suggested revisions, but otherwise looks and works well to me :+1:

File: client/components/token-field/token-input.jsx (hunk 2 above)
Comment (ebinnion) [inline client/components/token-field/token-input.jsx]: I don't think it's necessary. Just being cautious :smile:

File: client/components/token-field/index.jsx (hunk 1 above)
Comment (ebinnion) [inline client/components/token-field/index.jsx]: Ooohhh – Thanks for explaining that. :bowtie:

File: client/components/token-field/index.jsx (hunk 3 above)
Comment (ebinnion) [inline client/components/token-field/index.jsx]: :+1:

**Comment by ebinnion** [comment]
Thanks for the feedback @aduth! I have updated the PR to address your feedback.

**Comment by v18** [comment]
I tried it out and it works beautifully.
