### PR TITLE
Store: Set currency for a new order using the site's settings

### LINKED ISSUE #23559: Store: New Order screen doesn't use store currency
The new order screen doesn't seem to pull in the store currency when creating a new order.

Steps to reproduce:

1. Set your currency (`http://calypso.localhost:3000/store/settings/site`) to something like Pounds
2. Navigate to the new order screen (`http://calypso.localhost:3000/store/order/:site`)
3. Notice the shipping dialog displays `$`
4. Click add a product. The prices here will be displayed correctly.
5. Select a product and add it.
6. The product row will display the price in USD.
7. Save your order. The API response that comes back will contain `"currency":"USD"`.

Example: https://cloudup.com/cpQhPmtzHxl

### PR DESCRIPTION
**Pull request by allendav**
Fixes #23559 

To test:
* Set the currency under Settings > Payments to something other than USD
* Start creating a new order under Orders > New
* Make sure the order currency is correct and that you can save the order, abandon creation, etc.
* Repeat for other currencies including USD

### CODE REVIEW

File: client/extensions/woocommerce/app/order/create.js [hunk 1]
```diff
@@ -34,18 +39,37 @@ import { recordTrack } from 'woocommerce/lib/analytics';
...
+
+		this.possiblyFetchDefaultCurrency( this.props );
 	}
 
 	componentWillReceiveProps( newProps ) {
 		if ( this.props.siteId !== newProps.siteId ) {
 			this.props.editOrder( newProps.siteId, {} );
 		}
+
+		this.possiblyFetchDefaultCurrency( newProps );
```
Comment (ryelle) [inline client/extensions/woocommerce/app/order/create.js]: This shouldn't be necessary if you're also calling it in `componentDidUpdate`, I think this would lead to calling the function twice

File: client/extensions/woocommerce/app/order/create.js [hunk 2]
```diff
@@ -131,18 +155,35 @@ export default connect(
...
 		};
 	},
 	dispatch =>
-		bindActionCreators( { clearOrderEdits, editOrder, saveOrder, sendOrderInvoice }, dispatch )
+		bindActionCreators(
+			{
+				clearOrderEdits,
+				editOrder,
+				fetchSettingsGeneral,
+				getPaymentCurrencySettings,
```
Comment (ryelle) [inline client/extensions/woocommerce/app/order/create.js]: This is a selector, not an action, right?

File: client/extensions/woocommerce/app/order/create.js [hunk 3]
```diff
@@ -34,18 +39,37 @@ import { recordTrack } from 'woocommerce/lib/analytics';
 import { sendOrderInvoice } from 'woocommerce/state/sites/orders/send-invoice/actions';
 
 class Order extends Component {
+	possiblyFetchDefaultCurrency( props ) {
```
Comment (ryelle) [inline client/extensions/woocommerce/app/order/create.js]: This is personal preference, so feel free to ignore -- but I usually leave the component lifecycle methods at the top of the class (so this would be below `componentWillUnmount`)

File: client/extensions/woocommerce/app/order/create.js [hunk 4]
```diff
@@ -34,18 +39,37 @@ import { recordTrack } from 'woocommerce/lib/analytics';
...
+		const { currencyCode, orderEdits, settingsGeneralLoaded, siteId } = props;
+		if ( siteId ) {
+			if ( ! settingsGeneralLoaded ) {
+				this.props.fetchSettingsGeneral( siteId );
+			} else if ( isEmpty( orderEdits.currency ) ) {
+				this.props.editOrder( siteId, { currency: currencyCode } );
+			}
```
Comment (ryelle) [inline client/extensions/woocommerce/app/order/create.js]: I think I've figured out the logic here but maybe add a comment or two with some plain english for what this condition is doing?

File: client/extensions/woocommerce/app/order/create.js [hunk 5]
```diff
@@ -131,18 +155,35 @@ export default connect(
 		const siteId = site ? site.ID : false;
 		const orderId = getCurrentlyEditingOrderId( state );
 		const isSaving = isOrderUpdating( state, orderId );
-		const hasOrderEdits = ! isEmpty( getOrderEdits( state ) );
+		const orderEdits = getOrderEdits( state );
+		const hasOrderEdits = ! isEmpty( omit( orderEdits, [ 'currency' ] ) );
```
Comment (ryelle) [inline client/extensions/woocommerce/app/order/create.js]: Maybe add a comment here too, about why you need to omit currency?

File: client/extensions/woocommerce/app/order/create.js (hunk 3 above)
Comment (timmyc) [reply client/extensions/woocommerce/app/order/create.js]: I like that as well, and it seems a pretty common pattern throughout Calypso.

File: client/extensions/woocommerce/app/order/create.js (hunk 4 above)
Comment (allendav) [reply client/extensions/woocommerce/app/order/create.js]: Good idea! Fixed in https://github.com/Automattic/wp-calypso/pull/23568/commits/8a7c403776596e9294f02baf3bf29b7b5c04d140

File: client/extensions/woocommerce/app/order/create.js (hunk 3 above)
Comment (allendav) [reply client/extensions/woocommerce/app/order/create.js]: Good idea! Fixed in https://github.com/Automattic/wp-calypso/pull/23568/commits/8a7c403776596e9294f02baf3bf29b7b5c04d140

File: client/extensions/woocommerce/app/order/create.js (hunk 2 above)
Comment (allendav) [reply client/extensions/woocommerce/app/order/create.js]: Oops! Fixed in https://github.com/Automattic/wp-calypso/pull/23568/commits/8a7c403776596e9294f02baf3bf29b7b5c04d140

File: client/extensions/woocommerce/app/order/create.js (hunk 1 above)
Comment (allendav) [reply client/extensions/woocommerce/app/order/create.js]: You're right! I shouldn't be making network requests in componentWillReceiveProps anyways. Fixed in https://github.com/Automattic/wp-calypso/pull/23568/commits/8a7c403776596e9294f02baf3bf29b7b5c04d140

File: client/extensions/woocommerce/app/order/create.js (hunk 5 above)
Comment (allendav) [reply client/extensions/woocommerce/app/order/create.js]: Good idea! Fixed in https://github.com/Automattic/wp-calypso/pull/23568/commits/8a7c403776596e9294f02baf3bf29b7b5c04d140

File: client/extensions/woocommerce/app/order/create.js (hunk 4 above)
Comment (allendav) [reply client/extensions/woocommerce/app/order/create.js]: Added comments at top of this function
