### PR TITLE
Site Settings: Retrieve site visibility from settings in Traffic tab

### LINKED ISSUE #13414: Site Settings: Site visibility not respected
Site visibility is not respected at all in SEO settings. Previously, there was a banner displayed there when the site is non-public, but it's not visible now:

#### Steps to reproduce
1. Select a private site.
2. Go to `/settings/traffic/$site`.
3. You should be seeing the notice from the screenshot above the SEO settings, but you're not.

This appears to have slipped through our fingers when we migrated the Traffic tab to not use `sites-list` - #13258, cc @gwwar

### PR DESCRIPTION
**Pull request by tyxla**
This PR fixes #13414, where site visibility isn't being fetched properly in SEO settings. This happened because when migrating Traffic away from `sites-list` in #13258, we didn't update the `settings` to be retrieved from the settings redux tree. This PR fixes that by making sure settings will be queried, and fetching the privacy setting from there.

To test:
* Go to `/settings/traffic/$site` where `$site` is one of your private/hidden sites with Business/Professional plan.
* Verify you're seeing the notice properly:

* Go to `/settings/traffic/$site` where `$site` is one of your public sites with Business/Professional plan.
* Verify you're not seeing the notice.

### CODE REVIEW

File: client/my-sites/site-settings/seo-settings/form.jsx [hunk 1]
```diff
@@ -378,15 +380,13 @@ export const SeoForm = React.createClass( {
...
+			siteSettings,
 			isFetchingSite,
 			isSeoToolsActive,
 			isVerificationToolsActive,
 			translate,
 		} = this.props;
 		const {
-			settings: {
-				blog_public = 1
-			} = {},
```
Comment (gwwar) [inline client/my-sites/site-settings/seo-settings/form.jsx]: Pretty fancy destructuring assignment going on here. This is just an aside, but I think anything deeper than one level is confusing for folks to read. So 👍  for removing this.
