### PR TITLE
Move localizeUrl to new i18n-utils package

### LINKED ISSUE #37665: Gutenboarding: i18n
Gutenboarding should fully support a localized experience. MT: pbAok1-dn-p2

## Tasks

**Wip:**
- [ ] Creating a site with the name "테스트" works after D54000-code but we need to replicate #48031 for the launch flow in ETK as it also auto searches the blog name resulting in an instant error. #48399

**Todo:**

**Backlog:**
- [ ] Add new font pairings for non latin locales #43002

**Other teams:**
- [ ] [_low priority_] Gutenboarding: Load user provided translations #39493
- [ ] [_low priority_] Propagate locale slug through all log in flows: #23126
- [ ] Localize [support URL in launch flow summary step](https://github.com/Automattic/wp-calypso/blob/ec22864/apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/final-step/index.tsx#L165) (`localizeUrl( 'https://wordpress.com/help/contact' )`) (Logged in users will see a translated page, this is for logged out) #47947 - blocked, see: #48033
- [ ] Switch language picker on by setting `gutenboarding/language-picker` config entry to true or removing flag altogether. Relies on https://github.com/Automattic/wp-calypso/pull/46328 (not a blocker because we're releasing to existing users first)

**Done:**
- [x] Try using mshots for fetching vertically oriented screenshots in Gutenboarding (https://github.com/Automattic/wp-calypso/pull/43428)
- [x] Not all copy is updated when user switches languages #48196 #48232
- [x] Provide default blog name for /sites/new when providing non latin site titles. Skip domain step without providing ascii characters currently results in a ["something went wrong"](https://github.com/Automattic/wp-calypso/pull/48031#issuecomment-739734208) error on site creation. D54000-code
- [x] some copy isn't being queued for translation in ETK #47884 
- [x] Error handling for domain suggestions and non-Latin chars pbAok1-dn-p2#comment-3227 #48031
- [x] Non-latin character set handling for domain search: Don't auto search non-latin characters using the site name #48031 
- [x] Non-latin character set handling for domain search: Improve error handling by removing note about potential connection errors. (i.e. split the error conditions apart so the error message doesn't tell the user to refresh the page for a validation error) #47985
- [x] Gutenboarding: Localize support URL for HSTS required tooltip in domain suggestions https://github.com/Automattic/wp-calypso/issues/45610 #46670 #46998 #47564 #47492 #47567 #47570 #47612 #47613
- [x] illustration on domain step doesn't work on RTL languages #47490 #47891
- [x] should progress bars be filled from right-to-left? #47886
- [x] domain picker shows domain components in the wrong order in RTL locale #47885 #47889
- [x] Plan details are showing up untranslated (intermittent), there is a timing issue where we request `/plans/details` without a locale and with a locale around the same time, depending which one comes back first changes the outcomes, page: /new/features #47611 
- [x] Update Editing Toolkit to ensure the correct locale is passed to the `plans/details` API endpoint in the launch flow plans step as mentioned here: https://github.com/Automattic/wp-calypso/pull/46588#issuecomment-719196987 #47227
- [x] Move localizeUrl to a package (probably i18n-calypso) Depends on _Move language data to a package_ #46998
- [x] Localize domain suggestion shown in launch flow summary https://github.com/Automattic/wp-calypso/pull/44840#discussion_r468701391 #47178
- [x] Move language data to a package #46709
- [x] Ensure that the WPCOM Nux modal slides are translated https://github.com/Automattic/wp-calypso/pull/47136
- [x] Ensure code shipped from `./packages` (_without_ text-domain) works when shipped in Editor kit plugin (_with_ text-domain). context: pbAok1-1Ao-p2 Part of https://github.com/Automattic/wp-calypso/pull/46557 ?
- [x] Use translated plan feature lists either from `lib/plans` or API ([code](https://github.com/Automattic/wp-calypso/blob/366a96ac656d9e05e37ec4361eca2a11e8d15968/client/landing/gutenboarding/stores/plans/plans-data.ts)) in progress in #46588, endpoint deployed in D51380-code and D51895-code
- [x] Extract Gutenboarding language picker into @automattic/language-picker #46020 
- [x] Update style preview to generate template/demo endpoint url using current locale instead of path param #46793 
- [x] Get translated strings before rendering the page to avoid the current flicker of EN text at first load. (#46473)
- [x] Add `plans/details` endpoint (D51380-code)
- [x] RTL stylesheets #39592
- [x] Ensure Recoleta font works with all symbols of the language (https://github.com/Automattic/wp-calypso/issues/42522, https://github.com/Automattic/wp-calypso/pull/42814)
- [x] Gutenboarding: Set lang/dir in browser #39491 (Think this one is now redundant See [comment](https://github.com/Automattic/wp-calypso/issues/39491#issuecomment-711904463))
- [x] [?check if done] localize templates API
- [x] Finalize switching site locale in the flow from header by shipping it https://github.com/Automattic/wp-calypso/issues/40011
- [x] Implement switching site locale in the flow from header https://github.com/Automattic/wp-calypso/issues/40011
- [x] Localise domain prices #40733
- [x] Ensure domain categories come translated from the API (https://github.com/Automattic/wp-calypso/pull/41450)
- [x] Ensure we translate plan names consistently https://github.com/Automattic/wp-calypso/pull/41679#discussion_r421184975
- [x] Extract `@wordpress/i18n`-style strings for translation (#39541 / @yuliyan)
- [x] Add translation context to [animated verticals list](https://github.com/Automattic/wp-calypso/blob/9e68e6e3ca64f6a2dd16c42911b2aaada7a181fd/client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/index.tsx#L65-L77)
- [x] get locale for logged-in users: #39410
- [x] localize text strings: #39410
- [x] get locale for new users: https://github.com/Automattic/wp-calypso/issues/38909
- [x] Gutenboarding: Serve/update RTL CSS as needed #39492
- [ ] ~localize vertical API: https://github.com/Automattic/wp-calypso/issues/37630~ **No verticals currently**
- [ ] ~[server-side-detect locale?](https://github.com/Automattic/wp-calypso/blob/a51b7190df0b9711b5c059e91e576ab9f2593f69/client/signup/index.node.js)~ **Suspect duplicate of #46473**

**Test i18n:**

- `en`: (redirect strip locale) https://wordpress.com/new/en
- `ar`: (RTL) https://wordpress.com/new/ar
- `de`: https://wordpress.com/new/de
- `es`: https://wordpress.com/new/es
- `fr`: https://wordpress.com/new/fr
- `he`: (RTL) https://wordpress.com/new/he
- `id`: https://wordpress.com/new/id
- `it`: https://wordpress.com/new/it
- `ja`: (non latin check) https://wordpress.com/new/ja
- `ko`: https://wordpress.com/new/ko
- `nl`: https://wordpress.com/new/nl
- `pt-br`: https://wordpress.com/new/pt-br
- `ru`: (long translations) https://wordpress.com/new/ru
- `sv`: https://wordpress.com/new/sv
- `tr`: https://wordpress.com/new/tr
- `zh-cn`: https://wordpress.com/new/zh-cn
- `zh-tw`: https://wordpress.com/new/zh-tw

**Some additional pointers:**

- Might be good to release work in stages, so e.g. left-to-right languages work first (Spanish etc) and then separately right-to-left languages.
- The site should be created in the locale that the UI is in.
- All the APIs, verticalized contents, UI strings, etc should be consistently translated.
- The flow works in Calypso, but parts of it are shipped to WP Admin, in which case UI translations should still work. Code for these parts shipped to two environments is typically in `/packages/*`
- Nothing gets shipped to "Calypso proper" but it should also work already (See 138-GH-i18n-issues)

### PR DESCRIPTION
**Pull request by lsl**
#### Changes proposed in this Pull Request
* Moves lib/i18n-utils' `localizeUrl` function to a new package in `packages/i18n-utils`

#### Testing instructions

localizeUrl tests were included in the move:

```
yarn test-client client/lib/i18n-utils
yarn workspace @automattic/i18n-utils test
```

Manual testing involves checking `localizeUrl` usage still works as expected for example:

- Set locale to german or french using the account settings page http://calypso.localhost:3000/me/account
- Navigate to http://calypso.localhost:3000/me/privacy
- The link to `https://automattic.com/privacy` should be localized (e.g. `https://automattic.com/fr/privacy`) but should point to the original english url for any other language.

---

- Partially fixes #37665 - introduces / exposes localizeUrl for use in apps/packages.
- Enables a fix for #45610

### CODE REVIEW

File: client/lib/wporg/index.js [hunk 1]
```diff
@@ -37,6 +37,7 @@ function getWporgLocaleCode() {
 
 async function pluginRequest( url, body ) {
 	try {
+		// eslint-disable-next-line no-undef -- Probably: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API
```
Comment (scinos) [inline client/lib/wporg/index.js:40]: It would be better to add `env: { browser: true }` to `./client/.eslintrc.js`. Does that removes the need to add this exclusion?

File: packages/i18n-utils/jest.config.js [hunk 2]
```diff
@@ -0,0 +1,5 @@
+module.exports = {
+	preset: '../../test/packages/jest-preset.js',
+	rootDir: __dirname,
```
Comment (scinos) [inline packages/i18n-utils/jest.config.js:3]: I think you don't need `rootDir` or `cacheDirectory`, they come from the `preset`

File: packages/languages/bin/download.js [hunk 3]
```diff
@@ -1,24 +1,21 @@
...
 /**
  * External dependencies
  */
 const https = require( 'https' );
 const fs = require( 'fs' );
+const path = require( 'path' );
 
 const LANGUAGES_META_URL = 'https://widgets.wp.com/languages/calypso/languages-meta.json';
-const FILE_PATH = 'client/languages/languages-meta.json';
+const FILE_PATH = path.resolve( __dirname, '../src/languages-meta.json' );
```
Comment (scinos) [inline packages/languages/bin/download.js:11]: `path.join()` will give us the same result and is a bit more correct IMO

File: packages/languages/bin/download.js [hunk 4]
```diff
@@ -1,24 +1,21 @@
+/* eslint-disable no-console, no-process-exit, import/no-nodejs-modules */
```
Comment (scinos) [inline packages/languages/bin/download.js:1]: This could be moved up to `./bin/.eslintrc.js`, and I think they will apply to any script inside `./bin`

File: packages/languages/jest.config.js [hunk 5]
```diff
@@ -0,0 +1,5 @@
+module.exports = {
```
Comment (scinos) [inline packages/languages/jest.config.js:1]: I think you don't need `rootDir` or `cacheDirectory`, they come from the `preset`

**Comment by lsl** [comment]
@yuliyan / @scinos 

Parts of this `i18n-utils` package make more sense to be part of `packages/languages`: e.g. `getLanguage( langSlug )` just performs a lookup on the language data with a fallback to parent locale if available, and `isTranslatedIncompletely` just returns a value of the language looked up by `getLanguage`

The remaining parts make more sense to be part of `package/i18n-calypso`. e.g. `canBeTranslated`, `translationExists`, `isMagnificentLocale` are all very a8c specific or depend on i18n-calypso to get the current locale (like `localizeUrl`)

My thinking is maybe to split i18n-utils up between the two existing packages and drop the notion of a new one. Does this sound ok **or is there still a push to drop `i18n-calypso` in favor of `@wordpress/i18n`?** In which case it may be wise to keep i18n-utils in play with some/none of it moved into languages. It would still depend on i18n-calypso but that can be dropped as soon as there is a replacement solution for getLocaleSlug (the only problematic dep.)

File: client/lib/wporg/index.js (hunk 1 above)
Comment (lsl) [reply client/lib/wporg/index.js:40]: [`ac46ab7` (#46709)](https://github.com/Automattic/wp-calypso/pull/46709/commits/ac46ab7f2aa93858ab98ee2043081260e4087ce8)

File: packages/languages/bin/download.js (hunk 3 above)
Comment (lsl) [reply packages/languages/bin/download.js:11]: [`56f0d23` (#46709)](https://github.com/Automattic/wp-calypso/pull/46709/commits/56f0d23af66b41528e943c53996fd010e6ec715f)

File: packages/languages/bin/download.js (hunk 4 above)
Comment (lsl) [reply packages/languages/bin/download.js:1]: [`f50407a` (#46709)](https://github.com/Automattic/wp-calypso/pull/46709/commits/f50407add9123d769fc390f8c6c274e9bf7d473c)

File: packages/languages/jest.config.js (hunk 5 above)
Comment (lsl) [reply packages/languages/jest.config.js:1]: [`4ea1e04` (#46709)](https://github.com/Automattic/wp-calypso/pull/46709/commits/4ea1e0437b0dc126993ef86634c563a553d083a3)

**Comment by lsl** [comment]
@scinos I copy and pasted most of these config files / settings from elsewhere and have only looked into a handful of what each thing does so I very much appreciate the audit! :beers: 

Most of your comments were on code from the other PR #46709 so I've fixed there and rebased here. Thanks!

**Comment by yuliyan** [comment]
> Parts of this `i18n-utils` package make more sense to be part of `packages/languages`: e.g. `getLanguage( langSlug )` just performs a lookup on the language data with a fallback to parent locale if available, and `isTranslatedIncompletely` just returns a value of the language looked up by `getLanguage`

That makes sense and I think moving them into `@automattic/languages` is fine. As for the remaining helpers, I like the idea of having them separate from `i18n-calypso` better. With `@wordpress/i18n` we would be forced to have them in a separate package anyway, so I think it will make the transition more smooth.

File: packages/languages/src/index.ts [hunk 6]
```diff
@@ -25,6 +26,7 @@ type SubLanguage = BaseLanguage & { parentLangSlug: string };
 
 export type Language = BaseLanguage | SubLanguage;
 
-const languages: Language[] = values( data );
-
+export const languagesBySlug = data;
+export const languageSlugs: LanguageSlug[] = keys( data );
```
Comment (p-jackson) [inline packages/languages/src/index.ts:30]: You could always use `Object.keys( data )` instead of lodash. Doesn't make a big difference in the grand scheme of things, but it is one less dependency on a non-standard library.

**Review by p-jackson — COMMENTED** [review]
Looks good so far. I realise it's still a WIP, just left a couple notes. Let me know if there's anything I can help with.

File: packages/languages/src/index.ts (hunk 6 above)
Comment (lsl) [reply packages/languages/src/index.ts:30]: Yea, was just sticking with lodash because the values call did the same, probably should be Object.values / Object.keys. Is this a safe change or does lodash do something extra?

Comment (jsnajdr) [reply packages/languages/src/index.ts:30]: The Lodash versions accept a `null` or `undefined` argument and return an empty array for them. The standard `Object.*` versions will throw a `TypeError: Cannot convert undefined or null to object`.

Without Lodash, you need to check if the inputs are always valid objects/arrays and add some guards otherwise.

Comment (lsl) [reply packages/languages/src/index.ts:30]: So definitely safe now we're not downloading the file in the build. Will swap to those! thanks!

**Review by p-jackson — COMMENTED** [review]
I haven't quite finished my review yet: I can't seem to build calypso locally, and it also looks like there's a change where the new package isn't doing some sort of lazy load of something out of the config and I want to get to the bottom of that.

File: packages/i18n-utils/test/localize-url.js [hunk 7]
```diff
@@ -0,0 +1,333 @@
...
+		getLocaleSlug.mockImplementationOnce( () => 'en' );
+		expect( localizeUrl( 'https://automattic.com/cookies', 'fr' ) ).toEqual(
+			'https://automattic.com/fr/cookies/'
+		);
+		getLocaleSlug(); // make sure to consume it.
+
+		// Finally make sure that no overriding has stuck and it uses the getLocaleSlug() when no override is specified.
+		getLocaleSlug.mockImplementationOnce( () => 'ru' );
+		expect( localizeUrl( 'https://automattic.com/cookies/' ) ).toEqual(
+			'https://automattic.com/cookies/'
```
[the remark this answers is not in the document]
Comment (ramonjd) [reply packages/i18n-utils/test/localize-url.js:112]: > Or maybe Russian isn't a mag16 language

Officially it is on WPCOM

Here's the list:

```
			'es',
			'pt-br',
			'de',
			'fr',
			'he',
			'ja',
			'it',
			'nl',
			'ru',
			'tr',
			'id',
			'zh-cn',
			'zh-tw',
			'ko',
			'ar',
			'sv',
```

[the remark this answers is not in the document]
Comment (lsl) [reply packages/i18n-utils/test/localize-url.js:112]: automattic.com cookie and privacy policies are translated with a manual process (needs legal input irrc), we only have translations for a couple of locales on these pages and defer to english in most situations.

I just copy pasted these tests from lib/i18n-utils, the test description should probably explain why the locale needs to be overridden but I suspect most of these cases are ported from the php version of this function.

File: packages/i18n-utils/test/localize-url.js [hunk 8]
```diff
@@ -0,0 +1,333 @@
...
+			expect( localizeUrl( fullUrl ) ).toEqual( fullUrl );
+		} );
+	} );
+
+	test( 'handles invalid URLs', () => {
+		[ undefined, null, [], {}, { href: 'https://test' }, 'not-a-url', () => {} ].forEach(
+			( fullUrl ) => {
+				getLocaleSlug.mockImplementationOnce( () => 'en' );
+				expect( localizeUrl( fullUrl ) ).toEqual( fullUrl );
+				getLocaleSlug(); // make sure to consume it.
```
[the remark this answers is not in the document]
Comment (lsl) [reply packages/i18n-utils/test/localize-url.js:44]: Lets leave as is so this file continues to match the client/lib version... Actually maybe its a good idea to drop that duplicate test code right now?

File: packages/i18n-utils/test/localize-url.js [hunk 9]
```diff
@@ -0,0 +1,333 @@
...
+
+	test( 'trailing slash variations', () => {
+		getLocaleSlug.mockImplementationOnce( () => 'de' );
+		expect( localizeUrl( 'https://automattic.com/cookies/' ) ).toEqual(
+			'https://automattic.com/de/cookies/'
+		);
+		getLocaleSlug.mockImplementationOnce( () => 'de' );
+		expect( localizeUrl( 'https://automattic.com/cookies' ) ).toEqual(
+			'https://automattic.com/de/cookies/'
+		);
```
[the remark this answers is not in the document]
Comment (lsl) [reply packages/i18n-utils/test/localize-url.js:93]: It's probably an artifact of serverside version. We use a permalink structure that specifies trailing slash on urls in at least some if not all wp properties, so we probably have something that cleans these up in a filter running somewhere. I only learned about this recently so don't quote me as it might be off on some detail.

File: packages/i18n-utils/test/localize-url.js (hunk 8 above)
[the remark this answers is not in the document]
Comment (lsl) [reply packages/i18n-utils/test/localize-url.js:44]: further to that... all of these tests should just pass in the locale it wants to test, the mocking of getLocaleSlug should only really happen once to confirm the implementation uses getLocaleSlug if its not provided with a locale.

**Review by wp-desktop — DISMISSED** [review]
WordPress Desktop CI Failure for job "wp-desktop-mac".

@lsl please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/947082). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

File: packages/i18n-utils/test/localize-url.js (hunk 8 above)
[the remark this answers is not in the document]
Comment (p-jackson) [reply packages/i18n-utils/test/localize-url.js:44]: Yes actually! We only have to test it the hard way once 👍

**Review by p-jackson — APPROVED** [review]
Looks good 👍

**Comment by lsl** [comment]
This sort of non-side-by-side refactor is quite hard to do safely, caught a sloppy copy paste bug testing random links in the UI: [`59dd2bc` (#46998)](https://github.com/Automattic/wp-calypso/pull/46998/commits/59dd2bc43d7cfc5f574663361faf70913360041f)

**Comment by yuliyan** [comment]
Are [#localizeUrl unit tests in lib/i18n-utils](https://github.com/Automattic/wp-calypso/blob/master/client/lib/i18n-utils/test/utils.js) now redundant? If so, let's remove them in a follow-up PR before they start failing.
