### PR TITLE
Make 'v' open a new tab while 'enter' remains same

### LINKED ISSUE #30988: Reader: Keyboard Shortcut for "Visit Site"
#### Steps to reproduce
1. Starting at URL: WordPress.com/reader
2. Use `j` or `k` to navigate the list.
3. Type `v`.

#### What I expected
The URL for currently highlighted Reader item will be opened in a new tab/window.

#### What happened instead
Nothing.

#### Browser / OS version
Chrome / Mojave

#### Context / Source
#dogfooding
We have the ability to use the `enter` or `return` key to open the item within Reader, but coming from my experience with Google Reader and other RSS readers like FeedBin, the `v` key is commonly used to open the selected item within a new window or tab.

### PR DESCRIPTION
**Pull request by bor0**
#### Changes proposed in this Pull Request

* Make 'v' open a new tab while 'enter' remains same

#### Testing instructions

1. Navigate through the reader using `j` and `k` keys
2. Press `v`
Expected: It should open the post in a new tab
3. Press 'enter'
Expected: It should open the post in the same tab

Fixes #30988.

### CODE REVIEW

File: client/reader/stream/index.jsx [hunk 1]
```diff
@@ -173,6 +175,10 @@ class ReaderStream extends React.Component {
 		}
 	}
 
+	handleOpenSelectionNewTab = () => {
+		window.open( this.props.selectedPostKey.url, '_blank' );
```
Comment (blowery) [inline client/reader/stream/index.jsx]: we should also use `noreferrer,noopener` as the feature string to prevent opened windows from [getting a handle back to us via window.opener](https://developer.mozilla.org/en-US/docs/Web/API/Window/open#Window_functionality_features).
```suggestion
		window.open( this.props.selectedPostKey.url, '_blank', 'noreferrer,noopener' );
```
