### PR TITLE
Show Search options for Atomic sites

### LINKED ISSUE #21711: Search (Beta) shows for non-Jetpack sites in Calypso's "My Plan"
Two issues with "Search (Beta)", i.e. the new Jetpack search showing up under My Site > Plan > My Plan.

1. It shows for normal Business plan sites, which it shouldn't.

2. It shows for AT sites, which it should, but it links to Calypso's `wordpress.com/settings/traffic/` and there's no option to enable the new search from there. It can ONLY be enabled from WP-Admin > Jetpack settings.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plans/my-plan/{site}

Scroll down, you'll see this:

image

* To not show up for normal Business plan sites

* To does show up for AT sites (which it does), BUT, it links to a non-existent setting in `wordpress.com/settings/traffic/{site}` ...

There's no option to enable this search from `/settings/traffic/{site}`. This is reported in #19743

### PR DESCRIPTION
**Pull request by gravityrail**
Fixes #21711

Show Search options for Atomic and VIP Go sites on Business or Enterprise plans, as well as Jetpack sites on a Professional plan.

### CODE REVIEW

File: client/my-sites/site-settings/search.jsx [hunk 1]
```diff
@@ -152,10 +139,10 @@ class Search extends Component {
 				<SectionHeader label={ translate( 'Search' ) } />
 
 				<CompactCard className="search__card site-settings__traffic-settings">
-					{ siteIsJetpack ? this.renderJetpackSettings() : this.renderWpcomSettings() }
+					{ this.renderSettings() }
 				</CompactCard>
 				{ searchModuleActive && (
-					<CompactCard href={ widgetURL }>{ translate( 'Add Jetpack Search Widget' ) }</CompactCard>
+					<CompactCard href={ widgetURL }>{ translate( 'Add Search Widget' ) }</CompactCard>
```
Comment (a8ci18n) [inline client/my-sites/site-settings/search.jsx]: :disappointed: 16 existing translations will be lost with this change.
