### PR TITLE
VideoPress: Keep using the VideoPress player in video blocks after a downgrade

### LINKED ISSUE #30814: VideoPress: Block not migrated to default video block after a downgrade
#### Steps to reproduce
1. Go to `https://wordpress.com/block-editor/post` while proxied.
2. Select a site under a Premium plan.
3. Insert a video block and upload a new video.
4. Check you see the VideoPress player.
5. Save the post.
6. Downgrade to a free plan.
7. Open the previously saved post.

#### What I expected

Since VideoPress is not available now, the video block should fallback to the core video block (or maybe we should still use the VideoPress player since the video is still available in VideoPress?).

#### What happened instead

The editor displays an error saying the block contains invalid content.

#### Screenshot / Video

image

### PR DESCRIPTION
**Pull request by mmtr**
#### Changes proposed in this Pull Request

* Customize the video blocks even when VideoPress it not available, so we can support videos that were uploaded to VideoPress if it was available in the past (i.e. before a plan upgrade).
  * After a downgrade for Simple sites, existing VideoPress videos work in the published view. VideoPress previews in editor still works. Uploading new videos shows a permission error (which can be made more friendly in future work) and we see a related media modal video nudge if attempting to insert from the media library.
  * After a downgrade for Jetpack sites/module disable. VideoPress videos work in the published view. VideoPress previews in the editor work. New uploads, upload locally to the site, and exhibit core video block behavior.
* Rename and refactor the `isJetpackExtensionAvailable` function that was returning a `bool` value indicating wether the extension is available to a wider `getJetpackExtensionAvailability` utility so we can also check the reason why an extension is unavailable.

Fixes #30814 

#### Testing instructions

* Select an environment:
  * Gutenlypso.
    * Start Calypso with Calypsoify Iframe disabled: `DISABLE_FEATURES=calypsoify/iframe npm start`.
    * Go to `/block-editor`.
    * Select a site under a premium/business plan.
  * Jetpack.
    * [Create a new JN site using the extensions from this branch](https://jurassic.ninja/create?gutenpack&calypsobranch=update/videopress-extension-downgrade&jetpack-beta&shortlived&wp-debug-log).
    * Connect to WP.com using a premium/business subscription.
    * Go to Settings → Jetpack Constants in the site’s wp-admin and set `JETPACK_BETA_BLOCKS` to true.
    * Go to Jetpack → Settings and activate the VideoPress module (by enabling the "Enable high-speed, ad-free video player" option).
    * Go to Posts → New.
* Insert a video block and upload a new video.
* Check you see the VideoPress player.
* Save the post.
* Downgrade to a free plan or deactivate the VideoPress module.
* Open the previously saved post. Note that in Gutenlypso you need to actually reload the browser since the [extensions availability](https://github.com/Automattic/wp-calypso/blob/80ee7fbe83b121aae14d9dc5f4e876f6ad973cc9/client/gutenberg/editor/controller.js#L105-L116) is not updated when you change the plan and open the block editor in the same session.
* Make sure you still see the VideoPress player but:
  * You cannot upload new videos in Simple sites.
  * You can upload new videos in Jetpack but they are not converted by VideoPress.

image

### CODE REVIEW

File: client/gutenberg/extensions/presets/jetpack/utils/register-jetpack-block.js [hunk 1]
```diff
@@ -17,7 +17,7 @@ import isJetpackExtensionAvailable from './is-jetpack-extension-available';
  * @returns {object|false} Either false if the block is not available, or the results of `registerBlockType`
  */
 export default function registerJetpackBlock( name, settings, childBlocks = [] ) {
-	if ( ! isJetpackExtensionAvailable( name ) ) {
+	if ( ! getJetpackExtensionAvailability( name ).available ) {
```
Comment (gwwar) [inline client/gutenberg/extensions/presets/jetpack/utils/register-jetpack-block.js]: If we're going to use the unavailable reason later, it might be clearer to specify what this check means.
```jsx
const { available, unavailableReason } = getJetpackExtensionAvailability( name );
const unavailable = ! available;
```

**Comment by gwwar** [comment]
> * Open the previously saved post. Note that in Gutenlypso you need to actually reload the browser since the [extensions availability](https://github.com/Automattic/wp-calypso/blob/80ee7fbe83b121aae14d9dc5f4e876f6ad973cc9/client/gutenberg/editor/controller.js#L105-L116) is not updated when you change the plan and open the block editor in the same session.

😅 This probably need to be a query component in a separate PR. This might be causing some of these reports here: https://github.com/Automattic/wp-calypso/issues/30453

cc @Automattic/gutenpack

**Comment by gwwar** [comment]
For **simple sites** I don't think we ever want to switch back to using the core block representation. I think proposed behavior makes sense for Jetpack but not for WordPress.com simple sites.

Current behavior Calypso Classic -> Add Video -> Downgrade
1. Published post still works with video
2. VideoPress preview remains in calypso classic editor. (Video shows up in All in Media modal, but removes entries in the Video tab)

Gutenberg Editor -> Add Video -> Downgrade
1. Published post still works with video
2. Editor switches back to the core video block, resulting in broken previews for certain types.

screen shot 2019-02-18 at 4 29 34 pm

cc @apeatling

**Comment by mmtr** [comment]
Thanks for the feedback @gwwar! Actually, as per @jeherve's feedback (https://github.com/Automattic/jetpack/pull/11193#issuecomment-459328914, addressed in https://github.com/Automattic/jetpack/pull/11268) I think it makes sense to keep using the VideoPress player on the editor in Jetpack as well.

Since the extension fallbacks to the core video block when the video is not available on VideoPress it sounds reasonable to me to activate the extension even if we're missing a plan or the module is deactivated. That way, the blocks are backwards compatible with existing VideoPress videos.

I'm preparing an update applying the needed changes.
