### PR TITLE
Pass the siteSlug or siteId to further steps in the hero flow to support refreshing

### LINKED ISSUE #58339: [Bug]: refreshing at design picker step at onboarding shows white screen
### Quick summary

When refreshing the page when at design picker, onboarding breaks.

### Steps to reproduce

1. Create a new site from `/start` as logged in user, and pass domains, plans
2. At write/build question, note URL and answer build
   
    Screenshot 2021-11-22 at 10 55 23
 
3. At design picker, note how URL has lost site URL
    Screenshot 2021-11-22 at 10 55 34

4. Refresh the page, get error in console:
    Screenshot 2021-11-22 at 10 55 45
  

### What you expected to happen

Refresh to just work.

### What actually happened

White screen.

### Context

_No response_

### Browser

Mozilla Firefox

### Simple/Atomic

Simple

### Other notes

_No response_

### Reproducibility

Consistent

### Severity

_No response_

### Available workarounds?

_No response_

### Workaround details

_No response_

cc @autumnfjeld  for triage.

### PR DESCRIPTION
**Pull request by roo2**
#### Changes proposed in this Pull Request

Fixes https://github.com/Automattic/wp-calypso/issues/58339 By passing the `siteSlug` or `siteId` which is a required dependency for all steps of the hero flow.

Also passes the query param when users use the back button.

#### Testing instructions
Navigate to 
`/start/setup-site/intent?flags=signup/hero-flow&siteSlug=YOUR_SITE.wordpress.com` or
`/start/setup-site/intent?flags=signup/hero-flow&siteId=$YOUR_SITE_ID`

Navigate through the hero flow and assert that the siteId or siteSlug is passed to the next step.
Use browser refresh to refresh the page and verify that it loads correctly.

### CODE REVIEW

File: client/signup/utils.js [hunk 1]
```diff
@@ -1,9 +1,9 @@
 import config from '@automattic/calypso-config';
 import { translate } from 'i18n-calypso';
 import { filter, find, includes, isEmpty, pick, sortBy } from 'lodash';
+import { addQueryArgs } from 'calypso/lib/url';
 import flows from 'calypso/signup/config/flows';
 import steps from 'calypso/signup/config/steps-pure';
-
```
Comment (arthur791004) [inline client/signup/utils.js:6]: Still prefer to keep empty line after import section

File: client/signup/main.jsx [hunk 2]
```diff
@@ -542,7 +542,9 @@ class Signup extends Component {
 		// to invalid step.
 		if ( stepName && ! this.isEveryStepSubmitted() ) {
 			const locale = ! this.props.isLoggedIn ? this.props.locale : '';
-			page( getStepUrl( flowName, stepName, stepSectionName, locale ) );
+			const queryObject = ( this.props.initialContext && this.props.initialContext.query ) || {};
+			const siteSlugOrId = pick( queryObject, [ 'siteSlug', 'siteId' ] );
```
Comment (arthur791004) [inline client/signup/main.jsx]: Not important but `siteIdOrSlug` might be better as we use this term everywhere in our codebase except one.

File: client/signup/steps/design-picker/index.jsx [hunk 3]
```diff
@@ -308,6 +310,7 @@ export default function DesignPickerStep( props ) {
 			stepContent={ renderDesignPicker() }
 			align={ isReskinned ? 'left' : 'center' }
 			skipButtonAlign={ isReskinned ? 'top' : 'bottom' }
+			queryParams={ siteSlugOrId }
```
Comment (arthur791004) [inline client/signup/steps/design-picker/index.jsx]: I think we can pass `queryParams` in the following place and we don't need to handle this in every step component
```js
// main.jsx
<CurrentComponent
  ...
  queryParams={ siteIdOrSlug }
/>
```

**Review by arthur791004 — COMMENTED** [review]
Great job! How about doing it inside the `getStepUrl` function directly (I think we can get the query string from that function directly)? Then, we don't need to change so many places. But one thing that needs to take care of might be `getBackUrl` in the `NavigationLink` as it concatenates the querying with the return value of `getStepUrl`.

**Comment by roo2** [comment]
thanks for the feedback @arthur791004! I updated it to pass the value of `siteIdOrSlug` in via main.jsx as you suggested and this simplified the code quite a bit.

I also updated other usages of `getStepUrl` to pass in a `params` object rather than concatenating the params on the end.

I'm not sure how we should get the `siteIdOrSlug` from `getStepUrl`, we could use `window.location.search` but I think it is nicer to pass in the `params` argument because it is a clearer flow of data, even if it results in more code.

**Comment by arthur791004** [comment]
> I'm not sure how we should get the siteIdOrSlug from getStepUrl, we could use window.location.search but I think it is nicer to pass in the params argument because it is a clearer flow of data, even if it results in more code.

Yeah, we could use `window.location.search` to forward the query string to the previous/next step and we can avoid missing `siteIdOrSlug` in the future. But I'm okay with the current way 👍

**Review by arthur791004 — APPROVED** [review]

File: client/signup/main.jsx [hunk 4]
```diff
@@ -542,7 +542,9 @@ class Signup extends Component {
 		// to invalid step.
 		if ( stepName && ! this.isEveryStepSubmitted() ) {
 			const locale = ! this.props.isLoggedIn ? this.props.locale : '';
-			page( getStepUrl( flowName, stepName, stepSectionName, locale ) );
+			const queryObject = this.props.initialContext && this.props.initialContext.query;
+			const siteIdOrSlug = pick( queryObject, [ 'siteSlug', 'siteId' ] );
```
Comment (tyxla) [inline client/signup/main.jsx]: `pick()` is one of those Lodash functions that is very easy to replace with 1 or 2 lines of native code. 

In those instances, I'd strongly recommend not introducing an extra helper function, and using native code instead. If it's necessary in a component, you can always abstract it to a separate function.

For example, see how the usage here even makes the code simpler:

```suggestion
			const { siteSlug, siteId } = this.props.initialContext && this.props.initialContext.query;
			const siteIdOrSlug = { siteSlug, siteId };
```

**Review by tyxla — CHANGES_REQUESTED** [review]
I'd advise against introducing a `pick()` helper function, since it's a pretty simple functionality that can be achieved with very little code (just a simple object destructuring + creating a new object with the destructured props).

File: client/signup/main.jsx (hunk 4 above)
Comment (roo2) [reply client/signup/main.jsx]: oh yea... brain fart... oh well, I had fun implementing it 😂

Comment (arthur791004) [reply client/signup/main.jsx]: @tyxla We've replaced pick with native code.

File: packages/js-utils/src/pick.ts [hunk 5]
```diff
@@ -0,0 +1,16 @@
+/**
+ * Implementation of the lodash "pick" function
+ *
+ * @param object Object to pick properties from
+ * @param props The properties to pick
+ * @returns An object with only the "picked" properties
+ */
+export default function pick< T, U extends keyof T >( object: T, props: Array< U > ): Pick< T, U > {
```
Comment (tyxla) [inline packages/js-utils/src/pick.ts]: Seems like we can delete this one from the PR now. Thanks for simplifying the logic 👍

Comment (arthur791004) [reply packages/js-utils/src/pick.ts]: I think we can keep this in case somebody wants to use it in the future? Or we can also re-implement this function at that time 🤔

Comment (tyxla) [reply packages/js-utils/src/pick.ts]: The logic is very easy and implementable inline. That's preferable IMHO, rather than adding additional dependencies for one-liner functions. Not to mention that there's no reason to be introducing unused code. I suggest removing it.

Comment (arthur791004) [reply packages/js-utils/src/pick.ts]: Okay, I've removed it

**Comment by simison** [comment]
@tyxla are there/should there be Eslint warnings against using Lodash `pick()`?

**Comment by tyxla** [comment]
> @tyxla are there/should there be Eslint warnings against using Lodash `pick()`?

Yes, but our strategy to enable them for a particular Lodash function is to do it after we've fully refactored away from the Lodash version across the codebase, in order to avoid introducing new eslint warnings.

File: packages/js-utils/src/pick.ts (hunk 5 above)
Comment (arthur791004) [reply packages/js-utils/src/pick.ts]: @tyxla Okay, I've removed it!
