### PR TITLE
Invites: Fix Invite Accept Form Title

### LINKED ISSUE #95171: Sign up screen for viewer invite wording says "start editing"
### Quick summary

When inviting a user to an Atomic or Simple site, when following the confirmation link sent via email, and the invited user is not logged in on WordPres.com, the signup screen says "Sign up to start editing {site-title}"

### Steps to reproduce

1. On a Simple or Atomic private site, invite a user as a viewer. 
2. Click on the confirmation link received via email and make sure you are not logged into WordPress.com.
3. Check the sign-up screen text.

### What you expected to happen

See a different wording, like: 

Sign up to view/follow {site-title}.

### What actually happened

Seeing "Sign up to start editing {site-title}" as the screen title

### Impact

All

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

8275107-zd-a8c

### PR DESCRIPTION
**Pull request by Aurorum**
Fixes #95171

## Proposed Changes

There are two variants of the Invite Accept form that are relevant here: `InviteAcceptLoggedIn` and `InviteAcceptLoggedOut`. We also have `InviteFormHeader` which, as the name applies, is basically a heading for both those screens. But at the moment, something strange happens: `InviteFormHeader` is **only** used in `InviteAcceptLoggedIn`. In `InviteAcceptLoggedOut`, the code is extracted from `InviteFormHeader` and used manually (but not all of the code is, which is what causes the current bug).

To handle this better, I see two possible solutions:

1. Make `InviteAcceptLoggedIn` also use the extracted functions
2. Just use `InviteFormHeader` directly in both.

This PR does the second because I think it makes more sense to treat the form header like a component that can be used in both screens. For that reason, I've done the following:

* Moved `getExplanationForInvite` into a central location rather than having that function being called individually (but weirdly, only in the logged out screen and not the logged in screen)
* Treated it as a component, so that even though the styles are different for the logged in/out screen, they're included within the parent stylesheet instead.  

## Why are these changes being made?

* Currently when you invite a reader to a private site, the Invite Form title says "Sign up to start editing". This fixes that text to be more accurate since viewers cannot edit sites. 

## Testing Instructions

1. Create a private site on Account A
2. Invite Account B to be a viewer of that site (make sure you haven't actually registered Account B yet!)
3. Accept the invite link 
4. Confirm that you're now prompted to view the site rather than edit it (the strings were already there, and in the interests of i18n, I haven't changed them)

| Before | After |
|--------|--------|
| Screenshot 2024-10-05 at 13 32 44 | Screenshot 2024-10-05 at 13 32 31 |

5. Just in the interests of completeness, it might make sense to check the other use of `InviteFormHeader`. This is basically the same steps, but sending the invite to an email already with a WP.com account which you're signed into.

| Before | After |
|--------|--------|
| Screenshot 2024-10-05 at 14 51 41 | Screenshot 2024-10-05 at 14 51 37 | 

I removed some styles that are inherited with this change, but there should be no real difference. I might be misunderstanding what this code is trying to do, but I hope these changes make sense!

cc @jsnajdr, @renancarvalho, @agrullon95

### CODE REVIEW

File: client/my-sites/invites/invite-accept-logged-in/index.jsx [hunk 1]
```diff
@@ -86,11 +86,11 @@ class InviteAcceptLoggedIn extends Component {
 	renderMatchEmailError = () => {
 		return (
 			<Card>
-				<InviteFormHeader { ...this.props.invite } user={ this.props.user } matchEmailError />
```
Comment (Aurorum) [inline client/my-sites/invites/invite-accept-logged-in/index.jsx:89]: As far as I can tell, this prop doesn't do anything anymore, which is why I removed it.

Comment (ironprogrammer) [reply client/my-sites/invites/invite-accept-logged-in/index.jsx:89]: 👍🏻 Looks like it was rendered obsolete in https://github.com/Automattic/wp-calypso/commit/d598d15f172a1749354ad0d67a8b614c1d6fbefc.

File: client/my-sites/invites/invite-accept-logged-in/index.jsx [hunk 2]
```diff
@@ -86,11 +86,11 @@ class InviteAcceptLoggedIn extends Component {
...
+				<InviteFormHeader { ...this.props.invite } user={ this.props.user } />
 				<div className="invite-accept-logged-in__button-bar">
 					<Button onClick={ this.signInLink } href={ this.props.signInLink }>
 						{ this.props.invite.knownUser
-							? this.props.translate( 'Sign In as %(email)s', {
+							? this.props.translate( 'Sign in as %(email)s', {
```
Comment (ironprogrammer) [inline client/my-sites/invites/invite-accept-logged-in/index.jsx:93]: Nice catch!

**Comment by ironprogrammer** [comment]
Thanks for the PR, @Aurorum! 🙌🏻 This update works as advertised in my testing.

## Test Report
- This PR is a bit behind `trunk`, so I rebased it locally before testing the patch.
- I followed the testing steps from the issue description.
- Note that the use of periods/full-stops in `invite-form-header` caused the wrap to differ in this specific test (see text shift below), however, this usage is consistent with other `getLoggedOutTitleForInvite` values.

### Results
- ✅ "start editing" text is replaced with "begin viewing".
- ✅ Format and styles from `InviteFormHeader` are carried over, including the site title hyperlink and domain name in explanation text ("As a viewer...")

|       **Before**       |      **After**        |
| :----------: | :----------: |
| wp-calypso-95172-repro | wp-calypso-95172-patch |

File: client/my-sites/invites/invite-form-header/index.jsx [hunk 3]
```diff
@@ -186,12 +179,74 @@ class InviteFormHeader extends Component {
 		return title;
 	};
 
+	getExplanationForInvite = () => {
```
Comment (ironprogrammer) [inline client/my-sites/invites/invite-form-header/index.jsx:182]: Good call on consolidating these messages 👍🏻

**Review by ironprogrammer — APPROVED** [review]
This PR should be rebased, but otherwise these changes look good to me.

**Comment by ironprogrammer** [comment]
I've rebased this PR and reached out for a secondary reviewer/committer 🤞🏻

**Comment by ironprogrammer** [comment]
These changes have been deployed 🚢 .
