### PR TITLE
resize-image-url: Default to safe hosts when trying to resize images

### LINKED ISSUE #27787: Media Library Loads Very Slowly
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/media/143628165 or https://wordpress.com/media/51707092
2. Media loads really really slowly 

#### What I expected
To load normally, didn't notice this problem before

#### What happened instead
Takes ages to load. 

#### Browser / OS version

whatsmybrowser.org/b/YTZ7DLK
Mac OS 10.13.6

#### Screenshot / Video
https://d.pr/free/i/8kjZtS

Found this issue only on Atomic sites.

### PR DESCRIPTION
**Pull request by blowery**
The current resize-image-url function tries to force the url to a "safe" host using safeImageUrl when called with a numeric width and height, but does not do so when called with a parameter object. This patch reworks the code to always try to use a safe host, unless a new param is specified. The param is also used to prevent infinite recursion.

Testing Instructions:
* Load the media library on a simple site, an atomic site, and a jp site. We should pull images from photon on the atomic and jp sites and from files.wordpress.com on the simple site.

Fixes #27787

### CODE REVIEW

File: client/lib/resize-image-url/index.js [hunk 1]
```diff
@@ -42,7 +42,7 @@ const SIZE_PARAMS = [ 'w', 'h', 'resize', 'fit', 's' ];
  * @type {Object}
  */
 const SERVICE_HOSTNAME_PATTERNS = {
-	photon: /(^i\d\.wp\.com|(^|\.)wordpress\.com)$/,
+	photon: /(^[is]\d\.wp\.com|(^|\.)wordpress\.com)$/,
```
Comment (blowery) [inline client/lib/resize-image-url/index.js]: do we have photon urls that look like i0.wp.com?

Comment (blowery) [reply client/lib/resize-image-url/index.js]: ah yeah, non-secure.

**Review by flootr — APPROVED** [review]
> We should pull images from photon on the atomic and simple sites.

This should be atomic and jp and not simple sites, right? If so, this works as expected 👍
