### PR TITLE
Show upgrade banner when installing a theme on a Limited Atomic site

### LINKED ISSUE #65295: Upgrade banner missing in the Install Theme page for Limited Atomic sites
### Quick summary

The `/themes/upload` page seems to be missing an upgrade banner when visited from an Atomic site on lower-tier plan. It also shows a weird message that looks related to the Atomic eligibility warnings modal.

### Steps to reproduce

- Go to https://wpcalypso.wordpress.com/themes/upload
- Select an Atomic sites with a lower-tier plan (e.g. Starter plan)

### What you expected to happen

To see an upgrade banner offering the Pro plan, like we do on Simple sites:

Screen Shot 2022-07-06 at 15 43 06

### What actually happened

There is no upgrade banner, and the page displays a weird message that looks related to the Atomic eligibility warnings modal:

Screen Shot 2022-07-06 at 15 42 56

### PR DESCRIPTION
**Pull request by mmtr**
Fixes https://github.com/Automattic/wp-calypso/issues/65295

#### Proposed Changes

Ensures that an upgrade banner shows up in the Install Theme page on Atomic sites with a lower-tier plan. It also hides the Atomic eligibility component

Before | After
--- | ---
Screen Shot 2022-07-06 at 15 42 56 | Screen Shot 2022-07-06 at 17 39 30

#### Testing Instructions

- Use the Calypso live link below
- Go to `/themes/upload`
- Switch to an Atomic site with a lower-tier plan (e.g. Starter plan)
- Make sure you see an upgrade banner and there is no Atomic eligibility messages
- Make sure there are no regressions in other sites
  - Simple sites on Free/Starter should show an upgrade banner
  - Simple sites on Pro should show the Atomic eligibility warning
  - Jetpack sites on any plan should allow theme uploads

### CODE REVIEW

**Comment by obenland** [comment]
It looks like the upload dropzone is now active and usable, whereas in production it's disabled?

Production: 
image

Calypso Live:
image

**Comment by mreishus** [comment]
Seeing the same thing.

File: client/my-sites/themes/theme-upload/index.jsx [hunk 1]
```diff
@@ -266,15 +265,13 @@ class Upload extends Component {
...
+			isAtomic,
 			selectedSite,
 			uploadedTheme,
 		} = this.props;
 
-		const { showEligibility } = this.state;
-
 		const uploadAction = isJetpack ? this.props.uploadTheme : this.props.initiateThemeTransfer;
-		const isDisabled = showEligibility || ( ! canUploadThemesOrPlugins && ! isJetpack );
+		const isDisabled = ! canUploadThemesOrPlugins && ! isJetpack;
```
Comment (mreishus) [inline client/my-sites/themes/theme-upload/index.jsx]: -> isStandaloneJetpack ?

**Comment by mmtr** [comment]
Good catch! Should be fixed now.

**Comment by obenland** [comment]
It is now also disabled for Simple sites on a Pro plan, I'm afraid (even after clicking on "Continue").

image

**Comment by mreishus** [comment]
Ah, the `showEligibility ||` part was used to enable after continue is clicked

**Comment by mmtr** [comment]
My goodness, this code is quite convoluted 😅 I _think_ it should be working now?

**Review by obenland — APPROVED** [review]
