### PR TITLE
Fix migration flow from white screen

### LINKED ISSUE #98243: White screen when attempting to import a site
### Quick summary

When using the site importer **any** action from the [migrate site screen](https://wordpress.com/setup/hosted-site-migration/site-migration-identify?source=sites-dashboard&ref=topbar) results in a white screen.

### Steps to reproduce

1. Open https://wordpress.com/sites
2. Open the 'Add new site' dropdown menu, and select 'Import an existing site'

Path 1:
Enter a valid site url for a live website and submit the form, then observe the 'Scanning your site' message and loading animation

Path 2:
Click 'pick your current platform from a list'

### What you expected to happen

Path 1:
A new screen loads with the result of the scan

Path 2:
A new screen loads with a list of platforms

### What actually happened

Empty white screen for both paths.

### Impact

All

### Available workarounds?

No and the platform is unusable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

Google Chrome

When submitting a site, there is a 404 response for https://public-api.wordpress.com/rest/v1.1/sites/?http_envelope=1&force=wpcom

Image

When 'pick your current platform from a list' is clicked there are no errors.

### PR DESCRIPTION
**Pull request by candy02058912**
Fixes https://github.com/Automattic/wp-calypso/issues/98243

## Proposed Changes

* Use `flow.variantSlug` instead of `flow.name` for `hosted-site-migration` flow

## Why are these changes being made?

* p1736747265983289-slack-C02FMH4G8

## Testing Instructions

1. Open https://wordpress.com/sites
2. Open the 'Add new site' dropdown menu, and select 'Import an existing site'

Path 1:
Enter a valid site url for a live website and submit the form, then observe the 'Scanning your site' message and loading animation

1. Go to migrate flow for WP sites
WP@2x

2. Go to platform selection for sites from other platform
platform selection@2x

Path 2:
Click 'pick your current platform from a list'

1. Go to platform selection

platform selection@2x

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/landing/stepper/declarative-flow/internals/hooks/use-flow-navigation/index.tsx [hunk 1]
```diff
@@ -110,8 +111,14 @@ export const useFlowNavigation = ( flow: Flow ): FlowNavigation => {
 				...extraData,
 			} );
 
+			// For HOSTED_SITE_MIGRATION_FLOW, we must use the flow.variantSlug instead of flow.name
+			// to prevent navigation errors.
+			const exceptionFlowsToUseVariantSlug = [ HOSTED_SITE_MIGRATION_FLOW ];
```
Comment (candy02058912) [inline client/landing/stepper/declarative-flow/internals/hooks/use-flow-navigation/index.tsx]: Trying to keep things as contained as possible as this is an escalation: p1736747265983289-slack-C02FMH4G8

File: client/landing/stepper/declarative-flow/internals/hooks/use-flow-navigation/index.tsx [hunk 2]
```diff
@@ -110,8 +111,14 @@ export const useFlowNavigation = ( flow: Flow ): FlowNavigation => {
...
+
 			const newPath = generatePath( `/:flow/:step/:lang?`, {
-				flow: flow.name,
+				flow: exceptionFlowsToUseVariantSlug.includes( flow.variantSlug ?? '' )
```
Comment (arthur791004) [inline client/landing/stepper/declarative-flow/internals/hooks/use-flow-navigation/index.tsx]: I assume we can simply use `variationSlug` as the flow name at the top of this hook 🙂

```js
const flowName = flow.variantSlug ?? flow.name;
```

Comment (arthur791004) [reply client/landing/stepper/declarative-flow/internals/hooks/use-flow-navigation/index.tsx]: [#98083](https://github.com/Automattic/wp-calypso/pull/98083/files#diff-02905ef287e14f1af091215bc793466996490677638f8f5f2e0b944768f07133L41) changed to use the flow name from the `flow` object instead of the `:flow` from the URL path, so I think it's safe to keep using the `variantSlug` as the flow name if it's defined.

Comment (arthur791004) [reply client/landing/stepper/declarative-flow/internals/hooks/use-flow-navigation/index.tsx]: Actually, I'm unsure what's the benefit of the `variantSlug` 🙈

Comment (candy02058912) [reply client/landing/stepper/declarative-flow/internals/hooks/use-flow-navigation/index.tsx]: I see we're using the same sort of logic [here](https://github.com/Automattic/wp-calypso/blob/2953316a4d35e4b38f149d5be1fb6b073768c7d2/client/landing/stepper/declarative-flow/internals/index.tsx#L234) and [here](https://github.com/Automattic/wp-calypso/blob/2953316a4d35e4b38f149d5be1fb6b073768c7d2/client/landing/stepper/hooks/use-login-url-for-flow.ts#L60).
Seems safe to change it to be a more generic case.

**Review by arthur791004 — APPROVED** [review]
👍

**Comment by arthur791004** [comment]
There seem to be potential issues [here](https://github.com/Automattic/wp-calypso/blob/2953316a4d35e4b38f149d5be1fb6b073768c7d2/client/landing/stepper/declarative-flow/internals/hooks/use-flow-navigation/index.tsx#L65). But let's address it later 🙂

**Comment by candy02058912** [comment]
> There seem to be potential issues [here](https://github.com/Automattic/wp-calypso/blob/2953316a4d35e4b38f149d5be1fb6b073768c7d2/client/landing/stepper/declarative-flow/internals/index.tsx#L170). But let's address it later 🙂

Got it, thanks! Will create a follow-up for that.

File: client/landing/stepper/declarative-flow/internals/hooks/use-flow-navigation/index.tsx (hunk 2 above)
Comment (talldan) [reply client/landing/stepper/declarative-flow/internals/hooks/use-flow-navigation/index.tsx]: Not a blocker to the PR, but is it worth testing other stepper flows that might have been affected (that also use the `variantSlug`) to see if they were previously broken and will be fixed by this PR?

There are two that I can see:
- googleDomainTransfer
- siteSetupWithoutGoalsFlow

I'm still learning the codebase, so I'm not sure how to test these.

Comment (candy02058912) [reply client/landing/stepper/declarative-flow/internals/hooks/use-flow-navigation/index.tsx]: Tested these flows:
* ✅ /setup/domain-transfer/intro: googleDomainTransfer
* ✅ /start/guided: siteSetupWithoutGoalsFlow (confirmed that this got fixed, it is going to the goals step in production, but not anymore with this PR)
