### PR TITLE
Signup: Do not show post landing upgrade screen if a user doesn't create a domain.

### LINKED ISSUE #17407: Signup: Site specific copy even if a user is only creating an account
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start/account
2. Create an account
3. See the success screen:

screen shot 2017-08-21 at 18 14 46

This copy isn't appropriate for users who are just creating an account.

cc @taggon

### PR DESCRIPTION
**Pull request by taggon**
The post-signup upgrade screen should appear only when a user creates a website with free domain because the screen contains site specific copy.

## How to test

1. Set the _postSignupUpgradeScreen_ A/B test to _modified_.
2. You shouldn't be able to see the upgrade screen in the following cases:
  - Create a new account from https://wordpress.com/start/account
  - Create a new account from https://wordpress.com/start/rebrand-cities
  - Create a site with a custom domain from https://wordpress.com/start
3. The upgrade screen should show up in the following case:
  - Create a site with free plan from https://wordpress.com/start

Close #17407

### CODE REVIEW

File: client/signup/processing-screen/index.jsx [hunk 1]
```diff
@@ -231,7 +235,7 @@ export class SignupProcessingScreen extends Component {
 	}
 
 	render() {
-		if ( abtest( 'postSignupUpgradeScreen' ) === 'modified' && ! this.state.hasPaidSubscription && this.props.flow !== 'rebrand-cities' ) {
+		if ( abtest( 'postSignupUpgradeScreen' ) === 'modified' && ! this.state.hasPaidSubscription && this.currentFlowIncludesDomainStep() ) {
```
Comment (akirk) [inline client/signup/processing-screen/index.jsx]: Is that change in logic intentional?

Comment (taggon) [reply client/signup/processing-screen/index.jsx]: @akirk Yes, it was my intention. Like _rebrand-cities_, flows that don't create a custom domain should skip the new post-signup screen.

Comment (akirk) [reply client/signup/processing-screen/index.jsx]: Ok, I just think for clarity in the PR it would have been useful to explain that `this.props.flowSteps.indexOf( 'domains' ) !== -1` covers the `this.props.flow !== 'rebrand-cities'` case also.
