### PR TITLE
FSE: Handle post content block with no attributes when merging post with template

### LINKED ISSUE #34431: FSE: Content not saved when post content block align attribute is unset
#### Steps to reproduce
* Make sure you have activated the FSE plugin in your [dev environment](https://github.com/Automattic/wp-calypso/tree/master/apps/full-site-editing).
* Go to Templates (`/wp-admin/edit.php?post_type=wp_template`)
* Create a new template containing a header template part, a post content block and a footer template part.
image

* Make sure the post content block doesn't have any align attribute specified:
image

* Publish the template.
* Go to Pages > Add new (`/wp-admin/post-new.php?post_type=page`)
* Select any starter page template.
* On the FSE sidebar, select the new template created above:
image

* Publish the page and reload the editor, so the new template is applied.
* Add some content, update the page and reload the editor.

#### What I expected

The new content to be in the editor.

#### What happened instead

The content is missing in the post content block.

#### Context / Source

I think this is a edge case not covered in https://github.com/Automattic/wp-calypso/pull/34318

### PR DESCRIPTION
**Pull request by mmtr**
#### Changes proposed in this Pull Request

In order to display the template on the editor, the FSE plugin merges the content with the template during the `the_post` action ([#](https://github.com/Automattic/wp-calypso/blob/d05a79ff74bac431ff30a2e74dab54746cc39475/apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php#L35)). 

Previously, the plugin was assuming that any post content block present in the template will have attributes ([#](https://github.com/Automattic/wp-calypso/blob/d05a79ff74bac431ff30a2e74dab54746cc39475/apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php#L481-L485)), but that won't be true after https://github.com/Automattic/themes/pull/1103, making the `str_replace` call to don't wrap the inner blocks in a post content block, since the expected pattern was not found.

This PR tries to make that merge more abstract by just copying the same markup present in the template. If there are no attributes, the wrapped post content block won't have them.

#### Testing instructions

* Update your sandbox with the latest changes of the FSE plugin (D30622).
* Update your sandbox with the changes to the Modern Business theme available at https://github.com/Automattic/themes/pull/1103.
* Switch to the Modern Business theme. If that was already the active theme of your site, you'll need to delete the existing template parts and templates and then deactivate Modern Business. To make sure that when you reactivate modern business that it repopulates everything, you'll need to comment out the line in `inc/fse-template-data.php` where it bails to prevent multiple insertions. (line 29).
* Start creating a new page.
* Add some content save it.
* Reload the editor.
* Make sure the content previously added is present on the editor after the reload.

Fixes #34431

### CODE REVIEW

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php [hunk 1]
```diff
@@ -478,25 +478,7 @@ public function merge_template_and_post( $post ) {
...
-	 *
-	 * @param array $blocks    An array of template blocks.
-	 */
-	private function get_post_content_block_attrs( $blocks ) {
-		foreach ( $blocks as $key => $value ) {
-			if ( 'a8c/post-content' === $value['blockName'] ) {
-				return count( $value['attrs'] ) > 0 ? wp_json_encode( $value['attrs'] ) : '';
-			}
-		}
+		$post->post_content = preg_replace( '@(<!-- wp:a8c/post-content)(.*?)(/-->)@', "$1$2-->$post->post_content<!-- /wp:a8c/post-content -->", $template_content );
```
Comment (vindl) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php]: Optional: might be easier to read if we explicitly copy `<!-- wp:a8c/post-content` instead of `$1`. We'd also only need a capturing group for `.*?` in that case.
