### PR TITLE
Plans: Fix plans flashing incorrect interval 

### LINKED ISSUE #75778: Plans: Picking a monthly plan quickly flashes the annual plans grid
### Quick summary

When selecting a monthly plan, specifically on `/start/hosting`, the screen briefly shows the annual plans before proceeding to the domains step.

https://user-images.githubusercontent.com/26530524/232076941-f300ca1b-230a-4975-83fd-6416790a1861.mov

### Steps to reproduce

1. Browse `/start/hosting`;
2. Switch to monthly plans;
3. Click any monthly plan;
4. Check that the screen rapidly flashes the annual plans before proceeding to the domains step.

### What you expected to happen

The user should not see the annual plans flash.

### What actually happened

The user sees the annual plans for a brief period.

### Impact

All

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by vykes-mac**
Closes to #75778

## Proposed Changes
The issue is due to the fact that when clicking `Get Business` the url gets updated with the domain step and the plans component re-renders, The `getIntervalType` function then checks the url for query param `intervalType` which doesn't exist since url is updated to the domain step, it then fallback to yearly because `intervalType` is missing.

* Since the plan step url is stored in the `path` props, this change passes the path to the `getIntervalType` method and extracts the interval from the `path`. If it doesn't exist in the path it attempts to find it in `window.location` otherwise it fallback to yearly.

## Testing Instructions
1. Browse `/start/hosting`;
2. Switch to monthly plans;
3. Click any monthly plan;
4. Check that the screen doesn't flash the annual plans before proceeding to the domains step. (see issue for video of what's happening)

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: client/signup/steps/plans/util.ts [hunk 1]
```diff
@@ -6,9 +6,16 @@ type DomainItem = {
...
 };
 
-export const getIntervalType = (): string => {
-	const urlParts = getUrlParts( typeof window !== 'undefined' ? window.location?.href : '' );
-	const intervalType = urlParts?.searchParams.get( 'intervalType' ) || '';
+export const getIntervalType = ( path?: string ): string => {
+	const pathHasIntervalType = path?.includes( 'intervalType=' );
+
+	if ( pathHasIntervalType ) {
+		const urlPartsFromPath = getUrlParts( path || '' );
```
Comment (zaguiini) [inline client/signup/steps/plans/util.ts]: It feels a little over-defensive to have `path || ''`.

We're checking if the path includes `intervalType=` by string matching, and if does, then `path` already exists and is not empty. Instead, we can check if the `path` variable is defined. If not, we can fall back to the `window.location`.

Here's how I'd write this function:

```js
export const getIntervalType = ( path?: string ): string => {
  const url = path ?? window?.location?.href ?? '';
  const intervalType = getUrlParts( url ).searchParams.get( 'intervalType' ) ?? 'yearly';

  ... /* keep the rest as it is */
}
```

**Review by zaguiini — APPROVED** [review]
Looks good to me! Stopped seeing the plans flash after a selection. Great stuff :shipit:
