### PR TITLE
Fix: Show subtitles on /me/purchases and edit subtitle on /purchases/subscriptions

### LINKED ISSUE #52174: Purchases: Show subtitles on /me Purchases screen to match
We recently added subheadings to many pages across Calypso, including `/purchases/[site]`. There's another Purchases screen at `/me/purchases` that has the same content and could benefit from the same subheading. It should read:

`View, manage, or cancel your WordPress.com plan and other purchases.`

The subheading should probably also be present on the Billing History and Payment Methods screens in the `/payments` section:

Screen Shot 2021-04-21 at 3 54 32 PM

pbAPfg-1iV-p2#comment-3017 /cc @donalirl

### PR DESCRIPTION
**Pull request by chrisfromthelc**
#### Changes proposed in this Pull Request

* Update the subtitle from `View, manage, or cancel your WordPress.com plan and other purchases.` to `View, manage, or cancel your plan and other purchases.` to be inclusive of non-WPCOM products (Jetpack, etc.) on `/purchases/subscriptions`. Additionally, add the subtitle to Billing History, "View, print, and email your receipts." and add the subtitle to Payment Methods, "Add or delete payment methods for your account".

Markup 2021-07-21 at 11 36 40

* Add the subtitle `View, manage, or cancel your plan and other purchases.` to `/me/purchases` to show on the Active Upgrades tab. Additionally, add the subtitle to Billing History, "View, print, and email your receipts." and add the subtitle to Payment Methods, "Add or delete payment methods for your account".

Screenshot on 2021-07-21 at 11-35-24

Fixes #52174

#### Testing instructions

* Visit `/purchases/subscriptions` and observe if text is updated to `View, manage, or cancel your WordPress.com plan and other purchases.` on the Active Upgrades tab. Also check for presence of "View, print, and email your receipts." on Billing History and "Add or delete payment methods for your account" on Payment Methods.
* Visit `/me/purchases` and observe if the text `View, manage, or cancel your WordPress.com plan and other purchases.` is present on the Active Upgrades tab. Also check for presence of "View, print, and email your receipts." on Billing History and "Add or delete payment methods for your account" on Payment Methods.

### CODE REVIEW

**Review by nbloomf — APPROVED** [review]
Nice; the updated text looks good in both `me/purchases` and `purchases`.

Screen Shot 2021-07-21 at 1 46 36 PM

Screen Shot 2021-07-21 at 1 46 52 PM

File: client/my-sites/purchases/main.tsx [hunk 1]
```diff
@@ -68,9 +68,7 @@ export function Purchases(): JSX.Element {
 				brandFont
 				className="purchases__page-heading"
 				headerText={ titles.sectionTitle }
-				subHeaderText={ translate(
-					'View, manage, or cancel your WordPress.com plan and other purchases.'
-				) }
+				subHeaderText={ translate( 'View, manage, or cancel your plan and other purchases.' ) }
```
Comment (a8ci18n) [inline client/my-sites/purchases/main.tsx]: :warning: This change will be queued for retranslation. We'll display the English text until then.

**Comment by jjchrisdiehl** [comment]
Same results as Nathan, this looks good to me:

`/me/purchases`

image

`/purchases/subscriptions/[site]`

image

Small aside, would we want to just provide copy that is generic such as:

"View, manage, or cancel your ~plan and other~ purchases."

**Review by michaeldcain — CHANGES_REQUESTED** [review]
The current changes look great, but while we're at it, [can we add subtitles to the other tabs inside the purchase section](https://github.com/Automattic/wp-calypso/issues/52174#issuecomment-864082484)?

Screen Shot 2021-07-21 at 8 42 24 PM
Screen Shot 2021-07-21 at 8 42 29 PM

I think for Billing History we could say "View, print, and email your receipts." and for Payment Methods, "Add or delete payment methods for your account". These would persist to the sub-pages of the tabs. We can do this in a follow-up PR, but in that case, remove the "Fixes #---" from this PR.

**Comment by chrisfromthelc** [comment]
> The current changes look great, but while we're at it, [can we add subtitles to the other tabs inside the purchase section](https://github.com/Automattic/wp-calypso/issues/52174#issuecomment-864082484)?
>  
> I think for Billing History we could say "View, print, and email your receipts." and for Payment Methods, "Add or delete payment methods for your account". These would persist to the sub-pages of the tabs. We can do this in a follow-up PR, but in that case, remove the "Fixes #---" from this PR.

Sorry, I misread that section to mean that those tabs should specifically not have anything. I've added the suggested text on Billing History and Payment Methods in both `/me/purchases` and `/purchases/subscriptions`.

One thing I wanted to note is that in [client/me/purchases/payment-methods/main.tsx](https://github.com/Automattic/wp-calypso/pull/54772/files#diff-59f41ee55370a1db7bbbd207b3fefb26df80126dec8b05953035d6d08b3eab06), `useTranslate()` was not being imported. I went ahead and imported that in line with how the other sections were imported in their respective files.

The sections should render now as shown in these screenshots.

Screenshot on 2021-07-21 at 21-21-15
Screenshot on 2021-07-21 at 21-21-25
Screenshot on 2021-07-21 at 21-21-33

I've also updated the original PR description to include the addition of the Billing History and Payment Methods subtitles.

File: client/my-sites/purchases/billing-history/index.tsx [hunk 2]
```diff
@@ -76,6 +76,7 @@ export function BillingHistory( { siteSlug }: { siteSlug: string } ) {
 				brandFont
 				className="billing-history__page-heading"
 				headerText={ titles.sectionTitle }
+				subHeaderText={ translate( 'View, print, and email your receipts.' ) }
```
Comment (michaeldcain) [inline client/my-sites/purchases/billing-history/index.tsx]: Since this is the site-specific view, can we update it to `View, print, and email your receipts for this site.`

File: client/my-sites/purchases/main.tsx (hunk 1 above)
Comment (michaeldcain) [reply client/my-sites/purchases/main.tsx]: Since this is the site-specific view, can we update it to `View, manage, or cancel your plan and other purchases for this site.`

File: client/my-sites/purchases/payment-methods/index.tsx [hunk 3]
```diff
@@ -72,6 +72,7 @@ export function PaymentMethods( { siteSlug }: { siteSlug: string } ): JSX.Elemen
 				brandFont
 				className="payment-methods__page-heading"
 				headerText={ titles.sectionTitle }
+				subHeaderText={ translate( 'Add or delete payment methods for your account.' ) }
```
Comment (michaeldcain) [inline client/my-sites/purchases/payment-methods/index.tsx:75]: This one is good - even though it's the site-specific view, payment methods are managed for the entire account.

**Review by michaeldcain — CHANGES_REQUESTED** [review]
This is looking good. In testing, I noticed that it's probably worth adding something to indicate that some of these views are site-specific. Sorry for the additional back and forth on this one.

File: client/my-sites/purchases/billing-history/index.tsx (hunk 2 above)
Comment (chrisfromthelc) [reply client/my-sites/purchases/billing-history/index.tsx]: Instead of `View, print, and email your receipts for this site.`, should we go as far as `View, print, and email your receipts for example.com` with the specific site address (and replicate to the other site-specific views)?

Comment (michaeldcain) [reply client/my-sites/purchases/billing-history/index.tsx]: I think that's a good idea, but I'm worried about any confusion that might be attached to multiple domains on a single site, or for instance if an email was for a secondary domain. Customer Home and Domains both use "your site", which I thought about doing, but "email _your_ receipts for _your_ site" felt redundant.

Comment (chrisfromthelc) [reply client/my-sites/purchases/billing-history/index.tsx]: This is now added.

Screen Shot 2021-07-23 at 12 33 12 PM

Marking as resolved.

File: client/my-sites/purchases/payment-methods/index.tsx (hunk 3 above)
Comment (chrisfromthelc) [reply client/my-sites/purchases/payment-methods/index.tsx:75]: `client/my-sites/purchases/main.tsx` is corrected now as well.

Screen Shot 2021-07-23 at 12 32 51 PM

Marking as resolved.

File: client/me/purchases/purchases-list/index.jsx [hunk 4]
```diff
@@ -177,7 +177,12 @@ class PurchasesList extends Component {
 				<PageViewTracker path="/me/purchases" title="Purchases" />
 				<MeSidebarNavigation />
 
-				<FormattedHeader brandFont headerText={ titles.sectionTitle } align="left" />
+				<FormattedHeader
+					brandFont
+					headerText={ titles.sectionTitle }
+					subHeaderText={ translate( 'View, manage, or cancel your plan and other purchases.' ) }
```
Comment (a8ci18n) [inline client/me/purchases/purchases-list/index.jsx:183]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **17** times:
`translate( 'View, manage, or cancel your WordPress.com plan and other purchases.' )` *ES Score: 10*

File: client/my-sites/purchases/main.tsx [hunk 5]
```diff
@@ -69,7 +69,7 @@ export function Purchases(): JSX.Element {
 				className="purchases__page-heading"
 				headerText={ titles.sectionTitle }
 				subHeaderText={ translate(
-					'View, manage, or cancel your WordPress.com plan and other purchases.'
+					'View, manage, or cancel your plan and other purchases for this site.'
```
Comment (a8ci18n) [inline client/my-sites/purchases/main.tsx:72]: :warning: This change will be queued for retranslation. We'll display the English text until then.

File: client/me/purchases/purchases-list/index.jsx (hunk 4 above)
Comment (chrisfromthelc) [reply client/me/purchases/purchases-list/index.jsx:183]: Resolving since this is a new string being added intentionally.

**Comment by chrisfromthelc** [comment]
The E2E tests for `[WPCOM] Editor: Media Upload (mobile) @parallel @jetpack: Can upload a normal image` are continually failing, and appear unrelated to the changes in this PR. It looks as if it's timing out in trying to select the Image block.

After chatting with @sirbrillig, it seems that it'll be okay to ignore and merge this.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6277384

Thank you @chrisfromthelc for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6277384).
