### PR TITLE
Desktop App: remove dependency on Keytar for Windows 32bit compatibility.

### LINKED ISSUE #80092: Desktop App: 32bit Windows app crashes with "keytar.node is not a valid Win32 application".
### Quick summary

User reports the app crashes and they get an error.

Ticket: 6516883-zd-woothemes
Slack: p1690626327588859-slack-C08GLCXMZ

### Steps to reproduce

1. On a Windows device (user's appear to be 32bit) open the WordPress.com app version 8.0.0 or 8.0.1
2. Notice an error appears and the app crashes
 
image

### What you expected to happen

The app to open and work as usual. 

### What actually happened

It crashed.

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

The user has been using version 7.2.0.

### PR DESCRIPTION
**Pull request by worldomonation**
Fixes: https://github.com/Automattic/wp-calypso/issues/80092

## Proposed Changes

This PR removes the use of `node-keytar` (which has been deprecated as of December 2022) in favor of the built-in `electron.safeStorage` and `electron-store`. 

Idea for this came from https://freek.dev/2103-replacing-keytar-with-electrons-safestorage-in-ray.

## Testing Instructions

Check the artifacts:
  - [x] Windows 32-bit.
  - [x] Windows 64-bit.
  - [x] macOS Apple Silicon.
  - [x] macOS Intel.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by wp-desktop — DISMISSED** [review]
WordPress Desktop CI Failure for job "wp-desktop-mac".

@worldomonation please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/1125530). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

**Comment by worldomonation** [comment]
@nsakaimbo Who else would you like me to ping for reviews in the future for the desktop app?

File: desktop/app/lib/keychain/index.js [hunk 1]
```diff
@@ -1,26 +1,31 @@
...
 async function read( key ) {
-	let value = await keytar.getPassword( keychainService, key );
-	if ( value ) {
-		value = JSON.parse( value );
+	if ( store.has( key ) ) {
+		const buffer = store.get( key );
+		return safeStorage.decryptString( Buffer.from( buffer, 'latin1' ) );
 	}
-	return value;
+	throw new Error( 'Requested value not found.' );
```
Comment (worldomonation) [inline desktop/app/lib/keychain/index.js:26]: I am guessing this is new behavior, as previously there was no check whether the target key exists in the keychain/store.

File: desktop/app/lib/keychain/index.js [hunk 2]
```diff
@@ -1,26 +1,31 @@
-const keytar = require( 'keytar' );
+const { safeStorage } = require( 'electron' );
```
Comment (worldomonation) [inline desktop/app/lib/keychain/index.js:1]: This was introduced with Electron v15, and it uses the system's keychain to perform encrypt/decrypt actions. From what I've read, it is just as secure as using `keytar` because both use the system keychain to manage the key.

**Comment by nsakaimbo** [comment]
Seems like a reasonable fix. Have you tested what happens to the app when upgrading from the previous app version with keytar, and already logged in? You can do so by installing the current app version, logging in, and without uninstalling the existing version, installing the build from this PR. I'm hoping that in the worst case, the user simply has to log in again - but hopefully not some sort of 4xx error.

**Review by nsakaimbo — APPROVED** [review]
Patch seems reasonable - nice work. See my note regarding manually testing the upgrade to ensure nothing is borked.

File: desktop/app/lib/keychain/index.js [hunk 3]
```diff
@@ -1,26 +1,31 @@
...
+} );
 
 async function write( key, value ) {
-	return keytar.setPassword( keychainService, key, JSON.stringify( value ) );
+	if ( ! safeStorage.isEncryptionAvailable() ) {
+		throw new Error( 'Encryption is not avaialble.' );
+	}
+
+	const buffer = safeStorage.encryptString( value );
+	store.set( key, buffer.toString( 'latin1' ) );
```
Comment (nsakaimbo) [inline desktop/app/lib/keychain/index.js]: Why latin1, and not utf-8?

Comment (worldomonation) [reply desktop/app/lib/keychain/index.js]: Good question! I took it from the source I referenced, which uses `latin1`. Probably a good idea to use `utf8` as you suggest, though.

**Comment by worldomonation** [comment]
> Seems like a reasonable fix. Have you tested what happens to the app when upgrading from the previous app version with keytar, and already logged in? You can do so by installing the current app version, logging in, and without uninstalling the existing version, installing the build from this PR. I'm hoping that in the worst case, the user simply has to log in again - but hopefully not some sort of 4xx error.

I carried out the best approximation of an upgrade that we can do on both macOS (Apple Siliconj and Windows (64-bit).

Detailed steps taken for both OS:

1. install the official 8.0.1 release.
2. launch the app, log in, ensure the app runs.
3. install the updated app from CircleCI artifacts.
4. launch the app.

In both cases, the upgraded binary continued to work just fine. 
The logged-in status remained and the app appears to be functional.

On macOS, the updated app creates a new keychain items called "WordPressDesktop Safe Stoage", separate from the old "WordPress.com" entry.
