### PR TITLE
Jetpack Connect: pre-flight query

### LINKED ISSUE #15666: Jetpack connect: Connect from site banner fails
When connecting a new Jetpack user to a site via wp-admin banner, connection fails or ends in incoherent state.

### To reproduce
1. You must have a connected Jetpack site.
1. Add and invite a new user to the site via wp-admin.
1. Accept invite and log in the site with this new user. Do not log in using WordPress.com credentials.
1. Ensure you are logged in to WordPress.com with a different user who is _not_ currently connected to the site.
1. Visit the Jetpack Dashboard, you should see a banner nudging you to link. Click "Link to WordPress.com".
   link banner
1. There seem to be two unsatisfactory outcomes.

### What I expected

Follow a Jetpack connection flow and be returned to a site dashboard, either in Calypso or wp-admin.

### What happened

There were two outcomes.

#### Initial attempt

Here, we're immediately presented with a "Return to site" button. Click it and we return to the site without connecting. Note this gif loops, but there are _two_ attempts here. You can see in the second attempt that "Approve" appears.

bad-connect

It seems that some of the state may not be loaded which is causing a "Return to site" button to be shown rather than the desired "Approve" button. 

#### Subsequent attempts

If you do see "Approve" and click it, the site is connected. However the return to a connect form with a "Finishing set up…" notification. What to do, there's not obvious way ouy?

approve-connect

Back at the site, you _are_ connected at this point.

### Observations

There appear to be two main issues.

1. The user is shown a button to return without connecting.
1. If they wait and see the "Approve" button, the user is connected but arrives at a dead end.

Reported by @keoshi here: p1498748549590798-slack-jpop-design

### PR DESCRIPTION
**Pull request by roccotripaldi**
Refactoring the pre-flight query.
We should first check that the site is accesible, then check that the user is connected.

See p7rcWF-th-p2

Fixes #15666

### CODE REVIEW

File: client/state/jetpack-connect/actions.js [hunk 1]
```diff
@@ -316,6 +321,37 @@ export default {
...
+					type: SITE_REQUEST_SUCCESS,
+					siteId
+				} );
+			} )
+			.catch( ( error ) => {
+				dispatch( {
+					type: SITE_REQUEST_FAILURE,
+					siteId,
+					error
+				} );
```
Comment (sirreal) [inline client/state/jetpack-connect/actions.js]: It would be nice to have dedicated action creator functions for `SITE_REQUEST_SUCCESS` and `SITE_REQUEST_FAILURE`, but that doesn't need to happen in this PR.

**Comment by roccotripaldi** [comment]
Thanks for the review @sirreal - i addressed you concerns.
After a bunch of testing, I modified the approach slightly.

File: client/jetpack-connect/auth-logged-in-form.jsx [hunk 2]
```diff
@@ -140,7 +140,7 @@ class LoggedInForm extends Component {
 			? translate( 'Thank you for flying with Jetpack' )
 			: translate( 'Jetpack is finishing up the connection process' );
 		const siteCard = versionCompare( queryObject.jp_version, '4.0.3', '>' )
-			? <SiteCard queryObject={ queryObject } />
+			? <SiteCard queryObject={ queryObject } isAlreadyOnSitesList={ isAlreadyOnSitesList } />
```
Comment (sirreal) [inline client/jetpack-connect/auth-logged-in-form.jsx]: 👍  This should fix the issue I noticed.

File: client/jetpack-connect/auth-logged-in-form.jsx [hunk 3]
```diff
@@ -284,8 +284,11 @@ class LoggedInForm extends Component {
 	}
 
 	renderNotices() {
-		const { authorizeError, queryObject, isAuthorizing, authorizeSuccess } = this.props.jetpackConnectAuthorize;
-		if ( queryObject.already_authorized && ! this.props.isFetchingSites && ! this.props.isAlreadyOnSitesList ) {
+		const { authorizeError, queryObject, isAuthorizing, authorizeSuccess, userAlreadyConnected } = this.props.jetpackConnectAuthorize;
+		if (
+			( queryObject.already_authorized && ! this.props.isFetchingSites && ! this.props.isAlreadyOnSitesList ) ||
+			( userAlreadyConnected )
```
Comment (sirreal) [inline client/jetpack-connect/auth-logged-in-form.jsx]: What's the motivation for this change? Is there a good way to test this?

File: client/jetpack-connect/auth-logged-out-form.jsx [hunk 4]
```diff
@@ -63,12 +63,12 @@ class LoggedOutForm extends Component {
...
 
 	renderFormHeader() {
-		const { translate } = this.props;
+		const { translate, isAlreadyOnSitesList } = this.props;
 		const headerText = translate( 'Create your account' );
 		const subHeaderText = translate( 'You are moments away from connecting your site.' );
 		const { queryObject } = this.props.jetpackConnectAuthorize;
 		const siteCard = versionCompare( queryObject.jp_version, '4.0.3', '>' )
-			? <SiteCard queryObject={ queryObject } />
+			? <SiteCard queryObject={ queryObject } isAlreadyOnSitesList={ isAlreadyOnSitesList } />
```
Comment (sirreal) [inline client/jetpack-connect/auth-logged-out-form.jsx]: 👍 This should fix the issue I noticed.

File: client/jetpack-connect/auth-logged-in-form.jsx (hunk 3 above)
Comment (roccotripaldi) [inline client/jetpack-connect/auth-logged-in-form.jsx]: Yeah. I suppose I'll write some unit tests. And sorry for not writing better testing instructions.
Here is my attempt at putting this into words:

`isAlreadyOnSitesList` is not always going to work. 

In cases where a new user is trying to link to an already connected site, we will issue a request to `sites/$site` and that will come back as 200 even though the current user is not yet linked. It comes back as 200 because `sites/$site` is a public endpoint that will return data for any connected site.

Prior to this patch, upon receiving the 200, we'd add the site to the list, and then we'd disallow the new user from linking because we'd think they were already on the site.

This patch now adds a new redux action, and a new property to state. when we get the 200, we make an additional request to see if the user is actually connected. if so, we update the `userAlreadyConnected` property on the state, and disallow linkage.  if not connected, we allow the linkage, and possible remove the site from sites list.

To test `userAlreadyConnected`, you could connect a site, then try to to link an additional user to the same wpcom account.

You'll likely see the poorly worded notice :)

Comment (sirreal) [inline client/jetpack-connect/auth-logged-in-form.jsx]: Thanks! I get it now. Let me see if this is right:

* You're logged in to WordPress.com as a user who is linked to the site.
* You're logged in to the site, but with an account that _is not_ associated with your currently logged in WordPress.com account.
* You try to link. 💥  see a message

Yeah, this message is terrible:

> This site is already connected to a different WordPress.com user, you need to disconnect that user before you can connect another.

I don't think that really describes the same conditions we're talking about. Do we need a new notification?
