### PR TITLE
Fix handling empty API responses

### LINKED ISSUE #70790: Data Layer: Allow `null` responses from the API
In https://github.com/Automattic/wp-calypso/pull/70480#issuecomment-1329980914, we discovered that the data layer borks on `null` responses from the API.

As it turns out, this is probably a bug! p1670277810543499/1669734008.636179-slack-C7YPUHBB2

We should fix it up 💪

**Done is:**
* The data layer properly handles `null` responses from the API.
* We have tests so we don't run into this issue again (you're welcome to steal https://github.com/Automattic/wp-calypso/pull/70531)

### PR DESCRIPTION
**Pull request by wojtekn**
#### Proposed Changes

In this PR, I propose to add support for empty API responses in the Data Later. The fix was originally introduced in https://github.com/Automattic/wp-calypso/pull/18543 but was missed during further rebase/merges.

#### Testing Instructions

Run tests:

```
yarn run test-client client/state/data-layer/wpcom-http/test/utils.js
```

#### Pre-merge Checklist

- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] ~~Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)~~
- [ ] ~~Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?~~
- [ ] ~~For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?~~

Fixes https://github.com/Automattic/wp-calypso/issues/70790

### CODE REVIEW

File: client/state/data-layer/wpcom-http/test/utils.js [hunk 1]
```diff
@@ -187,6 +200,16 @@ describe( 'WPCOM HTTP Data Layer', () => {
 			expect( dispatch ).toHaveBeenCalledWith( successAction );
 		} );
 
+		test( 'should call onSuccess if meta includes empty string response data', () => {
+			dispatcher( store, successEmptyStringHttpAction );
+			expect( dispatch ).toHaveBeenCalledWith( successEmptyStringAction );
+		} );
+
+		test( 'should call onSuccess if meta includes empty array response data', () => {
```
Comment (wojtekn) [inline client/state/data-layer/wpcom-http/test/utils.js:208]: This case worked already, but I've added a test to explicitly show how we want to handle it.

**Review by dmsnell — APPROVED** [review]
While I did not test this change it looks like it's the right one, and assuming that you tested it, should be good to merge.

There's a chance some code has been built, based upon the truthy-falsey response behavior over the past five years, and that could break. Hopefully that's not the case.

**Comment by danielbachhuber** [comment]
> There's a chance some code has been built, based upon the truthy-falsey response behavior over the past five years, and that could break. Hopefully that's not the case.

@dmsnell The falsy response would produce the request loop, at least.

Any creative ideas for how we might find said code?

**Comment by dmsnell** [comment]
> Any creative ideas for how we might find said code?

Nope, and maybe you're right that they'd already be uncovered by experiencing the bug. Funny thing is that there was such an example of buggy code which led to the original introduction of the fix, but apparently that didn't remain a problem after the fix was inadvertently removed.

My guess is that folks updated their API endpoints to stop sending `null`, which is totally a legitimate value, but also odd given that no response is necessary.
