### PR TITLE
Importer: pre-select author when site has only one author

### LINKED ISSUE #3272: Import: Promise error when trying to start an import
To reproduce:

1. Start an import using data from http://wptest.io/
2. Map authors and click 'start'
3.  The import will begin, and then reset to the state before mapping. A JS error is thown ( see below )

Note: based on the Jabber logs, a job id is never assigned.

screen shot 2016-02-11 at 4 44 41 pm

### PR DESCRIPTION
**Pull request by roccotripaldi**
Issue #3272 was happening because a selected author was only being
saved to the state when chosen via the authorSelect component. Sites
with only one author do not show authorSelect, and in that case, we
need to automatically pre-select the one-and-only author.

Closes #3272 

To test:

1. on master, try to complete an import on a site that has only one author, and note that the error described in #3272 occours
2. checkout this branch
3. try to complete an import again, and celebrate it's completion

cc: @dmsnell

### CODE REVIEW

File: client/my-sites/importer/author-mapping-item.jsx [hunk 1]
```diff
@@ -32,6 +32,15 @@ export default React.createClass( {
 		} ).isRequired
 	},
 
+	componentWillMount() {
+		const { hasSingleAuthor, onSelect } = this.props;
+
+		if ( hasSingleAuthor ) {
+			// Pre-selects the current user for author mapping, if the site only has one user.
```
Comment (dmsnell) [inline client/my-sites/importer/author-mapping-item.jsx]: It seems pretty straightforward without the comment even. We might be just as well leaving it out

**Comment by dmsnell** [comment]
The code looks great @roccotripaldi ! :shipit:

If there were anything to change, it's mentioned in my comment.
