### PR TITLE
composite-checkout: Fix full credits calculation

### LINKED ISSUE #39322: composite-checkout: we show full credits payment method based on total rather than subtotal
The total returned by the shopping cart endpoint can mean different things when different amounts of credits are available.

Currently, the shopping cart response includes `total_cost` (and its display/int conversions) which represents the total amount that the customer must pay after taxes, coupons, discounts, etc. However, this total actually has two variations!

If the user has partial credits (their credit total is lower than the total cost without credits), `total_cost` includes the credits as a discount. The reason for this is that the credits appear in the cart itself as a line item with a negative price that adjusts the total.

If the user has full credits (their credit total is equal to or higher than the total cost without credits), `total_cost` ignores the credits entirely as does the rest of the cart response except for the `credits` property (and its display/int conversions). There is no credits line item in this case, which is why the total is not adjusted to 0, as would be consistent.

The decision to display the full credits payment method is currently based on comparing the amount of credits to the total. This works in a full credits situation; for example, if the user has $100 in credits and the cost of a plan is $70, the `total_cost` is $70, and since 100 > 70 we display the full credits method. 

It is sometimes incorrect for partial credits, though; for example, if the user has $50 in credits and the cost of a plan is $70, the `total_cost` is $20, and since 50 > 20 we display the full credits method. It would be correct if the user only had $5 in credits, since 5 < 65.

This needs to be fixed somehow, and there's various places we could do so. The endpoint response is one, and the client is another; both may be best. See D38606-code for an attempt to fix the endpoint.

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

Currently, the shopping cart response includes `total_cost` which represents the total amount that the customer must pay after taxes, coupons, discounts, etc. 

The decision to display the full credits payment method is currently based on comparing the amount of credits to the total. This works in a full credits situation because of an inconsistent behavior of the endpoint documented more fully in D38606-code.

It is sometimes incorrect for partial credits, though; for example, if the user has $50 in credits and the cost of a plan is $70, the `total_cost` is $20, and since 50 > 20 we display the full credits method. It would be correct if the user only had $5 in credits, since 5 < 65.

This PR adds the `sub_total` property returned by the shopping card endpoint to the data returned by `useShoppingCart` and then uses that value to compare against the credit amount when deciding if we should display the full credits method.

Fixes #39322

#### Testing instructions

- Run calypso with `ENABLE_FEATURES=composite-checkout-wpcom npm start`.
- Sandbox the store.
- Make sure your test account has no credits.
- Add a plan to your cart.
- Visit checkout and verify that the "Credits" method does not appear in the first step.
- Add enough credits to your test account to cover 50% of the plan cost.
- Visit checkout again and verify that the "Credits" method still does not appear in the first step.
- Add enough credits to your test account to cover 100% of the plan cost.
- Visit checkout again and verify that the "Credits" method appears, is the first payment method, and that it is selected by default.
- Complete checkout with the "Credits" payment method and verify that the payment is successful.

### CODE REVIEW

**Comment by sirbrillig** [comment]
Note that this solution is not ideal since the subtotal also doesn’t include taxes. Really we just need to fix the endpoint response and then change how we display the total, but this is less disruptive for the time being and we need to work on taxes anyway.

File: packages/composite-checkout-wpcom/src/lib/translate-cart.ts [hunk 1]
```diff
@@ -52,10 +55,22 @@ export function translateWpcomCartToCheckoutCart( serverCart: ResponseCart ): WP
 		},
 	};
 
+	const subtotalItem: CheckoutCartItem = {
+		id: 'total',
```
Comment (nbloomf) [inline packages/composite-checkout-wpcom/src/lib/translate-cart.ts]: I'm a little confused that `totalItem` and `subtotalItem` have the same id, which probably stems from the inconsistency on the backend about exactly what the subtotal is. I'm not sure what would be a better alternative though. IIUC this is "total cost before partial credits and before taxes".

Comment (sirbrillig) [reply packages/composite-checkout-wpcom/src/lib/translate-cart.ts]: Oops. That was a typo. Thanks!
