### PR TITLE
Remove unnecessary radio button when adding a payment method

### LINKED ISSUE #100556: Remove unnecessary radio button when adding a payment method
### Context and steps to reproduce

When adding a payment method at /me/purchases/add-payment-method we show a single container for adding the card details. This containers has a radio button and selected state which is unnecessary given that there are no other options on this page to choose from.

We should remove the border and radio button if there is only one option displayed on this page.

Image

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Minor

### What other impact(s) does this issue have?

_No response_

### If a workaround is available, please outline it here.

_No response_

### Platform

_No response_

### PR DESCRIPTION
**Pull request by katinthehatsite**
Closes https://github.com/Automattic/wp-calypso/issues/100556

## Proposed Changes

This PR removes the border and the radio button when there is just one payment method that needs to be added. 

Screenshot 2025-04-29 at 11 33 44 AM

## Testing Instructions

* Pull the changes from this branch or use Calypso Live Link
* Navigate to `/me/purchases/add-payment-method`
* Confirm that you can see the form without the radio button (as shown on screenshot)
* Confirm that there is no border and confirm that no border appears on hover

**Test for when there are multiple payment methods*

* Navigate to `/setup/onboarding/domains?source=sites-dashboard` to create a new site
* Select a domain
* Select a paid plan
* Once at the checkout, edit your payment method
* Confirm that the border and the radio button is still present when there are multiple payment method suggestions

Screenshot 2025-04-29 at 11 34 56 AM

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: packages/composite-checkout/src/components/radio-button.tsx [hunk 1]
```diff
@@ -72,12 +83,6 @@ const RadioButtonWrapper = styled.div<
 	${ handleWrapperDisabled };
 `;
 
-interface RadioButtonWrapperProps {
```
Comment (katinthehatsite) [inline packages/composite-checkout/src/components/radio-button.tsx:75]: I just moved these to the top to be right above RadioButtonWrapper so that it is more organized in the code

File: packages/composite-checkout/src/components/radio-button.tsx [hunk 2]
```diff
@@ -14,28 +21,32 @@ const RadioButtonWrapper = styled.div<
...
-		content: '';
-		border: ${ ( props ) => ( props.checked ? '1px solid ' + getBorderColor( props ) : 'none' ) };
-		border-bottom: ${ ( props ) => '1px solid ' + getBorderColor( props ) };
-		box-sizing: border-box;
-		border-radius: ${ ( props ) => ( props.checked ? '3px' : 0 ) };
-		.rtl & {
-			right: 0;
-			left: auto;
+	${ ( props ) =>
+		! props.hideRadioButton &&
```
Comment (katinthehatsite) [inline packages/composite-checkout/src/components/radio-button.tsx:25]: According to this comment https://github.com/Automattic/wp-calypso/issues/99813#issuecomment-2715212052 , it seems that we need to remove the border completely where there is only one payment method. One thing that I was unsure about is whether we should also slightly reduce the padding before the cta button (indicated in red on screenshot). I left it as is for now but happy to adjust:

Screenshot 2025-04-29 at 11 36 08 AM

**Review by gavande1 — APPROVED** [review]
Thanks @katinthehatsite for working on this. I have tested this and everything is woking as expected. 

### Single Payment Method

CleanShot 2025-04-29 at 15 43 07@2x

### Multiple Payment Methods
CleanShot 2025-04-29 at 15 42 50@2x

LGTM 👍

**Comment by gavande1** [comment]
Note: I see there is a lot of space between the border and the actual form. Is there something that we can do it? 

CleanShot 2025-04-29 at 15 48 31@2x

cc @matt-west

**Review by gcsecsey — APPROVED** [review]
These changes LGTM. 👍

I see no border on the branch version on the `/me/purchases/add-payment-method` page, even when hovering:
CleanShot 2025-04-29 at 16 54 03@2x

I can also confirm that the radio button and border are still the same on the branch as on the trunk version on the checkout page, the pages look identical:
CleanShot 2025-04-29 at 16 55 10@2x

**Review by sirbrillig — APPROVED** [review]
I haven't tested but the code looks good to me. Thanks for this clean up!
