### PR TITLE
Ensure user data is actually cleared before logging out

### LINKED ISSUE #11766: Themes: Logging in, then back out gives empty site selector dropdown on attempted activation
Reported by @lancewillett in D4604-code:

#### Steps to reproduce
* Log into Calypso, then log out
* Go to https://wordpress.com/theme/sela
* When the page first loads, you'll see "Pick this design" — but the button changes quickly to "Activate this design"
* Click activate

#### What I expected

The button to be labelled "Pick this design", and clicking it to direct me to signup (with that theme preselected).

#### What happened instead

I got the Themes Site Selector Modal with an empty dropdown of sites.

#### Screenshot / Video

https://cloudup.com/c7-RTG9mqgH

### PR DESCRIPTION
**Pull request by seear**
Fixes #11766

Supply redirect func as a callback to the async localforage call that clears the persisted state. Seems that previously, the redirect was occurring before the persisted data was cleared.

**To Test**
* Sign out of Calypso and check that the `redux-state` item in indexedDB has actually been removed

### CODE REVIEW

File: client/lib/user/user.js [hunk 1]
```diff
@@ -231,7 +236,7 @@ User.prototype.clear = function() {
 	delete this.settings;
 	store.clear();
 	if ( config.isEnabled( 'persist-redux' ) ) {
-		localforage.removeItem( 'redux-state' );
+		localforage.removeItem( 'redux-state', onClear );
```
Comment (gwwar) [inline client/lib/user/user.js]: Good catch, what do we want to do if we're unable to clear state? Probably redirect anyway?

```jsx
localForage.removeItem( 'redux-state' ).then( onClear ).catch( onClear );
```

Comment (gwwar) [inline client/lib/user/user.js]: Ah they're using node style error handling, so the above is perfectly fine.

**Comment by seear** [comment]
@gwwar thanks for the review!
