### PR TITLE
Editor: Media modal: Disable Insert when loading image via URL

### LINKED ISSUE #11831: Editor/Media: Broken image when inserting via URL too quickly
#### Steps to reproduce
1. Starting in the post editor, tap _Add Media_ to bring up the media library
2. Tap _Add via URL_, provide an external image URL
3. Tap _Submit_ so that the loading of the image onto the site starts
4. **Quickly** tap _Insert_ to close the media modal and return to the editor **before** the image has finished loading onto the site

#### What I expected

Either:
- The image I just added via URL would show in my post, even if only after a few seconds
- The _Insert_ button was disabled while the loading completed, preventing me from making this "mistake" of inserting too early

#### What happened instead

An image element gets created in my post but it is missing the `src` tag, thus appearing as a broken image.

#### Browser / OS version

Latest macOS / Chrome.

#### Screenshot / Video

editor-add-from-url

#### Context / Source

#dogfooding #manual-testing

### PR DESCRIPTION
**Pull request by mcsf**
Fixes #11831 

# To test

See parent issue

# Visuals

media-modal-disable-insert

### CODE REVIEW

File: client/post-editor/media-modal/index.jsx [hunk 1]
```diff
@@ -111,7 +111,13 @@ export class EditorMediaModal extends Component {
 	isDisabled() {
 		return some( this.props.mediaLibrarySelectedItems, function( item ) {
 			const mimePrefix = MediaUtils.getMimePrefix( item );
-			return item.transient && ( mimePrefix !== 'image' || ModalViews.GALLERY === this.props.view );
+			return item.transient && (
+				// Transients can't be handled by the editor if they are being
+				// uploaded via an external URL
+				item.is_uploading_via_url ||
```
Comment (mcsf) [inline client/post-editor/media-modal/index.jsx]: I initially thought of merely testing for `typeof item.guid === 'undefined'`, but this felt more explicit: by introducing a new flag, the relationship between these two pieces of the codebase becomes clear with one grep. This would potentially avoid situations where changes to `MediaUtils` suddenly broke `isDisabled`.

**Comment by mcsf** [comment]
One item left here would be tests. I haven't looked yet where the best place for this would be. Any ideas welcome.

File: client/post-editor/media-modal/index.jsx (hunk 1 above)
Comment (aduth) [inline client/post-editor/media-modal/index.jsx]: I dunno, I actually think it's more direct to test for the presence of the value that would actually be used in generating the image. The issue is that we're trying to show an image in the editor, but the `media.URL` is undefined so it appears broken. If we know whether we'd be able to insert anything by checking `media.URL`, we could determine ahead of time whether it wouldn't be a good item to use. The downside I see to this approach is that it may mislead a developer to think this is a real property of the media endpoints response payload.

**Comment by aduth** [comment]
>One item left here would be tests. I haven't looked yet where the best place for this would be. Any ideas welcome.

There's already test files for both the `<MediaModal />` component and Flux media actions. Not sure how much effort would be involved in trying to verify the behavior of `isDisabled` (doesn't seem to be well tested at the moment).

File: client/post-editor/media-modal/index.jsx (hunk 1 above)
Comment (mcsf) [inline client/post-editor/media-modal/index.jsx]: > The downside I see to this approach is that it may mislead a developer to think this is a real property of the media endpoints response payload.

True. Though, for me:

> If we know whether we'd be able to insert anything by checking `media.URL`

this is relying on the implementation of the layer below, in a sense. I'm torn between both approaches, but if I had to choose now I'd keep the current one.

> mislead a developer to think this is a real property

What if we prefix the property with `calypso_`, would that mitigate it?

**Comment by mcsf** [comment]
@aduth, does c487777 make more sense?

**Comment by marekhrabe** [comment]
Looks good to me and testing proves it fixes the original bug! 🚢 

I can see tests on CircleCI failing due to the recent time shifting. I guess rebasing might resolve that.

File: client/post-editor/media-modal/index.jsx [hunk 2]
```diff
@@ -109,24 +121,19 @@ export class EditorMediaModal extends Component {
...
-		}.bind( this ) );
-	}
-
 	confirmSelection = () => {
 		const { view, mediaLibrarySelectedItems } = this.props;
 
-		let value;
-		if ( mediaLibrarySelectedItems.length ) {
-			value = {
+		if ( areMediaActionsDisabled( view, mediaLibrarySelectedItems ) ) {
```
Comment (aduth) [inline client/post-editor/media-modal/index.jsx]: Why did we need to change this behavior? When would `confirmSelection` be called while `areMediaActionsDisabled` is `true` ? Even if it would, is the ideal behavior that the modal not be closed?

Comment (mcsf) [inline client/post-editor/media-modal/index.jsx]: The `disabled` prop was apparently not enough to prevent the Insert action: the button would appear disabled but, on occasion, clicking it would still call `confirmSelection`. As a response, I first tried something like:

```diff
 			buttons.push( {
 				action: 'confirm',
 				label: this.props.labels.confirm || this.props.translate( 'Insert' ),
 				isPrimary: true,
 				disabled: isDisabled || 0 === selectedItems.length,
-				onClick: this.confirmSelection
+				onClick: isDisabled ? undefined : this.confirmSelection
 			} );
```

but in practice the behavior was quite clunky (can't remember the details).
