### PR TITLE
Fix/3rd party cookies disabled notice mobile

### LINKED ISSUE #59022: [Bug]: Google login — 3rd party cookie popover doesn't work on mobile
### Quick summary

On desktop, we show a "3rd party cookies need to be enabled" popover for the Google Login button when hovering the button.

On a mobile browsers hovering isn't possible.  Pressing the disabled button just shows the popover for a split-second, and then it's gone.

Mobile users have no idea why the button stays disabled. 

image

### Steps to reproduce

- Open a new tab on browsers (desktop & mobile) in incognito mode
- Go to https://wordpress.com/start
- Observe the Google login button

### What you expected to happen

Understand on mobile why the button is disabled.

Once we have e.g. inline text on mobile version, we should check if the [docs](https://wordpress.com/support/third-party-cookies/) we link to make sense on mobile as well.

### What actually happened

Nada.

### Context

_No response_

### Browser

Google Chrome/Chromium

### Simple/Atomic

Simple

### Other notes

_No response_

### Reproducibility

Consistent

### Severity

_No response_

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by enejb**
#### Changes proposed in this Pull Request

* Fixes Mobile Tooltip appearance. 
Currently when a user visit Wordpress.com/login in a incognito chrome on android they 
are not able to continue with the google sign in flow. 

This is because the 3rd party cookie are disabled. 
When the user click on the button however they do  not see a reason why. 

This PR intends to fix this. 

Fixes https://github.com/Automattic/wp-calypso/issues/59022

#### Testing instructions

1. Disable 3rd party cookies in your browser. 
2. Logout and navigete to the /log-in page. 
3. Mousing over the `Continue with google - sign in` show the popover message.
4. Mousing out from `Continue with google - sign in` hides the popover message.
5. Clicking the buttons toggles the message.

On mobile. 
1. Clicking the buttons toggles the message as expected.
2. If the popover is shown then clicking outside the button should hide the popover.

What other flows should I be testing here? 

Other flows to try
/start/user 
/start/p2

### CODE REVIEW

**Comment by noahtallen** [comment]
Hey, @enejb, could you rebase this one? It seems like the calypso.live links have expired :)

**Review by noahtallen — APPROVED** [review]
This tests well for me in incognito Chrome. 👍

File: client/components/social-buttons/google.js [hunk 1]
```diff
@@ -140,6 +141,15 @@ class GoogleLoginButton extends Component {
 
 	handleClick( event ) {
 		event.preventDefault();
+		event.stopPropagation();
+
+		if ( this.state.error && this.state.eventTimeStamp !== event.timeStamp ) {
+			this.setState( {
+				showError: ! this.state.showError,
```
Comment (tyxla) [inline client/components/social-buttons/google.js:148]: I know this used to be like that before, but it's worth fixing while we're here: directly relying on state values for calculating the next state can lead to a potentially inconsistent value and subtle bugs. This is because React optimizes for performance and may batch several `setState()` into a single update. 

Fixing this is as easy as replacing the `this.setState()` call to use the callback form:

```
this.setState( ( state ) => ( {
	showError: ! state.showError,
	errorRef: event.currentTarget,
	eventTimeStamp: event.timeStamp,
} ) );
```

You can read more about async state updates here: https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous
