### PR TITLE
Handle press this functionality in the wp-admin editor.

### LINKED ISSUE #58098: Press This not working, launches editor without any content, title, or link
### Quick summary

PressThis is not adding any of the highlighted content into the popup window block editor post. I can reproduce the issue more frequently on simple sites.  However, AT sites are impacted too. 

### Steps to reproduce

1. Open up a simple/AT site.
2. Go to Settings → Writing
3. Drag and drop the "Press This" button below your bookmarks bar.
4. Go to a page on any site.
5. Highlight the text and click on the "Press This" bookmarklet.
6. A popup will appear with a new block editor post and no content added.

### What you expected to happen

- A pop-up with the highlighted text copied into a new post.

### What actually happened

- A pop-up with none of the highlighted text copied over in a new post.

### Context

The issue was brought up in a Slack discussion by @inaikem: 
p1637027688339100-slack-C03TY6J1A

Testing with a simple site:

https://user-images.githubusercontent.com/21261509/141952818-684332c9-80b0-4932-a6cf-2856f973f2b7.mp4

Testing with an AT site:

https://user-images.githubusercontent.com/21261509/141953610-4396f6f1-2c38-4bb1-acdd-d2ac7d62d16f.mp4

### Operating System

Windows, macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

_No response_

### Other notes

- From my own testing, I'm unable to get Press This working correctly on Chrome for both AT and simple sites. 
- On Firefox, Press This is working for one of my AT sites (but not all) and none of my simple sites.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

There is a workaround for AT sites that seems to work sometimes but not all the time. When I tried this on a simple site, I had no luck.

- Add the bookmarklet to the browser again after removing the old one.

### PR DESCRIPTION
**Pull request by roo2**
Fixes https://github.com/Automattic/wp-calypso/issues/58098

In #58098, when some users use the "Press this" bookmarklet, they are first taken to the _Iframed_ calypso editor e.g. `https://wordpress.com/post/$site.wordpress.com?url=foo&title=bar&text=baz`. This _iframed_ editor supports interpreting the query string parameters url, title and text. However, if for some reason the editor fails to load, the user will be taken to the wp-admin version of the editor `https://$site.wordpress.com/wp-admin/post-new.php?url=foo&title=bar&text=baz`.

This PR pulls handling of the press this query parameters into a common function that can be called from the _iframed_ calypso editor, or from the wp-admin editor.

Note: I see that "Press This" also supports the `image` and `embed` url params, but I haven't been able to get these to be passed into the URL by the bookmarklet, I have ported `image` and `embed` to the wp-admin editor with the same implementation as what was used on calypso, but I haven't yet worked out how to test either.

### Testing instructions
Changes are made to the wpcom-block-editor plugin.
Sync these changes to your sandbox with:` cd apps/wpcom-block-editor && yarn dev --sync`
Install and use the "Press This" bookmarklet as described in #58098
Copy the url you are given, replace the pattern `https://wordpress.com/post/$site.wordpress.com` with `https://$site.wordpress.com/wp-admin/post-new.php`, maintain the query string.
This simulates what happens when the calypso iframe fails to load
Ensure that press this content is loaded as expected.

### CODE REVIEW

File: apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js [hunk 1]
```diff
@@ -168,56 +169,7 @@ function handlePressThis( calypsoPort ) {
...
-						value: `<p>${ text }</p>`,
-						citation: link,
-					} )
-				);
-			}
-
-			dispatch( 'core/editor' ).resetEditorBlocks( blocks );
-			dispatch( 'core/editor' ).editPost( { title: title } );
-		} );
+		doPressThis( payload );
```
Comment (mmtr) [inline apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]: Features are not meant to be shared across bundles, because we already have a `default` bundle which does exactly that (provides features to both the iframed editor and the WP Admin editor).

Since we're already adding the feature to the `default` bundle,  we should be able to remove the logic from the `calypso` bundle.

We would need to pass the press this query params (`url`, `title`, `text`, etc) captured by Calypso to the iframe source though:

https://github.com/Automattic/wp-calypso/blob/56c5b5b3892f0d5e429f8377dea75920f422bf4e/client/gutenberg/editor/calypsoify-iframe.tsx#L822

Could be done directly based on the existing `pressThis` prop:

```diff
diff --git a/client/gutenberg/editor/calypsoify-iframe.tsx b/client/gutenberg/editor/calypsoify-iframe.tsx
index 6c78f6083f..b41407f7e7 100644
--- a/client/gutenberg/editor/calypsoify-iframe.tsx
+++ b/client/gutenberg/editor/calypsoify-iframe.tsx
@@ -811,6 +811,7 @@ const mapStateToProps = (
                stripeConnectSuccess,
                anchorFmData,
                showDraftPostModal,
+               pressThis,
        }: Props
 ) => {
        const siteId = getSelectedSiteId( state );
@@ -836,6 +837,7 @@ const mapStateToProps = (
                ...anchorFmData,
                openSidebar: getQueryArg( window.location.href, 'openSidebar' ),
                showDraftPostModal,
+               ...pressThis,
        } );
 
        // needed for loading the editor in SU sessions
```

That would enable us to simplify the overall implementation by removing some chunks of code like [the `pressThis` function](https://github.com/Automattic/wp-calypso/blob/56c5b5b3892f0d5e429f8377dea75920f422bf4e/client/gutenberg/editor/calypsoify-iframe.tsx#L612-L623) or [the `handlePressThis` function](https://github.com/Automattic/wp-calypso/blob/32cced72bbd5d4a7f4569da7c2360f4550534e08/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js#L160-L174).

**Review by mmtr — COMMENTED** [review]
Works great, thanks for adding the logic to `wpcom-block-editor`!

Left some feedback about further simplifying the code, but it's not blocking. It'd be great to also document the new feature in [the `wpcom-block-editor`'s README](https://github.com/Automattic/wp-calypso/tree/trunk/apps/wpcom-block-editor).

File: apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js (hunk 1 above)
Comment (roo2) [reply apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]: Thank you, this worked a treat!

I tested this works, cleaned up the other code, and updated the readme, thanks!

File: apps/wpcom-block-editor/src/default/features/press-this.js [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+
+const { url, title, text, image, embed } = getQueryArgs( window.location.href );
+
+if ( url ) {
+	const unsubscribe = subscribe( () => {
+		// We need to be sure that the editor is initialized and the core blocks
+		// registered. There is an unstable selector for that, so we use
+		// `isCleanNewPost` otherwise which is triggered when everything is
+		// initialized if the post is new.
+		const editorIsReady = select( 'core/editor' ).__unstableIsEditorReady
```
Comment (arthur791004) [inline apps/wpcom-block-editor/src/default/features/press-this.js]: [NIT] We can use [isEditorReady](https://github.com/Automattic/wp-calypso/blob/0ecb6b29ef6241aa938d62ec441e0e7794f5d59f/apps/wpcom-block-editor/src/utils.js#L36) util now!

```js
await isEditorReady();
```

File: client/gutenberg/editor/calypsoify-iframe.tsx [hunk 3]
```diff
@@ -836,6 +821,7 @@ const mapStateToProps = (
 		...anchorFmData,
 		openSidebar: getQueryArg( window.location.href, 'openSidebar' ),
 		showDraftPostModal,
+		...pressThis,
```
Comment (arthur791004) [inline client/gutenberg/editor/calypsoify-iframe.tsx]: [NIT] Prefer to rename to `pressThisData` as `pressThis` looks like a function and doing spreading is a bit weird 😅

**Review by arthur791004 — APPROVED** [review]
Nice job 👍

**Review by mmtr — APPROVED** [review]
Thanks for the latest changes, still works great! 🚀

File: apps/wpcom-block-editor/src/default/features/press-this.js (hunk 2 above)
Comment (roo2) [reply apps/wpcom-block-editor/src/default/features/press-this.js]: nice that is better 👍

File: client/gutenberg/editor/calypsoify-iframe.tsx (hunk 3 above)
Comment (roo2) [reply client/gutenberg/editor/calypsoify-iframe.tsx]: good point
