### PR TITLE
Login: Back link broken

### LINKED ISSUE #15349: Login: Back link broken
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/log-in/es?redirect_to=https%3A%2F%2Fwordpress.com%2F
2. Click the Back to WordPress.com link in the footer

#### What I expected
To go back to the home page

#### What happened instead
The footer went weird

#### Environment
Doesn't happen in development

#### Screenshot / Video
https://cloudup.com/cg8sl6h78rv

### PR DESCRIPTION
**Pull request by pento**
This pull request fixes #15349 by breaking routing if a logged out user tries to visit /.

#### Testing instructions

I haven't found a good way of testing this in dev, this is the least hacky way. 🙃

1. Run `git checkout fix/15349-reboot-logged-out-home-visit`
2. In `login-links.jsx`, change the "Back to WordPress.com" `href` to `http://calypso.localhost:3000/`
3. Start your server in the `production` environment: `CALYPSO_ENV=production npm start`
2. Open the [`Log In` page](http://calypso.localhost:3000/log-in)
3. Click the "Back to WordPress.com" link.

The result is that you'll be redirected to https://wordpress.com/wp-login.php, but if you check your network activity, you should see that you went to http://calypso.localhost:3000/, first.

#### Reviews

- [x] Code

### CODE REVIEW

File: client/boot/common.js [hunk 1]
```diff
@@ -87,6 +87,12 @@ const loggedOutMiddleware = currentUser => {
 				page.redirect( '/devdocs/start' );
 			}
 		} );
+	} else {
+		// Break routing if the user is logged out, and tries to visit /
+		page( '/', () => {
+			window.location.href = '/';
+			return;
```
Comment (stephanethomas) [inline client/boot/common.js]: It looks like `return` shouldn't be needed here, or should be after the `page()` call.

**Comment by stephanethomas** [comment]
We use Page.js to handle routing client-side. This client-side routing takes precedence over server-side routing once the app has loaded. Looking at the documentation, this means that links will be managed by Page.js in most circumstances, except the ones described [here](https://github.com/visionmedia/page.js/#pagepath-callback-callback-):

> Under certain conditions, links will be disregarded and will not be dispatched, such as:
>
> * Links that are not of the same origin
> * Links with the download attribute
> * Links with the target attribute
> * Links with the `rel="external"` attribute

Our problem only happens in production because in this environment the link points to the same origin, i.e. `wordpress.com`. Instead of modifying `boot` with a change that has a very large scope, I'd like to suggest to simply take advantage of the `rel="external"` attribute to bypass Page.js on that specific link. I've added a commit to show that alternative, let me know what you think of it.

**Comment by pento** [comment]
Oh, this is way better. Thanks, @stephanethomas!
