### PR TITLE
Reader: fix Discover site attribution icon

### LINKED ISSUE #19798: Discover attribution uses a WordPress logo instead of the site icon in some cases.
Some Discover picks show a default WordPress logo instead of the corresponding site's icon. 

---

**Expected Behavior**
The attribution line on a full-post view should display the site icon. This happens correctly for many sites:

screen shot 2017-11-15 at 8 38 50 am

---

**Actual Behavior**
One some posts however, we're pulling in a default WordPress logo instead.

screen shot 2017-11-15 at 8 34 54 am

This happens even if the site has an icon that appears in other areas of the Reader:

screen shot 2017-11-15 at 8 41 55 am

---

**Steps to Reproduce**

Visit the full post view of a Discover post with the issue. Scroll down below the post body to see the attribution line. Example posts: 

- http://calypso.localhost:3000/read/blogs/53424024/posts/30360
- http://calypso.localhost:3000/read/blogs/53424024/posts/29663
- http://calypso.localhost:3000/read/blogs/53424024/posts/29632

---

cc @jancavan, who [noticed this issue](https://github.com/Automattic/wp-calypso/pull/19778#issuecomment-344473584) over at PR #19778

### PR DESCRIPTION
**Pull request by bluefuton**
Fixes #19798, in which @kjellr notes that we are displaying a default WordPress site icon for the Discover attribution line in full post, even in cases where we appear to have the right site icon elsewhere in Reader.

32838828-41099eb0-c9e0-11e7-9196-fd820b759ad0

This PR introduces two changes:
- discard the default avatar if is provided by the API
- fallback to the site icon if we don't have an avatar

The resulting selection order for site avatars is:

1. Discover attribution avatar URL (unless it's the default avatar)
2. Site icon
3. Globe gridicon

### To test

Here's a post with an attribution avatar (should display as before):

http://calypso.localhost:3000/read/blogs/53424024/posts/30475

screen shot 2017-11-24 at 15 08 18

Here are two posts with a site icon used as fallback:

http://calypso.localhost:3000/read/blogs/53424024/posts/30360
http://calypso.localhost:3000/read/blogs/53424024/posts/29663

screen shot 2017-11-24 at 15 09 06

And finally, here's a post with neither an attribution avatar nor a site icon:

http://calypso.localhost:3000/read/blogs/53424024/posts/29632

screen shot 2017-11-24 at 15 09 45

### CODE REVIEW

File: client/blocks/site-icon/index.jsx [hunk 1]
```diff
@@ -27,6 +27,7 @@ function SiteIcon( { siteId, site, iconUrl, size, imgSize, isTransientIcon } ) {
 	const classes = classNames( 'site-icon', {
 		'is-blank': ! iconSrc,
 		'is-transient': isTransientIcon,
+		'has-icon': !! iconSrc,
```
Comment (bluefuton) [inline client/blocks/site-icon/index.jsx]: I reckon we need both this and `is-blank` because we want to apply a background colour in all cases _except_ when there's an icon.

File: client/reader/discover/site-attribution.jsx [hunk 2]
```diff
@@ -14,63 +16,75 @@ import { translate } from 'i18n-calypso';
...
+		const attribution = get( post, 'discover_metadata.attribution' );
+		const siteUrl = getSiteUrl( post );
+		const followUrl = getSourceFollowUrl( post );
+		const { blogId: siteId } = getSourceData( post );
+		const siteLinkProps = getLinkProps( siteUrl );
 		const siteClasses = classNames( 'discover-attribution__blog ignore-click' );
 
+		let avatarUrl = attribution.avatar_url;
+		// Drop default avatar
+		if ( path.basename( avatarUrl ) === 'defaultavatar.png' ) {
```
Comment (samouri) [inline client/reader/discover/site-attribution.jsx]: is this the same thing as `_.endsWith`?

File: client/reader/discover/site-attribution.jsx [hunk 3]
```diff
@@ -14,63 +16,75 @@ import { translate } from 'i18n-calypso';
...
 						className="gravatar"
 						src={ encodeURI( attribution.avatar_url ) }
 						alt="Avatar"
 						width="20"
 						height="20"
 					/>
-				) : (
-					<Gridicon icon="globe" size={ 18 } />
 				) }
+				{ ! avatarUrl && siteId && <QueryReaderSite siteId={ siteId } /> }
```
Comment (samouri) [inline client/reader/discover/site-attribution.jsx]: should we also hide the `QueryReaderSite` in the case that the site is already loaded?
i.e.
`! avatarUrl && siteId && ! site && ...`

**Comment by samouri** [comment]
is the globe actually just a SiteIcon without a site?

**Comment by samouri** [comment]
functionally this is looking like its pretty good at picking the right image! Nice updates @bluefuton 🎉 .

I'm seeing the icons misaligned in both FF Quantum and Chrome:

example1:
screen shot 2017-11-24 at 11 32 55 am

example2:
screen shot 2017-11-24 at 11 32 24 am

File: client/reader/discover/site-attribution.jsx (hunk 2 above)
Comment (bluefuton) [reply client/reader/discover/site-attribution.jsx]: Yes! I've just done some benchmarking and `endsWith` is _much_ faster. I'll swap it.

https://codesandbox.io/s/422967z0m9

**Comment by bluefuton** [comment]
> is the globe actually just a SiteIcon without a site?

Yep! The `SiteIcon` component uses it as a fallback.

**Comment by kjellr** [comment]
Glad to see these icons showing up! I tested, and the only bugs I noticed are those alignment bugs that @samouri noted. Thanks @bluefuton!

**Comment by bluefuton** [comment]
Sorry folks, the rendering issues were caused by a misnamed class 🤦‍♂️ 

All fixed now, and converted to Flexbox for good measure.

File: client/reader/discover/style.scss [hunk 4]
```diff
@@ -46,21 +47,24 @@
...
 	}
 
-	.gridicons-globe {
-		vertical-align: text-bottom;
-		background-color: lighten( $gray, 20% );
-		color: $white;
+	.site-icon {
 		margin-right: 6px;
+		background: lighten( $gray, 20% );
+		.gridicon {
```
Comment (jancavan) [inline client/reader/discover/style.scss]: Nitpick: I would add a space before `.gridicon`. Looks good otherwise.

Comment (bluefuton) [reply client/reader/discover/style.scss]: Thanks @jancavan. I've added a new line, and also removed some old gridicon arrow styles we no longer use.

**Comment by samouri** [comment]
giving this another round of testing

**Comment by jancavan** [comment]
I think `flex` becomes an issue if the site name is long. However, I think that might be an edge case. I'll fix separately.

screenshot 2017-11-27 10 37 12

**Comment by jancavan** [comment]
Fixed https://github.com/Automattic/wp-calypso/pull/20202#issuecomment-347281430 in: https://github.com/Automattic/wp-calypso/pull/20202/commits/fa6b915ecea917556c59fd08d1f7f45f85404e98

screenshot 2017-11-27 11 39 48

Mobile:
screenshot 2017-11-27 11 39 55

**Comment by samouri** [comment]
@jancavan: i'm now seeing the follow button right-aligned even for short titles:
screen shot 2017-11-27 at 11 51 22 am

**Comment by jancavan** [comment]
> i'm now seeing the follow button right-aligned even for short titles:

Fixed in: https://github.com/Automattic/wp-calypso/pull/20202/commits/7c4165115a6971bdae8c02a9ba5db6ef31a7e205

I don't think we can make long-content-fade work here, but that's ok since I don't think extra long site names are too common.

**Comment by samouri** [comment]
giving this one more round of testing and if it looks good I'll 🚢
