### PR TITLE
Components & DevDocs: dont make the `altText` a required prop for PaymentLogo

### LINKED ISSUE #24775: DevDocs: not all supported types of PaymentLogo are documented
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/devdocs/design/payment-logo
2. In **Required Props** section, the document says there are currently 5 possible values for the `type` prop: `amex`, `discover`, `mastercard`, `paypal`, `visa`.

#### What I expected

 I expected all those possible values are documented.
There are at least 13 possible values for `type`.

#### What happened instead

The document says there are only 5 possible values for the `type` prop, which is apparently not true.

#### Context / Source

According to the variables `$payment-cc-brands` and `$payment-types` in `client/components/payment-logo/style.scss`, I believe there are at least 12 possible values for `type`.

I also found that in `client/extensions/woocommerce/woocommerce-services/views/label-settings/label-payment-method.js`, PaymentLogo is invoked with the `type` prop being `placeholder`. That makes `placeholder` the 13th possible value.

I've tried to document all the possible values of `type` in PR #24769 , but I'm not sure about the `placeholder` type. It seems like a special case to me. I would really like to know what this `placeholder` type means and when to use it.

### PR DESCRIPTION
**Pull request by jsliang**
When visiting the README of PaymentLogo (http://calypso.localhost:3000/devdocs/design/payment-logo), I saw the following warning in dev console:

```
index.jsx:101 Warning: Failed prop type: The prop `altText` is marked as required in `PaymentLogo`, but its value is `undefined`.
    in PaymentLogo (created by PaymentLogo)
    in PaymentLogo (created by DesignAssets)
    in span (created by DocsExampleWrapper)
    in div (created by DocsExampleWrapper)
    in div (created by DocsExampleWrapper)
    in DocsExampleWrapper (created by Collection)
    in div (created by Collection)
    in div (created by LazilyRender)
    in LazilyRender (created by Collection)
    in div (created by Collection)
    in Collection (created by DesignAssets)
    in main (created by Main)
    in Main (created by DesignAssets)
    in DesignAssets (created by AsyncLoad)
    in AsyncLoad (created by DevdocsAsyncLoad)
    in DevdocsAsyncLoad
    in div (created by Layout)
    in div (created by Layout)
    in div (created by Layout)
    in Layout (created by Connect(Layout))
    in Connect(Layout) (created by ReduxWrappedLayout)
    in Provider (created by ReduxWrappedLayout)
    in ReduxWrappedLayout
```

I searched through the whole repository and found that most of the usages of `PaymentLogo` do not pass anything to the `altText` prop. Since the possible values of the `type` prop are limited (according to the README of `PaymentLogo`), I think it makes sense to infer `PaymentLogo`'s `altText` from its `type` when `altText` is not given. We can achieve this by maintaining a mapping from `type` to `altText`. 

In addition, I found that the possible values of `type` in `PaymentLogo` are far more than those documented on README when I looked into `PaymentLogo`'s `style.scss`. I've updated README and examples accordingly.

Fixes #24775.

### CODE REVIEW

**Comment by designsimply** [comment]
Tested and confirmed I can see the "failed prop type" warning in the console ([screenshot](https://user-images.githubusercontent.com/1119271/39896120-215d5e2a-546a-11e8-9e05-9e41a2805d56.png)).

**Comment by designsimply** [comment]
I tested `try/paymentlogo-dont-require-alttext` and confirmed the "failed prop type" warning no longer appears in the console when loading http://calypso.localhost:3000/devdocs/design/payment-logo

We still need a code review too. 🙂

File: client/components/payment-logo/index.jsx [hunk 1]
```diff
@@ -7,20 +7,43 @@
...
+		altText: PropTypes.string,
 		isCompact: PropTypes.bool,
 	};
 
 	render() {
-		const classes = classNames( 'payment-logo', `is-${ this.props.type }`, {
-			'is-compact': this.props.isCompact,
+		const { altText, isCompact, type } = this.props;
+
+		const classes = classNames( 'payment-logo', `is-${ type }`, {
```
Comment (jsnmoon) [inline client/components/payment-logo/index.jsx]: It might be nice to add support for adding in `this.props.className` here. We'd probably want to add `className` to our `propTypes` if we do, though.

File: client/components/payment-logo/index.jsx [hunk 2]
```diff
@@ -7,20 +7,43 @@
...
+			'is-compact': isCompact,
 		} );
 
-		return <div className={ classes } aria-label={ this.props.altText } />;
+		return <div className={ classes } aria-label={ altText || ALT_TEXT[ type ] || '' } />;
```
Comment (jsnmoon) [inline client/components/payment-logo/index.jsx]: We could add property propagation here by inserting `{ ...this.props }` before `className` here. Doing so will allow consumers of this component to pass down whatever properties they'd like to the `div` element.

File: client/components/payment-logo/index.jsx (hunk 1 above)
Comment (jsliang) [reply client/components/payment-logo/index.jsx]: Thank you! Added in commit 0d4661373e7d40298a1c5adde062cc1cf25421c2 as suggested 😄

File: client/components/payment-logo/index.jsx (hunk 2 above)
Comment (jsliang) [reply client/components/payment-logo/index.jsx]: Hi @jsnmoon ,  I'm a little concerned about the use of `{ ...this.props }`. I'd rather specify a finite list of props that can be consumed by PaymentLogo for ease of maintenance. If consumers pass down props that are not documented, would that causes hassles if we want to refactor this component at some time in the future?

File: client/components/payment-logo/docs/example.jsx [hunk 3]
```diff
@@ -17,9 +17,12 @@ class PaymentLogoExamples extends React.PureComponent {
...
 			<div>
-				<PaymentLogo type="amex" /> <PaymentLogo type="discover" /> {' '}
-				<PaymentLogo type="mastercard" /> <PaymentLogo type="visa" /> {' '}
-				<PaymentLogo type="paypal" isCompact /> <PaymentLogo type="paypal" />
+				<PaymentLogo type="alipay" /> <PaymentLogo type="amex" /> <PaymentLogo type="bancontact" />{' '}
+				<PaymentLogo type="diners" /> <PaymentLogo type="discover" /> <PaymentLogo type="eps" />{' '}
+				<PaymentLogo type="giropay" /> <PaymentLogo type="ideal" /> <PaymentLogo type="jcb" />{' '}
+				<PaymentLogo type="mastercard" /> <PaymentLogo type="p24" /> <PaymentLogo type="paypal" />
+				<PaymentLogo type="paypal" isCompact /> <PaymentLogo type="unionpay" />{' '}
+				<PaymentLogo type="visa" />
```
[the remark this answers is not in the document]
Comment (jsliang) [reply client/components/payment-logo/docs/example.jsx]: Thank you @jsnmoon . I've redone this part with array maps as you suggested. I've also moved out the special case: `type="placeholder"` to another paragraph.

For right margins, my intuition was to use add a CSS class for this `payment-logo/docs/example.jsx` that append margins to each `<PaymentLogo />`. However, I failed to find any example that introduces any new CSS classes just for documentation purpose. I guess that it's not encouraged?

To workaround, I wrapped each `<PaymentLogo />`  with a `<div>` so that they are displayed in different lines.

[the remark this answers is not in the document]
Comment (jsnmoon) [reply client/components/payment-logo/docs/example.jsx]: > For right margins, my intuition was to use add a CSS class for this `payment-logo/docs/example.jsx` that append margins to each `<PaymentLogo />`. However, I failed to find any example that introduces new CSS classes just for documentation purpose. I guess that it's not encouraged?

Unfortunately, I don't think we currently have a good way of supporting this yet.

> To workaround, I wrapped each `<PaymentLogo />`  with a `<div>` so that they are displayed in different lines.

Well done! 👍

File: client/components/payment-logo/index.jsx (hunk 2 above)
Comment (jsnmoon) [reply client/components/payment-logo/index.jsx]: I think your point is a valid concern. 

Given that the component already handle most use-cases that may involve property propagation (e.g. setting alt text or class name), I think your call to exclude `{ ...this.props }` is the right one to make.

File: client/components/payment-logo/docs/example.jsx [hunk 4]
```diff
@@ -5,21 +5,45 @@
  */
 
 import React from 'react';
+import concat from 'lodash/fp/concat';
```
Comment (bluefuton) [inline client/components/payment-logo/docs/example.jsx]: To shorten this, we could do:

`import { concat, filter, flow, map, sortBy } from 'lodash';`

:)

Comment (jsliang) [reply client/components/payment-logo/docs/example.jsx]: Hi @bluefuton, I’m importing with this verbosity here is because I need auto-curried iteratee-first data-last methods (those provided by `lodash/fp`) to pass into `flow`. And to use `lodash/fp`, it seems to me that we have to import each method line by line. `import { concat, filter, flow, map, sortBy } from 'lodash/fp';` is not valid.

**Comment by jsnmoon** [comment]
Looks good to me! Squash merging now.

**Comment by jsnmoon** [comment]
This is now live in production. Well done, @jsliang!
