### PR TITLE
Pages: Show site icon and title in all sites mode

### LINKED ISSUE #16888: Pages: When viewing All My Sites, pages do not show site icon or url
#### Steps to reproduce
1. Starting at URL: `/pages/published`

#### What I expected

To see a the site icon and url for each post in the list

#### What happened instead

The site icon and url for each post was not shown

#### Context / Source

This is due to the strict equality check used here:

https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/pages/page-list.jsx#L295

```
<Page key={ 'page-' + page.global_ID } page={ page } multisite={ this.props.siteId === false } />
```

#dogfooding

### PR DESCRIPTION
**Pull request by jonathansadowski**
Fixes #16888 

This PR fixes an issue where when viewing Pages with "All My Sites" selected in the site-selector, the site icons and domain were not visible.

To test:
* Checkout branch, `npm start`
* Visit http://calypso.localhost:3000/pages using an account with multiple sites.
* Verify that the site icons and domains are now visible for your pages.

### CODE REVIEW

File: client/my-sites/pages/page-list.jsx [hunk 1]
```diff
@@ -292,7 +292,7 @@ const Pages = localize( React.createClass( {
 
 			// Render each page
 			return (
-				<Page key={ 'page-' + page.global_ID } page={ page } multisite={ this.props.siteId === false } />
+				<Page key={ 'page-' + page.global_ID } page={ page } multisite={ ! this.props.siteId } />
```
Comment (mcsf) [inline client/my-sites/pages/page-list.jsx]: Wouldn't `=== null` be more appropriate?

**Comment by jonathansadowski** [comment]
Thanks for the review / suggestion. I've updated the check.
