### PR TITLE
Cart: Round Price to Appropriate Decimal Point

### LINKED ISSUE #55119: Empathy Testing: Popover cart price is not rounded off.
### Steps to reproduce the behavior

1. Go to Upgrades > Domains
2. Add a new domain to the site
2. Select a discounted domain such as `.blog` which has a discounted price of $9.90
3. You will notice that the domain price is not rounded off properly in the popover cart

#### What I expected to happen

The domain price in the popover cart should be the same as the listed price.

#### What actually happened

The price was not rounded off properly

#### Is this specific to the applied theme? Which one?
No

#### Does this happen on simple or atomic sites or both?
Both

#### Is there any console output or error text?
No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

 Affects all sites

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

image

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

* Rounds the price to an appropriate decimal point in the Cart popover

#### Testing instructions

Add the discounted `.blog` domain to your cart, and verify that the price displays appropriately. If you change your currency to one which rounds to a different number of decimal points (Bahraini Dinar rounds to three), that should be reflected here too.

**Before:**
Screenshot 2021-08-03 at 11 40 11

**After:**
Screenshot 2021-08-03 at 11 39 52

cc @sirbrillig

Fixes #55119

### CODE REVIEW

**Comment by sirbrillig** [comment]
Nice fix! These components have pretty much been abandoned as we've replaced checkout, and there's definitely known issues with some of them. We have a plan (but no timeline) to replace the popover cart with a masterbar cart that uses new checkout components instead (see https://github.com/Automattic/wp-calypso/pull/52890). In the meantime, it's good to fix large issues like this one, so thank you.

File: client/my-sites/checkout/cart/cart-item.jsx [hunk 1]
```diff
@@ -61,7 +61,8 @@ export class CartItem extends React.Component {
 			return this.getDomainPlanPrice( cartItem );
 		}
 
-		const cost = cartItem.cost * cartItem.volume;
+		const unformattedCost = cartItem.cost * cartItem.volume;
+		const cost = unformattedCost.toFixed( getCurrencyDefaults( cartItem.currency ).precision );
```
Comment (sirbrillig) [inline client/my-sites/checkout/cart/cart-item.jsx]: That's weird. The unit tests for this component are failing with `TypeError: (0 , _formatCurrency.getCurrencyDefaults) is not a function`, but I see that function exported by the package and used in other places. 🤔  

It sounds to me like something wrong with the test. However! I was thinking, there's really no need for this calculation at all. We can do things like [new checkout does them](https://github.com/Automattic/wp-calypso/blob/0799ab42a1d41122373468cbd33d6dda20be5291/client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx#L884), and use `cartItem.item_subtotal_display` which should include the pre-calculated, localized price with its currency symbol.

Comment (Aurorum) [reply client/my-sites/checkout/cart/cart-item.jsx]: Sure thing, done! :) 

Screenshot 2021-08-04 at 12 12 48

**Review by sirbrillig — APPROVED** [review]
This looks great to me! Thank you!
