### PR TITLE
FSE: Fix back navigation from template part editor

### LINKED ISSUE #34864: Full Site Editing: close button not navigating back on Simple sites [3]
While editing header and footer on Dotcom simple sites, after click the close button the browser URL is updated correctly (to the post ID passed in `fse_parent_post` parameter), but the action for navigating to that page is no longer working.

I'm certain that this was working after I deployed the latest sync patches for FSE, Gutenframe, and Modern Business - on Monday and Tuesday (7/22 and 7/23), and I tested this flow quite a few times. However, it's no longer working for me - not sure what change might have caused this since we haven't deployed any FSE related changes since that time.

### PR DESCRIPTION
**Pull request by noahtallen**
We were having a lot of trouble getting `navigate` to work correctly between different gutenberg editor instances. As a result, we decided to do the navigation server side. Previously, Miguel enabled server navigation for opening the template part editor #34766. This PR also enables server back navigation specifically for navigating back from the template part post type. There was another attempt at fixing this in #34738, but my guess is that switching to the server side nav to get into a template part somehow messed something up with navigating back from template parts.

Here's a really interesting find. If we get rid of this entire PR, we could also fix this bug by doing this instead: 

```js
// This:
this.props.navigate( `${ window.location.origin }${this.props.closeUrl}` );

// Instead of:
this.props.navigate( this.props.closeUrl );
```

However, this brings back the bug where you get two unsaved changes prompts. I think @mmtr did a lot of work on that and ended up having to switch to a server side approach, so it makes sense to stick with the current approach, I think, unless we find something that fixes all this in one fell swoop.

**Navigation working in this PR:**

**Navigation not working without this PR:**

### Changes proposed in this Pull Request
- Updates the closeUrl in the calypsoifyGutenberg global object with the correct closeUrl from the client. I initially did this for a different possible solution for this. It's not needed for this PR per se, but I still think it's good to keep this URL in sync, since it is used by some other things in the bridge server.
- Update the close button override. Before, we just sent a message to the client to tell it to navigate. We still do that, but now the client decides if it wants to send a message back to the server, which tells the server to do the navigation instead. We wait until the client sends a message back to us so that the "Unsaved Changes" state stuff can update correctly. (I.e. the functions which update that are called before we send the message back to the server triggering the navigation.)

### Testing Prereqs
1. Have the calypso setup running.
2. Have the iframe bridge server setup running. You can see the steps for doing that here: PCYsg-l4k-p2. I personally synced the build to my sandbox with unison.
3. Sandbox `widgets.wp.com` so that it hits off your sandbox for the iframe server code.
4. Make sure your sandbox is running :)
5. Make sure that your sandbox has FSE enabled: PCYsg-ly5-p2 ("Activating the plugin on WordPress.com").
6. Sync the build of FSE to your sandbox from this branch, just to make sure everything is consistent.
7. Make sure you have FSE and the modern business theme active on your sandbox site. (i.e. go into the page editor and double check that template parts are visible) 

Now that you have a bajillion terminals open,
### Testing
1. Go to `http://calypso.localhost:3000/pages/{your-sandbox-site}`
2. Open one of your pages. _Make sure you can see the template parts_
3. Click on a template part. _Make sure that it takes you to the template part editor_
4. In the template part editor, everything should look normal. Nothing to see here :)
5. Click the back button in the template part editor. **Make sure it navigates back to the page editor you were looking at before you went into the post. This is the goal of the PR**
6. Once in the page editor again, click the back button again and make sure it takes you back to the all pages view.
6. Try steps 1-6 again with a different page, just to be sure nothing weird happens in between.
7. Go to `http://calypso.localhost:3000/posts/{your-sandbox-site}` and open one of your posts.
8. Make sure that the back button from the post editor takes you back to the all posts view. 
9. Finally, go back into the template part editor (via the page editor) again.
10. Make some changes to the template part without saving.
11. Click the back button. You should get a single prompt telling informing you of unsaved changes. You should **not** get two prompts.
12. If you click "leave", it should go back to the previous page.
13. If you click "cancel", it should stay on the template part editor.

Fixes #34864

### CODE REVIEW

File: client/gutenberg/editor/calypsoify-iframe.tsx [hunk 1]
```diff
@@ -60,7 +60,7 @@ interface Props {
 	postType: T.PostType;
 	pressThis: any;
 	siteAdminUrl: T.URL | null;
-	fseParentPostId: T.PostId;
+	fseParentPageId: T.PostId;
```
Comment (noahtallen) [inline client/gutenberg/editor/calypsoify-iframe.tsx]: Note: this was just a typo I fixed to get my type errors to go away.
