### PR TITLE
Plugin List: Set the title corretly on mobile

### LINKED ISSUE #441: Jetpack Plugins: page title incorrect on mobile
When navigating to the single plugin view and then back to the list of plugins, you sometimes end up with the wrong page title showing. I might not being reset/cleared properly on some navigation routes.

Steps to reproduce:
1. Go to My Sites
2. Choose a Jetpack site
3. Go to Plugins
screen shot 2015-11-22 at 3 27 41 pm
4. Click on a specific plugin
screen shot 2015-11-22 at 3 28 01 pm
5. Click 'Back', see that the page title displayed is incorrect. It says 'Akismet Plugin' instead of 'Plugins'
screen shot 2015-11-22 at 3 28 15 pm

### PR DESCRIPTION
**Pull request by enejb**
Fixes #441 See https://cloudup.com/cOuGNFudhPW

This fix works because on the single plugin view we update the page title after a page finished loading. 
This just makes sure that the page title gets overwritten when the user is on the plugin list page. On a tick after the plugin list gets shown. Which then in turn overwrites the page title correctly again. 

To test make sure that the page title displays correctly when navigatin in mobile view between a single plugin view and the list plugin view. 
cc: @johnHackworth

### CODE REVIEW

**Comment by johnHackworth** [comment]
hmm, this works great, but I'm not very sure about the setTimeout solution... it feels that we are patching a bigger architecture problem with that instead of fixing the root cause :/

After playing  a little with the code, I've found a way of avoiding that setTimeout: The `componentWillUnmount` method of the main plugin single view component will clear the timeout used to refresh the title. That avoids overwritting it with outdated data. We probably should be doing this with any timeout we use inside a component anyway! I've added a commit that pretty much changes 100% the way this work... so if you feel there's any problem with my approach (or if doesn't feel right), please, revert it without any remorse! :)

**Comment by enejb** [comment]
I haven't tried this yet but I like your solution much better already :heart:

**Comment by artpi** [comment]
@enejb, @johnHackworth : I will remove `Needs Review` label for now ok?
As I understand, this review is outdated and either needs more work or Javi's solution changed a lot?
So, feel free to add it again if I'm mistaken

**Comment by johnHackworth** [comment]
In fact it really needs review... @enejb  started this and I hijacked his PR and rewrite most of it, so pretty much it's done, but waiting for someone (possibly @enejb, since he was the one starting everything ) reviewing it :)

**Comment by artpi** [comment]
Ah, I'm sorry @johnHackworth, I understood that you were working in a different PR :)

**Comment by johnHackworth** [comment]
I would say that this need someone other than  @enejb or me to review it... @roccotripaldi @lezama

File: client/my-sites/plugins/plugin.jsx [hunk 1]
```diff
@@ -113,9 +116,8 @@ export default React.createClass( {
 
 	refreshSitesAndPlugins( nextProps ) {
 		this.setState( this.getSitesPlugin( nextProps ) );
-
 		// setTimeout to avoid React dispatch conflicts.
-		setTimeout( () => {
+		this.pluginRefreshTimeout = setTimeout( () => {
```
Comment (lezama) [inline client/my-sites/plugins/plugin.jsx]: `setTitle` has its own `setTimeout`: https://github.com/Automattic/wp-calypso/blob/a7478174b0441760c332fcb4b8c454f5b8d73dfc/shared/lib/screen-title/actions.js#L16, do we know why that one isn't enough?

Comment (johnHackworth) [inline client/my-sites/plugins/plugin.jsx]: The problem is due that timeout, the title change code is being executed even if this component has been unmounted already ... that's why this component was overwriting the title even if this component was already dead.
With this second internal timeout, we can clear it and not launch the title edit code when the component is unmounted, avoiding nasty side effects! :)

Comment (lezama) [inline client/my-sites/plugins/plugin.jsx]: Hmmm...that makes sense, thanks for the clear explanation :)

I have another question :p, can't we set the title at the controller? 
I think it could be useful for future cases if we return the `timeoutID` in https://github.com/Automattic/wp-calypso/blob/a7478174b0441760c332fcb4b8c454f5b8d73dfc/shared/lib/screen-title/actions.js#L16 and clear that one instead of creating a new one.

Comment (enejb) [inline client/my-sites/plugins/plugin.jsx]: The reason why we can't set the timeout in the controller is because we load the data about the plugin in the plugin component. So we are not passing the controller any more after we get the data. We end up with the slug instead of the name in the title.

**Comment by enejb** [comment]
@lezama can you take another look. I added code that prevents the page title from update multiple times as well as makes sure that the page title updates when needed. @johnHackworth changes make much more sense. Since the setTimeout was causing the update to happen to many times. Removing it on page unmount solved this issue.

**Comment by lezama** [comment]
LGTM :+1:
