### PR TITLE
Checkout: Disable coupon form if coupon field is empty

### LINKED ISSUE #3799: Checkout: Missing validation for coupon code
#### Steps to reproduce
1. Proceed to checkout
2. Input any (or even none) coupon code
3. Hit `Apply`
#### What I expected

Not allowing the submission of empty coupon code (disabled `Apply` button, validation error on the input field, stuff like that).
Not allowing the submission of an invalid coupon code (_if_ there is a common format for them).
#### What happened instead

The form instantly submitted, but returned an error in a `Notice` after a considerable delay.

### PR DESCRIPTION
**Pull request by Copons**
Fix #3799

Disable the coupon form if the coupon field is empty.

### Testing instructions

- Proceed to checkout and click on "Have a coupon code?" in the sidebar to show the coupon form.
- The coupon form submit button should be disable when the coupon field is empty or has only space characters.

### Note

> Not allowing the submission of an invalid coupon code (if there is a common format for them).

@klimeryk I've checked our coupons and they don't seem to share any format, so I've disregarded the request.

### CODE REVIEW

File: client/my-sites/checkout/cart/cart-coupon.jsx [hunk 1]
```diff
@@ -102,7 +102,11 @@ class CartCoupon extends React.Component {
 					onChange={ this.handleCouponInput }
 					value={ this.state.couponInputValue }
 				/>
-				<button type="submit" className="button">
+				<button
+					type="submit"
+					className="cart__button button"
```
Comment (vindl) [inline client/my-sites/checkout/cart/cart-coupon.jsx]: Should there be any CSS updates that match the new `className` here? Should we also remove the `button` class?

Comment (Copons) [reply client/my-sites/checkout/cart/cart-coupon.jsx]: I didn't want to go out of scope there.

To be honest, I only had to add `cart_button` there because the error was on the same line of the actual change, breaking the commit hooks.
Funnily enough, by adding it, the line becomes too long and Prettier breaks it, moving it into its own line. 😅

Comment (klimeryk) [reply client/my-sites/checkout/cart/cart-coupon.jsx]: The funny thing is - that className should not be required at all. Instead, a `Button` component should be used (which has the `button` style applied internally). Not sure why it was done this way originally 🤔 
```
<Button disabled={} ></Button>
```
seems like a simpler fix than adding a custom class name that is not used anywhere :)

File: client/my-sites/checkout/cart/cart-coupon.jsx [hunk 2]
```diff
@@ -102,7 +102,11 @@ class CartCoupon extends React.Component {
...
+					disabled={ ! trim( this.state.couponInputValue ) }
```
Comment (klimeryk) [inline client/my-sites/checkout/cart/cart-coupon.jsx]: I prefer a more explicit check than coercing a string into a boolean - seems safer to use something like [lodash's `isEmpty`](https://lodash.com/docs/#isEmpty).

**Comment by Copons** [comment]
I've implemented both suggestions by @klimeryk.
Since they were minor code style changes, I'll take the liberty of shipping this without further reviews. 🙂
