### PR TITLE
Media: Fix dropdown filter not working on some screen widths

### LINKED ISSUE #23878: Media: Dropdown filter does not work.
At different screen widths, the media filter alternates between text tabs and a dropdown. It works fine when in tabs, but doesn't work when a dropdown.

dropdown

The filter items [are generated](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/media-library/filter-item.jsx) by `FilterItem`, and get [converted to a dropdown](https://github.com/Automattic/wp-calypso/blob/master/client/components/section-nav/tabs.jsx#L108) in `NavTabs`.

It seems like [this click handler](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/media-library/filter-item.jsx#L15) is firing properly for tabs, but not getting passed to the dropdown items, and may have something to do with `onClick` vs. `onChange` props.

### PR DESCRIPTION
**Pull request by Copons**
Fix #23878

The [`SectionNavTabs`](https://github.com/Automattic/wp-calypso/blob/17276793273dd19f31a6e52de675fb8222918ff4/client/components/section-nav/tabs.jsx) component has three way to render its children:
- As actual tabs, when the container is wide enough to display all the labels.
- As a [`SelectDropdown`](https://github.com/Automattic/wp-calypso/tree/17276793273dd19f31a6e52de675fb8222918ff4/client/components/select-dropdown) when the container is not wide enough.
- As a special kind of dropdown for mobile screens.

`SectionNavTabs` expects its children to be [`SectionNavTabItem`](https://github.com/Automattic/wp-calypso/blob/17276793273dd19f31a6e52de675fb8222918ff4/client/components/section-nav/item.jsx) with (in this case) the `onClick` prop.

Currently though, the Media `SectionNavTabs` uses [`FilterItem`](https://github.com/Automattic/wp-calypso/blob/17276793273dd19f31a6e52de675fb8222918ff4/client/my-sites/media-library/filter-item.jsx) as children with the sole purpose of calling the click handler with `props.value` as parameter.
For some reason, the `FilterItem`'s click handler is called `onChange` which, though, is not the `onClick` that `SelectDropdown` expects.

This PR removes `FilterItem` altogether and replaces it with a simple `SectionNavTabItem`.
The `changeFilter` function becomes a higher-order function that can be called right away instead of requiring the whole "middleware" component.

## Testing instructions

- Open `/media` on a screen large enough that the navigation bar displays all the items as tabs.
- Make sure that clicking on those items changes the content of the page.
- Reduce the screen width so that the items are grouped in a dropdown button.
- Again test clicking the navigation items.
- Reduce the screen width as much as possible in order to show a mobile layout.
- Test the navigation items one last time.

### CODE REVIEW

File: client/my-sites/media-library/filter-bar.jsx [hunk 1]
```diff
@@ -125,15 +125,14 @@ export class MediaLibraryFilterBar extends Component {
 		return (
 			<SectionNavTabs>
 				{ tabs.map( filter => (
-					<FilterItem
+					<SectionNavTabItem
 						key={ 'filter-tab-' + filter }
-						value={ filter }
 						selected={ this.props.filter === filter }
-						onChange={ this.changeFilter }
+						onClick={ this.changeFilter( filter ) }
```
Comment (gwwar) [inline client/my-sites/media-library/filter-bar.jsx]: Hmm, only downside to this is we're recreating these on each render, when we know we have a fixed list of filters that don't change. Digging through code a bit this mostly translates to a state update and stat bump.

```jsx
	onFilterChange = filter => {
		if ( filter !== this.state.filter ) {
			analytics.mc.bumpStat( 'editor_media_actions', 'filter_' + ( filter || 'all' ) );
		}

		this.setState( { filter } );
	};
```

We probably had the child component do the following, which avoids the extra closure above.
```
this.props.onChange( this.props.value );
```

@Copons I think this is a reasonable approach, but do you mind doing a quick render count check to make sure the tabs behaving well?

Comment (Copons) [reply client/my-sites/media-library/filter-bar.jsx]: We're talking about ~30 renders at first load + ~3 renders every filter change.
I don't think this is _that_ bad perf wise. If anything, I'd probably seek to reduce the 30 initial renders.
