### PR TITLE
State: Move post-invite-accept user fetching to action

### LINKED ISSUE #53546: Invites: Accepting invitation doesn't redirect to posts page
### Steps to reproduce the behavior

You'll need two accounts for this, and the second one shouldn't have any sites:
1. With first account, go to  Users / Add new
2. Add the second account as an editor to your site
3. Log out with the first account and accept the invitation with the second account
4. See that Calypso is still on the `You have no sites` page instead of the Posts page for the site you were invited to.

See this whole flow in this recording of a [failing spec](https://teamcity.a8c.com/viewLog.html?buildId=6281404&buildTypeId=calypso_RunCalypsoE2eDesktopTests&tab=buildResultsDiv&branch_calypso_WebApp=fix%2Fe2e-create-site-for-domain-tests): https://teamcity.a8c.com/repository/download/calypso_RunCalypsoE2eDesktopTests/6281404:id/screenshots/user-has-been-added-as-editor-2021-06-09T12-23-13.mpg

#### What I expected to happen

After accepting an invitation a user should be redirected to the Posts page of the site they were invited to.

#### What actually happened

The `You have no sites` page is opened after accepting an invitation.

#### Level of impact

Low. The redirect happens when page is refreshed or the `My Sites` button is clicked.

### PR DESCRIPTION
**Pull request by tyxla**
#### Changes proposed in this Pull Request

Currently, when accepting an invite we'll redirect to `/posts/:siteId` but without ensuring the user's site count has been refreshed. That leads the user to hang on the invitation page. Caused by a regression we introduced in #53301.

This PR moves the user fetching to the action and waits for it to complete before continuing.

Fixes #53546

This PR ended up being related to #24004 where we aim to reduxify `lib/user`.

#### Testing instructions

* You're going to need 2 separate browser sessions for 2 separate users to test this.
* Create an account X without sites. To do that, start at `/start`, register, and just stop the flow. Verify you're logged in by going to `wordpress.com`.
* From another account (Y) send an Editor invitation to X to join the site.
* Go to the inbox of user X and copy the invitation button link.
* Change the `wordpress.com` part of the link to the `calypso.live` link or `calypso.localhost` link (wherever you're testing this branch)
* Accept.
* Verify you're redirected to `/posts/:siteId` and the posts list loads, and you can see the success notice.
* Verify e2e tests pass, particularly the one that is responsible for accepting an invite "User has been added as Editor".

### CODE REVIEW

**Review by WunderBart — APPROVED** [review]
Works perfectly. Thank you! 🚀

File: client/state/invites/actions.js [hunk 1]
```diff
@@ -219,33 +220,33 @@ export function disableInviteLinks( siteId ) {
...
-				dispatch( inviteAccepted( invite ) );
-				dispatch( requestSites() );
-			} )
-			.catch( ( error ) => {
-				if ( error.message ) {
-					dispatch( errorNotice( error.message, { displayOnNextPage: true } ) );
-				}
-				recordTracksEvent( 'calypso_invite_accept_failed', { error: error.error } );
+	return async ( dispatch ) => {
+		const data = await wpcom.undocumented().acceptInvite( invite );
```
Comment (jsnajdr) [inline client/state/invites/actions.js:224]: This REST call happens outside the try/catch block, so the `catch` statement won't catch errors from it. I'll fix it in a PR that removes the `wpcom.undocumented()` methods.

Also, the original promise-based action returned a rejected promise in case of error. Now it returns a promise resolved to `undefined`.
