### PR TITLE
Possible fix for 16198

### LINKED ISSUE #16198: Having a site with Jetpack version lower than 3.3 and going to posts crashes the app, instead of showing the warning
While refactoring minimum jetpack version notice on plugins, I checked for other uses of this notices and I may have found a bug in posts.
To reproduce just go to https://wordpress.com/posts/{site}, where {site} is a site using jetpack with a version lower than 3.3 e.g:3.2.
Instead of displaying the notice “Jetpack 3.3 is required to take full advantage of all post editing features." The application becomes totally unresponsive and if we are lucky (tab does not crash) a big amount of notices appears with a screen saying an unexpected error happened.
Tested in the last version of Chrome and Opera.

The browser is not responsive so the gif is long but in the end it is possible to see chrome asking if I want to kill the tab I said to wait and then it is possible to see a big amount of notices.

opera_2017-07-13_16-43-33

This was tested against the deployed public version of wordpress.com. If for some reason I missed something and the bug I reported does not exist, it's probably my testing scenario that has something wrong. If so I’m really sorry for that and I will try to find out what was wrong.

If this in fact proves a bug I created a possible fix in PR https://github.com/Automattic/wp-calypso/pull/16201.

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
While re-factoring minimum Jetpack version notice on plugins (to remove sites-list),  I checked for other uses of this notices and I found a bug in posts.

 This pull request proposes a solution based on an idea from @sirreal, it fixes #16198.

### CODE REVIEW

File: client/my-sites/posts/main.jsx [hunk 1]
```diff
@@ -34,21 +34,11 @@ import {
...
-	siteHasMinimumJetpackVersion
 } from 'state/sites/selectors';
 
 const PostsMain = React.createClass( {
-	componentWillMount() {
-		this.setWarning( this.props );
-	},
-
-	componentWillReceiveProps( nextProps ) {
-		this.setWarning( nextProps );
```
Comment (sirreal) [inline client/my-sites/posts/main.jsx]: This is likely the source of the problem and a fix could be applied here. Perhaps just checking `this.props` and `nextProps` equality for the props relevant to showing the warning: `siteId`, `isJetpack`, `hasMinimumJetpackVersion`.

Comment (jorgefilipecosta) [inline client/my-sites/posts/main.jsx]: 👍 Hi @sirreal thank you for having a look into this.  You are tottaly right if I change this to:
		if ( nextProps.siteId !== this.props.siteId || nextProps.hasMinimumJetpackVersion !== this.props.hasMinimumJetpackVersion ) {
			this.setWarning( nextProps );
		}

Things work perfectly. Should I create a new PR with this change?

Comment (sirreal) [inline client/my-sites/posts/main.jsx]: In my opinion, a lighter touch here may be a good thing. If this can be fixed by changing 1 line of code rather than adding ~40, that's probably a good thing 🙂

**Comment by jorgefilipecosta** [comment]
Hi @sirreal this PR now proposes the very small fix based on your idea. Feel free to have a new look.

**Comment by jorgefilipecosta** [comment]
Hi @sirreal, thank you for reviewing and confirming that this fixes the issue! If from your side there are no remaining discussion points, if you could merge and ship this PR it would be perfect :)

**Comment by sirreal** [comment]
Thanks @jorgefilipecosta!
