### PR TITLE
Make the login form "Return" link conditional on there being somewhere to return.

### LINKED ISSUE #13785: Login form displays a 'Return' link when there's nowhere to return to
#### Steps to reproduce
1. Open http://calypso.localhost:3000/login in a new tab
2. Confirm that there's no history (the browser back button is disabled)
3. Note that the 'Return' link below the login form is visible, but does nothing

#### What I expected

The Return link shouldn't be visible.

#### Screenshot / Video

Login form showing Return link

### PR DESCRIPTION
**Pull request by pento**
This pull request addresses/fixes #13785 by removing the "Return" link when there's nothing in `window.history`:
 
Login page without browser history:

Login page without browser history

Login page with browser history:

Login page with browser history

 
#### Testing instructions
 
1. Run `git checkout fix/13785-login-return-link` and start your server, or open a [live branch](https://calypso.live/?branch=fix/13785-login-return-link)
2. Open the [`Login` page](http://calypso.localhost:3000/login)
3. Check that the "Return" link shows if your browser back button is active, and doesn't show if they button isn't active.
 
#### Reviews
 
- [ ] Code
- [ ] Product
- [ ] Tests

### CODE REVIEW

File: client/login/wp-login/index.jsx [hunk 1]
```diff
@@ -104,12 +104,16 @@ class Login extends React.Component {
...
-			onClick={ this.goBack }>
-				<Gridicon icon="arrow-left" size={ 18 } /> { this.props.translate( 'Return' ) }
-			</a>;
+		let goBackLink;
+		if ( typeof window === 'undefined' || window.history.length > 1 ) {
+			goBackLink = ! magicLoginView && <a
+				href="#"
+				key="back-link"
+				onClick={ this.goBack }>
+					<Gridicon icon="arrow-left" size={ 18 } /> { this.props.translate( 'Return' ) }
```
Comment (yurynix) [inline client/login/wp-login/index.jsx]: Nitpick: you can just `translate( 'Return' )` here

File: client/login/wp-login/index.jsx [hunk 2]
```diff
@@ -104,12 +104,16 @@ class Login extends React.Component {
...
 		}
 
-		const goBackLink = ! magicLoginView && <a
-			href="#"
-			key="back-link"
-			onClick={ this.goBack }>
-				<Gridicon icon="arrow-left" size={ 18 } /> { this.props.translate( 'Return' ) }
-			</a>;
+		let goBackLink;
+		if ( typeof window === 'undefined' || window.history.length > 1 ) {
```
Comment (yurynix) [inline client/login/wp-login/index.jsx]: Not sure I understand that, why `||` and not `&&` ?
`this.goBack` is essentially `window.history.back();` so if we don't have a `window` we shouldn't display a link as well, am I missing something?

Comment (pento) [inline client/login/wp-login/index.jsx]: `/login` is rendered on the server side, so `window` isn't available. However, when it gets to the client side, `window` is now available, and we can detect if there's something in `window.history` to go back to.

Unfortunately, this is both bad (it causes a the Return button to initially appear, then disappear) and wrong (React dumps an error in the console, complaining about markup that doesn't match between server and client).

File: client/login/wp-login/index.jsx (hunk 1 above)
Comment (pento) [inline client/login/wp-login/index.jsx]: Fixed!

File: client/login/wp-login/index.jsx (hunk 2 above)
Comment (yurynix) [inline client/login/wp-login/index.jsx]: Checkout the trick with `componentDidMount` [here](https://github.com/Automattic/delphin/blob/master/app/components/ui/form/email.js) and `state` here, maybe that's a better approach?

Comment (pento) [inline client/login/wp-login/index.jsx]: Thanks for the pointer, fixed. :-)

**Comment by pento** [comment]
In the tests, it feels fairly hacky to be mocking `translate()` manually. Is there a better way of doing this?

File: client/login/wp-login/index.jsx [hunk 3]
```diff
@@ -36,7 +36,7 @@ import RequestLoginEmailForm from '../magic-login/request-login-email-form';
 import { recordTracksEvent } from 'state/analytics/actions';
 import PageViewTracker from 'lib/analytics/page-view-tracker';
 
-class Login extends React.Component {
+export class Login extends React.Component {
```
Comment (pento) [inline client/login/wp-login/index.jsx]: I guess I'm supposed to just export the class, so I can load it in testing? Does this have side effects I'm not aware of?

File: client/login/wp-login/index.jsx [hunk 4]
```diff
@@ -89,7 +103,7 @@ class Login extends React.Component {
 		}
 	};
 
-	footerLinks() {
+	footerLinks = () => {
```
Comment (pento) [inline client/login/wp-login/index.jsx]: Is this the correct way to make a method publicly usable?

File: client/login/wp-login/test/test.js [hunk 5]
```diff
@@ -0,0 +1,53 @@
...
+ */
+import { expect } from 'chai';
+
+/**
+ * Internal Dependencies
+ */
+import { Login } from '../index.jsx';
+import useFakeDom from 'test/helpers/use-fake-dom';
+
+const defaultProps = {
```
Comment (pento) [inline client/login/wp-login/test/test.js]: Defining `defaultProps` here seems kind of weird, I didn't notice other examples of how to do it, though. Should I be loading the `Login` component in some other way that adds the `props` in the normal fashion?

File: client/login/wp-login/test/test.js [hunk 6]
```diff
@@ -0,0 +1,53 @@
...
+	magicLoginEnabled: true,
+	magicLoginView: '',
+	translate: ( str ) => {
```
Comment (pento) [inline client/login/wp-login/test/test.js]: Inlining a `translate()` mock feels awful. I hope there's a better way to do this?

File: client/login/wp-login/test/test.js [hunk 7]
```diff
@@ -0,0 +1,53 @@
...
+		it( 'should not have a return button before the state is loaded', () => {
+			const login = new Login( defaultProps );
+			const links = login.footerLinks();
+
+			expect( links ).to.have.length( 2 );
+		} );
+
+		it( 'should not have a return button after the state is loaded, but there is no history', () => {
+			const login = new Login( defaultProps );
+			login.state.loaded = true;
```
Comment (pento) [inline client/login/wp-login/test/test.js]: It seems like a bad idea to be writing to `state` directly, but I got an error when I tried to use `setState()`.

File: client/login/wp-login/test/test.js [hunk 8]
```diff
@@ -0,0 +1,53 @@
...
+			window.history.pushState( {}, '' );
+
+			const login = new Login( defaultProps );
+			login.state.loaded = true;
+
+			const links = login.footerLinks();
+
+			expect( links ).to.have.length( 3 );
+
+			window.history.back();
```
Comment (pento) [inline client/login/wp-login/test/test.js]: Do I need to reset my changes to `window.history`, or will `use-fake-dom` take care of that?

Comment (pento) [inline client/login/wp-login/test/test.js]: Is it okay to do cleanup after an `expect()` call? I know that some testing libraries `throw` an error when they fail, so anything that happens after that fails won't be run - they provide magic cleanup functions, instead.

File: client/login/wp-login/index.jsx (hunk 3 above)
Comment (yurynix) [inline client/login/wp-login/index.jsx]: No side effects I can think of.
More complicated option is importing the default export and mocking `connect` & `localize` HoCs.

File: client/login/wp-login/index.jsx (hunk 4 above)
Comment (yurynix) [inline client/login/wp-login/index.jsx]: It's not about public vs private, but about `this` binded or not:
Arrow funcs have their this bound to current this, while regular methods aren't,
so it's one option to achieve that for funcs we'll have to pass further, to for example, `onClick` prop.

File: client/login/wp-login/test/test.js (hunk 5 above)
Comment (yurynix) [inline client/login/wp-login/test/test.js]: I think that's fine, since these are the parameters `Login` component depends on.

File: client/login/wp-login/test/test.js (hunk 6 above)
Comment (yurynix) [inline client/login/wp-login/test/test.js]: that's one of the dependencies, so moking it makes sense to me, you can do `translate: str => str,`

File: client/login/wp-login/test/test.js (hunk 7 above)
Comment (yurynix) [inline client/login/wp-login/test/test.js]: For testing react component we use `enzyme`, take a look at an example [here](https://github.com/Automattic/wp-calypso/blob/master/client/components/domains/domain-suggestion/test/index.js).

You can't just call the methods, because you need to emulate the whole react life-cycle.

For server side rendering you can use something like [that](https://github.com/Automattic/wp-calypso/blob/fcf789ebb43b7d8fe9a912d8fa82d5bee66573b5/server/pages/test/index.js#L31)

File: client/login/wp-login/test/test.js (hunk 8 above)
Comment (gziolo) [inline client/login/wp-login/test/test.js]: `useFakeDom` will take care of cleanup after this test suite is executed. This helper assigns to window object fresh instance of mocked DOM.

Comment (gziolo) [inline client/login/wp-login/test/test.js]: Usually you use `after` and `afterEach` methods to perform cleanup. First method is called after all tests finished, second method is called after each test. It will be run event when tests fails, errors, etc. So it is very similar to PHPUnit's `tearDown` method which you can execute on instance or as static property of class. Cleanup after error in the test itself is not guaranteed as you suspect.

File: client/login/wp-login/test/test.js (hunk 6 above)
Comment (gziolo) [inline client/login/wp-login/test/test.js]:
```js
translate: x => x
```
makes it even shorter :)

You can also use `identity` from `lodash` which does the same.

File: client/login/wp-login/index.jsx [hunk 9]
```diff
@@ -104,12 +118,16 @@ class Login extends React.Component {
...
 		}
 
-		const goBackLink = ! magicLoginView && <a
-			href="#"
-			key="back-link"
-			onClick={ this.goBack }>
-				<Gridicon icon="arrow-left" size={ 18 } /> { this.props.translate( 'Return' ) }
-			</a>;
+		let goBackLink;
+		if ( this.state.loaded && window.history.length > 1 ) {
```
Comment (gziolo) [inline client/login/wp-login/index.jsx]: We are server rendering this component. Node doesn't have access to `window` object. We can use
```js
window && window.history.length > 1
```
to make sure it doesn't throw error on the server.

File: client/login/wp-login/index.jsx (hunk 3 above)
Comment (gziolo) [inline client/login/wp-login/index.jsx]: It's perfectly fine, because wrapped component is exported as default 👍

File: client/login/wp-login/index.jsx (hunk 4 above)
Comment (gziolo) [inline client/login/wp-login/index.jsx]: As Yury mentioned below, you should use enzyme to test React components and treat them more like a black box. You can always extract footer links to its own component if you want to test that part explicitly.

File: client/login/wp-login/test/test.js (hunk 7 above)
Comment (gziolo) [inline client/login/wp-login/test/test.js]: I would rather recommend using [shallow rendering](https://github.com/airbnb/enzyme/blob/master/docs/api/shallow.md) for testing React components :)

Example here: https://github.com/Automattic/wp-calypso/blob/13c51873c56898ebd2dad72564d97822de4e5a22/client/components/notice/test/index.js

This test also uses `identity` to stub `translate` property.

File: client/login/wp-login/index.jsx (hunk 3 above)
Comment (Tug) [inline client/login/wp-login/index.jsx]: Note that it has a side effect for webpack if we use `require` to load the module.
Since we now have more than a `default` exported, we would need to write `const Login = require( 'login/wp-login' ).default` explicitly.

Comment (pento) [inline client/login/wp-login/index.jsx]: @Tug: Unfortunately, I have no context as to whether that's a problem or not. Can you go into more detail, please? :)

File: client/login/wp-login/test/test.js (hunk 7 above)
Comment (pento) [inline client/login/wp-login/test/test.js]: Cool, I've switched the tests over to using `enzyme`.

File: client/login/wp-login/test/test.js (hunk 5 above)
Comment (pento) [inline client/login/wp-login/test/test.js]: Deleted this, it's no longer needed now that the tests use `enzyme` instead.

File: client/login/wp-login/test/test.js (hunk 6 above)
Comment (pento) [inline client/login/wp-login/test/test.js]: Went with the `identity` method, thanks. :)

File: client/login/wp-login/index.jsx (hunk 9 above)
Comment (pento) [inline client/login/wp-login/index.jsx]: I've tried this before, but React throws an error in the console:
`Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) " data-reactid="41"><svg class="gridicon
 (server) " data-reactid="41">Email me a login lin`

The current method is based on @yurynix's [suggestion](https://github.com/Automattic/wp-calypso/pull/13786#discussion_r115421298).

File: client/login/wp-login/index.jsx (hunk 3 above)
Comment (Tug) [inline client/login/wp-login/index.jsx]: Nop, it's not a problem here, just a comment that it can, sometimes, have side effects ;)

File: client/login/wp-login/test/test.jsx [hunk 10]
```diff
@@ -0,0 +1,55 @@
...
+
+				expect( login.find( '.wp-login__footer > a' ).length ).to.equal( 1 );
+			} );
+		} );
+
+		context( 'after state is loaded', () => {
+			context( 'there is no history', () => {
+				it( 'should not have a return button', () => {
+					const login = shallow( <Login queryArguments={ { redirect_to: '' } } translate={ identity } /> );
+					login.setState( { loaded: true } );
```
Comment (yurynix) [inline client/login/wp-login/test/test.jsx]: Maybe we should `mount()` the component, `componentDidMount` will execute and set the state and then we test the result?

File: client/login/wp-login/index.jsx (hunk 9 above)
Comment (stephanethomas) [inline client/login/wp-login/index.jsx]: Humm. I wonder why React throws this warning since the browser history should be empty on page load, meaning the return link wouldn't be displayed in that case.

Comment (yurynix) [inline client/login/wp-login/index.jsx]: It gives that warning because on SSR there's no `window`, but when you render on client there is a history, hence the warning of mismatched markup.

Comment (stephanethomas) [inline client/login/wp-login/index.jsx]: Yes, but when you are client-side the history should be empty (or said differently, you shouldn't be able to navigate back to any previous page).

Comment (stephanethomas) [inline client/login/wp-login/index.jsx]: My bad, it's indeed possible to land on this page by following a link, meaning the history wouldn't be empty. Not sure why my brain couldn't envision such frequent scenario ...

File: client/login/wp-login/index.jsx [hunk 11]
```diff
@@ -49,6 +49,13 @@ class Login extends React.Component {
 		this.props.showMagicLoginRequestForm();
 	};
 
+	constructor( props ) {
+		super( props );
+		this.state = {
+			loaded: false
+		};
+	}
```
Comment (pento) [inline client/login/wp-login/index.jsx]: 👍🏻

File: client/login/wp-login/test/test.jsx (hunk 10 above)
Comment (pento) [inline client/login/wp-login/test/test.jsx]: I get an exciting new error when I try that.
```
Invariant Violation: Could not find "store" in either the context or props of "Connect(PageViewTracker)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(PageViewTracker)".
      at invariant (node_modules/invariant/invariant.js:42:15)
      at new Connect (node_modules/react-redux/lib/components/connectAdvanced.js:134:33)
      at node_modules/react-dom/lib/ReactCompositeComponent.js:295:18
      at measureLifeCyclePerf (node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
      at ReactCompositeComponentWrapper._constructComponentWithoutOwner (node_modules/react-dom/lib/ReactCompositeComponent.js:294:16)
      at ReactCompositeComponentWrapper._constructComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:280:21)
      at ReactCompositeComponentWrapper.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:188:21)
      at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:46:35)
      at ReactDOMComponent.mountChildren (node_modules/react-dom/lib/ReactMultiChild.js:238:44)
      at ReactDOMComponent._createInitialChildren (node_modules/react-dom/lib/ReactDOMComponent.js:691:32)```

**Comment by pento** [comment]
I thought I'd fixed the return button flicker when the page is reloaded, but I guess not.

Any suggestions?

screen-grab

File: client/login/wp-login/index.jsx [hunk 12]
```diff
@@ -118,12 +127,16 @@ class Login extends React.Component {
...
 
-		const goBackLink = ! magicLoginView && <a
-			href="#"
-			key="back-link"
-			onClick={ this.goBack }>
-				<Gridicon icon="arrow-left" size={ 18 } /> { this.props.translate( 'Return' ) }
-			</a>;
+		let goBackLink;
+		if ( this.state.loaded && window.history.length > 1 ) {
+			goBackLink = ! magicLoginView && <a
```
Comment (stephanethomas) [inline client/login/wp-login/index.jsx]: That's super minor and probably personal preference, but I feel like the test on `! magicLoginView`  should be part of the `if` condition above.

File: client/login/wp-login/test/test.jsx (hunk 10 above)
Comment (yurynix) [inline client/login/wp-login/test/test.jsx]: That happens because in `render()` we have `PageViewTracker` which is a `connect`ed component, therefor it needs a redux store, so either we mock `PageViewTracker` or the redux store.
