### PR TITLE
Store: Show Store in sidebar for all countries, provide means to get to wp-admin for unsupported countries

### LINKED ISSUE #20607: Store: Update Logic for Store Sidebar Link in Calypso
To prepare for non US/CA users of WooCommerce on AT sites, we need to update the logic that is used to display the "Store" link in the sidebar, and determine what the link target is. So there will be five different states for the sidebar store link:

__Atomic Site, Supported Country, WooCommerce Installed__
If the site is on AT, has `woocommerce` installed and activated, and is in a supported country ( currently US / CA ), the Store link will be shown, and the target will be `https://wordpress.com/store/DOMAIN`

__Atomic Site, Supported Country, WooCommerce not Installed__
The Store link should be shown in this instance, and will target the existing new store flow.

__Atomic Site, Non-Supported Country, WooCommerce Installed__
For AT sites that have `woocommerce` installed and activated, but are not in a currently supported country, show the Store link with the external gridicon, and link to the WC dashboard page `/wp-admin/edit.php?post_type=shop_order`

external-link

__Atomic Site, Non-Supported Country, WooCommerce not Installed__
For now I think the link should not be shown in this scenario. Once the Store Nux supports non-supported countries, we could expose the Store link and send these users through the standard setup flow, which will ultimately send them to the Woo setup wizard.

__All Other Sites__
In all other instances the Store link should not be shown. Eventually we could consider exposing the Store link to Pro plan users to attempt an up-sell, but for now let's just keep it hidden.

### LINKED ISSUE #21478: Store: "Let's set up your store" view appears for nonUS nonCA stores
#### Steps to reproduce
1. Use https://developer.wordpress.com/docs/api/console/ to POST 0 to every field in sites/{SITEID}/calypso-preferences/woocommerce - thereby simulating a new site
2. Starting at URL: https://wordpress.com/store/{DOMAIN}
3. On the Have something to sell? view, click Set up my store!
4. On the Howdy! Ready to start selling? view, enter a nonUS nonCA address and click Next
5. You should be sent to the WooCommerce setup wizard on the site in question
6. Manually navigate to https://wordpress.com/store/{DOMAIN}
7. You get dropped in the Let's set up your store checklist view (you should not be able to setup or manage nonUS nonCA stores in calypso at this time)

props @timmyc for the find

### PR DESCRIPTION
**Pull request by allendav**
Fixes #20607 
Fixes #21478 

To test:
* Use https://developer.wordpress.com/docs/api/console/ to POST to /sites/{SITEID}/calypso-preferences/woocommerce set_store_address_during_initial_setup to 0
* Navigate to http://calypso.localhost:3000/store/{DOMAIN} and set your store's address to a US address
* Navigate to https://wordpress.com/stats/day{DOMAIN}
* Click on the Store link in the sidebar
* Ensure you are taken to the dashboard in calypso
* Repeat for a Canadian address, e.g.

```
811 Hornby St
Vancouver, BC V6Z2E6
Canada
```

* Ensure you are taken to the dashboard in calypso

* Repeat for a nonUS nonCA address, e.g.:

```
2 Elizabeth St
Melbourne VIC 3004
Australia

or

7 Allées du Président Franklin Roosevelt
31000 Toulouse
France
(Make sure currency is set to EUR, dimensions to cm and weight to kg)
```

* Make sure you see a prompt and a button and that the sidebar only has the dashboard itself, e.g.:

screen shot 2018-01-11 at 11 48 55 am

* Make sure that clicking on the button takes you to your orders view in wp-admin

### CODE REVIEW

File: client/extensions/woocommerce/app/dashboard/manage-external-view.js [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+
+	render = () => {
+		const { site, translate } = this.props;
+
+		const title = translate( 'Manage your store' );
+		const line = translate(
+			'Stores in your country are managed directly on your site. ' +
+				'We will let you know when you can manage your store here.'
+		);
+		const actionURL = site.URL + '/wp-admin/edit.php?post_type=shop_order';
```
Comment (timmyc) [inline client/extensions/woocommerce/app/dashboard/manage-external-view.js]: If we end up going this route, I'd love to have some tracks on the number of clicks here.

File: client/my-sites/sidebar/sidebar.jsx [hunk 2]
```diff
@@ -376,35 +371,28 @@ export class MySitesSidebar extends Component {
 			return null;
 		}
 
-		const storeLink = '/store' + siteSuffix;
-
-		const isJetpackOrAtomicSite =
-			isJetpack && canUserManageOptions && this.props.isSiteAutomatedTransfer;
+		const isPermittedSite = isJetpack && canUserManageOptions && this.props.isSiteAutomatedTransfer;
```
Comment (timmyc) [inline client/my-sites/sidebar/sidebar.jsx]: I realize this code is the same as before almost but isn't a site `isJetpack` always true when `isSiteAutomatedTransfer`?

**Comment by allendav** [comment]
@timmyc wrote

> should I open an issue up for the wrong wizard showing?

yes please!

File: client/my-sites/sidebar/sidebar.jsx (hunk 2 above)
Comment (allendav) [reply client/my-sites/sidebar/sidebar.jsx]: I'm not sure but I think you're right.

**Comment by allendav** [comment]
@timmyc wrote

> Also it looks like the MailChimp dashboard item is shown, which I think should be hidden for non-supported countries.

Hmmm - I didn't see that - I'll figure out what is happening there

File: client/my-sites/sidebar/sidebar.jsx (hunk 2 above)
Comment (allendav) [reply client/my-sites/sidebar/sidebar.jsx]: Fixed in https://github.com/Automattic/wp-calypso/pull/21466/commits/7912b018ccbea3295bfe1fa768749c4b2286495a

**Comment by allendav** [comment]
@timmyc wrote

> Also it looks like the MailChimp dashboard item is shown, which I think should be hidden for non-supported countries.

@allendav wrote 

> Hmmm - I didn't see that - I'll figure out what is happening there

Ah - that happens only if the mailchimp has never been configured (i.e. empty api key) - fixing now

File: client/extensions/woocommerce/app/dashboard/manage-external-view.js (hunk 1 above)
Comment (allendav) [reply client/extensions/woocommerce/app/dashboard/manage-external-view.js]: Fixed in https://github.com/Automattic/wp-calypso/pull/21466/commits/e88080314c755645ae2dff6a65342babff2b7d5f

**Comment by allendav** [comment]
@timmyc wrote:

> I did however discover a bug that is in production too where if a user doesn't configure their store and are in a non US/CA country, they are shown the wizard in calypso:

Fixed in https://github.com/Automattic/wp-calypso/pull/21466/commits/a9eae3a6564dd0c8885beee7d13e57cc1081b26e

**Comment by timmyc** [comment]
@kellychoffman while we are on support week, we kind of in a bit of a limbo state for non US/CA customers right now. The sidebar link is very well a bit broken for them currently, so I'm thinking we should land this PR for now - since it works well, and then circle back after support week is over.

What do you think?

**Comment by kellychoffman** [comment]
I'm on board with that. We'll just need a rewording: 

**Managing your store**

Howdy! It looks like your store is located in a country that we can not fully support in this interface. Store setup and management will take place in wp-admin, our classic admin interface. We are actively working on adding broader support and we'll let you know when you can manage your store here!

[**Manage my Store** [external link icon] ]

**Comment by allendav** [comment]
OK, it looks like this now

screen shot 2018-01-16 at 9 48 52 am

**Comment by allendav** [comment]
Oops - the copy changes didn't make it in (I forgot to push them) - will do so in a separate PR
