### PR TITLE
Gutenboarding: Handle Domain Suggestion APIs failures

### LINKED ISSUE #43503: Domain Picker: Make domain picker resilient against potential Domain Suggestions API failure.
I discovered that the 2nd step domains page could blank out when the domain suggestions API fails.

Granted, my testing environment is a little botched, because I'm pointing `public-api.wordpress.com` to my broken sandbox where php logs are being outputted inside http response causing malformed JSON response. 

**However, I think it's an opportunity to test the resilience of the client-side when server-side API fails.**

image

The `wpcomRequest()` function as used in `packages/data-stores/src/domain-suggestions/resolvers.ts` could return an empty string when API request fails.

When this empty string lands on to places like `domainSuggestions?.map()`, the optional chain operator `?` only checks against`undefined` and `null` when transpiled, that's why an operation like `"".map()` breaks, and the domain picker component fails to render.

image

Another issue I had was instances where `wpcomRequest()` fails without making any network request, this also returns an empty string. I could only replicate this when running e2e test. This empty string occurrence happens inside `useOnLogin()` hook. 

image

I can't explain this behaviour yet but one thing to keep in mind is that e2e test is running as guest (at least initially). It may or may not be the cause of this issue p1592573181429200-slack-CNMU1UHHB (where some user on Chrome iOS don't get pass 2nd step), but at least we can eliminate one possible point of failure.

If the domain picker doesn't blank out completely, at least user can still continue to search for domains, and who knows, maybe the API request only fails the first time, but not the second time around on unstable network.

### PR DESCRIPTION
**Pull request by ciampo**
### Changes proposed in this Pull Request

- Refactor the `@wordpress/data` store in `packages/data-stores/src/domain-suggestions` so that it handles (in the store's state) the different errors that can happen while calling the Domain Suggestion APIs:
  - network failure
  - malformed JSON response from the APIs
  - JSON response containing an error message (eg. when the query contains non-latin characters)
  - empty string response (which is also a sign of a server error)

- Show an error message to the user, together with a "Retry" button which re-triggers the call to the APIs
  - I applied a minor refactor to the logic behind showing different parts of the UI (e.g. show error message vs show domain suggestion results)
  - I also refactored the return value `useDomainSuggestion()` hook — it now returns an object with all the variables and functions needed by the UI
  - The API call is re-triggered by invalidating the cached results of the store resolver
  - While the error message is displayed, the text field for the domain query is disabled — this is to avoid that the user can trigger a new Domain Suggestion search during an error state.
  - _Please note that I didn't follow any design spec for this part of the layout_.

- The shape of the store's state is heavily inspired by the [http-data module](https://github.com/Automattic/wp-calypso/blob/master/client/state/data-layer/http-data.ts#L17-L41)

#### First scenario: network failure
1.  Go to http://calypso.localhost:3000/new and enter a site name
2. Wait for the domain suggestion to load successfully
3. Open the dev tools, go to the Network tab, and simulate "Offline" network conditions
4. Type in the text field to trigger a new domain suggestion query
5. Notice how an error message is shown
6. Open the dev tools, go to the Network tab switch back to "Online" network conditions
7. Click on the "Retry" button
8. The Domain Suggestion loads successfully

#### Second scenario: non-latin characters
1.  Go to http://calypso.localhost:3000/new and enter a site name
2. Wait for the domain suggestion to load successfully
3. Type some non-latin characters in the text field to trigger a new domain suggestion query
4. Notice how an error message is shown
5. Type a new query using latin characters
6. The Domain Suggestion loads successfully

#### Third scenario: malformed server response

1. With a fresh & up-to-date version of the sandbox, edit the `~/public-html/public.api/rest/wpcom-json-endpoints/class.wpcom-store-domains-api-endpoints.php` file, and add this code as the first line of the `callback` function: `if ( A8C_PROXIED_REQUEST ) { var_dump('test'); exit(); }`
2. Change your hosts file and add a rule to redirect `public-api.wordpress.com` to your sandbox
3. Clear DNS and hosts cache
4.  Go to http://calypso.localhost:3000/new and enter a site name
5. Notice how an error message is shown (you can check that the response received from the Domain Suggestion APIs contains indeed the "test" string from the sandbox)
6. Disable the hosts rule mapping the APIs to the sandbox and clear DNS and hosts cache
7. Type a new query in the text field to trigger a new Domain Suggestion query
8. The Domain Suggestion loads successfully

### Before

(Notice how the UI just hangs on the user without any visible error message)

Screenshot 2020-09-08 at 17 13 23

### After

(error message + "Retry" button are shown)

Screenshot 2020-09-08 at 17 13 51

Fixes #43503

Partially related to #44421, although that issue seems to be more related to domain availability checking. But it would be good if the code was already structured to allow for the changes required by that issue.

---

### Questions / notes:

- Specifically, regarding types, it seems that [`invalidateResolutionForStoreSelector`](https://github.com/WordPress/gutenberg/blob/master/packages/data/src/namespace-store/metadata/actions.js#L57) is not typed as an action returned by `useDispatch` — for now I just ignored the TypeScript warning, but that needs to be addressed
- Error messages: especially in the light of future work (see #44421), should we structure error messages in a different way? How would we handle i18n for the error messages?

### CODE REVIEW

File: packages/domain-picker/src/hooks/use-domain-suggestions.ts [hunk 1]
```diff
@@ -1,35 +1,64 @@
...
+import type { DataState } from '@automattic/data-stores/src/domain-suggestions/constants';
+import type { DomainSuggestion } from '@automattic/data-stores/src/domain-suggestions/types';
 import { useDebounce } from 'use-debounce';
 
 /**
  * Internal dependencies
  */
 import { DOMAIN_SUGGESTIONS_STORE, DOMAIN_SEARCH_DEBOUNCE_INTERVAL } from '../constants';
 
+type ReturnType = {
```
Comment (alshakero) [inline packages/domain-picker/src/hooks/use-domain-suggestions.ts:14]: I would give this a more specific name.

```suggestion
type DomainSuggestionsResult = {
```

File: packages/data-stores/src/domain-suggestions/constants.ts [hunk 2]
```diff
@@ -1 +1,8 @@
 export const STORE_KEY = 'automattic/domains/suggestions';
+
+export enum DataState {
```
Comment (alshakero) [inline packages/data-stores/src/domain-suggestions/constants.ts:3]: `State` can be conflated with the genenal state. I'd use `Status`.

File: packages/data-stores/src/domain-suggestions/actions.ts [hunk 3]
```diff
@@ -9,14 +9,30 @@ export const receiveCategories = ( categories: DomainCategory[] ) =>
...
+		type: 'FETCH_DOMAIN_SUGGESTIONS',
+	} as const );
+
+export const receiveDomainSuggestionsData = (
 	queryObject: DomainSuggestionQuery,
 	suggestions: DomainSuggestion[] | undefined
 ) =>
 	( {
-		type: 'RECEIVE_DOMAIN_SUGGESTIONS',
+		type: 'RECEIVE_DOMAIN_SUGGESTIONS_DATA',
```
Comment (alshakero) [inline packages/data-stores/src/domain-suggestions/actions.ts:22]: IMO, `DATA` is almost always a tautology, doesn't add meaning. Maybe make it `SUCCESS`.

File: packages/data-stores/src/domain-suggestions/reducer.ts [hunk 4]
```diff
@@ -3,24 +3,71 @@
  */
 import type { Reducer } from 'redux';
 import { combineReducers } from '@wordpress/data';
+import type { TimestampMS } from 'wp-calypso-client/types';
```
Comment (alshakero) [inline packages/data-stores/src/domain-suggestions/reducer.ts:6]: This would probably cause issues when the package is used in wp-admin. You can inline it if you want `ReturnType< typeof Date.now >`.

File: packages/domain-picker/src/domain-picker/index.tsx [hunk 5]
```diff
@@ -169,6 +177,11 @@ const DomainPicker: FunctionComponent< Props > = ( {
 		onSetDomainSearch( searchQuery );
 	};
 
+	const showErrorMessage = domainSuggestionState === DataState.Failure;
+	const isDomainSearchEmpty = domainSearch.trim()?.length <= 1;
```
Comment (alshakero) [inline packages/domain-picker/src/domain-picker/index.tsx:181]: If trim works, length will defintely work. You probably need the `?` before the trim call. 
```suggestion
	const isDomainSearchEmpty = domainSearch.trim?.().length <= 1; // or domainSearch.trim?.().length ?? false;
```

File: packages/domain-picker/src/domain-picker/index.tsx [hunk 6]
```diff
@@ -185,9 +198,25 @@ const DomainPicker: FunctionComponent< Props > = ( {
...
 					value={ domainSearch }
+					disabled={ showErrorMessage }
 				/>
 			</div>
-			{ domainSearch.trim()?.length > 1 ? (
+			{ showErrorMessage && (
+				<div className="domain-picker__error">
+					<p className="domain-picker__error-message">
+						{ __( 'An error has occurred, please check your connection and retry.' ) }
+						{ domainSuggestionErrorMessage && ` ${ domainSuggestionErrorMessage }` }
```
Comment (alshakero) [inline packages/domain-picker/src/domain-picker/index.tsx:208]: This won't be translated. You need to wrap the string with `__()`. But not here, where it's originally defined, the translation bot parses the code looking for phrases, but it doesn't evaluate it. So It has to be 

`__('the string itself')`

**Review by alshakero — CHANGES_REQUESTED** [review]
Great great work! The implementation is great. But I think the business logic is a bit off.

There is no need to retry when the error is in the query, retrying won't make a difference. Especially that the field is disabled and you can't fix your query. Maybe we need to make some errors retryable (network) and others not (non-latin).

#### To answer your questions
> Should we consider splitting the categories and the domainSuggestions sub-reducers?

That's really up to you. I think it's alright now

> Regarding the reducer, I'm not sure I put the right code in the right place, especially around type declarations and constants — I'd love some feedback around that!

Not a types expert, but IMO you nailed it. Great work.

> Error messages: especially in the light of future work (see #44421), should we structure error messages in a different way? How would we handle i18n for the error messages?

I think the structure is alright. But I commented on one example how can you fix it to make i18n work.

> What's the best way for me to add tests (unit tests for the @wordpress/data store, and potentially e2e)?

I honestly don't have a good opinion on this, but I'd personally mimic the current (e2e) tests and ask @razvanpapadopol to review.

File: packages/data-stores/src/domain-suggestions/reducer.ts [hunk 7]
```diff
@@ -3,24 +3,71 @@
...
 
-const domainSuggestions: Reducer< Record< string, DomainSuggestion[] | undefined >, Action > = (
-	state = {},
+export interface DomainSuggestionState {
+	state: DataState;
+	data: Record< string, DomainSuggestion[] | undefined >;
+	errorMessage: string | null;
+	lastUpdated: TimestampMS;
+	pendingSince: TimestampMS | undefined;
+}
```
Comment (sirreal) [inline packages/data-stores/src/domain-suggestions/reducer.ts:22]: This is a simplification of what's in `http-data` which loses some important properties. For comparison:

https://github.com/Automattic/wp-calypso/blob/b9523f1420982eef9f659e2a04fb4b5efd065dfd/client/state/data-layer/http-data.ts#L17-L41

There's a practice often referred to as "making invalid states unrepresentable" which the http-data structure strives for but is lost here. [Here's an example](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBDAnmApnA3nASigJgVwGMUo4BfOAMyghDgHIo98APegbgChRJYM5CtAEbAAdihwFiUAM7kqNOo2ZsunJKjgAVUChkwAhuACyAZTgBebChj4oorchQAeABQaUESnAAiBmCgAlADa9KIQAO70ALoAfJwoLLzwKKL4dH6GpoYBGJxwBXAAYgbAADZ2aFb0lKUVTPQANPmFAAqpuGIA5pYMqKKdol1NLQWmRMQyctUyE3oyI4VwAKqiYsAwwAZlwABeeL30+Gtrm9t7eCNknNyiAVC1xNYyEHbEmQbOWo1wAKKxeSW+n8KAAXL5-AZsiCuEtcJDwVo4AAfODHXAoShiPCwwokGhQcG-FFogaY7G4XEFMoGfTLMDwgK4RG6YEmUxUuD9QZdUxiYgskB6Qzskno8niSmca7qJzPV5QYhfXrHADW4Qioh+xKsao1ogBFlGJNcOBebxQHy+2oBADJ+MCAuCPtCAgA6VbrM47faUuCMgzg8VYyXsOD46BBskhnFcjrdPmiAWkjExv1kQLG1GmvQK96Q61-O0OnJgiFZUtu9oDbphiOElMS2PchP8ss6IVssBmciZpbZs15y0F75FuD2zCOssuyslcqVOtQAmIn4toaJ5PBim9rNwHPmxXDwyF-7jksg52Q10oN3jQiTGRhgMr8NLyONtNhte8ttR1PbjM1A8eULQAfSKCAIBgABxY5lV1UR1UiLU-hVRD9UNQFCinS8KxhY1n2sQQoFwZx9CgbofnI7oxWjClYk5etwWooYSTSMoyk5Gk6QZEFmW0VkRW7DljW-Dd20EoxhNo-9Q2lG4AHoFO0AALYA5FwCA9FEeh4BAAxVTQGRUmMt1VLQYCZEQfQUDoJCIjkGAVP8MyAHUUHoAA3NB9IxOADFEOAxE885cDgKdSSYMAmGMu4DCEMob04QRRH0FYTg2LYfTwVyNhUj5wUHC1enQY0cPLKFK09U4souXBmjhBF+BYcF6C0NS5BkFTXjKXBRAAHV0uAhDQbYykiS5yB+JS4AAYWgJhCHgYD62NJiGBUlAOIgOAImgXrFkKbiYHpRk8HBABGAAGG6boawoxN-OBrqu5oZRm9r1P9LSZB0vSDKMkyUB+IR8GWzaEDlKybLoL6ZH8dSsTwZKIFS+Bqsy85fVypyPnAyCYOOQrczAiCoNg0QyJgCihkw0qgVLXDKpBD0Mu9Or7oKQjMBahhPs67r8F6gahpG-ztoiSayE519lw2rbxt2-bcEO6laRO3imUu267tE+N1yel63qAA):

```ts
// Let's assume http-data Resource mentioned above.

// This doesn't make sense. The type system knows that. We've made an invalid state unrepresentable.
const UninitializedWithData: Resource = {
    state: DataState.Uninitialized,
    data: { x: "This shouldn't be allowed" },  // Correct type error 👍
    error: undefined,
    lastUpdated: -Infinity,
    pendingSince: undefined,
}

// Based on DomainSuggestionState here
// The single interface with union type members is permissive allowing invalid states to be built as we'll see below
interface Resource_FootGun {
    state: DataState;
    data: 'string';
    error: string | null;
    lastUpdated: TimestampMS;
    pendingSince: TimestampMS | undefined;
}

// This doesn't make sense, but the type system is satisfied
const UninitializedWithData_FootGun: Resource_FootGun = {
    state: DataState.Uninitialized,
    data: { x: 'This shouldn\'t be allowed' },  // We shouldn't have data in an uninitialized resource 😕
    error: undefined,
    lastUpdated: -Infinity,
    pendingSince: undefined,
}
```

That's not to say we need to use the `http-data` types verbatim, but I'd like to see:
- The higher level `Resource` types are shared across this level. They could be parameterized on the type of data and error [like in my example](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBDAnmApnA3nASigJgVwGMUo4BfOAMyghDgHIo98APegbgChRJYM5CtAEbAAdihwFiUAM7kqNOo2ZsunJKjgAVUChkwAhuACyAZTgBebChj4oorchQAeABQaUESnAAiBmCgAlADa9KIQAO70ALoAfJwoLLzwKKL4dH6GpoYBGJxwBXAAYgbAADZ2aFb0lKUVTPQANPmFAAqpuGIA5pYMqKKdol1NLQWmRMQyctUyE3oyI4VwAKqiYsAwwAZlwABeeL30+Gtrm9t7eCNknNyiAVC1xNYyEHbEmQbOWo1wAKKxeSW+n8KAAXL5-AZsiCuEtcJDwVo4AAfODHXAoShiPCwwokGhQcG-FFogaY7G4XEFMoGfTLMDwgK4RG6YEmUxUuD9QZdUxiYgskB6Qzskno8niSmca7qJzPV5QYhfXrHADW4Qioh+xKsao1ogBFlGJNcOBebxQHy+2oBADJ+MCAuCPtCAgA6VbrM47faUuCMgzg8VYyXsOD46BBskhnFcjrdPmiAWkjExv1kQLG1GmvQK96Q61-O0OnJgiFZUtu9oDbphiOElMS2PchP8ss6IVssBmciZpbZs15y0F75FuD2zCOssuyslcqVOtQAmIn4toaJ5PBim9rNwHPmxXDwyF-7jksg52Q10oN3jQiTGRhgMr8NLyONtNhte8ttR1PbjM1A8eULQAfSKCAIBgABxY5lV1UR1UiLU-hVRD9UNQFCinS8KxhY1n2sQQoFwZx9CgbofnI7oxWjClYk5etwWooYSTSMoyk5Gk6QZEFmW0VkRW7DljW-Dd20EoxhNo-9Q2lG4AHoFO0AALYA5FwCA9FEeh4BAAxVTQGRUmMt1VLQYCZEQfQUDoJCIjkGAVP8MyAHUUHoAA3NB9IxOADFEOAxE885cDgKdSSYMAmGMu4DCEMob04QRRH0FYTg2LYfTwVyNhUj5wUHC1enQY0cPLKFK09U4souXBmjhBF+BYcF6C0NS5BkFTXjKXBRAAHV0uAhDQbYykiS5yB+JS4AAYWgJhCHgYD62NJiGBUlAOIgOAImgXrFkKbiYHpRk8HBABGAAGG6boawoxN-OBrqu5oZRm9r1P9LSZB0vSDKMkyUB+IR8GWzaEDlKybLoL6ZH8dSsTwZKIFS+Bqsy85fVypyPnAyCYOOQrczAiCoNg0QyJgCihkw0qgVLXDKpBD0Mu9Or7oKQjMBahhPs67r8F6gahpG-ztoiSayE519lw2rbxt2-bcEO6laRO3imUu267tE+N1yel63qAA).
- A few helper functions can help build the different states. The uninitialized state, for example, is always the same. The helper functions seem like they'd make sense for building action creators.
- Use the type system to make invalid states unrepresentable. We should have a union of better looking types.

**Review by sirreal — COMMENTED** [review]
Thanks for starting in this direction. I've left some feedback I hope is helpful 🙂

File: packages/data-stores/src/domain-suggestions/reducer.ts (hunk 4 above)
Comment (simison) [reply packages/data-stores/src/domain-suggestions/reducer.ts:6]: Specifically, packages pulling from `wp-calypso-client` tend to balloon things and make it less independent/more unpredictable.

Preferably packages would pull code only from other packages, so sometimes it means packaging things from the client, or duplicating if it's not worth the effort.

**Comment by simison** [comment]
> Maybe we need to make some errors retryable (network) and others not (non-latin).

I like the idea in general, and at the same time it probably isn't big deal to let queries retry to just keep it simple. After all we were running without error handling even for a while. 😅  Up to you!

File: packages/domain-picker/src/domain-picker/index.tsx (hunk 6 above)
Comment (simison) [reply packages/domain-picker/src/domain-picker/index.tsx:208]: Does the error message come from the API and is translated there already?

File: packages/domain-picker/src/hooks/use-domain-suggestions.ts (hunk 1 above)
Comment (dmsnell) [reply packages/domain-picker/src/hooks/use-domain-suggestions.ts:14]: also this is a mapped type provided by TypeScript so it's bound to confuse people.

```ts
type MyBool = boolean;
type BoolProducer = () => boolean;

// MyBool === ReturnType<BoolProducer>
```

that code works up to the point that `ReturnType` becomes its own concrete type, then who knows - a bunch of errors

**Comment by dmsnell** [comment]
@ciampo thanks for being inspired by `http-data`! just curious - did you consider using `http-data` directly instead of creating these new similar constructs? was there something about it that wasn't serving what you needed, or was there too much code to rewrite in order to move to its declarative interface?

**Comment by yansern** [comment]
> @ciampo thanks for being inspired by `http-data`! just curious - did you consider using `http-data` directly instead of creating these new similar constructs? was there something about it that wasn't serving what you needed, or was there too much code to rewrite in order to move to its declarative interface?

I think the reason is because this domain picker package is also going to be used under Editing Toolkit plugin, pulling it off Calypso could lead to a string of other dependencies to tag along. Might be interesting if `http-data` was a package.

**Comment by sirreal** [comment]
@dmsnell Doesn't `http-data` require Calypso's redux state tree (or some global redux store) to be present? Gutenboarding and WP Admin don't have Calypso state or any global redux store.

**Comment by dmsnell** [comment]
> Doesn't `http-data` require Calypso's redux state tree (or some global redux store) to be present? Gutenboarding and WP Admin don't have Calypso state or any global redux store.

we could adjust it to pull out Calypso. it relies on the `HTTP_REQUEST` middleware to run the requests and it updates a `TICK` when it gets responses back. I didn't realize pulling it out would be a requirement.

I don't think it would be much work. the system is designed to operate with any Redux store but `dispatchRequest` is the single piece that ties it all together. if someone wants to extract that I'd be happy to provide guidance, supervision, and review. for example, if we replaced the Redux store with a `what-wg` `fetch()` or other imperative HTTP API like `@wordpress/apiFetch` then I think we could do that.

File: packages/domain-picker/src/domain-picker/index.tsx (hunk 6 above)
Comment (tjcafferkey) [reply packages/domain-picker/src/domain-picker/index.tsx:208]: For reference it does not look like the error messages are translated from the API already.

**Comment by sirreal** [comment]
> > Doesn't `http-data` require Calypso's redux state tree (or some global redux store) to be present? Gutenboarding and WP Admin don't have Calypso state or any global redux store.
> 
> we could adjust it to pull out Calypso. it relies on the `HTTP_REQUEST` middleware to run the requests and it updates a `TICK` when it gets responses back. I didn't realize pulling it out would be a requirement.
> 
> I don't think it would be much work. the system is designed to operate with any Redux store but `dispatchRequest` is the single piece that ties it all together. if someone wants to extract that I'd be happy to provide guidance, supervision, and review. for example, if we replaced the Redux store with a `what-wg` `fetch()` or other imperative HTTP API like `@wordpress/apiFetch` then I think we could do that.

I think those changes would make direct usage of `http-data` for this work viable, right now it isn't. I'm not working on this project myself right now, so it would be up to @Automattic/luna folks to decide whether they'd like to move in that direction or not.

My hopes for this work —which I've probably poorly articulated— was to build some better foundations for @automattic/data-stores in general, more at the framework level and not at the level of a particular piece of state. That's a larger refactor similar to some of the work that's been done here, but it may not be something that the team is comfortable taking on at this point.

I didn't get these data stores into the shape I wanted before I moved away from the project 😞

**Comment by yansern** [comment]
Rebased!

File: packages/data-stores/src/domain-suggestions/types.ts [hunk 8]
```diff
@@ -183,3 +188,32 @@ export interface DomainAvailability {
...
+	/**
+	 * Timestamp from last updated attempt
+	 */
+	lastUpdated: TimestampMS;
+
+	/**
+	 * Pending timestamp
+	 */
+	pendingSince: TimestampMS | undefined;
+}
```
Comment (yansern) [inline packages/data-stores/src/domain-suggestions/types.ts:219]: An idea for the future would be something along the line of:
```
interface DomainSuggestionState implements HttpDataState {
    data: Record< DomainSuggestion[] >
}
```

File: packages/domain-picker/src/hooks/use-domain-suggestions.ts [hunk 9]
```diff
@@ -1,35 +1,64 @@
...
  * Internal dependencies
  */
 import { DOMAIN_SUGGESTIONS_STORE, DOMAIN_SEARCH_DEBOUNCE_INTERVAL } from '../constants';
 
+type DomainSuggestionsResult = {
+	allDomainSuggestions: DomainSuggestion[] | undefined;
+	errorMessage: string | null;
+	state: DataStatus;
+	retryRequest: () => void;
+};
```
Comment (yansern) [inline packages/domain-picker/src/hooks/use-domain-suggestions.ts:19]: IMHO, this feels too similar to `DomainSuggestionState` and it feels awkward to have `retryRequest()` wedged in here. Would be nice to think about and establish a best practice around how retrying/invalidating data is done in the future.

File: packages/domain-picker/src/hooks/use-domain-suggestions.ts [hunk 10]
```diff
@@ -1,35 +1,64 @@
...
 	domainCategory?: string,
 	locale = 'en'
-) {
+): DomainSuggestionsResult | undefined {
 	const [ domainSearch ] = useDebounce( searchTerm, DOMAIN_SEARCH_DEBOUNCE_INTERVAL );
 
+	// eslint-disable-next-line @typescript-eslint/ban-ts-ignore
+	// @ts-ignore
+	// Missing types for invalidateResolutionForStoreSelector
+	// (see packages/data/src/namespace-store/metadata/actions.js#L57)
```
Comment (yansern) [inline packages/domain-picker/src/hooks/use-domain-suggestions.ts:32]: Note to self: This is from Gutenberg package.

**Review by yansern — APPROVED** [review]
This is a foray into an unknown, I'd say a job well done to @ciampo & @tjcafferkey, and big thanks to everyone up in the comments for giving valuable feedback/insights. 

Functionality-wise, all works as expected. Code-wise, we all have differences in opinion on what's the best practice for this and that, I'm sure it'll take shape eventually, this is a good step forward.

PR approved!

**Comment by dmsnell** [comment]
Can we schedule a follow-up to this PR where we address some of the data concerns? I was reaching out in Slack so I didn't have a message about it here but I was hoping that we could pull back the abstractions at a minimum and leave things a little more concrete/duplicated/imperative in this PR.

That is, while it would be great to tackle making `@wordpress/apiFetch` and `http-data` work well together outside of Calypso, it'd probably still be best not to recreate 90% of them in a specific module. Better to leave things a little "worse off" in the specific case than to duplicate the generalized case in a subtly-different manner on a one-off feature.
