### PR TITLE
Plugins Browser: Add missing info in the plugin browser item.

### LINKED ISSUE #58319: Screen Options missing for the new Plugins browser page.
### Quick summary

We recently introduced a new update that directs `Plugins > Add New` destination to point to Calypso Plugins page for Atomic sites.

Ref: p7DVsv-d0A-p2

The Calypso plugins search page lacks details like active installation number, and if it's compatible or untested, or reviews written by other users on clicking plugin details page.

The new Calypso Plugins page is surely a downgrade for those who are used to the WP Admin plugin browser page. We have an older report here: #43332

An easy way to fix this gap is to introduce the `Screen Options` for the new Calypso page so that users can easily switch to WP Admin page. 

### Steps to reproduce

1. Open an atomic site.
2. Go to `Plugins > Add new` and search for a plugin.
3. Search results lack lots of details that are available on WP Admin plugin search page.
on

### What you expected to happen

The Calypso plugin search page should include all necessary details that were present WP Admin page.

### What actually happened

The Calypso plugin search page lacks crucial details and makes it difficult for users to browse the plugins.

### Context

User report: 4530120-zen

### Operating System

_No response_

### Browser

_No response_

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

_No response_

### Other notes

_No response_

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, difficult to implement

### Workaround details

Users have to remember or bookmark the wp-admin plugin search page: `wp-admin/plugin-install.php`.

An easy alternative that we can implement is to add the Screen Options to switch to Classic view on the new Plugins page.

### PR DESCRIPTION
**Pull request by WBerredo**
#### Changes proposed in this Pull Request
Addition of the following information on the Plugins Browser Item:

- [x] Last updated
- [x] Rating
- [x] Active Installs
- [x] Untested version warning

#### Testing instructions
* Go to `/plugins` page
* Confirm each plugin card has last updated, rating, and active install informations. Ex:

Screen Shot 2021-12-06 at 14 58 37

* Go to `/plugins` page
* Search for a term where will be showed plugins with untested versions. ex: application
* Check if the warning is being properly showed

Screen Shot 2021-12-08 at 11 20 45

---

Fixes  #58319

### CODE REVIEW

File: client/my-sites/plugins/plugins-browser-item/index.jsx [hunk 1]
```diff
@@ -16,137 +19,180 @@ import './style.scss';
...
+					<div className="plugins-browser-item__title">{ plugin.name }</div>
+					{ variant === PluginsBrowserElementVariant.Extended && (
+						<>
+							<div className="plugins-browser-item__author">
+								{ translate( 'by ' ) }
+								<span className="plugins-browser-item__author-name">{ plugin.author_name }</span>
+							</div>
+							{ dateFromNow && (
+								<div className="plugins-browser-item__last-updated">
+									{ translate( 'Last updated ' ) }
```
Comment (a8ci18n) [inline client/my-sites/plugins/plugins-browser-item/index.jsx]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **144** times:
`translate( 'Last Updated:' )` *ES Score: 9*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/enhance-plugins-browser-item)

**Comment by WBerredo** [comment]
@Saxon I have added the "info outline" icons instead of the warning one because I think it gets closer to the mock idea. Let me know your opinion: 

|info icon (current) | warning icon|
|-------|------|
|Screen Shot 2021-12-08 at 11 28 43|Screen Shot 2021-12-08 at 11 29 24|

You can see all the icon options here: https://developer.wordpress.org/resource/dashicons

File: client/my-sites/plugins/plugins-browser-item/index.jsx [hunk 2]
```diff
@@ -1,152 +1,217 @@
...
 import classnames from 'classnames';
-import { localize } from 'i18n-calypso';
-import { flowRight as compose, includes } from 'lodash';
-import { Component } from 'react';
-import { connect } from 'react-redux';
+import { useTranslate, getLocaleSlug } from 'i18n-calypso';
+import { includes } from 'lodash';
+import { useMemo, useCallback } from 'react';
+import { useSelector } from 'react-redux';
+import semverGt from 'semver/functions/gt';
```
Comment (cpapazoglou) [inline client/my-sites/plugins/plugins-browser-item/index.jsx]: Can `version_compare` 
https://github.com/Automattic/wp-calypso/blob/ea33197d3e2c9acd0b1cf674af577ed98114c98f/client/lib/version-compare/index.js#L7

accomplish the same thing without introducing a new dependency?

File: client/my-sites/plugins/plugins-browser-item/index.jsx [hunk 3]
```diff
@@ -1,152 +1,217 @@
...
+					<div className="plugins-browser-item__additional-info">
+						{ !! plugin.rating && (
+							<div className="plugins-browser-item__ratings">
+								<PluginRatings
+									rating={ plugin.rating }
+									inlineNumRatings={
+										plugin.rating && Number.isInteger( plugin.num_ratings )
+											? plugin.num_ratings.toLocaleString( getLocaleSlug() )
+											: null
+									}
```
Comment (cpapazoglou) [inline client/my-sites/plugins/plugins-browser-item/index.jsx]: Since this logic can be handled inside `PluginRatings` can we move it there?
Also, since `num_ratings` already exist, should `inlineNumRatings` be replaced by a boolean `inlineNumRatings`?

File: client/my-sites/plugins/plugins-browser-item/index.jsx (hunk 2 above)
Comment (WBerredo) [reply client/my-sites/plugins/plugins-browser-item/index.jsx]: That is right, thanks for pointing it.

fixed https://github.com/Automattic/wp-calypso/pull/58866/commits/d2c00f0f0a3036b0c3f0dc9d65b8c5298b3df09d

File: client/my-sites/plugins/plugin-ratings/index.jsx [hunk 4]
```diff
@@ -105,7 +113,10 @@ class PluginRatings extends Component {
 			<div className="plugin-ratings">
 				<div className="plugin-ratings__rating-stars">
 					<Rating rating={ rating } />
-					<span className="plugin-ratings__number">{ rating / 20 }</span>
+					{ inlineNumRatings && (
+						<span className="plugin-ratings__num-ratings">({ inlineNumRatings })</span>
+					) }
+					{ ! hideRatingValue && <span className="plugin-ratings__number">{ rating / 20 }</span> }
```
Comment (cpapazoglou) [inline client/my-sites/plugins/plugin-ratings/index.jsx]: Can we increase consistency by replacing `hideRatingValue` with `hideRatingNumber`?

File: client/my-sites/plugins/plugins-browser-item/index.jsx [hunk 5]
```diff
@@ -1,152 +1,217 @@
...
+					) }
+					<div className="plugins-browser-item__description">{ plugin.short_description }</div>
+				</div>
+				{ isUntestedVersion && (
+					<div className="plugins-browser-item__untested-notice">
+						<Icon size={ 20 } icon={ info } />
+						<span className="plugins-browser-item__untested-text">
+							{ translate( 'Untested with your version of WordPress' ) }
+						</span>
+					</div>
```
Comment (cpapazoglou) [inline client/my-sites/plugins/plugins-browser-item/index.jsx:135]: Have you considered reusing the `notice` component?
https://github.com/Automattic/wp-calypso/blob/f2e6f88ae65c8571bbac21b284c29b48ec987598/client/components/notice/index.jsx#L29

File: client/my-sites/plugins/plugins-browser-item/index.jsx [hunk 6]
```diff
@@ -1,152 +1,217 @@
...
 		}
 
-		if ( ! this.props.site ) {
+		if ( ! site ) {
 			return false;
 		}
 
-		return ! this.props.isJetpackSite && includes( PREINSTALLED_PLUGINS, this.props.plugin.name );
-	}
+		return ! isJetpack && includes( PREINSTALLED_PLUGINS, plugin.name );
```
Comment (cpapazoglou) [inline client/my-sites/plugins/plugins-browser-item/index.jsx]: Since we want to refactor away loadash, would `PREINSTALLED_PLUGINS.include( plugin.name )` work here?

File: client/my-sites/plugins/plugins-browser-item/index.jsx [hunk 7]
```diff
@@ -1,152 +1,217 @@
...
 						) }
-						<div className="plugins-browser-item__description">{ plugin.short_description }</div>
 					</div>
-					{ variant === PluginsBrowserElementVariant.Extended && this.renderInstalledInOrPricing() }
-				</a>
-				{ this.renderUpgradeButton() }
-			</li>
+				</div>
+			</a>
+			<UpgradeButton plugin={ plugin } />
```
Comment (cpapazoglou) [inline client/my-sites/plugins/plugins-browser-item/index.jsx]: It seems we can safely entirely remove the `UpgradeButton` since it was used for features not includes in your plan https://github.com/Automattic/wp-calypso/pull/18323/commits/4db1944654ecf1c6edf6136e6475b9418b5a2a34 and not for plugins.

File: client/my-sites/plugins/plugins-browser-item/style.scss [hunk 8]
```diff
@@ -123,6 +153,12 @@
 	}
 }
 
+.plugins-browser-item__footer {
+	margin-top: auto;
+	display: flex;
+	justify-content: space-between;
+}
+
```
Comment (cpapazoglou) [inline client/my-sites/plugins/plugins-browser-item/style.scss:161]: We should also remove the `UpgradeButton` CSS

**Review by cpapazoglou — CHANGES_REQUESTED** [review]
Thanks for refactoring to a functional component Wesley 👏👏👏.
Generally seems good, I have left some feedback where is room for improvement.

It seems though we have a regression:
Plugins doesn't appear as installed
|Before | After|
|-------|------|
|SS 2021-12-08 at 18 05 02|SS 2021-12-08 at 18 05 13|

File: client/my-sites/plugins/plugins-browser-item/style.scss (hunk 8 above)
Comment (WBerredo) [reply client/my-sites/plugins/plugins-browser-item/style.scss:161]: done 8284966f3a808426e9a78433dd75c7ee74df16d7

File: client/my-sites/plugins/plugins-browser-item/index.jsx (hunk 7 above)
Comment (WBerredo) [reply client/my-sites/plugins/plugins-browser-item/index.jsx]: done 8284966f3a808426e9a78433dd75c7ee74df16d7

File: client/my-sites/plugins/plugins-browser-item/index.jsx (hunk 6 above)
Comment (WBerredo) [reply client/my-sites/plugins/plugins-browser-item/index.jsx]: done 8284966f3a808426e9a78433dd75c7ee74df16d7

File: client/my-sites/plugins/plugin-ratings/index.jsx (hunk 4 above)
Comment (WBerredo) [reply client/my-sites/plugins/plugin-ratings/index.jsx]: done 8284966f3a808426e9a78433dd75c7ee74df16d7

File: client/my-sites/plugins/plugins-browser-item/index.jsx (hunk 3 above)
Comment (WBerredo) [reply client/my-sites/plugins/plugins-browser-item/index.jsx]: done 8284966f3a808426e9a78433dd75c7ee74df16d7

File: client/my-sites/plugins/plugins-browser-item/index.jsx (hunk 5 above)
Comment (WBerredo) [reply client/my-sites/plugins/plugins-browser-item/index.jsx:135]: Tried it quickly here, but it seems very different from what we have on the mock.

Screen Shot 2021-12-08 at 15 56 00

**Comment by WBerredo** [comment]
> It seems though we have a regression:
Plugins doesn't appear as installed

Fixed at 8284966f3a808426e9a78433dd75c7ee74df16d7

File: client/my-sites/plugins/plugins-browser-item/index.jsx (hunk 5 above)
Comment (cpapazoglou) [reply client/my-sites/plugins/plugins-browser-item/index.jsx:135]: Cool, it seems that the code added is less than the code that we would have to override.

**Review by cpapazoglou — APPROVED** [review]
LGTM! 🚢

File: client/my-sites/plugins/plugins-browser-item/index.jsx [hunk 9]
```diff
@@ -1,152 +1,202 @@
...
+						<>
 							<div className="plugins-browser-item__author">
 								{ translate( 'by ' ) }
 								<span className="plugins-browser-item__author-name">{ plugin.author_name }</span>
 							</div>
+
+							<div className="plugins-browser-item__last-updated">
+								{ dateFromNow && (
+									<>
+										{ translate( 'Last updated ' ) }
```
Comment (a8ci18n) [inline client/my-sites/plugins/plugins-browser-item/index.jsx:118]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **144** times:
`translate( 'Last Updated:' )` *ES Score: 9*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/enhance-plugins-browser-item)

File: client/my-sites/plugins/plugin-ratings/index.jsx [hunk 10]
```diff
@@ -105,9 +113,18 @@ class PluginRatings extends Component {
 			<div className="plugin-ratings">
 				<div className="plugin-ratings__rating-stars">
 					<Rating rating={ rating } />
-					<span className="plugin-ratings__number">{ rating / 20 }</span>
+					{ inlineNumRatings && numRatings && (
+						<span className="plugin-ratings__num-ratings">
+							(
+							{ rating && Number.isInteger( numRatings )
```
Comment (tyxla) [inline client/my-sites/plugins/plugin-ratings/index.jsx:119]: Noting that the `rating &&` check here is unnecessary because we already have a check that ensures `rating` is not falsy on L107.

Comment (WBerredo) [reply client/my-sites/plugins/plugin-ratings/index.jsx:119]: Thanks for pointing it. 

I created a follow-up PR with this change #59119 59119

Comment (tyxla) [reply client/my-sites/plugins/plugin-ratings/index.jsx:119]: It wasn't urgent, but thanks for the super swift turnaround 🚀
