### PR TITLE
Fix setting dates in Site Logs view

### LINKED ISSUE #79923: Atomic: Incorrect hour picker on Site Logs
### Quick summary

The hour picker on Tools > Site Logs does not reflect the selected hour. It appears the picker shows time in the site's timezone but adds to the field in UTC which is confusing.

### Steps to reproduce

1. Make sure the test site setting is not in UTC 0:00 timezone
2. On the AT site, go to Tools > Site Logs.
3. Click on the calendar icon and select the hour.
4. You will notice that the hour entered in the field is not what you selected.

### What you expected to happen

The hour selected in the picker should be added to the input.

### What actually happened

Screen recording: 

https://github.com/Automattic/wp-calypso/assets/33957570/c12bb57e-5567-49d5-9745-508eb08a0e39

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

User interaction: 6584158-zd-woothemes

### PR DESCRIPTION
**Pull request by p-jackson**
Fixes https://github.com/Automattic/wp-calypso/issues/79923

## Proposed Changes

* Moment objects are annoyingly mutable. Calling moment methods to display dates correctly was unintentionally modifying the components props.
* We ensured dates were displayed in the site's timezone, but we failed to recognise that the new dates supplied by the user would also be in the site's timezone.
* I didn't think it made a lot of sense to set the `value` prop in one timezone and then have the `onChange` callback return a different timezone. So now timestamps round-trip using the same timezone, and that timezone can be independent of the display timezone.

## Testing Instructions

Follow reproduction steps in https://github.com/Automattic/wp-calypso/issues/79923

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: client/my-sites/site-logs/components/site-logs-toolbar/date-time-picker.tsx [hunk 1]
```diff
@@ -21,20 +25,31 @@ export function DateTimePicker( { value, onChange, gmtOffset = 0, max, min, ...r
 	const moment = useLocalizedMoment();
 
 	const onDateChange = ( event: React.ChangeEvent< HTMLInputElement > ) => {
-		const newDate = moment( event.currentTarget.value, INPUT_DATE_FORMAT );
+		const newDate = moment( event.currentTarget.value, INPUT_DATE_FORMAT )
+			.utcOffset( gmtOffset * 60, true )
+			.utcOffset( value.utcOffset() );
```
Comment (zaguiini) [inline client/my-sites/site-logs/components/site-logs-toolbar/date-time-picker.tsx:30]: Why are we calling `utcOffset` twice here? Based on `value` definition below, shouldn't the second chaining call be `format` instead?

**Review by vykes-mac — APPROVED** [review]
Issue is fixed in my testing.

File: client/my-sites/site-logs/components/site-logs-toolbar/date-time-picker.tsx (hunk 1 above)
Comment (vykes-mac) [reply client/my-sites/site-logs/components/site-logs-toolbar/date-time-picker.tsx:30]: I think the second `.utcOffset` is necessary to convert the moment date back to the users timezone to return to the parent component. `.format` it seems is only used for display purpose on the input fields but doesn't have an effect on the timezone.

Comment (p-jackson) [reply client/my-sites/site-logs/components/site-logs-toolbar/date-time-picker.tsx:30]: Below we're using `.format()` to convert the moment object into a string, because the interface for the `<input>` is string based (and it has to be in a very specific format).

The first `.utcOffset()` has two arguments, notice the `true` as the second argument. Since the `<input>` doesn't have any timezone information it's telling the moment object that it should interpret itself as being in the `gmtOffset` timezone.

The second call to `.utcOffset()` doesn't have the second argument, and it means that the moment object should change it's internal representation to `value`'s timezone.
