### PR TITLE
Sites Management Page: Ignore match location using fuzzy search

### LINKED ISSUE #66296: Sites Management Page: fuzzy search does not find "wpcomstaging" sites
For some reason searching for `staging` isn't finding `wpcomstaging` sites. It could just be a bug with Atomic sites, or it could be that there are a number of search terms that don't work and this is just one of them.

#### Steps to reproduce

1. Log into an account where you have some `*.wpcomstaging.com` staging sites
2. Type `staging` into the browser's **cmd+f*** search
3. Confirm that your `*.wpcomstaging.com` sites are on the page
4. Clear the browser's search
5. Type `staging` into the **fuzzy search**

#### What I expected

My atomic test sites should appear in the filtered list

#### What I saw

They don't appear!

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #66296

## Proposed Changes

Ignores match location by default when using fuzzy search.

**Before,** a search would fail if the query didn't match within the first 8 characters of the search string:

image

https://user-images.githubusercontent.com/36432/183112254-ceaa2839-0b35-4535-9818-cd5ab5110f5b.mp4

**After,** a search is successful when the query falls anywhere within the search string:

image

https://user-images.githubusercontent.com/36432/183112067-e29ee96c-ab14-4abd-8b17-08499771bf95.mp4

## Testing Instructions

1. Navigate to `/sites-dashboard`.
2. Perform a search where your search string is in the middle of the matching string.
3. See the results you expect to see.

### CODE REVIEW

**Review by zaguiini — APPROVED** [review]
Wow, that's some nasty behavior 🤔 Glad it's fixed!

**Comment by p-jackson** [comment]
:phew: glad you figured that one out :)

File: packages/search/src/use-fuzzy-search.ts [hunk 1]
```diff
@@ -4,6 +4,7 @@ import { useMemo } from 'react';
 const defaultOptions = {
 	threshold: 0.4,
 	distance: 20,
```
Comment (wojtekn) [inline packages/search/src/use-fuzzy-search.ts:6]: @danielbachhuber I was reviewing https://github.com/Automattic/wp-calypso/issues/66248, and I found out that when we use `ignoreLocation`, it ignores the `distance`. In this case, it makes sense to remove `distance` to avoid confusion.

Comment (danielbachhuber) [reply packages/search/src/use-fuzzy-search.ts:6]: @wojtekn Sounds good! Created #66342
