### PR TITLE
Use cards and section headers for app download page

### LINKED ISSUE #8693: Me: "Get Apps" layout is hard to read on small screens
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/me/ with a phone or tablet
2. Click on "Get Apps"
#### What I expected

Readable layout.
#### What happened instead

Text is too wide in some places, not flush left (centered?), and in some cases doesn't have enough padding or margin from the sides of the viewport.
#### Browser / OS version

I tested with Chrome on Android 7.0 (Nexus 6P).
#### Screenshot / Video

Here are screenshots from Chrome on Mac (sized down using dev tools):

#### Context / Source
# dogfooding wpcalypso on an Android phone.

### PR DESCRIPTION
**Pull request by dmsnell**
Resolves #8693
See #9017

Code import from the work @jchimienti89 did with some fixes to get the
PR working without error. Previously in #9017 the change in export
format needed to be matched with a change in `require()` to
`require().default`.

**Before/After**
mobilelayout

cc: @jasmussen @folletto

### CODE REVIEW

File: client/me/get-apps/index.jsx [hunk 1]
```diff
@@ -1,82 +1,99 @@
...
+		<Card className="get-apps__desktop">
 
-	displayName: 'GetApps',
+			<section className="get-apps__app">
+				<div className="get-apps__app-icon">
+					<img src="/calypso/images/me/get-apps-osx.svg" alt={ translate( 'Mac' ) } width="96" height="96" />
+				</div>
+				<p><strong>{ translate( 'Mac' ) }</strong><br />
+				{ translate( 'Requires 10.11 or newer' ) }</p>
+				<Button href="https://apps.wordpress.com/d/osx?ref=getapps">{ translate( 'Download', { context: 'verb' } ) }</Button>
```
Comment (a8ci18n) [inline client/me/get-apps/index.jsx]: Hi! I've found a possible matching string that has already been translated **6** times:
`translate( 'download' )` *ES Score: 19*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/8693-mobile-layout-get-apps)

Help me improve these suggestions: react with :thumbsdown: if the suggestion doesn't make any sense, or with :thumbsup: if it's a particularly good one (even if not implemented).

:information_source: This string already exists without a **context**. Only add a context if the meaning of the string is very specific.
