### PR TITLE
Checkout: US 9 digit zip code validation/formatting

### LINKED ISSUE #56007: Checkout: US 9 digit zip code validation/formatting.
### Steps to reproduce the behavior

While testing another PR, I noticed that a US 9 digit zipcode sans hyphen does not get correctly reformatted like some non-US zip codes do (BR, CA, GB, IE, JP, KY, NL,PL, PT, SE). 

1. Add a plan or domain to the cart.
2. Enter a 9 digit US zip code without the hyphen (100195401 as an example); and click continue. It will notify that it's invalid.
3. You can enter the zip code with the hyphen (10019-5401) and it will validate with no issues.

Screen Shot 2021-09-03 at 5 16 19 PM

After a bit of investigation, it looks like this might be responsible for this issue: https://github.com/Automattic/wp-calypso/blob/trunk/packages/wpcom-checkout/src/postal-code.ts

### PR DESCRIPTION
**Pull request by chrisfromthelc**
#### Changes proposed in this Pull Request

The changes in this PR add a formatter that correctly handles 9 digit US zip codes, removing the need to manually insert a hyphen, and will still fail incorrect zip codes (anything not 5 or 9 digits when US is the selected country).

#### Testing instructions

*Correct zip codes*
1. Add a plan or domain to the cart.
2. Enter a 9 digit US zip code without the hyphen (100195401 as an example); and click continue. It should auto-format to add the hyphen and accept the correctly formatted zip code.

*Incorrect zip codes*
1. Add a plan or domain to the cart.
2. Enter any non 5 or 9 digit US zip code ; and click continue. It should reject it when clicking continue.

Related to #56007

### CODE REVIEW

File: packages/wpcom-checkout/src/postal-code.ts [hunk 1]
```diff
@@ -76,6 +76,17 @@ const twoPartPostalCodes: Record<
 		delimiter: ' ',
 		partLength: 3,
 	},
+	US: {
+		length: [ 9 ],
+		delimiter: '-',
+		formatter: ( postalCodeInput: string, delimiter: string ) => {
```
Comment (amustaque97) [inline packages/wpcom-checkout/src/postal-code.ts]: Thank you for the PR. One doubt here! Why do we need to write formatter? Something like this `partLength: 5` should work out of the box. It will reduce LOC as well.

Function `defaultFormatter` is also doing same work
https://github.com/Automattic/wp-calypso/blob/ccde1b0b9b44c993d6de513b60ab38458832cf71/packages/wpcom-checkout/src/postal-code.ts#L15-L17

Thanks

Comment (chrisfromthelc) [reply packages/wpcom-checkout/src/postal-code.ts]: @amustaque97 Thanks for pointing this out. I've updated this to use `partLength`.

**Review by sirbrillig — APPROVED** [review]
Looks good to me! When testing, however, I noticed one possible issue which is really a separate thing: the autoformatting runs on the tax contact fields:

Screen Shot 2021-09-07 at 6 24 58 PM

But it does not run on the Domain contact fields:

Screen Shot 2021-09-07 at 6 27 01 PM

My guess is that it might not run on the G Suite contact fields either, but I didn't try them. 

I think that this is because the auto-formatting was only ever applied to the tax fields here: https://github.com/Automattic/wp-calypso/blob/3194533e2eb93f3fa3b853090538c957e6c24f5b/client/my-sites/checkout/composite-checkout/components/tax-fields.tsx#L59

I created a separate issue for that in https://github.com/Automattic/wp-calypso/issues/56088

**Comment by chrisfromthelc** [comment]
> Looks good to me! When testing, however, I noticed one possible issue which is really a separate thing: the autoformatting runs on the tax contact fields:
> 
> 
> But it does not run on the Domain contact fields:
> 
> 
> My guess is that it might not run on the G Suite contact fields either, but I didn't try them.
> 
> I think that this is because the auto-formatting was only ever applied to the tax fields here:
> 
> https://github.com/Automattic/wp-calypso/blob/3194533e2eb93f3fa3b853090538c957e6c24f5b/client/my-sites/checkout/composite-checkout/components/tax-fields.tsx#L59
> 
> I created a separate issue for that in #56088

That would make sense. I only noticed the original issue on the main billing zip code. I'll grab this new issue and run with it as well.
