### PR TITLE
Checklist: start site setup task does not make checklist incomplete on its own

### LINKED ISSUE #51311: Site setup complete; crashing customer home after launch
Customer home checklist crashes after site launch for sites without menu.

### Steps to reproduce the behavior

1. Go to wordpress.com/new/
2. Enter a site name
3. Pick a free domain
4. Pick a design with the blank canvas theme, one of these will do:

    Screenshot 2021-03-23 at 14 44 50

5. When in the editor, hit "launch"

    Screenshot 2021-03-23 at 14 45 25

6. When at confirmation, press "back home"

    Screenshot 2021-03-23 at 14 45 55

7. At customer home, press Show site setup

    Screenshot 2021-03-23 at 14 46 11

8. Observe completed site list appear for a moment, and then the whole page to crash with error in console:

    Screenshot 2021-03-23 at 14 41 38

    Something here:

    Screenshot 2021-03-23 at 14 41 55

    See https://github.com/Automattic/wp-calypso/search?q=START_SITE_SETUP

### PR DESCRIPTION
**Pull request by creativecoder**
#### Changes proposed in this Pull Request

Two small optimizations to the site checklist

- Prevent a js error after completing the last task (and there's not a next incomplete task to move to)
- Prevent the site setup started task from flagging a checklist as incomplete. This task is autocompleted when viewed, so there's no reason to see the entire checklist if this is the only task that's incomplete.

This companion diff is not required to test this change, but is directly related: D59219-code

Related to #51311

#### Testing instructions

This is a bit difficult to test, but one practical result you can see is that after following the flow to reproduce #51311, and launching a site, you will see a slightly different launched celebration card on My Home. The secondary action will display "Dismiss," rather than "Skip site setup".

Screen Shot 2021-03-24 at 14 09 36

### CODE REVIEW

**Comment by jeyip** [comment]
I'm following [these instructions](https://github.com/Automattic/wp-calypso/issues/51311) in a local calypso dev environment, but at step 6, there is no opportunity to click the "Back home" hyperlink.

Screen Shot 2021-04-05 at 11 48 26 PM

I end up navigating back to the home screen manually to see the launch celebration card, but there's odd behavior there as well. If I use the back button in the browser, I'll be redirected to the home screen and see the celebration card with the "Dismiss" secondary action. If I refresh the "Hooray" page instead of using the back button, I'll still be redirected to the home screen but see the "Skip site setup" secondary action. Not entirely sure if this is an oddity with my dev environment or whether or not it needs to be addressed 🤔 Curious what your thoughts are Grant.

**Comment by jeyip** [comment]
I'm following [these instructions](https://github.com/Automattic/wp-calypso/issues/51311) in a local calypso dev environment, but at step 6, there is no opportunity to click the "Back home" hyperlink.

Screen Shot 2021-04-05 at 11 48 26 PM

Because of this, I'm manually navigating back to the home screen to inspect the launch celebration card. I'm also seeing odd behavior there as well. If I use the back button in the browser, I'll be redirected to the home screen and see the "Dismiss" secondary action. If I refresh the "Hooray" page instead of using the back button, I'll still be redirected to the home screen but see the "Skip site setup" secondary action.

**Comment by creativecoder** [comment]
> but at step 6, there is no opportunity to click the "Back home" hyperlink.

@jeyip It looks like that's an unrelated regression.

> I end up navigating back to the home screen manually to see the launch celebration card, but there's odd behavior there as well. If I use the back button in the browser, I'll be redirected to the home screen and see the celebration card with the "Dismiss" secondary action. If I refresh the "Hooray" page instead of using the back button, I'll still be redirected to the home screen but see the "Skip site setup" secondary action. Not entirely sure if this is an oddity with my dev environment or whether or not it needs to be addressed

I'm not sure either! It's very possible there's something else affecting if Calypso detects the checklist is complete or not in the launch card, with these alternative flows.

The easiest thing to do is probably waiting until the regression is fixed, then retesting this (very minor) change.

**Comment by jeyip** [comment]
> The easiest thing to do is probably waiting until the regression is fixed, then retesting this (very minor) change.

Sounds good 👍

**Comment by razvanpapadopol** [comment]
There is a proposed fix (https://github.com/Automattic/wp-calypso/pull/51741) for the regression mentioned in https://github.com/Automattic/wp-calypso/pull/51324#issuecomment-813880256. We'll ping current gardeners to rebase and re-test after it's merged.

**Comment by ciampo** [comment]
> There is a proposed fix (#51741) for the regression mentioned in [#51324 (comment)](https://github.com/Automattic/wp-calypso/pull/51324#issuecomment-813880256). We'll ping current gardeners to rebase and re-test after it's merged.

#51741 was merged and this PR rebased

**Review by ciampo — APPROVED** [review]
Tests well as per instructions!

@creativecoder, I just a left a [comment](https://github.com/Automattic/wp-calypso/pull/51324#discussion_r611896917), but after addressing it feel free to 🚢 

Screenshot 2021-04-12 at 21 26 20

File: client/state/selectors/is-site-checklist-complete.js [hunk 1]
```diff
@@ -52,6 +52,11 @@ export default function isSiteChecklistComplete( state, siteId ) {
 			return true;
 		}
 
+		// Starting site setup autocompletes, so it shouldn't cause an incomplete checklist.
+		if ( CHECKLIST_KNOWN_TASKS.START_SITE_SETUP === task.id ) {
+			return true;
+		}
+
```
Comment (ciampo) [inline client/state/selectors/is-site-checklist-complete.js:61]: A bit of a nit, but before merging could you update this function's JS docs to bring it up to date with the code changes?

**Review by jeyip — COMMENTED** [review]
## Testing
### Behavior
- [x] Celebration card secondary action is "Dismiss" instead of "Skip site setup"

### Browsers
- [x] Chrome
- [x] Firefox
- [x] Edge
- [ ] ~Safari~

**Notes:**
- If the page renders slowly enough, "Skip site setup" is flashed on the screen momentarily before "Dismiss" replaces it
- I tried testing these update in Safari, but, even after following [these instructions](https://github.com/Automattic/wp-calypso/issues/49237#issuecomment-783375234) to authenticate myself as a user, I couldn't make it through the onboarding process. It would perpetually ask me to log in in the final step before site creation. I still feel comfortable moving forward. If things don't work as expected in Safari, this seems like a low-profile issue that we can roll back pretty easily.

+1 from me when we resolve discussions about "Skip site setup" flashing on the screen. (I'm comfortable handling this in a follow-up)

File: client/state/selectors/is-site-checklist-complete.js (hunk 1 above)
Comment (creativecoder) [reply client/state/selectors/is-site-checklist-complete.js:61]: Done, thanks for pointing that out!
