### PR TITLE
VideoPress: Handle dropped files into the block editor

### LINKED ISSUE #30883: VideoPress: Dragging a video into the block editor does not upload a new media item
Props to @arunsathiya 

#### Steps to reproduce
* Go to `https://wordpress.com/block-editor/post` while proxied.
* Select a site under a Premium plan.
* Drag and drop a video file to the editor.

#### What I expected
The video to be uploaded and the block to render the VideoPress player.

#### What happened instead
The video is not uploaded (checked by going to My site > Media) and the block always render the uploading placeholder.

Checking the performed networks calls, I notice some differences from uploading the video by inserting first a video block: 
* There is no `POST` request to the `media` API endpoint.
* Instead, there is an `OPTIONS` request to the `media` API endpoint.
screen shot 2019-02-19 at 15 56 20

### PR DESCRIPTION
**Pull request by mmtr**
#### Changes proposed in this Pull Request

The core video block relies on `componentDidMount` for uploading a new media item when a file is dropped into the editor ([#](https://github.com/WordPress/gutenberg/blob/929afdd88a0e2855048ca2c098cbdb623cf27a4a/packages/block-library/src/video/index.js#L92-L94), [#](https://github.com/WordPress/gutenberg/blob/929afdd88a0e2855048ca2c098cbdb623cf27a4a/packages/block-library/src/video/edit.js#L58-L73)).

But our custom VideoPress-enhanced video block overwrites that method suppressing the upload behavior ([#](https://github.com/Automattic/wp-calypso/blob/8553d598d488597ebc61be912ca8a3c29b3602e3/client/gutenberg/extensions/videopress/edit.js#L33-L36)).

This PRs defines a new transformation to the VideoPress-enhanced video block to ensure that the file is uploaded.

Fixes #30883.

#### Testing instructions

* Select an environment:
  * Gutenlypso.  
    * Start Calypso with Calypsoify Iframe disabled: `DISABLE_FEATURES=calypsoify/iframe npm start`.
    * Go to `/block-editor`.
    * Select a site under a premium/business plan.
  * Jetpack.
    * [Create a new JN site using the extensions from this branch](https://jurassic.ninja/create?gutenpack&calypsobranch=fix/videopress-gutenberg-drag-drop&jetpack-beta&shortlived&wp-debug-log).
    * Connect to WP.com using a premium/business subscription.
    * Go to Settings → Jetpack Constants in the site’s wp-admin and set `JETPACK_BETA_BLOCKS` to true.
    * Go to Jetpack → Settings and activate the VideoPress module (by enabling the "Enable high-speed, ad-free video player" option).
    * Go to Posts → New.
* Drag and drop a video file to the editor.
* Make sure the video is upload and you see the VideoPress player on the editor. Note that due to a current issue in Jetpack that is preventing to upload the videos to VideoPress if they are not uploaded using the Media Library (https://github.com/Automattic/jetpack/issues/11194), the VideoPress player won't be visible and the video block will fallback to the core video block.
* Drag and drop multiple video files.
* Make sure multiple video blocks are created.

### CODE REVIEW

File: client/gutenberg/extensions/videopress/editor.js [hunk 1]
```diff
@@ -43,8 +47,40 @@ const addVideoPressSupport = ( settings, name ) => {
...
+				{
+					type: 'files',
+					isMatch( files ) {
+						return files.length === 1 && files[ 0 ].type.indexOf( 'video/' ) === 0;
+					},
+					// We define a higher priority (lower number) than the default of 10. This ensures that this
+					// transformation prevails over the core video block default transformations.
+					priority: 9,
+					transform( files, onChange ) {
+						const file = files[ 0 ];
```
Comment (simison) [inline client/gutenberg/extensions/videopress/editor.js]: What happens with multiple files — could we `filter()` + loop them all here?

Comment (mmtr) [reply client/gutenberg/extensions/videopress/editor.js]: Good idea! I applied it on 61264f9 but only if all the dropped files are videos. 

Since Gutenberg only applies the first transformation that matches, I think it's safer to don't create blocks at all if the file types are different. Otherwise, we would be creating a video block when the user drops an image and a video and maybe they wanted to drop only an image (but accidentally dropped a video too).

File: client/gutenberg/extensions/videopress/editor.js [hunk 2]
```diff
@@ -43,8 +48,41 @@ const addVideoPressSupport = ( settings, name ) => {
...
+
+		transforms: {
+			...settings.transforms,
+			from: [
+				{
+					type: 'files',
+					isMatch: files => every( files, file => file.type.indexOf( 'video/' ) === 0 ),
+					// We define a higher priority (lower number) than the default of 10. This ensures that this
+					// transformation prevails over the core video block default transformations.
+					priority: 9,
```
Comment (gwwar) [inline client/gutenberg/extensions/videopress/editor.js]: Thanks for the comment here! It's saves us from having to search for documentation on magic numbers.

**Comment by mmtr** [comment]
> Is the Jetpack test link correct? I followed test instructions but found that videos dropped in via drag and drop were core video blocks, while ones uploaded to the media library were VideoPress blocks.

Oh right, that's a known issue but I forgot to indicate that on the testing instructions. In Jetpack, videos uploaded *within* the block are not transcoded by VideoPress (https://github.com/Automattic/jetpack/issues/11194) and we are forced to use the Media Library. 

So, in this case, we should only check that multiple video blocks are created and they fallback to the core video blocks because we're missing the VideoPress videos. 

Since this is the behavior you found, I'll go ahead and merge this PR.
