### PR TITLE
Fix/Media library grid visually broken on mobile

### LINKED ISSUE #48227: Media library grid visually broken on mobile
Media library doesn't scale down well.

Thanks @elibud for reporting.

#### Steps to reproduce

1. Starting at URL: Open wordpress.com/media
2. Try mobile width
3. 💥 

@michaeldcain mentioned that it would look at little better if we defaulted to the next size larger for thumbnails on mobile:

cc @Automattic/team-calypso anything lately changed in componentry or in media-library that might've caused this? Anything in CSS loading-order that might affect?

### PR DESCRIPTION
**Pull request by richardkang112**
#### Changes proposed in this Pull Request

* Render only 3 or 1 media library list items per row on mobile viewport, regardless of the scale slider position.
* Limit the maximum media scale value to 0.323 when the scale slider is visible.  

#### Testing instructions

Please view http://calypso.localhost:3000/media/:domain on mobile width. The page should render 3 items per row on mobile viewport. You should be able to switch from 3 items per row to 1 item per row with the segmented control buttons. When you switch to a larger viewport (window screen width greater than 480) when the page was displaying 1 item per row on mobile viewport, the media scale value is set back to 0.323. 

* Before
image

image

* After
image

image

Fixes #48227
Related to #8295

### CODE REVIEW

File: client/state/preferences/selectors.js [hunk 1]
```diff
@@ -36,6 +36,26 @@ export function getPreference( state, key ) {
...
+			[
+				state.preferences?.localValues,
+				state.preferences?.remoteValues,
+				DEFAULT_PREFERENCE_VALUES,
+			],
+			( source ) => has( source, key )
+		),
+		key,
+		null
+	);
```
Comment (jsnajdr) [inline client/state/preferences/selectors.js]: This should call the `getPreference()` selector instead of duplicating its code.

File: client/state/preferences/selectors.js [hunk 2]
```diff
@@ -36,6 +36,26 @@ export function getPreference( state, key ) {
 	);
 }
 
+export function getMediaScalePreference( state, key, isMobile ) {
+	const SCALE_TOUCH_GRID = 0.323;
```
Comment (jsnajdr) [inline client/state/preferences/selectors.js]: The `SCALE_TOUCH_GRID` constant is not duplicated at two places. Let's move it to the `lib/media/constants` module, right next to the `SCALE_CHOICES` array, which is very closely related.

File: client/state/preferences/selectors.js [hunk 3]
```diff
@@ -36,6 +36,26 @@ export function getPreference( state, key ) {
...
+			],
+			( source ) => has( source, key )
+		),
+		key,
+		null
+	);
+
+	if ( ( isMobile && mediaScale !== 1 ) || ( ! isMobile && mediaScale > SCALE_TOUCH_GRID ) ) {
+		return SCALE_TOUCH_GRID;
+	}
```
Comment (jsnajdr) [inline client/state/preferences/selectors.js]: This condition deserves a comment that explains it. And maybe also being divided into two conditions:
1. On mobile view, allow only 1 and 0.323 scales.
2. On non-mobile view, don't allow the 1 scale: always show at least 3 columns.

And if the `getMediaScalePreference` selector ends up being called only at one place, let's inline it in that module. The selector is too specialized to be in the general-purpose `state/preferences`  module.

File: client/my-sites/media-library/content.jsx [hunk 4]
```diff
@@ -63,12 +64,14 @@ export class MediaLibraryContent extends React.Component {
...
 		postId: PropTypes.number,
 		isConnected: PropTypes.bool,
+		isMobile: PropTypes.bool,
 	};
 
 	static defaultProps = {
 		mediaValidationErrors: Object.freeze( {} ),
 		onAddMedia: noop,
 		source: '',
+		isMobile: isMobile(),
```
Comment (jsnajdr) [inline client/my-sites/media-library/content.jsx]: This default is not very useful in my opinion. It will be evaluated only once, when the app is loaded, and the result will be the default forever. And won't update when the window is resized.

File: client/my-sites/media-library/content.jsx [hunk 5]
```diff
@@ -364,6 +367,7 @@ export class MediaLibraryContent extends React.Component {
 				<MediaLibraryList
 					key="list-loading"
 					filterRequiresUpgrade={ this.props.filterRequiresUpgrade }
+					isMobile={ this.props.isMobile }
```
Comment (jsnajdr) [inline client/my-sites/media-library/content.jsx]: If we ended up drilling the `isMobile` prop from top down to the `MediaLibraryScale` component, can we use the `mediaScale` prop instead? That's the value we _really_ want, isn't it?

That way, the `mediaScale` value will be computed only at one place, and passed down to all other components that need it.

File: client/my-sites/media-library/content.jsx (hunk 4 above)
Comment (jsnajdr) [reply client/my-sites/media-library/content.jsx]: The value of `isMobile` should be retrieved by wrapping the component with the `withMobileBreakpoint` HOC. It will observe window size changes and will automatically pass an always-up-to-date `isBreakpointActive` prop to the wrapped component.

File: client/my-sites/media-library/content.jsx (hunk 5 above)
Comment (richardkang112) [reply client/my-sites/media-library/content.jsx]: If we pass down `mediaScale` prop value to children components, I think they need to unsubscribe from the Redux Store because the `mediaScale` value from Redux would overwrite the value from the parent components. Would it be alright to unsubscribe?

**Comment by richardkang112** [comment]
Sorry, I didn't mean to request review to bunch of people. I made some mistakes on Git.

File: client/my-sites/media-library/content.jsx (hunk 5 above)
Comment (jsnajdr) [reply client/my-sites/media-library/content.jsx]: I'm not sure what you mean by "unsubscribe". Do you mean that the `MediaLibraryScale` preference would no longer read the `scale` prop in Redux with `getMediaScalePreference`, but it would get the value in the regular `scale` prop from the parent component? Then yes, that's alright and desirable. Ideally, there would be only one `getMediaScalePreference` call at the top of the tree and `scale` would be passed down, exactly the same way as your patch currently does with the `isMobile` prop.

File: client/my-sites/media-library/scale.jsx [hunk 6]
```diff
@@ -34,14 +34,15 @@ const SLIDER_STEPS = 100;
  *
  * @type {number}
  */
-const SCALE_TOUCH_GRID = 0.32;
+const SCALE_TOUCH_GRID = 0.323;
```
Comment (jsnajdr) [inline client/my-sites/media-library/scale.jsx]: The constant should be imported from the `constants` module now.

**Review by jsnajdr — APPROVED** [review]
Works great :+1: Thank you very much for a valuable contribution! ❤️

**Comment by richardkang112** [comment]
@jsnajdr Thank you very much for your feedback. They were crucial to solve the problem. 👍
