### PR TITLE
Me: Improve UI when photo and Gravatar profile are hidden

### LINKED ISSUE #63199: Profile Photo: Can't update when "Hide my Gravatar profile" is toggled ON
### Quick summary

User reported and tested on my own site as well.

It seems like when an account wants toggles the **Hide my Gravatar profile** option at https://wordpress.com/me, they won't be able to update their profile photo.

Error:

```
Hmm, your new profile photo was not saved. Please try uploading again.
```

Untoggled: I can update photo.
CleanShot 2022-05-01 at 14 46 56

Toggled. I can't update photo:
CleanShot 2022-05-01 at 14 47 56

### Steps to reproduce

1. set the **Hide my Gravatar profile** option to untoggled at https://wordpress.com/me
2. try uploading an image
3. Image can be updated.
4. toggle the option **Hide my Gravatar profile** (so it is blue)
5. Try uploading an image.
6. Error message received `Hmm, your new profile photo was not saved. Please try uploading again.`

### What you expected to happen

It would work either way.

### What actually happened

Users who wish to hide Gravatar photo, cannot update photo.

### Context

_No response_

### Simple, Atomic or both?

_No response_

### Theme-specific issue?

_No response_

### Browser, operating system and other notes

_No response_

### Reproducibility

_No response_

### Severity

_No response_

### Available workarounds?

Yes, easy to implement

### Workaround details

Set the Gravatar option to untoggled.

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes https://github.com/Automattic/wp-calypso/issues/63199

### Clarifies language on the "hide Gravatar" toggle

Instead of saying "Hide Gravatar profile", say "Hide photo and Gravatar profile":

#### After

image

#### Before

image

### Visually indicates when Gravatar is hidden

When the user's photo and Gravatar profile are hidden, the page appears as follows:

image

image

When the user's photo and Gravatar are enabled, the page appears as follows:

image

#### Testing Instructions

1. Navigate to `/me`.
2. Observe the page appears as documented above.
3. Toggle the "Hide photo and Gravatar profile" button.
4. Observe the changed display of the page.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@Automattic/build One thing that's kinda funky: it takes a brief moment for `userSettings` to load. This causes the Gravatar photo to display briefly when refreshing the page, until the `gravatar_profile_hidden` setting is set to `true`:

https://user-images.githubusercontent.com/36432/176684253-01c4c786-2c4f-452a-894d-44b5fab4065c.mp4

Any ideas on how to work around this?

**Comment by wojtekn** [comment]
@danielbachhuber feature-wise looks great to me.

> This causes the Gravatar photo to display briefly when refreshing the page

I also observed this behavior. I tried to quickly refresh and click on the upload button before it disappears, but with no luck. This is good, but that blinking is weird indeed.

Maybe we should have another state, like a placeholder image (similar to one used when the photo is disabled), and return this one if `userSettings` are not loaded yet?

File: client/blocks/edit-gravatar/index.jsx [hunk 1]
```diff
@@ -254,6 +300,7 @@ const recordReceiveImageEvent = () => recordTracksEvent( 'calypso_edit_gravatar_
 export default connect(
 	( state ) => ( {
 		user: getCurrentUser( state ) || {},
+		userSettings: getUserSettings( state ),
```
Comment (p-jackson) [inline client/blocks/edit-gravatar/index.jsx]: Using the `getUserSetting` selector instead means that the component will update immediately when the user toggles rather than having to wait until the user clicks "Save changes". (that's because this selector consults the unsaved settings too).

It also has the advantage that it will only rerender the component when the setting we're interested in changes, not when _any_ setting changes.

```suggestion
		isGravatarProfileHidden: getUserSetting( state, 'gravatar_profile_hidden' ),
```

File: client/blocks/edit-gravatar/index.jsx [hunk 2]
```diff
@@ -153,11 +154,56 @@ export class EditGravatar extends Component {
...
 
 	render() {
-		const { isUploading, translate, user, additionalUploadHtml } = this.props;
+		const { isUploading, translate, user, additionalUploadHtml, userSettings } = this.props;
 		const gravatarLink = `https://gravatar.com/${ user.username || '' }`;
 		// use imgSize = 400 for caching
 		// it's the popular value for large Gravatars in Calypso
 		const GRAVATAR_IMG_SIZE = 400;
+
+		if ( userSettings.gravatar_profile_hidden ) {
```
Comment (p-jackson) [inline client/blocks/edit-gravatar/index.jsx]: It's too bad that this hidden profile version has to involve so much copy-paste, but I think I can see how it's _just_ different enough from the public profile version that it'd be just as messy to try and merge the two cases together but using if/elses to change what's needed. 😮‍💨

**Review by p-jackson — COMMENTED** [review]
> it takes a brief moment for `userSettings` to load

Yes for me this is taking a couple of seconds to load so it does look pretty bad. I like the idea of using placeholders too. The "Profile links" section on this page is also using them so it should feel fine. Not intending to increase the scope of this PR even further, but the toggle switch suffers from the same issue so maybe it should get a rectangle placeholder too, or at least render as disabled while user settings are loading?

You can use this mixin https://github.com/Automattic/wp-calypso/blob/a2d8ff3b0590cb08034bc310fd00abd8b594fff7/client/assets/stylesheets/shared/mixins/_placeholder.scss#L6 to add the standard Calypso pulsing animation to your placeholder elements.

File: client/blocks/edit-gravatar/index.jsx (hunk 1 above)
Comment (p-jackson) [reply client/blocks/edit-gravatar/index.jsx]: Just realised you'd still need to use the `getUserSettings()` selector in order to decide whether the settings were currently loading and the placeholders should be rendered. But personally, I'd still use the singular `getUserSetting()` to get the boolean from the store, since it feels much nicer to have the Gravatar component update in real-time as you toggle the setting.

File: client/me/profile/index.jsx [hunk 3]
```diff
@@ -120,7 +120,7 @@ class Profile extends Component {
 								checked={ this.props.getSetting( 'gravatar_profile_hidden' ) }
 								onChange={ this.toggleGravatarHidden }
 								label={ this.props.translate(
-									'{{spanLead}}Hide my Gravatar profile.{{/spanLead}} {{spanExtra}}This will prevent your {{profileLink}}Gravatar profile{{/profileLink}} and photo from appearing on any site. It may take some time for the changes to take effect. Gravatar profiles can be deleted at {{deleteLink}}Gravatar.com{{/deleteLink}}.{{/spanExtra}}',
+									'{{spanLead}}Hide my photo and Gravatar profile.{{/spanLead}} {{spanExtra}}This will prevent your {{profileLink}}Gravatar profile{{/profileLink}} and photo from appearing on any site. It may take some time for the changes to take effect. Gravatar profiles can be deleted at {{deleteLink}}Gravatar.com{{/deleteLink}}.{{/spanExtra}}',
```
Comment (p-jackson) [inline client/me/profile/index.jsx]: I sometimes like to be a little extra when deploying a string change like this where it's a block of text that's only slightly changed.

As soon as this deploys, because we don't have the translations for it yet, it's going to default to showing the English version for all non-English speaking users. Since the new message is only incrementally better than the old message, Spanish speakers for instance would be better off keeping the old message until translations are ready. It'd also be a big chunk of unreadable text appearing in a quite important part of the UI, so it might be a bit unnerving not knowing what it says!

```js
import i18n, { localize } from 'i18n-calypso';
import { englishLocales } from '@automattic/i18n-utils';

function MyComponent( { translate, locale } ) {
	const message = englishLocals.includes( locale ) && i18n.hasTranslation( 'The updated string' )
		? translate( 'The updated string' )
		: translate( 'The old string' );

	return <p>{ message }</p>;
}

// I'll use the localize HoC here to get access to `translate` and `locale` props
// since that's how this profile view works.
export default localize( MyComponent );
```

Whenever a translation becomes available in glotpress, it'll appear in the UI. Once all the mag16 languages are translated we can tidy up this code as a Janitorial task.

---

The simpler way of doing this is to simply not merge the PR until all translations are complete. This is doable with the `String Freeze` label. p4TIVU-5Jq-p2 (don't apply the label until you're fairly certain you have the final wording)
But that might be a few weeks, and we presumably don't want to block this bug from being fixed for that long.

File: client/blocks/edit-gravatar/index.jsx (hunk 2 above)
Comment (danielbachhuber) [reply client/blocks/edit-gravatar/index.jsx]: In the future, we'll be able to write code with our minds, and we won't even have to worry about which file the code goes in!

**Comment by danielbachhuber** [comment]
@p-jackson Added the loading UX to the avatar with c4dde83a861c522a83a934b27bbdbe9124c3859d

https://user-images.githubusercontent.com/36432/176773828-b34b2de5-e35f-4a25-9a72-d4d5944333c9.mp4

Is this the best way to determine whether the selector is loading, or is there a more precise approach?

https://github.com/Automattic/wp-calypso/pull/65122/commits/c4dde83a861c522a83a934b27bbdbe9124c3859d#diff-3d48acc81a692f5fa88e3c076767498266c4f5fbea40435394e30be798152fb2R171

File: client/me/profile/index.jsx (hunk 3 above)
Comment (danielbachhuber) [reply client/me/profile/index.jsx]: > I sometimes like to be a little extra when deploying a string change like this where it's a block of text that's only slightly changed.

@p-jackson Great suggestion! I've applied an implementation of your example in 2600366850

**Comment by danielbachhuber** [comment]
Added loading UX to the toggle fieldset too in 4343b5eda52a91b3063e82054aff99d881d6277d

https://user-images.githubusercontent.com/36432/176781691-c56fc8d2-c585-4177-a31e-9c025f07d9da.mp4

**Comment by clucasrowlands** [comment]
Hello from the Publications Team (formerly Editorial)! 

Copy-wise, looks fine. You could even swap the order so that it's consistent with the wording just after, but that's a small thing, and ultimately up to you.

> **Hide my Gravatar profile and photo.** This will prevent your Gravatar profile and photo from appearing...

**Comment by danielbachhuber** [comment]
@clucasrowlands Thanks!

How would you feel about swapping the other instance?

> **Hide my photo and Gravatar profile.** This will prevent your photo and Gravatar profile from appearing...

The reason I suggest this is because it seems like 'photo' is the primary object we're discussing.

**Comment by clucasrowlands** [comment]
> How would you feel about swapping the other instance?

Works for me!

**Comment by wojtekn** [comment]
> Is this the best way to determine whether the selector is loading, or is there a more precise approach?

I see in a few places we use `isUpdatingUserSettings` from `calypso/state/user-settings/selectors`, maybe this one would work?

**Comment by wojtekn** [comment]
@danielbachhuber I see one thing that may need an adjustment - the width of the photo container changes when we enable/disable photo, and it causes name fields to be slightly moving:

Screen Capture on 2022-07-01 at 11-30-41

**Comment by danielbachhuber** [comment]
> > How would you feel about swapping the other instance?
> 
> Works for me!

@clucasrowlands Great! Updated in 0c34a9ec1e

> I see in a few places we use `isUpdatingUserSettings` from `calypso/state/user-settings/selectors`, maybe this one would work?

@wojtekn `isUpdatingUserSettings` doesn't work (only `true` when _updating_)... but `isFetchingUserSettings` works great!

Thanks for the tip 😄 Cleaned up with b4930f3098

> I see one thing that may need an adjustment - the width of the photo container changes when we enable/disable photo, and it causes name fields to be slightly moving:

Good catch! Cleaned that up in 27951a48e9

https://user-images.githubusercontent.com/36432/176892386-808c550d-7e4b-48f6-9af5-2430edc760e4.mp4

File: client/blocks/edit-gravatar/test/index.jsx [hunk 4]
```diff
@@ -23,6 +23,10 @@ describe( 'EditGravatar', () => {
 		email_verified: false,
 	};
 
+	const userSettings = {
```
Comment (p-jackson) [inline client/blocks/edit-gravatar/test/index.jsx]: This `userSettings` prop can be removed from all the tests now. Most of the test cases are just dealing with situations where `isGravatarProfileHidden` and `isFetchingUserSettings` are falsey, so they're working just fine without the new props having to be explict.

**Review by p-jackson — APPROVED** [review]
> `isFetchingUserSettings` works great!

Perfect!

I've retested the component in `/me` and in the P2 signup process at `/start/p2` and it's working great.

Left a note about cleaning up the unit tests, but this is looking good to go. I think it's a great improvement 👍

**Review by wojtekn — APPROVED** [review]

File: client/me/profile/updated-gravatar-string.js [hunk 5]
```diff
@@ -0,0 +1,32 @@
...
+			},
+		};
+		return englishLocales.includes( locale ) ||
+			i18n.hasTranslation(
+				'{{spanLead}}Hide my photo and Gravatar profile.{{/spanLead}} {{spanExtra}}This will prevent your photo and {{profileLink}}Gravatar profile{{/profileLink}} from appearing on any site. It may take some time for the changes to take effect. Gravatar profiles can be deleted at {{deleteLink}}Gravatar.com{{/deleteLink}}.{{/spanExtra}}'
+			)
+			? translate(
+					'{{spanLead}}Hide my photo and Gravatar profile.{{/spanLead}} {{spanExtra}}This will prevent your photo and {{profileLink}}Gravatar profile{{/profileLink}} from appearing on any site. It may take some time for the changes to take effect. Gravatar profiles can be deleted at {{deleteLink}}Gravatar.com{{/deleteLink}}.{{/spanExtra}}',
+					stringParts
+			  )
```
Comment (zaguiini) [inline client/me/profile/updated-gravatar-string.js:25]: Could we extract these strings, that are identical, to a constant?

File: client/blocks/edit-gravatar/index.jsx [hunk 6]
```diff
@@ -153,11 +155,70 @@ export class EditGravatar extends Component {
...
-		const { isUploading, translate, user, additionalUploadHtml } = this.props;
+		const { isGravatarProfileHidden, isUploading, translate, user, additionalUploadHtml } =
+			this.props;
 		const gravatarLink = `https://gravatar.com/${ user.username || '' }`;
 		// use imgSize = 400 for caching
 		// it's the popular value for large Gravatars in Calypso
 		const GRAVATAR_IMG_SIZE = 400;
+
+		if ( this.props.isFetchingUserSettings ) {
+			return (
```
Comment (zaguiini) [inline client/blocks/edit-gravatar/index.jsx]: I like to keep the `render` method as slim as possible for edge cases. Would it be cleaner if we extracted those edge-case markups to a method and then call it here?

File: client/blocks/edit-gravatar/index.jsx [hunk 7]
```diff
@@ -153,11 +155,70 @@ export class EditGravatar extends Component {
...
+					</div>
+					<div>
+						<p className="edit-gravatar__explanation edit-gravatar__explanation-placeholder"></p>
+					</div>
+				</div>
+			);
+		}
+
+		if ( isGravatarProfileHidden ) {
+			return (
```
Comment (zaguiini) [inline client/blocks/edit-gravatar/index.jsx]: I like to keep the `render` method as slim as possible for edge cases. Would it be cleaner if we extracted those edge-case markups to a method and then call it here?

File: client/me/profile/updated-gravatar-string.js [hunk 8]
```diff
@@ -0,0 +1,32 @@
...
+			: translate(
+					'{{spanLead}}Hide my Gravatar profile.{{/spanLead}} {{spanExtra}}This will prevent your {{profileLink}}Gravatar profile{{/profileLink}} and photo from appearing on any site. It may take some time for the changes to take effect. Gravatar profiles can be deleted at {{deleteLink}}Gravatar.com{{/deleteLink}}.{{/spanExtra}}',
```
Comment (zaguiini) [inline client/me/profile/updated-gravatar-string.js:27]: This one too. It takes a lot of space and it's not clear why it exists.

**Review by zaguiini — APPROVED** [review]
Functionality-wise, it works fine. I left some non-blocking comments on code organization.

File: client/blocks/edit-gravatar/index.jsx (hunk 6 above)
Comment (p-jackson) [reply client/blocks/edit-gravatar/index.jsx]: That's true. Having the `render` method mostly just contain the happy-path UI is nice.

Comment (danielbachhuber) [reply client/blocks/edit-gravatar/index.jsx]: > I like to keep the `render` method as slim as possible for edge cases. Would it be cleaner if we extracted those edge-case markups to a method and then call it here?

@zaguiini Good suggestion! I did so with c3281ed5c9

File: client/blocks/edit-gravatar/index.jsx (hunk 7 above)
Comment (danielbachhuber) [reply client/blocks/edit-gravatar/index.jsx]: Did with c3281ed5c9

File: client/me/profile/updated-gravatar-string.js (hunk 5 above)
Comment (danielbachhuber) [reply client/me/profile/updated-gravatar-string.js:25]: > Could we extract these strings, that are identical, to a constant?

@zaguiini Unfortunately, I tried that, but `translate()` doesn't like to receive a constant.

File: client/me/profile/updated-gravatar-string.js (hunk 8 above)
Comment (danielbachhuber) [reply client/me/profile/updated-gravatar-string.js:27]: See above ^ — `translate()` doesn't want to receive a constant.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7419597

Thank you @danielbachhuber for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7419597).

**Comment by p-jackson** [comment]
PR to tidy up the `hasTranslation` check: #65626
