### PR TITLE
Fix unified design picker mShot config

### LINKED ISSUE #71439: Lettre design looks off in the Design Picker
# Description
 See p1671645376874249-slack-C048CUFRGFQ

Screenshot from the Design Picker (looks odd)
Image

Image

Screenshot from the Showcase (looks better)

Image

# Dev Tasks
- [x] investigate if the is an mShots issue or something else

### PR DESCRIPTION
**Pull request by candy02058912**
#### Proposed Changes

* Make scrollable false (p1672387691133409/1672385901.465829-slack-CRWCHQGUB)
Note: scrollable is not working even when set to true (was testing in Chrome).
* Adjust the mShot config according to [this comment](https://github.com/Automattic/wp-calypso/issues/71439#issuecomment-1367335609)

| Before  | After |
| :-------------: | :-------------: |
|   | |

#### Testing Instructions

* Checkout to this branch
* Go to `/setup/site-setup/designSetup?siteSlug=:site`
* Check if screenshots for all designs look normal on desktop and mobile

#### Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] ~[Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?~
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] ~Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)~
- [ ] ~Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?~
- [ ] ~For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?~

Fixes #71439

### CODE REVIEW

File: packages/design-picker/src/utils/available-designs.ts [hunk 1]
```diff
@@ -57,7 +57,8 @@ export const getMShotOptions = ( {
 	// Take care changing these values, as the design-picker CSS animations are written for these values (see the *__landscape and *__portrait classes)
 	return {
 		vpw: isMobile ? MOBILE_VIEWPORT_WIDTH : DEFAULT_VIEWPORT_WIDTH,
-		vph: scrollable ? 1600 : 1040,
+		// 901 renders well with all the current designs
```
Comment (arthur791004) [inline packages/design-picker/src/utils/available-designs.ts]: [nit] It would be better to put the related link in the comment 🙂

**Review by arthur791004 — APPROVED** [review]
LGTM 👍
