### PR TITLE
Don't apply user color scheme on checkout pages.

### LINKED ISSUE #93746: Checkout: User account color settings get applied to checkout
### Quick summary

While @jjchrisdiehl and I were investigating https://github.com/Automattic/wp-calypso/issues/88437, we stumbled upon the realization that customer dashboard color schemes were being applied to Checkout. 

Image

### Steps to reproduce

1. Add a product to your Checkout from your account
2. Notice the color of the links and the highlights when you click on input fields (like first name and last name)
3. In a separate tab, go to `me/account`
4. Scroll down to `Interface settings > Dashboard color scheme` (Sunrise and Sunset make it really obvious)
5. Select a color scheme which is different than your current settings and save your changes
6. Go back to Checkout in your original tab, notice the links and highlights are a different color now

Image

### What you expected to happen

Checkout should be using its own colors and styles to maintain the correct branding for service purchase (WordPress.com, Jetpack, Akismet, etc).

### What actually happened

 The user `Dashboard color settings` are applied in Checkout, breaking the branding. There are also places, like the country select field, where neither the user settings or Checkout are fully applied. This causes the visuals to get even more messy:

Image

Notice the pink/red border with the blue offset? The pink and red color is coming from the `Sunrise` dashboard color setting. The blue is coming from Checkout.

### Impact

All

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

It looks like we can override the user color settings by updating the styling in [BillingFormFields](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/checkout/src/components/wp-contact-form.tsx#L9-L41). We just need to figure out what all needs to be updated.

### PR DESCRIPTION
**Pull request by TimBroddin**
Fixes https://github.com/Automattic/wp-calypso/issues/93746

## Proposed Changes

* Don't apply the user's color scheme on checkout pages.

## Why are these changes being made?

*

## Testing Instructions

1. Add a product to your Checkout from your account
2. Notice the color of the links and the highlights when you click on input fields (like first name and last name)
3. In a separate tab, go to me/account
4. Scroll down to Interface settings > Dashboard color scheme (Sunrise and Sunset make it really obvious)
5. Select a color scheme which is different than your current settings and save your changes
6. Go back to Checkout in your original tab, confirm the links and highlights have the same color

Also test navigating through the whole flow, your selected color scheme should be reapplied when exiting the checkout flow.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by mpkelly** [comment]
I tested it with the Sunset theme, and it works for me. 

**Before**

Screenshot 2567-08-22 at 16 40 02

**After**

Screenshot 2567-08-22 at 16 41 17

File: client/layout/index.jsx [hunk 1]
```diff
@@ -261,7 +262,9 @@ class Layout extends Component {
 			( this.props.isGlobalSidebarVisible && this.props.colorScheme !== 'global' ) ||
 			( prevProps.isGlobalSidebarVisible &&
 				! this.props.isGlobalSidebarVisible &&
-				this.props.colorScheme !== 'global' )
+				this.props.colorScheme !== 'global' ) ||
+			( prevProps.sectionName !== 'checkout' && this.props.sectionName === 'checkout' ) ||
+			( prevProps.sectionName === 'checkout' && this.props.sectionName !== 'checkout' )
```
Comment (xavier-lc) [inline client/layout/index.jsx]: This is a bit complicated to read, I think naming it before the `if` would be better:

```
const isCurrentOrPreviousSectionCheckout = ( prevProps.sectionName !== 'checkout' && this.props.sectionName === 'checkout' ) ||
			( prevProps.sectionName === 'checkout' && this.props.sectionName !== 'checkout' )
```

**Review by xavier-lc — APPROVED** [review]
Tested and works as described.

File: client/layout/index.jsx (hunk 1 above)
Comment (TimBroddin) [reply client/layout/index.jsx]: I'll change it!

**Review by xavier-lc — APPROVED** [review]
`willTransitionFromOrToCheckout` sounds much better, thanks! 

🚀🚀🚀
