### PR TITLE
Jetpack E2E: stabilization of the Stats spec. 

### LINKED ISSUE #81062: Flaky E2E: Filter traffic activity to Likes
### Spec file

specs/stats/stats.ts

### TeamCity ID

_No response_

### Logs

image

```
======= Failed test run #1 ==========
  locator.waitFor: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for getByRole('main').locator('.stats-tabs').locator('.is-selected').filter({ hasText: 'Likes' }) to be visible
  ============================================================
  at StatsPage.waitFor [as showStatsOfType] (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/stats-page.ts:143:5)
      at Object.<anonymous> (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/stats/stats.ts:72:4)
======= Failed test run #2 ==========
  locator.waitFor: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for getByRole('main').locator('.stats-tabs').locator('.is-selected').filter({ hasText: 'Likes' }) to be visible
  ============================================================
  at StatsPage.waitFor [as showStatsOfType] (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/stats-page.ts:143:5)
      at Object.<anonymous> (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/stats/stats.ts:72:4)
```

### PR DESCRIPTION
**Pull request by worldomonation**
Related to https://github.com/Automattic/wp-calypso/issues/80730, https://github.com/Automattic/wp-calypso/pull/80891.
Fixes https://github.com/Automattic/wp-calypso/issues/81062.

## Proposed Changes

This PR adjusts the loading wait for the Stats graph in the hopes of making the Stats spec, expanded in https://github.com/Automattic/wp-calypso/pull/80891, more stable. In particular, the flakiness is recorded in https://github.com/Automattic/wp-calypso/issues/81062.

## Testing Instructions

Ensure the following build configurations are passing:
  - [x] Calypso E2E (desktop)
  - [x] Jetpack E2E Simple (mobile)
  - [x] Jetpack E2E Simple (desktop)
  - [x] Jetpack E2E AT (desktop)

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: test/e2e/specs/stats/stats.ts [hunk 1]
```diff
@@ -71,10 +71,6 @@ describe( DataHelper.createSuiteTitle( 'Stats' ), function () {
 		it( 'Filter traffic activity to Likes', async function () {
 			await statsPage.showStatsOfType( { tab: 'Traffic', type: 'Likes' } );
 		} );
-
-		it( 'Filter traffic activity to Comments', async function () {
-			await statsPage.showStatsOfType( { tab: 'Traffic', type: 'Visitors' } );
-		} );
```
Comment (worldomonation) [inline test/e2e/specs/stats/stats.ts:77]: In the end, I decided that 

It doesn't even matter

If the step here exists or not.

File: packages/calypso-e2e/src/lib/pages/stats-page.ts [hunk 2]
```diff
@@ -113,7 +113,7 @@ export class StatsPage {
 		// Wait for the charts to load first, even if no activity is present.
 		// CSS selector has to be used here because there is no a11y selector
 		// for this element.
-		await this.page.locator( selectors.graph ).waitFor();
+		await this.page.locator( '.is-loading' ).waitFor( { state: 'detached' } );
```
Comment (worldomonation) [inline packages/calypso-e2e/src/lib/pages/stats-page.ts]: Yeah, replacing one CSS locator for another.

File: packages/calypso-e2e/src/lib/pages/stats-page.ts [hunk 3]
```diff
@@ -113,7 +113,12 @@ export class StatsPage {
 		// Wait for the charts to load first, even if no activity is present.
 		// CSS selector has to be used here because there is no a11y selector
 		// for this element.
-		await this.page.locator( selectors.graph ).waitFor();
+		// A loop is used here because multiple locators can match the CSS locator
+		// and to be safe, it's best to wait for all placeholders to be detached.
+		const locators = await this.page.locator( '.is-loading' ).all();
+		for ( const locator of locators ) {
```
Comment (karenroldan) [inline packages/calypso-e2e/src/lib/pages/stats-page.ts:119]: **thought (non-blocking):** While I understand why a loop is used here, I think using `Promise.all()` is more efficient because it waits for all elements to be detached concurrently rather than sequentially. What do you think?

**Review by karenroldan — APPROVED** [review]
LGTM 👍🏻  left one non-blocking comment. Feel free to merge whenever!

File: packages/calypso-e2e/src/lib/pages/stats-page.ts (hunk 3 above)
Comment (worldomonation) [reply packages/calypso-e2e/src/lib/pages/stats-page.ts:119]: Good point, I think I've subconsciously tried to stop using `Promise.all`.

However, I'm drawing a bit of a blank on how to apply the `waitFor()` method to the array produced by the call in Line 118. I don't think I've ever done that with a locator before - with a `page.waitForSelector`, yes. It's easy to do with the `waitForSelector`:

```
await page.waitForSelector( <selector> );
```
