### PR TITLE
WCS Labels - fixed the label modal not updating with recent settings

### LINKED ISSUE #18881: WooCommerce - label purchase modal data can be left behind if settings are updated
To reproduce:
1. Open an order and open the label purchase modal
2. In the same tab, navigate to the settings screen and change settings (update the packages list, enable/disable the labels)
3. Navigate back to the same order
4. The label modal still has the old data
5. Refresh the page - the label data will be updated

We should load and read the data from the appropriate state subtrees for settings rather than rely on the data that has been compiled on load time in the backend (use query components)

CC @DanReyLop @dechov

### PR DESCRIPTION
**Pull request by marcinbot**
Fixes #18881 

To test:
* when WCS is not configured (no payment method selected) open an order and verify that there is no "print label" button
* in the same tab open shipping settings and select a payment method
* navigate back to the same order and verify that you can print labels now

* with WCS shipping enabled and set up, open an order
* in the same tab, navigate to the shipping settings and change some settings (enable/disable labels, add new packages)
* navigate back to the order and verify that the changes are reflected there

### CODE REVIEW

File: client/extensions/woocommerce/app/order/order-fulfillment/index.js [hunk 1]
```diff
@@ -273,13 +276,16 @@ class OrderFulfillment extends Component {
 
 export default connect(
 	( state, { order, site } ) => {
-		const labelsLoaded = wcsEnabled && Boolean( areLabelsLoaded( state, order.id, site.ID ) );
+		const labelsLoaded = wcsEnabled && Boolean( areLabelsFullyLoaded( state, order.id, site.ID ) );
 		const hasLabelsPaymentMethod =
-			wcsEnabled && labelsLoaded && getSelectedPaymentMethod( state, order.id, site.ID );
+			wcsEnabled &&
+			labelsLoaded &&
+			areLabelSettingsPristine( state, site.ID ) &&
```
Comment (DanReyLop) [inline client/extensions/woocommerce/app/order/order-fulfillment/index.js]: This is a bad UX. If the user leaves the `Settings` screen without saving, he won't be able to purchase a label.

Should we store in the `settings` state the "previous" form values so they're returned if the form is "not pristine"?

File: client/extensions/woocommerce/woocommerce-services/components/query-label-settings/index.js [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+	}
+
+	render() {
+		return null;
+	}
+}
+
+export default connect(
+	( state ) => ( {
+		siteId: getSelectedSiteId( state ),
```
Comment (DanReyLop) [inline client/extensions/woocommerce/woocommerce-services/components/query-label-settings/index.js]: `siteId` should be passed down as a prop, not fetched from `state`.

File: client/extensions/woocommerce/woocommerce-services/components/query-packages/index.js [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+	}
+
+	render() {
+		return null;
+	}
+}
+
+export default connect(
+	( state ) => ( {
+		siteId: getSelectedSiteId( state ),
```
Comment (DanReyLop) [inline client/extensions/woocommerce/woocommerce-services/components/query-packages/index.js]: Same here and in the `QueryLabels` component, `siteId` should be passed down as a prop.

File: client/extensions/woocommerce/woocommerce-services/state/shipping-label/actions.js [hunk 4]
```diff
@@ -487,14 +487,15 @@ export const removePackage = ( orderId, siteId, packageId ) => {
...
-	return {
+export const setPackageType = ( orderId, siteId, packageId, boxTypeId ) => ( dispatch, getState ) => {
+	dispatch( {
 		type: WOOCOMMERCE_SERVICES_SHIPPING_LABEL_SET_PACKAGE_TYPE,
 		siteId,
 		orderId,
 		packageId,
 		boxTypeId,
-	};
+		allBoxes: getAllPackageDefinitions( getState(), siteId ),
```
Comment (DanReyLop) [inline client/extensions/woocommerce/woocommerce-services/state/shipping-label/actions.js]: Using an action object to pass data down to the reducer feels wrong... at least pass down only `box: allBoxes[boxTypeId]`.

File: client/extensions/woocommerce/app/order/order-fulfillment/index.js (hunk 1 above)
Comment (marcinbot) [reply client/extensions/woocommerce/app/order/order-fulfillment/index.js]: The unsaved settings are already being used in the backend. This is to prevent a scenario where the user changes the payment method, then expects to pay for a label with the new card, but still pays with the old one. 

65b39e5 conditionally disables the button and adds a tooltip that says why the button has been disabled

File: client/extensions/woocommerce/woocommerce-services/state/shipping-label/actions.js (hunk 4 above)
Comment (marcinbot) [reply client/extensions/woocommerce/woocommerce-services/state/shipping-label/actions.js]: I agree, but there's no way to retrieve the state from the reducer. I went with your suggestion.

File: client/extensions/woocommerce/woocommerce-services/state/label-settings/reducer.js [hunk 5]
```diff
@@ -44,6 +50,11 @@ reducers[ WOOCOMMERCE_SERVICES_LABELS_INIT_FORM ] = (
 };
 
 reducers[ WOOCOMMERCE_SERVICES_LABELS_SET_FORM_DATA_VALUE ] = ( state, { key, value } ) => {
+	let pristineData = state.pristineData;
+	if ( state.meta.pristine ) {
+		pristineData = cloneDeep( state.data );
```
Comment (DanReyLop) [inline client/extensions/woocommerce/woocommerce-services/state/label-settings/reducer.js]: No need to `cloneDeep`, since `state` is immutable. `pristineData = state.data` is enough.

Comment (marcinbot) [reply client/extensions/woocommerce/woocommerce-services/state/label-settings/reducer.js]: Thanks, I removed it.
