### PR TITLE
FSE: Fix missing inserter

### LINKED ISSUE #43784: Missing Block Inserter in dotcom FSE w/ Gutenberg 8.4
Dotcom FSE sites running on Gutenberg v 8.4 are missing their inserter:

Screen Shot 2020-06-29 at 7 41 23 PM

Expected (as seen on v8.3):

Screen Shot 2020-06-29 at 7 42 30 PM

This seems to be an issue with the Inserter implementation in `post-content-block-appender`:

https://github.com/Automattic/wp-calypso/blob/6a3f9e6170f0eb3a6c7f3ad8f9855dbb6e49ad1f/apps/full-site-editing/full-site-editing-plugin/dotcom-fse/editor/block-inserter/post-content-block-appender.js#L24-L29

### PR DESCRIPTION
**Pull request by sirreal**
#### Changes proposed in this Pull Request

Add a MutationObserver to re-inject a React component on DOM changes if the component is not already present.

This is a workaround for https://github.com/Automattic/wp-calypso/issues/43784, which observed that the component is missing. The component is injected into a React tree, which is volatile. Injected components like this will disappear if a parent is re-rendered.

This also adds a class to fix the block inserter from being removed from the post editor. It should only be removed from the page editor.

#### Testing instructions

Use a [dotcom-fse](https://horizon.wordpress.com/start/test-fse) enabled site for testing.

* Try to reproduce https://github.com/Automattic/wp-calypso/issues/43784 on a Simple site without Gutenberg edge.
* Try to reproduce https://github.com/Automattic/wp-calypso/issues/43784 on a Simple site with Gutenberg edge.
* Visit the post editor and ensure you can see the standard block inserter (https://github.com/Automattic/wp-calypso/issues/43784#issuecomment-662551458).

Fixes https://github.com/Automattic/wp-calypso/issues/43784

### CODE REVIEW

File: apps/full-site-editing/full-site-editing-plugin/dotcom-fse/editor/block-inserter/index.js [hunk 1]
```diff
@@ -26,14 +29,34 @@ function renderPostContentBlockInserter() {
 			return;
 		}
 		clearInterval( editPostHeaderToolbarInception );
+		injectBlockInserter();
+
+		// Re-inject the FSE inserter as needed in case React re-renders the header
+		const wpbody = document.getElementById( 'wpbody' );
+		if ( wpbody && typeof window.MutationObserver !== 'undefined' ) {
+			const observer = new window.MutationObserver( injectBlockInserter );
```
Comment (fullofcaffeine) [inline apps/full-site-editing/full-site-editing-plugin/dotcom-fse/editor/block-inserter/index.js:37]: Clever workaround! I learned something new today, didn't know about the `MutationObserver` API.

**Comment by fullofcaffeine** [comment]
> This also adds a class to fix the block inserter from being removed from the post editor. It should only be removed from the page editor.

Why should it not be present on the page editor?

**Comment by sirreal** [comment]
> Why should it not be present on the page editor?

It's hidden on the page editor so that it can be replaced with a custom inserter. That's part of the dotcom-fse functionality.

I don't know many details about why 🙂

**Comment by fullofcaffeine** [comment]
Works great :heavy_check_mark: 

1. Tested from a fresh FSE-dotcom site mapped to a clear sandbox + the `gutenberg-edge` sticker applied (8.5.1). Could reproduce #43784;
1. Checked out this branch and synced the files over to the sandbox using FSE's `yarn dev --sync`;
1. Verified that the **block inserter button** in the toolbar was visible and functional in both the FSE/page editor and the post editor.

**Comment by fullofcaffeine** [comment]
> > Why should it not be present on the page editor?
> 
> It's hidden on the page editor so that it can be replaced with a custom inserter. That's part of the dotcom-fse functionality.
> 
> I don't know many details about why slightly_smiling_face

Interesting. Not critical or anything, but I'd love to know why a custom inserter is needed there cc @noahtallen

**Comment by noahtallen** [comment]
> I don't know many details about why

If I remember correctly:
1. It prevents blocks from being inserted outside of the post content block. In dotcom FSE, you are not able to edit the underlying template: it consists of just "header, post content, footer". You can edit each of those three blocks, but you are not able to modify the order or anything about that root template. This is one of the technical limitations for dotcom FSE which is resolved by core FSE. Basically, the "template" is hardcoded in PHP, which means that you should not be able to insert it it in the editor. Expanding further beyond that, we were basically hacking the normal page editor to render multiple entities, so the default behavior would be to edit anything on the page, which obviously doesn't work if parts of the page must always be hardcoded to the same thing.
2. It might also enable FSE blocks to show up only in the FSE editor.

File: apps/full-site-editing/full-site-editing-plugin/dotcom-fse/editor/block-inserter/index.js (hunk 1 above)
Comment (Addison-Stavlo) [reply apps/full-site-editing/full-site-editing-plugin/dotcom-fse/editor/block-inserter/index.js:37]: > Clever workaround!

Agreed!  I didn't know about the `MutationObserver` either, this is very interesting and great to see.  Nice work here. 😄

**Review by Addison-Stavlo — APPROVED** [review]
Testing this on my FSE site and it looks good!  

I didn't realize that the inserter was also being hidden in the post editor but only re-added in the page editor.  🤦‍♀️   So the inserter must have been missing from the post editor for quite some time?

Either way, with this PR the inserter is back in both editors and working well on both (edge and non-edge) Gutenberg versions.

Great job, and thank you for fixing this!

<hr/>

Although a separate issue, it's worth noting that the inserter is different between the post and page editors.  Since the post editor is not re-implementing the inserter we have the standard sidebar style inserter with the patterns tab.  While in the page editor our re-implemented version is the dropdown inserter for blocks only.  This is expected with the current implementation and is in the prioritized backlog of the gardening board (https://github.com/Automattic/wp-calypso/issues/41654).

**Comment by sirreal** [comment]
Thanks, folks!

> So the inserter must have been missing from the post editor for quite some time?

That seems to be the case. I discovered it when I started looking at https://github.com/Automattic/wp-calypso/issues/43784.

**Comment by sirreal** [comment]
Changes to `/apps` should have no impact on the Calypso e2e tests run against this branch. I'll merge in spite of those e2e test failures.
