### PR TITLE
Help Center: Show error if submitting ticket fails

### LINKED ISSUE #63552: Task: Help center error messaging
### Details

Now, we don't handle any failures in the contact form. We need to communicate clearly to the users when things go wrong (missing subject, missing title, etc..).

### Checklist

- [ ] Handle Kayako tickets failures
- [ ] Handle Forum topics failures
- [ ] Report error on form validation if needed.

### Related

_No response_

### PR DESCRIPTION
**Pull request by escapemanuele**
#### Changes proposed in this Pull Request

image

- Introduced an error shown to the user if the request for submitting to forums (as a free user) or sending an email fails.
- In FORUM and EMAIL the subject is now required, without that the request would fail.
- Moved `FormInputValidation` to `@automattic/components`, as we needed to use it from the help center package

#### Testing instructions

Don't be scared of the huge number of files, 99% is only changing the import! 

* checkout the branch
* `yarn dev --sync` from `apps/editing-toolkit`
* open the help center
* check that the subject is now required in EMAIL and FORUM
* `yarn start`
* check that there are no errors for the import changes ([http://calypso.localhost:3000/devdocs/design/form-fields](http://calypso.localhost:3000/devdocs/design/form-fields) could be a nice place to check)

Related to #63552
Fixes #63552

### CODE REVIEW

File: packages/components/src/forms/form-input-validation/index.tsx [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+	} );
+
+	const defaultIcon = isError || isWarning ? 'notice-outline' : 'checkmark';
+
+	return (
+		<div className={ classes } role="alert">
+			<span id={ id }>
+				<Gridicon size={ 24 } icon={ icon ? icon : defaultIcon } /> { text }
+				{ children }
+			</span>
```
Comment (alshakero) [inline packages/components/src/forms/form-input-validation/index.tsx:43]: I think these two (icon and childen) need to be in their own elements to fix this vertical alignment issue:

image

File: packages/help-center/src/components/help-center-contact-form.tsx [hunk 2]
```diff
@@ -387,6 +402,12 @@ const ContactForm: React.FC< ContactFormProps > = ( { mode, onBackClick, onGoHom
 				>
 					{ isSubmitting ? formTitles.buttonLoadingLabel : formTitles.buttonLabel }
 				</Button>
+				{ hasSubmittingError && (
+					<FormInputValidation
+						isError
+						text={ __( 'Something went wrong, please try again later', __i18n_text_domain__ ) }
```
Comment (alshakero) [inline packages/help-center/src/components/help-center-contact-form.tsx]:
```suggestion
						text={ __( 'Something went wrong, please try again later.', __i18n_text_domain__ ) }
```

File: packages/help-center/src/components/help-center-contact-form.tsx [hunk 3]
```diff
@@ -294,7 +303,12 @@ const ContactForm: React.FC< ContactFormProps > = ( { mode, onBackClick, onGoHom
 	};
 
 	const isCTADisabled = () => {
-		return isLoading || ( mode !== 'FORUM' && ! supportSite ) || ! message;
+		return (
+			isLoading ||
+			( mode !== 'FORUM' && ! supportSite ) ||
+			( mode !== 'CHAT' && ! subject ) ||
+			! message
+		);
```
Comment (alshakero) [inline packages/help-center/src/components/help-center-contact-form.tsx]: Can we make this a switch around `mode`? We'll need it for Directly support soon.

**Review by alshakero — COMMENTED** [review]
Brilliant work. "moved to a package" 🎵 to my ears.


Left two tiny notes.

File: packages/help-center/src/components/help-center-contact-form.tsx [hunk 4]
```diff
@@ -294,7 +303,12 @@ const ContactForm: React.FC< ContactFormProps > = ( { mode, onBackClick, onGoHom
 	};
 
 	const isCTADisabled = () => {
-		return isLoading || ( mode !== 'FORUM' && ! supportSite ) || ! message;
+		return (
+			isLoading ||
+			( mode !== 'FORUM' && ! supportSite ) ||
+			( mode !== 'CHAT' && ! subject ) ||
```
Comment (klimeryk) [inline packages/help-center/src/components/help-center-contact-form.tsx]: Shouldn't this check for `subject` be also for `EMAIL`? From my testing it was also a required field for the endpoint.

Comment (escapemanuele) [reply packages/help-center/src/components/help-center-contact-form.tsx]: Yes @klimeryk , the current code checks for the subject presence if the mode is different from `CHAT`, so `EMAIL` and `FORUM` :) 

It could be a little confusing written like this, so in a bit I'll push a refactor of this.

File: packages/help-center/src/components/help-center-contact-form.tsx [hunk 5]
```diff
@@ -294,7 +303,18 @@ const ContactForm: React.FC< ContactFormProps > = ( { mode, onBackClick, onGoHom
...
+		}
+
+		switch ( mode ) {
+			case 'CHAT':
+				return ! supportSite;
+			case 'EMAIL':
+				return ! supportSite || ! subject;
+			case 'FORUM':
+				return ! subject;
+		}
```
Comment (alshakero) [inline packages/help-center/src/components/help-center-contact-form.tsx:317]: Truly beautiful.

**Comment by escapemanuele** [comment]
Should have addressed everything @alshakero 👍

**Review by alshakero — CHANGES_REQUESTED** [review]
The alignment still looks off and it seems we lost the red color:

image

**Comment by escapemanuele** [comment]
Thanks for catching that, I must have forgot to commit something 🤔

**Review by alshakero — APPROVED** [review]
Looks and works great! Thanks for moving Form fields to a package.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7329987

Thank you @escapemanuele for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7329987).
