### PR TITLE
Stats: Make Post Trends Visualization always start on Mondays.

### LINKED ISSUE #6138: Stats: Insights: Posting activity heatmap layout changes with change in interface language
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/insights/ with interface language set to the en locale.
2. Take note of layout of the posting activity heatmap. Specifically, the top row indicate dates falling on a Monday.

stats_ _wordpress_com
1. Go to Account settings: https://wordpress.com/me/account/
2. Change the interface language to any other language than en, then view Insights page again.
#### What I expected

For layout on the Insights page to be the same as with the previous language settings.
#### What happened instead

The layout of the Posting Activity heatmap changed to now show dates falling on Tuesdays on the top row:

statistiken_ _wordpress_com

I confirmed this happening with several interface languages. Tested a sampling of Latin and non-Latin alphabets with LTR and RTL languages. 

With some languages that have more than one locale results are inconsistent: Of the languages tested, en, pt-br and fr-ca display the heatmap correctly, while en-gb, pt, fr and fr-be changes the layout
#### Browser / OS version

Confirmed on latest versions of FF and Chrome on OSX.
#### Context / Source

Reported via 744627-f

### PR DESCRIPTION
**Pull request by timmyc**
Fixes #6138 - The "Posting Activity" visualization on the Stats Insights page is _supposed_ to start the week columns on Mondays, but due to some moment.js locale mishaps, in certain locales, the start of the week shows as Tuesdays.  Since this visualization, specifically the day "boxes", are quite small - it makes sense to ensure we start the week on a consistent day - and who doesn't love Mondays?!

While fixing the issue, I opted to update a few of the components in this visualization to current standards as well by removing `createClass` and such.  This branch is best tested on a site with post data in the visualization.  en.blog.worpdress.com is a great one to use.

__To Test__
1. Starting at URL: https://wordpress.com/stats/insights/ with interface language set to the en locale.
2. Take note of layout of the posting activity heatmap. Specifically, the top row indicate dates falling on a Monday.

stats_ _wordpress_com

3. Go to Account settings: https://wordpress.com/me/account/
4. Change the interface language to any other language than en, then view Insights page again.
5. Verify the top row represents Monday's still, and the label when you mouse over is localized

### CODE REVIEW

File: client/my-sites/stats/post-trends/week.jsx [hunk 1]
```diff
@@ -55,19 +53,26 @@ export default React.createClass( {
...
 	}
 
-} );
+}
+
+export default connect(
+	( state ) => ( { userLocale: getCurrentUserLocale( state ) } ),
+	{},
+	null,
+	{ pure: false }
```
Comment (youknowriad) [inline client/my-sites/stats/post-trends/week.jsx]: For my own knowledge, I'm wondering what is the exact rule to add the `pure: false` option? I'm not sure I understand it correctly

Comment (timmyc) [inline client/my-sites/stats/post-trends/week.jsx]: Good point - not sure I need this here but have ran into issues with components and old data-list stores in the past.  I'll try it without.

**Comment by timmyc** [comment]
Thanks for the review @youknowriad - updates in e74ca86

**Comment by youknowriad** [comment]
LGTM 🚢
