### PR TITLE
Subscribers Page: Fix subscribers empty view

### LINKED ISSUE #85667: Subscribers page: view for no results when searching is missing
Image

### PR DESCRIPTION
**Pull request by phcp**
Closes https://github.com/Automattic/wp-calypso/issues/85667

## Proposed Changes

* Change `grandTotal` to use `useSubscriberCountQuery`
  * Check if the current user is subscribed to remove from the count (as the GET /subscribers endpoint always excludes the current user)
* Fix cache key to include `hasManySubscribers`

## Testing Instructions

* Apply this PR to your local
* Go to http://calypso.localhost:3000/subscribers/{site-slug}
* Open a site with no subscribers
* You should see the Subscribers Launchpad
* Open a site with subscribers and search for a non-existent subscriber
* You should see an empty search view
* Perform regression tests on the Subscribers list

image

image

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by yansern** [comment]
Tested on empty subscriber site, sites with subscribers and site with > 30k subscriber. And also, thanks for fixing the cacheKey for site with > 30k subscriber.

File: client/my-sites/subscribers/components/subscribers-page/subscribers-page-context.tsx [hunk 1]
```diff
@@ -112,9 +117,18 @@ export const SubscribersPageProvider = ( {
...
 	const pages = subscribersQueryResult.data?.pages || 0;
 
+	// Current user is not included in the subscribers list, so we need to remove from the total
+	const { data: subscribersTotals } = useSubscriberCountQuery( siteId );
+	const userId = useSelector( getCurrentUserId ) ?? undefined;
+	const { data: isCurrentUserSubscribed } = useSubscriberDetailsQuery( siteId, undefined, userId );
+
+	const grandTotal =
+		isCurrentUserSubscribed && subscribersTotals?.email_subscribers
+			? subscribersTotals.email_subscribers - 1
```
Comment (yansern) [inline client/my-sites/subscribers/components/subscribers-page/subscribers-page-context.tsx:129]: Note to self, grandTotal excludes the site owner himself.

**Review by yansern — APPROVED** [review]
