### PR TITLE
Editor: fix available publicize connections

### LINKED ISSUE #867: Editor: Sharing: Partially revealing non-shared connections from other users
We are partially revealing non-shared connections from other users, when they are returned by the `/publicize-connections` REST API endpoint. The Sharing accordion ends up in this state of showing services but not individual connections:

screenshot from 2015-11-26 09-24-40

### PR DESCRIPTION
**Pull request by jkudish**
Fixes #867

Fixes available publicize connections by filtering them appropriately for the
current user context. Only shared connections or those belonging to the
current user should be available within the sharing accordion.

__Testing Instructions:__

Open the Editor for different sites with a different set of publicize connections available for each, and ensure that only shared connections or those belonging to you are offered within the sharing accordion.

### CODE REVIEW

File: shared/lib/sharing/publicize/selectors.js [hunk 1]
```diff
@@ -18,6 +18,23 @@ export function getConnectionsBySiteId( state, siteId ) {
...
 /**
+ * Returns an array of known connections for the given site ID
+ * that are available to the current user
+ *
+ * @param  {Object} state         Global state tree
+ * @param  {Number} siteId        Site ID
+ * @param  {Number} currentUserID ID of the current user
+ * @return {Array}                Site connections
+ */
+export function getConnectionsBySiteIdAvailableToCurrentUser( state, siteId, currentUserID ) {
```
Comment (timmyc) [inline shared/lib/sharing/publicize/selectors.js]: Looks like we have a [test suite](https://github.com/Automattic/wp-calypso/blob/fix/editor-sharing-do-not-show-non-shared-connections/shared/lib/sharing/publicize/test/selectors.js) for this file - could we add some tests for this new selector?

File: client/post-editor/editor-drawer/index.jsx [hunk 2]
```diff
@@ -113,8 +114,9 @@ var EditorDrawer = React.createClass( {
 	},
 
 	renderSharing: function() {
+		const currentUser = user.get();
 		return (
-			<EditorSharingContainer site={ this.props.site } />
+			<EditorSharingContainer site={ this.props.site } currentUserID={ currentUser.ID } />
```
Comment (timmyc) [inline client/post-editor/editor-drawer/index.jsx]: Though highly unlikely ( maybe not even possible ? ) do we need to consider the possibility of not having a `currentUser` here and return `null` instead?

**Comment by timmyc** [comment]
Tests out well for me - I think it would be nice to add some quick test cases for the new method though.

File: client/post-editor/editor-drawer/index.jsx (hunk 2 above)
Comment (aduth) [inline client/post-editor/editor-drawer/index.jsx]: A few comments here:

- `currentUserID` does not conform to [capitalization guidelines](https://github.com/Automattic/wp-calypso/blob/master/docs/coding-guidelines/javascript.md#naming-conventions) and should be `currentUserId`. The capitalized `.ID` property is okay only because it's reflective of the API response.
- Per @timmyc's comment above, users are bootstrapped server-side in production environments, but not in development (last I checked, anyways), so we should guard against empty value
- We should move the user handling to within the `<EditorSharingContainer />` component rather than passing it as a prop. Eventually, I'd like for `<EditorSharingContainer />` to accept no props and instead be entirely self-sufficient (see #756).

**Comment by aduth** [comment]
I guess we're stuck here with users in the same way we need sites to be part of the Redux state tree. If the current user were part of the global state tree, then `getConnectionsBySiteIdAvailableToCurrentUser` wouldn't need to accept `currentUserId` as a parameter. Certainly not within the scope of this pull request, butbut eventually I'd like to see the function look more like:

```js
export function getConnectionsBySiteIdAvailableToCurrentUser( state, siteId ) {
	const currentUserId = state.users.currentId;
	const connectionsBySiteId = getConnectionsBySiteId( state, siteId );

	return connectionsBySiteId.filter( connection => {
		return connection.shared || connection.keyring_connection_user_ID === currentUserID;
	} );
}
```

**Comment by jkudish** [comment]
Good call -- tests added now. To run them:

`cd shared/lib/sharing/publicize && make test`

Note: last changes also includes a fix for another test in the same folder

**Comment by jkudish** [comment]
> eventually I'd like to see the function look more like:

Yeah that'll be neat when we get there,

File: client/post-editor/editor-drawer/index.jsx (hunk 2 above)
Comment (jkudish) [inline client/post-editor/editor-drawer/index.jsx]: Addressed in df82c94

**Comment by timmyc** [comment]
Thanks for adding those tests in @jkudish - LGTM and tests out well still.
