### PR TITLE
Defer initializing the Guided Tours UI until it's actually displayed

### LINKED ISSUE #22284: Guided Tours: translated strings aren't being used
#### Steps to reproduce
1. under `https://wordpress.com/me/account`, set your language to something other than English
2. go to `https://wordpress.com/post/SITE_URL?tour=editorBasicsTour` to start the Editor Basics Tour

#### What I expected

I expected the tour content to be translated as well, just like the rest of the UI. 

#### What happened instead

The tour content was in English while the rest of the UI was correctly translated. 

#### Screenshot / Video

gt-translate

#### Context / Source

Note that the strings are translated, they're seemingly just not being used ([example](https://translate.wordpress.com/projects/wpcom/de/default/?filters%5Bterm%5D=Write+your+post+in+the+content+area.&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc)). 

Thanks @Copons for the initial report!

### PR DESCRIPTION
**Pull request by jsnajdr**
When profiling the initial load of Calypso, a very visible amount of time is consumed initializing the Guided Tours UI when processing the `makeTour` calls. Their structure is like this:
```jsx
export const EditorBasicsTour = makeTour(
  <Tour>
    <Step name="firstStep">
      <p>{ translate( 'UI of the first step' ) }</p>
    </Step>
    <Step>
      <p>{ translate( 'UI of the first step' ) }</p>
    </Step>
  </Tour>
);
```
That means that the JSX elements for each and every step of each and every tour are created and strings are translated during Calypso initialization, statically, when the `build.js` file is evaluated.

This PR defers part of the initialization by converting the UI part into a "render prop":
```jsx
<Step>
  { props => <p>{ props.translate( 'UI of the step' ) }</p> }
</Step>
```

The initialization of Guided Tours in now faster on the scale of 10-20ms. Not astonishing, but every bit helps.

In addition to the performance benefits, this PR also fixes a bug where the Guided Tours were never localized properly: because the translations are loaded async after initialization, the static `translate` calls at boot time would always work with the `en` locale (fixes #22284).

There are plenty of `Step`s to modify, so I wrote a codemod for that.

**How to test:**
1. Change your user's language to non-English, i.e., Deutsch.
2. Force start of the editor tour by going to post editor URL with a query string:
```
/post/:site/:post?tour=editorBasicsTour
```

Before patch, the UI is partially English:
guided-tour-before

After the patch, the UI is 💯🇩🇪 :
guided-tour-after

### CODE REVIEW

**Comment by samouri** [comment]
```
Commit: f98a1fccfd9a5da0661daa700d9d5ba74c25872b
Delta:
chunk     stat_size           parsed_size           gzip_size
build       +8688 B  (+0.2%)      +2351 B  (+0.2%)     +122 B  (+0.0%)
manifest       +0 B                  +0 B                +1 B  (+0.0%)
```

File: client/layout/guided-tours/docs/examples/tours/simple-payments-end-of-year-guide.js [hunk 1]
```diff
@@ -1,9 +1,10 @@
 /**
  * External dependencies
+ *
+ * @format
```
Comment (samouri) [inline client/layout/guided-tours/docs/examples/tours/simple-payments-end-of-year-guide.js]: this is strange. I wouldn't have expected this to be happening anymore since we should always be formatting files as we add them

File: bin/codemods/src/guided-tours-render.js [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+	stepEls.forEach( stepEl => {
+		/* Extract the children */
+		const stepElValue = stepEl.get().value;
+		const { children } = stepElValue;
+
+		/* Wrap them in a functional component with Fragment */
+		const trIden = j.identifier( 'translate' );
+		const trProp = j.property( 'init', trIden, trIden );
+		trProp.shorthand = true;
+		const fragmentIden = j.jsxIdentifier( 'Fragment' );
```
Comment (samouri) [inline bin/codemods/src/guided-tours-render.js]: any reason you chose `Fragment` over `<>`?

Comment (jsnajdr) [reply bin/codemods/src/guided-tours-render.js]: `<>` requires Babel 7.0 (currently in beta), the 6.x version doesn't understand it.

Also, my Atom editor reports this as a syntax error. I don't know where Atom's JavaScript parser is extendable by packages and how it works in general.

The only part of the toolset that's ready seems to be Prettier :smile:

File: client/layout/guided-tours/docs/examples/tours/simple-payments-end-of-year-guide.js (hunk 1 above)
Comment (jsnajdr) [reply client/layout/guided-tours/docs/examples/tours/simple-payments-end-of-year-guide.js]: This is in a `docs/examples` directory -- maybe it was skipped during the mass-reformat?

File: client/layout/guided-tours/config-elements/step.js [hunk 3]
```diff
@@ -321,7 +325,7 @@ export default class Step extends Component {
 
 		return (
 			<Card className={ classNames( ...classes ) } style={ style }>
-				{ children }
+				<ContentComponent translate={ translate } />
```
Comment (samouri) [inline client/layout/guided-tours/config-elements/step.js]: I've never seen a render prop called in jsx form.
I had to do a double take looking for waht `ContentComponent` was -- but really it is the render function supplied as the 'children'.

**Comment by mcsf** [comment]
Nice to see these improvements!

I suggest, whenever these fixes present the opportunity, to keep the ARCHITECTURE-FUTURE and ARCHITECTURE docs up-to-date:

https://github.com/Automattic/wp-calypso/blob/master/client/layout/guided-tours/docs/ARCHITECTURE-FUTURE.md
https://github.com/Automattic/wp-calypso/blob/master/client/layout/guided-tours/docs/ARCHITECTURE.md

**Comment by jsnajdr** [comment]
@lsinger I'm afraid that wrapping `Step` components with `translate` lambda would make things more complicated:
```jsx
<Tour>
  { ( { translate } ) => (
    <Fragment>
      <Step name="first" />
      <Step name="second" />
    </Fragment>
  ) }
</Tour>
```

The `Tour`'s [render method walks through](https://github.com/Automattic/wp-calypso/blob/master/client/layout/guided-tours/config-elements/tour.js#L29-L31) its `children`, which are `Step` components, and finds the one with the right `name`. Wrapping the Steps inside a function and a fragment would make that lookup more difficult -- one needs to call the function and search in the result, taking the Fragment into consideration.

Also, I'd like to make more clear the distinction between deciding which tour and step should be displayed, and actually rendering that step. The `Tour` and `Step` components implement the decision logic -- they don't render anything, don't need to be React components at all, they are basically conditionals wrapped inside angled brackets. It's only the Step's children that actually render a UI.

The Step's markup should also be created and translated only when the step is actually displayed. I'd like to avoid creating markup for multiple Steps and Tours and then throwing it all away except one.

I'm all for finding ways to make the syntax more friendly, but I think we should keep the general structure:
```jsx
<Tour>
  <Step name="a"><UIForStepA /></Step>
  <Step name="b"><UIForStepB /></Step>
</Tour>
```

**Comment by jsnajdr** [comment]
I rebased this PR on top of latest master and also the commit from #23284. It's ready for review again now.

**Comment by jsnajdr** [comment]
@samouri I pushed a commit that fixes all the eslint errors (missing `img alt` attributes and too long lines)

@mcsf I updated the TUTORIAL.md doc to reflect the new API for the `Step` component. Thanks for the nudge! The architecture docs didn't need any update.

Going to merge in the next few minutes.

**Comment by lsinger** [comment]
Does the API.md file also need updating because of the changes in `Step`?

**Comment by jsnajdr** [comment]
@lsinger That's right, I updated the API.md doc too a few moments ago. Thanks for pointing that out.
