### PR TITLE
Business hours: show 'closed' when data is incomplete for a given interval

### LINKED ISSUE #31027: Business Hours block: Missing hours shows empty day
#### Steps to reproduce
1. Add a business hours block
2. Remove the start or end time from one of the days
3. Deselect the block

#### What I expected

Something to be displayed

#### What happened instead

The day is empty

#### Screenshot / Video

screen shot 2019-02-26 at 14 57 24
screen shot 2019-02-26 at 14 57 14

### PR DESCRIPTION
**Pull request by roccotripaldi**
#### Changes proposed in this Pull Request

* To better align with what is displayed on the front end, let's show 'Closed' when data is malformed or incomplete

screen shot 2019-02-27 at 10 43 11 am

screen shot 2019-02-27 at 10 43 23 am

#### Testing instructions

* [Try out this Jurassic.ninja link](https://jurassic.ninja/create/?gutenpack&shortlived&jetpack-beta&calypsobranch=fix/31027-missing-business-hours)
* Enable beta blocks in Settings -> Jetpack Constants
* Try adding a business hours block in the post editor
* Try creating a day that has missing or incomplete opening hours
* Click off from the block, and ensure 'Closed' is shown for that day
* Click Preview or Publish, and ensure 'Closed' is  also shown for the malformed day

Fixes #31027

### CODE REVIEW

File: client/gutenberg/extensions/business-hours/components/day-save.jsx [hunk 1]
```diff
@@ -22,17 +22,19 @@ class DaySave extends Component {
 	}
 
 	renderInterval = ( interval, key ) => {
+		if ( isEmpty( interval.opening ) || isEmpty( interval.closing ) ) {
+			return key === 0 ? (
```
Comment (lezama) [inline client/gutenberg/extensions/business-hours/components/day-save.jsx]: why this `key === 0` check?

**Comment by jeherve** [comment]
Cherry-picked to the release branch in 55241b87c1a9f4b604f2cc2f19d8fe3c1204b936
