### PR TITLE
Filter USPS packages for international orders

### LINKED ISSUE #1498: Remove or disable predefined boxes from the Purchase Label flow when they can't be used
Some packages make no sense for international shipments. `Regional Rate Box A1-A2-B1-B2` come to mind, but I'm not sure if there are other situations where knowing the origin and destination, we could safely exclude some kinds of boxes.

When the user interacts with the `Packages` step of the Purchase Label modal, the origin and destination are already known. It makes sense to remove from the `Package` dropdown (or at least disable) the options that don't apply. For example, a `Regional` box will never work if the origin and destination are in different countries.

Things to note:
* Double-check what's a "domestic" and "international" shipment for USPS, specially when it involves those non-US territories that have USPS offices.
* What happens if the user had selected an "incorrect" box? Edge case, but since the merchant can change the destination address at label-purchase time, it's something we need to address, and show an error or something (or maybe just keep going with the bogus box and let the error in the `Rates` step inform the user).

### PR DESCRIPTION
**Pull request by v18**
Fixes https://github.com/Automattic/woocommerce-services/issues/1498

The fix works by using the new `can_ship_international` property received from the server (not yet merged) to filter out boxes that cannot be used for international orders. The filtering is done in the `getPackageGroupsForLabelPurchase` selector.

It's unfortunate to add a boolean as an argument to `getPackageGroupsForLabelPurchase`, but since it's a memoized selector, we can only use simple arguments and not objects. If there's a better way to do this, let me know.

I didn't want to unnecessarily filter through the packages results after they're received from the selector, and the selector does seem like the best place for figuring out which packages belong in the list, as opposed to adding this logic to `<PackageInfo />`.

In the future when we support multiple shipping services (in addition to USPS), we'll need to re-think the international package filtering - but we'll also need to re-think a bunch of the other related architecture as well.

# Testing instructions
This can be tested using Calypso and a WooCommerce Services local server.
1. Go to an international (from US to non-US) order on your store on Calypso, e.g. `http://calypso.localhost:3000/store/order/{siteUrl}/{orderId}`
2. See that you can see the regional rate boxes in the drop-down:
all-packages
3. Use the server branch `add/international-shipping-props-for-boxes`

4. Use frequent fetch in a [snippet](https://wordpress.org/plugins/code-snippets/) or wp-config on your site so that the new packages definitions are fetched:
`define( 'WOOCOMMERCE_CONNECT_FREQUENT_FETCH', true );`
5. Open the same order as before, see that the regional rate boxes are no longer shown:
no-intl-packages
6. Open a domestic order, see the regional rate boxes

### CODE REVIEW

File: client/extensions/woocommerce/woocommerce-services/state/packages/selectors.js [hunk 1]
```diff
@@ -89,7 +89,7 @@ export const getAllSelectedPackages = createSelector(
  * @returns {Object} packages grouped by services
  */
 export const getPackageGroupsForLabelPurchase = createSelector(
-	( state, siteId = getSelectedSiteId( state ) ) => {
+	( state, siteId = getSelectedSiteId( state ), isInternationalOrder ) => {
```
Comment (DanReyLop) [inline client/extensions/woocommerce/woocommerce-services/state/packages/selectors.js]: I think it would be cleaner (and several other selectors work that way) if you pass `state, siteId, orderId` as arguments, and use those arguments to check if the order is international.

File: client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/package-info.js [hunk 2]
```diff
@@ -258,13 +260,19 @@ const mapStateToProps = ( state, { orderId, siteId } ) => {
 	const shippingLabel = getShippingLabel( state, orderId, siteId );
 	const storeOptions = loaded ? shippingLabel.storeOptions : {};
 	const errors = loaded && getFormErrors( state, orderId, siteId ).packages;
+	const isInternationalOrder =
+		has( shippingLabel, 'form.destination' ) &&
```
Comment (DanReyLop) [inline client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/package-info.js]: Nitpick: Using `'object.path.represented.as.string'` is significantly slower in lodash because it has to parse the path using a RegExp. `has( shippingLabel, [ 'form', 'destination' ] )` is better.

File: client/extensions/woocommerce/woocommerce-services/state/packages/selectors.js (hunk 1 above)
Comment (v18) [reply client/extensions/woocommerce/woocommerce-services/state/packages/selectors.js]: 👍 

Hehe 😄that's the approach I started with. I switched because none of the packages selectors are aware of the order ID, and I didn't want to add a coupling of the packages state tree and the shippingLabel state tree. But, either way something has to get coupled (either in the selectors, or in the component) and now that I'm re-thinking it, making the selector order-aware as you say is probably better long-term.

File: client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/package-info.js (hunk 2 above)
Comment (v18) [reply client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/package-info.js]: Cool, thanks for the tip.

File: client/extensions/woocommerce/woocommerce-services/state/packages/selectors.js (hunk 1 above)
Comment (v18) [reply client/extensions/woocommerce/woocommerce-services/state/packages/selectors.js]: As an example of a long-term thing that will likely be easier with a selector that's aware of both the packages and shippingLabel: when we add fedex as a shipping service, the list of boxes we'll want to return may depend on a fedex/usps selection, and adding another parameter to the selector will not scale well. Regardless, we'll be able to split the packages and shippingLabel state trees into separate (combined) reducers.

**Comment by v18** [comment]
@DanReyLop - updated

File: client/extensions/woocommerce/woocommerce-services/state/packages/selectors.js [hunk 3]
```diff
@@ -89,12 +92,19 @@ export const getAllSelectedPackages = createSelector(
...
+	( state, orderId, siteId = getSelectedSiteId( state ) ) => {
 		const form = getPackagesForm( state, siteId );
 		if ( ! form || ! form.predefinedSchema || ! form.packages ) {
 			return null;
 		}
 
+		const shippingLabelForm = getForm( state, orderId, siteId );
+		const originCountryCode = getAddressValues( shippingLabelForm.origin ).country;
+		const destinationCountryCode = getAddressValues( shippingLabelForm.destination ).country;
+		const isInternationalOrder =
```
Comment (DanReyLop) [inline client/extensions/woocommerce/woocommerce-services/state/packages/selectors.js]: What I did on an unrelated server change, to prepare this logic for when we open for other countries, was this:
```js
const isDomestic = originCountry === destinationCountry ||
    ( ACCEPTED_USPS_ORIGIN_COUNTRIES.includes( originCountry ) && ACCEPTED_USPS_ORIGIN_COUNTRIES.includes( destinationCountry ) );
```

So, every reasonable case would be covered:
* Canada -> Canada: Domestic
* Canada -> UK: International
* Canada -> US: International
* US -> Puerto Rico: Domestic
* etc

It doesn't matter right now, but it would be one less thing to think about when/if we open labels to other carriers.

**Review by DanReyLop — APPROVED** [review]
Code looks good and works as expected :)
:shipit:

**Comment by jeffstieler** [comment]
I'll go ahead and take the merge+deploy since @v18 is AFK today.
