### PR TITLE
Show loading state while removing domain from minicart

### LINKED ISSUE #101880: Onboarding: Domains: Inaccurate pricing while removing domains
Similar to #101839, when you _remove_ a domain from the mini cart, it displays an incorrect price temporarily while the API request is happening.

https://github.com/user-attachments/assets/ba42f1dd-369b-40bc-8779-3f0147ba9b45

### PR DESCRIPTION
**Pull request by p-jackson**
Fixes https://github.com/Automattic/wp-calypso/issues/101880
Related to https://github.com/Automattic/wp-calypso/pull/101839

## Proposed Changes

* Do not show total price while a domain is being removed
  * You'd think we could show the real price while a domain is being removed because we'd just sum up the remaining domains. However it doesn't work like this because after round tripping to the server we may discover that some discount is now applied differently (e.g. if you removed the free-for-one-year domain)
* Show the correct total while domains are being removed
  * The old logic had something to do with `temporaryCart`, but it seems like the logic had gone stale.
* I removed the `temporaryCart` prop from the mini cart component since it's no longer used.
  * Claude said that `temporaryCart` is where pending domains are supposed to sit before while the API request is being made. Once the API request is successful it moves the domain from `temporaryCart` to `domainsInCart` array. However these two arrays are merged before being passed to the mini cart component. So I think this is not how the mini cart is supposed to work. https://github.com/Automattic/wp-calypso/blob/270eb3edaf8010e03790e970ec5c8184e9191cf9/client/signup/steps/domains/index.jsx#L939-L949

Pinging @paulopmt1 to see if he can remember what the deal is with the temporary array (found some of your previous work https://github.com/Automattic/wp-calypso/pull/84171)

## Why are these changes being made?

*

## Testing Instructions

**Before**

https://github.com/user-attachments/assets/ba42f1dd-369b-40bc-8779-3f0147ba9b45

**After**

https://github.com/user-attachments/assets/c76dbcc3-621f-4cc5-ba07-cb7ebe42982b

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/signup/steps/domains/domains-mini-cart.jsx [hunk 1]
```diff
@@ -149,8 +149,22 @@ export class DomainsMiniCart extends Component {
...
 	};
 
+	formatCartTotal = () => {
+		const isRemovingDomain = this.props.domainsInCart.some( ( domain ) =>
+			this.props.domainRemovalQueue.some( ( removalItem ) => removalItem.meta === domain.meta )
+		);
+
+		const hasTemporaryDomain = this.props.domainsInCart.some( ( domain ) => domain.temporary );
+
+		return isRemovingDomain || hasTemporaryDomain
```
Comment (paulopmt1) [inline client/signup/steps/domains/domains-mini-cart.jsx:159]: Showing the total cost after removing the domain makes sense; we don't need to attempt to calculate that upfront.

File: client/signup/steps/domains/domains-mini-cart.jsx [hunk 2]
```diff
@@ -112,15 +115,12 @@ export class DomainsMiniCart extends Component {
...
-					result--;
-				}
-			} );
-		}
+		// Deduct domains from the count that are on the removal queue
+		this.props.domainRemovalQueue?.forEach( ( item ) => {
+			if ( this.props.domainsInCart.some( ( domain ) => domain.meta === item.meta ) ) {
+				result--;
+			}
+		} );
```
Comment (paulopmt1) [inline client/signup/steps/domains/domains-mini-cart.jsx:123]: IIRC this was only a redundancy measurement. I couldn't simulate bugs without the temporaryCart on this logic, so we're safe.

File: client/signup/steps/domains/domains-mini-cart.jsx [hunk 3]
```diff
@@ -149,8 +149,22 @@ export class DomainsMiniCart extends Component {
 		);
 	};
 
+	formatCartTotal = () => {
```
Comment (paulopmt1) [inline client/signup/steps/domains/domains-mini-cart.jsx:152]: Thanks for extracting and reusing it!

**Review by paulopmt1 — APPROVED** [review]
It's working as expected, thanks for these improvements and bufixes @p-jackson!

> Claude said that temporaryCart is where pending domains are supposed to sit before while the API request is being made. Once the API request is successful it moves the domain from temporaryCart to domainsInCart array. 

Yeah, the `temporaryCart` allow us to instantly add a domain to our miniCart. Before it, we needed to wait the roundtrip from the server.

> However these two arrays are merged before being passed to the mini cart component. So I think this is not how the mini cart is supposed to work.

Since [we're filtering that](https://github.com/Automattic/wp-calypso/blob/fix/mini-cart-loading-state-removing-domain/client/signup/steps/domains/index.jsx#L941) we only use one instance of each.

**Comment by p-jackson** [comment]
😌 I'm glad you remember working on this @paulopmt1 because I was scared of making cart changes!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17316928).
