### PR TITLE
Users: Adds polling to SiteUsersFetcher data component

### LINKED ISSUE #3936: People: List of users doesn't refresh when a user is added
#### Steps to reproduce
1. Starting at URL: /people/team/[site]
2. Leave this page open, and then add another person to your site
3. The page does not update, I have to refresh the page to see the new person in the list.

This means there is no way to see a new user in the desktop app.

#### What I expected

The list to show the new person added.

#### What happened instead

Nothing changed.

/cc @ebinnion

### PR DESCRIPTION
**Pull request by ebinnion**
Fixes #3936.

Previously, we didn't employ polling for the team list at `/people/team/$site`. While this is fine for web, this present an issue for the desktop apps.

To test:
- Checkout `update/people-lists-poll` branch
- Go to `/people/team/$site` where `$site` is a Jetpack site (WP.com will work as well, but it's easier to add users to Jetpack sites)
- In another tab, go to `$site/wp-admin` and add a user
- Within 30 seconds, the user should be added to the team list
- Go to `/post/$site`
- Click on the author selector near the top left of the editor to drop down a list of authors for your site
- Delete the user we added before
- Within 30 seconds, the user should be removed from that list

cc @rralian and @lezama for review.

### CODE REVIEW

File: client/lib/users/actions.js [hunk 1]
```diff
@@ -11,16 +11,18 @@ const Dispatcher = require( 'dispatcher' ),
...
 		const paginationData = UsersStore.getPaginationData( fetchOptions );
 		if ( paginationData.fetchingUsers ) {
 			return;
 		}
 		debug( 'fetchUsers', fetchOptions );
-		Dispatcher.handleViewAction( {
-			type: 'FETCHING_USERS',
-			fetchOptions: fetchOptions
-		} );
+		if ( ! silentUpdate ) {
```
Comment (lezama) [inline client/lib/users/actions.js]: just curious, what happens if we don't do this?

**Comment by lezama** [comment]
LGTM :+1:

File: client/lib/users/actions.js (hunk 1 above)
Comment (ebinnion) [inline client/lib/users/actions.js]: It dispatches the `FETCHING_USERS` event, which updates the UI. In the cases of people management and the author selector, that results in a placeholder being put at the bottom of the list.
