### PR TITLE
Plugin Upload: offer a WP Admin link in case of plugin already existing.

### LINKED ISSUE #58508: Plugin Upload: not possible to upgrade / downgrade plugins by uploading a zip file
### Quick summary

On the new Plugin Marketplace is not possible to update custom plugins by uploading a zip file with the new version 

### Steps to reproduce

1. On an Atomic site, install a custom plugin. You test it with this one: [my-custom-plugin.zip](https://github.com/Automattic/wp-calypso/files/7603262/my-custom-plugin.zip)
2. Then, try to update it by uploading the new version in a zip file via the Marketplace. This is the 1.1 version of the previous plugin: 
[my-custom-plugin.zip](https://github.com/Automattic/wp-calypso/files/7603308/my-custom-plugin.zip)

### What you expected to happen

Land in a page, like it's happening on WP Admin, indicating that the plugin already exists, and allowing to update it: 

Markup on 2021-11-25 at 14:34:28

### What actually happened

Got the error that the plugin is already installed on the site:

Markup on 2021-11-25 at 14:31:55

### Context

_No response_

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

_No response_

### Other notes

_No response_

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

As mentioned on #58322, users can use the WP Admin URL: `/wp-admin/plugin-install.php`.

### PR DESCRIPTION
**Pull request by cpapazoglou**
#### Changes proposed in this Pull Request

This PR attempts to:
- better explain the plugin upload error in case of folder already existing
- allow the user to get self serviced by offering a WP Admin link to upload the plugin
- change all error messages to use `line` prop instead of `title`. Line seems having a better font-size.

#### Testing instructions

|Before | After|
|-------|------|
|SS 2021-12-08 at 15 58 23|SS 2021-12-08 at 16 14 20|

**Folder Exists Scenario**
- visit `/plugins/upload/[domain]` of an Atomic site
- drop a zip of an already uploaded plugin
- you should get the new screen
- click `Continue`, you should be redirected to WP Admin `Add New` screen

**Regression Testing, Other Upload error**
- visit `/plugins/upload/[domain]` of an Atomic site
- drop a zip which is not a plugin
- you should get the `An error occurred while installing the plugin` screen

Fixes #58508

### CODE REVIEW

File: client/my-sites/marketplace/pages/marketplace-plugin-upload-status/index.tsx [hunk 1]
```diff
@@ -53,6 +53,7 @@ const MarketplacePluginInstall = ( {
 	const siteId = useSelector( getSelectedSiteId ) as number;
 	const pluginUploadProgress = useSelector( ( state ) => getPluginUploadProgress( state, siteId ) );
 	const pluginUploadError = useSelector( ( state ) => getPluginUploadError( state, siteId ) );
+	const pluginExists = pluginUploadError?.error === 'folder_exists' || false;
```
Comment (WBerredo) [inline client/my-sites/marketplace/pages/marketplace-plugin-upload-status/index.tsx]: Nitpicking: I think a validation (`===`) will always return a boolean, not sure if we'll ever need the `|| false` part.

File: client/my-sites/marketplace/pages/marketplace-plugin-upload-status/index.tsx [hunk 2]
```diff
@@ -256,14 +259,31 @@ const MarketplacePluginInstall = ( {
...
 				/>
 			);
 		}
+		if ( pluginExists ) {
+			return (
+				<EmptyContent
+					illustration="/calypso/images/illustrations/error.svg"
+					title={ null }
+					line={ translate(
+						'This plugin already exists in your site. If you want to upgrade/ downgrade it please continue by uploading again from WP Admin.'
```
Comment (WBerredo) [inline client/my-sites/marketplace/pages/marketplace-plugin-upload-status/index.tsx]: Shouldn't we use `upgrade/downgrade` instead of `upgrade/ downgrade`?

```suggestion
						'This plugin already exists in your site. If you want to upgrade/downgrade it please continue by uploading again from WP Admin.'
```

**Review by WBerredo — COMMENTED** [review]
It is working as expected on my tests, just find it a bit odd to see the **back** button with the primary color and the **continue** in white. I think we are working with the opposite pattern, isn't it?

File: client/my-sites/marketplace/pages/marketplace-plugin-upload-status/index.tsx (hunk 1 above)
Comment (cpapazoglou) [reply client/my-sites/marketplace/pages/marketplace-plugin-upload-status/index.tsx]: True ;-), ec44803

File: client/my-sites/marketplace/pages/marketplace-plugin-upload-status/index.tsx (hunk 2 above)
Comment (cpapazoglou) [reply client/my-sites/marketplace/pages/marketplace-plugin-upload-status/index.tsx]: I am always adding a space after punctuation marks but I don't have a strong opinion here. @emmnyc85 any preference here?

**Comment by cpapazoglou** [comment]
> It is working as expected on my tests, just find it a bit odd to see the **back** button with the primary color and the **continue** in white. I think we are working with the opposite pattern, isn't it?

In fact I tried this, but the primary action is always shown first and results to `Continue`, `Back`. 
SS 2021-12-08 at 18 38 04

Do you prefer it?

**Comment by cpapazoglou** [comment]
After a very quick poll I reverted them p1638981610346300-slack-C029JEQRVRT

dbf13a7

**Review by WBerredo — APPROVED** [review]
Happy with the changes.

It can get merged as soon as we have a decision about the `upgrade/downgrade` text.

File: client/my-sites/marketplace/pages/marketplace-plugin-upload-status/index.tsx (hunk 2 above)
Comment (emmnyc85) [reply client/my-sites/marketplace/pages/marketplace-plugin-upload-status/index.tsx]: 'This plugin already exists on your site. If you want to upgrade or downgrade the plugin, please continue by uploading the plugin again from WP Admin.'

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7031317

Thank you @cpapazoglou for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7031317).
