### PR TITLE
Billing: Fix search with null or undefined transaction data

### LINKED ISSUE #13254: Billing: can't search for upcoming charges
1. Navigate to https://wordpress.com/me/purchases/billing
2. Scroll down to Upcoming Charges
screen shot 2017-04-19 at 4 32 11 pm
3. Type some text into the search box
Expected: search to filter entries
Actual: js errors are thrown
screen shot 2017-04-19 at 4 32 23 pm

cc @tyxla

### PR DESCRIPTION
**Pull request by tyxla**
This PR fixes #13254, where searching in billing transactions that have one or more `null` or `undefined` attributes can cause an issue.

To test:
* Make sure you have at least one transaction with `null` or `undefined` attribute. Or use @gwwar's WordPress.com account :stuck_out_tongue_winking_eye: 
* Go to `/me/purchases/billing`
* Try searching and verify it doesn't break.

### CODE REVIEW

File: client/me/billing-history/table-rows.js [hunk 1]
```diff
@@ -1,21 +1,24 @@
...
 }
 
 function getSearchableStrings( transaction ) {
-	var rootStrings = values( omit( transaction, 'items' ) ),
+	const rootStrings = values( omit( transaction, 'items' ) ),
 		transactionItems = transaction.items || [],
-		itemStrings = flatten( transactionItems.map( values ) );
+		itemStrings = without( flatten( transactionItems.map( values ) ), null, undefined );
 
 	return rootStrings.concat( itemStrings );
```
Comment (gwwar) [inline client/me/billing-history/table-rows.js]: rootStrings may also contain falsey values, so let's move the without to this line:
```
return without( rootStrings.concat( itemStrings ), null, undefined );
```

Comment (tyxla) [inline client/me/billing-history/table-rows.js]: :+1: fixed in 0f49dfba9e68c91533de9b455ea8d21e8d5b6346.
