### PR TITLE
Ignores the protocol while sanitizing external urls in sidebar.

### LINKED ISSUE #50371: Nav Unification: plugins item does not link to plugins page
### Steps to reproduce the behavior

Reproduces while on Spanish locale, but it may apply to all locales (needs triaging)

1. Go to customer home (`/home`)
2. Click on the "Plugins" nav item
3. Notice how the browser doesn't navigate to the plugins page

#### What I expected to happen

The browser should navigate to the plugins page

#### Environment

Business plan (Atomic) on Calypso

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/1083581/108842318-60f5b300-75d9-11eb-81af-47e428f9fc4d.mp4

### PR DESCRIPTION
**Pull request by cpapazoglou**
#### Changes proposed in this Pull Request

* Ignore the protocol while sanitizing external urls to be used in the sidebar navigation.

#### Testing instructions

* On trunk Go to https://github.com/Automattic/wp-calypso/blob/dcabd91c78a8f8096aa8b3e18a1235bab7a2c055/client/state/data-layer/wpcom/sites/admin-menu/index.js#L60 and replace it with `const wpAdminUrl = "http://[DOMAIN]/wp-admin"`
* Inspect that external links are all empty (they link to home)
* On this branch, external links should appear as expected

Before | After
-------|------
 | 

Fixes #50371

### CODE REVIEW

File: client/state/data-layer/wpcom/sites/admin-menu/index.js [hunk 1]
```diff
@@ -20,7 +20,11 @@ export const requestFetchAdminMenu = ( action ) =>
 
 const sanitizeUrl = ( url, wpAdminUrl ) => {
 	const isSafeInternalUrl = new RegExp( '^/' ).test( url );
-	const isSafeWpAdminUrl = new RegExp( `^${ wpAdminUrl }` ).test( url );
+	// The replace function removes the protocol.
+	const isSafeWpAdminUrl = new RegExp( `^${ wpAdminUrl?.replace( /(^\w+:|^)\/\//, '' ) }` ).test(
+		url?.replace( /(^\w+:|^)\/\//, '' )
+	);
```
Comment (mmtr) [inline client/state/data-layer/wpcom/sites/admin-menu/index.js]: What do you think about using this more readable regex?

```suggestion
	const isSafeWpAdminUrl = new RegExp( `^${ wpAdminUrl?.replace( /^https?:\/\//, '' ) }` ).test(
		url?.replace( /^https?:\/\//, '' )
	);
```

**Review by mmtr — APPROVED** [review]
This tests well for me, nice sleuthing @cpapazoglou! I left a minor non-blocking comment regarding the readability of the regex.

File: client/state/data-layer/wpcom/sites/admin-menu/index.js (hunk 1 above)
Comment (cpapazoglou) [reply client/state/data-layer/wpcom/sites/admin-menu/index.js]: I guess it's ok since we only expect an http protocol.
