### PR TITLE
Reader: post author & subscribe button on smaller screen sizes

### LINKED ISSUE #93781: Post details view is missing the author and the subscribe button
### Quick summary

The post details view in the reader lacks important information that the readers may need, and the authors would like to be there.

### Steps to reproduce

1. Go to /read and click any post
2. No author and subscribe button, the site title is visible but at the bottom

### What you expected to happen

Here's how it looks in the Mobile Reader

IMG_8980

Site, Author, and Subscribe are at the top, clearly visible (okay, a bit hidden but clearly there)

### What actually happened

Screenshot 2024-08-21 at 17 32 47

Who wrote that? How do I subscribe? There's a follow conversation button instead of subscribe, which is probably also worth removing to not confuse the audience from what's important.

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Chrome, Desktop

### PR DESCRIPTION
**Pull request by TimBroddin**
Related to https://github.com/Automattic/wp-calypso/issues/93781

## Proposed Changes

This PR shows the site author & subscribe button underneath the post title on smaller screen sizes.

Before | After
--|--
Screenshot 2024-08-30 at 12 16 09 PM  | Screenshot 2024-08-30 at 12 15 54 PM

Before | After
--|--
Screenshot 2024-08-30 at 12 17 02 PM  | Screenshot 2024-08-30 at 12 16 34 PM

This PR probably needs some eyes from someone from design (cc @JanaMW27)

## Testing Instructions

1. Use Calypso Live
2. View a Reader post and resize your screen to various widths
3. Here is an example of header variants to test:

- /read/blogs/103780599/posts/22023
- /read/blogs/19734/posts/69499
- /read/feeds/160601169/posts/5312674212
- /read/blogs/236514021/posts/4
- /read/blogs/85208038/posts/43734

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by DustyReagan — COMMENTED** [review]
It looks like the profile icon is overlapping the title on Medium widths.

From the Discover tab:
Screenshot 2024-08-28 at 10 10 50 AM

From the Recent tab:
Screenshot 2024-08-28 at 10 08 07 AM

File: client/blocks/reader-full-post/header.jsx [hunk 1]
```diff
@@ -43,6 +43,7 @@ const ReaderFullPostHeader = ( { post } ) => {
 					</h1>
 				</AutoDirection>
 			) : null }
+			<div className="reader-full-post__author-block">{ authorProfile }</div>
```
Comment (DustyReagan) [inline client/blocks/reader-full-post/header.jsx:46]: Added a new class name here to target to prevent the new CSS from leaking / causing regressions elsewhere.

File: client/blocks/author-compact-profile/index.jsx [hunk 2]
```diff
@@ -65,22 +65,23 @@ class AuthorCompactProfile extends Component {
...
-						className="author-compact-profile__site-link"
-						feedId={ feedId }
-						siteId={ siteId }
-						post={ post }
-					>
-						{ siteName }
-					</ReaderSiteStreamLink>
-				) }
-
+				<div className="author-compact-profile__names">
```
Comment (DustyReagan) [inline client/blocks/author-compact-profile/index.jsx:68]: Wrapped these elements in a div with a class name.

File: client/blocks/reader-full-post/style.scss [hunk 3]
```diff
@@ -665,3 +665,125 @@ $reader-full-post-desktop-min: $reader-full-post-sidebar-width + $reader-full-po
...
+					position: relative;
+					left: 18px;
+					top: -18px;
+					vertical-align: bottom;
+					max-width: initial;
+				}
+
+				.site-icon,
+				.gridicon {
+					height: 32px !important;
```
Comment (davemart-in) [inline client/blocks/reader-full-post/style.scss:732]: I'm sure this is intentional, but just making sure that these `!important`'s are absolutely needed.

**Review by davemart-in — APPROVED** [review]
Changes look solid. I tested on subscribed and not subscribed sites.

File: client/blocks/reader-full-post/style.scss (hunk 3 above)
Comment (DustyReagan) [reply client/blocks/reader-full-post/style.scss:732]: I was able to remove one `!important` by increasing the selector specificity https://github.com/Automattic/wp-calypso/pull/93816/commits/57ae25a9108953498d415d131a1b86fc79fbdd0e. The remaining `!important`s are overriding inline styles.
