### PR TITLE
Themes: Update Thanks Modal

### LINKED ISSUE #11046: Themes: welcome message modal for Jetpack has wrong links
lmohjmr9f1

Let's update the welcome modal for Jetpack users:

1. The “awesome theme” link takes me to https://wordpress.com/themes/orvis/ rather than https://wordpress.com/theme/orvis or https://wordpress.com/theme/orvis/www.richardmuscatistestingthings.com as other “Info” links around the UI do
2. The phrasing of the first bullet point seems off for. Suggest: “[Learn more](#) about this theme.” or “[Learn more](#) about your new active theme.”
The “contact theme author” link simply drops me at https://wordpress.com/themes/ which feels incorrect

/ht @richardmuscat

### PR DESCRIPTION
**Pull request by ockham**
Link to theme sheets for Jetpack sites, too.
Simplify some methods.
Remove line about WP.org theme forums -- we displayed that conditionally if there was no theme info link. Since we now always provide a theme info link, I think we can drop the other one.

Fixes #11046

To test: Verify that #11046 is fixed and nothing else breaks 😄
More specifically:
* Check that the thanks modal's URLs point to all the right locations:
  * try dotcom themes, dotorg-only themes, and themes that are in neither repo
* Try activating both from the list and theme sheet
  * From the list, the thanks modal's upper bullet point should point to theme info (i.e. the sheet)
  * From the sheet, it should point to the customizer

### CODE REVIEW

File: client/my-sites/themes/thanks-modal.jsx [hunk 1]
```diff
@@ -92,17 +87,16 @@ const ThanksModal = React.createClass( {
...
 			return (
-				<li>
-					{ translate( 'Learn more about this {{a}}awesome theme{{/a}}.', {
-						components: {
-							a: <a href={ themeUri }
-								onClick={ this.onLinkClick( 'org theme' ) } />
-						}
-					} ) }
-				</li>
+				translate( '{{a}}Learn more about{{/a}} this theme.', {
```
Comment (a8ci18n) [inline client/my-sites/themes/thanks-modal.jsx]: Hi! I've found a possible matching string that has already been translated **21** times:
`translate( 'Learn more about this {{a}}awesome theme{{/a}}.' )` *ES Score: 6.35*

Help me improve these suggestions: react with :thumbsdown: if the suggestion doesn't make any sense, or with :thumbsup: if it's a particularly good one (even if not implemented).

**Comment by budzanowski** [comment]
In genera it looks very nice. From #11046:

> The “contact theme author” link simply drops me at https://wordpress.com/themes/ which feels incorrect

I still drops to that place.

**Comment by seear** [comment]
Should we be using the [`isWpcomTheme`](https://github.com/Automattic/wp-calypso/blob/master/client/state/themes/selectors.js#L332) selector instead of jetpack site to decide what to render?

I'm refining that selector in #11087

**Comment by folletto** [comment]
Seems working well.

And yes:

> The “contact theme author” link simply drops me at https://wordpress.com/themes/ which feels incorrect

Which however happens only on .com themes, if I try the same on a Jetpack theme it points to the `style` author website.

If we can recognize it's one of our themes we can just point to our support forum instead? i.e. `en.forums.wordpress.com/forum/themes`

**Comment by ockham** [comment]
Pushed a commit that should _theoretically_ fix behavior as desired. However, it doesn't 😄 
Reason: The active theme endpoint returns the `-wpcom` suffixed theme ID, and we can't use that to find out if `isWpcomTheme` since that's equivalent to `!! getTheme( state, 'wpcom', themeId )`-- and it certainly won't find the suffixed theme ID there.

However, we can't use the `isThemeFromWpcom` util (which checks for the `-wpcom` suffix) either if we want to use the same check on WP.com sites, since they're unprefixed there.

So the issue is really that the active theme endpoint returns the suffixed theme ID in the first place IMO. Another piece of evidence against that thing I'd say.

**Comment by ockham** [comment]
And yeah, as for any checks for fields like `theme_uri` -- those won't work that well here either, since we'd need to `getTheme( state, siteId, themeId )` in the first place -- but do we check in the `siteId` or `wpcom` subtree?

File: client/my-sites/themes/thanks-modal.jsx [hunk 2]
```diff
@@ -81,71 +77,47 @@ const ThanksModal = React.createClass( {
...
-						components: {
-							a: <a href={ themeUri }
-								onClick={ this.onLinkClick( 'org theme' ) } />
-						}
-					} ) }
-				</li>
-			);
-		}
+	renderThemeInfo() {
+		return translate( '{{a}}Learn more about{{/a}} this theme.', {
```
Comment (a8ci18n) [inline client/my-sites/themes/thanks-modal.jsx]: Hi! I've found a possible matching string that has already been translated **22** times:
`translate( 'Learn more about this {{a}}awesome theme{{/a}}.' )` *ES Score: 9.68*

Help me improve these suggestions: react with :thumbsdown: if the suggestion doesn't make any sense, or with :thumbsup: if it's a particularly good one (even if not implemented).

**Comment by ockham** [comment]
Should be unblocked by #11330. However, still some issues, since e.g. the WP.org API doesn't seem to return `author_uri`. Maybe I can make it do using [the `request[fields]` arg](https://codex.wordpress.org/WordPress.org_API#Arguments:_2)...

**Comment by folletto** [comment]
We can approach this by simplifying: let's not add the line if the field is empty, so we fix the modal and it's not broken anymore, and then we review later.

**Comment by ockham** [comment]
> the WP.org API doesn't seem to return `author_uri`. Maybe I can make it do using [the `request[fields]` arg](https://codex.wordpress.org/WordPress.org_API#Arguments:_2)...

A quick chat with @stephdau revealed that the API really isn't exposing that field. Waiting for our Apollo friends to maybe add it 😁

**Comment by ockham** [comment]
(In the meantime, I'm happy to go with a shortcut solution @folletto)

**Comment by ockham** [comment]
Filed https://meta.trac.wordpress.org/ticket/2521#ticket

**Comment by folletto** [comment]
Checked:

1. Activated a .org theme → name & author — ✅ 
2. Activated a .org theme → "Learn more about" — ✅ 
3. Activated a .org theme → "support forums" — ✅ 

If I haven't missed checking something, seems shippable to me :y:

**Comment by ockham** [comment]
> Activated a .org theme → "support forums" — ✅

That was pointing to the wrong location (WP.com generic theme forums). Latest commit should fix it.

**Comment by ockham** [comment]
@folletto On a Jetpack site, what support forum URL do we return for
* A theme that's on WP.com and on WP.org
* A theme that's on WP.com but not on WP.org?

**Comment by ockham** [comment]
(Asking because right now with this PR,

> A theme that's on WP.com but not on WP.org

returns `null` for the support forums URL, i.e. we get a link that's not pointing anywhere 😕 )

**Comment by folletto** [comment]
> A theme that's on WP.com and on WP.org
> A theme that's on WP.com but not on WP.org?

Ideally we provide support, so should link to .com forums. :)

File: client/my-sites/themes/thanks-modal.jsx [hunk 3]
```diff
@@ -61,92 +62,59 @@ const ThanksModal = React.createClass( {
...
+	renderSupportInfo() {
+		const { author_uri: authorUri } = this.props.currentTheme;
 
-	renderJetpackInfo() {
-		const {
-			theme_uri: themeUri,
-			author_uri: authorUri
-		} = this.props.currentTheme;
+		if ( this.props.forumUrl ) {
+			return translate( 'Have questions? Stop by our {{a}}support forums{{/a}}.', {
```
Comment (a8ci18n) [inline client/my-sites/themes/thanks-modal.jsx]: Hi! I've found a possible matching string that has already been translated **25** times:
`translate( 'Have questions? Stop by our {{a}}support forums.{{/a}}' )` *ES Score: 16.56*

Help me improve these suggestions: react with :thumbsdown: if the suggestion doesn't make any sense, or with :thumbsup: if it's a particularly good one (even if not implemented).

**Comment by ockham** [comment]
Found a number of other regressions with this that should now be fixed. Can you give this another round of testing and reviewing, folks? I added more detailed testing instructions to the PR desc.

**Comment by budzanowski** [comment]
I love how thanks modal links to two different places depending from where it comes :heart: 
Code looks good!

**Comment by folletto** [comment]
Checked on Chrome:

1. Jetpack — .com theme URLS — ✅ 
2. Jetpack — .org theme URLS — ✅ 
3. Jetpack — custom theme URLS — ✅  
4. Jetpack — .com theme activate (list) — ✅ 
5. Jetpack — .org theme activate (list) — ✅ 
6. Jetpack — custom theme activate (list) — ✅ 
7. Jetpack — .com theme activate (sheet) — ✅ 
8. Jetpack — .org theme activate (sheet) — ✅ 
9. Jetpack — custom theme activate (sheet) — ✅ 

Ship! :shipit:
