### PR TITLE
Help: Fix chat ended experience

### LINKED ISSUE #1337: Help: Make the "HEs have returned" notice dismissable
Repro:

1. Target a chat group with no operators available.
2. Load /help/contact.
3. Observe that the form will submit a ticket.
4. Have an operator become available and wait a moment.
5. Observe the green notice that an operator is available.

I'm thinking it might be nice if we could dismiss this notice, since if you've already scrolled down a bit, it covers some of the UI and is kind of annoying. I think maybe there is built-in dismiss UI/functionality in the notification component and that we just need to set a prop or something. Here's what it looks like at present:

screen shot 2015-12-07 at 1 34 52 pm

### LINKED ISSUE #1340: Help: Ending a chat results in the "leave a message" chat box
Repro:

1. Target a chat group with operators available.
2. Load /help/contact.
3. Initiate a chat.
4. Navigate around a bit (away from /help/contact).
5. As an operator, end the chat. In my test, I was the only operator available, and I was at my chat limit, so when I ended, no operators were available.

I wound up seeing this after the chat ended:

screen shot 2015-12-07 at 2 12 15 pm

It's the offline message form, but there's not a way to fill it out. It seems like we'd want the chat box to behave differently in this case. It may be ok to show the "Leave a message" form (in fact, Olark may not afford us much of an alternative), but if we do, it should be submittable (note from the screen capture that there's no button and no text entry field). 

Or maybe we should just hide the box altogether when a chat ends, since by default it won't be displayed at bottom right all the time anyway once this ships.

### LINKED ISSUE #1341: Help: Ending a chat while a user is on /help/contact is a jarring experience.
Repro:

1. Target a group with operators available.
2. Navigate to /help/contact and initiate a chat.
3. As an operator, end the chat.

Expected: There'll be some reasonable indicator that the chat has ended.

Actual: The screen refreshes to the offline contact form and shows the `Sorry! We just missed you as our Happiness Engineers stepped away.` notification. 

To better illustrate the interaction, here's a gif of the interaction:

chat-end

It's a pretty jarring experience. I'm not sure what the proper experience here is. Maybe on `!end` in this scenario, we could show a notification that the chat has been ended and disable the text entry field? Cc @mattmiklic for design feedback.

### PR DESCRIPTION
**Pull request by omarjackman**
## Fix "chat has ended" experience.
This pull request aims to fix the jarring experience a user might have when a chat has ended and there are no operators available. 

#### Whats changed
* Removed the operator availability notifications that currently show up inside of the olark chat widget.
* Added calypso notifications to indicate olark operator availability when the chatbox is expanded or while viewing the contact form.
* Show a notification within the olark widget immediately after an operator sends the `!end` command.
* Allow the calypso notices to be dismissed.

#### How to test
*Note: You must be in a group that has one operator*
1. Navigate to http://calypso.localhost:3000/help/contact
2. Start a chat
3. Leave the contact form by clicking on any link in the sidebar.
4. Have the operator end the chat with the `!end` command.
5. Have the operator set them self as "Away" in olark.
6. Notice that the notification that operators went away now appears.
7. Have the operator set them self as "Available" in olark.
8. Notice that the notificaiton appears again saying that operators have returned.
9. Collapse the olark widget and repeat steps 5 and 7. Notice that no availability messages were displayed because the olark widget is collapsed.

**Before**
screen shot 2015-12-17 at 4 50 46 am

screen shot 2015-12-17 at 2 43 58 am

screen shot 2015-12-17 at 2 44 15 am

**After**
screen shot 2015-12-17 at 2 06 56 pm

screen shot 2015-12-17 at 4 28 45 am

screen shot 2015-12-17 at 4 32 54 am

screen shot 2015-12-17 at 2 40 10 am

Fixes #1340
Fixes #1341
Fixes #1337

### CODE REVIEW

File: client/lib/olark/index.js [hunk 1]
```diff
@@ -164,6 +168,24 @@ const olark = {
...
 	},
 
+	showAvailabilityNotice() {
+		const { details, isOperatorAvailable } = olarkStore.get();
+		const noticeOptions = {
+			duration: 10000,
+			showDismiss: false
+		};
+
+		if ( ! ( details.isConversing || window.location.pathname === '/help/contact' ) ) {
```
Comment (omarjackman) [inline client/lib/olark/index.js]: `window.location` being here might raise a few eyebrows but its here because I was trying to avoid duplication in the `HelpContact` component.

**Comment by omarjackman** [comment]
cc @mtias @dllh review please

**Comment by dllh** [comment]
I tested this a bit, and it's working well for me. Would rather have another set of eyes on the code, though it looked fine to my somewhat inexperienced eye.

**Comment by dllh** [comment]
I did some more testing and it still feels really good on the whole. I think it's a little weird still that in the case of no operators and and ended chat, we re-render the contact form with chat in the lower right and a notice rather than just showing the inline chat with some ui indicating that the chat is done (like what's displayed [here](https://cloud.githubusercontent.com/assets/1396552/11723650/796c28c4-9f3d-11e5-9b3b-490bafa12162.png)), but I think that on the whole, this is a big improvement and we should try to get the code reviewed asap and get this merged.

**Comment by omarjackman** [comment]
> I think it's a little weird still that in the case of no operators and and ended chat

@dllh this is fixed now.

**Comment by omarjackman** [comment]
cc @mtias @dmsnell review please

File: client/lib/olark-events/index.js [hunk 2]
```diff
@@ -78,7 +78,7 @@ var OlarkEventEmitter = {
 	 */
 	olarkEventListener: function( event, ...eventArguments ) {
 		debug( 'Olark event: %s', event );
-		this.emit( event, eventArguments );
+		this.emit( event, ...eventArguments );
```
Comment (dmsnell) [inline client/lib/olark-events/index.js]: This is a 0.5 out of 10 as far as being an important critique, but is `eventArguments` a little verbose when something like `args` seems like it would convey the same meaning?

```js
olarkApi( event, ( ...args ) => this.olarkEventListener( event, ...args ) );

…
olarkEventListener( event, ...args ) {
	this.emit( event, ...args );
}
```

File: client/lib/olark-store/actions.js [hunk 3]
```diff
@@ -45,6 +45,13 @@ const olarkActions = {
 		} );
 	},
 
+	setExpanded( isOlarkExpanded ) {
+		dispatcher.handleServerAction( {
+			isOlarkExpanded,
+			type: ActionTypes.OLARK_EXPANDED
```
Comment (dmsnell) [inline client/lib/olark-store/actions.js]: This is _slightly_ confusing. Maybe `OLARK_SET_EXPANDED` would be a clearer indication that the action is doing something.

File: client/lib/olark/index.js [hunk 4]
```diff
@@ -148,10 +156,32 @@ const olark = {
 		olarkEvents.on( 'api.chat.onOperatorsAway', olarkActions.setOperatorsAway );
 		olarkEvents.on( 'api.chat.onOperatorsAvailable', olarkActions.setOperatorsAvailable );
 
+		olarkExpandedEvents.forEach( ( event ) => olarkEvents.on( event, () => {
```
Comment (dmsnell) [inline client/lib/olark/index.js]: `event` seems to communicate to me that I should expect the event properties associated with these events, so it's a bit surprising to realize that these are actually the names of the events.

it would be clearer to me with something like:

```js
olarkExpandedEvents.forEach( eventName => olarkEvents.on( eventName, … ) );
```

Comment (dmsnell) [inline client/lib/olark/index.js]: Maybe better still we could just do away with the name and make the action itself the focus of attention:

```js
syncStoreWithExpandedState() {
	const isOlarkExpanded = !! document.querySelector( '.olrk-state-expanded' );
	if ( isOlarkExpanded !== olarkStore.get().isOlarkExpanded ) {
		olarkActions.setExpanded( isOlarkExpanded );
	}
}

hookExpansionEventToStoreSync( eventName ) {
	olarkEvents.on( eventName, syncStoreWithExpandedState );
}

…

olarkExpandedEvents.forEach( hookExpansionEventToStoreSync );
```

File: client/lib/olark/index.js [hunk 5]
```diff
@@ -148,10 +156,32 @@ const olark = {
...
+			}
+		} ) );
+
 		updateDetailsEvents.forEach( event => olarkEvents.on( event, olarkActions.updateDetails ) );
 
 		debug( 'Olark code loaded, beginning configuration' );
 
+		olarkEvents.on( 'api.chat.onCommandFromOperator', ( event ) => {
+			if ( event.command.name === 'end' ) {
+				const { email } = user.get();
```
Comment (dmsnell) [inline client/lib/olark/index.js]: I don't know how `user` operates, but if it's not caching this we might be needlessly getting the data.

Can't say for sure, but I'm guessing we don't change emails during a single session very often

**Comment by dmsnell** [comment]
@omarjackman I left a few suggestions. Happy to go for a second pass when you need it.

**Comment by dllh** [comment]
I think the fixes for the last case I mentioned are a big improvement in terms of the interaction. I do have one more bit of feedback for it, but I'd not block the PR for this (would instead see about improving in a future PR). Here's what I see when opers are available and the chat ends:

ended-available

Looks great. If the oper then goes away, I see this:

ended-away

It's definitely better in my opinion that jumping back to the contact form with the chat box at lower right, but it's a little weird that it now shows the different offline form and doesn't have info pre-filled even though I'm logged in. I know that this is something Olark does, so we may be very limited in what we can do to fix it. This feels to me like an improved experience, so I'd be in favor of landing with this and then later exploring our options to improve it further.

**Comment by omarjackman** [comment]
@dmsnell all comments addressed. More review please.

**Comment by dmsnell** [comment]
looks good on the code size @omarjackman. if there were one thing to mention it's that I probably wouldn't be declaring those new functions as such in the linear flow of the code as it is. I'd probably either create variables that are functions at the top of the scope or create those functions outside of the scope. it's strange to see a bunch of sequential code and then a function definition and then more sequential code

**Comment by omarjackman** [comment]
> if there were one thing to mention it's that I probably wouldn't be declaring those new functions as such in the linear flow

@dmsnell I moved it out of the function.

**Comment by omarjackman** [comment]
@dmsnell @dllh can I git a :ship: ?

**Comment by dmsnell** [comment]
:ship:

File: client/lib/olark/index.js [hunk 6]
```diff
@@ -164,6 +186,36 @@ const olark = {
...
+	},
+
+	hookExpansionEventToStoreSync( eventName ) {
+		olarkEvents.on( eventName, this.syncStoreWithExpandedState );
+	},
+
+	showAvailabilityNotice() {
+		const noticeOptions = { showDismiss: true };
+		const { isOperatorAvailable, isUserEligible, isOlarkExpanded, isOlarkReady } = olarkStore.get();
+		const onEligibleContactForm = isUserEligible && window.location.pathname === '/help/contact';
```
Comment (mtias) [inline client/lib/olark/index.js]: This is not a blocker now, but I find it odd to have this tied to a url from here, seems like it the route should choose to display it not the module look at the route.

Comment (mtias) [inline client/lib/olark/index.js]: In other words, this seems like controller's business.
