### PR TITLE
Fix post scheduling calendar not indicating other scheduled posts 

### LINKED ISSUE #17888: Post Schedule Calendar: not indicating future scheduled posts
An investigation/question task:

**Is the following behaviour a regression or are the docs out of date?**

According to the [_Schedule a Post_ documentation](https://en.support.wordpress.com/schedule-a-post/):

> When looking at the calendar, the currently selected date will be indicated with a blue dot, and today’s date will have an orange circle around it.
> 
> Dates when other posts are already scheduled to be published are indicated with a light blue outline. You can move your cursor over these dates to see what post(s) are scheduled for that day.

#### Steps to reproduce
1. Create several new posts to be published in the near future
2. Create a new post
3. Open the schedule post calendar

#### What I expected
Posts scheduled to be published in step 1 above should be indicated by a light blue outline, as per the documentation, and mousing over these dates should reveal the scheduled post's information. 

screen-shot-2015-11-11-at-10-28-04-am

#### What happened instead
The scheduled post date and mouseover information are missing.
screen shot 2017-09-07 at 10 23 47

#### Side notes

[PostSchedule](https://github.com/Automattic/wp-calypso/tree/master/client/components/post-schedule) takes an `events` prop<Array>. Looks like this isn't being passed down (?)

#user-report #manual-testing

### PR DESCRIPTION
**Pull request by nylen**
Fixes #17888 - see that issue for testing instructions.

There is a component, `PostScheduler`, that renders `PostSchedule` along with a list of other posts from the site, so that they can be displayed with light blue outlines in the scheduling calendar.  In previous PRs related to the publish confirmation sidebars, this component was no longer used, and finally the reference to it was removed [here](https://github.com/Automattic/wp-calypso/pull/17655/files#diff-2b7e4118ffc960578bd452a0242ed25aL25).

This PR reinstates the `PostScheduler` component and modifies it to fit with the new code structure of the publish confirmation sidebar.

In the "After" screenshot below, note that the clock display changed to include AM/PM.  This can be removed if desired, but I believe it is also a fix from the current behavior.  In `master` we are not passing a `site` object to `post-schedule`, and this is used [here](https://github.com/Automattic/wp-calypso/blob/f17172466808e44e7b4354894c8e10ec5af1e64c/client/components/post-schedule/index.jsx#L204-L210) to render a `Clock` component with site-specific settings.

### Before

2017-09-06t21 18 51-0500

### After

2017-09-06t21 20 26-0500

### CODE REVIEW

**Comment by alisterscott** [comment]
Tested via https://calypso.live/?branch=fix/schedule-post-other-dates and this works well 👍 

There's one lint error on https://github.com/Automattic/wp-calypso/blob/cbdf64f9e1003c07404d2aa89c338cab466725e1/client/post-editor/editor-publish-date/index.jsx#L182 where `props` isn't necessary - otherwise LGTM

**Comment by nylen** [comment]
Strange, that error didn't show up in the [first failed build](https://circleci.com/gh/Automattic/wp-calypso/65688?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)...

```
/home/ubuntu/wp-calypso/client/post-editor/editor-publish-date/post-scheduler.jsx
  22:1  error  Unexpected space between function name and paren            func-call-spacing
  22:1  error  Unexpected space between function name and paren            no-spaced-func
  35:7  error  'ConnectedPostSchedule' is assigned a value but never used  no-unused-vars

✖ 3 problems (3 errors, 0 warnings)
```

Hopefully this one passes :crossed_fingers:

File: client/post-editor/editor-publish-date/post-scheduler.jsx [hunk 1]
```diff
@@ -9,35 +9,28 @@ import { get } from 'lodash';
...
 import QueryPosts from 'components/data/query-posts';
 import postUtils from 'lib/posts/utils';
 import siteUtils from 'lib/site/utils';
 import { getSitePostsForQueryIgnoringPage } from 'state/posts/selectors';
 
-const PostSchedule = ( { onDateChange, onMonthChange, posts, selectedDay, site } ) => {
-	const tz = siteUtils.timezone( site );
-	const gmtOffset = siteUtils.gmtOffset( site );
-
+const PostScheduleWithCurrentMonthPosts = connect(
```
Comment (mattsherman) [inline client/post-editor/editor-publish-date/post-scheduler.jsx]: This name doesn't really make sense, as the calendar shows posts for months other than the current month as well.

File: client/post-editor/editor-publish-date/post-scheduler.jsx [hunk 2]
```diff
@@ -9,35 +9,28 @@ import { get } from 'lodash';
...
+	( state, { site, query } ) => ( {
+		posts: getSitePostsForQueryIgnoringPage( state, get( site, 'ID' ), query ) || [],
+	} )
+)( function( { onDateChange, onMonthChange, posts, selectedDay, site } ) {
 	return (
-		<AsyncLoad
```
Comment (mattsherman) [inline client/post-editor/editor-publish-date/post-scheduler.jsx]: Why is AsyncLoad no longer needed? (Not sure why is was in there to begin with)

File: client/post-editor/editor-publish-date/post-scheduler.jsx (hunk 1 above)
Comment (nylen) [reply client/post-editor/editor-publish-date/post-scheduler.jsx]: "Current month" as in "the current month selected in the calendar".  In that sense, the name is accurate.

Do you have suggestions for an alternate name?  `s/Current/Selected/` maybe?

File: client/post-editor/editor-publish-date/post-scheduler.jsx (hunk 2 above)
Comment (nylen) [reply client/post-editor/editor-publish-date/post-scheduler.jsx]: Now that the publish confirmation sidebar is live, we're not using it in current `master`.

Investigating further, it was introduced here:  https://github.com/Automattic/wp-calypso/pull/9112

and the code size for that chunk is larger than I would have expected.

I don't have a clear preference for whether or not to bring back this behavior.  Thoughts?

File: client/post-editor/editor-publish-date/post-scheduler.jsx [hunk 3]
```diff
@@ -89,12 +82,11 @@ export default class PostScheduler extends PureComponent {
 		};
 
 		return (
-			<span className="editor-ground-control__schedule-post">
+			<span className="editor-publish-date__post-scheduler">
```
Comment (nylen) [inline client/post-editor/editor-publish-date/post-scheduler.jsx]: This class name is unused, I'll probably remove it and the wrapper element when I address the current round of feedback.

File: client/post-editor/editor-publish-date/post-scheduler.jsx (hunk 2 above)
Comment (mattsherman) [reply client/post-editor/editor-publish-date/post-scheduler.jsx]: Okay, it's probably fine to leave it out, since we we not using `AsyncLoad` anymore in this context.

File: client/post-editor/editor-publish-date/post-scheduler.jsx (hunk 1 above)
Comment (mattsherman) [reply client/post-editor/editor-publish-date/post-scheduler.jsx]: Hmm... maybe something like `PostScheduleWithOtherPostsIndicated`?

File: client/post-editor/editor-publish-date/post-scheduler.jsx (hunk 2 above)
Comment (nylen) [reply client/post-editor/editor-publish-date/post-scheduler.jsx]: :+1: I created https://github.com/Automattic/wp-calypso/issues/17924 for future follow-up there.

File: client/post-editor/editor-publish-date/post-scheduler.jsx (hunk 3 above)
Comment (nylen) [reply client/post-editor/editor-publish-date/post-scheduler.jsx]: I thought I would be able to remove the wrapper element in favor of returning an array, but:

```
Uncaught Error: PostScheduler.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.
```

So I've changed this to a plain `<div>` instead, which is more common for an element that is only needed as a wrapper.

**Comment by nylen** [comment]
Thanks for reviewing!

**Comment by KokkieH** [comment]
Thanks all for getting this fixed so quickly.
