### PR TITLE
Refactor Stats Bar Chart X Axis Component & Fix Weird Initial Render

### LINKED ISSUE #36089: Stats: x-axis renders wider than graph while loading
#### Steps to reproduce
1. Load `/stats/day` with a wide browser width
2. Observe: 
Screen Shot 2019-09-13 at 12 16 37 PM

### PR DESCRIPTION
**Pull request by cbauerman**
#### Changes proposed in this Pull Request

* Refactor stats bar chart x axis as functional component
* Use `useLayoutEffect` to hold render until axis is fixed

**BEFORE**
Screen Shot 2019-09-13 at 12 16 37 PM

**AFTER**
Screen Shot 2019-09-13 at 12 15 53 PM

#### Testing instructions
1. Navigate to `/stats/day` with a wide-ish browser width
2. Confirm the initial x axis does _not_ match the "BEFORE" screenshot above

Fixes #36089

### CODE REVIEW

File: client/components/chart/x-axis.jsx [hunk 1]
```diff
@@ -4,91 +4,69 @@
...
+	const axisSpacerRef = useRef( null );
+	const dataCount = data.length || 1;
+
+	const [ spacing, setSpacing ] = useState( labelWidth );
+
+	const [ divisor, setDivisor ] = useState( 1 );
+
+	useLayoutEffect( () => {
+		const resize = () => {
+			const width = axisRef.current.clientWidth - axisSpacerRef.current.clientWidth;
```
Comment (gwwar) [inline client/components/chart/x-axis.jsx]: Non-blocking, but should we throttle the resize event? Accessing clientWidth triggers a browser reflow which is a bit expensive.

**Comment by gwwar** [comment]
Verified that behavior looks good ✅Thanks @cbauerman, will help land for you!
