### PR TITLE
Disable browser push notifications in old chrome versions

### LINKED ISSUE #6243: Push Notifications: Chrome v49 doesn't display notifications
#### Steps to reproduce
1. Running Chrome v49 for either Linux/OSX/Windows (obtained [here](http://www.slimjet.com/chrome/google-chrome-old-version.php))
2. Enable desktop notifications at https://wordpress.com/me/notifications
3. Spawn a new notification

#### What I expected
To receive a desktop popup

#### What happened instead
Nothing but the badge on the notification icon

#### Browser / OS version
Linux / OSX / Windows Chrome v49

#### Context / Source
#manual-testing

### PR DESCRIPTION
**Pull request by mjuhasz**
Fixes #6243

This PR seeks to fix the bug whereby browser push notifications do not arrive after enabling them. This bug affects users using Chrome 40-49, and this PR disables the feature for these users.

Chrome versions 40-49 support web push notifications, but not encryption. Our feature detection shows the browser as supporting web push notifications, and allows users to enable them. Due to lack of encryption support in these browsers, the subscription saved does not include encryption keys. When the notification is sent, an error such the following will get logged: 

```
Error sending notification: Malformed subscription: keys and endpoint required.
```

Even though Chrome 49 and below our not supported anymore, we will still disable notification support in these browsers because we see from our logs that some users are sticking with obsolete browser versions.

### Testing instructions

1. Turn on debugging for calypso: `localStorage.setItem( 'debug', 'calypso:*' );`
2. Navigate to the live branch in a Chrome browser v50 or above, and verify that the opt-in notice is visible (you may need a new user if you have dismissed the notice before), and the notification settings page (`/me/notifications`) has the browser notification panel.
3. Navigate to the live branch in a Chrome browser v49 (or below), and verify that neither the notice nor the browser notification settings are not visible. You will also see these lines in the console:

screen shot 2016-07-07 at 4 22 11 pm

I downloaded a VM from http://www.osboxes.org/ubuntu/ and an old Chrome version from http://www.slimjet.com/chrome/google-chrome-old-version.php for testing, but your milage may very.

4. Open the live branch in Firefox, and confirm that the notice and notification settings are visible there (no regression).

Test live: https://calypso.live/?branch=fix/push-notifications-in-old-chrome-6

### CODE REVIEW

File: client/components/push-notification/prompt.jsx [hunk 1]
```diff
@@ -79,13 +80,25 @@ const PushNotificationPrompt = React.createClass( {
 		return <Notice className="push-notification__notice" text={ noticeText } icon="bell" onDismissClick={ this.props.dismissNotice } />;
 	},
 
+	isUnsupportedChromeVersion: function() {
```
Comment (mattsherman) [inline client/components/push-notification/prompt.jsx]: This should be put in https://github.com/Automattic/wp-calypso/blob/master/client/state/push-notifications/utils.js#L8, avoiding the need to duplicate the logic and stopping things earlier on.

File: client/components/push-notification/prompt.jsx [hunk 2]
```diff
@@ -79,13 +80,25 @@ const PushNotificationPrompt = React.createClass( {
...
+		if ( global.window && global.window.chrome && global.window.navigator.appVersion ) {
+			const chromeVersion = global.window.navigator.appVersion.match( /Chrome\/(\d+)/ )[ 1 ];
+			if ( chromeVersion < 50 ) {
+				analytics.mc.bumpStat( 'calypso_push_notification_chrome', chromeVersion );
```
Comment (mattsherman) [inline client/components/push-notification/prompt.jsx]: Good idea to track this with a stat!

The stat name seems a bit vague (people looking at the stat wouldn't know that it only tracks unsupported versions of Chrome). I'd suggest renaming it to something like `calypso_push_notification_unsupported_chrome` (not sure if that is too long -- you'll want to double-check that).

File: client/components/push-notification/prompt.jsx (hunk 1 above)
Comment (mjuhasz) [inline client/components/push-notification/prompt.jsx]: Absolutely. I'm still testing it, and the easiest was to push something so that I can test it from VMs without proxying, hence the duplication. Thanks for the advice on where to extract the logic!

File: client/components/push-notification/prompt.jsx (hunk 2 above)
Comment (mjuhasz) [inline client/components/push-notification/prompt.jsx]: 32-character limit applies, this label is exactly 32 characters. `calypso_` comes from the naming convention. We can try something like `calypso_push_notif_unsup_chrome' (that's 31 characters).

File: client/state/push-notifications/utils.js [hunk 3]
```diff
@@ -5,6 +5,19 @@ import {
 	isServiceWorkerSupported,
 } from 'lib/service-worker';
 
+export function isUnsupportedChromeVersion() {
+	if ( window && window.chrome && window.navigator.appVersion ) {
+		if ( getChromeVersion() < 50 ) {
+			return true;
+		}
```
Comment (mattsherman) [inline client/state/push-notifications/utils.js]: Slightly cleaner to just write `return getChromeVersion() < 50;`

**Comment by mattsherman** [comment]
Tested with Chrome 48 on Windows and verified that prompt did not appear and that the two lines mentioned in the testing instructions appeared in the console.

Tested with Chrome 51 on Mac and verified that prompt did appear.

Tested with Firefox 47 on Mac and verified that prompt did appear.

Code changes look good -- just one minor inline code style suggestion.

File: client/state/push-notifications/utils.js (hunk 3 above)
Comment (mjuhasz) [inline client/state/push-notifications/utils.js]: Of course, thanks!

**Comment by mjuhasz** [comment]
Thank you for the testing!

**Comment by mattsherman** [comment]
LGTM! 👍
