### PR TITLE
Staging Sites: Fix staging site check that breaks user account in some cases

### LINKED ISSUE #76099: User must make many attempts to actually log out, intermittently
### Quick summary

TL;DR: User frequently has to try several (or even many) times to log out and sees either blank pages or errors when trying, until after repetition, it finally works.

This is a weird, intermittent bug that a user is encountering. I cannot personally reproduce, nor have any HEs been able to. There is a javascript error I wanted to note in case it was relevant. I don't think [this PR](https://github.com/Automattic/wp-calypso/pull/73855) is relevant, but it's the only fairly recent thing I could find that referenced the javascript property that's sending an error to the user's browser.

See 6080495-zd-woothemes.

### Steps to reproduce

I added the console steps that begin and end this repro list, to see if the user could spot anything useful in the console that might point to a server-side issue, as this has occurred on multiple browsers and devices with cookies/etc. cleared.

1. Load the browser console.
2. Click the user avatar at the top right of the admin bar from any screen. This should go to /me.
3. Observe that a blank screen loads rather than the profile.
5. Click back to get to the prior page.
6. See step 3. Keep trying this until:
7. The message "We're sorry but an unexpected error has occurred" appears in the main content area to the right of the usual admin sidebar.
8. Look for any errors in the browser console (my debugging step for the user).

### What you expected to happen

The user is logged out and sees an appropriate logout screen.

### What actually happened

The user reports:

> When I try to log out, the page My Profile appears, over and over again. Sometimes have to try three or four times to log out.

The user also reported that sometimes it takes many more tries (like a couple of dozen). And sometimes the logout works as expected, so it's intermittent.

Further, when they sent me info from the browser console, this one came up:

Screen Shot 2023-04-21 at 3 56 46 PM

It may not be related to this at all (I sort of doubt it is, in fact), but a javascript error seemed worth reporting in any case.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

The user has cleared cache and cookies on multiple browsers and computers. They have also seen this behavior on their phone. I don't think we can consider this a browser-specific issue, hence my suggesting we look for console errors that _could_ point to some other (maybe server-side?) problem. I don't actually think the error sent back actually points to such an issue.

The user says he can live with the issue but wanted to bring it to our attention. This seems like it must be some kind of edge case, as I could find no other similar reports. So there may not be much to do here, but perhaps the js error is worth a look.

### PR DESCRIPTION
**Pull request by wojtekn**
Fixes https://github.com/Automattic/wp-calypso/issues/76099

## Proposed Changes

In this PR, I propose to use optional chaining to avoid breaking UI if not all site data is loaded.

The issue popped out on the domain upsell block on the customer profile page via staging site check from `client/sites-dashboard/utils.ts`. To reproduce without setting upsell on the data level:

1. Run Calypso on local environment
2. Open customer profile
3. Edit the `client/my-sites/customer-home/cards/features/domain-upsell/index.jsx` file and remove three other checks from the condition that includes a check for `isStagingSite`
4. Refresh customer profile

## Testing Instructions

1. Run Calypso on the local environment or use Calypso Live
2. Open customer profile
3. Confirm page loads without an error

Additionally, check if:

- staging site has a badge on the Sites page in both table and grid modes
- staging site has a badge in the left sidebar menu
- staging site doesn’t have a link to Staging sites on Sites page context menu

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by danielbachhuber** [comment]
How did we end up with a Site object without the `is_wpcom_staging_site` attribute?

**Comment by wojtekn** [comment]
@danielbachhuber we get it from `getSelectedSite`, which can return null.

**Review by kozer — APPROVED** [review]

**Comment by danielbachhuber** [comment]
> we get it from `getSelectedSite`, which can return null.

@wojtekn Sounds good.

**Comment by katinthehatsite** [comment]
Works as expected for me, no errors visible!

File: client/sites-dashboard/utils.ts [hunk 1]
```diff
@@ -45,7 +45,7 @@ export const isP2Site = ( site: SiteExcerptNetworkData ) => {
 };
 
 export const isStagingSite = ( site: SiteExcerptNetworkData ) => {
```
Comment (sejas) [inline client/sites-dashboard/utils.ts]: @wojtekn , should we update the type of the `site` parameter?

```suggestion
export const isStagingSite = ( site: SiteExcerptNetworkData | undefined) => {
```

File: client/sites-dashboard/components/sites-ellipsis-menu.tsx [hunk 2]
```diff
@@ -263,7 +263,7 @@ const SiteDropdownMenu = styled( DropdownMenu )( {
 function useSubmenuItems( site: SiteExcerptData ) {
 	const { __ } = useI18n();
 	const siteSlug = site.slug;
-	const isStagingSite = site.is_wpcom_staging_site;
+	const isStagingSite = site?.is_wpcom_staging_site;
```
Comment (sejas) [inline client/sites-dashboard/components/sites-ellipsis-menu.tsx]: Ideally, inside all the `sites-dashboard` folder we could use the `isStagingSite` function directly importing it from `client/sites-dashboard/utils.ts`

**Review by sejas — APPROVED** [review]
@wojtekn , the change looks good, and it's better to be safe.
 I've seen the site can be undefined in some cases during the deleting staging sites flow 👍 .

I added a couple of suggestions. No strong opinion though.

File: client/sites-dashboard/components/sites-ellipsis-menu.tsx (hunk 2 above)
Comment (wojtekn) [reply client/sites-dashboard/components/sites-ellipsis-menu.tsx]: Thanks, I've modified the code to use this existing function.

**Review by danielbachhuber — APPROVED** [review]
I confirmed that the `Staging` label still appears as expected in a few places, and was able to successfully log out.

Landing this so we can get the fix in front of users.
