### PR TITLE
Login: Fix redirect not working after succesfull 2FA push notification

### LINKED ISSUE #14210: Login: nothing happens after approving push notification
Steps to reproduce:

- choose an account that has 2FA via authenticator app enabled
- log in to that account in the WordPress mobile app
- visit `/log-in` and enter your username and password
- you'll be redirected to `/log-in/push` and should get a push notification in your phone
- click Approve in the notification in your phone
- note that nothing happens in your browser (expected behavior: you see a green notice and are logged in).

Seems this is a regression, since it was working yesterday when I was testing M2.

### PR DESCRIPTION
**Pull request by stephanethomas**
This pull request fixes #14210 in order to redirect the user to the `Reader` page after a successful login with 2FA and push notification. It also adds a page title to the `Login` pages.
  
#### Testing instructions
 
1. Run `git checkout fix/login-with-2fa-push` and start your server, or open a [live branch](https://calypso.live/?branch=fix/login-with-2fa-push)
2. Open the [`Login` page](http://calypso.localhost:3000/log-in) in an incognito window
3. Check that the title of the page is now `Log In`
4. Enter credentials of a 2FA account that has push notifications enabled
5. Check that you are redirected to the [`Reader` page](http://calypso.localhost:3000/) once you have allowed the login request

#### Reviews
 
- [x] Code
- [x] Product

### CODE REVIEW

File: client/blocks/login/two-factor-authentication/waiting-notification-approval.jsx [hunk 1]
```diff
@@ -40,8 +40,6 @@ class WaitingTwoFactorNotificationApproval extends Component {
 
 	componentWillReceiveProps( nextProps ) {
 		if ( ! this.props.pushSuccess && nextProps.pushSuccess ) {
-			const { translate } = this.props;
-			this.props.successNotice( translate( 'Logging In…' ) );
```
Comment (stephanethomas) [inline client/blocks/login/two-factor-authentication/waiting-notification-approval.jsx]: That's probably a left-over of https://github.com/Automattic/wp-calypso/commit/06390be4396573e11125aec18026b3377eedbd11.

Comment (fabianapsimoes) [inline client/blocks/login/two-factor-authentication/waiting-notification-approval.jsx]: Ha: https://github.com/Automattic/wp-calypso/issues/14155

**Comment by fabianapsimoes** [comment]
👏 

Product 👍

File: client/blocks/login/two-factor-authentication/waiting-notification-approval.jsx (hunk 1 above)
Comment (scruffian) [inline client/blocks/login/two-factor-authentication/waiting-notification-approval.jsx]: We actually aren't sure if we want this or not (https://github.com/Automattic/wp-calypso/issues/14155) but it's fine to remove it for now.

**Comment by scruffian** [comment]
Code 👍
