### PR TITLE
Calypsoify: Handle Query block link and handle links in site editor too

### LINKED ISSUE #51206: Site Editor: Query Block link to open Post Editor not working on Horizon
### Steps to reproduce the behavior

1. Open Site Editor in WP.com.
2. Add a Query Block.
3. Open block inspector sidebar.
4. Click "Create a new post." (Screenshot below.)
5. See bug. (Screenshot below.)

**Click "Create a new post."**

image

**See bug.**

image

### PR DESCRIPTION
**Pull request by david-szabo97**
#### Changes proposed in this Pull Request

* Redirect Query block's "Create a new post" link to the correct URL in WPcom context (both post and site editor)
* Fix "Manage reusable blocks" link in the Site Editor, in WPcom context.

#### Testing instructions

**Preparation**
1. Follow instructions in PCYsg-l4k-p2 to apply the changes proposed in this PR on your sandbox
2. Apply D60514-code diff on your sandbox 

**Manage reusable blocks**

**1**
1. Open WPcom post editor
2. Add a paragraph block
3. Turn it into a reusable block
4. Open global block inserter
5. Navigate to "Reusable" tab
6. Make sure the "Manage reusable blocks" link on the bottom is pointing to: wordpress.com/types/.......

**2**
1. Open WPcom post editor
2. Click 3 dots menu
3. Make sure the "Manage reusable blocks" link is pointing to: wordpress.com/types/.......

**3**
1. Open WPcom site editor
2. Click 3 dots menu
3. Make sure the "Manage reusable blocks" link is pointing to: wordpress.com/types/.......

**Create new post**
**1**
1. Open WPcom post editor
2 Add a "Query" block, choose any variation
3 Open "Block Settings" and click on the "Create a new post" link
4 "Unsaved changes" alert should popup
5 Click "Yes" to proceed on and make sure you are redirected to the new post page: wordpress.com/post/....

**2**
1. Open WPcom site editor
2. Add a "Query" block, choose any variation
3. Open "Block Settings" and click on the "Create a new post" link
4. "Unsaved changes" alert should popup
5. Click "Yes" to proceed on and make sure you are redirected to the new post page: wordpress.com/post/....

Fixes #51206

### CODE REVIEW

**Review by creativecoder — COMMENTED** [review]
Question: can you think of any way of changing the link so that it respects "Open link in a new tab" (either through Cmd/Ctrl clicking, or through a right click action)?

Comment: Jetpack will also need an update to add `calypsoifyGutenberg.createNewPostUrl` so this works correctly for Jetpack/Atomic sites (https://github.com/Automattic/jetpack/blob/446ab7025351501a4e0722a1b1eb1a58a4205a32/projects/plugins/jetpack/modules/calypsoify/class-jetpack-calypsoify.php#L85)

**Comment by david-szabo97** [comment]
@creativecoder Nice catch! Pushed a commit as a fix.

**Comment by jeyip** [comment]
## Testings
### Requirements
- [x] When clicked, the "Create a new post" link warns the user about unsaved changes
- [x] When clicked, the "Create a new post" link redirects the user to an empty post editor where they can create a new post
- [x] When Cmd + Clicked, the "Create a new post" link opens an empty post editor in a new tab

### Browsers
- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge

File: apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js [hunk 1]
```diff
@@ -676,15 +676,27 @@ function openLinksInParentFrame( calypsoPort ) {
...
+				const manageReusableBlocksLinkSelectors = [
+					'.block-editor-inserter__manage-reusable-blocks', // Link in the Blocks Inserter
+					'a.components-menu-item__button[href*="post_type=wp_block"]', // Link in the More Menu
+				].join( ',' );
+				$( manageReusableBlocksLinkSelectors, $editor )
+					.attr( 'href', calypsoifyGutenberg.manageReusableBlocksUrl )
+					.attr( 'target', '_top' );
+			}
+		};
+		setInterval( replaceLink, 50 );
```
Comment (jeyip) [inline apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]: I'm curious about this `setInterval`. It looks like the `manageReusableBlocksLink` worked without an interval before these changes. Would you mind elaborating on why we prefer one now?

Also, were there any events we might be able to listen to instead?

**Review by jeyip — COMMENTED** [review]
I'm not the most familiar with this area of the codebase, but everything looks reasonable. +1 from me when we resolve code review.

**Note:**
 It looks like the failing E2E tests are unrelated.

File: apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js (hunk 1 above)
Comment (creativecoder) [reply apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]: The trouble with the previous approach is that intercepting the click event won't handle "open in a new tab" flows, where the browser takes the href and opens the url in a new tab. Without changing the actual href, there's no effect on the destination url.

One solution might be using a mutation observer. That feels heavy, but it's likely worth it. I think opening a new tab is going to be common with this particular link, because otherwise you need to save your changes before you exit the editor to create a new post. cc @david-szabo97

Comment (jeyip) [reply apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]: Ah I see. One note about the mutation observer -- if we end up going down that route, let's be sure to scope to a specific enough target when calling `mutationObserver.observe()`. 

A commit to the coblocks library actually borked the block editor because the changes added a condition whereby, instead of just a subset of the DOM document, the entire DOM document was tracked for changes. ( see pbAok1-1e6-p2 under subheading "Root Cause" )

Comment (david-szabo97) [reply apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]: That was tough to pull off, but it's ready for review 😄

**Comment by david-szabo97** [comment]
@creativecoder  @jeyip It's ready for another round of testing 🙇 Thanks! I hope using MutationObserver is worth it 😄

File: apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js [hunk 2]
```diff
@@ -676,15 +676,121 @@ function openLinksInParentFrame( calypsoPort ) {
...
+				hyperlink.target = '_top';
+			}
+		}
+	} );
+
+	const sidebarsObserver = new window.MutationObserver( ( mutations ) => {
+		for ( const record of mutations ) {
+			for ( const node of record.addedNodes ) {
+				if (
+					createNewPostUrl &&
```
Comment (jeyip) [inline apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]: `nb:` It might be worthwhile to turn the if conditional clause into a helper function ( the naming can be adjusted ). It can be used here and on line 740. I feel like it adds clarity.

```javascript
function shouldReplaceSidebarLinksFor( node ) {
    return createNewPostUrl && 
        ( node.classList.contains( 'interface-interface-skeleton__sidebar' ) || // Site editor
	    node.classList.contains( 'edit-post-sidebar' ) ) // Post editor
}

if ( shouldReplaceSidebarLinksFor ( node ) ) {
    const componentsPanel = node.querySelector( '.interface-interface-skeleton__sidebar .components-panel, .edit-post-sidebar .components-panel' );

    createNewPostLinkObserver.observe( componentsPanel, {
        childList: true,
        subtree: true,
    } );
}
```

The same can probably be done for the manage reusable blocks else if clause.

**Review by jeyip — APPROVED** [review]
Thanks for making the changes @david-szabo97! The modifications we made to use the MutationObserver were a bit overwhelming to look through at first. I'm leaving a few non-blocking comments -- let me know what you think. Hopefully they add some clarity to these updates.

Would love if @creativecoder gets a chance to look through the code changes before we ship, but otherwise, everything lgtm!

File: apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js [hunk 3]
```diff
@@ -676,15 +676,116 @@ function openLinksInParentFrame( calypsoPort ) {
...
+			node.classList.contains( 'edit-post-sidebar' ) ); // Post editor
+
+	const shouldReplaceManageReusableBlockLinksFor = ( node ) =>
+		manageReusableBlocksUrl &&
+		node.classList.contains( 'interface-interface-skeleton__secondary-sidebar' );
+
+	const sidebarsObserver = new window.MutationObserver( ( mutations ) => {
+		for ( const record of mutations ) {
+			for ( const node of record.addedNodes ) {
+				if ( shouldReplaceCreateNewPostLinksFor( node ) ) {
```
Comment (creativecoder) [inline apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]: What do you think about disconnecting the `createNewPostLinkObserver` when `shouldReplaceCreateNewPostLinksFor` is false? (and similar for the other observers)

It seems like it would be a good idea to clean these up when the relevant elements are removed from the DOM.

Comment (creativecoder) [reply apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]: Oh, now I see you're already doing that down on line 740.

File: apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js [hunk 4]
```diff
@@ -676,15 +676,116 @@ function openLinksInParentFrame( calypsoPort ) {
...
+	const shouldReplaceCreateNewPostLinksFor = ( node ) =>
+		createNewPostUrl &&
+		( node.classList.contains( 'interface-interface-skeleton__sidebar' ) || // Site editor
+			node.classList.contains( 'edit-post-sidebar' ) ); // Post editor
+
+	const shouldReplaceManageReusableBlockLinksFor = ( node ) =>
+		manageReusableBlocksUrl &&
+		node.classList.contains( 'interface-interface-skeleton__secondary-sidebar' );
+
+	const sidebarsObserver = new window.MutationObserver( ( mutations ) => {
```
Comment (creativecoder) [inline apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js:724]:
```suggestion
	// This observer functions as a "parent" observer, which connects and disconnects "child" observers as the relevant sidebar settings appear and disappear in the DOM.
	const sidebarsObserver = new window.MutationObserver( ( mutations ) => {
```

File: apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js (hunk 3 above)
Comment (creativecoder) [inline apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]:
```suggestion
				// Block settings sidebar for Query block.
				if ( shouldReplaceCreateNewPostLinksFor( node ) ) {
```

File: apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js [hunk 5]
```diff
@@ -676,15 +676,116 @@ function openLinksInParentFrame( calypsoPort ) {
...
+			for ( const node of record.addedNodes ) {
+				if ( shouldReplaceCreateNewPostLinksFor( node ) ) {
+					const componentsPanel = node.querySelector(
+						'.interface-interface-skeleton__sidebar .components-panel, .edit-post-sidebar .components-panel'
+					);
+					createNewPostLinkObserver.observe( componentsPanel, {
+						childList: true,
+						subtree: true,
+					} );
+				} else if ( shouldReplaceManageReusableBlockLinksFor( node ) ) {
```
Comment (creativecoder) [inline apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]:
```suggestion
				// Block inserter sidebar, Reusable tab
				} else if ( shouldReplaceManageReusableBlockLinksFor( node ) ) {
```

File: apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js [hunk 6]
```diff
@@ -676,15 +676,116 @@ function openLinksInParentFrame( calypsoPort ) {
...
+	// Site editor
+	sidebarsObserver.observe( document.querySelector( '.interface-interface-skeleton__body' ), {
+		childList: true,
+	} );
+	// Post editor
+	sidebarsObserver.observe( document.querySelector( '.interface-interface-skeleton__sidebar' ), {
+		childList: true,
+	} );
+
+	// Manage reusable blocks link in the 3 dots more menu
```
Comment (creativecoder) [inline apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]:
```suggestion
	// Manage reusable blocks link in the 3 dots more menu, post and site editors.
```

**Review by creativecoder — DISMISSED** [review]
✅ After tweaking for browser compatibility (see below), this is working well for me.

I commend you for laying this out logically and avoiding performance pitfalls!

---

I did a little bit of profiling, and it seems this is very performant. By conditionally adding mutation observers for each section of the DOM, and disconnecting them when no longer needed, this seems very fast.

For reference, here's the execution time of just the sidebarsObserver callback (run on page load)... it's very short

Screen Shot 2021-05-05 at 17 09 11

---

I ran into 2 browser compatibility issues when testing this, that I pushed fixes for in https://github.com/Automattic/wp-calypso/pull/52122/commits/3bdd9955403fbefe1939ba67a8f64ec965fcb669

- In Firefox, accessing an attribute directly on the node didn't work (e.g. `node.ariaSelected`). Instead, it requires using the `NamedNodeMap` API (`node.attributes.getNamedItem( 'aria-expanded' )?.nodeValue`)
- In Safari, for some reason the "more" menu has not yet rendered when the mutationObserver callback executes, so I wrapped the href change in a `setTimeout` call to wait for the render, which seems to fix the issue.

---

Finally, I'll leave some suggested additional code comments for documenting this -- this code took me quite some time to work through and understand and I want a head start next time 😄

**Review by creativecoder — CHANGES_REQUESTED** [review]
I was testing this more and discovered that if you open and close the sidebar, the observer doesn't work for changing the query block new post link.

Screen Shot 2021-05-06 at 20 04 18

Because the observer is added after the sidebar is open, the callback that changes the link doesn't run, because there's no DOM mutation in the sidebar after that point.

**Comment by creativecoder** [comment]
Note, here's a companion PR to cover Jetpack sites: https://github.com/Automattic/jetpack/pull/19769

**Comment by david-szabo97** [comment]
Thanks a lot @creativecoder for working on this and reviewing! Fixed the bug and added the comments.

File: apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js [hunk 7]
```diff
@@ -676,15 +676,136 @@ function openLinksInParentFrame( calypsoPort ) {
...
+			for ( const node of record.removedNodes ) {
+				if ( shouldReplaceCreateNewPostLinksFor( node ) ) {
+					createNewPostLinkObserver.disconnect();
+				} else if ( shouldReplaceManageReusableBlockLinksFor( node ) ) {
+					inserterManageReusableBlocksObserver.disconnect();
+				}
+			}
+		}
+	} );
+	// Site editor
```
Comment (creativecoder) [inline apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]: I think this is actually just for the block inserter (post editor only)?

File: apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js [hunk 8]
```diff
@@ -676,15 +676,136 @@ function openLinksInParentFrame( calypsoPort ) {
...
+	sidebarsObserver.observe( document.querySelector( '.interface-interface-skeleton__body' ), {
+		childList: true,
+	} );
+	// Post editor
```
Comment (creativecoder) [inline apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]: I think this is for the block settings sidebar in both the post and site editors?

**Review by creativecoder — APPROVED** [review]
This is now working well for me 🎉

I think a couple of the code comments might be incorrect, but otherwise this looks good to go!

File: apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js (hunk 8 above)
Comment (david-szabo97) [reply apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]: Corrected the comments.
- Block settings sidebar, post editor

File: apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js (hunk 7 above)
Comment (david-szabo97) [reply apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]: Corrected the comments.
- Block inserter sidebar, post editor
- Block settings sidebar, site editor

**Comment by david-szabo97** [comment]
@creativecoder Made some updates to the comments. 🙇

**Comment by creativecoder** [comment]
Thanks for the additional comments, very helpful!

I've just retested this (Firefox and Safari) and this looks good to go. 🚢

---

Meta note about this feature (not specific to the PR) -- dynamically replacing DOM nodes to update the new post link feels very fragile and likely to break. I plan to spend some time looking to see if there's a way the link could be filtered or similar with some upstream changes to Gutenberg. This seems like it could be an issue for any editor instance that lives outside wp-admin.

**Comment by creativecoder** [comment]
Also, e2e test failures look unrelated. I don't think wpcom-block-editor is deployed in any way for running the tests, so I wouldn't worry about fiddling with them before merging.

**Review by jeyip — APPROVED** [review]
Tested this again as well -- looks good! 🚢
