### PR TITLE
FSE: modify button links in SPT template selection

### LINKED ISSUE #39315: Links in Homepage Templates linking to theme demo sites
#### Steps to reproduce
1. Create a page on a site using a homepage template using the Balasana template
2. Visit the front end view of that page
3. Search for "View Teachers" and inspect the button link
4. Note that the button links to the theme demo site for Balasana

image

We should automatically update the links to be relative to the users site, remove the URLs entirely, just have them link to the homepage of the site, or link to the newly created page (to prevent a user getting lost before they update the button).

### PR DESCRIPTION
**Pull request by frontdevde**
#### Changes proposed in this Pull Request

This PR aims to fix the issue reported in https://github.com/Automattic/wp-calypso/issues/39315. Currently the buttons in the Home Page Templates link to the external template sites. To prevent this, this PR modifies the url attribute for all button links on template selection.

Fixes https://github.com/Automattic/wp-calypso/issues/39315

#### Testing instructions

The key thing to check is:

* When selecting a Home Page template (e.g. Balasana) and adding it to the editor, the buttons should not link to external sites but instead have the link value '#'.

This requires the FSE Plugin to be active on your WP install. You can find guidance for this at `PaYJgx-sW-p2`. You can test on local WP instance or WPCom (assuming you have sandbox syncing setup).

### Before

* Activate FSE Plugin.
* Create new Page.
* See SPT selector.
* Click "Balasana" template to show the preview
* Click "Use Balasana template" to load it in the Editor
* Check the Button links, they should show an external URL e.g. 
"balasanademo.wordpress.com/classes/"

Screenshot 2020-02-26 at 16 22 52

### After

* Check out this PR branch.
* Build FSE and sync to your WP install.
* Ensure FSE Plugin is active.
* Create new Page.
* See SPT selector.
* Click "Balasana" template to show the preview
* Click "Use Balasana template" to load it in the Editor
* Check the Button links, they should not show an external URL but have the link value '#' instead.

Screenshot 2020-02-26 at 16 23 17

### CODE REVIEW

**Comment by getdave** [comment]
Once the [`modifyBlocks` util is merged in my PR](https://github.com/Automattic/wp-calypso/pull/39697/files#diff-cca4f5004d5d8f46ca53e09d134b74e0) then you should be able to use here as well.

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js [hunk 1]
```diff
@@ -71,6 +71,19 @@ class PageTemplateModal extends Component {
 		} );
 	} );
 
+	getBlocksForSelection = selectedTemplate => {
+		const blocks = this.getBlocksByTemplateSlug( selectedTemplate );
+		// Modify the existing blocks returning new block object references.
+		return modifyBlocks( blocks, function modifyBlocksForPreview( block ) {
```
Comment (marekhrabe) [inline apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]:
```suggestion
		return modifyBlocks( blocks, function modifyBlocksForSelection( block ) {
```

**Review by marekhrabe — COMMENTED** [review]
This is working perfectly on the first try. All buttons are set to `href="#"`. 

Maybe we should do a review if there are more block types in templates that could have links or other content tied to demo sites but solving just buttons now, this does it well.

Please note I've suggested a name change for function `modifyBlocks` in the parent PR. Make sure to follow it and update if that ends up being changed. If not, let's ship it!

**Comment by getdave** [comment]
@frontdevde The parent PR is now merged.

**Comment by frontdevde** [comment]
@getdave @marekhrabe Should be good to go!

**Review by marekhrabe — APPROVED** [review]
Yay, feedback addressed and tests green! :shipit:
