### PR TITLE
Plugins: point multisite sidebar links to the all sites view

### LINKED ISSUE #70453: Plugins: fix multisite link and show all sites
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/stats/day
2. Click on the Plugins link in the sidebar.

#### What I expected

To view all installed plugins across my different sites.

Screenshot 2022-11-26 at 3 09 44 AM

#### What happened instead

I was taken to the Plugins Marketplace view.

Screenshot 2022-11-26 at 3 10 11 AM

#### Browser / OS version

Any.

### PR DESCRIPTION
**Pull request by vindl**
#### Proposed Changes

Fixes https://github.com/Automattic/wp-calypso/issues/70453

Plugins marketplace work overrode the `/plugins` route, which was initially used for the all-sites view. We can repoint the existing sidebar links to the /plugins/manage route, which still serves the correct all-sites plugins management view.

#### Testing Instructions

1. Navigate to the Plugins page for your test simple site (`http://calypso.localhost:3000/plugins/{site_url}`).
2. Click on `Switch Site`.
3. Click on `View plugins for all sites`.
4. Verify that you are taken to the `/plugins/manage` page, which shows installed plugins for all sites.
5. Click on `/Stats` in the multisite sidebar.
6. Click on the `Plugins` in the multisite sidebar.
7. Verify that it also links to the `/plugins/manage` page.
8. Confirm that the `Posts` multisite link behavior didn't change.

|Before|After|
|-|-|
|Screenshot 2022-11-26 at 3 10 11 AM|Screenshot 2022-11-26 at 3 09 44 AM|

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: client/components/site-selector/index.jsx [hunk 1]
```diff
@@ -311,13 +311,27 @@ export class SiteSelector extends Component {
 		return sites;
 	}
 
+	mapAllSitesPath = ( path ) => {
+		if ( path.includes( '/posts/my' ) ) {
+			return path.replace( '/posts/my', '/posts' );
+		}
+
+		// We used to show multisite plugins management on /plugins route, but that has changed
+		// and now we show the plugins marketplace on it, which is a single site view.
```
Comment (p-jackson) [inline client/components/site-selector/index.jsx:320]: > which is a single site view

Nothing to do with this PR, but that seems confusing doesn't it? If it's a single site view wouldn't it be `/plugins/:siteSlug`?

**Review by p-jackson — COMMENTED** [review]
The change looks good, but I think this behaviour is still confusing


https://user-images.githubusercontent.com/1500769/204191297-1fd924a7-c721-4232-95d5-43d7490613b2.mov

When you're viewing the plugins marketplace the `Plugins` menu item is highlighted, even though you're not really "in" that section of the app. And when you click the link it takes you somewhere else, even though it was highlighted.

It looks like you can customise how the sidebar item highlighting works in [`itemLinkMatches()`](https://github.com/Automattic/wp-calypso/blob/d293e0afb9a4625bac829a3d6dad9cbf5bebe3f4/client/my-sites/sidebar/utils.js#L16); we already customise things for a few specific cases. But to be honest I'm not quite sure what the correct behaviour should even be. If you were on the plugins marketplace maybe it'd feel strange for the "Plugins" sidebar item not to be highlighted 🤷

**Comment by wojtekn** [comment]
> When you're viewing the plugins marketplace the Plugins menu item is highlighted, even though you're not really "in" that section of the app. And when you click the link it takes you somewhere else, even though it was highlighted.

@p-jackson should we ever display the "Flex your site’s features with plugins" landing page if there is no site slug in the URL? Would it make sense to just redirect to the new multi-site view if users access `/plugins` without a slug?

File: client/components/site-selector/index.jsx (hunk 1 above)
Comment (vindl) [reply client/components/site-selector/index.jsx:320]: Yes, I find the fact that the new functionality overrode the previous behavior a bit confusing too, both for `/plugins` and `/plugins/:siteSlug`. (we had Calypso view for this too, and now it seems to be forcing wp-admin)

Looking at that page a bit more, maybe "site-less" would be a better description since it shows pretty much the same view regardless of the site, so `/plugins/:siteSlug` wouldn't be a good fit either. 😄

**Comment by vindl** [comment]
> When you're viewing the plugins marketplace the Plugins menu item is highlighted, even though you're not really "in" that section of the app. And when you click the link it takes you somewhere else, even though it was highlighted.
It looks like you can customise how the sidebar item highlighting works in [itemLinkMatches()](https://github.com/Automattic/wp-calypso/blob/d293e0afb9a4625bac829a3d6dad9cbf5bebe3f4/client/my-sites/sidebar/utils.js#L16); we already customise things for a few specific cases. But to be honest I'm not quite sure what the correct behaviour should even be. If you were on the plugins marketplace maybe it'd feel strange for the "Plugins" sidebar item not to be highlighted 🤷

Good catch @p-jackson! I'm not sure what the correct behavior would look like either. Ideally, the marketplace should have created a separate route and menu items for this, and not taken over the existing ones for plugin management. But it's a bit too late for that now. I'll need to give it some more thought and see if we can detangle this. The priority is to surface the new plugin management improvements Jetpack teams have been working on.

**Comment by vindl** [comment]
> Would it make sense to just redirect to the new multi-site view if users access /plugins without a slug?

This could be problematic since marketplace views/sales depend on that route, especially for logged-out views, but I'd guess the same is true for logged-in.

**Comment by p-jackson** [comment]
@vindl new idea: the site-less plugins marketplace shouldn't show the sidebar. The marketplace will look a lot like the logged out view except with the black topnav bar.

**Logged Out**
loggedout

**Logged In**
logged in

Feels like that's what the marketplace views/sales you mentioned above would be expecting.

The user clicks "My Sites" to go back to the "My Sites" section.

Maybe all it needs is this line to be removed? 🤷‍♂️ 🤞 
https://github.com/Automattic/wp-calypso/blob/d608ade5578ec7e9ab587ef1d740e252bdee3a14/client/my-sites/plugins/index.web.js#L87

**Comment by vindl** [comment]
@p-jackson I don't think that would be great either since this is also shown for single site Plugins (that's likely the large majority of the views). With that change, it would seem like we navigated away after clicking that sidebar link. 🤔 

Screenshot 2022-11-28 at 11 02 49 PM

**Comment by vindl** [comment]
@p-jackson After some thought, I think we should merge this as-is to fix the immediate problem of multisite plugin management not being accessible at all. The issue pointed out in https://github.com/Automattic/wp-calypso/pull/70454#pullrequestreview-1195178429 seems minor in comparison and I can start a follow-up issue for that. It will likely require some P2 coordination with the Marketplace teams.

**Comment by wojtekn** [comment]
> This could be problematic since marketplace views/sales depend on that route, especially for logged-out views, but I'd guess the same is true for logged-in.

Thanks for providing more background. I compared how it looks for logged out and for logged in, and I see that now. In such case I would think about removing the sidebar, but I see you already considered that and came to this conclusion:

> @p-jackson I don't think that would be great either since this is also shown for single site Plugins (that's likely the large majority of the views). With that change, it would seem like we navigated away after clicking that sidebar link. 🤔

I've checked it one more time, and I see that for a single-site user, we point to to this page, but URL includes the site slug:

https://wordpress.com/plugins/SLUG.wpcomstaging.com

As it includes the slug, would it make sense to redirect from `/plugins` to `/plugins/manage` for logged-in users?

**Comment by vindl** [comment]
> As it includes the slug, would it make sense to redirect from /plugins to /plugins/manage for logged-in users?

It makes sense. Since it has some potential to break existing marketplace flows unexpectedly, I'd like to verify that change with teams that worked on it first.

**Comment by p-jackson** [comment]
I've posted pdt2If-xg-p2 to get alignment.
