### PR TITLE
TSC: Fix unsupported TS syntax in `getTransformedStreamItems` selector

### LINKED ISSUE #66894: Running tsc manually crashes with "Parameter symbol already has a cached type which differs from newly assigned type"
### Quick summary

You can manually run the TypeScript type checks for the client directory with the command `yarn tsc -p client --noEmit`. This is helpful for finding TS errors before making a commit. 

However, now when I run that command, I get the following unhelpful error:

```
/Users/payton/Code/wp-calypso/node_modules/typescript/lib/tsc.js:96888
                throw e;
                ^

Error: Debug Failure. Expected [object Object] === [object Object]. Parameter symbol already has a cached type which differs from newly assigned type
    at assignParameterType (/Users/payton/Code/wp-calypso/node_modules/typescript/lib/tsc.js:64862:26)
    at assignContextualParameterTypes (/Users/payton/Code/wp-calypso/node_modules/typescript/lib/tsc.js:64827:21)
    at contextuallyCheckFunctionExpressionOrObjectLiteralMethod (/Users/payton/Code/wp-calypso/node_modules/typescript/lib/tsc.js:65229:29)
    at checkFunctionExpressionOrObjectLiteralMethod (/Users/payton/Code/wp-calypso/node_modules/typescript/lib/tsc.js:65208:13)
    at checkExpressionWorker (/Users/payton/Code/wp-calypso/node_modules/typescript/lib/tsc.js:66805:28)
    at checkExpression (/Users/payton/Code/wp-calypso/node_modules/typescript/lib/tsc.js:66707:38)
    at checkExpressionWithContextualType (/Users/payton/Code/wp-calypso/node_modules/typescript/lib/tsc.js:66396:28)
    at inferTypeArguments (/Users/payton/Code/wp-calypso/node_modules/typescript/lib/tsc.js:62906:39)
    at chooseOverload (/Users/payton/Code/wp-calypso/node_modules/typescript/lib/tsc.js:63566:53)
    at resolveCall (/Users/payton/Code/wp-calypso/node_modules/typescript/lib/tsc.js:63403:26)
```

This same error happens if I run `yarn tsc --build client/tsconfig.json` which appears to run fine in the CI environment. I tried starting with a fresh `node_modules` and removing `.tsc-cache` but neither has any effect.

It seems to have been introduced by https://github.com/Automattic/wp-calypso/pull/66817. Before that commit, running the command works as expected. Afterward, it produces the error above. 

However, I can't see how that PR could have caused any problems. I tried manually undoing the changes it made and the error continues.

### Steps to reproduce

1. `git checkout f0d3672658` (this is the merge commit which matches up to https://github.com/Automattic/wp-calypso/pull/66817)
2. `yarn tsc -p client --noEmit`
3. Notice that it displays a debug error.
4. `git checkout f0d3672658~1` (this is the commit before https://github.com/Automattic/wp-calypso/pull/66817)
5. `yarn tsc -p client --noEmit`
6. Notice that the process completes successfully.

### What you expected to happen

`tsc` should run and display any TypeScript errors.

### What actually happened

`tsc` fails.

### PR DESCRIPTION
**Pull request by tyxla**
## Proposed Changes

While working on #73890 I stumbled upon an error that I see when I run `yarn tsc --noEmit --project client/tsconfig.json`:

Screenshot 2023-03-02 at 14 02 17

The fix is straightforward: we're renaming the offending file from `.js` to `.ts` and specifying a type for the deps argument of the `treeSelect`'s `selector` argument. Without the type, TS was crashing.

This has also been reported in #66894.

Fixes #66894.

## Testing Instructions

* Checkout latest `trunk` locally.
* Run `yarn tsc --noEmit --project client/tsconfig.json`
* Verify you get the error from above.
* Now checkout this branch.
* Run the command again.
* Verify that it passes without errors (nothing should be output by the command).
* Smoke test the reader and a few different stream types.
* Verify that all checks are green. There are e2e tests that test the reader that would fail if we broke this selector.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by tyxla** [comment]
Made this a draft as I'm still working on it.

File: packages/tree-select/src/index.ts [hunk 1]
```diff
@@ -26,7 +26,7 @@ interface Options< A extends unknown[] > {
 	getCacheKey?: GenerateCacheKey< A >;
 }
 
-interface CachedSelector< S, A extends unknown[], R = unknown > {
+export interface CachedSelector< S, A extends unknown[], R = unknown > {
```
Comment (tyxla) [inline packages/tree-select/src/index.ts:29]: Necessary as without it we were also getting this error:

> Exported variable 'getTransformedStreamItems' has or is using name 'CachedSelector' from external module "/calypso/packages/tree-select/src/index" but cannot be named.

File: client/state/reader/streams/selectors/get-reader-stream-transformed-items.ts [hunk 2]
```diff
@@ -17,12 +17,13 @@ import 'calypso/state/reader/init';
...
 export const getTransformedStreamItems = treeSelect(
-	( state, { streamKey, recsStreamKey } ) => [
+	( state, { streamKey, recsStreamKey }: { streamKey: string; recsStreamKey: string } ) => [
 		getReaderStream( state, streamKey ).items,
 		getReaderStream( state, recsStreamKey ).items,
 		getReaderFollows( state ),
 	],
-	( [ items, recs, follows ] ) => {
+	// eslint-disable-next-line @typescript-eslint/no-explicit-any
+	( [ items, recs, follows ]: Array< any > ) => {
```
Comment (tyxla) [inline client/state/reader/streams/selectors/get-reader-stream-transformed-items.ts:26]: Here's the magic. For some reason, TS needs this type explicitly, although it's properly specified in `treeSelect`'s types.

File: client/state/reader/streams/selectors/get-reader-stream-transformed-items.ts [hunk 3]
```diff
@@ -17,12 +17,13 @@ import 'calypso/state/reader/init';
  * function( state, { streamKey: string, recsStreamKey: string }): Array
  */
 export const getTransformedStreamItems = treeSelect(
-	( state, { streamKey, recsStreamKey } ) => [
+	( state, { streamKey, recsStreamKey }: { streamKey: string; recsStreamKey: string } ) => [
```
Comment (tyxla) [inline client/state/reader/streams/selectors/get-reader-stream-transformed-items.ts:20]: Necessary only to complete the type definition. Went the simple inline way, no need for abstractions IMHO.

**Review by tyxla — COMMENTED** [review]
This is ready for a review 👀 

Doing a self-review, too.

**Review by danielbachhuber — APPROVED** [review]
This change resolves the unexpected crash for me. The code changes seem fine, although I don't feel 100% qualified to assess them.

image

image

**Review by sirbrillig — APPROVED** [review]
This seems to work and I can run `tsc` again!

**Review by Initsogar — APPROVED** [review]
Tested locally, and now I can run`yarn run typecheck` (`yarn run tsc --project client`).
Thanks for jumping in and helping us to fix it. :)
