### PR TITLE
Gutenberg: modify BrowserURL to match Calypso routes

### LINKED ISSUE #27298: Gutenberg: after autosave occurs url update is incorrect.
- Visit https://wpcalypso.wordpress.com/gutenberg
- Select a site
- Type and let an autosave occur

Expected: the browser address is updated to:
https://wpcalypso.wordpress.com/gutenberg/post/{siteSlug}/{postId}

Actual: the browser address is updated to https://wpcalypso.wordpress.com/gutenberg/post/post.php?post={postId}&action=edit

### PR DESCRIPTION
**Pull request by gwwar**
This fixes #27298 where the browser url was incorrectly updated to match wp-admin routes vs Calypso ones. There is a separate issue to update the document title appropriately in https://github.com/Automattic/wp-calypso/issues/27300

### Testing Instructions
- Visit http://calypso.localhost:3000/gutenberg
- Select a site
- in console type `state.ui.route.path` verify that this matches the current path
- Type and let an autosave occur

The browser address is updated to:
http://calypso.localhost:3000/gutenberg/post/{siteSlug}/{postId}

Instead of http://calypso.localhost:3000/gutenberg/post/post.php?post={postId}&action=edit

After the url updates, verify that `state.ui.route.path` in console matches

### CODE REVIEW

File: client/gutenberg/editor/browser-url/index.js [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+	setBrowserURL( postId ) {
+		window.history.replaceState(
+			{ id: postId },
+			null,
+			`${ window.location.href }/${ postId }`
+		);
+
+		this.setState( () => ( {
+			historyId: postId,
+		} ) );
```
Comment (dmsnell) [inline client/gutenberg/editor/browser-url/index.js]: we may want to rearrange this here so that the state updates first. I don't know if we could envision a re-render on `replaceState` or not but if that's possible but there's also an almost-circular thing going on here

what if we flipped it so `setState` were in `componentDidUpdate` and the `setBrowserURL` method _only_ set the browser URL?

```js
if ( … ) {
  this.setState( { historyId: postId }, () => this.setBrowserURL( postId ) );
}
```

also was the function syntax in `setState` habit or leftover? since we're assigning a raw value there I don't think there's any difference in the runtime

File: client/gutenberg/editor/browser-url/index.js [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+	/**
+	 * Replaces the browser URL with a post editor link for the given post ID
+	 *
+	 * @param {number} postId Post ID for which to generate post editor URL.
+	 */
+	setBrowserURL( postId ) {
+		window.history.replaceState(
+			{ id: postId },
+			null,
+			`${ window.location.href }/${ postId }`
```
Comment (dmsnell) [inline client/gutenberg/editor/browser-url/index.js]: we probably need to use the URL-building functions here. `href` could also include a fragment or query string

File: client/gutenberg/editor/browser-url/index.js [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+ * https://wordpress.com/gutenberg/post/mysiteslug/1234
+ */
+export class BrowserURL extends Component {
+	constructor() {
+		super( ...arguments );
+
+		this.state = {
+			historyId: null,
+		};
+	}
```
Comment (Copons) [inline client/gutenberg/editor/browser-url/index.js]: Is this format to keep the file as similar as possible to the Guten version?
Couldn't we move the state as a class property?

**Comment by Copons** [comment]
Tested and it works fine! ✨ 

I've left a minor nitpick and I agree with @dmsnell re: https://github.com/Automattic/wp-calypso/pull/27301#discussion_r218662006, but this looks pretty much ready!

File: client/gutenberg/editor/browser-url/index.js (hunk 1 above)
Comment (gwwar) [reply client/gutenberg/editor/browser-url/index.js]: I basically deleted code 🔪 from the base Gutenberg component.

The guts of the update cycle are from the `edit-post` BrowserURL component, but I suppose I could write something smaller from scratch :)

Last 30 minutes of the day trying to sneak in a PR

**Comment by gwwar** [comment]
Thanks for the reviews! I'll give this a better rewrite today or tomorrow, there isn't much here we need to save from the core component.

**Comment by kwight** [comment]
Works great for me too as-is 👍

**Comment by gwwar** [comment]
Thanks @dmsnell @Copons @kwight! I think I addressed most feedback in 41d9a0e, though let me know if we think it's overkill to connect to global state for just the route path. I can use `url.parse` otherwise.

File: client/gutenberg/editor/browser-url/index.js (hunk 3 above)
Comment (gwwar) [reply client/gutenberg/editor/browser-url/index.js]: Copy pasta removed in 41d9a0e

File: client/gutenberg/editor/browser-url/index.js (hunk 1 above)
Comment (gwwar) [reply client/gutenberg/editor/browser-url/index.js]: Oh hmm, we have `react/no-did-update-set-state` as an eslint rule. Let me 🤔 a bit more on this.

File: client/gutenberg/editor/browser-url/index.js [hunk 4]
```diff
@@ -0,0 +1,68 @@
...
+import getCurrentRoute from 'state/selectors/get-current-route';
+
+
+/**
+ * After making changes to a new post, this component will update the url to append the post id:
+ *
+ * For example:
+ * https://wordpress.com/gutenberg/post/mysiteslug
+ *
+ * https://wordpress.com/gutenberg/post/mysiteslug/1234
```
Comment (dmsnell) [inline client/gutenberg/editor/browser-url/index.js]: thanks for this excellent example - so clear

**Comment by gwwar** [comment]
I've updated this to use navigation middleware since I realized global routes weren't updated. I'll land this tomorrow unless folks have issues with the approach.

**Comment by gwwar** [comment]
Thanks for the reviews folks! 💖
