### PR TITLE
Using home layout to define whether to show Focused Launchpad

### LINKED ISSUE #101018: Remove empty launchpad
## Problem

After initiating a migration, people can still access their sites:

Image

After clicking the My home screen, I see a broken launchpad:

Image

## Where

1. Visit `/move`
2. Perform an assisted migration all the way to the end.
3. Click on View sites dashboard
4. Click on My Home.

### PR DESCRIPTION
**Pull request by paulopmt1**
Related to https://github.com/Automattic/wp-calypso/issues/101018

For more information and how to test, head out to 177382-ghe-Automattic/wpcom

### CODE REVIEW

**Comment by vykes-mac** [comment]
@paulopmt1 is there an associated jetpack PR that should be part of this test? I test with other flows but the focused launchpad did not show.

**Comment by paulopmt1** [comment]
> @paulopmt1 is there an associated jetpack PR that should be part of this test? I test with other flows but the focused launchpad did not show.

Hey @vykes-mac, thanks for testing it! 
Yeah, you'll want to apply this other PR in our sandbox (177382-ghe-Automattic/wpcom) to test it.

File: client/my-sites/customer-home/components/home-content/index.jsx [hunk 1]
```diff
@@ -122,6 +126,14 @@ const HomeContent = ( {
 		}
 	}, [ emailDnsDiagnostics ] );
 
+	useEffect( () => {
+		if ( layout?.view_name === 'VIEW_FOCUSED_LAUNCHPAD' ) {
+			setShowFocusedLaunchpad( true );
+		} else {
+			setShowFocusedLaunchpad( false );
+		}
+	}, [ layout ] );
```
Comment (p-jackson) [inline client/my-sites/customer-home/components/home-content/index.jsx]: `useEffect` 🙅🔥

```ts
const [ focusedLaunchpadDismissed, setFocusedLaunchpadDismissed ] = useState( false );

// ... 

if ( layout?.view_name === 'VIEW_FOCUSED_LAUNCHPAD' && ! focusedLaunchpadDismissed ) {
	return (
		<FullScreenLaunchpad { /* ... */ } />
	);
}

```

**Review by vykes-mac — APPROVED** [review]
Everything tests well!

File: client/my-sites/customer-home/components/home-content/index.jsx [hunk 2]
```diff
@@ -148,6 +160,22 @@ const HomeContent = ( {
 		);
 	}
 
+	if ( showFocusedLaunchpad ) {
+		return (
+			<FullScreenLaunchpad
+				onClose={ async () => {
+					setShowFocusedLaunchpad( false );
+					await updateLaunchpadSettings( siteId, { launchpad_screen: 'skipped' } );
+					queryClient.invalidateQueries( { queryKey: getCacheKey( siteId ) } );
```
Comment (p-jackson) [inline client/my-sites/customer-home/components/home-content/index.jsx]: There's already a hook for skipping to the next view: `useSkipCurrentViewMutation()`

**Review by p-jackson — COMMENTED** [review]
The loading behaviour is now a little different when you dismiss the focused launchpad.

**Now**
The My Home header appears which I think makes sense. But where's the `<div className="customer-home__loading-placeholder">`?

https://github.com/user-attachments/assets/4c553195-3b2e-40ff-9747-2ef1b574c93d


**Before**
There didn't use to be a loading state at all.

https://github.com/user-attachments/assets/ca0263bf-2b8b-4ed5-a289-749b6164ce6d

That's because the focused launchpad is actually pre-loading the layout and is so the My Home layout was ready to go.
https://github.com/Automattic/wp-calypso/blob/850057c0b7eec69a56545f63aa356720f882975c/client/my-sites/customer-home/components/full-screen-launchpad.tsx#L40

**Review by p-jackson — APPROVED** [review]
I addressed the feedback I left, and also ensured that the placeholder appears when the focused launchpad is skipped. I did that by ensuring the layout is cleared from the data store which means the `isLoading` flag is set to `true` again.

https://github.com/user-attachments/assets/fa0acfa8-af48-414b-afef-e80e7b732945

It's not too pretty. But the loading state has to go somewhere.

**Comment by p-jackson** [comment]
> It's not too pretty. But the loading state has to go somewhere.

Another option @paulopmt1 is to have the loading state on the `Skip to dashboard` button. If the button is set to busy and the `skipCurrentView()` function is called, then behind the scenes the layout will change and then the `<HomeContent>` will automatically switch to start rendering the new layout. In some ways it'd actually be a lot cleaner. `focusedLaunchpadDismissed` would no longer need to be used as a special case.

I think the problem is figuring out the design. I'm not sure what a busy version of the skip button should actually look like. I'll leave it up to you.

**Comment by paulopmt1** [comment]
> I think the problem is figuring out the design. I'm not sure what a busy version of the skip button should actually look like.

Yeah, currently, if we do apply the loading state for that button, it will be a bit weird. We would need to customize that CTA further:

image


Since the load is pretty fast, I think we're good with your loading state. Thanks for adding that!
