### PR TITLE
Show SMS option when an account is using the SMS for 2fa

### LINKED ISSUE #36809: 2fa: The SMS fallback option is shown even when a given WP.com account doesn't use SMS as second factor
We currently show the `Send Code via SMS` button when the 2fa cookie expires or when we want to disable 2fa. 

#### Steps to reproduce
1. Log in to WP.com with an account with 2fa enabled, and with sms disabled (an a8c account for example).
2. Navigate to `/` (`http://calypso.localhost:3000/`)
3. Remove the `twostep_auth` cookie from the `wordpress.com/public-api.wordpress.com` domain.
4. Navigate to `http://calypso.localhost:3000/me`
5. See that the 2fa prompt contains the `Send SMS` button

#### What I expected
The SMS option should likely be only visible when one sets up 2fa with the SMS method.

#### What happened instead
The SMS button is shown, clicking on it doesn't really sends the code because the backend code disables it.

#### Browser / OS version
Chrome, OSX 10.14

#### Screenshot / Video
Screenshot 2019-10-16 at 12 10 05
Screenshot 2019-10-16 at 12 09 55

#### Context / Source
This is somewhat related to #36063, as we probably need to separate the SMS and Authenticator App flows.

### PR DESCRIPTION
**Pull request by xknown**
#### Changes proposed in this Pull Request

This hides the Send Code by SMS buttons on the 2fa prompt as well as when one wants to disable 2fa for a given account.
Screen Shot 2020-08-12 at 1 35 42 PM

Screen Shot 2020-08-14 at 11 34 02 AM

- Only show the sms button on the 2fa prompt (re-auth) and 2fa disable prompt when sms recovery phone number has been added
- Fix linter issues: remove extra space in translated text and remove `autoFocus` because it's an accessibility / usability issue to skip the warning text above the verification field. Also add id for the verification field to associate it with its label.

#### Testing instructions

- Log in to WP.com with an account with 2fa enabled via app, and with sms disabled (an a8c account for example).
- Navigate to http://calypso.localhost:3000/
- Remove the `twostep_auth` cookie from the `wordpress.com/public-api.wordpress.com` domain and refresh.
- Navigate to http://calypso.localhost:3000/me
- [ ] The 2fa re-auth prompt does NOT contain the "Send code via text message" button at the bottom
- Re-enter the verification code and go to two-step settings (me/security/two-step) and click "Disable two-step authentication"
- [ ] The 2fa disable prompt does NOT contain the "Send code via SMS" button at the bottom
- Repeat the above steps with an account that has 2fa enabled via app and an SMS recovery number added.
- [ ] The 2fa re-auth prompt does contain the "Send code via text message" button at the bottom
- [ ] The 2fa disable prompt does contain the "Send code via SMS" button at the bottom

Fixes #36809

### CODE REVIEW

**Comment by xknown** [comment]
Fixing the failing `lint-and-translate` test seems out of scope of this change and can likely be done on a different PR.

**Comment by kwight** [comment]
@xknown From what I can tell, this has already been handled as part of https://github.com/Automattic/wp-calypso/pull/39515 – is that right?

**Comment by xknown** [comment]
> @xknown From what I can tell, this has already been handled as part of #39515 – is that right?

Not really, the PR you mention only added support for webauthn, it only updated the place where the SMS button is shown, but it didn't change anything related to SMS.

**Comment by kwight** [comment]
This will need a rebase and some attention then – I'll put it into the queue for janitorial rotation.

**Review by wp-desktop — DISMISSED** [review]
WordPress Desktop CI Failure for job "wp-desktop-mac".

@allilevine please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/849831). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

File: client/me/reauth-required/index.jsx [hunk 1]
```diff
@@ -268,7 +268,11 @@ const ReauthRequired = createReactClass( {
 				<TwoFactorActions
 					twoFactorAuthType={ twoFactorAuthType }
 					onChange={ this.handleAuthSwitch }
-					isSmsSupported={ method === 'sms' || method === 'authenticator' }
+					isSmsSupported={
+						method === 'sms' ||
+						( method === 'authenticator' &&
+							this.props.twoStepAuthorization.data.two_step_sms_last_four.length )
```
Comment (allilevine) [inline client/me/reauth-required/index.jsx:274]: @xknown I added this condition to show the "Send code via text message" button only when an SMS number has been added. When there is no SMS second factor (like for an a8c account), there's no second method shown:
Screen Shot 2020-08-12 at 1 35 42 PM

Does that fix the issue while keeping the SMS fallback option around for people who enabled it?

**Review by nsakaimbo — DISMISSED** [review]
👋 Does this PR affect any components that are displayed when logging out? For some reason desktop CI is consistently failing at the step:

```
1) Can logout from profile page
    - Can see app login page after logging out
```

([link](https://app.circleci.com/pipelines/github/Automattic/wp-calypso/70358/workflows/4129b7d5-ff37-49a6-a8c6-032967ac8579/jobs/849867))

CI is failing for two separate platforms (Mac and Linux) in the same location. If the desktop CI fails to pass even after a couple of re-tries you may want to take a closer look at any possible regressions this change might have introduced.

FWIW, it seems the last passing commit in this branch was b7b9183 "Only show the SMS button when the WP.com account is using the SMS for two factor". CI started failing with the subsequent commit.

**Comment by allilevine** [comment]
Hi @vortfu -- would you be able to provide a Secops review for this PR?

**Comment by xknown** [comment]
The change seems fine to fix the reported UI issue. However, I guess we still need to improve this in the future -- ideally we need to only allow the initial method a given user set up, the 2fa recovery number could be potentially implemented somewhere else.

**Comment by allilevine** [comment]
> The change seems fine to fix the reported UI issue. However, I guess we still need to improve this in the future -- ideally we need to only allow the initial method a given user set up, the 2fa recovery number could be potentially implemented somewhere else.

Thanks! Do you mean that a 2fa recovery number could be added somewhere else and we wouldn't know about it? Or that the account recovery number should be completely separate from 2fa?

File: client/me/reauth-required/index.jsx [hunk 2]
```diff
@@ -250,6 +250,9 @@ const ReauthRequired = createReactClass( {
 		const shouldEnableSmsButton =
 			this.state.smsRequestsAllowed || ( method === 'sms' && twoFactorAuthType === 'webauthn' );
 
+		const hasSmsRecoveryNumber = !! this.props.twoStepAuthorization.data.two_step_sms_last_four
```
Comment (retrofox) [inline client/me/reauth-required/index.jsx:253]: Is it possible that some property there is undefined and it could trigger an Error exception? If so, maybe we could check the full path in order to avoid it. Something like the following:

```suggestion
		const hasSmsRecoveryNumber = !! this.props?.twoStepAuthorization?.data?.two_step_sms_last_four
```

File: client/me/security-2fa-code-prompt/index.jsx [hunk 3]
```diff
@@ -192,6 +192,7 @@ class Security2faCodePrompt extends React.Component {
 
 	render() {
 		const method = twoStepAuthorization.isTwoStepSMSEnabled() ? 'sms' : 'app';
+		const hasSmsRecoveryNumber = !! twoStepAuthorization.data.two_step_sms_last_four?.length;
```
Comment (retrofox) [inline client/me/security-2fa-code-prompt/index.jsx:195]: Similar suggestion to [this one](https://github.com/Automattic/wp-calypso/pull/36811/files#r495007558).

File: client/me/reauth-required/index.jsx (hunk 2 above)
Comment (allilevine) [reply client/me/reauth-required/index.jsx]: Thanks, good idea! I made the change in both places.

**Review by retrofox — COMMENTED** [review]
My tests

* Log in to WP.com with an account with 2fa enabled via app, and with sms disabled (an a8c account for example). ✅





* Navigate to http://calypso.localhost:3000/ ✅

* Remove the twostep_auth cookie from the wordpress.com/public-api.wordpress.com domain and refresh. ✅


* Navigate to http://calypso.localhost:3000/me ✅ 

* The 2fa re-auth prompt does NOT contain the "Send code via text message" button at the bottom ✅ 



* Go to two-step settings (me/security/two-step) and click "Disable two-step authentication"

It's like I can't authenticate from this point. The app asks, again and again, introduce the _the verification code generated by your authenticator app._

**Comment by retrofox** [comment]
> It's like I can't authenticate from this point. The app asks, again and again, introduce the _the verification code generated by your authenticator app._

It happens in Chrome. Tested in Firefox and it works as expected.

**Review by retrofox — APPROVED** [review]
LGTM. 👍

**Comment by allilevine** [comment]
> > It's like I can't authenticate from this point. The app asks, again and again, introduce the _the verification code generated by your authenticator app._
> 
> It happens in Chrome. Tested in Firefox and it works as expected.
> 
> 

Verified that this is an issue on the master branch. Opened #46127
