### PR TITLE
Editor: Use Redux editPost Action to update th post's password

### LINKED ISSUE #12276: Editor: Not able to edit passwords on password protected posts
It's not possible to edit passwords on password protected posts.

#### Steps to reproduce

1. Starting at: https://wordpress.com/post/
2. Publish a new post and, under the editor's Status module, edit the post's visibility so that it's password protected.
3. Navigate back to the editor for your newly published post.
4. Attempt to backspace over/edit the post's password.

#### What I expected

I expected to be able to edit the password after clicking/typing into the password field.

#### What happened instead

It wasn't possible to edit the password after typing straight into the field. 

I needed to toggle to "Public" and then back to "Password Protected" in order to be able to edit/change the password:

#### Browser / OS version

Chrome / macOS Sierra 10.12.3

#### Screenshot / Video

password

#### Context / Source

Reported in 249921-hc

#user-report #reallife

### PR DESCRIPTION
**Pull request by youknowriad**
This is an alternative to #12353 closes #12276 

Since the password prop is retrieved from the Redux Edited Post, we should use the redux action to dispatch any change to this value.

**Testing instructions**

 - Draft a new post
 - Set a password to this post
 - Publish
 - Edit the post's password
 - Save the edited post.

The password should update properly.

### CODE REVIEW

File: client/post-editor/editor-visibility/index.jsx [hunk 1]
```diff
@@ -158,21 +162,23 @@ export default React.createClass( {
...
-		newVisibility = event.target.value;
+		const { siteId, postId } = this.props;
+		const defaultVisibility = 'draft' === this.props.status ? 'draft' : 'publish';
+		const postEdits = {
+			status: this.props.savedStatus && 'private' !== this.props.savedStatus
+				? this.props.savedStatus
+				: defaultVisibility
+		};
+		const newVisibility = event.target.value;
+		let reduxPostEdits = false;
```
Comment (aduth) [inline client/post-editor/editor-visibility/index.jsx]: This would work just as well (and arguably more semantically meaningful) not assigning a value:

```js
let reduxPostEdits;
```

**Comment by youknowriad** [comment]
@aduth I had to do more changes than expected because I've figured out the `visibility` was not computed properly, but we were mixing the edited password with the saved status when computing the current visibility which causes bugs (especially on saved private posts, when switching the visibility). It should be ok now

File: client/post-editor/edit-post-status/index.jsx [hunk 2]
```diff
@@ -195,16 +195,15 @@ class EditPostStatus extends Component {
...
 		}
 
-		const { status, password, type } = this.props.post || {};
+		const { password, type } = this.props.post || {};
 		const isPrivateSite = this.props.site && this.props.site.is_private;
 		const savedStatus = this.props.savedPost ? this.props.savedPost.status : null;
 		const savedPassword = this.props.savedPost ? this.props.savedPost.password : null;
 		const props = {
-			visibility: utils.getVisibility( this.props.post ),
+			status: this.props.status,
```
Comment (aduth) [inline client/post-editor/edit-post-status/index.jsx]: Did the logic need to be moved up as a prop? Seems like it would have been enough to simply remove the `utils.getVisibility`.

File: client/post-editor/editor-visibility/index.jsx [hunk 3]
```diff
@@ -65,10 +69,23 @@ export default React.createClass( {
...
+		if ( 'private' === props.status ) {
+			return 'private';
+		}
+
+		return 'public';
+	},
+
 	setVisibility( props ) {
-		if ( props.visibility !== this.state.visibility ) {
+		const newVisibility = this.getVisibility( props );
```
Comment (aduth) [inline client/post-editor/editor-visibility/index.jsx]: At this point I question whether `visibility` should exist in state at all, and instead to simply call upon `getVisibility` directly at any point we'd have used the state value.

File: client/post-editor/edit-post-status/index.jsx (hunk 2 above)
Comment (youknowriad) [inline client/post-editor/edit-post-status/index.jsx]: Since we were already passing the `status` and `password`, passing visibility would have been a `duplicate` prop for me. That's why I prefer to keep it inside the editorVisibility component.

Removing `utils.getVisibility`: It's still used in one other place

File: client/post-editor/editor-visibility/index.jsx (hunk 3 above)
Comment (youknowriad) [inline client/post-editor/editor-visibility/index.jsx]: Yep, good point. I think we should drop it

File: client/post-editor/editor-drawer/index.jsx [hunk 4]
```diff
@@ -308,8 +308,11 @@ const EditorDrawer = React.createClass( {
 	renderStatus() {
 		// TODO: REDUX - remove this logic and prop for EditPostStatus when date is moved to redux
 		const postDate = this.props.post && this.props.post.date
-				? this.props.post.date
-				: null;
+			? this.props.post.date
+			: null;
+		const postStatus = this.props.post && this.props.post.status
```
Comment (aduth) [inline client/post-editor/editor-drawer/index.jsx]: Minor refactoring point, this could be cleaner with `_.get`:

```
const postDate = get( this.props.post, 'date', null );
const postStatus = get( this.props.post, 'status', null );
```

Not clear whether `null` is necessary fallback.

File: client/post-editor/editor-drawer/index.jsx [hunk 5]
```diff
@@ -321,7 +324,9 @@ const EditorDrawer = React.createClass( {
 					onTrashingPost={ this.props.onTrashingPost }
 					onPrivatePublish={ this.props.onPrivatePublish }
 					setPostDate={ this.props.setPostDate }
-					site={ this.props.site }>
+					site={ this.props.site }
+					status={ postStatus }
+				>
```
Comment (aduth) [inline client/post-editor/editor-drawer/index.jsx]: Minor: In moving the opening `>`, we could have also made this self-closing `/>`.
