### PR TITLE
Me:2FA: Add site name and username to backup code printout

### LINKED ISSUE #398: Me: 2fa: add title to print page for 2fa backup codes
When printing backup codes in Chrome the default title for the document is "Untitled". Which is no big deal if you're printing directly, but I was saving mine temporarily to print them all in a batch and then delete. It would be a simple change to have it be something generic like "WordPress.com - Backup Codes for usernamehere"

Steps to reproduce:
1. Go to /me/security
2. Generate new backup codes
3. Print them
4. See how the page doesn't have a title?

screen shot 2015-07-14 at 23 07 42

a9a21b6e-2a7d-11e5-971c-d241d423f79a

This is related to #385

### PR DESCRIPTION
**Pull request by blowery**
#### Changes proposed in this Pull Request

* Adds the site name and username to the 2FA code printout

#### Testing instructions

* Generate new 2FA codes and click the Printer button. The generated printout should contain WordPress.com in the title and both WordPress.com and the username in the text

Fixes #398

### CODE REVIEW

File: client/me/security-2fa-backup-codes-list/index.jsx [hunk 1]
```diff
@@ -146,14 +146,16 @@ class Security2faBackupCodesList extends React.Component {
 		let row;
 		let html = '<html><head><title>';
 
-		html += this.props.translate( 'Backup verification codes' );
+		html += this.props.translate( 'WordPress.com Backup Verification Codes' );
```
Comment (a8ci18n) [inline client/me/security-2fa-backup-codes-list/index.jsx]: :warning: This change will be queued for retranslation. We'll display the English text until then.

**Review by lynnbgriffith — APPROVED** [review]
🚢LGTM

**Review by tyxla — APPROVED** [review]
LGTM 🚢
