### PR TITLE
Stats: Properly display new graph data when new data is received

### LINKED ISSUE #45314: Viewing historical graph data renders with unordered data
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/stats/day/{site-URL}
2. Take note of how the bar graph displays
3. Modify the URL to view the daily stats for a date that falls before the current range of the bar graph, e.g. by appending `?startDate=2019-06-23`
4. Modify the URL again and try the next month. The graph will show data that is not ordered.

#### What I expected
For the data on the graph to be in the correct order

#### What happened instead
The graph showed data in the incorrect order

#### Browser / OS version
Chrome

#### Screenshot / Video
Stats3

### LINKED ISSUE #45315: Viewing historical graph data renders empty
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/stats/day/{site-URL}
2. Take note of how the bar graph displays
3. Modify the URL to view the daily stats for a date that falls before the current range of the bar graph, e.g. by appending `?startDate=2019-06-23`
4. Modify the URL again and try another month. The graph will show that there is no data, but if you refresh the page, you'll see data on the graph

#### What I expected
For there to be data on the graph

#### What happened instead
The graph showed "No Activity"

#### Browser / OS version
Chrome

### PR DESCRIPTION
**Pull request by krymson24**
#### Changes proposed in this Pull Request

* We render a new set of data instead of appending data to the store when the first data point from the API is different from the first data point from our store. The previous behavior resulted in potential data points outside the bounds of the graph range and undefined values which resulted in empty graph states. If the dataset length or period differs from what is in the store, we assume that the data received is a new set of data.
* Considerations for how to solve this problem were documented here: https://github.com/Automattic/wp-calypso/issues/45315

#### Testing instructions

1. Starting at URL: `/stats/day/{site-URL}`
2. Take note of how the bar graph displays
3. Modify the URL to view the daily stats for a date that falls before the current range of the bar graph, e.g. by appending `?startDate=2019-06-23`
4. Reload the page with the same start date. The data on the graph should be consistent and should not be empty.
5. Change the startDate, and/or change the time period. Take note of the data and then reload the page. The data on the graph should be consistent and should not be empty.

Note: This PR branches from the changes implemented here: https://github.com/Automattic/wp-calypso/pull/45313 to ensure that the graphs show the correct labels on the x-axis. This PR should be merged after that PR is.

#### GIFs

Changing period

Changing start date

Reloading the page and changing the start date in the URL

Fixes #45315
Fixes #45314

### CODE REVIEW

File: client/state/stats/chart-tabs/test/reducer.js [hunk 1]
```diff
@@ -106,12 +106,6 @@ describe( 'reducer', () => {
 			expect( state ).toEqual( {
 				[ siteId ]: {
 					[ period ]: [
-						{
```
Comment (kwight) [inline client/state/stats/chart-tabs/test/reducer.js:109]: Why does this need to be removed?

**Comment by kwight** [comment]
Fantastic @krymson24 , works well! 🎉  We'll give a rebase and another look and approval after #45313 is in, but I think this should be good to go too 👍

**Comment by krymson24** [comment]
> Fantastic @krymson24 , works well! 🎉 We'll give a rebase and another look and approval after #45313 is in, but I think this should be good to go too 👍

Rebased!

File: client/state/stats/chart-tabs/test/reducer.js (hunk 1 above)
Comment (krymson24) [reply client/state/stats/chart-tabs/test/reducer.js:109]: The test case didn't make sense to me to begin with. The test case is:

`should not merge count records with differing period values`

The previous response/state had a period of `2018-09-20`. The new response/state has a period of `2019-09-30` with a period of `day`. Given what we're testing for per the test case, these should not be merged, and the result should just be `2019-09-30`. I think the expected result now aligns with the test case, but it wasn't previously.

**Review by kwight — APPROVED** [review]
