### PR TITLE
Gutenberg: Persist the nudge notice dismissal.

### LINKED ISSUE #29252: Gutenberg: opt in notice continues to show after opting out
#### Steps to reproduce
1. Open Gutenberg editor on a site that has opted in.
2. Opt out using Inline help or Ellipsis menu.
3. Navigate to Classic editor.
4. The opt in notice is displayed again no matter how many times we opt out, and it will always pop up in front of content in the editor.

screenshot 2018-12-11 at 05 10 58

#### What I expected

We should remove the notice after opting out and just leave the "Learn more" nudge in the sidebar.

### PR DESCRIPTION
**Pull request by kwight**
#### Changes proposed in this Pull Request

This PR takes advantage of existing Calypso user preferences to note when a user dismisses the "level up" nudge notice displayed at the bottom of the editor (when a user has not yet opted in to Gutenberg). Note that we'll still leave the sidebar nudge as a constant prompt to opt in (it's less intrusive, as it's not obscuring editor content, like the notice does).

gute-notice

#### Testing instructions

* Apply this branch, and load `/post/:site` with a site that has not opted in to Gutenberg.
* Dismiss the "level up" notice at the bottom of the screen.
* Observe the API call to `https://public-api.wordpress.com/rest/v1.1/me/preferences?http_envelope=1`, and verify it sends a value of `gutenberg_nudge_notice_dismissed: true`.
* Refresh the page, and see that the notice does not display.

Fixes #29252 .

### CODE REVIEW

**Comment by vindl** [comment]
> Should we also set this dismissal if a user clicks "Use the Classic editor" in the modal dialog? Might be helpful, but it's also a little weird... meh, let's leave it like this, a user will figure out how to get rid of it quickly enough.

👍 for leaving it as is.

File: client/post-editor/editor-gutenberg-opt-in-notice/index.jsx [hunk 1]
```diff
@@ -30,20 +32,14 @@ class EditorGutenbergOptInNotice extends Component {
...
+		noticeDismissed: PropTypes.bool,
+		dismissNotice: PropTypes.func,
 	};
 
-	state = {
-		dismissed: false,
-	};
-
-	dismissNotice = () => this.setState( { dismissed: true } );
+	dismissNotice = () => this.props.dismissNotice( 'gutenberg_nudge_notice_dismissed', true );
```
Comment (vindl) [inline client/post-editor/editor-gutenberg-opt-in-notice/index.jsx]: One thing I'd consider is saving the timestamp of dismissal here instead of just `true`. Just in case someone decides in a month that we should boost opt-in rates by showing this nudge again every month or so.
It would make things easier to handle, instead of grandfathering. Your call. :)

Comment (vindl) [inline client/post-editor/editor-gutenberg-opt-in-notice/index.jsx]: One thing I'd consider is saving the timestamp of dismissal here instead of just true. Just in case someone decides in a month that we should boost opt-in rates by showing this nudge again every month or so.
It would make things easier to handle, instead of grandfathering. Your call. :)

Comment (kwight) [reply client/post-editor/editor-gutenberg-opt-in-notice/index.jsx]: I'll stick with what we have, and we can deal with it if it ever comes to pass 🤷‍♂️
