### PR TITLE
Prevent safari from prompting for storage

### LINKED ISSUE #36858: Safari Storage Prompt
#### Steps to reproduce
1. Using specific Browser/OS version below
2. Starting at URL: Varies

#### What I expected

To use the browser without prompting for storage

#### What happened instead

Users are periodically receive a variation of this message:

`Do you want to allow "https://wordpress.com" to use up to X.X GB of storage on your Mac?`

We haven't been able to reproduce the error locally, but have received multiple user reports. It seems to be related to the MacOS Catalina release and/or the Safari 13.0.1 release.

For several users, even after accepting the local storage the message continues to pop up. Even if the initial notification is necessary, having to repeatedly answer this prompt is a bad UX. The size of the data varies from several hundred MB to several GB.

#### Browser / OS version

Safari 13.0.1
MacOS 10.14.6

or

iPadOS13 with Safari

#### Screenshot / Video

Screen Shot 2019-10-17 at 09 58 01

#### Context / Source

Discussed in p2EDhh-Us-p2
Reported in:
14160447-hc
1041772-hc (follow-up in 2382371-zen)
15565796-hc
15472317-hc
15522283-hc (This one is on iOS with iPadOS 13)
8031519-hc
2411378-zen (iPad)
14339371-hc

### PR DESCRIPTION
**Pull request by blowery**
Safari has a bug where the write-ahead log that indexed db uses grows continually until the page reloads, and this size counts towards our storage quota. If you use Calypso long enough, eventually you'll be prompted to give us more storage room, even though we're not using much.

To work around this, clear out storage before saving off the redux tree. This also clears the write-ahead log and keeps us under the cap.

Fixes #36858

### CODE REVIEW

**Review by gwwar — DISMISSED** [review]
Nice sleuthing @blowery ! 

I tested this locally and didn't find any regressions. Were there any specific cases we'd like folks to test?

**Comment by chaitanyamsv** [comment]
Could this be merged, so we can let the customer know? Thank you for all your hard work on this issue!

File: client/state/initial-state.js [hunk 1]
```diff
@@ -193,13 +193,16 @@ export function persistOnChange( reduxStore ) {
...
 
-			const storeTasks = map( serializedState.get(), ( data, storageKey ) =>
-				persistentStoreState( reduxStateKey, storageKey, data, _timestamp )
-			);
-
-			Promise.all( storeTasks ).catch( setError =>
-				debug( 'failed to set redux-store state', setError )
-			);
+			// clear out storage first to prevent safari's WAL from growing forever
+			clearStorage().then( () => {
```
Comment (jsnajdr) [inline client/state/initial-state.js]: This won't work well with the current dynamically loaded reducers:
- first session: loads the `root` and the `signup` reducer, stores `root` and the `signup` state
- second session: loads the `root` and `woo` reducers, but not `signup` (not on a signup route any more), then clears storage and stores `root` and `woo` state. The `signup` state will be wiped out.

The series of patches by @sgomes will change that, as it always loads all state. But at this moment, let's think about whether we're not breaking signup -- that's the only section that I think is at risk.

File: client/state/test/initial-state.js [hunk 2]
```diff
@@ -553,7 +561,7 @@ describe( 'initial-state', () => {
 
 			clock.tick( SERIALIZE_THROTTLE );
 
-			expect( setStoredItemSpy ).toHaveBeenCalledTimes( 1 );
+			expect( clearStorageSpy ).toHaveBeenCalledTimes( 1 );
```
Comment (jsnajdr) [inline client/state/test/initial-state.js]: Shouldn't this test still test if `setStoredItem` was called? We now clear the storage first and _then_ store the state.

File: client/state/test/initial-state.js [hunk 3]
```diff
@@ -531,6 +531,13 @@ describe( 'initial-state', () => {
 			// we use fake timers from Sinon (aka Lolex) because `lodash.throttle` also uses `Date.now()`
 			// and relies on it returning a mocked value. Jest fake timers don't mock `Date`, Lolex does.
 			clock = useFakeTimers();
+			clearStorageSpy = jest.spyOn( browserStorage, 'clearStorage' ).mockImplementation( () => {
+				return {
+					then( fn ) {
+						fn();
```
Comment (jsnajdr) [inline client/state/test/initial-state.js]: This mock will call the callback synchronously, which is a behavior different from the real one. A better mock is one of:
```js
.mockImplementation( () => Promise.resolve() );
.mockReturnValue( Promise.resolve() );
.mockResolvedValue(); // my favorite
```

File: client/state/initial-state.js (hunk 1 above)
Comment (blowery) [reply client/state/initial-state.js]: Good point. 

Maybe we break this out a different way. Load all of the current keys, clear the db, then save them all again. Though if we did that we'd also need a `isPurging` type state that prevented writes during the async clear process.

File: client/state/test/initial-state.js (hunk 2 above)
Comment (blowery) [reply client/state/test/initial-state.js]: yup, missed that. working on it now.

File: client/state/test/initial-state.js (hunk 3 above)
Comment (blowery) [reply client/state/test/initial-state.js]: yeah, that's ... tricky. We need to run the assertions after all of the promises have resolved, so we need a way to wait until all of the mocked assertions have completed. The sync hack was a hack to work around that. 

Not going to worry about it given we probably have to rework this entirely.

File: client/state/initial-state.js (hunk 1 above)
Comment (blowery) [reply client/state/initial-state.js]: Hmm, if we wanted to do that, landing https://github.com/Automattic/wp-calypso/pull/38320 would make it much easier, as that gives us a supported way of getting all the current values.

**Comment by blowery** [comment]
@chaitanyamsv currently on hold to make sure we're not breaking some signup flows with this

File: client/state/initial-state.js (hunk 1 above)
Comment (jsnajdr) [reply client/state/initial-state.js]: > Load all of the current keys, clear the db, then save them all again.

Yes, that should work well. The race condition can be avoided by adding some promise-based equivalent of a mutex.

>  Hmm, if we wanted to do that, landing #38320 would make it much easier

I agree. I can review that work ASAP and see if it can be merged quickly. It would help a lot with this high-priority issue.

**Comment by gwwar** [comment]
Wanted to check in on this one to help if y'all needed it. Were there other related PRs that needed review?

**Comment by blowery** [comment]
@gwwar https://github.com/Automattic/wp-calypso/pull/38976 could use a review, it's a stats-pushing PR to collect counts when folks refuse the storage upgrade.

We're sort of holding on https://github.com/Automattic/wp-calypso/pull/37883 since that would simplify how this PR could work. The approach taken in this PR breaks the storage bits in the signup flow.

**Comment by blowery** [comment]
Back working on this one

**Comment by blowery** [comment]
OK, thanks to @sgomes getAllItems method, we have a working method that blocks writes while we're resetting. Currently looking into reliable ways to detect Safari 13.

File: client/lib/browser-storage/index.ts [hunk 4]
```diff
@@ -21,6 +21,10 @@ const STORE_NAME = 'calypso_store';
 
 const SANITY_TEST_KEY = 'browser-storage-sanity-test';
 
+function isAffectedSafari() {
+	return true;
```
Comment (blowery) [inline client/lib/browser-storage/index.ts]: looking for a safe / small way to detect affected webkit versions, but having trouble. We may want to land this without the safari check.

The complication here is iOS in-app and Chromed browsers on iOS. All browsers on iOS are webkit under the hood, but they don't exhibit the same behavior when the quota is reacted. Chrome for iOS for example never prompts the user and just starts failing writes to idb.

**Comment by blowery** [comment]
@gwwar This is ready for another look I think. If you have any ideas on how to reliably detect Safari 13, I'd love the help.

```
function isAffectedSafari(): boolean {
	// we only want to affect Safari/13
	// but everything on iOS is Safari...
	if ( !globalThis.navigator ) return false;
	const ua = globalThis.navigator.userAgent;
    // this misses Chrome / Firefox / Opera / etc on iOS...
	return /Version\/13\./.test( ua ) && /Safari/.test(ua);
}
```

Is my current best effort...

**Comment by gwwar** [comment]
Nice I'll take a look tomorrow @blowery! Was there a trick to logging into Safari from localhost, or do I need to run the full docker image?

For UA detection, there's [lib/user-agent](https://github.com/Automattic/wp-calypso/blob/c68896a4eb2abbf22fd1b106ef359a732978d885/client/lib/user-agent/index.js#L5) that is an alias for the `express-useragent`package. So try a combo of [isSafari](https://github.com/biggora/express-useragent/blob/master/lib/express-useragent.js#L294) and [getBrowserVersion](https://github.com/biggora/express-useragent/blob/master/lib/express-useragent.js#L337).

**Comment by blowery** [comment]
> For UA detection, there's lib/user-agent that is an alias for the express-useragentpackage. So try a combo of isSafari and getBrowserVersion.

Yeah, this is weirder than that unfortunately. Since every "browser" on iOS is really webkit under the hood, they all suffer the same bug, though it manifests in different ways. Chrome for iOS never prompts for storage, it just dies. 

I suppose I could just check the iOS version, if I can get ahold of it..

**Comment by blowery** [comment]
See https://chromium.googlesource.com/chromium/src.git/+/master/docs/ios/user_agent.md for details on the Chrome for iOS UA

**Comment by sgomes** [comment]
@blowery It's probably best to avoid user agents altogether, particularly now that Chrome is intending to deprecate the UA string (and other vendors might follow?)

And as you mention, there's all the issues with Chrome and Firefox (and everything else) using WebKit under the hood in iOS.

There are ways we can work around this without using UA strings, though. If the bug is not directly detectable, we could use a feature-detection type approach to determine the underlying engine and even version, if necessary. Happy to work with you on that!

Things I need to know:
- Does the detection have to be sync, or can it be async?
- Do we need to look for a particular version range, or are all Safari versions equally buggy in this regard?
- Do we need to differentiate between desktop / mobile or macOS / iOS?

**Comment by blowery** [comment]
> Does the detection have to be sync, or can it be async?

It can be async

> Do we need to look for a particular version range, or are all Safari versions equally buggy in this regard?

The WebKit backing Safari 13+ only. Also, this may end up getting fixed in a patch release, which makes me think we'd want to be able to gate it, but at that point I think we'd drop the mitigation and tell folks to upgrade.

> Do we need to differentiate between desktop / mobile or between macOS / iOS?

Nope, it affects both

**Comment by sgomes** [comment]
Thanks, @blowery! 

This is the best I came up with:
```js
const isBuggyIDBWebkit = !!IDBKeyRange.lowerBound(0).includes && !!window.webkitAudioContext && !!window.PointerEvent;
```

The first check ensures that it has IDB 2, the second that it's a WebKit (and not Blink-based) browser, and the third checks for Pointer Event support, which was only added in Safari 13's WebKit.

If a subsequent version of Safari/WebKit fixes the issue, we can extend this check to exclude it.

I tested this across a bunch of browsers and versions and it seems to work, but please run some checks yourself! If it produces an unexpected result somewhere, we can refine it.

**Comment by blowery** [comment]
@sgomes that check looks good everywhere I've tried it. Nice work!

**Comment by sgomes** [comment]
@blowery Looks like you're going to have to safeguard that check to prevent it from failing on the server:

```js
const isAffectedSafari =
  typeof window !== 'undefined' &&
  [...]
```

**Comment by blowery** [comment]
Desktop failures seem to be unrelated

**Comment by blowery** [comment]
> Was there a trick to logging into Safari from localhost, or do I need to run the full docker image?

Looks like using the docker image and faking out wpcalypso.wordpress.com is the only option right now. ITP has killed local development.

**Review by gwwar — APPROVED** [review]
> Looks like using the docker image and faking out wpcalypso.wordpress.com is the only option right now. ITP has killed local development.

Okay, I'm not having luck with my local docker build, it takes ages and then fails to make an image. 

@blowery Maybe feature flag this on horizon or wpcalypso for manual Safari testing, or if folks are pretty confidant we can try this in prod next week and monitor MC error stats from `calypso-browser-storage`

Giving approval here in case folks would like to try and 🚢

**Comment by gwwar** [comment]
As an aside we might want to revisit build times for thedocker since we do need a working env for folks should on specific features (like specific routing/login).

**Comment by blowery** [comment]
@gwwar I'm getting it to build locally (what errors are you seeing? you may need to give docker more memory, I give it 8GB per container...), however the new way we handle login tokens means that we need to serve it over https for it to work...

**Comment by blowery** [comment]
@gwwar filed https://github.com/Automattic/wp-calypso/issues/39216 to track the local docker problems

**Comment by blowery** [comment]
> Maybe feature flag this on horizon or wpcalypso for manual Safari testing...

Sounds like a good plan. I'll add that in.
