### PR TITLE
Subscription Management: Fix handling of invalid urls.

### LINKED ISSUE #76898: Subscription Management: JavaScript error when using link to login
### Quick summary

See screenshot below. When I start with an incognito window, go to `/subscriptions`, enter my a8c email, then paste the link in to this incognito window, I end up with JavaScript errors and a blank page.

Screenshot 2023-05-12 at 6 57 52 PM

### Steps to reproduce

1. Start with incognito window and logged out.
2. Enter in a8c email.
3. Go to email and get link.
4. Paste into incognito window.
5. Verify JS error.

### What you expected to happen

No error.

### What actually happened

Error.

### Impact

Some. I can reproduce on my a8c account but not on my personal WPCOM account.

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### Logs or notes

Tested on Mac OS and Microsoft Edge.

### PR DESCRIPTION
**Pull request by yansern**
Fixes https://github.com/Automattic/wp-calypso/issues/76898

## Proposed Changes

Site subscription with `false` in the url property causes WSOD. The `false` value may come from purged Jetpack-connected site (even though it doesn't seem to apply to other purged Jetpack-connected sites I've seen).

The fix is done on client-side instead of server-side because the server-side API endpoint is also shared with Reader, and I'd like to avoid diving into Reader's code to see how they are handling falsy URLs (and if they are handling it).

## Testing Instructions

**Setup**
1. On your sandbox, modify `class[...]read-following-mine-v1-2-endpoint.php` at line 423, make it return `false`.
2. Sandbox `public-api.wordpress.com`.

**Test**
1. Test as external user by setting `subkey` on the `calypso.localhost:3000` cookie.
2. Go to `/subscriptions`.
3. It should render the list just fine instead of WSOD'ing.

Screenshot of how it looks like when rendered:

image

Error Reference:

image

image

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: client/landing/subscriptions/components/site-list/site-row.tsx [hunk 1]
```diff
@@ -32,7 +32,7 @@ export default function SiteRow( {
 	date_subscribed,
 	delivery_methods,
 }: SiteSubscription ) {
-	const hostname = useMemo( () => new URL( url ).hostname, [ url ] );
+	const hostname = useMemo( () => ( url ? new URL( url ).hostname : '' ), [ url ] );
```
Comment (mashikag) [inline client/landing/subscriptions/components/site-list/site-row.tsx]: If we are not planning to change the API, then we should also correct our types, i.e. in `SiteSubscription` type we should say that it may have value of `boolean`, or even to be more precise `false`.

**Review by JuanLucha — APPROVED** [review]

File: client/landing/subscriptions/components/site-list/site-row.tsx (hunk 1 above)
Comment (yansern) [reply client/landing/subscriptions/components/site-list/site-row.tsx]: Done. https://github.com/Automattic/wp-calypso/pull/76944/commits/83a4cc9a04553fbf18502a258a10b8b5206096b5

**Comment by yansern** [comment]
Relooking at this issue with fresher eyes, I'm going to use `try..catch` to handle more edge cases.

image

**Comment by obenland** [comment]
> The fix is done on client-side instead of server-side because the server-side API endpoint is also shared with Reader, and I'd like to avoid diving into Reader's code to see how they are handling falsy URLs (and if they are handling it).

`is_valid_blog_for_feed_subscription()` is supposed to filter out spam sites and deleted sites—wouldn't purged Jetpack-connected sites fall within that bucket?

**Comment by obenland** [comment]
@yansern Not sure if you got a notification for this? ^

**Comment by yansern** [comment]
> `is_valid_blog_for_feed_subscription()` is supposed to filter out spam sites and deleted sites—wouldn't purged Jetpack-connected sites fall within that bucket?

Thanks!  Looking at the API endpoint, generating the subscription site list for both external users and logged-in users go through the same `build_subscriptions` function which calls the `is_valid_blog_for_feed_subscription()` function.

If the function is already called, it means it hasn't catered for other edge cases.

What exact other edge cases are there? I'm not sure. I will set up a logstash to monitor sites that produce these false URLs and determine what these other edge cases are.

> @yansern Not sure if you got a notification for this? ^

Thanks for the persistent reminder! You leave no stone unturned!

**Comment by yansern** [comment]
Issue created: https://github.com/Automattic/wp-calypso/issues/77487
