### PR TITLE
ETK: Add typecheck in TC

### LINKED ISSUE #50334: TypeScript errors are not caught when building Editing Toolkit
### Steps to reproduce the behavior

1. On your local machine, introduce a TypeScript error in the `apps/editing-toolkit` folder (for example: #50335)
2. Notice how the error is flagged in a IDE that supports TypeScript
3. Build the project (`yarn && yarn build` in one terminal tab) and ETK (`cd apps/editing-toolkit && yarn build` in another tab)
4. Notice how the build completes, and no TypeScript errors were logged
5. Commit the code and push to a new PR
6. Notice how the CI check pass successfully, and no TypeScript errors were logged

#### What I expected to happen

- The site build should not complete if there are TypeScript errors
- In the same way, CI tasks in a PR should fail if there are TypeScript errors

#### What actually happened

- The site build completed successfully
- CI tasks in a PR passed successfully

### Context

This scenario already happened a handful of times in the past weeks and caused a few bugs (since the team trusted TSC to flag errors in the code).

I opened a few PRs to exemplify this issue:
- #50335 introduced an error in `apps/editing-toolkit`. Both local build and CI check passed, despite the TypeScript errors.
- #50339 introduced an error in `packages/launch`.  Some of the CI checks failed because of the TypeScript errors
- #50340 introduced an error in `client/landing/gutenboarding`.  Some of the CI checks failed because of the TypeScript errors

Could be related to #49984

### PR DESCRIPTION
**Pull request by noahtallen**
#### Changes proposed in this Pull Request
Resolves #50334. We were not running a typescript build for ETK, so this adds one to catch major errors. Also solves some TS lint problems which didn't yet get reported in CI.

#### Testing instructions
test on your wpocm sandbox with `install-plugin.sh etk add/typecheck-etk`

- [x] unit tests should pass
- [x] static analysis + lint should pass
- [x] builds should pass
- [x] smoke test ETK on wpcom

### CODE REVIEW

**Comment by noahtallen** [comment]
Nice, got it working:

Screen Shot 2021-02-22 at 2 54 39 PM

Now just have to fix the TS issues :)

**Comment by noahtallen** [comment]
@sirreal @ciampo @scinos I'm not sure how to move forward here (I know very little about TS options). I added `tsc apps/editing-toolkit/tsconfig.json` to do type checking, and it's reporting a ton of errors. To me, this says that the problem is deeper than when we turned off tsc a week or two ago.

The first problem I get is: `apps/editing-toolkit/tsconfig.json:41:3 - error TS6310: Referenced project '/Users/noahtallen/source/wp-calypso/packages/format-currency' may not disable emit.`

Once I add `"noEmit": false` to the compiler options there, it gets further, but has a ton of further issues. Not really sure where to start here, I feel like there must be something not turned on or that I didn't reference properly for there to be this many problems.

```
~/source/wp-calypso(add/typecheck-etk) » yarn tsc --build apps/editing-toolkit/tsconfig.json
yarn run v1.22.10
$ NODE_OPTIONS='--max-old-space-size=4096' tsc --build apps/editing-toolkit/tsconfig.json
error TS5055: Cannot write file '/Users/noahtallen/source/wp-calypso/packages/format-currency/jest.config.js' because it would overwrite input file.

error TS5055: Cannot write file '/Users/noahtallen/source/wp-calypso/packages/format-currency/src/currencies.js' because it would overwrite input file.

error TS5055: Cannot write file '/Users/noahtallen/source/wp-calypso/packages/format-currency/src/index.js' because it would overwrite input file.

error TS5055: Cannot write file '/Users/noahtallen/source/wp-calypso/packages/format-currency/test/index.js' because it would overwrite input file.

apps/editing-toolkit/editing-toolkit-plugin/block-patterns/src/premium-block-patterns.tsx:41:10 - error TS2339: Property '__experimentalBlockPatterns' does not exist on type 'EditorSettings'.

41  const { __experimentalBlockPatterns } = useSelect( ( select ) =>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~

apps/editing-toolkit/editing-toolkit-plugin/block-patterns/src/premium-block-patterns.tsx:48:26 - error TS2314: Generic type 'Array<T>' requires 1 type argument(s).

48  	const updatedPatterns: Array = [];
    	                       ~~~~~

apps/editing-toolkit/editing-toolkit-plugin/block-patterns/src/premium-block-patterns.tsx:64:6 - error TS2322: Type 'Element' is not assignable to type 'string'.

64  				pattern.title = titleOverride;
    				~~~~~~~~~~~~~

apps/editing-toolkit/editing-toolkit-plugin/block-patterns/src/premium-block-patterns.tsx:79:5 - error TS2345: Argument of type '{ __experimentalBlockPatterns: any; }' is not assignable to parameter of type 'Partial<EditorSettings>'.
  Object literal may only specify known properties, and '__experimentalBlockPatterns' does not exist in type 'Partial<EditorSettings>'.

79  			__experimentalBlockPatterns: updatedPatterns,
    			~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

packages/shopping-cart/src/with-shopping-cart.tsx:4:8 - error TS1259: Module '"/Users/noahtallen/source/wp-calypso/node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

4 import React from 'react';
         ~~~~~

  node_modules/@types/react/index.d.ts:65:1
    65 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

packages/shopping-cart/src/shopping-cart-provider.tsx:4:8 - error TS1259: Module '"/Users/noahtallen/source/wp-calypso/node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

4 import React from 'react';
         ~~~~~

  node_modules/@types/react/index.d.ts:65:1
    65 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

packages/i18n-utils/dist/types/localize-url.d.ts:4:8 - error TS1259: Module '"/Users/noahtallen/source/wp-calypso/node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

4 import React from 'react';
         ~~~~~

  node_modules/@types/react/index.d.ts:65:1
    65 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

packages/i18n-utils/dist/types/locale-context.d.ts:4:8 - error TS1259: Module '"/Users/noahtallen/source/wp-calypso/node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

4 import React from 'react';
         ~~~~~

  node_modules/@types/react/index.d.ts:65:1
    65 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

packages/domain-picker/dist/types/domain-picker/index.d.ts:4:8 - error TS1259: Module '"/Users/noahtallen/source/wp-calypso/node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

4 import React, { FunctionComponent } from 'react';
         ~~~~~

  node_modules/@types/react/index.d.ts:65:1
    65 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

packages/composite-checkout/dist/types/components/button.d.ts:4:8 - error TS1259: Module '"/Users/noahtallen/source/wp-calypso/node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

4 import React from 'react';
         ~~~~~

  node_modules/@types/react/index.d.ts:65:1
    65 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

packages/composite-checkout/dist/types/components/checkout-error-boundary.d.ts:4:8 - error TS1259: Module '"/Users/noahtallen/source/wp-calypso/node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

4 import React, { ErrorInfo } from 'react';
         ~~~~~

  node_modules/@types/react/index.d.ts:65:1
    65 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

packages/composite-checkout/dist/types/components/checkout-steps.d.ts:4:8 - error TS1259: Module '"/Users/noahtallen/source/wp-calypso/node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

4 import React from 'react';
         ~~~~~

  node_modules/@types/react/index.d.ts:65:1
    65 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

packages/composite-checkout/dist/types/components/checkout-steps.d.ts:5:8 - error TS1192: Module '"/Users/noahtallen/source/wp-calypso/node_modules/@types/prop-types/index"' has no default export.

5 import PropTypes from 'prop-types';
         ~~~~~~~~~

packages/composite-checkout/dist/types/components/checkout-payment-methods.d.ts:4:8 - error TS1259: Module '"/Users/noahtallen/source/wp-calypso/node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

4 import React from 'react';
         ~~~~~

  node_modules/@types/react/index.d.ts:65:1
    65 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

packages/composite-checkout/dist/types/components/checkout-payment-methods.d.ts:5:8 - error TS1192: Module '"/Users/noahtallen/source/wp-calypso/node_modules/@types/prop-types/index"' has no default export.

5 import PropTypes from 'prop-types';
         ~~~~~~~~~

packages/composite-checkout/dist/types/components/order-review-line-items.d.ts:4:8 - error TS1259: Module '"/Users/noahtallen/source/wp-calypso/node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

4 import React from 'react';
         ~~~~~

  node_modules/@types/react/index.d.ts:65:1
    65 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

packages/composite-checkout/dist/types/components/order-review-line-items.d.ts:5:8 - error TS1192: Module '"/Users/noahtallen/source/wp-calypso/node_modules/@types/prop-types/index"' has no default export.

5 import PropTypes from 'prop-types';
         ~~~~~~~~~

packages/composite-checkout/dist/types/components/checkout-modal.d.ts:1:8 - error TS1192: Module '"/Users/noahtallen/source/wp-calypso/node_modules/@types/prop-types/index"' has no default export.

1 import PropTypes from 'prop-types';
         ~~~~~~~~~

packages/composite-checkout/dist/types/lib/line-items.d.ts:4:8 - error TS1259: Module '"/Users/noahtallen/source/wp-calypso/node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

4 import React from 'react';
         ~~~~~

  node_modules/@types/react/index.d.ts:65:1
    65 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

packages/composite-checkout/dist/types/components/shared-icons.d.ts:1:8 - error TS1192: Module '"/Users/noahtallen/source/wp-calypso/node_modules/@types/prop-types/index"' has no default export.

1 import PropTypes from 'prop-types';
         ~~~~~~~~~

packages/composite-checkout/dist/types/components/radio-button.d.ts:4:8 - error TS1259: Module '"/Users/noahtallen/source/wp-calypso/node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

4 import React from 'react';
         ~~~~~

  node_modules/@types/react/index.d.ts:65:1
    65 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

packages/composite-checkout/dist/types/components/radio-button.d.ts:5:8 - error TS1192: Module '"/Users/noahtallen/source/wp-calypso/node_modules/@types/prop-types/index"' has no default export.

5 import PropTypes from 'prop-types';
         ~~~~~~~~~

apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-focused-modal/index.tsx:1:1 - error TS1208: 'index.tsx' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.

1


apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/create-page/index.tsx:53:4 - error TS2322: Type 'unknown' is not assignable to type 'string | undefined'.
  Type 'unknown' is not assignable to type 'string'.

53  		target={ applyFilters( 'a8c.WpcomBlockEditorNavSidebar.linkTarget', undefined ) }
    		~~~~~~

  node_modules/@types/react/index.d.ts:1915:9
    1915         target?: string;
                 ~~~~~~
    The expected type comes from property 'target' which is declared here on type '(IntrinsicAttributes & AnchorProps & { icon?: any; iconSize?: number | undefined; }) | (IntrinsicAttributes & ButtonProps & { ...; })'

apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/create-page/index.tsx:56:4 - error TS2322: Type 'unknown' is not assignable to type 'string | undefined'.
  Type 'unknown' is not assignable to type 'string'.

56  		href={ url }
    		~~~~

  node_modules/@types/react/index.d.ts:1858:9
    1858         href?: string;
                 ~~~~
    The expected type comes from property 'href' which is declared here on type '(IntrinsicAttributes & AnchorProps & { icon?: any; iconSize?: number | undefined; }) | (IntrinsicAttributes & ButtonProps & { ...; })'

apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/create-page/index.tsx:60:4 - error TS2322: Type 'unknown' is not assignable to type 'ReactNode'.
  Type 'unknown' is not assignable to type 'ReactPortal'.

60  		{ label }
    		~~~~~~~~~

  node_modules/@types/react/index.d.ts:1351:9
    1351         children?: ReactNode;
                 ~~~~~~~~
    The expected type comes from property 'children' which is declared here on type '(IntrinsicAttributes & AnchorProps & { icon?: any; iconSize?: number | undefined; }) | (IntrinsicAttributes & ButtonProps & { ...; })'

apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-item/index.tsx:48:5 - error TS2769: No overload matches this call.
  Overload 2 of 2, '(props: PropsWithChildren<Props>, context?: any): ReactElement<any, any> | Component<Props, any, any> | null', gave the following error.
    Type 'unknown' is not assignable to type 'string | undefined'.
      Type 'unknown' is not assignable to type 'string'.
  Overload 2 of 2, '(props: PropsWithChildren<Props>, context?: any): ReactElement<any, any> | Component<Props, any, any> | null', gave the following error.
    Type 'unknown' is not assignable to type 'string | undefined'.
      Type 'unknown' is not assignable to type 'string'.

 48  			<Button
     			~~~~~~~
 49  				className={ buttonClasses }
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
 52  				target={ applyFilters( 'a8c.WpcomBlockEditorNavSidebar.linkTarget', undefined ) }
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 53  			>
    ~~~~~

  node_modules/@types/wordpress__components/button/index.d.ts:86:9
    86         href?: never;
               ~~~~
    The expected type comes from property 'href' which is declared here on type '(IntrinsicAttributes & ButtonProps & { children?: ReactNode; }) | (IntrinsicAttributes & AnchorProps & { ...; })'
  node_modules/@types/react/index.d.ts:1915:9
    1915         target?: string;
                 ~~~~~~
    The expected type comes from property 'target' which is declared here on type '(IntrinsicAttributes & ButtonProps & { children?: ReactNode; }) | (IntrinsicAttributes & AnchorProps & { ...; })'

apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx:208:6 - error TS2322: Type 'unknown' is not assignable to type 'string | undefined'.
  Type 'unknown' is not assignable to type 'string'.

208  				href={ closeUrl }
     				~~~~

  node_modules/@types/react/index.d.ts:1858:9
    1858         href?: string;
                 ~~~~
    The expected type comes from property 'href' which is declared here on type 'IntrinsicAttributes & Pick<(AnchorProps & { icon?: any; iconSize?: number | undefined; showTooltip?: boolean | undefined; }) | (ButtonProps & { ...; }), "typeof" | ... 374 more ... | "tooltipPosition"> & RefAttributes<...>'

apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx:213:6 - error TS2322: Type 'unknown' is not assignable to type 'ReactNode'.
  Type 'unknown' is not assignable to type 'ReactPortal'.

213  				{ closeLabel }
     				~~~~~~~~~~~~~~

  node_modules/@types/react/index.d.ts:1351:9
    1351         children?: ReactNode;
                 ~~~~~~~~
    The expected type comes from property 'children' which is declared here on type 'IntrinsicAttributes & Pick<(AnchorProps & { icon?: any; iconSize?: number | undefined; showTooltip?: boolean | undefined; }) | (ButtonProps & { ...; }), "typeof" | ... 374 more ... | "tooltipPosition"> & RefAttributes<...>'

apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx:216:6 - error TS2322: Type 'unknown' is not assignable to type 'ReactNode'.
  Type 'unknown' is not assignable to type 'ReactPortal'.

216  				{ listHeading }
     				~~~~~~~~~~~~~~~

  node_modules/@types/react/index.d.ts:1351:9
    1351         children?: ReactNode;
                 ~~~~~~~~
    The expected type comes from property 'children' which is declared here on type 'DetailedHTMLProps<HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>'

apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx:299:9 - error TS2322: Type 'Record<string, any>[]' is not assignable to type 'Post[]'.
  Type 'Record<string, any>' is missing the following properties from type 'Post': id, status, title

299  	const items: Post[] =
     	      ~~~~~


Found 35 errors.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by scinos** [comment]
I pushed a commit that fixes most of the type errors. The only one left is:

```
editing-toolkit-plugin/editor-site-launch/src/launch-steps/final-step/index.tsx:186:7 - error TS2741: Property 'css' is missing in type '{ children: (false | Element)[]; }' but required in type 'Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "typeof" | "id" | "dir" | "hidden" | ... 250 more ... | "css">'.

186                             <MainContentWrapper>
                                 ~~~~~~~~~~~~~~~~~~

editing-toolkit-plugin/editor-site-launch/src/launch-steps/final-step/index.tsx:189:10 - error TS2741: Property 'css' is missing in type '{ children: Element[]; className: string; }' but required in type 'Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "typeof" | "id" | "dir" | "hidden" | ... 250 more ... | "css">'.

189                                                     <CheckoutSummaryCard className="nux-launch__feature-list">
                                                         ~~~~~~~~~~~~~~~~~~~

editing-toolkit-plugin/editor-site-launch/src/launch-steps/final-step/index.tsx:222:8 - error TS2741: Property 'css' is missing in type '{ children: Element[]; }' but required in type 'Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "typeof" | "id" | "dir" | "hidden" | ... 250 more ... | "css">'.

222                                     <CheckoutStepAreaWrapper>
                                         ~~~~~~~~~~~~~~~~~~~~~~~

editing-toolkit-plugin/editor-site-launch/src/launch-steps/final-step/index.tsx:250:9 - error TS2741: Property 'css' is missing in type '{ children: Element; }' but required in type 'Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "typeof" | "id" | "dir" | "hidden" | ... 250 more ... | "css">'.

250                                             <SubmitButtonWrapper>
                                                 ~~~~~~~~~~~~~~~~~~~
```

Disclaimer: I'm not a TypeScript expert (by far!), I'd really appreciate if someone with more experience (@sirreal, @sarayourfriend, @jsnajdr ) can take a look and validate what I did.

File: apps/editing-toolkit/editing-toolkit-plugin/block-patterns/src/premium-block-patterns.tsx [hunk 1]
```diff
@@ -40,12 +45,16 @@ export const PatternTitleContainer: React.FunctionComponent< PatternTitleProps >
 export const PremiumBlockPatterns: React.FunctionComponent = () => {
 	const { __experimentalBlockPatterns } = useSelect( ( select ) =>
 		select( 'core/block-editor' ).getSettings()
+	) as ExperimentalEditorSettings;
+	const {
```
Comment (scinos) [inline apps/editing-toolkit/editing-toolkit-plugin/block-patterns/src/premium-block-patterns.tsx:49]: I have to make this change so we can use `__experimentalBlockPatterns`. I don't know if there is a better approach

File: apps/editing-toolkit/editing-toolkit-plugin/block-patterns/src/premium-block-patterns.tsx [hunk 2]
```diff
@@ -1,10 +1,11 @@
 /**
  * External dependencies
  */
-import * as React from 'react';
+import React from 'react';
```
Comment (scinos) [inline apps/editing-toolkit/editing-toolkit-plugin/block-patterns/src/premium-block-patterns.tsx]: `import *` is not needed anymore with `esModuleInterop` enabled (https://www.typescriptlang.org/tsconfig#esModuleInterop)

File: apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/attach-focused-launch.tsx [hunk 3]
```diff
@@ -1,7 +1,7 @@
 /**
  * External dependencies
  */
-import * as React from 'react';
+import React from 'react';
```
Comment (scinos) [inline apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/attach-focused-launch.tsx:4]: `react` has to be in scope, otherwise TS complains when using JSX.

I assume this was done to avoid shipping React and use whatever is in the page. That should be handled by webpack

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/create-page/index.tsx [hunk 4]
```diff
@@ -35,22 +36,24 @@ export default function CreatePage( { postType }: Props ) {
 		'a8c.WpcomBlockEditorNavSidebar.createPostLabel',
 		defaultLabel,
 		postType.slug
-	);
+	) as string;
```
Comment (scinos) [inline apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/create-page/index.tsx:39]: This forced type asserting feels weird. Is there a better way? Maybe a version of `applyFilter` with generics?

File: apps/editing-toolkit/tsconfig.json [hunk 5]
```diff
@@ -22,23 +23,20 @@
...
-		"jsx": "preserve"
+		"typeRoots": [ "./typings", "./node_modules/@types", "../../node_modules/@types" ]
 	},
 	"exclude": [ "node_modules" ],
 	"references": [
 		{ "path": "../../packages/data-stores" },
 		{ "path": "../../packages/calypso-analytics" },
 		{ "path": "../../packages/composite-checkout" },
 		{ "path": "../../packages/domain-picker" },
-		{ "path": "../../packages/format-currency" },
```
Comment (scinos) [inline apps/editing-toolkit/tsconfig.json:41]: Deleted because `format-currency` is not a real TS project.

File: apps/editing-toolkit/editing-toolkit-plugin/block-patterns/src/premium-block-patterns.tsx [hunk 6]
```diff
@@ -16,13 +17,17 @@ interface PatternTitleProps {
...
+}
+
 interface ExperimentalBlockPattern {
 	categories: string[];
 	content: string;
 	description: string;
 	isPremium: boolean;
 	name: string;
-	title: string;
+	title: string | JSX.Element;
```
Comment (ciampo) [inline apps/editing-toolkit/editing-toolkit-plugin/block-patterns/src/premium-block-patterns.tsx]: What about

```suggestion
	title: React.ReactNode;
```

File: apps/editing-toolkit/editing-toolkit-plugin/block-patterns/src/premium-block-patterns.tsx (hunk 2 above)
Comment (ciampo) [reply apps/editing-toolkit/editing-toolkit-plugin/block-patterns/src/premium-block-patterns.tsx]: Should we change all instances of `import * as React from 'react';` to  `import React from 'react';` in all files?

Comment (scinos) [reply apps/editing-toolkit/editing-toolkit-plugin/block-patterns/src/premium-block-patterns.tsx]: They should be changed in all ETK. Other apps still use them, I haven't validated their `tsconfig.json` yet. Probably for a future PR.

Comment (ciampo) [reply apps/editing-toolkit/editing-toolkit-plugin/block-patterns/src/premium-block-patterns.tsx]: Got it — thank you for the explanation!

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/create-page/index.tsx (hunk 4 above)
Comment (ciampo) [reply apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/create-page/index.tsx:39]: > Maybe a version of `applyFilter` with generics?

That's probably the better version — should we start patching it directly in ETK and open a parallel PR in core to improve the typings?

Comment (sirreal) [reply apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/create-page/index.tsx:39]: That would be better, but is difficult to implement the types for (in a sound way). We just recently got the [hooks package](https://github.com/WordPress/gutenberg/blob/master/packages/hooks/src/index.js) typed and it could likely be improved.

**Comment by sirreal** [comment]
I pushed type fixes. It seems like `@emotion/core` types weren't being resolved correctly which is what led to https://github.com/Automattic/wp-calypso/pull/50357#issuecomment-783937824.

I had to add jest types as well. I don't really like doing that because `describe` et.al become globals. We could add another project for test files that references the actual source.

There are still a couple errors, I'll hand it back off.

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx [hunk 7]
```diff
@@ -33,10 +34,13 @@ const Button = forwardRef(
 		{
 			children,
 			...rest
-		}: OriginalButton.Props & { icon?: any; iconSize?: number; showTooltip?: boolean },
+		}: OriginalButton.Props & { icon?: unknown; iconSize?: number; showTooltip?: boolean },
 		ref
 	) => (
-		<OriginalButton ref={ ref as any } { ...rest }>
+		<OriginalButton
+			ref={ ref as string | ( ( instance: HTMLElement | null ) => void ) }
```
Comment (noahtallen) [inline apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx:41]: `ref` types were weird here; basically just copy pasted from the type error.

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx [hunk 8]
```diff
@@ -45,7 +49,10 @@ const Button = forwardRef(
 function WpcomBlockEditorNavSidebar() {
 	const { toggleSidebar, setSidebarClosing } = useDispatch( STORE_KEY );
 	const [ isOpen, isClosing, postType, selectedItemId, siteTitle ] = useSelect( ( select ) => {
-		const { getPostType, getSite } = select( 'core' ) as any;
+		const { getPostType, getSite } = ( select( 'core' ) as unknown ) as {
+			getPostType: ( postType: string ) => null | { slug: string };
+			getSite: () => null | { title: string };
```
Comment (noahtallen) [inline apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx:54]: Retyping the result to what we use here. `select( 'core' )` wasn't giving any types.

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx (hunk 7 above)
Comment (sarayourfriend) [reply apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx:41]: Should it be `as React.Ref<HTMLElement>`?

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx [hunk 9]
```diff
@@ -72,10 +79,10 @@ function WpcomBlockEditorNavSidebar() {
 	}, [ isOpen, prevIsOpen, setSidebarClosing ] );
 
 	// When the sidebar closes the previously focused element should be re-focused
-	const activeElementOnMount = useRef< HTMLElement | null >( null );
-	const dismissButtonMount = ( el: HTMLDivElement | null ) => {
+	const activeElementOnMount = useRef< HTMLButtonElement | null >( null );
+	const dismissButtonMount = ( el: HTMLButtonElement | null ) => {
```
Comment (noahtallen) [inline apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx:83]: The `Button` component uses `Button` by default as far as I can tell, not div

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx [hunk 10]
```diff
@@ -287,7 +305,7 @@ function useNavItems(): Record< string, Post[] > {
 		const statuses = select( 'core' ).getEntityRecords( 'root', 'status' );
 
 		if ( ! statuses ) {
-			return [];
+			return { current: [], drafts: [], recent: [] };
```
Comment (noahtallen) [inline apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx:308]: The original code was never checking for an empty array anyways -- it always assumed that these properties existed. This is a little safer then, plus fixes the type issues here.

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/toggle-sidebar-button/index.tsx [hunk 11]
```diff
@@ -17,11 +18,11 @@ import './style.scss';
 const Button = ( {
 	children,
 	...rest
-}: OriginalButton.Props & { icon?: any; iconSize?: number; showTooltip?: boolean } ) => (
+}: OriginalButton.Props & { icon?: unknown; iconSize?: number; showTooltip?: boolean } ) => (
 	<OriginalButton { ...rest }>{ children }</OriginalButton>
 );
 
-export default function ToggleSidebarButton() {
+export default function ToggleSidebarButton(): JSX.Element {
```
Comment (noahtallen) [inline apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/toggle-sidebar-button/index.tsx:25]: Are we using `JSX.Element` for component return types, or is there something better?

**Comment by noahtallen** [comment]
These remaining type issues were thrown by the lint check (e.g. "no any", "no return type", etc) and should be fixed now 🤞. There are probably more like them in the ETK plugin, but they only show up when a file is modified, so they can be fixed as follow ups.

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/toggle-sidebar-button/index.tsx (hunk 11 above)
Comment (sarayourfriend) [reply apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/toggle-sidebar-button/index.tsx:25]: JSX.Element is perfect, the definition of a FunctionComponent is:

```
(props: PropsWithChildren<P>, context?: any): ReactElement<any, any> | null;
```

And in `JSX`: 

```
interface Element extends React.ReactElement<any, any> { }
```

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx (hunk 7 above)
Comment (noahtallen) [reply apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx:41]: That'd be nice, but it gives an error:

```
No overload matches this call.
  Overload 1 of 2, '(props: Props, context?: any): ReactElement<any, any> | Component<Props, any, any> | null', gave the following error.
    Type 'Ref<HTMLElement>' is not assignable to type 'string | ((instance: HTMLAnchorElement | null) => void) | RefObject<HTMLAnchorElement> | ((instance: HTMLButtonElement | null) => void) | RefObject<...> | null | undefined'.
      Type 'RefObject<HTMLElement>' is not assignable to type 'string | ((instance: HTMLAnchorElement | null) => void) | RefObject<HTMLAnchorElement> | ((instance: HTMLButtonElement | null) => void) | RefObject<...> | null | undefined'.
        Type 'RefObject<HTMLElement>' is not assignable to type 'RefObject<HTMLAnchorElement>'.
          Type 'HTMLElement' is missing the following properties from type 'HTMLAnchorElement': charset, coords, download, hreflang, and 21 more.
  Overload 2 of 2, '(props: PropsWithChildren<Props>, context?: any): ReactElement<any, any> | Component<Props, any, any> | null', gave the following error.
    Type 'Ref<HTMLElement>' is not assignable to type 'string | ((instance: HTMLAnchorElement | null) => void) | RefObject<HTMLAnchorElement> | ((instance: HTMLButtonElement | null) => void) | RefObject<...> | null | undefined'.
      Type 'RefObject<HTMLElement>' is not assignable to type 'string | ((instance: HTMLAnchorElement | null) => void) | RefObject<HTMLAnchorElement> | ((instance: HTMLButtonElement | null) => void) | RefObject<...> | null | undefined'.
        Type 'RefObject<HTMLElement>' is not assignable to type 'RefObject<HTMLAnchorElement>'.
```

I think the types on `Button` from @wordpress/components must be missing something 🤔

Comment (sarayourfriend) [reply apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx:41]: Ah, it's because `Button` can render either an `HTMLButtonElement` or a `HTMLAnchorElement`.

`HTMLElement` isn't a super type of `HTMLButtonElement` or `HTMLAnchorElement` so neither can fit into that box. You'll want to change it to `Ref<HTMLAnchorElement | HTMLButtonElement>` I think (though try just `HTMLAnchorElement` first?)

Comment (noahtallen) [reply apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx:41]: It still doesn't work with button, anchor, or button/anchor together :/

```
No overload matches this call.
  Overload 1 of 2, '(props: Props, context?: any): ReactElement<any, any> | Component<Props, any, any> | null', gave the following error.
    Type '{ children: ReactNode; isDefault?: boolean | undefined; isPrimary?: boolean | undefined; isSecondary?: boolean | undefined; isTertiary?: boolean | undefined; isDestructive?: boolean | undefined; ... 371 more ...; key?: string | ... 2 more ... | undefined; } | { ...; }' is not assignable to type '(IntrinsicAttributes & AnchorProps) | (IntrinsicAttributes & ButtonProps)'.
      Type '{ children: ReactNode; href?: undefined; isDefault?: boolean | undefined; isPrimary?: boolean | undefined; isSecondary?: boolean | undefined; isTertiary?: boolean | undefined; ... 371 more ...; key?: string | ... 2 more ... | undefined; }' is not assignable to type '(IntrinsicAttributes & AnchorProps) | (IntrinsicAttributes & ButtonProps)'.
        Type '{ children: ReactNode; href?: undefined; isDefault?: boolean | undefined; isPrimary?: boolean | undefined; isSecondary?: boolean | undefined; isTertiary?: boolean | undefined; ... 371 more ...; key?: string | ... 2 more ... | undefined; }' is not assignable to type 'ButtonProps'.
          Types of property 'ref' are incompatible.
            Type 'string | ((instance: HTMLAnchorElement | null) => void) | RefObject<HTMLAnchorElement> | ((instance: HTMLButtonElement | null) => void) | RefObject<...> | null' is not assignable to type 'string | ((instance: HTMLButtonElement | null) => void) | RefObject<HTMLButtonElement> | null | undefined'.
              Type '(instance: HTMLAnchorElement | null) => void' is not assignable to type 'string | ((instance: HTMLButtonElement | null) => void) | RefObject<HTMLButtonElement> | null | undefined'.
                Type '(instance: HTMLAnchorElement | null) => void' is not assignable to type '(instance: HTMLButtonElement | null) => void'.
                  Types of parameters 'instance' and 'instance' are incompatible.
                    Type 'HTMLButtonElement | null' is not assignable to type 'HTMLAnchorElement | null'.
                      Type 'HTMLButtonElement' is missing the following properties from type 'HTMLAnchorElement': charset, coords, download, hreflang, and 19 more.
  Overload 2 of 2, '(props: PropsWithChildren<Props>, context?: any): ReactElement<any, any> | Component<Props, any, any> | null', gave the following error.
    Type '{ children: ReactNode; isDefault?: boolean | undefined; isPrimary?: boolean | undefined; isSecondary?: boolean | undefined; isTertiary?: boolean | undefined; isDestructive?: boolean | undefined; ... 371 more ...; key?: string | ... 2 more ... | undefined; } | { ...; }' is not assignable to type '(IntrinsicAttributes & AnchorProps & { children?: ReactNode; }) | (IntrinsicAttributes & ButtonProps & { ...; })'.
      Type '{ children: ReactNode; href?: undefined; isDefault?: boolean | undefined; isPrimary?: boolean | undefined; isSecondary?: boolean | undefined; isTertiary?: boolean | undefined; ... 371 more ...; key?: string | ... 2 more ... | undefined; }' is not assignable to type '(IntrinsicAttributes & AnchorProps & { children?: ReactNode; }) | (IntrinsicAttributes & ButtonProps & { ...; })'.
        Type '{ children: ReactNode; href?: undefined; isDefault?: boolean | undefined; isPrimary?: boolean | undefined; isSecondary?: boolean | undefined; isTertiary?: boolean | undefined; ... 371 more ...; key?: string | ... 2 more ... | undefined; }' is not assignable to type 'ButtonProps'.
          Types of property 'ref' are incompatible.
            Type 'string | ((instance: HTMLAnchorElement | null) => void) | RefObject<HTMLAnchorElement> | ((instance: HTMLButtonElement | null) => void) | RefObject<...> | null' is not assignable to type 'string | ((instance: HTMLButtonElement | null) => void) | RefObject<HTMLButtonElement> | null | undefined'.
              Type '(instance: HTMLAnchorElement | null) => void' is not assignable to type 'string | ((instance: HTMLButtonElement | null) => void) | RefObject<HTMLButtonElement> | null | undefined'.
                Type '(instance: HTMLAnchorElement | null) => void' is not assignable to type '(instance: HTMLButtonElement | null) => void'.
```

Comment (noahtallen) [reply apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx:41]: I tried a few other things when I was working through it, and so far the only thing that clears it up is the code I committed 🙃

Comment (sarayourfriend) [reply apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx:41]: That's really unfortunate...

For reference, here's the DefinitelyTyped definition for `Button`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/wordpress__components/button/index.d.ts

I wonder what needs to be fixed there to make this work appropriately? The ref type doesn't seem to be documented at all. I wonder if it should be `ForwardRefExoticComponent` with the appropriate ref attributes put in instead of just `ComponentType`? 😓 What a mess 😕

**Comment by noahtallen** [comment]
Yep, all builds and lints passing now. Also tested the plugin build and it's working well 👍

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx (hunk 7 above)
Comment (noahtallen) [reply apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx:41]: oof. I wonder if this is something we could add more generally (e.g. it seems like most components should accept ref/classname)

Comment (sarayourfriend) [reply apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx:41]: It'll be easier when we move strictly to JSDoc/TypeScript for components. Not sure what to do about the DefinitelyTyped declarations though.

You're right that most components should forward refs, unfortunately many do not so it's still a work in progress. G2 components all forward refs though, so that's good!

**Comment by ciampo** [comment]
Rebased on top of latest `trunk`:

- [x] ETK build and lints still passing
- [x] Smoke tested ETK

Should we aim at merging this PR soon?

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx (hunk 8 above)
Comment (scinos) [reply apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx:54]: out of curiosity, what is `as unknown` doing here?

Comment (ciampo) [reply apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx:54]: I believe that's because that intermediary type assertion to `unknown` is necessary to assign the correct type. Without it, you'd get a TypeScript error saying

```
Conversion of type 'typeof import("/Users/marcociampini/Code/wp-calypso/node_modules/@types/wordpress__core-data/selectors")' to type '{ getPostType: (postType: string) => { slug: string; } | null; getSite: () => { title: string; } | null; }' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
```

Comment (scinos) [reply apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx:54]: TIL, thanks!

File: apps/editing-toolkit/editing-toolkit-plugin/block-patterns/src/premium-block-patterns.tsx [hunk 12]
```diff
@@ -16,13 +17,17 @@ interface PatternTitleProps {
...
+}
+
 interface ExperimentalBlockPattern {
 	categories: string[];
 	content: string;
 	description: string;
 	isPremium: boolean;
 	name: string;
-	title: string;
+	title: React.ReactNode;
```
Comment (sarayourfriend) [inline apps/editing-toolkit/editing-toolkit-plugin/block-patterns/src/premium-block-patterns.tsx]: nit: Use type import `import type { ReactNode } from 'react'` rather than accessing the type off the React object.

**Review by sarayourfriend — APPROVED** [review]
LGTM!

**Comment by ciampo** [comment]
@noahtallen maybe I could tag along later today if you're going to merge this PR? It could be a way for me to familiarise with the new ETK deployment process

File: apps/editing-toolkit/editing-toolkit-plugin/block-patterns/src/premium-block-patterns.tsx (hunk 12 above)
Comment (noahtallen) [reply apps/editing-toolkit/editing-toolkit-plugin/block-patterns/src/premium-block-patterns.tsx]: Done! Does `import React, { ReactNode } from 'react';` also work the same way? (It doesn't show errors for me locally)

**Comment by ciampo** [comment]
Rebased on top of latest `trunk`:

- [x] ETK build and lints are passing
- [x] Smoke tested ETK

Some e2e tests are failing, but they look unrelated to the changes in ETK. 

Since this PR has been approved and there's no comments pending, I'm going to merge it and release a new version of ETK
