### PR TITLE
Playwright: use a combination of `click` and `waitForSelector` instead of `check` when removing a user.

### LINKED ISSUE #57437: Playwright: Deleting invited user permissions is flaky
### Details

See Pre-release build no. 648 - checking the delete radio when removing the recently invited user failed and is flaky. 

```
page.check: Clicking the checkbox did not change its state
=========================== logs ===========================
waiting for selector "input[value="delete"]"
  selector resolved to visible <input type="radio" value="delete" name="radioOption" c…/>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (448.48,484)
  element does receive pointer events
  performing click action
  click action done
  waiting for scheduled navigations to finish
  navigations have finished
============================================================
```

### Checklist

_No response_

### Related

_No response_

### PR DESCRIPTION
**Pull request by worldomonation**
#### Changes proposed in this Pull Request

This PR modifies the interaction for `PeoplePage.deleteUser`.

Key changes:
- instead of single `page.check`, use `page.click` followed by `page.waitForSelector`.

Details:
Slack: p1635441879120200-slack-CQD1HH4MA

Rarely, Playwright fails to verify that `page.check` performed its actions when attempting to remove a user from the site. The radio button in question present on `/people/edit` is a React component and so the 'checked' behavior is not coming from a native form.

#### Testing instructions

- [x] pre-release test

Stress test is skipped due to the sheer load it would cause on the signup page, in addition to locking up Pre-Release task for 20 minutes (as execution is limited to 1 instance across all branches).

Fixes #57437.

### CODE REVIEW

File: packages/calypso-e2e/src/lib/pages/people-page.ts [hunk 1]
```diff
@@ -95,7 +95,13 @@ export class PeoplePage {
 			elementHandle
 		);
 
-		await this.page.check( selectors.deletedUserContentAction( 'delete' ) );
+		// Native `page.check` sometimes fails here. Instead, click on the radio and wait for the
+		// Delete user button to become enabled.
+		await this.page.click( selectors.deletedUserContentAction( 'delete' ) );
+		await this.page.waitForSelector( `${ selectors.deleteUserButton }[disabled=""]`, {
+			state: 'detached',
+		} );
```
Comment (dpasque) [inline packages/calypso-e2e/src/lib/pages/people-page.ts]: I don't think we should need this line right? The click action below will wait until the `deleteUserButton` is enabled by default.

I had kind of been imagining a `waitForSelector` for the checked state of the radio button, which would wait until the state is updated before proceeed.

You should be able to do that with the `:checked` psuedo-selector...
```typescript
await this.page.waitForSelector( `${ selectors.deletedUserContentAction( 'delete' ) }:checked` );
```

**Review by dpasque — COMMENTED** [review]
@worldomonation Had a suggestion about waiting for the actual checked state on the radio button - let me know what you think!

File: packages/calypso-e2e/src/lib/pages/people-page.ts (hunk 1 above)
Comment (worldomonation) [reply packages/calypso-e2e/src/lib/pages/people-page.ts]: My intention was to wait until the disabled marker for the `deleteUserButton` was removed, which would signify that a valid selection was made in the radio.

I suppose something similar can be done by either just waiting for the button to be enabled, or using that pseudo-CSS selector. I can try either or.

Comment (worldomonation) [reply packages/calypso-e2e/src/lib/pages/people-page.ts]: Pushed changes in 601ede455a16dfa891c3c05b0a11d857ae037edd

**Comment by worldomonation** [comment]
E2E failed due to a muted test. Retriggering.

**Review by dpasque — APPROVED** [review]
🚀
