### PR TITLE
Eligibility Warnings: Fix a couple of conditional strings in the "hold list"

### LINKED ISSUE #38638: Hosting: Site Eligibility Check Displaying Empty/Blank Error Message for SSL Blocker
When a site attempts to enable hosting configuration features, install a theme, or or install a plugin and their domain doesn't have an SSL certificate, the process is blocked. However, no error or warning is displayed.

image

Additionally, we may want to add details to the message for contacting support as, in some special cases, it can take days before a mapped domain gets an SSL cert.

Internal discussion: p9F6qB-4Bg-p2

#### Steps to reproduce
1. Add a domain/subdomain to a test Business site without adding the proper DNS records so the SSL provisioning times out/schedules for a later time
2. Add the proper DNS records and do not provide an SSL cert.
3. Make the new domain your primary
4. Attempt to install a plugin, theme, or activate hosting configuration features.
5. You’ll be presented with the blank/empty site eligibility check message.

To resolve this, the user will need to wait for an SSL cert to provision. In some special cases, a Happiness Engineer may need to do this for them as it can take hours or days.

#### What I expected
For the proper message to display. 

Other than getting that to display, we may want to add a notice to tell the user to contact us. If they’ve been sitting on a domain mapping that wasn’t configured for a while, it can take days before the system automatically provisions a cert.

The current message set to display appears to be.
> ‘Certificate installation in progress. Hold tight! We are setting up a digital certificate to allow secure browsing on your site using “HTTPS”.’
> 
> ‘Hold tight! We are setting up a digital certificate to allow secure browsing on your site, using “HTTPS”. Please try again in a few minutes.`

That's based on https://github.com/Automattic/wp-calypso/blob/2a3c6652a4c1bf0e23e8294643d7ca1f0e4a8797/client/blocks/eligibility-warnings/hold-list.tsx#L141

#### What happened instead

No message is displayed.

#### Screenshot / Video

image

#### Context / Source
Discussed internally: p9F6qB-4Bg-p2

#dogfooding #user-report

### PR DESCRIPTION
**Pull request by jblz**
There were a couple of places where we were attempting to render the return value of `hasLocalizedText` instead of `translate`, so the messages were not being displayed.

|Before|After|
|---|---|
|screen_shot_2020-01-02_at_2 28 10_pm|Screen Shot 2020-01-03 at 3 22 33 PM|

It's also worth noting that this section is in the process of a redesign, so this is not its final form.  Also, these strings should be fully localized by now, so I'll follow up with a PR to pull out the conditionals, but wanted to get this in to fix the broken notice.

### Changes proposed in this Pull Request

* Return the value of `translate` for `SITE_GRAYLISTED`
* Return the value of `translate` for `NO_SSL_CERTIFICATE`

#### Testing instructions

* Apply this patch to force the blocking hold in the client: https://gist.github.com/jblz/1b1179caf735b3cbef283460ed213372
* Browse to `/plugins/upload/` for a Business Plan site
* You should see appropriate text in the notice

Fixes #38638

### CODE REVIEW

File: client/blocks/eligibility-warnings/hold-list.tsx [hunk 1]
```diff
@@ -131,7 +131,7 @@ function getBlockingMessages( translate: LocalizeProps[ 'translate' ] ) {
 			message: hasLocalizedText(
 				"There's an ongoing site dispute. Contact us to review your site's standing and resolve the dispute."
```
Comment (a8ci18n) [inline client/blocks/eligibility-warnings/hold-list.tsx]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **19** times:
`translate( 'Contact us to review your site's standing and resolve the dispute.' )` *ES Score: 7*

File: client/blocks/eligibility-warnings/hold-list.tsx [hunk 2]
```diff
@@ -142,7 +142,7 @@ function getBlockingMessages( translate: LocalizeProps[ 'translate' ] ) {
 			message: hasLocalizedText(
 				'Certificate installation in progress. Hold tight! We are setting up a digital certificate to allow secure browsing on your site using "HTTPS".'
```
Comment (a8ci18n) [inline client/blocks/eligibility-warnings/hold-list.tsx]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **19** times:
`translate( 'Hold tight! We are setting up a digital certificate to allow secure browsing on your site, using "HTTPS". Please try again in a few minutes.' )` *ES Score: 7*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/fix/atomic-ssl-block-notice)

**Comment by jblz** [comment]
Follow up to pull out the old strings entirely in #38645
