### PR TITLE
Reader: Fix up links to jetpack galleries

### LINKED ISSUE #12558: Fullpost View: Galleries: Link to Carousel?
When a fullpost includes a gallery, currently, we link each image to its permalink page.

For example, this post includes a gallery: https://wordpress.com/read/feeds/35242705/posts/1392083041

And clicking an image in the gallery goes to the image's permalink page, like this: https://perfectlyirregular.wordpress.com/2017/03/25/my-hk-family/img_1376/

Could we instead link to the lightbox Carousel view, like the original post does? Like this:
https://perfectlyirregular.wordpress.com/2017/03/25/my-hk-family/#jp-carousel-3060

(If we do, we should probably open it in a new tab, too.)

cc @blowery @bluefuton

### PR DESCRIPTION
**Pull request by blowery**
Turn them into links to the carousel instead of leaving them plain.

Fixes #12558

### CODE REVIEW

**Comment by fraying** [comment]
Works! Could we also target a new tab with those links?

**Comment by blowery** [comment]
> Works! Could we also target a new tab with those links?

Should _all_ links go to a new tab?

**Comment by fraying** [comment]
Just the ones we insert (that go someplace other than Reader).

**Comment by blowery** [comment]
> Just the ones we insert (that go someplace other than Reader).

We're modifying an existing link here, not inserting a new one. As a user, how do I know which links in content go to a new tab and which ones do not?

**Comment by blowery** [comment]
branch updated to always pop new windows / tabs for carousels.

**Comment by fraying** [comment]
👍

**Comment by blowery** [comment]
@jom sorry, didn't mean to tag you on this one :D

**Comment by samouri** [comment]
Thanks for doing a great job of splitting up your commits so they are easy to follow! 👍

File: client/lib/post-normalizer/rule-content-link-jetpack-carousels.js [hunk 1]
```diff
@@ -0,0 +1,36 @@
+/**
+ * External Dependencies
+ */
+import { forEach, get } from 'lodash';
+
+export default function linkJetpackCarousels( post, dom ) {
+	const galleries = dom.querySelectorAll( '.tiled-gallery' );
+
+	forEach( galleries, gallery => {
+		let extra = get( gallery, [ 'dataset', 'carouselExtra' ], false );
```
Comment (samouri) [inline client/lib/post-normalizer/rule-content-link-jetpack-carousels.js]: so a gallery carousel can have either a property: `dataset.courselExtra` or a property `data-carousel-extra`?
What creates that property / when does one exist vs. the other?

File: client/lib/post-normalizer/rule-content-link-jetpack-carousels.js [hunk 2]
```diff
@@ -0,0 +1,36 @@
+/**
+ * External Dependencies
+ */
+import { forEach, get } from 'lodash';
+
+export default function linkJetpackCarousels( post, dom ) {
```
Comment (samouri) [inline client/lib/post-normalizer/rule-content-link-jetpack-carousels.js]: Can we add a comment right above the rule describing what it does?

Something like:
```
The linkJetpackCarousels rule modifies all of the galleries in the content that are from jetpack sites
to link you to their host websites carousels instead of the permalink for that specific image.

For example,
Before: https://perfectlyirregular.wordpress.com/2017/03/25/my-hk-family/img_1376/
After: https://perfectlyirregular.wordpress.com/2017/03/25/my-hk-family/#jp-carousel-3060

```

File: client/lib/post-normalizer/rule-content-link-jetpack-carousels.js [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+		let permalink;
+		try {
+			permalink = JSON.parse( extra ).permalink;
+		} catch ( e ) {
+			return post;
+		}
+		const links = gallery.querySelectorAll( '.tiled-gallery-item > a' );
+		forEach( links, link => {
+			const img = link.querySelector( 'img' );
+			if ( img ) {
```
Comment (samouri) [inline client/lib/post-normalizer/rule-content-link-jetpack-carousels.js]: Can we drop the if statement with something like:

```jsx
const img = link.querySelector.....
const attachmentId = img && img.getAttr....
```

File: client/lib/post-normalizer/rule-content-link-jetpack-carousels.js (hunk 1 above)
Comment (blowery) [inline client/lib/post-normalizer/rule-content-link-jetpack-carousels.js]: This is mostly for our test framework. jsdom doesn't support data attributes in the same way that browsers do.

Comment (samouri) [inline client/lib/post-normalizer/rule-content-link-jetpack-carousels.js]: Darn: https://github.com/tmpvar/jsdom/issues/961

File: client/lib/post-normalizer/rule-content-link-jetpack-carousels.js (hunk 2 above)
Comment (samouri) [inline client/lib/post-normalizer/rule-content-link-jetpack-carousels.js]: Also, for newbs like me, can we include that all galleries (including wpcom) are considered jetpack galleries?

**Comment by samouri** [comment]
Functionality LGTM. Super small comments on the code then 🚢 !
