### PR TITLE
Mailchimp Block: UI Review Updates

### LINKED ISSUE #30667: Mailchimp: Visual review
Here's a review of UI elements that need fixing:

__Editor UI:__

- [ ] I don't see the need for us to have a heading as part of the block. If for some reason we need one, we should have the same options as the Heading block.
- [ ] Can the email input be a `type="email"` rather than `type="text"`
- [ ] Could we have a button like the Button block and remove the label option from the sidebar?
- [ ] The text underneath, could it just be a Paragraph block (within the block) with some italic applied to it? At the moment, the italic setting doesn't work since it's already in italic. I'm not quite sure why this is a `figcaption` either, from an HTML point of view this makes no sense and it's invalid.
- [ ] Some places it's written "MailChimp", and some other "Mailchimp". The correct version is "Mailchimp" now.

__Front-end:__

- [ ] The forced styles on the email input are not needed `.wp-block-jetpack-mailchimp .wp-block-jetpack-mailchimp-email` themes style their inputs and forcing this is not recommended.
- [ ] Same with `.wp-block-jetpack-mailchimp .wp-block-jetpack-mailchimp-form-error` I would suggest we add a generic class `error` to the input. Again, most themes will style this.
- [ ] Displaying all 3 messages in the content with a `display: none` feels strange. Can we just add the message with some JS?
- [ ] Processing, have a more subtle background: `rgba(0, 0, 0, 0.025)`
- [ ] Success: Let's use an accessible green #1d7819 
- [ ] Same for error: #eb0001 
- [ ] `.wp-block-jetpack-mailchimp .wp-block-jetpack-mailchimp-notification` let's switch to ems: `margin-bottom: 1.5em` and `padding: 0.75em`.
- [ ] Remove the `text-center` from the messages. If the user adds a bunch of text to these messages, it wouldn't look great centred.

### PR DESCRIPTION
**Pull request by jeffersonrabb**
#### Changes proposed in this Pull Request

This PR contains a series of UI and design improvements flagged by @thomasguillot and @scruffian in https://github.com/Automattic/wp-calypso/issues/30667. Since the block uses Server-Side Rendering, many of these fixes involve similar changes in the Jetpack repo. Here's the list of changes. Quoted text is from the issue. 

__Editor UI:__

> I don't see the need for us to have a heading as part of the block. If for some reason we need one, we should have the same options as the Heading block.

Done in https://github.com/Automattic/wp-calypso/pull/30685/commits/141d9f2b32088fe3b4d10b2b935aebbc7c95d02b and https://github.com/Automattic/jetpack/pull/11317/commits/9431ca9cb4d4f272d832dd2f435b91b83c55d3dc

> Can the email input be a `type="email"` rather than `type="text"`

Done in https://github.com/Automattic/wp-calypso/pull/30685/commits/e363a8cf7d9ee3f1674399f564037e92862e9f1c and https://github.com/Automattic/jetpack/pull/11317/commits/d921ac35dc4fc095bfac66b3a8652cef82c05485

> Could we have a button like the Button block and remove the label option from the sidebar?

Done in https://github.com/Automattic/wp-calypso/pull/30685/commits/da91702ae46a949886d37500b48f0e4d01b94c25. 

Notes/Questions:

- I applied a class from the core Button block ( `wp-block-button__link` ) to get some of the style without duplicating a bunch of CSS. This might be a questionable practice since future changes Core Button could affect Mailchimp in unexpected ways. Curious if there are opinions on the best way to handle this situation.
- Core Button's background color defaults to `#0073aa`, which is not one of the Muriel blues. It seemed preferable to replicate the Core style rather than stick to Muriel colors and create dissonance, but I'm happy to go either way on this.
- On the Frontend, the button has only these classes `components-button is-button is-primary`, which should leave the button style to the theme. 

> The text underneath, could it just be a Paragraph block (within the block) with some italic applied to it? At the moment, the italic setting doesn't work since it's already in italic. I'm not quite sure why this is a `figcaption` either, from an HTML point of view this makes no sense and it's invalid.

Done in https://github.com/Automattic/wp-calypso/pull/30685/commits/7f61c7072311edd8d53d5f61a6aeaf059ae8ad01 and https://github.com/Automattic/jetpack/pull/11317/commits/f801919b5a991b005671b7fe55b38f322addf4f0. I applied a few additional styles here: https://github.com/Automattic/wp-calypso/blob/7f61c7072311edd8d53d5f61a6aeaf059ae8ad01/client/gutenberg/extensions/mailchimp/view.scss#L32-L35

> Some places it's written "MailChimp", and some other "Mailchimp". The correct version is "Mailchimp" now.

Done in https://github.com/Automattic/wp-calypso/pull/30685/commits/caaf82721eff8f761ad9245efc98bd53f42ac3b7 and https://github.com/Automattic/jetpack/pull/11317/commits/1a0be768d7af1a46e36eb45c1a7317f76d126c0d. 

Note: In the WP.com sharing interface, there are still instances of `MailChimp` that should be changed. @artpi would you be willing to take care of these when you have a chance?

__Front-end:__

> The forced styles on the email input are not needed `.wp-block-jetpack-mailchimp .wp-block-jetpack-mailchimp-email` themes style their inputs and forcing this is not recommended.

Done in https://github.com/Automattic/wp-calypso/pull/30685/commits/49e51babbcdb1e52be6d5d94b2f08cdb324ad0c6 and https://github.com/Automattic/jetpack/pull/11317/commits/5dba73933a66f1193e4b8792892e0c70c64f4a5a

> Same with `.wp-block-jetpack-mailchimp .wp-block-jetpack-mailchimp-form-error` I would suggest we add a generic class `error` to the input. Again, most themes will style this.

Done in https://github.com/Automattic/wp-calypso/pull/30685/commits/4653bcab00fe0b10c3d7d587303bcae6674ae658.

Note: This is tough to test now that the input field is type `email`, since the browser automatically enforces validation. Also, in the Inspector I tried adding the generic `error` class to the input, and didn't see any visual change.

> Displaying all 3 messages in the content with a `display: none` feels strange. Can we just add the message with some JS?

For the Editor, this is done in https://github.com/Automattic/wp-calypso/pull/30685/commits/c8d0bf79750c29e115d5aa0d9701e7106e73c1f3. 

Note: For the Frontend, it isn't terribly straightforward. The approach would probably be to store the notification text bits as data attributes on the block element, and then rework `view.js` to put the appropriate text in the DIV. I'd be happy to do this, but it feels like swapping one form of awkwardness for another, so I'm not sure there's much of a win here. If people feel that this should be done, I'll take it on in a separate PR.

_For all the color-related changes, it wasn't entirely clear to me where the discussion in the issue landed. Muriel? Gutenberg? For now, I just used @thomasguillot's original colors as-is. If the consensus was to go a different way, let me know and I'll change._

> Processing, have a more subtle background: `rgba(0, 0, 0, 0.025)`

Done in https://github.com/Automattic/wp-calypso/pull/30685/commits/d1e45187dc413a3ee7ced27552211997811d97a1

> Success: Let's use an accessible green #1d7819 

Done in https://github.com/Automattic/wp-calypso/pull/30685/commits/d1e45187dc413a3ee7ced27552211997811d97a1

> Same for error: #eb0001 

Done in https://github.com/Automattic/wp-calypso/pull/30685/commits/d1e45187dc413a3ee7ced27552211997811d97a1

> `.wp-block-jetpack-mailchimp .wp-block-jetpack-mailchimp-notification` let's switch to ems: `margin-bottom: 1.5em` and `padding: 0.75em`.

Done in https://github.com/Automattic/wp-calypso/pull/30685/commits/38e9cd2eecd8ab6273067b044c3a1067b8cd12e3

> Remove the `text-center` from the messages. If the user adds a bunch of text to these messages, it wouldn't look great centred.

Done in https://github.com/Automattic/wp-calypso/pull/30685/commits/ce803482484b38968bd6f757d74ab54b4993f2d8

#### Testing instructions

- https://jurassic.ninja/create/?gutenpack&calypsobranch=update/mailchimp-ui-changes&branch=update/mailchimp-ui-changes
- Enable Jetpack
- Enable `JETPACK_BETA_BLOCKS` in `Settings->Jetpack Constants`
- Add Mailchimp, verify all visual/UI changes.

Fixes #30667

### CODE REVIEW

**Comment by thomasguillot** [comment]
It looks great, thank you @jeffersonrabb! I just have a couple of notes/remarks:

> Core Button's background color defaults to `#0073aa`, which is not one of the Muriel blues.

Core Button's background color is good 👍 I'm just wondering now if we should allow for background/text custom colors like the actual Button block: https://cloudup.com/coHwOau93wT

Also, we shouldn't have a "link" option for the button and italic/bold doesn't seem to work, I think it's safe to remove these: https://cloudup.com/czHUFkuNB1N

> I applied a few additional styles here

Rather than forcing the color, font-size and font-style, can we just have a `<small>` text and then leave the rest to the user/theme to decide?

File: client/gutenberg/extensions/mailchimp/edit.jsx [hunk 1]
```diff
@@ -183,43 +184,29 @@ class MailchimpSubscribeEdit extends Component {
...
-					value={ title }
-					onChange={ value => setAttributes( { title: value } ) }
-					inlineToolbar
-				/>
 				{ ! audition && (
 					<form ref={ this.formRef }>
-						<TextControl placeholder={ emailPlaceholder } onChange={ () => false } />
-						<Button isPrimary>{ submitLabel }</Button>
+						<TextControl placeholder={ emailPlaceholder } onChange={ () => false } type="email" />
+						<div className="wp-block-button__link wp-block-jetpack-mailchimp_button">
```
Comment (sirreal) [inline client/gutenberg/extensions/mailchimp/edit.jsx]: Was it impossible to use the `Button` component here? I'd very much prefer to rely on that component rather than a class it uses.

If we need the styling, I think we're better off pulling the necessary styles into our own CSS.

Comment (jeffersonrabb) [reply client/gutenberg/extensions/mailchimp/edit.jsx]: The goal was to emulate the Gutenberg button block in appearance and functionality - and since https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/button/edit.js doesn't make use of the `Button` component I fear that this would lead to slight style divergences and then CSS to overcome them. Re: the styling, yes I'll pull it in.

**Comment by jeffersonrabb** [comment]
> Also, we shouldn't have a "link" option for the button and italic/bold doesn't seem to work, I think it's safe to remove these: https://cloudup.com/czHUFkuNB1N

Removed all the formatting controls in https://github.com/Automattic/wp-calypso/pull/30685/commits/bc6db320f35437255d59027b7fdd414a133609bf

**Comment by jeffersonrabb** [comment]
> Rather than forcing the color, font-size and font-style, can we just have a `<small>` text and then leave the rest to the user/theme to decide?

Confirming, the suggestion is to replace the `<p>` tag with `<small>`? (as opposed to adding `<small>` as a wrapper around it?)

File: client/gutenberg/extensions/mailchimp/edit.jsx (hunk 1 above)
Comment (jeffersonrabb) [reply client/gutenberg/extensions/mailchimp/edit.jsx]: > If we need the styling, I think we're better off pulling the necessary styles into our own CSS.

This is done in https://github.com/Automattic/wp-calypso/pull/30685/commits/8f066fdf9b2e425589ab12a006d474d7c1376bda

**Comment by jeffersonrabb** [comment]
> I'm just wondering now if we should allow for background/text custom colors like the actual Button block: https://cloudup.com/coHwOau93wT

I like the idea, but fear this puts us on a slippery slope of chasing the core button block. If we allow color customization would we also need to support core Button's style choices (Rounded|Outline|Squared)? Button has what looks like fairly dense color fallback handling, and uses a component called `ContrastChecker` that seems a little ... daunting. If changes were made to the Button block down the road presumably we'd want to replicate them in Mailchimp. Finally, the front-end rendering of the button in Mailchimp is quite a bit simpler than it is for Button block, using a `<button>` element with a couple of classes on it effectively leaving the button styling to the theme. If we introduce visual customization elements for the button colors this would need to be examined.

Given all of this, if you still feel we ought to pursue color options for the button I'd propose we land the current PR and address in a new one. @thomasguillot what do you think?

**Comment by thomasguillot** [comment]
> > Rather than forcing the color, font-size and font-style, can we just have a `<small>` text and then leave the rest to the user/theme to decide?
> 
> Confirming, the suggestion is to replace the `<p>` tag with `<small>`? (as opposed to adding `<small>` as a wrapper around it?)

`<p><small>........</small></p>`

**Comment by thomasguillot** [comment]
> Given all of this, if you still feel we ought to pursue color options for the button I'd propose we land the current PR and address in a new one. @thomasguillot what do you think?

Fair enough, thank you for the explanation @jeffersonrabb. Let's keep it as is 😊

**Comment by jeffersonrabb** [comment]
> `<p><small>........</small></p>`

I'm not sure this structure is possible - we're using the `RichText` component which allows setting the containing element as an attribute ( https://github.com/Automattic/wp-calypso/blob/8f066fdf9b2e425589ab12a006d474d7c1376bda/client/gutenberg/extensions/mailchimp/edit.jsx#L200 ). However, there isn't support that I'm aware of for structured tag hierarchy within the element. If I simply change the `tagName` attribute to `small`, the output looks pretty good but there's no paragraph tag. Is this invalid HTML? Also note this applies only to the editor. In the front-end we can structure the output however we'd like.

**Comment by sirreal** [comment]
> I'm not sure this structure is possible

Can't you do the following?

```jsx
<p><RichText tagName="small" /><p>
```

**Comment by jeffersonrabb** [comment]
> Can't you do the following? `<p><RichText tagName="small" /><p>`

`RichText` inserts a bunch of container `<div>`s, so if we take this approach we end up with markup like this:

screen shot 2019-02-11 at 7 50 59 am

@thomasguillot is this acceptable markup?

**Comment by thomasguillot** [comment]
> @thomasguillot is this acceptable markup?

It's not 😞`p` can't contain `div`. It's ok. For the editor we can just go with `small` and have `p small`for the front-end.

**Comment by sirreal** [comment]
> `RichText` inserts a bunch of container `<div>`s

😞 I actually came across similar problem when I tried to use it recently. I wonder if it could be improved to help with cases like this. There do seem to be short-term plans to iterate on the component: https://github.com/WordPress/gutenberg/issues/13778

**Comment by jeffersonrabb** [comment]
> It's not 😞`p` can't contain `div`. It's ok. For the editor we can just go with `small` and have `p small`for the front-end.

So much 😞around this one! Changes made in https://github.com/Automattic/wp-calypso/pull/30685/commits/d59edb66bc20fa3165558fa6fc6cbf9eebce2943 and https://github.com/Automattic/jetpack/pull/11317/commits/f4a7d6594e7520ef00ee80ac695633ee7932b6ea. I left the color and italics declarations in but removed the sizing - is this correct?

**Comment by thomasguillot** [comment]
> > It's not 😞`p` can't contain `div`. It's ok. For the editor we can just go with `small` and have `p small`for the front-end.
> 
> So much 😞around this one! Changes made in [d59edb6](https://github.com/Automattic/wp-calypso/commit/d59edb66bc20fa3165558fa6fc6cbf9eebce2943) and [Automattic/jetpack@f4a7d65](https://github.com/Automattic/jetpack/commit/f4a7d6594e7520ef00ee80ac695633ee7932b6ea). I left the color and italics declarations in but removed the sizing - is this correct?

Can we just remove the entire CSS for `.wp-block-jetpack-mailchimp_consent-text`?

`small` is enough to differentiate the text from the rest of the content.

**Comment by jeffersonrabb** [comment]
> Can we just remove the entire CSS for `.wp-block-jetpack-mailchimp_consent-text`?

Done in https://github.com/Automattic/wp-calypso/pull/30685/commits/1bc9f822521e630ace47d5b2a1c9e3d0e1cad87f and https://github.com/Automattic/jetpack/pull/11317/commits/6961def0b85f1c1e66adcb1698f21902c9233fd1#diff-e800fe1ba24cea2c2da6f6ac9f542d4dR68

**Comment by thomasguillot** [comment]
screenshot 2019-02-11 at 14 56 21

Front-end doesn't seem to work anymore

**Comment by jeffersonrabb** [comment]
> Front-end doesn't seem to work anymore

Try pulling the Jetpack branch (if you're testing locally), or create a new JN instance. Just resolved the issue in https://github.com/Automattic/jetpack/pull/11317/commits/89d53f05d77fe38c5d9c7ca2070db77b8119ea9a.

File: client/gutenberg/extensions/mailchimp/view.scss [hunk 2]
```diff
@@ -1,49 +1,32 @@
...
+			background-color: #eb0001;
+			color: #fff;
+		}
+
+		&.wp-block-jetpack-mailchimp_processing {
+			background-color: rgba( 0, 0, 0, 0.025 );
+		}
+
+		&.wp-block-jetpack-mailchimp_success {
+			background-color: #1d7819;
```
Comment (simison) [inline client/gutenberg/extensions/mailchimp/view.scss]: We could use `$muriel-green-500` here.

File: client/gutenberg/extensions/mailchimp/view.scss [hunk 3]
```diff
@@ -1,49 +1,32 @@
...
-		padding: 20px;
-		text-align: center;
+		margin-bottom: 1.5em;
+		padding: 0.75em;
 		&.is-visible {
 			display: block;
 		}
+
+		&.wp-block-jetpack-mailchimp_error {
+			background-color: #eb0001;
```
Comment (simison) [inline client/gutenberg/extensions/mailchimp/view.scss]: We could use `$muriel-hot-red-500` sass variable here.

These are available because we import these from https://github.com/Automattic/color-studio

File: client/gutenberg/extensions/mailchimp/view.scss (hunk 2 above)
Comment (thomasguillot) [reply client/gutenberg/extensions/mailchimp/view.scss]: Since we are using Hot Red and I didn't think of it previously, let's use Hot Green here instead 😊 `$muriel-hot-red-500`

File: client/gutenberg/extensions/mailchimp/view.scss (hunk 3 above)
Comment (jeffersonrabb) [reply client/gutenberg/extensions/mailchimp/view.scss]: Done in https://github.com/Automattic/wp-calypso/pull/30685/commits/5f34885968d9787ca316afa4305f794ef7486306

File: client/gutenberg/extensions/mailchimp/view.scss (hunk 2 above)
Comment (jeffersonrabb) [reply client/gutenberg/extensions/mailchimp/view.scss]: Done in https://github.com/Automattic/wp-calypso/pull/30685/commits/83bc6ab8cac6a70717947972975d00b768781b52

**Comment by jeffersonrabb** [comment]
@artpi pointed out an issue in which the consent text's inline toolbar blocks clicks on the submit button, making the button non-editable. This is fixed along with a change to the button text's cursor in https://github.com/Automattic/wp-calypso/pull/30685/commits/4518d4e7a1da9ef51f7a87622538354393ba9d7c. 

@thomasguillot does this approach raise any red flags?

**Comment by thomasguillot** [comment]
> @thomasguillot does this approach raise any red flags?

Nope, all good 🙂
