### PR TITLE
Site Address Changer: Improve error message when trying to rename wpcomstaging address

### LINKED ISSUE #55306: Unclear error in Calypso when trying to rename wpcomstaging address
### Steps to Reproduce

1. Create AT site without a custom domain
2. try to rename the site once it's gone AT
3. see the following error
2021-08-11 at 09 56

### What I expected to happen

They shouldn't be given this as an option in the first place
- also it would be nice if there was a clear reason given for why they can't change
- ala this section: https://wordpress.com/support/changing-site-address/#a-note-on-wpcomstaging-com-addresses

### What actually happened

It gives an error but doesn't explain why or what to do about it

### Context

p1628584715162900-slack-C03TY6J1A
User wanting to change address and workaround is to create a new site and import other contents... not a good option

### Operating System

macOS

### OS Version

_No response_

### Browser

Chrome/Chromium

### Browser Version(s)

_No response_

### Is this specific to applied theme? If so, what is the theme name?

no

### Simple, Atomic or both?

Atomic

### Console and/or error logs

_No response_

### Number of Users Impacted

_No response_

### Available Workarounds

Add a custom domain
create a new site and import contents <- terrible option

### Reproducibility

Consistent

### Other information

_No response_

### PR DESCRIPTION
**Pull request by allilevine**
#### Changes proposed in this Pull Request

* Add `errorStatus` to get error status code (e.g. 404) from error data
* [x] Add new error message

Screen Shot 2021-11-09 at 5 52 26 PM
#### Testing instructions

* Create a new site with a business plan.
* Go to Upgrades > Domains
* Click Manage > Change Site Address
* In a new tab, install a plugin to transfer the site to Atomic
* Once the site has transferred, go back to the first tab and start typing a new site address. 
* See our new and improved error message.
* Regression: Check that you can still see other errors when changing a Simple site address (e.g. about character length or the name being unavailable).

Fixes https://github.com/Automattic/wp-calypso/issues/55306

### CODE REVIEW

**Comment by Rolilink** [comment]
Added improved message [here](https://github.com/Automattic/wp-calypso/pull/57408/commits/1cb374d44dfa9f55628d48622c55c5357787b8c1) but maybe wording can be improved even more to reflect that the site has been transferred to atomic?:
Screen Shot 2021-10-28 at 6 22 33 PM

File: client/blocks/site-address-changer/index.jsx [hunk 1]
```diff
@@ -27,6 +27,7 @@ import { getSelectedSiteId } from 'calypso/state/ui/selectors';
 import ConfirmationDialog from './dialog';
 
 import './style.scss';
+import { isAtomicSiteLogAccessEnabled } from '../../state/selectors/is-atomic-site-log-access-enabled';
```
Comment (allilevine) [inline client/blocks/site-address-changer/index.jsx]: @Rolilink Do we need this import? I'm not seeing a reference to it 🤔

File: client/blocks/site-address-changer/index.jsx [hunk 2]
```diff
@@ -214,11 +215,28 @@ export class SiteAddressChanger extends Component {
 		return currentDomainName.replace( currentDomainSuffix, '' );
 	}
 
+	/**
+	 * Github Issue: #55306
```
Comment (allilevine) [inline client/blocks/site-address-changer/index.jsx]: This is a really helpful comment 🎉 I don't think we need the Github Issue number, but it looks great otherwise.

File: client/blocks/site-address-changer/index.jsx [hunk 3]
```diff
@@ -214,11 +215,28 @@ export class SiteAddressChanger extends Component {
...
+	 * This is an edge case scenario where user have the site address changer opened and the user transfers
+	 * the site to atomic on other tab/window, losing sync between client and server. Client will try to
+	 * check availability against wordpress.com and will receive 404s because site is transfered to wpcomstaging.com
+	 */
+	isUnsyncedAtomicSite() {
+		const { validationError, isAtomicSite } = this.props;
+		const serverValidationErrorStatus = get( validationError, 'errorStatus' );
+
+		return serverValidationErrorStatus === 404 && ! isAtomicSite;
```
Comment (allilevine) [inline client/blocks/site-address-changer/index.jsx]: Do we need to check `isAtomicSite`, or should we show the error regardless? It seems like if the site is Atomic we definitely want to show this error, but if `isAtomicSite` is `false` and we're getting the 404, we still want to show the error.

File: client/blocks/site-address-changer/index.jsx [hunk 4]
```diff
@@ -214,11 +215,28 @@ export class SiteAddressChanger extends Component {
 		return currentDomainName.replace( currentDomainSuffix, '' );
 	}
 
+	/**
+	 * Github Issue: #55306
+	 * This is an edge case scenario where user have the site address changer opened and the user transfers
+	 * the site to atomic on other tab/window, losing sync between client and server. Client will try to
+	 * check availability against wordpress.com and will receive 404s because site is transfered to wpcomstaging.com
+	 */
+	isUnsyncedAtomicSite() {
```
Comment (allilevine) [inline client/blocks/site-address-changer/index.jsx:221]: Would it help to set some local state here, since we reference this check twice? We could set something like `notFoundError = true` and then check that state.

**Review by allilevine — COMMENTED** [review]
This is working correctly for me, I see the new error message and the disabled button. 🎉 
Screen Shot 2021-10-29 at 10 00 28 AM

File: client/blocks/site-address-changer/index.jsx (hunk 1 above)
Comment (Rolilink) [reply client/blocks/site-address-changer/index.jsx]: 🤔  This seems to be some VSCode Shenanigans! will remove it!

File: client/blocks/site-address-changer/index.jsx (hunk 4 above)
Comment (Rolilink) [reply client/blocks/site-address-changer/index.jsx:221]: I thought about that but normally I try to not use state unless is absolutely necessary because it can trigger unnecessary re-renders since we already receiving the error through props, I thought it was fine just to go through the "functional-ish" route and derive data from the props. 

It could be just me overthinking it but would love to know what you think about it. ☺️

File: client/blocks/site-address-changer/index.jsx (hunk 3 above)
Comment (Rolilink) [reply client/blocks/site-address-changer/index.jsx]: I was thinking that this could be an edge case and maybe we have scenarios when a `404` is returned. But since there is no visible scenario yet it makes sense not to add it so I will remove it.

File: client/blocks/site-address-changer/index.jsx (hunk 4 above)
Comment (allilevine) [reply client/blocks/site-address-changer/index.jsx:221]: That's true! We don't need to re-render, and this function isn't doing anything intensive. Let's leave it like you have it 👍

**Review by DustyReagan — APPROVED** [review]
New error message appears correct. Old error messages are still appearing. 

LGTM! 👍

cannot-change

File: client/blocks/site-address-changer/index.jsx [hunk 5]
```diff
@@ -214,11 +213,27 @@ export class SiteAddressChanger extends Component {
...
+	/**
+	 * This is an edge case scenario where user have the site address changer opened and the user transfers
+	 * the site to atomic on other tab/window, losing sync between client and server. Client will try to
+	 * check availability against wordpress.com and will receive 404s because site is transfered to wpcomstaging.com
+	 */
+	isUnsyncedAtomicSite() {
+		const { validationError } = this.props;
+		const serverValidationErrorStatus = get( validationError, 'errorStatus' );
+
+		return serverValidationErrorStatus === 404;
```
Comment (pablinos) [inline client/blocks/site-address-changer/index.jsx]: Is there an advantage to using `get` here? If `validationError` is sometimes undefined, we could do:

```suggestion
		return 404 === validationError?.errorStatus;
```

File: client/state/site-address-change/actions.js [hunk 6]
```diff
@@ -60,13 +60,15 @@ export const requestSiteAddressAvailability = (
 		.then( ( data ) => {
 			const errorType = get( data, 'error' );
 			const message = get( data, 'message' );
+			const errorStatus = get( data, 'status' );
```
Comment (pablinos) [inline client/state/site-address-change/actions.js]: Similarly, perhaps we could change these three lines to:
```js
const { error: errorType, message, status: errorStatus } = data;
```

File: client/state/site-address-change/actions.js [hunk 7]
```diff
@@ -81,12 +83,14 @@ export const requestSiteAddressAvailability = (
 		.catch( ( error ) => {
 			const errorType = get( error, 'error' );
 			const message = get( error, 'message' );
+			const errorStatus = get( error, 'status' );
```
Comment (pablinos) [inline client/state/site-address-change/actions.js]: We could do the same here too, and perhaps remove the use of `get`

File: client/blocks/site-address-changer/index.jsx [hunk 8]
```diff
@@ -214,11 +213,27 @@ export class SiteAddressChanger extends Component {
...
+	}
+
 	getValidationMessage() {
 		const { isAvailable, validationError, translate } = this.props;
 		const { validationMessage } = this.state;
 		const serverValidationMessage = get( validationError, 'message' );
 
+		if ( this.isUnsyncedAtomicSite() ) {
+			return translate( 'wpcomstaging.com addresses cannot be changed.' );
```
Comment (pablinos) [inline client/blocks/site-address-changer/index.jsx]: Is it definitely only Atomic sites where this happens? Should we make this more generic, to something like "This site's address cannot be changed"?

**Review by pablinos — COMMENTED** [review]
Looks good! Just a few nitpick things. Take them or leave them

File: client/blocks/site-address-changer/index.jsx (hunk 5 above)
Comment (allilevine) [reply client/blocks/site-address-changer/index.jsx]: Sounds good! It was the convention in the file, but avoiding lodash would be better.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6952890

Thank you @allilevine for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6952890).
