### PR TITLE
Store orders: Set initial refund value in modal

### LINKED ISSUE #18673: Store: Refunds: Initial Total Refund Amount is zero (should include shipping cost)
On initially entering the refund flow, the total incorrectly shows $0.00 when it should show the shipping amount (if any)

incorrect-initial-refund-amount

Originally: https://github.com/Automattic/wp-calypso/pull/18633#issuecomment-335240428

### PR DESCRIPTION
**Pull request by ryelle**
Move refund calculation into the dialog, so that we can set an initial refund value when the dialog is opened. Fixes #18673

To test:

- View an order
- Open the refund modal by clicking "Submit Refund"
- The "Total refund amount" should pre-fill with the shipping amount, not be zero

### CODE REVIEW

**Comment by allendav** [comment]
Works great, but the amount in the refund box briefly reverts during the refund process.  Can we avoid that?

amount-in-refund-box-changes-briefly-during-refunding

**Comment by allendav** [comment]
On a different order, where I had refunded the product already, and then attempted to refund just the shipping, it incorrectly stated that the refund amount exceeded the allowed amount, when it actually exactly matched it:

835-vs-835

**Comment by ryelle** [comment]
The total refund amount reverting was an issue with resetting the values when toggling the dialog, so I've updated the code to only reset the values when the dialog opens. The latter issue is related to taxes and what I was talking about on the zoom today, where there's probably a fraction-cent mismatch between the total and refund amount. I'll address that in a future PR, after order-editing is done.

File: client/extensions/woocommerce/app/order/order-payment/dialog.js [hunk 1]
```diff
@@ -78,14 +78,17 @@ class OrderPaymentCard extends Component {
 		if ( oldSiteId !== newSiteId ) {
 			this.props.fetchPaymentMethods( newSiteId );
 		}
+		// Has been opened and closed before, let's reset the values.
+		if ( newProps.isVisible && ! this.props.isVisible ) {
```
Comment (allendav) [inline client/extensions/woocommerce/app/order/order-payment/dialog.js]: Nice
