### PR TITLE
Login: Honour `redirect_to` param after returning from Sign-in with Apple flow

### LINKED ISSUE #42092: Gutenboarding: Apple sign in redirects to `/start`
### Description

During the Gutenboarding flow, after signing in with Apple ID, the user is redirected to `/start` and not `/new`

### Steps to reproduce

1. Go through the `/new` flow
2. Instead of signing up, log in
3. Select "Continue with Apple"
4. Enter your Apple ID details

#### What happens

After logging in with Apple I'm taken to `/start`

#### What I expected

I'm taken back to the Gutenboarding flow where my site will be created :)

### PR DESCRIPTION
**Pull request by p-jackson**
#### Changes proposed in this Pull Request

* Refactor `rebootAfterLogin()` component method to redux action

This fixes a `@TODO` to share this code between the login block and magic link form.

But more importantly it fixes redirecting to the correct place if the user is signing in with Apple. The broken flow goes like this:

1. When the user clicks "Sign in with Apple" we [stash the `redirect_to` param in session storage](https://github.com/Automattic/wp-calypso/blob/5076a5b0355409a4aedb8df28262fa05d3b414c0/client/blocks/login/social.jsx#L176)
2. After the user successfully logs in with apple, we [read the redirect url out of session storage](https://github.com/Automattic/wp-calypso/blob/5076a5b0355409a4aedb8df28262fa05d3b414c0/client/blocks/login/social.jsx#L124) and [fire a `loginSocialUser` action](https://github.com/Automattic/wp-calypso/blob/5076a5b0355409a4aedb8df28262fa05d3b414c0/client/blocks/login/social.jsx#L138)
3. `loginSocialUser` calls `/wp-login.php` and on success stores the redirect url (which has been sanitized by the backend) [in the redux store](https://github.com/Automattic/wp-calypso/blob/5076a5b0355409a4aedb8df28262fa05d3b414c0/client/state/login/actions/login-social-user.js#L58)
4. Now that `loginSocialUser` is done [the component calls its success handler](https://github.com/Automattic/wp-calypso/blob/5076a5b0355409a4aedb8df28262fa05d3b414c0/client/blocks/login/social.jsx#L142)
5. Which is [the `rebootAfterLogin` method](https://github.com/Automattic/wp-calypso/blob/5076a5b0355409a4aedb8df28262fa05d3b414c0/client/blocks/login/index.jsx#L180). It redirects the user using the `redirectTo` prop, which it got from the redux store during the last render.

However the problem is that React hasn't had a chance to re-render the `<Login>` component yet! The redux store has been updated by `loginSocialUser`, however the component still has the old value, which is `null`.

By refactoring `rebootAfterLogin` to an action, we're able to use the latest values from the store, not whatever values were used in the last render.

#### Testing instructions

* Check out branch
* Go to `http://calypso.localhost:3000/log-in?redirect_to=http%3A%2F%2Fcalypso.localhost%3A3000%2Fme`, which is a login page that will go to `/me` after a successful log in
* Test that all these login flows eventually go to 
  * Username and password
  * With 2nd factor
  * "Email me a login link"
  * Google login
  * ***After staging deployment is complete*** Apple login
* `/log-in` is still SSR'd (disable JS and check the server renders a disabled login form)

Fixes #42092

### CODE REVIEW

**Comment by andrewserong** [comment]
I haven't tested this yet, but superficially it's looking good! And this refactor effectively includes the change in https://github.com/Automattic/wp-calypso/pull/42319 that will resolve part of #42035. I'll abandon #42319 in favour of this PR 😄

File: client/state/login/actions/reboot-after-login.ts [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+
+	dispatch(
+		recordTracksEvent( 'calypso_login_success', {
+			two_factor_enabled: twoFactorEnabled,
+			...tracksEventArgs,
+		} )
+	);
+
+	// Redirects to / if no redirect url is available
+	const url = redirectToSanitized || '/';
```
Comment (ramonjd) [inline client/state/login/actions/reboot-after-login.ts:30]: Warning: premature optimization! ;)

Could this line be deleted and we incorporate into `const url = getRedirectToSanitized( getState() ) || ''` ?

Comment (p-jackson) [reply client/state/login/actions/reboot-after-login.ts:30]: Yeah it can actually. I basically copied the exact code layout over from the component method, but probably would have written it differently if I'd done it from scratch.

**Comment by p-jackson** [comment]
> I haven't tested this yet, but superficially it's looking good! And this refactor effectively includes the change in #42319 that will resolve part of #42035. I'll abandon #42319 in favour of this PR 😄

Nice! I love it when tidying the code also fixes bugs

**Comment by andrewserong** [comment]
Tested logging in with:

✅ Username and password
✅ With 2nd factor
✅ "Email me a login link"
✅ Google login

All redirected correctly to the `redirect_to` location.

✅ /log-in is still SSR'd (disable JS and check the server renders a disabled login form)

I haven't managed to get SIWA working locally yet (either on this branch or master), but I'll keep having a play with it.

The mobile e2e test is failing, I've kicked it off again just to be sure (I don't imagine it's related, but let's see if it passes).

**Comment by p-jackson** [comment]
Managed to test SIWA using local dev environment and charles proxy so I could test it using the `wordpress.com` domain. Worked as expected.
