### PR TITLE
Editor: fix ability to edit feedbacks

### LINKED ISSUE #25315: Feedback: React errors when trying to edit feedback
Hi! I'm reporting a bug mentioned by a user on chat and reproduced on my own account. When editing a feedback from *My Site > Feedback*, the page is blank and the console shows numerous errors.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/types/feedback/ (*My Site > Feedback*)
2. Click on a feedback to edit it
3. Page is blank
4. Check console to see errors, including [React error 40](https://reactjs.org/docs/error-decoder.html?invariant=40)

#### What I expected

To be able to edit my feedback

#### What happened instead

Blank page on WordPress.com site. **It works fine with Jetpack sites.**

#### Browser / OS version

Reproduced on Chrome, Firefox and Safari

#### Screenshot / Video

screen capture on 2018-06-06 at 17-21-03

### PR DESCRIPTION
**Pull request by gwwar**
Fixes #25315 When folks leave feedback in a contact form, sometimes we'd like to edit this in the Editor. In production, we're seeing a blank page instead of the feedback loading. 

This is likely a regression from #23844 on an easy to miss case. Basically `const author = get( post, 'author', getCurrentUser( state ) );` will use the value `null` instead of the default fallback because it's a valid value. When this happens, an error is thrown on `const name = author.display_name || author.name;`

41048006-1849dc38-69ae-11e8-9295-984ffe3fd424

### Testing Instructions
- In Calypso, add a post or page with a contact form
- Publish the post or page
- Visit the published page/post
- Submit the contact form
- Navigate to https://wordpress.com/types/feedback/{site}
- Edit your feedback

### CODE REVIEW

File: client/post-editor/editor-author/index.jsx [hunk 1]
```diff
@@ -105,7 +105,9 @@ export default connect(
 
 		const site = getSite( state, siteId );
 		const post = getEditedPost( state, siteId, postId );
-		const author = get( post, 'author', getCurrentUser( state ) );
+		const postAuthor = get( post, 'author' );
+		//default to current user when null or falsey
+		const author = postAuthor ? postAuthor : getCurrentUser( state );
```
Comment (blowery) [inline client/post-editor/editor-author/index.jsx]: I trust that this fixed it, but I'm not seeing how. Do you happen to recall the exact call that somehow skipped the default somehow?

Comment (blowery) [reply client/post-editor/editor-author/index.jsx]: ah, got it
`_.get( { author: false }, 'author', 'default' )` => `false`

**Review by blowery — APPROVED** [review]
Nice sleuthing! 👍

**Comment by blowery** [comment]
I'll deploy this when it lands

File: client/post-editor/editor-author/index.jsx (hunk 1 above)
Comment (blowery) [reply client/post-editor/editor-author/index.jsx]: I am dense. :) This was in your description, it just didn't click the first few times I read it.
