### PR TITLE
Full Site Editing: Remove the Content and Template blocks from the Inserter

### LINKED ISSUE #35436: FSE: Can not delete Content Block from Header
#### Steps to reproduce
1. Open the header editor and add a content block to the header
2. Save
3. Head to the Page editor. See the error you've done the wrong thing
4. Reopen the header editor

#### What I expected

I see an error in the page editor that I can only use the content block once. I want to be able to click on the content block to remove it.

#### What happened instead

There is no 3 dots to click to remove the content block from the header editor

#### Browser / OS version

Chrome  Version 76.0.3809.100 (Official Build) (64-bit)
Mac OS 10.14.6 (18G87)

#### Screenshot / Video

Attempts to remove the content block

(Image link: https://cld.wthms.co/SWAdSJ )

### PR DESCRIPTION
**Pull request by Copons**
#### Changes proposed in this Pull Request

We can only have one Content block in pages (pre-filled), and none in templates.
We can only have two Template blocks in pages (pre-filled), and none in templates.

So there is no reason to have them available in the Inserter!

#### Testing instructions

* On an FSE site, try editing both a page and a template.
* Make sure in neither case it's possible to add both the Content and Template blocks.
  * It shouldn't appear in the Inserter menu in the top bar.
  * It shouldn't appear in the Inserter menu between blocks.
  * It shouldn't appear in the Inserter menu triggered with the `/` character.

Fixes #35436

### CODE REVIEW

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/index.js [hunk 1]
```diff
@@ -28,6 +28,7 @@ if ( 'wp_template' !== fullSiteEditing.editorPostType ) {
 			anchor: false,
 			customClassName: false,
 			html: false,
+			inserter: false,
```
Comment (noahtallen) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/index.js]: I **love** when gutenberg makes things this simple!
