### PR TITLE
reduxify user-settings in `me/account`

### LINKED ISSUE #49591: Ensure Me account page alerts of unsaved settings if only a single form group has been saved.
Identified in https://github.com/Automattic/wp-calypso/pull/48710#pullrequestreview-580468956.

This was identified by @mmtr:

> I expect the alert warning about unsaved changes to show up if I have unsaved changes in any in the 2 forms. however,  if you have unsaved changes in both forms and save one of them, the alert is not displayed when exiting the page, although I have unsaved changes in the 2nd form 

### Steps to reproduce the behavior

1. Go to http://calypso.localhost:3000/me/account
2. Make changes in _both_ forms.
3. Only save _1_ group of fields (eg: Account or Interface).
4. Attempt reload the page or navigate away. 
5. You don't see a browser alert warning of unsaved changes.

#### What I expected to happen

Any time I try and leave with unsaved changes I should be prompted to check I really want to leave the page.

#### What actually happened

See above.

### PR DESCRIPTION
**Pull request by flootr**
This PR is partly a spin-off from https://github.com/Automattic/wp-calypso/pull/49105. It doesn't contain certain refactorings (such as migrating `<Account />` to a class component) to make the PR more contained and easier to review. I'll follow up with a few more PRs which take care of those refactorings.

#### Changes proposed in this Pull Request

* Move `<Account />` to use Redux to change / update user settings
* Tangential:
  * fix a bug where changing the language would not protect the user from navigating away
  * fix a bug where changing user settings back to original values wouldn't let the user navigate away
  * fix a bug where saving user settings from the one form would let the user navigate away even though there are changes in the other form

#### Testing instructions

Note Also test this with a newly created account (to test settings which miss a default value such as `colorScheme`) as well as a non-a8c account with a verified email address to be able to change your username (can be the same).

1. Go to `/me/account` and verify updating account and interface settings work exactly like on prod (except for the mentioned bug fixes).
2.  Make sure the following scenarios work as expected:

- Make changes in both forms but only save one of them. Try to navigate away. A dialog should pop up warning you that you have unsaved changes. After you saved the other form, you should be able to navigate away
- Make changes to the form, navigate away (confirm the dialog) and go back. Make sure changes have been cleared and you're back to the initial state.
- Inspect the _Network_ request and verify only settings from the submitted form are being sent
- Check error handling works as expected by blocking requests to `public-api.wordpress.com/rest/v1.1/me/settings`
- Changing language settings should result in a page reload

Related to #24162 
Fixes https://github.com/Automattic/wp-calypso/issues/49591

### CODE REVIEW

File: client/state/user-settings/thunks/save-unsaved-user-settings.js [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+import getUnsavedUserSettings from 'calypso/state/selectors/get-unsaved-user-settings';
+
+const wpcom = wp.undocumented();
+
+/**
+ * Redux thunk which exclusively updates given unsaved user settings
+ *
+ * @param {Array} fields Array of keys to be saved from unsaved user settings
+ */
+const saveUnsavedUserSettings = ( fields = [] ) => async ( dispatch, getState ) => {
```
Comment (flootr) [inline client/state/user-settings/thunks/save-unsaved-user-settings.js:19]: I opted for a thunk in this case because `<Account />` contains two separate forms (as of #48710) which the `userSettings` reducer is not capable of handling (and shouldn't be imo). That means we continue to manage state like `isSubmittingForm` etc within the `<Account />` component, for now. This may change with the PRs which should follow to clean things up a bit more.

File: client/state/user-settings/actions.js [hunk 2]
```diff
@@ -116,22 +137,40 @@ export const removeUnsavedUserSetting = ( settingName ) => ( {
...
 		const settings = getUserSettings( getState() );
-
-		if ( get( settings, settingName ) === undefined ) {
+		const settingKey = Array.isArray( settingName ) ? settingName : settingName.split( '.' );
+
+		const maybeSetting = get( settings, settingKey );
+
+		if (
+			maybeSetting === undefined &&
+			/* FIXME: excluding these settings is a workaround which allows
```
Comment (flootr) [inline client/state/user-settings/actions.js]: This note was migrated from [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/me/account/main.jsx#L194-L214).

File: client/me/account/main.jsx [hunk 3]
```diff
@@ -98,29 +106,28 @@ const INTERFACE_FIELDS = [
...
 
 	componentDidMount() {
 		debug( this.constructor.displayName + ' component is mounted.' );
-		this.props.userSettings.getSettings();
 		this.debouncedUsernameValidate = debounce( this.validateUsername, 600 );
 	},
 
+	componentDidUpdate() {
+		if ( ! this.hasUnsavedUserSettings( [].concat( ACCOUNT_FIELDS, INTERFACE_FIELDS ) ) ) {
+			this.props.markSaved?.();
```
Comment (tyxla) [inline client/me/account/main.jsx]: I find it odd that in some instances we call `markSaved()` with optional chaining, and in some, we call it directly. If `markSaved` may not exist under some circumstances, shouldn't we update it to reflect that everywhere in the codebase?

File: client/me/account/main.jsx [hunk 4]
```diff
@@ -138,15 +145,29 @@ const Account = createReactClass( {
 	},
 
 	getUserSetting( settingName ) {
-		return this.props.userSettings.getSetting( settingName );
+		return (
+			get( this.props.unsavedUserSettings, settingName ) ??
```
Comment (tyxla) [inline client/me/account/main.jsx:151]: We're using nullish coalescing anyway to fall back to original setting, so should we avoid `get()` and use `this.props.unsavedUserSettings?.[ settingName ]` here instead?

File: client/me/account/main.jsx [hunk 5]
```diff
@@ -138,15 +145,29 @@ const Account = createReactClass( {
...
+			this.getUserOriginalSetting( settingName )
+		);
 	},
 
 	getUserOriginalSetting( settingName ) {
-		return this.props.userSettings.getOriginalSetting( settingName );
+		return get( this.props.userSettings, settingName );
```
Comment (tyxla) [inline client/me/account/main.jsx:157]: What's the benefit of using `get()` here instead of just going with optional chaining?

FWIW we also have other instances of `get()` here, consider this question applicable to them, too.

File: client/me/account/main.jsx [hunk 6]
```diff
@@ -138,15 +145,29 @@ const Account = createReactClass( {
...
+	},
+
+	hasUnsavedUserSetting( settingName ) {
+		return has( this.props.unsavedUserSettings, settingName );
```
Comment (tyxla) [inline client/me/account/main.jsx:161]: Is `has()` preferred than `this.props.unsavedUserSettings?.hasOwnProperty( settingName )` for a reason? 

FWIW we also have other instances of `has()` here, consider this question applicable to them, too.

File: client/me/account/main.jsx [hunk 7]
```diff
@@ -393,18 +406,18 @@ const Account = createReactClass( {
 	},
 
 	handleSubmitButtonClick() {
-		const { unsavedSettings } = this.props.userSettings;
+		const { unsavedUserSettings } = this.props;
 		this.recordClickEvent( 'Save Account Settings Button' );
-		if ( has( unsavedSettings, colorSchemeKey ) ) {
-			const colorScheme = get( unsavedSettings, colorSchemeKey );
+		if ( has( unsavedUserSettings, colorSchemeKey ) ) {
```
Comment (tyxla) [inline client/me/account/main.jsx]: Should we use `this.hasUnsavedUserSetting( colorSchemeKey )` here?

File: client/me/account/main.jsx [hunk 8]
```diff
@@ -393,18 +406,18 @@ const Account = createReactClass( {
...
+			const colorScheme = get( unsavedUserSettings, colorSchemeKey );
 			this.props.recordTracksEvent( 'calypso_color_schemes_save', {
 				color_scheme: colorScheme,
 			} );
 			this.props.recordGoogleEvent( 'Me', 'Saved Color Scheme', 'scheme', colorScheme );
 			this.props.bumpStat( 'calypso_changed_color_scheme', colorScheme );
 		}
 
-		if ( has( unsavedSettings, 'language' ) ) {
+		if ( has( unsavedUserSettings, 'language' ) ) {
```
Comment (tyxla) [inline client/me/account/main.jsx]: Should we use `this.hasUnsavedUserSetting( 'language' )` here?

File: client/state/user-settings/actions.js [hunk 9]
```diff
@@ -105,6 +105,27 @@ export const removeUnsavedUserSetting = ( settingName ) => ( {
...
+ * @param  {object}  settings user settings object.
+ * @returns {boolean} if the language setting has been changed.
+ */
+function hasLanguageChanged( languageSettingValue, settings = {} ) {
+	if ( ! languageSettingValue ) {
+		return false;
+	}
+	// if there is a saved variant we know that the user is changing back to the root language === setting hasn't changed
+	// but if settings.locale_variant is not empty then we assume the user is trying to switch back to the root
+	return (
```
Comment (tyxla) [inline client/state/user-settings/actions.js]: Should we also consider the empathy mode setting as we do here: https://github.com/Automattic/wp-calypso/pull/49760/files#diff-79489c122f24dcb8752581772ddb5070e083a14f1a77ebbfd4e04c6b2f8c64f8R206

File: client/state/user-settings/actions.js [hunk 10]
```diff
@@ -116,22 +137,40 @@ export const removeUnsavedUserSetting = ( settingName ) => ( {
 export function setUserSetting( settingName, value ) {
 	return ( dispatch, getState ) => {
 		const settings = getUserSettings( getState() );
-
-		if ( get( settings, settingName ) === undefined ) {
+		const settingKey = Array.isArray( settingName ) ? settingName : settingName.split( '.' );
```
Comment (tyxla) [inline client/state/user-settings/actions.js]: It feels like this logic could be abstracted and reused where necessary. 

Some tests could be useful for this action, too.

File: client/me/account/main.jsx (hunk 4 above)
Comment (flootr) [reply client/me/account/main.jsx:151]: `settingName` could be a path so we need to fall back to using `get` as long as we don't have our own version of it.

File: client/me/account/main.jsx (hunk 5 above)
Comment (flootr) [reply client/me/account/main.jsx:157]: See my comment here: https://github.com/Automattic/wp-calypso/pull/49760#discussion_r571189849

File: client/me/account/main.jsx (hunk 6 above)
Comment (flootr) [reply client/me/account/main.jsx:161]: See my comment here: https://github.com/Automattic/wp-calypso/pull/49760#discussion_r571189849 – also applies to `has`.

File: client/me/account/main.jsx (hunk 7 above)
Comment (flootr) [reply client/me/account/main.jsx]: Yes, we can do that 👍🏻

File: client/me/account/main.jsx (hunk 8 above)
Comment (flootr) [reply client/me/account/main.jsx]: Yes, we can do that 👍🏻

File: client/me/account/main.jsx (hunk 3 above)
Comment (flootr) [reply client/me/account/main.jsx]: You're right. We should assume it's there. I'll remove optional chaining for these methods.

File: client/me/account/main.jsx (hunk 4 above)
Comment (flootr) [reply client/me/account/main.jsx:151]: That said this could be a very good follow up. I already made a note to extract the recently introduced `setValue` and `removeValue` helpers as well (see https://github.com/Automattic/wp-calypso/pull/49521#discussion_r567798686).

File: client/me/account/main.jsx (hunk 3 above)
Comment (flootr) [reply client/me/account/main.jsx]: Addressed via https://github.com/Automattic/wp-calypso/pull/49760/commits/e9d1984639f9c7ae10c868215e4c5d3ac90af28b

File: client/me/account/main.jsx (hunk 7 above)
Comment (flootr) [reply client/me/account/main.jsx]: See https://github.com/Automattic/wp-calypso/pull/49760/commits/1cc66281e1f35db279a3d90db5eb6e3ad70678bd

File: client/me/account/main.jsx (hunk 8 above)
Comment (flootr) [reply client/me/account/main.jsx]: See https://github.com/Automattic/wp-calypso/pull/49760/commits/1cc66281e1f35db279a3d90db5eb6e3ad70678bd

File: client/state/user-settings/actions.js (hunk 10 above)
Comment (flootr) [reply client/state/user-settings/actions.js]: I extracted `setUserSetting` into the `thunks` directory and improved tests in https://github.com/Automattic/wp-calypso/pull/49760/commits/4e13faeb55669696e76d8682042ad72740218fb5

File: client/state/user-settings/actions.js (hunk 9 above)
Comment (flootr) [reply client/state/user-settings/actions.js]: That should already be covered. Only the `language` attribute is special because of its relation to `locale_variant`. While testing this I noticed that `i18n_empathy_mode` and `use_fallback_for_incomplete_languages` was missing from `INTERFACE_FIELDS` so I added them in https://github.com/Automattic/wp-calypso/pull/49760/commits/b5cf6150ae2752ae0d6f39d832d13001f90ce9f3

**Comment by flootr** [comment]
@getdave and @mmtr would you mind having another look whether your recent changes in `me/account` still work as expected?

File: client/me/account/main.jsx [hunk 11]
```diff
@@ -711,7 +724,9 @@ const Account = createReactClass( {
 	},
 
 	handleSubmitSuccess( response, formName = '' ) {
-		this.props.markSaved && this.props.markSaved();
+		if ( ! this.hasUnsavedUserSettings( [].concat( ACCOUNT_FIELDS, INTERFACE_FIELDS ) ) ) {
+			this.props.markSaved && this.props.markSaved();
```
Comment (tyxla) [inline client/me/account/main.jsx]: I guess we no longer need the `this.props.markSaved &&` check, or do we?

**Review by tyxla — COMMENTED** [review]
I don't see any notices when saving. This seems like a regression - in production, there are notices when saving the forms.

**Comment by mmtr** [comment]
> @getdave and @mmtr would you mind having another look whether your recent changes in `me/account` still work as expected?

Verified it still works as expected! It even fixes this issue: https://github.com/Automattic/wp-calypso/issues/49591

However, as @tyxla mentioned, success notices are not longer shown after updating the settings.

File: client/me/account/main.jsx (hunk 11 above)
Comment (flootr) [reply client/me/account/main.jsx]: removed in https://github.com/Automattic/wp-calypso/pull/49760/commits/3577e3b701189a8c9f908fbb170e61bc9f26b78a

**Comment by flootr** [comment]
> I don't see any notices when saving. This seems like a regression - in production, there are notices when saving the forms.

Should be fixed via https://github.com/Automattic/wp-calypso/pull/49760/commits/ef137d5527ea95c6d50b10f4e8b2f2e586bdc6e5

File: client/me/account/main.jsx [hunk 12]
```diff
@@ -98,29 +108,28 @@ const INTERFACE_FIELDS = [
...
 	},
 
 	componentDidMount() {
 		debug( this.constructor.displayName + ' component is mounted.' );
-		this.props.userSettings.getSettings();
 		this.debouncedUsernameValidate = debounce( this.validateUsername, 600 );
 	},
 
+	componentDidUpdate() {
+		if ( ! this.hasUnsavedUserSettings( [].concat( ACCOUNT_FIELDS, INTERFACE_FIELDS ) ) ) {
```
Comment (tyxla) [inline client/me/account/main.jsx]: Nit: is there any difference between `[].concat( A, B )` and `A.concat( B )`? Do we earn anything by starting with the empty array first?

File: client/me/account/main.jsx [hunk 13]
```diff
@@ -711,9 +723,11 @@ const Account = createReactClass( {
 	},
 
 	handleSubmitSuccess( response, formName = '' ) {
-		this.props.markSaved && this.props.markSaved();
+		if ( ! this.hasUnsavedUserSettings( [].concat( ACCOUNT_FIELDS, INTERFACE_FIELDS ) ) ) {
```
Comment (tyxla) [inline client/me/account/main.jsx]: Same nit question as above.

**Review by tyxla — APPROVED** [review]
Looks good and works well to me. Nice work @flootr!

File: client/me/account/main.jsx (hunk 12 above)
Comment (flootr) [reply client/me/account/main.jsx]: The latter is probably better because it avoids the creation of an empty array. Changed it here https://github.com/Automattic/wp-calypso/pull/49760/commits/66019a4b5e227f79fb9b0a826b1336c5a655c5b7.
