### PR TITLE
Fix Undo Notice on Menu Delete

### LINKED ISSUE #3379: Menus: Cannot undo menu deletion
To reproduce
* Delete a menu
* In the notice that appears, click 'Undo'
* You'll get a JS error in your console, complaining that `close is not a function`
* The menu is _not_ undeleted!

The relevant line is https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/menus/menu-delete-button.jsx#L33. Note that this code hasn't changed in quite a while, so maybe something's funky with `notices` (not?) passing `closeFunction` as the second argument to `onClick` [here](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/menus/menu-delete-button.jsx#L52) as it's [supposed to](https://github.com/Automattic/wp-calypso/tree/master/client/notices#onclick)?

Pinging @artpi since #1105 looks kinda related... :-)

### PR DESCRIPTION
**Pull request by georgeh**
This fixes #3379 

After deleting a menu, the undo notice was not working because it was expecting a close method from notices. The solution is to store the notice so that we can tell notices to remove it when undo-ing.

The root cause is that notices isn't sending the close function to the onClick handler ([per the documentation](https://github.com/Automattic/wp-calypso/tree/master/client/notices#onclick)), but I couldn't find where that was being used or any history of that close function being sent. This was the only instance of it being used I could see. ~~I wasn't sure if the documentation was wrong or the implementation, so my first pass is to work around the discrepancy. If someone more familiar with notices can comment I would prefer to implement the close function instead of this workaround.~~

Update: I've changed the fix to add a close function to notices, which will get the code in line with the documentation and make it easier to manage notices.

@ockham @nb please take a look

Testing procedure: delete a menu and click the undo notice that appears. Confirm that the menu you deleted is back and no script errors are triggered.

### CODE REVIEW

**Comment by georgeh** [comment]
My initial fix was to add the close functionality to the delete button, but after thinking some more I'm going to add the close function argument to the notice's `onClick` handler. That way it's simple to use in the future and keeps notice-management out of the menu delete button. I'll have an update PR in a bit.

File: client/notices/index.js [hunk 1]
```diff
@@ -37,14 +37,20 @@ module.exports = {
...
 			persistent: options.persistent
 		};
 
+		if ( 'function' === typeof options.onClick ) {
+			const closeFn = this.removeNotice.bind( this, noticeObject );
+			noticeObject.onClick = ( event ) => {
+				return options.onClick( event, closeFn );
+			}
+		}
+
```
Comment (nb) [inline client/notices/index.js]: I agree this fix makes a lot more sense. One small thing – the asymmetry of setting the option is worrying me. `onClick` is a strange exception, being set outside of the object literal. Can we do something about this?

Comment (georgeh) [inline client/notices/index.js]: I was able to move the onClick facade to inside the object declaration by getting rid of the references to `this`

File: client/notices/index.js [hunk 2]
```diff
@@ -11,7 +11,7 @@ var list = { containerNames: {} };
 Emitter( list );
 var delayedNotices = [];
 
-module.exports = {
+const notices = module.exports = {
```
Comment (ockham) [inline client/notices/index.js]: This looks a bit awkward -- you might consider doing it in two steps (define the const first, export it later).

File: client/notices/index.js [hunk 3]
```diff
@@ -37,7 +37,12 @@ module.exports = {
 			container: container,
 			button: options.button,
 			href: options.href,
-			onClick: options.onClick,
+			onClick: ( event ) => {
+				if ( 'function' === typeof options.onClick ) {
```
Comment (ockham) [inline client/notices/index.js]: Recommended it is, Yoda style with WordPress. [Not so much](https://github.com/Automattic/wp-calypso/blob/master/docs/coding-guidelines/javascript.md#yoda-conditions), with Calypso.

**Comment by ockham** [comment]
Looks good, and tests well. (Well, it's probably still not exactly aesthetic, but that's largely due to how that file is organized.) :+1:

**Comment by georgeh** [comment]
@ockham Thanks for the tips! I made the changes you suggested, rebased against master and squashed my commits.

**Comment by nb** [comment]
Thanks, @georgeh, works great. Rebased, and merging.

**Comment by artpi** [comment]
I was just testing it and debugging!
Thanks @georgeh !
@nb , you beat me to it :D!
