### PR TITLE
Help: Provide Link to User's Site in Forum Post

### LINKED ISSUE #16015: Support contact form: Add site-selector for free users
#### Steps to reproduce
1. Log in as an account that owns an upgrade plan
2. Navigate to https://wordpress.com/help/contact
3. Note that contact form contains a site picker so user can indicate which site they need help with
4. Next log in as an account that owns no upgrades
5. Navigate to https://wordpress.com/help/contact

#### What I expected
To still see a site picker to select which site I need help with.

#### What happened instead
No site picker is visible for free account even if account owns multiple sites. Instead, the primary site is automatically indicated in the forums as the site the user needs help with, which is not always accurate and leads to delays in helping the users.

#### Screenshot / Video
Paid user:
help_e28094_wordpress_com

Free user:
help_e28094_wordpress_com1

#### Context / Source

Change requested by forum moderators and volunteers in 852573-f and 848339-f

cc @dllh

### LINKED ISSUE #16016: Support contact form: add information for non-WPCOM users seeking support
#### Steps to reproduce
1. Log in as an account that doesn't own any upgrades, and which only has a Jetpack-connected site
2. Visit https://wordpress.com/help/contact
3. Submit a support ticket

#### What I expected
For the support ticket to be submitted somewhere I can get help with my site

#### What happened instead
My request posted to the WordPress.com support forums where volunteers are telling me they're unable to help me and I should go post to a different forum.

#### Context / Source

Based on feedback from forum moderators and volunteers in 852573-f and 848339-f

Self-hosted site owners post in the WordPress.com forums daily seeking help with their self-hosted WordPress sites, but the volunteers there lack the knowledge, and staff lack the access needed to help them, so they are told to post in the WordPress.org forums instead. This is frustrating for forum volunteers and for the users.

Would it be feasible to add copy to the contact form forewarning self-hosted users they're in the wrong place to get help with their site? A further enhancement could even add a selector for unpaid users needing help with our other products, Jetpack and WooCommerce as well to get them to the correct support contact forms for those products.

Could possibly be addressed along with #16015 if a prompt could be triggered upon site selection.

cc @dllh and also @notnownikki in case the docs smart search could somehow be leveraged to address this.

### LINKED ISSUE #38280: Support contact form: No "Site I need help with" indicated for free users
Related to #16015

When free users submit a support request via https://wordpress.com/help/contact, one of two things happen: They get routed to our Expert User support using the service, DIrectly (90% of support requests currently), or it gets posted to https://en.forums.wordpress.com/, with the account's primary site automatically indicated as the site they need help with, and the tag `wpcomhelp` added to the thread.

As of Friday we've noticed a sharp increase of forum threads being created in this way where the primary site is no longer included, even though the user owns a WordPress.com or Jetpack-connected site that is correctly set as the primary site in the account. This makes it difficult to provide support, as there's nothing indicating to volunteers what site someone needs help with, and requires staff to access our internal tools to see what sites a user owns, leading to extra back and forth communication to confirm the nature of the issue and sites involved.

#### Steps to reproduce
1. Log into an account only owning sites on the free plan (I can reliably replicate this on the test account with the username `boogeedeeboo`
2. Go to the support contact form at https://wordpress.com/help/contact
3. Provided the Submit button says "Ask in the forums", fill out the title and content fields and submit. (If the button lets you submit a ticket, it means the user is being rerouted to Directly support. I'm not sure how to force the request to be routed to the forums)
4. Check the post that is created for the user in the forums.

#### What I expected
For the user's primary site to be indicated as the "The site I need help with is:"

#### What happened instead
No site is indicated.

#### Screenshots

WordPress_com

Topic__Help___WordPress_com_Forums

#### Additional info

Some time ago we requested in #16015 that a site selector be added to that form for free users, as one already appears for paid users using the same form - users don't always want help with their primary site, leading to confused follow-ups in the forums as to why that site is being indicated in their support request.

However, since that issue was created the pop-up support contact form has also been introduced. Instead of using the API to create a new forum thread, that form simply has a button that sends the user directly to the forums to create their thread there instead.

WordPress_com

I wonder if it wouldn't be better if the form at https://wordpress.com/help/contact behaved in the same way for users being routed to the forums rather than to Directly. That would make for a consistent experience across the two contact options, make it clear to the user that they're posting in a public support forum (as they don't always realise that), and give them the ability to select the correct site they need help with via the forum's own submission form at https://en.forums.wordpress.com/?new=1

#### Context / Source

This issue was discovered by team Chiron over the weekend.

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

* When a user submits a post to the Forums, ensure that their URL is included. It also achieves the broader request made by @supernovia in https://github.com/Automattic/wp-calypso/issues/38280#issuecomment-567108997

#### Testing instructions

The way this is supposed to work is based on the number of sites which the user owns. You can compare the flows below:

| No Site                                                                                                                                                               | One site                                                                                                                                                              | Multiple sites                                                                                                                                                        |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Screenshot 2021-05-18 at 19 43 20 | Screenshot 2021-05-18 at 19 14 38 | Screenshot 2021-05-18 at 19 35 52 |

When a user enters the URL, it also performs some quick checks:

- If the site is a WordPress.com one owned by another account, it provides a link to the Account Recovery page since it can't be dealt with in the forums.
- If the site is not a WordPress.com one, and it's not connected with Jetpack, it provides a warning of that.

| Screenshot 2021-05-20 at 19 29 57 | Screenshot 2021-05-20 at 19 29 43 |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|

Depending on the options, one of the following messages will be included at the end of the Forums post:

- I don't have a site linked to this WordPress.com account
- I don't have a site with WordPress.com yet (different to the term above due to topics relating to Account Recover)
- The site I need help with is x.
- The site I need help with is x. This site is not linked to my WordPress.com account.

**Note:** If the site is self-hosted, a message either saying "It is not hosted by WordPress.com, but it is connected with Jetpack" or "It is not hosted by WordPress.com or connected with Jetpack" will be included too. This should save volunteers from having to manually check each blog, which can quickly become tiresome.

This also introduces an option to hide the URL in the Forums by setting it as an email; it'll automatically be hidden in the Forums due to this. You can see these changes in action below: https://wordpress.com/forums/topic/testing-please-ignore-apologies/

Screenshot 2021-05-20 at 19 43 49

@supernovia @kokkieh I'd be really grateful for any feedback which you could provide about this. :) 

cc @jsnajdr 

Fixes #38280 
Fixes #16015
Fixes #16016

### CODE REVIEW

File: client/me/help/help-contact/index.jsx [hunk 1]
```diff
@@ -256,15 +256,36 @@ class HelpContact extends React.Component {
...
 		this.recordCompactSubmit( 'forums' );
 
+		let blogHelpMessage = translate( "I don't have a site linked to my WordPress.com account yet" );
+
+		if ( userDeclaresNoSite ) {
+			blogHelpMessage = translate( "I don't have a site with WordPress.com yet" );
+		}
+
+		if ( site || userDeclaredUrl ) {
+			blogHelpMessage = translate( 'The blog I need help with is %(siteUrl)s.', {
```
Comment (Aurorum) [inline client/me/help/help-contact/index.jsx]: By the way, I think that "site" is the preferred reference over "blog", but this language is identical to the one used in the Forums already when a thread is made there so I'm just copying that.

**Comment by supernovia** [comment]
Oh my goodness! Thank you!

**A few questions on the no-site form:**
- Does it recognize and handle Jetpack / Atomic sites? Atomic sites would need fast attention especially. Jetpack sometimes needs staff attention
- _just a wish:_ Can we include a message about .org / other accounts?  Something along these lines; so if you're up for including a message we can refine it:

> "If you have a WordPress site but do not see it here, you might have a different account with us, or it might not be [hosted on our services](https://wordpress.com/support/com-vs-org/). If you're not sure, share your question with a link, and we'll point you in the right direction!"

And if you _really_ want to feel like a genie in a bottle for us, my only other ask is an option to let the site link be hidden, since people sometimes don't want to share their site address because of privacy reasons. Lately I've been telling them if they'll type it like this `hidden@sitename.com` it will show up for staff, but not in public.

File: client/me/help/help-contact/index.jsx (hunk 1 above)
Comment (supernovia) [reply client/me/help/help-contact/index.jsx]: I would go with site, FWIW

**Comment by supernovia** [comment]
Quick suggestion on the language for the one-site option, or checkmark for the multi-site option:

> This isn't the site which I need help with 

could be

> I need help with a different site

**Comment by Aurorum** [comment]
Hi Velda, thank you very much!

> Does it recognize and handle Jetpack / Atomic sites? Atomic sites would need fast attention especially. Jetpack sometimes needs staff attention

From my understanding, those sites shouldn't see this form as they should be offered the ability to email or chat with support. I suppose the exception might be if a user with an Atomic site has lost access to their account, but I can't imagine that happens much or enough to justify a specific case here. Let me know if I'm misunderstanding though!

> Can we include a message about .org / other accounts? Something along these lines; so if you're up for including a message we can refine it

Yes, definitely. I think that we can do better by querying the site too and checking if it's a WordPress.com one so that users receive a tailored message - for example. 

Screenshot 2021-05-19 at 17 49 22

> And if you really want to feel like a genie in a bottle for us, my only other ask is an option to let the site link be hidden, since people sometimes don't want to share their site address because of privacy reasons. Lately I've been telling them if they'll type it like this hidden@sitename.com it will show up for staff, but not in public.

Will definitely implement this! 

I'll probably update this PR with all the changes this weekend (or maybe a little earlier).

File: client/me/help/help-contact-form/index.jsx [hunk 2]
```diff
@@ -395,6 +442,51 @@ export class HelpContactForm extends React.PureComponent {
...
+		if ( isWpComConnectedSite ) {
+			// The site is linked to WordPress.com but not appearing for the user, so they've probably lost access to the account which owns it.
+			noticeMessage = translate(
+				"%(siteName)s is linked to another WordPress.com account. If you're trying to access it, please follow our Account Recovery procedure.",
+				{
+					args: {
+						siteName:
+							siteData && siteData.name
+								? siteData.name
+								: translate( 'This site', {
```
Comment (a8ci18n) [inline client/me/help/help-contact-form/index.jsx]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **45** times:
`translate( 'This Site' )` *ES Score: 6*

**Comment by Aurorum** [comment]
@supernovia This should all be covered now!

I've been looking into your question about Jetpack and Atomic sites. Although we shouldn't need to worry about Atomic sites since they can't see this form, there is a decision to be made about how to handle Jetpack sites. Below are two notices which will appear based on the URL entered by the user.

Currently, the "your site is not hosted on our services" notice won't be displayed if the site is connected to WordPress.com (ie. a Jetpack one). I felt that some people might have genuine issues with the plugin that can only be resolved in the forum, whereas that probably isn't likely if the user's site isn't a Jetpack one. Do we want to display this notice for Jetpack sites?

| Screenshot 2021-05-20 at 19 29 57 | Screenshot 2021-05-20 at 19 29 43 |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|

We could hide the notice, but add something like "My site is X. It is a self-hosted site connected by Jetpack." to the end of the Forums message. That might save volunteers a lot of time who have to manually check each URL.

Let me know what you'd prefer. :)

**Comment by csabarakasz** [comment]
This feature is amazing! I was just thinking about something similar. Great work on this!!

**Comment by KokkieH** [comment]
Thank you for tackling this again, @Aurorum!

> Currently, the "your site is not hosted on our services" notice won't be displayed if the site is connected to WordPress.com (ie. a Jetpack one). I felt that some people might have genuine issues with the plugin that can only be resolved in the forum, whereas that probably isn't likely if the user's site isn't a Jetpack one. Do we want to display this notice for Jetpack sites?

We can help with _some_ Jetpack-related issues in the WordPress.com forums - stats issues, follower migration, issues involving the WordPress.com account specifically like disconnecting Jetpack sites - but not all, and most of the time it's better if folks contact Jetpack support directly.

So I'd err on the side of showing the notice to Jetpack users. 

But I'd also change the copy: the majority of issues aren't hosting related, and most hosts don't provide WordPress support, so exclusively referring people to their hosts might not be the best call. Something like:

> Your site is not hosted on our services. Support for your version of WordPress is provided by the WordPress.org community forums (linked there), or if the problem relates to a specific plugin or theme, contact support for that product instead...

Followed by the rest. It's more wordy (our editorial team can review the final copy once the rest of the PR is sorted out - you can add the `[Status] Editorial Input Requested` label for that), but will better direct people to the best place to get help.

**Comment by Aurorum** [comment]
Thanks @KokkieH! I've ensured that this notice displays for Jetpack users, and if they choose to submit a forum thread, people will be able to easily see if it's a Jetpack site as one of these messages will appear:

- The site I need help with is x. It is not hosted by WordPress.com, but it is connected with Jetpack.
- The site I need help with is x. It is not hosted by WordPress.com or connected with Jetpack.

I should note that it's not possible to check if the URL is a WordPress site - it might not be, so the copy needs to reflect that, which is why I avoided using "your version of WordPress" in the notice.

Screenshot of the notice:
Screenshot 2021-05-22 at 10 38 04

Text in it that would be great to get a review on:
> Your site is not hosted on our services. Support for the self-hosted version of WordPress is provided by the WordPress.org community forums, or if the problem relates to a specific plugin or theme, contact support for that product instead. If you're not sure, share your question with a link, and we'll point you in the right direction!

This PR should be ready now (unless anyone has other recommendations) but unfortunately, I don't have the ability to add labels to request an editorial review. It'd definitely be worth it though, especially for that phrase since it's trying to convey a lot in a single notice.

___

@sixhours - Hi! Since you've worked on Help a lot recently, would you know who's best suited to review this (I appreciate it's slightly larger!) or could you please add a label requesting an editorial review?

**Comment by anastas10s-afk** [comment]
Hi there, had to publicly praise you for this @Aurorum 
Stellar work, indeed, let's hope it can be merged soon!

**Comment by sixhours** [comment]
Heyyyyy! I'd be happy to give this a look, and I'm flagging it for review by other folks in Serenity. I should be able to test it this Thursday. :)

File: client/me/help/help-contact/index.jsx [hunk 3]
```diff
@@ -256,15 +257,59 @@ class HelpContact extends React.Component {
...
+
+		if ( site || userDeclaredUrl ) {
+			const siteUrl = userDeclaredUrl
+				? withoutHttp( userDeclaredUrl.trim() )
+				: withoutHttp( site.URL );
+
+			blogHelpMessage = translate( 'The site I need help with is %(siteUrl)s.', {
+				args: {
+					siteUrl: userRequestsHidingUrl
+						? translate( '[visible only to staff]' ) + ' help@' + siteUrl
```
Comment (jsnajdr) [inline client/me/help/help-contact/index.jsx:289]: How does this work? When the forum message text contains an email address prefixed with `[visible only to staff]`, then it's hidden from public and visible to forum admins?

File: client/me/help/help-contact/index.jsx [hunk 4]
```diff
@@ -256,15 +257,59 @@ class HelpContact extends React.Component {
...
+			userDeclaresNoSite,
+			userDeclaredUrl,
+			userRequestsHidingUrl,
+		} = contactForm;
+		const { currentUserLocale, translate } = this.props;
 
 		this.setState( { isSubmitting: true } );
 		this.recordCompactSubmit( 'forums' );
 
+		let blogHelpMessage = translate( "I don't have a site linked to this WordPress.com account" );
```
Comment (jsnajdr) [inline client/me/help/help-contact/index.jsx:275]: Should we really translate these messages to the user's selected language? Or should all forum posts be English?

File: client/me/help/help-contact/index.jsx [hunk 5]
```diff
@@ -256,15 +257,59 @@ class HelpContact extends React.Component {
...
+				blogHelpMessage += ' ' + jetpackMessage;
+			}
+
+			if ( userDeclaredUrl ) {
+				blogHelpMessage +=
+					' ' + translate( 'This site is not linked to my WordPress.com account.' );
+			}
+		}
+
+		const forumMessage = message + '\n\n' + blogHelpMessage;
```
Comment (jsnajdr) [inline client/me/help/help-contact/index.jsx:308]: In other support channels, e.g., when submitting a ticked with `submitKayakoTicket`, we add the "meta info" at the beginning of the message, not at the end. Let's make the message formats adhere to some convention.

File: client/me/help/help-contact-form/index.jsx [hunk 6]
```diff
@@ -175,6 +197,22 @@ export class HelpContactForm extends React.PureComponent {
...
+			// The API would reject something like "https://wp.com/slug" - it'd need to be "wp.com".
+			const url = this.state.userDeclaredUrl;
+			const query = url.includes( '://' )
+				? new URL( this.state.userDeclaredUrl ).hostname
+				: new URL( 'http://' + this.state.userDeclaredUrl ).hostname;
+
+			this.props.requestSite( query, false, true ).then( ( siteData ) =>
+				this.setState( {
+					siteData,
+				} )
```
Comment (jsnajdr) [inline client/me/help/help-contact-form/index.jsx]: In case of success, the `siteData` will be `undefined`. The promise returned from `requestSite` doesn't provide the site data.

File: client/state/sites/actions.js [hunk 7]
```diff
@@ -158,6 +159,13 @@ export function requestSite( siteFragment, forceWpcom = false ) {
 				) {
 					return dispatch( requestSite( siteFragment, true ) );
 				}
+				if ( returnError ) {
+					return dispatch( {
+						type: SITE_REQUEST_FAILURE,
+						errorCode: error.error,
+						statusCode: error.status,
+					} );
+				}
```
Comment (jsnajdr) [inline client/state/sites/actions.js]: It would be much better if `requestSite` returned a reasonable promise. I.e., resolve with site info on success, and reject with the error on failure. That would require checking all usages of `dispatch( requestSite( siteId ) ).then( ... )` and making them work with rejected promises, too.

File: client/me/help/help-contact/index.jsx (hunk 3 above)
Comment (jsnajdr) [reply client/me/help/help-contact/index.jsx:289]: Nevermind, I see this question answered in existing comments on this PR :+1:

File: client/me/help/help-contact/index.jsx (hunk 5 above)
Comment (Aurorum) [reply client/me/help/help-contact/index.jsx:308]: I'm happy to update that, but my initial reasoning was that the "meta info" already appears at the end for threads created directly in the Forums. For example, you can see that on this thread: https://wordpress.com/forums/topic/home-page-not-displaying-menu/

Because of that, I feel like changing it around might be more inconsistent or slightly jarring for volunteers. Let me know if you still think it's worth switching around though! :)

File: client/me/help/help-contact/index.jsx (hunk 3 above)
Comment (Aurorum) [reply client/me/help/help-contact/index.jsx:289]: The `[visible only to staff]` technically could be removed! I mainly just included it to ensure volunteers who aren't staff on the Forums don't get confused, but happy to exclude it instead.

File: client/me/help/help-contact/index.jsx (hunk 4 above)
Comment (Aurorum) [reply client/me/help/help-contact/index.jsx:275]: I'll check this again to be certain, but I think that depending on the user's selected language, the question will be posted in a Forum for their language, so this should be translated. For example, the French forum contains numerous threads sent from this form: https://wordpress.com/fr/forums/topic-tag/wpcomhelp/

File: client/me/help/help-contact/index.jsx (hunk 3 above)
Comment (KokkieH) [reply client/me/help/help-contact/index.jsx:289]: > How does this work? When the forum message text contains an email address prefixed with [visible only to staff], then it's hidden from public and visible to forum admins?

Not commenting on the code, but I can confirm email addresses posted in the forums are not visible to non-a8c staff. Pinging @jmdodd as well on this, as she's the expert on how things work in the forums themselves in this regard.

File: client/me/help/help-contact/index.jsx (hunk 4 above)
Comment (KokkieH) [reply client/me/help/help-contact/index.jsx:275]: If a user's account language matches a language for which we have a support forum, their requests are automatically sent to the appropriate language forum, afaik.

Public list of our non-English forums can be found at https://wordpress.com/forums/topic/forums-in-other-languages-not-english/

File: client/me/help/help-contact-form/index.jsx (hunk 6 above)
Comment (Aurorum) [reply client/me/help/help-contact-form/index.jsx]: I'll check this out again today, but from what I remember, I don't believe that there should be successful cases because that would require the user having capabilities on that site. In order for this to be called, the user needs to select a box that declares they need help with a site which they don't have capabilities on.

File: client/state/sites/actions.js (hunk 7 above)
Comment (Aurorum) [reply client/state/sites/actions.js]: I think that'd make sense, but I feel it might be a little outside the scope of this PR, especially since it's only really dealing with failures in a specific scenario and there's a risk of causing issues elsewhere by changing that.

File: client/me/help/help-contact-form/index.jsx (hunk 6 above)
Comment (jsnajdr) [reply client/me/help/help-contact-form/index.jsx]: Oh I see, in this case, we're pretty much guaranteed to see a site that is not managed by us, and get the `SITE_REQUEST_FAILURE` action returned in this case.

I tried to make `requestSite` returned promises more reasonable in #53187. If that gets landed, the `HelpContactForm` can install `.then( site => ... )` and `.catch( error => ... )` and set its local state accordingly.

File: client/state/sites/actions.js (hunk 7 above)
Comment (jsnajdr) [reply client/state/sites/actions.js]: > I feel it might be a little outside the scope of this PR

That's true, it's complex enough to deserve its own PR. I just created #53187 for that.

File: client/me/help/help-contact/index.jsx (hunk 4 above)
Comment (jsnajdr) [reply client/me/help/help-contact/index.jsx:275]: What if I submit a question in a language that doesn't have a dedicated forum? In Czech, for example, the Help form would be localized. But will there be anyone to undestand my question? Does it happen in practice?

File: client/me/help/help-contact/index.jsx (hunk 5 above)
Comment (jsnajdr) [reply client/me/help/help-contact/index.jsx:308]: I just wanted to point out that other support methods format the message differently. I don't really know what's right for this situation. Maybe @KokkieH and @supernovia will have more qualified opinions about this.

File: client/me/help/help-contact/index.jsx (hunk 4 above)
Comment (KokkieH) [reply client/me/help/help-contact/index.jsx:275]: For languages that we don't have a forum in, it would go to the English forum, and there we'll use Google Translate to help the user.

This is consistent with paid support as well - in the languages we do offer localized support, people get routed to the support queue for their specific language, otherwise their request goes into the English queue.

File: client/me/help/help-contact/index.jsx (hunk 5 above)
Comment (KokkieH) [reply client/me/help/help-contact/index.jsx:308]: This is for the "The blog I need help with is..." section, correct?

In the forums that has always been appended at the end of the first message, both for threads created directly in the forums, and for threads created via the contact form before it stopped happening without any apparent explanation two years ago, as reported in #38280

File: client/me/help/help-contact-form/index.jsx (hunk 6 above)
Comment (supernovia) [reply client/me/help/help-contact-form/index.jsx]: >  In order for this to be called, the user needs to select a box that declares they need help with a site which they don't have capabilities on.

This is over my head so I'm not sure I understand the implications, but I do want to point out people will frequently ask for help with a site they're not connected to (like if they are logged into the [wrong account](https://wordpress.com/forums/topic-tag/other-user/), or are struggling with [account recovery](https://wordpress.com/forums/topic-tag/account-recovery/)).

Ultimately I hope folks can share a site link even if they are in the wrong account, and even if it's .org (or wix for that matter), but that they'll have a heads up.

Comment (Aurorum) [reply client/me/help/help-contact-form/index.jsx]: > Ultimately I hope folks can share a site link even if they are in the wrong account, and even if it's .org (or wix for that matter), but that they'll have a heads up.

Just to be clear, both of these should happen, and the site link will still be included! :)

Comment (supernovia) [reply client/me/help/help-contact-form/index.jsx]: Awesome. THANK YOU!

**Review by sixhours — COMMENTED** [review]
👋 Hey hey @Aurorum ! Thanks so much for tackling this! It looks great to me; I tested with all account types and got the expected results. 

I have some minor UI/UX feedback, but I don't want to hold this up or add unnecessary complexity, just food for thought.

It feels odd to me to have the URL privacy option split from the URL selection options, but I can see why having two checkboxes in a row would look weird/confusing. I also found it a little awkward that I can't "select" my site when I only have one; it feels like the copy is asking me to choose, but there's no way to actually select my single site. 

Which got me thinking, what if the site picker was a dropdown with an option at the end "I need help with a different site", which when selected would let the text input appear. Beware, expert-level mockup coming at ya:

Screen Shot 2021-05-28 at 10 57 47 AM

Again, food for thought, not a blocker. Happiness may also have thoughts. :) 

Noticed a potential color annotations issue that is maybe not specific to this PR; the selected menu item has a white gradient:

Screen Shot 2021-05-28 at 11 12 33 AM

**Comment by Aurorum** [comment]
Thank you for looking at this @sixhours!

> It feels odd to me to have the URL privacy option split from the URL selection options, but I can see why having two checkboxes in a row would look weird/confusing.

I wasn't sure about this either! In the end, I opted to put it at the end because it felt like more of a minor thing since it's an optional box, but I'm happy to move it up if that's the preferred location.

> I also found it a little awkward that I can't "select" my site when I only have one; it feels like the copy is asking me to choose, but there's no way to actually select my single site.

The copy could always be updated for cases of a single site - how about something like _Is this the site which you need help with?_

It might still feel a little strange given that there's also a box which says "I need help with a different site", but I agree the present scenario feels more odd.

> What if the site picker was a dropdown with an option at the end "I need help with a different site", which when selected would let the text input appear

I think this is a good idea! My only concern would be if people unintentionally miss it; I think that with a checkbox, there is effectively a guarantee that people will be submitting the right information to the Forums and less risk of it being unintentionally missed. That being said, if it's a better user experience and only a small number of users end up selecting the wrong site, it might not be a big deal. Just my thoughts anyway! :)

> Noticed a potential color annotations issue that is maybe not specific to this PR; the selected menu item has a white gradient

Yeah, it doesn't seem like this is caused by styles on the Help section so probably an issue for another PR. It seems to be triggered by the `is-nav-unification` body class.

**Comment by Aurorum** [comment]
The merging of Automattic/jetpack#19917 means that the only previous issue (where a user who owns a WP.com Atomic site _and_ lost access to their account would falsely be informed their site is a WP.org one) should be fixed once that takes effect.

**Comment by supernovia** [comment]
> My only concern would be if people unintentionally miss it; I think that with a checkbox, there is effectively a guarantee that people will be submitting the right information to the Forums and less risk of it being unintentionally missed.

Before this bug that had people select no site at all, I remember hearing at least once or twice per day "Not that site! I don't know how that got selected." 

Being possessed myself of a brain that tends to skim past details or mess up forms sometimes, I get that.

**Comment by Aurorum** [comment]
That's definitely understandable - in that case, I'm guessing that it'd probably be best to avoid including the "I need help with a different site" option within the Site Selector itself?

File: client/state/sites/actions.js (hunk 7 above)
Comment (jsnajdr) [reply client/state/sites/actions.js]: @Aurorum I merged #53187 today and I see you already merged `trunk` 🙂 This PR still does a trivial whitespace change in `client/state/sites/actions.js`. Would be nice to clean that up.

Comment (Aurorum) [reply client/state/sites/actions.js]: Testing this again, and I think there's a couple more tweaks needed to make this work with #53187 too. I'll try and fix those and then fix up the whitespace at the same time. :)

Comment (Aurorum) [reply client/state/sites/actions.js]: @jsnajdr Should all be working now - please let me know if there's any remaining issues! Thanks for working on #53187 too! :)

**Review by sixhours — APPROVED** [review]
I don't want to hold this up; it's working well for me. :D

**Comment by supernovia** [comment]
I've had a full plate for the past few days but am excited to hop back in and see where this is going -- who can squash and merge this?

**Comment by supernovia** [comment]
I've been thinking and thinking on this, sorry again I've been away from it so long!

> Your site is not hosted on our services. Support for the self-hosted version of WordPress is provided by the WordPress.org community forums, or if the problem relates to a specific plugin or theme, contact support for that product instead. If you're not sure, share your question with a link, and we'll point you in the right direction!

I'm wondering whether we might still run into cases where the person is indeed hosted here but the other checks aren't working (like if Jetpack is disconnected, for example, or perhaps even some VIP sites, which shouldn't go to the forums but likely shouldn't go to the .org forums either.)

What if we simply said this?

> This site may be a copy of WordPress with a different hosting service. [Here's the best way to find help with that.](https://wordpress.com/support/help/#linktbd) If you're not sure, though, please share your question with a link, and we'll point you in the right direction!

If we link to a support doc that explains how to get .org help (including how to find plugin support, etc), our Docs happiness engineers can manage the advice without having to send in PRs, too.

**Comment by Aurorum** [comment]
Hi! Happy to update that text and link (will do so later today) and in my view, I also think it's definitely worth adding a separate section since right now it seems to be a single paragraph hidden in a large page. Perhaps links to these in some sort of table or list would be great:

- Jetpack Support
- WooCommerce Support
- Something encouraging contacting the developers of third-party stuff
- .org forums

I do think we should be able to have confidence in these checks though. For the examples you cited, I chose not to display the .org notice at all when a Jetpack site was disconnected since it didn't really feel appropriate to direct them to the self-hosted forums, but it has been accounted for. I haven't tested a VIP site (let me know if you have a link to one and I'll give it a go!) but I suspect they probably won't see this form anyway, since I'm guessing they're offered Live Chat or Email support instead. And of course, if there's ever a case that goes through to the Forums where the check has gone wrong, it can definitely be quickly updated.

File: client/me/help/help-contact-form/index.jsx [hunk 8]
```diff
@@ -175,6 +197,22 @@ export class HelpContactForm extends React.PureComponent {
...
+			// It'd need to either be "https://wp.com" or "wp.com".
+			const url = this.state.userDeclaredUrl;
+			const query = url.includes( '://' )
+				? new URL( this.state.userDeclaredUrl ).hostname
+				: new URL( 'http://' + this.state.userDeclaredUrl ).hostname;
+
+			this.props
+				.requestSite( query )
+				.catch( ( error ) => this.setState( { errorData: error.error } ) )
+				.then( ( siteData ) => this.setState( { siteData } ) );
```
Comment (jsnajdr) [inline client/me/help/help-contact-form/index.jsx]: The order of the handlers should be reversed: `then` first, `catch` second. In the current order, the `then` handler will be called even in case of error, and will set `siteData` to `undefined`. That's the return value of the `catch` callback.

If you really want to reset `siteData` on error, it's better to do so explicitly.

File: client/me/help/help-contact-form/index.jsx [hunk 9]
```diff
@@ -269,6 +307,44 @@ export class HelpContactForm extends React.PureComponent {
 		);
 	};
 
+	/**
+	 * For the forums: check if we're dealing with a WP.com site.
+	 */
+	analyseSiteData = () => {
+		const requestData =
+			this.state.userDeclaredUrl && ( this.state.siteData || this.state.errorData );
```
Comment (jsnajdr) [inline client/me/help/help-contact-form/index.jsx]: Here `requestData` can be either the value of `this.state.siteData` or `this.state.errorData`. But both are very different data structures that have nothing in common. Or do they?

Comment (Aurorum) [reply client/me/help/help-contact-form/index.jsx]: I guess the only thing that they have common is they're both used to figure out if the site is WP.com-hosted or not. I've removed `requestData` now. :)

File: client/me/help/help-contact-form/index.jsx (hunk 8 above)
Comment (Aurorum) [reply client/me/help/help-contact-form/index.jsx]: Thanks, fixed!

**Comment by Aurorum** [comment]
@supernovia I updated the text and link to your suggested one. :)

Screenshot 2021-06-10 at 16 17 21

File: client/me/help/help-contact-form/index.jsx [hunk 10]
```diff
@@ -395,6 +488,61 @@ export class HelpContactForm extends React.PureComponent {
 			{ value: 'panicked', label: translate( 'Panicked' ) },
 		];
 
+		const analyseSiteData = this.analyseSiteData();
+		const siteData = this.state.userDeclaredUrl && this.state.siteData;
+		const siteName =
+			siteData && siteData.name
+				? siteData.name
+				: translate( 'This site', {
```
Comment (a8ci18n) [inline client/me/help/help-contact-form/index.jsx:496]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **45** times:
`translate( 'This Site' )` *ES Score: 6*

File: client/me/help/help-contact-form/index.jsx [hunk 11]
```diff
@@ -175,6 +197,22 @@ export class HelpContactForm extends React.PureComponent {
...
+			// It'd need to either be "http(s)://wp.com" or "wp.com".
+			const url = this.state.userDeclaredUrl;
+			const query = url.includes( '://' )
+				? new URL( this.state.userDeclaredUrl ).hostname
+				: new URL( 'http://' + this.state.userDeclaredUrl ).hostname;
+
+			this.props
+				.requestSite( query )
+				.then( ( siteData ) => this.setState( { siteData, errorData: '' } ) )
+				.catch( ( error ) => this.setState( { errorData: error.error, siteData: '' } ) );
```
Comment (jsnajdr) [inline client/me/help/help-contact-form/index.jsx]: It's more common to use `null` instead of empty string for cases like this. Especially for `siteData` which is an object, not a string.

**Review by jsnajdr — APPROVED** [review]
This is ready to go from my (framework) perspective. @aurorum let me know if you want to merge it now and follow up with improvements later, or want to improve it further before merging.

File: client/me/help/help-contact-form/index.jsx (hunk 11 above)
Comment (Aurorum) [reply client/me/help/help-contact-form/index.jsx]: Thanks, fixed!

**Comment by Aurorum** [comment]
Thanks @jsnajdr! I think that this should be good to merge; the only improvement that might be made is updating the anchor link on the notice when/if the support document is updated, but that shouldn't be a problem and can be easily changed in a separate PR.

File: client/me/help/help-contact-form/index.jsx (hunk 10 above)
Comment (a8ci18n) [inline client/me/help/help-contact-form/index.jsx:496]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **45** times:
`translate( 'This Site' )` *ES Score: 6*

Comment (a8ci18n) [inline client/me/help/help-contact-form/index.jsx:496]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **45** times:
`translate( 'This Site' )` *ES Score: 6*

**Comment by supernovia** [comment]
> Thanks @jsnajdr! I think that this should be good to merge; the only improvement that might be made is updating the anchor link on the notice when/if the support document is updated, but that shouldn't be a problem and can be easily changed in a separate PR.

Agreed, and as long as it's not #linktbd :D  we should be OK to go! The https://wordpress.com/support/help-support-options/ link will work just fine for now.

**Comment by Aurorum** [comment]
I've set it to https://wordpress.com/support/help-support-options/#where-should-i-go-for-support for now!

**Comment by jsnajdr** [comment]
Some e2e tests are failing, and they are very close to what this PR changes: in Inline Help:

Screenshot 2021-06-14 at 11 05 43

I'll try to fix this.

**Comment by jsnajdr** [comment]
I figured out that the Help Search card is not displayed in My Home because this branch doesn't contain changes from #53572. There was a pair of changes that changed REST API on server and rendering on client. But this branch is getting only one of the changes (backend) and therefore breaks e2e tests.

I'll merge this to `trunk` and I expect that the e2es will be green there.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6040490

Thank you @Aurorum for including a screenshot in the description! This is really helpful for our translators.

**Comment by Aurorum** [comment]
Thanks @jsnajdr and everyone else for helping get this merged! :)

I'll be keeping an eye on the forums this week looking for any issues with this, but if anyone does spot one, please feel free to let me know.

**Comment by supernovia** [comment]
I'm glad we changed the language to say the site _may_ not be hosted here. Today we ran into [a case](https://wordpress.com/forums/topic/asking-for-control-panel-link/) where someone was hosted here, but was logged into the wrong account and had an expired upgrade on the other. That's a fairly common occurrence, so we might want to adjust the language just a little bit more, but I'll see if I can get more feedback from the team first. We might need to adjust this part as well. 

>  It is not hosted by WordPress.com or connected with Jetpack. This site is not linked to my WordPress.com account.

Since these are language changes, though, I think we can send those in once we decide for sure what to say.

* Also, oddly, this user provided their site address saying it was an email address, but hid their site. 🤔  We'll have to see if users are just checking the hide site box without understanding it, but I'm guessing this one was an exception.

**Comment by Aurorum** [comment]
Thanks @supernovia, it should be possible to easily update the wording! However, I'm still keen on ensuring the checks are as accurate as possible, so would it please be possible to let me know of the URL if there's an issue where a site is marked incorrectly? 

I'm aware of an issue in https://wordpress.com/forums/topic/i-cant-figure-out-login-info, but that's a problem with `www.(URL)` being inputted - I'm about to open a PR to fix that now!

**Comment by Aurorum** [comment]
Ah, oops, just saw your edited comment! I'll take a look at that. 

PR for the other issue with [this thread](https://wordpress.com/forums/topic/i-cant-figure-out-login-info) in #53672. :)

**Comment by supernovia** [comment]
awesome! Thank you for that.

I think in cases where the plan/domain is expired, it's going to be hard to tell whether the site is hosted here. We could look at the name servers, but sometimes people will be using Cloudflare or their own DNS. And we could look at /.well-known/hosting-provider for the domain, but I don't think it'd work if the domain is expired. 🤔  Hmm hmm hmm. 

> so would it please be possible to let me know of the URL if there's an issue where a site is marked incorrectly? 

Yeah, this user put it in their forum thread anyway, so it's there, and sorry for the edit there!

Re: possible changes to the language that we put at the end of the post, would it be okay if we did something like this? I want to check with my team too since there's some confusion there, but something like this might be clearer.

Hosted by WordPress.com: Unsure
Connected to Jetpack: No (accounting for www though as you said)
Connected to this account: No

**Comment by supernovia** [comment]
> Hosted by WordPress.com: Unsure
> Connected to Jetpack: No (accounting for www though as you said)
> Connected to this account: No

I am hoping to get some feedback first from the team first on this, though, and a few of them are offline for the day, so I'll let you know what we find.

**Comment by Aurorum** [comment]
> I think in cases where the plan/domain is expired, it's going to be hard to tell whether the site is hosted here.

Agreed, I can't immediately think of a solution around that.

> Re: possible changes to the language that we put at the end of the post, would it be okay if we did something like this?

Yes, that shouldn't be too hard to implement. Let me know if there's consensus for this approach and I can change it if there is!

**Comment by supernovia** [comment]
I ran into a case where a ____.wpcomstaging.com (business plan without a domain yet) was not detected as .com. We'll want to watch for those too. Sorry this detection stuff is so complex!  🙃

**Comment by Aurorum** [comment]
Ah, I forgot about those! That issue will be fixed automatically when the next Jetpack release is out (the fix relies on Automattic/jetpack#19917), but I don't really think there's a solution until then.

**Comment by supernovia** [comment]
Thank you @Aurorum !

**Comment by csabarakasz** [comment]
This new feature is amazing! So helpful! Thank you. Hats off to everyone involved. 

I am still gathering more input to provide some feedback :)

**Comment by Aurorum** [comment]
Thank you @csabarakasz!

**Comment by supernovia** [comment]
Just so you've got a heads up on what I'm hearing, it sounds like people would like to streamline what's added to the post.  I need more team feedback and might not get it til Tuesday, but perhaps something like this would work?

Site: will either show as [redacted] or as a link
Live on WP.com: yes/unknown
Connected to Jetpack: yes/unknown

If we say unknown that should make any false negatives a non-issue.

Also, I've had some feedback about allowing people to hide their site. IMO what we're seeing with hidden sites is still nowhere near the cases we previously had where people didn't provide a site link at all, but we have seen a handful of cases so far where the user "hides" their site link while also providing a link in their post. IDK, users will use, but it's something we can keep an eye on and think about for iteration.

**Comment by Aurorum** [comment]
That would work! A couple of questions to think about though:

1) Do you still want it to say "Unknown" when the site is connected to a WordPress.com account? It's a lot easier to more reliably distinguish between self-hosted ones and WP.com ones if it belongs to the user and it's connected to their account. It would just require Automattic/jetpack#19917  to take effect in order to distinguish between WP.com Atomic sites and Jetpack sites.

2) Is there a risk of "Live on WP.com" being a bit confusing more confusing than "Hosted on WP.com"? I'm mainly thinking of examples such as when the site is suspended, so might not technically be classed as live by some people. 

3) Do you want to keep some sort of message saying whether the site is linked to the user's account?

My personal feelings currently lean to "Unknown" being best in cases when it's genuinely not known (for example, currently we just assume 403 errors are private WP.com sites, but I've seen two cases where they're actually Jetpack ones) - but I'm still happy to have that for all cases instead of a "No" case. The difficulty is the odd cases which you've mentioned, such as when a domain has expired! 

I guess that a lot of people are just checking the hidden site option for the sake of it. One option might be inverting the checkbox so that it's to enable displaying the site and having the default stage as automatically checked (under the assumption that people lean more towards checking boxes rather than leaving them empty).

**Comment by supernovia** [comment]
Hi!

Re: the checkbox, let's leave it unchecked. I think a few people will still check it anyway because they're not paying attention, but I'd think most folks will leave it be. We already warn them of a longer response time. Maybe say "This option may delay help." in bold, then leaving the rest about staff being able to see it.

Re: unknown, I'd rather have "unknown" than false negatives 🤔  -- if we leave all of the logic as is, then change just the word to "no" once that Jetpack PR goes live, would that work?  If we leave it as unknown for a while, but pretend as staff that it means "no" , then at will help us spot any other cases that might show up as false negatives.

Regarding the list words, here's what my team agreed on today:

Site: [redacted] OR http://theirsite.wordpress.com <-- they do want this to link if possible
WP.com: Unknown OR Yes
Jetpack: Unknown OR Yes*
Correct Account: No OR Yes

We were going to bold these labels, too, but I think that'd be suboptimal for SEO, so we'll leave them as is.

* If we're positive and accounting for www cases we can say no on this.

**Comment by Aurorum** [comment]
Hi! That should all be fine to implement - I'll probably have it done tomorrow or Friday. :)

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6040490).

**Comment by supernovia** [comment]
> Hi! That should all be fine to implement - I'll probably have it done tomorrow or Friday. :)

Thank you so much! 🏆

**Comment by Aurorum** [comment]
PR for those changes in #54052. :) 

> they do want this to link if possible

I should note that this is possible except for when the user has requested to hide the URL, unfortunately it won't link then.

**Comment by KokkieH** [comment]
We understand it won't work for hidden addresses, yes, that's fine :)

As long as the visible ones are hyperlinked, that would already make our lives a lot easier, thank you!

**Comment by rootjosh** [comment]
I'm not seeing this as having been raised anywhere yet, but there appears to be an error in the translation/language settings. 

Example:

https://wordpress.com/forums/topic/website-not-updated-after-edition/

The staff note is displaying as:

`我需要幫助的網站是 donate.tahr.org.tw。 這個網站不是由 WordPress.com 託管，但有連結 Jetpack。`

Unsurprisingly, the user has their language set to Chinese. 

Screen Shot 2021-06-30 at 8 27 29 AM

**Comment by Aurorum** [comment]
Hi @rootjosh, is there issue here with the actual translation itself or the fact that it's not in English? 

If the latter, whenever the User's Language settings is set to a different language, the support message will currently be in that language too because it could be sent to a non-English forum (that didn't happen in this case because there isn't a Chinese Forums). That does make it a little awkward when the user types their issue in English like with the thread you linked, but my understanding is that this is intentional. 

However, is the issue here that the message should be in English when it's sent to the English forums?

**Comment by rootjosh** [comment]
No issue with the translation itself that I'm aware of (though I'm the wrong person to ask). My comment was more around the language not matching the forum.

I think ideally the message would be in English for the English forum. Actually, it should probably match whatever language a forum was set to use. Having the message be in French because a French speaker posted in the Italian forum would be weird as well. As the message isn't really FOR the user making the post, it both looks odd and is unhelpful for anyone (staff or volunteers) who might be trying to assist the user in to see the message in the user's chosen language rather than the forum's "native" language.

**Comment by Aurorum** [comment]
> I think ideally the message would be in English for the English forum. Actually, it should probably match whatever language a forum was set to use.

That makes sense, I'll work on that. :)

**Comment by Aurorum** [comment]
I've included that change in #54052! That would prevent the issue in the thread which you linked.

**Comment by supernovia** [comment]
Awesome! Thank you.

**Comment by rootjosh** [comment]
#HUGETHANKS!

**Comment by csabarakasz** [comment]
Hi there,

I wanted to check in with the website hosting check feature.

> Site: [redacted] OR http://theirsite.wordpress.com <-- they do want this to link if possible
> WP.com: Unknown OR Yes
> Jetpack: Unknown OR Yes*
> Correct Account: No OR Yes

Generally I love it! My question:

Is it still true, that basically when we see "Unknown" at the WP.com, for the majority of the cases it means the site is not WordPress.com hosted? The reason why I ask because as a volunteer, when members choose to hide the website URL, I often find myself being hesitant to answer to the OP, because I am not sure whether it is really unknown or it is a no, but we are saying unknown. As a result, I, as a volunteer, become less efficient in helping. When we used the sentence version for this, it was a little bit more clear to me, even if someone chose to hide their website URL.

> If we leave it as unknown for a while, but pretend as staff that it means "no" , then at will help us spot any other cases that might show up as false negatives.

I guess if this is still true then I can just follow the pretend the "unknown" is a basically a no method.

Thanks for the confirmation.
@supernovia

**Comment by Aurorum** [comment]
Hi @csabarakasz, from a code perspective, nothing has changed regarding the checks which determine whether a site is self-hosted or not. In almost cases, "Unknown" should be equivalent to "No". 

However, there might be a really small proportion of cases where it is actually hosted by WordPress.com. I've fixed all of the ones reported here where that happens, except https://github.com/Automattic/wp-calypso/pull/52979#issuecomment-860819683, which I don't think there's a good solution to. But that should still only be a tiny minority of cases.

**Comment by csabarakasz** [comment]
Thanks for the reply @Aurorum! 

What would be the best place to report misdiagnosed sites. Yesterday I saw one where it was recognized as a WordPress.com site even-though it wasn't. I ended up not responding to the OP because of that. In this case, the URL was visible for me. I can imagine it is possible for this to happen when the URL is hidden for us.

[Here.](https://wordpress.com/forums/topic/customizing-33/)

**Comment by Aurorum** [comment]
It's probably best to just ping me here! I'll be sure to take a look at that example tomorrow since that's definitely not working correctly - thanks for letting me know. :)

**Comment by Aurorum** [comment]
I think that I've figured out what was causing the issue with that particular site - it should be fixed by #54954! :)

**Comment by KokkieH** [comment]
@Aurorum this change has been amazing. Thank you so much for your work on this.

I have a tiny request - at the moment the site URL line is appended with a full-stop, left over from the first version where the info was indicated as sentences rather than a list. Would it be possible to get rid of that? It will just simplify things in cases where we need to highlight>copy the URL in stead of clicking it, for example when it's hidden by converting it into an email address.

**Comment by Aurorum** [comment]
Thank you! And sure thing, I've included removing that full stop as part of #54954.

**Comment by KokkieH** [comment]
Brilliant! Thank you!
