### PR TITLE
Taxonomy Manager: Improve Alignment of Count Bubble

### LINKED ISSUE #52071: Settings: Default category number bubbles need vertical alignment tweak
### Steps to reproduce the behavior

Found this while working on #50568

1. Go to Settings -> Writing -> Categories on a site that has some posts assigned to the **default** category (other categories are fine)
2. Note the vertical alignment of the number label - the number should be centered in the bubble, but it's quite a bit off:

Screen Shot 2021-04-19 at 1 47 13 PM

#### Browser / OS version

Chrome, Firefox, and Safari for Mac

#### Does this happen on simple or atomic sites or both?

Both

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Low

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

* Improves the alignment of the number inside the "Count" component when managing categories

#### Testing instructions

Visit `/settings/taxonomies/category/site` and compare the alignment of the number in the Count bubble, especially for the "Default" category. 

**Before:**
Screenshot 2021-04-19 at 19 30 51

**After:**
Screenshot 2021-04-19 at 19 30 46

cc @sixhours 

Fixes #52071

### CODE REVIEW

File: client/blocks/taxonomy-manager/list-item.jsx [hunk 1]
```diff
@@ -165,12 +165,14 @@ class TaxonomyManagerListItem extends Component {
 					) }
 				</span>
 				{ typeof term.post_count !== 'undefined' && (
-					<Count
-						ref="count"
-						count={ term.post_count }
-						onMouseEnter={ this.showTooltip }
-						onMouseLeave={ this.hideTooltip }
-					/>
+					<div className="taxonomy-manager__count">
```
Comment (sixhours) [inline client/blocks/taxonomy-manager/list-item.jsx:168]: Is it possible to apply the class to the `Count` component directly rather than adding more markup? Just curious, not a blocker :)

Comment (Aurorum) [reply client/blocks/taxonomy-manager/list-item.jsx:168]: I think that because of the `display: flex` on `.taxonomy-manager__item`, the `Count` component needs to be wrapped on in a div to resolve the misalignment - I couldn't really think of an alternative, unfortunately!

**Comment by sixhours** [comment]
Linting errors appear to be due to old code and unrelated to this PR so I think they're safe to ignore.

**Comment by sixhours** [comment]
LGTM! Thanks @Aurorum  :D
