### PR TITLE
Stats: Add additional bars to week and month charts.

### LINKED ISSUE #11377: Stats: More bars in more places (30 bars on Months & Weeks)
#### Steps to reproduce
1. Starting at URL: https://calypso.live/stats/months
2. Pick any site

#### What I expected
I'd like to see how my site did in previous seasons.

#### What happened instead
I can only view 12 months at a time on my graph, and the bars are pretty fat given the space I've got.

Quote from a user:

> The old, good stats page months view shows 30 months of data, allowing you to easily see seasonal variations. The new one? Only 12. Impossible to see seasonal variation.

#### Screenshot / Video
https://cloudup.com/cVLem8fVLPO

#### Context / Source
In a stats feedback thread, users have complained about us not showing enough data at once for months and weeks.  I've also gathered that many of our advanced users feel like the big bars are dumbing things down (the sentiment I'm sensing is that they're a bit like those legos for babies) and that we should be utilizing more of the space.  We've been addressing desktop width concerns in other issues, but I think displaying 30 bars at a time for Weeks and Months would help as well.

### PR DESCRIPTION
**Pull request by timmyc**
This branch seeks to close #11377 - by setting the number of bars in the stats chart to 30 for Days, Weeks, and Months.  By adding more periods to the weeks and months charts, users will be able to see fluctuations in traffic over time easier - something that has been requested.

__To Test__
- Visit a site stats page
- Navigate to the Week, and Months pages, note the chart now shows up to 30 entries, just like Days.

### CODE REVIEW

File: client/my-sites/stats/stats-chart-tabs/index.jsx [hunk 1]
```diff
@@ -261,16 +261,10 @@ const connectComponent = connect(
...
-			case 'day':
-				quantity = 30;
-				break;
-			case 'month':
-				quantity = 12;
-				break;
-			case 'week':
-				quantity = 13;
+			case 'year':
+				quantity = 10;
```
Comment (youknowriad) [inline client/my-sites/stats/stats-chart-tabs/index.jsx]: Is the switch necessary anymore? maybe a ternary?

Comment (timmyc) [inline client/my-sites/stats/stats-chart-tabs/index.jsx]: Kind of to your point above about performance - I figured we can keep the switch here in case we need to roll this back.
