### PR TITLE
Nav Unification: Welcome Modal - Fix Typo

### LINKED ISSUE #51869: Nav Unification: Typo in welcome modal
Missing period at end of highlighted sentence.

image

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

* Fixes a typo in the Welcome Modal

The original issue reports that there should be a full stop at the end of the sentence. While I've added that, I'm also strongly inclined to think that "account settings" should be replaced with "Account Settings". It's the name of a section, and that's consistent with some of the references elsewhere. 

https://github.com/Automattic/wp-calypso/blob/38c37bbfe35b8c741c4e346637987ddc0fb3ab59/client/blocks/inline-help/contextual-help.js#L205

Happy to change that if it's intentional though! :)

#### Testing instructions

It's probably enough to just check the code, to be honest.

Screenshot 2021-04-12 at 22 34 05

Fixes #51869 
cc @tjcafferkey, @cpapazoglou

### CODE REVIEW

File: client/blocks/nav-unification-modal/index.jsx [hunk 1]
```diff
@@ -116,7 +116,7 @@ const Modal = () => {
 							}
 							heading={ translate( 'Do even more' ) }
 							content={ translate(
-								'Advanced admin features have a new home! You can find it in your account settings'
+								'Advanced admin features have a new home! You can find it in your Account Settings.'
```
Comment (a8ci18n) [inline client/blocks/nav-unification-modal/index.jsx]: :ok: This change will be queued for retranslation. We'll use the existing translations in the meantime.

**Comment by tjcafferkey** [comment]
Thanks @Aurorum!

I am wondering if this also might be a good opportunity to link the "Account Settings" text on the second slide [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/blocks/nav-unification-modal/index.jsx#L119) in the [same way they're linked on the last slide](https://github.com/Automattic/wp-calypso/blob/trunk/client/blocks/nav-unification-modal/index.jsx#L138-L142).

**Comment by Aurorum** [comment]
Added! I thought that it should link to the page in a new tab since that way, the user won't miss the final screen as part of the modal - let me know if that should be changed!

**Review by tjcafferkey — APPROVED** [review]
LGTM Thanks for this @Aurorum! 😄

File: client/blocks/nav-unification-modal/index.jsx [hunk 2]
```diff
@@ -116,7 +116,12 @@ const Modal = () => {
 							}
 							heading={ translate( 'Do even more' ) }
 							content={ translate(
-								'Advanced admin features have a new home! You can find it in your account settings'
+								'Advanced admin features have a new home! You can find it in your {{a}}Account Settings{{/a}}.',
```
Comment (Aurorum) [inline client/blocks/nav-unification-modal/index.jsx]: Before merging, could I just ask if this should be changed? I just spotted it now, but I feel it reads a little better. 

```suggestion
								'Advanced admin features have a new home! You can find them in your {{a}}Account Settings{{/a}}.',
```

Comment (tjcafferkey) [reply client/blocks/nav-unification-modal/index.jsx]: That seems like a good update to make. If you are able to push the commit I'll re-run the tests again. Thanks for spotting that.

Comment (Aurorum) [reply client/blocks/nav-unification-modal/index.jsx]: Thanks! I updated it.
