### PR TITLE
Domains: Switching free domains require two clicks

### LINKED ISSUE #101108: Domains: Switching free domains require two clicks
### Context and steps to reproduce

Clicking for the first time on a new domain deselects the current one, but doesn't select the new one. This is also reproducible on desktop. 

https://github.com/user-attachments/assets/53a136a6-e61d-4587-ae11-f004cbe4b0ca

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Critical

### What other impact(s) does this issue have?

_No response_

### If a workaround is available, please outline it here.

_No response_

### Platform

_No response_

### PR DESCRIPTION
**Pull request by katinthehatsite**
Closes https://github.com/Automattic/wp-calypso/issues/101108

## Proposed Changes

This PR ensures that when you first select a free domain on https://wordpress.com/start and then you decide to add a different free domain, it will be added to the cart in one click instead of requiring two clicks. 

## Testing Instructions

* Pull the changes from this branch or use the Calypso Live Link below
* Navigate to https://wordpress.com/start
* Enter a domain e.g. `test`
* Select the free domain option
* Observe that it is added to a mini-cart on the right side
* Input another domain in the search field e.g. `banana`
* Select a free domain option that appears in the suggestions
* Confirm that the old free domain gets removed from the mini-cart and that the new free domain gets added there automatically (this step previously did not work and you had to click twice to add a new free domain)
* Try adding a paid domain to a cart
* Confirm that both free and paid domains remain in the cart 

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/signup/steps/domains/index.jsx [hunk 1]
```diff
@@ -247,12 +247,11 @@ export class RenderDomainsStep extends Component {
 			suggestion?.isSubDomainSuggestion
 		) {
 			if ( this.state.wpcomSubdomainSelected ) {
-				this.freeDomainRemoveClickHandler();
-			} else {
-				this.setState( { wpcomSubdomainSelected: suggestion } );
-				this.props.saveSignupStep( stepData );
+				await this.freeDomainRemoveClickHandler();
```
Comment (renatho) [inline client/signup/steps/domains/index.jsx:251]: It seems the `freeDomainRemoveClickHandler` doesn't return a promise. I suspect we'll need to adopt a different approach here.

I think we need to wait for the `setState` (we could use the second argument that is a callback) and the `saveSignupStep`, right? Or maybe we could re-write in a way that we don't call both things in a row (calling once `setState` and `saveSignupStep`)?

**Review by renatho — COMMENTED** [review]
Hi @katinthehatsite! Thanks for your PR!
I left some suggestions in the code. 😉 Let me know if you need anything.

File: client/signup/steps/domains/index.jsx (hunk 1 above)
Comment (abotic) [reply client/signup/steps/domains/index.jsx:251]: That's a nice catch!

I did some testing to figure out why this might become problematic, and I think the code needed to be changed here would be:

```js
freeDomainRemoveClickHandler = () => {
  return new Promise(resolve => {
    this.setState({ wpcomSubdomainSelected: false }, () => {
      this.props.saveSignupStep({
        stepName: this.props.stepName,
        suggestion: {
          domain_name: false,
        },
      });
      resolve();
    });
  });
};
```
And then inside handleAddDomain, update the flow to use setState's callback for proper sequencing:

```js
if (shouldUseMultipleDomainsInCart(this.props.flowName) &&
    suggestion?.isSubDomainSuggestion
) {
  if (this.state.wpcomSubdomainSelected) {
    await this.freeDomainRemoveClickHandler();
  }
  this.setState({ wpcomSubdomainSelected: suggestion }, () => {
    this.props.saveSignupStep(stepData);
  });
  return;
}
```

This way we make sure that we properly wait for the domain removal and then update the state in sequence.
What do you think @katinthehatsite @renatho?

Comment (renatho) [reply client/signup/steps/domains/index.jsx:251]: Nice, @abotic! =)

I suspect in the `freeDomainRemoveClickHandler` we'll also need an `await` in the `this.props.saveSignupStep`, right? So it only resolves the promise after the setState and the request.

But, honestly, I didn't go deeper to understand the consequences if the `saveSignupStep` doesn't happen in the expected order.

Comment (katinthehatsite) [reply client/signup/steps/domains/index.jsx:251]: Thank you for suggestions, I slightly got tricked by the `else` condition 😅  ! I ended up applying the solution from @abotic as I think it would be best for ensuring that everything happens in the correct order. Feel free to give it another test.

**Comment by abotic** [comment]
Tested and it works great!
LGTM 🚢

**Review by abotic — APPROVED** [review]

File: client/signup/steps/domains/index.jsx [hunk 2]
```diff
@@ -907,12 +906,15 @@ export class RenderDomainsStep extends Component {
 	};
 
 	freeDomainRemoveClickHandler = () => {
-		this.setState( { wpcomSubdomainSelected: false } );
-		this.props.saveSignupStep( {
-			stepName: this.props.stepName,
-			suggestion: {
-				domain_name: false,
-			},
+		return new Promise( ( resolve ) => {
```
Comment (renatho) [inline client/signup/steps/domains/index.jsx:917]: Hi @katinthehatsite!

Shouldn't we wait for the `setState` and `saveSignupStep` to make sure everything will be called in the correct order?

Something like this?

```js
	freeDomainRemoveClickHandler = () => { // I didn't test it
		return new Promise( ( resolve ) => {
			this.setState( { wpcomSubdomainSelected: false }, () => {
				this.props.saveSignupStep( {
					stepName: this.props.stepName,
					suggestion: {
						domain_name: false,
					},
				} ).then( () => {
					resolve();
				} );
			} );
		} );
	};
```
