### PR TITLE
Site Settings SEO: Fix Jetpack Redirect to General Tab

### LINKED ISSUE #5511: SEO Settings: can load the SEO page directly for Jetpack sites
Whilst you can't access the page switching sites, or picking sites, you can hit the URL directly

#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/settings/seo/yourjetpacksite.com

#### What I expected

Redirect to General Settings

#### What happened instead

SEO Settings page shown

#### Browser / OS version

Chrome OSX

### PR DESCRIPTION
**Pull request by roundhill**
Check if site is Jetpack after the component mounts.

**To test:** visit /settings/seo/`yourjetpackurl.com`. You should be redirected to the general settings. Visiting the same url with a wp.com site should load the SEO tab.

Fixes #5511

### CODE REVIEW

File: client/my-sites/site-settings/form-seo.jsx [hunk 1]
```diff
@@ -84,19 +84,26 @@ export const SeoForm = React.createClass( {
 		return stateForSite( this.props.site );
 	},
 
-	componentWillReceiveProps: function( nextProps ) {
+	componentDidMount() {
+		this.redirectJetpack( this.props.site );
```
Comment (mtias) [inline client/my-sites/site-settings/form-seo.jsx]: We tend to do redirects like this at the controller level (`my-sites/site-settings/controller.js`). There's even a `redirectToGeneral` function there for this purpose.

Comment (roundhill) [inline client/my-sites/site-settings/form-seo.jsx]: Ah, thanks for the tip! I'll refactor.

**Comment by roundhill** [comment]
Thanks @mtias, moved redirect logic to the controller in a976bd7

File: client/my-sites/site-settings/controller.js [hunk 2]
```diff
@@ -75,6 +76,12 @@ module.exports = {
 			return;
 		}
 
+		// redirect seo tab to general for Jetpack sites
+		if ( site.jetpack && endsWith( basePath, 'seo' ) ) {
```
Comment (rralian) [inline client/my-sites/site-settings/controller.js]: A cleaner way to check for the section is `( context.params.section === 'seo' )` and you can get rid of the `endsWith` dependency. When the routes are declared, the placeholders get passed into the called controller methods in the `context` object that page.js creates. So this is populated form the route here https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/site-settings/index.js#L29.

**Comment by rralian** [comment]
I think there's a cleaner approach to checking the section. But if you agree and make the change, no need to have it re-reviewed. You can just 🚢  it.

File: client/my-sites/site-settings/controller.js (hunk 2 above)
Comment (roundhill) [inline client/my-sites/site-settings/controller.js]: oh nice, I missed the `section` property. Will update 👍

**Comment by mtias** [comment]
Much better!
