### PR TITLE
Gutenframe: Check origin against site admin URL

### LINKED ISSUE #31298: Gutenberg: WordPress.com Media Modal does not appear in place of core media modal
**Describe the bug**
Edit from @gwwar:

The Core Media Library displays instead of the WordPress.com Media Library. 

To reproduce:
- Select a site with a mapped domain
- Visit /block-editor
- Click on any item that will trigger the media modal, like the feature cover block, image, or media. 

See p1552024521367100-slack-lannister

Likely the message passing isn't making it through to the parent iframe. 

cc @Automattic/lannister to follow up

**To Reproduce**
1. For an affected site
2. Click on Posts - Add
3. Try clicking on the "media modal" for any blocks like image

**Follow-up**
#1861657-zd 

#### What I expected
They expected an Insert from URL option to be available on the Media & Text Block. 
They expected the Media Library button on the same block to have more functionality, that they claim to have lost. 

#### What happened instead
Insert From URL is no longer available on Media & Text
Media Library button has reduced functionality compared to a previous version. 

#### Browser / OS version
All

#### Context / Source
 #empathy #perspective #reallife #flowsharing #anxiety #anxiety-flow #stresscase #painpoint.

#user-report

### LINKED ISSUE #31338: Gutenframe: Missing free photo library and Google Photos library
#### Steps to reproduce 

- Start with a WordPress.com site and opt-in for Gutenberg 
- Visit `example.com/block-editor/post`
- Add an image block, gallery block or click on featured image section

#### What happens instead 

There is an option at the top left, to choose from `Free photo library` or `Google photos library`

Example image from Calypso editor:

Screenshot 2019-03-10 at 11 00 03

#### What happens instead 

The `Free photo library` and `Google photos library` options are missing.

Screenshot 2019-03-10 at 11 00 19

#### Notes

I [searched a bit](https://github.com/search?q=repo%3AAutomattic%2Fwp-calypso+is%3Aissue+is%3Aopen+%22photo+library%22) but did not come across an issue for this since [introducing Gutenframe](https://github.com/Automattic/wp-calypso/pull/31196). I do see [this comment](https://github.com/Automattic/wp-calypso/issues/28960#issuecomment-448570826) about introducing this for Gutenlypso, but doesn't look to be the case for Gutenframe at the moment.

1866000-hc

### PR DESCRIPTION
**Pull request by mmtr**
Previously when we were attempting to validate the origin
for incoming messages from the Gutenberg iframe we were
assuming that site slug would represent the proper domain.

This was wrong. On sites with mapped domains we get a mismatch
with the domain and the site admin URL.

In this patch, we updated the check in order to verify that
the origin comes from the site admin URL.

This fixes an issue where the core media modal was showing
instead of the Calypso media modal because the iframe
communication was not established.

#### Testing instructions

- Select a site with a mapped domain
- Create a new post by visiting `/block-editor`
- Insert a image block
- Make sure that the Calypso Media Modal is opened

Screen Shot 2019-03-11 at 10 37 06

Fixes #31298
Fixes #31338

### CODE REVIEW

**Comment by gwwar** [comment]
Mob paired with @Automattic/lannister at our meetup

File: client/gutenberg/editor/calypsoify-iframe.jsx [hunk 1]
```diff
@@ -64,16 +64,18 @@ class CalypsoifyIframe extends Component {
 	}
 
 	onMessage = ( { data, origin } ) => {
```
Comment (dmsnell) [inline client/gutenberg/editor/calypsoify-iframe.jsx]: to make variable assignment consistent… (referring to what @obenland brought up in person)

```js
onMessage = ( { data = { action, type } = {}, origin } ) => {
	if ( type !== 'gutenbergIFrameMessage' ) {
		return;
	}

	…

	if ( 'loaded' === action ) {
		…
	}

	…
}
```
