### PR TITLE
Plugins: do not use native find

### LINKED ISSUE #6422: Jetpack Plugins page fails to load on Chrome v44 and below
#### Steps to reproduce
1. Load URL for a Jetpack site: https://wordpress.com/plugins/example.jetpacksite.com

#### What I expected
A list of installed plugins, which is what I see on Chrome v45 and up

#### What happened instead
A pulsing list of placeholders and the following error in the JS console:

```
Uncaught TypeError: config(...).find is not a function
plugins.e524d43eb45d4219cd6c.min.js:4 Uncaught TypeError: config(...).find is not a functiongetWporgLocaleCode @ plugins.e524d43eb45d4219cd6c.min.js:4fetchPluginInformation @ plugins.e524d43eb45d4219cd6c.min.js:4(anonymous function) @ plugins.e524d43eb45d4219cd6c.min.js:4(anonymous function) @ build-production.6961e55e1583221eb0c6.min.js:74store.dispatch @ build-production.6961e55e1583221eb0c6.min.js:49(anonymous function) @ build-production.6961e55e1583221eb0c6.min.js:74(anonymous function) @ plugins.e524d43eb45d4219cd6c.min.js:8addWporgDataToPlugins @ plugins.e524d43eb45d4219cd6c.min.js:8getPluginsFromStore @ plugins.e524d43eb45d4219cd6c.min.js:8getPluginsState @ plugins.e524d43eb45d4219cd6c.min.js:8refreshPlugins @ plugins.e524d43eb45d4219cd6c.min.js:8EventEmitter.emit @ build-production.6961e55e1583221eb0c6.min.js:14SitesList.sync @ build-production.6961e55e1583221eb0c6.min.js:49(anonymous function) @ build-production.6961e55e1583221eb0c6.min.js:49(anonymous function) @ vendor.6961e55e1583221eb0c6.min.js:4onload @ build-production.6961e55e1583221eb0c6.min.js:34resolve @ build-production.6961e55e1583221eb0c6.min.js:35onmessage @ build-production.6961e55e1583221eb0c6.min.js:35
```

#### Browser / OS version
Seen in Windows and Linux with Chrome v44 and v43

#### Screenshot / Video

screen shot 2016-06-29 at 1 36 40 pm

#### Context / Source
#automated-testing  -- Since June 14th our CI system has been running a new version of Chrome, which doesn't have this problem.  Today I had to switch back to v43 in order to solve a different issue, and this problem popped up.  So it could've been broken at any point since then.

### PR DESCRIPTION
**Pull request by gwwar**
This fixes #6422 to use lodash find instead of native find, which is not supported in all browsers. I've also updated a native includes to use lodash includes.

## Testing Instructions
In IE:
- Navigate to http://calypso.localhost:3000.com/plugins/example.jetpacksite.com
- Plugins should load, instead of infinite placeholders.

cc @hoverduck @yoavf @jblz 

Test live: https://calypso.live/?branch=fix/plugins-find

### CODE REVIEW

File: client/lib/wporg/index.js [hunk 1]
```diff
@@ -24,7 +27,7 @@ function getWporgLocaleCode( ) {
 		wpOrgLocaleCode;
 
 	currentLocaleCode = i18n.getLocaleSlug();
-	wpOrgLocaleCode = config( 'languages' ).find( function( language ) {
+	wpOrgLocaleCode = find( config( 'languages' ), function( language ) {
```
Comment (aduth) [inline client/lib/wporg/index.js]: Best to get the fix in place first-and-foremost, but worth pointing out that Lodash's find has a convenient shorthand for this technique:

```js
wpOrgLocaleCode = find( config( 'languages' ), { langSlug: currentLocaleCode } );
```

**Comment by aduth** [comment]
👍  Confirmed working in IE11, Chrome latest.

File: client/lib/wporg/index.js (hunk 1 above)
Comment (gwwar) [inline client/lib/wporg/index.js]: Thanks, updated in c7492d1
