### PR TITLE
Gutenboarding: Enable frankenflow for non-authenticated users

### LINKED ISSUE #39170: Gutenboarding: "create my site" doesn't work when not logged in
When I'm not authenticated (e.g. in incognito), I cannot press "create my site" button without an error in console:

> Uncaught Error: AuthorizationRequiredError: An active access token must be used create a new Site for the User.

Depending on difficulty, we could either:
- Show signup form in Calypso
- Just not support this when authenticated but show e.g. `window.alert( 'Please sign up first before testing this flow' );`

### PR DESCRIPTION
**Pull request by razvanpapadopol**
Fix #39170 
Fix partial #37849 (reset data when creating a site)

New user demo: https://cloudup.com/cs5SErtrWZA

#### Changes proposed in this Pull Request
* Use Gutenboarding passwordless signup in frankenflow for non-authenticated users
* Reset Gutenboarding data from store after successfully creating a site.
* Replace **Create my site** button with a loading message while creating the site

#### Testing instructions

* When I'm not authenticated (eg: incognito) I should be able to go through Frankenflow starting in `/gutenboarding`
* Once the site is being created, the local Gutenboarding data is resetted

#### Follow up idea

* Use a dedicated screen while creating a site. Right now it is `/design`

### CODE REVIEW

**Comment by razvanpapadopol** [comment]
Thanks, @Addison-Stavlo for thorough testing and review. We'll address the clunky behaviour when  implementing issue https://github.com/Automattic/wp-calypso/issues/39246 and you're right, data resetting should be done at the moment when the site creation is confirmed. I suggest we implement it the proper way when chaining all the pieces together in https://github.com/Automattic/wp-calypso/issues/39096

**Comment by razvanpapadopol** [comment]
Rebased and added comments linking to related PRs.

File: client/landing/gutenboarding/components/header/index.tsx [hunk 1]
```diff
@@ -81,6 +87,23 @@ const Header: FunctionComponent< Props > = ( { prev } ) => {
 		siteVertical,
 		...( siteUrl && { siteUrl } ),
 		...( selectedDesign?.slug && { theme: selectedDesign?.slug } ),
+		onCreate: resetOnboardStore,
```
Comment (Addison-Stavlo) [inline client/landing/gutenboarding/components/header/index.tsx]: Nice, this seems to work well.  =)

File: client/landing/gutenboarding/utils.ts [hunk 2]
```diff
@@ -52,6 +55,7 @@ export function createSite( { siteTitle, siteUrl, theme, siteVertical }: CreateS
 		}
 
 		const siteSlug = urlToSlug( untrailingslashit( url ) );
+		onCreate();
```
Comment (sirreal) [inline client/landing/gutenboarding/utils.ts]: I expect this to be rather short lived (https://github.com/Automattic/wp-calypso/pull/39055 will replace it), but generally I'd prefer to return the promise as opposed to adding an `onCreate` parameter.

Fine to leave this here since it's temporary.

**Comment by Addison-Stavlo** [comment]
responding to @sirreal 
> The route seems like a good place to track the intent to create a site rather than the store. With that in mind, some of the onboarding store changes here don't seem necessary.

I think if we are going to go the `<Route>` route, we may need some store params as well.  My initial concern with using the Route is that anyone can visit a route directly or navigate 'back' to it.  So the component on the route will need to be checking data from the store to determine if it should be handling site creation or redirecting the user to a different step.  With that in mind, having something like `isCreatingSite` set true here when we push to Route.CreateSite may be helpful?

> this isn't blocking, and we can move ahead, but I'd expect some of this to be replaced

I agree.  Some things may need to be updated/replaced, but I think this is good to move ahead and we can re-adjust the create-site step from there.
