### PR TITLE
Resolve the capitalizing issue  at Manage >> Settings #35292

### LINKED ISSUE #35292: Manage > Settings: Section Headings and Options - Capitalization Inconsistencies
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/
2. Various sections, have inconsistent capitalization structures on titles and settings

#### What I expected
Consistent formatting across section titles/settings.

#### What happened instead
Inconsistent formatting across section titles/settings.

#### Screenshot / Video

WritingSettings

#### Context / Source
 #dogfooding 

It seems that the inconsistency might create a poor brand experience.

### PR DESCRIPTION
**Pull request by spraveenitpro**
#### Changes proposed in this Pull Request

This fix aims to resolve the Capitalization Inconsistencies at `Manage > Settings: Section Headings and Options`

#### Testing instructions

* Goto Calypso dashboard: `Manage >> Settings` and check for capitalization inconsistencies

Fixes #35292

### CODE REVIEW

File: client/my-sites/site-settings/composing/publish-confirmation.jsx [hunk 1]
```diff
@@ -50,7 +50,7 @@ class PublishConfirmation extends Component {
 		if ( showPublishFlow ) {
 			return (
 				<FormFieldset>
-					<FormLabel>{ translate( 'Show publish confirmation' ) }</FormLabel>
+					<FormLabel>{ translate( 'Show Publish Confirmation' ) }</FormLabel>
```
Comment (a8ci18n) [inline client/my-sites/site-settings/composing/publish-confirmation.jsx]: :disappointed: 27 existing translations will be lost with this change.

File: client/my-sites/site-settings/form-writing.jsx [hunk 2]
```diff
@@ -118,7 +118,7 @@ class SiteSettingsFormWriting extends Component {
 					isSaving={ isSavingSettings }
 					onButtonClick={ handleSubmitForm }
 					showButton
-					title={ translate( 'Content types' ) }
+					title={ translate( 'Content Types' ) }
```
Comment (a8ci18n) [inline client/my-sites/site-settings/form-writing.jsx]: :ok: This change is safe, we'll keep the existing 42 translations.

**Comment by arunsathiya** [comment]
Actually, I am adding the `Needs review` tag back again. I am unaware of how the translations may be affected, so, let's best waiting for @Automattic/i18n team to advise.
