### PR TITLE
Strip leading and trailing whitespace from domain contact fields on blur

### LINKED ISSUE #48305: Checkout: Contact information is not sanitized
#### Steps to reproduce

1. Add a domain to the cart.
2. In the "Contact information" step, add a space at the end of the field. Or put _just_ spaces in the field.

#### What I expected

The call to `https://public-api.wordpress.com/rest/v1.2/me/domain-contact-information/validate` to contain fields that were sanitized - most importantly, white space trimmed.

#### What happened instead

Field with dangling whitespace or containing _only_ whitespace were submitted.

#### Screenshot / Video

Screenshot 2020-12-14 at 11 31 06
Screenshot 2020-12-14 at 11 31 16

#dogfooding #user-report

### PR DESCRIPTION
**Pull request by nbloomf**
#### Changes proposed in this Pull Request

* Trim whitespace in `ManagedContactDomainFormFields` on blur.

#### Testing instructions

* Enter checkout with a domain in your cart.
* At the contact details step, first enter a complete and valid set of details if it is not auto-filled (this is to avoid triggering one of the other validation rules, so we can see this behavior in isolation.)
* Select a field and enter one or more trailing or leading space characters. (Note that the phone number field already doesn't allow these.)
* Try to submit your contact details by clicking "Continue". Provided there are no other errors this should succeed.
* Inspect the body of the network call to `domain-contact-information/validate`. There should be no leading or trailing whitespace in the field you altered two steps ago.
* Repeat, this time submitting only space characters for an optional field such as `address-2`.

Fixes #48305

### CODE REVIEW

File: client/components/domains/contact-details-form-fields/managed-contact-details-form-fields.jsx [hunk 1]
```diff
@@ -151,7 +151,7 @@ export class ManagedContactDetailsFormFields extends Component {
 			isError: !! form[ camelName ]?.errors?.length,
 			errorMessage: customErrorMessage || getFirstError( form[ camelName ] ),
 			onChange: this.handleFieldChangeEvent,
-			onBlur: this.handleBlur,
+			onBlur: this.handleBlur( name ),
```
Comment (sirbrillig) [inline client/components/domains/contact-details-form-fields/managed-contact-details-form-fields.jsx:154]: Should this remain a function argument? 

```suggestion
			onBlur: () => this.handleBlur( name ),
```

File: client/components/domains/contact-details-form-fields/managed-contact-details-form-fields.jsx [hunk 2]
```diff
@@ -181,6 +181,10 @@ export class ManagedContactDetailsFormFields extends Component {
 				this.handleFieldChange( 'postal-code', formattedPostalCode );
 			}
 		} );
+
+		// Strip leading and trailing whitespace
+		const sanitizedValue = form[ camelCase( name ) ]?.value.trim();
```
Comment (sirbrillig) [inline client/components/domains/contact-details-form-fields/managed-contact-details-form-fields.jsx]: Great work. I wonder if we should also run lodash's `deburr` here as it seems old checkout did:

https://github.com/Automattic/wp-calypso/blob/24366af8c62c9293fef59c1cc883694139ae0897/client/components/domains/contact-details-form-fields/index.jsx#L207

...although adjusted to not run if there's no value. Apparently that removes non-latin characters.

**Review by sirbrillig — APPROVED** [review]
Works as described! Thank you!

File: client/components/domains/contact-details-form-fields/managed-contact-details-form-fields.jsx (hunk 2 above)
Comment (nbloomf) [reply client/components/domains/contact-details-form-fields/managed-contact-details-form-fields.jsx]: I've added this because presumably there's a reason why old checkout had it, although not fully knowing how old checkout handled sanitization there's a possibility that this will behave differently from the user's point of view.

Specifically, if the user enters a field with diacritics (very common for names and place names) then this will remove them when the field blurs. What's awkward about this is that, regardless of any technical limitations imposed by a registrar, the text displayed back to the user will be _wrong_, and they won't be able to fix it.

Comment (mrfoxtalbot) [reply client/components/domains/contact-details-form-fields/managed-contact-details-form-fields.jsx]: > What's awkward about this is that, regardless of any technical limitations imposed by a registrar, the text displayed back to the user will be wrong, and they won't be able to fix it.

This is not ideal but I guess it is better than the previous situation. Thank you!
