### PR TITLE
Calypso linting: allow WP dependencies as import docblocks

### LINKED ISSUE #44387: eslint-plugin-wpcalypso: potential improvement for import-docblock
#### Steps to reproduce

1. Starting on a codebase using `wpcalypso/react`
2. In a new file, add the following:
```js
/**
 * WordPress dependencies
 */
import { __ } from '@wordpress/i18n';

export default {
...
```
3. This triggers `wpcalypso/import-docblock`, even though there are no other imports in the file, so we cannot have external or internal import docblocks (or they'd be empty).

I think it would make sense to update the rule to have it look for "WordPress dependencies" as well, since those can now be valid imports, on their own within a file.

Related discussion:
https://github.com/Automattic/jetpack/pull/16545#discussion_r459312544

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #44387

#### Changes proposed in this Pull Request

* Update the `wpcalypso/import-docblock` rule so it allows for WordPress dependencies in addition to the existing External and Internal dependencies.
* Release a new version of the package including this change (and the other un-released changes).

#### Testing instructions

* Do the tests pass?
* This should now be a valid import:
```js
/**
 * WordPress dependencies
 */
import { __ } from '@wordpress/i18n';
```

### CODE REVIEW

**Review by wp-desktop — DISMISSED** [review]
WordPress Desktop CI Failure for job "wp-desktop-source".

@jeherve please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/822052). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

File: packages/eslint-plugin-wpcalypso/lib/rules/test/import-docblock.js [hunk 1]
```diff
@@ -27,19 +27,19 @@ new RuleTester( {
 			code: `/**
  * External dependencies
  */
-import eslint from \'eslint\';`,
```
Comment (jeherve) [inline packages/eslint-plugin-wpcalypso/lib/rules/test/import-docblock.js:30]: Add to remove those even though I didn't change the tests. 

```
wp-calypso/packages/eslint-plugin-wpcalypso/lib/rules/test/import-docblock.js
  29:20  error  Unnecessary escape character: \'  no-useless-escape
  29:28  error  Unnecessary escape character: \'  no-useless-escape
  35:20  error  Unnecessary escape character: \'  no-useless-escape
  35:28  error  Unnecessary escape character: \'  no-useless-escape
  41:20  error  Unnecessary escape character: \'  no-useless-escape
  41:28  error  Unnecessary escape character: \'  no-useless-escape
```

**Comment by jeherve** [comment]
> WordPress Desktop CI Failure for job "wp-desktop-source".

```
Found '/home/circleci/wp-calypso/.nvmrc' with version <12.18.0>
 
Now using node v12.18.0 (npm v6.14.4)
 
/home/circleci/.nvm/versions/node/v12.18.0/bin/yarnpkg -> /home/circleci/.nvm/versions/node/v12.18.0/lib/node_modules/yarn/bin/yarn.js
 
/home/circleci/.nvm/versions/node/v12.18.0/bin/yarn -> /home/circleci/.nvm/versions/node/v12.18.0/lib/node_modules/yarn/bin/yarn.js
 
+ yarn@1.22.4
 
added 1 package in 0.268s
 
yarn install v1.22.4
 
[1/5] Validating package.json...
 
[2/5] Resolving packages...
 
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
 
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 
 
Exited with code exit status 1 
CircleCI received exit code 1 
```

Does this mean I should update the version of the package in the monorepo's `package.json`, and then update `yarn.lock` as well, all in this PR? I thought this would be done separately from actually updating the package.

**Comment by scinos** [comment]
The change looks good to me, but I need to ask: what's the goal? What value does it provide?  All wordpress imports are easily identifiable because they start with `@wordpress/`, no?

**Comment by scinos** [comment]
> Does this mean I should update the version of the package in the monorepo's package.json

I assume you need to change the version in `packages/eslint-plugin-wpcalypso/package.json` _and_ in any `package.json` in the repo where `eslint-plugin-wpcalypso` is being used.

File: packages/eslint-plugin-wpcalypso/package.json [hunk 2]
```diff
@@ -1,6 +1,6 @@
 {
 	"name": "eslint-plugin-wpcalypso",
-	"version": "4.1.0",
+	"version": "5.0.0",
```
Comment (scinos) [inline packages/eslint-plugin-wpcalypso/package.json:3]: Given that this is not a breaking change, this could be 4.2.0 as well

**Comment by jeherve** [comment]
> I need to ask: what's the goal? What value does it provide? All wordpress imports are easily identifiable because they start with @wordpress/, no?

They are, yes. This would mostly solve issues like [this one](https://github.com/Automattic/jetpack/pull/16545#discussion_r459287221), where the rule is triggered because there are no other imports in the file, only WordPress imports indicated as such in the docblock.

The alternative would be to continue to use the term "External" to define `@wordpress/` dependencies, since that's what they are. I'm fine with this too; that is what we do elsewhere in the Jetpack plugin codebase. cc @mmtr for your opinion on this.

**Comment by mmtr** [comment]
> The alternative would be to continue to use the term "External" to define `@wordpress/` dependencies, since that's what they are. I'm fine with this too; that is what we do elsewhere in the Jetpack plugin codebase. cc @mmtr for your opinion on this.

The main reason why we differentiate the WordPress dependencies it's because it's recommended in the [WordPress Coding Guidelines for imports](https://developer.wordpress.org/block-editor/contributors/develop/coding-guidelines/#imports) so I'd suggest to avoid referring the `@wordpress/*` packages as external dependencies in order to keep following the guidelines.

**Review by scinos — APPROVED** [review]

**Comment by nsakaimbo** [comment]
👋 The root Calypso CI job and wp-desktop source builds are both failing with the same error:

`error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`
