### PR TITLE
Fix issue hiding blogging prompts card when on the site checklist view on my home

### LINKED ISSUE #79380: Home: Hiding Daily Prompts impacts site checklist, revealing checklist restores daily prompts
### Quick summary

On my Free test site, when I hide the "Daily prompts" card on the My Home page, the "Blog setup" checklist is replaced with **Site setup complete!** But then if I click on the button to "Show me what's next", the Daily prompts card is restored, and I have to hide it again.  

Hiding it a second time seemed to work, but still changes the order of cards in above it.

### Steps to reproduce

1. Open a newer test site, or create a new test site and launch it without completing the checklist.
2. Open **My Home**, and observe the Blog Setup checklist as well as the Daily Prompts card.
3. Use the `...` button to hide the daily prompts.
     - _observe that the daily prompts hide, but so does the site checklist_
4. In the new **Site setup complete!** card, click on "Show me what's next"
     - _observe that the daily prompts card returns along with the checklist_
5. Repeat step 3 and hide the daily prompts again

### What you expected to happen

Only the "Daily Prompts" card is hidden, and the other content onscreen is not impacted.

### What actually happened

On one test site, I was able to hide the Daily writing prompt on my second attempt:

https://github.com/Automattic/wp-calypso/assets/27249804/69aab7a9-b56d-4714-8f58-dc5c57bc9fdd

On another free test site, the Daily writing prompts hid/ were revealed following the steps above, and then could not be hidden again:

https://github.com/Automattic/wp-calypso/assets/27249804/89371250-7cdb-4e2f-943b-e9899cb23db5

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Gutenberg: v16.2.0
Editing Toolkit: 3.71520
WP AMP: 2.0.5

Firefox 115.0.2 (64-bit)

### PR DESCRIPTION
**Pull request by roo2**
Fixes: https://github.com/Automattic/wp-calypso/issues/79380

This allows you to dismiss the blogging prompt card without also dismissing the onboarding checklist from my-home

### Code details
The code here is a little interesting basically as I understand it, there are three types of view.

* The `VIEW_SITE_SETUP` view which shows the site setup checklist
* Single card views such as the `VIEW_CELEBRATE_SITE_LAUNCH` view. They have one primary card
* The VIEW_POST_LAUNCH view which has the slider of advertisement style cards. This view cannot be skipped.

When dismissing a card, the `layout/skip` endpoint can be used in two ways:

Pass in a `card` and that `card` will be hidden.
Pass in a `view` and that `view` will be hidden.

We skipped single card views by passing the `view` to the API. So in effect, skipping a card and skipping a view were the same thing!

Prior to adding the blogging prompts card to the `VIEW_SITE_SETUP` view, that view had no skippable cards. The checklist items used a different endpoint to be dismissed.

So the bug appears when a skippable card (blogging prompts) was added to the `VIEW_SITE_SETUP` view. Dismissing this card would dismiss the whole view.

I was tempted to attempt to change the way that skipping cards and views works to make it more generic, but I think this is a simpler fix.

### Testing instructions

Reset calypso preferences to unhide all cards:
`wp user attribute delete <user_id> calypso_preferences`

Restore the site onboarding checklist:
`wp option delete --url=<site_slug> onboarding_checklist_completed`

With those commands you should be able to manually test this, different view types:
* Single card view. e.g. the post launch view which appears after launching a site.
* `VIEW_SITE_SETUP`
* `VIEW_POST_LAUNCH`

### CODE REVIEW

File: client/data/home/use-skip-current-view-mutation.ts [hunk 1]
```diff
@@ -28,16 +28,21 @@ function useSkipCurrentViewMutation< TData, TError >( siteId: number ): Result<
 				{ staleTime: Infinity }
 			);
 
+			const view_name = ( data as any ).view_name;
+			const multipleCardViews = [ 'VIEW_POST_PUBLISH', 'VIEW_SITE_SETUP' ];
```
Comment (p-jackson) [inline client/data/home/use-skip-current-view-mutation.ts]: Pretty sure this is a typo

```suggestion
			const multipleCardViews = [ 'VIEW_POST_LAUNCH', 'VIEW_SITE_SETUP' ];
```

**Review by p-jackson — COMMENTED** [review]
I hadn't heard of these different sorts of views referred to as "multiple" and "single" card views before. But I suppose it is a real sort of distinction. I've tended to think of it in terms of "views that have one definitive card" and "views that don't".

The change looks good though. Once I fixed the (presumed) typo it all tested correctly.

One question I have though is why not send the `view` param when it's a multicard view? It looks to me like the backend still makes use of that param regardless of whether it's a "single" or "multi" card view?

**Review by Addison-Stavlo — COMMENTED** [review]
This resolves the issues in my testing and the fix seems nice and simple!

File: client/data/home/use-skip-current-view-mutation.ts (hunk 1 above)
Comment (roo2) [reply client/data/home/use-skip-current-view-mutation.ts]: oops good catch!

**Comment by roo2** [comment]
> One question I have though is why not send the `view` param when it's a multicard view? It looks to me like the backend still makes use of that param regardless of whether it's a "single" or "multi" card view?

That was the original cause of the issue, when its a multicard view, sending the `view` param was causing the whole view to be skipped even if the intention was to only skip one of the cards.

**Review by p-jackson — APPROVED** [review]
Thanks for clarifying @roo2. Looks good to me now.
The e2e test failures look consistent, it looks like the PR might just need to be rebased though.
