### PR TITLE
Change the way we handle positioning for guided tours

### LINKED ISSUE #31688: Site Settings: Guiding message does not point to the button it's meant to highlight.
Screen_Shot_2019-03-19_at_10 55 53_AM

To reproduce:

1) Start with a new website. Go to your Checklist.
2) Click "Do It" next to "Give your site a name"
3) Update the site name and click "All done, continue"
4) Note the placement of the help message; it's supposed to point to the Save Settings button.

**I expected:**

The help message to point to the Save Settings button.

**What happened:**

The help message points to a random area in the header.

### PR DESCRIPTION
**Pull request by scruffian**
When guided tours overlap the right side of the screen, their position can look strange - see #31688

54836407-86197280-4c9a-11e9-9212-48292e022d8e

#### Changes proposed in this Pull Request

This PR makes a change to what happens in these cases, to align the step with the right of the element:

Screenshot 2019-03-26 at 14 54 32
Screenshot 2019-03-26 at 14 54 06

I've tested all the tours I could find, and this doesn't seem to break them, but there could be others I haven't found.

#### Testing instructions

* Open a site with a checklist
* Go through the checklist task to change your site title
* Go through the checklist task to change your site tagline
* Look for other tours which might be broken

Fixes #31688

### CODE REVIEW

File: client/layout/guided-tours/positioning.js [hunk 1]
```diff
@@ -34,11 +34,11 @@ const helpers = {
 	yBelow: bottom => {
 		return bottom + DIALOG_PADDING;
 	},
-	xAboveBelow: ( left, right, width ) => {
+	xAboveBelow: ( left, right ) => {
```
Comment (lsinger) [inline client/layout/guided-tours/positioning.js]: Would probably make sense to remove that passed in `rect.width` where `xAboveBelow` is used.

**Review by lsinger — APPROVED** [review]
Left a comment. Apart from that this looks good to me. Thanks for helping fix things! 😊
