### PR TITLE
[GB 11.1.0] E2E test fixes

### LINKED ISSUE #54760: [GB 11.1.0] E2E test wp-calypso-gutenberg-post-editor-spec.js fails
Test suite: `[WPCOM] Calypso Gutenberg Editor: Posts (desktop): Public Posts: Preview and Publish a Public Post @parallel`
Test name: `Can enter post title, content and image `

Error:

```
  TimeoutError: Waiting for element to be settable By(css selector, input.block-editor-inserter__search-input) to "Image"
  Wait timed out after 22210ms
  Error: TimeoutError: Waiting for element to be settable By(css selector, input.block-editor-inserter__search-input) to "Image"
  Wait timed out after 22210ms
  at Proxy.<anonymous> (lib/driver-manager.js:97:14)
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
  at async Proxy.setWhenSettable (lib/driver-helper.js:304:9)
  at async GutenbergEditorComponent.openBlockInserterAndSearch (lib/gutenberg/gutenberg-editor-component.js:252:3)
  at async GutenbergEditorComponent.addBlock (lib/gutenberg/gutenberg-editor-component.js:417:3)
  at async GutenbergEditorComponent.addImage (lib/gutenberg/gutenberg-editor-component.js:454:19)
  at async Context.<anonymous> (specs/specs-wpcom/wp-calypso-gutenberg-post-editor-spec.js:57:4)
```

### PR DESCRIPTION
**Pull request by fullofcaffeine**
Tracking issue: https://github.com/Automattic/wp-calypso/issues/54393.

Fixes https://github.com/Automattic/wp-calypso/issues/54760.

### CODE REVIEW

File: test/e2e/lib/components/site-editor-component.js [hunk 1]
```diff
@@ -254,9 +254,16 @@ export default class SiteEditorComponent extends AsyncBaseContainer {
 			await driverHelper.clickWhenClickable( this.driver, blockAppenderLocator );
 		} );
 
+		// @todo Remove this fallback and its reference below in the `By.css` call
```
Comment (fullofcaffeine) [inline test/e2e/lib/components/site-editor-component.js:257]: @david-szabo97 Would it be possible to share this function between the two classes? Maybe by extracting it to an external helper module? I noticed they are pretty much the same, but there's a small difference -- the fact that this one wraps the `blockAppenderLocator`'s `By.css` call in the `runInCanvas`. Why is this needed? Thanks!

**Review by scinos — APPROVED** [review]

File: test/e2e/lib/components/site-editor-component.js (hunk 1 above)
Comment (david-szabo97) [reply test/e2e/lib/components/site-editor-component.js:257]: The editor content is in an iframe in the Site Editor. In the Post Editor, it isn't. We wrap it in `runInCanvas` to make sure we run that part of the code in the editor's iframe content.

We can declare an empty function `runInCanvas` function in the PostEditor's Component class. Then we can pass the editor to the helper function. After that, we can remove the function from both components.

Comment (fullofcaffeine) [reply test/e2e/lib/components/site-editor-component.js:257]: Makes sense! I'll do that as a follow-up PR at some point this or next week as time allows 👍🏻
