### PR TITLE
Remove site icon when 'icon' prop is not present in new attributes coming from API

### LINKED ISSUE #1857: Jetpack: Site Icon still trying to be loaded even after it's been removed
Steps to reproduce:

1. Add a Site Icon through the self-hosted site's customizer at /wp-admin/customize.php?autofocus[control]=site_icon
2. Visit https://wordpress.com/ and check my self-hosted site to confirm the Site Icon appears there
3. Open the customizer again and remove the Site Icon. Confirm it no longer appears as the site's favicon in the browser.
4. Revisit https://wordpress.com/. Result: site icon still appears there, even after a hard refresh
5. Permanently delete the site icon image from my self-hosted site's media library.
6. Revisit https://wordpress.com/. Result: site icon still appears there, even after a hard refresh

I expected: Jetpack to be aware of the changes to the site icon, and to display the icon correctly (whether it exists or not)

### PR DESCRIPTION
**Pull request by lamosty**
Helps to fix #1857 (but doesn't fix entirely as another part is related to Jetpack).

After removing site icon on either WP.com site or Jetpack connected WP site, the `icon` property in the API result can have two states:

1. [Gravatar logo](https://secure.gravatar.com/blavatar/9de6281ba3183a48d80e8b3c8af3cc85?ts=1464349551) — when it is WP.com site;
2. The `icon` property gets removed from the `/me/sites` API endpoint results — with Jetpack connected WP site or after a while with WP.com site.

Screenshots:

1. state (Gravatar logo)
selection_026

2. state (`icon` prop gets removed from the API result)
selection_027

However, if the `icon` prop is removed, the site icon is not removed in Calypso because `Site.prototype.set` method — which is used to apply/set new attributes from the API — doesn't remove those props from a `Site` which are no longer present in the new `attributes` that are being set. It only updates the old props if they've been changed in the new `attributes`.

I found out these 3 solutions to the problem and decided to use the easiest to implement but also the least disruptive one. Let me explain:

#### 1. Modify WP.com API to always include the `icon` prop and set `icon` to an empty object if a site doesn't have site icon.

We would still need to update particular Calypso code which handles site icons because it shows empty icon only if the `icon` prop doesn't exist on a `Site` currently. What is more, if some other/3rd party apps that are consuming WP.com API depend on `icon` not being there, this change would break those apps. That's why I decided strongly against this approach. Maybe with a new API version.

#### 2. Modify `Site` obj in Calypso and add a new method (e.g. `Site.prototype.replace(attrs)`)

This new method would replace all the existing attributes on a `Site` with the new attributes if they changed. If an attribute is missing from the new attributes, remove it from the `Site`. Initially, I had this coded up and ready to create a PR, but the problem with this approach is that a site's attributes are stored in an instance of `Site` object which also contains other props such as `_maxListeners`, `options` and other programmatically added props. I would also delete those because they would be missing from the new attributes.

There are two solutions to this but I liked none of them:

1. Add a "whitelist" or a schema of all the attributes a site can have and remove only those not present from these. Problem is that attributes in API can be added/removed and this list would have to be updated manually all the time.

2. Move all the site's attributes to another object, say `site.attributes`. Then we could work only with this object and not with a `site` which includes other props. Problem is that `Site` object is used in many places and everything would have to be refactored. Quite a change for one site icon, don't you think?

#### 3. Add a condition that if new attributes don't contain 'icon' and current do, remove it from the current ones

This is the simplest and most straightforward approach and I finally went with it because:

1. We must add only 3 new lines of code, nothing else to change;
2. There are no other attributes which are removed from the API result except `icon` I know of. Even if there were, the `if` condition could be put into a loop.
3. When I talked about this issue with @rralian last time, he said that the Calypso code working with sites (e.g.: `Site`, `SitesList`) will be refactored into Redux anyway sometime in the future and we could use more solid approach when doing this that time.

I'm open to all suggestions/other approaches. Also, if you think approach 1. or 2. is better, please explain why.

Thanks.

@rralian @gwwar @mtias @dmsnell

### CODE REVIEW

**Comment by gwwar** [comment]
👍 The third approach here seems reasonable. We'll also want to add a similar check to the sites redux tree. The sites tree is currently populated from SitesList, but will be eventually decoupled.

Some approaches to this would be adding an explicit deleteIcon action, which the sites reducer could handle. Or doing a similar prune when we receive a site or sites:
https://github.com/Automattic/wp-calypso/blob/master/client/state/sites/reducer.js#L44

**Comment by rralian** [comment]
I don't think we can do this quite so simply. Currently it's valid to pass a subset of site data to `site.set()` when you only want to append/update certain attributes. I found [two](https://github.com/Automattic/wp-calypso/blob/master/client/lib/sites-list/list.js#L246) [examples](https://github.com/Automattic/wp-calypso/blob/master/client/lib/sites-list/list.js#L701) where `site.set()` is used this way. This usage is also implied in [these](https://github.com/Automattic/wp-calypso/blob/master/client/lib/site/test/index.js) [tests](https://github.com/Automattic/wp-calypso/blob/master/client/lib/sites-list/test/index.js). But with your code in place, this would trigger the removal of the `siteIcon`.

Maybe we can do a hybrid of your options 2 and 3, where we create a `site.replace()` method that is used when we get new `site` data from the API, which checks for the existence of the `siteIcon` and removes it appropriately, but we leave the `site.set()` method as it was before, so people can still use that directly when they want to add/edit specific attributes. We should then document the methods to describe that you can pass a subset of attributes to `site.set()` but you need to pass a full site object into `site.replace()`.

**Comment by lamosty** [comment]
@gwwar thanks for the suggestions, I'll look into this a bit more.

@rralian oops, you are 100% right, I've somehow overlooked this scenario. Nice idea, I like and will implement it.

**Comment by lamosty** [comment]
@gwwar:
> We'll also want to add a similar check to the sites redux tree. The sites tree is currently populated from SitesList, but will be eventually decoupled. Some approaches to this would be adding an explicit deleteIcon action, which the sites reducer could handle. Or doing a similar prune when we receive a site or sites:

Is this necessary? From what I see, when a site(s) is received, it gets appended to the state tree. Then, when the same site(s) is received again, the site is replaced with the new properties so if site icon will not be present in the new site attributes, it will be pruned from the sites tree: https://github.com/Automattic/wp-calypso/blob/e50feace918bc08750c4b0a816631aa19805461c/client/state/sites/reducer.js#L45-L47

If you meant something else or I'm missing something please correct me. :)

**Comment by lamosty** [comment]
I just tested this with [this Jetpack PR](https://github.com/Automattic/jetpack/pull/3992) on my Jetpack testing site and seems that it fixes #1857. I'm waiting on that Jetpack PR to get merged before closing the issue.

**Comment by gwwar** [comment]
@lamosty We try to avoid storing class instances in Redux, and aim to store plain objects in our global state tree. We couldn't avoid it in this case, but we will eventually get rid of the `lib/site` class, and instead use a number of [selectors](https://github.com/Automattic/wp-calypso/blob/master/docs/our-approach-to-data.md#selectors) instead of decorating the object.

This is also why we're doing funny things, like removing the computed properties via whitelisting fields. https://github.com/Automattic/wp-calypso/blob/e50feace918bc08750c4b0a816631aa19805461c/client/state/sites/reducer.js#L32

File: client/lib/site/index.js [hunk 1]
```diff
@@ -78,7 +86,39 @@ Site.prototype.set = function( attributes ) {
...
+
+/**
+ * Replaces all site's attributes. Will remove current attributes if they are not present in the
+ * new ones. Use Site.prototype.set if you want to update one or few attributes instead.
+ *
+ * @param {object} attributes - New attributes for a site.
+ * @returns {boolean} - Returns true if attributes changed, otherwise false.
+ */
+Site.prototype.replace = function( attributes ) {
+	var changed = false,
```
Comment (gwwar) [inline client/lib/site/index.js]: We [prefer](https://github.com/Automattic/wp-calypso/blob/master/docs/coding-guidelines/javascript.md#variable-declarations) `const`. It's OK if the style is not consistent with the rest of the file.

File: client/lib/site/index.js [hunk 2]
```diff
@@ -78,7 +86,39 @@ Site.prototype.set = function( attributes ) {
...
+		siteKeys = Object.keys( sitesSchema.patternProperties[ '^\\d+$' ].properties ),
+		that = this;
+
+	siteKeys.forEach( function( siteKey ) {
```
Comment (gwwar) [inline client/lib/site/index.js]: We can avoid the `that` if we use a fat arrow here:

```javascript
siteKeys.forEach( ( siteKey ) => { 
```

File: client/lib/site/index.js [hunk 3]
```diff
@@ -14,7 +14,8 @@ var wpcom = require( 'lib/wp' ),
 	notices = require( 'notices' ),
 	i18n = require( 'lib/mixins/i18n' ),
 	Emitter = require( 'lib/mixins/emitter' ),
-	isHttps = require( 'lib/url' ).isHttps;
+	isHttps = require( 'lib/url' ).isHttps,
+	sitesSchema = require( 'state/sites/schema' ).sitesSchema;
```
Comment (gwwar) [inline client/lib/site/index.js]: Let's update both the external and internal deps to import style.

**Comment by gwwar** [comment]
Apologies, my remembered information is out of date, and it looks like we might be ok in the redux site tree, since https://github.com/Automattic/wp-calypso/blob/9db620fa4c71d1d974b2c3da04686d72653d0c2f/client/my-sites/controller.js#L166-L166 we currently populate `state/sites` using a SitesList selected site. The only danger is that the icon in the sites tree may get stale if we edit an icon and don't switch sites or refresh. We'll want to verify the redux data before 🚢

**Comment by gwwar** [comment]
@lamosty It looks like we have a few computed site properties in the site schema: `options`, `is_previewable`, `is_customizable`, and `slug`. Let's go ahead and remove them from the schema. Without it SitesList.update will alway return true. I would recommend an additional unit test for this in sites-list

**Comment by gwwar** [comment]
@lamosty We'll also need some special handling for `site.options`, since option attributes are updated in `updateComputedAttributes`. In particular it's failing equality on `default_post_format` (false vs 'standard'). There's a few other properties in options which would make replace always return true. A unit test for this case is recommended as well.

**Comment by gwwar** [comment]
Sadly the API is a bit slow to update when I remove an icon. I'll check in tomorrow. This seems like a solid approach and we should be able to merge in after we clean up the false positives on SitesList.update.

**Comment by lamosty** [comment]
@gwwar 
> It looks like we have a few computed site properties in the site schema: is_previewable, is_customizable, and slug. Let's go ahead and remove them from the schema. Without it SitesList.update will alway return true.

Great catch! I will add a test (or more) for this case.

> We'll also need some special handling for site.options, since option attributes are updated in updateComputedAttributes. In particular it's failing equality on default_post_format (false vs 'standard'). 

I wonder whether this is a bug in the original `Site.prototype.set` method, too, as it also sets `changed` to `true` while `default_post_format` gets computed to `standard` and in the API it's `0`. Anyways, a great catch, again.

> There's a few other properties in options which would make replace always return true. A unit test for this case is recommended as well.

Hmm, would you mind telling me which ones, please? But yeah, I'll try to come up with some unit test for all the `options` props.

Thanks.

**Comment by gwwar** [comment]
> would you mind telling me which ones, please?

👍 Did a misread of the `this.options.unmapped_url.replace` in `updateComputedAttributes`, since that doesn't mutate the original string. It should just be `this.options.default_post_format`

File: client/lib/site/index.js [hunk 4]
```diff
@@ -100,6 +100,16 @@ Site.prototype.replace = function( attributes ) {
...
+	// Set attrs which will get computed and will mean the same before doing equality checks
+	// so the 'change' event is not triggered. See Site.prototype.updateComputedAttributes.
+	if ( attributes.hasOwnProperty( 'options' ) ) {
+		let options = attributes.options;
+
+		if ( ! options.hasOwnProperty( 'default_post_format' ) || options.default_post_format === '0' ) {
+			options.default_post_format = 'standard';
+		}
+	}
+
```
Comment (lamosty) [inline client/lib/site/index.js]: I had a nicer implementation ready with `isEqualWith` and an equality customizer:

```js
const computedAttrsCustomizer = ( newAttrVal, siteAttrVal, attrKey ) => {
	// options.default_post_format
	if ( 
		attrKey === 'default_post_format' &&
		newAttrVal === '0' &&
		siteAttrVal === 'standard'
	) {
		return true;
	}

	// Use the default comparison mechanism.
	return;
};
```

However, it didn't work because if the attributes coming from the API doesn't include `options.default_post_format` (which they sometimes don't), the above `if` condition is not run (=> there is no `newAttrVal`) and `isEqualWith` assumes that it's indeed not equal and replaces the `site.options` with `attrs.options` and `changed = true`. 

That's why I had to write the above solution. Can you think of something better?

File: client/lib/site/index.js [hunk 5]
```diff
@@ -112,9 +122,9 @@ Site.prototype.replace = function( attributes ) {
 		}
 	} );
 
-	this.updateComputedAttributes();
-
 	if ( changed ) {
+		this.updateComputedAttributes();
```
Comment (lamosty) [inline client/lib/site/index.js]: Why recompute attrs if nothing was changed?

File: client/lib/sites-list/test/index.js [hunk 6]
```diff
@@ -85,6 +85,16 @@ describe( 'SitesList', () => {
...
+
+		it( 'should not trigger change when sites attributes didn\'t change', () => {
+			const changeCallback = sinon.spy();
+
+			sitesList.once( 'change', changeCallback );
+
+			sitesList.update( cloneDeep( data.original ) );
+
+			assert.isFalse( changeCallback.called );
+		} );
```
Comment (lamosty) [inline client/lib/sites-list/test/index.js]: This test should catch all sites attrs, even nested ones. I think it's enough.

File: client/lib/site/index.js (hunk 4 above)
Comment (gwwar) [inline client/lib/site/index.js]: So if you look at `updateComputedAttributes` anything falsy for `default_post_format` is equivalent to 'standard'. Which means that undefined `default_post_format` should get set to 'standard' too.

```javascript
const computedAttrsCustomizer = ( newAttrVal, siteAttrVal, attrKey ) => {
    // options.default_post_format
    if ( attrKey === 'default_post_format' ) {
        const normalizedNewAttrVal = ! newAttrVal ? ' standard' : newAttrVal;
        const normalizedsiteAttrVal = ! siteAttrVal ? ' standard' : siteAttrVal;
        return normalizedNewAttrVal === normalizedsiteAttrVal;
    }
    // Use the default comparison mechanism.
    return;
};
// if we compare a and b
a.options.default_post_format = a.options.default_post_format || false;
b.options.default_post_format = b.options.default_post_format || false;
isEqualWith( a, b, computedAttrsCustomizer );
```

File: client/lib/sites-list/test/index.js (hunk 6 above)
Comment (gwwar) [inline client/lib/sites-list/test/index.js]: Were you able to get a failing test (with previous changes) without updating the test fixtures? Could we also add one of the computed props to the test data `is_previewable`, `is_customizable`, or slug? The test is 👍 once we do that.

**Comment by gwwar** [comment]
@lamosty since the schema was updated, we need to fix some tests in `state/sites/reducer`

File: client/lib/site/index.js (hunk 4 above)
Comment (lamosty) [inline client/lib/site/index.js]: That makes sense, thanks. However, when I tried it (back then), it seems like the `computedAttrsCustomizer` is not even run if the `options` don't include the `default_post_format` prop. Maybe lodash assumes that if the property is not on one side of the compared objects, it is not equal. 

While I can look into lodash's source code to verify this, I like my current solution more (should be faster as we don't use our own `customizer` which has to be called on each prop). Or do you think this `customizer` approach (if worked) would be more preferable?

File: client/lib/sites-list/test/index.js (hunk 6 above)
Comment (lamosty) [inline client/lib/sites-list/test/index.js]: Hmm, not sure I understand you 100%. :) I didn't touch the test fixtures (=> [test data](https://github.com/Automattic/wp-calypso/blob/228b91315aefb2bb74c6fcde434da35babe8abd7/client/lib/sites-list/test/fixtures/data.js)), only added the above test. It was failing before I removed the `is_previewable` etc from site schema though.

> Could we also add one of the computed props to the test data is_previewable, is_customizable

Yes, will do.

**Comment by lamosty** [comment]
@gwwar:
> since the schema was updated, we need to fix some tests in state/sites/reducer

"Run `make test` after changing/adding code, not only run the local tests`, I told myself now. Thanks.

File: client/lib/sites-list/test/index.js (hunk 6 above)
Comment (gwwar) [inline client/lib/sites-list/test/index.js]: > Hmm, not sure I understand you 100%. :) I didn't touch the test fixtures (=> test data), only added the above test. It was failing before I removed the is_previewable etc from site schema though.

Thanks I wanted to verify that the new test failed, before we updated code. Sometimes we can accidentally write tests that pass in both situations, which is not useful :)

**Comment by gwwar** [comment]
If circle ci has already run, you can click on the ❌  or ✔️ icon next to 
screen shot 2016-06-06 at 2 47 22 pm

This take you to the circle ci build, which will have some information on the failure, like so:
screen shot 2016-06-06 at 2 49 11 pm

Or you can navigate directly to builds via: https://circleci.com/gh/Automattic/wp-calypso/tree/fix%2Fremove-site-icon-from-site-attrs

**Comment by gwwar** [comment]
@lamosty if you've addressed all feedback and are ready, don't forget to switch back to "needs review" so folks will 👀

**Comment by lamosty** [comment]
@gwwar 

Thanks! Label updated.

File: client/lib/site/index.js [hunk 7]
```diff
@@ -78,7 +86,49 @@ Site.prototype.set = function( attributes ) {
...
+	const siteKeys = Object.keys( sitesSchema.patternProperties[ '^\\d+$' ].properties );
+
+	let changed = false;
+
+	// Set attrs which will get computed and will mean the same before doing equality checks
+	// so the 'change' event is not triggered. See Site.prototype.updateComputedAttributes.
+	if ( attributes.hasOwnProperty( 'options' ) ) {
+		let options = attributes.options;
+
+		if ( ! options.hasOwnProperty( 'default_post_format' ) || options.default_post_format === '0' ) {
```
Comment (gwwar) [inline client/lib/site/index.js]: We should match the what `updatedComputedAttribtues` is doing. ie `! this.options.default_post_format || this.options.default_post_format === '0'`

**Comment by gwwar** [comment]
Unfortunately, I'm still seeing it trigger changes incorrectly with `options.default_post_format`. I believe we'll want to compute the value for both `attributes.options.default_post_format` and `this.options.default_post_format` before performing the equality check.

**Comment by lamosty** [comment]
> Unfortunately, I'm still seeing it trigger changes incorrectly with options.default_post_format

Where? I'm running all tests and they pass. How can I reproduce it, please?

**Comment by gwwar** [comment]
Try adding a breakpoint or console.log at https://github.com/Automattic/wp-calypso/blob/97c4193e4cb19d0aea3aa4de41574f7c1885d36f/client/lib/site/index.js#L117, and load Calypso :)

**Comment by lamosty** [comment]
@gwwar:
> Try adding a breakpoint or console.log at https://github.com/Automattic/wp-calypso/blob/97c4193e4cb19d0aea3aa4de41574f7c1885d36f/client/lib/site/index.js#L117, and load Calypso :)

Oh, I see now. `options.default_post_format` can:
1. not be present in `options` at all;
2. be present with `false` value;
3. be present with `'0'` value;
4. be present with `'standard'` value.

I've updated the `sites-list` test data and also matched the condition in `Site.proto.repalce` to the condition in `Site.proto.updateComputedAttrs` — as you suggested before (and I did not understand..).

Could you give it one more review please? If it's okay, I'll merge and deploy.

**Comment by gwwar** [comment]
Looks great, lets 🚢

**Comment by ehg** [comment]
This PR broke the sidebar site card preview: https://github.com/Automattic/wp-calypso/issues/5963

Any ideas why?
