### PR TITLE
Fix Accessibility on Several Green Texts

### LINKED ISSUE #101301: General: Fix accessibility issues on Green color usage
## Problem

We spotted few accessibility issues when using the green colour. 

1. We've recently introduced a new badge style on the Plans Grid that is inaccessible 
2. Text within domains page page
3. Text within domain section in /overview
4. The green discount on dark mode (e.g. Hosting plans grid).

Image

Image

Image

Image

## Solutions 

Specific to the **Pricing grid badge**: It should use the same styles we have in the other green badges:

```
color: var(--studio-green-80);
background-color: var(--studio-green-5);
```

For all the instances when the **text appears alone**, always use:

```
color: var(--studio-green-60);
```

For all the instances when we have **green on dark mode**, always use:

```
color: var(--studio-green-10);
```

> [!NOTE]  
> In a separate issue we will be working on aligning all the badges to Core's [component](https://wordpress.github.io/gutenberg/?path=/docs/components-badge--docs#success)

### LINKED ISSUE #102776: Checkout: Update green colour (accessibility fix)
As per the parent issue, we should be fixing these instances in the Checkout. When the text is green, we should always use:

`color: var(--studio-green-60);`

Areas to fix:

**Billing dropdown:**
Image

**Free domain text:**
Image

### LINKED ISSUE #102777: Cart: Update green colour (accessibility fix)
As per the parent issue, we should be fixing these instances in the Checkout. When the text is green, we should always use:

`color: var(--studio-green-60);`

**CART**
Image

### PR DESCRIPTION
**Pull request by Copons**
Fixes https://github.com/Automattic/wp-calypso/issues/101301
Fixes https://github.com/Automattic/wp-calypso/issues/102776
Fixes https://github.com/Automattic/wp-calypso/issues/102777

Update several instances of green texts as instructed to fix accessibility issues caused by inadequate contrast.

* Text on light background: `--studio-green-60` (`#007017`).
* Text on dark background: `--studio-green-10` (`#68de86`).

### Screenshots

| Location | Before | After |
|--------|--------|--------|
| Onboarding (Domains) | image | Screenshot 2025-04-25 at 16 55 38 |
| Hosting Dashboard (Site Panel) | image | Screenshot 2025-05-07 at 15 20 29 |
| Checkout | image image | Screenshot 2025-04-25 at 17 05 30 |
| Add Professional Email Address | Screenshot 2025-05-07 at 15 25 03 | Screenshot 2025-05-07 at 15 24 51 |

### Testing Instructions

* Onboarding (Domains)
   * Create a new site and get to the Domains step.
   * Select a domain.
   * Confirm that the "Free for the first year with annual paid plans." text uses the `--studio-green-60` color.
* Hosting Dashboard (Site Panel)
   * Enter the Hosting Dashboard (`/sites`).
   * Pick a site.
   * Scroll to the Active Domains section.
   * Confirm that the "Primary site address" text uses the `--studio-green-60` color.
* Checkout
   * Select a free site.
   * Navigate to Plans (`/plans/:site`) and select a paid plan to put the upgrade in cart.
   * Now navigate to Domains (`/domains/manage/:site`).
   * Click on "Add new domain", select a domain to put it in cart.
   * The "Add a professional email address" screen will open.
   * Confirm that the discounted price uses the `--studio-green-60` color.
   * Confirm that the "3 months free" badge uses `--studio-green-80` for text and `--studio-green-5` for background (there should be no visible changes as this is a fallback normally overridden by the generic badge colors).
   * Open the cart (`/checkout/:site`).
   * Confirm that the following texts all use the `--studio-green-60` color:
      * The "Save xx%" suffix in the plan interval dropdown.
      * "Discount for first year" in the domain item.
      * "Free domain for first year" in the checkout summary (right sidebar).

### CODE REVIEW

File: packages/composite-checkout/src/lib/theme.ts [hunk 1]
```diff
@@ -70,7 +70,7 @@ const theme: Theme = {
 		highlightBorder: colorStudio.colors[ 'WordPress Blue 80' ],
 		highlightOver: colorStudio.colors[ 'WordPress Blue 60' ],
 		success: colorStudio.colors[ 'Green 30' ],
```
Comment (BogdanUngureanu) [inline packages/composite-checkout/src/lib/theme.ts:72]: Shouldn't `success` also use Green 60? 🤔

Comment (Copons) [reply packages/composite-checkout/src/lib/theme.ts:72]: I'm not entirely sure how `success` is used.

For example, [here](https://github.com/Automattic/wp-calypso/blob/af6d1c275f6e5275c800b309e5bfee046b6ec547/packages/composite-checkout/src/components/checkout-steps.tsx#L1090-L1091) is used as a background — in which case [it should be Green 5](https://github.com/Automattic/wp-calypso/issues/101301) — and a border color.

Instead of risking a regression, I've chosen to keep it out of scope. 🙂

**Review by dsas — COMMENTED** [review]
In the hosting dashboard overview, the other green text is using  active SSL use --color-studio-50. Shouldn't it be using --color-studio-60 too?
Screenshot 2025-05-07 at 10 54 05

**Review by dsas — COMMENTED** [review]
Maybe out of scope, but when adding a domain I get a titan upsell which uses studio-green-50 for the price
Screenshot 2025-05-07 at 11 38 59

File: client/my-sites/checkout/src/components/cost-overrides-list.tsx [hunk 2]
```diff
@@ -55,7 +55,7 @@ const CostOverridesListStyle = styled.div`
 	}
 
 	& .cost-overrides-list-item__reason--is-discount {
-		color: #008a20;
+		color: #007017;
```
Comment (dsas) [inline client/my-sites/checkout/src/components/cost-overrides-list.tsx]: it'd be nice if this used the variable

**Review by dsas — APPROVED** [review]
Approving, it improves things. There are some more incorrect greens I've commented about that I think should be fixed here or in a follow-up

**Comment by Copons** [comment]
Thank you @dsas, I've implemented all the suggested changes! ✨

**Review by dsas — APPROVED** [review]
Cheers, lgtm
