### PR TITLE
Flaky E2E: additional fixes to ensure the launchpad is skipped correctly.

### LINKED ISSUE #74389: Flaky E2E: Skip Launchpad
### Spec file

specs/plans/plans__signup-business.ts

### TeamCity ID

9649007

### Logs

```
page.waitForNavigation: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for navigation until "load"
  navigated to "https://wpcalypso.wordpress.com/home/e2eflowtestingprereleaseuser37083.wordpress.com?showLaunchpad=true"
  navigated to "https://wpcalypso.wordpress.com/home/e2eflowtestingprereleaseuser37083.wordpress.com?showLaunchpad=true"
  navigated to "https://wpcalypso.wordpress.com/setup//launchpad?siteSlug=e2eflowtestingprereleaseuser37083.wordpress.com"
  navigated to "https://wpcalypso.wordpress.com/setup/site-setup/goals?siteSlug=e2eflowtestingprereleaseuser37083.wordpress.com"
  navigated to "https://wpcalypso.wordpress.com/setup/site-setup/processing?siteSlug=e2eflowtestingprereleaseuser37083.wordpress.com"
  navigated to "https://wpcalypso.wordpress.com/home/e2eflowtestingprereleaseuser37083.wordpress.com?showLaunchpad=true"
  navigated to "https://wpcalypso.wordpress.com/home/e2eflowtestingprereleaseuser37083.wordpress.com?showLaunchpad=true"
  navigated to "https://wpcalypso.wordpress.com/setup/build/launchpad?siteSlug=e2eflowtestingprereleaseuser37083.wordpress.com"
============================================================
at Object.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/plans/plans__signup-business.ts:82:11)
    at Promise.then.completed (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:391:28)
    at callAsyncCircusFn (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:316:10)
    at _callCircusTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:218:40)
    at _runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:155:3)
    at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:66:9)
    at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at run (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:170:21)
    at jestAdapter (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:82:19)
    at runTestInternal (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:389:16)
    at runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:475:34)
    at Object.worker (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/testWorker.js:133:12)
```

### PR DESCRIPTION
**Pull request by worldomonation**
Fixes https://github.com/Automattic/wp-calypso/issues/74389.

## Proposed Changes

This PR adds waits for URL and network load state and removes usage of deprecated `waitForNavigation` call in the `Signup: Business` spec.

Context: p1678737506278029-slack-CHN6J22MP and https://github.com/Automattic/wp-calypso/pull/74082.

The fix previously added in https://github.com/Automattic/wp-calypso/pull/74082 worked well, but there was one instance where the click on `Skip to dashboard` failed because the click happened immediately when the element was visible but not before the page was ready. This resulted in the click being swallowed up by the pageload. Another issue is likely due to identical link names "Skip to dashboard" in both the `intent_capture` and `launchpad`, so an additional safeguard is to add a wait for the expected URL.

Key changes:
- add waitForURL calls to ensure, at each step, that the page shown is as expected.

## Testing Instructions

Ensure the following build configurations are passing:
  - [x] Pre-Release E2E

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by dpasque — APPROVED** [review]
👍

**Review by jeyip — COMMENTED** [review]
Thanks for drafting this and explaining your reasoning @worldomonation. After going through playwright documentation https://playwright.dev/docs/api/class-page#page-wait-for-navigation and other threads describing confusion around waitForNavigation https://github.com/puppeteer/puppeteer/issues/1412, this makes sense to me 👍 

I'll definitely keep this in mind for the future

**Review by jeyip — APPROVED** [review]

File: test/e2e/specs/plans/plans__signup-business.ts [hunk 1]
```diff
@@ -73,14 +73,18 @@ describe(
 			} );
 
 			it( 'Skip Onboarding', async function () {
+				await page.waitForURL( /setup\/site-setup\/goals/, { waitUntil: 'networkidle' } );
 				const startSiteFlow = new StartSiteFlow( page );
-				await startSiteFlow.clickButton( 'Skip to dashboard' );
+				await Promise.all( [
+					page.waitForURL( /build\/launchpad/, { waitUntil: 'networkidle' } ),
```
Comment (jeyip) [inline test/e2e/specs/plans/plans__signup-business.ts]: `NB:` Is there a reason we chose `networkidle` instead of `load`? Is it for extra safety?

```
'networkidle' - consider operation to be finished when there are no network connections for at least 500 ms.

'load' - consider operation to be finished when the load event is fired.
```

From my understanding, the main frame / DOM, assets, subframes would be complete when the `load` event is fired

Comment (worldomonation) [reply test/e2e/specs/plans/plans__signup-business.ts]: @jeyip Yes, the `networkidle` is for added safety. 

The default `waitForURL` call without the added parameter has an implicit wait for `load` state, which is good enough most of the time. I will remove the `networkidle` and we can observe whether it reduces/eliminates incidents of flakiness.
