### PR TITLE
Checkout: Prevent plan upgrade variants which are term downgrades

### LINKED ISSUE #52473: Checkout: do not show monthly plan option when upgrading from annual plan
From an internal bug report:

1. Customer bought our annual Premium plan
2. Customer then upgraded to our monthly Business plan on the same website
3. This left the customer charged with both the annual Premium and monthly Business plans

Apparently this is not desirable. It looks like someone already took care of this in https://github.com/Automattic/wp-calypso/pull/47229 but maybe it has become a problem again?

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

This PR prevents the checkout plan variant picker from showing plan upgrades which are billing term downgrades because that sort of upgrade is not supported by our payments system. That is, it prevents upgrading from one plan to another plan that has a shorter renewal period. For example, while switching from a Yearly Personal plan to a Yearly Business plan is allowed, switching from a Yearly Personal plan to a Monthly Business plan is _not_ allowed.

To prevent some cases where you could end up switching variants and then not be able to return to your previously selected variant, this also disables the variant picker when the cart item is a variant of the active plan.

Finally, to prevent confusion about what the "Save X%" numbers mean in cases where the monthly price is not shown, this also modifies the discount percentage shown on each product variant, which is currently based on the monthly price for that variant, so that it now is based on the smallest displayed variant's price.

Fixes https://github.com/Automattic/wp-calypso/issues/52473

#### Screenshots

On a site that has an annual premium plan upgrading to a business plan, this is editing the order in checkout before this PR:

Screen Shot 2021-07-08 at 7 52 46 PM

And this is editing the same order in checkout after this PR:

Screen Shot 2021-07-08 at 7 52 56 PM

Here's editing the checkout order for a site with an (expiring) annual premium plan downgrading to monthly before this PR:

Screen Shot 2021-07-08 at 8 03 48 PM

And here's editing that same order after this PR:

Screen Shot 2021-07-08 at 8 03 56 PM

#### Testing instructions

Verify unchanged behavior for free plans:

- Using a site which has a free plan, add a paid plan (of any term length) to your cart and visit checkout.
- Click the "Edit" button at the top-right of the first step.
- Verify that you see a variation picker for the plan and that it includes the monthly, yearly, and two-year plan variants.

Verify that monthly plans can upgrade to any term:

- Next, using a site which has a paid _monthly_ plan, add a higher level _monthly_ plan to your cart and visit checkout (eg: if you have a Personal plan, add a Premium or Business plan).
- Click the "Edit" button at the top-right of the first step.
- Verify that you see a variation picker for the plan and that it includes the monthly, yearly, and two-year plan variants.

Verify that yearly plans cannot upgrade to a monthly term:

- Next, using a site which has a paid _yearly_ plan, add a higher level _yearly_ plan to your cart and visit checkout.
- Click the "Edit" button at the top-right of the first step.
- Verify that you see a variation picker for the plan and that it includes only the yearly and two-year plan variants.

### CODE REVIEW

File: client/my-sites/checkout/composite-checkout/hooks/product-variants.tsx [hunk 1]
```diff
@@ -62,26 +73,25 @@ const DoNotPayThis = styled.span`
...
+): WPCOMProductVariant[] {
 	const translate = useTranslate();
 	const reduxDispatch = useDispatch();
 
+	const sitePlans: SitesPlansResult | null = useSelector( ( state ) =>
+		siteId ? getPlansBySiteId( state, siteId ) : null
+	);
+	const activePlan = sitePlans?.data?.find( ( plan ) => plan.currentPlan );
+	const isProductAnUpgrade = useSelector( ( state ) =>
+		siteId ? canUpgradeToPlan( state, siteId, productSlug ) : false
```
Comment (DavidRothstein) [inline client/my-sites/checkout/composite-checkout/hooks/product-variants.tsx]: Is the logic here actually correct?  I would expect to be checking each variant's product slug separately (rather than the overall `productSlug`).  I'm also not 100% sure that `canUpgradeToPlan()` is even necessary; regardless of whether it's an upgrade or not, do we **ever** want to allow a term downgrade via the variant picker specifically (even if we allow it in other contexts)?

I think one consequence of the above is the following behavior with this pull request:
1. Buy an annual plan.
2. Change the expiration date to something soon.
3. Go to the Manage Purchase page and choose the "Renew Monthly" option.
4. Open up the variant selector; notice that monthly is selected and all variants are available.
5. Switch to a 2-year plan; notice that monthly is no longer available, so you can't switch back.  (That's new behavior with this pull request.)
6. Switch to an annual plan; that turns the purchase into a renewal, so none of the variants are available to switch back to. (That's not ideal, but it is preexisting behavior.)

Also, if you repeat the above steps but start with a 2-year plan rather than an annual plan, the variant picker gives you a backdoor way to switch from 2-year to 1-year; that's existing behavior before this pull request too, although it's a downgrade path that we ideally shouldn't expose in the UI since our billing system isn't really ready for it.

If we just blocked all term downgrades via the variant picker (and then blocked the variant picker itself if the current item in the cart is a term downgrade) that might solve all the above, both the preexisting issues and the new one?

File: client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx [hunk 2]
```diff
@@ -987,7 +987,6 @@ WPLineItem.propTypes = {
 	hasDeleteButton: PropTypes.bool,
 	removeProductFromCart: PropTypes.func,
 	product: PropTypes.object.isRequired,
-	getItemVariants: PropTypes.func,
```
Comment (DavidRothstein) [inline client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx]: I don't know how much it matters, but would it make sense to add the new properties here (`allowVariants` and `siteId`) while removing the old ones?

**Review by DavidRothstein — COMMENTED** [review]
This looks very good and mostly seems to work as expected with both WPCOM and Jetpack.  I did find a couple edge cases that might need attention though (see inline comment).

File: client/my-sites/checkout/composite-checkout/hooks/product-variants.tsx (hunk 1 above)
Comment (sirbrillig) [reply client/my-sites/checkout/composite-checkout/hooks/product-variants.tsx]: > Switch to a 2-year plan; notice that monthly is no longer available, so you can't switch back. (That's new behavior with this pull request.)

Oh... that wasn't intentional. Downgrading terms for the _same_ plan was supposed to be allowed. In fact, that's why `canUpgradeToPlan` is there. I thought that was what we were supposed to be doing.

> If we just blocked all term downgrades via the variant picker (and then blocked the variant picker itself if the current item in the cart is a term downgrade) that might solve all the above, both the preexisting issues and the new one?

Sounds reasonable. I'll give that a shot!

File: client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx (hunk 2 above)
Comment (sirbrillig) [reply client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx]: Yes, good point. TypeScript is much more reliable than PropTypes, so in general I just stop using PropTypes when code is converted to TS, but that's not really a good reason to let existing ones get out of date; that's especially true here since this file is in `client` which doesn't have active type checking.

**Comment by sirbrillig** [comment]
> If we just blocked all term downgrades via the variant picker 

I think this is done now.

> and then blocked the variant picker itself if the current item in the cart is a term downgrade

I just need to figure out how to do this.

It'd also be nice if I could add automated tests for all these cases.

**Comment by DavidRothstein** [comment]
While filing a different issue (https://github.com/Automattic/wp-calypso/issues/54341), I noticed that the after-PR screenshot from above is actually confusing:

123002711-37c71280-d380-11eb-8281-bff27deb04da

The "Save 24%" and "Save 37%" are comparing to the monthly price, but now we're showing them without a monthly option present.  That makes it pretty much impossible to understand what they mean.

Two possible ways to fix this:
1. Remove the "Save X%" entirely in this case (i.e. extending what was done in https://github.com/Automattic/wp-calypso/pull/50798)
2. Change it so that it displays the percentage discount for the two-year plan compared to the one-year plan instead (i.e. make the code smart enough to always show the discount compared to the lowest-term plan that is available, rather than hardcoding it to monthly).  This was the behavior originally proposed in https://github.com/Automattic/wp-calypso/issues/50799 also.

Ideally I think we'd go with option 2 here (since unlike the previous time we ran into this, this one is actually a pretty common case).  But we could probably get away with option 1.

**Comment by sirbrillig** [comment]
Because it makes this PR very noisy, I've extracted the refactoring and adding the new tests into their own PR here: https://github.com/Automattic/wp-calypso/pull/54365

**Comment by sirbrillig** [comment]
@DavidRothstein I think I've covered all the issues you described above, and there are unit test for them as well. We now calculate the crossed-out total (and therefore the discount percentage) based on the smallest visible variant's full price, and I blocked displaying the variant picker at all if the cart item is a variant of your active plan (up or down, which is more than you had suggested but it seemed reasonable to me). What do you think?

**Comment by nbloomf** [comment]
Looks good! I tested the following upgrade paths:

Free -> Monthly Personal

Screen Shot 2021-07-09 at 11 40 32 AM

Monthly Personal -> Annual Premium

Screen Shot 2021-07-09 at 11 43 23 AM

Annual Premium -> Biannual Business

Screen Shot 2021-07-09 at 11 45 37 AM

Biannual Business -> eCommerce

Screen Shot 2021-07-09 at 11 47 16 AM

**Review by nbloomf — APPROVED** [review]

File: client/my-sites/checkout/composite-checkout/hooks/product-variants.tsx [hunk 3]
```diff
@@ -100,13 +125,84 @@ export function useGetProductVariants(
...
+	allVariants.sort( ( variantA, variantB ) => {
+		const variantAInterval = getTermDuration( variantA.plan.term );
+		const variantBInterval = getTermDuration( variantB.plan.term );
+		return variantAInterval - variantBInterval;
+	} );
+	const lowestVariant = allVariants[ 0 ];
+	const lowestVariantInterval = getTermDuration( lowestVariant.plan.term );
+	const variantInterval = getTermDuration( variant.plan.term );
+	const lowestVariantIntervalsInVariantInterval = Math.ceil(
+		variantInterval / lowestVariantInterval
```
Comment (DavidRothstein) [inline client/my-sites/checkout/composite-checkout/hooks/product-variants.tsx]: This works, but partially by coincidence... it basically works because we're representing a month term as 31 days right now.  If it were 30 days instead (a reasonable representation), then you'd have `Math.ceil( 365 / 30 ) = 13`, which is wrong.

I think it might be better to use `getBillingMonthsForTerm()` to figure out the exact ratio, similar to what the previous code did.

**Review by DavidRothstein — COMMENTED** [review]
>I blocked displaying the variant picker at all if the cart item is a variant of your active plan (up or down, which is more than you had suggested but it seemed reasonable to me)

Mostly, but it does mean there's no longer a path in Calypso to upgrade from monthly to bi-yearly for the same product (currently it's possible by choosing the option to upgrade from monthly to yearly on the plans page, then using the variant selector to go bi-yearly).  But that seems like kind of a backdoor option now, and as far as I can see there's already no way to go yearly to bi-yearly anyway.... So I think it's probably OK and no big loss.  I could imagine having to revisit this in the future, though, since doing it this way does block completely valid upgrade paths.

Otherwise, this looks great to me (I left one small inline comment).  I also tested some of the scenarios not tested above (including upgrades that change the billing term without changing the plan, and Jetpack upgrades), and it all seemed good to me.

**Review by DavidRothstein — APPROVED** [review]
Thanks - seems great to me now!

**Comment by sirbrillig** [comment]
> Mostly, but it does mean there's no longer a path in Calypso to upgrade from monthly to bi-yearly for the same product (currently it's possible by choosing the option to upgrade from monthly to yearly on the plans page, then using the variant selector to go bi-yearly). But that seems like kind of a backdoor option now, and as far as I can see there's already no way to go yearly to bi-yearly anyway.... So I think it's probably OK and no big loss. I could imagine having to revisit this in the future, though, since doing it this way does block completely valid upgrade paths.

Yeah, I intentionally was simplifying the possible paths because it seemed to me that there were some cases that were possible and maybe not well supported and I also didn't like the UX of a user getting stuck not being able to go back to a variant after changing one. I'm certain we'll need to revisit some of this logic in the future, but this way the obvious problems should be fixed and future modifications can be additive from a safe base (particularly now that the cases are covered by tests).
