### PR TITLE
Site Monitoring: Add 429 Errors to Filter

### LINKED ISSUE #90868: Site Monitoring: 429 not available as a filter
### Quick summary

429 isn't available from the drop down filter
2024-05-19 at 12 33

### Steps to reproduce

1. on a WoA site go to Tools > Site monitoring > server logs
2. open the status filter dropdown
3. look for 429

### What you expected to happen

Since this is one of the statuses that users are likely to be most interested in, I expected it to be an option

### What actually happened

can't filter by 429s

they can download the entire log and manually filter but it makes more sense to have the filter on our end

### Impact

All

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

would be nice if the filter was a multi-select rather than a single select

### PR DESCRIPTION
**Pull request by Aurorum**
Fixes #90868

## Proposed Changes

* Adds the 429 HTTP error to the Status dropdown under Site Monitoring. Incidentally, everything is already set up to filter those requests, including the API request - I assume it was simply just an oversight not to include it in the filter? 

Screenshot 2024-05-19 at 14 31 45

## Why are these changes being made?

See #90868. I also think this handles some of my concerns in #90306 by making those errors more accessible - at least I see where issues have arisen now! 

## Testing Instructions

Visit `/site-monitoring/SITE/web`, and confirm that "429" appears in the dropdown and works appropriately.

cc @sejas

### CODE REVIEW

File: client/my-sites/site-monitoring/components/site-logs-toolbar/index.tsx [hunk 1]
```diff
@@ -103,14 +103,15 @@ export const SiteLogsToolbar = ( {
 
 	const requestStatuses = [
 		{ value: '', label: translate( 'All' ) },
-		{ value: '200', label: translate( '200' ) },
```
Comment (Aurorum) [inline client/my-sites/site-monitoring/components/site-logs-toolbar/index.tsx]: I'd appreciate a sanity check here but I can't see why these numbers should be translated - any translator would just use the default number: 

Screenshot 2024-05-19 at 14 27 52

If the aim is to localise it based on decimal places, it might be better to use `formatNumber` - but that seems unnecessary for HTTP requests where you'd probably want the label to be exactly as shown instead.

Comment (wojtekn) [reply client/my-sites/site-monitoring/components/site-logs-toolbar/index.tsx]: Some languages don't use Arabic digits and use different characters instead. I'm unsure if they translate HTTP codes, though. If it doesn't do harm, I would leave it as before.

**Comment by wojtekn** [comment]
Thanks for contributing the fix @Aurorum !

It looks good, as it fixes the missing 429 filter option. In the future, we could add a more straightforward fix and fill the filter values based on the data received from the API.

File: client/my-sites/site-monitoring/components/site-logs-toolbar/index.tsx (hunk 1 above)
Comment (Aurorum) [reply client/my-sites/site-monitoring/components/site-logs-toolbar/index.tsx]: Ah, I see, thanks! I've switched it to `formatNumber` which should handle this without translators for each language needing to handle 9 different strings - do you think that might be okay? It seems to be the common approach for handling digits in Calypso: https://github.com/search?q=repo%3AAutomattic%2Fwp-calypso+numberformat&type=code&p=1

**Comment by Aurorum** [comment]
Thanks @wojtekn! Agreed re. the API - the only problem at the moment is that it only contains the first fifty responses, so I think the API itself would need to be updated in order to return a list of all the status codes.

File: client/my-sites/site-monitoring/components/site-logs-toolbar/index.tsx (hunk 1 above)
Comment (sejas) [reply client/my-sites/site-monitoring/components/site-logs-toolbar/index.tsx]: I think we can remove the `numberFormat`. I think that's used when it has decimals, so the comma and dot can be used in the right place.

**Review by sejas — COMMENTED** [review]
Thanks for adding the 429 error.
I would leave the previous translation, so this PR can address an unique change that is easy to understand.

File: client/my-sites/site-monitoring/components/site-logs-toolbar/index.tsx (hunk 1 above)
Comment (Aurorum) [reply client/my-sites/site-monitoring/components/site-logs-toolbar/index.tsx]: Sure, I've switched it back for now - I think that it localises it too, but the more I look into it, I'm not sure that this needs a `translate` at all (it looks like all Calypso languages use Arabic digits?). But I might be missing something, and possibly not in-scope for this PR!

Comment (wojtekn) [reply client/my-sites/site-monitoring/components/site-logs-toolbar/index.tsx]: @Aurorum thanks for changing it. I've checked this more with the translations team and got feedback saying that HTTP error codes should be displayed as digits in all languages. Thus it's okay in the current PR, and we can optionally remove `translate()` call for them under a separate PR.

**Review by wojtekn — APPROVED** [review]

File: client/my-sites/site-monitoring/components/site-logs-toolbar/index.tsx (hunk 1 above)
Comment (Aurorum) [reply client/my-sites/site-monitoring/components/site-logs-toolbar/index.tsx]: Thanks for the review, and for asking the i18n team about this! I've proposed removing them in #90920. :)
