### PR TITLE
Help Center: styling changes

### LINKED ISSUE #63547: Task: Help Center Sizing
### Details

This help-center can be too big for some screens.

### Checklist

- [ ] Make sure the HC works on smaller desktop screens
- [ ] Test against regression in mobile.

### Related

_No response_

### PR DESCRIPTION
**Pull request by arcangelini**
## Changes proposed in this Pull Request

More styling changes. These address all the current comments in #63275 

Related to #63275
Fixes #63547

### CODE REVIEW

File: packages/help-center/src/components/help-center-header.tsx [hunk 1]
```diff
@@ -50,8 +50,16 @@ const HelpCenterMobileHeader: React.FC< Header > = ( {
...
+				<p
+					style={ {
+						maxWidth: 300,
+						fontSize: 14,
+						fontWeight: 500,
+						display: 'flex',
+						alignItems: 'center',
+					} }
+				>
+					<span className="help-center-header__title">{ headerText }</span>
```
Comment (escapemanuele) [inline packages/help-center/src/components/help-center-header.tsx]: Why did you remove the class and add again the inline styles? I see that `help-center-header__text` is still in the scss file, and I'm not sure but this could be making us [lose some styles](https://github.com/Automattic/wp-calypso/pull/63639/files#diff-106247b3ddab08d2998bd029a32a570711ab72f884cc01410803133094e59406R40-R44)

File: client/blocks/inline-help/inline-help-center-content.scss [hunk 2]
```diff
@@ -336,7 +341,7 @@
 * ARTICLE EMBED
 */
 .help-center .help-center__container .inline-help__embed-result {
-	h1.support-article-dialog__header-title-link {
+	h1.support-article-dialog__header-title {
 		font-size: $font-title-medium;
```
Comment (escapemanuele) [inline client/blocks/inline-help/inline-help-center-content.scss:350]: May it be overridden? I see the h1 as 24px, but the a inside as 36px

**Review by escapemanuele — CHANGES_REQUESTED** [review]
Thanks for this! Styling is hard 👍 
I found a few things that I'll show in the comments and:
- `inline-help__resource-cell a`, still maintains the focus after clicking (the blue border)

Moreover, I'd ask @poligilad-auto to review the changes 👍

File: packages/help-center/src/components/help-center-header.tsx (hunk 1 above)
Comment (arcangelini) [reply packages/help-center/src/components/help-center-header.tsx]: Hmm I thought you added that. I think I may have gotten some branches crossed while working on this. I will remove it. Nice catch! 🎣

Comment (escapemanuele) [reply packages/help-center/src/components/help-center-header.tsx]: Well I added the `help-center-header__text` class and removed the inline styles 😄 I think we should not have the inline styles but the class I introduced, wdyt?

**Review by poligilad-auto — APPROVED** [review]
Go ahead and merge this @arcangelini, I prefer to review the changes when it's live as I seem to have issues seeing them with the sandbox. We are still in testing phases so it's easier to review that way.

File: packages/help-center/src/components/help-center-header.tsx (hunk 1 above)
Comment (arcangelini) [reply packages/help-center/src/components/help-center-header.tsx]: Totally agree. I fixed it and tested. Everything is working great still. Also updated this `inline-help__resource-cell a, still maintains the focus after clicking (the blue border)`

**Review by escapemanuele — APPROVED** [review]
