### PR TITLE
Fix: verified provider component shows the hosting provider

### LINKED ISSUE #82598: [Bug] Site Profiler: the verified provider component shows the hosting provider
See http://calypso.localhost:3000/site-profiler?domain=karenroldan.blog

The `VerifiedProvider` component does show the hosting provider but it should always show the domain registrant.

### PR DESCRIPTION
**Pull request by zaerl**
Context: p1696422641343489-slack-C01A60HCGUA
Fixes: https://github.com/Automattic/wp-calypso/issues/82598

## Proposed Changes

* Fix the verified provider output

## Testing Instructions

* http://calypso.localhost:3000/site-profiler?domain=wecanwang.com should be "Pressable" and "WordPress.com"
* http://calypso.localhost:3000/site-profiler?domain=cagrimmett.com should be "Pressable" and "Tucows"
* http://calypso.localhost:3000/site-profiler?domain=home.blog should be "WordPress.com" and "Knock knock"
* Other domains must work as well.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: client/site-profiler/components/domain-information/verified-provider.tsx [hunk 1]
```diff
@@ -22,9 +23,15 @@ export default function VerifiedProvider( props: Props ) {
 				{ /* eslint-disable wpcalypso/jsx-gridicon-size */ }
 				<Gridicon icon="checkmark" size={ 10 } />
 			</span>
-			<a href={ hostingProviderHomepage }>{ hostingProviderName }</a>
-			&nbsp;&nbsp;
-			<a href={ hostingProviderLogin }>({ translate( 'login' ) })</a>
+			<a href={ showHosting ? 'https://wordpress.com' : hostingProviderHomepage }>
+				{ showHosting ? translate( 'WordPress.com' ) : hostingProviderName }
```
Comment (ouikhuan) [inline client/site-profiler/components/domain-information/verified-provider.tsx]: The naming `showHosting` confused me a little, if this means "showing hosting provider" it seems the condition there needs to be the other way around.  I was expecting something like `overwriteWithPlatform`, and passing the props down to `useHostingProviderName`, `useHostingProviderURL` and `useHostingProviderURL` so we don't need to touch this level too much. But what you proposed is easier, so I'm fine with this, but we might want to reconsider the prop naming here.

File: client/site-profiler/components/domain-information/verified-provider.tsx [hunk 2]
```diff
@@ -22,9 +23,15 @@ export default function VerifiedProvider( props: Props ) {
...
+			</a>
+			{ ! showHosting && (
```
Comment (ouikhuan) [inline client/site-profiler/components/domain-information/verified-provider.tsx]: After rethinking this again. I think it'll still be great to show login link if someone has their domain registered with us but hosting elsewhere, so they can log in to manage their domain. Here's one example to test:
http://calypso.localhost:3000/site-profiler?domain=karenroldan.blog

File: client/site-profiler/components/domain-information/verified-provider.tsx (hunk 1 above)
Comment (zaerl) [reply client/site-profiler/components/domain-information/verified-provider.tsx]: Yeah. I tried to find a better name. Because this component is used in two different places. Maybe we should have two different components:

1. Section "Domain information": `<VerifiedProvider />` or simply `<VerifiedRegistrar />` the (verified) **domain registrar** (us). Shown as `WordPress.com`.
2. Section "Hosting information": `<VerifiedHostingProvider />` or simply `<VerifiedProvider />`. It's us again as the **hosting provider**, but it can be WPCOM, Pressable etc.

But I wanted to add only a little code in these last hours.

File: client/site-profiler/components/domain-information/verified-provider.tsx (hunk 2 above)
Comment (zaerl) [reply client/site-profiler/components/domain-information/verified-provider.tsx]: Nice idea.

**Review by ouikhuan — APPROVED** [review]
LGTM, thanks for making the changes! 🚢
