### PR TITLE
Admin color: block layout render when still fetching

### LINKED ISSUE #100959: WordPress.com Dashboard visual glitch
### Context and steps to reproduce

This was reported here: 9493798-zd-a8c

Left menu bar turns to a different color briefly upon login before returning to the Color Scheme that was chosen.
Occurs every time a user logs in. 

It doesn't happen with the default color scheme: 

https://github.com/user-attachments/assets/3cf5ea74-27b4-4641-a0b9-32c8e0c08b69

With other color schemes: 

https://github.com/user-attachments/assets/b65edf2e-d589-4f80-9af3-276713abf819

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Minor

### What other impact(s) does this issue have?

No revenue impact

### If a workaround is available, please outline it here.

No workaround as it doesn't impact the usage.

### Platform

Atomic, Simple

### PR DESCRIPTION
**Pull request by fushar**
Fixes DOTCOM-205
Fixes https://github.com/Automattic/wp-calypso/issues/100959

## Proposed Changes

This PR "solves" the issue where the user sees the default admin color scheme for a split second while  fetching the user's admin color. This happens when the redux store is empty during the first login. The fix is to not render the screen when this happens.

Note that this is only an "edge" case where the user first logs in. Afterwards, the admin color is in the redux store always and we never block the render anymore.

> [!NOTE]  
> This deliberately does not address the case when the user changes the admin color via `profile.php`.

### Before

https://github.com/user-attachments/assets/0d07d883-0f8f-419e-8219-edbe44aea4d2

### After

https://github.com/user-attachments/assets/80396059-43f1-447a-9398-da0e8bd9eba8

## Why are these changes being made?

Fixes visual bug.

## Testing Instructions

I found that the only reliable way to test these changes is to check out the branch locally, run Calypso locally, then add the `?flags=force-sympathy` query param.

1. Prepare a site with a non-default color scheme.
2. Run Calypso locally.
3. Go to `/home/:siteSlug?flags=force-sympathy`.
4. Notice the flash of color scheme from default to the actual.
5. Now, check out this PR's branch.
6. Repeat the above, verify that no flash occurs anymore.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [x] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/state/admin-color/selectors/index.js [hunk 1]
```diff
@@ -3,3 +3,7 @@ import 'calypso/state/admin-color/init';
 export function getAdminColor( state, siteId ) {
 	return state?.adminColor?.[ siteId ] || null;
 }
+
+export function isFetchingAdminColor( state, siteId ) {
+	return ! state?.adminColor?.[ siteId ];
```
Comment (StevenDufresne) [inline client/state/admin-color/selectors/index.js:8]: Did you consider adding a loading property to the [state](https://github.com/Automattic/wp-calypso/blob/c4d88f57af9784b7c862c9abf0eae72a5f6cffee/client/state/admin-color/reducer.js#L6)?

That would allow us to [handle a request failure](https://github.com/Automattic/wp-calypso/blob/c4d88f57af9784b7c862c9abf0eae72a5f6cffee/client/state/data-layer/wpcom/sites/admin-color/index.js#L24) properly. 

Currently, it seems like if `/sites/${ action.siteId }/admin-color/` fails, we won't render the Masterbar. 

Since color is not critical to our user stories, we probably want to avoid that scenario.

Comment (fushar) [reply client/state/admin-color/selectors/index.js:8]: Oh, nice catch!

I updated the code to fall back to the `default` scheme, when the request fails while the persisted value is still empty (i.e., during the first login). Note that if the request fails while the persisted value is already available, it won't do anything. This way the masterbar/sidebar will always render in all cases.

I wasn't able to add a "requesting" property cleanly to the state, because somehow the shape of the value in the redux state is just the string value, not an object 🥲 So the alternative is to add another `adminColorRequesting` reducer, which I feel is too much given that this will go away in the future after Untangling Calypso is finished.

**Review by StevenDufresne — APPROVED** [review]
Nice!

This is working as expected and cleans up the color shift. 👍

File: client/layout/index.jsx [hunk 2]
```diff
@@ -420,6 +429,8 @@ export default withCurrentRoute(
 			isOffline: isOffline( state ),
 			currentLayoutFocus: getCurrentLayoutFocus( state ),
 			colorScheme,
+			needsColorScheme: ! shouldShowGlobalSidebar,
```
Comment (fushar) [inline client/layout/index.jsx:432]: This condition is wrong. Will investigate later...

Comment (fushar) [reply client/layout/index.jsx:432]: Basically got bitten by the convoluted logic; see paYKcK-5Qk-p2 😅

Comment (StevenDufresne) [reply client/layout/index.jsx:432]: Dang. :(
