### PR TITLE
Sites: Restore `permalink_structure` options request

### LINKED ISSUE #14884: Cannot edit post slug
The ability to edit a post slug is no longer available.  When I click on the link icon next to the title, the only option is to copy the URL.  Opening the More Options panel, the post slug no longer appears above the Excerpt box.

The page slug option has disappeared under the More Options tab as well, although I can edit page slugs if I click on the link icon next to the page title.

**Steps to reproduce:**
1) Open a post to edit.
2) Click on the link icon next to the title - option to edit slug unavailable.
3) Click on the More Options tab in the Settings sidebar  - option to edit slug unavailable.

**What I expected**
To see the box to edit post slugs when opening More Options, or to click on the end of the URL to edit when clicking on the Link icon next to the post title.

**What happened instead**
The options are gone/unavailable.

**Screenshots**
link next to title
more options panel

#user-report

### PR DESCRIPTION
**Pull request by aduth**
Fixes #14884 
Regression of #14096

This pull request seeks to restore `permalink_structure` option to the sites request, used by the `areSitePermalinksEditable` selector to determine whether slug editing should be offered:

https://github.com/Automattic/wp-calypso/blob/b6c1830/client/state/selectors/are-site-permalinks-editable.js#L14

__Testing instructions:__

Repeat testing instructions from #14884, confirming that slugs are editable.

cc @designsimply @vparkhere

### CODE REVIEW

File: client/lib/sites-list/list.js [hunk 1]
```diff
@@ -82,7 +82,7 @@ SitesList.prototype.fetch = function() {
...
-		options: 'is_mapped_domain,unmapped_url,admin_url,is_redirect,is_automated_transfer,allowed_file_types,show_on_front,main_network_site,jetpack_version,software_version,default_post_format,created_at,frame_nonce,publicize_permanently_disabled,page_on_front,page_for_posts,advanced_seo_front_page_description,advanced_seo_title_formats,verification_services_codes,podcasting_archive,is_domain_only,default_sharing_status,default_likes_enabled,wordads,upgraded_filetypes_enabled,videopress_enabled' //eslint-disable-line max-len
+		options: 'is_mapped_domain,unmapped_url,admin_url,is_redirect,is_automated_transfer,allowed_file_types,show_on_front,main_network_site,jetpack_version,software_version,default_post_format,created_at,frame_nonce,publicize_permanently_disabled,page_on_front,page_for_posts,advanced_seo_front_page_description,advanced_seo_title_formats,verification_services_codes,podcasting_archive,is_domain_only,default_sharing_status,default_likes_enabled,wordads,upgraded_filetypes_enabled,videopress_enabled,permalink_structure' //eslint-disable-line max-len
```
Comment (blowery) [inline client/lib/sites-list/list.js]: these would be a lot easier to read if they were an array of values with a join. like ```
[ 
'one',
'two',
].join( ',' )
```

Comment (aduth) [inline client/lib/sites-list/list.js]: @blowery I agree

Comment (aduth) [inline client/lib/sites-list/list.js]: But not here 😄

**Comment by designsimply** [comment]
I tested with following steps:

1. Run `git checkout fix/14884-sites-option-permalinks` and start a local server.
1. Go to http://calypso.localhost:3000
1. Open a post to edit.
1. Click on the link icon next to the title, edit the post slug, save changes.
1. Go to More Options in the Editor sidebar and make sure the Slug option is present and reflects the change.
1. Visit the post on the front end and make sure the slug edit was applied.

screen shot 2017-06-08 at thu jun 8 9 20 11 am
<sup>Seen at http://calypso.localhost:3000/post/design5279.wordpress.com/11094 using Chrome 58.0.3029.110 on Mac OS X 10.12.5.</sup>

👍  LGTM. Thank you!
