### PR TITLE
desktop: fix print codes

### LINKED ISSUE #910: "Print codes" button for 2FA backup codes fails silently
#### Steps to reproduce
1. Activate 2FA
2. In the **Generate Backup Codes** stage, click Print Codes
3. Confirm that it fails silently

#### What I expected
Upon clicking Print codes, a prompt should appear.

#### What happened instead
Nothing happens on click.

#### App Version / OS version
6.0.0-beta2 / Mac OS 10.13

#### Screenshot / Video
https://cloudup.com/ciuGadMso39

#### Context / Source
Reported initially at https://wp.me/p5T066-1l3#comment-5074

#manual-testing #dogfooding

### PR DESCRIPTION
**Pull request by nsakaimbo**
### Description

This PR fixes the "print recovery codes" feature in wp-desktop, which was (for some reason) silently failing.

The event emitted from Calypso is also refactored to be consistent with other desktop events (i.e. use redux and desktop-specific middleware).

### To Test

Download, extract and run the artifacts built from Automattic/wp-desktop#928. From your profile, add two-factor authentication and select the "print recovery codes" button.

<p align="center">

</p>

Fixes Automattic/wp-desktop#910.

### CODE REVIEW

File: client/state/desktop/middleware.js [hunk 1]
```diff
@@ -90,6 +92,20 @@ export const desktopMiddleware = () => {
 				);
 				return next( action );
 
+			case SEND_TO_PRINTER: {
+				debug( 'Dispatching window event for action type: ', action.type );
+				const { title, contents } = action;
+				window.dispatchEvent(
+					new window.CustomEvent( NOTIFY_DESKTOP_SEND_TO_PRINTER, {
```
Comment (sgomes) [inline client/state/desktop/middleware.js:99]: We should be polyfilling `CustomEvent`, but it might be worth giving this a try in IE 11 to make sure it works. I'm unable to do so because of security restrictions on live branches, though 😕

**Review by sgomes — APPROVED** [review]
The code looks good to me, but I was unable to test due to security restrictions on the live branches. I added one comment for some compatibility testing.

File: client/state/desktop/middleware.js (hunk 1 above)
Comment (nsakaimbo) [reply client/state/desktop/middleware.js:99]: Thanks for the review!

My understanding is the desktop middleware is only included when Calypso is being built for the desktop app ([link](https://github.com/Automattic/wp-calypso/blob/e5b2796be1e4e11ae55e228ab5e8ccea3327fc0b/client/state/index.js#L62)). I think this means we can assume this code will be executed only in a Chrome context?

Would the polyfill for window.CustomEvent be necessary, in this case?

**Comment by nsakaimbo** [comment]
Merging - ignoring what appears to be a flakey test, unrelated to this PR in `ci/circleci: test-e2e-canary-woo`:

`FAIL (will retry, 1 time(s) left). Spent 52004 ms Can see WooCommerce settings in Calypso 'mobile' @parallel`

File: client/state/desktop/middleware.js (hunk 1 above)
Comment (sgomes) [reply client/state/desktop/middleware.js:99]: Ah, no, if that's the case then there's no need for confirming whether the polyfill is working for this 👍
