### PR TITLE
Fix sites being duplicated on `/sites` page.

### LINKED ISSUE #89825: Sites: Websites are duplicated on the Sites page
### Quick summary

The `Sites` page at `https://wordpress.com/sites` shows duplicate sites.
Screenshot 2024-04-23 at 4 12 31 PM

### Steps to reproduce

1. Go to WordPress.com
2. Click on "All Sites" at the top left corner.
3. View the Sites page with the duplicates.

### What you expected to happen

Only show each site once.

### What actually happened

Each site is listed twice.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

**Workaround**: Reloading the page seems to fix the issue.

This seems to occur on random sites, it's difficult to pin down an exact reason, and seems unrelated to the number of sites an account might own.  It happens on some accounts and not others.

It can be reproduced with account `mrsenff`.

### PR DESCRIPTION
**Pull request by vykes-mac**
Closes https://github.com/Automattic/wp-calypso/issues/89825

## Proposed Changes
The issue being encountered is that on the sites page the `useSiteExcerptsQuery` hook is being used twice, to get all sites and also deleted sites which are then concatenated. What happens is that there are cases where `initialData` is used to fetch sites from the redux store as a result the same data is fetched twice, the second time they are flagged as deleted sites then concatenated to the live sites causing duplications.

This PR uses the `site_owner` field to determine if a site was deleted instead of always setting it to true when the  `site_visibility = deleted`. Deleted sites do not have an owner

* Use site_owner to flag deleted sites.

## Testing Instructions

This is not reproducible on all sites so we have to use a user that's having the issue.
* In MC go to Tools > support user
* Set user to `mrsenff` and environment to `calypso.localhost`
* Click all sites and you will see sites are duplicated
* checkout branch
* do the same steps and click all sites and see sites are no longer duplicated.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)

### CODE REVIEW

File: client/sites-dashboard/components/sites-dashboard.tsx [hunk 1]
```diff
@@ -184,7 +184,7 @@ export function SitesDashboard( {
 
 	const { data: deletedSites = [] } = useSiteExcerptsQuery(
 		[],
-		( site ) => ! site.options?.is_domain_only,
+		( site ) => ! site.options?.is_domain_only && !! site?.is_deleted,
```
Comment (p-jackson) [inline client/sites-dashboard/components/sites-dashboard.tsx]: I feel like this logic probably belongs inside `useSiteExcerptsQuery()`. The called has passed the `'deleted'` option, and so it feels like the query hook should hide all the messiness that comes from the fact that this data might actually be loaded from the redux cache.

The `is_domain_only` filtering would stay in the component, but the `is_deleted` check would be inside `useSiteExcerptsQuery`

**Review by p-jackson — COMMENTED** [review]
The fix makes sense, but I think the underlying issue isn't addressed. The optimisation of using redux data if it's available depends on an assumption, the assumption that the data in redux is a strict _superset_ of the site excerpt data. If there's fields in `SiteExcerptData` that aren't in `SiteDetails` then it's not really an "excerpt" 😅

I think the underlying problem is that `useSiteExcerptsQuery` queries for the `is_deleted` flag but Redux doesn't I think the fix should be to make Redux also request that flag.

That can be done in `client/state/sites/constants.js` which defines which fields the Redux store requests.
https://github.com/Automattic/wp-calypso/blob/867d91b103b19b7bd76bdd55686b94fdcb177c44/client/state/sites/constants.js#L6

If we add `is_deleted` here, then there's no need to infer the deleted state based on the owner id.

You could add the `p2_thumbnail_elements` field too for good measure, which is requested by the excerpt query but not by Redux.

File: client/sites-dashboard/components/sites-dashboard.tsx (hunk 1 above)
Comment (p-jackson) [reply client/sites-dashboard/components/sites-dashboard.tsx]: Another reason to do this logic in `useSiteExcerptsQuery` is because there are multiple places which make the request for deleted sites and they'd all need this same logic.

For example:

https://github.com/Automattic/wp-calypso/blob/867d91b103b19b7bd76bdd55686b94fdcb177c44/client/sites-dashboard-v2/index.tsx#L128

**Comment by vykes-mac** [comment]
Would that work even though the `is_deleted` flag is not something that is returned from the api call but is set based on the `site_visibility` that's passed to the hook. As u can see `is_deleted` was always been set to `true` solely based on the visibility parameter.

**Comment by p-jackson** [comment]
Oh I see, it's not a real field! I thought the `is_deleted = true` code was just another work around for what I _thought_ was some underlying issue. This makes more sense.

In that case I still think the `is_deleted` deleted filtering logic should be done _inside_ the hook. But using the `site_owner` field to guess at the deleted status makes more sense.

What do you think about, when the hook is running in `site_visibility=deleted` mode, that it doesn't grab cached data from Redux at all? This is an optimisation to make loading faster, but in the case of deleted sites (which the user has to manually choose from the drop down) is it ok to always load that list fresh from the server? I'm just thinking of future proofing, will it always be the case that `site_owner === undefined` is equivalent to the site being deleted? 🤷

**Comment by mpkelly** [comment]
How about fixing this on the backend? I never liked that we did two queries, but I accepted it because initially, we decided only to show deleted sites if you filtered to "deleted" and not for "all." 

We could update the endpoint callback to include deleted sites for "all" and "deleted" statuses and then remove the code from the original PR, which wouldn't be necessary. This feels like a much nicer solution, where "deleted" is just another status we handle like the others. We could still merge this PR as a quick fix.

**Comment by mpkelly** [comment]
>This is not reproducible on all sites so we have to use a user that's having the issue.

Do we know why this is?

**Comment by p-jackson** [comment]
> Do we know why this is?

No I'm not sure. At first I thought I'd be able to easily reproduce it be carefully clearing the indexDB so that I always caused duplicates. But that didn't seem to work 🤷‍♂️

> How about fixing this on the backend?

Yeah that's another good point. If it's fetching `"all"` then surely the backend should just return `"all"`.

> We could still merge this PR as a quick fix.

Now that I more fully understand what's going on, 👆 this makes sense. Merging it using this solution and then fixing up the backend.

I still think the new `sitesFilterFn` logic which has been added to the sites dashboard should be added to the hook though. The other uses of `useSiteExcerptsQuery( ..., ..., 'deleted' )` in the codebase need that filtering logic too.

**Comment by vykes-mac** [comment]
> How about fixing this on the backend? I never liked that we did two queries, but I accepted it because initially, we decided only to show deleted sites if you filtered to "deleted" and not for "all." 
> 
> 
> 
> We could update the endpoint callback to include deleted sites for "all" and "deleted" statuses and then remove the code from the original PR, which wouldn't be necessary. This feels like a much nicer solution, where "deleted" is just another status we handle like the others. We could still merge this PR as a quick fix. 



Yeah fixing it on the backend is ideal, I looked into that but wanted to create a quick fix since the backend would involve adding
The field Jetpack

**Comment by vykes-mac** [comment]
The change make sense @p-jackson , feel free to merge

**Review by p-jackson — APPROVED** [review]
