### PR TITLE
Image Editor: store the original image aspect ratio, fix rotation crop bug

### LINKED ISSUE #9738: Image Editor: aspect ratio original while rotating has incorrect crop area
Originally reported in https://horizonfeedback.wordpress.com/2016/11/30/call-for-testing-image-editing/comment-page-1/#comment-264 

To reproduce:
1. Edit an image
2. Rotate
3. Set aspect ratio to Original
4. Rotate again
5. Crop area does not over entire image

http://www.screencast.com/t/94yddIzk2

### PR DESCRIPTION
**Pull request by gwwar**
Fixes #9738 where the crop area would be incorrect, when selecting the original aspect ratio and then rotating the image.

Originally reported in https://horizonfeedback.wordpress.com/2016/11/30/call-for-testing-image-editing/comment-page-1/#comment-264 

### Testing Instructions
1. Navigate to http://calypso.localhost:3000/post
2. Select a site
3. Open the media modal
4. Edit an image
5. Set aspect ratio to Original
6. Rotate

The crop should cover the entire image. Resizing then rotating should work like the other aspect ratios.

### CODE REVIEW

File: client/state/ui/editor/image-editor/actions.js [hunk 1]
```diff
@@ -99,8 +99,10 @@ export function imageEditorCrop( topRatio, leftRatio, widthRatio, heightRatio )
 	};
 }
 
-export function setImageEditorImageHasLoaded() {
+export function setImageEditorImageHasLoaded( width, height ) {
 	return {
-		type: IMAGE_EDITOR_IMAGE_HAS_LOADED
+		type: IMAGE_EDITOR_IMAGE_HAS_LOADED,
+		width: width,
+		height: height
```
Comment (obenland) [inline client/state/ui/editor/image-editor/actions.js]: You could optionally use the shorthand here too

File: client/state/ui/editor/image-editor/reducer.js [hunk 2]
```diff
@@ -68,6 +69,13 @@ export function hasChanges( state = false, action ) {
 	return state;
 }
 
+export const originalAspectRatio = createReducer( null, {
+	[ IMAGE_EDITOR_IMAGE_HAS_LOADED ]: ( state, { width, height } ) => {
+		return { width, height };
+	},
```
Comment (obenland) [inline client/state/ui/editor/image-editor/reducer.js]: Not sure if there is a preference either way, but you could optionally also do 

```js
[ IMAGE_EDITOR_IMAGE_HAS_LOADED ]: ( state, { width, height } ) => ( { width, height } ),
```

Comment (gwwar) [inline client/state/ui/editor/image-editor/reducer.js]: I avoided the one-liner here since it'd go over 80 characters:

screen shot 2017-01-25 at 9 08 46 am

File: client/state/ui/editor/image-editor/actions.js (hunk 1 above)
Comment (gwwar) [inline client/state/ui/editor/image-editor/actions.js]: 👍 Updated in d0fd305

**Comment by gwwar** [comment]
Thanks for the reviews @retrofox and @obenland !
