### PR TITLE
Purchases: Show new pre-cancellation form when cancelling non-plan products

### LINKED ISSUE #65186: Lack of Atomic revert warning before cancelling a marketplace plugin
### Quick summary

We should display a warning before proceeding with the cancellation of a marketplace plugin that would cause the Atomic site to be reverted to Simple, like we do when a user tries to cancel a plan that would trigger an Atomic revert.

This is what we display right now when cancelling the last marketplace plugin:
Screen Shot 2022-07-04 at 10 05 38

And this is what we display when cancelling a plan that supports the Atomic feature:
Screen Shot 2022-07-04 at 10 06 30

We would probably need to amend the wording, since the site has been unable to use any custom theme or the SFTP access. Backups are supported either, so we should hide that part as well.

### Steps to reproduce

- Go to https://wpcalypso.wordpress.com
- Go to Plugins
- Purchase a paid plugin
- Go to Upgrades > Purchases
- Cancel the purchase

### What you expected to happen

To see a warning indicating that my site will be set to private and that it's going to be reverted to the point when I installed the paid plugin.

### PR DESCRIPTION
**Pull request by mmtr**
Fixes https://github.com/Automattic/wp-calypso/issues/65186
Part of https://github.com/Automattic/wp-calypso/issues/56393

Please note that reviewing these changes is much easier by using this diff view:
Screen Shot 2022-07-04 at 13 55 40

#### Proposed Changes

Displays the new pre-cancellation form introduced by https://github.com/Automattic/wp-calypso/pull/56206 when cancelling other products than plans, so we can show the Atomic revert warning before cancelling a marketplace plugin from an Atomic site with a Starter plan.

Before | After (step 1) | After (step 2)
--- | --- | ---
Screen Shot 2022-07-04 at 10 05 38 | Screen Shot 2022-07-04 at 15 13 14 | Screen Shot 2022-07-04 at 15 13 22

#### Testing Instructions

- Use the Calypso live link below
- Go to Plugins
- Purchase a paid plugin
- Go to Upgrades > Purchases
- Cancel the purchase
- Make sure you see the new cancellation form. In the first step you should be able to provide some feedback, and in the second step you should be warned about the Atomic revert.
- Make sure there are no regressions when cancelling a plan from a site (you should get the same cancellation form as in prod).
- Make sure you don't see the Atomic revert warning when cancelling a marketplace plugin from a site that has additional marketplace plugins
- Make sure you don't see the Atomic revert warning when cancelling other non-plan purchases that don't support the Atomic feature (e.g. the No Ads addon)

### CODE REVIEW

File: client/state/purchases/selectors/will-atomic-site-revert-after-purchase-deactivation.js [hunk 1]
```diff
@@ -22,8 +24,13 @@ export const willAtomicSiteRevertAfterPurchaseDeactivation = ( state, purchaseId
...
 	const purchase = getByPurchaseId( state, purchaseId );
 
-	const isAtomicSupportedProduct = ( productSlug ) =>
-		planHasFeature( productSlug, WPCOM_FEATURES_ATOMIC );
+	const isAtomicSupportedProduct = ( productSlug ) => {
+		if ( isEnabled( 'marketplace-starter-plan' ) && isMarketplaceProduct( state, productSlug ) ) {
+			return true;
+		}
+
+		return planHasFeature( productSlug, WPCOM_FEATURES_ATOMIC );
```
Comment (mmtr) [inline client/state/purchases/selectors/will-atomic-site-revert-after-purchase-deactivation.js:46]: I wish `planHasFeature( productSlug, WPCOM_FEATURES_ATOMIC )` would also work for marketplace products, so I don't need the hardcoded plan/product check above, but I think that's not trivial because the marketplace products are not listed in https://github.com/Automattic/wp-calypso/blob/trunk/packages/calypso-products/src/plans-list.tsx

**Review by obenland — CHANGES_REQUESTED** [review]
* The "< Back" link in "Proceed with caution" doesn't take me back to the feedback step but only to the purchases screen.
* When I try to cancel my plan, the selected dropdown options are invisible. image
* While on Atomic with a Marketplace plugin, when I remove my Starter plan it shows me a modal warning me that I also have to remove the Marketplace plugin. When I go through the steps it does not show me the "Proceed with caution" section even though the site will be reverted.

File: client/components/marketing-survey/cancel-purchase-form/index.jsx [hunk 2]
```diff
@@ -1250,12 +1008,20 @@ export default connect(
...
 		isAtomicSite: isSiteAutomatedTransfer( state, purchase.siteId ),
 		isImport: !! getSiteImportEngine( state, purchase.siteId ),
-		isJetpack: isJetpackPlan( purchase ) || isJetpackProduct( purchase ),
 		downgradePlanPrice: getDowngradePlanRawPrice( state, purchase ),
 		supportVariation: getSupportVariation( state ),
 		site: getSite( state, purchase.siteId ),
 		willAtomicSiteRevert: willAtomicSiteRevertAfterPurchaseDeactivation( state, purchase.id ),
 		atomicTransfer: getAtomicTransfer( state, purchase.siteId ),
+		canInstallPlugins: siteHasFeature( state, purchase.siteId, WPCOM_FEATURES_INSTALL_PLUGINS ),
+		canInstallPremiumPlugins: siteHasFeature(
```
Comment (obenland) [inline client/components/marketing-survey/cancel-purchase-form/index.jsx]: Maybe this could be `canInstallPurchasedPlugins`?

Comment (obenland) [reply client/components/marketing-survey/cancel-purchase-form/index.jsx]: Not sure if it's worth separating `can*` nomenclature for user capabilities from `has*` nomenclature for features? I tried to stick with `has*` in the past to avoid confusion.
`canUseSFTP` vs `hasSFTPFeature`.

Comment (mmtr) [reply client/components/marketing-survey/cancel-purchase-form/index.jsx]: Good point. Renamed them in https://github.com/Automattic/wp-calypso/pull/65191/commits/76d4bae01f5326f1ab805d5cfebb9021c91db807, although I finally removed most of them in https://github.com/Automattic/wp-calypso/pull/65191/commits/6826e6b77f26d0f75e6caa87743e64b3eb9e0737 after realizing that current copy of the "Proceed with caution" step is pretty much also valid when cancelling a marketplace plugin.

**Comment by mmtr** [comment]
Thanks for the review, @obenland!

> The "< Back" link in "Proceed with caution" doesn't take me back to the feedback step but only to the purchases screen.

Yeah, that's a known and separate issue unrelated to this PR: https://github.com/Automattic/wp-calypso/issues/56990

> When I try to cancel my plan, the selected dropdown options are invisible.

Good catch! Fixed in https://github.com/Automattic/wp-calypso/pull/65191/commits/a22a77145e46bc7f03a62a767d1c07684f9c8630.

> When I go through the steps it does not show me the "Proceed with caution" section even though the site will be reverted.

It should've been solved in https://github.com/Automattic/wp-calypso/pull/65191/commits/6826e6b77f26d0f75e6caa87743e64b3eb9e0737

**Comment by mreishus** [comment]
I understand the changes to `willAtomicSiteRevertAfterPurchaseDeactivation()`, but there's also a lot going on in this PR that I don't understand: The changes to things like `shouldUseBlankCanvasLayout()`, `INITIAL_STEP`, `FINAL_STEP`, `previousStep`, `radioTextOption`, `renderCancellationEffect + renderDomainMappingDialogText + renderPlanDialogText -> defaultContent`, etc.

**Comment by mreishus** [comment]
In my testing, when removing a domain registration, the chat option no longer appears:

**Comment by obenland** [comment]
> In my testing, when removing a domain registration, the chat option no longer appears:

That might be an issue where live chat is not marked as available on staging vs production. I had the same issue when trying to test feature check changes for it a couple of months ago.

**Comment by mreishus** [comment]
Ah, it's a dev environment thing. The trunk branch is also not showing it in dev.

**Review by obenland — APPROVED** [review]
This tests well for me now.

Like @mreishus said, it's tough to review the code changes even on a per-commit basis, but I've not found any experience regressions.

**Comment by mmtr** [comment]
Thanks everyone, I appreciate your reviews. And yeah, I apologize for not having split this into smaller PRs.

> I don't understand: The changes to things like `shouldUseBlankCanvasLayout()`, `INITIAL_STEP`, `FINAL_STEP`, `previousStep`, `radioTextOption`, `renderCancellationEffect + renderDomainMappingDialogText + renderPlanDialogText -> defaultContent`, etc.

`shouldUseBlankCanvasLayout` was used as a way to limit the new pre-cancellation form to plans only, while leaving the old form for the rest of purchases. This PR essentially removes that limitation (except for domains, since they use a different form/component) which is why `shouldUseBlankCanvasLayout` has been removed.

That allowed to remove a bunch of code that won't be longer used since it was part of the old form only. That includes `INITIAL_STEP`, `FINAL_STEP`, `previousStep`, `radioTextOption`, `defaultContent`.

And the removal of the `defaultContent` property also triggered the removal of `renderCancellationEffect`, `renderDomainMappingDialogText`, `renderPlanDialogText`.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7421297

Thank you @mmtr for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7421297).
