### PR TITLE
Reader: Fix "List Not Found" Error

### LINKED ISSUE #48702: Reader Lists: list stream doesn't finish loading when a list is missing
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/read/list/not/there

#### What I expected

The list doesn't exist, so I should be shown an message telling me that.

#### What happened instead

The list stream stayed in loading state.

#### Screenshot / Video

Screen Shot 2021-01-07 at 15 19 03

API response:

Screen Shot 2021-01-07 at 15 19 00

#### Context / Source

Discovered while trying to test an event for https://github.com/Automattic/wp-calypso/pull/48244.

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

This is only my second time looking at Lists, so forgive me if I'm completely missing something, but I've been exploring this in depth and I can't understand why `missingLists` is needed. It's currently broken, but it seems the intention was to add missing lists to an array. Given that we're already aware of the owner and slug, it feels like it makes more sense to replace all this with a more simple one-liner: `! state.reader?.lists?.isRequestingLists && ! getListByOwnerAndSlug( state, owner, slug )`.

But I realise this does delete a lot of code, and although I'm pretty confident there's no downside to this, please let me know if I'm missing something obvious!

#### Testing instructions

Visit something like `/read/list/not/there` and verify that the appropriate error appears. A real list shouldn't prompt this error.

Screenshot 2021-05-28 at 16 53 54

cc @bluefuton 

Fixes #48702

### CODE REVIEW

**Comment by bluefuton** [comment]
Just for background: I wrote the original missingLists implementation a long time ago (2016) in https://github.com/Automattic/wp-calypso/pull/4756. I can't see why it'd still be required, so yay for deleting code!

File: client/reader/list-stream/missing.jsx [hunk 1]
```diff
@@ -40,6 +41,7 @@ class ListMissing extends React.Component {
 
 		return (
 			<div>
+				<DocumentHead title={ this.props.translate( 'List not found' ) } />
 				<QueryReaderList owner={ this.props.owner } slug={ this.props.slug } />
```
Comment (bluefuton) [inline client/reader/list-stream/missing.jsx]: Do we still need to query for the list if we're already rendering `missing.jsx`?

File: client/reader/list-stream/missing.jsx [hunk 2]
```diff
@@ -40,6 +41,7 @@ class ListMissing extends React.Component {
 
 		return (
 			<div>
```
Comment (bluefuton) [inline client/reader/list-stream/missing.jsx]: I think this should probably be a `ReaderMain` so we get the right positioning of the 'missing list' page. I also notice we have a grey background rather than the usual white one as shown in this missing site page:

Screen Shot 2021-06-01 at 12 29 11

Comment (Aurorum) [reply client/reader/list-stream/missing.jsx]: Fixed! I made a couple of changes to `ReaderListManage` in order to ensure there's not two duplicate components of `ReaderMain` on the same page.

File: client/reader/list-stream/missing.jsx (hunk 1 above)
Comment (Aurorum) [reply client/reader/list-stream/missing.jsx]: Nope, fixed! :)

**Review by bluefuton — APPROVED** [review]
Tests out well for me ✅

Thanks for fixing this @Aurorum!
