### PR TITLE
Domain management: Fix email management path when the feature flag is ON

### LINKED ISSUE #97623: Bug: Adding new "Forward Email" address does not redirect users to the email list page
The users should be taken to the emails list page after adding a new address in the forward email form. Instead, the page breaks-

https://github.com/user-attachments/assets/4279ed72-5f3e-48cd-bb94-d82680bd554f

### PR DESCRIPTION
**Pull request by bogiii**
Closes https://github.com/Automattic/wp-calypso/issues/97623

## Proposed Changes

* Fixes redirection issue

## Why are these changes being made?

* Domain management revamp

## Testing Instructions

* Open `/domains/manage?flags=calypso/all-domain-management`
* Select domain
* Add forward email
* Check if it redirects on email list

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/my-sites/email/paths.ts [hunk 1]
```diff
@@ -150,7 +150,9 @@ export const getEmailManagementPath: EmailPathUtilityFunction = (
 	urlParameters
 ) => {
 	if ( isUnderDomainManagementAll( relativeTo ) ) {
-		return getPath( siteName, domainName, null, relativeTo, urlParameters );
+		return `${ domainsManagementPrefix }/${ siteName }/${ domainName }${ buildQueryString(
+			urlParameters
+		) }`;
 	}
```
Comment (bogiii) [inline client/my-sites/email/paths.ts:156]: The similar approach as we did here:
https://github.com/Automattic/wp-calypso/blob/1f1cfcbeea6635788a9b1abcf755ca0555cb7c11/client/my-sites/email/paths.ts#L79-L83

**Review by Imran92 — APPROVED** [review]
LGTM 👍
