### PR TITLE
Onboarding: Add RTL support to domain picker

### LINKED ISSUE #47885: Onboarding: domain picker shows domain components in the wrong order in RTL locale
#### Steps to reproduce

1. Starting at URL: `/new/he`
2. Advance to the domain picker
3. Search for anything

#### What I expected
- The domain search should be left aligned (this is how we display domains in input boxes, see `/me/account` and `/start/domains`)
- The search results should show the domain components in the correct order

#### What happened instead
- The domain search is right aligned
- The domain results are displayed broken e.g. if I search for `mytestdomain` then the result will be `wordpress.com.mytestdomain`

#### Screenshot / Video
image

#### Context / Source
pbAok1-1II-p2#comment-3455

### PR DESCRIPTION
**Pull request by p-jackson**
#### Changes proposed in this Pull Request

The sub-parts of a domain are always shown in a LTR fashion, even in a RTL language. These changes fixes the domain picker so that domains are always shown the correct way even when we do special things like split domain parts into different DOM elements.

* The domain search box is always displayed LTR
* The domains in the search results are displayed correctly (i.e. the tld part is shown to the right of the subdomain part)

**Before**
image

**After**
image

**The old domain picker for reference**
image

#### Testing instructions

* Start onboarding at `/new/he` and go to the domain picker
* Test it out, resize the window etc. etc.
* Search for a `.dev` domain and verify that the tooltip margin is correct
* ~~Make sure the domain picker in the launch flow works too~~ actually we should do ETK stuff in another PR, it doesn't look like ETK's css is being run through auto-rtl processing yet, so we should get that going first.

Fixes #47885

### CODE REVIEW

**Comment by ramonjd** [comment]
Tested in Chrome, IE, Firefox  LGTM

Screen Shot 2020-12-01 at 3 04 06 pm
Screen Shot 2020-12-01 at 3 05 34 pm

File: packages/domain-picker/src/domain-picker/suggestion-item.tsx [hunk 1]
```diff
@@ -137,13 +137,13 @@ const DomainPickerSuggestionItem: FunctionComponent< Props > = ( {
 				) ) }
 			<div className="domain-picker__suggestion-item-name">
 				<div className="domain-picker__suggestion-item-name-inner">
-					<span className="domain-picker__domain-name">{ domainName }</span>
 					<span
-						className={ classnames( 'domain-picker__domain-tld', {
+						className={ classnames( 'domain-picker__whole-domain', {
```
Comment (ramonjd) [inline packages/domain-picker/src/domain-picker/suggestion-item.tsx]: Nitpick (not a blocker)

Would `domain-picker__domain-name-wrapper` also be a suitable descriptor?

Whole domain, at least to me, seems ambiguous. Whole compared to part?

**Review by ramonjd — APPROVED** [review]
Have a question about CSS class name, but otherwise LGTMoi!

File: packages/domain-picker/src/domain-picker/suggestion-item.tsx (hunk 1 above)
Comment (p-jackson) [reply packages/domain-picker/src/domain-picker/suggestion-item.tsx]: Yeah "whole" compared to "part" is what I was thinking, but fair enough, it's a clumsy name. I didn't like thinking of it as a "wrapper" because it's a `span` and I thought of it more like this _is_ the domain, not an element around the domain (plus it felt like there's already bazillions of wrapper elements in this area already).

But that's probably over thinking it. Wrapper is what we call this sort of thing.
