### PR TITLE
Add an is_gutenberg-opt-out-enabled selector to fix missing Switch to Classic button

### LINKED ISSUE #36490: Gutenberg: Missing Switch to Classic in Help Menu
When visiting /block-editor, click on the blue "?" help icon. We should see a switch to classic button. I will give folks kudos if we add an E2E to also catch this on the next upgrade :D 

Expected:
screen-shot-2019-07-08-at-11 34 58-am

Actual:
Screen Shot 2019-10-02 at 5 45 13 PM

### PR DESCRIPTION
**Pull request by glendaviesnz**
#### Changes proposed in this Pull Request

Currently the 'Switch to Classic' button is missing from the help menu. This is because there is a check in the `is-gutenberg-opt-in-enabled` selector which checks if the editor is currently 'classic' - https://github.com/Automattic/wp-calypso/blob/master/client/state/selectors/is-gutenberg-opt-in-enabled.js#L15 

The `showOptOut` prop in the popover uses the `is-gutenberg-opt-in-enabled` selector to determine if opt out should be enabled - https://github.com/Automattic/wp-calypso/blob/master/client/blocks/inline-help/popover.jsx#L387 - but since this will always return false while block editor is enabled, opt out never shows.

Rather than modifying the check, or adding an additional one,  in `is-gutenberg-opt-in-enabled` this PR adds an additional `is-gutenberg-opt-out-enabled` selector to avoid any confusion. 

I don't have any of the history behind the original prop and selector, so there may be a valid reason why `showOptOut` should use the  `is-gutenberg-opt-in-enabled` selector.

#### Testing instructions

Apply this patch and then visiting /block-editor, and click on the blue "?" help icon. You should see a switch to classic button. 

Before:
Screen Shot 2019-10-02 at 5 45 13 PM

After:
screen-shot-2019-07-08-at-11 34 58-am

Fixes #36490

### CODE REVIEW

**Comment by glendaviesnz** [comment]
If it is confirmed that this fixes the issue and doesn't cause any other problems I will look at adding an e2e test to cover this (don't want to miss out on @gwwar's kudos!).

File: client/blocks/inline-help/popover.jsx [hunk 1]
```diff
@@ -384,7 +385,8 @@ function mapStateToProps( state, { moment } ) {
 
 	const isAllowedToUseClassic =
 		! isSiteUsingFullSiteEditing( state, siteId ) && ! isUsingGutenbergPageTemplates;
-	const showOptOut = optInEnabled && isGutenbergEditor && isAllowedToUseClassic;
+	const showOptOut =
+		isGutenbergOptOutEnabled( state, siteId ) && isGutenbergEditor && isAllowedToUseClassic;
```
Comment (gwwar) [inline client/blocks/inline-help/popover.jsx]: Minor, non-blocking: If we only have controls displayed in the block-editor we can maybe also move over the isGutenbergEditor and isAllowedToUseClassic logic into the selector as well.

File: client/state/selectors/is-gutenberg-opt-out-enabled.js [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+/**
+ * Internal dependencies
+ */
+import getSelectedEditor from 'state/selectors/get-selected-editor';
+import isClassicEditorForced from 'state/selectors/is-classic-editor-forced';
+
+export const isGutenbergOptOutEnabled = ( state, siteId ) => {
+	return (
+		get( state, [ 'gutenbergOptIn', siteId ], true ) &&
+		getSelectedEditor( state, siteId ) === 'gutenberg-iframe' &&
```
Comment (noahtallen) [inline client/state/selectors/is-gutenberg-opt-out-enabled.js]: Any reason we want to use gutenberg-iframe here as opposed to `!== 'classic'` (i.e. so that we cover the different gutenberg cases?)

File: client/blocks/inline-help/popover.jsx (hunk 1 above)
Comment (noahtallen) [reply client/blocks/inline-help/popover.jsx]: This is handled in https://github.com/Automattic/wp-calypso/pull/36464/files.

(This moves these checks to the server.)

File: client/state/selectors/is-gutenberg-opt-out-enabled.js (hunk 2 above)
Comment (glendaviesnz) [reply client/state/selectors/is-gutenberg-opt-out-enabled.js]: good point  - have fixed this.
