### PR TITLE
[FSE] Remove alignment option for post content block.

### LINKED ISSUE #34430: FSE: Child blocks within post content block can't be moved at default parent block width
#### Steps to reproduce
1. Check out branch and follow instructions in https://github.com/Automattic/wp-calypso/tree/master/apps/full-site-editing#build-system. Install the FSE plugin, and activate it on local gutenberg dev
2. Edit a page and add some child blocks to the post content block
3. Try and move one of the child blocks within the post content block. The move options are hidden under the wpadmin left menu 
4. Select `Wide Width` on the post content block and move handles should now be visible on child blocks.

Default content block width - no block move handles visible:
Screen Shot 2019-07-03 at 5 10 38 PM

Wide width post content block - move handles now visible:
Screen Shot 2019-07-03 at 5 11 29 PM

#### What I expected

Block move handles should be visible for all post content block widths.

### LINKED ISSUE #34558: FSE: The content slot is affecting content widths
With the Modern Business theme and the FSE plugin disabled I get this for the home page template:

Screen Shot 2019-07-09 at 11 17 57 AM

If I activate the FSE plugin, I instead get this:

Screen Shot 2019-07-09 at 11 18 31 AM

Notice how the content widths are broken for the page content, the hero header is offset to the left. I suspect it is something to do with the content slot that is breaking this?

This was running locally with the latest version of the FSE plugin from master, and a copy of Modern Business pulled directly from the WordPress.com codebase.

### PR DESCRIPTION
**Pull request by noahtallen**
This, along with theme style changes, allows the post content to look like it does in the non-fse editor.

#### Changes proposed in this Pull Request
* Disables alignment options for the post content block.

#### Testing instructions
1. Activate the FSE plugin with this PR.
2. Open a page and select the post content block.
3. There should not be any options to change the alignment of the block.
4. The content should show up in the middle of the page with significant margins. Before, it would have been edge to edge.
5. _Update_: Also test that alignment options are disabled for the header and footer.

See also this theme PR which makes the styles of the post content work properly with alignment disabled: https://github.com/Automattic/themes/pull/1072

#### Followup tasks:
- [x] Disable alignment options for the header/footer
- [x] Make sure the header/footer styles are updated to work with alignment disabled

Fixes #34558
Coincidentally, this will also resolve #34430

### CODE REVIEW

**Comment by noahtallen** [comment]
I updated this PR to remove alignment support for template parts like header and footer. Same change as with the post content :)

**Comment by apeatling** [comment]
I've tested this and confirmed that the alignment options are missing. One concern I have is switching from full width to the middle of the page.

This issue isn't noticeable with modern business because the header is centered. With friendly business however you can see that with the header block margins the width is constrained and doesn't match the front end:

In editor:

Screen Shot 2019-07-17 at 2 10 10 PM

Front End:

Screen Shot 2019-07-17 at 2 10 18 PM

I think the template part blocks need to be full width in the editor, with the containing blocks determining the width. Does that make sense, or am I missing something?

**Comment by noahtallen** [comment]
Good thought! So the goal with this is to specifically make inner blocks of the template part blocks (like post content, header, and Footer) behave and look as they would inside the normal post editor. This is important for the post content block to make it look like the front end.

I (possibly incorrectly) assumed that we wanted a similar approach with the header and footer. If we also do a theme update for this theme like I have for modern business, any blocks that are full width aligned should behave correclly - for example of the header column block is full width aligned it should stretch edge to edge.

An alternative would be to do some CSS to make the header and footer full width. The problem then is that any full/wide/otherwise weird width blocks won't display correctly in the editor, since the themes style does percentage calculation based on the container being a particular percentage based width.

I'll do a quick style update for the friendly business theme and see if the change will also work for that layout!

**Comment by noahtallen** [comment]
> I'll do a quick style update for the friendly business theme and see if the change will also work for that layout!
It turns out that they don't quite work. The issue is partially that I expected the blocks inside that header placeholder to be full on blocks. So my expectation was that the column block would have the wp-block classname, and that it would have data-align="full" set inside the page editor. It does in the template part editor, but it apparently doesn't get pulled into the page editor where it shows the header at the top.

**Comment by vindl** [comment]
> I think the template part blocks need to be full width in the editor, with the containing blocks determining the width. Does that make sense, or am I missing something?

I also think this would be an ideal solution. 👍 On top of handling the themes that take up the whole width of the page for the header, I think it should be a nice visual cue that differentiates template parts from the rest of the nested post content blocks.

**Comment by noahtallen** [comment]
> On top of handling the themes that take up the whole width of the page for the header, I think it should be a nice visual cue that differentiates template parts from the rest of the nested post content blocks.

True! After looking into it more, I think this is going to work out ok because of how the header/footer template parts in the page editor don't actually contain full, editable blocks.I'm currently working on some css to make this full aligned. (From what I can tell, it's not possible to just tell the block to be full aligned while also disabling the toggle button.)

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/index.js [hunk 1]
```diff
@@ -19,7 +19,7 @@ if ( 'wp_template_part' !== fullSiteEditing.editorPostType ) {
 		category: 'layout',
 		attributes: { templateId: { type: 'number' } },
 		supports: {
-			align: [ 'wide', 'full' ],
+			align: [ 'full' ],
```
Comment (mmtr) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/index.js]: I think we can remove this support and use `getEditWrapperProps` to force always a full align, while ensuring the user is not able to change the alignment. 

Since you're AFK tomorrow, I'll commit a change based on that (hope you don't mind!).

Comment (mmtr) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/index.js]: Done in 2a10fb6. This also removes the necessity of hiding the block controls with CSS, solving the issue with the top toolbar mode enabled :)

**Comment by noahtallen** [comment]
Thanks for making that change! I'll dig into that on Friday. I bet that'll be a useful tool for the future! It's also soo much cleaner than the other options!
