### PR TITLE
Framework: i18n fall back to language code

### LINKED ISSUE #92: Invalid Locale Results in Undefined Error
Originally reported in 2415025-t a user was having issues setting up a new site.  After selecting a plan, the page would hang.

Upon investigating [this call](https://github.com/Automattic/wp-calypso/blob/master/shared/lib/wpcom-undocumented/lib/undocumented.js#L1361) to `getLanguage` was returning `null`.  The user's locale was set to `en-gb` which is not in the list of locales in the calypso config.

__To Reproduce__
- Visit https://`your-site`/wp-admin/users.php?page=grofiles-user-settings
- Change your Interface Language to `en-gb`
- Now attempt to add a new site via calypso, and after selecting the free plan ( or any plan ) the undefined error will be hit

### PR DESCRIPTION
**Pull request by gwwar**
Fixes #92. Users can set locales with country codes (`en-gb`) that that are not supported in the calypso config. This is fixed in this PR by falling back to using the language code (`en`) if possible.

### Testing Instructions
- Visit https://your-site/wp-admin/users.php?page=grofiles-user-settings
- Change your Interface Language to en-gb
- Now attempt to add a new site via calypso, and after selecting the free plan ( or any plan ). In prod this throws a js error and will get stuck.

Expected: you should be able to finish setting up a new site, and you are not stuck in any redirect loops.

cc @hoverduck @rralian

### CODE REVIEW

**Comment by hoverduck** [comment]
@gwwar - I checked it out, looks good.

**Comment by rralian** [comment]
I'm trying to understand why/how it's possible to set a language that we don't support in Calypso. Why don't we support it in Calypso? Is this something that should be solved from the framework side? Did I just miss a locale when originally setting this stuff up? /cc @yoavf

**Comment by gwwar** [comment]
@rralian What's available in the config is a subset of what you can set in wp-admin. If this wasn't intentional, we should open up another issue.

**Comment by rralian** [comment]
@gwwar I'm trying to understand how/why this happened. I see from looking at the private repo that `en-gb` was never supported in Calypso. I see `es-cl` is also missing form the config, but present in the wp-admin language dropdown. I stopped looking there though. Were these locales that were added after we created this list? Is there a need we cannot support them in Calypso? Because if the issue is just that we need to add some missing lang/locales to the configs, then we wouldn't need this fallback code. It would be preferable to just apply the correct locale right away. And I think it's a related issue to determine how/why this happened to see if we can avoid it in the future. So I'm hoping @yoavf or @jenial could chime in to let us know if we should just add `en-gb` and any other missing locales to the config, and whether we need some facility in place to make sure we don't get out of sync.

**Comment by akirk** [comment]
@rralian I don't know how the list of languages in Calypso came into being, but it is likely that at some point it was just copied from the supported languages on WordPress.com (there is a list in a PHP file). Then the list of locales was extended in that file but not in Calypso.

I think this PR definitely has its merit in that a decent fallback should be provided by `getLanguage`, we might change the list of supported languages, need to fix errors; getLanguage should not be able to return `null`.

In another PR we should also sync the languages from wp-admin to Calypso one last time. After that, we should remove the wp-admin way to change the language in order to only have one cannonical place to change it (i.e. Calypso).

File: shared/lib/i18n-utils/utils.js [hunk 1]
```diff
@@ -1,16 +1,24 @@
...
 
 /**
  * Internal dependencies
  */
-var config = require( 'config' );
+import config from 'config';
 
-var i18nUtils = {
+const localeRegex = /^[A-Z]{2}$/i;
+const localeWithCountryRegex = /^[A-Z]{2}-[A-Z]{2}$/i;
```
Comment (rralian) [inline shared/lib/i18n-utils/utils.js]: Minor, but the second portion is technically not always a country. I think either `variant` is the right word?

**Comment by rralian** [comment]
> @rralian I don't know how the list of languages in Calypso came into being, but it is likely that at some point it was just copied from the supported languages on WordPress.com (there is a list in a PHP file). Then the list of locales was extended in that file but not in Calypso.

Yep, that's how it came into being.

> I think this PR definitely has its merit in that a decent fallback should be provided by getLanguage, we might change the list of supported languages, need to fix errors; getLanguage should not be able to return null.

Ok, let's :ship: this, though I had one minor comment about variable naming.

> In another PR we should also sync the languages from wp-admin to Calypso one last time. After that, we should remove the wp-admin way to change the language in order to only have one cannonical place to change it (i.e. Calypso).

I'll create an issue for this and add an i18n label. I think part of that issue is putting in place some process to ensure these don't get out of sync again.

File: shared/lib/i18n-utils/utils.js (hunk 1 above)
Comment (gwwar) [inline shared/lib/i18n-utils/utils.js]: How about region? In Java, variant is reserved for arbitrary locale variants like `en-gb-mac`

Comment (gwwar) [inline shared/lib/i18n-utils/utils.js]: Updated name from country to region in dc08c30

Comment (rralian) [inline shared/lib/i18n-utils/utils.js]: Yeah, I wasn't sure which was more appropriate. `region` sounds good to me. :+1:
