### PR TITLE
Fix theme activation homepage confusion.

### LINKED ISSUE #39110: TFT: On sites with `Your latest posts` active, theme's Homepage is created as Draft instead of being set as new static Homepage
When a template-first theme (TFT) is activated on a site that has `Your latest posts` option active in _WordPress.com > My Sites > Design > Customize > Homepage Settings_, the Homepage of the chosen theme is created as a Draft instead of being set as the new static Homepage. 

Steps required to see the Homepage with demo content from the chosen theme on user's site are:
- Manually Publish the page (from Drafts)
- Set it in _WordPress.com > My Sites > Design > Customize > Homepage Settings > A static page > Homepage_ (since `Set As Home Page` option is not available for sites with `Your latest posts` active as per p7DVsv-7F2-p2#comment-24719)

**We should either warn the users about the above (as it's confusing and they cannot possibly figure it out on their own) or make sure that when a TFT is applied, the new static homepage with theme's content is set as such in _WordPress.com > My Sites > Design > Customize > Homepage Settings > A static page > Homepage_ .**

The issue is somehow related to https://github.com/Automattic/wp-calypso/issues/39073

I noticed this situation several times during Quick Start sessions.

**Context / Source**
#painpoint #user-report #quick-start-sessions

### PR DESCRIPTION
**Pull request by yansern**
### Current Flow

When user clicks on the **Activate Theme** button, it will:

 - Show a popup telling user _"XXX will automatically change your homepage layout. Your current homepage will become a draft. Would you like to continue?"_ <sup>[Screenshot 1]</sup>

When user continues activating the theme, the following happens behind the scenes:

  - Existing homepage is moved into **Draft**.
  - A new homepage **might** <sup>[3]</sup> be created by the theme and set to **Published**.
  - This new homepage **is set immediately** as your homepage. <sup>[2]</sup>

After the theme is activated:

  - A popup is shown with the button **"Edit Homepage"** as the next step for the user. <sup>[Screesnhot 2]</sup>
  - The homepage setting remains **"A Static Page"**. <sup>[1]</sup>

### Proposal for Scenario 1

 - No change. Keep everything the way it is.

### Current Flow

When user clicks on the **Activate Theme** button, it will:

 - Show a popup telling user _"XXX will automatically change your homepage layout. Your current homepage will become a draft. Would you like to continue?"_ <sup>[Screenshot 1]</sup>

When user continues activating the theme, **what happens next is not the same as what the popup message described**, the following happens behind the scenes:

 - Since there is no existing page being set as homepage <sup>[4]</sup>, unlike in scenario 1, no existing page will be moved to **Draft**.
 - A new homepage **might** <sup>[3]</sup> be created by the theme, unlike in scenario 1, the publishing status of this page is set to **Draft**.
- This new homepage post, unlike in scenario 1, **is not set immediately** as your homepage. <sup>[2]</sup>

After the theme is activated:

- The popup is shown with the button **Customize Site** as the next step for the step (unlike in scenario 1).
- The homepage setting remains **"Your Latest Posts"**. <sup>[1]</sup>

## Proposal for Scenario 2 (Option 1)

<details>
<summary>This PR implements option 3, but expand for details about option 1</summary>

- Change accuracy of popup message to describe what is actually happening behind the scenes.
- Hint the user to switch from latest posts to homepage created by theme (and also they tell them how to do so) if that is what they desire.
</details>

## Proposal for Scenario 2 (Option 2)

<details>
<summary>This PR implements option 3, but expand for details about option 2</summary>

- Use the same homepage creation flow in scenario 1.
- If user does not have a page set to show latest posts <sup>[5]</sup>:
  - Create an empty page.
  - Set this empty page as the page to show latest posts.
  - Set this page as the page to show latest posts <sup>[5]</sup> <sup>[Screenshot 4]</sup>.
</details>

## Proposal for Scenario 3 (Option 3)

- Use the same homepage creation flow in scenario 1.
- But do not modify the `show_on_front` setting so user keeps their Show Latest Posts option.

# Challenges

1. How do you determine if a theme is going to create a homepage since some themes does it, some themes don't <sup>[3]</sup>?
2. If the theme creates a homepage, how do you retrieve the id of this newly created page?
3. How do we resolve possible slug name conflict for empty page created to display latest posts? https://github.com/Automattic/wp-calypso/issues/39110#issuecomment-584896089

# Footnote

- [1] The config `show_on_front = page|posts` determines whether **A Static Page** or **Your Latest Posts** should be used as home page settings.
- [2] The config `page_on_front = pageId` determines which page should used as the homepage. 
- [3] Some themes like **Barnsbury** and **Dalston** create a homepage, some themes like **TwentyTwenty** does not create a homepage.
- [4] Even though there is no page being set as static page, the config `page_on_front` may still contain the id of the previous set page.
- [5] The config `page_for_posts = pageId` determines which empty page should be used to display list of blog posts.

# Screenshots (for reference)

Screenshot 1 - Pre-activation popup
image

Screenshot 2 - Post-activation popup if the user sets an existing static page as homepage.
image

Screenshot 3 - Post-activation popup if the user sets to show latest post as homepage.
image

Screenshot 4 - Where an empty post can be set to show list of posts in customizer
image

Fixes #39110

### CODE REVIEW

**Comment by obenland** [comment]
Sorry for the late reply, I've been making my way through notifications and pings.

> How do you determine if a theme is going to create a homepage since some themes does it, some themes don't?

Themes with the the `auto-loading-homepage` tag will have their homepage created. All associated logic is in the `A8C\MU\Full_Site_Editing\Template_First_Themes` class.

> If the theme creates a homepage, how do you retrieve the id of this newly created page?

See `A8C\MU\Full_Site_Editing\Template_First_Themes::update_homepage_template()`.

> How do we resolve possible slug name conflict for empty page created to display latest posts?

WordPress does that automatically. But that is not the biggest challenge. If we were to auto-create a blogs page, we'd also have to find a way to make it accessible. Add it to a navigation menu. And that is where it gets murky.

Which is why I'd advocate for Option 1. It feels like the best way to improve the situation.

**Comment by jancavan** [comment]
Screen Shot 2020-07-06 at 2 23 06 PM

@yansern The second option (Use new theme homepage) is the current behavior, correct? Where it switches you to the new theme's homepage and drafts your current one?

**Comment by obenland** [comment]
Related: #41243

**Comment by jancavan** [comment]
> [3] Some themes like Barnsbury and Dalston create a homepage, some themes like TwentyTwenty does not create a homepage.

Seems like homepages are not created if the theme doesn't come with demo content. Is this correct?

I don't think we need to display the prompt in cases where the user's existing homepage remains intact, and doesn't get drafted. For example, Twenty Twenty theme.

I think this PR works well to address the main issue, but I'd like to suggest some copy changes:

Screen Shot 2020-07-07 at 9 16 02 AM

We'd also default the user to the first radio option.

> Scenario 1: For sites showing a static page as homepage

Would also like to suggest some minor visual changes just so it doesn't look like the entire prompt consists of a giant heading. I mainly only tweaked the copy and broke the text up:

Screen Shot 2020-07-07 at 9 13 21 AM

Please note that "Activate" should also not be capitalized here.

@yansern @Automattic/ajax

**Comment by obenland** [comment]
> Seems like homepages are not created if the theme doesn't come with demo content. Is this correct?

Homepages are only created when switching to a theme that has the `'auto-loading-homepage'` tag. For Twenty Twenty there was confusion if a custom tag like that would be overwritten in a future update, IIRC.

File: client/my-sites/themes/auto-loading-homepage-modal.jsx [hunk 1]
```diff
@@ -96,32 +108,74 @@ class AutoLoadingHomepageModal extends Component {
 				buttons={ [
 					{
 						action: 'keepCurrentTheme',
-						label: translate( 'No, keep my current theme' ),
+						label:
+							show_on_front === 'posts'
+								? translate( 'Keep my current theme' )
```
Comment (a8ci18n) [inline client/my-sites/themes/auto-loading-homepage-modal.jsx:113]: :warning: This change will be queued for retranslation. We'll display the English text until then.

File: client/my-sites/themes/auto-loading-homepage-modal.jsx [hunk 2]
```diff
@@ -96,32 +108,74 @@ class AutoLoadingHomepageModal extends Component {
...
 						onClick: this.closeModalHandler( false ),
 					},
 					{
 						action: 'activeTheme',
-						label: translate( 'Yes, activate %(themeName)s', {
-							args: { themeName },
-						} ),
+						label:
+							show_on_front === 'posts'
+								? translate( 'Activate %(themeName)s', { args: { themeName } } )
```
Comment (a8ci18n) [inline client/my-sites/themes/auto-loading-homepage-modal.jsx:122]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **20** times:
`translate( 'Yes, Activate %(themeName)s' )` *ES Score: 8*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/fix/switch-theme-homepage-flow)

File: client/my-sites/themes/auto-loading-homepage-modal.jsx [hunk 3]
```diff
@@ -96,32 +108,72 @@ class AutoLoadingHomepageModal extends Component {
 				buttons={ [
 					{
 						action: 'keepCurrentTheme',
-						label: translate( 'No, keep my current theme' ),
+						label: postsOnFrontPage
+							? translate( 'Keep my current theme' )
```
Comment (a8ci18n) [inline client/my-sites/themes/auto-loading-homepage-modal.jsx:112]: :warning: This change will be queued for retranslation. We'll display the English text until then.

File: client/my-sites/themes/auto-loading-homepage-modal.jsx [hunk 4]
```diff
@@ -96,32 +108,72 @@ class AutoLoadingHomepageModal extends Component {
...
 						isPrimary: false,
 						onClick: this.closeModalHandler( false ),
 					},
 					{
 						action: 'activeTheme',
-						label: translate( 'Yes, activate %(themeName)s', {
-							args: { themeName },
-						} ),
+						label: postsOnFrontPage
+							? translate( 'Activate %(themeName)s', { args: { themeName } } )
```
Comment (a8ci18n) [inline client/my-sites/themes/auto-loading-homepage-modal.jsx:120]: :warning: This change will be queued for retranslation. We'll display the English text until then.
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **20** times:
`translate( 'Yes, Activate %(themeName)s' )` *ES Score: 8*

**Comment by p-jackson** [comment]
I've created D49715-code which implements a flag to prevent full-site-editing from switching the front page.

**Comment by p-jackson** [comment]
I've read the comments and implemented something that I think is in line with what's been discussed. If it's not then at least an implementation can give us something concrete to work from :)

I've implemented what I'm calling option 3 for scenario 2:
- If a site currently shows latest posts on front, then ask the user what they want to happen before activating
  - If they want to use the homepage and content from the theme they selected then they get the same thing they'd currently get in production; a new homepage is published and it is set as the front page
  - If instead they want to continue showing their latest posts on front then we will do almost everything that currently happens on production (i.e. import the theme's homepage as a page, set any old one as a draft et.) **except** we don't change the `show_on_front` option, that just stays as showing latest posts

Scenario 1 (the user is already showing a page on front) has no changes (except the dialog tweaks).

I've also made some styling changes to incorporate ideas from above.

Here's some a video to see it in action: https://d.pr/v/g7ASpX. You can also try it by using Calypso branch and applying D49715-code to your sandbox.

And here's screenshots of the dialog changes:
Screenshot 2020-09-18 at 6 26 40 PM
(I've kept the buttons right-aligned instead of centring them because I think overall dialog consistency is more important than this one case)

Screenshot 2020-09-18 at 6 27 22 PM
"keep using my latest posts" is the default. Also not that the dialog say that activating _can_ the homepage content. Accurate, but a little awkward.

A question about translations, is it safe to assume we can use the theme name in a sentence with an apostrophe like this? Are there some languages that would need to change the spelling of the theme to do the equivalent of a possessive apostrophe?

What do you think? @jancavan @ianstewart @obenland @simison since you've weighed in at various points.

**Comment by ianstewart** [comment]
> If a site currently shows latest posts on front …

I don't think I would tie this IF to latest posts specifically since someone may have any number of content or settings customizations to their homepage that they may like to keep when switching themes.

Here's how I'd modify the two resulting cases you shared …

- If they want to use the homepage and content from the theme they selected then they get the same thing they'd currently get in production; a new homepage is published and it is set as the front page, the old one is drafted.
- If instead they want to continue using their existing home page we activate the theme without making any changes to their site or other settings.

I think gist of the message we'd want to share would be something like this (whether or not we use this copy) …

**How would you like to use Barnsbury on your site?**

[x] Use Barnsbury without changing my homepage content.
[ ] Use Barnsbury's homepage content and make my existing homepage a draft.

- Keep my current theme
- Activate Barnsbury

**Comment by iamtakashi** [comment]
> I think gist of the message [...]
> Use Barnsbury without changing my homepage content.

+1 to that. I think the option should their homepage untouched, but change the theme.

**Comment by p-jackson** [comment]
> someone may have any number of content or settings customizations to their homepage that they may like to keep when switching themes.

Looks like we have agreement. I've updated the implementation so it will:
- always show the options to the user (as long as the theme has the `auto-loading-homepage` feature)
- if the user sticks with their current homepage we skip all of logic we added for template-first theme

Dialog always looks like this now:
Screenshot 2020-09-21 at 9 12 54 PM

I think this is ready for review. Remember to apply D49715-code!

File: client/my-sites/themes/auto-loading-homepage-modal.jsx [hunk 5]
```diff
@@ -49,11 +51,41 @@ class AutoLoadingHomepageModal extends Component {
...
+	}
+
+	static getDerivedStateFromProps( nextProps, prevState ) {
+		if ( nextProps.isVisible && ! prevState.wasVisible ) {
+			return { homepageAction: 'keep_current_homepage', wasVisible: true };
+		} else if ( ! nextProps.isVisible && prevState.wasVisible ) {
+			return { wasVisible: false };
+		}
+		return null;
+	}
```
Comment (p-jackson) [inline client/my-sites/themes/auto-loading-homepage-modal.jsx:71]: Using state derived from props is a bit messy, but I want to reset the state each time the dialog opens so that `keep_current_homepage` is always selected by default.

_Ideally_ I'd wrap the radio buttons in a `<form>` and grab the current selection when the user submits the form. That way we wouldn't need to maintain any state in the component. It'd be better for a11y too.
Unfortunately the interface for `<Dialog>` doesn't have a way to let me place the dialog buttons inside the `<form>` and make one of them `type="submit"`.

**Comment by ianstewart** [comment]
Small review without testing yet:

Can the radio options have periods at the end of them? Like so …

> Use Barnsbury without changing my homepage content.
> Use Barnsbury's homepage content and make my existing homepage a draft.

File: client/my-sites/themes/auto-loading-homepage-modal.jsx (hunk 5 above)
Comment (ciampo) [reply client/my-sites/themes/auto-loading-homepage-modal.jsx:71]: Agreed, it's a bit hacky but probably the best way to reset the state given the limitations from `<Dialog />`.

Maybe it would be worth to add a comment inside the `getDerivedStateFromProps` function, explaining that the code in there makes sure that `keep_current_homepage` is always the default selection when the dialog gets opened?

**Comment by ciampo** [comment]
Tested these scenarios successfully:
- with the latest posts showing in the homepage, activated a new theme, without changing my homepage content
- with the latest posts showing in the homepage, activated a new theme, using the new theme's homepage's content
- with a static homepage, activated a new theme, without changing my homepage content
- with a static homepage, activated a new theme, using the new theme's homepage's content

Just one quick nitpick, (not related to this PR specifically), when opening the `/themes/:siteId` page, there is a PropTypes error showing in the console:

> Failed prop type: The prop `installingThemeId` is marked as required in `AutoLoadingHomepageModal`, but its value is `undefined`

**Comment by p-jackson** [comment]
Thanks for testing @ciampo. I've created another PR to fix the warning #45859

**Review by ciampo — APPROVED** [review]
Thank you @p-jackson! Changes LGTM 🙌

**Comment by p-jackson** [comment]
Ready to merge, but given that the changes in this PR and #43933 taken together add up to a relatively big change, I'm going to post something to signal the change to HEs before deploying.
p1600689191014500-slack-C0160HSMDQV

File: client/my-sites/themes/auto-loading-homepage-modal.jsx [hunk 6]
```diff
@@ -96,32 +131,48 @@ class AutoLoadingHomepageModal extends Component {
 				buttons={ [
 					{
 						action: 'keepCurrentTheme',
-						label: translate( 'No, keep my current theme' ),
+						label: translate( 'Keep my current theme' ),
```
Comment (a8ci18n) [inline client/my-sites/themes/auto-loading-homepage-modal.jsx:134]: :warning: This change will be queued for retranslation. We'll display the English text until then.

File: client/my-sites/themes/auto-loading-homepage-modal.jsx [hunk 7]
```diff
@@ -96,32 +131,48 @@ class AutoLoadingHomepageModal extends Component {
...
 						isPrimary: false,
 						onClick: this.closeModalHandler( false ),
 					},
 					{
 						action: 'activeTheme',
-						label: translate( 'Yes, activate %(themeName)s', {
-							args: { themeName },
-						} ),
+						label: translate( 'Activate %(themeName)s', { args: { themeName } } ),
```
Comment (a8ci18n) [inline client/my-sites/themes/auto-loading-homepage-modal.jsx:140]: :warning: This change will be queued for retranslation. We'll display the English text until then.
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **20** times:
`translate( 'Yes, Activate %(themeName)s' )` *ES Score: 8*

**Comment by simison** [comment]
> Ready to merge,

Good to wait for those translations come back 100% first, anyway.

**Comment by simison** [comment]
Let's get this merged on Monday, looks like translations are now all ready.

**Comment by p-jackson** [comment]
PR was pretty old so rebased to re-run tests and check again.

**Comment by autumnfjeld** [comment]
The description of this PR is the most amazing piece of documentation.  Truly a masterpiece! 🥇
