### PR TITLE
Gutenberg: Fix Publicize broken connection handling

### LINKED ISSUE #29211: Gutenberg Publicize Social Sharing: Broken connection status not displayed
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/block-editor/post/ with an account with a broken social media connection
2. Click Jetpack icon and expand Share This Post

#### What I expected

As per Calypso Editor - the broken status of the connection should display:

calypso broken

#### What happened instead

Broken connections are displayed the same as other connections

screen shot 2018-12-07 at 2 09 18 pm

#### Browser / OS version

Chrome 70 on macOS

#### Screenshot / Video

See above

#### Context / Source

This issue also shows #28953

### PR DESCRIPTION
**Pull request by tyxla**
It seems that our current way of managing and handling broken Publicize connections for Gutenberg is broken. This PR fixes it, and does some improvements.

#### Changes proposed in this Pull Request

* Use the right field names and data structure, as it comes from the API.
* Remove an unnecessary layer of arrow functions that was concealing information.
* Use `<Notice />` component for the broken connections notice.
* Use a `<Button />` component for the broken connections refresh links.
* Properly clear the interval after restarting connection test.
* Janitorial enhancements and cleanups:
  * Remove unnecessary `constructor()` method.
  * Move `componentDidMount` up top.
  * Remove unnecessary `key` prop.
  * Sort imports
  * Simplify `connectionTestComplete()`.

#### Testing instructions

* Get setup with a site by either:
  * Using calypso.live - https://calypso.live/?branch=fix/gutenberg-publicize-connection-errors-handling and select a simple WP.com site
  * Using JN - [this link](https://jurassic.ninja/create?jetpack-beta&shortlived&gutenberg&gutenpack&calypsobranch=fix/gutenberg-publicize-connection-errors-handling) to create a site, then connect the site and activate the recommended features.
* Start writing a post.
* Expand the Jetpack sidebar, or click the Publish button.
* Connect a service to Publicize.
* Go to the social network and delete the auth token / app.
* Refresh the post.
* Verify you can see a notice at the bottom of the Publicize UI
* Click the refresh connection button.
* Verify it takes you to a new window where you can reconnect the service.
* Close the window.
* Verify the connections are refreshing, and if you successfully reconnected the service, notice is removed.

Fixes #29211

### CODE REVIEW

**Comment by tyxla** [comment]
@MichaelArestad @mapk - it seems this notice was positioned at the bottom back in the trial's work, but I'd like to confirm that this is intentional. Is there perhaps a better location where you'd place it?

**Comment by alisterscott** [comment]
Thanks for the quick fix @tyxla 

> Start a new JN site with this branch - gutenpack-jn.

Can you explain how to do that?


I tried:

https://jurassic.ninja/create?jetpack-beta&shortlived&gutenberg&gutenpack&calypsoBranch=fix/gutenberg-publicize-connection-errors-handling

but it still didn't work

**Comment by tyxla** [comment]
Hey @alisterscott - `gutenpack-jn` requires the tampermonkey script for jetpack beta branches. And the `calypsoBranch` parameter should be lowercase - `calypsobranch`.

An alternative seems to be calypso.live - https://calypso.live/?branch=fix/gutenberg-publicize-connection-errors-handling - I've updated the PR description test instructions.

**Comment by alisterscott** [comment]
Tested via calypso.live and displays the message as expected:

Before

before

After Jetpack Menu

after

After on Publish

after full

File: client/gutenberg/extensions/publicize/connection-verify.jsx [hunk 1]
```diff
@@ -63,8 +66,8 @@ class PublicizeConnectionVerify extends Component {
 	 */
 	connectionTestStart = () => {
 		apiFetch( { path: '/wpcom/v2/publicize/connection-test-results' } )
-			.then( () => this.connectionTestComplete )
-			.catch( () => this.connectionTestRequestFailed );
```
Comment (sirreal) [inline client/gutenberg/extensions/publicize/connection-verify.jsx]: These were the main broken bits, is that right? The methods were not being invoked?

Comment (tyxla) [reply client/gutenberg/extensions/publicize/connection-verify.jsx]: That, and also the wrong fields were used when rendering 😅 For example `refreshText` instead of the proper `refresh_text`.

**Comment by tyxla** [comment]
Thank you folks!

I'll merge this as-is, as it fixes a broken flow, but I could still use design feedback - mainly to know whether this looks well and is in the right location.

**Comment by mapk** [comment]
Just taking a look at the error positioning. I've moved it to the top of the module where I think it makes more sense. It works better here especially since the messaging says "refresh the _following_ connection(s)"

error-position

**Comment by tyxla** [comment]
> I've moved it to the top of the module where I think it makes more sense.

Thanks @mapk! Addressed in #29349.
