### PR TITLE
Stats: Fix "Average Per Day" Calculation for Current Month

### LINKED ISSUE #51673: Stats: "Average per day" in Insights for current month is inaccurate
### Steps to reproduce the behavior

1. Go to https://wordpress.com/stats/insights/DOMAIN.COM
2. Click on "Average per day" tab in "All-time views"
3. Check the number for current month

#### What actually happened

It shows a number that makes no sense. For example, for the user I chatted with today, they have gotten 3,760 views until the end of April 4th. And given that today is April 5th, the average daily number should be 940 but it showed 129 instead, which is totally inaccurate. 

I've checked several sites(both simple and atomic) and could reproduce the issue on all sites I've tested so far.

Jetpack Stats page we can access via https://DOMAIN.com/wp-admin/admin.php?page=stats&view=table&disable-nav-unification is showing the accurate number for "Average per Day". So this could be another reason why users prefer Jetpack Stats page(Related to #51381).

### Context

Originally reported in 28821709-hc.

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

The "Average Per Day" section of Stats is calculated by "total views in the month / total days in the month". This PR would change that formula only for the current month so that it becomes "total views so far in the month / total days **so far** in the month".

#### Testing instructions

This is a bit painful, but manually add up all the views obtained this month (April 2021). 

**Before:**
If you divide that number by 30, you should find the existing number.

Screenshot 2021-04-05 at 14 22 13

**After:**
If you divide that number by how many days have passed in the month (at the time of writing, it's the 5th of April so five), you should find the new number. 

Screenshot 2021-04-05 at 14 21 55
 
Also, verify none of the other numbers are affected.

Fixes #51673
cc @sixhours, @tyxla

### CODE REVIEW

File: client/state/stats/lists/selectors.js [hunk 1]
```diff
@@ -204,6 +204,14 @@ export function getSiteStatsViewSummary( state, siteId ) {
 		viewSummary[ years ][ months ].average = round( average, 0 );
 	} );
 
+	// With the current month, calculate the average based on the days passed so far in the month
+	const thisMonth = viewSummary[ moment().year() ][ moment().month() ];
```
Comment (tyxla) [inline client/state/stats/lists/selectors.js]: Do you think we can reduce the `moment()` calls to one in this case? And get the `month` and `year` from that single call, instead of calling `moment()` twice?

File: client/state/stats/lists/selectors.js [hunk 2]
```diff
@@ -204,6 +204,14 @@ export function getSiteStatsViewSummary( state, siteId ) {
...
+	if ( thisMonth ) {
+		const daysSinceStartOfMonth =
+			moment( new Date() ).diff( moment().startOf( 'month' ), 'days' ) + 1;
```
Comment (tyxla) [inline client/state/stats/lists/selectors.js]: In this first `moment()` call, can't we use the date we just used above for retrieving the current month?

File: client/state/stats/lists/selectors.js [hunk 3]
```diff
@@ -204,6 +204,14 @@ export function getSiteStatsViewSummary( state, siteId ) {
...
+		thisMonth.average = round( thisMonth.total / daysSinceStartOfMonth, 0 );
```
Comment (tyxla) [inline client/state/stats/lists/selectors.js]: Do you think we could use `Math.round()` instead of `round()`? We've been trying to avoid introducing new usages of Lodash recently because we're slowly refactoring away from it.

**Review by tyxla — COMMENTED** [review]
Hey @Aurorum, thanks for working on this one, it makes a lot of sense!

Have you considered using as little `moment()` calls as possible?

Also, it would be great if we could have a unit test for this particular scenario of the selector.

**Comment by Aurorum** [comment]
Hi @tyxla, thanks, I updated the `moment()` calls. Unfortunately, I'm not sure how to implement and fix those existing unit tests - I'll continue trying to do so, but I'm not entirely sure how to make them work when the data will be constantly changing.

File: client/state/stats/lists/selectors.js [hunk 4]
```diff
@@ -201,9 +201,20 @@ export function getSiteStatsViewSummary( state, siteId ) {
...
+		viewSummary[ years ][ months ].average = Math.round( average );
 	} );
 
+	// With the current month, calculate the average based on the days passed so far in the month
+	const momentTime = moment();
+	const thisMonth = viewSummary[ momentTime.year() ][ momentTime.month() ];
+
+	if ( thisMonth ) {
+		const daysSinceStartOfMonth =
+			moment( new Date() ).diff( momentTime.startOf( 'month' ), 'days' ) + 1;
```
Comment (tyxla) [inline client/state/stats/lists/selectors.js]: Instead of `moment( new Date() )` can't we use `momentTime`?

File: client/state/stats/lists/selectors.js [hunk 5]
```diff
@@ -201,9 +201,20 @@ export function getSiteStatsViewSummary( state, siteId ) {
 		viewSummary[ years ][ months ].data.push( item );
 		const average =
 			viewSummary[ years ][ months ].total / viewSummary[ years ][ months ].daysInMonth;
-		viewSummary[ years ][ months ].average = round( average, 0 );
+		viewSummary[ years ][ months ].average = Math.round( average );
```
Comment (tyxla) [inline client/state/stats/lists/selectors.js:205]: Thanks for refactoring this one to use `Math.round()` 👏

**Review by tyxla — COMMENTED** [review]
Thanks for the iteration here, @Aurorum, nice work 👍  I've left some more feedback. 

> Unfortunately, I'm not sure how to implement and fix those existing unit tests - I'll continue trying to do so, but I'm not entirely sure how to make them work when the data will be constantly changing.

Have you considered mocking `moment` for the tests so it would return a precise date? Something like what is being suggested in [this article](https://medium.com/front-end-weekly/mocking-moment-js-in-jest-a-simple-one-line-solution-61259ffaaa2).

Alternatively, if we always use the current date, tests could be refactored to be relative to the current date, vs. being absolute and relying on the date to be fixed to a specific moment in history.

**Comment by Aurorum** [comment]
Hi @tyxla, thank you! I've added some tests now - are those okay? It seems the reason some of them were failing earlier was because of a valid issue on a site where there was no `viewData` (ie. no views) causing it to crash, but that should be fixed now.

File: client/state/stats/lists/selectors.js (hunk 4 above)
Comment (Aurorum) [reply client/state/stats/lists/selectors.js]: Unless I'm making a super obvious mistake (oops!), this wasn't working for me and only returning `0`:

`const daysSinceStartOfMonth = momentTime.diff( momentTime.startOf( 'month' ), 'days' );`

Is there an issue with that line?

File: client/state/stats/lists/selectors.js [hunk 6]
```diff
@@ -201,9 +201,22 @@ export function getSiteStatsViewSummary( state, siteId ) {
...
 	} );
 
+	// With the current month, calculate the average based on the days passed so far in the month
+	if ( viewData.data.length ) {
+		const momentTime = moment();
```
Comment (tyxla) [inline client/state/stats/lists/selectors.js]: I've taken another look at this and I think the `moment` usage here is really unnecessary - it could be replaced with simple `Date()` usage:

* Instead of `moment()` , we can use `new Date()`.
* Instead of `momentTime.year()` we can use `new Date().getFullYear()`
* Instead of `momentTime.month()` we can use `new Date().getMonth() + 1` (because months are zero-based)
* Instead of `const daysSinceStartOfMonth = moment( new Date() ).diff( momentTime.startOf( 'month' ), 'days' ) + 1;` we can use `new Date().getDate()`.

That being said, I'd love it if we can avoid introducing `moment` in the tests, too.

Comment (Aurorum) [reply client/state/stats/lists/selectors.js]: Thank you! I've now removed the usage of `moment`, including in the tests. :)

File: client/state/stats/lists/selectors.js [hunk 7]
```diff
@@ -201,9 +201,20 @@ export function getSiteStatsViewSummary( state, siteId ) {
...
 		const average =
 			viewSummary[ years ][ months ].total / viewSummary[ years ][ months ].daysInMonth;
-		viewSummary[ years ][ months ].average = round( average, 0 );
+		viewSummary[ years ][ months ].average = Math.round( average );
 	} );
 
+	// With the current month, calculate the average based on the days passed so far in the month
+	if ( viewData.data.length ) {
+		const date = new Date();
+		const thisMonth = viewSummary[ date.getFullYear() ][ date.getMonth() ];
```
Comment (tyxla) [inline client/state/stats/lists/selectors.js]: It's possible that there won't be any stats for this year. In that case, `viewSummary[ date.getFullYear() ]` will be undefined, causing `viewSummary[ date.getFullYear() ][ date.getMonth() ]` to fail with an error like this:



We should try to access this safely, and if there are no stats at all, we don't have to do any calculations.

**Review by tyxla — CHANGES_REQUESTED** [review]

File: client/state/stats/lists/selectors.js (hunk 7 above)
Comment (Aurorum) [reply client/state/stats/lists/selectors.js]: Thank you! I've added a commit that should fix that issue.

**Comment by Aurorum** [comment]
I'm not sure if I should include it in this PR, but following some of the conversation earlier, I've also tried removing the `moment` usage in the rest of the function - is that better? There should be no visual changes caused by it.

**Review by tyxla — APPROVED** [review]
Absolutely brilliant work here, @Aurorum!  💯 

Thanks again for the wonderful contribution! 😍

**Comment by Aurorum** [comment]
Thanks @tyxla! I was just about to add a commit to remove the `moment` usage from the whole file, namely here 😅 

https://github.com/Automattic/wp-calypso/blob/fde400f81fd988bf3ee6950247c072dad53f69c8/client/state/stats/lists/selectors.js#L81-L82

Should I propose it in a separate PR and leave this one for now?

**Comment by tyxla** [comment]
> Thanks @tyxla! I was just about to add a commit to remove the `moment` usage from the whole file, namely here 😅
> 
> https://github.com/Automattic/wp-calypso/blob/fde400f81fd988bf3ee6950247c072dad53f69c8/client/state/stats/lists/selectors.js#L81-L82
> 
> Should I propose it in a separate PR and leave this one for now?

Nice! Let's ship this as-is, but feel free to open another PR for that.

Thanks again 🙌

**Comment by Aurorum** [comment]
Will do - thanks for the help on this! :)

**Comment by Aurorum** [comment]
PR in #51812 for that. :)
