### PR TITLE
Domains: Improve TXT record's validation

### LINKED ISSUE #3328: Domains: TXT record's value validation is broken
* The value is being unnecessarily sanitized (lower case, strip whitespace)
* It's possible to submit an empty value (but the backend thankfully rejects that)

### PR DESCRIPTION
**Pull request by klimeryk**
* Don't normalize TXT record's data, only name. Fixes regression introduced when we started normalizing every field of a DNS record before saving.
 * Don't allow empty value for the TXT record.

A nice side-effect of this change is that the selected record does not reset to 'A' after every submit.

Fixes #3328 

/cc @umurkontaci @aidvu for code review
@andrewspittle for testing

### CODE REVIEW

**Comment by BandonRandon** [comment]
Patch works for me
screenshot_25-02-2016-21 30 16

```
$ dig txt flagtest.me

;; ANSWER SECTION:
flagtest.me.   3600	IN	TXT	"google-site-verification=rXOxyZounnZasA8Z7oaD3c14JdjS9aKSWvsR1EbUSIQ"
```

File: client/my-sites/upgrades/domain-management/dns/dns-add-new.jsx [hunk 1]
```diff
@@ -107,14 +104,16 @@ const DnsAddNew = React.createClass( {
 	},
 
 	onChange( event ) {
+		const { name, value } = event.target;
 		this.formStateController.handleFieldChange( {
-			name: event.target.name,
-			value: event.target.value.trim().toLowerCase()
+			name,
+			value: name === 'data' && this.state.type === 'TXT' ? value : value.trim().toLowerCase(),
```
Comment (umurkontaci) [inline client/my-sites/upgrades/domain-management/dns/dns-add-new.jsx]: It might make sense to move this logic to a function or a variable something like `shouldNormalize`.

**Comment by umurkontaci** [comment]
There's one small improvement I suggested, otherwise it works as expected should be good to go

**Comment by klimeryk** [comment]
Thanks for the comment @umurkontaci - I've [included your suggestion](https://github.com/Automattic/wp-calypso/pull/3585/files#diff-825d3ad01961ba8ac2738c47f07c053cR108).

**Comment by umurkontaci** [comment]
LGTM
