### PR TITLE
E2E tests: Fix opening templates in FSE

### LINKED ISSUE #90445: E2E tests: Fix opening templates in FSE
Fixes an e2e error where templates cannot be loaded because a table view is expected rather than a grid.

This is currently breaking some nightly e2e tests for Gutenberg. This change modifies the e2e's expectations to fit the new realities.

### PR DESCRIPTION
**Pull request by olaseni**
Fixes an e2e error where templates cannot be loaded because a table view is expected rather than a grid.

This is currently breaking some nightly e2e tests for Gutenberg. This change modifies the e2e's expectations to fit the new realities.

Testing instructions
---

[Running e2e tests for Calypso](https://github.com/Automattic/wp-calypso/tree/trunk/test/e2e)

Run the editor schedule flow e2e edge tests, which was failing before this fix:

```bash
cd test/e2e
yarn jest --clearCache && yarn build  # clear build cache before each run


yarn jest specs/fse/fse__temp-smoke-test.ts 
GUTENBERG_EDGE=1 yarn jest specs/fse/fse__temp-smoke-test.ts 
GUTENBERG_EDGE=1 TEST_ON_ATOMIC=true yarn jest specs/fse/fse__temp-smoke-test.ts
```

### CODE REVIEW

File: packages/calypso-e2e/src/lib/components/full-side-editor-data-views-component.ts [hunk 1]
```diff
@@ -30,6 +30,13 @@ export class FullSiteEditorDataViewsComponent {
...
 		const editorParent = await this.editor.parent();
-		await editorParent.locator( selectors.primaryFieldByText( primaryFieldText ) ).click();
+		const primaryFieldInTable = editorParent.locator(
+			selectors.primaryFieldByText( 'table', primaryFieldText )
+		);
+		const primaryFieldInGrid = editorParent.locator(
+			selectors.primaryFieldByText( 'grid', primaryFieldText )
+		);
+
+		await Promise.race( [ primaryFieldInTable.click(), primaryFieldInGrid.click() ] );
```
Comment (nightnei) [inline packages/calypso-e2e/src/lib/components/full-side-editor-data-views-component.ts:40]: Looks a bit weird, could you please elaborate why we have two locators and finishing only one one of them is resolved?

**Review by nightnei — APPROVED** [review]

File: packages/calypso-e2e/src/lib/components/full-side-editor-data-views-component.ts (hunk 1 above)
Comment (olaseni) [reply packages/calypso-e2e/src/lib/components/full-side-editor-data-views-component.ts:40]: That's because the selectors vary between versions of GB, and platforms as well. In some instances a grid is expected. Other versions expect a table etc.
