### PR TITLE
Help Center: Redirect non eligible users to home when accessing wapuu

### LINKED ISSUE #93246: Help Center: Fallback for free users opening Wapuu
### Details

We have the possibility of having an url like `/help?help-center=wapuu`, which brings you to the page with Help Center open on Wapuu.

For free users that doesn't work well, since they are currently not able to access Wapuu. And it shows like this:

image

### Checklist

_No response_

### Related

_No response_

### PR DESCRIPTION
**Pull request by renancarvalho**
Related to #93246 
Fixes https://github.com/Automattic/wp-calypso/issues/93246

## Proposed Changes

* Non-eligible users are landing on `wapuu` and getting a blank page, this PR fixes it by sending them to `/home` since they are not eligible to access `wapuu`.

## Why are these changes being made?

* Fix users landing on the help center and getting a blank screen.

image

## Testing Instructions

* Check live link or pull and run this branch
* Add `/help?help-center=wapuu` to the URL, example: `http://calypso.localhost:3000/help?help-center=wapuu`
* Help center should open with wapuu if you're using a paid user (eligible)
* If you're using a free user, it should open the help center on home.

Regressions:

Kris noted here p1723120199029909/1723109797.283309-slack-C02T4NVL4JJ that there's an experiment running on Wapuu with free users, we need to make sure this PR is not interfering with the results of this experiment.

I have investigated, and the experiment uses a flag `&flags=wapuu` to 'choose' users that will get wapuu. To make sure this PR will not interfere with the experiment, you can add this flag too and make sure that free and paid users get Wapuu.

Example: http://calypso.localhost:3000/help?help-center=wapuu&flags=wapuu

@escapemanuele 

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: packages/odie-client/src/index.tsx [hunk 1]
```diff
@@ -12,16 +13,34 @@ export const ODIE_THUMBS_DOWN_RATING_VALUE = 0;
...
 	const messagesContainerRef = useRef< HTMLDivElement >( null );
+	const navigate = useNavigate();
 
 	useEffect( () => {
 		trackEvent( 'chatbox_view' );
 	}, [ trackEvent ] );
 
+	// Prevent not eligible users from accessing wapuu.
+	useEffect( () => {
+		if ( ! isUserElegible ) {
```
Comment (alshakero) [inline packages/odie-client/src/index.tsx]: I'm worried we may redirect a user who is still loading support status. We should probably check that it's not loading too.

Comment (AllTerrainDeveloper) [reply packages/odie-client/src/index.tsx]: The way we are injecting the isUserElegible is through the query:

```tsx
	const { data } = useSupportStatus();
	const isUserElegible = data?.eligibility.is_user_eligible ?? false;
```

So I would say that particular case is covered, but we could add anyway something like:
```tsx
	const { data, isLoading } = useSupportStatus();
	const isUserElegible = isLoading ? : false : data?.eligibility.is_user_eligible ?? false;
```

But I don't think it's necessary

File: packages/odie-client/src/index.tsx [hunk 2]
```diff
@@ -1,5 +1,6 @@
 import { Spinner } from '@wordpress/components';
 import { useEffect, useRef, useState } from 'react';
+import { useNavigate } from 'react-router-dom';
```
Comment (AllTerrainDeveloper) [inline packages/odie-client/src/index.tsx]: react-router-dom is not included in the package json. This would eventually break the package.

I would prefer injecting the navigate as it's done in the provider:
`help-center/src/components/help-center-content.tsx`

There you can see:

```tsx
	<Route
		path="/odie"
		element={
			<OdieAssistantProvider
				isLoadingEnvironment={ isLoadingEnvironment }
				botNameSlug={ odieBotNameSlug }
				botName="Wapuu"
				odieInitialPromptText={ odieInitialPromptText }
				enabled={ shouldUseWapuu }
				currentUser={ currentUser }
				isMinimized={ isMinimized }
				initialUserMessage={ searchTerm }
				logger={ trackEvent }
				loggerEventNamePrefix="calypso_odie"
				selectedSiteId={ site?.ID as number }
				extraContactOptions={ <ExtraContactOptions isUserElegible={ isUserElegible } /> }
				navigateToContactOptions={ navigateToContactOptions }
				navigateToSupportDocs={ navigateToSupportDocs }
				isUserElegible={ isUserElegible }
			>
				<HelpCenterOdie />
			</OdieAssistantProvider>
		}
```

So we can inject a new property: navigateToHome where we externally use the navigate function.

This way we keep the Odie-client independent to Help-Center or calypso (as the intention is still having a standalone component to be used elsewhere)

File: packages/odie-client/src/index.tsx [hunk 3]
```diff
@@ -12,16 +13,38 @@ export const ODIE_THUMBS_DOWN_RATING_VALUE = 0;
...
 	}, [ trackEvent ] );
 
+	useEffect( () => {
+		const { pathname, search } = location;
+		const shouldRedirectHome = ! isUserElegible && ! isLoading;
+
+		// Prevent not eligible users from accessing wapuu.
+		if ( shouldRedirectHome ) {
+			trackEvent( 'calypso_helpcenter_redirect_not_eligible_user_to_homepage', {
+				pathname,
```
Comment (alshakero) [inline packages/odie-client/src/index.tsx]: These two values wont really help us. Pathname will always be /odie and search will always be empty. This is the virtual pathname inside the Help Center's MemoryRouter, not the global one. 

I would switch to window.location.pathname and search.

**Review by alshakero — APPROVED** [review]
One note, looks great otherwise.

File: packages/odie-client/src/index.tsx (hunk 1 above)
Comment (alshakero) [reply packages/odie-client/src/index.tsx]: Is it covered? The user will seem illegible until the query loads, no?

File: packages/odie-client/src/index.tsx [hunk 4]
```diff
@@ -12,16 +13,38 @@ export const ODIE_THUMBS_DOWN_RATING_VALUE = 0;
...
 	const messagesContainerRef = useRef< HTMLDivElement >( null );
+	const navigate = useNavigate();
 
 	useEffect( () => {
 		trackEvent( 'chatbox_view' );
 	}, [ trackEvent ] );
 
+	useEffect( () => {
+		const { pathname, search } = location;
+		const shouldRedirectHome = ! isUserElegible && ! isLoading;
```
Comment (AllTerrainDeveloper) [inline packages/odie-client/src/index.tsx]: That `isLoading` is not related with the isUerElegible, you should be using `isLoadingEnviroment`

**Review by AllTerrainDeveloper — CHANGES_REQUESTED** [review]

File: packages/odie-client/src/index.tsx (hunk 2 above)
Comment (renancarvalho) [reply packages/odie-client/src/index.tsx]: Thank you for this input @AllTerrainDeveloper, since this business logic belongs to HC and HC configuration, I have decided to move this into HC and keep `Odie` apart from it. It makes more sense to me.

I was not sure where exactly would be the best place to put this, though. I think it is fine where it is now, please let me know your thoughts.

File: packages/help-center/src/components/help-center-content.tsx [hunk 5]
```diff
@@ -76,6 +76,17 @@ const HelpCenterContent: React.FC< { isRelative?: boolean; currentRoute?: string
...
+	useEffect( () => {
+		// Prevent not eligible users from accessing wapuu.
+		if ( ! isUserElegible && ! isLoadingEnvironment ) {
+			recordTracksEvent( 'calypso_helpcenter_redirect_not_eligible_user_to_homepage', {
+				pathname: window.location.pathname,
+				search: window.location.search,
+			} );
+			navigate( '/' );
+		}
+	}, [ isUserElegible, isLoadingEnvironment, navigate ] );
```
Comment (AllTerrainDeveloper) [inline packages/help-center/src/components/help-center-content.tsx]: I would remove the navigate function from the dependencies array. It happened to me frequently that the navigate function is not persistent across renders and might trigger many re renders automatically :)

**Review by AllTerrainDeveloper — CHANGES_REQUESTED** [review]

File: packages/help-center/src/components/help-center-content.tsx (hunk 5 above)
Comment (renancarvalho) [reply packages/help-center/src/components/help-center-content.tsx]: 🤔 I think it is necessary since it is a dependency of that function.
I have tried without it, despite the ESLint error, it did not work well.

Comment (AllTerrainDeveloper) [reply packages/help-center/src/components/help-center-content.tsx]: My bad then, I had pretty bad experiences in the past with navigate function in the deps array :)

**Review by AllTerrainDeveloper — APPROVED** [review]

File: packages/odie-client/src/index.tsx (hunk 2 above)
Comment (arcangelini) [reply packages/odie-client/src/index.tsx]: @AllTerrainDeveloper is there a reason we don't just pass in `navigate()` to Odie and allow it control this from there? I fear we are making many of this one off functions to accommodate Odie's limitations and will be adding more complexity and potentially debt to the Help Center.

**Review by alshakero — APPROVED** [review]
Looks great. I do acknowledge @arcangelini's point that this adds dept to the Help Center, but I think navigation is the Help Center responsivity. Odie doesn't have access to the list of available routes, to the router, and all of those things. The Help Center should handle navigating to a bad route.

**Comment by AllTerrainDeveloper** [comment]
> Looks great. I do acknowledge @arcangelini's point that this adds dept to the Help Center, but I think navigation is the Help Center responsivity. Odie doesn't have access to the list of available routes, to the router, and all of those things. The Help Center should handle navigating to a bad route.

That's the point, thank you for replying, I missed @arcangelini message.

The reason is that we want to make the Client as much universal as possible, looking forward to make it usable anywhere, so Odie should not know about any routes or anything like that, it's "parent" responsibility to send all needed information.

**Review by arcangelini — APPROVED** [review]
My first attempt at testing this I was getting redirected and always ended up in the `/` area for the Help Center. p1723647515016339-slack-C02T4NVL4JJ.

Since your recent commit everything is working as expected. With the wapuu flag I get Wapuu and without I get the home. 🚀 🚀

**Review by agrullon95 — CHANGES_REQUESTED** [review]
The Help Center is broken for my free user. I'm unable to open any articles and I can't access the contact form. It seems to be redirecting to `/`.


https://github.com/user-attachments/assets/ceff1bb5-452a-44db-a59b-a539c951ce9d

**Comment by renancarvalho** [comment]
> The Help Center is broken for my free user. I'm unable to open any articles and I can't access the contact form. It seems to be redirecting to `/`.
> 
>  CleanShot.2024-08-14.at.20.09.31.mp4

Great catch @agrullon95 thanks!

To fix that It would require a check on the current location pathname, if not `/odie`, then redirect to `/`. That would increase the condition complexity and decrease readability. I have decided to choose another approach and use protected routes on `/odie`. This way, the route more robust and less exposed to regressions and, IMO, cleaner.

🙇

**Review by agrullon95 — APPROVED** [review]
Great changes. The Help Center redirection is working correctly for my free user and I can confirm the tracks event is triggered.

**Comment by escapemanuele** [comment]
Hey @renancarvalho, please add Fixes so the PR can be linked to the issue

image
