### PR TITLE
Pages: prevent editing of latest posts page

### LINKED ISSUE #31917: Gutenframe: custom blog posts page shows wp-admin screen
#### Steps to reproduce
1. Use a test site that has opted in to Gutenberg.
1. Create a new page on you site with empty content.
1. Navigate to Customizer -> Homepage Settings and set the above page as a posts page.
2. Go to My Sites > Site Pages. 
3. Attempt to edit the above page.
4. Notice that this will show the wp-admin editor with a blank page.

Since this wp-admin view is iframed, trying to click on `Add new` button or similar functionality will result in `refused to connect` iframing error.

More info in the comments section of this post: p7DVsv-69v-p2.

### PR DESCRIPTION
**Pull request by vindl**
#### Changes proposed in this Pull Request

The content of latest post page is dynamically generated and allowing the
option to edit it was causing confusion for the users. This is also making
our UI consistent, since Edit option was hidden from ellipsis menu on the
right in this case.

Follow up to https://github.com/Automattic/wp-calypso/pull/31953
Fixes #31917

#### Visual changes

Screenshot 2019-04-04 at 15 26 32

#### Testing instructions

1. Navigate to Customizer > Homepage Settings and set the some of your test pages as Latest post page.
2. Navigate to http://calypso.localhost:3000/pages
3. Verify that clicking on that page is not showing redirecting to the page's front end view and not the editor.
4. There should be an Info Popover next to the latest post page title.
5. Differences when compared to #31953: this behavior is now applied regardless of editor preference or whether the post's content is empty.

### CODE REVIEW

File: client/my-sites/pages/page/index.js [hunk 1]
```diff
@@ -374,9 +375,9 @@ class Page extends Component {
 	undoPostStatus = () => this.updatePostStatus( this.props.shadowStatus.undo );
 
 	render() {
-		const { editorUrl, page, shadowStatus, translate, preventEditingInGutenberg } = this.props;
+		const { editorUrl, page, shadowStatus, translate, isPostsPage: latestPostsPage } = this.props;
```
Comment (vindl) [inline client/my-sites/pages/page/index.js]: The linter was complaining here since `isPostsPage` was already declared in upper scope.

File: client/my-sites/pages/page/index.js [hunk 2]
```diff
@@ -459,6 +460,13 @@ class Page extends Component {
 					>
 						{ depthIndicator }
 						{ title }
+						{ latestPostsPage && (
+							<InfoPopover position="right">
+								{ translate(
+									'The content of your latest posts page is automatically generated and it cannot be edited.'
```
Comment (obenland) [inline client/my-sites/pages/page/index.js]: Not a native speaker myself, but removing the `it` might make the text flow a little better

**Comment by vindl** [comment]
Thanks @obenland, updated both in 9cd062ff99c4ef00d0eeb011ec91e64972ebed47.
