### PR TITLE
Domains: Fix Domain Only flow post-checkout redirect

### LINKED ISSUE #56548: Domains Only flow: redirects to incorrect page post-checkout
### Quick summary

When using the `/start/domain` flow, post-checkout the page redirects to an invalid page.

### Steps to reproduce

prerequisite: log out of WordPresss.com account.
prerequisite for a11n: enable store sandbox.

1. start at /start/domain.
2. search for a domain to purchase and select it.
3. opt to purchase just to domain.
4. create a WordPress.com account.
5. enter domain registrar and billing details.
6. checkout.

### What you expected to happen

Page is redirected to `/checkout/thank-you/<domain name>`.

### What actually happened

Page briefly redirects to `/checkout/thank-you/<domain name>`.
It then redirects to `/checkout/thank-you/no-site/<purchase_id>/<purchase_id>`. 

Real example I generated: `https://wordpress.com/checkout/thank-you/no-site/19997771/19997771`

Screen Shot 2021-09-24 at 9 12 59 AM

Screen Shot 2021-09-24 at 9 13 15 AM

### Context

Developing automation testing for Playwright.

### Operating System

_No response_

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Simple, Atomic or both?

_No response_

### Theme-specific issue?

_No response_

### Other notes

No errors in developer console.

Logs from Playwright showing the redirect path:

```
  pw:api   navigated to "https://wordpress.com/checkout/no-site?signup=1&isDomainOnly=1#step2" +3m
  pw:api   navigated to "https://wordpress.com/checkout/thank-you/no-site/19997771" +44s
  pw:api   navigated to "https://wordpress.com/checkout/thank-you/e2eflowtestingdomainonly1632499598092.live" +224ms
  pw:api   navigated to "https://wordpress.com/checkout/thank-you/no-site/19997771/19997771" +597ms
  pw:api   "domcontentloaded" event fired +323ms
  pw:api   navigated to "https://public-api.wordpress.com/wp-admin/rest-proxy/?v=2.0#https://wordpress.com" +6ms
  pw:api   "domcontentloaded" event fired +88ms
  pw:api   "load" event fired +20ms
  pw:api   navigated to "https://wordpress.com/checkout/thank-you/no-site/19997771/19997771" +377ms
  pw:api   "load" event fired +514ms
  pw:api   "networkidle" event fired +544ms
```

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

The erroneous page still has the NavBar, so it is trivial to click on `My Sites` to navigate away.

### PR DESCRIPTION
**Pull request by rafaelgallani**
#### Changes proposed in this Pull Request
Fixes #56548.

Apparently (reported by `git bisect`) #55809 caused a bug for the domain-only flow, reported in #56548.
In short: the redirected post-checkout page is invalid. This PR fixes it.

#### Testing instructions
Same as #56548, but the post-checkout page should be correct:
- Start at `/start/domain`;
- Search for a domain name and add it to the cart;
- Opt to purchase just the domain name ("Just buy a domain" option);
- Add the billing details/checkout information and confirm the checkout;
- Check that after completing the checkout, there is a redirect to the domain-only page.

Also, make sure that the changes won't affect any flows other than the domain-only one.

### CODE REVIEW

**Comment by rafaelgallani** [comment]
I see that two unit tests have failed because of my changes.
But both these two have a comment before their declaration: 
`// Note: This just verifies the existing behavior; I suspect this is a bug`

So I'll update them for now with what I think should be the expected behavior.

File: client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/get-thank-you-page-url.ts [hunk 1]
```diff
@@ -207,8 +207,8 @@ export default function getThankYouPageUrl( {
 
 	// Domain only flow
 	if ( cart?.create_new_blog ) {
-		const newBlogUrl = urlFromCookie || fallbackUrl;
-		const newBlogReceiptUrl = `${ newBlogUrl }/${ pendingOrReceiptId }`;
+		const newBlogUrl = urlFromCookie;
+		const newBlogReceiptUrl = newBlogUrl ? `${ newBlogUrl }/${ pendingOrReceiptId }` : fallbackUrl;
```
Comment (sirbrillig) [inline client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/get-thank-you-page-url.ts]: Suuuper minor but we could get rid of `newBlogUrl` entirely and just rely on `urlFromCookie` directly on this line.

File: client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js [hunk 2]
```diff
@@ -635,18 +635,16 @@ describe( 'getThankYouPageUrl', () => {
 		expect( url ).toBe( '/cookie/:receiptId' );
 	} );
 
-	// Note: This just verifies the existing behavior; I suspect this is a bug
-	it( 'redirects to thank-you page followed by placeholder receiptId twice if no cookie url is set, create_new_blog is set, and there is no receipt', () => {
+	it( 'redirects to thank-you page followed by placeholder receiptId if no cookie url is set, create_new_blog is set, and there is no receipt', () => {
```
Comment (sirbrillig) [inline client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js:638]: Oh thank the gods; this always bothered me ever since I migrated this code into its current location (hence the comments).

**Review by delputnam — APPROVED** [review]
This LGTM.  Nice job!  Thank you!

**Comment by dpasque** [comment]
@rafaelgalani Hi there! 👋 

It looks like with this change, the behavior when closing a domains-only account may have inadvertently changed.  It looks like instead of showing the "Your account has been closed" confirmation page, it now just redirects to the wordpress.com homepage.

We have some new sign-up based tests we've been running in the background to fine tune before making them more public. [The one that goes through the domains-only flow](https://github.com/Automattic/wp-calypso/blob/trunk/test/e2e/specs/specs-playwright/wp-signup__domain.ts) started failing consistently at the close account step after this change merged.

Is there a chance this change could have caused that? Is that intentional behavior? Thanks! 😄

**Comment by worldomonation** [comment]
To expand on what @dpasque is saying - 

Prior to this PR merging, the expected outcome of closing an account is that users are redirected to the page at `client/me/account-close/closed.jsx`.

However, after the account is closed, users are redirected to the top level page at `https://wordpress.com`.

image

In the TeamCity Pre-Release tests, this behavior is confirmed by the e2e tests until this PR is merged (along with another PR #56802). See [TeamCity build](https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Pre_Release/6801955?buildTab=changes#%2Fscreenshots).

**Comment by sirbrillig** [comment]
FWIW, since this PR only changes the URL that you get sent to after checkout, I'm not sure how that would affect the page you get sent to after an account close (although you never know!).

Taking a quick look, the "close account" page seems to send the user to `/me/account/closed` here:

https://github.com/Automattic/wp-calypso/blob/f5ea5f3382ad3a98487bc5fd10104560ace041c0/client/me/account-close/confirm-dialog.jsx#L51-L54

The [route for that path](https://github.com/Automattic/wp-calypso/blob/f5ea5f3382ad3a98487bc5fd10104560ace041c0/client/me/account-close/index.js#L10) takes you to this component:

https://github.com/Automattic/wp-calypso/blob/f5ea5f3382ad3a98487bc5fd10104560ace041c0/client/me/account-close/closed.jsx#L12

And from there there's a link to the home page.

I just tried it manually and it seems to work correctly:

Screen Shot 2021-10-06 at 12 45 31 PM

Perhaps the e2e tests are doing something differently?

**Comment by worldomonation** [comment]
I've been able to narrow down the scenario.

This issue only happens with the Signup: Domain only flow - where an account holding only the domain is created, domain purchased, then cancelled, then account closed.

See the reproduction of the issue:


https://user-images.githubusercontent.com/6549265/136249166-90826b78-b498-414c-85eb-3507b78a2d88.mov


I've been able to narrow this down to a reason: the user has not logged out.

I ran another test, following the exact same steps as the test spec but added a step where I log out of the account, re-log in, then proceed to cancel the domain purchase and close the account. In that case, the redirect occurs as expected:


https://user-images.githubusercontent.com/6549265/136249345-9b02d50a-ac35-4d0b-bf8c-8825a91321ce.mov

**Comment by worldomonation** [comment]
In both situations, a new account was created after entering the `start/domain` flow. So the only difference between the two video replays, is that in the second replay (where the redirect happened as expected) the user logged out once.

**Comment by sirbrillig** [comment]
🤔  In the first replay, the home redirect seems to occur immediately after reaching the confirmation dialog, before clicking "Continue" and then entering in the username for the final confirmation. Are the remaining steps just happening too fast to be in the recording?

**Comment by worldomonation** [comment]
> 🤔 In the first replay, the home redirect seems to occur immediately after reaching the confirmation dialog, before clicking "Continue" and then entering in the username for the final confirmation. Are the remaining steps just happening too fast to be in the recording?

In the first replay, I thought the Close account did not process so I tried to click it again, but in fact the request was being processed.

The first time the username was entered and account closure confirmed, the request was sent and with normal accounts, one would expect the `You account is being closed` spinner to appear, but it does not in the faulty case.

**Comment by sirbrillig** [comment]
Oh, I see it now. Sorry I didn't understand that before!

I wonder where that redirect to the home page is coming from... the only call to `page()` in `AccountCloseConfirmDialog` is to the expected page. 

One thing that looks possibly suspicious is this code which redirects to a [logout page](https://github.com/Automattic/wp-calypso/blob/f5ea5f3382ad3a98487bc5fd10104560ace041c0/client/state/current-user/actions.js#L66).

https://github.com/Automattic/wp-calypso/blob/f5ea5f3382ad3a98487bc5fd10104560ace041c0/client/me/account-close/main.jsx#L38-L43

I wonder if maybe that redirect is triggering before the confirmation dialog's redirect (it's possible since the confirmation redirect uses `page` which may have a delay and the above redirect uses `window` which should be faster), and perhaps [the calculation it uses](https://github.com/Automattic/wp-calypso/blob/f5ea5f3382ad3a98487bc5fd10104560ace041c0/client/lib/user/shared-utils/get-logout-url.js#L3-L27) to determine the logout url is affected by logging-in for the first time.

I'd be curious to see what happens if we reproduce the problem and disable [the redirect in `AccountSettingsClose`](https://github.com/Automattic/wp-calypso/blob/f5ea5f3382ad3a98487bc5fd10104560ace041c0/client/me/account-close/main.jsx#L38-L43).

**Comment by worldomonation** [comment]
Thanks for looking into the root cause!

What I've done is to file a new issue at https://github.com/Automattic/wp-calypso/issues/56841 to hold further discussions.

In the grand scheme of things, I understand this is not such a critical flow - I would wager the only users that sign up for a Domain only account then close the account without logging out once is the e2e script. Most users would likely log out at a minimum prior to terminating their account.

I will go ahead and implement a workaround in the test spec to log out once prior to closing the account, and reference this PR and the newly filed issue in the comments I'll leave on the test step. 

How does this sound?
