### PR TITLE
Editor: When adding a new field in the 'add contact form' dialog, it's expanded automatically for editing it

### LINKED ISSUE #4117: Editor: Contact Form: Enhancement: Default new field to open state on add
#### Steps to reproduce
1. Starting at the editor with new contact form functionality
2. Add or edit a contact form
3. Click "Add New Field"

#### What I expected

New field defaults to open (edit state) as I would like to change title/type etc

#### What happened instead

New field defaults to closed state - so there's an additional step for the user to edit the newly added field

#### Browser / OS version

Chrome OSX 10.11.2

#### Screenshot / Video

add new field
r

### PR DESCRIPTION
**Pull request by DanReyLop**
Before this change, when adding a field to the form it appeared collapsed. Now it appears expanded, ready to be edited.

As a side note, when a `FoldableCard` is expanded, the content doesn't auto-scroll into view, so it can appear than it didn't expanded. What do you think about adding [scrollIntoViewIfNeeded](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoViewIfNeeded) to the `FoldableCard.onOpen` by default? This component is used in many places, but I can't think of any situation when we want to **not** scroll into view when the user expands the card.

cc @rodrigoi @alisterscott 
Fixes #4117

### CODE REVIEW

File: client/components/tinymce/plugins/contact-form/dialog/field-list.jsx [hunk 1]
```diff
@@ -24,11 +24,10 @@ export default React.createClass( {
 			return (
 				<div className="editor-contact-form-modal-fields">
 					{ this.props.fields.map( ( field, index ) => {
-						const { label, type, options, required } = field;
 						return (
 							<Field
 								key={ index }
-								{ ...{ label, type, options, required } }
+								{ ...field }
```
Comment (rodrigoi) [inline client/components/tinymce/plugins/contact-form/dialog/field-list.jsx]: good catch!

File: client/state/ui/editor/contact-form/constants.js [hunk 2]
```diff
@@ -20,5 +20,6 @@ export const CONTACT_FORM_DEFAULT = {
 
 export const CONTACT_FORM_DEFAULT_NEW_FIELD = {
 	label: 'Text',
-	type: CONTACT_FORM_FIELD_TYPES.text
+	type: CONTACT_FORM_FIELD_TYPES.text,
+	expanded: true
```
Comment (rodrigoi) [inline client/state/ui/editor/contact-form/constants.js]: this should be `isExpanded`.

**Comment by rodrigoi** [comment]
This is not working as expected. If you add, for example, two fields, and then change tabs to _Settings_ and back to _Form Fields_, those two new fields are open.

I would approach this from a different angle. The new field is __always__ added at the end of the fields array. That way you only need to know if the field list is _dirty_, and clear that _ui_ state on the `FoldableCard` `onClose` method.
That way, we can keep the field object clean of any properties that we shouldn't serialize back to the shortcode.

**Comment by alisterscott** [comment]
Thanks for your fix. I've tested this and the only issue I saw was what @rodrigoi mentioned above about when you add a new field and then close it, switching to the settings tab and returning back means it's opened again.

> As a side note, when a FoldableCard is expanded, the content doesn't auto-scroll into view, so it can appear than it didn't expanded. What do you think about adding scrollIntoViewIfNeeded to the FoldableCard.onOpen by default? This component is used in many places, but I can't think of any situation when we want to not scroll into view when the user expands the card.

I think this would be good functionality to have, but I would like to do some testing of those other places this component is in use to ensure we don't introduce any regressions.

**Comment by DanReyLop** [comment]
I've fixed the bogus behaviour, I've played with the form more extensively this time and it looks fine.

@rodrigoi Your approach in an ideal world it would be better, but since the `FoldableCard` is not a pure component, it would be quite messy (unless I'm not understanding anything, which is a very real possibility).

I tweaked my previous approach so now the field ìsRequired` property is updated (through Redux) when the `FoldableCard` is open / closed. That property is not serialized to the shortcode (I've checked), and since we are using the Redux state for UI (for example, to see in which tab is the user) I think that's a correct approach.

Let me know what you think about it.

@alisterscott You're totally right, that component is used in quite a few places, and critical ones like payments, I'll create a separate PR for the `scrollIntoView`.

**Comment by DanReyLop** [comment]
@rodrigoi Could you please take a look at this? I forgot completely that I had this PR sitting around.

**Comment by rodrigoi** [comment]
@DanReyLop feel free to merge this as your earliest convenience 😉 

:shipit:
