### PR TITLE
Editor: Simple Payments plugin now queries for Plans

### LINKED ISSUE #26373: Simple Payments Not Allowed on Plan Although it's a Premium Account
#### Steps to reproduce
1. Calypso Page Editor for site `https://easyartparties.com/weeones`
2. Add Simple Payment Botton
3. Add images and fill out all information and adding the price and allowing users to purchase multiple quantities of each item
4. Publish

#### What I expected

Items added are available for sale to the public.

#### What happened instead

The error message is displayed to Administrator
```
Your plan doesn't include Simple Payments. Learn more and upgrade.
(Only administrators will see this message.)
```

The Page does not have any Simple Payments for the Public.

### What I Tried ####

- Re-adding the Premium Plan
- Changing the theme
- Creating a new page 

#### Browser / OS version
 Firefrox as a Public Viewer- Unproxy
Google Chrome for SU/SSP

#### Screenshot / Video

**For Admin**
screen shot 2018-07-29 at 12 54 13 pm

**Public**: 
screen shot 2018-07-29 at 12 55 28 pm

#### Context / Source

I was unable to recreate this issue on my test site but could recreate on user's account. I do think have a work-around

If user agrees, complete the following:

- Create a new site for you with a new Premium Plan
- Export all content from the Old Site to the New Site
- Import all of your posts, pages, media, and comments, etc. to the new site
- Try Simple Payments Again

#manual-testing,
#user-report if applicable: 1311470-zen

### PR DESCRIPTION
**Pull request by rodrigoi**
Fixes #26373 

When loading the editor directly from the _Edit_ link on a site's frontend, if the page or post has simple payment buttons they won't show correctly, displaying the admin alert instead. This is because the site's plan state isn't ready.

| Before | After |
| - | - |
| screen shot 2018-08-01 at 13 27 57 | screen shot 2018-08-01 at 13 26 57 |

To test this:

* On a Premium or Business Sites (Premium or Professional for Jetpack), add one or more Simple Payments Products to a page or post.
* Publish the changes.
* Refresh the editor.

Without this fix, the feature not supported warning will show, but with this fix applied, the product should render correctly.

### CODE REVIEW

File: client/components/tinymce/plugins/wpcom-view/views/simple-payments/index.jsx [hunk 1]
```diff
@@ -19,18 +19,30 @@ import getSimplePayments from 'state/selectors/get-simple-payments';
...
+			siteId,
+			sitePlan,
+			planHasSimplePaymentsFeature,
+		} = this.props;
 
 		if ( ! product ) {
 			return <QuerySimplePayments siteId={ siteId } productId={ productId } />;
 		}
 
+		if ( ! sitePlan ) {
```
Comment (gwwar) [inline client/components/tinymce/plugins/wpcom-view/views/simple-payments/index.jsx]: No need for the check here. When rendering, we always need plan data. We can easily get into a situation where in memory data, or persisted browser data is out of sync. So if we declare a QueryComponent, generally we shouldn't need any conditional. 

(QuerySimplePayments for example should probably be refactored a bit to provide an `all` boolean so we don't need the product check).

Comment (rodrigoi) [reply client/components/tinymce/plugins/wpcom-view/views/simple-payments/index.jsx]: I did use a conditional here because otherwise the UI will either flash the admin warning or the product information while loading the site's plan:

aug-01-2018 18-32-57

I think that given how often Plan data is updated, this is a good first fix until we update `QuerySimplePayments` and the plans selectors to account for a loading state we can use to prevent this.

Comment (gwwar) [reply client/components/tinymce/plugins/wpcom-view/views/simple-payments/index.jsx]: Is possible to render a placeholder when plans is `null`?

**Comment by gwwar** [comment]
Hmm, let's 🚢 this to start, and could we follow up with a janitorial to refactor the component to always render the query component? We can create a helper function named something like `getSimplePaymentView` to return a placeholder, the warning or the full view:
```
return (
            <div className="wpview-content wpview-type-simple-payments">
                <QueryMedia siteId={ siteId } mediaId={ productImageId } />
                <QuerySimplePayments siteId={ siteId } productId={ productId } />
                <QuerySitePlans siteId={ siteId } />;
                { getSimplePaymentView() }
            </div>
        );
```
