### PR TITLE
Reader: Update share menu Twitter icon to X icon

### LINKED ISSUE #99407: Sharing button still points to Twitter (text + icon)
### Context and steps to reproduce

In the reader, there's a "sharing" button to share a post. One of the links it suggests says "Twitter" and uses the old icon (bird):

https://github.com/user-attachments/assets/0a94e5a6-536c-4868-b078-f930c9b6462d

The button works but the look&feel is outdated, given the Twitter-X rename happened many months ago.

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Minor

### What other impact(s) does this issue have?

_No response_

### If a workaround is available, please outline it here.

_No response_

### Platform

_No response_

### PR DESCRIPTION
**Pull request by artemiomorales**
Related to https://github.com/Automattic/wp-calypso/issues/99407

## Proposed Changes

This updates the Twitter icon to the X icon in the share menu on posts in the Reader.

### Before

Screenshot 2025-02-17 at 16 51 35

### After

Screenshot 2025-02-17 at 16 49 41

## Why are these changes being made?

It's been months since Twitter rebranded to X, and we want to keep the Reader up to date.

## Testing Instructions

- Go to the Reader
- Click on the "Share" button underneath any post
- See that the Twitter icon has been replaced by the X icon
- Click on the icon and ensure the sharing flow works as expected

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/reader/components/icons/x-icon.jsx [hunk 1]
```diff
@@ -0,0 +1,15 @@
+export default function ReaderXIcon( { iconSize } ) {
+	return (
+		<svg
+			key="x"
+			fill="none"
+			className="reader-x"
+			viewBox="0 0 1200 1227"
```
Comment (mehmoodak) [inline client/reader/components/icons/x-icon.jsx:7]: The value seems unusually large 🤔

File: client/blocks/reader-share/style.scss [hunk 2]
```diff
@@ -144,18 +144,18 @@
 		fill: var(--color-primary);
 	}
 
-	.reader-twitter {
-		fill: var(--color-twitter);
```
Comment (mehmoodak) [inline client/blocks/reader-share/style.scss:148]: Seems like we are using this variable in a couple of other places which also needs update (for follow up PR)

File: client/blocks/reader-share/social.jsx [hunk 3]
```diff
@@ -14,17 +14,17 @@ import { recordReaderTracksEvent } from 'calypso/state/reader/analytics/actions'
  * Local variables
  */
 const actionMap = {
-	twitter( post ) {
+	x( post ) {
 		const baseUrl = new URL( 'https://twitter.com/intent/tweet' );
```
Comment (mehmoodak) [inline client/blocks/reader-share/social.jsx:29]:
```suggestion
		const baseUrl = new URL( 'https://x.com/intent/tweet' );
```

File: client/blocks/reader-share/social.jsx [hunk 4]
```diff
@@ -84,13 +84,13 @@ const ReaderSocialShareSelection = ( props ) => {
...
-				action="twitter"
+				action="x"
 				className="reader-share__popover-item"
-				title={ translate( 'Share on Twitter' ) }
+				title={ translate( 'Share on X' ) }
 				focusOnHover={ false }
 			>
-				<ReaderTwitterIcon iconSize={ 20 } />
-				<span>Twitter</span>
+				<ReaderXIcon iconSize={ 20 } />
```
Comment (mehmoodak) [inline client/blocks/reader-share/social.jsx:118]: The alignment of all social icons looks a bit off, can we place make it exactly center aligned.

image

File: client/blocks/reader-share/social.jsx [hunk 5]
```diff
@@ -14,17 +14,17 @@ import { recordReaderTracksEvent } from 'calypso/state/reader/analytics/actions'
...
 			text: post.title,
 			url: post.URL,
 		} );
 		baseUrl.search = params.toString();
 
-		const twitterUrl = baseUrl.href;
+		const xUrl = baseUrl.href;
 
-		window.open( twitterUrl, 'twitter', 'width=550,height=420,resizeable,scrollbars' );
+		window.open( xUrl, 'x', 'width=550,height=420,resizeable,scrollbars' );
```
Comment (mehmoodak) [inline client/blocks/reader-share/social.jsx]: Currently we are opening new window on top left corner of the browser, can we open the new window on center of the browser? It will look better 🤔

**Review by mehmoodak — APPROVED** [review]
The change itself is working good, just left some small feedback.

File: client/reader/components/icons/x-icon.jsx (hunk 1 above)
Comment (artemiomorales) [reply client/reader/components/icons/x-icon.jsx:7]: I downloaded the SVG right from the [X brand toolkit](https://about.x.com/en/who-we-are/brand-toolkit). It's a very strange aspect ratio that doesn't scale to easy, round numbers 🧐 Here's an example:

Screenshot 2025-02-17 at 17 32 23

I personally don't see a compelling reason to change the official values, though I'm happy to discuss further! Let me know what you think.

File: client/blocks/reader-share/social.jsx (hunk 3 above)
Comment (artemiomorales) [reply client/blocks/reader-share/social.jsx:29]: Oh I forgot to write a note here when I created this PR — changing the base URL to `x.com` breaks the sharing of the featured image when sharing the post. It seems the API may have been updated in the move to X.

I started briefly looking into updating this URL, but it seemed to be more trouble than it was worth and I defaulted to, "If it isn't broken, don't fix it."

File: client/blocks/reader-share/style.scss (hunk 2 above)
Comment (artemiomorales) [reply client/blocks/reader-share/style.scss:148]: Issue created here: https://github.com/Automattic/wp-calypso/issues/99873

File: client/blocks/reader-share/social.jsx (hunk 4 above)
Comment (artemiomorales) [reply client/blocks/reader-share/social.jsx:118]: Will do!

File: client/blocks/reader-share/social.jsx (hunk 3 above)
Comment (mehmoodak) [reply client/blocks/reader-share/social.jsx:29]: How about we add a comment for this in codebase?

File: client/blocks/reader-share/social.jsx (hunk 4 above)
Comment (artemiomorales) [reply client/blocks/reader-share/social.jsx:118]: Done 👍
They're absolutely positioned with a `top` value of 9.75px — I think it looks pretty centered.

File: client/blocks/reader-share/social.jsx (hunk 5 above)
Comment (artemiomorales) [reply client/blocks/reader-share/social.jsx]: Done!
I also applied the fix to the Facebook popup.

File: client/blocks/reader-share/social.jsx (hunk 3 above)
Comment (artemiomorales) [reply client/blocks/reader-share/social.jsx:29]: Done!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17260693

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @artemiomorales for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17260693).
