### PR TITLE
Author Selector: Auto-focus using prop rather than ref

### LINKED ISSUE #49200: Search: Forwarded ref not applied causing manual focusing of element not to work
### Steps to reproduce the behavior

1. Get a site with multiple authors (at least 10)
2. Go to `people/edit/:site/:user`
3. Scroll to the bottom and select the option to attribute posts by the author to another.
4. Click the "Choose an author" button

#### What I expected to happen
According to the code, the search should auto-focus

#### What actually happened
The search does not auto-focus because the ref is not forwarded.

#### Browser / OS version
Firefox, macOS Big Sur

#### Is this specific to the applied theme? Which one?
N/A

#### Does this happen on simple or atomic sites or both?
N/A

#### Is there any console output or error text?
Yes, there is an error about refs not working

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low

### PR DESCRIPTION
**Pull request by sarayourfriend**
#### Changes proposed in this Pull Request

* Switches the auto-focusing logic to use the auto-focus prop rather than manually auto-focusing.

Fixes #49200

#### Testing instructions

1. Get a site with multiple authors (at least 10)
2. Go to people/edit/:site/:user
3. Scroll to the bottom and select the option to attribute posts by the author to another.
4. Click the "Choose an author" button
5. Ensure that the search is auto-focused

Search doesn't appear for sites with less than 10 users, so no need to test that.

You can test on a mobile device if possible and ensure that search is not auto-focused on it.

### CODE REVIEW

File: client/blocks/author-selector/switcher-shell.jsx [hunk 1]
```diff
@@ -107,7 +97,8 @@ class AuthorSwitcherShell extends React.Component {
 							onSearch={ this.onSearch }
 							placeholder={ this.props.translate( 'Find Author…', { context: 'search label' } ) }
 							delaySearch={ true }
-							ref={ this.authorSelectorSearchRef }
+							// eslint-disable-next-line jsx-a11y/no-autofocus
```
Comment (lynnbgriffith) [inline client/blocks/author-selector/switcher-shell.jsx:100]: @diegohaz What do you think of this eslint rule (`jsx-a11y/no-autofocus`). Autofocus in direct response to a user event like this shouldn’t raise a11y concerns, right? Do you think this eslint rule provides any value generally?

**Review by lynnbgriffith — APPROVED** [review]
👍 LGTM
