### PR TITLE
Nav-unification - Sidebar Scroll: fix scrolling when content is shorter than sidebar.

### LINKED ISSUE #48133: Scrolling is lost when using some of the Expanded Navigation Options
1. Load your page and note you can scroll up and down to see all navigation options.
2. Click on Users (the same happens with Appearance). 
3. Note you can no longer scroll. You have to expand the browser page to see the options again.

#### What I expected

To be able to scroll. 

#### What happened instead

I could not scroll

#### Browser / OS version

Firefox 83.0 (64-bit)

Browser window size: 1082 x 676

#### Screenshot / Video

Screen Capture on 2020-12-08 at 13-43-10

We'd also love to know how you found the bug: #manual-testing

### PR DESCRIPTION
**Pull request by cpapazoglou**
#### Changes proposed in this Pull Request

The new sidebar scrolling experience that wp-admin has and we have adopted in calypso for the nav-unification project, didn't handle cases where the content was shorter than the sidebar

In the cases pictured above, there was no scroll event triggered cause the content was smaller than the window and the sidebar is `position: fixed` with `overflow: initial`. There could potentially be another fix by **completely refactoring** the layout - sidebar code so that the sidebar in not fixed initially. I ended up using a trick ( making content slightly higher than the window ) so that the scroll event kicks in and adjusts the heights accordingly.

#### Testing instructions

* make sure you assign yourself to the treatment variation ( paYJgx-1af-p2 ).
* in a high enough window load https://wordpress.com/posts/cpapfree.wordpress.com .
* you should not be able to scroll.
* adjust your window height to be shorter than the sidebar and taller than the content.
* now you should be able to scroll.

Fixes https://github.com/Automattic/wp-calypso/issues/48133

### CODE REVIEW

File: client/layout/utils.ts [hunk 1]
```diff
@@ -17,27 +17,52 @@ export function getShouldShowAppBanner( site: any ): boolean {
...
 	const masterbarHeight = document.getElementById( 'header' )?.getBoundingClientRect().height;
 
+	// Check whether we need to adjust content height so that scroll events are triggered.
+	// Sidebar has overflow: initial and position:fixed, so content is our only chance for scroll events.
+	if (
+		content &&
+		contentHeight &&
+		masterbarHeight &&
+		secondaryElHeight &&
+		window.innerWidth > 660 // Run only for desktop viewports.
```
Comment (getdave) [inline client/layout/utils.ts]: Consider extracting to a var such as `isDesktopViewport` and removing the comment. Self documenting FTW.

File: client/layout/utils.ts [hunk 2]
```diff
@@ -17,27 +17,52 @@ export function getShouldShowAppBanner( site: any ): boolean {
...
+	}
+
 	if (
 		typeof window !== undefined &&
 		secondaryEl !== undefined &&
 		secondaryEl !== null &&
 		secondaryElHeight !== undefined &&
 		masterbarHeight !== undefined &&
-		window.innerWidth > 660 && // Do not run when sidebar is fullscreen
+		window.innerWidth > 660 && // Run only for desktop viewports.
```
Comment (getdave) [inline client/layout/utils.ts]: Same re: self documenting var

**Review by getdave — COMMENTED** [review]
Thanks for noticing this and for the PR.

I'm not sure if this works or not. See [this video](https://d.pr/v/cWxGXh/7tDVb6Fhjz) which shows the weird behaviour of the sidebar when I reduce the height of the window.

I was using the Calypso Live link to test.

File: client/layout/utils.ts (hunk 1 above)
Comment (cpapazoglou) [reply client/layout/utils.ts]: Great suggestion! In fact, as I was refactoring it came to me that we need to check for the viewport only once. So I simplified the code by returning early 05c946d.

**Comment by obenland** [comment]
Is this still in progress or ready for review?

**Comment by cpapazoglou** [comment]
This has been reviewed and has a flaw in an edge case as Dave says here https://github.com/Automattic/wp-calypso/pull/47901#pullrequestreview-541985668 .

I have pushed it back in an effort to work on issues that affect the Jetpack Release. We can probably merge it though, as it is an enhancement over the current situation and iterate further. How do you feel @davemart-in ?

**Comment by davemart-in** [comment]
> We can probably merge it though, as it is an enhancement over the current situation and iterate further.

I agree.
