### PR TITLE
Checkout: Display plan discount in `SecondaryCount`

### LINKED ISSUE #4039: Plans: domain discount isn't displayed until page is refreshed
When a user purchases a domain, they don't see the discount on the plans page straight away because the plans data is stale. We to refetch it after the user purchases a domain.

Plans page after purchasing a domain:
screen shot 2016-03-15 at 10 47 16

Plans page after clearing local storage:
screen shot 2016-03-15 at 10 47 55
 
Steps to reproduce:
1. Create a site on the free plan
2. Add a domain to the site
3. Visit /plans
4. Assert that the plan price is still $99 not $79
5. Clear local storage
6. Assert that the plan price is still now $79

### PR DESCRIPTION
**Pull request by drewblaisdell**
This PR adds these messages to checkout when purchasing a plan with a discount:

screen shot 2016-03-18 at 2 50 32 pm
screen shot 2016-03-18 at 2 59 11 pm

Requires D1365-code. Also fixes #4039.

**Testing**
*Discount from a prior domain purchase*
- Visit `/start` and create a new site without selecting a domain or a paid plan.
- Visit `/domains/add/:site` and add a domain to your cart.
- Purchase the domain.
- When you reach the thank you page, click 'My Sites' in the masterbar.
- Click 'Plan' in the sidebar.
- Assert that the premium/business plans each have a discount.
- Add either plan to your cart.
- Assert that you see a message indicating why the plan is cheaper in the cart at checkout:
screen shot 2016-03-18 at 2 50 32 pm

*Discount from a prior premium plan purchase when upgrading to  #business*
- Visit `/start` and create a new site without selecting a domain or a paid plan.
- Visit `/plans/:site` and add the premium plan to your cart.
- Purchase the premium plan.
- Visit `/plans/:site` and add the business plan to your cart.
- Assert that you see a message indicating why the plan is cheaper in the cart at checkout:
screen shot 2016-03-18 at 2 59 11 pm

- [x] Code review
- [x] Product review

### CODE REVIEW

**Comment by scruffian** [comment]
> I still need to determine how to not display this message when the discount comes from upgrading from premium to business – right now, this is displayed for all discounts, regardless of whether they are because of a previous domain purchase.

This sounds like business logic - I think it should happen on the server. I am working on a patch.

**Comment by Tug** [comment]
Product :+1:

File: client/my-sites/upgrades/cart/cart-plan-discount-ad.jsx [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+
+	componentDidMount() {
+		this.props.fetchSitePlans( this.props.sitePlans, this.props.selectedSite );
+	},
+
+	render() {
+		const { cart, sitePlans } = this.props;
+		let plan;
+
+		if ( ! sitePlans.hasLoadedFromServer || ! cart.hasLoadedFromServer || ! cartItems.getAll( cart ).some( isPlan ) ) {
```
Comment (Tug) [inline client/my-sites/upgrades/cart/cart-plan-discount-ad.jsx]: `cartItems.getAll( cart ).some( isPlan )` could be replaced by `cartItems.hasPlan( cart )`

File: client/my-sites/upgrades/cart/cart-plan-ad.jsx [hunk 2]
```diff
@@ -32,12 +33,15 @@ const CartPlanAd = React.createClass( {
...
 		return (
-			<div className="cart-plan-ad">{
-				this.translate( 'Get this domain for free when you upgrade to {{strong}}WordPress.com Premium{{/strong}}!', {
-					components: { strong: <strong /> }
-				} )
-			} <a href="" onClick={ this.addToCartAndRedirect }>{ this.translate( 'Upgrade Now' ) }</a>
-			</div>
+			<CartAd>
+				{
+					this.translate( 'Get this domain for free when you upgrade to {{strong}}WordPress.com Premium{{/strong}}!', {
```
Comment (scruffian) [inline client/my-sites/upgrades/cart/cart-plan-ad.jsx]: Is it a good idea to move this product name string to a variable? We don't want translators to translate it, and it would make it easier to update the plan names, should we decide to. This should be a different PR since we do this in other places already...

File: client/my-sites/upgrades/checkout-thank-you/index.jsx [hunk 3]
```diff
@@ -89,7 +88,8 @@ const CheckoutThankYou = React.createClass( {
 	},
 
 	refreshSitesAndSitePlansIfPlanPurchased() {
-		if ( this.props.receipt.hasLoadedFromServer && getPurchases( this.props ).some( isPlan ) ) {
+		if ( this.props.receipt.hasLoadedFromServer &&
+			getPurchases( this.props ).some( purchase => isPlan( purchase ) || isDomainRegistration( purchase ) ) ) {
```
Comment (scruffian) [inline client/my-sites/upgrades/checkout-thank-you/index.jsx]: This is probably long enough to warrant moving it to a different function.

File: client/my-sites/upgrades/cart/cart-plan-ad.jsx (hunk 2 above)
Comment (Tug) [inline client/my-sites/upgrades/cart/cart-plan-ad.jsx]: I agree it's better but we would have to load the product list, check that it's loaded... better do it once product-list has been moved to the global state tree.

**Comment by Tug** [comment]
Code :+1:
