### PR TITLE
Account Settings: Fix the username field falsely being marked as changed

### LINKED ISSUE #94474: Account Settings: The unsaved changes browser alert pops up even though the username input value is the same
### Quick summary

In the Accounts Settings page (/me/account), typing in the Username field will change the Account Information card as shown below. However, if the user changes their mind and navigates away, the browser will show an "unsaved changes" warning pop-up.

SCR-20240912-nlyl

### Steps to reproduce

0. Use a non-a11n account.
1. Head to /me/account.
2. Change the username, say from "A" to "AA". Don't save!
3. Then change the username back to "A".
4. Click on "My Profile" to navigate away.
5. Observe as the browser "unsaved changes" pops up, even though the username is still "A".

### What you expected to happen

Just be able to navigate away without any alerts.

### What actually happened

The browser showed the "unsaved changes" alert.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by m1r0**
Resolves https://github.com/Automattic/wp-calypso/issues/94474

## Proposed Changes

This change resets the user name field state when the user name is the same as the initial one. This fixes a bug where you always get the "unsaved changes" popup when the user name is reverted to the initial value.

## Testing Instructions

* Because automatticians are not allowed to change their usernames, apply the following patch:
```diff
--- a/client/me/account/main.jsx
+++ b/client/me/account/main.jsx
@@ -883,10 +883,6 @@ class Account extends Component {
                                                                autoComplete="off"
                                                                autoCorrect="off"
                                                                className="account__username"
-                                                               disabled={
-                                                                       this.getDisabledState( ACCOUNT_FORM_NAME ) ||
-                                                                       ! this.getUserSetting( 'user_login_can_be_changed' )
-                                                               }
                                                                id="user_login"
                                                                name="user_login"
                                                                onFocus={ this.getFocusHandler( 'Username Field' ) }
```
* Head to /me/account.
* Change your username. You should see a "Confirm Username" field. If you see an "Automatticians are not permitted to access this resource." error, that's normal.
* Change it back to the initial value.
* Click on "My Profile" to navigate away.
* There should be no "unsaved changes" popup.
* To make sure the "unsaved changes" popup is working, change your username and try to navigate away without reverting it.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by m1r0** [comment]
Hey, @okmttdhr! 👋 Not sure who to ping for a review so I'm going with what Github has suggested. Let me know if this doesn't fall into your domain.

File: client/me/account/main.jsx [hunk 1]
```diff
@@ -366,8 +366,15 @@ class Account extends Component {
...
+		const value = event.currentTarget.value;
+
+		if ( value === this.getUserOriginalSetting( 'user_login' ) ) {
+			this.cancelUsernameChange();
+			return;
+		}
+
 		this.validateUsername();
-		this.updateUserSetting( 'user_login', event.currentTarget.value );
+		this.updateUserSetting( 'user_login', value );
```
Comment (Imran92) [inline client/me/account/main.jsx:377]: The solution here is working as expected for me 👍 

Not a strong opinion, but I've noticed that there's already a similar check under the validation function which checks if the current username is equal to the input username and sets the validation to false if it is. https://github.com/Automattic/wp-calypso/blob/4806985beff3ec7d7e44e76f106a3616f20e255f/client/me/account/main.jsx#L224-L226

So I was wondering if we should utilize that instead of putting the check again here.

**Review by Imran92 — APPROVED** [review]
LGTM, but I've left a small comment

File: client/me/account/main.jsx (hunk 1 above)
Comment (m1r0) [reply client/me/account/main.jsx:377]: Thanks for the review, Imran! 

> So I was wondering if we should utilize that instead of putting the check again here.

Resetting the UI seems a bit more specific to me, so I prefer not to tie it with the validation.
