### PR TITLE
Jetpack Search: Show Correct Information if Disabled

### LINKED ISSUE #52405: Jetpack Search: shows as active on your site even if toggled off
### Steps to reproduce the behavior
1. On a site with a Jetpack Search plan purchased, go to Settings > General > Performance
2. Click to deactivate Jetpack Search with "Improve built-in WordPress search performance." toggle
3. Go to `/jetpack-search`

#### What I expected to happen

If I have an active Jetpack Search plan but have chosen to turn off Jetpack Search, the page should say that.

#### What actually happened

If I have an active Jetpack Search plan but have chosen to turn off Jetpack Search, I am still told "Jetpack Search is active on your site".

### Context

Raised by @jinnypark in Automattic/jpop-issues#6586.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Medium. The page isn't showing the correct information in this scenario.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

image

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

* Accurately convey that Jetpack Search is disabled when that's the case, and encourage people to enable it.

#### Testing instructions

Disable Jetpack Search under Settings > General > Performance and verify the screen on `/jetpack-search` accurately conveys that the product has been disabled.

Screenshot 2021-04-30 at 17 00 40

cc @bluefuton 

Fixes #52405

### CODE REVIEW

File: client/my-sites/jetpack-search/main.tsx [hunk 1]
```diff
@@ -71,15 +77,25 @@ export default function JetpackSearchMain(): ReactElement {
 			/>
 
 			<PromoCard
-				title={ translate( 'Jetpack Search is active on your site.' ) }
+				title={
+					isSearchEnabled
+						? translate( 'Jetpack Search is active on your site.' )
```
Comment (kangzj) [inline client/my-sites/jetpack-search/main.tsx]:
```suggestion
						? translate( 'Jetpack Search is enabled on your site.' )
```

File: client/my-sites/jetpack-search/main.tsx [hunk 2]
```diff
@@ -71,15 +77,25 @@ export default function JetpackSearchMain(): ReactElement {
...
+				}
 				image={ { path: JetpackSearchSVG } }
 				isPrimary
 			>
-				<p>{ translate( 'Your visitors are getting our fastest search experience.' ) }</p>
+				<p>
+					{ isSearchEnabled
+						? translate( 'Your visitors are getting our fastest search experience.' )
+						: translate(
+								'Enable it to ensure your visitors receive our fastest search experience.'
```
Comment (kangzj) [inline client/my-sites/jetpack-search/main.tsx]:
```suggestion
								'Enable it to ensure your visitors get our fastest search experience.'
```

Comment (Aurorum) [reply client/my-sites/jetpack-search/main.tsx]: Committed those changes. :)

File: client/my-sites/jetpack-search/main.tsx [hunk 3]
```diff
@@ -71,15 +77,25 @@ export default function JetpackSearchMain(): ReactElement {
...
+						  ) }
+				</p>
 
 				<PromoCardCTA
 					cta={ {
-						text: translate( 'Settings' ),
+						text: isSearchEnabled ? translate( 'Settings' ) : translate( 'Enable now' ),
```
Comment (kangzj) [inline client/my-sites/jetpack-search/main.tsx]: I feel like if it's 'Enable now', then if user clicks this button, then the search would be enabled, which is actually not the case. But I don't have a better option. Do you have one?
Or possibly we could keep just 'Settings' button here?  :-)

**Comment by kangzj** [comment]
Hi @Aurorum thank you so much for your contribution. It works awesome. We really appreciate it. 👍 
Just a couple of literal suggestions as commented in the review. Thanks again.

File: client/my-sites/jetpack-search/main.tsx (hunk 3 above)
Comment (Aurorum) [reply client/my-sites/jetpack-search/main.tsx]: Ah, good point! Maybe `Configure now`? Otherwise I'm happy to keep it as `Settings`.

Comment (kangzj) [reply client/my-sites/jetpack-search/main.tsx]: Thanks for your prompt reply 👍 
I'm happy to keep it as `Settings` :-)

Comment (Aurorum) [reply client/my-sites/jetpack-search/main.tsx]: Sure thing - fixed!

**Comment by kangzj** [comment]
@Aurorum Hi thanks for your prompt changes. Sorry it is the end of my day now, I'll come back and continue tomorrow if it's okay.

**Comment by Aurorum** [comment]
No worries, thanks @kangzj!

**Review by kangzj — APPROVED** [review]
It works perfectly for me. Thanks for your contribution. 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5869378

Thank you @Aurorum for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5869378).
