### PR TITLE
PG Onboarding flow: Show an error screen when invalid playground id is supplied

### LINKED ISSUE #102507: Playground onboarding flow not existing ID
### Context and steps to reproduce

An error is generated if an onboarding flow URL is shared with a Playground OPFS ID that does not exist in the target machine.

https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/playground/lib/initialize-playground.ts#L36

We assume that when an ID is passed in the query, then Playground is installed. A proper call to `playgroundAvailableInOpfs` must be added. Otherwise, an error is generated:

```
Uncaught (in promise) Error: WordPress installation has failed.
    at bootWordPress (worker-thread-af9966f2.js:111:1857)
    at async PlaygroundWorkerEndpoint.boot (worker-thread-af9966f2.js:823:2796)
```

The ID passed can be reused without being regenerated, so there will be no need to change the query parameter.

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Low

### What other impact(s) does this issue have?

_No response_

### If a workaround is available, please outline it here.

_No response_

### Platform

_No response_

### PR DESCRIPTION
**Pull request by ashfame**
Related to #102507

## Proposed Changes

* Add a new screen showing the error
* 5 sec counter to auto create a new playground

## Screenshot

Now with 5 sec timer:
Screenshot 2025-05-01 at 01 50 34

<details><summary>Previously with button</summary>
<p>
Screenshot 2025-04-18 at 13 41 52
</p>
</details> 

## Why are these changes being made?

* When playground ID is supplied, we try to boot from it which would fail if the playground ID is not valid. This would happen if someone shares their URL of the playground, which obviously exists only in their browser.

## Testing Instructions

* Specify a non-existent playground ID like http://calypso.localhost:3000/setup/onboarding/playground?playground=fail to see the screen.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/landing/stepper/declarative-flow/internals/steps-repository/playground/components/playground-error/index.tsx [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+import './style.scss';
+
+export function PlaygroundError( { createNewPlayground }: { createNewPlayground: () => void } ) {
+	const [ searchParams ] = useSearchParams();
+	const playgroundId = searchParams.get( 'playground' );
+
+	const errorMessage = sprintf(
+		// translators: %s is the playground ID from the URL
+		__(
+			'The playground you are trying to access (ID: %s) does not exist or is no longer available in this browser.'
```
Comment (bgrgicak) [inline client/landing/stepper/declarative-flow/internals/steps-repository/playground/components/playground-error/index.tsx:15]: Should it be an uppercase p?
```suggestion
			'The Playground you are trying to access (ID: %s) does not exist or is no longer available in this browser.'
```

File: client/landing/stepper/declarative-flow/internals/steps-repository/playground/lib/initialize-playground.ts [hunk 2]
```diff
@@ -12,6 +12,21 @@ export const LOCAL_STORAGE_KEY_FOR_PG_ID = 'pg_flow_pg_id';
...
+		return Promise.resolve( false );
+	}
+
+	// TODO: check if WordPress is installed using playgroundAvailableInOpfs from @wp-playground/website
+
+	// TODO: remove this case which was deliberately added for testing
+	if ( playgroundId === 'fail' ) {
+		return Promise.resolve( false );
+	}
+
```
Comment (bgrgicak) [inline client/landing/stepper/declarative-flow/internals/steps-repository/playground/lib/initialize-playground.ts]:
```suggestion
	// TODO: remove this case which was deliberately added for testing
	if ( playgroundId === 'fail' ) {
		return Promise.resolve( false );
	}

```

**Review by bgrgicak — APPROVED** [review]
The error message looks good, I just highlighted the test code that we need to remove before merging.

File: client/landing/stepper/declarative-flow/internals/steps-repository/playground/components/playground-error/style.scss [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+  justify-content: center;
+  height: 100%;
+  width: 100%;
+  background-color: #f6f7f7;
+
+  &__content {
+    max-width: 500px;
+    padding: 2rem;
+    text-align: center;
+    background-color: white;
```
Comment (zaerl) [inline client/landing/stepper/declarative-flow/internals/steps-repository/playground/components/playground-error/style.scss]: The builder is saying that "white is an unexpected color name". We should check if we must use a global variable here.

**Review by zaerl — CHANGES_REQUESTED** [review]

File: client/landing/stepper/declarative-flow/internals/steps-repository/playground/components/playground-error/index.tsx (hunk 1 above)
Comment (ashfame) [reply client/landing/stepper/declarative-flow/internals/steps-repository/playground/components/playground-error/index.tsx:15]: In this case, "playground" is still being used as a common noun, not a proper noun, so the lowercase usage is appropriate. I meant to refer to it as a generic instance of a playground identified by an ID, rather than a product specifically named "Playground" :)

File: client/landing/stepper/declarative-flow/internals/steps-repository/playground/components/playground-error/style.scss (hunk 3 above)
Comment (ashfame) [reply client/landing/stepper/declarative-flow/internals/steps-repository/playground/components/playground-error/style.scss]: @zaerl Can you take a look again? Screenshot in PR description.

File: client/landing/stepper/declarative-flow/internals/steps-repository/playground/components/playground-error/index.tsx [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+								'Creating new playground in %d second\u2026',
+								'Creating new playground in %d seconds\u2026',
+								countdown
+							),
+							countdown
+						) }
+					</p>
+				</div>
+			</div>
+		</div>
```
Comment (bgrgicak) [inline client/landing/stepper/declarative-flow/internals/steps-repository/playground/components/playground-error/index.tsx:49]: Have you considered using an existing component for this?

For example `Notice` (I'm sure there's a better one, but this is the first I found).

```suggestion
		<Notice status="is-error" text={ errorMessage } showDismiss={ false } />
```

Comment (ashfame) [reply client/landing/stepper/declarative-flow/internals/steps-repository/playground/components/playground-error/index.tsx:49]: Thanks for bringing that up! I checked out the components list, none of them quite fit the bill.

File: client/landing/stepper/declarative-flow/internals/steps-repository/playground/components/playground-error/style.scss (hunk 3 above)
Comment (zaerl) [reply client/landing/stepper/declarative-flow/internals/steps-repository/playground/components/playground-error/style.scss]: 👍

**Review by zaerl — APPROVED** [review]
Great work! 🚢

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17438611

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @ashfame for including a screenshot in the description! This is really helpful for our translators.
