### PR TITLE
Settings: Change wording of blog_public checkbox

### LINKED ISSUE #42180: Site Settings: Clarify Privacy Settings
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/settings
2. Note the language on search engine settings implies we can control whether search engines can access the site.

#### What I expected
Here's the warning from wp-admin, which is more accurate:

> Discourage search engines from indexing this site
> Note: Neither of these options blocks access to your site — it is up to search engines to honor your request.

#### What happened instead
People are confused if their site somehow "ends up on the web" anyway.

#### Context / Source
A user deleted their site, account, and email address that was associated with the account. Later, they found out archive.org still had a copy of the site. And archive.org naturally doesn't want to remove the archive unless the original owner requests it.

The user is upset because they thought ticking that box would protect the site from being indexed anywhere. Seems an adjustment to the language there might help.
https://wordpress.com/forums/topic/internet-archive-copyright-infringement/#post-3489920

### PR DESCRIPTION
**Pull request by mreishus**
fixes #42180

#### Changes proposed in this Pull Request

Url: `/settings/general/example.wordpress.com`

**Old wording:** "Do not allow search engines to index my site"

**New wording:** "Discourage search engines from indexing my site"
with explanation: "This option does not block access to your site — it is up to search engines to honor your request."

---

**Detail:** 

This brings the wording in line with wp-admin from wordpress.org:
[code link](https://github.com/WordPress/WordPress/blob/53c909a8256bbd481656ae864a4b7eb5a22c3692/wp-admin/options-reading.php#L184).

The point of clarification being made is that even though we modify
robots.txt entries to disallow everything, and add a meta robots tag
with "noindex, nofollow", it can still be ignored by search engines.
Putting a sign on your open lawn that says "Do not tresspass" does not
actually stop people from walking forward.

From my research, the wayback machine on archive.org either ignores
robots.txt now or plans to in the future. [1] To be excluded,
archive.org wants the author to send them an individual email, which
they will "review". [2]

1: https://blog.archive.org/2017/04/17/robots-txt-meant-for-search-engines-dont-work-well-for-web-archives/
2: https://help.archive.org/hc/en-us/articles/360004651732-Using-The-Wayback-Machine

This is stemming from a user who had ticked the box, but still found
their site on archive.org, when they thought it would be blocked.  See
issue #42180.

For the unit tests, I needed to add {exact: false} to a few
getByLabelText() calls because the label now spans html elements because
of the `<FormSettingExplanation>` added.  It does not match text across
elements. [3]

3: https://testing-library.com/docs/dom-testing-library/api-queries

---

#### Testing instructions

* Visit calypso.
* Visit Manage -> Settings on the left bar.
* Scroll down to 'privacy' to see the new checkbox label.

#### Other points

This does add new translated strings.  I'm not sure how to handle that, or what needs to be done.

### CODE REVIEW

File: client/my-sites/site-settings/form-general.jsx [hunk 1]
```diff
@@ -358,7 +358,12 @@ export class SiteSettingsFormGeneral extends Component {
 						disabled={ isRequestingSettings }
 						onClick={ eventTracker( 'Clicked Site Visibility Radio Button' ) }
 					/>
-					<span>{ translate( 'Do not allow search engines to index my site' ) }</span>
+					<span>{ translate( 'Discourage search engines from indexing my site' ) }</span>
```
Comment (a8ci18n) [inline client/my-sites/site-settings/form-general.jsx:361]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **121** times:
`translate( 'Discourage search engines from indexing this site' )` *ES Score: 9*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/blog-public-wording)

Comment (mreishus) [reply client/my-sites/site-settings/form-general.jsx]: Pushed [update/blog-public-wording 4dccc58be9] Small wording change to take advantage of pre-translated strings

File: client/my-sites/site-settings/test/form-general.jsx [hunk 2]
```diff
@@ -159,7 +159,7 @@ describe( 'SiteSettingsFormGeneral ', () => {
 				testProps.fields.blog_public = initialBlogPublic;
 				const { getByLabelText } = renderWithRedux( <SiteSettingsFormGeneral { ...testProps } /> );
 
-				const radioButton = getByLabelText( text );
+				const radioButton = getByLabelText( text, { exact: false } );
```
Comment (jeryj) [inline client/my-sites/site-settings/test/form-general.jsx:162]: Why is the `{ exact: false }` added here (and below)?

Comment (mreishus) [reply client/my-sites/site-settings/test/form-general.jsx:162]: The label of the checkbox now spans html elements because of the added `<FormSettingExplanation>`. `getByLabelText`, by default, looks for exact matches and does not match text across elements: 

https://testing-library.com/docs/dom-testing-library/api-queries
> `ByLabelText`
>It will NOT find the input node for label text broken up by elements.

Comment (jeryj) [reply client/my-sites/site-settings/test/form-general.jsx:162]: I just saw it in your PR description as well 🤦 Sorry I didn't read it more carefully there. Thanks for the explanation!

**Comment by mreishus** [comment]
The e2e tests are failing, but this is a persistent problem not related to this commit.  For example, PR #44550 received approval to merge after some testing people looked at it:
>We've had a bunch of issues the last two days. Today it seems that we've maxed out out signup ttests, so all of those will fail for the rest of the day
The tests failing here are similar: `Looks like creating account is taking to long`
