### PR TITLE
People: Fix send invites error notices and form recovery

### LINKED ISSUE #4073: People: check whether user is blocking email before sending invite (edge case)
It's possible to send out an email to a user who has opted not to receive any emails, if the email unsubscribe happens right after their name is added to the list of users to invite.

#### Steps to reproduce
1. Make sure you have the unsubscribe link handy for a test user of yours
2. Go to People > Add at /people/new/$site
3. Add the user from # 1 to the list  
4. Use the unsubscribe link to stop receiving emails for that user in a different tab
5. Send out the invite
6. See that the invite gets sent successfully

#### What I expected
I expected the invite not to be sent successfully.

### PR DESCRIPTION
**Pull request by ebinnion**
Fixes #4073 (in my testing) cc @v18 

I noticed that the logic for showing error notices when the invite form errors was wrong. 

Previously, we only considered the form submission as errored when the API returned an error object. But, we also want to show an error notice when the submission succeeds but there are some errors.

To test:
- Checkout `fix/invite-send-error-state` branch
- Go to `/people/new/$site` where `$site` is a WP.com site
- Send an invite that is successful. Are you shown a success notice?
- Go to `invite-people/index.jsx` and add a `return false;` to the top of `isSubmitDisabled()`.
- Try to submit the form with at least one errored invitee and at least one successful invitee
- After the form submits, do you see an error notice?
- Are the successful invitees removed?
- Do the errored invitees remain?

cc @lezama for code review and @rickybanister for design/flow review

### CODE REVIEW

**Comment by ebinnion** [comment]
Note: I was able to get a JS error by attempting to submit the form while offline due to `data` not being defined. So, I made use of `get` to more safely get the validation errors.

**Comment by lezama** [comment]
Shouldn't we add the check to the validation endpoint instead?

Code wise looks good :+1:

File: client/lib/invites/actions.js [hunk 1]
```diff
@@ -135,13 +140,31 @@ export function sendInvites( siteId, usernamesOrEmails, role, message, formId )
...
 
-			if ( error ) {
-				dispatch( errorNotice( i18n.translate(
-					'Invitation failed to send',
-					'Invitations failed to send', {
-						count: usernamesOrEmails.length
-					}
-				) ) );
+			if ( isErrored ) {
+				// If we there are no validation errors but the form errored, assume that all errored
```
Comment (lezama) [inline client/lib/invites/actions.js]: If we -> we

File: client/lib/invites/actions.js [hunk 2]
```diff
@@ -124,8 +126,11 @@ export function sendInvites( siteId, usernamesOrEmails, role, message, formId )
 			siteId, usernamesOrEmails, role, message
 		} );
 		wpcom.undocumented().sendInvites( siteId, usernamesOrEmails, role, message, ( error, data ) => {
+			const validationErrors = get( data, 'errors' );
```
Comment (lezama) [inline client/lib/invites/actions.js]: I think it would be better if validations errors are added to `error`?

**Comment by lezama** [comment]
If we could do it on validation we could display the error/tooltip at the invite/token in question.

**Comment by v18** [comment]
This worked for me.

**Comment by rickybanister** [comment]
I'm a little confused, shouldn't we disable the submit button if there are entries in error so you can't send a mixed successful/unsuccessful invite?

**Comment by ebinnion** [comment]
> I'm a little confused, shouldn't we disable the submit button if there are entries in error so you can't send a mixed successful/unsuccessful invite?

Correct. Invitees are pre-validated and we don't allow submitting the form until  all invitees are validated. That being said, there is at least one edge case that @v18 found where if a user happens to block invitations are validation has run then the form reports that the invite was sent successfully. 

Frankly, I don't think we'll end up using this logic too much. But because of the way we validate invitations, I think we either need:

- Something like this where we remove any successful validations and allow the user to try with the errored invitees
- Validate before accepting any invitees and sending invitations.

File: client/lib/invites/actions.js (hunk 2 above)
Comment (ebinnion) [inline client/lib/invites/actions.js]: To make sure we're on the same page, you're suggesting add the list of failed validations to `error`?

If so, I'm not sure how we would add an (object | array) of failed invitations to the error object since it expects a string key, string message, and number error code. We could stringify the object and add it to the message, but that feels awkward.

**Comment by rickybanister** [comment]
Since wp-admin currently allows successful invites to be processed and only returns errors, let's stick with that same approach here. Our pre-submit-validation efforts will do a lot to help curb errors on submission.

**Comment by ebinnion** [comment]
With a :+1: on code from @lezama and @rickybanister sign off on design, I'm going to go ahead and ship this.
