### PR TITLE
Marketing Connections: Fix tour position (updated seenTarget logic)

### LINKED ISSUE #44194: Marketing: Rogue guided tour
I was clicking through the different sub tabs of the marketing section and a guided tour appeared. I suppose I clicked quickly enough to a new tab of the marketing section and it caused this to happen:

image

That tour tip stayed on the screen (at x0,y0 presumably because the div it was supposed to target was removed from the dom when I switched tabs?) as I clicked from tab to tab. 

Larger question is do we need to use a guide tour here or could we have a tooltip appear on hover or something else on the sharing screen?

### PR DESCRIPTION
**Pull request by pablinos**
#### Changes proposed in this Pull Request

This is a fixed version of #44329. After merging @allilevine and I discovered that the tour wouldn't display. @creativecoder found this could be consistently reproduced by clearing Index DB. 

From what I can tell, the initialisation of the state caused by clearing index DB caused the order of asynchronously loaded code and the subsequent rendering of components to change, which threw up a bug with the MutationObserver. The tour step has an `onTargetDisappear` property, which is a callback used when the target element is no longer found in the DOM. The problem was that the logic wasn't checking that the target had ever appeared in the DOM and so was causing the tour to quit before it had been displayed.

#### Testing instructions

The instructions are generally the same as #44329. 

* Go to `/marketing/connections/[YOUR TEST SITE]?tour=marketingConnectionsTour`
* Without this change, the tour should display incorrectly at the top left of the screen. You may have to delete the Calypso database from Index DB to see this bug now
* With this change, the tour should appear once the connection statuses have loaded and as the screen changes it should adjust its position.
* Still with the change applied, delete the Calypso Index DB database, and check that the tour still functions as expected.

The bug looks like this:

image

With the change applied:

image

Fixes #44194

### CODE REVIEW

File: client/layout/guided-tours/config-elements/step.tsx [hunk 1]
```diff
@@ -183,29 +177,36 @@ export default class Step extends Component< Props, State > {
...
+
 		if ( ! this.observer ) {
 			this.observer = new window.MutationObserver( () => {
-				const { target, onTargetDisappear } = this.props;
+				if ( keepRepositioning ) {
+					this.onScrollOrResize();
+				}
 
-				if ( ! target || ! onTargetDisappear ) {
+				if ( ! target || ( ! waitForTarget && ! onTargetDisappear ) ) {
```
Comment (scruffian) [inline client/layout/guided-tours/config-elements/step.tsx:197]: This conditional looks quite complex, it might be nice to comment it to explain what it does (or move it to a function).

File: client/layout/guided-tours/config-elements/step.tsx [hunk 2]
```diff
@@ -183,29 +177,36 @@ export default class Step extends Component< Props, State > {
...
 					return;
 				}
 
-				const targetEl = document.querySelector( `[data-tip-target="${ target }"]` );
-				if ( ! targetEl ) {
+				const targetEl = targetForSlug( target );
+				if ( ! targetEl && onTargetDisappear && ( ! waitForTarget || this.state.seenTarget ) ) {
```
Comment (scruffian) [inline client/layout/guided-tours/config-elements/step.tsx:202]: Same comment here.
