### PR TITLE
`HelpCenter`: use distinct query key for search

### LINKED ISSUE #74630: HelpCenter crashes Calypso when searching for the same keyword on GetHelp section on /home
### Quick summary

There's currently a bug in the HelpCenter search which crashes Calypso when using for the same keyword which was previously searched for with the help search in the _Get help_ section on `/home`.

The reason for that is because the [`useHelpSearchQuery`](https://github.com/Automattic/wp-calypso/blob/trunk/packages/help-center/src/hooks/use-help-search-query.ts) which is used in Help Center uses the same query key as the [`useHelpSearchQuery`](https://github.com/Automattic/wp-calypso/blob/trunk/client/data/help/use-help-search-query.ts) (it's confusing they both use the same name) which means `react-query` assumes they work on the same (cached) data. However the latter stores an object with keys whereas the help center search query assumes an array. They also operate on different API routes.

A simple fix will be to use a different query key.

There seem to be plans to integrate both searches (tracked in #72392) which indicates to me the suggested fix is enough for now even if we duplicate some data on the client side.

I discovered this bug while working on the `react-query` upgrade to `v4`: https://github.com/Automattic/wp-calypso/pull/74381

Also referencing https://github.com/Automattic/wp-calypso/pull/65805 which, I think, introduced or is related to this regression.

### Steps to reproduce

1. Go to `/home` and use the help search card at the bottom to search for e.g. `post`
2. Open the HelpCenter by clicking on the icon in the top right
3. Search for the exact same keyword

### What you expected to happen

Don't crash but show the actual search results.

### What actually happened

Calypso crashes and shows a blank white screen.

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by flootr**
Fixes #74630

## Proposed Changes

* `HelpCenter`: use distinct query key for help center search results

## Testing Instructions

* Verify #74630 is not reproducable anymore and Calypso doesn't crash when following the steps
* Smoke test help center and make sure it still works as on production

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: packages/help-center/src/hooks/use-help-search-query.ts [hunk 1]
```diff
@@ -16,7 +16,7 @@ export const useHelpSearchQuery = (
 	const queryClient = useQueryClient();
 
 	return useQuery< SearchResult[] >(
-		[ 'help', search ],
+		[ 'help-center-search', search ],
```
Comment (tyxla) [inline packages/help-center/src/hooks/use-help-search-query.ts:19]: For anyone interested, here's the one that was using the same query key:

https://github.com/Automattic/wp-calypso/blob/24bfbebe9da214c118ff24aef93544319154c021/client/data/help/use-help-search-query.ts#L20

**Review by tyxla — APPROVED** [review]
Nice, thanks @flootr 🚀
