### PR TITLE
Avoid broken flow and site re-creation when clicking back from checkout

### LINKED ISSUE #95024: Checkout: Fix browser back
### Details

Context: pdDR7T-1Ed-p2#comment-2320
Related to https://github.com/Automattic/wp-calypso/pull/94859 (Fixes being applied on Start)

## What

- I can’t get back to the signup flow from checkout
- If I click the back button twice, then I end up with a duplicate site.

## How to reproduce

- Go to Signup flow at https://wordpress.com/setup/new-hosted-site
- Add a plan to cart and reach checkout
- Click browser back button

### PR DESCRIPTION
**Pull request by heavyweight**
Fixes https://github.com/Automattic/wp-calypso/issues/95024

## Proposed Changes

* Ensure that the same site is used when clicking back from checkout

## Why are these changes being made?

* Clicking back from checkout breaks the flow
* Clicking back again will create a new site

## Testing Instructions

* Go to Signup flow at `/setup/new-hosted-site`
* Add a plan to cart and reach checkout
* Click browser back button
* Select a plan again
* The same site slug should be used
* Complete the flow ( everything should work)

### CODE REVIEW

File: client/landing/stepper/declarative-flow/new-hosted-site-flow.ts [hunk 1]
```diff
@@ -96,19 +98,19 @@ const hosting: Flow = {
...
-					setSignupCompleteFlowName( flowName );
-
 					// If the product is a free trial, record the trial start event for ad tracking.
 					if ( planCartItem && isFreeHostingTrial( planCartItem?.product_slug ) ) {
 						recordFreeHostingTrialStarted( flowName );
 					}
 
 					if ( providedDependencies.goToCheckout ) {
+						persistSignupDestination( destination );
+						setSignupCompleteSlug( providedDependencies?.siteSlug );
```
Comment (heavyweight) [inline client/landing/stepper/declarative-flow/new-hosted-site-flow.ts:116]: Having this outsite of `providedDependencies.goToCheckout` will set the siteSlug to `undefined` in the session storage, since when clicking back we don't provide dependencies in that case.

File: client/landing/stepper/declarative-flow/new-hosted-site-flow.ts [hunk 2]
```diff
@@ -83,6 +84,7 @@ const hosting: Flow = {
 						return navigate( 'trialAcknowledge' );
 					}
 
+					setSignupCompleteFlowName( flowName );
```
Comment (heavyweight) [inline client/landing/stepper/declarative-flow/new-hosted-site-flow.ts:92]: The complete flow name is reset outside of this flow. We need it set so that new site is not created.

File: client/landing/stepper/declarative-flow/new-hosted-site-flow.ts [hunk 3]
```diff
@@ -96,19 +98,19 @@ const hosting: Flow = {
 				case 'processing': {
 					// Purchasing Business or Commerce plans will trigger an atomic transfer, so go to stepper flow where we wait for it to complete.
 					const destination = addQueryArgs( '/setup/transferring-hosted-site', {
-						siteId: providedDependencies.siteId,
+						siteId: providedDependencies.siteId || getSignupCompleteSlug(),
```
Comment (heavyweight) [inline client/landing/stepper/declarative-flow/new-hosted-site-flow.ts]: The flow requires us to have `siteId` after checkout. Ideally we should retrieve the id of this stored side when we click back from checkout, but this seems ok for me as well. But we need to double check it.

File: client/landing/stepper/declarative-flow/new-hosted-site-flow.ts [hunk 4]
```diff
@@ -120,7 +122,7 @@ const hosting: Flow = {
 						);
 					}
 
-					return window.location.assign( destination );
+					return navigate( 'plans' );
```
Comment (heavyweight) [inline client/landing/stepper/declarative-flow/new-hosted-site-flow.ts:130]: Navigating back from checkout will get us to the processing screen without  `providedDependencies.goToCheckout` we want to go to plans in this case instead of the signup destination

File: client/landing/stepper/declarative-flow/new-hosted-site-flow.ts (hunk 3 above)
Comment (escapemanuele) [reply client/landing/stepper/declarative-flow/new-hosted-site-flow.ts]: When I get back from checkout and click on a plan, I have the `siteId` with a value, is this necessary?
Yeah, right when we go back from checkout, destination will not have a value for siteId, but it will not be persisted as you changed it to persist only if we have `goToCheckout` true.

File: client/landing/stepper/declarative-flow/new-hosted-site-flow.ts (hunk 4 above)
Comment (escapemanuele) [reply client/landing/stepper/declarative-flow/new-hosted-site-flow.ts:130]: This works here because goToCheckout will always be true (apart when back from checkout) as we not present free plans! Just a reminder of this :)

**Review by escapemanuele — APPROVED** [review]
Thanks @heavyweight! The changes solve the flow problem when going back from checkout using the browser back button.

I'd love to find a more general solution to this problem, as this fix works only for this flow that doesn't have free plans. We'll try to think of something.

File: client/landing/stepper/declarative-flow/new-hosted-site-flow.ts (hunk 4 above)
Comment (heavyweight) [reply client/landing/stepper/declarative-flow/new-hosted-site-flow.ts:130]: Not entirely true since when create site submits when we reuse a slug we loose the id
https://github.com/Automattic/wp-calypso/blob/5379444943df9c0516f1b6dae16d0ee36485df98/client/landing/stepper/declarative-flow/internals/steps-repository/create-site/index.tsx#L203

**Comment by escapemanuele** [comment]
I find it all working much better now.



What we should try to look at is the jump that happens when reaching plans, @heavyweight

**Review by escapemanuele — APPROVED** [review]
But I don't believe the jump is related to this PR (also because prod is broken and it's difficult to say if we introduced this).

Approving this, great change 👍
