### PR TITLE
Plugins: Improve messaging for Jetpack Scan detected errors

### LINKED ISSUE #58942: Improve messaging for plugin upload failures that are due to Jetpack Scan
### Quick summary

For plugin uploads that fail due to Jetpack Scan's vulnerabilities check, we could improve the messaging on the Calypso notification. At this time, it says "Upload problem: Invalid plugin"

### Steps to reproduce

- Get a plugin file that fails Jetpack Scan's checks. (related conversation here: p1638946968328900-slack-C029JEQRVRT)
- Upload at https://wordpress.com/plugins/upload

### What you expected to happen

Messaging could be improved to actually describe what happened.

### What actually happened

Message reads "Upload problem: Invalid plugin" at the moment: 

image

### Context

Slack chat: p1638946968328900-slack-C029JEQRVRT

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

No.

### Browser, operating system and other notes

All devices.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by epeicher**
When uploading a plugin, it is scanned using Jetpack. The previous message
was unclear, so it has been improved to a more explicit message.

Depends on D74922-code

#### Changes proposed in this Pull Request

* Change the error message when Jetpack Scan reports a failure from
  > Upload problem: Invalid plugin. 

  to

  > The uploaded file is identified as malicious.

Additionally, the displayed page offers a workaround that reads:

> This plugin is identified as malicious. If you want to install the plugin, please continue by uploading the plugin again from WP Admin.

|Before | After|
|-------|------|
|image|image|

Pinging to @emmnyc85 and @cavalierlife to check if the suggested message is fine 🙂 

#### Testing instructions

* Apply D74922-code
* In an Atomic site, go to  https://wordpress.com/plugins/upload
* Upload a plugin that fails, for example, this one pdh6GB-6h-p2#comment-698 
* The notification message should display `The uploaded file is identified as malicious.` and the displayed page should contain the message `This plugin is identified as malicious. If you want to install the plugin, please continue by uploading the plugin again from WP Admin.`. That page will contain two action buttons:
  *  `Back` that will navigate to previous page
  * `Continue` that will re-direct to the upload plugin from the `wp-admin` page.

Fixes #58942

### CODE REVIEW

**Review by cpapazoglou — CHANGES_REQUESTED** [review]
Tested this and works as advertised. 

Can we also do the extra mile here by changing the error message in the main content and providing the user an alternative for uploading the plugin through WP Admin?

Prior art here

https://github.com/Automattic/wp-calypso/blob/08c583c6287e59734ad43ec1fc9692ed5cf73bde/client/my-sites/marketplace/pages/marketplace-plugin-install/index.tsx#L336-L350

File: client/my-sites/marketplace/pages/marketplace-plugin-install/index.tsx [hunk 1]
```diff
@@ -348,6 +349,21 @@ const MarketplacePluginInstall = ( {
 				/>
 			);
 		}
+		if ( pluginMalicious ) {
+			return (
+				<EmptyContent
+					illustration="/calypso/images/illustrations/error.svg"
+					title={ null }
+					line={ translate(
+						'This plugin is identified as malicious. If you want to install the plugin, please continue by uploading the plugin again from WP Admin.'
```
Comment (cpapazoglou) [inline client/my-sites/marketplace/pages/marketplace-plugin-install/index.tsx]:
```suggestion
						'This plugin is identified as malicious. If you still insist to install the plugin, please continue by uploading the plugin again from WP Admin.'
```

**Review by cpapazoglou — APPROVED** [review]
Thanks for addressing the feedback! That's a great improvement in UX!

Just left a minor comment regarding copy.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7141787

Thank you @epeicher for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7141787).
