### PR TITLE
Fix the search and replace to correctly insert post content into template content

### LINKED ISSUE #34243: Full Site Editing: Post Content Disappears on Second Edit
On subsequent page editor, post_content fails to load in the editor:

To reproduce:
- Install the FSE plugin, and activate it
- Edit a page
- Note that the header and footer template appears, within the page editor.
- Make some post content changes and save
- Verify that the published view reflects this.
- Edit the page again (with a refresh). The post_content is missing in the block editor.

### PR DESCRIPTION
**Pull request by glendaviesnz**
#### Changes proposed in this Pull Request

* Modify the search and replace syntax to correctly insert post content into template

#### Testing instructions
- Check out branch and Install the FSE plugin, and activate it on local gutenberg dev
- Edit a page
- Note that the header and footer template appears, within the page editor.
- Note that the post content also appears between the header and footer.
- Edit the page again (with a refresh) and check that the post content still appears
Screen Shot 2019-06-26 at 12 14 59 PM

Related to  #34243 - this is the initial fix, which will be followed by a more robust approach

### CODE REVIEW

**Comment by glendaviesnz** [comment]
looks like this change here https://github.com/Automattic/wp-calypso/pull/33885/files#diff-d4f340da4f72898d36eb7f2ca6c1e127R22 might have broken it by changing the site content comment wrapper from `<!-- wp:a8c/post-content -->` to `<!-- wp:a8c/post-content {"align":"full"} /-->`

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php [hunk 1]
```diff
@@ -473,7 +473,7 @@ public function merge_template_and_post( $post ) {
 		}
 
 		$wrapped_post_content = sprintf( '<!-- wp:a8c/post-content -->%s<!-- /wp:a8c/post-content -->', $post->post_content );
-		$post->post_content   = str_replace( '<!-- wp:a8c/post-content /-->', $wrapped_post_content, $template->get_template_content() );
+		$post->post_content   = str_replace( '<!-- wp:a8c/post-content {"align":"full"} /-->', $wrapped_post_content, $template->get_template_content() );
```
Comment (gwwar) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php]: Can we make this a bit more robust? We should have a server side block parser available from Gutenberg.

If the above is too expensive/difficult alternatively I'd recommend doing a partial match on `wp:a8c/post-content`, then matching the full html comment.
