### PR TITLE
Comments: Remove overflow hidden from CommentDetail reply box

### LINKED ISSUE #15576: Comments: scrollbar and resize handle missing
screen shot 2017-06-27 at 2 05 11 pm

When the max height is reached, there were no scrollbars visible, and scrolling with the mouse wheel doesn't work.

Also, the resize handle in the bottom right is missing, so I can't adjust the hight of the textarea. 

_See: notifications_

Safari 10.1.1

### PR DESCRIPTION
**Pull request by Copons**
Fixes #15576

Refactor of the textarea expansion logic to take care of:
- The resize handle.
- The scrollbar.
- The blue border.
- The correct Send button position.

jun-30-2017 13-25-23
jun-30-2017 13-26-19

### Glitches

There are extremely minor glitches that I believe do not really worsen the UX.
Still, here they are:

- The `textarea` max height is set at 10 lines. This means that the scrollbar shows up on line 10.
Somehow, a scrollbar appears briefly during the transition between line 9 and 10. I believe it's caused by the fact that the `overflow: auto` is applied immediately, but the actual height transitions for a little bit.
Note: there's no transition on the `textarea`; I'm assuming it's the one that handles the `CommentDetail` expand/collapse.

- When the scrollbar appears, the Send button is "displaced" a little bit (from `right: 18px` to `right: 24px`). Once displaced, though, it remains at `24px` even if the scrollbar disappears.
This is caused by the fact that the `textarea` internal height (`scrollHeight`) only increases but never decreases (i.e. it increases when you add a line, but when you remove the line it remains at its maximum value).
This is why previously we employed a workaround consisting in mirroring the `textarea` with an invisible `<pre>` that, instead, updates its `scrollHeight` "downwards" as well.
I've removed this mirror because it doesn't work well with the resize handle, so we don't have any easy way to know when the height decreases.

- The `textarea` cannot be resized below its `min-height`.
For the reasons explained before, the `min-height` is only updated "upwards" (and until a max value of 10 lines).
So, for example, once the `textarea` is filled with X lines of content, it can only be extended, but not shrank below X lines.

### CODE REVIEW

**Comment by Copons** [comment]
@drw158 If this isn't a dealbreaker for our ongoing testing, I can try to sort the resize out here once and for all.

**Comment by drw158** [comment]
No problem, this PR is not holding up user testing. Thanks!

**Comment by drw158** [comment]
I'm handling the missing blue border in #15669

**Comment by Copons** [comment]
@drw158 I've updated the PR with plenty of changes.
In the new description there is a list of things, some of those overlap #15669.

**Comment by Copons** [comment]
@drw158 Not at all, just beware, it's a bit fragile! 🙂

File: client/blocks/comment-detail/comment-detail-reply.jsx [hunk 1]
```diff
@@ -13,15 +13,42 @@ import { get } from 'lodash';
...
+		textareaMinHeight: TEXTAREA_MIN_HEIGHT_COLLAPSED,
 	};
 
-	handleTextChange = event => this.setState( { commentText: event.target.value } );
+	bindTextareaRef = textarea => {
+		this.textarea = textarea;
+	}
+
+	calculateTextareaMinHeight = () => {
+		const textareaScrollHeight = this.textarea.scrollHeight;
```
Comment (gwwar) [inline client/blocks/comment-detail/comment-detail-reply.jsx]: Just note that whenever we query an element for dimensions like `scrollHeight` that actually triggers a layout/reflow of the page. So just keep in mind to use this sparingly.

File: client/blocks/comment-detail/comment-detail-reply.jsx [hunk 2]
```diff
@@ -13,15 +13,42 @@ import { get } from 'lodash';
...
+		const textareaMinHeight = Math.min( TEXTAREA_MAX_HEIGHT, textareaScrollHeight + TEXTAREA_VERTICAL_BORDER );
```
Comment (gwwar) [inline client/blocks/comment-detail/comment-detail-reply.jsx]: Is it possible to set a fixed min-height, max-height, and then let the js update the height attribute?

**Comment by gwwar** [comment]
Overall this looks like this does the trick @Copons! I did notice the resize handles do a lag a bit when manually dragging.

Did you happen to have a gif of how a native text area behaves in this space? I'm curious if we can simplify this down a bit.

**Comment by Copons** [comment]
@gwwar 
> I did notice the resize handles do a lag a bit when manually dragging.

It got fixed by adding a `transition: min-height 0.15s linear` to the textarea, which I now see it's missing here. :/

File: client/blocks/comment-detail/comment-detail-reply.jsx (hunk 2 above)
Comment (Copons) [inline client/blocks/comment-detail/comment-detail-reply.jsx]: Awesome suggestion - even though maybe it's not what you meant. 😄 
By replacing `min-height` with `height` I basically "unlocked" the resize to go lower than the current textarea height set via JS/CSS.

FYI: I can't set a fixed `max-height` because it blocks the manual resize.
The logic there is that the textarea can't be taller than `TEXTAREA_MAX_HEIGHT` _when resizing automatically_.
Also, that constant is needed to toggle the overflow/scrollbar (something that doesn't happen reliably in CSS alone).
