### PR TITLE
Focused Launch success view: fix CTA rendering conditions

### LINKED ISSUE #51780: Focused Launch: show CTA buttons after launch in wp-admin
### Steps to reproduce the behavior

1. Go to /new and create a site
2. Go to wp-admin to edit a page or a post
3. Click Launch button in top bar
4. Complete the flow by picking Free plan and existing subdomain to launch your site for free

#### What I expected to happen
Success message to be displayed with CTA button to continue editing or return to Customer Home

#### What actually happened
CTA buttons weren't there so I had no way to go back or advance. 

### Context
Also mentioned in https://github.com/Automattic/wp-calypso/pull/51324#issuecomment-813880256

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Hitting a dead-end after launching a site is definitely hurting the UX.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
image

### PR DESCRIPTION
**Pull request by alshakero**
#### Changes proposed in this Pull Request

This PR readjusts the conditions we need to show the CTAs in success view of focused launch.

#### Testing instructions

1. Create a free unlaunched site using `/new`.
2. Let's say it's called http://test123.wordpress.com.
3. Sandbox this site.
4. In Calypso, run `yarn start`, in `apps/editing-toolkit` run `yarn dev --sync`.

### Calypso - free plan and domain

5. Go to http://calypso.localhost:3000/page/test123.wordpress.com/5.
6. Pick a free plan and a free domain.
7. Launch. You should see "Continue editing" button.

### Calypso - premium plan
(you need a new site)

5. Go to http://calypso.localhost:3000/page/test123.wordpress.com/5.
6. Click Launch.
7. Pick a premium plan and a free domain.
8. Launch. You should be taken to checkout without seeing success view. Checkout Modal should open over the editor and if closed, focused launch summary should be displayed.

### wp-admin - free plan
(you need a new site)

5. Go to http://test123.wordpress.com/wp-admin/post-new.php.
6. Click Launch.
7. Pick a free plan and a free domain.
8. Launch. Success view should have CTA buttons.

### wp-admin - premium plan
(you need a new site)

5. Go to http://test123.wordpress.com/wp-admin/post-new.php.
6. Click Launch.
7. Pick a premium plan and a free domain.
8. Launch. Success view shouldn't have any buttons.

### wp-admin or calypso - Ecommerce
(you need a new site)

5. Go to http://test123.wordpress.com/wp-admin/post-new.php.
6. Click Launch.
7. Pick an ecommerce plan and a free domain.
8. Launch. Success view shouldn't have any buttons.

Fixes https://github.com/Automattic/wp-calypso/issues/51780

### CODE REVIEW

File: packages/data-stores/src/launch/selectors.ts [hunk 1]
```diff
@@ -50,7 +50,7 @@ export const isSelectedPlanPaid = ( state: State ): boolean =>
  *
  * @param state State
  */
-export const hasSelectedDomain = ( state: State ): boolean =>
+export const hasSelectedDomainOrSubdomain = ( state: State ): boolean =>
```
Comment (ciampo) [inline packages/data-stores/src/launch/selectors.ts:53]: `packages/launch/src/focused-launch/index.tsx` needs refactoring too, otherwise it breaks the build

Comment (razvanpapadopol) [reply packages/data-stores/src/launch/selectors.ts:53]: Oops, sorry! I've forgotten to commit the second part of the refactoring 🙈
Fixed now. The remaining failing e2e is unrelated.

File: packages/data-stores/src/launch/selectors.ts [hunk 2]
```diff
@@ -22,7 +22,7 @@ export const hasPaidDomain = ( state: State ): boolean => {
 	if ( ! state.domain ) {
 		return false;
 	}
-	return ! state.domain.is_free;
+	return ! state.domain.is_free; // @TODO: check if we are ever storing a paid domain
```
Comment (ciampo) [inline packages/data-stores/src/launch/selectors.ts:25]: Hey @razvanpapadopol, is this `@TODO` still applicable? If so, should it be solved in this PR or should we open a follow-up issue?

Comment (razvanpapadopol) [reply packages/data-stores/src/launch/selectors.ts:25]: It's still applicable because this check for free domain is not needed with current Launch logic. If the user selects the sub-domain (free domain), we don't store it but we unset the domain selection. See https://github.com/Automattic/wp-calypso/blob/trunk/packages/launch/src/hooks/use-domain-selection.ts#L117

Comment (ciampo) [reply packages/data-stores/src/launch/selectors.ts:25]: Tracked separately in https://github.com/Automattic/wp-calypso/issues/51860

File: packages/launch/src/focused-launch/summary/index.tsx [hunk 3]
```diff
@@ -632,7 +637,7 @@ const Summary: React.FunctionComponent = () => {
 		<PlanStep
 			highlighted={ isPlansStepHighlighted }
 			hasPaidPlan={ hasPaidPlan }
-			selectedPaidDomain={ selectedDomain && ! selectedDomain.is_free }
+			selectedPaidDomain={ selectedDomain && ! selectedDomain.is_free } // @TODO: check if selectedDomain can ever be free
```
Comment (ciampo) [inline packages/launch/src/focused-launch/summary/index.tsx:640]: Note for https://github.com/Automattic/wp-calypso/issues/51860

File: packages/launch/src/focused-launch/success/index.tsx [hunk 4]
```diff
@@ -56,9 +59,13 @@ const Success: React.FunctionComponent = () => {
...
-	// if the user has an ecommerce plan or they're using focused launch from wp-admin
-	// they will be automatically redirected to /checkout, in which case the CTAs are not needed
-	const willUserBeRedirectedAutomatically = useWillRedirectAfterSuccess();
+	// Show CTA buttons needed to dismiss the success view only if the user is not going to be redirected to /checkout after launch.
+	// When we display the CTA buttons?
+	// 1. All the time for the free flow (no selected custom domain or paid plan).
+	// 2. If the selected plan isn't Ecommerce and we are in the iframed editor (conditions when we display Checkout Modal).
+	const isEcommerce = useHasEcommercePlan();
+	const isFreeFlow = ! selectedDomain && ! isSelectedPlanPaid;
+	const shouldShowCTAs = isFreeFlow || ( ! isEcommerce && isInIframe );
```
Comment (ciampo) [inline packages/launch/src/focused-launch/success/index.tsx:68]: Just noting that the same change in logic could have been achieved without refactoring the rest of the files in this PR and the `useWillRedirectAfterSuccess` hook, which in my opinion was a nice abstraction over the implementation details of the in-editor checkout modal vs redirection.

```suggestion
	const shouldShowCTAs = isFreeFlow || ! willUserBeRedirectedAutomatically;
```

Comment (alshakero) [reply packages/launch/src/focused-launch/success/index.tsx:68]: I didn't like that hook much because:

1) It's doesn't really determine whether we'll redirect. As you can see here we need to check whether we're in free flow too.

2) If we move the free flow check inside the hook, then we won't be able to use the hook [here](https://github.com/Automattic/wp-calypso/blob/38c37bbfe35b8c741c4e346637987ddc0fb3ab59/packages/launch/src/hooks/use-cart.ts#L80). Making it an abstraction that is used once.

Comment (ciampo) [reply packages/launch/src/focused-launch/success/index.tsx:68]: > It's doesn't really determine whether we'll redirect. As you can see here we need to check whether we're in free flow too.

I think that the hook determined correctly whether we'll redirect. Here we're checking for the free flow in order to show/hide CTAs (it's a different check which _also_ relies on knowing if the user will be redirected

> If we move the free flow check inside the hook, then we won't be able to use the hook here. Making it an abstraction that is used once.

We wouldn't need to move the free flow check inside the hook, because that free flow check is not needed to know if the page will be redirected — it is only needed to know if we should show the CTA buttons.

**Review by ciampo — APPROVED** [review]
Rebased, gave another look, opened follow-up issues.

Tests well as per instructions.

File: packages/launch/src/focused-launch/success/index.tsx (hunk 4 above)
Comment (alshakero) [reply packages/launch/src/focused-launch/success/index.tsx:68]: > I think that the hook determined correctly whether we'll redirect.

I don't think this is true. The hook would return `true` for the free plan in wp-admin (`! isInIframe || ! ecommercePlan`), even though we don't redirect in this case. Right?

Comment (ciampo) [reply packages/launch/src/focused-launch/success/index.tsx:68]: Oh, now I get your previous reply too — you're correct indeed, we'd need to add the free plan check too.
