### PR TITLE
Fix/spt sidebar open by default

### LINKED ISSUE #37781: Page Layout option in the sidebar should default to "open"
Instead of being closed by default, why not expand the "Page Layout" option by default? This way it has more visibility if users need to make changes to it.

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
#### Changes proposed in this Pull Request

* Adds a check to force the SPT "Page Layout" Sidebar plugin to open by default.

I will add a followup PR to core later this week to add an `initialOpen` property to the `PluginDocumentSettingPanel` component.  This component uses a `PanelBody` component, and the `PanelBody` component has this prop available and designed into its structure so it seems to make sense that the `PluginDocumentSettingPanel` should be updated to allow for this optional prop to pass through to the `PanelBody`.

#### Testing instructions

Tested Locally and on Sandbox
* Run this PR.
* Navigate to the page editor.
* Verify that the "Page Layouts" sidebar plugin is open.
* Close it.
* Reload or navigate back to the page editor again.
* Verify that it is open by default once more.

Fixes #37781

### CODE REVIEW

**Comment by apeatling** [comment]
I did this:

* Went to my pages, selected to edit my homepage
* Saw the panel was open by default, great
* Hit < Pages
* Clicked to the edit the home page again
* The panel was closed. :(

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js [hunk 1]
```diff
@@ -415,3 +420,14 @@ registerPlugin( 'page-templates-sidebar', {
...
+// Make sidebar plugin open by default.
+if (
+	! wpSelect( 'core/edit-post' ).isEditorPanelOpened(
+		'page-templates-sidebar/Template Modal Opener'
+	)
+) {
+	wpDispatch( 'core/edit-post' ).toggleEditorPanelOpened(
+		'page-templates-sidebar/Template Modal Opener'
+	);
+}
```
Comment (noahtallen) [inline apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: I didn't experience the thing Andy did locally, but I think we could solve the problem by making it a bit more robust. I think it's possible that at this point in execution, the state hasn't fully loaded. What about this? Alternatively, maybe it would work on `domReady`

```suggestion
import { subscribe } from '@wordpress/data';

const unsubscribe = subscribe( () => {
  if (
	  ! wpSelect( 'core/edit-post' ).isEditorPanelOpened(
		'page-templates-sidebar/Template Modal Opener'
	  )
  ) {
	  wpDispatch( 'core/edit-post' ).toggleEditorPanelOpened(
		'page-templates-sidebar/Template Modal Opener'
	  );
	  // Only open it once:
	  unsubscribe();
  }
} );
```

Comment (Copons) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: I agree with @noahtallen.
Also, we have used the `subscribe` trick in other occasions in FSE, so it all sounds good to me. 👍

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js [hunk 2]
```diff
@@ -9,7 +9,12 @@ import { __, sprintf } from '@wordpress/i18n';
 import { compose } from '@wordpress/compose';
 import { Button, Modal, Spinner, IconButton } from '@wordpress/components';
 import { registerPlugin } from '@wordpress/plugins';
-import { withDispatch, withSelect } from '@wordpress/data';
+import {
+	withDispatch,
+	withSelect,
+	select as wpSelect,
+	dispatch as wpDispatch,
```
Comment (Copons) [inline apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: At a quick check, I don't see any conflicts with `select` and `dispatch`. Any reasons why we're renaming them?

Comment (Addison-Stavlo) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: To make the linter happy.  LOL...  when I had them as just `select` and `dispatch` the linter was unhappy with the `select`s and `dispatch`s that were already in the connect/mapState functions in use.  So instead of committing with --no-verify or disabling the linter for those lines I figured I would just rename them.

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js (hunk 1 above)
Comment (Addison-Stavlo) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: Great recommendation, thanks!  I updated it to use the subscribe funciton.

Comment (Addison-Stavlo) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: It works great, but it is not what I expected from `subscribe`.  That is, `subscribe` is documented as running whenever the state changes.  But when we open or close the modal, isn't that updating the state?  If that was the case I would expect this check to run every time we minimize it in the sidebar, which would force it to open again?  But with testing that is not how it works, so I am a little confused on that.

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js (hunk 2 above)
Comment (Copons) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: Oh wow, my search skills really screwed up there!
I have no idea why I didn't see the other `select`s and `dispatch`s... I'm kinda wondering if I was looking into a different file... 😅

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js (hunk 1 above)
Comment (Copons) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: The `unsubscribe()` that is called when the panel is opened is exactly the reason why it doesn't happen!

Thinking in normal JS terms, `subscribe/unsubscribe` are similar to `setInterval/clearInterval`:
```js
const waitForOpenPanel = setInterval( () => {
  if ( isPanelOpen ) {
    clearInterval( waitForOpenPanel );
  }
} );
```

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js [hunk 3]
```diff
@@ -415,3 +421,18 @@ registerPlugin( 'page-templates-sidebar', {
...
+	if (
+		! wpSelect( 'core/edit-post' ).isEditorPanelOpened(
+			'page-templates-sidebar/Template Modal Opener'
+		)
+	) {
+		wpDispatch( 'core/edit-post' ).toggleEditorPanelOpened(
+			'page-templates-sidebar/Template Modal Opener'
+		);
+
+		unsubscribe();
```
Comment (noahtallen) [inline apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: One correction from my original comment. We should put `unsubscribe` at the end of the callback, not inside the if statement. Otherwise, if the editor panel was opened by default, if you click to close it, it won't close the first time because this is still listening!

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js (hunk 1 above)
Comment (Addison-Stavlo) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: ooohhhh... I see.   So in this case we are unsubscribing as soon as it runs, but we are subscribing in the first place to ensure that state has been fully loaded and everything is established before checking and dispatching to it?

Comment (noahtallen) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: right on!
