### PR TITLE
Monetize: Add tracking fot the "Add a new payment plan" button click

### LINKED ISSUE #90496: Jetpack Cloud: Missing tracking in /monetize
### Impacted plugin

Jetpack

### Quick summary

While building a funnel to track how many people click the Paid Newsletter CTA inside Newsletter settings I realized that we aren't tracking this button:

Screenshot 2024-05-09 at 13 07 54

### Steps to reproduce

1. Navigate to https://cloud.jetpack.com/monetize/payments/:site
2. Check if you can trigger an event when clicking `Add a new payment plan`
3. Creating a plan doesn't have any track either

### A clear and concise description of what you expected to happen.

It should have a tracks event like the Stripe button (`calypso_memberships_stripe_connect_click`).
Perhaps `calypso_membership_add_plan_click`?

And something similar for the user interactions happening inside the modal, especially when a user creates a new plan. This way, we'll be able to measure how many people open the modal and how many end up creating a new plan:
Screenshot 2024-05-09 at 13 11 36

### What actually happened

_No response_

### Impact

All

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by pkuliga**
Fixes https://github.com/Automattic/wp-calypso/issues/90496
Part of https://github.com/Automattic/jetpack/issues/36958

## Proposed Changes

It adds tracking to the "Add a new payment plan" button click so we can create a funnel that allows us to check how many users access Cloud > Monetize and create and save a plan.

## Testing Instructions

Code review should be enough.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/my-sites/earn/memberships/products-list.tsx [hunk 1]
```diff
@@ -85,6 +85,11 @@ function ProductsList() {
 		);
 	}
 
+	function onAddNewPaymentPlanButtonClick() {
+		dispatch( recordTracksEvent( 'calypso_memberships_add_payment_plan_click' ) );
```
Comment (lezama) [inline client/my-sites/earn/memberships/products-list.tsx:89]: I have seen ` recordTracksEvent(` calls without "dispatch", Is "dispatching" here the recommended Calypso way?

**Review by lezama — APPROVED** [review]

File: client/my-sites/earn/memberships/products-list.tsx (hunk 1 above)
Comment (pkuliga) [reply client/my-sites/earn/memberships/products-list.tsx:89]: Not sure, it was just a copy&paste from:
https://github.com/Automattic/wp-calypso/blob/2616b8da2c63ca8b63582b9a3a7424d4429aecb5/client/my-sites/earn/memberships/section.tsx#L96
