### PR TITLE
Framework: put the old notices in a different "namespace"

### LINKED ISSUE #2946: Framework: error and success notices don't like to co-exist
While testing #1916 I've encountered this error in the console:
```
Warning: flattenChildren(...): Encountered two children with the same key, `.1:$notice-0`. Child keys must be unique; when two children share a key, only the first child will be used.
```
Steps to reproduce:
* visit `/domains/manage/:site/dns/:domain`
* add a new record, a success notice will be displayed (don't dismiss it)
* trigger an error (I went offline using the Developer Tools and tried adding a new record)

It seems the success and error notices conflict with each other.
The code triggering this behaviour is in [`dns-add-new.jsx`](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/upgrades/domain-management/dns/dns-add-new.jsx#L95-L101). Nothing special - just calling `notices.success` and `notices.error` with a string. Note that I've observed the same behaviour with a mix of "reduxified" and normal notices (as seen in #1916).

### PR DESCRIPTION
**Pull request by klimeryk**
If we show old and new (from redux store) notices, we'll get conflicting keys (like `notice-0`), which are used by React during reder passes. This will trigger an error in the console and, more importantly, prevent one of the conflicting notices from showing.
This change changes the old notices' key prefix to a different one than for the new, reduxified ones, thus preventing the conflict.

Fixes #2946 

/cc @artpi

### CODE REVIEW

**Comment by artpi** [comment]
How did I not catch that? Thank you @klimeryk !

**Comment by artpi** [comment]
Code looks good, I'm going to fire up to test

File: client/components/global-notices/index.jsx [hunk 1]
```diff
@@ -54,7 +54,7 @@ const NoticesList = React.createClass( {
 		let noticesList = noticesRaw.map( function( notice, index ) {
 				return (
 					<Notice
-						key={ 'notice-' + index }
+						key={ 'notice-old-' + index }
```
Comment (gwwar) [inline client/components/global-notices/index.jsx]: Alternatively, the key for the notice below can be updated to:
```javascript
key={ `notice-${ noticesRaw.length + index }` }
```

**Comment by gwwar** [comment]
Feel free to :shipit: with either solution.

**Comment by klimeryk** [comment]
Thanks for the code reviews, @gwwar :bow:
I thought about your solution, but went with the different prefix for the key - it seems simpler, and shows the slightly different handling of old `notices` and global-notices better, IMHO. In the end, React cares that it's all unique. And hopefully, the old notices won't live too long now that we've welcomed our new master and overlord, Redux :wink:
