### PR TITLE
Checkout: fix annual plan upsell feature list

### LINKED ISSUE #54761: Checkout: clear up discount message for domain redemptions
When a domain is in redemption, we charge a late renewal fee that's inclusive of the domain cost. This results in a $0 domain registration line item, which causes the "Discount for first year" and "{domain} - free for one year" messages to be shown in Checkout. 

Screen Shot 2021-07-21 at 9 43 55 AM

Both of these feel incorrect. We should remove the sidebar message, and update the line item to mention that it includes the domain cost.

### PR DESCRIPTION
**Pull request by michaeldcain**
This aims to clear up the Checkout sidebar feature list for carts with monthly plans or different domain bundling situations. It pulls the `x {feature} - annual plans only` pattern out into a separate list of items. It also ties the `mydomain.com - free for one year` messaging to whether or not a domain is bundled in the cart.

Replaces: #54764
Fixes: #54761

| Before      | After |
| ----------- | ----------- |
| Screen Shot 2022-01-14 at 11 22 19 AM | Screen Shot 2022-01-14 at 11 22 50 AM |

**To test:**
- Add a monthly plan to your cart and visit Checkout
- Verify that the sidebar has an "Included with an annual plan" callout (a monthly Personal plan _should not_ show live chat with the annual plan)
- Verify that clicking the title or link of the callout changes the plan to the equivalent yearly plan
- Leave Checkout, add a domain to your cart, and return to Checkout
- Verify that in the sidebar, the domain has a "free for one year" message when bundled with a yearly plan
- Switch to the monthly variant
- Verify that in the sidebar, the domain no longer shows a "free for one year message"
- Remove the plan from the cart
- Verify that the upsell is no longer shown

### CODE REVIEW

File: client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.tsx [hunk 1]
```diff
@@ -332,6 +309,39 @@ function CheckoutSummaryPlanFeatures() {
...
+	const productSlug = props.plan?.product_slug;
+
+	if ( ! productSlug || ! isWpComPlan( productSlug ) ) {
+		return null;
+	}
+
+	return (
+		<CheckoutSummaryFeatures>
+			<CheckoutSummaryFeaturesTitle>
+				{ translate( 'Included with an annual plan' ) }
```
Comment (a8ci18n) [inline client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.tsx]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **24** times:
`translate( 'Included with annual plans' )` *ES Score: 9*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/fix/checkout-domain-credit-feature)

File: client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.tsx [hunk 2]
```diff
@@ -332,6 +308,43 @@ function CheckoutSummaryPlanFeatures() {
...
+		return null;
+	}
+
+	return (
+		<CheckoutSummaryFeaturesUpsell>
+			<CheckoutSummaryFeaturesTitle>
+				<SwitchToAnnualPlan
+					plan={ props.plan }
+					onChangePlanLength={ props.onChangePlanLength }
+					linkText={ translate( 'Included with an annual plan' ) }
```
Comment (a8ci18n) [inline client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.tsx:328]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **24** times:
`translate( 'Included with annual plans' )` *ES Score: 9*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/fix/checkout-domain-credit-feature)

**Review by nbloomf — APPROVED** [review]
Looks good and works as expected!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7084796

Thank you @michaeldcain for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7084796).
