### PR TITLE
Help Center: open support links from articles in HC

### LINKED ISSUE #93086: Help Center: All URLs of support docs should open in Help Center
### Quick summary

_No response_

### Steps to reproduce

1. Open Help Center and click on a support doc. It'll open right there in the Help Center area. 
2. Click on one of the in-line URLs. It'll open in another tab.

https://github.com/user-attachments/assets/e448c8fc-d13c-4285-b3d6-7fbbdb0aef47

### What you expected to happen

The expectation was to keep seeing all documentation in Help Center.

### What actually happened

Instead, URLs opened in another tab.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by arcangelini**
Fixes https://github.com/Automattic/dotcom-forge/issues/8291
Fixes https://github.com/Automattic/wp-calypso/issues/93086
Fixes https://github.com/Automattic/dotcom-forge/issues/8199

## Proposed Changes

* Replaces the `usePostByKey` hook with `usePostByUrl` which accepts URL's rather than post ID and blog ID.
* Add a new fetch to retrieve the post object using the URL. (new endpoint here - D155970-code and https://github.com/Automattic/jetpack/pull/38445)
* Adjusted the endpoint to handle all language links as well (fix is here - D156440-code)
* Adds a new hook `useContentFilter` that filters the content on render to add run an "action" to any element that matches the "pattern".
* Fix jump-to links in the table of contents using the new useContentFilter.
* Fix `initialRoute` setting. Now changing the `initialRoute` navigates to the location.
* Updates the tracks events to better reflect the user interaction.
* ~Refactors the article component.~ (moved to #92866)

## Why are these changes being made?

https://github.com/user-attachments/assets/3c166174-42ea-459a-bff0-ce5a60dfe480

The main cause of this PR is to add the ability for support guide links that are within support guides to be opened in the Help Center rather than navigating away to a new tab. This also addresses the broken ToC jump-to-links.

### ~Needs to be tested alongside D155970-code~ - DEPLOYED

1. Pull branch or open Calypso Live
2. Navigate to Help Center and start opening articles.
3. Click on ToC links and other links to /support in the articles.
4. Navigate back
5. Open links from inlinehelp that go directly to Articles.

### CODE REVIEW

**Comment by escapemanuele** [comment]
Thank you @arcangelini for following my ideas and opening a new PR for the refactoring! I'll look at it now 👍

File: packages/help-center/src/hooks/use-post-by-key.ts [hunk 1]
```diff
@@ -20,10 +20,50 @@ function fetchForKey( postKey: ReturnType< typeof getPostKey > ) {
...
+			return {
+				content: data.content,
+				title: data.title,
+				link: data.URL,
+				postId: data.ID,
+				blogId: data.site_ID,
+				slug: data.slug,
+				articleUrl: data.URL,
+			};
+		},
```
Comment (alshakero) [inline packages/help-center/src/hooks/use-post-by-key.ts]: We should make a new query because now its types are wonky, and it does not really fetch by key. It's possible that we don't need searching by key at all.

File: packages/help-center/src/hooks/use-article-content-click.tsx [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+				navigate( `/post?link=${ href }` );
+			},
+		},
+
+		/**
+		 * Fix jump-to-section links.
+		 */
+		{
+			condition: ( target: HTMLElement ) =>
+				target.tagName === 'A' && target.getAttribute( 'href' )?.startsWith( '#' ),
```
Comment (alshakero) [inline packages/help-center/src/hooks/use-article-content-click.tsx]: Maybe `matches` would be cleaner?
```suggestion
				target.matches( 'a[href^=#]' )
```

File: packages/help-center/src/hooks/use-article-content-click.tsx [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+					event.preventDefault();
+					const href = target.getAttribute( 'href' );
+					node?.querySelector( href as string )?.scrollIntoView();
+				}
+			},
+		},
+	];
+
+	useEffect( () => {
+		node?.addEventListener( 'click', ( event: Event ) => {
```
Comment (alshakero) [inline packages/help-center/src/hooks/use-article-content-click.tsx]: Making this change would probably free you from all the casting below. 

```suggestion
		node?.addEventListener( 'click', ( event: MouseEvent< HTMLElement >  ) => {
```

**Review by alshakero — COMMENTED** [review]
Great work. Left some comments.

File: packages/help-center/src/hooks/use-post-by-key.ts (hunk 1 above)
Comment (arcangelini) [reply packages/help-center/src/hooks/use-post-by-key.ts]: My desire was to not mess with the current hook too much as to require updating it and possibly other places people are navigating to articles. With that being said it is a bit challenging to make a hook that accepts either the key or the url and stores it in a way thats not redundant ie post cache by url and cached by key. I also was really confused by what the need for `getPostKey()` and all the alternative stuff that seems to be tied into this.

I think in an ideal world we would scrap the need for post and blog id's and just use the URL, because it is much simpler and requires less work. But maybe that is too big of a jump to start with to eliminate it completely and adjust all the places calling the initialRoute to a post? Do you have any thoughts on how you would structure this @alshakero ?

File: packages/help-center/src/hooks/use-article-content-click.tsx (hunk 3 above)
Comment (arcangelini) [reply packages/help-center/src/hooks/use-article-content-click.tsx]: Did you try that in VSCODE? I was stuck in a weird typing hell when I tried to use that and I couldn't get out of it. The types I have now were the only way I could format it to appease TS.

File: packages/help-center/src/hooks/use-post-by-key.ts (hunk 1 above)
Comment (alshakero) [reply packages/help-center/src/hooks/use-post-by-key.ts]: I think it's alright to switch to URLs only. This hook is used only in the Help Center. I built this hook a few weeks ago [here](https://github.com/Automattic/wp-calypso/pull/92008), don't worry about nuking it.

File: packages/help-center/src/hooks/use-article-content-click.tsx (hunk 3 above)
Comment (alshakero) [reply packages/help-center/src/hooks/use-article-content-click.tsx]: I think React's `MouseEvent`was messing with you, here's my take, I also added `useMemo` to fitlers.

```ts
import { useEffect, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';

const isThisASupportArticleLink = ( href: string ) =>
	/wordpress\.com(\/\w\w)?(?=\/support\/)|support\.wordpress\.com/.test( href );

export const useArticleContentClick = ( node: HTMLDivElement | null ) => {
	const navigate = useNavigate();

	const filters = useMemo(
		() => [
			/**
			 * Make support article links open within Help Center.
			 */
			{
				condition: ( target: HTMLElement ) =>
					target.tagName === 'A' &&
					isThisASupportArticleLink( target.getAttribute( 'href' ) || '' ),
				action: ( event: MouseEvent ) => {
					event.preventDefault();
					const target = event.target as HTMLElement;
					const href = target.getAttribute( 'href' );
					navigate( `/post?link=${ href }` );
				},
			},

			/**
			 * Fix jump-to-section links.
			 */
			{
				condition: ( target: HTMLElement ) =>
					target.tagName === 'A' && target.getAttribute( 'href' )?.startsWith( '#' ),
				action: ( event: MouseEvent ) => {
					const target = event.target as HTMLElement;
					if ( target.tagName === 'A' ) {
						event.preventDefault();
						const href = target.getAttribute( 'href' );
						node?.querySelector( href as string )?.scrollIntoView();
					}
				},
			},
		],
		[ node, navigate ]
	);

	useEffect( () => {
		node?.addEventListener( 'click', ( event: MouseEvent ) => {
			const target = event.target as HTMLElement;

			filters.forEach( ( { condition, action } ) => {
				if ( condition( target ) ) {
					action( event );
				}
			} );
		} );
	}, [ node, filters ] );
};
```

File: packages/help-center/src/components/help-center-article.tsx [hunk 4]
```diff
@@ -38,64 +34,46 @@ export const HelpCenterArticle: React.FC = () => {
 				}
 			}, 0 );
 		}
-	}, [ articleUrl, post ] );
+	}, [ postUrl, post ] );
 
+	// Handle redirecting to new routes
```
Comment (alshakero) [inline packages/help-center/src/components/help-center-article.tsx:39]: I suppose this cancels the need for https://github.com/Automattic/wp-calypso/pull/92899? cc @agrullon95.

File: packages/help-center/src/hooks/use-container-click.ts [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+			 * Fix table of content links.
+			 */
+			{
+				condition: ( target: HTMLElement ) =>
+					target.tagName === 'A' && target.closest( '.a8c-table-of-contents' ),
+				action: ( event: MouseEvent, target: HTMLElement ) => {
+					event.preventDefault();
+					const href = target.getAttribute( 'href' );
+					const hash = href?.split( '#' )[ 1 ];
+					node?.querySelector( `#${ hash }` )?.scrollIntoView();
```
Comment (alshakero) [inline packages/help-center/src/hooks/use-container-click.ts]:
```suggestion
					const href = target.hash;
					node?.querySelector( `#${ hash }` )?.scrollIntoView();
```

File: packages/help-center/src/hooks/use-container-click.ts [hunk 6]
```diff
@@ -0,0 +1,54 @@
...
+			},
+
+			/**
+			 * Fix table of content links.
+			 */
+			{
+				condition: ( target: HTMLElement ) =>
+					target.tagName === 'A' && target.closest( '.a8c-table-of-contents' ),
+				action: ( event: MouseEvent, target: HTMLElement ) => {
+					event.preventDefault();
```
Comment (alshakero) [inline packages/help-center/src/hooks/use-container-click.ts]: You should only `preventDefault` on success. This will break other clicks.

File: packages/help-center/src/hooks/use-container-click.ts (hunk 5 above)
Comment (alshakero) [inline packages/help-center/src/hooks/use-container-click.ts]: You can use `event.currentTarget` instead of accessing `node` that can be outdated.

File: packages/help-center/src/hooks/use-post-by-url.ts [hunk 7]
```diff
@@ -0,0 +1,23 @@
...
+						apiVersion: '2',
+				  } )
+				: apiFetch( {
+						path: `/help-center/fetch-post?post_url=${ encodeURIComponent( url ) }`,
+				  } ),
+		enabled: !! url,
+		refetchOnWindowFocus: false,
+		staleTime: 12 * 3600, // 12 hours
+	} );
+}
```
Comment (alshakero) [inline packages/help-center/src/hooks/use-post-by-url.ts:23]: <3

**Review by alshakero — CHANGES_REQUESTED** [review]
Beautiful. So much more straight forward!! Left some cosmetic comments.

File: packages/help-center/src/components/help-center-article.tsx (hunk 4 above)
Comment (agrullon95) [reply packages/help-center/src/components/help-center-article.tsx:39]: Yes, that's correct. I spoke with Tony and tested these changes. This will fix https://github.com/Automattic/wp-calypso/pull/92899. I will rename that PR and mainly use it to rename the navigation logic to make it clearer.

**Comment by agrullon95** [comment]
@arcangelini - Let's also add this CSS change to address the scrolling issue for the first ToC anchor links: https://github.com/Automattic/wp-calypso/pull/92798/files#diff-e5b27a0004ab04edbea14900e109175de860cbf365cd7d7d6f3d5ac1989bb0e0R229

**Comment by agrullon95** [comment]
Issues I've noticed so far (will update if I find more issues):

* If you click on an image, it attempts to open it as an article since it's a support URL (instead of opening the image in a new tab).

**Comment by escapemanuele** [comment]
Great catch @agrullon95!

I tried to catch some other bugs, but I couldn't find any 👌

**Review by escapemanuele — APPROVED** [review]
Just tested again and now the problem is fixed! 

I wonder though if it would make sense to remove the link from the images in the articles rendered inside the HC?

**Comment by escapemanuele** [comment]
Tested once more and all looks fine. Let's wait for the AT update to give a last test in Gutenberg and wp-admin and then we should be good 👍

**Comment by arcangelini** [comment]
AT landed and the endpoint is working as expected. I will deploy this in the AM.
