### PR TITLE
WelcomeTour/TourKit: Minimized tour on mobile when menu is opened

### LINKED ISSUE #55610: Welcome Tour: Tour stays in front of the menu on smaller screens
### Steps to reproduce the behavior

1. Open a browser and switch to a mobile viewport
2. Go to the Editor.
3. Open/Activate the Welcome Tour
4. Click on a menu item
5. The menu opens **behind** the Tour.

#### What I expected to happen
When the Welcome Tour is open, and you click on a menu item, the Tour should be minimized.

#### What actually happened
When the Welcome Tour is open, and you click on a menu item, the tour stays open.

Screenshot 2021-08-18 at 17 04 00

### PR DESCRIPTION
**Pull request by escapemanuele**
#### Changes proposed in this Pull Request

* Tour Kit now has a `isMinimized` boolean value in the config, so it is possible to minimize the tour from outside TourKit
* Tour Kit now has a `portalElementId` option element, to customize under which DOM container append the tour modal (defaults to document.body)
* WelcomeTour is minimized when on mobile and the inserter menu is opened
**Before**
image
* WelcomeTour is minimized when on mobile and the settings menu is opened
**Before**
image
* WelcomeTour is minimized when on desktop/tablet and the sidebar is opened
**Before**
image
* WelcomeTour is hidden when W-icon is clicked, on mobile and not in calypso

#### Why

A little detail about why we didn't minimize the tour when the W-icon is pressed: the sidebar doesn’t have any kind of state you can select from, it’s plain php and JS. 
With the great help of @cpapazoglou, we managed to hide the tour when the button is pressed, using CSS.
I'd like to ask @poligilad-auto if this solution is acceptable.

#### Testing instructions

* Checkout the branch
* `yarn dev --sync` from `apps/editing-toolkit`
* Go to the editor
* Check that the tour is minimized when:
-- the sidebar (after pressing the W icon) is open, on desktop and tablet
-- the inserter is open, on mobile
-- settings tab is open, on mobile
* Check that the tour isn't showing over the menu "my sites" (after pressing the w-icon, not in calypso ( where you'd be redirected to home ) )

Related to #55610
Fixes #55610

### CODE REVIEW

File: packages/tour-kit/src/components/tour-kit.tsx [hunk 1]
```diff
@@ -19,12 +19,19 @@ const TourKit: React.FunctionComponent< Props > = ( { config, __temp__className
 		const classes = [ 'tour-kit', ...( __temp__className ? [ __temp__className ] : [] ) ];
 
 		portalParent.classList.add( ...classes );
-		document.body.appendChild( portalParent );
+
+		let portalElement = document.body;
```
Comment (cpapazoglou) [inline packages/tour-kit/src/components/tour-kit.tsx]:
```suggestion
		const portalParentElement = config.options?.portalElementId || document.body;
```

I think making this an one-liner actually increases readability. Also, let's use a more declarative name `portalParentElement` rather than `portalElement`

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/style-tour.scss [hunk 2]
```diff
@@ -41,3 +41,12 @@ $welcome-tour-card-media-extra-padding: 14%; // temporary value, to match the pa
 		}
 	}
 }
+
+// Overriding an existing core WP rule, because the ID selector is necessary
```
Comment (cpapazoglou) [inline apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/style-tour.scss]: just noting that we are not overriding a WP rule, we are just adding one more related to the `tour-kit.wpcom-tour-kit`

File: packages/tour-kit/src/components/tour-kit.tsx (hunk 1 above)
Comment (escapemanuele) [reply packages/tour-kit/src/components/tour-kit.tsx]: `config.options?.portalElementId` is a string, while document.body an HTMLElement, so I modified it to pass directly the portal parent HTMLElement

**Comment by poligilad-auto** [comment]
@escapemanuele I like the solution of minimizing the tour in these instances. 
It makes sense to me, as the user didn't choose to close it and is trying to take another action on the screen, that way they could still access the tour if they like.

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-launch.tsx [hunk 3]
```diff
@@ -59,6 +60,16 @@ function WelcomeTour() {
...
+	const { isInserterOpened, isSidebarOpened, isSettingsOpened } = useSelect( ( select ) => ( {
+		isInserterOpened: select( 'core/edit-post' ).isInserterOpened(),
+		isSidebarOpened: select( 'automattic/block-editor-nav-sidebar' ).isSidebarOpened(),
+		isSettingsOpened:
+			select( 'core/interface' ).getActiveComplementaryArea( 'core/edit-post' ) ===
+			'edit-post/document',
+	} ) );
+
+	const isTourMinimized =
+		isSidebarOpened || ( isMobile() && ( isInserterOpened || isSettingsOpened ) );
```
Comment (arcangelini) [inline apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-launch.tsx]: I think Gutenberg uses the `MEDIUM` breakpoint for enabling the sidebars, which is at 782px. Could be helpful to use that instead of `isMobile` to ensure that this applies to all screens that would be affected by this.

**Review by arcangelini — CHANGES_REQUESTED** [review]
Bellissimo. Everything works as advertised. Just one suggestion that could help I think.

**Review by arcangelini — APPROVED** [review]
I like it 👍 2️⃣  🚢
