### PR TITLE
Subscription Management: Add cross-portal compatible Link component and fix title cell styling.

### LINKED ISSUE #78328: Subscription Management: Create Link component that works on both Calypso Router & React-Router.
We should create a `<Link>` component that works on both Calypso Router & React-Router.

We can use `<ConditonalLink>` component as a reference point.

### LINKED ISSUE #78331: Subscription Management: Whitespace around site title and site icon.
There is extra whitespace around the site title and site icon.
image

### PR DESCRIPTION
**Pull request by yansern**
Fixes https://github.com/Automattic/wp-calypso/issues/78328
Fixes https://github.com/Automattic/wp-calypso/issues/78331

## Proposed Changes

* Introduce a new `<Link>` component that works with both calypso router & react-router-dom.
  * This removes the need for `onSiteTitleClick()`.
* Migrate the links in Sites list to use `<Link>` component.
* Restore the old HTML structure for the title cell in Sites list with a bit of markup & styling clean-up.
  * This fixes the whitespace regression around the title icon and title name introduced in the [reader refactor PR](https://github.com/Automattic/wp-calypso/pull/77553).

## Testing Instructions

**Test standalone routing:**
 * Go to `/subscriptions/sites`.
 * Check if everything in the title cell renders properly.
 * Click on title icon and title name should take you to the individual site subscription page.

**Test reader routing:**
 * Go to `/read/subscriptions`.
 * Check if everything in the title cell renders properly.
 * Click on title icon and title name should take you to `/read/feeds/<broken_id>`.
   * Currently it leads to the wrong place. But as long as the URL on the address bar is correct, this is fine.
 

**Before:**
image

**After:**
image

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: client/landing/subscriptions/components/link/link.tsx [hunk 1]
```diff
@@ -0,0 +1,19 @@
+import { Link as RouterLink, LinkProps as RouterLinkProps } from 'react-router-dom';
+import {
+	useSubscriptionManagerContext,
+	SubscriptionsPortal,
+} from '../subscription-manager-context';
+
+type LinkProps = Omit< RouterLinkProps, 'to' > &
+	Omit< React.HTMLProps< HTMLAnchorElement >, 'ref' > & { active?: boolean };
+
+const Link: React.FunctionComponent< LinkProps > = ( { active = false, ...props } ) => {
```
Comment (TimBroddin) [inline client/landing/subscriptions/components/link/link.tsx]: Why not just ``` const Link = ( { active = false, ...props } : LinkProps ) => { } ```?

Asking out of curiousity.

File: client/landing/subscriptions/components/link/link.tsx [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+	const { portal } = useSubscriptionManagerContext();
+
+	if ( active || portal === SubscriptionsPortal ) {
+		return <RouterLink to={ props.href || '' } { ...props } />;
+	}
+	return <a { ...props }></a>;
```
Comment (TimBroddin) [inline client/landing/subscriptions/components/link/link.tsx:16]: If I'm understanding this correctly, this means that inside Reader this just renders normal `<a>` tags? But somehow Reader catches clicks on these to turn them into SPA-style links. TIL.

**Review by TimBroddin — APPROVED** [review]
Looks good to me.  I tested both scenarios and they work. 
As noted the links point to a 404 page on Reader, but that was to be expected.

File: client/landing/subscriptions/components/link/link.tsx (hunk 2 above)
Comment (yansern) [reply client/landing/subscriptions/components/link/link.tsx:16]: Yes, Calypso catches all `<a>` and SPA-route them.

File: client/landing/subscriptions/components/link/link.tsx (hunk 1 above)
Comment (yansern) [reply client/landing/subscriptions/components/link/link.tsx]: Looks like this works too! :) Gonna update it.

**Review by TimBroddin — APPROVED** [review]
Reapproved!
