### PR TITLE
Gutenlypso: Register server-defined blocks attributes (Take 2)

### LINKED ISSUE #27963: Gutenberg: Dynamic blocks default attributes aren't loaded
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/gutenberg/post/ ; select a site and load Gutenberg.
2. Insert a dynamic block such as `Latest Comments`.
3. Open the block settings: all the toggles are off and the slider's value is empty.
4. Compare it with how the block is rendered and observe how most, if not all, settings have the incorrect values.

Notes:
- Changing one setting will fix this inconsistency for that setting. This issue is only about the default values.
- Some cases (e.g. the Categories block) might be misleading, because all the attributes actually default to `false`.

#### What I expected

That the block default values are applied to the block sidebar.

#### What happened instead

The block sidebar uses the components default values instead (e.g. false for toggle; empty for the slider input)

#### Screenshot / Video

screenshot 2018-10-19 at 11 53 32

#### Context / Source

Gutenberg feeds those default values to the blocks settings with the [`unstable__bootstrapServerSideBlockDefinitions `](https://github.com/WordPress/gutenberg/blob/48c120966e155f4c4134133ae92bfe38f2a1f846/packages/blocks/src/api/registration.js#L20-L54) function, which is called in the [`client-assets.php`](https://github.com/WordPress/gutenberg/blob/48c120966e155f4c4134133ae92bfe38f2a1f846/lib/client-assets.php#L1429-L1433) file.

That function is never called in Calypso, and therefore all dynamic blocks default attributes fallback to empty objects.

### PR DESCRIPTION
**Pull request by Copons**
#### Changes proposed in this Pull Request

Alternative approach to #29984.

* Manually register the server-defined dynamic blocks (e.g. Latest Comments) attributes.

Note: to work, this has to happen before `registerCoreBlocks()`, hence the `then`.

#### Context

Dynamic blocks are registered [server-side](https://github.com/WordPress/gutenberg/blob/cded0f974461955d2ccffee1d9dcb6985d45abfc/packages/block-library/src/latest-comments/index.php#L150-L182), and their attribute are loaded through the [`unstable__bootstrapServerSideBlockDefinitions`](https://github.com/WordPress/gutenberg/blob/cded0f974461955d2ccffee1d9dcb6985d45abfc/packages/blocks/src/api/registration.js#L51-L53) function, called [server-side](https://github.com/WordPress/gutenberg/blob/cded0f974461955d2ccffee1d9dcb6985d45abfc/lib/client-assets.php#L1155-L1159) as well.

Gutenlypso doesn't have access to the same JS globals so it doesn't have any information about the dynamic blocks' schema and attributes.

#### Testing instructions

* Open `/block-editor`.
* Insert the Latest Comments block.
* Check that its preview correspond to its sidebar settings defaults:

screenshot 2019-01-08 at 15 12 23

Fixes #27963

### CODE REVIEW

**Comment by kwight** [comment]
Works great for me, wonderful job :) I left some comments to address on D22987-code.

File: client/gutenberg/editor/init.js [hunk 1]
```diff
@@ -60,6 +63,18 @@ const addResetToRegistry = registry => {
...
+	waitForData( {
+		serverBlocksAttributes: () => requestGutenbergServerBlocksAttributes(),
+	} ).then( ( { serverBlocksAttributes } ) => {
+		if ( serverBlocksAttributes.data ) {
+			debug( 'Registering server-defined blocks attributes' );
+			unstable__bootstrapServerSideBlockDefinitions( serverBlocksAttributes.data );
+		}
+		debug( 'Registering core blocks' );
+		registerCoreBlocks();
+	} );
```
Comment (dmsnell) [inline client/gutenberg/editor/init.js]: I don't know if we can find a good way to split it, but I'm noting that we seem to be introducing another API call serially here when I think we could be happy making it in parallel to other calls that prepare the editor.

if you look at [the EditorLoader](https://github.com/Automattic/wp-calypso/blob/c5f364d218c0a9cef188f6a3cdc952d312147bcc/client/gutenberg/editor/controller.js#L188) you can see where we list parallel-executed promises. it might end up a little complicated if we have to pass in the result of that API call to `init()` but it can be done and it would prevent another loading state.

I didn't see anything inside of `init` that was async. we might be able to rearrange `makeEditor` so that instead of calling the `require()` promise it gets that as its input.

```js
	const EditorLoader = asyncLoader( {
		promises: {
			editorModule: import( './init' ),
			serverBlocks: requestEm(),
			translations: loadTranslations( context.store ),
			blockAvailability: loadGutenbergBlockAvailability( context.store ),
		},
		loading: () => <Placeholder />,
		success: ( { editorModule: { init }, serverBlocks } ) => React.createElement( makeEditor( init, serverBlocks ) ),
		failure: () => <div>Couldn't load everything - try hitting reload in your browser…</div>,
	} );
```

That would start the load of the server blocks as soon as we start loading the editor code.

Also, the server block definitions are inside of the `once()` and I wonder if that will need to be evaluated in context of changing sites.

Comment (gwwar) [reply client/gutenberg/editor/init.js]: Hmm, are we overthinking this maybe? This definition should remain the same for simple sites on wpcom, so I think we can maybe even load this once in the app skeleton or layout. No Jetpack sites use Gutenlypso yet.

Comment (dmsnell) [reply client/gutenberg/editor/init.js]: I wasn't really looking at the broader problem @gwwar so @Copons yeah please defer to this comment above.

on that note though _if_ we end up making the API call I was mostly concerned about introducing the async task in the serial hot path vs. side loading it in parallel, even if it's only loaded once

Comment (gwwar) [reply client/gutenberg/editor/init.js]: We also wouldn't support non-whitelisted blocks in Calypso, so I suppose a sublist for Jetpack sites wouldn't hurt either

Comment (Copons) [reply client/gutenberg/editor/init.js]: My reasonings for running this in the `init` instead of in the controller async loader are:
- Keep the entire blocks registration logic in one single place.
- Make sure to only run the server-side attributes registration once.

Although, I agree that the controller's `asyncLoader` is a much better fit for `waitForData`.

**Comment by Copons** [comment]
FYI moved the discussion to p7jreA-23I-p2 (internal), especially `#comment-1488`.

File: client/gutenberg/editor/init.js (hunk 1 above)
Comment (Copons) [reply client/gutenberg/editor/init.js]: Sorry, I've somehow forgot to complete the thought.

I agree that `asyncLoader` is the right fit for `waitForData` functions.
But, since this is now only about Core blocks and Core blocks never change and are the same for all sites, it's also optimal to run this request only once.

I know that subsequent requests would always hit the cache, but they'd still be unnecessary.
