### PR TITLE
Subscribers Page: Fix subscribers empty view

### LINKED ISSUE #85667: Subscribers page: view for no results when searching is missing
Image

### PR DESCRIPTION
**Pull request by phcp**
Closes https://github.com/Automattic/wp-calypso/issues/85667

## Proposed Changes

* Change `grandTotal` to use `useSubscriberCountQuery`
* Fix cache key to include `hasManySubscribers`

## Testing Instructions

* Apply this PR to your local
* Go to http://calypso.localhost:3000/subscribers/{site-slug}
* Open a site with no subscribers
* You should see the Subscribers Launchpad
* Open a site with subscribers and search for a non-existent subscriber
* You should see an empty search view

image

image

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: client/my-sites/subscribers/components/subscriber-list-container/subscriber-list-container.tsx [hunk 1]
```diff
@@ -50,11 +50,11 @@ const SubscriberListContainer = ( {
 		if ( ! isLoading && subscribers.length === 0 && page > 1 ) {
 			pageChangeCallback( pages ?? 0 );
 		}
-	}, [ isLoading, subscribers, page, pageChangeCallback ] );
+	}, [ isLoading, subscribers, page, pageChangeCallback, pages ] );
 
 	return (
 		<section className="subscriber-list-container">
-			{ ! isLoading && ( Boolean( grandTotal ) || searchTerm ) && (
+			{ Boolean( grandTotal ) && (
```
Comment (JuanLucha) [inline client/my-sites/subscribers/components/subscriber-list-container/subscriber-list-container.tsx]: I wonder if we could leave this as `{ grandTotal && (` 🤔

**Review by JuanLucha — APPROVED** [review]
Nice work!
Screenshot 2024-01-24 at 20 39 56

File: client/my-sites/subscribers/components/subscriber-list-container/subscriber-list-container.tsx (hunk 1 above)
Comment (phcp) [reply client/my-sites/subscribers/components/subscriber-list-container/subscriber-list-container.tsx]: Yes, indeed. I'll do it :)
