### PR TITLE
Rewind - Signup flow: don't say that backups are ready if user skips the steps

### LINKED ISSUE #22293: Activity Log Connection: Conflicting messages when skipping credential sharing
#### Steps to reproduce
1. Starting at URL: https://my.pressable.com/
2. Create a new Pressable site.
3. In the Pressable site settings, select the link to finish setting up Jetpack Premium: "To finish activating Jetpack Premium, please follow this link."
4. On the "In partnership with Pressable" screen (logged in to WordPress.com), approve the connection to WordPress.com.
5. On the "Start backing up your site" screen, select "Skip" to decline credential sharing.
6. On the "Are you sure?" screen, select "Skip" again.

#### What I expected

I expected the connection to be successful, with no mention of site backups.

#### What happened instead

The success screen says, "Your site is backing up because your site is set up with Jetpack Premium plan at no additional cost to you."

This conflicts with the message I saw on the "Are you sure?" screen, which says, "If you don't share credentials with Jetpack, your site won't be backed up."

#### Screenshot / Video

screenshot 2018-02-09 16 42 37

screenshot 2018-02-09 16 28 08

screenshot 2018-02-09 16 43 39

#### Context / Source
#manual-testing #flow-testing

### PR DESCRIPTION
**Pull request by eliorivero**
Fixes #22293

This PR fixes the issue where the text saying that backups were ready and backing up the site was shown **even if the user skipped the setup steps**.

With this PR:
- the text is no longer shown when user skips the steps. Applies to `/start/pressable-nux` and `/start/rewind-auto-config` flows
- the button in the last step for the `/start/pressable-nux` is now a proper primary button

### Step when backups were not configured

captura de pantalla 2018-02-13 a la s 18 18 58

### Step when backups are configured

captura de pantalla 2018-02-13 a la s 18 19 14

### Testing

Please test with a Pressable site and a non-Pressable site
- site that doesn't have Rewind active because of the reason `vp_can_transfer`
- site in `awaiting_credentials` mode that requires the creds to be enter with the form
- site that can be auto-configured

If you need to re-test, make sure you clean Calypso's Local Storage and Indexed DB
captura de pantalla 2018-02-13 a la s 18 20 31

### CODE REVIEW

File: client/signup/steps/creds-complete/index.jsx [hunk 1]
```diff
@@ -21,25 +22,30 @@ class CredsCompleteStep extends Component {
...
 				<p className="creds-complete__description">
+					{ get( signupDependencies, 'rewindconfig', false ) &&
+						translate(
+							'Your site is backing up because your site is set up with Jetpack Premium plan at ' +
+								'no additional cost to you.'
+						) }
 					{ translate(
-						'Your site is backing up because your site is set up with Jetpack Premium plan at ' +
-							'no additional cost to you. Finish setting up Jetpack and your site is ready to be ' +
+						'Finish setting up Jetpack and your site is ready to be ' +
```
Comment (MichaelArestad) [inline client/signup/steps/creds-complete/index.jsx]: Needs a space before `Finish`

File: client/signup/steps/creds-complete/index.jsx [hunk 2]
```diff
@@ -21,25 +22,30 @@ class CredsCompleteStep extends Component {
...
+		signupDependencies: PropTypes.object,
 	};
 
 	renderStepContent = () => {
-		const { translate, wpAdminUrl } = this.props;
+		const { translate, wpAdminUrl, signupDependencies } = this.props;
 
 		return (
 			<Card className="creds-complete__card">
 				<h3 className="creds-complete__title">{ translate( 'Your site is set up and ready!' ) }</h3>
```
Comment (MichaelArestad) [inline client/signup/steps/creds-complete/index.jsx]: This headline is a little weird in the context of adding credentials from the activity log. Would it be easy to change for just that flow? Perhaps the person could just exit the flow from the second skip link instead?

File: client/signup/steps/creds-complete/index.jsx (hunk 1 above)
Comment (rcoll) [reply client/signup/steps/creds-complete/index.jsx]: Yeah this copy feels awkward to me as well.

**Comment by rcoll** [comment]
On this page, after following the JITM to set up credentials, and skipping twice, I get the following heading:

screen shot 2018-02-13 at 5 14 06 pm

File: client/signup/steps/rewind-were-backing/index.jsx [hunk 3]
```diff
@@ -25,21 +26,27 @@ class RewindWereBacking extends Component {
...
 				<p className="rewind-were-backing__description rewind-switch__description">
+					{ get( dependencyStore, 'rewindconfig', false ) &&
+						translate(
+							'Your site is backing up because your site is set up with Jetpack Premium plan at ' +
+								'no additional cost to you.'
+						) }
 					{ translate(
-						'Welcome to your Jetpack Premium plan! ' +
-							"That sound you're hearing? It's your website doing backflips with excitement!"
+						'Finish setting up Jetpack and your site is ready to be ' +
```
Comment (beaulebens) [inline client/signup/steps/rewind-were-backing/index.jsx]: This sentence ends up butting up against the previous one -- needs a space in there.

File: client/signup/steps/rewind-were-backing/index.jsx [hunk 4]
```diff
@@ -25,21 +26,27 @@ class RewindWereBacking extends Component {
...
 			<Card className="rewind-were-backing__card rewind-switch__card rewind-switch__content">
 				<h3 className="rewind-were-backing__title rewind-switch__heading">
-					{ translate( "We're backing up your site!" ) }
+					{ translate( 'Your site is set up and ready!' ) }
 				</h3>
 				<img src="/calypso/images/illustrations/thankYou.svg" alt="" />
 				<p className="rewind-were-backing__description rewind-switch__description">
+					{ get( dependencyStore, 'rewindconfig', false ) &&
+						translate(
+							'Your site is backing up because your site is set up with Jetpack Premium plan at ' +
```
Comment (beaulebens) [inline client/signup/steps/rewind-were-backing/index.jsx]: This wording is pretty awkward, suggest:

"Your site is being backed up because it is set up with Jetpack Premium at no additional cost to you."

Comment (beaulebens) [reply client/signup/steps/rewind-were-backing/index.jsx]: (same above)

File: client/signup/config/steps.js [hunk 5]
```diff
@@ -262,12 +262,12 @@ export default {
 
 	'creds-confirm': {
 		stepName: 'creds-confirm',
-		providesDependencies: [],
+		providesDependencies: [ 'rewindconfig' ],
```
Comment (rcoll) [inline client/signup/config/steps.js]: I'm curious why this is necessary here.

File: client/signup/steps/rewind-were-backing/index.jsx (hunk 3 above)
Comment (rcoll) [inline client/signup/steps/rewind-were-backing/index.jsx]: It could just be me, but this copy feels awkward and unclear.

File: client/signup/steps/rewind-were-backing/index.jsx [hunk 6]
```diff
@@ -25,21 +26,27 @@ class RewindWereBacking extends Component {
...
 
 		return (
 			<Card className="rewind-were-backing__card rewind-switch__card rewind-switch__content">
 				<h3 className="rewind-were-backing__title rewind-switch__heading">
-					{ translate( "We're backing up your site!" ) }
+					{ translate( 'Your site is set up and ready!' ) }
 				</h3>
 				<img src="/calypso/images/illustrations/thankYou.svg" alt="" />
 				<p className="rewind-were-backing__description rewind-switch__description">
+					{ get( dependencyStore, 'rewindconfig', false ) &&
```
Comment (rcoll) [inline client/signup/steps/rewind-were-backing/index.jsx]: This does work, but it seems like we should be checking the SM here, rather than relying on the dependency store.

File: client/signup/steps/rewind-were-backing/index.jsx (hunk 3 above)
Comment (MichaelArestad) [reply client/signup/steps/rewind-were-backing/index.jsx]: Yeah, I thought it odd as well. We might want a specific version for folks setting up creds via the JITM?

File: client/signup/config/steps.js (hunk 5 above)
Comment (eliorivero) [reply client/signup/config/steps.js]: @rcoll it's to whitelist the dependency, otherwise JS console throws a warning.

File: client/signup/steps/rewind-were-backing/index.jsx (hunk 3 above)
Comment (eliorivero) [reply client/signup/steps/rewind-were-backing/index.jsx]: Good catch, thanks!

File: client/signup/steps/creds-complete/index.jsx (hunk 2 above)
Comment (eliorivero) [reply client/signup/steps/creds-complete/index.jsx]: @MichaelArestad yes, it's possible, and exiting through the second link would've required less refactoring. Please confirm if we'll go with that and I'll adapt things.

**Comment by eliorivero** [comment]
@rcoll that screenshot with the "We're backing up your site" is odd because that string was actually removed in https://github.com/Automattic/wp-calypso/pull/22411/files#diff-38269bd48feacb757467e037ffb3626dL36

File: client/signup/steps/rewind-were-backing/index.jsx (hunk 6 above)
Comment (eliorivero) [reply client/signup/steps/rewind-were-backing/index.jsx]: Makes sense 👍
I'll wait until Michael responds about exiting the flow in the second skip.

File: client/signup/steps/creds-complete/index.jsx (hunk 2 above)
Comment (MichaelArestad) [reply client/signup/steps/creds-complete/index.jsx]: Let's exit through the second skip link for the JITM/Banner flow.

**Comment by rcoll** [comment]
@eliorivero I got sent to Production when I clicked the JITM on my first test. Just tested again locally and didn't get the message. False alarm, looks fine!

File: client/signup/steps/rewind-were-backing/index.jsx (hunk 4 above)
Comment (eliorivero) [reply client/signup/steps/rewind-were-backing/index.jsx]: Done 👍

**Comment by eliorivero** [comment]
Thanks for the review, I've addressed the issues:

- in the /start/rewind-auto-config flow, go back to AL if user skips a second time
- added space to separate sentences
- updated "Your site is being backed up..." wording

**Comment by MichaelArestad** [comment]
Nice. Ship it!
