### PR TITLE
Fix SIWA when users have 2FA enabled

### LINKED ISSUE #42359: Sign in with Apple (SIWA): Can't connect Apple account to existing WP.com account when 2FA is enabled
Connecting an Apple account to an existing account that already has 2FA enabled currently fails when a user attempts to do this via `/log-in`. The Apple account can be added successfully if you go to `/me/security/social-login` after logging in.

Connecting an Apple account to an existing account that _doesn't_ have 2FA enabled, appears to work correctly.

#### Steps to reproduce

1. With an account that doesn't have an Apple account connected, enable 2FA (the email should match the Apple account you're going to use).
2. Go to `/log-in`
3. Select `Continue with Apple`
4. You should see a notice that an account already exists and to log in to connect your Apple account with the WordPress.com account
5. After entering your password and 2FA, you'll be redirected to `/log-in/social-connect`, however there'll be additional errors in the console, and the [social connect prompt](https://github.com/automattic/wp-calypso/blob/d8abda88ad56af035ed0c6f49da22650ba73635f/client/blocks/login/index.jsx#L401) does not get rendered.

#### What I expected

To be able to add an Apple account to an existing WordPress.com account via `/log-in`.

#### What happened instead

An empty page.

#### Browser / OS version

Chrome 81, MacOS 10.14.6

#### Screenshot / Video

The page looks like this:

image

It should look like this:

image

### PR DESCRIPTION
**Pull request by alshakero**
### Changes proposed in this Pull Request

This PR fixes signing in with Apple when 2FA is enabled.

What was happening is that at the last stage of the login flow, in [LoginBlock](https://github.com/Automattic/wp-calypso/blob/master/client/blocks/login/index.jsx#L425), there are two boolean flags called `twoFactorEnabled` and `socialConnect`.

These flags, when `true`, are used to asynchronously fetch and render respective login blocks. The issue is that LoginBlock renders said blocks in an either or fashion. If `twoFactorEnabled` is enabled, the component will return the 2FA login block and bail out. Making `socialConnect` flag useless.

So if the user has 2FA **AND** Social login enabled, the social login block will not be fetched nor rendered.

This PR flips the order and makes `socialConnect` flag take precedence. Because this flag is only set to `true` after the 2FA flow is already done, so there is no need to render the 2FA block by the time `socialConnect` is set `true`.

I know this because `socialConnect` [is only set to `true` when the user is redirected to `social-connect`](https://github.com/Automattic/wp-calypso/blob/master/client/login/controller.js#L41) path. Whereas `twoFactorEnabled` remains `true` as long as the user is identified to have 2FA enabled. 

### Testing

Automatticians can't use social login. And my only Apple ID is an a8c account. So I can't test it. But the hiccup was before the a8c check, so I know this PR at least fixes the current faulty point. But I couldn't test beyond that.

Apple will not accept `calypso.live` domain as a valid domain for "sign in with Apple". To work around that please follow the following steps:

1. Checkout this branch locally and start Calypso. This PR has special config and will accept HTTPS requests on port 443.

2. Add `127.0.0.1 wordpress.com` to your hosts file.

2. Then visit https://wordpress.com/log-in. You should see a certificate warning. In this Chrome warning screen, type "thisisunsafe". This is a cheat code for Chrome that allows you to ignore certificate issues.

3. Once the page loads, please follow [these instructions](https://github.com/Automattic/wp-calypso/issues/42359#:~:text=Steps%20to%20reproduce) and see if the issue is still reproducible. 

Fixes #42359

### CODE REVIEW

**Comment by rachelmcr** [comment]
A testing note: For testing SIWA, I'd recommend [creating a new Apple ID](https://appleid.apple.com/account#!&page=create) using a non-a8c test email address, and test with a non-a8c WordPress.com account. I don't think there's any limitation on creating new Apple IDs as long as you're using a unique email.

I tested SIWA using the testing instructions in this PR and wasn't able to complete the login. I did get the 2FA prompt, as expected, but when I reached the social connect screen it was missing the Apple information:

Expected|Actual
-|-
|

Trying to proceed from there (clicking the Connect button) resulted in an error: `Please provide all of the required parameters.`

Screenshot 2020-07-23 11 33 54

However, that might just be an issue with the testing setup. (I'm not familiar enough with how to set things up for SIWA testing to know if there's another way to get this to work.) I also tested Google login (since the same issue was reported for Google in https://github.com/Automattic/wp-calypso/issues/42774 and I'd expect the fix for resolve both social logins). In that case, I was able to connect Google login to an existing WordPress.com account with 2FA (confirming after login that Google was connected):

Screenshot 2020-07-23 11 39 48

I also tested connecting Google login to a WordPress.com account without 2FA and confirmed that flow still works with this change.

Based on that Google login testing (and looking at the code) I think this change looks ok, but I'm hesitant to merge it without being able to test the full SIWA flow.

File: client/server/boot/index.js [hunk 1]
```diff
@@ -32,6 +33,9 @@ export default function setup() {
 	app.use( userAgent.express() );
 
 	if ( 'development' === process.env.NODE_ENV ) {
+		// use de.wordpress.com to prevent an infinite-loop
+		app.use( '/wp-login.php', createProxyMiddleware( { target: 'https://de.wordpress.com' } ) );
```
Comment (Tug) [inline client/server/boot/index.js:37]: don't forget to remove this change before merging ;)

**Comment by rachelmcr** [comment]
> Just a note: I have tested linking an existing wpcom account with a matching email address using social login without success. The app sends you a magic link which bypasses the linking screen. This is not a regression with this PR however as it's reproducible on production.

It sounds like the existing wpcom account you used was probably a passwordless account. (I confirmed it works when the existing wpcom account has a password.) There's an open issue https://github.com/Automattic/wp-calypso/issues/35909 for the general issue with magic links not working for connecting social login to an existing account — that's annoying if you want to choose to get a magic link, but definitely a more significant issue for passwordless accounts. I'll update that issue to reflect that.
