### PR TITLE
Themes: Use redux state for upload page back button

### LINKED ISSUE #11039: Themes: "All Themes" back link on sheet loses site reference after "Try & Customize"
If Try & Customize is triggered from the demo site web preview in the Theme Sheet, the "All Themes" back button to the full list loses the site reference.

Steps to reproduce:

1. Go to https://wordpress.com/design/$site where $site is a Jetpack site.
2. Select any theme.
3. Click on “Open Live Demo”.
4. Click on “Try & Customize” (when into the Jetpack site already).
5. Click the X button to cancel.
5. You’re redirected back to the theme page for that site as expected.
6. However, the “All Themes” link was pointing to just /design, not /design/$site as I’d expect.

Also likely related to this, even this basic flow is broken:

1. Go to https://wordpress.com/theme/ixion/$site, where $site is a Jetpack site. Do it in a fresh request, in a new tab.
2. Notice the “All Themes” link points to “/design” and not to “/design/$site”.

/ht @tyxla

### PR DESCRIPTION
**Pull request by seear**
back_path

Allow the theme upload page _Back_ button to return to any previous theme query state.

Use the same back path state in the upload page as we use for the theme info sheets. Only set the path state if the previous page was '/design' (but not '/design/upload').

Use path for <- back button and 'cancel' button on the eligibility form.

~~**Note** @folletto If the active site is changed whilst on the upload page, the `back` button will not take user to /design page for the new active site. If we want that behaviour, we will have to use a different approach.~~

Also fixes #11039 and #8500

### CODE REVIEW

**Comment by folletto** [comment]
> If the active site is changed whilst on the upload page, the back button will not take user to /design page for the new active site. If we want that behaviour, we will have to use a different approach.

Yes... we want that approach, as that's the underlying structure of Calypso (it's a matrix) ^^'

So this is a test flow:

1. open → `/design/$site1`
2. filter → `/design/free/$site1?s=white`
3. upload → `/design/upload/$site1`
4. switch site → `/design/upload/$site2`
5. back → `/design/free/$site2?s=white`

I'd say that for the first iteration back could just always go to `/design/$site`, whichever site happens to be active.

**Comment by seear** [comment]
> Yes... we want that approach, as that's the underlying structure of Calypso (it's a matrix) ^^'

Agreed. Ok, let me rethink. We can improve the way this works for theme sheets at the same time.

**Comment by seear** [comment]
> I'd say that for the first iteration back could just always go to /design/$site, whichever site happens to be active.

I've pushed a tweak in b68fc8f that falls back to /design/$site if the stored back path does not contain the currently selected site.

I've been playing with another solution that stores the back path as a template, for example:
`/design/music/${ siteSlug }/?s=news`
But it is more complicated, so I think we should go with the approach in this PR for now.

**Comment by folletto** [comment]
Test flow A — 

1. open → `/design/$site1`
2. filter → `/design/free/$site1?s=white`
3. upload → `/design/upload/$site1`
4. switch site → `/design/upload/$site2`
5. back → `/design/free/$site2?s=white`

Test flow B (from #8500) —

1. open → `/design/$site`
2. tap Current Theme "Info" button → `/theme/$theme/$site`
3. back "All Themes" → `/design/$site`
4. tap Current Theme "Customize" button
5. × close Customizer
6. lands → `/design/$site`

Test flow C (from #11039) — 

1. open → `/design/$jetpacksite`
2. tap theme thumbnail ("Info") → `/theme/$theme/$jetpacksite`
3. tap "Open Live Demo" → web preview modal
4. tap "Try & Customize"
5. × close Customizer
6. lands → `/theme/$theme/$jetpacksite`
7. back "All Themes" → `/design/$site`

Test flow D (from #11039) — 

1. open directly → `/theme/$theme/$jetpacksite` (fresh request, new tab from blank)
2. back "All Themes" → `/design/$site`

**Comment by folletto** [comment]
* Test flow A — ☑️ 
* Test flow B — ✅ 
* Test flow C — ❓ 
* Test flow D — ✅ 

**Test flow A**
Preserves site, but lost search and filter. This is however ok for this PR, as it might feel strange to preserve these too. I'm writing this just to noting the behaviour.

**Test flow C**
This is a bit hard to test as redirect back from a self-hosted to `calypso.live` is blocked and redirects thus to the site homepage. However, I tried to play around a bit and I'd say that it seems solved too as it's mostly related to the (D) flow as jumping from self-hosted back to Calypso probably count as a full reload.

Jetpack 4.5.

Ship it. 👍

File: client/my-sites/themes/theme-upload/index.jsx [hunk 1]
```diff
@@ -266,14 +263,14 @@ class Upload extends React.Component {
...
-				<HeaderCake onClick={ this.onBackClick }>{ translate( 'Upload theme' ) }</HeaderCake>
+				<HeaderCake backHref={ this.props.backPath }>{ translate( 'Upload theme' ) }</HeaderCake>
 				{ upgradeJetpack && <JetpackManageErrorPage
 					template="updateJetpack"
 					siteId={ siteId }
 					featureExample={ this.renderUploadCard() }
 					version="4.4.2" /> }
 				{ showEligibility && <EligibilityWarnings
-					backUrl="/design"
+					backUrl={ this.props.backPath }
```
Comment (ockham) [inline client/my-sites/themes/theme-upload/index.jsx]: Since it's used twice, you could destructure `backPath` along with the other destructured props on lines 247-254.

File: client/my-sites/themes/controller.jsx [hunk 2]
```diff
@@ -55,6 +55,11 @@ function getProps( context ) {
 }
 
 export function upload( context, next ) {
+	if ( startsWith( context.prevPath, '/design' ) &&
```
Comment (budzanowski) [inline client/my-sites/themes/controller.jsx]: Maybe a short comment here? At least I feel like it is needed. I actually never know if I should comment or rely on Blame and backtracking a PR.

File: client/my-sites/themes/theme-upload/index.jsx (hunk 1 above)
Comment (budzanowski) [inline client/my-sites/themes/theme-upload/index.jsx]: :+1:

File: client/my-sites/themes/controller.jsx (hunk 2 above)
Comment (seear) [inline client/my-sites/themes/controller.jsx]: Yes, I think this line can be confusing enough that it deserves a comment.
