### PR TITLE
Themes: fix entities in theme description

### LINKED ISSUE #34091: Themes: Add alt attributes from Showcase Data
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/themes
2. View source to see no alt attribute on theme screenshots.

#### What I expected

I expected there to be an alt attribute because I've added one in the theme showcase install. It looks like we have some code in place, but not sure where it's coming from. See: https://github.com/Automattic/wp-calypso/blob/d8d2ba47ec5a1bed7fd7146acd9fa4ed980d3fd9/client/components/theme/index.jsx#L223

#### What happened instead

No alt attribute was added, meaning screen reader users can't know what the themes look like.

#### Context / Source
Reported through a customer: #user-report.

### PR DESCRIPTION
**Pull request by bluefuton**
#### Changes proposed in this Pull Request

In https://github.com/Automattic/wp-calypso/issues/34091, it was reported that there was no alt text for theme screenshots. I've made an API change to include theme descriptions in the response, but some of them contain HTML entities.

This PR decodes HTML entities as they are received in the theme description.

#### Testing instructions

Go to http://calypso.localhost:3000/themes and hover over a theme screenshot. Make sure there are no entities in the theme description.

Examples of theme descriptions that previously included undecoded entities are 'Modern Business' and 'Elegant Business'.

Before:

Screen Shot 2019-06-25 at 15 47 31

After:

Screen Shot 2019-06-25 at 15 48 25

Fixes #34091.

### CODE REVIEW

File: client/state/themes/reducer.js [hunk 1]
```diff
@@ -301,6 +303,14 @@ export const queries = ( () => {
 		};
 	}
 
+	function fromApi( theme ) {
```
Comment (bluefuton) [inline client/state/themes/reducer.js]: Handling this in the reducer because this API request does not use the data layer.

File: client/state/themes/reducer.js [hunk 2]
```diff
@@ -223,11 +223,13 @@ export const themeRequestErrors = createReducer(
  * @return {Object}        Updated state
  */
 export function queryRequests( state = {}, action ) {
+	let serializedQuery;
```
Comment (bluefuton) [inline client/state/themes/reducer.js]: This is a linting fix for `no-case-declarations`:

https://eslint.org/docs/rules/no-case-declarations

File: client/state/themes/reducer.js [hunk 3]
```diff
@@ -301,7 +303,15 @@ export const queries = ( () => {
 		};
 	}
 
-	// Time after which queries storred in IndexedDb will be invalidated.
+	function fromApi( theme ) {
+		if ( ! theme || ! theme.description ) {
+			return theme;
+		}
+
+		return Object.assign( {}, theme, { description: decodeEntities( theme.description ) } );
```
Comment (jsnmoon) [inline client/state/themes/reducer.js]: Could we do `{ ...theme, description: decodeEntities( theme.description ) }` here instead? Is there a reason we're using `Object.assign` here in particular?

Comment (bluefuton) [reply client/state/themes/reducer.js]: Sounds good - I'll change that.
