### PR TITLE
Reader Cold Start: pass post down to post preview rather than using selector

### LINKED ISSUE #6181: Reader Cold Start: featured posts do not load in Safari until after refresh
Reported by @shaunandrews.

#### Steps to reproduce
1. Starting at URL: http://wpcalypso.wordpress.com/read/start

#### What I expected

Full post cards load, including featured post.

#### What happened instead

Featured posts do not load. Mostly appears after refresh.

Works fine in Chrome.

#### Browser / OS version

Safari OS X

#### Screenshot / Video

screen-shot-2016-06-21-at-12-21-18-am

### PR DESCRIPTION
**Pull request by bluefuton**
When loading cards in Cold Start, we're having an intermittent issue where the featured post does not load:

4691df4e-37d0-11e6-87a6-af0cc03bb4bd

As we're already loading the post in the card component, this PR passes the post object down to the post preview component, rather than just handing it the post ID.

Fingers crossed, this should solve the missing featured post. I'm unable to reproduce locally so don't know for certain.

Fixes #6181.

Test live: https://calypso.live/?branch=fix/reader/cold-start-post-preview-not-displaying-safari

### CODE REVIEW

**Comment by blowery** [comment]
Might as well  move everything up to the StartCard and just have the `connect` call there. Pull in the site and the post and pass them down the tree... Makes sense and it's simpler to reason about. The main reason for doing all the connects is to separate the list items from the list itself, and the card does that nicely.

**Comment by bluefuton** [comment]
> Might as well move everything up to the StartCard and just have the connect call there.

That's what I've done with the post preview and, you're right, may as well do the same for `site` and the card header. I'll add that now.

**Comment by bluefuton** [comment]
@blowery ready for 👀 again. The card does all the hard work now, and hands `post` and `site` down to the child components.

**Comment by jancavan** [comment]
Works for me now. I now see the featured post.

File: client/reader/start/card.jsx [hunk 1]
```diff
@@ -67,14 +68,14 @@ export default connect(
...
 		const siteId = get( recommendation, 'recommended_site_ID' );
 		const postId = get( recommendation, 'recommended_post_ID' );
-
+		const site = siteId ? getSite( state, siteId ) : undefined;
 		const post = postId ? getPostBySiteAndId( state, siteId, postId ) : undefined;
 
 		return {
 			recommendation,
-			siteId,
 			postId,
```
Comment (blowery) [inline client/reader/start/card.jsx]: can drop the postId now, ya?

Comment (bluefuton) [inline client/reader/start/card.jsx]: Yeah, guess we can just check the `post` object instead. I've remove.

Comment (bluefuton) [inline client/reader/start/card.jsx]: All gone! Ready for :eyes:.

**Comment by blowery** [comment]
🚢
