### PR TITLE
Fixed Header: add navigation items

### LINKED ISSUE #57101: Marketplace: New Plugins page header
### What

Update the Plugins header

### Why

Following the new Marketplace Designs (oU6nEIeiKSg8CayhEtgR6b-fi-6693%3A53273) we will need to update the header components and styles.

- [ ] Styling
- [x] Move search component to header
- [x] Rename "Install Plugin" to "Upload" and add the icon
- [ ] Navigation Breadcrumbs

|Before | After|
|-------|------|
|||

### How

_No response_

### PR DESCRIPTION
**Pull request by cpapazoglou**
#### Changes proposed in this Pull Request

* Creates a new breadcrumb component
* Fixes examples and docs
* Adds the nav items in `/plugins`, `/plugins/manage`

#### Testing instructions

* Visit `/plugins`
* Search for `woo`, you should get a new breadcrumb `Plugins > Search Results`
* Click **Manage**, you should get a new breadcrumb `Plugins > Manage`
* On all cases, clicking "Plugins" should redirect you back to the plugins screen

SS 2021-11-03 at 19 18 38

Fixes #57101

### CODE REVIEW

File: client/my-sites/plugins/main.jsx [hunk 1]
```diff
@@ -390,6 +390,25 @@ export class PluginsMain extends Component {
 		);
 	}
 
+	getNavigationItems() {
+		const { search, selectedSiteSlug } = this.props;
+		const navigationItems = [
+			{ label: this.props.translate( 'Plugins' ), href: `/plugins/${ selectedSiteSlug || '' }` },
```
Comment (cpapazoglou) [inline client/my-sites/plugins/main.jsx:396]: Just noting that `selectedSiteSlug || ''` is used for the all sites screens where `selectedSiteSlug === null`

File: client/components/fixed-navigation-header/README.md [hunk 2]
```diff
@@ -1,22 +1,26 @@
-# FixedNavigationHeader (JSX)
+# FixedNavigationHeader (TSX)
```
Comment (WBerredo) [inline client/components/fixed-navigation-header/README.md:1]: Is this an intentional change? If yes, why TSX?

File: client/components/breadcrumb/index.tsx [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+interface Props {
+	items: { label: string; href?: string }[];
+}
+
+const Breadcrumb: React.FunctionComponent< Props > = ( { items } ) => {
+	return (
+		<StyledUl>
+			{ items.map( ( item: { href?: string; label: string }, index: Key, { length } ) => {
+				// eslint-disable-next-line no-nested-ternary
+				const className = index === 0 ? 'first' : index === length - 1 ? 'last' : '';
```
Comment (WBerredo) [inline client/components/breadcrumb/index.tsx:44]: Nitpick: Any reason to be skipping this lint rule? Is it considered "simple enough"?

**Review by WBerredo — APPROVED** [review]
I was not able to test the *manage flow* as it sends me to wp-admin.

Just small questions below. Otherwise looks good.

File: client/components/fixed-navigation-header/README.md (hunk 2 above)
Comment (cpapazoglou) [reply client/components/fixed-navigation-header/README.md:1]: Yes it was, cause it's a typescript component.

File: client/components/breadcrumb/index.tsx (hunk 3 above)
Comment (cpapazoglou) [reply client/components/breadcrumb/index.tsx:44]: If you got it right with the first time reading it, yes I would consider it simple.

**Comment by cpapazoglou** [comment]
> I was not able to test the _manage flow_ as it sends me to wp-admin.
> 
> Just small questions below. Otherwise looks good.

You can test it by going to /plugins without any site selected.

File: client/components/breadcrumb/index.tsx (hunk 3 above)
Comment (WBerredo) [reply client/components/breadcrumb/index.tsx:44]: This one I was able to get easily on the first time, but I usually find nested ternaries tricky that's why I try to avoid them.

Comment (cpapazoglou) [reply client/components/breadcrumb/index.tsx:44]: Thanks for pushing on this! It made me think out of the box, that we actually don't even need JS to tell which is first and which is last.. Here is a follow up PR https://github.com/Automattic/wp-calypso/pull/57637
