### PR TITLE
SEO Tools: Fix upgrade nudge for Jetpack sites

### LINKED ISSUE #48841: SEO Tools: eligible plans are prompted to upgrade in order to show previews
#### Steps to reproduce the behavior

1. Create a Jetpack site with a Jetpack Security Daily, Jetpack Security Real-time, or Jetpack Complete plan.
2. Go to Tools > Marketing > Traffic, and make sure "Enable SEO Tools to optimize your site for search engines" is enabled.
2. Scroll down to the "Website Meta" section and click the "Show Previews" button.

#### What I expected to happen

I expected to see the previews.

#### What actually happened

A pop-up appears telling me I need to upgrade to a Business plan, and there are no previews.

Screen%20Shot%20on%202021-01-12%20at%2018-08-27

### PR DESCRIPTION
**Pull request by pablinos**
The new Jetpack plans didn't include the SEO preview tools feature, and
so we would display a nudge to upgrade to a business plan. Looking at
the legacy plans, it seems as though this feature was available on all
paid Jetpack plans, not just business.

Testing with a premium WPCOM plan, the meta section isn't shown, which
is the same for free Jetpack sites. Therefore it would appear that we
don't display this nudge in this context.

#### Changes proposed in this Pull Request

This change adds the feature to the new Jetpack plans and updates the
nudge to prompt people with Jetpack sites to upgrade to Security Daily.

From reading that is the equivalent of the Premium plan, but it would be 
good to get that business logic confirmed. 

#### Testing instructions

The testing instructions are the same as #48841.

* Create a Jetpack site ~with one of the new Security or Complete plans~ ([after some discussion with @kraftbj ](https://github.com/Automattic/wp-calypso/issues/48841#issuecomment-772913611)we've decided to open this feature up to all Jetpack sites)
* Go to /tools/marketing/traffic
* Make sure that the "Enable SEO Tools to optimize your site for search engines" option is enabled
* In the meta section click on Show Preview, and you'll be prompted to upgrade to a business plan
* With this PR you should see the preview.

Fixes #48841

### CODE REVIEW

**Review by allilevine — APPROVED** [review]
Tested on a JN site with the Jetpack Security Daily plan activated:
- Before: When I clicked "show previews" only the upgrade nudge was visible.
- After: When I clicked "show previews" I could preview Google, Facebook, and Twitter:
Screen Shot 2021-02-01 at 12 49 25 PM

> From reading that is the equivalent of the Premium plan, but it would be
> good to get that business logic confirmed.

+1 We should confirm whether each plan should see the nudge or the previews.

File: client/components/seo/preview-upgrade-nudge/index.jsx [hunk 1]
```diff
@@ -47,10 +48,10 @@ export const SeoPreviewNudge = ( {
...
 				plan={
 					site &&
-					findFirstSimilarPlanKey( site.plan.product_slug, {
-						type: TYPE_BUSINESS,
-						...( isJetpack ? { term: TERM_ANNUALLY } : {} ),
-					} )
+					findFirstSimilarPlanKey(
+						site.plan.product_slug,
+						isJetpack ? { type: TYPE_SECURITY_DAILY, term: TERM_ANNUALLY } : { type: TYPE_BUSINESS }
+					)
```
Comment (pablinos) [inline client/components/seo/preview-upgrade-nudge/index.jsx:54]: I've left the Jetpack logic in here for now, but we shouldn't be loading this component for Jetpack sites.

File: client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx [hunk 2]
```diff
@@ -298,7 +298,7 @@ export function WPNonProductLineItem( {
 		<div
 			className={ joinClasses( [ className, 'checkout-line-item' ] ) }
 			data-e2e-product-slug={ lineItem.id }
-			data-product-type={ lineItem.id }
+			data-product-type={ lineItem.type }
```
Comment (pablinos) [inline client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx:301]: @sirbrillig I've been trying to fix the end to end tests for this PR and it seems like the failures related to removing a coupon were caused because of [this change to an attribute value](https://github.com/Automattic/wp-calypso/pull/49581/files#diff-7dcbfb6b6cb0263c9baa37599f7513ff164d19687374fd507f2c34da36ce1a08L97). Could you check it for me, please?

Comment (sirbrillig) [reply client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx:301]: 🤔  Yes, that seems like a regression on my part. `data-product-type` used to be `type` (which is typically either `plan` or the product slug) but here I accidentally changed it to `id`. Thanks for figuring that out and I apologize for the error!

Was there anything else that you were still wondering about?

Comment (pablinos) [reply client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx:301]: Thanks for that @sirbrillig. I just wanted to check my assumptions as I'm not familiar with that part of the codebase, and I definitely didn't want to break the checkout process!

I think that's all you can help me with for now. I've got some theme related tests failing too, which I'm trying to puzzle out, but they're not related to any of your changes.

**Comment by pablinos** [comment]
The Jetpack side of this is being handled in automattic/jetpack#17309
