### PR TITLE
Site Migration: remove back button on variant flow

### LINKED ISSUE #90656: Site Migration: Correct back button functionality
Right now the Back button appears in places where it doesn’t make sense, and when it does, it redirects to the incorrect flow.

### PR DESCRIPTION
**Pull request by andres-blanco**
Closes to https://github.com/Automattic/wp-calypso/issues/90656

## Proposed Changes

Since the new variant flow is standalone, in the sense that it can be accessed directly via URL, I've added this change to hide the `< Back` button when the Identify step is rendered within the hosted-site-migration flow.

## Why are these changes being made?

In order to prevent the Back button appearing in places where it doesn't make sense.

## Testing Instructions

* Apply this PR or go to the calypso.live link
* Navigate to `/setup/hosted-site-migration`
* Verify you don't see the `< Back` button on top-left
* Navigate to `/start` and go through the flow until you get to `/setup/site-migration`
* Verify you see the `< Back` button

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-identify/index.tsx [hunk 1]
```diff
@@ -96,7 +96,10 @@ const SiteMigrationIdentify: Step = function ( { navigation } ) {
 	);
 
 	const urlQueryParams = useQuery();
-	const isEntrepreneurSignup = urlQueryParams.get( 'ref' ) === 'entrepreneur-signup';
+	const shouldHideBack = () => {
```
Comment (markbiek) [inline client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-identify/index.tsx:99]: Not a blocker!

We have a bunch of `is<whatever>Flow` function in [flows.ts](https://github.com/Automattic/wp-calypso/blob/trunk/packages/onboarding/src/utils/flows.ts).

Would it be worth creating a new function for this flow?

**Review by markbiek — APPROVED** [review]
LGTM!

File: client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-identify/index.tsx (hunk 1 above)
Comment (andres-blanco) [reply client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-identify/index.tsx:99]: I am not sure what's the story behind `entrepreneur-signup`. It's not listed on the constants in [flows.ts](https://github.com/Automattic/wp-calypso/blob/trunk/packages/onboarding/src/utils/flows.ts).
I think it's better to leave it this way to prevent opening a can of worms.

Comment (markbiek) [reply client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-identify/index.tsx:99]: Makes sense to me. I wondered about `entrepreneur-signup` too.
