### PR TITLE
Purchases: Adjust modal message when deleting a Domain Mapping subscription. 

### LINKED ISSUE #49043: Mappings: Confusing Message When Removing It
#### Steps to reproduce the behavior
1. Go to Manage > Domains on a site where you have a mapping upgrade
2. Click on 'Delete domain mapping'

#### What I expected to happen
To maybe show a message to confirm the mapping removal, with a warning that the site will stop loading with it - something like that.

#### What actually happened
It asks for a reason to be removed, and warns that you won't be able to use it again without getting a plan - although the site is already on a plan and mappings are free and unlimited.

#### Screenshot / Video
From a site with a Personal plan:

RemovingMapping

#### Context
Confusion reported by user on 3644230-zd-woothemes

### PR DESCRIPTION
**Pull request by chrisfromthelc**
#### Changes proposed in this Pull Request

* As suggested in #49043, this PR will adjust the messaging when deleting a Domain Mapping subscription in order to better communicate the ramifications of removing it.

#### Testing instructions

1. Add a domain mapping to any plan.
2. Navigate through Upgrades > Domains > click on the domain mapping.
3. Click Delete Domain Mapping at the bottom.

You should be presented with a modal showing an updated message:

> Are you sure you want to remove `DOMAIN` from `SITEADDRESS`? You will not be able to reuse `DOMAIN` again without starting a new Domain Mapping subscription.

Screen Shot 2021-08-11 at 3 38 15 PM

Related to #49043

### CODE REVIEW

File: client/me/purchases/remove-purchase/index.jsx [hunk 1]
```diff
@@ -262,8 +269,11 @@ class RemovePurchase extends Component {
 						} )
 					}{ ' ' }
 					{ translate(
-						'You will not be able to reuse it again without purchasing a new subscription.',
-						{ comment: "'it' refers to a product purchased by a user" }
+						'You will not be able to reuse %(productName)s again without starting a new %(domainProductName)s subscription.',
```
Comment (DavidRothstein) [inline client/me/purchases/remove-purchase/index.jsx]: This code runs for more than just domain products, so `domainProductName` is probably not the best variable name.  But also, the wording doesn't seem to work well for those.  Here's what I get when removing a plan with this pull request:

remove-plan

It's a big repetitive :smile: 

I still wonder if we might be better borrowing text from the remove+refund case instead.  I'll comment on the issue with more details about that.

**Review by DavidRothstein — COMMENTED** [review]
Thanks for working on this!

File: client/me/purchases/remove-purchase/index.jsx (hunk 1 above)
Comment (chrisfromthelc) [reply client/me/purchases/remove-purchase/index.jsx]: Yeah, I don't like that either... I _thought_ this was catching just the domain mapping, but I see that I need to relook at this.

**Comment by chrisfromthelc** [comment]
@DavidRothstein After thinking on this further and digging around a bit more this evening, I'm wondering if it might be advantageous to treat removing a mapping like we would a registered domain. The registered domain code handling the deletion messaging has a series of checks to see if the user's account email is based on the deleting domain, if there is Titan email for the domain, etc.

https://github.com/Automattic/wp-calypso/blob/trunk/client/me/purchases/remove-purchase/remove-domain-dialog/index.jsx

I have encountered a number of users who have deleted/let expire a domain mapping where there were secondary effects like these, so it seems prudent to take similar steps like we would with a registered domain. We can have a customized modal/flow for mapping and rework the other text (what was originally to be changed with this PR) to something that works better for the other products.

**Comment by DavidRothstein** [comment]
@chrisfromthelc - hm, interesting idea!  I guess it's true that removing a domain mapping is similarly destructive to a site as removing a domain registration.  (Although the main difference is that removing a domain mapping is easier to recover from if you do it by mistake.)

In principal I do think something like this could work and would make sense, but I wonder how much effort is involved.  It seems to me like it would probably be a lot harder than just changing the text of the existing dialog... So overall, I don't know :shrug:

**Comment by chrisfromthelc** [comment]
> In principal I do think something like this could work and would make sense, but I wonder how much effort is involved. 

Since this isn't a very urgent issue, I'm looking into this to see what I can figure out, and it'll be a good learning experience on building out this kind of functionality.

**Comment by chrisfromthelc** [comment]
I reworked this, adding a new render for Domain Mapping specifically:

Screen Shot 2021-08-30 at 3 31 06 PM

The plans modal will have the original version of the message:

Screen Shot 2021-08-30 at 3 30 43 PM

We can tweak the messaging further if needed, but now that they're completely separated, we don't need to genericize the text as much as originally planned.

File: client/lib/purchases/index.js [hunk 2]
```diff
@@ -110,6 +110,9 @@ function getDisplayName( purchase ) {
 	if ( jetpackProductsDisplayNames[ purchase.productSlug ] ) {
 		return jetpackProductsDisplayNames[ purchase.productSlug ];
 	}
+	if ( isDomainRegistration( purchase ) || isDomainMapping( purchase ) ) {
```
Comment (michaeldcain) [inline client/lib/purchases/index.js]: This short-circuits the logic in [`getName()`](https://github.com/Automattic/wp-calypso/pull/55399/files#diff-89dba582c1178a5762fc60571795ac7d29184270129c1d265ca85cdfe755815bR100), and `getDisplayName()` is used in a few different places in the code where I think they intentionally want the domain name to show (instead of the product name).

**Review by michaeldcain — CHANGES_REQUESTED** [review]

File: client/lib/purchases/index.js (hunk 2 above)
Comment (chrisfromthelc) [reply client/lib/purchases/index.js]: This appears to be a remnent of a previous attempt; it's been removed and in `renderDomainMappingDialogText()`, it's calling `purchase.productName` instead, in order to show "Domain Connection" (or whatever this may be called in the future).

File: client/me/purchases/remove-purchase/index.jsx [hunk 3]
```diff
@@ -251,10 +305,14 @@ class RemovePurchase extends Component {
 							//{ components: { domain: <em>{ getIncludedDomain( purchase ) }</em> } }
 						} )
 					}{ ' ' }
-					{ translate(
-						'You will not be able to reuse it again without purchasing a new subscription.',
-						{ comment: "'it' refers to a product purchased by a user" }
-					) }
+					{ isDomainRegistration &&
+						translate(
+							'You will not be able to reuse it again without starting a new subscription.',
```
Comment (a8ci18n) [inline client/me/purchases/remove-purchase/index.jsx:301]: :ok: This change will be queued for retranslation. We'll use the existing translations in the meantime.

File: client/me/purchases/remove-purchase/index.jsx [hunk 4]
```diff
@@ -207,6 +213,53 @@ class RemovePurchase extends Component {
...
+	renderDomainMappingDialogText() {
+		const { purchase, translate } = this.props;
+		const productName = getName( purchase );
+		const domainProductName = purchase.productName;
+
+		return (
+			<div>
+				<p>
+					{
+						/* translators: "productName" is a product name (in this case, Domain Mapping). "domain" is something like example.wordpress.com */
```
Comment (michaeldcain) [inline client/me/purchases/remove-purchase/index.jsx]: I think this translator comment is incorrect. `productName` in this message is the domain name.

This isn't the fault of the PR, but rather the complex way we handle domain product naming. I think the variables could be cleared up here. Can you do the following: 

- update the variable on L235 to be `domainName` since this render is very specific (and `productName` followed by a different variable that is set with `purchase.productName` is somewhat confusing) 
- update the translation component to be `site` (instead of `domain`)
- update the translators comment to reflect the variable naming
- remove the `if we want to use the purchased domain…` comment

Then, in the next translation string (L251):

- make the translator comment format consistent between the two strings (either as a `comment` parameter or a `/* translators:` comment block - I think the latter is preferred now)
- remove the unused `productName` arg from this.

Also, it's not really important, but I believe that the "Domain Mapping" product name was updated to "Domain Connection" this week by the Domains team, so while you're in there, you might want to change the comment strings (I'd leave the function naming alone, since our codebase still refers to the product almost exclusively as domain mapping - it's more a display name change).

File: client/me/purchases/remove-purchase/index.jsx [hunk 5]
```diff
@@ -251,10 +305,14 @@ class RemovePurchase extends Component {
...
 					}{ ' ' }
-					{ translate(
-						'You will not be able to reuse it again without purchasing a new subscription.',
-						{ comment: "'it' refers to a product purchased by a user" }
-					) }
+					{ isDomainRegistration &&
+						translate(
+							'You will not be able to reuse it again without starting a new subscription.',
+							{
+								args: { productName, domainProductName },
```
Comment (michaeldcain) [inline client/me/purchases/remove-purchase/index.jsx]: These arguments aren't needed.

**Review by michaeldcain — CHANGES_REQUESTED** [review]

File: client/me/purchases/remove-purchase/index.jsx (hunk 5 above)
Comment (chrisfromthelc) [reply client/me/purchases/remove-purchase/index.jsx]: Removed.

File: client/me/purchases/remove-purchase/index.jsx (hunk 4 above)
Comment (chrisfromthelc) [reply client/me/purchases/remove-purchase/index.jsx]: These suggestions are done.

**Comment by jjchrisdiehl** [comment]
Tested - looks good to me:

Domain mapping

image

Plans

image

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6546680

Thank you @chrisfromthelc for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6546680).
