### PR TITLE
Plugins update manager: Fix plugin matching issue (missing .php extension)

### LINKED ISSUE #88310: FE: Extend the plugin name with .php extension
Context: p1709831390891799-slack-C01A60HCGUA

### PR DESCRIPTION
**Pull request by bogiii**
Closes https://github.com/Automattic/wp-calypso/issues/88310

## Proposed Changes

* Fixed the issue with matching the plugin name because of the missed extension

## Testing Instructions

* Go to `/plugins/scheduled-updates/{ATOMIC_SITE}`
* List/add/update schedules
* Check if plugin selection works well in the edit mode
* Check if the tooltip shows selected plugins

| Before | After |
|--------|--------|
| Screenshot 2024-03-08 at 12 50 00 | Screenshot 2024-03-08 at 12 50 08 |
| Screenshot 2024-03-08 at 12 50 19 | Screenshot 2024-03-08 at 12 50 28 | 

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/data/plugins/use-core-plugins-query.ts [hunk 1]
```diff
@@ -24,17 +24,27 @@ export type CorePluginsResponse = CorePlugin[];
...
+		let _plugins = decodeEntitiesFromPlugins( plugins );
+
+		if ( hideManagedPlugins ) {
+			_plugins = _plugins.filter( ( plugin ) => ! plugin.is_managed );
+		}
+
+		if ( addPluginExtension ) {
+			_plugins = _plugins.map( ( plugin ) => ( {
+				...plugin,
+				plugin: `${ plugin.plugin }.php`,
```
Comment (ouikhuan) [inline client/data/plugins/use-core-plugins-query.ts]: Not a blocker and I think this probably won't happen but should we be extra safe and check if the extension is already existed before appending it?

**Review by ouikhuan — APPROVED** [review]
LGTM!

File: client/data/plugins/use-core-plugins-query.ts (hunk 1 above)
Comment (bogiii) [reply client/data/plugins/use-core-plugins-query.ts]: Good suggestion. I'll add it. 👌

File: client/blocks/plugins-update-manager/hooks/use-prepare-plugins-tooltip-info.tsx [hunk 2]
```diff
@@ -1,16 +1,15 @@
...
-	const { data: pluginsData } = useSitePluginsQuery( siteSlug );
-	const plugins = pluginsData?.plugins ?? [];
+	const { data: plugins = [] } = useCorePluginsQuery( siteSlug, true, true );
 
 	const preparePluginsTooltipInfo = ( pluginsArgs: string[] ) => {
 		const pluginsList = pluginsArgs
 			.map(
 				( plugin: string ) =>
-					plugins.find( ( { name }: SitePlugin ) => name === plugin )?.display_name
+					plugins.find( ( { plugin: _plugin }: CorePlugin ) => _plugin === plugin )?.name
```
Comment (obenland) [inline client/blocks/plugins-update-manager/hooks/use-prepare-plugins-tooltip-info.tsx:12]: Rather than going through the trouble of adding `.php` to all plugins in the response, could we just remove `.php` from the args list here before comparing it?

Comment (bogiii) [reply client/blocks/plugins-update-manager/hooks/use-prepare-plugins-tooltip-info.tsx:12]: Ups, I didn't see your comment, but I have merged it to the trunk.

There are two places in the module where we need to map the plugins with the extension. That's why I thought that it is better to have an optional param to do it in a single place.
