### PR TITLE
Site Settings: Display activation banner when Stats module is disabled

### LINKED ISSUE #13647: Site Settings: Make the stats settings card show that the module is inactive
When the stats module is inactive, we're still shown a sort of success message about stats being collected.

#### Steps to reproduce
1. Deactivate the stats module in your Jetpack site.
2. Get to http://calypso.localhost:3000/settings/traffic.
3. Choose one or your jetpack sites.
4. Confirm that you see the same message as in the screenshot.

#### What I expected

To not be shown an optimistic message about stats being working if the module is inactive

#### What happened instead

The message `Collecting valuable traffic stats and insights` still shows.

#### Screenshot

image

The Jetpack admin page shows this:

image

statsinactive

### PR DESCRIPTION
**Pull request by tyxla**
Currently, when the Stats module is disabled, the Stats card under Traffic settings for Jetpack sites will incorrectly display that stats are enabled. Also, there isn't a way to enable the Stats module. 

This PR handles this case by displaying a banner with activation button when the module is disabled. It also improves the card by rendering a placeholder in two cases: while loading module data, and while activating the module. Fixes #13647.

This approach was suggested in p6TEKc-1ca-p2 by @MichaelArestad.

Preview - stats module enabled:

Preview - stats module disabled:

Preview - placeholder while data is loading or stats module being activated

This PR includes #14109 in it, as currently the `<Banner />` does not allow us to use the `event` in the `onClick` handlers, and it redirects to the plans page by default.

To test:
* Checkout this branch or get it going live.
* Go to `/settings/traffic/$site` where `$site` is one of your Jetpack sites.
* Verify you're seeing the placeholder while the data is loading.
* When Stats module is disabled, verify you see the activation banner.
* Verify the activation button works properly, and you are presented with the placeholder while the module is being activated.
* When the Stats module is enabled, verify you see the stats card.
* Verify there are no regressions with the Stats card.

**Hint:** Want to quickly disable the Stats module on your Jetpack site? Use the following WP CLI command: `wp jetpack module deactivate stats`

/cc @Automattic/jetpack as they'll be implementing this in Jetpack

### CODE REVIEW

**Comment by michelleweber** [comment]
For the enabled state, I'd like to see it actually say that in the description: "Enabled! You'll collecting valuable data and insights."

I'd also like to avoid using "stats" in the description in favor of more the specific language, so for the disabled state: "Enable this to see detailed information about your traffic, likes, comments, and subscribers."

File: client/my-sites/site-settings/jetpack-site-stats.jsx [hunk 1]
```diff
@@ -59,6 +63,14 @@ class JetpackSiteStats extends Component {
 		};
 	};
 
+	handleStatsActivationButton = ( event ) => {
+		const { siteId } = this.props;
+
+		this.props.activateModule( siteId, 'stats' );
+
+		event.preventDefault();
```
Comment (sirreal) [inline client/my-sites/site-settings/jetpack-site-stats.jsx]: I think convention would put this at the top, but no big deal.

**Comment by tyxla** [comment]
@michelleweber thanks for chiming in! I've updated the copy as follows:

> For the enabled state, I'd like to see it actually say that in the description: "Enabled! You'll collecting valuable data and insights."



> I'd also like to avoid using "stats" in the description in favor of more the specific language, so for the disabled state: "Enable this to see detailed information about your traffic, likes, comments, and subscribers."



With these changes, are we good, copy-wise?

**Comment by michelleweber** [comment]
All good! I'm removing the "needs copy review" label, but ping if there's anything else I can help with :)

**Comment by tyxla** [comment]
I appreciate your help @michelleweber 🙇

**Comment by MichaelArestad** [comment]
This looks great! 🚢
