### PR TITLE
Editor: Images can now be uploaded from URLs with query-string parameters.

### LINKED ISSUE #3817: Editor: can't upload image from URL if the URL has a query string component
#### Steps to reproduce
1. Starting at URL: New Post/Editor
2. Click to add an image (via URL)
3. Try a URL like http://i.imgur.com/xuhVEIN.png?2 (This is the kind of URL Imgur might give you for the "direct link"

#### What I expected
To be able to upload the image without editing the URL

#### What happened instead
not supported error

Removing the query string from the URL makes it work properly

#### Browser / OS version
Chrome Version 49.0.2623.75 (64-bit) on Mac OS X 10.11

### PR DESCRIPTION
**Pull request by DanReyLop**
Fixes #3817 

Current (production) situation: URL validation when uploading a media file from an URL is performed as if were a file path.

First example:
- URL: `http://foo.bar/something?f=path/to/imageName.png`
- Detected file name: `imageName.png`
- Detected extension: `png`
- Detected MIME type: `image/png`

Second example:
- URL: `http://foo.bar/path/to/imageName.png?12345`
- Detected file name: `imageName.png?12345`
- Detected extension: `png?12345`
- Detected MIME type: `undefined`

Therefore, the first URL is detected as valid, and the second as invalid, since `png?12345` is not a whitelisted extension in the WordPress configuration.

I've changed the logic so that the query-string (and hash, if any) are stripped before parsing the URL as if it were a file path. This would have the "opposite" result, allowing URLs like the second example, but rejecting URLs like the first example. We know that `imgur` uses the second format, so allowing it is a big win. Does anyone know any image hosting site that uses the first format (put the file name in the query-string)?

The perfect solution would be validating server-side, the same as we are throwing an error if the URL gives a 404. After all, `http://foo.bar/somethingWithoutExtension` can perfectly be a valid image file, but the only way of knowing it is to make a HEAD request to get the MIME-type, and that's not possible client-side due to the same-origin limitation.

What do you think? Good enough as it is, or should we implement server-side validation?

### CODE REVIEW

**Comment by aduth** [comment]
>The perfect solution would be validating server- side

Yeah, under the hood WordPress uses [`getimagesize`](http://php.net/manual/en/function.getimagesize.php) if available in [`wp_check_filetype_and_ext`](https://codex.wordpress.org/Function_Reference/wp_check_filetype_and_ext) to try to extract the "real" mime type, so would likely happily accept such a file. There's a bit of a balance here between client-side reactivity (presenting error as soon as possible) with accuracy. Since these cases are pretty rare, we chose to optimize for the former.

File: client/lib/media/actions.js [hunk 1]
```diff
@@ -116,13 +117,18 @@ MediaActions.add = function( siteId, files ) {
...
 
-		if ( 'string' === typeof file ) {
-			// Generate from string
+		// Determine upload mechanism by object type
+		const isUrl = 'string' === typeof file;
+		const addHandler = isUrl ? 'addMediaUrls' : 'addMediaFiles';
+
+		if ( isUrl ) {
+			// Generate from URL
+			const filePath = url.parse( file ).pathname;
```
Comment (aduth) [inline client/lib/media/actions.js]: I feel as though we should enhance the existing `MediaUtils` helpers to pull the correct extension from the path name, since other usages will still be susceptible to the issues we've experienced here (it's also easier to add [test cases](https://github.com/Automattic/wp-calypso/blob/master/client/lib/media/test/utils.js)).

In the course of doing so, we may need to add a new method `MediaUtils.getFileExtension`.

**Comment by DanReyLop** [comment]
Ok, so if you are aware of the limitations of client-side validation and that's a conscious decision, it's fine for me :)

I will rewrite it as suggested, add tests, and update the PR.

Just a silly question: should I ammend the commit and force-push? That's usually the flow with git repos, but I prefer to ask before force-pushing to a repo that's not mine :)

**Comment by aduth** [comment]
>Just a silly question: should I ammend the commit and force-push? That's usually the flow with git repos, but I prefer to ask before force-pushing to a repo that's not mine :)

Not a silly question. Up to you in this case. One option is to rebase, edit the commit, then force-push to your branch. Otherwise, you could simply add a new commit, treating the first approach as a useful piece of history, even if effectively reverted by your second commit.

**Comment by DanReyLop** [comment]
@aduth I've made the changes you pointed out and added tests. I opted for doing the force-push, I don't see the 'historical value' on the previous approach :)

File: client/lib/media/test/utils.js [hunk 2]
```diff
@@ -84,6 +84,40 @@ describe( 'MediaUtils', function() {
...
+		it( 'should detect extension from file name', function() {
+			expect( MediaUtils.getFileExtension( 'example.gif' ) ).to.equal( 'gif' );
+		} );
+
+		it( 'should ignore querystring parameters', function() {
+			expect( MediaUtils.getFileExtension( 'example.gif?w=100' ) ).to.equal( 'gif' );
+		} );
+
+		it( 'should detect extension from HTML5 File object', function() {
+			expect( MediaUtils.getFileExtension( new window.File( [''], 'example.gif' ) ) ).to.equal( 'gif' );
```
Comment (aduth) [inline client/lib/media/test/utils.js]: So, I was a bit confused why Babel didn't throw up at this line*, and it seems to be the consequence of some spillover from the `actions.js` test where a fake DOM is initialized but never cleaned up. Once we migrate these tests to a single test runner, this will become apparent in its breakage.

You can see the issue when running the test in isolation with Mocha from the `client/lib/media` folder:

```bash
media (fix/3817-upload-media-url-querystring) $ NODE_ENV=test NODE_PATH=../../../client mocha --compilers js:babel/register test/utils.js 


  MediaUtils
    #getFileExtension()
      1) should detect extension from HTML5 File object


  0 passing (559ms)
  1 failing

  1) MediaUtils #getFileExtension() should detect extension from HTML5 File object:
     ReferenceError: window is not defined
      at Context.<anonymous> (/Users/andrew/Documents/Code/wp-calypso/client/lib/media/test/utils.js:101:21)
      at callFn (/usr/local/lib/node_modules/mocha/lib/runnable.js:250:21)
      at Test.Runnable.run (/usr/local/lib/node_modules/mocha/lib/runnable.js:243:7)
      at Runner.runTest (/usr/local/lib/node_modules/mocha/lib/runner.js:373:10)
      at /usr/local/lib/node_modules/mocha/lib/runner.js:451:12
      at next (/usr/local/lib/node_modules/mocha/lib/runner.js:298:14)
      at /usr/local/lib/node_modules/mocha/lib/runner.js:308:7
      at next (/usr/local/lib/node_modules/mocha/lib/runner.js:246:23)
      at Immediate._onImmediate (/usr/local/lib/node_modules/mocha/lib/runner.js:275:5)
      at processImmediate [as _immediateCallback] (timers.js:383:17)
```

The resolution should be fairly straight-forward. Despite this test not being part of the single test runner, you should still be able to use the [`use-fake-dom` helper](https://github.com/Automattic/wp-calypso/blob/master/test/test/helpers/use-fake-dom/README.md) to initialize a DOM for the duration of this test.

_*_ Because, by default, DOM objects aren't available unless a fake DOM is created.

**Comment by aduth** [comment]
Aside from the one testing note, this looks and works great :+1:

**Comment by DanReyLop** [comment]
Ok, the `actions.js` used already a `window`object (and it already failed using the new test runner), so I didn't give it much thought.

I've fixed that.

**Comment by aduth** [comment]
Tests are failing with latest commit. I believe you'll need to augment the `NODE_PATH` to include the root `test` directory.

**Comment by DanReyLop** [comment]
Right, my bad, I tried running it with the wrong test runner. Should work now.

File: client/lib/media/test/utils.js [hunk 3]
```diff
@@ -84,7 +85,45 @@ describe( 'MediaUtils', function() {
...
+			expect( MediaUtils.getFileExtension( { URL: 'example.gif' } ) ).to.equal( 'gif' );
+		} );
+
+		it( 'should detect extension from object guid property', function() {
+			expect( MediaUtils.getFileExtension( { guid: 'example.gif' } ) ).to.equal( 'gif' );
+		} );
+	} );
+
 	describe( '#getMimePrefix()', function() {
+		useFakeDom();
```
Comment (aduth) [inline client/lib/media/test/utils.js]: If the fake DOM is needed across multiple tests, we should probably move `useFakeDom` to the top-level `describe` block.

Comment (DanReyLop) [inline client/lib/media/test/utils.js]: Done

**Comment by aduth** [comment]
Works and tests well! :+1:
