### PR TITLE
Full Site Editing: make `wp_template` not `public` by default

### LINKED ISSUE #32491: Full Site Editing: restricting access to wp_template CPT [3]
Depends on: https://github.com/Automattic/wp-calypso/issues/32244

We need to audit all of the places that this CPT might pop-up in wrong contexts and make sure to not expose it if it's not necessary (e.g. searches, site list etc).

### PR DESCRIPTION
**Pull request by mattwiebe**
The `public` flag when registering a post type opens it up to all kinds of exposure. Since we only have this in place to support searching through the core endpoint, this simply makes the CPT `public` when in an API endpoint.

We could probably do more robust detection than this to more strictly limit exposure (eg hooking into `WP_Query`) but since it's unlikely that we will continue to use the core search endpoint, this will do fine for now.

#### Changes proposed in this Pull Request

* set the `public` property on the `wp_template` CPT during a REST request

#### Testing instructions

* ensure that searching in the Content Slot and Template Part blocks still works
* look in feeds and frontend search results (and whatever you can think of) for `wp_template` posts (they shouldn't appear)

Fixes #32491

### CODE REVIEW

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php [hunk 1]
```diff
@@ -60,6 +61,21 @@ function register_blocks() {
...
+	 *
+	 * @return void
+	 */
+	function allow_searching_for_templates() {
+		$post_type = get_post_type_object( 'wp_template' );
+		if ( ! is_a( $post_type, 'WP_Post_Type' ) ) {
+			return;
+		}
+		// setting this to `public` will allow it to be found in the search endpoint
+		$post_type->public = true;
```
Comment (Copons) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php]: Interesting!
Code works as expected, but I have to ask: is this kind of mutation an established enough pattern, or is it something that might end up frowned upon when/if we push this into Core?

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php [hunk 2]
```diff
@@ -60,6 +61,21 @@ function register_blocks() {
...
+
+	/**
+	 * This will set the `wp_template` post type to `public` to support
+	 * the core search endpoint, which looks for it.
+	 *
+	 * @return void
+	 */
+	function allow_searching_for_templates() {
+		$post_type = get_post_type_object( 'wp_template' );
+		if ( ! is_a( $post_type, 'WP_Post_Type' ) ) {
```
Comment (obenland) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php]: Do you think using `instanceof` would be an option here? Core usually prefers that over `is_a()`

Comment (dmsnell) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php]: that's awesome to know @obenland - is there an explanation why? the PHP docs weren't clear to me what the differences in behaviors are.

Comment (obenland) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php]: I first thought because it was slightly faster than calling a function, the actual reason was a different one: https://core.trac.wordpress.org/changeset/31188

**Comment by vindl** [comment]
Doesn't seem related to this PR but it meddles with my testing - I'm not able to publish `wp_template` posts with my admin account, only getting `Submit for Review` as an option. Did anyone run into a similar issue?

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php (hunk 2 above)
Comment (mattwiebe) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php]: Thanks for the extra knowledge @obenland - I just assumed this was yet another place where PHP has multiple ways to do the same thing.

**Comment by mattwiebe** [comment]
> I'm not able to publish wp_template posts with my admin account, only getting Submit for Review as an option

I know that @Copons was getting some similar issues back [here](https://github.com/Automattic/wp-calypso/pull/32568#discussion_r278906306). My local test setup is multisite, so I'll try to muck around with a single install.

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php (hunk 1 above)
Comment (mattwiebe) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php]: There are sometimes workarounds somewhat like this in core, but usually what they expose is a need for changes elsewhere, which would generally happen as part of a merge strategy.

**Comment by mattwiebe** [comment]
I was previously testing on a multisite install as the super admin, which kind of defeated the purpose. The missing culprit seems to have been the missing `publish_posts` capability, which I've now added in 137ee626b24939f28412c66a9efe85df4ff3121c.

For those who don't know, running as a regular user in a multisite install is normal and fine (the only difference is that `kses` gets more strict by default, requiring the `unfiltered_html` capability in order to not strip things like `<script>` and `<iframe>` elements), **but** a super_admin automatically has *every capability*.
