### PR TITLE
Store: Product Trash Pickup

### LINKED ISSUE #16218: Store: Display more helpful error messages on product failure
Right now if a product fails to create, we just display a general error message. The WooCommerce Product API does return different error messages depending on what went wrong -- for example a duplicate SKU. We should be able to show more helpful messages in certain situations.

### LINKED ISSUE #20490: Store: Clicking Add Product after editing product description causes crash
When working in the products page, if you edit the product description, click Update, or disregard edits - the subsequently click "Add Product" errors are thrown in the console and the app crashes.

error-add-product

The error only occurs when you interact with the TinyMCE instance on the products page. Updating other data in my testing does not trigger the issue.

Errors in console:
product-errors

Via kibana it appears a few users have been hitting this problem in production. In kibana they are appearing as:

```
Minified React error #40; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=40 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
--
```

### LINKED ISSUE #20774: Store - SKU pencil doesn't activate edit mode
On the add/edit product screen we display a little pencil icon next to the auto-generated SKU. Hovering it changes the appearance but clicking doesn't activate edit mode - you have to click the text instead.

### LINKED ISSUE #21036: Store: Product Name Encoding Entities
product title entities

#### Steps to reproduce
1. Create a new product with an `&` in the name
2. Visit the products listing, note the `&` is displayed as `&amp;`

### PR DESCRIPTION
**Pull request by justinshreve**
This PR does some trash pickup around products. The following issues are addressed:

* Fixes #20774 “SKU pencil doesn't activate edit mode”.
* Fixes #20490 “Clicking Add Product after editing product description causes crash”.
* Fixes #16218 “Show a proper error message when a duplicate SKU is found.”
* Fixes #21036 "Product Name Encoding Entities”.

To Test:

* Run `npm run test-client client/extensions/woocommerce` and make sure all tests pass.
* Go to an existing product and click the pencil icon, verifying that the SKU input becomes editable. Close the input.
* Add an entity ( & ) to your title and click save. Verify that the success message and input field don’t replace your & with &amp;.
* Open your dev console.
* Click “Add” on the sidebar, and verify that you are taken to the add a product form. Verify that the form loads and there is not a huge warning explosion in your console.
* Create a new product and give it a SKU that matches an existing SKU. Save and verify you get the duplicate SKU error message. Change your SKU, save, and verify the product saves.
* When you are redirected to the products list, verify products are correctly listed.

### CODE REVIEW

File: client/extensions/woocommerce/app/products/product-create.js [hunk 1]
```diff
@@ -190,6 +188,10 @@ class ProductCreate extends React.Component {
 		const isBusy = Boolean( actionList ); // If there's an action list present, we're trying to save.
 		const saveEnabled = isValid && ! isBusy && 0 === this.state.isUploading.length;
 
+		if ( ! product || isNumber( product.id ) ) {
```
Comment (timmyc) [inline client/extensions/woocommerce/app/products/product-create.js]: I'm groking the check for `! product` but the second clause has me thinking a bit - so this is to short circuit the `create` view if a `product` exists and is not a placeholder/un-saved product?

File: client/extensions/woocommerce/app/products/product-form-details-card.js [hunk 2]
```diff
@@ -45,7 +45,6 @@ export default class ProductFormDetailsCard extends Component {
 
 		this.setName = this.setName.bind( this );
 		this.setDescription = this.setDescription.bind( this );
-		this.debouncedSetDescription = debounce( this.setDescription, 200 );
```
Comment (timmyc) [inline client/extensions/woocommerce/app/products/product-form-details-card.js]: When trying to track down this bug, this did jump out at me - what was the original reason for this logic?

File: client/extensions/woocommerce/app/products/product-create.js (hunk 1 above)
Comment (justinshreve) [reply client/extensions/woocommerce/app/products/product-create.js]: Yeah.

I found in testing, the few actions that clear away edits in product UI state, variations, etc (which also resets `currentlyEditingId` and this `product` object) might not have all ran yet before the component mounts. And because of how the CompactTinyMCE component works, (it only an initial value), this is needed to prevent rendering of the form in that brief moment of time. Once the prop updates the form renders.

File: client/extensions/woocommerce/app/products/product-form-details-card.js (hunk 2 above)
Comment (justinshreve) [reply client/extensions/woocommerce/app/products/product-form-details-card.js]: I'm not sure now, sorry.  It doesn't seem necessary from the testing I did though.

Comment (timmyc) [reply client/extensions/woocommerce/app/products/product-form-details-card.js]: Looks like it was added in here #14944 though i don't see any details around that specific bit. I think this might be some carry-over from patterns in the post editor maybe. But I agree if its not needed, it is great to remove it.
