### PR TITLE
Settings: fix security support links

### LINKED ISSUE #59975: Replace SSO Jetpack Doc with WordPress.com Doc
### Quick summary

On WordPress.com atomic sites, the WordPress.com Log In settings (SSO) links to a Jetpack doc. It is more helpful to link to the WordPress.com doc because this contains information specific to a .com website.

### Steps to reproduce

1. Go to Settings > Security
2. Under WordPress.com log in, click the (i) icon.
3. View the Learn More and Privacy Information links.

"Learn more" should link to https://wordpress.com/support/wordpress-com-secure-sign-on-sso/

"Privacy Information" can be removed for WordPress.com sites.

### What you expected to happen

I expected to be taken to a WordPress.com help resource.

### What actually happened

I arrived at a Jetpack doc for self-hosted sites, https://jetpack.com/support/sso/

image

### Context

_No response_

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

_No response_

### Browser, operating system and other notes

_No response_

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by arcangelini**
## Changes proposed in this Pull Request
Similar to the other fixes ( #60962, #61175 ) this uses the `siteIsAutomatedTransfer` prop with a ternary operator to change links depending on the context. I also changed `isAtomic` to `siteIsAutomatedTransfer` to match the naming in the other setting components.

There was also an error with the check for `isAtomic`, the selector needed to have the state passed along with the siteId. This was causing the check to return `NULL` and showing this when it shoudln't have:

#### Before
Markup 2022-02-17 at 11 56 23

#### After
Markup 2022-02-17 at 12 03 06

## Testing instructions
1. Load the branch and launch calypso `yarn start`
2. Go to Settings ⇢ Security
3. Click the `( i )` and verify the links all work as explained
4. Make sure the Akismet section is only showing for JPOP sites
5. Repeat the test with Simple, Atomic, and Jetpack sites

Fixes #59975

### CODE REVIEW

File: client/my-sites/site-settings/form-security.jsx [hunk 1]
```diff
@@ -96,7 +97,7 @@ class SiteSettingsFormSecurity extends Component {
 
 const connectComponent = connect( ( state ) => {
 	const siteId = getSelectedSiteId( state );
-	const isAtomic = isSiteAutomatedTransfer( siteId );
+	const siteIsAutomatedTransfer = isSiteAutomatedTransfer( state, siteId );
```
Comment (chriskmnds) [inline client/my-sites/site-settings/form-security.jsx]: We have a lot of instances of `isAtomic` throughout the repo - most stemming from a call to `isSiteAutomatedTransfer`, and a couple that derive this from site options. If we feel this is something that needs a refactor, then might be best to do it holistically maybe. Not sure if it's the right decision though:

1. The selector could have been named anything. The inference from it seems to be the "atomic" status of a site.
2. I feel `isAtomic` may have evolved into a bit of a de facto convention, as `siteIsAutomatedTransfer` only appears in these two other files modified 4 years ago.

Naming is hard! What is more acceptable: "atomic site" or "automated transfer site"?

Comment (arcangelini) [reply client/my-sites/site-settings/form-security.jsx]: Ahh haha those were the two files that I was working on it seems. I got this backward. I will undo that piece.

File: client/my-sites/site-settings/sso.jsx [hunk 2]
```diff
@@ -81,6 +87,8 @@ Sso.defaultProps = {
 };
 
 Sso.propTypes = {
+	isAtomic: PropTypes.bool,
+	siteIsJetpack: PropTypes.bool,
```
Comment (chriskmnds) [inline client/my-sites/site-settings/sso.jsx]: This is not used anywhere right now. Something we meant to use for removing the privacy section?

**Review by chriskmnds — COMMENTED** [review]
Thanks @arcangelini . I checked with my atomic site and it works as advertised. Looks like this is not relevant to simple sites though right (no security settings page there)?

Also, this part from the GH issue, should we address here as well?

> "Privacy Information" can be removed for WordPress.com sites.

**Comment by arcangelini** [comment]
> Also, this part from the GH issue, should we address here as well?

Great question... I was operating under the instructions given in one of the other GH issues - #59976

>Also, emphasizing that we only want to change link for Learn More, the links for Privacy Information can stay as is.

I have made a comment in one of the [other GH issues](https://github.com/Automattic/wp-calypso/issues/59977#issuecomment-1042937076) to see how to handle all these uniformly.

File: client/my-sites/site-settings/sso.jsx [hunk 3]
```diff
@@ -32,7 +33,12 @@ const Sso = ( {
 						text={ translate(
 							'Allows registered users to log in to your site with their WordPress.com accounts.'
 						) }
-						link="https://jetpack.com/support/sso/"
+						link={
+							isAtomic
+								? 'https://wordpress.com/en/support/wordpress-com-secure-sign-on-sso/'
+								: 'https://jetpack.com/support/sso/'
+						}
+						privacyLink={ isAtomic }
```
Comment (alshakero) [inline client/my-sites/site-settings/sso.jsx]: You know this by now, this only accepts `string`, `false`, and `undefined`. `true` breaks it.

**Review by alshakero — CHANGES_REQUESTED** [review]

**Comment by arcangelini** [comment]
rebased to get changes to `SupportInfo` component and tested again. Everything is working as expected now. #61260 

| Jetpack | Atomic |
| - | - |
| Markup 2022-02-22 at 11 48 21 | Markup 2022-02-22 at 11 48 50 |

File: client/my-sites/site-settings/sso.jsx (hunk 3 above)
Comment (arcangelini) [reply client/my-sites/site-settings/sso.jsx]: Updated in this PR #61260

**Review by alshakero — APPROVED** [review]
LGTM!
