### PR TITLE
Redirect to previous page when closing cart on hosted site migration

### LINKED ISSUE #93851: Migrate flow: Checkout close button does not work
### Quick summary

This issue was previously reported in pcmemI-3dx-p2#comment-2406.

### Steps to reproduce

1. Go to wordpress.com/move
2. Enter a website you want to migrate, say https://lexfridman.com/.
3. Create a new account, go through the flow, select the Business plan, and land on checkout.
4. Click on the `X` close button

Related:
Empty cart and click on "Go back":
Screenshot 2024-08-23 at 11 51 10 AM

### What you expected to happen

* The checkout page should close when clicking the button.
* The checkout page should navigate away when clicking "Go back"

### What actually happened

Nothing happened on clicking the button. Check pcmemI-3dx-p2#comment-2406 for a video recording.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by TimBroddin**
Closes #93851

## Proposed Changes

When initiating the hosted site migration flow from wordpress.com/move the close button of the cart doesn't work. This is because the flow gets opened in a new tab, which causes this to be true and return:

```
if (
		siteSlug &&
		sendMessageToOpener( siteSlug, 'checkoutCancelled' ) &&
	) {
		return;
	}
```

This PR adds an extra check:

```
if (
		siteSlug &&
		sendMessageToOpener( siteSlug, 'checkoutCancelled' ) &&
		signupFlowName !== 'hosted-site-migration'
	) {
		return;
	}
``` 

This will still send the message to opener (in case the behavior is needed), but will not return when the flow is `hosted-site-migration` and will go back to the previous page. 

@andres-blanco since you created the flow, would you mind taking a look at this PR?

An alternative approach would be to add a direct comparison ( `window.opener.location.href.includes("wordpress.com/move)` in leaveCheckout.

## Why are these changes being made?

*

## Testing Instructions

1. Launch Calypso.
2. Use this JSBin to enter the flow in a new window: https://jsbin.com/fusofahejo/edit?html,output 
3. Select "Create a new one", "Migrate site", "I'll do it myself" & "Get the plan & migrate"
4. When presented with the cart, click on the close button
5. You should be redirected to the previous page.

CleanShot 2024-08-23 at 08 25 58@2x

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by miksansegundo — APPROVED** [review]
LGTM 👍 

### Before

https://github.com/user-attachments/assets/22ecdf6e-4c6c-443e-addc-82098f19d236

### After

https://github.com/user-attachments/assets/ec1216f6-fd1e-46a1-9b7b-1e62a71f84cb

**Comment by TimBroddin** [comment]
@andres-blanco Do you want to do a quick check to see if this is fine to merge?

**Comment by miksansegundo** [comment]
cc: @Automattic/serenity

**Review by andres-blanco — APPROVED** [review]
Changes look good. I confirmed that the bug can be reproduced and that it doesn't happen when following the testing instructions.

**Review by paulopmt1 — APPROVED** [review]
Working as expected. Deploying it...

**Review by jjchrisdiehl — APPROVED** [review]
LGTM 👍

File: client/my-sites/checkout/src/lib/leave-checkout.ts [hunk 1]
```diff
@@ -38,7 +38,11 @@ export const leaveCheckout = ( {
 	const launchpadURLRegex = /^\/setup\/[a-z][a-z\-_]*[a-z]\/launchpad\b/g;
 	const launchpadURLRegexMatch = redirectToParam?.toString().match( launchpadURLRegex );
 
-	if ( siteSlug && sendMessageToOpener( siteSlug, 'checkoutCancelled' ) ) {
+	if (
+		siteSlug &&
+		sendMessageToOpener( siteSlug, 'checkoutCancelled' ) &&
+		signupFlowName !== 'hosted-site-migration'
```
Comment (gabrielcaires) [inline client/my-sites/checkout/src/lib/leave-checkout.ts]: Can we use the const names instead of the hardcoded ones they are on '@automattic/onboarding'
 and include `migration` as another exception
E.g. 
import { MIGRATION_FLOW } from '@automattic/onboarding';

**Review by gabrielcaires — APPROVED** [review]
