### PR TITLE
New Onboarding: fix /new/free flow

### LINKED ISSUE #49391: New onboarding: /new/free flow is not working
### Steps to reproduce the behavior

1. Go to wordpress.com/new/free?fresh
2. Advance through the flow

#### What I expected to happen
Free plan to be pre-selected and Plans step to be skipped by default. More details in https://github.com/Automattic/wp-calypso/pull/48115

#### What actually happened
The `/free` path in the URL was ignored so the experience is the same as landing on `/new`

### Context
Related to changes in Plans data-store: https://github.com/Automattic/wp-calypso/pull/48790

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
The results of pbxNRc-xd-p2 experiment will be affected.

### PR DESCRIPTION
**Pull request by razvanpapadopol**
#### Changes proposed in this Pull Request

* When Plans data-store was refactored, `getPlanByPath` selector was also [modified](https://github.com/Automattic/wp-calypso/pull/48790/files#diff-fe3f8145013cbb4868d1e345357357b4f1564e6c1c194ad20eec492fa402bb34R111-R125) and now it uses path slugs returned from the API. Since there is no slug in the API response for Free plan, we can return `'free'` in the resolver.

#### Testing instructions

* Go to /new/free
* Advance through the flow. Free plan should be displayed as selected in top-right corner and Plans step shouldn't be mandatory if you pick a free domain and skip Features step. See more details in #48115

Fixes #49391

### CODE REVIEW

File: packages/data-stores/src/plans/test/resolvers.ts [hunk 1]
```diff
@@ -116,7 +116,7 @@ describe( 'getSupportedPlans', () => {
 				{
 					annualPrice: '₹0',
 					billingPeriod: 'ANNUALLY',
-					pathSlug: undefined,
+					pathSlug: 'free',
```
Comment (razvanpapadopol) [inline packages/data-stores/src/plans/test/resolvers.ts:119]: Ok to use a string directly here since the response is typed: https://github.com/Automattic/wp-calypso/blob/trunk/packages/data-stores/src/plans/types.ts#L34

File: packages/data-stores/src/plans/resolvers.ts [hunk 2]
```diff
@@ -110,7 +110,7 @@ function normalizePlanProducts(
 			periodAgnosticSlug: periodAgnosticPlan.periodAgnosticSlug,
 			storeSlug: planProduct.product_slug,
 			rawPrice: planProduct.raw_price,
-			pathSlug: planProduct.path_slug,
+			pathSlug: planProduct.product_slug === 'free_plan' ? 'free' : planProduct.path_slug,
```
Comment (razvanpapadopol) [inline packages/data-stores/src/plans/resolvers.ts]: Ok to use the `'free'` string directly here since the response is typed: https://github.com/Automattic/wp-calypso/blob/trunk/packages/data-stores/src/plans/types.ts#L34

**Review by ciampo — APPROVED** [review]
LGTM — ~Let's just wait for #48963 to be merged, in case there's any conflicts~ Good to go!
