### PR TITLE
Masterbar: Better descriptive text for Gravatar icon

### LINKED ISSUE #34800: Improve Gravatar alt-text
#### Steps to reproduce
1. Login to WordPress.com
2. Right-click to inspect gravatar
3. Note alt-text is "Me"

#### What I expected
The alt-text to be descriptive of the image, like "image of _username_".

#### What happened instead
The alt-text reads "Me". This lack clarity out of context.

#### Browser / OS version
All

#### Screenshot / Video

```Me```

### PR DESCRIPTION
**Pull request by sixhours**
#### Changes proposed in this Pull Request

* Updates the alt text and accompanying menu item label from "Me" to "My Profile" since this is a more descriptive name for the page which the Gravatar links to. Contextual note in the code suggests this needs to be less than 12 characters and "My Profile" is 10 characters.

Screen Shot 2019-08-06 at 10 55 46 AM

Screen Shot 2019-08-06 at 10 54 55 AM

#### Testing instructions

* Switch to this PR and log in
* Check the source for the Gravatar image in the masterbar 

Fixes #34800

### CODE REVIEW

File: client/layout/masterbar/logged-in.jsx [hunk 1]
```diff
@@ -149,9 +149,9 @@ class MasterbarLoggedIn extends React.Component {
 					tooltip={ translate( 'Update your profile, personal settings, and more' ) }
 					preloadSection={ this.preloadMe }
 				>
-					<Gravatar user={ this.props.user } alt="Me" size={ 18 } />
+					<Gravatar user={ this.props.user } alt={ translate( 'My Profile' ) } size={ 18 } />
```
Comment (a8ci18n) [inline client/layout/masterbar/logged-in.jsx]: Hi! I've found a possible matching string that has already been translated **73** times:
`translate( 'My Profile' )` *ES Score: 10*

Help me improve these suggestions: react with :thumbsdown: if the suggestion doesn't make any sense, or with :thumbsup: if it's a particularly good one (even if not implemented).

:information_source: This **context** is really long. Are you sure you don't want to use a translator comment instead?

**Review by donpark — APPROVED** [review]
LGTM

**Comment by donpark** [comment]
I moved it back to Needs Review column because of "Needs i18n Review". Feel free to move it back to "Reviewed" stack when i18n Review is done.

**Review by lcollette — APPROVED** [review]
LGTM!
