### PR TITLE
Stats: Improve Clarity of Marking Spam Text

### LINKED ISSUE #38875: Site Stats: Clarify !Spam Next to Referrer Links
#### Steps to reproduce
1. https://wordpress.com/stats/day/
2. In "Referrers" box, click 3-dots menu next to a link
3. It shows "!Spam" but no context, could be interpreted that this link is already spam
4. The "!Spam" is also clickable, so if you're curious, you might inadvertently mark an innocent link as spam

#### What I expected
Something like "Mark as Spam" would avoid the impression that this is a spam link. 

#### What happened instead
It says "!Spam" and user though their other blog was shows up as spam in people's Referreres

#### Browser / OS version
MacOSX 10.15.2
Chrome 79.0.3945.117

#### Screenshot / Video
image

#### Context / Source
#perspective #user-report #16926970-hc

If requesting a new feature, explain why you'd like to see it added.
-->

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

Prefixes the "Spam" text with "Mark as" for clarity in stats

#### Testing instructions

Visit the Stats page and look at the Referrers column. On a referral with an ellipses Gridicon next to it, click it and compare the text.

**Before:**
Screenshot 2020-01-20 at 20 49 18

**After:**
Screenshot 2020-01-20 at 20 49 00

Then mark the item as spam, and hover over it again to see the other label change.

Screenshot 2020-01-20 at 20 49 43

Fixes #38875

### CODE REVIEW

File: client/my-sites/stats/stats-list/action-spam.jsx [hunk 1]
```diff
@@ -44,22 +44,22 @@ class StatsActionSpam extends React.Component {
 
 	render() {
 		let label = this.state.spammed
-				? this.props.translate( 'Not Spam' )
-				: this.props.translate( 'Spam', {
+				? this.props.translate( 'Mark as Not Spam' )
+				: this.props.translate( 'Mark as Spam', {
```
Comment (a8ci18n) [inline client/my-sites/stats/stats-list/action-spam.jsx]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **137** times:
`translate( 'Mark as Spam', { context: 'site'} )` *ES Score: 11*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/pull/38957)


:information_source: This **context** is really long. Are you sure you don't want to use a translator comment instead?

File: client/my-sites/stats/stats-list/action-spam.jsx [hunk 2]
```diff
@@ -44,22 +44,22 @@ class StatsActionSpam extends React.Component {
 
 	render() {
 		let label = this.state.spammed
-				? this.props.translate( 'Not Spam' )
-				: this.props.translate( 'Spam', {
+				? this.props.translate( 'Mark as Not Spam' )
```
Comment (a8ci18n) [inline client/my-sites/stats/stats-list/action-spam.jsx]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **45** times:
`translate( 'Mark as Not Spam' )` *ES Score: 12*


:information_source: This **context** is really long. Are you sure you don't want to use a translator comment instead?

File: client/my-sites/stats/stats-list/action-spam.jsx [hunk 3]
```diff
@@ -37,47 +37,50 @@ class StatsActionSpam extends React.Component {
...
+					textOnly: true,
+					context: 'Stats: Action to undo marking an item as spam',
+					comment:
+						'Secondary label (default label is "Spam"). Recommended to use a very short label.',
+			  } )
+			: this.props.translate( 'Mark as Spam', {
+					textOnly: true,
+					context: 'Stats: Action to mark an item as spam',
+					comment: 'Default label (changes into "Mark as Not Spam").',
+			  } );
```
Comment (Aurorum) [inline client/my-sites/stats/stats-list/action-spam.jsx]: I tried to fix the lint errors by using a Button and changing most of the `lets` to `consts`, but I'm not sure if I should've done that in this PR, which was initially a simple label switch. Just to clarify, these are the labels which were changed. Let me know if I should revert some of the lint fixes I tried to make.

File: client/my-sites/stats/stats-list/action-spam.jsx [hunk 4]
```diff
@@ -37,47 +37,50 @@ class StatsActionSpam extends React.Component {
...
-						context: 'Stats: Action to mark an item as spam',
-						comment: 'Default label (changes into "Not Spam").',
-				  } ),
-			wrapperClass = classNames( 'module-content-list-item-action-wrapper', {
-				spam: ! this.state.spammed,
-				unspam: this.state.spammed,
-			} );
+		const label = this.state.spammed
+			? this.props.translate( 'Mark as Not Spam' )
+			: this.props.translate( 'Mark as Spam', {
```
Comment (a8ci18n) [inline client/my-sites/stats/stats-list/action-spam.jsx]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **137** times:
`translate( 'Mark as Spam', { context: 'site'} )` *ES Score: 11*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/pull/38957)


:information_source: This **context** is really long. Are you sure you don't want to use a translator comment instead?

File: client/my-sites/stats/stats-list/action-spam.jsx [hunk 5]
```diff
@@ -37,47 +37,50 @@ class StatsActionSpam extends React.Component {
...
-						textOnly: true,
-						context: 'Stats: Action to mark an item as spam',
-						comment: 'Default label (changes into "Not Spam").',
-				  } ),
-			wrapperClass = classNames( 'module-content-list-item-action-wrapper', {
-				spam: ! this.state.spammed,
-				unspam: this.state.spammed,
-			} );
+		const label = this.state.spammed
+			? this.props.translate( 'Mark as Not Spam' )
```
Comment (a8ci18n) [inline client/my-sites/stats/stats-list/action-spam.jsx]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **45** times:
`translate( 'Mark as Not Spam' )` *ES Score: 12*


:information_source: This **context** is really long. Are you sure you don't want to use a translator comment instead?

File: client/my-sites/stats/stats-list/action-spam.jsx (hunk 1 above)
Comment (jacoswan) [reply client/my-sites/stats/stats-list/action-spam.jsx]: Design looks great 👍🏼

File: client/my-sites/stats/stats-list/style.scss [hunk 6]
```diff
@@ -558,6 +559,10 @@ ul.module-content-list-item-action-submenu {
 			margin-right: 0;
 		}
 	}
+	
+	.button.module-content-list-item-action-wrapper .gridicon {
+		vertical-align: unset; // 2
```
Comment (bluefuton) [inline client/my-sites/stats/stats-list/style.scss]: I think it'd be more readable if the comment was near the style rule rather than referring to it by number:

```
// When a button instead of a link is used
.button.module-content-list-item-action-wrapper .gridicon {
		vertical-align: unset;
}
```

File: client/my-sites/stats/stats-list/action-spam.jsx (hunk 3 above)
Comment (bluefuton) [reply client/my-sites/stats/stats-list/action-spam.jsx]: Linting changes look good to me 👍

**Comment by bluefuton** [comment]
Thanks for the PR @Aurorum!

I noticed some odd behaviour when testing in Firefox. If the popover is open and you move the mouse away from it, the 'mark as spam' label vanishes:



Can we investigate why this happens?

File: client/my-sites/stats/stats-list/action-spam.jsx [hunk 7]
```diff
@@ -37,47 +37,50 @@ class StatsActionSpam extends React.Component {
...
+			: this.props.translate( 'Mark as Spam', {
+					context: 'Stats: Action to mark an item as spam',
+					comment: 'Default label (changes into "Mark as Not Spam").',
+			  } );
+		const title = this.state.spammed
+			? this.props.translate( 'Mark as Not Spam', {
+					textOnly: true,
+					context: 'Stats: Action to undo marking an item as spam',
+					comment:
+						'Secondary label (default label is "Spam"). Recommended to use a very short label.',
```
Comment (bluefuton) [inline client/my-sites/stats/stats-list/action-spam.jsx]: Shall we update this translator comment? The default label is no longer 'Spam'.

Comment (Aurorum) [reply client/my-sites/stats/stats-list/action-spam.jsx]: Yes, I don't think they're necessary anymore though so I just removed them :)

**Comment by Aurorum** [comment]
I can reproduce that behaviour in Chrome; I think it was a defect from #34194 or #33080. I've added a commit to fix it. :)

File: client/my-sites/stats/stats-list/style.scss (hunk 6 above)
Comment (Aurorum) [reply client/my-sites/stats/stats-list/style.scss]: 👍
