### PR TITLE
Explicitly list unsupported browsers.

### LINKED ISSUE #58352: [Bug]: wordpress.com see "Unsupported browser on Safari"
### Quick summary

image

image
Version 14.0.2 (16610.3.7.1.9)

### Steps to reproduce

1. In Safari goto wordpress.com
2. See redirect to https://wordpress.com/browsehappy?from=%2F and see the Unsupported Browser page

### What you expected to happen

I expect to see the wordpress.com landing page

### What actually happened

redirect to https://wordpress.com/browsehappy?from=%2F and see the Unsupported Browser page

### Context

_No response_

### Browser

Apple Safari

### Simple/Atomic

_No response_

### Other notes

_No response_

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

_No response_

### Workaround details

No workaround- the landing page should work in Safari

### PR DESCRIPTION
**Pull request by noahtallen**
### Changes proposed in this Pull Request
Follow up to #58218, we explicitly list unsupported browsers. These browsers will see the unsupported browser messaging. See reasoning in #58218. Importantly, the listed browsers cannot use the login form or get a WSOD upon login. (So it's not an arbitrary list.)

Another benefit of this approach is that if we don't know" whether a browser is supported, we'll allow them to try to access Calypso.

I also adjusted the "allow path" code. Since we know for certain that the pages I removed (log-in, start, new, domains) do not work at all with these browsers, we should show the message before trying to access them. Otherwise, the user won't have any path forward.

The only reason we added that code was to handle bots like the googlebot. Since the google bot isn't in our "unsupported browser list," it should never be redirected. As a result, it's not as important to completely allow these unauthenticated pages.

Resolves #58352
### Testing instructions

Access the calypso.live link using Firefox 74, then using Firefox 73. The former will not get an unsupported browser message. The latter will.

### CODE REVIEW

**Review by scinos — APPROVED** [review]

File: client/server/middleware/unsupported-browser.js [hunk 1]
```diff
@@ -28,15 +56,7 @@ function allowPath( path ) {
 		? path.replace( new RegExp( `^/${ prefixedLocale }` ), '' )
 		: path;
 
-	const allowedPaths = [
-		'/browsehappy',
-		'/log-in',
```
Comment (tyxla) [inline client/server/middleware/unsupported-browser.js:33]: I'd love to hear more about what data we have on which page works on which browser and which doesn't. The word "likely" in the new comment above bothers me a little bit. It sounds like we could go further to verify what works and what doesn't.

File: client/server/middleware/unsupported-browser.js [hunk 2]
```diff
@@ -28,15 +56,7 @@ function allowPath( path ) {
...
-		'/start',
-		'/new',
-		'/themes',
-		'/theme',
-		'/domains',
-	];
+	const allowedPaths = [ '/browsehappy', '/themes', '/theme' ];
```
Comment (tyxla) [inline client/server/middleware/unsupported-browser.js:58]: `/themes/:site` will redirect to `/log-in`. Is this something to consider? It seems like we don't care about the rest of the path, as long as it starts with one of our allowed list.

**Review by tyxla — COMMENTED** [review]
Tests well for me and code looks sensible 👍

**Review by tyxla — APPROVED** [review]

File: client/server/middleware/unsupported-browser.js (hunk 1 above)
Comment (noahtallen) [reply client/server/middleware/unsupported-browser.js:33]: I should probably update the comment. I tested and the pages I removed from here definitely do not work

File: client/server/middleware/unsupported-browser.js (hunk 2 above)
Comment (noahtallen) [reply client/server/middleware/unsupported-browser.js:58]: > Is this something to consider

It will redirect after it redirects, so I think it's okay. We allow the rest of the path so that accessing individual themes works
