### PR TITLE
Prevent deleting or removing a user when they have active subscriptions

### LINKED ISSUE #27481: Users that own upgrades can be removed from sites
#### Steps to reproduce

1. Create a free [WordPress.com](<http://WordPress.com>) site
2. Add a new administrator to the site
3. As the new administrator, purchase a site upgrade
4. As the new administrator, attempt to remove the site owner
5. As the site owner, remove the new administrator who owns the upgrade
6. As the new administrator, attempt to renew or manage the upgraded purchase

#### What I expected

When removing the site owner, an error is returned:

annotation on 2018-8-4

This would be the preferred behavior when an attempt is made to remove a user that owns an upgrade, as well.

#### What happened instead

Instead, the upgrade owner is removed:

screen shot on 2018-09-27 at 13 26 36

And that user can't access the site to manage the plan that they own:

screen shot on 2018-09-27 at 13 28 46

The site owner can't access it as well.

screen shot on 2018-09-27 at 13-29-09

This leaves the site in a state where the plan can't be renewed without several steps involving coordinating with support to resolve the issue.

The better solution would be to prevent the user from being removed and giving the user the reason why they can't be removed (they own the upgrade(s) to the account) and what can be done if they need to be removed (transfer ownership of the upgrade(s) first).

#### Browser / OS version

Browser-independent

#### Screenshot / Video

Above

#### Context / Source

This has come up at different times, especially in the Account Recovery queue.

Two recent examples are 1443076-zen and 1392450-zen

### PR DESCRIPTION
**Pull request by klimeryk**
Fixes https://github.com/Automattic/wp-calypso/issues/27481

#### Changes proposed in this Pull Request

It is not possible to remove a user with active domain subscriptions:
Screenshot 2021-03-03 at 11 44 01

However, other active upgrades are not a blocker - which is an issue, because the user then cannot manage those purchases.

This PR adds handling for a new backend check (see D59343-code) that should prevent this situation and show an appropriate error message:

Screenshot 2021-03-25 at 22 58 50

#### Testing instructions

Best tested with D59343-code, though it should work without it (just won't show any new error messages and a user with active upgrades _will_ be possible to remove - but we need to preserve backwards compatibility).

Go to Users -> All users and try to remove a user that owns upgrades on the site. Try one with only domain subscriptions, only non-domain ones (usually a paid plan) or a mix of both.

### CODE REVIEW

File: client/my-sites/people/people-notices/index.jsx [hunk 1]
```diff
@@ -105,14 +105,30 @@ class PeopleNotices extends React.Component {
...
+							},
+							components: {
+								strong: <strong />,
+							},
+						}
+					);
+				} else if ( 'user_has_active_subscriptions' === log.error.error ) {
+					const productNames = log.error.data ?? [];
+					return i18n.translate(
+						'@%(user)s owns following product used on this site: {{strong}}%(productNames)s{{/strong}}. This product will have to be transferred to a different site, user, or canceled before removing or deleting @%(user)s.',
```
Comment (a8ci18n) [inline client/my-sites/people/people-notices/index.jsx:126]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **19** times:
`translate( '@%(user)s owns following domain used on this site: {{strong}}%(domains)s{{/strong}}. This domain will have to be transferred to a different site, transferred to a different registrar, or canceled before removing or deleting @%(user)s.', '@%(user)s owns following domains used on this site: {{strong}}%(domains)s{{/strong}}. These domains will have to be transferred to a different site, transferred to a different registrar, or canceled before removing or deleting @%(user)s.' )` *ES Score: 8*

**Review by sirbrillig — APPROVED** [review]
Looks good from a Payments point of view!

**Review by olaseni — APPROVED** [review]
LGTM!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5632342

Thank you @klimeryk for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5632342).
