### PR TITLE
Site Migration: Fix Failed import styling

### LINKED ISSUE #39582: Migration: Fix up styling of import failed screen
The import failed screen needs a bit of design love.

Some thoughts:

* "There was an error with your import" is mostly unnecessary as that's implied with "Import failed" heading above it.
* We could combine those two sentences into one, something like "There was an error starting the import." or "There was an error { verb-ified error message }." (yeah... verb-ified!)
* Rephrase the contact us sentence and move it above the button to keep all the messaging together and consistent.

Screen Shot 2020-02-20 at 4 10 25 PM

### PR DESCRIPTION
**Pull request by bisko**
#### Changes proposed in this Pull Request

* Updates the styling a bit, according to #39582

#### Testing instructions

* Use Calypso.live link
* Start a migration
* "Fail" the migration by issuing a fail migration command or updating the record in the database. 

Fixes #39582

### CODE REVIEW

File: client/my-sites/migrate/section-migrate.jsx [hunk 1]
```diff
@@ -365,28 +365,29 @@ class SectionMigrate extends Component {
 					{ translate( 'There was an error with your import.' ) }
 					<br />
 					{ this.state.errorMessage }
+
+					<p className="migrate__info">
+						{ translate(
+							'{{supportLink}}Contact us{{/supportLink}} so we can' +
```
Comment (a8ci18n) [inline client/my-sites/migrate/section-migrate.jsx]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **14** times:
`translate( 'Or {{supportLink}}contact us{{/supportLink}} so we can figure out exactly what needs adjusting and get your site imported.' )` *ES Score: 13*

Comment (bisko) [reply client/my-sites/migrate/section-migrate.jsx]: We're updating the wording.

File: client/my-sites/migrate/section-migrate.jsx [hunk 2]
```diff
@@ -365,28 +365,29 @@ class SectionMigrate extends Component {
...
+								' figure out exactly' +
+								' what needs adjusting, or try again.',
+							{
+								components: {
+									supportLink: (
+										<a
+											href="https://support.wordpress.com"
```
Comment (Aurorum) [inline client/my-sites/migrate/section-migrate.jsx]: I know this is already the case, but would it not make more sense for "Contact us" to link to the contact page (ie. `/help/contact`) rather than a collection of support documents?

Comment (bisko) [reply client/my-sites/migrate/section-migrate.jsx]: That's an extremely good point. Thanks for pointing that out! Updated!
