### PR TITLE
Reader: Use static 'Streams' title for mobile header

### LINKED ISSUE #14079: Reader: clicking < SITE TITLE on mobile view shows calypso sidebar
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/following/manage **on mobile width**
2. Choose a site
3. On the site's Reader page click **< TITLE OF YOUR SITE**

#### What I expected

Not sure what this should do and how it's different from < BACK !?!

#### What happened instead

Shows Calypso sidebar

#### Browser / OS version

Mobile width browsers

#### Screenshot / Video

site title in reader mobile

### PR DESCRIPTION
**Pull request by blowery**
Fixes #14079

before
screenshot 2017-05-19 12 22 31

after
screenshot 2017-05-19 12 21 58

### CODE REVIEW

**Comment by jancavan** [comment]
@blowery it's working great except for Manage and Search.

**Comment by blowery** [comment]
Good catch! Got 'em.

File: client/reader/search-stream/index.jsx [hunk 1]
```diff
@@ -134,15 +134,18 @@ class SearchStream extends Component {
...
-			flatMap( suggestions, suggestion => [
-				<Suggestion
-					suggestion={ suggestion.text }
-					source="search"
-					sort={ sortOrder === 'date' ? sortOrder : undefined }
-					railcar={ suggestion.railcar }
-				/>,
-				', ',
-			] )
+			flatMap(
```
Comment (blowery) [inline client/reader/search-stream/index.jsx]: this was just prettier being pretty.
