### PR TITLE
Agency Dashboard: Fix site reported as down when enabling downtime monitoring

### LINKED ISSUE #74711: Jetpack Dashboard: Site is reported down for a few seconds after Monitor is enabled
### Summary

When you try to enable the Jetpack monitor from the dashboard, it's reported as "Site down" for a couple of seconds after that.

### Steps to reproduce

- Create a new JN site
- Connect Jetpack
- Access cloud.jetpack.com as an agency
- Try to enable monitor from the toggle button

### What you expected to happen

To see the monitor enabled.

### What actually happened

The site was reported as "Site down" for a couple of seconds.

Image

### PR DESCRIPTION
**Pull request by vitozev**
Resolves #74711

## Proposed Changes

When downtime monitoring is enabled from the Dashboard, we optimistically update some of the fields that the ES index will return, but we don't assume that the site is live by default.

Slack: p1679400855937679-slack-C03Q2D22DGV

## Testing Instructions

- Run `git checkout fix/jetpack-agency-dashboard-enable-monitor-site-down` and `yarn start-jetpack-cloud`
- Create a new JN site and connect Jetpack
- Visit http://jetpack.cloud.localhost:3000/
- Enable Jetpack monitor from the toggle for your site
- Verify that your site is not reported as "Site down" for a while

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: client/jetpack-cloud/sections/agency-dashboard/sites-overview/utils.ts [hunk 1]
```diff
@@ -408,11 +408,12 @@ const formatMonitorData = ( site: Site ) => {
 		error: false,
 		settings: site.monitor_settings,
 	};
-	const monitorStatus = site.monitor_settings.monitor_active;
```
Comment (vitozev) [inline client/jetpack-cloud/sections/agency-dashboard/sites-overview/utils.ts:411]: I decided to rename this `monitorStatus` to `monitorActive` because it is what it refers to.

**Review by oikeme — APPROVED** [review]
Tested these changes and they work as expected and the site down status is now reflected correctly when enabling/disabling monitor. LGTM
