### PR TITLE
Woo Express: Fix My Plan page description for Video and audio posts section

### LINKED ISSUE #76513: Woo Express: Essential plan shows 200GB storage on My Plans page
Related to #73212

Navigating to `/plans/my-plan/{SITE-SLUG}` on site with the Woo Express Essential plan shows 200 GB of storage instead of 50 GB.

Screen Shot 2023-05-02 at 14 47 07

This  can probably be solved by working on the following condition:
https://github.com/Automattic/wp-calypso/blob/trunk/client/blocks/product-purchase-features-list/video-audio-posts.jsx#L33-L38

### PR DESCRIPTION
**Pull request by valterlorran**
Closes #76513

## Proposed Changes

* Fixes the name of the plan in the **Video and audio posts**  section on the My Plan page.
* Fixes the storage limit for the Essential plan in the **Video and audio posts**  section on the My Plan page.

#### Essential Plan

* Navigate to `/plans/my-plan/{SITE-SLUG}` on a site with the Woo Express Essential plan
* The video **Video and audio posts** sections should make reference to the Woo Express Essential plan, and the storage limit should be 50GB.

Screen Shot 2023-05-04 at 08 54 50

#### Performance Plan
* Navigate to `/plans/my-plan/{SITE-SLUG}` on a site with the Woo Express Performance plan
* The video **Video and audio posts** sections should make reference to the Woo Express Performance plan, and the storage limit should be 200GB.

Screen Shot 2023-05-04 at 08 54 39

### CODE REVIEW

File: client/blocks/product-purchase-features-list/video-audio-posts.jsx [hunk 1]
```diff
@@ -30,6 +34,26 @@ function getDescription( plan, translate ) {
 				'directly to your site — the Pro Plan has 50 GB storage.'
 		);
 	}
+	if ( isWooExpressPlan( plan ) ) {
+		const wooExpressPlan = getPlan( plan );
+		let wooExpressStorageLimit = 3;
```
Comment (sixhours) [inline client/blocks/product-purchase-features-list/video-audio-posts.jsx:39]: Is there a way to get these values from the plan data rather than hard-coding them? Just thinking if things change in the future we'll have to remember to change them again.

File: client/blocks/product-purchase-features-list/video-audio-posts.jsx [hunk 2]
```diff
@@ -30,6 +34,26 @@ function getDescription( plan, translate ) {
...
+		if ( isWooExpressMediumPlan( plan ) ) {
+			wooExpressStorageLimit = 200;
+		} else if ( isWooExpressSmallPlan( plan ) ) {
+			wooExpressStorageLimit = 50;
+		}
+		// Translators: %(planName)s is the name of the plan, %(storageLimit)d is the storage limit in GB.
+		return translate(
+			'Enrich your posts and pages with video or audio. Upload plenty of media, ' +
```
Comment (sixhours) [inline client/blocks/product-purchase-features-list/video-audio-posts.jsx:47]: I think there's a colon in the plan names, ie. "Woo Express: Performance"

Screen Shot 2023-05-03 at 9 30 33 AM

And I'm not sure "Plan" should be capitalized.

**Review by andres-blanco — APPROVED** [review]

**Review by sixhours — COMMENTED** [review]
This is working for me! Once the copy is final this should probably have the string freeze label applied so the new text is sent for translation.

File: client/blocks/product-purchase-features-list/video-audio-posts.jsx (hunk 1 above)
Comment (valterlorran) [reply client/blocks/product-purchase-features-list/video-audio-posts.jsx:39]: I couldn't find it, I've been wondering how we get the plan features, and I'm not confident using `get2023PricingGridSignupWpcomFeatures` or `get2023PricingGridSignupStorageOptions` to get the storage feature.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7966547

Thank you @valterlorran for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7966547).
