### PR TITLE
Fix "Manage Reusable blocks" button in components dropdown to the expected page.

### LINKED ISSUE #59794: Manage Reusable Blocks causes Grey Screen of Death
### Quick summary

4659976-zen / 33326429-hc
Choosing `Manage Reusable Blocks` from the block options menu causes a grey screen of death with `<site> refused to connect`

https://user-images.githubusercontent.com/12906034/148331454-f5536af7-efe5-4ace-a9b0-26d3b6819462.mp4

Other methods of reaching the Manage Reusable Blocks page do not cause this issue.

### Steps to reproduce

1. Open a Post with a reusable post on the affected site.
2. Select the reusable block.
3. Select `Manage Reusable Blocks`

### What you expected to happen

User should be taken to the Manage Reusable Blocks page.

### What actually happened

User receives a grey screen of death with `<site> refused to connect`

### Context

Customer report. I was not able to reproduce on my test site.

I noticed that one of the user's reusable blocks itself contains a reusable block. In my testing I tried creating a reusable block within a reusable block in the same way, but I still could not reproduce the issue.

I didn't attempt to alter the user's reusable blocks in any way, as I'm not sure whether both versions of the reusable block are used somewhere on the site.

### Simple, Atomic or both?

Simple

### Theme-specific issue?

_No response_

### Browser, operating system and other notes

_No response_

### Reproducibility

Once

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

User can also access the Manage Reusable Blocks page from the settings menu from the three dots in the upper right corner or the Add Block plus sign in the upper right corner of the editor. Using these methods do not cause the issue.

### PR DESCRIPTION
**Pull request by mashikag**
This commit is fixing an issue where in wpcom block editor when user clicks on "Manage Reusable blocks" button from a reusable block's component settings dropdown, it would open up "grey screen of death".
Now clicking on the button will open up the expected page.

[Issue page here.](https://github.com/Automattic/wp-calypso/issues/59794)

manageReusableBefore

manageReusableAfter

#### Changes proposed in this Pull Request

* observe DOM element of `.interface-interface-skeleton ~ .popover-slot` for `childList` mutations
* when new child is inserted in the DOM element, check whether the child element is `components-popover`
* if it is components popover, then search for any descendant anchor element with href ending with the following string `edit.php?post_type=wp_block`
* if found one, then replace its ref and target properties to contents of `manageReusableBlocksUrl` variable and to `_top` string literal respectively.

#### Testing instructions

* Test this PR on a wpcom site. See [the automated comment](https://github.com/Automattic/wp-calypso/pull/62473#issuecomment-1086294495) for instructions.
* Go to wpcom block editor. This can be add/edit page or post.
* Open up component dropdown settings on any inserted block, and add it to reusable blocks. Use any name you wish. See below screenshot for reference.
Screenshot 2022-04-02 at 14 25 31
* Once the block is a reusable block, open-up the components dropdown menu again and you should see `Manage Reusable blocks` button this time, click it. 
* You should expect to be redirected to manage reusable blocks and not to see "the grey screen of death".

Related to https://github.com/Automattic/wp-calypso/issues/59794

### CODE REVIEW

File: apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js [hunk 1]
```diff
@@ -697,13 +700,36 @@ async function openLinksInParentFrame( calypsoPort ) {
...
-		observeSidebarMutations( sidebar );
+		handleSidebarNodeAdded( sidebar );
 	}
 
 	// Add and remove the sidebar observers as the sidebar elements appear and disappear.
 	// They are always direct children of the body element.
-	const body = document.querySelector( '.interface-interface-skeleton__body' );
-	sidebarsObserver.observe( body, { childList: true } );
+	const sidebarBodyElem = document.querySelector( '.interface-interface-skeleton__body' );
+	sidebarsObserver.observe( sidebarBodyElem, { childList: true } );
```
Comment (noahtallen) [inline apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]: The changes from L623-L709 appear to just rename the variables. IMO, the old names aren't necessarily worse. Since they're subjective, could we leave these changes out of the PR to avoid marking these lines as changed in the commit? (This way, it's easier to track down the commit where the main changes to those lines happened.)

**Review by noahtallen — APPROVED** [review]
I like the approach, and the fix tests correctly for me!

**Review by ivan-ottinger — COMMENTED** [review]
Update: Contemplating on my own screen recording made me notice [one issue](https://github.com/Automattic/wp-calypso/pull/62473#discussion_r842671812).

The changes work well on my end:

https://user-images.githubusercontent.com/25105483/161701639-1c262f65-4da5-4184-a179-f923a23573cf.mp4

I couldn't reproduce the issue anymore.

It takes a couple of seconds to reach the admin page with the reusable blocks, but I suspect this is related to running the changes in sandbox.

File: apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js (hunk 1 above)
Comment (ivan-ottinger) [reply apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]: I would also vote for leaving the name changes out from this PR. This would make the PR focused on that one bug fix.

Comment (mashikag) [reply apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]: @noahtallen good call! I will revert those now. 👍

File: apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js [hunk 2]
```diff
@@ -697,13 +700,36 @@ async function openLinksInParentFrame( calypsoPort ) {
...
+
+	const popoverSlotObserver = new window.MutationObserver( ( mutations ) => {
+		const isComponentsPopover = ( node ) => node.classList.contains( 'components-popover' );
+
+		const replaceWithManageReusableBlocksHref = ( anchorElem ) => {
+			anchorElem.ref = manageReusableBlocksUrl;
```
Comment (ivan-ottinger) [inline apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]: On a second round of review I found the following typo (missing `h`):

```suggestion
			anchorElem.href = manageReusableBlocksUrl;
```

As a result of the typo, the link still points to the WP Admin page instead of the Calypso one (which I didn't realize before).

This is how the page should look like:
Markup on 2022-04-05 at 13:21:22

instead of:
Markup on 2022-04-05 at 13:21:35

At least the `_top` in `anchorElem.target = '_top'` made the WP Admin link open (as opposed to displaying the "grey screen of death"). :)

**Review by ivan-ottinger — DISMISSED** [review]

**Review by ivan-ottinger — COMMENTED** [review]
Looks good to me now. 👍🏼 Tests well on my end. I am redirected to the correct "Reusable blocks" page in Calypso (`http://[site]/types/wp_block/[site-address]`).

Leaving the PR approval for another set of experienced eyes, just in case I missed something.

**Comment by yansern** [comment]
While reviewing this PR, I noticed the error:
```
Uncaught (in promise) TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
```

Upon digging, it is coming from the **more menu observer** code below your **popover observer** code.

The **more menu observer** is listening to the `.edit-post-more-menu` element, to find the "Manage reusable blocks" menu item, to replace its `href` value.

This `.edit-post-more-menu` classname was renamed renamed to `.interface-more-menu` in https://github.com/WordPress/gutenberg/pull/39115.

The good thing about the **popover observer** created in this PR is that it also replaces the `href` value of the "Manage reusable blocks" menu item under `.interface-more-menu`.

This effectively means the **more menu observer** is no longer required (and it was broken anyway).

I've added an additional commit https://github.com/Automattic/wp-calypso/pull/62473/commits/523b114fc05ae1a4d99508232dc10f827485d0a5 to remove those codes.

**Comment by noahtallen** [comment]
Nice find @yansern! Funny enough, I also fixed that in this (unmerged) PR yesterday: #62504. Love to hear that the new approach unifies that :)

**Review by noahtallen — APPROVED** [review]
This is still testing great for me, thanks for the fix!

**Comment by mashikag** [comment]
@noahtallen no worries, and thank you for your review. 🙇

**Review by yansern — APPROVED** [review]
The handler for the popover observer executes whenever the popover component is rendered on screen. My concern is if this introduces additional overhead but doing a bit of profiling shows that the performance penalty is negligible.

Looking at https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/popover/index.js, it is highly probable that `.popover-slot` container will always contain `.components-popover` as an immediate children, therefore `isComponentsPopover` might not be needed, but I might be wrong. Eitherway, it is not a blocker.

This PR is good to go.

**Comment by yansern** [comment]
> Nice find @yansern! Funny enough, I also fixed that in this (unmerged) PR yesterday: https://github.com/Automattic/wp-calypso/pull/62504. Love to hear that the new approach unifies that :)

Hey @noahtallen, was looking at https://github.com/Automattic/wp-calypso/pull/62504/files#diff-3cd9fa865f1d9d2531b85d0a08341a655b497a3304dfbb78ff787e34ff80556bR707 and the back-compat consideration slipped my mind.

The `.edit-post-more-menu` element no longer exists since > 10.7.2. I hope it is safe to remove now. I think the popover observer will also work with <= 10.7.2 as the popover observer searches for href element with that specific manage reusable block URL. 

It should be fine. :+1:

**Comment by noahtallen** [comment]
> The handler for the popover observer executes whenever the popover component is rendered on screen. My concern is if this introduces additional overhead but doing a bit of profiling shows that the performance penalty is negligible.

I was thinking the same thing, and as I looked through the existing mutation observers (which I know were at one point tweaked for performance), they seemed possibly worse. So that made me think this would probably work well if those are fine. 

> The .edit-post-more-menu element no longer exists since > 10.7.2. I hope it is safe to remove now. I think the popover observer will also work with <= 10.7.2 as the popover observer searches for href element with specific URL.

I think it should be ok too. I wasn't sure myself, which is why I kept it. I know there can _sometimes_ be older versions used in certain cases. But I don't think it's important to have this fixed in all of the older versions we have :) I think it's pretty rare.
