### PR TITLE
Marketplace: Fix error on incognito navigation avoiding /me/sites/plugins call at /plugins

### LINKED ISSUE #68828: Error retrieving plugins on incognito browser
When we browse /plugin at an incognito browser, we get the following error:

Image

It seems like plugin fetching is initially failing in the logged-out view.

The endpoint `https://public-api.wordpress.com/rest/v1.1/me/sites/plugins?http_envelope=1` is failing:

image

### PR DESCRIPTION
**Pull request by paulopmt1**
fix #68828

### Proposed Changes

* Fix error on incognito navigation avoiding /me/sites/plugins call at /plugins

### Testing Instructions

**At logged-in navigation**:
* Make sure we still have the /me/sites/plugins call at /plugins page

**At incognito navigation**:

* Open the http://calypso.localhost:3000/plugins page
* Open plugin details
* Make a plugin search

In all the above scenarios, make sure you don't see the error anymore:

image

#### Pre-merge Checklist

- [ ] ~~[Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?~~
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] ~~Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)~~
- [ ] ~~Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?~~

Related to #

### CODE REVIEW

**Review by lupus2k — APPROVED** [review]

File: client/components/data/query-plugins/index.tsx [hunk 1]
```diff
@@ -1,6 +1,11 @@
+import { useSelector } from 'react-redux';
+import { isUserLoggedIn } from 'calypso/state/current-user/selectors';
 import QueryAllJetpackSitesPlugins from '../query-all-jetpack-sites-plugins';
 import QueryJetpackPlugins from '../query-jetpack-plugins';
 
 export default function QueryPlugins( { siteId }: { siteId?: number } ) {
+	const isLoggedIn = useSelector( isUserLoggedIn );
+	if ( isLoggedIn === false ) return false;
```
Comment (obenland) [inline client/components/data/query-plugins/index.tsx]: Any chance you could add some curly braces and line breaks here to stay with [WordPress JS](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/javascript/#blocks-and-curly-braces) and [Calypso](https://github.com/Automattic/wp-calypso/blob/trunk/docs/coding-guidelines/javascript.md#blocks-and-curly-braces) coding standards?

**Review by obenland — CHANGES_REQUESTED** [review]

File: client/components/data/query-plugins/index.tsx (hunk 1 above)
Comment (lsl) [reply client/components/data/query-plugins/index.tsx]: Why isn't the linter/fixer picking this up? @Automattic/team-calypso-platform maybe the right people to ping?

Comment (jsnajdr) [reply client/components/data/query-plugins/index.tsx]: I think checking these `if` one-liners fell through the cracks when we started to use Prettier and then removed all formatting-related ESLint rules. One of them was the [`curly`](https://eslint.org/docs/latest/rules/curly) rule. We should reintroduce `curly` if we want to enforce this style (good idea IMO). It doesn't conflict with Prettier, which accepts and formats both forms (`IfStatement` + `ReturnStatement` AST vs `IfStatement` + `Block` + `ReturnStatement`), just adds on top of it.

Comment (paulopmt1) [reply client/components/data/query-plugins/index.tsx]: Thanks for noting that, @obenland. Fixed [it here](https://github.com/Automattic/wp-calypso/pull/68835/commits/74784889d9438c5d210fdaf8e85dbdf598ed76a1).

**Comment by paulopmt1** [comment]
@claudiucelfilip I see you worked a lot on logged-out implementations. Is this a good approach to restricting loading resources for authenticated users only? 

I wonder if it would be more self-explanatory to add this condition [where we import this component](https://github.com/Automattic/wp-calypso/blob/fix/68828-error-on-incognito-browser/client/my-sites/plugins/main.jsx#L468). The downside would be we'll need to remember to do that each time we import it, which currently is in three places.

**Comment by claudiucelfilip** [comment]
> Is this a good approach to restricting loading resources for authenticated users only?

Looks good to me. I've also used similar approaches to adjust for other logged-in/logged-out differences.

**Review by claudiucelfilip — APPROVED** [review]

File: client/components/data/query-plugins/index.tsx (hunk 1 above)
Comment (noahtallen) [reply client/components/data/query-plugins/index.tsx]: Updated eslint here: #68923

**Comment by paulopmt1** [comment]
Thanks for everyone's review! Deploying...
