### PR TITLE
Fix masterbar title on the Plugin install page

### LINKED ISSUE #61836: Plugin install page: masterbar title is not centered correctly
When installing a plugin, the WP masterbar has the "Plugin installation" text centered not considering the WP wordmark:
image

This looks a bit off with the rest of the site content centered, it should be centered relative to the window width.

### PR DESCRIPTION
**Pull request by gcsecsey**
#### Changes proposed in this Pull Request

* Applied styling from the checkout masterbar
* Moved the title to the left to align with Figma and other instances of the masterbar

#### Testing instructions

* Try installing any plugin, or visit the plugin install page directly (`/marketplace/<productSlug>/install/<siteUrl>`)
* Verify that the masterbar layout looks like this:
  | Before | After | 
  | --- | --- |
  | calypso localhost_3000_marketplace_mailpoet_install_gcsecseysimplebusiness wpcomstaging com | calypso localhost_3000_marketplace_mailpoet_install_gcsecseysimplebusiness wpcomstaging com (1) |

Closes #61836

### CODE REVIEW

File: client/my-sites/marketplace/pages/marketplace-plugin-install/index.tsx [hunk 1]
```diff
@@ -395,8 +394,12 @@ const MarketplacePluginInstall = ( {
 			/>
 			{ siteId && <QueryJetpackPlugins siteIds={ [ siteId ] } /> }
 			<Masterbar>
-				<WordPressWordmark className="marketplace-plugin-install__wpcom-wordmark" />
-				<Item>{ translate( 'Plugin Installation' ) }</Item>
+				<div className="marketplace-plugin-install__masterbar">
```
Comment (cpapazoglou) [inline client/my-sites/marketplace/pages/marketplace-plugin-install/index.tsx]: is that wrapper needed? I see that `Masterbar` accepts a `class`

File: client/my-sites/marketplace/pages/marketplace-plugin-install/index.tsx [hunk 2]
```diff
@@ -395,8 +394,12 @@ const MarketplacePluginInstall = ( {
...
+					<WordPressWordmark className="marketplace-plugin-install__wpcom-wordmark" />
+					<span className="marketplace-plugin-install__plugin-installation-text">
+						{ translate( 'Plugin installation' ) }
+					</span>
```
Comment (cpapazoglou) [inline client/my-sites/marketplace/pages/marketplace-plugin-install/index.tsx]: Can't we reuse the `<Item>` and just override the css rules needed? In terms of placement

```
.masterbar {
    justify-content: flex-start;
}
.masterbar__item {
   flex-grow: 0;
}
```
I think are enough? 

Not sure why Checkout has opted to use a new element rather than reusing `<Item>`. Both interfaces should have the same look and feel.

Comment (gcsecsey) [reply client/my-sites/marketplace/pages/marketplace-plugin-install/index.tsx]: Great point, thanks, I've updated the styling. 👍 

One interesting note: `<Item>` always renders a `button` or an `a` element, so the hover state needs to be overridden in CSS. Maybe that's why Checkout opted to add custom elements.

**Review by cpapazoglou — APPROVED** [review]
LGTM!
