### PR TITLE
Skip redirect if page is supported

### LINKED ISSUE #56602: Crawlers: Prevent Google bot (and some other bots) from seeing the /browsehappy browser unsupported page
### Steps to reproduce the behavior

1. [Override Chrome user agent](https://developer.chrome.com/docs/devtools/device-mode/override-user-agent/) to use the Google mobile crawler bot user agent string: **Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F70 Safari/600.1.4 (compatible; Googlebot /2.1; +http://www.google.com/bot.html)**
2. Then go to one of these urls: WordPress.com/log-in or WordPress.com/start or WordPress.com/themes
3. Notice you will be redirected to /browsehappy?from=/log-in (browser unsupported page)

#### What I expected to happen
Page should load correctly for GoogleBot (very Important), Google Mobile Crawler Bot (Very Important) and Semrush Bot (Required for internal analysis)

#### Browser / OS version

- User Agents: Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F70 Safari/600.1.4 (compatible; Googlebot /2.1; +http://www.google.com/bot.html)
- User Agents: Mozilla/5.0 (compatible; SemrushBot/7~bl; +http://www.semrush.com/bot.html)

#### Does this happen on simple or atomic sites or both?

- WordPress.com/log-in 
- WordPress.com/start
- WordPress.com/themes

#### Is there any console output or error text?
No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
It is hampering clicks to the Log-In page in terms of - the google bot is seeing this unsupported message and as a result it is gradually pulling urls out of its index.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

- https://share.getcloudapp.com/p9ukDGLm
- https://share.getcloudapp.com/wbubl7xd 
- https://share.getcloudapp.com/geuANze7
- https://share.getcloudapp.com/wbubl7Gn

### PR DESCRIPTION
**Pull request by noahtallen**
### Changes proposed in this Pull Request
Resolves #56602.

We have a problem where some bots are unable to access public pages. We want to support these bots.

Option 1 is to add their user agents to the list of "supported browsers". (I think I personally lean towards this option.)
Option 2 is to simply not redirect certain public pages. In our team call today, this seemed to be the most favored option, so I've implemented it here :)

Unfortunately, I didn't quickly see a simple way to dynamically allow access to _any_ public page, as the routing logic is set up after the unsupported browser middleware. (E.g. we redirect before we know what pages are available.) Since this is semi-possibly-temporary (if we remove the redirect altogether in the future), I figure a simple list of pages to support is fine. (Plus, this covers the only pages we know about affecting the bot behavior in a negative way.

The reason I like option 1 better is that in this scenario, a user could do all the work of going through the login flow and only afterwards get redirected to the browsehappy page. That's a very negative experience, IMO. Since we want something like `log-in` to also be indexed by bots, just allowing the bot user agent would solve both problems.

### Testing instructions
1. Load calypso.live in IE11
2. Access one of the permitted pages, like "themes". You should not be redirected. (Important: the page may not work.)
4. Access another page, like "posts". You should be redirected to browsehappy.

### CODE REVIEW

File: client/server/middleware/unsupported-browser.js [hunk 1]
```diff
@@ -18,13 +18,21 @@ function isSupportedBrowser( req ) {
 	} );
 }
 
+// We don't want to redirect some of our public landing pages, so we include them
+// here.
+function shouldRedirectPath( path ) {
+	const allowedPaths = [ 'browsehappy', 'log-in', 'start', 'new', 'themes' ];
+	return ! allowedPaths.includes( path.slice( 1 ) );
```
Comment (fullofcaffeine) [inline client/server/middleware/unsupported-browser.js]: Could `path` contain a leading `/`?

File: client/server/middleware/unsupported-browser.js [hunk 2]
```diff
@@ -18,13 +18,21 @@ function isSupportedBrowser( req ) {
...
+
 export default () => ( req, res, next ) => {
 	if ( ! config.isEnabled( 'redirect-fallback-browsers' ) ) {
 		next();
 		return;
 	}
 
-	if ( req.path === '/browsehappy' ) {
+	// Permitted paths even if the browser is unsupported.
+	if ( ! shouldRedirectPath( req.path ) ) {
```
Comment (fullofcaffeine) [inline client/server/middleware/unsupported-browser.js]: Nit: I'd call this function something like `allowPath` or `allowPathToOpen`:

```js
if ( allowPath( req.path ) ) {
	next();
	return;
}
```

Which I think is easier to read and reason about.

**Review by fullofcaffeine — APPROVED** [review]
This tests well! I also left a few non-blocking comments.

File: client/server/middleware/unsupported-browser.js (hunk 1 above)
Comment (jsnajdr) [reply client/server/middleware/unsupported-browser.js]: The test should catch URLs like `/themes/travel` or `/theme/twenty-twenty-one`. Therefore:
```js
[ '/browsehappy', '/log-in', ..., '/themes', '/theme' ].some( p => path.startsWith( p ) )
```

And there are also localized theme pages served by Calypso with URLs like `/de/themes` or `/es/theme/foo`.

File: client/server/middleware/unsupported-browser.js (hunk 2 above)
Comment (noahtallen) [reply client/server/middleware/unsupported-browser.js]: Sounds good!

File: client/server/middleware/unsupported-browser.js (hunk 1 above)
Comment (noahtallen) [reply client/server/middleware/unsupported-browser.js]: > Could path contain a leading /?

Yep, the leading '/' is removed.

I've also updated the matcher with @jsnajdr's suggestions:
- uses `startsWith`
- strips out leading locale using `config( 'magnificent_non_en_locales' )`

As an example, an input of `/es/theme/twenty-twenty` will be parsed to `theme/twenty-twenty`, and since that starts with `theme`, it will be allowed.

File: client/server/middleware/unsupported-browser.js [hunk 3]
```diff
@@ -18,13 +18,32 @@ function isSupportedBrowser( req ) {
 	} );
 }
 
+// We don't want to redirect some of our public landing pages, so we include them
+// here.
+function allowPath( path ) {
+	// Strip leading '/'.
```
Comment (jsnajdr) [inline client/server/middleware/unsupported-browser.js:24]: The leading slash is always guaranteed to be there, so we don't need to assume it's optional.

File: client/server/middleware/unsupported-browser.js [hunk 4]
```diff
@@ -18,13 +18,32 @@ function isSupportedBrowser( req ) {
...
+	let parsedPath = path.replace( /^\//, '' );
+	const possiblePathLocales = [ 'en', ...config( 'magnificent_non_en_locales' ) ];
+	for ( const locale of possiblePathLocales ) {
+		// Strip leading locale (e.g. 'es/')
+		if ( parsedPath.startsWith( locale ) ) {
```
Comment (jsnajdr) [inline client/server/middleware/unsupported-browser.js:29]: This matching is implemented a bit carelessly I would say. It will match also `/design` and `/devdocs` and the `parsedPath` becomes `sign` or `vdocs`, that is further matched against `start` or `new`...

The `allowedPaths` will also accept `/startups` or `/newport` although it shouldn't... Although there probably isn't any Calypso URL that would get mismatched, we can do better, by also checking the `/` characters at expected places.

File: client/server/middleware/unsupported-browser.js (hunk 3 above)
Comment (noahtallen) [reply client/server/middleware/unsupported-browser.js:24]: I wrote it this way to avoid prefixing `/` to all the paths and locales we try to match :)

File: client/server/middleware/unsupported-browser.js (hunk 4 above)
Comment (noahtallen) [reply client/server/middleware/unsupported-browser.js:29]: Thanks! Fixed: #56737

File: client/server/middleware/unsupported-browser.js (hunk 3 above)
Comment (jsnajdr) [reply client/server/middleware/unsupported-browser.js:24]: Prefixing all the paths is fine, we use it all the time e.g. in `client/layout/index.jsx`. And in theory the `/log-in` string should be easier to grep than `log-in`, like when answering a "what are all the places where we work with the `/log-in` route?" question.

Comment (noahtallen) [reply client/server/middleware/unsupported-browser.js:24]: Hm, yeah that's a good point. I'll follow up on that today

Comment (noahtallen) [reply client/server/middleware/unsupported-browser.js:24]: #56765
