### PR TITLE
Separate concerns and display proper error message

### LINKED ISSUE #13954: Social Signup: Connection loop when .com email already exists
#### Steps to reproduce
1. Starting at URL: https://calypso.live/start/social?branch=master
2. Try signing in with a gmail email that is already connected to a WP.com account 
3. Once you see the connection error try logging in again 
4. It does not give the option to log in with a different gmail account

#### What I expected
Once I tried to connect one gmail account, I wanted to try to connect another gmail that had not yet been connected to a .com account.

#### What happened instead
I was stuck in a loop with no option to select a different account: 

#### Browser / OS version
chrome (incognito window)  57.0.2987.133

#### Context / Source
#painpoint
#manual-testing

### PR DESCRIPTION
**Pull request by yurynix**
This pull request fixes #13954 by refactoring the error handling logic.

log_in_error

#### Testing instructions
  
1. Run `git checkout update/error-existing-user` and start your server, or open a [live branch](https://calypso.live/?branch=update/error-existing-user)
2. Open the [`Login` page](http://calypso.localhost:3000/log-in)
3. Try to log-in with Google account that has an email that already has a WordPress.com account
4. Assert you see a correct error message
5. Repeat with a fresh email and assert the account is indeed created.
    
#### Reviews
  
- [x] Code
- [x] Product

### CODE REVIEW

File: client/state/login/actions.js [hunk 1]
```diff
@@ -202,8 +215,16 @@ export const loginSocialUser = ( service, token ) => dispatch => {
 			dispatch( { type: SOCIAL_LOGIN_REQUEST_SUCCESS } );
 		} )
 		.catch( ( httpError ) => {
+			const errorKey = get( httpError, 'response.body.data.errors[0]' );
 			const error = getErrorFromHTTPError( httpError );
 
+			if ( errorKey === 'unknown_user' ) {
+				if ( ( typeof shouldCreateAccount === 'function' && shouldCreateAccount() ) ||
+					shouldCreateAccount ) {
```
Comment (drewblaisdell) [inline client/state/login/actions.js]: If `shouldCreateAccount` is always one type (only ever a function, currently), I think handling an additional type just makes the code a little harder to follow.

File: client/blocks/login/social.jsx [hunk 2]
```diff
@@ -34,25 +33,27 @@ class SocialLoginForm extends Component {
 			return;
 		}
 
-		this.props.loginSocialUser( 'google', response.Zi.id_token ).then( () => {
+		let creatingAccountNotice = null;
+
+		this.props.loginSocialUser( 'google', response.Zi.id_token, () => {
+			const { notice } = this.props.infoNotice( this.props.translate( 'Creating your account' ) );
+			creatingAccountNotice = notice;
+			return true;
```
Comment (drewblaisdell) [inline client/blocks/login/social.jsx]: Passing a predicate in the `shouldCreateAccount` parameter that always returns `true` makes me think this will always create an account. It also feels a little strange to mix promises and callbacks like this.

Could we just use promises instead, but move the `usersSocialNew` to an action? This seems easier to understand to me:

```js
this.props.loginSocialUser( 'google', response.Zi.id_token )
  .then( result => {
    // set success state
  } )
  .catch( error => {
    if ( error.code === 'unknown_user' ) {
      // create an account
    } else {
      // error notice
    }
  } );
```

**Comment by gziolo** [comment]
Also @ranh proposed this copy:

> Whoops! Your email on Google (mail@example.com) is already in use WordPress.com. To use your existing WordPress.com account, log in with your email address and password. To create a new WordPress.com account, you'll have to switch to a different Google account.

**Comment by yurynix** [comment]
@drewblaisdell Thank you for reviewing that, I've refactored to a different approach, passing account creation threw redux, what's your take on that?

**Comment by yurynix** [comment]
Hope I got the rebase right, most issues were:
1. the tracking
2. Addition of `code` to the error, in my PR i used `type` instead...

File: client/state/login/reducer.js [hunk 3]
```diff
@@ -78,6 +82,20 @@ export const twoFactorAuthPushPoll = createReducer( { inProgress: false, success
 	[ TWO_FACTOR_AUTHENTICATION_PUSH_POLL_COMPLETED ]: state => ( { ...state, inProgress: false, success: true } ),
 } );
 
+export const socialAccount = createReducer( { creating: false }, {
+	[ SOCIAL_CREATE_ACCOUNT_REQUEST ]: () => ( { creating: true } ),
+	[ SOCIAL_CREATE_ACCOUNT_FAILURE ]: ( state, { error } ) => ( { creating: false, createError: error } ),
+	[ SOCIAL_CREATE_ACCOUNT_SUCCESS ]: ( state, { data: { username, bearerToken } } ) => ( {
+		creating: false,
```
Comment (stephanethomas) [inline client/state/login/reducer.js]: I think the convention is to prefix such flag with `is` (see `isRequesting` for example).

File: client/blocks/login/social.jsx [hunk 4]
```diff
@@ -10,70 +10,55 @@ import { localize } from 'i18n-calypso';
...
+		this.props.loginSocialUser( 'google', response.Zi.id_token )
+			.then(
+				() => {
+					recordEvent( 'calypso_social_login_form_login_success' );
 
-						this.setState( {
-							username: wpcomResponse.username,
-							bearerToken: wpcomResponse.bearer_token
-						} );
+					this.props.onSuccess()
```
Comment (yurynix) [inline client/blocks/login/social.jsx]: Hmm, I wonder how it passed the linter

File: client/state/action-types.js [hunk 5]
```diff
@@ -693,6 +693,9 @@ export const SITE_WORDPRESS_UPDATE_REQUEST_SUCCESS = 'SITE_WORDPRESS_UPDATE_REQU
 export const SOCIAL_LOGIN_REQUEST = 'SOCIAL_LOGIN_REQUEST';
 export const SOCIAL_LOGIN_REQUEST_SUCCESS = 'SOCIAL_LOGIN_REQUEST_SUCCESS';
 export const SOCIAL_LOGIN_REQUEST_FAILURE = 'SOCIAL_LOGIN_REQUEST_FAILURE';
+export const SOCIAL_CREATE_ACCOUNT_REQUEST = 'SOCIAL_CREATE_ACCOUNT_REQUEST';
```
Comment (Tug) [inline client/state/action-types.js]: Minor but we could use `SIGNUP` instead of `CREATE_ACCOUNT`

File: client/state/login/reducer.js [hunk 6]
```diff
@@ -78,6 +82,20 @@ export const twoFactorAuthPushPoll = createReducer( { inProgress: false, success
...
+		username,
+		bearerToken
```
Comment (Tug) [inline client/state/login/reducer.js]: It's not great to have the bearerToken in the `socialAccount` state, that's why I didn't move it to redux initially. Maybe we should do 1 action to create the social account and log in. However, it would need a bit of refactoring around the `WpcomLoginForm` component which is not welcomed in this PR.

Comment (drewblaisdell) [inline client/state/login/reducer.js]: @Tug Is the issue that the global state could be persisted to local storage? Is it a problem if we don't provide a way to serialize this branch?

**Comment by Tug** [comment]
I'm not 100% convinced by this move to redux. Sure the code looks a bit nicer now but the server-side is already complex (get a bearer token in 1 endpoint and use it on another) and we have now hidden that complexity to different places in the state.
Also, as I commented we are retaining a bearer token in the state with this approach. It should not be a huge security concern since it is not persisted but it still doesn't seem like a good practice.
What do you think?

File: client/blocks/login/social.jsx [hunk 7]
```diff
@@ -10,70 +10,55 @@ import { localize } from 'i18n-calypso';
...
+			...params
+		} );
 
-						this.props.errorNotice( wpcomError.message );
-					} else {
-						this.props.recordTracksEvent( 'calypso_social_login_form_signup_success', {
-							social_account_type: 'google',
-						} );
+		this.props.loginSocialUser( 'google', response.Zi.id_token )
+			.then(
```
Comment (drewblaisdell) [inline client/blocks/login/social.jsx]: This is a lot easier to read, I think. :)

**Comment by drewblaisdell** [comment]
Thanks @yurynix, this looks like an improvement to me.

> It should not be a huge security concern since it is not persisted but it still doesn't seem like a good practice.

@Tug Would you mind elaborating on why this isn't a good practice?

If we can't decide whether or not to store this in the global state, I think simply adding a `createSocialAccount` action (which this PR does) is enough to move forward.

**Comment by Tug** [comment]
Well a bearer token is pretty much like user's credentials and we wouldn't store the user's password as plaintext in the store I believe. It's at risk of being exposed to other part of the code, third party scripts, browser extensions...

File: client/blocks/login/social.jsx (hunk 4 above)
Comment (yurynix) [inline client/blocks/login/social.jsx]: Done

File: client/components/social-buttons/google.js [hunk 8]
```diff
@@ -152,7 +153,7 @@ class GoogleLoginButton extends Component {
 					{ /* eslint-enable max-len */ }
 
 					<span className="social-buttons__service-name">
-						{ this.props.translate( 'Continue with %(service)s', {
+						{ this.props.overrideText || this.props.translate( 'Continue with %(service)s', {
```
Comment (yurynix) [inline client/components/social-buttons/google.js]: done

File: client/state/login/reducer.js (hunk 3 above)
Comment (yurynix) [inline client/state/login/reducer.js]: done

File: client/state/action-types.js (hunk 5 above)
Comment (yurynix) [inline client/state/action-types.js]: It seems we don’t mention signup anywhere else, the endpoint is called `/users/social/new` so, imo create account is fine, because that’s what we’re doing...
I'll leave it as it is unless you feel strongly about it.

File: client/state/login/reducer.js (hunk 6 above)
Comment (yurynix) [inline client/state/login/reducer.js]: I don't think that changes something from what it used to be, as this state branch is not persisted, so on reload that state is lost.

**Comment by yurynix** [comment]
I don't think that PR changes something from how it's used to be, on reload the bearerToken is deleted.

In theory, if it's not deleted, it can be gotten from memory whether it in components state (like it was) or in redux state...

**Comment by fabianapsimoes** [comment]
Product :+1:

**Comment by drewblaisdell** [comment]
> In theory, if it's not deleted, it can be gotten from memory whether it in components state (like it was) or in redux state...

@Tug and I talked about this elsewhere, and he convinced me that while the bearer token lives in memory either way, adding it to the global store is a bit more prone to error as it will be more easily caught by middleware and browser extensions that interact with this object.

File: client/state/action-types.js (hunk 5 above)
Comment (Tug) [inline client/state/action-types.js]: Ok it's not super important anyway

File: client/blocks/login/social.jsx [hunk 9]
```diff
@@ -86,13 +71,17 @@ class SocialLoginForm extends Component {
 				<div className="login__social-buttons">
 					<GoogleLoginButton
 						clientId={ config( 'google_oauth_client_id' ) }
-						responseHandler={ this.handleGoogleResponse } />
+						responseHandler={ this.handleGoogleResponse }
+						label={ this.props.isSocialAccountCreating
```
Comment (Tug) [inline client/blocks/login/social.jsx]: I'm not convinced by this change either, this should be a notice instead

**Comment by drewblaisdell** [comment]
@Tug has convinced me that we should probably avoid storing the bearer token in the global store, since the odds of it being saved to local storage or saved by other middleware/the Redux browser extensions is higher than if it were in component state, thus introducing fragility.

**Comment by Tug** [comment]
@yurynix Could we move to a simpler version of this PR where we mostly display the error message? I have no problem moving things to redux unless it's the bearer token!
I believe this PR could be way simpler.

**Comment by yurynix** [comment]
> @Tug has convinced me that we should probably avoid storing the bearer token in the global store, since the odds of it being saved to local storage or saved by other middleware/the Redux browser extensions is higher than if it were in component state, thus introducing fragility.

Browser extensions see all that is happening in your browser, so they can store whatever they want from the request / memory directly. Regular users don't have redux browser extension, so I'm not sure I get the point?

We have mechanism in place that prevents reducers be serialized to local storage, other than that, whatever there is in memory can be accessed whether it's in the global store or the component's state, so I don't really see how is storing the token in component state is "more secure" than storing it in the global store.

**Comment by Tug** [comment]
The thing is, it shouldn't really be part of the state at all, it's only used once to authenticate the user!

We talked many times about the many awesome things we could do with redux, such as session playback. I'm just assuming that the code will be changed for the worse at some point in time and that having an important auth token stored along ui data doesn't seem like the best choice when we know that we don't need to store it at all.

**Comment by yurynix** [comment]
Why it shouldn't be in state? how is it different than `login.twoFactorAuth.*` for example? It is as well only used for auth and has sensitive information.

Once bearer token hits client side, it doesn't matter where we store it IMO, if we could avoid seeing it on the client side at all thats a different story.

File: client/blocks/global-notice/README.md [hunk 10]
```diff
@@ -0,0 +1,24 @@
+Global Notice
```
Comment (gziolo) [inline client/blocks/global-notice/README.md]: We already have `<GlobalNotices />` components. See https://github.com/Automattic/wp-calypso/tree/master/client/components/global-notices. It is a bit different, but I think this change in such shape would introduce some confusion. We should rather put this component in the same folder and pick a different name to make it clear how it differs from we already have.

Comment (Tug) [inline client/blocks/global-notice/README.md]: It's different, the one you linked is plural and used to display all notices from the store. This one triggers a notice on mount, a bit like a data component.

I agree we should think how we organize the code as it can be confusing in the current state.

**Comment by fabianapsimoes** [comment]
I can see a flash of a notice saying "Creating your account" before the error notice is displayed. If it's not an easy fix, I wouldn't block merging on this issue. Apart from that, product :+1:

File: client/state/login/actions.js [hunk 11]
```diff
@@ -96,9 +96,9 @@ function getErrorFromHTTPError( httpError ) {
 }
 
 const wpcomErrorMessages = {
-	user_exists: translate( 'Whoops! Your email on Google is already in use on WordPress.com. ' +
-		'To use your existing WordPress.com account, log in with your email address and password. ' +
-		"To create a new WordPress.com account, you'll have to switch to a different Google account." )
+	user_exists: translate( 'Your Google email address is already in use WordPress.com. ' +
+		'Log in to your account using your email address or username, and your password. ' +
+		"To create a new WordPress.com account, use a different Google account." )
```
Comment (gziolo) [inline client/state/login/actions.js]: Eslint complains now about using `"`.

Comment (Tug) [inline client/state/login/actions.js]: thx fixed it

**Comment by Tug** [comment]
So the "Creating your account..." notice is shown during the duration of the request, it's really tied to it and I'd rather not add some complexity to `notices` in this PR to make them fade out nicely.

File: client/blocks/login/social.jsx [hunk 12]
```diff
@@ -95,10 +88,14 @@ class SocialLoginForm extends Component {
 						onClick={ this.trackGoogleLogin } />
 				</div>
 
-				{ this.state.bearerToken && (
+				{ this.props.isSocialAccountCreating &&
+					<InfoNotice text={ this.props.translate( 'Creating your account…' ) } />
```
Comment (gziolo) [inline client/blocks/login/social.jsx]: I'm still not convinced about the idea of having a special block that is used to display a global notice. We can achieve exactly the same behavior using `componentWillReceiveProps` and a few lines of code.

Comment (gziolo) [inline client/blocks/login/social.jsx]: If we really want to proceed with this approach, I would prefer to put that component in [client/components/global-notices](https://github.com/Automattic/wp-calypso/tree/master/client/components/global-notices) folder.

File: client/blocks/login/index.jsx [hunk 13]
```diff
@@ -90,9 +92,12 @@ class Login extends Component {
 	};
 
 	renderError() {
-		const error = this.props.requestError || this.props.twoFactorAuthRequestError;
+		const error = this.props.requestError ||
```
Comment (gziolo) [inline client/blocks/login/index.jsx]: This one is too long to process :)

File: client/state/login/actions.js [hunk 14]
```diff
@@ -239,10 +257,14 @@ export const createSocialUser = ( service, token, flowName ) => dispatch => {
...
-		dispatch( { type: SOCIAL_CREATE_ACCOUNT_REQUEST_SUCCESS } );
-		return Promise.resolve( wpcomResponse );
-	} ).catch( wpcomError => {
-		const error = { ...wpcomError, field: 'global' };
+		const data = {
+			username: wpcomResponse.username,
+			bearerToken: wpcomResponse.bearer_token
+		};
+		dispatch( { type: SOCIAL_CREATE_ACCOUNT_REQUEST_SUCCESS, data } );
+		return data;
```
Comment (gziolo) [inline client/state/login/actions.js]: We no longer resolve promise here, but I guess it's fine.

File: client/state/login/reducer.js [hunk 15]
```diff
@@ -124,6 +125,22 @@ export const twoFactorAuthPushPoll = createReducer( { inProgress: false, success
...
+	[ SOCIAL_CREATE_ACCOUNT_REQUEST_SUCCESS ]: ( state, { data: { username, bearerToken } } ) => ( {
+		isCreating: false,
+		username,
+		bearerToken
+	} ),
+	[ SOCIAL_LOGIN_REQUEST_FAILURE ]: ( state, { error } ) => ( {
+		...state,
+		requestError: error
+	} ),
+	[ USER_RECEIVE ]: state => ( { ...state, bearerToken: null, username: null } ),
```
Comment (gziolo) [inline client/state/login/reducer.js]: I was wondering if we should set state to its initial value:
```js
{ isCreating: false }
```
for `USER_RECEIVE` and `LOGIN_REQUEST` action types.

I wanted to double check to be on a safe side.

**Comment by gziolo** [comment]
Tests well for me. I was able to see `Creating account...` global notice and proper error message when email is already in use. 👍
