### PR TITLE
Fix Professional Email mailbox validation

### LINKED ISSUE #53308: Professional (Titan) email failing to show validation message for the "Full name" field.
When signing up for Professional (Titan) email, if we leave the "Full Name" field empt, the "Add Professional Email" button will just not work, but no error message will be displayed.

titan-email-validation

This validation error notice/message will only show if the user has clicked first on the Full Name field (and left it empty):

Screen Shot on 2021-06-01 at 17:16:48

My suggestion is that this "This field is required" notice should show even if the user has not clicked on that input.  

This is happening on both simple and atomic sites.

MacBook Pro - OS Big Sur.
Google Chrome 90.0.4430.212

### PR DESCRIPTION
**Pull request by daledupreez**
#### Changes proposed in this Pull Request

* This PR improves the logic for the Professional Email pages that display mailbox creation fields so they show all errors after the user tries to add the mailbox(es) to their cart.
* The PR also adds JSDoc annotations to `client/lib/titan/new-mailbox.js`

From a technical perspective, this PR has three core pieces:
* The `TitanNewMailbox` component has a new `showAllErrors` prop that overrides the existing interaction-based logic when it is true.
* The wrapping page logic re-validates all the mailboxes before adding them to the cart, as the validation is currently interaction-driven and wouldn't occur for new mailboxes that had no interactions yet. After this validation step, we recall the uuids for the validated mailboxes.
* The wrapping page supplies the fully validated mailbox uuids to the `TitanNewMailboxList` component, which then uses the uuids to control which mailboxes should show all errors.

_I've kept the changes to Professional Email for now, as I was more familiar with that code, and wanted to get feedback before porting. The work for Google can happen in a follow-on PR._

#### Testing instructions

* Run this branch locally or via [the live branch](https://calypso.live/?branch=fix/email-account-validation-display).
* Run through the following tests when creating Professional Email mailboxes via `/email/:domain/manage/:siteSlug` for a domain with and without an existing Professional Email subscription (for the first case, you'll need to click on "Add new mailboxes")
  - Enter only some of the fields in the first mailbox _without_ interacting with the other fields (we've received issues with the password field and the name field, but you should also test with leaving the "Password reset email address" field empty)
  - Click on "Continue" or "Add Professional Email" to submit the form (or try hitting Enter/Return with a field focused)
  - Verify that errors are displayed for all invalid fields, especially the ones you didn't interact with
  - Click on the "Add another mailbox" button
  - Verify that no errors are displayed for the newly created mailbox
  - Click on the "Continue"/"Add Professional Email" button (or hit Enter/Return)
  - Verify that all the empty fields in the newly created mailbox are highlighted
  - Throw more test cases and interactions at the form and make sure you see all validation issues whenever you try to submit the data.

Fixes #53308

### CODE REVIEW

File: client/lib/titan/new-mailbox.js [hunk 1]
```diff
@@ -13,6 +13,56 @@ import { v4 as uuidv4 } from 'uuid';
...
+/**
+ * A Titan mailbox with a string value
+ *
+ * @typedef {Object} TitanMailboxStringValue
+ * @property {string} value
+ * @property {TitanMailboxValueError} error
+ */
+
+/**
+ * A Titan mailbox with a string value
```
Comment (stephanethomas) [inline client/lib/titan/new-mailbox.js]: Looks like this comment is a duplicate of the one above.

File: client/lib/titan/new-mailbox.js [hunk 2]
```diff
@@ -66,6 +116,12 @@ const sanitizeEmailSuggestion = ( emailSuggestion ) =>
 		.replace( /[^0-9a-z_'.-]/gi, '' )
 		.toLowerCase();
 
+/**
+ * Validate that mailboxes don't contain duplicate mailbox names.
+ *
+ * @param {TitanMailbox[]} mailboxes The list of mailboxes.
+ * @returns {TitanMailbox[]} The validated list of mailboxes.
+ */
```
Comment (stephanethomas) [inline client/lib/titan/new-mailbox.js:124]: Thank you for adding all the comments in that file, that's great!

**Review by stephanethomas — APPROVED** [review]
I know we've briefly touched that part earlier today, and that's something not related to your changes, but I think we have a really big problem with those Titan and Google Workspace forms. I am going to put aside the fact that the code is duplicated, something that is already a red flag given how close those two forms are. But wow, look at the number and complexity of the changes required just to be able to display errors when the user clicks the submit button! Honestly, I'm lost when I look at this validation logic, there are callbacks everywhere and the data flows in totally different directions. I'm honestly glad you figured out a solution.

This pull request does what is says, so I'm going to approve those changes.
