### PR TITLE
Framework: add back some site options for nudges

### LINKED ISSUE #14879: Media: Videos and Audio tabs prompt for upgrade on already upgraded site
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/media/audio/ or https://wordpress.com/media/videos/ on a site with a Premium or Business plan
2. Note that you are prompted to upgrade to upload audio or video despite having a valid plan. The All tab and WP Admin allow you to upload videos and audio as expected. 

#### What I expected
To be able to see existing audio and video uploads and add further files.

#### What happened instead
I see a prompt to upgrade.

#### Browser / OS version
Macintosh OS X 10.11.6, Chrome 58.0.3029.110

#### Screenshot / Video
screen shot 2017-06-07 at 4 28 36 pm
screen shot 2017-06-07 at 4 28 39 pm

#### Context / Source
#user-report

### PR DESCRIPTION
**Pull request by gwwar**
Fixes #14879 where we would prompt users to upgrade when they already had a plan. Regression caused by #14096

#### Testing Instructions
1. Navigate to http://calypso.localhost:3000/media/audio/:siteId: or /media/videos/:siteId: on a site with a Premium or Business plan
2. We should see the video/audio tab without being prompted to upgrade

### CODE REVIEW

File: client/state/jetpack-connect/actions.js [hunk 1]
```diff
@@ -360,7 +360,7 @@ export default {
...
 					fields: 'ID,URL,name,capabilities,jetpack,visible,is_private,is_vip,icon,plan,jetpack_modules,single_user_site,is_multisite,options', //eslint-disable-line max-len
-					options: 'is_mapped_domain,unmapped_url,admin_url,is_redirect,is_automated_transfer,allowed_file_types,show_on_front,main_network_site,jetpack_version,software_version,default_post_format,created_at,frame_nonce,publicize_permanently_disabled,page_on_front,page_for_posts,advanced_seo_front_page_description,advanced_seo_title_formats,verification_services_codes,podcasting_archive,is_domain_only,default_sharing_status,default_likes_enabled,wordads' //eslint-disable-line max-len
+					options: 'is_mapped_domain,unmapped_url,admin_url,is_redirect,is_automated_transfer,allowed_file_types,show_on_front,main_network_site,jetpack_version,software_version,default_post_format,created_at,frame_nonce,publicize_permanently_disabled,page_on_front,page_for_posts,advanced_seo_front_page_description,advanced_seo_title_formats,verification_services_codes,podcasting_archive,is_domain_only,default_sharing_status,default_likes_enabled,wordads,upgraded_filetypes_enabled,videopress_enabled' //eslint-disable-line max-len
```
Comment (gwwar) [inline client/state/jetpack-connect/actions.js]: As an aside, I would recommend doing this option filter in one place. It'd be very easy to drift. It's also kind of random that we're doing a direct network request here.

**Comment by gwwar** [comment]
Thanks for the review @roundhill !

**Comment by mtias** [comment]
@gwwar should be added to https://github.com/Automattic/wp-calypso/blob/master/client/state/sites/actions.js#L92 as well.

**Comment by gwwar** [comment]
Thanks @mtias, do you think we can move these options in another PR to a single util/const file?
