### PR TITLE
Gutenframe: Open FSE links to the customizer in parent frame

### LINKED ISSUE #34005: Full Site Editing: Support navigation to the customizer from /block-editor [3]
As a follow up to https://github.com/Automattic/wp-calypso/issues/33108 and https://github.com/Automattic/wp-calypso/issues/33109 some blocks link to the customizer from the editor.

screen-shot-2019-04-23-at-11 25 44-am

Doing so from WordPress.com/block-editor will turn into a sad-browser, because X-Frame-Options are set to same origin. Let's add the appropriate integration to allow for this navigation.

To reproduce:
- Start from WordPress.com/block-editor
- Insert an a8c navigation block
- Click Edit

See: PCYsg-jzC-p2 and PCYsg-lwV-p2 for context

### PR DESCRIPTION
**Pull request by mmtr**
#### Changes proposed in this Pull Request

Previously, the links to the customizer of the FSE blocks' edit buttons were opened in the child frame of the WordPress.com block editor, causing a sad-browser error because the customizer is not allowed to be embed in an iframe.

Furthermore, those links were pointing to the WP Admin customizer, but we should use the Calypso Customizer (`https://wordpress.com/customize/:domain`) on WP.com sites.

This PR ensures that we open the Calypso Customizer when the edit links of the FSE blocks are clicked by sending a message to the client side that caused a navigation to the Customizer within Calypso.

#### Testing instructions

- Update the `wpcom-block-editor` build of your sandbox following instructions available at PCYsg-l4k-p2#building-and-testing-changes.
- Make sure the Full Site Editing plugin is available in your sandbox by following instructions available at PCYsg-ly5-p2#activating-the-plugin-on-wordpress-com.
- Go to http://calypso.localhost:3000/block-editor and select your sandbox site.
- Insert any FSE block that contains an edit link to the customizer (i.e. 'Navigation Menu' or 'Site Logo').
- Click on the edit button of the block (the one with the pencil icon).
- Make sure the Customizer is opened on the parent frame and you get the Calypso Customizer (`http://calypso.localhost:3000/customize/:domain`) instead of the  WP Admin Customizer (`:domain/wp-admin/customize.php`).

Fixes #34005

### CODE REVIEW

File: apps/wpcom-block-editor/src/calypso/iframe-bridge-server.js [hunk 1]
```diff
@@ -560,6 +560,26 @@ function openLinksInParentFrame() {
...
 }
 
+/**
+ * Ensures the Calypso Customizer is opened when clicking on the the FSE blocks' edit buttons.
+ *
+ * @param {MessagePort} calypsoPort Port used for communication with parent frame.
+ */
+function openCustomizer( calypsoPort ) {
+	const customizerLinkSelector = 'a.components-button[href*="customize.php"]';
+	$( '#editor' ).on( 'click', customizerLinkSelector, e => {
```
Comment (kwight) [inline apps/wpcom-block-editor/src/calypso/iframe-bridge-server.js]: Why do we use this selector filtering, instead of using `customizerLinkSelector` as the primary selector?

Comment (gwwar) [reply apps/wpcom-block-editor/src/calypso/iframe-bridge-server.js]: The above binds the click event handler to the editor div. So if the other selector is dynamically added we don't need to add a click event on the child when it's created.

See also http://api.jquery.com/delegate/

**Comment by kwight** [comment]
Beautiful, beautiful magic 😍

While working perfectly for the Navigation Menu block, it doesn't work with the Site Logo block, since it doesn't have a proper `href` on the button (it's all done through a click handler). This is fine though, as the Site Logo block will likely be simplified to a customized Image block, no longer requiring use of the Customizer.

**Review by kwight — APPROVED** [review]

File: apps/wpcom-block-editor/src/calypso/iframe-bridge-server.js (hunk 1 above)
Comment (kwight) [reply apps/wpcom-block-editor/src/calypso/iframe-bridge-server.js]: Ah! I knew I was missing something – I get it now 👍
