### PR TITLE
ETK Nav Sidebar: Use site icon for menu toggle when available

### LINKED ISSUE #51740: W logo visually broken in the editor
In the editor, the W logo is visually broken:

I don't remember seeing this border on hover before — I think the whole area just used to have brighter color on hover:

Screenshot 2021-04-07 at 11 36 32

And when I open the drawer, site title/logo breaks up, and border around logo remains visible:

Screenshot 2021-04-07 at 11 36 04

I believe the code for side nav is here: https://github.com/Automattic/wp-calypso/tree/714324a537c380b2d6135c95af9838b25247229b/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar

Themes I tested:
- Independent Publisher 2
- Alves
- Atomic Blocks

Plugins:
Gutenberg: v10.3.1-with-autocomplete-fix
CoBlocks: 2.5.3
Editing Toolkit: 3.3976
WP AMP: 1.4.2

### PR DESCRIPTION
**Pull request by creativecoder**
#### Changes proposed in this Pull Request

Use the site icon for toggling the editor sidebar menu (when in full screen mode), rather then the default "W" icon.

Related to #51396
Related to #51482
Resolves #51740

| Closed | Open |
| - | - |
| Screen Shot 2021-04-05 at 22 49 17 | Screen Shot 2021-04-05 at 22 49 31 |

#### Testing instructions

Testing this requires install the Editing Toolkit plugin, v10.3.0 or higher of the Gutenberg plugin, and wpcomsh (for dot org sites). I recommend a8c-wp-env (for installing all dependencies), or installing the plugin zip to an Atomic site (PCYsg-ly5-p2#etk-and-atomic-sites).

Note that the [sidebar menu styles were changed](https://github.com/WordPress/gutenberg/pull/29888) in v10.3 of Gutenberg (the current release). If you wanted to be thorough, you could test with a previous version of the plugin as well (I did while I was developing and it looked okay).

1. Set a site icon, using either the Customizer or Settings (Calpyso version)
1. Open a page or post in the editor
1. You should see the site icon used to toggle the sidebar.
1. Ensure focus and hover styles, as well as keyboard navigation, work as expected

Note that this requires D59822-code to work for Simple sites.

### CODE REVIEW

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/site-icon/index.tsx [hunk 1]
```diff
@@ -0,0 +1,35 @@
+/**
+ * External dependencies
+ */
+import React from 'react';
+import { useSelect } from '@wordpress/data';
+import { Icon, wordpress } from '@wordpress/icons';
+import { __ } from '@wordpress/i18n';
+
+export default function SiteIcon(): JSX.Element {
+	const currentSiteId: number = window._currentSiteId;
```
Comment (ciampo) [inline apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/site-icon/index.tsx]: The `number` type is not necessary, as `_currentSiteId` is already typed [here](https://github.com/Automattic/wp-calypso/blob/93741c3debcefb5a8c317ca858d1031389dda34e/apps/editing-toolkit/typings/index.d.ts)

```suggestion
	const currentSiteId = window._currentSiteId;
```

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/site-icon/index.tsx [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+
+	// The site icon url should be available from /wp/v2/settings or similar in the future,
+	// but for now it's accessible at the index endpoint.
+	// https://github.com/WordPress/gutenberg/blob/68c3978be352c6d3982f73bcf8c80744608c53c8/lib/init.php#L160
```
Comment (ciampo) [inline apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/site-icon/index.tsx:12]: Should we open a follow-up PR to track this task?

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/site-icon/index.tsx [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+	const siteIconUrl = useSelect(
+		( select ) => {
+			const { getEntityRecord } = select( 'core' );
+			const siteData = getEntityRecord( 'root', '__unstableBase', undefined ) || {};
```
Comment (ciampo) [inline apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/site-icon/index.tsx]: TypeScript is not happy with the third argument being `undefined`:

```Argument of type 'undefined' is not assignable to parameter of type 'number'.```

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/site-icon/index.tsx [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+import { Icon, wordpress } from '@wordpress/icons';
+import { __ } from '@wordpress/i18n';
+
+export default function SiteIcon(): JSX.Element {
+	const currentSiteId: number = window._currentSiteId;
+
+	// The site icon url should be available from /wp/v2/settings or similar in the future,
+	// but for now it's accessible at the index endpoint.
+	// https://github.com/WordPress/gutenberg/blob/68c3978be352c6d3982f73bcf8c80744608c53c8/lib/init.php#L160
+	const siteIconUrl = useSelect(
```
Comment (ciampo) [inline apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/site-icon/index.tsx]: Currently, `siteIconUrl` is of type `any`

```suggestion
	const siteIconUrl: string | undefined = useSelect(
```

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/toggle-sidebar-button/style.scss [hunk 5]
```diff
@@ -1,9 +1,15 @@
...
 
 .wpcom-block-editor-nav-sidebar-toggle-sidebar-button__button {
 	height: $header-height !important;
 
+	// Match this animation with the nav-sidebar, so that the button is not hidden
+	// before the sidebar menu finishes sliding out.
 	&.is-hidden {
 		visibility: hidden;
+		animation: visibility $sidebar-transition-period linear;
+		@include reduce-motion( 'animation' );
```
Comment (ciampo) [inline apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/toggle-sidebar-button/style.scss]: From my tests, the icon button used to open the sidebar still gets hidden before the sidebar finishes animating.

Did you mean to use the CSS `transition` property, instead of `animation` ?


```suggestion
	// Match this animation with the nav-sidebar, so that the button is not hidden
	// before the sidebar menu finishes sliding out.
	&.is-hidden {
		visibility: hidden;
		transition: visibility $sidebar-transition-period linear;
		@include reduce-motion( 'transition' );
```

Using `transition` should delay the icon button's disappearance correctly (although the button will still disappear abruptly, since the `visibility` property can't be animated gradually)

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/style.scss [hunk 6]
```diff
@@ -70,10 +70,11 @@ $sidebar-button-text-color: #a2aab2; // former $light-gray-900
 .wpcom-block-editor-nav-sidebar-nav-sidebar__header {
 	box-sizing: content-box;
 	background-color: $sidebar-nav-header-background-color;
+	display: flex;
```
Comment (ciampo) [inline apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/style.scss:73]: Love the switch to flexbox instead of `position: fixed`

**Review by ciampo — COMMENTED** [review]
I left a few inline comments, but overall this PR tests well as per instructions, including hover and focus styles

Tested on an Atomic site with Gutenberg 10.3.1 (my site's icon is an orange square):

https://user-images.githubusercontent.com/1083581/113740423-f750e480-9700-11eb-841e-ec9baa814b6a.mp4


Also, it seems like the unit tests CI task is failing, which is not ideal — could you try rebasing to see it if fixes it?

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/site-icon/index.tsx (hunk 1 above)
Comment (creativecoder) [reply apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/site-icon/index.tsx]: Thanks! I also realized using `_currentSiteId` was left over from a previous version I tried and no longer needed, so I've removed it.

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/site-icon/index.tsx (hunk 3 above)
Comment (creativecoder) [reply apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/site-icon/index.tsx]: I resolved the type error, but it's a bit ugly! I'd imagine the types will be updated in Gutenberg if and when the `__unstableBase` becomes "stable".

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/site-icon/index.tsx (hunk 4 above)
Comment (creativecoder) [reply apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/site-icon/index.tsx]: Updated, thanks.

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/site-icon/index.tsx (hunk 2 above)
Comment (creativecoder) [reply apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/site-icon/index.tsx:12]: Good point, issue here: https://github.com/Automattic/wp-calypso/issues/51722

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/toggle-sidebar-button/style.scss (hunk 5 above)
Comment (creativecoder) [reply apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/toggle-sidebar-button/style.scss]: Yes, it was a copy paste mistake. Now updated.

**Comment by creativecoder** [comment]
> Also, it seems like the unit tests CI task is failing, which is not ideal — could you try rebasing to see it if fixes it?

Done, I think that did it.

@ciampo Thanks so much for the detailed feedback. This is ready for another look.

**Comment by creativecoder** [comment]
Note that I've created a diff that gets this working with Simple sites, as well: D59822-code

**Review by ciampo — APPROVED** [review]
Tests well as per instructions, and all feedback has been addressed (I just added a [tiny change](https://github.com/Automattic/wp-calypso/pull/51477/commits/2726781ce389eb71185e90e301a9351bec383b1e) that addressed a potential flexbox bug).

I'm going to take over this PR and merge it, since it fixes #51740.

Also, noting that D59822-code needs to be merged in order for the icon to display correctly in Simple Sites

**Comment by creativecoder** [comment]
Thanks for getting this over the line @ciampo ! ❤️
