### PR TITLE
Fix the two year plan upsell in checkout when browser window short

### LINKED ISSUE #70298: [Bug]: Two-year plan upsell in checkout gets cut off if the browser window is too short
### Quick summary

As reported at p1668537497002199-slack-CT1FP5D62, the upsell nudge for two-year plans in checkout can get cut off vertically, if your browser window is too short.

This is most likely to happen with a monthly plan and domain in the cart (since the content above the nudge is taller then) but in theory could happen for anything.

Example (in this screenshot you can see via the left column that I've scrolled all the way down, but since the right column isn't scrollable, it's still not fully visible):

two-years-upsell

@michaeldcain suggested solving this for the monthly case by just removing the two-year upsell (since it duplicates the probably more-relevant annual upsell a bit further up in the sidebar).  This is probably a good idea, although it wouldn't necessarily solve the more general bug in the case of an even-shorter browser window.

### Steps to reproduce

1. Put a non-two-year plan in your shopping cart.
2. Adjust the height of your browser window until you see the bug.

### What you expected to happen

Either the right sidebar content is short enough to fit on my screen, or it is able to scroll.

### What actually happened

The content was cut off.

### Browser

_No response_

### Context

_No response_

### Platform (Simple, Atomic, or both?)

_No response_

### Other notes

_No response_

### Reproducibility

Consistent

### Severity

_No response_

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by spraveenitpro**
The upsell nudge for two-year plans in checkout can get cut off vertically, if your browser window is too short. This PR aims to fix that.

#### Proposed Changes

* We implement a `overflow-y` for the sidebar so that it gets a vertical scrollbar when the height is limited.
* We also add border 1 px to the Upsell card that gets displayed as earlier it was implemented as box shadow which does not work any more.

#### Testing Instructions

1. Put a non-two-year plan in your shopping cart.
2. Adjust the height of your browser window to make it shorter and you should see a vertical scroll appear that will allow you to view the upsell card like below.

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Fixes #70298

### CODE REVIEW

File: client/my-sites/checkout/composite-checkout/components/wp-checkout.tsx [hunk 1]
```diff
@@ -537,6 +537,11 @@ const CheckoutSummaryBody = styled.div`
 		max-width: 328px;
 		position: fixed;
 		width: 100%;
+		overflow-y: auto;
+		height: 100vh;
+	}
+	.card {
```
Comment (sirbrillig) [inline client/my-sites/checkout/composite-checkout/components/wp-checkout.tsx]: I'm not 100% sure about this, but I think that maybe, even though this selector is inside the `styled` call, it might apply globally. I think you should scope it to just this component using the `&` shortcut to say "only cards inside this element".

```suggestion
	& .card {
```

File: client/my-sites/checkout/composite-checkout/components/wp-checkout.tsx [hunk 2]
```diff
@@ -537,6 +537,11 @@ const CheckoutSummaryBody = styled.div`
...
+		border: 1px solid ${ ( props ) => props.theme.colors.borderColorLight };
```
Comment (sirbrillig) [inline client/my-sites/checkout/composite-checkout/components/wp-checkout.tsx]: This looks good at wider widths, but at thinner widths, it looks very thick:

Screenshot 2022-12-07 at 5 57 07 PM

Compare this to how it looks in production:

Screenshot 2022-12-07 at 6 00 25 PM

Honestly, the placement is awkward even before this PR and maybe we should remove the spacing around it at small widths too, but that's beyond the scope of this change.

Comment (spraveenitpro) [reply client/my-sites/checkout/composite-checkout/components/wp-checkout.tsx]: That is correct, looks thick. I have done some changes as it looks like it already had a border top and bottom. Now it looks close to production:

### Viewing it at 100% screen zoom:



### Zooming in further 150%:



@sirbrillig

Comment (sirbrillig) [reply client/my-sites/checkout/composite-checkout/components/wp-checkout.tsx]: That screenshot is desktop width. Did you check mobile width? That's what I'm talking about.

Comment (spraveenitpro) [reply client/my-sites/checkout/composite-checkout/components/wp-checkout.tsx]: oh ok, got it, I think it looks quite close now on the mobile layout:

**Review by sirbrillig — APPROVED** [review]
Looks good to me and works as described!
