### PR TITLE
Jetpack Sync: Show error notice when sync status fails >= 3 times

### LINKED ISSUE #6824: Jetpack Sync: Add error notice for failing sync status request
We should show an error notice if sync status requests fail multiple times in a row. We are not as interested in single failures since we poll every 5 seconds, and it is very possible that the occasional request will fail. But, we should show some error that the site is unresponsive if multiple requests fail.

### PR DESCRIPTION
**Pull request by ebinnion**
Closes #6824.

We currently do not have an error notice if sync status fails. The most likely case for this happening in our UI seems to be if a user loses connection.

Since we poll for sync status, and it is a simple GET request, we're not as interested in one failure. But, if a failure occurs at least 3 times we show a notice.

Here's what it looks like:

screen shot 2016-07-15 at 2 49 35 pm

The "Check Connection" action links to the debugger on the remote Jetpack site.

To test:

- Checkout `update/jetpack-sync-error-notice-multiple-status` branch
- Go to `/settings/general/$site` where `$site` is a Jetpack site with latest `branch-4.2` version of Jetpack
- Click "Perform full sync" button if sync is not already happening
- Open "Network conditions" panel in console, and turn off wifi
- Look at "Network" tab
- Verify that notice shows up after 3 failed statuses
- Click "Check Connection" action and ensure it sends you to remote site (probably right click and open in new tab to not lose state in current tab)
- Turn wifi back on
- Verify that the sync status UI recovers

cc @rickybanister @lezama @gravityrail for code review

Test live: https://calypso.live/?branch=update/jetpack-sync-error-notice-multiple-status

### CODE REVIEW

File: client/my-sites/site-settings/form-general.jsx [hunk 1]
```diff
@@ -471,13 +471,13 @@ const FormGeneral = React.createClass( {
...
 		}
 
-		const site = this.props.site;
+		const { site } = this.props;
 		if ( ! site.jetpack || this.props.site.versionCompare( '4.2-alpha', '<' ) ) {
 			return null;
 		}
 
 		return (
-			<JetpackSyncPanel siteId={ site.ID } />
```
Comment (ebinnion) [inline client/my-sites/site-settings/form-general.jsx]: We don't need this, and never did actually, since we get the selected site out of state.

File: client/my-sites/site-settings/jetpack-sync-panel/index.jsx [hunk 2]
```diff
@@ -60,32 +62,56 @@ const JetpackSyncPanel = React.createClass( {
 		this.props.scheduleJetpackFullysync( this.props.siteId );
 	},
 
+	onClickDebug() {
+		debug( 'Clicked check connection button' );
```
Comment (ebinnion) [inline client/my-sites/site-settings/jetpack-sync-panel/index.jsx]: I know this method is not currently very useful. I will add analytics to it in a follow-up PR.

**Comment by gravityrail** [comment]
LGTM! 👍

**Comment by ebinnion** [comment]
I pinged @rickybanister in Slack, and he seemed to like this approach. So, I'm going to go ahead and merge so I can wrap up sync status. I'll be glad to address any design feedback in follow-up PRs.
