### PR TITLE
Media Library: Enable Access for Contributors

### LINKED ISSUE #35530: Media: Page should show a permission error for contributor users
#### Steps to reproduce 

- Start with a WordPress.com site with a contributor user on it.
- Visit https://wordpress.com/media for that site, as the contributor user.

#### What is expected 

The page isn't actionable by this user, as media uploads are not available for contributor users. [Details](https://en.support.wordpress.com/editors/media-icons/).

#### What happens instead 

The page shows the list of media files uploaded on that site.

There is also a broken bar where typically "Add new" button and the storage space slider appears.

Screenshot 2019-08-18 at 13 59 05

Also, drag-dropping files shows no response. 

#### What is suggested

We should just avoiding showing these media library files, and show a notice that this page is not actionable by contributor users. Something similar to what was proposed in https://github.com/Automattic/wp-calypso/issues/33032.

### PR DESCRIPTION
**Pull request by Aurorum**
After some discussion below, this PR will now open access to the Media Library for contributors, granting access from the sidebar.

Please try testing as both a contributor and another role, then spot any issues. In the Media Library, it should only be possible to view the images, which means that the Edit button is hidden. There should be no differences in the Media Modal. 

Screenshot 2019-08-21 at 10 12 05

Fixes #35530

### CODE REVIEW

**Comment by donpark** [comment]
@Aurorum I don't understand. AFAIK, contributors cannot upload nor publish posts but they can create draft posts with images from site's Media Library and request approval for publishing.

Also using lack of `publish_posts` permission as not having permission to access Media Library seems like a little far fetched.

**Comment by Aurorum** [comment]
> Also using lack of publish_posts permission as not having permission to access Media Library seems like a little far fetched.

Hmm...I'm not sure what the ideal goal is here. I'm happy to update this PR, but I think this is the correct solution as "Media" is already hidden in the sidebar for contributors. This just prevents contributors from directly accessing the link...unless "Media" being hidden for contributors in the sidebar is a bug?

FWIW, the design is now broken for me on production with the admin role 

Screenshot 2019-08-19 at 16 11 27

**Comment by Aurorum** [comment]
So I guess there's two options here:

1. Keep the PR as is, which restricts contributors from accessing the Media Library with the link directly
2. Allow contributors to access the Media Library and add it to the sidebar, but prevent them from being able to edit images and fix up the design. This could make sense as contributors are already able to see the contents of the Media Library in the Media Modal when editing a post 

I suppose the question is which option?

**Comment by donpark** [comment]
> > Also using lack of publish_posts permission as not having permission to access Media Library seems like a little far fetched.
> 
> Hmm...I'm not sure what the ideal goal is here. I'm happy to update this PR, but I think this is the correct solution as "Media" is already hidden in the sidebar for contributors. This just prevents contributors from directly accessing the link...unless "Media" being hidden for contributors in the sidebar is a bug?

I don't know who decided to hide "Media" sidebar menu but  I think that may be a mistake because limiting Contributor to text only post makes the role less useful. Contributors have permissions, at API level, to view, list, and enumerate assets in the Media Library. They also have permission to create draft posts with assets in the Media Library. Whether or not they can use Calypso to do those things, they can do so through API.

> FWIW, the design is now broken for me on production with the admin role
> 
> Screenshot 2019-08-19 at 16 11 27

It's broken for me as well.

**Comment by Aurorum** [comment]
Furtherest I can trace it back to is #8619: https://github.com/Automattic/wp-calypso/pull/8619/files#diff-1d152baa1bf3915176c8d547febcf867R86

Possibly was an oversight to exclude contributors? cc @artpi

**Comment by Aurorum** [comment]
> It's broken for me as well.

Until there's confirmation on which approach to take with the Media Library, I think it's better to fix this in a separate PR. I'm pretty sure it's a regression caused by #35051.

PR in #35598 :)

**Comment by Aurorum** [comment]
Something that also just occurred to me...contributors don't have access to the Media Library in wp-admin. 

Screenshot 2019-08-20 at 14 45 02

**Comment by arunsathiya** [comment]
Just had a chance to circle back here.

>AFAIK, contributors cannot upload nor publish posts but they can create draft posts with images from site's Media Library and request approval for publishing

My understanding has always been that contributors cannot upload images, and there is no "Add image" or featured image section for them on wp-admin. 

I verified this once on a WordPress.com site, and that seems to be the case:

Screenshot 2019-08-20 at 19 49 08

Same on a WordPress.org site:

Screenshot 2019-08-20 at 20 00 12

On WordPress.org site with Gutenberg though, there is a featured image section, which is not actionable:

Screenshot 2019-08-20 at 19 59 32

With this being the behaviour, it looks like there is no way for them to add images, and no way to choose from existing images either. 

>Something that also just occurred to me...contributors don't have access to the Media Library in wp-admin.

Yup, I see the same behaviour on WordPress.com and WordPress.org sites.

These said, feels correct to show a permission warning on https://wordpress.com/media for contributors. 

>Contributors have permissions, at API level, to view, list, and enumerate assets in the Media Library. They also have permission to create draft posts with assets in the Media Library. Whether or not they can use Calypso to do those things, they can do so through API.

But, with this statement, I am lost again. 

And, I tested Calypso editor for a contributor user on a WordPress.com site, and such an user is able to choose from existing images:

Screenshot 2019-08-20 at 20 05 57


More confusions! Perhaps we should get more eyes on this discussion. 🤔

**Comment by Aurorum** [comment]
> My understanding has always been that contributors cannot upload images

I thought the same, that contributors cannot upload images but they can use already uploaded images. I think the question now is whether or not Calypso and wp-admin should be aligned, in which case leave the PR as is, or if contributors should be able to maximise the benefits of their role. Both seem like reasonable options.

**Comment by donpark** [comment]
> we want contributors to be able to use media too

This is from an old comment in WPCOM JSON API endpoint for listing Media Library images. And images added to Media Library are publicly accessible via URL even if they are not used anywhere.

UX wise, Calypso allowing Contributor to use images from Media Library is a convenience feature. Without it, they'll just end up receiving which URL to use from editors or leave blank for fill-in later.

Real problem is the cost of delivering that convenience across the board, meaning Gutenberg and wp-admin. Even if we decide that ability to use Media Library images as Contributor is a Calypso-only feature, we still need to disable Media Library Edit/Delete for Contributors.

**Comment by Aurorum** [comment]
> Real problem is the cost of delivering that convenience across the board, meaning Gutenberg and wp-admin

From what I understand though from @arunsathiya's comment above, that convenience/consistency already isn't happening; Calypso is the exception where contributors _can_ use already uploaded images through the Media Modal. That seems Calypso-only. 

With the exception of the "Edit" and "Delete" button, which I'm assuming could be patched up pretty easily though I've not experimented with them yet, I'm not sure I understand the reasoning to allow contributors access to the Media Modal but not the Media Library.

> Even if we decide that ability to use Media Library images as Contributor is a Calypso-only feature, we still need to disable Media Library Edit/Delete for Contributors.

Yep. Should this be the approach to go with then?

**Comment by donpark** [comment]
> > Even if we decide that ability to use Media Library images as Contributor is a Calypso-only feature, we still need to disable Media Library Edit/Delete for Contributors.
> 
> Yep. Should this be the approach to go with then?

Short of disagreements and new revelations, I think so.

**Comment by Aurorum** [comment]
Okay, I've updated the PR for that to be the case. This should be good to review now.

Screenshot 2019-08-21 at 10 12 05

The only problem is that the tests are failing, and I'm not exactly sure why or how to fix it. I've checked the issue manually, and the issue being reported by the tests isn't actually happening.

Screenshot 2019-08-21 at 10 18 09

File: client/my-sites/media-library/list-item.jsx [hunk 1]
```diff
@@ -20,12 +19,15 @@ import ListItemAudio from './list-item-audio';
...
 /**
  * Style dependencies
  */
 import './list-item.scss';
 
-export default class extends React.Component {
+class MediaLibraryListItem extends React.Component {
 	static displayName = 'MediaLibraryListItem';
 
 	static propTypes = {
```
Comment (donpark) [inline client/my-sites/media-library/list-item.jsx]: New props needs to be appended to `propTypes` to avoid unknown attribute DOM errors via `...props`:
```
isMediaLibrary: PropTypes.bool,
isContributor: PropTypes.bool,
```

File: client/my-sites/media-library/list-item.jsx [hunk 2]
```diff
@@ -143,3 +147,10 @@ export default class extends React.Component {
 		);
 	}
 }
+
+export default connect( state => {
+	return {
+		isContributor: ! canCurrentUser( state, getSelectedSiteId( state ), 'publish_posts' ),
+		isMediaLibrary: getSectionName( state ) === 'media',
+	};
+} )( MediaLibraryListItem );
```
Comment (donpark) [inline client/my-sites/media-library/list-item.jsx]: Got following warning:

screenshot_872

Adding `{}` or `() => {}` as `mapDispatchToProps` cleared the warning.

**Comment by donpark** [comment]
Other than two issues with `MediaLibraryListItem` mentioned above, I tested successfully that:

1. Media sidebar menu is now visible to Contributor.
2. Contributor can now view but not edit or delete images in Media Library.
3. Contributor can now insert but not edit or delete images from Classic Editor.

Making good progress.

**Comment by donpark** [comment]
> The only problem is that the tests are failing, and I'm not exactly sure why or how to fix it. I've checked the issue manually, and the issue being reported by the tests isn't actually happening.

I think `client/my-sites/media-library/test/list-item.jsx` is failing because this PR wraps `MediaLibraryListItem` component with Redux `connect()` which needs a store but Media Library is still using Flux and its tests don't setup Redux store.

I tried rigging a fake Redux store in the failing test but could not get it working.

File: client/my-sites/media-library/list-item.jsx (hunk 2 above)
Comment (Aurorum) [reply client/my-sites/media-library/list-item.jsx]: Thanks, I completely missed those errors!

I'm not sure if I did this correctly but I took a look at some examples in the rest of Calypso and I think I've managed to clear the console errors now.

**Comment by Aurorum** [comment]
I wonder if it's worth just overriding the `is-selected` style with some more CSS instead of trying to prevent that class being applied? I'm not sure it's ideal, but that should fix both issues above (though I think/hope the last commit has already done that), as well as fix the tests.

**Comment by donpark** [comment]
> I wonder if it's worth just overriding the `is-selected` style with some more CSS instead of trying to prevent that class being applied? I'm not sure it's ideal, but that should fix both issues above (though I think/hope the last commit has already done that), as well as fix the tests.

Worth a try if that'll fix the two failing tests.

**Comment by Aurorum** [comment]
I've updated this PR to take a CSS approach. It saves quite a bit of code and should fix the failing tests. Everything should still work the same though!

**Review by donpark — APPROVED** [review]
LGTM

Retested successfully. Good job!
