### PR TITLE
Map Block: kebab-case Data Attributes

### LINKED ISSUE #28792: Map Block: Gets corrupted when added by Contributor
#### Steps to reproduce
1. Starting at URL: /wp-admin/post-new.php as Contributor
2. add a Map block
3. Publish -> Submit for Review
4. See corrupted block and check JS console for errors

#### What I expected

Block behavior shouldn't differ depending on user role

#### What happened instead

Block becomes corrupted. It is unable to modify it by any other user role. 

JS error in console:
```
blocks.min.js?ver=5.0-beta5-43933:2 Block validation: Block validation failed for `jetpack/map` (Object).

Expected:

<div class="wp-block-jetpack-map" data-map_style="default" data-map_details="true" data-points="[]" data-zoom="13" data-map_center="{&quot;longitude&quot;:-122.41941550000001,&quot;latitude&quot;:37.7749295}" data-marker_color="red"></div>

Actual:

<div class="wp-block-jetpack-map" data-points="[]" data-zoom="13"></div>
```

#### Browser / OS version

Chrome / MacOS

#### Screenshot / Video

screencast 2018-11-22 14-07-57

### PR DESCRIPTION
**Pull request by jeffersonrabb**
#### Changes proposed in this Pull Request

In https://github.com/Automattic/wp-calypso/issues/28792 noted that Map block created by a Contributor will break on save. This is because data attributes with underscores are removed from markup for Contributors, although not for higher level users. `data-points` survives but `data-map_style` and others do not. Because they are stripped out, the expected output no longer matches the actual and block is marked as invalid. This PR switches data attributes from snake_case to kebab-case, which survives saves. Also, began having difficulties using `dataset` which seems to convert kebab-case data attribute names to camelcase. Rather than risk that this might be slightly different browser-to-browser, I stopped using `dataset` in favor of explicit data attribute names, e.g. `node.getAttribute( 'data-map-style' )` instead of `node.dataset( 'map-style' )` or `node.dataset( 'mapStyle' )`.

#### Testing instructions

- Spin up JN instance: https://jurassic.ninja/create?wordpress-5-beta&gutenpack&calypsobranch=fix/map-kebab-case-data-attributes
- Enable Jetpack
- Create a Contributor user, and log in as this user
- Create Map block, save.
- Refresh the page. 

The block should remain, without showing the validation error.

Fixes #28792

### CODE REVIEW

File: client/gutenberg/extensions/map/save.js [hunk 1]
```diff
@@ -19,16 +19,16 @@ class MapSave extends Component {
...
-				data-map_style={ mapStyle }
-				data-map_details={ mapDetails }
+				data-map-style={ mapStyle }
+				data-map-details={ mapDetails }
 				data-points={ JSON.stringify( points ) }
 				data-zoom={ zoom }
-				data-map_center={ JSON.stringify( mapCenter ) }
-				data-marker_color={ markerColor }
+				data-map-center={ JSON.stringify( mapCenter ) }
+				data-marker-color={ markerColor }
```
Comment (sirreal) [inline client/gutenberg/extensions/map/save.js]: It really seems like we should be able to automate this better. This puts data into a structure that will be used by `FrontendManagement`, is that correct? It seems like we should have a utility, perhaps just some methods, that put data into and read data from data-attributes in a consistent way.

This bit here could become something like the following rather than manually writing the keys:

```jsx
import { compose, mapKeys, kebabCase } from 'lodash';

function objectToDataAttributes( obj ) {
  return mapKeys( obj, ( _ /* value */, key ) => `data-${ kebab-case( key ) }` );
}

function stringifyValues( obj ) {
  return mapValues( obj, JSON.stringify );
}

const toSpreadableDataAtts = compose( objectToDataAttributes, stringifyValues );

<div
  className={ className, kebabCase }
  { ...toSpreadableDataAtts( attributes ) }
/>
```

Reading would need to `JSON.parse` all the attributes values in `FrontendManagement`, a symmetry I like and would save some conditional handling for different types.

Just some thoughts. Not everything is stringify-able, which would be a limitation. This could be good work for a next version.

File: client/gutenberg/extensions/shared/frontend-management.js [hunk 2]
```diff
@@ -17,18 +17,19 @@ export class FrontendManagement {
 		const { selector } = options;
 		const blockClass = [ '.wp-block', name.replace( '/', '-' ) ].join( '-' );
 		rootNode.querySelectorAll( blockClass ).forEach( node => {
```
[the remark this answers is not in the document]
Comment (simison) [reply client/gutenberg/extensions/shared/frontend-management.js]: Thanks for confirming, good for another PR since it's already in. 👍

File: client/gutenberg/extensions/shared/frontend-management.js [hunk 3]
```diff
@@ -17,18 +17,19 @@ export class FrontendManagement {
 		const { selector } = options;
 		const blockClass = [ '.wp-block', name.replace( '/', '-' ) ].join( '-' );
```
Comment (simison) [inline client/gutenberg/extensions/shared/frontend-management.js]:
```js
[ '.wp-block', name.replace( '/', '-' ) ].join( '-' );
```

This might read more elegantly like so:

```js
`.wp-block-${ name.replace( '/', '-' ) }`
```

Or `@wordpress/blocks` has `getBlockDefaultClassName` [helper](https://github.com/WordPress/gutenberg/blob/94f54892c214ebd014ec126a9575b7e902198ad9/packages/blocks/src/api/serializer.js#L19-L32) which also applies a className filter folks might be using:

```js
getBlockDefaultClassName( name )
```

...I'm just not sure if that filter applies additional classes in some situations, which would probably be an issue for using it in `querySelectorAll()`.

Don't let this comment hold you off merging. :-)

File: client/gutenberg/extensions/map/save.js (hunk 1 above)
Comment (jeffersonrabb) [reply client/gutenberg/extensions/map/save.js]: I had originally wanted a solution like this too, and still would like to add at some point. Here are a few reasons why I didn't pursue, at least for now:

1) This idea of passing block attributes through to the view script by way of data attributes is new and somewhat difficult to describe concisely, so I liked the idea of a highly readable `save()` function at least for the first application of the pattern.
2) I didn't want to incur the cost of JSON.stringify()-ing non-object values, although this is so trivial this was probably a ridiculous concern.
3) I suspected there might be some attribute values that required additional pre-processing before serialization, and wanted to keep that option easily open. In the end I didn't need this.
4) I also anticipate that there might be attributes which we needed _only_ in editor, and didn't want them serialized/de-serialized unnecessarily. This also proved false for the map block.

Anyway, I'd propose deferring this for now for fear it will introduce new issues, and taking a pass at it after v1 of this block ships. Sound OK?

Comment (sirreal) [reply client/gutenberg/extensions/map/save.js]: > I'd propose deferring this for now for fear it will introduce new issues

Yes, please don't include any of these suggestions in this release 🙂

File: client/gutenberg/extensions/shared/frontend-management.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (jeffersonrabb) [reply client/gutenberg/extensions/shared/frontend-management.js]: Ah, wasn't aware. Looking through options in https://css-tricks.com/a-bunch-of-options-for-looping-over-queryselectorall-nodelists/, it seems like the best solution looks like this:

```
const blockNodes = Array.prototype.slice.apply(
	rootNode.querySelectorAll( blockClass )
);
blockNodes.forEach( node => {
```

How does this sound?

File: client/gutenberg/extensions/shared/frontend-management.js (hunk 3 above)
Comment (jeffersonrabb) [reply client/gutenberg/extensions/shared/frontend-management.js]: I'd prefer not to have to import `@wordpress/blocks` here if possible - trying to keep this pretty lean. I'll take your suggestion though, which I agree reads easier.

File: client/gutenberg/extensions/shared/frontend-management.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (jeffersonrabb) [reply client/gutenberg/extensions/shared/frontend-management.js]: Done: https://github.com/Automattic/wp-calypso/pull/28795/commits/740dcb9a22bff5b6a7ed017298fdc444e94f39a0. Going to leave this unmerged for a little bit in case @simison disagrees with the approach.

File: client/gutenberg/extensions/shared/frontend-management.js (hunk 3 above)
Comment (jeffersonrabb) [reply client/gutenberg/extensions/shared/frontend-management.js]: Done: https://github.com/Automattic/wp-calypso/pull/28795/commits/740dcb9a22bff5b6a7ed017298fdc444e94f39a0

File: client/gutenberg/extensions/map/save.js (hunk 1 above)
Comment (jeffersonrabb) [reply client/gutenberg/extensions/map/save.js]: OK great. I'll prepare a PR with this shortly.

File: client/gutenberg/extensions/shared/frontend-management.js [hunk 4]
```diff
@@ -15,20 +15,22 @@ export class FrontendManagement {
 	initializeFrontendReactBlocks( component, options = {}, rootNode ) {
 		const { name, attributes } = options.settings;
 		const { selector } = options;
-		const blockClass = [ '.wp-block', name.replace( '/', '-' ) ].join( '-' );
-		rootNode.querySelectorAll( blockClass ).forEach( node => {
-			const data = this.extractAttributesFromContainer( node.dataset, attributes );
+		const blockClass = `.wp-block-${ name.replace( '/', '-' ) }`;
+		const blockNodes = Array.prototype.slice.apply( rootNode.querySelectorAll( blockClass ) );
+		blockNodes.forEach( node => {
```
Comment (sirreal) [inline client/gutenberg/extensions/shared/frontend-management.js]: For the record: [MDN says `NodeList.prototype.forEach` is not supported in IE.](https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach#Browser_Compatibility)

---

Why not just use a `for` loop?

```js
for (var i = 0; i < myNodeList.length; i++) {
  var item = myNodeList[i];
}
```

**Comment by simison** [comment]
Would `for...of` work nicely here?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of

I'm fine with anything that translates it to real array first. Simple
spread might do the job and reads well: `[...nodelist].for each()`

**Comment by simison** [comment]
Ah, Jon was faster to recommend for...of. Darn phone screens. :-D

Plenty patterns to choose from!

**Comment by jeffersonrabb** [comment]
Here's `for of` - nice and simple and oldschool. How's it look? https://github.com/Automattic/wp-calypso/pull/28795/commits/f6d702f762f4ac2f7c6f6aca17c4f2aec4c9f0a6

**Comment by jeffersonrabb** [comment]
Re-tested in a range of browsers and found one additional `nodeList.forEach` problem which caused the block to fail in IE. Resolved in https://github.com/Automattic/wp-calypso/pull/28795/commits/7ed0b77b66be652401ea76a742ff374d30ec9441
