### PR TITLE
Editor: Display warning on accordion toggle if broken connection exists

### LINKED ISSUE #3277: Editor: Increase visibility of broken connections
Currently, if a user has a broken Publicize connection, they must expand the Sharing accordion in the editor for this to be apparent. We should seek to improve this experience to reduce the likelihood that posts fail to Publicize to the user's confusion and frustration.

Two suggestions:
- Add an icon to the accordion header to visually indicate a broken connection, even when the accordion is collapsed
- Display a warning prompt to the user if they try to publish the post while a selected connection is broken

### PR DESCRIPTION
**Pull request by aduth**
Closes #3277

This pull request seeks to improve the visibility of broken Sharing connections in the post editor by displaying a warning in the accordion toggle.

| Before | After |
| --- | --- |
| Before | After |

Many services' tokens are not permanent, and unless a user expands the sharing accordion or visits their connection settings screen, they will not be made aware that the connection is broken, leading to frustration when the post fails to Publicize.

**Testing instructions:**

Verify that a status indicator is shown in the Sharing accordion toggle if a broken connection exists for the site and user. It's easiest to test using a service that allows you to revoke an integration (e.g. Twitter). Due to connection status caching, it's also preferred that you test using two sites.
1. Navigate to http://calypso.localhost:3000/sharing
2. Select a site
3. Click Connect on the Twitter connection heading
4. Connect to a Twitter account
5. Confirm the connection after returning to Calypso
6. Navigate to https://twitter.com/settings/applications
7. Revoke WordPress
8. Navigate to http://calypso.localhost:3000/sharing
9. Select a _different_ site
10. Click Connect on the Twitter connection heading
11. _Do not_ authorize the connection, simply close the modal
12. Confirm the connection established in step 4
13. The connection should show as broken (needing Reconnect) after established
14. Navigate to the post editor for this site
15. Note that the Sharing accordion displays a warning indicator, linking back to the connections screen

Also verify that the demonstration on [DevDocs Design](http://calypso.localhost:3000/devdocs/design/accordion) includes a working example of an Accordion including status.

### CODE REVIEW

**Comment by folletto** [comment]
Excellent idea. :)

I feel the indicator would be better at `18px` instead of `24px`. I did a test and seems evident enough already, while having a better balance. :)

**Comment by aduth** [comment]
Thanks @folletto . Decreased size of Gridicon and updated original comment with new "After" screenshot.

**Comment by folletto** [comment]
Design wise: 👍

File: client/components/accordion/status.jsx [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+		position: PropTypes.string,
+		onClick: PropTypes.func
+	};
+
+	static defaultProps = {
+		type: 'info',
+		onClick: () => {}
+	};
+
+	state = {};
```
Comment (obenland) [inline client/components/accordion/status.jsx]: Is this needed?

**Comment by aduth** [comment]
>In a perfect _[...]_ the accordion wouldn't open when clicking the link

Does it? That's what the `event.stopPropagation()` was meant to address in the status component. I'll plan to take a look.

File: client/post-editor/editor-sharing/accordion.jsx [hunk 2]
```diff
@@ -100,11 +104,23 @@ const EditorSharingAccordion = React.createClass( {
...
 		}
 
+		let status;
+		if ( this.props.hasBrokenConnection ) {
+			status = {
+				type: 'warning',
+				text: this.translate( 'A broken connection requires repair' ),
+				url: `/sharing/${ this.props.site.slug }`,
+				position: isMobile() ? 'top left' : 'top',
+				onClick: this.props.onStatusClick
```
Comment (obenland) [inline client/post-editor/editor-sharing/accordion.jsx]: What do you think about moving `position` and `onClick` into `AccordionStatus`?

File: client/components/accordion/status.jsx (hunk 1 above)
Comment (aduth) [inline client/components/accordion/status.jsx]: >Is this needed?

Missed this comment earlier. We use state taking advantage that it will trigger a re-render and attach the `Tooltip` to the anchor.

Comment (aduth) [inline client/components/accordion/status.jsx]: Or, if the question is whether we need to initialize it as we have here, then yes, because by default a component's `state` is `undefined`. We could account for this in `render` but I think it's useful as a reference that we do use state in the component (maybe even more useful if we included the keys that will ever exist, even if `null` to begin with).

File: client/post-editor/editor-sharing/accordion.jsx (hunk 2 above)
Comment (aduth) [inline client/post-editor/editor-sharing/accordion.jsx]: >What do you think about moving `position` and `onClick` into `AccordionStatus`?

I'm not clear on what exactly you mean by this

**Comment by aduth** [comment]
Pushed rebase to resolve conflicts.

>In a perfect _[...]_ the accordion wouldn't open when clicking the link

So I still wasn't able to reproduce this in the editor, but was able to in the DevDocs demo. In d8ac453, I moved the status component outside the clickable header toggle, so it no longer needs to try to stop propagation and no longer toggles the contents when clicked. Mind giving it another go?

**Comment by obenland** [comment]
Looks good, thanks for the update!

Another thing I just noticed is that the "Reconnect" link in the expanded section opens the Sharing section in a new tab (I assume to prevent the AYS message for unsaved changes). Maybe that behavior could be aligned in a new PR?

**Comment by obenland** [comment]
I think this is good to go after conflicts are resolved
