### PR TITLE
[Gutenberg 7.7.1]: Fix editor close button

### LINKED ISSUE #40315: Gutenberg 7.7.1 update on wpcom: fix back button URL
With Gutenberg 7.7.1, this:

image

...is replaced with this:

image

We need to ensure getting back to the editor works equally well with W logo. We might just need fixing some selectors.

Be mindful of wpcom-FSE sites! You can get one via https://horizon.wordpress.com/start/test-fse

### LINKED ISSUE #40334: Dotcom FSE: remove close button on Gutenberg 7.7
Out custom functionality to remove the default back button and replace it with our custom one doesn't work with Gutenberg 7.7 update. We need to update the functionality in order to remove the newly added `W` close button:

Screenshot 2020-03-20 at 14 56 40

Our custom button is still inserted correctly but there is a styling issue with the right border that should be addressed as part of this task.

### PR DESCRIPTION
**Pull request by razvanpapadopol**
### Block editor updates:
- update function to close editor and ignore existing URL
- update tracking
- update e2e gutenberg lib

### FSE updates:
- remove W button
- fix back button positioning

#### Testing instructions
Here is a diff for testing the wpcom-block-editor: D40709-code.

Checkout this PR locally and sync **wp-block-editor** widget and **FSE** plugin using FSE Plugin Development instructions in FG.
* On a non-FSE site start editing a page or post.
* Pressing on top-left W button should close the editor.
* On a FSE enabled site, go to `/block-editor/page/[EDGE_STICKERED_SITE].wordpress.com`
* There shouldn't be any W button
* [Backward compatibility] On a site running the previous version of Gutenberg everything should look and work the same as before.

### Follow up:
- fix editor header positioning for smaller screens https://github.com/Automattic/wp-calypso/issues/40335 

Fixes #40315, Fixes #40334  
Part of: #40078

### CODE REVIEW

**Review by vindl — APPROVED** [review]
LGTM! :shipit:

**Comment by vindl** [comment]
Just a note that we'll have to be careful with deployment order here. Block editor diff should probably land around the same time we land Gutenberg plugin update, and at that time we should also sync FSE new plugin version containing these changes.

**Comment by simison** [comment]
Remember that Atomic users can have older Gutenberg version so we should support both for a while.

I think there is a window global for the version?

**Comment by noahtallen** [comment]
`wpcomGutenberg.pluginVersion` should work. Only in the iFrame, I think.

**Comment by noahtallen** [comment]
I think instead of detecting the version, we could just keep both .css selectors instead of removing the old .css selectors.

**Comment by noahtallen** [comment]
If we merge the PR with support for 7.3, then it can be deployed before releasing 7.7.1 (which is ideal, as we don't want the back button to stop working for some gap period of time)

File: apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-editor-close-click.js [hunk 1]
```diff
@@ -9,7 +9,7 @@ import tracksRecordEvent from './track-record-event';
  * @returns {{handler: Function, selector: string, type: string}} event object definition.
  */
 export default () => ( {
-	selector: '.edit-post-fullscreen-mode-close__toolbar',
+	selector: '.edit-post-header .edit-post-fullscreen-mode-close',
```
Comment (noahtallen) [inline apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-editor-close-click.js]: I think it's fine to keep this with the new selector and no longer track the old one.

File: apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js [hunk 2]
```diff
@@ -564,7 +564,7 @@ function handleInsertClassicBlockMedia( calypsoPort ) {
  * @param {MessagePort} calypsoPort Port used for communication with parent frame.
  */
 function handleCloseEditor( calypsoPort ) {
-	$( '#editor' ).on( 'click', '.edit-post-fullscreen-mode-close__toolbar a', e => {
+	$( '#editor' ).on( 'click', '.edit-post-header .edit-post-fullscreen-mode-close', e => {
```
Comment (noahtallen) [inline apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]: I think we should make sure this selector works for both old and new

File: apps/full-site-editing/full-site-editing-plugin/dotcom-fse/plugins/close-button-override/style.scss [hunk 3]
```diff
@@ -31,10 +32,6 @@
 		margin-left: -7px;
 	}
 
-	@media ( max-width: 599px ) {
-		margin-left: -2px;
```
Comment (noahtallen) [inline apps/full-site-editing/full-site-editing-plugin/dotcom-fse/plugins/close-button-override/style.scss]: I think it's fine to have the old version aligned slightly off 👍

File: apps/full-site-editing/full-site-editing-plugin/dotcom-fse/plugins/close-button-override/style.scss [hunk 4]
```diff
@@ -11,7 +11,8 @@
 	display: flex;
 	align-items: center;
 	padding: 9px 10px;
-	margin-left: -8px;
+	margin-left: -24px;
```
Comment (noahtallen) [inline apps/full-site-editing/full-site-editing-plugin/dotcom-fse/plugins/close-button-override/style.scss]: I think it's fine to optimize for the new version and have the old version be aligned a bit off, especially since there might not be a great way to retroactively apply these styles only if using the old version.

File: apps/full-site-editing/full-site-editing-plugin/dotcom-fse/plugins/close-button-override/style.scss [hunk 5]
```diff
@@ -1,6 +1,6 @@
-.post-type-wp_template_part .edit-post-fullscreen-mode-close__toolbar,
-.post-type-page .edit-post-fullscreen-mode-close__toolbar,
-.post-type-post .edit-post-fullscreen-mode-close__toolbar,
+.post-type-wp_template_part .edit-post-header .edit-post-fullscreen-mode-close,
```
Comment (noahtallen) [inline apps/full-site-editing/full-site-editing-plugin/dotcom-fse/plugins/close-button-override/style.scss]: I think we should keep the old and new selectors here so that the button is still hidden for users on the old version

File: test/e2e/lib/gutenberg/gutenberg-editor-component.js [hunk 6]
```diff
@@ -410,7 +410,9 @@ export default class GutenbergEditorComponent extends AsyncBaseContainer {
 	async closeEditor() {
 		return await driverHelper.clickWhenClickable(
 			this.driver,
-			By.css( '.edit-post-fullscreen-mode-close__toolbar, .edit-post-header-toolbar__back' )
+			By.css(
```
Comment (noahtallen) [inline test/e2e/lib/gutenberg/gutenberg-editor-component.js]: e2e tests will use the new version 👍

**Review by noahtallen — COMMENTED** [review]
I "audited" the different classnames to see which ones should work for WP 5.4 AND Gutenberg 7.7.1+, and which ones are fine to drop compatibility with WP 5.4. 

It might cause some visual inconsistency in dotcom-FSE if you've turned of the Gutenberg plugin. But honestly, the plugin is designed to only work with the latest version, _and_ there aren't a large enough number of people using it in the first place. So the subset that could see weird visual things is pretty small (i.e. Atomic user who has kept their original theme and has turned off the Gutenberg plugin).

I did test that this fixes the FSE back button issues on 7.7.1, but I didn't get a chance to test the wpcom fixes. They look good to me though :)

File: apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js (hunk 2 above)
Comment (razvanpapadopol) [reply apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]: Yes, good catch! 🙌 
Fixed in b11651ed6c013a8993d7dc23b0794e548cbc5657

File: apps/full-site-editing/full-site-editing-plugin/dotcom-fse/plugins/close-button-override/style.scss (hunk 3 above)
Comment (razvanpapadopol) [reply apps/full-site-editing/full-site-editing-plugin/dotcom-fse/plugins/close-button-override/style.scss]: Found a way to keep both looking good with an extra className. Done in b88c7e9900fc9e8dc5076ddb65b052d71d28a2cb

File: apps/full-site-editing/full-site-editing-plugin/dotcom-fse/plugins/close-button-override/style.scss (hunk 5 above)
Comment (razvanpapadopol) [reply apps/full-site-editing/full-site-editing-plugin/dotcom-fse/plugins/close-button-override/style.scss]: 👍 Fixed in b88c7e9900fc9e8dc5076ddb65b052d71d28a2cb

File: apps/full-site-editing/full-site-editing-plugin/dotcom-fse/plugins/close-button-override/style.scss (hunk 4 above)
Comment (razvanpapadopol) [reply apps/full-site-editing/full-site-editing-plugin/dotcom-fse/plugins/close-button-override/style.scss]: Added backward support in b88c7e9900fc9e8dc5076ddb65b052d71d28a2cb

**Review by noahtallen — APPROVED** [review]
I did a lot of testing for this PR, and it works fantastically. It can be shipped immediately to simple sites and to FSE :shipit: 

By the way, I also created this diff for the wpcom block editor changes. That can be done at any time now that this works for the old and new versions: D40709-code. 

### dotcom-fse

_With Gutenberg edge:_
✅ SPT navigation on new pages
✅ navigating back from new/existing pages
✅ navigating to and back from template parts like the header/footer
✅ back from new and existing posts

_Without Gutenberg edge:_
✅ SPT navigation on new pages
✅ navigating back from new/existing pages
✅ navigating to and back from template parts like the header/footer
✅ back from new and existing posts

### non-fse/normal sites

_With Gutenberg edge:_
✅ SPT navigation on new pages
✅ navigating back from new/existing pages
✅ back from new and existing posts

_Without Gutenberg edge:_
✅ SPT navigation on new pages
✅ navigating back from new/existing pages
✅ back from new and existing posts
