### PR TITLE
Guided Transfer: Prevent unavailability notice flashing up before load

### LINKED ISSUE #7828: Guided Transfer: Unavailability notice flashes before loading availability the first time
When loading the guided transfer page for the first time for a site, the unavailability notice flashes up while we load the status of guided transfers.
#### Steps to reproduce
1. Clear your local Redux store
2. Go to http://calypso.localhost:3000/settings/export/ yourtestsite.wordpress.com
3. Under the guided transfer heading, notice the unavailability notice appears for a moment before switching to the button:
   unavailableflash

### PR DESCRIPTION
**Pull request by jordwest**
Fixes #7828 

cc @rickybanister 

This prevents the flash of the "Guided Transfer unavailable" message before we've actually loaded the status. Instead, it disables the Purchase button until the status arrives.
### How to test
1. Go to **My Sites > Settings > Export**
2. Notice that when loading the page, the "Purchase Guided Transfer" button is displayed but disabled. After a few moments, the button should become enabled.
3. On master, the "Guided Transfer unavailable" notice is displayed on the very first load during those few moments, even if Guided Transfer is available.
### Before

Before animation
### After

guided_loading
### After (when GT is actually unavailable)

guided_unavailable

cc

### CODE REVIEW

**Comment by rickybanister** [comment]
That seems better!

File: client/my-sites/exporter/guided-transfer-card/index.jsx [hunk 1]
```diff
@@ -35,9 +38,9 @@ const UnavailableInfo = localize( ( { translate } ) =>
 	<div className="guided-transfer-card__unavailable-notice">
 		<span>{ translate( 'Guided Transfer unavailable' ) }</span>
 		<InfoPopover className="guided-transfer-card__unavailable-info-icon" position="left">
-			{ translate( `Guided Transfer is unavailable at the moment. We'll
-				be back as soon as possible! In the meantime, you can transfer your
-				WordPress.com blog elsewhere by following {{a}}these steps{{/a}}`,
+			{ translate( "Guided Transfer is unavailable at the moment. We'll " +
```
Comment (gwwar) [inline client/my-sites/exporter/guided-transfer-card/index.jsx]: We can use single quotes here

File: client/my-sites/exporter/guided-transfer-card/index.jsx [hunk 2]
```diff
@@ -111,6 +115,7 @@ class GuidedTransferCard extends Component {
 const mapStateToProps = state => ( {
```
Comment (gwwar) [inline client/my-sites/exporter/guided-transfer-card/index.jsx]: Minor but we can store the selectedSiteId in a variable since this is used multiple times.
```javascript
const mapStateToProps = ( state ) => {
   const selectedSiteId = getSelectedSiteId( state );
   return {
       siteId,
       siteSlug: getSiteSlug( state, siteId ),
       //... 
   }
```

**Comment by gwwar** [comment]
Codewise this looks fine to me 👍 Have we maybe considered using a placeholder here instead? It's also jarring going from a disabled button state to transfers unavailable.

**Comment by lancewillett** [comment]
Re-ping @jordwest @rickybanister 

(This came up in a search for pull requests pending without an update in last 2 months.)

**Comment by jordwest** [comment]
Thanks for the ping @lancewillett.

@rickybanister any thoughts on using a placeholder here instead?

**Comment by rickybanister** [comment]
I think your solution works pretty ok, but I'd rather see us just not show anything at all until we know the status of GT. The placeholder isn't a very accurate substitute for a button—they were built for text. 

If the concern is showing a disabled button and then removing that button, perhaps we can show nothing until we can fully load the page. Could we then fade in the button with a simple animation, rather than letting it appear.

**Comment by lancewillett** [comment]
Re-ping @jordwest — going to close this one soon (no activity in over 2 months). Still pending and active? Ready to merge?

**Comment by jordwest** [comment]
@rickybanister are you happy to merge this? I think this is an improvement over what's currently there, maybe we could open an issue to improve it further?

**Comment by rickybanister** [comment]
@jordwest yeah, I just tested again, I agree with some of the feedback on this thread that we could likely make this even better, but what we have here is an improvement so no reason to hold out longer.

:merge:
