### PR TITLE
Wait for blocks when triggering the conversion prompt

### LINKED ISSUE #38489: Convert to Blocks Prompt Does Not Display
WordPress.com has a custom integration that detects when:

- Displays the following modal when a post is loaded with a single classic block (HTML soup)
- Clicking on Convert to Blocks should convert the classic block to blocks. (Normally buried under more options)

screen-shot-2019-07-08-at-11 37 12-am

https://github.com/Automattic/wp-calypso/blob/1442ba0d3c802f9f05706294d37c17295e227030/apps/wpcom-block-editor/src/calypso/iframe-bridge-server.js#L29

This currently doesn't work since, the block editor inserts a paragraph block on edits:
Screen Shot 2019-12-17 at 1 30 19 PM

To reproduce this:
- ? > Switch to Classic 
- Publish a post without mixing block content
- Edit the post > ? > Switch to Block Editor
- We should see the modal display

### PR DESCRIPTION
**Pull request by mmtr**
#### Changes proposed in this Pull Request

Seems we cannot rely on `getCurrentPost` for determining if the editor has been initialized and blocks has been added, so the convert to blocks dialog was not being displayed when a post has been created with the classic editor 

This PR replaces that check in favor of `isCleanNewPost` + `getBlocks` which apparently is more reliable.

Screenshot 2019-12-19 at 12 00 16

#### Testing instructions

* Apply D36950-code and sandbox `widgets.wp.com`.
* Switch to the classic editor.
* Publish a post.
* Switch to the block editor.
* Make sure the convert to blocks dialog is displayed when loading the previous post.
* Verify invalid blocks are still autofixed on editor loaded (https://github.com/Automattic/wp-calypso/pull/38397) 

Fixes #38489

### CODE REVIEW

File: apps/wpcom-block-editor/src/wpcom/features/fix-block-invalidation-errors.js [hunk 1]
```diff
@@ -3,25 +3,21 @@
...
-
-	const blocks = select( 'core/editor' ).getBlocks();
+/**
+ * Internal dependencies
+ */
+import { isEditorReadyWithBlocks } from '../../utils';
 
-	if ( blocks.length === 0 ) {
+async function fixInvalidBlocks() {
+	const editorHasBlocks = await isEditorReadyWithBlocks();
```
Comment (gwwar) [inline apps/wpcom-block-editor/src/wpcom/features/fix-block-invalidation-errors.js]: Nice tidying ✨
