### PR TITLE
Newsletter Accent Color: Default input state should be blue

### LINKED ISSUE #67603: Newsletter Accent Color: Default state should be WP blue.
This seems to be a regression.

In case someone cannot reproduce it, please clear your local storage for the domain you are trying to access the screen from.

Image

### PR DESCRIPTION
**Pull request by mashikag**
#### The Issue
Screen Shot 2022-09-09 at 15 00 55

This is a regression that was introduced with: https://github.com/Automattic/wp-calypso/pull/67275

#### Proposed Changes

* If the initial store's value for site accent color is empty string - set the input's value to default

#### Testing Instructions

* Clear local storage for http://calypso.localhost:3000
Screen Shot 2022-09-12 at 10 40 24

* Go to http://calypso.localhost:3000/setup/newsletterSetup?flow=newsletter
* Check that the default color is set correctly once page loads
* Play around with the color picker to ensure contrast checker works as expected too

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Resolves #67603

### CODE REVIEW

File: client/landing/stepper/declarative-flow/internals/steps-repository/newsletter-setup/index.tsx [hunk 1]
```diff
@@ -71,10 +77,10 @@ const NewsletterSetup: Step = ( { navigation } ) => {
 
 	useEffect( () => {
 		const { siteAccentColor, siteTitle, siteDescription, siteLogo } = state;
-		if ( defaultAccentColor.hex === siteAccentColor ) {
-			setAccentColor( defaultAccentColor );
+		if ( siteAccentColor && siteAccentColor !== '' && siteAccentColor !== defaultAccentColor.hex ) {
```
Comment (alshakero) [inline client/landing/stepper/declarative-flow/internals/steps-repository/newsletter-setup/index.tsx:80]:
```suggestion
		if ( siteAccentColor && siteAccentColor !== defaultAccentColor.hex ) {
```

**Review by alshakero — APPROVED** [review]
Code LGTM! But didn't test.

File: client/landing/stepper/declarative-flow/internals/steps-repository/newsletter-setup/index.tsx (hunk 1 above)
Comment (mashikag) [reply client/landing/stepper/declarative-flow/internals/steps-repository/newsletter-setup/index.tsx:80]: Why would we remove the `siteAccentColor !== ''` from this condition? The default state in the `OnboardStore` of the `siteAccentColor` is `''`. If this condition was not here, we would treat the empty string value as a valid hex color, and we would try to obtain its RGB representation. The end result would be what we have now where by default there is no color selected.

Comment (alshakero) [reply client/landing/stepper/declarative-flow/internals/steps-repository/newsletter-setup/index.tsx:80]: Because `siteAccentColor &&` already takes care of that, empty strings are falsy.

Comment (mashikag) [reply client/landing/stepper/declarative-flow/internals/steps-repository/newsletter-setup/index.tsx:80]: Omg... I cannot believe I was not aware of the empty string returning `false`. 😱 For some reason I just assumed it behaves the same as if checking against empty array or an empty object, and no one ever corrected me about this before. Big thanks for that @alshakero ! 😂
