### PR TITLE
Plans: Show Specific Upgrades for Features Advertised in Nudges

### LINKED ISSUE #15671: Plugin Uploads: Highlight business plan when arriving from upgrade nudge
After user clicks on nudge in #15668:

screen shot 2017-06-29 at 17 21 47

### LINKED ISSUE #41041: Offer only Business & Ecommerce plan when coming from the "Install plugin" section.
When a user arrives to the "add/upgrade" plan section coming from them "Install plugin" link, they should only be offered a Business or Ecommerce plan.

#### Steps to reproduce

1. Head to https://wordpress.com/plugins/ on a free site
2. Click on "Upgrade to Business to install a plugin" notice
3. The first option will be to upgrade to Premium or Personal

#### What I expected
I expected to be offered only the plan I need to install plugins, taking into account where I was coming from.

#### What happened instead
I was offered a lower plan which will not let me install plugins and, if I try again, I will probably be asked a further payment, causing quite a but of frustration and confusion.

#### Browser / OS version
MacOS 10.13.6 (17G2307)
Google Chrome 79.0.3945.88

#### Screenshot / Video
install-plugin-offers-simple-site-plan (3)

#### Context / Source

#dogfooding, #manual-testing

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

Upsell nudges should sometimes send you directly to the Checkout, such as with the Plugins screen.

https://github.com/Automattic/wp-calypso/blob/6f17a7b64dbdfb1c39f27ecf45f783a8be3ff283/client/my-sites/plugins/plugins-browser/index.jsx#L518-L533

This PR ensures that they do.  It also ensures that with nudges for the Business Plan, the Premium Plan isn't shown. Currently, this is displayed:

Screenshot 2020-04-13 at 11 34 06

#### Testing instructions

Firstly, go to `/plugins/site` and verify that the nudge redirects directly to Checkout. 

Secondly, go to another Upsell Nudge that shouldn't redirect to Checkout. For example, there's one on `/settings/general/` under "Footer Credit". Click it, and verify that only the Business and eCommerce plans appear. 

Screenshot 2020-04-16 at 11 41 56

cc @sixhours 

Fixes #41041 and fixes #15671 since the plugins nudge will redirect to Checkout again

### CODE REVIEW

File: client/blocks/upsell-nudge/index.jsx [hunk 1]
```diff
@@ -56,11 +56,14 @@ export const UpsellNudge = ( {
 		return null;
 	}
 
-	if ( ! href && site ) {
-		href = addQueryArgs( { feature, plan }, `/plans/${ site.slug }` );
-	}
+	const customerType = plan === 'business-bundle' ? 'business' : 'personal';
```
Comment (mmtr) [inline client/blocks/upsell-nudge/index.jsx:59]: I'd suggest to use the `PLAN_BUSINESS` constant instead of having hardcoded the value.
```suggestion
	const customerType = plan === PLAN_BUSINESS ? 'business' : 'personal';
```

(Note that you'd need to import it first: `import { PLAN_BUSINESS } from 'lib/plans/constants';`)

Also, is there any reason why this defaults to `personal`? What if the given plan is neither Business or Personal ([example](https://github.com/Automattic/wp-calypso/blob/b081c32d30efdfdcb40119808ff5a9666477bfbf/client/my-sites/activity/activity-log-banner/upgrade-banner.jsx))? Or if no plan is given ([example](https://github.com/Automattic/wp-calypso/blob/b081c32d30efdfdcb40119808ff5a9666477bfbf/client/components/tinymce/plugins/simple-payments/dialog/index.jsx#L477-L488))?

Comment (Aurorum) [reply client/blocks/upsell-nudge/index.jsx]: > I'd suggest to use the PLAN_BUSINESS constant instead of having hardcoded the value.

That reminds me to make this work with the eCommerce plan too! I'm not sure if there's any examples of an eCommerce nudge yet, but I've made it work with that too. 

(It can be tested by switching `PLAN_BUSINESS` to `PLAN_ECOMMERCE` with one of the nudges)

Anyway, I've updated that now! 

> Also, is there any reason why this defaults to personal? What if the given plan is neither Business or Personal (example)? Or if no plan is given (example)?

Just to be clear, `personal` (along with `business`) in this case doesn't refer to the plan name; it refers to the Personal and Premium plan which is displayed on the Plans page.

https://github.com/Automattic/wp-calypso/blob/6835546ab0c857b638afaaa7226d07390be8e092/client/my-sites/plans-features-main/index.jsx#L308

Currently, the customerType refers to the following:

- `personal`: Personal/Premium Plans
- `business`: Premium/Business/eCommerce Plans

This PR would remove Premium from the `business` customerType but _only_ if a nudge has immediately been clicked - there are no wider changes overall. This is ideal because otherwise people would click a nudge for a feature and see the Premium Plan, when in reality, that feature would require a Business or eCommerce plan.

As such, in the examples you've mentioned on the Activity Log and Simple Payments, nothing would change with this PR: people would still be offered the Personal and Premium plan after clicking the nudge. :)

**Comment by gwwar** [comment]
🤔 @mmtr do you think there's an A/B test active here? I'm not seeing the tab options in the plans page on a test account but I do on my main.

Screen Shot 2020-04-14 at 3 16 44 PM

Screen Shot 2020-04-14 at 3 16 57 PM

Overall this tests well for me @Aurorum 💖. I might need to reach out to circle for support on the test-client failures.

**Comment by mmtr** [comment]
> 🤔 @mmtr do you think there's an A/B test active here? I'm not seeing the tab options in the plans page on a test account but I do on my main.

Likely caused by this check:

https://github.com/Automattic/wp-calypso/blob/19125eba844f62615f8986982008940c06e7f4b3/client/my-sites/plans-features-main/index.jsx#L425-L427

Seems we display that only when there is a discount active:

https://github.com/Automattic/wp-calypso/blob/19125eba844f62615f8986982008940c06e7f4b3/client/my-sites/plans-features-main/index.jsx#L546-L550

**Comment by mmtr** [comment]
> I might need to reach out to circle for support on the test-client failures.

Created a branch in our repo to see if that could clean up the failures, but it didn't help: https://github.com/Automattic/wp-calypso/pull/41130

File: client/blocks/upsell-nudge/index.jsx (hunk 1 above)
Comment (mmtr) [reply client/blocks/upsell-nudge/index.jsx]: > As such, in the examples you've mentioned on the Activity Log and Simple Payments, nothing would change with this PR: people would still be offered the Personal and Premium plan after clicking the nudge. :)

The problem with my examples is that they are not actually regular but Jetpack plans. But don't worry, I'll make sure to test them 😉

**Comment by Aurorum** [comment]
Just noting that the href prop was fixed in #41115. :) (this still handles which plans are displayed after clicking the nudge though)

**Comment by mmtr** [comment]
Noting that I still get offered the Personal and Premium Jetpack plans for features that are available on Professional plan only.

To reproduce:
- Set up a Jetpack site (install the Jetpack plugin on a self-hosted site and configure it).
- Switch to that site on wordpress.com and go to Manage > Settings > Performance.
- Click on the Jetpack search upsell:
Screen Shot 2020-04-15 at 12 53 48

- Note how the feature is highlighted in the Professional plan, but the other plans are still available:
Screen Shot 2020-04-15 at 12 55 25

File: client/blocks/upsell-nudge/index.jsx [hunk 2]
```diff
@@ -56,11 +56,14 @@ export const UpsellNudge = ( {
...
 
-	if ( ! href && site ) {
-		href = addQueryArgs( { feature, plan }, `/plans/${ site.slug }` );
-	}
+	const customerType = plan === PLAN_BUSINESS || PLAN_ECOMMERCE ? 'business' : 'personal';
+
+	const link =
+		href && site
+			? href
+			: addQueryArgs( { feature, customerType }, `/plans/${ site.slug }?${ plan }` );
```
Comment (mmtr) [inline client/blocks/upsell-nudge/index.jsx:64]: Why don't we add the plan with `addQueryArgs` as well?
```suggestion
			: addQueryArgs( { feature, customerType, plan }, `/plans/${ site.slug }` );
```

File: client/blocks/upsell-nudge/index.jsx [hunk 3]
```diff
@@ -56,11 +56,14 @@ export const UpsellNudge = ( {
 		return null;
 	}
 
-	if ( ! href && site ) {
-		href = addQueryArgs( { feature, plan }, `/plans/${ site.slug }` );
-	}
+	const customerType = plan === PLAN_BUSINESS || PLAN_ECOMMERCE ? 'business' : 'personal';
```
Comment (mmtr) [inline client/blocks/upsell-nudge/index.jsx:59]: We need to probably handle monthly and Jetpack plans here as well. I wonder if we can include a new util in `lib/plans/constants` to centralize the logic:

```
export const PLANS_FOR_BUSINESS_CUSTOMER_TYPE = [
  PLAN_BUSINESS_MONTHLY,
  PLAN_BUSINESS,
  PLAN_BUSINESS_2_YEARS,
  PLAN_ECOMMERCE,
  PLAN_ECOMMERCE_2_YEARS,
  PLAN_JETPACK_BUSINESS,
  PLAN_JETPACK_BUSINESS_MONTHLY,
];

export function isPlanForBusinessCustomerType( plan ) {
	return PLANS_FOR_BUSINESS_CUSTOMER_TYPE.includes( plan );
}
```

Comment (mmtr) [reply client/blocks/upsell-nudge/index.jsx:59]: Actually, just found out that we have [`chooseDefaultCustomerType`](https://github.com/Automattic/wp-calypso/blob/7ace25447946a9188ec4cb667b29b5314f4ed02a/client/lib/plans/index.js#L466), where we get the customer type in `client/my-sites/plans-features-main/index.jsx`:

https://github.com/Automattic/wp-calypso/blob/0f3e445a83f2c54c933564a37d78caa92f014d9c/client/my-sites/plans-features-main/index.jsx#L554-L558

I wonder if we actually have a bug there so it returns the wrong customer type for the given plan.

Comment (Aurorum) [reply client/blocks/upsell-nudge/index.jsx:59]: I think there's two issues which arise from trying to change Jetpack plans:

- Whereas currently, the user could still see all plans after toggling, making this change with Jetpack plans could cause an issue where people are confused why the Personal and Premium plans don't appear when there's no immediate 
- It looks like Jetpack nudges record the feature rather than the plan, unlike WordPress.com ones? 

> I wonder if we actually have a bug there so it returns the wrong customer type for the given plan.

If changing that, should the `business` customerType always exclude the Premium plan? That feels like a bigger and wider change rather than a small bug fix, so this PR just proposes excluding it immediately after a nudge has been clicked for now, but happy to explore that.

Comment (mmtr) [reply client/blocks/upsell-nudge/index.jsx:59]: Let me analyze a bit further the code, but my assumption is that upsells already link to the plans comparison page, passing the needed plan for the feature/plan highlighted in the upsell as a `?plan=` query argument. 

They shouldn't be aware of the customer type. To me, that's a responsibility for `chooseDefaultCustomerType`. I think that changes on this PR could hide the underlying issue, since they are overriding/ignoring whatever `chooseDefaultCustomerType` returns.

Comment (mmtr) [reply client/blocks/upsell-nudge/index.jsx:59]: Alright, I think the problem is not in `chooseDefaultCustomerType` at all. For some reason, we want to show the Premium plan to both customer types, so let's leave that as-is. 

My main concern is that we're adding logic to the upsells that IMO should be handled entirely in the plans comparison, in case we link to that page from other places.

@Aurorum let me know what do you think about this alternate approach. 

Provided that:
- [All upsells link to `/plans/:site/?feature=:feature&plan=:plan`](https://github.com/Automattic/wp-calypso/blob/182ec54971af1e1dbac2bc3670064391e30fc79b/client/blocks/upsell-nudge/index.jsx#L60).
- The passed plan is available as the [`selectedPlan` property](https://github.com/Automattic/wp-calypso/blob/182ec54971af1e1dbac2bc3670064391e30fc79b/client/my-sites/plans-features-main/index.jsx#L512) in `PlansFeaturesMain`.
- Our goal is to hide plans not containing the upsold feature.

What if we just hide any plan that is "lower" than the selected plan?

```
const visiblePlans = this.getVisiblePlansForPlanFeatures( plans );
const availablePlans = visiblePlans.filter( plan => {
  if ( isEcommercePlan( this.props.selectedPlan ) ) {
    return isEcommercePlan( plan );
  }
  if ( isBusinessPlan( this.props.selectedPlan ) ) {
    return isBusinessPlan( plan ) || isEcommercePlan( plan );
  }
  if ( isPremiumPlan( this.props.selectedPlan ) ) {
    return isPremiumPlan( plan ) || isBusinessPlan( plan ) || isEcommercePlan( plan );
  }
  // ...
} );
```

**Comment by sixhours** [comment]
I've cc'ed MarTech to get their thoughts since I'm not super familiar with how upsell nudges should act beyond the component itself.

**Comment by gwwar** [comment]
> Seems we display that only when there is a discount active:

Oh super bizarre. Let's chat with folks on if we can remove this. It's been a Matt want to try and remove unify the experience in Calypso (so removing date gates and such).

**Comment by mmtr** [comment]
> Oh super bizarre. Let's chat with folks on if we can remove this. It's been a Matt want to try and remove unify the experience in Calypso (so removing date gates and such).

pbAPfg-gX-p2

File: client/blocks/upsell-nudge/index.jsx (hunk 3 above)
Comment (Aurorum) [reply client/blocks/upsell-nudge/index.jsx]: Thanks @mmtr, that works really well! I've also added a way to "reset" the plans through the "View all plans" link, as I think that's necessary with this approach to prevent confusion. 

Screenshot 2020-04-16 at 11 41 56

**Comment by Aurorum** [comment]
> Created a branch in our repo to see if that could clean up the failures, but it didn't help: #41130

Those tests are passing now, but it looks like even `setup` is failing here. Not sure why; `test-client` appears to be passing locally.

Screenshot 2020-04-16 at 11 48 39

File: client/blocks/upsell-nudge/index.jsx [hunk 4]
```diff
@@ -56,11 +56,9 @@ export const UpsellNudge = ( {
 		return null;
 	}
 
-	if ( ! href && site ) {
-		href = addQueryArgs( { feature, plan }, `/plans/${ site.slug }` );
-	}
+	const link = href && site ? href : addQueryArgs( { feature, plan }, `/plans/${ site.slug }` );
```
Comment (mmtr) [inline client/blocks/upsell-nudge/index.jsx:59]: Not sure if these changes are intended, but previously we were setting a link to the plans page only when a site was defined. Now we're overriding the given href if no site is selected (i.e. when visiting the [Reader](https://github.com/Automattic/wp-calypso/blob/e7f164a8ef1fa81c0f15a626eb410781e051408b/client/reader/sidebar/reader-sidebar-nudges/index.jsx#L27-L38)), probably causing a broken link to `/plans/undefined` or similar.

File: client/my-sites/plans-features-main/index.jsx [hunk 5]
```diff
@@ -109,6 +114,14 @@ export class PlansFeaturesMain extends Component {
 		return true;
 	}
 
+	isDisplayingPlansNeededForFeature() {
+		const { selectedFeature, selectedPlan, previousRoute } = this.props;
+
+		if ( selectedFeature && selectedPlan && ! previousRoute.startsWith( '/plans/' ) ) {
```
Comment (mmtr) [inline client/my-sites/plans-features-main/index.jsx:120]: Did you add the route check just in case or did you find any case where the user can land in this page coming from other `/plans` router?

File: client/my-sites/plans-features-main/index.jsx [hunk 6]
```diff
@@ -129,12 +142,33 @@ export class PlansFeaturesMain extends Component {
...
 			siteId,
 			plansWithScroll,
-			translate,
 			customHeader,
 		} = this.props;
 
 		const plans = this.getPlansForPlanFeatures();
 		const visiblePlans = this.getVisiblePlansForPlanFeatures( plans );
+		const availablePlans = this.isDisplayingPlansNeededForFeature()
+			? visiblePlans.filter( plan => {
```
Comment (mmtr) [inline client/my-sites/plans-features-main/index.jsx:151]: I think we need to exclude this filter for Jetpack plans. I'm currently getting an empty page when reproducing [these steps](https://github.com/Automattic/wp-calypso/pull/41044#issuecomment-613968844).

Screen Shot 2020-04-16 at 16 31 14

File: client/blocks/upsell-nudge/index.jsx (hunk 4 above)
Comment (Aurorum) [reply client/blocks/upsell-nudge/index.jsx]: Whoops, that's unintentional. Fixed :)

File: client/blocks/upsell-nudge/index.jsx [hunk 7]
```diff
@@ -56,11 +56,9 @@ export const UpsellNudge = ( {
 		return null;
 	}
 
-	if ( ! href && site ) {
-		href = addQueryArgs( { feature, plan }, `/plans/${ site.slug }` );
-	}
+	const link = href ? href : addQueryArgs( { feature, plan }, `/plans/${ site.slug }` );
```
Comment (mmtr) [inline client/blocks/upsell-nudge/index.jsx:59]: I think there is still an error. Before setting a link to `/plans/:site` we need to make sure `site` is defined. Probably it's better to revert all these changes at all.

File: client/my-sites/plans-features-main/index.jsx (hunk 6 above)
Comment (mmtr) [reply client/my-sites/plans-features-main/index.jsx:151]: Alternatively, we could include the Jetpack plan checks (`isJetpackBusinessPlan`, `isJetpackPremiumPlan`, etc) here so we also hide Jetpack plans not containing the upsold feature/plan.

Comment (mmtr) [reply client/my-sites/plans-features-main/index.jsx:151]: Actually the current checks are fine. The problem is that the JP search upsell is setting a wrong link. It links to `/plans/:site?feature=search&plan=jetpack_search`. Note how the plan is `jetpack_search` while it should be `jetpack_business`.

This issue is unrelated to this PR, so I'd suggest to just skip the filter on JP plans and show all of them as previsouly.

File: client/my-sites/plans-features-main/index.jsx (hunk 5 above)
Comment (mmtr) [inline client/my-sites/plans-features-main/index.jsx:120]: As an extra safety check to avoid [the issue I ran into](https://github.com/Automattic/wp-calypso/pull/41044/files#r409621782), we can check the selected feature and plan is valid:

```suggestion
		if ( selectedFeature && isValidFeatureKey( selectedFeature ) && selectedPlan && getPlan( selectedPlan ) && ! previousRoute.startsWith( '/plans/' ) ) {
```

File: client/blocks/upsell-nudge/index.jsx (hunk 7 above)
Comment (Aurorum) [reply client/blocks/upsell-nudge/index.jsx:59]: I think that this can't be reverted, else nudges such as the "Remove the footer credit entirely" one won't work since they don't contain this link. But I don't think there can be a case where `site` is undefined.

https://github.com/Automattic/wp-calypso/blob/ff1fdca234890a0d8dbb95df0e7ce3345fb2e50c/client/blocks/upsell-nudge/index.jsx#L46

Comment (mmtr) [reply client/blocks/upsell-nudge/index.jsx:59]: > I think that this can't be reverted, else nudges such as the "Remove the footer credit entirely" one won't work since they don't contain this link

I think they work currently. At least they work for me when testing in production:

Screen Shot 2020-04-16 at 17 17 52

Which makes with what I see with the current code: we add a link when none is provided and there is a selected site (`! href && site`).

> But I don't think there can be a case where site is undefined.

When `forceDisplay` is true.

File: client/my-sites/plans-features-main/index.jsx (hunk 5 above)
Comment (Aurorum) [reply client/my-sites/plans-features-main/index.jsx]: It's necessary to prevent this issue.

ezgif-6-6fe344aabfa3

File: client/my-sites/plans-features-main/index.jsx (hunk 6 above)
Comment (Aurorum) [reply client/my-sites/plans-features-main/index.jsx:156]: Thank you! The checks you suggested solve the issue with Jetpack Search whilst maintaining the checks for Jetpack nudges with a valid plan. :)  

Screenshot 2020-04-16 at 16 12 27

File: client/blocks/upsell-nudge/index.jsx (hunk 7 above)
Comment (Aurorum) [reply client/blocks/upsell-nudge/index.jsx:59]: Hmm, this confuses me. I say the same thing on production, but when I remove this line and keep `return <Banner { ...props } showIcon={ showIcon } className={ classes } href={ href } />;`, I see this:

Screenshot 2020-04-16 at 16 25 30

Comment (mmtr) [reply client/blocks/upsell-nudge/index.jsx:59]: When you say you remove this line, you mean this one?

```
const link = href ? href : addQueryArgs( { feature, plan }, `/plans/${ site.slug }` );
``` 

I guess you do, but just to confirm, you also add the previous code when removing that line, right?

```
if ( ! href && site ) {
	href = addQueryArgs( { feature, plan }, `/plans/${ site.slug }` );
}
```

**Comment by mmtr** [comment]
@Aurorum can you rebase this branch in order to solve the conflicts?

File: client/blocks/upsell-nudge/index.jsx (hunk 7 above)
Comment (Aurorum) [reply client/blocks/upsell-nudge/index.jsx]: That explains it, oops! Fixed!

**Comment by Aurorum** [comment]
Conflicts resolved 👍

**Comment by Aurorum** [comment]
I wonder if the Jetpack Search nudge should be updated to work with the changes in this PR? A quick look suggests it's one of the only UpsellNudges that doesn't appear to work because it sets the plan to `PRODUCT_JETPACK_SEARCH`, but there's not many other plans prefixed by `PRODUCT`:

https://github.com/Automattic/wp-calypso/blob/57875af4dcc1380a82c2539af89ec8b9aec3d877/client/my-sites/site-settings/search.jsx#L165

**Comment by mmtr** [comment]
> I wonder if the Jetpack Search nudge should be updated to work with the changes in this PR? 

I think it's fine to fix that in a separate PR in order to keep changes here as narrowed as possible.

File: client/my-sites/plans-features-main/index.jsx [hunk 8]
```diff
@@ -129,12 +147,33 @@ export class PlansFeaturesMain extends Component {
...
+						return isEcommercePlan( plan );
+					}
+					if ( isBusinessPlan( selectedPlan ) ) {
+						return isBusinessPlan( plan ) || isEcommercePlan( plan );
+					}
+					if ( isPremiumPlan( selectedPlan ) ) {
+						return isPremiumPlan( plan ) || isBusinessPlan( plan ) || isEcommercePlan( plan );
+					}
+
+					if ( isPersonalPlan( selectedPlan ) ) {
```
Comment (mmtr) [inline client/my-sites/plans-features-main/index.jsx:167]: One of the reasons why we show the tabbed navigation that separates plans for personal sites from plans for business sites is for not showing more than 3 plans at time.

Also, given that the Personal plan is the "lowest" one, can we maybe don't filter the plans on that case?

I guess we can add one more check to `isDisplayingPlansNeededForFeature`:

```
if (
	isValidFeatureKey( selectedFeature ) &&
	getPlan( selectedPlan ) &&
	! isPersonalPlan( selectedPlan ) && 
	! previousRoute.startsWith( '/plans/' )
) {
	return true;
}
```

That way we can remove the 4 plans returned here.

File: client/my-sites/plans-features-main/index.jsx [hunk 9]
```diff
@@ -428,6 +461,37 @@ export class PlansFeaturesMain extends Component {
...
+		let headerText;
+		let subHeaderText;
+		if ( this.isJetpackBackupAvailable() ) {
+			headerText = translate( 'Plans' );
+			subHeaderText = translate(
+				'Get everything your site needs, in one package — so you can focus on your business.'
+			);
+		}
+		if ( this.isDisplayingPlansNeededForFeature() ) {
+			headerText = translate( 'Upgrade plans to access this feature and more' );
```
Comment (mmtr) [inline client/my-sites/plans-features-main/index.jsx:475]: @obi2020 Do you have any suggestion for this copy? For context, we're going to show this when a user clicks on an upsell nudge advertising a feature that is included only on a few selected plans. We'll hide the plans not containing the upsold feature, but we'll show a link so the user can view all plans.

Screenshot 2020-04-16 at 11 41 56

File: client/my-sites/plans-features-main/index.jsx (hunk 8 above)
Comment (mmtr) [reply client/my-sites/plans-features-main/index.jsx:167]: See for example what happens currently with the upsell nudge displayed on the activity log. That feature is included in the Personal plan, so the plans displayed after clicking on "View all plans" don't change at all.

Apr-17-2020 13-02-29

Comment (Aurorum) [reply client/my-sites/plans-features-main/index.jsx]: That makes sense! Updated the PR with that change. :)

**Comment by mmtr** [comment]
Awesome work, @Aurorum! I think this should be good to go now, but seems there is a test that needs to be fixed first. 

```
 FAIL  client/my-sites/plans-features-main/test/index.jsx
  ● Test suite failed to run

    TypeError: Cannot read property 'includes' of undefined

      200 | 		validLocales = config( validLocales );
      201 | 	}
    > 202 | 	if ( validLocales.includes( localeSlug ) && localeSlug !== 'en' ) {
          | 	                  ^
      203 | 		urlParts.pathname = ( localesToSubdomains[ localeSlug ] || localeSlug ) + urlParts.pathname;
      204 | 	}
      205 | 	return urlParts;
```

Let's also wait for any feedback on the copy before landing this.

**Comment by Aurorum** [comment]
I'm a bit confused by this test failure, to be honest. That code appears to be here:

https://github.com/Automattic/wp-calypso/blob/57875af4dcc1380a82c2539af89ec8b9aec3d877/client/lib/i18n-utils/utils.js#L198-L206

But isn't used directly: https://github.com/Automattic/wp-calypso/search?q=prefixLocalizedUrlPath&unscoped_q=prefixLocalizedUrlPath

And `localiseUrl` isn't used in this file. Any ideas what's causing it?

**Comment by kwight** [comment]
> And localiseUrl isn't used in this file. Any ideas what's causing it?

Hm, on a quick look, there's an [instance](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/plans-features-main/index.jsx#L464) of `WpcomFAQ` that seems to use `localizeUrl` – maybe that's related?..

**Comment by Aurorum** [comment]
Thanks @kwight! Still looks like the usages there are ordinary and not unexpected...really not sure how to fix this one!

**Comment by gwwar** [comment]
To fix this, in plans-features-main/test/index.jsx update the config mock to:

```jsx
jest.mock( 'config', () => {
	const fn = () => {
		return [];
	};
	fn.isEnabled = jest.fn( () => true );
	return fn;
} );
jest
```

Basically it's choking on `validLocales = config( validLocales ); ` and the current mock doesn't handle this.

**Comment by Aurorum** [comment]
Thank you! :)

**Comment by gwwar** [comment]
Thank you @Aurorum 💖I think all that's left is checking in with editorial on copy for https://github.com/Automattic/wp-calypso/pull/41044#discussion_r410149571 

I'll ping folks.

**Comment by kristastevens** [comment]
Hello! Thanks for the ping. 

> Upgrade plans to access this feature and more

I would suggest changing this to: 

> Upgrade your plan to access this feature and more

My assumption here is that the customer is being asked to upgrade a single plan.

**Comment by Aurorum** [comment]
Thanks @kristastevens - that assumption is correct, and I've updated the wording to match! :) 

Screenshot 2020-04-20 at 15 10 27
