### PR TITLE
Inline Help: escape `searchQuery` when using `get`

### LINKED ISSUE #23493: Inline Help: search doesn't work with special characters
#### Steps to reproduce
1. Open inline help
2. Type ".com" into the search box

#### What I expected
As the `/rest/v1.1/help/search` request returns valid results, they should be displayed.

#### What happened instead
No results are displayed.

The selectors in `state/inline-help` don't work well with queries that contain special characters, e.g., `.com` or `foo[1]`. The JS code is:
```js
get( state, 'inlineHelpSearchResults.search.items.' + searchQuery );
```
Dots and brackets are interpreted by `lodash.get`.

Cc @lsinger

### PR DESCRIPTION
**Pull request by lsinger**
... so special characters in the search query / key don't get interpreted. This fixes #23493. 

To test:

- Use Inline Help's search. Make sure it works well for regular queries, but also for those containing special characters — e.g., searching for '.com' or '.co.uk' should not result in no results. 

Props @jsnajdr on filling the issue and some pre-PR advice!

### CODE REVIEW

File: client/state/inline-help/selectors.js [hunk 1]
```diff
@@ -33,7 +33,8 @@ export function getSelectedResult( state ) {
  * @return {Boolean}        Whether search results are being requested
  */
 export function isRequestingInlineHelpSearchResultsForQuery( state, searchQuery ) {
-	return !! get( state, 'inlineHelpSearchResults.requesting.' + searchQuery );
+	const allRequesting = get( state, 'inlineHelpSearchResults.requesting' );
+	return !! get( allRequesting, [ searchQuery ] );
```
Comment (spen) [inline client/state/inline-help/selectors.js]: We could use `has` here, which would return a boolean to stat with.
Also, is there benefit to splitting out in to 2 calls? Maybe `has( state, [ 'inlineHelpSearchResults', 'requesting', searchQuery ] )` could work?

Comment (spen) [reply client/state/inline-help/selectors.js]: Not a blocker btw, just a suggestion/thought :)

Comment (lsinger) [reply client/state/inline-help/selectors.js]: Nice idea! `has` doesn't work here though since it can be both set and false at the same time. Using `has` that would always return `true`.

Comment (spen) [reply client/state/inline-help/selectors.js]: Got ya! I thought that might be a possibility! Thanks for the info!
