### PR TITLE
Fix the skipping the site options step

### LINKED ISSUE #57783: Blogger Flow: process does not complete
Reports of the Loading screen never ending when going through the writing intent flow.

**Reproduce:**
From Louis's slack comments:
* proxied not sandboxed was able to repro a couple of times.
* In local dev calypso.localhost
* See video from Louis:
p1636354685105900/1636353578.105000-slack-CRWCHQGUB

Screenshots from Louis's video:
image

image

### PR DESCRIPTION
**Pull request by roo2**
Currently, if the site-options step is skipped, we are getting stuck on the loading screen. https://github.com/Automattic/wp-calypso/issues/57783

This is due to the site-options step being skipped and therefore the dependencies being unavailable, but the signup flow controller was still expecting them. This is because the signup flow controller hadn't been updated to handle skipped steps.

This PR allows the flow to be completed if all of the steps have either been _completed_ OR _skipped_. It extends the existing skipStep functionality for steps that have providesDependencies.

### Testing instructions.

Go to `/start/setup-site/intent?siteSlug=YOUR_TEST_SITE.wordpress.com&flags=signup/hero-flow` and select the `write` intent. Skip the site-options step. Choose the "Start Writing" starting point.

Screen Shot 2021-11-09 at 9 47 56 pm

Also test other flows as this PR modifies code in the flowController which is shared across other onboarding flows.

fixes https://github.com/Automattic/wp-calypso/issues/57783

### CODE REVIEW

File: client/state/signup/progress/schema.ts [hunk 1]
```diff
@@ -29,6 +29,7 @@ export interface StepState {
 	providedDependencies?: string[];
 	status: 'completed' | 'processing' | 'pending' | 'in-progress' | 'invalid';
 	stepName: string;
+	wasSkipped?: boolean;
```
Comment (roo2) [inline client/state/signup/progress/schema.ts:32]: The StepState object already uses the `wasSkipped` property for skipping the `plan` step https://github.com/Automattic/wp-calypso/blob/trunk/client/state/signup/progress/selectors.ts#L24

File: client/lib/signup/flow-controller.ts [hunk 2]
```diff
@@ -317,7 +322,10 @@ export default class SignupFlowController {
 			includes( currentSteps, step.stepName )
 		);
 		const pendingSteps = filter( signupProgress, { status: 'pending' } );
-		const completedSteps = filter( signupProgress, { status: 'completed' } );
+		const completedSteps = filter(
+			signupProgress,
+			( step ) => step.status === 'completed' || step.wasSkipped
```
Comment (arthur791004) [inline client/lib/signup/flow-controller.ts]: Should we need to change this? As the status of skipped step might be `pending`, it will also show in the `pendingSteps`. I feel a little weird 🤔

**Review by arthur791004 — COMMENTED** [review]
I think this might affect the previous step [here](https://github.com/Automattic/wp-calypso/blob/5e43f071e52c9f01d3ccf2a1da6d0f7bf7f1e927/client/signup/navigation-link/index.jsx#L59) and it looks that we might not be able to go back to the skipped step. But it works well after my test.

**Comment by arthur791004** [comment]
Maybe the simple solution is to add the default dependencies `{ siteTitle: '', tagline: '' }` so that `Skip this step` has the same behavior when the user doesn't fill out the form and clicks the `Continue`.

File: client/lib/signup/flow-controller.ts (hunk 2 above)
Comment (roo2) [reply client/lib/signup/flow-controller.ts]: Oh I see what you mean around the naming. I changed it to include skipped steps so that [the check on line 331](https://github.com/Automattic/wp-calypso/blob/trunk/client/lib/signup/flow-controller.ts#L331) passes if the user skipped a step. I've updated the name to be `completedOrSkippedSteps` (it's only used for the one check)

Comment (arthur791004) [reply client/lib/signup/flow-controller.ts]: Oh I mean the skipped steps might also show in `pendingSteps`. For example
```js
const pendingSteps = [ 'site-options'  ]; // as the step.status === 'pending'
const completedOrSkippedSteps = [ 'site-options' ]; // as the step.wasSkipped === true
```

Comment (roo2) [reply client/lib/signup/flow-controller.ts]: ok, I updated pendingSteps to only include steps that were did not skipped. The array is used to process steps later in this function.

**Comment by roo2** [comment]
> Maybe the simple solution is to add the default dependencies { siteTitle: '', tagline: '' } so that Skip this step has the same behavior when the user doesn't fill out the form and clicks the Continue.

Yea I thought of that too, but it felt slightly incorrect because technically the step wasn't submitted but we would still be making the API call to set those properties. I think this current approach is more extensible if we want to skip other steps in the future.

**Review by arthur791004 — APPROVED** [review]

File: client/lib/signup/flow-controller.ts (hunk 2 above)
Comment (arthur791004) [reply client/lib/signup/flow-controller.ts]: 👍

**Comment by roo2** [comment]
@arthur791004 hmmm it looks like there's a problem with this, I just tested how the `add-domain` flow handles skipping steps. It actually specified providesDependencies on `site-or-domain` and `select-domain` steps that aren't provided, and so if `_assertFlowProvidedRequiredDependencies` is run, validation will fail. It only works because dependency validation is not run due to skipped steps... I think that code is implemented incorrectly but it is probably easier/safer just to use the approach that you suggested than to change the other flows. (submitting empty site options `{ siteTitle: '', tagline: '' }`)

File: client/signup/config/steps-pure.js [hunk 3]
```diff
@@ -325,7 +325,7 @@ export function generateSteps( {
 		},
 		'domain-only': {
 			stepName: 'domain-only',
-			providesDependencies: [ 'siteId', 'siteSlug', 'domainItem' ],
+			providesDependencies: [ 'siteId', 'siteSlug', 'domainItem' ], // note: siteId, siteSlug are not provided when used in domain flow
```
Comment (roo2) [inline client/signup/config/steps-pure.js:328]: just adding some warning comments for the next person

File: client/signup/steps/site-options/index.tsx [hunk 4]
```diff
@@ -55,6 +67,7 @@ export default function SiteOptionsStep( props: Props ): React.ReactNode {
 			skipLabelText={ translate( 'Skip this step' ) }
 			isHorizontalLayout={ true }
 			{ ...props }
+			goToNextStep={ skipStep }
```
Comment (arthur791004) [inline client/signup/steps/site-options/index.tsx]: We can just use `defaultDependencies` as followed because it would submit the `defaultDependencies` when you click the skip button. Otherwise, the `submitSignupStep` would be called twice.
```js
defaultDependencies={ {
  siteTitle: '',
  tagline: '',
} }
```

Comment (roo2) [reply client/signup/steps/site-options/index.tsx]: ahh nice 👍

**Review by arthur791004 — APPROVED** [review]
👍
