### PR TITLE
Signup: Show the full price of domains for plan flows without a free domain

### LINKED ISSUE #49992: Signup Domains Step: Suggestions show price as "free" for /start/free and /start/<monthly-plan> flows
### Steps to reproduce the behavior

1. Go to https://wordpress.com/start/free
2. Create an account.
3. Notice that the domain suggestions show the price as "Free".
4. Select a paid domain.
5. You are taken directly to the checkout page and the full price of the domain is applied.

This is also true for monthly plan specific flows which were added in #49601 

#### What I expected to happen

If the user is on a flow for a plan which does not include the free domain, the full price of the domain should be shown in the domain suggestions.

#### What actually happened

The price shown for the domain suggestions was shown as free.

#### Browser / OS version
Chrome 88.0.4324.150 / Catalina 10.15.6 (19G2021). This bug is not dependent on these.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low-Medium (May cause unnecessary questions for happiness)

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
image

### PR DESCRIPTION
**Pull request by aneeshd16**
#### Changes proposed in this Pull Request

Plan-specific flows for the free and monthly plans show the price of the domain suggestion as "Free" even though free domains are not included in these plans. This change fixes this behaviour to show the full price. Please see #49992 for more context.

#### Testing instructions

* Create an account using the `free` or any of the monthly plan-specific flows:
/start/free
/start/personal-monthly
/start/premium-monthly
/start/business-monthly
/start/ecommerce-monthly
* On the domains step, ensure that the full price of the domains is shown.
image

Fixes #49992

### CODE REVIEW

File: client/lib/cart-values/cart-items.js [hunk 1]
```diff
@@ -1317,6 +1337,10 @@ export function getDomainPriceRule( withPlansOnly, selectedSite, cart, suggestio
 		return 'PRICE';
 	}
 
+	if ( isMonthlyOrFreeFlow( flowName ) ) {
```
Comment (ddc22) [inline client/lib/cart-values/cart-items.js:1340]: Maybe this can be combined with the condition above?

**Review by ddc22 — APPROVED** [review]
Minor comment but the rest LGTM 🚢

File: client/lib/cart-values/cart-items.js [hunk 2]
```diff
@@ -1308,7 +1308,27 @@ export function isPaidDomain( domainPriceRule ) {
...
+		flowName &&
+		[
+			'free',
+			'personal-monthly',
+			'premium-monthly',
+			'business-monthly',
+			'ecommerce-monthly',
+		].includes( flowName )
+	);
+};
```
Comment (southp) [inline client/lib/cart-values/cart-items.js:1322]: While the code in general looks good to me, using a flow name here somewhat makes me cautious because I sort of recall we have seen some issues causing by refreshing and back navigation in the past. However, I'm not sure if that's still the case. @niranjan-uma-shankar could you help me confirm if this is safe?

**Review by niranjan-uma-shankar — COMMENTED** [review]
-

**Review by niranjan-uma-shankar — CHANGES_REQUESTED** [review]
Can we do something similar to what is done for the domain-only flow `https://wordpress.com/start/domain`? The prop `forceHideFreeDomainExplainerAndStrikeoutUi ` is used to suppress the explainer and striked out text as [given here](https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/config/steps-pure.js#L331).

While we're at it, would you mind updating the [README](https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/README.md) file with an explanation for the new prop?

**Comment by aneeshd16** [comment]
> Can we do something similar to what is done for the domain-only flow `https://wordpress.com/start/domain`? The prop `forceHideFreeDomainExplainerAndStrikeoutUi ` is used to suppress the explainer and striked out text as [given here](https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/config/steps-pure.js#L331).

Thanks for the review! For testing this, I added `forceHideFreeDomainExplainerAndStrikeoutUi: true,` to the `domains` step. ([here](https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/config/steps-pure.js#L321))
1. The text now reads "First year included in paid plans". (Screenshot below)
1. Starting with the `free` flow, clicking on any paid domain directly leads me to the checkout page, without giving me an opportunity to buy a plan. The full price of the domain is shown in checkout.
1. Starting with any monthly plan flow, the text would convey an incorrect message since monthly plans do not include a free domain.

If we can change this text to "First year included in annual paid plans" or similar, it would work out well. What do you think?

image

**Review by niranjan-uma-shankar — APPROVED** [review]
I realized that my previous comment is not correct. Using `forceHideFreeDomainExplainerAndStrikeoutUi` will show the older domain UI which we don't want. I went through your changes again and they make sense to me, sorry for the confusion. 

LGTM.

File: client/lib/cart-values/cart-items.js (hunk 2 above)
Comment (niranjan-uma-shankar) [reply client/lib/cart-values/cart-items.js:1322]: @southp I don't exactly recollect it. In this case, since we're restricting by flow name, I believe it to be safe. If you happen to recall the issue, do let me know!

**Comment by niranjan-uma-shankar** [comment]
@aneeshd16 I missed to mention this in my review - could you also check on the price display for domain transfer and mapping in the monthly-plan signup flow? 

Screenshot 2021-02-23 at 3 07 06 PM

Screenshot 2021-02-23 at 3 06 58 PM

**Comment by aneeshd16** [comment]
@niranjan-uma-shankar Thanks for flagging this! I see a few more usages of this string - https://github.com/Automattic/wp-calypso/search?q=%22included+in+paid+plans%22

I'll take this into a separate issue.
