### PR TITLE
Remove disabled actions from `DnsRecordsListItem`

### LINKED ISSUE #60680: Confusing UI when trying to edit "Handled by WordPress.com" DNS records
### Quick summary

This is somewhere between a bug and an enhancement.

The new UI to manage custom DNS records will show a "Handled by WordPress" message, but users are still able to click on the three dots menu and the EDIT and DELETE buttons will show, just inactive:
uneditable

This UI is different from the one shown when we interact with an editable record:
editable

### Steps to reproduce

1. Head to wordpress.com/domains/manage
2. Select a domain and click on "Manage DNS Records"
3. Try to edit one of t he DNS records marked as "Handled by WordPress"

### What you expected to happen

Rather than displaying disabled buttons, the drop-down menu should be removed or, even better, upon clicking, the user should see a short message explaining that they cannot edit those DNS records alongside a link to our documentation.

### What actually happened

These buttons were visible but disabled. 

### Context

Dog Fooding.

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

N/A

### Browser, operating system, and other notes

N/A

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

_No response_

### Workaround details

No workarounds per se.

### PR DESCRIPTION
**Pull request by gius80**
## Changes proposed in this Pull Request

This PR remove disabled actions from the popover menu, in domain dns record list item, and hide the entire menu if no actions are available.

It also add a link to support documentation to better explain the role of default CNAME, A and MX records.

dns-records

## Testing instructions

- Build this branch locally or open the live Calypso link
- Select a owned domain, with default DNS record (with email forwarding service enabled) a go to DNS record page (Upgrade->Domains-> DNS record card -> "Manage")
- Verify that
  - Default A record doesn't have popover menu
  - Default CNAME record doesn't have popover menu
  - Default MX record has only Delete action in popover menu
  - All the default records has a Learn more link pointing to [Editing or deleting DNS records](https://wordpress.com/support/domains/custom-dns/#editing-or-deleting-dns-records)

Related to #60680

### CODE REVIEW

File: client/my-sites/domains/domain-management/dns/dns-records-list-item.jsx [hunk 1]
```diff
@@ -52,7 +56,7 @@ function DnsRecordsListItem( { type, name, value, actions, disabled, isHeader, r
 					<span>{ value }</span>
 				</div>
 				<div className="dns-records-list-item__data dns-records-list-item__menu">
-					{ ! isHeader && menu }
+					{ ! isHeader && enabledActions > 0 && menu }
```
Comment (delputnam) [inline client/my-sites/domains/domain-management/dns/dns-records-list-item.jsx]: Since we're not going to show the disabled actions at all any longer, what would you think about just filtering them out from the `DnsRecordData` component when they are passed in as a prop here like `actions={ actions.filter( ( action ) => ! action.disabled ) }`?

Then instead of adding the extra `enabledActions` variable here, we could use `const menu = actions && actions.length > 0 && ( ...`

**Review by delputnam — APPROVED** [review]
This looks good.  I made one suggestion inline to perhaps simplify the logic and avoid adding a new variable.  Otherwise, looks good and works great!

File: client/my-sites/domains/domain-management/dns/dns-records-list-item.jsx (hunk 1 above)
Comment (delputnam) [reply client/my-sites/domains/domain-management/dns/dns-records-list-item.jsx]: One other thought on this...I guess we could go back even further in the call stack and just not return the disabled actions from `getActionsForDnsRecord()` ...then there would be no need to even do the filtering.

Comment (gius80) [reply client/my-sites/domains/domain-management/dns/dns-records-list-item.jsx]: Thanks for the suggestions! I've update the code, it's way better now.

File: client/my-sites/domains/domain-management/dns/dns-records-list.jsx [hunk 2]
```diff
@@ -196,10 +196,15 @@ class DnsRecordsList extends Component {
...
-			{ ...this.editRecordAction, disabled: record.protected_field },
-			{ ...this.deleteRecordAction, disabled: record.protected_field && 'MX' !== record.type },
-		];
+		const actions = [];
+
+		if ( ! record.protected_field ) {
+			actions.push( { ...this.editRecordAction, disabled: false } );
+		}
+		if ( ! ( record.protected_field && 'MX' !== record.type ) ) {
+			actions.push( { ...this.deleteRecordAction, disabled: false } );
```
Comment (delputnam) [inline client/my-sites/domains/domain-management/dns/dns-records-list.jsx]: Since we're always just returning `false` for the `disabled` property here now, I guess we can probably remove this property and remove the checks for it above. Does that seem right?

File: client/my-sites/domains/domain-management/dns/dns-records-list-item.jsx [hunk 3]
```diff
@@ -19,7 +19,7 @@ function DnsRecordsListItem( { type, name, value, actions, disabled, isHeader, r
 			position="bottom left"
 		>
 			{ actions.map( ( action ) => {
-				return (
+				return action.disabled ? null : (
 					<PopoverMenuItem
 						disabled={ action.disabled }
```
Comment (delputnam) [inline client/my-sites/domains/domain-management/dns/dns-records-list-item.jsx]: I guess we could remove the `disabled` test check here too.

File: client/my-sites/domains/domain-management/dns/dns-records-list-item.jsx [hunk 4]
```diff
@@ -19,7 +19,7 @@ function DnsRecordsListItem( { type, name, value, actions, disabled, isHeader, r
 			position="bottom left"
 		>
 			{ actions.map( ( action ) => {
-				return (
+				return action.disabled ? null : (
```
Comment (delputnam) [inline client/my-sites/domains/domain-management/dns/dns-records-list-item.jsx]: If we remove the `disabled` property, then I guess we don't need this conditional here either.

**Review by delputnam — COMMENTED** [review]
This looks so much better @gius80 .  I guess we can remove the entire `disabled` property and the conditions that check for it now too??  (I don't think they're used anywhere else...but you probably want to double-check me on that.)

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7181027

Thank you @gius80 for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7181027).
