### PR TITLE
Playwright: additional tweaks to sidebar.click

### LINKED ISSUE #54614: Playwright: flaky behavior when clicking sidebar menu items as Atomic user.
### Details

Logs:
```
elementHandle.click: Element is not attached to the DOM
=========================== logs ===========================
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
Error:
at Object.captureStackTrace (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/utils/stackTrace.js:50:19)
at Connection.sendMessageToServer (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/connection.js:65:48)
at Proxy.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/channelOwner.js:64:61)
at /home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/elementHandle.js:142:34
at ElementHandle._wrapApiCall (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/channelOwner.js:77:34)
at ElementHandle.click (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/elementHandle.js:141:21)
at SidebarComponent._click (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/sidebar-component.ts:147:23)
at SidebarComponent.gotoMenu (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/sidebar-component.ts:84:4)
at Object.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-media__edit-spec.js:31:5)
```

Playwright logs:
```
2021-07-15T14:34:33.444Z 487 api info: => browserContext.newPage started
2021-07-15T14:34:33.540Z 487 api info: <= browserContext.newPage succeeded
2021-07-15T14:34:33.541Z 487 api info: => page.goto started
2021-07-15T14:34:34.290Z 487 api info: <= page.goto succeeded
2021-07-15T14:34:34.328Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:34.569Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:34.570Z 487 api info: => page.waitForLoadState started
2021-07-15T14:34:35.421Z 487 api info: <= page.waitForLoadState succeeded
2021-07-15T14:34:35.421Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:35.436Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:35.437Z 487 api info: => elementHandle.waitForElementState started
2021-07-15T14:34:35.460Z 487 api info: <= elementHandle.waitForElementState succeeded
2021-07-15T14:34:35.461Z 487 api info: => page.$ started
2021-07-15T14:34:35.464Z 487 api info: <= page.$ succeeded
2021-07-15T14:34:35.464Z 487 api info: => page.fill started
2021-07-15T14:34:35.487Z 487 api info: <= page.fill succeeded
2021-07-15T14:34:35.506Z 487 api info: => page.fill started
2021-07-15T14:34:35.686Z 487 api info: <= page.fill succeeded
2021-07-15T14:34:35.703Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:40.535Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:40.539Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:40.839Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:40.840Z 487 api info: => elementHandle.waitForElementState started
2021-07-15T14:34:40.897Z 487 api info: <= elementHandle.waitForElementState succeeded
2021-07-15T14:34:40.899Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:41.009Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:41.010Z 487 api info: => page.evaluate started
2021-07-15T14:34:41.027Z 487 api info: <= page.evaluate succeeded
2021-07-15T14:34:41.027Z 487 api info: => elementHandle.click started
2021-07-15T14:34:41.301Z 487 api info: <= elementHandle.click succeeded
2021-07-15T14:34:41.302Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:41.721Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:41.722Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:42.220Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:42.221Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:42.245Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:42.245Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:42.387Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:42.388Z 487 api info: => elementHandle.getAttribute started
2021-07-15T14:34:42.786Z 487 api info: <= elementHandle.getAttribute succeeded
2021-07-15T14:34:42.786Z 487 api info: => page.click started
2021-07-15T14:34:43.615Z 487 api info: <= page.click succeeded
2021-07-15T14:34:43.615Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:47.641Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:47.642Z 487 api info: => elementHandle.waitForElementState started
2021-07-15T14:34:47.695Z 487 api info: <= elementHandle.waitForElementState succeeded
2021-07-15T14:34:47.696Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:47.712Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:47.713Z 487 api info: => elementHandle.click started
2021-07-15T14:34:47.816Z 487 api info: <= elementHandle.click succeeded
2021-07-15T14:34:47.817Z 487 api info: => page.waitForFunction started
2021-07-15T14:34:47.840Z 487 api info: <= page.waitForFunction succeeded
2021-07-15T14:34:47.842Z 487 api info: => page.click started
2021-07-15T14:34:48.091Z 487 api info: <= page.click succeeded
2021-07-15T14:34:48.091Z 487 api info: => page.click started
2021-07-15T14:34:48.430Z 487 api info: <= page.click succeeded
2021-07-15T14:34:48.432Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:48.735Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:48.736Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:48.776Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:48.777Z 487 api info: => page.click started
2021-07-15T14:34:48.952Z 487 api info: <= page.click succeeded
2021-07-15T14:34:48.952Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:49.000Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:49.000Z 487 api info: => elementHandle.waitForElementState started
2021-07-15T14:34:49.001Z 487 api info: => page.waitForFunction started
2021-07-15T14:34:49.024Z 487 api info: <= page.waitForFunction succeeded
2021-07-15T14:34:49.025Z 487 api info: <= elementHandle.waitForElementState succeeded
2021-07-15T14:34:49.033Z 487 api info: => page.click started
2021-07-15T14:34:49.177Z 487 api info: <= page.click succeeded
2021-07-15T14:34:49.177Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:49.231Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:49.232Z 487 api info: => page.goto started
2021-07-15T14:34:49.607Z 487 api info: <= page.goto succeeded
2021-07-15T14:34:49.609Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:49.653Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:49.656Z 487 api info: => page.waitForLoadState started
2021-07-15T14:34:50.841Z 487 api info: <= page.waitForLoadState succeeded
2021-07-15T14:34:50.842Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:50.866Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:50.866Z 487 api info: => elementHandle.waitForElementState started
2021-07-15T14:34:50.961Z 487 api info: <= elementHandle.waitForElementState succeeded
2021-07-15T14:34:50.961Z 487 api info: => page.$ started
2021-07-15T14:34:51.001Z 487 api info: <= page.$ succeeded
2021-07-15T14:34:51.005Z 487 api info: => page.click started
2021-07-15T14:34:51.295Z 487 api info: <= page.click succeeded
2021-07-15T14:34:51.295Z 487 api info: => page.fill started
2021-07-15T14:34:51.401Z 487 api info: <= page.fill succeeded
2021-07-15T14:34:51.423Z 487 api info: => page.fill started
2021-07-15T14:34:51.638Z 487 api info: <= page.fill succeeded
2021-07-15T14:34:51.647Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:54.937Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:54.937Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:55.154Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:55.154Z 487 api info: => elementHandle.waitForElementState started
2021-07-15T14:34:55.217Z 487 api info: <= elementHandle.waitForElementState succeeded
2021-07-15T14:34:55.218Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:55.265Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:55.266Z 487 api info: => page.evaluate started
2021-07-15T14:34:55.273Z 487 api info: <= page.evaluate succeeded
2021-07-15T14:34:55.274Z 487 api info: => elementHandle.click started
2021-07-15T14:34:55.450Z 487 api info: <= elementHandle.click failed
2021-07-15T14:34:55.452Z 487 api info: => page.screenshot started
2021-07-15T14:34:55.671Z 487 api info: <= page.screenshot succeeded
2021-07-15T14:34:55.672Z 487 api info: => page.close started
2021-07-15T14:34:55.707Z 487 api info: <= page.close succeeded

```

### Checklist

- [ ]
- [ ]

### Related

_No response_

### PR DESCRIPTION
**Pull request by worldomonation**
#### Changes proposed in this Pull Request

This PR proposes additional tweaks in an effort to make the `_click` method more reliable when interacting with both Simple and Atomic sites.

Changes:
- change the `waitForLoadState` from `domcontentloaded` to `load`
- addition of `waitForElementStable` after a potential scroll has occurred

Background Details:

[navigation lifecycle](https://playwright.dev/docs/navigations/#navigation-lifecycle)

The `domcontentloaded` event is the first one to be fired in a navigation lifecycle and is fired when the document content has been parsed. `load` is fired when _some_ scripts (documentation is unclear what constitutes _some_) have been executed and images/resources loaded. `networkidle` is fired once dynamically loaded scripts are completed and no network requests are made for at least 500ms.

There also exists slight behavior difference between Simple and Atomic sites when the login flow takes users from `/log-in` to `/home` from Playwright's perspective.

Simple: dashboard is loaded and the `networkidle` event is fired about ~25s later.
Atomic: dashboard is loaded and the `networkidle` event is fired about ~3s later.

It is possible to solve the flakey `SidebarComponent._click` action by setting the `waitForLoadState('networkidle')` but this will result in every SidebarComponent interaction on Simple site to take an additional ~25s, which is an unacceptable delay.

#### Testing instructions

TeamCity
- ensure that sidebar interaction in tests (eg. SEO Preview) are not failing due to flakiness in clicking. To verify, view any video recordings that are in the `artifacts` tab.
- no failures should be occurring on Atomic sidebar interaction.

Related to #

### CODE REVIEW

File: packages/calypso-e2e/src/lib/components/sidebar-component.ts [hunk 1]
```diff
@@ -144,6 +144,8 @@ export class SidebarComponent extends BaseContainer {
 			[ elementHandle ]
 		);
 
+		await elementHandle.waitForElementState( 'stable' );
```
Comment (worldomonation) [inline packages/calypso-e2e/src/lib/components/sidebar-component.ts]: To be frank, I suspect this part isn't necessary since the scroll action != animation and [according to the docs](https://playwright.dev/docs/actionability#stable) the `stable` state fires when an element `...maintained the same bounding box for at least two consecutive animation frames.`

Comment (bsessions85) [reply packages/calypso-e2e/src/lib/components/sidebar-component.ts]: 🤔  Do we still want to add it if it could be doing nothing? I'll let you make that decision

**Review by bsessions85 — APPROVED** [review]
Looks fine to me. It might be good to decide if the element state piece is necessary before merging.

File: packages/calypso-e2e/src/lib/components/sidebar-component.ts (hunk 1 above)
Comment (worldomonation) [reply packages/calypso-e2e/src/lib/components/sidebar-component.ts]: I needed to verify if this was necessary, which I will do before merging this PR. Plan is to set up another branch, one without this change and make it run tests several times. I suspect it isn't necessary, but I've been wrong on these `waitForElementState` before.
