### PR TITLE
Goals first: Reset onboard store when entering the flow

### LINKED ISSUE #97887: Bug: Trying to create two sites in sequence in the new onboarding flow doesn't work
### Quick summary

Bug report: pdtkmj-3es-p2#comment-6077

### Steps to reproduce

Follow this video: 

https://github.com/user-attachments/assets/f0363164-17a9-4999-b6a2-b96a7d0d7d50

### What you expected to happen

When registering the second site, it should clear the previous domain selection so it will create a new domain instead of reusing the domain of the previous site.

### What actually happened

Since the domain from the recent created site was at the domain selection list, it tried to use the same domain for the new site and failed

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by zaguiini**
Closes https://github.com/Automattic/wp-calypso/issues/97887.

## Proposed Changes

Title. We're keeping the domain selection information as it is in case the user wants to create a new site with their previously selected domain (that they haven't bought.)

## Why are these changes being made?

Because right now it's impossible to create two sites through `/setup/onboarding`.

## Testing Instructions

Enter `/setup/onboarding` and create a site. Enter the flow again and create a second site. You should end up with two sites.

On `trunk`, the user is getting redirected to `/sites` after trying to create the second site.

Also, go through the flow with a paid domain and leave the cart while keeping the domain there. Enter `/setup/onboarding` and verify that the paid domain is preselected.

### CODE REVIEW

File: client/landing/stepper/declarative-flow/onboarding.ts [hunk 1]
```diff
@@ -344,6 +346,18 @@ const onboarding: Flow = {
...
 	},
+	useSideEffect( currentStepSlug ) {
+		const dispatch = useDispatch();
+		const [ , , clearAllStepPersistedState ] = useStepPersistedState( 'onboarding' );
+
+		useEffect( () => {
+			if ( ! currentStepSlug ) {
+				resetOnboardStore();
+				dispatch( setSelectedSiteId( null ) );
+				clearAllStepPersistedState();
```
Comment (vykes-mac) [inline client/landing/stepper/declarative-flow/onboarding.ts]: The onboarding store is already being reset in the `site-setup-flow` [here](https://github.com/Automattic/wp-calypso/blob/6b6d701f8101637b9a5e10f5c3238ae62acff380/client/landing/stepper/declarative-flow/site-setup-flow.ts#L250). I wonder if it make sense to also call the `clearAllStepPersistedState` there so everything is cleaned up after the flow ends

**Review by paulopmt1 — APPROVED** [review]
Work as intended. Shared a full review here: p1736002952764819/1735915114.483079-slack-C04H4NY6STW

My main concern as a follow-up is to ensure the `.wordpress.com` domain suggestion always shows up as the first time we go through the flow.

Thanks for working on it @zaguiini and @candy02058912 !

**Review by p-jackson — APPROVED** [review]
After testing and talking in p1736137453158579/1735915114.483079-slack-C04H4NY6STW I think it's ok to move the reseting of the onboarding state to the front of the flow.

File: packages/onboarding/src/hooks/use-persisted-state.ts [hunk 2]
```diff
@@ -23,6 +23,20 @@ function getPersistedState( key: string, storage: Storage, TTL: number ) {
 	}
 }
 
+/**
+ * Clears all persisted state created by useStepPersistedState
+ * @param storage The storage to clear (defaults to localStorage)
+ */
+function clearStepPersistedState( storage: Storage = localStorage ): void {
```
Comment (p-jackson) [inline packages/onboarding/src/hooks/use-persisted-state.ts]: The API would feel a lot cleaner to me if this function was just exported directly. It doesn't depend on any React state, so it doesn't feel like it needs to be returned by a hook.

The fact that the only time it's actually used, the first two things returned from the hook aren't used, it kinda shows how it doesn't need to be colocated with the `useStepPersistedState` hook for it to be useful.

File: client/landing/stepper/declarative-flow/onboarding.ts (hunk 1 above)
Comment (p-jackson) [reply client/landing/stepper/declarative-flow/onboarding.ts]: I think it's ok to move the logic for clearing the state to the front of the flow. But I guess that means we should have a follow up task that removes the `resetOnboardStore` call from the `site-setup` flow.

File: packages/onboarding/src/hooks/use-persisted-state.ts [hunk 3]
```diff
@@ -23,6 +23,20 @@ function getPersistedState( key: string, storage: Storage, TTL: number ) {
...
+	const keys = Object.keys( storage );
+	const persistedKeys = keys.filter( ( key ) => key.startsWith( `${ VERSION }-${ KEY }` ) );
```
Comment (p-jackson) [inline packages/onboarding/src/hooks/use-persisted-state.ts]: If we we're feeling real fancy we could maybe remove all keys prefixed by `${VERSION}-${KEY}-${flow}`? Restarting a flow should only reset the data for that flow maybe?

File: client/landing/stepper/declarative-flow/onboarding.ts (hunk 1 above)
Comment (p-jackson) [reply client/landing/stepper/declarative-flow/onboarding.ts]: I got a WIP https://github.com/Automattic/wp-calypso/pull/97972

File: packages/onboarding/src/hooks/use-persisted-state.ts (hunk 2 above)
Comment (candy02058912) [reply packages/onboarding/src/hooks/use-persisted-state.ts]: I thought about this while working with https://github.com/Automattic/wp-calypso/pull/97920 and agree that this doesn't need to live inside the `useStepPersistedState` hook.

I really like how the two functions are now in the same file, close together.

Another reason is that if it's inside the hook, we’d run the rest of the hook’s code unnecessarily even when all we need is `clearStepPersistedState`.

So +1 for exporting this function directly in this file ❤️

**Review by candy02058912 — APPROVED** [review]
> Also, go through the flow with a paid domain and leave the cart while keeping the domain there. Enter /setup/onboarding and verify that the paid domain is preselected.

Domain is preseleted.
But the price isn't 0 with the "Free for the first year with annual paid plans." description. Also, the price doesn't match the regular price.

https://github.com/user-attachments/assets/8e29afaf-1dee-453b-9529-460dfabbb957

Don't think that's a blocker for merging this PR as the amount in the checkout cart is still correct. (Free domain with an annual plan selected)

File: client/landing/stepper/declarative-flow/internals/steps-repository/unified-domains/use-is-managed-site-flow.ts [hunk 4]
```diff
@@ -9,23 +9,23 @@ import {
...
+export const useIsManagedSiteFlowProps = ( flow: string ) => {
 	const postSignUpSiteSlugParam = getSignupCompleteSlug();
 	const postSignUpSiteIdParam = getSignupCompleteSiteID();
 
 	const selectedSite = useSite( postSignUpSiteSlugParam || postSignUpSiteIdParam );
 
 	useEffect( () => {
 		const signupDestinationCookieExists = retrieveSignupDestination();
-		const isReEnteringFlow = getSignupCompleteFlowName() === 'onboarding';
+		const isReEnteringFlow = getSignupCompleteFlowName() === flow;
```
Comment (zaguiini) [inline client/landing/stepper/declarative-flow/internals/steps-repository/unified-domains/use-is-managed-site-flow.ts]: Is this something we should keep? I wonder what the consequences are. This statement is like that everywhere except here. cc @p-jackson @alshakero

**Comment by autumnfjeld** [comment]
For reference, team testing discussed here: p1736205027317489/1736196927.663189-slack-C085HCWCEDN

File: client/landing/stepper/declarative-flow/internals/steps-repository/unified-domains/use-is-managed-site-flow.ts (hunk 4 above)
Comment (p-jackson) [reply client/landing/stepper/declarative-flow/internals/steps-repository/unified-domains/use-is-managed-site-flow.ts]: I'm going to keep it because I don't know enough about this to know whether it's safe to delete

Comment (autumnfjeld) [reply client/landing/stepper/declarative-flow/internals/steps-repository/unified-domains/use-is-managed-site-flow.ts]: @p-jackson  @lsl  User "Kosta" four months ago hard coded `onboarding` in this line.  I'm assuming Luis is wanting  to make sure changing it to dynamically get the flow value is a wise idea.  That's what I called out here p1736209066024739/1736196927.663189-slack-C085HCWCEDN

Comment (autumnfjeld) [reply client/landing/stepper/declarative-flow/internals/steps-repository/unified-domains/use-is-managed-site-flow.ts]: > I'm going to keep it because I don't know enough about this to know whether it's safe to delete

To be clear, you'll keep the hard coded `onboarding` value?  
Agreed.

Comment (p-jackson) [reply client/landing/stepper/declarative-flow/internals/steps-repository/unified-domains/use-is-managed-site-flow.ts:20]: Yeah, keep it the way Luis did it :)

Comment (p-jackson) [reply client/landing/stepper/declarative-flow/internals/steps-repository/unified-domains/use-is-managed-site-flow.ts]: I actually meant keeping things the way Luis did them. Cause I'd assumed that it was all necessary to get the fix working. But if it's not then I would keep it hard coded. Since I really don't know enough about what a "managed site flow" is to know how to make the call.

Comment (autumnfjeld) [reply client/landing/stepper/declarative-flow/internals/steps-repository/unified-domains/use-is-managed-site-flow.ts]: I see that @arthur791004 has worked in [`unified-domains`](https://github.com/Automattic/wp-calypso/blob/b705d829c188808ee0259ae6c41a660598e954e4/client/landing/stepper/declarative-flow/internals/steps-repository/unified-domains/index.tsx) , maybe you have some knowledge to share here @arthur791004?

File: client/landing/stepper/declarative-flow/internals/steps-repository/create-site/index.tsx [hunk 5]
```diff
@@ -183,7 +183,10 @@ const CreateSite: Step = function CreateSite( { navigation, flow, data } ) {
 	//User has already reached checkout and then hit the browser back button.
 	//In this case, site has already been created, and plan added to cart. We need to avoid to create another site.
 	const isManageSiteFlow = Boolean(
-		wasSignupCheckoutPageUnloaded() && signupDestinationCookieExists && isReEnteringFlow
+		wasSignupCheckoutPageUnloaded() &&
+			signupDestinationCookieExists &&
+			isReEnteringFlow &&
+			getSignupCompleteSlug()
```
Comment (p-jackson) [inline client/landing/stepper/declarative-flow/internals/steps-repository/create-site/index.tsx:189]: I've added this check because further on (in the `createSite` function), if `isManageSiteFlow` is `true` then we go ahead an use the signup complete slug, just assuming that it will be valid. So we shouldn't really go into that branch unless we also know the signup complete slug is valid.

This was causing an issue where if the user went back and made another site using the onboarding flow a 2nd time, `isReEnteringFlow` so it didn't think it had to create a site. But we don't have a site slug, we really do need to create a site.

File: client/landing/stepper/declarative-flow/internals/steps-repository/unified-domains/use-is-managed-site-flow.ts (hunk 4 above)
Comment (autumnfjeld) [reply client/landing/stepper/declarative-flow/internals/steps-repository/unified-domains/use-is-managed-site-flow.ts]: Decision: reverted in [Revert the change which made useIsManagedSiteFlowProps accept a flow name](https://github.com/Automattic/wp-calypso/pull/97936/commits/cdf5f6cb83c1a06bd955be61f29d475714be5033)

**Comment by candy02058912** [comment]
Shared testing creating two sites here: p1736224151854289/1736196927.663189-slack-C085HCWCEDN
There's also more discussions regarding this PR in that thread, so linking it here for context in the future.
