### PR TITLE
Fix jetpack site disconnect

### LINKED ISSUE #22794: Jetpack: Disconnecting sites doesn't work
#### Steps to reproduce
1. Starting at URL: https://wordpress.com with a Jetpack site that no longer exists
2. Click "My Sites" and use the red icon and click "Remove Site"
3. Complete the survey
4. Click "Disconnect"

#### What I expected

Until recently, a confirmation dialog success message was shown saying site was disconnected

#### What happened instead

Nothing, site **isn't** disconnected

#### Browser / OS version

Chrome on macOS

#### Screenshot / Video

disconnect site

#### Context / Source
 #automated-testing

### PR DESCRIPTION
**Pull request by seear**
Fixes #22794

Fixes problems that were introduced by PRs #22362 and #22724. The `mapDispatchToProps` arg of `connect()` can only contain action creators, not local methods as was happening here.

@eliorivero can you check that the changes intended by the above PRs are still working ok, in particular the rewind redirect and tracks events?

## Testing
* test as-per #22794

### CODE REVIEW

File: client/blocks/disconnect-jetpack/index.jsx [hunk 1]
```diff
@@ -203,7 +203,15 @@ class DisconnectJetpack extends PureComponent {
 		);
 	};
 
-	handleTryRewind = () => this.props.trackTryRewind( this.props.siteSlug );
+	handleTryRewind = () => {
+		const { siteSlug } = this.props;
```
Comment (ockham) [inline client/blocks/disconnect-jetpack/index.jsx]: You could also destructure `recordTracksEvent` if you want. Or inline `this.props.siteSlug`on L209 since it's only used once.

File: client/my-sites/site-indicator/site-indicator.jsx [hunk 2]
```diff
@@ -417,9 +424,7 @@ export default connect(
 	},
 	{
 		updateWordPress,
-		trackSiteDisconnect: siteId => {
-			recordGoogleEvent( 'Jetpack', 'Clicked in site indicator to start Jetpack Disconnect flow' );
-			recordTracksEvent( 'calypso_jetpack_site_indicator_disconnect_start', { siteId } );
-		},
```
Comment (ockham) [inline client/my-sites/site-indicator/site-indicator.jsx]: I think you could use `composeAnalytics` here, see https://github.com/Automattic/wp-calypso/blob/master/client/state/analytics/README.md#api.

File: client/blocks/disconnect-jetpack/index.jsx [hunk 3]
```diff
@@ -203,7 +203,14 @@ class DisconnectJetpack extends PureComponent {
 		);
 	};
 
-	handleTryRewind = () => this.props.trackTryRewind( this.props.siteSlug );
+	handleTryRewind = () => {
+		this.props.recordTracksEvent( 'calypso_disconnect_jetpack_try_rewind' );
```
Comment (ockham) [inline client/blocks/disconnect-jetpack/index.jsx]: I think this needs to be `recordTracksEventAction` (either that, or L212 is incorrect 😅).

**Comment by ockham** [comment]
> @eliorivero can you check that the changes intended by the above PRs are still working ok, in particular the rewind redirect and tracks events?

I also tried to test to ensure the 'Rewind' option as described in #22724 could be triggered, but I couldn't actually manage to. FWIW, I bought a Professional plan and went through initial AL setup, but still didn't get the option during disconnect flow. Not sure what I'm missing.

File: client/my-sites/site-indicator/site-indicator.jsx (hunk 2 above)
Comment (seear) [reply client/my-sites/site-indicator/site-indicator.jsx]: Nice! Done. Noting that we don't need the `siteId` tracks prop—we get it as `blog_id` for free.

File: client/blocks/disconnect-jetpack/index.jsx [hunk 4]
```diff
@@ -305,20 +312,14 @@ export default connect(
...
+	{
+		setAllSitesSelected,
+		recordGoogleEvent: recordGoogleEventAction,
+		recordTracksEvent: recordTracksEventAction,
+		disconnect,
+		successNotice,
+		errorNotice,
+		infoNotice,
+		removeNotice,
+	}
```
Comment (eliorivero) [inline client/blocks/disconnect-jetpack/index.jsx]: I don't think it's necessary to roll all this back. It should be enough just passing the missing arguments, like modifying
```
disconnect: () => dispatch( disconnect ),
```
to
```
disconnect: ( siteId ) => dispatch( disconnect( siteId ) ),
```
I would actually prefer if these weren't modified so we don't have to put more complex functions like `handleTryRewind` and `trackTryRewindHelp` in the component implementation and we could leave them in the connect area.

Comment (seear) [reply client/blocks/disconnect-jetpack/index.jsx]: Sure, feel free to tweak this.

Comment (ockham) [reply client/blocks/disconnect-jetpack/index.jsx]: > I don't think it's necessary to roll all this back. It should be enough just passing the missing arguments, like modifying
> ```
> disconnect: () => dispatch( disconnect ),
> ```
> to
> ```
> disconnect: ( siteId ) => dispatch( disconnect( siteId ) ),
> ```

This doesn't really make any difference, and it's equivalent to

```
disconnect
```

which is more elegant, and the kind of notation we try to use throughout Calypso.

> I would actually prefer if these weren't modified so we don't have to put more complex functions like `handleTryRewind` and `trackTryRewindHelp` in the component implementation and we could leave them in the connect area.

That's a fair point. I'll point out that prior to #22724, the component was using class methods to trigger tracks events -- arguably, #22724 made it somewhat inconsistent in that regard.

If you'd like to keep those functions in `connect`, it's still possible to do so without invoking `dispatch`, e.g.

```
{
/*...*/
trackTryRewindHelp: () => recordTracksEventAction( 'calypso_disconnect_jetpack_try_rewind_help' )
}
```

The 0-ary function on the right-hand side will then be auto-bound (wrapped) with `dispatch` by `connect`.

It's a little trickier but still possible for `trackTryRewind`, I'll follow up on that.

Comment (ockham) [reply client/blocks/disconnect-jetpack/index.jsx]: > It's a little trickier but still possible for `trackTryRewind`, I'll follow up on that.

As discussed via DM, it should be possible using [`withAnalytics`](https://github.com/Automattic/wp-calypso/tree/master/client/state/analytics#usage) and  [`navigate` ](https://github.com/Automattic/wp-calypso/tree/master/client/state/navigation) 🙂

**Comment by ockham** [comment]
> The events are not tracked anymore after the refactor. I think, and already pointed in a comment, that the `dispatch`es should be kept, fixing them passing the proper arguments.

Could you post testing instructions here? Much harder to test these changes without really knowing what's required to do so (also see https://github.com/Automattic/wp-calypso/pull/22806#issuecomment-368546224).

**Comment by ockham** [comment]
For reference, Elio's follow-up PR: #22819 😄
