### PR TITLE
FSE: Improve/fse eligibility active check v2

### LINKED ISSUE #35950: Full Site Editing: Infinite Loaders on Header and Footer
Currently in prod we're seeing infinite headers/footers loading for eligible sites, on non-supported themes. Let's see what fix caused the regression.

Screen Shot 2019-09-03 at 6 36 48 PM

There may be another minor case where we currently depend on the `after_switch_theme` action to populate default data. https://github.com/Automattic/wp-calypso/blob/6c41229ff6a4953ab82441e995a3bfecc4e663c7/apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php#L64

Please investigate if it's possible to get infinite Header/Footer loaders on FSE flows with the following steps:

- With an FSE enabled site, activate Maywood
- Then apply a code patch that whitelists support for Maywood

Or alternatively:
- With an non-fse eligible site, active a supported FSE theme
- Mark the site as FSE eligible

### PR DESCRIPTION
**Pull request by glendaviesnz**
#### Changes proposed in this Pull Request

* Add a filter for grabbing the theme. We need this to override the api theme in the API context
* Bail on merging templates if header and footer templates empty

#### Testing instructions

* Apply D32454-code to your sandbox
* Checkout this patch, build FSE plugin and sync with your sandbox
* Sandbox API
* Make sure FSE templates display on supported theme on WP.com and not on unsupported theme
* Check same thing on local install

Fixes #35950

### CODE REVIEW

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php [hunk 1]
```diff
@@ -52,6 +52,75 @@ function load_full_site_editing() {
...
+/**
+ * Returns normalized theme slug for the current theme.
+ *
+ * Normalize WP.com theme slugs that differ from those that we'll get on self hosted sites.
+ * For example, we will get 'modern-business-wpcom' when retrieving theme slug on self hosted sites,
+ * but due to WP.com setup, on Simple sites we'll get 'pub/modern-business' for the theme.
+ *
+ * @return string Normalized theme slug.
+ */
+function get_theme_slug() {
```
Comment (glendaviesnz) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php]: This can probably go as this can be handled by a filter in the given context with this approach

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php [hunk 2]
```diff
@@ -52,6 +52,75 @@ function load_full_site_editing() {
...
+ */
+function is_theme_supported() {
+	/**
+	 * Can be used to enable Full Site Editing theme support in certian contexts.
+	 *
+	 * @since 0.7
+	 *
+	 * @param bool true if Full Site Editing is available for current theme, false otherwise.
+	 */
+	return apply_filters( 'a8c_fse_enable_theme_support', false );
```
Comment (gwwar) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php]: Can we fallback to a default function for Jetpack sites, maybe with a high loading number?

**Comment by gwwar** [comment]
Awesome I think this is working well on Simple Sites, and should let us support other site types.

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php (hunk 2 above)
Comment (noahtallen) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php]: i think it would be nice to handle the support check here, but get the theme name from the filter instead (that way we don't duplicate the array everywhere)

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php [hunk 3]
```diff
@@ -52,6 +52,75 @@ function load_full_site_editing() {
...
 
+/**
+ * Whether or not FSE is active.
+ * If false, FSE functionality can be disabled.
+ *
+ * @returns bool True if FSE is active, false otherwise.
+ */
+function is_full_site_editing_active() {
+	return is_site_eligible_for_full_site_editing() &&
+			( is_theme_supported() || in_array( get_theme_slug(), SUPPORTED_THEMES, true ) );
```
Comment (noahtallen) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php]: what if we put the default `in_array` bit into the is_theme_supported function?

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php (hunk 2 above)
Comment (gwwar) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php]: ah that'd make sense too

**Comment by noahtallen** [comment]
Tested working on these sites:
- Simple site with supported theme
- Simple site with unsupported theme
- Simulated Atomic site (wpcomsh, Jetpack, this branch of FSE, and eligibility option on jurassic ninja) with supported theme
- Simulated Atomic site with unsupported theme

Only thing I haven't tested is creating a new site. I could see a possible issue with that since we changed how the filter works which the site creation step relies on

**Comment by gwwar** [comment]
Testing with a fresh user/site creation:

Correctly shows FSE with Maywood:
Screen Shot 2019-09-05 at 11 49 59 AM

And a normal block-editor with an unsupported theme:
Screen Shot 2019-09-05 at 11 51 55 AM

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php [hunk 4]
```diff
@@ -52,6 +50,77 @@ function load_full_site_editing() {
...
+/**
+ * Returns normalized theme slug for the current theme.
+ *
+ * Normalize WP.com theme slugs that differ from those that we'll get on self hosted sites.
+ * For example, we will get 'modern-business-wpcom' when retrieving theme slug on self hosted sites,
+ * but due to WP.com setup, on Simple sites we'll get 'pub/modern-business' for the theme.
+ *
+ * @return string Normalized theme slug.
+ */
+function get_theme_slug() {
```
Comment (vindl) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php]: Just a note that we already have similar method declared in https://github.com/Automattic/wp-calypso/blame/17e28769440e74dcdcb3fea9d3be6e6e6d2ea509/apps/full-site-editing/full-site-editing-plugin/full-site-editing/templates/class-wp-template.php#L60 and https://github.com/Automattic/wp-calypso/blame/58f4fdf7deb635453b18f0796cd463fed54e6ecf/apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php#L129.

Might be good to circle back and refactor this to avoid duplication.

Comment (noahtallen) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php]: 💯for sure! I originally copied it here so that we didn't have to create a class instance to access it :D
