### PR TITLE
Gutenberg iframe: show post type trash when moving a post to the trash.

### LINKED ISSUE #30655: Gutenberg iframe: override Move to Trash on the Document sidebar
Part of #30551

#### Steps to reproduce

With the `calypsoify/iframe` feature flag enabled, open a page or post for edit. On the Document sidebar module, click _Move to trash_.

!()[https://user-images.githubusercontent.com/1270189/52146166-d3bd1b80-2617-11e9-9770-a6adfb4dc322.png]

The section will not load since X-Frame-Options are by default set to sameorigin.

### PR DESCRIPTION
**Pull request by rodrigoi**
Fixes #30655.

#### Changes proposed in this Pull Request

Adds a handled when the `postTrashed` action is sent over by the Gutenberg iframe. When the action is received, it navigates away to the post type trash page.
All the heavy lifting is done on D24207-code.

#### Testing instructions

* sandbox a WordPress.com site and apply D24207-code.
* edit a post on the sandboxed site.
* on the _Document_ settings, look for _Status and Visibility_ and click _Move to Trash_

The post should be trashed correctly and the iframe should close and be redirected to the trashed post page. This should work with all post types.

### CODE REVIEW

**Comment by kwight** [comment]
Lovely! I don't get sent to the Trash view though, I'll be shown whichever view was last active in the list (seems to be the case for all post types).

**Comment by mmtr** [comment]
I can reproduce behavior described by @kwight.

File: client/gutenberg/editor/calypsoify-iframe.jsx [hunk 1]
```diff
@@ -102,6 +104,10 @@ class CalypsoifyIframe extends Component {
 				this.props.setRoute( `${ currentRoute }/${ postId }` );
 			}
 		}
+
+		if ( 'postTrashed' === action ) {
+			page.back( this.props.postTypeTrashUrl );
```
Comment (gwwar) [inline client/gutenberg/editor/calypsoify-iframe.jsx]: Instead of back, we probably should navigate to the post, page or CPT list, so dispatching a redux `NAVIGATE` event would make sense here.

**Comment by gwwar** [comment]
Pretty close @rodrigoi ! Are we planning to add a success message in the post list here too or in a follow up PR?

File: client/gutenberg/editor/calypsoify-iframe.jsx (hunk 1 above)
Comment (rodrigoi) [reply client/gutenberg/editor/calypsoify-iframe.jsx]: fixed on 6c988b01854ed51e141ee42ff8e4675a701d991f 😉

**Comment by rodrigoi** [comment]
@kwight @mmtr thanks for the review. I've updated the code to use the navigation middleware, which I think fixed the problem you were having. So, this is ready for another review.

@gwwar I was planning on keeping this PR just about the action, so I'd rather have a new PR for all the success since it will require changes on the posts list components.
