### PR TITLE
 Stats: Include URL in CSV Export Data

### LINKED ISSUE #39912: Stats: Include (correct) URLs in CSV export
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/
2. Click Switch Site & choose a site that would have recent data
3. Scroll to Posts & Pages, click that header
4. Select a viewing period
5. Scroll down and choose to export CSV

#### What I expected
I was hoping the CSV would include the title, URL, and number of visits for that period

#### What happened instead
I got the title and visits, but no URL. If I'm working on a report to compare stats for a list of posts from one period to the next, this means I have to go grab each URL manually. Not ideal.

#### Browser / OS version
Doesn't matter

#### Screenshot / Video
Here's what I get:
what I get

Here's what I want. Note I added the title and column headers manually. If you think those would be a good idea and wouldn't jack up anyone's processes, OK, but I'm also fine with just the data. Also note, the URL that shows on the stats page for individual threads is actually wrong, but I'll file another issue about that.
ideal csv

#### Context / Source
#dogfooding trying to get some data from our forums :)

#### Side Note
 I thought for now I could simply copy and paste into a sheet and let Google Sheets figure out how to split it. Not so much. Selecting was hard (basically I had to select the title above, then hold down shift while selecting the CSV option below. That did copy data, but formatting it in a spreadsheet will be a bit of a pain. This is what I got on paste, and even on asking Sheets to split data for me:
what happens when I just paste

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

* Adds the URL of the content to CSV exports in Stats

#### Testing instructions

Visit `/stats/day/posts/SITEURL` and click the " Download data as CSV" button at the bottom of the table. You may need to upload the file to something like Google Sheets in order to analyse it, but it should now include the content's URL.

| Before                                                                                                                                                                | After                                                                                                                                                                 |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Screenshot 2021-05-30 at 11 19 20 | <Screenshot 2021-05-30 at 11 19 12 |

cc @sixhours 

Fixes #39912

### CODE REVIEW

File: client/state/stats/lists/test/utils.js [hunk 1]
```diff
@@ -218,10 +254,10 @@ describe( 'utils', () => {
...
 				} )
 			).toEqual( [
-				[ '"BBQ"', 10 ],
-				[ '"BBQ > Chicken"', 5 ],
-				[ '"BBQ > Ribs"', 2 ],
-				[ '"BBQ > Ribs > Babyback"', 1 ],
+				[ '"BBQ"', 10, 'https://example.com/bbq' ],
+				[ '"BBQ > Chicken"', 5, 'https://example.com/bbq/chicken' ],
+				[ '"BBQ > Ribs"', 2, 'https://example.com/bbq/ribs' ],
+				[ '"BBQ > Ribs > Babyback"', 1, 'https://example.com/bbq/ribs/babyback' ],
```
Comment (sarayourfriend) [inline client/state/stats/lists/test/utils.js:260]: These examples... 🤤

File: client/state/stats/lists/utils.js [hunk 2]
```diff
@@ -101,12 +101,12 @@ function parseAvatar( avatarUrl ) {
  * @returns {Array}         CSV Row
  */
 export function buildExportArray( data, parent = null ) {
-	if ( ! data || ! data.label || ! data.value ) {
+	if ( ! data || ! data.label || ! data.value || ! data.actions ) {
```
Comment (sarayourfriend) [inline client/state/stats/lists/utils.js]: Should we check `data.actions.length` as well, or is it safe to assume that if it exists it will always include at least one element?

**Review by sarayourfriend — COMMENTED** [review]
Code LGTM so far! Just one question 🎉

File: client/state/stats/lists/utils.js (hunk 2 above)
Comment (Aurorum) [reply client/state/stats/lists/utils.js]: I believe that there'll always be one element, but I added a commit with that check just in case! :)

File: client/state/stats/lists/test/utils.js (hunk 1 above)
Comment (Aurorum) [reply client/state/stats/lists/test/utils.js:260]: spirited-away-no-face-gif-14

**Comment by sixhours** [comment]
This is working for me! @sarayourfriend did you have additional feedback or is this good to deploy?

**Comment by sixhours** [comment]
Screen Shot 2021-06-25 at 1 18 22 PM

Looks like a test may still need updating for this to pass.

**Comment by Aurorum** [comment]
Thanks @sixhours! I don't think the test in itself is broken; it's conveying a genuine bug which I missed where this would break the ability to download Countries data in `/stats/day/countryviews/site.com`. I've fixed that bug now!

**Comment by sarayourfriend** [comment]
No additional feedback from me!
