### PR TITLE
Checkout: fix chargeback-only display issues

### LINKED ISSUE #64203: [Bug]: "Included with your purchase" section in checkout is empty for certain products
### Quick summary

@claudiucelfilip noticed this bug for the upcoming No Ads product, but it occurs for some existing products too:  The "Included with your purchase" section in checkout is completely empty.

### Steps to reproduce

Easiest to reproduce with Search since it's already for sale:

1. Go to https://cloud.jetpack.com/pricing
2. Choose the Site Search product
3. Select an existing site (can be a WordPress.com site or a Jetpack site)
4. Look for the empty section in checkout

### What you expected to happen

Either the section to not appear at all (if there's nothing in it), or otherwise some basic text to be displayed.

Perhaps for many products, we can add similar text to what we do for domains (basically, one bullet point about the product, and one about the refund window), but then also make it disappear automatically for any products where we didn't do that.

Domains:

domains

### What actually happened

The section is empty:

Screenshot from 2022-05-31 12-57-27

### Context

_No response_

### Browser

_No response_

### Simple/Atomic

_No response_

### Other notes

_No response_

### Reproducibility

Consistent

### Severity

_No response_

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by michaeldcain**
This makes a few small updates to the way Checkout handles a cart that's only Chargeback fees.

Fixes: https://github.com/Automattic/wp-calypso/issues/64203

| Before      | After |
| ----------- | ----------- |
|   wordpress com_checkout_cainsnuxtest2401135335 wordpress com   |    calypso localhost_3000_checkout_cainsnuxtest2401135335 wordpress com    |

**To test:**
- Testing a chargeback is difficult - I'll create a guide. The easiest way to test this is probably to SU `cainstesting` and then visit https://wordpress.com/checkout/cainsnuxtest2401135335.wordpress.com
- Verify that the changes look correct
- Visit Checkout for any other site/product combination
- Verify that there haven't been visual regressions

### CODE REVIEW

File: client/my-sites/checkout/src/components/CheckoutMoneyBackGuarantee.jsx [hunk 1]
```diff
@@ -33,6 +34,11 @@ const StyledIcon = styled( Icon )`
 `;
 
 export function CheckoutMoneyBackGuarantee( { cart } ) {
+	// Return early if the cart is only Chargebacks fees
+	if ( cart.products.every( isChargeback ) ) {
```
Comment (sirbrillig) [inline client/my-sites/checkout/src/components/CheckoutMoneyBackGuarantee.jsx]: What if your cart contains credits also? (Ugh it'd be nice to not have to handle this case some day.)

**Review by sirbrillig — APPROVED** [review]
Marking approved although you might want to test it with credits in the cart too, since those are technically line items 😒

File: client/my-sites/checkout/src/components/CheckoutMoneyBackGuarantee.jsx (hunk 1 above)
Comment (michaeldcain) [reply client/my-sites/checkout/src/components/CheckoutMoneyBackGuarantee.jsx]: Thanks - added a check for credits:

Screenshot 2024-02-06 at 2 54 59 PM
