### PR TITLE
Google My Business: Update Strings to Google Business Profile

### LINKED ISSUE #84970: Google My Business is now called Google Business Profile
### Quick summary

We have a Google My Business integration, but Google has changed the name to Google Business Profile.

### Steps to reproduce

On a Business or Commerce plan site:

1. Navigate to Tools → Marketing
2. Click the Connections tab
3. Scroll down to the Google My Business section

### What you expected to happen

I expected our feature to reflect the current name: Google Business Profile

### What actually happened

It says "Google My Business"

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by Aurorum**
Fixes #84970

## Proposed Changes

* Replaces "Google My Business" with "Google Business Profile" for users following Google's rebranding of the service 

I've only touched translatable strings because I don't want to mess up any actual code, and I don't want to mess up any analytics either. But also, it seems that's what happens in Calypso when other services are renamed (eg. Twitter) so I don't think that's a problem - let me know if it should be changed though!  

Only other thing that needs updating is the endpoints `/connections` and `/external-services`, which I don't think I can do. 

## Testing Instructions

Should be a case of making sure the code looks sane since it's only strings, and confirming that the strings are updated on Calypso. 

Screenshot 2024-01-11 at 14 23 00

cc @stephanethomas @creativecoder

### CODE REVIEW

**Review by creativecoder — APPROVED** [review]
Thanks @Aurorum for the update!

I found a couple additional strings that seemed good to change, and added them in https://github.com/Automattic/wp-calypso/pull/86301/commits/6e14ebb11a1628efbbcad3e51990686b322c27dc

I personally haven't touched this feature in a long time, but these changes look good to me.

File: client/my-sites/google-my-business/new-account/index.js [hunk 1]
```diff
@@ -64,10 +64,10 @@ class GoogleMyBusinessNewAccount extends Component {
 			<Main className="gmb-new-account" wideLayout>
 				<PageViewTracker path="/google-my-business/new/:site" title="Google My Business > New" />
```
Comment (olaseni) [inline client/my-sites/google-my-business/new-account/index.js]:
```suggestion
				<PageViewTracker path="/google-my-business/new/:site" title="Google Business Profile > New" />
```

I think we are fine to refactor the `PageViewTracker` title. The last I checked those paths are rarely viewed anyway.

**Review by olaseni — CHANGES_REQUESTED** [review]
As mentioned in a comment, let's make changes to the title properties where analytics is concerned. The path property is still retained, so analytics is only partially impacted. Those pages don't receive a lot of views anyway.

We should also be good to make changes in comments, like in this [utils.js.](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/google-my-business/utils.js#L7), or in this [test unit file](https://github.com/Automattic/wp-calypso/blob/trunk/client/state/data-layer/wpcom/sites/stats/google-my-business/test/index.js)

File: client/my-sites/google-my-business/new-account/index.js (hunk 1 above)
Comment (Aurorum) [reply client/my-sites/google-my-business/new-account/index.js]: All done - thanks for taking a look! :)

**Review by olaseni — APPROVED** [review]
Thanks @Aurorum. The changes look good!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/11481870

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @Aurorum for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/11481870).
