### PR TITLE
Checkout: Don't use localStorage to save product data for the thank you page

### LINKED ISSUE #2235: Checkout: thank you page does not work with Safari's private browsing
Raised by @rads 

The Checkout Thank You page currently relies on `localStorage` which is not supported in Safari's Private Browsing mode. @scruffian has already created a PR (3128-gh-calypso-pre-oss) to get the discussion going on how to solve this issue.

Comments from @rachelmcr 

> I tested and confirmed that this is still an issue in Safari's Private Browsing mode. After checkout I landed on https://wordpress.com/plans/undefined with this console error:
> 
> `TypeError: null is not an object (evaluating 'lastTransaction.selectedSite')`
> 
> screen shot 2015-08-27 at 5 20 10 pm
> 
> Do we know how often users make purchases in private browsing mode? I agree with the low priority label on this bug, since the only issue is with the thank you page (the purchase goes through).

Comment from @mattm 

> I want to add that when we do figure out how to customize the Thank You page for users who purchase via PayPal Express, we also need to add a `calypso_checkout_payment_success` event because currently one is not triggered for PayPal Express payments, but it's important for analytics purposes that we track it.

### PR DESCRIPTION
**Pull request by drewblaisdell**
Fixes #2235.

This PR updates the checkout process, and:
- Changes the route for the checkout thank you page from `/checkout/thank-you` to `/checkout/:site_slug/:receipt_id/thank-you`.
- Adds actions/a reducer/selector to fetch a receipt from the server and store it in the global state tree.
- Dispatches an action to store a receipt when a transaction is completed successfully.
- Fetches a receipt on the thank you page.
- Updates the thank you page to render using purchases from the receipt, instead of items from the last cart.
- Removes `lastTransaction` from local storage, and any logic that used to use that property.

#### Testing instructions - Credit card

1. Run `git checkout fix/thank-you-page` and start your server
2. Open the [`Plans` page](http://calypso.localhost:3000/plans/:site)
3. Purchase a plan with a credit credit card
4. Assert that you are redirect to the thank you page with the correct information on it
5. Navigate to another page (like reader)
6. Assert that clicking back reloads the thank you page

#### Testing instructions - PayPal

1. Run `git checkout fix/thank-you-page` and start your server
2. Open the [`Plans` page](http://calypso.localhost:3000/plans/:site)
3. Purchase a plan with paypal
4. Go through the paypal flow
4. Assert that you are redirect to the thank you page with the correct information on it
5. Navigate to another page (like reader)
6. Assert that clicking back reloads the thank you page

#### Testing instructions - generic thank you page
1. Visit `/checkout/:site/thank-you` for any site.
2. Assert that you see a [generic thank you page](https://cloudup.com/cpStlBbu7LJ).

#### Additional notes

Also worth testing:
- different plans
- premium themes
- domains

#### Reviews

- [x] Code
- [x] Product

### CODE REVIEW

**Comment by drewblaisdell** [comment]
I broke this into two PRs (the other, #3294, is in review) to make it easier to review. This will be ready for review once:

- I add a placeholder state to the thank you page.
- #3294 is merged.
- This is rebased.

**Comment by drewblaisdell** [comment]
This has been rebased, and a loading state for `CheckoutThankYou` has been added.

This should work on the production API for credit card purchases now. Once the API is updated to redirect users that purchase with PayPal back to `/checkout/:site_slug/:receipt_id/thank-you`, this will work for all users.

File: client/lib/products-values/index.js [hunk 1]
```diff
@@ -281,6 +304,8 @@ module.exports = {
 	isFreeJetpackPlan,
 	isFreeTrial,
 	isGoogleApps,
+	isJetpackBusiness,
+	isJetpackPremium,
 	isJetpackPlan,
```
Comment (stephanethomas) [inline client/lib/products-values/index.js]: The order is almost right :).

File: client/my-sites/upgrades/index.js [hunk 2]
```diff
@@ -276,8 +276,8 @@ module.exports = function() {
 
 	if ( config.isEnabled( 'upgrades/checkout' ) ) {
 		page(
-			'/checkout/thank-you',
-			upgradesController.redirectIfThemePurchased,
+			'/checkout/:domain/:receipt_id/thank-you',
```
Comment (stephanethomas) [inline client/my-sites/upgrades/index.js]: We should use `:site` instead of `:domain` in the route.

Comment (stephanethomas) [inline client/my-sites/upgrades/index.js]: We should also use `:receiptId` instead of `:receipt_id`.

**Comment by stephanethomas** [comment]
I tried to purchase a domain mapping but the following error was raised when displaying the `Thank You` page:

screenshot

That's because the [`isDomainMapping()` function](https://github.com/Automattic/wp-calypso/blob/fix/thank-you-page/client/my-sites/upgrades/checkout/thank-you.jsx#L263) expects a `product_slug` property whereas we feed it with a `productSlug`:

```
freeTrial: false
isDomainRegistration: false
meta: "example.com"
productId: 5
productNameShort: null
productSlug: "domain_map"
```

**Comment by stephanethomas** [comment]
My understanding was that we shouldn't have to update the API for PayPal since the endpoint already accepts a [success url](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/upgrades/checkout/paypal-payment-box.jsx#L78) (i.e. a return url). However I tried to purchase with PayPal but the following error was raised upon submitting the form:

screenshot

That's because we call [`getCheckoutCompleteRedirectPath()`](https://github.com/Automattic/wp-calypso/blob/fix/thank-you-page/client/my-sites/upgrades/checkout/checkout.jsx#L136) too early during the checkout process, i.e. at a time where no receipt has been fetched yet.

**Comment by stephanethomas** [comment]
As mentioned internally, after much head-scratching this afternoon, it seems there is no other solution than hacking the API code to return the new success url.

**Comment by drewblaisdell** [comment]
Thanks for looking, @stephanethomas.

> That's because the [`isDomainMapping()` function](https://github.com/Automattic/wp-calypso/blob/fix/thank-you-page/client/my-sites/upgrades/checkout/thank-you.jsx#L263) expects a `product_slug` property whereas we feed it with a `productSlug`:

`isDomainMapping` accepts an object with either camel/snake cased properties:

```js
isDomainMapping( { productSlug: 'domain_map' } ); // => true
```

The problem was that I never imported `find` (:sweat_smile:) and the error message wasn't helpful because `find` is also a [method on `window`](https://developer.mozilla.org/en-US/docs/Web/API/Window/find).

File: client/my-sites/upgrades/checkout/checkout.jsx [hunk 3]
```diff
@@ -118,8 +120,22 @@ const Checkout = React.createClass( {
...
+			flatPurchases = flatPurchases.concat( sitePurchases );
+		} );
+
+		return flatPurchases;
+	},
+
 	getCheckoutCompleteRedirectPath: function() {
-		var renewalItem;
+		var renewalItem,
+			receiptId = ':receipt_id';
```
Comment (stephanethomas) [inline client/my-sites/upgrades/checkout/checkout.jsx]: Sorry to be nitpicky but this should be `:receiptId`.

File: client/my-sites/upgrades/index.js [hunk 4]
```diff
@@ -276,8 +276,8 @@ module.exports = function() {
 
 	if ( config.isEnabled( 'upgrades/checkout' ) ) {
 		page(
-			'/checkout/thank-you',
-			upgradesController.redirectIfThemePurchased,
+			'/checkout/:site/:receipt_id/thank-you',
```
Comment (stephanethomas) [inline client/my-sites/upgrades/index.js]: This was already mentioned before but we should also use `:receiptId` instead of `:receipt_id`.

**Comment by scruffian** [comment]
I saw this when testing:

screen shot 2016-02-19 at 10 59 07

**Comment by fabianapsimoes** [comment]
Product :+1: 

I've tested the following products: plans, domain registration, domain mapping, Google Apps and a Premium theme. Both credit card and PayPal.

Nice job, Drew!

File: client/my-sites/upgrades/checkout/checkout.jsx [hunk 5]
```diff
@@ -133,8 +149,17 @@ const Checkout = React.createClass( {
...
-		// TODO: include the receipt ID in this URL when it is present
-		return `/checkout/${ this.props.sites.getSelectedSite().slug }/thank-you`;
+		if ( this.props.transaction.step.data && this.props.transaction.step.data.receipt_id ) {
+			receiptId = this.props.transaction.step.data.receipt_id;
+
+			this.props.fetchReceiptCompleted( receiptId, {
+				receiptId: receiptId,
+				purchases: this.getPurchasesFromReceipt()
+			} );
+		}
```
Comment (stephanethomas) [inline client/my-sites/upgrades/checkout/checkout.jsx]: I'm not a big fan of accessing the transaction data directly like this. It would be great to hide that logic by using the receipts reducer. To be more specific, what I suggest is to update the `store-transactions` module to update the [receipts state tree](https://github.com/Automattic/wp-calypso/tree/master/client/state/receipts) when [receiving a response](https://github.com/Automattic/wp-calypso/blob/master/client/lib/store-transactions/index.js#L172) from the API. What do you think? That way we would also reduce the number of lines of code by reusing the [receipt assembler](https://github.com/Automattic/wp-calypso/blob/master/client/state/receipts/assembler.js).

**Comment by stephanethomas** [comment]
I've raised a point about simplify our code but this is something that can be addressed in a different pull request - that way we can deploy this one today.

**Comment by drewblaisdell** [comment]
Thanks for the reviews/commits, @fabianapsimoes @stephanethomas @scruffian.

I just realized that this PR also needed a commit that renders a generic thank you page at `/checkout/:site/thank-you`: https://cloudup.com/cpStlBbu7LJ This is necessary for the case where the API redirects the user to that route when we fail to generate a receipt ID (which @peterbutler claims happens a very small percentage of the time).

This is easy to test and a component already existed for it, so I added it in with [this](https://github.com/Automattic/wp-calypso/commit/5b36788c7419c8b8707c6fcc676ad93148d9ceb7) commit.

**Testing**
- Visit `/checkout/:site/thank-you` for any site.
- Assert that you see a [generic thank you page](https://cloudup.com/cpStlBbu7LJ).

I've updated the testing instructions above and unchecked code/product. We should only need to review this commit.

**Comment by scruffian** [comment]
Tested and reviewed again :ship:

File: client/my-sites/upgrades/checkout/checkout.jsx (hunk 5 above)
Comment (drewblaisdell) [inline client/my-sites/upgrades/checkout/checkout.jsx]: I opened an issue for this: https://github.com/Automattic/wp-calypso/issues/3422
