### PR TITLE
Stepper: Only call `calypso_stepper_flow_start`  when the user lands to a valid step

### LINKED ISSUE #95035: Stepper: `calypso_stepper_flow_start`  event is using locale code as step when the flow is started with the `/setup/:flow/:locale`
### Details

Steps to Reproduce
- Access any flow with a locale code. E.g.`/setup/migration/es`
- Clean up your session storage using `sessionStorage.clear()`  in the developer console
-  Access `/setup/migration` again reloading the page
-  Check the `calypso_stepper_flow_start` was called with the locale code as step

**What is expected?**
We should use the correct step name 

**What is happening?**
In the described scenario, we are using the locale name as the step name.

### Related

Related to p1727701047312749-slack-C073776NJ66

### PR DESCRIPTION
**Pull request by gabrielcaires**
Closes  #95035

## Proposed Changes
* Disable the calypso_stepper_flow_start event trigger when the flow is started with an invalid step.

## Why are these changes being made?
Nowadays, we can start a flow using different ways:
1. `/setup/:flow`  -  Redirects user to the first flow step
2. `/setup/:flow/:step/` 
4. `/setup/:flow/:step/:lang`
5. `/setup/:flow/:lang`  --> Redirect the user to the first flow step using the correct language. * 

* If a flow starts with a locale code on the user, but the user is logged in, we respect the user preference instead of the URL.

Scenarios 2 and 4 are conflicting because we need to differentiate if the value after the flow name is a step or a locale.

This PR updates it only to trigger the `calypso_stepper_flow_start` when the user lands on a valid step. 

## Testing Instructions
* Clean up your sessionStorage  `sessionStorage.clear()`
* Access `/setup/migration/es` 
*  Check if you have a call to the calypso_stepper_flow_start event with the correct step name.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/landing/stepper/declarative-flow/internals/index.tsx [hunk 1]
```diff
@@ -75,10 +75,14 @@ export const FlowRenderer: React.FC< { flow: Flow } > = ( { flow } ) => {
...
 	const isLoggedIn = useSelector( isUserLoggedIn );
 	const { lang = null } = useParams();
+	const isValidStep = params.step != null && stepPaths.includes( params.step );
 
 	// Start tracking performance for this step.
 	useStartStepperPerformanceTracking( params.flow || '', currentStepRoute );
-	useFlowAnalytics( { flow: params.flow, step: currentStepRoute, variant: flow.variantSlug } );
+	useFlowAnalytics(
+		{ flow: params.flow, step: params.step, variant: flow.variantSlug },
+		{ enabled: isValidStep }
```
Comment (chriskmnds) [inline client/landing/stepper/declarative-flow/internals/index.tsx:84]: Something isn't connecting with me here. To clarify my undestanding: A step being `invalid` here covers the case where the request is for `/setup/:flow/:lang`, correct? Where the step is falsely assumed to be `lang`. In that case, we "disable" a hook.

If my reading is correct, then the issue still exists in the app (in the routing/`useFlowNavigation`), so are we ignoring the root cause? Should we focus instead on attaching a correct/valid step onto `params`, so this ambiguity is eliminated (and the need to accompany with `isValidStep`)?

Comment (gabrielcaires) [reply client/landing/stepper/declarative-flow/internals/index.tsx:84]: > Something isn't connecting with me here. To clarify my undestanding: A step being invalid here covers the case where the request is for /setup/:flow/:lang, correct? Where the step is falsely assumed to be lang. In that case, we "disable" a hook.
Yes, you are right.

> If my reading is correct, the issue still exists in the app (in the routing/useFlowNavigation), so are we ignoring the root cause?

Partially. I think the ideal solution would be not to render the complete flow-render code. We may have bugs in any code inside this component regardless of whether the `useFlowNavigation` returns the correct step because the flows always assume a valid step was rendered. 

My concern in updating `useFlowNavigation,` which are flows we are checking if the user is on the initial step, like [this](https://github.com/Automattic/wp-calypso/blob/ce12270095c0bef77d1986e8115a366bf16f1956/client/landing/stepper/declarative-flow/migration/index.tsx#L320). 

It will just run while we redirect the user to the correct step.

What do you think about skipping the `FlowRender` component rendering?

Comment (chriskmnds) [reply client/landing/stepper/declarative-flow/internals/index.tsx:84]: Thanks for following up :-)

> I think the ideal solution would be not to render the complete flow-render code. We may have bugs in any code inside this component regardless of whether the `useFlowNavigation` returns the correct step because the flows always assume a valid step was rendered.
>
> My concern in updating `useFlowNavigation`, which are flows we are checking if the user is on the initial step, like [this](https://github.com/Automattic/wp-calypso/blob/ce12270095c0bef77d1986e8115a366bf16f1956/client/landing/stepper/declarative-flow/migration/index.tsx#L320).

Agreed. I meant to explain my thinking in broader terms. I haven't actually inspected `useFlowNavigation`, just thought this is an issue with a layer above the `FlowRender` component e.g. a "routing" issue or a missing knowledge of a default or first step. 

I guess a question is whether a flow access without a valid step makes sense at all in purely logical terms. There's obviously always some step being rendered - so what's a flow with an invalid one? If this is correct, then what you suggest to "skip the `FlowRender` component" makes sense. Is this your thinking also?

If you'd rather we ship this and do a follow-up in separate PR/issue, also works for me.

Comment (gabrielcaires) [reply client/landing/stepper/declarative-flow/internals/index.tsx:84]: >  Is this your thinking also?

Yes, I think it will save us to introduce more complexity and prevent bugs.

>  If you'd instead we ship this and do a follow-up in separate PR/issue, also works for me. 
Agree. I am working on another project now, so shipping this will give me more time to do it. 

I just need approval on this PR.

Comment (chriskmnds) [reply client/landing/stepper/declarative-flow/internals/index.tsx:84]: Sounds good. I can create the issue from our convo and carry on there.

**Review by chriskmnds — APPROVED** [review]
Tests out as outlined. Thanks! 🚢 
I'll create the follow-up issue later and we can continue more freely there.

One other thing I want to highlight is whether we need the restriction to only record `calypso_stepper_flow_start` once per every few seconds. So a page reload won't record it again until that interval passes. Technically speaking, `calypso_stepper_flow_start` should indicate the start of a flow. It might not be necessary to have any such logic in place i.e. any reload should re-record the event as it's a fresh restart technically, no? cc @escapemanuele @MicBosi 

> any reload should re-record the event as it's a fresh restart technically

Just like we have for `calypso_signup_start`. Are there different semantics/expectations with `calypso_stepper_flow_start`? 🤔

**Comment by MicBosi** [comment]
> One other thing I want to highlight is whether we need the restriction to only record calypso_stepper_flow_start once per every few seconds. So a page reload won't record it again until that interval passes. 

@chriskmnds I left a few related thoughts [here](https://github.com/Automattic/wp-calypso/issues/95106#issuecomment-2391484592). I think in general 1) we should probably avoid doing it, 2) avoid creating situations where these type of things are need in the first place.

What would be a situation where a page fires multiple times per second the same `calypso_stepper_flow_start` event?

**Comment by chriskmnds** [comment]
@MicBosi 

> What would be a situation where a page fires multiple times per second the same `calypso_stepper_flow_start` event?

The current logic already restricts this to only fire once a certain interval has passed. I think it was put together to avoid recording again when user is "re-entering" the flow - presumably this was relevant when we were redirecting to `/start` for logging in. @gabrielcaires can confirm. I'm wondering if it's obsolete logic we need to clean up.

**Comment by gabrielcaires** [comment]
I merged the PR because the discussion are related to other topic than the PR is fixing 👍

**Comment by gabrielcaires** [comment]
> Is it obsolete logic we need to clean up?

> I think it was put together to avoid recording again when user is "re-entering" the flow - presumably this was relevant when we were redirecting . 

Yes, especially if a user starts a flow that doesn't require login after some initial steps.  
If this scenario is not more valid we can think about remove this logic.
