### PR TITLE
Jetpack Search purchase flow: Allow 'enter' key form submission during purchase flow

### LINKED ISSUE #54344: Purchase Product: pressing enter on the text input doesn't work on /purchase-product/jetpack_search/monthly
Originally noted by @jsnmoon.

**Steps to reproduce the issue**

1. Attempt to purchase a Search plan via `/purchase-product/jetpack_search/monthly`.
2. Choose a site, then try and press Enter to submit the form.

**What I expected**

Enter submits the form.

**What happened instead**

You can use Enter to select a site, but you can't use it to submit the form.

Screen Shot 2021-07-07 at 15 53 31

### PR DESCRIPTION
**Pull request by interlineae**
## Proposed Changes

Addresses #54344

This PR enables the use of the `Enter` key to submit the form at `/purchase-product/jetpack_search/monthly`.

> [!NOTE]  
> Because `components/suggestion-search/index.jsx` is modified, this change also impacts any form that uses this component, meaning that `Enter` key submission would not be limited to only the form shown through the `/purchase-product/jetpack_search/monthly` flow. I looked into limiting the change to the one form, but if `Enter` key submission is a UX/QoL concern for the Jetpack Search purchase flow, then I would expect it to be a concern for similar flows elsewhere, and so we wouldn't want to limit this change.

## Why are these changes being made?

This addresses a UX/QoL concern. As a user, I would expect to be able to press `Enter` twice when going through this purchase flow — once to select my site from the Site Search field and again to submit the form itself via the `Get Search` button. Right now, pressing `Enter` to select my site prevents `Enter` being used again to submit the form.

## Testing Instructions

* Ensure you're testing with an account that has a Jetpack-connected site, but no Search plan purchased.
* Navigate to `/purchase-product/jetpack_search/monthly` and begin to type your site's URL
* Press `Enter` to select the suggested site
* Press `Enter` again to submit the Jetpack Search `Get Search` form
* Upon pressing enter you should expect to be taken to the billing area to enter your purchase details
* Try the same flow again using mouse clicks, and a combination of mouse clicks and `enter` key presses

- Confirm no unexpected behaviour at the other paths impacted by this change:
  - `/purchase-product/jetpack_search`
  - `/purchase-product/jetpack_search/monthly`
  - `/purchase-product/wpcom_search`
  - `/purchase-product/wpcom_search/monthly`

- Confirm Jetpack connection flow is not impacted, including:
  - `/jetpack/connect/`
  - `/jetpack/connect/search`

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you tested accessibility for your changes? Ensure the feature remains usable with various user agents (e.g., browsers), interfaces (e.g., keyboard navigation), and assistive technologies (e.g., screen readers) (PCYsg-S3g-p2).
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/components/suggestion-search/index.jsx [hunk 1]
```diff
@@ -95,15 +115,6 @@ class SuggestionSearch extends Component {
...
 	}
 
-	getSuggestionLabel( suggestionPosition ) {
-		return this.suggestionsRef.props.suggestions[ suggestionPosition ].label;
-	}
-
-	updateFieldFromSuggestion( newValue ) {
-		this.updateInputValue( newValue );
-		this.props.onChange( newValue, true );
-	}
```
Comment (interlineae) [inline client/components/suggestion-search/index.jsx]: These methods are unused.

**Comment by anaemnesis** [comment]
@Automattic/red I'm not quite sure who to request for review on this. Would someone on the team have availability, or be able to suggest a better someone to reach out to?

File: client/jetpack-connect/site-url-input.jsx [hunk 2]
```diff
@@ -207,6 +207,10 @@ class JetpackConnectSiteUrlInput extends Component {
 							id="siteSelection"
 							placeholder="Type your site"
 							onChange={ this.handleChange }
+							onSelect={ this.props.onSelect }
+							onSubmit={ this.handleFormSubmit }
```
Comment (kangzj) [inline client/jetpack-connect/site-url-input.jsx]: The approach does work, but I don't think it's following the best practices to submit a form from a input field. We should probably wrap the inputs up with `<form></form>` and handle the submission from there. An example could be found at: https://react.dev/reference/react-dom/components/input#reading-the-input-values-when-submitting-a-form

**Review by kangzj — COMMENTED** [review]
It works well, but maybe it's not the best way to submit a form from an input. Left a comment.

File: client/jetpack-connect/site-url-input.jsx (hunk 2 above)
Comment (interlineae) [reply client/jetpack-connect/site-url-input.jsx]: @kangzj That is good to know! I think I've addressed that here https://github.com/Automattic/wp-calypso/pull/104885/commits/d47175e9a552b3002916c86298c330da5b43a9b6.

**Review by kangzj — APPROVED** [review]
Thanks for iterating on this. I only reverted some unnecessary changes. Hope you don't mind. Think it's good to ship now 🚀
