### PR TITLE
Domains: Update Domain Mapping Thank You

### LINKED ISSUE #11848: Purchases: Update mapping instructions for subdomains
When you map a subdomain to your site, the instructions you receive following purchase still mention name servers. The instructions should instruct users to update the CNAME record on their domain instead.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains/manage/{site}
2. Go through the steps to map a subdomain to your site

#### What I expected
To get clear instructions tell me to set a CNAME record to WordPress.com. Basically, these instructions:

https://en.support.wordpress.com/map-subdomain/

#### What happened instead
The instructions still mentioned name servers, which isn't applicable if you're just mapping a subdomain.

#### Screenshot / Video

screen shot 2017-03-04 at 8 27 30 am

#### Context / Source
#reallife

### PR DESCRIPTION
**Pull request by aidvu**
Fix #11848 
Depends on D10749-code

After purchasing a domain mapping, display the correct instructions according to the following cases:

- Domain
- Subdomain (non-Business Plan)
- Subdomain (Business Plan)
- Subdomain with root domain registered with us

The "Learn More" button has been updated as well to point to the [Map a Subdomain](https://en.support.wordpress.com/domains/map-subdomain/) support page.

| Domain | Subdomain | Subdomain (Biz) |
| --- | --- | --- |
| screen shot 2018-03-06 at 12 39 24 | screen shot 2018-03-06 at 12 37 24 | screen shot 2018-03-06 at 12 36 56 |

### Testing instructions

Add a domain mapping to some sites and make sure that:

- If the mapped domain is an actual domain, the instructions show a list of:
`ns1.wordpress.com` (etc.).
- If it's a subdomain and the site plan is not Business, the instructions show a single line:
`subdomain.foo.bar IN CNAME sitename.wordpress.com`.
- If it's a subdomain for a Business plan, the instructions show a list of:
`subdomain.foo.bar IN NS ns1.wordpress.com` (etc.).
- If it's a subdomain with a root domain registered with us, it should show a congratulations screen w/o any instructions because we set everything up automatically.

Also make sure that the "Learn More" button points to the correct page (map domain or map subdomain).

/cc @Copons as I shamelessly stole his PR description. I used your work, and built on it to improve the copy. Thanks!

### CODE REVIEW

**Comment by ranh** [comment]
Since the main concern here is that this screen makes people feel like their job is done, I suggest we get rid of "congratulations" and the trophy illustration.

My suggestion for the domain mapping case:

> **Almost done!**
> 
> Follow the instructions below to finish setting up your domain **subdomain.example.com**.
> 
> > To point your domain at your WordPress.com site, log in to your domain provider's site (where you purchased the domain), and update your name servers to:
> >
> > *ns1.wordpress.com*
> > *ns2.wordpress.com*
> > *ns3.wordpress.com*
> >
> > Need help? Get [detailed instructions and more information](https://en.support.wordpress.com/domains/map-existing-domain/). 
> >
> > If you already did this, no further action is required.

Chatting with @aidvu, he mentioned that the instructions for mapping a subdomain also need updating:

> **Almost done!**
> 
> Follow the instructions below to finish setting up your domain **subdomain.example.com**.
> 
> > To point your domain at your WordPress.com site, log in to your domain provider's site (where you purchased the domain), and edit the DNS records to add a CNAME record:
> >
> > `subdomain.example.com. IN CNAME example.wordpress.com.`
> >
> > Need help? Get [detailed instructions and more information](https://en.support.wordpress.com/domains/map-subdomain/). 
> >
> > If you already did this, no further action is required.

As for the illustration, @aidvu mentioned we already use this in a similar context: https://github.com/Automattic/wp-calypso/blob/a838cc82dbaf6484e3899ae7ebe07a7d856984aa/public/images/upgrades/publish-button.svg

I think it could work here too. cc @danhauk

**Comment by Copons** [comment]
Codewise, this LGTM.

Just an extremely minor nitpick.
I'm not a fan of `let` (reason why I went with 3 separate variables for each instructions case 😅), but also not strictly opposed to it.
Also, maybe the [conditional render](https://github.com/Automattic/wp-calypso/blob/ceeb2684757dd9a1f8a2cdb77308253a26537a90/client/my-sites/checkout/checkout-thank-you/domain-mapping-details.jsx#L113-L115) is slightly more readable?

All in all it mostly comes down to personal preference (even though, usually on Calypso we're inclined to always use `const`).

**Comment by aidvu** [comment]
Thanks @Copons. This feels more readable to me. 🤷‍♂️  If there's a preference on how we do it in Calypso, can switch!

**Comment by Copons** [comment]
> If there's a preference on how we do it in Calypso, can switch!

@aidvu Nah, it's not worth the effort. 🙂

**Comment by hambai** [comment]
Uhh... Okay, I may be a bit late but...

If the domain is registered with us and we map a subdomain to a site there is no need to add NS records for the subdomain because we do that automatically. Maybe we have to mention that in the copy?

Also, we do add NS records for all subdomains (not only for business plans) so theoretically the CNAME instructions for domains hosted with us is also a bit... misleading.

So how about we put a "If your domain is registered with wordpress.com we already did that for you." or something like that?

**Comment by aidvu** [comment]
@hambai what you're saying is that for domains already registered with us, but with a subdomain mapping are set right away?

@ranh suggestions?

**Comment by hambai** [comment]
@aidvu yeah. We can probably make a 4th version of that screen that is displayed for subdomains when the domain is registered with us that should say something like "We have set up all the necessary DNS records for you"

**Comment by danhauk** [comment]
@aidvu @hambai If the domain is already registered with us how about just using the original illustration and "Congratulations on your purchase" screen without the DNS explanation below it. The subheading could be something like 

> Your domain sub.example.com was added to your site. We have set everything up for you but it may take a little while to start working.

**Comment by aidvu** [comment]
Would have to return that info from the endpoint. Will think about it.

**Comment by aidvu** [comment]
Added 4th case. When subdomain, but root domain registered with us:

working

**Comment by aidvu** [comment]
@danhauk / @hambai updated!

File: client/my-sites/checkout/checkout-thank-you/header.jsx [hunk 1]
```diff
@@ -261,7 +287,7 @@ class CheckoutThankYouHeader extends PureComponent {
 		return (
 			<div className={ classNames( 'checkout-thank-you__header', classes ) }>
 				<div className="checkout-thank-you__header-icon">
-					<img src={ `/calypso/images/upgrades/${ svg }` } />
+					<img src={ `/calypso/images/upgrades/${ svg }` } alt="" />
```
Comment (klimeryk) [inline client/my-sites/checkout/checkout-thank-you/header.jsx]: That's not really addressing the issue :)

File: client/my-sites/checkout/checkout-thank-you/header.jsx [hunk 2]
```diff
@@ -98,9 +106,23 @@ class CheckoutThankYouHeader extends PureComponent {
 		}
 
 		if ( isDomainMapping( primaryPurchase ) ) {
+			if ( primaryPurchase.isRootDomainWithUs ) {
+				return translate(
+					'Your domain {{strong}}%(domain)s{{/strong}} was added to your site. ' +
+						'We have set everything up for you but it may take a little while to start working.',
```
Comment (klimeryk) [inline client/my-sites/checkout/checkout-thank-you/header.jsx]: I think there's a comma missing:
> We have set everything up for you*,* but it may ...

File: client/my-sites/checkout/checkout-thank-you/header.jsx (hunk 1 above)
Comment (aidvu) [reply client/my-sites/checkout/checkout-thank-you/header.jsx]: If you check the lint message, it says `empty string for decorative images`. :) Or we can reuse the `getHeading()`?

**Comment by aidvu** [comment]
The test behavior is unchanged from the previous one.

File: client/my-sites/checkout/checkout-thank-you/header.jsx (hunk 1 above)
Comment (aidvu) [reply client/my-sites/checkout/checkout-thank-you/header.jsx]: Actually, makes no sense, as that would have 2x the same info. empty `alt` is what we want here.

Comment (klimeryk) [reply client/my-sites/checkout/checkout-thank-you/header.jsx]: 🤷‍♂️ I guess it makes sense.
