### PR TITLE
Image Editor: disable on non-desktop/touch devices

### LINKED ISSUE #7979: hide feature in mobile (or make it work better)
Testing wpcalpso on my iphone, I can get to the "edit image" button, and I can click into the editing interface, but the image never loads and I cannot interact with the handles. I'm not sure if this is meant to work in mobile or not.

I suspect this isn't expected to work in mobile and we just need to hide the button for touch interface devices. But if I'm wrong, we have some work to do before we can launch this for mobile.

## Button Available
img_0383

## Image Editing Not Functional
img_0384

### PR DESCRIPTION
**Pull request by lamosty**
Fixes #7979.

The image editor doesn't yet support touch events. Let's disable it for mobiles/touch devices until we got it supported.

## Testing Instructions

1. In browser: In media modal, select an image and click on Edit;
2. Do you see "Edit image" button? Can you edit the image?
3. Either use a mobile device or just simulate it with dev tools: enable touch and/or resize browser window to <= 960px and reload the page;
4. Is the "Edit Image" button hidden? Is it not possible for you to edit the image?

Note: some desktop devices support touch events (e.g. Dell XPS 15). Image editor is disabled on them too. Maybe we could enable it on screen widths >960px, however some mobile devices might have this large screen and the image editor wouldn't still be usable. Any ideas?

/cc @gwwar @rralian @retrofox

### CODE REVIEW

File: client/post-editor/media-modal/detail/detail-item.jsx [hunk 1]
```diff
@@ -44,6 +47,10 @@ module.exports = React.createClass( {
 		};
 	},
 
+	isMobileTouchDevice() {
+		return ! isDesktop() || hasTouch();
```
Comment (rralian) [inline client/post-editor/media-modal/detail/detail-item.jsx]: I think this is good for now. We might want to revisit this at some point to make sure we're targeting the right devices (e.g., I think we should be able to support a Surface, but I think we'd be hiding it here). But I don't think we should do that until we get some real user feedback.

**Comment by rralian** [comment]
:shipit:

File: client/post-editor/media-modal/detail/detail-item.jsx (hunk 1 above)
Comment (gwwar) [inline client/post-editor/media-modal/detail/detail-item.jsx]: We might be fine with just the hasTouch check. I testing the image editor at smaller screen sizes and it looks like it still works OK.

**Comment by gwwar** [comment]
This looks good to me too. I'll add another issue for making sure crop works in mobile.

**Comment by lamosty** [comment]
Thanks for the reviews @rralian and @gwwar!
