### PR TITLE
Domains: Return to site selector if user does not have domain management permissions for selected site.

### LINKED ISSUE #23255: Site Picker: switching site to a site with lesser role on page not support throws console error (blank page)
You need a user with access to two sites

Site 1: Administrator - can access 'domains'
Site 2: Author - can't access 'domains'

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains/manage for site 1
2. Choose Switch Site
3. Choose site 2

#### What I expected

Redirected to Calypso home - or unauthorized page 

#### What happened instead

Blank screen with console error: `TypeError: null is not an object (evaluating 'n.ID')`

#### Browser / OS version

Chrome, Firefox, Safari on macOS

#### Screenshot / Video

switch sites

#### Context / Source
 #dogfooding

### PR DESCRIPTION
**Pull request by kwight**
Using the sidebar site selector to select a site for which the user has no domain privileges will result in a TypeError and a blank page. This is because as Calypso proceeds to switch sites, an API call to `/sites/:site/domains` will result in a 403, "User or Token does not have access to specified site.", making expected domain info unavailable. This PR patches two spots which can fatal in these cases. With this PR, the user will now end up redirected to the site selector at `/domains/manage` (the same as if loading an unauthorized site from the URL `/domains/manage/:site`).

Fixes #23255 .

**Testing**
* Log in as a user that has Admin privileges for one of their sites (`A`), and something less (say Author) on another (`B`).
* Load `/domains/manage/A`. This should work fine.
* Using the sidebar, select Switch Site, and click site B.
* This should reproduce the problem of a blank screen.
* Apply this PR, and repeat; after clicking B, you will be forwarded to `/domains/manage`.

### CODE REVIEW

**Comment by aidvu** [comment]
This is good, as it fixes the JS errors. The behavior is weird tho. We redirect to `/domains/manage`, but the site for which the user has no `Domains` access privileges is still there, and the user can click it again, and it redirects back to `/domains/manage`.

We could probably check if they have access, and redirect to the `/stats` page, or remove the site from the `SitePicker` for `/domains/manage`. I think there's a `filter` function you can pass to the site picker.

What do you think @kwight?

File: client/components/data/domain-management/index.jsx [hunk 1]
```diff
@@ -59,7 +59,7 @@ const DomainManagementData = createReactClass( {
 		const { selectedSite: prevSite } = this.props;
 		const { selectedSite: nextSite } = nextProps;
 
-		if ( nextSite !== prevSite ) {
+		if ( nextSite && nextSite !== prevSite ) {
 			fetchDomains( nextSite.ID );
```
Comment (gwwar) [inline client/components/data/domain-management/index.jsx]: I think we can simplify things further by also fetching selectedSiteId from redux in connect. In addition to that we could maybe update `fetchDomains` to no-op when it gets a falsey value, this would make much less work for the caller.

Comment (gwwar) [reply client/components/data/domain-management/index.jsx]: eg
```
if ( this.props.selectedSiteId !== nextProps.selectedSiteId ) {
    fetchDomains( nextProps.selectedSiteId );
}
```

Comment (gwwar) [reply client/components/data/domain-management/index.jsx]: Note that QueryComponents like `QuerySitePlans` can handle falsey siteId input (for ease of use). So similarly we can update this to:
```jsx
<QuerySitePlans siteId={ this.props.selectedSiteId } />
```

If `QueryContactDetailsCache` should only fetch data when there's a selected site available (in general) consider moving that check to the query component itself. If it's a one off we can of course call:
```jsx
{ this.props.selectedSiteId && <QueryContactDetailsCache /> }
```

**Comment by gwwar** [comment]
> We could probably check if they have access, and redirect to the /stats page, or remove the site from the SitePicker for /domains/manage. I think there's a filter function you can pass to the site picker.

Sounds reasonable to me to look into 👍 . Note that if we do filter, there's a corner case of a user having no eligible sites to manage, and so we should redirect in that case.

**Comment by alisterscott** [comment]
Thanks for the fix - as @aidvu points out - this fixes the JavaScript console errors, but the site picker still shows the site for which I can't manage the domains for. I guess that's a separate issue.

Perhaps instead of showing the domains page when switching site it should show the calypso root page (stats)?

**Comment by kwight** [comment]
I agree, I'd say the root problem is that the site selector shouldn't display sites for which the user doesn't have access/privileges – this is a bigger project though, while this PR will simply stop the fatals and get us to a predictable behaviour (whether it's the best behaviour or not).

I'd say we merge this as-is, and do any further optimization/UX work in other PRs.

**Comment by gwwar** [comment]
How about if we simply redirect to stats for this case? We can do something smarter as a follow up PR.

**Comment by gwwar** [comment]
So it looks like we have the following redirect behavior for the following routes, where basically if a site does not have correct permissions, we redirect to the specified subroot (in all sites view), except when the user only has a single site to avoid a redirect loop.
`domains/add/*`
`domains/manage/*`

Let's hold off on additional behavior changes. Folks can follow up on that in other PRs. I would also highly recommend deleting path.js and using interpolated strings in `domains/index.js`. There was a lot of indirection and some things were difficult to search for.

```jsx
const redirectIfNoSite = redirectTo => {
	return ( context, next ) => {
		const state = context.store.getState();
		const siteId = getSelectedSiteId( state );
		const userCanManageOptions = canCurrentUser( state, siteId, 'manage_options' );

		if ( ! userCanManageOptions ) {
			const user = getCurrentUser( state );
			const visibleSiteCount = get( user, 'visible_site_count', 0 );
			//if only one site navigate to stats to avoid redirect loop
			const redirect = visibleSiteCount > 1 ? redirectTo : '/stats';
			return page.redirect( redirect );
		}
		next();
	};
};
```

**Comment by alisterscott** [comment]
Looks like a good idea to land this as-is and I can raise a follow up issue for the redirection.

**Comment by alisterscott** [comment]
I've raised the site picker issue here: https://github.com/Automattic/wp-calypso/issues/23351
