### PR TITLE
PlanNoticeCreditUpgrade: Replace support link with InlineSupportLink component

### LINKED ISSUE #83923: Upgrade Credit support link doesn't land on correct section, and browser back doesn't work properly
### Quick summary

I clicked on the link on the Plans page to `upgrade credit` today, actually thinking that this would show my upgrade credit in a cart or something. Instead I was directed to: `https://wordpress.com/support/manage-purchases/upgrade-your-plan/`, not the "upgrade credit" section. 

Then, when trying to return to my plans page, the `back` button in my browser didn't take me back until I reached a wp-admin page (the site editor).

Link directs to: `https://wordpress.com/support/manage-purchases/upgrade-your-plan/#upgrade-credit`

### Steps to reproduce

1. Open a site with a paid plan attached
2. Open the Plans page
3. Click on the "upgrade credit" link from the notice of upgrade credits at the top of the plans page in the same tab
     - _Observe that the doc opens to the top of the document_
4. Click "back" in the browser a few times, watching the address bar

### What you expected to happen

To return to the Plans page right away

### What actually happened

The address bar first shows the correct `#upgrade-credit` link, but the support doc only reloads, and doesn't jump to that section. Then it changes to `https://wordpress.com/home/` rather than the plans page, but I'm still not directed there.

Once I reach the site-editor, the last wp-admin page I was working on, my browser finally loads that page.

**Recording**

https://github.com/Automattic/wp-calypso/assets/27249804/0b855f70-bb45-4517-805a-b30f90a12226

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Happening consistently on a Simple site using **Firefox 119.0**

### PR DESCRIPTION
**Pull request by bogiii**
Closes #83923

## Proposed Changes

* Fixes the redirection/linking issue when the user clicks on "upgrade credits" (more info: https://github.com/Automattic/wp-calypso/issues/83923)

Screenshot 2024-09-17 at 12 35 59

## Why are these changes being made?

* The global router handler causes the issue, so we use the `InlineSupportLink` component to have a unified way of handling support page redirection.

## Testing Instructions

* Go to `/plans/{SITE_SLUG}` *it should be an atomic site
* Click on "upgrade credits"
* Check if you are redirected (in new tab) to "/support/manage-purchases/upgrade-your-plan/#upgrade-credit" -> Upgrade Credit section

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?-

### CODE REVIEW

**Review by fushar — COMMENTED** [review]
Seems to me that this is another patch to a problem rather than a fix 🤔 

I think, there is another problem here. When I click the URL, the hash is lost and I do not get scrolled to the `#upgrade-credit` heading automatically.

I think a "more correct" solution is to update the link to an `<InlineSupportLink>` or an `<ExternalLink>` instead. I see more instances of these patterns recently. What do you think?

**Comment by bogiii** [comment]
> I think, there is another problem here. When I click the URL, the hash is lost and I do not get scrolled to the #upgrade-credit heading automatically.

This is precisely what is fixed with this PR.

> I think a "more correct" solution is to update the link to an <InlineSupportLink> or an <ExternalLink> instead. I see more instances of these patterns recently. What do you think?

Sure, I can give it a try.

Thanks for the suggestion.

File: client/my-sites/plans-features-main/components/plan-notice-credit-update.tsx [hunk 1]
```diff
@@ -16,13 +17,7 @@ type Props = {
 	visiblePlans?: PlanSlug[];
 };
 
-const PlanNoticeCreditUpgrade = ( {
-	className,
-	onDismissClick,
-	linkTarget,
```
Comment (fushar) [inline client/my-sites/plans-features-main/components/plan-notice-credit-update.tsx:22]: I think we need to remove this prop in all callers.

**Review by fushar — APPROVED** [review]
Much better now! :)

File: client/my-sites/plans-features-main/components/plan-notice-credit-update.tsx (hunk 1 above)
Comment (bogiii) [reply client/my-sites/plans-features-main/components/plan-notice-credit-update.tsx:22]: Make sense. I'll clean it up.
