### PR TITLE
Storefront: Add unique theme demo URL for Storefront as a temporary workaround

### LINKED ISSUE #37658: Theme Showcase: Incorrect Link To Storefront Demo site
#### Steps to reproduce

On an atomic Business plan site:

1. Install & activate WooCommerce.
2. Starting at URL: https://wordpress.com/themes/
2. Search for the Storefront theme
3. Click the three dots and then "Live Demo"

#### What I expected

I expected to view a site that showcases the Storefront theme, like this:

https://themes.woocommerce.com/storefront/

#### What happened instead

It opens this page:

https://wp-themes.com/storefront/?demo=true&iframe=true&theme_preview=true

While that seems to be using the Storefront theme, it is not a demo site that shows the features of Storefront. For example, no products on the homepage. This is unhelpful for people considering Storefront as the demo site does not show the potential of the theme.

Same result when accessing the live demo from this screen:

https://wordpress.com/theme/storefront/

#### Screenshot / Video

Screen+Recording+2019-11-18+at+10 27 14 87+AM

#### Context / Source

Seen during #2499500-zen

### PR DESCRIPTION
**Pull request by sixhours**
#### Changes proposed in this Pull Request

* Temporarily update the `getThemeDemoUrl` selector to point to a special demo site for Storefront rather than the automatically generated one at wp-themes.com
* Update direct references to the demo site on the theme sheet to the unique demo site for Storefront
* Also updates button copy for "Open Live Demo" to use Title case

Fixes #37658

[We talked about whether we should do a "hacky" fix like this and decided it's probably worth it](https://github.com/Automattic/wp-calypso/issues/37658#issuecomment-843426848), since it does not look like we'll be adding Storefront to WP.com soon.

**Before**

Screen Shot 2021-06-01 at 1 13 02 PM

**After**

Screen Shot 2021-06-01 at 1 15 13 PM

#### Testing instructions

* Switch to this PR
* Navigate to `/themes` for an Atomic site
* Search for Storefront under "Show all themes"
* Click the "Live demo" link under the theme's ellipsis menu; it should first open an iFrame preview, which then redirects you to `https://themes.woocommerce.com/storefront/` in a new tab (this is the known behavior for all themes uploaded by a user ie. not native to WP.com)
* View the theme sheet for Storefront (click on the screenshot); you should see `https://themes.woocommerce.com/storefront/`as the URL when you hover over the "Open live demo" button or the theme screenshot on the right
* Clicking on either the screenshot or the "Open live demo" button should open the iFrame preview, which then redirects you to `https://themes.woocommerce.com/storefront/` in a new tab
* Make sure other themes' demo links work as expected; themes native to WP.com will open demo sites in the iFrame preview, themes that have been installed by the user will open in a new tab

### CODE REVIEW

File: client/my-sites/theme/main.jsx [hunk 1]
```diff
@@ -555,7 +556,7 @@ class ThemeSheet extends React.Component {
 						</div>
 					</div>
 					<Button primary={ true } href={ '/themes/' }>
-						{ i18n.translate( 'See All Themes' ) }
+						{ i18n.translate( 'See all themes' ) }
```
Comment (a8ci18n) [inline client/my-sites/theme/main.jsx:565]: :warning: This change will be queued for retranslation. We'll display the English text until then.

File: client/my-sites/theme/main.jsx [hunk 2]
```diff
@@ -243,7 +243,7 @@ class ThemeSheet extends React.Component {
 		return (
 			<div className="theme__sheet-preview-link">
 				<span className="theme__sheet-preview-link-text">
-					{ i18n.translate( 'Open Live Demo', {
+					{ i18n.translate( 'Open live demo', {
```
Comment (a8ci18n) [inline client/my-sites/theme/main.jsx:249]: :warning: This change will be queued for retranslation. We'll display the English text until then.

**Comment by DanielSmithMichigan** [comment]
Looking at this one

File: client/my-sites/theme/main.jsx [hunk 3]
```diff
@@ -797,6 +808,7 @@ const ThemeSheetWithOptions = ( props ) => {
 	return (
 		<ConnectedThemeSheet
 			{ ...props }
+			demo_uri={ 'Storefront' === themeName ? storefrontDemoUri : demo_uri }
```
Comment (DanielSmithMichigan) [inline client/my-sites/theme/main.jsx]: What do you think about defining the demo_uri property by re-using [the getThemeDemoUrl selector](https://github.com/Automattic/wp-calypso/blob/79c4583a523a3d6deed21f5ec79cfbdd03fab28a/client/state/themes/selectors/get-theme-demo-url.js#L16)? This way we would only define the storefrontDemoUri constant one time.

I pushed the suggestion up to this branch (untested): update/storefront-demo-link_danielsmithmichigan-suggestion

**Review by DanielSmithMichigan — COMMENTED** [review]
✅ "Live Demo" link from theme-options on theme card opens new url [video](https://d.pr/v/JDR5aV)
✅ "Open Live Demo" link from <ThemeSheet /> opens new url [video](https://d.pr/v/pz6cuT)
✅ Screenshot href from <ThemeSheet /> opens new url [video](https://d.pr/v/S8i96u)
✅ Twenty-twenty-one and spearhead live demos still work
✅ I found [only one other reference to demo_uri](https://user-images.githubusercontent.com/10274366/120511584-89d7d200-c398-11eb-9d89-285558b946d3.png), but confirmed the page isn't available for jetpack connected sites, so should not impact PR.
❓See comment

File: client/my-sites/theme/main.jsx (hunk 3 above)
Comment (sixhours) [reply client/my-sites/theme/main.jsx]: Good call! I honestly wondered if I should have added the logic in `getCanonicalTheme`, but then it feels wrong to mess with, uh, canon. 🤷‍♀️ I've swapped the passed prop for the selector in this case.

File: client/my-sites/theme/main.jsx [hunk 4]
```diff
@@ -839,6 +841,7 @@ export default connect(
 			canUserUploadThemes: hasFeature( state, siteId, FEATURE_UPLOAD_THEMES ),
 			// No siteId specified since we want the *canonical* URL :-)
 			canonicalUrl: 'https://wordpress.com' + getThemeDetailsUrl( state, id ),
+			demoUrl: getThemeDemoUrl( state, id ),
```
Comment (DanielSmithMichigan) [inline client/my-sites/theme/main.jsx]: Isn't siteId the third argument here?

Or is this similar to the above property, where we want the "canonical demo URL" ?

File: client/state/themes/selectors/get-theme-demo-url.js [hunk 5]
```diff
@@ -15,5 +15,12 @@ import 'calypso/state/themes/init';
  */
 export function getThemeDemoUrl( state, themeId, siteId ) {
 	const theme = getCanonicalTheme( state, siteId, themeId );
+	//Temp. workaround to show an accurate theme demo site for Storefront
```
Comment (DanielSmithMichigan) [inline client/state/themes/selectors/get-theme-demo-url.js]: It might help to link to the github comment which contains the reason why we did this, so the next person knows what to look out for when they undo this.

File: client/my-sites/theme/main.jsx (hunk 4 above)
Comment (DanielSmithMichigan) [reply client/my-sites/theme/main.jsx:844]: I noticed when we get the `theme` variable above, we use:

```
const theme = getCanonicalTheme( state, siteId, id );
```

getThemeDemoUrl uses getCanonicalTheme under the hood

```
export function getThemeDemoUrl( state, themeId, siteId ) {
	const theme = getCanonicalTheme( state, siteId, themeId );
```

So I think the usage of getCanonicalThemeUrl should be the same in both places, since it's the same connector function?

**Comment by kwight** [comment]
With @sixhours out this week, @DanielSmithMichigan can you pick this up where she left up and get it finished? Thanks!

**Review by DanielSmithMichigan — APPROVED** [review]
Finished testing and reviewing this today after I implemented my recommended changes.

I didn't find anything that should prevent us from merging this, so I plan to merge it tomorrow morning.

I did find [this suggestion](https://github.com/Automattic/wp-calypso/pull/53311#discussion_r644292766) made sense from a high level, but it doesn't seem like it should have any impact. Basically this enables calypso to look at the local theme repository for theme data (for jetpack connected sites). But it doesn't look like jetpack is syncing the demo_uri from the style.css page anyway, so it shouldn't have an impact.

I found that the href changes in this pull request actually just change the link addresses on the "Open Live Demo" button and screenshot. It's only used if you copy the address or open it directly. Those URLs are working correctly. The actual URL of the demo is populated using the themeId which is passed to the ThemePreview component.

I also stumbled into [this pre-existing error](https://user-images.githubusercontent.com/10274366/121111356-b5195180-c7dc-11eb-9a58-a0bf6ebaf88d.png) which occurs on a private, atomic site when you open the demo. Since it was pre-existing, I didn't think it should prevent this from being merged.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6007299).
