### PR TITLE
Comments: Remove error notices on single comment failed requests

### LINKED ISSUE #18322: Comments: when failing to retrieve comments, auto dismiss error message,  (or not show it)
Users are unable to do anything meaningful in this case, so it might be better to not show an error.

### PR DESCRIPTION
**Pull request by Copons**
Closes #18322

The PR title says it all.
The reason is that users can't do anything about it anyway.

This change affects both Comments Management and the Reader.
I checked both, and they both work as expected (no notices shown on failed single comments requests).

As a follow-up, for Comments Management, @kwight [proposed](https://github.com/Automattic/wp-calypso/issues/18322#issuecomment-337732346) to replace the failed comments' placeholder with an error message.
I think we could do this by taking advantage of the `comments.errors` state updated by `COMMENTS_RECEIVE_ERROR`

### CODE REVIEW

**Comment by kwight** [comment]
Works well for me 👍 

I tested by switching a particular comment ID to an invalid comment ID within the sandboxed API (so that it would return with `error: unknown_comment`). This triggered the notice on `master`, but the notice didn't display on this branch. In both cases, the placeholder just keep pulsing.

File: client/state/data-layer/wpcom/sites/comments/index.js [hunk 1]
```diff
@@ -111,37 +109,12 @@ export const receiveCommentSuccess = ( store, action, response ) => {
...
-			rawSite && rawSite.name
-				? translate( 'Failed to retrieve comment for site “%(siteName)s”', {
-						args: { siteName: rawSite.name },
-					} )
-				: translate( 'Failed to retrieve comment for your site' );
-
-		dispatch( errorNotice( error, { id: `request-comment-error-${ siteId }` } ) );
-	}
-
+export const receiveCommentError = ( { dispatch, getState }, { siteId, commentId } ) =>
```
Comment (rodrigoi) [inline client/state/data-layer/wpcom/sites/comments/index.js]: no need to destructure `getState`. (why the linter didn't catched it?)

Comment (kwight) [reply client/state/data-layer/wpcom/sites/comments/index.js]: Heyyyyy, great catch – yeah, I don't get any linter complaints either.

**Comment by gwwar** [comment]
I think we'll want to add some handling for those infinite placeholders in the PR. Kirk's suggestion looks like a good path forward.

cc @samouri @blowery what would you like the Reader to do in this case?

**Comment by samouri** [comment]
I'm not sure what our Reader current behavior is yet.  I have a feeling this might be the cause of an infinite error loop i've been seeing recently. We'll want to make sure this works as well.

**Comment by gwwar** [comment]
Any updates here @samouri or @blowery ?

**Comment by samouri** [comment]
I've separately filed the bug: https://github.com/Automattic/wp-calypso/issues/19233

**Comment by Copons** [comment]
Thanks @samouri, I'll deploy this!
