### PR TITLE
Reading settings: correctly update incoming fields based on prevState to avoid race condition

### LINKED ISSUE #79506: After changing theme, sometimes the Reading Settings shows wrong value for "Your homepage displays"
### Quick summary

Some themes (currently, the ones with the `auto-loading-homepage` tag) will update the "Your homepage displays" setting to a new page upon activation. However, this new value is sometimes not reflected in the Reading Settings page.

@Automattic/lego 

### Steps to reproduce

Note: it is important to follow the steps EXACTLY.

1. Create a new site.
1. Skip the Design Picker theme selection, which will set the theme of your site to TT3.
1. Go to Settings -> Reading.
1. First, verify that the values are correct: 
    
    image

1. Activate Meraki theme (or any theme in https://wordpress.com/themes/filter/auto-loading-homepage).
1. Go back to Settings -> Reading.

### What you expected to happen

The values should be:

image

### What actually happened

The values are not updated (though actually on the backend side, the values did update)

image

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by fushar**
Related to:

- #79506

## Proposed Changes

So, after a long investigation, the bug was accidentally caused by this PR:

- #72418

What's happening? Basically, this piece of code from the above PR:

https://github.com/Automattic/wp-calypso/blob/f5c3046bc476215eb27c63d52b16274d0d494ef7/client/my-sites/site-settings/reading-newsletter-settings/index.tsx#L42-L46

happens at the same with:

https://github.com/Automattic/wp-calypso/blob/f5c3046bc476215eb27c63d52b16274d0d494ef7/client/my-sites/site-settings/wrap-settings-form.jsx#L52-L57

which happens when the site options are updated (after a theme switch).

React sees two state updates and batch them in one render. Unfortunately, the current implementation of `updateFields()` sets the state without considering the previous state (`prevState`) correctly. Therefore, sometimes (or consistently, depending on React's internal implementation), one of the old state from the two state updates will still remain.

This PR fixes this, by using the correct `this.setState()` overload, which takes the `prevState` into account.

## Testing Instructions

See:

- #79506

Verify that now the Reading Setting values are correct.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by okmttdhr — APPROVED** [review]
Tested and worked well ✅ 

I have previously seen the issue https://github.com/Automattic/wp-calypso/issues/79506, but I did not look into the depth as it looked complicated at that time. I think this is a very good sign, as we can make this kind of rabbit hole explainable by revamping the theme-switch UX. Thank you! 🌮

**Review by taipeicoder — APPROVED** [review]
Tested with a new site and couldn't reproduce the issue, nicely done 🎉

File: client/lib/track-form/index.jsx [hunk 1]
```diff
@@ -11,16 +11,17 @@ export const trackForm = ( WrappedComponent ) =>
...
-				dirtyFields: [ ...new Set( [].concat( this.state.dirtyFields, Object.keys( fields ) ) ) ],
-				fields: {
-					...this.state.fields,
-					...fields,
-				},
-			};
-			debug( 'updateFields', { fields, newState } );
-
-			this.setState( newState, callback );
+			this.setState( ( prevState ) => {
```
Comment (arthur791004) [inline client/lib/track-form/index.jsx:14]: Do we need to make the same change in `replaceFields` to avoid potential issues?

**Review by arthur791004 — APPROVED** [review]
Nice findings 👍

File: client/lib/track-form/index.jsx (hunk 1 above)
Comment (fushar) [reply client/lib/track-form/index.jsx:14]: Alright, I'm fixing this once and for all 😄 Pushed!

@arthur791004, ~since you brought this up~, could you help retest this PR again after the last commit?

**Comment by okmttdhr** [comment]
badge

_I don't think it is part of this PR_, but I thought it'd be good, when values are being fetched, to make the `<select id="homepage-page-select"/>` of Reading Settings disabled or change the UI to indicate that it is being fetched. That might mitigate the confusion caused by the momentary display of default values.

**Comment by fushar** [comment]
> I thought it'd be good, when values are being fetched, to make the select id="homepage-page-select"/>of Reading Settings disabled or change the UI to indicate that it is being fetched.

I agree! It has been bothering me as well during testing 😂 let's fix this in a follow-up PR.
