### PR TITLE
Plans Subheader: fix subheader for tailored flows to respect the 'hideFreePlan' value

### LINKED ISSUE #67330: Keep free plan visible when the user clicks "Decide later" in domains page.

### PR DESCRIPTION
**Pull request by heavyweight**
#### Proposed Changes

* For tailored flow the subheader text was not respecting the value of 'hideFreePlan' and this PR fixes that.

#### Testing Instructions
- Checkout this branch
- Run `yarn start`
- Test on the [newsletter flow](http://calypso.localhost:3000/setup?flow=newsletter)
- And also test on the [link in bio flow](http://calypso.localhost:3000/setup?flow=link-in-bio)
- When clicking on "Decide Later" or selecting the free wordpress domain in the domains page you should see subheader with a link Screenshot 2022-09-02 at 18 08 17
- When selecting a paid domain it should NOT show a link to start with a free plan Screenshot 2022-09-02 at 18 37 50

Related to #67330

### CODE REVIEW

File: client/signup/steps/domains/index.jsx [hunk 1]
```diff
@@ -622,7 +622,7 @@ class DomainsStep extends Component {
 					<span
 						role="button"
 						class="tailored-flow-subtitle__cta-text"
-						onClick={ this.handleDomainExplainerClick }
+						onClick={ this.handleSkip }
```
Comment (alshakero) [inline client/signup/steps/domains/index.jsx]: Oh man.. This reminded me of a bug we introduced in [May last year](https://github.com/Automattic/wp-calypso/pull/52560). This would break checkout because it adds a faulty item to the cart.

`handleSkip` first param shouldn't be an object.

```suggestion
						onClick={ () => this.handleSkip() }
```

**Review by alshakero — CHANGES_REQUESTED** [review]
Other the issue I meantioned, this is good to go.

File: client/lib/signup/step-actions/index.js [hunk 2]
```diff
@@ -130,7 +130,7 @@ function getNewSiteParams( {
 
 	const forceAutoGeneratedBlogName = signupDependencies?.forceAutoGeneratedBlogName;
 	const shouldHideFreePlan = get( signupDependencies, 'shouldHideFreePlan', false );
-	const useAutoGeneratedBlogName = shouldHideFreePlan || forceAutoGeneratedBlogName;
+	const useAutoGeneratedBlogName = ! siteTitle || shouldHideFreePlan || forceAutoGeneratedBlogName;
```
Comment (heavyweight) [inline client/lib/signup/step-actions/index.js:133]: @alshakero now with skipping the domains step, we have `shouldHideFreePlan` false here.
I added a check for `siteTitle` to handle this new scenario. Skipping the domain selection much have autogenerated blog name since this is required by the backend

**Review by alshakero — APPROVED** [review]
Tested carefully against tailored and non-tailored flows.

**Review by escapemanuele — APPROVED** [review]
Tested and it works great! Great catch with the `siteTitle` check 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7513540

Thank you @heavyweight for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7513540).
