### PR TITLE
Marketplace: infinite scroll fixes

### LINKED ISSUE #63315: Marketplace: Infinite requests on `dotorg` when filter plugin by author
When filtering plugins by author, sometimes enter in a loop requesting pages to `dotorg` infinitely.
I found the problem does not affect all authors, and I selected some authors to make tests.

##### Affected by the issue 
`mailpoet`, `wpforms`, `yaniiliev`, `elemntor`

##### Not affected by the issue
`google`, `azaozz`, `yoast`, `takayukister`

#### Steps to reproduce

1. On your browser, open the `developer tools` and go to the Network tab.
2. Go to `/plugins/:site?s=developer:"mailpoet"` (replace :`site` with your site).
3. You will see infinite requests to `https://api.wordpress.org/plugins/info/1.2/?action=query_plugins`

### LINKED ISSUE #63532: Marketplace: Enable infinite scrolling on search results
- Infinite scroll is currently disabled
- When trying to enable it I noticed:
- ^ Mobile view searches sometimes fail to execute
- ^ Scrolling past the infinite scroll component into the footer prevents infinite scroll loads form executing.

- [ ] Enable infinite scroll
- [ ] Ensure it's not buggy

May also want to disable the footer in the same PR: see https://github.com/Automattic/wp-calypso/issues/63938

### PR DESCRIPTION
**Pull request by lsl**
#### Changes proposed in this Pull Request

* Enables infinite scroll search results - suspect missed during hook change

#### Testing instructions

- [x] Search results should auto load new results as you scroll down the page
- [x] Search results should auto load new results even if you scroll through the bottom of results and into the footer (we may just need to hide the footer on search result pages)
- [x] Mobile viewports and whatever timing? bug discussed below in the failing test should no longer fail under any scenarios (note, this was hard to reliably trigger, got lots of false negative runs in my testing)

Unit test in question, specifically "Search for ecommerce":
```
yarn workspace @automattic/calypso-e2e build && CALYPSO_BASE_URL="http://calypso.localhost:3000" VIEWPORT_NAME=mobile yarn jest specs/plugins/plugins__search.ts
```

Fixes https://github.com/Automattic/wp-calypso/issues/63532 https://github.com/Automattic/wp-calypso/issues/63938

### CODE REVIEW

**Comment by lsl** [comment]
That e2e test failure is real, repro'd on mobile view. Desktop doesn't seem to have the same issue but because all results get cached its hard to debug.

File: client/my-sites/plugins/use-plugins/index.ts [hunk 1]
```diff
@@ -149,12 +150,25 @@ const usePlugins = ( {
 			break;
 	}
 
+	function fetchNextPageAndStop() {
```
Comment (Rolilink) [inline client/my-sites/plugins/use-plugins/index.ts:159]: nitpick, I think this one should be called `fetchNextPageOrStop`

**Comment by Rolilink** [comment]
LGTM, only needs to fix the test to merge this one

**Review by Rolilink — APPROVED** [review]

File: client/my-sites/plugins/use-plugins/index.ts (hunk 1 above)
Comment (lsl) [reply client/my-sites/plugins/use-plugins/index.ts:159]: I went with and because its called in a recursive loop :smile:

**Comment by lsl** [comment]
This is working for me now, had to clear IndexDB, I wonder if the e2e test is caching that somehow?

**Comment by Rolilink** [comment]
> This is working for me now, had to clear IndexDB, I wonder if the e2e test is caching that somehow?

This could make sense!

**Comment by lsl** [comment]
> This could make sense!

Confirmed no caching in between runs in CI. p1652286034668769/1652245268.934369-slack-C1A1EKDGQ

Current thinking is that there is two/three? things in play:

- Something up with InfiniteScroll component and the way it flips its fetcher on / off depending on visibility.
- I don't think the infinite query thing that infinite scroll is leveraging fires off the first request
- Something else - even with the current fix, I'm still sometimes seeing test failures, or a test passes but then while the window is open, you click on e.g. seo and then that one fails.

**Comment by Rolilink** [comment]
> Something up with InfiniteScroll component and the way it flips its fetcher on / off depending on visibility.

This doesn't seem to be the case, it will always fetch the next page when it reaches the anchor point being the div returned by `<InfiniteScroll>`.

> I don't think the infinite query thing that infinite scroll is leveraging fires off the first request

[The first request (and multiple ones) is actually fired ](https://github.com/Automattic/wp-calypso/blob/trunk/client/components/infinite-scroll/index.js#L44-L52)by the `<InfiniteScroll>`, it seems like it tries to push multiple pages until the anchor point is outside of the screen.

> Something else - even with the current fix, I'm still sometimes seeing test failures, or a test passes but then while the window is open, you click on e.g. seo and then that one fails.

Haven't been able to confirm this one but could be some flakiness on the http call? tried to debug and was able to constantly reproduce it for a couple of times, but then I started to get test passing consistently.

**Comment by Rolilink** [comment]
> Search results should auto load new results as you scroll down the page
 Search results should auto load new results even if you scroll through the bottom of results and into the footer (we may just need to hide the footer on search result pages)

This ones are fixed by removing the footer.

File: client/data/marketplace/utils.ts [hunk 2]
```diff
@@ -11,14 +11,10 @@ export const getPluginsListKey = (
...
-		keyParams.push( 'infinite' );
-	} else {
-		keyParams.push( options.page || '' );
-	}
-	if ( options.tag && ! options.searchTerm ) {
-		keyParams.push( options.tag );
-	}
+
 	return [ key, ...keyParams ];
 };
```
Comment (lsl) [inline client/data/marketplace/utils.ts:20]: @gcsecsey are you ok with the changes in here? I'm ensuring options always reside in the same key position by no longer making things optionally pushed. It wasn't actually required for this PR but was something I was debugging and felt it was worth making more specific. Do you agree? (Feel free to say no, I'm not particularly confident here)

There is a subtle difference in that page and infinite are always included regardless. I couldn't really test this because we don't have anything that sends page values. 

This might highlight:

```
	if ( infinite ) {
		keyParams.push( 'infinite' );
	}
	if ( options.page ) {
		keyParams.push( options.page );
	}

```

File: client/my-sites/plugins/use-plugins/index.ts [hunk 3]
```diff
@@ -96,7 +96,7 @@ const usePlugins = ( {
 		isLoading: isFetchingWPORGInfinite,
 		fetchNextPage,
 	} = searchHook( wporgPluginsOptions, {
-		enabled: infinite && WPORG_CATEGORIES_BLOCKLIST.includes( category || '' ) && wporgEnabled,
+		enabled: infinite && ! WPORG_CATEGORIES_BLOCKLIST.includes( category || '' ) && wporgEnabled,
```
Comment (lsl) [inline client/my-sites/plugins/use-plugins/index.ts]: @Rolilink this was the "first load problem" and what fixed the flaky e2e test. Replaces the need for this commit [`71d959e` (#63438)](https://github.com/Automattic/wp-calypso/pull/63438/commits/71d959e2e38cd9c3bdaa18e679b97deb28123577)

Not sure how it fixed the flaky test :confused: Timing issue? It does load the discover page just prior, maybe cache key related?

**Comment by lsl** [comment]
@Rolilink will merge tomorrow but could use a fresh review, also curious about what @gcsecsey says relating to the new search mode behind config flag in case I've broken something with this.

File: client/data/marketplace/utils.ts (hunk 2 above)
Comment (gcsecsey) [reply client/data/marketplace/utils.ts:20]: I agree it's worth making it more specific. Based on [how query keys work](https://tkdodo.eu/blog/effective-react-query-keys), the main point with this function is to produce the same array for the same set of parameters.

I think the `page` param is a leftover from before we've added the [InfiniteQuery hook](https://github.com/Automattic/wp-calypso/pull/62519/files#diff-4aa4ee82e625627654fb119928b8c515c079207f6273d88cb27bbf02d1fc3feeR80). AFAIK we don't use paginated queries anywhere else anymore, as InfiniteQuery handles the `pageParam` in its callback.

I've searched around a bit, and it seems that these can now be removed, along with [their stores](https://github.com/Automattic/wp-calypso/blob/trunk/client/state/plugins/wporg/actions.js#L29). AFAIK these aren't used since the react-query implementation. What do you think?

**Review by gcsecsey — APPROVED** [review]
Works great, changes LGTM 🎉

File: client/my-sites/plugins/use-plugins/index.ts (hunk 3 above)
Comment (Rolilink) [reply client/my-sites/plugins/use-plugins/index.ts]: My guess here will be the query was always disabled and not triggering the first fetch but calling `nextPage` was actually doing the fetching. Gonna give it some more rounds of test running and merge it

Comment (Rolilink) [reply client/my-sites/plugins/use-plugins/index.ts]: > It does load the discover page just prior

On the test? that should be normal the test first visits the discovery page and does the search from there

**Review by Rolilink — APPROVED** [review]

File: client/data/marketplace/utils.ts (hunk 2 above)
Comment (Rolilink) [reply client/data/marketplace/utils.ts:20]: @gcsecsey can we add a ticket to do a cleanup on plugins state?

**Comment by Rolilink** [comment]
Last commit is just me being picky, practically what @lsl did solves the issue, I did some testing and @lsl instinct was correct. What is happening is that the first call is not triggered, but `<InfiniteScroll>` is calling `fetchNextPage` and triggering the first call. Sometimes in the test `fetchNextPage` is not called and there is no result to check with.

I added a check on `fetchNextPageAndStop` so if the hook isn't receiving `infinite: true` it doesn't execute and a check to enable the infinite when we get a valid search term  or a valid category.

File: client/data/marketplace/utils.ts (hunk 2 above)
Comment (lsl) [reply client/data/marketplace/utils.ts:20]: I'd like to leave pagination around for a bit. Eventually we're going to want to show plugins in a logged out view. I'm wondering if we might opt for pagination on that view for seo purposes.

**Comment by lsl** [comment]
Sounds good @Rolilink :+1:
