### PR TITLE
Fix: Send Invitation button needs to be clicked twice when not focused

### LINKED ISSUE #78886: "Send invitiation" needs to be clicked two times when not focused
### Quick summary

When I invite a new user to my site and provide a user's email or username, I need to click "Send invitation" twice: first to focus it, and second to submit. 

### Steps to reproduce

1. Navigate to Users -> Add New
2. Fill in the username
3. Click the "Send invitation" button
4. Notice that nothing happens
5. Click the button again to submit
6. Confirm that form was submitted

### What you expected to happen

I expected the button submits a form with a single click.

### What actually happened

I need to click two times to submit the form.

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by katinthehatsite**
Closes: https://github.com/Automattic/wp-calypso/issues/78886

## Proposed Changes

This PR fixes the need for the `Send Invitation` button to be clicked twice when it is not focused on `Users -> Add New` tab. 

## Testing Instructions

* Navigate to `Users -> Add New` 
* Type a valid username or email in the field
* Click on `Send Invitation` 
* Confirm that the invitation gets sent on the first click

**Testing invalid username**

* Navigate to `Users -> Add New` 
* Type an invalid username or email (you can use `katerynakodonenk` which is invalid)
* Confirm that you see the error that the user is not found
* Confirm that you can't send an invitation

**Notes**

* The issue with the button needed to be clicked twice is caused by `onTokenBlur` function that would only started the validation of tokens when the user clicks outside of the input field. This would work okay if we had another field that was mandatory and that would make the user click out. Since this is not the case, it requires the user to click somewhere first before the validation can start and the button is working
* We moved with @kozer , the validation of tokens to `onChange` instead and used `useDebouncedCallback` to prevent validation requests to the API on every keystroke
## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by kozer** [comment]
@katinthehatsite For me is okay ( we have already had many discussions while we were pairing together on this one ).
We already use a similar approach on the Login form so it should be fine.

I'll approve myself, but I want to take some feedback from the rest of the team as well.

In the meantime, it would be good if we could add some tests on that. It is a complex component, and I believe that we are going to benefit from testing.

However, because this could be a long task, based on the actions that user can take, it is fine if we create a separate ticket for that, and tackle it separately.

**Review by kozer — APPROVED** [review]

File: client/my-sites/people/team-invite/invite-form.tsx [hunk 1]
```diff
@@ -63,45 +64,60 @@ function InviteForm( props: Props ) {
...
 	}, [ invitingProgress ] );
 	useValidationNotifications();
 	useInvitingNotifications( tokenValues );
 
-	function onFormSubmit( e: FormEvent ) {
-		e.preventDefault();
-		if ( ! readyForSubmit || invitingProgress ) {
-			return;
-		}
+	const onFormSubmit = useCallback(
```
Comment (sejas) [inline client/my-sites/people/team-invite/invite-form.tsx]: Is there any specific reason to add a `useCallback`  here?

I noticed that `onTokenChange` or `reactOnInvitationSuccess` are not wrapped with `useCallback`.

If it's not strictly necessary to fix this issue I would remove the `useCallback` for `onFormSubmit`, to avoid changing lines that are not fixing the bug.

**Review by sejas — APPROVED** [review]
@katinthehatsite , great work!

I tested it and it works as described. Now we the user can send the invitation with just one click instead of two.

I noticed that with the current debounce time sometimes the not found error appears after the form is submitted, but I think it works well to avoid showing the user the error while typing.

I added a small comment, but feel free to change it or not. Just a curious question.

Another alternative solution to avoid using the debounce function, would be validating the emails when the user clicks on the submit button and before sending the invitations.
Probably your solution is closer to the current implementation, though.

File: client/my-sites/people/team-invite/invite-form.tsx (hunk 1 above)
Comment (katinthehatsite) [reply client/my-sites/people/team-invite/invite-form.tsx]: Thanks for the review @sejas - I don't think it is strictly necessary. If I remember correctly, we added it to ensure that it renders only when dependencies update but it works without it as well. I removed it as per your suggestion.

As for the error being shown after the button is clicked, it is somewhat unavoidable because we start validation 3s after the user starts typing so it finishes with the delay. I decreased the time in `useDebouncedCallback` to a bit shorter to make this less visible but it is still going to be there. Otherwise, if we remove it completely, we will be sending API requests on every keystroke.
