### PR TITLE
Replace children propType element with node

### LINKED ISSUE #19578: DialogBase: React warning in dev
I noticed this on master starting today:

developer_tools_-_http___calypso_localhost_3000__and_index_js____projects_wp-calypso_client_extensions_woocommerce_lib_analytics__-_vim1

It comes up every page load, regardless of URL.

#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/
2. Open browser dev console, view warning.

#### What I expected
No dev console errors/warnings.

#### What happened instead
`Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `DialogBase`, expected a single ReactElement`

#### Browser / OS version
OSX Chrome Version 62.0.3202.75 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by sirreal**
This PR fixes an apparently inaccurate propType causing warnings to display in the console.

`PropTypes.element` is used to specifically require a _single_ element child.
Children normally does not have this restriction and `PropTypes.node` is more
appropriate.

This rule was introduced in #19204

Fixes #19578

### CODE REVIEW

**Comment by jsnajdr** [comment]
This is a great PR, thanks! 👍 

The incorrect prop type for children appears at a handful of other places:
```js
// this should really be PropTypes.node (meaning: anything renderable):
children: PropTypes.element
// this should also be PropTypes.node
children: PropTypes.arrayOf( PropTypes.element )
// redundant: just 'PropTypes.node' is enough. It detects arrays of nodes
// and any other renderable stuff
children: PropTypes.oneOfType( [ PropTypes.arrayOf( PropTypes.node ), PropTypes.node ] )
```

How do you feel about fixing them all in one PR?

**Comment by sirreal** [comment]
> How do you feel about fixing them all in one PR?

I'll have a look.

The following could be valid if you _really_ do want just 1 element:

```js
children: PropTypes.element
```

The others cases do look like the just missed the mark 🙂

**Comment by jsnajdr** [comment]
> The following could be valid if you really do want just 1 element:

If that's really the component author's intent, they should use [React.Children.only](https://reactjs.org/docs/react-api.html#reactchildrenonly) -- that enforces the constraint much more strongly, as it throws a runtime exception rather that just logging a warning.

**Comment by sirreal** [comment]
@jsnajdr Do you think there's any value in this `propType` if it's just `node`? I'm considering just removing if the intent is `children: PropTypes.node`

**Comment by jsnajdr** [comment]
> Do you think there's any value in this propType if it's just node?

That's a very good point! I played with React 16 for a while and figured out that it already gives you plenty of warnings and errors if you pass something suspicious as `children`:
```jsx
// Warning: Functions are not valid as a React child.
<div>{ () => null }</div>
// Uncaught Error: Objects are not valid as a React child
<div>{ { silly: 'object' } }</div>
```

So my conclusion is that checking `children` with `PropTypes.node` is redundant. There are components that require something special in `children`, like a function. These should check for `PropTypes.func`. But in the default case, there's no need.

**Comment by spen** [comment]
Thanks for submitting a fix to this so quickly @sirreal :)

> PropTypes.element is used to specifically require a single element child.

Eek, I wasn't aware of this!

Given the above, I'd agree that there's not much value in the `propType` in this case :)

**Comment by sirreal** [comment]
I added a significant amount of cleanup around `propTypes.children`. I tried to be conservative and only remove this propType if it seemed to be incorrect or add little value like the case of `PropTypes.node`.

Please review

File: client/extensions/woocommerce/components/action-header/index.js [hunk 1]
```diff
@@ -50,7 +50,6 @@ const ActionHeader = ( { children, breadcrumbs, isLoading } ) => {
 
 ActionHeader.propTypes = {
 	breadcrumbs: PropTypes.oneOfType( [ PropTypes.arrayOf( PropTypes.node ), PropTypes.node ] ),
```
Comment (jsnajdr) [inline client/extensions/woocommerce/components/action-header/index.js]: This `breadcrumbs` prop could also be simplified to `PropTypes.node`.

Comment (sirreal) [reply client/extensions/woocommerce/components/action-header/index.js]: 👍  nabbed it in 10e274e8dd0893ab43c4cade4b4e1fad35fc8fd3
