### PR TITLE
E2E: validate selected free domain

### LINKED ISSUE #67549: Add E2E for preselected free domain
The [PR](https://github.com/Automattic/wp-calypso/pull/67332) created an incident where the preselected free domain for a customer was not respected.

We need to add E2E coverage for this scenario, to prevent this regression from happening.

### PR DESCRIPTION
**Pull request by heavyweight**
#### Proposed Changes

* Recent changes required for tailored signup flows [caused an issue](p58i-d6T-p2) where the value of the preselected free `.wordpress.com` domain was not respected. A site with different domain was created at the end of the signup.
* This PR modifies existing tests to verify the created site, so that this issue is prevented in the future.

#### Testing Instructions
- Checkout this branch
- Run `yarn start`
- Run the e2e tests. Follow the [e2e instructions if needed](https://github.com/Automattic/wp-calypso/tree/trunk/test/e2e)
- Or run the changed tests one by one:
```
yarn jest specs/onboarding/ftme__write
yarn jest specs/plans/plans__signup-free
```

Related to #67549

### CODE REVIEW

**Review by escapemanuele — APPROVED** [review]
Works really well for me, thanks for adding this! 👍

File: test/e2e/specs/onboarding/ftme__write.ts [hunk 1]
```diff
@@ -41,7 +42,7 @@ describe( DataHelper.createSuiteTitle( 'FTME: Write' ), function () {
 		it( 'Select a .wordpress.com domain name', async function () {
 			const domainSearchComponent = new DomainSearchComponent( page );
 			await domainSearchComponent.search( blogName );
-			await domainSearchComponent.selectDomain( '.wordpress.com' );
+			selectedFreeDomain = await domainSearchComponent.selectDomain( '.wordpress.com' );
```
Comment (worldomonation) [inline test/e2e/specs/onboarding/ftme__write.ts:45]: **comment**: I had totally forgotten that I implemented a return value for `domainSearchComponent.selectDomain`. Good use!

**Review by worldomonation — APPROVED** [review]
Triggered Pre-Release Tests against the calypso.live branch to double-check the changes and all tests passed.

image
