### PR TITLE
Focused Launch: Debounce domain search for focused launch on key press

### LINKED ISSUE #48107: Focused Launch: Search for domains on key press rather than on blur
#### Steps to reproduce

1. Visit `/page/SANDBOXED_UNLAUNCHED_SITE_ID_CREATED_WITH_START.wordpress.com/home?flags=create/focused-launch-flow-calypso`. Focused Launch modal should appear
2. Enter site title
3. Observe no new domains being returned until you click outside of the site title input.

#### What I expected

* New domains to be returned on key press rather than on blur (clicking outside of the input)

#### What happened instead

* I had to click outside of the site title input before any new domain suggestions were fetched.

#### Context / Source

p58i-9Mt-p2#comment-48400

### PR DESCRIPTION
**Pull request by tjcafferkey**
#### Changes proposed in this Pull Request

* Moved launch title in to the `LAUNCH_STORE`
* Search for domains `onChange` instead of `onBlur`

#### Testing instructions

Setup:
1. Checkout this branch
2. Run `yarn start` in Claypso
3. Run `yarn dev --sync` in `apps/editing-toolkit`
4. Sandbox an unlaunched site created via `/start` (for Focused Launch testing)
5. Sandbox an unlaunched site created via `/new` (for Launch testing)

**Focused Launch**
1. Go to `/page/UNLAUNCHED_SITE_ID_CREATED_WITH_START.wordpress.com/home?flags=create/focused-launch-flow`
2. Click on "Launch" to open the Focused Launch modal
3. In the "Name your site" step enter a search term and observe the domain suggestions update as you type.

**Launch - Regression testing**
1. Go to `/page/UNLAUNCHED_SITE_ID_CREATED_WITH_NEW.wordpress.com/home`
2. Click "Launch" to open the launch modal
3. Test that the Step-by-step Launch modal works as normally expected.

Fixes https://github.com/Automattic/wp-calypso/issues/48107

### CODE REVIEW

**Comment by ciampo** [comment]
Code changes LGTM — this well written PR description made it very easy to understand the scope of the changes.

Since the changes are a bit old, I'll wait for a rebase and then I'll test changes according to the instructions

File: apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/name-step/index.tsx [hunk 1]
```diff
@@ -14,10 +14,9 @@ import { useTitle } from '@automattic/launch';
 import './styles.scss';
 
 const NameStep: React.FunctionComponent< LaunchStepProps > = ( { onPrevStep, onNextStep } ) => {
-	const { title, updateTitle, saveTitle } = useTitle();
+	const { title, updateTitle } = useTitle();
 
 	const handleNext = () => {
-		saveTitle();
```
Comment (ciampo) [inline apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/name-step/index.tsx:20]: In the very remote case that the user types a title and then clicks the "next" button before 1s debounce ticks, would the debounced function still execute, and the title still be saved?

File: apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/name-step/index.tsx [hunk 2]
```diff
@@ -42,7 +41,6 @@ const NameStep: React.FunctionComponent< LaunchStepProps > = ( { onPrevStep, onN
 						id="nux-launch-step__input"
 						className="nux-launch-step__input"
 						onChange={ updateTitle }
-						onBlur={ saveTitle }
 						value={ title }
```
Comment (ciampo) [inline apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/name-step/index.tsx]: With the changes in the `useTitle()` hook, I can now see a TypeScript error related to the fact that the `title` variable can now be `undefined`

In Focused Launch, this issue was solved by passing `title || ''` instead (see https://github.com/Automattic/wp-calypso/blob/cba6c935b5ad4736a52c74712996ddba7a66cb82/packages/launch/src/focused-launch/summary/index.tsx#L537)

**Review by ciampo — CHANGES_REQUESTED** [review]
Changes test well, although I added a couple of small comments that need to be addressed before merging

File: apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/name-step/index.tsx (hunk 2 above)
Comment (tjcafferkey) [reply apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/name-step/index.tsx]: Good spot. Fixed.

File: apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/name-step/index.tsx (hunk 1 above)
Comment (ciampo) [reply apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/name-step/index.tsx:20]: After testing, we can confirm that the debounced function still executes even if the user presses the Next button

**Review by ciampo — APPROVED** [review]
LGTM 🚢
