### PR TITLE
Sensei setup: Focus on input field on load, show error message

### LINKED ISSUE #84118: Error state when clicking continue in senseiSetup without Site name
### Quick summary

On the [setup step of the Sensei flow](https://wordpress.com/setup/sensei/senseiSetup), it's not obvious what the user needs to do to move to the next step.

### Steps to reproduce

1. Go to https://wordpress.com/setup/sensei/senseiSetup.
2. The cursor is not in the _Site name_ field and it's not obvious why the _Continue_ button is disabled.

### What you expected to happen

The _Continue_ button to be enabled, _Site name_ to be highlighted with the cursor in the field, and an error message to be displayed when the button is clicked and _Site name_ is empty. We can use an error message and UI similar to the [Newsletter flow](https://wordpress.com/setup/newsletter/newsletterSetup). The error message should be "Oops. Looks like your course site doesn't have a name yet."

Screenshot 2023-11-10 at 2 48 56 PM

### What actually happened

It's unclear what needs to be done to enable the _Continue_ button.

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by Imran92**
Related to https://github.com/Automattic/wp-calypso/issues/84118

## Proposed Changes

* Added an error message below Site Title
* Made the Continue button in the bottom Active by default (before it was deactivated)
* Site title is focused on site load
* if Site Title is < 3 characters long and user clicks on Continue, cursor is moved to site title and error message is shown
* When the user starts typing again, error message is removed

## Testing Instructions

* Go to http://calypso.localhost:3000/setup/sensei/senseiSetup
* Check that the site title input is focused, cursor is blinking on site title
* Make sure no error message is there by default
* Click on the Continue button without typing anything in the site title field
* Make sure you see an error message below site title
* Make sure you are automatically focused on site title
* Start typing something
* Check that the error message is removed
* Remove whatever you typed
* Click on Continue button
* The message should appear again
* Now write a site title
* Click on Continue
* It should take you to the next page
* Check the whole flow on other screen size as well

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by donnapep** [comment]
Just a friendly reminder to ensure that all the merge tasks pass before asking for a review. Do you have a TeamCity account? Here's what the failure is showing:

Screenshot 2023-11-15 at 3 52 52 PM

**Comment by Imran92** [comment]
> Just a friendly reminder to ensure that all the merge tasks pass before asking for a review. Do you have a TeamCity account? Here's what the failure is showing:
> 
> Screenshot 2023-11-15 at 3 52 52 PM

Thanks @donnapep , I've fixed it here https://github.com/Automattic/wp-calypso/pull/84168/commits/e011966c0399e634e03b4c4bbcc92f8cab745715. I don't have a teamcity account, but checked as a Guest

File: client/landing/stepper/declarative-flow/internals/steps-repository/sensei-setup/index.tsx [hunk 1]
```diff
@@ -77,7 +79,23 @@ const SenseiSetup: Step = ( { navigation } ) => {
...
 	}, [ dispatch ] );
 
+	const focusOnSiteTitleInput = () => {
+		// Focus on the input when the step is mounted.
+		if ( inputRef.current ) {
+			inputRef.current.focus();
+		}
+	};
+
+	const isValidSiteTitle = () => siteTitle && siteTitle.length > 2;
```
Comment (renatho) [inline client/landing/stepper/declarative-flow/internals/steps-repository/sensei-setup/index.tsx]: I'm not sure why `handleSubmit` uses the `useCallback`.
If we can't remove it, we should also use the `useCallback` in this function and send it as a dependency to the `handleSubmit`.

**Review by renatho — COMMENTED** [review]
Looks good and works well!
I just added a small suggestion to follow the `react-hooks/exhaustive-deps` lint rule and avoid weird issues with the states. 😉

File: client/landing/stepper/declarative-flow/internals/steps-repository/sensei-setup/index.tsx (hunk 1 above)
Comment (Imran92) [reply client/landing/stepper/declarative-flow/internals/steps-repository/sensei-setup/index.tsx]: > I'm not sure why handleSubmit uses the useCallback.

I'm not sure either. But wasn't sure either about removing it. I've updated my function with useCallback and passed it as a dependency here https://github.com/Automattic/wp-calypso/pull/84168/commits/f82f64e8a690a2bf5401ff434f75906b61479cc7

Comment (renatho) [reply client/landing/stepper/declarative-flow/internals/steps-repository/sensei-setup/index.tsx]: Thank you! Looks good and works well!

File: client/landing/stepper/declarative-flow/internals/steps-repository/sensei-setup/index.tsx [hunk 2]
```diff
@@ -77,18 +79,38 @@ const SenseiSetup: Step = ( { navigation } ) => {
...
 	}, [ dispatch ] );
 
+	const focusOnSiteTitleInput = () => {
+		// Focus on the input when the step is mounted.
+		if ( inputRef.current ) {
+			inputRef.current.focus();
+		}
+	};
+
+	const isValidSiteTitle = useCallback( () => siteTitle && siteTitle.length > 2, [ siteTitle ] );
```
Comment (renatho) [inline client/landing/stepper/declarative-flow/internals/steps-repository/sensei-setup/index.tsx]: I think it should be this to match the previous behavior, right? Or did we change it on purpose?

```suggestion
	const isValidSiteTitle = useCallback( () => siteTitle && siteTitle.length >= 2, [ siteTitle ] );
```

File: client/landing/stepper/declarative-flow/internals/steps-repository/sensei-setup/index.tsx [hunk 3]
```diff
@@ -99,11 +121,19 @@ const SenseiSetup: Step = ( { navigation } ) => {
...
 							setSiteTitle( ev.target.value );
 						} }
 						placeholder={ __( 'Photography Class' ) }
 						value={ siteTitle }
+						ref={ inputRef }
 					/>
+					{ hasSubmitted && ! isValidSiteTitle() && (
+						<FormInputValidation
+							isError={ true }
+							text={ __( `Oops. Looks like your course site doesn't have a name yet.` ) }
```
Comment (renatho) [inline client/landing/stepper/declarative-flow/internals/steps-repository/sensei-setup/index.tsx:132]: I think we need to tweak a bit this message, because it's a little weird when we have 1 character.
We probably should make explicit in the message that it needs to have a minimum of 2 characters.

With a help from GPT:

```suggestion
							text={ __( `Oops. Looks like your site doesn't have a name yet. It requires a minimum of 2 characters.` ) }
```

**Review by renatho — COMMENTED** [review]
Sorry! Just more these small things I realized in the final review.

File: client/landing/stepper/declarative-flow/internals/steps-repository/sensei-setup/index.tsx (hunk 3 above)
Comment (donnapep) [inline client/landing/stepper/declarative-flow/internals/steps-repository/sensei-setup/index.tsx:132]: Hmm...I'm not a big fan of the changes to this message. I added the original check based on [an issue Giannis reported](https://github.com/Automattic/wp-calypso/pull/77979#pullrequestreview-1474448044), but that I was never able to reproduce. Maybe we could try taking out the site title 2 character restriction and test to see if the flow still works well?

Comment (Imran92) [reply client/landing/stepper/declarative-flow/internals/steps-repository/sensei-setup/index.tsx:132]: Your message looks good to me too, but it was the one suggested in the issue. So I think we need to ask first

Comment (Imran92) [reply client/landing/stepper/declarative-flow/internals/steps-repository/sensei-setup/index.tsx:132]: Makes sense, I'm checking without the restriction now

Comment (Imran92) [reply client/landing/stepper/declarative-flow/internals/steps-repository/sensei-setup/index.tsx:132]: Looks like domain search only with 2 or more characters. If we have less than that, the site title in the searchbox becomes empty, so no search results either.

Domain search page after logging in when the site title had only 1 character

image

Should we change the text to mention about 2 character restriction?

Comment (donnapep) [reply client/landing/stepper/declarative-flow/internals/steps-repository/sensei-setup/index.tsx:132]: Looking at all the other flows that expect a site name, none of them seem to have a 2 character minimum restriction. The domains page isn't broken or anything; it just requires more characters in order to do a search. Given this, I think I'd probably lean slightly on the side of doing what the other flows are already doing. WDYT?

Comment (Imran92) [reply client/landing/stepper/declarative-flow/internals/steps-repository/sensei-setup/index.tsx:132]: Makes sense to me, we can follow the behavior we have elsewhere here. Also, I think it's a very edge case that a user might try a single character as sitename, unless they're deliberately trying to test. I've removed the constraint here https://github.com/Automattic/wp-calypso/pull/84168/commits/fdd84e96a534533cfbd704d5a08e9ce1d27c26de

**Review by renatho — APPROVED** [review]
Looks good and works well! 🎉
