### PR TITLE
Display notice when a plugin is active without a subscription

### LINKED ISSUE #69973: Marketplace: Yoast SEO Premium shows as inactive if purchased directly from Yoast
### Quick summary

If Yoast SEO Premium is purchased from Yoast directly, then it will show as **Inactive** on the Plugin Marketplace. 

Screenshot 2022-11-13 at 1 06 51 pm

### Steps to reproduce

1. Download Yoast SEO Premium directly from their site: https://yoast.com/wordpress/plugins/seo/
2. Install it on AT WordPress.com site.
3. Search for `yoast` in Marketplace.
4. It will display as **Installed** but **Inactive**.

### What you expected to happen

Expected **Yoast SEO Premium** to show as **Active**.

### What actually happened

**Yoast SEO Premium** shows as **Inactive**.

### Context

5706530-zd-woothemes

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

_No response_

### Browser, operating system and other notes

_No response_

### Reproducibility

_No response_

### Severity

_No response_

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by JulianBustamante**
Related to #69973

## Proposed Changes

- active / inactive status displayed on the plugin browser item doesn't depend on having a subscription it only depends on the actual plugin status reported from the API.
- In the plugin details page, if there isn't an active subscription, a notice with the message is displayed "Plugin subscription not found or you have purchased the plugin outside of WordPress.com. Purchase a WordPress.com subscription if you want to receive updates and support"

## Testing Instructions

- Apply this patch
- Download Yoast SEO Premium directly from their site: https://yoast.com/wordpress/plugins/seo/
- Install it on AT WordPress.com site.
- Search for yoast in Marketplace /plugins.
- It will display Installed and Active.

Screenshot 2023-04-04 at 3 32 47 PM

- Go to the details page of the plugin
- A notice is displayed at the top with the message

Screenshot 2023-04-05 at 12 25 24 PM

- This notice should not be displayed in preinstalled or plugins that don't belong to the marketplace.
- Upgrade a site from a simple to an e-commerce plan and make sure the notice doesn't appear on bundled plugins for instance WooCommerce Product Add-ons.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

### CODE REVIEW

**Review by WBerredo — APPROVED** [review]
Its working as described, LGTM! 🚢

**Review by cpapazoglou — CHANGES_REQUESTED** [review]
In my testing, I have some scenarios that this code doesn't work as expected

1. Having a valid subscription, I can see a notice that I don't have a subscription

|Production | This branch|
|-------|------|
|CleanShot 2023-04-11 at 19 45 18@2x|CleanShot 2023-04-11 at 19 43 35@2x|

2. Not having a subscription, but product comes as pre-installed with ecommerce plan. Here are the plugin bundled with ecommerce plans fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Sngbzvp%2Sjbn%2Qrpbzzrepr%2Qfbsgjner.cuc%23423-og

I think that we can create a static list in Calypso for now

CleanShot 2023-04-11 at 19 49 13@2x

3. Here is a case that I should get the notice cause I don't have a subscription but I don't get one

CleanShot 2023-04-11 at 19 53 25@2x

although I correctly get it for this one

CleanShot 2023-04-11 at 19 54 35@2x

I added it you as an admin in my site to easier debug those scenarios.

File: client/my-sites/plugins/plugin-details.jsx [hunk 1]
```diff
@@ -333,6 +342,19 @@ function PluginDetails( props ) {
...
+					showDismiss={ false }
+					status="is-warning"
+					text={ translate(
+						'Plugin subscription not found or you have purchased the plugin outside of WordPress.com. Purchase a WordPress.com subscription if you want to receive updates and support.',
+						{
+							textOnly: true,
+						}
+					) }
+				></Notice>
+			) }
```
Comment (cpapazoglou) [inline client/my-sites/plugins/plugin-details.jsx]: I would suggest moving this code and the logic that renders it or not to a new component cause I think it will get more complex.

**Comment by JulianBustamante** [comment]
- Fixed the issue where having a valid subscription was displaying the notice component.
- Still missing the e-commerce preinstalled static list and moving the notice to an independent component.

**Comment by JulianBustamante** [comment]
- The logic to show the notice was moved to a component.
- Avoid displaying the notices in bundled plugins will be tackled in a follow-up ticket.

**Review by cpapazoglou — APPROVED** [review]
Changes LGTM, we should still avoid merging it before we account for plugins bundled with plans ( eg ecommerce plan with woocommerce extensions ).

**Comment by cpapazoglou** [comment]
> we should still avoid merging it before we account for plugins bundled with plans ( eg ecommerce plan with woocommerce extensions ).

@JulianBustamante is there an issue created related to plugins bundled with plans?

**Comment by JulianBustamante** [comment]
> > we should still avoid merging it before we account for plugins bundled with plans ( eg ecommerce plan with woocommerce extensions ).
> 
> @JulianBustamante is there an issue created related to plugins bundled with plans?

@cpapazoglou  I worked on the bundled plugins in this issue.

File: client/my-sites/plugins/plugin-details-notices.jsx [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+	getSitePurchases,
+	hasLoadedSitePurchasesFromServer,
+} from 'calypso/state/purchases/selectors';
+
+const PluginDetailsNotices = ( { selectedSite, plugin, translate } ) => {
+	const hasLoadedSitePurchases = useSelector( hasLoadedSitePurchasesFromServer );
+	const isFullPluginAndPurchasesFetched = hasLoadedSitePurchases && plugin?.fetched;
+	const isWpcomPreinstalled =
+		PREINSTALLED_PLUGINS.includes( plugin.slug ) || AUTOMOMANAGED_PLUGINS.includes( plugin.slug );
+	const isBundledPlugin = BUNDLED_PLUGINS_BY_PLAN[ selectedSite?.plan?.product_slug ]?.includes(
```
Comment (cpapazoglou) [inline client/my-sites/plugins/plugin-details-notices.jsx]: `ecommerce-bundle` is the product slug of `ecommerce` annual plan. The monthly one is `ecommerce-bundle-monthly`. We also have `ecommerce-bundle-2y` and might have more variations in the future. Seems like `isSiteOnEcommerce` would be a better variable to check against. https://github.com/Automattic/wp-calypso/blob/4193801455167437405e54230134c45750a7b779/client/state/sites/plans/selectors/is-site-on-ecommerce.ts#L17

CleanShot 2023-05-04 at 16 03 05@2x

Comment (JulianBustamante) [reply client/my-sites/plugins/plugin-details-notices.jsx]: I fixed the issue by using the method you suggested. Thank you, @cpapazoglou !

**Review by gcsecsey — APPROVED** [review]
Changes LGTM. I've tested with both bundled plugins and Yoast SEO, and it works as described. :shipit:

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7978454

Thank you @JulianBustamante for including a screenshot in the description! This is really helpful for our translators.

**Comment by druesome** [comment]
@JulianBustamante It seems that the issue is happening to free plugins not sold in our marketplace.  When I install any non-marketplace plugin and activate it, the message "Plugin subscription not found or you have purchased the plugin outside of WordPress.com. Purchase a WordPress.com subscription if you want to receive updates and support." still appears on top of the plugin page.

image

Can you look into this?  Thanks!

**Comment by cpapazoglou** [comment]
@druesome I have drafted a fix in https://github.com/Automattic/wp-calypso/pull/76937

**Comment by druesome** [comment]
@cpapazoglou perfect, thank you!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7978454).
