### PR TITLE
Taxonomies: Update the default category's site settings value if we rename this category

### LINKED ISSUE #9967: Taxonomy Manager: Renaming default category removes default label
Renaming the default category seems to remove it as the default category. It's fixed on refresh, but it's a bit confusing at first.

## To reproduce
1. Set a new category as the default one for your site.
2. After saving as the default category, go back and edit the name then save again.

The "default" label will be removed from the saved category until you refresh.

categories

### PR DESCRIPTION
**Pull request by youknowriad**
Nothing too fancy :) I just trigger a site settings update if the id of the default category changes while updating it.

closes #9967

**Testing instructions**

 * Rename the default category from the taxonomy manager
 * Submit the form
 * The "default" label should be visible in the category row after renaming the category

### CODE REVIEW

File: client/state/terms/actions.js [hunk 1]
```diff
@@ -84,6 +86,12 @@ export function updateTerm( siteId, taxonomy, termId, termSlug, term ) {
 					} ) );
 				} );
 
+				// Update the default category if needed
+				const siteSettings = getSiteSettings( state, siteId );
+				if ( taxonomy === 'category' && get( siteSettings, [ 'default_category' ] ) === termId && updatedTerm.ID !== termId ) {
```
Comment (timmyc) [inline client/state/terms/actions.js]: This conditional is quite long and having the `get` nested in there makes it hard to read at a glance, should we put each condition on its own line?

**Comment by timmyc** [comment]
Testing out well 🚢
