### PR TITLE
Welcome Tour: Temporary fix overlap between mobile gifs and Tour kit header controls

### LINKED ISSUE #55826: Editor Welcome: instructional graphics for mobile UI
### What

When displaying the Editor Welcome tour on mobile, we should show instructional graphics relevant to the mobile screen resolution. 

Some of the slides included in the tour are generic (eg: block, block toolbar, drag & drop) but some of them show the editor UI ( p1629901900075300/1629899413.074600-slack-C029WSAQMT9 ) and probably those would need a mobile version.

Latest update on Slack: p1630298089013600/1629899413.074600-slack-C029WSAQMT9

### Why

Our users would benefit most from guidance adapted to the screen they are using.

### A/C

- [x] GIFs with the mobile UI @donalirl 
- [ ] Final graphics with the GIFs on grey background, similar to the desktop ones @poligilad-auto 
- [ ] (dev) Implement new graphics and copy to be rendered when the Welcome Tour is displayed on mobile

### PR DESCRIPTION
**Pull request by escapemanuele**
#### Changes proposed in this Pull Request

The gifs we are using for the mobile version of the Welcome Tour overlap with the header buttons.

Screenshot 2021-12-10 at 09 56 14

We should change the gifs, and in the meantime, this is a temporary solution.

#### Testing instructions

* Checkout the branch
* yarn dev --sync for ETK
* Check that in the sandboxed site the gifs and the header controls do not overlap

Screenshot 2021-12-10 at 10 19 03

Fixes #55826
Related to #55826

### CODE REVIEW

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-card.js [hunk 1]
```diff
@@ -2,7 +2,7 @@
  * External Dependencies
  */
 import { recordTracksEvent } from '@automattic/calypso-analytics';
-import { getMediaQueryList } from '@automattic/viewport';
+import { getMediaQueryList, isMobile } from '@automattic/viewport';
```
Comment (razvanpapadopol) [inline apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-card.js]: There's a way to highlight a bit more explicitly why we need to use `isMobile` here and not other utility function from `@automattic/viewport`.
See my comment on the original PR: https://github.com/Automattic/wp-calypso/pull/56347#pullrequestreview-828842013

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-card.js [hunk 2]
```diff
@@ -155,7 +155,9 @@ function CardNavigation( {
 }
 
 function CardOverlayControls( { onMinimize, onDismiss } ) {
-	const buttonClasses = classNames( 'welcome-tour-card__overlay-controls' );
+	const buttonClasses = classNames( 'welcome-tour-card__overlay-controls', {
+		'welcome-tour-card__overlay-controls__absolute': ! isMobile(),
```
Comment (razvanpapadopol) [inline apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-card.js:159]: This should work fine for now but if we need more desktop specific styles, I believe a proper way to do it is to add a `is-desktop` (or a modifier if we are using BEM) class name [at the top level of the wpcom flavoured tour](https://github.com/Automattic/wp-calypso/blob/trunk/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-launch.js#L125).

No action is needed in this PR.
cc: @chriskmnds if you see a potential tour-kit extension for this ✍🏼

**Review by razvanpapadopol — APPROVED** [review]
Looking good, @escapemanuele
Love the mobile-first approach!
Left a couple of comments but nothing blocking  🚀

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-card.js (hunk 2 above)
Comment (chriskmnds) [reply apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-card.js:159]: Yeah, I think there is a bit of a convention mismatch. `__` should really be used to signal a relationship with an element e.g. `foo__title` or `foo__header` (as in the case with `.welcome-tour-card__overlay-controls`). For modifiers, like in the change above, the convention would be to use an `.is-modifier` class and attach it to the parent. See our [CSS/Sass Coding Guidelines](https://github.com/Automattic/wp-calypso/blob/trunk/docs/coding-guidelines/css.md) for more. I've also seen `--modifier` used elsewhere (I think that's the BEM convention).

**Comment by chriskmnds** [comment]
p.s. let's use the "Tour Kit" label for things that touch the tour kit, and "Welcome Tour" for ETK welcome tour changes (in general). Just to keep things clear when planning around. Of course, soon, more things will touch the tour kit, but until then.... 😁

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-card.js (hunk 2 above)
Comment (razvanpapadopol) [reply apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-card.js:159]: > I've also seen --modifier used elsewhere (I think that's the BEM convention).

Yes, that's one of the BEM options. You can also use a single underscore as an alternative.
eg: `[block]__[element]_[modifier-name]_[modifier-value]`

But I think I'd go with our documented approach using `.is-modifier` as it doesn't bloat the code too much 😬
