### PR TITLE
Reader: Check that comment author's URL is valid before use

### LINKED ISSUE #99012: Website input in comment form for guests needs URL validation
### Context and steps to reproduce

If not signed, when trying to leave a comment on a blog, there is no URL validation when filling out one's personal website. We've seen this lead to errors wherein a user has mistakenly added a space in the middle of her website, causing the link to their site to break in the Reader:

Image

Let's introduce URL validation to that input.

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Minor

### What other impact(s) does this issue have?

_No response_

### If a workaround is available, please outline it here.

_No response_

### Platform

_No response_

### PR DESCRIPTION
**Pull request by DustyReagan**
Related to https://github.com/Automattic/wp-calypso/issues/99012

## Proposed Changes

* Check that the comment author URL is valid before using it as a link.

## Why are these changes being made?

* WordPress Core does not validate comment author URLs, so we need to check that these URLs are valid before using them.

## Testing Instructions

* In production, go to http://wordpress.com/reader/feeds/151205063/posts/5582644405
* You should see several demo comments. The comment "Dusty Invalid URL" has a space in the author URL, and "Dusty FTP" is a link using the FTP protocol. In production, both of these links will be clickable.
* Use Calypso Live and go to /reader/feeds/151205063/posts/5582644405
* You'll see the same demo comments, but the one with an invalid author URL and the one using the FTP protocol will not be clickable. 

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/blocks/comments/post-comment.jsx [hunk 1]
```diff
@@ -318,12 +318,26 @@ class PostComment extends PureComponent {
...
+		try {
+			// URL constructor throws an error if the URL is invalid.
+			const urlObject = new URL( url );
+			// Only allow http or https URLs.
+			return urlObject.protocol === 'http:' || urlObject.protocol === 'https:';
+		} catch ( e ) {
+			return false;
+		}
+	};
+
```
Comment (Addison-Stavlo) [inline client/blocks/comments/post-comment.jsx]: It looks like we have a handful of ad-hoc definitions for isValidURL across the app. Would it make sense to use any of those? And aside from various local/exported definitions in places, some areas seem to be using something from a 'valid-url' module 🤔

File: client/blocks/comments/post-comment.jsx [hunk 2]
```diff
@@ -318,7 +319,13 @@ class PostComment extends PureComponent {
 		} else if ( commentAuthor.site_ID ) {
 			commentAuthorUrl = getStreamUrl( null, commentAuthor.site_ID );
 		} else {
-			commentAuthorUrl = commentAuthor?.URL;
+			const urlToCheck = commentAuthor?.URL;
+			if ( urlToCheck && isURL( urlToCheck ) ) {
+				const protocol = getProtocol( urlToCheck );
+				if ( protocol === 'http:' || protocol === 'https:' ) {
```
Comment (DustyReagan) [inline client/blocks/comments/post-comment.jsx]: Technically, the comment author can link to any valid protocol. However, I think it would be prudent to only expose links to HTTP protocols.

File: client/blocks/comments/post-comment.jsx (hunk 1 above)
Comment (DustyReagan) [reply client/blocks/comments/post-comment.jsx]: Good point! There is an [isURL](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-url/#isurl) function in the wordpress/url package that does nearly the same thing. How about we use that?

File: client/blocks/comments/post-comment.jsx (hunk 2 above)
Comment (Addison-Stavlo) [reply client/blocks/comments/post-comment.jsx]: I suppose we aren't limiting it right now, so no regression here... but wondering out loud: "should we" be linking to unsecure http anyways?

**Review by Addison-Stavlo — COMMENTED** [review]
Im still seeing Dusty Invalid URL as clickable (https://word%20press.com/)

**Comment by DustyReagan** [comment]
> Im still seeing Dusty Invalid URL as clickable (https://word%20press.com/)

Are you using Calypo Live, @Addison-Stavlo? It looks un-clickable to me.

Screenshot 2025-03-19 at 10 11 50 AM

File: client/blocks/comments/post-comment.jsx (hunk 2 above)
Comment (DustyReagan) [reply client/blocks/comments/post-comment.jsx]: That's a valid point! I was leaning lenient, but a quick search said > 80% of the web is using HTTPS these days. I'd be ok limiting support to HTTPS to push that along and keep our users secure.

**Comment by Addison-Stavlo** [comment]
> Are you using Calypo Live, @Addison-Stavlo? It looks un-clickable to me.

Weird! I think i used calypso live first definitely, I might have also spun up local calypso after that wasn't working but I dont recall.

Looking at calypso live right now im seeing the same thing:

image

**Review by artemiomorales — COMMENTED** [review]
Heads up, I gave this a look, both on WP Calypso and locally, and the Dusty Invalid URL is still blue.

File: client/blocks/comments/post-comment.jsx (hunk 2 above)
Comment (DustyReagan) [reply client/blocks/comments/post-comment.jsx]: I updated it to only allow HTTPS in 5839d836f5d24c26959e5c62c80c3f2e9b4957d2

**Comment by DustyReagan** [comment]
Thanks for taking a look @Addison-Stavlo and @artemiomorales. I see the problem. [Chrome and Firefox have different results for URL()](https://stackoverflow.com/questions/78874301/differences-between-firefox-and-chromium-javascript-url-validation-with-new-url). Chrome incorrectly allows `%20` in a domain name, and Firefox correctly does not. `%` chars are not allowed in domain names, so along with checking `isURL` for general validity, I added a custom check to workaround Chrome and ensure `%` is not in the domain name. 5839d836f5d24c26959e5c62c80c3f2e9b4957d2

**Review by Addison-Stavlo — APPROVED** [review]
How interesting!

This works well and makes sense to me. thanks Dusty!
