### PR TITLE
People: Fix team list and follower list freezing while scrolling

### LINKED ISSUE #23937: People: Scrolling through team list causes an unresponsive page
Edit by @gwwar: I'd recommend for any content we need to manage that we have a simple pager instead of an infinite list. Infinite lists are usually better for consuming content.

When scrolling through the people list (at `/people/team/:site`), I somehow triggered an infinite loop where the InfiniteList component keeps trying to update state. I end up with an unresponsive page, and this error:

`Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops. The above error occurred in the <InfiniteList> component`

screen shot 2018-04-05 at 11 03 30 am

I discovered this on a site with 22 people, replicated on a site with 734 users, but could not replicate on a site with 2 users (there was no scroll).

This is on Mac OS/Chrome.

---

Update by @mattsherman:

As mentioned in #25609, this also happens in the `/people/followers/{site}` section.

### PR DESCRIPTION
**Pull request by donpark**
#### Changes proposed in this Pull Request

In `InfiniteList` class, wrapped call to `upscroll()` from `componentDidUpdate()` with setTimeout to prevent React state update stack from blowing.

NOTE: This patch is a stop gap remedy until InfiniteList is rewritten to be more React friendly or replaced with a third-party virtual list package.

#### Testing instructions

Test with a site with lots of users or followers. Use dotcom p2 if you're an Automattician and don't have a site with many users.

1. Navigate to Manage > People and select either Team or Followers.
2. Scroll through the list of users.

If the list of users or followers shouldn't freeze or blank out with this patch.

*

Fixes #23937

### CODE REVIEW

**Comment by sixhours** [comment]
I scrolled alllll the way through my followers and email followers and no crashes this time. :D Will leave it to someone more dev-savvy to review the code, but this worked for me!

File: client/components/infinite-list/index.jsx [hunk 1]
```diff
@@ -154,9 +159,12 @@ export default class InfiniteList extends React.Component {
 		// we may have guessed item heights wrong - now we have real heights
 		if ( ! this.isScrolling ) {
 			this.cancelAnimationFrame();
-			this.updateScroll( {
-				triggeredByScroll: false,
-			} );
+			// updateScroll misbehaves when it's called syncronously from componentDidUpdate.
+			setTimeout( () => {
+				this.updateScroll( {
```
Comment (blowery) [inline client/components/infinite-list/index.jsx]: this could also use a `_isMounted` check, in case the component unmounted after scheduling the run.

File: client/components/infinite-list/index.jsx [hunk 2]
```diff
@@ -154,9 +159,12 @@ export default class InfiniteList extends React.Component {
 		// we may have guessed item heights wrong - now we have real heights
 		if ( ! this.isScrolling ) {
 			this.cancelAnimationFrame();
-			this.updateScroll( {
-				triggeredByScroll: false,
-			} );
+			// updateScroll misbehaves when it's called syncronously from componentDidUpdate.
+			setTimeout( () => {
```
Comment (blowery) [inline client/components/infinite-list/index.jsx]: could use `Promise.resolve().then( ... )` here to schedule the check [even closer](https://stackoverflow.com/questions/38752620/promise-vs-settimeout) to `componentDidUpdate` running.

**Comment by donpark** [comment]
@blowery `_isMounted` is now used so this PR is ready for review again. :-)

**Comment by donpark** [comment]
Marking this ready for merge since it's been reviewed from developer perspective and requested changes have been made.

**Comment by donpark** [comment]
I'll be merging this EOD today or tomorrow just in case.
