### PR TITLE
Sort email verification task to first if not verified

### LINKED ISSUE #84163: Move email verification step to top of Launchpad for unverified emails
### What

When an email addressed is unverified, a notice is displayed on the My Home page asking the user to verify their email address. We should move the "Confirm your email address" step to the top of the _Site setup_ list to encourage them to complete this step and remove the notice:

Screenshot 2023-11-14 at 8 36 53 AM

Here's how to reproduce:

- In an incognito window, move through the Sensei onboarding flow.
- When you get to the account step, enter a dummy email address.
- On the domain page, select a .blog domain.
- When checking out, first search for the email address you used in Store Admin and give yourself the appropriate number of **free** credits.
- Continue the checkout process. For payment, choose the "Assign a payment method later" option.
- Eventually you should end up on the My Home page.

### Why

Putting the email verification step first in the checklist should help with removing that notice sooner rather than later.

### How

_No response_

### PR DESCRIPTION
**Pull request by Imran92**
Related to https://github.com/Automattic/wp-calypso/issues/84163

## Proposed Changes

* Pushed email verification step to the top of tasklist if the email is not verified.

## Testing Instructions

1. In an incognito window, move through the Sensei onboarding flow.
2. When you get to the account step, enter a dummy email address.
3. On the domain page, select a .blog domain.
4. When checking out, first search for the email address you used in Store Admin and give yourself the appropriate number of free credits.
5. Continue the checkout process. For payment, choose the "Assign a payment method later" option.
6. Eventually you should end up on the My Home page.
7. Check that the verify email step is on the top
8. Now try accessing the My Home Page as a user with a verified email, maybe your current account
9. Check that the email verification step hasn't changed its place

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx [hunk 1]
```diff
@@ -131,6 +131,12 @@ const SiteSetupList = ( {
 			( task ) => task.id === CHECKLIST_KNOWN_TASKS.DOMAIN_VERIFIED && ! task.isCompleted
 		).length > 0;
 
+	useEffect( () => {
+		tasks.sort( ( task ) =>
```
Comment (renatho) [inline client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx]: This is a little dangerous because we're modifying the `tasks` variable that is prop coming to the component.

I'd suggest doing it earlier on the `ConnectedSiteSetupList`. Maybe we could even have a new filter in `WpcomTaskList` to use instead of the `getAll`? We just need to make sure we're not modifying the state.

Comment (Imran92) [reply client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx]: Thanks @renatho! I've used an es6 approach here for sorting and have used a local state for task list, https://github.com/Automattic/wp-calypso/pull/84291/commits/dd809789fb5728f75c3280e4860c8b55a77357d7, LMK if it looks good to you

Comment (renatho) [reply client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx]: It looks good, but was there a reason to create the additional state?

Instead of the new state and a `useEffect`, wouldn't it be more simple to sort after the `getAll` on the `ConnectedSiteSetupList`? We'd just need to memoize it (From what I can see we have installed in the project, it could be `createSelector` or `memoize`) to avoid the re-rendering. Maybe it was the reason you decided to create the new state?

If you prefer to keep it as it is, I'm fine. Just let me know that I can do a final test to approve. 😉

Comment (Imran92) [reply client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx]: Adding a new function beside `getAll` for sorted output looked like the best way to go here. Didn't require much change in the jsx file, also `getAllSorted` can be used from other places too if needed, with any type of comparator. And the main task list stays untouched. I've made the relevant changes here https://github.com/Automattic/wp-calypso/pull/84291/commits/15dc22f8855e6dbc1a1fb635bb3f6f867d3dc74d. Thanks for all the great suggestions Renatho! LMK if this approach looks good to you.

Comment (renatho) [reply client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx]: Nice!!! This is looking great!

I just have one last thing about the memoization. Could we memoize the result of the `getAllSorted` based on the `this.tasks`? Otherwise, it will always return a new value to the components, even if there's not change there.

Comment (Imran92) [reply client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx]: Thanks @renatho! I've memoized both the comparator and and sorting function here https://github.com/Automattic/wp-calypso/pull/84291/commits/682fd01fb84394e4bd7fe8b5777fd932340f1fc6.

> Could we memoize the result of the getAllSorted based on the this.tasks

We probably don't need memorize by the `this.tasks` explicitly here because it is already memoized during export-
https://github.com/Automattic/wp-calypso/blob/961cef3ebdda4e56f5093572a14bbfdda6d19574/client/lib/checklist/index.js#L60-L66

And `taskStatuses` is a dependency for the memoize cache key [here](https://github.com/Automattic/wp-calypso/blob/961cef3ebdda4e56f5093572a14bbfdda6d19574/client/lib/checklist/index.js#L63), so when it's updated, we already get a new instance of the sort function

**Comment by Imran92** [comment]
Looks like the "Build Calypso" step is failing even after reverting the changes https://github.com/Automattic/wp-calypso/pull/84291/commits/254b546ebbfecad8236860858baad4d57ef08ac2, so I think that's unrelated to this PR

File: client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx [hunk 2]
```diff
@@ -370,7 +376,9 @@ const ConnectedSiteSetupList = connect( ( state, props ) => {
 		menusUrl: getCustomizerUrl( state, siteId, null, null, 'add-menu' ),
 		siteId,
 		siteSlug: getSiteSlug( state, siteId ),
-		tasks: taskList.getAll(),
+		tasks: taskList.getAllSorted(
+			unverifiedEmailTaskComparator( ! isCurrentUserEmailVerified( state ) )
```
Comment (renatho) [inline client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx]: Could we move `! isCurrentUserEmailVerified( state )` to a variable to use in this argument and in the `isEmailUnverified` property?

File: client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx (hunk 1 above)
Comment (renatho) [reply client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx]: Sorry for being a little nitpicky in this part, but I'm thinking that it's important since it will impact other parts of the application not related to Sensei too. :)

> memoized both the comparator

Do you think we really need to memoize the `unverifiedEmailTaskComparator`? I think it's just memoizing the internal function based on the `isEmailUnverified` argument, right? I think this memoization wouldn't be needed with the `getAllSorted` memoized, right?

> and sorting function

I think we should send the second argument to the `memoize` to make the memoization based on the `this.tasks`? Otherwise, I think it will memoize based on the `comparator`.

File: client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx (hunk 2 above)
Comment (Imran92) [reply client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx]: Good suggestion, I've moved it to a variable here https://github.com/Automattic/wp-calypso/pull/84291/commits/ac055ce553473bbca6d2221500486a59348e3173

File: client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx (hunk 1 above)
Comment (renatho) [reply client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx]: Hey! Just to document here, based on what we talked in Slack, I'm approving this. That we want to memoize that comparator anyway, to re-run the selector in case it's changed. Thank you for working on this, Imran!

**Review by renatho — APPROVED** [review]
🚀
