### PR TITLE
Comments: Add action faker

### LINKED ISSUE #14581: DevDocs: CommentDetail block missing details
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/blocks/comment-detail
2. Observe

#### What I expected
To see comment details like this (previous screenshot):

screen shot 2017-05-30 at 9 11 14 am

#### What happened instead
Empty details (current screenshot):

screen shot 2017-05-30 at 9 11 18 am

Likely due to PR #14510, which makes it sound like it's not a functional bug but just a missing update to DevDocs - cc @Copons 

#### Browser / OS version
Seen here in OSX Firefox

#### Context / Source
#automated-testing #visdiff

### PR DESCRIPTION
**Pull request by Copons**
Incidentally fixes #14581

Introduce a `CommentFaker` HOC to easily test the Comments Management without the necessity of real data or actions.

See: https://github.com/Automattic/wp-calypso/pull/14593#issuecomment-305203184

`CommentFaker` takes the comments passed via props (with mock data, Redux-connected, etc.) and puts them in its internal state.
Then passes them and various actions (status and like setters) to the actual comment list component.
Once data and actions are completely Reduxified, it will be enough to remove the `CommentFaker` call and use the `mapDispatchToProps` actions instead.

## Notes:

- I've added two different methods to set the comment like.
Once we're set on one version, we can easily delete the other and adapt the structure in no time.
  - `toggleCommentLike( commentId )`: this is the function currently expected by `CommentDetail`.
  - `setCommentLike( commentId, likeValue )`: explicitly set the like to a defined value. This is likely the function that will be provided by the API and Redux.

- I've not included the notice related actions in the `CommentFaker` as I consider their implementation pretty much final.

### CODE REVIEW

File: client/my-sites/comments/comment-list/index.jsx [hunk 1]
```diff
@@ -214,6 +187,86 @@ export class CommentList extends Component {
 	}
 }
 
+export const CommentFaker = WrappedCommentList => class extends Component {
```
Comment (gwwar) [inline client/my-sites/comments/comment-list/index.jsx]: Let's move this into it's own file. Components/HOC are easier to find when we have one export per file.

Some jsDoc here for intent would be great too, since we don't have any faker patterns in the codebase yet.

File: client/my-sites/comments/comment-list/index.jsx [hunk 2]
```diff
@@ -176,14 +151,13 @@ export class CommentList extends Component {
 				>
 					{ map( filteredComments, comment =>
 						<CommentDetail
-							commentId={ comment.ID }
-							deleteForever={ this.deleteForever( comment.ID ) }
+							comment={ comment }
+							deleteCommentPermanently={ this.deleteCommentPermanently( comment.ID ) }
```
Comment (gwwar) [inline client/my-sites/comments/comment-list/index.jsx]: Not a blocker, but we can avoid the function creation here by updating by letting the `<CommentDetail />` component call this with:

```
this.props. deleteCommentPermanently( this.props.commentId )
```

File: client/blocks/comment-detail/index.jsx [hunk 3]
```diff
@@ -178,25 +179,32 @@ export class CommentDetail extends Component {
...
+
+	return ( {
+		authorAvatarUrl: get( comment, 'author.avatar_URL' ),
+		authorDisplayName: get( comment, 'author.name' ),
+		authorEmail: get( comment, 'author.email' ),
+		authorId: get( comment, 'author.ID' ),
+		authorIp: get( comment, 'author.ip' ), // TODO: not available in the current data structure
+		authorIsBlocked: get( comment, 'author.isBlocked' ), // TODO: not available in the current data structure
+		authorUrl: get( comment, 'author.URL' ),
+		authorUsername: get( comment, 'author.nice_name' ),
```
Comment (gwwar) [inline client/blocks/comment-detail/index.jsx]: Note that for the author props, we might normalize this in the future, where this is fetched from the users redux tree.

eg maybe something like
```jsx
authorAvatarUrl: getUserAvatarUrl( state, userId )
```

File: client/my-sites/comments/comment-list/index.jsx (hunk 1 above)
Comment (dmsnell) [inline client/my-sites/comments/comment-list/index.jsx]: @gwwar I had recommended this to @copons as it's supposed to be a dev-only (and small!) piece of code to prevent coupling fake-data operations into the final produce. I'm fine moving it, but I wanted to make note of this fact that it shouldn't be "found" by anyone

File: client/blocks/comment-detail/docs/comment-faker.jsx [hunk 4]
```diff
@@ -0,0 +1,98 @@
...
+export const CommentFaker = WrappedCommentList => class extends Component {
+	state = {
+		comments: {},
+	};
+
+	componentWillMount() {
+		if ( this.props.comments.length ) {
+			this.setState( { comments: keyBy( this.props.comments, 'ID' ) } );
+		}
+	}
```
Comment (dmsnell) [inline client/blocks/comment-detail/docs/comment-faker.jsx]: note that our length check here shouldn't really matter that much. if we have a list of zero length, `keyBy()` should return an empty object.

if we're worried about getting a list, we should probably fix that elsewhere or check specifically that it's a list we're getting

File: client/blocks/comment-detail/docs/comment-faker.jsx [hunk 5]
```diff
@@ -0,0 +1,98 @@
...
+
+	componentWillReceiveProps( nextProps ) {
+		if ( ! this.props.comments.length ) {
+			this.setState( { comments: keyBy( nextProps.comments, 'ID' ) } );
+		}
+	}
```
Comment (dmsnell) [inline client/blocks/comment-detail/docs/comment-faker.jsx]: fun tip!

I don't always aggressively modularize when I only do a thing twice in code, but in places where I'm duplicating update logic I tend to find value in leaving all of that in one spot, preferring to write duplicate calls over duplicate changes, even if it _adds_ more code overall, with the idea that it lowers our surface-area for update bugs. do as you like since this component is small (now) and it's easy enough to see both places (though it's not obvious that they should both be doing the same thing)

```js
componentWillMount() {
	this.pullCommentsFrom( this.props );
}

componentWillReceiveProps( nextProps ) {
	this.pullCommentsFrom( nextProps );
}

pullCommentsFrom = ( { comments } ) => this.setState( { comments: keyBy( comments, 'ID' ) } );
```

we see at this point too the structure inherent in both former calls and can harness that similarity

File: client/blocks/comment-detail/docs/comment-faker.jsx [hunk 6]
```diff
@@ -0,0 +1,98 @@
...
+			comments: {
+				...this.state.comments,
+				[ commentId ]: {
+					...comment,
+					i_like: likeValue,
+					status: likeValue ? 'approved' : comment.status,
+				}
+			},
+		} );
+	}
```
Comment (dmsnell) [inline client/blocks/comment-detail/docs/comment-faker.jsx]: it's fair to have both of these functions and I often find them useful because the UI often aligns more with the notion of _toggling_ than it does in _setting_. however, note the similarity between the two and where we might be able to take advantage of that…

```js
toggleCommentLike = commentId => this.setCommentLike(
	commentId,
	! get( this.state.comments, [ commentId, 'i_like' ], false ) 
);
```

a _toggle_ is just a composition of a _get_ and a _set_

File: client/blocks/comment-detail/docs/comment-faker.jsx [hunk 7]
```diff
@@ -0,0 +1,98 @@
...
+
+	render() {
+		return (
+			<WrappedCommentList
+				{ ...this.props }
+				comments={ this.state.comments }
```
Comment (dmsnell) [inline client/blocks/comment-detail/docs/comment-faker.jsx]: I sense a change in data structures here. Internally the object makes a lot of sense, but previously the interface was a list of comments. Now we're externally passing an object instead of a list. Was this intentional?

Is it better for the comments management page you built to receive a list of comments or an object?

File: client/my-sites/comments/comment-list/index.jsx (hunk 2 above)
Comment (dmsnell) [inline client/my-sites/comments/comment-list/index.jsx]: @gwwar was there a typo in that comment? it looks the same basically as what I see written in the PR.

that being said…

> avoid the function creation here

please! it should stand out that `deleteCommentPermanently` does not look like the others (`() => () => {}` instead of `() => {}`). It's okay to say, "this function I'm giving you takes a comment ID" and let the `<CommentDetail />` call it given its passed `comment`'s ID. at the end of the line we have custom data attributes to store identifier values for the actual markup receiving the click.

File: client/blocks/comment-detail/docs/comment-faker.jsx (hunk 4 above)
Comment (Copons) [inline client/blocks/comment-detail/docs/comment-faker.jsx]: The reasoning here is as follow:

- If we have `props.comments` at `willMount`: we are passing them manually (like in the CommentDetail docs). Pull those and call it a day.

- If we manage to get to `willReceiveProps` with an empty `props.comments`: we are waiting for the Redux state to be populated. Once it's populated, pull the comments in state and stop checking for `props.comments` changes, because we don't need them in the faker.

Now, that check started in `willReceiveProps` to avoid performing unnecessary `setState()` and accidentally changing `state.comments`.
But yeah, of course it's not needed in `willMount`.

File: client/blocks/comment-detail/docs/comment-faker.jsx (hunk 6 above)
Comment (Copons) [inline client/blocks/comment-detail/docs/comment-faker.jsx]: I was planning to do this but I totally forgot about it at some point.
Likely, I wanted to create a generic comment property setter to easily change both status and like. Turned out it wasn't that useful and I dropped it, and with that this as well.

File: client/blocks/comment-detail/docs/comment-faker.jsx (hunk 7 above)
Comment (Copons) [inline client/blocks/comment-detail/docs/comment-faker.jsx]: Great catch!

The page (list, nav, details) don't really care if it's an array or an object. The loop is a lodash `map` and all actions are performed via `commentId` and handled from outside anyway.

It's the faker that, as you proposed in some past PR, prefers an object to quickly update single elements.
I guess the actual API and Redux actions don't care about that as well, so I'm gonna send it to the actual `CommentList` as an array because it just makes more sense.

File: client/blocks/comment-detail/docs/comment-faker.jsx (hunk 4 above)
Comment (dmsnell) [inline client/blocks/comment-detail/docs/comment-faker.jsx]: oh, so you think it could send props with 6 comments, then 0 comments, then 8 comments or something like that and you want to make sure we don't wipe out the comments?

File: client/blocks/comment-detail/docs/comment-faker.jsx (hunk 7 above)
Comment (dmsnell) [inline client/blocks/comment-detail/docs/comment-faker.jsx]: > don't really care if it's an array or an object

the big difference here is going to be whether or not the component expects the comments to come in with a specific sort order. I doubt it since the component will likely perform its own sort based on which buttons are clicked. in the case of an object we don't know what `values()` or `map()` will be - it should end up in the order with which the keys were added to the object. with a list the sort order is explicit unless we manually sort it - position in the list.

File: client/blocks/comment-detail/docs/comment-faker.jsx (hunk 4 above)
Comment (Copons) [inline client/blocks/comment-detail/docs/comment-faker.jsx]: Considering that the Redux state changes often and unpredictably, what actually happens is that the comments in the Redux state endlessly overwrite those in the internal state.
So when you perform an action, the internal state changes and immediately after is overwritten by the Redux state.

Allowing only one single "props-to-state" prevents that, keeps things snappy and it's a fair enough tradeoff for testing purposes.

**Comment by Copons** [comment]
Thanks @dmsnell.
I've applied your suggestions and this is ready for the hopefully last look :)

File: client/my-sites/comments/comment-list/index.jsx (hunk 2 above)
Comment (gwwar) [inline client/my-sites/comments/comment-list/index.jsx]: Oh I meant that the child component could pass the commentId, since it already has it available. Very roughly this might look like:

In CommentList:
```jsx
deleteCommentPermanently={ this.deleteCommentPermanently }
```

And in the child component CommentDetail:
```jsx
deleteCommentPermanently = () => {
    this.props.deleteCommentPermanently( this.props.commentId );
}
```
