### PR TITLE
Me: Check if re-auth is required before fetching links

### LINKED ISSUE #10783: Me: Flurry of requests when re-authentication needed
Not sure exactly how I can reproduce it. I was testing a PR and noticed editor preferences wouldn't update. I checked the API response and it said the user needs to be re-authenticated. With dev toolbar still open I went over to my profile where I noticed the request storm. It obviously ended after I re-authenticated.

#### Steps to reproduce
1. Probably have 2FA activated
2. Starting at URL: wordpress.com/me

#### What I expected
The re-authentication modal to show up

#### What happened instead
The re-authentication modal to showed up and I noticed a flurry of requests

#### Screenshot / Video
request-storm

### PR DESCRIPTION
**Pull request by obenland**
This PR fixes a bug where profile links were continued to be fetched during re-authentication of a user with 2FA.

To test:
1. Have 2FA enabled.
1. Sandbox the API and add a `return true;` in `WPCOM_API_Restrict_2FA::does_token_need_refresh()`
1. Navigate to http://calypso.localhost:3000/me. The re-auth modal should show and there shouldn't be more than one profile-links request in the network tab of devtools.
1. Remove the `return true;` statement in the API.
1. Complete re-authentication. There should be only one more profile-links request.

Fixes #10783.

### CODE REVIEW

File: client/lib/two-step-authorization/index.js [hunk 1]
```diff
@@ -71,6 +71,7 @@ TwoStepAuthorization.prototype.validateCode = function( args, callback ) {
 				userSettings.fetchSettings();
 				applicationPasswords.fetch();
 				connectedApplications.fetch();
+				profileLinks.reAuthRequired = false;
```
Comment (gwwar) [inline client/lib/two-step-authorization/index.js]: I'm looking through usages. Did we never have any handlers that set this back to false before?

Comment (obenland) [inline client/lib/two-step-authorization/index.js]: Maybe we did and it was removed at some point?
