### PR TITLE
Jetpack Connect: Use correct site slug for subdir installs

### LINKED ISSUE #13509: Jetpack Connection: redirected to connect start when WP is installed in a subdirectory
#### Steps to reproduce
1. Starting on wp-admin with a site where [WordPress is installed in a subdirectory](https://codex.wordpress.org/Giving_WordPress_Its_Own_Directory).
2. Click on the Connect button to start the Jetpack connection process.
3. After connecting, you'll be redirected to the connection start.
4. Your site is in fact properly connected behind the scenes.

https://videopress.com/v/JgOF5BpW

Related: #10980

### PR DESCRIPTION
**Pull request by seear**
Fixes #13509

For sites where WordPress is installed in a subdirectory but the home url is top-level, the Calypso site slug does not contain the subdir part. Take this into account when redirecting after connection by using the home url instead of site url to generate a Calypso-style slug.

## Testing

* Test as-per #13509 
* Also test connecting a regular top-level site
* Also test connecting a site where the home url has a subdir

All of these scenarios should connect properly, then redirect to the plans page, then on to wp-admin after choosing a free plan.

### CODE REVIEW

File: client/jetpack-connect/authorize.js [hunk 1]
```diff
@@ -632,15 +632,15 @@ export class JetpackAuthorize extends Component {
 
 export default connect(
 	( state, { authQuery } ) => {
-		const siteSlug = urlToSlug( authQuery.site );
+		const siteSlug = urlToSlug( authQuery.homeUrl );
```
Comment (sirreal) [inline client/jetpack-connect/authorize.js]: If we're not using this for other connected props, this is _only_ used for redirection now. Let's just do this in the redirection where it's used.

I'll push a change.

File: client/jetpack-connect/authorize.js [hunk 2]
```diff
@@ -531,7 +529,10 @@ export class JetpackAuthorize extends Component {
 			return `/start/pressable-nux?blogid=${ clientId }`;
 		}
 
-		return addQueryArgs( { redirect: redirectAfterAuth }, `${ JPC_PATH_PLANS }/${ siteSlug }` );
+		return addQueryArgs(
+			{ redirect: redirectAfterAuth },
+			`${ JPC_PATH_PLANS }/${ urlToSlug( homeUrl ) }`
```
Comment (sirreal) [inline client/jetpack-connect/authorize.js]: If we believe `homeUrl` is reliable as part of the `authQuery`, we should adjust the schema appropriately.

We can either add it to `required` (fail early if the request doesn't include it) or we could make it fall back to `site`, which would be the previous behavior.

Thoughts? @jeherve @georgestephanis

Comment (georgestephanis) [reply client/jetpack-connect/authorize.js]: Honestly unsure -- I'd be happy to give you a site that demonstrates the issue for you to test against if it helps.

Comment (sirreal) [reply client/jetpack-connect/authorize.js]: Whoops, right in front of our eyes, `home_url` is required by the schema and just needs to be  cleaned up in the transform.

For reference, it's at least as reliable as `site_url`:

https://github.com/Automattic/jetpack/blame/02dc0701044e1238f2605a34d3bec26a1ef3739d/class.jetpack.php#L4508

**Comment by simison** [comment]
I just tested this in a dogfooding situation and it indeed fixes the problem! :thumbsup:

Details p7rcWF-Ig-p2
