### PR TITLE
Design picker: Lazy load mShot thumbnails images

### LINKED ISSUE #99283: Improve design picker performance
### Context and steps to reproduce

We recently updated the design picker to have crisper images. One of the side-effects is that it comes at a performance hit on slower connections. It can take a long time to load the images. What our customers see is a grid of flashing grey tiles:

Image

### Site owner impact

More than 60% of the total website/platform users

### Severity

Major

### What other impact(s) does this issue have?

Platform revenue

### If a workaround is available, please outline it here.

N/A

### Platform

_No response_

### PR DESCRIPTION
**Pull request by bcotrim**
Fixes #99283 

## Proposed Changes

* Adds lazy loading to images
* Use `IntersectionObserver` so the changes work on Firefox

## Why are these changes being made?

* The changes suggested on https://github.com/Automattic/wp-calypso/pull/99700 didn't work for Firefox.
* This PR follows up on that work, but uses a different approach with `IntersectionObserver`

## Testing Instructions

Borrowing @gavande1 instructions

* Visit `/setup/site-setup/goals?siteSlug=23hjrev23gh.wordpress.com`
* Open the network tab in the developer tools and select `img` requests.
* Click on Next
* Look for the number of requests sent for images. It should only send requests for images visible on the viewport.

| Before | After |
|--------|--------|
| CleanShot 2025-02-13 at 11 22 53@2x | CleanShot 2025-02-13 at 11 23 23@2x |  

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: packages/onboarding/src/mshots-image/index.tsx [hunk 1]
```diff
@@ -268,7 +273,7 @@ const MShotsImageControl = ( {
 		) : (
 			<img
 				ref={ imgRef }
-				{ ...{ className, style, src, alt } }
+				{ ...{ className, style, src, alt, loading } }
 				aria-labelledby={ labelledby }
 				alt={ alt }
```
Comment (daledupreez) [inline packages/onboarding/src/mshots-image/index.tsx]: Pre-existing nit: `alt` is being set via the `...` as well as explicitly via `alt={ alt }`. We should only use one of the two.

File: packages/onboarding/src/mshots-image/index.tsx [hunk 2]
```diff
@@ -331,9 +361,14 @@ const MShotsImageTreatment = ( {
...
 	return scrollable || ! visible ? (
-		<div className={ className } style={ style } aria-labelledby={ labelledby } />
+		<div ref={ divRef } className={ className } style={ style } aria-labelledby={ labelledby } />
 	) : (
-		<img { ...{ className, style, src, alt } } aria-labelledby={ labelledby } alt={ alt } />
+		<img
+			ref={ imgRef }
+			{ ...{ className, style, src, alt, loading } }
+			aria-labelledby={ labelledby }
+			alt={ alt }
```
Comment (daledupreez) [inline packages/onboarding/src/mshots-image/index.tsx]: As above, we're setting `alt` twice.

**Review by daledupreez — APPROVED** [review]
The updated changes seem to be working for me in both Chrome and Firefox, so I think we can likely get this shipped.

**Comment by gavande1** [comment]
@bcotrim, Thanks for the fix. TIL about [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API).
