### PR TITLE
Social Previews: strip html tags

### LINKED ISSUE #43948: (5P) Social Previews: Prevent rendering HTML tags visually
#### Steps to reproduce

The preview currently shows things like this:

Screenshot 2020-07-07 at 17 58 08

We should strip tags or find different sources for data that are already cleared.

### PR DESCRIPTION
**Pull request by cpapazoglou**
#### Changes proposed in this Pull Request

* strip html tags from descriptions for social previews

#### Testing instructions
**Manual for legacy components** 
- Run yarn && yarn start to build all the things. Wait for Calypso to boot. Goto http://calypso.localhost:3000/.
- On a Business site, create a new Post with some content and a title and click "Preview".
- Toggle the Preview to "Search and Social" using the dropdown.
- You should see the post previews and be able to toggle between each type with no errors.
- Edit your page to only include an html block with the following
```
<p>paragraph Test</p>
<p class="test">Class Test</p>
<p style="color:red;">Style Test</p><p>
</p><div>Div Test</div>
```
- Facebook, Google, Twitter previews should display their description without any html tags

**Automatic for social-previews npm package**
`>yarn run jest -c=test/packages/jest.config.js packages/social-previews/test/index.js`

Before | After
-------|------
 | 

Fixes #43948

### CODE REVIEW

File: client/components/seo/facebook-preview/index.jsx [hunk 1]
```diff
@@ -32,6 +32,8 @@ export class FacebookPreview extends PureComponent {
 	render() {
 		const { url, type, title, description, image, author } = this.props;
 
+		const strippedDescription = description ? description.replace( /<[^>]+>/g, '' ) : '';
```
Comment (retrofox) [inline client/components/seo/facebook-preview/index.jsx:35]: I did a little research about striping HTML, and found this function in [a CSS tricks post](https://css-tricks.com/snippets/javascript/strip-html-tags-in-javascript/):

```es6
const strippedString = originalString.replace(/(<([^>]+)>)/gi, "");
```

Just FYI. Also, wondering if we could create a single helper function for this,

Comment (cpapazoglou) [reply client/components/seo/facebook-preview/index.jsx:35]: > Also, wondering if we could create a single helper function for this.

I will create a follow up PR cause I just saw it when hitting the merge button!
