### PR TITLE
Signup: Show filters button for domain step in reskinned

### LINKED ISSUE #53770: Signup: missing TLD filtering in reskinned onboarding
### Steps to reproduce the behavior

1. Go to wordpress.com/start/domains?flags=signup/reskin

#### What I expected to happen
- I should be able to filter by TLD

#### What actually happened
- There is no 'wheel' (settings) button to open the filtering popover.

### Context
TLD filtering with buttons previously used in reskin was removed from the production version in https://github.com/Automattic/wp-calypso/pull/52874

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Screenshot 2021-06-17 at 11 54 17

This example is taken from the `/start/new-launch` flow that is already using a white background in production. Let's show the wheel button also for reskin.
Screenshot 2021-06-17 at 11 47 19

### PR DESCRIPTION
**Pull request by alshakero**
#### Changes proposed in this Pull Request

* Fixes https://github.com/Automattic/wp-calypso/issues/53770

#### Testing instructions

1. Go to /start?flags=signup/reskin
2. Reach domain step.
3. You should see filters button there.

### CODE REVIEW

File: client/components/domains/register-domain-step/index.jsx [hunk 1]
```diff
@@ -506,7 +506,8 @@ class RegisterDomainStep extends React.Component {
 			! Array.isArray( this.state.searchResults ) &&
 			! this.state.loadingResults &&
 			! this.props.showExampleSuggestions;
-		const showFilters = isKrackenUi && ! isRenderingInitialSuggestions && ! this.props.isReskinned;
+		const showFilters =
+			( isKrackenUi && ! isRenderingInitialSuggestions ) || this.props.isReskinned;
```
Comment (StefanNieuwenhuis) [inline client/components/domains/register-domain-step/index.jsx:510]: `isKrackenUi` is defined twice (`client/components/domains/register-domain-step/index.jsx` line [501](https://github.com/Automattic/wp-calypso/blob/3acbf529fb061866c8b0eebf7f17c5b93bcb7251/client/components/domains/register-domain-step/index.jsx#L501) & [389](https://github.com/Automattic/wp-calypso/blob/3acbf529fb061866c8b0eebf7f17c5b93bcb7251/client/components/domains/register-domain-step/index.jsx#L389)). 

Why are the definitions different and are the filters affected?

**Review by StefanNieuwenhuis — COMMENTED** [review]
The filters are showing up nicely (see screenshot), but the hover currently uses a theme color. Don't we have to use a reskin-defined-color (something blue-ish)?

I left another comment regarding the `isKrackenUi` variable. 

Can you please address them? Thanks so much!

Screenshot 2021-06-17 at 14 49 55

File: client/components/domains/register-domain-step/index.jsx (hunk 1 above)
Comment (alshakero) [reply client/components/domains/register-domain-step/index.jsx:510]: > Why are the definitions different and are the filters affected?

Because one of them is only concerning pagination, while the other is concerning filters. I don't think filters are affected by this inconsistency. Although, I agree that the Kraken variable names aren't great.

Comment (StefanNieuwenhuis) [reply client/components/domains/register-domain-step/index.jsx:510]: Thanks for elaborating @alshakero. It may become confusing in the future, but for now, it makes sense to let it as is.

**Comment by StefanNieuwenhuis** [comment]
I noticed the search bar & filter pop up overflowing from the screen on certain breakpoints. On production, the search bar is nicely contained in the screen, so I suspect the filter + filter popup. 

I think it's best to create a separate issue for this and fix it there. WDYT?

Screenshot 2021-06-18 at 11 48 05

File: client/components/domains/search-filters/style.scss [hunk 2]
```diff
@@ -178,17 +178,21 @@
 body.is-section-signup.is-white-signup {
 	$accent-blue: #117ac9;
 
+	.search-filters__popover,
 	.search-filters-extensions__popover {
-		@include break-medium {
-			transform: translateX( 65px );
-		}
```
Comment (StefanNieuwenhuis) [inline client/components/domains/search-filters/style.scss:184]: Thanks so much for addressing this Omar! It's much better already but I think that we still have to include the transform in `breakpoints > mobile` (see screenshot) since the modal isn't aligned with the search bar anymore. WDYT? 

Screenshot 2021-06-18 at 12 15 48

Comment (alshakero) [reply client/components/domains/search-filters/style.scss:184]: The modal wasn't aligned with the field before this change, and I'm not sure if we should touch that because it affects [other places as well](https://github.com/Automattic/wp-calypso/pull/53779#issuecomment-863904718).

Comment (StefanNieuwenhuis) [reply client/components/domains/search-filters/style.scss:184]: Let's leave it as is :)

**Review by StefanNieuwenhuis — APPROVED** [review]
Code tested as per testing instructions and all works well. 
Thanks for addressing my comments.
I'd say Squash, Merge & Release! 🚀
