### PR TITLE
Don't show fullscreen launchpad for sites with no intent

### LINKED ISSUE #101219: Focused Launchpad is empty
### Context and steps to reproduce

I'm seeing a blank page on the focused launchpad:

Image

Steps to reproduce:

1. Signup as a fresh user
2. On the plans step of the signup flow, choose any paid plan.
3. Once you reach the checkout page, just type wordpress.com in the address bar of your browser.
4. Notice that the focused launchpad is an empty page.

Another way to reproduce:

1. Signup as a fresh user
2. On the plans step of the signup flow, choose a Free plan.
3. Once you reach the goals step, just type wordpress.com in the address bar of your browser.
4. Notice that the focused launchpad is an empty page.

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Major

### What other impact(s) does this issue have?

_No response_

### If a workaround is available, please outline it here.

_No response_

### Platform

_No response_

### PR DESCRIPTION
**Pull request by daledupreez**
Fixes https://github.com/Automattic/wp-calypso/issues/101219

Related to https://github.com/Automattic/wp-calypso/issues/101018 - it's possible this PR addresses that issue as well.

## Proposed Changes

* This change updates the `shouldShowLaunchpadFirst( site )` selector's internal logic so that it doesn't show the fullscreen launchpad when we have a site that doesn't have a site_intent option set, or has the `site_intent` option set to `''`. This should prevent us from showing a fullscreen launchpad with no tasks.

## Why are these changes being made?

* As reported in https://github.com/Automattic/wp-calypso/issues/101219, this is an awful UX for users who have somehow missed having a site intent set.

## Testing Instructions

* Run the code from this branch locally or via calypso.live
* Work through the onboarding flow at `/setup/onboarding`, and pick a paid plan on the plans step
* Wait for checkout to load, and not the site slug in the URL - do not complete checkout
* In a second window, load `/home/[site_slug]`
* Verify that you are redirected to My Home, and do not see the fullscreen launchpad

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [N/A] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [N/A] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [N/A] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [N/A] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/state/selectors/should-show-launchpad-first.ts [hunk 1]
```diff
@@ -3,15 +3,18 @@ import { SiteDetails, Onboard } from '@automattic/data-stores';
...
+ * Determines if the launchpad should be shown first based on site creation flow.
  * @param site Site object
  * @returns Whether launchpad should be shown first
  */
 export const shouldShowLaunchpadFirst = ( site: SiteDetails ): boolean => {
 	const wasSiteCreatedOnboardingFlow = site.options?.site_creation_flow === 'onboarding';
 	const isBigSkyIntent = site?.options?.site_intent === SiteIntent.AIAssembler;
+	// If we don't have a site intent, fall through to the next option.
+	const siteHasNoIntent =
+		site && site.options && ( site.options.site_intent === '' || ! site.options.site_intent );
```
Comment (p-jackson) [inline client/state/selectors/should-show-launchpad-first.ts:15]: Rather than testing for different kinds of emptiness, maybe we could flip the sense of the `! wasSiteCreatedOnboardingFlow`. That is, remove the early exit and replace the functions logic with:

```ts
return wasSiteCreatedOnboardingFlow && ! isBigSkyIntent
```

**Review by p-jackson — APPROVED** [review]
Oh no 🙈 bad bug.

I left a comment about the logic, but the approach is good.

File: client/state/selectors/should-show-launchpad-first.ts (hunk 1 above)
Comment (daledupreez) [reply client/state/selectors/should-show-launchpad-first.ts:15]: Thanks for the review, @p-jackson!

I don't think that would address this issue, TBH, as your proposed condition would still return `true` for the case where the site _was_ created via the `onboarding` flow, but doesn't have any declared intent.

Comment (daledupreez) [reply client/state/selectors/should-show-launchpad-first.ts:15]: I am also happy for you and your team to consider how to handle this better in general -- I have a related bug coming shortly that's going to push us to think about the logic here more broadly.

**Review by niranjan-uma-shankar — APPROVED** [review]
LGTM.

I tested the scenarios mentioned in https://github.com/Automattic/wp-calypso/issues/101219, and can confirm that I get the full launchpad instead of the empty launchpad. I'm not too familiar with the code, so I defer that to someone more knowledgeable on it.

File: client/state/selectors/test/should-show-launchpad-first.ts [hunk 2]
```diff
@@ -14,19 +14,48 @@ beforeEach( () => {
...
 			},
 		} as SiteDetails;
 
 		expect( await shouldShowLaunchpadFirst( site ) ).toBe( true );
 	} );
 
+	it( 'should return false when site was created via onboarding flow, has the ai-assembler intent, and assigned to experiment', async () => {
+		( loadExperimentAssignment as jest.Mock ).mockResolvedValue( {
+			variationName: 'treatment_cumulative',
+		} );
```
Comment (daledupreez) [inline client/state/selectors/test/should-show-launchpad-first.ts:34]: @Automattic/quake, is the experiment assignment mocking still needed in these tests? If not, I think it would be well worth cleaning up the tests.

File: client/state/selectors/should-show-launchpad-first.ts (hunk 1 above)
Comment (p-jackson) [reply client/state/selectors/should-show-launchpad-first.ts:15]: Woops you're right. I still think flipping the sense makes things easier though:

`isOnboardingFlow && hasIntent && ! bigSky`

> I am also happy for you and your team to consider how to handle this better in general 

I'm eod so I'm happy for you to merge this, it doesn't really look like a bug we should delay fixing.

File: client/state/selectors/test/should-show-launchpad-first.ts (hunk 2 above)
Comment (p-jackson) [reply client/state/selectors/test/should-show-launchpad-first.ts:34]: I left it in because I imagined there would be future experiments that would impact the launchpad. But with the change in focus and the goal-based launchpad projects on hold I can't see it being needed.

It should be cleaned up.

File: client/state/selectors/should-show-launchpad-first.ts (hunk 1 above)
Comment (daledupreez) [reply client/state/selectors/should-show-launchpad-first.ts:15]: Agreed! I'd be happy for the logic to get cleaned up, but I wanted to fix the immediate problem as an initial priority. So I've merged this as-is, and we can improve from here.
