### PR TITLE
Themes - Fix going "back" to themes showcase and losing my place in browsing themes.

### LINKED ISSUE #38182: Themes: select a theme, then go back and my place is lost (for subsequent attempts)
#### Steps to reproduce
1. Visit wordpress.com/themes
2. Scroll past "Recommended Themes" and click the "More Themes" button.
3.  Scroll down further and view "info" of a theme.
4.  Hit the back button, notice we are in scroll position of viewing the theme we selected "info" for.
5.  Select "info" a second time, and hit the "back" button a second time.
6.  Verify we are now looking at the top of the Themes page and have lost our place in scrolling through search results.

#### What I expected
To go back to where I was in scroll position and Theme browsing.

#### What happened instead
Reloaded to the top of the page.

#### Context / Source

This is a result of recent changes made on the Themes showcase section after adding a "Recommended Themes" section and hiding the search functionality behind the "More Themes" button.  
- Main PR #37696 and Issue #37285.
- First followup PR #38107 and Issue #38061.
- Second followup PR #38133 and issue #38120

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
#### Changes proposed in this Pull Request

* Add a `themesBookmark` section to the data store to allow for users to consistently return to their place in the browsing the showcase.

#### How this works
When a user clicks on a Theme card, the theme id is stored as the bookmark.  

When the `ThemesShowcase` mounts, it checks to see if the bookmark is set and scrolls to the card if it exists on the screen.

The theme is found by a React `ref` that is created in the `ThemesShowcase` and passed down child components until it gets to the `ThemeList`.  Here, the `ThemeList` decides whether or not to continue passing the `ref` down to the `Theme` component based on the `id` of the theme and the bookmark.

#### Testing instructions

* Run this PR locally.
* Navigate to themes section.
* Open "More Themes", scroll down, and select "Info" for some theme.
* Hit the "back" button.
* Verify we are back at the theme we selected.
* Hit "Info" again (for the same or a different theme), and hit the "Back" button again.  Verify we are still led back to the theme we had selected.
* Navigate to another section of calypso, such as "Plan" or "My Site".
* Hit "Themes" again, verify that we are looking at the theme we last viewed info for.
* Hit "Themes" again, verify we return to the top of the themes page.

Fixes #38182

### CODE REVIEW

File: client/components/theme/index.jsx [hunk 1]
```diff
@@ -197,14 +208,16 @@ export class Theme extends Component {
...
 		return (
-			<Card className={ themeClass } data-e2e-theme={ e2eThemeName }>
+			<Card className={ themeClass } data-e2e-theme={ e2eThemeName } onClick={ this.setBookmark }>
 				{ this.isBeginnerTheme() && (
 					<Ribbon className="theme__ribbon" color="green">
 						{ translate( 'Beginner' ) }
 					</Ribbon>
 				) }
-				<div className="theme__content">
+				<div className="theme__content" { ...bookmarkRef }>
```
Comment (noahtallen) [inline client/components/theme/index.jsx]: I feel like in this case it could be more clear to do `ref={ bookmarkRef }` and then destructure `bookmarkRef` from props instead of putting it inside of an object. Though I'm not sure -- does `ref` need to be a value, or can it be null?

Comment (Addison-Stavlo) [reply client/components/theme/index.jsx]: This is what I did at first, and ref can be null.  What happens is that there is a `ref={null}` on every Theme card that way.  I am not sure if having the unnecessary `ref` prop on that many cards is "ok" (it probably is), but to be safe I edited it this way so that only the bookmarked theme card has a `ref` prop on it.  

React documentation talks about not 'overusing' refs, and while having `ref={null}` all over the place may not be what they are referring to, I figured limiting the prop to only the card that is actually using it would be the safest thing to do.

**Comment by Addison-Stavlo** [comment]
> Then it returns me to the theme card even though I scrolled away from it. Do we think that's an ok tradeoff? 🤔

Consider that prior to this PR in that flow the final return would take you to the top of the Themes page at 'Recommended Themes,'  which is neither the last theme you were looking at nor where you left off in scroll-browsing.  With that being the case, I don't think it is a bad trade off to return to the last card that was clicked.  

I had originally thought about saving the scroll location on dismount and returning to that.  However in trying to implement this I found some inconsistencies (possibly related to some SSR 'weirdness') where it would not always save the expected scroll location, causing you to return to the bookmark that would have been expected from 2-3 attempts ago and not properly updating for new ones.

File: client/my-sites/themes/theme-showcase.jsx [hunk 2]
```diff
@@ -107,10 +107,24 @@ class ThemeShowcase extends React.Component {
...
+			setTimeout( () => {
+				const lastTheme = this.bookmarkRef.current;
+				if ( lastTheme ) {
+					lastTheme.scrollIntoView( {
+						behavior: 'auto',
+						block: 'center',
+						inline: 'center',
+					} );
+				}
+			}, 40 );
```
Comment (Addison-Stavlo) [inline client/my-sites/themes/theme-showcase.jsx]: @noahtallen what are your thoughts on the timeout?

I found without the timeout it would always return to the top of the page.  After digging around the code and testing different `scrollTo( 0, 0 )`s that were in place, I was not successful in finding anything as the specific cause.  Adding the timeout seems to make it work correctly, but I am still not too happy about having some arbitrary number of ms sitting there as the fix.

I could make this `10` instead of `40` and it still seems to work fine.  Will this have issues on slower machines?  or will it not matter since the timeout will always run after whatever instantaneous post-mount function is causing this odd behavior?  I am inclined to believe the latter but I figured it would be worth pointing this out.

File: client/components/theme/index.jsx (hunk 1 above)
Comment (noahtallen) [reply client/components/theme/index.jsx]: sounds good!

File: client/my-sites/themes/theme-showcase.jsx (hunk 2 above)
Comment (noahtallen) [reply client/my-sites/themes/theme-showcase.jsx]: The only thing I can think of is weird issues with the JS event loop. Since we have a timeout set, it defers the callback until the next iteration of the event loop -- i.e. it does not happen synchronously. Perhaps something in the immediate execution needs to happen before the scroll will work. If that's the case, then you should be able to use `setTimeout` of 0 in order to get JS to run the callback asynchronously

Comment (noahtallen) [reply client/my-sites/themes/theme-showcase.jsx]: If you haven't heard about this (I hadn't either until a few months ago 😁), you can read up on it here: https://stackoverflow.com/questions/779379/why-is-settimeoutfn-0-sometimes-useful (there are some useful videos linked too)

Comment (Addison-Stavlo) [reply client/my-sites/themes/theme-showcase.jsx]: Awesome, thanks for the input and info.  That makes sense and it works well with no delay on the timeout, the scroll just needed to be at the end of the queue for whatever reason.  I have updated it to just be `setTimeout( func )` instead which makes me feel a bit better. 😄

Comment (noahtallen) [reply client/my-sites/themes/theme-showcase.jsx]: Great!
