### PR TITLE
Theme: fix upload area visual styling and cursor

### LINKED ISSUE #11037: Themes: upload area cursor and styling
screen shot 2017-01-30 at 14 04 09

Since we allow clicking on the drop area, we should show `cursor: pointer;`.

/ht @roccotripaldi

### PR DESCRIPTION
**Pull request by folletto**
Updating the styling of the theme upload drop/click area, fixes #11037.

Before:

screen shot 2017-02-06 at 21 47 39

After (with hover):

screen shot 2017-02-06 at 21 46 53

screen shot 2017-02-06 at 21 47 01

### To test

1. Open My Sites → Themes → Upload.
2. Try to hover the form with the mouse, click to open.
3. Make sure the hover style works and the mouse cursor is the `pointer`.

### CODE REVIEW

File: client/my-sites/themes/theme-upload/index.jsx [hunk 1]
```diff
@@ -156,24 +156,19 @@ class Upload extends React.Component {
...
-			'Do you have a custom theme to upload to your site?'
-		);
-		const uploadInstructionsText = translate(
-			"Make sure it's a single zip file, and upload it here."
-		);
 		const dropText = translate(
 			'Drop files or click here to upload'
 		);
+		const uploadInstructionsText = translate(
+			"Only single .zip files are accepted."
```
Comment (omarjackman) [inline client/my-sites/themes/theme-upload/index.jsx]: This'll generate a warning and should be changed to single quotes

Comment (folletto) [inline client/my-sites/themes/theme-upload/index.jsx]: *facepalm* you're right. I wonder why Atom didn't mark it :|

Comment (omarjackman) [inline client/my-sites/themes/theme-upload/index.jsx]: > This'll generate a warning and should be changed to single quotes

That sounded kinda blunt, sorry about that :smile:
