### PR TITLE
Plugin Management: Fix issue with auto managed plugin tooltip appearing on self-hosted sites.

### LINKED ISSUE #73403: Jetpack Cloud: Plugins page incorrectly says Jetpack is managed
### Quick summary

Jetpack is listed as a managed plugin. How is this determined?

### Steps to reproduce

1. Visit a self-hosted Jetpack site's plugin page via cloud.jetpack.com
2. See Gutenberg, Akismet, Jetpack, etc listed as "auto managed" even though it isn't.

### What you expected to happen

Plugins not be displayed as managed when not an Atomic host.

### What actually happened

Atomic managed plugins listed as such.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

2023-02-15 at 4 25 PM

### PR DESCRIPTION
**Pull request by jkguidaven**
Currently, in the Plugin Management UI, preinstalled plugins in the Atomic sites and not on the self-hosted site appear to be **auto-managed**. 

219199741-63130ee1-55ae-4773-a8a6-1843d79ef278

Related to https://github.com/Automattic/wp-calypso/issues/73403

## Proposed Changes

* Update `isAutoManaged` to only consider preinstalled plugins for Atomic sites.

## Testing Instructions

**Self-hosted sites**
* Spin up a JN site and connect it to the Jetpack cloud. Make sure there is Jetpack or any plugins that are preinstalled on Atomic sites (e.g., Akismet, Gutenberg, etc. )
* Use the Jetpack Cloud or Calypso live link and goto `/plugins/manage/<JN site>.`
* Confirm that the Jetpack or any preinstalled plugins on Atomic sites do not appear as **auto-managed** in the JN site.
Screen Shot 2023-05-24 at 3 02 35 PM

**Atomic sites**
* Spin up an Atomic site by creating a new WordPress site in WPCOM with a Business plan. This should convert your site to an Atomic site
* Use the Calypso live link and goto `/plugins/manage/<JN site>.`
* Confirm that the Jetpack or any preinstalled plugins on Atomic sites are auto-managed.
Screen Shot 2023-05-24 at 3 05 36 PM

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React, or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by jkguidaven** [comment]
I am unfamiliar with plugin management, so I am adding the Calypso team as a reviewer.

**Comment by kraftbj** [comment]
I notice two, maybe three issues.
1. I think now Jetpack just isn't shown at all? [this may be limited to only sites running versions of Jetpack from the beta plugin, so may be a different issue. I don't see it on one site, but do see Jetpack on another.
2023-05-24 at 9 28 AM

2. Other managed plugins that aren't pre-installed still suffer from this:

2023-05-24 at 9 29 AM
2023-05-24 at 9 30 AM

3. For Pressable sites (and I presume other Atomic-but-not-WoA sites), Akismet and Jetpack are managed, but not displayed as such. I don't know if we expect Calypso to understand that thought:
2023-05-24 at 9 33 AM

2023-05-24 at 9 33 AM

File: client/my-sites/plugins/plugin-autoupdate-toggle/index.jsx [hunk 1]
```diff
@@ -60,7 +60,8 @@ export class PluginAutoUpdateToggle extends Component {
 
 	isAutoManaged = () =>
 		( this.props.isMarketplaceProduct && this.props.productPurchase ) ||
-		PREINSTALLED_PLUGINS.includes( this.props.plugin.slug ) ||
+		( this.props.site?.is_wpcom_atomic &&
```
Comment (tyxla) [inline client/my-sites/plugins/plugin-autoupdate-toggle/index.jsx]: We likely want to use the `isSiteAutomatedTransfer` selector here instead.

**Review by tyxla — COMMENTED** [review]
Kraft left some pretty awesome review already, so I'll just add a suggestion on the code itself.

File: client/my-sites/plugins/plugin-autoupdate-toggle/index.jsx (hunk 1 above)
Comment (jkguidaven) [reply client/my-sites/plugins/plugin-autoupdate-toggle/index.jsx]: Thanks for suggesting this 👍 . I tweaked the conditions to fix the issue Kraft mentioned above. Let me know what your thought about the new change.

**Comment by jkguidaven** [comment]
> I think now Jetpack just isn't shown at all? [this may be limited to only sites running versions of Jetpack from the beta plugin, so may be a different issue. I don't see it on one site, but do see Jetpack on another.

That is weird. I tried spinning a JN site with Jetpack beta on it but it was displaying fine. I also don't think the changes here is related to displaying or hiding plugins in the list. 

> Other managed plugins that aren't pre-installed still suffer from this:

My latest change should now fix this. 👍 

> For Pressable sites (and I presume other Atomic-but-not-WoA sites), Akismet and Jetpack are managed, but not displayed as such. I don't know if we expect Calypso to understand that thought:

 I am not sure we should expect Calypso to know what plugins are managed in Pressable. Any thoughts on this @tyxla?

**Review by tyxla — COMMENTED** [review]
> I am not sure we should expect Calypso to know what plugins are managed in Pressable. Any thoughts on this @tyxla?

I think it should know, Pressable are our own after all. Calypso already does know, to some degree, but not properly:

Screenshot 2023-05-30 at 15 15 31

You can see that it properly detects that Akismet is managed and autoupdates are disabled, but we're still allowed to disable it. Not sure that's expected behavior.

Activating/deactivating seems to be disabled for Jetpack on that page. However, when I open the Jetpack plugin page, it allows me to deactivate it, which definitely feels wrong when we're managing it:

Screenshot 2023-05-30 at 15 20 26

File: client/my-sites/plugins/plugin-autoupdate-toggle/index.jsx (hunk 1 above)
Comment (tyxla) [reply client/my-sites/plugins/plugin-autoupdate-toggle/index.jsx]: Thanks 👍 

Nit: I think the `isAutoManaged` function can now use some improvement, as it's pretty hard to read. Maybe it could use some comments to help with that. And/or, we could separate the condition bits into variables and that could help make the code more comprehensible.

**Comment by jkguidaven** [comment]
> You can see that it properly detects that Akismet is managed and autoupdates are disabled, but we're still allowed to disable it. Not sure that's expected behavior.

I think this was a side effect of the bug since both WPCOM and Pressable manage Jetpack and Akismet. It looks like it was working, but If you try to install **Yoast SEO** on the Pressable site, it will also appear auto-managed even though it is not. 

Screen Shot 2023-05-31 at 2 37 25 PM


As for the **Pessable OnePress login** plugin, it was not in WPOrg plugin repo so auto-update was disabled.

The recent commit changes the behavior for Pressable sites.

Screen Shot 2023-05-31 at 2 21 50 PM

> I think it should know, Pressable are our own after all. Calypso already does know, to some degree, but not properly:


If we decide to include Pressable managed plugins, where do I find the list of plugins? Also, do we have a way to determine which site is hosted in Pressable in Calypso?


> Activating/deactivating seems to be disabled for Jetpack on that page. However, when I open the Jetpack plugin page, it allows me to deactivate it, which definitely feels wrong when we're managing it:Activating/deactivating seems to be disabled for Jetpack on that page. However, when I open the Jetpack plugin page, it allows me to deactivate it, which definitely feels wrong when we're managing it:

Thanks for spotting this 👍 . This is another area that needs to be fixed.

**Comment by tyxla** [comment]
> If we decide to include Pressable managed plugins, where do I find the list of plugins? 

I haven't worked with Pressable myself for a long time, and those can change at every given moment. It's best to coordinate with the Pressable team to get a thorough list. Perhaps @zwiesman31 may know?

> Also, do we have a way to determine which site is hosted in Pressable in Calypso?

Yes, one way we've historically done it is to use the Jetpack Start API and retrieve the partner by blog ID. If a partner is found, you can check the result data if it's Pressable or not.

Perhaps folks from @Automattic/jetpack-avalon might know more since I know they're working on partner portals and it's likely that they work a lot more closely with those APIs.

**Comment by atanas-dev** [comment]
> Perhaps folks from https://github.com/orgs/Automattic/teams/jetpack-avalon might know more since I know they're working on partner portals and it's likely that they work a lot more closely with those APIs.

On the WPCOM side, we can determine whether Pressable has provisioned a Jetpack product to a given site (which they should only be doing for sites hosted on Pressable) but we can't determine whether a site is hosted by Pressable if they don't have a Jetpack product provisioned via our API.

**Comment by jkguidaven** [comment]
> > Perhaps folks from https://github.com/orgs/Automattic/teams/jetpack-avalon might know more since I know they're working on partner portals and it's likely that they work a lot more closely with those APIs.
> 
> On the WPCOM side, we can determine whether Pressable has provisioned a Jetpack product to a given site (which they should only be doing for sites hosted on Pressable) but we can't determine whether a site is hosted by Pressable if they don't have a Jetpack product provisioned via our API.

Thank you for this information, @atanas-dev.  That being said, let's revisit this later with a reliable solution to determine Pressable sites without needing a Jetpack plugin provisioned via Partner Licensing API.  I added a task (1202619025189113-as-1204755800257985) to our maintenance board to investigate how we can do this.

For now, we scope this PR to fix the issue with WPCOM auto-managed plugin.

File: client/my-sites/plugins/plugin-autoupdate-toggle/index.jsx (hunk 1 above)
Comment (jkguidaven) [reply client/my-sites/plugins/plugin-autoupdate-toggle/index.jsx]: Thanks. I added some improvements in `isAutoManaged` as suggested. 👍

**Review by yashwin — APPROVED** [review]
LGTM. Thanks for fixing this issue!

**Comment by jkguidaven** [comment]
@tyxla, my PR is ready for another review. Can you have another look? 🙏

**Review by tyxla — APPROVED** [review]
LGTM 👍

**Comment by jkguidaven** [comment]
Thanks everyone for the review 👍
