### PR TITLE
FSE: Fix navigation to the template editor

### LINKED ISSUE #36380: FSE: Fix Template Editor Navigation in Calypso
Holy cow, this part of our codebase is super fragile.

I'm noticing that navigating to a template editor from the page editor does not update the URL, nor does the back button go back to the page editor. 

1. Start at the pages list for your site in calypso.
2. Open a page to edit it
3. Immediately click "edit header" to open the header editor (_do not select the header before clicking the button_)
4. Notice that the URL did not update to match wp-template as the post type.
5. Click "back to page" and notice that it takes you to the all pages list, not the page you were editing.

Interestingly, if you focus the header block before clicking the button, this bug does not happen!!

Notice in this gif that the URL in the lower left (the href of the button when you hover on it) is set to the wpadmin URL before I select the header block. After I select the header block, that href changes to the correct Calypso URL.

We've had similar bugs before:

- This PR introduced Calypso navigation for the template editor: https://github.com/Automattic/wp-calypso/pull/34766
- This PR fixed back navigation from the template editor: https://github.com/Automattic/wp-calypso/pull/35005
- Issue with back to page button showing up on wpcom: https://github.com/Automattic/wp-calypso/pull/35354
- Back button didn't go back to the checklist: https://github.com/Automattic/wp-calypso/pull/35841

### PR DESCRIPTION
**Pull request by noahtallen**
We changed the structure of the hover UI for the "edit template" button in the page editor, so the iframe bridge server wasn't updating the hrefs with the correct Calypso URLs until the template blocks were focused in Gutenberg. This was valid before we changed the hover interaction, but caused bugs when clicking the button without focusing the block.

This code keeps breaking when we change the hover interaction, so I added a scary comment to the FSE code which touches it.

We really need a less artisanal solution, but I'd like to ship this for the 10% test. IMO, the correct solution would be a well-designed Calypso-iFrame navigation API that we can hook into through the iFrame bridge server. Occasionally, we have buttons in the block editor which need their hrefs changed from wpadmin URLs to Calypso URLs. Currently, we do manual DOM selection to handle this for a few cases, but this is obviously not a stable solution.

#### Changes proposed in this Pull Request
* Update the iframe bridge server to update the href on the "edit template" links correctly. 

#### Testing instructions
1. Apply this patch to your sandbox (the auto-generated iframe bridge server code): **D33303-code**
2. Sandbox the API and widgets.wp.com, as well as the site you're going to test.
3. On an FSE enabled site, open the page editor from Calypso. Hover over the "edit header" button. 
4. In the bottom-left corner of the browser, you should see the href of the button. It should match the format `.../block-editor/edit/wp_template/...`
Screen Shot 2019-09-27 at 5 11 48 PM

5. Click on the button without focusing the header area and make sure that when the template editor loads, the browser URL updates to match the path above.
6. Click the back button in the template editor. It should load the previous page editor. It should not load the all pages list. 
7. Repeat steps 5 and 6 several times with the header/footer and make sure that it always goes to the template editor and back to the page editor without messing up. :) You're mainly trying to see if you can reproduce using the instructions in #36380

Fixes #36380

### CODE REVIEW

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/edit.js [hunk 1]
```diff
@@ -132,6 +132,22 @@ const TemplateEdit = compose(
 			savePost();
 		};
 
+		/**
```
Comment (vindl) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/edit.js]: ❤️
