### PR TITLE
[PbD Interim Fix]: Update EligibilityWarnings layout

### LINKED ISSUE #38141: [PBD interim fix] Update Upgrade&Launch prompt screen
Related to PBD interim fix epic https://github.com/Automattic/wp-calypso/issues/38110

**Goal**

Make `/plugins/upload` and `/themes/upload` pages look like the screenshot below for users who are not eligible for an upgrade:

Zrzut ekranu 2019-12-3 o 15 32 57

* Only mention the business plan if they are on lower plan
* Only mention site launch if their site is private
* Replicate the `calypso_banner_cta_click` event that's currently fired by the upgrade banner

Obviously ignore the arrows from Figma :-)

**Links**
* Figma file 233b7-pb
* paObgF-I3-p2

### PR DESCRIPTION
**Pull request by p-jackson**
## Changes proposed in this Pull Request

Fixes the Private by Default upgrade experience as desribed here paObgF-I3-p2

This PR tries to focus on the layout changes of the `<EligibilityWarnings>` component. Let me know if there's something you think could be split into a seperate PR.

* Removes the "upgrade to business" `<Banner>` and moves it into the list of other holds
* Restyle the list of holds to use checkmarks
* Restyle the list of warnings to look consistent with holds
* Dim and disable the main warnings card when there's a blocking `<Notice>` at the top e.g. when you get a `BLOCKED_ATOMIC_TRANSFER` error

*Before*
Screenshot 2019-12-12 at 5 46 37 PM

*After*
See testing instructions

#### Free, unlaunched/private site should see:

Zrzut ekranu 2019-12-20 o 12 40 42

#### Free, public site should see:

Zrzut ekranu 2019-12-20 o 12 40 46

#### Business plan, unlaunched/private site should see:

Zrzut ekranu 2019-12-20 o 12 40 53

#### Business plan, public site should see:

Zrzut ekranu 2019-12-20 o 13 07 29

#### Unlaunched site with a paid domain should see:

Zrzut ekranu 2019-12-20 o 12 43 50

#### Business plan, public site, with a paid domain should see:

Zrzut ekranu 2019-12-20 o 13 12 13

### On `/themes/upload`

Repeat the same process as above. The only difference should be the header and the copy. It should talk about themes instead of plugins.

### On `/hosting-config/activate`

Repeat the same process as above. The only difference should be the header and the copy. It should talk about activating hosting instead of plugins.

### With blog sticker

Add the `blocked-from-atomic-transfer` sticker to your site, you should see the following:

Zrzut ekranu 2019-12-20 o 12 59 24

### Other considerations

* Click on Continue button, confirm a tracks event `cta_name=calypso-theme-eligibility-upgrade-nudge` is still getting logged
* Try the same test plan with a mobile device - is everything still looking good there?
* After switching UI to another language, fallback copy should be used:

Zrzut ekranu 2019-12-20 o 15 34 40

## Known issues

* The copy in this PR seems a little bit weird, it effectively says "You'll need to: Public site". This is going to be addressed in another PR that will be released in tandem with this one: https://github.com/Automattic/wp-calypso/pull/38324
* We still have a "Help" button that links to support pages and is effectively a dead end. This is in line with what's currently on that screen and will be addressed in another PR.

Fixes #38141

### CODE REVIEW

File: client/blocks/eligibility-warnings/hold-list.tsx [hunk 1]
```diff
@@ -94,24 +65,82 @@ function getHoldMessages( translate: LocalizeProps[ 'translate' ] ) {
...
+			contactUrl: null,
+		},
+		NO_VIP_SITES: {
+			message: translate( 'Try using a different site.' ),
+			status: 'is-error',
+			contactUrl: null,
+		},
+		SITE_GRAYLISTED: {
+			message: translate(
+				"There's an ongoing site dispute. Contact us to review your site's standing and resolve the dispute."
```
Comment (a8ci18n) [inline client/blocks/eligibility-warnings/hold-list.tsx]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **19** times:
`translate( 'Contact us to review your site's standing and resolve the dispute.' )` *ES Score: 6*

File: client/blocks/eligibility-warnings/hold-list.tsx [hunk 2]
```diff
@@ -94,24 +65,82 @@ function getHoldMessages( translate: LocalizeProps[ 'translate' ] ) {
...
+			),
+			status: 'is-error',
+			contactUrl: localizeUrl( 'https://en.support.wordpress.com/suspended-blogs/' ),
+		},
+		NO_SSL_CERTIFICATE: {
+			message: translate(
+				'Certificate installation in progress. Hold tight! We are setting up a digital certificate to allow secure browing on your site using "HTTPS".'
```
Comment (a8ci18n) [inline client/blocks/eligibility-warnings/hold-list.tsx]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **19** times:
`translate( 'Hold tight! We are setting up a digital certificate to allow secure browsing on your site, using "HTTPS". Please try again in a few minutes.' )` *ES Score: 6*

File: client/blocks/eligibility-warnings/hold-list.tsx [hunk 3]
```diff
@@ -93,24 +65,91 @@ function getHoldMessages( translate: LocalizeProps[ 'translate' ] ) {
...
+		BLOCKED_ATOMIC_TRANSFER: {
+			message: translate(
+				'This site is not currently eligible to install themes and plugins. Please contact our support team for help.'
+			),
+			status: 'is-error',
+			contactUrl: localizeUrl( 'https://wordpress.com/help/contact' ),
+		},
+		TRANSFER_ALREADY_EXISTS: {
+			message: translate(
+				'Installation in progress. Just a minute! Please wait until the installation is finisehd, then try again.'
```
Comment (ramonjd) [inline client/blocks/eligibility-warnings/hold-list.tsx]: `finisehd`

File: client/blocks/eligibility-warnings/hold-list.tsx [hunk 4]
```diff
@@ -93,24 +65,91 @@ function getHoldMessages( translate: LocalizeProps[ 'translate' ] ) {
...
+		SITE_GRAYLISTED: {
+			message: translate(
+				"There's an ongoing site dispute. Contact us to review your site's standing and resolve the dispute."
+			),
+			status: 'is-error',
+			contactUrl: localizeUrl( 'https://en.support.wordpress.com/suspended-blogs/' ),
+		},
+		NO_SSL_CERTIFICATE: {
+			message: translate(
+				'Certificate installation in progress. Hold tight! We are setting up a digital certificate to allow secure browing on your site using "HTTPS".'
```
Comment (ramonjd) [inline client/blocks/eligibility-warnings/hold-list.tsx]: `browing`

File: client/blocks/eligibility-warnings/hold-list.tsx [hunk 5]
```diff
@@ -151,16 +190,37 @@ export const HoldList = ( { holds, isPlaceholder, translate }: Props ) => {
...
-		</div>
+			</div>
+		</>
 	);
 };
 
+function getCardHeading( context: string | null, translate: LocalizeProps[ 'translate' ] ) {
+	switch ( context ) {
+		case 'plugins':
+			return translate( "To install plugins, you'll need a couple things:" );
```
Comment (ramonjd) [inline client/blocks/eligibility-warnings/hold-list.tsx]: `couple things`

File: client/blocks/eligibility-warnings/hold-list.tsx [hunk 6]
```diff
@@ -151,16 +190,37 @@ export const HoldList = ( { holds, isPlaceholder, translate }: Props ) => {
...
+		case 'themes':
+			return translate( "To install themes, you'll need a couple things:" );
```
Comment (ramonjd) [inline client/blocks/eligibility-warnings/hold-list.tsx]: as above: missing `of`

File: client/blocks/eligibility-warnings/hold-list.tsx [hunk 7]
```diff
@@ -151,16 +190,37 @@ export const HoldList = ( { holds, isPlaceholder, translate }: Props ) => {
...
+		default:
+			return translate( "To continue, you'll need a couple things:" );
```
Comment (ramonjd) [inline client/blocks/eligibility-warnings/hold-list.tsx]: as above: missing `of`

**Review by ramonjd — CHANGES_REQUESTED** [review]
I've tested according to instructions, and the screens look good

Screen Shot 2019-12-12 at 4 45 30 pm
Screen Shot 2019-12-12 at 4 45 43 pm
Screen Shot 2019-12-12 at 4 48 01 pm

Not confident on commenting on the code being a bit out of the loop.

Requesting changes as there are some typos in the copy.

File: client/blocks/eligibility-warnings/hold-list.tsx (hunk 7 above)
Comment (p-jackson) [reply client/blocks/eligibility-warnings/hold-list.tsx]: I was not typing well that day it seems! 😅 

The "couple things" came from the design. I don't mind it, but do you feel it's too informal compared to our usual voice?

File: client/blocks/eligibility-warnings/hold-list.tsx [hunk 8]
```diff
@@ -93,24 +65,91 @@ function getHoldMessages( translate: LocalizeProps[ 'translate' ] ) {
...
+		BLOCKED_ATOMIC_TRANSFER: {
+			message: translate(
+				'This site is not currently eligible to install themes and plugins. Please contact our support team for help.'
+			),
+			status: 'is-error',
+			contactUrl: localizeUrl( 'https://wordpress.com/help/contact' ),
+		},
+		TRANSFER_ALREADY_EXISTS: {
+			message: translate(
+				'Installation in progress. Just a minute! Please wait until the installation is finished, then try again.'
```
Comment (a8ci18n) [inline client/blocks/eligibility-warnings/hold-list.tsx]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **20** times:
`translate( 'Just a minute! Please wait until the installation is finished, then try again.' )` *ES Score: 8*

File: client/blocks/eligibility-warnings/hold-list.tsx [hunk 9]
```diff
@@ -93,24 +65,91 @@ function getHoldMessages( translate: LocalizeProps[ 'translate' ] ) {
...
+		SITE_GRAYLISTED: {
+			message: translate(
+				"There's an ongoing site dispute. Contact us to review your site's standing and resolve the dispute."
+			),
+			status: 'is-error',
+			contactUrl: localizeUrl( 'https://en.support.wordpress.com/suspended-blogs/' ),
+		},
+		NO_SSL_CERTIFICATE: {
+			message: translate(
+				'Certificate installation in progress. Hold tight! We are setting up a digital certificate to allow secure browsing on your site using "HTTPS".'
```
Comment (a8ci18n) [inline client/blocks/eligibility-warnings/hold-list.tsx]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **19** times:
`translate( 'Hold tight! We are setting up a digital certificate to allow secure browsing on your site, using "HTTPS". Please try again in a few minutes.' )` *ES Score: 8*

File: client/blocks/eligibility-warnings/hold-list.tsx (hunk 7 above)
Comment (ramonjd) [reply client/blocks/eligibility-warnings/hold-list.tsx]: I've heard it before, and shudder every time :)

I know it's part of North-American English, but in my judgement, readers from the UK/AU/NZ/CA would find it unusual. Confusing things further, "couple things" is also used to describe activities that take place between couples in a relationship.

We're speaking to a wider audience, and therefore I'd feel comfortable overriding the copy writers on this one, if only to make the sentence clearer, and easier to read.

Just my 1.39c (after AUD->USD conversion)

**Review by ramonjd — DISMISSED** [review]

**Comment by adamziel** [comment]
Relevant discussion going on at paObgF-Mn-p2

File: client/blocks/eligibility-warnings/hold-list.tsx [hunk 10]
```diff
@@ -93,24 +70,91 @@ function getHoldMessages( translate: LocalizeProps[ 'translate' ] ) {
 	};
 }
 
+function getBlockingMessages( translate: LocalizeProps[ 'translate' ] ) {
+	return {
+		BLOCKED_ATOMIC_TRANSFER: {
+			message: translate(
+				'This site is not currently eligible to install themes and plugins, or activate hosting access. Please contact our support team for help.'
```
Comment (a8ci18n) [inline client/blocks/eligibility-warnings/hold-list.tsx]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **19** times:
`translate( 'This site is not currently eligible to install themes and plugins. Please contact our support team for help.' )` *ES Score: 7*

**Comment by p-jackson** [comment]
Updated some copy that assumed `<EligibilityWarnings>` was going to appear during plugin uploading. But it's also used during theme upload and when configuring hsoting options https://github.com/Automattic/wp-calypso/pull/38277/commits/c9547b077e5c20c83b4fca2685f1f4c6c0a2fd3f

When describing the hosting I said things like: `These features aren't (yet) compatible with`**`hosting access`**`and will be disabled` and `This site is not currently eligible to install themes and plugins, or`**`activate hosting access`**.

I got nomenclature from the notice on `/hosting-config`:
Screenshot 2019-12-20 at 4 43 16 PM

**Comment by adamziel** [comment]
Thank you so much @p-jackson, this is super thoughtful!

I just implemented the rest of design updates and this is ready for review again. CC @michaeldcain @ianstewart

File: client/blocks/eligibility-warnings/hold-list.tsx (hunk 1 above)
Comment (jblz) [reply client/blocks/eligibility-warnings/hold-list.tsx]: Merging the titles and messages like this is going to result in a number of places where we'll be waiting for localized strings.  Should we either:
* String freeze this PR & hold for translations
* Do something like: `message: hasTranslation( "There's an ongoing site dispute. Contact us to review your site's standing and resolve the dispute." ) ? translate( "There's an ongoing site dispute. Contact us to review your site's standing and resolve the dispute." : translate( 'Contact us to review your site's standing and resolve the dispute.' ),`

File: client/blocks/eligibility-warnings/hold-list.tsx [hunk 11]
```diff
@@ -151,16 +194,39 @@ export const HoldList = ( { holds, isPlaceholder, translate }: Props ) => {
...
+function getCardHeading( context: string | null, translate: LocalizeProps[ 'translate' ] ) {
+	switch ( context ) {
+		case 'plugins':
+			return translate( "To install plugins you'll need to:" );
+		case 'themes':
+			return translate( "To install themes you'll need to:" );
+		case 'hosting':
+			return translate( "To activate hosting access you'll need to:" );
+		default:
+			return translate( "To continue you'll need to" + ':' );
```
Comment (jblz) [inline client/blocks/eligibility-warnings/hold-list.tsx]:
```suggestion
			return translate( "To continue you'll need to:" );
```

File: client/blocks/eligibility-warnings/hold-list.tsx [hunk 12]
```diff
@@ -1,44 +1,35 @@
...
-import SectionHeader from 'components/section-header';
+import { Button } from '@automattic/components';
+import CardHeading from 'components/card-heading';
+import Gridicon from 'components/gridicon';
+import Notice from 'components/notice';
+import NoticeAction from 'components/notice/notice-action';
 import { localizeUrl } from 'lib/i18n-utils';
 
 // Mapping eligibility holds to messages that will be shown to the user
 // TODO: update supportUrls and maybe create similar mapping for warnings
```
Comment (jblz) [inline client/blocks/eligibility-warnings/hold-list.tsx]: Is this TODO still relevant after the change?

File: client/blocks/eligibility-warnings/index.tsx [hunk 13]
```diff
@@ -38,66 +34,34 @@ interface ExternalProps {
...
-				feature={ feature }
-				event={ event }
-				plan={ plan }
-				title={ title }
-				href={ bannerURL }
-			/>
-		);
-	}
+	const logEventAndProceed = () => {
+		// We removed <Banner /> Component which logged this event on upsell click.
```
Comment (jblz) [inline client/blocks/eligibility-warnings/index.tsx]: I'm not sure this comment is useful in the codebase going forward.  I'd document it in the PR / commit history and take out the comment

File: client/blocks/eligibility-warnings/test/index.tsx [hunk 14]
```diff
@@ -0,0 +1,172 @@
...
+ */
+
+/**
+ * External dependencies
+ */
+import { noop } from 'lodash';
+import React, { ReactChild } from 'react';
+import { createStore } from 'redux';
+import { Provider } from 'react-redux';
+import { fireEvent, render } from '@testing-library/react';
```
Comment (jblz) [inline client/blocks/eligibility-warnings/test/index.tsx]: 😍

File: client/blocks/eligibility-warnings/hold-list.tsx (hunk 1 above)
Comment (adamziel) [reply client/blocks/eligibility-warnings/hold-list.tsx]: I was thinking about shipping this one without waiting for translations since it's a way better experience than what we currently have, `hasTranslation` is just perfect - I'm going to update this PR right now.

**Review by jblz — COMMENTED** [review]
The code looks really good overall -- Great work! I'm continuing to test.

I added a concern about string changes that we should probably solve before landing this.

Also, I think it would be helpful to add is more developer documentation around eligibility warnings in general and about specific functions.

Can we please either / and / or:
* Add a `client/blocks/eligibility-warnings/README.md` which describes the purpose of the component at a high level
* Add JSDoc blocks to functions like:
  * `isHardBlockingHoldType`
  * `getBlockingMessages`

...so unfamiliar folks (& future us) will have an easier time groking what this does and how it relates to the data from the API

**Comment by jblz** [comment]
Noting that the `ci/wp-desktop` failure looks related to the node upgrade.

File: client/blocks/eligibility-warnings/index.tsx [hunk 15]
```diff
@@ -38,66 +34,34 @@ interface ExternalProps {
...
+		// We want to keep tracking the data in the same way, so let's fake the banner click here
+		recordCtaClick( feature );
+		onProceed();
```
Comment (jblz) [inline client/blocks/eligibility-warnings/index.tsx]: It looks like the component is not actually blocking the plugin flow (at least):

eligibility-warning-doesnt-block

Do we still need to build out the implementation for the click handler to launch the site, add the plan to the cart, & redirect to checkout?

**Review by jblz — DISMISSED** [review]

File: client/blocks/eligibility-warnings/index.tsx (hunk 15 above)
Comment (adamziel) [reply client/blocks/eligibility-warnings/index.tsx]: That's listed in known issues

Comment (adamziel) [reply client/blocks/eligibility-warnings/index.tsx]: See https://github.com/Automattic/wp-calypso/pull/38364

Comment (jblz) [reply client/blocks/eligibility-warnings/index.tsx]: Cool.  That's all I've found -- I'll go review that PR now so we can get it merged in here.

Comment (adamziel) [reply client/blocks/eligibility-warnings/index.tsx]: This is now part of this PR so it should be fully functional

File: client/blocks/eligibility-warnings/hold-list.tsx [hunk 16]
```diff
@@ -93,24 +87,115 @@ function getHoldMessages( translate: LocalizeProps[ 'translate' ] ) {
...
+				: translate( "Contact us to review your site's standing and resolve the dispute." ),
+			status: 'is-error',
+			contactUrl: localizeUrl( 'https://en.support.wordpress.com/suspended-blogs/' ),
+		},
+		NO_SSL_CERTIFICATE: {
+			message: hasTranslation(
+				'Certificate installation in progress. Hold tight! We are setting up a digital certificate to allow secure browsing on your site using "HTTPS".'
+			)
+				? hasTranslation(
+						'Certificate installation in progress. Hold tight! We are setting up a digital certificate to allow secure browsing on your site using "HTTPS".'
```
Comment (a8ci18n) [inline client/blocks/eligibility-warnings/hold-list.tsx]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **19** times:
`translate( 'Hold tight! We are setting up a digital certificate to allow secure browsing on your site, using "HTTPS". Please try again in a few minutes.' )` *ES Score: 9*

File: client/blocks/eligibility-warnings/hold-list.tsx [hunk 17]
```diff
@@ -151,16 +235,57 @@ export const HoldList = ( { holds, isPlaceholder, translate }: Props ) => {
...
 					) }
-			</Card>
-		</div>
+			</div>
+		</>
 	);
 };
 
+function getCardHeading( context: string | null, translate: LocalizeProps[ 'translate' ] ) {
+	const defaultCopy = translate( 'Please clear all issues above to proceed.' );
```
Comment (jblz) [inline client/blocks/eligibility-warnings/hold-list.tsx]: Unfortunately, this copy (`Please clear all issues above to proceed.`) doesn't work since the issues now appear below the Heading text.  I'll just update it to the new fallback: `To continue you'll need to:` & hopefully the individual items will be enough context for non-English speakers.

Comment (jblz) [reply client/blocks/eligibility-warnings/hold-list.tsx]: This should be fixed in 3a756ef

**Review by jblz — CHANGES_REQUESTED** [review]
Varying the text by consulting `i18n.hasTranslation` was not working properly in the default (US English) locale.  Fix in #38562

File: client/blocks/eligibility-warnings/test/index.tsx [hunk 18]
```diff
@@ -0,0 +1,181 @@
...
+			<EligibilityWarnings backUrl="" onProceed={ handleProceed } />,
+			state
+		);
+
+		const upgradeAndContinue = getByText( 'Upgrade and continue' );
+
+		fireEvent.click( upgradeAndContinue );
+
+		expect( handleProceed ).not.toHaveBeenCalled();
+		expect( upgradeAndContinue ).toHaveAttribute(
```
Comment (jblz) [inline client/blocks/eligibility-warnings/test/index.tsx]: This is the only test failing once the strings are fixed by #38562.

I think we need to do something like:
* Attach an `onClick` to the component which:
  * Dispatches the action to launch the site, then
  * Redirects to the checkout screen
* Update this test to cover the above

**Review by jblz — DISMISSED** [review]

File: client/blocks/eligibility-warnings/test/index.tsx (hunk 18 above)
Comment (adamziel) [reply client/blocks/eligibility-warnings/test/index.tsx]: That test is off, this isn’t supposed to work in this PR. For now the button is just greyed out. There is a separate PR to add „auto-launching” feature. It’s okay to remove this test from here.

Comment (adamziel) [reply client/blocks/eligibility-warnings/test/index.tsx]: Ah I got confused by `Dispatches the action to launch the site, then` - I took a deeper look and this test should pass. Your follow-up PR will fix it though as the button will have the correct copy (https://github.com/Automattic/wp-calypso/pull/38562).

**Comment by adamziel** [comment]
As `i18n-calypso` patch may not be straightforward to merge (See https://github.com/Automattic/wp-calypso/pull/38565 and https://github.com/Automattic/wp-calypso/pull/38566), I added a local version of `hasLocalizedText()` function what we may use for now. Let's remove it once the other patch gets merged or this one gets properly translated.

**Review by jblz — COMMENTED** [review]
This is working really well.  Once this is rebased w/ unrelated changes removed, I think it's good to go!

File: client/blocks/eligibility-warnings/has-localized-text.js [hunk 19]
```diff
@@ -0,0 +1,9 @@
+/**
+ * External dependencies
+ */
+import i18n from 'i18n-calypso';
+
+export const hasLocalizedText = message =>
+	i18n.state.localeSlug === i18n.defaultLocaleSlug || i18n.hasTranslation( message );
+
+export default hasLocalizedText;
```
[the remark this answers is not in the document]
Comment (adamziel) [reply client/blocks/eligibility-warnings/has-localized-text.js]: A linter rules would be a good follow up to this

**Review by jblz — APPROVED** [review]
Bravo!

**Comment by adamziel** [comment]
This one was quite a journey - deployed now :-)
