### PR TITLE
fix(/me/purchases) Update domain description message

### LINKED ISSUE #26664: Confusing Message in Purchases when Renewing Domains
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/purchases
2. Click on a domain purchase

#### Actual Message

The message that comes up is confusing. It says "Replaces your site's free address with the domain SITE.wordpress.com, making it easier to remember and easier to share." I noticed this while exploring Purchases.

 #### Expected message
Something linke: Replaces your site's free address damiannepatomicsite9383.wordpress.com with the domain, making it easier to remember and easier to share.

#### Screenshot / Video
domain registration message

#### Context / Source
<!-- Optional: share your unique context to help us understand your perspective. You can add context tags such as: #journey #anecdote #narrative #context #empathy #perspective #reallife #dogfooding #livesharing #flowsharing #anxiety #anxiety-flow #stresscase #painpoint.

### PR DESCRIPTION
**Pull request by Hywan**
Fix #26664.

### CODE REVIEW

File: client/me/purchases/manage-purchase/index.jsx [hunk 1]
```diff
@@ -312,7 +312,7 @@ class ManagePurchase extends Component {
 			description = theme.description;
 		} else if ( isDomainMapping( purchase ) || isDomainRegistration( purchase ) ) {
 			description = translate(
-				"Replaces your site's free address with the domain %(domain)s, " +
+				"Replaces your site's free address %(domain)s with the domain, " +
```
Comment (prettyboymp) [inline client/me/purchases/manage-purchase/index.jsx]: Since the `%(domain)s` is a non-defining detail, it should be enclosed in comma's.  E.g,

"Replaces your site's free address, example.wordpress.com, with the domain, making it easier to remember and share"
