### PR TITLE
HelpCenter: set env based on proxied connection

### LINKED ISSUE #67933: [Bug]: Help Center: Sorry We Couldn't Connect You Error
### Quick summary

When starting a new chat I initially see a "Sorry we couldn't connect you with a Happiness Engineer. Please check back later." message. 

chat message

@arcangelini 

### Steps to reproduce

1. Open Help Center from a chat eligible account
2. Select Still Need Help
3. Select Live chat
4. Start a chat
5. See the we couldn't connect you message

### What you expected to happen

To be connected to a Happiness Engineer without an error message

### What actually happened

A connection error message is shown for a few seconds

### Browser

Google Chrome/Chromium

### Context

_No response_

### Platform (Simple, Atomic, or both?)

_No response_

### Other notes

_No response_

### Reproducibility

Consistent

### Severity

_No response_

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by arcangelini**
## Proposed Changes

~This uses a new API endpoint to determine if the user is proxied or not. If proxied then Happy Chat auth and chat init will connect to the staging. If not then it will use production.~

Currently there can be a discrepancy between the chat environment that is checked for availability and the chat environment that the user enters. In theory this is something only seen by proxied users, but this PR unifies the environments and allow it to change dynamically if you are proxied. We extended the `/happychat/session` endpoint to return the environment URL. This is passed through the `auth` and is used to update the `window.configData` in the happychat app.

There was also a bug introduced in a past PR that was disabling the init connection of happychat inside widgets.wp.com. I removed the bug but we need to address disabling HappyChat/inline-help in places that Help Center is showing.

## Testing Instructions

1. Open your sandbox and pull this diff - D88273-code
2. Pull branch and `cd apps/editing-toolkit/ && yarn dev --sync`
3. Sandbox a testing site URL, public-api, and widgets.wp.com
4. Go to the editor and open Help Center and start a chat.
5. Look at the websockets and ensure the check and connection use the same URL.
7. It should check against staging and connect you to staging chat.

Closes #67933

### CODE REVIEW

File: apps/happychat/src/app.jsx [hunk 1]
```diff
@@ -79,6 +79,12 @@ async function AppBoot() {
 		}
 	}
 
+	if ( auth ) {
+		window.configData.env_id =
+			auth.url === 'https://happychat.io/customer' ? 'production' : 'development';
+		window.configData.happychat_url = auth.url;
+	}
```
Comment (alshakero) [inline apps/happychat/src/app.jsx]: We don't need this anymore 🕺🏼  We should delete all `happychat_url` instances from all the code and use the one from session. And to fix the widgets app and change main Calypso, you just need to change this [function](https://github.com/Automattic/wp-calypso/blob/trunk/client/state/happychat/utils.js) the same way you changed this [one](https://github.com/Automattic/wp-calypso/blob/trunk/packages/happychat-connection/src/use-happychat-auth.ts#L14). 

But please create a `url` variable with a JSDoc above it. Because this is a confusing change for someone 1) used to happychat_url config 2) unaware of the context.

Something like this:
```js
	/**
	 * The /happychat/session endpoint returns the right env (staging vs production) based on whether the user is proxied.
	 */
	const url: string = ....
```

@klimeryk This is a tiny but important change and might confuse people, is there somewhere we should share it?

He're the reasoning behind it: p1663771182341809-slack-C02T4NVL4JJ

File: apps/happychat/src/index.ejs [hunk 2]
```diff
@@ -22,19 +22,12 @@
...
-			const env_id = env === 'dev' ? 'development' : 'production';
-
 			window.configData = {
-				env_id,
+				env_id: 'development',
 				i18n_default_locale_slug: 'en',
 				google_analytics_key: 'UA-10673494-15',
 				client_slug: 'browser',
-				happychat_url,
+				happychat_url: 'https://happychat-io-staging.go-vip.co/customer',
```
Comment (alshakero) [inline apps/happychat/src/index.ejs]:
```suggestion
```

File: apps/happychat/src/index.ejs [hunk 3]
```diff
@@ -22,19 +22,12 @@
...
-			const env = new URLSearchParams( window.location.search ).get( 'env' ) || 'dev';
-			const happychat_url =
-				env === 'dev'
-					? 'https://happychat-io-staging.go-vip.co/customer'
-					: 'https://happychat.io/customer';
-			const env_id = env === 'dev' ? 'development' : 'production';
-
 			window.configData = {
-				env_id,
+				env_id: 'development',
```
Comment (alshakero) [inline apps/happychat/src/index.ejs]: Oooh I hope this one doesn't complicate things. 

I searched the code and Happychat doesn't seem to depend on this, we're probably OK to delete it. Would appreciate any insight on this one @klimeryk 🙏🏼 .

File: client/components/happychat/connection-connected.jsx [hunk 4]
```diff
@@ -11,8 +9,7 @@ export default connect(
 	( state, ownProps ) => ( {
 		getAuth: ownProps.getAuth || getHappychatAuth( state ),
 		isConnectionUninitialized: isHappychatConnectionUninitialized( state ),
-		isHappychatEnabled:
-			config.isEnabled( 'happychat' ) && ! shouldShowHelpCenterToUser( getCurrentUserId( state ) ),
+		isHappychatEnabled: config.isEnabled( 'happychat' ),
```
Comment (alshakero) [inline client/components/happychat/connection-connected.jsx]: This will bring back the bug explained [here](https://github.com/Automattic/wp-calypso/pull/66407#:~:text=again.%20Interestingly%2C%20it%20seems%20the-,remnants,-of%20FAB%20are%20active%20and). 

Let's copy the solution from [here](https://github.com/Automattic/wp-calypso/pull/68046/files#diff-52162a5dc985b44902901411edeb96565c4c4be47adc7e8f32ffaff072d4b3a5R15-R17)

Then pass this [this](https://github.com/Automattic/wp-calypso/pull/68046/files#diff-bd7ff7b9859f24ed9347c9c12b799ddb65f3a77c0ca58f8bd7bfeca923b17b32R163).

File: packages/help-center/src/components/help-center-inline-chat.tsx [hunk 5]
```diff
@@ -18,7 +16,7 @@ const InlineChat: React.FC = () => {
 			ref={ ( ref ) => setIframe( ref ) }
 			className="help-center-inline-chat__iframe"
 			title="Happychat"
-			src={ `https://widgets.wp.com/calypso-happychat/?env=${ env }` }
+			src="https://widgets.wp.com/calypso-happychat/"
```
Comment (alshakero) [inline packages/help-center/src/components/help-center-inline-chat.tsx:19]: Beautiful <3

**Review by alshakero — CHANGES_REQUESTED** [review]
Much much neater!

File: apps/happychat/src/index.ejs (hunk 3 above)
Comment (arcangelini) [reply apps/happychat/src/index.ejs]: Removed and tested in dev / prod both seem to start correctly in widgets.wp.com 👍

File: apps/happychat/src/index.ejs (hunk 2 above)
Comment (arcangelini) [reply apps/happychat/src/index.ejs]: 👍

File: client/components/happychat/connection-connected.jsx (hunk 4 above)
Comment (arcangelini) [reply client/components/happychat/connection-connected.jsx]: 👍

**Review by alshakero — APPROVED** [review]
Super pumped about this one!
