### PR TITLE
Connections: Add default grid icons for connection services

### LINKED ISSUE #41326: Connections: Instagram avatar and disconnection message
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/marketing/connections/[site]
2. Create a new Instagram connection
3. The avatar looks like this:
Screenshot 2020-04-21 at 15 27 13
4. Disconnect Instagram
5. The message looks like this:
Screenshot 2020-04-21 at 15 27 02

#### What I expected
- We should show the correct Avatar
- We should show the correct service name when disconnecting

### PR DESCRIPTION
**Pull request by ivan-ottinger**
Third-party services (e.g. Facebook, LinkedIn, Twitter, ...) connected to a site (in Tools → Marketing → Connections) display linked profile picture (if it is available):

Markup on 2021-11-10 at 12:55:43

When there is no profile picture available, empty box is displayed instead:

Markup on 2021-11-10 at 12:58:51
Markup on 2021-11-10 at 13:01:53

The proposed change adds default [Grid icon](https://github.com/Automattic/gridicons) for each service and also addresses the Instagram case (https://github.com/Automattic/wp-calypso/issues/41326) where the profile picture isn't available due to [Instagram API](https://developers.facebook.com/docs/instagram-basic-display-api/reference/user) limitations.

The following screenshots illustrates the changes proposed by this PR:

Markup on 2021-11-10 at 13:10:06
Markup on 2021-11-10 at 13:10:30

#### Changes proposed in this Pull Request

* Add default Grid icon for third-party services
* Make sure the styling is correct

#### Testing instructions
1. Navigate to Tools → Marketing → Connections
2. Decide which service you would like to test. The services easiest to test are Instagram and LinedIn.
3. If you are testing Instagram, simply connect your account to the site
4. If you are testing LinkedIn (or other third-party service), it is necessary to temporarily remove your profile picture from your third-party service account.
5. The default Grid icons (`user` - avatar) should be displayed - as can be see in the two screenshots above

Please note that some services won't let you remove your profile picture completely (e.g. Twitter). The PR adds default icon for them anyways - in case the service changes the way they handle profile pictures in the future.

Related to https://github.com/Automattic/wp-calypso/issues/41326.

### CODE REVIEW

File: client/my-sites/marketing/connections/connection.jsx [hunk 1]
```diff
@@ -46,6 +46,12 @@ class SharingConnection extends Component {
 		defaultServiceIcon: {
 			google_my_business: 'institution',
 			slack: 'link',
+			'instagram-basic-display': 'user',
```
Comment (arcangelini) [inline client/my-sites/marketing/connections/connection.jsx:49]: Haha it bugs me that this is the only one in single quotes but it seems like that is how it should be.

**Review by arcangelini — APPROVED** [review]
Tested and works for me 🥳 

Markup 2021-11-11 at 16 23 46

File: client/my-sites/marketing/connections/connection.jsx (hunk 1 above)
Comment (ivan-ottinger) [reply client/my-sites/marketing/connections/connection.jsx:49]: Yeah, it would look better without the quotes. :)

Thank you or the review!
