### PR TITLE
2FA: Auto-trim code input on changes

### LINKED ISSUE #14709: Login: Backup: Trailing space fails validation and inconsistent validation error design
Steps to reproduce:

- Pick an account that has 2FA enabled and make sure you have your backup codes handy.
- Visit `/login` and enter your username and password.
- In the next screen, click "I can't access my phone"
- Paste a backup code followed by a trailing space and click Continue
- Note that you won't be able to proceed and that the validation message displayed is not formatted as other validation messages (for example, enter an invalid username in `/login`).

screenshot from 2017-06-02 11-44-35

Tested on both Chrome and Firefox.

### PR DESCRIPTION
**Pull request by jsnmoon**
This fixes #14709 by auto-trimming the two-factor key input. This prevents invalid input states caused by leading/trailing spaces.

#### Testing instructions

1. Check out locally (`git checkout fix/login-verification-code-validation`) and start your server. You can also use a [live branch](https://calypso.live/?branch=fix/login-verification-code-validation)
2. Open the [{login page}](http://calypso.localhost:3000/log-in)
3. Try the SMS flow. Verify that leading and trailing spaces are not enterable.
4. Try the authenticator flow. Verify the same as above.
5. Try the backup codes flow. Verify the same as above.

#### Reviews

- [ ] Code
- [ ] Product

### CODE REVIEW

File: client/blocks/login/two-factor-authentication/verification-code-form.jsx [hunk 1]
```diff
@@ -64,10 +65,15 @@ class VerificationCodeForm extends Component {
...
+		const {
+			name,
+			value = '',
+		} = event.target;
+
 		this.props.formUpdate();
 
 		this.setState( {
-			[ event.target.name ]: event.target.value,
+			[ name ]: typeof value === 'string' ? value.trim() : value,
```
Comment (stephanethomas) [inline client/blocks/login/two-factor-authentication/verification-code-form.jsx]: Just curious, when would `value` be something other than a string? Or `undefined`?

Comment (jsnmoon) [inline client/blocks/login/two-factor-authentication/verification-code-form.jsx]: In its current state, this component would never set the target value to `undefined` nor `null`. Just my instinctual defensive programming habits kicking in :)

I'll remove this check and merge this PR.
