### PR TITLE
Gutenlypso: Polish trash flow

### LINKED ISSUE #28813: Gutenberg in Calypso - Trashing a post doesn't show notice on resulting posts screen
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/block-editor/post
2. Create a draft
3. Click "Move to Trash"

#### What I expected

Posts screen displays with message post was trashed (as per existing Calypso editor behaviour)

trash calypso

#### What happened instead

No notice on posts screen:

trash calypso gutenberg

#### Browser / OS version

Chrome 70 on macOS

#### Screenshot / Video

*see above for before and after

#### Context / Source

Found converting e2e tests

### PR DESCRIPTION
**Pull request by Copons**
#### Changes proposed in this Pull Request

- Move `getPostTypeTrashUrl` into its own selector for reusability.

- Move the redirection to the trash list logic from `BrowserUrl` to a new `PostTrashLink` component overriding the Gutenberg one.

- On click, `PostTrashLink` moves the post to trash, and then navigates back to the trash list while displaying a success notice with an undo action.
Note: this uses the Calypso `trashPost` action to take advantage of its side effect that handles notices and undo.

- Opening a trash post will display a Restore dialog, like in Calypso Classic.
Note: this uses the Gutenberg `savePost` action to restore, so that the editor instantly knows about the status change.

#### Testing instructions

* Open an existing post in Gutenlypso at `/block-editor`.
* Click on "Move to trash" in the document sidebar.
* ⚠️ It should redirect to the trashed posts list of the correct post type.
* ⚠️ It should actually trash the post. Check in the network tab if there is a call to `/v1.1/sites/:site/posts/:post/delete`.
* ⚠️ It should display a success notice with an undo action.
* Try clicking on the undo action.
* ⚠️ It should restore the post.
* Do it all again, but this time don't restore the post. Edit it instead.
* ⚠️ It should display a "Restore" dialog.
* Try clicking on "Don't restore".
* ⚠️ It should return to the trashed posts list.
* Edit the trashed post again, and this time click on "Restore" in the dialog.
* ⚠️ It should restore the post into a draft. Check in the network tab if there is a call to `/wp/v2/sites/:site/posts/:post`.

#### Notes

- The posts list is quite janky when it comes to recalculate the post counts. It's unrelated to Gutenberg, so please disregard it.
- The Calypso Classic version has a [confirm dialog](https://github.com/Automattic/wp-calypso/blob/38897e746214c4536c0974d1df1dc4b3d2e73ada/client/post-editor/editor-delete-post/index.jsx#L64-L88). I've chosen not to port it over because Gutenberg doesn't have it, and I kinda agree with it. Trashing is not a destructive action, and users can safely restore the post immediately after trashing it.

Fixes #28813

### CODE REVIEW

File: client/gutenberg/editor/components/post-trash-link/index.js [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+ * Internal dependencies
+ */
+import { restorePost, trashPost } from 'state/posts/actions';
+import { navigate } from 'state/ui/actions';
+import { getSelectedSiteId } from 'state/ui/selectors';
+import getPostTypeTrashUrl from 'state/selectors/get-post-type-trash-url';
+
+export class PostTrashLink extends Component {
+	onClick = () => {
+		const { postId, siteId, trashUrl } = this.props;
```
Comment (mmtr) [inline client/gutenberg/editor/components/post-trash-link/index.js]: Any reason for not using the object destructuring as well for getting `trashPost` and `navigate`?

```suggestion
		const { navigate, postId, siteId, trashPost, trashUrl } = this.props;
```

File: client/gutenberg/editor/components/post-trash-link/index.js [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+	};
+} )(
+	connect(
+		( state, { postType } ) => ( {
+			siteId: getSelectedSiteId( state ),
+			trashUrl: getPostTypeTrashUrl( state, postType ),
+		} ),
+		{
+			navigate,
+			restorePost,
```
Comment (mmtr) [inline client/gutenberg/editor/components/post-trash-link/index.js]: This action is not used in the component.

File: client/gutenberg/editor/layout/index.jsx [hunk 3]
```diff
@@ -39,16 +56,24 @@ export class GutenlypsoLayout extends Component {
...
 		return {
+			editPost,
+			savePost,
 			updatePost,
 			resetBlocks,
 		};
 	} ),
-] )( GutenlypsoLayout );
+] )(
+	connect( ( state, { postType } ) => ( {
```
Comment (mmtr) [inline client/gutenberg/editor/layout/index.jsx]: You can include the `connect` call as the third argument of the `compose` class, which turns into more readable code.

Note that you can use both 3 arguments or a single array argument:

3 arguments:
```js
export default compose(
	withSelect(...),
	withDispatch(...),
	connect(...)
)( GutenlypsoLayout );
```
Single array argument
```js
export default compose( [
	withSelect(...),
	withDispatch(...),
	connect(...),
] )( GutenlypsoLayout );
```

File: client/gutenberg/editor/components/post-trash-link/index.js (hunk 1 above)
Comment (Copons) [reply client/gutenberg/editor/components/post-trash-link/index.js]: It's just because they have the same names as their imports, and so they would then be `already declared in the upper scope. eslint(no-shadow)` 🙂

File: client/gutenberg/editor/components/post-trash-link/index.js (hunk 2 above)
Comment (Copons) [reply client/gutenberg/editor/components/post-trash-link/index.js]: Great catch, I was sure I had removed all the leftovers!

File: client/gutenberg/editor/layout/index.jsx (hunk 3 above)
Comment (Copons) [reply client/gutenberg/editor/layout/index.jsx]: Wowee, thanks! I've never thought of that!
