### PR TITLE
Seller Experience: Copy fixes

### LINKED ISSUE #61009: Seller Experience: Minor copy fixes needed
Typo in this paragraph, "than" should be "then".

image

The headings at the store intent step "Start simple" and "More Power" are inconsistent about capitalization. We should pick one. :)

### PR DESCRIPTION
**Pull request by sixhours**
#### Changes proposed in this Pull Request

* Minor polish to copy; change "than" to "then", un-capitalize "power" in the heading.

**Before**

153462099-aa2f4a84-9faf-43b1-851f-3ae96b3e2bd0

**After**

Screen Shot 2022-02-14 at 11 33 14 AM

#### Testing instructions

* Switch to this PR, navigate to `/start?flags=seller-experience`, create a site
* At the intent step, choose Sell
* Check copy on the Simple vs. More power step

Fixes #61009

### CODE REVIEW

File: client/signup/steps/store-features/index.tsx [hunk 1]
```diff
@@ -103,7 +103,7 @@ export default function StoreFeaturesStep( props: Props ): React.ReactNode {
 		},
 		{
 			key: 'power',
-			title: translate( 'More Power' ),
+			title: translate( 'More power' ),
```
Comment (a8ci18n) [inline client/signup/steps/store-features/index.tsx:106]: :ok: This change will be queued for retranslation. We'll use the existing translations in the meantime.

File: client/signup/steps/store-features/index.tsx [hunk 2]
```diff
@@ -118,7 +118,7 @@ export default function StoreFeaturesStep( props: Props ): React.ReactNode {
 
 					<p>
 						{ translate(
-							'If you have multiple products or require extensive order and shipping management than this might suit your needs better.'
+							'If you have multiple products or require extensive order and shipping management then this might suit your needs better.'
```
Comment (a8ci18n) [inline client/signup/steps/store-features/index.tsx:121]: :warning: This change will be queued for retranslation. We'll display the English text until then.

**Review by kwight — APPROVED** [review]

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7142092

Thank you @sixhours for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7142092).
