### PR TITLE
Observe reopening of the settings popover

### LINKED ISSUE #83472: Loading Manage Patterns fails with iframe issues
### Quick summary

Menu items to manage patterns from inside the post-editor are broken, leading you to a browser error page.

#### Editor menu

1. (In firefox, ensuring you use the calypso rather than classic view to manage posts)
2. Go to the **post editor**
3. Click the three-dot/meatball menu at the top right
4. Click Manage patterns

#### Block-specific menu

1. (In firefox, ensuring you use the calypso rather than classic view to manage posts)
2. Go to the **post editor**
3. Insert a block
4. Click on the three-dot/meatball menu for that block
5. Click "Create pattern"
6. Fill out the form ensuring you create a synced pattern
7. The block will now be a pattern block, click on its three-dot/meatball menu
8. Click "Manage patterns"
9. The browser might (repeatedly) warn you about confirming you want to leave, choose leave page

### What you expected to happen

A page to load listing all of my patterns allowing me to manage them.

### What actually happened

The page displays a full screen iframe of `https://deantest772.wordpress.com/wp-admin/post-new.php?calypsoify=1&amp;block-editor=1&amp;frame-nonce=933a230d97&amp;origin=https%3A%2F%2Fwordpress.com&amp;environment-id=stage&amp;support_user=&amp;_support_token=&amp;in-editor-deprecation-group=1` but this is blocked from loading and instead displays:

> Firefox Can’t Open This Page
>
> To protect your security, deantest772.wordpress.com will not allow Firefox to display the page if another site has embedded it. To see this page, you need to open it in a new window.

Console says:
> The loading of “https://deantest772.wordpress.com/wp-admin/site-editor.php?path=%2Fpatterns” in a frame is denied by “X-Frame-Options“ directive set to “sameorigin“.

Clicking "open site in new window" opens https://deantest772.wordpress.com/wp-admin/site-editor.php?path=%2Fpatterns

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple (haven't tested atomic).

It's likely a wpcom specific problem due to the way we iframe the editor.

### Logs or notes

The work around is to ignore the scary text and press the button saying "Open site in new window", it's easily done but the browser warning looks scary and we look broken.

See conversation at p1698185155235349-slack-C0160HSMDQV

Only tested in Firefox, but probably a problem in other browsers too.

### PR DESCRIPTION
**Pull request by lsl**
Related to https://github.com/Automattic/wp-calypso/issues/91796
Fixes https://github.com/Automattic/wp-calypso/issues/83472

## Proposed Changes

* Ensures observation continues on secondary menu clicks

## Testing Instructions
* Sync changes running `install-plugin.sh wpcom-block-editor update/observerobserver` 
* Sandbox `widgets.wp.com`
* Create a new post from `https://wordpress.com/post/{ SITE SLUG }` with a site using the Default admin style
* Open the editor options from the three dots menu on the top right
* Close it and open it again to trigger a re-render
* Click on "Manage Patterns"

Screenshot 2567-08-23 at 17 57 00

* Expect to see the pattern manager

Screenshot 2567-08-23 at 17 55 19

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js [hunk 1]
```diff
@@ -718,8 +723,21 @@ async function openLinksInParentFrame( calypsoPort ) {
...
+				}
+				if ( node?.classList?.contains( 'components-popover__fallback-container' ) ) {
+					popoverSlotObserver.observe( node, { childList: true } );
+				}
+			}
+		}
+	} );
+	const htmlBody = document.querySelector( 'body' );
+	htmlBody && popoverSlotObserver.observe( htmlBody, { childList: true } );
+	htmlBody && popoverSlotObserverObserver.observe( htmlBody, { childList: true } );
```
Comment (lsl) [inline apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]: Review note: Both are required, the first should only be getting ~called~ observed once due to `components-popover__fallback-container` only being inserted once.

Skipping the first means it never observes the initial link inserts, you need to close and reopen to see updated links.

Skipping the second means it never observes the secondary link inserts, you don't see the updated link on reopen.

Comment (arthur791004) [reply apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]: I think we have lots of assumptions here such as 
* The popover component would be inserted into an element under the body
* The `.components-popover__fallback-container` element might be the element to be inserted

How about just copying [these lines](https://github.com/WordPress/gutenberg/blob/8ba6b11fba4e12bec3ad6174886fbcc8a97a0094/packages/components/src/popover/index.tsx#L97-L109) and calling `getPopoverFallbackContainer` to get the container and observe its child list to make it simple?

Comment (miksansegundo) [reply apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]: I'm trying this idea now and will take over the PR.

**Comment by miksansegundo** [comment]
When testing, I can no longer see the "refused to connect" error because the Manage Patterns link is not changing after opening twice the Editor Options menu.

The URL is always `https://wordpress.com/types/wp_block/{ SITE SLUG }` which works well in the iframe.

This PR is meant to fix the case when the Manage Patterns link is `{ SITE }/wp-admin/site-editor.php?path=%2Fpatterns`

File: apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js [hunk 2]
```diff
@@ -700,12 +715,16 @@ async function openLinksInParentFrame( calypsoPort ) {
 					continue;
 				}
 
-				const popoverSlot = node.querySelector( '.components-popover' );
+				// The popoverSlotObserver will observe addedNodes containing components-popover node elements
+				const popoverSlot = node?.classList?.contains( 'components-popover' )
+					? node
+					: node.querySelector( '.components-popover' );
```
Comment (lsl) [inline apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]: I suspect this isn't necessary when using the getPopoverFallbackContainer approach.

File: apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js (hunk 1 above)
Comment (lsl) [reply apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]: Thanks for the suggestion, this simplifies things a bit!

**Review by arthur791004 — APPROVED** [review]
Works well 🎉
