### PR TITLE
Editor/CPT: Display dialog when user cannot edit posts

### LINKED ISSUE #5398: CPT: Capability Checks Needed on Listing / Editor Routes
Currently users with "contributor" capabilities on sites are able to manually navigate to CPT listing pages ( i.e. `/types/jetpack-testimonial/{site.slug}` and the listing will render.  Worth noting that the API currently will return a post list for a given content type like this, but it will *only* return published items - drafts are omitted and this _feels_ like the proper way to handle this.

Additionally, you can also manually pull up an editor route in calypso for a CPT as a contributor, even if your role is not permitted to do so.  For example, the editor will render at `/edit/jetpack-portfolio/{site.slug}` for a contributor, but any POSTs to the API to save a draft or submit a draft for review will fail.

In contrast, these actions wp-admin are greeted with the "Cheatin’ uh?" message.

A few routes to fix this issue in calypso could be:

- Allow post type listing for contributors, but only show publicized items.  But disable all edit options from this view.
- Disable the post type listing for contributors all together - like wp-admin does.

And in either scenario, we should probably not render the editor for users without the proper capabilities.

### PR DESCRIPTION
**Pull request by aduth**
Fixes #5398
Related: #5598
Concepts: https://github.com/Automattic/wp-calypso/pull/5598#issuecomment-222169832

This pull request seeks to display a warning dialog when the user attempts to navigate to the editor for a post type for which they do not have access to edit.

Before|After
---|---
Before|After

__Testing instructions:__

1. Switch to a user with "Contributor" role on a site
2. Navigate to the [page editor](http://calypso.localhost:3000/page)
3. If prompted, select the site on which the user is a contributor
4. Note that you are prompted with a warning that you do not have access to edit this type (since contributors lack `edit_pages` capability)

Test live: https://calypso.live/?branch=update/editor-cpt-forbidden

### CODE REVIEW

File: client/post-editor/editor-forbidden/index.jsx [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+/**
+ * Internal dependencies
+ */
+import { localize } from 'i18n-calypso';
+import { getSelectedSiteId } from 'state/ui/selectors';
+import { getEditorPostId } from 'state/ui/editor/selectors';
+import { getEditedPostValue } from 'state/posts/selectors';
+import { getPostType } from 'state/post-types/selectors';
+import { getSiteSlug } from 'state/sites/selectors';
+import { canCurrentUser } from 'state/current-user/selectors';
```
Comment (timmyc) [inline client/post-editor/editor-forbidden/index.jsx]: so.much.selector.

**Comment by timmyc** [comment]
Working well for me, after a rebase should be good to 🚢

File: client/post-editor/editor-forbidden/index.jsx (hunk 1 above)
Comment (aduth) [inline client/post-editor/editor-forbidden/index.jsx]: >so.much.selector.

Will hopefully be less of an eye-sore soon! #5954
