### PR TITLE
Framework: Only persist state for logged-in users

### LINKED ISSUE #11766: Themes: Logging in, then back out gives empty site selector dropdown on attempted activation
Reported by @lancewillett in D4604-code:

#### Steps to reproduce
* Log into Calypso, then log out
* Go to https://wordpress.com/theme/sela
* When the page first loads, you'll see "Pick this design" — but the button changes quickly to "Activate this design"
* Click activate

#### What I expected

The button to be labelled "Pick this design", and clicking it to direct me to signup (with that theme preselected).

#### What happened instead

I got the Themes Site Selector Modal with an empty dropdown of sites.

#### Screenshot / Video

https://cloudup.com/c7-RTG9mqgH

### PR DESCRIPTION
**Pull request by seear**
Fixes #11766

Only ever read or write persistent state if a user is logged-in, and key the store by user ID to prevent any cross-contamination.

**To Test**
* Log in and out, checking the `calypso_store` in IndexedDB in the browser.
* The `redux-state` item should now be `redux-state-{userId}` when logged in
* When logged out that item should not be present

### CODE REVIEW

File: client/state/initial-state.js [hunk 1]
```diff
@@ -88,11 +90,23 @@ export function persistOnChange( reduxStore, serializeState = serialize ) {
...
 }
 
+/**
+ * Removes redux state change listener, cancels any pending writes,
+ * and clears all persisted state.
+ *
+ * @param {function} onClear function to call on clearing of persisted state
+ */
+export function shutdown( onClear ) {
+	unsubscribe();
```
Comment (gwwar) [inline client/state/initial-state.js]: I'm not sure this would work with our throttle usage in `initial-state`. How about checking for if the user is logged out and then returning early in throttledSaveState?

**Comment by seear** [comment]
>  How about checking for if the user is logged out and then returning early in throttledSaveState?

Yeah, that is better.

Although, I'm wondering now if the user id should be part of the key, for example `redux-state-9284730`, since we never want users to share persisted state?

**Comment by gwwar** [comment]
> Although, I'm wondering now if the user id should be part of the key, for example redux-state-9284730

Yeah that'd work too 👍  We'd still want to clear the persisted value on logout though even if we namespace

File: client/state/initial-state.js [hunk 2]
```diff
@@ -94,8 +104,10 @@ export function persistOnChange( reduxStore, serializeState = serialize ) {
 }
 
 export default function createReduxStoreFromPersistedInitialState( reduxStoreReady ) {
-	if ( config.isEnabled( 'persist-redux' ) && ! isSupportUserSession() ) {
-		localforage.getItem( 'redux-state' )
+	if ( config.isEnabled( 'persist-redux' ) && isLoggedIn() && ! isSupportUserSession() ) {
+		// clear storage any storage that used the old-style key
+		localforage.removeItem( 'redux-state' );
```
Comment (seear) [inline client/state/initial-state.js]: @gwwar Do you think we need this line to remove old-style storage? Better to do this somewhere else?

Comment (gwwar) [inline client/state/initial-state.js]: Hmm, perhaps use https://localforage.github.io/localForage/#data-api-clear ? The only other thing we're storing with localForage at the moment is the sync-handler which basically just caches some post list data. I can't think of a good reason for that to stick around when people log out.

**Comment by seear** [comment]
> Hmm, perhaps use https://localforage.github.io/localForage/#data-api-clear ? 

Yes, that is tidier. Done in 416a22d.

Ok, I think this could be ready to go. Biggest risk with this PR is that all users logging in after deployment will have no persisted state. I'll post to WHTA p2 to alert HEs.

Any extra testing we should be doing?

**Comment by gwwar** [comment]
> Any extra testing we should be doing?

Probably double checking that `su` still works. I'll let you know what I find.

File: client/state/initial-state.js [hunk 3]
```diff
@@ -67,18 +69,26 @@ function loadInitialStateFailed( error ) {
 	return createReduxStore();
 }
 
+function isLoggedIn() {
+	return !! user.get() && user.get().ID;
```
Comment (gwwar) [inline client/state/initial-state.js]: Maybe do user.get() once and store the result in a const.

**Comment by seear** [comment]
@gwwar thanks for your help with this one.

**Comment by bisko** [comment]
This PR explicitly breaks Signup's `Resume` functionality, where a user can leave at any point and resume to Signup at a later point, starting from where they left off. 

With the merge of #6124, part of Signup's data is being saved to the Redux state. 

The idea behind that change was to start moving Signup away from Flux and `localStorage` and move the data to Redux, where we have better means to work with it. 

Unfortunately this change completely destroys this functionality, since the user is not logged in until they finish signing up completely.

To test:

1. Start signup at `/start`, e.g. `https://wordpress.com/start`
2. Fill up information about your site until you reach the User information step ( `username`, `password`, `e-mail` )
3. Refresh the page.
4. _Previously filled state is gone by this point_
5. Fill up user details
6. Submit
7. You're stuck without any ability to continue

Right now the user is resumed to their last not-completed step, because there is still code in Signup that uses `localStorage`, but the important data is inside Redux, which means that the users who start, go away/refresh and then return are left in this non-working state, which is sub-optimal experience. We want to offer them a consistent experience no matter where they leave Signup.

This will possibly affect the Desktop app too, but I haven't tested it ( not sure how to approach that ).

If it is decided to keep this behavior, it will surely affect, or make impossible, future Signup improvements ( p5XAZ9-1qm-p2 ).

Also it will possibly hinder transitioning from logged-out to logged-in state in Calypso when we come to that point ( Right now the whole Calypso has to be reloaded in order to correctly load the new user information. More information in my comment here: p7rd6c-AM-p2 ). 

This wasn't caught as there aren't tests that cover resuming Signup flows. 

Kudos to @Tug who pointed me to that change in our discussion in #10738.

CC: @seear @gwwar @lancewillett @folletto

**Comment by folletto** [comment]
Can you open it as a separate issue? I think it's better than adding a comment on a closed PR as it make it findable and allows the discussion to be clearly dedicated to that.

**Comment by seear** [comment]
@bisko I'm not familiar with the details of how signup resume works, but we could possibly fix it by tweaking the persistence behaviour so that logged-out data is persisted again, just without a user id suffix. This would still leave complications when transitioning from logged-out to logged-in.

I do think that any logged-in persisted data should continue to be keyed by user id to prevent sharing of data between accounts.

**Comment by gwwar** [comment]
> You're stuck without any ability to continue

@bisko Persistence is just an enhancement. Any of our flows should work with persistence turned off, as certain browsers will not support it. (Think incognito safari) You can test this locally by  `DISABLE_FEATURES=persist-redux make run`

With that said, I think there's a fair use case to store some state locally for logged out folks. We could try to update the redux system, or if you really need a custom solution, one option is to use the `localForage` lib directly so you have more control over how things are cached, and expunged.

If we update redux, I'd recommend prefixing either with `logged out` or one of the identifying uids we assign to anon folks on the wordpress/api cookie. It's been a while but I think the value is `tk_tc`.
