### PR TITLE
Plugins: add HOC to handle plugin redirect

### LINKED ISSUE #17686: Plugins: Install button missing from plugins page after initial AT plugin installation
#### Steps to reproduce
1. On a new site with a business plan, add a plugin (ex: WooCommerce)
2. Wait while the plugin installs
3. When the "Activating plugin" message appears, navigate away from the plugins page (ex: stats) 
4. Navigate back to the plugins page by clicking "Add" 
5. Click on any other uninstalled plugin to view the plugin details 
6. The install button is not available on the plugins page 

The install button is not available on any subsequent plugins page. The only thing that brings the Install button back is a hard refresh on the page (cmd+shift+R)

#### What I expected
That the Install button would be available on any plugins page 

#### What happened instead
The install button disappears after the installation of the first plugin on a new site that just went through AT

#### Browser / OS version
Chrome / Mac OS

#### Screenshot / Video
screen shot 2017-08-31 at 4 31 58 pm

### LINKED ISSUE #51327: Plugins: WooCommerce onboarding does not launch after installation
### Steps to reproduce the behavior

1. Go to plugins screen in Calypso
2. Install WooCommerce

#### What I expected to happen

One of the following options

1. That I be directed automatically to the WooCommerce Onboarding flow similar to actions in the Ecommerce Plan on WP.com or when installing Woo on a self-hosted site.
2. That I am offered direction via the UI on how to get to the Onboarding flow.

#### What actually happened

I was left on this screen after installation.

image

### LINKED ISSUE #52539: Plugin install button appears clickable during the installation process
### Steps to reproduce the behavior

1. On a newly created business site, install the WooCommerce plugin
2. During installation, observe that the button still appears clickable.

https://user-images.githubusercontent.com/10274366/116947587-2ba9b900-ac4b-11eb-9ba9-87e1ec271439.mov

#### What I expected to happen

Ideally the cursor would change to show that the button shouldn't be clicked, and one of two things: 

1. The install button could appear gray, and show a cursor indicating the button is not clickable.
2. The button could show an animation like [some of our other buttons do](https://user-images.githubusercontent.com/10274366/116947720-804d3400-ac4b-11eb-9c7d-68165d3ab688.mov):

#### What actually happened

The install button is unchanged.

### PR DESCRIPTION
**Pull request by retrofox**
#### Changes proposed in this Pull Request

This PR is a different approach to handle when the client should redirect once some plugins are installed on the site.
Almost all logic is handled by the `withPluginRedirect()` HOC, which wraps the `<PluginMeta />` component.
It supports the `WooCommerce` plugin redirection so far, but it gets almost everything ready to extend its functionality to scale to other plugins that require dealing with similar behavior.

Fixes #51327 #17686 https://github.com/Automattic/wp-calypso/issues/52539

#### Testing instructions

Test with **Jetpack** and **Atomic** site

* Go to WooCommerce plugin page in calypso: `<hostname>/plugins/woocommerce/<site-id>`

Screen Shot 2021-04-26 at 9 30 50 AM

* Click on the Install button to trigger the install process.
* Once the plugin is installed, the app should show the first success notice:

* then, seconds after it should show another success message

* From here, confirm you have 5 seconds to cancel the redirect by clicking on the `Cancel` button.
* Confirm that after fice seconds, the client performs a redirect to the WooCommerce Wizard page.

Screen Shot 2021-04-26 at 9 34 57 AM

### Jetpack site

https://user-images.githubusercontent.com/77539/116469530-a8522700-a848-11eb-8f59-30083ee73c22.mov

### Atomic site
https://user-images.githubusercontent.com/77539/116469456-91133980-a848-11eb-9381-5c2f2a4bbed9.mov

*

Related to #

### CODE REVIEW

File: client/my-sites/plugins/plugin-install-button-wpcom/index.jsx [hunk 1]
```diff
@@ -56,9 +57,11 @@ export const WpcomPluginInstallButton = ( props ) => {
 		}
 	}
 
+	const label = isTransferring ? translate( 'Installing…' ) : translate( 'Install' );
```
Comment (pablinos) [inline client/my-sites/plugins/plugin-install-button-wpcom/index.jsx:60]: I'm not seeing this change while the site is transferring

image

File: client/my-sites/plugins/with-plugin-redirect.js [hunk 2]
```diff
@@ -0,0 +1,150 @@
...
+ */
+function getPluginRedirectUrl( slug ) {
+	if ( Object.keys( redirectingPluginsList ).indexOf( slug ) < 0 ) {
+		return false;
+	}
+
+	return redirectingPluginsList[ slug ];
+}
+
+const withPluginRedirect = ( Component ) => ( props ) => {
```
Comment (pablinos) [inline client/my-sites/plugins/with-plugin-redirect.js]: As this is using hooks internally, should we change it to a custom hook? `usePluginRedirect` perhaps?

File: client/my-sites/plugins/with-plugin-redirect.js [hunk 3]
```diff
@@ -0,0 +1,150 @@
...
+					translate( 'Redirecting to the %(pluginName)s onborading page in five seconds.', {
+						args: {
+							pluginName,
+						},
+					} ),
+					{
+						duration: 5000,
+						button: translate( 'Cancel' ),
+						id: 'plugin-redirect-notice',
+						onClick: function () {
```
Comment (pablinos) [inline client/my-sites/plugins/with-plugin-redirect.js]: I'm wondering about accessibility here. Can it be cancelled using the escape key for example? Should we also have a 'redirect now' link, or make part of the text a link, so you don't have to wait? With that, we could extend the delay too.

File: client/my-sites/plugins/with-plugin-redirect.js [hunk 4]
```diff
@@ -0,0 +1,150 @@
...
+			dispatch( removeNotice( 'plugin-notice' ) );
+
+			// re-use same timer ID to redirect the client.
+			timerId = setTimeout( () => {
+				window.location.href = url;
+			}, 5500 );
+
+			dispatch(
+				successNotice(
+					translate( 'Redirecting to the %(pluginName)s onborading page in five seconds.', {
```
Comment (pablinos) [inline client/my-sites/plugins/with-plugin-redirect.js]: There's a typo with 'onboarding', but should we mention onboarding at all? Maybe 'Redirecting to setup %{pluginName} in five seconds'?

**Review by pablinos — COMMENTED** [review]
This is working well for me. The redirect happens after a few seconds. I didn't end up in exactly the right place at one point, but I believe that was related to the setup of a support session interfering with the redirect.

I noticed that if I navigate away from the page, when I return for the first time, I'm prompted that the redirect will happen in 5 seconds. I think this is a good reason to have the delay, and not redirect immediately. 

I'm not sure if we should tackle it with this PR if it's a problem, but I think the routing isn't working correctly. If I go to `/plugins/woocommerce` without a site slug, I'm not getting the site selector.

File: client/my-sites/plugins/plugin-install-button-wpcom/index.jsx (hunk 1 above)
Comment (retrofox) [reply client/my-sites/plugins/plugin-install-button-wpcom/index.jsx:60]: Let me take a look.

File: client/my-sites/plugins/with-plugin-redirect.js (hunk 2 above)
Comment (retrofox) [reply client/my-sites/plugins/with-plugin-redirect.js]: yes, we can. Let me take a look.

File: client/my-sites/plugins/with-plugin-redirect.js (hunk 3 above)
Comment (retrofox) [reply client/my-sites/plugins/with-plugin-redirect.js]: I can dig into this, but I'm not sure whether is possible to add another button there. Also, we could do the opposite by providing a button to redirect instead.

File: client/my-sites/plugins/with-plugin-redirect.js (hunk 4 above)
Comment (retrofox) [reply client/my-sites/plugins/with-plugin-redirect.js]: sounds better to me. Also, let's make define it in the plugins list object.

File: client/my-sites/plugins/plugin.jsx [hunk 5]
```diff
@@ -246,6 +246,7 @@ class SinglePlugin extends React.Component {
 						isPlaceholder
 						isInstalledOnSite={ this.isPluginInstalledOnsite() }
 						plugin={ this.getPlugin() }
+						pluginSlug={ this.props.pluginSlug }
```
Comment (tyxla) [inline client/my-sites/plugins/plugin.jsx]: Do we really need this new prop? Isn't the plugin slug part of the `plugin` prop as received from `this.getPlugin()`?

File: client/my-sites/plugins/with-plugin-redirect.js (hunk 3 above)
Comment (retrofox) [reply client/my-sites/plugins/with-plugin-redirect.js]: > This is working well for me. The redirect happens after a few seconds. I didn't end up in exactly the right place at one point, but I believe that was related to the setup of a support session interfering with the redirect.

what was the url?


> I noticed that if I navigate away from the page, when I return for the first time, I'm prompted that the redirect will happen in 5 seconds. I think this is a good reason to have the delay, and not redirect immediately.

In theory, when the redirection should be canceled when the PluginMeta is unMounted. Let me check it.


> I'm not sure if we should tackle it with this PR if it's a problem, but I think the routing isn't working correctly. If I go to `/plugins/woocommerce` without a site slug, I'm not getting the site selector.

Weird. Not related to this PR if I'm not wrong, though.

File: client/my-sites/plugins/with-plugin-redirect.js (hunk 2 above)
Comment (tyxla) [inline client/my-sites/plugins/with-plugin-redirect.js]: FWIW for new HoCs we've been using `createHigherOrderComponent` from `@wordpress/compose` recently.

File: client/my-sites/plugins/with-plugin-redirect.js [hunk 6]
```diff
@@ -0,0 +1,150 @@
...
+import { getSelectedSite } from 'calypso/state/ui/selectors';
+import { isJetpackSite, getSiteWoocommerceWizardUrl } from 'calypso/state/sites/selectors';
+import { isPluginActionCompleted } from 'calypso/state/plugins/installed/selectors';
+import { INSTALL_PLUGIN } from 'calypso/lib/plugins/constants';
+import getSiteConnectionStatus from 'calypso/state/selectors/get-site-connection-status';
+import { getAutomatedTransferStatus } from 'calypso/state/automated-transfer/selectors';
+import { transferStates } from 'calypso/state/automated-transfer/constants';
+import { successNotice, removeNotice } from 'calypso/state/notices/actions';
+
+// Plugins list that should perfomr a redirect
```
Comment (tyxla) [inline client/my-sites/plugins/with-plugin-redirect.js]:
```suggestion
// List of plugins that should perform a redirect
```

File: client/my-sites/plugins/with-plugin-redirect.js [hunk 7]
```diff
@@ -0,0 +1,150 @@
...
+// once it's installed.
+const redirectingPluginsList = {
+	woocommerce: getSiteWoocommerceWizardUrl,
```
Comment (tyxla) [inline client/my-sites/plugins/with-plugin-redirect.js]: This can get messy if the selector needs additional arguments, but since it doesn't right now, we could keep it simple for now.

File: client/my-sites/plugins/with-plugin-redirect.js [hunk 8]
```diff
@@ -0,0 +1,150 @@
...
+};
+
+/**
+ * Return the handler function to get the plugin redirect URL.
+ *
+ * @param {string} slug - Plugin slug.
+ * @returns {Function|boolean} Selector handler if the plugin should redirect. Otherwise, False.
+ */
+function getPluginRedirectUrl( slug ) {
+	if ( Object.keys( redirectingPluginsList ).indexOf( slug ) < 0 ) {
```
Comment (tyxla) [inline client/my-sites/plugins/with-plugin-redirect.js]: I think we can simplify this with `Object.prototype.hasOwnProperty`:

```suggestion
	if ( redirectingPluginsList.hasOwnProperty( slug ) ) {
```

File: client/my-sites/plugins/with-plugin-redirect.js [hunk 9]
```diff
@@ -0,0 +1,150 @@
...
+		return false;
+	}
+
+	return redirectingPluginsList[ slug ];
+}
+
+const withPluginRedirect = ( Component ) => ( props ) => {
+	const { plugin = {} } = props;
```
Comment (tyxla) [inline client/my-sites/plugins/with-plugin-redirect.js]: Won't `plugin` be a new object on every re-render that way? Should we declare the default property as a constant outside of the component declaration, and use that instead of defining a new empty object every time?

File: client/my-sites/plugins/with-plugin-redirect.js [hunk 10]
```diff
@@ -0,0 +1,150 @@
...
+	if ( ! redirectUrlHandler ) {
+		return <Component { ...props } />;
+	}
+
+	const translate = useTranslate();
+	const dispatch = useDispatch();
+
+	const { redirect, url, hasSiteBeenTransferred } = useSelector(
+		( state ) => {
+			const site = getSelectedSite( state );
```
Comment (tyxla) [inline client/my-sites/plugins/with-plugin-redirect.js]: If we only need the selected site ID, perhaps we can use the `getSelectedSiteId` selector instead?

File: client/my-sites/plugins/with-plugin-redirect.js [hunk 11]
```diff
@@ -0,0 +1,150 @@
...
+				pluginSlug === 'woocommerce' &&
+				woocommerceWizardUrl &&
+				hasPluginJustBeenInstalled &&
+				isSiteConnected
+			) {
+				return { ...selectedData, redirect: true };
+			}
+
+			// Atomic Site.
+			if (
```
Comment (tyxla) [inline client/my-sites/plugins/with-plugin-redirect.js]: This condition looks very similar to the one for Jetpack sites. What we return is also the same for both cases. Do you think it makes sense to combine them into one?

File: client/my-sites/plugins/with-plugin-redirect.js [hunk 12]
```diff
@@ -0,0 +1,150 @@
...
+	const pluginName = plugin?.name;
+
+	useEffect( () => {
+		if ( ! redirect || ! url || ! pluginName ) {
+			return;
+		}
+
+		const pluginInstalledNoticeTime = hasSiteBeenTransferred ? 0 : 3000;
+
+		let timerId = setTimeout( () => {
```
Comment (tyxla) [inline client/my-sites/plugins/with-plugin-redirect.js]: Any reason to prefer `setTimeout` vs `requestAnimationFrame`?

File: client/my-sites/plugins/with-plugin-redirect.js [hunk 13]
```diff
@@ -0,0 +1,150 @@
...
+			dispatch( removeNotice( 'plugin-notice' ) );
+
+			// re-use same timer ID to redirect the client.
+			timerId = setTimeout( () => {
+				window.location.href = url;
+			}, 5500 );
```
Comment (tyxla) [inline client/my-sites/plugins/with-plugin-redirect.js]: What's the rationale behind the timing choice here?

File: client/state/plugins/installed/selectors.js [hunk 14]
```diff
@@ -210,6 +210,19 @@ export function isPluginActionInProgress( state, siteId, pluginId, action ) {
...
+/**
+ * Whether the plugin's status for one or more recent actions is completed.
+ *
+ * @param  {object}       state    Global state tree
+ * @param  {number}       siteId   ID of the site
+ * @param  {string}       pluginId ID of the plugin
+ * @param  {string|Array} action   Action, or array of actions of interest
+ * @returns {boolean}              True if one or more specified actions are completed, false otherwise.
+ */
+export function isPluginActionCompleted( state, siteId, pluginId, action ) {
```
Comment (tyxla) [inline client/state/plugins/installed/selectors.js:222]: I'd say that if we only use this once, we might as well just use the `isPluginActionStatus` selector.

File: client/state/sites/selectors/get-site-woocommerce-wizard-url.js [hunk 15]
```diff
@@ -0,0 +1,20 @@
...
+ */
+import getSiteAdminUrl from './get-site-admin-url';
+
+/**
+ * Returns a site's wp-admin WooCommerce Wizrd plugin URL,
+ * or null if the admin URL for the site cannot be determined.
+ *
+ * @param  {object}  state  Global state tree
+ * @param  {number}  siteId Site ID
+ * @returns {?string}       Full URL to WooCommerce Aizard plugin in wp-admin
```
Comment (tyxla) [inline client/state/sites/selectors/get-site-woocommerce-wizard-url.js]:
```suggestion
 * @returns {?string}       Full URL to WooCommerce Wizard plugin in wp-admin
```

File: client/state/sites/selectors/get-site-woocommerce-wizard-url.js [hunk 16]
```diff
@@ -0,0 +1,20 @@
+/**
+ * Internal dependencies
+ */
+import getSiteAdminUrl from './get-site-admin-url';
+
+/**
+ * Returns a site's wp-admin WooCommerce Wizrd plugin URL,
```
Comment (tyxla) [inline client/state/sites/selectors/get-site-woocommerce-wizard-url.js]:
```suggestion
 * Returns a site's wp-admin WooCommerce Wizard plugin URL,
```

File: client/state/sites/selectors/get-site-woocommerce-wizard-url.js [hunk 17]
```diff
@@ -0,0 +1,20 @@
+/**
+ * Internal dependencies
+ */
+import getSiteAdminUrl from './get-site-admin-url';
```
Comment (tyxla) [inline client/state/sites/selectors/get-site-woocommerce-wizard-url.js]: I'd suggest using the full path to the selector here. We tend to move those a lot, and absolute paths are much easier to update than relative ones 😅

**Review by tyxla — COMMENTED** [review]
I haven't tested this, but the overall approach seems good to me 👍 

I've left some comments and questions, let me know what you think.

File: client/my-sites/plugins/plugin.jsx (hunk 5 above)
Comment (retrofox) [reply client/my-sites/plugins/plugin.jsx]: Correct. Updating...

File: client/my-sites/plugins/with-plugin-redirect.js (hunk 6 above)
Comment (retrofox) [reply client/my-sites/plugins/with-plugin-redirect.js]: going to update but from my local since I added some changes there. 🙇‍♂️

File: client/my-sites/plugins/with-plugin-redirect.js (hunk 7 above)
Comment (retrofox) [reply client/my-sites/plugins/with-plugin-redirect.js]: 👍

File: client/my-sites/plugins/with-plugin-redirect.js (hunk 8 above)
Comment (retrofox) [reply client/my-sites/plugins/with-plugin-redirect.js]: <3

File: client/my-sites/plugins/with-plugin-redirect.js (hunk 2 above)
Comment (retrofox) [reply client/my-sites/plugins/with-plugin-redirect.js]: Let's tackle it in a follow-up PR. The main reason why we use a HOC is that the `<PluginMeta />` is not a functional component

File: client/my-sites/plugins/with-plugin-redirect.js (hunk 9 above)
Comment (retrofox) [reply client/my-sites/plugins/with-plugin-redirect.js]: yes... I got a little bit confused. But let's make the HOC expect the `plugin` object prop.

File: client/my-sites/plugins/with-plugin-redirect.js (hunk 11 above)
Comment (retrofox) [reply client/my-sites/plugins/with-plugin-redirect.js]: :+1: I did significant changes and I think it's handled clearer.

File: client/my-sites/plugins/with-plugin-redirect.js (hunk 13 above)
Comment (retrofox) [reply client/my-sites/plugins/with-plugin-redirect.js]: we should the Notice for 5 seconds... so make the redirect 500ms after the notification get out.

File: client/state/plugins/installed/selectors.js (hunk 14 above)
Comment (retrofox) [reply client/state/plugins/installed/selectors.js:222]: I'm trying to be consistent with the code. There is not any call to `isPluginActionStatus()` out of the selectors context. `isPluginActionCompleted` was inspired on `isPluginActionInProgress`. I prefer keeping this selector, but I don't have s strong opinion about not removing it though. Please can you confirm removing it?

File: client/my-sites/plugins/plugin-install-button-wpcom/index.jsx (hunk 1 above)
Comment (retrofox) [reply client/my-sites/plugins/plugin-install-button-wpcom/index.jsx:60]: Fixed

File: client/my-sites/plugins/with-plugin-redirect.js [hunk 18]
```diff
@@ -0,0 +1,183 @@
+/**
+ * External dependencies
+ */
+import React, { useEffect, useRef, useState } from 'react';
+import { useSelector, useDispatch } from 'react-redux';
+import { useTranslate, translate as __ } from 'i18n-calypso';
```
Comment (tyxla) [inline client/my-sites/plugins/with-plugin-redirect.js]: Is there a good reason why we alias `translate` to `__` here? I think it can be confusing and someone could think we're using `@wordpress/i18n` instead.

File: client/my-sites/plugins/with-plugin-redirect.js [hunk 19]
```diff
@@ -0,0 +1,183 @@
...
+const redirectingPluginsList = {
+	woocommerce: {
+		name: 'WooCommerce',
+		message: __( 'Redirecting to setup WooCommerce in five seconds.' ),
+		handler: getSiteWoocommerceWizardUrl,
+	},
+};
+
+/**
+ * Return the redirec plugin object.
```
Comment (tyxla) [inline client/my-sites/plugins/with-plugin-redirect.js]:
```suggestion
 * Return the redirect plugin object.
```

File: client/state/plugins/installed/selectors.js (hunk 14 above)
Comment (tyxla) [reply client/state/plugins/installed/selectors.js:222]: I'm fine with keeping it if that's your preference, I have no strong feelings about removing it TBH 👍

File: client/my-sites/plugins/with-plugin-redirect.js [hunk 20]
```diff
@@ -0,0 +1,183 @@
...
+			/// there is not a Notice.
+			const pluginInstalledNoticeTime = hasSiteBeenTransferred ? 0 : 3000;
+
+			let timerId = setTimeout( () => {
+				dispatch( removeNotice( 'plugin-notice' ) );
+
+				// re-use same timer ID to redirect the client.
+				timerId = setTimeout( () => {
+					window.location.href = redirectTo;
+				}, 5500 );
```
Comment (tyxla) [inline client/my-sites/plugins/with-plugin-redirect.js]: Would be great if we add the `5000` to a `noticeDuration` variable, and then here we have `noticeDuration + 500`. That would definitely make it more clear about the intent and where this number is coming from.

File: client/my-sites/plugins/with-plugin-redirect.js [hunk 21]
```diff
@@ -0,0 +1,183 @@
...
+} from 'calypso/state/plugins/installed/selectors';
+import { INSTALL_PLUGIN } from 'calypso/lib/plugins/constants';
+import getSiteConnectionStatus from 'calypso/state/selectors/get-site-connection-status';
+import { getAutomatedTransferStatus } from 'calypso/state/automated-transfer/selectors';
+import { transferStates } from 'calypso/state/automated-transfer/constants';
+import { successNotice, removeNotice } from 'calypso/state/notices/actions';
+
+// List of plugins that should perform a redirect
+// once it's installed.
+const redirectingPluginsList = {
```
Comment (tyxla) [inline client/my-sites/plugins/with-plugin-redirect.js]: We could put those directly in the component. That way we could use the `translate()` from `useTranslate` directly.

File: client/my-sites/plugins/with-plugin-redirect.js [hunk 22]
```diff
@@ -0,0 +1,183 @@
...
+				const isInstalling = isPluginActionInProgress( state, siteId, pluginSlug, INSTALL_PLUGIN );
+				const hasBeenInstalled = isPluginActionCompleted(
+					state,
+					siteId,
+					pluginSlug,
+					INSTALL_PLUGIN
+				);
+
+				return {
+					hasSiteBeenTransferred: transferState === transferStates?.COMPLETE,
```
Comment (tyxla) [inline client/my-sites/plugins/with-plugin-redirect.js]: Seems to me that `transferStates` will always be an object, so we can safely access `.COMPLETE` without optional chaining.

File: client/my-sites/plugins/with-plugin-redirect.js [hunk 23]
```diff
@@ -0,0 +1,183 @@
...
+			return <Component { ...props } />;
+		}
+
+		const pluginSlug = plugin.slug;
+		const redirectPlugin = getPluginRedirect( pluginSlug );
+		if ( ! redirectPlugin ) {
+			return <Component { ...props } />;
+		}
+
+		const wasInstalling = useRef();
```
Comment (tyxla) [inline client/my-sites/plugins/with-plugin-redirect.js]: Is there a reason why this uses a ref and not state with `useState` like the one below?

File: client/my-sites/plugins/with-plugin-redirect.js [hunk 24]
```diff
@@ -0,0 +1,183 @@
...
+						id: 'plugin-redirect-notice',
+						onClick: function () {
+							timerId && window.clearTimeout( timerId );
+							dispatch( removeNotice( 'plugin-redirect-notice' ) );
+						},
+					} )
+				);
+			}, pluginInstalledNoticeTime );
+
+			return function () {
```
Comment (tyxla) [inline client/my-sites/plugins/with-plugin-redirect.js]: IMHO an arrow function here would make this shorter and more concise.

**Review by tyxla — COMMENTED** [review]
I've left some minor comments and questions here. I think it should be good to go once they're addressed, but don't see any big blockers, to be honest.

I haven't tested this, so if it works well in your testing and it doesn't break any of the existing plugin flows, feel free to ship 👍

File: client/my-sites/plugins/with-plugin-redirect.js (hunk 18 above)
Comment (retrofox) [reply client/my-sites/plugins/with-plugin-redirect.js]: in HOC, I created the `translate` form which was triggering a lint error. Let me update it.

File: client/my-sites/plugins/with-plugin-redirect.js (hunk 21 above)
Comment (retrofox) [reply client/my-sites/plugins/with-plugin-redirect.js]: sounds goot to me

Comment (retrofox) [reply client/my-sites/plugins/with-plugin-redirect.js]: Actually, I think it's ok keeping these data out of the component. I think it looks clearer and also allows us to move these data to another location, in case we want to do it.

Comment (retrofox) [reply client/my-sites/plugins/with-plugin-redirect.js]: moved 😅

File: client/my-sites/plugins/with-plugin-redirect.js (hunk 23 above)
Comment (retrofox) [reply client/my-sites/plugins/with-plugin-redirect.js]: we can use the state here too.

File: client/my-sites/plugins/with-plugin-redirect.js (hunk 20 above)
Comment (retrofox) [reply client/my-sites/plugins/with-plugin-redirect.js]: oh, sorry I opted to don't close the notification so the user will see it until it redirects

**Comment by retrofox** [comment]
I"m getting some CORB issue when trying to redirect once the Simple site has been transferred.

```
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://wooredirect24984401644.wpcomstaging.com/wp-admin/ with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

I'm digging on this now.

**Comment by retrofox** [comment]
> I"m getting some CORB issue when trying to redirect once the Simple site has been transferred.
> 
> ```
> Cross-Origin Read Blocking (CORB) blocked cross-origin response https://wooredirect24984401644.wpcomstaging.com/wp-admin/ with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
> ```
> 
> I'm digging on this now.

@tyxla @jsnajdr do you have any advice to deal with this issue? Not sure whether it's related to a security issue of maybe I'm doing something wrong.

**Comment by jsnajdr** [comment]
> I"m getting some CORB issue when trying to redirect once the Simple site has been transferred.

@retrofox This can happen when you load the `wpcomstaging.com/wp-admin` URL with a fetch/XHR request and then try to read the response body. Instead of just navigating to that URL. Does your code possibly do a `fetch` like that?

**Comment by retrofox** [comment]
> > I"m getting some CORB issue when trying to redirect once the Simple site has been transferred.
> 
> @retrofox This can happen when you load the `wpcomstaging.com/wp-admin` URL with a fetch/XHR request and then try to read the response body. Instead of just navigating to that URL. Does your code possibly do a `fetch` like that?

Thanks, Jarda.
It doesn't seem to be my case. I'll test again... but basically, it locks the app when trying to redirect to the wp-admin but using `window.location.href = redirectTo;`, [here](https://github.com/Automattic/wp-calypso/pull/52398/files#diff-ebe29c17f4cbaa5277eecdb0592c49a38d8562afcbda5947ad3bb480b71cc6d9R164)

**Comment by jsnajdr** [comment]
When you try to reproduce it next time, please find the `wp-admin` request in the Network devtool. What is the "Type" column? "document" or something else like "xhr"? And what is the "Initiator"?

Mere `window.location.href = redirectTo` shouldn't trigger the CORB error -- the blocking is done on other types of requests, like XHR from JavaScript or ``.

**Comment by retrofox** [comment]
I've refactored the code and now it works as expected. I was doing something wrong when redirecting.

File: client/my-sites/plugins/plugin-install-button-wpcom/index.jsx (hunk 1 above)
Comment (allilevine) [inline client/my-sites/plugins/plugin-install-button-wpcom/index.jsx:60]: This looks great, and may also fix https://github.com/Automattic/wp-calypso/issues/52539

Screen Shot 2021-05-17 at 2 46 46 PM

Comment (retrofox) [reply client/my-sites/plugins/plugin-install-button-wpcom/index.jsx:60]: Thanks. Issue linked.

File: client/my-sites/plugins/with-plugin-redirect/utils.js [hunk 25]
```diff
@@ -0,0 +1,46 @@
...
+
+/**
+ * Helper function that
+ * return the plugin redirect object.
+ *
+ * @param {string} slug - plugin  slug
+ * @returns {object} Redirect plugin object for the plugin, or False.
+ */
+export function getRedirectPluginHandler( slug ) {
+	if ( ! redirectingPluginsList.hasOwnProperty( slug ) ) {
```
Comment (pablinos) [inline client/my-sites/plugins/with-plugin-redirect/utils.js]: This is very minor, but do we care if the key has a falsey value here? If not, we could change this function to something like:

```js
return redirectingPluginList[ slug ] ?? false;
```

File: client/my-sites/plugins/with-plugin-redirect/index.js [hunk 26]
```diff
@@ -0,0 +1,190 @@
...
+							timerId && window.clearTimeout( timerId );
+							setPrevProcessingState( 'done' );
+							setShouldRedirect( null );
+							dispatch( removeNotice( 'plugin-redirect-notice' ) );
+						},
+					} )
+				);
+			}, pluginInstalledNoticeTime );
+
+			return () => timerId && window.clearTimeout( timerId );
```
Comment (pablinos) [inline client/my-sites/plugins/with-plugin-redirect/index.js]: Another minor thought, but are we guaranteed to have a value in `timerId` and so could remove `timerId &&`?

File: client/my-sites/plugins/with-plugin-redirect/index.js [hunk 27]
```diff
@@ -0,0 +1,190 @@
...
+				timerId = setTimeout( () => {
+					if ( ! window?.top.location.href ) {
+						return;
+					}
+
+					return ( window.location.href = shouldRedirect );
+				}, 6000 );
+
+				const redirectMessage =
+					redirectHandler.message ||
```
Comment (pablinos) [inline client/my-sites/plugins/with-plugin-redirect/index.js]: Should we put `redirectHandler.message` inside the call to `translate`?

File: client/my-sites/plugins/with-plugin-redirect/utils.js [hunk 28]
```diff
@@ -0,0 +1,46 @@
...
+ */
+export const redirectingPluginsList = {
+	woocommerce: {
+		name: 'WooCommerce',
+		message: translate( 'Redirecting to setup WooCommerce in five seconds.' ),
+		getUrl: getSiteWooCommerceWizardUrl,
+	},
+
+	'wordpress-seo': {
+		name: 'WooCommerce',
```
Comment (pablinos) [inline client/my-sites/plugins/with-plugin-redirect/utils.js]: This should probably be Yoast?

File: client/state/sites/selectors/get-site-wordpress-seo-wizard-url.js [hunk 29]
```diff
@@ -0,0 +1,16 @@
+/**
+ * Internal dependencies
+ */
+import getSiteAdminUrl from 'calypso/state/sites/selectors/get-site-admin-url';
+
+/**
+ * Returns a site's wp-admin WooCommerce Wizard plugin URL,
```
Comment (pablinos) [inline client/state/sites/selectors/get-site-wordpress-seo-wizard-url.js]: We should replace WooCommerce with Yoast or WordPress SEO in this file

**Review by pablinos — COMMENTED** [review]
This is working well for me. Just a couple of miner thoughts, but otherwise it's good to go

File: client/my-sites/plugins/with-plugin-redirect/index.js (hunk 27 above)
Comment (retrofox) [reply client/my-sites/plugins/with-plugin-redirect/index.js]: It's already translated when the string is defineded.

File: client/my-sites/plugins/with-plugin-redirect/utils.js (hunk 28 above)
Comment (retrofox) [reply client/my-sites/plugins/with-plugin-redirect/utils.js]: yeah :-(

File: client/state/sites/selectors/get-site-wordpress-seo-wizard-url.js (hunk 29 above)
Comment (retrofox) [reply client/state/sites/selectors/get-site-wordpress-seo-wizard-url.js]: yup! updating...

File: client/my-sites/plugins/with-plugin-redirect/index.js (hunk 27 above)
Comment (pablinos) [reply client/my-sites/plugins/with-plugin-redirect/index.js]: Ah, so it is. Do you think we should keep it in the same place? Also I notice that the messages are set to the default but with the plugin name embedded, we should probably just leave it to the default to reduce the number of translated strings.

File: client/my-sites/plugins/with-plugin-redirect/index.js [hunk 30]
```diff
@@ -0,0 +1,190 @@
...
+					translate( 'Redirecting to setup %{pluginName} in five seconds.', {
+						args: {
+							pluginName: redirectHandler.name,
```
Comment (pablinos) [inline client/my-sites/plugins/with-plugin-redirect/index.js]: Should we add the number of seconds as an argument too?

Comment (retrofox) [reply client/my-sites/plugins/with-plugin-redirect/index.js]: why should we do that, considering that the number of seconds is not a variable?

File: client/my-sites/plugins/with-plugin-redirect/index.js (hunk 27 above)
Comment (retrofox) [reply client/my-sites/plugins/with-plugin-redirect/index.js]: The idea behind this is to be able to set a custom message but it's totally optional. If for some reason the message is not defined, we can use the default value.

Comment (pablinos) [reply client/my-sites/plugins/with-plugin-redirect/index.js]: Yes, but the custom messages we have defined are currently just the default, but as the plugin name is in them, they will have to be translated as separate strings. Should we just remove those?

**Review by pablinos — APPROVED** [review]
Thanks for looking at those bits. This looks good to me!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5929875

Thank you @retrofox for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5929875).
