### PR TITLE
[Domains] Disable premium plan price popover

### LINKED ISSUE #24249: Pop-up to be removed from Domain Search Redesign
#### Steps to reproduce
1. Starting at URL: https://horizon.wordpress.com/start/domains
2. Domain results show a pop-up, coming from the previous interface.

#### What I expected

No pop-up, considering it was not present in any of the design wireframes.

#### Browser / OS version

Chrome and Safari. I guess, all browsers.

#### Screenshot / Video

screen shot 2018-04-17 at 13 31 27

#### Context / Source

#manual-testing

### PR DESCRIPTION
**Pull request by jsnmoon**
Fixes #24249.

This disables the premium plan popover for the domain registration price component. 

### Test instructions
1. Spin up this branch locally.
2. Navigate to `/start/domains`.
3. Enter a query. Ensure that hovering over `Price included in paid plans` does not trigger a popover.

### CODE REVIEW

File: client/components/domains/domain-product-price/index.jsx [hunk 1]
```diff
@@ -65,19 +65,24 @@ class DomainProductPrice extends React.Component {
 	renderIncludedInPremium() {
 		const { translate, showExpandedPrice } = this.props;
 
-		let textLabel = translate( 'Included in WordPress.com Premium' );
-
+		// TODO: When removing this flag, remember to remove PremiumPopover component
+		//       from the codebase.
 		const isKrackenUi = config.isEnabled( 'domains/kracken-ui' );
```
Comment (gwwar) [inline client/components/domains/domain-product-price/index.jsx]: For folks reading we can explicitly enable this feature flag with:
```
ENABLE_FEATURES=domains/kracken-ui npm start
```
And disable with:
```
DISABLE_FEATURES=domains/kracken-ui npm start
```

File: client/components/domains/domain-product-price/index.jsx [hunk 2]
```diff
@@ -65,19 +65,24 @@ class DomainProductPrice extends React.Component {
...
-		if ( isKrackenUi ) {
-			textLabel = showExpandedPrice
-				? translate( 'Price included in paid plans' )
-				: translate( 'Included in paid plans' );
-		}
+		const text = showExpandedPrice
```
Comment (gwwar) [inline client/components/domains/domain-product-price/index.jsx]: `includedInPlan` maybe?

File: client/components/domains/domain-product-price/index.jsx (hunk 1 above)
Comment (delputnam) [reply client/components/domains/domain-product-price/index.jsx]: TIL
