### PR TITLE
Goals first: Reset onboard store when entering the flow (v2)

### LINKED ISSUE #97887: Bug: Trying to create two sites in sequence in the new onboarding flow doesn't work
### Quick summary

Bug report: pdtkmj-3es-p2#comment-6077

### Steps to reproduce

Follow this video: 

https://github.com/user-attachments/assets/f0363164-17a9-4999-b6a2-b96a7d0d7d50

### What you expected to happen

When registering the second site, it should clear the previous domain selection so it will create a new domain instead of reusing the domain of the previous site.

### What actually happened

Since the domain from the recent created site was at the domain selection list, it tried to use the same domain for the new site and failed

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by candy02058912**
Supersedes #97936. Closes https://github.com/Automattic/wp-calypso/issues/97887.

## Proposed Changes

We kept the domain selection information in case the user wants to create a new site with their previously selected domain (that they haven't bought.) This is okay for paid domains (p1736205514246109/1736196927.663189-slack-C085HCWCEDN), but we were keeping it for free domains, which causes the issue https://github.com/Automattic/wp-calypso/issues/97887

* Reset the store/persisted step data when a user enters the flow
* Continue to reset the `ONBOARD_STORE` at the end of the flow

> [!NOTE]  
> Known issues to be addressed in separate PRs to keep each PR change contained
> If a paid domain is selected, the domain price may be wrong when reentering the flow: PR TBD

https://github.com/user-attachments/assets/a4ea6980-feb6-4ad6-8efb-309370dff4fd

## Why are these changes being made?

* Right now, it's impossible to create two sites through /setup/onboarding.

## Testing Instructions

Two entry points to test
`/start` and `/setup/onboarding` (/start should redirect to /setup/onboarding)

Scenarios to test
* Create two sites: Enter /setup/onboarding and create a site. Enter the flow again and create a second site. You should end up with two sites. Both sites can be launched from the launchpad.
* Paid plan (cancel): Create a site but select a paid plan, at checkout empty the cart, launch the site
* Paid plan: Create a site that requires a paid plan, checkout, launch the site
* Paid domain (cancel): Create a site and select a domain, go through the flow and empty cart when checkout, launch the site

Note: always test the flow end to end until the user can launch the site.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/landing/stepper/declarative-flow/site-setup-flow.ts [hunk 1]
```diff
@@ -247,7 +247,7 @@ const siteSetupFlow: Flow = {
 			navigate( 'processing' );
 
 			// Clean-up the store so that if onboard for new site will be launched it will be launched with no preselected values
-			resetOnboardStoreWithSkipFlags( [ 'skipPendingAction', 'skipIntent', 'skipSelectedDesign' ] );
+			resetOnboardStoreWithSkipFlags( [ 'skipPendingAction', 'skipIntent' ] );
```
Comment (candy02058912) [inline client/landing/stepper/declarative-flow/site-setup-flow.ts:250]: Context for removing `skipSelectedDesign`: p1736215217275209-slack-C085HCWCEDN

As for why remove the if statement that was originally in #97936:
In the previous PR (#97936), [we added an if statement to not reset store for the goals first flow at the end](https://github.com/Automattic/wp-calypso/pull/97936/files#diff-614cccce787b17e46e84a16af7865700992dfd374e701239023fd2e1feaa12a1R250-R253) because we were doing so when entering the flow and we wanted to keep the store resetting in either the start or the end of the flow.

This broke the Launch site button in the launchpad: p1736238320621649/1736196927.663189-slack-C085HCWCEDN

So here we'll still reset the store to avoid that.

**Review by paulopmt1 — COMMENTED** [review]
We are almost there @candy02058912!
Worked as expected:

- I can create multiple free sites in a row
- I bought the `tazza` theme with business plan and worked as expected
- I bought a personal theme with a personal plan 
- I started buying a personal plan and changed my mind in the checkout by going back and emptying the checkout

Two things are not working
- If we add a paid domain and get back to screen it doesn't show it's free ([we know how to fix it](https://github.com/Automattic/wp-calypso/pull/97936/commits/37a86e05890e3e390b0fa61b36082637615c2a92))
- I tried to buy a paid plan with a paid domain and it failed (will share the video on our slack thread)
