### PR TITLE
Seller Experience - Stepper: Redirect to the WC admin at the end of the woo flow

### LINKED ISSUE #63295: Woo on Stepper: Wrong redirection in the end
In the current `/start` flow the user is redirected to `wc-admin` when the flow ends successfully (something like this: `https://test468610507.wpcomstaging.com/wp-admin/admin.php?page=wc-admin`). In the `/setup` implementation we are getting redirected to `http://calypso.localhost:3000/home/test468610507.wordpress.com` instead.

### PR DESCRIPTION
**Pull request by markbiek**
#### Changes proposed in this Pull Request

Redirect to the WC admin at the end of the woo flow. Previously we redirected to `/home`

https://user-images.githubusercontent.com/917632/166747394-d0e998fe-8560-4bee-b1a9-52fabd6f2341.mp4

#### Testing instructions

1. Go to http://calypso.localhost:3000/start/?flags=stepper-woocommerce-poc
2. Go through the "Sell" intent and "More power" 
3. At the end of the process, you should be redirected to the wc admin page instead of `/home`

Fixes #63295

### CODE REVIEW

File: client/landing/stepper/declarative-flow/site-setup-flow.ts [hunk 1]
```diff
@@ -109,6 +109,8 @@ export const siteSetupFlow: Flow = {
 					// End of woo flow
 					if ( storeType === 'power' ) {
 						dispatch( recordTracksEvent( 'calypso_woocommerce_dashboard_redirect' ) );
+
+						return exitFlow( `https://${ siteSlug }/wp-admin/admin.php?page=wc-admin` );
```
Comment (andres-blanco) [inline client/landing/stepper/declarative-flow/site-setup-flow.ts]: In the `/start` framework a [specific selector](https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/steps/woocommerce-install/transfer/install-plugins.tsx#L39) is being used to assemble this url. Do we need to bring this over to the data-store?

Comment (markbiek) [reply client/landing/stepper/declarative-flow/site-setup-flow.ts]: Ah, didn't know about that! Let me look and see if it's something we need in the site data-store.

Comment (markbiek) [reply client/landing/stepper/declarative-flow/site-setup-flow.ts]: @andres-blanco I've got a new pr (#63305) which adds selectors for retrieving site options. I'll use those selectors to retrieve the admin url and assemble the url in the confirm step.

**Comment by markbiek** [comment]
@andres-blanco Not sure what's happening here as this was functioning yesterday.

Now, when I run through the Woo flow, the onboarding store loses the `storeType` so the flow doesn't exit in the correct place.

I may have to pick this back up next week.

**Comment by markbiek** [comment]
This should be ready to go!

**Comment by markbiek** [comment]
This all seems to be working properly now.

**Review by andres-blanco — APPROVED** [review]
This is working fine! Heads up with the CI checks that are failing
