### PR TITLE
The development label should be gated behind a feature flag

### LINKED ISSUE #93756: `Development` label shown in A4A dashboard for all sites
### Quick summary

The issue was reported by p1724198541780969-slack-C06JY8QL0TU All sites in the A4A dashboard and shown with a `Development` badge. 

image

### Steps to reproduce

* Go to https://agencies.automattic.com/sites.
* Observe the `Development` badge rendered for all sites in the list.

### What you expected to happen

The `Development` badge should only be shown when proxied and when the feature flag `a4a-dev-sites` is enabled.

### What actually happened

The `Development` badge is shown to all users.

### Impact

All

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by wongasy**
Fixes https://github.com/Automattic/wp-calypso/issues/93756
Related to https://github.com/Automattic/wp-calypso/pull/93186

## Proposed Changes

A bug was introduced by the combination of https://github.com/Automattic/wp-calypso/pull/93186 and https://github.com/Automattic/wp-calypso/pull/93408/ where the "Development" badge for free development site was exposed to public users. The free development site feature is not yet released, the badge should be gated behind the respective feature flag `a4a-dev-sites`. 

## Testing Instructions

* Click the Automattic for Agencies live link: https://github.com/Automattic/wp-calypso/pull/93755#issuecomment-2299985773
* Refresh the page after appending `?flags=a4a-dev-sites` to the URL.
* Navigate to "Sites" and assert that the "Development" badge is shown.

Screen Shot 2024-08-20 at 8 29 41 PM

* Refresh the page after appending `?flags=-a4a-dev-sites` to the URL (this removes the feature flag).
* Navigate to "Sites" and assert that the "Development" badge is _not_ shown.

Screen Shot 2024-08-20 at 8 29 26 PM

### CODE REVIEW

File: client/a8c-for-agencies/sections/sites/sites-dataviews/site-data-field.tsx [hunk 1]
```diff
@@ -32,14 +34,14 @@ const SiteDataField = ( { isLoading, site, isDevSite, onSiteTitleClick }: SiteDa
...
-					>
-						{ migrationInProgress
-							? translate( 'Migration in progress' )
-							: translate( 'Development' ) }
+				{ migrationInProgress && (
+					<Badge className="status-badge" type="info-blue">
+						{ translate( 'Migration in progress' ) }
+					</Badge>
+				) }
+				{ devSitesEnabled && isDevSite && (
```
Comment (wongasy) [inline client/a8c-for-agencies/sections/sites/sites-dataviews/site-data-field.tsx:42]: I've decoupled the conditions so it's easier to read and less error prone.

**Review by yansern — APPROVED** [review]
Thanks for decoupling and gating the development label.
