### PR TITLE
Credential Form: Show error message on the correct language + cleanup

### LINKED ISSUE #95625: Site Migration: Credential Step is not showing localized error menssages from backend
### Details

As demonstrated in the comment 
https://github.com/Automattic/wp-calypso/pull/95552#pullrequestreview-2387978031

Errors messages incoming from the backend are not translated;

### Steps to reproduce
* Setup your account in any language different from English
* Go to any of the migration flows
* Follow the steps, choosing the 'Do it for me" option until you reach the steps that require the site credentials
* Set a valid site + invalid credentials

## What is expected?
See errors messages using the correct language

## What is happening?
We only display messages in English.

### PR DESCRIPTION
**Pull request by gabrielcaires**
Fix  #95625 and continue the work started on Remove English-based verifications #95552

## Proposed Changes
* Remove all locale checking from the credential step
* Add _locale flag to the ticket creation request

## Context
This  [comment](https://github.com/Automattic/wp-calypso/pull/95552#pullrequestreview-2387978031)  highlighted we are not showing an error message on the user language. I initially thought the reason was the missing _locale flag, but actually, I [found another English ](https://github.com/Automattic/wp-calypso/compare/update/remove-english-checkings?expand=1#diff-382f42f81c8c6345dcc99cb07d5d3b7498000569987df98536685a295289f9d4L99)checking that was making the UI show errors directly from the backend.

Now, the UI is showing correct error messages.

 
## Testing Instructions
* Select any locale (excluding en) in your WordPress account
* Access any of the migration flows 
* Go to the `Do it for me` 
* Follow all steps until you reach the credential form
* Set a valid WordPress site 
* Set invalids credentials
* Check if the error messages are using the correct language.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-credentials/hooks/use-form-error-mapping.ts [hunk 1]
```diff
@@ -96,10 +93,7 @@ export const useFormErrorMapping = (
 				};
 			}
 
-			if (
-				isEnglishLocale &&
-				code === 'automated_migration_tools_login_and_get_cookies_test_failed'
-			) {
+			if ( code === 'automated_migration_tools_login_and_get_cookies_test_failed' ) {
```
Comment (sixhours) [inline client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-credentials/hooks/use-form-error-mapping.ts:96]: Super nitpicky, but we should reverse this conditional so the constant is on the left-hand side ("Yoda" conditions as per WP coding standards)

**Comment by sixhours** [comment]
Screenshot 2024-10-28 at 12 41 21 PM

Confirmed this fixes the error message translations!

File: client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-credentials/hooks/use-form-error-mapping.ts (hunk 1 above)
Comment (gabrielcaires) [reply client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-credentials/hooks/use-form-error-mapping.ts:96]: Thanks @sixhours.
I just double-checked if we are adopting the WP pattern, and I saw we just have 
164 instances of the Yoda style
1494 instances of the regular style.

I run a search using the following patterns:
Regular style
```
=== '
```
Yoda style

```
' === 
```

The javascript WordPress code standards also contain examples of "regular" style usage.
https://developer.wordpress.org/coding-standards/wordpress-coding-standards/javascript/

So, I think the Yoda style is more applicable to PHP
