### PR TITLE
Marketing: Fix official sharing buttons iframe error

### LINKED ISSUE #60354: Sharing Buttons showing blank page when editing "More" buttons with "Official Buttons" selected as Button style.
### Quick summary

https://user-images.githubusercontent.com/92185881/150625951-bacd31ee-5872-411c-9978-5bd21ff57497.mp4

Marketing > Sharing Buttons

Clicking on Edit "More" buttons with the "Official Buttons" option selected for "Button style" leads to a blank page (throws errors in the browser console log, as seen in the other notes section below).

The screen recording shows the expected behavior from the other options selected, with the resulting error from the "Official Buttons" option selected at the end.

Consistent on both Simple and Atomic sites right now, after testing on sites with a Premium, and a Business subscription.

### Steps to reproduce

1. Marketing > Sharing Buttons.
2. In Button style, select "Official Buttons".
3. Click on Edit "More" buttons.
4. Led to a blank page with errors showing up on the browser console logs.

### What you expected to happen

The Edit "More" buttons display the buttons that can be reordered, like how the other options is showing.

### What actually happened

Blank page with errors showing up in the browser console logs.

### Context

_No response_

### Simple, Atomic or both?

_No response_

### Theme-specific issue?

_No response_

### Browser, operating system and other notes

Chrome Console errors:

Screenshot 2022-01-22 at 13 02 56

```
TypeError: Cannot read properties of undefined (reading 'postMessage')
    at Ee.showMorePreview (marketing.3432ba5f2b759cdff70e.min.js:2:60313)
    at Ee.updateMorePreviewVisibility (marketing.3432ba5f2b759cdff70e.min.js:2:60090)
    at Ee.componentDidUpdate (marketing.3432ba5f2b759cdff70e.min.js:2:62401)
    at gi (61606.7ff894d70e590c95786d.min.js:2:191058)
    at Fl (61606.7ff894d70e590c95786d.min.js:2:207806)
    at t.unstable_runWithPriority (61606.7ff894d70e590c95786d.min.js:2:234507)
    at qo (61606.7ff894d70e590c95786d.min.js:2:149926)
    at Nl (61606.7ff894d70e590c95786d.min.js:2:204545)
    at bl (61606.7ff894d70e590c95786d.min.js:2:200656)
    at 61606.7ff894d70e590c95786d.min.js:2:150149
```

### Reproducibility

Consistent

### Severity

_No response_

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by tyxla**
#### Changes proposed in this Pull Request

This PR fixes the reference to the official sharing buttons preview iframe that we broke when porting refs to the string syntax in #56719.

Fixes #60354.

#### Testing instructions

* Go to Marketing > Sharing Buttons.
* In the Button style radio group, select "Official Buttons".
* Click on the "Edit "More" buttons" button.
* Verify you can edit (select, deselect, reorder) the buttons and they save correctly.
* Verify the preview also works and there are no errors in the console.

### CODE REVIEW

File: client/my-sites/marketing/buttons/preview-buttons.jsx [hunk 1]
```diff
@@ -127,7 +127,7 @@ class SharingButtonsPreviewButtons extends Component {
 		if ( 'official' === this.props.style ) {
 			// To show the more preview when rendering official style buttons,
 			// we request that the frame emit a show message with the offset
-			this.previewIframeRef.current.contentWindow.postMessage( 'more-show', '*' );
+			this.previewIframeRef.current.iframeRef.current.contentWindow.postMessage( 'more-show', '*' );
```
Comment (noahtallen) [inline client/my-sites/marketing/buttons/preview-buttons.jsx:130]: iframe ref-ception! 🤯

**Review by noahtallen — APPROVED** [review]
Tests well to me and thanks for the fix! The "more" button in the preview is not intractable, but I'm not sure if that was ever intended.

I do see this error in the console, but unrelated to the fix itself: ``Uncaught DOMException: Element.querySelector: 'a span:visible' is not a valid selector``

**Comment by tyxla** [comment]
> Tests well to me and thanks for the fix! The "more" button in the preview is not intractable, but I'm not sure if that was ever intended.

Yup, that sounds fine, AFAIK it intends to be static and just be a visual demo.

> I do see this error in the console, but unrelated to the fix itself: `Uncaught DOMException: Element.querySelector: 'a span:visible' is not a valid selector`

Happy to take a look at that in another PR!

**Comment by tyxla** [comment]
> > I do see this error in the console, but unrelated to the fix itself: `Uncaught DOMException: Element.querySelector: 'a span:visible' is not a valid selector`
> 
> Happy to take a look at that in another PR!

I actually wasn't able to reproduce, but happy to try and fix it if you can tell me the concrete steps you took to repro it.

**Comment by noahtallen** [comment]
Good point! I couldn't reproduce for a moment as well, but I finally noticed it was related to the pinterest button, or maybe just adding new buttons:

1. Visit `wordpress.com/marketing/sharing-buttons/$site`
2. Click "edit sharing buttons"
3. Select the pinterest button
4. Observe error in the console

**Comment by tyxla** [comment]
Reproduced! 

However, this is coming from the sharingdaddy module:

https://github.com/Automattic/jetpack/blob/825a23899cb4ae1335ba4f91441cf1b50082a991/projects/plugins/jetpack/modules/sharedaddy/sharing-sources.php#L1760

And it currently works in an odd way: if we make it work, it stretches the Pinterest button a bit too wide. 

I wonder if this code can just be removed altogether for both Jetpack and WP.com.
