### PR TITLE
Plans: Fix multiple plans requests

### LINKED ISSUE #3888: Plans: Multiple requests to the same endpoint
When testing #3839 I noticed that we make multiple requests to the endpoint at `/site/:site/plans`:

screen shot 2016-03-09 at 10 21 49

We should find where this extra request is coming from and ensure we only make one.

### PR DESCRIPTION
**Pull request by Tug**
Fixes #3888 

When `Plans` and `PopoverCart` (a child of `Plans`) mount, they each trigger a request to the site-specific plans endpoint. Instead of having each of these components request data independently, we should trigger the request in the former and have it pass data down through props to the latter.

`PopoverCart` is mounted in `UpgradesNavigation`, which is mounted in four other components besides `Plans`. Two of those already had `sitePlans`, but data components needed to be updated for two others to pass `sitePlans` down from the top of the render tree.

**Testing**
Visit the following routes and assert in the developer tools that we do not make multiple requests to `/sites/%s/plans`. You can filter for this endpoint by entering `sites plans` in the filter input in the network pane in Chrome.
- `/plans/:site` for a site with a free trial and a site without a free trial
- `/domains/manage/:site`
- `/domains/manage/email/:site`
- `/domains/add/:site`

- [x] Code review
- [x] Product review

### CODE REVIEW

**Comment by drewblaisdell** [comment]
I added a commit and updated the PR description with my rationale.

**Comment by Tug** [comment]
Product :+1:

File: client/components/data/domain-management/email/index.jsx [hunk 1]
```diff
@@ -111,7 +120,12 @@ export default connect(
 			: () => fetchBySiteId( sites.getSelectedSite().ID );
 
 		return {
-			fetch: () => dispatch( fetcher() )
+			fetch: () => dispatch( fetcher() ),
```
Comment (Tug) [inline client/components/data/domain-management/email/index.jsx]: Although not part of this PR, this could be renamed `fetchGoogleAppsUsers`

File: client/my-sites/upgrades/domain-search/domain-search.jsx [hunk 2]
```diff
@@ -41,10 +41,14 @@ var DomainSearch = React.createClass( {
...
 		this.props.fetchSitePlans( this.props.sitePlans, this.props.sites.getSelectedSite() );
+
+		this.previousSelectedSite = this.props.sites.getSelectedSite();
 	},
 
 	componentWillReceiveProps: function() {
-		this.props.fetchSitePlans( this.props.sitePlans, this.props.sites.getSelectedSite() );
+		if ( this.previousSelectedSite !== this.props.sites.getSelectedSite() ) {
+			this.props.fetchSitePlans( this.props.sitePlans, this.props.sites.getSelectedSite() );
+		}
```
Comment (Tug) [inline client/my-sites/upgrades/domain-search/domain-search.jsx]: I think `this. previousSelectedSite` should be updated with the new selectedSite here

File: client/my-sites/upgrades/domain-search/domain-search.jsx [hunk 3]
```diff
@@ -41,10 +41,14 @@ var DomainSearch = React.createClass( {
 	componentDidMount: function() {
 		this.props.sites.on( 'change', this.checkSiteIsUpgradeable );
 		this.props.fetchSitePlans( this.props.sitePlans, this.props.sites.getSelectedSite() );
+
+		this.previousSelectedSite = this.props.sites.getSelectedSite();
```
Comment (Tug) [inline client/my-sites/upgrades/domain-search/domain-search.jsx]: IMO, it would be nicer to move the `sites` observer to the parent component and pass `site` as a prop to this component

Comment (Tug) [inline client/my-sites/upgrades/domain-search/domain-search.jsx]: Oh nevermind, the parent component is the controller itself.

**Comment by Tug** [comment]
I did really minor fixes and I think this is ready to merge!
Great job @drewblaisdell
