### PR TITLE
Checkout: Add auto login to ecommerce setup flow

### LINKED ISSUE #49064: Permission error in "Create your store" link in eCommerce plan purchase
#### Steps to reproduce the behavior

1. Purchase a new site with eCommerce plan
2. Wait for the thank you page to load
3. Click on 'Create your store' button
4. Observe the error page

#### What I expected to happen
It loads WooCommerce setup screen.

#### What actually happened
Error with the following text: `Sorry, you are not allowed to access this page.`

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Thank you page:
image

Error page:
image

### PR DESCRIPTION
**Pull request by allilevine**
#### Changes proposed in this Pull Request

* Adds `WpAdminAutoLogin` to the checkout flow for an ecommerce site to fix https://github.com/Automattic/wp-calypso/issues/49064 (unauthorized error when opening the Woo setup wizard)

#### Testing instructions

1. Purchase a new site with eCommerce plan at /new
2. Wait for the thank you page to load
3. Check for network requests to wp-login
3. Click on 'Create your store' button
4. Setup store page in WooCommerce loads
5. Regression: check other checkout flows, e.g. purchasing an upgrade to business.
6. Regression: check that we don't attempt wp-login if the user's email is unverified.

image

Related to https://github.com/Automattic/wp-calypso/issues/49064

### CODE REVIEW

File: client/my-sites/checkout/checkout-thank-you/index.jsx [hunk 1]
```diff
@@ -445,6 +446,12 @@ export class CheckoutThankYou extends React.Component {
 
 			return (
 				<Main className="checkout-thank-you">
+					{ this.props.transferComplete && (
+						<WpAdminAutoLogin
+							site={ { URL: `https://${ this.props.site?.wpcom_url }` } }
```
Comment (allilevine) [inline client/my-sites/checkout/checkout-thank-you/index.jsx:451]: Firefox doesn't allow the auto-login with the wpcomstaging domain (possibly a cross-site rule), so I'm using the site's pre-transfer wordpress.com domain here.

File: client/my-sites/checkout/checkout-thank-you/index.jsx [hunk 2]
```diff
@@ -445,6 +446,12 @@ export class CheckoutThankYou extends React.Component {
...
+							delay={ 0 }
```
Comment (allilevine) [inline client/my-sites/checkout/checkout-thank-you/index.jsx:452]: I've set the delay to 0 here in case the user clicks the button immediately. It's a lot of network traffic for a minute, but then the attempts should stop.

File: client/my-sites/checkout/checkout-thank-you/atomic-store-thank-you-card.jsx [hunk 3]
```diff
@@ -116,7 +116,7 @@ class AtomicStoreThankYouCard extends Component {
 			<div className="checkout-thank-you__atomic-store-action-buttons">
 				<a
 					className={ classNames( 'button', 'thank-you-card__button' ) }
-					href={ site.URL + '/wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard' }
+					href={ siteWooCommerceWizardUrl }
```
Comment (allilevine) [inline client/my-sites/checkout/checkout-thank-you/atomic-store-thank-you-card.jsx:119]: This update doesn't fix the issue but it seemed best to align the Woo wizard link with the one used in the plugins redirect.

**Review by michaeldcain — APPROVED** [review]
I've tested this on both `/new` (Gutenboarding) and `/start/` (Signup), and it works as described. Code-wise, this LGTM. Thanks for fixing this!

**Review by DustyReagan — APPROVED** [review]
Tested /new in Safari, FF, & Chrome. Tested /start in FF. Tested signing up for a business plan, then installing a plugin. All seems good! ✅
