### PR TITLE
Google Apps: Improvements to checkout form

### LINKED ISSUE #2140: Google Apps: Show inline validation instead of notice
The Google Apps form validation notice is currently showing in the wrong place:

screen_shot_2015-10-13_at_12_10_18_pm

Regardless, this should be moved to inline validation to be consistent with the rest of Calypso.

### LINKED ISSUE #5442: Google Apps: Don't require inputting full email during registration
When adding Google Apps during domain registration, we shouldn't require the user to provide the `@example.com` part - it's easy to make a typo and it can be confusing for the user what email should be put there. If we changed it to an input field with the domain in a uneditable suffix ( see https://wpcalypso.wordpress.com/devdocs/design/form-fields), it would mean quicker, simpler checkout.

screen shot 2016-05-18 at 17 26 45

### PR DESCRIPTION
**Pull request by klimeryk**
This PR refreshes the checkout form when buying Google Apps.
Apart from cleaning up the code a bit (I've tried refraining from bigger refactors, like using `form-state` because we don't really have time for that right now), there are some visual and UX improvements:
* Inline validation errors instead of a list on top of the form (fixes #2140).
* Using a form input with a domain suffix so that the user does not have to input the domain manually (fixes #5442 and #2462).
* Improved validation for the email - we check for [allowed characters](https://support.google.com/a/answer/33386?hl=en) and validate the email using `email-validator` (so that emails like `something...@example.com`) won't get through.
* Improved validation for first and last names - since Google allows all Unicode characters, we don't really need to check for anything - apart from max length (60 characters) and trim whitespace, just to be on the safe side.

**Before:**
screen shot 2016-06-29 at 00 23 33

**After:**
screen shot 2016-06-29 at 00 21 50

/cc @aidvu @umurkontaci for code review
/cc @BandonRandon @Lochlaer for product review

Test live: https://calypso.live/?branch=fix/gapps-affixes

### CODE REVIEW

File: client/components/upgrades/google-apps/dialog/index.jsx [hunk 1]
```diff
@@ -139,36 +120,32 @@ var GoogleAppsDialog = React.createClass( {
...
 	},
 
-	footer: function() {
-		var continueButtonHandler = this.state.isAddingEmail ? this.handleFormSubmit : this.handleAddEmail,
-			continueButtonText = this.state.isAddingEmail ?
-				this.translate( 'Continue \u00BB' ) :
-				this.translate( 'Add Email \u00BB' );
+	footer() {
+		const continueButtonHandler = this.state.isAddingEmail ? this.handleFormSubmit : this.handleAddEmail,
+			continueButtonText = this.state.isAddingEmail
```
Comment (aidvu) [inline client/components/upgrades/google-apps/dialog/index.jsx]: There's probably code standards for this, but the former is easier to read for me.

File: client/components/upgrades/google-apps/dialog/users.jsx [hunk 2]
```diff
@@ -46,75 +50,80 @@ var GoogleAppsUsers = React.createClass( {
...
-		var newValue, updatedFields;
+	updateField( index, event ) {
 		event.preventDefault();
 
-		newValue = event.target.value;
-
-		updatedFields = clone( this.props.fields );
+		const newValue = event.target.value,
+			fieldName = event.target.name,
+			updatedFields = clone( this.props.fields );
```
Comment (aidvu) [inline client/components/upgrades/google-apps/dialog/users.jsx]: Shouldn't this one be `let`? You do change it below, tho I don't know why it doesn't trigger JS errors. :D

**Comment by aidvu** [comment]
:+1: 
A nice improvement. I'd love to see it use `form-state`, but let's iterate on it.

File: client/components/upgrades/google-apps/dialog/index.jsx (hunk 1 above)
Comment (klimeryk) [inline client/components/upgrades/google-apps/dialog/index.jsx]: It's in the [coding guidelines](https://github.com/Automattic/wp-calypso/blob/master/docs/coding-guidelines/javascript.md#multi-line-statements) and is [enforced by eslint](http://eslint.org/docs/rules/operator-linebreak) :grin:

Comment (aidvu) [inline client/components/upgrades/google-apps/dialog/index.jsx]: Kind of guessed.

File: client/components/upgrades/google-apps/dialog/users.jsx (hunk 2 above)
Comment (klimeryk) [inline client/components/upgrades/google-apps/dialog/users.jsx]: Because I am changing the value of this variable, not its reference.
From [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const):
> The const declaration creates a read-only reference to a value. It does not mean the value it holds is immutable, just that the variable identifier cannot be reassigned.

JS does not have a qualifier for what you want to achieve - immutability (unfortunately - oh, glorious C++, how I miss your mighty `const`). There's [immutable.js](https://facebook.github.io/immutable-js/), though :)

Comment (aidvu) [inline client/components/upgrades/google-apps/dialog/users.jsx]: Just `let` it be. :laughing: Mumbo-jumbo JS.

Comment (klimeryk) [inline client/components/upgrades/google-apps/dialog/users.jsx]: hq1hssx
