### PR TITLE
CDN Upsell Nudge: Take the user directly to the Pro checkout

### LINKED ISSUE #64975: [Bug]: CTA for CDN upsells is not precise
### Quick summary

"Available on the Pro plan" CTA points to the plan selector page which allows choosing wrong plan during the flow. 

### Steps to reproduce

1. Create a simple blog
2. Navigate to WP Admin -> Settings -> Performance
3. Click "Available on the Pro plan" action either in CDN or Cloudflare CDN block

### What you expected to happen

I see the checkout for the Pro plan:

`/checkout/{$siteSlug}/pro`

### What actually happened

I see the plan comparison:

`/plans/{$siteSlug}?customerType=business`

### Context

Brought by @sejas under https://github.com/Automattic/wp-calypso/pull/64889

### Browser

_No response_

### Simple/Atomic

Simple

### Other notes

_No response_

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #64975

## Proposed Changes

Takes the user directly to the Pro plan checkout when they click on the CDN Upsell Nudge:

https://user-images.githubusercontent.com/36432/177626809-0d447d12-b8bb-4dfb-9ad0-32e4460685a5.mp4

Prior to this change, they would end up on the plan selector page:

https://user-images.githubusercontent.com/36432/177627080-e50daa36-e320-472d-b2b1-a216733f8d92.mp4

The `UpsellNudge` card with `const upgradeLink = '?customerType=business';` was originally added in #49263

"Available on the Pro plan" was added 3 months ago with #61595 but it seems `upgradeLink` was missed in the process.

## Testing Instructions

1. Create a simple blog
2. Navigate to WP Admin -> Settings -> Performance
3. Click "Available on the Pro plan" action either in CDN or Cloudflare CDN block

### CODE REVIEW

File: client/my-sites/site-settings/cloudflare.js [hunk 1]
```diff
@@ -23,7 +23,7 @@ const Cloudflare = () => {
 	const hasJetpackCDN = useSelector( ( state ) =>
 		siteHasFeature( state, siteId, WPCOM_FEATURES_CDN )
 	);
-	const upgradeLink = `/plans/${ siteSlug }?customerType=business`;
+	const upgradeLink = `/checkout/${ siteSlug }/pro`;
```
Comment (wojtekn) [inline client/my-sites/site-settings/cloudflare.js:26]: UpsellNudge uses this link as default if we do not set a `href` attribute. Would it make sense to remove it entirely and rely on default behavior?

**Review by wojtekn — COMMENTED** [review]
@danielbachhuber it works as described. I've added one comment as we could potentially simplify the code.

File: client/my-sites/site-settings/cloudflare.js (hunk 1 above)
Comment (danielbachhuber) [reply client/my-sites/site-settings/cloudflare.js:26]: > UpsellNudge uses this link as default if we do not set a `href` attribute. Would it make sense to remove it entirely and rely on default behavior?

@wojtekn I considered this option, however `UpsellNudge` only defaults to the Pro checkout in certain state-dependent cases:

https://github.com/Automattic/wp-calypso/blob/fa07d72b06029093c4a9e6f7ee273b91f3b832b7/client/blocks/upsell-nudge/index.jsx#L95-L112

I didn't want to invest a bunch of time understanding all of those states, so I thought it simpler and more precise to make the change here.

Comment (wojtekn) [reply client/my-sites/site-settings/cloudflare.js:26]: @danielbachhuber, thank you for providing the details. Relying on the default gives some benefits e.g., the upsell logic becomes more centralized, but the way with link also works fine.

**Review by wojtekn — APPROVED** [review]
