### PR TITLE
Framework: dismiss soft keyboard on enter/search

### LINKED ISSUE #660: Framework: when searching, search button in Android does not dismiss keyboard
Steps to reproduce:

1/ Go to the Themes page
2/ Enter a keyword to search by
3/ Click the search button in the keyboard:

image

4/ Notice that the keyboard does not get dismissed

The usual action for that search button in Android is to dismiss the keyboard & start the search. Given that in Calypso the search starts immediately, the search button should just dismiss the keyboard.

You can also see this happen in the Media search bar.

### PR DESCRIPTION
**Pull request by gwwar**
Fixes #660, where tapping on the search button did not dismiss the android soft keyboard.

## Testing Instructions
* Setup your android emulator via android studio/android virtual device manager
* Make sure the image has enough space, and keyboard input is disabled. (You want to see the soft keyboard).
keyboard
* Start the image
* Update the hosts file to point your host computer ip to calypso.localhost:
```
cd ~/Library/Android/sdk/platform-tools
# remount system
./adb remount
./adb push <yourhostfile> /system/etc
```
* To see the default browser output:
```
./adb logcat browser:V *:S
```
1. Navigate to http://calypso.localhost:3000/design
2. Using the soft keyboard, type in a search query
3. Press the Search button in the android soft keyboard
4. The keyboard should be dismissed

### CODE REVIEW

**Comment by gwwar** [comment]
cc @hoverduck @rralian

File: client/components/search/index.jsx [hunk 1]
```diff
@@ -203,6 +205,11 @@ module.exports = React.createClass( {
 		if ( event.key === 'Escape' ) {
 			this.closeSearch( event );
 		}
+
+		if ( this.props.blurOnEnter && event.which === 13 ) {
```
Comment (rralian) [inline client/components/search/index.jsx]: Is this behavior only desirable on `themes-search-card.jsx`? Wouldn't we want the soft keyboard to blur in any search situation when you hit enter? I would think we would want to somehow gate this on some indication that you have a virtual keyboard (ideal) or are on mobile (ok). I don't see any good approaches for detecting a virtual keyboard. We could maybe build something that infers this based on the viewport size changing when you focus an input element. Or what would you think of using [viewport.isMobile()](https://github.com/Automattic/wp-calypso/tree/master/client/lib/viewport) here instead of introducing a prop? Or maybe we could instead base this decision on how much of the screen is visible below the search input?

Comment (gwwar) [inline client/components/search/index.jsx]: If you look at `themes-search-card/index.jsx` this is only being set in the renderMobile function. Losing focus on <kbd>enter</kbd> is pretty annoying for anyone who's using a keyboard so that's why I opted for being more explicit in this first pass. 

Thanks for the viewport link, I think it should be OK to gate off of the viewport dimensions. The only concern is that some of the larger phones may not trigger this, but I'll try it out and test a few different images. https://design.google.com/devices/

Comment (rralian) [inline client/components/search/index.jsx]: Yeah, I agree we don't want this to apply to desktop because that would be really annoying. Ultimately the `renderMobile` decision in `themes-search-card` [is determined by viewport.isMobile](https://github.com/Automattic/wp-calypso/blob/fix/android-keyboard-660/shared/my-sites/themes/themes-search-card/index.jsx#L18) anyway. So if this behavior is desirable for search in general (I think it is), I'd probably just apply it to search based on `isMobile` and remove the prop. Though I agree this is a dirty bit of feature detection that could stand to be improved.

Comment (gwwar) [inline client/components/search/index.jsx]: Updated to use viewport in 6fcdec9

**Comment by rralian** [comment]
This looks good to me. But I am having a _bad time_ trying to test android. I don't have a personal android device and neither browserstack nor android studio will work for me. :-( If some other kind soul would just give this a quick test, I think we can :ship: this.

**Comment by gwwar** [comment]
@hoverduck if you have an android environment ready, it'd be much appreciated if you could test this.

**Comment by hoverduck** [comment]
@gwwar / @rralian - I checked it out, and it looks good on the Themes page mentioned in the original issue (#660).  But I looked around for other search fields and found that the one under Reader -> Manage Followed Sites still shows the old behavior.  It looks like they're both using the same Search component, unless I'm missing something.  Do we need another issue?

**Comment by gwwar** [comment]
@hoverduck good catch! I updated the code so it should work on all search inputs when viewing in mobile (not just pinned search inputs). Do you mind taking another look?

**Comment by hoverduck** [comment]
@gwwar Looks good!
