### PR TITLE
Onboarding consistency: Fix checkout blinks

### LINKED ISSUE #102459: Onboarding consistency: Fix checkout blinks
### Details

Map task [the work being done here](https://github.com/Automattic/wp-calypso/pull/102347).

### PR DESCRIPTION
**Pull request by zaguiini**
## Proposed Changes

From the video, I don't like these blinking loading messages. Should we also address them? Remember that the post-checkout process can take a while. Let's address this as part of a follow-up.

## Why are these changes being made?

Style consistency in the onboarding flow.

| Before | After |
| ------- | ----- |
| <video src="https://github.com/user-attachments/assets/4ddad975-af31-4d1c-a06b-f1912bcb0a74" /> | <video src="https://github.com/user-attachments/assets/1560fec2-a6c7-4f6d-b45b-a75d9735032a" /> |

## Testing Instructions

Go through `/setup/onboarding` with the `onboarding/step-container-v2` feature flag turned on and verify you don't see any blinks or gray backgrounds.

Turning the feature flag off and going through the same process also shouldn't break the app. And there should be no visual changes throughout Calypso as well when booting the app (refreshing the page, navigating through pages and refreshing the page.)

### CODE REVIEW

File: client/sections-middleware.js [hunk 1]
```diff
@@ -86,6 +88,15 @@ function loadSectionHandler( sectionDefinition ) {
...
 }
 
+function maybeRenderLoading( context, next ) {
+	if ( isInStepContainerV2FlowContext( context.pathname, context.querystring ) ) {
+		context.layout = <Step.Loading />;
+		controller.render( context );
+	}
+
+	next();
+}
```
Comment (zaguiini) [inline client/sections-middleware.js]: This is the most relevant change of this PR, @jsnajdr @tyxla.

The page is blank when loading sections, causing the in-between loading states to blink. The blinking goes away if we render the `Step.Loading` component within that interval of fetching the async section and rendering it.

Is this the best way to do this? The right place?

**Review by paulopmt1 — APPROVED** [review]
Ohh, this is so much better. Thanks for another great improvement @zaguiini!

> I don't like these blinking loading messages. Should we also address them? Remember that the post-checkout process can take a while.

I see that the flow does:

1. /checkout/{site}
2. /checkout/thank-you/{site} - Text blink
3. /setup/onboarding/post-checkout-onboarding - Text blink
4. /setup/onboarding/processing
5. /setup/site-setup
6. /setup/site-setup/goals

Video for reference:

https://github.com/user-attachments/assets/72180bec-d477-4f1a-80db-2a0a41678d7b

If we have more time to fix things, maybe we could remove some intermediate steps like the `2. /thank-you` and the `3. /post-checkout-onboarding` going directly to the `/processing`?

**Comment by p-jackson** [comment]
> I don't like these blinking loading messages. Should we also address them?

Yes we absolutely should. I'd rather have none of them than messages that appear and disappear. Doesn't have to be this PR though. It feels like a different sort of change, just better detection on the processing step to know when it's in a post checkout phase.

File: client/assets/stylesheets/_main.scss [hunk 2]
```diff
@@ -49,7 +49,7 @@ body {
 	background: var(--color-surface-backdrop);
 
 	&:has(.step-container-v2) {
-		background: #fdfdfd;
+		background: var(--stepper-background);
```
Comment (p-jackson) [inline client/assets/stylesheets/_main.scss]: @nuriapenya heads up that the stepper framework background is `#fdfdfd`, but that Calypso uses pure white. (`--color-surface` in the sites dashboard and `--color-surface-backdrop` in the main site dashboard, but both evaluate to `#fff`)

This PR makes some tweaks to ensure users don't notice a color change as they transition between stepper / checkout / and back to stepper again. But it would be simpler if everywhere used the same background color.

Should the stepper framework just use `--color-surface`?

File: client/sections-middleware.js (hunk 1 above)
Comment (p-jackson) [reply client/sections-middleware.js]: The only thing I could think of was something like this

(pseudo code)

```ts
context.primary = <Step.Loading />;
makeLayout( context, () => clientRender( context, next ) );
return;
```

To make sure we run through the usual layout code. Maybe it's unnecessary though.

**Review by p-jackson — APPROVED** [review]
This is looking much smoother. I do still want to see the text not appear and disappear quickly. Tantalisingly close.

File: client/sections-middleware.js (hunk 1 above)
Comment (tyxla) [reply client/sections-middleware.js]: This is a very unexpected place to render the loading spinner 😉 If we were to do it in such a way, I'd expect us to do it more centrally, and not a one-off thing like here. It just looks and feels like a hack since it escapes the natural flow of routing and rendering.

Can we move this check to component land in order to avoid forking the rendering logic?

Comment (jsnajdr) [reply client/sections-middleware.js]: > The page is blank when loading sections, causing the in-between loading states to blink.

Here I'd like to understand better why the page is blank when loading sections. When an async `page.js` router handler is running, the rendered React UI doesn't change. What was rendered by the previous route hander remains rendered.

Only when the new section finishes loading, it does its own `clientRender` call and renders something new. That's the moment when the old UI instantly switches to the new UI.

Between which two routes exactly do we see the "blank page"?

There's one fundamental design problem in Calypso routing that is not solved: when the old React UI is still rendered, the URL of the page can already have the new value. When the old UI reads the route path or query args in a reactive way (Redux selectors etc.), it can get confused by seeing values it doesn't know.

Maybe that's what is going on here?

**Review by ciampo — COMMENTED** [review]
I'd like to leave some more generic feedback about the architecture of these flows, separation of concerns and encapsulation — I understand that this PR doesn't introduce any of these aspects, but the changes in this PR are a good example.

One aspect that I'd love to see change in Calypso, is to have more encapsulation / separation of concerns between different components.

A few examples:
- `client/assets/stylesheets/_main.scss` should not "know" about `step-container-v2`, that should be a detail inside Stepper. In general, Stepper should be "self-contained" and not leak stepper variables and references outside of itself
- In a similar fashion, Stepper should not defile global styles — it should only define styles for content rendered inside Stepper.
- Changing the background color in the body also seems like a hack to hide an underlying issue, as suggested by Jarda
- Maybe Stepper should render a background on top of the `document.body` that is always there even when navigating between steps
- In a similar fashion, I don't like the idea of having a `--stepper-background` variables shared globally in `client/assets/stylesheets/shared/_variables.scss` — Stepper should be self-container, and its variables should live under its scope.
- This lack of encapsulation is manifested when `--stepper-background` gets applied to the Register Domain step. The "register domain" step lives outside of Stepper, which means that it's supposed to be reused in more places across Calypso. Having a stepper variable in the Register Domain step breaks the encapsulation and makes the step less reusable.
  - If the step is only used in Stepper, it should be moved to the stepper folder / framework
  - if the step is reusable, it should have its own styles, and expose clear ways to its consumers to style it (eg. by inheriting backgrounds, or by having its consumer pass the chosen background)
- The same applies for thank you, plans, domains, odie, etc — tying them to a stepper variable tightly couples them to stepper and hinders their reusability

File: client/sections-middleware.js (hunk 1 above)
Comment (zaguiini) [reply client/sections-middleware.js]: Thanks for the feedback and for scrutinizing this PR. After some more testing and research, I think I've figured it out.

---

### Our goal: render the loading placeholder instead of seeing the gray page blink.

---

Let's browse a regular Calypso page with an async section, like `/checkout/:siteId`. The process goes like that:

1. [Call the boot function](https://github.com/Automattic/wp-calypso/blob/trunk/client/boot/common.js#L358);
2. [If there's no primary content coming from the server](https://github.com/Automattic/wp-calypso/blob/trunk/client/boot/common.js#L348), then [render an initial `<Layout />`](https://github.com/Automattic/wp-calypso/blob/trunk/client/boot/common.js#L318-L321);
3. The async section gets loaded, and the React root hydrates.

Let's revisit step 2 and see what we can learn from it.

We're checking if we've rendered some content on the server by querying for `#primary`. In our case, it will return `false` as [we're rendering our loader within a pseudo-Layout on the server](https://github.com/Automattic/wp-calypso/blob/trunk/client/document/index.jsx#L191-L213), and there isn't an element with an id of `primary`.

**We can call it a day if we change this conditional so it queries for `.layout`.** It preserves the content from the server and only replaces it once the async section finishes loading, which is what we want.

---

If we don't want to do that, let's continue digging. Let's analyze how the initial layout gets rendered. [We're calling `<ProviderWrappedLayout />` with our `reduxStore` and `reactQueryClient` as props](https://github.com/Automattic/wp-calypso/blob/trunk/client/boot/common.js#L319).

Looking at what `ProviderWrapperLayout` renders, we'll notice it wraps the layout in `RouteProvider`, and [that component returns `null` if we don't pass a `currentRoute` prop](https://github.com/Automattic/wp-calypso/blob/trunk/client/components/route/index.js#L26-L28), which is exactly the case (remember that we're only passing the Redux store and the query client.)

**That is why we're getting a blank page**. Nothing gets returned from `ProviderWrapperLayout`, and then the checkout section loads and injects its content in `#wpcom`.

We have some options here:
1. We can pass a `currentRoute` prop, which, from what I've seen, is just a regular `window.location.pathname`;
2. We can remove the early return from `RouteProvider`. [Here's more context on why it was added](https://github.com/Automattic/wp-calypso/pull/91510#discussion_r1628598348). 

Both options would render our pre-section layout. But we'd not be done yet...

---

Even though we're not rendering `null` anymore, we still see a blank page.

That happens because we're not defining any `primary` content when rendering our initial Layout, so the page is empty. Here, we have a few options:

### Solution 1: Check if we're within the StepContainerV2 flow and pass `<Step.Loading />` as the primary content of the layout

Like this:

```jsx
function renderLayout( reduxStore, reactQueryClient ) {
	ReactDom.render(
		<ProviderWrappedLayout
			store={ reduxStore }
			queryClient={ reactQueryClient }
			primary={
				isInStepContainerV2FlowContext( window.location.pathname, window.location.search ) ? (
					<Step.Loading />
				) : undefined
			}
		/>,
		document.getElementById( 'wpcom' )
	);
}
```

This works and is the most straightforward solution for async-loaded sections since this rendered Layout is discarded once the new section arrives. However, it's outside component land as @tyxla said, and it does feel a bit out of place.

### Solution 2: Render `<Step.Loading />` instead of the initial Layout

If applicable, of course. It suffers from the same concerns raised by Marin as explained above. Here's what it looks like:

```jsx
function renderLayout( reduxStore, reactQueryClient ) {
	if ( isInStepContainerV2FlowContext( window.location.pathname, window.location.search ) ) {
		return ReactDom.render( <Step.Loading />, document.getElementById( 'wpcom' ) );
	}

	ReactDom.render(
		<ProviderWrappedLayout store={ reduxStore } queryClient={ reactQueryClient } />,
		document.getElementById( 'wpcom' )
	);
}
```

I honestly... don't hate it. We're technically in component land already within this function, so it isn't too bad.

### Solution 3: Modify [`<LayoutLoader />`](https://github.com/Automattic/wp-calypso/blob/trunk/client/layout/loader.jsx#L7) so it's aware of StepContainerV2's flows

Something like this:

```jsx
export default function LayoutLoader() {
	const isLoading = useSelector( isSectionLoading );

	if ( isInStepContainerV2FlowContext( window.location.pathname, window.location.search ) ) {
		return (
			<div className={ clsx( 'layout__loader--step-container-v2', { 'is-active': isLoading } ) }>
				<Step.Loading />
			</div>
		);
	}

	return (
		<div className={ clsx( 'layout__loader', { 'is-active': isLoading } ) }>
			{ isLoading && <PulsingDot delay={ 400 } active /> }
		</div>
	);
}
```

That doesn't work by itself. See, the initial Layout gets rendered before the async section starts loading, so `isSectionLoading` starts with `false`, which doesn't fix the blink.

We can call `reduxStore.dispatch( setSectionLoading( true ) );` [right before `renderLayout`](https://github.com/Automattic/wp-calypso/blob/trunk/client/boot/common.js#L349) and voilà, the blink is gone. Or add a new prop to `ProviderWrappedLayout` like `initialLoading` and drill it to the loader component.

The assumption with this approach is that we're always going to load a section (or anything else), and I'm not sure how safe it is. Unless we add the StepContainerV2 check like we're doing in Solution 2.

Finally, `<LayoutLoader />` isn't the same thing as `<Step.Loading />`, aesthetically speaking. It's just a blinking dot at the top at the page, not a full-page loading screen. Not sure if we want to mix both.

---

### The end

I believe this explanation and proposed solutions are enough to keep the conversation going and propose even better alternatives. Let me know what's on your mind.

---

Trivia: That blinking problem doesn't happen when creating a free site in `/setup/onboarding` because Stepper boots through a [different entry point](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/index.tsx) and that entry point [already includes StepContainerV2's loader](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/index.tsx#L214-L221).

Comment (jsnajdr) [reply client/sections-middleware.js]: Another solution: stop calling `renderLayout` completely in the `boot` function. Currently it doesn't render anything anyway because there is no `primary` or `secondary` content. And also because `RouteProvider` will render `null` because there is no `currentRoute` set in Redux yet.

Seems that this `renderLayout` doesn't perform any function nowadays. Removing it will keep displaying the placeholder sent by server (`<Step.Loading>` or the "classic" one), and the real UI will be displayed after `page.start()` handles the initial route. No rendering in between.

I'd bet that this initial layout used to display something better than just a blank white page. I think it was a skeleton of a Calypso page with the sidebar and masterbar areas visible (as placeholder rectangles in shades of gray).

That was at the time when all Calypso pages had this common masterbar+sidebar+content structure. But that disappeared over the last few years, today Calypso pages have very variable layouts, for better or worse, and there is no longer any common placeholder.

Comment (jsnajdr) [reply client/sections-middleware.js]: > This is a very unexpected place to render the loading spinner 😉 If we were to do it in such a way, I'd expect us to do it more centrally,

Turns out we already have a central place where a rich variety of spinners is rendered 🙂 It's on the server, selected by the `chooseLoadingLogo` function. It can render one of 7 spinners:
- four variants of "show a logo": WordPress, Jetpack, Woo, A4A (Automattic logo)
- `Step.Loading` for Signup
- `Loading` component from `components/loading` used across Stepper, Signup and Checkout
- `LoadingEllipsis` which used to be used by Signup but is no longer active

Comment (jsnajdr) [reply client/sections-middleware.js]: > `LoadingEllipsis` which used to be used by Signup but is no longer active

I'm removing this unused code in #102441.

Comment (zaguiini) [reply client/sections-middleware.js]: Awesome @jsnajdr I was a bit wary of removing that logic as I didn't really look why we were doing it 😁 I'll remove it, then.

Comment (jsnajdr) [reply client/sections-middleware.js]: The only reason why this initial render could possibly be relevant is SSR and hydration. If the server renders something and sends it along in the initial HTML, your initial render must match the server markup exactly. That's why we needed to do this initial render with empty layout. That's what I remember from 5+ years ago 🙂 Today the initial layout and render seems to be significantly different.

File: client/my-sites/sidebar/style.scss [hunk 3]
```diff
@@ -146,7 +146,7 @@ $font-size: rem(14px);
 /* stylelint-disable-next-line no-duplicate-selectors */
 .theme-default {
 	// client/layout/style.scss
-	.layout__content {
+	&:has(.sidebar) .layout__content {
```
Comment (zaguiini) [inline client/my-sites/sidebar/style.scss:149]: This "scopes" the sidebar hack to only change the div's height if there's, in fact, a sidebar. We can revisit that code and check if it's still needed as part of a follow-up.

The original code caused the loading progress bar to jump because the minimum page height changed.

**Review by zaguiini — COMMENTED** [review]
@ciampo @tyxla @jsnajdr, it turns out these gray backgrounds were happening because of the empty layout we were rendering. 

Removing it also removed the gray blinks :)

The background color changes are now reverted.

**Review by jsnajdr — APPROVED** [review]
There's one thing that should be fixed sooner or later: the server renders the `Step.Loading` component, but doesn't reliably ship its styles.

The styles (mainly `TopBar/style.scss`) are there only by accident: when a section like `checkout` is loaded, we preload its styles in the initial HTML, and that's how the placeholder is also correctly styled. But when I enable the `Step.Loading` placeholder on another section, it won't be correctly styled.

Bad styling:
Screenshot 2025-04-08 at 8 19 36

Correct styling:
Screenshot 2025-04-08 at 8 20 38
