### PR TITLE
Framework: disable background scroll when dialog is visible

### LINKED ISSUE #110: Framework: I can scroll background when modal shows
I know this probably applies to all instances of the popup modal, but I can still scroll behind when the 2FA verification code popup is displayed.  To reproduce, visit https://wordpress.com/me/ and delete the twostep_auth_cookie; on refreshing the page, the popup modal came up and you can scroll behind it.

For the fix, I tried adding a CSS rule body `{ overflow-y: hidden; }` to the browser inspector and it didn't prevent scrolling. I had to add the rule at the html level using html `{ overflow-y: hidden; }` for it to take effect.  The `dialog` component should be updated as a universal enhancement.

Tested in Chrome 44.0.2403.107, Mac OSX 10.10.4

### PR DESCRIPTION
**Pull request by gwwar**
Fixes #110 so background content cannot be scrolled on dialogs.

## Testing Instructions
1. Navigate to calypso.localhost:3000/me
2. Delete your 2-factor auth cookie `twostep_auth` under `public-api.wordpress.com`
3. Refresh the page
4. Attempt to scroll with the 2-factor auth modal displayed

Before: 
scroll

After (note the lack of scrollbar on the browser window):
after

cc @rralian @hoverduck

### CODE REVIEW

**Comment by gwwar** [comment]
@hoverduck do you know of any other dialogs where we should update the scrolling behavior?

File: client/my-sites/plugins/plugin-activate-toggle/test/index.jsx [hunk 1]
```diff
@@ -29,6 +29,7 @@ describe( 'PluginActivateToggle', function() {
 		mockery.registerMock( 'analytics', analyticsMock );
 		mockery.registerMock( 'my-sites/plugins/plugin-action/plugin-action', mockedPluginAction );
 		mockery.registerMock( 'lib/plugins/actions', mockedActions );
+		mockery.registerMock( 'component-classes', {} );
```
Comment (gwwar) [inline client/my-sites/plugins/plugin-activate-toggle/test/index.jsx]: I had to work around the test failures, by mocking out the component-classes module. Let me know if you'd rather have me update the html classes in `dialog-base.jsx` using plain js to avoid touching these test files.

**Comment by hoverduck** [comment]
I just dug around and the only other page I found with the problem is Jetpack security (/settings/security/`site name`) -> Enable Jetpack Scan -> Click "Get your public key string."

I feel like I've seen the problem elsewhere, but that was all I could find at the moment.  If it comes up on another page we can just write a new issue and link to this one for the fix.

**Comment by gwwar** [comment]
@hoverduck if you have time, could you test and see if the Jetpack dialog is happy? My Jetpack env isn't ready yet.

**Comment by hoverduck** [comment]
@gwwar Looks good!

**Comment by gwwar** [comment]
Thanks for testing that @hoverduck!

**Comment by rralian** [comment]
Can this just be the default behavior? Do we have a need to allow for scrolling in some cases for a dialog? I couldn't think of any, but maybe there are and I'm just missing them.

**Comment by gwwar** [comment]
> Can this just be the default behavior? Do we have a need to allow for scrolling in some cases for a dialog? I couldn't think of any, but maybe there are and I'm just missing them.

I can only think of one, j/k keyboard events in the reader when the post preview is up. We can update the default, as long as we're not afraid of some potential breakages.

**Comment by rralian** [comment]
Hmm... I don't notice any difference in behavior in the branch when using j/k to navigate the reader (including the list view and the post view). Maybe a sanity check by @blowery? And @mtias and @adambbecker can either of you think of a situation where we need the original behavior (ability to scroll the background behind a dialog)? If we don't need it, I'd prefer to simplify.

**Comment by adambbecker** [comment]
> can either of you think of a situation where we need the original behavior (ability to scroll the background behind a dialog)? If we don't need it, I'd prefer to simplify.

Can't think of any. Also agree with having that be the default behavior / potentially not needing the prop.

**Comment by gwwar** [comment]
@rralian looks like j/k behavior is broken in the reader (cc @blowery), unless it's intentional. When you have full post preview up, it shouldn't dismiss on j/k. Basically as you go through items, infinite list needs the scroll to load more pages.

I'll flip the default in a bit.

**Comment by rralian** [comment]
> @rralian looks like j/k behavior is broken in the reader

Yeah, seemed odd to me, but I wasn't sure if the behavior was intentional.

**Comment by gwwar** [comment]
@adambbecker @rralian I went ahead and removed the prop, since the j/k edge case in reader appears broken. Once it's fixed we can route around that if we need to in a future PR.

**Comment by rickybanister** [comment]
Adding a new category in the editor also uses a dialog like this.

I noted today that if your browser is short (vertically) you cannot scroll the dialog to the bottom to access submit buttons, etc. 

Now that we've disabled scrolling on the bg, could we enable it within the dialog? Something like `max-height: 100vh; overflow-y: scroll;` (or similar)?

**Comment by blowery** [comment]
the reader's j/k is busted in full post view for a different reason, the new exit routes i added.. :/

**Comment by rralian** [comment]
> Now that we've disabled scrolling on the bg, could we enable it within the dialog? Something like max-height: 100vh; overflow-y: scroll; (or similar)?

I think we'll need that, but it's probably best to do that in a different PR.

**Comment by blowery** [comment]
#1400 to address the issues with reader. probably worth testing these two together to see if the breakage is still there.

**Comment by mtias** [comment]
@rickybanister our thinking here before was that `dialog` should be like browser/OS dialogs, a simple window with a couple options. Once we use it like a full page modal it starts to break, and I'd rather people take conscious measures when they are breaking the pattern (like `media`).

**Comment by rickybanister** [comment]
I don't disagree, but the add-category dialog isn't exactly the full screen. I simply had the inspector open and couldn't get to the buttons. Even if the dialog is only 100px tall there could be strange circumstances where the window was short and you couldn't access the bottom of the dialog. Allowing it to scroll if it gets too tall seems like a good failsafe–that said we should probably also avoid 'full screen' and other large dialogs, the two don't seem mutually exclusive though.

**Comment by gwwar** [comment]
@blowery I'll rebase once #1400 lands. Thanks for taking a look :)

**Comment by rralian** [comment]
I'm gonna change this to in-progress until #1400 lands and we can rebase and give it another look.

**Comment by gwwar** [comment]
Retested this with #1400 fixed, and it looks like we're not affecting behavior in the reader. This should be ready for review again.

**Comment by blowery** [comment]
thanks for the update!

File: assets/stylesheets/layout/_main.scss [hunk 2]
```diff
@@ -541,3 +541,8 @@ body.newdash div.wordpress-com-extension-promo {
 		display: none;
 	}
 }
+
+//added to the html element when we don't want the background content to scroll
+.noscroll {
```
Comment (mtias) [inline assets/stylesheets/layout/_main.scss]: I'd add the `html` selector just for safety, and maybe adjust the class to be `no-scroll`? So `html.no-scroll`.

File: client/components/dialog/index.jsx [hunk 3]
```diff
@@ -17,7 +17,9 @@ export default React.createClass( {
 		baseClassName: React.PropTypes.string,
 		enterTimeout: React.PropTypes.number,
 		leaveTimeout: React.PropTypes.number,
-		onClosed: React.PropTypes.func
+		transitionLeave: React.PropTypes.bool,
+		onClosed: React.PropTypes.func,
+		onClickOutside: React.PropTypes.func
```
Comment (mtias) [inline client/components/dialog/index.jsx]: are we doing anything with this?

**Comment by mtias** [comment]
Sorry @gwwar this fall through the cracks. I added a couple minor comment but this looks good to me.

File: client/components/dialog/index.jsx (hunk 3 above)
Comment (gwwar) [inline client/components/dialog/index.jsx]: I added in some missing prop types that were described in default props.

File: assets/stylesheets/layout/_main.scss (hunk 2 above)
Comment (gwwar) [inline assets/stylesheets/layout/_main.scss]: updated in 8c1072b

**Comment by gwwar** [comment]
:+1: Thanks for the look @mtias
