### PR TITLE
Calypso 404: Redirect user to selected site home when 404 return home is clicked

### LINKED ISSUE #94938: Calypso 404: The Return Home button takes users back to their primary site, not selected site
### Quick summary

As title, the "Return Home" button takes users back to their primary site instead of the currently selected site.

Screenshot 2024-09-26 at 4 39 55 PM

### Steps to reproduce

1. Access https://wordpress.com/dev-tools/{SITE}.
2. Click on the "Return Home" button.

### What you expected to happen

To go back to the Dashboard/My Home of the selected site.

### What actually happened

Went back to my primary site instead.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by vykes-mac**
Closes https://github.com/Automattic/wp-calypso/issues/94938

## Proposed Changes
Currently if the user encounters 404 on a selected site, the `return home` button redirects to the dashboard of their primary site which is not desirable. This PR

* Returns to the selected site home/dashboard if 404 happens on a selected site route

## Why are these changes being made?

* As an improvement to the user experience

## Testing Instructions

* At `wordpress.com/me/account ` ensure `Admin home is disabled
* Go to `/dev-tools/selectedSite`
* Verify the 404 CTA redirects to the selected site home
* Verify that if there are no selected site eg. `/dev-tools/` the CTA redirects to the home of your primary site. Ensure a primary site is set on the account.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/test/root-section.ts [hunk 1]
```diff
@@ -135,4 +139,32 @@ describe( 'Logged In Landing Page', () => {
...
+					},
+				},
+			},
+		};
+		const { page } = initRouter( { state } );
+
+		page( '/' );
+
+		await waitFor( () => expect( page.current ).toBe( '/home/selected.wordpress.com' ) );
+	} );
```
Comment (daledupreez) [inline client/test/root-section.ts]: It feels like we should also add a test case to make sure that users with WPAdmin as their preferred UI are redirected correctly too.

**Review by daledupreez — COMMENTED** [review]
This is working as expected for sites that are using Calypso and Classic interfaces for home, but I think it would be good to expand the testing instructions and the tests to cover both cases.

**Review by agrullon95 — APPROVED** [review]
Followed the testing instructions and was redirected to the correct site `/home/{site_slug}`
