### PR TITLE
Gutenberg: adds support for the fetch all middleware

### LINKED ISSUE #28615: Gutenberg: fix core fetch all middleware handling
The API Fetch package has special behavior when per_page is set to `-1`. This means we should fetch all pages of a given resource.

This appears to have broken again, leaving us with only the first 100 results. Causing issues like us not rendering the full author list in the sidebar.

https://github.com/WordPress/gutenberg/blob/cdeb4098607e8d5f1dc439e6527191359f1a1852/packages/api-fetch/src/middlewares/fetch-all-middleware.js

cc @georgeh if you had tips from the last fix

### Testing Instructions
- Navigate to a site with more than 100 users (for a8c folks a p2 site will do the trick)
- Edit a post or page
- In the sidebar click on the Author dropdown

Expected: all users are visible
Actual: only the first 100 are returned

### PR DESCRIPTION
**Pull request by rodrigoi**
#### Changes proposed in this Pull Request

This PR adds the `fetchAllMiddleware` to `apiFetch` when Gutenberg is loaded in Calypso.

| Before | After |
| - | - |
| before | after |

##### Why we need to add this again?

The `fetchAllMiddleware` is the [next to last middleware on the list of native middlewares](https://github.com/WordPress/gutenberg/blob/68a6bd57e569b83acd8ea2c8f4a425df29565775/packages/api-fetch/src/index.js#L122) run by `apiFetch` natively, so, why do we need to add it again?

Because `wpcomProxyMiddleware` intentionally breaks the middleware chain, so the only middlwares executed are the ones defined in Calypso.

##### What's with the `parse` thing?

For `fetchAllMiddleware` to work, we need to make some changes on the way we return data from the `rest-proxy`, because it expect the objects returned to conform with the Fetch API (specifically with the `Headers` and `Response` interfaces.

To do that, we need to skip parsing. The middleware will include a `parse=false` option to inform us that it wants to do it's own parsing, since it will call `next` several times until there's no more data to fetch from the server.

This PR modifies `wpcomProxyMiddleware` to take into consideration the `parse` option, that defaults to `true`. If `parse` is `false`, we need to format our response such that:

- the `body` is accessed using a `json()` function: https://developer.mozilla.org/en-US/docs/Web/API/Body/json
- the headers are: 
    - accessed using a `get()` function.
    - 'link` si lowercase.

```js
const { Link: link, ...moreHeaders } = headers;
return resolve( {
    json: () => fromApi( dataResponse ),
    headers: { get: header => get( { link, ...moreHeaders }, header ) },
} );
```

We need to lowercase the name of the header, because `fetchAllMiddleware` [uses `link`](https://github.com/WordPress/gutenberg/blob/68a6bd57e569b83acd8ea2c8f4a425df29565775/packages/api-fetch/src/middlewares/fetch-all-middleware.js#L29), but the API response contains `Link` and: 

> header names are matched by case-insensitive byte sequence.
> https://developer.mozilla.org/en-US/docs/Web/API/Headers

screen shot 2018-11-16 at 20 39 03

#### Testing instructions

* Sandbox `public-api.wordpress.com` and apply this patch: D21000-code.
* Start Calypso with `?flags=-calypsoify/gutenberg`: http://calypso.localhost:3000/?flags=-calypsoify/gutenberg
* Opt-In to use Gutenberg if you haven't done on that site.
* Select a site with more than 100 authors or categories (for a12s p2 site should do).
* Click to add a new blog post.

Verify that all the panels on the sidebar work correctly, authors and categories are loaded and there are no regressions when saving or publishing the post.

Fixes #28615 and #28536 for the Calypso Integration (**not Calypsoify**)

Part of #28271

### CODE REVIEW

**Comment by gwwar** [comment]
As a higher level question are folks on @Automattic/lannister comfortable with continuing to break the middleware chain, since no core middleware will run?

The tradeoff is that it has a higher maintenance cost and we also need to port other core middleware in follow-ups, and maintain that on upgrades.

Alternatively we'd need to abandon using wpcom.js and figure out an alternative auth mechanism, perhaps more similar to what we have in wp-admin.

File: client/gutenberg/editor/api-middleware/index.js [hunk 1]
```diff
@@ -30,19 +30,28 @@ const debugMiddleware = ( options, next ) => {
...
+		const path = options.path.replace( '/wp/v2/', `/sites/${ siteSlug }/` );
 
 		//TODO: temporary fix, we need to add fetchAllMiddleware from Gutenberg core, a -1 value is rewritten to fetch _all_ values
 		// https://github.com/WordPress/gutenberg/blob/master/packages/api-fetch/src/middlewares/fetch-all-middleware.js
-		if ( /per_page=-1/.test( path ) ) {
-			path = path.replace( 'per_page=-1', 'per_page=100' );
-		}
+		// if ( /per_page=-1/.test( path ) ) {
+		// 	path = path.replace( 'per_page=-1', 'per_page=100' );
+		// }
```
Comment (gwwar) [inline client/gutenberg/editor/api-middleware/index.js]: Please delete dead code, we can always refer back to history 👍

File: client/gutenberg/editor/api-middleware/index.js [hunk 2]
```diff
@@ -30,19 +30,28 @@ const debugMiddleware = ( options, next ) => {
 // Rewrite default API paths to match WP.com equivalents. Note that
 // passed apiNamespace will be prepended to the replaced path.
 export const wpcomPathMappingMiddleware = ( options, next, siteSlug ) => {
+	//support for fetchAllMiddleware, that uses url instead of path
```
Comment (gwwar) [inline client/gutenberg/editor/api-middleware/index.js]: Curious 🤔 we may need to audit for anything else we're missing.

**Comment by gwwar** [comment]
Thanks @rodrigoi verified that this works with D21000-code applied. Let's land this after D21000 is out, and I'll add additional issues for the other core middleware we're missing.

File: client/gutenberg/editor/api-middleware/index.js (hunk 2 above)
Comment (vindl) [reply client/gutenberg/editor/api-middleware/index.js]: I did introduce `url` mapping initially too, but removed it since it wasn't doing anything at the time.

What else might we be missing?
