### PR TITLE
FSE: Append new blocks inside post content block

### LINKED ISSUE #34327: FSE: Blocks are inserted outside the post content block [8]
#### Steps to reproduce
1. Go to your FSE testing environment.
1. Trash all templates and template parts.
1. Deactivate and then reactivate the FSE plugin.
1. Create a new page.
1. Select the Blank template.
1. Insert a paragraph block and enter some text.
1. Publish the page and refresh the editor.
1. Notice how the default FSE template has been applied (you should see the header/footer template parts and the post content block).
1. Insert an image block using the global inserter in the editor header and upload/select an image:
Screen Shot 2019-06-27 at 08 53 24

1. Update the page.
1. Refresh the editor.

#### What I expected

The image to be displayed on the published view of the page and the image block to be in the post content when I refreshed the editor.

#### What happened instead

The image doesn't not appear in the published view and the block is missing in the editor.

#### Context / Source

Seems that the global block inserter is adding the blocks outside the post content, so they get stripped on save.

Screen Shot 2019-06-27 at 08 59 05

### LINKED ISSUE #34330: Full Site Editing: Starter pages templates content appended after footer [5]
It seems that the starter page templates (Portfolio, Services, etc) assume the page will be empty. So now that we apply the FSE template when starting a new page (#34296), selecting any other template than Blank will result in the content of the selected page template to be appended after the footer template part.

Maybe related to https://github.com/Automattic/wp-calypso/issues/34327.

### LINKED ISSUE #34331: Full Site Editing: Post content block is removable [5]
When editing a full site page, we should make the post content block unremovable in order to avoid having pages without, well, content 😄.

Apart from losing the content, if a user remove the `a8c/post-content` block will result in an editor with the post title missing, given that since https://github.com/Automattic/wp-calypso/pull/34296 we're rendering the post title as part of the post content block when editing a full site page (and adding a `show-post-title-before-content` class to the `body` element that would keep the regular editor post title hidden).

### PR DESCRIPTION
**Pull request by mmtr**
#### Changes proposed in this Pull Request

This PR replaces the block inserter in the header toolbar with a custom one that ensures that new blocks are appended inside the post content block.

Jul-03-2019 09-56-12

Since the default inserter in the header toolbar rendered by Gutenberg doesn't set any `rootClientId` ([#](https://github.com/WordPress/gutenberg/blob/672bd9e06de74fec0fcddb81d083e792f800d42e/packages/edit-post/src/components/header/header-toolbar/index.js#L34)), we cannot define which block should contain any new inserted block.

This PR aims to solve that by rendering a replica of the same header inserter but using the client id of the post content block as `rootClientId`. The same client id is also used now when inserting a starter page template to avoid that content being appended after the footer (https://github.com/Automattic/wp-calypso/issues/34330).

In order to don't display the default header inserter, we lock the template making impossible to insert new blocks in the root (thus the header doesn't show the default block inserter). But this also prevents the user from removing existing blocks, which solves the issue of having the post content block removable (https://github.com/Automattic/wp-calypso/issues/34331).

#### Testing instructions

* Apply this branch to your FSE dev environment.
* Make sure the FSE plugin is activated.
* Create a new page.
* Select the blank template.
* Insert a block.
* Check the block has been inserted inside the post content block.
* Make sure you cannot insert any block in the root document.
* Verify root blocks (template parts and post content) cannot be moved.
* Create a new page again.
* Select a starter page template such as Portfolio or Services.
* Confirm the template content has been inserted inside the post content block.
* Go to Templates (`/wp-admin/edit.php?post_type=wp_template`).
* Trash all the templates (you also need to delete them permanently due to https://github.com/Automattic/wp-calypso/issues/34424).
* Create one more page.
* Select any template.
* Make sure blocks are inserted in the root document now.

Fixes #34327.
Fixes #34330.
Fixes #34331.

### CODE REVIEW

**Comment by mmtr** [comment]
Hmm, noted these warnings while loading an existing page with content:

Screen Shot 2019-07-03 at 10 29 42

Not sure if that's a bug in core Gutenberg or if maybe we need to define a new template passed to the editor settings when there is content. Will keep investigating.

**Comment by mmtr** [comment]
> Hmm, noted these warnings while loading an existing page with content:
> 
> Screen Shot 2019-07-03 at 10 29 42
> 
> Not sure if that's a bug in core Gutenberg or if maybe we need to define a new template passed to the editor settings when there is content. Will keep investigating.

Seems to be a core bug caused by having a parent block with a locked template and a nested block with an unlocked template: https://github.com/Automattic/wp-calypso/pull/34425#issuecomment-507903436

Will try to manually override the template validity by dispatching a `setTemplateValidity` action.

**Comment by mmtr** [comment]
> Will try to manually override the template validity by dispatching a `setTemplateValidity` action.

Fixed in 0443021

**Comment by glendaviesnz** [comment]
Nice work figuring out a solution to this! I ran through all the suggested testing steps quickly and it works as specified for me so far, but will do some more rigorous testing in the morning.

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php [hunk 1]
```diff
@@ -588,6 +588,7 @@ public function set_block_template( $editor_settings ) {
 				$template[] = fse_map_block_to_editor_template_setting( $block );
 			}
 			$editor_settings['template'] = $template;
+			$editor_settings['templateLock'] = 'all';
```
Comment (vindl) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php]: Nice!

**Comment by vindl** [comment]
Dang, I found an error in further testing. Everything works fine with existing pages, but when I try to add a new page I'm running into the blank screen with the following error:

`Uncaught TypeError: Cannot read property 'insertBefore' of null`

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing/editor/block-inserter/index.js [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+/**
+ * External dependencies
+ */
+import domReady from '@wordpress/dom-ready';
+import { render } from '@wordpress/element';
+import { Inserter } from '@wordpress/editor';
+import { compose } from '@wordpress/compose';
+import { withSelect } from '@wordpress/data';
+
+const PostContentBlockAppender = compose(
```
Comment (rodrigoi) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing/editor/block-inserter/index.js]: We should separate this into its own component file.

Comment (mmtr) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing/editor/block-inserter/index.js]: Moved in a1e8aed.

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing/editor/template-validity-override/index.js [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+ * block with a locked template containing a nested InnerBlocks with an unlocked template.
+ *
+ * @see https://github.com/WordPress/gutenberg/issues/11681
+ */
+function resetTemplateValidity() {
+	if ( 'page' !== fullSiteEditing.editorPostType ) {
+		return;
+	}
+
+	dispatch( 'core/editor' ).setTemplateValidity( true );
```
Comment (rodrigoi) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing/editor/template-validity-override/index.js]: `setTemplateValidity ` has been moved to `core/block-editor` and it's triggering a deprecation warning.

```suggestion
	dispatch( 'core/block-editor' ).setTemplateValidity( true );
```

**Comment by mmtr** [comment]
Thanks for the reviews @vindl @rodrigoi! 

The last commit should fix the `Uncaught TypeError: Cannot read property 'insertBefore' of null` error and I also moved the appender component to a separate file, so this should be ready for another pass.

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing/editor/block-inserter/index.js [hunk 4]
```diff
@@ -0,0 +1,47 @@
+/* global fullSiteEditing */
+
+/**
+ * External dependencies
+ */
+import domReady from '@wordpress/dom-ready';
+import { render } from '@wordpress/element';
+import { Inserter } from '@wordpress/editor';
```
Comment (rodrigoi) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing/editor/block-inserter/index.js]: `<Inserter />` has been moved to `@wordpres/block-editor` and it's triggering a deprecation warning.

```suggestion
import { Inserter } from '@wordpress/block-editor';
```

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing/editor/block-inserter/post-content-block-appender.js [hunk 5]
```diff
@@ -0,0 +1,26 @@
+/**
+ * External dependencies
+ */
+import { Inserter } from '@wordpress/editor';
```
Comment (rodrigoi) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing/editor/block-inserter/post-content-block-appender.js]: `<Inserter />` has been moved to `@wordpres/block-editor` and it's triggering a deprecation warning.

```suggestion
import { Inserter } from '@wordpress/block-editor';
```

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing/editor/template-validity-override/index.js (hunk 3 above)
Comment (mmtr) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing/editor/template-validity-override/index.js]: We still need to use `core/editor` in order to support sites not using the latest version: https://github.com/Automattic/wp-calypso/pull/34096

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing/editor/block-inserter/index.js (hunk 4 above)
Comment (mmtr) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing/editor/block-inserter/index.js]: https://github.com/Automattic/wp-calypso/pull/34425#discussion_r300818242

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing/editor/block-inserter/post-content-block-appender.js (hunk 5 above)
Comment (mmtr) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing/editor/block-inserter/post-content-block-appender.js]: https://github.com/Automattic/wp-calypso/pull/34425#discussion_r300818242

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing/editor/template-validity-override/index.js (hunk 3 above)
Comment (rodrigoi) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing/editor/template-validity-override/index.js]: Awesome!

**Comment by rodrigoi** [comment]
Excellent work @mmtr!!

**Comment by vindl** [comment]
Thank for the update @mmtr! Not sure if it's just me, but when testing locally I'm still running into an error when trying to create a new page, although a different one this time (likely not related with this PR but it gets in the way of testing):

`factory.js:45 Uncaught (in promise) TypeError: Cannot read property 'attributes' of undefined`

I logged this one here https://github.com/Automattic/wp-calypso/issues/34481 along with the PR that might have introduced it.

I also noticed that the inserter now appears before the back button, not sure if that was the case previously:

Screenshot 2019-07-08 at 21 00 36

But that can be handled in follow-up PRs as long as we log an issue to keep track of it.

**Comment by vindl** [comment]
Created another follow up issue to track incorrect inserter button position here: https://github.com/Automattic/wp-calypso/issues/34544
