### PR TITLE
Copy Post: Allow Copy Post on Atomic sites.

### LINKED ISSUE #29876: Gutenberg Calypsoify: Support Copy a Post Functionality
When given a query param of`?copy=postId` in the Gutenberg editor, let's start a new post with that post content and title copied. This issue will first fix the calypsoify flow from the Calypso post/page. We can iterate on duplication flows from wp-admin lists or as an extension on the Block Editor sidebar in separate followups outside of this issue.

See related https://github.com/Automattic/wp-calypso/issues/28555

#### Steps to reproduce
1. On an atomic site, visit the Calypso Page List or Post List
2. In the dropdown options select "duplicate a post" or "copy a post"
3. I'm navigated to `/wp-admin/post-new.php?calypsoify=1&copy=<postId>`
4. The postId title and content are pre-populated as expected

### PR DESCRIPTION
**Pull request by kwight**
With the `jetpack-copy` query parameter now consistent and active across [Calypso](https://github.com/Automattic/wp-calypso/pull/30800), Atomic, and [Jetpack](https://github.com/Automattic/jetpack/pull/11106), we can allow Copy Post for Atomic sites. This makes the Copy Post option available to all three site types, regardless of being Calypsoified or not. Note that the Copy Post feature does not rely on an editor either (it works with the Calypso, Classic, and Block editors).

Fixes #29876.

**Testing Instructions**
* Switch to this branch.
* Load `http://calypso.localhost:3000/posts/` and select an Atomic site with the Copy Post module enabled.
* Verify that the menu dropdown for posts has a Copy Post item, and that it works correctly (it loads a new post edit screen with the source content copied over).
* Disable the module, and verify the Copy Post item does not appear in Calypso's ellipsis menu any more.
* Repeat the process with a simple site. This should work properly, as before.
* Select a Jetpack site. The editor URL for Copy will be a Calypso URL, which should copy a new post as before.

### CODE REVIEW

**Comment by kwight** [comment]
@mmtr @dmsnell I realize that with my last commit, I'm hitting the problem again of needing the `QueryJetpackModules` query component to populate `state.jetpack.modules.items` (used by the `isJetpackModuleActive` selector). In #30506, you mentioned [expecting the query component in the same place as the selector](https://github.com/Automattic/wp-calypso/pull/30506/files#r255703700), but I don't see how to do that here: we don't want to render anything if the module isn't active, so how do we "render" the query component to get the dat in the first place? I think that was why I placed in higher in the tree before, and to also have that data already available when `PostActionsEllipsisMenuDuplicate` gets mounted (which is only once the user clicks the ellipsis to expose the menu). Any tips here?

File: client/my-sites/post-type-list/post-actions-ellipsis-menu/duplicate.jsx [hunk 1]
```diff
@@ -16,23 +16,23 @@ import PopoverMenuItem from 'components/popover/menu-item';
...
 	type,
+	copyPostIsActive,
 	duplicateUrl,
 	onDuplicateClick,
-	calypsoifyGutenberg,
 } ) {
 	const validStatus = includes( [ 'draft', 'future', 'pending', 'private', 'publish' ], status );
 
-	if ( ! canEdit || ! validStatus || 'post' !== type || calypsoifyGutenberg ) {
+	if ( ! canEdit || ! validStatus || 'post' !== type || ! copyPostIsActive ) {
```
Comment (gwwar) [inline client/my-sites/post-type-list/post-actions-ellipsis-menu/duplicate.jsx]: @kwight, if the component uses a selector that needs to be populated, we'd expect that component to also add the QueryComponent in the render function. There are some exceptions (say when we add query components to layout, but this help keeps it clear to the reader where the data is being populated from.)

In theory our data-layer should batch duplicate GET requests.

For QueryComponents to work, we always need to call this, so for example we may update this to:
```jsx
if ( shouldNotRenderUI ) {
    return ( <MyQueryComponent /> );
}

return (
<PopoverMenuItem>
    <MyQueryComponent />
    { myOtherChildren }
</PopOverMenuItem>
);
```

Comment (kwight) [reply client/my-sites/post-type-list/post-actions-ellipsis-menu/duplicate.jsx]: Worked a treat. The menu item still suddenly pops in the first time, but it's fine, I think. Thanks @gwwar !

**Comment by obenland** [comment]
> Would this be adding another values to the whitelist during transfer

It would need to be added to `A8C\Atomic\Jetpack_Manager::$active_modules` in `lib/atomic`. 
I'm sure you're aware, but that will only activate that module for new transfers, not existing Atomic sites.

**Comment by kwight** [comment]
Atomic activation follow-up patch in D25404-code.
