### PR TITLE
Fix copy-site > domain selection step header

### LINKED ISSUE #97155: Copy Site: overlapping header
### Quick summary

In Copy Site feature, the heading overlaps with the back button.

### Steps to reproduce

1. Go to `/settings/genera/:siteSlug`.
2. Scroll down and click "Copy site":

Image

### What you expected to happen

In narrower screen width, the header looks good.

### What actually happened

In narrower screen width, the header overlaps with the back button:

Image

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by gabrielcaires**
Closes #97155

## Proposed Changes
* Small style adjustments  on the step header

## Testing Instructions
- Go to /setup/copy-site/domains?sourceSlug=[SOME-WPCOM-STAGING-SITE-SLUG]

## Screenshots

Before
image

After

image

---

Mobile
image

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/landing/stepper/declarative-flow/internals/steps-repository/domains/index.tsx [hunk 1]
```diff
@@ -321,16 +321,8 @@ const DomainsStep: Step = function DomainsStep( { navigation, flow } ) {
...
-						[ HUNDRED_YEAR_PLAN_FLOW, HUNDRED_YEAR_DOMAIN_FLOW ].includes( flow )
-							? 'center'
-							: 'left'
-					}
-					subHeaderAlign={
-						[ HUNDRED_YEAR_PLAN_FLOW, HUNDRED_YEAR_DOMAIN_FLOW ].includes( flow )
-							? 'center'
-							: undefined
-					}
+					align="center"
```
Comment (sixhours) [inline client/landing/stepper/declarative-flow/internals/steps-repository/domains/index.tsx:324]: Have we confirmed that the hundred year plan flow won't use this screen and this logic can be removed? Just curious.

**Review by sixhours — APPROVED** [review]
Tested and this is working fine! Left a comment about the removal of the hundred-year plan logic.

File: client/landing/stepper/declarative-flow/internals/steps-repository/domains/index.tsx (hunk 1 above)
Comment (gabrielcaires) [reply client/landing/stepper/declarative-flow/internals/steps-repository/domains/index.tsx:324]: Yes, I confirmed the hundred-year requires center, and this screen also requires.
