### PR TITLE
Signup: Fix sites-list first time fetching

### LINKED ISSUE #2828: Signup: get stuck after adding a site during normal signup flow on a pre-existing account
Steps to reproduce:

<ol>
	<li>Go to <a href="https://wordpress.com/">https://wordpress.com/</a> and click "Create Website"</li>
	<li>Click Cubic theme</li>
	<li>Enter a domain and click "Select"</li>
	<li>Click "Select Free Plan"</li>
	<li>Enter email and discover you already have an account</li>
	<li>Click "log in now" link</li>
	<li>Enter login credentials and click "Log In"</li>
	<li>Land on step one in signup again</li>
	<li>Click "Skip"</li>
	<li>Try another domain "test"</li>
	<li>Click "Select" button next to the first result (again)</li>
	<li>Click "Select Free Plan" (again)</li>
	<li>"Almost done!" message gets stuck</li>
	<li>Eventually click My Site</li>
</ol>

<strong>Result:</strong> links to My Site and create a new post do not work unless you hard refresh. Aside: the "test8516" blog I entered in the 2nd signup step 2 didn't get created.

Console error:

```
TypeError: _sites.getPrimary(...) is undefined
build-…:19:29936
```

Video: https://cloudup.com/cxgWlTPEHOM

screen shot 2016-01-27 at wed jan 27 9 50 02 am
<sup>Seen at https://wordpress.com/ using Firefox 44.0 on Mac OS X 10.10.5</sup>

Found during user testing. (p4hfux-Qw-p2)

### PR DESCRIPTION
**Pull request by Tug**
Fixes #2828 

#### Fix Summary
The bug is that when sites-list is fetching for the first time, `initialized` will be `false` so `this.sync` won't ever switch back `fetching` to `false`. Further calls to `fetch` would then return immediately.

#### Testing instructions
- Do the signup flow as a logged in user
- Ensure you do not get stuck at the "Adding your domain step"

#### Review
- [x] Code Review
- [x] Product Review

### CODE REVIEW

File: client/lib/signup/step-actions.js [hunk 1]
```diff
@@ -37,10 +37,9 @@ function fetchSitesAndUser( siteSlug, onComplete ) {
 		},
 		callback => {
 			user.once( 'change', callback );
+			user.fetch();
```
Comment (Tug) [inline client/lib/signup/step-actions.js]: Let's group those 2 statements together since they are related

**Comment by fabianapsimoes** [comment]
Product :+1:

**Comment by scruffian** [comment]
LGTM :+1:
