### PR TITLE
Removing the last subscriber of the last page goes to previous page

### LINKED ISSUE #85540: Subscribers page: removing the last subscriber from the last page leaves it empty.
This is a bug in the subscriber list. These are the steps to reproduce it:
- Go to your subscriber page.
- Make sure you have only one subscriber on the last page of subscribers (you need to have at least two pages of subscribers to reproduce this).
- Remove that subscriber.
- BOOM! You will see an empty last page of subscribers:

Image

**Proposed solution:** when this situation happens, navigate to the previous page if the user is not on the first one.

### PR DESCRIPTION
**Pull request by JuanLucha**
☢️☢️☢️ Don't merge this one until https://github.com/Automattic/wp-calypso/pull/85572 is merged! ☢️☢️☢️
Fixes https://github.com/Automattic/wp-calypso/issues/85540

## Proposed Changes

This PR fixes this situation: 
- The site's owner is on the last page of their subscribers page. 
- There is only one subscriber there.
- The user removes that subscriber.
- The page has no subscribers, but the user is not redirected to the previous site.

## Testing Instructions

- Apply this PR and start the application.
- You need a site with more than one page of subscribers.
- Remove or add subscribers until the last page has only 1 subscriber.
- Remove that subscriber.
- You should be redirected to the previous page of subscribers (i.e., if you were on page 5 of subscribers, you will end up on page 4).

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: client/my-sites/subscribers/components/subscriber-list-container/subscriber-list-container.tsx [hunk 1]
```diff
@@ -26,14 +26,29 @@ const SubscriberListContainer = ( {
...
+	} = useSubscribersPage();
 	useRecordSearch();
 
 	const isSimple = useSelector( isSimpleSite );
 	const isAtomic = useSelector( ( state ) => isAtomicSite( state, siteId ) );
 	const EmptyComponent = isSimple || isAtomic ? SubscriberLaunchpad : EmptyListView;
 
+	useEffect( () => {
+		if ( ! isLoading && subscribers.length === 0 && page > 1 ) {
+			const newPageNumber = page - 1;
```
Comment (phcp) [inline client/my-sites/subscribers/components/subscriber-list-container/subscriber-list-container.tsx]: @JuanLucha The `useSubscribersQuery` returns the total number of pages (`pages` prop); we could pass these values to the context and use it here instead of decrementing the current page. It would avoid multiple useEffects in sequence.

**Review by phcp — COMMENTED** [review]
I think the effect loop could be problematic on a invalid input. For example, if the user mistakenly types some zeros after the page number it would make several requests to the subscribers endpoint until getting to the actual last page. I left one suggestion on how we could handle it.

File: client/my-sites/subscribers/components/subscriber-list-container/subscriber-list-container.tsx (hunk 1 above)
Comment (JuanLucha) [reply client/my-sites/subscribers/components/subscriber-list-container/subscriber-list-container.tsx]: Good point! I'll do it! Thanks, @phcp !

**Review by phcp — APPROVED** [review]
Great job @JuanLucha! The PR looks good and works as expected.
