### PR TITLE
Subscriptions Management: Fix `subscription_date` timezone offset and `post_title` overflow on the Comments page

### LINKED ISSUE #75902: `/subscriptions/comments`: Fix `post_title` overflow
Long post titles are overflowing out of their column.

More context: p1681810277308639/1681808098.652289-slack-C02TCEHP3HA.

### PR DESCRIPTION
**Pull request by ivan-ottinger**
Fixes https://github.com/Automattic/wp-calypso/issues/75902 and https://github.com/Automattic/wp-calypso/issues/75901 

## Proposed Changes

* fix `subscription_date` timezone offset: The timestamp received from the endpoint is in UTC, but is missing timezone information. → This PR adds it in.
* fix `post_title` overflow

Markup on 2023-04-18 at 16:25:25

## Testing Instructions

1. Check out and build the PR locally.
2. Apply the correct `subkey` cookie value to your `calypso.localhost:3000` host.
3. Make sure the related user has existing comment subscriptions - while at least one of the posts needs to have a long post title.
4. Subscribe to comments on one of your posts and note the current time.
5. Navigate to http://calypso.localhost:3000/subscriptions/comments and review the page.
6. Check if the long post title is not overflowing and that the subscription date matches with the time you noted in the point 4 (you can hover over the date to see it in full)

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: packages/data-stores/src/reader/queries/use-post-subscriptions-query.ts [hunk 1]
```diff
@@ -60,7 +60,7 @@ const usePostSubscriptionsQuery = ( {
 		// Transform the dates into Date objects
 		const transformedData = flattenedData?.map( ( comment_subscription ) => ( {
 			...comment_subscription,
-			subscription_date: new Date( comment_subscription.subscription_date ),
+			subscription_date: new Date( comment_subscription.subscription_date + ' UTC' ),
```
Comment (ivan-ottinger) [inline packages/data-stores/src/reader/queries/use-post-subscriptions-query.ts:63]: Would you keep this change in the frontend - or would you address it on the endpoint side? I see benefits in both approaches, but would be interested in hearing your point of view.

**Comment by ivan-ottinger** [comment]
This PR is now ready for review.

File: packages/data-stores/src/reader/queries/use-post-subscriptions-query.ts (hunk 1 above)
Comment (yansern) [reply packages/data-stores/src/reader/queries/use-post-subscriptions-query.ts:63]: Frontend. This gives room for endpoint to be cached, if the user flies from NL to BG on the same day and the hour changes.

Comment (ivan-ottinger) [reply packages/data-stores/src/reader/queries/use-post-subscriptions-query.ts:63]: But in both cases (implementation in front-end vs back-end), the `new Date()` is still getting the same input string. The difference is where the `UTC` is appended to the end of that string.

**Comment by yansern** [comment]
Offset adjustment is correct.

image

Text is truncated/ellipsed.
image

**Review by yansern — APPROVED** [review]

File: packages/data-stores/src/reader/queries/use-post-subscriptions-query.ts (hunk 1 above)
Comment (yansern) [reply packages/data-stores/src/reader/queries/use-post-subscriptions-query.ts:63]: Ah you're talking about appending the `UTC` string on the frontend or backend (not about the timezone offsets). 
I would append `UTC` string on the front end since this is something that `new Date()` is expecting.

Comment (ivan-ottinger) [reply packages/data-stores/src/reader/queries/use-post-subscriptions-query.ts:63]: In that case, I will leave the UTC string on the frontend side - just so we can move forward with the deployment of the Comments tab and then will remove it in the later PR, while also adding the UTC string on the endpoint.
