### PR TITLE
NUX: use appropriate page titles during signup

### LINKED ISSUE #3173: Signup NUX: Page title doesn't change between steps - always "Create an account"
When going through signup steps, the page title always displays "Create an account".

**Steps to reproduce**

1. Visit https://wordpress.com/start/
2. Look at page title
3. Choose a theme
4. Look at page title

create an account

**Expected Result**

It would be nice to see titles change as per the current signup step (these should be localized)

1. Choose a theme
2. Choose a domain
3. Pick a plan 

etc

### PR DESCRIPTION
**Pull request by alisterscott**
Fixes #3173 

Each step of the signup will now have the correct page title, and the account signup flow will have a different title

*****

**Creating an Account BEFORE**

before account

**Creating an Account AFTER**

after account

*****

**Creating a Site (new user) BEFORE**

before site

**Creating a Site (new user) AFTER**

after site

*****

**Creating a Site (existing user signed in) BEFORE**

create account signed in before

**Creating a Site (existing user signed in) AFTER**

create account signed in after

### CODE REVIEW

File: client/signup/main.jsx [hunk 1]
```diff
@@ -41,6 +41,8 @@ import utils from './utils';
 import { currentUserHasFlag, getCurrentUser } from 'state/current-user/selectors';
 import { DOMAINS_WITH_PLANS_ONLY } from 'state/current-user/constants';
 import * as oauthToken from 'lib/oauth-token';
+import DocumentHead from 'components/data/document-head';
+import i18n from 'i18n-calypso';
```
Comment (bisko) [inline client/signup/main.jsx]: There is no need to import the whole `i18n-calypso` library here, when we're just using `translate`.

It can be done like this:

```
import { translate } from 'i18n-calypso';
...
return this.props.flowName === accountFlowName ? translate( 'Create an account' ) : translate( 'Create a site' );
```

Comment (alisterscott) [inline client/signup/main.jsx]: Thanks, updated the code just now.

File: client/signup/main.jsx [hunk 2]
```diff
@@ -329,6 +331,11 @@ const Signup = React.createClass( {
 			null;
 	},
 
+	pageTitle() {
+		const accountFlowName = 'account';
+		return this.props.flowName === accountFlowName ? translate( 'Create an account' ) : translate( 'Create a site' );
```
Comment (jordwest) [inline client/signup/main.jsx]: Should this always fall back to "Create a site"? Not sure if there's anything else `props.flowName` could be, but there may be in the future.

Comment (alisterscott) [inline client/signup/main.jsx]: Thanks. I checked client/signup/config/flows.js and account is the only one that is different, the rest are variations on creating a site
