### PR TITLE
Export Media: Hide when No Files are Present

### LINKED ISSUE #32109: Exporter: Redundant media library export failure notice for sites without media files
#### Steps to reproduce 

- With a site without media library files, visit https://wordpress.com/settings/general 
- Click on the `Export` section available on that page

#### What is expected 

There is no `We couldn't export your media library at the moment. Please try again later.` failure notice shown.

#### What happens instead

A `We couldn't export your media library at the moment. Please try again later.` failure notice appears out of nowhere. In particular, it can be noted that this happens without having to click on `Export all` button for `.xml` export, or `Download` for media library files export.

No warnings/errors shown on console.

Screenshot 2019-04-08 at 19 51 13
Screenshot 2019-04-08 at 19 51 26

The failure notice seems to be redundant and should not appear unless the media library exporter is used, and fails.

#### Notes

I have noticed that this happens particularly for sites without media library files and for sites with one or more media library files, that notice does not appear.

Screenshot 2019-04-08 at 19 55 17 

#manual-testing

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

This removes the "Export media library" section from the Exporter when no media files are available.

#### Testing instructions

1. Start on a site with no media files
2. Head to the Exporter and verify you can't export your Media Library
3. Upload a file
4. Verify the Exporter works as usual 

cc @arunsathiya, @creativecoder, @southp 

Fixes #32109

### CODE REVIEW

**Comment by arunsathiya** [comment]
I am marking this for design review as well, because I am wondering if we can show `Upload files first` in that place or to see if there's a better option.

File: client/my-sites/exporter/export-media-card/index.js [hunk 1]
```diff
@@ -61,6 +67,7 @@ class ExportMediaCard extends Component {
 export default connect(
 	state => ( {
 		mediaExportUrl: getMediaExportUrl( state ),
+		mediaStorageUsed: getMediaStorageUsed( state, getSelectedSiteId( state ) ),
```
Comment (mmtr) [inline client/my-sites/exporter/export-media-card/index.js:70]: Nitpick: since `mediaStorageUsed` is used only for setting `hasNoMediaFiles`, I think we can expose a `hasNoMediaFiles` prop directly here.

 ```suggestion
		hasNoMediaFiles: getMediaStorageUsed( state, getSelectedSiteId( state ) ) === 0 && ! getMediaExportUrl( state ),
```

Comment (Aurorum) [reply client/my-sites/exporter/export-media-card/index.js]: Yep, done! :)

**Comment by Aurorum** [comment]
> What if we hide entirely the "Export media library" section? I don't think it makes sense to encourage users to upload media when they only want to export their content.

Yeah, that makes sense. I was thinking that people would appreciate knowing it's possible to export their Media Library, but it'd be odd to want to export your site before uploading a media file anyway. I've made that change now. :)
