### PR TITLE
Post Editor: Fix post attributes reverting after a post copy

### LINKED ISSUE #12536: Bug: Editor Publicize Custom Message Reverting To Default
#### Steps to reproduce
1. Starting at WP.com new post
2.  Post Settings - Sharing
3. Type customised message to share post via twitter
4. Hit save

#### What I expected
The custom text would save ready for when I decided to publish

#### What happened instead
What I typed reverted back to the default post title.

#### Browser / OS version
Chrome 57.0.2987.98

#### Screenshot / Video
twitter

#### Context / Source
On this occasion this happened after I had selected a previous post to copy and edited. It's happened a number of times this week but I can't remember if I had chosen to copy a post on every occasion.

### PR DESCRIPTION
**Pull request by Copons**
Fixes #12536

Follow up #12506

This PR fixes a Copy Post zero-day bug: when changing some attributes on a freshly copied post, their values would revert to their original (copied) values at post save.
The only workaround was to copy the post, save it or let it autosave, and reload the page. Once reloaded, the post would behave as expected.

It took me quite some time to identify this issue as the Post Editor consists of a heavily intertwined tangle of Flux and Redux. Some attributes are managed by Flux, some others by Redux; some look managed by both but in fact they respond to only one's actions (the post title!).

Now though, the PR was written to fix two attributes reverts in particular: the featured image and the sharing message (which is a metadata).

## Fixing the Metadata

Turns out it's not enough to send them to the dispatcher as-is (array of objects):
```js
[
  { key: 'foo', value: 'bar' },
  { key: 'baz', value: 'qux' },
]
```
But [they must be submitted as a single object](https://github.com/Automattic/wp-calypso/blob/master/client/lib/posts/actions.js#L25-L75) such as:
```js
{
  foo: 'bar',
  baz: 'qux',
}
```
Enough said, I guess.
Once reduced the array into an object, the sharing message (and for that matters every other metadata) gets copied correctly.

## Fixing the Featured Image

There's not much to be said here.
The debugging consisted of an endless amount of commenting stuff out until at some point I realized that there was only one thing I've never ever commented out: the Redux `editPost()` action.
Once commented it, the featured image worked smoothly.
Unfortunately I couldn't completely get rid of it, as title and categories (note: not all terms but only categories; tags are managed without issues by Flux only) are only managed via Redux.
Though, I went on the conservative side, with a Redux-managed attributes whitelist replacing the previous, too optimistic, "blanket" list (basically, I passed the same attributes list to both Flux and Redux).

Currently, the Redux-whitelisted attributes are only `title` and `terms`. Though I expect this list to grow over time, as we gradually Reduxify the entire Post Editor.

## Testing Instructions

- Create and save a new post complete of the following attributes:
  - title
  - content
  - featured image
  - categories
  - tags
  - sharing message (found in *Post Drawer → Sharing*, after connecting a social media to the site)
- Go back to the posts list, locate the newly created post and *Copy* it (copy button is in the *More* part of the post controls).
- Check that all those attributes show up as inserted and expected.
- Modify every single one of those attributes.
- Manually save the draft (or wait for an autosave).
- Check that the attributes values are still filled as expected and **that not a single one of them reverted to its original (copied) value**.
Especially check the featured image (which should be quite obvious) and the sharing message.

### CODE REVIEW

File: client/post-editor/controller.js [hunk 1]
```diff
@@ -135,13 +134,24 @@ function startEditingPostCopy( siteId, postToCopyId, context ) {
 		postAttributes.title = decodeEntities( postAttributes.title );
 		postAttributes.featured_image = getFeaturedImageId( postToCopy );
 
+		const reduxPostAttributes = {
```
Comment (gwwar) [inline client/post-editor/controller.js]: Can we maybe leave a comment here on why we're whitelisting

**Comment by Copons** [comment]
@gwwar Documentation added!
