### PR TITLE
Gutenframe: Add a denied list of plugins that will not allow Gutenframe.

### LINKED ISSUE #32887: Gutenframe: Editing with Elementor plugin triggers X-Frame-Options/sameorigin error
#### Steps to reproduce
1. Start with any Jetpack site in Calypso
2. Install the 'Elementor' plugin (https://wordpress.org/plugins/elementor/)
3. Edit a new page
4. Click 'Edit with Elementor' button

#### What I expected

Elementor to load the fullscreen editor (as would happen by clicking the 'Edit with Elementor' link in wp-admin/posts (eg /wp-admin/post.php?post=16&action=elementor)

#### What happened instead

Browser shows a 'Refused to connect' error and console has an error:
`Refused to display[URL] in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

#### Browser / OS version
Mac OS 10.13, Chrome Version 74.0.3729.131

#### Screenshot / Video

Screen Shot 2019-05-08 at 12 51 45 pm

Screen Shot 2019-05-08 at 12 51 26 pm

#### Context / Source
#user-report in 2015542-zen

### LINKED ISSUE #32934: Gutenframe: Audit popular plugins for blacklist.
Some plugins (such as page builders) may result in confusing, broken, or unintended flows by being iframed with Gutenframe. #32915 adds the capability to blacklist plugins by slug; let's do an audit of the most popular plugins on Atomic sites and see if anything else needs to be added to that blacklist before attempting another launch of Gutenframe for Jetpack sites.

### PR DESCRIPTION
**Pull request by kwight**
#### Changes proposed in this Pull Request

* Add the `isAnyPluginActive` selector to determine if any of the denied plugins are active on the current site.
* If so, Gutenframe will fall back to a standard redirect to the `wp-admin` block editor.

#### Testing instructions

* Install a denied plugin on a test JP site.
* Load the site at `/block-editor/post/:site`, and verify you are forwarded instead to the site's WP Admin block editor.

Fixes #32887.
Fixes #32934.

### CODE REVIEW

**Comment by kwight** [comment]
The selector doesn't work; I can see that it's always returning an empty array. Maybe the string interpolation isn't working correctly?

File: client/state/selectors/is-any-plugin-active.js [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+ * from a given array. This is useful for jetpack connected sites.
+ *
+ * @param {Object} state - Global state tree
+ * @param {Number} siteId - Site ID
+ * @param {Array} pluginSlugs - Array of plugin slugs for which to check
+ * @return {Boolean} - truthiness of a site having at least one of the given plugins active
+ */
+export default function isAnyPluginActive( state, siteId, pluginSlugs ) {
+	const sitePlugins = get( state, `plugins.installed.plugins[ ${ siteId } ]`, [] );
+	const matches = sitePlugins.filter(
```
Comment (vindl) [inline client/state/selectors/is-any-plugin-active.js]: We could reuse the existing `getPlugins` [selector](https://github.com/Automattic/wp-calypso/blob/master/client/state/plugins/installed/selectors.js#L62) to simplify this (at which point we might not need a separate selector). For example:

```javascript
const activePlugins = getPlugins( state, siteId, 'active' );

return !! intersectionWith( activePlugins, blacklistPlugins, ( ap, bp ) => ap.slug === bp );
```

File: client/state/selectors/is-plugin-replacing-wp-admin-editor.js [hunk 2]
```diff
@@ -0,0 +1,23 @@
+/** @format */
+
+/**
+ * Internal dependencies
+ */
+import isPluginActive from 'state/selectors/is-plugin-active';
+
+// List of known plugins that replaces the default WP Admin editor.
+const pluginBlacklist = [ 'elementor' ];
```
Comment (obenland) [inline client/state/selectors/is-plugin-replacing-wp-admin-editor.js]: Can we change this to `deniedPluginsList`?

File: client/state/selectors/is-plugin-replacing-wp-admin-editor.js [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+
+/**
+ * Indicates whether a site has active a plugin that replaces the default WP Admin editor with other custom editor.
+ *
+ * @param {Object} state - Global state tree
+ * @param {Number} siteId - Site ID
+ * @return {Boolean} - truthiness of a site having at least one conflicting plugin active
+ */
+export default function isPluginReplacingWpAdminEditor( state, siteId ) {
```
Comment (obenland) [inline client/state/selectors/is-plugin-replacing-wp-admin-editor.js]: How do you feel about `hasEditorConflictingPlugin`?

Comment (mmtr) [reply client/state/selectors/is-plugin-replacing-wp-admin-editor.js]: Sounds good, but I think we should indicate clearly we're talking about the WP Admin editor and not about the Calypso editor, so `hasWpAdminEditorConflictingPlugin ` should clarify that.

File: client/state/selectors/get-gutenberg-editor-url.js [hunk 4]
```diff
@@ -8,6 +8,7 @@ import { getEditorPath } from 'state/ui/editor/selectors';
 import { isEnabled } from 'config';
 import isSiteAtomic from 'state/selectors/is-site-automated-transfer';
 import { addQueryArgs } from 'lib/route';
+import hasWpAdminEditorConflictingPlugin from 'state/selectors/has-wp-admin-editor-conflicting-plugin';
```
Comment (kwight) [inline client/state/selectors/get-gutenberg-editor-url.js]: I don't like the selector being so specific (at least in name); it should be usable anywhere in Calypso, with any array of slugs for whatever purpose, I think.

File: client/state/selectors/has-wp-admin-editor-conflicting-plugin.js [hunk 5]
```diff
@@ -0,0 +1,23 @@
+/** @format */
+
+/**
+ * Internal dependencies
+ */
+import isPluginActive from 'state/selectors/is-plugin-active';
+
+// List of known plugins that replaces the default WP Admin editor.
+const deniedPluginsList = [ 'elementor' ];
```
Comment (kwight) [inline client/state/selectors/has-wp-admin-editor-conflicting-plugin.js]: If we kept the array of slugs to check out of the selector, and always have them passed in, then the selector is more capable of other uses than our own here.

File: client/state/selectors/is-any-plugin-active.js (hunk 1 above)
Comment (kwight) [reply client/state/selectors/is-any-plugin-active.js]: Ooooh, I like this way better; added d842546 for evaluation.

File: client/state/selectors/is-wp-admin-gutenberg-enabled.js [hunk 6]
```diff
@@ -9,8 +14,11 @@ import isSiteAutomatedTransfer from 'state/selectors/is-site-automated-transfer'
 import getWordPressVersion from 'state/selectors/get-wordpress-version';
 import versionCompare from 'lib/version-compare';
 import isPluginActive from 'state/selectors/is-plugin-active';
+import getPlugins from 'state/plugins/installed';
 import { isHttps } from 'lib/url';
 
+export const blacklistedPlugins = [ 'elementor' ];
```
Comment (obenland) [inline client/state/selectors/is-wp-admin-gutenberg-enabled.js]: Can we also rename this to `deniedPluginsList` please?

File: client/state/selectors/is-any-plugin-active.js (hunk 1 above)
Comment (mmtr) [reply client/state/selectors/is-any-plugin-active.js]: Thanks @kwight! 

As discussed on Slack, I don't have any strong objection about this approach. But I see some benefits on having the logic encapsulated in terms of code maintenance. Otherwise we should duplicate the same `getPlugins`/`intersectionWith` logic in `isWpAdminGutenbergEnabled`, `isGutenframeEnabled` and `getGutenbergEditorUrl`.

But I see your point of making that selector more abstract and less specific by keeping the array of slugs out of it.

On 5a8919e441e29daf2022d9e0be7c4a1813f94b28 I brought back your original more-generic `isPluginActive` selector and and moved the definition of the denied plugins list to `lib/plugins`.

File: client/lib/plugins/utils.js [hunk 7]
```diff
@@ -161,7 +161,7 @@ export function normalizePluginData( plugin, pluginData ) {
 				returnData.author_name = extractAuthorName( item );
 				returnData.author_url = plugin.author_url || extractAuthorUrl( item );
 				break;
-			case 'sections':
+			case 'sections': {
```
Comment (mmtr) [inline client/lib/plugins/utils.js]: This change is unrelated to the PR, but needed since ESLint was complaining about `cleanItem` being defined in a `case` clause (see [`no-case-declarations`](https://eslint.org/docs/rules/no-case-declarations)).

**Comment by kwight** [comment]
Fantastic, this works well (as long as JP Sync can keep up with activation/deactivation from the JP side – I haven't seen problematic delays yet).
