### PR TITLE
Fix Jetpack Search checkout variant dropdown prices

### LINKED ISSUE #63233: Pricing discrepancy on Jetpack Search
### Quick summary

When I tried to add Jetpack Search to my site, it says it’s $3/mth billed annually. But when it’s added to my cart it’s charging $144 (CAD)

### Steps to reproduce

1. On an AT site with currency set as CAD, go to Jetpack > Settings > Performance
2. Click the Upgrade option for Jetpack Search
3. Page displays an introductory price of $3/month billed yearly (discounted from $6/month)
4. Proceed to checkout and the amount in the checkout is $144 (though you may have to have clicked the Upgrade button twice)

https://user-images.githubusercontent.com/42655541/166343818-899c28aa-34c6-41b1-b713-85eed26639f8.mp4

Another test on USD site, after first click of the upgrade button - it's not reflecting the discounted price, but is still the right regular price:

https://user-images.githubusercontent.com/42655541/166343937-761c873b-4acd-4e28-88fb-df8427fd4ec2.mp4

After second click of the upgrade button, the cost doubles the regular annual price:

https://user-images.githubusercontent.com/42655541/166343950-9b71b412-c2f4-4acf-aa92-912102001e06.mp4

In both cases we chose to "Empty cart" when leaving the checkout.

### What you expected to happen

I expected the checkout to reflect $36CAD when I added it to my cart. (And $30USD on the second example.)

### What actually happened

The cart reflected double the price of the regular, non-discounted cost.

### Context

Stumbled on this because of internal testing for another purpose.

I'm not sure what to mark severity as but I suspect this might be happening for anyone trying to add Jetpack Search?

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

_No response_

### Browser, operating system and other notes

_No response_

### Reproducibility

Consistent

### Severity

_No response_

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by elliottprogrammer**
#### Changes proposed in this Pull Request

The tiered prices for Jetpack Search are incorrectly displayed in checkout (in the term variant dropdown), for sites above the 1st tier, (sites with more than 100 records). This PR fixes the term variant dropdown prices for Jetpack Search tiered prices.

search-checkout-pricing

Related to: 
- 1164141197617539-as-1201985749766679/f
- 1164141197617539-as-1202210164385929/f
- p1647507273547209-slack-CQXNTE9K9

Fixes: #63233 

#### Testing instructions

1. You'll need a Jetpack site with more than 100 posts. If you don't already own one, create a Jurassic Ninja site, connect Jetpack (Select Free plan), and then add & install the "Duplicate Posts" plugin. Duplicate a post 101+ times and publish, so that your site now has more than 100 posts.
2. Checkout this PR and spin up Calypso blue (`yarn start`).
3. Go to: http://calypso.localhost:3000/checkout/:SITE/jetpack_search (replace **:SITE** with the site-slug of your site).
4. You should now be in Checkout, with Jetpack search in your cart.
5. In the dropdown term variant items (for a site with 101 - 1000 records), verify the yearly price is correct at **$59.50** and the monthly price is at **$10**
6. Now load checkout with Jetpack Search, with a site with < 100 records. Verify the dropdown variant item prices are correct at **$29.97** (yearly) and **$5** (monthly).

- You'll notice that the full price (that is striked-through with a line) in the variant dropdown displays as **$120**, when it should be **$119**.  (See screenshot below). This is not an issue with the code, it is because the _monthly_ price for Search is not set correctly in the _product pricing table_.  The monthly price for Search is set to **$10** (tier 2), but the monthly price should actually be set to: **$9.92**. This will need to be addressed in a follow-up PR.
Markup 2022-05-15 at 21 28 08

#### Screenshots:

Markup 2022-05-17 at 09 22 15

Markup 2022-05-17 at 09 23 52

### CODE REVIEW

**Review by manzoorwanijk — COMMENTED** [review]
Code looks good but I tested with local currency (INR) and things don't seem to be right.

### For yearly plan

Screenshot 2022-05-16 at 1 20 57 PM

### For monthly plan

Screenshot 2022-05-16 at 1 21 51 PM

File: client/my-sites/checkout/composite-checkout/composite-checkout.tsx [hunk 1]
```diff
@@ -660,6 +662,14 @@ export default function CompositeCheckout( {
 		reduxDispatch( infoNotice( translate( 'Redirecting to payment partner…' ) ) );
 	}, [ reduxDispatch, translate ] );
 
+	const cartHasSearchProduct = useMemo(
+		() =>
+			items.some( ( { type } ) =>
```
Comment (sirbrillig) [inline client/my-sites/checkout/composite-checkout/composite-checkout.tsx]: This is not a big deal, but I think it would be better to use `responseCart.products` here rather than `items`. The reason is that `items` is a type of data has been deprecated (see https://github.com/Automattic/wp-calypso/pull/49580) and should probably be removed (in fact, thanks for the reminder!).

**Comment by elliottprogrammer** [comment]
> Code looks good but I tested with local currency (INR) and things don't seem to be right.

@manzoorwanijk, I can't seem to reproduce what's showing in your screenshots. Your screenshots look like the original issue that this PR fixes.. 🤔   Could you re-check to make sure you weren't accidentally looking at production? However, if you are able to reproduce the issue, can you describe your steps?  Thanks much! 🙂

Here's how currency INR is showing for me:

Markup 2022-05-16 at 19 22 00

File: client/my-sites/checkout/composite-checkout/composite-checkout.tsx (hunk 1 above)
Comment (elliottprogrammer) [reply client/my-sites/checkout/composite-checkout/composite-checkout.tsx]: Awesome, makes sense. Thanks for catching that. 👍 
Fixed.

**Comment by manzoorwanijk** [comment]
> Could you re-check to make sure you weren't accidentally looking at production?

Yes, it looks like I checked the wrong page. Everything works fine now. Sorry about the confusion.

**Review by manzoorwanijk — APPROVED** [review]

File: client/state/products-list/selectors/compute-full-and-monthly-prices-for-plan.js [hunk 2]
```diff
@@ -55,3 +64,27 @@ function computePricesForWpComPlan( state, siteId, planObject ) {
...
+function getSearchProductTierPrice( state, siteId, productSlug ) {
+	const postsCounts = getAllPostCounts( state, siteId, 'post' );
+	const postsCount = postsCounts?.publish || 0;
+	const priceTierList = getProductPriceTierList( state, productSlug );
+	const tier = priceTierList.filter(
+		( tierItem ) => postsCount >= tierItem.minimum_units && postsCount <= tierItem.maximum_units
+	);
+	const minPrice = tier[ 0 ].minimum_price.toString(); // is missing decimal, ie- $9.95 is returned as 995
+	return (
+		// Inject decimal point into 100ths position.
```
Comment (sirbrillig) [inline client/state/products-list/selectors/compute-full-and-monthly-prices-for-plan.js:85]: How does this work with currencies that do not use a decimal (eg: JPY)?
