### PR TITLE
Editor: show warning when updating a published post date

### LINKED ISSUE #10358: Editor: warn about links when changing post date
When you change the date for a post, you have the potential to break existing links to that post. We should at least warn people about this. This was particularly bothersome when coupled with this issue where posts get the wrong post date. https://github.com/Automattic/wp-calypso/issues/9014

### PR DESCRIPTION
**Pull request by gwwar**
Fixes #10358, this adds a warning when a user attempts to update the date of an already published post. Updating this will create a new post url, and the url will not work.

screen shot 2017-02-10 at 11 23 57 am

### Testing Instructions
- Navigate to to http://calypso.localhost:3000/post
- Select a site
- Add some content
- Publish your post
- Click on the calendar button, and set a date in the past or future
- Warning should display

### CODE REVIEW

**Comment by gwwar** [comment]
Just a sec, I need to limit this check to posts only

**Comment by obenland** [comment]
If the URL breaks based on a date change that feels like a calypso bug. AFAIK old URLs should redirect to updated ones, no?

**Comment by gwwar** [comment]
Ideally old links would 302, but I think we should still point out that we do update the url

**Comment by retrofox** [comment]
should we remove the warning message if the setting date is canceled? (close the PostSchedule pressing the `ESC` key)

**Comment by gwwar** [comment]
> should we remove the warning message if the setting date is canceled? 

Good catch, didn't realize <kbd>esc</kbd> was clearing out the date changes

**Comment by retrofox** [comment]
> Good catch, didn't realize esc was clearing out the date changes

I think in general `ESC` means cancel action in popovers. `clickoutside` not necessarily.

**Comment by gwwar** [comment]
Updated to account for <kbd>esc</kbd> behavior in c861b47

**Comment by gwwar** [comment]
Thanks @retrofox I'll do a moment comparison

File: client/post-editor/editor-ground-control/index.jsx [hunk 1]
```diff
@@ -174,7 +185,7 @@ export default React.createClass( {
 				: null;
 
 			this.setPostDate( date );
-			this.props.warnPublishDateChange( { clearWarning: true } );
+			// this.props.warnPublishDateChange( { clearWarning: true } ); -> not needed anymre
```
Comment (gwwar) [inline client/post-editor/editor-ground-control/index.jsx]: You can just remove this then 👍

**Comment by gwwar** [comment]
Oh you beat me, thanks @retrofox I'll test, but we'll probably need a third person to 👍

**Comment by retrofox** [comment]
added this commit: 77f71fa4b86b5a0f322a3f68e8a7ff902a485a91

I thinks is better compare the dates using moment() instead of the string. And lets remove the warn on the fly.

editor-warning-03

I've comment the line when it was removed.

File: client/post-editor/editor-ground-control/index.jsx [hunk 2]
```diff
@@ -134,6 +136,24 @@ export default React.createClass( {
...
+
+		if ( ! savedPost ) {
+			return;
+		}
+
+		const currentDate = this.moment( date );
+		const ModifiedDate = this.moment( savedPost.date );
+		const diff = !! currentDate.diff( ModifiedDate );
+
+		if ( savedPost.type !== 'page' && postUtils.isPublished( savedPost ) && diff ) {
```
Comment (gwwar) [inline client/post-editor/editor-ground-control/index.jsx]: Oh it looks like posts are the only ones that have date based links? I tried a few cpts and they didn't appear to have this issue.

**Comment by iamtakashi** [comment]
Design wise 👍

**Comment by retrofox** [comment]
Let's rebase this commit https://github.com/Automattic/wp-calypso/pull/11337/commits/f89f021bd0f17c1df1e98d9dea786cca2c59c1f4 please Kerry before to definitely :shipit:
it looks nice.

File: client/post-editor/editor-ground-control/index.jsx [hunk 3]
```diff
@@ -123,8 +123,10 @@ export default React.createClass( {
 	},
 
 	setPostDate: function( date ) {
+		const dateValue = date ? date.format() : null;
 		// TODO: REDUX - remove flux actions when whole post-editor is reduxified
-		postActions.edit( { date: date ? date.format() : null } );
+		postActions.edit( { date: dateValue } );
+		this.showDateWarning( dateValue );
```
Comment (rralian) [inline client/post-editor/editor-ground-control/index.jsx]: The naming is a little misleading here. That method checks whether a warning is necessary. When I see `showDateWarning()` I expect that it will be shown. Maybe this should be `checkForDateChange()`?

Comment (retrofox) [inline client/post-editor/editor-ground-control/index.jsx]: `showWarnIfDateChange()`?

Comment (rralian) [inline client/post-editor/editor-ground-control/index.jsx]: IMHO it should just be `checkForDateChange()` and that method should call the methods that actually do things. Maybe we'll want to do other things in the future based on a date change.

Comment (gwwar) [inline client/post-editor/editor-ground-control/index.jsx]: Updated in 20ef315

**Comment by gwwar** [comment]
Thanks for the reviews! Could I get someone else to smoke test this as well before I deploy?

cc @rralian @obenland

**Comment by obenland** [comment]
Tested it and it works as expected!

**Comment by gwwar** [comment]
Thanks @obenland !
