### PR TITLE
Fix/signup field validation

### LINKED ISSUE #16684: Signup: better handling of form validation
We should rethink how form validation is being handled in Calypso — specifically the timing of when exactly are we validating the fields in the signup page: https://wordpress.com/start/account/user

When this page is loaded we autofocus on the first field (no problem there), but since we're doing validation on _all fields_ when _any click outside the form_ takes place, it leads to a barrage of errors like this:

signup-validation-01

This is especially flagrant when a user already has an account and wants to click the log in link at the bottom, and sees a red sea of errors flashing while they're being redirected:

signup-validation-02

Thoughts @folletto @mtias ?

Good reference on validation timing: https://medium.com/@andrew.burton/form-validation-best-practices-8e3bec7d0549#2d03

### PR DESCRIPTION
**Pull request by davemart-in**
### The Problem

This PR attempts to remedy a couple of overly aggressive form validation use cases:

1) onBlur triggers validation on all fields (even one's we've yet to get to yet)

2) Debounce triggers validation on all fields (even one's we've yet to get to yet)

### The Solution

With this patch applied, we fix the over aggressive validation messages:

#### Testing instructions

- Check out branch
- Recompile
- Test changes on http://calypso.localhost:3000/start/user

Fixes #16684
Which was technically closed in response to #18058, but that PR only fixed part of the problem (entering nothing and then clicking a link)

### CODE REVIEW

**Review by blowery — APPROVED** [review]
LGTM! Testing bumping focus around using both mouse and key events. Did notice some oddities if I put the form into a bad state, then clear all the fields, then refresh, but I'm not sure it's anything to be concerned about.

File: client/blocks/signup-form/index.jsx [hunk 1]
```diff
@@ -249,6 +251,14 @@ class SignupForm extends Component {
 				: mapKeys( response.messages, ( value, key ) => camelCase( key ) );
 
 			forEach( messages, ( fieldError, field ) => {
+				// If they've yet to tab to the password or username fields, don't show an error message prematurely
+				if ( field === 'password' && ! this.state.focusPassword ) {
+					delete messages.password;
+				}
+				if ( field === 'username' && ! this.state.focusUsername ) {
+					delete messages.username;
+				}
```
Comment (jsnajdr) [inline client/blocks/signup-form/index.jsx]: Looking at the server-side source of the `/signups/validation/user` endpoint that `validateNewUser()` calls, I see it has pretty good support for validating an incomplete signup form. If we took advantage of it here, it would fix the bug in a cleaner way.

The endpoint supports validation of the following fields:
```js
'email', 'first_name', 'last_name', 'username', 'password'
```
If any of them is missing (e.g., we provide only `username`), the endpoint will validate only the supplied fields individually.

Only when the complete set is supplied, the form is validated as a whole using the `wpmu_validate_user_signup` hook.

Therefore, if we used `focusPassword` and `focusUsername` to filter the field set in the _request_ rather than in the _response_ (see the `fieldsForValidation` array a few lines above), the validation endpoint would get more precise input and could provide more precise and relevant output.

Feature-rich React form libraries like Redux Form or Formik support a concept of a "pristine" status of a field. If a field is "pristine", i.e., the user hasn't typed anything into it yet, it can be excluded from validation, as that usually triggers only annoying and irrelevant errors. The `focus*` state fields here provide a basic implementation of that concept. In the long term, we should convert all our forms to use one of the 3rd party libraries.

**Review by jsnajdr — CHANGES_REQUESTED** [review]

File: client/blocks/signup-form/index.jsx (hunk 1 above)
Comment (davemart-in) [reply client/blocks/signup-form/index.jsx]: Thanks for pointing that out @jsnajdr! Updated in https://github.com/Automattic/wp-calypso/commit/0c67059c4885b2462ad77c503181dbff312e0caa

File: client/blocks/signup-form/index.jsx [hunk 2]
```diff
@@ -233,7 +235,22 @@ class SignupForm extends Component {
...
+		// Remove fields that have yet to be visited
+		forEach( data, ( value, field ) => {
+			// prevent an error messages from being shown prematurely
+			if ( field === 'password' && ! this.state.focusPassword ) {
+				delete data.password;
+			}
+
+			if ( field === 'username' && ! this.state.focusUsername ) {
+				delete data.username;
+			}
```
Comment (jsnajdr) [inline client/blocks/signup-form/index.jsx]: What if you excluded the unwanted fields when creating the `fieldsForValidation` array?
```js
const fieldsForValidation = filter( [
  'email',
  this.state.focusPassword && 'password',
  this.props.displayUsernameInput && this.state.focusUsername && 'username',
  this.props.displayNameInput && 'firstName',
  this.props.displayNameInput && 'lastName',
] );
```

Comment (davemart-in) [reply client/blocks/signup-form/index.jsx]: Even better! Updated in https://github.com/Automattic/wp-calypso/commit/0c152b503e061e065b6d320e052bea0add56b3c0 Thanks for the improvements @jsnajdr!

File: client/blocks/signup-form/index.jsx [hunk 3]
```diff
@@ -319,6 +321,14 @@ class SignupForm extends Component {
 
 	handleBlur = () => {
 		const data = this.getUserData();
+		const fieldId = event.target.id;
```
Comment (jsnajdr) [inline client/blocks/signup-form/index.jsx]: The `event` variable here is not defined. The `handleBlur` function should declare `event` as parameter.

The reason why this works and why ESLint doesn't complain is that there is a [`window.event` global](https://developer.mozilla.org/en-US/docs/Web/API/Window/event) that contains the currently handled event. But that's a weird legacy feature of the web platform that is better avoided. Another slight difference is that in one case `event` is the native DOM event, and in the other one (as `handleBlur` param) it's React event wrapper.

**Review by jsnajdr — COMMENTED** [review]
Howdy @davemart-in :wave: Thanks for making the requested fixes! I posted one more little suggestion about an `event` variable.

When testing, I noticed a behavior that's probably correct and expected, but still worth mentioning:

When the first thing I do is to click the `username` field and enter something, the validator will report the `email` field, although I didn't touch it yet:

screenshot 2019-03-05 at 09 34 37

We don't want to implement a `focusEmail` behavior, do we? The user skipped a field, and that deserves a warning. As opposed to warning about fields that the user didn't get to yet.

File: client/blocks/signup-form/index.jsx (hunk 3 above)
Comment (davemart-in) [reply client/blocks/signup-form/index.jsx]: > We don't want to implement a focusEmail behavior, do we?

That's correct. Showing the email validation error is intentional in this scenario since technically we've already progressed past that field.

> The event variable here is not defined. 

Doh! Another great catch. Updated in https://github.com/Automattic/wp-calypso/commit/9c3896bf4c1db37013000bd879b90e6570b551fd Thank you!

> The reason why this works and why ESLint doesn't complain is that there is a window.event global that contains the currently handled event. But that's a weird legacy feature of the web platform that is better avoided.

I did not know this. Thanks for the heads up!

Comment (jsnajdr) [reply client/blocks/signup-form/index.jsx]: > I did not know this. Thanks for the heads up!

Neither did I until earlier today 🙂

**Review by jsnajdr — APPROVED** [review]
Looks ready to :ship: Thanks for working on this and for addressing all issues!
