### PR TITLE
In Reader empty sidebar sections, use max-width rather than \xa0

### LINKED ISSUE #11522: Reader: Tags shows a non-translated string if locale (es - Spanish) is set
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/me/account
2. Switch UI to: es - Español
3. Save the changes
4. Click on Lector -> Etiquetas

#### What I expected
- String _"Find relevant posts by adding a tag."_ translated in Spanish

#### What happened instead
- String _"Find relevant posts by adding a tag."_ doesn't have a Spanish Translation

#### Screenshots

image

#### Browser / OS version
Chrome Version 56.0.2924.87 (64-bit) / macOS Sierra 10.12.3

#### Context / Source
Test is part of a support rotation. 

- I'd suggest to either add the string to the repository, or use this proposed Translation: _"Encuentra entradas relevantes añadiendo una etiqueta."_

#i18n, #manual-testing, #support #rotation #spanish_support

### PR DESCRIPTION
**Pull request by bluefuton**
@nellofn discovered that the string "Find relevant posts by adding a tag" in the Reader sidebar menu is not translated. @akirk found that this was caused by a rogue `\xa0` character, which had been inserted to prevent the word "tag" being orphaned on the second line.

This PR removes the `\xa0` character and instead uses max-width to constrain the string:

screen shot 2017-03-10 at 10 14 52

Fixes #11522.

### To test

Open the Reader at http://calypso.localhost:3000 and expand the 'Tags' section in the sidebar. If you're not following any tags, you should see the message.

cc @blowery

### CODE REVIEW

File: client/reader/sidebar/reader-sidebar-lists/list.jsx [hunk 1]
```diff
@@ -43,7 +43,7 @@ export class ReaderSidebarListsList extends React.Component {
 		const { translate, lists } = this.props;
 		if ( ! lists || lists.length === 0 ) {
 			return (
-				<li key="empty" className="sidebar__menu-empty">{ translate( 'Collect sites together by adding a\xa0list.' ) }</li>
+				<li key="empty" className="sidebar__menu-empty">{ translate( 'Collect sites together by adding a list.' ) }</li>
```
Comment (a8ci18n) [inline client/reader/sidebar/reader-sidebar-lists/list.jsx]: :ok: This change is safe, we'll keep the existing 4 translations.

File: client/reader/sidebar/reader-sidebar-tags/list.jsx [hunk 2]
```diff
@@ -43,7 +43,7 @@ export class ReaderSidebarTagsList extends Component {
 		const { tags, translate } = this.props;
 		if ( ! tags || tags.length === 0 ) {
 			return (
-				<li key="empty" className="sidebar__menu-empty">{ translate( 'Find relevant posts by adding a\xa0tag.' ) }</li>
+				<li key="empty" className="sidebar__menu-empty">{ translate( 'Find relevant posts by adding a tag.' ) }</li>
```
Comment (a8ci18n) [inline client/reader/sidebar/reader-sidebar-tags/list.jsx]: :ok: This change is safe, we'll keep the existing 4 translations.

**Comment by bluefuton** [comment]
Thanks for the initial ping and the review, @akirk!
