### PR TITLE
Customize: redirect to wp-admin customizer if jetpack

### LINKED ISSUE #14565: Customizer: Does not work for AT sites
#### Steps to reproduce
1. Create an AT site. E.g: mysite.blog
2. Try to access the Customizer on Calypso https://wordpress.com/customize/mysite.blog
3. I get this error *Sorry, the customizing tools did not load correctly*
4. Check the console log, there is an error. 
```
Refused to display 'https://mysite.blog/wp-admin/customize.php?return=https%3A%2F%2Fwordpress…ypso=true&calypsoOrigin=https%3A%2F%2Fwordpress.com&frame-nonce=8167bd4396' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE
mysite.blog/wp-admin/customize.php?return=https%3A%2F%2Fwordpress.com%2Fs…ypso=true&calypsoOrigin=https%3A%2F%2Fwordpress.com&frame-nonce=8167bd4396 Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE
```

#### What I expected

I can see the Customizer. 

#### What happened instead

I get this error *Sorry, the customizing tools did not load correctly*

#### Browser / OS version

I am using Mac on Chrome.

#### Screenshot / Video

screenshot_2017-05-30__15-34-33_edit

#### Context / Source

* This is reported from an user on 414465-hc. 
* I myself and another HE can see it as well.

### PR DESCRIPTION
**Pull request by sirbrillig**
Currently if a site is a Jetpack site, and you click on the "Customize" sidebar link in the Calypso sidebar, you will be redirected to the wp-admin customizer page for your site rather than the `/customize` Calypso page. This is because the `/customize` page just loads the wp-admin customizer inside an iframe, and due to the different domain it's not possible to iframe a Jetpack site.

However, it is still possible to end up on the `/customize` page with a Jetpack site. There are other links around Calypso and other places, including support documents, which do not have this redirect in place. In those cases, the user will inevitably see an error message that the customizer failed to load. This is a very poor UX.

This PR adds code to the `/customize` page itself which will redirect to the wp-admin customizer if the site is a Jetpack site.

Fixes #14565

This also updates the `Customize` component to ES6, which is most of the changes.

## Testing

1. Using a WPCOM (non-Jetpack) site, visit http://calypso.localhost:3000/customize/[your-site-here].
2. Verify that the Customizer loads.
3. Verify that the URL has remained on Calypso and on the `/customize` route (the domain might change if there is a custom domain).
4. Using a Jetpack site, visit the same URL as step 1.
5. Verify that the Customizer loads.
6. Verify that the URL is now `/wp-admin/customize.php` for your site.

## Possible additional work

- Support passing a requested `panel` prop to the redirect so that URLs like https://calypso.localhost:3000/customize/widgets will still end up on the widgets panel (added in #5287)
- Support the `/customize/menus` path (this is related to the `panel` prop).

### CODE REVIEW

**Comment by ockham** [comment]
> it is still possible to end up on the `/customize` page with a Jetpack site. There are other links around Calypso and other places, including support documents, which do not have this redirect in place

As for the ones in Calypso, we should probably change them to use `getCustomizerUrl()`...

**Comment by ockham** [comment]
This seems to break the `/customize/menus/<JPsite>` redirect for me, which works in production...

**Comment by ockham** [comment]
> This seems to break the `/customize/menus/<JPsite>` redirect for me, which works in production...

Uh, nevermind. What matters moer is the `/menus/<JPsite>` redirect, and that still seems to work.

File: client/my-sites/customize/main.jsx [hunk 1]
```diff
@@ -1,83 +1,96 @@
...
-	connect = require( 'react-redux' ).connect,
-	debug = require( 'debug' )( 'calypso:my-sites:customize' );
-import { get, startsWith } from 'lodash';
+import React, { PropTypes } from 'react';
+import { localize } from 'i18n-calypso';
+import url from 'url';
+import Qs from 'qs';
+import cloneDeep from 'lodash/cloneDeep';
+import get from 'lodash/get';
+import startsWith from 'lodash/startsWith';
```
Comment (ockham) [inline client/my-sites/customize/main.jsx]: Can we make those three into

```js
import { cloneDeep, get, startsWith } from 'lodash';
````
?

File: client/my-sites/customize/main.jsx [hunk 2]
```diff
@@ -1,83 +1,96 @@
...
-	componentWillMount: function() {
+	componentWillMount() {
 		this.redirectIfNeeded( this.props.pathname );
 		this.listenToCustomizer();
 		this.waitForLoading();
-		window.scrollTo( 0, 0 );
-	},
+		if ( window ) {
+			window.scrollTo( 0, 0 );
+		}
```
Comment (ockham) [inline client/my-sites/customize/main.jsx]: Should this go to `componentDidMount` instead? (Maybe we could drop the `window` check there.) ([ref](https://facebook.github.io/react/docs/react-component.html#componentwillmount))

File: client/my-sites/customize/main.jsx [hunk 3]
```diff
@@ -1,83 +1,96 @@
...
+	}
 
-	componentWillUnmount: function() {
-		window.removeEventListener( 'message', this.onMessage, false );
+	componentWillUnmount() {
+		if ( window ) {
```
Comment (ockham) [inline client/my-sites/customize/main.jsx]: Do we need the check? ([ref](https://facebook.github.io/react/docs/react-component.html#componentwillunmount))

File: client/my-sites/customize/main.jsx (hunk 1 above)
Comment (sirbrillig) [inline client/my-sites/customize/main.jsx]: I thought that caused a larger footprint because then it has to import the whole module? Maybe my knowledge is outdated.

File: client/my-sites/customize/main.jsx (hunk 2 above)
Comment (sirbrillig) [inline client/my-sites/customize/main.jsx]: Hm... yeah, not sure why that was in `componentWillMount`. I'd like to leave the `window` check, though. It makes components more testable if they don't rely on `window` globals.

File: client/my-sites/customize/main.jsx (hunk 3 above)
Comment (sirbrillig) [inline client/my-sites/customize/main.jsx]: See [previous comment](https://github.com/Automattic/wp-calypso/pull/15998/files/441422e6a33a9dbae4c9cd1049dd82b51070a1b1#r127827939). This is just defensive coding.

File: client/my-sites/customize/main.jsx (hunk 1 above)
Comment (ockham) [inline client/my-sites/customize/main.jsx]: I guess you're referring to p4TIVU-7g0-p2. I'd still say the curly braces imports are the currently suggested way in Calypso for sake of consistency, while we're aiming for a solution to the bloat issue on a higher level (which might involve codemodding all the things).

Comment (sirbrillig) [inline client/my-sites/customize/main.jsx]: I guess `babel-plugin-lodash` takes care of doing this automatically, so I'll use the shorter version.

**Comment by sirbrillig** [comment]
Thanks! Going to test this once more tomorrow with the tweaks and then merge.
