### PR TITLE
Separate post likes and likers state

### LINKED ISSUE #84213: Unable to like posts via the Reader
### Quick summary

There is a current issue with the likes on posts not registering properly through the Reader when the like button is clicked after mousing over the button.

I can reproduce it occasionally if I click on the like button immediately after mousing over it, however, some users wait several seconds and then click the like button and it doesn't work, as seen in the example shown in this ticket here: 7189825-zd-a8c

### Steps to reproduce

1. Go to the Reader: https://wordpress.com/read
2. Mouse over the like button and click to like.
3. The post will be liked for a millisecond and then it will disappear.

### What you expected to happen

The selected post to be liked

### What actually happened

The post is not liked

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

Slack thread: p1699278120610229-slack-C03NLNTPZ2T

### PR DESCRIPTION
**Pull request by daledupreez**
Fixes #84213

## Proposed Changes

* This PR creates a dedicated `QueryPostLikers` component to query for likes information, and splits up the state handling for basic post likes information, specifically the number of likes and whether the current user likes the post, and the likers information, specifically which users liked the post.
* The reason for making this change is that the bug reported in #84213 occurs because we end up making two API requests: one when we show the popover, and one to like the post when the user clicks, but we end up overwriting the number of likes and liked state when the response from the popover comes back.
* To avoid further race conditions, the solution in this PR is to update the `iLike` and `found` state if and only if we're performing a like-related action, and to update the `likes` state if and only if we're specifically updating the `likes` data. This avoids cases where slow calls to fetch likes data can overwrite likes performed on the client, as in the original issue.

### Testing procedure

* Open the Reader and find a post card with multiple existing likes
* Mouse over the like star and immediately click on it
* [Optional extension - h/t @roo2] Click on the like star again in short succession

### Test cases

* Run WordPress.com _without_ this patch.
* Follow the testing procedure above, and verify that you see the like state and like count behave as reported in the original bug -- the end like state should be _unliked_ (i.e. not filled), and the like count should toggle unexpectedly
  - This is a timing issue/race condition, but we want to verify that you can reproduce the problem
  - If you are having trouble reproducing the issue, try throttling your network connection to see if that makes it easier to reproduce. This is probably easiest to do via your browser dev tools.
* Run this branch locally or via Calypso.live
* Follow the testing procedure above.
* Verify that the like state updates immediately so the star is filled and the liker count is updated, and that the popover shows your username without any changes to the like count or star fill state

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [N/A] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [N/A] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [N/A] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [N/A] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by Addison-Stavlo — COMMENTED** [review]
I am unable to repro this problem at home although I was able to at the meetup. So my testing currently can't 100% determine if this fixes the bug.  But given everything I have seen at the meetup while looking at this, I think this should resolve the issue. It would be nice to get a tester that can repro the bug to confirm, but not a blocker. Are you able to repro the original bug at home @daledupreez ? 

In testing, the components continue to work well and I see no regressions.

The unit tests have some failures. Some seem to be around our change to setting `iLike` as `true` in the add likes reducer, but there are some others noting the likes array as undefined where unexpected we may need to look into.

**Comment by daledupreez** [comment]
Thanks for taking a look, @Addison-Stavlo! I made some changes to fix the unit tests earlier, and I've just updated the testing instructions to suggest adding browser-based network throttling.

I can reproduce the issue without the throttling, likely because of my network latency to our data centres, but it should be easier to trigger over a slower network connection (even if it's simulated).

**Review by markbiek — APPROVED** [review]
Working as expected!

I did have to set throttling in my browser to be able to reproduce it (Regular 3G seemed to be a good setting).

Once I had throttling turned on, I could reproduce the original issue and was able to verify that it functioned correctly using the calypso.live link.

**Comment by daledupreez** [comment]
I also double-checked whether there were any other callers of `receiveLikes()`, and confirmed that the only current caller specifically doesn't supply `likes`. So I think we should be clear to move forward.
https://github.com/Automattic/wp-calypso/blob/1669ddee39b5a8be3ea91b0fc2e8b81bde94b777/client/state/reader/posts/actions.js#L96-L101

**Comment by roo2** [comment]
hmm I haven't looked into the code yet but it seems to introduce another issue at least on the post details page.

When you double click, the state gets a bit inconsistent, with the icon being marked as liked but the count matching the unliked value.

https://github.com/Automattic/wp-calypso/assets/22446385/ed69b6ef-db96-46e4-a16e-a286dd30128b

It does look like this is newly introduced with this PR as I couldn't reproduce it on wpcom

File: client/state/posts/likes/reducer.js [hunk 1]
```diff
@@ -80,7 +92,7 @@ export const itemReducer = withSchemaValidation(
 
 				return {
 					likes,
-					iLike: state.iLike,
+					iLike: true,
```
Comment (daledupreez) [inline client/state/posts/likes/reducer.js]: @roo2, you're 100% right that I introduced a regression. I am 99% sure it's due to this line, but I will keep digging.

**Comment by valterlorran** [comment]
I want to mention that none of my likes showed as persisted, reloading the page right after the like action. I tested with this PR applied and directly on WordPress.com. After a few minutes, the state appeared as liked. I don't think is related to this PR.

**Comment by daledupreez** [comment]
> I want to mention that none of my likes showed as persisted, reloading the page right after the like action. I tested with this PR applied and directly on WordPress.com. After a few minutes, the state appeared as liked. I don't think is related to this PR.

This is a more subtle issue, and is unrelated, as you mention, @valterlorran. For reloads, the initial like state is fetched from the server, which may itself be cached and/or fetched from our content back end. The most recent change in this area, D128079-code, seems not to have made a change for `like_count`, so that may be the source of the issue.

FWIW, when we receive the list of posts from the back end, we use the like data in the post to initialise the client-side state:

https://github.com/Automattic/wp-calypso/blob/ae0ea04be4695711c56e0842e2036a2a04b9166a/client/state/reader/posts/actions.js#L93-L103

**Review by valterlorran — APPROVED** [review]
LGTM! We just need to check why the tests are failing, maybe a rebase will fix it.

File: client/blocks/post-likes/index.jsx [hunk 2]
```diff
@@ -91,7 +91,7 @@ class PostLikes extends PureComponent {
 
 		return (
 			<div className={ classes } { ...extraProps }>
-				{ !! postId && <QueryPostLikes siteId={ siteId } postId={ postId } needsLikers={ true } /> }
```
Comment (roo2) [inline client/blocks/post-likes/index.jsx:94]: You can remove the `needsLikers` prop and related code from the component completely now because it will always be false :)

File: client/state/posts/likes/reducer.js [hunk 3]
```diff
@@ -19,9 +19,23 @@ import itemSchema from './schema';
 export const itemReducer = withSchemaValidation(
 	itemSchema,
 	( state = { likes: undefined, iLike: false, found: 0, lastUpdated: undefined }, action ) => {
+		/*
+		 * NOTE: This reducer includes some subtle, non-obvious behavior.
```
Comment (roo2) [inline client/state/posts/likes/reducer.js:23]: Thanks for adding the comment! Just double checking it's up to date with any further changes you made? :)

**Review by roo2 — APPROVED** [review]
LGTM, nice fix!

File: client/state/posts/likes/reducer.js (hunk 3 above)
Comment (daledupreez) [reply client/state/posts/likes/reducer.js:23]: I can confirm this is accurate -- I added most of the content here quite late in the PR (thankfully!).

File: client/blocks/post-likes/index.jsx (hunk 2 above)
Comment (daledupreez) [reply client/blocks/post-likes/index.jsx:94]: You're right! I'll tackle that in a follow-up PR once this one ships.

Comment (daledupreez) [reply client/blocks/post-likes/index.jsx:94]: Follow up PR to remove the `needsLikers` prop: https://github.com/Automattic/wp-calypso/pull/84538
