### PR TITLE
Migration Flow: Fix multiple stickers being added simultaneously when navigating to the "DIY" option

### LINKED ISSUE #95560: Multiple stickers being added simultaneously when navigating to the "DIY" option
## Description

As reported [here](https://github.com/Automattic/wp-calypso/pull/95413#issuecomment-2426859639) by @m1r0, there's a bug when creating the migration stickers for the DIY option. It's probably related to a race condition because one is called in the option click and the other when the step "Let’s migrate your site" is loaded.

Some approaches I thought that we could explore more and try:

- Create the migration started sticker on the WPCOM side. We just need to keep in mind that our solution needs to make sense for the DIY and DIFM.
- Skip the cache in the backend when checking the existing stickers. Not sure if it could cause performance issues.
- Create a loader when the user click on the options that would wait for this post before navigating to the next step.

## Steps

- Go to `/setup/migration`.
- Select the "WordPress" and the "I'll do it myself" option.
- Check the blog stickers for the site (you can check it in the Blog RC), and see that it created one for pending and other for started.

### PR DESCRIPTION
**Pull request by m1r0**
Resolves #95560

## Proposed Changes

* This fixes a race condition causing multiple stickers to be added when the "I'll do it myself" option is selected. The problem is explained in detail [here](https://github.com/Automattic/wp-calypso/issues/95560).

## Why are these changes being made?

* We need only one migration sticker to be present at all times.

## Testing Instructions

- Go to `/setup/migration`.
- Select "WordPress" and the "I'll do it myself" option.
- Check the blog stickers for the site (you can check it in the Blog RC), and make sure that only the`migration-started-diy` sticker is present.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx [hunk 1]
```diff
@@ -1,8 +1,9 @@
 import { StepContainer } from '@automattic/onboarding';
 import { useTranslate } from 'i18n-calypso';
-import { FC, useMemo } from 'react';
+import { FC, useMemo, useState } from 'react';
```
Comment (renatho) [inline client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx:3]: The component `SiteMigrationHowToMigrate` is getting a little complex (big). I started extracting part of the logic to another hook [here](https://github.com/Automattic/wp-calypso/pull/95413/files#diff-d840edfeb1289157ef7b061afe8ba90034b8a354210586b68aacac10c2d60f50). I think it would be nice to base this PR there and also add the loading logic there, returning the loading state. WDYT?

File: client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx [hunk 2]
```diff
@@ -76,29 +77,41 @@ const SiteMigrationHowToMigrate: FC< Props > = ( props ) => {
 		? true
 		: false;
 
-	const { updateMigrationStatus } = useUpdateMigrationStatus();
+	const [ isLoading, setIsLoading ] = useState( false );
```
Comment (renatho) [inline client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx]: Instead of an extra state that we need to control, we can use the `isLoading` returned from the [mutation](https://tanstack.com/query/v4/docs/framework/react/reference/useMutation).

File: client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx [hunk 3]
```diff
@@ -76,29 +77,41 @@ const SiteMigrationHowToMigrate: FC< Props > = ( props ) => {
...
-					<FlowCard
-						key={ i }
-						title={ option.label }
-						text={ option.description }
-						onClick={ () => handleClick( option.value ) }
-					/>
-				) ) }
-			</div>
+			{ isLoading ? (
+				<LoadingEllipsis />
```
Comment (renatho) [inline client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx]: It would be nice to centralize the loader. Since the step content is centered, it looks a little weird having the loader in the left.

File: client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx (hunk 1 above)
Comment (renatho) [reply client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx:3]: And I thought of another scenario where we could have the same issue.
If the user is in a slow connection and they click on one of the options quickly it would be registering the "pending" sticker, and could try to register the "pending-{TYPE}" at the same time.

If we rebase this PR, we could also add the loader for this scenario: https://github.com/Automattic/wp-calypso/pull/95413/files#diff-d840edfeb1289157ef7b061afe8ba90034b8a354210586b68aacac10c2d60f50R26

If we follow the suggestion of the other comment, I think it would assume this behavior automatically.

**Review by renatho — COMMENTED** [review]
Thanks @m1r0! In my tests, it seems the issue was fixed! 🙌

I just left some suggestions in the code.

File: client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx (hunk 1 above)
Comment (renatho) [inline client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx:3]: And I thought of another scenario where we could have the same race condition issue.
If the user is in a slow connection and they click on one of the options quickly it would be registering the "pending" sticker, and could try to register the "pending-{TYPE}" at the same time.

If we rebase this PR, we could also add the loader for [this scenario](https://github.com/Automattic/wp-calypso/pull/95413/files#diff-d840edfeb1289157ef7b061afe8ba90034b8a354210586b68aacac10c2d60f50R26) (when creating the first "pending" sticker).

If we follow the suggestion of the [other comment](https://github.com/Automattic/wp-calypso/pull/95612/files#r1813336612), I think it would assume this behavior automatically.

File: client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx (hunk 3 above)
Comment (m1r0) [reply client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx]: I swear that was centered while I was testing! 😅 It's [fixed](https://github.com/Automattic/wp-calypso/pull/95612/files#diff-263e4afa19ba8a95b4c2662c5dfc0a0b97103d852c7b20c18c957a382dbdf8c6R47) now.

File: client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx (hunk 1 above)
Comment (m1r0) [reply client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx:3]: Sounds good!

I've updated the code but I'm a bit unsure if my implementation is aligned with your vision. 😅 Could you give it a look again?

Comment (m1r0) [reply client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx:3]: I think I've managed to fix this scenario but I'm facing an issue with the component loading first and then the loader appearing. 

https://github.com/user-attachments/assets/bacd7776-fb77-4af5-aecb-b87da2e56b6a

Can I fix this without having an extra state in the component?

File: client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx [hunk 4]
```diff
@@ -72,16 +75,20 @@ const SiteMigrationHowToMigrate: FC< Props > = ( props ) => {
...
-				{ options.map( ( option, i ) => (
-					<FlowCard
-						key={ i }
-						title={ option.label }
-						text={ option.description }
-						onClick={ () => setPendingMigration( option.value ) }
-					/>
-				) ) }
-			</div>
+			{ isLoading ? (
```
Comment (renatho) [inline client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx]: I just noticed that the `<></>` is not needed here since it has only a single item inside.
In your next iteration, could you take the opportunity to remove it? =)

File: client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx (hunk 1 above)
Comment (renatho) [reply client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx:3]: Yes! That looks great!

File: client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx (hunk 3 above)
Comment (renatho) [reply client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx]: Haha. Looks good now! Thanks!

File: client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx (hunk 1 above)
Comment (renatho) [reply client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx:3]: Hm! I noticed that it's because this fetch depends on the `siteId`, and [it's taking some time to be ready because it's coming from the store](https://github.com/Automattic/wp-calypso/commit/2101023e8f1f0b9ff09a9c8f6e94f53f4bcfee11#diff-d840edfeb1289157ef7b061afe8ba90034b8a354210586b68aacac10c2d60f50R23-R28). I wonder if we could get it directly from the query string, so we would have this information immediately when the component is loaded to start already with the loader. WDYT?

**Comment by gabrielcaires** [comment]
We are having page flickering, probably due to the 
https://github.com/user-attachments/assets/5e9404f5-54a1-470a-8bd2-748cc0a965e5 
https://github.com/Automattic/wp-calypso/pull/95612#discussion_r1817275555

I suggest showing the content only when we are ready to show it, preventing any future race conditions.

File: client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx (hunk 1 above)
Comment (m1r0) [reply client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx:3]: Could you take a look at [this approach](https://github.com/Automattic/wp-calypso/pull/95612/commits/02527876960d205defe96bdf88c40bf63e090f13)? I wasn't able to avoid the site loading because of [this check](https://github.com/Automattic/wp-calypso/blob/a9fd24e414cb89fffa385e3a1b39aae152beb74f/client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/use-pending-migration-status.ts#L15). Do you think it's good enough? 🙂

File: client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx (hunk 4 above)
Comment (m1r0) [reply client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx]: Right! Fixed in https://github.com/Automattic/wp-calypso/pull/95612/commits/682f844641964d6e74f6f6064ae2b8a42d045458.

**Comment by m1r0** [comment]
@gabrielcaires, do you mean replacing the whole page content, not just the step content?

File: client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx (hunk 1 above)
Comment (renatho) [reply client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx:3]: This approach looks good to me!

But I just noticed another flickering after clicking on the options ("Do it for me", for example). It finishes the loading (the sticker creating that comes from the click), and displays the step again very quickly before calling the `onSubmit`.

https://github.com/user-attachments/assets/1882069e-140f-4b0f-8c6f-8eef0d6eb250

I think we'll probably need an extra state here, similar to your previous approach. Maybe something that we set as loading after clicking and keep this state unchanged, so `onSubmit` is called when it's still in the loading state.

Comment (m1r0) [reply client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-how-to-migrate/index.tsx:3]: Oh, I didn't noticed that one. I've fixed it [here](https://github.com/Automattic/wp-calypso/pull/95612/commits/eff54d4a14c8ba05ac28bfab6fed2b10a16d6916) following your suggestion. Thank you for your patience!

**Review by renatho — APPROVED** [review]
Looks good and works well!
I'm already approving, but pinging @gabrielcaires to check if he has anything else to add based on his last comment.

**Comment by m1r0** [comment]
Merging to unblock a [potential refactor](https://github.com/Automattic/wp-calypso/pull/95413#discussion_r1824632570).
