### PR TITLE
Editor: decode slug for display in the editor.

### LINKED ISSUE #3465: Editor: Non-latin alphabet characters display as unicode in post/page slug
## URL:

https://wordpress.com/post and /page
## What I expected

When a draft is saved or published, the post title is added as the permalink slug, and can be edited under More Options in the editor menu. When using non-Latin alphabet characters, the expectation is that those characters will display in the edit-box. This happens in the WP-Admin editor, and the non-Latin characters also display when viewing the page in a browser.
## What happened instead

This was reported by a Hebrew user in 2537264-t. On saving the post the slug displayed in Hebrew letters, but the moment the post was published those changed into encoded characters instead.

I tested this in a few other non-Latin alphabets as well with the same result.

The actual permalink of the page still shows the correct characters, but the characters not displaying in the editor makes it problematic to edit the existing slug if needed.
## Steps to reproduce

Create a new post or page.

Add a title in any non-Latin alphabet.

Save the post, and expand More Options to see the slug matching the post title.

Publish the post. The slug will change as soon as the post is published.
## Browser / OS version

It happens on various browsers, on Mac and Windows, and also in the desktop apps
## Screenshots / Video

hebrew slug

### PR DESCRIPTION
**Pull request by timmyc**
This fixes #3465 - The API returns slugs in a url encoded format, which is handy, but when non-latin characters are used in the slug, the encoded representation is subsequently shown in the editor.

__To Test__
- Create a new post in the editor, from the original issue, you can use `זהו עין הנמר` as a title to trigger the bug
- Publish the post
- Expand the sidebar or the link icon next to the title and verify the slug shown is not url encoded

### CODE REVIEW

**Comment by folletto** [comment]
Tested in Chrome: 👍 

screen shot 2016-12-14 at 10 48 37

screen shot 2016-12-14 at 10 49 12

screen shot 2016-12-14 at 10 49 16

File: client/post-editor/editor-slug/index.jsx [hunk 1]
```diff
@@ -122,7 +122,7 @@ class PostEditorSlug extends Component {
 					<TrackInputChanges onNewValue={ this.recordChangeStats }>
 						<FormTextInput
 							ref="slugField"
-							value={ slug }
+							value={ decodeURI( slug ) }
```
Comment (omarjackman) [inline client/post-editor/editor-slug/index.jsx]: Would it solve this issue side wide if we sanitized this slug as it comes from the API and before it gets put in the state tree?

**Comment by timmyc** [comment]
@omarjackman moved the logic into the selector + added a test in 952ad0b - thanks again for the review.

**Comment by youknowriad** [comment]
Don't you think the problem here is on the API side? I mean the API should return the RAW value instead of the URL encoded value. (Slugs could be used outside of URLs, so why auto-encoding them).

Tho, I understand that this PR tries to move things forward due to the difficulty to fix it on the API side, since it would require a lot more changes and it have several implications (breaking change).

**Comment by timmyc** [comment]
> Don't you think the problem here is on the API side?

Perhaps, so that might be worth opening an issue to track elsewhere, but guessing we might need to version the endpoint to make that change.
