### PR TITLE
DomainPicker: update price formatting

### LINKED ISSUE #49410: New Onboarding: domains and plans price formatting doesn't match
### Steps to reproduce the behavior

1. Go to https://wordpress.com/new as non-US user with USD currency set in your account
2. Advance to Domains step and check the price formatting for domain suggestions
3. Advance to Plans step and check the price formatting

#### What I expected to happen
Price formatting should match and should be similar to what's on `/start` onboarding flow.

### Context
For domain suggestions, we're currently using the price formatted by the backend.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Not a blocker but since a user can jump very easily from Plans Grid to picking a domain, some consistency would be good.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
* Plans price formatting:
Screenshot 2021-01-28 at 16 56 42

* Domain suggestion price formatting:
Screenshot 2021-01-28 at 16 57 22

### PR DESCRIPTION
**Pull request by razvanpapadopol**
#### Changes proposed in this Pull Request

* Use newly introduced properties from D56060-code to format domain suggestion price on client

#### Testing instructions

* Go to /new as a non-US user having USD currency set for your account
* Open DomainPicker and PlansGrid and price formatting should match
* Check in one of the launch flows
* Check with other currency (see guide on PCYsg-2xJ-p2)

#### Screenshots
* **Before**
Screenshot 2021-01-29 at 13 56 15

* **After**
Screenshot 2021-01-29 at 13 55 59

Fixes #49410

### CODE REVIEW

File: packages/data-stores/src/domain-suggestions/types.ts [hunk 1]
```diff
@@ -100,22 +121,15 @@ export interface DomainSuggestion {
...
 	 * The product ID
 	 */
-	product_id: number;
+	product_id?: number;
 
 	/**
 	 * The product slug
 	 */
-	product_slug: string;
+	product_slug?: string;
```
Comment (razvanpapadopol) [inline packages/data-stores/src/domain-suggestions/types.ts:132]: Switched a bunch of properties to optional because the free suggestion returned by the API doesn't include them.

Comment (StefanNieuwenhuis) [reply packages/data-stores/src/domain-suggestions/types.ts:132]: Why are `relevance`, `supports_privacy`, `vendor`, `product_id` & `product_slug` not included in the free suggestion and therefore optional?

**Review by StefanNieuwenhuis — COMMENTED** [review]
Both Domain & Feature picker looks good to me!

### Focused Launch - Domain Picker

#### Account Settings

Language: **Dutch**
Currency: **USD**

Screenshot 2021-02-01 at 11 19 01

#### Account Settings

Language: **Dutch**
Currency: **JPY**

Screenshot 2021-02-01 at 11 21 41

### Focused Launch - Plans Picker 

#### Account Settings

Language: **Dutch**
Currency: **USD**

**Annual**
Screenshot 2021-02-01 at 11 19 39

**Monthly**
Screenshot 2021-02-01 at 11 19 49

#### Account Settings

Language: **Dutch**
Currency: **JPY**

**Annual**
Screenshot 2021-02-01 at 11 21 20

**Monthly**
Screenshot 2021-02-01 at 11 21 23
