### PR TITLE
Fixed plan selector alignment and plan blocks size on tablet screen sizes

### LINKED ISSUE #101964: Onboarding style consistency: Improve mobile plan alignments
### Details

1. Tenure selector and plans not extended:

Image

2. Subtitle and title should be centered until mobile break on StepContainerV2. Once it breaks, both should be left aligned.

Image

### PR DESCRIPTION
**Pull request by paulopmt1**
Related to https://github.com/Automattic/wp-calypso/issues/101964
Slack thread: p1743085286744789-slack-C04H4NY6STW

## Proposed Changes

* Set plan duration selector full width for mobile and tablet resolutions
* Increase one plan block for tablet resolutions
* Left align subtitle on StepContainerV2 mobile resolution

| Before | Header |
|--------|--------|
| image | image | 
| image | image |

## Testing Instructions

* Go to [/setup/onboarding](http://calypso.localhost:3000/setup/onboarding) (locally or use the feature flag `?flags=onboarding/step-container-v2` on staging)
* Add a paid domain to your cart and advance to the plans page

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: packages/plans-grid-next/src/components/features-grid/index.tsx [hunk 1]
```diff
@@ -404,7 +404,7 @@ const WrappedFeaturesGrid = ( props: FeaturesGridExternalProps ) => {
 		}
 
 		// we want to fit 3 plans per row in this breakpoint
-		const mediumBreakpoint = isInSiteDashboard ? 667 : 741;
+		const mediumBreakpoint = 669;
```
Comment (zaguiini) [inline packages/plans-grid-next/src/components/features-grid/index.tsx:407]: What's the reason behind this change? If we want to customize this further, then we'll likely need a prop, otherwise it will break other pages, no?

File: client/landing/stepper/declarative-flow/internals/steps-repository/unified-plans/style.scss [hunk 2]
```diff
@@ -27,14 +27,22 @@
 	}
 }
 
-.step-container-v2--plans {
-	.plans-wrapper {
-		margin: 0;
-		padding: 0;
+.step-container-v2 {
```
Comment (zaguiini) [inline client/landing/stepper/declarative-flow/internals/steps-repository/unified-plans/style.scss:30]: Why did we need this change? Specificity? Can we do it without? I don't like the idea of targeting `step-container-v2` directly.

File: packages/plans-grid-next/src/components/features-grid/index.tsx (hunk 1 above)
Comment (paulopmt1) [reply packages/plans-grid-next/src/components/features-grid/index.tsx:407]: > What's the reason behind this change?

We want to match the breakpoint with the max-width break-small [defined here](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/unified-plans/style.scss#L37).
So that will generate this behavior:

https://github.com/user-attachments/assets/87cba7e2-410b-43c2-b69e-583948ef3aa7

Without setting it, we'll have this weird behavior where a single plan is shown after the break-small:


https://github.com/user-attachments/assets/cc985109-5032-4cc5-9aa0-02809c1d5910


> If we want to customize this further, then we'll likely need a prop

The original value [was introduced here](https://github.com/Automattic/wp-calypso/pull/101603/files#diff-2b3a86f7c01159702bfe7bcd0c345cf14a15c1ad992c8162ce11401684f8ababR407-R408).

I don't think we want to keep customizing it since it's hard-coded to this screen. @fushar can you confirm that?


> otherwise it will break other pages, no?

I tested that feature locally (which has the flag `isInSiteDashboard` true) to ensure the value chance of 2px (before was 667) wouldn't change their behavior, and it looks good. 

I also tested other flows where we show the plans screen, like /plans, and the new change (669 instead 741) looks good as well.

File: client/landing/stepper/declarative-flow/internals/steps-repository/unified-plans/style.scss (hunk 2 above)
Comment (paulopmt1) [reply client/landing/stepper/declarative-flow/internals/steps-repository/unified-plans/style.scss:30]: Good question. The `.step-container-v2--plans` selector won't allow us to update the subtitle, so for that we need to start on a parent element. That's why I used the `.step-container-v2`.

image

We could implement it outside of the current CSS, something like this:

image


But it feels more organized to keep everything inside the same parent, since all these changes are specific for the new step container `.step-container-v2`.

> I don't like the idea of targeting step-container-v2 directly.

Interesting, can you elaborate more on why?

Comment (vykes-mac) [reply client/landing/stepper/declarative-flow/internals/steps-repository/unified-plans/style.scss:30]: I think @zaguiini concern is that by making the inner contents tightly coupled to the step container can lead to unintended style inheritance in other components of the step container and cause unintended side-effects.  
I think having outside as it's own class is the safer approach.

**Comment by autumnfjeld** [comment]
Not sure if this PR is final not, but did a few smoke tests, did not find any problems. 

https://www.awesomescreenshot.com/video/38132998?key=91a00235af747350ae7f23d329da2b6c

**Comment by vykes-mac** [comment]
@paulopmt1 Tested this and it looks good!

File: packages/plans-grid-next/src/components/features-grid/index.tsx (hunk 1 above)
Comment (fushar) [reply packages/plans-grid-next/src/components/features-grid/index.tsx:407]: It looks good on my end, too! Yeah, it would be good to have a single value here.

File: client/landing/stepper/declarative-flow/internals/steps-repository/unified-plans/style.scss (hunk 2 above)
Comment (zaguiini) [reply client/landing/stepper/declarative-flow/internals/steps-repository/unified-plans/style.scss:30]: Well this is fine. It's going to be reworked anyway. Let's move forward.

File: packages/plans-grid-next/src/components/features-grid/index.tsx (hunk 1 above)
Comment (zaguiini) [reply packages/plans-grid-next/src/components/features-grid/index.tsx:407]: Cool 👍🏻
