### PR TITLE
Editor: hide sharing on page editor for JP sites without sharing/likes enabled

### LINKED ISSUE #7088: Editor: Sharing accordion present on page editor for Jetpack site with Publicize, Likes, and Sharing disabled
#### Steps to reproduce
1. Disable Publicize, Likes, and Sharing modules on your Jetpack site
2. Navigate to URL: https://wordpress.com/page
3. Select the Jetpack site configured in step 1

#### What I expected

No Sharing accordion should be present in the sidebar.

#### What happened instead

A Sharing accordion with empty content is shown in the sidebar.

#### Screenshot

Page editor sharing

### PR DESCRIPTION
**Pull request by timmyc**
Fixes #7088 - This branch fixes a minor issue that happens for Jetpack sites that have likes and sharing disabled in the page editor:

new_page_ _haiku2_ _wordpress_com_

To re-create the issue, you need to disable Likes and Sharing on a Jetpack site, but keep Publicize *enabled*.

__To Test__
- Configure a jetpack site as outlined above
- Open up a page in the editor for that site, verify that the sharing accordion is not shown
- Open a post in the editor for that JP site, verify the sharing accordion is shown for publicize

/cc @aduth 

Test live: https://calypso.live/?branch=fix/editor/7088

### CODE REVIEW

File: client/post-editor/editor-sharing/accordion.jsx [hunk 1]
```diff
@@ -82,18 +83,23 @@ const EditorSharingAccordion = React.createClass( {
...
+		return ( this.props.site &&
+				this.props.site.jetpack &&
+				! this.props.site.isModuleActive( 'publicize' ) &&
+				! this.props.site.isModuleActive( 'sharedaddy' ) &&
+				! this.props.site.isModuleActive( 'likes' ) ) ||
+			( this.props.site &&
+				this.props.site.jetpack &&
+				this.props.postType === 'page' &&
+				! this.props.site.isModuleActive( 'sharedaddy' ) &&
+				! this.props.site.isModuleActive( 'likes' ) );
```
Comment (nylen) [inline client/post-editor/editor-sharing/accordion.jsx]: I think we can make this method a bit cleaner, and we should probably be using the `postTypeSupports` selector to avoid hardcoding:

```js
const { site, postTypeSupportsPublicize } = this.props;

if ( ! site || ! site.jetpack ) {
    return false;
}

let sharingModules;
if ( postTypeSupportsPublicize ) {
    sharingModules = [ 'publicize', 'sharedaddy', 'likes' ];
} else {
    sharingModules = [ 'sharedaddy', 'likes' ];
}
return sharingModules.every( ( module ) => ! site.isModuleActive( module ) );
```

Comment (nylen) [inline client/post-editor/editor-sharing/accordion.jsx]: Looking again, I see this component already has an `isPublicizeEnabled` prop which will do nicely here.  Another alternative which I think I like better than the array + `every` nonsense:

```js
return (
    ! site.isModuleActive( 'sharedaddy' ) &&
    ! site.isModuleActive( 'likes' ) &&
    ( ! isPublicizeEnabled || ! site.isModuleActive( 'publicize' ) )
);
```

Comment (aduth) [inline client/post-editor/editor-sharing/accordion.jsx]: Adding to @nylen 's remarks, we should also consider using the state selector [`isJetpackModuleActive`](https://github.com/Automattic/wp-calypso/blob/37d3a88e3732ec131ad518eb0266ed076855e927/client/state/sites/selectors.js#L134-L151) in place of the site instance function, though this is more a general refactoring remark.

@nylen it appears you're missing the `page` type consideration in your alternative approach.

Comment (aduth) [inline client/post-editor/editor-sharing/accordion.jsx]: Given that we're already using the logic in a few components already, thinking it makes sense for a new selector `isPublicizeEnabled`? Roughly:

```js
export function isPublicizeEnabled( state, siteId, postType ) {
	return (
		false !== isJetpackModuleActive( state, siteId, 'publicize' ) &&
		true !== getSiteOption( state, siteId, 'publicize_permanently_disabled' ) &&
		postTypeSupports( state, siteId, postType, 'publicize' )
	);
}
```

(Or with `postId` argument instead of `postType`, in `state/posts/selectors.js` or `state/ui/editor/selectors.js`)

**Comment by timmyc** [comment]
Okay @nylen and @aduth updated the logic a bit - not too thrilled with the naming of `isSharingAndLikesDisabled`, grammar and all, but thought we have to use `is` on boolean params.

File: client/post-editor/editor-sharing/accordion.jsx [hunk 2]
```diff
@@ -82,18 +85,24 @@ const EditorSharingAccordion = React.createClass( {
...
-			! this.props.site.isModuleActive( 'likes' );
+		const { isJetpack, isSharingAndLikesDisabled, isPublicizeEnabled } = this.props;
+
+		if ( ! isJetpack ) {
+			return false;
+		}
+
+		if ( this.props.postType === 'page' && isSharingAndLikesDisabled ) {
+			return true;
+		}
```
Comment (timmyc) [inline client/post-editor/editor-sharing/accordion.jsx]: Ah good point.

**Comment by nylen** [comment]
This is working well for me.  Naming could be improved, as you mentioned - for example changing `isSharingAndLikesDisabled` to `isSharingEnabled` and `isLikesEnabled` for grammar and for consistency with `isPublicizeEnabled` - but it's not worth nitpicking IMO.

File: client/post-editor/editor-sharing/accordion.jsx [hunk 3]
```diff
@@ -132,10 +141,16 @@ export default connect(
...
 			postTypeSupports( state, siteId, postType, 'publicize' )
 		);
+		const isSharingActive = false !== isJetpackModuleActive( state, siteId, 'sharedaddy' );
+		const isLikesActive = false !== isJetpackModuleActive( state, siteId, 'likes' );
+		const isJetpack = false !== isJetpackSite( state, siteId );
 
 		return {
+			connections: getSiteUserConnections( state, siteId, userId ),
+			isSharingAndLikesDisabled: ! isSharingActive && ! isLikesActive,
+			isJetpack,
```
Comment (aduth) [inline client/post-editor/editor-sharing/accordion.jsx]: Do we need this prop, since `isJetpackModuleActive` is already checking for the site to be Jetpack and will never be explicitly `false` for a WordPress.com site?

From docs:

>Returns null if the site is not known or is not a Jetpack site.

**Comment by timmyc** [comment]
@nylen can you check this out once more really quick?

File: client/post-editor/editor-sharing/accordion.jsx (hunk 3 above)
Comment (aduth) [inline client/post-editor/editor-sharing/accordion.jsx]: _cough_ https://github.com/Automattic/wp-calypso/pull/7378#discussion_r74314277

Comment (timmyc) [inline client/post-editor/editor-sharing/accordion.jsx]: Strange I thought I had left a comment here.  Sorry, too many tabs.  What I had written was I personally think the approach here is quite legible at a quick glance, but will change it up because I'm fine either way.

**Comment by timmyc** [comment]
Squashed up all those changes, one final look would be much appreciated 🙇

File: client/post-editor/editor-sharing/accordion.jsx [hunk 4]
```diff
@@ -132,10 +132,15 @@ export default connect(
...
+		const isSharingActive = false !== isJetpackModuleActive( state, siteId, 'sharedaddy' );
+		const isLikesActive = false !== isJetpackModuleActive( state, siteId, 'likes' );
 
 		return {
+			connections: getSiteUserConnections( state, siteId, userId ),
+			isSharingActive,
+			isLikesActive,
 			isPublicizeEnabled,
-			connections: getSiteUserConnections( state, siteId, userId )
+			postType
```
Comment (aduth) [inline client/post-editor/editor-sharing/accordion.jsx]: You're not using `postType` in the component.

File: client/post-editor/editor-sharing/accordion.jsx [hunk 5]
```diff
@@ -82,18 +85,15 @@ const EditorSharingAccordion = React.createClass( {
 	},
 
 	hideSharing: function() {
-		return this.props.site &&
-			this.props.site.jetpack &&
-			! this.props.site.isModuleActive( 'publicize' ) &&
-			! this.props.site.isModuleActive( 'sharedaddy' ) &&
-			! this.props.site.isModuleActive( 'likes' );
+		const { isSharingActive, isLikesActive, isPublicizeEnabled } = this.props;
+		return ( ! isSharingActive && ! isLikesActive ) && ! isPublicizeEnabled;
```
Comment (aduth) [inline client/post-editor/editor-sharing/accordion.jsx]: Parentheses seem a bit arbitrary

**Comment by aduth** [comment]
Cleanup tasks notwithstanding, this looks and works well 👍

**Comment by aduth** [comment]
Another aside: When only one or the other of Sharing or Likes modules are active, maybe we should change the label to reflect this. In the screenshot below, only Likes is active, but the label still says "Sharing Buttons & Likes".

image

**Comment by aduth** [comment]
LGTM 👍
