### PR TITLE
Login: Scroll to top on page change

### LINKED ISSUE #14182: Login: Scroll to top
When navigating around screens in /login the page should scroll to top, so that I am given context for the page.

Steps to reproduce:
1. Go to /login
2. Log in to a 2FA account
3. Scroll down
4. Select a different 2FA option
5. You will not be scrolled back up to the top of the page

### PR DESCRIPTION
**Pull request by stephanethomas**
This pull request fixes #14182 by scrolling the viewport to the top of the page when navigating any of the `Login` pages.
 
screenshot

  
#### Testing instructions
 
1. Run `git checkout add/scrolling-to-login-pages` and start your server, or open a [live branch](https://calypso.live/?branch=add/scrolling-to-login-pages)
2. Open the [`Login` page](http://calypso.localhost:3000/log-in)
3. Submit the form with credentials from an account that has 2FA with push notifications enabled
4. Narrow your browser's window to make the vertical scrollbar appears, and scroll down
5. Click the `Your Authenticator app` link
6. Assert that you are presented with the top of the new page
7. Scroll down again, and click the `Code via text message` link this time
8. Assert that you are presented with the top of the new page

#### Reviews
 
- [x] Code
- [x] Product

### CODE REVIEW

**Comment by Tug** [comment]
Still had some errors with `tween.js`, I had to upgrade this dependency.
It seems to be working fine now 👍

File: client/lib/scroll-to/test/index.js [hunk 1]
```diff
@@ -15,7 +15,7 @@ describe( 'scroll-to', () => {
 	useFakeDom();
 
 	before( () => {
-		scrollTo = require( '..' );
+		scrollTo = require( '..' ).default;
```
Comment (drewblaisdell) [inline client/lib/scroll-to/test/index.js]: @stephanethomas This change breaks the tests. It appears to work properly without this change, though.

**Comment by Tug** [comment]
I think the problem is that WpLogin is SSR enabled and `lib/scroll-to` was never intended to work on the server. We probably need to upgrade tween.js first

File: client/blocks/login/index.jsx [hunk 2]
```diff
@@ -46,6 +47,12 @@ class Login extends Component {
 		}
 	};
 
+	componentWillReceiveProps = ( nextProps ) => {
+		if ( this.props.twoFactorAuthType !== nextProps.twoFactorAuthType ) {
```
Comment (gziolo) [inline client/blocks/login/index.jsx]: Why don't we use global notices in case of errors? It was discussed several times in the past and there was decision made to use global notices to avoid scrolling of the page to show messages.

File: client/login/wp-login/test/test.jsx [hunk 3]
```diff
@@ -9,12 +9,17 @@ import { identity } from 'lodash';
...
-import { Login } from '../index.jsx';
 import useFakeDom from 'test/helpers/use-fake-dom';
 
 describe( 'Login', () => {
+	let Login;
+
 	useFakeDom();
 
+	before( () => {
+		Login = require( '..' ).Login;
```
Comment (gziolo) [inline client/login/wp-login/test/test.jsx]: That's a good example why we need to migrate to Jest at some point :)

**Comment by gziolo** [comment]
This one fails when trying to build:

> ReferenceError: window is not defined
>     at /home/ubuntu/data/gh-wp-calypso/branches/add/scrolling-to-login-pages/node_modules/tween.js/src/Tween.js:13:23
>     at Object. (/home/ubuntu/data/gh-wp-calypso/branches/add/scrolling-to-login-pages/node_modules/tween.js/src/Tween.js:31:3)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.defineProperty.value (/home/ubuntu/data/gh-wp-calypso/branches/add/scrolling-to-login-pages/build/webpack:/external "tween.js":1:1)
>     at __webpack_require__ (/home/ubuntu/data/gh-wp-calypso/branches/add/scrolling-to-login-pages/build/webpack:/webpack/bootstrap f69ec4aa219249c08986:19:1)
>     at Object. (/home/ubuntu/data/gh-wp-calypso/branches/add/scrolling-to-login-pages/build/webpack:/client/lib/scroll-to/index.js:4:1)
>     at __webpack_require__ (/home/ubuntu/data/gh-wp-calypso/branches/add/scrolling-to-login-pages/build/webpack:/webpack/bootstrap f69ec4aa219249c08986:19:1)
>     at Object.defineProperty.value (/home/ubuntu/data/gh-wp-calypso/branches/add/scrolling-to-login-pages/build/webpack:/client/blocks/login/index.jsx:26:1)
>     at __webpack_require__ (/home/ubuntu/data/gh-wp-calypso/branches/add/scrolling-to-login-pages/build/webpack:/webpack/bootstrap f69ec4aa219249c08986:19:1)
>     at Object.defineProperty.value (/home/ubuntu/data/gh-wp-calypso/branches/add/scrolling-to-login-pages/build/webpack:/client/login/wp-login/index.jsx:35:1)
>     at __webpack_require__ (/home/ubuntu/data/gh-wp-calypso/branches/add/scrolling-to-login-pages/build/webpack:/webpack/bootstrap f69ec4aa219249c08986:19:1)
>     at Object.defineProperty.value (/home/ubuntu/data/gh-wp-calypso/branches/add/scrolling-to-login-pages/build/webpack:/client/login/controller.js:9:1)
>     at __webpack_require__ (/home/ubuntu/data/gh-wp-calypso/branches/add/scrolling-to-login-pages/build/webpack:/webpack/bootstrap f69ec4aa219249c08986:19:1)
>     at Object.defineProperty.value (/home/ubuntu/data/gh-wp-calypso/branches/add/scrolling-to-login-pages/build/webpack:/client/login/index.js:5:1)
>     at __webpack_require__ (/home/ubuntu/data/gh-wp-calypso/branches/add/scrolling-to-login-pages/build/webpack:/webpack/bootstrap f69ec4aa219249c08986:19:1)
>     at Object.require (/home/ubuntu/data/gh-wp-calypso/branches/add/scrolling-to-login-pages/build/webpack:/client/sections.js:10:1)

File: client/blocks/login/index.jsx (hunk 2 above)
Comment (stephanethomas) [inline client/blocks/login/index.jsx]: Good catch @yurynix, I didn't think at all about `requestError`. Looking at the props I don't think we need to handle anything else but let me know if I missed something.

Comment (stephanethomas) [inline client/blocks/login/index.jsx]: @gziolo: I'm a bit behind discussions about notices. Looking at the `renderError()` method it seems this component is able to handle both global and local notices. Now I have no idea if it's a left over or if that's something that is required. Maybe @scruffian or @drewblaisdell can chime in.

**Comment by stephanethomas** [comment]
Thanks everyone for your feedback! It seems that what was supposed to be a very simple pull request is just a can of worms. I took another stab to it today and tried different things to no avail (such as upgrading `tween.js`). I decided to give up introducing this new `scrollToTop()` function in the `scroll-to` lib, and just call `window.scrollTo()` directly. This is ready for review again.

File: client/blocks/login/index.jsx [hunk 4]
```diff
@@ -40,12 +40,30 @@ class Login extends Component {
 	};
 
 	componentWillMount = () => {
-		if ( ! this.props.twoStepNonce && this.props.twoFactorAuthType && typeof window !== 'undefined' ) {
+		if ( typeof window === 'undefined' ) {
```
Comment (gziolo) [inline client/blocks/login/index.jsx]: > This is the only lifecycle hook called on server rendering.

You can use `componentDidMount` and check against `window` won't be necessary. See https://facebook.github.io/react/docs/react-component.html#componentwillmount

File: client/blocks/login/index.jsx [hunk 5]
```diff
@@ -40,12 +40,30 @@ class Login extends Component {
...
+		}
+
+		if ( ! this.props.twoStepNonce && this.props.twoFactorAuthType ) {
 			// Disallow access to the 2FA pages unless the user has received a nonce
 			page( login( { isNative: true } ) );
 		}
 	};
 
+	componentWillReceiveProps = ( nextProps ) => {
+		if ( typeof window === 'undefined' ) {
```
Comment (gziolo) [inline client/blocks/login/index.jsx]: `componentWillReceiveProps` is never called on the server, so we can skip check against `window`.

**Comment by gziolo** [comment]
It works as expected with the updated code. I left some comments to consider, but I wouldn't call them blockers.

🚢

**Comment by stephanethomas** [comment]
I've rebased and addressed your comments.
