### PR TITLE
Store: Fix react warning for quantity field

### LINKED ISSUE #19438: Store: Product: Inventory: Warning: FormTextInput is changing an uncontrolled input of type number to be controlled
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/store/product/{DOMAIN}
2. Note that when you start entering a value in the Inventory field, the React warning occurs

#### Screenshot / Video

uncontrolled-to-controlled

#### Context / Source
* Today's master

### PR DESCRIPTION
**Pull request by coderkevin**
This fixes a warning from React about changing a component from managed
to unmanaged as `undefined` was being passed as a value to the field.

To test:

1. Edit a product and update it.
2. Click the "Add" button for a new product in the sidebar.
3. Verify no React warnings for managed/unmanaged components in the console.

Note: I found this issue while looking at #20490 and this PR doesn't solve that issue, only the extra warning I found here.

Fixes #19438

### CODE REVIEW

File: client/extensions/woocommerce/app/products/product-form-simple-card.js [hunk 1]
```diff
@@ -97,7 +97,7 @@ const ProductFormSimpleCard = ( { siteId, product, editProduct, translate } ) =>
 	} );
 
 	const { stock_quantity } = product;
-	const quantity = ! isNull( stock_quantity ) ? stock_quantity : '';
+	const quantity = isNull( stock_quantity ) || isUndefined( stock_quantity ) ? '' : stock_quantity;
```
Comment (budzanowski) [inline client/extensions/woocommerce/app/products/product-form-simple-card.js]: maybe you could use `lodash.isNil` ?
