### PR TITLE
Cancel Purchase: show marketplace subscriptions dialog.

### LINKED ISSUE #65235: Marketplace plugins remain active after cancelling a plan
### Quick summary

https://github.com/Automattic/wp-calypso/pull/59910 introduced a new mechanism that deactivates all the active marketplace plugins on a site when deactivating the required plan needed for them to work.

However, looks like it only covered the removal flow. When cancelling a plan, the marketplace plugins remain active.

To clarify, we have two deactivation flows:
- **Removal flow**: when the purchase has auto-renew OFF (e.g. purchases made with credits). It's handled here: https://github.com/Automattic/wp-calypso/tree/trunk/client/me/purchases/remove-purchase.
- **Cancellation flow**: when the purchase has auto-renew ON (e.g. purchases made with a credit card). It's handled here: https://github.com/Automattic/wp-calypso/tree/trunk/client/me/purchases/cancel-purchase.

We should incorporate the same mechanism into the cancellation flow.

cc @cpapazoglou @gcsecsey

### Steps to reproduce

- Go to https://wordpress.com
- Switch to a Simple site
- Purchase a Pro plan with a credit card (you can use the Sandbox store if you don't want to enter an actual credit card: PCYsg-IA-p2#sandbox)
- Go to Plugins
- Purchase a paid plugin with a credit card
- Go to Upgrades > Purchases
- Cancel the Pro plan

### What you expected to happen

To see a warning indicating that all the marketplace plugin will be cancelled as well, like we do when removing a plan:

Screen Shot 2022-07-05 at 13 51 09

### What actually happened

There is no warning and all the marketplace plugins remain active

### PR DESCRIPTION
**Pull request by cpapazoglou**
### Proposed Changes

* Displays the following Dialog in both **Cancellation flow** and **Cancellation and refund flow**
CleanShot 2022-09-30 at 17 40 24@2x

* The Dialog is displayed when the user tries to either Remove or Cancel a Plan, and it has active Marketplace subscriptions. For example, the user has _WooCommerce Bookings_ and a _Businesss_ plan and tries to remove or cancel the _Business_ plan.
* The following is a table with three different scenarios when removing/cancelling a purchase
> **Note** That some recent changes have changed the wordings and removed the `and Refund` words, [comment here](https://github.com/Automattic/wp-calypso/pull/65596#issuecomment-1260736588)

|Removal Flow | Cancellation Flow | Cancellation and Refund Flow |
|-------|------|------|
|    `CleanShot`` 2022-09-26 at 09 47 37@2x    |     CleanShot 2022-09-26 at 09 40 49@2x        |     CleanShot 2022-09-26 at 09 38 04@2x       |  

- This PR will only affect the **Cancellation flow** (the last two columns above), and the existing **Removal flow** (first column) has not been modified
- The changes suggested are:
  - Update the logic in the cancellation flow to display the modal when cancelling a plan
  - Iterate over all the subscriptions and either cancel or cancel and refund them when required
  - Adds two new async methods that will be used in the previous log instead of using callbacks

#### Scenario 1: Cancel and Refund:
- Go to https://wordpress.com/
- Switch to a Simple site
- Purchase a Business plan with a credit card (you can use the Sandbox store if you don't want to enter an actual credit card:  PCYsg-IA-p2#sandbox)
- Go to Plugins
- Purchase a paid plugin with a credit card
- Go to Upgrades > Purchases
- Cancel and Refund the Business plan
- Make sure a Dialog is displayed asking for confirmation. The Dialog should refer to the `Cancel` flow instead of `Remove` in the wordings.
- Click on `Continue`
- Make sure that both the plan and the subscriptions have been cancelled and refunded.

#### Scenario 2: Cancel:
- Go to https://wordpress.com/
- Switch to a Business site **that was purchased with a credit card more than 14 days ago**
- Go to Plugins
- Purchase a paid plugin with a credit card
- Make sure the plugin has auto-renew activated -> Auto-renew is **ON**
- Go to Upgrades > Purchases
- Cancel the Business plan
- Make sure a Dialog is displayed asking for confirmation. The Dialog should refer to the `Cancel` flow instead of `Remove` in the wordings.
- Click on `Continue`
- Make sure that the plan is cancelled and the subscription auto-renew is **OFF**

#### Scenario 3: Removal flow (this is to check there is no regression in existing functionality):
- Go to https://wordpress.com/
- Switch to a Simple site
- Purchase a Business plan **with credits**
- Go to Plugins
- Purchase a paid plugin **with credits**
- Go to Upgrades > Purchases
- Remove the Business plan
- Make sure the following Dialog is displayed https://user-images.githubusercontent.com/11555574/149156886-64d2f4a1-fe99-4209-981a-eeacb417dcf8.png
- Click on `Remove Plan & All Subscriptions`
- Make sure that both the plan and the subscriptions have been cancelled and refunded.

#### Pre-merge Checklist

Complete applicable items on this checklist **before** merging into trunk. Inapplicable items can be left unchecked.

Both the PR author and reviewer are responsible for ensuring the checklist is completed.

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in [Simple](P9HQHe-k8-p2-p2), [Atomic](P9HQHe-jW-p2-p2), and [self-hosted Jetpack sites](PCYsg-g6b-p2-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Are we memoizing when appropriate (for expensive computations)? More info in [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md) and [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors)
- [ ] Have we sent any new strings [for translation](PCYsg-1vr-p2-p2) ASAP?

Fixes #65235

### CODE REVIEW

**Comment by cpapazoglou** [comment]
This is still WIP, I am having a problem getting the `ProductList`.

**Comment by epeicher** [comment]
Applying this branch displays the Modal as expected 
CleanShot 2022-09-21 at 18 56 25@2x
but the subscriptions are not removed. 

I am going to investigate

**Comment by cpapazoglou** [comment]
The intention is that marketplace subscriptions are note removed when canceling a purchase. They should remain functional until subscription expires and plan gets removed. I haven't updated the copy at all though here.

**Comment by epeicher** [comment]
When following the **Cancellation flow** instead of the **Removal flow** (reference [here](https://github.com/Automattic/wp-calypso/issues/65235#issue-1294255727)), the following modal will be displayed:
CleanShot 2022-09-23 at 15 51 54@2x

**Comment by epeicher** [comment]
[Question asked in the linked task](https://github.com/Automattic/wp-calypso/issues/65235#issuecomment-1256329787) to  confirm the approach before proceeding

**Comment by epeicher** [comment]
I have uploaded some changes to handle Marketplace subscription removal and cancels. I have refactored a bit the `cancel-purchase/button.jsx` component to use `async-await` as it simplifies the code when using a collection of asynchronous tasks.

The following video has been recorded with a test done cancelling a plan that is more than 14 days old and it was paid using credit card

https://user-images.githubusercontent.com/3519124/192029990-73edc6a3-6262-4dc0-8e10-e7813858ef65.mp4

**Comment by epeicher** [comment]
The following video has been recorded showing the flow when the system allows **Cancel and Refund**:

https://user-images.githubusercontent.com/3519124/192214808-2cd26e3f-bef8-40d0-973e-15898b14e573.mp4

In this scenario **both the Plan and the Plugins are refunded**

**Comment by cpapazoglou** [comment]
The modal though still has the wrong content, it should look like this
image

> When the user is allowed to Cancel and Refund ([example video here](https://github.com/Automattic/wp-calypso/pull/65596#issuecomment-1257578639)):
The site plan is immediately cancelled and refunded
The plugin is immediately cancelled and refunded

The plugin should not get refunded if the refund period has passed.
Example:
- I renew an annual plan now
- My plugin annual subscription expires in 5 days

If I Cancel my plan:
- plan should get refunded and removed
- plugin should be removed - no refund for the plugin

**Comment by epeicher** [comment]
Heads up, after the following changes https://github.com/Automattic/wp-calypso/pull/68088/files the logic of `Cancel` and `Cancel and Refund` is the same but the wording has changed.

**Comment by epeicher** [comment]
@cpapazoglou thanks for the wording suggestions. I have changed them but maybe we should update it again to cover additional scenarios. 

Regarding the logic implemented, I think it is correct but the description was not accurate. Let me summarise it:
#### Removal flow:

This has not changed as part of this PR. When the user removes a plan, everything seems to be removed. This could be handled in a follow-up task if it is not correct.

#### Cancellation flow
- User cancels a plan. Regardless of the plan being refundable or not:
- _For each_ subscription:
  - If the purchase is cancellabe, it will be cancelled. This means auto-renew of the plugin will change to `OFF`
  - If the purchase is cancellable and refundable, it will be cancelled and refunded. This means the plugin is removed immediately.

Please see [this video](
https://user-images.githubusercontent.com/3519124/192768509-a5e44115-44c2-41bf-9de6-aeb814a8fd70.mp4) with a scenario with:
- A site plan that can be cancelled and refunded
- A plugin that can be cancelled and refunded
- A plugin that cannot be refunded

With the above logic, that means that some subscriptions could be refunded and removed immediately and some others will be just cancelled. Should we adapt the wording of the Dialog to the following more generic?
> The subscriptions will be cancelled.

CleanShot 2022-09-28 at 13 27 27@2x

**Comment by cpapazoglou** [comment]
> User cancels a plan. Regardless of the plan being refundable or not:
For each subscription:
If the purchase is cancellabe, it will be cancelled. This means auto-renew of the plugin will change to OFF
If the purchase is cancellable and refundable, it will be cancelled and refunded. This means the plugin is removed immediately.

The plugin subscriptions should depend to the plan being refundable or not, since when the plan is refundable and gets refunded it will get removed, site will get downgraded, plugins will be unusable. In this case (copying exactly what you have suggested which is correct) : 

For each subscription:
- If the purchase is cancellabe, it will be cancelled. This means auto-renew of the plugin will change to OFF
- If the purchase is cancellable and refundable, it will be cancelled and refunded. This means the plugin is removed immediately.

**But if the plan is not refundable**, it won't get removed - it might even expire after 364 days. In this case, plugins should not get refunded - removed. For each subscription we should disable auto-renew and make sure the user is aware.

> Should we adapt the wording of the Dialog to the following more generic?

Yes, feel free to adapt as needed.

**Comment by epeicher** [comment]
> The plugin subscriptions should depend to the plan being refundable or not,

Ok, that makes sense. Thanks for your input! I am going to update the logic to:

#### Cancellation flow
User cancels a plan which is **refundable**:
- For each subscription:
  - If the purchase is cancellable, it will be cancelled. This means auto-renew of the plugin will change to OFF
  - If the purchase is cancellable and refundable, it will be cancelled and refunded. This means the plugin is removed 

User cancels a plan which is **not** refundable:
- For each subscription:
  - If the purchase is cancellable, it will be cancelled. This means auto-renew of the plugin will change to OFF
  - If the purchase is cancellable and refundable, it will **not** be refunded, just cancelled. This means auto-renew of the plugin will change to OFF

**Comment by epeicher** [comment]
The logic has been updated to reflect [the latest comments](https://github.com/Automattic/wp-calypso/pull/65596#issuecomment-1263601669). The Dialog wording has been kept generic:

CleanShot 2022-09-30 at 17 40 24@2x

File: client/me/purchases/cancel-purchase/button.jsx [hunk 1]
```diff
@@ -314,6 +357,28 @@ class CancelPurchaseButton extends Component {
...
+						activeSubscriptions={ activeSubscriptions }
+						sectionHeadingText={ translate( 'Cancel %(plan)s', {
+							args: { plan: planName },
+						} ) }
+						primaryButtonText={ translate( 'Continue', {
+							comment:
+								'This button cancels the active plan and all active Marketplace subscriptions on the site',
+						} ) }
+						bodyParagraphText={ translate(
+							'This subscription will be cancelled. It will be removed when your plan expires.',
```
Comment (cpapazoglou) [inline client/me/purchases/cancel-purchase/button.jsx]:
```suggestion
							'This subscription will be cancelled. It will be removed when it expires.',
```

File: client/me/purchases/cancel-purchase/button.jsx [hunk 2]
```diff
@@ -314,6 +357,28 @@ class CancelPurchaseButton extends Component {
...
+							'These subscriptions will be cancelled. They will be removed when your plan expires.',
```
Comment (cpapazoglou) [inline client/me/purchases/cancel-purchase/button.jsx]:
```suggestion
							'These subscriptions will be cancelled. They will be removed when they expire.',
```

**Comment by cpapazoglou** [comment]
Thanks for wrangling this @epeicher!

**Review by WBerredo — APPROVED** [review]

File: client/me/purchases/cancel-purchase/button.jsx (hunk 1 above)
Comment (epeicher) [reply client/me/purchases/cancel-purchase/button.jsx]: That new wording is more accurate, thanks for the suggestions!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7561230

Thank you @cpapazoglou for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7561230).
