### PR TITLE
Tour Kit/Welcome Tour: On step view callback handler

### LINKED ISSUE #59700: Tour Kit: Introduce on-step-view logic / callback handler
### Details

As part of the extraction, we will need a callback handler that will execute once per step view. This was originally used in the welcome tour [to record a track event once per slide view](https://github.com/Automattic/wp-calypso/blob/trunk/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-card.js#L42), so we ought to migrate that over to tour-kit in a generic form (to aid with the variant extraction). So a variant implementation (where step renderers will be implemented in the package) should be able to pass a callback to execute once per step view.

p.s. I believe this is actually broken right now in the welcome tour since we removed the ID from the card component a while back. Ideally, the event should only be called once per session (page load). Let's confirm first.

### Checklist

A bit of investigation first to get a sense of approach. The end solution may look like:

- [ ] Add a `onStepViewOnce` callback to the tour-kit [types](https://github.com/Automattic/wp-calypso/blob/trunk/packages/tour-kit/src/types.ts#L51)
- [ ] Handle the callback in the new TourKitStep component
- [ ] Make sure it fires once per step view per session

### Related

_No response_

### LINKED ISSUE #59763: Welcome Tour: Slide view tracking records only first step view
### Quick summary

In `tour-card.js` we record the event `calypso_editor_wpcom_tour_slide_view`. 
It should record one event per slide view per session, but it instead is now broken and only records the first view.

Related to [59700](https://github.com/Automattic/wp-calypso/issues/59700)

### Steps to reproduce

1. Open Welcome Tour
2. Check when `recordTracksEvent` is called 

### What you expected to happen

I expected it to record an event for each slide viewed, only once per slide per session

### What actually happened

Only recorded the first step view

### Reproducibility

Consistent

### PR DESCRIPTION
**Pull request by escapemanuele**
#### Changes proposed in this Pull Request

*  Added a `onStepViewOnce` callback to the tour-kit, it can be added to the tour options (see [types](https://github.com/Automattic/wp-calypso/pull/59719/files#diff-0c13310d2a096eea8756b621efe0c8e337e90c2e35d75dd8abf2094d71353ce9R61)). This function will be called once per session on every different step view.
* removed `justMaximized` state (and `setJustMaximized`), it's no longer needed (it was used to avoid another event record when you returned to maximized state after minimizing the tour)
* moved tracking of `calypso_editor_wpcom_tour_slide_view` from `tour-card` to the `onStepViewOnce` callback

#### Testing instructions

* checkout branch
* `yarn dev --sync` from `apps/editing-toolkit` to sync the welcome tour to the sandbox
* Event `calypso_editor_wpcom_tour_slide_view` should be recorded only once per step per session

Related to #59700
Fixes #59700
Fixes #59763

### CODE REVIEW

File: packages/tour-kit/src/components/tour-kit-frame.tsx [hunk 1]
```diff
@@ -29,6 +29,8 @@ const TourKitFrame: React.FunctionComponent< Props > = ( { config } ) => {
 		null
 	);
 	const [ isMinimized, setIsMinimized ] = useState( false );
+
+	const [ stepsViewed, setStepsViewed ] = useState< number[] >( [] );
```
Comment (escapemanuele) [inline packages/tour-kit/src/components/tour-kit-frame.tsx]: To be defined if we want this state to be here or inside context, to have `tour-kit-frame` know a little less about things.

Comment (escapemanuele) [reply packages/tour-kit/src/components/tour-kit-frame.tsx]: We decided to remove context from the Welcome Tour, so we'll leave this state where it is for the moment!

File: packages/tour-kit/src/components/tour-kit-step.tsx [hunk 2]
```diff
@@ -29,6 +34,19 @@ const TourKitStep: React.FunctionComponent< Props > = ( {
 		config.steps[ currentStepIndex ].options?.className
 	);
 
+	useEffect( () => {
+		if ( typeof config.options?.callbacks?.onStepViewOnce !== 'function' ) {
+			return;
+		}
```
Comment (chriskmnds) [inline packages/tour-kit/src/components/tour-kit-step.tsx]: Nit - I think it might be better to move this to the end and let the rest of the logic work irrespective. Keeping track of viewed steps is something that could happen regardless of callback (I think!).

So could be:

```
typeof config.options?.callbacks?.onStepViewOnce === 'function' && config.options?.callbacks?.onStepViewOnce( currentStepIndex );
```

Thinking whether to actually even avoid the "function" check and let it error if misused in this case. 😬

File: packages/tour-kit/src/components/tour-kit-step.tsx [hunk 3]
```diff
@@ -29,6 +34,19 @@ const TourKitStep: React.FunctionComponent< Props > = ( {
 		config.steps[ currentStepIndex ].options?.className
 	);
 
+	useEffect( () => {
```
Comment (chriskmnds) [inline packages/tour-kit/src/components/tour-kit-step.tsx]: Thinking whether we can abstract this into a hook and avoid passing state through this way? Something like `use-step-tracking`

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-launch.js [hunk 4]
```diff
@@ -93,12 +87,22 @@ function WelcomeTour() {
...
 				},
 				onMaximize: ( currentStepIndex ) => {
-					setJustMaximized( true );
 					recordTracksEvent( 'calypso_editor_wpcom_tour_maximize', {
 						is_gutenboarding: isGutenboarding,
 						slide_number: currentStepIndex + 1,
 					} );
 				},
+				onStepViewOnce: ( currentStepIndex ) => {
+					const lastStepIndex = tourSteps.length - 1;
```
Comment (chriskmnds) [inline apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-launch.js:95]: `tourSteps` is a bit of a side effect here as it's coming from the outer context (same with `isGutenboarding`). We may need to rethink these a bit, but not sure exactly how right now 🤔

**Review by chriskmnds — COMMENTED** [review]
Thanks buddy!

File: packages/tour-kit/src/components/tour-kit-step.tsx (hunk 2 above)
Comment (escapemanuele) [reply packages/tour-kit/src/components/tour-kit-step.tsx]: Cool, I did not think that keeping track of viewed steps was something we'd need if no callback function was provided, but it's something that could be useful 👍

File: packages/tour-kit/src/components/tour-kit-step.tsx (hunk 3 above)
Comment (escapemanuele) [reply packages/tour-kit/src/components/tour-kit-step.tsx]: Abstracted into `useStepTracking` in [d3309c7](https://github.com/Automattic/wp-calypso/pull/59719/commits/d3309c7f34e74ae97bdf1dcfad8f98bc772cbcd0)

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-launch.js (hunk 4 above)
Comment (escapemanuele) [reply apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-launch.js:95]: Good news is that `isGutenboarding` is already going to be removed in [60040](https://github.com/Automattic/wp-calypso/issues/60040). We need to think about what to do with `tourSteps` here, if there is another solution apart from passing used values to the `onStepViewOnce` function

File: packages/tour-kit/src/hooks/use-step-tracking.ts [hunk 5]
```diff
@@ -0,0 +1,27 @@
...
+): void => {
+	const [ stepsViewed, setStepsViewed ] = useState< number[] >( [] );
+
+	useEffect( () => {
+		if ( stepsViewed.includes( currentStepIndex ) ) {
+			return;
+		}
+
+		setStepsViewed( ( prev ) => [ ...prev, currentStepIndex ] );
+
```
Comment (chriskmnds) [inline packages/tour-kit/src/hooks/use-step-tracking.ts]:
```suggestion
```

File: packages/tour-kit/src/components/tour-kit-frame.tsx [hunk 6]
```diff
@@ -29,6 +30,9 @@ const TourKitFrame: React.FunctionComponent< Props > = ( { config } ) => {
 		null
 	);
 	const [ isMinimized, setIsMinimized ] = useState( false );
+
+	useStepTracking( currentStepIndex, config.options?.callbacks?.onStepViewOnce );
```
Comment (chriskmnds) [inline packages/tour-kit/src/components/tour-kit-frame.tsx]: Let's move this down to line ~196, after the `const` definitions?

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-launch.js (hunk 4 above)
Comment (chriskmnds) [reply apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-launch.js:95]: We can come back to this in a follow-up.

**Review by chriskmnds — APPROVED** [review]
Thanks for the follow-ups! The code looks good. I think test a few more times to make sure we are not missing something, and 🚢 🇮🇹
