### PR TITLE
GuidedTours: target-based blanket exit without `Continue`

### LINKED ISSUE #9178: Guided Tours: Tour does not quit when leaving relevant page
#### Steps to reproduce
1. Checkout branch from #8627 
2. Starting at URL: http://calypso.localhost:3000/stats/day/___your_primary_site___?tour=siteTitle
3. Click "Let's change it" and "Settings"
4. With bubble below the input, open Reader

#### What I expected

No more bubble.

#### What happened instead

Bubble stayed on screen and even moves with page when you scroll.

#### Screenshot / Video

screen shot 2016-11-07 at 15 45 39
screen shot 2016-11-07 at 15 46 01

### PR DESCRIPTION
**Pull request by lsinger**
In Guided Tours, "blanket exit" is the idea that when a user navigates away, they might want to quit the tour that is currently running. It tries to infer user intent.

One heuristic we use is to quit the tour if the current step has a target we want to point at but we can't find that target on the page. However, we have used that only in the `Continue` element, since we had assumed that only there would we need targets.

Now that @marekhrabe has been working on a "site title" tour in #8627, we noticed that having a target is perfectly legitimate even when the user advances the step manually with a "Next" button. In such a case, "blanket exit" would not have worked because the check for finding the target element would not have been called.

Therefore, this change moves the check for the target into the more general `Step` component. If our step has a target and we can't find it on the page, we quit the tour.

Fixed #9178. 

To test: 

- make sure the `main` tour and the `siteTitle` tour (apply this change to #8627) both still work
- make sure blanket exit works for both the `main` tour and the `siteTitle` tour (apply this change to #8627)

### CODE REVIEW

File: client/layout/guided-tours/config-elements.js [hunk 1]
```diff
@@ -193,12 +193,22 @@ export class Step extends Component {
...
 			} );
-		} else {
-			debug( 'Step.quitIfInvalidRoute: not quitting' );
 		}
+
+		// quit if we have a target but cant find it
+		defer( () => {
+			const { quit } = this.context;
+			const target = targetForSlug( this.props.target );
+			if ( this.props.target && ! target ) {
```
Comment (mcsf) [inline client/layout/guided-tours/config-elements.js]: What happens if `target` is a prop of something below `Step` instead? Do we need to change the tour configs? (They aren't touched by this PR so far)

Comment (lsinger) [inline client/layout/guided-tours/config-elements.js]: Interestingly in all the cases I was able to find, we duplicated any `target` in a `Continue` element in its parent `Step` component.

Comment (mcsf) [inline client/layout/guided-tours/config-elements.js]: Let's!

Comment (lsinger) [inline client/layout/guided-tours/config-elements.js]: There it is: #9435 

Is this PR ready to go, then? 😬

Comment (mcsf) [inline client/layout/guided-tours/config-elements.js]: 🚢 🚢
