### PR TITLE
WooExpress: Check for WooCommerce at the beginning of the plugin-bundle flow

### LINKED ISSUE #71215: Bundled Plugins: Atomic sites activating bundled themes produce unexpected results
**Steps to reproduce**

1. Visit `/themes` on an Atomic site (*.wpcomstaging or custom domain) that already has WooCommerce activated
2. Activate a theme that bundles WooCommerce (like Tsubaki or Tazza) - click the three-dots menu and Activate, or visit the theme's page and click Activate 
3. You'll be prompted to choose whether to replace your home page content -- doesn't matter which you choose, pick one and click Activate
4. You'll be redirected to `/setup/plugin-bundle/getCurrentThemeSoftwareSets?siteSlug=[siteSlug]`, then to `/home/[siteSlug]`

**What I expected to happen**

To have the theme activate, stay on the Theme Showcase (or at least direct me back to it), and display a notice similar to this:

Screen Shot 2022-12-14 at 3 21 03 PM

**What happens instead**

https://user-images.githubusercontent.com/2124984/207705466-542629f8-4d1e-4ad5-bee8-62f3388bf295.mov

### PR DESCRIPTION
**Pull request by markbiek**
Closes #71215

## Proposed Changes

When we start the plugin-bundle flow, we check to see if WooCommerce is already installed. If it is, we exit the flow early.

The normal behavior for themes with bundled plugins is that they return to `/home` after the plugin-bundle flow. In our case, we'll actually end up on the WooCommerce launch checklist which is the correct behavior for WooExpress trial sites.

## Testing Instructions

* Apply this branch.
* Start with an existing trial site or create a new one by visiting http://calypso.localhost:3000/setup/wooexpress/.
* Once the trial site is complete visit, `http://calypso.localhost:3000/themes/:siteSlug?s=tazza`.
* Activate the Tazza theme.
* You should briefly enter the plugin-bundle flow but will return to the dashboard after the `checkForWoo` step.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: client/landing/stepper/declarative-flow/internals/steps-repository/check-for-woo/index.tsx [hunk 1]
```diff
@@ -0,0 +1,46 @@
+/* eslint-disable no-console */
```
Comment (daledupreez) [inline client/landing/stepper/declarative-flow/internals/steps-repository/check-for-woo/index.tsx]: I think we should remove this line. 😁 
```suggestion
```

File: client/landing/stepper/declarative-flow/plugin-bundle-flow.ts [hunk 2]
```diff
@@ -130,6 +130,15 @@ const pluginBundleFlow: Flow = {
 			recordSubmitStep( providedDependencies, intent, flowName, currentStep );
 
 			switch ( currentStep ) {
+				case 'checkForWoo':
+					// If WooCommerce is already installed, we should exit the flow.
+					if ( providedDependencies?.hasWooCommerce ) {
+						return exitFlow( `/home/${ siteSlug }` );
```
Comment (daledupreez) [inline client/landing/stepper/declarative-flow/plugin-bundle-flow.ts:136]: This experience is awkward for the user -- after switching a theme, I am completely removed from the context I was in before I started that flow.

Maybe for a follow-up PR, but can we pass in a URL to redirect to or even an allow-list of URL identifiers that we will redirect to? e.g. `themes` or `themes/<theme_slug>` That we way at least drop the user into the theme showcase or theme detail page if that's where they started.

**Review by daledupreez — APPROVED** [review]
This is working as expected, and definitely fixes the stalling issue, so I think we should ship this ASAP.

However, I think we should fix the overall flow for users who are only switching their theme in a follow-up PR.

File: client/landing/stepper/declarative-flow/internals/steps-repository/check-for-woo/index.tsx (hunk 1 above)
Comment (markbiek) [reply client/landing/stepper/declarative-flow/internals/steps-repository/check-for-woo/index.tsx]: Sorry, I keep accidentally leaving those in when I copy from another step. I'll add it to my personal checklist so I remember next time.

File: client/landing/stepper/declarative-flow/plugin-bundle-flow.ts (hunk 2 above)
Comment (markbiek) [reply client/landing/stepper/declarative-flow/plugin-bundle-flow.ts:136]: I've created #73661 to tackle that after this PR ships.
