### PR TITLE
Block Editor Tracking: Fix innerBlocksReplace tracking

### LINKED ISSUE #53413: Undo/Redo events affecting Reusable Block and Template Part content triggers block inserted tracking events.
When an "undo" or "redo" event happens that affects a Reusable Block or Template Part's content, a (or multiple) "wpcom_block_inserted" tracking event fires.

To Reproduce:
* Debug log wpcom editor tracking events.
* Add a template part or reusable block to the post/page editor.
* Update inner block content of a paragraph.
* Hit "undo"
* Notice 'wpcom_block_inserted' event in the log just after the undo event.

Related:
#53410

### PR DESCRIPTION
**Pull request by david-szabo97**
#### Changes proposed in this Pull Request

Reusable Block and Template Parts are loaded asynchronously from the REST API. When they are loaded, then all the blocks from the API response are inserted by using `replaceInnerBlocks`. This causes the `trackInnerBlockReplacement` to track all these block replacements. Which is giving us totally false tracking 😄  

Any changes made to the underlying template part or reusable block entity will result in a `replaceInnerBlocks`.
These changes will result in a `replaceInnerBlocksCall`:
* any undo or redo related to template parts and reusable blocks
* having multiple instances of a template part or reusable block and making an edit to a single instance
* template part and reusable block loading for the first time

We want to ignore all of these and as far as we know, there are no other use-case that's relying on `replaceInnerBlocks`. So we are safe to ingore them.

Related code for template part inner blocks syncing: https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/inner-blocks/use-inner-block-template-sync.js

Related code for reusable block inner blocks syncing: https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/provider/use-block-sync.js

#### Testing instructions

* Follow steps to enable tracking debugging at PCYsg-nrf-p2

**Reusable Block**

* Create a new Post
* Add any block
* Convert it to a reusable block
* Save and Refresh page
* Make sure `replaceInnerBlocks` is called (you will see that in the console), but no events are recorded
  * `trunk` branch:
image

  * this branch:
image

**Template Part**
* Open site editor
* Insert template parts if you don't have any
* Make sure you have blocks inside the template parts
* Save and Refresh page
* Make sure `replaceInnerBlocks` is called for each template part (you will see that in the console), but no events are recorded

Fixes  #53413

### CODE REVIEW

**Review by Addison-Stavlo — COMMENTED** [review]
I tested the changes so far and they seem to now work as expected!  I think the assumptions we are making make sense here. 🤔

File: apps/wpcom-block-editor/src/wpcom/features/tracking.js [hunk 1]
```diff
@@ -281,6 +282,36 @@ const trackBlockReplacement = ( originalBlockIds, blocks, ...args ) => {
...
+	// populated when the response is received. We want to ignore
+	// `replaceInnerBlocks` action calls when the `innerBlocks` are replaced
+	// because the template part or reusable block just loaded.
+	const parentBlock = select( 'core/block-editor' ).getBlocksByClientId( rootClientId )?.[ 0 ];
+	if ( parentBlock ) {
+		const { name, innerBlocks } = parentBlock;
+		const isAsyncLoadedEntityBlock =
+			// Template Part
+			name === 'core/template-part' ||
+			// Reusable BLock
```
Comment (tyxla) [inline apps/wpcom-block-editor/src/wpcom/features/tracking.js]:
```suggestion
			// Reusable Block
```

File: apps/wpcom-block-editor/src/wpcom/features/tracking.js [hunk 2]
```diff
@@ -281,6 +282,36 @@ const trackBlockReplacement = ( originalBlockIds, blocks, ...args ) => {
...
+			return;
+		}
+	}
+
+	// Performing an undo or redo will cause affected template parts
+	// and reusable blocks to synchronize their inner blocks.
+	// Which results in `replaceInnerBlocks` calls. We ignore them
+	// to avoid tracking these changes since they are behind the scenes changes.
+	const msElapsedSinceLastUndoOrRedo = Date.now() - lastUndoOrRedoTimestamp;
+	const IGNORE_THRESHOLD_IN_MS = 250;
```
Comment (tyxla) [inline apps/wpcom-block-editor/src/wpcom/features/tracking.js]: Do we know for sure that 250ms is enough for the synchronization of inner blocks to complete? Is there a better way to guarantee that happened?

File: apps/wpcom-block-editor/src/wpcom/features/tracking.js (hunk 1 above)
Comment (david-szabo97) [reply apps/wpcom-block-editor/src/wpcom/features/tracking.js]: Thanks!

File: apps/wpcom-block-editor/src/wpcom/features/tracking.js (hunk 2 above)
Comment (david-szabo97) [reply apps/wpcom-block-editor/src/wpcom/features/tracking.js]: I think a better way to guarantee it is just to ignore all the `replaceInnerBlocks` for Template parts and Reusable blocks. I did some digging and it seems to be a good way for now. I'm not sure about its future-proof-ness though. We are very limited here and we can't differentiate between a user action vs behind the scenes action. So we better ignore everything and put some actions on the allow list later on if we need to.

Comment (david-szabo97) [reply apps/wpcom-block-editor/src/wpcom/features/tracking.js]: Updated the PR description to reflect the latest commits.

Comment (Addison-Stavlo) [reply apps/wpcom-block-editor/src/wpcom/features/tracking.js]: >I think a better way to guarantee it is just to ignore all the replaceInnerBlocks.

Just noting (as is in the PR description as well) that this is only ignored for Template Parts and Reusable blocks.  Very well described comments in the code 😁 .

**Review by Addison-Stavlo — APPROVED** [review]

**Review by Copons — APPROVED** [review]

**Review by tyxla — APPROVED** [review]
👍
