### PR TITLE
Fix/focus plugin list update

### LINKED ISSUE #2227: Jetpack Plugins: main content area hidden when selecting site from sidebar before to update plugin
Steps to reproduce:

1. Go to https://wordpress.com/plugins
2. In the sidebar, click on "Switch Site". The main content area gets hidden.
3. In the sidebar, click on the Orange update icon on a site where a plugin update is available.
4. In the sidebar, click on "There is a plugin update available"
5. The site's plugin update page loads, but the main content area is still hidden.

Here is a screencast:
https://cloudup.com/ctm9zYKrMTI

### PR DESCRIPTION
**Pull request by enejb**
Fixes #2227

Currently site indicator when clicked on can't refocus the right side of the page. 
This PR fixes this by passing the onSelect function to the site indicator. 

To test:
1. Go to https://wordpress.com/plugins
2. In the sidebar, click on "Switch Site". The main content area gets hidden.
3. In the sidebar, click on the Orange update icon on a site where a plugin update is available.
4. In the sidebar, click on "There is a plugin update available"
5. The site's plugin update page loads, but the main content area is still now shown. 

cc @jeherve

### CODE REVIEW

File: client/my-sites/site-indicator/site-indicator.jsx [hunk 1]
```diff
@@ -124,8 +133,11 @@ export default React.createClass( {
 		}.bind( this ), 15000 );
 	},
 
-	handlePluginsUpdate() {
+	handlePluginsUpdate( event ) {
 		window.scrollTo( 0, 0 );
+		if ( this.props.onSelect ) {
+			this.props.onSelect( event );
```
Comment (dmsnell) [inline client/my-sites/site-indicator/site-indicator.jsx]: Something I like to do in cases like this is to eliminate the presence-checking by setting a default `noop` on the prop…

```js
import { noop } from 'lodash';

getDefaultProps: () => ( {
	onSelect: noop
} )
```

This way, we can safely call `this.props.onSelect( event )` without the conditional.

File: client/my-sites/site/index.jsx [hunk 2]
```diff
@@ -89,7 +89,7 @@ module.exports = React.createClass( {
 		}
 
 		siteClass = classNames( {
-			'site': true,
+			site: true,
```
Comment (dmsnell) [inline client/my-sites/site/index.jsx]: we can also pass always-true classes as the first parameter here:

```js
siteClass = classNames( 'site', {
	'is-jetpack': site.jetpack,
	'is-primary': site.primary,
	'is-private': site.is_private
} );
```

**Comment by johnHackworth** [comment]
I've rebased this & resolved some conflicts, also added the noop suggestion @dmsnell did. I think it's ready to go!

**Comment by enejb** [comment]
Thanks for the reviews + changes. @johnHackworth and @dmsnell

**Comment by gravityrail** [comment]
lgtm :+1:
