### PR TITLE
Hide inline-help widget in the help page

### LINKED ISSUE #32590: Help: Help icon covers Send button in mobile browser
The Help (?) icon covers the Send button in a mobile browser.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/help/contact in mobile browser
2. Start a chat.
3. Go to another page in the dashboard.
4. Tap on the chat icon to return to chat.

#### What I expected
The Help (?) icon hides itself.

#### What happened instead
The Help (?) icon reappeared and covered the Send button.

#### Browser / OS version
iOS 12.2
Chrome

#### Screenshots
IMG_8831
IMG_8833
IMG_8836
IMG_8835

#### Context / Source
#user-report
12146251-hc

### PR DESCRIPTION
**Pull request by alshakero**
#### Changes proposed in this Pull Request

Currently, the inline-help float sometimes covers key parts of the UI on mobile. See [Help: Help icon covers Send button in mobile browser](https://github.com/Automattic/wp-calypso/issues/32590) issue for details.

This PR hides the inline help widget on the help page since users are already in.. well... the help page. 

#### Testing instructions
Move around Calypso making sure the inline-help widget shows in most places. And doesn't appear on the help page. 

Fixes #32590

### CODE REVIEW

File: client/layout/index.jsx [hunk 1]
```diff
@@ -105,30 +105,13 @@ class Layout extends Component {
...
-		}
-
-		if ( '/log-in/jetpack' === this.props.currentRoute ) {
-			return false;
-		}
-
-		if ( '/me/account/closed' === this.props.currentRoute ) {
-			return false;
-		}
+		const exemptedSections = [ 'jetpack-connect', 'happychat', 'devdocs', 'help' ];
```
Comment (alshakero) [inline client/layout/index.jsx:108]: The only logic difference here is adding `help` to the list.

File: client/layout/index.jsx [hunk 2]
```diff
@@ -105,30 +105,13 @@ class Layout extends Component {
...
-
-		if ( 'devdocs' === this.props.sectionName ) {
-			return false;
-		}
-
-		return true;
+		return (
+			! exemptedSections.includes( this.props.sectionName ) &&
+			! exemptedRoutes.includes( this.props.currentRoute )
+		);
```
Comment (alshakero) [inline client/layout/index.jsx:114]: The only logic difference here is adding help to the list.

**Review by andrewserong — APPROVED** [review]
LGTM! Each of the sections and routes hides the inline help as expected, along with the addition of the `help` section. Nice clean refactor, too!
