### PR TITLE
WooExpress: Fixes the padding for RTL languages

### LINKED ISSUE #73392: RTL Languages are breaking My Plan and Plans page
The layout is broken on the My Plan and Plans page because the padding is fixed on the left side, and the icon 👉 is displayed repeatedly.

**My Plan page**
Screen Shot 2023-02-15 at 17 22 34

**Plans page**
Screen Shot 2023-02-15 at 17 25 40

### PR DESCRIPTION
**Pull request by valterlorran**
## Proposed Changes

* Fixes the padding for RTL languages on the My Plans and Plans page.

**Before**
Screen Shot 2023-02-15 at 17 17 58

**After**
Screen Shot 2023-02-16 at 14 47 53

## Testing Instructions

* Navigate to `/me/account` and set an RTL language on the `Interface Language` option. In my case I selected Hebrew.
* Navigate to `/plans/my-plans/:siteSlug` and `/plans/:siteSlug`
* The padding should be fixed now

Closes #73392

### CODE REVIEW

**Review by markbiek — APPROVED** [review]
LGTM!

File: client/my-sites/plans/modernized-layout.tsx [hunk 1]
```diff
@@ -134,10 +134,18 @@ const ModernizedLayout: React.FunctionComponent< { dropShadowOnHeader?: boolean
 			// this overrides the default .layout__content that adds unwanted padding
 			& .layout__content,
 			&.theme-default .focus-content .layout__content {
-				padding: ${ layoutContentPaddingTop } 0 0 0;
+				:not( .rtl ) & {
+					padding: ${ layoutContentPaddingTop } 0 0 0;
```
Comment (aneeshd16) [inline client/my-sites/plans/modernized-layout.tsx]: I was wondering if we can use `padding-inline-` and `padding-block-` styles to simplify this? 🤔 

For example:
```css
padding: 0;
padding-block-start: ${ layoutContentPaddingTop };

@media ( min-width: ${ sidebarAppearanceBreakPoint } ) {
    padding-inline-start: calc( var( --sidebar-width-max ) + 1px );
}
```

Comment (valterlorran) [reply client/my-sites/plans/modernized-layout.tsx]: TIL! Thanks! that made the code way simpler :)

**Review by markbiek — APPROVED** [review]
LGTM!
