### PR TITLE
Woo on Stepper: Fix message on Woo confirm screen

### LINKED ISSUE #63356: Seller Exp - Fix WooCommerce onboarding confirm screen text in Stepper
In the Stepper implementation, the text on the confirmation screen seems a little off:

image

Let's change this to "Upgrade to the Pro plan and..."

### PR DESCRIPTION
**Pull request by andres-blanco**
Changes WooCommerce upsell message on confirm screen.

| Before  | After |
| ------------- | ------------- |
| image  | image |

#### Testing
1. Apply this PR.
2. Go to `http://calypso.localhost:3000/setup/wooConfirm?siteSlug=<YOUR_SITE>` where `<YOUR_SITE>` is a free site.
3. Verify that the messsage to upgrade reads: `Upgrade to the Pro plan and set up your WooCommerce store`.

Closes https://github.com/Automattic/wp-calypso/issues/63356

### CODE REVIEW

File: client/landing/stepper/declarative-flow/internals/steps-repository/woo-confirm/index.tsx [hunk 1]
```diff
@@ -168,13 +167,7 @@ const WooConfirm: Step = function WooCommerceConfirm( { navigation } ) {
...
 		),
 		productName,
-		description: productName
-			? sprintf(
-					/* translators: %s: The upgrading plan name (ex.: WordPress.com Business) */
-					__( 'Upgrade to the %s plan and set up your WooCommerce store.' ),
-					productName
-			  )
-			: __( 'Upgrade to set up your WooCommerce store.' ),
+		description: __( 'Upgrade to the Pro plan and set up your WooCommerce store.' ),
```
Comment (markbiek) [inline client/landing/stepper/declarative-flow/internals/steps-repository/woo-confirm/index.tsx:169]: If we're going to use a static string, we could also get rid of all the references to `productName`.

Comment (andres-blanco) [reply client/landing/stepper/declarative-flow/internals/steps-repository/woo-confirm/index.tsx:169]: I've removed the property from the object, but I left the variable since it looks related to this issue https://github.com/Automattic/wp-calypso/issues/63296

**Review by sixhours — APPROVED** [review]
LGTM! 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7305001

Thank you @andres-blanco for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7305001).
