### PR TITLE
Welcome Tour/Site Editor: Disable WP Core welcome guide when in site editor

### LINKED ISSUE #61036: [Bug]: three consecutive banners when landing in FSE
### Quick summary

There are three upsells/banners in the editor and at least two of them are conflicting with each other (core banner and WPCOM banner). 

See p1644591908914389-slack-C01DF571R5Y for context.

### What to do:

Quoting @simison :
1. Mobile banner shows up too early and then hides; it should be visible in the editor first thing, just like in post/page editor. => PR for this: https://github.com/Automattic/wp-calypso/pull/61134
2. We should show one tour. I’d say let’s show the .com one but no biggie if it’s easier to just show the core one. We’ll do some changes here soon anyway.
3. Let's also ensure we can separate site-editor mobile banner in tracks events from page/post editors. But check first with apps team if that's ok and expected

### Steps to reproduce

See p1644591908914389-slack-C01DF571R5Y for context.

### What you expected to happen

We should show one tour.

### What actually happened

Two tours are showing.

### Context

Discussion about the two modals (the Welcome Tour and the Core modal) is here: pbAok1-2vM-p2

### Browser

iOS Safari

### Simple/Atomic

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### PR DESCRIPTION
**Pull request by escapemanuele**
#### Changes proposed in this Pull Request

Read convo in pbAok1-2vM-p2

Currently, when landing in Full Site Editor we show two modals to the user, the WP Core one and the wordpress.com (see screenshot). 
To fix it quickly we decided to show the wpcom welcome tour only.

#### Screenshots

Before
image

After
image

#### Testing instructions

*  Checkout branch
* `yarn dev --sync` from `apps/editing-toolkit` to sync the welcome tour to the sandbox
*  In Incognito, go to `https://horizon.wordpress.com/start` and create a new website. Choose a FSE theme (like Geologist for example)
*  Before entering the site editor, be sure to sandbox the new website you just created: add `your.sandbox.ip  new-site-name.wordpress.com` to your `/etc/hosts` file 
* Check that only the wpcom welcome tour shows
* Check that the Styles core modal is still showing
image

Related to #61036

### CODE REVIEW

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/disable-core-nux.js [hunk 1]
```diff
@@ -24,4 +24,10 @@ subscribe( () => {
 			openedManually: true,
 		} );
 	}
+	if ( select( 'core/edit-site' )?.isFeatureActive( 'welcomeGuide' ) ) {
+		dispatch( 'core/edit-site' ).toggleFeature( 'welcomeGuide' );
+		dispatch( 'automattic/wpcom-welcome-guide' ).setShowWelcomeGuide( true, {
+			openedManually: true,
```
Comment (Addison-Stavlo) [inline apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/disable-core-nux.js:33]: In the case of initial load, I don't think it makes sense for `openedManually` to be `true`.

I think this is solved for the post editor by lines 8-10:
```
	if ( select( 'core/edit-post' )?.isFeatureActive( 'welcomeGuide' ) ) {
		dispatch( 'core/edit-post' ).toggleFeature( 'welcomeGuide' );
	}
	unsubscribe();
```
And we should probably add this for this `edit-site` version as well. It looks like that first subscribe block is meant to handle the initial load (then unsubscribe), while the second subscribe block is meant to remain and handle the later actions of the user trying to open the guide manually (hence the `openedManually: true` addition there).

So right now this works, but on load we are dismissing the core guide and setting the a8c guide to open (when it is already open) with the added `openedManually` prop. As opposed to just dismissing the core guide and leaving the a8c one alone.

**Review by Addison-Stavlo — COMMENTED** [review]
I tested this out and it works well!

I think we are sending the `openedManually: true` prop in some cases where it doesn't make sense, but I think the fix to that is simple.

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/disable-core-nux.js (hunk 1 above)
Comment (escapemanuele) [reply apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/disable-core-nux.js:33]: Thanks, that makes totally sense, I added those changes in the last commit ([23aaec6](https://github.com/Automattic/wp-calypso/pull/61157/commits/23aaec6bf5f2937839307f4ce3fd496fa0ff797e))!

**Review by Addison-Stavlo — APPROVED** [review]
This still tests well, and makes sense to me. 😁 

Thank you!
