### PR TITLE
Themes: Don't show My Themes for sites that can't upload themes

### LINKED ISSUE #61509: There should be no "My Themes" tab on sub Business plan Atomic sites.
### What plan tier(s) are affected?

Free, Personal, Premium

### Steps to Reproduce

Go to https://wordpress.com/themes/ on a Simple Free site and on an Atomic Free site. There should not be a "My Themes" tab on the Atomic Free site because uploads are not allowed on plans below Business.

### Expected (Simple)

no-my-themes-tab-free-simple

### Expected (Atomic)

There should be no "My Themes" tab in the "Themes" section on plans that don't allow theme uploads. (Currently plans below Business.)

### Actual

my-themes-tab-free-atomic

### Is this specific to the applied theme? If so, which one?

_No response_

### PR DESCRIPTION
**Pull request by obenland**
#### Changes proposed in this Pull Request

* Adds a feature check for WoA sites to determine if My Themes should be shown.

#### Testing instructions

* Set up an Atomic site with a plan below Business.
* Navigate to https://wordpress.com/themes and select a site.
* Verify that My Themes doesn't show up.

Fixes #61509

### CODE REVIEW

File: client/my-sites/themes/theme-showcase.jsx [hunk 1]
```diff
@@ -378,9 +386,11 @@ const mapStateToProps = ( state, { siteId, filter, tier, vertical } ) => {
 	const currentThemeId = getActiveTheme( state, siteId );
 	const currentTheme = getCanonicalTheme( state, siteId, currentThemeId );
 	return {
+		canUploadThemes: hasActiveSiteFeature( state, siteId, FEATURE_UPLOAD_THEMES ),
```
Comment (obenland) [inline client/my-sites/themes/theme-showcase.jsx]: Should this be `FEATURE_INSTALL_THEMES`?

Comment (mmtr) [reply client/my-sites/themes/theme-showcase.jsx]: Installing a theme is the same as uploading it, isn't it? In any case, I think this should check a new `FEATURE_ACTIVATE_THEMES` constant, since My Themes only allows users to activate themes that are already installed in the site.

**Review by mmtr — APPROVED** [review]
This tests well for me! I left a minor comment regarding the name of the feature checked, but that can be followed up later.

File: client/my-sites/themes/theme-showcase.jsx (hunk 1 above)
Comment (obenland) [reply client/my-sites/themes/theme-showcase.jsx]: Did some more research and it looks like `install_themes` lets users install themes from the Theme Directory while `upload_themes` only enables the theme uploader in wp-admin.

So, yeah, I think I agree, checking for `switch_themes` makes sense since they're not able to install themes here.

Comment (obenland) [reply client/my-sites/themes/theme-showcase.jsx]: Hm, the premise of the original issue was

> There should not be a "My Themes" tab on the Atomic Free site because uploads are not allowed on plans below Business.

Comment (mmtr) [reply client/my-sites/themes/theme-showcase.jsx]: Oh right, I guess it would depend on how we sell the Business plan.

If we say that users are only allowed to **use** custom themes on the Business plan, I think we shouldn't differentiate between install/upload/switch, and instead create a more generic feature/capability that includes the whole management of custom themes. That new generic feature/capability is the one we should check everywhere to prevent users from installing/uploading/activating custom themes if the site doesn't have the required upgrade.

On the other hand, if we say that users cannot **upload** custom themes on the Business plan but they are free to **activate** the ones they uploaded while the site had the Business plan active, then we should check `switch_themes` which would keep My Themes available even if the site doesn't have the required upgrade.
