### PR TITLE
Jetpack Plans: Add product API key to purchase page

### LINKED ISSUE #205: .org Plans: no "Registration Keys" page
Steps to reproduce:
1. Purchase a .org Plan
2. Receive an email with your Akismet and VaultPress keys
3. Ignore those, you don't have time to deal with this right now.
4. A few days later, you forgot about the email, and go to https://wordpress.com/my-upgrades , looking for your keys.

Result: No keys anywhere.

### PR DESCRIPTION
**Pull request by ryelle**
Fixes #205, #10494

This PR starts the work to show product API keys in Calypso. It creates a new component card which is displayed on the Manage Purchase page (`/me/purchases`). This only shows up on paid Jetpack sites.

**To test**

1. On a Jetpack site with a Personal, Professional, or Premium plan, view your plan `/plans/my-plan/$site`
2. Click Manage Payment (this is the easiest way to get to the purchase screen)
3. Below your site info, there should be a second card with your API keys.

screen shot 2017-03-16 at 4 31 31 pm
(those are not real keys for the screenshot, but it does show your actual keys 😄 )

cc @johnHackworth

### CODE REVIEW

**Comment by ryelle** [comment]
This also triggers the "Your plan needs setting up" notice due to how it detects that from the state.
 
screen shot 2017-03-16 at 4 36 29 pm

Maybe there should be a separate object in state for "started the install process"? Or we could create another query to fetch these instructions, that doesn't also set the state for auto-installing. Pinging @ebinnion since you've been working on this lately :)

**Comment by johnHackworth** [comment]
this is amazing, @ryelle !!!

**Comment by ebinnion** [comment]
Could we modify the selector to check if we never started installing? Perhaps something like checking if all plugins are `wait` status?

**Comment by ryelle** [comment]
>  Perhaps something like checking if all plugins are wait status?

Ah, that's a good idea. I'll do that in another PR :)

**Comment by ryelle** [comment]
I've addressed the blue banner issue in #12377

**Comment by ryelle** [comment]
I've updated this PR to basically be groundwork for the new design (see #12746) so that we don't have monster PRs :) This one ended up a bit large because I also switched `ManagePurchase` to use localize instead of `this.translate`.

File: client/me/purchases/manage-purchase/index.jsx [hunk 1]
```diff
@@ -681,6 +685,13 @@ const ManagePurchase = React.createClass( {
 					{ contactSupportToRenewMessage }
 				</Card>
 
+				<PurchasePlanDetails
+					hasLoadedSites={ this.props.hasLoadedSites }
+					hasLoadedUserPurchasesFromServer={ this.props.hasLoadedUserPurchasesFromServer }
+					selectedSite={ this.props.selectedSite }
```
Comment (tyxla) [inline client/me/purchases/manage-purchase/index.jsx]: Does it make sense to omit these props here and add them the `connect()` of `PurchasePlanDetails` directly, since it's already connected anyway? This could help make the component more independent. Or are we doing it this way for consistency with other components like `RemovePurchase` for example?

File: client/me/purchases/manage-purchase/index.jsx [hunk 2]
```diff
@@ -436,7 +440,7 @@ const ManagePurchase = React.createClass( {
 			<Notice
 				showDismiss={ false }
 				status="is-error"
-				text={ this.translate( 'This purchase has expired and is no longer in use.' ) }>
+				text={ this.props.translate( 'This purchase has expired and is no longer in use.' ) }>
```
Comment (tyxla) [inline client/me/purchases/manage-purchase/index.jsx]: If we assign `const { translate } = this.props` here and there, we could save some code by avoiding to have to use `this.props.` everywhere.

File: client/me/purchases/manage-purchase/plan-details/index.jsx [hunk 3]
```diff
@@ -0,0 +1,61 @@
...
+		if ( ! isJetpackPlan( purchase ) || isFreeJetpackPlan( purchase ) ) {
+			return null;
+		}
+
+		return (
+			<Card>
+				<QueryPluginKeys siteId={ selectedSite.ID } />
+				{ pluginList.map( ( plugin, i ) => {
+					return (
+						<FormFieldset key={ i }>
```
Comment (tyxla) [inline client/me/purchases/manage-purchase/plan-details/index.jsx]: A design item really, but there's some extra space below the last `FormFieldset`:



Can we avoid that by setting a `margin-bottom: 0` of the `.form-fieldset:last-child`?

File: client/me/purchases/manage-purchase/plan-details/index.jsx [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+import Card from 'components/card';
+import ClipboardButtonInput from 'components/clipboard-button-input';
+import FormFieldset from 'components/forms/form-fieldset';
+import FormLabel from 'components/forms/form-label';
+import QueryPluginKeys from 'components/data/query-plugin-keys';
+import { getPurchase, isDataLoading } from '../../utils';
+import { isJetpackPlan, isFreeJetpackPlan } from 'lib/products-values';
+import { getPluginsForSite } from 'state/plugins/premium/selectors';
+
+class PurchasePlanDetails extends Component {
```
Comment (tyxla) [inline client/me/purchases/manage-purchase/plan-details/index.jsx]: This component is to be used strictly for Jetpack plans, does it make sense to rename it to `PurchaseJetpackPlanDetails` or similar?

File: client/me/purchases/manage-purchase/plan-details/index.jsx [hunk 5]
```diff
@@ -0,0 +1,61 @@
...
+		switch ( slug ) {
+			case 'vaultpress':
+				return this.props.translate( 'Backups and security scanning API key' );
+			case 'akismet':
+				return this.props.translate( 'Anti-spam API key' );
+		}
+	}
+
+	render() {
+		if ( isDataLoading( this.props ) || ! this.props.selectedSite ) {
```
Comment (tyxla) [inline client/me/purchases/manage-purchase/plan-details/index.jsx]: Would it make sense to display a placeholder instead of nothing, for example in a situation where purchases and site have loaded, but plugin keys haven't?

File: client/me/purchases/manage-purchase/plan-details/index.jsx [hunk 6]
```diff
@@ -0,0 +1,61 @@
...
+			return null;
+		}
+
+		const { selectedSite, pluginList } = this.props;
```
Comment (tyxla) [inline client/me/purchases/manage-purchase/plan-details/index.jsx]: Let's move this line to the top of the method, this way we won't have to use `this.props.selectedSite` and will use just `selectedSite` instead.

File: client/me/purchases/manage-purchase/index.jsx [hunk 7]
```diff
@@ -681,6 +685,13 @@ const ManagePurchase = React.createClass( {
 					{ contactSupportToRenewMessage }
 				</Card>
 
+				<PurchasePlanDetails
```
Comment (tyxla) [inline client/me/purchases/manage-purchase/index.jsx]: Can we completely avoid rendering this one if we know it's not a Jetpack site? `isJetpackSite` could come in handy.

File: client/me/purchases/manage-purchase/plan-details/index.jsx [hunk 8]
```diff
@@ -0,0 +1,61 @@
...
+
+/**
+ * Internal Dependencies
+ */
+import Card from 'components/card';
+import ClipboardButtonInput from 'components/clipboard-button-input';
+import FormFieldset from 'components/forms/form-fieldset';
+import FormLabel from 'components/forms/form-label';
+import QueryPluginKeys from 'components/data/query-plugin-keys';
+import { getPurchase, isDataLoading } from '../../utils';
```
Comment (tyxla) [inline client/me/purchases/manage-purchase/plan-details/index.jsx]: I'd avoid relative paths at all costs, especially such with 2 directories above - they often break as we move files here and there. And `client/me/purchases/utils` isn't that long anyway 😉

**Comment by ryelle** [comment]
Thanks @tyxla, I've addressed some of what you've said. The rest isn't really applicable because this is just a first-pass of adding these fields, the design will be updated in a following PR, along with some other fields that are used on a wp.com site (see #12746)

**Comment by rickybanister** [comment]
It's a little hard to do a 'design review' of this since there's a bit of an order of operations problem with merging the other PRs to get the new design in place. 

Can we just put a feature flag on this card until the other PRs can be merged?

**Comment by ryelle** [comment]
@rickybanister I've added a feature flag so this should only show up in development & wpcalypso. Are you OK with me merging this as-is?

**Comment by rickybanister** [comment]
Yup, in that case let's merge so we can get everything starting to come together.
