### PR TITLE
Post-checkout: Fix PlanThankYouCard error when site not available

### LINKED ISSUE #7874: DevDocs: Plan Thank You Card fails to load on first attempt
#### Steps to reproduce
1. Open https://wpcalypso.wordpress.com/devdocs on a fresh browser
2. Click the Blocks link on the sidebar
3. Watch the JS console

#### What I expected
The blocks page to load

#### What happened instead
The page loads blank on the first attempt, spamming the following errors into the console.  Refreshing the page then works fine.

```js
devdocs.588dcf2….min.js:14 Uncaught TypeError: Cannot read property 'URL' of null
build-wpcalypso.63c078a….min.js:7 Uncaught TypeError: Cannot read property '__reactInternalInstance$m7amfkjwt84fb311hw0dd9529' of null
getClosestInstanceFromNode @ build-wpcalypso.63c078a….min.js:7
findParent @ build-wpcalypso.63c078a….min.js:84
handleTopLevelImpl @ build-wpcalypso.63c078a….min.js:84
perform @ build-wpcalypso.63c078a….min.js:
18batchedUpdates @ build-wpcalypso.63c078a….min.js:49
batchedUpdates @ build-wpcalypso.63c078a….min.js:10
dispatchEvent @ build-wpcalypso.63c078a….min.js:84
```

cc: @marekhrabe, this error first started after the Plan Thank You Card component was first introduced in https://github.com/Automattic/wp-calypso/pull/7606

#### Browser / OS version
OSX / Linux Chrome

#### Screenshot / Video
wp-calypso-plan-thankyou-crash

#### Context / Source
#automated-testing

### PR DESCRIPTION
**Pull request by marekhrabe**
After this change, the block doesn't expect the site object to be preloaded. It also adds a placeholder state to the CTA button, before we have the URL fetched. 

Fixes #7874 

Test live: https://calypso.live/?branch=fix/plan-thank-you-card-devdocs

### CODE REVIEW

**Comment by hoverduck** [comment]
LGTM - Thanks for the quick fix

**Comment by marekhrabe** [comment]
This still needs to get a code review. @hoverduck was testing just the functionality

File: client/blocks/plan-thank-you-card/docs/example.jsx [hunk 1]
```diff
@@ -24,7 +24,11 @@ function PlanThankYouCardExample( { primarySiteId } ) {
 }
 
 const ConnectedPlanThankYouCard = connect( ( state ) => {
-	const primarySiteId = get( getCurrentUser( state ), 'primary_blog' );
```
Comment (ehg) [inline client/blocks/plan-thank-you-card/docs/example.jsx]: Adding a `false` as third argument to `get()` should work here. I don't believe it's any less confusing than setting `primarySiteId` to `-1`

**Comment by hoverduck** [comment]
@marekhrabe can we get this merged?  I'd like to pull out the page refresh workaround from the visual diff tests

File: client/blocks/plan-thank-you-card/docs/example.jsx (hunk 1 above)
Comment (gwwar) [inline client/blocks/plan-thank-you-card/docs/example.jsx]: I agree with adding the default arg, and removing the if block below.

I would suggest `null` or `-1` over `false` as the default since I would not expect a boolean value from the variable name.
```javascript
const primarySiteId = get( getCurrentUser( state ), 'primary_blog', null );
```

File: client/blocks/plan-thank-you-card/style.scss [hunk 2]
```diff
@@ -53,6 +53,15 @@
 	border-width: 1px 1px 2px;
 }
 
+.plan-thank-you-card__button.is-placeholder,
+.plan-thank-you-card__button.is-placeholder:visited {
+	@include placeholder();
+	pointer-events: none;
```
Comment (gwwar) [inline client/blocks/plan-thank-you-card/style.scss]: Why do we need to turn off pointer events? Did we want something to be clickable underneath?

**Comment by gwwar** [comment]
I left a few notes, but there's nothing blocking here.
