### PR TITLE
Correct spelling and capitalization of Media Library

### LINKED ISSUE #39981: Media Library: Welcome Message Typo
When a new user visits their Media Library in Calypso, a popup window appears, welcoming them to the Media Library.  However, the welcome message contains a typo, as it reads "Welcome to your media libary!"

This seems to be the affected file:

https://github.com/Automattic/wp-calypso/blob/f2c9d99b07e14ea938829e9b2e5b31b6fb388a90/client/layout/guided-tours/tours/media-basics-tour/index.js#L39

#### Steps to reproduce
1. Sign up for a new WordPress.com account and create a new site
2. Visit Site > Media in Calypso
3. Wait for the welcome popup to appear

#### What I expected

Welcome message to be "Welcome to your media library!"

#### What happened instead

"Welcome to your media libary!"

### PR DESCRIPTION
**Pull request by kriskarkoski**
Library was originally misspelled as libary and media library was not capitalized

I do not have local Calypso development environment so was not able to follow https://github.com/Automattic/wp-calypso/blob/master/docs/merge-checklist.md but I do not believe it should be necessary for this small of a change.

#### Changes proposed in this Pull Request

* Fixed spelling and capitalization of Media Library in Guided Tours

#### Testing instructions

* Trigger the Guided Tour on the Media Library as shown in the screenshots on #39981 and see the correct spelling and capitalization of Media Library

Fixes #39981

### CODE REVIEW

**Comment by blowery** [comment]
@kriskarkoski nice work, thanks! I added the `string freeze` label to try and get translations for this as quickly as possible.

File: client/layout/guided-tours/tours/media-basics-tour/index.js [hunk 1]
```diff
@@ -61,7 +61,7 @@ export const MediaBasicsTour = makeTour(
 				<Fragment>
 					<p>
 						{ translate(
-							'You can also drag-and-drop image and video files from your computer into your media library.'
+							'You can also drag-and-drop image and video files from your computer into your Media Library.'
```
Comment (a8ci18n) [inline client/layout/guided-tours/tours/media-basics-tour/index.js]: :ok: This change will be queued for retranslation. We'll use the existing translations in the meantime.

**Comment by lancewillett** [comment]
Nice first pull request, @kriskarkoski 👍 

_Welcome to WordPress.com development!_

**Comment by blowery** [comment]
@kriskarkoski to be clear too, you don't _have_ to wait on translations here, I was only adding the label to get them queued up before landing on master. We fall back to the old translations while we're waiting on the new ones, and that's perfect for this case.

**Comment by tyxla** [comment]
Thank you for the fix @kriskarkoski 🙌

**Comment by kriskarkoski** [comment]
Thanks for merging @lancewillett and for the clarification @blowery. I was being extra cautious since I haven't been in here much to date :)
