### PR TITLE
move legend outside of heading container

### LINKED ISSUE #91632: Visual bug: Paid Subscriber Stats
### Quick summary

Related to https://github.com/Automattic/wp-calypso/pull/91585

### Steps to reproduce

1. Visit a WordPress.com site > Stats > Subscribers
2. Mouse over the chart to choose a date.
3. The `subscribers-section-duration-control-with-legend` moves horizontally

https://github.com/Automattic/wp-calypso/assets/25607244/66daa247-30d4-436f-83b4-16e8b0cb68d9

### What you expected to happen

The `subscribers-section-duration-control-with-legend` shouldn't move.

### What actually happened

Something is wrong with the `subscribers-section-duration-control-with-legend` alignment or paddings, so it moves when it has data.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by annacmc**
Related to https://github.com/Automattic/wp-calypso/issues/91632

## Proposed Changes

* Moves the Subscriber Stats chart legend out of the heading container in order to fix visual bug causing other elements to jump. 

## Why are these changes being made?

* see comment https://github.com/Automattic/wp-calypso/issues/91632#issuecomment-2401381766

## Testing Instructions

* open calypso live branch for a site with at least one paid subscriber and one free one
* if you need a su-user to test with ping me (annacmc) 
* navigate to `/stats/subscribers/{site URL}`
* hover over different elements of the chart and off the chart to load different data quantities into the chart legend
* confirm this doesn't make any other elements on the header or page jump or shift
* test on different sized displays, mobile, alternative browsers etc. 

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/my-sites/stats/stats-subscribers-chart-section/index.tsx [hunk 1]
```diff
@@ -160,10 +160,10 @@ export default function SubscribersChartSection( {
 						<StatsPeriodHeader>
 							<Intervals selected={ period } pathTemplate={ pathTemplate } compact />
 						</StatsPeriodHeader>
-						<div className="subscribers-section-legend" ref={ legendRef }></div>
 					</div>
 				</div>
 			</div>
+			<div className="subscribers-section-legend" ref={ legendRef }></div>
```
Comment (dognose24) [inline client/my-sites/stats/stats-subscribers-chart-section/index.tsx]: Could we move this line to be wrapped with `<UplotChart />` below, as their structure would be more meaningful to stay together? From doing that, this section would only appear when the chart is loaded and has data.

**Review by dognose24 — APPROVED** [review]
LGTM! 👍🏼 One nitty suggestion that is not a blocker.
