### PR TITLE
Jetpack Backup: Fix Atomic post-transfer experience

### LINKED ISSUE #50687: Backups: Jetpack connection has failed
When a site is taken from Simple to Atomic by clicking the Jetpack > Backup button, until the first backup is available, the user sees the message "Jetpack connection has failed". 
Markup on 2021-03-03 at 14:09:23

### Steps to reproduce the behavior

1. Create a Simple Site with the Business plan
2. Go to Jetpack > Backup and click the **Activate Jetpack Backup now** button. 
3. Navigate away from the page after the message **Your first backup will be ready soon** appears.
4. Navigate back to Jetpack > Backup.
5. You will see the error **Jetpack connection has failed.**
6. Clicking on the **Reconnect Jetpack** button brings the user to the General Settings page but with the URL - `https://wordpress.com/settings/disconnect-site/siteaddress?type=down`

Markup on 2021-03-03 at 14:12:47

#### What I expected to happen
While no backup is ready, I would expect the message to continue to say "Your first backup will be ready soon".

#### What actually happened
Jetpack is still connected to the site.  It looks like the issue is that no live backups are on file yet.  Once a full backup is ready, the normal backup screen begins to show. 

#### Temporary Workaround
I have been able to resolve this issue by queuing a full backup and then triggering a full Jetpack sync. 

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
This appears to be affecting all users that go Atomic through activating a backup.

#### Video

https://user-images.githubusercontent.com/24914028/109756832-fc1b0800-7c2b-11eb-8da9-546a4e91f48d.mov

### PR DESCRIPTION
**Pull request by mmtr**
Fixes https://github.com/Automattic/wp-calypso/issues/50687
Requires D163334-code

## Proposed Changes

When a Simple site becomes Atomic, there is a brief period of time where the site endpoint can return data indicating that all capabilities are disabled, presumably because there is a provisioning still running.

This was causing a broken experience after the Atomic transfer initiated in Jetpack > Backup, because users suddenly were not authorized to see the page.

To mitigate that scenario, we now wait for the site endpoint to return accurate capabilities before updating the Redux state.

Before | After
--- | ---
Screenshot 2024-10-07 at 14 53 54 | Screenshot 2024-10-08 at 12 09 30

## Why are these changes being made?

Because the Atomic post-transfer experience in the Jetpack > Backup screen was broken

## Testing Instructions

- Apply D163334-code to your sandbox
- Sandbox the API
- Use the Calypso live link below
- Go to `/start`
- Create a new site and pick the Business plan
- Once the site is created, go to Jetpack > Backup
- Click on the "Activate Jetpack VaultPress Backup" button
- Wait for the Atomic transfer to be completed
- Make sure the latest backup loads successfully

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/state/sites/actions.js [hunk 1]
```diff
@@ -158,7 +158,22 @@ export function requestSite( siteFragment ) {
...
+					const isAtomic = site?.options?.is_wpcom_atomic;
+					const wasAdmin = state?.currentUser?.capabilities?.[ siteFragment ]?.manage_options;
+					const isAdmin = site?.capabilities?.manage_options;
+
+					/*
+					 * Capabilities are not immediately propagated to the Atomic site
+					 * after transfer, so let's hold off updating the state until the
+					 * endpoint returns accurate data.
+					 */
+					if ( ! wasAtomic && isAtomic && wasAdmin && ! isAdmin ) {
```
Comment (xavier-lc) [inline client/state/sites/actions.js]: I understand that the `wasAdmin && ! isAdmin` bit is to check if the capabilites are outdated? If so, we could rename it to `areCapabilitesOutdated` or something along the lines.

**Review by xavier-lc — APPROVED** [review]
Works as described

File: client/state/sites/actions.js (hunk 1 above)
Comment (mmtr) [reply client/state/sites/actions.js]: https://github.com/Automattic/wp-calypso/pull/95220/commits/84442b34bbcffeb19254d4665c52dc73a73ba65e
