### PR TITLE
UrlPreview: Fix support of Jetpack sites in subdirectories, take 2

### LINKED ISSUE #13913: Dashboard:  Site Preview button does not load site if custom domain is used
Noted this while helping a few site owners today.  If a site is using a custom domain, when clicking the Site Preview button in the dashboard, no preview of the site is loaded, just a constantly spinning load icon.

Gif:  
nopreview

Note: preview seems to work fine if the site is using the default sitename.wordpress.com URL as primary, so only seems to affect sites with a custom domain (mapped or registered at WordPress.com) set to the primary address.

Also tested to see if site visibility is a factor, but preview will not load for either public or private sites.

### PR DESCRIPTION
**Pull request by tyxla**
Yesterday I fixed a bug with previewing Jetpack sites that are installed in subdirectories in #13805, but by doing so, I removed the https forcing that we were doing. This basically broke the preview for all sites that were mapped as http but support https as well. This PR reverts #13805 while taking care of the Jetpack subdirectory issue in an alternative way. FIxes #13913.

To test:
* Click on the "Site Preview" in the sidebar and verify it loads correctly for:
  * WP.com Site that is mapped with HTTP, but supports HTTPS and is previewable.
  * WP.com Site that is mapped with HTTPS and supports it
  * WP.com site with the default *.wordpress.com domain.
  * A Jetpack site, installed in the root.
  * A Jetpack site, installed in a subdirectory.
  * A Jetpack multisite, main site
  * A Jetpack multisite, subsite

cc @jerrysarcastic who caught and reported the issue in #13913

### CODE REVIEW

File: client/blocks/url-preview/index.jsx [hunk 1]
```diff
@@ -97,11 +97,12 @@ export default function urlPreview( WebPreview ) {
 
 	function mapStateToProps( state ) {
 		const selectedSiteId = getSelectedSiteId( state );
-		const selectedSite = getSelectedSite( state );
+		const siteUrl = 'https://' + getSiteSlug( state, selectedSiteId );
```
Comment (seear) [inline client/blocks/url-preview/index.jsx]: Maybe we should add a comment like:
`// Force https to prevent mixed content errors in the iframe`

Comment (tyxla) [inline client/blocks/url-preview/index.jsx]: :+1: done in f248980738e01552c1da9109f2c578cb5e550e88.
