### PR TITLE
Blogger Experience - Fix video UI course loading and Tracks errors

### LINKED ISSUE #57622: Videos UI: Tracks view events are firing too much.
Tracks view events are (I think) firing on every re-render of the `<VideosUi />` component, including on every video selection (now in #57618).

Screen Shot 2021-11-03 at 2 38 59 PM

### PR DESCRIPTION
**Pull request by blackjackkent**
This PR addresses multiple `calypso_courses_view` Tracks events firing on a single load.

It also addresses an error which was preventing tracks events for the videos UI play button to run correctly:

image

Fixes #57622.

#### Testing instructions
* Verify that the component loads correctly, that clicking on "Play" buttons does not log a console error, and that Tracks events are properly catalogued 
* Enter `localStorage.setItem( 'debug', 'calypso:analytics*' )` in your console to see live Tracks events.

### CODE REVIEW

File: client/components/videos-ui/index.jsx [hunk 1]
```diff
@@ -15,7 +15,7 @@ const VideosUi = ( { shouldDisplayTopLinks = false } ) => {
 	const onVideoPlayClick = ( video ) => {
 		recordTracksEvent( 'calypso_courses_play_click', {
 			course: course.slug,
-			video,
+			video: video.title,
```
Comment (kwight) [inline client/components/videos-ui/index.jsx]: We've had this data before, it's fallen through the cracks somewhere: https://github.com/Automattic/wp-calypso/pull/57580/files#diff-51922af659b0340039db737b7ddc17e9edbd076ae43d125f37b91cd4d8454a73R88

We want to be recording slugs, not strings, they're just easier to work with on the Tracks side.

**Review by kwight — APPROVED** [review]
Great!
