### PR TITLE
Fix for Jetpack SSO 3rd party cookie blocking issue with gutenframe

### LINKED ISSUE #33142: Gutenberg Editor: WordPress.com Editor Fails to Load in Safari 12.1.x [1]
#### Steps to reproduce

1. Starting in the WordPress.com dashboard, click on Site > Posts > Add New Post
2. The WordPress.com Editor fails to load when using Safari 12.1.x

#### What I expected

The WordPress.com Editor would open in Safari as with other browsers. I tried disabling cross-site tracking protection, [here](https://cld.wthms.co/FAgWAk):

_Screenshot direct link:_ https://cld.wthms.co/FAgWAk

This didn't affect the result.

#### What happened instead

The block editor failed to load at all. Instead, I saw a blank screen, [like this](https://cld.wthms.co/gFJpsN):

Screenshot direct link: https://cld.wthms.co/gFJpsN

#### Browser / OS version

Safari 12.1 running on macOS 10.14.4. A user who reported this issue is using Safari 12.1.1. Same result.

#### Context / Source

This is based on a report from a user in 2038016-zen.

### PR DESCRIPTION
**Pull request by glendaviesnz**
#### Changes proposed in this Pull Request

Some browsers can prevent the cookies to be stored if they are coming from a different domain than the one we're currently visiting. This was causing issues to AT sites with a custom domain when using Gutenframe.

This PR seeks to solve that by performing a redirection to the custom domain, so the authentication cookies can be stored and then we redirect back to Calypso.

#### Testing instructions

* Make sure you have an AT test site using a custom domain.
* Make sure that the "Prevent cross-site tracking" option is enabled in the Safari privacy settings:
Screen Shot 2019-08-02 at 12 10 35

* Make sure there are no cookies saved for the custom domain of your AT test site:
Screen Shot 2019-08-02 at 12 13 18
Screen Shot 2019-08-02 at 12 13 55

* Start Calypso running on master.
* In Safari, go to `calypso.localhost:3000/block-editor/post` and select your AT test site.
  * If you're asked to enter your credentials, go first to `wordpress.com/login` and enter your credentials there, so the `wordpress.com` auth cookies can be stored and read by `calypso.localhost`.
* The editor should hang on the loading screen.
* Switch to this branch and reload `calypso.localhost:3000/block-editor/post`.
* You should notice the URL redirect to your custom domain to authenticate, and then redirect back to Calypso. This redirect should only happen once per browser session.
 
Fixes #33142.

### CODE REVIEW

**Comment by glendaviesnz** [comment]
After a lot of going around in circles looking for solutions to this it seems like the only way to do it without making changes to the core  /wp-admin/post.php page (to detect if cookies can be set and if not break out of the iFrame) is to redirect from calypsoify on each load where it is detected that the iFrame domain is different from the parent.

Another option would be for calypsoify to call a custom page first to determine if 3rd party cookies can be set and if not break out of the frame and do the redirect - this would prevent the need to redirect on every editor load, and instead just do it when needed - but I am picking it would be hard to guarantee the existence of this custom page in JetPack sites.

File: client/gutenberg/editor/calypsoify-iframe.tsx [hunk 1]
```diff
@@ -116,6 +116,29 @@ class CalypsoifyIframe extends Component< Props & ConnectedProps & ProtectedForm
...
+			.replace( 'https://', '' )
+			.split( /[/?#]/ )[ 0 ];
+
+		// get the query params from parent frame to check if we have already redirected back from 3rd party auth
+		const urlParams = new URLSearchParams( window.location.search );
+
+		// if editor iFrame is a different domain then redirect to that domain to auth
+		// and redirect back here with 3rdPartyAuthed param set
+		if (
+			iFrameDomain.indexOf( window.location.hostname ) === -1 &&
```
[the remark this answers is not in the document]
Comment (mmtr) [reply client/gutenberg/editor/calypsoify-iframe.tsx]: Maybe this is what's causing the e2e tests to fail: https://circleci.com/gh/Automattic/wp-calypso/373423 (I believe they are tested against `calypso.live`).

**Comment by mmtr** [comment]
We should also avoid the redirection to `:site/wp-login.php` if Calypso is running on the desktop app. The desktop app only opens wordpress.com URLs within the app, so any other URL like `:site/wp-login.php` will be opened in the browser, breaking the auth flow.

**Comment by mmtr** [comment]
Note that we can always redirect to the WP Admin editor instead of using Gutenframe. I wouldn't discard that if this redirect to /wp-login approach ends up requiring too many complex workarounds.

**Comment by gwwar** [comment]
Nice work so far @glendaviesnz 

Have we tried to see if checking this on the server makes more sense? So if I'm thinking correctly, when we try and load WordPress.com/block-editor with a site slug set, we also check for potential auth/xdomain issues (not a Simple site on a .wordpress.com subdomain) + no cookie set. (This info should be easy to fetch from the site).

We can then have the server redirect without doing this on the client.

File: client/gutenberg/editor/calypsoify-iframe.tsx [hunk 2]
```diff
@@ -116,6 +116,29 @@ class CalypsoifyIframe extends Component< Props & ConnectedProps & ProtectedForm
 	componentDidMount() {
 		MediaStore.on( 'change', this.updateImageBlocks );
 		window.addEventListener( 'message', this.onMessage, false );
+
+		// get the domain of the iframed editor so we can check if it is different to parent frame
+		// if so we want to redirect to that domain to set auth cookie to prevent 3rd party cookie
+		// blocking by browser security
+		const iFrameDomain = this.props.iframeUrl
```
[the remark this answers is not in the document]
Comment (glendaviesnz) [reply client/gutenberg/editor/calypsoify-iframe.tsx]: nice - hadn't noticed that url import, much cleaner way to get the host!

File: client/gutenberg/editor/calypsoify-iframe.tsx [hunk 3]
```diff
@@ -116,6 +116,29 @@ class CalypsoifyIframe extends Component< Props & ConnectedProps & ProtectedForm
...
+			.toString()
+			.replace( 'http://', '' )
+			.replace( 'https://', '' )
+			.split( /[/?#]/ )[ 0 ];
+
+		// get the query params from parent frame to check if we have already redirected back from 3rd party auth
+		const urlParams = new URLSearchParams( window.location.search );
```
[the remark this answers is not in the document]
Comment (glendaviesnz) [reply client/gutenberg/editor/calypsoify-iframe.tsx]: this works nicely as well, just had to add a second 'true' param to url.parse to get query params as an object instead of a string

**Comment by glendaviesnz** [comment]
> We should also avoid the redirection to `:site/wp-login.php` if Calypso is running on the desktop

Is there an easy way to detect if we are in the desktop app?

File: client/gutenberg/editor/calypsoify-iframe.tsx [hunk 4]
```diff
@@ -116,6 +116,29 @@ class CalypsoifyIframe extends Component< Props & ConnectedProps & ProtectedForm
...
+
+		// if editor iFrame is a different domain then redirect to that domain to auth
+		// and redirect back here with 3rdPartyAuthed param set
+		if (
+			iFrameDomain.indexOf( window.location.hostname ) === -1 &&
+			! urlParams.get( '3rdPartyAuthed' )
+		) {
+			const returnURL = encodeURIComponent( `${ window.location.href }?3rdPartyAuthed=true` );
+			( window.location
+				.href as any ) = `https://${ iFrameDomain }/wp-login.php?redirect_to=${ returnURL }`;
```
[the remark this answers is not in the document]
Comment (glendaviesnz) [reply client/gutenberg/editor/calypsoify-iframe.tsx]: good point, have fixed.

File: client/gutenberg/editor/calypsoify-iframe.tsx (hunk 1 above)
[the remark this answers is not in the document]
Comment (glendaviesnz) [reply client/gutenberg/editor/calypsoify-iframe.tsx]: have added a check to only run the redirect if iFrame domain is not in a list of 'firstParty' domains

**Comment by glendaviesnz** [comment]
> However, I noted a weird redirection when opening the block editor a 2nd tim

This was due to a timing issue and window.location not being updated before onComponentDidMount - have fixed by using the curretRoute.prop instead

File: client/gutenberg/editor/calypsoify-iframe.tsx [hunk 5]
```diff
@@ -116,6 +116,29 @@ class CalypsoifyIframe extends Component< Props & ConnectedProps & ProtectedForm
...
+		}
```
[the remark this answers is not in the document]
Comment (glendaviesnz) [reply client/gutenberg/editor/calypsoify-iframe.tsx]: not sure what was going on here - was just a temporary fix to stop IDE complaining, but when I went back to tidy it up today the cast wasn't needed at all!

File: client/gutenberg/editor/calypsoify-iframe.tsx (hunk 4 above)
[the remark this answers is not in the document]
Comment (glendaviesnz) [reply client/gutenberg/editor/calypsoify-iframe.tsx]: done

**Comment by glendaviesnz** [comment]
> Have we tried to see if checking this on the server makes more sense? So if I'm thinking correctly, when we try and load WordPress.com/block-editor with a site slug set,

Just having another look at this now to make sure I have explored both options fully, but at a quick look on Friday it looked like in order to test for 3rd party cookie support you would need to hit custom.domain/wp-admin/post.php and not WordPress.com/block-editor (ie. the only way I can see that you can test third party cookie support is by setting and checking a cookie within an iFramed 3rd party domain), and the lack of authentication at that point means you hit the redirection loop before getting to that file to check cookie support. 

My initial thoughts about handling server side are :  

- We would need a server side file that sits outside normal php flows, eg. wp-admin/check-3rd-party-cookie-support.php. 
- If calypsoify detects third party domain it points iFrame initially to this file
- If this file detects that a cookie exists, or can be set it redirects iFrame to back to custom.domain/wp-admin/post.php
- If this file detects issue with 3rd party cookies it would have to redirect client to a page that had javascript that could break the child frame out of the parent frame, and redirect it to the custom domain for auth, and then back to calypsoify

It looks to me that to handle it server side we would need to add a couple of more complex steps at the start of the process, that still require an initial redirect, and that end at the same point as the client only solution of breaking out of iFrame to auth on custom domain.

Really happy to have some ongoing discussion around this though, as I may be overlooking something simple in terms of detecting 3rd party cookie issues server side.

**Comment by glendaviesnz** [comment]
Have made the solution a bit more robust by only redirecting if the iFrame domain is not in a whitelist of '1st party' domains, and also saving flag to session storage on a successful 3rd party auth redirect so redirect only happens once per session.

Have tested on Simple, Atomic and JetPack sites for adding new and editing existing posts, and seems to work reliably in all these instances - but will do some more testing - let me know if there are any edge cases I need to test.

**Comment by glendaviesnz** [comment]
The latest version of the patch seems to work reasonably reliable, have tried switching between editing in a Simple SIte, Atomic Site and Jetpack in a single Calypso session, adding new pages, editing existing, editing drafts, switching to frontend view after updating and going back, and all seems to work as expected, and e2e tests are also passing again now.

The only issue I have noticed is if when you get the auth redirect on first loading the editor, if you use your browser back button to go back to the page listing instead of back link top left of editor you need to hit it twice to get back to the listing. Will have a look tomorrow to see if we can pull the auth redirect our of history after returning.

File: client/gutenberg/editor/calypsoify-iframe.tsx [hunk 6]
```diff
@@ -116,13 +117,57 @@ class CalypsoifyIframe extends Component< Props & ConnectedProps & ProtectedForm
...
+			hostname: parentDomain,
+			protocol: parentProtocol,
+			port,
+			query: parentQuery,
+		} = url.parse( window.location.href, true );
+		const parentPort = port ? `:${ port }` : '';
+		const firstPartyDomains = [ 'wordpress.com', 'calypso.live', 'calypso.localhost' ];
+		const isThirdPartyDomain = ! some( firstPartyDomains, domain => {
+			return endsWith( iFrameDomain, domain );
+		} );
```
Comment (jsnajdr) [inline client/gutenberg/editor/calypsoify-iframe.tsx]: Let's be careful about this kind of checks. It often causes security issues when done wrong. In this case, anyone can register `evilwordpress.com` and the check will succeed for it.

File: client/gutenberg/editor/calypsoify-iframe.tsx [hunk 7]
```diff
@@ -116,13 +117,57 @@ class CalypsoifyIframe extends Component< Props & ConnectedProps & ProtectedForm
...
+
+		if ( isThirdPartyDomain ) {
```
Comment (jsnajdr) [inline client/gutenberg/editor/calypsoify-iframe.tsx]: Tip for writing readable functions without too many nested indents: return early if some precondition fails:
```js
if ( ! isThirdPartyDomain ) {
  return;
}

if ( parentQuery.thirdParty ) {
  return;
}

if ( setInLocalStorage ) {
  return;
}

// do the main job at level 1 of indentation
window.location.href = ...;
```

File: client/gutenberg/editor/calypsoify-iframe.tsx [hunk 8]
```diff
@@ -116,13 +117,57 @@ class CalypsoifyIframe extends Component< Props & ConnectedProps & ProtectedForm
...
+			// check query params from parent frame to check if we have already redirected back from 3rd party auth.
+			if ( parentQuery.thirdPartyAuthed ) {
+				// If successfully redirected save to session storage so we don't need to redirect on every editor load
+				sessionStorage.setItem( `calypsoify_${ iFrameDomain }_thirdPartyAuthed`, 'true' );
```
Comment (jsnajdr) [inline client/gutenberg/editor/calypsoify-iframe.tsx]: The "third party authed" process is officially called "Jetpack SSO". It would be nice to reflect that in the name (both query param and local storage key).

File: client/gutenberg/editor/calypsoify-iframe.tsx [hunk 9]
```diff
@@ -116,13 +117,57 @@ class CalypsoifyIframe extends Component< Props & ConnectedProps & ProtectedForm
 	componentDidMount() {
 		MediaStore.on( 'change', this.updateImageBlocks );
 		window.addEventListener( 'message', this.onMessage, false );
+
+		this.handleThirdPartyiFrameDomains();
```
Comment (jsnajdr) [inline client/gutenberg/editor/calypsoify-iframe.tsx]: Checking the iframe URL in `componentDidMount` is somewhat late: at that time, the `iframe` is already rendered and its load request is being issued.

It's hard to find a good place for this check (component constructor is much better, but still not ideal). I would personally do it in a page.js handler in `gutenberg/editor/controller`.

**Comment by glendaviesnz** [comment]
> There is some prior art for Jetpack SSO autologin after an Automated Transfer in #11457 (by @artpi). The goal was to prevent a login screen when going to iframed customizer or site preview.
> 
> I'm suprised that it ever worked (if it did)

Thanks for this reference. I gave it a try, and it seems to work in Chrome, but not in Safari unless "Prevent cross-site tracking" is switched off.

**Comment by jsnajdr** [comment]
> Thanks for this reference. I gave it a try, and it seems to work in Chrome, but not in Safari

Do you also have third-party cookie blocking disabled by default in Chrome?
Screenshot 2019-07-29 at 23 23 56

I was surprised to learn that it's not enabled by default.

**Comment by glendaviesnz** [comment]
> Do you also have third-party cookie blocking disabled by default in Chrome?

No, I have it as the default off - I should have clarified in my response that this would be the reason it did work in Chrome.  

I have been looking at this issue from the perspective that it can be turned on in any browser, rather than just focusing on it as the Safari issue that the initial ticket raised. I will be surprised if  Chrome doesn't turn it on by default at some point in the future.

File: client/gutenberg/editor/calypsoify-iframe.tsx [hunk 10]
```diff
@@ -116,13 +117,57 @@ class CalypsoifyIframe extends Component< Props & ConnectedProps & ProtectedForm
...
+				sessionStorage.setItem( `calypsoify_${ iFrameDomain }_thirdPartyAuthed`, 'true' );
+			}
+
+			// if 3rd party iFrame is not authenticated yet then redirect to that domain to auth
+			// and redirect back here with 3rdPartyAuthed param set
+			if ( ! sessionStorage.getItem( `calypsoify_${ iFrameDomain }_thirdPartyAuthed` ) ) {
+				// Add new params to existing in case there are new calypsoify query params added in future that
+				// need to be included in the redirect
+				parentQuery.thirdPartyAuthed = 'true';
+				const queryParams = map( parentQuery, ( value, key ) => `${ key }=${ value }` ).join( '&' );
```
[the remark this answers is not in the document]
Comment (glendaviesnz) [reply client/gutenberg/editor/calypsoify-iframe.tsx]: nice, have switched to use that.

File: client/gutenberg/editor/calypsoify-iframe.tsx (hunk 6 above)
Comment (glendaviesnz) [reply client/gutenberg/editor/calypsoify-iframe.tsx]: Turned out this domain checking was not needed  - just need to check if jetpack = true, so removed now

File: client/gutenberg/editor/calypsoify-iframe.tsx (hunk 7 above)
Comment (glendaviesnz) [reply client/gutenberg/editor/calypsoify-iframe.tsx]: Thanks for the reminder  - done.

File: client/gutenberg/editor/calypsoify-iframe.tsx (hunk 8 above)
Comment (glendaviesnz) [reply client/gutenberg/editor/calypsoify-iframe.tsx]: Thanks for this clarification - I had '3rd party cookie' stuck in my head while investigating - but narrowing it down to jetpack auth made it easier not just for naming but for the logic to decide whether to run this or not

File: client/gutenberg/editor/calypsoify-iframe.tsx (hunk 9 above)
Comment (glendaviesnz) [reply client/gutenberg/editor/calypsoify-iframe.tsx]: have moved to the controller, that did seem like a nice logical home for this.

**Comment by glendaviesnz** [comment]
@jsnajdr  - thanks for the feedback, that has helped to clarify and simplify things I think.

**Comment by josephscott** [comment]
Note that if this is hitting the Safari ITP ( the thing in Safari that strips cookies from 3rd party requests ), you'll never be able to test if the 3rd party cookie is there, because it will always fail.

**Comment by glendaviesnz** [comment]
@mmtr & @kwight A couple of things to note for further testing of this fix based on the feedback from @josephscott & @jsnajdr:

- This fix works because Safari is allowing the 3rd party cookie because we have first party authed the domain before iFraming it, but this is time limited, ie. Safari checks when the last time the domain was 1st party authed, so we probably should add a time limit of less than 24 hours on our session storage flag

- Safari ITP is a state machine and what works once may not always work, ie. Safari can allow things to happen an arbitrary number of times and then clamp down on them - so this fix needs to be tested multiple times in a single browser session

I suspect that we probably need to see this as a temporary solution as Safari could change its 3rd party cookie handling during any release, so probably needs a discussion at some point about whether gutenframe is the best way to handle gutenberg for jetpack sites.

**Comment by kwight** [comment]
> I suspect that we probably need to see this as a temporary solution as Safari could change its 3rd party cookie handling during any release, so probably needs a discussion at some point about whether gutenframe is the best way to handle gutenberg for jetpack sites.

Temporary is better than not working at all 👍

We're down to so few options when it comes to handling JP+Atomic+Gutenberg+WP.com, I'm not sure what anyone could propose otherwise. We've knowingly traded all the other brick walls (running third-party plugins, syncing and maintaining even more codebases/editors, etc) with one big problem of iframes. 🙃

**Comment by gwwar** [comment]
Thanks for digging into this one @glendaviesnz !

> but this is time limited, ie. Safari checks when the last time the domain was 1st party authed, so we probably should add a time limit of less than 24 hours on our session storage flag

Overall I'm okay with an better but imperfect solution 👍 

> I suspect that we probably need to see this as a temporary solution as Safari could change its 3rd party cookie handling during any release, so probably needs a discussion at some point about whether gutenframe is the best way to handle gutenberg for jetpack sites.

If it's bad enough later we could default to redirecting to wp-admin, though folks will lose the ability to use things like the Calypso media modal.


Were folks able to manually test this one? I'm having trouble logging into Calypso from localhost. 🤔If y'all were able to verify flows manually, my note is non-blocking but please ✅the PR in this case.

File: client/gutenberg/editor/controller.js [hunk 11]
```diff
@@ -98,6 +143,7 @@ function getPressThisData( query ) {
 export const post = ( context, next ) => {
 	// See post-editor/controller.js for reference.
 
+	handleJetpackSSO( context );
```
Comment (jsnajdr) [inline client/gutenberg/editor/controller.js]: If `handleJetpackSSO` does a redirect, you don't want to continue handling the route. All the code that follows will just do useless work that will be thrown away on the next event loop tick, when the navigation will be actually performed.

File: client/gutenberg/editor/controller.js [hunk 12]
```diff
@@ -62,6 +65,48 @@ function waitForSiteIdAndSelectedEditor( context ) {
...
+
+	// if site is not authenticated yet then redirect to that domain to auth
+	// and redirect back here with jetpackSSO param set
+	parentQuery.jetpackSSO = 'true';
+	const returnURL = encodeURIComponent(
+		`${ parentProtocol }//${ parentDomain }${ parentPort }${ currentRoute }?${ stringify(
+			parentQuery
+		) }`
+	);
+	window.location.href = `${ selectedSiteUrl }/wp-login.php?redirect_to=${ returnURL }`;
```
Comment (jsnajdr) [inline client/gutenberg/editor/controller.js]: Calling `page.redirect` might be a bit nicer inside a page.js handler. In the end, it will do the same thing for an external URL.

File: client/gutenberg/editor/controller.js [hunk 13]
```diff
@@ -62,6 +65,48 @@ function waitForSiteIdAndSelectedEditor( context ) {
...
+		protocol: parentProtocol,
+		port,
+		query: parentQuery,
+	} = urlLib.parse( window.location.href, true );
+	const parentPort = port ? `:${ port }` : '';
+
+	// check query params from parent frame to check if we have already redirected back from Jetpack auth.
+	if ( parentQuery.jetpackSSO ) {
+		// If successfully redirected save to session storage so we don't need to redirect on every editor load
+		sessionStorage.setItem( `calypsoify_${ selectedSiteDomain }_jetpackSSO`, 'true' );
```
Comment (jsnajdr) [inline client/gutenberg/editor/controller.js]: `sessionStorage` will be cleared after you close the tab. If you open a new tab with the same URL, it will start with a clear session. Do you really want that? Is there a reason why you don't use `localStorage`?

File: client/gutenberg/editor/controller.js [hunk 14]
```diff
@@ -62,6 +65,48 @@ function waitForSiteIdAndSelectedEditor( context ) {
 	} );
 }
 
+function handleJetpackSSO( context ) {
+	// If we are dealing with an Atomic or Jetpack site we need to make sure that Jetpack SSO
+	// has been handled before we load the editor in an iFrame in order to prevent any issues
+	// with 3rd party cookie setting being blocked by the browser
+	const state = context.store.getState();
+	const currentRoute = getCurrentRoute( state );
```
Comment (jsnajdr) [inline client/gutenberg/editor/controller.js]: Inside a page.js handler, it's better to use page.js API instead of reading from Redux. The current route is in `context.pathname`.

**Comment by jsnajdr** [comment]
> Note that if this is hitting the Safari ITP ( the thing in Safari that strips cookies from 3rd party requests ), you'll never be able to test if the 3rd party cookie is there, because it will always fail.

@josephscott @glendaviesnz My understanding of the Safari ITP and Gutenframe story is as follows:
- redirecting from Calypso to Jetpack SSO and back will set first-party auth cookies for `example.blog` (the Jetpack/Atomic site), because we visited `example.blog` as first-party site during the redirect dance
- but the embedded `example.blog` Gutenframe generally won't see the cookies, because the cookie storage is partitioned: "`example.blog` as 1st party" and "`example.blog` iframed in `wordpress.com`" are two different storage areas
- Safari will let the iframe see the first-party cookies if the user visited `example.blog` in the [last 24 hours](https://webkit.org/blog/8124/introducing-storage-access-api/), otherwise it won't
- Firefox implements a similar policy with slightly different rules, [documented on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API).
- if the first-party cookies aren't accessible automatically, the iframe script can still request them by calling `document.requestStorageAccess()`. This will show a browser permissions dialog that the user can approve (or not). The `requestStorageAccess` call must be initiated by a user action, e.g., by clicking on a button. Just calling it from a script won't work. (similar to file uploads policy)

Could `document.requestStorageAccess()` be a usable fallback for Gutenframe? @josephscott do we still use it anywhere in the (async) remote login code? There used to be a button on WP.com site frontends for a while and then quickly removed. I don't know how it evolved further.

**Comment by josephscott** [comment]
> @josephscott @glendaviesnz My understanding of the Safari ITP and Gutenframe story is as follows:

I haven't followed the evolution of Gutenframe, but I can comment on Safari ITP.

ITP has gone through several iterations ( see https://webkit.org/blog/category/privacy/ ).  The 24-hour grace period that you mentioned was from a post in Feb 2018.  An update, ITP 2.0, in Jun 2018 removed that:

> ITP 2.0, as opposed to earlier versions, immediately partitions cookies for domains determined to have tracking abilities. The previous general cookie access window of 24 hours after user interaction has been removed. Instead, authenticated embeds can get access to their first-party cookies through the Storage Access API. The API requires that the user interacts with the embedded content.

You are correct about `document.requestStorageAccess()`, that is the mechanism that you can use to request the user to grant tracking abilities.  I did deploy that as a solution for async remote login on WordPress.com, but it was removed because the user experience was very poor.

For this case, the user experience might not be as bad ( though still perhaps not super great ) because you would only be showing it to people you know would need to be logged in.

**Comment by mmtr** [comment]
> Were folks able to manually test this one? I'm having trouble logging into Calypso from localhost. 🤔If y'all were able to verify flows manually, my note is non-blocking but please ✅the PR in this case.

You need to authenticate through `wordpress.com/login`, so the `wordpress.com` auth cookies are stored and `calypso.localhost` can read them. I updated the testing instructions to better reflect this.

File: client/gutenberg/editor/controller.js (hunk 13 above)
Comment (mmtr) [reply client/gutenberg/editor/controller.js]: I think we need to stick with `sessionStorage` since we don't have any control over the 3rd-party cookies created by the custom domain when the current session finishes (i.e. the user could remove them after closing `wordpress.com/block-editor`).

Is there any other way to ensure that those cookies are always created before loading the editor?

File: client/gutenberg/editor/controller.js (hunk 12 above)
Comment (mmtr) [reply client/gutenberg/editor/controller.js]: I ended up using `window.location.replace` because `page.redirect` was triggering this error:

Screen Shot 2019-08-02 at 14 40 56

File: client/gutenberg/editor/controller.js (hunk 11 above)
Comment (mmtr) [reply client/gutenberg/editor/controller.js]: Moved this function to an independent `page` controller in 136a57d3a6c74ae86bdbaa9e2f87ba4f8ff24149. The new controller won't execute the next callback registered in the route unless the WP Admin request is already authenticated.

File: client/gutenberg/editor/controller.js (hunk 14 above)
Comment (mmtr) [reply client/gutenberg/editor/controller.js]: With the refactor done in 136a57d3a6c74ae86bdbaa9e2f87ba4f8ff24149 we don't the current route anymore.

**Comment by mmtr** [comment]
I refactored a little bit the code on my last commit, but it's still implementing the same idea first implemented by @glendaviesnz (great work there!).

If I'm interpreting correctly how ITP 2.2 works (https://webkit.org/blog/8828/intelligent-tracking-prevention-2-2/), with the current approach we would have access for the 3rd-party cookie during 24h:
> ### Exactly When Should I Expect Cookies to Expire?
> Here’s an example of when ITP 2.2 will cap cookie persistence to one day:
> 1. The website social.example has been classified by ITP as having cross-site tracking capabilities. How this classification works is explained in detail in the original ITP blog post and the ITP 2.0 blog post.
> 1. The user clicks a link on social.example.
> 1. The click results in a cross-site navigation that lands on shop.example and the landing URL has a query string and/or a fragment identifier.
> 1. The shop.example webpage sets a persistent cookie through document.cookie. **This cookie will now have a maximum expiry of one day.**

Since we're redirecting users to WP Admin on every browser session (we use `localStorage` for avoiding redirects on every editor load), that might be enough if we assume that most of the user sessions will last less than a day.

If folks like this approach and can verify this improves the behavior for AT sites, I'd suggest to land this. We can always circle back if we notice more edge cases.

**Comment by mmtr** [comment]
Thanks for the review @jsnajdr! I'll land this next week in order to avoid a deploy before the weekend 🙂

**Comment by jsnajdr** [comment]
> I'll land this next week in order to avoid a deploy before the weekend

Good idea especially for this one 🙂 Thank you for a great collaboration.

**Comment by glendaviesnz** [comment]
Thanks for following up in this @mmtr, this approach tidies it up nicely 👍 

I just gave it a quick try locally and noticed the following in Safari:

The fist time I select a post I see a briefly the post list without the left navigation and top bar, and then get redirected back to the post list:

wrong-redirect

If I select the post again I get redirected correctly this time and the session storage is set, but I still briefly see the post list again without left navigation before going to the editor:

flash-of-post-list

In Chrome I don't get the incorrect redirect back to the post list on the first try, but still see the post list without navigation and top bar before going to the editor.

**Comment by glendaviesnz** [comment]
> The fist time I select a post I see a briefly the post list without the left navigation and top bar, and then get redirected back to the post list:

I suspect that the incorrect redirect is caused by a race condition that I experienced in one of my initial versions of this patch. I was able to reliably reproduce this on my home network, but can't reproduce now on a co-working space network.

If using `window.location.href` to generate the returnUrl there seems to be some instances where the browser hasn't updated this from the previous route before it is captured by our redirect script. The only way I could find to reliably avoid this in the earlier patch was to not rely on `window.location.href` for the redirect url, but to generate it manually from the relevant parts as in:

https://github.com/Automattic/wp-calypso/pull/34902/commits/1e0e2d723f86706bbb1a39aade6ef5436301ed24#diff-f319ed205677209241d77fdb7197d1a3R104

@jsnajdr suggested using `context.pathname` instead of `getCurrentRoute( state )` to get the path.

**Comment by glendaviesnz** [comment]
> The fist time I select a post I see a briefly the post list without the left navigation and top bar, and then get redirected back to the post list:

I suspect that this incorrect redirect was caused by the same race condition that I experienced in one of the initial versions of this patch (@mmtr from memory I think it was you that reported this when testing the earlier patch that you sometimes redirected back to the post list instead of the editor). I was able to reliably reproduce this problem at home this morning, but couldn't reproduce again at co-working space during the day, and now can't replicate at home again - so anyone's guess why it happened reliably this morning!

It seems that if using `window.location.href` to generate the returnUrl there are some circumstances where the browser hasn't updated this from the previous route before it is captured by the auth redirect script. Previously the only way I could find to avoid this was to not rely on `window.location.href` for the redirect url, but to generate it manually from the relevant parts as in:

https://github.com/Automattic/wp-calypso/pull/34902/commits/1e0e2d723f86706bbb1a39aade6ef5436301ed24#diff-f319ed205677209241d77fdb7197d1a3R104

Will leave it to you to decide if my issues this morning were a temporary glitch - or whether there is a potential race condition that could reoccur in production that we should account for :-)

**Comment by mmtr** [comment]
Thanks for the review @glendaviesnz! My last commits should handle both the posts list rendering glitch and the potential race condition when generating the return URL.

File: client/gutenberg/editor/controller.js [hunk 15]
```diff
@@ -62,6 +66,59 @@ function waitForSiteIdAndSelectedEditor( context ) {
...
+		return next();
+	}
+
+	// Shows the editor placeholder while doing the redirection.
+	context.primary = <Placeholder />;
+	makeLayout( context, noop );
+	render( context );
+
+	// We could use `window.location.href` to generate the return URL but there are some potential race conditions that
+	// can cause the browser to don't update it before redirecting to WP Admin. To avoid that, we manually generate the
```
Comment (glendaviesnz) [inline client/gutenberg/editor/controller.js]: very minor, not a blocker `to don't update it` should be `to not update it`

**Comment by glendaviesnz** [comment]
LGTM - tests well on Safari and Chrome
