### PR TITLE
Advanced SEO: Fix polyfill loading for draft-js

### LINKED ISSUE #8052: Advanced SEO: JS Error in IE 11
Looks like IE 11 is still struggling to load the title format editor, even with the polyfills we added:

`Object doesn't support property or method 'startsWith'`

### PR DESCRIPTION
**Pull request by vindl**
Closes #8052

The draft-js polyfills were created after draft-js was loaded,
resulting in errors on IE 11. Since `parser.js` imports `draft-js` too,
we need to load it after the polyfills are created.

### CODE REVIEW

**Comment by vindl** [comment]
cc @dan @dmsnell

**Comment by vindl** [comment]
cc @roundhill @dmsnell

File: client/boot/index.js [hunk 1]
```diff
@@ -1,5 +1,9 @@
 // Initialize localStorage polyfill before any dependencies are loaded
 require( 'lib/local-storage' )();
+
+// Initialize draft-js polyfill needed for SEO title format editor
+require( 'lib/draft-js-polyfill' )();
```
Comment (mtias) [inline client/boot/index.js]: We shouldn't be loading a very specific polyfill like this that affects all of calypso.

Comment (mtias) [inline client/boot/index.js]: To expand a bit, is the reason for the issue here that draft-js is being loaded in a chunk different than the one SEO lives at? If so, could we look at making it part of the same bundle and load the polyfill only at the start of that chunk?

The main issue is that loading at the start of boot doesn't take into account that most sections of Calypso don't need to run draft-js at the moment.

Comment (vindl) [inline client/boot/index.js]: @mtias From what I've gathered, the draft-js is already part of the same chunk as SEO. Furthermore, the polyfill was already placed at the start of that chunk. It seems like the issue was caused by importing `parser.js`, that in turn imported `draft-js`, before the polyfills were defined.

> The main issue is that loading at the start of boot doesn't take into account that most sections of Calypso don't need to run draft-js at the moment.

I agree, that was my concern with original approach too. I have completely revamped the previous solution in order to remove those polyfills from boot.

**Comment by dmsnell** [comment]
@vindl it was right under our nose! thanks for finding and fixing this!

:shipit:

**Comment by mtias** [comment]
@vindl nice, thanks for finding the issue and making a better solution :)
