### PR TITLE
UI Cleanup: GitHub Deployments

### LINKED ISSUE #95903: GitHub Deployments UI Cleanup
### Quick summary

During a feature walkthrough, we noticed a few UI issues that should be addressed:
* Ensure all buttons have proper style applied (they should not have different border radius from that of the "WP Admin" button). Here are some examples of the buttons that require cleanup, there may be more.

|Connect|Connect repository|Disconnect repository|
|--------|-------------------|-----------------------|
|Image|Image|Image|

* We should use the same search UI for consistency. Currently the search box for sites and repositories look different.

* Disconnect repository confirmation modal style is off:
    * Inconsistent margins
    * Is the "Disconnect repository" button red-worthy?

### Steps to reproduce

1. Have a site on Business or higher plan.
2. [Activate hosting features](https://wordpress.com/support/activate-your-business-plan/#activate-hosting-access) if they're not yet activated.
3. Go to "Deployments" tab.
4. **Observe** "Connect" button not rendered in correct style.
5. Select and connect a repository.
6. After the repository is connected, observe "Connect repository" button not rendered in correct style.
7. **Observe** the search box is inconsistent with the sites search box.
8. Click "..." to bring up the context menu, select "Disconnect repository".
9. **Observe** the confirmation modal style is off.

### What you expected to happen

GitHub deployments UI rendered in style consistent with the rest of the site.

### What actually happened

GitHub deployments UI rendered in style inconsistent with the rest of the site.

### Impact

Some (< 50%)

### Available workarounds?

There is no user impact

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by zaguiini**
Closes https://github.com/Automattic/wp-calypso/issues/95903.

## Proposed Changes

- Switch most `<Button />` instances to Gutenberg component instances instead of the deprecated Calypso button. I'm not switching them all because the leftovers will be removed when transitioning the tables to DataViews https://github.com/Automattic/dotcom-forge/issues/9598#top.

- Smaller font sizes in the repository selection dialog, along with replacing the search component.

image

- Smaller font size in the repository "input":

image

## Why are these changes being made?

To conform to the new Calypso guidelines.

### CODE REVIEW

**Comment by zaguiini** [comment]
### Select repository dialog

The text feels too big here.

image

### Claustrophobia

With the new design changes introduced in Calypso, things are starting to become squeezed. Look at the deployed commit details:

image

File: client/sites/tools/deployments/components/repositories/browse-repositories.tsx [hunk 1]
```diff
@@ -89,8 +89,9 @@ export const GitHubBrowseRepositories = ( {
 					value={ installation }
 					onChange={ setInstallation }
 				/>
-				<SearchRepos
-					disabled={ ! installations.length }
+				<SearchControl
```
Comment (paulopmt1) [inline client/sites/tools/deployments/components/repositories/browse-repositories.tsx:92]: Should we add the `Search Repositories` placeholder as we had in the previous implementation?

File: client/sites/tools/deployments/components/github-connection-form/index.tsx [hunk 2]
```diff
@@ -151,25 +151,23 @@ export const GitHubConnectionForm = ( {
...
+											displayMissingRepositoryError,
+									} ) }
 								>
-									{ repository.owner }/{ repository.name }
-								</ExternalLink>
-							) : (
-								<FormSettingExplanation css={ { margin: '0 !important' } }>
-									{ __( 'No repository selected' ) }
-								</FormSettingExplanation>
+									<ExternalLink
```
Comment (paulopmt1) [inline client/sites/tools/deployments/components/github-connection-form/index.tsx:162]: This improved the UX IMHO.

File: client/sites/tools/deployments/style.scss [hunk 3]
```diff
@@ -8,4 +8,9 @@
 		align-self: flex-start;
 		margin: 0;
 	}
+
+	.components-button.is-primary.is-busy {
```
Comment (paulopmt1) [inline client/sites/tools/deployments/style.scss:13]: Should we keep the default gray linear gradient and align that with the designers?

File: client/sites/tools/deployments/deployment-management/style.scss [hunk 4]
```diff
@@ -1,51 +0,0 @@
-.github-deployments-connect-repository {
```
Comment (paulopmt1) [inline client/sites/tools/deployments/deployment-management/style.scss:1]: This is awesome!

File: client/sites/tools/deployments/components/repositories/style.scss [hunk 5]
```diff
@@ -92,7 +78,7 @@
 
 	tr th {
 		font-weight: 500;
-		color: var(--studio-gray-60, #50575e);
+		color: var(--studio-gray-60);
```
Comment (paulopmt1) [inline client/sites/tools/deployments/components/repositories/style.scss:81]: Thanks for removing all these custom codes!

**Review by paulopmt1 — APPROVED** [review]
Good job @zaguiini, thanks for improving it!

Left some non-blocking feedback.

File: client/sites/tools/deployments/style.scss (hunk 3 above)
Comment (zaguiini) [reply client/sites/tools/deployments/style.scss:12]: I'm not sure I follow. I'm adding these styles to revert to the Gutenberg styles because we're adding our own global overrides.

| Before | After |
| ----- | ------- | 
| https://github.com/user-attachments/assets/32dbe076-07e1-42e3-8bbd-3580c525b30c | https://github.com/user-attachments/assets/2a5f9721-13f9-4a41-ad63-3e7a3cbc99b6 |

Comment (zaguiini) [reply client/sites/tools/deployments/style.scss:13]: I'm not sure I follow. I'm adding these styles to revert to the Gutenberg styles because we're adding our own global overrides.

Here's what we have with this patch:

https://github.com/user-attachments/assets/c68d9af1-a460-45e6-beb9-f3eb8982a0b3

And here's what we get if we remove it:

https://github.com/user-attachments/assets/d115c258-7c39-4e2b-8d08-95a2e4ca414e

Is there a better way of achieving the same result?

Comment (paulopmt1) [reply client/sites/tools/deployments/style.scss:13]: > I'm adding these styles to revert to the Gutenberg styles because we're adding our own global overrides

I mean, maybe we should search and remove the overrides instead of adding another one since we've been working towards removing any Gutenberg overrides recently.

Comment (zaguiini) [reply client/sites/tools/deployments/style.scss:13]: Absolutely. I'm just not sure how we can do it. But I'll take a look.

Comment (zaguiini) [reply client/sites/tools/deployments/style.scss:13]: I tried looking for a solution but it seems that it's a bit more complex than that. I ended up adding a FIXME comment pointing to this Slack message: p1731590534067879-slack-C03DY3RJ5. It's totally unrelated to the PR so that's why I think we should address it elsewhere (and remove the patches.)
