### PR TITLE
Purchases: Button state for cancelling Private Registration

### LINKED ISSUE #195: Purchases: weird button state when cancelling private registration
The Cancel button in the Cancel Private Registration screen becomes white with a blue border when clicked. This is confusing, as it makes it look like something went wrong or broke -- especially since there's no processing indicator and it's unclear wither the cancellation is happening or not. 

This is what it looks like in Firefox 40.0.3 for Linux:

screenshot-wpcalypso wordpress com 2015-11-19 16-47-33

As far as I can see, other products have the same issue in the Cancel button, but it seems to be more prominent with Private Registration.

### PR DESCRIPTION
**Pull request by umurkontaci**
Fixes #195.

This PR adds a cancelling state to the button when cancelling Private Registration.
It changes the button label to "Processing..." on click.

It also blurs the button on click to get rid of the blue outline after clicking the button. I opted to keep the css for the focus state since that helps with accessibility, but after clicking the outline is gone.

Testing:
---

1. Go to `/purchases`
2. Select a domain with Private Registration
3. Go ahead and cancel it
4. Verify that the text changes to "Processing..."
5. Verify that the blue outline goes away.

/cc: @fabianapsimoes

### CODE REVIEW

**Comment by fabianapsimoes** [comment]
The contrast between "Processing..." and the background is quite low. Can we make it dark gray?

dmlite

cc @mikeshelton1503 for a design review.

**Comment by fabianapsimoes** [comment]
> Blue outline still there. 

It actually only persists in Firefox. In Chrome, it shows briefly and then disappears.

**Comment by umurkontaci** [comment]
I've updated the code and opted to keep the outline for focusing, but after clicking, I'm blurring the button so the outline will not be there to confuse people.

File: client/me/purchases/cancel-private-registration/index.jsx [hunk 1]
```diff
@@ -88,7 +93,7 @@ const CancelPrivateRegistration = React.createClass( {
 				onClick={ this.cancel }
 				className="cancel-private-registration__cancel-button"
 				disabled={ this.state.disabled }>
-				{ this.translate( 'Cancel Private Registration' ) }
+				{ this.state.cancelling ? this.translate( 'Processing…' ) : this.translate( 'Cancel Private Registration' ) }
```
Comment (umurkontaci) [inline client/me/purchases/cancel-private-registration/index.jsx]: :white_check_mark:

**Comment by mikeshelton1503** [comment]
This looks great @umurkontaci. Design :+1: 

Though we should add this same behavior and styling to all cancel actions not just private registrations.

File: client/me/purchases/cancel-private-registration/index.jsx [hunk 2]
```diff
@@ -20,7 +20,8 @@ import SimpleNotice from 'notices/simple-notice';
 const CancelPrivateRegistration = React.createClass( {
 	getInitialState() {
 		return {
-			disabled: false
+			disabled: false,
+			cancelling: false
```
Comment (stephanethomas) [inline client/me/purchases/cancel-private-registration/index.jsx]: Do we really need to introduce another attribute? `disabled` and `cancelling` handle the same thing apparently. I could see a reason to make the distinction if there was a form with data loading from the API but here we only need to prevent users from submitting the form when they click the `Cancel Private Registration` button.

File: client/me/purchases/cancel-private-registration/style.scss [hunk 3]
```diff
@@ -23,4 +23,8 @@
 
 .cancel-private-registration__cancel-button {
 	margin-top: 10px;
+
+	&.disabled, &[disabled] {
```
Comment (stephanethomas) [inline client/me/purchases/cancel-private-registration/style.scss]: Do we really need to specify the `&.disabled` selector? As far I can see it's never used by our markup.

File: client/me/purchases/cancel-private-registration/index.jsx (hunk 2 above)
Comment (umurkontaci) [inline client/me/purchases/cancel-private-registration/index.jsx]: I think we do. For this case the output will be the same regardless, but I think it is important to be a bit more explicit about the attributes. Afaik we have been explicit about our attributes and I'm following the convention. We can just use the "cancelling" attribute for this case, but I think being explicit is more of an example. This is open to discussion though.

File: client/me/purchases/cancel-private-registration/index.jsx [hunk 4]
```diff
@@ -30,14 +31,22 @@ const CancelPrivateRegistration = React.createClass( {
 		page( paths.managePurchase( domain, id ) );
 	},
 
-	cancel() {
+	cancel( event ) {
+		event.preventDefault();
+		event.target.blur();
```
Comment (stephanethomas) [inline client/me/purchases/cancel-private-registration/index.jsx]: We could add a comment explaining why we're calling `blur()` - it's not obvious at first glance.

Just curious, why did you have to call `preventDefault()`?

File: client/me/purchases/cancel-private-registration/style.scss (hunk 3 above)
Comment (umurkontaci) [inline client/me/purchases/cancel-private-registration/style.scss]: Muscle memory :) Removed `.disabled` selector.

File: client/me/purchases/cancel-private-registration/index.jsx (hunk 4 above)
Comment (umurkontaci) [inline client/me/purchases/cancel-private-registration/index.jsx]: Added comment for the `blur()`, and removed `preventDefault()` call.

**Comment by stephanethomas** [comment]
Thinking a bit more about this outline issue, I don't see this problem with submit buttons in the domain management section. Maybe it's because we use `<FormButton />` elements there? Moreover, we probably don't have to handle that in Javascript - using the `:blur` pseudo-class in our CSS should do the trick.

**Comment by umurkontaci** [comment]
FF and Chrome acts differently for buttons, we need to confirm that the outline is not there in Firefox on Domain Management section.

Basically, Chrome removes the `:active` pseudo class after the click is through, but FF keeps it until you click somewhere else. `:blur` won't do anything since it's not going to be blurred until either we trigger it, or the user clicks something else.

**Comment by stephanethomas** [comment]
Good point. I confirm that the outline is not hidden in Firefox.

**Comment by stephanethomas** [comment]
This outline issue is probably something we should address in a different pull request though. That way we will update every location by updating the `<Button />` and `<FormButton />` components. People from design could probably help us in this regard. What do you think?

**Comment by umurkontaci** [comment]
It sounds like a viable solution. Do you think we'd have any issues by making an active change to a widely used component? Is there any case we'd *not* want to blur? 

I can't think of any. Do you think it's OK @mikeshelton1503 ?

File: client/me/purchases/cancel-private-registration/index.jsx (hunk 2 above)
Comment (babyhognut) [inline client/me/purchases/cancel-private-registration/index.jsx]: its

**Comment by fabianapsimoes** [comment]
This latest version looks good.

> Though we should add this same behavior and styling to all cancel actions not just private registrations.

@umurkontaci would you rather I open a new issue for this?

**Comment by umurkontaci** [comment]
@fabianapsimoes Let's hear from the design team first to hear that it's alright to blur on click on every button.

**Comment by mikeshelton1503** [comment]
>It sounds like a viable solution. Do you think we'd have any issues by making an active change to a widely used component? Is there any case we'd not want to blur?

I'm not sure honestly. @MichaelArestad recently did some work on the button component so he might be better to answer that question.

File: client/me/purchases/cancel-private-registration/index.jsx (hunk 2 above)
Comment (drewblaisdell) [inline client/me/purchases/cancel-private-registration/index.jsx]: Not our own, but the React docs recommend that you use the [minimal representation of UI state](https://facebook.github.io/react/docs/thinking-in-react.html#step-3-identify-the-minimal-but-complete-representation-of-ui-state). Keeping state as small as possible also means that we'll have fewer possible states to test (even though this component can currently never get in a state where canceling !== disabled). We follow this principle enough in Calypso that two separate properties with the same value in state might be confusing.

**Comment by fabianapsimoes** [comment]
@umurkontaci I'd say merge this as it is, and open a new issue for the component changes / updating the other buttons. What do you think?

cc @stephanethomas, @drewblaisdell who reviewed the code.

**Comment by scruffian** [comment]
Lets not block this waiting for design feedback on a component...

**Comment by scruffian** [comment]
LGTM :+1:
