### PR TITLE
Reader: Stop resizing images in content

### LINKED ISSUE #10091: Reader: square gallery images look distorted in Reader full post view
Steps to reproduce:

1. Create an publish a new post including a gallery of images set to use the "Square Tiles" layout.
1. Find the site in the Reader (you can tap the ellipsis in the bottom-right menu and then click on the "View Site in the Reader" link).
1. Click on the post title so that you are viewing the full post in the Reader.
1. Check to see whether the images look normal or squished.

<strong>Result:</strong> images from a square gallery look distorted in the Reader full post view.

screen shot 2016-12-15 at thu dec 15 11 45 57 am
<sup>Seen at https://wordpress.com/read/feeds/42873943/posts/1262017714 using Firefox 50.0.2 on Mac OS X 10.12</sup>

/hat tip pellymade for the report at https://en.forums.wordpress.com/topic/new-reader-look?replies=4#post-2816708

### PR DESCRIPTION
**Pull request by blowery**
This was a misguided attempt to get bigger images for features, from a long time ago.
Sadly, it breaks things that use photon or the wp image api to make images a specific size.

Fixes #10091

This doesn't make the gallery responsive to window resizing; that will have to come in another PR.

To test, open a variety of full posts in the Reader. Make sure the images look how you would expect.

### CODE REVIEW

**Comment by blowery** [comment]
after
square_gallery_test_ _design5279_ _reader_ _wordpress_com

**Comment by bluefuton** [comment]
@blowery can you share the URL to your test post above?

File: client/lib/post-normalizer/rule-content-make-images-safe.js [hunk 1]
```diff
@@ -60,7 +60,7 @@ function isCandidateForContentImage( imageUrl ) {
 	} );
 }
 
-export default function( maxWidth ) {
```
Comment (blowery) [inline client/lib/post-normalizer/rule-content-make-images-safe.js]: we're not, but i'm not sure no one is. If we drop it, we also have to update callers too to not invoke the function to get the actual normalization function.

Comment (blowery) [inline client/lib/post-normalizer/rule-content-make-images-safe.js]: i mean, the wrapped function is still using it, but callers no longer have to use it. Notice the caller is still invoking the function with `()`

**Comment by blowery** [comment]
Post was https://wordpress.com/read/feeds/42873943/posts/1262017714

File: client/lib/post-normalizer/rule-content-make-images-safe.js (hunk 1 above)
Comment (samouri) [inline client/lib/post-normalizer/rule-content-make-images-safe.js]: @blowery, can you explain a little more how this broke things?
I'm still unsure if this bug is affecting `posts-lists` (the only other client of this functionality).

Comment (blowery) [inline client/lib/post-normalizer/rule-content-make-images-safe.js]: @samouri sure. we're resizing images passed through photon, forcing them to conform to a max width. But when we do that, we also strip a bunch of parameters also related to sizing, like crop and fit. Dropping those is what caused the reported squishing of images. 

My first thought was to modify those parameters too, instead of dropping them, but going down that road showed that altering the width of the content images actually has some pretty bad effects, especially when an image is missing a width and height in the source (which is pretty common for dotcom images and responsive wp sites). 

So the best solution I found was to leave the images alone, but to at least make them safe.
