### PR TITLE
Slideshow Block: Image captions not reflecting newly updated caption in block editor.

### LINKED ISSUE #51013: Slideshow Block: Block remembers Image Captions, so they can't be changed or removed.
### Steps to reproduce the behavior

1. Go to the site's Media Library, and import some images from Pexels (since those come with captions by default)
2. Go to Site - Pages, create a page, add a Slideshow Block to it, and add all of your new Pexels images to the slideshow. Publish the page. 
3. Visit the page, and you'll see all of the captions appearing at the bottom of images. 
4. Go back to your Media Library, click on your images, remove the captions, or change them to something different.
5. Refresh the page that has the existing slideshow on it. The captions do not change. They'll remain as they were when they were originally added to the slideshow block.

#### What I expected to happen
Image Captions to change on the slideshow once they're changed on the actual image.

#### What actually happened
Image captions do not change with the slideshow. The image needs to be removed from the slideshow, saved, then added back in, for the caption to update.

### Context
#user-report

#### Browser / OS version
All
#### Does this happen on simple or atomic sites or both?
Both.
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Affects all slideshow blocks.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
image
image

### PR DESCRIPTION
**Pull request by yansern**
## Changes proposed in this Pull Request

This PR partially fixes the issue https://github.com/Automattic/wp-calypso/issues/51013. 

**What is fixed:**
Image caption on Slideshow block is updated when editing the image caption on media library through the **Block Editor**,

**What is not fixed:**
Image caption on Slideshow block is updated when editing the image caption on media library through **Calypso**.

**Technical changes:**
* Keep a local component state `updatedItems` which contains changes made (like caption) on the `selectedItems`.
* Introduce `getSelectedItems()` which returns selected items with updated local changes (in case saving remotely hasn't happened yet).

## Testing instructions

1. On your block editor, add a Slideshow block with 2 images.
2. Click on the "Edit" button on the block toolbar of the Slideshow block.
3. Media library will open again.
4. Click "Edit" button on the media library to edit the caption of the images.
5. Modify the caption, and click "Insert" button.
6. The newly updated caption should be reflected on the slideshow block.

## Preview

https://user-images.githubusercontent.com/1287077/134908225-adf744a6-ca20-4d18-a8d1-0dd2c12d40e1.mp4

Partially fixes https://github.com/Automattic/wp-calypso/issues/51013

### CODE REVIEW

File: client/post-editor/media-modal/detail/detail-fields.jsx [hunk 1]
```diff
@@ -31,19 +31,20 @@ class EditorMediaModalDetailFields extends Component {
 
 	constructor() {
 		super( ...arguments );
-		this.persistChange = debounce( this._persistChange, 1000 );
+
+		// Save changes to server after 1000 second delay
```
Comment (arcangelini) [inline client/post-editor/media-modal/detail/detail-fields.jsx]: Would this be 1000 seconds or 1000 milliseconds aka 1 second?

**Review by arcangelini — APPROVED** [review]
Tested and works 🎉

File: client/post-editor/media-modal/detail/detail-fields.jsx (hunk 1 above)
Comment (yansern) [reply client/post-editor/media-modal/detail/detail-fields.jsx]: Thanks! It should be 1 second. Updating!
