### PR TITLE
Jetpack Connect: Add Browser Title

### LINKED ISSUE #32430: Jetpack connection flow has "Statistics" in site title
Browser title (I mean the actual `<title>` tag) doesn't get updated when entering Jetpack connect flow from Calypso.

#### Steps to reproduce
1. Go to "My sites", you should be at "statistics" page for a site
2. From sidebar, press "switch site" and then "add new site" 
    image
3. Enter a site URL in the Jetpack input
4. If the URL isn't a Jetpack site, error shows up and page title/tab stays "Statistics". If the site is correct, title says "Statistics" until the redirect happens and then it says "WordPress.com". It could mention something about connecting a site so that page history titles would be little bit more meaningful:
  image

Doesn't happen when creating a new simple site via same flow.

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

Switches the browser title for the Jetpack Connect flow and for the screen where you can add a new site. Currently, the browser title is identical to the previous page which the user was on, or WordPress.com. 

#### Testing instructions

**Route:** `jetpack/new/` (can be accessed by clicking "Add New Site" in sidebar)
**Title:** Add New Site (the wording is from the heading that appears on the page)

**Route:** `jetpack/connect/` (also includes connections from wp-admin)
**Title:** Jetpack Connect (until Checkout, where the title is "Checkout")

Screenshot 2019-08-03 at 16 27 40

1. Are the correct titles reflected in the browser?
2. Is the wording okay?

cc @simison 

Fixes #32430

### CODE REVIEW

File: client/jetpack-connect/main-wrapper.jsx [hunk 1]
```diff
@@ -45,6 +46,7 @@ export class JetpackConnectMainWrapper extends PureComponent {
 
 		return (
 			<Main className={ classNames( className, wrapperClassName ) }>
+				<DocumentHead title={ translate( 'Jetpack Connect' ) } />
```
Comment (a8ci18n) [inline client/jetpack-connect/main-wrapper.jsx]: Hi! I've found a possible matching string that has already been translated **42** times:
`translate( 'Connect Jetpack' )` *ES Score: 7*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/pull/35121)

Help me improve these suggestions: react with :thumbsdown: if the suggestion doesn't make any sense, or with :thumbsup: if it's a particularly good one (even if not implemented).

Comment (Aurorum) [reply client/jetpack-connect/main-wrapper.jsx]: I wonder if this is the better option to go with anyway?

**Comment by Aurorum** [comment]
Hm, I can't manage to get the tests to pass on this one - any idea what I'm doing wrong?

**Comment by sirreal** [comment]
Thanks @Aurorum!

> Hm, I can't manage to get the tests to pass on this one - any idea what I'm doing wrong?

You didn't do anything wrong 🙂 

The problem is that `DocumentHead` is a _connected_ component, it connects to Redux state and expects to be wrapped by a Redux `Provider`:

https://github.com/Automattic/wp-calypso/blob/721c68b6249449bfe948a264ceb15bcaa6be2126/client/components/data/document-head/index.jsx#L95-L105

In the application, components don't need to worry about that. The `Provider` is at or near the top of the component tree and wraps pretty much everything. In tests, we often isolate components. This becomes problematic for components that expect to be connected.

This simplest and quickest way forward is probably to mock the `DocumentHead` component in the failing tests. You should find examples around the codebase if you look for `jest.mock`.

**Comment by Aurorum** [comment]
Thank you, that got the tests passing! 💜
