### PR TITLE
Page Templates: Fix Blank title insertion, some code cleanup

### LINKED ISSUE #36060: (1P) SPT: Don't insert "Blank" title when selecting blank template
This bug was introduced last iteration, when we added the template title to the preview.

### PR DESCRIPTION
**Pull request by marekhrabe**
Fixing the Blank title bug was connected to some other parts of code so I did a bit of a cleanup along the way.

#### Changes proposed in this Pull Request

* fix the bug when selecting a blank template would insert the title "Blank"
* removed long unused code for `onFocus` (which had nothing to do with a focus)
* removed multiple sources of truth and extraneous passing for template titles between components
* select the first template by default (Blank)

#### Testing instructions

* use inserter as normal, try switching between templates
* insert template with content - everything should work
* insert "Blank" - our plugin should close and you should see nothing being inserted into the editor - no title, no content

Fixes #36060

### CODE REVIEW

**Review by obenland — APPROVED** [review]
Tested locally. Looks good to me! :shipit:

**Review by getdave — CHANGES_REQUESTED** [review]
Nice work! Glad this is fixed. I tested this and confirmed that:

✅ The title (ie: "blank") is not inserted when selecting the Blank template.
✅ The correct Template title _is_ inserted when selecting a valid Template other than the blank one.

My only other concerns are:

1. Have / will you updated the tests (shout if you need help with setup...etc)?
2. Are we merging too many changes into this PR. Lots of small things add up and are also making this harder to review code-wise.

Thanks for working on this 👍

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/template-selector-item.js [hunk 1]
```diff
@@ -54,8 +53,7 @@ const TemplateSelectorItem = props => {
 			type="button"
 			className="template-selector-item__label"
 			value={ value }
-			onMouseEnter={ () => onFocus( value, label ) }
-			onClick={ () => onSelect( value, label ) }
+			onClick={ () => onSelect( value ) }
```
[the remark this answers is not in the document]
Comment (retrofox) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/template-selector-item.js]: from PR description:

> removed long unused code for onFocus (which had nothing to do with a focus)

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js [hunk 2]
```diff
@@ -33,16 +33,22 @@ const {
...
 
 	constructor( props ) {
 		super();
-		this.state.isOpen = ! isEmpty( props.templates );
+		const hasTemplates = ! isEmpty( props.templates );
+		this.state.isOpen = hasTemplates;
+		// Select the first template automatically.
+		if ( hasTemplates ) {
+			this.state.previewedTemplate = get( props.templates, [ 0, 'slug' ] );
+			this.state.templatesBySlug = keyBy( props.templates, 'slug' );
```
Comment (retrofox) [inline apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: Do you think that it's completely needed to populate the state with the `templatesBySlug` object? It seems to be used only to get the template title. What about...

```es6
	getTitleBySlug( slug = this.state.previewedTemplate ) {
		return get( find( this.props.templates, { slug } ), 'title', '' );
	}
```

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js [hunk 3]
```diff
@@ -134,16 +138,12 @@ class PageTemplateModal extends Component {
...
-	getBlocksByTemplateSlug( slug = this.state.slug ) {
-		if ( ! slug ) {
-			return [];
-		}
-
-		if ( ! this.state.blocks.hasOwnProperty( slug ) ) {
-			return [];
-		}
+	getBlocksBySlug( slug = this.state.previewedTemplate ) {
+		return get( this.state.blocksBySlug, [ slug ], [] );
```
Comment (retrofox) [inline apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: :100:

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js [hunk 4]
```diff
@@ -134,16 +138,12 @@ class PageTemplateModal extends Component {
...
 
-	getBlocksByTemplateSlug( slug = this.state.slug ) {
-		if ( ! slug ) {
-			return [];
-		}
-
-		if ( ! this.state.blocks.hasOwnProperty( slug ) ) {
-			return [];
-		}
+	getBlocksBySlug( slug = this.state.previewedTemplate ) {
```
Comment (retrofox) [inline apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: Not 100% sure about renaming the method here, since `templateSlug` describes that it refers to the template slug. It worths in this context, imho.

**Review by retrofox — COMMENTED** [review]
It works as expected. I got similar concerns as @getdave 

> Are we merging too many changes into this PR. Lots of small things add up and are also making this harder to review code-wise.

We're going to introduce many changes that maybe aren't completely needed to fix the original issue, and it could impact on other patches. Anyway, it's part of our job ;-).

Left some comments, which I think make worth take a look, especially this one: 
https://github.com/Automattic/wp-calypso/pull/36270#pullrequestreview-293098588
I'd like to know your opinion before to approve this one. 🙇

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js [hunk 5]
```diff
@@ -63,35 +69,30 @@ class PageTemplateModal extends Component {
...
+		const title = this.getTitleBySlug( slug );
 
 		// Skip inserting if there's nothing to insert.
 		if ( ! blocks || ! blocks.length ) {
+			this.setState( { isOpen: false } );
 			return;
 		}
 
+		// Show loading state.
+		this.setState( {
```
[the remark this answers is not in the document]
Comment (marekhrabe) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: No, it has been introduced as part of the ability to side load images. It has only been moved in this PR (and prepended with a comment).

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js [hunk 6]
```diff
@@ -193,10 +193,10 @@ class PageTemplateModal extends Component {
 					<Button
 						isPrimary
 						isLarge
-						disabled={ isEmpty( this.state.slug ) || this.state.isLoading }
+						disabled={ isEmpty( this.state.previewedTemplate ) || this.state.isLoading }
 						onClick={ this.handleConfirmation }
 					>
-						{ sprintf( __( 'Use %s template', 'full-site-editing' ), this.state.title ) }
+						{ sprintf( __( 'Use %s template', 'full-site-editing' ), this.getTitleBySlug() ) }
```
[the remark this answers is not in the document]
Comment (marekhrabe) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: I was actually in the same boat - I don't like that much but I wanted to follow what was in the code. I would much rather remove the default fallback and always pass slug.

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/template-selector-item.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (marekhrabe) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/template-selector-item.js]: I was standing between the choice to either update the function call to keep it working (the same way as `onClick`) or remove it because we don't use it at all. I chose the 🔥method but happy to revert if you want the fn to stay for some reason.

**Comment by marekhrabe** [comment]
Just to clarify about the PR scope, all those things are deeply connected. I initially started just by fixing the "Blank" title problem but it was just another bandaid on top of previous ones. So I went through the rabbit hole - the template title was duplicated in state and was passed in both directions (from parent to child but sadly also from child to parent). So I removed that explicit passing in favor of always reading it from the template object. Making a getter fn for the title allowed me to use in both the UI and the template insertion. That however lead to the issue when initial state of the modal said "Use undefined template" because no template is initially selected. So I've added the automattic selection of the first template (which happens to be Blank). 

I'm always in favor of smaller PRs but I felt that in this case if we don't do those together, their separate PRs would all be half-functioning without each other and even less testable. I believe the diff size is not too terrible in this case but I'll aim for smaller ones next time and spend more time trying to figure out how to split more.

**Comment by retrofox** [comment]
> I believe the diff size is not too terrible in this case but I'll aim for smaller ones next time and spend more time trying to figure out how to split more.

No worries at all, completely sure we understand this situation. A question that I'm interesting to know here is why we are storing the templates (by slug) in the state when we already have them into the props. since it doesn't seem to be necessary. https://github.com/Automattic/wp-calypso/pull/36270#pullrequestreview-293098588, but don't take it as a blocker and go ahead!

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js [hunk 7]
```diff
@@ -115,13 +117,15 @@ class PageTemplateModal extends Component {
 		return this.props.shouldPrefetchAssets ? ensureAssets( blocks ) : Promise.resolve( blocks );
 	};
 
-	handleConfirmation = () => this.setTemplate( this.state.slug, this.state.title );
+	handleConfirmation = () => this.setTemplate( this.state.previewedTemplate );
 
-	previewTemplate = ( slug, title ) => {
-		this.setState( { slug, title } );
+	previewTemplate = slug => {
+		// Immediately confirm and close when 'blank' is selected.
```
[the remark this answers is not in the document]
Comment (retrofox) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: Keep in mind this PR was recently closed.

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js (hunk 2 above)
Comment (marekhrabe) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: While the `find` solution definitely works, it requires to always loop over the array for each call of that function which we do twice per render. Having the dictionary in state created by `keyBy` makes this loop happen once per page view and any further lookup is instantaneous while keeping a really low memory impact (remember objects are not copies but references here). 

The only disadvantage is that `templatesBySlug` won't update if we get re-rendered with a different set of `templates` but this is true for our whole plugin so I didn't bother at this point (also because that situation is not possible to be triggered with our current code).

Comment (retrofox) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: Ok, got it. Already getting into very detailed issues, make sense just store the title instead of the whole template object? My concern provably unfounded is filling the state with duplicated data.
Take this comment much as a teaching session rather than a feedback request. ;-)

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js [hunk 8]
```diff
@@ -171,17 +171,17 @@ class PageTemplateModal extends Component {
...
 										siteInformation={ siteInformation }
 									/>
 								</fieldset>
 							</form>
 							<TemplateSelectorPreview
-								blocks={ this.getBlocksByTemplateSlug() }
+								blocks={ this.getBlocksBySlug() }
 								viewportWidth={ 960 }
-								title={ this.state.title }
+								title={ this.getTitleBySlug() }
```
[the remark this answers is not in the document]
Comment (marekhrabe) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: now always explicit

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js (hunk 4 above)
Comment (marekhrabe) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: ok, it's using the longer wording from now on 👍

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js (hunk 2 above)
Comment (marekhrabe) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: We are definitely in a theoretical area here but I like it! Normally, I would have implemented all this props/state mess as a Redux store and in those, it is a well established pattern to use two data structs to store data like this:

- `templatesBySlug` - an object keyed by the slug with values of the full template objects. an example:

```
templatesBySlug = {
  blank: { title: 'Blank', … },
  about: { title: 'About', … },
  …
}
```

- and the other part `templateList` - an array of slugs that are supposed to be displayed (also explicitly stating their order). an example:

```
templateList = [ 'blank', 'about', 'contact', … ]
```

I think we are slowly getting there and I expect us to switch to Redux at some point (with @wordpress/data) so just keeping it here for an inspiration.

Regarding storing just titles, the difference is that those would be stored as copies in memory (doubling the usage) as that's what JS does for scalar types. On the other hand, when storing objects, they are not copies but only references.

In case of titles, the memory impact is extremely tiny even for copies (they are short strings and there is a small number of them). I'm happy to switch to that approach for now as we don't access anything other than titles.

Comment (retrofox) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: I really appreciate it. :thanks:

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js [hunk 9]
```diff
@@ -33,16 +33,22 @@ const {
...
 		error: null,
 		isOpen: false,
 	};
 
 	constructor( props ) {
 		super();
-		this.state.isOpen = ! isEmpty( props.templates );
+		const hasTemplates = ! isEmpty( props.templates );
+		this.state.isOpen = hasTemplates;
+		// Select the first template automatically.
```
[the remark this answers is not in the document]
Comment (marekhrabe) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: > wrapped up in a PR which is concerned with blank template titles.

I left longer explanation as a comment in the main PR thread. tldr: when there was no template selected (that was the initial state) and titles were no longer duplicated in the state, it lead to the confirmation button saying "Use undefined template" as it referenced non-existing template. This change, although not seeming related, made sure we don't need to add more complexity to the button rendering logic and there will always be a template selected.

**Comment by marekhrabe** [comment]
I hope I've addressed most of the feedback now. I left a few conversations opened where I'm not sure you are ok with proceeding. Let me know!

**Comment by retrofox** [comment]
- [x] fix the bug when selecting a blank template would insert the title "Blank"
- [x] removed long unused code for onFocus (which had nothing to do with a focus)
- [x] removed multiple sources of truth and extraneous passing for template titles between components
- [x] select the first template by default (Blank)

Screen Shot 2019-09-26 at 10 13 48 AM

**Review by retrofox — APPROVED** [review]
Thanks, Marek for this PR. Improves the code considerably 👍
