### PR TITLE
Change the editor links when Dashboard Appearance toggle is enabled

### LINKED ISSUE #51058: Nav Unification: Force the "Write" button in the Masterbar to acknowledge the status of the "Dashboard Appearance" toggle
### Steps to reproduce the behavior

1. Create a new post or page
2. Click on the "View all posts" link to go back

Screen Shot on 2021-03-15 at 08:25:26

#### What I expected to happen

I expected this link to take into account my current "Dashboard Appearance" and take me to `wordpress.com/posts` or `wp-admin/edit.php` depending on my preference 

#### What actually happened

The link will always take me to https://wordpress.com/posts if the new post was created via https://wordpress.com/post and to `wp-admin/edit.php` of the post was being edited via `wp-admin/post-new.php` regardless of the status of the "Dashboard Appearance" toggle. 

The exact same thing happens with PAGES.

In most scenarios this will not happen, as the "NEW Page/Post" button will use the wp-admin or Calypso URL depending on the "Dashboard Appearance" preference, but at the moment the "Write" button on the top Master bar, does seem to ALWAYS take to https://wordpress.com/posts

Screen Shot on 2021-03-15 at 08:35:44

This is directly related to https://github.com/Automattic/wp-calypso/issues/29208

### PR DESCRIPTION
**Pull request by pablinos**
The links to the editor still default to the iframe'd `/posts` URLs and
that means that people can find themselves back in Calypso even though
they have enabled the 'Dashboard Appearance' option, which should
default to `wp-admin`.

#### Changes proposed in this Pull Request

This change, updates the logic in the selector for these links, as well
as the redirect logic as the iframe loads, to take the 'Dashboard
Appearance' setting in to account.

Fixes https://github.com/Automattic/wp-calypso/issues/51058

#### Testing instructions

As outlined in #51058.

* Change your 'Dashboard Appearance' setting in `/me/account` so that it is enabled.
* Click on the 'Write' button in the top bar. This should now take you to the `wp-admin` version of the editor.
* Clicking on the 'All Posts' link in the left side nav, should take you back to `wp-admin`
* Also check that heading to /post/<YOUR SITE> redirects you to `wp-admin`

#### Notes

It's worth noting that this is relying on something that could be considered a bug. When the editor is loaded outside of the iframe, the code to override the editor `closeUrl` isn't loaded, so it is left as the default, which is `wp-admin`. By making sure that we load the editor in `wp-admin`, outside of the iframe, then the link works as expected. 

We should change this so the code takes the 'Dashboard Appearance' setting into account and loads the code when appropriate. This is a much larger change though.

Also, I think there will need to be a separate change to update the link in the top navigation bar in `wp-admin`, as well as possibly the WordPress.com navigation module in Jetpack.

Related to #51058

### CODE REVIEW

**Comment by allilevine** [comment]
> 
>     * Change your 'Dashboard Appearance' setting in `/me/account` so that it is enabled.
> 
>     * Click on the 'Write' button in the top bar. This should now take you to the `wp-admin` version of the editor.
> 
>     * Clicking on the 'All Posts' link in the left side nav, should take you back to `wp-admin`
> 
>     * Also check that heading to /post/ redirects you to `wp-admin`

All of the links took me to `wp-admin` except `/post/`. 🤔 I'm testing by going to `http://calypso.localhost:3000/post/blog-url`.

**Comment by pablinos** [comment]
> All of the links took me to wp-admin except /post/. 🤔 I'm testing by going to http://calypso.localhost:3000/post/blog-url.

Thanks! Sounds like something isn't right, and the tests are failing. I'll take another look.

**Comment by pablinos** [comment]
So, after some investigation, it appears that what is happening is that the `calypso_preferences` in the state are `undefined` until the API request returns successfully. It's a race condition where sometimes this comes back before the redirect check and sometimes it doesn't.

I'm not sure of the best way to solve this, as we need the preference to know whether to redirect, and we could wait for it in the state, but I've had a situation where that request comes back as unauthorised, so we'd need to deal with the error state too. That feels like a lot of logic to live in the controller. 

I feel like I'm missing something obvious. I'll give it some more thought.

**Comment by mmtr** [comment]
> it appears that what is happening is that the calypso_preferences in the state are undefined until the API request returns successfully

I remember we had a similar issue when we first introduced Gutenberg in Calypso a couple of years ago, since we needed to retrieve data from the API before deciding the editor URL. We solved that by:
- Querying the needed data in the `Layout` component: 
https://github.com/Automattic/wp-calypso/blob/f8531073cb6c5f77b4351569426872c3b3afa5cd/client/layout/index.jsx#L235-L237
- Ensuring the data has been received in the editor routes controller:
https://github.com/Automattic/wp-calypso/blob/f8531073cb6c5f77b4351569426872c3b3afa5cd/client/gutenberg/editor/controller.js#L175-L178

**Comment by pablinos** [comment]
Thanks, @mmtr, I was wondering if I needed to do that. I started writing a similar `waitForDesktopAppearanceSetting` but got into a funny state where the API call was returning an error. In those situations, I think things would get stuck. I'll see if there's a simple way to check for errors and default one way or the other.

It also seemed like a complex solution and so I wondered if I was missing something.

**Review by retrofox — COMMENTED** [review]
I've tested the app activating and deactivating the "Dashboard appearance". To works as expected.
The links when creating a new post link points to wp-admin when "Dashboard appearance" is activated. If I type manually the URL to start to edit using the iframe, the app redirects on the fly to wp-admin too.

I have a question about the posts list page. The link for every post seems to follow the _Dashboard appearance_ rule. It means, when it's activated, the URL points to the wp-admin. Otherwise, it points to the calypso app: 

Screen Shot 2021-03-29 at 3 34 14 PM

However, the `All posts` link in the uni-nav menu always points to the wp-admin, independently of the _Dashboard appearance_ state.

Screen Shot 2021-03-29 at 3 33 07 PM

Is it something to deal with?

**Comment by pablinos** [comment]
Hmmm, that seems like a bug. I'll check if it's introduced by this change and if not then I think we should look at it separately.

**Comment by retrofox** [comment]
> Hmmm, that seems like a bug. I'll check if it's introduced by this change and if not then I think we should look at it separately.

Let me help with this too.

**Comment by retrofox** [comment]
it seems to happen even in production too

**Review by retrofox — APPROVED** [review]
Going to approve it since what I commented before seems to happen in prod too.

**Comment by pablinos** [comment]
Yes, I think the site(s) you're seeing this for are Jetpack sites, where wp-admin is the default for all nav links. Simple sites that I've tested this on, the link does change based on the setting

**Comment by pablinos** [comment]
@mmtr Would you mind taking a look at this when you've got a chance please? I'm waiting for both the selected editor and the user preferences to be available before continuing with the routing logic in the controller. I've tried to cover the error condition where we just continue - things should get picked up later, it's not the end of the world if someone ends up in the wrong place and if we can't get the user settings for some reason then it's a sign of something more serious.

Can you see any problems with this? I don't want people getting stuck in this redirect check.

File: client/state/selectors/should-load-gutenframe.js [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+ */
+import { isEligibleForGutenframe } from 'calypso/state/gutenberg-iframe-eligible/is-eligible-for-gutenframe';
+import { shouldCalypsoifyJetpack } from 'calypso/state/selectors/should-calypsoify-jetpack';
+import isNavUnificationEnabled from 'calypso/state/selectors/is-nav-unification-enabled';
+import getUserSettings from 'calypso/state/selectors/get-user-settings';
+
+export const shouldLoadGutenframe = ( state, siteId ) => {
+	return (
+		isEligibleForGutenframe( state, siteId ) &&
+		shouldCalypsoifyJetpack( state, siteId ) &&
```
Comment (mmtr) [inline client/state/selectors/should-load-gutenframe.js]: Nitpick: `isEligibleForGutenframe` already checks `shouldCalypsoifyJetpack`, so do we need to check it again here?

**Review by mmtr — APPROVED** [review]
The proposed approach looks good to me. Nice job, @pablinos.

**Comment by mmtr** [comment]
However, I think this will also need a counterpart fix for WP Admin, so the "Write" button of the top bar displayed on WP Admin screens also links to the same URL.

**Comment by pablinos** [comment]
> However, I think this will also need a counterpart fix for WP Admin, so the "Write" button of the top bar displayed on WP Admin screens also links to the same URL.

Yes, I've been looking at this. I think we've so far taken the approach of sending everyone to `/post` from `wp-admin`. I'll need to look the best way to replicate the logic.

File: client/state/selectors/should-load-gutenframe.js (hunk 1 above)
Comment (pablinos) [reply client/state/selectors/should-load-gutenframe.js]: Yes, that's true. I think I must have forgotten we had it in there. I've updated it.

**Comment by noahtallen** [comment]
I this introduced a performance regression, see: https://github.com/Automattic/wp-calypso/issues/52651
