### PR TITLE
Block Editor: Add an update image event on Media Modal changes

### LINKED ISSUE #29928: Gutenberg: images added from free photo library cause an invalid block
#### Steps to reproduce
1. Add a new image block
2. Insert from media library
3. Select the "free photo library" using the top left icon
4. Insert the image
5. Save the post
6. Refresh the page to reload the post

#### What I expected

The image block should be ok.

#### What happened instead

The image block has a notice about unexpected HTML

screen shot 2019-01-08 at 3 34 20 pm

### PR DESCRIPTION
**Pull request by Copons**
#### Changes proposed in this Pull Request

* Emit an `updateImageBlocks` event whenever an image has been updated or deleted in the Media Modal, so that the server can update accordingly all the blocks containing it.

#### Testing instructions

Test 1

* Apply D25703-code and sandbox a site.
* Open the Block Editor.
* Insert an Image block and, through the Media Modal, add an image from an external source (Pexels or Google Photos).
* Wait a bit until the image is uploaded. There should be no visual clues, but opening the image in a new tab should show a WP.com url instead of a Pexels or Google one).
* Save and reload.
* Make sure the image is displayed correctly.

Test 2

* Add the same image in other blocks (e.g. a File or Gallery block, and try also nesting them into other blocks like Columns).
* Open the Media Modal by editing any of these blocks, and edit the image.
* Rotate the image and confirm. Wait for the new version of the image to be uploaded successfully (the image should not be faded out and loading anymore).
* Instead of inserting it, cancel to close the modal.
* Make sure all the blocks containing the image have been updated correctly with the rotated image.

Test 3

* Open the Media Modal and delete the image.
* Make sure all the blocks containing it have been updated correctly by removing the image.

Fixes #29928

### CODE REVIEW

**Comment by rodrigoi** [comment]
For future generations, #30104 was an issue present with the Gutenlypso code that is not reproducible with this new implementation. Please, be aware when testing.

File: client/gutenberg/editor/calypsoify-iframe.jsx [hunk 1]
```diff
@@ -189,6 +191,23 @@ class CalypsoifyIframe extends Component {
 		}
 	};
 
+	updateImageBlocks = action => {
+		if (
+			! action ||
+			! startsWith( action.data.mime_type, 'image/' ) ||
+			startsWith( action.data.URL, 'blob:' )
+		) {
```
Comment (rodrigoi) [inline client/gutenberg/editor/calypsoify-iframe.jsx]: maybe add a check for `this.iframePort` just to be consistent with other handlers. I didn't found a case when it fails, but that doesn't mean it can't 😉

**Comment by kwight** [comment]
Worked great for me too 👍
