### PR TITLE
Reading Settings: Fix usePostsQuery hook

### LINKED ISSUE #71547: Reading Settings: Fix `usePostsQuery` hook

### PR DESCRIPTION
**Pull request by mashikag**
#### Proposed Changes

* Remove the breaking parameter of `apiNamespace: 'rest/v1.1'`  in the `wpcom.req.get` call to `/sites/${ siteId }/posts`
* Enhance react-query key creation for the `usePostsQuery` hook

#### Testing Instructions

* There is no easy way to test this at the moment. The hook is not used in calypso at all yet. Once merged in it will be picked up and utilised by the upcoming PR for https://github.com/Automattic/wp-calypso/issues/70409.
* Personally I have test this code in the following draft PR: https://github.com/Automattic/wp-calypso/pull/71550

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Fixes #71547

### CODE REVIEW

File: client/data/posts/use-posts-query.ts [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+	parent_id: string;
+	exclude: number | number[];
+	exclude_tree: number;
+	status: string;
+	sticky: 'include' | 'exclude' | 'require';
+	author: string;
+	search: string;
+	meta_key: string;
+	meta_value: string;
+} >;
```
Comment (yansern) [inline client/data/posts/use-posts-query.ts:33]: Thank you for writing the type definitions for this.

**Review by yansern — APPROVED** [review]
Used these 3 snippets on an existing react component to test it out quickly.
```
// In the header
import usePostsQuery from 'calypso/data/posts/use-posts-query';

// In the component
const posts = usePostsQuery( 'yoursitehere.wordpress.com', { page: 1, number: 10 } );

// In the component's output
<textarea>{ JSON.stringify( posts, null, 2 ) }</textarea>
```

The hook works, the data is returning just fine.

Semi-related to this PR: And yes, my only concern is that we're dumping out quite a lot of data just to build a dropdown selection. A specialized API might keep things optimized. Approving this PR anyway.
