### PR TITLE
Activity log: Rewind button behavior

### LINKED ISSUE #18450: Can click inactive Rewind button
#### Steps to reproduce
1. Open Activity Log
2. Click an inactive "Rewind to this day button"

Note: It may take a few clicks — could also be positioning of click.

#### What I expected

Nothing happens, button is inactive

#### What happened instead

Restore dialog appears. Rewind is off, so this should not be possible.

#### Browser / OS version

Mac OS X 10.12.6 / Chrome 61.0.3163.100 (Official Build) (64-bit)

#### Screenshot / Video
kzvtks

#### Context / Source
#manual-testing

### PR DESCRIPTION
**Pull request by eliorivero**
rewindclick

#### Dialog
- homogenize markup for secondary actions (info, chat) using `Button` and update their styling
- remove redundant method and consolidate markup in a single place

#### Rewind button
- update behavior of Rewind button in day header
- when it's clicked, it will be disabled and will expand its associated day to reveal the Rewind dialog that has been inserted
- button is reactivated if
    - Rewind dialog is canceled, or,
    - if another Rewind button is clicked, either in an ellipsis menu or another day header
- when Rewind dialog is canceled or another Rewind button is clicked, the expanded day is not collapsed

Fixes #18450

### CODE REVIEW

File: client/my-sites/stats/activity-log-day/index.jsx [hunk 1]
```diff
@@ -65,6 +88,16 @@ class ActivityLogDay extends Component {
...
+		this.setState( {
+			dayExpanded: true,
+		} );
+	};
+
+	handleCloseDay = () => {
+		this.setState( {
+			dayExpanded: false,
+		} );
 	};
```
Comment (dmsnell) [inline client/my-sites/stats/activity-log-day/index.jsx]: fun fact! we can get rid of some of the syntax noise

```js
handleCloseDay = () => this.setState( { dayExpanded: false } );
```

this is because all we're wanting to do is evaluate the expression. we don't care about the return value but it would be the return from `this.setState()` in this case because of how arrow functions work

**Comment by keoshi** [comment]
Looks good to me!

One detail that I think we should address before merging is whether we allow the day block we're rewinding on to be closed or not.

Right now we do allow it and when the day block is collapsed you can't really tell what's going on. It leads to this confusing state where the _Rewind_ button is disabled and the restore dialog is hidden behind it.

image

**Comment by MichaelArestad** [comment]
@keoshi I was discussing this with @eliorivero yesterday. This is the conclusion I came to:

> Let's disable it for now once clicked. If the use either clicks the cancel button or folds the card, it should cancel the Rewind dialogue and revert the button to be clickable.

Thoughts?

**Comment by keoshi** [comment]
Hm, I like that though I worry about dismissing the restore dialog if the cancellation is anything other than explicit by the user. Will they realize the rewind confirmation has been cancelled just by collapsing the corresponding day?

In my perspective the UI enters a unique, semi-permanent state when rewinding. A suspended state of sorts: you can still browse days and events and change your restore point by defining a new one, but no other actions should happen, nor should other buttons be enabled until the rewind is either confirmed or cancelled. Does this make sense?

**Comment by MichaelArestad** [comment]
> Will they realize the rewind confirmation has been cancelled just by collapsing the corresponding day?

I think we should still close it if the collapse the day for a couple reasons:
* It returns the button state back to default so the user doesn't make assumptions as to why it is white.
* It makes a small guess at intent that they are no longer interested in seeing the events of that day and thus are unlikely to rewind.
* If the user selects rewind on another day, there isn't a leftover rewind dialogue hidden in a collapsed day.

**Comment by MichaelArestad** [comment]
> In my perspective the UI enters a unique, semi-permanent state when rewinding. A suspended state of sorts: you can still browse days and events and change your restore point by defining a new one, but no other actions should happen, nor should other buttons be enabled until the rewind is either confirmed or cancelled. Does this make sense?

I don't think this makes sense because it's just a confirmation dialogue of sorts. If they leave it hanging and decide to rewind from another point, we should let them. If it closes, nothing is harmed.

**Comment by keoshi** [comment]
Fair enough, I trust you! :)

File: client/my-sites/stats/activity-log-day/index.jsx (hunk 1 above)
Comment (eliorivero) [reply client/my-sites/stats/activity-log-day/index.jsx]: Addressed in ab73fd1a07

**Comment by eliorivero** [comment]
In https://github.com/Automattic/wp-calypso/pull/18722/commits/8d77f8c14acde790883728ea14972760a81de40a:

when Rewind is initiated in the day header and the foldable card is expanded and the Rewind dialog inserted, don't allow to collapse the foldable card until user clicks another Rewind button or it's cancelled

rewindcancel

**Comment by MichaelArestad** [comment]
One minor thing and then it's good to go.

1. I select "Rewind to this day"
2. I then select "Rewind to this day" on another day.

When I do things in that order, the button I clicked in step 1 never turns back to being blue. I think it should only remain white if there is a rewind confirmation box inside that same day.

File: client/components/foldable-card/README.md [hunk 2]
```diff
@@ -42,3 +42,4 @@ render: function() {
 * `onOpen`: function to be executed in addition to the expand action when the card is opened
 * `summary`: string or component to show next to the action button when closed
 * `clickableHeader`: boolean indicating if the whole header can be clicked to open the card
+* `disableToggle`: boolean indicating if the chevron up/down button can toggle the card. This is useful for example if you've expanded the card and want to prevent users from closing it unless some action inside the card is completed.
```
Comment (dmsnell) [inline client/components/foldable-card/README.md]: Do we have a true need for this? Why wouldn't we want someone to close the card?

File: client/my-sites/stats/activity-log-day/index.jsx [hunk 3]
```diff
@@ -41,15 +42,38 @@ class ActivityLogDay extends Component {
...
+		rewindHere: false,
+		dayExpanded: false,
+	};
+
+	componentWillReceiveProps( nextProps ) {
+		// if Rewind dialog is being displayed and it's then canceled or a different Rewind button is clicked
+		if (
+			this.state.rewindHere &&
+			( isEmpty( nextProps.requestedRewind ) ||
+				this.props.requestedRewind !== nextProps.requestedRewind )
```
Comment (dmsnell) [inline client/my-sites/stats/activity-log-day/index.jsx]: this `isEmpty()` check may be redundant. Are we only considering cases where it _was_ something but now _isn't_? An empty `nextProps.requestedRewind` will already `!==` a filled-in `this.props.requestedRewind`

also, what is the type of `requestedRewind`? A string? an object?

File: client/my-sites/stats/activity-log-day/index.jsx [hunk 4]
```diff
@@ -65,8 +89,14 @@ class ActivityLogDay extends Component {
 			ts_end_site_day: tsEndOfSiteDay,
 			utc_date: moment.utc( tsEndOfSiteDay ).format( 'YYYY-MM-DD' ),
 		} );
+
+		this.setState( {
+			dayExpanded: true,
+		} );
 	};
 
+	handleCloseDay = () => this.setState( { dayExpanded: false } );
```
Comment (dmsnell) [inline client/my-sites/stats/activity-log-day/index.jsx]: nice terse function!

**Comment by eliorivero** [comment]
In https://github.com/Automattic/wp-calypso/pull/18722/commits/fd720383e4e9c64cfd2e125d8afe01f6a877786c:

make Rewind button in day header always blue when active unless there's a Rewind dialog inserted in this day

blue

File: client/components/foldable-card/README.md (hunk 2 above)
Comment (eliorivero) [reply client/components/foldable-card/README.md]: This was [discussed in](https://github.com/Automattic/wp-calypso/pull/18722#issuecomment-335787750) so the user doesn't lose track that there's a pending confirmation dialog.

File: client/my-sites/stats/activity-log-day/index.jsx (hunk 3 above)
Comment (eliorivero) [reply client/my-sites/stats/activity-log-day/index.jsx]: > this isEmpty() check may be redundant.

Good catch. I've removed the isEmpty.

> what is the type of requestedRewind?

It's a string. It's added in the prop types.

**Comment by eliorivero** [comment]
In 71527f62a42ab8a76d7b7a82faedd7241bbfcb62:

- revert FoldableCard to the way it was before
- restored ability for users to always expand/collapse day
- on card collapse, Rewind dialog will be dismissed, no matter if it was started through day header button or item within day.

blue

File: client/my-sites/stats/activity-log-day/index.jsx [hunk 5]
```diff
@@ -144,47 +186,76 @@ class ActivityLogDay extends Component {
 			requestRestore,
 			rewindConfirmDialog,
 			siteId,
+			tsEndOfSiteDay,
 		} = this.props;
 
-		const hasLogs = ! isEmpty( logs );
+		const hasLogs = ! isEmpty( logs ),
+			rewindHere = this.state.rewindHere,
+			dayExpanded = this.state.dayExpanded ? true : rewindHere;
```
Comment (dmsnell) [inline client/my-sites/stats/activity-log-day/index.jsx]: note that according to our style guides we're putting these on separate lines. the `vars` get grouped but not the `let`s and `const`s

```js
const hasLogs = ! isEmpty( logs );
const { rewindHere } = this.state;
const dayExpanded = this.state.dayExpected ? true : rewindHere;
```

File: client/my-sites/stats/activity-log-day/index.jsx [hunk 6]
```diff
@@ -144,47 +186,76 @@ class ActivityLogDay extends Component {
...
+						applySiteOffset={ applySiteOffset }
+						disableRestore={ disableRestore }
+						hideRestore={ hideRestore }
+						key={ log.activityId }
+						log={ log }
+						requestRestore={ requestRestore }
+						siteId={ siteId }
+					/>,
+				];
+			} );
```
Comment (dmsnell) [inline client/my-sites/stats/activity-log-day/index.jsx]: I'm curious about our use of `let hasConfirmDisalog` here and whether we could get away with more basic assignment as a `const`. what is our purpose of this code? in many cases when we are iterating over a list of things and carrying forth some value what we have is a _reduce_ operation over the list. we supply a function which takes the previous return value and gets the next value and that loops until the end. in this case, we might rewrite this as so…

```js
const [ activityItems, hasConfirmDialog ] = logs.reduce( ( [ items, hasConfirmDialog ], log ) => {
	const restoreThis = log.activityId === requestedRestoreActivityId;

	return [
		[
			...items,
			restoreThis && rewindConfirmDialog,
			<ActivityLogItem … />
		],
		hasConfirmDialog || ( restoreThis && ( … ) )
	];
}, [ [], false ] );
```

We could also use an object as the _accumulator_, the big that the reducer returns and passes along to the next iteration. With this pattern we're never mutating any variables and we can focus on moving from one step to the next instead of thinking more globally (considering `hasConfirmDialog` here).

Comment (dmsnell) [reply client/my-sites/stats/activity-log-day/index.jsx]: Actually the more I look at it, why is `hasConfirmDialog` inside of this iteration anyway? It doesn't appear to be related to building the items at all and so maybe we could move it out into another computation.

```js
const hasConfirmDialog = logs.some( ( { activityId, activityTs } ) => (
	restoreThis &&
	(
		tsEndOfSiteDay - DAY_IN_MILLISECONDS <= activityTs &&
		activityTs <= tsEndOfSiteDay
	)
) );

const items = flatMap( logs, log => [
	log.activityId === requestedRestoreActivityId && rewindConfirmDialog,
	<ActivityLogItem
		…
	/>
] );
```

File: client/my-sites/stats/activity-log-day/index.jsx (hunk 5 above)
Comment (eliorivero) [reply client/my-sites/stats/activity-log-day/index.jsx]: Thanks, I've updated this. I wasn't aware of this guideline and will keep it mind in the future.

File: client/my-sites/stats/activity-log-day/index.jsx (hunk 6 above)
Comment (eliorivero) [reply client/my-sites/stats/activity-log-day/index.jsx]: I didn't want to create an additional loop for this. I know it's not related, but given that we might have a lot of items in a day, I didn't want to go over the same loop again.
I'm also aware it will be more descriptive, but the only reason driving my decision is to make as few calculations as possible.
If you consider that being more descriptive outweighs running the same loop again then I'll make the change.

Comment (dmsnell) [reply client/my-sites/stats/activity-log-day/index.jsx]: I'd say let's generally be careful in assuming that something will be a problem. We might have up to a thousand activities here, right? So iterating over a thousand things is normal - could be problematic, may not be. Tens of thousands or millions for sure, hundreds probably not.

Maintainability is far more important to me and the general saying is that we spend 80% of our time _reading_ code; therefore, I think it's easy to justify writing the code _first_ in a way that makes it clear what we want or intend on accomplishing and waiting to see if performance is a problem before obscuring the code for the name of speed.

We can note too that the first `.some()` loop should be quite fast and on average will only iterate through half the list (assuming that we have at least one restore point per day and that restores are equally likely to occur at any time). Probably this loop will terminate early on in most iterations because we'll find the restore point we're looking for early in the list.

> If you consider that being more descriptive outweighs running the same loop again then I'll make the change.

So…definitely! :smile:

Another way to think about this is that if we suppose performance _does_ become an issue, how easily will the next person be able to come in, figure out what is supposed to happen, and then fix the issue? We have a number of optimizations available to us, but they are only possible if we can make specific assumptions about the code and its purpose

Comment (eliorivero) [reply client/my-sites/stats/activity-log-day/index.jsx]: Updated in https://github.com/Automattic/wp-calypso/pull/18722/commits/e09f5df96dc070560ec5b83ce86a5ab3fbfe0172
Thanks for the review 👍

File: client/my-sites/stats/activity-log-day/index.jsx [hunk 7]
```diff
@@ -144,47 +186,75 @@ class ActivityLogDay extends Component {
...
-							<ActivityLogItem
-								applySiteOffset={ applySiteOffset }
-								disableRestore={ disableRestore }
-								hideRestore={ hideRestore }
-								key={ log.activityId }
-								log={ log }
-								requestRestore={ requestRestore }
-								siteId={ siteId }
-							/>,
-						] ) }
```
Comment (dmsnell) [inline client/my-sites/stats/activity-log-day/index.jsx]: any thoughts on inlining the activities back in here? it would make it quicker to see what `render()` is rendering plus it would shrink the PR size 👍

Comment (eliorivero) [reply client/my-sites/stats/activity-log-day/index.jsx]: My bad. I've updated it now.

File: client/my-sites/stats/activity-log-day/index.jsx [hunk 8]
```diff
@@ -65,8 +87,28 @@ class ActivityLogDay extends Component {
...
+	closeDayOnly = () =>
+		this.setState( {
+			rewindHere: false,
+			dayExpanded: false,
+		} );
+
+	closeDayAndRewindDialog = () => {
+		const { recordTracksEvent, rewindRequestDismiss, siteId } = this.props;
+		recordTracksEvent( 'calypso_activitylog_restore_cancel' );
+		rewindRequestDismiss( siteId );
```
Comment (dmsnell) [inline client/my-sites/stats/activity-log-day/index.jsx]: The last thing I think I would recommend on this PR is that we don't have to make the component aware of the metrics we are tracking. The fact that we're tracking the cancellation is incidental to the job the UI is performing and we have a nice way of [extracting that logic](https://github.com/Automattic/wp-calypso/tree/110106d322fd8138e9f9d203ac46a0518df2fd82/client/state/analytics), which again can make for easier testing as we don't have to test both that the button does its job _and_ the metrics are tracking.

```js
const mapDispatchToProps = dispatch => ( {
	cancelRewind: siteId => dispatch( withAnalytics(
		recordTracksEvent( 'calypso_activitylog_restore_cancel' ),
		rewindRequestDismiss( siteId )
	) )
} )
```

Comment (eliorivero) [reply client/my-sites/stats/activity-log-day/index.jsx]: Addressed in https://github.com/Automattic/wp-calypso/pull/18722/commits/6f343353a11e557c8c5cfa349ae6890ef4418424
Thanks for the help with this.

File: client/my-sites/stats/activity-log-day/index.jsx [hunk 9]
```diff
@@ -178,13 +242,20 @@ class ActivityLogDay extends Component {
...
 		return {
 			isToday: now <= tsEndOfSiteDay && tsEndOfSiteDay - DAY_IN_MILLISECONDS <= now,
+			requestedRewind: getRequestedRewind( state, siteId ),
 		};
 	},
 	{
 		recordTracksEvent: recordTracksEventAction,
+		rewindRequestDismiss: rewindRequestDismissAction,
+		trackRewindCancel: siteId =>
+			withAnalyticsAction(
```
Comment (dmsnell) [inline client/my-sites/stats/activity-log-day/index.jsx]: any particular reason for the rename of this from `withAnalytics()`?

Comment (eliorivero) [reply client/my-sites/stats/activity-log-day/index.jsx]: I just followed what was done in this and other files in Activity Log project: imported actions are renamed to {action}Action.
I actually don't see much worth in doing this, but 1) I thought it was something that was agreed upon so I went with it and 2) since it's done in almost all cases I wanted to preserve consistency and did the same.

Comment (dmsnell) [reply client/my-sites/stats/activity-log-day/index.jsx]: It’s definitely not anything agreed upon. The only reason I think people rename those actions is because `eslint` yells at them for shadowing names.

We can get around it in other ways which are also prevalent in Calypso code:
 - choose names that don’t conflict when designing selectors and UI: for example `chooseSitePlan()` action and `choosePlan()` name in the component
 - refer to the actions via `this.props.actionName()` instead of restructuring them out

I tend to prefer the first solution because it encourages us to decouple the UI from the state system. That is, the interface for the specific UI element is usually much more generic than we are thinking when we are building it. A plan item may just need `onClick` or `selectPlan` while our actions tend to carry more contextual information which is provided and scaffolded in `connect()`

In general though it’s not assume any patterns are deliberate or any existing code should be an example. 😉
