### PR TITLE
Posts: Comment count doesn't update when adding a comment

### LINKED ISSUE #4889: Posts: comment count doesn't update when you add a reply
#### Steps to reproduce
1. Starting at URL: `/posts/{site}`
2. Click comment bubble if there are comments
3. Add a reply
4. Check that comment count in the post hasn't updated

We should update the count to reflect reality.

### PR DESCRIPTION
**Pull request by rodrigoi**
This PR includes the following changes:

`CommentButton` block component is now connected to the store to get the Total Comments Count. If the comments are not loaded into state, it defaults to a provided comment count.

When `tagName={ 'a' }` specified for `LikeButton` block component, it behaves like a link to the post stats page. Also, it was updated to extend `PureComponent` and `localize`.

`LikeButtonContainer` was updated to extend `PureComponent` and use `localize`. Also, it no longer omits `postId` on the props for the `LikeButton`.

`PostLikeButton` is a new component that configures a `LikeButtonContainer` to behave like a link to the post stats, and obtains the site's `slug` from the state.

`PostActions`, a new block component that encapsulates all the metadata for the post, and the actions the user can have on that metadata. It replaces the `getMeta()` function on `Post`.

The `getMeta()` function on `Post` has been replaced with a `PostActions` instance. Also, `Post` has been updated to use `localize`.

The `writeComment` action creator now dispatches a `COMMENTS_COUNT_RECEIVE` action, updating the total comments count when the user replies to a comment.

#### Steps to reproduce
1. Starting at URL: `/posts/{site}`
2. Click comment bubble if there are comments
3. Add a reply
4. Check that comment count in the post hasn't updated

Fixes #4889

### CODE REVIEW

File: client/blocks/post-actions/index.jsx [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+const showStats = site => site.capabilities	&&
+	site.capabilities.view_stats &&
+	( ! site.jetpack || site.isModuleActive( 'stats' ) );
+
+const PostActions = ( { className, post, site, toggleComments, recordEvent } ) => {
+	const { contentLinkURL, contentLinkTarget } = getContentLink( site, post );
+	const isDraft = post.status === 'draft';
+
+	const postRelativeTimeStatusOnClick = () => recordEvent( 'Clicked Post Date' );
+	const postTotalViewsOnClick = () => recordEvent( 'Clicked View Post Stats' );
```
Comment (dmsnell) [inline client/blocks/post-actions/index.jsx]: these are probably best defined in `connect()`

File: client/my-sites/posts/post.jsx [hunk 2]
```diff
@@ -375,13 +280,7 @@ module.exports = React.createClass( {
...
 					{ this.getPostImage() }
 					{ this.getContent() }
-					<footer className="post__info">
-						<PostRelativeTimeStatus post={ this.props.post } link={ this.getContentLinkURL() } target={ this.getContentLinkTarget() } onClick={ this.analyticsEvents.dateClick }/>
-						{
-							// Only show meta items for non-drafts
-							( this.props.post.status === 'draft' ) ? null : this.getMeta()
-						}
-					</footer>
+					<PostActions { ...{ site, post: this.props.post, toggleComments: this.toggleComments } } />
```
Comment (dmsnell) [inline client/my-sites/posts/post.jsx]: instead of passing `site` down here could I encourage us to pass a simple-data reference to a site and allow `connect#mapStateToProps()` to provide the actual site data to `PostActions`?

note also how in `PostActions` we're coupling the data of the `site` object in Calypso with the structure of the data the API returns (as indicated by `comment_count` instead of `commentCount` - we would ideally get the comment count from state directly)

Comment (rodrigoi) [inline client/my-sites/posts/post.jsx]: I'd rather keep this depending on the `site` object instead of just passing a `siteId` and depending on `getSite` because of the work that still to be done on the comments store. There's a lot of ways to simplify the component structure providing additional selectors for comments, but I'd rather keep that on a different PR.

**Comment by rodrigoi** [comment]
@lancewillett would you mind giving this a try?

**Comment by roundhill** [comment]
Noticed some wrapping issue with the views count:

screen shot 2017-03-21 at 11 53 35 am

It looks fine in production.

**Comment by lancewillett** [comment]
Confirmed fixed, using the live branch. 🎉  Thank you.

File: client/blocks/post-actions/index.jsx [hunk 3]
```diff
@@ -0,0 +1,107 @@
...
+import { recordGoogleEvent } from 'state/analytics/actions';
+import PostRelativeTimeStatus from 'my-sites/post-relative-time-status';
+import CommentButton from 'blocks/comment-button';
+import LikeButton from 'my-sites/post-like-button';
+import PostTotalViews from 'my-sites/posts/post-total-views';
+import utils from 'lib/posts/utils';
+
+const getContentLink = ( site, post ) => {
+	let contentLinkURL = post.URL;
+	let contentLinkTarget = '_blank';
```
Comment (roundhill) [inline client/blocks/post-actions/index.jsx]: I was informed in one of my PRs where I used external links that we should add `rel="noopener noreferrer`: https://github.com/Automattic/wp-calypso/pull/7680

**Comment by roundhill** [comment]
Seems to work well, besides a few small things I noticed I think this is looking good 👍

File: client/blocks/post-actions/index.jsx (hunk 3 above)
Comment (rodrigoi) [inline client/blocks/post-actions/index.jsx]: Fixed on 56eec55e1651418358255ee0721e27156ed73de2.

**Comment by rodrigoi** [comment]
@roundhill View counter alignment issue fixed on 60319bf08c84cdb73e888abbe02c38c86a5ab08d :)

**Comment by roundhill** [comment]
> @roundhill View counter alignment issue fixed on 60319bf :)

The wrapping is fixed, but I now noticed that the text isn't lining up properly:

screen shot 2017-03-22 at 9 28 22 am

**Comment by rodrigoi** [comment]
@roundhill adding a `padding-top: 2px` on 8c86b147940cf69f4289c1d35f7cea0d6bc7adb8. I think that's the best I can do without refactoring the `PostTotalViews` and `StatUpdateIndicator` components (which is something we should do anyway, but better on a new PR)

**Comment by roundhill** [comment]
Looks good! I say :shipit:
