### PR TITLE
Domains: Better price messaging for domain mappings

### LINKED ISSUE #28936: Domains: Remove mention of mapping cost from the UI
#### Steps to reproduce
1. Use a site with a paid plan, and the free domain credit unavailable (DWPO vs not does not matter)
2. Go to My Site ->Domains ->Add and select `Use a domain I own`
3. Choose the mapping option on the next page and follow the steps until checkout

#### What I expected
For the UI to indicate that mapping is free with the plan

#### What happened instead
Both at `https://wordpress.com/domains/add/use-your-domain` and `https://wordpress.com/domains/add/mapping` it indicates that domain mapping costs $13 a year. Once you reach the Checkout screen the amount changes to $0.

#### Screenshot / Video
use_your_own_domain_e280b9_kokkiestrialtestsite_e28094_wordpress_com
map_a_domain_e280b9_kokkiestrialtestsite_e28094_wordpress_com

#### Context / Source

Noticed while testing the new domain mapping for free feature.

Context: p7DVsv-5IE-p2

cc @aidvu

### PR DESCRIPTION
**Pull request by aidvu**
#### Changes proposed in this Pull Request

For users that can only have domains with plans, mappings are free, as we auto-add plans. Update the UI to show `Included/Free with paid plans` depending whether the user is DWPO or not.

#### Testing instructions

1. Use a site with DWPO user and no plan
2. Go to My Site ->Domains ->Add and select `Use a domain I own`
3. Make sure the message says included in paid plans
3. Choose the mapping option 
4. Should see `Included with paid plans`
5. Go to checkout, see price 0

---------------------------------------------------

1. Use a site with DWPO user and plan
2. Go to My Site ->Domains ->Add and select `Use a domain I own`
3. Make sure the message says free with your plan
3. Choose the mapping option 
4. Should see `Free with your plan`
5. Go to checkout, see price 0

---------------------------------------------------

1. Use a site with non-DWPO user and no plan
2. Go to My Site ->Domains ->Add and select `Use a domain I own`
3. Make sure the message shows the mapping cost
3. Choose the mapping option 
4. Should see the cost (13$)
5. Go to checkout, see price 13$

Fixes #28936

### CODE REVIEW

File: client/components/domains/use-your-domain-step/index.jsx [hunk 1]
```diff
@@ -355,6 +367,7 @@ export default connect(
 	state => ( {
 		currentUser: getCurrentUser( state ),
 		currencyCode: getCurrentUserCurrencyCode( state ),
+		domainsWithPlansOnly: currentUserHasFlag( state, DOMAINS_WITH_PLANS_ONLY ),
```
Comment (aidvu) [inline client/components/domains/use-your-domain-step/index.jsx]: @delputnam fun thing, this kind of never worked w/o the flag here. :stuck_out_tongue:

File: client/components/domains/domain-search-results/index.jsx [hunk 2]
```diff
@@ -106,7 +105,7 @@ class DomainSearchResults extends React.Component {
 					'{{small}}If you purchased %(domain)s elsewhere, you can {{a}}map it{{/a}} for free.{{/small}}',
 					{ args: { domain }, components }
 				);
-			} else if ( ! this.props.domainsWithPlansOnly || this.props.isSiteOnPaidPlan ) {
+			} else if ( ! domainsWithPlansOnly ) {
```
Comment (aidvu) [inline client/components/domains/domain-search-results/index.jsx]: We check if a mapping is free above with `isDomainMappingFree()`. So at this point, if not DWPO user, it will have the default cost.

**Comment by eoigal** [comment]
Works as outlined for me.

Fwiw, I toggled the DWPO by rem'ing the line `client/state/current-user/constants.js:3` and returning false early from the function `\calypso_domains_with_plans_only` in the file `/wp-content/mu-plugins/calypso-domains-with-plans-only.php`

**Comment by KokkieH** [comment]
Checked with DWPO user with no plan - saw domain mapping as included in paid plans.

Checked with DWPO user with plan and domain credit available, and plan and domain credit disconnected, - saw domain mapping as free with plan.

Checked non-DWPO user with plan - saw domain mapping as free with plan

Checked non-DWPO user no plan - saw mapping available at $13.

So works as expected.

I like the new copy as well.
