### PR TITLE
Security Settings: Don't send wordpress_api_key

### LINKED ISSUE #93698: Security Settings: WAF settings update error - wordpress_api_key: Please activate Akismet.
### Quick summary

When visiting `/settings/security/<site_url>` for a Jetpack connected site, with Akismet disabled, and the WAF module enabled, when updating and saving the Block list or Allow list settings, the request to `jetpack/v4/settings` is successful and the settings effectively update however the response is a `400` error with the following body:
```
{error: "some_updated", message: " wordpress_api_key: Please activate Akismet."}
```

### Steps to reproduce

1. Activate and connect Jetpack
2. Ensure the WAF is active from the security settings in the plugin UI
3. Proceed to `/settings/security/<site_url>` in Calypso
4. Toggle on or off the WAF Block list and/or Allow list settings
5. Review the UI handling and verify the request response

### What you expected to happen

The error notice should not occur and the UI state should update accordingly without the need to refresh the page.

### What actually happened

The update is initially recognized as a success with a corresponding success notice and change in a toggle state. Shortly after an error notice displays and the toggle is reverted to original state.
Screen Capture on 2024-08-19 at 14-04-11

### Impact

All

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by TimBroddin**
Fixes #93698

## Proposed Changes

The Security Settings form would try to update `wordpress_api_key` even when not rendering the Akimset section. The Akismet API key field only gets rendered on certain conditions:

Site is not Atomic & 

- Site has bought Jetpack Spam Protection
- Site has installed Akismet manually.

image

This PR excludes the `wordpress_api_key` field for all other conditions.

## Testing Instructions

1. Apply this PR
2. Visit http://calypso.localhost:3000/settings/security/youratomicsite 

Change some settings (for example `Always allow specific IP addresses`). No error should occur. 

Using Network Tools, verify that wordpress_api_key is not sent. 

Testing again using a Jurassic Tube JP site. Try with activated & deactivated Jetpack plugin.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/my-sites/site-settings/form-security.jsx [hunk 1]
```diff
@@ -144,9 +159,21 @@ const getFormSettings = ( settings ) =>
...
+};
 
 export default connectComponent(
-	localize( wrapSettingsForm( getFormSettings )( SiteSettingsFormSecurity ) )
+	localize( ( props ) => {
+		const WrappedSiteSettingsFormSecurity = wrapSettingsForm(
+			getFormSettings( props.includeAkismetFields )
+		)( SiteSettingsFormSecurity );
+
+		return <WrappedSiteSettingsFormSecurity { ...props } />;
```
Comment (jsnajdr) [inline client/my-sites/site-settings/form-security.jsx]: I'm afraid this won't work. The inner component will create a new wrapped component on each render, while a regular HOC does it only once, statically. The wrapped component will be losing local state and focus on each rerender.

A better solution would be `getFormSettings` accepting a second parameter (props) so that it can make decisions derived from the props. And the `includeAkismet` value would need to passed from outside somehow, so that `getFormSettings` can read it.

File: client/my-sites/site-settings/form-security.jsx [hunk 2]
```diff
@@ -119,6 +125,14 @@ const connectComponent = connect( ( state ) => {
 		'akismet'
 	);
 
+	const hasAkismetFeature = siteHasFeature( state, siteId, WPCOM_FEATURES_AKISMET );
+	const hasAntiSpamFeature = siteHasFeature( state, siteId, WPCOM_FEATURES_ANTISPAM );
+	const hasJetpackAntiSpamProduct =
+		getSiteProducts( state, siteId )?.filter( isJetpackAntiSpam ).length > 0;
```
Comment (jsnajdr) [inline client/my-sites/site-settings/form-security.jsx]: Here `.some( isJetpackAntiSpam )` is a bit nicer 🙂

Comment (TimBroddin) [reply client/my-sites/site-settings/form-security.jsx]: Thanks for the input. I adjusted accordingly.

File: client/my-sites/site-settings/form-security.jsx (hunk 1 above)
Comment (TimBroddin) [reply client/my-sites/site-settings/form-security.jsx]: Dang, you're right. I'll go the route of giving `getFormSettings` a second arg.

Comment (TimBroddin) [reply client/my-sites/site-settings/form-security.jsx]: Updated!

File: client/my-sites/site-settings/form-security.jsx [hunk 3]
```diff
@@ -119,6 +125,13 @@ const connectComponent = connect( ( state ) => {
 		'akismet'
 	);
 
+	const hasAkismetFeature = siteHasFeature( state, siteId, WPCOM_FEATURES_AKISMET );
+	const hasAntiSpamFeature = siteHasFeature( state, siteId, WPCOM_FEATURES_ANTISPAM );
+	const hasJetpackAntiSpamProduct = getSiteProducts( state, siteId )?.some( isJetpackAntiSpam );
+
+	const includeAkismetKeyField =
+		! isAtomic && ( hasAkismetFeature || hasAntiSpamFeature || hasJetpackAntiSpamProduct );
```
Comment (jsnajdr) [inline client/my-sites/site-settings/form-security.jsx:134]: This maybe deserves a comment that this condition, including the `settings.akismet` in `getFormSettings`, is exactly identical to the one in `SpamFilteringSettings` that decides whether the UI for the Akismet key is disabled.

**Review by jsnajdr — APPROVED** [review]
Looks good, thanks for fixing this :+1:
