### PR TITLE
fix: Delete User: Translate untranslated string

### LINKED ISSUE #49203: Delete User: Untranslated string
### Steps to reproduce the behavior

1. Go to `/people/edit/:site/:user`
2. Scroll to the bottom and select the option to attribute posts to a different user
3. Switch to a langauge other than English with Empathy mode off

#### What I expected to happen
Everything should be translated

#### What actually happened
Note that the "choose an author..." is untranslated

https://github.com/Automattic/wp-calypso/blame/ba397f3282601531876a2bb31f618b6274e0eeba/client/my-sites/people/delete-user/index.jsx#L128

#### Browser / OS version
Firefox, macOS Big Sur

#### Is this specific to the applied theme? Which one?
N/A

#### Does this happen on simple or atomic sites or both?
N/A

#### Is there any console output or error text?
N/A

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Captura de Tela 2021-01-22 às 09 44 50

### PR DESCRIPTION
**Pull request by sarayourfriend**
#### Changes proposed in this Pull Request

* Translate untagged string

#### Testing instructions

Captura de Tela 2021-01-25 às 10 06 08

* Verify the translated string is tagged and still works

Fixes #49203

### CODE REVIEW

File: client/my-sites/people/delete-user/index.jsx [hunk 1]
```diff
@@ -125,7 +125,7 @@ class DeleteUser extends React.Component {
 	getAuthorSelectPlaceholder = () => {
 		return (
 			<span className="delete-user__select-placeholder">
-				<User size={ 26 } user={ { name: /* Don't translate yet */ 'Choose an author…' } } />
```
Comment (sixhours) [inline client/my-sites/people/delete-user/index.jsx:128]: Wut. 😆 I have no idea why this is the way it is.

File: client/my-sites/people/delete-user/index.jsx [hunk 2]
```diff
@@ -125,7 +125,7 @@ class DeleteUser extends React.Component {
...
+				<User size={ 26 } user={ { name: this.props.translate( 'Choose an author…' ) } } />
```
Comment (sixhours) [inline client/my-sites/people/delete-user/index.jsx:128]: I think this is fine! I'm not sure why we wouldn't have wanted to translate the value here. It might be worth pinging for an i18n review.

**Review by sixhours — APPROVED** [review]

File: client/my-sites/people/delete-user/index.jsx (hunk 2 above)
Comment (sarayourfriend) [reply client/my-sites/people/delete-user/index.jsx:128]: It looks like this code is from 2 years ago... maybe this was just a new feature and we weren't planning to roll it out and this was missed? Just guessing there though.

**Review by tyxla — APPROVED** [review]
I don't see why this should be untranslated. Nice catch, LGTM 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5475117

Thank you @saramarcondes for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5475117).
