### PR TITLE
Plugin Details: Retrieve product list when plugin is not found on WPorg

### LINKED ISSUE #64161: [Bug]: Not possible to purchase recently added marketplace plugins
### Quick summary

It's not possible to view the plugin details page (the one with the buy button) immediately after a marketplace plugin has been added, if you already have visited the marketplace recently, however it is possible to see it in search results.

### Steps to reproduce

1. View the marketplace page
2. Add a new paid marketplace plugin (devs only)
3. View the marketplace page
4. Search the plugin
5. Click on the plugin

### What you expected to happen

The plugin details page (https://wordpress.com/plugins/:plugin-slug/:site) to load and be populated with data about the plugin, including a nice big buy button

### What actually happened

The plugin details page is blank and never changes, there's a request for plugin details to the dotorg api, which doesn't work as the plugin isn't kept there.

### Context

Found while adding a marketplace plugin, see p1653572554097819-slack-C029JEQRVRT

### Browser

_No response_

### Simple/Atomic

_No response_

### Other notes

This is caused by checking in the cached productList state for the plugin which doesn’t contain the new plugin yet.

_Perhaps_ [this persist](https://github.com/Automattic/wp-calypso/blob/861d28d49a6aff3dbda1b9a97ca135f19659cf34/client/my-sites/plugins/plugins-browser/index.jsx#L221) is the problem 

### Reproducibility

Consistent

### Severity

_No response_

### Available workarounds?

Yes, difficult to implement

### Workaround details

Clear the IndexedDB using browser dev tools, or open a new browser or incognito/private window.

### PR DESCRIPTION
**Pull request by WBerredo**
#### Proposed Changes

Stop using the persistent mode on QueryProductsList when the plugin is not found on WP.org.

It should reload the product list when the plugin is not found on WP.org repository, which might mean the current product list is out of date.

#### Testing Instructions

- Open the Browser dev tools and go the `Network` tab
-  Go to a plugin details page (`/plugins/{plugin_slug}`) of a an existing plugin. Ex: `/plugins/woocommerce`
- It should show the plugin and don't make any requests to the products list (`https://public-api.wordpress.com/rest/v1.1/products`)
- Go to a non-existent plugin details page, it should emulate a recently added plugin. Ex: `/plugins/abc`
- The page should be blank. (To be addressed by the follow up: #64872)
-  You should see a request to the products list (`https://public-api.wordpress.com/rest/v1.1/products`)

---

Fixes #64161

### CODE REVIEW

File: client/my-sites/plugins/plugin-details.jsx [hunk 1]
```diff
@@ -94,6 +95,10 @@ function PluginDetails( props ) {
 	const isWporgPluginFetched = useSelector( ( state ) =>
 		isWporgPluginFetchedSelector( state, props.pluginSlug )
 	);
+	const wporgPluginError = useSelector( ( state ) =>
+		isWporgPluginErrorSelector( state, props.pluginSlug )
+	);
+	const wporgPluginNotFound = wporgPluginError?.response?.status === 404;
```
Comment (epeicher) [inline client/my-sites/plugins/plugin-details.jsx:101]: Minor question, what do you think about adding that logic to the selector and renaming it to something like `isPluginFound` or something around that line? Just to avoid having this logic in the component.

**Review by epeicher — APPROVED** [review]
Thanks for the detailed testing steps. I have tested it and works as advertised. LGTM!

I have left a question to see your opinion but it is not a blocker so feel free to merge it and 🚢 it!

File: client/my-sites/plugins/plugin-details.jsx (hunk 1 above)
Comment (WBerredo) [reply client/my-sites/plugins/plugin-details.jsx:101]: We have a similar selector called `isWporgPluginFetchedSelector` which can be confusing with `isWporgPluginFoundSelector`. And this selector cannot be used here because it tells nothing about the status code returned.
