### PR TITLE
Media: Preserve media order by uploading in series

### LINKED ISSUE #333: Editor: Media: gallery order is wrong in the edit details view
When I drag several images in order into the media library modal, the numbering is correct but the image order is all jumbled:

e6c5d6da-862f-11e5-90b6-caae789b3499
<sup>Tested with Chrome 46.0.2490.80 on Mac OS X 10.10.5</sup>

In the edit details view, the images are displayed in the order they appear in the media library and not in the numbered order:

369f66da-8630-11e5-8952-5edbf05c8350
<sup>This image should appear 6th (see screenshot above), but appears first here. Tested with Chrome 46.0.2490.80 on Mac OS X 10.10.5</sup>

Outside of these two views (i.e. in the preview/reorder tabs and in the post after the gallery is inserted), the order goes back to the expected numbered ordering.

### PR DESCRIPTION
**Pull request by aduth**
Fixes #333 

This pull request seeks to upload media items in series, rather than parallel, so that media order is preserved. Currently, since all media uploads simultaneously, the order in which the items finish uploading is not always consistent with the original order in which they were dropped. By uploading in series, we can ensure that this order is always preserved.

order

__Testing instructions:__

1. Navigate to the [Calypso editor](http://calypso.localhost:3000/post)
2. Select a site, if prompted
3. Click the media button in the editor toolbar
4. Upload a single or multiple media items
5. Note that as the media items upload, the order never changes

### CODE REVIEW

File: client/lib/media/actions.js [hunk 1]
```diff
@@ -84,84 +90,94 @@ MediaActions.fetchNextPage = function( siteId ) {
...
-	const post = PostEditStore.get();
-	if ( post && post.ID && ! isPlainObject( file ) ) {
-		file = {
-			parent_id: post.ID,
-			[ isUrl ? 'url' : 'file' ]: file
+	// We offset the current time when generating a fake date for the transient
+	// media so that the first uploaded media doesn't suddenly become newest in
+	// the set once it finishes uploading. This duration is pretty arbitrary,
+	// but one would hope that it would never take this long to upload an item.
+	const baseTime = Date.now() + ONE_YEAR_IN_MILLISECONDS;
```
Comment (timmyc) [inline client/lib/media/actions.js]: That would be a very patient user to wait that long for an upload to complete.

File: client/lib/media/test/actions.js [hunk 2]
```diff
@@ -249,22 +252,36 @@ describe( 'MediaActions', function() {
...
+					parent_id: 200
+				} );
+			} );
+		} );
 
-			expect( mediaAddUrls ).to.have.been.calledWithMatch( {}, {
-				url: DUMMY_URL,
-				parent_id: 200
+		it( 'should upload in series', () => {
+			// An awkward test, but the idea is that at the point at which
```
Comment (timmyc) [inline client/lib/media/test/actions.js]: Pretty clever way to test this, nice.

**Comment by timmyc** [comment]
LGTM

File: client/lib/media/actions.js (hunk 1 above)
Comment (aduth) [inline client/lib/media/actions.js]: >That would be a very patient user to wait that long for an upload to complete.

Indeed! Maybe add an easter egg to give them a storage upgrade for such dedication :wink:
