### PR TITLE
Sidebar & JP Checklist: Fix links to JP wp-admin

### LINKED ISSUE #33277: Sidebar: WP Admin Jetpack link is incorrect
I believe this may have been introduced in #32790 (cc @sirreal)

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/nnn where nnn is a Jetpack site.
2. Click on the WP Admin link at the bottom of the sidebar.
3. You'll be redirected to https://nnn/wp-admin/?page=jetpack#/my-plan

This link is incorrect. While it loads the right page, the WordPress navigation does not support it:

image

It should be https://nnn/wp-admin/admin.php?page=jetpack#/my-plan

image

### PR DESCRIPTION
**Pull request by ockham**
#### Changes proposed in this Pull Request

Sidebar & JP Checklist: Fix links to JP wp-admin

#### Testing instructions

1. Starting at URL: `http://calypso.localhost:3000/plans/my-plan/:site` where `:site` is a Jetpack site.
2. Click on the WP Admin link at the bottom of the sidebar.
3. Verify that `https://:site/wp-admin/admin.php?page=jetpack#/my-plan` is opened
4. Go back to `http://calypso.localhost:3000/plans/my-plan/:site`
5. Locate the 'Return to WP Admin' button at the bottom of the checklist and click it.
6. Verify that it also takes you to `https://:site/wp-admin/admin.php?page=jetpack#/my-plan`

Fixes #33277 (see there for more detail)

### CODE REVIEW

File: client/my-sites/plans/current-plan/jetpack-checklist/index.js [hunk 1]
```diff
@@ -179,7 +179,7 @@ export default connect(
 		let wpAdminUrl = get( site, 'options.admin_url' );
 		wpAdminUrl = wpAdminUrl
 			? formatUrl( {
-					...parseUrl( wpAdminUrl ),
+					...parseUrl( wpAdminUrl + 'admin.php' ),
```
Comment (simison) [inline client/my-sites/plans/current-plan/jetpack-checklist/index.js]: Suppose we can (but asking anyway); can we trust this is always without trailing slash?

I've noticed this being done like so elsewhere:
```js
	import { untrailingslashit } from 'lib/route';

	let adminURL = get( selectedSite, 'options.admin_url', '' );
	if ( adminURL ) {
		adminURL = untrailingslashit( adminURL ) + '/admin.php?page=jetpack';
	}
```

Comment (ockham) [reply client/my-sites/plans/current-plan/jetpack-checklist/index.js]: There's quite a lot of precedent around the Calypso codebase that omits the slash (try searching for `admin_url + '`), so I'm assuming `admin_url` is guaranteed to always contain a trailing slash (or else we'd have seen a ton of bugreports by now :sweat_smile: ).

Comment (simison) [reply client/my-sites/plans/current-plan/jetpack-checklist/index.js]: Sounds good! :-)
