### PR TITLE
Checkout: Ensure correct thank-you page is shown to plan customers who don't transfer a domain

### LINKED ISSUE #37009: Unexpected post-purchase screen after upgrading before Launch
I found an unexpected post-purchase screen after upgrading a site before launching it.

#### Steps to reproduce
I was able to see this screen in two ways.

First, by following this path …

1. Create a new WP.com site, with a new account
2. Verify email
3. Click install plugin at /plugins
4. Click Business Plan required prompt at /plugins/upload
5. Complete checkout
6. See unexpected checkout success screen (see screenshot below)

And then …

1. Create a new WP.com site, with a new account
2. Verify email
3. Click Upgrade at /plans
4. Click "Let's do it!" on Site Privacy modal
5. Complete Checkout
6. See unexpected checkout success screen (see screenshot below)

#### What I expected

I expected to see a WPcom-branded screen like the following …

image

#### What happened instead

I saw this screen instead …

image

#### Browser / OS version

MacOS, Chrome.

### PR DESCRIPTION
**Pull request by sixhours**
#### Changes proposed in this Pull Request

* This PR reworks the checkout logic such that all cases except domain transfers see the standard check-out screen.

**Before**

Screen Shot 2019-11-08 at 12 03 54 PM

**After**

Screen Shot 2019-11-08 at 4 45 41 PM

#### Testing instructions

* Switch to this PR
* Create a brand-new WordPress.com account with a Free plan
* Go to Manage -> Plugins and click the upsell to Business
* Add a Business plan to the cart and check out
* You should see the "After" screenshot as a thank-you, not the "Before"

Fixes #37009

### CODE REVIEW

**Comment by sixhours** [comment]
@klimeryk can you confirm the new logic makes sense and will show the correct thank-you screen and actions for a domain transfer post-checkout? I'm not sure how to "fake" a domain transfer at checkout for testing purposes...

File: client/my-sites/checkout/checkout-thank-you/index.jsx [hunk 1]
```diff
@@ -422,21 +422,18 @@ export class CheckoutThankYou extends React.Component {
...
-					action: (
-						// eslint-disable-next-line
-						<a className="thank-you-card__button" onClick={ this.startTransfer }>
-							{ translate( 'Start Domain Transfer' ) }
-						</a>
-					),
-					description: translate( "Now let's get your domain transferred." ),
-				};
-			}
+		} else if ( wasDotcomPlanPurchased && delayedTransferPurchase && this.isNewUser() ) {
```
Comment (klimeryk) [inline client/my-sites/checkout/checkout-thank-you/index.jsx]: I'd make it even simpler: just check for `delayedTransferPurchase`. `isNewUser` has a weird check to see if the user was created in the last 2 hours - not sure why it's needed here. Definitely should _not_ control if we show this Thank you page or not. And you can purchase a transfer in without a plan, so the plan check does not seem to be needed as well, IMHO.

Comment (sixhours) [reply client/my-sites/checkout/checkout-thank-you/index.jsx]: Gotcha! I've updated the logic. :)
