### PR TITLE
Backup: fix retention setting confirmation modal

### LINKED ISSUE #88201: Jetpack Backup Retention Settings Confirmation Modal not disappearing
### Quick summary

The confirmation modal to change Jetpack settings persists unless you click the `cancel` button or refresh the page. 

### Steps to reproduce

1. Go to https://cloud.jetpack.com/settings/
2. Reduce backup retention period to 7 days. 
3. Click `confirm change` on the warning model which pops up: "You are about to reduce the number of days your backups are being saved. Backups older than 7 days will be lost."

### What you expected to happen

After confirming the change, the modal should disappear. 

### What actually happened

It persists until clicking the `cancel` button or refreshing the page. 

https://github.com/Automattic/wp-calypso/assets/26651984/1728bd09-6a1c-42a3-a84b-588a37e9f1ec

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by Initsogar**
Fixes https://github.com/Automattic/wp-calypso/issues/88201

Currently, we are not hiding the confirmation dialog when the retention update is completed, because we were always assuming the request status (returned by `getBackupRetentionUpdateRequestStatus` selector) is `unsubmitted`. This PR address to properly return the right value, so now if the retention is successful, we will close the confirmation dialog.

## Proposed Changes

* Register the `updateBackupRetentionRequestStatus` reducer as `state.rewind[].retention.requestStatus`
* Fix the `getBackupRetentionUpdateRequestStatus` selector to return the proper request status
* Update unit tests on reducer and selector to reflect this change
  * Removed a test case that is no longer necessary on `getBackupRetentionUpdateRequestStatus`selector tests

## Testing Instructions

* Spin up a Calypso or Jetpack Cloud Live Branch
* Pick a site with Jetpack VaultPress Backup with a plan that has storage limit. Ensure your site is not marked as angency.
* Navigate to `Settings`
* Try switching your retention period to a lower value, like from 30 days to 7 days.
* Ensure you see the confirmation dialog
* Click on `Confirm change`
* Ensure the dialog closes and it shows a success notice indicating the change is successful

### Unit tests
Ensure unit tests are passing:
* `yarn run test-client client/state/rewind`

## Demo

https://github.com/Automattic/wp-calypso/assets/1488641/967ecdb7-8b6c-4dba-b4f4-96db7f51f6e4

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/state/rewind/retention/test/reducer.js [hunk 1]
```diff
@@ -39,25 +39,25 @@ describe( 'updateBackupRetentionRequestStatus', () => {
...
 	test( 'should return PENDING status when retention update request action is initiated', () => {
 		// lets update backup retention for siteId:123 to 7 days.
 		expect(
 			updateBackupRetentionRequestStatus( undefined, updateBackupRetention( 123, 7 ) )
-		).toEqual( BACKUP_RETENTION_UPDATE_REQUEST.PENDING );
+		).toEqual( { requestStatus: BACKUP_RETENTION_UPDATE_REQUEST.PENDING } );
 	} );
 
-	test( 'should return SUCCESS status when retention update request action gets completed successfully', () => {
+	test( '1should return SUCCESS status when retention update request action gets completed successfully', () => {
```
Comment (rustamshaikh) [inline client/state/rewind/retention/test/reducer.js]:
```suggestion
	test( 'should return SUCCESS status when retention update request action gets completed successfully', () => {
```
Sorry for the nit :)

**Review by rustamshaikh — APPROVED** [review]
Works as expected, verified with my test site, thanks @Initsogar for fixing this 👍

File: client/state/rewind/retention/test/reducer.js (hunk 1 above)
Comment (Initsogar) [reply client/state/rewind/retention/test/reducer.js]: Thanks! I added that `1` unintentionally 😅
