### PR TITLE
Tracking: Improve selected sign up domain origin

### LINKED ISSUE #95225: Stepper Tracking: incorrect signup_domain_origin for Skip Domain + Free Plan scenarios
👋 Hi Team, 

I noticed that in the Stepper onboarding flow, the "**_Skip Domain + Free Plan_**" scenarios are incorrectly logging `signup_domain_origin` property for `calypso_signup_complete` event. This should be logged as `choose-later`, but the Stepper flow is logging it as `free`. See the recordings and details below. This issue does not occur in the Classic onboarding flow.

- Stepper: https://wordpress.com/setup/onboarding/es/?ref=seahtest
- Classic: https://wordpress.com/start/onboarding/es/?ref=seahtest

**Select .blog domain > Select “Elegir mi dominio más tarde” option in the right pane + Free Plan** ([recording](https://d.pr/v/dwcSOO)) 
- flow: onboarding
- is_new_user: true
- is_new_site: true
- has_cart_items: false
- signup_domain_origin: free 
- site_count: 0
- site_id_label: wpcom
- _en: calypso_signup_complete

https://github.com/user-attachments/assets/90d3b7c6-86e9-4fdc-9714-503ef58c8873

**Skip domain (click “Ver los planes de pago »”) + Free Plan** ([Stepper: recording](https://d.pr/v/NvMf2P))
- flow: onboarding
- is_new_user: true
- is_new_site: true
- has_cart_items: false
- signup_domain_origin: free
- site_count: 0
- site_id_label: wpcom
- _en: calypso_signup_complete

https://github.com/user-attachments/assets/d5be5a73-af9a-4c8b-89f8-b092a8606b12

### PR DESCRIPTION
**Pull request by renancarvalho**
Related to https://github.com/Automattic/wp-calypso/issues/95225
Fixes https://github.com/Automattic/wp-calypso/issues/95225

## Proposed Changes

* Use the value previously stored in `signupDomainOrigin` to log/track the correct domain selection.

## Why are these changes being made?

* We need to make sure we're tracking the correct domain selection.

## Testing Instructions

* Use live link (The link will be generated below)
* Test the scenarios described in this [issue](https://github.com/Automattic/wp-calypso/issues/95225) 

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/landing/stepper/declarative-flow/onboarding.ts [hunk 1]
```diff
@@ -113,9 +119,9 @@ const onboarding: Flow = {
 					if ( ! cartItems?.[ 0 ] ) {
 						// Since we're removing the paid domain, it means that the user chose to continue
 						// with a free domain. Because signupDomainOrigin should reflect the last domain
-						// selection status before they land on the checkout page, we switch the value
-						// to "free".
-						setSignupDomainOrigin( SIGNUP_DOMAIN_ORIGIN.FREE );
+						// selection status before they land on the checkout page, this value can be
+						// 'free' or 'choose-later'
```
Comment (renancarvalho) [inline client/landing/stepper/declarative-flow/onboarding.ts:123]: c/c @escapemanuele 
I think this is better, right?

Comment (escapemanuele) [reply client/landing/stepper/declarative-flow/onboarding.ts:123]: Sounds cool 👍

**Comment by skim1220** [comment]
@renancarvalho , I just did a quick test, and `signup_domain_origin` is now correctly logged with `choose-later` for Skip Domain + Free Plan scenarios 🥳
