### PR TITLE
Stats: Make `PageViewTracker` aware of the the selected site

### LINKED ISSUE #23108: Blog ID is reported incorrectly as null, undefined, or as incorrect site
When reporting tracks events we may get some non-sensical blog_id values when reporting from site specific routes. eg `/posts/:site`

We may be running into timing issues where:
- site id is not available yet
- site id is incorrect (this might be the last site we looked at)
- we shouldn't be looking at the current site id at all ( #16900 )

This line may be of some interest:
https://github.com/Automattic/wp-calypso/blob/d7b8e0a3d6e65bcd75d864f6122c9ba7ddc732cc/client/lib/analytics/super-props.js#L24

See p4qSXL-2hc-p2 (comment-5825) for additional examples.

### PR DESCRIPTION
**Pull request by Copons**
Contribute to fixing #23108 
H/t @rodrigoi for pointing me to `PageViewTracker`. 🙇 

Make `PageViewTracker` aware of the sites list and the selected site.

- If the selected site change, dispatch a new `analytics.pageView`, because the user switched site (e.g. passed from `comments/foo.wordpress.com` to `comments/bar.wordpress.com`), and requires a new page view tracking.

- Prevent dispatching a page view tracking if the sites list is empty. It means that it's too early in the loading of the page. The tracking will be automatically dispatched when the sites list updates, because the selected site will change (obtaining a value itself).

## Note

This PR is not enough for #23108.
On top of this, it will be required to replace all direct `analytics.pageView` calls with the `PageViewTracker` component.

## Context

Currently, the page view event tracking is dispatched immediately upon opening a page.
There are at least 2 cases where the tracks object contains an incorrect `blog_id` property:
- Calypso is loading uncached: the sites list is not ready yet and `selectedSiteId` is `null`.
- The user switches site: `analytics.pageView` is dispatched before the state update, and reports the previous `selectedSiteId`.

It might be possible to fix this with a centralized approach, but let's see if this is viable instead.

## Testing instructions

- Type `localStorage.clear(); indexedDB.deleteDatabase( 'calypso' );` to clear the cache.
- Type `localStorage.setItem('debug', 'calypso:analytics:tracks')` in the browser console to enable the debug.
- Load a page that uses `PageViewTracker`, for example the comments section: `comments/`.
- Make sure that there is a `calypso_page_view` event **without `blog_id`**, because the path defaulted to `comments/all`, and `blog_id: null` denotes All Sites.
- Pick a site and make sure there is a new page view event **including the correct `blog_id`**.
- Switch site and check that there is another page view event with the **new `blog_id`**.
- Now clear the cache and enable the debug again.
- Load a comments page with the site fragment (e.g. `comments/all/foo.wordpress.com`).
- Make sure the first (and only) page view event **contains the correct `blog_id`**.

### CODE REVIEW

**Comment by gwwar** [comment]
I think the overall approach could work here! Here are a few corner cases to consider:

- Are we still tracking pack views for site-less users? (To create one you can visit https://wordpress.com/start/account/ or from https://wordpress.com/domains/ )
- On non-site specific paths like for /me or reader, we don't want or actually need the blog_id, and so we can bypass waiting for sites to return.

**Comment by Copons** [comment]
> - Are we still tracking page views for site-less users? (To create one you can visit https://wordpress.com/start/account/ or from https://wordpress.com/domains/ )

@gwwar I was totally sure that site-less users had a site anyway, like, created behind the scene, which was listed in their site list but not displayed.
I actually realized this wasn't the case earlier while working on the "Welcome" notification.

I haven't given a try yet, but hopefully it's enough to also check if the user's site count is 0.

> - On non-site specific paths like for /me or reader, we don't want or actually need the blog_id, and so we can bypass waiting for sites to return.

Let's say that is step 2. 😄 
I guess it should be enough to extend `PageViewTracker` with an `omitBlogId` props.

Though, the idea was to test the waters and see how crazy was this approach (especially considered the necessity of update all `analytics.pageView` calls with the `PageViewTracker`.

**Comment by markryall** [comment]
Hmm - i've been looking at this somewhat related issue - #16902 - and it seems a pretty tricky problem.

The problem with using `PageViewTracker` everywhere instead of `analytics.pageView` calls (eg. in the controller functions) is that components need to be able to reconstruct the precise route that is being used to render them.  This means that anyone making changes to routing needs to also know that similar logic will exist elsewhere to try to infer the route that has resulted in the component being rendered.

This won't be a big deal for some simple cases but would be awkward for something like the multitude `/checkout` routes.

Calling `analytics.pageView` approach in controller functions is certainly going to exhibit this problem of sending null blog id or completely the wrong blog id more frequently.

**Comment by Copons** [comment]
In 3a20609 I've added a proof of concept of what I was saying in https://github.com/Automattic/wp-calypso/pull/23338#issuecomment-374631504.

The Comments section currently has a small bug in the path tracked by `PageViewTracker` which doesn't consider the `.../:post` route.

---

On an unrelated note: @gwwar omitting the blog ID is not as simple as I imagined, because it's part of a group of props that are generated automatically for analytics purposes.
So, we can add an `omit` prop, but it'll have a rather long way from the component to the actual place where it's needed. So much that I'd be more comfortable tackling it in a follow up PR.

**Comment by kwight** [comment]
3a20609 only seems to work if the URL is loaded directly; clinking a post to go to the post view from within the comments list won't trigger the stat.

**Comment by Copons** [comment]
@kwight good catch, and fixed in 0d46daa.
I totally didn't consider that.
To be fair, it's another shortcoming of `PageViewTracker` together with not tracking site changes (which is fixed for free by this PR).

**Comment by kwight** [comment]
Hm, this now double-reports when loading the post view direct from the URL (but works when navigating from within the UI 👍 ). It also now reports on clicking the Back button in the header – I have no idea if we should be counting those a page views or not 🙃 .

**Comment by Copons** [comment]
> Hm, this now double-reports when loading the post view direct from the URL

Can't reproduce 🤔 

This is my console from a clean-cache load of `comments/:status/:site/:post` (don't mind the manual log):

screen shot 2018-03-20 at 18 30 15

> It also now reports on clicking the Back button in the header

And also the Back button in the browser. :)
It was to be expected, and imho it is the correct behaviour (also, it's what happens in sections that use the direct `analytics` calls instead of the `PageViewTracker` component).

File: client/lib/analytics/page-view-tracker/index.jsx [hunk 1]
```diff
@@ -14,6 +14,8 @@ import { connect } from 'react-redux';
  * Internal dependencies
  */
 import { recordPageView } from 'state/analytics/actions';
+import { getSelectedSiteId } from 'state/ui/selectors';
+import { hasLoadedSites } from 'state/selectors';
```
Comment (gwwar) [inline client/lib/analytics/page-view-tracker/index.jsx]: Note that `hasLoadedSites` will return true if `state.sites.items` is not empty. We persist sites, so we can get into the case where we have this information, but the sites fetch for fresh data isn't completed yet. It is still possible for us to get into a state where we have some site information but not for the current siteSlug.

File: client/lib/analytics/page-view-tracker/index.jsx [hunk 2]
```diff
@@ -44,12 +48,21 @@ export class PageViewTracker extends React.Component {
...
+	}
+
 	queuePageView = () => {
-		const { delay = 0, path, recorder = noop, title } = this.props;
+		const { delay = 0, path, recorder = noop, sitesLoaded, title } = this.props;
 
 		debug( `Queuing Page View: "${ title }" at "${ path }" with ${ delay }ms delay` );
 
-		if ( this.state.timer ) {
+		if ( ! sitesLoaded || this.state.timer ) {
```
Comment (gwwar) [inline client/lib/analytics/page-view-tracker/index.jsx]: I wonder if we could update this check to instead verify that if the current path has a `siteSlug`, do we have a valid `selectedSiteId`?

Comment (gwwar) [reply client/lib/analytics/page-view-tracker/index.jsx]: Anothter option: If the path has a slug, maybe use `getSiteSlug( selectedSiteId )` to see if it matches the slug provided in the path?

File: client/lib/analytics/page-view-tracker/index.jsx (hunk 1 above)
Comment (Copons) [reply client/lib/analytics/page-view-tracker/index.jsx]: Uhm, wondering what could be the case though.
A cached `state.sites.items` should cover all sites owned by a user, and if they then go and create a new site, I assume it will be added to `state.sites.items` and cached consequently.

Comment (gwwar) [reply client/lib/analytics/page-view-tracker/index.jsx]: It would be more rare but not too uncommon. For example imagine I use multiple computers, or multiple browser profiles, where in profile A I do not log in for a week or so, and in profile B do a bunch of work adding sites, I log back into profile A, and voila! Isn't storing state fun :D

Comment (Copons) [reply client/lib/analytics/page-view-tracker/index.jsx]: Cache was a mistake!

**Comment by kwight** [comment]
> Can't reproduce 🤔

Oh! It had something to do with the site being sandboxed; with non-sandboxed sites, I don't see the issue either. ¯\_(ツ)_/¯

**Comment by Copons** [comment]
@gwwar Following your suggestion of taking advantage of the slug, I've updated the check in cacdfff.

Instead of checking if the sites list is loaded, we compare:
- The site fragment obtained from the current window location.
- The site slug obtained via `selectedSiteId`.

If the current path has no site fragment, we can assume it's an "all sites" page, and we can track the page view as is.
The only section that use `PageViewTracker` in the all page that I've found is **Themes**: it should work, with the correct `blog_id: null` value.

If the path's site fragment is different than the selected site slug, we can assume we're still loading the sites list, and so we'll repeat the check once the selected site ID updates until eventually fragment and slug will be the same and the event will be tracked with the correct `blog_id` value.

File: client/lib/analytics/page-view-tracker/index.jsx [hunk 3]
```diff
@@ -67,8 +81,19 @@ export class PageViewTracker extends React.Component {
 	}
 }
 
+const mapStateToProps = state => {
+	const selectedSiteId = getSelectedSiteId( state );
+	const selectedSiteSlug = getSiteSlug( state, selectedSiteId );
+	const currentSlug = getSiteFragment( get( window, 'location.pathname', '' ) );
+	const hasSelectedSiteLoaded = ! currentSlug || currentSlug === selectedSiteSlug;
```
Comment (gwwar) [inline client/lib/analytics/page-view-tracker/index.jsx]: @lamosty @jsnajdr are there any site conflict corner cases we should be aware of, or would the url normally redirect in that case?

File: client/lib/analytics/page-view-tracker/index.jsx [hunk 4]
```diff
@@ -67,8 +81,19 @@ export class PageViewTracker extends React.Component {
 	}
 }
 
+const mapStateToProps = state => {
+	const selectedSiteId = getSelectedSiteId( state );
+	const selectedSiteSlug = getSiteSlug( state, selectedSiteId );
+	const currentSlug = getSiteFragment( get( window, 'location.pathname', '' ) );
```
Comment (gwwar) [inline client/lib/analytics/page-view-tracker/index.jsx]: We might also need to do a check here to see if the fragment is a number. We do also accept the siteId directly.

File: client/lib/analytics/page-view-tracker/index.jsx (hunk 3 above)
Comment (lamosty) [reply client/lib/analytics/page-view-tracker/index.jsx]: Hmm, not sure. Any redirects that happen on site selection level are defined in `my-sites/controller/siteSelection`

**Comment by gwwar** [comment]
Okay tested with a siteless/domain only user, and I think we're okay with usages. Last things before 🚢 

- [ ] Fix when page tracking doesn't appear to fire with urls like `http://calypso.localhost:3000/comments/all/{siteId}
- [ ] Fix related tests

File: client/lib/analytics/page-view-tracker/index.jsx (hunk 4 above)
Comment (gwwar) [inline client/lib/analytics/page-view-tracker/index.jsx]: We need to check before calling a global var. This will throw otherwise in test envs.
```jsx
const currentSlug = typeof window === 'undefined' ? '' : getSiteFragment( get( window, 'location.pathname', '' ) );
```
