### PR TITLE
Sites Management Page: Fix sites thumbnail loader

### LINKED ISSUE #66616: Sites Management Page: Fix thumbnail loader
Currently the sites thumbnail loader does not fill the thumbnail container but only the site icon, it also shows the default mshots loading image when fetching a new thumbnail for an updated site.

### PR DESCRIPTION
**Pull request by vykes-mac**
#### Proposed Changes

* This PR fix loader so that it takes up the entire thumbnail instead of only the site icon
* This PR fix loader to remove the mshots default loader when site is updated and new screen shot is loaded without a page refresh.

**Bad Loader**

https://user-images.githubusercontent.com/47489215/184968326-b00208f5-9e46-490b-8883-e189986089f5.mov

https://user-images.githubusercontent.com/47489215/184968608-af911c34-03c8-459d-83f8-e820aaf1a57b.mov

**Fixed Loader**

https://user-images.githubusercontent.com/47489215/184969092-6d692b6d-0d67-409a-8815-168fdc162498.mov

#### Testing Instructions

1. Go to `/sites-dashboard`
2. Throttle internet speed using chrome network tab to simulate slower speed (clear cache)
3. Test mshots loader is not shown for thumbnail view by following instructions [here](https://github.com/Automattic/wp-calypso/pull/66534) to modify a site and see it updated in sites-dashboard without refreshing
4. Verify the loaders are shown as in the fixed videos above

*

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to https://github.com/Automattic/wp-calypso/issues/66616

### CODE REVIEW

File: packages/components/src/site-thumbnail/index.tsx [hunk 1]
```diff
@@ -57,14 +58,19 @@ export const SiteThumbnail = ( {
...
+						display: 'flex',
 					} }
 				>
 					{ children }
 				</div>
 			) }
 			{ src && ! isError && (
 				<img
-					className="site-thumbnail__image"
+					className={ removeMshotsDefaultLoader }
```
Comment (p-jackson) [inline packages/components/src/site-thumbnail/index.tsx]: We usually use the `classnames` library for this sort of logic (which is already imported in this file)

```suggestion
					className={ classnames( {
						'site-thumbnail__image': isLoading,
					} ) }
```

Comment (p-jackson) [reply packages/components/src/site-thumbnail/index.tsx]: I see we're doing the same sort of class name logic for the `site-thumbnail-loader` class above ...

File: packages/components/src/site-thumbnail/index.tsx [hunk 2]
```diff
@@ -57,14 +58,19 @@ export const SiteThumbnail = ( {
 					className={ loader }
 					style={ {
 						position: 'absolute',
+						width: '100%',
+						height: '100%',
+						alignItems: 'center',
+						justifyContent: 'center',
+						display: 'flex',
```
Comment (p-jackson) [inline packages/components/src/site-thumbnail/index.tsx]: Feels like these should all be dropped into a new CSS class

File: packages/components/src/site-thumbnail/use-mshots-img.tsx [hunk 3]
```diff
@@ -38,7 +38,7 @@ export const useMshotsImg = (
 		[ src, options, retryCount ]
 	);
 	const imgRef = useRef< HTMLImageElement >( null );
-	const [ isLoading, setIsLoading ] = useState( true );
+	const [ isLoading, setIsLoading ] = useState( false );
```
Comment (p-jackson) [inline packages/components/src/site-thumbnail/use-mshots-img.tsx]: I'm a little bit confused about why `isLoading` is initially set to `true`. I'm not super sure about how this hook works, but wouldn't it mean that the loading state isn't shown until we get a `404` returned by the server? But what if there's never a `404` because we get the image back first try? Wouldn't we still want to have the loading visual while the image is downloading?

Comment (p-jackson) [reply packages/components/src/site-thumbnail/use-mshots-img.tsx]: I see, maybe we don't want the loading state to appear for that first time round because otherwise we see the fallback first letter ...

**Review by p-jackson — DISMISSED** [review]
I think this might have introduced some sort of infinite loop in the image requesting code. When I observe the network tools it keeps on requesting more and more images, even though it looks like all the thumbnails have loaded in the UI.

CleanShot 2022-08-17 at 11 29 51@2x

When I clear the log it just keeps on requesting more 😆 

Maybe the change to the `if else` that controls the retry count introduced it?

File: packages/components/src/site-thumbnail/index.tsx (hunk 2 above)
Comment (vykes-mac) [reply packages/components/src/site-thumbnail/index.tsx]: yeah that make sense

File: packages/components/src/site-thumbnail/use-mshots-img.tsx (hunk 3 above)
Comment (vykes-mac) [reply packages/components/src/site-thumbnail/use-mshots-img.tsx]: setting loading to true initially shows the fallback state at first all times, removing it here was to set it in `onload` so that it would be fired when `onload` is called in the background but this cause the fallback state from earlier to be rendered at all. I think we should set is loading to true initially and also in the `onload` function to capture the background event scenario

**Review by p-jackson — APPROVED** [review]
Phew that's better, no more continuous image loading.
Mobile users might have been a bit shocked when they looked at their data bill 😅
