### PR TITLE
Help Center: disable the posting button when submitting

### LINKED ISSUE #79180: Duplicate posts/topics in Forums possible through Help Center
### Quick summary

Clicking the "Posting to forums" button, results in multiple posts being added to the forums. The "Post to forums" button should be disabled once clicked.

### Steps to reproduce

- Open the Help Center and search for a topic
- Click Still need help? 
- Select Forums, then add any more content
- Click the Post to forums button. 
- The button changes to “Posting to forums”, and if you click that once more, it will create a duplicate post (so you have it twice). 

### What you expected to happen

After clicking the button once, and the button text changes, the button shouldn't be able to be pressed again. 

### What actually happened

Clicking the button after it has been pressed creates a new, duplicate, forum topic. I assume (but haven't tested) it will create more the more you click on it, it seems the button should be disabled after the first press and it changes?

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by yoavf**
Fixes #79180

## Proposed Changes

* When AI answers are enabled (current default), the CTA button needs to be disabled while submitting the request, otherwise we can end up with multiple submissions.
* This also prevents the button from being disabled after the request is typed (and the debounce time has past), if we're still on the form page.

## Testing Instructions

* See #79180 

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: packages/help-center/src/components/help-center-contact-form.tsx [hunk 1]
```diff
@@ -515,7 +515,7 @@ export const HelpCenterContactForm = () => {
 				<section className="contact-form-submit">
 					<Button
 						isBusy={ isFetchingGPTResponse }
-						disabled={ isFetchingGPTResponse }
+						disabled={ isFetchingGPTResponse || isCTADisabled() }
```
Comment (alshakero) [inline packages/help-center/src/components/help-center-contact-form.tsx]: Can we move `isFetchingGPTResponse` inside `isCTADisabled` to keep all the reasons the button should be disabled in one place?

**Review by alshakero — APPROVED** [review]
Left one optional note. LGTM!

File: packages/help-center/src/components/help-center-contact-form.tsx (hunk 1 above)
Comment (yoavf) [reply packages/help-center/src/components/help-center-contact-form.tsx]: Makes sense, thanks!
While testing again I noticed another issue which was only visible when the debounce timer ended on the form screen - the button would be disabled in the contact form screen, while we were pre-fetching the response (which we don't really need to do, but is out of scope for this fix).
