### PR TITLE
All Sites View: Update Labels for Posts & Pages

### LINKED ISSUE #51904: All My Sites View: Posts and Pages labels do not adjust to multi-site view
### Steps to reproduce the behavior

1. Visit WP.com with an account that has multiple sites.
2. Use the nav sidebar to click on Posts or Pages screen.
3. Click Switch Site in sidebar.
4. Click All My Sites in sidebar.
5. See label that refers to single site view on the multi-site screen.

image

image

#### What I expected to happen

The label to update relative to the multi-site management context.

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

* Updates the `subHeaderText` of the All Sites View for posts and pages by using the plural of "site" 

#### Testing instructions

Visit `/posts` and `/pages` on an account with multiple sites and verify that the plural for "site" appears.

Screenshot 2021-04-14 at 18 52 49

Fixes #51904

### CODE REVIEW

File: client/my-sites/pages/main.jsx [hunk 1]
```diff
@@ -99,7 +99,11 @@ class PagesMain extends React.Component {
 					brandFont
 					className="pages__page-heading"
 					headerText={ translate( 'Pages' ) }
-					subHeaderText={ translate( 'Create, edit, and manage the pages on your site.' ) }
+					subHeaderText={
+						siteId
+							? translate( 'Create, edit, and manage the pages on your site.' )
```
Comment (a8ci18n) [inline client/my-sites/pages/main.jsx:104]: :ok: This change will be queued for retranslation. We'll use the existing translations in the meantime.

File: client/my-sites/posts/main.jsx [hunk 2]
```diff
@@ -82,7 +82,11 @@ class PostsMain extends React.Component {
 					brandFont
 					className="posts__page-heading"
 					headerText={ translate( 'Posts' ) }
-					subHeaderText={ translate( 'Create, edit, and manage the posts on your site.' ) }
+					subHeaderText={
+						siteId
+							? translate( 'Create, edit, and manage the posts on your site.' )
```
Comment (a8ci18n) [inline client/my-sites/posts/main.jsx:87]: :ok: This change will be queued for retranslation. We'll use the existing translations in the meantime.

**Review by sixhours — APPROVED** [review]
Works well, and I think this makes sense!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5900546

Thank you @Aurorum for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5900546).
