### PR TITLE
Hide non-public post types from post selector in editor

### LINKED ISSUE #4940: Editor: Link to existing content includes results for non-public post types
Edit by @marekhrabe: issue is **fixed** for dotcom sites, JP support coming soon!

---

**Steps to reproduce:**
1. Ensure at least one published "Feedback" exists, which can be managed from WP-Admin under Feedback > Feedback
2. Navigate to the [post editor](https://wordpress.com/post)
3. Select a site, if prompted
4. Click Add Link from the editor toolbar

**Expected result:**

Feedback should not be included in results since the post type is not public.

**Actual result:**

Feedback results are included.

**Suspected cause:**

The WP-Admin editor only [queries link results for post types which are registered as public](https://github.com/WordPress/WordPress/blob/a58ec423da502c779e37ed0e3b944f2a765a385c/wp-includes/class-wp-editor.php#L1317). The Calypso editor link dialog [queries for any post type](https://github.com/Automattic/wp-calypso/blob/912b3c3d3668aa82ac3a5eecf4c1c6412ef65fb2/client/components/tinymce/plugins/wplink/dialog.jsx#L343).

Further, this will likely require additional functionality from the REST API to either (a) allow querying a list of posts for public post types or (b) allow querying a list of posts for a comma-separated list of types. Currently you can only specify a single `type` or `any` from the `GET /sites/%s/posts` endpoint. If we change this to accept a comma-separated list of types, we'll need to enhance the editor to first retrieve public post types before displaying the selector results.

### PR DESCRIPTION
**Pull request by marekhrabe**
This will fix #4940

**To test:**

1. Apply D4766-code to your sandbox and make sure you are sandboxing the API in browser
2. Select a site that has some private post types with at least one post there (Feedback for example)
3. Create a new post (doesn't matter which type)
4. Write some content and create a link using the link modal

screen shot 2017-05-11 at 16 54 56

5. Make sure the list of suggested links contains only posts of public post types (post, page, portfolio project… and NOT feedback)
6. Search is not broken and the modal generally behaves as expected

**How it looks like:**

| Before | After |
| --- | --- |
| screen shot 2017-05-11 at 16 57 59 | screen shot 2017-05-11 at 16 59 12 |

### CODE REVIEW

**Comment by alisterscott** [comment]
Is there anything I can do to help move this along?

**Comment by marekhrabe** [comment]
@alisterscott Sorry I missed your note - most work is being done outside of this PR (wpcom backend, jetpack). We'll now focus on this project with more people from Samus to get this done soon.

File: client/my-sites/post-selector/selector.jsx [hunk 1]
```diff
@@ -444,11 +446,18 @@ const PostSelectorPosts = React.createClass( {
 
 export default connect( ( state, ownProps ) => {
 	const { siteId, query } = ownProps;
+
+	const queryWithVersion = { ...query };
+	if ( ! isJetpackSite( state, siteId ) || isJetpackMinimumVersion( state, siteId, '99' ) ) {
+		queryWithVersion.apiVersion = '1.2';
+	}
```
Comment (mcsf) [inline client/my-sites/post-selector/selector.jsx]: Nitpicky, but since const assignment and property assignment happen at the same time, I'd condense into:

```js
const apiVersion = ( ! … || … )
  ? '1.2'
  : undefined;
const queryWithVersion = { ...query, apiVersion };
```

Comment (marekhrabe) [inline client/my-sites/post-selector/selector.jsx]: @mcsf good idea, PR updated!

**Comment by jblz** [comment]
Looks good to me!  Nice work.

**Comment by mcsf** [comment]
I was still wondering about

> what the reason behind replacing `query` with `queryWithVersion` throughout `selector.jsx`.

* * *

Furthermore, I don't love the fact that, due to how `mapState` computes properties, `PostSelectorPosts` will never be able to skip rendering — since `nextProps.queryWithVersion` will always differ from `this.props.queryWithVersion`. 

Considering that this view is usually only rendered for a brief moment in a specific prompt context, it's not too serious. However, maybe in a follow-up PR, I would consider fixing. I see two ways to address this:
- either add a `shouldComponentUpdate` that knew what to look for (e.g. strict equality check for all props except for `queryWithVersion`, for which we would do a shallow per-property equality check)
- create a memoized cloner/append like so:

```js
( state, ownProps ) => {
  const { siteId, query } = …;
  const apiVersion = …;
  const queryWithVersion = appendVersion( query, apiVersion );
  return { /* props */ };
}
```

where `appendVersion` uses memoization, e.g.

```js
const appendVersion = createSelector(
  ( query, apiVersion ) => ( { ...query, apiVersion } ),
  ( query ) => query
); // (untested)
```

**Comment by mcsf** [comment]
My questions above shouldn't stop you from merging. LGTM

**Comment by marekhrabe** [comment]
I'll go ahead with this now and create a card in backlog to address updating better. Thanks for a good and detailed feedback on it :)
