### PR TITLE
Theme Showcase: Fix copy on upsell

### LINKED ISSUE #55988: Theme showcase incorrectly advertises theme uploads on Premium Plan
**To reproduce …**

1. Create a new test site and visit the theme showcase.
2. See issue in screenshot below.

**Issue …**

image

**What you should actually see …**

This should probably say "Business and Ecommerce" plans as those are the only two plans that allow theme uploads.

### PR DESCRIPTION
**Pull request by sixhours**
#### Changes proposed in this Pull Request

* Update wording on Theme Showcase upsell to reflect the correct upgrade path for uploading themes (Business and eCommerce, not Premium and Business)

**Before**

Screen Shot 2021-09-03 at 10 02 25 AM

**After**

Screen Shot 2021-09-03 at 10 02 11 AM

#### Testing instructions

* Switch to this PR on a free simple site
* Go to `/themes/[site]`
* You should see the upsell underneath the search area

Fixes #55988

### CODE REVIEW

**Review by ianstewart — APPROVED** [review]

File: client/my-sites/themes/single-site-wpcom.jsx [hunk 1]
```diff
@@ -27,7 +27,7 @@ const ConnectedSingleSiteWpcom = connectOptions( ( props ) => {
 					plan={ PLAN_PREMIUM }
 					customerType="business"
 					className="themes__showcase-banner"
-					title={ translate( 'Upload your own themes with our Premium and Business plans!' ) }
+					title={ translate( 'Upload your own themes with our Business and eCommerce plans!' ) }
```
Comment (a8ci18n) [inline client/my-sites/themes/single-site-wpcom.jsx:30]: :warning: This change will be queued for retranslation. We'll display the English text until then.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6545879

Thank you @sixhours for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6545879).
