### PR TITLE
Plans: /my-plan should show domains even if already upgraded 

### LINKED ISSUE #7177: Plans: /my-plan should show domains even if already upgraded
The intention of /my-plan is to showcase what the user can do with the plan that they purchased. Currently, if the user has added a domain upgrade to their plan, we remove any reference to domains being included in plans.

Regardless of whether or not a user has added a custom domain for their site, we should showcase that the domain is included in the plan, perhaps even highlighting the domain(s) they have associated with the site here.

#### Steps to reproduce
1. Go to /my-plan on a site with a plan but **no** custom domain upgrade
2. Notice that there's a nudge to add a custom domain in the "what your plan includes" text
3. Go to /my-plan on a site with a plan **and** a custom domain upgrade
2. Notice that there is no mention of domains being included in any of the plans

### PR DESCRIPTION
**Pull request by lamosty**
Fixes #7177. Shows that you own a custom domain as a part of plan upgrade on My Plan page. We need proper wording (and maybe custom design?).

## Testing Instructions

1. With Personal site, navigate to `/plans/my-plan` and claim your free domain;
2. After claiming the free domain, navigate back to `/plans/my-plan` and check whether it shows either "Custom Domain" feature box or "$yourDomain" feature box;
3. Upgrade to Premium and check whether it shows the same;
4. Upgrade to Business and check whether it shows the same.

## Issues

The main problem is that after you claim your free domain, it takes a while (say 5-10 mins) before we can detect you have a custom domain in code. However, we can detect immediately whether you have domain credit or not. I fixed this by showing a generic text "Custom Domain" if you don't have free domain credit and showing your domain name when you don't have domain credit + I can safely tell you have a custom domain.

However, there is a problem with this fix. Let's imagine the following scenario:

1. User upgrades to Personal plan and claims the free custom domain;
2. She then cancels this domain;
3. Now, she has no domain credit and no custom domain but still sees the "Custom Domain" feature box telling her that she has a custom domain because she is on the Personal plan.

I'm not sure how to fix this. Maybe with some special wording. Refer to screenshots below to better understand what I mean by "Custom Domain" feature box.

### With custom domain unknown/having no domain credit

selection_030

### With custom domain known

selection_032

### With claim your free domain (no changes from current implementation)

selection_031

cc @rralian @gwwar @meremagee @mtias @apeatling 

Test live: https://calypso.live/?branch=add/show-domain-upgrade-on-my-plan-page

Note: sorry about the failing tests. In `lib/site/utils`, I moved functions from global `export default { }` to individual function definitions so I could access the fns from within the same file. This broke parts of Calypso. However, things in this branch can still be tested just fine. I'll see what I can do about this next week.

### CODE REVIEW

**Comment by rralian** [comment]
> With custom domain unknown/having no domain credit

I'm not sure I understand this case. All of our plans include a custom domain, and I believe they always have. So how would we have a case where the user has not chosen a domain or have a domain credit available?

Should we differentiate between someone who has purchased a custom domain and someone who has used their domain credit by mapping a domain they already own?

I would suggest tweaking the copy a bit. Assuming we have a need for the case I was asking about ^^, my suggestion is this:

## unknown domain, but no domain credit

> ### Custom Domain
Your plan includes a free custom domain.

## known domain, no domain credit

> ### Custom Domain
Your plan includes the custom domain **lamostyrocksthelobster.com**, your own personal corner of the web.

## domain credit available

> ### Select Your Custom Domain
Your plan includes a free custom domain. Replace **lamostyrocksthelobster.wordpress.com** with a custom domain to personalize your site.
**[ Claim your free domain ]**

**Comment by gwwar** [comment]
Design wise, the information is useful, but I also think each box should have a useable call to action.
1. No Custom Domain (with or without credit) - A button/link to `/domains/add/:siteId:`
2. Has X Domains for site - A button/link to `/domains/manage/:siteId:`

**Comment by lamosty** [comment]
> Should we differentiate between someone who has purchased a custom domain and someone who has used their domain credit by mapping a domain they already own?

I think no.

> I'm not sure I understand this case. All of our plans include a custom domain, and I believe they always have. So how would we have a case where the user has not chosen a domain or have a domain credit available?

TL,DR: we have identical props for two different states of UI.

Let me clarify the issue we've got here: when user uses free credits to purchase custom domain, we don't have the info about the domain right away after completing the checkout. It takes a few minutes before we can say for 100% that user has a custom domain. These are the props on this state:

- `hasDomainCredit: false` (because user used domain credit for purchase a second ago)
- `domain: <user-site.wordpress.com>` (because Calypso doesn't know about user's custom domain right after its purchase, up to 5-10 minutes).

The system was set up to not show anything about domain on My Plan page if user doesn't have domain credit and show "Claim your free domain" otherwise. But as you can see, user doesn't need to have domain credit but still can have a custom domain mapped.

Now, the same props (hasDomainCredit: false and domain: <user-site.wordpress.com>) can happen in case user used free domain credit, then cancelled and then doesn't purchased a new domain. Two identical props for the two different UI states.

We'll probably need to show the same UI (wording) for both of these states. But what should the wording be? "Your plan includes a free custom domain." is good for the first case when user purchased custom domain but we don't know yet. However, it's not good (IMO) for the case when user used domain credit, then cancelled the free domain and then didn't purchase a new one.

To be honest, the second case should be pretty rare IMO so maybe we could use the "Your plan includes a free custom domain." wording and forget about this.

**Comment by lamosty** [comment]
I think the best solution is to have two different UIs:

1. If we know for 100% user has a custom domain, show him "Your plan includes the custom domain lamostyrocksthelobster.com, your own personal corner of the web." and button to manage the domain.

2. If user has a free domain credit, show him "Your plan includes a free custom domain. Replace lamostyrocksthelobster.wordpress.com with a custom domain to personalize your site." with button to claim the free domain.

It's the most straightforward solution without the complexities. The only downside of it is that after claiming or purchasing a domain, we won't show any mention of a domain on My Plans page, until we get new data from server and are 100% user has custom domain. That's about 5-10 minutes from my testing but only after full reload, looks like.

File: client/lib/site/utils.js [hunk 1]
```diff
@@ -175,9 +175,22 @@ export default {
 	},
 
 	/**
+	 * Returns the supplied URL without the initial http(s).
+	 * @param  {String}  url The URL to remove http(s) from
+	 * @return {?String}     URL without the initial http(s)
+	 */
+	withoutHttp( url ) {
```
Comment (lamosty) [inline client/lib/site/utils.js]: This fn is not used in the PR but I think it's a good addition to Calypso as I've seen `.replace( /^https?:\/\//, '' )` on too many places.

Comment (gwwar) [inline client/lib/site/utils.js]: Could you move this into a separate janitorial PR

File: client/lib/site/utils.js [hunk 2]
```diff
@@ -172,5 +172,31 @@ export default {
...
+	 * Checks whether a site has a custom mapped URL.
+	 * @param  {Object}   site Site object
+	 * @return {?Boolean}      Whether site has custom domain
+	 */
+	hasCustomDomain( site ) {
+		if ( ! site || ! site.domain || ! site.wpcom_url ) {
+			return null;
+		}
+
+		return site.domain !== site.wpcom_url;
```
Comment (gwwar) [inline client/lib/site/utils.js]: This is OK for now, but should also be ported to https://github.com/Automattic/wp-calypso/blob/master/client/state/sites/selectors.js

File: client/my-sites/upgrades/checkout-thank-you/custom-domain-purchase-detail.jsx [hunk 3]
```diff
@@ -2,38 +2,68 @@
...
+		<PurchaseDetail
+			icon="globe"
+			title={ translate( 'Custom Domain' ) }
+			description={ translate(
+				'Your plan includes the custom domain {{em}}%(siteDomain)s{{/em}}, your own personal corner of the web.', {
+					args: { siteDomain: selectedSite.domain },
+					components: { em: <em /> }
+				}
+			) }
+			buttonText={ translate( 'Manage my domain(s)' ) }
```
Comment (gwwar) [inline client/my-sites/upgrades/checkout-thank-you/custom-domain-purchase-detail.jsx]: Let's stick with `Manage my domains`

File: client/my-sites/upgrades/checkout-thank-you/custom-domain-purchase-detail.jsx [hunk 4]
```diff
@@ -2,38 +2,68 @@
...
+			href={ `/domains/manage/${ selectedSite.slug }` }
+		/>;
+
+	const renderCustomDomainDetail = () => {
+		if ( hasCustomDomain( selectedSite ) ) {
+			return renderHasCustomDomain();
+		}
+
+		return null;
```
Comment (gwwar) [inline client/my-sites/upgrades/checkout-thank-you/custom-domain-purchase-detail.jsx]: We should fall back to renderCustomDomainDetail(). This renders nothing if I use my domain credit and cancel the domain.

**Comment by gwwar** [comment]
Looking good so far, this should be good to 🚢 after the used credits case w/ cancelled domain is fixed.

**Comment by artpi** [comment]
Very nice addition!
I tested it and works fine in all scenarios.

I have noticed following things:

My domain, *piszek.com* is mapped. However, phrasing suggested that its included. For less savvy customers that may make them think that it will be renewed along with wpcom plan, which is not the case.
screen shot 2016-08-10 at 10 07 19 am

Also, we could make this:

screen shot 2016-08-10 at 10 16 44 am

Even more suggestive with actual suggestion of a domain. We have this data already:
screen shot 2016-08-10 at 10 08 34 am


These are not blockers, just points :) The soon we ship it, the better  :)

**Comment by lamosty** [comment]
Thanks for the review, @gwwar and @artpi!

> My domain, piszek.com is mapped. However, phrasing suggested that its included. For less savvy customers that may make them think that it will be renewed along with wpcom plan, which is not the case.

Do you mean that for users who have been grandfathered to have domain mapping, this should show something else? Because if you renew the plan, the domain will be renewed too (that's how I understand it).

> Also, we could make this: [...] Even more suggestive with actual suggestion of a domain. We have this data already: [...]

Good idea. However, I'd need some design for this as I don't know how would it fit and align with all the other texts.

File: client/lib/site/utils.js (hunk 2 above)
Comment (lamosty) [inline client/lib/site/utils.js]: Will do in another PR with tests as well.

**Comment by artpi** [comment]
> Because if you renew the plan, the domain will be renewed too (that's how I understand it).

No, it will not. I have bought it using a completely different registrar and used domain mapping to make it work. We have a significant number of users that use this procedure:

- for domain TLDs we do not offer
- for domains not bought from us. It it impossible to transfer domain to us, so people have to use mapping.

**Comment by lamosty** [comment]
> No, it will not. I have bought it using a completely different registrar and used domain mapping to make it work. We have a significant number of users that use this procedure:

Oh, yep, I see, thanks. The problem is, I don't know whether we differentiate between a domain purchased through us or a mapped on. In `selectedSite` object, there are only `domain` (= `slug`) props and `options.unmapped_url` which is the site's wp.com URL.

File: client/my-sites/upgrades/checkout-thank-you/custom-domain-purchase-detail.jsx (hunk 4 above)
Comment (lamosty) [inline client/my-sites/upgrades/checkout-thank-you/custom-domain-purchase-detail.jsx]: Sorry, I don't follow. What should I render if user has no domain credit and no custom domain?

This? "Custom Domain" --- "Your plan includes a free custom domain.". If yes, that won't make sense if you used your domain credit and then cancelled the domain.

If you meant to render "Custom Domain" --- "Your plan includes the custom domain mysitewithoutcustomdomain.wordpress.com, your own personal corner of the web.", that, too, doesn't make sense in this case as "mysitewithoutcustomdomain.wordpress.com" is not a custom domain.

**Comment by lamosty** [comment]
Just checked and `selectedSite.options.is_mapped_domain` is `true` in both cases: if you have a domain mapping or if you used your free credits to purchase a `.com` domain through us.

Any ideas? Maybe adjust the wording a bit so it's neutral to both parties?

File: client/my-sites/upgrades/checkout-thank-you/custom-domain-purchase-detail.jsx (hunk 4 above)
Comment (gwwar) [inline client/my-sites/upgrades/checkout-thank-you/custom-domain-purchase-detail.jsx]: Mainly I want the users to still have a link to `domains/add`. It does sound like we need different copy for this.

I could defer also if we think this isn't important enough to cover. The user needs to contact us in support to get in this state.

**Comment by artpi** [comment]
Honestly, I would make an issue and ship the code you have - it's a bit seperate :)
But nice that you checked!

**Comment by gwwar** [comment]
Do you mind updating `Manage my domain(s)` to `Manage my domains`? Retested, and I think this is good to 🚢

**Comment by lamosty** [comment]
> Do you mind updating Manage my domain(s) to Manage my domains?

Oh, I thought I've already done that. Maybe forgot to push from the other PC.

Thanks, gonna deploy!
