### PR TITLE
Gutenberg: fix bug in Publicize block

### LINKED ISSUE #28677: Gutenberg: Unable to delete the Publicize custom message to start over
As reported by @arunsathiya in p1HpG7-5Ta-p2:

> I am unable to remove all the text in the Publicize message. Cmd + A > Delete does not work. [Video showing this behaviour](https://cloudup.com/cpCLq_fxFQh).
>
> Trying to remove all the words on the Publicize message does not work, fails when the time to remove the first word comes. [Video showing this behaviour](https://cloudup.com/cNAPxPrxYyE).

It seems we'll need to be smarter about defaulting the message to post title, and change this to happen only if the user hasn't yet updated the custom message manually.

### PR DESCRIPTION
**Pull request by roccotripaldi**
Fixes #28677 by ensuring that an empty string can be used for the sharing message in the UI,
and if an empty string is used, ensure a place-holder shows up.

#### Changes proposed in this Pull Request

* Fixes a bug that would not allow folks to complete delete the sharing message when using the publicize block in the post editor

Screencast: https://cloudup.com/cRflteAVcjB

#### Testing instructions

* Use `npm run sdk gutenberg client/gutenberg/extensions/presets/jetpack -- --output-dir=../path/to/jetpack/docker-env` to build this branch into your local jetpack environment
* OR
* [Try this jurassic ninja link](https://jurassic.ninja/create/?gutenberg&gutenpack&shortlived&jetpack-beta&calypsobranch=fix/28677-handle-default-publicize-message&branch=master)
* Open the gutenberg editor on your site
* Publish a post, and in the pre-publish panel, ensure you can enter a blank sharing message 
* Ensure the placeholder text makes sense

Fixes #28677

### CODE REVIEW

File: client/gutenberg/extensions/publicize/form-unwrapped.jsx [hunk 1]
```diff
@@ -75,10 +86,14 @@ class PublicizeFormUnwrapped extends Component {
...
 				<div className="jetpack-publicize-message-box">
 					<textarea
-						value={ shareMessage }
-						onChange={ messageChange }
+						value={ this.getShareMessage() }
+						onChange={ this.onMessageChange }
 						disabled={ this.isDisabled() }
 						maxLength={ MAXIMUM_MESSAGE_LENGTH }
+						placeholder={ __(
+							"Write a message for your audience here. If you leave it blank, the post's title will be used."
```
Comment (ockham) [inline client/gutenberg/extensions/publicize/form-unwrapped.jsx]: What about setting the placeholder to the post title? This would somewhat imply the behavior that this string is now describing. (It would also reflect the Classic Editor's Publicize module's behavior.)

**Comment by michelleweber** [comment]
Wee suggestion: "If you leave this blank, we'll use the post's title as the message."

File: client/gutenberg/extensions/publicize/form-unwrapped.jsx [hunk 2]
```diff
@@ -44,14 +50,19 @@ class PublicizeFormUnwrapped extends Component {
 		return ! formEnabled;
 	}
 
+	getShareMessage() {
+		const { shareMessage, defaultShareMessage } = this.props;
+		return this.state.hasEditedShareMessage ? shareMessage : defaultShareMessage;
```
Comment (ockham) [inline client/gutenberg/extensions/publicize/form-unwrapped.jsx]: I don't think you actually need component state (`hasEditedShareMessage`) to determine what to display here. The information whether the message has been manually edited should be fully contained in `shareMessage` and `defaultShareMessage`. You can probably just

```jsx
return shareMessage !== defaultShareMessage ? shareMessage : '';
```

and drop `onMessageChange` altogether (just reverting to using `messageChange` for the `textarea`'s `onChange` prop.

Comment (ockham) [reply client/gutenberg/extensions/publicize/form-unwrapped.jsx]: ^ This should also fix the [bug](https://github.com/Automattic/wp-calypso/pull/28695#pullrequestreview-176525372) I found

File: client/gutenberg/extensions/publicize/form-unwrapped.jsx (hunk 1 above)
Comment (ockham) [reply client/gutenberg/extensions/publicize/form-unwrapped.jsx]: > What about setting the placeholder to the post title?

(I.e. to `defaultShareMessage`)

File: client/gutenberg/extensions/publicize/form.jsx [hunk 3]
```diff
@@ -23,13 +23,14 @@ const PublicizeForm = compose( [
 	withSelect( select => {
 		const meta = select( 'core/editor' ).getEditedPostAttribute( 'meta' );
 		const postTitle = select( 'core/editor' ).getEditedPostAttribute( 'title' );
-		const message = get( meta, [ 'jetpack_publicize_message' ], '' ) || postTitle || '';
+		const message = get( meta, [ 'jetpack_publicize_message' ], '' ) || '';
```
Comment (ockham) [inline client/gutenberg/extensions/publicize/form.jsx]: You can drop the last `|| ''` here

File: client/gutenberg/extensions/publicize/form-unwrapped.jsx (hunk 1 above)
Comment (roccotripaldi) [reply client/gutenberg/extensions/publicize/form-unwrapped.jsx]: I think this may cause a little frustration for first time publicize users. Sure, you and I would understand the directness of displaying the post title when the field is blank, because we use publicize all the time. Someone who is using Publicize for the first time would appreciate a bit more information describing the situation.

File: client/gutenberg/extensions/publicize/form-unwrapped.jsx (hunk 2 above)
Comment (roccotripaldi) [reply client/gutenberg/extensions/publicize/form-unwrapped.jsx]: I pushed a change in logic that fixes this bug in 4c78a14465f8319bcff0cd21eec908e7bfa06c4f. Your suggestion would work nicely if we decided to use the post title as the placeholder. I'd like to keep a more descriptive placeholder, so i had to shake up the logic a bit!

Comment (ockham) [reply client/gutenberg/extensions/publicize/form-unwrapped.jsx]: Yeah, I think it's not so much about the placeholder content rather than about different behavior upon first load -- it's true that with my suggestion, we'd be displaying the placeholder on first load (rather than the default message).

**Comment by tyxla** [comment]
Rebased and cleaned up the constructor. Ready for another review @ockham

File: client/gutenberg/extensions/publicize/form.jsx [hunk 4]
```diff
@@ -23,12 +23,14 @@ const PublicizeForm = compose( [
...
 		const meta = select( 'core/editor' ).getEditedPostAttribute( 'meta' );
 		const postTitle = select( 'core/editor' ).getEditedPostAttribute( 'title' );
-		const message = get( meta, [ 'jetpack_publicize_message' ], '' ) || postTitle || '';
+		const message = get( meta, [ 'jetpack_publicize_message' ], '' );
 
 		return {
 			connections: select( 'core/editor' ).getEditedPostAttribute(
 				'jetpack_publicize_connections'
 			),
+			meta,
```
Comment (ockham) [inline client/gutenberg/extensions/publicize/form.jsx]: Oops, seems like this sneaked its way back in during the rebase. No longer needed per #28689.

Comment (tyxla) [reply client/gutenberg/extensions/publicize/form.jsx]: 👍 Removed again in https://github.com/Automattic/wp-calypso/pull/28695/commits/71897bda68ebef092129f321e63d17f630ac08f1

**Comment by ockham** [comment]
Merging so this makes it into the release.
