### PR TITLE
Fix/upload plugin on automated transfer

### LINKED ISSUE #62928: Plugin Uploads / Atomic Transfer: Plugin upload installation fails when transferring private Simple sites
### Quick summary

***Since the process transfers the site to Atomic, users can try uploading the plugin again and it will not be impacted by this issue.***

Simple sites can transfer to the Atomic platform in various ways, one is by uploading a plugin manually via My Sites > Plugins > Upload.  

Uploading a plugin there initiates an Atomic transfer and the marketplace-styled installer. 

In the background, the site will transfer to Atomic successfully but the plugin installation process will fail.

Sometimes, the user may encounter an error while waiting for the plugin installer to finish on `https://wordpress.com/plugins/upload/SITE_DOMAIN`

`This URL should not be accessed directly. Please try to upload the plugin again. - Go to the the upload page`
Screen Shot on 2022-04-20 at 13:02:43

### Steps to reproduce

1. Start with a Simple site with an Atomic compatible plan
2. Set site to Private under My Sites > Settings > General
3. Navigate to My Sites > Plugins > Upload
3. Attempt to upload a plugin, such as Elementor, manually via a .zip file.
4. See error, check site's Installed Plugins to find the plugin was not installed

### What you expected to happen

Plugin to install and activate, no errors

### What actually happened

Errors, plugin did not install

### Context

Internal testing, p1650481191135179/1650469650.753789-slack-C036E4KFP2L

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

_No response_

### Browser, operating system and other notes

_No response_

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

After failure, user can try again and the plugin should install properly

### PR DESCRIPTION
**Pull request by sejas**
#### Description

Currently, there is an error when a user uploads a zip plugin on a simple site with Atomic compatibility. This PR fixes this issue #62928.

#### Proposed Changes

* Navigate to Thank you screen after uploading a zip plugin to a simple site.

#### Testing Instructions

* Grab any zip plugin. You can find one here: https://wordpress.org/plugins/
* On a simple site, buy a pro account 
* Navigate to Plugins > Upload
* Accept the notice about domain renaming
* Drop your zip plugin to start uploading it
* Wait until the process finishes
* Observe it finishes successfully and you see the thank you screen
* Go to Plugins > installed plugins and observe your installed plugin is active

#### Screenshots
Thank you Screen:
Screenshot 2022-06-09 at 11 42 24

Screencast:

https://user-images.githubusercontent.com/779993/172831009-839bd72a-47aa-4584-a4fa-8e44952415bf.mov

---

- Fixes #62928

### CODE REVIEW

File: client/my-sites/marketplace/pages/marketplace-plugin-install/index.tsx [hunk 1]
```diff
@@ -232,17 +232,23 @@ const MarketplacePluginInstall = ( { productSlug }: MarketplacePluginInstallProp
 	// Check completition of all flows and redirect to thank you page
 	useEffect( () => {
 		if (
+			// Default process
 			( installedPlugin && pluginActive ) ||
-			( atomicFlow && transferStates.COMPLETE === automatedTransferStatus )
+			// Tranfer to atomic using a marketplace plugin
```
Comment (wojtekn) [inline client/my-sites/marketplace/pages/marketplace-plugin-install/index.tsx]: There is a small typo in Tranfer -> Transfer here.

**Review by wojtekn — COMMENTED** [review]
@sejas I reviewed the code and I think that the change looks clean. Comments that explain conditions are making this code easier to understand 👍  I tested it on my local Calypso - the PR changed the behavior when the plugin installation fails - now it doesn't display "This URL should not be accessed directly. [...] error but displays the Thank You page.

I've tested the workflow a few times using Vimeo and Hello Dolly plugin. I was able to go through successfully through the process two times - one for Hello Dolly, and one for Vimeo. In both cases, I've got a proper Thank You page URL, with a plugin slug in the URL. I was able to use the button to go to the "Manage Plugin" page and my plugin was listed there.

However, a few times I've got a Thank You page that was looking like a false result - the page showed that plugin was installed, but instead of the plugin slug in the URL, I saw `null` in one case and `false` in another. In both cases, the plugin was not installed. I also spot the case in which my site was not migrated to Atomic, but I've got that Thank You page displayed. The links looked as follows:

http://calypso.localhost:3000/marketplace/thank-you/null/<WP SITE SLUG\>.wordpress.com
http://calypso.localhost:3000/marketplace/thank-you/false/<WP SITE SLUG\>.wordpress.com

Did you have a similar experience? Is it that we are only changing error handling when plugin installation occurs, and not the actual error that leads to plugin installation failure?

Also, should we clarify the testing steps and say that the site should be Private? Or is it not relevant?

File: client/my-sites/marketplace/pages/marketplace-plugin-install/index.tsx (hunk 1 above)
Comment (sejas) [reply client/my-sites/marketplace/pages/marketplace-plugin-install/index.tsx]: Thanks for your finding @wojtekn.

I've been able to reproduce the `null` on the URL. It seems to happen when I upload a zip plugin to a site that is already atomic. I'll fix it and ask for your review again.
Thank you!!

I've confirmed that the original issue, uploading zip plugins affects private and public sites. So the issue is not related to the visibility of the site.
Screenshot 2022-06-13 at 10 01 07

**Comment by sejas** [comment]
@wojtekn, I've found that the new issue you've seen was related to a recently transferred site.
The `automatedTransferStatus = useSelector...` is returning the latest value of the transfer until you refresh the page, in this case, `complete`, even if it's a new plugin installation.
I've changed the conditions to trigger the redirection to the thank you page.
Now everything should work fine. Can you review it again?

I've fixed the typo in the comment too.

Thank you!

**Review by wojtekn — APPROVED** [review]
@sejas thanks. Change looks good. I've tested it for both plugins I used before, and it worked fine each time.
