### PR TITLE
Themes: Allow WoA sites to purchase premium themes

### LINKED ISSUE #64119: [Bug]: Unable to purchase Premium theme
### Quick summary

Purchasing a Premium theme isn’t supported on limited atomic site

### Steps to reproduce

1. While on a limited atomic site with the Starter plan, go to My Site → Appearance → Themes
2. Go to Premium theme
3. Try purchasing a premium theme
4. The checkout page shows the purchase is not supported.

### What you expected to happen

The site should be able to purchase the theme without facing any issues.

### What actually happened

I wasn't able to purchase a premium theme.
I'm suspecting this could be a Starter plan issue.

### Context

_No response_

### Browser

_No response_

### Simple/Atomic

Atomic

### Other notes

_No response_

### Reproducibility

Consistent

### Severity

_No response_

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by obenland**
The theme showcase for Jetpack sites now also accounts for Atomic sites.

#### Proposed Changes

* Accounts for the subsection of Atomic sites when checking for Jetpack.
* Shows the wpcom theme showcase for Atomic sites.

#### Testing Instructions

* Go to [wordpress.com/themes/premium/](https://container-great-nightingale.calypso.live/themes/premium/) and select an Atomic site on a Personal or Free plan.
* Check that it shows the star icon upgrade banner between the price of the theme and the ellipsis menu:   image
* Click on the ellipsis menu and check that it now has a "Purchase" option (previously "Upgrade to Activate") image
* Click "Purchase" and verify that you can buy that theme.

Fixes #64119.

### CODE REVIEW

File: client/my-sites/themes/theme-options.js [hunk 1]
```diff
@@ -65,6 +66,7 @@ function getAllThemeOptions( { translate, blockEditorSettings } ) {
 			getJetpackUpgradeUrlIfPremiumTheme( state, themeId, siteId ),
 		hideForTheme: ( state, themeId, siteId ) =>
 			! isJetpackSite( state, siteId ) ||
+			isSiteWpcomAtomic( state, siteId ) ||
```
Comment (mreishus) [inline client/my-sites/themes/theme-options.js:69]: Makes sense. This works because the inverse of `(jetpack && !atomic)` is `(!jetpack || atomic)`, and here we're replacing "not jetpack" with "not standalone jetpack".

**Review by mreishus — APPROVED** [review]
LGTM. Fixes the issue of inappropriate "upgrade to activate" on atomic sites without unlimited premium themes (which links to a jetpack upgrade).

**What I see on prod**


**On this branch, I can purchase the theme.**
