### PR TITLE
People: Fixes RoleSelect issue with localStorage cleared

### LINKED ISSUE #3442: People: Handle cleared localStorage for invite people
After clearing `localStorage`, if a user goes to `/people/new/$site`, then the `RoleSelect` component does not properly work. Let's fix this and then go ahead and make sure validation and submission work properly as well.

Linking to #3172

### PR DESCRIPTION
**Pull request by ebinnion**
Fixes #3442

Previously, the RoleSelect did not work properly when going to `/people/new/$site` with a cleared `localStorage`. After some digging, this seems to have been because we were not re-fetching once site was set properly. :scream: 

This PR fixes that by ensuring that we fetch in `componentWillReceiveProps`. Note that while we call `this.fetchRoles()` each time we receive new props, we do not in fact fetch each time. If a site already has roles, `fetchRoles()` bails early.

To test:
- Checkout `update/people-invites-localstorage` branch
- Go to `/people/new/$site` where `$site` is a WP.com site
- In console, `localStorage.clear()`
- Refresh
- Ensure that all site roles load
- Go to `/people/team/$site` where `$site` is a WP.com or Jetpack site
- Ensure that roles load properly

cc @lezama for review

### CODE REVIEW

File: client/my-sites/people/role-select/index.jsx [hunk 1]
```diff
@@ -20,7 +20,7 @@ import sitesList from 'lib/sites-list';
 /**
  * Module variables
  */
-const debug = debugFactory( 'calypso:role-select' );
+const debug = debugFactory( 'calypso:my-sites:people:role-select' );
```
Comment (lezama) [inline client/my-sites/people/role-select/index.jsx]: :+1:
