### PR TITLE
Admin color: block layout render when still fetching (take 2)

### LINKED ISSUE #100959: WordPress.com Dashboard visual glitch
### Context and steps to reproduce

This was reported here: 9493798-zd-a8c

Left menu bar turns to a different color briefly upon login before returning to the Color Scheme that was chosen.
Occurs every time a user logs in. 

It doesn't happen with the default color scheme: 

https://github.com/user-attachments/assets/3cf5ea74-27b4-4641-a0b9-32c8e0c08b69

With other color schemes: 

https://github.com/user-attachments/assets/b65edf2e-d589-4f80-9af3-276713abf819

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Minor

### What other impact(s) does this issue have?

No revenue impact

### If a workaround is available, please outline it here.

No workaround as it doesn't impact the usage.

### Platform

Atomic, Simple

### PR DESCRIPTION
**Pull request by fushar**
Fixes DOTCOM-205
Fixes https://github.com/Automattic/wp-calypso/issues/100959

## Proposed Changes

This PR "solves" the issue where the user sees the default admin color scheme for a split second while  fetching the user's admin color. This happens when the redux store is empty during the first login. The fix is to not render the screen when this happens.

Note that this is only an "edge" case where the user first logs in. Afterwards, the admin color is in the redux store always and we never block the render anymore.

> [!NOTE]  
> This deliberately does not address the case when the user changes the admin color via `profile.php`.

> [!WARNING]  
> This is a re-take of https://github.com/Automattic/wp-calypso/pull/102591. The only difference is the last commit, where it makes use of the correct sidebar type enum from https://github.com/Automattic/wp-calypso/pull/102900.

### Before

https://github.com/user-attachments/assets/0d07d883-0f8f-419e-8219-edbe44aea4d2

### After

https://github.com/user-attachments/assets/80396059-43f1-447a-9398-da0e8bd9eba8

## Why are these changes being made?

Fixes visual bug.

## Testing Instructions

I found that the only reliable way to test these changes is to check out the branch locally, run Calypso locally, then add the `?flags=force-sympathy` query param.

1. Prepare a site with a non-default color scheme.
2. Run Calypso locally.
3. Go to `/home/:siteSlug?flags=force-sympathy`.
4. Notice the flash of color scheme from default to the actual.
5. Now, check out this PR's branch.
6. Repeat the above, verify that no flash occurs anymore.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [x] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/layout/index.jsx [hunk 1]
```diff
@@ -395,6 +404,9 @@ export default withCurrentRoute(
 					sidebarIsHidden,
 					sectionName,
 			  } );
+		const needsColorScheme =
```
Comment (arthur791004) [inline client/layout/index.jsx:403]: do we need to check whether the sidebar is hidden? For example, I think DomainAndPlanPackageFlow doesn't need the color scheme 🤔

File: client/state/admin-color/reducer.js [hunk 2]
```diff
@@ -1,12 +1,14 @@
...
+import { ADMIN_COLOR_RECEIVE, ADMIN_COLOR_REQUEST_FAILURE } from 'calypso/state/action-types';
 import { keyedReducer, withPersistence } from 'calypso/state/utils';
 import 'calypso/state/data-layer/wpcom/sites/admin-color';
 
 const adminColorReducer = ( state = [], action ) => {
 	switch ( action.type ) {
 		case ADMIN_COLOR_RECEIVE:
 			return action.adminColor;
+		case ADMIN_COLOR_REQUEST_FAILURE:
+			return action.adminColor || 'default'; // fallback color scheme: packages/calypso-color-schemes/src/shared/color-schemes/_default.scss
```
Comment (arthur791004) [inline client/state/admin-color/reducer.js]: Is there any issue if we leave it undefined?

File: client/layout/index.jsx (hunk 1 above)
Comment (fushar) [reply client/layout/index.jsx:403]: Good idea, updated!

File: client/state/admin-color/reducer.js (hunk 2 above)
Comment (fushar) [reply client/state/admin-color/reducer.js]: Yes, there is. It will think that we still haven't fetched the admin color, and we will never show the sidebar 🥲

Comment (arthur791004) [reply client/state/admin-color/reducer.js]: Oh yeah this is the quick way to determine whether the admin color is fetched or not 🫠

**Review by arthur791004 — APPROVED** [review]
Tested and works as expected!
