### PR TITLE
Full Site Editing: render child blocks using BlockEdit

### LINKED ISSUE #34102: Full Site Editing: Template Part styles missing when editing a Template [3]
When creating or editing a _Template_ and assigning a _Template Part_, any custom colour is missing.

#### Steps to reproduce
1. Create or Edit a Template Part, and assign it a Custom Background Color.
2. Insert that Template Part on a Template.

#### What I expected

The Template Part to be displayed with all their custom colours.

#### What happened instead

The _Template Part_ custom colours were missing from the preview. The content still there, but the styles are missing.

#### Screenshot / Video

| Template Part | Selecting Template Part | Template Part Preview |
| - | - | - |
| FireShot Capture 016 - Add New Template Part ‹ Gutenberg Dev — WordPress - localhost | FireShot Capture 017 - Add New Template ‹ Gutenberg Dev — WordPress - localhost | FireShot Capture 018 - Add New Template ‹ Gutenberg Dev — WordPress - localhost |

### PR DESCRIPTION
**Pull request by rodrigoi**
Uses the `<BlockEdit />` component instead of `<RawHTML />` to render the child blocks of the template part.

#### The Problem

When we edit a block and set a property like _overlay_ or _text colour_ using the _Block Sidebar_, some CSS classes (like `has-background-dim-##` or `has-*-background-color`) are appended to the block. Those CSS classes are not loaded with the _Editor Styles_, so, to compensate for their absence some inline styles are added to the `edit` instance of the block. By design, those inline styles are not persisted when saving the HTML representation of the block.

When we load the raw content of the template part for preview, it could potentially show broken.

| Edit | Preview |
| - | - |
| Screen Shot 2019-07-04 at 14 47 52 | Screen Shot 2019-07-04 at 14 49 03 |

#### Changes proposed in this Pull Request

Instead of loading the raw content, we need to parse the template blocks and add them to the editor state.

- Show a `<Spinner />` while loading the template post.
- Parse the template block from the post raw content.
- Create a `core/template` block if the template has multiple blocks. This is because we need to store the clientId on the state for later use.
- Add the received blocks to the editor state using `receiveBlocks` and preserve the clientId of the template top-most component in the state.
- If the template block has been added to the state, render it using the `<BlockEdit />` component.

| Before | After |
| - | - |
| before | after |

##### Adding the missing classes to the _Editor Styles_

The _Editor Styles_ are loaded when the editor is initialized (`wp.editPost.initializeEditor`) and stored in the state on the `core/editor` store. Settings can be changed by dispatching a `updateEditorSettings` action with the extra styles. The problem with this approach was that the mechanisms to detect the need to add extra CSS declarations depends on knowing the allowed themes and all the class variants. This could be viable now but could be difficult to maintain.
There is also a problem of timing because the editor is initialized on `domReady`. We need to delay the execution of our code with the potential of making the content _flash_.

##### Using `<InnerBlocks />` or `<BlockList />`

Instead of using `receiveBlocks` to add the template blocks to the editor state and render them manually, we could use `replaceInnerBlocks` to add them as children to the template part block when we load them. Then we could delegate the rendering to `<InnerBlocks />` (or `<BlockList />`).
This works fine, but it has a couple of undesirable side effect. The focus of the editor is set to the last block added, making the page jump to the footer. And the _appender_ is shown unless we override the template lock.

#### Testing instructions

- Edit a Template part. Add a paragraph with Color, or a Cover with an Overlay.
- Verify that all the blocks inside the template part render correctly.
- Verify that there are no regressions when editing a template.

Fixes #34102

### CODE REVIEW

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/edit.js [hunk 1]
```diff
@@ -28,93 +30,131 @@ const TemplateEdit = compose(
...
-								<Button
-									href={ `?post=${ templateId }&action=edit&fse_parent_post=${ currentPostId }` }
-									isDefault
+							</div>
+						</Placeholder>
+					) }
+					{ showContent && (
+						<Fragment>
+							{ parsedBlock && (
+								<BlockEdit
```
Comment (gwwar) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/edit.js]: Interesting, I wasn't able to find any docs for this one. When you have time later @rodrigoi, it'd be super helpful to add what benefits this change has and what BlockEdit does in the PR Summary.

Comment (rodrigoi) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/edit.js]: This is one of the extremely grey areas of Gutenberg, and this still very much a work in progress that, if working as I expect, will serve a double purpose:

* fix the render bug, because blocks cheat when setting things like colour options.
* bring us one step closer to in place editing of template parts.

I'm reverse engineering this from the `Group` block, and the `ReusableBlock`, and considering the lack of documentation, this PR description will take longer to write than the actual code 😧

Comment (gwwar) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/edit.js]: Thanks @rodrigoi I think it's enough then to update the summary on what items will be improved by the PR.

cc @getdave in case you had extra context with regards to the BlockEdit component.

Comment (glendaviesnz) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/edit.js]: could this be part of the solution to #34279 then? - been looking at this and it is currently impossible (from what I can see) to apply the theme styling to the template parts because of the way the fse blocks are currently rendered.

Comment (rodrigoi) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/edit.js]: The first thing I've tried was to add the missing classes to the _Editor Styles_ but there are no extension points there.
The problem with #34279 is that Gutenberg is not a WYSIWYG editor. There are bound to be differences between what you edit and what you render. I'll expand this idea there.

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/edit.js [hunk 2]
```diff
@@ -4,119 +4,178 @@
...
-							<Placeholder
-								className="template-block__overlay"
-								instructions={ __(
-									'This block is part of your site template and may appear on multiple pages.'
+				<div
+					className={ classNames( 'template-block', {
+						[ `align${ align }` ]: align,
+					} ) }
+				>
+					{ showPlaceholder && (
```
Comment (vindl) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/edit.js]: I think this whole block can be removed now - this is a remnant of an earlier phase when we were selecting Template Parts to preview manually. These are now populated automatically based on assigned Page Template.

Comment (rodrigoi) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/edit.js]: I wasn't really sure we wanted to go down that road, so I left everything there. But I'll take this as approval so I'll remove it :)

Comment (vindl) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/edit.js]: I think it's unreachable now, unless something in our code is broken. 😄

Comment (rodrigoi) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/edit.js]: Lots of code removed in 7078ae74866f87e53669ed81b9bb1b853190fa5b.
