### PR TITLE
Fix theme purchase at signup

### LINKED ISSUE #20717: Signup: Themes cannot be purchased/activated in signup flow from logged out theme showcase
#### Steps to reproduce
1. Starting at URL (logged out of WordPress.com): https://wordpress.com/theme/photo-blog (or any other premium theme)
2. Select "Pick this design" and complete the signup flow.

#### What I expected

I expected to be presented with a checkout page during signup to purchase the theme, so it's activated when signup is completed.

#### What happened instead

I never had a chance to purchase the theme, and my new site has a default theme (Twenty Sixteen) activated.

If you select the Free plan during signup, checkout is skipped entirely. If you select a paid plan, you get a checkout page but only the plan (not the theme) is in the cart.

#### Browser / OS version

Mac OS 10.12.6, Chrome 62.

#### Context / Source
#manual-testing Found while retesting https://github.com/Automattic/wp-calypso/issues/8264

### PR DESCRIPTION
**Pull request by seear**
Fixes #20717

screen shot 2017-12-12 at 17 13 22

PR #18557 renamed the `queryObject` prop passed to the signup components to `initialContext`. There are still some uses of `queryObject`. This change fixes the the signup-with-theme flow that takes the chosen theme details from the `queryObject` prop.

@Tug you probably want to take a look at the remaining uses of `queryObject` in signup.

## Testing

Follow steps in #20717

### CODE REVIEW

File: client/signup/steps/domains/index.jsx [hunk 1]
```diff
@@ -330,13 +330,14 @@ const submitDomainStepSelection = ( suggestion, section ) => {
 };
 
 export default connect(
-	state => ( {
+	( state, ownProps ) => ( {
```
Comment (ockham) [inline client/signup/steps/domains/index.jsx]: Since we're only using one prop, you could destructure here,

```js
( state, { initialContext } ) => ( {
```

which is a bit more declarative.

**Comment by ockham** [comment]
As discussed with @seear in Slack, I'm having the same issue on this branch as documented here: vhttps://github.com/Automattic/wp-calypso/issues/20717#issuecomment-351375445

**Comment by rachelmcr** [comment]
I tested the following flows:

- Start on theme showcase and sign up for Free plan
- Start on theme showcase and sign up for Personal plan
- Start on theme showcase and sign up for Premium plan

The first two cases worked as expected (with the theme purchase included in the cart and the theme activated on the site after checkout). However, the theme wasn't activated correctly when I signed up for the Premium plan with these steps:

1. Starting at URL (logged out of WordPress.com): http://calypso.localhost:3000/theme/small-business
2. Select "Pick this design."
3. Signup Step 1: Choose a free WordPress.com address.
4. Signup Step 2: Select the Premium plan.
5. Signup Step 3: Create an account.
6. Checkout page: Purchase the Premium plan (the premium theme should be included in this plan, so it's expected to only see the plan in the cart).
7. On the Purchase success screen, select "Visit your site."

Result: A free theme is activated on the new site, instead of the selected premium theme.

**Comment by seear** [comment]
> A free theme is activated on the new site, instead of the selected premium theme.

Thanks @rachelmcr, I'll look into this.

**Comment by Tug** [comment]
Thanks for fixing @seear, I suggest we just add back `queryObject` as props here:
https://github.com/Automattic/wp-calypso/commit/1a5304347580bdb951c2922c0426c310e8542eab#diff-46ce4cd8580489aebbb3447a87c3cb57L104
Indeed, it should not have been removed, there are still steps using it... not sure how we let this slip!

**Comment by seear** [comment]
> I suggest we just add back queryObject as props here:

Ok, I'll do that instead, since I don't particularly like the way I've fixed it in `connect`—it just seemed to be the lightest-touch fix available.

**Comment by seear** [comment]
> A free theme is activated on the new site, instead of the selected premium theme.

@rachelmcr ^ this seems to be another issue entirely, possibly server-side. I suggest we merge this PR, since it does at least allow the purchase of the theme, then continue to investigate the remaining issues.

**Comment by seear** [comment]
@tug could I get another quick check on this code before merge?

**Comment by rachelmcr** [comment]
> I suggest we merge this PR, since it does at least allow the purchase of the theme, then continue to investigate the remaining issues.

👍  That sounds good to me.

**Comment by Tug** [comment]
LGTM 👍 
Will fix free and personal plans!
