### PR TITLE
Billing: Change copy for non expired jetpack

### LINKED ISSUE #59726: Billing: When a site is disconnected from Jetpack, Calypso says Jetpack plan is expired (even if it's not)
### Quick summary

If a user attempts to manage their Jetpack purchase in Calypso, and the site is not currently connected to Jetpack, the user will see some messaging letting them know that they need to reconnect the site in order to manage their purchase. However, it appears that messaging has been coded to always say the plan is expired - regardless of whether or not the plan is actually expired.

This appears to date back to this change: 

https://github.com/Automattic/wp-calypso/pull/39764

The issue with the copy stating the plan has expired was initially reported in a P2 comment shortly afterwards, in March 2020, but it looks like it slipped through the cracks and wasn't addressed - pbtFFM-5K-p2#comment-245

This issue was mentioned again a couple of months ago in 6930-gh-Automattic/jpop-issues#issuecomment-951902244 

Seems like that wasn't the right place either, so I'm opening a bug report here instead :) 

### Steps to reproduce

1. Disconnect Jetpack on a self-hosted site with an active Jetpack upgrade
2. Visit WordPress.com > Manage Purchases > click on the purchase to manage it
3. See the messaging stating the upgrade has expired (although it hasn't). (Note I stole this screenshot is from the original report in March 2020, hence the dates)
screenshot-from-2020-03-16-17-56-45
 

### What you expected to happen

To see the messaging stating the site is disconnected, but not that the plan has expired.

### What actually happened

There is a message saying the plan has expired when it hasn't.

### Context

Encountered this when assisting a user with their plan billing.

### Simple, Atomic or both?

_No response_

### Theme-specific issue?

_No response_

### Browser, operating system and other notes

_No response_

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by sejas**
#### Changes proposed in this Pull Request

- We've changed the copy related to the purchase status of disconnected jetpack sites.
- Before we displayed the website as expired
- Now, the text is different for only disconnected sites that are not expired yet.

**1. Message for expired and disconnected jetpack plans**
59726_jetpack-disconnected-not-expired_expired

**2. Message for only disconnected jetpack plans**
59726_jetpack-disconnected-not-expired_disconnected

#### Testing instructions

1. Connect a jetpack site to your WordPress account
2. Buy any jetpack upgrade
3. Disconnect your site
4. Go to your purchase history: https://wordpress.com/me/purchases
5. Click on the specific jetpack purchase
6. Observe that the text in the purchase footnotes explains how to reconnect the site. Nothing about the expired site.
7. Change the expiration date in the Store Admin to test the case of expired sites.
8. Go back to the purchase detail and refresh.
9. Observe that the same purchase footnotes mention that the site is disconnected and expired.

- Closes: #59726

### CODE REVIEW

File: client/me/purchases/manage-purchase/purchase-meta.jsx [hunk 1]
```diff
@@ -357,13 +357,27 @@ function RenewErrorMessage( { purchase, translate, site } ) {
 	if ( isJetpack ) {
 		return (
 			<div className="manage-purchase__footnotes">
+				{ isExpired( purchase )
+					? translate(
+							'%(purchaseName)s expired on %(siteSlug)s, and the site is no longer connected to WordPress.com. ' +
+								'To renew this purchase, please reconnect %(siteSlug)s to your WordPress.com account, then complete your purchase. ',
```
Comment (mmtr) [inline client/me/purchases/manage-purchase/purchase-meta.jsx]:
```suggestion
								'To renew this purchase, please reconnect %(siteSlug)s to your WordPress.com account, then complete your purchase.',
```

We should exclude the final whitespace from the translation, because otherwise translators may miss it.

Comment (sejas) [reply client/me/purchases/manage-purchase/purchase-meta.jsx]: Done!, I've pushed the changes using `&nbsp`.
Looking forward to deploying it together tomorrow 💪

**Review by mmtr — APPROVED** [review]
Works as described and code looks good to me 🚀

File: client/me/purchases/manage-purchase/purchase-meta.jsx [hunk 2]
```diff
@@ -357,13 +357,27 @@ function RenewErrorMessage( { purchase, translate, site } ) {
...
+							args: {
+								siteSlug: purchase.domain,
+							},
+					  } ) }
+				&nbsp;
 				{ translate(
-					'%(purchaseName)s expired on %(siteSlug)s, and the site is no longer connected to WordPress.com. ' +
-						'To renew this purchase, please reconnect %(siteSlug)s to your WordPress.com account, then complete your purchase. ' +
-						'Now sure how to reconnect? {{supportPageLink}}Here are the instructions{{/supportPageLink}}.',
+					'Not sure how to reconnect? {{supportPageLink}}Here are the instructions{{/supportPageLink}}.',
```
Comment (sirbrillig) [inline client/me/purchases/manage-purchase/purchase-meta.jsx:378]: Minor but if you wanted to preserve the old text until the new text is translated, you could use [hasTranslation](https://github.com/Automattic/wp-calypso/blob/7dfafccf2c723707cbf5819cd7fc2d8bb3703784/packages/i18n-calypso/README.md#hastranslation-method). A string freeze label would do basically the same thing. Anyway, just wanted to mention it.

Comment (mmtr) [reply client/me/purchases/manage-purchase/purchase-meta.jsx:378]: Yup, that's usually quite helpful. For this case though I think we're fine displaying an untranslated text in the meantime since this is rather an edge case (expired purchases of disconnected Jetpack sites which are only visible from `/me/purchases`) which doesn't justify the extra cost of maintaing two translations.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7306873

Thank you @sejas for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7306873).
