### PR TITLE
Remove special chars for domain validation

### LINKED ISSUE #66969: [Bug]: tailored flows, handle special characters for prefilled domain search
### Quick summary

When doing domain search in tailored flows (newsletter, link in bio) and using special characters, the domain search errors.

### Steps to reproduce

1. start newsletter or link in bio flow
2. enter name with special characters (e.g. , . /)
3. note error at domain step

### What you expected to happen

No error.

### What actually happened

image

### Browser

_No response_

### Context

_No response_

### Platform (Simple, Atomic, or both?)

_No response_

### Other notes

_No response_

### Reproducibility

Consistent

### Severity

_No response_

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by renancarvalho**
## Proposed Changes

Removes special chars from domain suggestions

## Testing Instructions

- Pull this branch and run yarn
- Navigate to `setup/intro?flow=newsletter`
- Choose any site title
- On the domain step you should not see the error message describe on the [issue](66969).

Related to #66969
Fixes #66969

### CODE REVIEW

File: client/lib/domains/get-fixed-domain-search.js [hunk 1]
```diff
@@ -7,5 +7,6 @@ export function getFixedDomainSearch( domainName ) {
 		.replace( /^www[0-9]?\./, '' )
 		.replace( /\/$/, '' )
 		.replace( /_/g, '-' )
+		.replace( /[^a-z0-9-]/, '' )
 		.replace( /^\.+|\.+$/, '' );
```
Comment (alshakero) [inline client/lib/domains/get-fixed-domain-search.js]: Your `replace` will take care of these.

```suggestion
		.replace( /[^a-z0-9-]/, '' )
```

**Review by alshakero — CHANGES_REQUESTED** [review]
This still doesn't handle short queries whose length is <2.

Visit this to repro: https://container-quizzical-curran.calypso.live/start/link-in-bio/domains?new=r&search=yes&hide_initial_query=yes

File: client/lib/domains/get-fixed-domain-search.js [hunk 2]
```diff
@@ -5,5 +5,5 @@ export function getFixedDomainSearch( domainName ) {
 		.toLowerCase()
 		.replace( /^(https?:\/\/)?(www[0-9]?\.)?/, '' )
 		.replace( /^www[0-9]?\./, '' )
-		.replace( /[^a-z0-9-\\.]/, '' );
+		.replace( /[^a-z0-9-.]/, '' );
```
Comment (alshakero) [inline client/lib/domains/get-fixed-domain-search.js:8]: `.` doesn't need escaping when within `[]`.

**Review by alshakero — APPROVED** [review]
OK now it works and tests should pass. 

To test, simply visit `start/link-in-bio/domains?new=r`&search=yes&hide_initial_query=yes`.
