### PR TITLE
Store: Fix product error when inventory/stock is set and then unset

### LINKED ISSUE #16779: Store: Unable to update the product when inventory is set and then unset
#### Steps to reproduce

1. Create a product without filling the inventory
2. Update the product with inventory set to 1, but don't save it yet
3. Empty the inventory again
4. Click update

#### What I expected

* To be able to save it without inventory being set just like how the product is created
* Clear wording on the notice on why it's not allowed for me to update (maybe pointing to inventory field). Currently, it tells me "There was a problem...".

See this recording:

inventory-validation

### PR DESCRIPTION
**Pull request by justinshreve**
Fixes #16779.

If you made an edit to the stock, backspaced to unset it, and then tried to save, an API error would occur griping about `stock_quantity` being invalid since it would get passed an empty string.

This PR fixes that and passes something the API can handle.

To Test:
* Create a product with a price but without filling the inventory. Save.
* View your product on the front end to make sure it is purchasable (add to cart button visible)
* Update the product with inventory set to 1, but don't save it yet
* Empty the inventory again (backspace / empty input)
* Click update and make sure you get a success message and not an error
* View your product on the front end to make sure it is purchasable
* Update the product with inventory set to 1 and save this time
* View your product on the front end to make sure it is purchasable

### CODE REVIEW

File: client/extensions/woocommerce/app/products/product-form-simple-card.js [hunk 1]
```diff
@@ -87,14 +95,17 @@ const ProductFormSimpleCard = ( { siteId, product, editProduct, translate } ) =>
 		'products__product-form-stock-disabled': ! product.manage_stock,
 	} );
 
+	const { stock_quantity } = product;
+	const quantity = ! isNull( stock_quantity ) && Number( stock_quantity ) >= 0 ? stock_quantity : '';
```
Comment (coderkevin) [inline client/extensions/woocommerce/app/products/product-form-simple-card.js]: Is it possible to have a negative stock quantity? Back orders? Just curious what the check here is trying to prevent. Seems strange to be doing API data validation in a render function.

Comment (justinshreve) [inline client/extensions/woocommerce/app/products/product-form-simple-card.js]: Good call. Yeah stock can go negative for backorders. The whole line in general was to make sure we could display 0 and still have the other stock options display, and hide if no value is entered (per design) but the `isNull` check already takes care of that. I've removed the negative stock check. Thanks.
