### PR TITLE
AssetWriter: close WritableStream after writing

### LINKED ISSUE #27038: Server error: Unexpected token { in JSON
#26655 addressed intermittent server-crashing errors that mentioned `TypeError: Cannot read property 'style.css' of undefined`.

After that landed, I've just observed a new error which outputs the following message. 
The server continues to run but only appears to serve this plain text response:

```
SyntaxError: Unexpected token { in JSON at position 1019639
    at JSON.parse (<anonymous>)
    at parse (…/build/webpack:/server/pages/index.js:87:18)
    at getAssets (…/build/webpack:/server/pages/index.js:129:17)
    at generateStaticUrls (…/build/webpack:/server/pages/index.js:507:9)
    at Layer.handle_error (…/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (…/node_modules/express/lib/router/index.js:315:13)
    at …/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (…/node_modules/express/lib/router/index.js:335:12)
    at next (…/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (…/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (…/node_modules/express/lib/router/index.js:315:13)
    at …/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (…/node_modules/express/lib/router/index.js:335:12)
    at next (…/node_modules/express/lib/router/index.js:275:10)
    at next (…/node_modules/express/lib/router/route.js:127:14)
    at Layer.handle [as handle_request] (…/node_modules/express/lib/router/layer.js:97:5)
```

I'm not sure if there's a reliable way to reproduce this.

cc: @Automattic/team-calypso

### PR DESCRIPTION
**Pull request by flootr**
This was the cause of a problem where `server/bundler/assets.json` wasn't readable anymore because of invalid JSON. AssetWriter used to just append new output instead of replacing existing JSON which causes the server to fail while trying to read that file and parsing with `JSON.parse`.

It's described in more detail here: https://github.com/Automattic/wp-calypso/issues/27038#issuecomment-419052392

fixes #27038

I still think it's questionable if we need to rewrite `assets.json`. The only runtime usage is in `/server/pages/index.js:getAssets()` but there we cache the output in a variable and at least theoretically don't consume it another time. Maybe @blowery can give more insight on this one.

### Testing instructions

1. Change `getAssets` in `server/pages/index.js` to look like the following:

```diff
 const getAssets = ( () => {
-       let assets;
+       // let assets;
        return () => {
-               if ( ! assets ) {
-                       assets = JSON.parse( fs.readFileSync( ASSETS_PATH, 'utf8' ) );
-               }
+               // if ( ! assets ) {
+               const assets = JSON.parse( fs.readFileSync( ASSETS_PATH, 'utf8' ) );
+               // }
                return assets;
        };
 } )();
```
2. Boot up Calypso and go to https://calypso.localhost:3000
3. Make an arbitrary change in any file to trigger webpack recompile
4. Reload https://calypso.localhost:3000
4.1. `master` should fail with a `SyntaxError: Unexpected token { in JSON ...`
4.2. this branch should not fail

### CODE REVIEW

File: server/bundler/assets-writer.js [hunk 1]
```diff
@@ -26,6 +25,7 @@ Object.assign( AssetsWriter.prototype, {
 		const self = this;
 
 		compiler.hooks.afterEmit.tap( 'AssetsWriter', compilation => {
```
Comment (blowery) [inline server/bundler/assets-writer.js]: i wonder if we should make this an async tap and only allow things to proceed when the write has completed?

File: server/bundler/assets-writer.js [hunk 2]
```diff
@@ -85,7 +85,9 @@ Object.assign( AssetsWriter.prototype, {
 				} )
 			);
 
-			self.outputStream.write( JSON.stringify( statsToOutput, null, '\t' ) );
+			self.outputStream.write( JSON.stringify( statsToOutput, null, '\t' ), () =>
```
Comment (blowery) [inline server/bundler/assets-writer.js]: this can be an `.end( .. )` call since it's the last thing we write. That should catch any double writes.

File: server/bundler/assets-writer.js (hunk 1 above)
Comment (blowery) [reply server/bundler/assets-writer.js]: see https://github.com/webpack/tapable#usage

File: server/bundler/assets-writer.js [hunk 3]
```diff
@@ -85,7 +85,7 @@ Object.assign( AssetsWriter.prototype, {
 				} )
 			);
 
-			self.outputStream.write( JSON.stringify( statsToOutput, null, '\t' ) );
+			self.outputStream.end( JSON.stringify( statsToOutput, null, '\t' ), () => callback() );
```
Comment (ockham) [inline server/bundler/assets-writer.js]: Can we simplify `() => callback()` to just `callback`?

Comment (flootr) [reply server/bundler/assets-writer.js]: Yes, the callback of `.end` doesn't seem to get any arguments so that should be possible.

**Comment by flootr** [comment]
@blowery @ockham gtm?

**Comment by blowery** [comment]
LGTM, just testing it in Docker
