### PR TITLE
Jetpack Search: instant search toggle should change with Jetpack Search toggle

### LINKED ISSUE #52404: Settings: if Jetpack Search is turned off, Instant Search should appear untoggled too
### Steps to reproduce the behavior

1. On a site with a Jetpack Search plan purchased, go to Settings > General > Performance
2. Click to deactivate Jetpack Search with "Improve built-in WordPress search performance." toggle

#### What I expected to happen

When I deactivate Jetpack Search, the Instant Search experience toggle should be untoggled too.

#### What actually happened

The Instant Search experience toggle remained on.

### Context

Raised by @jinnypark in https://github.com/Automattic/jpop-issues/issues/6586.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Low.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

Consistent.

#### Screenshot / Video

Screen Shot 2021-04-29 at 16 47 21

### PR DESCRIPTION
**Pull request by kangzj**
Fixes: #52404

#### Changes proposed in this Pull Request
- When disabling Jetpack Search, instant search would also be disabled which is a child option under Jetpack Search, which also aligns with Jetpack plugin settings page.
- And, because we recommend instant search, when Jetpack is re-enabled, instant search would be re-enabled too.
- Changed label to be clearer - 'Enable Jetpack Search'
- Separate the setting saving of jetpack sites (including Atomic) from simple sites to avoid a random error discussed in P2.

#### Discussion
pcNPJE-8a-p2

#### Testing instructions
- Open Settings->General->Performance of a site with Jetpack Search plan (Atomic/Simple/Jetpack sites) in Clypso
- Ensure when Jetpack Search  is toggled disabled, instant search is disabled as well.
- Ensure when Jetpack Search is toggled enabled, instant search is set to enabled.
- Ensure Instant search toggle could change and save without affecting Jetpack Search toggle.
- Ensure it works for Atomic / Simple / Jetpack site.

image

Gif: https://d.pr/i/dl2HRh

### CODE REVIEW

**Comment by kangzj** [comment]
When updating instant search toggle (live or on this branch), it calls /rest/v1.1/jetpack-blogs/190071516/rest-api/?http_envelope=1 to sync the Jetpack setting to the site, which sometimes fails with error code 400. 

The above issue mentioned will be looked at separately.

Request
```JSON
{"path":"/jetpack/v4/settings/","body":"{\"lazy-images\":true,\"photon-cdn\":false,\"photon\":false,\"instant_search_enabled\":true}","json":true}
﻿```

Response
```JSON
{"code":400,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"some_updated","message":""}}
```

File: client/my-sites/site-settings/search.jsx [hunk 1]
```diff
@@ -154,16 +170,17 @@ class Search extends Component {
 							<JetpackModuleToggle
 								siteId={ siteId }
 								moduleSlug="search"
-								label={ translate( 'Improve built-in WordPress search performance.' ) }
+								label={ translate( 'Enable Jetpack Search' ) }
```
Comment (bluefuton) [inline client/my-sites/site-settings/search.jsx]: Much clearer! 👏

File: client/my-sites/site-settings/search.jsx [hunk 2]
```diff
@@ -143,8 +152,38 @@ class Search extends Component {
...
 			siteId,
 			translate,
+			saveJetpackSettings,
+			submitForm,
+			updateFields,
+			trackEvent,
 		} = this.props;
 
+		/**
+		 * Call WPCOM endpionts to update remote Jetpack sites' settings
```
Comment (bluefuton) [inline client/my-sites/site-settings/search.jsx]:
```suggestion
		 * Call WPCOM endpoints to update remote Jetpack sites' settings
```

File: client/my-sites/site-settings/search.jsx [hunk 3]
```diff
@@ -143,8 +152,38 @@ class Search extends Component {
...
+				instant_search_enabled: jetpackSearchEnabled,
+			} );
+
+		/**
+		 * Change instant toggle status with Jetpack Search toggle and then save settings
+		 *
+		 * @param {boolean} jetpackSearchEnabled Whether Jetpack Search is enabled
+		 */
+		const handleJetpackSearchToggleForSimpleSites = ( jetpackSearchEnabled ) => {
+			trackEvent( `Toggled instant_search_enabled` );
```
Comment (bluefuton) [inline client/my-sites/site-settings/search.jsx]:
```suggestion
			trackEvent( 'Toggled instant_search_enabled' );
```

^ Switched to single quotes because we're not doing any variable interpolation.

Do we know where `trackEvent` records events? I see it used in the AMP component but I've never used it myself before.

**Comment by bluefuton** [comment]
I notice that sometimes the instant search toggle loads before the main JP Search toggle - could we do `checked={ fields.jetpack_search_enabled && fields.jetpack_instant_search_enabled }` for that second toggle?

File: client/my-sites/site-settings/search.jsx (hunk 3 above)
Comment (kangzj) [reply client/my-sites/site-settings/search.jsx]: The toggle event was originally tracked in handleAutosavingToggle, since I changed not to use the function, I added the event tracking here. 
It seems it sends events to Google Analytics, but didn't see any requests sent out. Do you think I should look further?

Comment (bluefuton) [reply client/my-sites/site-settings/search.jsx]: If we're just preserving the existing usage, that's all good :)

**Comment by bluefuton** [comment]
The "If deactivated..." part of the description seems a bit redundant now we've made the main toggle label clearer ('Enable Jetpack Search'). Might also be confusing in light of the 'submit' overlay trigger we're adding in https://github.com/Automattic/jetpack/pull/19795. Shall we drop it?

**Comment by kangzj** [comment]
> The "If deactivated..." part of the description seems a bit redundant now we've made the main toggle label clearer ('Enable Jetpack Search'). Might also be confusing in light of the 'submit' overlay trigger we're adding in [Automattic/jetpack#19795](https://github.com/Automattic/jetpack/pull/19795). Shall we drop it?

Agree. The text is a bit vague now, removed in 96a8bef.

**Comment by kangzj** [comment]
> I notice that sometimes the instant search toggle loads before the main JP Search toggle - could we do `checked={ fields.jetpack_search_enabled && fields.jetpack_instant_search_enabled }` for that second toggle?

Good point. Fixed in 5b6d040

**Review by jsnmoon — COMMENTED** [review]
Changes look good overall. Two questions:

1. Would it be possible to keep the Instant Search enabled even if the Search module is disabled? (e.g. When Instant Search is enabled, the Search module is also toggled on.) This is how it currently works in `/wp-admin/admin.php?page=jetpack#/performance`.

2. What do we gain by refactoring `renderSettingsCard` to create `renderSearchTogglesForJetpackSites` and `renderSearchTogglesForSimpleSites`? I'm seeing a bit of duplicated code (e.g. form toggles' disabled conditional) and am curious about the rationale for this change. Is it to improve code clarity?

EDIT: Meant to say "keep the Instant Search **toggle** enabled" for point 1.

**Comment by kangzj** [comment]
Thanks for your review @jsnmoon :-)
 
> 1. Would it be possible to keep the Instant Search enabled even if the Search module is disabled? (e.g. When Instant Search is enabled, the Search module is also toggled on.) This is how it currently works in `/wp-admin/admin.php?page=jetpack#/performance`.

Hmmm, are you sure? As I tested, the way proposed in the PR works the same as it is in WP Admin - the Instant Search option toggles with the Search option. And actually this is one of the reasons to change in Calypso - to align experience. 

> 2. What do we gain by refactoring `renderSettingsCard` to create `renderSearchTogglesForJetpackSites` and `renderSearchTogglesForSimpleSites`? I'm seeing a bit of duplicated code (e.g. form toggles' disabled conditional) and am curious about the rationale for this change. Is it to improve code clarity?

Yes it is, otherwise we'll have to test whether the site is Jetpack or not for every component (and attributes), which is not very pleasant to read. By refactoring it like above, there is a bit of duplication, but much better readability.

File: client/my-sites/site-settings/search.jsx [hunk 4]
```diff
@@ -85,14 +94,10 @@ class Search extends Component {
...
 					) }{ ' ' }
-					{ this.props.hasSearchProduct
-						? this.props.translate(
-								'If deactivated, Jetpack Search will still optimize your search results but visitors will have to submit a search query before seeing any results.'
-						  )
-						: // The following notice is only shown for Business/Pro plan holders.
-						  this.props.translate(
-								'Instant search is only available with a Jetpack Search subscription.'
-						  ) }
+					{ ! this.props.hasSearchProduct && // The following notice is only shown for Business/Pro plan holders.
```
Comment (bluefuton) [inline client/my-sites/site-settings/search.jsx:97]: Noticed while testing that we could make this clearer: https://github.com/Automattic/wp-calypso/issues/52736.

One for a future PR though!

File: client/my-sites/site-settings/wrap-settings-form.jsx [hunk 5]
```diff
@@ -87,6 +88,22 @@ const wrapSettingsForm = ( getFormSettings ) => ( SettingsForm ) => {
...
 				}
+			} else if (
+				this.props.siteIsJetpack &&
+				this.props.saveInstantSearchRequest?.status === 'success' &&
+				( typeof prevProps.saveInstantSearchRequest?.lastUpdated === 'undefined' ||
+					prevProps.saveInstantSearchRequest?.lastUpdated <
+						this.props.saveInstantSearchRequest?.lastUpdated ) &&
+				this.props.siteId === prevProps.siteId
+			) {
+				// NOTE: 1. the condition is pretty messy - the problem is that, if a request is the same
```
Comment (bluefuton) [inline client/my-sites/site-settings/wrap-settings-form.jsx:99]: I trust your research here :) Works as intended!

**Review by bluefuton — APPROVED** [review]
Looks good! 🚢

**Comment by kangzj** [comment]
> Looks good! 🚢

Thanks @bluefuton 

So excited to get this done!!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5902969

Thank you @kangzj for including a screenshot in the description! This is really helpful for our translators.

**Comment by jsnmoon** [comment]
> > 1. Would it be possible to keep the Instant Search enabled even if the Search module is disabled? (e.g. When Instant Search is enabled, the Search module is also toggled on.) This is how it currently works in `/wp-admin/admin.php?page=jetpack#/performance`.
> 
> Hmmm, are you sure? As I tested, the way proposed in the PR works the same as it is in WP Admin - the Instant Search option toggles with the Search option. And actually this is one of the reasons to change in Calypso - to align experience.

Oops, I fat-fingered my initial review. I meant to say if it would be possible to keep the Instant Search **toggle** enabled even if the search module is disabled. This is how it currently works in wp-admin:

https://user-images.githubusercontent.com/4044428/118177469-f68e2b00-b3ef-11eb-8921-16ef9f8be2b5.mp4

Since the Instant Search toggle is disabled when the module is disabled, this UX is not currently possible:

Screen Shot 2021-05-13 at 1 36 20 PM

**Comment by kangzj** [comment]
> I meant to say if it would be possible to keep the Instant Search toggle enabled even if the search module is disabled.

Ha got it. It makes sense. Thanks for reporting this, will get it addressed with #52736

**Comment by cavalierlife** [comment]
@kangzj I think the new wording looks good. Approved from our end.

**Comment by kangzj** [comment]
Thanks @cavalierlife  👍

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5902969).
