### PR TITLE
Site Icon: update help text to include minimum size

### LINKED ISSUE #11234: Site Icon: improve help text to include size requirements
Improve usability and final quality of site icons by providing contextual help to authors uploading images.

We currently don't state clearly that 512 by 512 pixels is the minimum size for the best quality display across all browsers, apps, widgets, and more.

#### Steps to reproduce
1. Starting at URL: `/settings/general/example.wordpress.com`.
2. Click the help icon next to Site Icon form.

#### What I expected
To see an explanation of the square aspect ratio, and 512 x 512 as minimum recommended size.

#### What happened instead
Didn't see the size info on the Calypso settings info popup.

screen shot 2017-02-07 at 06 57 30

Also checked our <a href="https://en.support.wordpress.com/site-icons/">support page</a> and that needs size info as well.

I also looked in the Customizer, and it does have size info.
        
screen shot 2017-02-07 at 06 57 42

- [ ] Update help in setting screen: https://github.com/Automattic/wp-calypso/pull/11235
- [x] Update [support document](https://en.support.wordpress.com/site-icons/).

### PR DESCRIPTION
**Pull request by lancewillett**
Fixes #11234

**Before**
screen shot 2017-02-07 at 06 57 30

**After**
screen shot 2017-02-07 at 09 13 19

### CODE REVIEW

File: client/my-sites/site-settings/site-icon-setting/index.jsx [hunk 1]
```diff
@@ -256,8 +256,8 @@ class SiteIconSetting extends Component {
 				<FormLabel className="site-icon-setting__heading">
 					{ translate( 'Site Icon' ) }
 					<InfoPopover position="bottom right">
-						{ translate( 'Your site icon will be shown across WordPress.com, in your' +
-							' visitors\' browser tabs, and as a home screen app icon.' ) }
+						{ translate( 'The Site Icon is used as a browser and app icon for your site.' +
```
Comment (aduth) [inline client/my-sites/site-settings/site-icon-setting/index.jsx]: I'm not sure if core strings are used verbatim if matching our strings, but in case they are, the exact string defines the pixel dimension as a placeholder:

>The Site Icon is used as a browser and app icon for your site. Icons must be square, and at least %s pixels wide and tall.

https://translate.wordpress.com/projects/wpcom/fr/default/?filters%5Bterm%5D=site+icon+is+used&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

Rewritten this would be:

```js
{ translate(
	'The Site Icon is used as a browser and app icon for your site.' +
	'Icons must be square, and at least %s pixels wide and tall.',
	{ args: [ 512 ] }
) }
```

**Comment by aduth** [comment]
Background: #10796, #10451

There was some discussion around expanding on how site icons are used throughout the Calypso experience (e.g. Reader, etc). I agree though that requirements would be good to include.

File: client/my-sites/site-settings/site-icon-setting/index.jsx (hunk 1 above)
Comment (lancewillett) [inline client/my-sites/site-settings/site-icon-setting/index.jsx]: Thanks! Let's match it as closely as possible, for the sake of translation and UX consistency.

**Comment by lancewillett** [comment]
@aduth Updated to use a placeholder. Thanks for your review.
