### PR TITLE
Block Editor: Add default routes for block editor paths.

### LINKED ISSUE #29822: Editor: Blank screen when the post type isn't specified
#### Steps to reproduce
1. Starting at URL: `/block-editor/:site` (note: this only happens if the site fragment is provided).

#### What I expected

To being redirected to `/block-editor/post/:site`.

#### What happened instead

It opens the non-existent `/block-editor/:site` route, causing a blank screen.

### LINKED ISSUE #29864: Gutenberg: Blank Screen on /block-editor/posts
#### Steps to reproduce 

- Open https://wordpress.com/block-editor/posts

#### What happens at the moment 

It loads a blank screen.

#### Suggested enhancement

Is it possible to redirect this path to https://wordpress.com/block-editor/post, so that user can pick a site to compose the post? Or, is there a way to make this path actionable?

I think the same behaviour is not available yet for WordPress Editor, as WordPress Editor is not available for Jetpack sites at this time - https://github.com/Automattic/wp-calypso/issues/28251

#### Behaviour on Calypso editor

Visiting https://wordpress.com/posts shows the list of all posts from all the sites the user has associated to their WordPress.com account.

#### Context

I came across https://github.com/Automattic/wp-calypso/issues/29822 and decided to test this path. #manual-testing

### PR DESCRIPTION
**Pull request by kwight**
#### Changes proposed in this Pull Request

Add fallback `page` handlers for the `/block-editor` routes.

* If we have two or more additional segments where the first is unidentified, redirect to the `/block-editor/post` site picker. 
* If we have only one additional unidentified segment, we redirect to `/block-editor/post/:site`; if the site segment is valid, we'll get the iframed editor, and if not, we're redirected to the site picker at `/block-editor/post`.

#### Testing instructions

* Switch to this branch.
* Load `http://calypso.localhost:3000/block-editor/:site`. Verify the redirect to `http://calypso.localhost:3000/block-editor/post/:site`, and the successful iframing of the editor.
* Load `http://calypso.localhost:3000/block-editor/cats/dogs`, and verify the redirect to `/block-editor/post`.
* Load `http://calypso.localhost:3000/block-editor/cats/`, and verify the redirect to `/block-editor/post`.
* Try any and all other valid or invalid routes, and see if you can find any unpredicted behaviour.

Fixes #29822.
Fixes #29864.

### CODE REVIEW

**Comment by mmtr** [comment]
This will also fix https://github.com/Automattic/wp-calypso/issues/29864 (I already updated the description).

File: client/gutenberg/editor/index.js [hunk 1]
```diff
@@ -56,6 +56,11 @@ export default function() {
 				clientRender
 			);
 		}
+
+		page( '/block-editor/**/*', '/block-editor/post' );
```
Comment (vindl) [inline client/gutenberg/editor/index.js]: What's the point of double asterisk here? I'd expect this to work with `/block-editor/*/*`.

Comment (kwight) [reply client/gutenberg/editor/index.js]: No point at all, not sure why I did that 🙃 Removed it 👍
