### PR TITLE
Tailored Flows: Remove redirect to launchpad for removed flows

### LINKED ISSUE #95667: Tailored Flows: Unlaunched sites are redirected to `/start`
**Steps to reproduce**
- Go to `wordpress.com/sites`
- Pick a site created with the (now obsolete) free flow

**Current behavior**
- I'm redirected to `/start/free` which doesn't make sense because I don't want to create a site

https://github.com/user-attachments/assets/80e34da4-d85c-42a0-819f-5fea4ddbbf21

**Expected behavior**

I should land on either the stepper launchpad or My Home

https://github.com/user-attachments/assets/ba288992-8d37-43c2-a561-76218fbb372c

### PR DESCRIPTION
**Pull request by mmtr**
Fixes https://github.com/Automattic/wp-calypso/issues/95667

## Proposed Changes

Prevents the redirection from `/home/:site` to `/setup/:flow/launchpad` if the site was created with one of the flows we have removed as part of https://github.com/Automattic/dotcom-forge/issues/8999.

**Before**

https://github.com/user-attachments/assets/2fbd2be4-b4af-47f6-8911-3f313927d8cd

**After**

https://github.com/user-attachments/assets/701d4e90-5ea0-4952-b498-3340ae2d78c2

## Why are these changes being made?

Because unlaunched sites created with a removed tailored flow were getting a broken experience

## Testing Instructions

- If you don't have a site created with one of the removed tailored flows, run this on your sandbox:

```
update_blog_option( <SITE_ID>, 'site_intent', 'free' );
```

- Make sure the site is unlaunched and has not skipped/completed the launchpad
- Use the Calypso live link below
- Go to `/sites`
- Pick the site and click on the "My Home" button
- Make sure you stay on My Home and are not redirected to `/setup/:flow/launchpad`

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/landing/stepper/utils/flow-redirect-handler.ts [hunk 1]
```diff
@@ -1,12 +1,12 @@
...
-	{ from: '/setup/free/', to: '/start/free:lang?' },
-	{ from: '/setup/link-in-bio/', to: '/start:lang?' },
-	{ from: '/setup/videopress/', to: '/start:lang?' },
-	{ from: '/setup/sensei/', to: ':lang?/plugins/sensei-pro/' },
+export const REMOVED_TAILORED_FLOWS = [
+	{ flow: 'blog', to: '/start:lang?' },
+	{ flow: 'free', to: '/start/free:lang?' },
+	{ flow: 'link-in-bio', to: '/start:lang?' },
+	{ flow: 'videopress', to: '/start:lang?' },
+	{ flow: 'sensei', to: ':lang?/plugins/sensei-pro/' },
```
Comment (rcrdortiz) [inline client/landing/stepper/utils/flow-redirect-handler.ts]: We can use the Flow constants here.

Comment (xavier-lc) [inline client/landing/stepper/utils/flow-redirect-handler.ts]: Nit: I think this would make more sense as a map, since it doesn't look like we'll be adding more fields to the objects:

```
export const REMOVED_TAILORED_FLOWS_REDIRECT_URL = {
	blog: '/start:lang?',
	free: '/start/free:lang?',
	link_in_bio: '/start:lang?',
	videopress: '/start:lang?',
	sensei: ':lang?/plugins/sensei-pro/',
};
```

File: client/my-sites/customer-home/controller.jsx [hunk 2]
```diff
@@ -67,7 +68,8 @@ export async function maybeRedirect( context, next ) {
 			checklist: launchpadChecklist,
 		} = await fetchLaunchpad( slug );
 
-		const shouldShowLaunchpad = true;
+		const isRemovedFlow = REMOVED_TAILORED_FLOWS.find( ( { flow } ) => flow === siteIntentOption );
+		const shouldShowLaunchpad = ! isRemovedFlow;
```
Comment (rcrdortiz) [inline client/my-sites/customer-home/controller.jsx]: I think it would be better to delegate determining if a flow is removed to a function inside the `flow-redirect-handler`, maybe we could have a function called isRemovedFlow( flow: string );

An implementation could be:
````
const isFlowRemoved = ( option ) => !!REMOVED_TAILORED_FLOWS.find(({ flow }) => flow === option );
````
We wouldn't need to export the ` REMOVED_TAILORED_FLOWS` since it can be limited to its domain and not need to be exposed.

**Review by xavier-lc — APPROVED** [review]
Works as described.

File: client/landing/stepper/utils/flow-redirect-handler.ts (hunk 1 above)
Comment (rcrdortiz) [reply client/landing/stepper/utils/flow-redirect-handler.ts]: As a map we lose the contextual information about what the key means. It's also more cumbersome to iterate over

Comment (mmtr) [reply client/landing/stepper/utils/flow-redirect-handler.ts]: https://github.com/Automattic/wp-calypso/pull/95669/commits/b4cb7bf7517a0fb912438e4df1a1a32b9babba01

File: client/my-sites/customer-home/controller.jsx (hunk 2 above)
Comment (mmtr) [reply client/my-sites/customer-home/controller.jsx]: https://github.com/Automattic/wp-calypso/pull/95669/commits/550b909a3839ec08643a6b513e68e9d1efe26fb6

**Review by rcrdortiz — APPROVED** [review]
Works as expected, thanks for the changes.
