### PR TITLE
Jetpack Plans: Fix confirmation dialog when leaving the plugins install screen

### LINKED ISSUE #5908: Jetpack Plans: Confirmation when leaving the plugins auto-install is inconsistent
There are two issues with the confirmation pop-up.

**Confirmation fires without installing anything**

1. Start the plugins install & configuration process at `/plugins/setup/$site`, for a site without Manage enabled.
2. You see an "Enable Manage" card
3. Try to close the tab, you're asked to confirm

**Confirmation doesn't fire for internal links**

1. Start the plugins install & configuration process at `/plugins/setup/$site`
2. While the process is running, click Reader
3. You can, there is no confirmation

cc @johnHackworth @roccotripaldi

### PR DESCRIPTION
**Pull request by ryelle**
This adds better checks for whether we're currently installing plugins, so that the confirmation dialog fires at appropriate times. This also adds a confirmation dialog when navigating to another calypso route.

To test:

1. Start the plugins install & configuration process at /plugins/setup/$site
2. While the process is running, click Reader
3. You're alerted "We haven't finished installing your plugins.", so you can "cancel" and continue installing, or hit "OK" to navigate away.

You can also test this with WordPress.com sites, sites with no write access, etc, and you **should not** see a confirmation dialog when closing the tab.

**Note:** Chrome, Firefox, and Safari [no longer respect the custom text](https://developers.google.com/web/updates/2016/04/chrome-51-deprecations?hl=en#remove-custom-messages-in-onbeforeload-dialogs) returned in the `beforeunload` event, so the text seen when closing the tab is not the same as navigating away in calypso.

Fixes #5908 

cc @johnHackworth @rickybanister @roccotripaldi 

Test live: https://calypso.live/?branch=fix/jetpack-plugins-confirmation

### CODE REVIEW

File: client/my-sites/plugins/jetpack-plugins-setup/index.jsx [hunk 1]
```diff
@@ -85,6 +85,23 @@ const PlansSetup = React.createClass( {
 		if ( this.props.siteId ) {
 			this.fetchInstallInstructions();
 		}
+
+		page.exit( '/plugins/setup/*', ( context, next ) => {
+			const confirmText = this.warnIfNotFinished( {} );
+			if ( ! confirmText ) {
+				return next();
+			}
+			console.log( 'We\'re still installing...' );
```
Comment (johnHackworth) [inline client/my-sites/plugins/jetpack-plugins-setup/index.jsx]: Is this console.log left here intentionally?

**Comment by johnHackworth** [comment]
I left a (very minor) comment, but I think this is ready to go! :shipit:

File: client/my-sites/plugins/jetpack-plugins-setup/index.jsx (hunk 1 above)
Comment (ryelle) [inline client/my-sites/plugins/jetpack-plugins-setup/index.jsx]: nope 😫  I'll remove it before merging.
