### PR TITLE
CPT / Themes: Refresh post types when site theme changes

### LINKED ISSUE #7131: CPT: clicking on a CPT not supported by the active theme results in an "Invalid post type" error
Steps to reproduce:

1. Log in to https://wordpress.com/ while proxied (staging)
1. Go to https://wordpress.com/settings/writing and select a site if prompted
1. Make sure Testimonials and Portfolio Projects are on and click "Save Changes"
1. Click Themes in the left sidebar and activate the Confit theme
1. Refresh the page
1. Click Food Menus in the left sidebar and verify the link works normally
1. Click Themes in the left sidebar and activate the Stay theme
1. Click Food Menus in the left sidebar again (without doing a full page refresh first)

<strong>Result:</strong> the custom CPT options in the sidebar are not updated after a theme switch and clicking on a custom CPT that does not apply to the active theme results in an "Invalid post type" error. ([1m31s](https://cloudup.com/c19yuQ5AhLG))

screen shot 2016-07-28 at thu jul 28 12 46 28 pm
<sup>Seen at https://design5279.wordpress.com/wp-admin/edit.php?post_type+hotels+testimonial on staging using Firefox 47.0.1 on Mac OS X 10.11.5</sup>

### PR DESCRIPTION
**Pull request by aduth**
Fixes #7131

This pull request seeks to resolve an issue where sidebar Publish menu items are not updated after changing the theme for a site to reflect post types supported by that theme.

__Testing instructions:__

Verify that after changing a theme, if support is added or removed for a post type, the Publish menu is updated accordingly. It may be easiest to start with a theme that does not have support for any built-in post types, disable [custom content types on writing settings](http://calypso.localhost:3000/settings/writing), then switching to a theme with custom post type support (e.g. Sketch theme supporting Portfolios). I've found that some themes, when switched, appear to activate the "Portfolio" custom content type option automatically, so even when switching to a theme without default support, the Portfolio menu will (correctly) still display.

1. Navigate to the [themes screen](http://calypso.localhost:3000/design)
2. Select a site, if prompted
3. Change the theme
4. Note that the Publish menu items reflect available post types for the theme

/cc @ockham 

Test live: https://calypso.live/?branch=fix/7131-post-types-refresh-theme-change

### CODE REVIEW

File: client/components/data/query-post-types/index.jsx [hunk 1]
```diff
@@ -34,7 +39,7 @@ class QueryPostTypes extends Component {
 }
 
 QueryPostTypes.propTypes = {
-	siteId: PropTypes.number,
+	siteId: PropTypes.number.isRequired,
 	requestingPostTypes: PropTypes.bool,
 	requestPostTypes: PropTypes.func
```
Comment (ockham) [inline client/components/data/query-post-types/index.jsx]: Add a `propType` for `themeSlug`?

**Comment by ockham** [comment]
This is great! Maybe add that one `propType`, but definitiely :shipit:

I’ll file a `Themes` labeled issue for us to remove our `current-theme` state subtree and make `site.options.theme_slug` the single source of truth.

File: client/components/data/query-post-types/index.jsx (hunk 1 above)
Comment (aduth) [inline client/components/data/query-post-types/index.jsx]: >Add a `propType` for `themeSlug`?

Yep. Updated in rebased 4e358ce.

**Comment by aduth** [comment]
Aha, I wasn't aware of the `themes.currentTheme` state. It does seem there's a bit of a disconnect between that and the site object. I'm not opposed to customizing the shape the state tree, but we'd want to at least account for the theme as reflected in a `SITE_RECEIVE` too I think, similar to how we've created a custom [`currentUser.capabilities` reducer](https://github.com/Automattic/wp-calypso/blob/533265f38693c5349a8acd75f323f558fd4fe766/client/state/current-user/reducer.js#L53-L83).

I think I'll go ahead and merge this anyways so we can at least resolve the bug, but we can continue to discuss and iterate on the state structure in subsequent pull requests.
