### PR TITLE
Google Apps: Properly format monthly price for G Suite

### LINKED ISSUE #15192: G Suite: Incorrect price in Japanese Yen
As reported by @chaitanyamsv in `p2MSmN-63K-p2`, the price of G Suite in Japanese Yen is incorrect (`https://wordpress.com/domains/manage/email/:site`):
g-suite-price-in-yen

The issue is probably in this file: https://github.com/Automattic/wp-calypso/blob/master/client/lib/google-apps/index.js
That's where we try to calculate the formatted price we get from the backend from annual to monthly format. I'm guessing, the regexp there does not handle Yens correctly, or we need a different approach altogether.

### PR DESCRIPTION
**Pull request by klimeryk**
The previous approach was hacky and brittle - for example, it failed and burned for Japanese Yen (formatted as `5,800`, with `,` as the thousands separator, not a decimal separator).

The new approach (hattip to @iamgabrielma for the idea) uses `format-currency` and the raw price we get from the backend. Less hacky code and should be future-proof.

### Testing
We show these monthly prices in two places:

1. Domains -> Add -> domain:
screen shot 2017-06-28 at 15 31 47

2. Domains -> Email:
screen shot 2017-06-28 at 15 33 05

Fixes #15192

### CODE REVIEW

File: client/my-sites/upgrades/domain-management/email/add-google-apps-card.jsx [hunk 1]
```diff
@@ -29,14 +32,13 @@ const AddGoogleAppsCard = React.createClass( {
...
+		const prices = get( this.props, 'products.gapps.prices', [] ),
 			googleAppsSupportUrl = support.ADDING_GOOGLE_APPS_TO_YOUR_SITE,
-			price = gapps && gapps.cost_display,
 			selectedDomainName = this.props.selectedSite.domain,
-			{ translate } = this.props;
+			{ currencyCode, translate } = this.props;
 
-		const annualPrice = getAnnualPrice( price );
-		const monthlyPrice = getMonthlyPrice( price );
+		const annualPrice = getAnnualPrice( prices[ currencyCode ], currencyCode );
```
Comment (aidvu) [inline client/my-sites/upgrades/domain-management/email/add-google-apps-card.jsx]: I'm guessing you know that we always return all the prices in there. :)

File: client/my-sites/upgrades/domain-management/email/add-google-apps-card.jsx [hunk 2]
```diff
@@ -29,14 +32,13 @@ const AddGoogleAppsCard = React.createClass( {
 	mixins: [ analyticsMixin( 'domainManagement', 'email' ) ],
 
 	render() {
-		const gapps = this.props.products.gapps,
+		const prices = get( this.props, 'products.gapps.prices', [] ),
```
Comment (aidvu) [inline client/my-sites/upgrades/domain-management/email/add-google-apps-card.jsx]: You could probably deconstruct `props` first, and then include the `currencyCode` here and default the price to 0 or something. If we somehow end w/o a price, might be some errors.

File: client/lib/google-apps/index.js [hunk 3]
```diff
@@ -1,26 +1,19 @@
...
 const GOOGLE_APPS_LINK_PREFIX = 'https://mail.google.com/a/';
-const PRICE_FORMAT = /(\d+[.,]?\d+)/;
 
-function getAnnualPrice( price ) {
-	return price && price.replace( PRICE_FORMAT, ( value ) => {
-		const number = parseFloat( value );
-		return number % 1 === 0 ? number : numberFormat( number, 2 );
-	} );
+function getAnnualPrice( cost, currencyCode ) {
+	return formatCurrency( cost, currencyCode, { precision: 0 } );
```
Comment (aidvu) [inline client/lib/google-apps/index.js]: Nice! Why precision 0 tho? :)

File: client/my-sites/upgrades/domain-management/email/add-google-apps-card.jsx (hunk 2 above)
Comment (delputnam) [inline client/my-sites/upgrades/domain-management/email/add-google-apps-card.jsx]: I'm not sure if this is an issue or not, but it appears that prices for GAPPS are only available in for AUD, BRL, CAD, EUR, GBP, JPY, and USD. So, if I have my currency set to SEK, HUF, ILS, MXN, or NZD, then `monthlyPrice` and `annualPrice` will end up `null`.

Comment (delputnam) [inline client/my-sites/upgrades/domain-management/email/add-google-apps-card.jsx]: Update: D6292-code will fix the problem of prices not being available in all currencies, but support for the new currencies was added in #15492 which was merged after this PR was created, so you will still get `null` for `monthlyPrice` and `annualPrice` in this branch.

File: client/lib/google-apps/index.js (hunk 3 above)
Comment (delputnam) [inline client/lib/google-apps/index.js]: I am not sure we should use precision 0 here. The annual price in NZD is NZ$72.5, but this will show up as NZ$73 in the details section of the component, but as NZ$72.5 in the shopping cart.

Comment (klimeryk) [inline client/lib/google-apps/index.js]: That was based on the original design - and with the old currencies, none provided decimal points. But I didn't like it either, so I'll change the precision to the default one.

File: client/my-sites/upgrades/domain-management/email/add-google-apps-card.jsx (hunk 1 above)
Comment (klimeryk) [inline client/my-sites/upgrades/domain-management/email/add-google-apps-card.jsx]: I'm not sure what you meant here, @aidvu :)

Comment (aidvu) [inline client/my-sites/upgrades/domain-management/email/add-google-apps-card.jsx]: That `prices` won't have some `currencyCode`. But should be fixed now. :)

Comment (klimeryk) [inline client/my-sites/upgrades/domain-management/email/add-google-apps-card.jsx]: Ah, OK.

File: client/my-sites/upgrades/domain-management/email/add-google-apps-card.jsx (hunk 2 above)
Comment (klimeryk) [inline client/my-sites/upgrades/domain-management/email/add-google-apps-card.jsx]: @aidvu I've done one better and did it all in one step thanks to the alternative syntax for [lodash `get`](https://lodash.com/docs#get) (using an array, instead of string). I've used 0 as the default - technically, if there's no price for that currency, I could default to the USD price, but that seems very unlikely, especially with @delputnam's patch.
