### PR TITLE
WooCommerce: Fix document titles for store pages.

### LINKED ISSUE #15956: Store: Setup page has incorrect page title
#### Steps to reproduce
1. Starting at URL from other plugin in Calypso: (I used  https://wpcalypso.wordpress.com/plugins/wordpress-seo/coderkevintest-automated-transfer.blog)
2. Click "Store (BETA)"
3. Page updates, shows "Howdy! Ready to start selling?"
4. Look at tab of page, title is unchanged and now inaccurate.

#### What I expected
Title to say "Store < coderkevintest.wordpress.com" or something similar.

#### What happened instead
Title still says "Yoast SEO Plugin < coderkevintest.wordpress.com"

#### Browser / OS version
OSX Chrome Version 59.0.3071.115 (Official Build) (64-bit)

#### Screenshot / Video
yoast_seo_plugin_ _coderkevintest_ _wordpress_com_and_general_-_yoast_seo_ _coderkevintest_ _wordpress_and_coderkevin_on_autonet_irc_network_ __automattic-bots__241_users_

### PR DESCRIPTION
**Pull request by justinshreve**
Fixes #15956.

We haven't been using `DocumentHead`, which allows us to set the `<title>` tag of our pages. This PR fixes that, and passes document titles that match what we do in similar Calypso pages. The fallback title is just 'Store' which gets used for the dashboard and setup tasks.

To Test:
* Go to `http://calypso.localhost:3000/store/:site` and start clicking around to different pages, making sure a title is set in your browser tab (instead of the previous title sticking around).

### CODE REVIEW

File: client/extensions/woocommerce/index.js [hunk 1]
```diff
@@ -61,6 +62,7 @@ const getStorePages = () => {
 			configKey: 'woocommerce/extension-products',
 			path: '/store/product/:site',
 			parentPath: '/store/products/:site',
+			documentTitle: translate( 'New Product' ),
```
Comment (a8ci18n) [inline client/extensions/woocommerce/index.js]: Hi! I've found a possible matching string that has already been translated **61** times:
`translate( 'Product' )` *ES Score: 7*

Help me improve these suggestions: react with :thumbsdown: if the suggestion doesn't make any sense, or with :thumbsup: if it's a particularly good one (even if not implemented).
