### PR TITLE
Jetpack Pro Dashboard: show "Not supported on multisite" when a product is not supported on a multisite

### LINKED ISSUE #73406: Jetpack Dashboard: Do not show threats for multisites
### Quick summary

Jetpack Scan does not support multisite (sad trombone), but on the Jetpack Dashboard, we're showing the number of the threats for the site. When you click to act, you're told Scan isn't supported for the site.

### Steps to reproduce

1. Add a multisite with a plan that usually would include Scan, e.g. Complete
2. Add something that will throw a threat (I'm not sure what is doing it on my site since Scan isn't supported).
3. Visit the Jetpack Cloud Dashboard.
4. See the 1 Thread icon

### What you expected to happen

If I can't see the threat (and thus can't fix it either), why alert me at all?

### What actually happened

Scary warning with zero information

### Impact

All

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

On the dashboard:
2023-02-15 at 4 44 PM

Click the 1 Threat:
2023-02-15 at 4 45 PM

### PR DESCRIPTION
**Pull request by yashwin**
Closes https://github.com/Automattic/wp-calypso/issues/73406

## Proposed Changes

This PR makes the following changes

- Show `-` with a tooltip showing `Not supported on multisite` when the product is `Scan`
- Show `-` with a tooltip showing `Not supported on multisite` when the product is `Backup` and does not have a backup subscription https://href.li/?https://wp.me/pbuNQi-1jg

#### Testing Instructions

**Prerequisites**

Since these changes are made specifically for agencies, you must set yourself(partner) as an agency - 2c49b-pb. Make sure to switch it back to the previous type.

**Instructions**

1. Run `git checkout fix/handle-unsupported-products-for-multisite` and `yarn start-jetpack-cloud`
2. Open http://jetpack.cloud.localhost:3000/, and you'll be redirected to the /dashboard.
3. Add a multisite with a plan that usually would include Backup & Scan, e.g. Complete.
4. Verify that the Backup column shows the clock or check icon and Scan shows `-` and when hovering over, it shows `Not supported on multisite`. We will show the backup as it is if it is already added - https://href.li/?https://wp.me/pbuNQi-1jg
5. Add another multisite without any plan
6. Verify that both Backup &  Scan shows `-` and when hovering over, it shows `Not supported on multisite`.

Screenshot 2023-03-21 at 12 16 03 PM

Screenshot 2023-03-21 at 12 36 06 PM

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by vitozev — COMMENTED** [review]
Works as expected! I just noticed one minor issue:

image

The "1 available" isn't an actual link for the multisite, is that expected?

**Comment by yashwin** [comment]
> The "1 available" isn't an actual link for the multisite, is that expected?

@vitozev - Thanks for the review. No, it is not. I have fixed it now - https://github.com/Automattic/wp-calypso/pull/74692/commits/df64857113b2c05300597cc5550f30644a936e2f

File: client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content.tsx [hunk 1]
```diff
@@ -175,159 +178,174 @@ export default function SiteStatusContent( {
...
-				status={ status }
-				tooltip={ tooltip }
-				tooltipId={ tooltipId }
-				siteError={ siteError }
-				isLargeScreen={ isLargeScreen }
-			/>
-		);
-	}
+	let content;
+	let updatedTooltip = tooltip;
```
Comment (vitozev) [inline client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content.tsx]: What do you think about not introducing a new variable here?

We can do something like this:

```
const { a } = foo; 
let { b } = foo;
```

We can cache the value of `getRowMetaData` and use it on two separate destructuring assignments.

**Review by vitozev — CHANGES_REQUESTED** [review]
I added one comment that I think will make the code easier to read. WDYT?

**Comment by yashwin** [comment]
> I added one comment that I think will make the code easier to read. WDYT?

I have made the changes - https://github.com/Automattic/wp-calypso/pull/74692/commits/93fda786fb7cfc757aec4217ec1ad1e10c2314ae

**Review by vitozev — APPROVED** [review]
LGTM!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7883000

Thank you @yashwin for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7883000).
