### PR TITLE
Fediverse: remove support for Jetpack/Atomic sites

### LINKED ISSUE #96700: Marketing Connections: Frediverse Connection Status Not Updating After ActivityPub Plugin Installation
### Quick summary

After installing the ActivityPub plugin via My Site > Hosting > Marketing > Frediverse, the plugin works as expected, but Calypso's Marketing Connection still indicates that Frediverse is inactive and continues to prompt the user to install the ActivityPub plugin. 

### Steps to reproduce

1. Start with any Atomic site that has a [custom domain set as primary](https://wordpress.com/support/domains/set-a-primary-address/). 
2. Navigate to My Site > Hosting or Tools (depends on your default dashboard) > Marketing > Connections > Frediverse (https://wordpress.com/marketing/tools/{yourdomain} )
3. Click the "Install ActivityPub" button.
4. On the ActivityPub plugin page click "Install and Activate" 
5. From the plugins page, navigate back to My Site > Hosting or Tools (depends on your default dashboard) > Marketing > Connections > Frediverse. 

### What you expected to happen

Since I started the connection process to Frediverse through the Calypso flow, I expect that after completing step 4, I would be taken back to the Marketing Connections page rather than being redirected to the Installed Plugins section, or just never leave the Connections page? 

I expect to see some configuration options for managing my Frediverse settings, similar to what is demonstrated in the support guide’s video at the 0:18 mark:
Image

### What actually happened

After completing step 4, I am redirected to the Installed Plugins page instead of being taken back to Marketing Connections. 

When I manually navigate back to Marketing Connections and click the dropdown on Frediverse, I am incorrectly prompted to install the ActivityPub plugin again, even though it is already installed and functioning.

Image

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

The ActivityPub plugin works regardless of the Calypso Marketing Connections settings.

You just have to go to Tools > ActivityPub > Settings and change to "Both author and blog profiles" and save. With that set up, when I copy my Username or Profile URL from Tools > Activity Pub and search for them on https://mastodon.social/ my profile information is pulled in and newly published posts too:   

Image

### Platform (Simple and/or Atomic)

Atomic 

### Logs or notes

- user reported: 9080553-zd-a8c

### PR DESCRIPTION
**Pull request by mattwiebe**
Our support in Marketing Connections for Jetpack/Atomic sites has been a bit hacky. It recently grew more fragile to the point where it makes the most sense to rip it out. **Business users can simply install the ActivityPub plugin**, this was just guided them through that process, albeit not well enough to not be confusing.

Fixes #96700

## Proposed Changes

* Remove Fediverse from the Connections page for Jetpack/Atomic sites. They can use the ActivityPub plugin directly.

## Why are these changes being made?
* With the move in #96605 to a new design, there has been some additional strange behavior: clicking the section open would close it immediately. A little more debugging showed that the plugins list is currently pretty unreliable, which is what prompted the weird behavior in #96700.

## Testing Instructions

* With this PR active, navigate to Marketing Connections on an Atomic site. There should be no "Fediverse" section.
* For a Simple site, navigate to Marketing Connections. There **should be** a Fediverse section.

Screenshot 2024-12-02 at 15 23 53

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/my-sites/site-settings/settings-discussion/main.jsx [hunk 1]
```diff
@@ -29,7 +28,6 @@ const SiteSettingsDiscussion = ( { site, translate } ) => (
 		/>
 
 		<SiteSettingsNavigation site={ site } section="discussion" />
-		<FediverseDeprecatedDiscussionSection />
```
Comment (mattwiebe) [inline client/my-sites/site-settings/settings-discussion/main.jsx:32]: This had been here since we migrated the settings from Discussion to Connections. Seemed like a good time to get rid of it.

**Review by obenland — APPROVED** [review]
Tested it with multiple WoA and Simple sites from within the /sites list

**Review by obenland — APPROVED** [review]
Tested it with multiple WoA and Simple sites from within the /sites list
