### PR TITLE
Woo Express: Update redirect post-checkout, add Tracks events

### LINKED ISSUE #75281: Users are not shown the Woo Express purchase page after purchasing a plan
### Quick summary

When a user purchases a Woo Express plan from the pricing grid that we are rolling out, we do not redirect them to the Woo Express post-purchase page. This was the behaviour before we switched to the pricing grid.

### Steps to reproduce

1. For a site with the eCommerce trial, navigate to _Upgrades_ -> _Plans_
2. Once on the page, enable the `plans/wooexpress-small` feature flag by adding `?flags=plans/wooexpress-small` to the URL
3. You should see a pricing grid showing the Essential and Performance plans
4. Click on the CTA to purchase a plan, and complete the purchase from the checkout page

### What you expected to happen

The user should be redirected to the Woo Express upgrade page at `/plans/my-plan/trial-upgraded/:siteSlug`.

### What actually happened

The user was redirected to the legacy eCommerce thank you page.

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by daledupreez**
Fixes #75281

## Proposed Changes

* This PR ensures that when users purchase a Woo Express plan, we redirect them to the Woo Express post-purchase page.
* The PR also makes the following small changes:
  - The plan name displayed on the post-purchase page is now dynamic and derived from the current plan for the site
  - We trigger Tracks events when selecting a plan from the plans grid -- the events use the existing event name on the expired trial and free trial pages, but use a value of `plans_grid` for the `location` event prop, as well as adding a `plan_slug` prop to identify which plan was selected.

## Testing Instructions

* Perform all of the following steps in the Calypso live environment, as the `plans/wooexpress-small` feature flag is enabled there
* Navigate to _Upgrades_ -> _Plans_ for an eCommerce trial site
* Click on a plan CTA in the plans grid
* Verify that you get an appropriate Tracks event with the correct plan slug and location

Screen Shot 2023-04-04 at 12 37 51 PM

* Verify that the right plan is added to your cart
* Complete the purchase
* Verify that after the purchase completes, you are redirected to the Woo Express post-purchase page
* Verify that the plan name reflects the plan you purchased, especially if you purchased an Essential plan:

Screen Shot 2023-04-04 at 12 41 22 PM

* For an expired eCommerce trial site, try to navigate to a page in Calypso - this should redirect you to the expired trial page:

Screen Shot 2023-04-04 at 12 42 30 PM

* Click on a plan CTA in the plans grid - it should not be the same product as above (i.e. it should be Essential if you purchased Performance above - just an interval is not sufficient)
* Verify that a Tracks event is triggered with the correct plan slug and location:

Screen Shot 2023-04-04 at 12 43 06 PM

* Complete the purchase
* Verify that after the purchase completes, you are redirected to the Woo Express post-purchase page
* Verify that the plan name reflects the plan you purchased, especially if you purchased an Essential plan:

Screen Shot 2023-04-04 at 12 43 54 PM

* For the site where you purchased the Essential plan, navigate to _Upgrades_ -> _Plans_
* The Essential plan options should be disabled, so click on the plan CTA for a Performance plan
* Verify that you get an appropriate Tracks event with the correct plan slug and location:

Screen Shot 2023-04-04 at 1 07 55 PM

* Verify that the right plan is added to your cart
* Complete the purchase
* Verify that after the purchase completes, you are redirected to the Woo Express post-purchase page
* Verify that the plan name reflects the plan you purchased:

Screen Shot 2023-04-04 at 12 47 43 PM

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [N/A] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [N/A] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by sixhours** [comment]
I gave this a run-through and added screenshots to testing instructions. I noticed a couple things in the process (that I will dive in to fix shortly, just wanted to document them first):

* ~~The `location` data is missing from the Tracks event when clicked on from the `/plans` page when upgrading from Essential to Performance.~~ -- this has been fixed with [2839e7a](https://github.com/Automattic/wp-calypso/pull/75286/commits/2839e7af7a7256dda6d3c5298658f38f4084a7e7)
* The plan name on the post-checkout screen will often update mid-render so you get a flash of the previous plan name before it settles on the correct one. We should probably add a check to make sure we have the final plan name before displaying the text:


https://user-images.githubusercontent.com/2124984/229872142-5ca2d470-799e-48ad-b419-7e9d46371245.mov

Rather than relying on the site's current plan name, which will take a few seconds to update in state, could we request the name of the plan that was purchased in checkout? Not sure if there's a selector for that, or if checkout passes along that information before we're forwarded to the confirmation screen.

(Also good to note, IMO this shouldn't be a blocker for the CfT.)

**Comment by sixhours** [comment]
I tried a few things for the flash-of-outdated-state problem for a while but couldn't wrap my head around it. 🙃 I don't think it should hold up this review, though.

File: client/my-sites/plans/ecommerce-trial/upgrade-confirmation/index.tsx [hunk 1]
```diff
@@ -22,9 +23,12 @@ const TrialUpgradeConfirmation = () => {
...
 
+	const currentPlanName = selectedSite?.plan?.product_name_short ?? '';
+
 	return (
 		<>
 			<BodySectionCssClass bodyClass={ [ 'ecommerce-trial-upgraded' ] } />
+			<QuerySitePlans siteId={ selectedSite?.ID ?? 0 } />
 			<Main wideLayout>
 				<PageViewTracker
 					path="/plans/my-plan/trial-upgraded/:site"
```
Comment (daledupreez) [inline client/my-sites/plans/ecommerce-trial/upgrade-confirmation/index.tsx:43]: @sixhours, noting for posterity: the `title` prop of `PageViewTracker` should be kept untranslated, as we include that value as-is in the `calypso_page_view` events we record. We want that to stay stable across languages.

Comment (sixhours) [reply client/my-sites/plans/ecommerce-trial/upgrade-confirmation/index.tsx:43]: I suspected there was a reason it was left untranslated, thanks for clarifying!

**Comment by sixhours** [comment]
Yay, isFetchingSitePlan worked a charm! I added some logic to hide the subheading so you don't see this "Your purchase is complete and you're now on the **plan**..." while it's loading:

https://user-images.githubusercontent.com/2124984/230104866-77d1d576-8a5e-402f-8c17-120060f24213.mov

**Review by daledupreez — COMMENTED** [review]
I've retested this after all of @sixhours work, and I think it's ready to ship. I can't approve as the original author, but will go ahead and merge this shortly.
