### PR TITLE
wpcom-block-editor - add fill for closing site editor.

### LINKED ISSUE #46822: Horizon Site Editor: Can't exit the Site Editor
I expect this one may turn out to be just a small one to fix as things may have just got a bit out of sync. To reproduce …

- [Create a site on Horizon with the site editor flag](https://horizon.wordpress.com/new?flags=gutenboarding/site-editor).
- Attempt to exit the site editor and go back to Calypso.

Here's what I see when I attempt to exit the Site Editor right now. My browser tab appears to be crashing here in Chrome MacOS.

image

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
#### Changes proposed in this Pull Request

* Adds fill to fix "Back to dashboard" button in site editor navigation panel when used through calypso.

#### Testing instructions

* Sync changes from this PR to your sandbox using `yarn dev --sync` from the `apps/wpcom-block-editor` directory
* Sandbox widgets.wp.com
* Load the site editor from calypso and verify 'back to dashboard' leads back to calypso as expected.
* Smoke test the post editor.

Fixes #46822

### CODE REVIEW

**Comment by Addison-Stavlo** [comment]
This seems to work in the site editor, however when I load the post editor it is a WSOD:
`Cannot read property '__experimentalMainDashboardButton' of undefined` - it sounds like its not happy with the import from edit-site in that case 🤔

**Comment by Addison-Stavlo** [comment]
> This seems to work in the site editor, however when I load the post editor it is a WSOD:
Cannot read property '__experimentalMainDashboardButton' of undefined - it sounds like its not happy with the import from edit-site in that case 🤔

d7e8c4e resolves this issue.

**Comment by jeyip** [comment]
Hmmm...I think it's an issue on my end, but I'm having difficulty getting the back button to work. 

- I checkout this branch locally
- I run `yarn && yarn dev --sync` from within `apps/wpcom-block-editor`
- I sandbox widgets.wp.com, public-api.wordpress.com, and the test site 
- I load the site editor from calypso in firefox, chrome, etc., and I'm still getting the `testsite123.wordpress.com refused to connect.` error when I click on the dashboard button

I've tried "un-sandboxing" and sandboxing the environment again, _only_ sandboxing widgets.wp.com and the test site (not public api), _only_ sandboxing widgets.wp.com, and reinstalling all node modules. Is there something I might be missing Addie?

File: apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js [hunk 1]
```diff
@@ -23,6 +27,13 @@ import { STORE_KEY as NAV_SIDEBAR_STORE_KEY } from '../../../../editing-toolkit/
  */
 import { inIframe, isEditorReadyWithBlocks, sendMessage, getPages } from '../../utils';
 
+/**
+ * Conditional dependency.  We cannot use the standard 'import' since this package is
+ * not available in the post editor and causes WSOD in that case.  Instead, we can
+ * define it from 'require' and conditionally check if it is available for use.
+ */
+const editSitePackage = require( '@wordpress/edit-site' );
```
Comment (jeyip) [inline apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js:35]: What a curious problem 🤔 -- your approach makes sense, and I can't think of a better way to handle the issue.

I do wonder if there is already an established convention in Calypso or Gutenberg. I'll try and do a cursory search through the codebase tomorrow.

File: test/e2e/specs/wp-gutenberg-experimental-features-spec.js [hunk 2]
```diff
@@ -26,6 +26,8 @@ const EXPERIMENTAL_FEATURES = {
 	'@wordpress/block-editor': [ '__experimentalBlock', '__experimentalInserterMenuExtension' ],
 	'@wordpress/date': [ '__experimentalGetSettings' ],
 	'@wordpress/interface': [ '__experimentalMainDashboardButton' ],
+	'@wordpress/components': [ '__experimentalNavigationBackButton' ],
+	'@wordpress/edit-site': [ '__experimentalMainDashboardButton' ],
```
Comment (jeyip) [inline test/e2e/specs/wp-gutenberg-experimental-features-spec.js:30]: Out of curiosity, is there a reason we added `'@wordpress/edit-site': [ '__experimentalMainDashboardButton' ]` to the list of Calypso dependencies?

I see the use of `__experimentalMainDashboardButton` in `iframe-bridge-server.js`, but it's already being exported by `@wordpress/interface`.

**Review by jeyip — COMMENTED** [review]
Definitely not an expert on the calypso iframe bridge server or slotfills, but generally speaking, everything in this PR looks reasonable to me 👍 . I'll read up more about the slotfills first thing tomorrow https://developer.wordpress.org/block-editor/developers/slotfills/

File: test/e2e/specs/wp-gutenberg-experimental-features-spec.js (hunk 2 above)
Comment (Addison-Stavlo) [reply test/e2e/specs/wp-gutenberg-experimental-features-spec.js:30]: The [version from the edit-site package](https://github.com/WordPress/gutenberg/blob/master/packages/edit-site/src/components/main-dashboard-button/index.js) is the one we specifically set up for the navigation panel.  It is the one [whose slot is added in the Nav panel](https://github.com/WordPress/gutenberg/blob/d12c81d8ac45c785d2d2633724e0bdbaa8aa9198/packages/edit-site/src/components/navigation-sidebar/navigation-panel/templates-navigation.js#L18), so that is the one we need to use for the fill.

File: apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js (hunk 1 above)
Comment (Addison-Stavlo) [reply apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js:35]: Yeah it is a bit odd.  There is some 'magic' going on in how we set up the dependency system for `wp.stuff` globals in the editor.  If you look in the post editor console in the post.php context, or the site editor in (i think index.php) you can find the dependencies available under global `wp`.  So `wp.editPost` in the post editor, or `wp.editSite` in the site editor.

The other option is digging into this magic and ensuring the post editor has `wp.editSite` as well, but to be honest I think that wouldn't be a great solution since we would be bundling an entire extra package that would never be used into the post editor, inflating the size only for the sake of how we write one odd import.  

I don't think we have imported anything from edit-site in calypso in the past, and the only reason it seems sticky here is because we are working in the wpcom-block-editor and that dependency global magic going on.  In other places where package bundling works 'normally' it wouldn't be an issue.

**Comment by Addison-Stavlo** [comment]
> Hmmm...I think it's an issue on my end, but I'm having difficulty getting the back button to work.
> Is there something I might be missing Addie?

🤔  Im not sure exactly.  I ran `yarn install` from the calypso root, and `yarn dev --sync` from `apps/wpcom-block-editor` and it was working.  I wonder if widgets wasn't getting sandboxed for some reason... or if you need to clear your cache to get it to pick up on the changes?  I think I remember having to some cache issues when working with wpcom-block-editor before.

**Comment by jeyip** [comment]
> or if you need to clear your cache to get it to pick up on the changes? 

Ahhh good call. If anyone else tests this and has trouble, I had to clear each of my browser caches individually to pick up the changes 👍

### Testing
I could successfully navigate back to the calypso home screen from:

- Chrome
- Firefox
- Edge

The IE11 site editor wouldn't load for me 🙃. The Safari browser wasn't responding to "Back to dashboard" button clicks (Both of these, however, were issues I saw on master as well) I think it's fair to create a follow-up tickets for safari and IE11 to be prioritized accordingly.

**Comment by Addison-Stavlo** [comment]
>  The Safari browser wasn't responding to "Back to dashboard" button clicks (Both of these, however, were issues I saw on master as well)

Thats so weird!  Im noticing that as well, with or without these changes.  I wonder what the deal is there.  This only seems to be true through the calypso iframe. 🤔

File: apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js (hunk 1 above)
Comment (jeyip) [reply apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js:35]: I did a really brief search and couldn't find any existing examples of people doing this in Calypso or Gutenberg. This lgtm 👍

**Review by jeyip — APPROVED** [review]

**Comment by Addison-Stavlo** [comment]
>  Im noticing that as well

Or not... for me it seems like issues with sandboxing from safari, its actually running the production API still and trying to goto `*/wp-admin/index.php`.  Once its actually running these changes I think it should work.

**Review by david-szabo97 — APPROVED** [review]
Followed the testing instructions and it works well! LGTM ✅ 🚢

**Review by vindl — APPROVED** [review]
LGTM :shipit:
