### PR TITLE
Flaky E2E: some more tweaks to the Site Assembler spec.

### LINKED ISSUE #81156: Flaky E2E: Select "Sections"
### Spec file

specs/onboarding/ftme__site-assembler.ts

### TeamCity ID

10672654

### Logs

```
======= Failed test run #1 ==========
  locator.scrollIntoViewIfNeeded: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for getByRole('listbox', { name: 'Block patterns' }).getByRole('option', { name: 'Heading with two images and descriptions', exact: true })
  ============================================================
  at SiteAssemblerFlow.scrollIntoViewIfNeeded [as selectLayoutComponent] (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/flows/site-assembler-flow.ts:57:16)
      at Object.<anonymous> (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/onboarding/ftme__site-assembler.ts:102:4)
======= Failed test run #2 ==========
  locator.scrollIntoViewIfNeeded: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for getByRole('listbox', { name: 'Block patterns' }).getByRole('option', { name: 'Heading with two images and descriptions', exact: true })
  ============================================================
  at SiteAssemblerFlow.scrollIntoViewIfNeeded [as selectLayoutComponent] (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/flows/site-assembler-flow.ts:57:16)
      at Object.<anonymous> (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/onboarding/ftme__site-assembler.ts:102:4)
```

image

### PR DESCRIPTION
**Pull request by worldomonation**
Fixes https://github.com/Automattic/wp-calypso/issues/81156.

## Proposed Changes

This PR updates the `selectLayoutComponent` method to support both index and name-based selections. This is so that site asssembler components being removed or added do not affect the spec.

Additionally, after inserting a new component, the wait method is new and is based on counter.

## Testing Instructions

Ensure the following build configurations are passing:
  - [x] Calypso E2E (desktop)
  - [x] Calypso E2E (mobile)
  - [x] Pre-Release E2E

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: test/e2e/specs/onboarding/ftme__site-assembler.ts [hunk 1]
```diff
@@ -92,35 +92,36 @@ describe( 'Site Assembler', () => {
...
+			await siteAssemblerFlow.clickButton( 'Save and continue' );
 		} );
 
 		it( 'Click "Save and continue" and land on the Site Editor', async function () {
-			await Promise.all( [
-				page.waitForURL( /processing/ ),
-				siteAssemblerFlow.clickButton( 'Save and continue' ),
-			] );
+			const urlPromise = page.waitForURL( /processing/ );
+			await siteAssemblerFlow.clickButton( 'Start adding content' );
```
Comment (arthur791004) [inline test/e2e/specs/onboarding/ftme__site-assembler.ts:122]: ha, I just want to address this change as well 😆

File: packages/calypso-e2e/src/lib/flows/site-assembler-flow.ts [hunk 2]
```diff
@@ -35,39 +35,56 @@ export class SiteAssemblerFlow {
...
+	}: { name?: string; index?: number } = {} ): Promise< void > {
 		// To reduce network load times, abort any request for
 		// placeholder images.
 		await this.page.route( '**/*.png', ( route ) => {
 			route.abort( 'aborted' );
 		} );
 
+		// Convert index to the accessible name of a component.
+		if ( index !== undefined ) {
+			name = ( await this.page
```
Comment (arthur791004) [inline packages/calypso-e2e/src/lib/flows/site-assembler-flow.ts:63]: I got an error below and it seems the return value is not a string

```bash
 locator.scrollIntoViewIfNeeded: Error while parsing selector `option[name=[object Object]]` - unexpected symbol "[" at position 12 during parsing attribute value
```

Comment (arthur791004) [reply packages/calypso-e2e/src/lib/flows/site-assembler-flow.ts:63]: Oops...I forgot to re-build the test 🤣

**Review by arthur791004 — APPROVED** [review]
Work as expected, thanks 👍
