### PR TITLE
Sharing: Update Facebook preview

### LINKED ISSUE #23656: Sharing: Facebook preview doesn't match the created card
#### Steps to reproduce
0. Use a test site that has a Premium or Business plan and Facebook connection enabled.
1. Navigate to `https://wordpress.com/posts/{site}`.
2. For individual post click on the more options drop-down menu and select `Share`.
3. Click on `Preview` and capture a screenshot of the generated preview.
4. Click on `Share post` and compare the actual results of the Facebook card with generated Preview.
5. Notice that there are a couple of things missing in the preview like card title and description after the image.

### PR DESCRIPTION
**Pull request by Copons**
Fix #23656

Make Sharing's Facebook preview look as similar as possible to the current Facebook post.

## Changes

- Previews of posts _with_ images now consist of:
`[ content summary | permalink | featured image ]`

screen-shot-2018-04-25-at-16-14-13

- Previews of post _without_ images now consist of:
`[ content summary | permalink | card using the site icon ]`

screen-shot-2018-04-25-at-16-14-07

- Add a border to the profile picture.
Code looks a bit weird (compared to a simple `border: 1px solid gray`), but it's how FB does it to have a semitransparent border on top of the image.

- Guard the profile picture against broken Graph API (last time it happened while I was working on this!).

- Adjust text colors and weights.

- Add a border to the preview image as well. (Same approach as the profile picture)

- Add a period after "published an article on WordPress".

- Added the "Just now" relative time string, so that the "WordPress" app name is not weirdly alone in the second meta line.

- Fix some graphic glitches of the Facebook card preview (`FacebookPreview` component), and adjust it to look as much as possible like the real thing.

## Screenshots

| Before | Facebook | After |
| --- | --- | --- |
| screen shot 2018-04-20 at 11 13 15 | screen shot 2018-04-20 at 11 13 22 | screen shot 2018-04-20 at 11 49 25 |
| screen shot 2018-04-26 at 12 16 35 | screen shot 2018-04-26 at 12 18 00 | screen shot 2018-04-26 at 12 31 11 |

## Testing instructions

- Use a test site that has a Premium or Business plan and Facebook connection enabled.
- Navigate to `https://wordpress.com/posts/{site}`.
- Test for both posts with and without images.
- For an individual post, click on the more options drop-down menu and select `Share`.
- Click on `Preview` and capture a screenshot of the generated preview.
- Click on `Share post` and compare the actual results of the Facebook card with the generated Preview.

Regression checks:

- Try the Facebook (card) preview for site (`/settings/traffic/{site}`) and post editor (`/post/{site}`).
- Check if they are broken, and if they're still consistent with the Facebook real things.

### CODE REVIEW

File: client/components/share/facebook-share-preview/index.jsx [hunk 1]
```diff
@@ -45,14 +45,18 @@ export class FacebookSharePreview extends PureComponent {
...
-									{ translate( 'published an article on {{a}}WordPress{{/a}}', {
+									{ translate( 'published an article on {{a}}WordPress{{/a}}.', {
 										components: {
 											a: <a href="#" />,
 										},
 									} ) }
 								</span>
 							</div>
 							<div className="facebook-share-preview__meta-line">
+								{ translate( 'Just now', {
```
Comment (a8ci18n) [inline client/components/share/facebook-share-preview/index.jsx]: Hi! I've found a possible matching string that has already been translated **61** times:
`translate( 'just now' )` *ES Score: 12*

Help me improve these suggestions: react with :thumbsdown: if the suggestion doesn't make any sense, or with :thumbsup: if it's a particularly good one (even if not implemented).

File: client/components/share/facebook-share-preview/index.jsx [hunk 2]
```diff
@@ -45,14 +45,18 @@ export class FacebookSharePreview extends PureComponent {
 									{ externalDisplay }
 								</a>
 								<span>
-									{ translate( 'published an article on {{a}}WordPress{{/a}}', {
+									{ translate( 'published an article on {{a}}WordPress{{/a}}.', {
```
Comment (a8ci18n) [inline client/components/share/facebook-share-preview/index.jsx]: :ok: This change is safe, we'll keep the existing 19 translations.

**Comment by kwight** [comment]
Following the instructions and using a default post with no additional message, I seem to have gotten an excerpt added above the (somewhat mangled) post URL (other changes look good though):

screen shot 2018-04-23 at 10 39 36 am

**Comment by vindl** [comment]
While testing I noticed an edge case for posts that contain no images. In that case Facebook will display Blavatar along with the card, but our preview is not matching that and is only showing text.

To reproduce, create a test post that only has a title and a single line of text. Then in Blog posts select `Share` for that post, and compare the preview with what's actually shared on Facebook.

**Comment by Copons** [comment]
I'm putting this PR on hold for now, because I've noticed that we have 2 completely different preview components, and we're likely better off using only one of them.

File: client/components/seo/facebook-preview/index.jsx [hunk 3]
```diff
@@ -10,9 +11,10 @@ import { compact } from 'lodash';
 import { firstValid, hardTruncation, shortEnough } from '../helpers';
 
 const TITLE_LENGTH = 80;
-const DESCRIPTION_LENGTH = 270;
+const DESCRIPTION_LENGTH = 200;
```
Comment (kwight) [inline client/components/seo/facebook-preview/index.jsx]: Why does this need to change?..

File: client/components/seo/facebook-preview/index.jsx [hunk 4]
```diff
@@ -31,11 +33,7 @@ export class FacebookPreview extends PureComponent {
 		return (
 			<div className={ `facebook-preview facebook-preview__${ type }` }>
 				<div className="facebook-preview__content">
-					{ image && (
-						<div className="facebook-preview__image">
-							<img src={ image } />
-						</div>
-					) }
+					<div className="facebook-preview__image">{ image && <img src={ image } /> }</div>
```
Comment (kwight) [inline client/components/seo/facebook-preview/index.jsx]: Should the conditional render be on the whole `div`, or do we need to maintain an empty `div` for some reason?

File: client/components/share/facebook-share-preview/index.jsx [hunk 5]
```diff
@@ -7,36 +8,60 @@
...
 						<div className="facebook-share-preview__profile-picture-part">
-							<img
-								className="facebook-share-preview__profile-picture"
-								src={ externalProfilePicture }
-							/>
+							{ ! isProfileImageBroken && (
+								<img
+									className="facebook-share-preview__profile-picture"
+									src={ externalProfilePicture }
+									onError={ this.setBrokenProfileImage }
```
Comment (kwight) [inline client/components/share/facebook-share-preview/index.jsx]: This all feels quite... circular 🙃 Can we not determine the validity of the profile image higher up, and send down a regular prop, getting rid of the need for local state management?

File: client/components/seo/facebook-preview/index.jsx (hunk 3 above)
Comment (Copons) [reply client/components/seo/facebook-preview/index.jsx]: In my tests with longer post contents, I've noticed that FB cuts the text at _roughly_ 200 chars (actually something like 196, but for the sake of magic-number-clarity, I chose to be off of ~4 chars, which is still way better than being off of ~74 🙂).

File: client/components/seo/facebook-preview/index.jsx (hunk 4 above)
Comment (Copons) [reply client/components/seo/facebook-preview/index.jsx]: So, this is a kind of effort of trying to avoid regressions.

The `img` is styled as `width: 100%; height: auto`, which means that it's as large as its container, and the height is calculated accordingly.

Though, that container is `width: 158px; height: 158px`, no matter what it contains or if it contains anything at all.

If we alternated between image and empty container, we would need to style both as `width: 158px; height: 158px;`, risking to screw up the image aspect ratio.

File: client/components/share/facebook-share-preview/index.jsx (hunk 5 above)
Comment (Copons) [reply client/components/share/facebook-share-preview/index.jsx]: I'm not quite sure how to do what you mean?
There has been a day while I was working on this PR, that the Graph API was partially down or broken.
What happened was that we had the correct profile picture URL, but it returned `4xx`.

While I was researching the issue, I've found out that it's something quite common for the Graph API (there have been reports of similar issues for years).
Maybe "common" is not the right word. Maybe it's just "sometimes", but it's also unpredictable enough, and it really makes our preview look broken.

That `onError` is a quick check to avoid showing the broken image icon, when just the image CDN (or whatever fails) is down, but the rest of the API is up.

File: client/blocks/sharing-preview-pane/utils.js [hunk 6]
```diff
@@ -56,3 +56,17 @@ export const getExcerptForPost = post => {
 		)
 	);
 };
+
+export const getSummaryForPost = ( post, translate, maxWords = 60 ) => {
```
Comment (gwwar) [inline client/blocks/sharing-preview-pane/utils.js]: @Copons do they normally truncate by words or approximate character length?

File: client/components/seo/facebook-preview/index.jsx [hunk 7]
```diff
@@ -1,4 +1,5 @@
 /** @format */
+/* eslint-disable jsx-a11y/alt-text */
```
Comment (gwwar) [inline client/components/seo/facebook-preview/index.jsx]: Why are we disabling these?

File: client/blocks/sharing-preview-pane/utils.js (hunk 6 above)
Comment (gwwar) [reply client/blocks/sharing-preview-pane/utils.js]: Did some testing in FB, and looks like it's a bit arbitrary. ~240 characters for single word chars and ~500ish for longer words.

Let's leave some JSDoc that this function is an approximation of the truncation logic of what our servers sent to FB, and that it will be out of sync with that and FB's actual truncation algorithm.

If there are specific truncation cases we'd like to cover, lets add unit tests here.

**Comment by gwwar** [comment]
Thanks for updating this. It'll always be a constant battle to get these previews somewhat close. I left a few notes, but no blockers on this one. Let's try to rebase to see if the canary tests clear up.

File: client/components/share/facebook-share-preview/index.jsx (hunk 5 above)
Comment (rodrigoi) [reply client/components/share/facebook-share-preview/index.jsx]: We can't verify if the image is valid (I don't think valid is the right word. Maybe _available_?) until we try to load it. It may be a bit overkill, but we can take `facebook-share-preview__profile-picture` and make it a small component out of it that'll handle the `onError`, and maybe retry after a while.
