### PR TITLE
ETK Timeline Block: Use enableAlpha=true to allow 'transparent' as an available `background` color

### LINKED ISSUE #63626: Error when removing Timeline Block Background color
### Quick summary

When removing the background color from the Timeline block, an error is showing in the console and the block only shows the "Attempt Block Recovery" message. 

### Steps to reproduce

1. Add in a Timeline block
2. Go into a Timeline Entry child block settings and press "clear" to remove the background color from the block.

Markup on 2022-05-14 at 15:57:57

3. Save draft.
4. Reload page.

### What you expected to happen

I don't think this block should have a background color by default and I would expect that we can remove the background color if needed.

### What actually happened

When saving the change, an error is shown in the console.

Markup on 2022-05-14 at 15:52:51

```
Block validation: Expected attributes  
0: Array(3) [ "style", "background-color:#eeeeee", true ]
1: Array(3) [ "class", "wp-block-jetpack-timeline-item", true ]
length: 2

​instead saw  
0: Array(3) [ "class", "wp-block-jetpack-timeline-item", true ]
length: 1
```

### Context

5212968-zen

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

_No response_

### Browser, operating system and other notes

_No response_

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

The workaround that I found was to add in a background color to match the site editor, but I think a better solution would be, to be able to clear the background color if desired.

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #63626

Building on evaluation in https://github.com/Automattic/wp-calypso/pull/65104#issuecomment-1170735113

Opened https://github.com/WordPress/gutenberg/issues/42170 to see if there's a better way.

## Proposed Changes

Uses `enableAlpha={ true }` to make transparency available to the Timeline Block:

image

This lets the user override the default `background` color, and let the background color of the page appear.

#### Testing Instructions

1. Sandbox a WordPress.com site.
2. Install ETK from branch: `install-plugin.sh editing-toolkit improve/timeline-block-transparent-color`
3. Create a new post.
4. Add a "Timeline Block" to the post.
5. Verify the Timeline Block has the default background color `#EEEEEE`:

image

image

6. Verify the Timeline Block allows accessing the alpha channel of the color picker:

image

7. Select a transparent color and verify it's applied to the Timeline Block:

image

image

8. Switch to the Code Editor, and then back to the Visual Editor and verify the Timeline Block isn't crashed.

### CODE REVIEW

File: apps/editing-toolkit/editing-toolkit-plugin/jetpack-timeline/blocks/src/timeline-item.js [hunk 1]
```diff
@@ -88,6 +109,7 @@ export function registerTimelineItemBlock() {
 										onChange: ( background ) =>
 											setAttributes( { background: background || DEFAULT_BACKGROUND } ),
 										label: __( 'Background Color', 'full-site-editing' ),
+										colors: Colors(),
```
Comment (p-jackson) [inline apps/editing-toolkit/editing-toolkit-plugin/jetpack-timeline/blocks/src/timeline-item.js]: The way `Colors` is being used means that it should be a "hook" instead of a component. [The capitalised function name means it's a component](https://reactjs.org/docs/jsx-in-depth.html#user-defined-components-must-be-capitalized), and so you'd expect it to be used like `<Colors />`. But it really just wants to wrap to the `useSetting` hook with its own logic, and so it should be [a custom hook](https://reactjs.org/docs/hooks-custom.html).

So maybe rename `Colors` to something like `useBackgroundColors` or something like that?

To satisfy the linter you'll also need to convince it that the `edit` attribute on line 55 represents a React component. Which you can do with something like:
```javascript
edit: function Edit( { attributes, clientId, setAttributes } ) {
```

File: apps/editing-toolkit/editing-toolkit-plugin/jetpack-timeline/blocks/src/timeline-item.js [hunk 2]
```diff
@@ -14,6 +15,26 @@ import { TimelineIcon } from './icon';
...
 
+function Colors() {
+	const colors = useSetting( 'color.palette' );
+	let appendTransparent = true;
+	if ( colors.length > 0 ) {
+		colors.forEach( ( color ) => {
+			if ( 'transparent' === color.color ) {
+				appendTransparent = false;
+			}
+		} );
```
Comment (p-jackson) [inline apps/editing-toolkit/editing-toolkit-plugin/jetpack-timeline/blocks/src/timeline-item.js]: This one's a non-blocking comment, but just another way to do the loop that is (arguably) more semantic 🤷 

```suggestion
		const appendTransparent = colors.every( ( { color } ) => 'transparent' !== color );
```

**Review by p-jackson — CHANGES_REQUESTED** [review]
😎 I love it when a plan comes together.

Not sure how much of an issue this is, or even how much we can do about it, but the colour name and code aren't visible because I guess the algorithm can't figure out whether the text should be white or black:
CleanShot 2022-07-07 at 21 44 39@2x

The "request changes" is for the comment about components/hooks

File: apps/editing-toolkit/editing-toolkit-plugin/jetpack-timeline/blocks/src/timeline-item.js (hunk 1 above)
Comment (danielbachhuber) [reply apps/editing-toolkit/editing-toolkit-plugin/jetpack-timeline/blocks/src/timeline-item.js]: > The way `Colors` is being used means that it should be a "hook" instead of a component. [The capitalised function name means it's a component](https://reactjs.org/docs/jsx-in-depth.html#user-defined-components-must-be-capitalized), and so you'd expect it to be used like `<Colors />`. But it really just wants to wrap to the `useSetting` hook with its own logic, and so it should be [a custom hook](https://reactjs.org/docs/hooks-custom.html).

@p-jackson I learn something new every day!

> So maybe rename `Colors` to something like `useBackgroundColors` or something like that?
> 
> To satisfy the linter you'll also need to convince it that the `edit` attribute on line 55 represents a React component. Which you can do with something like:

Made this change with 9ad6752f3c

**Comment by danielbachhuber** [comment]
> Not sure how much of an issue this is, or even how much we can do about it, but the colour name and code aren't visible because I guess the algorithm can't figure out whether the text should be white or black:

@p-jackson Yep, this is a Gutenberg problem: https://github.com/WordPress/gutenberg/issues/42230

I submitted a pull request for it: https://github.com/WordPress/gutenberg/pull/42232

**Review by p-jackson — APPROVED** [review]
This has been a nice source of upstream contributions :)

Tested and everything still working as expected 👍 

I've asked here p1657236274127459-slack-C029GN3KD to see whether there's anyone we should be asking about adding this new feature, or at the least letting them know what we're doing. Since this one is more of an enhancement than a straight bug-fix.

**Comment by simison** [comment]
Why "transparent" background color instead of just no background color set?

This is the UI how I'd expect, done via [block supports](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-supports/#color-background) API:

Screenshot 2022-07-08 at 10 36 45
Screenshot 2022-07-08 at 10 36 50
image

**Comment by danielbachhuber** [comment]
> Why "transparent" background color instead of just no background color set?
> 
> This is the UI how I'd expect, done via [block supports](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-supports/#color-background) API:

@simison The Paragraph Block doesn't have a default color specified for `background`. As such, removing the specified color restores its "no color" default state.

The Timeline Block _does_ have a default color, so removing the specified color restores its default color state.

**Comment by danielbachhuber** [comment]
@p-jackson Caught a classic JavaScript mistake with some final testing 😱 0631190e9973535310b4c84b23f63689ff5628c6

**Comment by simison** [comment]
> The Paragraph Block doesn't have a default color specified for background. As such, removing the specified color restores its "no color" default state.

Gotcha. UI that seems very custom and clunky in Philip's [screenshot](https://github.com/Automattic/wp-calypso/pull/65266#pullrequestreview-1031285738) above is what got me worried.

@mtias are there core blocks/other blocks with good examples of handling for background color transparency settings?

Quote and background are the only ones I can think that might have background color by default, but I didn't see transparency settings for those. Didn't look very hard either.

Screenshot 2022-07-08 at 15 47 39

**Comment by p-jackson** [comment]
The custom colour picker in global styles and the core block settings has a slider for the alpha channel. This allows users to choose a transparent colour.

CleanShot 2022-07-11 at 13 41 56@2x

I didn't notice this before! But I'm also not sure why the colour picker in the Timeline block doesn't have the alpha slider. Maybe it's just a matter of updating the version of `@wordpress/components` the ETK plugin uses? (although I would have thought this was one of the shared packages)

**Comment by simison** [comment]
If the timeline block doesn't yet simply declare global styles background color support, changing it do do so might give you transparency slider "for free".

**Comment by danielbachhuber** [comment]
> If the timeline block doesn't yet simply declare global styles background color support, changing it do do so might give you transparency slider "for free".

@simison I tried adding the following to the `jetpack/timeline-item` block:

```
supports: {
	color: {
		text: false,
		background: true,
	},
},
```

However, the declaration above simply presents the same UI:

image

Is there something I'm missing?

---

> But I'm also not sure why the colour picker in the Timeline block doesn't have the alpha slider. Maybe it's just a matter of updating the version of `@wordpress/components` the ETK plugin uses?

@p-jackson The `PanelColorSettings` component supports an `enableAlpha` prop that achieves what you're referring to:

image

However, the UI isn't particularly intuitive:
1. First, you have to click on the background color preview to open the color picker.
2. Then, in order to get true transparency, you have to switch `rgba()` and dial the alpha channel back entirely. The alpha slider isn't entirely sufficient, as it generates a nonsensical HEX value of `#94292900`.

image

---

I'd like to land the PR as-is unless there's a strong opinion against.

I think this PR is the clearest way, given our current possibilities, for the user to clear the background color from the block:
* https://github.com/WordPress/gutenberg/issues/42230 will eventually address the core idiosyncrasy.
* Ideally, the UI would be a "Remove background color" button on the `PanelColorSettings` component, but I don't think it's likely for core to implement it in any sort of timely manner.

**Comment by p-jackson** [comment]
> The `PanelColorSettings` component supports an `enableAlpha` prop that achieves what you're referring to

😮 🎊

> I'd like to land the PR as-is unless there's a strong opinion against.

I don't have a strong opinion about whether the UI in this PR is good or bad, but I do feel like our mandate for doing something in a non-standard way isn't very strong.

The feature request was mixed in with a more serious bug report, so we're probably only looking into it because of it was reported along with the bug. So it's not too clear to me how popular this feature would be. If 1 in 1000 Timeline users would like to have a transparent background, then I don't think that justifies creating a custom way of dealing with transparency. We're better off allowing users to use the standard tools to solve their problems. That way if Core comes up with a more intuitive way to set transparency, this block will automatically inherit it.
If the breakdown was more like 500 in 1000 users want transparency then there might be some justification in doing something non-standard to optimise a common flow. But I think it's probably closer to the first number.

**Comment by danielbachhuber** [comment]
@p-jackson @simison What would you suggest as next steps for this PR?

**Comment by danielbachhuber** [comment]
Switched to `enableAlpha={ true }` with 105237eb2a

While I _really wanted_ to use my original 'transparent' color button, it would put us in a little bit of a future compatibility bind: 'transparent' would also need to be available as a color option.

I feel somewhat comforted by the fact there may be a better path to selecting 'transparent' in the future: https://github.com/WordPress/gutenberg/issues/42170#issuecomment-1182555529

**Comment by p-jackson** [comment]
I think that's the right call. The transparency setting could be more obvious, but I'd much rather see that design come from the WordPress side of things.
