### PR TITLE
Use wp/v2 tags and category delete to delete the right term

### LINKED ISSUE #36620: Post Tags Bug: Adding an apostrophe to the end of a tag causes tag deletion to delete tags that do not have the apostrophe
#### Steps to reproduce
1. Starting at URL: Create a WordPress.com site
2. Publish some posts with the tag books
3. Accidentally create a second tag - books'
4. Delete books' from the WordPress.com dashboard under Manage - Settings - Writing

#### What I expected
I expected books' with the apostrophe to be deleted.

#### What happened instead
Books without the apostrophe was deleted, which also makes all of your posts tagged with books no longer have that tag. 

This was particularly painful for a user who had thousands of posts and multiple tags with apostrophes at the end. They were trying to clean up their tags list by deleting the empty tags with apostrophes. They now have to re-tag hundreds of those posts after having their tags mistakenly deleted via this bug.

The apostrophed tags can be removed in WP-Admin.

#### Browser / OS version
All of them. 

#### Screenshot / Video
tags

#### Context / Source
#reallife #anxiety #anxiety-flow #stresscase #painpoint  #user-report

### PR DESCRIPTION
**Pull request by gwwar**
Fixes https://github.com/Automattic/wp-calypso/issues/36620 

Slugs for taxonomies aren't guaranteed to be unique. This means that wpcom v1.x APIs that rely on this behavior may in fact delete or update the wrong term. For example a tag of `test` and `test'` will share a slug of `test` but have a different `id` and `name` field.

This PR only updates the delete method to use the wp/v2 taxonomies endpoint https://developer.wordpress.org/rest-api/reference/taxonomies/#definition-2

Overall I'd recommend a full refactor of this section to use `wp/v2` APIs, but I'd like a smaller fix here to address the terrible behavior noted in the parent issue. I've added https://github.com/Automattic/wp-calypso/issues/36877 to track the larger refactor.

66780737-7657ba80-ee86-11e9-856f-e571a25540dc

### Testing Instructions
- It may be more stable to visit `wp-admin/edit-tags.php?taxonomy=post_tag` and add/edit tags there.
- Create Posts with both `test'` and other posts with `test`
- Visit http://calypso.localhost:3000/settings/taxonomies/post_tag/siteId (Manage > Settings > Tags)
- Delete a tag `test'`
- Verify that `test'` was deleted only, not `test` and that tag references are removed from posts.
- Repeat for Categories (Manage > Settings > Categories)
- Manually visit a custom taxonomy by visiting `http://calypso.localhost:3000/settings/taxonomies/${ taxonomy }/${ siteId }` (The UI may be a bit funky)
- Verify that deleting still works as expected.

### Notes
- The Calypso Classic editor allows creating tags of `test'` but will save with a tag of `test`
- The Block Editor will properly add and tag `test'`
- There's some odd behavior with adding a single tag in the Block-Editor which should be resolved in a separate PR

### CODE REVIEW

**Review by mmtr — COMMENTED** [review]
Overall this works as intended and terms are removed using the `wp/v2` API. 

I had problems adding tags with quotes using the block editor (they are created but posts are not assigned to them) although that's not related to this PR.

I'd recommend to avoid the code duplication by moving the callback to an independent function and calling it from the requests to both `wp/v2`/`rest/v1.1`.

Also, the `wp/v2` endpoint seems to work seamless with any taxonomy. Is there any reason why we don't use for all of them instead of just tags and categories?

**Comment by gwwar** [comment]
> Also, the wp/v2 endpoint seems to work seamless with any taxonomy. Is there any reason why we don't use for all of them instead of just tags and categories? 

Thanks @mmtr I wasn't quite sure of the name mapping. For example, the actual taxonomy of tags isn't `tags` but `post_tag`. Happy to follow up with other custom ones, if I can verify that it works.

I'll try to tidy this smaller fix further tomorrow, and will make a few issues for a full refactor of the section (might be harder to untangle other pieces of global state, there's some fancy state caching internally).

File: client/state/terms/test/actions.js [hunk 1]
```diff
@@ -47,7 +47,7 @@ const testTerms = [
 	},
 ];
 const siteId = 2916284;
-const taxonomyName = 'jetpack-testimonials';
```
Comment (gwwar) [inline client/state/terms/test/actions.js]: jetpack-testimonials are a CPT but not a taxonomy

**Comment by gwwar** [comment]
@Automattic/team-calypso @mmtr this is ready for another look.

File: client/state/terms/actions.js [hunk 2]
```diff
@@ -119,72 +119,122 @@ export function updateTerm( siteId, taxonomy, termId, termSlug, term ) {
...
+ *
+ * @param   {Number} siteId   Site ID
+ * @param   {String} taxonomy Taxonomy Slug
+ * @returns {Promise}         A promise that resolves to a wp/v2 taxonomy rest base string.
+ */
+const getTaxonomyRestBase = ( siteId, taxonomy ) => {
+	return new Promise( ( resolve, reject ) => {
+		switch ( taxonomy ) {
+			case 'category':
+				resolve( 'categories' );
```
Comment (mmtr) [inline client/state/terms/actions.js]: Since `register_taxonomy` can modify an existing taxonomy, would it be better to protect ourselves from a potential plugin in an AT site that could modify the `category`/`post_tag` taxonomies and change the rest base?

**Review by mmtr — COMMENTED** [review]
Thanks for the changes @gwwar! Tested a bunch of taxonomies (tags, categories and portfolios) and all of them worked without issues.

I have a note about plugins that can change the taxonomy rest base, but this should be good to merge after addressing that.

File: client/state/terms/actions.js (hunk 2 above)
Comment (gwwar) [reply client/state/terms/actions.js]: I think this is going to be pretty unlikely for plugins to modify tags/categories. I'd be hesitant to add a full API request for this case.

cc @blowery @griffbrad @jsnajdr do folks have preferences?

**Review by kwight — APPROVED** [review]
Fantastic – tested with tags and Portfolio Types (hierarchical), all behaved as expected 👍

**Comment by gwwar** [comment]
Thanks @mmtr @kwight for the reviews. I'll land this next Tuesday! If folks are inclined to merge and keep 👀on things in production, y'all are welcome to land earlier.
