### PR TITLE
Domains: Properly handle underscores in SRV records

### LINKED ISSUE #5830: Domains: Format SRV Records properly in DNS Settings
When an SRV is added intitally the format is correct. However, upon refresh the format is changed from:
`_sip_tcp.example.com`
to
`sip_tcp.example.com..example.com`

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains/manage/[domain]/dns/[primary_domain]
2. Click "Add New DNS Record"
3. Select SRV from dropdown
4. Enter an SRV record starting with an underscore. In my testing I used the Microsoft 365 ones found at: https://support.office.com/en-US/article/Create-DNS-records-for-Office-365-at-any-DNS-hosting-provider-7b7b075d-79f9-4e37-8a9e-fb60c1d95166#BKMK_add_SRV

#### What I expected
For the formatting to show the same regardless of refreshing the page. Also didn't not expect to have the underscore removed and extra period added. 

#### What happened instead
Formatting changed on refresh. 

#### Browser / OS version
Replicated on both Windows and Linux, video is showing Linux Mint 17.3 in Chromium 50.

#### Screenshot / Video
Initial display upon save:
screenshot_06-06-2016-11 49 37

After refresh (and every other visit):
screenshot_06-06-2016-11 52 19

Video: 
https://cloudup.com/cfbjL8zKO6f

### PR DESCRIPTION
**Pull request by klimeryk**
We are trimming the leading underscores for the service part of the SRV record on the backend, so the frontend should take that into account. Apparently, that's the convention (we already do this for the `protocol` part).
So, now it's `_service._protocol.domain.tld`, instead of the `service_protocol.domain.tld` mess earlier :grin:
This form seems to be the correct one - pasting it as-is to `dig` allows you to properly query a SRV record.
Additionally, I've simplified the getNormalizedName function - it doesn't have to build a complicated name. On the backend we strip it of the domain part either way...

Fixes #5830 

/cc @aidvu @umurkontaci for code review
/cc @BandonRandon @ehti for testing

Test live: https://calypso.live/?branch=fix/underscores-in-srv-records

### CODE REVIEW

**Comment by BandonRandon** [comment]
:tada: worked for me:
screenshot_01-07-2016-17 29 31

File: client/my-sites/upgrades/domain-management/dns/dns-record.jsx [hunk 1]
```diff
@@ -79,17 +81,17 @@ var DnsRecord = React.createClass( {
 	getName: function() {
 		const { name, service, protocol, type } = this.props.dnsRecord,
 			domain = this.props.selectedDomainName,
-			isRoot = name === domain + '.';
+			isRoot = name === `${ domain }.`;
 
 		if ( 'SRV' === type ) {
-			return service + '_' + protocol + '.' + ( isRoot ? name + '.' : '' ) + domain;
+			return `_${ service }._${ protocol }.${ isRoot ? '' : name + '.' }${ domain }`;
```
Comment (aidvu) [inline client/my-sites/upgrades/domain-management/dns/dns-record.jsx]: If I read this correctly, before the root record was bugged? :D

**Comment by aidvu** [comment]
Looking good. Found a bug with AAAA records.

aaaa records

Tried adding all kinds of records, and all is looking good.

File: client/my-sites/upgrades/domain-management/dns/dns-record.jsx (hunk 1 above)
Comment (klimeryk) [inline client/my-sites/upgrades/domain-management/dns/dns-record.jsx]: That's putting it lightly...
Before it looked like this:
screen shot 2016-07-08 at 13 14 36

Now, it's:
screen shot 2016-07-08 at 13 18 55
Note that there was no `.` between service and protocol, too 😀 
(and, yes, that leading underscore is required for SRV records - that way you can just copy and paste it to `dig`)

**Comment by klimeryk** [comment]
> Found a bug with AAAA records.

[I was first!](https://github.com/Automattic/wp-calypso/pull/5430#issuecomment-224023870) 😝 
But thanks for reminding me of it - even though it's not related to this change, I've added a small fix for it 👍 

Aaaand now it seems that @rads [recent patch](https://github.com/Automattic/wp-calypso/pull/6319) somehow broke SRV records? When you add one, the view is never updated to show that it's been added (it stays gray/disabled). The SRV record is actually successfully added, but the view is not updated 😣 Looking for a fix...

**Comment by klimeryk** [comment]
It seems the problematic change is https://github.com/Automattic/wp-calypso/pull/6319/files#diff-38687b7dd25904cac993aff2950c50dcR90
@rads, was this change required for your PR to work or was it for readability/performance/etc purposes?
I've proposed a fix in https://github.com/Automattic/wp-calypso/pull/6504/commits/6d47142b0a6818e298890f3f8963f4a9545159e8 and outlined the situation.
I don't like how brittle the way it works right now is, but I wanted to fix the regression first.

**Comment by rads** [comment]
@klimeryk: I did have to change the code to get my patch to work, but `6d47142` seems to work in both cases. 👍 

It would be ideal if we never encounter `undefined` and `null` in this flow and instead only use blank strings to represent values that are not filled in.

**Comment by klimeryk** [comment]
Thanks for confirming, @rads!

> It would be ideal if we never encounter undefined and null in this flow and instead only use blank strings to represent values that are not filled in.

I completely agree, but let's keep it simple for this PR. I've learned the hard way that when you start fiddling with the DNS editor, things quickly get out of control 😅

**Comment by klimeryk** [comment]
@aidvu - ping for a (final?) check :bow:

**Comment by aidvu** [comment]
:rocket:

**Comment by ehti** [comment]
Thanks for the fix, @klimeryk. Works fine, and I like the fact that we're auto-adding a leading underscore (even if user doesn't enter it) at the frontend.
