### PR TITLE
Editor: Reduxify EditorVisibility Component

### LINKED ISSUE #12276: Editor: Not able to edit passwords on password protected posts
It's not possible to edit passwords on password protected posts.

#### Steps to reproduce

1. Starting at: https://wordpress.com/post/
2. Publish a new post and, under the editor's Status module, edit the post's visibility so that it's password protected.
3. Navigate back to the editor for your newly published post.
4. Attempt to backspace over/edit the post's password.

#### What I expected

I expected to be able to edit the password after clicking/typing into the password field.

#### What happened instead

It wasn't possible to edit the password after typing straight into the field. 

I needed to toggle to "Public" and then back to "Password Protected" in order to be able to edit/change the password:

#### Browser / OS version

Chrome / macOS Sierra 10.12.3

#### Screenshot / Video

password

#### Context / Source

Reported in 249921-hc

#user-report #reallife

### PR DESCRIPTION
**Pull request by youknowriad**
closes #12276

This PR reduxifies the EditorVisibility Component on the Calypso's Editor. So from now on, all updates to the post status are performed through Redux. While this is a step forward in reduxifying the whole editor, this is also a risky change, that needs to be tested carefully.

I tried several workflows: Saving Drafts, switching to private published posts, switching to password protected posts, editing the password, switching to a "future" post. It seems to behave as expected but I'll definitely need a lot of eyes here.

### CODE REVIEW

**Comment by jasmussen** [comment]
Nice work!

Tested calypso.live branch in Chrome. Tested and working:

- Writing and publishing a post from scratch
- Editing a draft, adding a password, publishing
- Editing a draft, changing it to private. This also published the post, which seems to be the intended behavior (same behavior deployed currently)
- Reverting a private post to draft. 
- Writing a password protected post from scratch
- Publishing a post, then adding a password after publishing

Saw no JS errors. Everything worked fast and snappilly. 

I did manage to get one weird behavior where the post wouldn't save, and there was the following JS error in the console:

```
Service Worker termination by a timeout timer was canceled because DevTools is attached.
```
```
Warning: FormTextInput is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components
```
Video: https://cloudup.com/cc_iyMKeBdy

This may have been a non issue, though, as publishing worked fine, and trying to reload after a publish gave me the same error:

screen shot 2017-03-20 at 13 54 05

I couldn't reproduce the bug, btw. The way I got here involved editing a lot of drafts from the drafts drawer, changing lots of metabox options including pinned and needs review.

**Comment by aduth** [comment]
From @joendotcom 's comment:

>Warning: FormTextInput is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components

Haven't looked at the code yet, but this could be likely that we're passing an `undefined` or `null` value to the input in some cases (likely default value) and then swapping that out with the user defined value as they start typing.

**Comment by jasmussen** [comment]
> From @joendotcom 's comment:

Hehe, sorry, you mean @jasmussen. I wasn't able to snatch my username on GitHub.

File: client/post-editor/post-editor.jsx [hunk 1]
```diff
@@ -252,7 +252,6 @@ export const PostEditor = React.createClass( {
 								onDismissClick={ this.hideNotice } />
 							<EditorActionBar
 								isNew={ this.state.isNew }
-								onPrivatePublish={ this.onPublish }
```
Comment (youknowriad) [inline client/post-editor/post-editor.jsx]: No these are usefull, I guess this one has been moved to `EditorVisibility` and `Sidebar and we just forgot to clean if from here.

File: client/post-editor/post-editor.jsx [hunk 2]
```diff
@@ -650,14 +649,12 @@ export const PostEditor = React.createClass( {
...
+			status: 'publish',
+			...this.props.edits
 		};
 
-		// determine if this is a private publish
-		if ( utils.isPrivate( this.state.post ) ) {
-			edits.status = 'private';
-		} else if ( utils.isFutureDated( this.state.post ) ) {
+		// determine if this is a future publish
+		if ( utils.isFutureDated( this.state.post ) ) {
```
Comment (youknowriad) [inline client/post-editor/post-editor.jsx]: I'm not sure I understand your comment properly. Anyway, dropping this check has no effect on the behavior of the editor on my testings because even if we save a post with a status "publish" and a future date, the api will sanitize it to "future" as a response

**Comment by timmyc** [comment]
Wow thanks for grabbing this one Riad ( _checks it off his to-do list for today_ ✅  ).  The input warning is coming from the text field in `renderPasswordInput()` - maybe just change the value prop to `value= value || ''` would clear up the error

**Comment by youknowriad** [comment]
> The input warning is coming from the text field in renderPasswordInput()

I'm not certain about this. I was not able to reproduce it myself but the value was set to `null` on empty passwords and `null` on input is not possible on React (another warning different from the uncontrolled warning). So I updated the default value in 739e91e

File: client/post-editor/post-editor.jsx (hunk 2 above)
Comment (aduth) [inline client/post-editor/post-editor.jsx]: Because effectively this changes logic from:

Before: We don't trust `edits`, apply `publish` status and decide after if we need `private` or `future`
After: We trust `edits`, but use `publish` as a default

With "After" case, we could do similar with future dating to apply it as an edit before calling `onPublish`.

Comment (youknowriad) [inline client/post-editor/post-editor.jsx]: > With "After" case, we could do similar with future dating to apply it as an edit before calling onPublish.

Yeah! I thought about this! this makes it more explicit instead of relying on the server. seems like `setPostDate` is a good candidate for this logic

Comment (youknowriad) [inline client/post-editor/post-editor.jsx]: Oh now that I'm thinking about it, shouldn't be part of the EDIT_POST reducer :)

Comment (youknowriad) [inline client/post-editor/post-editor.jsx]: 🤔 The post  date is not reduxified yet. To keep the scope small. I'm adding this logic to the `setPostDate` for now

**Comment by aduth** [comment]
The change to remove applying `"status": "future"` to the request payload of a future-dated post is a little terrifying, but at least in my preliminary testing appears to work fine.

Another weird case that appears to exist in master as well: If you select "Password Protected" and add a password, but before saving backspace to remove all text from the password field, an error text is shown but I can still publish the post. When published, the post has a "Password" field and it's not clear what password to use (empty password doesn't work). We should probably disallow publishing if password protected is selected but no password is entered.

Otherwise this looks and works well 👍

File: client/post-editor/post-editor.jsx (hunk 2 above)
Comment (youknowriad) [inline client/post-editor/post-editor.jsx]: After some tests, I'm leaving this as is for now. If we were to make it explicit we'll need to undo the `status` edit when the date is set to a previous date, which makes me think the most convenient way to handle this is on the `onPublish` or server side like now, edits should only contain user edits.
