### PR TITLE
Plans: Fix `sitePlans` fetching on site switch

### LINKED ISSUE #2610: Plans: Update `sitePlans` on site switch
Originally reported by @mikeshelton1503 
> I was testing something locally on my Jetpack test site and saw the trials offered for Jetpack

image

This is probably linked to the fact that `sitePlans` is currently not updating on site switch in `client/my-sites/plans/main.jsx`
The component should be modified to update `sitePlans` on site change. `componentWillReceiveProps` won't update on site change since we are using the observer mixin. We should use either `componentWillUpdate` to watch for a new selected site in `sites` or pass it down to a new component.

### PR DESCRIPTION
**Pull request by Tug**
Fixes #2610 

### Description of the issue
Switching site from the Plans page is failing when switching from a Jetpack site to a WordPress.com site. A fatal error is visible in the console:
```
Uncaught TypeError: Cannot read property 'freeTrial' of undefined
Uncaught TypeError: Cannot read property 'remove' of undefined
```
This happens because in `components/plan`, `sitePlans` still contains the data for jetpack plans while the new site's `sitePlans` data is being fetched. This is not handled in PlanAction which expects a valid `sitePlan` props and test for the `freeTrial` property in it.

### Description of the fix
This removes the use of data observers and fixes the Redux connector in Plans' main.
We're adding here a `site` props so `componentWillReceiveProps` will be called on site change.
Also `shouldFetchSitePlans` is removed because we want to fetch sitePlans on each site change and the `site` props should never be `null`.
Edit: actually, as reported by @drewblaisdell, this won't work if the data is not loaded. So we have to keep the data observers in for now (until we move `sites-list` to the global state tree).

### Testing instructions
- Checkout this branch with `git checkout fix/2610-siteplans-switch` and run your server

#### Test 1 - Existing user with multiple sites
- Go to the Plans page on one of your site and try to switch site. Switch to a jetpack site then back to a wordpress.com site, it shouldn't throw any error
- Do the same for the Plans Compare page

#### Test 2 - New user
- In incognito mode, go to http://calypso.localhost:3000/start and check that nothing broke in the Plan Select and Plan Compare page

#### Test 3 - New site
- Using an existing account, go to http://calypso.localhost:3000/start and check that nothing broke in the Plan Select and Plan Compare page

Reviews
- [ ] Code Review
- [x] Product Review

### CODE REVIEW

File: client/my-sites/plans/controller.jsx [hunk 1]
```diff
@@ -74,18 +75,17 @@ module.exports = {
...
-						plans={ plans }
-						context={ context }
-						destinationType={ context.params.destinationType }/>
-				</CartData>
-			</ReduxProvider>,
-			document.getElementById( 'primary' )
+		renderWithReduxStore(
+			<CartData>
+				<Plans
+					site={ site }
```
Comment (drewblaisdell) [inline client/my-sites/plans/controller.jsx]: This method is only called when the `/plans/:site` route is hit, so when a user switches from site `foo` to site `bar`, this method is called and `Plans` receives new props. 

However, when the user visits this route and local storage is empty, `site` is not available until the sites are fetched, and because the route doesn't change once the sites are fetched, a new `site` prop is never provided to `Plans`. This results in a [perpetual loading state](https://cloudup.com/cNaiWh_xJmn), even once the sites have loaded.

File: client/my-sites/plans/main.jsx [hunk 2]
```diff
@@ -163,12 +157,11 @@ var Plans = React.createClass( {
 						<UpgradesNavigation
 							path={ this.props.context.path }
 							cart={ this.props.cart }
-							selectedSite={ this.props.sites.getSelectedSite() } />
+							selectedSite={ selectedSite } />
 
 						{ this.renderTrialCopy() }
 
 						<PlanList
-							sites={ this.props.sites }
```
Comment (drewblaisdell) [inline client/my-sites/plans/main.jsx]: I think you forgot to pass `site` in here instead. This is probably why I'm not seeing `PlanActions` buttons anywhere:

screen shot 2016-03-01 at 4 00 27 pm

Comment (Tug) [inline client/my-sites/plans/main.jsx]: Ah yep you're right, fixed now :)

File: client/my-sites/plans/main.jsx [hunk 3]
```diff
@@ -55,25 +53,21 @@ var Plans = React.createClass( {
...
 			return '';
 		}
 
-		if ( selectedSite ) {
-			url += '/' + selectedSite.slug;
-		}
-
 		return (
-			<a href={ url } className="compare-plans-link" onClick={ this.recordComparePlansClick }>
+			<a href={ '/plans/compare/' + selectedSite.slug } className="compare-plans-link" onClick={ this.recordComparePlansClick }>
```
Comment (stephanethomas) [inline client/my-sites/plans/main.jsx]: We could use a template literal here.

File: client/my-sites/plans/controller.jsx (hunk 1 above)
Comment (Tug) [inline client/my-sites/plans/controller.jsx]: Again you're right! Now I remember why we had this.
Ok I have no choice but to revert most of the changes and find another way :(

File: client/my-sites/plans/main.jsx (hunk 3 above)
Comment (Tug) [inline client/my-sites/plans/main.jsx]: Yeah, but I don't think we should, this file is still in ES5

Comment (stephanethomas) [inline client/my-sites/plans/main.jsx]: True.

**Comment by Tug** [comment]
Back for review :)

File: client/my-sites/plans/main.jsx [hunk 4]
```diff
@@ -39,11 +39,18 @@ var Plans = React.createClass( {
...
 	},
 
 	componentWillReceiveProps: function() {
-		this.props.fetchSitePlans( this.props.sitePlans, this.props.sites.getSelectedSite() );
+		this.updateSitePlans();
+	},
+
+	updateSitePlans: function() {
+		var selectedSite = this.props.sites.getSelectedSite();
+		if ( selectedSite ) {
```
Comment (drewblaisdell) [inline client/my-sites/plans/main.jsx]: `fetchSitePlans` calls `shouldFetchSitePlans`, which contains this check already.

File: client/my-sites/plans/main.jsx (hunk 3 above)
Comment (drewblaisdell) [inline client/my-sites/plans/main.jsx]: This line works because `selectedSite` is never `undefined`, and `( false ).name === undefined`, right? If that is the case, we might want to change it, as this seems somewhat fragile.

File: client/my-sites/plans/main.jsx (hunk 4 above)
Comment (Tug) [inline client/my-sites/plans/main.jsx]: True, let's remove it. Actually, let's revert it back to how it was!

File: client/my-sites/plans/main.jsx (hunk 3 above)
Comment (Tug) [inline client/my-sites/plans/main.jsx]: Yep you're right (once more), this is a mistake

File: client/my-sites/plans/controller.jsx [hunk 5]
```diff
@@ -74,18 +74,17 @@ module.exports = {
...
-			</ReduxProvider>,
-			document.getElementById( 'primary' )
+		renderWithReduxStore(
+			<CartData>
+				<Plans
+					sites={ sites }
+					onSelectPlan={ handlePlanSelect }
+					plans={ plans }
+					context={ context }
+					destinationType={ context.params.destinationType }/>
```
Comment (scruffian) [inline client/my-sites/plans/controller.jsx]: Trivial: `}/>` - missing space.

File: client/my-sites/plans/controller.jsx [hunk 6]
```diff
@@ -4,8 +4,8 @@
 var page = require( 'page' ),
 	ReactDom = require( 'react-dom' ),
 	React = require( 'react' ),
-	ReduxProvider = require( 'react-redux' ).Provider,
-	defer = require( 'lodash/defer' );
+	defer = require( 'lodash/defer' ),
+	renderWithReduxStore = require( 'lib/react-helpers' ).renderWithReduxStore;
```
Comment (scruffian) [inline client/my-sites/plans/controller.jsx]: I think this should be in `Internal Dependencies`.

File: client/my-sites/plans/controller.jsx (hunk 5 above)
Comment (Tug) [inline client/my-sites/plans/controller.jsx]: Thx, fixed it

File: client/my-sites/plans/controller.jsx (hunk 6 above)
Comment (Tug) [inline client/my-sites/plans/controller.jsx]: Thx, fixed it

**Comment by fabianapsimoes** [comment]
I've noticed the table headers in `/plans/compare` is incorrect for Jetpack sites. It shouldn't have WordPress.com before the name of the plans. Not really related to this PR, but if it's simple enough we can maybe fix it as part of it? Happy to create a new issue otherwise, just let me know.

Apart from that, product looks looks :+1:

**Comment by scruffian** [comment]
Code :+1:
