### PR TITLE
Token Input: Fix Firefox blur problems

### LINKED ISSUE #144: Components: Refactor TokenField focus and blur handling
The current `TokenField` focus and blur handling is a mess of timeouts and race conditions, and needs to be refactored.  See 10446-gh-calypso-pre-oss for discussion and starting points.

### LINKED ISSUE #2682: Editor: lose focus on editor during auto-save
If a meta box, like tags, is expanded, upon auto-save, focus on editor is lost and placed in side bar meta box instead.

Repro:
- Write in post body/editor in a draft
- expand tags/categories meta box
- click into tags input to select
- click back into editor
- notice that tags/categories meta is still in selected state: https://cloudup.com/cM0lpaYLzwZ
- type in body
- allow for autosave to initiate and continue typing
- notice that auto-save causes a loss of focus on editor
- focus is returned to meta box

video: https://cloudup.com/cJDQmZ-nQ4q

### LINKED ISSUE #4313: Editor: Tags TokenField doesn't blur correctly in Firefox
Noticed this while testing #4220 but it's an issue in master as well.

#### Steps to reproduce

1. Starting at URL: https://wpcalypso.wordpress.com/post (and pick a site)
2. Expand "Categories & Tags"
3. Click the tags field; add some tags or otherwise interact with it.  Note expansion of suggestions list for sites that already have some tags
4. Click onto another text field on the page.  (Clicking onto blank space seems to work fine.)

#### What I expected

The tags field should lose focus: the suggestions list should collapse and the blue border should go away.

#### What happened instead

The tags field keeps its focused appearance.

#### Browser / OS version

Firefox 42.0 (latest is 45.0; I would expect same behavior in latest)

OS X 10.10

### PR DESCRIPTION
**Pull request by marekhrabe**
Due to some browser event inconsistencies, in Firefox, there is a strange bug that makes `TokenField` steal focus back even after you selected another input and interacted with it. 

#### Steps to reproduce
- Use Firefox
- Open up New post
- Select tag input
- Insert some tag
- Focus Post title input and try to enter "test"

| Wordpress.com | This Branch |
| ----- | ----- |
| dot-com-focus | fix-branch |

On Wordpress, you should be only able to enter the first letter before tag input steals back the focus. This PR fixes that.

---

It is fixed by moving onBlur listener to `<input>` (instead of div) and adding preventDefault as a response to mouseDown on suggestion elements.

I tested this in Chrome, Safari and Firefox. I have not tested IE, I hope someone can.

- Fixes #144
- Fixes #2682
- Fixes #4313

Test live: https://calypso.live/?branch=fix/token-input-blur

### CODE REVIEW

**Comment by marekhrabe** [comment]
There were three tests failing, I fixed one of them by editing it to test exactly what it describes and not to test side-effects of that action https://github.com/Automattic/wp-calypso/pull/6162/commits/cc524a7fe22ac1aad10eabe6e1295f03c35c0973. I removed a source of those side effects in this PR — clicking a suggestion no longer triggers blur, because it preventsDefault on mouseDown event. That allowed me to really simplify the problem here.

There are currently two failing tests left (they are both targeted specifically for Firefox), but honestly, I have no idea what to do with them. They test that if you can click anywhere in the field, the component will be activated. That seems to work in browsers (including Firefox) but it fails in tests. 

It might be related to the fact, that I removed some `onClick` as by my other changes, it was rendered useless. There is no need to listen for onClick anymore because we listen for onFocus on the parent element and it catches clicks correctly. I think it is safe to remove those two tests, but I'd like some other opinion on that.

I saw that @gziolo wrote those tests and @nylen fixed some issues regarding the Firefox blur previously. Can any of you (or anyone else) help me test the functionality and give me your suggestion on removing tests? Thanks

**Comment by gziolo** [comment]
I only refactored those tests to work with Enzyme. @nylen can confirm if it is okey to remove them.

**Comment by marekhrabe** [comment]
> TypeError: this._clearBlurTimeout is not a function

Oh, thanks for noticing this one. I have made everything synchronous, so there is no need for the timeout anymore. However, I left one call there which caused tests to fail. It should be fine now. Only those 2 tests fail

**Comment by nylen** [comment]
Thanks for working on this.  I would love to see this messy code removed, but there are some bugs with the current implementation.

In Chrome, if you type part of a tag, then click the post title, the tags input steals the focus.  After that, if you click the tags input again, the current token is added (it seems the code gets confused about whether the field is active):

tokenfield-without-blur-handling

Same behavior in Safari, but everything seems to work well in Firefox.

I'd recommend getting an IE virtual machine from http://modern.ie/

This change also needs to be tested on mobile browsers.  I ran through it on Android Chrome and iOS Safari (v8.2), everything seems OK on both of these.  Do you have any others handy that you can test with?

I agree that the tests are tightly coupled to the implementation at the moment.  Let's get everything working well then circle back around to the tests.

File: client/components/token-field/index.jsx [hunk 1]
```diff
@@ -193,78 +187,22 @@ var TokenField = React.createClass( {
...
-			window.clearTimeout( this._blurTimeoutID );
-			this._blurTimeoutID = null;
-		}
-	},
-
-	_onClick: function() {
-		if ( this.refs.input && ! this.refs.input.hasFocus() ) {
-			debug( '_onClick focusing input' );
-			this.refs.input.focus();
+		debug( '_onBlur setting component inactive' );
```
Comment (nylen) [inline client/components/token-field/index.jsx]: Since the new `_onBlur` code is very simple we can remove this debug statement...

File: client/components/token-field/index.jsx [hunk 2]
```diff
@@ -193,78 +187,22 @@ var TokenField = React.createClass( {
...
+		if ( this._inputHasValidValue() ) {
+			debug( '_onBlur adding current token' );
+			this._addCurrentToken();
+		} else {
+			debug( '_onBlur not adding current token' );
 		}
+		debug( '_onBlur resetting component state' );
```
Comment (nylen) [inline client/components/token-field/index.jsx]: ...and we can remove this one as well.

**Comment by gziolo** [comment]
You have changed behavior of `_onBlur` handler. Those 2 failing tests simulate blur event, so that probably has some connection. I don't have time to investigate that further this week, I hope you can figure it out yourself ;)

**Comment by marekhrabe** [comment]
@nylen Thanks a lot for finding the bug that slipped under my radar. The problem was that `_addCurrentToken` (which `onBlur` is calling), was checking `state.isActive` and forcing focus if it is true. I added a reset for `isActive`, just before calling `_addCurrentToken`. It seems to be working well now.

**Comment by nylen** [comment]
Found another bug... since the `onBlur` handler was moved from the `div.token-field` to the `input` we can trigger a blur by clicking on the `div`.  I've added `background: #fcc` to the `input` to illustrate the issue.

tokenfield-click-div-bug

File: client/components/token-field/suggestions-list.jsx [hunk 3]
```diff
@@ -94,6 +94,7 @@ var SuggestionsList = React.createClass( {
 				<li
 					className={ classes }
 					key={ suggestion }
+					onMouseDown={ this._handleMouseDown }
```
Comment (nylen) [inline client/components/token-field/suggestions-list.jsx]: Do we need `onTouchStart` here as well?

**Comment by nylen** [comment]
Took a shot at fixing the bug I noted above, and cleaned up the tests.  Flipping to Needs Review.

File: client/components/token-field/suggestions-list.jsx (hunk 3 above)
Comment (marekhrabe) [inline client/components/token-field/suggestions-list.jsx]: I've tested this on the iPhone and mouseDown seems to do the job.

**Comment by marekhrabe** [comment]
Thanks for going ahead and fixing the problem & tests :) 

I just tested this in Chrome, Firefox, macOS Safari, iOS Safari & IE11. It seems to work consistently everywhere now. I've been mainly testing to blur token input by different methods (clicking outside, clicking inside, click on suggestion, <kbd>Tab</kbd>) and I haven't found focus stealing anymore, which was the original problem this PR fixes. After a code review, I think this is ready to be merged.

**Comment by nylen** [comment]
Nice work again, and thanks for taking another look!
