### PR TITLE
Reader comments: Fix "view earlier comments" does not load all top-level comments

### LINKED ISSUE #5587: Reader comments: "view earlier comments" does not load all top-level comments
#### Steps to reproduce
1. Starting at URL: http://wordpress.com/read/feeds/40474296/posts/999143144
2. Click "view earlier comments" twice

The original post for comparison is https://futonbleu.wordpress.com/2016/04/18/comment-test/.

#### What I expected

All top-level comments are displayed. 

#### What happened instead

The initial view shows three of four top-level comments.

After clicking "view earlier comments" twice, only two of four top level comments are displayed.

#### Screenshot / Video

screen shot 2016-05-25 at 12 50 40

### PR DESCRIPTION
**Pull request by yurynix**
That fixes #5587 

`getDisplayedComments` method should only count top level comments as the taken ones, not count comments with children

We also shouldn't rely on previous comments count since we requesting a fetch.

### CODE REVIEW

File: client/reader/comments/post-comment-list.jsx [hunk 1]
```diff
@@ -129,35 +129,30 @@ class PostCommentList extends React.Component {
...
-		let foundComments = 0;
-
-		const displayedComments = commentIds.takeWhile( ( val ) => {
-			const keepGoing = foundComments < take;
-			if ( keepGoing ) {
-				foundComments += this.getCommentsCount( [ val ] );
-			}
-			return keepGoing;
-		} );
+		const displayedComments = commentIds.take( take );
```
Comment (Tug) [inline client/reader/comments/post-comment-list.jsx]: Just curious about the `take` method, I have never heard of such a method on Array's prototype, does it come from some shim we're using?

Comment (yurynix) [inline client/reader/comments/post-comment-list.jsx]: That's not an array, but an Immutable List

Comment (Tug) [inline client/reader/comments/post-comment-list.jsx]: Oh I see, thanks for the clarification. I think it might be good to add it to the function doc IMO :)

File: client/reader/comments/post-comment-list.jsx [hunk 2]
```diff
@@ -129,35 +129,30 @@ class PostCommentList extends React.Component {
 		return commentIds.reduce( ( prevSum, commentId ) => prevSum + this.getCommentsCount( this.props.commentsTree.getIn( [ commentId, 'children' ] ) ) + 1, 0 );
 	}
 
+	/***
+	 * Gets comments for display
+	 * @param {Array<Number>} commentIds The top level commentIds to take from
+	 * @param {Number} take How many top level comments to take
+	 * @returns {Object} that has the displayed comments + total displayed count including children
+	 */
 	getDisplayedComments( commentIds, take ) {
```
Comment (Tug) [inline client/reader/comments/post-comment-list.jsx]: I wonder if this function should even exist now, given that it only calls take on the list basically.
But then I agree that it can make the calling code a bit unclear so might be worth keeping it

**Comment by Tug** [comment]
Code LGTM 👍

**Comment by Tug** [comment]
Product 👍 
Nice fix Yury! I suggest you just add this info about `commentIds` being an immutable list and then it's ready to merge.

File: client/reader/comments/post-comment-list.jsx (hunk 1 above)
Comment (yurynix) [inline client/reader/comments/post-comment-list.jsx]: I fixed the JSDOC to indicate it's `Immutable.List`

**Comment by blowery** [comment]
Testing this just to make sure

**Comment by yurynix** [comment]
Thanks @blowery !

**Comment by bluefuton** [comment]
Nice one @yurynix 🎉

**Comment by blowery** [comment]
+1 thanks @yurynix !
