### PR TITLE
Fix/migrate enzyme to react testing library

### LINKED ISSUE #63370: Migrate enzyme to react testing library - Button-group component
### Quick summary

Changes proposed in this Pull Request:

1. The Button group component is using the enzyme framework for testing, We need to migrate it to React-testing-library and jest
### Testing instructions
1. Run the test for button-group block with yarn run test-client:watch from source directory
2. Select P and then type button-group
3. We should see that the correct test file was executed and run like this:

[Direct Link](https://d.pr/i/LuxMS4+)

### PR DESCRIPTION
**Pull request by spraveenitpro**
### Quick summary
The button-group component is using the enzyme framework for testing, We need to migrate it to React-testing-library and jest

### Testing instructions
1. Run the test for button-group block with yarn run test-client:watch from source directory
2. Select P and then type button-group
3. We should see that the correct test file was executed and run like this:

[Direct Link](https://d.pr/i/LuxMS4+)

Related to #63370

Fixes #63370.

### CODE REVIEW

File: client/components/button-group/index.jsx [hunk 1]
```diff
@@ -9,7 +9,11 @@ const ButtonGroup = ( { busy = false, children, className = '', primary = false
 		'is-primary': primary,
 	} );
 
-	return <span className={ buttonGroupClasses }>{ children }</span>;
+	return (
+		<span className={ buttonGroupClasses } data-testid="button-group-id">
```
Comment (tyxla) [inline client/components/button-group/index.jsx]: I'd ideally suggest against introducing `data-testid` in components without a very good reason. It's also discouraged by `@testing-library/react` too, [see docs](https://testing-library.com/docs/queries/bytestid/):

> In the spirit of [the guiding principles](https://testing-library.com/docs/guiding-principles), it is recommended to use this only after the other queries don't work for your use case. Using data-testid attributes do not resemble how your software is used and should be avoided if possible. That said, they are way better than querying based on DOM structure or styling css class names. Learn more about data-testids from the blog post ["Making your UI tests resilient to change"](https://kentcdodds.com/blog/making-your-ui-tests-resilient-to-change)

That being said, have you considered taking a look at the WCAG (Web Content Accessibility Guidelines) recommendations for that purpose? [ARIA17](https://www.w3.org/TR/WCAG20-TECHS/ARIA17.html) solves that perfectly with a `role="group"`, and this is widely adopted throughout various component libraries ([Bootstrap](https://getbootstrap.com/docs/4.0/components/button-group/), [CoreUI](https://coreui.io/react/docs/components/button-group/)). Last but not least, `@testing-library/react` has a `*byRole` query family ([see docs](https://testing-library.com/docs/queries/byrole)) so that approach should work just fine for our testing purposes, while still contributing to improving the accessibility of the component.

File: client/components/button-group/test/index.js [hunk 2]
```diff
@@ -1,25 +1,27 @@
...
 	test( 'should contains the same number of .button nodes than <Button>s it receives', () => {
-		const buttonGroup = shallow(
+		render(
 			<ButtonGroup>
 				<Button>test</Button>
 				<Button>test2</Button>
 			</ButtonGroup>
 		);
-		expect( buttonGroup.find( Button ) ).toHaveLength( 2 );
+		expect( screen.getAllByRole( 'button' ).length ).toBe( 2 );
```
Comment (tyxla) [inline client/components/button-group/test/index.js]: Nice that we're using `getAllByRole` 👏 

We could improve a little bit by using the idiomatic `toHaveLength()`:

```suggestion
		expect( screen.getAllByRole( 'button' ) ).toHaveLength( 2 );
```

**Review by tyxla — CHANGES_REQUESTED** [review]
Thanks a lot for this one, it looks great overall 👍 

My only reservation here is introducing `data-test-id` without a good reason to do that. See my suggestion on what better alternatives we could go with.

File: client/components/button-group/index.jsx (hunk 1 above)
Comment (spraveenitpro) [reply client/components/button-group/index.jsx]: Some mind-bending stuff here. A couple of points

1. in this doc https://www.w3.org/TR/WCAG20-TECHS/ARIA17.html#ARIA17-examples , it clearly says `For a group of radio buttons, one could also use role="radiogroup" instead of role="group"`
2. So I am creating a role called `buttongroup` but that is causing eslint to throw 
3. So I set the role to `button`, which is allowing me to use `getByRole` and  `getAllByRole` for all the 3 tests which seem to pass. Please let me if there is a more optimal approach. [first time doing this]

Comment (tyxla) [reply client/components/button-group/index.jsx]: Well, those aren't radio buttons, but are rather just plain buttons, so it's not a good example to look at IMHO. `role="group"` makes the most sense in my opinion. Also, see this document for more information and examples: https://www.digitala11y.com/group-role/ - you'll see an example that precisely displays a button that contains 2 buttons. On the other hand, having `role="button"` for the buttons makes a lot of sense, but we can't guarantee that the role of buttons in there will be "button", there could always be an additional component with a different role.

File: client/components/button-group/index.jsx [hunk 3]
```diff
@@ -9,7 +9,11 @@ const ButtonGroup = ( { busy = false, children, className = '', primary = false
 		'is-primary': primary,
 	} );
 
-	return <span className={ buttonGroupClasses }>{ children }</span>;
+	return (
+		<span className={ buttonGroupClasses } role="button">
```
Comment (tyxla) [inline client/components/button-group/index.jsx]: Sorry, but the button group doesn't make much sense to have a "button" role. Its children _could_ have that role, but it's not a requirement. The parent IMHO should have a `role="group"`. What's the case against that?

**Review by tyxla — CHANGES_REQUESTED** [review]

File: client/components/button-group/test/index.js [hunk 4]
```diff
@@ -1,25 +1,27 @@
+/**
+ * @jest-environment jsdom
+ */
+import '@testing-library/jest-dom';
```
Comment (tyxla) [inline client/components/button-group/test/index.js]: This should now be removed because since #63505 we globally import `jest-dom`.

**Review by tyxla — CHANGES_REQUESTED** [review]
Thanks for addressing the feedback! I somehow missed that.

There's one more thing before this is ready to merge.

Also, you'll have to rebase to the latest `trunk` to be able to benefit from the globally imported `jest-dom`.

File: client/components/button-group/test/index.js (hunk 4 above)
Comment (spraveenitpro) [reply client/components/button-group/test/index.js]: Thank you, just did that!

**Review by tyxla — APPROVED** [review]
Awesome work @spraveenitpro! 🚀  Thank you 🙌
