### PR TITLE
Editor: Properly clear local state tree edits on POST_SAVE_SUCCESS

### LINKED ISSUE #11567: Editor: Autosave reverts content typed while autosaving
#### Steps to reproduce
1. Go to your WordPress site
2. Click the "Write" button in the top toolbar
3. Start to type a title. Type a character every half second or so.
4. Wait for autosave to kick in
5. Keep typing while autosave is autosaving
6. Wonder where your title went

#### What I expected

I expected that autosave would keep the content I was typing when autosave was running

#### What happened instead

The title reverts to the state it was in when autosave started.

We've had reports this happens on tags and the post body too, but for some reason it's harder to reproduce there.

#### Browser / OS version

Chrome/Firefox, Windows/Mac/Linux

#### Screenshot / Video

https://cloudup.com/ctBtqSg67o9

#### Context / Source

#intense-frustration #data-loss #user-report

### PR DESCRIPTION
**Pull request by timmyc**
This is take 2 of #11729 which was reverted in #11878 due to breaking an e2e test.  Ultimately, this branch seeks to close #11567 - which is a nasty bug that results in local changes to things like the post title, and terms being lost when an auto-save is in-flight.

__Notes__
While the original fix definitely solved the issue of lost post titles, it also uncovered the issue of the shape of `terms` being different between what we set in the local `edits` and send to the API, and what the API ultimately returns.  Since the prior logic would clear out all local edits on `POST_SAVE_SUCCESS` the `terms` discrepancy was never an issue - though they too were exposed to data loss of edits made while API requests were in-flight.

The reason there are differences are quite numerous: API issues and CPT custom taxonomy support, but for those interested see #7617 and D2607-code for some history.  

Ultimately, here is how we track term edits in the local state tree:
```
{
    terms: {
        post_tag: [ 'tag one', 'tag two' ], // non-hierarchical terms are added as simple arrays
        category: [
          { ID: 1, name: 'uncategorized' ] // while hierarchical terms are added as full objects
        ]
    }
}
```

And here is what the API response looks like after saving those edits from above:
```
{
    terms: {
        post_tag: {
          'tag one': { ID: ... },
          'tag two': { ID: ... }
        }
        category:  {
          'uncategorized': { ID: ... }
        }
    }
}
```

Because of this difference in object shape, the simple [equality check](https://github.com/Automattic/wp-calypso/blob/master/client/state/posts/reducer.js#L256) in `POSTS_RECIEVE` would always be `false`y for `terms` and even though term saves were working, the local edits were never properly flushed out on a valid save.

__Proposed Solution__
To get around this issue without disrupting all the term persistence logic, I have opted here to introduce a new utility method `hasTermEditDifferences` that compares local term edits against those saved in the API to determine equality.

__To Test__
Two distinct flows need to be tested.  The first is to ensure the data-loss issue is still fixed:
- Open a new draft in the editor
- Add a title and some content, place your cursor in the title field
- Wait for an auto-save to trigger, then quickly edit the title 
- After the auto-save completes, your edited title should still be intact, and the autosave status link should show 'SAVE' as an option since local edits do exist

Test the flow covered by the e2e test:
- Open a new draft in the editor
- Select a category ( other than the default )
- Add a tag
- Edit the title and wait for an autosave to happen
- Note after the auto-save finishes, the 'SAVE' link does not show, because no local edits exist. Also navigating away from the editor **should not** trigger the unsaved changes dialog

/cc @alisterscott if we could run the e2e tests against this branch I'd really appreciate it ( or if this is something I can do myself, please let me know how )

### CODE REVIEW

**Comment by timmyc** [comment]
FWIW I kept the two logic changes in different commits here.  960963c is largely the prior PR ( plus a typo fix in a test ), and ceae0c1 is the new util method to determine equality of local term edits against the API payload

**Comment by alisterscott** [comment]
Thanks for the fix.

I ran all editor e2e tests against desktop and mobile screen sizes and all passed 👍

File: client/state/posts/reducer.js [hunk 1]
```diff
@@ -253,6 +254,9 @@ export function edits( state = {}, action ) {
 				}
 
 				return set( memoState, [ post.site_ID, post.ID ], omitBy( postEdits, ( value, key ) => {
+					if ( key === 'terms' ) {
```
Comment (youknowriad) [inline client/state/posts/reducer.js]: I'm not familiar with the API results, but this make me wonder if there's other keys that could have different shapes?

File: client/state/posts/test/reducer.js [hunk 2]
```diff
@@ -892,6 +892,124 @@ describe( 'reducer', () => {
...
+						title: 'Hello World'
+					},
+					'': {
+						title: 'Unrelated'
+					}
+				}
+			} );
+		} );
+
+		it( 'should should preserve term edit differences on posts received', () => {
```
Comment (youknowriad) [inline client/state/posts/test/reducer.js]: 2x should

File: client/state/posts/utils.js [hunk 3]
```diff
@@ -241,6 +243,33 @@ export function normalizeTermsForApi( post ) {
...
+ * @return {Boolean}                are there differences in local edits vs saved terms
+ */
+export function hasTermEditDifferences( localTermEdits, savedTerms ) {
+	if ( ! localTermEdits || ! savedTerms ) {
+		return false;
+	}
+
+	return !! find( localTermEdits, ( terms, taxonomy ) => {
+		const termsArray = toArray( terms );
+		const isTag = ! isPlainObject( termsArray[ 0 ] );
```
Comment (aduth) [inline client/state/posts/utils.js]: More accurate might be to use hierarchical / non-hierarchical terminology? Since this could apply to other taxonomies aside from tag.

File: client/state/posts/utils.js [hunk 4]
```diff
@@ -241,6 +243,33 @@ export function normalizeTermsForApi( post ) {
...
+ * @param  {Object}  localTermEdits local state of term edits
+ * @param  {Object}  savedTerms     term object returned from API POST
+ * @return {Boolean}                are there differences in local edits vs saved terms
+ */
+export function hasTermEditDifferences( localTermEdits, savedTerms ) {
+	if ( ! localTermEdits || ! savedTerms ) {
+		return false;
+	}
+
+	return !! find( localTermEdits, ( terms, taxonomy ) => {
```
Comment (aduth) [inline client/state/posts/utils.js]: Minor: [`_.some`](https://lodash.com/docs/4.17.4#some) might be more precise to what you're trying to achieve (returns boolean rather than the found value).

File: client/state/posts/utils.js [hunk 5]
```diff
@@ -241,6 +243,33 @@ export function normalizeTermsForApi( post ) {
...
 /**
+ * Returns truthy if local terms object is different than API response
+ *
+ * @param  {Object}  localTermEdits local state of term edits
+ * @param  {Object}  savedTerms     term object returned from API POST
+ * @return {Boolean}                are there differences in local edits vs saved terms
+ */
+export function hasTermEditDifferences( localTermEdits, savedTerms ) {
+	if ( ! localTermEdits || ! savedTerms ) {
+		return false;
```
Comment (aduth) [inline client/state/posts/utils.js]: Would we expect this to return `true` if `hasTermEditDifferences( { post_tag: [ ... ] }, null )` ? Not sure anything like this would ever happen.

File: client/state/posts/utils.js (hunk 4 above)
Comment (aduth) [inline client/state/posts/utils.js]: Alternatively, to avoid all the negating, what if we were to use this function as `isTermsEqual` instead of returning whether there's a difference? Using [`_.every`](https://lodash.com/docs/4.17.4#every)

Comment (aduth) [inline client/state/posts/utils.js]: Hmm... how do we reconcile if there are more taxonomies in `savedTerms` than locally? Probably not something we'd expect to happen.

File: client/state/posts/test/utils.js [hunk 6]
```diff
@@ -16,10 +16,80 @@ import {
...
 
 describe( 'utils', () => {
+	describe( 'hasTermEditDifferences', () => {
+		it( 'should return false if no term edits passed', () => {
+			expect( hasTermEditDifferences() ).to.be.false;
+		} );
+
+		it( 'should return false if term edits are the same as saved terms', () => {
+			const hasDifferences = hasTermEditDifferences( {
+				post_tag: [ 'ribs', 'chicken' ],
```
Comment (aduth) [inline client/state/posts/test/utils.js]: I think I'm blanking on some normalization logic we implemented that I'm unable to find, but at what point does a post's `terms` turn from a plain object to an array of either objects or strings?

File: client/state/posts/utils.js [hunk 7]
```diff
@@ -241,6 +243,33 @@ export function normalizeTermsForApi( post ) {
...
+	}
+
+	return !! find( localTermEdits, ( terms, taxonomy ) => {
+		const termsArray = toArray( terms );
+		const isTag = ! isPlainObject( termsArray[ 0 ] );
+		const normalizedEditedTerms = isTag ? termsArray.sort() : map( termsArray, 'ID' ).sort();
+		const normalizedKey = isTag ? 'name' : 'ID';
+		const normalizedSavedTerms = map( savedTerms[ taxonomy ], normalizedKey ).sort();
```
Comment (aduth) [inline client/state/posts/utils.js]: To avoid the need to compare terms in perfect sorted order, [`_.xor`](https://lodash.com/docs/4.17.4#xor) might come in handy:

```js
export function isTermsEqual( localTermEdits, savedTerms ) {
	return every( localTermEdits, ( terms, taxonomy ) => {
		const termsArray = toArray( terms );
		const isHierarchical = isPlainObject( termsArray[ 0 ] );
		const normalizedEditedTerms = isHierarchical ? map( termsArray, 'ID' ) : termsArray;
		const normalizedKey = isHierarchical ? 'ID' : 'name';
		const normalizedSavedTerms = map( savedTerms[ taxonomy ], normalizedKey );
		return ! xor( normalizedEditedTerms, normalizedSavedTerms ).length;
	} );
}
```

File: client/state/posts/utils.js (hunk 5 above)
Comment (timmyc) [inline client/state/posts/utils.js]: Great point!

File: client/state/posts/reducer.js (hunk 1 above)
Comment (timmyc) [inline client/state/posts/reducer.js]: Not that I know of.  `terms` is _special_

File: client/state/posts/test/reducer.js (hunk 2 above)
Comment (timmyc) [inline client/state/posts/test/reducer.js]: Weird, I could have sworn I fixed that.

File: client/state/posts/test/utils.js (hunk 6 above)
Comment (timmyc) [inline client/state/posts/test/utils.js]: When the state is updated via the term selector, or token field.  But there are a few different normalization flows that pertain to editing and transforming data in terms prior to sending to the API https://github.com/Automattic/wp-calypso/blob/master/client/state/posts/utils.js#L40-L46

File: client/state/posts/utils.js (hunk 7 above)
Comment (timmyc) [inline client/state/posts/utils.js]: Your lodash wizardry always amazes me Mr. Andrew 🙇

**Comment by timmyc** [comment]
Updated logic, @aduth could I bother you for one more 👀
