### PR TITLE
Reader: Update image border implementation

### LINKED ISSUE #100488: Reader: A strange looking block in post details
### Context and steps to reproduce

This block looks strange when using the Reader with lines going over the post images (it's more visible with the second image but is the same with the first as well):
https://wordpress.com/reader/feeds/376341/posts/5576676564

https://github.com/user-attachments/assets/6508e66c-02a0-4d0e-a01e-b677bf61f620

This is how it looks on the blog:

Image

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Minor

### What other impact(s) does this issue have?

_No response_

### If a workaround is available, please outline it here.

_No response_

### Platform

_No response_

### PR DESCRIPTION
**Pull request by artemiomorales**
Related to https://github.com/Automattic/wp-calypso/issues/100488#top

## Proposed Changes

- Addresses image border inconsistencies by removing extra div and calculations
- Adds a border radius to images so that they're consistent in posts that were published using both the classic and Gutenberg editors

### Before

Screenshot 2025-03-26 at 17 00 01

### After

Screenshot 2025-03-26 at 16 57 07

## Why are these changes being made?

- Various scenarios with different image positioning were causing the border to be misplaced and inconsistent ([examples](https://github.com/Automattic/wp-calypso/issues/100488#issuecomment-2751559796))

## Testing Instructions

- Visit the following URLs and ensure the borders appear as expected: 
  - `/reader/feeds/376341/posts/5576676564`
  - `/reader/feeds/133226297/posts/5608707143`
  - `/reader/feeds/133226297/posts/5608694237`
  - `/reader/feeds/133226297/posts/5608683349`
  - `/reader/feeds/133226297/posts/5608676689`
  - `/reader/feeds/133226297/posts/5608668454`
  - `/reader/feeds/133226297/posts/5608662523`
- Check images in other posts and make sure there are no regressions
- Try publishing some posts with different image alignments, using various image features, and ensure there are no regressions

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/lib/post-normalizer/rule-add-image-wrapper-element.js [hunk 1]
```diff
@@ -94,17 +71,6 @@ export default function addImageWrapperElement( post, dom ) {
...
-		// Add div to allow image border with an inset box-shadow
-		const imageWidth = getCurrentImageWidth( image );
-		if ( imageWidth > 0 ) {
-			const imageBorder = document.createElement( 'div' );
-			const borderStyle = document.createAttribute( 'style' );
-			imageBorder.className = 'image-border';
-			borderStyle.value = 'width: ' + imageWidth + 'px';
-			imageBorder.setAttributeNode( borderStyle );
-			imageWrapper.appendChild( imageBorder );
-		}
```
Comment (artemiomorales) [inline client/lib/post-normalizer/rule-add-image-wrapper-element.js:107]: I might be missing something, but I couldn't see why creating an extra `div` for the image border is necessary 🤔 This may have made more sense in a previous iteration of Gutenberg, or when complex image arrangements and alignments weren't possible. Now this just seems error-prone and less robust than just using a border directly on the image ([additional context](https://github.com/Automattic/wp-calypso/issues/100488#issuecomment-2752511061))

File: client/blocks/reader-full-post/_content.scss [hunk 2]
```diff
@@ -81,27 +81,15 @@
...
-			max-width: 100%;
-		}
-
 		figcaption {
 			border-bottom-left-radius: 6px; /* stylelint-disable-line scales/radii */
 			border-bottom-right-radius: 6px; /* stylelint-disable-line scales/radii */
 		}
 	}
 	.image-wrapper img {
+		border-radius: 6px; /* stylelint-disable-line scales/radii */
```
Comment (artemiomorales) [inline client/blocks/reader-full-post/_content.scss]: Here I'm just maintaining the styles that were already established.

File: client/blocks/reader-full-post/_content.scss [hunk 3]
```diff
@@ -81,27 +81,15 @@
...
 		display: inherit;
+		border: 1px solid #E5E5E5;
```
Comment (artemiomorales) [inline client/blocks/reader-full-post/_content.scss]: This is the effective color of the border when it was implemented as a `box-shadow`.

Comment (mehmoodak) [reply client/blocks/reader-full-post/_content.scss]: Can we use a variable from `color-studio`?

File: client/blocks/reader-full-post/_content.scss (hunk 2 above)
Comment (mehmoodak) [reply client/blocks/reader-full-post/_content.scss]: Can we use existing variable for this purpose either `$radius-medium` or `$radius-large`? We don't have a variable for 6px which we can introduce but I think going with existing ones is also fine.

File: client/lib/post-normalizer/rule-add-image-wrapper-element.js (hunk 1 above)
Comment (mehmoodak) [reply client/lib/post-normalizer/rule-add-image-wrapper-element.js:107]: Seems like this is introduced by @eoigal 2 years ago so most likely he will have more context on this.

File: client/blocks/reader-full-post/_content.scss (hunk 2 above)
Comment (artemiomorales) [reply client/blocks/reader-full-post/_content.scss]: Done 👍

File: client/blocks/reader-full-post/_content.scss (hunk 3 above)
Comment (artemiomorales) [reply client/blocks/reader-full-post/_content.scss]: Done 👍

**Review by mehmoodak — APPROVED** [review]

File: client/blocks/reader-full-post/_content.scss [hunk 4]
```diff
@@ -1,3 +1,6 @@
+@import '@wordpress/base-styles/variables';
```
Comment (artemiomorales) [inline client/blocks/reader-full-post/_content.scss]: @mehmoodak This new import is causing the build to fail even though it works locally. Do you know how to include the files properly by chance or have any other suggestions to resolve?

Screenshot 2025-03-27 at 18 27 34

**Comment by artemiomorales** [comment]
@mehmoodak I believe the new SCSS imports are causing the build to fail even though it works locally. Do you know how to include the files properly?

Screenshot 2025-03-27 at 18 27 34

**Review by dzver — COMMENTED** [review]
A nice red PR, good job!
