### PR TITLE
Editor: prevent published scheduled posts from auto saving

### LINKED ISSUE #310: Editor: Scheduled Post Can Publish Changes on Autosave
What I did:
- Scheduled a post sometime in the future. Came back to edit the post close to the set publish time. (To reproduce you can just schedule a post a couple minutes into the future.)
- Leave the Editor window open past the scheduled time.
- Make changes to the post
- Let autosave happen

What Happened:
- The post was published on the autosave with the changes I had just been making

What I Expected:
- As the post was past the scheduled time I expected to have to press the Update button for the changes I was working on to be published.

raised by sandymcfadden

### PR DESCRIPTION
**Pull request by timmyc**
fixes #310

There is an edge case where if a scheduled post time has lapsed ( e.g. the post is now published ), and the editor window the post was drafted in is still open, the first set of modifications preformed in the "stale" editor window will be auto-saved, and updated to the live post.

After that first false auto-save, the state is properly updated in the post edit store, and no more auto-saves will happen.

This branch seeks to prevent that first false auto-save from firing by seeing if the `post.date` is in the past when `post.status === 'future'`.

__To Test__
- Scheduled a post sometime in the future. Came back to edit the post close to the set publish time. (To reproduce you can just schedule a post a couple minutes into the future.)
- Leave the Editor window open past the scheduled time.
- After publish time has lapsed, make some changes to the post, validate that these changes are not autosaved
- Also create a new post, and ensure no auto-save functionality has changed

__Notes__
Due to this new logic to `isPublished` some tests were failing for ground control.  I have updated the tests in e9614bb to reflect this new logic, but wanted to hear @aduth 's thoughts on the matter.

### CODE REVIEW

File: client/lib/posts/test/utils.js [hunk 1]
```diff
@@ -67,6 +67,30 @@ describe( 'utils', function() {
...
+			assert( ! postUtils.isBackDatedPublished() );
+		} );
+
+		it( 'should return false when status !== future', function() {
+			assert( ! postUtils.isBackDatedPublished( { status: 'draft' } ) );
+		} );
+
+		it( 'should return false when status === future and date is in future', function() {
+			const tenMinutes = 1000 * 60;
+			const postDate = +new Date() + tenMinutes;
```
Comment (aduth) [inline client/lib/posts/test/utils.js]: `Date.now()` is a more readable variant of `+new Date()`, latter seen usually when pre-ES5 support needed, IE<9.

File: client/lib/posts/test/utils.js [hunk 2]
```diff
@@ -67,6 +67,30 @@ describe( 'utils', function() {
 		} );
 	} );
 
+	describe( '#isBackDatePublished', function() {
```
Comment (aduth) [inline client/lib/posts/test/utils.js]: Typo dated, not date 😄

File: client/post-editor/editor-ground-control/test/index.jsx [hunk 3]
```diff
@@ -181,7 +181,7 @@ describe( 'EditorGroundControl', function() {
 				/>
 			).instance();
 
-			expect( tree.getPrimaryButtonLabel() ).to.equal( 'Publish' );
+			expect( tree.getPrimaryButtonLabel() ).to.equal( 'Update' );
```
Comment (aduth) [inline client/post-editor/editor-ground-control/test/index.jsx]: Confused me at first, but I think I understand the original expectation. When creating a new post, if the user schedules the post in the past (while still drafted), we'd expect the text to be "Publish", not "Update". The latter is true only when the post is already published.

schedule

Comment (aduth) [inline client/post-editor/editor-ground-control/test/index.jsx]: So it may be that we want to detect whether the `savedPost` is published already, showing "Update" if it is, and "Publish" otherwise?

**Comment by aduth** [comment]
This looks like the right direction (considering back-dated as `isPublished`), but I think we'll want to preserve the workflow of back-dating a post while drafting.

File: client/post-editor/editor-ground-control/test/index.jsx (hunk 3 above)
Comment (timmyc) [inline client/post-editor/editor-ground-control/test/index.jsx]: So I think that is working as expected right now in this branch - but the test case doesn't align properly:

past-dated

**Comment by timmyc** [comment]
Okay I reverted the changes to ground control tests and made them green in 1465010.  Strange as testing without those changes yielded the expected results in my [screen grab](https://github.com/Automattic/wp-calypso/pull/4973#discussion_r60959928).

I thought about moving the `isBackDatedPublished` logic into the auto save action, but that would short circuit any auto-saves for backdated unpublished posts.  Another possible fix for the initial bug would be to implement some form of polling for the post - perhaps that would set the stage for locking posts that are being edited elsewhere...

**Comment by aduth** [comment]
Took this for another spin, and looks to work very well. I added a few more (passing) tests in 408250d to cover some of the new cases.

One edge-y detail: I noticed the primary action remained "Publish" when returning to my tab after the scheduled date had lapsed, when I would have expected it to change to "Update". I think this is a pretty minor detail all-things-considered, so feel free to merge anyways 👍
