### PR TITLE
Jetpack Backup: Fix Credentials and AL wording based on currently supported product

### LINKED ISSUE #38395: Jetpack Backup confirmation in Activity Log says "real time" but I purchased "daily" backups
#### Steps to reproduce
1. Buy Daily Backups for a Jetpack site
2. Head to Activity Log and enter your credentials
3. You will see a notification like "Your backup is underway. We're currently backing up your site for the first time, and we'll let you know when we're finished. After this initial backup, we'll save future changes in real time."
4. Note that I did _not_ buy real-time backups.

#### What I expected

Prompt that correctly describes the product I purchased

#### What happened instead

Prompt says real-time, product says daily

#### Browser / OS version

Chrome 79 / Android 10, and
Chrome 78 / macOS 10.15

#### Screenshot / Video

daily-real-time

### PR DESCRIPTION
**Pull request by tyxla**
Previously, we were saying "in real time" in both the AL and the credentials screen. However, if the user has a daily backup product, this is no longer accurate. This PR is fixing the wording to reflect the currently supported product/plan.

#### Changes proposed in this Pull Request

* Introduce a new `siteSupportsRealtimeBackup` selector with tests.
* Activity Log: Fix wording depending on the supported backup.
* Settings: Fix credentials wording depending on the supported backup.

#### Preview

Activity Log - with a Daily Backup product

Activity Log - with a Realtime Backup product

Security Settings - with a Daily Backup product

Security Settings - with a Realtime Backup product

#### Testing instructions

* Checkout this branch.
* Create 2 JN sites and connect them. Let's call them site X and site Y.
* Buy a daily backup for site X, buy a realtime backup for site Y.
* You'll be prompted to add credentials. If you aren't, you can do it at http://calypso.localhost:3000/settings/security/:site
* Add credentials for each of the sites.
* Take a look at the credentials section. Verify it says:
  * `Your site is being backed up every day and regularly scanned for security threats.` for site X.
  * `Your site is being backed up in real time and regularly scanned for security threats.` for site Y.
* Go to Activity: http://calypso.localhost:3000/activity-log/:site
* Take a look at the top nudge, verify it ends with:
  * `...After this initial backup, we'll save future changes every day.`
  * `...After this initial backup, we'll save future changes in real time.`
* Verify tests pass: `npm run test-client client/state/selectors/test/site-supports-realtime-backup.js`

Fixes #38395

### CODE REVIEW

File: client/my-sites/activity/activity-log/index.jsx [hunk 1]
```diff
@@ -406,12 +429,24 @@ class ActivityLog extends Component {
 			};
 		} )();
 
+		const provisioningText = this.supportsRealtimeBackup()
+			? translate(
+					"We're currently backing up your site for the first time, and we'll let you know when we're finished. " +
+						"After this initial backup, we'll save future changes in real time."
+			  )
+			: translate(
+					"We're currently backing up your site for the first time, and we'll let you know when we're finished. " +
```
Comment (a8ci18n) [inline client/my-sites/activity/activity-log/index.jsx]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **17** times:
`translate( 'We're currently backing up your site for the first time, and we'll let you know when we're finished. After this initial backup, we'll save future changes in real time.' )` *ES Score: 9*

File: client/my-sites/site-settings/jetpack-credentials/credentials-configured/index.jsx [hunk 2]
```diff
@@ -89,6 +116,14 @@ class CredentialsConfigured extends Component {
 			);
 		}
 
+		const headerText = this.supportsRealtimeBackup()
+			? translate(
+					'Your site is being backed up in real time and regularly scanned for security threats.'
+			  )
+			: translate(
+					'Your site is being backed up every day and regularly scanned for security threats.'
```
Comment (a8ci18n) [inline client/my-sites/site-settings/jetpack-credentials/credentials-configured/index.jsx]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **27** times:
`translate( 'Your site is being backed up in real time and regularly scanned for security threats.' )` *ES Score: 8*

File: client/my-sites/site-settings/jetpack-credentials/credentials-configured/index.jsx [hunk 3]
```diff
@@ -34,6 +42,25 @@ class CredentialsConfigured extends Component {
 
 	toggleRevoking = () => this.setState( { isRevoking: ! this.state.isRevoking } );
 
+	supportsRealtimeBackup() {
```
Comment (tyxla) [inline client/my-sites/site-settings/jetpack-credentials/credentials-configured/index.jsx]: I was thinking it would be nice to avoid this duplication, but somehow it felt too concrete to have this as a separate selector. But if y'all think we should create that selector, I'm fine to go that way!

File: client/my-sites/activity/activity-log/index.jsx (hunk 1 above)
Comment (tyxla) [reply client/my-sites/activity/activity-log/index.jsx]: This is expected, we're introducing a new variation of that string.

File: client/my-sites/site-settings/jetpack-credentials/credentials-configured/index.jsx (hunk 2 above)
Comment (tyxla) [reply client/my-sites/site-settings/jetpack-credentials/credentials-configured/index.jsx]: This is expected, we're introducing a new variation of that string.

File: client/my-sites/site-settings/jetpack-credentials/credentials-configured/index.jsx (hunk 3 above)
Comment (ChaosExAnima) [reply client/my-sites/site-settings/jetpack-credentials/credentials-configured/index.jsx]: I wonder if it may be useful to have a selector that's a more generic `planSupports` query for use cases like this. May not be something for this PR, but would be good to avoid duplication of logic like this down the road.

File: client/my-sites/activity/activity-log/index.jsx [hunk 4]
```diff
@@ -357,6 +361,25 @@ class ActivityLog extends Component {
 		);
 	}
 
+	supportsRealtimeBackup() {
```
Comment (robertf4) [inline client/my-sites/activity/activity-log/index.jsx]: What do you think about moving this to a lib function? This seems like something that could be reused across components.

File: client/my-sites/site-settings/jetpack-credentials/credentials-configured/index.jsx (hunk 3 above)
Comment (robertf4) [reply client/my-sites/site-settings/jetpack-credentials/credentials-configured/index.jsx]: I think it's best as its own selector. For example, see `has_jetpack_backup_realtime_feature` in jetpack.com's store. There are a variety of functions like this available for reuse there, and I think Calypso would benefit from something similar.

Comment (tyxla) [reply client/my-sites/site-settings/jetpack-credentials/credentials-configured/index.jsx]: Okay, fair enough folks! I've created a `siteSupportsRealtimeBackup` selector with some tests, and adapted the code to use that selector. Take another look when you get a chance 😉

File: client/my-sites/activity/activity-log/index.jsx (hunk 4 above)
Comment (tyxla) [reply client/my-sites/activity/activity-log/index.jsx]: See https://github.com/Automattic/wp-calypso/pull/38473#discussion_r359313708

**Comment by tyxla** [comment]
Okay, I've added a new `siteSupportsRealtimeBackup` selector with tests, and updated the code to use that selector.

This PR could use another review, thanks 🙌

File: client/my-sites/activity/activity-log/index.jsx [hunk 5]
```diff
@@ -605,6 +616,7 @@ export default connect(
 			timezone,
 			siteHasNoLog,
 			isIntroDismissed: getPreference( state, 'dismissible-card-activity-introduction-banner' ),
+			supportsRealtimeBackup: siteSupportsRealtimeBackup( state, siteId ),
```
Comment (delawski) [inline client/my-sites/activity/activity-log/index.jsx]: Like noted in one of the following comments - I think it would be useful to note in a comment that this selector needs `QuerySitePurchases` to work.

File: client/state/selectors/test/site-supports-realtime-backup.js [hunk 6]
```diff
@@ -0,0 +1,218 @@
...
+			purchases: {
+				data: [],
+			},
+			sites: {
+				plans: {
+					[ siteId ]: {
+						data: [
+							{
+								currentPlan: true,
+								productSlug: 'jetpack_premium',
```
[the remark this answers is not in the document]
Comment (tyxla) [reply client/state/selectors/test/site-supports-realtime-backup.js]: Ah, good catch. I just hacked this quickly and never did it properly. Thanks! Fixed in https://github.com/Automattic/wp-calypso/pull/38473/commits/e1d3df0f63c724277ef95cefa5f45f5276d9e6bd

File: client/state/selectors/test/site-supports-realtime-backup.js [hunk 7]
```diff
@@ -0,0 +1,218 @@
...
+			},
+			sites: {
+				plans: {},
+			},
+		};
+
+		expect( siteSupportsRealtimeBackup( state, siteId ) ).toBe( true );
+	} );
+
+	test( 'should return false when site is on a Jetpack Premium yearly plan', () => {
```
[the remark this answers is not in the document]
Comment (tyxla) [reply client/state/selectors/test/site-supports-realtime-backup.js]: While I prefer how expressive the previous version of the tests was, I have no strong feelings, so I updated them to use loops, because you're right - it cuts the test code almost in half. Done in https://github.com/Automattic/wp-calypso/pull/38473/commits/39bc0efcce98c81f8fb28725d9700be3248c8de0

File: client/my-sites/site-settings/jetpack-credentials/credentials-configured/index.jsx [hunk 8]
```diff
@@ -128,6 +136,7 @@ const mapStateToProps = ( state, { siteId } ) => {
 	return {
 		canAutoconfigure: canAutoconfigure || credentials.some( c => c.type === 'auto' ), // eslint-disable-line wpcalypso/redux-no-bound-selectors
 		mainCredentials: find( credentials, { role: 'main' } ),
+		supportsRealtimeBackup: siteSupportsRealtimeBackup( state, siteId ),
```
[the remark this answers is not in the document]
Comment (tyxla) [reply client/my-sites/site-settings/jetpack-credentials/credentials-configured/index.jsx]: No, it's not a common practice at all to specify that, so if you don't mind, I'll pass. Selectors aren't at all responsible for fetching data, so it's expected that one will have to get that data to the state first. We have that described in one of our fundamental docs: https://github.com/Automattic/wp-calypso/blob/master/docs/our-approach-to-data.md#current-recommendations

File: client/my-sites/activity/activity-log/index.jsx (hunk 5 above)
Comment (tyxla) [reply client/my-sites/activity/activity-log/index.jsx]: See https://github.com/Automattic/wp-calypso/pull/38473#discussion_r362475829

**Comment by tyxla** [comment]
Thanks everyone! I've addressed the feedback, and this could use another review.

**Comment by enejb** [comment]
This worked well for me. 
I wasn't able to see the notice... on the activity log page. 
But notice on the Security settings was correct. Expect for sites that only have the backup product. 

We shouldn't be telling them that we are doing security scanning if we are not. 

If you want to fix that in a different PR I think that would be good as well. And this is ready to merge.

**Comment by enejb** [comment]
🤔 If you ask me I think we should probably try to make the banner simple less verbose and update it so that that we don't need any logic that is dependent on the plan. 

Something like 
"Jetpack is backing up your site for the first time. We will let you know when we are done."

**Comment by tyxla** [comment]
> 🤔 If you ask me I think we should probably try to make the banner simple less verbose and update it so that that we don't need any logic that is dependent on the plan.
> 
> Something like
> "Jetpack is backing up your site for the first time. We will let you know when we are done."

Sounds like a solid next step 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/2238988

Thank you @tyxla for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/2238988).
