### PR TITLE
Marketplace: Fix encoding issue on plugin search

### LINKED ISSUE #73907: Marketplace: Encoding issue on plugin search
### Quick summary

I noticed an encoded `'` when searching for Clarity that shouldn't be there.

Screenshot 2023-02-28 at 4 33 04 PM

The issue shows when I go to `/plugins/$site` and then search for `clarity`

### Steps to reproduce

1. Start at `/plugins/$site`
2. Search for `clarity`
3. Verify encoded character
4. Click on Clarity item
5. Verify no encoded character

### What you expected to happen

No encoded character.

### What actually happened

Encoded character.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by epeicher**
Fixes #73907

## Proposed Changes

* Use `decodeEntities` to decode html-encoded characters in `title`, `slug` and `short_description`

## Testing Instructions

- Start at `/plugins/$site`
- Search for `clarity`
- Verify encoded character
- Click on Clarity item
- Verify no encoded character
- Repeat searches for other plugins like `Check & Health`
- Verify there are no encoded characters

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
~- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?~
~- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?~

### CODE REVIEW

File: client/data/marketplace/use-es-query.ts [hunk 1]
```diff
@@ -41,8 +42,8 @@ const mapIndexResultsToPluginData = ( results: ESHits ): Plugin[] => {
 	}
 	return results.map( ( { fields: hit, railcar } ) => {
 		const plugin: Plugin = {
-			name: hit.plugin?.title, // TODO: add localization
-			slug: hit.slug,
+			name: decodeEntities( hit.plugin?.title ), // TODO: add localization
+			slug: decodeEntities( hit.slug ),
```
Comment (WBerredo) [inline client/data/marketplace/use-es-query.ts:46]: I'm not sure if we want to make any changes to a slug.

Comment (WBerredo) [inline client/data/marketplace/use-es-query.ts:46]: Do we need to make any changes to a slug?

File: client/data/marketplace/use-es-query.ts [hunk 2]
```diff
@@ -54,9 +55,9 @@ const mapIndexResultsToPluginData = ( results: ESHits ): Plugin[] => {
 			support_threads_resolved: hit[ 'plugin.support_threads_resolved' ],
 			active_installs: hit.plugin?.active_installs,
 			last_updated: hit.modified,
-			short_description: hit.plugin?.excerpt, // TODO: add localization
+			short_description: decodeEntities( hit.plugin?.excerpt ), // TODO: add localization
 			icon: getIconUrl( hit.slug, hit.plugin?.icons ),
-			premium_slug: hit.plugin?.premium_slug,
+			premium_slug: decodeEntities( hit.plugin?.premium_slug ),
```
Comment (WBerredo) [inline client/data/marketplace/use-es-query.ts:60]: Same as above.

**Review by WBerredo — APPROVED** [review]
Non-blocking comments, LGTM!

File: client/data/marketplace/use-es-query.ts (hunk 1 above)
Comment (epeicher) [reply client/data/marketplace/use-es-query.ts:46]: That's a very legit question I also asked myself. I took the approach from the following method
https://github.com/Automattic/wp-calypso/blob/00ac42ffb4faa327c7b8e538917d066eb8b15c24/client/lib/plugins/utils.js#L202
where  `slug` is also decoded so I wanted to mimic that functionality. But I don't expect any `slug` to have encoded-html characters so we can remove it from `slug`, what do you think?

File: client/data/marketplace/use-es-query.ts (hunk 2 above)
Comment (epeicher) [reply client/data/marketplace/use-es-query.ts:60]: Similar answer to the above https://github.com/Automattic/wp-calypso/pull/73935#discussion_r1122037313

File: client/data/marketplace/use-es-query.ts (hunk 1 above)
Comment (WBerredo) [reply client/data/marketplace/use-es-query.ts:46]: >  I took the approach from the following method

Yeah, if this is applied somewhere else I don't see a reason to not have it here too.

>  I don't expect any slug to have encoded-html characters

Me neither, but for the sake of keeping the same behavior, I don't see a reason to remove it.
