### PR TITLE
Jetpack NUX: Update error screen for plugins auto-config

### LINKED ISSUE #6432: Jetpack NUX: if auto-config fails, provide path to support
If installation of a plugin fails on auto-config, we currently show a blue notice that mentions there was a problem, and directs you to look at each plugin card to see the error. 

This notice should be red, and can be more actionable. Let's make it red, let's provide any known reasons for the failure, and let's provide links to the manual instructions and to contact Jetpack support:

screen shot 2016-06-29 at 4 01 42 pm

### PR DESCRIPTION
**Pull request by ryelle**
We should show more detailed error messages when we  can't install plugins, or when installation fails.

To test (part 1):

1. Visit the install page for a site with `DISALLOW_FILE_MODS` set, or which is a subsite of a multisite, or any other case we can't install plugins on.
2. You'll see an "Oh no!" message, with text saying why we can't install plugins on this site.
3. You can click a "Contact Support" button.

Preview:

screen shot 2016-06-30 at 6 06 47 pm

To test (part 2):

1. Visit the install page with a site we know will encounter an error (easy breakage: create a folder called `akismet` in your plugins folder, set permissions so the web user can't write to it)
2. Your plugins will start to install, then encounter whatever error case you have. The plugin with the error gets a compact error notice.
3. When all plugins are installed, a larger notice appears, saying that there was an error, with a link to manual install instructions, and an action to contact support.

Preview:

screen shot 2016-07-01 at 5 15 56 pm

Fixes #6432

Test live: https://calypso.live/?branch=update/jetpack-config-errors

### CODE REVIEW

**Comment by ryelle** [comment]
@rickybanister @johnHackworth This is ready for review now

**Comment by rickybanister** [comment]
That looks perfect to me, only one tiny nitpick that may be optional...

Should we say '...it may be possible to fix this by manually installing the plugin'?

**Comment by johnHackworth** [comment]
Works perfect :+1:

File: client/my-sites/plugins/jetpack-plugins-setup/index.jsx [hunk 1]
```diff
@@ -295,23 +318,54 @@ const PlansSetup = React.createClass( {
...
 			return null;
 		}
 
-		const pluginsWithErrors = filter( this.props.plugins, ( item ) => {
+		const plugins = this.addWporgDataToPlugins( this.props.plugins );
+		const pluginsWithErrors = filter( plugins, ( item ) => {
 			return ( item.error !== null );
 		} );
 
 		if ( pluginsWithErrors.length ) {
```
Comment (johnHackworth) [inline client/my-sites/plugins/jetpack-plugins-setup/index.jsx]: Maybe all the code within this `if` block could be extracted to a new `renderErrorMessages` method so it's just 
```
if ( pluginsWithErrors.length ) {
   return this.renderErrorMessages();
}
```

Not that it adds anything, but it would make the code a little more compact

**Comment by johnHackworth** [comment]
I left a minor comment about code organization, but this would be ready to merge both if you agree with it or if you don't... :shipit: !

**Comment by ryelle** [comment]
Great :) I agree, so made the change, and will merge.
