### PR TITLE
Marketplace: Handle SaaS redirect url when no site is selected

### LINKED ISSUE #69329: Marketplace: Handle SaaS products when no site is selected
When no site is selected and the user selects a SaaS product, it should redirect the user to the third-party vendor as it currently does when opening the plugin details and a site is selected https://github.com/Automattic/wp-calypso/pull/68667#issue-1398137649

#### Steps to reproduce:
- Sandbox your API and make sure you have define( 'USE_STORE_SANDBOX', true ); as explained in PCYsg-IA-p2
- Navigate to https://wordpress.com/plugins?s=test _without selecting any site_
- Select the `Test SaaS Product`
- Click on Manage sites (screenshot below)
- The buttons should read `Getting started in a similar way to when opening the plugin details with a selected site

CleanShot 2022-10-21 at 13 17 42@2x

### PR DESCRIPTION
**Pull request by epeicher**
#### Proposed Changes
 Adds a new button functionality when selecting `Manage sites` in a plugin details screen for SaaS products

#### Testing Instructions

* Sandbox the API and make sure you are using the test store. More information here PCYsg-IA-p2
* Navigate to `/plugins/test-saas-product` without a site selected
* Click on `Manage sites`
* Make sure the buttons are displayed with the `Get Started` text 
* Make sure when clicking the buttons, the site is redirected to the test URL with both the `userId` and `siteId` in the URL in the `uuuid` query param

##### Regression testing
* Navigate to another plugin without a site selected and make sure when clicking the `Manage sites` button, the dialog and buttons behave like in production. E.g. `/plugins/woocommerce-bookings` or `/plugins/woocommerce`
* Navigate to the `test saas product` plugin detail with a site selected and make sure it behaves like in production. Example URL is `/plugins/test-saas-product/<site_id>`

#### Screenshot
CleanShot 2022-10-25 at 13 43 29@2x

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Fixed #69329

### CODE REVIEW

**Comment by epeicher** [comment]
The commit https://github.com/Automattic/wp-calypso/pull/69423/commits/a1df6ce78ea62785026c76ef89cacd4588e6a889 is a refactor commit that removes the selector `isSaasProduct` from `plugin-details-cta` and `plugin-price` components now that is added to the `plugin` object [here](https://github.com/Automattic/wp-calypso/pull/69423/files#diff-88b330820980195a5fac3dab16832001fa668d33d4ae537321f4e16794dbb33fR166)

File: client/lib/plugins/utils.js [hunk 1]
```diff
@@ -460,3 +460,24 @@ export const getPluginPurchased = ( plugin, purchases, isMarketplaceProduct ) =>
...
+ *
+ * @param {plugin} plugin The plugin object  to read the SaaS redirect url from
+ * @param {number} userId The user id
+ * @param {number} siteId The site id
+ * @returns The URL of the SaaS redirect page or null if it doesn't exist or is an invalid URL
+ */
+export function getSaasRedirectUrl( plugin, userId, siteId ) {
+	if ( ! plugin.saas_landing_page ) {
+		return null;
+	}
```
Comment (WBerredo) [inline client/lib/plugins/utils.js]: Nitpicking: Add `?` would avoid it to break if no plugin is passed.

```suggestion
	if ( ! plugin?.saas_landing_page ) {
		return null;
	}
```

File: client/my-sites/plugins/plugin-details-CTA/index.jsx [hunk 2]
```diff
@@ -117,17 +112,8 @@ const PluginDetailsCTA = ( { plugin, isPlaceholder } ) => {
 	}, [ selectedSite?.slug ] );
 
 	const getSaasRedirectHRef = useCallback( () => {
```
Comment (WBerredo) [inline client/my-sites/plugins/plugin-details-CTA/index.jsx]: Not added in this change, but I'm wondering why this is a callback if we only use its value based on properties. Maybe a `useMemo` would better fit here.

Reference: https://reactjs.org/docs/hooks-reference.html#usememo

**Review by WBerredo — APPROVED** [review]
Everyting is working as described, LGTM!

Added some comments but none of them are blocking, 🚢

File: client/lib/plugins/utils.js (hunk 1 above)
Comment (epeicher) [reply client/lib/plugins/utils.js]: I agree as this is a utility function and it is good to cope with edge cases. Committed

File: client/my-sites/plugins/plugin-details-CTA/index.jsx (hunk 2 above)
Comment (epeicher) [reply client/my-sites/plugins/plugin-details-CTA/index.jsx]: Not any specific reason as they are [equivalent](https://reactjs.org/docs/hooks-reference.html#usecallback), but I agree that `useMemo` is semantically more correct here so I will change it 😄
