### PR TITLE
Jetpack connect: fix auto-auth and flow-type persistence

### LINKED ISSUE #16081: Jetpack Connect: Pre-selected plan is lost for logged out users
#### Steps to reproduce
1. Log out from WP.com and pick a non-connected JP site.
2. Go through the `/jetpack/connect/:flow` flow, for example you can use the `personal` flow.
3. Input your site URL in the JPC form.
4. You will be presented with the signup form.
5. Click the login link below.
6. Log in.
7. Go through the authorization process.
8. You are thrown to the plans page, without a pre-selected plan.

#### What I expected
To have the Jetpack Personal plan pre-selected, and therefore continue to the checkout process.

#### What happened instead
I was presented with the plans selection page

#### Context / Source
Found while testing the new calypso login form #manual-testing

### PR DESCRIPTION
**Pull request by seear**
Fixes #16081.

Store jetpack connect session and flow type in a cookie instead of persisted redux state. Cookies will work across logins, unlike persisted redux state.

See #11119 for cookie prior art.

## Testing
* #16081 should be fixed (in particular the flow type part, for example `/jetpack/connect/pro` )
* Starting the connection in Calypso (for example at `/jetpack/connect` ) should sail through the authorize step without having to click the _Approve_ button

You can keep an eye on the cookie contents in Chrome's _Application_ tab:

screen shot 2017-11-28 at 19 04 10

### CODE REVIEW

File: client/state/jetpack-connect/actions.js [hunk 1]
```diff
@@ -63,6 +64,15 @@ const remoteAuthPath =
 const remoteInstallPath = '/wp-admin/plugin-install.php?tab=plugin-information&plugin=jetpack';
 const remoteActivatePath = '/wp-admin/plugins.php';
 
+const persistSession = ( url, flowType ) => {
+	const options = {
+		maxAge: 300,
```
Comment (seear) [inline client/state/jetpack-connect/actions.js]: This value (seconds) needs to match up with the old `isStale()` check from the selector. Add a constant.

**Comment by seear** [comment]
Rebased.

File: client/jetpack-connect/persistence-utils.js [hunk 2]
```diff
@@ -24,3 +30,31 @@ export const retrievePlan = () => {
...
+};
+
+export const isCalypsoStartedConnection = siteSlug => {
+	const cookies = cookie.parse( document.cookie );
+	return cookies.jetpack_connect_session_url === urlToSlug( siteSlug );
+};
+
+export const persistFlowType = flowType => {
+	const options = { path: '/' };
+	document.cookie = cookie.serialize( 'jetpack_connect_session_flowtype', flowType, options );
```
Comment (seear) [inline client/jetpack-connect/persistence-utils.js]: Maybe we should only allow certain values to be written here?

Comment (sirreal) [reply client/jetpack-connect/persistence-utils.js]: 👍  `flowTypes`:

https://github.com/Automattic/wp-calypso/blob/fc5b6a060e7c0eeb4c2871301a65a96043677c2c/client/jetpack-connect/main.jsx#L52

File: client/jetpack-connect/main.jsx [hunk 3]
```diff
@@ -314,12 +315,7 @@ class JetpackConnectMain extends Component {
 	}
 
 	isInstall() {
-		/*
-		 * FIXME: `return ! this.props.type` should be sufficient
-		 * I'm avoiding significantly changing this implementation
-		 * until propTypes have been around for a while.
-		 */
-		return includes( [ 'install', 'pro', 'premium', 'personal' ], this.props.type );
+		return includes( FLOW_TYPES, this.props.type );
```
Comment (seear) [inline client/jetpack-connect/main.jsx]: I think this existing logic is wrong here, which is why the url entry button says _Install_ for paid flows instead of just the install flow. I'll tackle it in a different PR.

**Comment by sirreal** [comment]
- [x] #16081 should be fixed (in particular the flow type part, for example /jetpack/connect/pro )
     Nice, starting logged out at `/jetpack/connect/personal` I arrive at the cart with a Jetpack Personal plan at the end of the flow (no plans page).
- [x] Starting the connection in Calypso (for example at /jetpack/connect ) should sail through the authorize step without having to click the Approve button
     Starting logged out at `/jetpack/connect?url=my.site.url`, I _do_ breeze through 💨 

Tests nicely, well done.

File: client/jetpack-connect/main.jsx (hunk 3 above)
Comment (sirreal) [reply client/jetpack-connect/main.jsx]: Seems like it

File: client/jetpack-connect/persistence-utils.js [hunk 4]
```diff
@@ -24,3 +31,34 @@ export const retrievePlan = () => {
...
+
+export const clearFlowType = () => {
+	const options = { path: '/' };
+	document.cookie = cookie.serialize( 'jetpack_connect_session_flowtype', '', options );
+};
+
+export const retrieveFlowType = () => {
+	const cookies = cookie.parse( document.cookie );
+	return cookies.jetpack_connect_session_flowtype;
+};
```
Comment (sirreal) [inline client/jetpack-connect/persistence-utils.js]: Just an observation, repeating a lot of code here. Might be nice to abstract helpers `{get,set,clear}Cookie( name, value )` or something along those lines.

**Comment by seear** [comment]
Thanks for review @sirreal !

**Comment by seear** [comment]
Squashed + rebased.

File: client/jetpack-connect/main.jsx (hunk 3 above)
Comment (seear) [reply client/jetpack-connect/main.jsx]: Seems it was intentional in #6460

**Comment by tyxla** [comment]
Awesomeness ❤️  thanks for fixing that one Steve!
