### PR TITLE
Block editor: remove page layout preview from sidebar

### LINKED ISSUE #40766: Gutenboarding: template picker shows incorrect template in the editor
image

We can solve this by removing the thumbnail preview and leaving the "Change Layout" button intact.

See: pbAok1-BW-p2#comment-1566

### LINKED ISSUE #41793: Hide template picker preview thumbnail
(context pbaok1-bw-p2/#comment-1549)

When editing a page, there's a template thumbnail visible in the sidebar:

image

Let's hide the thumbnail as it;
- shows wrong templates for Gutenboarding templates
- gets out of sync very quickly as the user modifies their page
- is out of sync right away if the user is using a different theme than one in the screenshot

The button should be left, but it can be done as "secondary" vs "primary". There should be less primary buttons visible at once at any view:

image

The code for this is in FSE plugin.

### PR DESCRIPTION
**Pull request by p-jackson**
#### Changes proposed in this Pull Request

For the reasons outlined in #41793

**Before**
Screenshot 2020-05-06 at 7 38 55 PM

**After**
Screenshot 2020-05-06 at 7 39 21 PM

* Page layout screenshot removed from document settings sidebar
* "Change Layout" button changed to secondary button style and margin removed
* removed `siteInformation` from the `window.starterPageTemplatesConfig` global sent from server (no longer used)
* Formatting changes from the pre-commit hook

The FSE plugin will need to be deployed after this is merged.

#### Testing instructions

* Clone branch
* `cd apps/full-site-editing && yarn dev`
* `cd apps/full-site-editing && wp-env start` in another terminal
* `localhost:4013/wp-admin` and edit a page
* See changes in the document settings sidebar

You can also see changes as they would appear on wpcom by using `yarn wpcom-sync` and sandboxing a site.

Fixes #40766
Fixes #41793

### CODE REVIEW

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php [hunk 1]
```diff
@@ -32,20 +32,20 @@ class Starter_Page_Templates {
 	private function __construct() {
 		$this->templates_cache_key = implode(
 			'_',
-			[
+			array(
 				'starter_page_templates',
 				PLUGIN_VERSION,
 				get_option( 'site_vertical', 'default' ),
 				get_locale(),
-			]
```
Comment (simison) [inline apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php:40]: This is odd; `[` is newer and we should support it. Are you sure you have the right version of `phpcs` installed?

I was surprised config doesn't define version here: https://github.com/Automattic/wp-calypso/blob/e9d236f7c95333fc09928cbd8a764b66c400eb92/apps/phpcs.xml

Not entirely sure what it should be or how it should be defined ([had a look at Jetpack](https://github.com/Automattic/jetpack/blob/16ec81984f5b14efe89dae5b36acf1e5c740b125/.phpcs.xml.dist#L4))

@vindl do you know what's going on here?

**Comment by simison** [comment]
I feel like switching "Change Layout" to sentence-case "Change layout" but maybe that would bust out translations and it's better to do something like that separately with string-freeze label. :-)

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php (hunk 1 above)
Comment (p-jackson) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php:40]: Kind of out of my depth here, but `$ ./vendor/bin/phpcs --version` says `3.5.3`. When I first commited the pre-commit hook complained at me so I ran `composer install` at the root of my `wp-calypso` repo.

Comment (simison) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php:40]: There's some documentation at PCYsg-ly5-p2 (could just be moved to FSE repo as public docs...).

**Comment by ramonjd** [comment]
Aside from the PHP syntax issue mentioned above, this tests well and LGTM

Screen Shot 2020-05-06 at 7 19 35 pm
Screen Shot 2020-05-06 at 7 19 53 pm

I switched to master and ran `./vendor/bin/phpcs apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php` and got a lot of errors, mostly indents and spacings, but nothing about array syntax.

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php (hunk 1 above)
Comment (noahtallen) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php:40]: Yeah, phpcs keeps auto-formatting these files to the old array syntax. I'm not sure why; I don't think anyone has had a chance to look into it

**Comment by noahtallen** [comment]
This seems fine to me, but I will say from a UX point of view it's weird that you have to:
1. Click one of the menus to open it
2. Click a button to open the layout selector

Seems like those could be rolled into a single action now that there isn't anything else going on in the area. Probably not important though

Also, if i could push back for half a sec, I wonder if users find the preview helpful. It seems like the visual would help someone understand exactly what the button does -- and now it blends in with the rest of the interface.

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php (hunk 1 above)
Comment (simison) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php:40]: I wonder if defining new enough PHP version like in https://github.com/Automattic/jetpack/blob/997026990b6d74f843ce7c5137cd2e7e8672ab2b/.phpcs.xml.dist#L4 would help.

**Comment by simison** [comment]
>     Click one of the menus to open it
>    Click a button to open the layout selector

I didn't test but I was assuming the section would be auto-opened by default. :-)

**Comment by noahtallen** [comment]
>  I was assuming the section would be auto-opened by default

I think it is in most cases :)

**Comment by p-jackson** [comment]
> It seems like the visual would help someone understand exactly what the button does

This is probably true. So many things could be called layout, so which of those things is this talking about?

But I also think the fact the image drifts away from reality doesn't help the user either. @rickybanister do you think it'd be worth trying a static image to clue the user in? Something reminiscent of a block layout maybe like the old block patterns icon?

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php (hunk 1 above)
Comment (p-jackson) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php:40]: I tried setting the `testVersion` but alas that didn't fix it. I also pinned all the dependencies to the same ones used by Jetpack, but that also wasn't it.

Not a long term solution, but I'm just going to commit again and skip hooks so that the diff is smaller.

**Comment by rickybanister** [comment]
I think that the whole layout picker is due for a greater rethink, especially with patterns joining blocks in the inserter. I hesitate to spend too much time on this without considering how it fits into other aspects of page editing.

I could imagine us trying something a little different like this:

Screen Shot 2020-05-06 at 7 39 55 PM

We don't currently expose names per layout, so we'd have to solve that. 

I'm ok with just the button for now honestly, while we work out a few other things.

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php (hunk 1 above)
Comment (andrewserong) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php]: I was wondering if we need to switch to `NeutronStandard` which includes the [DisallowLongformArraySniff](https://github.com/Automattic/phpcs-neutron-standard/blob/master/NeutronStandard/Sniffs/Arrays/DisallowLongformArraySniff.php)?

Comment (andrewserong) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php]: (But skipping the hooks to get your diff smaller for now sounds like the way to go 👍)

**Comment by rickybanister** [comment]
> consensus

Just noting for the record that my opinion doesn't amount to consensus :P

**Comment by ramonjd** [comment]
> Just noting for the record that my opinion doesn't amount to consensus :P

🤣 

I'm drawing results from a very rough qualitative aggregate of Slack, p2, Github and imaginary conversations.

**Comment by p-jackson** [comment]
I've canvased the opinions of 6 hypothetical characters who might join the team one day. They all agreed with me.

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php (hunk 1 above)
Comment (p-jackson) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php]: skipping the hooks to ~get your diff smaller for now~ punt the problem to the next person 😅
