### PR TITLE
Subscription Management: Fix mutation updates related to `useSiteSubscribeMutation` and `useSiteUnsubscribeMutation`

### LINKED ISSUE #77093: Subscription Management: Update site subscriptions count when the user unsubscribes or resubscribes
### Details

The number of site subscriptions should decrement or increment depending on if the user unsubscribed or resubscribed:

Markup on 2023-05-18 at 15:24:34

Details:

- the text should state "subscribers" instead of "followers" (contrary to the screenshot)
- the number should be formatted with commas (as can be seen in the screenshot)
- let's use optimistic updates

Design: inDLaEQV8jJ21O4WXawIsJ-fi-712_30652

### Checklist

_No response_

### Related

_No response_

### PR DESCRIPTION
**Pull request by ivan-ottinger**
Resolves https://github.com/Automattic/wp-calypso/issues/77093.

TODO:
- [x] rebase this PR and resolve conflicts after https://github.com/Automattic/wp-calypso/pull/77266#pullrequestreview-1441130804 is merged.

## Proposed Changes

* add `onMutate` (including optimistic update for `subscriber_count`), `onError` and `onSettled` (invalidating queries after successful resubscribe) to `useSiteSubscribeMutation` 
* add optimistic update for `subscriber_count` to `useSiteUnsubscribeMutation`
* fix "`date_subscribed` undefined" error that manifested on resubscribe

### External user

https://github.com/Automattic/wp-calypso/assets/25105483/d2b4329e-2ac1-440f-99d1-91b95088c883

### Logged-in user

https://github.com/Automattic/wp-calypso/assets/25105483/e7846cb8-5ade-49b5-8649-284ed2421be0

### Testing as an external user
1. Check out the PR and build the app.
2. Authenticate as an external user (`subkey` "dance" in the incognito browser window).
3. Make sure your external user is subscribed to some sites already.
4. Navigate to `http://calypso.localhost:3000/subscriptions/site/[blog_id]` where `[blog_id]` needs to be replaced with a specific blog ID your user is subscribed to.
5. When the page loads, make sure the "Email me new posts" is set to something else than "Immediately". 
6. Click on the "Cancel subscription" button on the bottom of the page.
7. The user should be unsubscribed from the site (this can be checked at https://wordpress.com/subscriptions/sites), the settings should be hidden, success notice should display and the `subscriber_count` should be decremented.
8. Click on the "Resubscribe" button. You should be resubscribed to the site, the settings should display again, `subscriber_count` should increment, "Email me new posts" setting should switch to "Immediately" (the default value)  and the "Date" to "just now".

Feel free to compare the behavior with the screen recording above.

### Testing as a logged-in user
1. Check out the PR.
2. Navigate to `client/server/pages/index.js` and temporarily add `return next();` to the line `833`:

Markup on 2023-04-28 at 17:50:44

3. Build the app.
4. Log in to a test WordPress.com account that has some existing Site subscriptions.
5. Navigate to `http://calypso.localhost:3000/subscriptions/site/[blog_id]` where `[blog_id]` needs to be replaced with a specific blog ID your user is subscribed to.
6. When the page loads, change the settings randomly.
7. Click on the "Cancel subscription" button on the bottom of the page.
8. The user should be unsubscribed from the site (this can be checked at https://wordpress.com/subscriptions/sites), the settings should be hidden, the success notice should display and `subscriber_count` should decrement (similarly as when testing with the external user).
9. Click on the "Resubscribe" button. You should be resubscribed to the site, `subscriber_count` should increment and the settings should display again while switching to their default values.

Feel free to compare the behavior with the screen recording above.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by ivan-ottinger** [comment]
This PR is not yet ready for full review (as I still need to add the description and testing instructions), but I am sharing it already in case somebody would like to take a look earlier.

Tomorrow I will add all the details and make the PR ready for full review. 🙂

**Comment by ivan-ottinger** [comment]
Just noting that this PR is now freshly rebased.

File: packages/data-stores/src/reader/mutations/use-site-unsubscribe-mutation.ts [hunk 1]
```diff
@@ -107,9 +132,17 @@ const useSiteUnsubscribeMutation = () => {
...
+			if ( context?.previousSiteSubscriptionDetails ) {
+				queryClient.setQueryData(
+					siteSubscriptionDetailsCacheKey,
+					context.previousSiteSubscriptionDetails
+				);
+			}
 		},
 		onSettled: () => {
-			// pass in more minimal keys, everything to the right will be invalidated
+			// We are not invalidating the `siteSubscriptionDetailsCacheKey` on purpose here,
```
Comment (mashikag) [inline packages/data-stores/src/reader/mutations/use-site-unsubscribe-mutation.ts]: It sounds not right to me. The react-query is meant to resemble backend state. Using it for frontend state management will potentially make it more difficult to maintain in the future.

Comment (ivan-ottinger) [reply packages/data-stores/src/reader/mutations/use-site-unsubscribe-mutation.ts]: Thanks for your feedback, Maciej!

I think I have a better solution now, using `refetchType: 'none'` in the `invalidateQueries` call:

```js
queryClient.invalidateQueries( siteSubscriptionDetailsCacheKey, { refetchType: 'none' } );
```

Will test it out and if it works as expected, commit the change.

Comment (ivan-ottinger) [reply packages/data-stores/src/reader/mutations/use-site-unsubscribe-mutation.ts]: This is now addressed in https://github.com/Automattic/wp-calypso/pull/77264/commits/ede480f83dcfd6bfc141ac7741cff5a0edfc37d5.

File: packages/data-stores/src/reader/mutations/use-site-unsubscribe-mutation.ts [hunk 2]
```diff
@@ -14,11 +18,16 @@ type UnsubscribeResponse = {
...
-const useSiteUnsubscribeMutation = () => {
+const useSiteUnsubscribeMutation = ( blog_id?: string ) => {
 	const { isLoggedIn } = useIsLoggedIn();
 	const queryClient = useQueryClient();
 	const siteSubscriptionsCacheKey = useCacheKey( [ 'read', 'site-subscriptions' ] );
 	const subscriptionsCountCacheKey = useCacheKey( [ 'read', 'subscriptions-count' ] );
+	const siteSubscriptionDetailsCacheKey = useCacheKey( [
+		'read',
+		'site-subscription-details',
+		...( blog_id ? [ blog_id ] : [] ),
```
Comment (mashikag) [inline packages/data-stores/src/reader/mutations/use-site-unsubscribe-mutation.ts:29]: I think in terms of the cache key, it is perfectly fine to just spit out `blog_id` as is, even if it is `undefined`. But I suppose there is nothing wrong with this solution too. 🙂

Comment (ivan-ottinger) [reply packages/data-stores/src/reader/mutations/use-site-unsubscribe-mutation.ts:29]: Thanks for the suggestion, Maciej!

The reason for the construction above is that I didn't want to have the empty string, nor word "undefined" as a part of the cache key. But I agree that your proposal makes the code cleaner.

**Review by mashikag — APPROVED** [review]
All looks good to me now! 🚀
