### PR TITLE
Plans Grid: show expired plan as spotlight

### LINKED ISSUE #85310: Expired plans show up as Free on the plans page
### Quick summary

If you have a plan that is expired but has not been removed yet, the Plans page shows your plan as being "Free" (even though other parts of the page correctly identify that you still own a paid plan).

In the screenshot below, the blue arrows are basically correct, and the red arrow shows the problem:

expired-plan

I feel like we've seen similar bugs elsewhere (but I can't remember), and there might be some particular API in Calypso that is (deliberately) ignoring the existence of expired plans, and that API shouldn't be used here.

### Steps to reproduce

1. Get a site with an expired plan (i.e. a few days past its expiration date).  Automatticians can set this up themselves, but otherwise I guess you have to wait :smile: 
2. Visit https://wordpress.com/plans for your site, while logged in as the site owner

### What you expected to happen

Some indication that the plan was still on my site, probably also indicating that it is expired (as done elsewhere in Calypso).

### What actually happened

It said I had a free plan, even though I don't (and even though that contradicts information elsewhere on the page).

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by aneeshd16**
Fixes #85310

## Proposed Changes

* The free plan was shown as the current plan instead of the expired plan because the `getSitePlanSlug` selector returned the free plan if the current plan had expired. We were also using two different selectors (`getCurrentPlan` and `getSitePlanSlug`) which essentially did the same thing. In this PR, I have replaced the `getSitePlanSlug` selector with `currentPlan?.productSlug`, and it reduces the chance of a data mismatch.
* Added a new selector, `isCurrentPlanExpired`, which is similar to the existing `isCurrentPlanExpiring`. This is used to modify the text of the CTA on the spotlight plan to "Renew Plan" if the plan has expired.

### Screenshots
| Production | This PR |
|--------|--------|
|image |image |

## Testing Instructions

* Get a site with an expired plan (i.e. a few days past its expiration date). Automatticians can set this up themselves(using SA).
* Visit `/plans<site slug>` for your site, while logged in as the site owner.
* Confirm that the expired plan is shown in the spotlight card.
* Confirm that the CTA text is "Renew Plan".

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/my-sites/plans-features-main/index.tsx [hunk 1]
```diff
@@ -67,8 +67,12 @@ import getDomainFromHomeUpsellInQuery from 'calypso/state/selectors/get-domain-f
 import getPreviousRoute from 'calypso/state/selectors/get-previous-route';
 import isEligibleForWpComMonthlyPlan from 'calypso/state/selectors/is-eligible-for-wpcom-monthly-plan';
 import { isUserEligibleForFreeHostingTrial } from 'calypso/state/selectors/is-user-eligible-for-free-hosting-trial';
-import { getCurrentPlan, isCurrentUserCurrentPlanOwner } from 'calypso/state/sites/plans/selectors';
-import { getSitePlanSlug, getSiteSlug, isCurrentPlanPaid } from 'calypso/state/sites/selectors';
+import {
+	getCurrentPlan,
```
Comment (chriskmnds) [inline client/my-sites/plans-features-main/index.tsx]: You can also use [Plans.useCurrentPlan](https://github.com/Automattic/wp-calypso/blob/trunk/packages/data-stores/src/plans/hooks/use-current-plan.ts) from data-stores package. It would be nice to start moving things closer to the data-store approach.

File: client/state/sites/plans/selectors/is-current-plan-expired.ts [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+export function isCurrentPlanExpired( state: IAppState, siteId: SiteId ): boolean | null {
+	const currentPlan = getCurrentPlan( state, siteId );
+
+	if ( ! currentPlan || ! currentPlan.expiryDate ) {
+		return null;
+	}
+
+	const expiration = moment( currentPlan.expiryDate ).startOf( 'day' );
+	return expiration < moment();
+}
```
Comment (chriskmnds) [inline client/state/sites/plans/selectors/is-current-plan-expired.ts]: Similarly. This could fit under `/packages/data-stores/src/plans/hooks`
although not sure about importing `moment`, if not already imported. it's possible to do the logic with `Date` construct.

File: client/my-sites/plans-features-main/index.tsx (hunk 1 above)
Comment (aneeshd16) [reply client/my-sites/plans-features-main/index.tsx]: Nice! I wasn't aware about this hook.

File: client/state/sites/plans/selectors/is-current-plan-expired.ts (hunk 2 above)
Comment (aneeshd16) [reply client/state/sites/plans/selectors/is-current-plan-expired.ts]: Sounds good! I had assumed `moment` was used to parse a non-standard date format, but it turns out that the expiry date is returned in ISO 8601 format, which can be parsed by `Date()` in all browsers. (fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Snqzva%2Qcyhtvaf%2Sjcpbz%2Qovyyvat%2Sfgber%2Qcebqhpg%2Qyvfg.cuc%3Se%3Q6283np92%232591-og)

**Comment by aneeshd16** [comment]
Thanks for the review, @chriskmnds! I am currently waiting on design (https://github.com/Automattic/wp-calypso/issues/85310#issuecomment-2048952809), and I'll address the review feedback when I get an update.

**Comment by aneeshd16** [comment]
Hi @chriskmnds and @southp, can you please have another look when you can? I have updated the PR so that the plan is shown and the spotlight plan CTA is "Renew Plan" if the plan has expired. There are more extensive changes (p9Jlb4-bSl-p2) planned for the spotlight card, so the objective of this PR is just to fix the original bug.

File: client/my-sites/plans-features-main/index.tsx [hunk 3]
```diff
@@ -454,7 +453,7 @@ const PlansFeaturesMain = ( {
 	let _customerType = chooseDefaultCustomerType( {
 		currentCustomerType: customerType,
 		selectedPlan,
-		currentPlan: { productSlug: currentPlan?.productSlug },
+		currentPlan: { productSlug: currentPlan?.productSlug || PLAN_FREE },
```
Comment (chriskmnds) [inline client/my-sites/plans-features-main/index.tsx]: Why is this necessary? If `currentPlan` exists as `undefined`, then we should probably update the method to work with `undefined` values.

File: packages/data-stores/src/plans/hooks/use-get-current-plan-expiry-date.ts [hunk 4]
```diff
@@ -0,0 +1,17 @@
+import useCurrentPlan from './use-current-plan';
+
+interface Props {
+	siteId?: string | number | null;
+}
+
+const useCurrentPlanExpiryDate = ( { siteId }: Props ): Date | undefined => {
```
Comment (chriskmnds) [inline packages/data-stores/src/plans/hooks/use-get-current-plan-expiry-date.ts]: I meant to ask if this selector was necessary, but I can see that we may want to keep `SitePlan->expiry` raw and project onto a Date through a selector.

Perhaps we should rename the file though to match the selector (`use-get-current-plan-expiry-date.ts` -> `use-current-plan-expiry-date.ts`)?

**Review by chriskmnds — COMMENTED** [review]
Heya. just a run-by review with some comments. will do some testing next

File: packages/data-stores/src/plans/hooks/use-get-current-plan-expiry-date.ts (hunk 4 above)
Comment (aneeshd16) [reply packages/data-stores/src/plans/hooks/use-get-current-plan-expiry-date.ts]: Good catch! Changed it.

**Comment by chriskmnds** [comment]
@aneeshd16 Looks good in my testing. works as outlined

File: client/my-sites/plans-features-main/index.tsx (hunk 3 above)
Comment (aneeshd16) [reply client/my-sites/plans-features-main/index.tsx]: Good catch! It wasn't necessary and I have removed it.
