### PR TITLE
Login Assistance: Revert the "show migrate CTA when login fails" experiment

### LINKED ISSUE #93074: Login Assistance: Revert the experiment code
### Details

The code related to the 21864-explat-experiment should be reverted.

Context: pdxWSz-1G5-p2#comment-587

Related PRs: https://github.com/Automattic/wp-calypso/pull/91188, https://github.com/Automattic/wp-calypso/pull/92245, https://github.com/Automattic/wp-calypso/pull/91607

### PR DESCRIPTION
**Pull request by m1r0**
Resolves https://github.com/Automattic/wp-calypso/issues/93074

## Proposed Changes

* Revert all the code related to the experiment.

## Why are these changes being made?

* Based on the related experiments, it was decided that this is not something that we want to pursue. More context here: pdxWSz-1G5-p2#comment-587

## Testing Instructions

* Go to http://calypso.localhost:3000/log-in.
* Test the login form.
* Make sure the error message is displayed when you fail to log in.
* Make sure the form works correctly when you log in with the correct credentials.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/lib/login/index.js [hunk 1]
```diff
@@ -15,10 +15,6 @@ import {
 } from 'calypso/lib/oauth2-clients';
 import { login } from 'calypso/lib/paths';
 
-function getCookies() {
```
Comment (donnapep) [inline client/lib/login/index.js]: It seems to me that this would be a worthwhile change to keep.

**Review by donnapep — APPROVED** [review]
Looks good, though I think we may as well go ahead and keep the `getCookies` function in case we need it in future.
