### PR TITLE
Site Assembler - Focus first pattern in a category (fix for scroll)

### LINKED ISSUE #75423: Site Assembler - Focus the first pattern in the category when switching categories
## What

When exploring patterns the scroll position is persisted after switching categories.

## Why

Because users can miss the patterns at the top because they are already scrolled. 

## How

When a category is selected and its patterns load in the panel, scroll to the top of the list automatically.

### PR DESCRIPTION
**Pull request by miksansegundo**
Related to #75365
Closes #75423

## Proposed Changes

* Focus on the first pattern in a category when the patterns panel opens

While #75365 addressed the same issue, it didn't work when the patterns list is scrolled. The version in this PR always focuses on the first pattern in the list when exploring patterns in categories because it resets the previous scroll position.

https://user-images.githubusercontent.com/1881481/230820302-471c7e83-21bf-4afe-b9cf-6c22582bdb7a.mov

## Testing Instructions

- Click on the Calypso Live link in the first comment.
- Create a new site and `Continue` until landing on the Design Picker.
- Go to the site assembler by clicking `Start designing` from the bottom.
- Click `Sections`, then `Add patterns` and click on `Posts` category and scroll to the bottom of the list, then click `Call to action` and verify that the first pattern is focused.

## Pre-merge Checklist

- [X] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [X] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [X] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [X] Have you checked for TypeScript, React or other console errors?
- [X] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [X] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [X] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-list-renderer.tsx [hunk 1]
```diff
@@ -28,24 +27,12 @@ interface PatternListRendererProps {
...
-	onSelect,
-}: PatternListItemProps ) => {
+const PatternListItem = ( { pattern, className, isShown, onSelect }: PatternListItemProps ) => {
 	const [ inViewOnce, setInViewOnce ] = useState( false );
 	const ref = useInView< HTMLButtonElement >( () => setInViewOnce( true ), {
 		threshold: [ 0 ],
 	} );
 
-	useEffect( () => {
-		if ( isShown && inViewOnce && isFirst && ref.current ) {
```
Comment (arthur791004) [inline client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-list-renderer.tsx:44]: I guess we can simply remove `inViewOnce` from the condition to fix the issue. WDYT?

Comment (miksansegundo) [reply client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-list-renderer.tsx:44]: OKay 👍

**Review by okmttdhr — APPROVED** [review]
Thank you for your fix!
