### PR TITLE
Marketing -> Traffic settings: Fix SEO & Analytics Settings for Free plans

### LINKED ISSUE #51828: Marketing -> Traffic settings: Fix for Free plans
### What plan tier is the site on?
Free

### Where are you seeing the issue?
Marketing > Traffic settings 

Both Google Analytics and wpcom's SEO feature needs consideration when on a Free plan on Atomic. 

#### What I expected on the Atomic site
image
image

#### What actually happened
image
image

### PR DESCRIPTION
**Pull request by allilevine**
#### Changes proposed in this Pull Request

Show the correct banners on Tools > Marketing > Traffic > Search Engine Optimization and Google Analytics:
- Use `hasActiveSiteFeature()` to check if we should show a banner / nudge or the setting
- Use `isAtomic` to show the correct nudge or form

#### Testing instructions

* On a free Atomic site, open Tools > Marketing > Traffic settings.
* There should be upsell nudges under Search engine optimization and Google Analytics.
* Clicking the upsell nudges goes to plans, not checkout.
* Repeat for Personal and Premium plans on Atomic sites. Google Analytics should be available with no nudge on Premium Atomic.
* Regression: 
    * Regular/paid Atomic: SEO and Analytics should be available, no nudge.
    * Simple: The nudges should be the same as for free, Personal, and Premium Atomic.
    * VIP (see: PCYsg-zan-p2): SEO has a nudge with no plan, Google Analytics is available.
    * Jetpack: SEO should be available on all plans, Analytics is not available on free Jetpack and there should be a Jetpack checkout nudge.

Simple | Free Atomic | Regular Atomic
------- | ------------ | ---------------
Screen Shot 2021-06-01 at 5 04 32 PM | Screen Shot 2021-06-01 at 5 05 11 PM | Screen Shot 2021-06-01 at 5 05 32 PM
Screen Shot 2021-06-01 at 5 04 41 PM | Screen Shot 2021-06-01 at 5 05 19 PM | Screen Shot 2021-06-01 at 5 05 41 PM

[
Follow-up needed](https://github.com/Automattic/wp-calypso/issues/54555) to fix the upsell nudge link plan slugs for free Atomic (should be business-bundle and value_bundle).

Fixes #51828

### CODE REVIEW

File: client/my-sites/marketing/traffic/index.js [hunk 1]
```diff
@@ -108,7 +109,8 @@ const connectComponent = connect( ( state ) => {
 	const siteId = getSelectedSiteId( state );
 	const isAdmin = canCurrentUser( state, siteId, 'manage_options' );
 	const isJetpack = isJetpackSite( state, siteId );
-	const isJetpackAdmin = isJetpack && isAdmin;
+	const isFreeAtomic = isFreeAtomicSite( state, siteId );
+	const isJetpackAdmin = isJetpack && isAdmin && ! isFreeAtomic;
```
Comment (allilevine) [inline client/my-sites/marketing/traffic/index.js]: I used `isFreeAtomic` rather than `isAtomic` here since these settings are currently available to Atomic sites.

File: client/my-sites/site-settings/analytics/form-google-analytics.jsx [hunk 2]
```diff
@@ -89,7 +90,7 @@ export const GoogleAnalyticsForm = ( props ) => {
 		recordSupportLinkClick,
 		setDisplayForm,
 	};
-	if ( props.siteIsJetpack ) {
+	if ( props.siteIsJetpack && ! props.siteIsFreeAtomic ) {
```
Comment (allilevine) [inline client/my-sites/site-settings/analytics/form-google-analytics.jsx]: I used `isFreeAtomic` rather than `isAtomic` here since the Jetpack version of this form is currently available to Atomic sites.

File: client/my-sites/site-settings/seo-settings/form.jsx [hunk 3]
```diff
@@ -332,7 +336,7 @@ export class SeoForm extends React.Component {
 				<QuerySiteSettings siteId={ siteId } />
 				{ siteId && <QueryJetpackPlugins siteIds={ [ siteId ] } /> }
 				{ siteIsJetpack && <QueryJetpackModules siteId={ siteId } /> }
-				{ ( isSitePrivate || isSiteHidden ) && hasSiteSeoFeature( selectedSite ) && (
+				{ ( isSitePrivate || isSiteHidden ) && showAdvancedSeo && (
```
Comment (allilevine) [inline client/my-sites/site-settings/seo-settings/form.jsx:331]: `showAdvancedSeo` includes a check for `hasSiteSeoFeature( selectedSite )`, while making sure we don't show this warning on `jetpack_free` sites. We could leave this as-is though, if there are other types of sites that should show it.

File: client/my-sites/site-settings/seo-settings/form.jsx [hunk 4]
```diff
@@ -482,13 +486,17 @@ const mapStateToProps = ( state ) => {
...
 	// SEO Tools are available with Business plan on WordPress.com, and
 	// will soon be available on all Jetpack sites, so we're checking
 	// the availability of the module.
 	const isAdvancedSeoEligible =
 		selectedSite.plan &&
 		hasSiteSeoFeature( selectedSite ) &&
-		( ! siteIsJetpack || get( getJetpackModules( state, siteId ), 'seo-tools.available', false ) );
+		( ! siteIsJetpack ||
+			get( getJetpackModules( state, siteId ), 'seo-tools.available', false ) ) &&
+		! siteIsFreeAtomic;
```
Comment (allilevine) [inline client/my-sites/site-settings/seo-settings/form.jsx]: Free Atomic sites will return true without this check.

File: client/my-sites/site-settings/seo-settings/help.jsx [hunk 5]
```diff
@@ -25,16 +26,18 @@ const SeoSettingsHelpCard = ( {
...
+	siteIsFreeAtomic,
 	translate,
 } ) => {
-	const seoHelpLink = siteIsJetpack
-		? 'https://jetpack.com/support/seo-tools/'
-		: 'https://wpbizseo.wordpress.com/';
+	const seoHelpLink =
+		siteIsJetpack && ! siteIsFreeAtomic
+			? 'https://jetpack.com/support/seo-tools/'
+			: 'https://wpbizseo.wordpress.com/';
```
Comment (allilevine) [inline client/my-sites/site-settings/seo-settings/help.jsx]: Checking for `isFreeAtomic` here as well, to keep Atomic access to Jetpack features.

**Comment by allilevine** [comment]
I'm running into an issue with the upsell nudge links to plans. We look for `findFirstSimilarPlanKey()`, rather than for the specific plan, so we're getting Jetpack plans like `&plan=jetpack_business` rather than `&plan=business-bundle`:

https://github.com/Automattic/wp-calypso/blob/75e0cab9778cbf5b37ccf27fa1f84a610b8c452e/client/my-sites/site-settings/seo-settings/form.jsx#L324-L328

I tried changing to specific plans, but we offer different interval upgrades, so that breaks the tests.

As a result, the highlighting on the plans page is incorrect:
Screen Shot 2021-06-01 at 5 35 09 PM

That may be best fixed in a separate PR though.

File: client/lib/site/utils.js [hunk 6]
```diff
@@ -176,3 +178,16 @@ export function hasSiteFeature( site, feature ) {
...
+
+/**
+ * Checks if the site has a free plan and is Atomic.
+ *
+ * @param {object} state  Global state tree
+ * @param {number} siteId Site ID
+ * @returns {boolean} True if site is free and Atomic
+ */
+export function isFreeAtomicSite( state, siteId ) {
+	const isAtomic = isAtomicSite( state, siteId );
```
Comment (retrofox) [inline client/lib/site/utils.js]: Does it make sense to bail early when it isn't an Atomic site? Something like...
```suggestion
	const isAtomic = isAtomicSite( state, siteId );
	if ( ! isAtomic ) {
	  return false;
  }
```

**Comment by retrofox** [comment]
Hi, there 👋 
I'm not 100% sure about adding this selector.

> Add isFreeAtomicSite helper and use the new helper to determine which banners and settings to show on
Marketing > Traffic.

I immediately start to think that we're going to add `isPremiumAtomicSite`, isFreeSimpleSite` and all combinations.
On the other hand, adding this selector reduces the amount of code that makes adding it sense.

👍 to add the selector, but I'd like to hear other opinions.

**Comment by cpapazoglou** [comment]
I agree with @retrofox! While currently we don't allow Atomic sites to buy a Personal or Premium plan, let's think ahead.

I wonder if we should check for explicit plans rather than `siteIsJetpack && ! siteIsFreeAtomic `. 
We shouldn't really care whether the site is in Simple or Atomic. It seems that in the past we have used the infrastructure type as an easy way to enable / disable features. 

Wouldn't it be better to check whether current plan supports X feature? Something like this 
https://github.com/Automattic/wp-calypso/blob/b703449c2b079916da70356acd66ca823760cebf/client/state/sites/plans/selectors/has-feature.js#L19-L21

**Comment by allilevine** [comment]
> I immediately start to think that we're going to add `isPremiumAtomicSite`, isFreeSimpleSite` and all combinations.
> I agree with @retrofox! While currently we don't allow Atomic sites to buy a Personal or Premium plan, let's think ahead.

@retrofox @cpapazoglou That's a good point, we might allow different Atomic plans in the future. 

> I wonder if we should check for explicit plans rather than `siteIsJetpack && ! siteIsFreeAtomic`.

The issue (as described here: pd2C1Z-Q-p2) is that the plan for free Atomic sites is `jetpack_free`. With all of these `isJetpack && ! isAtomic` and `isJetpack && ! isFreeAtomic` checks, we're adding hacks to change that behavior in the UI. I agree that it would be better to check for plans and features, but as far as I can tell we need to change the plan for that to work.

**Comment by retrofox** [comment]
I agree we are dealing with these issues using basic helpers bringing duplicated code. Maybe we should start to consider adding smarter selectors/helpers considering the new site variations depending on:

* the platform (Simple, Jetpack, Atomic)
* the plan: Free, Personal, Business, eCommerce, etc
* the features

### Platform helpers / selectors

* `isSimpleSite()`
* `isJetpackSite()`
* `isAtomicSite()`

I've seen that sometimes we'd like to know when the site is exclusively a Jetpack site (not Atomic). We could create a new helper for this, or maybe add a parameter to the helper function:

```js
function isJetpackSite(  notAtomic = false ) {
  // Check whether the Jetpack is not Atomic site.
  if ( notAtomic && isAtomicSite() ) {
    return false;
  }
};
```

### Plans helpers / selectors

### Features helpers / selectors

* `hasMarketplaceAddOns()`

Is it a good moment to review/audit the current implementation and start coming up with a refactoring plan?

**Review by mmtr — COMMENTED** [review]
Nice, overall this works quite well for me.

Is it possible to change the plan slug used in the URL?

On Simple sites we use `business-bundle`, so the Business plan gets highlighted:

Screen Shot 2021-06-03 at 16 25 57
Screen Shot 2021-06-03 at 16 27 58

However, on Free Atomic sites we use `jetpack_business` which is not available on WP.com so none of the plans gets highlighted:

Screen Shot 2021-06-03 at 16 26 29
Screen Shot 2021-06-03 at 16 29 24

**Comment by mmtr** [comment]
Also noted a small regression on my Free Jetpack site.

On production, we directly link to the checkout page:

Screen Shot 2021-06-03 at 16 35 04

On this branch, we link to the plans page:
Screen Shot 2021-06-03 at 16 35 33

**Comment by retrofox** [comment]
> Also noted a small regression on my Free Jetpack site.

Is it an Atomic site? Because it may redirect the user to the plans page instead of the checkout one when it's an Atomic site.

**Comment by mmtr** [comment]
> Is it an Atomic site? Because it may redirect the user to the plans page instead of the checkout one when it's an Atomic site.

No, it's a Jetpack site

**Comment by allilevine** [comment]
> Is it possible to change the plan slug used in the URL?

@mmtr Thanks for taking a look! I'd written [a comment above](https://github.com/Automattic/wp-calypso/pull/53196#issuecomment-852461882) about why I was hesitant to make that change in this PR. I decided to try again since we shouldn't need to worry about plan intervals when we're starting with a free plan anyway. It seems to be working (with some test fixes), but the highlight for Premium / Google Analytics is still wrong:
Screen Shot 2021-06-03 at 5 58 50 PM
The cause seems to be that we don't allow Atomic sites on a free plan / no plan to upgrade to Premium:
- We only add the `is-highlighted` class if `availableForPurchase` is `true` (as of https://github.com/Automattic/wp-calypso/pull/53146)
- `availableForPurchase` is only `true` if `canUpgradeToPlan()` returns `true`
- `canUpgradeToPlan()` doesn't allow Atomic sites without a plan to upgrade to Premium:
https://github.com/Automattic/wp-calypso/blob/e797df8452361ce7ead6ae1cdfec37378da0309c/client/state/selectors/test/can-upgrade-to-plan.js#L347-L351

Changing that seems like it should be handled in a separate PR. Let me know if I've missed anything there.

> Also noted a small regression on my Free Jetpack site.

Let me know if this is fixed now. I've made the logic for which banner to show more specific. It should look like this for free Jetpack:
Screen Shot 2021-06-03 at 6 09 50 PM

**Comment by mmtr** [comment]
> The cause seems to be that we don't allow Atomic sites on a free plan / no plan to upgrade to Premium:

Yeah, this is fine to address on a follow-up. My comment was specifically for the SEO banner which requires the Business plan and it's available for Atomic sites, but missed to explicitly note it. I see it has been now fixed 🎉 

> I've made the logic for which banner to show more specific. It should look like this for free Jetpack:

Awesome, I can confirm it's been fixed now.

File: client/lib/site/utils.js [hunk 7]
```diff
@@ -176,3 +177,17 @@ export function hasSiteFeature( site, feature ) {
...
+/**
+ * Checks if the site is eligible for SEO features.
+ *
+ * @param {object} site Site to check
+ * @param {string} state State tree
+ * @param {string} siteId Site id
+ * @returns {boolean} True if does
+ */
+export function isEligibleForSEOFeatures( site, state, siteId ) {
+	if ( site && site.plan && state ) {
```
Comment (mmtr) [inline client/lib/site/utils.js]: Nitpick: Show we return false when this check doesn't pass?

File: client/my-sites/marketing/traffic/index.js [hunk 8]
```diff
@@ -105,10 +106,12 @@ const SiteSettingsTraffic = ( {
 );
 
 const connectComponent = connect( ( state ) => {
+	const site = getSelectedSite( state );
 	const siteId = getSelectedSiteId( state );
 	const isAdmin = canCurrentUser( state, siteId, 'manage_options' );
 	const isJetpack = isJetpackSite( state, siteId );
-	const isJetpackAdmin = isJetpack && isAdmin;
+	const isEligible = isEligibleForSEOFeatures( site, state, siteId );
+	const isJetpackAdmin = isJetpack && isAdmin && isEligible;
```
Comment (mmtr) [inline client/my-sites/marketing/traffic/index.js]: `isJetpackAdmin` seems used for other features than SEO like Stats or the WP.me Shortlinks. Why `isEligibleForSEOFeatures` is controlling these features?

File: client/my-sites/site-settings/analytics/form-google-analytics-simple.jsx [hunk 9]
```diff
@@ -73,9 +75,11 @@ const GoogleAnalyticsSimpleForm = ( {
 	};
 
 	const renderForm = () => {
-		const plan = findFirstSimilarPlanKey( site.plan.product_slug, {
-			type: TYPE_PREMIUM,
-		} );
+		const plan = ! isSEOEligible
```
Comment (mmtr) [inline client/my-sites/site-settings/analytics/form-google-analytics-simple.jsx]: This also confuses me. What's the connection between the SEO and the GA features?

File: client/my-sites/site-settings/analytics/form-google-analytics.jsx [hunk 10]
```diff
@@ -88,8 +90,9 @@ export const GoogleAnalyticsForm = ( props ) => {
 		placeholderText,
 		recordSupportLinkClick,
 		setDisplayForm,
+		isSEOEligible,
 	};
-	if ( props.siteIsJetpack ) {
+	if ( props.siteIsJetpack && isSEOEligible ) {
```
Comment (mmtr) [inline client/my-sites/site-settings/analytics/form-google-analytics.jsx]: Same here, I don't understand why the SEO eligibility is affecting the GA eligibility.

**Review by mmtr — COMMENTED** [review]
Nice! Tested this on a variety of scenarios (Free Simple, Premium Simple, Business Simple, Free Atomic, Business Atomic, Free Jetpack) and they all worked as expected!

Got some questions code-wise though, since I'm really confused about the dependency between the SEO and the Google Analytics features.

File: client/lib/site/utils.js (hunk 7 above)
Comment (allilevine) [reply client/lib/site/utils.js]: Good point, changed here: https://github.com/Automattic/wp-calypso/pull/53196/commits/188710bebb54c56996e0266435a6b2dab5ae487f

File: client/my-sites/marketing/traffic/index.js (hunk 8 above)
Comment (allilevine) [reply client/my-sites/marketing/traffic/index.js]: The issue I'm trying to solve here is that `isJetpackAdmin` returns `true` for a free / no plan Atomic site. There's no particular feature we're checking for, just Jetpack. But this check is used to determine whether to show the Stats and WP.me Shortlinks features. I guess it should really be checking for Analytics feature availability. Would having a `isEligibleForAnalyticsFeatures` helper or using `hasSiteAnalyticsFeature()` help clarify that?

Comment (mmtr) [reply client/my-sites/marketing/traffic/index.js]: > The issue I'm trying to solve here is that `isJetpackAdmin` returns `true` for a free / no plan Atomic site.

Why is this an issue? AFAIK both Stats or the WP.me Shortlinks are features available for free sites, aren't they?

Comment (allilevine) [reply client/my-sites/marketing/traffic/index.js]: Stats and WP.me Shortlinks are available to all Jetpack plans (including free) and Atomic sites. But they’re not available for Simple free sites, under Tools > Marketing > Traffic:

Simple | Atomic
------- | -------
Screen Shot 2021-06-07 at 2 10 31 PM | Screen Shot 2021-06-07 at 2 10 56 PM

We're trying to provide the same experience for free Atomic sites as the one we provide for Simple free. These settings weren't mentioned in the issue, but they're also Marketing -> Traffic settings that shouldn't be available / visible on Atomic free. I think there might be additional issues, like whether we show the ad removal upgrade banner and Cloudflare.

File: client/my-sites/site-settings/analytics/form-google-analytics-simple.jsx (hunk 9 above)
Comment (allilevine) [reply client/my-sites/site-settings/analytics/form-google-analytics-simple.jsx]: This is a check for which plan slug to use in the URL (use `value-bundle` for free Atomic). We could change it to an Analytics eligibility check.

File: client/my-sites/site-settings/analytics/form-google-analytics.jsx (hunk 10 above)
Comment (allilevine) [reply client/my-sites/site-settings/analytics/form-google-analytics.jsx]: This is a check for which Analytics form to show. For Atomic, we show the Jetpack form. But for free Atomic, we want to show the Simple form with WordPress.com plan upgrade nudges. We could change it to an Analytics eligibility check.

File: client/lib/site/utils.js [hunk 11]
```diff
@@ -176,3 +177,19 @@ export function hasSiteFeature( site, feature ) {
...
+ * @param {string} siteId Site id
+ * @returns {boolean} True if does
+ */
+export function isEligibleForSEOFeatures( site, state, siteId ) {
+	if ( ! ( site && site.plan && state ) ) {
+		return false;
+	}
+
+	return ! ( isFreePlan( site.plan.product_slug ) && isSiteWPCOM( state, siteId ) );
+}
```
Comment (pablinos) [inline client/lib/site/utils.js]: I was doing something similar in #53216, but when I started needing to use state, I decided that maybe my equivalent helper function should [live with the other selectors](https://github.com/Automattic/wp-calypso/pull/53216/files#diff-a127bedefab489a412871109c45762ff55c5b2e0bfe0ca7f853f8f3bccce253bR1).

Could it be worth doing the same thing here, or is it better placed in this utils lib?

File: client/my-sites/marketing/traffic/index.js (hunk 8 above)
Comment (mmtr) [reply client/my-sites/marketing/traffic/index.js]: Gotcha. As per the discussion in pd2C1Z-10-p2, I think it makes sense to remove/hide these features from Atomic sites on any plan (free or paid) in order to achieve parity across Simple and Atomic sites (although I recommend allowing users to turn on the features if they were deactivated in the past).

As per the helper function used for determining if a site is eligible for a feature, I don't see a clear correlation between WP.me shortlinks or Stats, so I like your suggestion of creating a more abstract `hasSiteAnalyticsFeature` function which checks if a given feature is available for a given site (e.g. `hasSiteAnalyticsFeature( state, siteId, 'shortlinks' )`).

File: client/my-sites/site-settings/analytics/form-google-analytics-simple.jsx (hunk 9 above)
Comment (mmtr) [reply client/my-sites/site-settings/analytics/form-google-analytics-simple.jsx]: Since the plan slug actually depends on the site (`value-bundle` for WP.com sites, `jetpack_security_daily_monthly` for Jetpack sites) and not on the feature, I'd use a site check here. I think that's less confusing.

File: client/my-sites/site-settings/analytics/form-google-analytics.jsx (hunk 10 above)
Comment (mmtr) [reply client/my-sites/site-settings/analytics/form-google-analytics.jsx]: > We could change it to an Analytics eligibility check.

👍

File: client/my-sites/marketing/traffic/index.js (hunk 8 above)
Comment (allilevine) [reply client/my-sites/marketing/traffic/index.js]: @mmtr I've removed this change from this PR in favor of investigating removing these from Atomic further. Follow-up issues:
- https://github.com/Automattic/wp-calypso/issues/53507
- https://github.com/Automattic/wp-calypso/issues/53508

File: client/my-sites/site-settings/analytics/form-google-analytics-simple.jsx (hunk 9 above)
Comment (allilevine) [reply client/my-sites/site-settings/analytics/form-google-analytics-simple.jsx]: Thanks, I've changed to checking for a WPCOM site with a free plan here. Otherwise `findFirstSimilarPlanKey()` returns a Jetpack plan. 

For all other WPCOM plans we're checking the current plan duration to determine which slug to use.

File: client/my-sites/site-settings/analytics/form-google-analytics.jsx (hunk 10 above)
Comment (allilevine) [reply client/my-sites/site-settings/analytics/form-google-analytics.jsx]: Changed here: https://github.com/Automattic/wp-calypso/pull/53196/commits/1cf6ee4b7abc92aeaa02d91ca239f8992bf10e1a

File: client/my-sites/site-settings/analytics/form-google-analytics.jsx [hunk 12]
```diff
@@ -88,8 +90,9 @@ export const GoogleAnalyticsForm = ( props ) => {
 		placeholderText,
 		recordSupportLinkClick,
 		setDisplayForm,
+		isFreeWPCOM,
 	};
-	if ( props.siteIsJetpack ) {
+	if ( props.siteIsJetpack && isGoogleAnalyticsEligible ) {
```
Comment (mmtr) [inline client/my-sites/site-settings/analytics/form-google-analytics.jsx:95]: I think `isGoogleAnalyticsEligible` returns `false` for Jetpack Free sites and that causes the regression I noted.

File: client/my-sites/site-settings/seo-settings/form.jsx [hunk 13]
```diff
@@ -306,23 +308,25 @@ export class SeoForm extends React.Component {
...
-					),
-					feature: FEATURE_ADVANCED_SEO,
-					plan:
-						selectedSite.plan &&
-						findFirstSimilarPlanKey( selectedSite.plan.product_slug, {
-							type: TYPE_BUSINESS,
-						} ),
-			  };
+		const upsellProps =
+			siteIsJetpack && ! isFreeWPCOM
```
Comment (mmtr) [inline client/my-sites/site-settings/seo-settings/form.jsx]: Non-blocking: In the future, Atomic sites could support Personal and Premium plans, which are not eligible for the SEO feature. Would it be more robust to check `! isAtomic` here to avoid potential issues?

**Review by mmtr — COMMENTED** [review]
Tested this on a Simple Free site, Simple Business site, Atomic Free site, Atomic Business site, and Jetpack Free site. They all worked great except the Jetpack Free site, which has this regression:

Before | After
--- | ---
Screen Shot 2021-06-09 at 11 54 03 | Screen Shot 2021-06-09 at 11 54 34

- Copy of the nudge has changed from `Connect your site to Google Analytics` to `Connect your site to Google Analytics in seconds with the Premium plan` .
- URL has changed from `/checkout/:site/jetpack_security_daily_monthly` to `/plans/:site?feature=google-analytics&plan=jetpack_premium`

File: client/my-sites/site-settings/utils.ts [hunk 14]
```diff
@@ -13,9 +20,48 @@ type Site = {
...
+}
+
+export function hasSiteAnalyticsFeature(
+	site: Site,
+	state: string,
+	siteId: string
+): boolean | undefined {
+	if ( state && siteId && isFreeWPCOMSite( site, state, siteId ) ) {
+		return false;
+	}
```
Comment (mmtr) [inline client/my-sites/site-settings/utils.ts]: Trying to understand why is this needed, it seems that this handles an underlying issue where the plan for Atomic Free sites is set incorrectly as `jetpack_free`, right?

Screen Shot 2021-06-09 at 13 10 06

Would it be possible to fix the root issue in WP.com, so the proper plan is returned? Maybe after doing that we could remove most of these workarounds?

```diff
Index: wp-content/admin-plugins/wpcom-billing/class.wpcom-store-api.php
===================================================================
--- wp-content/admin-plugins/wpcom-billing/class.wpcom-store-api.php    (revision 226908)
+++ wp-content/admin-plugins/wpcom-billing/class.wpcom-store-api.php    (working copy)
@@ -443,7 +443,7 @@
                                $billing_period = 'Biyearly';
                        }
                } else {
-                       $product_id = is_jetpack_site( $blog_id ) ? JETPACK_FREE : WPCOM_FREE_PRODUCT;
+                       $product_id = is_jetpack_site( $blog_id ) && ! is_blog_atomic( get_blog_details( $blog_id ) ) ? JETPACK_FREE : WPCOM_FREE_PRODUCT;
                        $product = WPCOM_Store::get_product( $product_id );
                        $subscription_is_expired = false;
                        $user_is_owner = false;
```

**Comment by allilevine** [comment]
> Tested this on a Simple Free site, Simple Business site, Atomic Free site, Atomic Business site, and Jetpack Free site. They all worked great except the Jetpack Free site, which has this regression:

Thanks for catching that! I forgot that was why I couldn't use `isGoogleAnalyticsEligible` for which form to show. Fixed here: https://github.com/Automattic/wp-calypso/pull/53196/commits/69530633390ae28bd73864fc4d486844661f2423

File: client/my-sites/site-settings/seo-settings/form.jsx (hunk 13 above)
Comment (allilevine) [reply client/my-sites/site-settings/seo-settings/form.jsx]: That's a good idea, changed here: https://github.com/Automattic/wp-calypso/pull/53196/commits/69530633390ae28bd73864fc4d486844661f2423

File: client/my-sites/site-settings/utils.ts (hunk 14 above)
Comment (allilevine) [reply client/my-sites/site-settings/utils.ts]: > Trying to understand why is this needed, it seems that this handles an underlying issue where the plan for Atomic Free sites is set incorrectly as `jetpack_free`, right?

That's correct, and the issue was discussed here: pd2C1Z-Q-p2

> Would it be possible to fix the root issue in WP.com, so the proper plan is returned? Maybe after doing that we could remove most of these workarounds?

That would be awesome! My understanding is that it's a bigger task to make that change and check that it doesn't break anything and that all of the feature checks continue to work. This marketing settings fix is on our list of issues blocking the free Atomic work, so we're looking for a short-term UI workaround.

**Review by mmtr — APPROVED** [review]

File: client/my-sites/site-settings/seo-settings/form.jsx [hunk 15]
```diff
@@ -479,15 +485,15 @@ export class SeoForm extends React.Component {
 }
 
 const mapStateToProps = ( state ) => {
-	const selectedSite = getSelectedSite( state );
+	const site = getSelectedSite( state );
```
Comment (pablinos) [inline client/my-sites/site-settings/seo-settings/form.jsx]: Is this renamed to make it more concise?

File: client/my-sites/site-settings/utils.ts [hunk 16]
```diff
@@ -13,9 +20,48 @@ type Site = {
...
-export function hasSiteAnalyticsFeature( site: Site ): boolean | undefined {
+/**
+ * Returns true if the site is on a free plan and a WPCOM site (Simple or Atomic).
+ *
+ * @param site The site to check.
+ * @param state Global state tree.
+ * @param siteId Site ID to check.
+ * @returns bool True if the site is on a free pln and a WPCOM site, false otherwise.
+ */
+export function isFreeWPCOMSite( site: Site, state: string, siteId: string ): boolean | null {
```
Comment (pablinos) [inline client/my-sites/site-settings/utils.ts]: Now this is using state, it's essentially a selector. Should we move these helpers to live with the other selectors?

**Review by pablinos — COMMENTED** [review]
Looks good! Just a couple of queries, but it tests ok and shows right nudges.

I notice the nudge talks about a premium plan, but then that's not available when you click through. I think that's something we'll have to live with for now until we have all plans available on Atomic.

**Comment by allilevine** [comment]
> I notice the nudge talks about a premium plan, but then that's not available when you click through. I think that's something we'll have to live with for now until we have all plans available on Atomic.

Yeah, I've opened an issue: https://github.com/Automattic/wp-calypso/issues/53515

File: client/my-sites/site-settings/seo-settings/form.jsx (hunk 15 above)
Comment (allilevine) [reply client/my-sites/site-settings/seo-settings/form.jsx]: Mostly because it was annoying me that it wasn't consistent with the other props. 😅 Should I revert it to keep the changes down?

File: client/my-sites/site-settings/utils.ts (hunk 16 above)
Comment (allilevine) [reply client/my-sites/site-settings/utils.ts]: I moved / converted them to selectors: https://github.com/Automattic/wp-calypso/pull/53196/commits/0e63e216afb7d078af1935ed40c02364ae1140b7

I'm getting this warning though: "Do not pass complex objects as arguments for a memoized selector". Maybe `site` is too complex. 🤔 

I should probably also add selector tests to replace the util tests I deleted.

File: client/lib/site/utils.js (hunk 11 above)
Comment (pablinos) [reply client/lib/site/utils.js]: Not sure what happened here, this looks like from a review I started on a previous version!

It's the same point I've made below, but it's not as important as that makes it appear - I can see pros and cons for leaving these functions here as well as moving it.

File: client/my-sites/site-settings/seo-settings/form.jsx (hunk 15 above)
Comment (pablinos) [reply client/my-sites/site-settings/seo-settings/form.jsx]: I'm not sure. Consistency is a valid reason to rename it too! It gets renamed to `selectedSite` again later on. Would we want to change that too?

File: client/my-sites/site-settings/analytics/form-google-analytics.jsx [hunk 17]
```diff
@@ -88,8 +90,9 @@ export const GoogleAnalyticsForm = ( props ) => {
 		placeholderText,
 		recordSupportLinkClick,
 		setDisplayForm,
+		isFreeWPCOM,
 	};
-	if ( props.siteIsJetpack ) {
+	if ( props.siteIsJetpack && ! isFreeWPCOM ) {
```
Comment (pablinos) [inline client/my-sites/site-settings/analytics/form-google-analytics.jsx]: I wonder whether in a future change we should adapt the `hasSiteAnalyticsFeature` selector to return something like `wpcom` and `jetpack`, so that we can keep this logic contained in the selector. 

Eventually that logic could also be pushed server-side, extending the plan features work @retrofox has been doing.

File: client/my-sites/site-settings/seo-settings/form.jsx [hunk 18]
```diff
@@ -306,23 +311,25 @@ export class SeoForm extends React.Component {
...
+						feature: FEATURE_SEO_PREVIEW_TOOLS,
+						href: `/checkout/${ slug }/${ PRODUCT_UPSELLS_BY_FEATURE[ FEATURE_ADVANCED_SEO ] }`,
+				  }
+				: {
+						title: translate(
+							'Boost your search engine ranking with the powerful SEO tools in the Business plan'
+						),
+						feature: FEATURE_ADVANCED_SEO,
+						plan: isFreeWPCOM
+							? PLAN_BUSINESS
```
Comment (pablinos) [inline client/my-sites/site-settings/seo-settings/form.jsx]: Is this because Atomic Free sites will be on the `jetpack_free` plan which `findFirstSimilarPlanKey` will fail for? If so, should this check be `isAtomic` to prevent us from changing the code run for Simple Free sites?

File: client/my-sites/site-settings/seo-settings/form.jsx [hunk 19]
```diff
@@ -306,23 +311,25 @@ export class SeoForm extends React.Component {
...
-					),
-					feature: FEATURE_ADVANCED_SEO,
-					plan:
-						selectedSite.plan &&
-						findFirstSimilarPlanKey( selectedSite.plan.product_slug, {
-							type: TYPE_BUSINESS,
-						} ),
-			  };
+		const upsellProps =
+			siteIsJetpack && ! isAtomic
```
Comment (pablinos) [inline client/my-sites/site-settings/seo-settings/form.jsx:305]: Similarly to the analytics checks, it feels like this logic shouldn't be here. We should probably have the plan to promote, current plan, and site type all sent from the server with the other feature information, but that's definitely not something to tackle in this PR.

Maybe we should decide if that's a good idea and raise an issue.

File: client/my-sites/site-settings/seo-settings/form.jsx [hunk 20]
```diff
@@ -479,15 +486,15 @@ export class SeoForm extends React.Component {
...
+	const site = getSelectedSite( state );
 	const siteId = getSelectedSiteId( state );
 	const siteIsJetpack = isJetpackSite( state, siteId );
 	// SEO Tools are available with Business plan on WordPress.com, and
 	// will soon be available on all Jetpack sites, so we're checking
 	// the availability of the module.
 	const isAdvancedSeoEligible =
-		selectedSite.plan &&
-		hasSiteSeoFeature( selectedSite ) &&
+		site.plan &&
```
Comment (pablinos) [inline client/my-sites/site-settings/seo-settings/form.jsx]: Maybe it's good to short circuit the check early, have we implicitly got this check in `hasSiteSeoFeature`?

**Review by pablinos — COMMENTED** [review]
This is looking great, thanks for doing all that refactoring!

Just a few minor comments and thoughts, but this is pretty much there I reckon.

File: client/my-sites/site-settings/seo-settings/form.jsx (hunk 20 above)
Comment (allilevine) [reply client/my-sites/site-settings/seo-settings/form.jsx]: Yeah I think we do, I removed that check here: https://github.com/Automattic/wp-calypso/pull/53196/commits/6c722ae335fe3176cbfe6cd5c57698efe9b0f536

I also reverted the `selectedSite` -> `site` change since we're no longer using `site` with the selectors.

File: client/my-sites/site-settings/seo-settings/form.jsx (hunk 18 above)
Comment (allilevine) [reply client/my-sites/site-settings/seo-settings/form.jsx]: Yes. Maybe that needs to be clearer.

I added `isAtomic`, so now it checks `isFreeWPCOM && isAtomic`. I think in general on Atomic plans we still want to check what term their plan is for, e.g. 2-year, 1-year, monthly to find the right plan slug.

File: client/my-sites/site-settings/analytics/form-google-analytics.jsx (hunk 17 above)
Comment (allilevine) [reply client/my-sites/site-settings/analytics/form-google-analytics.jsx]: That would definitely be an improvement. I've also wondered if we should continue to have two different Google Analytics form components.

File: client/my-sites/site-settings/seo-settings/form.jsx (hunk 19 above)
Comment (allilevine) [reply client/my-sites/site-settings/seo-settings/form.jsx:305]: I opened an issue to track it: https://github.com/Automattic/wp-calypso/issues/53793

File: client/state/selectors/has-site-analytics-feature.js [hunk 21]
```diff
@@ -0,0 +1,30 @@
...
+/**
+ * Returns true if the site has the analytics feature, false if the site is WPCOM
+ * and on a free plan or doesn't have this feature.
+ *
+ * @param {object} state Global state tree.
+ * @param {object} site The site to check.
+ * @param {number} siteId The id of the site to check.
+ * @returns {boolean} True if the site has the analytics feature, false otherwise.
+ */
+export default ( state, site, siteId ) => {
```
Comment (allilevine) [inline client/state/selectors/has-site-analytics-feature.js]: This is messy but I wanted to use the data we already have, rather than re-creating the `site` object in the selector. Let me know if you have any suggestions for improving it.

**Review by retrofox — COMMENTED** [review]
LGTM. I've tested the approach and it works as expected. Also, we talked about a possible follow-up task where we may want to make focus on the site features instead of the site type and plan but it's something that we can iterate later.

Thanks for taking over this tough issue. 👏

**Review by retrofox — APPROVED** [review]
Forgot to approve it. ✅

File: client/state/selectors/has-site-analytics-feature.js (hunk 21 above)
Comment (pablinos) [reply client/state/selectors/has-site-analytics-feature.js]: I know we've talked a little about this, but I've just been doing a bit more thinking, and I'm leaning on sticking to using just the `siteId`.

From what I can see of the other selectors we're only ever using the site's ID, so this would make it consistent and I notice that we're using `getSelectedSite` only to pass it to these selectors, so we could get the site object when we need it and default the site ID parameter to the currently selected site - `siteId = getSelectedSiteId( state )` - which seems to be a common pattern.

Comment (allilevine) [reply client/state/selectors/has-site-analytics-feature.js]: Refactored to use just `siteId` here: https://github.com/Automattic/wp-calypso/pull/53196/commits/4d964cf3942b6bde035d85093b19ee22403dbb6f

I had to the remove tests for no data passed in since `getSelectedSiteId( state )` requires `state`.

File: client/layout/index.jsx [hunk 22]
```diff
@@ -295,6 +296,7 @@ class Layout extends Component {
 				<QuerySites primaryAndRecent={ ! config.isEnabled( 'jetpack-cloud' ) } />
 				{ this.props.shouldQueryAllSites && <QuerySites allSites /> }
 				<QueryPreferences />
+				<QuerySiteFeatures siteId={ this.props.siteId } />
```
Comment (pablinos) [inline client/layout/index.jsx:287]: I'm not sure where it's triggered (perhaps as part of QuerySites) but the features information is being returned under the `plan` section of the data that comes back from the `/sites/<SITE ID>` API call. Could we save a request by using that data and only explicitly querying for it if it's unavailable, or we suspect it's stale?

Comment (allilevine) [reply client/layout/index.jsx:287]: I decided to try this out by checking for the features under the site plan data in the selector, and then checking that selector before rendering the `<QuerySiteFeatures>` component. If we already have the features from either /sites or /features, then we shouldn't fetch the features. I also prevented fetching if we were already fetching /site or /sites.

What kept happening was that state would update with the features from /sites, but then update without them afterwards. And then of course we'd have to fetch the features again.

The cause seems to be that while the `v1.1/sites/<SITE ID>` API response does include features in the plan section, the `v1.2/me/sites` API response we fetch afterwards on line 297 (`<QuerySites allSites />`) does not include features. That replaces the site data so that features are removed from state. 

Should we update the `v1.2/me/sites` endpoint to include features? Or is there another way of working around this that I missed?

Comment (retrofox) [reply client/layout/index.jsx:287]: Also, for some reason sometimes, the `plan` section is not populated in the endpoint response. I tested with retrosimplepremium01.wordpress.com site.

File: client/my-sites/domains/domain-management/list/index.jsx [hunk 23]
```diff
@@ -472,7 +471,6 @@ export class List extends React.Component {
 
 		return [
 			<QuerySitePurchases key="query-purchases" siteId={ selectedSite.ID } />,
-			<QuerySiteFeatures key="query-features" siteId={ selectedSite.ID } />,
```
Comment (retrofox) [inline client/my-sites/domains/domain-management/list/index.jsx:475]: nice

**Review by retrofox — APPROVED** [review]
Tested again, and it LGTM.
Confirmed that the app hits the features endpoint properly. Also, confirmed the different cases described in the PR description  👍
