### PR TITLE
E2E: fix permanently failing tests in WPCOM/Gutenberg.

### LINKED ISSUE #61272: Flaky E2E: Add Heading
### Spec file

specs/editor/editor__post-basic-flow.ts

### TeamCity ID

7429305

### Logs

Link: https://teamcity.a8c.com/buildConfiguration/calypso_WPComTests_gutenberg_Playwright_desktop/7429305?showRootCauses=false&expandBuildChangesSection=true&expandBuildTestsSection=true

Logs:
```
frame.click: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "div[aria-label="Heading"]"
============================================================
at GutenbergEditorPage.addPattern (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts:329:15)
    at Object.<anonymous> (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/editor/editor__post-basic-flow.ts:73:4)
```

### LINKED ISSUE #61273: Flaky E2E: Set page visibility to Private
### Spec file

specs/editor/editor__privacy-private.ts

### TeamCity ID

7435456

### Logs

Link: https://teamcity.a8c.com/buildConfiguration/calypso_WPComTests_gutenberg_Playwright_mobile/7435456?showRootCauses=false&expandBuildTestsSection=true&expandBuildChangesSection=true

Logs:
```
frame.click: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".edit-post-post-visibility__toggle"
  selector resolved to visible <button type="button" aria-expanded="true" class="compon…>Public</button>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #1
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #2
  waiting 20ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #3
  waiting 100ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #4
  waiting 100ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #5
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #6
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #7
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #8
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #9
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #10
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #11
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #12
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #13
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #14
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #15
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #16
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #17
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #18
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #19
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #20
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #21
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #22
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #23
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #24
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #25
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #26
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #27
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #28
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #29
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #30
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #31
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #32
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #33
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #34
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #35
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #36
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #37
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #38
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #39
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #40
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #41
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #42
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #43
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #44
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #45
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #46
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #47
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #48
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #49
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #50
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #51
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #52
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #53
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #54
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #55
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #56
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #57
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #58
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #59
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <div role="document" class="components-modal__content…>…</div> from <div class="components-modal__screen-overlay fa-fa-f-…>…</div> subtree intercepts pointer events
retrying click action, attempt #60
  waiting 500ms
============================================================
at EditorSettingsSidebarComponent.setVisibility (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-settings-sidebar-component.ts:140:20)
    at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/editor/shared/privacy-testing.ts:70:5)
```

### PR DESCRIPTION
**Pull request by worldomonation**
#### Changes proposed in this Pull Request

This PR fixes permanent failing tests in WPCOM/Gutenberg E2E tests.

Permanent failures:
- Editor: Privacy (updated modal) (https://github.com/WordPress/gutenberg/pull/37602)
- Editor: Basic Post Flow (new pattern) 
- Jetpack: Grow (Subscription Form) (https://github.com/Automattic/jetpack/pull/22694)

#### Testing instructions

- [x] Ensure these pass:
  - [x] WPCOM desktop
  - [x] WPCOM mobile
  - [x] Calypso desktop
  - [x] Calypso mobile

Related to #

### CODE REVIEW

File: test/e2e/specs/editor/editor__post-basic-flow.ts [hunk 1]
```diff
@@ -44,32 +43,19 @@ describe( DataHelper.createSuiteTitle( 'Editor: Basic Post Flow' ), function ()
...
-		it( 'Add image block', async function () {
-			blockHandle = await gutenbergEditorPage.addBlock(
-				ImageBlock.blockName,
-				ImageBlock.blockEditorSelector
-			);
-		} );
-
-		it( 'Remove image block', async function () {
-			await gutenbergEditorPage.removeBlock( blockHandle );
-		} );
```
Comment (worldomonation) [inline test/e2e/specs/editor/editor__post-basic-flow.ts:66]: This is semi-related, in that we already have Media blocks being tested in its own suite, so this felt redundant.

File: packages/calypso-e2e/src/lib/components/editor-settings-sidebar-component.ts [hunk 2]
```diff
@@ -120,13 +120,13 @@ export class EditorSettingsSidebarComponent {
...
-		// Private posts display a dialog that when accepted will publish the post.
-		// For non-Private posts, this handler has no effect.
-		await Promise.all( [
-			this.page.once( 'dialog', ( dialog ) => dialog.accept() ),
-			this.frame.click( selectors.visibilityOption( visibility ) ),
-		] );
+		if ( visibility === 'Private' ) {
+			await this.frame.click( selectors.visibilityOption( visibility ) );
+			// @TODO: eventually refactor this out to a ConfirmationDialogComponent.
+			await this.frame.click( `div[role="dialog"] button:has-text("OK")` );
```
Comment (worldomonation) [inline packages/calypso-e2e/src/lib/components/editor-settings-sidebar-component.ts:127]: I've chosen to implement this as a straight call to click a selector for now.

**Review by dpasque — APPROVED** [review]
Code changes look good, once the WPCOM builds pass, we should be good to merge!

**Comment by dpasque** [comment]
I've retriggered the WPCOM tests on TC. 👍

**Comment by worldomonation** [comment]
Now the Editor Privacy: Password test is failing...Investigating.

**Comment by worldomonation** [comment]
Awesome, all tests passed!
