### PR TITLE
`DesignPickerDesignTitle`: Use `ThemeTierBadge` on the badge if the `themes/tiers` flag is enabled

### LINKED ISSUE #86526: Theme Tiers: DP doesn't use new badges on theme details
Theme Tiers should use the new \<ThemeTierBadge> badges, not the \<ThemeTypeBadge> if the themes/tiers flag is enabled.

## Repro steps

1. Start a new site on the free plan and work through to the design picker
2. Add flags=themes/tiers to the url and reload
3. On the theme grid the badges are the new ones
4. Click on a premium theme like Annalee
5. Note that the Premium badge appears at the top of the screen rather than the tier badge. It says "Let your site stand out from the crowd...." when hovering.

Screenshot 2024-01-17 at 09 47 28

### PR DESCRIPTION
**Pull request by xavier-lc**
Fixes #86526

## Proposed Changes

On the design picker, show the badge with the new `ThemeTierBadge` component if the `themes/tiers` flag is enabled.

## Testing Instructions

1. Open the live preview and go to `/start`
2. Start a new site on the free plan and work through to the design picker
3. Add `?flags=themes/tiers` to the URL and reload
4. On the theme grid the badges are the new ones
5. Click on a premium theme like Annalee
6. Check that the badge that appears over the theme title says **Upgrade**
7. Go back to the theme list
8. Go to the "Twenty Twenty-Four" theme
9. Click on a style different from the default one, check that this action triggers the appearance of the **Upgrade** badge

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/design-picker-design-title.tsx [hunk 1]
```diff
@@ -30,10 +44,20 @@ const DesignPickerDesignTitle: FC< Props > = ( { designTitle, selectedDesign } )
...
 	);
 
-	const bundleSettings = useBundleSettingsByTheme( selectedDesign.slug );
-
 	let badge: React.ReactNode = null;
-	if ( selectedDesign.software_sets && selectedDesign.software_sets.length > 0 ) {
+	if ( isEnabled( 'themes/tiers' ) ) {
+		const isDefaultVariation = isDefaultGlobalStylesVariationSlug( selectedStyleVariation?.slug );
+		const isLockedStyleVariation =
+			( ! selectedDesign.is_premium && shouldLimitGlobalStyles && ! isDefaultVariation ) ?? false;
```
Comment (xavier-lc) [inline client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/design-picker-design-title.tsx]: I copied this from:
https://github.com/Automattic/wp-calypso/blob/483892a5f840debe021b0395d732f8f0a935a713/packages/design-picker/src/components/unified-design-picker.tsx#L176-L177 
but there's a slightly different definition that doesn't check whether the theme is premium:
https://github.com/Automattic/wp-calypso/blob/4527c48fb086a38e17129da2125866914e2217b7/client/components/theme/index.jsx#L317-L319

@mmtr, since both of them where added by you, could you tell me the difference?

Thanks!

File: client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/style.scss [hunk 2]
```diff
@@ -578,6 +578,13 @@ $design-button-primary-color: rgb(17, 122, 201);
 					}
 				}
 			}
+
+		}
+
+		.design-picker-design-title__theme-tier-badge {
+			&:empty {
+				display: none;
+			}
```
Comment (xavier-lc) [inline client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/style.scss]: I'm using the `:empty` pseudo-selector because the `ThemeTierBadge` always returns a `div`, even if the badge is `null`. I thought it would be easier to hide this with styling than risking breaking designs elsewhere.

File: client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/design-picker-design-title.tsx (hunk 1 above)
Comment (mmtr) [reply client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/design-picker-design-title.tsx]: Nice finding!

Styles variation of premium styles shouldn't trigger any Limited GS warning/upsell because to use a premium theme you need a Explorer plan which already gives you access to the GS style variations.

In the Design Picker (`unified-design-picker.tsx`), we check whether the theme is premium to ensure that users previewing a style variation of a premium theme still see the premium theme upsell instead of the GS upsell:

Previewing a style variation of a free theme in the DP | Previewing a style variation of a premium theme in the DP
--- | ---
GS upsellScreenshot 2024-01-18 at 13 38 01 | Premium theme upsellScreenshot 2024-01-18 at 13 38 24

The fact that we're not doing the same in the Theme Showcase (`components/theme/index.jsx`) is causing a bug so we always show the GS upsell regardless of whether the theme is premium or free:

Previewing a style variation of a free theme in the TS | Previewing a style variation of a premium theme in the TS
--- | ---
GS upsellScreenshot 2024-01-18 at 13 43 10 | GS upsellScreenshot 2024-01-18 at 13 43 03

We should show the premium theme upsell in the TS when previewing a style variation of a premium theme.

File: client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/design-picker-design-title.tsx [hunk 3]
```diff
@@ -30,10 +44,20 @@ const DesignPickerDesignTitle: FC< Props > = ( { designTitle, selectedDesign } )
 		)
 	);
 
-	const bundleSettings = useBundleSettingsByTheme( selectedDesign.slug );
-
 	let badge: React.ReactNode = null;
-	if ( selectedDesign.software_sets && selectedDesign.software_sets.length > 0 ) {
```
Comment (mmtr) [inline client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/design-picker-design-title.tsx:36]: I think we need to keep the `software_sets` check at the beginning. Otherwise the Partner themes will show a badge with a weird layout:

Before | After
--- | ---
Screenshot 2024-01-18 at 15 24 01 | Screenshot 2024-01-18 at 15 24 06

File: client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/design-picker-design-title.tsx (hunk 1 above)
Comment (xavier-lc) [reply client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/design-picker-design-title.tsx]: Ok, so the code in [wp-calypso/client/components/theme/index.jsx](https://github.com/Automattic/wp-calypso/blob/4527c48fb086a38e17129da2125866914e2217b7/client/components/theme/index.jsx#L317-L319) needs to be fixed, right? I can do that on a followup PR.

File: client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/design-picker-design-title.tsx [hunk 4]
```diff
@@ -30,10 +44,20 @@ const DesignPickerDesignTitle: FC< Props > = ( { designTitle, selectedDesign } )
...
+	if ( isEnabled( 'themes/tiers' ) ) {
+		const isDefaultVariation = isDefaultGlobalStylesVariationSlug( selectedStyleVariation?.slug );
+		const isLockedStyleVariation =
+			( ! selectedDesign.is_premium && shouldLimitGlobalStyles && ! isDefaultVariation ) ?? false;
+
+		badge = (
+			<ThemeTierBadge
+				className="design-picker-design-title__theme-tier-badge"
+				isLockedStyleVariation={ isLockedStyleVariation }
```
Comment (mmtr) [inline client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/design-picker-design-title.tsx]: I don't think we need the `isLockedStyleVariation` prop. As noted in p1705588567980119-slack-C04DZ8M0GHW, the locked style variations should be highlighted with a different section. The upgrade badge that is displayed above the theme name should be only visible for premium themes.

File: client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/design-picker-design-title.tsx (hunk 3 above)
Comment (xavier-lc) [reply client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/design-picker-design-title.tsx:36]: I've added spacing on https://github.com/Automattic/wp-calypso/pull/86582/commits/9a5973a6b81e2541cbc7f20688b4c3737d65383e. I think that the badge shown on this page should be the same(s) than on the listing.

File: client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/design-picker-design-title.tsx (hunk 4 above)
Comment (xavier-lc) [reply client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/design-picker-design-title.tsx]: If you try to **Continue** after selecting a style other than the default one, you get the upgrade modal:

image 

So I think it makes sense to have the upgrade badge, don't you think?

Comment (mmtr) [reply client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/design-picker-design-title.tsx]: > So I think it makes sense to have the upgrade badge, don't you think?

As long as it is in a separate section as it used to be (see the badge next to "Style Variation":

Screenshot 2024-01-18 at 15 33 44

Otherwise it's not clear that only the default style variation is free:

Screenshot 2024-01-18 at 15 34 05

Comment (mmtr) [reply client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/design-picker-design-title.tsx]: So for now, I think we can hide the badge for free themes (even if a locked style variation is selected) and I'll work in bringing back the separate section.

Comment (xavier-lc) [reply client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/design-picker-design-title.tsx]: Set it to `false` on https://github.com/Automattic/wp-calypso/pull/86582/commits/d95f058f2e540bd82235158afb9358dbdd62b65d

File: client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/style.scss [hunk 5]
```diff
@@ -578,6 +578,15 @@ $design-button-primary-color: rgb(17, 122, 201);
...
 			}
+
+		}
+
+		.design-picker-design-title__theme-tier-badge {
+			gap: 8px;
+
+			&:empty {
+				display: none;
+			}
```
Comment (mmtr) [inline client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/style.scss:589]: What do you think about adding a comment explaining why we hide it? Although I think that the component returning an empty `div` is actually a bug and we should fix that instead.

File: client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/design-picker-design-title.tsx [hunk 6]
```diff
@@ -1,21 +1,26 @@
...
-import type { Design } from '@automattic/design-picker';
 import type { FC } from 'react';
 
 import './design-picker-design-title.scss';
 
 type Props = {
 	designTitle: string;
 	selectedDesign: Design;
+	selectedStyleVariation?: StyleVariation;
+	shouldLimitGlobalStyles: boolean;
```
Comment (mmtr) [inline client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/design-picker-design-title.tsx]: These two props are no longer needed, right?

**Review by mmtr — COMMENTED** [review]
Nice! I wonder if we should place the tooltip always below the container, since it's always sticky to the top, but I guess we can discuss that in a follow-up.

I observed though that we display a link inside the tooltip that abruptly exists the Design Picker flow, so we should probably hide it:

Screenshot 2024-01-18 at 16 40 49

Note how there are no links in the grid:

Screenshot 2024-01-18 at 16 40 44

File: client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/style.scss (hunk 5 above)
Comment (xavier-lc) [reply client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/style.scss:589]: > I think that the component returning an empty div is actually a bug and we should fix that instead.

Seems reasonable, I can try to address that on a separate PR.

**Review by mmtr — APPROVED** [review]

File: client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/design-picker-design-title.tsx (hunk 1 above)
Comment (xavier-lc) [reply client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/design-picker-design-title.tsx]: Fix PR: https://github.com/Automattic/wp-calypso/pull/86654

File: client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/style.scss (hunk 5 above)
Comment (xavier-lc) [reply client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/style.scss:589]: Fix PR: https://github.com/Automattic/wp-calypso/pull/86659
