### PR TITLE
User Email: Fixes #685 by disabeling and showing the new email address

### LINKED ISSUE #685: Me: make changing email addresses more visually explicit
Currently the process for changing your WordPress.com account email address looks like this:

Default:
screen shot 2015-11-24 at 4 11 13 pm

Changed:
screen shot 2015-11-24 at 4 12 14 pm

I find that to be very confusing. Until I read the fine print I assumed my change did not go through. Instead we should do this:

screen shot 2015-11-24 at 4 14 39 pm

We should display the new email address in the field, but disable the field. The user shouldn't be able to change the email again until they verify the new address. If they want to go back to the original address they can click the cancel link.

Also note that the notice did not have a prop for 'is-info' so it is missing styling. The existing class seems like it was added via ClassNames incorrectly as 'info'.

cc @ebinnion @alternatekev @MichaelArestad

### PR DESCRIPTION
**Pull request by enejb**
Fixes #685
Updated the email form field to be disabled and show the new email address in the notice. 

When the user has the email in the pending state we now disabled the email address field until the user click cancel or confirms the new email address.

Before:
screen shot 2015-12-09 at 13 22 14

After:
screen shot 2015-12-09 at 13 24 21

*To test*

Visit http://calypso.localhost:3000/me/account 
Change your email address notice that the new email address will show up in the text field and the text field will be disabled.

### CODE REVIEW

**Comment by rickybanister** [comment]
This seems like it's correct—instead of obfuscating the screenshot, could you just edit the actual address in the inspector to `example@wordpress.com`? It's hard to tell that the field is disabled (I trust you obviously).

**Comment by enejb** [comment]
@rickybanister good idea I update the screenshots.

**Comment by rickybanister** [comment]
Looks perfect design-wise.

File: client/me/account/index.jsx [hunk 1]
```diff
@@ -346,11 +360,11 @@ module.exports = React.createClass( {
 				<FormFieldset>
 					<FormLabel htmlFor="email">{ this.translate( 'Email Address' ) }</FormLabel>
 					<FormTextInput
-						disabled={ this.getDisabledState() }
+						disabled={ this.getDisabledState() || this.hasPendingEmailChange() }
 						id="email"
 						name="email"
 						onFocus={ this.recordFocusEvent( 'Email Address Field' ) }
-						valueLink={ this.valueLink( 'user_email' ) } />
+						valueLink={ this.renderEmailValueLink() } />
```
Comment (ebinnion) [inline client/me/account/index.jsx]: The only issue I have with using `valueLink` for `new_user_email` is that since we don't allow the user to modify `new_user_email` directly, we don't really need two-way binding.

An alternative, while more verbose, would be:

```
<FormTextInput
	disabled={ this.getDisabledState() || this.hasPendingEmailChange() }
	id="email"
	name="email"
	onFocus={ this.recordFocusEvent( 'Email Address Field' ) }
	value={ this.hasPendingEmailChange() ? this.props.userSettings.getSetting( 'new_user_email' ) : null }
	valueLink={ this.hasPendingEmailChange() ? null : this.valueLink( 'user_email' ) } />
```

I just tested that solution and it seemed to work. I don't feel super strongly about this though, so  ¯\_(ツ)_/¯

File: client/me/account/index.jsx [hunk 2]
```diff
@@ -202,8 +198,16 @@ module.exports = React.createClass( {
...
+			startDate = this.moment( {
+				year: today.year(),
+				month: 11,
+				day: 1
+			} ),
+			endDate = this.moment( {
+				year: today.year(),
+				month: 0,
+				day: 4
+			} );
```
Comment (ebinnion) [inline client/me/account/index.jsx]: I think every change from line `210` and above in this file is due to your auto-formatter. I don't have an issue with that, but could we break it into a separate commit that way the change needed for the issue is more clear?

**Comment by ebinnion** [comment]
This worked as described for me. I left a couple of minor comments. After addressing, :shipit:

**Comment by enejb** [comment]
@ebinnion I update the `renderEmailValueLink` method to not return the valueLink of `new_user_email`

And also split the commits so that they are easier to review.

**Comment by ebinnion** [comment]
LGTM
