### PR TITLE
Woo-Connect Insights: use currency codes in list and add tests (and fix isWoo bug)

### LINKED ISSUE #16033: Woo-Connect Insights: Use Currency Code in Lists
Default $ currency formatting being shown in the top-* lists. This needs to be updated to use the 3 character code from the responses.

### PR DESCRIPTION
**Pull request by greenafrican**
- ensures that lists use the 3 character currency code from the API response
- renamed constant `type` to `format`
- new tests for a few currencies and missing currency values
- fix odd isWooConnect `isRequired` bug

Fixes #16033

To test:
-ENABLE_FEATURES=woocommerce/extension-stats make run
-browse to /store/stats/orders/day/{ slug } of a site with WooCommerce and Jetpack syncing
-ensure currency correctly formatted in top-* lists at the bottom and on list pages (click top-* list title)

### CODE REVIEW

File: client/extensions/woocommerce/app/store-stats/constants.js [hunk 1]
```diff
@@ -7,35 +7,35 @@ export const sparkWidgetList1 = [
...
 	},
 	{
 		key: 'avg_products_per_order',
 		title: translate( 'Products Per Order' ),
-		type: 'number'
+		format: 'number'
 	},
 	{
 		key: 'coupons',
 		title: translate( 'Coupons Used' ),
```
Comment (a8ci18n) [inline client/extensions/woocommerce/app/store-stats/constants.js]: Hi! I've found a possible matching string that has already been translated **33** times:
`translate( 'Coupons' )` *ES Score: 8*

Help me improve these suggestions: react with :thumbsdown: if the suggestion doesn't make any sense, or with :thumbsup: if it's a particularly good one (even if not implemented).
