### PR TITLE
Fix html invalid markup, propagate react extra props

### LINKED ISSUE #46095: Nav unification - improve Reader sidebar markup
During our most recent exploration it became obvious that the reader sidebar has some markup issues and the use of classes varies compared to our unified sidebar, causing styling issues.

Screenshot 2020-10-01 at 14 22 21

In addition to styling and markup issues, there's an issue with too many items in flyout menus. This issue is also being tracked in https://github.com/Automattic/wp-calypso/issues/46094:

>Flyout menus with a lot of items currently also get cut off. This is an issue with the reader in particular. In wp-admin the same can happen if there are too many items in a menu. It just doesn't surface as reader level submenus are uncommon.
One suggestion from design was to limit the number of items shown in the reader submenu to 5 items.

### PR DESCRIPTION
**Pull request by cpapazoglou**
#### Changes proposed in this Pull Request

* Remove duplicate `ul` wrappers
* Replace all `ul` children with `li` elements
* Propagate ...props further down to the components

#### Testing instructions

* Load Calypso Sites, Reader, Me and make sure nothing has changes UI / UX wise
* Repeat for mobile viewports

Fixes #46095

### CODE REVIEW

File: client/reader/sidebar/index.jsx [hunk 1]
```diff
@@ -153,82 +153,80 @@ export class ReaderSidebar extends React.Component {
 		return (
 			<SidebarMenu>
 				<SidebarHeading>{ translate( 'Streams' ) }</SidebarHeading>
-				<ul>
-					<QueryReaderLists />
-					<QueryReaderTeams />
-
+				<QueryReaderLists />
```
Comment (cpapazoglou) [inline client/reader/sidebar/index.jsx:156]: Just removed the `ul` wrapper. The diff produced is rather unfortunate!

File: client/me/sidebar/index.jsx [hunk 2]
```diff
@@ -128,77 +128,76 @@ class MeSidebar extends React.Component {
 
 					<SidebarMenu>
 						<SidebarHeading>{ translate( 'Profile' ) }</SidebarHeading>
```
Comment (cpapazoglou) [inline client/me/sidebar/index.jsx:130]: Just removed the `ul` wrapper. The diff produced is rather unfortunate!

**Comment by obenland** [comment]
Hiding whitespace changes can help with reviewing this one

image

**Comment by mreishus** [comment]
I'm still seeing `<ul>` as child of `<ul>` in some cases, with nav unification both on and off.




That said, I'm not against merging it as it's an improvement.

**Comment by cpapazoglou** [comment]
Thanks @mreishus for reviewing. Indeed there were far more problems that expected... Hopefully I resolved all invalid `ul` , `li` markup regarding the sidebar.

A rule of thumb is:
- `*SidebarMenu` is a `ul` and should only have `li` children and not `ul` parent
- `SidebarHeading` and `SidebarItem` are `li` and they can only a `ul` parent and not `li` children

Thankfully, adding / removing `ul`, `li` doesn't seem to alter the visual representation / behaviour .

**Comment by marekhrabe** [comment]
I've used `document.querySelectorAll('ul > ul')` which revealed one more. It is in the "Lists" submenu.

Screenshot 2020-11-09 at 16 27 03

**Comment by cpapazoglou** [comment]
> I've used `document.querySelectorAll('ul > ul')` which revealed one more. It is in the "Lists" submenu.
> 
> Screenshot 2020-11-09 at 16 27 03

Interesting I couldn't see the Lists item! I mocked and fixed it d4b6dae! Very good catch and clever way! Thanks!

**Review by marekhrabe — APPROVED** [review]
Looks good in my testing! Thanks for the update. 

I think it's also a good stopping point - if more strangely marked up menus surface, let's fix them separately and ship this huge improvement now :)
