### PR TITLE
Site Settings: Rely dirty checking on comparing persisted/unperstited fields

### LINKED ISSUE #10412: Site Icon: making changes to site settings then adding site icon makes form change potentially lost
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/settings/general/
2. Make some changes to general settings - don't click Save
3. Upload a new site icon
4. Navigate away from form without clicking Save

#### What I expected

Prompt saying there are unsaved changes

#### What happened instead

No prompt - changes are lost

#### Browser / OS version

Chrome OSX

#### Screenshot / Video

loses changes

### PR DESCRIPTION
**Pull request by youknowriad**
closes #10412

Before this setting dirtyFields was imperative on Fields Change,
with this PR, dirtyFields are computed by comparing the settings received as a prop
from the redux state and the component state.

--
This way of dirty checking is more "declarative" (which is preferable IMO), but the drawback here is the need to drop the optimistic redux update. 
If we want to keep this optimistic update absolutely (which I think is not that usefull right now), we would have to add some complexity to the redux store, where we would store the persisted and the edited settings directly on the store. I think this is too much not needed complexity.

**Testing instructions**

Scenario 1:
 1- Navigate to the General settings page
 2- Edit a field (title)
 3- Try to navigate away from the page
 4- You should be prompted with the "changes not saved modal"
 5- Save the form and retry to navigate away
 6- The modal should not show up

Scenario 2:
 1- Navigate to the General settings page
 2- Edit a field (title)
 3- Revert the field to the old value
 4- Try to navigate away from the page
 5- The modal should not show up

Scenario 3:
 1- Navigate to the General settings page
 2- Edit a field (title)
 3- Change the site icon (follow all the steps to change it)
 4- Once the site icon is saved and the "Settings saved" notice show up, try to navigate away from the page
 5- You should be prompted with the "changes not saved modal"

### CODE REVIEW

File: client/my-sites/site-settings/wrap-settings-form.jsx [hunk 1]
```diff
@@ -6,6 +6,7 @@ import { bindActionCreators } from 'redux';
 import { flowRight, omit, keys, pick } from 'lodash';
 import { connect } from 'react-redux';
 import { localize } from 'i18n-calypso';
+import shallowEqual from 'react-pure-render/shallowEqual';
```
Comment (aduth) [inline client/my-sites/site-settings/wrap-settings-form.jsx]: I don't know that we have it tracked anywhere, but we should seek to drop `react-pure-render`. It was once useful for its `PureComponent` component before React implemented its own, but has been effectively deprecated since (["No Maintenance Intended"](https://github.com/gaearon/react-pure-render)).

Instead, we have available either [`react-addons-shallow-compare`](https://github.com/Automattic/wp-calypso/blob/3e8286efdb2b27fb8478522f0b74802fee4bea1b/package.json#L101) or [`_.isEqual`](https://lodash.com/docs/4.17.4#isEqual) (which is a deep equality check, but should be fine if you know the shapes of the objects are shallow anyways).

File: client/my-sites/site-settings/wrap-settings-form.jsx [hunk 2]
```diff
@@ -44,39 +45,55 @@ const wrapSettingsForm = getFormSettings => SettingsForm => {
...
 		}
 
+		updateDirtyFields() {
+			const unpersistedFields = this.props.fields;
+			const persistedFields = getFormSettings( this.props.settings );
+			// Compute the dirty fields by comparing the persisted and not persisted fields
+			const dirtyFields = Object.keys( unpersistedFields )
+				.filter( field => unpersistedFields[ field ] !== persistedFields[ field ] );
+			// Set the new non dirty fields
+			this.props.replaceFields( omit( persistedFields, dirtyFields ) );
```
Comment (aduth) [inline client/my-sites/site-settings/wrap-settings-form.jsx]: Do we want to check first whether there's any difference in the new persisted/non-dirty before calling `replaceFields`? Is that unlikely to occur?

File: client/my-sites/site-settings/wrap-settings-form.jsx [hunk 3]
```diff
@@ -44,39 +45,55 @@ const wrapSettingsForm = getFormSettings => SettingsForm => {
...
+
+			// Update the dirty fields state without updating their values
+			this.props.clearDirtyFields();
```
Comment (aduth) [inline client/my-sites/site-settings/wrap-settings-form.jsx]: Same applies here. Maybe we need an early return in the function if nothing has changed?

File: client/my-sites/site-settings/wrap-settings-form.jsx [hunk 4]
```diff
@@ -44,39 +45,55 @@ const wrapSettingsForm = getFormSettings => SettingsForm => {
...
 							break;
 					}
-					nextProps.errorNotice( text, { id: 'site-settings-save' } );
+					this.props.errorNotice( text, { id: 'site-settings-save' } );
 				}
 			}
 		}
 
+		updateDirtyFields() {
+			const unpersistedFields = this.props.fields;
```
Comment (aduth) [inline client/my-sites/site-settings/wrap-settings-form.jsx]: Minor: I wonder if this would be more clear as `dirtyFields`, then change `dirtyFields` below to `nextDirtyFields`, to indicate that we're updating what we'd previously considered to be dirty to what we now think to be dirty.

Comment (youknowriad) [inline client/my-sites/site-settings/wrap-settings-form.jsx]: Well! this is not totally true because `this.props.fields` contains the field values for either the dirty and the non dirty fields.

File: client/my-sites/site-settings/wrap-settings-form.jsx (hunk 2 above)
Comment (youknowriad) [inline client/my-sites/site-settings/wrap-settings-form.jsx]: I'm not sure I undertand your poing, this is exactly what the `dirtyFields` check above does. We compute the dirtyFields (fields with difference between persisted and unpersisted values), and now we just provide the HoC with the new persisited values (we're omitting the dirty fields here)

Comment (youknowriad) [inline client/my-sites/site-settings/wrap-settings-form.jsx]: Oh I understand better what you are saying after reading the following comment, yeah we could return if the `dirtyFields` have not changed :)

File: client/my-sites/site-settings/wrap-settings-form.jsx (hunk 4 above)
Comment (aduth) [inline client/my-sites/site-settings/wrap-settings-form.jsx]: >Well! this is not totally true because `this.props.fields` contains the field values for either the dirty and the non dirty fields.

Huh, didn't realize that. Guess it makes sense if the consuming components are meant to be able to pull a persisted or dirty value always via `fields`.

File: client/my-sites/site-settings/wrap-settings-form.jsx (hunk 2 above)
Comment (aduth) [inline client/my-sites/site-settings/wrap-settings-form.jsx]: >I'm not sure I undertand your poing
>Oh I understand better what you are saying

Maybe you are right actually. Is the `shallowCompare` in the `componentDidUpdate` enough to ensure that we'll never reach this point without there being some change?

File: client/my-sites/site-settings/wrap-settings-form.jsx (hunk 1 above)
Comment (youknowriad) [inline client/my-sites/site-settings/wrap-settings-form.jsx]: From the React doc, we should use the purecomponent version instead https://facebook.github.io/react/docs/shallow-compare.html.

I'm a bit concerned about the performance of `isEqual`, do you think I should write our own `shallowEqual`?

File: client/my-sites/site-settings/wrap-settings-form.jsx (hunk 2 above)
Comment (youknowriad) [inline client/my-sites/site-settings/wrap-settings-form.jsx]: Well! after trying to shortcut these calls when there are no changes, I noticed some lags. I prefer to leave these as is for now.

**Comment by youknowriad** [comment]
@aduth I updated the PR to fix a small bug when loading the form from a cold cache, it should be good now. I left  the `shallowEqual` because it's more performant than `isEqual` and as I said from the React Doc, this looks like the way to go https://facebook.github.io/react/docs/shallow-compare.html.

**Comment by aduth** [comment]
I forgot that `react-addons-shallow-compare` was deprecated. I'd say for objects that we know to be shallow anyways, the impact of deep equality checking is non-existent (or if there is, it more accurately reflects deep changes we'd want to observe anyways). I agree we'd want a more general solution for cases where shallow comparison is appropriate; we should probably look to see if there's an existing package we can leverage ([`shallow-equals`](https://www.npmjs.com/package/shallow-equals)?).

**Comment by aduth** [comment]
And to clarify, `_.isEqual` isn't inherently slow. If an object's values are not object-like, it's the same as a shallow comparison ([source](https://github.com/lodash/lodash/blob/912d6b04a1f6b732508a6da72a95ec4f96bda154/lodash.js#L3278-L3286)).

**Comment by youknowriad** [comment]
@aduth Actually, I was thinking our objects are not shallow but the more I think about it, the more I think, if it's the case and our form can mutate these sub objects, `isEqual` is better in this case. 

I updated the PR, let me know if you have another concern

**Comment by youknowriad** [comment]
@aduth do you have the time to check this again 😄 ?

**Comment by aduth** [comment]
Do we need to rebase and update to remove references to `markChanged` prop in [`form-analytics.jsx`](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/site-settings/form-analytics.jsx) ?

File: client/my-sites/site-settings/wrap-settings-form.jsx (hunk 4 above)
Comment (aduth) [inline client/my-sites/site-settings/wrap-settings-form.jsx]: Still wondering if another name would be more appropriate, since this does include a mix of both persisted and unpersisted fields, yeah? Maybe `allFields` or `currentFields`?

Comment (youknowriad) [inline client/my-sites/site-settings/wrap-settings-form.jsx]: Ok, I'm going for `currentFields` 👍

**Comment by youknowriad** [comment]
@aduth RIght! I rebased and addressed the notes in 2038eb9 :)

**Comment by aduth** [comment]
This looks and works well for me 👍 

The only "issue" I have is that `updateDirtyFields` will be triggered unnecessarily when first visiting a settings form because it transitions from an empty `fields` array to one with members as a consequence of the `replaceFields` in `componentWillMount`, so it passes the `! isEqual( prevProps.fields, this.props.fields )` condition. I don't necessarily think this is a blocker, but could be optimized.

**Comment by youknowriad** [comment]
Tks for the review @aduth I could check that `prevProps.fields` is different than an empty object to avoid this first "run", but I don't think it's a good idea since a form could decide to initialize the settings as an empty object.
