### PR TITLE
Reader: change tag photo attribution

### LINKED ISSUE #31088: Reader: Misattributed photos
A photographer complained that our photos from Pexels are being used in the reader, with "Photo by (blogger name)"   While the cc0 license does not require attribution, _misattribution_ is problematic.

#### Steps to reproduce
1. Starting at URL: wordpress.com/tag/poetry (or any other tag)
2. Note the photo at the top. Sometimes it really is by the blogger, but often it's not, and the phrasing seems to attribute all photos to the site owner.

#### What I expected
Suggestion: instead of saying "Photo by (blogger)" we could say "Photo on (site)" or "Photo from (site)" so as to avoid misattributing.

#### Context / Source
https://en.forums.wordpress.com/topic/why-are-wp-crediting-writers-for-images-instead-of-the-real-photographers/#post-3274476

screen shot 2019-02-27 at 10 47 19 am

### PR DESCRIPTION
**Pull request by bluefuton**
#### Changes proposed in this Pull Request

In https://github.com/Automattic/wp-calypso/issues/31088, @supernovia notes that we currently attribute tag header photos to the originating site using the phrase "Photo by...".

This could be a misattribution, because the photo could be created by someone else.

This PR changes the phrase to "Photo from..." to avoid giving the impression that the site owner is the one who created the photo.

#### Testing instructions

Visit a tag stream like http://calypso.localhost:3000/tag/otter, and verify that the attribution contains "from" not "by".

screen shot 2019-02-28 at 13 43 51

Fixes #31088.

### CODE REVIEW

**Comment by supernovia** [comment]
Looks good to me! A simple change makes a big difference.

File: client/reader/tag-stream/header.jsx [hunk 1]
```diff
@@ -115,7 +115,7 @@ class TagStreamHeader extends React.Component {
 					</h1>
 					{ tagImage && (
 						<div className="tag-stream__header-image-byline">
-							{ translate( '{{photoByWrapper}}Photo by{{/photoByWrapper}} {{authorLink/}}', {
+							{ translate( '{{photoByWrapper}}Photo from{{/photoByWrapper}} {{authorLink/}}', {
```
Comment (blowery) [inline client/reader/tag-stream/header.jsx]: Maybe change the name of the wrapping placeholder as well? Maybe
```suggestion
							{ translate( '{{sourceWrapper}}Photo from{{/sourceWrapper}} {{authorLink/}}', {
```
