### PR TITLE
Site settings: allow site to be deleted if only purchases are non-refundable premium themes

### LINKED ISSUE #17012: Site settings: Allow site with premium theme to be deleted with proper warnings
In adding a warning when deleting a site with a Premium theme we have blocked sites with only a Premium theme from deleting their site. The message is generic for all upgrades and advises the user to cancel the upgrade before deleting their site. However, premium themes are a one-time purchase and we do not support deleting them. 

#9639 was opened to allow premium themes to be canceled, but given the difficulty for staff to restore them in the case of accidental cancellation and potential loss of settings when this happens I think we should instead allow sites with only premium theme(s) to delete their site as they could previously, but with proper warning that the site has a premium theme and access to it will be lost.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/general/example.wordpress.com where example.wordpress.com has a premium theme
2. Select the "Delete your site permanently option"
3. You are shown the following warning with no way to proceed without contacting support, as Premium themes cannot be canceled by users

screen shot 2017-07-26 at 10 34 46 am

#### What I expected
To be able to delete a site with a premium theme with proper warnings that I would lose access

#### What happened instead
The user is shown a message to cancel the upgrades that cannot be done on their own and requires support intervention

### PR DESCRIPTION
**Pull request by bluefuton**
#### Changes proposed in this Pull Request

Currently, it is not possible to delete a site with any active purchases. We direct the user to their Purchases to cancel everything first.

Premium themes are a special case, in that it is not possible to cancel them after they're outside the refund period. Users with a premium theme therefore are unable to delete their site.

This PR allows users to delete a site if the only purchases attached to it are non-refundable premium themes.

#### Testing instructions

screen shot 2018-10-19 at 15 02 28

Visit http://calypso.localhost:3000/settings/general and test with sites that:

* Only have premium themes that are not refundable. Verify that you can now proceed with site deletion.

* Do not have any premium themes or purchases. You should still be able to proceed with site deletion.

* Have purchases besides premium themes. Verify that you are shown the warning popover, and that it is not possible to delete the site.

screen shot 2018-10-19 at 15 02 32

Fixes #17012.

### CODE REVIEW

**Comment by bluefuton** [comment]
Related PR dealing with the same scenario for account closure: https://github.com/Automattic/wp-calypso/pull/27411.

File: client/my-sites/site-settings/delete-site/index.jsx [hunk 1]
```diff
@@ -263,14 +260,17 @@ class DeleteSite extends Component {
...
+								<li className="delete-site__content-list-item">
+									{ translate( 'Premium Themes' ) }
+								</li>
 							</ul>
 						</ActionPanelFigure>
 						{ ! isAtomic && (
 							<div>
 								<p>
 									{ translate(
 										'Deletion {{strong}}can not{{/strong}} be undone, ' +
```
Comment (a8ci18n) [inline client/my-sites/site-settings/delete-site/index.jsx]: Hi! I've found a possible matching string that has already been translated **27** times:
`translate( 'Deletion {{strong}}can not{{/strong}} be undone, and will remove all content, contributors, domains, and upgrades from this site.' )` *ES Score: 12*

Help me improve these suggestions: react with :thumbsdown: if the suggestion doesn't make any sense, or with :thumbsup: if it's a particularly good one (even if not implemented).

File: client/my-sites/site-settings/delete-site/index.jsx [hunk 2]
```diff
@@ -299,7 +299,7 @@ class DeleteSite extends Component {
 								<p>
 									{ translate(
 										"To delete this site, you'll need to contact our support team. Deletion can not be undone, " +
```
Comment (a8ci18n) [inline client/my-sites/site-settings/delete-site/index.jsx]: Hi! I've found a possible matching string that has already been translated **18** times:
`translate( 'To delete this site, you'll need to contact our support team. Deletion can not be undone, and will remove all content, contributors, domains, and upgrades from this site.' )` *ES Score: 12*

Help me improve these suggestions: react with :thumbsdown: if the suggestion doesn't make any sense, or with :thumbsup: if it's a particularly good one (even if not implemented).

File: client/my-sites/site-settings/delete-site/index.jsx (hunk 1 above)
Comment (bluefuton) [reply client/my-sites/site-settings/delete-site/index.jsx]: `translate` can handle strings split with the concatenation operator `+`, but it looks like the bot can't :)

**Comment by KokkieH** [comment]
Tested using these steps:

### Test 1

1. Purchased a premium theme on a new site on a test account using PayPal so there's a refundable transaction
2. Ran the branch locally and visited Purchases - Theme shows cancel and refund option
3. Went to My Site ->Settings and click on Delete your site permanently

Saw an overlay prompting me to cancel my upgrades prior to deleting the site. After cancelling and refunding the theme I'm able to delete the site.

### Test 2

1. Purchased a premium theme using credits so the theme won't be refundable
2. With this branch running, visited Purchases and confirmed theme does not show as refundable
3. Went to My Site ->Settings and click on Delete your site permanently

I was able to successfully confirm and finish deleting the site without having to remove the theme.

### Test 3

1. Purchased the Personal Plan as well as a Premium Theme using credits.
2. With this branch running, went to My Site ->Settings and attempt to delete the site.
3. See overlay that I need to cancel my upgrades first.
4. Visit Purchases and cancel the plan - theme is non-refundable and cannot be cancelled
5. Go back to My Site ->Settings and attempt to delete the site.

I was able to successfully delete the site.

I'm also able to delete a site with no purchases as normal.

**Summary**: From what I can see the PR is working as intended.
