### PR TITLE
Manage Purchases: Hide "Excludes Tax" for Free Purchases

### LINKED ISSUE #88872: Purchase Management: "Renewal Price" shouldn't show for one-time purchases
### Quick summary

On the purchase management page, a "Renewal Price" section is shown for one-time purchases:

one-time-purchase-renewal

It doesn't make sense and therefore shouldn't be shown.

### Steps to reproduce

1. Make a one-time purchase (buying "Built By WordPress.com Express" by starting at https://wordpress.com/website-design-service/ is one way to do it).
2. Find it on https://wordpress.com/me/purchases and click through to view the purchase management page.

### What you expected to happen

I did not expect to see information about a renewal price and renewal taxes, since the purchase doesn't actually renew.

(I'm pretty sure we used to handle one-time purchases differently on this page, although I don't remember how.)

### What actually happened

I saw the screenshot shown above.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### LINKED ISSUE #89121: Purchase Management: Free purchases shouldn't show "excludes tax"
### Quick summary

For a free purchase (for example a domain connection subscription that is free with a plan) we are showing "excludes tax" in the Renewal Price section, which doesn't make sense:

free-domain-connection

### Steps to reproduce

1. Buy a plan
2. Add a free domain connection
3. Go to https://wordpress.com/me/purchases and click through to manage the domain connection purchase

### What you expected to happen

It should have just said "Renewal Price: Free with Plan"

### What actually happened

It also said "excludes tax"

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by Aurorum**
Fixes #89121 and fixes #88872

## Proposed Changes

* Hides the "excludes tax" string for purchases that are free. 

## Testing Instructions

* Connect a domain to a site with a paid plan (you don't actually need a domain - just need to follow the process!)
* Go to Me > Purchases
* Confirm that "Excludes tax" no longer appears under the "Renewal price", but that it does with other purchases

| Before | After |
|--------|--------|
| Screenshot 2024-04-04 at 06 53 55 | Screenshot 2024-04-04 at 06 52 17 |

cc @DavidRothstein, @JessBoctor, @sirbrillig

### CODE REVIEW

**Review by michaeldcain — APPROVED** [review]
This works as described and LGTM. Thanks for the patch!

Screenshot 2024-04-05 at 4 51 29 PM

@Aurorum if you want to take a look at https://github.com/Automattic/wp-calypso/issues/88872, I'd be happy to drop some one-time purchases on one of your sites.

**Comment by Aurorum** [comment]
Thanks for the review @michaeldcain! 

More than happy to address that issue too. I suspect it might just be a matter of adding a check for `isOneTimePurchase` but you’re right that I didn’t include it because I can’t test it, so if you’d mind adding a one-time purchase, that’d be super handy. :) (my WPcom username is `torres126`)

**Comment by michaeldcain** [comment]
@Aurorum I added a one-time purchase to `testsiteaurorum.wordpress.com` - let me know if you run into any issues.

**Comment by Aurorum** [comment]
Perfect, thank you! Should be removed there now too.

Screenshot 2024-04-05 at 22 37 32

File: client/me/purchases/manage-purchase/purchase-meta.tsx [hunk 1]
```diff
@@ -82,6 +82,8 @@ export default function PurchaseMeta( {
 			? translate( 'Renewal Price' )
 			: translate( 'Price' );
 
+	const hideTaxString = isIncludedWithPlan( purchase ) || isOneTimePurchase( purchase );
```
Comment (michaeldcain) [inline client/me/purchases/manage-purchase/purchase-meta.tsx]: Sorry for the confusion, but for the one-time purchases, the goal of #88872 is to hide the entire section (starting at the list item on L112), not just the tax message. It would ultimately look like the following for a Quick Start:

Screenshot 2024-04-06 at 9 36 22 AM

**Review by michaeldcain — CHANGES_REQUESTED** [review]
One small change with the newest commit.

File: client/me/purchases/manage-purchase/purchase-meta.tsx (hunk 1 above)
Comment (Aurorum) [reply client/me/purchases/manage-purchase/purchase-meta.tsx]: Ah, my apologies - totally missed that. Should be fixed now.

**Review by DavidRothstein — COMMENTED** [review]
Looks nice -- thanks!

I haven't checked, but this probably won't hide the message for all free purchases (only for domain connection subscriptions included with a plan) and thus it might not fully fix https://github.com/Automattic/wp-calypso/issues/89121, but I think it's fine to commit even without being a complete fix since it's definitely an improvement.

**Review by sirbrillig — APPROVED** [review]
I like it. Running full tests...

**Comment by sirbrillig** [comment]
~All the tests have passed but I'm having trouble getting the "Code style" tests to show up as having run for some reason. I re-ran them twice but the PR still says "Waiting for status to be reported". I'm asking for help but if you see this first @Aurorum, maybe you can try rebasing the PR and force pushing it to kick off another test run?~

Nevermind, I figured out how to run them.

**Comment by Aurorum** [comment]
Hey @sirbrillig - sorry, only seeing this now! Thanks for helping get this merged. :) 

##

@DavidRothstein 

> I haven't checked, but this probably won't hide the message for all free purchases

Ah, good point. I'd be happy to include those too, but the problem is that I don't have a free purchase on my account. @michaeldcain would you mind adding one for me again?!

Thanks all!! :)
