### PR TITLE
Fix: business hours validation

### LINKED ISSUE #11441: Domains: Update notices and warnings for domain-only domains
We show a couple of warning notices for newly registered domains (see attachments). We still need these but we should improve on them.

image
image

We should treat these notices as part of the flow. Otherwise it's like you always end the flow in an error state.

Summary from chats on Slack about the problems with current implementation for domain-only users:

* The information in the notices could be incorporated in thank you screen and email, so we don't have to rely on these notices for new users.
* The sidebar notice about verifying the contact information doesn’t have to be shown from day 0, we can start to show it later. Users will still get notified about this by email, more than once.
* The "primary domain" part of the yellow notice doesn't apply to domain-only sites.
* The “72 hours” part of the yellow notice can perhaps be reimagined as a less intrusive “domain changes pending” indicator. We don't know if a user can see their domain or not when we show this notice, and this notice makes a normal delay seem like an error.

#### Proposed solutions:

* Let's only show the sidebar notice about verifying email address after a day.
* Let's completely remove the yellow notice for domain-only sites.
* Let's add the information about new domain delay to the default screen, and only show it for the first six hours:
image

### PR DESCRIPTION
**Pull request by roccotripaldi**
#### Changes proposed in this Pull Request

Currently, if you create a post with a business hours block, and then change your site's locale or time format, the previously saved post will become invalid when you try to edit it again.

screen shot 2019-02-28 at 9 57 29 am

This PR ensures we only save un-localize content. We save it in english with a time format of `g:i`
And we only localize on the front end, and when we preview the block in the editor.

#### Testing instructions

* [Try out this Jurassic.ninja link](https://jurassic.ninja/create/?gutenpack&shortlived&jetpack-beta&calypsobranch=fix/11441-business-hours-validation)
* Enable Beta blocks in Settings -> Jetpack Constants
* Create a post with a Business Hours block and save it
* change your site's locale in Settings -> General
* Visit the post on the front end. Is it localized?
* Edit the post, and ensure there are no validation errors
* change your site's time format in Settings -> General
* Visit the post on the front end. Does the time format look right?
* Edit the post again, and ensure there are no validation errors

Fixes #11441

### CODE REVIEW

**Comment by lezama** [comment]
I am seeing a "jump" when loading the block in another language, not sure if there's something easy we could do about it

jump

File: client/gutenberg/extensions/business-hours/components/day-save.jsx [hunk 1]
```diff
@@ -6,11 +6,6 @@ import { date } from '@wordpress/date';
 import { isEmpty } from 'lodash';
 import { sprintf } from '@wordpress/i18n';
 
-/**
- * Internal dependencies
- */
-import { _x } from 'gutenberg/extensions/presets/jetpack/utils/i18n';
-
 class DaySave extends Component {
```
Comment (lezama) [inline client/gutenberg/extensions/business-hours/components/day-save.jsx]: `DaySave` sounds weird as component name, are we using this `ComponentSave` notation elsewhere?

**Comment by roccotripaldi** [comment]
> not sure if there's something easy we could do about it

I'm not able to repeat it

File: client/gutenberg/extensions/business-hours/components/day-save.jsx (hunk 1 above)
Comment (roccotripaldi) [reply client/gutenberg/extensions/business-hours/components/day-save.jsx]: no we don't. i'm not sure what else to call it

Comment (simison) [reply client/gutenberg/extensions/business-hours/components/day-save.jsx]: We use similar notation here: https://github.com/Automattic/wp-calypso/tree/9073dcc3c49d2afadf602e042dd454779039ede1/client/gutenberg/extensions/tiled-gallery/gallery-image

I think important part is to call the other one `DayEdit` if there is `DaySave`

`DateRow` could be alternative for "Day"

**Comment by sirreal** [comment]
I suspect the issue @lezama is seeing comes from using the English string initially, then swapping it for a localized string that comes back from an API call.

**Comment by roccotripaldi** [comment]
> I suspect the issue @lezama is seeing comes from using the English string initially, then swapping it for a localized string that comes back from an API call.

That's reasonable - but as far as i can tell we should only be showing placeholders until we have the right data

**Comment by simison** [comment]
> as far as i can tell we should only be showing placeholders until we have the right data

Showing placeholders seems like a sensible solution, cc @thomasguillot for design opinion.

I'm not sure if there is a way to check for current locale in the editor, but if is possible, you could avoid doing `apiFetch` when locale is already `en_*`?

**Comment by roccotripaldi** [comment]
After a conversation with @sirreal - we've decided on this approach:
- drop the save component altogether, because we use server-side rendering for the block
- have a <DayEdit /> and <DayPreview /> component for client side rendering, which are only rendered once we've fetched localization

File: client/gutenberg/extensions/business-hours/edit.jsx [hunk 2]
```diff
@@ -68,26 +77,24 @@ class BusinessHours extends Component {
...
-				/>
-			);
-		}
-
 		return (
 			<div className={ classNames( className, 'is-edit' ) }>
 				{ localizedWeek.map( ( day, key ) => {
-					return <Day key={ key } day={ day } localization={ localization } { ...this.props } />;
+					return (
+						<DayEdit key={ key } day={ day } localization={ localization } { ...this.props } />
```
Comment (sirreal) [inline client/gutenberg/extensions/business-hours/edit.jsx]: A minor point: I prefer to avoid `...spreadProps` in most Component hierarchies. I find the clarity of explicit prop passing to be more maintainable.

**Comment by jeherve** [comment]
Cherry-picked to the release branch in 1d98d30105242a862402c64ec8e93d0dd99af4e7
