### PR TITLE
Use wpcc onboarding flow for account creation during oauth login by default

### LINKED ISSUE #71027: [Bug]: Redirect destinations are not preserved after user account creation
### Quick summary

If you visit any URL that you need to be logged in to access, it will redirect you to the login page, and if you log in from there it will nicely redirect you back to your final destination afterwards, via use of a `redirect_to` URL parameter.

However, if you click "Create a new account" from that login page, then after account creation you wind up thrown into the site creation flow -- the original destination in `redirect_to` is gone and you never get back there.

**In many cases, this is a terrible user experience.  Basically whatever purpose you were trying to create your WordPress.com account for, you are taken completely away from that with no obvious way back!**

This issue was originally noted by me in pdtkmj-Ks-p2#comment-1231 as part of the subscription gifting project, and then moved to https://github.com/Automattic/wp-calypso/issues/70354.  The fix there wound up being to use a logged-out checkout flow (which was the best user experience for that specific subscription gifting scenario anyway) but the underlying problem here seems like a major user experience problem that could be affecting many parts of WordPress.com.

----

To solve this, the "Create a new account" link probably needs to be conditionally changed to something like `https://wordpress.com/start/account/user?redirect_to=[....]` (i.e., put the user into the simple account creation flow that doesn't expect to send the user to site creation afterwards, and also preserve the original `redirect_to` parameter that was there before).  This should mostly work, although basic testing showed that in some cases you might wind up with a "Building your site" interstitial inserted on the page before you are redirected.

### Steps to reproduce

1. While logged out, visit any URL that requires login (example, https://wordpress.com/me/purchases).
2. Notice that you are redirected to the login page with the destination in a `redirect_to` parameter (example, https://wordpress.com/log-in?redirect_to=%2Fme%2Fpurchases), 
3. Create an account from that page.

### What you expected to happen

After creating an account, I would expect to wind up on the page I was originally trying to go to.

### What actually happened

I wound up in the site creation flow, e.g. at a URL like https://wordpress.com/start/user or https://wordpress.com/start/domains.

### Browser

_No response_

### Context

_No response_

### Platform (Simple, Atomic, or both?)

_No response_

### Other notes

_No response_

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by lsl**
Fixes https://github.com/Automattic/wp-calypso/issues/71027

## Proposed Changes

There are two issues being resolved here:
- #71027 outlines how redirect_to is ignored when creating an account from the login screen as the redirect_to param gets dropped when moving to /start. Even if it was passed in it would be ignored by the /start/onboarding flow. This PR both ensures the redirect_to is passed through and that /start/account is used in place of /start/onboarding (aka /start) when a redirect_to query param is provided. 
- p1697220716421119-slack-C02T4NVL4JJ discusses account creation when logging in to e.g. vaultpress via oauth. This PR routes all signups via oauth through /start/wpcc if there isn't a specific flow already defined in `signupUrl`

Todo:

Could use help testing
- [x] Each oauth client flow, especially jetpack and woocommerce.com
- [x] Jetpack connections
- [x] Comment / like signups

## Testing Instructions

Redirect to & /start/account handling:

* While logged out visit:
* http://calypso.localhost:3000/me
* You should be landed there after creating an account using the "Create a new account" button

Wpcc login paths:

* While logged out of wordpress.com visit:
* https://vaultpress.com/
* Click login
* You'll be taken to wordpress.com login screen: e.g. `https://wordpress.com/log-in?client_id=930&redirect_to=https%......`
* Change the `wordpress.com` part to `calypso.localhost:3000` for testing.
* Click "Create a new account"
* You should be taken to the /start/wpcc sign up flow and ultimately logged in to vaultpress after signup.

Screenshot(33)

### CODE REVIEW

**Review by paulopmt1 — APPROVED** [review]
It's working as expected on the Calypso private site link, vaultpress.com and WooCommerce login. 
Nice fix @lsl!

**Review by DustyReagan — APPROVED** [review]
I tested and added unit tests as I went. Looks good to me! Please feel free to edit the tests! 👍

File: client/lib/login/index.js [hunk 1]
```diff
@@ -121,20 +115,23 @@ export function getSignupUrl( currentQuery, currentRoute, oauth2Client, locale,
...
+			oauth2_client_id: oauth2Client.id,
+			oauth2_redirect: redirectTo,
+		} );
+		signupUrl = `${ signupUrl }/wpcc?${ oauth2Params.toString() }`;
+	} else if (
 		isFromMigrationPlugin ||
 		isFromPublicAPIConnectFlow ||
-		( includes( redirectTo, 'action=jetpack-sso' ) && includes( redirectTo, 'sso_nonce=' ) )
+		( includes( redirectTo, 'action=jetpack-sso' ) && includes( redirectTo, 'sso_nonce=' ) ) ||
+		redirectTo
```
Comment (lsl) [inline client/lib/login/index.js:153]: I think this breaks /log-in/jetpack maybe.

Comment (lsl) [reply client/lib/login/index.js:153]: Should be fine now, returning early instead.

File: client/lib/login/index.js [hunk 2]
```diff
@@ -120,26 +117,45 @@ export function getSignupUrl( currentQuery, currentRoute, oauth2Client, locale,
...
+	}
+
+	if ( signupFlow ) {
+		if ( redirectTo ) {
+			const params = new URLSearchParams( {
+				redirect_to: redirectTo,
+			} );
+			return `${ signupUrl }/${ signupFlow }?${ params.toString() }`;
+		}
+		return `${ signupUrl }/${ signupFlow }`;
```
Comment (lsl) [inline client/lib/login/index.js:146]: Moved signupFlow down to here, maintaining redirectTo pass through for consistency, I can't actually see anything that uses it other than 3-4 instances in trunk that are only using it to bypass /start (they're setting signup_flow to account i.e. what we would return with the redirect_to anyway.)

**Comment by lsl** [comment]
@eoigal do you mind taking a look re the highlander comment login pathing through here?

**Comment by mdawaffe** [comment]
Worked for me testing an OAuth2 app.

This PR directs the signup through a user-only flow (that is, no site is created). The use case I'm looking at is for an app that doesn't make sense to use unless the user has at least one site, but I think that's a separate issue. Thanks for fixing!

**Comment by lsl** [comment]
> The use case I'm looking at is for an app that doesn't make sense to use unless the user has at least one site, but I think that's a separate issue. Thanks for fixing!

These are the use cases I'm worried about as we'll more or less be breaking them with this change. They should be fixable by passing in a `?singup_flow=onboarding` query param to the login link. The issue being that the onboarding flow doesn't respect any redirect_to's passed in along with it. (I don't think it ever did)
