### PR TITLE
Domains: Switch to v1.2 of is_available endpoint

### LINKED ISSUE #11051: Unable to map .ie and certain other TLDs
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains/add/
2. Type any registered .ie domain (or subdomain if you want to)

#### What I expected

To be able to map any registered, valid, .ie, id, .pk, some other domains. For example, mydomain.ie, tracker.ie, news.ie

#### What happened instead

It asks me to: "You can register it elsewhere first and then add it here." But, it's already registered! :)

#### Browser / OS version

Chrome, latest, Win10.

#### Screenshot / Video

mapping-ie

And if you choose the last option to map it anyway, still won't let you map:

mapping-ie2

#### Context / Source
It seems like there are multiple mapping issues present in the flow. #8998 was related but fixed. Not sure if I should've re-opened that. There's #10176 which also deals with mapping but not directly related with .ie.

#user-report , #manual-testing

### PR DESCRIPTION
**Pull request by klimeryk**
Every month we run into problems caused by the constrains of the v1 of our `is_available` endpoint and the way it returns the availability/mappability/registrability of a domain. On the frontend, we tried to figure out how these flags work with each other, etc. Which led to bugs, whenever we touched one of them. These boolean flags also did not allow for a more finegrained returns status, like when we _don't_ know if a domain is available or not.
Since patching this approach obviously was not working, I've decided to step back, look at our requirements for that endpoint and try to write a v1.2 that satisfies them all.

The backend patch required for this PR is `D4542-code`.

The core of the change is that instead of individual flags, we have one `status` (string) field. If a domain is available for registration, it's `available`, if it's mappable, it's `mappable`. Other cases are treated as errors, with the exception of `unknown`, which gets a special treatment, since we have to allow mapping of such domains.

### Testing
Patch your sandbox with `D4542-code`.

Be sure to thoroughly test both the NUX and Domain Management flows for adding/registering a new domain or mapping an existing one.
Verify that `.ie` domains _and_ subdomains can be mapped (but not registered, of course).

screen shot 2017-03-01 at 22 58 54

Fixes #11051

### CODE REVIEW

File: client/lib/domains/index.js [hunk 1]
```diff
@@ -35,40 +35,17 @@ function canAddGoogleApps( domainName ) {
...
-			errorCode = 'not_available_but_mappable';
-		} else if ( isAvailable && ! isRegistrable ) {
-			errorCode = 'available_but_not_registrable';
-		}
-
-		if ( errorCode ) {
-			onComplete( new ValidationError( errorCode ) );
-		} else {
-			onComplete( null, data );
-		}
```
Comment (umurkontaci) [inline client/lib/domains/index.js]: 👍 🎉

Comment (aidvu) [inline client/lib/domains/index.js]: 😮

File: client/components/domains/map-domain-step/index.jsx [hunk 2]
```diff
@@ -59,8 +60,7 @@ const MapDomainStep = React.createClass( {
 
 	render: function() {
 		const suggestion = { cost: this.props.products.domain_map.cost_display, product_slug: this.props.products.domain_map.product_slug },
```
Comment (aidvu) [inline client/components/domains/map-domain-step/index.jsx]: I believe the `domain_map` can't be `undefined`? Otherwise, we'd need the same condition from below.

File: client/lib/wpcom-undocumented/lib/undocumented.js [hunk 3]
```diff
@@ -442,29 +442,17 @@ Undocumented.prototype._sendRequestWithLocale = function( originalParams, fn ) {
 };
 
 /**
- * Determine whether a domain name can be mapped
- *
- * @param {string} domain - The domain name to check.
- * @param {Function} fn The callback function
- * @api public
- */
-Undocumented.prototype.isDomainMappable = function( domain, fn ) {
```
Comment (aidvu) [inline client/lib/wpcom-undocumented/lib/undocumented.js]: Surprised we didn't remove this before, as it's not used anymore.

Comment (klimeryk) [inline client/lib/wpcom-undocumented/lib/undocumented.js]: That's on me - I've removed the code for checking mappability in `lib/domains/index` in https://github.com/Automattic/wp-calypso/pull/10967/files#diff-a36618f44b2f6aeae8145056394c517aL73, but forgot to remove the actual API call 😞 So I fixed it here ;)

File: client/components/domains/map-domain-step/index.jsx (hunk 2 above)
Comment (klimeryk) [inline client/components/domains/map-domain-step/index.jsx]: Yeah, tested it thoroughly (including a new user, empty session, throttled) and it seems OK. Probably because we load products at the start of Calypso :man_shrugging:

Comment (klimeryk) [inline client/components/domains/map-domain-step/index.jsx]: OK, since I don't like ambiguity and depending on how the application behaves _now_, I'll add a safeguard for this 👍
