### PR TITLE
Change copy that displayed for Google Apps and Premium Theme cancelation

### LINKED ISSUE #4698: Purchases: incorrect copy on Premium theme cancellation
The confirmation dialog for Premium Theme cancellation contains plan related copy:

screenshot-wordpress com 2016-04-13 10-22-15

We need to update this with correct copy. cc @ranh 

Steps to reproduce:

- Purchase a Premium Theme from `/design`.
- Go to `/purchases`, find the new theme and hit Cancel and Refund.
- A dialog will show with incorrect copy.

### PR DESCRIPTION
**Pull request by yurynix**
That PR resolves #4698,
by adding the following messages for cancelation of products that are google apps / premium themes:

Remove google apps ( without refund / after cancel + refund ):
screen shot 2016-05-30 at 10 31 39 am

Google apps cancelation with refund: 
screen shot 2016-05-30 at 11 10 44 am

Premium theme cancelation with refund:
screen shot 2016-05-30 at 11 20 47 am

#### Testing instructions
 
1. Run `git checkout fix/change-cancel-copy` and start your server
2. Purchase Google Apps and a Premium theme
3. Cancel each one of them (both before refund period and after)
4. Verify the correct message appears
 
#### Reviews
 
- [x] Code
- [ ] Product

### CODE REVIEW

**Comment by Tug** [comment]
Code 👍

**Comment by fabianapsimoes** [comment]
Product :+1:

File: client/me/purchases/cancel-purchase/button.jsx [hunk 1]
```diff
@@ -60,9 +60,38 @@ const CancelPurchaseButton = React.createClass( {
...
 					disabled: this.state.submitting,
 					onClick: this.submitCancelAndRefundPurchase
-				},
+				}
 			];
 
+		let cancelationEffectString = this.translate(
+			'All plan features and custom changes will be removed from your site and you will be refunded %(priceText)s.', {
+				args: {
+					priceText: refundText
```
Comment (stephanethomas) [inline client/me/purchases/cancel-purchase/button.jsx]: This has come up before but again I don't think it's a good idea to use `priceText` in these strings because translators won't have a clear idea of what this variable will contain. So we should either add more context or (probably better) rename it into `cost` or something like that.

File: client/me/purchases/cancel-purchase/button.jsx [hunk 2]
```diff
@@ -60,9 +60,38 @@ const CancelPurchaseButton = React.createClass( {
 					isPrimary: true,
 					disabled: this.state.submitting,
 					onClick: this.submitCancelAndRefundPurchase
-				},
+				}
 			];
 
+		let cancelationEffectString = this.translate(
```
Comment (stephanethomas) [inline client/me/purchases/cancel-purchase/button.jsx]: We should probably avoid using this `String` suffix. First because we usually don't do that and second because the `translate()` function sometimes returns objects or arrays.

File: client/me/purchases/remove-purchase/index.jsx [hunk 3]
```diff
@@ -168,7 +168,11 @@ const RemovePurchase = React.createClass( {
 						} )
 					}
 					{ ' ' }
-					{ this.translate( 'You will not be able to reuse it again without purchasing a new subscription.', {
+					{ isGoogleApps( purchase )
+						? this.translate( 'Your Google Apps account will continue working without interruption. ' +
+										'You will be able to manage your Google Apps billing directly through Google.'
+						)
+					: this.translate( 'You will not be able to reuse it again without purchasing a new subscription.', {
```
Comment (stephanethomas) [inline client/me/purchases/remove-purchase/index.jsx]: I think the indentation here is slightly incorrect and should be:

```javascript
  { isGoogleApps( purchase )
    ? this.translate( 'Your Google Apps account will continue working without interruption. ' +
            'You will be able to manage your Google Apps billing directly through Google.'
    )
    : this.translate( 'You will not be able to reuse it again without purchasing a new subscription.', {
      comment: "'it' refers to a product purchased by a user"
    } )
  }
```

Comment (yurynix) [inline client/me/purchases/remove-purchase/index.jsx]: Changed that, thanks!

File: client/me/purchases/cancel-purchase/button.jsx (hunk 2 above)
Comment (yurynix) [inline client/me/purchases/cancel-purchase/button.jsx]: Changed that, thanks!

File: client/me/purchases/cancel-purchase/button.jsx (hunk 1 above)
Comment (yurynix) [inline client/me/purchases/cancel-purchase/button.jsx]: Changed that, thanks!

**Comment by stephanethomas** [comment]
This is good to good as soon as you have cleaned the commits history :+1: .
