### PR TITLE
Reader: add referral post to full post view

### LINKED ISSUE #9803: Reader refresh: Discover full post links no longer link to discover.wordpress.com
In the prior full post view, discover picks linked out to the post on discover.wordpress.com.  The request was then redirected to the source post.  On all but the discover site picks the new full post view uses the source post links. This has caused a significant drop in views on discover.wordpress.com

#### Steps to reproduce
1. Visit https://wordpress.com/discover
2. Click on a non-site pick to go to full post view
3. Visit source post from reader stream by clicking the title or post date

#### What I expected

The view should be counted for the pick on discover.wordpress.com

### PR DESCRIPTION
**Pull request by jhnstn**
This adds the ability to load a referral from the reader stream to a full post view. It uses query parameters set in the full post url to load the referred post. This way the referred URL can be shared without losing the referral.

This PR also includes the implementation to swap out the source post links with their associated discover.wordpress.com link. 

Fixes #9803 

**Test**

**From discover stream**
1. Click on a discover pick, quote or image from the [discover stream](https://calypso.live/discover?branch=fix/reader-full-post-referral).
2. The full post view title and date should have a discover.wordpress.com link

**Direct link**
1. Visit a [referred post](https://calypso.live/read/blogs/24404096/posts/1201?branch=fix/reader-full-post-referral&ref_blog=53424024&ref_post=20008)
2. Hovering over the title or post at should show the [discover.wordpress.com](https://discover.wordpress.com/2016/11/30/calgarys-deane-house/) link

_note_: Clicking the title or post will redirect to [the post](https://toddkorol.wordpress.com/2016/11/28/calgarys-deane-house/) on the source blog

**Without referral**
1. Visit [the post](https://calypso.live/read/blogs/24404096/posts/1201?branch=fix/reader-full-post-referral) without the referral parameters.
2. Hovering over the title or post date should show the source [post url](https://toddkorol.wordpress.com/2016/11/28/calgarys-deane-house/)

### CODE REVIEW

File: client/reader/stream/post.jsx [hunk 1]
```diff
@@ -196,6 +196,10 @@ const Post = React.createClass( {
 		// For Discover posts (but not site picks), open the original post in full post view
 		if ( this.state.originalPost ) {
 			postToOpen = this.state.originalPost;
+
+			if ( postToOpen ) {
+				postToOpen.referral = { blogId: DiscoverHelper.discoverBlogId, postId: this.props.ID }
```
Comment (omarjackman) [inline client/reader/stream/post.jsx]: It looks like you are updating the state directly here. I think if you don't need `referral` to be in state then you should change the statement on line 198 to `postToOpen = { ...this.state.originalPost };`

File: client/reader/stream/refresh-post.jsx [hunk 2]
```diff
@@ -102,6 +102,9 @@ export default class ReaderPostCardAdapterFluxContainer extends React.Component
 				blogId: post.discover_metadata.featured_post_wpcom_data.blog_id,
 				postId: post.discover_metadata.featured_post_wpcom_data.post_id
 			} );
+			if ( originalPost ) {
+				originalPost.referral = { blogId: DiscoverHelper.discoverBlogId, postId: post.ID }
```
Comment (jhnstn) [inline client/reader/stream/refresh-post.jsx]: That function _does_ return `{ originalPost }` but I think I see the issue. `referral` doesn't need to be part of the state but it does need to get attached to the `originalPost` at some point. I did that in the older `./post.jsx` in the click handler but did not do that here ( I fixed the state mutation there as you correctly suggested ). 

`DRY` failure on my end, so to speak. In post.jsx we do the `isDiscover` logic in click handler and not in the state related functions. In the refresh the opposite is true so I incorrectly _DRY_'d the `isDiscover` logic and set the referral in the state management flow. 

Thanks for catching this!

File: client/blocks/reader-full-post/index.jsx [hunk 3]
```diff
@@ -396,6 +397,10 @@ const ConnectedFullPostView = connect(
 		if ( feedId ) {
 			props.feed = getFeed( state, feedId );
 		}
+
+		if ( ownProps.referral ) {
+			props.referralPost = getPostBySiteAndId( state, ownProps.referral.blogId, ownProps.referral.postId );
```
Comment (blowery) [inline client/blocks/reader-full-post/index.jsx]: we don't generally store posts in redux, only things that come in through related posts on the full post screen, and those get mirrored over into the flux `PostStore`. What case is this covering?

File: client/reader/stream/post.jsx [hunk 4]
```diff
@@ -195,7 +195,14 @@ const Post = React.createClass( {
 		let postToOpen = this.props.post;
 		// For Discover posts (but not site picks), open the original post in full post view
 		if ( this.state.originalPost ) {
-			postToOpen = this.state.originalPost;
+			postToOpen = { ...this.state.originalPost };
+
+			if ( postToOpen ) {
```
Comment (blowery) [inline client/reader/stream/post.jsx]: why the `if`?

File: client/reader/stream/post.jsx [hunk 5]
```diff
@@ -195,7 +195,14 @@ const Post = React.createClass( {
 		let postToOpen = this.props.post;
 		// For Discover posts (but not site picks), open the original post in full post view
 		if ( this.state.originalPost ) {
-			postToOpen = this.state.originalPost;
+			postToOpen = { ...this.state.originalPost };
```
Comment (blowery) [inline client/reader/stream/post.jsx]: this could just be 
```
postToOpen = {
  ...this.state.originalPost, 
  { 
    referral: {
      blogId: DiscoverHelper.discoverBlogId,
      postId: this.props.ID
    }
}
```

Comment (blowery) [inline client/reader/stream/post.jsx]: i edited this ... so many times. :D

File: client/reader/stream/refresh-post.jsx [hunk 6]
```diff
@@ -13,15 +13,27 @@ import { getSite } from 'state/reader/sites/selectors';
...
+	isDiscoverSitePick,
+	getSourceData as getDiscoverSourceData,
+	discoverBlogId
+ } from 'reader/discover/helper';
 
 class ReaderPostCardAdapter extends React.Component {
 
 	onClick = ( postToOpen ) => {
-		this.props.handleClick && this.props.handleClick( postToOpen );
+		const propagatePost = { ...postToOpen };
```
Comment (blowery) [inline client/reader/stream/refresh-post.jsx]: could we make this a `let` and only copy the post when we have to?

**Comment by blowery** [comment]
I assume the Visit Site link on both the stream card and the full post view (top right) should also flow through discover.wordpress.com? 

Also, this post is getting the querystring bits, but it appears to be a post on discover itself?
discover_ _reader_ _wordpress_com

**Comment by jhnstn** [comment]
> I assume the Visit Site link on both the stream card and the full post view (top right) should also flow through discover.wordpress.com?

Yeah, I was going to follow up with the one in the stream I missed the one on the full post view. I'll update both

**Comment by jhnstn** [comment]
@blowery the visit link in the stream refresh is a bit more involved. I'm leaning toward a new PR for that. The full post visit link is updated.

**Comment by bluefuton** [comment]
@jhnstn Looks good! 

Can we add some information to the (admittedly very sparse) reader-full-post/README.md about this prop and how it works? And can we add `propTypes` to the `FullPostView` component while we're at it?

**Comment by jhnstn** [comment]
@bluefuton , @blowery I noticed when adding the prop types that we are passing the controller `context` to the full post block but are not using it. 
https://github.com/Automattic/wp-calypso/pull/9858/files#diff-c3091eaa05e597c07a7a8971f1e15c46L49

Any reason we still need that in the block component?

File: client/blocks/reader-full-post/README.md [hunk 7]
```diff
@@ -1,3 +1,19 @@
...
+*required*
+- `blogId`: The blog id for the post
+- `postId`: The post id
+- `onClose`: An onClose event handler function
+- `onPostNotFound` : A Post not found handler function
+
+*optional*
+- `context`: The `page` controller context
+- `referral`: An object containing a `blogId` and `postId`
+
```
Comment (bluefuton) [inline client/blocks/reader-full-post/README.md]: Nice one 👍

File: client/blocks/reader-full-post/README.md [hunk 8]
```diff
@@ -1,3 +1,19 @@
...
+### Referral
+
+The referral object can be used to link the full post view to it's source card in a reader stream. The current usage is to link discover pick cards to the full post view.
```
Comment (bluefuton) [inline client/blocks/reader-full-post/README.md]: it's -> its

File: client/blocks/reader-full-post/index.jsx [hunk 9]
```diff
@@ -71,6 +71,12 @@ export class FullPostView extends React.Component {
 		this.hasScrolledToCommentAnchor = false;
 	}
 
+	static PropTypes = {
```
Comment (jhnstn) [inline client/blocks/reader-full-post/index.jsx]: yup!

**Comment by bluefuton** [comment]
> Any reason we still need that in the block component? Feels like we would be pushing the dependency on page.js ( or at least its context interface ) down to the component if someone does decide to use the context prop

Good point - looks like it's safe to remove. cc @blowery

**Comment by blowery** [comment]
Yeah, I can't think of any reason we still need the context. I'm not sure we ever actually used it.
