### PR TITLE
Stepper: support for siteId and added useAssertConditions

### LINKED ISSUE #62688: Stepper: Throw error when accessing without siteSlug or siteId
Following [this discussion](p1649730525734919-slack-C02T4NVL4JJ), 
we can see that right now in the Stepper you can access the pages without a `siteSlug` or `siteId`, but that results in broken pages (like in the design setup).

That generates some confusion, as it is difficult for someone to tell what's the root of the problem.
In `/start` it is [immediately thrown an error](https://github.com/Automattic/wp-calypso/blob/trunk/client/lib/signup/flow-controller.ts#L149). Could be worth adding that to the stepper, to make things clearer.

### PR DESCRIPTION
**Pull request by escapemanuele**
#### Changes proposed in this Pull Request

Now the stepper works not only with `?siteSlug=site-slug`, but also with `?siteId=site-is`.

Added a new optional property in the Flow, `useAssertConditions`, where we can define some checks to do and throw Error if those are not met. 
It's quite open to customization, one could not throw errors but simply log something, for example.
In our case, it checks for the presence of either `siteSlug` or `siteId`

#### Testing instructions

* checkout the branch
* yarn start
* visit `http://calypso.localhost:3000/stepper/designSetup` and make sure that an error is thrown in the browser console.
* visit other steps (like `intent' or `storeFeatures` and check that the error is there)
* visit the steps with the appropriate query parameter `?siteSlug=YOUR-SITE.wordpress.com` and everything should work as usual
* verify that the design setup step works
* visit the steps with site id as a query parameter `?siteid=4142...` and everything should work as usual.
* if you need an id try with `205343885`, so `http://calypso.localhost:3000/stepper/intent?siteId=205343885`

Related to #62688
Fixes #62688

### CODE REVIEW

**Review by alshakero — APPROVED** [review]
Simple and straightforward. LGTM.

File: client/landing/stepper/declarative-flow/site-setup-flow.ts [hunk 1]
```diff
@@ -194,4 +194,12 @@ export const siteSetupFlow: Flow = {
 
 		return { goNext, goBack, goToStep, submit };
 	},
+
+	useAssertConditions() {
+		const siteSlug = useSiteSlugParam();
+
+		if ( ! siteSlug ) {
```
Comment (roo2) [inline client/landing/stepper/declarative-flow/site-setup-flow.ts]: We will need to support (`siteId` OR `siteSlug`) in the future because when a user purchases a domain in signup, they actually don't have a siteSlug yet and so `siteId` is passed (at least that's how it works in the `/start` flow, @alshakero might know if this flow handles that case in another way?) p1649730710637599-slack-C02T4NVL4JJ

Comment (escapemanuele) [reply client/landing/stepper/declarative-flow/site-setup-flow.ts]: Thanks @roo2, in my last commit I should have addressed the `siteId` support.

**Review by arcangelini — APPROVED** [review]
Amazing job, everything works really well.

The failing test in TeamCity has to do with a Prettier error. I fixed that in this PR #62818 so you should be able to rebase and get all ✅
