### PR TITLE
Ensure site prop is not null

### LINKED ISSUE #95973: Failing to load /sites when navigating from Settings > General
Something is preventing /sites from loading when navigating from Settings General. It looks like siteId is needed but null - this might be something to do with how we keep track of last selected site in the global view but I haven't confirmed.

This is happening in dev, staging, and production environments.

https://github.com/user-attachments/assets/083c74f6-9368-4f6c-8c36-5c4b0e32aa7b

https://github.com/user-attachments/assets/6edcea7d-6eef-4722-949e-9ad1ea275e3b

Note I point out the retry=1 thing in the recording but I don't know if that's relevant, see more details on that [here](https://github.com/Automattic/wp-calypso/blob/428b8cfdc0535e6276df57e6105fe7eaa291891b/client/server/bundler/README.md?plain=1#L65).

### PR DESCRIPTION
**Pull request by lsl**
Fixes https://github.com/Automattic/wp-calypso/issues/95973

## Proposed Changes

Ensures site / siteId is not null before trying to render the settings form. This was occurring during navigation between `/settings/general` and `/sites`. See issue for repro video.

## Testing

- Navigate to Settings > General
- Click the "W" logo to navigate to /sites
- The /sites dashboard should load first time
- There should be no console errors (other than the unrelated warning about "Invalid prop `callToAction`".)

### CODE REVIEW

File: client/my-sites/site-settings/form-general.jsx [hunk 1]
```diff
@@ -601,6 +601,10 @@ export class SiteSettingsFormGeneral extends Component {
 		} );
 		const isDevelopmentSite = Boolean( site?.is_a4a_dev_site );
 
+		if ( ! site ) {
+			return null;
+		}
```
Comment (lsl) [inline client/my-sites/site-settings/form-general.jsx:606]: If anyone knows why this is needed I'd like to know. This "fixes" the problem but I think it's just masking the root cause, why is both site being unset after navigation and the page still trying to render this form?

Comment (okmttdhr) [reply client/my-sites/site-settings/form-general.jsx:606]: I may not be answering the question, but I remember that navigating to /sites triggers a site state reset? Adding a guard for `site=null` could be beneficial in general, similar to the approach used at https://github.com/Automattic/wp-calypso/pull/95981/files#diff-bc79a829db32a21a70056887cf8a6bd4ebce6890c1a8fd3091258dba0610b680R610

**Review by okmttdhr — APPROVED** [review]
Just tested and observed the fix ✅
