### PR TITLE
Redirect /help/courses to wordpress.com/learn/courses

### LINKED ISSUE #59055: [Bug]: Stale content under /help/courses
### Quick summary

The content under `/help/courses` hasn't been updated in a few years, and one of the Youtube videos is no longer available.

### Steps to reproduce

1. Go to wordpress.com/help/courses
2. See the second video is shown as unavailable

### What you expected to happen

I expected to see a valid video.

### What actually happened

The second video shows as unavailable.

### Context

_No response_

### Browser

_No response_

### Simple/Atomic

_No response_

### Other notes

It may make sense to consider redirecting this page to a more current list of courses and/or webinars.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by escapemanuele**
The content in `/help/courses` is stale, so we redirect to `wordpress.com/learn/courses`

## Testing
1. Live link and visit `/help/courses`
2. You should land in `wordpress.com/learn/courses`

Fixes https://github.com/Automattic/wp-calypso/issues/59055

### CODE REVIEW

File: client/server/pages/index.js [hunk 1]
```diff
@@ -832,6 +832,12 @@ function wpcomPages( app ) {
 		const redirectUrl = '/setup/domain-transfer';
 		res.redirect( 301, redirectUrl );
 	} );
+
+	// Redirects from /help/courses to https://wordpress.com/learn/courses.
+	app.get( '/help/courses', function ( req, res ) {
+		const redirectUrl = 'https://wordpress.com/learn/courses';
```
Comment (daledupreez) [inline client/server/pages/index.js:838]: I've just tested this and I think we should use a relative URL instead so we stay within the current environment.
```suggestion
		const redirectUrl = '/learn/courses';
```

**Comment by escapemanuele** [comment]
Thank you @daledupreez, committed your suggestion!

**Review by daledupreez — APPROVED** [review]
I just realised that we don't serve `/learn/courses` via Calypso. 🤦 So maybe we _do_ need the absolute URL after all, @escapemanuele.

I'm happy to approve either way, as both sets of code worked.

**Comment by escapemanuele** [comment]
Yes, you're right. It'd work on wordpress.com, but not work during development.
So, I set it back to use an absolute url 👍
