### PR TITLE
Domains: fix redirect loop when user has one site and lacks manage_option capability

### LINKED ISSUE #2142: Domains: Redirect Loop
If there's a user account with only one site, and the user has Editor permissions on that site;
if the user tries to go to a page that requires admin permissions (`/domains/manage` etc.), this will start a infinite redirect loop.
1. Admin page knows that the user doesn't have the permissions and redirects them to the site selection page.
2. Site selection page know that the user has only one site, and auto-selects it and redirects them to back to the admin page.

There _shouldn't_ be any links shown to the user, so I think this can only happen if the user types to URL to get to the site.

### PR DESCRIPTION
**Pull request by gwwar**
Fixes #2142 where we could get into an infinite redirect loop on the /domains page. This was caused by:
1. The /domains/manage/:site: route handler redirecting to base /domains for site selection
2. site selection automatically occurs, as the user only has a single site
3. user goes back to the site specific url: /domains/manage/:site: and the loop repeats.

## Testing Instructions
1. As an admin on a site, invite a new user to the site with a role less than admin. (For example, editor)
2. Check inbox for invite, complete registration in another browser
3. Navigate to http://calypso.localhost:3000
4. Click on "My Sites"
5. Note that the sidebar does not render plans or domain links
6. Navigate to http://calypso.localhost:3000/plans
7. Page should render fine, but links to domains or email management should not be seen in the header

screen shot 2016-11-12 at 3 54 07 pm

8. Navigate directly to http://calypso.localhost:3000/domains
9. You will be redirected to /stats
10. Switch to the admin user /domains and /plans behaves normally

cc @umurkontaci @lancewillett @lamosty @retrofox @lamosty

### CODE REVIEW

**Comment by klimeryk** [comment]
Thank you so much for fixing this! 🙇 
LGTM - works as advertised, tested all the cases I could think of 👍 
I did find a link to `/domains` on the Plans page :D It's hidden in the popup cart:
screen shot 2016-11-14 at 14 42 29

Of course, that link redirects to stats, as it should :)
I don't see any notice or anything that prevents from adding a plan to cart, though (which fails with a console error, stating that only admins can add upgrades). Nothing serious (since the user should not even see this page), and if anything, can be addressed in a separate PR.

File: client/my-sites/upgrades/navigation.jsx [hunk 1]
```diff
@@ -69,13 +70,13 @@ const PlansNavigation = React.createClass( {
 					<NavItem path={ `/plans/${ site.slug }` } key="plans" selected={ path === '/plans' || path === '/plans/monthly' }>
 						{ this.translate( 'Plans' ) }
 					</NavItem>
-					{ ! isJetpack &&
+					{ ! isJetpack && get( site, 'capabilities.manage_options', false ) &&
```
Comment (gwwar) [inline client/my-sites/upgrades/navigation.jsx]: updated in 828f198

**Comment by gwwar** [comment]
Thanks for the review @klimeryk !
