### PR TITLE
Block Editor: Update the featured image preview after editing the image file

### LINKED ISSUE #29829: Gutenberg: Featured Image not updated when edited on Media Modal
#### Steps to reproduce
1. Open the block editor at /block-editor and select a site under a paid plan (free plans don't allow to edit images in the Media Modal).
2. Set a featured image.
3. Click on the featured media so the Medial Modal is opened.
4. Select the current featured image and click on the Edit button.
5. Push the "Edit Image" button and apply some changes to the image (e.g. flip it).
6. Click on the Done button and insert the modified image.

#### What I expected
The featured image should display the modified image.

#### What happened instead
The featured image displays the previous image.

#### Context / Source
Related: #29791.

### PR DESCRIPTION
**Pull request by Copons**
#### Changes proposed in this Pull Request

* Add the image's `width` and `height` to the update message's payload so that the iframe bridge will be able to recalculate the preview size after the image has been edited.

#### Testing instructions

* Apply D26023-code and sandbox a site.
* Open the Block Editor and add a rectangular image as featured image.
* Click on the featured image preview; the Media Modal will open with the featured image selected.
* Edit the image and rotate it; wait for the new image to be uploaded, when the spinner disappears.
* Close the modal and make sure the featured image has been updated and the preview has the correct size (scaled to fit the sidebar), and that it doesn't overlap any neighbouring elements.

Fixes #29829

### CODE REVIEW

File: client/gutenberg/editor/calypsoify-iframe.jsx [hunk 1]
```diff
@@ -243,9 +243,11 @@ class CalypsoifyIframe extends Component {
 		}
 		const payload = {
 			id: get( action, 'data.ID' ),
-			url: get( action, 'data.URL' ),
-			transientId: get( action, 'id' ),
+			height: get( action, 'data.height' ),
 			status: 'REMOVE_MEDIA_ITEM' === action.type ? 'deleted' : 'updated',
+			transientId: get( action, 'id' ),
+			url: get( action, 'data.URL' ),
+			width: get( action, 'data.width' ),
```
Comment (obenland) [inline client/gutenberg/editor/calypsoify-iframe.jsx]: Thank you for ordering those alphabetically!
