### PR TITLE
Routing: Correctly route to legacy paths with a trailing slash

### LINKED ISSUE #5623: Routes: Legacy routes ending with a trailing `/` don't redirect
First reported in p2UL9c-2GR-p2 by @shawnajean 

#### Steps to reproduce
1. Create a link to a legacy route somewhere in Calypso ending with a trailing slash. The easiest way to do this is to start a chat and send 'https://wordpress.com/themes/affinity/'.
2. Click the link
3. Notice that you're not redirected
4. Refresh Calypso, then try again **without** a trailing slash
5. You should be redirected as expected

There's a redirect happening with trailing slashes, which might be interfering:
screen shot 2016-05-27 at 6 34 49 pm

cc @ebinnion

### PR DESCRIPTION
**Pull request by jordwest**
This fixes #5623 and p2UL9c-2GR-p2.

When a legacy link is clicked - that is one beginning with wordpress.com but not handled by Calypso - we don't want Calypso to handle that URL using pushState, but for the browser to reload that page.

Before this change, any link to a legacy route that contained a trailing slash was being caught by the page module and redirected to the path without the trailing slash.

This meant that a legacy route was considered 'handled' by Calypso and pushed to the browser's history state, instead of letting the browser do its thing.

This change detects legacy links, and skips the internal redirect. This lets the request fall through Calypso's routing mechanism unhandled, allowing the browser to handle it.

### How to test
1. Click around, ensure normal internal routes work as expected.
2. Create a link to a legacy route somewhere in Calypso ending with a trailing slash. The easiest way to do this is to start a chat and send 'https://wordpress.com/themes/affinity/'.
3. Click the link.
4. You should be redirected correctly in this branch, while `master` won't redirect.

cc @ebinnion @blowery

### CODE REVIEW

File: client/boot/index.js [hunk 1]
```diff
@@ -217,6 +218,18 @@ function reduxStoreReady( reduxStore ) {
 		renderLayout( reduxStore );
 	}
 
+	const isLegacyRoute = ( path ) => {
+		return ( /.php$/.test( path ) ||
+			/^\/?$/.test( path ) && ! config.isEnabled( 'reader' ) ||
```
Comment (dmsnell) [inline client/boot/index.js]: Although we thankfully have pretty solid precedence rules, I find these situations really confusing. That is, whenever we have a mix of boolean logic in a sequence. If they are all `||` then it's easy to see that only a single one in the mix has to be true; likewise if they are all `&&` then we know they all need to be true.

What about in `a && b || c`? Does _only_ `c` need to be true or does _either_ `b` or `c` need to be true _with_ `a` being true?

Thus, I usually like to clarify by wrapping different boolean expressions in parenthesis to make the order of evaluation explicit. `a && (b || c)` or `(a && b) || c`

File: client/boot/index.js [hunk 2]
```diff
@@ -217,6 +218,18 @@ function reduxStoreReady( reduxStore ) {
...
+			/^\/my-stats/.test( path ) ||
+			/^\/notifications/.test( path ) ||
+			/^\/themes/.test( path ) ||
+			/^\/manage/.test( path ) ||
+			/^\/plans/.test( path ) && ! config.isEnabled( 'manage/plans' ) ||
+			/^\/me/.test( path ) && ! /^\/me\/billing/.test( path ) &&
+			! /^\/me\/next/.test( path ) && ! config.isEnabled( 'me/my-profile' ) );
+	};
```
Comment (dmsnell) [inline client/boot/index.js]: Of course, with all the repetition here and mixed data and logic, it seems ripe for some helper function…

```js
const notEnabled = feature => () => ! config.isEnabled( feature );

const matchingMePaths = path =>
	! /^\/me\/billing/.test( path ) &&
	! /^\/me\/next/.test( path ) &&
	notEnabled( 'me/my-profile' );

// [ [ path matching Regex, optional predicate condition ] ]
const legacyRoutes = [
	[ /.php&/ ],
	[ /^\/?$/, notEnabled( 'reader' ],
	[ /^\/my-stats/ ],
	[ /^\/notifications/ ],
	[ /^\/themes/ ],
	…
	[ /^\/me/, matchingMePaths ]
];

const isLegacyRoute = path => 
	legacyRoutes.some( ( [ pattern, predicate = constant( true ) ] => pattern.test( path ) && predicate( path ) );
```

**Comment by dmsnell** [comment]
@jordwest I just left a comment noticing that nobody else has. is this still relevant and valid? Might need to rebase against **master** since it's been a while.

**Comment by jordwest** [comment]
Thanks for taking a look @dmsnell! This is still an open issue (#5623)

I've basically just copied and pasted the legacy route matching logic to avoid breaking them, but I agree they're confusing and could do with some refactoring. I'll put together some tests and extract them into a separate file.

**Comment by ebinnion** [comment]
Sorry for the super slow reply. 

@jordwest - Is this still ready for review? I see you mentioned something about testing in your last comment.

**Comment by jordwest** [comment]
This is now ready for review again - I've just finished adding tests and refactoring the boolean logic, with a few changes from the pattern @dmsnell proposed.

**Comment by dmsnell** [comment]
@jordwest I really like what you did with the route and the logic. Very nice!

**Comment by ebinnion** [comment]
This looks good to me. Tests pass which is great. I also tested to make sure that #5623 is handled by this, and it was. 🎉
