### PR TITLE
Don't allow access to domain settings page for free site URLs

### LINKED ISSUE #60358: Domains: DNS records management should not show for free site addresses
### Quick summary

_No response_

### Steps to reproduce

*   On a Free Plan site navigate to `https://wordpress.com/domains/manage/{FREESITEURL}/edit/{FREESITEURL}`
*   Alternatively, go to Upgrades > Domains > three dots next to the free site address > Change site address and then click Back at the top to end up on the same screen

DNS-free-site-address
.

### What you expected to happen

See no DNS records tile since it makes no sense for a free site address, but only for custom domains.

### What actually happened

DNS records tile is displayed and has the Manage button that leads to a page that allows me to add DNS records but throws errors when I try.

https://user-images.githubusercontent.com/39308239/150638284-5913224c-e1e4-43c6-b258-297c8578a3f3.mov

### Context

_No response_

### Simple, Atomic or both?

Simple

### Theme-specific issue?

_No response_

### Browser, operating system and other notes

macOS Monterrey 12.1 with Chrome 97

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by delputnam**
#### Changes proposed in this Pull Request

We should not allow access to the domain settings page when the domain name is a WPCOM url (ex. foo.wordpress.com)

The back button from the "/change-site-address" page would lead to a URL like: `https://wordpress.com/domains/manage/{FREESITEURL}/edit/{SITESLUG}`

This PR fixes the back-button URL for the change site address page and also adds a redirect back to the domain list for the selected site in the case where the `/domains/manage/{FREESITEURL}/edit/{SITESLUG}` is entered manually or for some other reason.

#### Testing instructions

Go to the change site address page for the "free WordPress.com address" from a site list. Click on the back button. Make sure that you are returned to the domains list page.

Manually go to a path like `/domains/manage/{FREESITEURL}/edit/{SITESLUG}`.  Make sure you are redirected back to the domains list page for the site.

Related to #60358

### CODE REVIEW

File: client/my-sites/domains/domain-management/controller.jsx [hunk 1]
```diff
@@ -72,6 +72,17 @@ export default {
 	},
 
 	domainManagementEdit( pageContext, next ) {
+		const selectedDomainName = decodeURIComponentIfValid( pageContext.params.domain );
+		if (
+			selectedDomainName &&
+			( selectedDomainName.endsWith( '.wordpress.com' ) ||
+				selectedDomainName.endsWith( '.wpcomstaging.com' ) )
```
Comment (rafaelgallani) [inline client/my-sites/domains/domain-management/controller.jsx]: It works for both simple and atomic sites, but it doesn't work for free `.blog` subdomains (e.g. `rafagalani.home.blog`).

Maybe moving the logic and adding a `useEffect` function call on the inner `Settings` component could do it:

```javascript
useEffect( () => {
	if ( domain && isFreeUrlDomain( domain ) ) {
		page.redirect( domainManagementList( selectedSite.slug ) );
	}
}, [ domain, selectedSite ] );
```

Some more validations might be necessary, but something like it 😄

**Review by rafaelgallani — CHANGES_REQUESTED** [review]
Confirmed that all the fixes are working, but there is one last case we should be handling too - free `.blog` subdomains. 

Currently, I don't think that there's a way of dealing with them in the controller file, as it wouldn't be possible to differentiate between a `.blog` domain and a free `.blog` subdomain - we would need the domain details and its `type` to validate it. 

I added a comment and a suggestion related to it. Other than that, LGTM 😄

**Comment by delputnam** [comment]
I thought about these too, but wasn't sure it was worth the extra check since they're such a small edge case and you'd now have to manually type the url in to get to the settings page for them (now that the back button is fixed).

File: client/my-sites/domains/domain-management/controller.jsx (hunk 1 above)
Comment (delputnam) [reply client/my-sites/domains/domain-management/controller.jsx]: I'd rather not load the component and the make the endpoint calls necessary to fetch this information just to do a simple redirect.  Better to just use a utility function that looks for these well-known strings.

**Review by rafaelgallani — APPROVED** [review]
LGTM! :shipit:
