### PR TITLE
Store: Update Payment Method Title when changed

### LINKED ISSUE #20217: Store: Payment Title Updates not reflected in UI
#### Steps to reproduce
1. From a Store Settings page http://calypso.localhost:3000/store/settings/STOREDOMAIN, edit or manage any offline payment method.
2. Change the title of the payment method in the dialog, Close the dialog
3. Note the new title is not shown on the Settings page
4. Save the settings
5. Note the new title still is not shown until you hard refresh

#### What I expected
For the new title to be shown.

#### What happened instead
Old title was still shown until a refresh

#### Screenshot / Video
method-name-no-update

### PR DESCRIPTION
**Pull request by timmyc**
Fixes #20217 

Currently when you make a change to a Payment Method title from `/store/settings/SITE` page, the new payment method title is not shown until/if you save and hard refresh the page.

method-name-no-update

__To Test__
- Visit a site settings page, and click "Setup" on the check payment method ( or "Manage" if enabled )
- Change the title of the payment method, and click the "Done" button in the dialog
- Verify the new title is shown on the Settings page

### CODE REVIEW

File: client/extensions/woocommerce/state/ui/payments/methods/test/selectors.js [hunk 1]
```diff
@@ -87,6 +87,23 @@ describe( 'selectors', () => {
 			] );
 		} );
 
+		test( 'should apply the "edits" to title to title attribute and settings value', () => {
```
Comment (budzanowski) [inline client/extensions/woocommerce/state/ui/payments/methods/test/selectors.js]: I think that I am reading this correctly and the two `to title` make sense. Just checking.

**Comment by budzanowski** [comment]
Looks good, tests well.

File: client/extensions/woocommerce/state/ui/payments/methods/test/selectors.js (hunk 1 above)
Comment (timmyc) [reply client/extensions/woocommerce/state/ui/payments/methods/test/selectors.js]: Yeah that wording is a bit funky, I might re-write that sentence. I try to avoid the "to to" thing.
