### PR TITLE
Plugins: Prevent Atomic Sites Installing Incompatible Ones

### LINKED ISSUE #17305: Plugins: Incompatible plugins need to be disabled for Atomic sites in "All My Sites" view
#### Steps to reproduce
0. Make sure you have an Atomic site on your account.
1. Starting at URL: https://wordpress.com/plugins/wp-super-cache
2. Under "Available sites" click the "Install" button on an Atomic site.
3. In the sidebar, select "Switch Site" and choose the same Atomic site.

#### What I expected

I expected that in both places, the ability to install the plugin would be blocked since it's an incompatible plugin.

#### What happened instead

There's an "Install" button next to the Atomic site on the plugin's page with the "All My Sites" view (no specific site selected). Selecting it returns the error "An error occurred while installing WP Super Cache."

Installing the plugin is blocked (as expected) when you select the Atomic site in the sidebar. Under the plugin description there, you'll see a yellow warning "Incompatible plugin: This plugin is not supported on WordPress.com." There's no option to install the plugin from there.

#### Browser / OS version

Chrome 60.0.3112.101 / Mac OSX 10.12.6

#### Screenshot / Video

"All My Sites" view:

screen shot 2017-08-17 at 5 46 29 pm

Atomic site selected:

screen shot 2017-08-17 at 5 45 11 pm

#### Context / Source
#manual-testing

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

Firstly, this creates a separate file for the list of incompatible plugins, so it can be used in multiple files. 

It also prevents incompatible ones being installed on WP.com Atomic sites on the "All My Sites" view, since that was causing a series of bugs as mentioned in the initial issue.

Screenshot 2020-01-22 at 19 18 02

#### Testing instructions

1. Ensure you have a WP.com atomic site 
2. Visit `/plugins/wp-super-cache` (example of an incompatible plugin) and verify that you **can't** install it on your WP.com atomic site
3. Visit `/plugins/woocommerce` (example of a compatible plugin) and verify that you **can** install it on your WP.com atomic site

The wording is similar to the error that appears when you visit the plugin page on a single-site view. If you'd like, you can verify this still appears, since that now uses the list created in this PR.

Screenshot 2020-01-22 at 19 44 36 

Fixes #17305

### CODE REVIEW

File: client/my-sites/plugins/plugin-install-button/index.jsx [hunk 1]
```diff
@@ -195,6 +199,38 @@ export class PluginInstallButton extends Component {
...
+				</span>
+				<InfoPopover
+					position="bottom left"
+					popoverName={ 'Plugin Action Disabled Install' }
+					gaEventCategory="Plugins"
+					ref="infoPopover"
+					ignoreContext={ this.refs && this.refs.disabledInfoLabel }
+				>
+					<div>
+						<p>{ translate( 'This plugin is not supported on WordPress.com.' ) }</p>
```
Comment (a8ci18n) [inline client/my-sites/plugins/plugin-install-button/index.jsx]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **22** times:
`translate( 'Incompatible plugin: This plugin is not supported on WordPress.com.' )` *ES Score: 6*

File: client/my-sites/plugins/plugin-install-button/index.jsx [hunk 2]
```diff
@@ -195,6 +199,38 @@ export class PluginInstallButton extends Component {
...
+					onClick={ this.togglePopover }
+					ref="disabledInfoLabel"
+					className="plugin-install-button__warning"
+				>
+					{ translate( 'Incompatible Plugin' ) }
+				</span>
+				<InfoPopover
+					position="bottom left"
+					popoverName={ 'Plugin Action Disabled Install' }
+					gaEventCategory="Plugins"
```
Comment (Aurorum) [inline client/my-sites/plugins/plugin-install-button/index.jsx]: I should probably note, since I don't understand them well, that these are the same as the unreachable notice: https://github.com/Automattic/wp-calypso/blob/804f0eac3a288ec978eed2989a027bdf7ac6e911/client/my-sites/plugins/plugin-install-button/index.jsx#L178-L184

**Comment by tyxla** [comment]
cc @brandonpayton - perhaps it makes sense for someone from the Atomic team to take a look at this one?

File: client/my-sites/plugins/incompatible-plugins.js [hunk 3]
```diff
@@ -0,0 +1,136 @@
...
+ * This is a list of plugins not supported on WordPress.com Atomic sites.
+ *
+ * If this list is modified, please ensure that the support document also reflects
+ * any changes made:
+ *  - https://en.support.wordpress.com/incompatible-plugins
+ *
+ * Please keep this list alphabetized within the different categories!
+ */
+
+export const IncompatiblePlugins = [
```
Comment (brandonpayton) [inline client/my-sites/plugins/incompatible-plugins.js]: I think `IncompatiblePlugins` should probably be lower-cased.

Since we are conceptually treating this as a set, we can go ahead and make it a real [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set).

```javascript
const incompatiblePlugins = new Set( [
  // ...
] );
```

And since all the consumers of this module are simply checking whether something is included in the set, maybe we should export an `isIncompatiblePlugin()` function instead of the data structure we're using to represent the set.

Further, to avoid the awkwardness and confusion of using is-negative function (confusing when negating the result like `! isIncompatiblePlugin()`), maybe we should rename this module to `plugin-compatibility.js` and export an `isCompatiblePlugin()` function.

File: client/my-sites/plugins/plugin-install-button/index.jsx [hunk 4]
```diff
@@ -261,12 +297,16 @@ export class PluginInstallButton extends Component {
...
 
 	renderNoticeOrButton() {
-		const { selectedSite, siteIsConnected } = this.props;
+		const { isWpcomAtomicSite, plugin, selectedSite, siteIsConnected } = this.props;
 
 		if ( siteIsConnected === false ) {
 			return this.renderUnreachableNotice();
 		}
 
+		if ( includes( IncompatiblePlugins, plugin.slug ) && isWpcomAtomicSite ) {
```
Comment (brandonpayton) [inline client/my-sites/plugins/plugin-install-button/index.jsx]: Assuming that we will provide an `isCompatiblePlugin()` function, this doesn't matter, but in general, we don't need lodash in this case. We can just use the native [Array#includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) function like `IncompatiblePlugins.includes( plugin.slug )`.

File: client/my-sites/plugins/plugin-install-button/index.jsx [hunk 5]
```diff
@@ -302,6 +342,7 @@ export default connect(
 		return {
 			siteId,
 			siteIsConnected: getSiteConnectionStatus( state, siteId ),
+			isWpcomAtomicSite: isSiteWpcomAtomic( state, siteId ),
```
Comment (brandonpayton) [inline client/my-sites/plugins/plugin-install-button/index.jsx]: Similar to `siteIsConnected` on the line above, naming this `siteIsWpcomAtomic` would make the prop sound less like a function that answers a question.

**Review by brandonpayton — CHANGES_REQUESTED** [review]
Hi @Aurorum, thanks for your contribution! I haven't tested yet, but the changes generally look good. I left a few review comments, and after those are addressed, I can look a bit closer and test.

File: client/my-sites/plugins/plugin-install-button/index.jsx (hunk 4 above)
Comment (Aurorum) [reply client/my-sites/plugins/plugin-install-button/index.jsx]: Hi! I've tried turning it into a Set as you suggested, however I've been struggling to get the function to work, being unable to check the plugin slug. When trying to use the includes as suggested (`incompatiblePlugins.includes( this.props.plugin.slug )`), I'm getting this error:

Screenshot 2020-02-03 at 17 58 38

I wonder if you could please advise where I'm going wrong? :)

Comment (brandonpayton) [reply client/my-sites/plugins/plugin-install-button/index.jsx]: Hi @Aurorum,

I'm sorry. I see how my comment could be confusing. This comment doesn't matter if you follow the advice in my [previous comment](https://github.com/Automattic/wp-calypso/pull/39020#discussion_r373077195) because you'll be calling an `isCompatiblePlugin()` function here instead of working directly with an Array (or Set).

My intent was simply to point out that the `Array#includes` method should probably be used instead of lodash's `includes()` function because it is a native part of the Array API and allows us to reduce our dependency on lodash. In general, if we can do without a dependency while writing similar code, we prefer to do without because dependencies increase the size of the JS bundles we send to the browser.

If you are in an intermediate place where you have converted `incompatiblePlugins` to a `Set` but are still exporting `incompatiblePlugins` and not an `isCompatiblePlugin()` function, the `includes()` method is not provided by `Set`. Instead, you can use the [Set#has()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/has) method like `IncompatiblePlugins.has( plugin.slug )`.

Does that clear things up?

Comment (Aurorum) [reply client/my-sites/plugins/plugin-install-button/index.jsx]: Thank you, it does! Sorry, last question: I've been toying around a lot with trying to make the function you referenced work, and I've been searching through Calypso on a way to get the plugin slug. I've been unable to find anything though, so whilst everything else works, the main logic on `if the slug has something in the set` doesn't, since I'm not sure how to get the slug. Any ideas? :)

Comment (brandonpayton) [reply client/my-sites/plugins/plugin-install-button/index.jsx]: Ah, this is again a place where I could have been clearer. The `isCompatiblePlugin` function should take a slug argument like `isCompatiblePlugin( pluginSlug )`. When I mentioned `isCompatiblePlugin()`, I meant the parentheses to indicate it is a function, but I didn't mean to indicate the function should take no arguments. I'm sorry for the confusion.

If you're asking where the React components in this PR get the plugin slug, it looks like it is part of the `plugin` prop they are receiving (i.e. `this.props.plugin.slug`).

Does that answer your question?

Comment (Aurorum) [reply client/my-sites/plugins/plugin-install-button/index.jsx]: Yes, thank you very much! I believe that this PR should now be working with the ideal function, and is ready for review again. :)

**Review by brandonpayton — CHANGES_REQUESTED** [review]
Hi, I reviewed the code and tested, and this looks really close. I requested one more change related to previous review comments.

**Comment by brandonpayton** [comment]
Do you think the text added here is stable? If so, I can add the "String Freeze" label so we can get the new text translated.

File: client/my-sites/plugins/plugin-compatibility.js [hunk 6]
```diff
@@ -0,0 +1,140 @@
...
+ *
+ * If this list is modified, please ensure that the support document also reflects
+ * any changes made:
+ *  - https://en.support.wordpress.com/incompatible-plugins
+ *
+ * Please keep this list alphabetized within the different categories!
+ */
+
+export function isCompatiblePlugin( pluginSlug ) {
+	const incompatiblePlugins = [
```
[the remark this answers is not in the document]
Comment (Aurorum) [reply client/my-sites/plugins/plugin-compatibility.js]: I completely forgot to change it to a Set, oops 😅 Should be fixed now! :)

**Comment by Aurorum** [comment]
I'm assuming you're referring to if there's any intention to change the text, in which case, I don't think so; this phrasing should be adequate and it's consistent with what's used elsewhere. :)

**Review by brandonpayton — APPROVED** [review]
This looks good to me, and it tested well with compatible and incompatible plugins for:
- All sites view
- Business plan site without a plugin installed
- Business plan site with plugins installed. Single plugin view redirects to wp-admin which is outside the scope of this PR, but such sites show as expected in All Sites view.
- External Jetpack site
- Site with a lower plan tier than Business plan

Thank you!

**Comment by brandonpayton** [comment]
Hi @Aurorum, it looks like it should be about a week until the new strings are fully translated. Let's wait for those and tentatively plan to merge at the middle of next week.

**Comment by Aurorum** [comment]
Sounds good, thanks @brandonpayton! :)

**Comment by brandonpayton** [comment]
Hi @Aurorum, it looks like your strings weren't picked up for translation for some reason. Are you up for rebasing on master and pushing to this branch? Maybe we can trigger the ci/i18n test to rerun.

cc @akirk

**Comment by Aurorum** [comment]
I *think* I've done that correctly (though my previous experience of trying this has not been great...)

**Comment by brandonpayton** [comment]
Hi @Aurorum, it looks like an unintentional commit made it into your last push. I just rebased and force pushed. Hopefully that is OK for you and fixes the issue. The tests are running again now.

**Comment by Aurorum** [comment]
Thanks @brandonpayton! :)

**Comment by brandonpayton** [comment]
you're welcome :)  It looks like the tests passed, and the "ci/i18n" check shows untranslated strings again. Hopefully, we made it in time so the strings can be sent for translation this week.

**Comment by akirk** [comment]
We always have some trouble if you change strings when the String Freeze label has already been applied. For some reason the strings didn't make it into GlotPress yet, so I'll have to nudge it manually. Please try and only apply the label when the strings won't change anymore. Thanks!

**Comment by brandonpayton** [comment]
> We always have some trouble if you change strings when the String Freeze label has already been applied. For some reason the strings didn't make it into GlotPress yet, so I'll have to nudge it manually. Please try and only apply the label when the strings won't change anymore. Thanks!

Hi @akirk, I'm not aware of the strings changing after we applied the freeze label. We had a problem with ci/i18n showing 0 strings. IIRC, no tests showed failures so I rebased and pushed to try triggering an update to get things in a better state. I'm not sure why ci/i18n was showing no strings initially.

**Comment by brandonpayton** [comment]
Thank you for nudging GlotPress manually 🙇‍♂️

**Comment by Aurorum** [comment]
Hi all, just a gentle nudge on if this should still be merged. :)

**Comment by bluefuton** [comment]
👋  @brandonpayton are you happy for this one to be merged?

**Comment by brandonpayton** [comment]
yep, this was on my list to get back to. Sorry for the wait, @Aurorum. I'll look at merging this today.

**Comment by brandonpayton** [comment]
There were i18n strings I thought would get translated after a week or so, but this turned out to require manual attention from Team Global.

**Comment by brandonpayton** [comment]
This is now deployed on WordPress.com. Thanks, @Aurorum!

**Comment by Aurorum** [comment]
Thank you!

File: client/my-sites/plugins/plugin-meta/index.jsx [hunk 7]
```diff
@@ -228,151 +229,16 @@ export class PluginMeta extends Component {
...
-
-		return includes( unsupportedPlugins, plugin.slug );
-	}
-
 	isWpcomInstallDisabled() {
-		const { isTransfering } = this.props;
+		const { isTransfering, plugin } = this.props;
 
-		return ! this.hasBusinessPlan() || this.isUnsupportedPluginForAT() || isTransfering;
+		return ! this.hasBusinessPlan() || ! isCompatiblePlugin( plugin.slug ) || isTransfering;
```
Comment (retrofox) [inline client/my-sites/plugins/plugin-meta/index.jsx:235]: There is a typo here: `isTransfering` should be `isTransferring`. Working on this in a new PR. cc @Aurorum
