### PR TITLE
Store: Disable save button while images are uploading

### LINKED ISSUE #21474: Store: Save Button Enabled While Image Is Uploading
When creating a new product or product category, the save button is enabled/clickable while the associated images are uploading. This results in the category or product being created without the new media item being attached to it.

#### Steps to reproduce
1. Either visit the add product or product category page
2. Add data to the form ( title description )
3. Select an Image to upload, larger size helps reproduce the failure
4. While the image is uploading, click the "Save" button

#### What I expected
I think in this scenario, if an upload is in-progress, we should consider disabling the save button - or that some redux magic would take care of assigning the media to the product or category.

#### What happened instead
The image was not attached to the product category

When I discovered this issue in product categories, the following warning was also displayed:

warning-after-save-redirect

### PR DESCRIPTION
**Pull request by justinshreve**
Fixes #21474.

This PR disables the save button on both the product categories form and the product form. It also fixes the warning that can occur if you navigate away when an upload is in process.

For products, since there can be any number of image upload components (one per variation, and the parent) -- I track an array of uploads in progress and when all of them are removed, this save button is re-enabled. For product categories, this logic is a bit simpler since you can only have one image.

I'm hoping some of this is temporary and we can work on integrating the Calypso media modal experience instead in the future (#21302), but this helps fix a few buglets.

To Test:
* Go to the product category add new form and type in a title. Make sure that the save button becomes active. Upload an image and watch the button deactivate while the upload is in process, and reactivate again once it's done.
* Start another upload and then navigate away to the category listing page. Wait a few moments and verify that the warning mentioned in #21474 doesn't occur.
* Repeat step 1 in the edit context.
* Go to products add screen, add a title, and upload an image or two and verify the button updates correctly.
* Create two variations and upload an image for each and verify the button state.
* Repeat the above product steps in the edit context.

### CODE REVIEW

File: client/extensions/woocommerce/app/product-categories/form.js [hunk 1]
```diff
@@ -34,6 +34,8 @@ class ProductCategoryForm extends Component {
 			id: PropTypes.isRequired,
 		} ),
 		editProductCategory: PropTypes.func.isRequired,
+		onUploadStart: PropTypes.func,
```
Comment (timmyc) [inline client/extensions/woocommerce/app/product-categories/form.js]: Should these be `isRequired`? Looks the same for other components where the new props are introduced too.

**Comment by justinshreve** [comment]
I updated my PropTypes. Good call.

I think the busy state on the save button could be a little confusing since that is already used to indicate the entire form is saving but I'm open to implementing whatever!

**Comment by jameskoster** [comment]
> /cc @kellychoffman and @jameskoster to check out the button state as an image is uploading still.

Looks fine to me!

**Comment by kellychoffman** [comment]
Disabled button looks groovy.
