### PR TITLE
Sharing: Fix sharing buttons options saving failures

### LINKED ISSUE #22811: Sharing: changes do not get saved if you toggle all of the "Show sharing buttons on" options from checked to unchecked [2]
Steps to reproduce:

1. Go to My Sites > Sharing > Sharing buttons.
1. Find the "Options" section.
1. Uncheck everything under "Show sharing buttons on."
1. Click the "Save Changes" button.

<strong>Result:</strong> if you toggle all of the "Show sharing buttons on" options from checked to unchecked, changes do not get saved.

<strong>Video:</strong> [36s](https://cloudup.com/cDV0HOIGMTq)

screen shot 2018-02-26 at mon feb 26 9 19 50 am
<sup>Seen at https://wordpress.com/sharing/buttons/design5279.wordpress.com (production) using Firefox 58.0.2 on macOS 10.13.3.</sup>

Aside: this bug is really strange, some combinations of saving changes work and some don't. ([4m12s](https://cloudup.com/cP4ZBdt-Eaa))

/hat tip 🤠 @cecoates because a related bug posted in the #triage channel led me to find this bug!

### PR DESCRIPTION
**Pull request by Copons**
#### Changes proposed in this Pull Request

* Only show `public` post types, which are those that are actually saved by the back end (see D26674-code).
* Always POST the multi-checkbox values array, even if empty, as the intersection happens in the back-end. (Currently, if the array is empty, we send `null`, which eventually gets skipped.)
* These options are largely broken on Jetpack < 7.3 (where Automattic/jetpack#11981 will be merged). This PR also adds a version check and on lower versions shows a "Visit WP Admin" banner instead.

#### Testing instructions

* Apply D26674-code, and sandbox the API.
* Open `/marketing/sharing-buttons`.
* Make sure it only shows the `public` post types. (See example screenshots)
* Try saving: all the options, none of the options, some options.
* Try reloading between each save to make sure the options are really updated
* Switch to a Jetpack site.
* Make sure the sharing options are not shown, and instead there is a "Visit WP Admin" banner at the bottom of the section that opens `options-general.php?page=sharing`.

| Correct | Incorrect |
| - | - |
| Screenshot 2019-04-08 at 15 13 22 | Screenshot 2019-04-08 at 15 13 10 |

Fixes #22811

### CODE REVIEW

**Comment by obenland** [comment]
Can I change the outcome of a review here? :)
I just noticed that Jetpack sites don't have post or page post types displayed

**Comment by obenland** [comment]
It looks like post types from Jetpack sites don't get the `public` attribute added

**Comment by Copons** [comment]
@obenland good catch, I totally forgot that endpoints are on Fusion 🤦‍♂️ .
I'll close the WPCOM diff and proceed through JP, which means this fix will take a while to land (next release is scheduled for May 7).

**Comment by Copons** [comment]
@obenland FYI I've opened https://github.com/Automattic/jetpack/pull/11981, which automagically created D26674-code. They should cover all our site types now.

**Comment by Copons** [comment]
After a bit of thoughts, I'd like ship this (after merging the WPCOM diff) regardless of JP.
It doesn't really make sense to check for JP version to be up to date here, because right now it doesn't work anyway.
Shipping this without the back-end change would mean showing a very limited Sharing Options list:
Screenshot 2019-04-16 at 10 58 13
But, that is also the only element that would be saved correctly in any case.
Other options are at risk of not being saved.

Alternatively, we could do one of the following:
- Add a link to the wp-admin sharing settings, something like: "[You can find more options in the WP Admin dashboard](/wp-admin/options-general.php?page=sharing)".
- Have more checks in place and prevent displaying the entire Options section if no elements inside are supported (e.g. the "show on" would only be supported on WPCOM or JP>7.3, etc.).

These would probably require more thought, editorial involvement, and generally more changes, and so we should do it in a follow up PR.

**Comment by codebykat** [comment]
Just a drive-by -- Personally I'm in favor of doing version detection on JP and linking back to the Jetpack wp-admin for those cases, and also hiding the options if they're going to be broken or incomplete.

**Comment by Copons** [comment]
I've updated this by hiding the sharing buttons options on JP < 7.3 (which is the next version, scheduled for May 7), and showing a "Visit WP Admin" banner instead.

File: client/my-sites/marketing/buttons/options.jsx [hunk 1]
```diff
@@ -195,43 +196,72 @@ class SharingButtonsOptions extends Component {
...
-							disabled={ ! initialized }
-						/>
-					</fieldset>
-					{ this.getCommentLikesOptionElement() }
-					{ this.getTwitterViaOptionElement() }
-				</div>
+			<Banner
+				className="sharing-buttons__banner"
+				href={ `${ siteAdminUrl }options-general.php?page=sharing` }
+				title={ translate( 'Visit WP Admin for more sharing buttons options.' ) }
```
Comment (codebykat) [inline client/my-sites/marketing/buttons/options.jsx]: Small question -- I don't actually know the answer to this, but is there a standard way of referring to a site's wp-admin to users? Didn't we used to call it the dashboard or something?

Comment (Copons) [reply client/my-sites/marketing/buttons/options.jsx]: I had the same doubt and just ran a simple search across the repo, and it's mentioned as "WP Admin" in several occasions, for example, in the link at the bottom of the sidebar.
