### PR TITLE
People: fix 'viewers' tab for invites.

### LINKED ISSUE #22865: People: Viewers tab is not visible on private site in invites section
screen shot 2018-02-27 at 1 56 49 pm

screen shot 2018-02-27 at 1 57 58 pm

1. Make your site private
2. Navigate to https://wordpress.com/people/invites/{yoursiteslug}
3. Verify that the Viewers tab is not visible
4. Switch to another subtab like followers

### PR DESCRIPTION
**Pull request by michaeldcain**
Fixes #22865.

36757369-3dd58852-1bc6-11e8-92c1-5f2ad111156f

**To test:**
- For a private site with viewers, the 'Viewers' filter should be available in all tabs of the People section
- ~~For a private Jetpack site, there should not be a 'Viewers' filter in the People section~~
- For a public site, there should not be a 'Viewers' filter in the People section

### CODE REVIEW

**Comment by mattsherman** [comment]
> For a private Jetpack site, there should not be a 'Viewers' filter in the People section

@michaeldcain How does one create a private Jetpack site?

File: client/my-sites/people/people-invites/index.jsx [hunk 1]
```diff
@@ -64,14 +66,19 @@ class PeopleInvites extends React.PureComponent {
...
-		const { site } = this.props;
+		const { site, isJetpack, isPrivate } = this.props;
 		const siteId = site && site.ID;
 
 		return (
 			<Main className="people-invites">
 				{ siteId && <QuerySiteInvites siteId={ siteId } /> }
 				<SidebarNavigation />
-				<PeopleSectionNav filter="invites" site={ site } />
+				<PeopleSectionNav
```
Comment (mattsherman) [inline client/my-sites/people/people-invites/index.jsx]: We should also have `jetpackPeopleSupported` here for completeness (it really should be a blackbox to us as to what this prop controls). As done in

https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/people/main.jsx#L106

**Comment by michaeldcain** [comment]
>How does one create a private Jetpack site?

@mattsherman My mistake, this isn't possible - I was just reading the conditional. I've added the other prop. We should be ready for re-review.
