### PR TITLE
Upgrades: Fix Activity Log banner on Atomic sites

### LINKED ISSUE #51585: Free Atomic: Activity Log Banner
Activity Log is different based on their plan. We need to ensure that after they purchase Yoast and are migrated to Atomic infrastructure that the view and upgrade options are maintained.

### What plan tier is the site on?
Free

### Where are you seeing the issue?
/activity-log/site

#### What I expected on the Atomic site

image

#### What actually happened
image

#### Is this specific to the applied theme? Which one?
no

### PR DESCRIPTION
**Pull request by mmtr**
#### Changes proposed in this Pull Request

* Renders the WP.com upgrade banner of the Activity Log feature for Atomic sites on a Free plan.
* Removes the "Suggested" label from plans that cannot be purchased.
* Removes the highlighted features from plans that cannot be purchased.
* Defaults to "Business sites and online stores" plans if the Personal plan cannot be purchased.

Before | After
--- | ---
Screen Shot 2021-05-25 at 15 38 16 | Screen Shot 2021-05-25 at 15 38 22
Screen Shot 2021-05-25 at 15 37 53 | Screen Shot 2021-05-25 at 15 43 51

#### Testing instructions

* Switch to an Atomic site on a Free plan.
* Go to Jetpack > Activity log.
* Make sure you have not dismissed the Activity Log intro banner. If you have done so, you can make it to appear again by removing the `dismissible-card-activity-introduction-banner` Calypso preference: Screen Shot 2021-05-26 at 13 01 02
* Click on "Upgrade now".
* Make sure you're redirected to the Plans page with the "Business sites and online stores" option selected.
* Click on "Blogs and personal sites".
* Make sure the Personal plan does not have the "Suggested" label.
* Make sure the "Jetpack essential features" items are not highlighted.
* Go back to Jetpack > Activity log.
* Make sure the WP.com upgrade bander (the one with a star as icon) gets rendered.
* Click on "Learn more".
* Make sure you're redirected to the Plans page with the "Business sites and online stores" option selected.

Fixes https://github.com/Automattic/wp-calypso/issues/51585

### CODE REVIEW

**Comment by allilevine** [comment]
This tests well and also fixes the upsell styles for https://github.com/Automattic/wp-calypso/issues/51828, thanks for pointing that out! I just have some questions:

- Is it worth adding a helper to check when we're on a free Atomic site, rather than checking `isAtomic`? I guess on a Business or E-commerce plan we wouldn't see these banners anyway, but for Google Analytics we currently show a different form for Jetpack / Atomic vs. Simple. 
- There's an issue to change the Atomic Plans page to look like the one for Simple: https://github.com/Automattic/wp-calypso/issues/51823 Would that resolve the Plans bugs you're fixing here?
- I'm seeing a second banner at the top of the Activity log that links to Jetpack checkout:
Screen Shot 2021-05-25 at 2 24 58 PM
Should we change that one to link to Plans too?

File: client/blocks/upsell-nudge/index.jsx [hunk 1]
```diff
@@ -29,6 +29,7 @@ import isVipSite from 'calypso/state/selectors/is-vip-site';
 import { getSelectedSiteId, getSelectedSiteSlug } from 'calypso/state/ui/selectors';
 import { getSite, isJetpackSite } from 'calypso/state/sites/selectors';
 import isSiteWPForTeams from 'calypso/state/selectors/is-site-wpforteams';
+import isSiteWpcomAtomic from 'calypso/state/selectors/is-site-wpcom-atomic';
```
Comment (retrofox) [inline client/blocks/upsell-nudge/index.jsx]: why do you use `is-site-wpcom-atomic` instead of `is-site-automated-transfer`?

**Comment by mmtr** [comment]
> Is it worth adding a helper to check when we're on a free Atomic site, rather than checking isAtomic? 

It shouldn't be needed, at least on the upsell nudges. The `UpsellNudge` component (which is what `UpgradeBanner` renders) already checks if the current plan of the site contains the feature we want to upsell: https://github.com/Automattic/wp-calypso/blob/db584fece8fe1a99cb1429f44b34f78d4fe10226/client/blocks/upsell-nudge/index.jsx#L83

> There's an issue to change the Atomic Plans page to look like the one for Simple: #51823 Would that resolve the Plans bugs you're fixing here?

It seems so! Once that issue is solved, all plans should be available for purchase on Atomic sites, so we wouldn't need to check the `availableForPurchase` property for removing the suggested label and the highlighted features.

> I'm seeing a second banner at the top of the Activity log that links to Jetpack checkout:

Good catch, that's part of a dismissible banner that I didn't see because I dismissed in the past. Should've been fixed in 641ee48.

File: client/blocks/upsell-nudge/index.jsx (hunk 1 above)
Comment (mmtr) [reply client/blocks/upsell-nudge/index.jsx]: What's the differences between them? I didn't know about `is-site-automated-transfer` so that's why I used `is-site-wpcom-atomic`. It's also the selector used for determining if a site can be upgraded to a given plan: https://github.com/Automattic/wp-calypso/blob/db584fece8fe1a99cb1429f44b34f78d4fe10226/client/state/selectors/can-upgrade-to-plan.js#L20

Comment (mmtr) [reply client/blocks/upsell-nudge/index.jsx]: Interestingly, `is-site-automated-transfer` is also used there 😅 

https://github.com/Automattic/wp-calypso/blob/db584fece8fe1a99cb1429f44b34f78d4fe10226/client/state/selectors/can-upgrade-to-plan.js#L19-L20

Seems that the differences between the selectors are tied to the differences between Atomic v1 and v2? See https://github.com/Automattic/wp-calypso/pull/32544.

Now I wonder which one we should use.

Comment (retrofox) [reply client/blocks/upsell-nudge/index.jsx]: > Now I wonder which one we should use.

yes, that's why I asked. I did a quick search and it seems that the automated transfer selected is more used compared with the atomic one. :-/

Comment (mmtr) [reply client/blocks/upsell-nudge/index.jsx]: According to https://github.com/Automattic/wp-calypso/pull/32544, it seems that `isSiteAutomatedTransfer` returns true for both Atomic v1 and Atomic v2 sites, while `isSiteWpcomAtomic` only returns true for Atomic v2 sites.

I guess we should use `isSiteAutomatedTransfer`  then. Changed in 342baab

**Review by cpapazoglou — APPROVED** [review]
Followed the testing instructions and works as advertised.

**Comment by allilevine** [comment]
> It shouldn't be needed, at least on the upsell nudges. The `UpsellNudge` component (which is what `UpgradeBanner` renders) already checks if the current plan of the site contains the feature we want to upsell:

I'm finding that because the current plan for free Atomic is `jetpack_free`, the checks for certain Jetpack features (e.g. SEO Tools) are returning `true`. I took a stab at a helper in https://github.com/Automattic/wp-calypso/pull/53196

> It seems so! Once that issue is solved, all plans should be available for purchase on Atomic sites, so we wouldn't need to check the `availableForPurchase` property for removing the suggested label and the highlighted features.

Nice! We're running into a similar `jetpack_free` issue with that one, discussion here: p1622033207381300/1622032174.378100-slack-C01V2184KHD

> Good catch, that's part of a dismissible banner that I didn't see because I dismissed in the past. Should've been fixed in [641ee48](https://github.com/Automattic/wp-calypso/commit/641ee48d66ce2fbc3932ce45591831e01635e541).

It's fixed! 🙌 Thanks!
