### PR TITLE
Site picker: Disable the icon and dropdown when only 1 site available

### LINKED ISSUE #9895: Primary site picker when user has only one site
I am opening this as a bug, but you could consider this also a question, because I am not sure what the intended behaviour is.

#### Prerequisite
Having a WordPress account to which only one site is associated.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/account
2. Open the dropdown that permits to select the Primary site.

It's a quote from @mtias, [here](https://github.com/Automattic/wp-calypso/pull/9754#issuecomment-265433211) .

#### What happened instead
The dropdown works as there were multiple sites.
If I select the only site in the dropdown the next time I open the dropdown it appears empty.

#### Screenshot / Video

* The dropdown works as there were multiple sites.

toggle

* If I select the only site in the dropdown the next time I open the dropdown it appears empty.

difference

#### Context / Source
I stumbled on this while working on the pull request #9754, that is an attempt to uniform the usage of `siteId` over `siteSlug` as preferred method to identify internally a site.
I've written test cases on the basis of the current working of the component in production.
@mtias suggested that probably in this case there was a regression at some point.

Maybe @ebinnion, who introduced sites-dropdown in me/account/main.jsx, when it was still named me/account/index.jsx ([history ref](https://github.com/Automattic/wp-calypso/commit/5138ea7bc18a4435c7a27e6190f016020b8dedeb)), can help us here to remember the original intended behaviour.

### PR DESCRIPTION
**Pull request by coreymckrill**
Adds a `siteCount` property to SiteDropdown and only enables the
dropdown site list functionality when multiple sites are available.

Adds tests for cases with only one available site and with multiple
sites.

Refs #9895

**Screenshots**

Before

before1

before2

After

after1

**To test:**

* Log in with an account that only has one associated site.
* Navigate to `me/account`
* Try hovering on and clicking on the Primary Site control.
* Expected: Nothing should happen. There should not be a chevron icon on the right side of the control.

* Log in with an account with multiple associated sites.
* Navigate to `me/account`
* Try hovering on and clicking on the Primary Site control.
* Expected: The sites dropdown should expand as usual. The chevron icon should be present on the right side of the control.

### CODE REVIEW

File: client/components/sites-dropdown/index.jsx [hunk 1]
```diff
@@ -104,5 +114,6 @@ export class SitesDropdown extends PureComponent {
 export default connect(
 	( state ) => ( {
 		primarySiteId: getPrimarySiteId( state ),
+		siteCount: get( getCurrentUser( state ), 'site_count', 0 )
```
Comment (gziolo) [inline client/components/sites-dropdown/index.jsx]: As we discussed, it would be nice to do a simple refactoring and pass down to the component `hasMultipleSites` boolean flag to avoid several code calls like `this.props.siteCount > 1`.

File: client/components/sites-dropdown/test/index.js [hunk 2]
```diff
@@ -32,18 +32,30 @@ describe( 'index', function() {
...
 		it( 'should render a dropdown component initially closed', function() {
 			const sitesDropdown = shallow( <SitesDropdown /> );
-			expect( sitesDropdown.hasClass( 'sites-dropdown' ) ).to.be.true;
-			expect( sitesDropdown.hasClass( 'is-open' ) ).to.be.false;
+			expect( sitesDropdown.hasClass( 'sites-dropdown' ) ).to.equal( true );
+			expect( sitesDropdown.hasClass( 'is-open' ) ).to.equal( false );
 		} );
 
-		it( 'should toggle the dropdown, when it is clicked', function() {
+		it( 'with multiple sites, should toggle the dropdown when it is clicked', function() {
```
Comment (gziolo) [inline client/components/sites-dropdown/test/index.js]: I like those tests, I think it is enough to make sure we provide different visual state depending on the number of sites.

**Comment by gziolo** [comment]
Code looks good to me. I tested using provided instructions and it works as advertised. It would be great to got thumbs up from @mtias or @rickybanister as it touches the most important piece of Calypso :)

File: client/components/sites-dropdown/index.jsx [hunk 3]
```diff
@@ -104,5 +114,6 @@ export class SitesDropdown extends PureComponent {
 export default connect(
 	( state ) => ( {
 		primarySiteId: getPrimarySiteId( state ),
+		hasMultipleSites: get( getCurrentUser( state ), 'site_count', 1 ) > 1
```
Comment (gziolo) [inline client/components/sites-dropdown/index.jsx]: Thanks for introducing this change 👍

**Comment by folletto** [comment]
Design wise it's good. 

It could probably even lose the "button" border, as it's not active anymore, but for that we should probably review it in all the various contexts it appears on.

**Comment by rickybanister** [comment]
I'm only basing this feedback on the screenshots—but I don't think the non-clickable state should have a double bottom border or 'shadow' on it as it is not clickable.

Should we instead do a single stroke around the site card? 

The screenshot also seems to show something going on with the round corners on the right side of the object—not sure if that's part of the screenshot or not.

**Comment by folletto** [comment]
> The screenshot also seems to show something going on with the round corners on the right side of the object—not sure if that's part of the screenshot or not.

Well spotted! I checked and it seems a byproduct when the icon gets removed, probably due to the shadow to trim the long text.

screen shot 2017-09-20 at 18 57 45


> Should we instead do a single stroke around the site card?

What if we just remove the border? 
If we single-stroke, would be ok to forego the rounded corners then? (as non-clickable, might feel more aligned with Calypso in general, i.e. sidebar site picker).

Mocks for reference:

## (1) No Borders
screen shot 2017-09-20 at 18 58 19

## (2) Flat, Round Corners
screen shot 2017-09-20 at 18 58 51

## (3) Flat, Sharp Corners
screen shot 2017-09-20 at 18 58 42

**Comment by rickybanister** [comment]
My vote would be for the flat, round corners. I don't feel adamant, but I think that feels right—it feels like the rounded select menu/button is no longer raised and clickable. 

I also don't particularly like putting square bordered things inside of square bordered things—I'm thinking about the compact notice here. The round corners soften its position inside the sharp-cornered card. It's a silly little thing, but it makes it easier for me to flow to the next 'inline-block' element within the larger block. 

The non-bordered option feels the most weird especially because it still has margin/padding (at least in the mockup). The border helps it be an 'object' I think.

**Comment by folletto** [comment]
Makes sense, let's go for _flat, round corners_ then :)

**Comment by coreymckrill** [comment]
@folletto The above commit applies _(2) flat, round corners_ and fixes the rounded corner issue in Firefox and Webkit. I didn't have a ready way to test in IE/Edge.

**Comment by gziolo** [comment]
@coreymckrill You can use calypso.live and browserstack.com to test in IE/Edge :) It might work with a local instance, too. I don't remember.

**Comment by gziolo** [comment]
Code wise, this is ready to go. We just need to confirm it looks like as expected in all browsers 👍

**Comment by apeatling** [comment]
@coreymckrill Are you able to do the final browser testing so we can merge this one?

**Comment by kwight** [comment]
@coreymckrill You should be good to go with some final browser testing and a rebase.

**Comment by coreymckrill** [comment]
Sorry for the delay. I'm going to step back into this and get it wrapped this week or next.

**Comment by coreymckrill** [comment]
This has now been rebased and tested on Firefox, Chrome, Safari, Edge, and IE11. I believe it's ready to merge. @apeatling @kwight

**Comment by apeatling** [comment]
@kwight Good to merge? Can we also close https://github.com/Automattic/wp-calypso/issues/9895 when this is done?

**Comment by apeatling** [comment]
@coreymckrill Could you rebase and merge? Thanks

**Comment by coreymckrill** [comment]
@apeatling Rebased, merged.

**Comment by mattsherman** [comment]
I noticed this was still marked as "Needs Review" -- changed to "Ready to Merge" based on comments above.

**Comment by lancewillett** [comment]
@coreymckrill Ready to merge?

**Comment by mattsherman** [comment]
If this is still a change we desire to have, let's get this merged!
