### PR TITLE
Fix fatal error loading the block list for the first time for a site

### LINKED ISSUE #40229: Turning block into a reusable block breaks editor
#### Steps to reproduce

1. Have a wpcom simple site with Gutenberg (happened in 7.7.1 but also other versions)
1. Have a block on a page
1. Turn the page into a reusable block
    image
1. Editor breaks
image
1. Get `Error: An error occurred while running 'mapSelect': Cannot read property 'length' of undefined`

It doesn't happen each time and consistently, only sometimes.

Related to https://github.com/Automattic/wp-calypso/issues/40127?

Log:

```
Error: An error occurred while running 'mapSelect': Cannot read property 'length' of undefined
The error may be correlated with this previous error:
TypeError: Cannot read property 'length' of undefined
    at b (https://s0.wp.com/_static/??-eJydUMsOwiAQ/CFha2JtPRi/hcdat8JCYFHj18vJxIuHHifzygw8syJ2oXmssFbwVAUeyD4VKGic6Eis17qDLnSJBVkgh7YQV1hahxbL0pmCMOlJ78E2Ch5sSBaIPb42mE2TlDe7e7W7q4qFTKC3EUqsPF5NC6KyKZ34jf47X/kUN16A1ZmM6iYxfAsv8bwf58MwzsfhtH4AFleJzg==:38:3066)
    at p (https://s0.wp.com/_static/??-eJydUMsOwiAQ/CFha2JtPRi/hcdat8JCYFHj18vJxIuHHifzygw8syJ2oXmssFbwVAUeyD4VKGic6Eis17qDLnSJBVkgh7YQV1hahxbL0pmCMOlJ78E2Ch5sSBaIPb42mE2TlDe7e7W7q4qFTKC3EUqsPF5NC6KyKZ34jf47X/kUN16A1ZmM6iYxfAsv8bwf58MwzsfhtH4AFleJzg==:38:2400)
    at f (https://s0.wp.com/_static/??-eJydUMsOwiAQ/CFha2JtPRi/hcdat8JCYFHj18vJxIuHHifzygw8syJ2oXmssFbwVAUeyD4VKGic6Eis17qDLnSJBVkgh7YQV1hahxbL0pmCMOlJ78E2Ch5sSBaIPb42mE2TlDe7e7W7q4qFTKC3EUqsPF5NC6KyKZ34jf47X/kUN16A1ZmM6iYxfAsv8bwf58MwzsfhtH4AFleJzg==:38:1879)
    at Vr (https://s0.wp.com/wp-content/plugins/gutenberg-core/7.7.1/build/blocks/index.js?m=1584058609h&ver=62d2ef2b823630f6a2dc6480f95a2d52:2:143481)
    at https://s0.wp.com/wp-content/plugins/gutenberg-core/7.7.1/build/block-editor/index.js?m=1584058609h&ver=7a8c786c617cc3c2c2e61df45e20373a:1:183950
    at u (https://s0.wp.com/wp-content/plugins/gutenberg-core/7.7.1/build/block-editor/index.js?m=1584058609h&ver=7a8c786c617cc3c2c2e61df45e20373a:1:6934)
    at c (https://s0.wp.com/wp-content/plugins/gutenberg-core/7.7.1/build/block-editor/index.js?m=1584058609h&ver=7a8c786c617cc3c2c2e61df45e20373a:1:182093)
    at Array.map (<anonymous>)
    at https://s0.wp.com/wp-content/plugins/gutenberg-core/7.7.1/build/block-editor/index.js?m=1584058609h&ver=7a8c786c617cc3c2c2e61df45e20373a:1:182503
    at u (https://s0.wp.com/wp-content/plugins/gutenberg-core/7.7.1/build/block-editor/index.js?m=1584058609h&ver=7a8c786c617cc3c2c2e61df45e20373a:1:6934)

Original stack trace:
    at Me (https://s0.wp.com/wp-content/plugins/gutenberg-core/7.7.1/build/data/index.js?m=1584058609h&ver=b79a407ada12e6608f0d38482ef1bb40:1:22884)
    at https://s0.wp.com/wp-content/plugins/gutenberg-core/7.7.1/build/data/index.js?m=1584058609h&ver=b79a407ada12e6608f0d38482ef1bb40:1:23440
    at je (https://s0.wp.com/_static/??-eJydUMsOwiAQ/CFha2JtPRi/hcdat8JCYFHj18vJxIuHHifzygw8syJ2oXmssFbwVAUeyD4VKGic6Eis17qDLnSJBVkgh7YQV1hahxbL0pmCMOlJ78E2Ch5sSBaIPb42mE2TlDe7e7W7q4qFTKC3EUqsPF5NC6KyKZ34jf47X/kUN16A1ZmM6iYxfAsv8bwf58MwzsfhtH4AFleJzg==:116:476)
    at qe (https://s0.wp.com/_static/??-eJydUMsOwiAQ/CFha2JtPRi/hcdat8JCYFHj18vJxIuHHifzygw8syJ2oXmssFbwVAUeyD4VKGic6Eis17qDLnSJBVkgh7YQV1hahxbL0pmCMOlJ78E2Ch5sSBaIPb42mE2TlDe7e7W7q4qFTKC3EUqsPF5NC6KyKZ34jf47X/kUN16A1ZmM6iYxfAsv8bwf58MwzsfhtH4AFleJzg==:127:115)
    at ph (https://s0.wp.com/_static/??-eJydUMsOwiAQ/CFha2JtPRi/hcdat8JCYFHj18vJxIuHHifzygw8syJ2oXmssFbwVAUeyD4VKGic6Eis17qDLnSJBVkgh7YQV1hahxbL0pmCMOlJ78E2Ch5sSBaIPb42mE2TlDe7e7W7q4qFTKC3EUqsPF5NC6KyKZ34jf47X/kUN16A1ZmM6iYxfAsv8bwf58MwzsfhtH4AFleJzg==:254:489)
    at lh (https://s0.wp.com/_static/??-eJydUMsOwiAQ/CFha2JtPRi/hcdat8JCYFHj18vJxIuHHifzygw8syJ2oXmssFbwVAUeyD4VKGic6Eis17qDLnSJBVkgh7YQV1hahxbL0pmCMOlJ78E2Ch5sSBaIPb42mE2TlDe7e7W7q4qFTKC3EUqsPF5NC6KyKZ34jf47X/kUN16A1ZmM6iYxfAsv8bwf58MwzsfhtH4AFleJzg==:164:409)
    at O (https://s0.wp.com/_static/??-eJydUMsOwiAQ/CFha2JtPRi/hcdat8JCYFHj18vJxIuHHifzygw8syJ2oXmssFbwVAUeyD4VKGic6Eis17qDLnSJBVkgh7YQV1hahxbL0pmCMOlJ78E2Ch5sSBaIPb42mE2TlDe7e7W7q4qFTKC3EUqsPF5NC6KyKZ34jf47X/kUN16A1ZmM6iYxfAsv8bwf58MwzsfhtH4AFleJzg==:159:71)
    at ze (https://s0.wp.com/_static/??-eJydUMsOwiAQ/CFha2JtPRi/hcdat8JCYFHj18vJxIuHHifzygw8syJ2oXmssFbwVAUeyD4VKGic6Eis17qDLnSJBVkgh7YQV1hahxbL0pmCMOlJ78E2Ch5sSBaIPb42mE2TlDe7e7W7q4qFTKC3EUqsPF5NC6KyKZ34jf47X/kUN16A1ZmM6iYxfAsv8bwf58MwzsfhtH4AFleJzg==:156:14)
    at https://s0.wp.com/_static/??-eJydUMsOwiAQ/CFha2JtPRi/hcdat8JCYFHj18vJxIuHHifzygw8syJ2oXmssFbwVAUeyD4VKGic6Eis17qDLnSJBVkgh7YQV1hahxbL0pmCMOlJ78E2Ch5sSBaIPb42mE2TlDe7e7W7q4qFTKC3EUqsPF5NC6KyKZ34jf47X/kUN16A1ZmM6iYxfAsv8bwf58MwzsfhtH4AFleJzg==:91:49
    at unstable_runWithPriority (https://s0.wp.com/_static/??-eJydUMsOwiAQ/CFha2JtPRi/hcdat8JCYFHj18vJxIuHHifzygw8syJ2oXmssFbwVAUeyD4VKGic6Eis17qDLnSJBVkgh7YQV1hahxbL0pmCMOlJ78E2Ch5sSBaIPb42mE2TlDe7e7W7q4qFTKC3EUqsPF5NC6KyKZ34jf47X/kUN16A1ZmM6iYxfAsv8bwf58MwzsfhtH4AFleJzg==:26:340)
```

### PR DESCRIPTION
**Pull request by roo2**
Users have been [complaining about crashes around reusable blocks for some time](https://github.com/Automattic/wp-calypso/issues/40229), I think that this bug may have been the root cause.

It appears that normally when loading the reusable block list, the users permissions will be cached, and the page will load correctly.

However, if the user's permissions are not cached,  the page will attempt to load with `postType` and `userCanEdit` set to `null`. This will cause several errors which prevent the page from loading. This PR adds null handling to the reusable block list page.

# To reproduce:
Have two sites set up, one that you haven't logged into for a while (sorry it's a bit vague)
In site one, navigate to the reusable blocks page
https://wordpress.com/types/wp_block/<YOUR_SITE.wordpress.com>
while on this page, switch sites to a site that you haven't logged into for a while
Observe JS errors prevent the page from loading

Sep-02-2020 11-27-45

fixes #40229

### CODE REVIEW

File: client/my-sites/types/main.jsx [hunk 1]
```diff
@@ -81,7 +81,7 @@ export default connect( ( state, ownProps ) => {
 	return {
 		siteId,
 		postType,
-		postTypeSupported: isPostTypeSupported( state, siteId, ownProps.query.type ),
-		userCanEdit: canCurrentUser( state, siteId, capability ),
+		postTypeSupported: isPostTypeSupported( state, siteId, ownProps.query.type ) || false,
```
Comment (ramonjd) [inline client/my-sites/types/main.jsx:84]: I wonder if we should have been more consistent in the return value of the selectors in the first place:
https://github.com/Automattic/wp-calypso/blob/b5b9732/client/state/post-types/selectors.js#L117

File: client/my-sites/types/main.jsx [hunk 2]
```diff
@@ -81,7 +81,7 @@ export default connect( ( state, ownProps ) => {
...
+		userCanEdit: canCurrentUser( state, siteId, capability ) || false,
```
Comment (ramonjd) [inline client/my-sites/types/main.jsx:85]: Same as above here:
https://github.com/Automattic/wp-calypso/blob/b5b9732/client/state/selectors/can-current-user.js#L22

File: client/my-sites/types/main.jsx (hunk 1 above)
Comment (roo2) [reply client/my-sites/types/main.jsx:84]: yea, good point, thanks for investigating that a bit deeper! I'll look through that and try to get a more consistent solution

Comment (roo2) [reply client/my-sites/types/main.jsx]: I've updated it to change the selectors to return a true or false boolean, the canCurrentUser selector is used in quite a few places, I searched through them and actually it seems like the `null` return value was almost always just treated as `false`. This allowed me to clean up quite a few redundant type coercions.

Comment (ramonjd) [reply client/my-sites/types/main.jsx]: > The original use case for returning null would have been to prevent showing not authorized errors prematurely, and in fact, when loading the reusable blocks list page for the first time now, you do briefly see a permission error!

Thanks for changing these and explaining the reason why it was done in the first place. I didn't realize the checks were so pervasive.

I'm sorry to say – and it's my fault for not checking before I made the comment –  that maybe we shouldn't go so far in this PR since it's changing so many different areas.

Apologies for not mentioning this earlier and wasting your time 😞

I can revert back to https://github.com/Automattic/wp-calypso/pull/45346/commits/e33e7f21d0eee9d28ee8033c11ce8442428cd7cf and retest. The initial changes did look good to me, even from a defensive standpoint.

Comment (ramonjd) [reply client/my-sites/types/main.jsx]: Also, to elaborate - they are good changes, but probably better suited for another PR

Comment (ramonjd) [reply client/my-sites/types/main.jsx]: Actually, while I've been testing this diff, I checked all the pages and things just work, so maybe I was too conservative. 

So ignore my comments from above 🤣

**Review by ramonjd — APPROVED** [review]
I couldn't actually reproduce this error, but the changes you've make sense when considering the return value of the selectors.

Checked:

- activity-log
- comments
- types

All seems to be working as normal.

I rebased onto master and forced push to see if the e2e tests pass :)
