### PR TITLE
Domains: Fix error on mapping domains with no expiry

### LINKED ISSUE #4338: Domains: Error when managing a domain mapping on a VIP site
#### Steps to reproduce
1. Go to the Domains management page for any VIP site that has a mapped domain.
2. Click on a mapped domain.

#### What I expected
The details for the domain.

#### What happened instead
```
Uncaught TypeError: Cannot read property 'format' of null
```
in https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/upgrades/domain-management/edit/mapped-domain.jsx#L34

This issue has probably been introduced as part of #4194 by @aidvu and reviewed by yours truly (note to self: always test PRs on a VIP site). We forgot to take into account the fact that domain mappings for VIP sites never expire (`expiry` is `false`).

### PR DESCRIPTION
**Pull request by umurkontaci**
Fixes #4338, which broke mapped domains with no expiration (notably VIP sites). It'll now say "Never" on expiration time.

Also changes the usage of `selectedSite.domain` to `selectedSite.slug` which is the proper usage in case of a name conflict between the sites. 

Added tests for both.

Testing:
- Go to VIP site and confirm everything works as expected.

/cc: @klimeryk @aidvu

### CODE REVIEW

File: client/my-sites/upgrades/domain-management/edit/mapped-domain.jsx [hunk 1]
```diff
@@ -29,9 +29,12 @@ const MappedDomain = React.createClass( {
 			);
 		}
 
+		const expirationString = domain.expirationMoment && domain.expirationMoment.format( 'MMMM D, YYYY' ) ||
+			this.translate( 'Never', { context: 'Expiration time for a mapped domain' } );
```
Comment (klimeryk) [inline client/my-sites/upgrades/domain-management/edit/mapped-domain.jsx]: I'd change this to `<em>{ this.translate( 'Never Expires' ) }</em>` for consistency sake with what's shown for `*.wordpress.com` domains in the [domain's details page](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/upgrades/domain-management/edit/wpcom-domain.jsx#L35) and [purchase page](https://github.com/Automattic/wp-calypso/blob/master/client/me/purchases/list/item/index.jsx#L85).

**Comment by klimeryk** [comment]
This is good to :ship: - just left a comment for a possible copy change, if you agree that will improve consistency with other kinda similar products.
Special kudos for adding the tests for the fix :ok_hand:

**Comment by umurkontaci** [comment]
Thanks @klimeryk, good catch, I'll changed it to `<em>Never Expires</em>`
