### PR TITLE
Post Editor: fix error notice when saving post that has no changes

### LINKED ISSUE #25801: Post Editor: Save of draft failed.
#### Steps to reproduce
1. Starting at: My Sites > Posts
2. Choose a post
3. Hit "Update" without making changes

Same goes for pages.

#### What I expected

My suggestion would be to either disable the Update button or make it possible to hit Update on posts with no actual changes. It's unclear to me why it failed saving that draft and if that is intended.

#### What happened instead

An error message pops up saying "Saving of draft failed.".

#### Browser / OS version

Seems not to be related to a specific Browser/OS.

#### Screenshot / Video

screen shot 2018-06-28 at 12 02 50

#### Context / Source

I had a user in chat who said they couldn't update their posts. It works for them if they make changes though.

### PR DESCRIPTION
**Pull request by jsnajdr**
Fixes #25801. The `getPostEdits` selector returns `null` when the post has no local edits. And then we check for `changedAttributes.content`... This patch wraps the check with `_.get`.

Nice catch by @flootr. It's a regression introduced in #25160.

I'm not changing any UI behavior in this patch: the "Update" button continues to be enabled and does nothing when there are no changes to save.

### CODE REVIEW

File: client/lib/posts/actions.js [hunk 1]
```diff
@@ -215,7 +215,7 @@ export const saveEdited = options => async ( dispatch, getState ) => {
 	// when toggling editor modes, it is possible for the post to be dirty
 	// even though the content hasn't changed. To avoid a confusing UX
 	// let's just pass the content through and save it anyway
-	if ( ! changedAttributes.content && rawContent !== initialRawContent ) {
+	if ( ! get( changedAttributes, 'content' ) && rawContent !== initialRawContent ) {
```
Comment (blowery) [inline client/lib/posts/actions.js]: looks good. Did tickle an old thought though, maybe we should turn on https://www.npmjs.com/package/babel-plugin-transform-optional-chaining ?

Comment (jsnajdr) [reply client/lib/posts/actions.js]: I would totally love to use optional chaining. But last time I was reading TC39 minutes, I learned there is a risk that the proposal will be totally reworked from scratch with a different syntax.

Comment (blowery) [reply client/lib/posts/actions.js]: that makes me sad. :(

**Review by blowery — APPROVED** [review]
LGTM
