### PR TITLE
Site Migration: Enable the `ImportList`'s  back button redirect the user to previous flows

### LINKED ISSUE #89407: Site Migration: The ImportList back button is redirecting the users to the old site-migration flow
## What is happening?
The back button on the `setup/site-setup/importList`  page is always redirecting the users to `site-setup/import` regardless.

## What was expected?
If the user arrives on the `setup/site-setup/importList` via the new site-migration flow, the back button should redirect the user to the site-migration-identify step.

## Steps to reproduce
* Start the new site-migration-flow
* Set 'tumblr.com' as source site
* Wait to be redirected to the 'setup/site-setup/importList'
* Click on the back buttons

### PR DESCRIPTION
**Pull request by gabrielcaires**
Closes #89407

## Proposed Changes
* Introduce the `backToFlow` param as similar to the already existent `backToStep` query param to indicate the back button should return the user to the previous flow instead of the previous step.

### More context
The new site migration identify screen lands the user on the 'site-setup/importList' page when the user enters one of our supported platform (E.g. tumblr.com) or when the user clicks on the  'choose a content platform'

## Testing Instructions
**Scenario 1:** `Import content from another platform` 
* Go to the site migration identify page
* Select the `choose a content platform'` button
* Click on the back button on the `Import content from another platform`
* Check if you were redirected to the `setup/site-migration/site-migration-identify` page. 

**Scenario 2:**  `Enter a supported content platform` 
* Go to the site migration identify page
* Set `tumblr.com` as site URL
* Click on the back button on the `Import content from another platform`
* Check if you were redirected to the `setup/site-migration/site-migration-identify` page. 

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/landing/stepper/declarative-flow/site-migration-flow.ts [hunk 1]
```diff
@@ -16,8 +16,10 @@ import { AssertConditionState } from './internals/types';
 import type { AssertConditionResult, Flow, ProvidedDependencies } from './internals/types';
 import type { OnboardSelect, SiteSelect, UserSelect } from '@automattic/data-stores';
 
+const FLOW_NAME = 'site-migration';
```
Comment (markbiek) [inline client/landing/stepper/declarative-flow/site-migration-flow.ts:19]: What do you think about exporting this in case we need to refer to it from another flow?

File: client/landing/stepper/declarative-flow/site-migration-flow.ts [hunk 2]
```diff
@@ -163,7 +165,13 @@ const siteMigration: Flow = {
...
 							addQueryArgs(
-								{ siteId, siteSlug, from, origin: STEPS.SITE_MIGRATION_IDENTIFY.slug },
+								{
+									siteId,
+									siteSlug,
+									from,
+									origin: STEPS.SITE_MIGRATION_IDENTIFY.slug,
+									backToFlow: `/${ FLOW_NAME }/${ STEPS.SITE_MIGRATION_IDENTIFY.slug }`,
+								},
 								'/setup/site-setup/importList'
```
Comment (markbiek) [inline client/landing/stepper/declarative-flow/site-migration-flow.ts:175]: A thought for a future PR might be to add a constant for the flow name in `site-setup-flow.ts`. Then we could use that constant here.

**Review by markbiek — APPROVED** [review]
Left a couple of minor thoughts but other this is Working as expected!

File: client/landing/stepper/declarative-flow/site-migration-flow.ts (hunk 1 above)
Comment (gabrielcaires) [reply client/landing/stepper/declarative-flow/site-migration-flow.ts:19]: Considering we still not using it I prefer not to export but I am also missing something to generate step paths. We have a lot of hardcoded strings with step names 😢 .

File: client/landing/stepper/declarative-flow/site-migration-flow.ts (hunk 2 above)
Comment (gabrielcaires) [reply client/landing/stepper/declarative-flow/site-migration-flow.ts:175]: Yes, or at least something better to reuse the step name.
