### PR TITLE
Fix product purchase features custom domain logic

### LINKED ISSUE #7857: Rename PlanPurchaseFeatures to ProductPurchaseFeatures
In #7410, I forgot to rename `PlanPurchaseFeatures` from `blocks/product-purchase-features` to `ProductPurchaseFeatures` as a part of refactor. It causes no bugs but should be properly named to be consistent.

### PR DESCRIPTION
**Pull request by lamosty**
Fixes #7857 and #7177.

## Testing Instructions

To be able to test successfully, we need #7965 to land first. In the meantime, checkout the specific files from that branch into this one or just rebase on top of it.

1. With Personal site which has domain credit, navigate to /plans/my-plan and claim your free domain;
2. After claiming the free domain, navigate back to /plans/my-plan and check whether it shows either that you have a custom domain or doesn't show anything domain related at all.

After a domain is purchased/claimed, we don't immediately know that and therefore, users won't see anything domain related in `/plans/my-plan` for a few minutes after they claim a custom domain. More info/discussion in #7311.

/cc @mtias @meremagee @gwwar 

Test live: https://calypso.live/?branch=fix/product-purchase-features-custom-domain-logic

### CODE REVIEW

File: client/blocks/product-purchase-features/product-purchase-features-list/index.jsx [hunk 1]
```diff
@@ -147,7 +148,7 @@ export default class ProductPurchaseFeaturesList extends Component {
 			sitePlans,
 		} = this.props;
 
-		const plan = find( sitePlans.data, isWpcomPremium );
+		const plan = find( sitePlans.data, isWpcomPersonal );
```
Comment (gwwar) [inline client/blocks/product-purchase-features/product-purchase-features-list/index.jsx]: @lamosty this is out of scope, but do you remember why this component isn't connected anymore? We have a number of selectors we could use otherwise, like `getSitePlan` and `hasDomainCredit`

**Comment by gwwar** [comment]
@lamosty the changes here look good. I do suggest we display the 72 hour notice though for recently purchased domains:

The thank you page displays:
screen shot 2016-09-06 at 10 57 29 am

While in domains we see:
screen shot 2016-09-06 at 10 58 11 am

File: client/blocks/product-purchase-features/product-purchase-features-list/index.jsx (hunk 1 above)
Comment (lamosty) [inline client/blocks/product-purchase-features/product-purchase-features-list/index.jsx]: Hmm, for no apparent reason. Maybe while I moved it out from `ProductPurchaseFeatures`, I forgot to connect it. Will do in another PR. Thanks!

**Comment by lamosty** [comment]
> I do suggest we display the 72 hour notice though for recently purchased domains:

Great catch!

I'm going to reuse the domain notice in My Plan page.

**Comment by lamosty** [comment]
I added the domain notices. They are now the same as on the Domains Management page (using the same component):

selection_021

**Comment by gwwar** [comment]
also cc @apeatling @rralian for any opinions on the new domain notices

**Comment by lamosty** [comment]
Sorry, this should have not been closed. GitHub automatically closed this when I merged #7965 because it thought that PR fixes this one. It seems to be enough to write "Fixes <issue or PR number>" and upon merging that one, it automatically closes the mentioned one.

> also cc @apeatling @rralian for any opinions on the new domain notices

This is still relevant. I'm going to rebase this.

**Comment by lamosty** [comment]
Rebased and ready for more testing.

**Comment by gwwar** [comment]
cc @adambbecker for if there's an alternative to the double decker notices in
screen shot 2016-09-28 at 3 04 28 pm

**Comment by rralian** [comment]
The double-decker notices are a corner case though right? IMHO they're fine, since both notices are important, and hopefully seeing both together will be a rare state. Fine if I'm overruled by @adambbecker with a better idea though.

**Comment by lamosty** [comment]
> The double-decker notices are a corner case though right?

Yes, I usually get only the second one.

> IMHO they're fine, since both notices are important

Exactly. The same behavior happens on the `Domains` subpage as well.

I recommend trying it yourself. Purchase a plan, claim free domain and navigate to `my-plan/` page. You should see only the yellow notice.

**Comment by rralian** [comment]
Let's just go with this for now.
