### PR TITLE
Simple payments block: fix saving product ID to post too late on publish

### LINKED ISSUE #28800: Simple Payments Block: Sometimes block is not rendering on frontend
#### Steps to reproduce
1. Starting at URL: /wp-admin/post-new.php
2. Add SP block
3. Fill in SP block details and publish block without un-focusing block
4. Check your post on frontend - SP block will be missing

The problem: At the moment of publishing - SP block did not have it's ID and shortcode created, which means post published without SP shortcode.

#### What I expected

SP block will be rendered on frontend no matter how fast or tricky my flow would be

#### What happened instead

SP block wasn't populated with shortcode/ID due to how block request this data 

#### Screenshot / Video

screencast 2018-11-22 17-08-45

### PR DESCRIPTION
**Pull request by simison**
#### Changes proposed in this Pull Request

- Don't validate values on saveProduct so that we can send invalid form data to API, instead we validate on `componentDidUpdate`
- On `componentDidUpdate`, if we don't have `paymentId`, save product as a draft. This will not require valid form attributes.
- All future saves will require valid form attributes and will change the product's status to "publish"

https://codex.wordpress.org/Post_Status

Fixes #28800

##### Admin flow
- Create a new Gutenberg post, test e.g. with JN: gutenpack-jn or in Calypso: https://calypso.live/gutenberg/post?branch=update/simple-payments-block-early-id
- Add a Simple payment block to post
- Observe from networks new draft product being created, block receives product ID and stores it in attributes. You can confirm that from Editor's source view.
- Don't fill in form values and let auto-save happen (every 20s or so): observe _no_ POST request being made to update the product
- Fill in all required form fields and let auto-save happen again: observe POST request to update the product

##### Contributor flow
- Repeat steps as a contributor user and confirm no products are saved, but all values are stored in attributes instead.
- As an admin, open the post made as contributor and modify the post, then publish it. Does product ID get saved to attributes? Does product get saved _once_ and not multiple times?

##### Contributor flow
- Repeat steps as a contributor user and confirm no products are saved, but all values are stored in attributes instead
- As an admin, open the post made as contributor and publish it without touching the editor. Does product ID get saved to attributes? Does product get saved _once_ and not multiple times?

##### Contributor quick publish flow
- Repeat steps as a contributor user and confirm no products are saved, but all values are stored in attributes instead
- As an admin, do not open the post but instead publish it directly from the post list using "quick edit". Does product ID get saved to attributes and is product post created?
    image
    image

### CODE REVIEW

File: client/gutenberg/extensions/simple-payments/edit.js [hunk 1]
```diff
@@ -461,8 +473,17 @@ const mapSelectToProps = withSelect( ( select, props ) => {
...
 	const { paymentId } = props.attributes;
 
+	const fields = [
+		'content',
+		'meta.spay_currency',
+		'meta.spay_email',
+		'meta.spay_multiple',
+		'meta.spay_price',
+		'title.raw',
+	];
```
Comment (simison) [inline client/gutenberg/extensions/simple-payments/edit.js]: should check if:
```

	const fields = [
		'content',
		[ 'meta', 'spay_currency' ],
        // ...
	];
```
...works.

File: client/gutenberg/extensions/simple-payments/edit.js [hunk 2]
```diff
@@ -40,18 +40,33 @@ class SimplePaymentsEdit extends Component {
 		isSavingProduct: false,
 	};
 
+	hasInjectPaymentAttributes = false;
```
Comment (simison) [inline client/gutenberg/extensions/simple-payments/edit.js]: typo, `hasInjectPaymentAttributes` => `hasInjectedPaymentAttributes`

File: client/gutenberg/extensions/simple-payments/edit.js [hunk 3]
```diff
@@ -90,7 +128,7 @@ class SimplePaymentsEdit extends Component {
 				spay_multiple: multiple,
 				spay_price: price,
 			},
-			status: 'publish',
+			status: paymentId ? 'publish' : 'draft',
```
Comment (sirreal) [inline client/gutenberg/extensions/simple-payments/edit.js]: Mostly this works well, although there is one important consideration.

We serialize this as a shortcode 😕 

That would be fine if the shortcode respected the product post status as I expected, but it does not appear to 😞 

I'm going to look at Jetpack to verify this, but the best approach may be to file a PR with Jetpack to ensure we only render products from shortcodes if _the product is published_.

---

A more subtle note: By looking at this line, it's not clear what's happening or why. Here's what I understand to be happening. It would be great if this were more explicit.

When we add a brand new button, we call this method. In that case, we don't have a `paymentId`, so we create a draft. This is necessary so that as we work on the post and change the simple payment, we can save the post and the simple payment concurrently.

As the payment is modified, values are stored as block attributes. When the containing post is saved, we attempt to save the product if it is valid. In that case, we would update the product's status to `publish`.

---

Comment (sirreal) [reply client/gutenberg/extensions/simple-payments/edit.js]: https://github.com/Automattic/jetpack/blob/6ee14cffce0947b7ddfdeb0b58bdda5b7e7edb35/modules/simple-payments/simple-payments.php#L119-L121

```php
		if ( $product->post_type !== self::$post_type_product || 'trash' === $product->post_status ) {
			return;
		}
```

If it's not in the trash, show it 🤷‍♂️

File: client/gutenberg/extensions/simple-payments/edit.js [hunk 4]
```diff
@@ -40,18 +40,44 @@ class SimplePaymentsEdit extends Component {
...
+		if ( ! isEqual( prevProps.simplePayment, this.props.simplePayment ) ) {
 			this.injectPaymentAttributes();
 		}
 
-		if ( ! prevProps.isSaving && this.props.isSaving && hasPublishAction ) {
+		if (
+			! prevProps.isSaving &&
+			this.props.isSaving &&
+			hasPublishAction &&
+			this.validateAttributes()
```
Comment (sirreal) [inline client/gutenberg/extensions/simple-payments/edit.js]: This is a bit tricky…

Now with draft products, if they're modified but still not valid then we'll never update the draft and any changes (stored in attributes) will be overwritten when the saved draft product is read from the API. Try adding an invalid product, updating it, then refreshing the post editor.

We might:

- Need to know what status the product is in
- Update drafts with invalid data
- Update published products only if they're valid

File: client/gutenberg/extensions/simple-payments/edit.js (hunk 1 above)
Comment (sirreal) [reply client/gutenberg/extensions/simple-payments/edit.js]: That would work. Changing to array-paths was a bit stylistic, but:

`'content' === [ 'content' ]`
`'meta.spay_currency' === [ 'meta', 'spay_currency' ]`

Lodash will parse the strings into parts (even if it ends up with just one part, it doesn't know that initially), but the right hand array versions will be used directly.

**Comment by jeherve** [comment]
> Contributor flow
> As an admin, open the post made as contributor and publish it without touching the editor. Does product ID get saved to attributes? Does product get saved once and not multiple times?

Once the product has been successfully created once, I see a POST request to `wp/v2/jp_pay_product/ID` made every time an autosave happens.

> do not open the post but instead publish it directly from the post list using "quick edit". Does product ID get saved to attributes and is product post created?

This did not work in my test. I had to edit the post to see a request made and for the post to be created. Until then, even if the post had been published, no simple product had been created.

**Comment by simison** [comment]
Thanks, @jeherve note that those flows I listed under "These flows are not fixed by this PR" cuz they're still a bit buggy.

First one is improved greatly though and kinda works if admin is slow enough to press "publish". Done fast enough, it could still fail so we'll need to loop back to that.

This PR still fixes issues for most users.

**Comment by jeherve** [comment]
D'oh, I missed that heading, my bad 🤦‍♂️ Sorry!
