### PR TITLE
AnchorFM: Podcasting Card

### LINKED ISSUE #310: Editor: Scheduled Post Can Publish Changes on Autosave
What I did:
- Scheduled a post sometime in the future. Came back to edit the post close to the set publish time. (To reproduce you can just schedule a post a couple minutes into the future.)
- Leave the Editor window open past the scheduled time.
- Make changes to the post
- Let autosave happen

What Happened:
- The post was published on the autosave with the changes I had just been making

What I Expected:
- As the post was past the scheduled time I expected to have to press the Update button for the changes I was working on to be published.

raised by sandymcfadden

### PR DESCRIPTION
**Pull request by krymson24**
#### Changes proposed in this Pull Request

- Added a task card for starting a podcast website with Anchor.fm

#### Testing instructions

1. Sandbox the API and apply this diff D52847-code
2. Uncomment line 54 from `wp-content/lib/home/views.php`
3. Use Calypso Live to checkout this branch: https://github.com/Automattic/wp-calypso/pull/47487
4. On your site https://wordpress.com/home/{site}, where you've already gone through the introductory set-up tasks, dismiss the cards at the top until you see the podcast card.
5. Click on "Get Started". This should take you to https://anchor.fm/. Clicking on "Hide this" should dismiss this card.

#### Screenshots and GIFs

Screen Shot 2020-11-16 at 7 29 10 PM

Fixes 310-gh-dotcom-manage

### CODE REVIEW

File: client/my-sites/customer-home/cards/tasks/podcasting/index.jsx [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+	const translate = useTranslate();
+
+	return (
+		<Task
+			title={ translate( 'Grow your audience with a podcast' ) }
+			description={ translate(
+				`Easily turn your blog into a podcast with Anchor — the world's biggest podcasting platform.`
+			) }
+			actionText={ translate( 'Get started' ) }
+			actionUrl={ `https://anchor.fm` }
```
Comment (mmtr) [inline client/my-sites/customer-home/cards/tasks/podcasting/index.jsx:24]: Is this a temporary link? Similarly to the Stripe connection process on Earn blocks, I think this should redirect to a URL where users can connect their Anchor.fm account to their WP.com account and then they are redirected back to WP.com. But probably that process is still not implemented, in that case the temporary link is fine, but maybe we can include a TODO comment linking to the pending issue.

**Review by mmtr — COMMENTED** [review]
> Sandbox the API and apply this diff.

I guess this refers to D52847-code?

File: client/my-sites/customer-home/cards/tasks/podcasting/index.jsx (hunk 1 above)
Comment (krymson24) [reply client/my-sites/customer-home/cards/tasks/podcasting/index.jsx:24]: I followed the description here: 310-gh-dotcom-manage

I agree -- the action URL as it stands doesn't make sense to me. I'll add a TODO

**Comment by sixhours** [comment]
I took this for a quick spin and it worked! 👍

File: client/my-sites/customer-home/cards/tasks/podcasting/index.jsx [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+	const translate = useTranslate();
+
+	return (
+		<Task
+			title={ translate( 'Grow your audience with a podcast' ) }
+			description={ translate(
+				`Easily turn your blog into a podcast with Anchor — the world's biggest podcasting platform.`
+			) }
+			actionText={ translate( 'Get started' ) }
+			// TODO replace with more appropriate URL: https://github.com/Automattic/dotcom-manage/issues/320
```
Comment (mmtr) [inline client/my-sites/customer-home/cards/tasks/podcasting/index.jsx:24]: Nitpick: Since this is a private issue, it should use the shorthand. Also, the linked issue is for the inbound link (Anchor→WP.com), but the TODO here refers to the outbound link (WP.com→Anchor). We can maybe create a new follow-up issue.

File: client/my-sites/customer-home/cards/tasks/podcasting/index.jsx [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+			actionUrl={ `https://anchor.fm` }
+			completeOnStart={ false }
```
Comment (mmtr) [inline client/my-sites/customer-home/cards/tasks/podcasting/index.jsx:26]: One more nitpick: `completeOnStart` defaults to false so we can remove this altogether.

https://github.com/Automattic/wp-calypso/blob/5da115c261edabdb231326acaad57d6147721f88/client/my-sites/customer-home/cards/tasks/task.jsx#L40

**Review by mmtr — APPROVED** [review]
Great start! As noted in D52847-code and in the comments of this PR, I think we still need to apply to some iterations, but it can be followed up later (we can create new issues or keep 310-gh-Automattic/dotcom-manage opened and note there the pending stuff).

**Comment by blackjackkent** [comment]
I went ahead and added updates for the small issues mentioned in Miguel's comments above. :) This looks good to me too though.

**Comment by krymson24** [comment]
> I went ahead and added updates for the small issues mentioned in Miguel's comments above. :) This looks good to me too though.

Thanks @blackjackkent !

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5219671

Thank you @krymson24 for including a screenshot in the description! This is really helpful for our translators.

**Comment by ghost** [comment]
The Anchor link opening in the same window feels a bit unexpected. Can we change that CTA copy to make it a little clearer this is taking you out of WordPress.com? Maybe something like "Create an Anchor account"

Home

**Comment by krymson24** [comment]
> The Anchor link opening in the same window feels a bit unexpected. Can we change that CTA copy to make it a little clearer this is taking you out of WordPress.com? Maybe something like "Create an Anchor account"
> 
> Home

@sfougnier PR here: https://github.com/Automattic/wp-calypso/pull/47726
Issue here: 339-gh-dotcom-manage

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5219671).
