### PR TITLE
 Fix Marketplace Plugins Breadcrumb 2x Click Issue

### LINKED ISSUE #66795: Marketplace: Plugin details breadcrumbs requires double click to navigate
pdh6GB-1QJ-p2 - When viewing a product, navigating to the plugin page root from a plugin detail page requires two clicks of the breadcrumb to load it.

Acceptance:
- [ ] Links no longer require two clicks

### PR DESCRIPTION
**Pull request by DustyReagan**
#### Proposed Changes

P2: pdh6GB-1QJ-p2

Before this PR, on the Plugin details page, it took 2 clicks on the breadcrumb links before the linked page would load.

After this PR, it takes only 1 click.

before-2-clicks

`setQueryArgs` calls `page()`, the `useEffect` on page render was running when we try to render the `PluginsBrowser`.

This PR replaces that call with the previous approach of updating the search input box content via the `searchRef` directly. This PR also removes the `useCallback` usage as it doesn't seem required.

#### Testing Instructions

* Apply this PR
* Visit the plugin details page for any plugin
For example: http://calypso.localhost:3000/plugins/woocommerce-table-rate-shipping/{your-test-site}
* Click on "Plugins" in the breadcrumb links. It should only take 1 click to load.
* (Regression test) Additionally, you should still be able to clear a search term by pressing the "X" found in the search bar, or by clearing the search box and pressing enter/return.

clear-search-x

* Test around this issue.

#### Pre-merge Checklist

- [ ] ~[Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?~
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] ~Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)~
- [ ] ~Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?~

Fixes https://github.com/Automattic/wp-calypso/issues/66795

### CODE REVIEW

**Review by lupus2k — APPROVED** [review]
LGTM, good job!

File: client/my-sites/plugins/search-box-header/index.jsx [hunk 1]
```diff
@@ -20,6 +20,7 @@ const SearchBox = ( { isMobile, searchTerm, doSearch, searchBoxRef, isSearching
 				pinned={ isMobile }
 				fitsContainer={ isMobile }
 				onSearch={ doSearch }
+				onSearchClose={ () => setQueryArgs( {} ) }
```
Comment (lsl) [inline client/my-sites/plugins/search-box-header/index.jsx]: This creates a second `page()` call. `onSearch('')` is [already being called](https://github.com/Automattic/wp-calypso/blob/d2e27c7b2f8120cdd7861fe37bacc41921428f97/packages/search/src/search.tsx#L240) on close(clicking the "X").

```suggestion
```

**Comment by lsl** [comment]
Still didn't look quite right. There was something going on with the search box state (not clearing). I think this is working right now. @DustyReagan could you review the changes?

- [x] Double click should be fixed
- [x] Clicking popular search should show the search term in the search box 
- [x] Clicking X should clear it
- [x] Clicking Clear should clear it
- [x] Should be taken back to the plugins browser after clearing either way.

Oddity but I think it's expected:

- [x] Clicking on a category then a popular search then "X" should take you back to the category
- [x] Clicking on a category then a popular search then "Clear" should take you back to the main plugins page

The difference in behavior is because we use a link for clear and aren't detecting being on a category page. Possibly ties in with this other issue https://github.com/Automattic/wp-calypso/issues/66495#issuecomment-1225124709 @lupus2k (not something that needs fixing here.)

File: client/my-sites/plugins/search-box-header/index.jsx [hunk 2]
```diff
@@ -1,12 +1,16 @@
...
+import { Fragment, useEffect } from 'react';
 import { useDispatch } from 'react-redux';
 import { setQueryArgs } from 'calypso/lib/query-args';
 import { recordGoogleEvent, recordTracksEvent } from 'calypso/state/analytics/actions';
 import './style.scss';
 
-const SearchBox = ( { isMobile, searchTerm, doSearch, searchBoxRef, isSearching } ) => {
+function pageToSearch( s ) {
+	setQueryArgs( '' !== s ? { s } : {} );
+}
```
Comment (lsl) [inline client/my-sites/plugins/search-box-header/index.jsx:11]: @candy02058912 this is the new `doSearch`. Youll be able to drop the window scroll call in here safely once its merged, but you may also need it in the clear call or somewhere else. (This is what I was struggling to test in https://github.com/Automattic/wp-calypso/pull/66805 while the bug was active)

**Comment by candy02058912** [comment]
Would like to check if this would be considered an issue or an intended behavior:
1. Enter the search term but don't actually search
2. Navigate to a category
3. search term is preserved

Screencast:

https://user-images.githubusercontent.com/6586048/186385899-9537b3ab-e74a-4384-bc2c-604bc865f12c.mp4

**Comment by DustyReagan** [comment]
> Would like to check if this would be considered an issue or an intended behavior:
>
>     1. Enter the search term but don't actually search
>     2. Navigate to a category
>     3. search term is preserved

I'm not sure if this is intended or not, @candy02058912. 🤔 I'm a bit on the fence about this UI behavior myself. However, production behaves this way as well, so we've not introduced this behavior in this PR. I created a [new issue](https://github.com/Automattic/wp-calypso/issues/66937) for this based on your comment for further discussion. I think it's ok to leave it as is in this PR.

**Comment by DustyReagan** [comment]
> Oddity but I think it's expected:
> 
> Clicking on a category then a popular search then "X" should take you back to the category
> Clicking on a category then a popular search then "Clear" should take you back to the main plugins page

"Clear" actually acts a little strange in production. It takes you back to the category, but the URL updates to the main plugin page. So this PR "fixes" that, in that "Clear" actually goes to where the URL is pointing (the main plugin page). I'm not sure what was intended in production. However, I think the search behavior under categories is strange and worthy of its own discussion. I created an [issue here](https://github.com/Automattic/wp-calypso/issues/66938).

**Comment by lsl** [comment]
> "Clear" actually acts a little strange in production. It takes you back to the category, but the URL updates to the main plugin page. So this PR "fixes" that, in that "Clear" actually goes to where the URL is pointing (the main plugin page). I'm not sure what was intended in production.

Nope, that's a regression, from the same change I think. Should be fixed now. The clear link should take you to /plugins/:site and the interface should behave as you'd expect.

> Would like to check if this would be considered an issue or an intended behavior: search term is preserved

Not intended but I don't know if its something that needs fixing either. It's a trade off between leaving the users unfinished input in place and whether we treat category clicks as link clicks with full page navigation that would wipe out entered state. Something to raise with design to make a call on as I'm not really clear how the single page app thing is meant to treat these "links" in the general case, @vinimotaa maybe?

**Comment by candy02058912** [comment]
> Something to raise with design to make a call on as I'm not really clear how the single page app thing is meant to treat these "links" in the general case, @vinimotaa maybe?

I'll ping in the newly created issue https://github.com/Automattic/wp-calypso/issues/66937.
