### PR TITLE
FSE: Remove custom publish button and panel, and replace with info notice

### LINKED ISSUE #34705: Full Site Editing: TemplateUpdateConfirmationButton causes rendering loop
#### Steps to reproduce
1. Check out branch follow instructions in https://github.com/Automattic/wp-calypso/tree/master/apps/full-site-editing#build-system. Install the FSE plugin, and activate it on local gutenberg dev
2. Add console log to /full-site-editing/full-site-editing-plugin/full-site-editing/plugins/template-update-confirmation/button.js componentDidUpdate
3. Edit a template part, eg. Header or Footer with console open - console.log will show the component constantly rerendering
4.  Comment the following in componentDidUpdate and re-render stops - so looks like the onResize method is causing the render loop somehow.

```
	if ( props.isFullScreen !== prevProps.isFullScreen ) {
			// this ensures the button is repositioned properly when toggling fullscreen mode
			setTimeout( () => this.onResize(), 1 );
		}
```

### PR DESCRIPTION
**Pull request by glendaviesnz**
#### Changes proposed in this Pull Request

* Remove the custom publish button and warning panel for FSE template part updating
* Add a fixed info notice to warn users of the implications of template part update

Partly implements #34728
Fixes #34705

#### Testing instructions

* Check out this branch and rebuild the FSE plugin for your local FSE test environment `npx lerna run dev --scope='@automattic/full-site-editing'`
* Edit a Header or Footer template part and check that you see a blue warning notice about updates affecting multiple parts of the site
* The Publish button should also now follow the normal editor flows of 'Update' rather than always showing 'Publish' and there should be not warning panel on update.
* Test in both full screen mode and also normal mode and on different screen sizes.

Currently the notice is not fixed so scrolls up - given it is fixed I quite like this approach as it is not constantly stealing screen space if user scrolls to edit - but happy to hear thoughts on whether to fix it or not:

notice

This is how it looks with a stacked editor notice:

stacked

### CODE REVIEW

**Comment by glendaviesnz** [comment]
@shaunandrews  - what is your preference re having this notice fixed in position verses scrolling off?

**Comment by shaunandrews** [comment]
> Currently the notice is not fixed so scrolls up - given it is fixed I quite like this approach as it is not constantly stealing screen space if user scrolls to edit 

I would have said it should be fixed, but with the possibility of multiple notices I think I agree with you — lets have it scroll with the page for now. We can revisit later if needed.

Worth noting, that for now, our headers and footers are going to be very short anyways. So its likely lots of people won't have scrollbars anyways.

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/template-update-notice/index.js [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+
+domReady( () => {
+	if ( 'wp_template_part' !== fullSiteEditing.editorPostType ) {
+		return;
+	}
+	const element = document.createElement( 'div' );
+	element.classList.add( 'wp-block-a8c-template-edit-warning' );
+	document.getElementsByClassName( 'edit-post-layout__content' )[ 0 ].prepend( element );
+	render(
+		<Notice isDismissible={ false }>
```
Comment (noahtallen) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/template-update-notice/index.js]: Do we want it to be non dismissible?

Comment (noahtallen) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/template-update-notice/index.js]: Do we want it to be non dismissible? (just curious, not sure what the spec is)

**Comment by glendaviesnz** [comment]
> Unfortunately, the text doesn't wrap on mobile!

Nice catch - thanks, it was me that broke this - I had to adjust the default height of the notice and then made a quick and dirty adjustment to re-centre the text again - which only worked for single lines - have modified and should wrap and centre properly on mobile now.

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/template-update-notice/index.js (hunk 1 above)
Comment (glendaviesnz) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/template-update-notice/index.js]: @shaunandrews  - your designs didn't show any close 'x' in this notice so I read that to mean it wasn't dismissible  - can you just confirm that is the case before I go ahead and merge this please?

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/template-update-notice/index.js [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+ * Internal dependencies
+ */
+import './style.scss';
+
+domReady( () => {
+	if ( 'wp_template_part' !== fullSiteEditing.editorPostType ) {
+		return;
+	}
+	const element = document.createElement( 'div' );
+	element.classList.add( 'wp-block-a8c-template-edit-warning' );
```
Comment (vindl) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/template-update-notice/index.js]: Just curious, could we use `dispatch('core/notices').createNotice( ... )` here? Maybe something along the following lines:

```javascript
wp.data.dispatch( 'core/notices' ).createNotice(
    'warning',
    'Updates to this block will affect multiple pages on your site.',
    { isDismissible: false }
);
```

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/template-update-notice/index.js [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+	document.getElementsByClassName( 'edit-post-layout__content' )[ 0 ].prepend( element );
+	render(
+		<Notice isDismissible={ false }>
+			{ __( 'Updates to this block will affect multiple pages on your site' ) }
```
Comment (vindl) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/template-update-notice/index.js]: I know that this text has been carried over from the designs in the issues. Would it make sense to state that this "will affect **all** of the pages on your site", given that that's the current behavior? cc @shaunandrews

This might also make it easier for users to figure out how to customize header for dynamic pages, which are now not editable in FSE.

Comment (vindl) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/template-update-notice/index.js]: One more thing - I'm not sure that "block" is the best term for what we are updating here. I'm not sure what would be the best term to use here. One thing that comes to my mind is "template" which might be more future-proof and aligned with core.

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/template-update-notice/index.js (hunk 2 above)
Comment (glendaviesnz) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/template-update-notice/index.js]: ah, good point - my vision was narrowed here by the way the custom publish button was done - dispatching a notice is a much less hacky way so I will give that a try - thanks.

Comment (glendaviesnz) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/template-update-notice/index.js]: That worked and is a much nicer solution so have gone with that.

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/template-update-notice/index.js (hunk 3 above)
Comment (glendaviesnz) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/template-update-notice/index.js]: Have updated it to your wording as I think it is clearer. Will leave open for a bit longer to see if @shaunandrews has anything to add
