### PR TITLE
Focused Launch: Once there is a plan selected, do not use plan from cart anymore.

### LINKED ISSUE #50272: Focused Launch: plan from cart automatically selected when unsetting Free plan
### Steps to reproduce the behavior

1. Create a site via `/start` and add Personal annual plan to cart but abandon Checkout
2. Enable Focused Launch A/B test
3. In the editor, click on the Launch button in the header bar
4. Notice how the Personal plan is displayed as pre-selected in Focused Launch Summary view
5. Open Focused Launch plan details view and select another paid plan with a monthly billing period
6. Back in Summary view select a Free plan and then a custom domain

#### What I expected to happen
- Free plan option to be deselected and greyed out
- Billing period shown in Summary View to remain the same
- Launch your site button to become disabled

#### What happened instead
- Plan from cart was automatically selected when Free plan was deselected
- Billing period jumped to match the plan coming from cart

### Context

A possible option would be to do the pre-selection from cart just when initializing Focused Launch without a selected Plan  and not every time the plan value changes.

#### Video

https://user-images.githubusercontent.com/14192054/108513291-0c95bf00-72cb-11eb-911a-1490498d043e.mov

### PR DESCRIPTION
**Pull request by yansern**
#### Changes proposed in this Pull Request

* Do not fallback to plan from cart once a plan has been selected.

#### Testing instructions
* Create a site via `/start`.
  * `yarn dev --sync` and sandbox your site.
* Go to **Site Home > Upgrades**, select **Personal Plan**, click **Upgrade**, then abandon checkout.
* Go to Focused Launch.
  * [ ] **Personal Plan** should be the pre-selected plan.
* Click on **View all plans** and selected another paid plan.
  * Go back to summary view  and select **Free plan**.
* Click on a custom domain.
  * [ ] The **Free plan** should be deselected.

Fixes #50272

### CODE REVIEW

File: packages/launch/src/focused-launch/index.tsx [hunk 1]
```diff
@@ -46,11 +46,30 @@ const FocusedLaunch: React.FunctionComponent = () => {
 	const planProductIdFromCart = usePlanProductIdFromCart();
 	const { setPlanProductId } = useDispatch( LAUNCH_STORE );
 
+	// Once there is a selected plan, do not retrieve plan from from cart anymore.
+	const canUsePlanProductIdFromCart = React.useRef( false );
```
Comment (razvanpapadopol) [inline packages/launch/src/focused-launch/index.tsx]: For the variable name to make sense we should probably initialize it with `true`, right? 
Then, of course, update the following occurrences.

File: packages/launch/src/focused-launch/index.tsx [hunk 2]
```diff
@@ -46,11 +46,30 @@ const FocusedLaunch: React.FunctionComponent = () => {
...
+			canUsePlanProductIdFromCart.current = false;
+		}
+	}, [ selectedPlanProductId ] );
+
+	React.useEffect( () => {
+		if (
+			! selectedPlanProductId &&
+			planProductIdFromCart &&
+			! hasPaidPlan &&
+			canUsePlanProductIdFromCart.current
```
Comment (StefanNieuwenhuis) [inline packages/launch/src/focused-launch/index.tsx:62]: Set `setPlanProductId` when:
* I haven't selected a plan and;
* The checkout cart contains a paid plan and;
* haven't purchased a paid plan already and;
* It's okay to select a plan from the cart **.

** `useRef` is persistent through render cycles, hence it makes sense to add this. Without it, it's still possible to select the store's plan causing an ugly-ish jump while selecting a custom domain.

**Review by StefanNieuwenhuis — APPROVED** [review]
Tested the changes and the flow works as expected. 
I looked at the code, tried to comprehend it (see comment) and it all makes sense. 

I surely hope that we can address the `@TODO` soon to unify all the plan selecting variants in a hook or store selector.

 But, for now: LGTM! 🚢

File: packages/launch/src/focused-launch/index.tsx (hunk 2 above)
Comment (yansern) [reply packages/launch/src/focused-launch/index.tsx:62]: Thanks for the summary! <3
