### PR TITLE
Editor Guided Tour: dismiss tour on editor close and `null` update

### LINKED ISSUE #26101: Checklist guided tour doesn't disable buttons on Personalize Contact page
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/checklist/siteurl.wordpress.com/checklist/:site:
Signed up for a free account. 
2. Click "Do It!" to Personalize your Contact page
3. Once the contact page opens, note that Update button looks enabled. Click on it.

#### What I expected
The Update either happens, or is disabled until all guided tour popups are dismissed. Maybe see this part of the tour (if image and page was done in the expected order, this is what you see):
screen shot 2018-07-16 at 8 20 46 pm

#### What happened instead
Nothing. Clicking the update button didn't save the page or move me to the next guided tour modal.

#### Browser / OS version
Chrome 67.0.3396.99 
Mac OS 10.13.6

#### Context / Source
#manual-testing
#Idontfollowdirections

### PR DESCRIPTION
**Pull request by ramonjd**
This PR attempts to resolve #26101 by dismissing the Editor Guided Tour after a `null` update ([when the saveEdited() action returns null](https://github.com/Automattic/wp-calypso/blob/master/client/state/posts/actions.js#L672)). It occurs infrequently, but mainly when the Update button is activated and the user clicks it without having edit the post.

oct-26-2018 14-53-13

This PR also closes the Featured images Guided Tour when the Editor is closed. 

oct-26-2018 14-41-50

In order to commit I have updated the following accessibility/style-related features:

- Changing positive integer tabIndexes to `0` See: [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex)
- Changing a non-interactive element (div) with a click handler to a button
- Using `UNSAFE_` prefix for deprecated React lifecycle methods

## Testing

1) Create a new site
2) Go to `/checklist/{your.new.site}` and click on *Do it!* next to *Personalize your Contact page*
3) If the Update button is blue, click it without updating the page. _The modal should disappear._
4) Go to `/checklist/{your.new.site}` and click on *Do it!* next to *Personalize your Contact page*
5) Click on  *All done, continue* in the Guided Tour window to bring up the next step
6) Click `Close` in the top left hand corner of the Editor. _The Featured images modal should disappear._
7) In the console, enter `state.users.items[Object.keys(state.users.items)[0]].email_verified = false` to fake the email verification state
8) Click on *Do it!* next to *Personalize your Contact page*. _The email verification notice should appear as normal and should be clickable and tabable_^

^ _tabable_ 🤷‍♂️

### CODE REVIEW

File: client/post-editor/post-editor.jsx [hunk 1]
```diff
@@ -82,6 +81,7 @@ import { removep } from 'lib/formatting';
 import QuickSaveButtons from 'post-editor/editor-ground-control/quick-save-buttons';
 import EditorRevisionsDialog from 'post-editor/editor-revisions/dialog';
 import PageViewTracker from 'lib/analytics/page-view-tracker';
+import { pauseGuidedTour } from 'state/ui/guided-tours/selectors';
```
Comment (niranjan-uma-shankar) [inline client/post-editor/post-editor.jsx]: I think this should be in the actions folder?

```suggestion
import { pauseGuidedTour } from 'state/ui/guided-tours/actions';
```

Comment (ramonjd) [reply client/post-editor/post-editor.jsx]: Why is there no face palm emoji :) 🌴 🤕 ?? :)

Thanks!!
