### PR TITLE
Reader: Fix settings toggles

### LINKED ISSUE #40668: Reader preferences: toggles should be adjacent to their labels
In the Reader's management screen we show a popover for subscription settings:

image

The toggles should be on the left, anchoring the labels like almost all other screens in WordPress.com.

The toggles also appear to be the large version, whereas I think we use the compact toggle throughout settings.

### PR DESCRIPTION
**Pull request by sixhours**
#### Changes proposed in this Pull Request

* Tidies up the look of the Reader settings by swapping regular form toggles for compact, and moving them to the left of the labels.
* Also removes the notification Gridicon, since it added visual cruft.
* Adds `FormLabel`s around each label with IDs for accessibility. I'm not sure how effective these are, however, as they don't trigger the toggle with a click the way a normal HTML checkbox would. But hopefully this at least helps connect the label text to the toggle itself.

**Before**

Screen Shot 2020-04-07 at 11 10 30 AM

**After**

Screen Shot 2020-04-07 at 11 59 37 AM

#### Testing instructions

* Switch to this PR
* Navigate to `/following/manage` and click the Settings menu next to one of your followed blogs.
* Note the changes in the settings screen.

Fixes #40668

### CODE REVIEW

**Comment by blowery** [comment]
Nice, I like the new look!

Found a couple of bugs:
* Clicking on the label for the first option (notify me) doesn't flip the toggle
* Turning on Email Me New Posts doesn't show the three option buttongroup any more

**Comment by blowery** [comment]
To expand on that bug report, the behavior is quite odd.

If no notifications are currently active, the labels seem to be clickable. However, clicking the middle one never shows the buttongroup. If you click directly on the toggle, then the buttongroup _does_ appear...

If "email me new posts" is set, then the label is no longer clickable and you _must_ click on the toggle button directly.

**Comment by sixhours** [comment]
> To expand on that bug report, the behavior is quite odd.

> If no notifications are currently active, the labels seem to be clickable. However, clicking the middle one never shows the buttongroup. If you click directly on the toggle, then the buttongroup does appear...

> If "email me new posts" is set, then the label is no longer clickable and you must click on the toggle button directly.

Seeing this, too! I wonder if it's because our toggles aren't standard HTML checkboxes, which would respond properly to `for` labels.

As a workaround, what if we fire the same event when the form label is clicked as when the toggle changes? This seems to work in practice, but I wonder if there's the possibility of hitting a race condition...

File: client/blocks/reader-site-notification-settings/index.jsx [hunk 1]
```diff
@@ -154,13 +155,18 @@ class ReaderSiteNotificationSettings extends Component {
...
 				>
 					<div className="reader-site-notification-settings__popout-toggle">
-						{ translate( 'Notify me of new posts' ) }
-						<Gridicon icon="bell" size={ 18 } />
-						<FormToggle
+						<CompactFormToggle
 							onChange={ this.toggleNewPostNotification }
 							checked={ sendNewPostsByNotification }
 							wrapperClassName="reader-site-notification-settings__popout-form-toggle"
+							id="reader-site-notification-settings__notifications"
```
Comment (gwwar) [inline client/blocks/reader-site-notification-settings/index.jsx:162]: Do we only have one of these on the page?

Comment (sixhours) [reply client/blocks/reader-site-notification-settings/index.jsx:162]: It appears so, but I think I've figured out a way to do this without adding `FormLabel`s manually. If I wrap the label text with `CompactFormToggle` it will show the component's children as the label. Trying that now...

**Comment by gwwar** [comment]
I don't think I was able to reproduce the behavior @blowery noticed, maybe 1107e73 fixed it?

I did notice that each click immediately fires off an xhr request (without any debouncing), so we might see some funny behavior if we're really clicky with the options. It's pretty easy to show a red global notice for example.

**Comment by gwwar** [comment]
I think we may need to update a few E2E suites as well:
Screen Shot 2020-04-08 at 9 56 30 AM

@sixhours PCYsg-o8X-p2 should be a good starting point, but feel free to grab me when you get here if you're unfamiliar with our E2Es and I'd be happy to help walk through env setup.

**Comment by sixhours** [comment]
I think the test failures may have been temporary and/or unrelated; I just ran them locally with the Reader, Notifications, and Comments specs and all passed. LMK if there's another spec I should try!

**Comment by jancavan** [comment]
Thanks for cleaning this up @sixhours. IIRC, the toggles were intentionally added on the right because in mobile OS, toggles are mostly on the right (to take advantage of majority of people being right-handed). In our Settings pages, they're on the left though, but I'm not quite sure why that is. I think it's just because we haven't really set a standard for any of these.

**Comment by kwight** [comment]
This works great for me with the recent changes 👍 A rebase and re-run may help clear up the tests now.
