### PR TITLE
Gutenlypso: Reset part of the Gutenberg stores when navigating to the editor

### LINKED ISSUE #29153: Block Editor: Edited post titles display on other posts
Changing the title of a post in the block editor causes that new post title to carry over into other posts when they are opened in the editor; it fails to update the title of the post in the post list.

This problem appears to be related to unsaved changes to a post as after publishing/updating the app state appears to reset.

messed-up-post-titles mov

### LINKED ISSUE #29216: Gutenberg in Calypso: switching back to classic Calypso editor doesn't show changes
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/post/ using classic editor
2. Enter title and text and save draft
3. Switch to new editor within Calypso
4. Draft displayed
5. Make some updates
6. Switch back to classic editor

#### What I expected

Changes displayed immediately in classic editor - like it does when using wp-admin

#### What happened instead

Old contents displayed due to no page refresh

#### Browser / OS version

Chrome 70 on macOS

#### Screenshot / Video

Calypso Gutenberg ❌ 

classic editor and calypso

Calypsofy wp-admin ✅ 

classic editor and wp-admin

### PR DESCRIPTION
**Pull request by Copons**
#### Changes proposed in this Pull Request

Context: p7jreA-1Zu-p2
Props to @aduth and @jsnajdr 

* Add a reset middleware to the Gutenberg `core/editor` and `core/notices` stores.
* Reset those stores when opening Gutenlypso.

#### Testing instructions

Edited post titles display on other posts:

- Edit post 1.
- Change its title.
- Navigate back to the post list without saving.
- Edit post 2.
- It contains the post 1 title.

A post preview display on other posts previews. (note: previews might not load at first try, but it's a separate issue)

- Edit post 1.
- Change its title.
- Open the preview.
- Navigate back to the post list.
- Edit post 2.
- Open the preview.
- It shows the post 1.

Notices and the Publish sidebar persist across page changes

- Publish a post.
- Observe that the Publish sidebar is open, and there is a success notice.
- Navigate to the posts list with the browser’s back button.
- Edit a post (the same or another one).
- Observe that the publish sidebar is open, and the success notice is visible.

Modals persist across page changes

- From the More menu (the ellipsis icon in the top right corner), select the Keyboard Shortcuts item to open the Keyboard Shortcuts modal.
- Navigate to the posts list with the browser’s back button.
- Edit a post (the same or another one).
- Observe that the Keyboard Shortcuts modal is open.

Fixes #29153 
Fixes #29216

### CODE REVIEW

File: client/gutenberg/editor/init.js [hunk 1]
```diff
@@ -29,6 +29,35 @@ const loadA8CExtensions = () => {
 	require( 'gutenberg/extensions/presets/jetpack/editor.js' );
 };
 
+const addResetToRegistry = registry => {
+	if ( typeof window === 'object' && window.app && window.app.isDebug ) {
+		window.gutenbergState = () => mapValues( registry.stores, ( { store } ) => store.getState() );
```
Comment (kwight) [inline client/gutenberg/editor/init.js]: Should this only be in certain environments (not prod)?

**Comment by kwight** [comment]
Love it, love it, love it, couldn't find any issues, and all the test scenarios above are corrected ✨

File: client/gutenberg/editor/controller.js [hunk 2]
```diff
@@ -102,6 +106,11 @@ export const loadGutenbergBlockAvailability = store => {
 	} );
 };
 
+export const resetGutenbergState = registry => {
+	registry.reset();
+	return {};
+};
```
Comment (jsnajdr) [inline client/gutenberg/editor/controller.js]: This is a plugin that's registered repeatedly on every route load, and all it does is to call the `registry.reset()` method? We do it this way because there is no other way to access the `registry` object and call a method from it? The `@wordpress/data` package exports only few selected methods of the registry.

File: client/gutenberg/editor/controller.js [hunk 3]
```diff
@@ -121,6 +130,11 @@ export const post = async ( context, next ) => {
 
 		const Editor = initGutenberg( userId, siteSlug );
 
+		// Reset the Gutenberg state
+		use( resetGutenbergState );
```
Comment (jsnajdr) [inline client/gutenberg/editor/controller.js]: `use( addResetToRegistry )` in `initGutenberg` returns the registry enhanced with the `reset` method. Maybe we could do this?
```js
const { Editor, registry } = initGutenberg(); // updated return value of initGutenberg
registry.reset();
```
This way, function call is a function call and not a plugin registration 🙂

File: client/gutenberg/editor/controller.js [hunk 4]
```diff
@@ -121,6 +130,11 @@ export const post = async ( context, next ) => {
...
+		dispatch( 'core/edit-post' ).closePublishSidebar();
+		dispatch( 'core/edit-post' ).closeModal();
```
Comment (jsnajdr) [inline client/gutenberg/editor/controller.js]: What if we just added `core/edit-post` to the list of resettable stores?

Comment (Copons) [reply client/gutenberg/editor/controller.js]: The `edit-post` store also contain other "harmless" parts and preferences that we are fine keeping across editor instances.
