### PR TITLE
Plans: fix pricing labels when loading

### LINKED ISSUE #5044: Checkout: Monthly prices showing NaN until the prices load
When I am sandboxed some of the endpoints take a while to load. This means that when I add a plan to my cart I see this in the checkout sidebar, until the prices have loaded from the API:

screen shot 2016-04-27 at 09 24 21

I guess we should fall back to the "Loading" text in this case, until the prices have loaded.

cc: @rralian @gwwar since you touched this last I think.

### PR DESCRIPTION
**Pull request by gwwar**
Fixes #5044 This PR adds text loading placeholders when plan pricing is loading in a cart item, or in the plans compare page.

screen shot 2016-04-27 at 8 46 22 am

cc @scruffian @rralian

### CODE REVIEW

File: client/my-sites/upgrades/cart/cart-item.jsx [hunk 1]
```diff
@@ -57,6 +57,11 @@ export default React.createClass( {
 
 	monthlyPrice: function() {
 		const { cost, currency } = this.props.cartItem;
+
+		if ( typeof cost === 'undefined' ) {
+			return this.translate( 'Loading price' );
```
Comment (rralian) [inline client/my-sites/upgrades/cart/cart-item.jsx]: I think we just want to return `null` here. Otherwise it repeats "Loading price" on two different lines.
loading price

Comment (gwwar) [inline client/my-sites/upgrades/cart/cart-item.jsx]: As long as you don't mind the height jump. This case should happen rarely enough, so I don't mind either way.

File: client/components/plans/plan-price/index.jsx [hunk 2]
```diff
@@ -55,7 +55,9 @@ const PlanPrice = React.createClass( {
 			return <div className="plan-price is-placeholder" />;
 		}
 
-		if ( abtest( 'planPricing' ) === 'monthly' && plan.raw_price !== 0 ) {
+		if ( ! plan ) {
+			periodLabel = this.translate( 'Loading' );
```
Comment (rralian) [inline client/components/plans/plan-price/index.jsx]: We should just return null here, otherwise we get a double-loading indicator.

double-loading

**Comment by rralian** [comment]
I forced the situations above by setting the plan data to null. I believe it's the same case that would happen if you were getting a slow `plans` response, but I wasn't able to test that case directly.

Saw another tangentially related issue, but we could maybe address it here. We're applying this `($x X 12)` treatment to all items in the cart, but that doesn't make sense for credits.

credits get monthly treatment

I'm also not sure we want it for domains, but that's probably worth discussing in a separate PR/issue.

File: client/components/plans/plan-price/index.jsx (hunk 2 above)
Comment (gwwar) [inline client/components/plans/plan-price/index.jsx]: This needs to be a string, but I'll pass through an empty one if this bothers you.

File: client/my-sites/upgrades/cart/cart-item.jsx (hunk 1 above)
Comment (rralian) [inline client/my-sites/upgrades/cart/cart-item.jsx]: In that case I'd rather add return no-break space or something like that to match the height. The redundancy seems weird.

**Comment by gwwar** [comment]
That case should be fixed now too.
screen shot 2016-04-27 at 11 43 10 am

**Comment by rralian** [comment]
looks good, :shipit:

File: client/my-sites/upgrades/cart/cart-item.jsx (hunk 1 above)
Comment (scruffian) [inline client/my-sites/upgrades/cart/cart-item.jsx]: Or it could be a placeholder element.
