### PR TITLE
Fix pending transfer domain delete button

### LINKED ISSUE #62941: Domains: `Cancel transfer` link is not working for inbound domain transfer
### Quick summary

The `Cancel transfer` link in Calypso for an inbound domain transfer is not functional/clickable. The HTML code doesn't even have an <a> tag.

image

### Steps to reproduce

Check the Calypso domain page for a domain in `pending_start` status.

### What you expected to happen

A working `Cancel transfer` link

### What actually happened

`Cancel transfer` is not a link, so there is no way to cancel the inbound domain transfer.

### Context

Initially reported in p1648645854517919-slack-C0761SX4K. I think it falls under @Automattic/nomado?

### Simple, Atomic or both?

Simple

### Theme-specific issue?

No

### Browser, operating system and other notes

macOS Monterrey 12.3 with Google Chrome Version 100.0.4896.127 (Official Build) (x86_64)

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Domain transfer can be removed via the Purchases https://wordpress.com/me/purchases

### PR DESCRIPTION
**Pull request by gius80**
## Changes proposed in this Pull Request

This PR fixes a bug in domain settings that prevented pending transfer domain (bought without using free credits) from being canceled.

Related to #62941 

transfer-before

transfer-after

## Testing instructions

In order to test this, you need a pending transfer domain (not bought with free credits).

- Build this branch locally or open the live Calypso link
- Go to domain settings page and verify that "Delete" button is rendered on the right column.

### CODE REVIEW

File: client/my-sites/domains/domain-management/components/domain/domain-info-card/delete/index.tsx [hunk 1]
```diff
@@ -56,14 +58,28 @@ const DomainDeleteInfoCard = ( {
...
 
+	if ( ! isCancelable( purchase ) ) {
+		return null;
+	}
+	const link = getCancelPurchaseUrlFor( selectedSite.slug, purchase.id );
 	return (
 		<DomainInfoCard
-			type="custom"
+			type="href"
+			ctaText={ translate( 'Delete' ) }
```
Comment (hambai) [inline client/my-sites/domains/domain-management/components/domain/domain-info-card/delete/index.tsx:79]: Shouldn't this be "Cancel" instead of "Delete"?

**Review by hambai — APPROVED** [review]
The PR works as expected. I only wonder if the button label is a bit off?
