### PR TITLE
Sites page: Fix nested dropdown clipped by the viewport 

### LINKED ISSUE #81590: Sites page: Nested dropdown clipped by the viewport
When you open a nested dropdown on the Sites page, it's clipped by the viewport:

In the case of a Business plan site, it looks like this:

Screenshot 2023-09-11 at 2 05 08 PM

In the case of lower-tier plans, we show the upsell nudge, but currently, its styles seem to be off. Not sure if this is a related or separate issue:

Screenshot 2023-09-11 at 2 04 37 PM

### PR DESCRIPTION
**Pull request by katinthehatsite**
Closes https://github.com/Automattic/wp-calypso/issues/81590

## Proposed Changes

This PR fixes the nested dropdown from the `Hosting Configuration` menu item in the ellipsis menu on `https://wordpress.com/sites` that was getting clipped by the viewport.

**Before**

Screenshot 2023-09-12 at 11 02 53 AM
   
**After**

Screenshot 2023-09-12 at 11 03 24 AM

## Testing Instructions

**Testing the grid view**

* Navigate to `https://wordpress.com/sites` (you can use Calypso Live link)
* Select the grid view:

Screenshot 2023-09-12 at 11 07 45 AM

* Click on the ellipsis menu for a site that is located on the right side (make sure you don't use a P2 site as it does not have `Hosting Configuration` menu item)
* Select `Hosting Configuration` menu item
* Confirm that the nested popover does not get clipped on the right and flips to the left
* Check the popover for the other sites in the grid (the one on the left, the one in the middle)

**Testing the list view**

* Switch to the list view:

Screenshot 2023-09-12 at 11 10 16 AM

* Navigate to the ellipsis menu
* Select `Hosting Configuration` menu item
* Confirm that the nested popover does not get clipped by the viewport and flips to the left 

----

**Issue with styles**:

While fixing the viewport, I noticed one more regression with the nested submenu popover - the CSS cascade was broken and the styles were not applying. This is what the result of the regression looks like:

Screenshot 2023-09-13 at 11 02 12 AM

After some research, I found that the issue is coming from https://github.com/WordPress/gutenberg/pull/53982 and https://github.com/WordPress/gutenberg/pull/53889: recently the `Popover.Slot` was made optional which made the popover to be rendered at the end of the body instead of being rendered inline:

Screenshot 2023-09-12 at 4 36 37 PM

As a solution, I added an optional `inline` prop to make the popover render inline again and inherit the styles. This is what it looks like after the fix:

Screenshot 2023-09-13 at 11 06 59 AM

**To test**:

* Navigate to `https://wordpress.com/sites` (you can use Calypso Live link)
*  Click on the ellipsis menu for a site that is located on the right side (make sure you don't use a P2 site as it does not have `Hosting Configuration` menu item)
* Select `Hosting Configuration` menu item
* Confirm that the styles of the popover inherit the styles of the parent (the styles should look as on the screenshot above)

**Note**: I tried a few solutions for this and `inline` prop seemed to be the least messy of all but happy to reconsider if there are other preferences or ideas. 

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: packages/components/src/upsell-menu-group/index.tsx [hunk 1]
```diff
@@ -17,6 +17,7 @@ const Content = styled.div( {
 	width: 210,
 	whiteSpace: 'break-spaces',
 	maxWidth: '80vw',
+	fontSize: '0.8125rem',
```
Comment (kozer) [inline packages/components/src/upsell-menu-group/index.tsx]: [Proposal]: Where did you get this size from? Based on some discussions in progress https://github.com/Automattic/wp-calypso/pull/81271, and in an effort to make things easier to track in the future, I suggest creating a new constant to indicate what this variable is. ( Searching for it, I noticed that this size is sometimes used for subtitles. )

Comment (katinthehatsite) [reply packages/components/src/upsell-menu-group/index.tsx]: Thanks @kozer - I will take a look but likely I am going to remove it completely. I found another issue related to dependencies update and the nested popover that messed a bunch of CSS classes. I will attempt to fix the root cause instead because it affects more things than `fontSize`.

File: packages/components/src/submenu-popover/index.tsx [hunk 2]
```diff
@@ -81,9 +83,9 @@ function useHasRightSpace( parentElement: HTMLElement | undefined, isVisible: bo
 }
 
 export function useSubmenuPopoverProps< T extends HTMLElement >(
-	options: { offset?: number } = {}
+	options: { offset?: number; inline?: boolean } = {}
 ) {
-	const { offset = 0 } = options;
+	const { offset = 0, inline } = options;
```
Comment (kozer) [inline packages/components/src/submenu-popover/index.tsx]: I would use some extra params here, for every prop we use down below, in order to give the user the opportunity to pass the props he wants, and some sane defaults as well. For example:
```
options: { offset?: number; inline?: boolean; flip?: boolean; resize?: boolean; inline; boolean} = {}
```
and on initialization:

```
const { offset = 0, inline=false, flip =true, resize = true } = options;
```
Note that in case you are wondering why I put those defaults, those are what the component uses, and more specifically, those are all the default props:
```
{
		animate = true,
		headerTitle,
		onClose,
		children,
		className,
		noArrow = true,
		position,
		placement: placementProp = 'bottom-start',
		offset: offsetProp = 0,
		focusOnMount = 'firstElement',
		anchor,
		expandOnMobile,
		onFocusOutside,
		__unstableSlotName = SLOT_NAME,
		flip = true,
		resize = true,
		shift = false,
		inline = false,
		variant,

		// Deprecated props
		__unstableForcePosition,
		anchorRef,
		anchorRect,
		getAnchorRect,
		isAlternate,

		// Rest
		...contentProps
	}
```

**Review by kozer — CHANGES_REQUESTED** [review]

**Comment by kozer** [comment]
Great work @katinthehatsite ! It works as expected! Left a comment!

File: packages/components/src/submenu-popover/index.tsx (hunk 2 above)
Comment (katinthehatsite) [reply packages/components/src/submenu-popover/index.tsx]: Thanks @kozer ! I will add those - I saw that initially Antonio passed only offset there (not sure what was the reasoning there) but makes sense! I will add those 👍

**Comment by katinthehatsite** [comment]
@kozer - changes applied! Let me know what you think

File: packages/components/src/submenu-popover/index.tsx [hunk 3]
```diff
@@ -81,9 +83,9 @@ function useHasRightSpace( parentElement: HTMLElement | undefined, isVisible: bo
 }
 
 export function useSubmenuPopoverProps< T extends HTMLElement >(
-	options: { offset?: number } = {}
+	options: { offset?: number; flip?: boolean; resize?: boolean; inline?: boolean } = {}
```
Comment (kozer) [inline packages/components/src/submenu-popover/index.tsx]: What do you think about defining those props `Partial< SubmenuPopoverProps >`, like below?

**Review by kozer — CHANGES_REQUESTED** [review]

**Comment by kozer** [comment]
Nice @katinthehatsite ! I added one more comment, I missed before! Sorry about that :slightly_smiling_face:

File: packages/components/src/submenu-popover/index.tsx (hunk 3 above)
Comment (katinthehatsite) [reply packages/components/src/submenu-popover/index.tsx]: Thanks @kozer - I think I see why it is a better approach as it allows us to provide explicit default values, is that right?

I made updates based on your suggestion!

File: packages/components/src/submenu-popover/index.tsx [hunk 4]
```diff
@@ -81,9 +83,9 @@ function useHasRightSpace( parentElement: HTMLElement | undefined, isVisible: bo
 }
 
 export function useSubmenuPopoverProps< T extends HTMLElement >(
-	options: { offset?: number } = {}
+	options: { offset?: 0; flip?: true; resize?: true; inline?: false } = {}
 ) {
-	const { offset = 0 } = options;
+	const { offset = 0, inline = false, flip = true, resize = true } = options;
```
Comment (kozer) [inline packages/components/src/submenu-popover/index.tsx]:
```suggestion
export function useSubmenuPopoverProps< T extends HTMLElement >(
	options: Omit< SubmenuPopoverProps, 'isVisible' | 'placement' | 'anchor' | 'children' > = {
		offset: 0,
		flip: true,
		resize: true,
		inline: false,
	}
) {
	const { offset, inline, flip, resize } = options;
```
Actually I was thinking something like that

Comment (kozer) [reply packages/components/src/submenu-popover/index.tsx]: The reason is that the props we are passing are actually a subset of what submenu props are ( `const submenu: Partial< SubmenuPopoverProps >` ). If for some reason `SubmenuPopoverProps` changes completely, the suggestion I made will create a ts error. However, this was not the case before, as there was not any relationship between options and SubmenuPopoverProps ( which it should have ).

**Review by kozer — APPROVED** [review]
