### PR TITLE
Invites: Fixes issues with auto-filling email

### LINKED ISSUE #1143: People: Accepting invite without changing email fails validation
Note in the following screenshot that all details are filled out, but the email doesn't validate. I was able to get validation to work by removing an `m` from the end of the email and then adding it back :smile: 

screen shot 1

### PR DESCRIPTION
**Pull request by ebinnion**
Fixes #1143 and #1144 

This PR fixes a couple of issues with our auto filling of the email input by properly initializing the email value for the form.

To test:
- Checkout `fix/logged-out-prefill-email`

__Accept Invite__
- Create an invite at `$site/wp-admin/users.php?page=wpcom-invite-users`
- In the invite email, make note of the invitation key
- While logged out, go to `/accept-invite/$site/$invite_key`
- An email should be populated. If so, the email should be validated shortly after loading
- Now test that you can remove the email by backspacing all characters. If you're able to empty the input, then :+1: 
- Lastly, can you successfully create a user and accept the invite?

__Signup Framework__
- Go to `/start/account/user`
- Attempt to create a new user
- Do form fields properly validate? Are you able to successfully create a user?

cc @lezama and @scruffian for review

### CODE REVIEW

File: client/components/signup-form/index.jsx [hunk 1]
```diff
@@ -267,9 +284,9 @@ export default React.createClass( {
 						id="email"
 						name="email"
 						type="email"
-						value={ formState.getFieldValue( this.state.form, 'email' ) || this.props.email }
+						value={ formState.getFieldValue( this.state.form, 'email' ) }
 						isError={ formState.isFieldInvalid( this.state.form, 'email' ) }
-						isValid={ formState.isFieldValid( this.state.form, 'email' ) }
+						isValid={ this.state.validationInitialized && formState.isFieldValid( this.state.form, 'email' ) }
```
Comment (lezama) [inline client/components/signup-form/index.jsx]: I removed this check and it seems to work alright, why do we need it?

**Comment by lezama** [comment]
Good catch @ebinnion! 
Works as described. I added a commit to focus on username when the email is provided.

LGTM

File: client/components/signup-form/index.jsx (hunk 1 above)
Comment (ebinnion) [inline client/components/signup-form/index.jsx]: In my testing, if we don't have that check, the field flashes green before properly validating.

You can test this by sendin an invite to an existing WP.com user and then trying to accept that invite while logged out.
