### PR TITLE
Reader iFrames: Allows resizing iframes from WP sites.

### LINKED ISSUE #45105: Reader: WordPress embeds are cropped when viewed in the Reader
When viewing a post that contains Gutenberg WordPress embed blocks in the Calypso reader, the content can be cropped.

#### Steps to reproduce
1. Create a post on a test site and add some Gutenberg WordPress embed blocks.  ([This](https://wordpress.com/read/feeds/40377931/posts/2871709673) is my test post).  Link the blocks to WordPress posts that will generate preview cards. ([This is one](https://olagist.net/may-d-x-davido-lowo-lowo-video/) I randomly picked.)
2. View the post in the Calypso reader.
3. Compare the post in the reader vs the post on the site.  Notice that the bottom of the card is cropped. 

Depending on the card, this might look okay, or it might end up cropping the site logo beneath the card image. In any event the border around the card is cropped.

My expectation is the full card would be shown. 

#### Browser / OS version
Chrome, macOS 10.15.5

#### Screenshot / Video

Screen Shot 2020-08-21 at 10 02 16 AM

### PR DESCRIPTION
**Pull request by cpapazoglou**
#### Changes proposed in this Pull Request
~~I have allowed `allow-scripts` in the sandboxed iFrame so that it has the chance to send a message with the contents height. I am pretty sure that this is a security risk, I have created this PR just to kick off discussions.~~ discussed here https://github.com/Automattic/wp-calypso/pull/54410#discussion_r667830934

What has changed:
- If there are embeds from WordPress sites they will get resized to proper height
- Also, I they will get 100% of width
- and the blockquotes that used to hold the Title / link are removed since the Embed Title is now clickable.

If we eventually don't want to add `allow-scripts` in the sandbox, we have no way (?) of finding / applying the correct height. In that case, we can resort to having fixed height iFrames and some CSS which would apply a fading overlay on the bottom of the iFrames, we would lose though the bottom part of the embed

#### Testing instructions

On a site you follow:
- Copy - paste `https://azcir.org/news/2021/06/14/504-plans-favor-wealthy-white-students-disabilities/` in your editor
- Save the post
- Visit the Calypso Reader and open this post
- Note that the iFrame gets resized to fit all the content
- Resizing the browser should resize the iFrames

Before | After
-------|------
SS 2021-07-12 at 17 44 53|SS 2021-07-12 at 17 45 54

Fixes #45105

### CODE REVIEW

**Review by tyxla — COMMENTED** [review]
Hey @cpapazoglou I haven't dug into this thoroughly, but I was wondering if `ResizableIframe` ([link](https://github.com/Automattic/wp-calypso/blob/trunk/client/components/resizable-iframe/README.md#L1)) could do the job for you here.

**Comment by cpapazoglou** [comment]
> Hey @cpapazoglou I haven't dug into this thoroughly, but I was wondering if `ResizableIframe` ([link](https://github.com/Automattic/wp-calypso/blob/trunk/client/components/resizable-iframe/README.md#L1)) could do the job for you here.

Well, this is for directly embedding something in an iFrame which is different from parsing the post body for iFrames like is done here https://github.com/Automattic/wp-calypso/blob/6340c1e70ad4b1e1e29fab57f1c913c1ba51[…]18f/client/lib/post-normalizer/rule-content-make-embeds-safe.js. 

The good part is that it includes sending and receiving the height and width from the iFrame to the top, which means it could work for other sources than WordPress too which currently do not send a message to the top. 

**BUT** in both cases (my PR and this component) the iFrame will need to be allowed to run scripts. And this is my main concern here.

File: client/lib/post-normalizer/rule-content-make-embeds-safe.js [hunk 1]
```diff
@@ -49,7 +49,7 @@ export default function makeEmbedsSafe( post, dom ) {
 		} else if ( iframeIsAllowed( iframe ) ) {
 			iframe.setAttribute( 'sandbox', 'allow-same-origin allow-scripts allow-popups' );
 		} else {
-			iframe.setAttribute( 'sandbox', '' );
+			iframe.setAttribute( 'sandbox', 'allow-scripts' );
```
Comment (tyxla) [inline client/lib/post-normalizer/rule-content-make-embeds-safe.js:52]: Enabling `sandbox="allow-scripts"` to any iframe without verifying it's from a safe source is definitely a security risk. I would advise strongly against it. 

I'm in favor of the alternative idea you suggested - introducing a fading overlay at the bottom of the frame.

Comment (cpapazoglou) [reply client/lib/post-normalizer/rule-content-make-embeds-safe.js:52]: Since the iFrame is sandboxed and doesn't allow access to parent frame, I am not sure if `sandbox="allow-scripts"` is a security risk. It can certainly be:

- a performance hog
- behave incorrectly (itself)

The parent frame content and cookies _should_ be safe. 

We could also limit the `iFrames` having `sandbox="allow-scripts"` only to those ending with `/embed` which is the format for WordPress embeds eg https://azcir.org/news/2021/06/14/504-plans-favor-wealthy-white-students-disabilities/embed/.

Just doing a final stretch, before going on with the CSS hack 😃

Comment (tyxla) [reply client/lib/post-normalizer/rule-content-make-embeds-safe.js:52]: I agree, the parent frame content and cookies are safe if we don't provide `allow-same-origin` too, but it just feels wrong (and too permissive) to allow any site to execute any script they wish. There's a bunch one can do with JavaScript (even without access to the parent frame) and I'm not sure allowing this is justified when we can just go around with a visual trick. Anyway, I don't have super strong feelings about this, and I'm generally open about it.

File: client/blocks/reader-full-post/iFrameResize.js [hunk 2]
```diff
@@ -0,0 +1,129 @@
...
+				if ( targetURL.host === sourceURL.host ) {
+					if ( document.activeElement === source ) {
+						window.top.location.href = data.value;
+					}
+				}
+			}
+		}
+	};
+
+	function onLoad() {
```
Comment (jsnajdr) [inline client/blocks/reader-full-post/iFrameResize.js]: This function will never be called, because it's attached to the window's `load` and `DOMContentLoaded` events. But at the time when it's being attached, both events already fired a long time ago.

And it also doesn't do anything useful or related to resizing the embed. It can be removed completely.

File: client/blocks/reader-full-post/iFrameResize.js [hunk 3]
```diff
@@ -0,0 +1,129 @@
...
+	}
+
+	/** @namespace wp */
+	window.wp = window.wp || {};
+
+	if ( window.wp.receiveEmbedMessage ) {
+		return;
+	}
+
+	window.wp.receiveEmbedMessage = function ( e ) {
```
Comment (jsnajdr) [inline client/blocks/reader-full-post/iFrameResize.js]: This could be a module-local function, not exposed on `window.wp` at all.

File: client/lib/post-normalizer/rule-content-make-embeds-safe.js (hunk 1 above)
Comment (jsnajdr) [reply client/lib/post-normalizer/rule-content-make-embeds-safe.js:52]: Allowing scripts to run in the iframe seems OK to me here. As long as the sandbox disables all the annoying or unsafe actions that the script could do: showing popups, navigating the top-level window, perform downloads or submit forms... They are all listed here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox

If the embed runs scripts that affect only the embed iframe's rectangle and can't reach out outside it, it should be OK.

When the embed in the post is rendered on the site frontend, it also runs in an `<iframe sandbox="allow-scripts">`. Therefore, on frontend, the embed can run scripts that, for example, send a `height` message to the parent frame, but can't do anything annoying.

We also don't sandbox iframes in Calypso that show a post preview. We should probably start doing that.

File: client/blocks/reader-full-post/index.jsx [hunk 4]
```diff
@@ -119,6 +120,7 @@ export class FullPostView extends React.Component {
 		if ( this.hasCommentAnchor && ! this.hasScrolledToCommentAnchor ) {
 			this.scrollToComments();
 		}
+		iFrameResize();
```
Comment (jsnajdr) [inline client/blocks/reader-full-post/index.jsx]: The resizer should work in such a way that it attaches the `message` listener on mount, and detaches in on unmount.

To be even more resilient, it should manage only iframes that are children of the `FullPostView` component instance's DOM element. That prevents accidental interaction with unrelated iframes that are in a different part of the Calypso UI.

Instead of querying for `document.querySelectorAll( 'iframe' )`, it should query locally as `this.elRef.current.querySelectorAll( 'iframe' )`.

**Review by jsnajdr — COMMENTED** [review]
The `iFrameResize.js` file name should follow Calypso convention of `lowercase-with-dashes.js` file names.

The resize script can also be greatly simplified: assume modern browsers, remove the `onLoad` function... We can label it as inspired by the Core's counterpart, it doesn't need to be a verbatim copy.

**Comment by cpapazoglou** [comment]
Thanks for your comments @tyxla and @jsnajdr! 

Based on @jsnajdr recommendations, I have refactored the implementation to be more simple and resilient.

File: client/blocks/reader-full-post/index.jsx [hunk 5]
```diff
@@ -500,6 +507,7 @@ export class FullPostView extends React.Component {
 								<EmbedContainer>
 									<AutoDirection>
 										<div
+											ref={ this.postContentWrapper }
```
Comment (jsnajdr) [inline client/blocks/reader-full-post/index.jsx:511]: What about the `PostExcerpt` component above? Can it happen that the excerpt also contains embed iframes? If yes, it also deserves that the `ref` is passed, and the embeds are managed by the resize listener.

File: client/blocks/reader-full-post/wp-iframe-resize.js [hunk 6]
```diff
@@ -0,0 +1,86 @@
...
+		if ( ! ( data.secret || data.message || data.value ) ) {
+			return;
+		}
+
+		if ( /[^a-zA-Z0-9]/.test( data.secret ) ) {
+			return;
+		}
+
+		const iframes = contentWrapper.querySelectorAll( 'iframe[data-secret="' + data.secret + '"]' );
+		const blockquotes = document.querySelectorAll(
```
Comment (jsnajdr) [inline client/blocks/reader-full-post/wp-iframe-resize.js]: This should also query only in `contentWrapper`.

File: client/blocks/reader-full-post/wp-iframe-resize.js [hunk 7]
```diff
@@ -0,0 +1,86 @@
...
+					if ( document.activeElement === source ) {
+						window.top.location.href = data.value;
+					}
+				}
+			}
+		}
+	};
+
+	if ( removeListener ) {
+		window.removeEventListener( 'message', receiveEmbedMessage, false );
```
Comment (jsnajdr) [inline client/blocks/reader-full-post/wp-iframe-resize.js]: This won't really remove the listener because the `receiveEmbedMessage` is a different function on each `WPiFrameResize()` call.

File: client/blocks/reader-full-post/wp-iframe-resize.js [hunk 8]
```diff
@@ -0,0 +1,86 @@
...
+
+		const iframes = contentWrapper.querySelectorAll( 'iframe[data-secret="' + data.secret + '"]' );
+		const blockquotes = document.querySelectorAll(
+			'blockquote[data-secret="' + data.secret + '"]'
+		);
+		let i;
+		let source;
+		let height;
+		let sourceURL;
+		let targetURL;
```
Comment (jsnajdr) [inline client/blocks/reader-full-post/wp-iframe-resize.js]: Let's move these variables to the inner blocks where they are used. That's the ES2015 style.

File: client/blocks/reader-full-post/wp-iframe-resize.js (hunk 6 above)
Comment (cpapazoglou) [reply client/blocks/reader-full-post/wp-iframe-resize.js]: Good catch! 5e90b04

File: client/blocks/reader-full-post/wp-iframe-resize.js (hunk 8 above)
Comment (cpapazoglou) [reply client/blocks/reader-full-post/wp-iframe-resize.js]: Good idea, 43c15f2!

File: client/blocks/reader-full-post/wp-iframe-resize.js [hunk 9]
```diff
@@ -0,0 +1,86 @@
...
+			}
+
+			source.removeAttribute( 'style' );
+
+			/* Resize the iframe on request. */
+			if ( 'height' === data.message ) {
+				height = parseInt( data.value, 10 );
+				if ( height > 1000 ) {
+					height = 1000;
+				} else if ( ~~height < 200 ) {
```
Comment (dsas) [inline client/blocks/reader-full-post/wp-iframe-resize.js]: TIL about ~~ in JS

File: client/blocks/reader-full-post/wp-iframe-resize.js (hunk 7 above)
Comment (cpapazoglou) [reply client/blocks/reader-full-post/wp-iframe-resize.js]: This should be resolved now 306ca35

**Review by dsas — APPROVED** [review]

File: client/blocks/reader-full-post/wp-iframe-resize.js (hunk 7 above)
Comment (jsnajdr) [reply client/blocks/reader-full-post/wp-iframe-resize.js]: Now this will break when used by two components in parallel 🙁 

What about returning an unsubscribe callback instead of having the `removeListener` param?

Then usage inside `useEffect` hook is trivial, and for class components we do:
```js
componentDidMount() {
  this.stopResize = wpIframeResize( this.postContentWrapper.current );
}

componentWillUnmount() {
  this.stopResize();
}
```

File: client/blocks/reader-full-post/wp-iframe-resize.js [hunk 10]
```diff
@@ -0,0 +1,83 @@
...
+
+		source.removeAttribute( 'style' );
+
+		/* Resize the iframe on request. */
+		if ( 'height' === data.message ) {
+			let height;
+			height = parseInt( data.value, 10 );
+			if ( height > 1000 ) {
+				height = 1000;
+			} else if ( ~~height < 200 ) {
```
Comment (jsnajdr) [inline client/blocks/reader-full-post/wp-iframe-resize.js]: I don't know what the `~~` does here even after looking it up on StackOverflow. It's an alternative to `Math.floor` but here `height` is always an integer because it was returned by `parseInt`.

Comment (cpapazoglou) [reply client/blocks/reader-full-post/wp-iframe-resize.js]: Looking at it more thoroughly doesn't make sense to me either. It seems it was added here https://core.trac.wordpress.org/changeset/35478 as an effort to make sure that `height` is a number.

Thinking it a bit more, I am not sure if we even need to limit the `height` to `200 <= height <= 1000`
How would you feel removing the conditionals and just do `source.height = parseInt( data.value, 10 );`

File: client/blocks/reader-full-post/index.jsx (hunk 5 above)
Comment (cpapazoglou) [reply client/blocks/reader-full-post/index.jsx:511]: Nope, `iFrames` are children of `figure` and are stripped from excerpts here https://github.com/Automattic/wp-calypso/blob/4abde5793955a3bb230acbc0515e3ad93741d6e2/client/lib/post-normalizer/rule-create-better-excerpt.js#L58-L60

File: client/blocks/reader-full-post/wp-iframe-resize.js (hunk 7 above)
Comment (cpapazoglou) [reply client/blocks/reader-full-post/wp-iframe-resize.js]: Sorry for my naive implementation. Your suggestion makes sense, is that ok now 683528a?

File: client/blocks/reader-full-post/index.jsx [hunk 11]
```diff
@@ -151,6 +157,8 @@ export class FullPostView extends React.Component {
 		KeyboardShortcuts.off( 'like-selection', this.handleLike );
 		KeyboardShortcuts.off( 'move-selection-down', this.goToNextPost );
 		KeyboardShortcuts.off( 'move-selection-up', this.goToPreviousPost );
+		// Remove WPiFrameResize listener.
+		this.stopResize();
```
Comment (jsnajdr) [inline client/blocks/reader-full-post/index.jsx]: This should be `this.stopResize?()`. Otherwise it will crash when `this.stopResize` is not assigned a function, like when `this.postContentWrapper.current` is null.

File: client/blocks/reader-full-post/wp-iframe-resize.js [hunk 12]
```diff
@@ -0,0 +1,82 @@
...
+				if ( targetURL.host === sourceURL.host ) {
+					if ( document.activeElement === source ) {
+						window.top.location.href = data.value;
+					}
+				}
+			}
+		}
+	};
+
+	window.addEventListener( 'message', receiveEmbedMessage, false );
```
Comment (jsnajdr) [inline client/blocks/reader-full-post/wp-iframe-resize.js]: The third `false` argument can be omitted. The `message` event doesn't bubble through the DOM and there are no bubble/capture phases for the event.

File: client/blocks/reader-full-post/wp-iframe-resize.js (hunk 9 above)
Comment (jsnajdr) [reply client/blocks/reader-full-post/wp-iframe-resize.js]: > How would you feel removing the conditionals and just do `source.height = parseInt( data.value, 10 );`

@cpapazoglou I would keep at least the upper limit. When debugging the patch, I noticed the `height` event is sent not only once, but several times before stabilizing at the final value. For example, it's sent [when the iframe resizes](https://github.com/WordPress/WordPress/blob/master/wp-includes/js/wp-embed-template.js#L188).

Without the upper limit, I'm afraid that we'll fail to stop some infinite loops where the height grows indefinitely.

File: client/blocks/reader-full-post/wp-iframe-resize.js (hunk 10 above)
Comment (cpapazoglou) [reply client/blocks/reader-full-post/wp-iframe-resize.js]: Done here be29e42

File: client/blocks/reader-full-post/wp-iframe-resize.js (hunk 12 above)
Comment (cpapazoglou) [reply client/blocks/reader-full-post/wp-iframe-resize.js]: TIL! 840cdd2

File: client/blocks/reader-full-post/index.jsx (hunk 11 above)
Comment (cpapazoglou) [reply client/blocks/reader-full-post/index.jsx]: Good catch and TIL 👍 90c8709

File: client/blocks/reader-full-post/wp-iframe-resize.js (hunk 10 above)
Comment (jsnajdr) [reply client/blocks/reader-full-post/wp-iframe-resize.js]: @cpapazoglou Did you see my comment here? https://github.com/Automattic/wp-calypso/pull/54410#discussion_r669523230

**Comment by cpapazoglou** [comment]
@jsnajdr regarding https://github.com/Automattic/wp-calypso/pull/54410#discussion_r669523230, if we fall into a loop what will be the difference of either `height = 1000` or `height = real_height_>_1000`? It won't stop the code from running again and again. 

Without upper limit, at least there is a chance of displaying correctly big posts like this (`1394px`)

**Review by jsnajdr — APPROVED** [review]
Approving because all feedback has been addressed and the PR is ready.

I recommend to reintroduce the upper height limit of 1000px just to be sure that infinite loops don't happen. But that's not a blocker.

**Comment by jsnajdr** [comment]
@cpapazoglou I was thinking about a case where the iframe height is set to 1000px, then the inner content expands to 1100px, triggering a `height` event that leads to iframe being resized to 1100px, then the content expands again to 1200px... But perhaps that's only hypothetical.

**Comment by cpapazoglou** [comment]
> @cpapazoglou I was thinking about a case where the iframe height is set to 1000px, then the inner content expands to 1100px, triggering a `height` event that leads to iframe being resized to 1100px, then the content expands again to 1200px... But perhaps that's only hypothetical.

It now came to my mind that we have enabled scripts in the iFrame, and as it seems  different `Themes` may introduce their embed functionality. So even if it sounds hypothetical, I have reinstated the upper limit. Thanks for pushing! 39c3455
