### PR TITLE
Plugin Details: Update the automanaged verification to also check if a marketplace product was purchased

### LINKED ISSUE #67840: Marketplace: Plugin detail settings dropdown broken with out of band install
Installing a managed plugin via plugin upload breaks this dropdown:

Screenshot_2022-09-15_14-16-04

Expected:
Screenshot_2022-09-15_14-48-03

### PR DESCRIPTION
**Pull request by WBerredo**
#### Proposed Changes

* Show the *management area* on the sidebar for all installed plugins and not only plugins with subscriptions. This would also cover the uploaded marketplace plugins
* Update the auto-managed check to also verify if a marketplace product was purchased. An uploaded Marketplace product is not considered auto-managed.

##### Uploaded Plugin
* Upload a Markeplace plugin. Ex: `woocommerce-shipment-tracking`
* Go to the plugin details page of this plugin. Ex: `/plugins/woocommerce-shipment-tracking/{installed_site}`
* Check if the `Enable autoupdades.` option is possible to be changed
* Check if the `Remove` option is shown on the menu

##### Purchased Plugin
* Purchase a Marketplace plugin.
* Go to the plugin details page of this plugin. Ex: `/plugins/woocommerce-shipment-tracking/{installed_site}`
* Check if the `Enable autoupdades.` option is disabled to be changed and a message about automanaged plugins is shown
* Check if the `Remove` option is NOT shown on the menu and there is the option `Manage Subscription`

| Uploaded Plugin  | Purchased Plugin (automanaged) |
| ------------- | ------------- |
|Screen Shot 2022-10-28 at 10 03 44|Screen Shot 2022-10-28 at 09 58 13|

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Fixes #67840

### CODE REVIEW

**Review by cpapazoglou — APPROVED** [review]
Tested it and LGTM!

File: client/my-sites/plugins/plugin-details-CTA/index.jsx [hunk 1]
```diff
@@ -168,7 +167,7 @@ const PluginDetailsCTA = ( { plugin, isPlaceholder } ) => {
 		return <PluginDetailsCTAPlaceholder />;
 	}
 
-	if ( isPluginInstalledOnsiteWithSubscription && sitePlugin ) {
+	if ( isPluginInstalledOnsite && sitePlugin ) {
```
Comment (cpapazoglou) [inline client/my-sites/plugins/plugin-details-CTA/index.jsx:170]: @WBerredo this change interferes with freemium (paid) plugins that show as installed even in case they don't have an active subscription.

In this paid listing you will see that the plugin is installed (the free version) but there is no purchase (see the ellipsis menu) and therefore users that have already the free version cannot purchase the paid.

CleanShot 2022-11-16 at 12 12 10@2x

Is there any reason we wanted this change?

Comment (WBerredo) [reply client/my-sites/plugins/plugin-details-CTA/index.jsx:170]: We do have another case where a marketplace plugin is active but doesn't have a purchase. That happens when you upload a premium plugin therefore it won't have a purchase associated. 

We need to find a differentiation between the two cases (freemium and premium uploaded) to show the correct CTAs for each.

Comment (WBerredo) [reply client/my-sites/plugins/plugin-details-CTA/index.jsx:170]: Do you know any property that we could use that flags it is freemium or it was uploaded?

Comment (cpapazoglou) [reply client/my-sites/plugins/plugin-details-CTA/index.jsx:170]: > We do have another case where a marketplace plugin is active but doesn't have a purchase. That happens when you upload a premium plugin therefore it won't have a purchase associated.
> 
> We need to find a differentiation between the two cases (freemium and premium uploaded) to show the correct CTAs for each.

Even in those cases, shouldn't the customer be able to buy the subscription from WordPress.com? I can understand though that "inactive" wording doesn't help, it should rather be "subscription inactive"?

Comment (WBerredo) [reply client/my-sites/plugins/plugin-details-CTA/index.jsx:170]: Currently, we either show the purchase option or we show the menu to manage the plugin installation. In those cases should we show both?

Comment (cpapazoglou) [reply client/my-sites/plugins/plugin-details-CTA/index.jsx:170]: > Currently, we either show the purchase option or we show the menu to manage the plugin installation. In those cases should we show both?

Doesn't sound good or bad - maybe it's midterm solution?

Comment (WBerredo) [reply client/my-sites/plugins/plugin-details-CTA/index.jsx:170]: I implemented this solution here: #70393
