### PR TITLE
fix(my-sites/checkout) Update informative text according to plan

### LINKED ISSUE #26847: Plans: 2-year plan manual renewal checkout displays "renews annually"
#### Steps to reproduce
For a site that has a 2-year plan which needs to be **manually** renewed...
1. Navigate to Purchases: https://wordpress.com/purchases
2. Click on the plan which needs to be renewed.
3. Click the "Renew Now"

screen shot 2018-08-23 at 7 02 08 am

4. Complete the checkout process.

#### What I expected
I expected to see language which more clearly reflected that I was renewing a plan for two additional years.

#### What happened instead
Instead I saw "renews annually" next to the "Completing your purchase" button. That could create some confusion.

screen shot 2018-08-23 at 7 04 50 am

Perhaps changing the language to something like `renews every two years` at a minimum would make it a bit clearer.

#### Browser / OS version
Chrome 68.0.3440.106 / Mac OS 10.13.6

#### Context / Source
Thanks to @allykmyta for noticing something wasn't quite right when helping a user in chat.

### PR DESCRIPTION
**Pull request by Hywan**
The information text was “renews annually”, which is only true for
yearly plan. This patch adds two other information texts: “renews
biennially” and “renews monthly”.

Fix #26847.

### CODE REVIEW

File: client/my-sites/checkout/checkout/subscription-text.jsx [hunk 1]
```diff
@@ -15,14 +16,27 @@ import { cartItems } from 'lib/cart-values';
...
-				</span>
-			);
+		const { cart, translate } = this.props;
+
+		if ( cartItems.hasRenewalItem( cart ) ) {
+			const product = cart.products[ 0 ];
+			let informative_text = '';
+
+			if ( isBiennially( product ) ) {
+				informative_text = translate( 'renews biennially', {
```
Comment (rralian) [inline client/my-sites/checkout/checkout/subscription-text.jsx]: IMHO many people get confused by this term, not knowing positively whether it means once every two years or twice per year. If we have the space I would recommend changing this to "renews every two years".

Comment (Hywan) [reply client/my-sites/checkout/checkout/subscription-text.jsx]: Done :-).
