### PR TITLE
Permafail E2E: fix Google Authentication spec.

### LINKED ISSUE #75674: Permafail E2E: Enter Google password
### Spec file

https://teamcity.a8c.com/test/-2414616547121257762?currentProjectId=calypso_WebApp

### TeamCity ID

_No response_

### Logs

```
locator.waitFor: Error: strict mode violation: locator('input[type="password"]') resolved to 2 elements:
1) <input tabindex="-1" class="F29zPe" type="password" jsn…/> aka locator('input[name="hiddenPassword"]')
    2) <input dir="ltr" tabindex="0" type="password" jsname="Y…/> aka getByRole('textbox', { name: 'Enter your password' })
=========================== logs ===========================
waiting for locator('input[type="password"]') to be visible
  locator resolved to hidden <input tabindex="-1" class="F29zPe" type="password" jsn…/>
  locator resolved to hidden <input tabindex="-1" class="F29zPe" type="password" jsn…/>
  locator resolved to hidden <input tabindex="-1" class="F29zPe" type="password" jsn…/>
  locator resolved to hidden <input tabindex="-1" class="F29zPe" type="password" jsn…/>
  locator resolved to hidden <input tabindex="-1" class="F29zPe" type="password" jsn…/>
  locator resolved to hidden <input tabindex="-1" class="F29zPe" type="password" jsn…/>
============================================================
    at GoogleLoginPage.waitUntilStable (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/external/google-login-page.ts:35:12)
    at GoogleLoginPage.enterPassword (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/external/google-login-page.ts:66:3)
    at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/authentication/authentication__google.ts:50:3)
```

### PR DESCRIPTION
**Pull request by worldomonation**
Fixes https://github.com/Automattic/wp-calypso/issues/75674.

## Proposed Changes

This PR fixes the permanently failing Google Authentications spec within the Authentications suite of specs.

Key changes:
- update POMs to use accessible locators.
- codify expected URL in the test steps.
- handle the double 2FA challenge that Google is sending our test account. I have not seen this in actual user accounts before and I have structured the E2E spec to handle the scenario where Google returns to a single 2FA challenge.

## Testing Instructions

Ensure the following build configurations are passing:
  - [x] Authentication E2E

Authentication E2E suite (limited to the Google Authenticate scenario, to save on SMS costs) passed:
image

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: test/e2e/specs/authentication/authentication__google.ts [hunk 1]
```diff
@@ -8,67 +8,105 @@
...
-			const totpClient = new TOTPClient( credentials.totpKey as string );
-			const code = totpClient.getToken();
+	// In a game of cat and mouse, Google now appears to require
+	// two 2FA challege for our `googleLoginUser` account.
+	// It is not known why, but the most likely explanation is that
+	// this spec has tripped something in the Google backend.
+	// The result is that the user is required to enter two sets of
+	// TOTP codes, and because the TOTP codes regenerate every 30s
+	// this means the spec has to wait until the TOTP code updates.
+	// This behavior was confirmed manually by @worldomonation as well.
```
Comment (karenroldan) [inline test/e2e/specs/authentication/authentication__google.ts:106]: **praise**: thank you for the detailed context on why this is added.

**Review by karenroldan — APPROVED** [review]
LGTM 🚀
