### PR TITLE
Fix misaligned labels in post list view

### LINKED ISSUE #67104: Misaligned labels in the post list view [Staging]
### Quick summary

Labels in the post list view are misaligned - staging environment 

CleanShot 2022-08-29 at 15 15 07@2x

### Steps to reproduce

1. Open https://wordpress.com/home/dotcom.wordpress.com - or any site within wordpress.com as A12s
2. Open Posts on the left sidebar
3. Look at the list view with posts
4. On the lists, labels located under the post title are misaligned 

### What you expected to happen

I expect all the labels aligned horizontally

### What actually happened

Labels under the post title are not aligned horizontally making it look clunky 

### Context

_No response_

### Platform (Simple, Atomic, or both?)

_No response_

### Theme-specific issue?

_No response_

### Browser, operating system and other notes

Mac OS, 12.5 
Chrome Version 104.0.5112.101 (Official Build) (arm64)

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

There is no user impact

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by wojtekn**
#### Proposed Changes

In this PR, I propose to fix the alignment problem in the post block on the list of posts.

The issue was reported for Chrome, but I couldn't reproduce it in Chrome. I reproduced it in Safari, though.

fixed

#### Testing Instructions

1. Navigate to the site's Post list page
2. Confirm that date is not misaligned with post stats

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] ~~[Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?~~
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] ~~Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)~~
- [ ] ~~Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?~~
- [ ] ~~For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?~~

Fixes https://github.com/Automattic/wp-calypso/issues/67104

### CODE REVIEW

File: client/my-sites/post-relative-time-status/index.jsx [hunk 1]
```diff
@@ -225,12 +225,12 @@ class PostRelativeTime extends PureComponent {
 		const { showPublishedStatus, post } = this.props;
 		const timeText = this.getTimeText();
 		let innerText = (
-			<span>
+			<>
```
Comment (wojtekn) [inline client/my-sites/post-relative-time-status/index.jsx:228]: I couldn't figure out the exact fix on the rendered item height level - it was something around `inline-block` and `vertical-align`. However, I realized the issue was gone when I removed this `span` element.

I think it should be good as it was added more than seven years ago and we didn't have React fragments then.

File: client/my-sites/post-relative-time-status/style.scss [hunk 2]
```diff
@@ -34,7 +34,7 @@ a.post-relative-time-status__link {
 .post-relative-time-status__time,
 .post-relative-time-status__status {
 	display: inline-block;
-	margin-right: math.div(11, 12)  * 1em;
+	margin-right: 2em;
```
Comment (wojtekn) [inline client/my-sites/post-relative-time-status/style.scss]: I've increased that margin because even with the fix, there was still the illusion that elements were not aligned.

It may happen because the date text ends with only x-height letters, with the descender in "g", and the stats text starts with digits and uppercase letters.

**Review by danielbachhuber — COMMENTED** [review]
Looks better in my testing for Chrome and Firefox:

**Chrome**

image

**Firefox**

image

Safari seems marginally off, however...

image

Assigning `height: 20px` to `span.post-item__meta-time-status` and `ul.post-action-counts` seems to have everything line up even better:

image

Also, I noticed the ellipsis menu is all of the way to the right on Firefox and Safari:

image

Easy to fix that too?

**Comment by wojtekn** [comment]
Thanks @danielbachhuber . I can't observe your findings in my environment. For me, it worked well in Chrome even before my changes.

I've just checked Firefox and Safari - I reproduced the problem on production in both browsers. Then I checked this PR, and it fixes the problem in both, and in Chrome, it's still good. When I apply 20px height you proposed, it becomes 1px odd in Chrome.

@mpkelly would you mind taking look at this?

**Comment by mpkelly** [comment]
Chrome looks okay, but I can see a problem using Safari. The icon and text is slightly higher than the clock icon:

image

I tried Calypso Live and Calypso local, but I can't log in using Safari. I get some security errors:

image

Here's Chrome using prod and Calypso Live:

image

**Comment by wojtekn** [comment]
@mpkelly you need to disable "Prevent cross-site tracking" in Settings -> Privacy to sign in on those test environments in Safari.

As regards alignment, yeah, it looks the icon also is not aligned perfectly, but I was focusing on fixing the misalignment between the date text and stats here.

**Comment by wojtekn** [comment]
> Also, I noticed the ellipsis menu is all of the way to the right on Firefox and Safari:

@danielbachhuber would you mind adding a separate ticket for that? I've checked it, but couldn't find an obvious fix. This doesn't look related to browsers. I reproduce the issue in all browsers but only on environments other than production and staging. It seems that additional CSS code is loaded for `.button.is-borderless` on those environments, and it resets padding to 0.

**Comment by danielbachhuber** [comment]
> I've checked it, but couldn't find an obvious fix. This doesn't look related to browsers. I reproduce the issue in all browsers but only on environments other than production and staging. It seems that additional CSS code is loaded for `.button.is-borderless` on those environments, and it resets padding to 0.

@wojtekn Great debugging!

> would you mind adding a separate ticket for that?

Yep, done: https://github.com/Automattic/wp-calypso/issues/71007

File: client/my-sites/post-relative-time-status/style.scss [hunk 3]
```diff
@@ -34,7 +34,7 @@ a.post-relative-time-status__link {
 .post-relative-time-status__time,
 .post-relative-time-status__status {
 	display: inline-block;
```
Comment (sejas) [inline client/my-sites/post-relative-time-status/style.scss]:
```suggestion
	display: flex;
	align-items: center;
```

**Review by sejas — COMMENTED** [review]
> The icon and text is slightly higher than the clock icon

Same for me in Safari.
I've added a suggestion that it improves the icon alignment too.
I prefer using flex and align-items center.

| **Env** | **Screenshot** |
|---|---|
| **PRO** | pro |
| **Pull Request** | pr |
| **Suggestion** | changes |

**Comment by wojtekn** [comment]
Thanks for the suggestion @sejas . It looks aligned well in all three browsers now:

| **Browser** | **Screenshot** |
|---|---|
| **Chrome** | fix-4-chrome |
| **Safari** | fix-4-safari |
| **Firefox** | fix-4-firefox |

**Review by sejas — APPROVED** [review]
Looking good !! 👍
