### PR TITLE
Pages: only show blog-posts page in published filter.

### LINKED ISSUE #4218: Pages: "Blog Posts" pseudo-item also shown in trash
#### Steps to reproduce

Starting at `/pages/published/foo.wordpress.com`:

calypso-pages-trash

#### What I expected

The trash tab should only display actual trashed pages — in this case, _Test Page_.

#### What happened instead

The _Posts_ ("Artigos", in pt-pt) pseudo-item is shown, potentially leading to a lot of confusion.

#### Browser / OS version

- Chrome Version 49.0.2623.87 (64-bit)
- OS X 10.11.3

### PR DESCRIPTION
**Pull request by mtias**
Fixes #4218.

### CODE REVIEW

File: client/my-sites/pages/page-list.jsx [hunk 1]
```diff
@@ -243,7 +243,7 @@ var Pages = React.createClass({
 
 		const site = this.props.sites.getSelectedSite();
 
-		if ( site && site.options && site.options.show_on_front === 'posts' ) {
+		if ( this.props.status === 'published' && site && site.options && site.options.show_on_front === 'posts' ) {
```
Comment (dmsnell) [inline client/my-sites/pages/page-list.jsx]: would this be a fitting time to bring in a helper to clean up the nested data get?

```js
import get from 'lodash/get';

if ( this.props.status === 'published' && get( site, 'options.show_on_front' ) === 'posts' ) {
	…
}
```

or alternatively

```js
import matchesProperty from 'lodash/matchesProperty';

if ( this.props.status === 'published' && matchesProperty( 'options.show_on_front', 'posts' )( site ) ) {
```

**Comment by dmsnell** [comment]
One small question about code style, but looks good to merge anyway
