### PR TITLE
Plans 2023: Fix large-currency logic issues. More consistent application in comparison grid.

### LINKED ISSUE #79220: The plans comparison table is broken in /plans when owning a highlighted plan.
Originally reported in https://github.com/Automattic/wp-calypso/pull/79122#issuecomment-1628492795. tl;dr: when visiting /plans using a site on a highlighted plan, e.g. the Premium plan, the comparison table will be broken:

Image

@chriskmnds later found the code that potentially caused the breakage in https://github.com/Automattic/wp-calypso/pull/79122#issuecomment-1628606672.

### PR DESCRIPTION
**Pull request by chriskmnds**
Related to https://github.com/Automattic/wp-calypso/issues/79220

## Proposed Changes

- Fixes some large-currency-related issues in code, and may or may not fix https://github.com/Automattic/wp-calypso/issues/79220
- The current method was not working consistently for the comparison grid
- A few more issues with how we'd condition around the thresholds for the combined pricing (original + discount). I think this was more accidentally working so far.
- Fixes/aligns prices in the grid when discounted

### Comparison Grid

- **Before**
  Screenshot 2023-11-21 at 1 32 23 PM 

- **After (is-large-currency conditions properly applied)**
  Screenshot 2023-11-21 at 1 32 15 PM

### Features Grid & Comparison Grid

- **Before**

Screenshot 2023-11-21 at 1 33 13 PM

- **After (prices aligned - better?)**

Screenshot 2023-11-21 at 1 33 06 PM

### Signup

- **Before (looks like incorrect is-large-currency conditioning)**

Screenshot 2023-11-21 at 2 29 41 PM

- **After** 

Screenshot 2023-11-21 at 2 29 56 PM

## Testing Instructions

- Go to `/plans` and `/start/plans` with currency & plan combinations that will force discounts
- Ensure prices render as expected

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: client/my-sites/plans-grid/hooks/use-plan-pricing-info-from-grid-plans.ts [hunk 1]
```diff
@@ -26,10 +26,10 @@ export function usePlanPricingInfoFromGridPlans( {
 
 					return {
 						prices: [ ...acc.prices, originalPriceForTerm, discountedPriceForTerm ],
-						...( currencyCode && { currencyCode } ),
```
Comment (chriskmnds) [inline client/my-sites/plans-grid/hooks/use-plan-pricing-info-from-grid-plans.ts:29]: If my reading is correct, this would always result in `undefined` if the last plan iterated was a non-priced plan. So this and the rest of the logic outside effectively always resulted in `USD` being the evaluated currency. That's incorrect as it prefixes prices with `US` when formatting (so you'd always get 2 more symbols in the calculation of is-large-currency).

cc @jeyip to confirm in case I miss something?

File: client/my-sites/plans-grid/hooks/npm-ready/use-is-large-currency.ts [hunk 2]
```diff
@@ -35,27 +35,26 @@ function hasExceededPriceThreshold( displayPrices?: string[], isAddOn = false )
...
-		if ( ! originalPrice || ! discountedPrice ) {
-			planPrices.push( price );
-			return;
+		if ( originalPrice.length + discountedPrice.length > LARGE_CURRENCY_COMBINED_CHAR_THRESHOLD ) {
+			return true;
 		}
+	}
 
-		exceedsThreshold =
-			originalPrice.length + discountedPrice.length > LARGE_CURRENCY_COMBINED_CHAR_THRESHOLD;
```
Comment (chriskmnds) [inline client/my-sites/plans-grid/hooks/npm-ready/use-is-large-currency.ts:52]: Similar to my other comment. This would reflect the last iterated set of prices, which seems incorrect. We want this to reflect any excess of the threshold from any price pair, right? (so not sure if this part ever worked outside of accidentally 🤔 )

cc @jeyip to confirm in case I miss something?

File: client/my-sites/plans-grid/hooks/use-plan-pricing-info-from-grid-plans.ts (hunk 1 above)
Comment (jeyip) [reply client/my-sites/plans-grid/hooks/use-plan-pricing-info-from-grid-plans.ts:29]: I'm going to summarize to make sure I understand correctly, so please feel free to correct any misunderstandings on my part.

- I believe what you're conveying is that if the last `gridPlan` in the iteration has some `undefined` `currencyCode` value, then existing logic interprets the currency for all plans to be `USD`
- If my understanding above sounds right, then what you're saying is definitely correct -- I didn't consider that some `gridPlans` might have a meaningful `currencyCode` value while others wouldn't, and assumed that the `currencyCode` for the final `gridPlan` would be representative of all `gridPlans`. Giving this more consideration, I'm assuming that one example where we run into this problem is something like the VIP enterprise plan?
- If you're comfortable with it, I'm happy to add unit tests in this PR or as a follow-up. I'll also be sure to give more consideration to non-priced plans in the future. Thanks for bringing this to my attention 🙏

File: client/my-sites/plans-grid/hooks/npm-ready/use-is-large-currency.ts (hunk 2 above)
Comment (jeyip) [reply client/my-sites/plans-grid/hooks/npm-ready/use-is-large-currency.ts:52]: > so not sure if this part ever worked outside of accidentally 🤔

I believe you're correct here as well -- the logic wasn't working as intended. If anything, it seems like it was only capturing the results of the final `gridPlan`. I notice some updated conditional logic which appears to make sense. I'll take a closer look and test this PR first thing when I'm online on Monday

Thanks again for raising these questions Christos

File: client/my-sites/plans-grid/hooks/use-plan-pricing-info-from-grid-plans.ts (hunk 1 above)
Comment (chriskmnds) [reply client/my-sites/plans-grid/hooks/use-plan-pricing-info-from-grid-plans.ts:29]: Yep, that's what I think is going on too.

> VIP enterprise plan?

Indeed. Any sort of non-priced plan will force `USD` to be the currency that's evaluated (given the current logic)

File: client/my-sites/plans-grid/hooks/npm-ready/use-is-large-currency.ts (hunk 2 above)
Comment (chriskmnds) [reply client/my-sites/plans-grid/hooks/npm-ready/use-is-large-currency.ts:52]: Gotcha. Thanks for clarifying @jeyip 

> I'll take a closer look and test this PR first thing when I'm online on Monday

Super! Thank you :-)

Comment (jeyip) [reply client/my-sites/plans-grid/hooks/npm-ready/use-is-large-currency.ts:52]: Taking a look now 👀

Comment (jeyip) [reply client/my-sites/plans-grid/hooks/npm-ready/use-is-large-currency.ts:52]: I'm seeing some divergent spacing of plan header prices between this branch and production + `trunk`, even when there are _no_ discounted plans. Taking a closer look...

| Branch      | Production and `trunk` |
| ----- | ----- |
| Screenshot 2023-12-04 at 11 11 17 AM   | Screenshot 2023-12-04 at 11 11 22 AM |

File: client/my-sites/plans-grid/components/header-price.tsx [hunk 3]
```diff
@@ -205,14 +209,38 @@ const PlanFeatures2023GridHeaderPrice = ( {
...
-						currencyCode={ currencyCode }
-						rawPrice={ originalPrice.monthly }
-						displayPerMonthNotation={ false }
-						isLargeCurrency={ isLargeCurrency }
-						isSmallestUnit={ true }
-						priceDisplayWrapperClassName="plans-grid-2023__html-price-display-wrapper"
-					/>
+					{ isLargeCurrency ? (
+						<PricesGroup isLargeCurrency={ isLargeCurrency }>
+							<PlanPrice
```
Comment (jeyip) [inline client/my-sites/plans-grid/components/header-price.tsx:214]: The addition of this placeholder `PlanPrice` component with styling `visibility: hidden;` leads to a div with empty content that still affects layout ( when there is no discounted price ) See this comment https://github.com/Automattic/wp-calypso/pull/84349/files#r1414366115

Screenshot 2023-12-04 at 1 46 13 PM

I do, however, recognize that one of the intentions of this PR is to fix alignment issues, so I'll try and wrap my head around the solution here and what might be done about this

_Edit:_

For anyone else that happens to be reading this, here's a visual of why the placeholder is necessary for a plan even if it's not discounted when _other_ plans happen to be discounted. Otherwise we run into the misalignment problem described in the original issue

| With this branch      | Without this branch |
| ----- | ----- |
| Screenshot 2023-12-04 at 2 12 11 PM   | Screenshot 2023-12-04 at 2 12 05 PM        |

File: client/my-sites/plans-grid/components/header-price.tsx [hunk 4]
```diff
@@ -205,14 +209,38 @@ const PlanFeatures2023GridHeaderPrice = ( {
...
 					) }
-					<PlanPrice
-						currencyCode={ currencyCode }
-						rawPrice={ originalPrice.monthly }
-						displayPerMonthNotation={ false }
-						isLargeCurrency={ isLargeCurrency }
-						isSmallestUnit={ true }
-						priceDisplayWrapperClassName="plans-grid-2023__html-price-display-wrapper"
-					/>
+					{ isLargeCurrency ? (
```
Comment (jeyip) [inline client/my-sites/plans-grid/components/header-price.tsx]: @chriskmnds I believe if you add the `isAnyVisibleGridPlanDiscounted` condition here it should resolve [ any spacing oddness ]( https://github.com/Automattic/wp-calypso/pull/84349/files#r1414366115 ) we were seeing while still maintaining the original spirit of this PR, which was to fix alignment issues. It seems like we only want the placeholder to exist if _at least_ one other plan is discounted in the grid. Curious to hear your thoughts on this though 🤔 

```suggestion
					{ isLargeCurrency && isAnyVisibleGridPlanDiscounted ? (
```

**Comment by jeyip** [comment]
## Testing
### Requirements

Flows:
- [x] /start
- [x] /plans

Currencies:
- [x] MXN to test a currency discounted plan
- [x] IDR to test the longest currency
- [x] USD

For each of the flows listed below:
- [x] Verify that plan header pricing is displayed properly ( and aligned ) in features grid
- [x] Verify that discounted plan header pricing is displayed properly ( and aligned ) in features grid
- [x] Verify that plan header pricing is displayed properly ( and aligned ) in comparison grid
- [x] Verify that discounted plan header pricing is displayed properly ( and aligned ) in comparison grid
- [x] Verify that prices are correct
- [x] Verify that storage add-on upgrades update pricing as expected
- [x] Verify that plan credits display properly ( only tested with USD )

### Browsers
- [x] Chrome

**Note:**
Thanks to Christos spotting flawed logic in large currency calculations, there are now instances where calculations are being handled properly, like MXN. Whereas before, they'd overflow in the plans comparison grid, they are now being displayed as expected.

+1 from me when discussions about spacing are resolved in https://github.com/Automattic/wp-calypso/pull/84349#discussion_r1414578795. If this isn't merged by tomorrow, I'll test out other currencies with this PR as well.

File: client/my-sites/plans-grid/components/header-price.tsx (hunk 4 above)
Comment (chriskmnds) [reply client/my-sites/plans-grid/components/header-price.tsx]: that does it @jeyip . Thank you :-)

I'm also renaming `shouldShowDiscountedPrice` to `isGridPlanDiscounted` to be consistent with `isAnyVisibleGridPlanDiscounted`

**Comment by chriskmnds** [comment]
@jeyip one thing I notice now is that when a "isLargeCurrency" exists for the combined (discounted/crossed-out price), the resulting render minimizes the individual prices, whilst they could individually fit into the box:

Screenshot 2023-12-05 at 3 41 56 PM

I'm going to merge this PR cause it fixes several other issues with the calculations. I'm happy to deal with the above, unless it's something that you want to follow-up on (as having put together the framework for computing large currency - in case you'd be interested) :-)

**Comment by jeyip** [comment]
> @jeyip one thing I notice now is that when a "isLargeCurrency" exists for the combined (discounted/crossed-out price), the resulting render minimizes the individual prices, whilst they could individually fit into the box:

> I'm happy to deal with the above, unless it's something that you want to follow-up on (as having put together the framework for computing large currency - in case you'd be interested) :-)

Yeah the existing logic is, at best, an approximation of when a currency will overflow its container 😮‍💨

I didn't get a chance to take a closer look at this today, but I can keep this on my radar and try taking a closer look later this week or early next week if that works for us 🙂
