### PR TITLE
Focused Launch: fix Summary View plan step placeholders

### LINKED ISSUE #48621: Focused Launch: expected placeholders are not displayed for plan step
When opening Focused Launch modal, there should be at least 2 placeholder items displayed for plan step before loading plans data.

#### Screenshot / Video
- with selected plan (1 placeholder): https://cloudup.com/c8L49JyauAc (this is because of a bug that should be fixed in https://github.com/Automattic/wp-calypso/pull/48619)
- without selected plan (no placeholder): https://cloudup.com/cqTPtf6x5WN

### PR DESCRIPTION
**Pull request by razvanpapadopol**
#### Changes proposed in this Pull Request

* Render the correct number of loading placeholders for the plan step in Summary View. At the moment there are 2 placeholders expected (for popular paid plan and free plan). 

#### Testing instructions

* When opening focused launch on a poor connection (or even offline), the correct number of placeholders should be displayed for the plan step before data is loaded.

Fixes #48621

### CODE REVIEW

File: packages/launch/src/focused-launch/summary/index.tsx [hunk 1]
```diff
@@ -302,9 +302,11 @@ const PlanStep: React.FunctionComponent< PlanStepProps > = ( {
...
 	const { sitePlan } = useSite();
 
-	const allAvailablePlans = [ defaultPaidPlan, nonDefaultPaidPlan, defaultFreePlan ].filter(
-		Boolean
-	) as Plan[];
+	const allAvailablePlans: ( Plan | undefined )[] = [
+		defaultPaidPlan,
+		...( nonDefaultPaidPlan ? [ nonDefaultPaidPlan ] : [] ),
+		defaultFreePlan,
+	];
```
Comment (alshakero) [inline packages/launch/src/focused-launch/summary/index.tsx]: Small nit, it might be easier to read like this:
```suggestion
	const allAvailablePlans: ( Plan | undefined )[] = nonDefaultPaidPlan
		? [ defaultPaidPlan, nonDefaultPaidPlan, defaultFreePlan ]
		: [ defaultPaidPlan, defaultFreePlan ];
```

**Review by alshakero — APPROVED** [review]
Reviewed and tested. LGTM.
