### PR TITLE
Flaky E2E: tweaks to the SupportComponent and Help Centre test expectations.

### LINKED ISSUE #78968: Flaky E2E: Help Doc article is shown
### Spec file

specs/help-center/help-center__general-interaction.ts

### TeamCity ID

10321966

### Logs

image

```
======= Failed test run #1 ==========
  locator.waitFor: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for locator('.help-center__container').getByRole('article').getByRole('heading').first() to be visible
  ============================================================
  at SupportComponent.waitFor [as getOpenArticleTitle] (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/support-component.ts:106:17)
      at Object.getOpenArticleTitle (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/help-center/help-center__general-interaction.ts:42:48)
      at Promise.then.completed (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:293:28)
      at callAsyncCircusFn (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:226:10)
      at _callCircusTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:297:40)
      at _runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:233:3)
      at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:135:9)
      at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:130:9)
      at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:130:9)
      at run (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:68:3)
      at runAndTransformResultsToJestFormat (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
      at jestAdapter (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
      at runTestInternal (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:367:16)
      at runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:444:34)
      at Object.worker (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/testWorker.js:106:12)
======= Failed test run #2 ==========
  locator.waitFor: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for locator('.help-center__container').getByRole('article').getByRole('heading').first() to be visible
  ============================================================
  at SupportComponent.waitFor [as getOpenArticleTitle] (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/support-component.ts:106:17)
      at Object.getOpenArticleTitle (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/help-center/help-center__general-interaction.ts:42:48)
      at Promise.then.completed (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:293:28)
      at callAsyncCircusFn (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:226:10)
      at _callCircusTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:297:40)
      at _runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:233:3)
      at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:135:9)
      at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:130:9)
      at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:130:9)
      at run (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:68:3)
      at runAndTransformResultsToJestFormat (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
      at jestAdapter (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
      at runTestInternal (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:367:16)
      at runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:444:34)
```

### PR DESCRIPTION
**Pull request by worldomonation**
Fixes https://github.com/Automattic/wp-calypso/issues/78968.

## Proposed Changes

This PR makes two tweaks to the Help Centre spec:
- add a `waitForResponse` when accessing a help doc.
- generate the promise prior to the popup, then resolve the promise in the same test step.

## Testing Instructions
Ensure the following build configurations are passing:
  - [x] Calypso E2E (desktop)
  - [x] Calypso E2E (mobile)

It would appear the changes are stable, but we'll see how it behaves in production.
image

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: packages/calypso-e2e/src/lib/components/support-component.ts [hunk 1]
```diff
@@ -101,7 +107,7 @@ export class SupportComponent {
 	 * @returns {string} Title of the article.
 	 */
 	async getOpenArticleTitle(): Promise< string > {
-		const locator = this.anchor.getByRole( 'article' ).getByRole( 'heading' ).nth( 0 );
+		const locator = this.anchor.getByRole( 'article' ).getByRole( 'heading' ).first();
```
Comment (worldomonation) [inline packages/calypso-e2e/src/lib/components/support-component.ts:110]: This effectively changes nothing, because the TypeScript transpiler already converts the `.nth(0)` command to a `.first()`.

File: test/e2e/specs/help-center/help-center__general-interaction.ts [hunk 2]
```diff
@@ -58,11 +60,13 @@ describe( 'Help Center: Interact with Results', function () {
 		} );
 
 		it( 'Click on the first Calypso Link result', async function () {
+			const popupEvent = page.waitForEvent( 'popup' );
 			await supportComponent.clickResultByIndex( 'Calypso Link', 0 );
+			popupPage = await popupEvent;
```
Comment (worldomonation) [inline test/e2e/specs/help-center/help-center__general-interaction.ts:65]: This pattern is now suggested by Playwright docs: https://playwright.dev/docs/pages#handling-popups

**Review by karenroldan — APPROVED** [review]
LGTM! 🚀
