### PR TITLE
Jetpack Onboarding: Restart flow when credentials are missing

### LINKED ISSUE #21688: Jetpack Onboading: Guard against missing credentials
Currently, if we land in the Jetpack Onboarding flow by just visiting one of the steps, and we try to load/save anything, the request will fail, because Calypso's currently missing the site's onboarding credentials.

To avoid cases like this, we should add a mechanism to reinitialize the JPO flow. So if the onboarding credentials are missing, we should redirect to wp-admin to obtain them again, and redirect back to the JPO flow properly.

### PR DESCRIPTION
**Pull request by tyxla**
This PR implements a mechanism to restart the Jetpack Onboarding flow if we visit the flow and we don't have credentials yet.

Fixes #21688.

To test:

* Checkout this branch
* Go to http://calypso.localhost:3000/jetpack/onboarding/:site, where `:site` is the slug of one of your non-connected Jetpack sites.
* Verify you're presented with a WP loading logo and after a short redirect loop you're redirected back to the JPO flow with JPO credentials loaded in Calypso.
* Start the onboarding flow from wp-admin (`?page=jetpack&action=onboard&calypso_env=development`)
* Verify the JPO flow works like it did before.

### CODE REVIEW

File: client/jetpack-onboarding/main.jsx [hunk 1]
```diff
@@ -27,22 +29,43 @@ class JetpackOnboardingMain extends React.PureComponent {
...
+						basePath="/jetpack/onboarding"
+						baseSuffix={ siteSlug }
+						components={ COMPONENTS }
+						siteId={ siteId /* Passed down to individual steps */ }
+						steps={ steps }
+						stepName={ stepName }
+						hideNavigation={ stepName === STEPS.SUMMARY }
+					/>
+				) : (
+					<div className="jetpack-onboarding__loading wpcom-site__logo noticon noticon-wordpress" />
```
Comment (tyxla) [inline client/jetpack-onboarding/main.jsx]: We probably can do this one better....

File: client/jetpack-onboarding/main.jsx [hunk 2]
```diff
@@ -27,22 +29,43 @@ class JetpackOnboardingMain extends React.PureComponent {
...
+			const siteDomain = siteSlug.replace( '::', '/' );
+			const url = addQueryArgs(
+				{
+					page: 'jetpack',
+					action: 'onboard',
+					calypso_env: config( 'env_id' ),
+				},
+				`//${ siteDomain }/wp-admin/admin.php`
+			);
+			externalRedirect( url );
```
Comment (tyxla) [inline client/jetpack-onboarding/main.jsx]: I'm wondering if we should try accessing the Jetpack site before redirecting to it (similar to how JPC checks it), and if it's not a valid WordPress site with Jetpack installed and activated, redirect to `/` or something...

**Comment by ockham** [comment]
Rebased.

**Comment by ockham** [comment]
...aaand rebased again 😄

**Comment by tyxla** [comment]
Rebased again and ready for review.

File: client/jetpack-onboarding/main.jsx (hunk 2 above)
Comment (ockham) [reply client/jetpack-onboarding/main.jsx]: Could be material for another iteration :slightly_smiling_face:

File: client/jetpack-onboarding/main.jsx [hunk 3]
```diff
@@ -35,7 +37,25 @@ class JetpackOnboardingMain extends React.PureComponent {
...
 	};
 
-	// TODO: Add lifecycle methods to redirect if no siteId
+	componentDidMount() {
+		const { siteId, siteSlug } = this.props;
+
+		// If we are missing the Jetpack onboarding credentials,
+		// redirect back to wp-admin so we can obtain them again.
+		if ( ! siteId && siteSlug ) {
+			const siteDomain = siteSlug.replace( '::', '/' );
```
Comment (ockham) [inline client/jetpack-onboarding/main.jsx]: Hmm, I'd rather not manually re-generate the domain from the slug, without even using a library function -- it'll be super-hard to locate this if we miss e.g. an edge case, or the implementation of the slug-to-domain mapping is ever going to allow for different cases we're not yet considering.

Can we use [this mechanism](https://github.com/Automattic/wp-calypso/blob/e373aec638e9acca56fd0c05b4a267a0a176baec/client/state/selectors/get-unconnected-site-id-by-slug.js#L21-L24) instead? That uses our existing dictionary of unconnected site URLs and a lib function instead...

That will also include the protocol and thus allow us to drop the `//` on L53, which might also cause trouble otherwise...

File: client/jetpack-onboarding/main.jsx [hunk 4]
```diff
@@ -35,7 +37,25 @@ class JetpackOnboardingMain extends React.PureComponent {
...
+			const url = addQueryArgs(
+				{
+					page: 'jetpack',
+					action: 'onboard',
+					calypso_env: config( 'env_id' ),
```
Comment (ockham) [inline client/jetpack-onboarding/main.jsx]: Maybe only add this if it's not `production`?

File: client/jetpack-onboarding/main.jsx (hunk 3 above)
Comment (ockham) [reply client/jetpack-onboarding/main.jsx]: > Can we use this mechanism instead? That uses our existing dictionary of unconnected site URLs and a lib function instead...

Scratch the part about the 'existing dictionary of unconnected site URLs', we don't have that here...

File: client/jetpack-onboarding/main.jsx (hunk 4 above)
Comment (tyxla) [reply client/jetpack-onboarding/main.jsx]: A little more specificity wouldn't hurt? Omitting that would rely on what the default values are, and by specifically passing it we disregard the default values, which sounds good to me.

**Comment by tyxla** [comment]
@ockham thanks for the review! Got any other suggestions before 🚢 ?
