### PR TITLE
People: fix prop type warning when searching for a team member

### LINKED ISSUE #20222: People: Invalid prop-type console warnings
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/people/team/:site?s=:searchTerm (use e.g. your name as a search term — it has to return results to reveal both warnings).
1. See dev console for errors:
    > Failed form propType: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`. Check the render method of `Search`.

    > Failed prop type: Invalid prop `label` of type `array` supplied to `PeopleListSectionHeader`, expected `string`.

#### What I expected

☀️ 🌷 🌷 

#### What happened instead

image

The point for the 2nd error seems to be [here in client/my-sites/people/team-list/team.jsx](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/people/team-list/team.jsx#L99)

#### Browser / OS version

Chrome 62 / MacOS High Sierra

### PR DESCRIPTION
**Pull request by Umangvaghela**
Partial fix for #20222. 

screen shot 2017-12-11 at 10 47 31

When a search is performed, it's possible for the `label` prop to be an array.

### To test

1. Visit http://calypso.localhost:3000/people/team/<yoursite.com>
2. Search for a team member (try your username)
3. Ensure that the above warning does not appear in your console

### CODE REVIEW

**Comment by bluefuton** [comment]
Thanks for the contribution @Umangvaghela. It'd be great if you could provide a bit more description about the issue you've tried to solve, what your solution is, and how to test it.

**Comment by Umangvaghela** [comment]
@bluefuton, @designsimply

When we search team member then an error is generated.
Problem : 
While we search var headerText is provide an array, not a string.

Testing instruction.
Clone to the latest calypso.
Click on the people menu and search team member.

Sir, Provide your feedback if I miss something in this PR.

Thanks,

**Comment by Umangvaghela** [comment]
@designsimply 

Hello sir can you review this PR when you get a leisure time. 

Thanks

File: client/my-sites/people/people-list-section-header/index.jsx [hunk 1]
```diff
@@ -24,7 +24,7 @@ import isSiteAutomatedTransfer from 'state/selectors/is-site-automated-transfer'
 
 class PeopleListSectionHeader extends Component {
 	static propTypes = {
-		label: PropTypes.string.isRequired,
+		label: PropTypes.string,
```
Comment (simison) [inline client/my-sites/people/people-list-section-header/index.jsx]: Why was this change needed?

**Comment by Umangvaghela** [comment]
Hello @simison 

https://github.com/Automattic/wp-calypso/pull/20280 .
To solve first console error I was do that but I update changes. I think PropTypes.string.isRequired, is fine.

And also check this PR to overcome the all error.
https://github.com/Automattic/wp-calypso/pull/20280
 
Thanks

File: client/my-sites/people/people-list-section-header/index.jsx (hunk 1 above)
Comment (bluefuton) [reply client/my-sites/people/people-list-section-header/index.jsx]: @Umangvaghela you mentioned above that the `label` prop can be an array. If it can be _either_ an array or a string, we probably want something like:

```label: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.array,
  ]).isRequired
```

Comment (Umangvaghela) [reply client/my-sites/people/people-list-section-header/index.jsx]: @bluefuton 
You want to say me to change  label: PropTypes.string.isRequired, to  label: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.array,
]).isRequired 

Am I right. 

But In this condition : 
if ( this.props.site && this.props.users.length ) {
			if ( this.props.search && this.props.totalUsers ) {
				headerText = this.props.translate(
					'%(numberPeople)d Person Matching {{em}}"%(searchTerm)s"{{/em}}',
					'%(numberPeople)d People Matching {{em}}"%(searchTerm)s"{{/em}}',
					{
						count: this.props.users.length,
						args: {
							numberPeople: this.props.totalUsers,
							searchTerm: this.props.search,
						},
						components: {
							em: <em />,
						},
					}
				);
				
			}
Var headerText is given array value. That's why the issue is happening.

You want to change only PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.array,
]).isRequired  or headerText  = headerText [0] or  both.

Thanks

Comment (simison) [reply client/my-sites/people/people-list-section-header/index.jsx]: Howdy @Umangvaghela. Check out [article about creating codeblocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/). It'll make reading code easier for everyone. :-) You can modify your comments to add those blocks. Thanks!

**Comment by Umangvaghela** [comment]
@simison 

Sir, I add changes which are suggested by @bluefuton.

Thanks

**Comment by Umangvaghela** [comment]
@simison 

Sir,  what you think on this PR,  Change are fine or not. 

Thanks

**Comment by bluefuton** [comment]
@Umangvaghela when you submit a PR in the future, it's really helpful for us if you provide:
- a meaningful title
- a good description of the issue in the first comment (screenshots are always helpful)
- step-by-step instructions

These things make it much easier for the tester and code reviewer. I've updated this issue for you.

**Comment by Umangvaghela** [comment]
@bluefuton 

Hello sir,

Can you tell me this is fine , If something is missing on that so told me so I would change it as soon as possible.

Thanks
