### PR TITLE
refactor(sftp-card): tsx, styled to scss, removed unused classNames, fixed checkbox padding, fixed cleaning up of the password

### LINKED ISSUE #95435: Server Settings: Missing padding between SSH toggle and text box
### Quick summary

The SSH access toggle and SSH command line text box are stacked together without any padding.

### Steps to reproduce

1. Have an Atomic site.
2. Look for it in wordpress.com/sites.
3. Click "Server Settings".
4. Click "Create credentials".
5. Turn on the "Enable SSH access for this site" toggle.

### What you expected to happen

SSH command line rendered below the SSH toggle with appropriate padding.

### What actually happened

SSH command line rendered right below the SSH toggle without any padding.

### Impact

All

### Available workarounds?

There is no user impact

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

The bug impacts all users with an Atomic site.

### PR DESCRIPTION
**Pull request by nightnei**
Related to https://github.com/Automattic/wp-calypso/issues/95435

## Proposed Changes
With this PR we are fixing the gap for `Enable SSH access for this site` checkbox.
And also I decided to improve a few things:
1. Rewrite sftp-card component to tsx
2. Moved `styled`-css to `.scss`, for consistency with most of the component in Calypso
3. Removed a bunch of unused classNames
4. Fixed cleaning up of the password (thanks TSX for highlighting it).
I know that in Calypso we don't force to use tsx, but I advocate everybody to do it. 4-th point is good example, during rewriting it I faced a bug. It wasn't critical, but still.
	4.1 We provided 3 arguments instead of 2 - the [function](https://github.com/Automattic/wp-calypso/pull/95474/files#diff-dbd074daac3cf148d2da3e33d4b5613dc7cb4477bf617cb2633c40ed39adcb61L411) expects `siteId, username`, but we [provide](https://github.com/Automattic/wp-calypso/pull/95474/files#diff-dbd074daac3cf148d2da3e33d4b5613dc7cb4477bf617cb2633c40ed39adcb61L100) `siteId, currentUserId, username`.
	4.2 Cleaning up process was incorrect - we invoked `destroy` function [immediately during render process](https://github.com/Automattic/wp-calypso/pull/95474/files#diff-dbd074daac3cf148d2da3e33d4b5613dc7cb4477bf617cb2633c40ed39adcb61L136), instead of [on unmounting](https://github.com/Automattic/wp-calypso/pull/95474/files#diff-dbd074daac3cf148d2da3e33d4b5613dc7cb4477bf617cb2633c40ed39adcb61R131-R140). We can see that intention was to return it, but by mistake it was immediately invoked.

### Main [issues](https://github.com/Automattic/wp-calypso/issues/95435)
1. Have an Atomic site.
2. Look for it in wordpress.com/sites.
3. Click "Server Settings".
4. Click "Create credentials".
5. Turn on the "Enable SSH access for this site" toggle.
6. Assert that checbox and input are not stacked
<table>
<tr>
<td>BEFORE
<td>AFTER
</tr>
<tr>
<td>Screenshot 2024-10-17 at 15 17 04
<td>Screenshot 2024-10-17 at 15 17 26
</tr>
</table>

### Refactor
1. Smoke test that everything looks and works the same way as before
2. TRy to reset password -> Open another tab (e.g. "Staging Site") -> Come back to "Server Settings" -> Assert that you see "Reset password" button

### CODE REVIEW

File: client/hosting/server-settings/components/sftp-card/index.tsx [hunk 1]
```diff
@@ -95,12 +94,6 @@ export const SftpCard = ( {
 
 	const sshConnectString = `ssh ${ username }@sftp.wp.com`;
 
-	const onDestroy = () => {
-		if ( password ) {
-			removePasswordFromState( siteId, currentUserId, username );
```
Comment (nightnei) [inline client/hosting/server-settings/components/sftp-card/index.tsx:100]: It's the case (4-th point from "Proposed Changes"), where we had a bug and TSX helped to highlight it - the function expects `siteId, username`, but we provide `siteId, currentUserId, username`.

File: client/hosting/server-settings/components/sftp-card/index.tsx [hunk 2]
```diff
@@ -36,35 +35,35 @@ import { getAtomicHostingSshAccess } from 'calypso/state/selectors/get-atomic-ho
...
+	isSshAccessEnabled: boolean;
+	isLoadingSftpData: boolean;
+	createSftpUser: ( siteId: number | null, currentUserId: number | null ) => void;
+	requestSftpUsers: ( siteId: number | null ) => void;
+	resetSftpPassword: ( siteId: number | null, sshUsername: string | null ) => void;
+	requestSshAccess: ( siteId: number | null ) => void;
+	enableSshAccess: ( siteId: number | null ) => void;
+	disableSshAccess: ( siteId: number | null ) => void;
+	removePasswordFromState: ( siteId: number | null, username: string | null ) => void;
+};
```
Comment (fredrikekelund) [inline client/hosting/server-settings/components/sftp-card/index.tsx]: The reason I typically avoid `connect` when converting JS files to TS is to avoid this redundancy. In other words, `useSelector` calls provide us with "free" types, whereas we have to manually respecify types when using `connect`.

I would advise we do the same in this case and employ `useSelector` and `useDispatch` instead of connect. It'll make the code more compact and future refactorings easier.

File: client/hosting/server-settings/components/sftp-card/style.scss [hunk 3]
```diff
@@ -0,0 +1,26 @@
+.sftp-card__ssh-field .sftp-card__input {
+	margin-top: 5px;
+}
```
Comment (fredrikekelund) [inline client/hosting/server-settings/components/sftp-card/style.scss]: Nit, I would move this selector closer to the other `.sftp-card__input` selector.

File: client/hosting/server-settings/components/sftp-card/index.tsx [hunk 4]
```diff
@@ -133,9 +126,19 @@ export const SftpCard = ( {
 				requestSshAccess( siteId );
 			}
 		}
-		return onDestroy();
```
Comment (fredrikekelund) [inline client/hosting/server-settings/components/sftp-card/index.tsx:136]: This does indeed look like a mistake, even if it's hard to tell for sure at first glance. Did you verify this somehow, @nightnei?

**Review by fredrikekelund — COMMENTED** [review]
This fixes the problem, and kudos for taking the extra step to refactor to TS 👍 I think we should consider dropping the use of `connect`, though (see my comment about that).

Also, could @matt-west please take a look at the margin between the `Enable SSH` toggle and the SSH snippet input and verify that it looks good from a design perspective? I believe this PR restores what we had previously, but it looks slightly cramped to me, so I just want to take the opportunity to tweak that if needed.

**Review by matt-west — COMMENTED** [review]
Thanks for the ping @fredrikekelund!

I agree, we need some more spacing between the control and snippet below. `16px` should be enough.

Screenshot 2024-10-18 at 10 48 58

File: client/hosting/server-settings/components/sftp-card/index.tsx (hunk 4 above)
Comment (nightnei) [reply client/hosting/server-settings/components/sftp-card/index.tsx:136]: Yes, as a result - we didn't clean it up during unmounting and it was possible to notice it for a short period of time when we did the second mounting (go back and forth between pages). Why for the short period of time - since we retrieve the list of users every time during mounting, so it wasn't a big issue. But for safety reasons - it's better to clean it up as soon as possible (it was what the author intended to do, but called onDestroy by mistake, and called it with wrong arguments - userId instead of username).

File: client/hosting/server-settings/components/sftp-card/index.tsx [hunk 5]
```diff
@@ -39,53 +39,96 @@ import { getSelectedSiteId, getSelectedSiteSlug } from 'calypso/state/ui/selecto
...
+				password = users[ 0 ].password;
+			} else {
+				// No SFTP user created yet.
+				username = null;
+				password = null;
+			}
+		}
+
+		return { username, password };
+	} );
```
Comment (fredrikekelund) [inline client/hosting/server-settings/components/sftp-card/index.tsx:130]: I copied the old logic exactly because this component relies on a difference between `null` and `undefined` values here (something I learned while fixing the tests). 

Definitely not an ideal solution to begin with, but the scope of this PR is already pretty large, so if we want to fix that, we should do it in another PR (I don't think it warrants fixing right now btw)

**Review by fredrikekelund — APPROVED** [review]
Dropping `connect` broke the tests, so I had to make some tweaks to get them working again. LGTM now, though 👍
