### PR TITLE
SPT: Modal close button enhancements

### LINKED ISSUE #6397: Jetpack connect: Jetpack version dettection failing in some cases
From @ryelle : 
I just found an issue with connect's detection of whether I have Jetpack installed. I have a nginx server with default permalinks (that is, no rewrites, just ?p=2 etc). trying to fetch the jetpack readme ​_doesn't_​ return an error code, so `getJetpackVersion` falls through to `true` – and i get an " You must update Jetpack before connecting" error which is incorrect.

If I switch on pretty permalinks, WP knows that `/wp-content/plugins/jetpack/readme.txt` doesn't exist, and correctly detects that I have no jetpack.

### PR DESCRIPTION
**Pull request by retrofox**
#### Changes proposed in this Pull Request

This PR changes the icon of the close button and fixes some styles.

#### Testing instructions

Apply these changes
1) Start to create a new page
2) Close the modal

Fixes #6397

### CODE REVIEW

**Comment by getdave** [comment]
Testing this now

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js [hunk 1]
```diff
@@ -131,8 +132,15 @@ class PageTemplateModal extends Component {
 		if ( event.target.matches( 'button.template-selector-item__label' ) ) {
 			return false;
 		}
-		this.setState( { isOpen: false } );
+
+		this.setState( { wasClosed: true } );
 		trackDismiss( this.props.segment.id, this.props.vertical.id );
+
+		if ( window && window.history && window.history.length ) {
+			window.history.back();
```
Comment (getdave) [inline apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: Just wondering if `constructor` is where we should be handling such things? I wonder whether the life cycle methods would be more appropriate?

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js [hunk 2]
```diff
@@ -198,7 +207,7 @@ class PageTemplateModal extends Component {
 					<Button
 						isPrimary
 						isLarge
-						disabled={ isEmpty( previewedTemplate ) || isLoading }
+						disabled={ isEmpty( previewedTemplate ) || isLoading || wasClosed }
```
Comment (getdave) [inline apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: I still don't understand why this button is disabled if we've previously closed the model. Surely it won't be visible. I'm probably missing something...

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/styles/starter-page-templates-editor.scss [hunk 3]
```diff
@@ -69,7 +69,26 @@ body.admin-bar:not( .is-fullscreen-mode ) .page-template-modal-screen-overlay {
 
 // Close button
 .page-template-modal .components-modal__header .components-button {
-	left: 0;
+	left: -24px; // Make up for 24px modal padding.
```
Comment (getdave) [inline apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/styles/starter-page-templates-editor.scss]: I think this value needs to be made into a sass variable. It's littered around the CSS (my fault!) and needs encapsulating.

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/styles/starter-page-templates-editor.scss [hunk 4]
```diff
@@ -69,7 +69,26 @@ body.admin-bar:not( .is-fullscreen-mode ) .page-template-modal-screen-overlay {
...
+	margin: 9px 10px;
```
Comment (getdave) [inline apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/styles/starter-page-templates-editor.scss]: Are these numbers related to anything or purely arbitrary for this single use case?

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/styles/starter-page-templates-editor.scss [hunk 5]
```diff
@@ -69,7 +69,26 @@ body.admin-bar:not( .is-fullscreen-mode ) .page-template-modal-screen-overlay {
...
+	.dashicon {
+		width: 28px;
+		height: 28px;
+	}
+}
+
+.page-template-modal .components-modal__header {
+	position: relative;
+
+	&::after {
```
Comment (getdave) [inline apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/styles/starter-page-templates-editor.scss]: It would be great to add a comment here detailing what this is doing. It will help the next developer who comes to this code.

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/styles/starter-page-templates-editor.scss [hunk 6]
```diff
@@ -69,7 +69,26 @@ body.admin-bar:not( .is-fullscreen-mode ) .page-template-modal-screen-overlay {
...
+		position: absolute;
+		content: ' ';
+		border-right: 1px solid #e2e4e7;
```
Comment (getdave) [inline apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/styles/starter-page-templates-editor.scss]: Should `#e2e4e7` be a variable? Is it used elsewhere?

**Comment by obenland** [comment]
> I was taken back to the main Dashboard at wp-admin. As a user this was not what I was expecting. I expected to see an empty canvas.

The intent of the change is to link back to the posts list. @retrofox we might need to be more explicit than `history.back()` in order to achieve that

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js (hunk 1 above)
Comment (retrofox) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: I'm not sure if I understand the comment, here. The idea is just to get back to the previous page when the user clicks on the `X` button. Thinking in the wp-admin, where usually the user can start to add a new through of the `Add Page` submenu:

image

So if the current page is the users, for instance as above, when the user clicks on the `X` button, it should show the users page again.

Comment (obenland) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: @apeatling @shaunandrews What are your thoughts here?

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js (hunk 2 above)
Comment (retrofox) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: When I was testing, getting back to the previous took a kinda long time, allowing me to add a template in the editor even after closing the modal. A few seconds after adding the template into the editor, the browser finally went to the previous page.
Although I couldn't reproduce it again (no gif :-() I think it's possible so I suggest disable the button in order to avoid this situation.

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js (hunk 1 above)
Comment (retrofox) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: Reading again the issue I see now that the idea is/was get the page lists. By mistake, I understood a different behavior, which maybe is a feature? Sorry about this confusion.

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js (hunk 2 above)
Comment (getdave) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: Ah I see. Thanks. That's an interesting edge case.

**Comment by getdave** [comment]
> The intent of the change is to link back to the posts list. @retrofox we might need to be more explicit than history.back() in order to achieve that

Are we absolutely 100% on what we're trying to achieve here? 

What happens under different conditions and in different scenarios? If we have the "spec" (even a couple of rough user stories) we can code it correctly first time.

I'm going to say again, that in IMHO the close button should _**not**_ appear as a close `X` if the action is actually "go back". 

It sounds like we're changing "Close" to actually mean "go back" so we need to ensure this is absolutely clear and perceivable. There should be no ambiguity and the button should perform the same function under all scenarios.

I would suggest we bite the bullet and make this a true "back" button rather than a "dismiss" button. 

This requires a "back" arrow like the one we currently have on Dotcom. 

Be aware, however, that this means the only way to create a "Blank" page is then selecting the "Blank" option in the template selector. We the recent changes to reduce the size of the "Blank" option on mobile, we need to be confident this is still a clear UX.

File: apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js (hunk 1 above)
Comment (getdave) [reply apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js]: This comment was specifically about using the `constructor` for side effects.

Note this from [the React docs](https://reactjs.org/docs/react-component.html#constructor):

> Avoid introducing any side-effects or subscriptions in the constructor. For those use cases, use componentDidMount() instead.

I'm flagging `window.history.back()` as a side effect that would be better handled in a lifecycle method.
