### PR TITLE
New Onboarding: Fix broken back button when landing from external pages.

### LINKED ISSUE #49360: New Onboarding: navigation doesn't work when landing from an external page
### Steps to reproduce the behavior

1. Go to wordpress.com/new/design
2. Click on Domain Nudge in the header. Domain selection modal will open
3. Click on _Use a domain I own_ button. You will be redirected to an external flow
4. Go back to the Domain selection modal
5. Try closing the modal

#### What I expected to happen
I should land on the previous step in the onboarding (Design selection in this case)

#### What actually happened
I landed on the external page

### Context
Using back/skip buttons to use the browser history doesn't work when the user lands from an external page. 
Hint: explore the possibility of persisting the previous step in local state and use that instead of browser history to go back from a modal.

#### Video
https://cloudup.com/c-NUFnLRdb8

### PR DESCRIPTION
**Pull request by yansern**
## Changes proposed in this Pull Request

The "Go Back" button breaks when landing through the url to the following path:
- /new/language-modal
- /new/plans-modal
- /new/domains-modal

This PR fixes this by storing the last route location in the data store `lastLocation` when route changes in when user go through the onboarding flow.

## Testing instructions

**Pro Tip:** You can add the following line to the dev tools live expression watcher to see what values it holds:

```
JSON.parse(localStorage.getItem('WP_ONBOARD'))['automattic/onboard'].lastLocation
```

### Test 1: Pressing **Go Back** should go back to fallback step `/` name step when fresh.

* Enter `/new?fresh`.
* **Open a new tab** and go to any of these 3 urls:
    - [x] `/new/language-modal`
    - [x] `/new/plans-modal`
    - [x] `/new/domains-modal`
* Click on **Go Back** button.
* It should go to the `/` name step.

### Test 2: Pressing **Go Back** should go back to previous step where user left off.

* Enter `/new` and feel free to stop at any step (domain step, design step, feature picker step, plan step, etc.).
* Open up any of the following modal by clicking on their respective header buttons.
   * [x] Domain modal _(through the domain button on the top left)_.
   * [x] Plans modal _(through the plans button on the top right)_.
   * [x] Language modal _(through the language button on the top right)_. 
* **Open a new tab** and go to any of these 3 urls:
    - [x] `/new/language-modal`
    - [x] `/new/plans-modal`
    - [x] `/new/domains-modal`
* Click on **Go Back** button.
* It should go to the previous step where the user left off.

Fixes #49360

### CODE REVIEW

File: client/landing/gutenboarding/hooks/use-last-location.ts [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+	const history = useHistory();
+
+	const lastLocation = useSelect( ( select ) => select( ONBOARD_STORE ).getLastLocation() );
+
+	const goLastLocation = ( fallbackLocation = '/' ) => {
+		history.push( lastLocation || fallbackLocation );
+	};
+
+	return {
+		goLastLocation: goLastLocation,
```
Comment (alshakero) [inline client/landing/gutenboarding/hooks/use-last-location.ts]:
```suggestion
		goLastLocation,
```

File: client/landing/gutenboarding/onboarding-block/edit.tsx [hunk 2]
```diff
@@ -116,6 +117,28 @@ const OnboardingEdit: React.FunctionComponent< BlockEditProps< Attributes > > =
...
+			! [
+				Step.DomainsModal as string,
+				Step.PlansModal as string,
+				Step.LanguageModal as string,
+			].includes( step )
+		) {
+			// Remember last location
+			setLastLocation( location.pathname );
+		}
+	}, [ location, step, setLastLocation ] );
```
Comment (alshakero) [inline client/landing/gutenboarding/onboarding-block/edit.tsx]: I would do this for readability and to avoid casting.

```suggestion
	React.useEffect( () => {
		const modalSteps: StepType[] = [ Step.DomainsModal, Step.PlansModal, Step.LanguageModal ];
		if (
			// When location.key is undefined, this means user has just entered gutenboarding from url.
			location.key !== undefined &&
			// When step exists, and step is not any from the modals
			step &&
			! modalSteps.includes( step )
		) {
			// Remember last location
			setLastLocation( location.pathname );
		}
	}, [ location, step, setLastLocation ] );
```

File: client/landing/gutenboarding/stores/onboard/reducer.ts [hunk 3]
```diff
@@ -226,6 +226,16 @@ const hasOnboardingStarted: Reducer< boolean, OnboardAction > = ( state = false,
 	return state;
 };
 
+const lastLocation: Reducer< string, OnboardAction > = ( state = '', action ) => {
+	if ( action.type === 'SET_LAST_LOCATION' ) {
+		return action.path;
+	}
+	if ( action.type === 'RESET_ONBOARD_STORE' ) {
+		return '';
+	}
```
Comment (alshakero) [inline client/landing/gutenboarding/stores/onboard/reducer.ts:235]: Awesome work. Can be easily overlooked.

**Review by alshakero — COMMENTED** [review]
Code review: cosmetics and types improvements. I'll test now.

**Review by alshakero — APPROVED** [review]
Finished testing and this is borderline miraculous. So freaking smooth.

File: client/landing/gutenboarding/hooks/use-last-location.ts [hunk 4]
```diff
@@ -0,0 +1,23 @@
...
+import { useHistory } from 'react-router-dom';
+/**
+ * Internal dependencies
+ */
+import { STORE_KEY as ONBOARD_STORE } from '../stores/onboard';
+
+export default function useLastLocation(): { goLastLocation: () => void } {
+	const history = useHistory();
+
+	const lastLocation = useSelect( ( select ) => select( ONBOARD_STORE ).getLastLocation() );
```
Comment (ciampo) [inline client/landing/gutenboarding/hooks/use-last-location.ts]: Should we add the second argument for `useSelect` ?

```suggestion
	const lastLocation = useSelect( ( select ) => select( ONBOARD_STORE ).getLastLocation(), [] );
```

File: client/landing/gutenboarding/onboarding-block/edit.tsx (hunk 2 above)
Comment (yansern) [reply client/landing/gutenboarding/onboarding-block/edit.tsx]: Thanks. I was scratching my head how to fix this!
