### PR TITLE
Gutenboarding: persist free domain when selecting free plan

### LINKED ISSUE #43927: Gutenboarding: subdomain selection is lost or changed
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/new?fresh
2. Enter a site title and proceed
3. Change the domain search query to generate different results and select the subdomain
4. Open Plans Modal and select Free Plan => domain selection will be automatically re-generated based on the site title
5. Repeat steps above but this time skip site title at step 2 => domain selection will be lost

#### What I expected
- free domain selection to be persisted
 
#### What happened instead
- domain selection is lost or replaced with the default one based on site title 

#### Screenshot / Video
https://cloudup.com/cBMWYVIJkEz

### PR DESCRIPTION
**Pull request by razvanpapadopol**
#### Changes proposed in this Pull Request
* Update condition to trigger automatic domain update when selecting Free plan.
* Add `plan` to `ONBOARD` store and remove `selectedPlanSlug` from `@data-stores/plans`.

#### Testing instructions
* go to [/new](https://wordpress.com/new?fresh) in production and try to reproduce #43927
* go to [/new](https://calypso.live/new?branch=fix/gutenboarding-persist-free-domain) and the free domain should be persisted
* the rest of domain and plan selection functionality and analytics events should remain the same.

Fixes #43927

### CODE REVIEW

File: packages/data-stores/src/plans/selectors.ts [hunk 1]
```diff
@@ -10,11 +10,9 @@ function getPlan( slug: PlanSlug ) {
 	return PLANS_LIST[ slug ];
 }
 
-export const getSelectedPlan = ( state: State ) =>
-	state.selectedPlanSlug ? getPlan( state.selectedPlanSlug ) : null;
+export const getPlanBySlug = ( _: State, slug: PlanSlug ) => getPlan( slug );
 
-export const getDefaultPlan = ( _: State, hasPaidDomain: boolean, hasPaidDesign: boolean ) =>
```
Comment (razvanpapadopol) [inline packages/data-stores/src/plans/selectors.ts:16]: `plans` store shouldn't care about external state such as `hasPaidDomain` or `hasPaidDesign`.

File: packages/data-stores/src/plans/reducer.ts [hunk 2]
```diff
@@ -30,11 +28,6 @@ const DEFAUlT_STATE: {
 
 const reducer = function ( state = DEFAUlT_STATE, action: PlanAction ) {
 	switch ( action.type ) {
-		case 'SET_PLAN':
-			return {
-				...state,
-				selectedPlanSlug: action.slug,
-			};
```
Comment (razvanpapadopol) [inline packages/data-stores/src/plans/reducer.ts:37]: With this state moved to consumer app's store (`Onboard` at the moment) it will be easier to understand the scope of `plans` / `domain-suggestions` data-stores. Their purpose is to store data fetched from the API and error/loading related states. Keeping track of application state (plan, domain, last search query, etc) should be the responsibility of each consumer app.
Some context about this: https://github.com/Automattic/wp-calypso/pull/43858/files#r449029095

Comment (yansern) [reply packages/data-stores/src/plans/reducer.ts:37]: > Keeping track of application state (plan, domain, last search query, etc) should be the responsibility of each consumer app.

Agree! This makes it clear who does what now.

File: packages/data-stores/src/plans/selectors.ts (hunk 1 above)
Comment (yansern) [reply packages/data-stores/src/plans/selectors.ts:16]: Thanks. I can see that now `useSelectedPlan()`, a hook in the consumer app, now determines what plan to return.  If a free plan is selected, but a paid domain or paid design is selected , it will change to a paid plan. Is there a place where `updatePlan()` is called when this is changed?

Comment (razvanpapadopol) [reply packages/data-stores/src/plans/selectors.ts:16]: > If a free plan is selected, but a paid domain or paid design is selected

At the moment, only if a paid domain is selected because we still don't have the UI ready to connect the concepts of paid plan <=> premium design. Check this convo: https://github.com/Automattic/wp-calypso/issues/42601#issuecomment-644742819

> Is there a place where setPlan()/updatePlan() is called when this is changed or is this not necessary?

We're not updating the selected plan in these cases in Gutenboarding because we always want to show Plans grid. See in code: https://github.com/Automattic/wp-calypso/pull/43935/files#diff-7ccae80646b579bcdfe01b44b7601d43R57-R59
