### PR TITLE
Nav Unification: fix detached sidebar blocker issue

### LINKED ISSUE #49175: Sidebar scroll/fixed state seems to have a variety of bugginess and jumpiness depending on screen size
See p7DVsv-ago-p2#comment-33833.

Essentially  depending on screen size, length of the content in the sidebar, and if you resize the browser in various scroll positions the sidebar scroll seems to be buggy.

We also see a spike in CPU usage which needs to be addressed.

Screen Shot 2021-01-22 at 09 57 56

### Steps to reproduce the behavior

To reproduce, browser size needs to be slightly larger than the navigation content:

screenshot-2021-01-22-at-11 37 21

Then if it’s not happening yet, resize the browser window’s height just lightly and try scrolling again. Sidebar should now scroll in a “broken state”.

### PR DESCRIPTION
**Pull request by frontdevde**
### Changes proposed in this Pull Request

This PR aims to fix a blocker issue where the sidebar could get into a detached state after resizing the viewport.

The identified cause for the issue is that when the viewport is shorter than the sidebar, we add some inline styles to position the sidebar accordingly. When we resize the viewport to then be taller than the sidebar, we didn't remove the inline styles previously set. This PR aims to rectify that.

Fixes https://github.com/Automattic/wp-calypso/issues/49175

### Testing instructions

|Before|After|
|-|-|
|Screenshot 2021-02-11 at 17 31 59|Screenshot 2021-02-11 at 17 32 48|

**First it's important to reproduce the issue in production so you can be sure the changes proposed here fix the issue. The most reliable way to reproduce the issue I've found is the following:**

* Load /home page with enough space for the entire sidebar to fit the screen
* Resize the window to make the height smaller than the sidebar
* Scroll down the page to the end and all the way up again
* Resize the window to make the height taller than the sidebar
* Scrolling the page now leaves the sidebar in a detached state

**After reproducing the issue in production, test with the calypso.live link for this PR. The issue shouldn't be present anymore. In addition the sidebar should still behave as expected across viewport heights.**

### CODE REVIEW

File: client/layout/utils.ts [hunk 1]
```diff
@@ -49,10 +49,14 @@ export const handleScroll = ( event: React.UIEvent< HTMLElement > ): void => {
 
 		if (
 			windowHeight >= secondaryElHeight + masterbarHeight &&
-			content.style.minHeight !== 'initial'
+			secondaryEl !== undefined &&
```
Comment (tjcafferkey) [inline client/layout/utils.ts]: Do you think `secondaryEl instanceof HTMLElement` would be a more reliable and readable check here? (It would reduce a line of code too)

File: client/layout/utils.ts [hunk 2]
```diff
@@ -49,10 +49,14 @@ export const handleScroll = ( event: React.UIEvent< HTMLElement > ): void => {
...
+			secondaryEl !== null &&
+			( content.style.minHeight !== 'initial' || secondaryEl.style.position )
```
Comment (tjcafferkey) [inline client/layout/utils.ts:54]: We seem to be doing more thorough checks on `secondaryEl` than we are on `content` when they are being operated on in similar ways

Do you think we should apply the same check as the above comment (`content instanceof HTMLElement`) to `content`?

**Comment by tjcafferkey** [comment]
This PR works as expected. I have just left some inline comments that I think would be a nice addition unless you see any problems with it.

File: client/layout/utils.ts [hunk 3]
```diff
@@ -49,10 +49,14 @@ export const handleScroll = ( event: React.UIEvent< HTMLElement > ): void => {
 
 		if (
 			windowHeight >= secondaryElHeight + masterbarHeight &&
-			content.style.minHeight !== 'initial'
+			secondaryEl !== undefined &&
+			secondaryEl !== null &&
```
Comment (mmtr) [inline client/layout/utils.ts]: According to the MDN Web Docs, if the element is not found, `getElementById` returns `null` so I think we can simply check that. It could be a good idea to check `content` to, as Tom suggested.

https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById#return_value
```suggestion
			content !== null &&
			secondaryEl !== null &&
```

File: client/layout/utils.ts (hunk 1 above)
Comment (mmtr) [reply client/layout/utils.ts]: According to the MDN Web Docs, if the element is not found, `getElementById` returns `null` so I think we can simply check that. It could be a good idea to check `content` to, as you suggested above.

https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById#return_value
```suggestion
			content !== null &&
```

**Review by mmtr — APPROVED** [review]
Nice investigation here trying to reproduce the issue and finding out the root cause! It works like a charm.

File: client/layout/utils.ts (hunk 2 above)
Comment (mmtr) [reply client/layout/utils.ts:54]: Fixed in 556bd9b72e9bd7282114cf19422d2f6a47100883

**Comment by getdave** [comment]
I still can't reproduce this so I'm glad someone could 😄  Nice work @frontdevde!

**Comment by frontdevde** [comment]
Failed e2e tests unrelated and failed on all recently merged PRs as well.
