### PR TITLE
Checkout: Add price tier and renewal frequency to Jetpack Search products

### LINKED ISSUE #46934: Checkout: Display tier of plan in the cart for Search
#### Steps to reproduce

1. Starting at URL: https://jetpack.com/upgrade/search/
2. Click on either the main CTA (https://wordpress.com/purchase-product/jetpack_search/monthly) or the annual link (https://wordpress.com/purchase-product/jetpack_search) 
3. Select a site to add the upgrade to (can be a Jetpack site or a WP.com site)
4. You end up at the cart

#### What I expected

I should see the tier of the subscription (e.g. up to 1000 records) and see whether it is monthly or annual.

~~I should also be able to switch between monthly and annual.~~ (Tracked separately)

#### What happened instead

I just see "Jetpack Search" with a price and no context.

#### Screenshot / Video

screen-shot-on-2020-10-29-at-15-15-41

95409762-df312000-097e-11eb-94e3-fdda67303be0

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

This adds a sub-label to Jetpack Search products in checkout so that they display their current tier maximum and their renewal frequency.

Before:

before-jetpack-search-without

After:

jetpack-search-item-with-sublabel

Here's how it compares to a plan product's sub-label:

Screen Shot 2021-04-26 at 7 51 43 PM

Fixes https://github.com/Automattic/wp-calypso/issues/46934

#### Testing instructions

- Add Jetpack search to your cart. You can do this on a Jetpack site by visiting `/plans` for that site and clicking the button under the "Search" product.
- Visit checkout and verify that the product sub-label includes information on the maximum number of units in the current tier and a "Renews ..." line explaining how often the product renews.

### CODE REVIEW

File: client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx [hunk 1]
```diff
@@ -554,6 +559,51 @@ function canItemBeDeleted( item: ResponseCartProduct ): boolean {
...
+			);
+		}
+	}
+	return null;
+}
+
+function RenewalFrequency( { product }: { product: ResponseCartProduct } ): JSX.Element | null {
+	const translate = useTranslate();
+	if ( isMonthlyProduct( product ) ) {
+		return <LineItemMeta>{ translate( 'Renews monthly' ) }</LineItemMeta>;
```
Comment (a8ci18n) [inline client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx:602]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **23** times:
`translate( 'renews monthly', { context: 'Informative text for renewals in /checkout'} )` *ES Score: 14*

File: client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx [hunk 2]
```diff
@@ -554,6 +559,51 @@ function canItemBeDeleted( item: ResponseCartProduct ): boolean {
...
+	}
+
+	if ( isYearly( product ) ) {
+		return <LineItemMeta>{ translate( 'Renews annually' ) }</LineItemMeta>;
```
Comment (a8ci18n) [inline client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx:606]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **29** times:
`translate( 'renews annually', { context: 'Informative text for renewals in /checkout'} )` *ES Score: 15*

File: client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx [hunk 3]
```diff
@@ -554,6 +559,51 @@ function canItemBeDeleted( item: ResponseCartProduct ): boolean {
...
+	}
+
+	if ( isBiennially( product ) ) {
+		return <LineItemMeta>{ translate( 'Renews every two years' ) }</LineItemMeta>;
```
Comment (a8ci18n) [inline client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx:610]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **23** times:
`translate( 'renews every two years', { context: 'Informative text for renewals in /checkout'} )` *ES Score: 14*

**Comment by michaeldcain** [comment]
I see both a "Billed Monthly" and "Renews Monthly" - which seem a little redundant:

Screen Shot 2021-04-27 at 11 03 33 AM

**Comment by sirbrillig** [comment]
> I see both a "Billed Monthly" and "Renews Monthly" - which seem a little redundant:

😬  That's not right. Let me take another look at where that "Billed monthly" text comes from and see why it wasn't present in the items I added.

File: client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx [hunk 4]
```diff
@@ -554,6 +559,51 @@ function canItemBeDeleted( item: ResponseCartProduct ): boolean {
...
+		getProductPriceTierList( state, product.product_slug )
+	);
+
+	if ( isJetpackSearch( product ) && product.current_quantity ) {
+		const tierMaximum = getPriceTierForUnits( priceTierList, product.current_quantity )
+			?.maximum_units;
+		if ( tierMaximum ) {
+			return (
+				<LineItemMeta>
+					{ translate( 'Up to %(tierMaximum)s records', { args: { tierMaximum } } ) }
```
Comment (DavidRothstein) [inline client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx:584]: This won't display anything for the "more than 1,000,000 records" tier?  You could add something to handle that if you want, or not worry about it much because the number of sites that run into that is presumably small.

Comment (sirbrillig) [reply client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx:584]: Oh, good point.

**Comment by sirbrillig** [comment]
Ok, the reason for the duplicate "Billed monthly" is because monthly products (of any kind) already have a sublabel of "Billed monthly", but annual or biannual products have no such label. I've removed the duplicate label in this PR but that means that annual and biannual Jetpack Search will not display a renewal frequency. I think that's a separate issue: should we display renewal frequency for all our products, even for yearly and 2-year renewals? If I add it now, we'll end up with more duplication because _some_ products (domain reg., domain map, G Suite, and plans) already have a separate inline text (separated from the other meta by a colon) that display renewal frequency.

**Comment by sirbrillig** [comment]
There, I think I fixed it for Jetpack Search without messing with anything else, but we should eventually do an audit of all these different sublabels and their variations.

Screen Shot 2021-04-27 at 6 33 11 PM

**Review by michaeldcain — APPROVED** [review]
This works as described and LGTM.

> but we should eventually do an audit of all these different sublabels and their variations.

Absolutely. I'm kind of blown away by the amount of variation in sublabels that has appeared in such a short amount of time. :|

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5826032

Thank you @sirbrillig for including a screenshot in the description! This is really helpful for our translators.

File: client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx (hunk 3 above)
Comment (sirbrillig) [reply client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx:610]: These are the same except that the casing is different. I believe it's worthwhile in English to capitalize this sentence.

File: client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx (hunk 2 above)
Comment (sirbrillig) [reply client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx:606]: These are the same except that the casing is different. I believe it's worthwhile in English to capitalize this sentence.

File: client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx (hunk 1 above)
Comment (sirbrillig) [reply client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.tsx:602]: These are the same except that the casing is different. I believe it's worthwhile in English to capitalize this sentence.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5826032).
