### PR TITLE
Plans: Redirect non-Jetpack monthly view to yearly

### LINKED ISSUE #17515: Plans: Non-Jetpack sites should not be able to access monthly view
#### Steps to reproduce - scenario A
1. Go to https://wordpress.com/plans/`:site`, where `:site` is a Jetpack site.
2. Toggle to monthly plans view.
3. Switch to a WP.com site or an Atomic site.
4. Notice you still have `/monthly` in the URL, but you're viewing yearly plans.

#### Steps to reproduce - scenario B
1. Go to https://wordpress.com/plans/monthly/`:site`, where `:site` is a WordPress.com or Atomic site.
2. Notice page loads and you have `/monthly` in the URL, but you're viewing yearly plans.

#### What I expected
To be redirected to the yearly plans view.

#### What happened instead
I still was in the `/monthly` plans view, although I was seeing yearly plans.

#### Context / Source
Found while manually testing #17462 and #17494.

#manual-testing

### PR DESCRIPTION
**Pull request by tyxla**
This PR updates the Plans page to redirect to yearly plans when accessing monthly plans view for a non-Jetpack site.

Fixes #17515.

### To test

**Scenario A** - switching from a Jetpack site on monthly view to a .com site
1. Go to https://wordpress.com/plans/`:site`, where `:site` is a Jetpack site.
2. Toggle to monthly plans view.
3. Switch to a WP.com site.
4. Verify you no longer have `/monthly` in the URL, but instead you're in the yearly view.

**Scenario B** - switching from a Jetpack site on monthly view to an Atomic site
1. Go to https://wordpress.com/plans/`:site`, where `:site` is a Jetpack site.
2. Toggle to monthly plans view.
3. Switch to an Atomic site.
4. Verify you no longer have `/monthly` in the URL, but instead you're redirected to the yearly view.

**Scenario C** - directly accessing plans monthly view on a .com site
1. Go to https://wordpress.com/plans/monthly/`:site`, where `:site` is a WordPress.com site.
2. Verify you no longer have `/monthly` in the URL, but instead you're redirected to the yearly view.

**Scenario D** - directly accessing plans monthly view on an Atomic site
1. Go to https://wordpress.com/plans/monthly/`:site`, where `:site` is an Atomic site.
2. Verify you no longer have `/monthly` in the URL, but instead you're redirected to the yearly view.

### CODE REVIEW

File: client/my-sites/plans/main.jsx [hunk 1]
```diff
@@ -37,12 +38,30 @@ const Plans = React.createClass( {
...
 	componentDidMount() {
+		this.redirectIfNonJetpackMonthly();
+
 		// Scroll to the top
 		if ( typeof window !== 'undefined' ) {
 			window.scrollTo( 0, 0 );
 		}
 	},
 
+	componentDidUpdate() {
```
Comment (seear) [inline client/my-sites/plans/main.jsx]: Wondering if using `componentWillReceiveProps()` would be slightly better here so we can redirect before rendering?

Comment (tyxla) [reply client/my-sites/plans/main.jsx]: I don't think it would make a big difference, and I usually try to avoid having side effects in `componentWillReceiveProps`.

Comment (tyxla) [reply client/my-sites/plans/main.jsx]: I'm fine to change it if you have a hard opinion on it though.

Comment (seear) [reply client/my-sites/plans/main.jsx]: > I don't think it would make a big difference

Yes, I agree there, I don't think it matters much, so I'm fine the way it is.

> I usually try to avoid having side effects in componentWillReceiveProps

Curious about this, though. The [docs](https://facebook.github.io/react/docs/react-component.html#componentwillreceiveprops) don't mention avoiding side effects. `componentWillReceiveProps` is the earliest opportunity to take action on changed props, so why wait till later?

Comment (tyxla) [reply client/my-sites/plans/main.jsx]: Oh yeah, I totally agree it's not included in the docs, and it's probably something that should be mentioned there. Sadly I can only provide rough non-docs links for consideration, like this one for example: https://twitter.com/acdlite/status/818931319703044096?lang=en
