### PR TITLE
Media: wrap selected detail index in getter

### LINKED ISSUE #8005: Media: Multiple selection/deselection leads to console errors and unresponsive modal
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/example.wordpress.com
2. Click the Add Media button
3. Select two or more images and click Edit at the bottom left
4. Click the right arrow to proceed to the next image
5. Click the Media Library return button at the upper left
6. Deselect one of the images
7. Attempt to edit the remaining image
8. Attempt to cancel the media modal

#### What I expected
To be able to continue editing images

#### What happened instead
The edit dialog never opens again, and I'm unable to cancel.  The following errors show up in the JS console:

```js
Uncaught TypeError: Cannot read property 'transient' of undefined post-editor.025f79f….min.js:1 
Uncaught TypeError: Cannot read property 'getHostNode' of null build-wpcalypso.27ffe58….min.js:16
```
#### Browser / OS version
OSX Chrome and Firefox

#### Screenshot / Video
wp-calypso-image-editor-crash

#### Context / Source
#manual-testing

### PR DESCRIPTION
**Pull request by gwwar**
Fixes #8005 where the media modal would become unresponsive if the `detailSelectedIndex` is out of bounds in all selected items ( `mediaLibrarySelectedItems` ). This can get out of sync because `detailSelectedIndex` is component state, and any selections/deselections on media items updates the `mediaLibrarySelectedItems` list but not the `detailSelectedIndex`.

#### Steps to reproduce
1. Starting at URL: https://calypso.localhost:300/post
2. Select a site
3. Click the Add Media button
4. Select two or more images and click Edit at the bottom left
5. Click the right arrow to proceed to the next image
6. Click the Media Library return button at the upper left
7. Deselect one of the images
8. Attempt to edit the remaining image
9. Attempt to cancel the media modal

cc @hoverduck @aduth @lamosty @artpi @retrofox

### CODE REVIEW

**Comment by lamosty** [comment]
Nice fix @gwwar!

The bug seems to be fixed and code looks fine.

LGTM :shipit:.

File: client/lib/media/utils.js [hunk 1]
```diff
@@ -38,6 +38,11 @@ const MediaUtils = {
 	 * @return {string}         URL to the media
 	 */
 	url: function( media, options ) {
+
```
Comment (aduth) [inline client/lib/media/utils.js]:
```
wp-calypso (fix/media-selection) $ ./node_modules/.bin/eslint --quiet --rule 'padded-blocks: 2' client/lib/media/utils.js 

/Users/andrew/Documents/Code/wp-calypso/client/lib/media/utils.js
  40:34  error  Block must not be padded by blank lines  padded-blocks

✖ 1 problem (1 error, 0 warnings)
```

**Comment by hoverduck** [comment]
Tested, looks good to me!

File: client/lib/media/utils.js (hunk 1 above)
Comment (gwwar) [inline client/lib/media/utils.js]: Nice 👀

**Comment by gwwar** [comment]
> Had you considered alternatively comparing the length in componentWillReceiveProps and updating state if it's no longer valid?

I'm thinking that in another PR we could move `detailSelectedIndex` from being component state. It really seems like the select/deselect actions should modify not only `mediaLibrarySelectedItems` but `detailSelectedIndex` too.

File: client/lib/media/utils.js (hunk 1 above)
Comment (gwwar) [inline client/lib/media/utils.js]: updated in f0ab160

**Comment by gwwar** [comment]
Thanks for the reviews!
