### PR TITLE
Google Apps: postcode unresponsive during signup

### LINKED ISSUE #25547: Domains checkout: Unable to add postal code to G Suite checkout form, in order to add new user
Reported in 4401200-hc (follow-up in 1226465-zen). There is at least one other instance in 1224009-zen.

#### Steps to reproduce
1. Starting at `My Sites` > `Domains` > `USER_DOMAIN` > `Email`
2. Click on `Add G Suite` button
3. Complete form by adding first and last names, selecting country from dropdown
4. Clicked in the `Postal Code` field to type in a postal code

#### What I expected

I expected to be able to type a postal code into the `Postal Code` field.

#### What happened instead

Instead, I was unable to type a postal code into the field. The field seems to capture one character that's typed, but not the whole postal code.

It doesn't seem to make a difference which country is selected first.

#### Browser / OS version

User was using Chrome 66.0.3359.181, on Windows 10.0.

I'm using Chrome 67, on macOS 10.13.5

#### Workaround 

There's a workaround to this issue that another HE discovered:

1. Go to `My Sites` > `Domains` > `USER_DOMAIN` > `Email` and click on `Add G Suite` button. If you still have the item in your cart, you can click on the cart icon in `Domains`, and click on the Checkout button to re-open the pending item.
2. Choose the email address you want and hit `Continue`
3. Fill in `First Name`, `Last Name` and choose `Country`
4. Since we can’t type anything in `Postal Code` section now, we can copy a postal code in a note app (or to your clipboard) in advance.
5. Paste it to `Postal Code` section.
6. Reload the page. Then the postal code we pasted shows up.
7. Click on `Continue` to Checkout
8. Proceed with normal checkout process

For some reason, pasting the postal code into the `Postal Code` field, then reloading the page, seems to render the form with the postal code, and other details already entered.

### PR DESCRIPTION
**Pull request by ramonjd**
This PR fixes #25547

I wish I could outline the cause properly, but I cannot. Suffice to say that wading through `formState` and the continual prop updates is about as much fun as playing chess against deep blue while tied to a flaming pole.

And given that `componentWillMount` is deprecated, we're going to have to deal with at least four `formState` controller instantiations that take place in this lifecycle method. But I digress...

Result:

https://cldup.com/_0BpqDLQxq.mp4

cc @deBhal who I kindly request to merge during my AFK 🙇 

## Testing

1. Fire up the branch
2. Starting at `My Sites` > `Domains` > `USER_DOMAIN` > `Email`
3. Click on `Add G Suite` button
4. Complete form by adding first and last names, selecting country from dropdown
5. Clicked in the `Postal Code` field to type in a postal code
6. Switch countries and repeat 5
7. Continue onto payments

### Expectations

You can add/edit your postcode. Postcode formats that are no valid for the country you selected should trigger and error.

You should be able to continue onto payments.

### CODE REVIEW

File: client/components/domains/contact-details-form-fields/index.jsx [hunk 1]
```diff
@@ -413,6 +412,24 @@ export class ContactDetailsFormFields extends Component {
 		);
 	}
 
+	renderGAppFieldset() {
```
Comment (klimeryk) [inline client/components/domains/contact-details-form-fields/index.jsx]: Small nitpick: could you rename it to plural? `renderGAppsFieldset`?
