### PR TITLE
Reader: Fix how CommentButton cancels events, update Reader to use it

### LINKED ISSUE #535: Reader: Comment button doesn't work on Android
If you view the Reader list on Android, tapping on the comment button does turn it to the blue highlight color but nothing happens after that.

Samsung Galaxy S6, Android 5.1 and Chrome browser.

### PR DESCRIPTION
**Pull request by blowery**
The CommentButton `comment-button` component was only using onTapTouch to handle events. This meant that the prevent didn't actually work, unless you were on a system with touch events, when it did. This patch changes it to be consistent and always prevent the click.

It also updates the Reader to handle clicks on the comment button, as we can no longer rely on it falling through. This also cleans up the click handler a bit which is a bonus.

Fixes #535

### CODE REVIEW

**Comment by blowery** [comment]
cc @roundhill as the reporter

File: client/reader/following-stream/post.jsx [hunk 1]
```diff
@@ -223,11 +223,18 @@ var Post = React.createClass( {
 		classes( headerNode ).toggle( 'is-long', this.shouldApplyIsLong() );
 	},
 
+	propogateCardClick: function( options = {} ) {
```
Comment (bluefuton) [inline client/reader/following-stream/post.jsx]: propogate -> propagate :)

Comment (blowery) [inline client/reader/following-stream/post.jsx]: it's the american spelling. :tada: (kidding)

**Comment by bluefuton** [comment]
No having a lot of luck with my Android environment (on public wifi today, which doesn't help).

cc @gwwar - would you mind having a quick test of this one for us please? :)

**Comment by gwwar** [comment]
:ship: Tested in android emulator.
