### PR TITLE
E2E: Update spec `wp-domains__add` to match new experience introduced in #56949.

### LINKED ISSUE #57239: Broken E2E: Domains: Add
### Spec file

wp-domains__add.ts

### Suite or step

Manage Domain

### Framework

Playwright

### Logs

Screen changed due to #56949.

Logs:
```
page.click: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "button:text("Manage domain")"
============================================================
at Object.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-domains__add.ts:91:14)
at Promise.then.completed (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:390:28)
at callAsyncCircusFn (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:315:10)
at _callCircusTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:218:40)
at runNextTicks (node:internal/process/task_queues:61:5)
at processImmediate (node:internal/timers:437:9)
at _runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:155:3)
at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:66:9)
at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
at run (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:25:3)
at runAndTransformResultsToJestFormat (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:167:21)
at jestAdapter (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:82:19)
at runTestInternal (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:389:16)
at runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:475:34)
at Object.worker (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/testWorker.js:133:12)
```

Run: https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Pre_Release/6870981

Trace: https://teamcity.a8c.com/repository/download/calypso_Calypso_E2E_Pre_Release/6870981:id/trace/cancel-domain-2021-10-21T16-38-34.zip

### PR DESCRIPTION
**Pull request by worldomonation**
#### Changes proposed in this Pull Request

This PR updates the flow of the `Domains: Add` spec to match the new screen.

Key changes:
- add second level `describe` blocks to group test steps.
- update test steps to navigate to home dashboard from the purchase thank you screen.
- implement new method to click on purchased domain by name.

cancel-domain-2021-10-21T17-43-43

#### Testing instructions

- [x] pre-release
- [ ] desktop
- [ ] mobile

Fixes  #57239

### CODE REVIEW

File: packages/calypso-e2e/src/lib/pages/domains-page.ts [hunk 1]
```diff
@@ -36,6 +42,15 @@ export class DomainsPage {
 		] );
 	}
 
+	/**
+	 * Click initial button to use a domain already owned by the user (make connection or transfer)
+	 */
+	async useADomainIOwn(): Promise< void > {
+		await this.page.click( selectors.useADomainIOwnButton );
+	}
```
Comment (worldomonation) [inline packages/calypso-e2e/src/lib/pages/domains-page.ts:50]: Just shuffling around the methods.

**Comment by worldomonation** [comment]
Pre-release tests passed, which is the important part.

**Review by dpasque — APPROVED** [review]
🚀
