### PR TITLE
Reader: fix scrolling problems in streams

### LINKED ISSUE #37901: Reader: scrolling problems in Reader (Firefox)
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/tag/photography (I think it happens on any page, but this tag makes it easier to see)
2. Scroll, keep scrolling
3. Observe the scroll marker on the right of the browser
4. Observe images

#### What I expected
To see smooth-ish scrolling on the right.
To see each post once.

#### What happened instead
The scroll marker jumps rather eratically.

Posts appear to be duplicated, but I'm pretty sure it is just that the page is jumping back to a previous point.

Observe in the video below that when I click a link, and then see the same image again, the link is still outlined, which is why I think it is page jumping, not posts actually being duplicated.

#### Browser / OS version
Firefox 70.0.1
Mac OS X Mojave
Windows 10
Maybe Edge also?

#### Screenshot / Video
https://cld.wthms.co/tn6FmL

#### Context / Source
#user-report
2505176-zen

### PR DESCRIPTION
**Pull request by jsnajdr**
Fixes #37901.

Was caused by me removing a ref on `PostLifecycle` component in #37553. Here's a quote of the very unwise comment I made there:

> **Unneeded refs in Reader Stream:**
`PostLifecycle` is a connect-ed component without `forwardRef`, and yet we're passing a ref to it. It's never used though, so I simply removed it.

I didn't realize then that the ref is used internally by `InfiniteList`, and is used to measure the list item pixel dimensions. If the refs are not set, items are assumed to have a "guessed" height of 600px. Which is almost never true and leads to buggy scrolling experience.

See the commit message in https://github.com/Automattic/wp-calypso/commit/df0faf80276035c241fe521146a0a09da580d7fb for more technical details and suggestions to improve that part of `InfiniteList` API.

The https://github.com/Automattic/wp-calypso/commit/df0faf80276035c241fe521146a0a09da580d7fb commit is the one that fixes the bug -- add back the `PostLifecycle` ref and add `forwardRef` flag to `PostLifecycle`'s `connect` wrapper so that it forwards the ref to the wrapped component.

The remaining commits are janitorial drive-by fixes:
- fix lint errors by converting references to `history` to `window.history`
- use `React.createRef` to manage a ref to the `InfiniteList`
- modernize and simplify the `forEachInRow` method in `InfiniteList`

Each change is a small isolated commit and shouldn't be difficult to review and test.

@kristarella @pento can you check (on calypso.live) that this patch indeed fixes the weird scroll behavior? The bug shouldn't be browser-specific at all, although the bug report mentions Firefox and others.

### CODE REVIEW

File: client/components/infinite-list/scroll-helper.js [hunk 1]
```diff
@@ -47,71 +47,53 @@ class ScrollHelper {
 		return height;
 	}
 
-	forEachInRow( index, callback, context ) {
-		if ( typeof callback !== 'function' ) {
-			return;
-		}
+	forEachInRow( index, callback ) {
```
Comment (blowery) [inline client/components/infinite-list/scroll-helper.js]: nice change. yay for modernity.

File: client/reader/stream/index.jsx [hunk 2]
```diff
@@ -157,8 +159,8 @@ class ReaderStream extends React.Component {
 		KeyboardShortcuts.on( 'like-selection', this.toggleLikeOnSelectedPost );
 		KeyboardShortcuts.on( 'go-to-top', this.goToTop );
 		window.addEventListener( 'popstate', this._popstate );
-		if ( 'scrollRestoration' in history ) {
-			history.scrollRestoration = 'manual';
+		if ( 'scrollRestoration' in window.history ) {
```
Comment (blowery) [inline client/reader/stream/index.jsx]: should we guard this against a node-like environment by checking to see if `window` is an object?

File: client/reader/stream/index.jsx [hunk 3]
```diff
@@ -117,7 +119,7 @@ class ReaderStream extends React.Component {
 	}
 
 	_popstate = () => {
-		if ( this.props.selectedPostKey && history.scrollRestoration !== 'manual' ) {
+		if ( this.props.selectedPostKey && window.history.scrollRestoration !== 'manual' ) {
```
Comment (blowery) [inline client/reader/stream/index.jsx]: this one i'm not worried about because it's a handler that would only be called if we had attached to history

File: client/reader/stream/index.jsx [hunk 4]
```diff
@@ -365,6 +370,7 @@ class ReaderStream extends React.Component {
 		return (
 			<PostLifecycle
 				key={ itemKey }
+				ref={ itemKey /* The ref is stored into `InfiniteList`'s `this.ref` map */ }
```
Comment (blowery) [inline client/reader/stream/index.jsx]: tangent: reworking infinite list to use modern refs if going to be an interesting challenge.

**Review by blowery — APPROVED** [review]
LGTM, stream works as expected.

File: client/reader/stream/index.jsx (hunk 2 above)
Comment (jsnajdr) [reply client/reader/stream/index.jsx]: It's `componentDidMount`, therefore it's never called in SSR.

The methods that need to be SSR safe are the constructor, `componentWillMount` and `render`. All others are run only in interactive environment, i.e., only in browser.

File: client/reader/stream/index.jsx (hunk 4 above)
Comment (jsnajdr) [reply client/reader/stream/index.jsx]: We already did something like that three or four times, and it's not that hard. In cases like this, you want to replicate the `this.refs` map by implementing your own:
```jsx
itemElements = new Map();

storeElementRef( itemKey ) {
  return el => {
    if ( el ) {
      this.itemElements.set( itemKey, el );
    } else {
      this.itemElements.delete( itemKey );
    }
  }
}

render() {
  return (
    <ul>
      {
        this.props.items.map( item => (
          <li ref={ this.storeElementRef( item.id ) }>{ item.text }</li>
        )
      }
    </ul>
  );
}
```
