### PR TITLE
Plans (grid): Reflect storage add-on selection on intro offer price and billing desc

### LINKED ISSUE #95342: `/start/plans` in INR: Storage addon does not show updated prices
### Quick summary

In INR currency, selecting a storage addon does not update the price of the plan in the pricing grid. This issue is potentially seen in other first-year discounted currencies MXN and PHP, though I've not tested in those currencies. 

### Steps to reproduce

1. In INR currency, visit /start/plans
2. On the Business plan, select the 150GB storage addon

### What you expected to happen

I expected the plan price in the pricing grid to be updated with the storage addon's price

### What actually happened

The original (non-discounted and crossed-out) price was updated, but the current (discounted) price was not updated.

https://github.com/user-attachments/assets/c3491c06-3a0e-4a86-b664-e28d95880132

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

cc @Automattic/martech-decepticons

### PR DESCRIPTION
**Pull request by chriskmnds**
Fixes https://github.com/Automattic/wp-calypso/issues/95342

## Proposed Changes

- Enables storage selection in the plans grid to be reflected on the intro offer prices.

I'll skip a long description as I've run out of time. Read https://github.com/Automattic/wp-calypso/issues/95342 as this precisely addresses the issue

## Why are these changes being made?

Fix https://github.com/Automattic/wp-calypso/issues/95342 

## Testing Instructions

**Main:**

* Switch to INR currency (or other currency that gives first-year discount)
* Go to `/plans/:site` and `/start/plans` (or `/setup/onboarding/plans`)
* Confirm prices and billing descriptions are rendered correctly with the intro & cross-out pricing
* Go to Business or Commerce plans in the grid and select a storage add-on upgrade
* Confirm the pricing is updated to reflect the additional cost (as done for non discounted currencies)
* Repeat with USD/EUR and confirm the same

**Other:**

These changes also affect intro-offers displayed elsewhere.
- Confirm the upgrade-plan for the migration flow renders the intro pricing correctly cc @merkushin 

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: packages/data-stores/src/plans/hooks/test/use-pricing-meta-for-grid-plans.ts [hunk 1]
```diff
@@ -257,24 +248,30 @@ describe( 'usePricingMetaForGridPlans', () => {
...
-			};
-		};
+		Plans.useSitePlans.mockImplementation( () => ( {
+			isLoading: false,
+			data: {
+				[ PLAN_BUSINESS ]: {
+					...SITE_PLANS[ PLAN_BUSINESS ],
+					pricing: {
+						...SITE_PLANS[ PLAN_BUSINESS ].pricing,
+						costOverrides: [ { overrideCode: COST_OVERRIDE_REASONS.RECENT_PLAN_PRORATION } ],
```
Comment (chriskmnds) [inline packages/data-stores/src/plans/hooks/test/use-pricing-meta-for-grid-plans.ts:258]: No idea why this test worked previously. This is needed for the condition to pass, but curious if I'm missing something. @aneeshd16 would you mind confirming?

**Comment by jeyip** [comment]
## Testing
### Requirements

All prices were tested in INR / USD / EUR:

`/plans/:site`
- [ ] Confirm prices and billing descriptions are rendered correctly with the intro & cross-out pricing
- [ ] Go to Business or Commerce plans in the grid and select a storage add-on upgrade. Confirm the pricing is updated to reflect the additional cost ( as done for non discounted currencies )

`/start/plans`
- [ ] Confirm prices and billing descriptions are rendered correctly with the intro & cross-out pricing
- [ ] Go to Business or Commerce plans in the grid and select a storage add-on upgrade. Confirm the pricing is updated to reflect the additional cost (as done for non discounted currencies)

`/setup/onboarding/plans`
- [ ] Confirm prices and billing descriptions are rendered correctly with the intro & cross-out pricing
- [ ] Go to Business or Commerce plans in the grid and select a storage add-on upgrade. Confirm the pricing is updated to reflect the additional cost (as done for non discounted currencies)

### Browsers
- [x] Chrome

File: packages/data-stores/src/plans/hooks/test/use-pricing-meta-for-grid-plans.ts [hunk 2]
```diff
@@ -286,7 +283,119 @@ describe( 'usePricingMetaForGridPlans', () => {
...
+						SITE_PLANS[ PLAN_BUSINESS ].pricing.discountedPrice.monthly +
+						STORAGE_ADD_ONS_MOCK[ 0 ].prices.monthlyPrice,
+				},
+				billingPeriod: SITE_PLANS[ PLAN_BUSINESS ].pricing.billPeriod,
+				currencyCode: SITE_PLANS[ PLAN_BUSINESS ].pricing.currencyCode,
+				expiry: null,
+				introOffer: {
+					...introOffer,
+					rawPrice: {
+						monthly: 12.5 + STORAGE_ADD_ONS_MOCK[ 0 ].prices.monthlyPrice,
```
Comment (jeyip) [inline packages/data-stores/src/plans/hooks/test/use-pricing-meta-for-grid-plans.ts:395]: `Non-blocking / Nitpick :`

I believe that we can retrieve the rawPrice intro offer prices from the introOffer object https://github.com/Automattic/wp-calypso/pull/95428/files#diff-a46b47c6eea7443bc49db0374dd5b54d5a14a95c388dd9cca9481ce161ba6fcfR76-R77

File: packages/plans-grid-next/src/hooks/data-store/use-plan-billing-description.tsx [hunk 3]
```diff
@@ -224,7 +232,7 @@ export default function usePlanBillingDescription( {
 							'then %(rawPrice)s billed annually, excl. taxes',
 						{
 							args: {
-								introOfferFormattedPrice: introOffer.formattedPrice,
+								introOfferFormattedPrice: introOfferFullTermText,
```
Comment (jeyip) [inline packages/plans-grid-next/src/hooks/data-store/use-plan-billing-description.tsx:235]: `Non-blocking / Nitpick:`

I noticed that you marked the introOffer.formattedPrice field [as deprecated](https://github.com/Automattic/wp-calypso/pull/95428/files#diff-d822933ae1c209e261cde32fc0c43cf346c6271be748990c5c5edd5c289f48bcR70-R73).

I did a cursory search and didn't see other usages of `introOffer.formattedPrice` ( it was fast so not 100% certain ), so we might be able to remove the `formattedPrice` field entirely. Not important for this PR, but wondering what your thoughts are @chriskmnds

File: packages/data-stores/src/plans/hooks/use-pricing-meta-for-grid-plans.ts [hunk 4]
```diff
@@ -112,6 +113,7 @@ const usePricingMetaForGridPlans = ( {
 					originalPrice: Plans.PlanPricing[ 'originalPrice' ];
 					discountedPrice: Plans.PlanPricing[ 'discountedPrice' ];
 					currencyCode: Plans.PlanPricing[ 'currencyCode' ];
+					introOffer: Plans.PlanPricing[ 'introOffer' ];
```
Comment (jeyip) [inline packages/data-stores/src/plans/hooks/use-pricing-meta-for-grid-plans.ts:116]: `Non-blocking / Nitpick:`

It might be worth clearly differentiating between `discountPrice` and `introOffer`, whether it be an inline comment here or elsewhere. I'm assuming that intro offers are also discounted prices, but for _new_ customers only?

**Review by jeyip — APPROVED** [review]
The approach makes sense to me. For others following along, we:

- Update pricing meta to account for storage add-ons in intro offer pricing
- Update the header price component, which references the pricing meta
- Update billing description hook, which references the pricing meta

Left non-blocking comments, but otherwise LGTM. @chriskmnds let me know if you'd like me to create any issues for the comments -- happy to take care of that. 🚢

**Comment by jeyip** [comment]
@merkushin you're mentioned in Christos's PR description.

> Confirm the upgrade-plan for the migration flow renders the intro pricing correctly cc @merkushin

Would you mind confirming the above? Everything else looks good to go.

File: packages/data-stores/src/plans/hooks/test/use-pricing-meta-for-grid-plans.ts (hunk 1 above)
Comment (aneeshd16) [reply packages/data-stores/src/plans/hooks/test/use-pricing-meta-for-grid-plans.ts:258]: This was previously defined in the mock here: https://github.com/Automattic/wp-calypso/blob/8bab616ec6c7f2d8877bb5c16d88c149fd40a21e/packages/data-stores/src/plans/hooks/test/use-pricing-meta-for-grid-plans.ts#L81

File: packages/data-stores/src/plans/hooks/use-pricing-meta-for-grid-plans.ts (hunk 4 above)
Comment (aneeshd16) [reply packages/data-stores/src/plans/hooks/use-pricing-meta-for-grid-plans.ts:116]: Intro offers are a separate entity with it's own set of rules and configuration. Here's some more info :)
PCYsg-Wr4-p2

**Comment by aneeshd16** [comment]
Fixed the price display on the import upgrade screen via https://github.com/Automattic/wp-calypso/pull/95428/commits/c733a4d704a9bf4e99af0202c2f7a84764585e7a.

**Before**
image

**After**
image

**Review by aneeshd16 — APPROVED** [review]
