### PR TITLE
Frankenflow: Hide up-selling nudge

### LINKED ISSUE #39197: Gutenboarding: hide premium designs nudge in Frankenflow
Let's hide "premium designs" nudge in Gutenboarding pre-launch flow (Franken version).

#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/gutenboarding
2. "Press Create site" and end up in the editor, press "launch" button
3. Purchase a plan (I purchased Personal in this case)
4. End up at "premium designs" nudge

    Screenshot 2020-01-31 at 14 24 36

5. You can skip it with button at the bottom of the nudge:

    Screenshot 2020-01-31 at 14 24 51

#### What I expected
- No nudge

### PR DESCRIPTION
**Pull request by razvanpapadopol**
#### Changes proposed in this Pull Request
* Enable checkout customisation when coming from Frankenflow by adding `preLaunch=1` as query argument to the URL.
* Don't redirect to upsell nudge when coming from Frankenflow and buying a Personal or Premium plan

#### Testing instructions
* Go to `/start/frankenflow?siteSlug=SITE_SLUG` for a non-launched site
* Choose a paid plan and on the checkout page, the URL should include `preLaunch=1`
* Purchase the _Personal_ plan and you'll be redirected directly to home (no upsell nudge)
* When launching a site using the 'Launch site' button from home, nothing should change

#### Follow up
* We can now customize checkout step https://github.com/Automattic/wp-calypso/issues/38936 - PR: https://github.com/Automattic/wp-calypso/pull/39447

Fixes #39197

### CODE REVIEW

File: client/my-sites/checkout/checkout/index.jsx [hunk 1]
```diff
@@ -474,6 +474,11 @@ export class Checkout extends React.Component {
 	}
 
 	maybeRedirectToConciergeNudge( pendingOrReceiptId ) {
+		// For testing Frankenflow we disable any redirect to Nudge
```
Comment (simison) [inline client/my-sites/checkout/checkout/index.jsx]: It's a valid feature on its own for some flows — maybe we can even leave the comment out or make it more generic? :-)

Comment (razvanpapadopol) [reply client/my-sites/checkout/checkout/index.jsx]: Good point! So we'll enable it in `CheckoutContainer` based on `isComingFromFrankenflow` flag (which will be used also for customising the checkout screen header) and other flows could do the same.

**Comment by razvanpapadopol** [comment]
Rebased
