### PR TITLE
Fix/1275 disable disconnect link

### LINKED ISSUE #1275: Plugins: Feature Gate Bug user is able to disconnect jetpack
While on a single site plugin page that has the feature gate component. 
For example http://calypso.localhost:3000/plugins/example.com

The user is able to tab to the disconnect jetpack dialog and get to the disconnect button. 
screen shot 2015-12-04 at 09 51 14

I think it the site will not disconnected. if you click disconnect but we should prevent the user from even being able to tab to the link. 

cc @johnHackworth

### PR DESCRIPTION
**Pull request by enejb**
Fixes #1275 

Remove the ability to navigate to the disconnect link. Also remove the plugin info component if the plugin is display the mock version. 
Prevents this from happening:
screen shot 2016-01-21 at 14 21 09
After:
screen shot 2016-01-21 at 14 21 22

### CODE REVIEW

File: client/my-sites/plugins/disconnect-jetpack/disconnect-jetpack-button.jsx [hunk 1]
```diff
@@ -48,6 +49,9 @@ export default React.createClass( {
 			scary: true,
 			onClick: ( event ) => {
 				event.preventDefault();
+				if ( this.props.isMock ) {
+					return;
```
Comment (lezama) [inline client/my-sites/plugins/disconnect-jetpack/disconnect-jetpack-button.jsx]: Could we not render the `DisconnectJetpackButton` component at all if `isMock`?

Comment (lezama) [inline client/my-sites/plugins/disconnect-jetpack/disconnect-jetpack-button.jsx]: Like you did for `PluginInformation`

Comment (enejb) [inline client/my-sites/plugins/disconnect-jetpack/disconnect-jetpack-button.jsx]: I think the idea is that we still want the toggles and the disconnect buttons visible. Since they show the possible actions when that would be available to the user.

Comment (johnHackworth) [inline client/my-sites/plugins/disconnect-jetpack/disconnect-jetpack-button.jsx]: yup, the idea is to show the users what they are missing :)

**Comment by johnHackworth** [comment]
works great :+1:
