### PR TITLE
Prevent duplicate sites in signup 

### LINKED ISSUE #45862: Launch flow: Back button from checkout leads to a blank page
#### Steps to reproduce

1. Create a new site on the free plan and enter the site launch flow
2. Select a paid plan in the launch flow and enter checkout
3. On the checkout page, hit the browser back button

#### What I expected

I expected to see the launch flow UI

#### What happened instead

I got a blank page

#### Screenshot / Video

https://cloudup.com/c3RWuKqYRDu

### LINKED ISSUE #45905: Manage site flow: Allow to change subdomain
In pau2Xa-1Io-p2#comment-6759 , we take users clicking browser back from checkout through a modified signup flow. The domain step in this flow does not allow to change the subdomain of the user's current site.

#### Steps to reproduce

1. Starting at URL: wordpress.com/start
2. Select a paid plan and proceed to the checkout page
3. Hit browser back button on the checkout page. 
4. Wait till the domain step has finished rendering.

#### What I expected

I expected to change my current site's wordpress.com subdomain.

#### What happened instead

I am not shown any *.wordpress.com suggestions, and I'm not allowed to change the current site's subdomain. I'm however allowed to purchase a custom domain for the current site.

### PR DESCRIPTION
**Pull request by niranjan-uma-shankar**
#### Changes proposed in this Pull Request

* Detect if signup flow was loaded via back button, and in that case do not create a new site when the signup flow is complete.
* Check pau2Xa-1Io-p2#comment-6759 for an explanation on how this implementation works
* There's an edge case in which a user could end up seeing the launch flow UI version when going to wordpress.com/start to add a new site. But it's going to be an extremely rare case, and a few things have to align, so we can safely not bother about this issue:
    - Firstly, when the user is on checkout page from signup flow, they should navigate to a different part of Calypso on the _same tab_ without using the close button on checkout header, or empty cart action.
    - Next, on the _same tab_, they should navigate to wordpress.com/start by directly typing the URL in the address bar, or clicking a link that opens the page(on the same tab).
    - All of this should happen in < 1 day since a new site was created (signup destination cookie will expire in 1 day).
Important to note that this issue will not be a permanent problem - the user just needs to open wordpress.com/start in a new tab to see the regular signup flow again. Again, this is a super edge case and not something to worry about IMO.

#### Testing instructions

**Scenario 1** (Verify that going back from checkout page to signup, you can select a new domain/plan and complete purchase without creating a duplicate site).

1. Starting logged out of wpcom, go through the signup at wordpress.com/start and select a paid plan.
2. On the checkout page, hit browser back. Verify that you see the launch flow UI version:

Screenshot 2020-08-27 at 5 38 18 PM

3. Test the following two scenarios:
    (A) Selecting a free plan should take you to customer home and duplicate site should not be created. 
    (B) Select a custom domain and paid plan and complete payment. Verify that the new domain and plan got added to your site and that duplicate sites were not created.

**Scenario 2** (When on signup via browser back from checkout, page reload should not affect the UI)

1.  Starting logged out of wpcom, go through the signup at wordpress.com/start and select a paid plan.
2.  On the checkout page, hit browser back. Verify that you see the launch flow UI version (screen shot in Scenario 1)
3. Reload the page and verify that you still see the launch flow UI version.

**Scenario 3** (Add new site should work, and open the regular signup flow)

1.  Starting logged out of wpcom, go through the signup at wordpress.com/start and select a paid plan.
2.  On the checkout page, click the close button in the masterbar or empty all cart items.
3. Click "Add new site" from Calypso's sidebar, and verify that the domain step shows the regular signup flow UI(and not the launch flow UI)

**Scenario 4**
1. Try browser back from checkout in other flows besides `onboarding`, like in /start/premium, or the plan-domain swap flow*(for this you need to be assigned to the test variant, check https://github.com/Automattic/wp-calypso/pull/43675#pullrequestreview-440991033 for details on how to enter the variant).
2. In all these flows, you should be able to add purchase to the existing site without creating duplicates sites.

**Scenario 5** (When signup destination cookie is not cleared, closing tab and reopening a new tab should kill `sessionStorage` so /start should open "Add new site" flow instead of launch flow UI version)

1.  Starting logged out of wpcom, go through the signup at wordpress.com/start and select a paid plan.
2. On the checkout page, close tab and in a new tab, open wordpress.com/start
3. You should be taken to the "Add new site" flow to create a new site, with the regular signup UI.

**Scenario 6**

Verify that https://github.com/Automattic/wp-calypso/issues/45862 is fixed.

### CODE REVIEW

**Review by claudiucelfilip — APPROVED** [review]
Went through all scenarios and works as described; going back keeps the initial site and only updates the Order list on checkout.
Initially, I had my public-api sandbox, which caused a problem where I couldn't re-add the same domain if I removed it from the Order list. Fixed by un-sanboxing.

**Comment by aneeshd16** [comment]
>App Entrypoints (~35058 bytes added 📈 [gzipped])
>
>Details
>name        parsed_size            gzip_size
>entry-main    +132605 B  (+10.0%)   +35058 B  (+10.6%)

Hi @niranjan-uma-shankar, if I am reading it correctly, it says that around 132KB has been added to the main entry point which would cause longer load times. Is there anything that we can do to avoid this?

File: client/my-sites/checkout/controller.jsx [hunk 1]
```diff
@@ -70,6 +71,19 @@ export function checkout( context, next ) {
 		context.pathname.includes( '/checkout/no-site' ) &&
 		'no-user' === context.query.cart;
 
+	const searchParams = new URLSearchParams( window.location.search );
+	const isSignupCheckout = searchParams.get( 'signup' ) === '1';
```
Comment (southp) [inline client/my-sites/checkout/controller.jsx:75]: Could you help me point out where this is set in the first place? I'd like to confirm how confident we can rely on this.

File: client/my-sites/checkout/controller.jsx [hunk 2]
```diff
@@ -70,6 +71,19 @@ export function checkout( context, next ) {
...
+
+	if ( isSignupCheckout && ! isDomainOnlyFlow ) {
+		window.addEventListener( 'beforeunload', function () {
+			const signupDestinationCookieExists = retrieveSignupDestination();
+
+			if ( signupDestinationCookieExists ) {
+				sessionStorage.setItem( 'signupCheckoutPageUnloaded', true ); // eslint-disable-line no-undef
```
Comment (southp) [inline client/my-sites/checkout/controller.jsx:82]: Just like what you've done with the cookie, I'd suggest to abstract the access to this session storage flag as a pair of getter/setter in utils.js, so we can both name them as meaningful functions and keep them in one place for easier maintenance.

File: client/signup/main.jsx [hunk 3]
```diff
@@ -161,6 +165,23 @@ class Signup extends React.Component {
 			providedDependencies = pick( queryObject, flow.providesDependenciesInQuery );
 		}
 
+		const searchParams = new URLSearchParams( window.location.search );
+		const isAddNewSiteFlow = searchParams.has( 'ref' );
```
Comment (southp) [inline client/signup/main.jsx:169]: I am not sure I understand this. Could you help me understand why we can rely on this?

**Comment by southp** [comment]
@niranjan-uma-shankar I have run through all the test scenarios and a few other combinations, and everything works perfectly. However, I'd need your help clarifying a few questions in the inlined comments so I can review more properly. Thanks :)

File: client/my-sites/checkout/controller.jsx (hunk 1 above)
Comment (niranjan-uma-shankar) [reply client/my-sites/checkout/controller.jsx:75]: It is being set in [this line](https://github.com/Automattic/wp-calypso/blob/master/client/signup/config/flows.js#L26).

File: client/signup/main.jsx (hunk 3 above)
Comment (niranjan-uma-shankar) [reply client/signup/main.jsx:169]: Clicking on "Add new site" from Calypso will take to the signup flow with a `ref` query parameter([code ref](https://github.com/Automattic/wp-calypso/blob/a2db298e5e1f43fa039fa1ec6a8667bb02a64099/client/my-sites/sidebar/index.jsx#L863)). If the ref exists, then the user clicked on "Add new site", and in this case we will delete the signup destination cookie since the user is already inside Calypso.

**Comment by niranjan-uma-shankar** [comment]
>  if I am reading it correctly, it says that around 132KB has been added to the main entry point which would cause longer load times. Is there anything that we can do to avoid this?

@aneeshd16 Thanks for spotting that! I rebased today and the number has halved to ~60KB. Is that still a bit high for a change of this nature? I don't know, but I'm also not calling any packages.

**Comment by aneeshd16** [comment]
> @aneeshd16 Thanks for spotting that! I rebased today and the number has halved to ~60KB. Is that still a bit high for a change of this nature?

We did get a call-out for this when the size was 18KB, so this maybe an issue.
https://github.com/Automattic/wp-calypso/pull/44223#issuecomment-674829532
https://github.com/Automattic/wp-calypso/pull/44644#issuecomment-674839076

>  I don't know, but I'm also not calling any packages.

It is probably because additional imports are causing the bundles to be built in a different way - adding size to the main bundle while reducing it from other bundles. I am not sure specifically which import might cause this, but it could be this one:
https://github.com/Automattic/wp-calypso/pull/45040/files#diff-8302628106a075feef9e1f2c79429ff7R43

File: client/my-sites/checkout/controller.jsx (hunk 2 above)
Comment (niranjan-uma-shankar) [reply client/my-sites/checkout/controller.jsx]: Done - I've moved sessionStorage getters and setters to their own utils file.

**Comment by niranjan-uma-shankar** [comment]
> We did get a call-out for this when the size was 18KB, so this maybe an issue.

@aneeshd16 I refactored the code and moved the checkout masterbar to be async loaded, and moved the utils to another file. Looks like this has greatly helped reduce the size:

Screenshot 2020-09-22 at 7 18 06 PM

**Comment by niranjan-uma-shankar** [comment]
@Automattic/shilling I've added y'all as reviewers since this PR makes the masterbar in checkout page to be async loaded. This really helped reduce bundle size([check comment](https://github.com/Automattic/wp-calypso/pull/45040#issuecomment-696734223)). If you can confirm no issues with the checkout masterbar related confirm, that would be awesome. 

Besides wpcom, I verified the masterbar renders well in Jetpack too:

signup

**Comment by niranjan-uma-shankar** [comment]
I pushed a cleanup in [12be1bc](https://github.com/Automattic/wp-calypso/pull/45040/commits/12be1bc5c8254601c43ad652d3a0d8e8622c350e) since I realized that I don't need to create yet another cookie when I could just use session storage.

**Review by sirbrillig — APPROVED** [review]
> this PR makes the masterbar in checkout page to be async loaded. This really helped reduce bundle size(check comment). If you can confirm no issues with the checkout masterbar related confirm, that would be awesome.

Thank you for asking! I tried it out, and while I didn't run through the full testing instructions, I don't see any issues with the masterbar in Jetpack or WPCOM checkout.

There will be a small conflict fix needed when https://github.com/Automattic/wp-calypso/pull/45558 lands because I moved `useRedirectIfCartEmpty` to its own file (sorry!) but ultimately that should help that hook be easier to work with.

File: client/signup/main.jsx [hunk 4]
```diff
@@ -161,6 +167,23 @@ class Signup extends React.Component {
...
+
+		if ( isAddNewSiteFlow ) {
+			clearSignupDestinationCookie();
+		}
+
+		const wasSignupCheckoutUnnloaded = getFromSessionStorage( 'signupCheckoutPageUnloaded' );
```
Comment (aneeshd16) [inline client/signup/main.jsx:177]: Do you think it will be better to have functions explicitly get/set these values rather than relying on strings? For example - `get(set)SignupCheckoutPageUnloaded()`, `get(set)SignupCompleteSlug()`. The wrapper functions otherwise do not extend `sessionStorage` functionality.

**Review by aneeshd16 — COMMENTED** [review]
Tested these scenarios, looks good to me! I have one minor nitpick in the comments :)

Also, thanks for making the masterbar to be async loaded, it looks like a lot of savings. 🚀

File: client/signup/storageUtils.js [hunk 5]
```diff
@@ -0,0 +1,32 @@
+/**
+ * Exernal dependencies
```
Comment (southp) [inline client/signup/storageUtils.js:2]: Typo: Exernal -> External

File: client/signup/main.jsx (hunk 4 above)
Comment (southp) [reply client/signup/main.jsx:177]: I'd like to second what @aneeshd16 proposed here, since it was actually what I meant when I left [this comment](https://github.com/Automattic/wp-calypso/pull/45040#discussion_r485482467) :)

Borrowing the terms from mathematics, the primary purpose of abstracting them into specific getter/setter here is to restrain the domains and the ranges of these functions so that they are unlikely to be misused. 

Also, I think `wasSignupCheckoutUnnloaded` has an redundant n here? i.e. Unnloaded -> Unloaded?

File: client/signup/storageUtils.js (hunk 5 above)
Comment (niranjan-uma-shankar) [reply client/signup/storageUtils.js]: Thanks for catching that. I copied this line from utils.js, and I didn't notice the typo. I now fixed it in both files.

File: client/signup/main.jsx (hunk 4 above)
Comment (niranjan-uma-shankar) [reply client/signup/main.jsx]: Feedback addressed.

**Review by aneeshd16 — APPROVED** [review]
