### PR TITLE
PaymentCountrySelect: only pre-select valid country codes

### LINKED ISSUE #25863: Edit Card Details: Country field not recognized
The following issue appears if one wants to update their card details. It doesn't seem to happen the first time one enters their payment details as the country field isn't prefilled then.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/purchases
2. Choose a subscription and hit "Edit Payment Method" / "Add Credit Card"
3. Insert card details without touching the pre-filled country field
4. Hit "Save Card"

#### What I expected

My updated payment details were saved.

#### What happened instead

An error appears which says the country field is missing.

#### Browser / OS version

any

#### Screenshot / Video

screen shot 2018-07-04 at 13 51 36

#### Context / Source

I had a user in chat who weren't able to update their card details. Tried to replicate myself and found this issue.

### PR DESCRIPTION
**Pull request by flootr**
closes #25863 

**Note:** I could use some feedback especially for the selector part.

### The problem

The `countryList` prop isn't filled at the time of mounting the `PaymentCountrySelect` component. Which means the check in `componentDidMount` will always return an empty `countryCode` to the `onCountrySelected` callback on first mount. However, we do use the country code we receive from the state to pre-select it anyways regardless of it's invalid state. 

### Proposed solution

Move the check whether a country code is valid from `componentDidMount` to the selector for the country code. Additionally we only use this one `countryCode` prop to report back to the `onCountrySelected` callback. I added a callback invocation in `componentDidUpdate` to cover the case where the state gets updated after the first mount and the change isn't covered by `handleFieldChange`.

### Testing instructions

1. Go to /me/purchases on this branch locally or https://calypso.live/?branch=fix/payment-cc
2. Select a subscription and choose either "Edit Payment Method" or "Add Credit Card" depending on what's there
3. If no country is pre-selected. Choose one, hit the back button and reload. Then do 2) again
4. A country should be pre-selected now. If you hit "Save Card" it shouldn't show an error message for the country field

If you compare with master you should see an error message [as described in the issue](https://github.com/Automattic/wp-calypso/issues/25863).

### CODE REVIEW

**Comment by DavidRothstein** [comment]
Interesting.  I'm reasonably convinced that this scenario used to work after I developed the original component, but not 100% positive :)  I think it's possible https://github.com/Automattic/wp-calypso/pull/25223 broke it?  Just looking at the diff there for the `componentDidMount` method:

```
-		if ( ! filter( this.props.countriesList.get(), { code: countryCode } ).length ) {
+		if ( ! filter( this.props.countriesList, { code: countryCode } ).length ) {
```

So it went from passing in an object that could be used to load the country list when necessary, to passing in a country list that may or may not have been loaded yet.

The fix seems OK, but there are a couple things that aren't ideal:
- The `onCountrySelected` callback looks like it will get called twice whenever the field changes (once via `componentDidUpdate` and once via `handleFieldChange`)?  I am not sure if there are any side effects of that.
- I was originally trying to have the validation be based on the passed in `countriesList` property alone, without any assumption of what countries are contained in it.  With this patch it now assumes that `getCountries( state, 'payments' )` is always the list to validate against - even if that had no relationship to the actual countries in the dropdown.  It may not make a difference in practice, but it seems a little wrong.

Would it be possibe to address both those problems by keeping the validation internal to the component (in other words, not using the new `getValidPaymentCountryCode` selector) but just having the `componentDidMount` and `componentDidUpdate` methods be more careful about when they act?  For example, if `componentDidMount` were to bail out early like this:

```
// Don't do anything if the country list isn't ready yet.
if ( ! this.props.countriesList.length ) {
	return;
}
```

and if `componentDidUpdate` were to only take action right after the countries list was populated:

```
if ( ! prevProps.countriesList.length && this.props.countriesList.length ) {
	// Only do things in here.
}
```

then both of them could just do the same validation plus `onCountrySelected` call that `componentDidMount` does now?  And in that case, we'd guarantee that those two things always happen exactly once, immediately after the `countriesList` property is actually ready.

**Comment by flootr** [comment]
@DavidRothstein Thanks! Those are valid points and I agree those need to be addressed :)

One thing which isn't covered besides validation is, in the previous version we go ahead and pass on the `countryCode` - if there is one - to the underlying select component as selected value regardless of whether validation has failed. I want to fix that as well. We'd need to check whether the validation has already happened and only pass on this value if it was successful. 

Does that make sense for you?

**Comment by DavidRothstein** [comment]
Oh, good point.  Yes, that would be nice to fix.  (The impact is probably low because passing in an invalid selection to the select component should just result in nothing being selected... which is what we'd want anyway in that case.  But I agree it's worth fixing.)

> We'd need to check whether the validation has already happened and only pass on this value if it was successful.

The validation looks like it's pretty cheap, I think.  So one option might just be to re-run the validation in the `render()` method instead?  Or to avoid that, maybe store the validated value in `this.state` so it only needs to be calculated once?

File: client/components/payment-country-select/index.jsx [hunk 1]
```diff
@@ -33,19 +33,18 @@ export class PaymentCountrySelect extends Component {
...
+		this.props.onCountrySelected( this.props.name, this.props.countryCode );
 	};
 
+	componentDidUpdate( prevProps ) {
+		// In addition to 'componentDidMount' in case a valid countryCode
+		// is received on a later render not catched by 'handleFieldChange'
+		// i.e. a store update
+		if ( prevProps.countryCode !== this.props.countryCode ) {
+			this.props.onCountrySelected( this.props.name, this.props.countryCode );
+		}
```
Comment (dmsnell) [inline client/components/payment-country-select/index.jsx]: fun fact! React paid attention to common uses and created `getDerivedStateFromProps()` for situations like this were we are wanting to compare previous props to next props. in one function it handles the mount and update scenarios.

Comment (flootr) [reply client/components/payment-country-select/index.jsx]: I feel like `getDerivedStateFromProps` is not the right one here because it doesn't allow to compare with previous props by default. Other than `componentDidUpdate` it's receiving current props and if I understand it correctly we'd need to use state for a proper comparison.

Comment (dmsnell) [reply client/components/payment-country-select/index.jsx]: that's a correct inference. it changes how we compare to previous props in that we have to internalize them into state. at the same time it solves some other problems, notably here the duplication of the updating logic.

it's rather new and I won't say I fully understand it. just wanted to point it out 😄

**Comment by alisterscott** [comment]
Does this need more reviews before merging?

**Comment by flootr** [comment]
@alisterscott yup.

Pinging @DavidRothstein for another look. I implemented your suggestions but didn't found a quick solution for my additions. It's not a blocker though as you said correctly it shouldn't result in unexpected any behaviour for our users.
