### PR TITLE
E2E: discontinue `Editor: Basic Post Flow` from running as part of calypso-pr and calypso-release groups.

### LINKED ISSUE #59964: Playwright: do not run Gutenberg steps in Calypso suites
### Details

We've recently had instances where the Pre-Release tests flipped to failing due to issues caused by Gutenberg version upgrades. 

- https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Pre_Release/7227129
- https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Pre_Release/7213984

While this is useful, Pre-Release tests is not the appropriate place to detect Gutenberg regressions.

As discussed in p1641864184077500-slack-C02DQP0FP and p1641546921046300-slack-C02DQP0FP, separate out the non-Calypso steps from `Editor: Basic Post Flow` such that Gutenberg changes are not tested.

### Checklist

_No response_

### Related

_No response_

### PR DESCRIPTION
**Pull request by worldomonation**
#### Changes proposed in this Pull Request

This PR discontinues `Editor: Basic Post Flow` from running as part of the `calypso-pr` and `pre-release` groups.
The aforementioned groups are focused on Calypso behavior, not Gutenberg.

For more information, see discussion at p1641930193090800/1641546921.046300-slack-C02DQP0FP.

Key changes:
- remove `calypso-pr` and `calypso-release` groups from `Editor: Basic Post Flow`.
- use `Heading` post pattern instead of `About Me`.
- use conditional skip, as Preview step should not be skipped for mobile devices.
- move the spec file under `specs/specs-wpcom`.

#### Testing instructions

Ensure that:

- [x] Calypso E2E does not register this spec as having been run.
- [x] WPCOM Gutenberg E2E continues to run this spec.

### CODE REVIEW

**Review by cometgrrl — APPROVED** [review]
LGTM!

File: test/e2e/specs/specs-wpcom/wp-editor__post-basic-flow-spec.ts [hunk 1]
```diff
@@ -119,7 +117,7 @@ describe( DataHelper.createSuiteTitle( 'Editor: Basic Post Flow' ), function ()
 			}
 		} );
 
-		it.skip( 'Close preview', async function () {
+		skipItIf( targetDevice === 'desktop' )( 'Close preview', async function () {
```
Comment (fullofcaffeine) [inline test/e2e/specs/specs-wpcom/wp-editor__post-basic-flow-spec.ts:120]: That's a pretty neat guard pattern. Is that part of Jest?

Comment (worldomonation) [reply test/e2e/specs/specs-wpcom/wp-editor__post-basic-flow-spec.ts:120]: It's something we implemented ourselves in [this file](https://github.com/Automattic/wp-calypso/blob/trunk/packages/calypso-e2e/src/jest-conditionals.ts) :)
