### PR TITLE
Plugins: Fix back button behavior from search query

### LINKED ISSUE #12978: Plugin Section Navigation on Search and Select
NOTE: This was copied from a different repo, submitted by @JasonSnow-Mad. /cc @roundhill @drw158 as this is plugins section related. Questions/followups should go to him.

----------------------
While searching for plugins in Calypso (https://wordpress.com/plugins/browse/), if you select a plugin from the results to review it, and then use the back button, you are taken back to the Plugin Home screen, rather than your search results. 

**Searched for 'editor':**
cloudup-t4jwmgsxjvo

**Selected WP Editor:**
cloudup-x1ixylowdby

**Selected the 'Back' link and was taken back to the main plugins page:**
cloudup-d5sgmtdy03g

It would be better to return to the search results on 'Back'.

### PR DESCRIPTION
**Pull request by roundhill**
Plugins has had an interesting history of back navigation fixes for switching sites, searching, etc. The issue in #12978 arose somewhere along the way, where pressing the Back button doesn't return to a search query page.

Since the back behavior is quite fragile, this solution (based on a suggestion from @aduth, thank you!) seems to do the job without effecting the other scenarios for the back button's behavior.

I'm just getting familiar with Page.js myself, so any other ideas for a solution will be most welcome :)

**To test**
* Visit `/plugins` and visit the plugins browser.
* Enter a search query, and select one of the results.
* Press the `Back` button, you should return to the search query results.
* Test the back button in other scenarios, it should work as expected.

Fixes #12978

### CODE REVIEW

File: client/my-sites/plugins/index.js [hunk 1]
```diff
@@ -82,8 +82,12 @@ module.exports = function() {
 			pluginsController.eligibility
 		);
 
-		page.exit( '/plugins*',
-			pluginsController.resetHistory
-		);
+		page.exit( '/plugins*', ( context, next ) => {
+			if ( 0 !== page.current.indexOf( '/plugins' ) ) {
```
Comment (aduth) [inline client/my-sites/plugins/index.js]: Should we change this and the path pattern to include the trailing `/` in case we ever decide to add unrelated  `/plugins-foo` routes in the future?

I kinda hoped there'd be an easy way to reuse the regular expression generated by page.js here to avoid a string comparison on `'/plugins'` but it doesn't seem there's an easy way to get at that. At least not without some horrendous abuse of internal APIs such as:

```js
const exitRoute = new page.Route( '/plugins*' );
page.exits.push( exitRoute.middleware( ( context, next ) => {
	if ( ! exitRoute.regexp.test( page.current ) ) {
		pluginsController.resetHistory();
	}

	next();
} ) );
```

(The [page.js source](https://github.com/visionmedia/page.js/blob/master/page.js) is surprisingly approachable)

File: client/my-sites/plugins/controller.js [hunk 2]
```diff
@@ -258,10 +258,9 @@ const controller = {
 		renderPluginWarnings( context );
 	},
 
-	resetHistory( context, next ) {
+	resetHistory() {
```
Comment (aduth) [inline client/my-sites/plugins/controller.js]: Minor and probably fine, but at this point `resetHistory` is the only exported method which is not a proper page.js callback handler (i.e. not accepting `context`, `next`).

File: client/my-sites/plugins/index.js (hunk 1 above)
Comment (roundhill) [inline client/my-sites/plugins/index.js]: Makes sense, added in f6667c4 (also added it to the `exit()` path as well just in case)
