### PR TITLE
Playwright: Fix flaky signup spec and decouple magic link login from rest of script

### LINKED ISSUE #56318: Flaky E2E: New signup spec fails when trying to close account
### Spec

wp-signup__free.ts

### Suite

Delete account permanently

### Framework

Playwright

### Logs

Sometimes:

```
waiting for selector ".sidebar a:has(span:has-text("Account Settings"))"
  selector resolved to visible <a href="/me/account" class="sidebar__menu-link">…</a>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
element was detached from the DOM, retrying
waiting for selector ".sidebar a:has(span:has-text("Account Settings"))"
  selector resolved to hidden <a href="/me/account" class="sidebar__menu-link">…</a>
attempting click action
  waiting for element to be visible, enabled and stable
element is not visible - waiting...
element is visible, enabled and stable
element was detached from the DOM, retrying
waiting for selector ".sidebar a:has(span:has-text("Account Settings"))"
```

Also can run into:
```
page.click: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "p:text("Close your account permanently")"
============================================================
```

It looks like from the videos that after following the mail link in, it quickly switches from the account page to the home page. Looking into that.

### PR DESCRIPTION
**Pull request by dpasque**
#### Changes proposed in this Pull Request

This PR fixes two issues with the free signup Playwright spec.

1. As documented in #56318, the signup spec has had some flakeyness. The issue happens after logging in with the magic link and trying to navigate to the `/me` page.

There's a race condition that happens when trying to navigate right after logging in with the magic link. Logging in through the magic link goes through several different redirects (real and "fake" react navigations) before settling. The navbar button to navigate to `/me` technically becomes visible and active before everything has settled. So what happens is that `wordpress.com` loads, Playwright clicks the button to navigate to `/me`, then there is a navigation to `wordpress.com/home/<site name>`, and that navigation takes the script out of the `/me` page and back to the home page.

2. All magic links use the `wordpress.com` host. This means if you continue anything in the spec after using a magic link login, you are no longer testing your target host of Calypso. This means the deletion part of the spec is always running against  staging/prod.

Both of of these are solved with the same solution - after following the magic link, force a re-login at the correct host before carrying on with the rest of the spec.

#### Testing instructions
- Update your `calypsoBaseURL` in config to point to a different host, like `wpcalypso.wordpress.com`
- [x] `TARGET_DEVICE=mobile yarn jest specs/specs-playwright/wp-signup__free.ts`
- [x] `TARGET_DEVICE=desktop yarn jest specs/specs-playwright/wp-signup__free.ts`

Fixes #56318

### CODE REVIEW

File: packages/calypso-e2e/src/lib/components/navbar-component.ts [hunk 1]
```diff
@@ -55,6 +55,7 @@ export class NavbarComponent {
 	 * Click on `Me` on top right of the Home dashboard.
 	 */
 	async clickMe(): Promise< void > {
+		await this.pageSettled();
```
Comment (worldomonation) [inline packages/calypso-e2e/src/lib/components/navbar-component.ts:58]: Ah good call on this one

**Review by worldomonation — APPROVED** [review]
🥇
