### PR TITLE
Anchor: Add error handling for invalid podcast ID

### LINKED ISSUE #63216: Anchor: Add error handling for invalid podcast ID
The old flow shows an error when attempting to start the flow with an invalid podcast ID param for `anchor_podcast` -- we should probably do the same rather than failing silently.

Example, when you visit `wordpress.com/new?anchor_podcast=something`:

Screen Shot 2022-05-02 at 11 46 42 AM

### PR DESCRIPTION
**Pull request by valterlorran**
#### Changes proposed in this Pull Request

* Add the error step on the Anchor.fm flow when the `anchor_podcast` param is invalid.

Screen Shot 2022-05-10 at 15 54 27

#### Testing instructions

* Go to `/setup/error?anchor_podcast=invalid` and you should be redirected to the error step.

Depends on #63284

Closes #63216

### CODE REVIEW

File: client/landing/stepper/declarative-flow/internals/steps-repository/error-step/index.tsx [hunk 1]
```diff
@@ -25,12 +25,12 @@ const ErrorStep: Step = function ErrorStep( { navigation } ) {
 		domain = siteDomains[ 0 ].domain;
 	}
 
-	const headerText = siteSetupError ? siteSetupError.error : __( "We've hit a snag" );
```
Comment (andres-blanco) [inline client/landing/stepper/declarative-flow/internals/steps-repository/error-step/index.tsx]: This kind of syntax changes are better handled in a separate PR. That way the actual feature being implemented is easier to follow 👍

Comment (andres-blanco) [inline client/landing/stepper/declarative-flow/internals/steps-repository/error-step/index.tsx]: This kind of syntax changes should be handled in a separate PR. That way the actual feature being implemented is easier to follow 👍

Comment (valterlorran) [reply client/landing/stepper/declarative-flow/internals/steps-repository/error-step/index.tsx]: This change is actually in another PR(#63284) that I used as the basis for this one. Let me know if that's the correct way to do it.

Comment (andres-blanco) [reply client/landing/stepper/declarative-flow/internals/steps-repository/error-step/index.tsx]: Oh I didn't notice. I will re-review once the other PR is merged!

**Review by sixhours — APPROVED** [review]
This works! 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7305103

Thank you @valterlorran for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7305103).
