### PR TITLE
Focused Launch: Add Launch your site button

### LINKED ISSUE #47241: Domain Step: saving selection data to the launch store and the cart
- [x] Any change to the selected (or unselected) plan or domain should be saved in the `@automattic/launch` data store, so that the user can stop and resume the site launch and keep their existing selections
- [x] When the user is launching their site having selected a paid plan (and possibly also a domain) they need to be taken to the checkout step. At this point, all of the items in the cart should be removed, and replaced by the items selected in the launch data store (this is to avoid potentially showing more than one custom domain to the user)

### LINKED ISSUE #47392: Focused Launch: "Launch your site" button
- [x] The button should say _"Launch your site"_

- [x] The button should be disabled if at least one of the active steps doesn't have a valid selected value:

Screenshot 2020-11-12 at 21 03 57

- [x] The button should be enabled once all active steps have a valid selected value:

Screenshot 2020-11-12 at 21 04 11

- [x] If the user doesn't need to make any purchase, the button should take the user to the Success view (#47393)

- [x] If the user needs to make a purchase:
  - [x] (https://github.com/Automattic/wp-calypso/pull/47808) the button should take the user to the checkout screen and set the "success" URL redirection back to the Success view (spec'd in #47393, done in #47404).
  - [ ] When redirecting the user back to the editor (from Checkout) we should show the Success View (implemented in #47808)
  - [x] Data should be stored according to what defined in #47241

- [x] The button should be sticky at the bottom of the screen on mobile screens, and fill the whole width of the screen (apart from some padding around it):

Screenshot 2020-11-12 at 21 14 45

### LINKED ISSUE #47734: Focused Launch: selectedPlan is undefined if the site already has an associated premium plan
#### Steps to reproduce

1. Create a new site via `/start` — keep the default domain, but purchase a premium plan
2. Go to the block editor, append `?flags=create/focused-launch-flow` to the URL and refresh the page
3. Click on the "Launch" button in the editor's header
4. Focused Launch modal appears, but the Plan label is missing

#### Screenshot / Video

Markup 2020-11-25 at 12 21 21

#### Context / Source

From a quick look, it looks like the `getSelectedPlan()` selector used to  always returns `undefined`

https://github.com/Automattic/wp-calypso/blob/377dc0ab01cb12347cbba577e99529a910472890/packages%2Flaunch%2Fsrc%2Ffocused-launch%2Fsummary%2Findex.tsx#L272

This issue may be related to [this other bug](https://github.com/Automattic/wp-calypso/pull/47601#discussion_r529772106)

### PR DESCRIPTION
**Pull request by razvanpapadopol**
### Changes proposed in this Pull Request

- Display _"Launch your site"_ button sticky and full-width on mobile
- Disable _"Launch your site"_ button if at least one of the active steps doesn't have a valid selected value. Enable it otherwise.
- When pressing the button, show the loading screen first (success screen without buttons and with slightly different copy) cc: @ollierozdarz since this is not in designs; added to Screenshots section below.
- When the site is launched, show the Success view.
- If the user selected paid items during Launch flow, show Checkout overlay.
- Ignore any previous items existing in cart (eg: additional domains) and populate the cart only with selected items from Launch flow.

#### Todo (or follow up):
- [x]  When redirecting the user back to the editor from the thank you page or they navigate themselves to editor from plans page / My home / other pages in Calypso, Success View should be displayed unless the user clicks one of the action buttons to close it. (https://github.com/Automattic/wp-calypso/pull/47808)
- [x] Enable _"Launch your site"_ button if there is a paid plan and selected domain or paid plan and domain. https://github.com/Automattic/wp-calypso/pull/47601#discussion_r529772106
- [x] When pressing _"Launch your site"_ button, don't show checkout if:
   - there is a purchased plan and a purchased domain
   - there is a purchased plan and subdomain selected

## Testing instructions
1. Check out the branch on your machine and run in two parallel terminal windows:
  - `yarn && yarn start`
  - `cd apps/editing-toolkit && yarn dev --sync`
2. Add an _unlaunched_ site created with `/start` to your sandbox (for convenience, `SITE_ID`)
3. Visit `calypso.localhost:3000/page/SITE_ID/home?flags=create/focused-launch-flow` and click on the "Launch" button. The Focused Launch modal should appear.

#### Testing instructions (Focused launch free and paid flows)
4. Select free domain and plan and click "Launch your site" at the bottom => the loading view and then Success view should appear.
5. Repeat steps 2-3 and select a paid domain and a paid plan => the loading view and then checkout overlay should be displayed. Closing the checkout overlay should reveal the Success view so you can continue editing (no redirect).
6. Repeat steps 2, 3, 5 and complete purchase for a plan. You should be redirected to thank-you page (depending on the plan) and after skipping the upsell you should be redirected back to editor (WIP to show success view here).

#### Testing instructions (regression testing - Step by step launch)
8. Create a site on a free plan starting at `/new` and sandbox it.
9. Press launch in editor and launch flow with sidebar should appear.
10. Complete the flow by selecting a free plan => redirect to My home
11. Complete the flow by selecting a paid plan => redirect to `/checkout` with some known error mentioned in #47150

* Note: testing this in calypso overlay (using `?flags=create/focused-launch-flow-calypso` flag) will launch the site, add any selected paid items to cart, but won't open Checkout modal.

### Screenshot
Screenshot 2020-11-24 at 11 50 05

Fixes #47392
Fixes #47241
Fixes #47734

### CODE REVIEW

File: client/gutenberg/editor/calypsoify-iframe.tsx [hunk 1]
```diff
@@ -787,7 +794,6 @@ const mapStateToProps = (
 	const currentRoute = getCurrentRoute( state );
 	const postTypeTrashUrl = getPostTypeTrashUrl( state, postType );
 	const siteOption = isJetpackSite( state, siteId ) ? 'jetpack_frame_nonce' : 'frame_nonce';
-	const plan = getCurrentPlan( state, siteId );
```
Comment (razvanpapadopol) [inline client/gutenberg/editor/calypsoify-iframe.tsx:790]: just some cleanup after https://github.com/Automattic/wp-calypso/pull/47514/files#diff-94cbcc079892f7f8fb113398707b6a9b6394766e051b1f2c28f98334ad25015f

File: client/gutenberg/editor/calypsoify-iframe.tsx [hunk 2]
```diff
@@ -743,13 +749,14 @@ class CalypsoifyIframe extends Component<
 					source=""
 					visible={ isMediaModalVisible }
 				/>
-				{ isCheckoutOverlayEnabled && isCheckoutModalVisible && (
+				{ isCheckoutOverlayEnabled && (
```
Comment (razvanpapadopol) [inline client/gutenberg/editor/calypsoify-iframe.tsx:745]: allow pre-loading Checkout Modal before opening it

File: apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-modal/index.tsx [hunk 3]
```diff
@@ -24,24 +24,20 @@ interface Props {
...
+
 	const { step: currentStep, isSidebarFullscreen } = useSelect( ( select ) =>
 		select( LAUNCH_STORE ).getState()
 	);
-	const { launchSite } = useDispatch( LAUNCH_STORE );
-
 	const [ isLaunching, setIsLaunching ] = React.useState( false );
 
-	const { isPaidPlan } = useSite();
+	const { launchSite } = useDispatch( SITE_STORE );
```
Comment (razvanpapadopol) [inline apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-modal/index.tsx:34]: [Only for testing]: `launchSiteComplete` action can be dispatched to simulate a site launch without actually launching the site.

File: apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/attach-focused-launch.tsx [hunk 4]
```diff
@@ -3,34 +3,53 @@
...
+				doAction( HOOK_OPEN_CHECKOUT_MODAL );
+				return;
+			}
+
+			// fallback: redirect to /checkout page
+			const checkoutUrl = addQueryArgs( `https://wordpress.com/checkout/${ siteId }`, {
+				// Redirect to My Home after checkout only if the selected plan is not eCommerce
+				...( ! isEcommerce && { redirect_to: `/home/${ siteId }` } ),
+			} );
+			window.top.location.href = checkoutUrl;
```
Comment (ciampo) [inline apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/attach-focused-launch.tsx]: We should look into refactoring this line to share the same code for the `redirectTo` prop passed to `< FocusedLaunchModal />` (in this same file, just a few lines below)

File: client/blocks/editor-checkout-modal/index.tsx [hunk 5]
```diff
@@ -82,29 +82,31 @@ const EditorCheckoutModal = ( props: Props ) => {
...
-						isInEditor
-						siteId={ site.ID }
-						siteSlug={ site.slug }
-						productAliasFromUrl={ commaSeparatedProductSlugs }
-					/>
-				</StripeHookProvider>
-			</ShoppingCartProvider>
-		</Modal>
+	return (
+		isOpen && (
```
Comment (ciampo) [inline client/blocks/editor-checkout-modal/index.tsx:89]: What is the motivation for changing the check from `hasEmptyCart` to `isOpen` ?

File: client/blocks/editor-checkout-modal/index.tsx [hunk 6]
```diff
@@ -82,29 +82,31 @@ const EditorCheckoutModal = ( props: Props ) => {
...
+			<Modal
+				open={ isOpen }
+				overlayClassName="editor-checkout-modal"
+				onRequestClose={ onClose }
+				title=""
```
Comment (ciampo) [inline client/blocks/editor-checkout-modal/index.tsx]: I know it was already like this before this PR, but should provide a title?

File: client/gutenberg/editor/calypsoify-iframe.tsx (hunk 2 above)
Comment (ciampo) [reply client/gutenberg/editor/calypsoify-iframe.tsx:745]: What are the perf consequences of this? We may be loading the checkout modal even if we don't need it

File: packages/data-stores/src/launch/selectors.ts [hunk 7]
```diff
@@ -35,7 +37,12 @@ export const getSelectedPlan = ( state: State ): Plans.Plan | undefined => state
  */
 export const getPaidPlan = ( state: State ): Plans.Plan | undefined => state.paidPlan;
 
+// Check if a domain has been explicitly selected (including free subdomain)
+export const hasSelectedDomain = ( state: State ): boolean =>
+	!! getSelectedDomain( state ) || state.confirmedDomainSelection;
+
 // Completion status of steps is derived from the state of the launch flow
+// Warning: because it's using getEntityRecord it works only inside the editor
```
Comment (ciampo) [inline packages/data-stores/src/launch/selectors.ts:45]: Should we open a new issue to track/fix this ?

File: packages/data-stores/src/site/actions.ts [hunk 8]
```diff
@@ -95,18 +95,24 @@ export function createActions( clientCreds: WpcomClientCredentials ) {
...
 
 	function* launchSite( siteId: number ) {
+		yield launchSiteStart( siteId );
 		yield wpcomRequest( {
 			path: `/sites/${ siteId }/launch`,
 			apiVersion: '1.1',
 			method: 'post',
 		} );
-		yield launchedSite( siteId );
+		yield launchSiteComplete( siteId );
```
Comment (ciampo) [inline packages/data-stores/src/site/actions.ts:115]: We should add error handling on the `yield wpcomRequest()` call. Even an empty `try / catch` is probably better than having this action failing mid-way through.

Ideally, though, we should add a new `LAUNCH_SITE_ERROR` action, and handle that property in the reducer/selectors too. And therefore, also have the "launch error" UI ready. Not a blocker for this PR, but should probably be added to the backlog

File: packages/data-stores/src/site/reducer.ts [hunk 9]
```diff
@@ -101,12 +101,15 @@ export const sitesDomains: Reducer< { [ key: number ]: Domain[] }, Action > = (
...
-		return { ...state, [ action.siteId ]: true };
+export const launchStatus: Reducer<
+	{ [ key: number ]: { isLaunched: boolean; isSiteLaunching: boolean } },
+	Action
+> = ( state = {}, action ) => {
+	if ( action.type === 'LAUNCH_SITE_START' ) {
+		return { ...state, [ action.siteId ]: { isLaunched: false, isSiteLaunching: true } };
+	}
+	if ( action.type === 'LAUNCH_SITE_COMPLETE' ) {
+		return { ...state, [ action.siteId ]: { isLaunched: true, isSiteLaunching: false } };
```
Comment (ciampo) [inline packages/data-stores/src/site/reducer.ts]: See https://github.com/Automattic/wp-calypso/pull/47601/files#r529511556

File: packages/launch/src/context.ts [hunk 10]
```diff
@@ -16,6 +19,14 @@ const LaunchContext = React.createContext< LaunchContext >( {
 		// Won't work if trying to redirect the parent frame
 		window.location.href = url;
 	},
+	openCheckout: ( siteId, isEcommerce ) => {
+		window.top.location.href = addQueryArgs( `https://wordpress.com/checkout/${ siteId }`, {
```
Comment (ciampo) [inline packages/launch/src/context.ts]: should it use the `redirectTo` function just defined above?

At the moment the default values of `redirectTo` and `openCheckout` don't align — one assumes (by default) that the Launch flow is in the context of Calypso (uses `window.location`), the other assumes that it's in the context of the iframed block editor (uses `window.top.location`)

File: packages/launch/src/focused-launch/index.tsx [hunk 11]
```diff
@@ -2,26 +2,32 @@
...
 import './style.scss';
 
 const FocusedLaunch: React.FunctionComponent = () => {
-	// handle redirects to checkout / my home after launch
-	useOnLaunch();
+	const { isLaunched, isSiteLaunching } = useSite();
+
+	React.useEffect( () => {
+		if ( isLaunched || isSiteLaunching ) {
+			document.body.classList.add( 'is-focused-launch-complete' );
```
Comment (ciampo) [inline packages/launch/src/focused-launch/index.tsx:24]: Maybe a better alternative is not to append the launch button at all in https://github.com/Automattic/wp-calypso/blob/a669343f83369e6062273e009416d874c70a3aa1/apps%2Fediting-toolkit%2Fediting-toolkit-plugin%2Feditor-gutenboarding-launch%2Findex.ts#L156

File: packages/launch/src/focused-launch/index.tsx [hunk 12]
```diff
@@ -2,26 +2,32 @@
...
+		}
+	}, [ isLaunched, isSiteLaunching ] );
 
 	return (
 		<Router initialEntries={ [ FocusedLaunchRoute.Summary ] }>
+			{ ( isLaunched || isSiteLaunching ) && <Redirect to={ FocusedLaunchRoute.Success } /> }
```
Comment (ciampo) [inline packages/launch/src/focused-launch/index.tsx]: It looks like the "Success" view now is more of a "Launch complete" view. We should at least add a comment explaining that
- the `Success` view is shown also while the site is still launching
- the `Success` view is technically going to be the selected view in the modal even while the user goes through the checkout flow (which is rendered on top of this view)

In the long term, we should probably rename the `Success` view/route to reflect its new usage

File: packages/launch/src/launch/index.tsx [hunk 13]
```diff
@@ -1,45 +1,48 @@
 /**
  * External dependencies
  */
-import React, { useCallback } from 'react';
+import React from 'react';
```
Comment (ciampo) [inline packages/launch/src/launch/index.tsx]: Should it be changed to `import * as React from 'react'` ?

File: packages/launch/src/hooks/use-on-launch.ts [hunk 14]
```diff
@@ -72,5 +62,5 @@ export const useOnLaunch = () => {
 			}
 			window.top.location.href = `https://wordpress.com/home/${ siteId }`;
 		}
-	}, [ launchStatus ] );
+	}, [ isLaunched ] ); // eslint-disable-line react-hooks/exhaustive-deps
```
Comment (ciampo) [inline packages/launch/src/hooks/use-on-launch.ts]: Is there a reason why we're not setting all of the correct dependencies for this `useEffect` hook?

File: packages/launch/src/hooks/use-on-launch.ts [hunk 15]
```diff
@@ -72,5 +62,5 @@ export const useOnLaunch = () => {
 			}
 			window.top.location.href = `https://wordpress.com/home/${ siteId }`;
```
Comment (ciampo) [inline packages/launch/src/hooks/use-on-launch.ts]: I know it's not in the scope of this PR, but it'd be nice if we could the `redirectTo` function from the Launch context, instead of hardcoding the redirection.

File: packages/launch/src/launch/index.tsx [hunk 16]
```diff
@@ -1,45 +1,48 @@
...
 		select( LAUNCH_STORE ).isModalTitleVisible()
 	);
 
-	const onModalRequestClose = useCallback( () => {
-		isModalDismissible && onClose();
-	}, [ isModalDismissible, onClose ] );
+	const { closeFocusedLaunch } = useDispatch( LAUNCH_STORE );
+
+	const onModalRequestClose = () => {
+		closeFocusedLaunch();
```
Comment (ciampo) [inline packages/launch/src/launch/index.tsx]: Why was the `isModalDismissible` flag check removed?

**Review by ciampo — DISMISSED** [review]
I'll need to do more testing, but in the meantime, I've left a few comments after the first round of review.

Also noting that this PR will need to be rebased (and solve conflicts) since #47624 got merged

File: client/gutenberg/editor/calypsoify-iframe.tsx (hunk 2 above)
Comment (razvanpapadopol) [reply client/gutenberg/editor/calypsoify-iframe.tsx:745]: There are considerably more cases when we need it than when we don't. For example:
- All free and personal sites where a premium block has been added.
- All unlaunched sites once Launch button is clicked (even those with paid plans could use checkout to add a domain).
- [TBD] All sites on a subdomain if domain upsell modal is open.

Of course we can be more specific when to load it but until we add all the conditions above, if initial load time isn't affected, the overall improvement in UX overweights any downside from my perspective.

Cc'ing @tyxla for confirmation on perf impact.

File: client/blocks/editor-checkout-modal/index.tsx (hunk 5 above)
Comment (razvanpapadopol) [reply client/blocks/editor-checkout-modal/index.tsx:89]: `isOpen` was added in context of https://github.com/Automattic/wp-calypso/pull/47601#discussion_r529419721

I'll check this and probably re-add `hasEmptyCart` as an additional condition.

File: client/blocks/editor-checkout-modal/index.tsx (hunk 6 above)
Comment (razvanpapadopol) [reply client/blocks/editor-checkout-modal/index.tsx]: Are you thinking at a11y? In this case, yes, a title would be good. 

But not sure if we should also display it or not on screen. Cc: @ollierozdarz

File: packages/data-stores/src/site/actions.ts (hunk 8 above)
Comment (razvanpapadopol) [reply packages/data-stores/src/site/actions.ts:115]: Yes, good point. LAUNCH_SITE_ERROR action would also remove the loading state.

File: packages/launch/src/focused-launch/index.tsx (hunk 11 above)
Comment (razvanpapadopol) [reply packages/launch/src/focused-launch/index.tsx:24]: The button is already appended at this time and we don't refresh the page is the user is choosing to "continue editing".

File: client/gutenberg/editor/calypsoify-iframe.tsx (hunk 2 above)
Comment (tyxla) [reply client/gutenberg/editor/calypsoify-iframe.tsx:745]: From a perf standpoint I see no concerns here. What has been necessary here has already been done - the checkout modal is loaded asynchronously and that's enough to defer the loading for after the initial page load. In other words, initial loading time won't be affected by this because we're already asynchronously loading the checkout modal. 

> Of course we can be more specific when to load it but until we add all the conditions above, if initial load time isn't affected, the overall improvement in UX overweights any downside from my perspective.

Ditto. I agree the better user experience of seeing the checkout modal immediately is more important than the few extra bytes they might end up downloading in background, as long as the initial load speed is unaffected.

File: packages/launch/src/focused-launch/index.tsx (hunk 11 above)
Comment (ciampo) [reply packages/launch/src/focused-launch/index.tsx:24]: I see. I was hoping we could have a less hacky way of hiding the Launch button than adding a class to the `body`

File: client/gutenberg/editor/calypsoify-iframe.tsx (hunk 2 above)
Comment (ciampo) [reply client/gutenberg/editor/calypsoify-iframe.tsx:745]: Thank you both for the explanation. We can consider this review comment resolved.

File: packages/data-stores/src/site/reducer.ts [hunk 17]
```diff
@@ -101,12 +101,15 @@ export const sitesDomains: Reducer< { [ key: number ]: Domain[] }, Action > = (
...
 };
 
-export const launchStatus: Reducer< { [ key: number ]: boolean }, Action > = (
-	state = {},
-	action
-) => {
-	if ( action.type === 'LAUNCHED_SITE' ) {
-		return { ...state, [ action.siteId ]: true };
+export const launchStatus: Reducer<
+	{ [ key: number ]: { isLaunched: boolean; isSiteLaunching: boolean } },
```
Comment (ciampo) [inline packages/data-stores/src/site/reducer.ts]: We should name variables consistently — e.g `isSiteLaunched` and `isSiteLaunching`, or `isLaunched` and `isLaunching`

File: packages/launch/src/focused-launch/summary/index.tsx [hunk 18]
```diff
@@ -494,38 +495,47 @@ const PlanStep: React.FunctionComponent< PlanStepProps > = ( {
...
 	stepIndex: number;
 	forwardStepIndex: boolean;
-} ) => ReactNode;
+} ) => React.ReactNode;
 
 const Summary: React.FunctionComponent = () => {
-	const { title, updateTitle, saveTitle, isSiteTitleStepVisible, showSiteTitleStep } = useTitle();
+	const hasSelectedDomain = useSelect( ( select ) => select( LAUNCH_STORE ).hasSelectedDomain() );
+	const selectedDomain = useSelect( ( select ) => select( LAUNCH_STORE ).getSelectedDomain() );
+	const selectedPlan = useSelect( ( select ) => select( LAUNCH_STORE ).getSelectedPlan() );
```
Comment (ciampo) [inline packages/launch/src/focused-launch/summary/index.tsx:509]: Not sure if this bug was introduced by this PR, but if the site already has an associated premium plan, then `selectedPlan` seems to be `undefined`.

This causes 2 main issues:
- The disabled plan item at the top of the Summary view has an empty label

image

- The "Launch your site" button is always `disabled`

Comment (razvanpapadopol) [reply packages/launch/src/focused-launch/summary/index.tsx:509]: This is an existing issue (we need to open a GH ticket):
> The disabled plan item at the top of the Summary view has an empty label

Thanks for spotting the disabled button. Added a new item to the ToDo list in the description for it

File: packages/launch/src/launch/index.tsx (hunk 16 above)
Comment (razvanpapadopol) [reply packages/launch/src/launch/index.tsx]: We're already passing the flag to `Modal` at line 58 below so `onModalRequestClose` can't be called if the flag is set to `false`.

File: packages/launch/src/hooks/use-on-launch.ts (hunk 14 above)
Comment (razvanpapadopol) [reply packages/launch/src/hooks/use-on-launch.ts]: We want to run the code inside only once, when `isLaunched` becomes `true`. So think of it like `launchSite.then( () => { /* run what's inside the if( isLaunched ) condition above */ } )`.

I know the implementation with `useEffect` for this is not stellar and some chained action creators on Launch store would've been probably close to ideal. But because of the way wp-data works (or how we're using it) we ended up here. Anyway, once we migrate Step-by-step launch flow to using Editor checkout, we can remove this hook.

File: packages/launch/src/focused-launch/index.tsx (hunk 11 above)
Comment (razvanpapadopol) [reply packages/launch/src/focused-launch/index.tsx:24]: Yup, I can agree it's not ideal but at least it's cleaner than how we add the button. We'll have the non-hacky solution once we use some Gutenberg API to insert the button properly 😬

File: packages/launch/src/launch/index.tsx (hunk 16 above)
Comment (ciampo) [reply packages/launch/src/launch/index.tsx]: > We're already passing the flag to Modal at line 58 below so onModalRequestClose can't be called if the flag is set to false.

Unfortunately, the `isDismissible` seems to only hide the `X` button, but it won't prevent the modal from closing when pressing the `ESC` key — you should be able to reproduce this behaviour by pressing the `ESC` key when in the Success view.

It looks like this could be fixed in a cleaner way by passing more props to the `<Modal>`:

```
  [...]
  shouldCloseOnEsc={ isModalDismissible }
  shouldCloseOnClickOutside={ isModalDismissible }
```

At that point, the `onModalRequestClose()` wrapper function would become useless, and we could pass the `closeFocusedLaunch()` function directly to the `<Modal>` too:

```
  onRequestClose={ closeFocusedLaunch }
```

File: packages/data-stores/src/site/actions.ts (hunk 8 above)
Comment (ciampo) [reply packages/data-stores/src/site/actions.ts:115]: Yes, that's what I was thinking too. We should also add a flag in the reducer for when there is an error, and probably add a simple error message in the "Success" view, similar to what you already added for the loading state

File: packages/launch/src/focused-launch/summary/index.tsx (hunk 18 above)
Comment (ciampo) [reply packages/launch/src/focused-launch/summary/index.tsx:509]: > This is an existing issue (we need to open a GH ticket):

I opened https://github.com/Automattic/wp-calypso/issues/47734 to track this bug.

I believe there's a chance that fixing the bug afflicting the disabled "Launch your site" button will also fix this new issue.

File: packages/launch/src/hooks/use-on-launch.ts (hunk 14 above)
Comment (ciampo) [reply packages/launch/src/hooks/use-on-launch.ts]: Thank you for the explanation, good to keep this in mind for the next time we need to implement this sort of logic.

For the purpose of this PR, we can consider this conversation resolved

File: client/blocks/editor-checkout-modal/index.tsx (hunk 6 above)
Comment (ciampo) [reply client/blocks/editor-checkout-modal/index.tsx]: A way of improving the a11y without changing the current design could be:
1. Add a modal title
2. Hide it by using the`onboarding-screen-reader-text()` SCSS mixin from the [@automattic/onboarding package](https://github.com/Automattic/wp-calypso/blob/trunk/packages/onboarding/styles/mixins.scss#L239)

This is similar to the approach that we took for the [Focused Launch modal](https://github.com/Automattic/wp-calypso/blob/fd38eb47d0effef6a796e6548625b33dd7177d58/packages%2Flaunch%2Fsrc%2Flaunch%2Fstyles.scss#L60-L62)

File: packages/data-stores/src/launch/selectors.ts (hunk 7 above)
Comment (ciampo) [reply packages/data-stores/src/launch/selectors.ts:45]: I opened #47737 as agreed. This conversation can be considered resolved

File: packages/launch/src/focused-launch/summary/index.tsx (hunk 18 above)
Comment (razvanpapadopol) [reply packages/launch/src/focused-launch/summary/index.tsx:509]: Fixed the missing purchased plan label in https://github.com/Automattic/wp-calypso/pull/47601/commits/1a559a45892290b88d4880ab14e360550c172c08

Context: when https://github.com/Automattic/wp-calypso/pull/47378 was approved, the corresponding diff (D52710-code) wasn't yet deployed and finally it was abandoned in favour of a frontend solution.

Comment (ciampo) [reply packages/launch/src/focused-launch/summary/index.tsx:509]: Great find! Thank you for looking into this issue

Comment (razvanpapadopol) [reply packages/launch/src/focused-launch/summary/index.tsx:509]: Fixed also the second issue mentioned above (launch button being always disabled) in https://github.com/Automattic/wp-calypso/pull/47601/commits/f749acab90d87d8be50b42f772a89df02d7674d4

File: packages/data-stores/src/site/reducer.ts (hunk 17 above)
Comment (razvanpapadopol) [reply packages/data-stores/src/site/reducer.ts]: done in https://github.com/Automattic/wp-calypso/pull/47601/commits/a1d1ff86292dd085e7727e408c58c58c0ac8a684

File: packages/launch/src/launch/index.tsx (hunk 16 above)
Comment (razvanpapadopol) [reply packages/launch/src/launch/index.tsx]: Added those 2 props and removed `onModalRequestClose` in https://github.com/Automattic/wp-calypso/pull/47601/commits/2f1f213d9ab9424d3bf7e8f5a1ec13da2a93442d

File: packages/launch/src/launch/index.tsx (hunk 13 above)
Comment (razvanpapadopol) [reply packages/launch/src/launch/index.tsx]: Updated react imports for all the package in https://github.com/Automattic/wp-calypso/pull/47601/commits/2d9af7a3079d2968ccc129e0faa74a96d0e492c8

File: apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/attach-focused-launch.tsx (hunk 4 above)
Comment (razvanpapadopol) [reply apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/attach-focused-launch.tsx]: The implementation in https://github.com/Automattic/wp-calypso/pull/47601/commits/50da20ece08415bef2b1bfc513be0190d7256003 is what you had in mind?

File: client/blocks/editor-checkout-modal/index.tsx (hunk 5 above)
Comment (razvanpapadopol) [reply client/blocks/editor-checkout-modal/index.tsx:89]: `hasEmptyCart` is not actually checking if the cart is empty but rather if there are any products passed to the `EditorCheckoutModal` component. 

In the case of Launch, we're [just calling the hook](https://github.com/Automattic/wp-calypso/pull/47601/files#diff-2f5e6bd15fcaddc71644575361bf6a5f0193c51502cd8c5337a40d345d897cc9R41) to open the Checkout modal, without passing any products. They are already [added via a REST API call](https://github.com/Automattic/wp-calypso/blob/9644ddf7d0a588a2774d5b245664273a45079ab5/packages/launch/src/hooks/use-cart.ts#L30) to the cart before that.

File: apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/attach-focused-launch.tsx (hunk 4 above)
Comment (ciampo) [reply apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/attach-focused-launch.tsx]: What I had in mind was an even bigger refactor (with the main objective of hardcoding the `https://wordpress.com/` origin only once in the refactored function), but I realize now that it may be complicated given the `addQueryArgs`.

If it requires too long, we can leave it out of the scope of this PR

File: client/blocks/editor-checkout-modal/index.tsx (hunk 5 above)
Comment (ciampo) [reply client/blocks/editor-checkout-modal/index.tsx:89]: > `hasEmptyCart` is not actually checking if the cart is empty but rather if there are any products passed to the EditorCheckoutModal component.

Good to know

> In the case of Launch, we're just calling the hook to open the Checkout modal, without passing any products. They are already added via a REST API call to the cart before that.

Thank makes sense. We just need to make sure that changing the check from `hasEmptyCart` to `isOpen` won't affect any other flows that are using this block

File: client/blocks/editor-checkout-modal/index.tsx (hunk 6 above)
Comment (razvanpapadopol) [reply client/blocks/editor-checkout-modal/index.tsx]: Added title in https://github.com/Automattic/wp-calypso/pull/47601/commits/c562aa9d00927981250ea29a59071dfe286b4ce2

It's not straight forward to re-use the onboarding mixins since they bring also[ this z-index function](https://github.com/Automattic/wp-calypso/blob/trunk/packages/onboarding/styles/base-styles.scss#L1) (takes 1 argument) which is in conflict with [the one used in this file](https://github.com/Automattic/wp-calypso/blob/trunk/client/blocks/editor-checkout-modal/style.scss#L6) (two arguments). So an ideal solution would involve refactoring onboarding package first to get out that import and explicitly add it only where needed.

File: client/blocks/editor-checkout-modal/index.tsx (hunk 5 above)
Comment (razvanpapadopol) [reply client/blocks/editor-checkout-modal/index.tsx:89]: Tested premium blocks upgrade and it looks fine. It's also E2E tested now 😁

File: apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/attach-focused-launch.tsx (hunk 4 above)
Comment (razvanpapadopol) [reply apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/attach-focused-launch.tsx]: I see we're always using `wordpress.com` here and I'm not sure it's entirely correct to ignore the environment of the parent window (wpcalypso/horizon/etc). I'm thinking of e2e tests now.

Another example: https://github.com/Automattic/wp-calypso/blob/trunk/apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/final-step/index.tsx#L166

Let's leave this in the backlog for now.

File: packages/launch/src/context.ts (hunk 10 above)
Comment (razvanpapadopol) [reply packages/launch/src/context.ts]: Fixed in https://github.com/Automattic/wp-calypso/pull/47601/commits/9b5e7daa93b6ceecdfb86e30f470db302b2d0543

File: packages/launch/src/focused-launch/index.tsx (hunk 12 above)
Comment (razvanpapadopol) [reply packages/launch/src/focused-launch/index.tsx]: Added comment in https://github.com/Automattic/wp-calypso/pull/47601/commits/7f18ef996c0a7d6476887aac7302b9d9036019fa

File: apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/attach-focused-launch.tsx (hunk 4 above)
Comment (ciampo) [reply apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/attach-focused-launch.tsx]: I opened #47762 in the meantime

File: client/blocks/editor-checkout-modal/index.tsx (hunk 6 above)
Comment (ollierozdarz) [reply client/blocks/editor-checkout-modal/index.tsx]: Hi @ciampo, 

> Are you thinking at a11y? In this case, yes, a title would be good.
> But not sure if we should also display it or not on screen. Cc: @ollierozdarz 

What is the title here referring to?

Comment (razvanpapadopol) [reply client/blocks/editor-checkout-modal/index.tsx]: This would be the modal title, when displaying Checkout at the end of the launch flow. But at the moment we hide it (so it's there just for screen readers) and we display only the W icon as originally designed.

Screenshot 2020-11-26 at 09 14 45

File: packages/data-stores/src/site/actions.ts (hunk 8 above)
Comment (razvanpapadopol) [reply packages/data-stores/src/site/actions.ts:115]: Added https://github.com/Automattic/wp-calypso/issues/47782 to handle errors in this case and check the rest of the flow.

File: packages/launch/src/hooks/use-on-launch.ts (hunk 15 above)
Comment (razvanpapadopol) [reply packages/launch/src/hooks/use-on-launch.ts]: Done in https://github.com/Automattic/wp-calypso/pull/47601/commits/d20436594404d073ad4c931bf67f9b92cfb067f6

File: client/blocks/editor-checkout-modal/index.tsx (hunk 5 above)
Comment (ciampo) [reply client/blocks/editor-checkout-modal/index.tsx:89]: gotta love e2e tests!

File: client/blocks/editor-checkout-modal/index.tsx (hunk 6 above)
Comment (ciampo) [reply client/blocks/editor-checkout-modal/index.tsx]: To clarify further:
- at the beginning of this conversation the modal title was simply left empty
- @razvanpapadopol, then, made changes so that the modal title reads "Checkout modal" — although it's only accessible by screen readers, and is not visible in the browser

We wanted to confirm with you if this is a good approach, or if you think that we should instead also visually show the title in the browser

File: apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/attach-focused-launch.tsx [hunk 19]
```diff
@@ -3,40 +3,56 @@
...
+			} );
+			redirectParentWindow( checkoutUrl );
+		};
+
 		return (
 			<FocusedLaunchModal
-				siteId={ window._currentSiteId }
-				onClose={ closeFocusedLaunch }
+				siteId={ currentSiteId }
+				openCheckout={ handleCheckout }
```
Comment (ciampo) [inline apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/attach-focused-launch.tsx]: I'm getting a TypeScript error about the type of `siteId` in the `handleCheckout` function:

```
Type 'string' is not assignable to type 'number | undefined'
```

File: client/blocks/editor-launch-modal/index.tsx [hunk 20]
```diff
@@ -14,7 +14,14 @@ interface Props {
 }
 
 const EditorLaunchModal: React.FunctionComponent< Props > = ( { siteId, locale } ) => {
-	return <FocusedLaunchModal onClose={ noop } siteId={ siteId } locale={ locale } />;
+	return (
+		<FocusedLaunchModal
+			onClose={ noop }
```
Comment (ciampo) [inline client/blocks/editor-launch-modal/index.tsx]: This line should be deleted, since the `onClose` property has been removed from the `<FocusedLaunchModal />` component

```suggestion
```

File: apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/attach-focused-launch.tsx [hunk 21]
```diff
@@ -3,40 +3,56 @@
...
+				doAction( HOOK_OPEN_CHECKOUT_MODAL );
+				return;
+			}
+
+			// fallback: redirect to /checkout page
+			const checkoutUrl = addQueryArgs( `https://wordpress.com/checkout/${ siteId }`, {
+				// Redirect to My Home after checkout only if the selected plan is not eCommerce
+				...( ! isEcommerce && { redirect_to: `/home/${ siteId }` } ),
+			} );
+			redirectParentWindow( checkoutUrl );
```
Comment (ciampo) [inline apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/attach-focused-launch.tsx]: To further reduce the amount of hardcoded `https://wordpress.com` instances, we could:

- remove the `redirectParentWindow` import
- change this code snippet to:

```suggestion
			const checkoutUrl = addQueryArgs( `/checkout/${ siteId }`, {
				// Redirect to My Home after checkout only if the selected plan is not eCommerce
				...( ! isEcommerce && { redirect_to: `/home/${ siteId }` } ),
			} );
			redirectToWpcomPath( checkoutUrl );
```

File: apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/attach-launch-sidebar.tsx [hunk 22]
```diff
@@ -43,7 +45,13 @@ registerPlugin( 'a8c-editor-site-launch', {
 
 		return (
 			<LocaleProvider localeSlug={ window.wpcomEditorSiteLaunch?.locale }>
-				<LaunchContext.Provider value={ { siteId: window._currentSiteId } }>
+				<LaunchContext.Provider
+					value={ {
+						siteId: window._currentSiteId,
+						flow: FLOW_ID,
+						redirectTo: redirectToWpcomPath,
+					} }
```
Comment (ciampo) [inline apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/attach-launch-sidebar.tsx]: TypeScript error about the missing required properties `locale` and `openCheckout`

File: client/blocks/editor-checkout-modal/index.tsx [hunk 23]
```diff
@@ -82,29 +85,31 @@ const EditorCheckoutModal = ( props: Props ) => {
...
-				</StripeHookProvider>
-			</ShoppingCartProvider>
-		</Modal>
+	return (
+		isOpen && (
+			<Modal
+				open={ isOpen }
+				overlayClassName="editor-checkout-modal"
+				onRequestClose={ onClose }
+				title={ translate( 'Checkout modal' ) }
```
Comment (ciampo) [inline client/blocks/editor-checkout-modal/index.tsx]: TypeScript error `Type 'TranslateResult' is not assignable to type 'string'.`

File: client/blocks/editor-checkout-modal/index.tsx [hunk 24]
```diff
@@ -82,29 +85,31 @@ const EditorCheckoutModal = ( props: Props ) => {
 		: cartData.products.map( ( product ) => product.product_slug );
 	const commaSeparatedProductSlugs = productSlugs?.join( ',' ) || null;
```
Comment (ciampo) [inline client/blocks/editor-checkout-modal/index.tsx:86]:
```suggestion
	const commaSeparatedProductSlugs = productSlugs?.join( ',' );
```

I know it's not in the scope of this PR, but I noticed the TypeScript error while reviewing changes. The suggested change fixes the TypeScript error shown later in the same file when this variable is passed as the value of the `productAliasFromUrl` prop: `Type 'string | null' is not assignable to type 'string | undefined'`

cc @tjcafferkey to confirm this change won't break the composite checkout

Comment (ciampo) [reply client/blocks/editor-checkout-modal/index.tsx:86]: I actually opened #47798 to track this separately — going to mark this conversation as resolved. Sorry for the PR review noise

File: packages/launch/src/focused-launch/success/index.tsx [hunk 25]
```diff
@@ -3,39 +3,44 @@
 /**
  * External dependencies
  */
-import React, { useState, useEffect, useContext } from 'react';
+import React from 'react';
```
Comment (ciampo) [inline packages/launch/src/focused-launch/success/index.tsx]:
```suggestion
import * as React from 'react';
```

File: packages/launch/src/focused-launch/success/style.scss [hunk 26]
```diff
@@ -103,3 +103,19 @@
 		width: auto;
 	}
 }
+
+.focused-launch-success__go-back-button {
+	color: var( --studio-gray-50 );
+}
+
+.focused-launch-container .action-buttons:not( .is-sticky ) {
```
Comment (ciampo) [inline packages/launch/src/focused-launch/success/style.scss]: Probably these styles (and the following CSS rule too) should belong to the [`packages/launch/src/focused-launch/summart/style.scss`](https://github.com/Automattic/wp-calypso/blob/trunk/packages/launch/src/focused-launch/summary/style.scss) file?

Also, these styles may not be necessary (see https://github.com/Automattic/wp-calypso/blob/trunk/packages/launch/src/focused-launch/summary/style.scss#L197-L207)

File: packages/launch/src/hooks/use-cart.ts [hunk 27]
```diff
@@ -0,0 +1,40 @@
...
+import { useSelect, useDispatch } from '@wordpress/data';
+
+/**
+ * Internal dependencies
+ */
+import { LAUNCH_STORE, SITE_STORE, PLANS_STORE } from '../stores';
+import LaunchContext from '../context';
+import { getPlanProduct, getDomainProduct } from '../utils';
+
+export function useCart() {
```
Comment (ciampo) [inline packages/launch/src/hooks/use-cart.ts]:
```suggestion
export function useCart(): { goToCheckout: () => Promise< void > } {
```

File: packages/launch/src/utils.ts [hunk 28]
```diff
@@ -18,3 +20,21 @@ export const isDefaultSiteTitle = ( {
 	exact
 		? currentSiteTitle === DEFAULT_SITE_NAME
 		: new RegExp( DEFAULT_SITE_NAME, 'i' ).test( currentSiteTitle );
+
+export const getPlanProduct = ( plan: Plans.Plan, flow: string ) => ( {
```
Comment (ciampo) [inline packages/launch/src/utils.ts]:
```suggestion
type PlanProduct = {
	product_id: number;
	product_slug: string;
	extra: {
		source: string;
	};
};
export const getPlanProduct = ( plan: Plans.Plan, flow: string ): PlanProduct => ( {
```

File: packages/launch/src/utils.ts [hunk 29]
```diff
@@ -18,3 +20,21 @@ export const isDefaultSiteTitle = ( {
...
+	product_id: plan.productId,
+	product_slug: plan.storeSlug,
+	extra: {
+		source: flow,
+	},
+} );
+
+export const getDomainProduct = ( domain: DomainSuggestions.DomainSuggestion, flow: string ) => ( {
```
Comment (ciampo) [inline packages/launch/src/utils.ts]:
```suggestion
type DomainProduct = {
	meta: string;
	product_id: number;
	extra: {
		privacy_available: boolean;
		privacy: boolean;
		source: string;
	};
};
export const getDomainProduct = (
	domain: DomainSuggestions.DomainSuggestion,
	flow: string
): DomainProduct => ( {
```

File: client/blocks/editor-checkout-modal/index.tsx (hunk 6 above)
Comment (ciampo) [reply client/blocks/editor-checkout-modal/index.tsx]: > It's not straight forward to re-use the onboarding mixins since they bring also this z-index function (takes 1 argument) which is in conflict with the one used in this file (two arguments). So an ideal solution would involve refactoring onboarding package first to get out that import and explicitly add it only where needed.

Also, I opened https://github.com/Automattic/wp-calypso/issues/47805 to keep track of this task

Comment (ollierozdarz) [reply client/blocks/editor-checkout-modal/index.tsx]: Thanks @razvanpapadopol and @ciampo. I like the change to add the title for screen readers! (although I'd lose the word 'modal' personally). Great catch. 

I'd like to keep it to have no title for non-screen readers so the page is ultra focused on the task at hand (selecting and converting). When there are more 'things', there is more noise.

Comment (ciampo) [reply client/blocks/editor-checkout-modal/index.tsx]: Thank you @ollierozdarz ! I opened #47829 to track this task separately from this PR. This conversation can be marked as resolved

**Comment by tjcafferkey** [comment]
#### Focused Launch - Free Domain and Plan

Things of note:
* Sub-domain is pre-selected. (https://github.com/Automattic/wp-calypso/issues/47743)
* Clicking free plan did not enable the launch button even though sub-domain is selected
* Had to click paid domain, and then free sub-domain again to enable button
* It does however go straight to Success view as expected once it's enabled.

See video [here](https://www.loom.com/share/8721d2545ba64fcbbfe4982c3528ba26)

#### Focused Launch - Paid Domain and Plan - Complete Checkout

Things of note:
* After selecting a paid domain in the Domain Details view the Summary domains step was still disabled. Related to https://github.com/Automattic/wp-calypso/pull/47633 perhaps? 
* Selecting paid plan enabled Launch button with a paid domain selected.
* Clicking Launch button showed me the Success view, and then seconds later the checkout overlay appeared. Seemed weird?
* Wasn't given the upsell option?
* Completing checkout took me back to the editor but did not reveal Success view (This is noted as WIP above in the testing instructions)

See video [here](https://www.loom.com/share/ef321df8f8db4be58a90c5073aa980c7)

#### Focused Launch - Paid Domain and Plan - Closing Checkout Modal

Things of note:
* Clicking Launch button showed me the Success view, and then seconds later the checkout overlay appeared. Seemed weird?
* Closing the checkout modal revealed the Success view as expected.

See video [here](https://www.loom.com/share/9e52d9521bbe46699b32d47d8d97d37e)

#### Focused Launch - Paid Domain and Pre-Paid Plan

Things of note:
* The pre-paid plan was present, and disabled (as expected) but was above "Site title". Looks different to the design [here](https://github.com/Automattic/wp-calypso/issues/47734). Has this changed since?
* Clicking Launch button showed me the Success view, and then seconds later the checkout overlay appeared. Seemed weird?
* Closing the checkout modal revealed the Success view as expected.

See video [here](https://www.loom.com/share/622c2c933c26474f86bb756d921f019c)

#### Launch Flow Regression testing

* Worked as described even with the expected error raised here https://github.com/Automattic/wp-calypso/issues/47150

**Comment by razvanpapadopol** [comment]
> Clicking free plan did not enable the launch button even though sub-domain is selected
Had to click paid domain, and then free sub-domain again to enable button

This is 100% in scope of #47743

> Wasn’t given the upsell option?

Seems like a checkout bug or special case and not related to this flow. When testing only Personal/Premium plan purchase I always got redirected to thank you page.

> Completing checkout took me back to the editor but did not reveal Success view (This is noted as WIP above in the testing instructions)

Fixed separately in #47808 as agreed on Slack in order to unblock this PR.

> After selecting a paid domain in the Domain Details view the Summary domains step was still disabled. Related to #47633 perhaps?

Domain step wasn’t highlighted. It’s fixed in #47503 according to spec.

> The pre-paid plan was present, and disabled (as expected) but was above "Site title". Looks different to the design here. Has this changed since?

In that design there is no site title. The rule is to place purchased (disabled) items at the very top.

**Comment by tjcafferkey** [comment]
@razvanpapadopol thanks for going through the feedback. Was there anything around why the Success view is being shown briefly before the checkout?

Seems like everything that needs addressing is being taken care of and tracked in their own issues. Everything else seems fine for a user point of view except what I mentioned above. 👍🏻

@ciampo I know is delving into the code changes separately.

**Review by ciampo — COMMENTED** [review]
> @ciampo I know is delving into the code changes separately.

Code changes LGTM, all of my feedback has been addressed.

@tjcafferkey Feel free to approve once all of your feedback has been addressed and the necessary follow-up issues have been created

**Comment by razvanpapadopol** [comment]
> Clicking Launch button showed me the Success view, and then seconds later the checkout overlay appeared. Seemed weird?

This is caused by the async nature of updating cart and launch actions. We'll look into this more and come up with a better solution from UX perspective. Opened #47831 to track it.

**Review by tjcafferkey — APPROVED** [review]
@ciampo changes have been addressed and issues highlighted in the user flows are being tracked in separate issues. LGTM
