### PR TITLE
New Onboarding: alternative to fix flaky select free domain suggestion E2E test

### LINKED ISSUE #51857: New Onboarding: Flaky select free domain suggestion E2E test.
This E2E failure sometimes crops up because because selectFreeDomain() might be clicking on the free suggestion item too quickly before the list of domain suggestions are reloaded, causing the driver to target the element that has already been removed from DOM.

```
stale element reference: element is not attached to the page document
  (Session info: chrome=84.0.4147.135)
StaleElementReferenceError: stale element reference: element is not attached to the page document
(Session info: chrome=84.0.4147.135)
at Object.throwDecodedError (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/selenium-webdriver/lib/error.js:550:15)
at parseHttpResponse (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/selenium-webdriver/lib/http.js:565:13)
at Executor.execute (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/selenium-webdriver/lib/http.js:491:26)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async Driver.execute (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/selenium-webdriver/lib/webdriver.js:700:17)
at async Proxy.clickWhenClickable (lib/driver-helper.js:73:3)
at async DomainsPage.selectFreeDomain (lib/pages/gutenboarding/domains-page.js:37:3)
at async Context.<anonymous> (specs/wp-gutenboarding-spec.js:85:20)
```

### PR DESCRIPTION
**Pull request by razvanpapadopol**
**Changes proposed in this Pull Request**
The E2E failure stale element reference: element is not attached to the page document sometimes crops up because because selectFreeDomain() might be clicking on the free suggestion item too quickly before the list of domain suggestions are reloaded, causing the driver to target the element that has already been removed from DOM.

The solution is to add a delay bigger than the debounce interval when getting domain suggestions.

**Testing instructions**
Since this is intermittent, just rerun the E2E desktop on TeamCity and see if the stale element reference error still persist on the 'Can see Domains Page and pick a free domain and continue' step.

Related to https://github.com/Automattic/wp-calypso/pull/51858#pullrequestreview-635335624
Fixes #51857.

### CODE REVIEW

**Comment by yansern** [comment]
I like where this is heading.

File: test/e2e/lib/pages/gutenboarding/domains-page.js [hunk 1]
```diff
@@ -21,23 +21,39 @@ export default class DomainsPage extends AsyncBaseContainer {
...
+		await driverHelper.setWhenSettable( this.driver, searchFieldSelector, query );
+		// After typing the new query value, wait for domain suggestions to reload.
+		// The sleep value should be higher than the DOMAIN_SEARCH_DEBOUNCE_INTERVAL defined in domain-picker.
+		//https://github.com/Automattic/wp-calypso/blob/trunk/packages/domain-picker/src/constants.ts#L18
+		await this.driver.sleep( 500 );
+	}
+
+	async waitForDomainSuggestionsToLoad() {
+		const placeholderSelector = By.css( '.domain-picker__suggestion-item.placeholder' );
+		await driverHelper.waitTillNotPresent( this.driver, placeholderSelector );
```
Comment (yansern) [inline test/e2e/lib/pages/gutenboarding/domains-page.js:35]: `waitTillNotPresent` can be a point of flakiness though, in this example here, https://github.com/Automattic/wp-calypso/pull/51863/files#diff-b7f8735b885b065dc18c161fbf8de3c5bfecafd5fd04319842a8eea5f5c32180L77, the spinner disappears too quickly so it got stuck there.

Comment (yansern) [reply test/e2e/lib/pages/gutenboarding/domains-page.js:35]: Oh yeah right, `waitTillNotPresent` will just slide through if the element is not present. :) Okay, let's see what the E2E results show overtime.

**Review by yansern — APPROVED** [review]
Alright! All good.
