### PR TITLE
Media: Fix photon URLs in media library

### LINKED ISSUE #27410: Photon (iX.wp.com) should not be used for *.files.wordpress.com URLs
#### Steps to reproduce
1. Starting at URL: https://wordpress.com
2. My Sites (pick any public WordPress.com site)
3. Media
4.  Right click -> Copy image address on any thumbnail image

#### What I expected

To see the resized image served directly from WordPress.com

https://barry.files.wordpress.com/2015/11/img_3008.jpg?w=450

#### What happened instead

WordPress.com images being redirected through Photon: 

https://i2.wp.com/barry.files.wordpress.com/2015/11/img_3008.jpg?ssl=1&w=450

#### Browser / OS version

All

#### Screenshot / Video

None

#### Context / Source

We'd also love to know how you found the bug:  Customer complaint.

### PR DESCRIPTION
**Pull request by alisterscott**
This updates the thumbnails in the media library to use the WordPress.com URLs instead of Photon urls.

Fixes #27410 

**Testing Instructions**

1. Visit https://calypso.live/?branch=try/fix-photon-urls-media-library
2. Choose a site and Media
3. Make sure media src URLs are files.wordpress.com ones (not photon like iX.wp.com)
4. Make sure this works for WordPress.com simple public, private, Atomic and Jetpack sites with Photon disabled and enabled

### CODE REVIEW

**Comment by alisterscott** [comment]
@ramonjd any chance of a review on this?

File: client/my-sites/media-library/content.jsx [hunk 1]
```diff
@@ -24,7 +24,6 @@ import MediaLibrarySelectedData from 'components/data/media-library-selected-dat
 import MediaActions from 'lib/media/actions';
 import {
 	ValidationErrors as MediaValidationErrors,
-	MEDIA_IMAGE_PHOTON,
```
Comment (ramonjd) [inline client/my-sites/media-library/content.jsx]: If we're no longer using this constant for images, perhaps it's a good chance to cull it. For example, the [default thumbnailType](https://github.com/Automattic/wp-calypso/blob/047412b/client/my-sites/media-library/list-item-image.jsx#L30) for `<ListItemImage />` is still `MEDIA_IMAGE_PHOTON`. 

I'm not sure however how photon relates to videos, but it looks like we're passing down `thumbnailType` to all `<ListItem />` [children](https://github.com/Automattic/wp-calypso/blob/047412b/client/my-sites/media-library/list.jsx#L188), so on the face of it, it appears we can change the default type in all child components. 

It might be worth doing should, for any reason, we want to prevent `MEDIA_IMAGE_PHOTON` from being the default. For example, if the child components don't receive a valid `props.thumbnailType`.

If you do decide to change the default type, then we can also get rid of the corresponding tests.

**Review by ramonjd — APPROVED** [review]
LGTM

Checked in various test sites, and media files are being served from `*files.wordpress.com`.

Just a question related to whether we need `MEDIA_IMAGE_PHOTON` at all now. Might be useful to get rid of it/provide an alternative default in child components.
