### PR TITLE
Make the post search placeholder be "Search [POST_TYPE]..."

### LINKED ISSUE #36147: Posts, Testimonials and Portfolio Projects: Change search placeholder text to reflect what is being searched for
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/posts/[site]
2. Click the search icon
3. Notice that you just see a generic "Search..." placeholder text.

A similar thing happens at https://wordpress.com/types/jetpack-testimonial/[site] and https://wordpress.com/types/jetpack-portfolio/[site].

In combination with https://github.com/Automattic/wp-calypso/pull/36109, @lcollette proposed that this should be "Search Posts..." instead (and the equivalent for the other content types, i.e. "Search Testimonials..." and "Search Projects...") so the user is more aware of what they are searching.

Note that we want to do the same for Pages also, but we'll handle that separately as part of https://github.com/Automattic/wp-calypso/issues/36121 since it's a separate area of the code, and also because for pages it already says things like "Search Published..." which we'll need to fix as part of that issue (since the search won't be limited to a particular status anymore).

### PR DESCRIPTION
**Pull request by DanReyLop**
Fixes #36147

Updated the search bar placeholder text to be context-dependent:
- In the "Posts" screen: `Search Posts...`
- In the "Pages" screen: `Search Published/Drafts/etc...` (unchanged, will be updated after https://github.com/Automattic/wp-calypso/issues/36121)
- In the "Testimonials" screen (Testimonials post type needs to be enabled in Jetpack): `Search Testimonials...` 
- In the "Portfolio" screen (Portfolio post type needs to be enabled in Jetpack): `Search Projects...`

Example:
Screenshot 2019-09-15 at 11 28 04

### CODE REVIEW

File: client/my-sites/post-type-filter/index.jsx [hunk 1]
```diff
@@ -241,6 +248,7 @@ export default flow(
 
 			return {
 				...props,
+				typeLabel: get( getPostType( state, siteId, query.type ), 'labels.name' ),
```
Comment (noahtallen) [inline client/my-sites/post-type-filter/index.jsx]: Should we return a default here? Or at least, handle the case where `labels.name` may not exist?

Comment (DanReyLop) [reply client/my-sites/post-type-filter/index.jsx]: If `labels.name` does not exist, the placeholder will be `Search ...` (notice the whitespace), which is OK IMHO.

Comment (noahtallen) [reply client/my-sites/post-type-filter/index.jsx]: sounds good!

**Comment by noahtallen** [comment]
Tests timed out; rerunning workflow

File: client/my-sites/post-type-filter/index.jsx (hunk 1 above)
Comment (DavidRothstein) [reply client/my-sites/post-type-filter/index.jsx]: Yeah, not 100% ideal, but good enough I think.
