### PR TITLE
JP Onboarding: Ensure we're fetching JPO credentials when logged-out

### LINKED ISSUE #23407: Jetpack Onboarding: Site title and description not prefilled when user is logged out
> Site title & tagline did not get prefilled when connecting while logged out in WP.com. When a user is logged into WP.com – Site title & tagline prefilled with values from site.

Reported in p1HpG7-4WU-p2 #comment-25051 by @brbrr

### LINKED ISSUE #23435: Jetpack Onboarding: Losing onboarding credentials when logged out and redirected to JPC flow
To reproduce:

1. Start the flow here: http://yourgroovydomain.com/wp-admin/admin.php?page=jetpack&action=onboard
1. Enter a site title.
1. Select "Personal" or "Business" for the site type.
1. Select "Recent news" or "Static page" for the homepage.
1. Select "Add a contact form" to be taken to the Jetpack connection flow. I was logged out, so this brought me to the account signup form.
1. Select the browser's back button.

Going back took me to this blank page with no console errors.

I used my browser's back button to go all the way back through the flow, and every page was blank. I had to re-enter the initial link to restart the flow.

---

Reported in p1HpG7-4WU-p2 #comment-25071 by @rachelmcr

### PR DESCRIPTION
**Pull request by ockham**
The reason we were seeing #23435 is that we rely on an `isRequestingSite()` check to tell whether we've finished fetching site details, which will tell us whether the site is connected, which we need in turn to conditionally send JPO auth credentials.
However, if we're logged out, we cannot `<QuerySites allSites />`, since the concept of "all of a user's sites" doesn't make sense if there is no user. We also cannot `<QuerySites siteId={ siteId } />` prior to having obtained the `siteId` through JPO -- a Catch-22 situation.
Fortunately, querying by `siteSlug` (which we have readily available from the route) works, since it's supported by underlying actions.

(The above explanation replicated in a code comment for posterity.)

Fixes #23435.
Fixes #23407.

I believe it's the more "correct" fix than #23437, and should fix issues @rachelmcr found with #23437:

>> Test as logged in and not connected and verify there are no behavioral changes.
>
> I saw the issue reported in #23407 (site title/tagline not prefilled) even while logged in this time. 
>> Test as logged in and connected and verify there are no behavioral changes.
>
> Again, I saw the issue reported in #23407 (site title/tagline not prefilled) even while logged in. 

### Testing instructions (stolen from @tyxla's #23437 😁):
* Log out from WP.com (or open an incognito browser window)
* Start the flow here: http://yourgroovydomain.com/wp-admin/admin.php?page=jetpack&action=onboard&calypso_env=development
* Enter a site title.
* Select "Personal" or "Business" for the site type.
* Select "Recent news" or "Static page" for the homepage.
* Select "Add a contact form" to be taken to the Jetpack connection flow. I was logged out, so this brought me to the account signup form.
* Select the browser's back button.
* Verify you're shortly being redirected to the Jetpack site to retrieve credentials, and after that you land in the first step of the flow (site title).
* Test as logged in and not connected and verify there are no behavioral changes.
* Test as logged in and connected and verify there are no behavioral changes.
* Test all cases with a clean Redux state.

### CODE REVIEW

File: client/jetpack-onboarding/main.jsx [hunk 1]
```diff
@@ -141,6 +142,16 @@ class JetpackOnboardingMain extends React.PureComponent {
...
+				{ /* It is important to use `<QuerySites siteId={ siteSlug } />` here, however wrong that seems.
+				   * The reason is that we rely on an `isRequestingSite()` check to tell whether we've
+				   * finished fetching site details, which will tell us whether the site is connected,
+				   * which we need in turn to conditionally send JPO auth credentials (see below).
+				   * However, if we're logged out, we cannot `<QuerySites allSites />`,
+				   * since the concept of "all of a user's sites" doesn't make sense if there is no user.
+				   * We also cannot `<QuerySites siteId={ siteId } />` prior to having obtained the `siteId`
+				   * through JPO -- a Catch-22 situation.
+				   * Fortunately, querying by `siteSlug` works, since it's supported by underlying actions. */ }
+				<QuerySites siteId={ siteSlug } />
```
Comment (tyxla) [inline client/jetpack-onboarding/main.jsx]: We'll need to fix the `siteId` propType to accept a slug.

Comment (tyxla) [inline client/jetpack-onboarding/main.jsx]: The downside with this is that we'll always get a 404 for unconnected sites:

File: client/jetpack-onboarding/main.jsx [hunk 2]
```diff
@@ -188,8 +199,11 @@ export default connect(
 		const settings = getJetpackOnboardingSettings( state, siteId );
 		const isBusiness = get( settings, 'siteType' ) === 'business';
 
+		// We really want `isRequestingSite( state, siteSlug )` (not `siteId`).
+		// For the rationale, see the comment right above the `<QuerySites />` component
+		// further up in this file.
 		const isRequestingWhetherConnected =
-			isRequestingSite( state, siteId ) || isRequestingSites( state );
+			isRequestingSite( state, siteSlug ) || isRequestingSites( state );
```
Comment (tyxla) [inline client/jetpack-onboarding/main.jsx]: According to its JSdoc `isRequestingSite` accepts only a numerical `siteId`. The endpoint supports a slug, so it probably makes sense to update it in the selector docs too, as it's a little weird to use a non-documented case like this.

**Comment by ockham** [comment]
> Kind of hacky, but I like it 😉 Seems to work great and resolves both #23407 and #23435.

TBH, that was the cleanest I could come up with, and I thought it was conceptually fine for the most part. The Catch-22 isn't trivial to break out of here since initially we know nothing except for the site slug. The only other way to fix this that I can see would be to always send `jpoAuth`, but that breaks another set of constraints for connected sites, doesn't it?

File: client/jetpack-onboarding/main.jsx (hunk 1 above)
Comment (ockham) [reply client/jetpack-onboarding/main.jsx]: Good spot 🙁 

Not sure we can do a lot about this since it's part of our "bootstrapping" where we're trying to find out whether the site is connected -- so arguably, this is relevant information, since we find out that it isn't...

**Comment by tyxla** [comment]
Yeah, I agree. Would be a little better if we knew all the constraints initially, but 🤷‍♂️ 

You have my green light for this one. Maybe we could wait for some more thorough testing from @rachelmcr before 🚢

**Comment by ockham** [comment]
BTW this is somewhat related to https://github.com/Automattic/wp-calypso/pull/22948#discussion_r171889976

**Comment by rachelmcr** [comment]
>Maybe we could wait for some more thorough testing

Testing this now! I'll add my review as soon as I'm done.

**Comment by tyxla** [comment]
Thanks so much @rachelmcr!

Going to close #23408 and #23437 in favor of this one.

**Comment by ockham** [comment]
Thanks a lot @tyxla and @rachelmcr! Going to merge.

File: client/jetpack-onboarding/main.jsx (hunk 1 above)
Comment (ockham) [reply client/jetpack-onboarding/main.jsx]: D'oh, merged, but forgot to fix the propType and selector JSDoc. Will spin up a PR to do that...

Comment (ockham) [reply client/jetpack-onboarding/main.jsx]: #23526

File: client/jetpack-onboarding/main.jsx (hunk 2 above)
Comment (ockham) [reply client/jetpack-onboarding/main.jsx]: #23526
