### PR TITLE
Fix/plans screaming case

### LINKED ISSUE #7502: Refactor plans/constants variable names to screaming snake case
As suggested by @gwwar [here](https://github.com/Automattic/wp-calypso/pull/7091#discussion_r74982748), let's refactor:

- `allPaidPlans` to `ALL_WPCOM_PAID_PLANS`;
- `allWpcomPlans` to `ALL_WPCOM_PLANS`;
- `plansList` to `PLANS_LIST`;
- `featuresList` to `FEATURES_LIST`

in `lib/plans/constants` and everywhere where needed.

### PR DESCRIPTION
**Pull request by artpi**
Resolves #7502

- Refactors  plansList to PLANS_LIST; featuresList to FEATURES_LIST
- Removes allPaidPlans and allWpcomPlans entirely
- changes plan/feature detection to be solely contained within plan object, not scattered all over
- Uses getPlan getter whenever applicable instead of using planFeatures[ feature ]

No functional changes

## Testing
- Make sure /plans work properly
- Make sure that NUX works properly
- make sure nudges appear properly
-- nudge in /design/:site all < premium
-- nudge in settings/analytics/:site for all < business
-- nudge in stats/insights/:site for all < personal

### CODE REVIEW

File: client/lib/plans/constants.js [hunk 1]
```diff
@@ -72,6 +72,7 @@ export const FEATURE_MALWARE_SCANNING_DAILY_AND_ON_DEMAND = 'malware-scanning-da
 export const FEATURE_ONE_CLICK_THREAT_RESOLUTION = 'one-click-threat-resolution';
 export const FEATURE_POLLS_PRO = 'polls-pro';
 
+// DO NOT import. Use `getPlan` from `lib/plans` instead.
 export const plansList = {
```
Comment (lamosty) [inline client/lib/plans/constants.js]: Maybe move the `getPlan` fn to this file so `plansList` does't have to be exported?

File: client/lib/plans/index.js [hunk 2]
```diff
@@ -75,19 +75,19 @@ export function getSitePlanSlug( siteID ) {
 
 export function canUpgradeToPlan( planKey, site = sitesList.getSelectedSite() ) {
 	const plan = get( site, [ 'plan', 'expired' ], false ) ? PLAN_FREE : get( site, [ 'plan', 'product_slug' ], PLAN_FREE );
-	return get( plansList, [ planKey, 'availableFor' ], () => false )( plan );
+	return get( PLANS_LIST, [ planKey, 'availableFor' ], () => false )( plan );
```
Comment (lamosty) [inline client/lib/plans/index.js]: We should use the `getPlan` fn in all these places probably. :)

**Comment by lamosty** [comment]
Looking fine, great work!

Could you squash some commits please? E.g. in one commit, you rename a variable and in another one you remove the variable completely.

In a7261a7aefafc9b2335c1701a5a636c15052e141, you remove the `plans` prop on `FEATURES_LIST`. Do you know whether this is safe and not needed? What was the original intention for adding it?

**Comment by artpi** [comment]
> Could you squash some commits please? E.g. in one commit, you rename a variable and in another one you remove the variable completely.

No, I don't do that anymore. I always use Github Squash'N'Merge. With that, there is no point in squashing PRs

> Do you know whether this is safe and not needed? What was the original intention for adding it?

It was used in `planHasFeature`, but it was working incorrect, so this PR actually solves a bug ( like  p3fqKv-3Kj-p2 )

File: client/lib/plans/index.js (hunk 2 above)
Comment (artpi) [inline client/lib/plans/index.js]: Ah yeah, we could, working on it

**Comment by lamosty** [comment]
> No, I don't do that anymore. I always use Github Squash'N'Merge. With that, there is no point in squashing PRs

I see. On the other hand, after squash'n'merge, the commit titles/descriptions will still be included in the final commit description. What if somebody from the future wants to debug an issue, arrives at such a commit and sees all these smaller commits that interact with each other.

I think they should read like a book. I started at point A, continued to point B and arrived at point C.

> It was used in planHasFeature, but it was working incorrect, so this PR actually solves a bug where nudge is shown but it shouldn't ( like p3fqKv-3Kj-p2 )

Ah, awesome! Maybe we could include a short description on the commit saying the same as you wrote above? :)

**Comment by artpi** [comment]
> I think they should read like a book. I started at point A, continued to point B and arrived at point C

Well that is PRECISELY what you loose in case of squashing manually, thats why I dont do that! :)

>  What if somebody from the future wants to debug an issue, arrives at such a commit and sees all these smaller commits that interact with each other.

Sorry, I dont quite get it... You can always open the PR and see either work rquashed OR see individual commits. 
When you squash manually - you can't

**Comment by lamosty** [comment]
> Sorry, I dont quite get it... You can always open the PR and see either work rquashed OR see individual commits. 
> When you squash manually - you can't

Okay, good points!

In that case, I think this PR is ready for merging. :ship:
