### PR TITLE
Store: Fix Console Warnings

### LINKED ISSUE #20418: Store: Console warning on products page
I'm seeing two new warnings when going to `Products > Add New`:

Both warnings are

> Warning: Expected `onClick` listener to be a function, instead got `false`.

screen shot 2017-12-01 at 9 14 39 am

Things still seem to work but we should fix the warnings.

### PR DESCRIPTION
**Pull request by timmyc**
Fixes #20418

Since the React upgrade, there have been some warnings thrown in the console on the Store Products pages - this branch seeks to fix that.

__To Test__
- Visit a Product Page for an existing product
- Very if no warnings are thrown in the console
- Edit the product slug, and click Update. Verify items are updated/saved as expected.

### CODE REVIEW

File: client/extensions/woocommerce/app/products/product-header.js [hunk 1]
```diff
@@ -37,7 +37,7 @@ function renderViewButton( product, translate ) {
 function renderTrashButton( onTrash, product, isBusy, translate ) {
 	return (
 		onTrash && (
-			<Button borderless scary onClick={ onTrash }>
+			<Button borderless scary onClick={ onTrash ? onTrash : undefined }>
```
Comment (budzanowski) [inline client/extensions/woocommerce/app/products/product-header.js]: Maybe shorter:
`onTrash || undefined`

**Comment by budzanowski** [comment]
Added one suggestion. But otherwise good to go.

File: client/extensions/woocommerce/app/products/product-header.js (hunk 1 above)
Comment (budzanowski) [reply client/extensions/woocommerce/app/products/product-header.js]: The same in other places.
