### PR TITLE
Send users to a different signup flow based on a query string parameter

### LINKED ISSUE #2019: Signup: Likes from logged out users should lead to user only signup
Right now clicking on the Likes, while not logged in leads you to sign in.  If you don't have an account, clicking Register takes you to the /start signup, but it should take you to the signup with least friction: /start/account

To reproduce:
1) While signed out, click a like button
2) Click Register
3) You're prompted to pick a theme, instead of just create a quick user

Ideally, this would also mark the post liked once signup is filled out.

### PR DESCRIPTION
**Pull request by scruffian**
This pull request fixes #2019 by sending users to a different signup flow based on the value of a `signup_flow` query string parameter.
  
This has also required some changes to the way we store data in localStorage, which won't work server side.
  
#### Testing instructions
  
1. Run `git checkout fix/2019` and start your server
2. Open the [`Login` page](http://calypso.localhost:3000/log-in)
3. Try adding various different parameters to the URL for different signup flows:
- ?signup_flow=account
- ?signup_flow=desktop
- ?signup_flow=asdfghdsa
4. Check that when the flow exists, the "Signup" button in the header goes to the correct flow, and when it doesn't it just goes to `/start`
  
#### Reviews
- [x] Code
- [x] Product

### CODE REVIEW

**Comment by scruffian** [comment]
If we move productsList to redux, that should be a different PR imo.

File: client/layout/masterbar/logged-out.jsx [hunk 1]
```diff
@@ -75,6 +76,7 @@ class MasterbarLoggedOut extends PureComponent {
 
 	renderSignupItem() {
 		const { currentQuery, currentRoute, sectionName, translate } = this.props;
+		const signupFlow = get( currentQuery, 'signup_flow' );
```
Comment (stephanethomas) [inline client/layout/masterbar/logged-out.jsx]: Super minor but we could move this declaration closer to the code that actually uses it.

File: client/signup/config/flows.js [hunk 2]
```diff
@@ -457,6 +457,10 @@ const Flows = {
 		return flows;
 	},
 
+	isValidFlow( flowName ) {
+		return Boolean( Flows.getFlows()[ flowName ] );
```
Comment (stephanethomas) [inline client/signup/config/flows.js]: We could use [`include()`](https://lodash.com/docs#includes) from Lodash instead here - which by the way is already imported in this file.

**Comment by scruffian** [comment]
> Could you explain why those changes were required? store already uses localStorage under the hood.

@stephanethomas, the problem is that `store` doesn't check whether `localStorage` is supported. When you try to use it on the server it just causes an error.

File: client/signup/config/flows.js (hunk 2 above)
Comment (scruffian) [reply client/signup/config/flows.js]: `includes` looks at the value of the elements of the array, not at the existence of the key. Personally I'd rather use native JS than a library when it's only one simple line.

File: client/login/controller.js [hunk 3]
```diff
@@ -24,7 +24,7 @@ import { getCurrentUser, getCurrentUserLocale } from 'state/current-user/selecto
 const enhanceContextWithLogin = context => {
 	const { path, params: { flow, isJetpack, socialService, twoFactorAuthType } } = context;
 
-	context.cacheQueryKeys = [ 'client_id' ];
+	context.cacheQueryKeys = [ 'client_id', 'signup_flow' ];
```
Comment (Tug) [inline client/login/controller.js]: FYI, This change is conflicting with https://github.com/Automattic/wp-calypso/pull/22614

Comment (scruffian) [reply client/login/controller.js]: 👍

Comment (Tug) [reply client/login/controller.js]: Thinking about it, it should not be a blocker.

**Comment by Tug** [comment]
LGTM 👍

**Comment by scruffian** [comment]
One option is to not validate the values in the query string. I don't see a particular issue with that. If someone modifies the query string maliciously the worst that could happen is that the user gets redirected to the default flow. What do you think @jsnajdr ?

**Comment by jsnajdr** [comment]
@scruffian Yes, skipping the validation looks like a good option to me. We can do some really basic validation, i.e., the `signup_flow` var should contain a `/` character.

The `/start/:flowName` route handler already validates the flow name and redirects to the default value if not valid (in the `getFlowName` function). So the behavior of `/start` and `/start/invalid-flow` should already be identical.
