### PR TITLE
Editor: Learn more link of Page Break block

### LINKED ISSUE #75758: Page Break Block - Learn More link is incorrect
### Quick summary

The Page Break block has a block description with a Learn More Link, but the link is to the wrong page.

Current link: https://wordpress.com/support/site-editing/theme-blocks/post-content-block/
Correct link: https://wordpress.com/support/wordpress-editor/blocks/page-break-block/

image

### Steps to reproduce

1. Open the editor
2. Insert a page break block
3. Open the sidebar settings
4. Click 'Learn more'

### What you expected to happen

To see this page: https://wordpress.com/support/wordpress-editor/blocks/page-break-block/

### What actually happened

I saw this page: https://wordpress.com/support/site-editing/theme-blocks/post-content-block/

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by escapemanuele**
## What

The Page Break block has a block description with a Learn More Link, but the link is to the wrong page.
Current link: https://wordpress.com/support/site-editing/theme-blocks/post-content-block/
Correct link: https://wordpress.com/support/wordpress-editor/blocks/page-break-block/
image

## Testing

1. Checkout the branch
2. `cd apps/editing-toolkit` and `yarn dev --sync`
3. Open the editor
4. Insert a page break block
5. Open the sidebar settings
6. Click 'Learn more', it should bring you to the correct url.

Fixes https://github.com/Automattic/wp-calypso/issues/75758

### CODE REVIEW

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-description-links/src/index.tsx [hunk 1]
```diff
@@ -56,13 +58,16 @@ const addBlockSupportLinks = (
...
+	/**
+	 * Some elements are children, but have their own url for Learn More, and we want to show those.
+	 */
+	settings.description = createLocalizedDescriptionWithLearnMore(
+		String( settings.title ),
+		settings.description,
+		childrenBlockLinksWithDifferentUrl[ name ]
+			? childrenBlockLinksWithDifferentUrl[ name ]
+			: blockLinks[ blockName ]
+	);
```
Comment (alshakero) [inline apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-description-links/src/index.tsx]: This will overwrite description with null when `childrenBlockLinksWithDifferentUrl` and `blockLinks` don't have this block.

**Review by alshakero — CHANGES_REQUESTED** [review]

File: apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-description-links/src/index.tsx (hunk 1 above)
Comment (escapemanuele) [reply apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-description-links/src/index.tsx]: Damn, I changed it at last just to have less code. Sent a fix for this 👍

**Review by alshakero — APPROVED** [review]
Tested and works great.
