### PR TITLE
Fix/fse template content parsing

### LINKED ISSUE #34243: Full Site Editing: Post Content Disappears on Second Edit
On subsequent page editor, post_content fails to load in the editor:

To reproduce:
- Install the FSE plugin, and activate it
- Edit a page
- Note that the header and footer template appears, within the page editor.
- Make some post content changes and save
- Verify that the published view reflects this.
- Edit the page again (with a refresh). The post_content is missing in the block editor.

### PR DESCRIPTION
**Pull request by glendaviesnz**
#### Changes proposed in this Pull Request

* Modify the search and replace syntax to correctly insert post content into template and also apply the post content block attributes correctly. The previous fix #34289 was not applying these attributes to the inserted content block, and was also fragile if the attributes changed.

#### Testing instructions
- Check out branch and Install the FSE plugin, and activate it on local gutenberg dev
- Edit a page
- Note that the header and footer template appears, within the page editor.
- Note that the post content also appears between the header and footer.
- Edit the page again (with a refresh) and check that the post content still appears
Screen Shot 2019-06-26 at 12 14 59 PM

Fixes  #34243

### CODE REVIEW

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php [hunk 1]
```diff
@@ -467,13 +467,37 @@ public function merge_template_and_post( $post ) {
...
+		// Bail if the post has no template id assigned.
 		if ( ! $template->get_template_id() ) {
 			return;
 		}
 
-		$wrapped_post_content = sprintf( '<!-- wp:a8c/post-content -->%s<!-- /wp:a8c/post-content -->', $post->post_content );
-		$post->post_content   = str_replace( '<!-- wp:a8c/post-content {"align":"full"} /-->', $wrapped_post_content, $template->get_template_content() );
+		$parser           = new WP_Block_Parser();
+		$template_content = $template->get_template_content();
+		$template_blocks  = $parser->parse( $template_content );
```
Comment (gwwar) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php]: If this is expensive it looks like we can check before parsing if we have a related block.

`has_blocks` https://core.trac.wordpress.org/browser/tags/5.2/src/wp-includes/blocks.php#L81 (this does a simple string pos check)

Comment (gwwar) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php]: 🤔 should we be calling parse_blocks https://core.trac.wordpress.org/browser/tags/5.2/src/wp-includes/blocks.php#L286 

The main difference is that this allows a hookpoint to change the parser implementation.

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php [hunk 2]
```diff
@@ -467,13 +467,37 @@ public function merge_template_and_post( $post ) {
 
 		$template = new A8C_WP_Template( $post->ID );
 
-		// Bail if the post has no tempalte id assigned.
+		// Bail if the post has no template id assigned.
```
Comment (gwwar) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php]: Nice catch!

**Comment by gwwar** [comment]
@glendaviesnz codewise this looks pretty close. 

I tried manually testing here and it appears that we're missing content in editing/published view. I wonder if it might be a bit safer to do something closer to do_blocks once we've parsed content here. The difference being for any other block we return identity, and for the post_content block we replace with post content. (similar to a dynamic block callback).

A unit test might help here, but non-blocking.

**Comment by glendaviesnz** [comment]
> I tried manually testing here and it appears that we're missing content in editing/published view.

hmm, ok that is strange, broken for me locally too now after pulling latest master from gutenberg - was sure it worked this morning before I pushed it. Will try and work out what has gone wrong.

**Comment by mmtr** [comment]
> I wonder if it might be a bit safer to do something closer to do_blocks once we've parsed content here. The difference being for any other block we return identity, and for the post_content block we replace with post content. (similar to a dynamic block callback).

Given that the problem with the post content not being saved turned out to be a regression I introduced in `save` changes of the `a8c/post-content` block added on https://github.com/Automattic/wp-calypso/pull/34214, I think we can keep relying on the default core rendering (a `do_blocks` call triggered by the `the_content` filter).

I feel this safer since we don't change how the post content is rendered and we delegate the full responsibility to the default core behavior.

In any case, we can open a follow-up PR later exploring an explicit `do_blocks` approach after parsing the content if we identify that's the direction we should head to.
