### PR TITLE
Reader full post: use feed URL for follow button in author compact profile

### LINKED ISSUE #8097: Reader: If Followed site is a feed/non-wpcom site, Follow button isn't green
#### Steps to reproduce:
1. In Manage Following, add a site feed or non-wpcom site
2. Go back to your Following stream
3. Check Follow button and notice this site's Follow button hasn't changed to "Following"

This site, for example, I'm already following but button still says "Follow":
screenshot 2016-09-23 15 09 50

/cc @blowery

### PR DESCRIPTION
**Pull request by bluefuton**
Fixes #8097.

The current full post view uses feed URL to power the follow button, but until now the refreshed full post view used site URL instead. These don't always match, so the correct following state wasn't always shown.

### To test

1. Follow http://calypso.localhost:3000/read/feeds/8878742 from Manage Following
2. Visit a post and ensure that the correct following state is shown in the sidebar (e.g. http://calypso.localhost:3000/read/feeds/8878742/posts/1123381012).

screen shot 2016-09-29 at 14 20 42 copy

### CODE REVIEW

File: client/blocks/reader-full-post/index.jsx [hunk 1]
```diff
@@ -189,7 +189,7 @@ export class FullPostView extends React.Component {
 								siteIcon={ get( site, 'icon.img' ) }
 								feedIcon={ get( feed, 'image' ) }
 								siteName={ post.site_name }
-								siteUrl= { post.site_URL }
+								feedUrl= { get( feed, 'feed_URL' ) }
```
Comment (blowery) [inline client/blocks/reader-full-post/index.jsx]: This should fall back to the site url, as not all blogs have an associated feed.

Comment (bluefuton) [inline client/blocks/reader-full-post/index.jsx]: Right you are.

@blowery noted in Slack that there are two types of sites that may have a blog ID but not a feed ID:
- Jetpack sites
- wpcom sites with no subscriptions (there aren't many, but they certainly exist)

Comment (bluefuton) [inline client/blocks/reader-full-post/index.jsx]: Fixed in 875c90c.

**Comment by blowery** [comment]
Tests passed.
