### PR TITLE
Login to mapped domain when added as a user

### LINKED ISSUE #52763: WPCOM logged in users don't get cookies set when added as a user for a site
### Steps to reproduce the behavior

1. Sign in to any WPCOM account on a browser that has 3rd party cookies _enabled_. Let's refer to this account as "user A". Keep this browser window open.
2. On a different browser or incognito window, sign in to a WPCOM account that has a .blog subdomain(say example.food.blog), navigate to `https://wordpress.com/people/team/{SITE_SLUG}` and add "user A" to this site.
2. Check the email inbox for "user A", and navigate to the invite link in the same browser that has "user A" signed in.
3. Now, navigate to example.food.blog in the browser that has "user A" signed in.

### What I expected

To be logged in to example.food.blog

### What happened instead

I got the logged out view for the site. Reloading the page rendered the logged in view, likely because the async remote login scripts created the auth cookies.

### NOTE

This bug is seen when _allowing_ third party cookies. In other words, Chrome's "Block third party cookies" settings option is _disabled_.

Screenshot 2021-05-12 at 11 33 32 AM

### PR DESCRIPTION
**Pull request by niranjan-uma-shankar**
#### Changes proposed in this Pull Request

When a user logged into WP.com is added as a user to another site(with a mapped domain), this PR and the associated patch(code-D61790) will login the user to the mapped domain site.

When the user is added to a site, they will receive an email to accept invitation. Following the invite link will bounce them through the r-login redirects and setup the login cookies for the mapped domain site.

**What is the effect of this change?**

When a user logged into WPCOM accepts invitation to be added as a user on another site with a mapped domain, their first visit to that site will be a logged in experience. 

**NOTE**

This PR will not login the user to their mapped domain if they are added as a "Viewer" or "Follower". This is because, currently `logmein()` only works for sites of the user, and "viwer/follower" roles won't show up as a site of the user. We will have to handle this case separately when scope of `logmein()` expands to any WP.com site.

#### Testing instructions

Apply code-D61790.

* On a site with a mapped domain, click on "Invite" button in https://wordpress.com/people/team/ and add a user with role "Editor" role.
* In a different browser or incognito window, disable 3rd party cookies and login to calypso.localhost:3000. Then navigate to the accept invitation page for the user you just added by following the link in the email invitation sent to this user. 
* When you are on the accept invitation page, change the wordpress.com host name in the browser with calypso.localhost:3000 and reload the page with the new URL, so that this branch's changes are applied.
* In a new tab, navigate to this new site and confirm that you are logged out for this domain.
* Ensure that you're sandboxed to https://r-login.wordpress.com and the new site for which the user got the invitation link.
* Click on the Accept CTA and verify that you are taken to the /posts page in WP.com. Observe the link redirects and confirm that you were taken through logmein redirect for the new site. 
* Visit the new site and confirm that you get the logged in experience.
* Repeat above steps for other roles - "Administrator", "Author" and "Contributor"
* Test on Chrome, Firefox, and Safari. 

**Other scenarios to test**

* Repeat all steps for a site on a *.wordpress.com subdomain, and confirm that you are _not_ taken through logmein redirect after clicking on the Accept CTA in the invitation page. This is because `logmein` is not required for wordpress.com subdomains.
* Repeat all the steps for an atomic site and confirm that you are not taken through logmein redirect after clicking on the Accept CTA in the invitation page.

Fixes https://github.com/Automattic/wp-calypso/issues/52763

### CODE REVIEW

**Comment by josephscott** [comment]
Where is the code that handles the `r_login_redirect` reference?

**Comment by lsl** [comment]
> Where is the code that handles the `r_login_redirect` reference?

D61790-code

**Comment by josephscott** [comment]
Thank you, not sure how I kept missing that in the original comment.

**Comment by lsl** [comment]
Do you think its better to wait for something like this https://github.com/Automattic/wp-calypso/pull/52909/files#diff-4edb20e49584b60790a9a754c4a145b0687e98bc8903f7cb1dde61db0d7a1e16R12-R27? We need to ensure only certain site types get this treatment.

I'm also wondering if it would be better to push this functionality into the navigate lib and catch all navigation's: https://github.com/Automattic/wp-calypso/blob/trunk/client/lib/navigate/index.ts#L16

`navigate` is what client/my-sites/invites/controller.js eventually calls with this `getRedirectAfterAccept` url.

**Comment by niranjan-uma-shankar** [comment]
> Do you think its better to wait for something like this https://github.com/Automattic/wp-calypso/pull/52909/files#diff-4edb20e49584b60790a9a754c4a145b0687e98bc8903f7cb1dde61db0d7a1e16R12-R27? We need to ensure only certain site types get this treatment.

@lsl Yes, I agree that it makes sense to wait for that to ensure that atomic and others are not affected by this change. I'll proceed with this change once your PR deploys.

**Comment by lsl** [comment]
Did something like the navigate thing I mentioned above [here](https://github.com/Automattic/wp-calypso/pull/53443/files#diff-d025c6a21229fe69836222916356ee8a2c395861252a82ff88e97b9facc70a4bR115), its untested and I might end up stripping it from this PR but its helping me organise the other helper functions for now.

**Comment by niranjan-uma-shankar** [comment]
This is now ready for review.

File: client/my-sites/invites/utils.js [hunk 1]
```diff
@@ -158,6 +164,13 @@ export function getRedirectAfterAccept( invite ) {
 
 	const readerPath = '/read';
 	const postsListPath = '/posts/' + invite.site.ID;
+	const getDestinationUrl = ( redirect ) => {
+		const remoteLoginHost = `https://${ invite.site.domain }`;
+		const remoteLoginBackUrl = ( destinationUri ) => `https://wordpress.com${ destinationUri }`;
+		const destination = logmeinUrl( remoteLoginHost, remoteLoginBackUrl( redirect ) );
```
Comment (lsl) [inline client/my-sites/invites/utils.js:170]: This usage needs fixing (function was changed recently)

File: client/my-sites/invites/utils.js [hunk 2]
```diff
@@ -158,6 +164,13 @@ export function getRedirectAfterAccept( invite ) {
 
 	const readerPath = '/read';
 	const postsListPath = '/posts/' + invite.site.ID;
+	const getDestinationUrl = ( redirect ) => {
+		const remoteLoginHost = `https://${ invite.site.domain }`;
+		const remoteLoginBackUrl = ( destinationUri ) => `https://wordpress.com${ destinationUri }`;
```
Comment (aneeshd16) [inline client/my-sites/invites/utils.js]: Small nit:
```suggestion
		const remoteLoginBackUrl = ( destinationPath ) => `https://wordpress.com${ destinationPath }`;
```

**Review by aneeshd16 — APPROVED** [review]
