### PR TITLE
Whats New: Working in Atomic

### LINKED ISSUE #65973: Fix useHasSeenWhatsNewModalQuery for Atomic sites
We use this query [here](https://github.com/Automattic/wp-calypso/blob/6264558dc849d9e9f0d8a776e1d7aca2ab2fae4a/apps/editing-toolkit/editing-toolkit-plugin/help-center/src/help-center.js#L26) and [here](https://github.com/Automattic/wp-calypso/blob/6264558dc849d9e9f0d8a776e1d7aca2ab2fae4a/packages/help-center/src/components/help-center-more-resources.tsx#L44)

The request fails with 404 error
Screenshot 2022-07-26 at 17 26 24

We should provide working rest endpoint for atomic sites to fix this.

### PR DESCRIPTION
**Pull request by escapemanuele**
Not urgent, may wait for all the changes done in https://github.com/Automattic/wp-calypso/pull/66407

#### Proposed Changes

* This PR reintroduces the `What's New Modal` in Atomic sites. It wasn't working before because of usual API problems in atomic sites (requests need to pass through Jetpack)
image
* Fixed the `useHasSeenWhatsNewModal` query in Atomic, used to determine if to show the dot next to the Help Center
image
* Changed the tracking event for the modal to `calypso_whats_new_slide_view` from `wpcom_whats_new_slide_view`, because it was blocked as not following the guidelines.

#### Testing Instructions

* Checkout branch
* `yarn dev --sync` in `apps/editing-toolkit`
* Check that the query works in simple and atomic sites

Related to #65973 
Fixes #65973

### CODE REVIEW

File: packages/whats-new/src/index.tsx [hunk 1]
```diff
@@ -19,16 +22,26 @@ interface WhatsNewAnnouncement {
...
-				apiNamespace: 'wpcom/v2',
-			} ),
+			isSimpleSite
+				? await wpcomRequest( {
+						path: `/whats-new/list?_locale=${ locale }`,
+						apiNamespace: 'wpcom/v2',
+				  } )
+				: await apiFetch( {
+						global: true,
+						path: `/wpcom/v2/block-editor/whats-new-list`,
```
Comment (alshakero) [inline packages/whats-new/src/index.tsx]: No locale here?

**Review by alshakero — COMMENTED** [review]
Look good. Great work. Makes me even more assured about supporting contact options in Atomic sites soon. Can you test with Jetpack disabled? @arcangelini found yesterday that many things break.


I don't expect the help-center to function without jetpack, but please test if the anything other than that breaks.

File: packages/whats-new/src/index.tsx (hunk 1 above)
Comment (escapemanuele) [reply packages/whats-new/src/index.tsx]: Great catch! Added in the last commit 👍

File: apps/editing-toolkit/editing-toolkit-plugin/whats-new/class-wp-rest-wpcom-block-editor-whats-new-dot-controller.php [hunk 2]
```diff
@@ -15,8 +15,9 @@ class WP_REST_WPCOM_Block_Editor_Whats_New_Dot_Controller extends \WP_REST_Contr
 	 * WP_REST_WPCOM_Block_Editor_Whats_New_Dot_Controller constructor.
 	 */
 	public function __construct() {
-		$this->namespace = 'wpcom/v2';
-		$this->rest_base = 'block-editor/has-seen-whats-new-modal';
+		$this->namespace                       = 'wpcom/v2';
```
Comment (heavyweight) [inline apps/editing-toolkit/editing-toolkit-plugin/whats-new/class-wp-rest-wpcom-block-editor-whats-new-dot-controller.php:18]: Minor formatting issues here

**Review by alshakero — COMMENTED** [review]
Code looks great and like the passing tests now. I will test tomorrow.

File: packages/wpcom-proxy-request/src/index.js [hunk 3]
```diff
@@ -502,8 +502,51 @@ function reject( xhr, err, headers ) {
...
+	return (
+		wpcomAllowedOrigins.includes( urlOrigin ) ||
+		urlOrigin.match( /^https:\/\/[a-z0-9-]+\.calypso\.live$/ ) ||
+		urlOrigin.match( /^https:\/\/([a-z0-9-]+\.)+wordpress\.com$/ )
+	);
+}
+
+function shouldTargetWpcom( isSimpleSite ) {
+	return isSimpleSite || isAllowedOrigin( window.location.origin );
+}
```
Comment (alshakero) [inline packages/wpcom-proxy-request/src/index.js]: `wpcom-proxy-request` shouldn't know about simple and atomic sites, I think we should:

1. Rename the function to `canAccessWpcomApis`.
2. Remove the boolean and use it wherever `shouldTargetWpcom` is used, even though I don't think we need the boolean. All simple sites match `wpcomAllowedOrigins` anyway.

**Review by alshakero — CHANGES_REQUESTED** [review]

**Comment by escapemanuele** [comment]
Thanks @alshakero! Starting from your suggestion, I refactored the use of `shouldTargetWpcom` and removed much of the `isSimpleSite` usage!

**Comment by noahtallen** [comment]
> Can you test with Jetpack disabled?

Is it possible to disable Jetpack on Atomic sites?

**Comment by alshakero** [comment]
> Is it possible to disable Jetpack on Atomic sites?

Yes, it seems like it 🙃 .@arcangelini says HEs can disable JP during debugging. But I can't find how. Any ideas Tony?

**Comment by noahtallen** [comment]
Maybe just on the atomic developer sites? It doesn't seem to be possible on my normal atomic site. I suppose it could be worth asking the Atomic team if a product feature can _always_ rely on jetpack

**Comment by arcangelini** [comment]
Yes, you have to use CLI to do so. It's part of the troubleshooting steps for some plugin/jetpack issues.

**Comment by escapemanuele** [comment]
Should be doable at yourwebsite.com/_cli and then using the command 'wp plugin deactivate jetpack'

**Review by heavyweight — APPROVED** [review]

**Review by alshakero — APPROVED** [review]
So freaking neat. 

1. What's new bubble ✅ 
2. English ✅ 
3. Spanish ✅ 
4. Atomic and Simple ✅
