### PR TITLE
Woo Shipping - Fixed multiple state select

### LINKED ISSUE #16661: Store shipping location: Unable to select more than one state
Noticed while recording the demo. 

states

To test, go to:

1. Settings > Shipping
2. Edit or add a zone with United States as the location
3. Choose: Include specific states in zone
4. Select a state
5. A glitch in the matrix!
6. Click done, and state has been added. 

Overall, I was able to add the state, but the UI sort of broke in step 5. I should also be able to add multiple states.

### PR DESCRIPTION
**Pull request by marcinbot**
Fixes #16661

This was quite difficult to debug. Basically a memoized result of a function was modified directly which then affected the rest of the app.

I also added small tweaks in some of the selectors.

CC @kellychoffman @DanReyLop

### CODE REVIEW

File: client/extensions/woocommerce/state/data-layer/ui/shipping-zones/index.js [hunk 1]
```diff
@@ -121,8 +121,11 @@ const getCreateShippingZoneSteps = ( siteId, zoneId, zoneProperties ) => {
 const getUpdateShippingZoneLocationsSteps = ( siteId, zoneId, locations, serverLocations ) => {
 	serverLocations = serverLocations || { continent: [], country: [], state: [], postcode: [] };
 	if ( ! isEmpty( locations.state ) ) {
-		locations.state = locations.state.map( st => locations.country[ 0 ] + ':' + st );
```
Comment (marcinbot) [inline client/extensions/woocommerce/state/data-layer/ui/shipping-zones/index.js]: This is what was causing the bug

File: client/extensions/woocommerce/state/ui/shipping/zones/locations/selectors.js [hunk 2]
```diff
@@ -284,10 +284,13 @@ export const getShippingZoneLocationsWithEdits = createSelector(
 		return [
 			loaded,
 			zone,
-			zone && getRawShippingZoneLocations( state, siteId ),
+			zone && getShippingZoneLocations( state, zone.id, siteId ),
```
Comment (marcinbot) [inline client/extensions/woocommerce/state/ui/shipping/zones/locations/selectors.js]: The new dependency is `getShippingZoneLocations` so I updated it.

File: client/extensions/woocommerce/state/ui/shipping/zones/locations/selectors.js [hunk 3]
```diff
@@ -284,10 +284,13 @@ export const getShippingZoneLocationsWithEdits = createSelector(
...
 			zone && getShippingZonesEdits( state, siteId ),
 			zone && getCountriesOwnedByOtherZone( state, siteId ),
 		];
+	},
+	( state, siteId = getSelectedSiteId( state ), overlayTemporalEdits = true ) => {
+		return [ siteId, overlayTemporalEdits ].join();
```
Comment (marcinbot) [inline client/extensions/woocommerce/state/ui/shipping/zones/locations/selectors.js]: This makes memoization more effective. Without it, the whole state tree is taken as a cache key. With it, the relevant state changes clean the cache by the function above, and the cache key consists only of the additional arguments passed to the function.

**Comment by kellychoffman** [comment]
Awesome! Late to the party but tested on production and it works great!
