### PR TITLE
Editor: Fix over-riding of local title edits on auto-save.

### LINKED ISSUE #11567: Editor: Autosave reverts content typed while autosaving
#### Steps to reproduce
1. Go to your WordPress site
2. Click the "Write" button in the top toolbar
3. Start to type a title. Type a character every half second or so.
4. Wait for autosave to kick in
5. Keep typing while autosave is autosaving
6. Wonder where your title went

#### What I expected

I expected that autosave would keep the content I was typing when autosave was running

#### What happened instead

The title reverts to the state it was in when autosave started.

We've had reports this happens on tags and the post body too, but for some reason it's harder to reproduce there.

#### Browser / OS version

Chrome/Firefox, Windows/Mac/Linux

#### Screenshot / Video

https://cloudup.com/ctBtqSg67o9

#### Context / Source

#intense-frustration #data-loss #user-report

### PR DESCRIPTION
**Pull request by timmyc**
This branch fixes #11567 which is causing local edits of the title field to be lost when the changes are made while an auto-save is in flight.

There is a video of the bug in #11567 - but to see the bug in action, add some content to a post ( draft ) you are editing, then focus on the title field.  Watch the ground control area, and as soon as an auto save fires, start changing the title, and once the API returns, your local title changes will disappear 💥 

I traced the issue back to `onSaveSuccess` in `<PostEditor />` which was calling `savePostSuccess` which clears out any local edits in the state tree.  `onSaveSuccess` also calls `receivePost` which iterates over the local edits, and compares it against the saved post from the API, and only deletes edits that match - so it _seems_ like the call to `recievePost` should be enough here ( though /cc @aduth for your thoughts ).

### CODE REVIEW

File: client/post-editor/post-editor.jsx [hunk 1]
```diff
@@ -713,9 +713,6 @@ export const PostEditor = React.createClass( {
 			this.props.resetEditorLastDraft();
 		}
 
-		// Remove this when the editor is completely reduxified ( When using Redux actions for all post saving requests )
-		this.props.savePostSuccess( post.site_ID, this.props.postId, post, {} );
```
Comment (youknowriad) [inline client/post-editor/post-editor.jsx]: This was introduced here https://github.com/Automattic/wp-calypso/pull/10177 and the idea IIRC was to update the editedPostId in the state when we're creating a new post. If we drop this, the editedPostId on the state will not reflect the saved post id. I'm not sure What's the impact yet.

Comment (youknowriad) [inline client/post-editor/post-editor.jsx]: One other thing to think about. Currently, since the editor is not reduxified, saving a post is called using the old Actions but when we reduxify everything, we would probably call the `savePost` action which could create the same bug. So maybe the fix for this would be to clear the edits when triggering the request instead of when receiving the response. The downside of this approach is when the save fails.

Comment (aduth) [inline client/post-editor/post-editor.jsx]: Alternatively, could we update the reducer for edits to migrate them to the updated post ID when saving a new post (i.e. going from `null` to valid `postId`)?

Comment (timmyc) [inline client/post-editor/post-editor.jsx]: In my testing I haven't found any issues with removing this code.  The same logic is repeated by [exitPost](https://github.com/Automattic/wp-calypso/blob/master/client/post-editor/controller.js#L233) which seems to clear up the original issue of lingering draft edits when leaving the editor.

> So maybe the fix for this would be to clear the edits when triggering the request instead of when receiving the response.

This seems like a logical approach too.  The action would have to clear edits specific for autoSave vs full save events since autoSave only sends Title, Excerpt and content so it should not clear out edits of other attributes.

Would you be willing to allow me to explore that approach in a subsequent PR @youknowriad and at least get this fix out to stop the loss of data?  I hit this bug a few times yesterday while testing the new chrome and it really does take ones trust away from the save operations.

Comment (aduth) [inline client/post-editor/post-editor.jsx]: If we remove this, we'll want to remove the prop from `mapDispatchToProps` since this is the only place it's used. Just a small observation, still doing a more in-depth review...

**Comment by timmyc** [comment]
Thanks for finding that issue @aduth - I will work on a solution.

**Comment by timmyc** [comment]
The issues were due to `state/ui/editor/reducer` still needing to have the `POST_SAVE_SUCCESS` action triggered in order to maintain a correct state.  So I set about a fix to make the `POST_SAVE_SUCCESS` reducer respect any local changes in the `edits` subtree... but then realized the same logic is already happening in `POSTS_RECEIVE` so we could safely remove the logic around `POST_SAVE_SUCCESS` in the edits reducer entirely ( which was what my original fix effectively did ).

At some point we will need to revisit this when all is in redux, but for now this seems to be a logical fix.  @aduth thoughts?

**Comment by aduth** [comment]
With the latest changes, it appears to revert back to the previous issue of losing changes made while the save request is in-flight. At least it does when writing a title for a new draft. I have a feeling that it's preserving the edits under the empty (new post) `''` key, but since the post ID is updated to a numeric value, it's no longer associated with the post being edited.

**Comment by gcorne** [comment]
Just a random drive-by from someon from another era, but I fixed this issue back in the day by keeping a queue of changes that occurred while a request was in-flight and then reapplying them. I imagine that subtle aspect got lost during reduxification. See https://github.com/Automattic/wp-calypso/blob/master/client/lib/posts/post-edit-store.js#L98

**Comment by gcorne** [comment]
To add a tiny bit of additional color, the reason that the queue was necesary was to properly set the dirty state after one or more edit actions has occurred (perhaps mutating different properties of the post) while the save request is in-flight.

**Comment by aduth** [comment]
Hi @gcorne 😄  Hope you've been well!

With the current Redux state being capable of tracking multiple posts and edit values for multiple posts, I think what had previously been reflected in the queue could be imitated by tracking edits in the empty (new) post key and, at the time the save completes, simply replace (or copy values from) the key with the new post ID. Maybe a new action which notifies that the edited post's ID has changed, in this case from `""` to `281` (or whatever the ID ends up being).

**Comment by timmyc** [comment]
👋  @gcorne - great to see you!

**Comment by timmyc** [comment]
@aduth in b7c5ec9I have added logic that when the prior save operation had a null `postId` copy over any edits from `''` to the new `savedPost.ID`

File: client/state/posts/reducer.js [hunk 2]
```diff
@@ -282,6 +281,23 @@ export function edits( state = {}, action ) {
...
 			} );
 
+		case POST_SAVE_SUCCESS:
+			if ( ! state.hasOwnProperty( action.siteId ) || ! action.savedPost ) {
+				break;
+			}
+			const { postId, siteId, savedPost } = action;
+
+			if ( postId ) {
+				return state;
```
Comment (aduth) [inline client/state/posts/reducer.js]: Should we be consistent with how we exit early from the switch, between this and the `break;` above which achieve the same goal?

File: client/state/posts/reducer.js [hunk 3]
```diff
@@ -282,6 +281,23 @@ export function edits( state = {}, action ) {
...
+			}
+
+			// if postId is null, copy over any edits
+			return Object.assign( {}, state, {
+				[ siteId ]: {
```
Comment (aduth) [inline client/state/posts/reducer.js]: The way we're assigning here will delete any other post IDs for the same site. While in practice this will probably never occur, and conveniently removes the `''` (empty) key for us, we might want to preserve these either with `_.merge` or a nested `Object.assign`:

```js
return {
	...state,
	[ siteId ]: {
		...state[ siteId ],
		[ savedPost.ID ]: state[ siteId ][ '' ]
	}
};
```

Of course at that point we'd need to assume responsibility for removing the empty key:

```js
const nextState = {
	...state,
	[ siteId ]: {
		...state[ siteId ],
		[ savedPost.ID ]: state[ siteId ][ '' ]
	}
};
delete nextState[ siteId ][ '' ];
return nextState;
```

Alternatively we could use [`_.mapKeys`](https://lodash.com/docs/4.17.4#mapKeys) to reassign the empty key:

```js
return {
	...state,
	[ siteId ]: mapKeys( state[ siteId ], ( value, key ) => (
		'' === key ? savedPost.ID : key
	) )
};
```

File: client/state/posts/reducer.js (hunk 2 above)
Comment (aduth) [inline client/state/posts/reducer.js]: Also, should we make this so specific to the empty postId case? Presumably if it were ever the case that the ID from the savedPost differs from the `postId` we sent with the save, we'd want to re-key?

File: client/state/posts/reducer.js [hunk 4]
```diff
@@ -282,6 +281,23 @@ export function edits( state = {}, action ) {
 				[ action.siteId ]: omit( state[ action.siteId ], action.postId || '' )
 			} );
 
+		case POST_SAVE_SUCCESS:
+			if ( ! state.hasOwnProperty( action.siteId ) || ! action.savedPost ) {
```
Comment (aduth) [inline client/state/posts/reducer.js]: A little safety doesn't hurt, but is there ever a case where `action.savedPost` would be falsey?

Comment (timmyc) [inline client/state/posts/reducer.js]: Probably not, but one seems okay to err on the side of safe here.

File: client/state/posts/reducer.js (hunk 2 above)
Comment (timmyc) [inline client/state/posts/reducer.js]: Not entirely sure I follow here, if the prior `props.postId` was set, and it differs from `savedPost.ID`?  I hope that doesn't happen, but is that what you are talking about?

**Comment by timmyc** [comment]
Went with the `mapKeys` approach in 940d479

File: client/state/posts/reducer.js [hunk 5]
```diff
@@ -282,6 +281,20 @@ export function edits( state = {}, action ) {
 				[ action.siteId ]: omit( state[ action.siteId ], action.postId || '' )
 			} );
 
+		case POST_SAVE_SUCCESS:
+			if ( ! state.hasOwnProperty( action.siteId ) || ! action.savedPost || action.postId ) {
+				break;
+			}
+			const { siteId, savedPost } = action;
```
Comment (aduth) [inline client/state/posts/reducer.js]: Minor, not worth another round of reviews: Could move destructuring above the condition to make the condition slightly shorter:

```js
const { siteId, savedPost, postId } = action;
if ( ! state.hasOwnProperty( siteId ) || ! savedPost || postId ) {
```

**Comment by aduth** [comment]
>Not entirely sure I follow here, if the prior props.postId was set, and it differs from savedPost.ID? I hope that doesn't happen, but is that what you are talking about?

Right, so the thinking is when we call `savePost` with a post ID, we include that original post ID in the final payload for `POST_SAVE_SUCCESS`, so if in the odd chance the ID for the post we assumed we were saving differs from what we receive in the response, we'd still want to reflect that by migrating the edits. Or at the very least, we needn't go out of our way to avoid it by adding conditions to check whether the `postId` is truthy.

But you're right, this shouldn't ever happen, and may very well have other implications if it were to, so I'm not too concerned about it.
