### PR TITLE
Store Services - handling failed fetch state

### LINKED ISSUE #20260: Store: Repeated requests (2x/sec) to Jetpack Proxy for /wc/v1/connect/account/settings
#### Steps to reproduce
1. Starting at URL: While sitting at http://calypso.localhost:3000/store/{DOMAIN}
2. Open the JavaScript developer tools, network tab
3. Observe repeated (2x/sec) calls to the Jetpack proxy for /wc/v1/connect/account/settings

Note: This doesn't seem to happen everytime you visit a store's dashboard - just some of the time

These calls all fail with
```
{"code":404,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"rest_no_route","message":"No route was found matching the URL and request method"}}
```

### PR DESCRIPTION
**Pull request by marcinbot**
Fixes #20260 

To test:
* in wp-admin, disable the WooCommerce services plugin
* in Calypso, open the shipping settings page and verify that the requests to the WCS endpoints are made only once, and the components are hidden after the requests error out
* navigate to a fulfilled order and verify that the activity log renders correctly
* navigate to an unfulfilled order and verify that the fulfill button and activity log render
* everything should also work as before when the plugin is enabled

### CODE REVIEW

File: client/extensions/woocommerce/state/sites/orders/activity-log/selectors.js [hunk 1]
```diff
@@ -52,8 +53,16 @@ export const EVENT_TYPES = {
...
  */
 export const isActivityLogLoaded = ( state, orderId, siteId = getSelectedSiteId( state ) ) => {
-	return areOrderNotesLoaded( state, orderId, siteId ) &&
-		( ! config.isEnabled( 'woocommerce/extension-wcservices' ) || areShippingLabelsLoaded( state, orderId, siteId ) );
+	const notesLoaded = areOrderNotesLoaded( state, orderId, siteId );
+	if ( ! notesLoaded ) {
+		return false;
+	}
+
+	if ( ! config.isEnabled( 'woocommerce/extension-wcservices' ) || areShippingLabelsErrored( state, orderId, siteId ) ) {
```
Comment (timmyc) [inline client/extensions/woocommerce/state/sites/orders/activity-log/selectors.js]: Is there an env where this still isn't enabled? Guessing Desktop, but since this is live in production now do we need to have this config check?

File: client/extensions/woocommerce/state/sites/orders/activity-log/selectors.js [hunk 2]
```diff
@@ -63,10 +72,16 @@ export const isActivityLogLoaded = ( state, orderId, siteId = getSelectedSiteId(
...
  */
 export const isActivityLogLoading = ( state, orderId, siteId = getSelectedSiteId( state ) ) => {
-	if ( config.isEnabled( 'woocommerce/extension-wcservices' ) ) {
-		return areOrderNotesLoading( state, orderId, siteId ) || areShippingLabelsLoading( state, orderId, siteId );
+	const notesLoading = areOrderNotesLoading( state, orderId, siteId );
+	if ( notesLoading ) {
+		return true;
+	}
+
+	if ( ! config.isEnabled( 'woocommerce/extension-wcservices' ) || areShippingLabelsErrored( state, orderId, siteId ) ) {
```
Comment (timmyc) [inline client/extensions/woocommerce/state/sites/orders/activity-log/selectors.js]: Likewise here, but we could just do config clean-up in a different PR too.

Comment (marcinbot) [reply client/extensions/woocommerce/state/sites/orders/activity-log/selectors.js]: Let's do a config cleanup in a separate PR. If we remove it here, there a bunch of other files that need to be fixed as well that are out of scope

**Comment by allendav** [comment]
@timmyc wrote

> Part of me thinks that since WCS isn't a firm requirement of Store on wpcom, we should not do the requests if we know the plugin is disabled, but wanted to hear other's thoughts.

I agree - not just for the customer's sake but for our support peoples' sake - if the console gets cluttered with false alarms if will become more and more difficult to troubleshoot end user's problems.

**Comment by DanReyLop** [comment]
So, if we don't want to have requests failing, what about this approach?
* Use the `<QueryJetpackPlugins>` component in the WooCommerce root view. That will fetch the status of all the installed plugins on the site.
* Create a helper function `isWCServicesEnabled` that checks *if* the config key `woocommerce/extension-wcservices` is enabled *AND* the `woocommerce-services` plugin is installed and active.
* Replace all instances of `config.isEnabled( 'woocommerce/extension-wcservices' )` with that function.
* Make sure everything works with `woocommerce-services` disabled, the config flag has been enabled for so long that maybe we missed something.
* Maybe add a global notice if the plugin is disabled? Like a nudge to install it?

This may be overkill for now, but we will need to handle this kind of cases when we open to Jetpack sites. The core Store experience should work without `woocommerce-services` installed, the same way it works without MailChimp etc.

What do you folks think about it?

**Comment by timmyc** [comment]
@DanReyLop I think that is a good plan, and like you said, something we will definitely need moving forward as we consider things like extension support in Store. This could also be used to, like you said, provide better error notices/feedback to users. We had a user contact support this week asking why Stripe wasn't showing up as a payment option - and it was due to the gateway plugin being disabled... so we could use this data in instances like that too.

> Maybe add a global notice if the plugin is disabled? Like a nudge to install it?

I think this would be a good nudge to have for WCS, especially if framed along the lines of how we handle this situation in wp-admin. Let them know about label printing in the notice. But I think that could be handled in a different PR.
