### PR TITLE
Account Closure: Provide Confirmation On-Screen

### LINKED ISSUE #35977: Me: Improve the on-screen feedback when an account is closed
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/account
2. Select "Close your account permanently."
3. On the next screen, select "Close account."
4. In the modal that appears, enter your username and select "Close your account" to confirm.

#### What I expected
I expected some kind of message or spinner to indicate that my account closure was being processed, and/or a confirmation message that it succeeded.

#### What happened instead
There was no indication on-screen that anything was happening (the modal window just disappeared) and then I was logged out of my account with no further message.

#### Browser / OS version
Safari version 12.1.2 (14607.3.9)
Mac OS Mojave 10.14.6

Reproduced in 76.0.3809.132

#### Context / Source
Beta testing, h/t @serabi and @coder-karen for the reports (internal refs: p77Llu-cz5-p2#comment-14708 and p77Llu-cz5-p2#comment-14719 )

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

Currently, when an account is closed, there's no confirmation that the account has been closed, and things can break if you start clicking away during the process. This PR changes that. It probably isn't exactly ideal since it creates a new section, but I found it the best way to make sure there's no sidebar or masterbar.

#### Testing instructions

Visit `me/account/closed` directly and verify you're taken to `me/account/close`. Now try to close your account following the on-screen steps, and verify that the result is the same as the GIF below.

**Before:**

ezgif-4-f3cb09815a4e

**After:**

ezgif-4-38189b5c2a99

cc @bluefuton - last account closure PR I think :)

Fixes #35977

### CODE REVIEW

File: client/me/account-close/closed.jsx [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+					<p className="account-close__spinner-text">
+						{ translate( 'Your account is being deleted' ) }
+					</p>
+				</div>
+			);
+		}
+
+		return (
+			<EmptyContent
+				title={ translate( 'Your account has been closed' ) }
```
Comment (a8ci18n) [inline client/me/account-close/closed.jsx]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **7** times:
`translate( 'User Account has been closed.' )` *ES Score: 7*

File: client/me/account-close/closed.jsx [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+				line={ translate( 'Thank you for flying with WordPress.com' ) }
```
Comment (a8ci18n) [inline client/me/account-close/closed.jsx]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **4** times:
`translate( 'Thanks for flying with WordPress.com' )` *ES Score: 7*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/pull/37688)

Comment (Aurorum) [reply client/me/account-close/closed.jsx]: Updated to this. :)

File: client/sections.js [hunk 3]
```diff
@@ -40,6 +40,13 @@ const sections = [
 		group: 'me',
 		secondary: true,
 	},
+	{
+		name: 'account-closed',
+		paths: [ '/me/account/closed' ],
+		module: 'me/account-close',
+		group: 'me',
+		secondary: false,
```
Comment (jsnajdr) [inline client/sections.js]: Is this `secondary: false` (i.e., no sidebar) the only reason you had to create a new section?

Comment (Aurorum) [reply client/sections.js]: Yep

File: client/layout/index.jsx [hunk 4]
```diff
@@ -187,7 +188,7 @@ export default connect( state => {
 	const siteId = getSelectedSiteId( state );
 	const isJetpackLogin = startsWith( currentRoute, '/log-in/jetpack' );
 	const isJetpack = isJetpackSite( state, siteId ) && ! isAtomicSite( state, siteId );
-	const noMasterbarForRoute = isJetpackLogin;
+	const noMasterbarForRoute = isJetpackLogin || 'account-closed' === sectionName;
```
[the remark this answers is not in the document]
Comment (Aurorum) [reply client/layout/index.jsx]: Whoops, fixed! :)

File: client/sections.js (hunk 3 above)
Comment (jsnajdr) [reply client/sections.js]: You can also hide the sidebar by dispatching a `setSection( null, { hasSidebar: false } )` action in the route handler.

See how [Jetpack Connect does it](https://github.com/Automattic/wp-calypso/blob/master/client/jetpack-onboarding/controller.js#L13). That disables the sidebar for one specific route and allows you to keep a single section.

Comment (Aurorum) [reply client/sections.js]: Thanks! I've updated the PR to do that and avoid creating a new section. :)

Comment (jsnajdr) [reply client/sections.js]: Nice! Today, I added a new action `hideSidebar` that should make this even easier: https://github.com/Automattic/wp-calypso/pull/37816

**Comment by jsnajdr** [comment]
About the "Your account has been closed" page:
- I assume that the user is logged out after we get here. Can we show the masterbar on this page then? It contains links to log in or sign up. The cycle of life can continue and the user can register or log in again 😄 Instead of being stuck on an "end of the internet" type of page.
- if the account closure really logs the user out and removes all authentication cookies (does it really?), we should do a full reload when navigating there: `window.location = ...` instead of `page( ... )`. If we do just a SPA navigation with page.js, the user info and state is still in memory.

**Comment by Aurorum** [comment]
Ah, that's a tough one. No, the user doesn't (wouldn't) see the logged-out Masterbar. A hard reload would be necessary for that to work, but if that happened, `/me/account/close` wouldn't be the previous route, so the user would just redirect to that page. 

I do agree that the "end of the internet" type page probably isn't ideal, but I'm not sure it's possible to add the Masterbar in an ideal way that doesn't allow people to directly visit `/me/account/closed`. I added a commit that adds a button to say "Return to WordPress.com", which does allow for the hard reload necessary to sign out. 

Screenshot 2019-11-21 at 17 15 00

Do you think that's a better approach?

File: client/sections.js (hunk 3 above)
Comment (Aurorum) [reply client/sections.js]: Thanks! Updated to use that. :)

File: client/me/account-close/closed.scss [hunk 5]
```diff
@@ -0,0 +1,10 @@
+.account-close__spinner {
+	padding-top: 120px;
+	text-align: center;
+
+	&-text {
```
Comment (jsnajdr) [inline client/me/account-close/closed.scss]: Can you expand this to the full `.account-close__spinner-text`? That makes it possible to grep the codebase for CSS class names.

File: client/me/account-close/closed.jsx [hunk 6]
```diff
@@ -0,0 +1,62 @@
...
+				</div>
+			);
+		}
+
+		return (
+			<EmptyContent
+				title={ translate( 'Your account has been closed' ) }
+				line={ translate( 'Thanks for flying with WordPress.com' ) }
+				secondaryAction={ translate( 'Return to WordPress.com' ) }
+				secondaryActionCallback={ this.onClick }
```
Comment (jsnajdr) [inline client/me/account-close/closed.jsx]: This could also be `secondaryActionURL="/"` and would render an `<a href="/">` with button styles. However, the navigation is done with `page` instead of `window.location`. But because we don't log out the user, it doesn't matter that much.

File: client/me/account-close/closed.jsx [hunk 7]
```diff
@@ -0,0 +1,62 @@
...
+import './closed.scss';
+
+class AccountSettingsClosedComponent extends Component {
+	onClick = () => {
+		window.location = '/';
+	};
+
+	render() {
+		/* eslint-disable-next-line no-shadow */
+		const { isAccountClosed, previousRoute, translate } = this.props;
```
Comment (jsnajdr) [inline client/me/account-close/closed.jsx]: Let's rename the `isAccountClosed` prop instead of shadowing the imported variable and having to disable the ESLint rule.

**Review by jsnajdr — APPROVED** [review]
I posted a few little comments, but otherwise this is ready to go.

**Comment by jsnajdr** [comment]
> I added a commit that adds a button to say "Return to WordPress.com"

Yes, I like it a lot! Thanks for this nice idea.

File: client/me/account-close/closed.jsx (hunk 6 above)
Comment (Aurorum) [reply client/me/account-close/closed.jsx]: Yep.

**Current:**
ezgif-6-7c43e1784d2b

**With `secondaryActionURL`:**

ezgif-6-f27bc63a8dca

File: client/me/account-close/closed.scss (hunk 5 above)
Comment (Aurorum) [reply client/me/account-close/closed.scss]: Done! :)

File: client/me/account-close/closed.jsx (hunk 7 above)
Comment (Aurorum) [reply client/me/account-close/closed.jsx]: Thanks, fixed! :)

File: client/me/account-close/closed.jsx (hunk 6 above)
Comment (jsnajdr) [reply client/me/account-close/closed.jsx]: OK, if you verified that `secondaryActionURL` really doesn't work, then let's keep the `Action` click handler.

My point was that for simple navigations from one page to another, an `<a href>` link would be preferrable. But in this case we need to enforce full page reload.
