### PR TITLE
Hosting: Provide Confirmation when Copying SFTP Credentials

### LINKED ISSUE #55316: Hosting Configuration: No visual indication / clue when clicking `Copy` button within SFTP Credentials fields
### Steps to Reproduce

1. Start at WordPress.com > My Sites > Settings > Hosting Configuration > Create SFTP Credentials
2. Try clicking any `Copy` button inside the text fields

### What I expected to happen

See some visual indication of the button being clicked or some message confirming that the value has been copied.

### What actually happened

There is no visual indication of the button being clicked or some message confirming that the value has been copied.

### Context

Encountered in 4208655-zd-woothemes after testing the SFTP Credentials creation on my own AT site

### Operating System

macOS

### OS Version

BigSur 11.4

### Browser

Chrome/Chromium

### Browser Version(s)

92

### Is this specific to applied theme? If so, what is the theme name?

No

### Simple, Atomic or both?

Atomic

### Console and/or error logs

_No response_

### Number of Users Impacted

All users

### Available Workarounds

_No response_

### Reproducibility

Consistent

### Other information

https://user-images.githubusercontent.com/39308239/128865368-8aa0f105-722b-4718-9d07-de81d63b7000.mov

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

* Provides confirmation when copying SFTP credentials

This change is consistent with the existing pattern in Calypso - see below. I did think about moving it into the component itself, but it probably makes sense to reset the "Copied" state of other buttons once something else is copied. 

https://github.com/Automattic/wp-calypso/blob/7fe7e962ea85fab34bf7abaa846c646e9e004e8a/client/my-sites/domains/components/domain-warnings/pending-gsuite-tos-notice-dialog.jsx#L147-L155

#### Testing instructions

Click the "Copy" button in the Hosting Configuration section, and verify this changes to "Copied!". It should then reset when you use a different copy button.

Screenshot 2021-09-21 at 14 47 25

cc @mmtr

Fixes #55316

### CODE REVIEW

**Comment by mmtr** [comment]
Thanks @Aurorum! Still have not reviewed your changes, since I've been AFK for a few days and I'm today catching up. Only wanted to let you know that this is on my radar and will review it as soon as I can. However, next week I'll be away attending our team meetup and my availability will be quite limited, so it may take a bit a longer. Apologies for the wait!

cc @Automattic/flowpatrol in case they can help in the meantime.

File: client/my-sites/hosting/sftp-card/index.js [hunk 1]
```diff
@@ -51,13 +51,35 @@ export const SftpCard = ( {
...
+		setIsCopied( { password: false, url: true, port: false, username: false } );
+	};
+
+	const onCopyPort = () => {
+		setIsCopied( { password: false, url: false, port: true, username: false } );
+	};
+
+	const onCopyUsername = () => {
+		setIsCopied( { password: false, url: false, port: false, username: true } );
+	};
```
Comment (mmtr) [inline client/my-sites/hosting/sftp-card/index.js]: Nitpick: I generally don't like early abstractions, but since we're already slightly copying the same code 4 times, it might be a good indicator that an abstraction here could help 🙂 

Something like this can work:

```js
const onCopy = ( field ) => setIsCopied( { ...isCopied, [ field ]: true } );
```

Then each `ClipboardButton` component should call to that function and provide the name of the affected field. Example:
```jsx
<ClipboardButton
	className="sftp-card__copy-button"
	text={ password }
	onCopy={ () => onCopy( 'password' ) }
	compact
>[...]</ClipboardButton>
```

Good thing about this approach is that the "Copied" label will be kept after copying a different field.

**Review by mmtr — COMMENTED** [review]
It works great! I left a minor comment, let me know what you think @Aurorum. 

Heads up that I'll be AFK for the rest of the week starting tomorrow, so it make take a bit more until I'm able to get back to you. Sorry once again for the extra wait!

**Comment by sixhours** [comment]
Hey hey @Aurorum! Tested and this works well! It probably needs a rebase before I run the tests. Feel free to save the abstraction for a separate PR if you like.

https://user-images.githubusercontent.com/2124984/137175038-21f75c9b-9339-4091-951e-56170558094d.mov

File: client/my-sites/hosting/sftp-card/index.js (hunk 1 above)
Comment (Aurorum) [reply client/my-sites/hosting/sftp-card/index.js]: Thanks @mmtr! I've simplified the approach based on that a bit, but I'm not very sure about whether the "Copied" label _should_ be kept after copying a different field. To me, that feels a little odd given you can usually only have one thing copied, and the user may want to re-copy that field. 

However, I'm happy to change that if it would be preferential to have the label reset after copying a different field.

**Comment by Aurorum** [comment]
Apologies for the delay! I've updated this PR now. :)

File: client/my-sites/hosting/sftp-card/index.js (hunk 1 above)
Comment (mmtr) [reply client/my-sites/hosting/sftp-card/index.js]: > To me, that feels a little odd given you can usually only have one thing copied, and the user may want to re-copy that field.

Very valid concern, didn't consider it!

**Review by mmtr — APPROVED** [review]

**Comment by mmtr** [comment]
Thanks for adding the small abstraction again @Aurorum! Still works great 🙂
