### PR TITLE
Fix: Bulk media editor does not save captions reliably

### LINKED ISSUE #52041: Image Captions: Bulk Editor does not add captions reliably
### Steps to reproduce the behavior

1. Add 10-15 images to media library
2. After they have loaded, click on Edit
3. Update "Title" and "Caption" fields for each image, moving between them using the arrow on the image.
4. Click Done after all images edited, then check image captions

#### What I expected to happen
The images should be updates according to the values added.

#### What actually happened
The titles have updated, and some captions have updated, but not all.

### Context
zd-3899223

#### Browser / OS version
Tested on Chrome, OSX 11.2.3

#### Is this specific to the applied theme? Which one?
Does not seem theme specific.

#### Does this happen on simple or atomic sites or both?
Only tested on Simple sites.

#### Is there any console output or error text?
N/A

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
It is mostly an irritation, and can be avoided by editing images one at a time. Some other aspects I did not check: Whether adding the titles first, saving that, and then adding the captions in another wave works, and I did not test the alt text or description fields.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Intermittent. Unclear what determines why a caption gets left off.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Every time I try to make a video of it, everything works the way it should. Maybe I'm not selecting enough images. Here's an image after the fact with some annotations:
Annotation on 2021-04-18 at 17-23-26

### PR DESCRIPTION
**Pull request by taggon**
#### Changes proposed in this Pull Request

* This PR fixes the following two bugs of the bulk media editor:
  * The caption or description is not saved when move to the next/prev image within one second after changing the field.
     ML BULK EDITING
  * The caption or description is not updated when you move to the next/prev image then back after chaning the field. It will be updated close and reopen the dialog.
    bulk-media-editor-bug

#### Testing instructions

**Case 1**
1. Select two images or more in the Media page.
2. Update caption or description then move to the next/prev image within one second after the change.
3. Click the Done button.
4. Reopen the media detail modal.
5. Make sure the value of the field is the same with your latest input.

**Case 2**
1. Select two images or more in the Media page.
2. Update caption or description.
3. Wait more than one second.
4. Move to the next/prev image then back. (do not close the dialog)
5. Make sure the value of the field is the same with your latest input.

Fixes #52041

### CODE REVIEW

**Comment by donlair** [comment]
This is looking good! One thing I noticed is related to unsaved changed if you switch to another image within one second: it only saves the first character added:

https://user-images.githubusercontent.com/35781181/119390865-a179d100-bc9b-11eb-9073-393e266204a5.mov

Everything else works as expected.

**Comment by taggon** [comment]
Thanks @donlair ! I fixed the case too. :)

File: client/my-sites/media/main.jsx [hunk 1]
```diff
@@ -204,6 +205,25 @@ class Media extends Component {
 		this.maybeRedirectToAll();
 	};
 
+	updateItem = ( itemId, detail ) => {
+		const { selectedItems } = this.state;
+		const index = findIndex( selectedItems, ( item ) => item.ID === itemId );
```
Comment (yansern) [inline client/my-sites/media/main.jsx]:
```suggestion
		const index = selectedItems.findIndex( ( item ) => item.ID === itemId );
```
Do consider native `Array.findIndex` since we're trying to move away from lodash? (See p4TIVU-9Bf-p2 and  https://github.com/Automattic/wp-calypso/pull/51976)

File: client/post-editor/media-modal/detail/detail-item.jsx [hunk 2]
```diff
@@ -139,8 +142,8 @@ export class EditorMediaModalDetailItem extends Component {
 		const { item, translate } = this.props;
 
 		//do a simple guid vs url check
-		const guidParts = url.parse( item.guid );
-		const URLParts = url.parse( item.URL );
+		const guidParts = getUrlParts( item.guid );
+		const URLParts = getUrlParts( item.URL );
```
Comment (yansern) [inline client/post-editor/media-modal/detail/detail-item.jsx:146]: Just curious to know why the decision of moving from `url` package and use `getUrlParts` from `@automattic/calypso-url` was made?

**Review by yansern — APPROVED** [review]
This PR tests well. Approving this PR.
I left some comments which are not blockers to getting this PR merged.

File: client/post-editor/media-modal/detail/detail-fields.jsx [hunk 3]
```diff
@@ -25,20 +25,30 @@ class EditorMediaModalDetailFields extends Component {
...
+	};
+
+	static defaultProps = {
+		onUpdate: noop,
 	};
 
 	constructor() {
 		super( ...arguments );
-		this.persistChange = debounce( this.persistChange, 1000 );
+		this.persistChange = debounce( this._persistChange, 1000 );
```
Comment (yansern) [inline client/post-editor/media-modal/detail/detail-fields.jsx:37]: When it comes to deciding the debouncing interval, I personally choose a value that is around 300ms. This is considering that average human typing CPM is about 200. So 1000ms / (200chars / 60 secs) = 300ms.

File: client/post-editor/media-modal/detail/detail-item.jsx (hunk 2 above)
Comment (taggon) [reply client/post-editor/media-modal/detail/detail-item.jsx:146]: @yansern The linter brought me there. The `url` package is deprecated.

File: client/post-editor/media-modal/detail/detail-fields.jsx (hunk 3 above)
Comment (taggon) [reply client/post-editor/media-modal/detail/detail-fields.jsx:37]: I just respect the original value to keep my changes as small as possible even though the number `1000` looks like a random magic number. :)
