### PR TITLE
Disable scrolling sync when Site Picker is shown in SideBar

### LINKED ISSUE #68251: [Bug]: The "Add new site" button is not always visible
### Quick summary

When the Site Picker is shown in the SideBar, sometimes the "Add new site" button is not visible. It's visible on load, but it disappears sometimes if you scroll the page vertically. 

https://user-images.githubusercontent.com/6851384/192198371-89f67f86-9510-41f5-9773-42620d1a4952.mp4

### Steps to reproduce

1. Open the Admin Dashboard at `/home/:site`. Make sure the SideBar is open 
2. Click the "Switch site" button to enable the Site Picker
3. Confirm you can see Sites search input, the "Manage sites" button and the "Add new site" button
4. Scroll up/down the content section, and you should see that the "Add new site" button is not on screen as per the video above

### What you expected to happen

The "Add new site" button should always be shown as the sites list is scrollable in this layout

### What actually happened

The "Add new site" button is hidden sometimes depending on the `#content` scroll position. 

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Context

I stumbled upon this when looking at a different issue. 

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Other notes

_No response_

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

You can still access the button by scrolling the page, but this might not be obvious to all users.

### PR DESCRIPTION
**Pull request by mpkelly**
Fixes https://github.com/Automattic/wp-calypso/issues/68251

#### Proposed Changes

* There is some sync scrolling logic in [SidebarScrollSynchronizer](https://github.com/Automattic/wp-calypso/blob/262c9458981e15997154fc400d4b154f254ea843/client/layout/index.jsx#L55) which isn't currently compatible with the Site Picker when it's shown in the SideBar. This PR disables `body` scrolling when the Site Picker is active which effectively disables the problematic logic so that the search input and two buttons in the Site Picker view are always visible. You can check https://github.com/Automattic/wp-calypso/issues/68251 for more details about the issue that this PR addresses. 

**If you think the Site Picker's scroll view (Site List) should be synced with the `#content` element, as we do for the regular `SideBar` Admin Menu, please add a comment.**

#### Testing Instructions

First, reproduce the issue on the `trunk` branch.

1. Open the Admin Dashboard at `/home/:site`. Make sure the SideBar is open 
2. Click the "Switch site" button to enable the Site Picker
3. Confirm you can see Sites search input, the "Manage sites" button and the "Add new site" button
4. Scroll up/down the content section, and you should see that the "Add new site" button is not on screen as per the video above

Now check out this branch and run your local Calypso deployment. Verify the issue is no longer present and that the "Add new site" button is always visible. You can try testing this using:
-  different screen sizes, including mobile view
- navigating from different pages e.g. `/home/.:site` -> `Switch site`, `/inbox/:site` -> `Switch site` etc. 
- different browsers
- different scroll positions on the `#content` element (e.g. scroll halfway, scroll to bottom etc.).  

Tested with Chrome and Firefox. 

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #

### CODE REVIEW

**Comment by mpkelly** [comment]
There appears to be a problem when using the Calypso Live link - so I moved this back to "In progress" to investigate.

File: client/layout/utils.ts [hunk 1]
```diff
@@ -17,6 +17,12 @@ export const handleScroll = ( event: React.UIEvent< HTMLElement > ): void => {
 	const secondaryElHeight = secondaryEl?.scrollHeight;
 	const masterbarHeight = document.getElementById( 'header' )?.getBoundingClientRect().height;
 
+	// if the Site Picker is shown, don't sync scrolling. The Site Picker has a
+	// nested scroll window which is not currently compatible with the sync logic here
+	if ( secondaryEl?.querySelector( '.site-selector__sites' ) ) {
+		return;
+	}
```
Comment (jsnajdr) [inline client/layout/utils.ts]: This condition kind of overlaps with the `active` variable in the `SidebarScrollSynchronizer` component that uses the handler. What if the `active` condition was enhanced with `&& layoutFocus !== 'sites'`? Then all the conditions are consolidated at one place. Will it work?

**Review by jsnajdr — COMMENTED** [review]
When trying to reproduce this bug, one thing strikes me as odd: when the site selector is active, the content area is being "disabled" with this style:

https://github.com/Automattic/wp-calypso/blob/trunk/client/layout/style.scss#L263-L268

But despite being disabled, it is still scrollable! What if we disabled the scrolling, seems to me that would also fix the bug? In a way that addresses the cause more directly?

To disable the scrolling, it works for me to set an `overflow: hidden` style on the `body` element. That's the one that scrolls.

**Comment by zaguiini** [comment]
I agree with @jsnajdr here.

Iterating upon his comment about making the content static (i.e. not scrollable), how about using flexbox to display a limited-height (almost the entire viewport height) scrollable site list instead of hooking into the scroll event?

File: client/layout/utils.ts (hunk 1 above)
Comment (mpkelly) [reply client/layout/utils.ts]: Good suggestion. I think it's better to move this up and use `layoutFocus`. 

>To disable the scrolling, it works for me to set an overflow: hidden style on the body element. That's the one that scrolls.

Do you mean to do this conditionally?

Comment (mpkelly) [reply client/layout/utils.ts]: I just tried to use `layoutFocus` but it doesn't always work. I agree it's better to have run conditions in one place, though. Currently, I have:
```js
const isNarrow = useBreakpoint( '<660px' );
const isNotShowingSitePicker = ! document.querySelector( '#secondary .site-selector__sites' );
const active = ! isNotShowingSitePicker && ! isNarrow && ! config.isEnabled( 'jetpack-cloud' );
```

**Comment by mpkelly** [comment]
> I agree with @jsnajdr here.
> 
> Iterating upon his comment about making the content static (i.e. not scrollable), how about using flexbox to display a limited-height (almost the entire viewport height) scrollable site list instead of hooking into the scroll event?

The Site Picker is mostly using `flex` already and has browser scrolling. Personally, I don't expect sync scrolling of the body/sidebar on any apps I use and would be in favour of removing this feature, which is quite complex. On the plus side, it helps users discover menu items that would otherwise get cut off.

File: client/layout/utils.ts (hunk 1 above)
Comment (mpkelly) [reply client/layout/utils.ts]: ...and the above code doesn't always work either so I am back with my original code. The `SidebarScrollSynchronizer` component doesn't update often enough for the logic to work there. I also want to see if there is a purely CSS-based fix.

**Comment by mpkelly** [comment]
It's trickier than I thought. There is also [this CSS ](https://github.com/Automattic/wp-calypso/blob/262c9458981e15997154fc400d4b154f254ea843/client/components/site-selector/style.scss#L174)which I believe is wrong now there is an extra `button`. But I don't think the solution is to increase this - Ideally, we'd remove it and have `flex` handle the height for us. 

```CSS
// The actual list of sites
.site-selector__sites {
	flex: 1;
	max-height: calc(100% - 93px);
```

**Comment by jsnajdr** [comment]
> Personally, I don't expect sync scrolling of the body/sidebar on any apps I use and would be in favour of removing this feature, which is quite complex.

The sync scrolling behavior has been adopted from WordPress Core `wp-admin`, as a part of the Nav Unification project. It's unlikely to go away any time soon, because that would make the Nav less unified.

The sync scrolling behavior is actually quite nice when it works perfectly. The `wp-admin` implementation is pretty good, but the Calypso one is still unfortunately bit quirky and I find interacting with it unpleasant at times. It would deserve some love.

> I just tried to use `layoutFocus` but it doesn't always work.

I'm wondering why it would not work: changing the `layoutFocus` Redux state is literally the very event that triggers display of the sites list in the sidebar. What exactly is the non-working behavior?

> The `SidebarScrollSynchronizer` component doesn't update often enough for the logic to work there.

Yes, the return value of `document.querySelector` can change, but there is nothing that would trigger a rerender of the React component that reads the value, so it doesn't notice the change. That was one of my motivations to suggest using React and Redux state changes to trigger disabling/enabing of the scroller, instead of reading from DOM.

> Do you mean to do this conditionally?

Yes, conditionally, when the `.layout.focus-sidebar` CSS class is active. To disable scrolling on the `body`, we might need to sync the `.focus-*` CSS classes to the `body` element, just like we already do with the `.is-section-*` and `.is-group-*` ones. The `BodySectionCssClass` component does that syncing.

**Comment by mpkelly** [comment]
Thanks for the extra context, @jsnajdr. 
>What exactly is the non-working behavior?

The problem persists, i.e. the fix didn't work, and you don't always see the buttons or the top input.

I think using `layoutFocus` did not work because the `SideBar` can be resized before you click the `Switch site` button. You can check this by going to **Appearance** > **Themes** and then scrolling a bit until you see the `SideBar` like this:
image
Now, if you scroll up a little and click the `Switch site` button, you will see that there aren't any buttons shown (at least on my Macbook).
Screenshot 2565-09-28 at 13 53 08

I am going to look more at this today.

**Comment by mpkelly** [comment]
I have modified this PR and it appears to work ok everywhere now. I used @jsnajdr's recommendation of hooking into the existing `BodySectionCssClass` component to add a `body` class which is then used to set `overflow: hidden` on the `body` when the `sites` layout is active. I needed to set the height of the `.site-selector` layout but was able to remove another `height:..` style in the same file. 

There's a bit of noise in the PR due to fixing "duplicate selector" issues.

File: client/components/site-selector/style.scss [hunk 2]
```diff
@@ -15,6 +15,7 @@
 	z-index: z-index("root", ".site-selector");
 	display: flex;
 	flex-direction: column;
+	height: calc(100vh - var(--masterbar-height));
```
Comment (zaguiini) [inline client/components/site-selector/style.scss:18]: Thanks for this!

**Review by zaguiini — APPROVED** [review]
I'm unable to reproduce the problematic behaviour in **production** WPCOM following the instructions given in issue 🤔 I've tested in Chrome and Brave, but the results are exactly the same as in the PR 😐

I am able to reproduce it in local Calypso, though. And this PR does fix the problem. Curious as to why this is happening only in development 💭 I'm glad you're fixing the issue, but at the same time I wonder what's different between the two environments...

Anyway, the PR does fix the problem, so it's a ✅ from me! 🥇

**Comment by mpkelly** [comment]
@zaguiini, thank you for testing this. It was using WordPress.com that I originally discovered the bug - although staging and not production because I have the proxy enabled mostly. I have just retried with the proxy disabled and still see the problem. It's possible that screen size and resolution could explain the difference - maybe try making your browser window smaller? To reproduce it, try starting from `/themes/<site>` and scroll down the theme's grid until you see the `SideBar` scroll move also. Then scroll the `SideBar` up just a little bit before clicking "Switch site". Here's a short video of me doing that:


https://user-images.githubusercontent.com/6851384/193489698-cf6a5bcf-c9c6-4210-9683-0e873e269679.mp4

**Comment by mpkelly** [comment]
This has been shipped just now.

**Comment by ebinnion** [comment]
This appears to be causing some issues on, at least, the site select on `/help/contact`. See conversation in Slack: p1665335799967009-slack-C0347E545HR

**Comment by mpkelly** [comment]
> This appears to be causing some issues on, at least, the site select on `/help/contact`. See conversation in Slack: p1665335799967009-slack-C0347E545HR

A fix was required for this. It's in PR https://github.com/Automattic/wp-calypso/pull/68801
