### PR TITLE
Staging Sites: Fix staging site address external link icon alignment

### LINKED ISSUE #99326: Staging Sites: External icon in link is not vertically aligned
### What

We observed that the external icon is not vertically aligned.

Image

### Why

During the Server Settings Walkthrough, we identified an opportunity to fix the alignment of the external icon.

pesfPa-1n1-p2

### How

_No response_

### PR DESCRIPTION
**Pull request by ivan-ottinger**
Fixes https://github.com/Automattic/wp-calypso/issues/99326.

## Proposed Changes

* fix external link icon styling

| Before | After |
|--------|--------|
| Markup on 2025-03-04 at 10:52:37 | Markup on 2025-03-04 at 10:51:42 | 

## Why are these changes being made?

These changes are made to fix the https://github.com/Automattic/wp-calypso/issues/99326 issue.

## Testing Instructions

1. Check out the PR branch and build the app with `yarn start`.
2. Head over to `http://calypso.localhost:3000/staging-site/{atomic-site-slug}` on an existing Atomic site and create a new staging site (if the site doesn't have any yet).
3. Review the external link icon. It should be formatted correctly. 

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by katinthehatsite** [comment]
The changes look good on my end and the icon is now aligned:

Screenshot 2025-03-04 at 11 19 16 AM

**Review by katinthehatsite — APPROVED** [review]

File: client/sites/tools/staging-site/components/staging-site-card/card-content/manage-staging-site-card-content.tsx [hunk 1]
```diff
@@ -80,6 +80,12 @@ const ActionButtons = styled.div( {
 	},
 } );
 
+const ExternalIcon = styled( Icon )( {
+	verticalAlign: 'middle',
```
Comment (wojtekn) [inline client/sites/tools/staging-site/components/staging-site-card/card-content/manage-staging-site-card-content.tsx]: As we are using flex to style parent items, we could consider following the flex approach here, too, by setting alignment on parent span element.

**Review by wojtekn — APPROVED** [review]
It fixes the issue.

**Review by nightnei — CHANGES_REQUESTED** [review]
Vertical align is provided by default in Button component, so we can fix vertical align with just removing <span> wrapper.

Also, there are weird things - we have class for it and even we have vertical align for SVG, but it's not used... 🤔
https://github.com/Automattic/wp-calypso/blob/2cf726151df5524eea8952a51da35e06bd6271c3/client/sites/tools/staging-site/style.scss#L16

So, there is no need to add extra styles and we should just remove <span> wrapped and additionally we should fix underlying issue - why ccs is ignored.

File: client/sites/tools/staging-site/components/staging-site-card/card-content/manage-staging-site-card-content.tsx (hunk 1 above)
Comment (ivan-ottinger) [reply client/sites/tools/staging-site/components/staging-site-card/card-content/manage-staging-site-card-content.tsx]: Thanks for feedback, Wojtek.

> As we are using flex to style parent items, we could consider following the flex approach here, too, by setting alignment on parent span element.

I have experimented with different approaches yesterday (including flex), but the results were not as expected on smaller screens where the staging site URL can get into two lines, e.g.:

Markup on 2025-03-04 at 12:30:40

**Comment by ivan-ottinger** [comment]
> Vertical align is provided by default in Button component, so we can fix vertical align with just removing wrapper.
> 
> Also, there are weird things - we have class for it and even we have vertical align for SVG, but it's not used... 🤔
> 
> https://github.com/Automattic/wp-calypso/blob/2cf726151df5524eea8952a51da35e06bd6271c3/client/sites/tools/staging-site/style.scss#L16
> 
> So, there is no need to add extra styles and we should just remove wrapped and additionally we should fix underlying issue - why ccs is ignored.

Thanks for the feedback, Vova.

Originally, I thought we can get rid of that `span` as well, but it is there to properly format the icon to the same line with the staging site URL on narrow screens - where the staging site URL gets into two lines:

Markup on 2025-03-04 at 12:47:53

**Comment by nightnei** [comment]
@ivan fixed https://github.com/Automattic/wp-calypso/pull/100766

Screenshot 2025-03-04 at 13 09 05

File: client/sites/tools/staging-site/components/staging-site-card/style.scss [hunk 2]
```diff
@@ -0,0 +1,14 @@
+.tools-staging-site__site-url {
+	word-wrap: break-word;
+	text-decoration: none;
+
+	&.is-link {
+		text-decoration: none;
+	}
```
Comment (nightnei) [inline client/sites/tools/staging-site/components/staging-site-card/style.scss]: It's redundant, anyway it's teh same selector but we need bigger specificity
```suggestion
	text-decoration: none;
```

**Review by nightnei — APPROVED** [review]

**Comment by nightnei** [comment]
@ivan-ottinger approved, but left one last comment https://github.com/Automattic/wp-calypso/pull/100762#discussion_r1979322344

**Comment by ivan-ottinger** [comment]
> I took a look closer at the issue and decided to push commit, to simplify explanation https://github.com/Automattic/wp-calypso/pull/100766
@ivan-ottinger feel free to merge it, if you don't have comments about it

> @ivan-ottinger fixed #100766
> 
> Screenshot 2025-03-04 at 13 09 05

Thank you for your input and also sharing your commit, Vova. I appreciate it. 🙂 

I think it is a good call to move the styling closer to the component so I made that change.

When it comes to removing the `span`, I would rather keep it in place instead of adding negative margin.

> @ivan-ottinger approved, but left one last comment https://github.com/Automattic/wp-calypso/pull/100762#discussion_r1979322344

Thank you! I will address that comment in a second.

File: client/sites/tools/staging-site/components/staging-site-card/style.scss (hunk 2 above)
Comment (ivan-ottinger) [reply client/sites/tools/staging-site/components/staging-site-card/style.scss]: Good catch, I have fixed it in https://github.com/Automattic/wp-calypso/pull/100762/commits/54e292c5bb0c4ede26f9e68e4685f8e7e393e81b.

**Comment by nightnei** [comment]
> When it comes to removing the span, I would rather keep it in place instead of adding negative margin.

@ivan-ottinger Oh, I just noticed that you haven't included my proposition for removing span.

Regarding negative margin - yes, there is a common rule (recommendation) in CSS world that negative margins are not good, but every CSS oportunity has its own place to be used and it's one of them, since this negative margin is for inline element and encapsulated inside inline-block, so it's more than safe to use negative margin here. Moreover, it's the decision between "negative margin" VS "positive margin + hack with additional span".

But even if we talk about not using the negative margin here, then we can easily achieve it with [this](https://github.com/Automattic/wp-calypso/pull/100776). Actually, it's what extra span does around CSSOM - it wraps children to override `display: flex` for the parent (Button) and it's kinda workaround, when the direct solution is override `display: flex` directly for the parrent.

It's not critical, but if we are here now, let's completely clean up things around this place in codebase https://github.com/Automattic/wp-calypso/pull/100776
