### PR TITLE
Gutenberg: Use Calypso Classic on AT sites if the Classic Editor plugin is active

### LINKED ISSUE #32676: Gutenberg: Atomic sites redirect to the WP Admin classic editor
Originally reported on p3fqKv-6Hh-p2 (#comment-10150)

**Steps to reproduce**
- Install the Classic Editor plugin on an Atomic site.
- In Calypso, go to `/posts/:atomicSiteSlug`.
- Click on the "Add New Post" button.

**Expected behavior**
Since the Classic Editor plugin, we have to consider the user has opted out of Gutenberg and therefore load the Calypso Classic editor.

**Actual behavior**
Calypso redirects the user to the WP Admin Classic editor.

### PR DESCRIPTION
**Pull request by mmtr**
#### Changes proposed in this Pull Request

I noticed that multiple selectors were not able to detect if the Classic Editor plugin was installed because we didn't have any plugin stored on the state. 

I realized this was due to the lack of any dispatched action fetching the plugin and probably the cause of the issue described on p3fqKv-6Hh-p2 (#comment-10150). 

Since we need the plugins in different parts of the application (on page controllers, on individual components) I decided to include the `QueryJetpackPlugins` query component in the `Layout` component, so the state will always reflect the installed plugins.

#### Testing instructions

* Install the Classic Editor plugin on an Atomic site.
* In Calypso, go to `/posts/:atomicSiteSlug`.
* Click on the "Add New Post" button.
* Make sure you see the Calypso Classic editor.

Fixes #32676

### CODE REVIEW

**Comment by obenland** [comment]
Hm, in my tests I'm getting a redirect loop. Is this the same thing you ran into with the other PR?
My setup is an Atomic site with Jetpack bleeding edge and calypso.live of this PR.

File: client/state/selectors/is-gutenberg-enabled.js [hunk 1]
```diff
@@ -32,7 +33,11 @@ export const isGutenbergEnabled = ( state, siteId ) => {
 				'>='
 			)
 		) {
-			return isEnabled( 'gutenberg' ) && ! isVipSite( state, siteId );
+			return (
+				isEnabled( 'gutenberg' ) &&
+				! isVipSite( state, siteId ) &&
+				! isPluginActive( state, siteId, 'classic-editor' )
```
Comment (dmsnell) [inline client/state/selectors/is-gutenberg-enabled.js]: we should differentiate here between "not active" and "not loaded yet" which I don't believe that `isPluginActive()` does. could this be behind the loop that @obenland found?

**Comment by dmsnell** [comment]
> I noticed that multiple selectors were not able to detect if the Classic Editor plugin was installed 

@mmtr as a general rule we always want to make sure that any use of queried data is paired in the same module with the query component. as you found out, missing the query component leads to data not being available.

sometimes we want to preload the data in a higher part of the React tree, but nesting the query in lower components should be benign and can prevent a refactor of a parent or ancestor component from breaking its children.

can you verify that each place we're relying on this selector that we have the query component?

---

here's another idea: that plugins code is pretty old and might involve some work to update. using `requestHttpData()` would give us the `pending` state we need to differentiate load vs. not-active, but could we move Jetpack versioning requirements into the selected editor API?

can we know on the server when we say `selectedEditor: 'gutenberg'` that a site doesn't have the requisite version or module activated and then revert to a different editor value in those cases? if we switch to calypsoify for example we should be able to say in PHP: "it's a Jetpack site and the version is too old, send `calypsoify-gutenberg` as the selected editor rather than `gutenberg`"?

getting this into the selected editor API would collapse _two things_ and two API requests into _one thing_ and it would remove the need to reassemble the logic in the client.

if this seems workable to you (@kwight your thoughts?) then I'd be happy to talk more about how to make it possible if you wanted.

**Comment by mmtr** [comment]
@dmsnell I totally agree with you on having the components tied to the query components they need and I actually started adding `QueryJetpackPlugins` to those components. But then, I noticed we also need this data on a [controller](https://github.com/Automattic/wp-calypso/blob/3a7349c9dffc82a41e89f20ed7db06a8f22a282a/client/post-editor/controller.js#L189) and I don't know what is the best way to deal with it.

I decided to place the query component in the `Layout` component because it seemed to be high enough and it's similar to what we do with other components preloading data we need on controllers (i.e. `<QuerySelectedEditor>`).

---

I like your alternative approach although I don't know if we can check the Jetpack version or the plugins installed in the WP.com side of a JP site. Anyway, that change wouldn't be trivial (new versioned endpoint performing the version/plugins checks, bump Calypso's usage of that API endpoint to the new version, change Calypso to handle the new selected editor) so I wonder if we can have a solution based on selectors and query components since that will probably take less time.

**Comment by mmtr** [comment]
> Is this limited to Atomic or will it work with all Jetpack sites?

It should work with both Jetpack and Atomic.

**Comment by mmtr** [comment]
> Hm, in my tests I'm getting a redirect loop. Is this the same thing you ran into with the other PR?
> My setup is an Atomic site with Jetpack bleeding edge and calypso.live of this PR.

@obenland it looks indeed like the same problem I had with the other PR, but I'm not able to reproduce it here. Does still happen to you after the rebase? In all your sites?

**Comment by obenland** [comment]
It doesn't, no! :)

**Comment by dmsnell** [comment]
> But then, I noticed we also need this data on a controller and I don't know what is the best way to deal with it.

In the controller we only need dispatch [the actual request](https://github.com/Automattic/wp-calypso/blob/master/client/state/plugins/installed/actions.js#L323):

```js
context.store.dispatch( fetchPlugins );
```

> I decided to place the query component in the Layout component

I missed that in review. probably it's best to not perform the check there as that page is rendered on every view. if we're not in the editor we shouldn't need it.

> I like your alternative approach although I don't know if we can check the Jetpack version or the plugins installed in the WP.com side of a JP site.

this is key to changing the way we do it. of course we can make HTTP calls from PHP to the Jetpack site and we may even have a special mechanism to talk to the remote end, plus caching on dotcom.

that is, I think if we can do it in Calypso then we should be able to do it in dotcom and much faster (data-center HTTP call to remote site plus blocking the first API call until it's back vs. make a call from the client then make a second call based on the results of the first).

the only variable is how much work would it take to do that. being unfamiliar with Jetpack I don't know. maybe someone on Jetpack could help us understand if it's easier than we think.

> wouldn't be trivial (new versioned endpoint performing the version/plugins checks, bump Calypso's usage of that API endpoint to the new version, change Calypso to handle the new selected editor) 

it's probably not nearly as much work as it appears. we wouldn't need to bump any versions. since this API is on dotcom and it's only being requested from Calypso we can control both sides.

that is, today we can transform `calypsoify-gutenberg` into `gutenberg` on the API entry point then after the server changes happen we can open that back up. point is, shouldn't be much work if the server-side is doable.

---

don't stress out about it. if it seems too big to chew we can move on. my purpose in pointing it out is to try and keep related API data in one central place on the server so we can keep logic out of the clients (multiple clients) for easier maintenance and more consistency.

> selectors and query components since that will probably take less time.

only if they already exist. we should not be creating new query components. if we want to we should be creating new data types based on `requestHttpData()` instead

👍

**Comment by mmtr** [comment]
Thanks @dmsnell for your inputs. I went ahead and merged this to avoid issues with staled data. I'll try to move the data preload to a better place (that doesn't require to make the request on every Calypso page) while working on https://github.com/Automattic/wp-calypso/issues/32709.

**Comment by mmtr** [comment]
> probably it's best to not perform the check there as that page is rendered on every view. if we're not in the editor we shouldn't need it.

I analyzed the code trying to identify all the components using the affected selectors (the ones needing the Jetpack plugins in the state) and I believe that the `Layout` component is not a bad place for this query component given they are all rendered along different sections and not only in the editor.

We are using `isPluginActive` on the `isCalypsoifyGutenbergEnabled` and `isGutenframeEnabled` selectors. And these selectors are used by the `gutenberg` and `post-editor` controllers and by other selectors: `getGutenbergEditorUrl`, `getEditorUrl`, `getEditorDuplicatePostPath` and `isGutenbergEnabled`.

These are the components using all those selectors grouped by sections:
- /my-sites: `Page`, `ManageMenu`, `SiteMenu`, `WpcomChecklistComponent`, `Draft`, `Pages`, `PostTypeListEmptyContent`, `PostTypeList`, `PostActionsEllipsisMenuEdit`, `PostActionsEllipsisMenuDuplicate`, `PublishConfirmation`.
- /blocks: `InlineHelpPopover`, `PostItem`.
- /post-editor: `EditorGutenbergBlocksWarningDialog`, `EditorGutenbergOptInDialog`, `EditorGutenbergOptInNotice`, `EditorGutenbergOptInSidebar`.
- /layout: `MasterbarPublish`.

> it's probably not nearly as much work as it appears. we wouldn't need to bump any versions. since this API is on dotcom and it's only being requested from Calypso we can control both sides.

We're also using this API at least on the desktop app (not sure if any mobile app is using it), so I think we need to handle the versioning if we want to take the approach of delegating responsibility to the server).
