### PR TITLE
Revert using component state for Image Editor Crop and fix underlying issue

### LINKED ISSUE #8286: Image Editor: Large Image Performance
Let's do a profiling pass on why the image editor chugs along on large images. If you find any bottlenecks, let's try to find work arounds.

### PR DESCRIPTION
**Pull request by lamosty**
Properly fixes #8286. Reverts #8296 and adds fix for underlying issue.

Initially, I thought this has something to do with using Redux for storing Image Editor Crop position/sizing as on each action dispatch, a lot of unrelated components to image editor are refreshed (even though their props were not updated).

However, I also noticed that this didn't happen some time ago (e.g. a month as said here: #8377). I went ahead and located the commit which introduced the regression. Turns out it was **I** who did this with [this line of code](https://github.com/Automattic/wp-calypso/pull/7913/commits/de1742e31fdcf215e64c4de1558f51e0e5ec2bf3#diff-d2ae10d6ec20ea5af5d82e33b56db5e6R66)! I apologize.

## Testing Instructions

1. Make sure the image editor works fine after applying this revert PR (cropping, rotating, changing aspect ratio, flipping, etc);
2. Follow the testing instructions in #8296;
3. Make sure that the issue described in #7988 is not back.

/cc @gwwar

### CODE REVIEW

File: client/post-editor/media-modal/image-editor/image-editor-canvas.jsx [hunk 1]
```diff
@@ -68,7 +68,9 @@ const MediaModalImageEditorCanvas = React.createClass( {
 	},
 
 	componentWillReceiveProps( newProps ) {
-		this.getImage( newProps.src );
```
Comment (lamosty) [inline client/post-editor/media-modal/image-editor/image-editor-canvas.jsx]: This was causing the image editor (+ media modal) slowness on any action as image had to be loaded and processed on any re-render. For some reason, I thought that [this lifecycle method](https://facebook.github.io/react/docs/component-specs.html#updating-componentwillreceiveprops) is called only on receiving **new** props. My bad..

**Comment by gwwar** [comment]
👍 Tested this and verified the perf diff. We still have long frames of around 200ms on applyCrop during mouseUp but we can try shortening that in future PRs

File: client/post-editor/media-modal/image-editor/image-editor-canvas.jsx (hunk 1 above)
Comment (gwwar) [inline client/post-editor/media-modal/image-editor/image-editor-canvas.jsx]: I must have missed this in the PR too since the placeholders removed a bunch of src checks. 😄

**Comment by lamosty** [comment]
Thanks for the review @gwwar!
