### PR TITLE
Comments: fall back to site post link until deep reader links for jetpack are supported

### LINKED ISSUE #18319: Comments: Reader post deep link does not work for Jetpack sites.
Whoops we added reader deep links for posts, but these don't appear to work for Jetpack sites. Let's investigate why. If reader doesn't support this as well, let's fall back to the site link.

screen shot 2017-09-27 at 9 26 38 am

### PR DESCRIPTION
**Pull request by gwwar**
This PR fixes #18319 by updating the post/comment link to point at the site post or site comment instead of the deep reader link. At the moment it doesn't appear that the reader is opening deep links from Jetpack sites correctly.

screen shot 2017-09-28 at 5 13 23 pm

### Testing Instructions
- `localStorage.debug= 'calypso:analytics*'` to enable analytics debugging
- Navigate to calypso.localhost:3000/comments
- Select a simple site with comments
- Expand a comment 
- Click on the post/comment link
- `calypso_comment_management_article_opened` or `calypso_comment_management_comment_opened` analytics event fires as expected
- Verify that we navigate to the Calypso reader with the post or comment open
- Navigate to calypso.localhost:3000/comments
- Select a Jetpack site with comments
- Expand a comment 
- Click on the post/comment link
- `calypso_comment_management_article_opened` or `calypso_comment_management_comment_opened` does NOT fire
- Verify that we navigate to the site post or site comment

### CODE REVIEW

File: client/blocks/comment-detail/index.jsx [hunk 1]
```diff
@@ -190,6 +199,17 @@ export class CommentDetail extends Component {
 		}
 	}
 
+	trackDeepReaderLinkClick = () => {
+		const { isJetpack, parentCommentContent } = this.props;
```
Comment (rodrigoi) [inline client/blocks/comment-detail/index.jsx]: any reason to destructure just these two props?

Comment (gwwar) [reply client/blocks/comment-detail/index.jsx]: I tend to do this for 2 or more, no hard reasoning.

**Comment by gwwar** [comment]
Thanks for the review @rodrigoi!

File: client/blocks/comment-detail/index.jsx (hunk 1 above)
Comment (rodrigoi) [reply client/blocks/comment-detail/index.jsx]: I thought there was a new rule I wasn't aware of, like, destructure variables but not functions 😌
