### PR TITLE
Jetpack Plans: Support monthly billing cycle in purchase detail page

### LINKED ISSUE #9344: Manage Purchases: Jetpack monthly plans display wrong billing cycle label
This site has a plan that is billed monthly, but the purchases page displays a 'yearly' label. These labels need to be conditionalized to display the appropriate label based on the billing cycle:

screen shot 2016-11-14 at 9 44 04 am

cc @johnHackworth @tyxla

### PR DESCRIPTION
**Pull request by tyxla**
This PR fixes #9344, where the monthly plans are not supported properly when displaying the plan price. 

To test:

* Checkout this branch.
* Load `/me/purchases/$site/`, where `$site` is one of your Jetpack sites that has a paid monthly plan.
* Click the monthly plan purchase.
* Verify it displays `{price}` / month instead of `{price}` / year (where `{price}` is the monthly price of the plan).
* Load `/me/purchases/$site/`, where `$site` is one of your Jetpack sites that has a paid yearly plan.
* Click the yearly plan purchase.
* Verify it displays `{price}` / year like it did before.

/cc @johnHackworth @rickybanister

### CODE REVIEW

**Comment by rickybanister** [comment]
Thanks for taking care of this!

File: client/me/purchases/manage-purchase/index.jsx [hunk 1]
```diff
@@ -289,8 +290,13 @@ const ManagePurchase = React.createClass( {
...
 		}
 
-		return this.translate( '%(currencySymbol)s%(amount)d %(currencyCode)s {{period}}/ year{{/period}}', {
-			args: { amount, currencyCode, currencySymbol },
+		return this.translate( '%(currencySymbol)s%(amount)d %(currencyCode)s {{period}}/ %(period)s{{/period}}', {
+			args: {
+				amount,
+				currencyCode,
+				currencySymbol,
+				period: productSlug && isMonthly( productSlug ) ? 'month' : 'year'
```
Comment (tyxla) [inline client/me/purchases/manage-purchase/index.jsx]: Makes sense. I've separated the logic from the `translate`call.

**Comment by johnHackworth** [comment]
works great! :+1: :ship:
