### PR TITLE
Login: Preserve redirect_to param if it already exists

### LINKED ISSUE #93522: `redirect_to` param in `/log-in` page is reset in some cases
### Quick summary

The `/log-in` page sometimes sets a `redirect_to` param when arriving on the login page from another WP.com page. There's a bug that causes the param to reset in some instances. 

### Steps to reproduce

There are a few ways to reproduce this issue:

**Method 1**

1. Go to the logged-out landing page https://wordpress.com/newsletter/
2. Click "Start my newsletter" CTA
3. In the `/start` page, click on "Continue with email". Notice the page URL has the `redirect_to` prop with the value `redirect_to=%2Fsetup%2Fnewsletter%2FnewsletterSetup%3Fref%3Dnewsletter-lp`. 
4. Enter an email address that has an existing WP.com account.
5. You will now be taken to the `/log-in` page. Notice in the URL that the `redirect_to` query param has already changed value to `redirect_to=https%3A%2F%2Fwordpress.com%2Fsetup%2Faccount`.
6. Complete signing in to the account.

**Method 2**

1. Repeat steps 1-5 above.
2. Click on "Email me a login link" in the `/log-in` page.
3. In the `/log-in/link/...` page, click on "Enter a password instead".
4. You'll be back on the `/log-in` page. Now complete signing into the account.

### What you expected to happen

I expected to be taken to the newsletter signup flow after successfully signing in.

**NOTE: Please also verify with other sign in methods such as Google / Apple / GitHub / "Login via app" methods on whether the `redirect_to` param value is retained.**

### What actually happened

I was taken to My Home page because the `redirect_to` prop was reset to a path that does not exist.

### Impact

This impacts existing users because we're not taking them to the intended destination. This bug also affects our metrics as some of our funnels track signup step -> onboarding step completion rate. If the user is directed to the Customer Home page, then it artificially decreases the step completion rate.

### PR DESCRIPTION
**Pull request by agrullon95**
Related to https://github.com/Automattic/wp-calypso/issues/93522
Fixes https://github.com/Automattic/wp-calypso/issues/93522

## Proposed Changes

* Update social first signup form to preserve `redirect_to` param if it already exists

## Why are these changes being made?

* When going through a flow such as the newsletter flow as a logged out, youre prompted to signup or login before you can begin the flow. A `redirect_to` param is set to return the user back to the newsletter flow after they login/signup, but that param is overridden. Due to this `redirect_to` param change, the user is not returned to the correct location after logging in.

## Testing Instructions

* Checkout branch or use the live link.
* Log out of WordPress.com.
* Go to `wordpress.com/newsletter` and click the `Start my newsletter` button. 
* Click `Continue with email`, enter an existing email, and complete the login flow. 
* Verify you are redirected to the newsletter flow (`setup/newsletter/newsletterSetup`).
* Test the other login methods. Repeat the steps until you reach the login screen (`Continue with email`) and test the other login methods ( `Login via app`, `Continue with Github`, etc.).

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/blocks/signup-form/signup-form-social-first.tsx [hunk 1]
```diff
@@ -147,6 +148,10 @@ const SignupFormSocialFirst = ( {
 				  }
 				: {};
 
+			const redirectToParam =
```
Comment (alshakero) [inline client/blocks/signup-form/signup-form-social-first.tsx:154]: Is it reasonable to use `queryArgs` object instead?

**Review by kevin940726 — APPROVED** [review]
Tested and worked for me!
