### PR TITLE
Retain cursor focus on user-mentions block when the popover opens

### LINKED ISSUE #37625: User mentions: cursor focus lost after typing '@'
This is a regression.

#### Steps to reproduce
1. Internal users only: browse to a P2 post in Reader (full post, e.g. /read/feeds/:feed_id/posts/:post_id)
2. Press '@' and start typing for user matches
3. Try and continue typing for a specific match

#### What I expected

After typing '@', I continue seeing matches as I add more text. I am then able to choose one by pressing 'Enter'.

#### What happened instead

After the '@' I cannot continue typing. I have to manually place the cursor back after the '@' to find user matches.

#### Browser / OS version

Chrome/Mac

#### Screenshot / Video

Screen Shot 2019-11-15 at 15 48 07

### PR DESCRIPTION
**Pull request by glenpadua**
Typing "@" in a textarea wrapped with the withUserMentions HOC would open a popover containing a
user suggestion list that would cause the textarea to lose focus, requiring the user to manually
place the cursor back to continue default behavior. Adding a default prop isFocusEnabled which
defaults to true to check if the deferred focusPopover method should be called.

#### Changes proposed in this Pull Request

* Add default prop isFocusEnabled
* Add check before calling focusPopover
* Default isFocusEnabled for Popover to true
* Pass isFocusEnabled as false to the popover in the UserMentions component

#### Testing instructions

* Visit http://calypso.localhost:3000/devdocs/blocks/user-mentions
* Press '@' and start typing for user matches
* User suggestions show up and textarea remains in focus, allowing the user to perform keyboard operations as expected.

Fixes #37625

### CODE REVIEW

**Comment by glenpadua** [comment]
I was unable to test the fix where the issue was originally reported as I'm not sure where it shows up 🤔 

> Internal users only: browse to a P2 post in Reader (full post, e.g. /read/feeds/:feed_id/posts/:post_id)

**Comment by bluefuton** [comment]
Thanks for tackling this @glenpadua! As this component is used throughout Calypso, I think we have to be cautious about removing this. There may be other places using `Popover` without `PopoverMenu` that rely on this behaviour.

Can we try adding a prop that is provided to the `Popover` component to turn off the focus instead, that defaults to enabled?

**Comment by glenpadua** [comment]
@bluefuton That sounds fair. Will do that then!

**Comment by glenpadua** [comment]
@bluefuton I've added a default prop called `isFocusEnabled`. Let me know if you have a better name for it and if I need to make any more changes!

File: client/components/popover/index.jsx [hunk 1]
```diff
@@ -38,6 +38,7 @@ class PopoverInner extends Component {
 		className: '',
 		closeOnEsc: true,
 		isRtl: false,
+		isFocusEnabled: false,
```
Comment (bluefuton) [inline client/components/popover/index.jsx:41]: As the popover is currently always focussed, can we default this to `true`, then pass in `isFocusEnabled={ false }` for the user mentions popover?

Comment (glenpadua) [reply client/components/popover/index.jsx]: @bluefuton Have made the change! 👍

**Review by bluefuton — APPROVED** [review]
Looks good to me. Thanks for fixing this @glenpadua! 🚢
