### PR TITLE
Subscriptions management: Add 'Subscription not found' state

### LINKED ISSUE #77305: `/subscriptions/site/:blogId`: Add error state for when query to get blog details fails

### PR DESCRIPTION
**Pull request by mashikag**
Screen Shot 2023-05-25 at 16 17 35

Closes https://github.com/Automattic/wp-calypso/issues/77305

## Proposed Changes

* Display the error notice when fetching a site subscription details is unsuccessful
* Handle both type of response errors
    1. Where the server itself is reporting an error. This is the classical HTTP error response.
    2. Where the endpoint is reporting an error. This is an error that is wrapped in a payload of 200 "OK" response.

## Testing Instructions

1. Test the classical HTTP error response:
    * Go to http://calypso.localhost:3000/subscriptions/site/a to test for the classical HTTP error response
    * Ensure the error message is displayed

2. Test the classical HTTP error response:
    * Go to http://calypso.localhost:3000/subscriptions/site/$site-id, where the `$site-id` is a valid ID of a site that you are not subscribed to (it can be an existing site, or not, but it is important that it matches blog ID regex on the server side), e.g. https://wordpress.com/subscriptions/site/12345678.
    * Ensure the error message is displayed

3. Test for no regressions
    * Go to http://calypso.localhost:3000/subscriptions/site/$site-id, where the `$site-id` is a valid ID of a site that you  subscribed to
    * Ensure the error message is not displayed 

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by ivan-ottinger** [comment]
I am reviewing this PR now.

**Review by ivan-ottinger — APPROVED** [review]
The changes look good to me and they work as expected. 👍🏼👍🏼

- tested the `/sites` page as well
- did not observe any regressions; and observed only the errors that should have been observed based on the test instructions 😉

**Comment by ivan-ottinger** [comment]
Oh, I just noticed that optimistic updates don't seem to be working for logged-in user for some reason.

File: client/landing/subscriptions/components/site-subscription-page/site-subscription-page.tsx [hunk 1]
```diff
@@ -140,59 +39,23 @@ const SiteSubscriptionPage = () => {
...
+						>
+							Subscription not found
+						</Notice>
+					) : (
+						<SiteSubscriptionDetails
+							name={ data.name }
+							subscriberCount={ data.subscriber_count }
+							dateSubscribed={ data.date_subscribed }
+							siteIcon={ data.site_icon }
+							blogId={ data.blog_ID }
```
Comment (ivan-ottinger) [inline client/landing/subscriptions/components/site-subscription-page/site-subscription-page.tsx]: This should help:

```suggestion
							blogId={ blogId }
```

Comment (mashikag) [reply client/landing/subscriptions/components/site-subscription-page/site-subscription-page.tsx]: Thanks @ivan-ottinger so much for spotting this, and debugging it. It helped me to save some time. 🙇  You are right that the usage of the `data.blog_ID` was the issue here.  For internal users, the `data.blog_ID` type is `number`, while the `blogId` is string. Using blog ID's of different types in react-query key is problematic.

Comment (mashikag) [reply client/landing/subscriptions/components/site-subscription-page/site-subscription-page.tsx]: The issue should be resolved with my latest commit. 🙇
