### PR TITLE
Plugin Details: Fix plugin sites list for paid plugins

### LINKED ISSUE #59292: Marketplace: Paid plugin details in all sites view
In all sites view "Sites List" doesn't render. It should render with a "Pay and install" button for eligible sites. The list shouldn't show Jetpack self hosted sites. 

figma: oU6nEIeiKSg8CayhEtgR6b-fi-6757%3A53821

SS 2021-12-16 at 11 59 48

### PR DESCRIPTION
**Pull request by cpapazoglou**
#### Changes proposed in this Pull Request

- Displays available sites in all sites view
- Adds price
- Allows for "Purchase and activate"

#### Testing instructions

|Before | After|
|-------|------|
|SS 2021-12-22 at 15 30 06|SS 2021-12-22 at 15 30 23|

- visit `https://wordpress.com/plugins/woocommerce-subscriptions`
- make sure that price is shown
- try buying the plugin for a site
- no Jetpack / Simple sites should appear in the list

Fixes #59292

### CODE REVIEW

File: client/my-sites/plugins/plugin-install-button/index.jsx [hunk 1]
```diff
@@ -147,6 +148,24 @@ export class PluginInstallButton extends Component {
...
+		const product_slug = plugin?.variations?.[ variationPeriod ]?.product_slug;
+
+		return (
+			<span className="plugin-install-button__install embed">
+				<Button
+					href={ `/checkout/${ selectedSite.slug }/${ product_slug }?redirect_to=/marketplace/thank-you/${ plugin.slug }/${ selectedSite.slug }#step2` }
+				>
+					<Gridicon key="plus-icon" icon="plus-small" size={ 18 } />
+					<Gridicon icon="plugins" size={ 18 } />
+					{ translate( 'Purchase and activate' ) }
```
Comment (a8ci18n) [inline client/my-sites/plugins/plugin-install-button/index.jsx:163]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **42** times:
`translate( 'Purchase and Activate &raquo;' )` *ES Score: 7*

**Review by gavande1 — APPROVED** [review]
I've tested as per the instructions and it works as expected. Also, tested by visiting the free plugin and there was no regression. Great work @cpapazoglou.

LGTM 👍
