### PR TITLE
E2E: reduce flakiness in `Site Assembler` spec.

### LINKED ISSUE #80699: Flaky E2E: Site Assembler header, section, and footer validation fails intermittently
### Spec file

specs/onboarding/ftme__site-assembler.ts

### TeamCity ID

10605893

### Logs

```
locator.click: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for getByRole('listbox', { name: 'Block patterns' }).getByRole('option').nth(1).frameLocator('iframe').locator('.block-editor-iframe__body')
  locator resolved to <body tabindex="0" contenteditable="false" class="bloc…>…</body>
attempting click action
  waiting for element to be visible, enabled and stable
element is not visible - waiting...
============================================================
    at SiteAssemblerFlow.click [as selectLayoutComponent] (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/flows/site-assembler-flow.ts:50:5)
    at Object.selectLayoutComponent (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/onboarding/ftme__site-assembler.ts:96:24)
```

### PR DESCRIPTION
**Pull request by worldomonation**
Fixes https://github.com/Automattic/wp-calypso/issues/80699.

## Proposed Changes

This PR refactors both the Site Assembler spec and the SiteAssemblerFlow POM to be less flaky.

Key changes:
- change behavior of `selectLayoutComponent` to select based on name, instead of index.
- add network interception to abort all requests for placeholder images.
- add explicit wait for component to be successfully inserted into the preview pane.
- move the counting method into the `SiteAssemblerFlow` POM.

## Testing Instructions

Ensure the following build configurations are passing:
  - [x] Pre-Release E2E

image

Locally tested in a loop of 20 iterations focused solely on selecting the site assembler components passed without issue.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: test/e2e/specs/onboarding/ftme__site-assembler.ts [hunk 1]
```diff
@@ -83,43 +83,31 @@ describe( 'Site Assembler', () => {
...
 		it( 'Select "Footer"', async function () {
-			await startSiteFlow.selectLayoutComponentType( 'Footer' );
-			await startSiteFlow.selectLayoutComponent( 1 );
+			await siteAssemblerFlow.selectLayoutComponentType( 'Footer' );
+			await siteAssemblerFlow.selectLayoutComponent( 'Simple centered footer' );
 
-			expect( await assembledPreviewLocator.count() ).toBe( 3 );
-		} );
-
-		it( 'Click "Save and continue" and land on the Site Editor', async function () {
```
Comment (youbrokesomething) [inline test/e2e/specs/onboarding/ftme__site-assembler.ts:115]: @worldomonation I agree that loading the site editor here probably doesn't have value, but should we check to ensure the 'save and continue' function works by clicking the button and verifying no errors are thrown? Or should we suggest to the dev that worked on this spec to cover that outside of E2E?

Comment (worldomonation) [reply test/e2e/specs/onboarding/ftme__site-assembler.ts:115]: @youbrokesomething Yes, good catch - I had removed this portion while I was stress testing and forgot to add it back in. Thanks for noticing!

Comment (worldomonation) [reply test/e2e/specs/onboarding/ftme__site-assembler.ts:115]: Also, according to the folks at Team Lego there is value in actually saving then checking the editor loads.
p1692260392212649-slack-CRWCHQGUB

File: packages/calypso-e2e/src/lib/flows/site-assembler-flow.ts [hunk 2]
```diff
@@ -35,18 +35,53 @@ export class SiteAssemblerFlow {
...
+	 *
+	 * @param {string} name Exact name of the component to select.
 	 */
-	async selectLayoutComponent( index = 0 ): Promise< void > {
-		await this.page
+	async selectLayoutComponent( name: string ): Promise< void > {
+		// To reduce network load times, abort any request for
+		// placeholder images.
+		await this.page.route( '**/*.png', ( route ) => {
+			route.abort( 'aborted' );
```
Comment (youbrokesomething) [inline packages/calypso-e2e/src/lib/flows/site-assembler-flow.ts:50]: Attempting to abort requests for placeholder images is failing for me locally.

Edit: Never mind! Rebuilding fixed it.

**Review by youbrokesomething — APPROVED** [review]
LGTM and runs well! 🚢

**Comment by fushar** [comment]
Thanks for fixing this!!! FYI @Automattic/lego 😄
