### PR TITLE
Onboarding - Remove progress bar from /site-setup flows

### LINKED ISSUE #73036: Pattern Assembler - Progress bar gets shorter in the write flow
The progress bar at the top of the window in the pattern assembler screen doesn't work in the write flow, it gets too short.

**Reproduction steps**

- Create a new site
- Select the goal "Write and Publish"
- Access the assembler from the bottom of the design picker
- Check the length of the progress bar at the top of the window

|Current|Expected|
|-------|--------|
|Image|Image|

Note that this flow has two more steps: `options` and `bloggerStartingPoint`.

Related https://github.com/Automattic/wp-calypso/pull/64586

## Dev Tasks 

- [X] Remove it from `/site-setup` flows. See pbxlJb-3wV-p2
- [X] Post a P2 to share that we are removing it due to its fragility until we develop a better version that can adapt dynamically to the changes in the onboarding steps.

### PR DESCRIPTION
**Pull request by miksansegundo**
Related to https://github.com/Automattic/wp-calypso/issues/73036 https://github.com/Automattic/wp-calypso/issues/72071 https://github.com/Automattic/wp-calypso/issues/70205 https://github.com/Automattic/wp-calypso/issues/72073
Close https://github.com/Automattic/wp-calypso/issues/73036 https://github.com/Automattic/wp-calypso/issues/70205

## Proposed Changes

* Remove the progress bar from the general onboarding flows in `/setup/site-setup`

Due to the fragility of the progress bar, we are removing it from the `site-setup` flow until we have a more maintainable version. See pbxlJb-3wV-p2

See how the progress of the bar is handled in [use-site-setup-flow-progress.ts](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/hooks/use-site-setup-flow-progress.ts) and the steps in the [site-setup-flow.ts](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/site-setup-flow.ts#L68).

**Why only from `site-setup` flow?**

Because there are many different flows and URLs, see them in [/stepper/declarative-flow](https://github.com/Automattic/wp-calypso/tree/trunk/client/landing/stepper/declarative-flow), I'd like to reduce the impact of the changes and start by removing the progress bar only from the `site-setup`. 

Let me know if this should be done otherwise or if there are other considerations.

## Testing Instructions

* Create a new site from the dashboard or `/start`
* Continue until the goals screen (this is the first screen of the general onboarding flows)
* Mark different goals and continue
* Verify that the progress bar doesn't appear on any screen other after the goals screen

|Before|After|
|------|-----|
|**No goal selected**Screenshot 2566-02-22 at 14 59 09**Write and publish**Screenshot 2566-02-22 at 14 59 24**Sell online**Screenshot 2566-02-22 at 14 59 35**Promote myself or business**Screenshot 2566-02-22 at 14 59 49**Get a website quickly [Premium]**Screenshot 2566-02-22 at 15 00 04**Import my existing website content**Screenshot 2566-02-22 at 15 00 13**Other**Screenshot 2566-02-22 at 15 00 24|**No goal selected**Screenshot 2566-02-22 at 15 08 15**Write and publish**Screenshot 2566-02-22 at 15 08 15**Sell online**Screenshot 2566-02-22 at 15 08 15**Promote myself or business**Screenshot 2566-02-22 at 15 08 15**Get a website quickly [Premium]**Screenshot 2566-02-22 at 15 00 04**Import my existing website content**Screenshot 2566-02-22 at 15 10 39**Other**Screenshot 2566-02-22 at 15 08 15|

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: client/landing/stepper/declarative-flow/internals/index.tsx [hunk 1]
```diff
@@ -146,14 +150,15 @@ export const FlowRenderer: React.FC< { flow: Flow } > = ( { flow } ) => {
...
 								) }
-								<ProgressBar
-									// eslint-disable-next-line wpcalypso/jsx-classname-namespace
-									className="flow-progress"
-									value={ progressValue * 100 }
-									total={ 100 }
-									style={ progressBarExtraStyle }
-								/>
-
+								{ flow.name !== SITE_SETUP_FLOW && (
```
Comment (arthur791004) [inline client/landing/stepper/declarative-flow/internals/index.tsx:153]: Could you add the comment to this PR to provide more context? thanks!

**Review by taipeicoder — APPROVED** [review]
The change looks good to me 🙂
+1 to @arthur791004's note of adding a comment of why we're excluding the site setup flow.

Let's wait a day and see if there's any push back in your post. Otherwise, this seems good to go.

**Comment by miksansegundo** [comment]
Thanks for the feedback! Let's wait a day before merging.

**Review by arthur791004 — APPROVED** [review]
👍
