### PR TITLE
Checkout: Make Jetpack masterbar logo visible on pending page

### LINKED ISSUE #66139: Jetpack logo in checkout pending page masterbar is black-on-black
If you view the post-checkout "pending" page for a Jetpack site (or for the `no-site` placeholder when your primary site is a Jetpack site), the masterbar product logo is invisible.

Screen Shot 2022-08-01 at 4 32 33 PM

To reproduce:

- You'll need a Jetpack site.
- Visit https://wordpress.com/checkout/thank-you/YOUR-SITE-SLUG-HERE/pending/12345

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Proposed Changes

The post-checkout "pending" page is shown very briefly after a purchase is complete. Its masterbar shows a logo for either WordPress.com or Jetpack, depending on the identity of the selected site. The WordPress.com logo is light and the Jetpack logo is dark. The background of the masterbar behind this logo is dark normally, but is light if the site is Jetpack and is on page in the checkout "section". However, the "pending" page is not in the checkout section; it is in the "checkout-pending" section. The result is that the (dark) Jetpack logo will be shown on the (dark) masterbar background, rendering it invisible.

This PR modifies the styles so that the light masterbar background will show on the checkout pending section as well.

This works for Jetpack sites, but there's an edge case that this PR also fixes. If there is no selected site, the masterbar will show the logo for the user's primary site instead. If this site is a Jetpack site, it will use the dark Jetpack logo. However, the background of the masterbar is only light if the layout is for a Jetpack site, and the `Layout` component does not check the user's primary site like the masterbar does.

This PR modifies the checkout masterbar to use its own classnames to determine if the Jetpack styles should be applied.

Fixes https://github.com/Automattic/wp-calypso/issues/66139

Before:

jetpack-masterbar-logo-before

After:

Screen Shot 2022-08-01 at 5 06 54 PM

#### Testing Instructions

First test the style changes:

- You'll need a Jetpack site.
- Visit https://wordpress.com/checkout/thank-you/YOUR-SITE-SLUG-HERE/pending/12345 for that site.
- Verify that the Jetpack icon in the masterbar is visible.

To test the Layout changes:

- Make a Jetpack site your primary site. You can do this on https://dashboard.wordpress.com/wp-admin/index.php?page=my-blogs
- Visit https://wordpress.com/checkout/thank-you/no-site/pending/12345.
- Verify that the Jetpack icon in the masterbar is visible.

### CODE REVIEW

**Comment by sirbrillig** [comment]
From what I can tell, there's not much risk by assigning a fallback `siteId` in the `Layout`, but I'd be curious if @Automattic/team-calypso-frameworks has any opinions.

File: client/layout/index.jsx [hunk 1]
```diff
@@ -324,7 +325,10 @@ export default withCurrentRoute(
 		( state, { currentSection, currentRoute, currentQuery, secondary } ) => {
 			const sectionGroup = currentSection?.group ?? null;
 			const sectionName = currentSection?.name ?? null;
-			const siteId = getSelectedSiteId( state );
+			// Falls back to using the user's primary site if no site has been selected
+			// by the user yet
+			const currentSelectedSiteId = getSelectedSiteId( state );
+			const siteId = currentSelectedSiteId || getPrimarySiteId( state );
```
Comment (tyxla) [inline client/layout/index.jsx]: We generally use the `getSelectedOrPrimarySiteId()` selector when we want to fall back to the primary site if no other one is currently selected.

**Review by tyxla — CHANGES_REQUESTED** [review]
I'd generally recommend against doing that change so generically for everything in `Layout` - subtle bugs could be introduced because of the different behavior suggested.

The difference is difficult to spot when we have persisted state. For example, if you've previously navigated through a route that has some sort of site selection or sets the current site ID, and even in a fresh browser session visit https://wordpress.com/me?debug you'll notice that logging `state.ui.selectedSiteId` refers to the ID of the last blog you were working with. However, if you clean that persisted state, and visit `/me` directly, it will be `null`. In that scenario, in this PR, we'll use the primary site for everything under `Layout`, and that might be unexpected and cause some unexpected requests. In `trunk`, though, on `/me` no unnecessary additional requests will be done when the `siteId` is `null` (for example, to `/sites/:siteId/features`). I consider that a regression - this data won't really be used on that page, because there's not even a current site context there.

As pointed in another comment, when we want to fall back to the primary site, we've been using the `getSelectedOrPrimarySiteId()` selector, and it makes the fallback behavior much more obvious.

So what I'd recommend here would be to try to keep `siteId` as it is in `Layout`, but also add the result of `getSelectedOrPrimarySiteId` as a separate prop, and use that prop only where really necessary to fall back to the primary site ID. That way we could avoid subtle bugs now and in the future.

**Comment by sirbrillig** [comment]
Thanks for the feedback @tyxla!

I think you have a good point. FWIW I had copied the `siteId` calculation from the following location (maybe that code should also differentiate between `siteId`, `currentSelectedSiteId`, and `primarySiteId`?)

https://github.com/Automattic/wp-calypso/blob/2af81d745bd37486d4c07c2ee71079207ca00fd2/client/layout/masterbar/logged-in.jsx#L556-L559

I altered the changes to `Layout` to use the selected-or-primary-site only for the `isJetpack` calculation, which is used (only) to set the `is-jetpack-site` className that I need here. I didn't also provide the new prop to the component because there seems to be no need at the moment.

Does that seem safer? I don't love that there is disagreement between `MasterbarLoggedIn` and `Layout` about what is a Jetpack site when no site is selected and this could definitely have unintended side effects (although there could already be other bugs as a result of the disagreement). 🤔 It might be possible to change the CSS code for the masterbar background to be injected by the masterbar instead of the layout...

**Comment by sirbrillig** [comment]
I had an idea. Each of the places that were having this problem were specific to the masterbar inside checkout on a Jetpack site; the logic that decides to show the Jetpack logo also is there. I modified that component, `CheckoutMasterbar`, to add its own classNames which I was then able to use to replace the `.is-section-checkout` and `.is-jetpack-site` selectors in the CSS. This seems to resolve the issue in https://github.com/Automattic/wp-calypso/issues/66139 without having to change the behavior of `Layout` (which still could be problematic somewhere but is outside the scope of this edge case).

**Review by tyxla — APPROVED** [review]
Looks great to me 👍 

Thanks for considering an alternative approach with less impact on unrelated functionality.

One thing I've noticed is that the Jetpack logo is a bit packed in the checkout masterbar, but this is pre-existing, so it's not related nor is blocking to this PR.

🚢
