### PR TITLE
Domains: Improve copy for TLDs unavailable for registration on WordPress.com

### LINKED ISSUE #6810: Domain Search: TLD error messages
#### Steps to reproduce
1. Starting at URL: WordPress.com/domains
2. Search for a domain that is not registered and ends in a TLD we don't offer
3. Error reads as follows:
screen shot 2016-07-14 at 4 17 59 pm
4. While this is true, we should specify that this isn't a TLD we offer.

A message like 

> We currently don't offer domains ending in .nl, but you can register it elsewhere and map it here

With a link to buy mapping, plus the list of alternatives below.

I know this might be a pain to maintain, but just saying you can't register it here is pretty general and not too helpful.

### PR DESCRIPTION
**Pull request by klimeryk**
Fixes #6810

Before, the error message was not very helpful (and it was shown as an intimidating error):

screen shot 2016-08-05 at 13 34 21

Now, the copy has been improved (thank you, @ranh!) and the notice has `info` severity:

screen shot 2016-08-05 at 13 33 45

The `Learn more` link points to `https://en.support.wordpress.com/map-existing-domain/`.

/cc @aidvu @umurkontaci for code review
/cc @spncrb 

Test live: https://calypso.live/?branch=fix/tld-error-message

### CODE REVIEW

**Comment by spncrb** [comment]
Product looks good to me 👍

File: client/components/domains/register-domain-step/index.jsx [hunk 1]
```diff
@@ -541,10 +539,20 @@ const RegisterDomainStep = React.createClass( {
 				severity = 'info';
 				break;
 			case 'not_registrable':
-				if ( domain.indexOf( '.' ) ) {
-					message = this.translate( 'Sorry but %(domain)s cannot be registered on WordPress.com.', {
-						args: { domain: domain }
-					} );
+				const tldIndex = domain.lastIndexOf( '.' );
```
Comment (umurkontaci) [inline client/components/domains/register-domain-step/index.jsx]: What about SLDs? (.co.uk e.g.)

File: client/components/domains/register-domain-step/index.jsx [hunk 2]
```diff
@@ -541,10 +539,20 @@ const RegisterDomainStep = React.createClass( {
...
+				if ( tldIndex !== -1 ) {
+					message = this.translate(
+						'To use a domain ending with {{strong}}%(tld)s{{/strong}} on your site, ' +
+						'you can register it elsewhere and then add it here. {{a}}Learn more{{/a}}.',
+						{
```
Comment (umurkontaci) [inline client/components/domains/register-domain-step/index.jsx]: "add it here" sounds a bit vague, what if they are already trying to "add" it here? I think we should say something like "map it here" with a link that jumps to mapping page with the domain name.

File: client/components/domains/register-domain-step/index.jsx (hunk 1 above)
Comment (spncrb) [inline client/components/domains/register-domain-step/index.jsx]: that's a good point since .co.uk results in 
screen shot 2016-08-05 at 9 56 28 am

Comment (umurkontaci) [inline client/components/domains/register-domain-step/index.jsx]: There's a `isSubdomain` function in https://github.com/Automattic/wp-calypso/blob/master/client/lib/domains/index.js#L114 which might be useful

Comment (klimeryk) [inline client/components/domains/register-domain-step/index.jsx]: Yes, I realized that it will do that for SLDs - but the sentence remains true. The domains "ends with .uk". I'm not familiar with any SLD which we don't allow registrations but allow registrations for the TLD of that SLD (ugh, hope that's clear). So, for `co.uk` we don't support `.co.uk` nor do we support `.uk`.
Why not just use the SLD in the notice? I can't figure out an easy way to reliably extract SLDs, if present. Picking just the TLD is safer.

File: client/components/domains/register-domain-step/index.jsx (hunk 2 above)
Comment (klimeryk) [inline client/components/domains/register-domain-step/index.jsx]: That's the copy @ranh provided in https://github.com/Automattic/wp-calypso/issues/6810#issuecomment-233879552. I'm just but a lowly JavaScript programmer - who am I to question His wise words? 😜

File: client/components/domains/register-domain-step/index.jsx (hunk 1 above)
Comment (umurkontaci) [inline client/components/domains/register-domain-step/index.jsx]: The whole point of the message is about the domains we don't support though. A straightforward, non-optimized way could be to count the dots and make use of the `isSubdomain` function;
```
if (dots.length == 1) {
  // TLD
} else if ( isSubdomain( domain ) ) {
  // TLD (also subdomain)
} else {
  // SLD (grab last 2 dots)
}
```

File: client/components/domains/register-domain-step/index.jsx (hunk 2 above)
Comment (ranh) [inline client/components/domains/register-domain-step/index.jsx]: I don't think "map" is commonly understood. We use it a lot, but if it's not necessary, I think it's better to avoid it.

If they are already trying to add it here, this notice still works. The important part is just that they first register it elsewhere.

If you think it will help, we can make that even clearer:

> To use a domain ending with .nl to your site, you can register it elsewhere first and then add it here. Learn more.

File: client/components/domains/register-domain-step/index.jsx (hunk 1 above)
Comment (klimeryk) [inline client/components/domains/register-domain-step/index.jsx]: The reason why I've not opted for such a solution is because unfortunately it's not as straightforward (as it usually is with domains). The `isSubdomain` function is very simple and dumb - it checks for 2-3 characters long tokens between dots and assumes those are TLD/SLDs. But there are many >3 character long SLDs (`.school.za`, `.csiro.au`, `.film.hu`, [etc.](https://en.wikipedia.org/wiki/Second-level_domain)) and there are many 2-3 character long domain names (cnn.com is an obvious one, az.pl is another example). The only reliable way is to have a hardcoded list of all the possible SLDs - something we can't afford on the frontend and doesn't seem worth a trip to the backend. Hence my proposal to just use the TLD part. It's not ideal, but I think given the situation is the optimal solution (it's better to stick to something we are more certain of than to confuse the user with guessing if we're dealing with a TLD/SLD/subdomain).

File: client/components/domains/register-domain-step/index.jsx (hunk 2 above)
Comment (klimeryk) [inline client/components/domains/register-domain-step/index.jsx]: I've changed the copy per your suggestion, Ran. Hope that solves your concern, Umur :)

File: client/components/domains/register-domain-step/index.jsx (hunk 1 above)
Comment (umurkontaci) [inline client/components/domains/register-domain-step/index.jsx]: I still think handling `co.uk.` is more important than some super rare domains. But if you are feeling strongly towards handling it this way I think that's alright as well.

**Comment by umurkontaci** [comment]
Our node version has been bumped to 6.1.0 since this branch has been created. So it needs a rebase :)

**Comment by umurkontaci** [comment]
I did the rebase everything seems OK. 

This is good to go, is there possibility of a delay when we try to determine whether the domain is registered or not? Like when the user registers a domain elsewhere and comes to our site right after and sees this message? In a sense, they already came here to "add" their domain.

It's certainly better than what we had before but I think it's something to think about for future.

File: client/components/domains/register-domain-step/index.jsx (hunk 1 above)
Comment (aidvu) [inline client/components/domains/register-domain-step/index.jsx]: You could add this info in the error response from the server? You get the TLD extracted there anyway.

**Comment by klimeryk** [comment]
That's a good point. It's probably highly dependent on the registrar - how fast they update/propagate. @spncrb, can you keep an eye out for such cases and let me know if they are confusing for users?

File: client/components/domains/register-domain-step/index.jsx (hunk 1 above)
Comment (klimeryk) [inline client/components/domains/register-domain-step/index.jsx]: Yeah, that's probably the best to do it - I'll try to do that in a separate patch in the meantime (though, I admit, it's not high priority 😉).
