### PR TITLE
Editor: Update page templates on theme change

### LINKED ISSUE #5387: Editor: page templates stuck from previous theme
I was doing some theme testing and switching between themes, as a result I noticed the templates got stuck. Initially I thought there was something wrong with the theme I was testing, however it wasn't the case. On switching to another theme, the same issue. 

Here is the video of what happened:
https://cldup.com/vdKVeKaqPF.mp4

Note, those templates don't exist in the theme, so actually clicking meant it didn't change. This only vanished when I did a hard refresh. This was despite coming in and out, saving and previewing. I even went into different sections, to change the theme, then came back. Only on refreshing did this clear up.

I have tried this with a few different themes and it happens every time - I need to refresh to get it to stick. The test site I am using is using Incognito Chrome (potentially the issue maybe?) and also a new user to test theme UX with. The site has only had 2 blog posts made and is verified: tuxthemereview.wordpress.com

### PR DESCRIPTION
**Pull request by jeremeylduvall**
Fixes #5387 

Ideally, we could move the page templates store to Redux, but this could act as a temporary fix. I connected the PageTemplatesData component to the currentTheme state. `currentTheme` is then passed in as a prop using [`getCurrentTheme`](https://github.com/Automattic/wp-calypso/blob/3ede1a2bef5bbe24baa7d929338c23603f5dc6e0/client/state/themes/current-theme/selectors.js#L3). In `componentWillReceiveProps`, we're checking if `this.props.currentTheme.stylesheet !== this.activeTheme`. Both of these URLs will be in the format `pub/hemingway-rewritten` for free themes or `premium/affinity` for premium themes. If they're equal, nothing happens. If they're not equal, we trigger a fetch and update `this.activeTheme` accordingly so we don't refetch unnecessarily. 

Using `this.props.currentTheme.stylesheet` feels a bit weird/non-intuitive, but it's the best comparison I could find since we're using `theme_slug` elsewhere as `this.activeTheme`. We don't have [a corresponding `theme_slug` on in the theme details currently.](https://github.com/Automattic/wp-calypso/blob/3ede1a2bef5bbe24baa7d929338c23603f5dc6e0/client/state/themes/theme-details/reducer.js)

## To Test
1. Checkout this branch and get it up and running
2. Activate "Scratchpad" on your site from http://calypso.localhost:3000/design/site.wordpress.com. Scratchpad doesn't have page templates.
3. Click "Add" to start a new page. Check under Page Options. You shouldn't see a page template option.
4. Navigate back to choose a new theme (don't refresh)
5. Activate Hemingway Rewritten (has page templates)
6. Click "Add" to start a new page and check under Page Options again. You should see page templates.

## GIF
(I reversed the steps in the GIF)
themechange

### CODE REVIEW

**Comment by aduth** [comment]
@jeremeylduvall : What was the reason for switching this to "In Progress"? Is it ready for a proper review or did you run into issues?

**Comment by jeremeylduvall** [comment]
@aduth The current version does work. Had a few improvements in mind though after chatting with @drewblaisdell . 

Since we now can monitor the theme from `componentWillReceiveProps`, I'm going to work on removing reference to `this.activeTheme` and compare `this.props.currentTheme` with `nextProps.currentTheme`. `_fetchTemplatesIfThemeChanges` is also redundant because we can decide if we should fetch new data when receiving props as well. Will work on those and get a new version up and running by tomorrow morning.

**Comment by jeremeylduvall** [comment]
Flipping this back to "Needs Review." I was hoping to remove reference to `this.activeTheme` and move most of the logic for when we should fetch new data to `componentWillReceiveProps` while removing the need for `_fetchTemplatesIfThemeChanges()`. 

I assume `_fetchTemplatesIfThemeChanges()` was introduced (back in 9579-gh-calypso-pre-oss) to update the page templates if a user has the editor open in one tab and changes themes in another tab. I thought I could remove this thinking `nextProps.currentTheme` would get the new theme in that circumstance, but it actually needs a refresh so my original idea won't work currently.

Everything mentioned in the original post (including how it works) still applies.

File: client/components/data/page-templates-data/index.jsx [hunk 1]
```diff
@@ -49,6 +51,10 @@ export default React.createClass( {
 
 	componentWillReceiveProps( nextProps ) {
 		if ( nextProps.siteId === this.props.siteId ) {
+			if ( this.props.currentTheme && this.props.currentTheme.stylesheet !== this.activeTheme ) {
```
Comment (aduth) [inline client/components/data/page-templates-data/index.jsx]: This should be checking `nextProps` I think, to compare the _incoming_ theme against the currently tracked active theme.

**Comment by jeremeylduvall** [comment]
Thanks @aduth. Definitely correct. Updated now. I did leave the fetch as `PageTemplatesActions.fetchPageTemplates( this.props.siteId );` instead of `PageTemplatesActions.fetchPageTemplates( nextProps.siteId );` since `this.props.siteId` and `nextProps.siteId` would be equal at this stage.

**Comment by aduth** [comment]
Looks good 👍  Took for a spin and newly introduced fetching logic triggered as I'd have expected when returning to the page editor after switching themes.
