### PR TITLE
Make custom domain callout in "Change your site address" modal appear more link-like.

### LINKED ISSUE #98717: Make "add a custom domain" link appear as link in the "Change your site address" modal.
### Context and steps to reproduce

In the change your site address modal, we provide users a link to add a custom domain. That link doesn't look like a link.

## Steps to reproduce
- Go to `domains/manage/{site}`
- Click the three dots in the Actions column
- Click change site address.

## Screenshot
Image

## Solution

Make it look like a link and only link "add a custom domain" instead of the whole sentence.

### Site owner impact

More than 60% of the total website/platform users

### Severity

Minor

### What other impact(s) does this issue have?

_No response_

### If a workaround is available, please outline it here.

_No response_

### Platform

_No response_

### PR DESCRIPTION
**Pull request by StevenDufresne**
Fixes #98717

## Proposed Changes

This PR updates `Did you want to add a custom domain?` in the "Change your site address" modal to appear visually as a link and to only link the action specific to the outcome of clicking the link. When a user clicks on the link, it goes into the domain search.

## Screenshots

| Before | After |
|--------|--------|
| Screenshot 2025-01-22 at 10 09 58 AM | Screenshot 2025-01-22 at 11 04 14 AM | 

## Why are these changes being made?

* It doesn't appear like a link.
* Linked questions typically navigate to documentation but this goes to the domain search.

## Testing Instructions

With an account that doesn't have a domain.

* Go to `domains/manage/{site}`
* Click three dots in "Action" column
* Verify that the link matches the Screenshots above.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/blocks/site-address-changer/index.jsx [hunk 1]
```diff
@@ -462,9 +462,11 @@ export class SiteAddressChanger extends Component {
...
 					{ ! hasNonWpcomDomains && (
 						<div className="site-address-changer__info-custom-domain">
-							<a href={ addDomainPath } onClick={ this.handleAddDomainClick }>
-								{ translate( 'Did you want to add a custom domain instead?' ) }
-							</a>
+							{ translate( 'Did you want to {{a}}add a custom domain{{/a}} instead?', {
+								components: {
+									a: <a href={ addDomainPath } onClick={ this.handleAddDomainClick } />,
+								},
+							} ) }
```
Comment (mmtr) [inline client/blocks/site-address-changer/index.jsx:469]: This will require a new translation, so it will temporary appear untranslated until the new string is translated:

Before | After
--- | ---
Screenshot 2025-01-31 at 10 59 17 | Screenshot 2025-01-31 at 10 59 03

To prevent that, you can use the new `fixMe` util (see p7H4VZ-5bl-p2):

```
i18n.fixMe( {
    text: 'Did you want to {{a}}add a custom domain{{/a}} instead?',
    newCopy: translate( 'Did you want to {{a}}add a custom domain{{/a}} instead?', { ... } ),
    oldCopy: translate( 'Did you want to add a custom domain instead?' ),
}
```

Alternatively, you can also add the "String freeze" label to this PR and wait for translations to be completed before merging (see PCYsg-3hI-p2#calypso).

**Review by mmtr — COMMENTED** [review]
Tests well for me! Left a note about translations.

File: client/blocks/site-address-changer/index.jsx (hunk 1 above)
Comment (StevenDufresne) [reply client/blocks/site-address-changer/index.jsx:469]: Lovely, thanks for that information!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17224252

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @StevenDufresne for including a screenshot in the description! This is really helpful for our translators.
