### PR TITLE
Bundled Themes: Highlights the Business plan

### LINKED ISSUE #72158: Bundle Themes: The upgrade nudge highlights the Premium plan
Clicking on the upgrade nudge in the Theme page redirects the user to the plan page with the Premium plan highlighted. However, the bundle themes require a Business plan.

#### Steps to reproduce

1. Navigate to `/theme/thriving-artist` on a free site
2. Click on the upgrade nudge
Screen Shot 2023-01-16 at 12 03 15
3. It will take you to the plan page, with the Premium Plan highlighted

#### What I expected

The Business plan to be highlighted

#### What happened instead

The Premium plan was highlighted

#### Context / Source

Slack report: p1673879352751749-slack-C0Q664T29

### PR DESCRIPTION
**Pull request by valterlorran**
#### Proposed Changes

* Fixes the redirect to the plan page. It defaulted to the Premium theme as the suggested theme. Now we suggest the Business plan, which is the plan needed for bundled Themes

#### Testing Instructions

* Navigate to `/theme/tsubaki/{YOUR-SITE}`
* Click on the banner
* Make sure the Business plan is suggested.

Closes #72158

### CODE REVIEW

File: client/my-sites/theme/main.jsx [hunk 1]
```diff
@@ -790,7 +790,9 @@ class ThemeSheet extends Component {
 		if ( ! isLoggedIn ) {
 			plansUrl = localizeUrl( 'https://wordpress.com/pricing' );
 		} else if ( siteSlug ) {
-			plansUrl = plansUrl + `/${ siteSlug }/?plan=value_bundle`;
+			const plan =
+				isExternallyManagedTheme || isBundledSoftwareSet ? 'business-bundle' : 'value_bundle';
```
Comment (sixhours) [inline client/my-sites/theme/main.jsx]: I would use the plan constants here, too.

**Review by sixhours — APPROVED** [review]
Minor note on using the plan constants, otherwise this works as described!
