### PR TITLE
FSE: Add default template content and error logging to better handle template population failures

### LINKED ISSUE #35077: Full Site Editing: Log template population failures and provide last fallback
Currently if the template population fails while activating the Modern Business theme it does so silently and the user is not aware that their site is not in a fully functional state.

Let's log this to Kibana, with debug information, but also provide some default basic fallback content.

### PR DESCRIPTION
**Pull request by glendaviesnz**
#### Changes proposed in this Pull Request

* Add default template content if call to API to get content fails
* Add error log when call to get template content fails

#### Testing instructions
*  Apply this patch to FSE dev enviroment
* Temporarily change [domain name here](https://github.com/Automattic/wp-calypso/blob/5589ce100348b02bbd02ed5845cae6c63540cc48/apps/full-site-editing/full-site-editing-plugin/full-site-editing/templates/class-wp-template-inserter.php#L76) to an invalid domain name, eg. public-api-bogus.wordpress.com
* Build FSE plugin and sync to sandbox
* Also apply D32445-code to sandbox
* Sandbox API, and also domain of test FSE site you are about to create on Horizon with new user via `/start/test-fse`
* Create a new FSE site with the domain name you sandboxed through the CfT flow
* Check that the header and footer templates were created but with the default content below instead of the default theme content
* Also check that a logstash log was added for the failure by searching kibana for `a8c_fse`

Screen Shot 2019-09-04 at 12 09 43 PM

Fixes #35077

### CODE REVIEW

**Comment by gwwar** [comment]
I think we might not be able to fit this into the 0.7 release, but let's try for 0.7.1 or 0.8

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing/templates/class-wp-template-inserter.php [hunk 1]
```diff
@@ -124,6 +127,35 @@ private function fetch_retry( $request_url, $request_args = null, $attempt = 1 )
...
+	public function get_default_header() {
+		return '<!-- wp:a8c/site-description /-->
+			<!-- wp:a8c/site-title /-->
+			<!-- wp:a8c/navigation-menu /-->
+			<!-- wp:paragraph -->
+				<p>' .
+				__(
+					'The theme did not activate correctly so it may not look identical to the demo site. 
+					You are still able to edit the header and footer content to suit your needs.',
+					'full-site-editing'
```
Comment (gwwar) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing/templates/class-wp-template-inserter.php]: Let's drop the warning message. Folks will end up having a published site with this visible, which isn't super helpful.

If we'd like to notify users, would recommend a plain notice component.

**Comment by gwwar** [comment]
@vindl @apeatling what do you think about just inserting a default value here as a fallback if our three API template population requests fail?

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing/templates/class-wp-template-inserter.php (hunk 1 above)
Comment (glendaviesnz) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing/templates/class-wp-template-inserter.php]: I have dropped the warning message. I can't see an easy way to get a notification from this point in the process to a notice component on the front-end without setting a cookie, or saving some info to the database that can be picked up when the editor loads - I suggest we circle back on this if the trial indicates that a lot of users are ending up in this state.

**Comment by gwwar** [comment]
Code looks reasonable to me! If folks don't have other feedback and can help manually test, you should be all set @glendaviesnz. I can circle back to manually test tomorrow if folks don't chime in.

**Comment by noahtallen** [comment]
Unfortunately I'm struggling to test this! I'll come back to this again tomorrow, but for some reason, the horizon flow is just hanging indefinitely for me when it says "hooray, your site will be ready shortly." I think a rebase would also be good to get all the latest changes in here :)

For some reason, a site which did make it through the flow didn't seem to have any header/footer inserted, but that might be because of my environment, so I'll try again tomorrow :)

**Comment by Copons** [comment]
A nitpick: we have been using the short `[ ]` notation for arrays (introduced in PHP 5.4) instead of `array()`, since WP needs at least PHP 5.6.

In my [follow up](https://github.com/Automattic/wp-calypso/pull/36267) to this PR, I've used `[ ]` for all the logs, including the one that I've copied straight from here, so feel free to ship this as-is, and leave the nitpick fix to #36267 🙂

**Comment by noahtallen** [comment]
> My issue right now is that template parts (correctly added to the site) don't show up in the page editor.

Looks like we're tracking this here: https://github.com/Automattic/wp-calypso/issues/36364. Though for some reason, I think it would be resolved with the latest version of FSE. I guess we'll see!

**Comment by noahtallen** [comment]
(Rebased to hopefully fix the tests :))

**Comment by noahtallen** [comment]
Fantastic! Merging this for Glen since he's out. This way, we can keep up in the related PRs :)
