### PR TITLE
Login: Fix inability to log in with Internet Explorer

### LINKED ISSUE #14213: Login: IE11: nothing happens after clicking Log In button for 2FA accounts
Using IE11.953.14393.0 on Windows 10:

- visit `/log-in` and enter credentials for an account that does not have 2FA enabled.
- note that you'll be logged in as you should.
- log and go back to `/log-in` and enter credentials for an account that does have 2FA enabled.
- note that after clicking Log In, nothing happens. No errors in the console.

### PR DESCRIPTION
**Pull request by stephanethomas**
This pull request fixes #14213 in order to allow users to log in again with Internet Explorer from the new `Login` page. To be more specific, it actually fixes an `Object doesn't support property or method 'includes'` error that was triggered upon submitting credentials (unfortunately this error wouldn't appear in the browser's console) because we don't polyfill `Array.includes()`.
  
#### Testing instructions
 
1. Run `git checkout fix/login-with-ie` and start your server, or open a [live branch](https://calypso.live/?branch=fix/login-with-ie)
2. Open the [`Login` page](http://calypso.localhost:3000/log-in) in an incognito window on Internet Explorer
3. Check that you can log in and that you are redirected to the [`Reader` page](http://calypso.localhost:3000)
 
#### Reviews
 
- [x] Code
- [ ] Product

### CODE REVIEW

**Comment by scruffian** [comment]
Code 👍 

Can't test :)

File: client/blocks/login/index.jsx [hunk 1]
```diff
@@ -3,6 +3,7 @@
  */
 import React, { Component, PropTypes } from 'react';
 import { connect } from 'react-redux';
+import includes from 'lodash/includes';
```
Comment (aduth) [inline client/blocks/login/index.jsx]: It's fine (and preferred) to import from Lodash selectively, i.e.

```js
import { includes } from 'lodash';
```

See: #6539

Comment (gziolo) [inline client/blocks/login/index.jsx]: Good catch!

**Comment by blowery** [comment]
Looks good. There's no need for includes though, you can just use a `Set` and `has`.

```
const twoFactorAuthTypes = new Set( [ ... ] );

if ( twoFactorAuthTypes.has( authType) {}
```

**Comment by blowery** [comment]
Testing
