### PR TITLE
Revert "Fix: Sites created through the ecommerce flow should be private"

### LINKED ISSUE #38824: New website: No WooCommerce plugin installed for the new website with eCommerce plan
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start
2. Create eCommerce new site (with eCommerce plan) under wordpress.com domain. 
3. Pay with credits.
4. Go to website admin.

#### What I expected
I expected the WooCommerce plugin to be installed and the website has some initial config for online-store. Or an invitation is expected at the dashboard for initial config.

#### What happened instead
The site looks like an ordinary blog

#### Browser / OS version
Google Chrome Version 79.0.3945.117 , OSX Catalina (10.15.2)

#### Screenshot / Video
Admin menu
image

The site view
image

Site plan page
image

#### Context / Source
Tried to create a test woocommerce site for learning and experiments.
Feel free to ping me in a8c slack for details (vbelolapotkov)

### PR DESCRIPTION
**Pull request by jblz**
Reverts Automattic/wp-calypso#38372

Reinstates the variable new site `blog_public` setting as per #35320 (& #34193 prior).

See discussion: p1579016110098700-slack-CCS1W9QVA

If eCommerce sites are created private, there's a chance that they'll be blocked from going Atomic when the upgrade succeeds. 

For now, let's just continue creating sites that select the eCommerce plan during signup as public.

### Automated tests

`npm run test-client client/state/selectors/test/should-new-site-be-private-by-default.js client/state/selectors/test/get-new-site-public-setting.js`

### Manual tests

* Run this branch
* Create a new site from `/start` with the eCommerce plan selected (don't complete the purchase yet)
  * It should be created as public
* Complete the purchase
  * It should be taken Atomic

* Create a new site from `/start` with any other plan selected
  * It should be created as private

Fixes #38824

### CODE REVIEW

File: client/lib/signup/site-type.js [hunk 1]
```diff
@@ -165,6 +165,7 @@ export function getAllSiteTypes() {
 			siteTopicLabel: i18n.translate( 'What type of products do you sell?' ),
 			customerType: 'business',
 			purchaseRequired: true,
+			forcePublicSite: true,
```
Comment (michaeldcain) [inline client/lib/signup/site-type.js]: Can we leave a comment here as a warning for other devs until we can get some e2e's in place?

**Comment by michaeldcain** [comment]
@jblz: I've updated the PR to use the plan instead of site type. This should be ready for review.

**Comment by jblz** [comment]
As the PR author, it won't let me mark this approved, but it's working well for me.  Thanks very much for spotting the issue w/ the Site type & plan not matching & for taking this over, @michaeldcain .  Cheers!

**Comment by jblz** [comment]
Not sure about the e2e tests -- restarted the workflow to see if it goes through
