### PR TITLE
FSE: Add front-end scripts for headers and footers containing CoBlocks gallery blocks.

### LINKED ISSUE #35509: FSE: CoBlocks Masonry block design broken when added to a header/footer without adding to content
When adding the `Masonry` block from `CoBlocks` to the header or footer region, without adding a copy to the `Content` section, the design isn't as expected - the images appear in a long vertical chain instead of the actual masonry layout.

Screenshot 2019-08-17 at 16 34 46

On the above image, 

- The first masonry is from the header region.
- The second masonry is from the footer region.
- There is no block on the content region.

When the block is added to the `Content` section, the same `Masonry` block on header and footer show the expected design again.

Screenshot 2019-08-17 at 16 35 49

On the above image, 

- The first masonry is on the header.
- The second masonry is on the content region.
- The third masonry is on the footer region.

### PR DESCRIPTION
**Pull request by kwight**
Because CoBlocks is unaware of FSE and its header+footer sections, CoBlocks only enqueues front-end scripts when its blocks are found in `post_content`. This PR also checks for CoBlocks gallery blocks in FSE headers and footers, enqueuing the scripts if necessary.

#### Testing instructions

* Install the CoBlocks plugin on your FSE dev environment.
* Create a new FSE page with a Masonry block in the header and footer.
* Verify the `coblocks-masonry.min.js` script is enqueued on the front-end.

Fixes #35509.

### CODE REVIEW

**Comment by mmtr** [comment]
Good start @kwight, but this will work only on self-hosted and Atomic sites, since the Simple sites have the styles in a versioned folder. Not sure what's the best way to handle all the environments, but an alternative would be to move this workaround to a WP.com diff + wpcomsh PR.

Note that we should also check if the plugin is active before loading any styles.

**Comment by mmtr** [comment]
Given there are no filters allowing us to customize the `has_block` function, I wonder if we could try a more aggressive approach with [`override_function`](https://www.php.net/manual/en/function.override-function.php)?

```php
rename_function( 'has_block' , 'core_has_block' );
override_function( 'has_block', '$block_type, $post = null', 'return fse_has_block( $block_type, $post ); ' );

function fse_has_block( $block_type, $post ){
  if ( ! $post ) {
    $template = new WP_Template();
    $header   = $template->get_template_content( 'header' );
    $footer   = $template->get_template_content( 'footer' );
    $content  = get_post()->post_content;
    $post     = $header . $content . $footer;
  }

  return core_has_block( $block_type, $post );
}
```

That way we'll have a more generic approach that works with any plugin using `has_block`.

**Comment by mmtr** [comment]
`override_function` is part of [APD](https://www.php.net/manual/en/intro.apd.php), so I don't think we can use that in WP.com

**Comment by mmtr** [comment]
> this will work only on self-hosted and Atomic sites, since the Simple sites have the styles in a versioned folder. Not sure what's the best way to handle all the environments

Oh, I think we can use the `asset_source` method of the plugin, since that will return the proper path in each environment.

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php [hunk 1]
```diff
@@ -115,3 +115,32 @@ function populate_wp_template_data() {
...
+function enqueue_coblocks_gallery_scripts() {
+	if ( ! is_plugin_active( 'coblocks' ) ) {
+		return;
+	}
+
+	$template = new WP_Template();
+	$header   = $template->get_template_content( 'header' );
+	$footer   = $template->get_template_content( 'footer' );
+
+	if ( has_block( 'coblocks/gallery-masonry', $header . $footer ) ) {
```
Comment (Copons) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php]: Any reasons why we are only checking for `/gallery-masonry` and not for `gallery-carousel` as well?

Comment (mmtr) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php]: Good point! Probably @kwight didn't included it because the gallery carousel block is not supported in Simple sites. 

But it is available when using the CoBlocks plugin in an AT site, so we should also load those styles when the block is found.

Comment (mmtr) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php]: Added in 82c7205045a5bc41fff5d6c46b3d77bfa11668a7

**Comment by mmtr** [comment]
> Oh, I think we can use the `asset_source` method of the plugin, since that will return the proper path in each environment.

Added some changes in 82c7205045a5bc41fff5d6c46b3d77bfa11668a7 using that, so now the load functionality should work in both Simple and Atomic sites.

**Comment by kwight** [comment]
Great – I originally thought it might be too much to do the same thing as the CoBlocks plugin itself, but in the end, here we are :) I'm having local env problems testing this, but code looks good; merge if you feel confident with it 👍

**Comment by gwwar** [comment]
Minor note that the edit view shows underline on nav here, but is okay in the published view. Non-blocking since we do want to switch initial support to Maywood.

Screen Shot 2019-08-23 at 4 33 36 PM

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php [hunk 2]
```diff
@@ -115,3 +115,50 @@ function populate_wp_template_data() {
...
+			'coblocks-masonry',
+			$dir . 'coblocks-masonry' . COBLOCKS_ASSET_SUFFIX . '.js',
+			array( 'jquery', 'masonry', 'imagesloaded' ),
+			COBLOCKS_VERSION,
+			true
+		);
+	}
+
+	// Carousel block.
+	if ( has_block( 'coblocks/gallery-carousel', $header . $footer ) ) {
```
Comment (gwwar) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php]: Are there any other blocks that need client JS? Atomic sites will get the full set of CoBlocks, so wondering if we need to check for those.

Comment (mmtr) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php]: Just these two: https://github.com/godaddy/coblocks/blob/530d8a3df2bae78a2364c11ac06be3e263e888f5/includes/class-coblocks-block-assets.php#L142-L171

Actually, the gallery carousel block is not enabled in Simple sites, but we handle it here in order to support AT sites.

**Comment by mmtr** [comment]
> Minor note that the edit view shows underline on nav here, but is okay in the published view. Non-blocking since we do want to switch initial support to Maywood.
> 
> Screen Shot 2019-08-23 at 4 33 36 PM

Uhm, interesting, I don't get the underline styles 🤔. Does this happen to you when testing with both a Simple site and a self-hosted site?

**Comment by gwwar** [comment]
> Does this happen to you when testing with both a Simple site and a self-hosted site?

Just Simple Sites, but it might be that my theme snapshot is a bit different. Not a blocker.
