### PR TITLE
Sharing: Don't display services when there are none.

### LINKED ISSUE #11542: Sharing: "Other Connections" perpetually loads for Jetpack sites
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/sharing
2. Select a Jetpack site

#### What I expected

"Other Connections" group should display connections or disappear after connections have been loaded. It's clear that connections eventually load because the "Publicize Your Posts" connections populate (see Facebook "Disconnect" in screenshot).

#### What happened instead

"Other Connections" shows as loading forever.

#### Browser / OS version

Google Chrome Version 56.0.2924.87 (64-bit)
macOS Sierra Version 10.12.3 (16D32)

#### Screenshot / Video

image

#### Context / Source

@obenland : Might this be related to recent refactoring of this screen?

### PR DESCRIPTION
**Pull request by obenland**
Only displays services placeholders when Services are being fetched.

Fixes a bug where "Other Connections" were shown as loading forever because `ServiceGroup` would just fall back to the loading indicator when there are no services.

Fixes #11542.

### CODE REVIEW

File: client/my-sites/sharing/connections/services-group.jsx [hunk 1]
```diff
@@ -19,36 +19,45 @@ import ServicePlaceholder from './service-placeholder';
...
-				) )
-				: times( NUMBER_OF_PLACEHOLDERS, ( index ) => (
-					<ServicePlaceholder key={ 'service-placeholder-' + index } />
-				) )
-			}
-		</ul>
-	</div>
-);
+const SharingServicesGroup = ( { connections, isFetching, services, title } ) => {
+	if ( services.length || isFetching ) {
```
Comment (aduth) [inline client/my-sites/sharing/connections/services-group.jsx]: Could avoid indentation of most of the function by doing the early return of `null` instead:

```js
if ( ! services.length && ! isFetching ) {
	return null;
}
```
