### PR TITLE
Framework: Fix single- to multi-tree layout transitions (2nd Attempt)

### LINKED ISSUE #6990: Themes: Logged-out navigation to signup and back broken again
#### Steps to reproduce
1. In an incognito window, go to http://calypso.localhost:3000/design
2. Click on a theme's '...' button, choose 'Pick this design'
3. Go back

bildschirmfoto 2016-07-25 um 11 32 02

### PR DESCRIPTION
**Pull request by seear**
Original PR #7021 suffered a var name clash on merge and had to be reverted.

Fixes #6990.

We used to be able to determine which sections use the legacy multi-tree layout by the lack of the isomorphic flag. The signup section has since been changed to use isomorphic routing, but not the single-tree layout, so that technique no longer works.

Use section name instead.

A longer-term fix for the incompatibility between single- and multi-tree layouts is to convert all of Calypso to use a single-tree layout.

To Test (stolen from #7000)

Verify that #6990 is fixed.
In the logged-out showcase, click on a (free) theme, and in its theme sheet, click 'Pick this design'. Click back. Verify that everything renders okay.
Try landing in different sections of Calypso, and navigate in between sections and groups (such as 'My Sites' to 'Reader', see #5081 (comment))
In the logged-in theme showcase, use the site picker to 'Add a New Wordpress', and navigate back. Verify that there is no visual funkiness.
Also:
Land on /design
Click on any theme's ellipsis menu, pick 'Info'
Verify that the ellipsis menu goes away.

Test live: https://calypso.live/?branch=revert-7032-revert-7021-fix/6990

### CODE REVIEW

File: client/boot/index.js [hunk 1]
```diff
@@ -52,7 +52,6 @@ var config = require( 'config' ),
 	supportUser = require( 'lib/user/support-user-interop' ),
 	isSectionIsomorphic = require( 'state/ui/selectors' ).isSectionIsomorphic,
```
Comment (ockham) [inline client/boot/index.js]: You could move this selector import to the new  `import { ... } from 'state/ui/selectors'` statement.

**Comment by ockham** [comment]
Looks good and tests well! Maybe fix that one thing I pointed out if you want, and then :shipit:!
