### PR TITLE
[E2E][GB 16.2.x] Test fixes for Gutenberg (edge/nightly)

### LINKED ISSUE #78975: Flaky E2E: Launch preview
### Spec file

specs/editor/editor__post-basic-flow.ts

### TeamCity ID

10326391

### Logs

image

```
======= Failed test run #1 ==========
  locator.getAttribute: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for locator('body.block-editor-page').locator('.interface-navigable-region[class*="header"] :text("View"):visible')
  ============================================================
  at EditorToolbarComponent.targetIsOpen (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-toolbar-component.ts:101:33)
      at EditorToolbarComponent.openDesktopPreviewMenu (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-toolbar-component.ts:200:12)
      at EditorToolbarComponent.openDesktopPreview (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-toolbar-component.ts:177:3)
      at EditorPage.previewAsDesktop (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/editor-page.ts:743:3)
      at Object.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/editor/editor__post-basic-flow.ts:92:5)
======= Failed test run #2 ==========
  locator.getAttribute: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for locator('body.block-editor-page').locator('.interface-navigable-region[class*="header"] :text("View"):visible')
  ============================================================
  at EditorToolbarComponent.targetIsOpen (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-toolbar-component.ts:101:33)
      at EditorToolbarComponent.openDesktopPreviewMenu (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-toolbar-component.ts:200:12)
      at EditorToolbarComponent.openDesktopPreview (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-toolbar-component.ts:177:3)
      at EditorPage.previewAsDesktop (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/editor-page.ts:743:3)
      at Object.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/editor/editor__post-basic-flow.ts:92:5)
```

### PR DESCRIPTION
**Pull request by fullofcaffeine**
Misc test fixes, preparing for the upcoming 14.6.x release on WPCOM, as part of the nightly/edge testing process.

Issues fixed:
- `specs/editor/editor__post-basic-flow.ts` - https://github.com/Automattic/wp-calypso/issues/78975

#### Testing Instructions

1. Run nightly tests from this branch, tests should pass.
2. Run other builds -- AT edge and simple edge, tests should pass.

Fixes https://github.com/Automattic/wp-calypso/issues/78975.

### CODE REVIEW

File: packages/calypso-e2e/src/lib/components/editor-toolbar-component.ts [hunk 1]
```diff
@@ -16,7 +16,7 @@ const selectors = {
 	switchToDraftButton: `${ panel } button.editor-post-switch-to-draft`,
 
 	// Preview
-	previewButton: `${ panel } :text("View"):visible`,
+	previewButton: `${ panel } [aria-label="Preview"]:visible`,
```
Comment (worldomonation) [inline packages/calypso-e2e/src/lib/components/editor-toolbar-component.ts:19]: I think this is suitable for now, but I will want to look at whether we can use accessible locators (eg. `getByRole`) in the future.

**Review by worldomonation — APPROVED** [review]
