### PR TITLE
Site Switcher: Update 'Add new site' button styles

### LINKED ISSUE #67041: Site Switcher: Move 'Manage [N] Sites' button to bottom of the UI, add conditional 'View [feature] for sites' button
After #66804 lands, we'd like to add a 'Manage Sites' button to the bottom of the Site Switcher UI.

image

The number should reflect the user's total number of sites.

Design for the button is a little TBD at the moment.

Next, the existing 'All my sites' button in the Site Switcher is a little erratic: sometimes it takes you to a list of all your sites, and other times it takes you the multi-site view relating to the feature you're looking at (e.g. stats). We'd like to instead change the existing 'All my sites' button to a 'View [feature] for sites' button that only appears when a given view has a multi-site context:

image

**Done is:**
* [x] A new 'Manage [N] Sites' button appears at the bottom of the Site Switcher UI.
* [ ] The count in the button reflects the user's total number of sites.
* [x] The button links to the new Sites page (`/sites`).
* [x] The button triggers a Tracks event when clicked.
* [x] The existing 'All my sites' UI element is removed.
* [x] A 'View [feature] for sites' button appears when a given view has a multi-site context.
* [ ] The 'Add new site' button is styled as depicted (without dropdown, though).
* [ ] Changes are tested against Jetpack Cloud to ensure no regressions.

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #67041

Originally #67346

## Proposed Changes

Updates the styling for the 'Add new site' button in the Site Switcher.

Uses the `primary` button style.

## Testing Instructions

1. Run Calypso locally (`yarn start`).
2. Verify the 'Add new site' button appears as expected with a variety of Dashboard Color Schemes.
3. Run Jetpack Cloud locally (`yarn start-jetpack-cloud-p`).
4. Verify the 'Add new site' button appears as expected.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Need to do some more work on the color schemes

File: client/components/site-selector/add-site.tsx [hunk 1]
```diff
@@ -19,15 +19,13 @@ const SiteSelectorAddSite: FunctionComponent = () => {
...
-			<Button
-				borderless
-				href={ `${ onboardingUrl() }?ref=calypso-selector` }
-				onClick={ recordAddNewSite }
-			>
-				<Gridicon icon="add-outline" /> { translate( 'Add new site' ) }
-			</Button>
-		</span>
+		<Button
+			className="site-selector__add-new-site"
```
Comment (p-jackson) [inline client/components/site-selector/add-site.tsx]: @danielbachhuber I didn't think we'd need to define all the custom colours for this button, because from the mockups I got the impression it was just supposed to be a "primary" button.

```suggestion
			primary
```

Sep-07-2022 09-45-52


There are some themes where the hover colour for primary buttons are a little odd.

Sep-07-2022 09-45-48

But the users will be used to it, since it's the same primary button hover used everywhere.

File: client/jetpack-cloud/style.scss [hunk 2]
```diff
@@ -320,6 +320,20 @@ html {
 
 .site-selector {
 	display: block;
+	.site-selector__actions {
+		padding: 16px;
+	}
+	.site-selector__add-new-site {
+		border-color: var( --color-sidebar-text );
+		border-radius: 2px;
```
Comment (p-jackson) [inline client/jetpack-cloud/style.scss]: CleanShot 2022-09-07 at 09 50 26@2x

Looks like Jetpack Cloud has it's own border radius value, so this rule ends up just getting ignored.

File: client/components/site-selector/add-site.tsx (hunk 1 above)
Comment (danielbachhuber) [reply client/components/site-selector/add-site.tsx]: > There are some themes where the hover colour for primary buttons are a little odd.

@p-jackson I think I like my styles better...

Comment (p-jackson) [reply client/components/site-selector/add-site.tsx]: Well they are better ❤️
Fair enough, I'm fine with the custom colours. The inverted colour scheme of the sidebar justifies the deviation from the norm I think.

**Review by p-jackson — COMMENTED** [review]
Pairing with Daniel, I've updated the buttons to use the `primary` style. The custom hover style Daniel created often looked better, but the intention from the mockup appears to be that the "add new site" button now uses the bright accent colour.

I've also pinned the button to the bottom of the sidebar in JP Cloud. 💯 points for consistency.

**Review by p-jackson — APPROVED** [review]

**Comment by danielbachhuber** [comment]
Thanks for working with me on this, @p-jackson !

File: client/jetpack-cloud/style.scss [hunk 3]
```diff
@@ -318,8 +318,8 @@ html {
 	}
 }
 
-.site-selector {
-	display: block;
```
Comment (zaguiini) [inline client/jetpack-cloud/style.scss:322]: @danielbachhuber was this change intentional? I'm treating the `.site-selector` as a block element instead of a flexible one because then the "Add new site" button would get close to the site list. This was the behavior we had before this PR, so I thought of maintaining it.

| Right now | How it was |
| ---------- | ------- |
| Screen Shot 2022-09-08 at 17 28 31 | Screen Shot 2022-09-08 at 17 29 39 |

Comment (danielbachhuber) [reply client/jetpack-cloud/style.scss:322]: @zaguiini Yep, it was: 83ec747f385c37b612a4785f076d664f396c94fe It was @p-jackson's preference.

Comment (p-jackson) [reply client/jetpack-cloud/style.scss:322]: This project has a goal of not breaking Jetpack Cloud, and I think that's a balance. It doesn't mean _no_ changes at all to JP Cloud IMO.
Jetpack Cloud is a little different from regular Calypso, but I don't think it should needlessly diverge.
