### PR TITLE
Site Settings - fix support links to open in modal dialog

### LINKED ISSUE #43789: Can't navigate back from support pages
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/settings/writing/[site]
2. Click on the `testimonials` link and wait for the support page to load
3. Click the back button

#### What I expected
I expected to go back

#### What happened instead
Nothing

#### Browser / OS version
Chrome / OSX

#### Screenshot / Video
calypso nav issue

#dogfooding

### PR DESCRIPTION
**Pull request by blackjackkent**
#### Changes proposed in this Pull Request

* This PR updates WPCOM support links on `/settings/writing/{siteUrl}` to open in a dialog modal rather than navigating completely to the support site.

#### Testing instructions

* In the Calypso sidebar for a site you own, click `Manage` -> `Settings`.
* Click the "Writing" tab.
* Click the "testimonials" and "portfolio projects" links under "Content Types" and verify that both of them open up a support site modal dialog.

Fixes #43789

### CODE REVIEW

File: client/my-sites/site-settings/custom-content-types/index.jsx [hunk 1]
```diff
@@ -160,7 +174,13 @@ class CustomContentTypes extends Component {
 				'you can display them using the shortcode [portfolio].',
 			{
 				components: {
-					link: <a href={ localizeUrl( 'https://wordpress.com/support/portfolios/' ) } />,
+					link: (
+						<a
+							onClick={ this.onSupportLinkClick }
+							href={ localizeUrl( 'https://wordpress.com/support/portfolios/' ) }
+							post-id={ 84808 }
+						/>
```
Comment (gwwar) [inline client/my-sites/site-settings/custom-content-types/index.jsx:182]: Was https://wpcalypso.wordpress.com/devdocs/design/inline-support-link not a good fit here?

File: client/my-sites/site-settings/custom-content-types/index.jsx [hunk 2]
```diff
@@ -144,7 +152,13 @@ class CustomContentTypes extends Component {
 				'you can display them using the shortcode [testimonials].',
 			{
 				components: {
-					link: <a href={ localizeUrl( 'https://wordpress.com/support/testimonials/' ) } />,
+					link: (
+						<a
+							onClick={ this.onSupportLinkClick }
+							href={ localizeUrl( 'https://wordpress.com/support/testimonials/' ) }
+							post-id={ 97757 }
```
Comment (gwwar) [inline client/my-sites/site-settings/custom-content-types/index.jsx:159]: This should work, but I wanted to note that embedding data is a little less common in wp-calypso since we usually have access to app state/know this ahead of time. For example in `mapDispatchToProps`, we might make a more specific action `openTestimonialsSupport`. 

```jsx
const openTestimonialsSupport = e => {
        e.preventDefault();
		openSupportArticleDialog( {
			postId: 97757,
			postUrl: localizeUrl( 'https://wordpress.com/support/testimonials/' ),
		} );
};
const openPortfoliosSupport = e => {
        e.preventDefault();
		openSupportArticleDialog( {
			postId: 84808,
			postUrl: localizeUrl( 'https://wordpress.com/support/portfolios/' ),
		} );
};

const mapDispatchToProps = {
   activateModule,
   openTestimonialsSupport,
    openPortfoliosSupport,
};
```

I'd still recommend using https://wpcalypso.wordpress.com/devdocs/design/inline-support-link unless it wasn't a good fit here.

File: client/my-sites/site-settings/custom-content-types/index.jsx (hunk 1 above)
Comment (blackjackkent) [reply client/my-sites/site-settings/custom-content-types/index.jsx:182]: Oop. You totally did also link that in our Slack conversation, I now see; I followed your link to https://github.com/Automattic/wp-calypso/pull/40937 and got sidetracked by the pattern offered in https://github.com/Automattic/wp-calypso/blob/master/client/blocks/support-article-dialog/README.md. `InlineSupportLink` looks cleaner, though, so I'll refactor to that. 😄

File: client/my-sites/site-settings/custom-content-types/index.jsx (hunk 2 above)
Comment (blackjackkent) [reply client/my-sites/site-settings/custom-content-types/index.jsx:159]: Makes sense. Taking the hardcoded values out of the JSX, in other words? I'll refactor towards that as well.

**Comment by blackjackkent** [comment]
Updated per comments above to use `<InlineSupportLink>` component.

File: client/my-sites/site-settings/custom-content-types/index.jsx [hunk 3]
```diff
@@ -140,11 +141,17 @@ class CustomContentTypes extends Component {
...
+			'Add, organize, and display {{link /}}. If your theme doesn’t support testimonials yet, ' +
 				'you can display them using the shortcode [testimonials].',
 			{
 				components: {
-					link: <a href={ localizeUrl( 'https://wordpress.com/support/testimonials/' ) } />,
+					link: (
+						<InlineSupportLink
+							supportLink={ localizeUrl( 'https://wordpress.com/support/testimonials/' ) }
+							supportPostId={ 97757 }
+							text={ translate( 'testimonials' ) }
```
Comment (a8ci18n) [inline client/my-sites/site-settings/custom-content-types/index.jsx:152]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **21** times:
`translate( 'Testimonials', { context: 'Block pattern category'} )` *ES Score: 11*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/custom-content-support-article-dialogs)

File: client/my-sites/site-settings/custom-content-types/index.jsx [hunk 4]
```diff
@@ -156,11 +163,17 @@ class CustomContentTypes extends Component {
...
+			'Add, organize, and display {{link /}}. If your theme doesn’t support portfolio projects yet, ' +
 				'you can display them using the shortcode [portfolio].',
 			{
 				components: {
-					link: <a href={ localizeUrl( 'https://wordpress.com/support/portfolios/' ) } />,
+					link: (
+						<InlineSupportLink
+							supportLink={ localizeUrl( 'https://wordpress.com/support/portfolios/' ) }
+							supportPostId={ 84808 }
+							text={ translate( 'portfolio projects' ) }
```
Comment (a8ci18n) [inline client/my-sites/site-settings/custom-content-types/index.jsx:174]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **37** times:
`translate( 'Portfolio projects' )` *ES Score: 12*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/custom-content-support-article-dialogs)

**Comment by blackjackkent** [comment]
Not sure about the comments above from @a8ci18n - definitely easy enough to fix, but the capitalization ends up looking a bit weird imo.

Screen Shot 2020-07-28 at 12 50 20 PM

**Comment by gwwar** [comment]
The i18n bot will add suggestions, we don't need to always follow them. 

If we're afraid of mangling the translation since this is used in a sentence, I think it'd be fine to add `children` support to inline-support-link. Which I think should allow us to keep the original translation string. 

Maybe something like the following in inline-support-link:
```jsx
		return (
			<LinkComponent
				className="inline-support-link"
				href={ url }
				onClick={ openDialog }
				target="_blank"
				rel="noopener noreferrer"
				{ ...externalLinkProps }
			>
                        //psuedocode, I'm sure we can tidy this for readability
                                 { children ? children : ( showText && ( text || translate( 'Learn more' ) ) supportPostId && showIcon && <Gridicon icon="help-outline" size={ iconSize } /> }
			</LinkComponent>
		);
```

**Comment by blackjackkent** [comment]
Updated per comments above to allow `InlineSupportLink` to accept children, which overrides the presence of the `text` prop if it's provided. (Verified this with the "Podcasting" support link elsewhere on the page.) I'm open to suggestions on the way I structured it for readability; it's a slightly gnarly set of conditionals.

File: client/components/inline-support-link/index.jsx [hunk 5]
```diff
@@ -71,6 +72,11 @@ class InlineSupportLink extends Component {
 			iconSize,
 		};
 
+		// props.children overrides text prop if both are provided
+		const shouldDisplayChildren = children != null;
+		const shouldDisplayTextPropValue = ! children && showText;
+		const shouldDisplayIcon = ! children && supportPostId && showIcon;
```
Comment (gwwar) [inline client/components/inline-support-link/index.jsx:78]: Can maybe shorten the names here to be `displayChildren`, `displayTextPropValue`, and `displayIcon`

File: client/components/inline-support-link/index.jsx [hunk 6]
```diff
@@ -80,8 +86,9 @@ class InlineSupportLink extends Component {
 				rel="noopener noreferrer"
 				{ ...externalLinkProps }
 			>
-				{ showText && ( text || translate( 'Learn more' ) ) }
-				{ supportPostId && showIcon && <Gridicon icon="help-outline" size={ iconSize } /> }
+				{ shouldDisplayChildren && children }
+				{ shouldDisplayTextPropValue && ( text || translate( 'Learn more' ) ) }
```
Comment (gwwar) [inline client/components/inline-support-link/index.jsx:90]: As a follow up Janitorial, we can maybe also simplify this to updating existing usages by removing the text prop/passing through text via children.

**Comment by gwwar** [comment]
Toggled the Needs Review label to trigger another E2E run

File: client/components/inline-support-link/index.jsx (hunk 6 above)
Comment (blackjackkent) [reply client/components/inline-support-link/index.jsx:90]: Yeah, I think that'd be a good idea in the long run.
