### PR TITLE
Editor: Reset title scroll position on blur

### LINKED ISSUE #347: Editor: the beginning of a title is not visible after tabbing from title to content area
Steps to reproduce:

1. Start a new post using the Calypso Editor
1. Write out a really long title that is longer than the title field
1. Press the tab key to move into the content field

<strong>Result:</strong> the beginning of the title field isn't showing

Reported by pedger in [#comment-144](https://horizonfeedback.wordpress.com/2015/09/14/call-for-testing-editor/comment-page-1/#comment-144) on +horizonfeedback.

> When writing a long post name, after inserting it and hitting tab to go to content, it should scroll the title back to the beginning.

Ok to close with an explanation if it's not something we want to take the time to update.

### PR DESCRIPTION
**Pull request by aduth**
Fixes #347 

This pull request seeks to resolve an issue in Firefox where, after tabbing from the editor title field after having entered a very long title, the field would not reset to the start of the field.

__Before:__

before

__After:__

after

__Testing instructions:__

Verify that the title resets to the show the beginning of the field value when tabbing to the editor. This should behave correctly in Firefox and in your preferred browser.

1. Navigate to the [Calypso post editor](http://caypso.localhost:3000/post)
2. Select a site, if prompted
3. Enter a long title, enough to scroll past the visible width of the editor
4. Tab from the field
5. Note that the beginning of the title field is visible

### CODE REVIEW

**Comment by nylen** [comment]
Confirming the bug and the fix.  :+1:

File: client/post-editor/editor-title/index.jsx [hunk 1]
```diff
@@ -66,6 +66,8 @@ export default React.createClass( {
 		} );
 
 		this.onChange( event );
+
+		event.target.scrollLeft = 0;
```
Comment (blowery) [inline client/post-editor/editor-title/index.jsx]: Is this something that should really be part of `FormTextInput`? Feels brittle to be monkeying with a DOM element from a custom element.

Comment (aduth) [inline client/post-editor/editor-title/index.jsx]: >Is this something that should really be part of `FormTextInput`? Feels brittle to be monkeying with a DOM element from a custom element.

That would depend whether we think browser quirks fall under the scope of behaviors to be implemented in the base form components. I'd personally lean towards keeping them as "pure" as possible such that their purpose is primarily aimed at keeping form styling consistent across the app. That said, an alternative view would be to consider them as normalized components, in which this would help keep behavior consistent across browsers.

Comment (blowery) [inline client/post-editor/editor-title/index.jsx]: Right. Either way, shouldn't hold the merge.
