### PR TITLE
DomainPicker: Fix incorrect selected domain on analytics when domain picker closes.

### LINKED ISSUE #42649: Domain picker: tracking issue in Gutenboarding
#### Steps to reproduce

1. Starting at URL: /new/design with analytics debugging active.
2. Wait for Domain Picker button to appear and open it to select a domain.

#### What I expected
* After selecting a new domain and pressing Confirm button the new selected domain should be recorded.

#### What happened instead
* The previous domain selected was recorded by Tracks and `undefined` if there was no previously selected domain.

#### Screenshot / Video
https://cloudup.com/ccOah6T7Lnf

#### Context / Source
Introduced in https://github.com/Automattic/wp-calypso/pull/42409
Might be related to https://github.com/Automattic/wp-calypso/issues/42639 but probably needs to be fixed inside DomainPicker package.

### PR DESCRIPTION
**Pull request by yansern**
## Changes proposed in this Pull Request

When domain picker is closed, the incorrect `selected_domain` was being tracked on analytics. This was due to the buggy implementation of a duplicated and modified hook `useTrackModal()`. 

This PR proposes the following fix:
* Remove `useTrackModal()` (and along with it, `useOnMount` and `useOnUnmount`) hook from domain picker package. 
* Remove `onMountOpen` and `onMountUnmount` event that was introduced during packaging (originally intended to make analytics work quickly).
* Trigger `recordEnterModal` and `recordCloseModal` event in the `DomainPickerButton` component instead, which is easier to maintain.

Also:
* `onCancel` event has been removed. Clicking **Cancel** button now triggers `onClose` event as well. This is to simplify things.

## Testing instructions

Before testing, run `localStorage.debug = 'calypso.analytics'` to see analytics logs on console.

#### Test `calypso_newsite_modal_open` event
- Opening popover should trigger this event.
- Opening modal should trigger this event.

#### Test `calypso_newsite_modal_close` event

**Fresh Without Selecting Domain**
  1. Open a fresh gutenboarding using `/new?fresh`
  2. Open popover/modal.
  3. Close popover/modal.
  4. This event should be triggered with `selected_domain` containing `undefined`.

**With A Domain Selected**
  1. Open popover/modal.
  2. Select a domain.
  3. Click **Confirm** button.
  4. This event should be triggered with `selected_domain` containing the domain you've just selected.

**With Another Domain Selected**
  1. Re-open popover/modal when you have a domain selected prior to this.
  2. Select another domain.
  3. Click **Confirm** button.
  4. This event should be triggered with the `selected_domain` containing the new domain you've just selected (and not the previous one).

**Test The Different Ways To Close Popover & Modal**
- You can close popover by:
  - Clicking outside
  - Pressing **ESC** key
  - Clicking **Close (X)** button
  - Clicking **Confirm** button

- You can close modal by:
  - Pressing the **ESC** key
  - Clicking **Confirm** button
  - Clicking **Cancel** button

All of the above should trigger the close event.

_Note: Clicking **More Options** button does not fire the close event._.

## Screenshot

image

Fixes #42649
Related https://github.com/Automattic/wp-calypso/pull/42409 https://github.com/Automattic/wp-calypso/pull/42657

### CODE REVIEW

File: client/landing/gutenboarding/components/domain-picker-button/index.tsx [hunk 1]
```diff
@@ -76,20 +76,28 @@ const DomainPickerButton: FunctionComponent< Props > = ( {
...
+	};
+
 	const handlePopoverClose = ( e?: React.FocusEvent ) => {
 		// Don't collide with button toggling
 		if ( e?.relatedTarget === buttonRef.current ) {
 			return;
 		}
 		setDomainPopoverVisibility( false );
+		recordCloseModal( 'DomainPickerPopover', {
+			selected_domain: getSelectedDomain()?.domain_name,
```
Comment (sirreal) [inline client/landing/gutenboarding/components/domain-picker-button/index.tsx:90]: Could the observed bug be related to this line?

https://github.com/Automattic/wp-calypso/blob/28e988feee80ce9e0ed1f595d190435e67c72b21/client/landing/gutenboarding/components/domain-picker-button/index.tsx#L69

I don't believe returning selectors from a `wp-data` is valid behavior… the selectors are meant to be invoked inside the `useSelect` callback and return a value. There's caching in place in `useSelect` and I suspect that return a selector (possibly an unexpectedly stable value) is causing the system to behave in unexpected ways.

Comment (sirreal) [reply client/landing/gutenboarding/components/domain-picker-button/index.tsx:90]: To elaborate, I'd expect that to be more like:

```js
const selectedDomain = useSelect( ( select ) => select( STORE_KEY ).getSelectedDomain() );
```

and then we'd use the value directly here rather than invoking the stored selector:

```suggestion
			selected_domain: selectedDomain?.domain_name,
```

Comment (yansern) [reply client/landing/gutenboarding/components/domain-picker-button/index.tsx:90]: Good one!

File: client/landing/gutenboarding/components/domain-picker-button/index.tsx [hunk 2]
```diff
@@ -76,20 +76,28 @@ const DomainPickerButton: FunctionComponent< Props > = ( {
...
+		} );
 	};
 
-	const handleModalClose = () => {
-		setDomainModalVisibility( false );
+	const handleModalOpen = () => {
+		recordEnterModal( 'DomainPickerModal' );
 	};
```
Comment (razvanpapadopol) [inline client/landing/gutenboarding/components/domain-picker-button/index.tsx:96]: Firing this event from the button doesn't make much sense. We'll open the modal also from the PlansGrid in the following days. I think it's ok to do this from modal/popover wrappers instead. That will also allow us to differentiate between type of modal opened.

File: client/landing/gutenboarding/components/domain-picker-popover/index.tsx [hunk 3]
```diff
@@ -15,16 +15,21 @@ import DomainPicker, { Props as DomainPickerProps } from '@automattic/domain-pic
...
-const DomainPickerPopover: React.FunctionComponent< Props > = ( { isOpen, ...props } ) => {
+const DomainPickerPopover: React.FunctionComponent< Props > = ( { isOpen, onOpen, ...props } ) => {
 	const onClose = props.onClose;
 
 	// Popover expands at medium viewport width
 	const isMobile = useViewportMatch( 'medium', '<' );
 
+	React.useEffect( () => {
+		isOpen && onOpen && onOpen();
+	}, [ isOpen, onOpen ] );
```
Comment (razvanpapadopol) [inline client/landing/gutenboarding/components/domain-picker-popover/index.tsx:31]: 🙈 I hope we don't need to do this and fire open event directly from this component. https://github.com/Automattic/wp-calypso/pull/42659/files#r430891845

File: packages/domain-picker/src/domain-picker/index.tsx [hunk 4]
```diff
@@ -214,10 +194,6 @@ const DomainPicker: FunctionComponent< Props > = ( {
 		}
 	}, [ allSuggestions, currentDomain ] );
 
-	useTrackModal( tracksName, onModalOpen, onModalUnmount, {
-		selected_domain: selectedDomain?.domain_name,
-	} );
```
Comment (razvanpapadopol) [inline packages/domain-picker/src/domain-picker/index.tsx:219]: 👍 
Since `DomainPicker` is not a modal (we only choose to wrap it inside a modal in Gutenboarding) getting this out feels right.

File: client/landing/gutenboarding/components/domain-picker-button/index.tsx (hunk 1 above)
Comment (yansern) [reply client/landing/gutenboarding/components/domain-picker-button/index.tsx:90]: Okay so the track event fires before the updated selected domain gets propagated down from the parent down to the child component, that's why the suggestion didn't work.

There are surely ways around this but I'm going to yank the firing of events out from DomainPickerButton and do it separately in DomainPickerPopover and DomainPickerModal as suggested by @razvanpapadopol here https://github.com/Automattic/wp-calypso/pull/42659#discussion_r430891845.

File: client/landing/gutenboarding/components/domain-picker-button/index.tsx (hunk 2 above)
Comment (yansern) [reply client/landing/gutenboarding/components/domain-picker-button/index.tsx:96]: I agree! I'm going to move the firing of events out from DomainPickerButton and into the DomainPickerPopover and DomainPickerModal component individually.

File: client/landing/gutenboarding/components/domain-picker-popover/index.tsx (hunk 3 above)
Comment (yansern) [reply client/landing/gutenboarding/components/domain-picker-popover/index.tsx:31]: Yep, makes sense. It's gonna go in there. https://github.com/Automattic/wp-calypso/pull/42659#discussion_r430927435

File: client/landing/gutenboarding/components/domain-picker-button/index.tsx (hunk 1 above)
Comment (yansern) [reply client/landing/gutenboarding/components/domain-picker-button/index.tsx:90]: Okay some updates. Due to the fact that there are 3 ways a popover gets closed (clicking outside, pressing ESC key, clicking on close button) and 3 ways a modal gets closed (clicking Confirm, clicking Cancel & clicking ESC key) where the closing event is handled either the parent component (popover/modal component) or the domain picker component itself, I did not invest the time into checking what values it holds when triggered by whom, so I'm resorting back to `selected_domain: getSelectedDomain()?.domain_name` for now which surely returns the currently selected domain name from store.

Comment (sirreal) [reply client/landing/gutenboarding/components/domain-picker-button/index.tsx]: I won't stand in the way of changes that are demonstrably working, but returning the selector fro `useSelect` is unorthodox, at least.

[The docs](https://github.com/WordPress/gutenberg/tree/master/packages/data#useSelect) return the value returned by the selector.

🤔  This has me thinking. If what we want here is to call a selector at an arbitrary time, why aren't we using [`select`](https://github.com/WordPress/gutenberg/tree/master/packages/data#select) directly? `useSelect` is tied to renders, but if we don't need render updated values, but rather we need to get a selected value e.g. when a user clicks, then perhaps we should be calling `select` directly in the click handler.

Comment (yansern) [reply client/landing/gutenboarding/components/domain-picker-button/index.tsx]: > If what we want here is to call a selector at an arbitrary time, why aren't we using select directly?
Ah yes! Makes sense! Let me try calling `select( STORE_KEY ).getSelectedDomain()` directly!

Comment (yansern) [reply client/landing/gutenboarding/components/domain-picker-button/index.tsx]: Works well! I'm pretty happy with this now. :) https://github.com/Automattic/wp-calypso/pull/42659/commits/10008fee61498fcd1acbe91072308adee545fdcd

Comment (sirreal) [reply client/landing/gutenboarding/components/domain-picker-button/index.tsx]: That's better 🙂

File: client/landing/gutenboarding/components/domain-picker-modal/index.tsx [hunk 5]
```diff
@@ -3,47 +3,61 @@
...
 		// header margin when the modal is opened.
 		window.scrollTo( 0, 0 );
+		recordEnterModal( tracksName );
+	};
+
+	const handleClose = () => {
+		recordCloseModal( tracksName, {
+			selected_domain: select( STORE_KEY ).getSelectedDomain()?.domain_name,
+		} );
+		onClose && onClose();
```
Comment (sirreal) [inline client/landing/gutenboarding/components/domain-picker-modal/index.tsx:42]: NIT: Optional chain can be optional call:

```suggestion
		onClose?.();
```

File: client/landing/gutenboarding/components/domain-picker-modal/index.tsx [hunk 6]
```diff
@@ -3,47 +3,61 @@
...
 	};
 
+	if ( ! isOpen ) return null;
+
```
Comment (sirreal) [inline client/landing/gutenboarding/components/domain-picker-modal/index.tsx:46]: An early return like this looks like it could go right at the top of the function. Is there any reason we need to do any work?

I'm surprised this doesn't require the block. I would've expected (and prefer):

```js
	if ( ! isOpen ) {
		return null;
	}
```

Coding guidelines do state that: https://github.com/Automattic/wp-calypso/blob/master/docs/coding-guidelines/javascript.md#blocks-and-curly-braces

File: client/landing/gutenboarding/components/domain-picker-popover/index.tsx [hunk 7]
```diff
@@ -4,27 +4,43 @@
...
+		if ( isOpen ) {
+			recordEnterModal( tracksName );
+		}
+	}, [ isOpen ] );
+
+	const handleClose = () => {
+		recordCloseModal( tracksName, {
+			selected_domain: select( STORE_KEY ).getSelectedDomain()?.domain_name,
+		} );
+		onClose && onClose();
```
Comment (sirreal) [inline client/landing/gutenboarding/components/domain-picker-popover/index.tsx:41]: Nit again, this could be:

```suggestion
		onClose?.();
```

File: packages/domain-picker/src/domain-picker/index.tsx [hunk 8]
```diff
@@ -182,7 +159,7 @@ const DomainPicker: FunctionComponent< Props > = ( {
 				isLink
 				className="domain-picker__cancel-button"
 				onClick={ () => {
-					onCancel && onCancel();
+					onClose();
 				} }
```
Comment (sirreal) [inline packages/domain-picker/src/domain-picker/index.tsx:163]: NIT: This is almost synonymous to the following. I think we can a wrapping function:

```js
onClick={ onClose }
```

**Review by sirreal — APPROVED** [review]
I've left some comments. After you have a look and adjust (nothing blocking), let's merge this and we can do some final testing in https://github.com/Automattic/wp-calypso/pull/42657

File: client/landing/gutenboarding/components/domain-picker-modal/index.tsx (hunk 6 above)
Comment (yansern) [reply client/landing/gutenboarding/components/domain-picker-modal/index.tsx:46]: > An early return like this looks like it could go right at the top of the function. Is there any reason we need to do any work?

Ah yes, initially it was because of `useSelect` I had to move this down. Since `useSelect` is not necesary, this can be moved back up!

> Coding guidelines do state that: https://github.com/Automattic/wp-calypso/blob/master/docs/coding-guidelines/javascript.md#blocks-and-curly-braces

Okay! Gonna use the curly brackets! (Yeah, you'd expect maybe prettier would've prettified it but seems like it didn't).

File: client/landing/gutenboarding/components/domain-picker-modal/index.tsx (hunk 5 above)
Comment (yansern) [reply client/landing/gutenboarding/components/domain-picker-modal/index.tsx:42]: Done.

File: packages/domain-picker/src/domain-picker/index.tsx (hunk 8 above)
Comment (yansern) [reply packages/domain-picker/src/domain-picker/index.tsx:163]: Thanks! Done.

File: client/landing/gutenboarding/components/domain-picker-popover/index.tsx (hunk 7 above)
Comment (yansern) [reply client/landing/gutenboarding/components/domain-picker-popover/index.tsx:41]: Done.
