### PR TITLE
Stats: Fixes for the mobile promo card component

### LINKED ISSUE #70055: Calypso: Inline SVG data for mobile QR code
Per [this comment](https://github.com/Automattic/wp-calypso/pull/70028#discussion_r1023458946), it would probably be better to have the SVG data in the bundle.

### PR DESCRIPTION
**Pull request by a8ck3n**
#### Proposed Changes

* Fixes an error in the SVG data `stroke-width` → `strokeWidth`.
* Adds a new story for Woo CTA.
* Adds the QR codes inline as PNG data.
* Adds icons and text for Woo version of component.
* Adds icons for the Apple and Google app stores.
* Adds basic device detection so we can show app store badges on mobile devices.

#### Testing Instructions

* Check out this branch.
* Run `yarn workspace @automattic/components run storybook`.
* Visit the Jetpack Mobile Promo Card entry.
* Confirm the icons, text, and QR codes display correctly.
* Confirm the QR codes link out correctly.
* Use the Chrome dev tools and change to the "iPhone 12 Pro" setting. Refresh the view and confirm you get an App Store badge that links to the app page.
* Change to the "Pixel 5" setting and refresh again. Confirm you get a Play Store badge and that it's wired up correctly.

**Question!** — The device detection is also checking for iPads. My thought process was that we'd want to link to the App Store there too. The Google tablets already behave this way (self reporting as Android devices). If we don't want this behaviour, please let me know.

**Question, the 2nd!** — The Jetpack and Woo text on mobile devices still links to the web pages. Only the badge links to the app store. This is what I'd expect to happen (links stay in browser, badges go to app store) but let me know if we need to change this.

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Fixes #70055

### CODE REVIEW

File: packages/components/src/jetpack-mobile-promo-card/index.tsx [hunk 1]
```diff
@@ -1,64 +1,118 @@
...
 				<p className="promo-card__message">
-					{ isMobile
-						? translate(
-								'Check your stats on-the-go and get real-time notifications with the Jetpack mobile app.'
-						  )
-						: translate(
-								'Visit {{a}}jetpack.com/app{{/a}} or scan the QR code to download the Jetpack mobile app.',
-								{ components }
-						  ) }
+					{ isApple &&
```
Comment (dognose24) [inline packages/components/src/jetpack-mobile-promo-card/index.tsx]: Before composing the returned HTML, could we determine the rendered content with the complex conditions? It would make the logic more explicit outside the HTML structure.

File: packages/components/src/jetpack-mobile-promo-card/index.tsx [hunk 2]
```diff
@@ -1,64 +1,118 @@
...
-							className="jetpack-qr-code"
-							src="https://s0.wp.com/wp-content/themes/a8c/jetpackme-new/images/landing-pages/jetpack-app-get-2x.png"
-							alt="QR Code for Jetpack mobile app"
+							className="promo-store-badge"
+							src={ storeBadgeApple }
+							alt="Badge for the Apple App Store"
 						/>
 					</a>
 				) }
+				{ isGoogle && (
```
Comment (dognose24) [inline packages/components/src/jetpack-mobile-promo-card/index.tsx]: The same recommendation as what was mentioned for the promo card messages.

File: packages/components/src/jetpack-mobile-promo-card/images/index.d.ts [hunk 3]
```diff
@@ -0,0 +1,4 @@
+declare module '*.png' {
```
Comment (dognose24) [inline packages/components/src/jetpack-mobile-promo-card/images/index.d.ts]:
```suggestion
declare module '*.png';
```

Would this shorthand-declared module be capable of resolving the importing error?

**Review by dognose24 — COMMENTED** [review]
I have left some suggestions on code changes. Could we import a higher resolution `icon-woo.png`? And as the support to `Woo` has been introduced, could we consider removing the `jetpack` from the name of this component?

File: packages/components/src/jetpack-mobile-promo-card/images/index.d.ts (hunk 3 above)
Comment (a8ck3n) [reply packages/components/src/jetpack-mobile-promo-card/images/index.d.ts]: Yes, it looks like this does the trick. Thanks!

**Comment by a8ck3n** [comment]
> I have left some suggestions on code changes. Could we import a higher resolution `icon-woo.png`? And as the support to `Woo` has been introduced, could we consider removing the `jetpack` from the name of this component?

Thanks for all the feedback, @dognose24. Very much appreciated!

I've made the requested changes except for the icon. I'll put in a request with the designers to see if we can get that but maybe we can handle that in a follow-up PR (so we don't need to wait on it). What do you think?

File: packages/components/src/mobile-promo-card/index.tsx [hunk 4]
```diff
@@ -0,0 +1,112 @@
...
+		} );
+	};
+
+	// Determines message text based on mobile, tablet, or Desktop.
+	const getMessage = () => {
+		if ( isApple ) {
+			return translate(
+				'Check your stats on-the-go and get real-time notifications with the Jetpack mobile app.'
+			);
+		} else if ( isGoogle ) {
```
Comment (dognose24) [inline packages/components/src/mobile-promo-card/index.tsx:47]:
```suggestion
		}
		
		if ( isGoogle ) {
```

This `else` could be ignored, which will not be a blocker.

**Review by dognose24 — APPROVED** [review]
LGTM! I left a comment that would not be a blocker. Feel free to ship this PR.

**Comment by dognose24** [comment]
> I've made the requested changes except for the icon. I'll put in a request with the designers to see if we can get that but maybe we can handle that in a follow-up PR (so we don't need to wait on it). What do you think?

Yeah, @a8ck3n! Sounds like a plan. I think this PR is ready to go. 😄

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7637516

Hi @a8ck3n, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Bring your Store stats with you using the {{a}}Woo{{/a}} mobile app`
- `Check your stats on-the-go and get real-time notifications with the Woo mobile app.`
- `Visit {{a}}woo.com/mobile{{/a}} or scan the QR code to download the WooCommerce mobile app.`

Thank you in advance!

**Comment by a8ck3n** [comment]
> I've made the requested changes except for the icon. I'll put in a request with the designers to see if we can get that but maybe we can handle that in a follow-up PR (so we don't need to wait on it). What do you think?

New issue for the higher resolution icon in #70462.

File: packages/components/src/mobile-promo-card/index.tsx (hunk 4 above)
Comment (a8ck3n) [reply packages/components/src/mobile-promo-card/index.tsx:47]: I'll have another PR up soon with these changes. Thanks, as always, @dognose!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7637516).
