### PR TITLE
Checkout: adds Jetpack branding

### LINKED ISSUE #28310: Cart: infuse Jetpack branding
#### Steps to reproduce
1. Starting at URL: https://jetpack.com
2. Click “Try it free”.
3. Select a paid plan when presented with https://wordpress.com/jetpack/connect/store
4. Go through the connection process.
5. When prompted to purchase the selected plan, notice the checkout screen.

See p6TEKc-2o1-p2

screen-shot-2018-11-01-at-12-51-55-pm

#### What I expected

Jetpack branding to be more prominent.

### PR DESCRIPTION
**Pull request by keoshi**
#### Changes proposed in this Pull Request

* Adds Jetpack branding to the checkout page.
* Had to replace `componentWillMount` with `UNSAFE_componentWillMount` to be able to commit my changes.

#### Testing instructions

* Visit `/checkout/[site_url]`.
* Check if the Jetpack logo is visible on the sidebar, and ensure this is only true for Jetpack sites.

#### Before
image

#### After

image

Fixes #28310

### CODE REVIEW

**Comment by keoshi** [comment]
@joanrho I did what I could with this. It's a very tricky view to tweak, certainly the most complex I've come across with. My thinking was “what can I do that doesn't require a developer?”, but I'm curious to know your suggestions.

Also, bear in mind that customers won't see the big “(W) WordPress.com Credits” block, so nowhere will they encounter any WP.com branding except for the small (W) logo on the top left-hand corner.

**Comment by rickybanister** [comment]
> This might be a long shot, but can we hide the navbar at this point for Jetpack-specific purchases? It's distracting, clearly branded WPcom, and can lead customers away (if they click on My Sites).

I get the thinking behind that @joanrho, but  I don't think we can assume that the purchase is happening during the onboarding flow. Someone could enter the cart for lots of reasons and if we hide the nav they can't navigate anywhere else, they would have to close the window or edit the url bar. Especially considering folks that didn't see the old 'start for free' button that could lead people into the cart and then abandon completely, forgetting about Jetpack in the process (they might already be doing that, but it would be slightly worse). 

@keoshi I think this is a fine place to start. Tomorrow it would be neat if we could cobble together a slideshow or frankenbranch of all the different PRs from this sprint to see how branding and other tweaks look side-by-side. What do you think?

File: client/my-sites/checkout/cart/secondary-cart.jsx [hunk 1]
```diff
@@ -90,9 +94,18 @@ class SecondaryCart extends Component {
 					showCoupon={ true }
 				/>
 				<CartPlanDiscountAd cart={ cart } selectedSite={ selectedSite } />
+
+				{ isJetpackNotAtomic && <JetpackHeader /> }
```
Comment (sirreal) [inline client/my-sites/checkout/cart/secondary-cart.jsx]: We probably just need the lighter and simpler [`JetpackLogo`](https://wpcalypso.wordpress.com/devdocs/design/jetpack-logo) here:

```suggestion
				{ isJetpackNotAtomic && <JetpackLogo full /> }
```

The header wraps up a bunch of conditional partner branding.

File: client/my-sites/checkout/cart/secondary-cart.jsx [hunk 2]
```diff
@@ -24,6 +24,10 @@ import Sidebar from 'layout/sidebar';
 import CartBodyLoadingPlaceholder from 'my-sites/checkout/cart/cart-body/loading-placeholder';
 import { CART_ON_MOBILE_SHOW } from 'lib/upgrades/action-types';
 import scrollIntoViewport from 'lib/scroll-into-viewport';
+import { getSelectedSiteId } from 'state/ui/selectors';
+import { isJetpackSite } from 'state/sites/selectors';
+import isAtomicSite from 'state/selectors/is-site-automated-transfer';
+import JetpackHeader from 'components/jetpack-header';
```
Comment (sirreal) [inline client/my-sites/checkout/cart/secondary-cart.jsx]:
```suggestion
import JetpackLogo from 'components/jetpack-logo';
```

File: client/my-sites/checkout/cart/style.scss [hunk 3]
```diff
@@ -386,6 +386,10 @@ div.popover-cart__popover {
 		position: relative;
 		top: 0;
 	}
+
+	.jetpack-header {
```
Comment (sirreal) [inline client/my-sites/checkout/cart/style.scss]:
```suggestion
	.jetpack-logo {
```

File: client/my-sites/checkout/cart/secondary-cart.jsx (hunk 1 above)
Comment (keoshi) [reply client/my-sites/checkout/cart/secondary-cart.jsx]: @sirreal I tried using that one, but didn't see the `full` param so went for this one. Will fix soon!

**Comment by keoshi** [comment]
@tyxla I agree with you. But as mentioned above this is the most complex view I've ever seen in terms of code, and was limited in terms of what I could do because I don't have enough skills.

Ideally, I'd like to see the logo centered, above the payment method card in the primary column, so it's consistent with all other JPC views.

**Comment by keoshi** [comment]
@rickybanister sounds good, jumping on that soon!

**Comment by tyxla** [comment]
Oh yeah, don't get me wrong @keoshi! I'm thrilled by the work you're doing these days ❤️

I appreciate the effort to do what's possible there - please know that I'm always there for you if you need a hand with anything I can help with.

**Comment by keoshi** [comment]
@tyxla Thanks for the vote of confidence and the offer to help — I'll most definitely will take you up on that! :)

**Comment by keoshi** [comment]
@tyxla Not sure where this ended up on. Do you think we should _not_ deploy as is and make changes instead?

**Comment by tyxla** [comment]
> @tyxla Not sure where this ended up on. Do you think we should not deploy as is and make changes instead?

Oh well, I was hoping we could find a better place for the branding 😉 But if this is good on the design side, I'm happy to review this PR for you.

**Comment by keoshi** [comment]
I'll let @joanrho and @jeffgolenski weigh in here. Maybe we can aim a better solution if we have time at the end of this week, otherwise this should be a reasonable cupcake.

**Comment by jeffgolenski** [comment]
As mentioned in the above conversations, @keoshi @tyxla I think this is fine for now just because it's the only place Filipe could squeeze it in, but for Q1, we should revisit and get a better spot for it. It's got my 👍 pending those terms. haha

**Comment by joanrho** [comment]
I agree with all of the feedback above. We will address making this even better in our Q1 2019 _Improved Onboarding_ effort when we have the dedicated development resources to handle more complex design solutions. In the absence of that now in our Early Value project, we should move forward with this. Let's ship it.

File: client/my-sites/checkout/cart/secondary-cart.jsx [hunk 4]
```diff
@@ -3,7 +3,7 @@
 /**
  * External dependencies
  */
-
+import { connect } from 'react-redux';
 import PropTypes from 'prop-types';
```
Comment (tyxla) [inline client/my-sites/checkout/cart/secondary-cart.jsx]: Nit: This likely should be below `PropTypes` / `React`. Ideally, imports should be alphabetized to improve readability. Not a big deal though.

Comment (keoshi) [reply client/my-sites/checkout/cart/secondary-cart.jsx]: @tyxla Thanks for that check! Can you quickly confirm this is what you meant? https://github.com/Automattic/wp-calypso/pull/28910/commits/e61e341b5f03aefde7a56265911f226dcae6226a

Comment (tyxla) [reply client/my-sites/checkout/cart/secondary-cart.jsx]: Yeah, that's right @keoshi!  👍 

The imports around seem to be not sorted too, but you don't have to sort them here, as they were like that before already 😉

Comment (keoshi) [reply client/my-sites/checkout/cart/secondary-cart.jsx]: Thanks! 🙌
