### PR TITLE
Editor: Render post selector hierarchy from flattened posts array

### LINKED ISSUE #6623: Editor: Selector pages will not all load for hierarchy with few top-level pages
#### Steps to reproduce

Your site should have at least twenty pages, with fewer than 10 top-level pages. When navigating to the page editor, you should observe that the second page never loads (a placeholder is forever shown at the bottom of the list).

1. Starting at URL: https://wordpress.com/page
2. Expand the Page Options sidebar accordion
3. Try to scroll to reveal all pages

#### What I expected

All pages will eventually be loaded and displayed.

#### What happened instead

Only the first requested set of pages will be loaded, and a placeholder will forever be shown at the bottom of the list.

#### Browser / OS version

Chrome OSX 51.0.2704.103 (64-bit)

#### Screenshot / Video

image

#### Workaround

You should still be able to search for the specific page you're trying to find.

### PR DESCRIPTION
**Pull request by aduth**
Fixes #6623 
Related: #6617 (alternate fix)
Related: #6495 (regression source)

This pull request seeks to resolve an issue where attempting to request posts via the rendered indices of the post selector can result in not all pages being shown as options, if few top-level pages exist on the site.

__Implementation notes:__

This approach moves away from using `getSitePostsHierarchyForQueryIgnoringPage` (in fact, the selector can be removed with these changes). Instead, the `<PostSelector />` component receives the original flattened posts array and tricks `<VirtualScroll />` into thinking that rows are rendered corresponding to the length of the flattened post. Hierarchy is reflected by not allowing the child posts to render (and have a 0 height) unless rendered in the context of the parent's recursive child rendering.

Included is some additional memoization and caching to minimize the effect of repeated lookups on posts, but this may be a bit excessive and hard to maintain ([related anti-pattern](https://facebook.github.io/react/tips/props-in-getInitialState-as-anti-pattern.html)).

__Testing instructions:__

Set up your site and repeat the steps to reproduce as described in #6623, verifying that all pages can be loaded in the Parent Page selector.

Test live: https://calypso.live/?branch=fix/6623-editor-hierarchy-loading

### CODE REVIEW

**Comment by timmyc** [comment]
Quick cursory glance this code seems a bit easier to grok than #6617.  One question - since the posts are not being treeified here, child items will not be sorted in any way correct?

File: client/my-sites/post-selector/selector.jsx [hunk 1]
```diff
@@ -95,6 +101,11 @@ const PostSelectorPosts = React.createClass( {
 				requestedPages: [ 1 ]
 			} );
 		}
+
+		if ( this.props.posts !== nextProps.posts ) {
```
Comment (timmyc) [inline client/my-sites/post-selector/selector.jsx]: I see we are comparing posts here and in line 121 - is performing this comparison a bit intensive due to posts being an array of large objects?

Comment (aduth) [inline client/my-sites/post-selector/selector.jsx]: >is performing this comparison a bit intensive due to posts being an array of large objects?

If it were a deep equality check (`_.isEqual`), then yes it would be, but this is simply comparing references, made possible only by the change in f94a36a to memoize and return the same result from the selector until state changes.

File: client/my-sites/post-selector/selector.jsx [hunk 2]
```diff
@@ -185,20 +200,27 @@ const PostSelectorPosts = React.createClass( {
...
-		let height = ITEM_HEIGHT;
+		if ( item.parent && ! _recurse && includes( this.postIds, item.parent.ID ) ) {
+			return 0;
+		}
 
-		if ( item && item.items ) {
-			height += item.items.reduce( ( memo, nestedItem ) => {
-				return memo + this.getItemHeight( nestedItem );
-			}, 0 );
+		if ( this.itemHeights[ item.global_ID ] ) {
```
Comment (timmyc) [inline client/my-sites/post-selector/selector.jsx]: Is there any chance these cached heights can get invalidated by a new child item being included on a subsequent page request?

**Comment by aduth** [comment]
>since the posts are not being treeified here, child items will not be sorted in any way correct?

This would be true, but we're not taking advantage of tree sorting anyways at the moment. We're [simply passing on the index of the post in the original/flattened array](https://github.com/Automattic/wp-calypso/blob/f34aec2de1a5b96f6685e64ee8c6fc76ac848196/client/state/posts/selectors.js#L287).

File: client/my-sites/post-selector/selector.jsx (hunk 2 above)
Comment (aduth) [inline client/my-sites/post-selector/selector.jsx]: Hmm, if I recall correctly, the idea with `setItemRef` is to [update the cached height](https://github.com/Automattic/wp-calypso/blob/f34aec2de1a5b96f6685e64ee8c6fc76ac848196/client/my-sites/post-selector/selector.jsx#L138-L141), even if it already existed, and to queue up a height recompute to the underlying `VirtualScroll` if anything has changed from current expectations. For this to work correctly, would require that `setItemRef` is called on later `renderItem` calls, which I should verify to be the case but I hadn't encountered any issues with it.

**Comment by timmyc** [comment]
I happened to already have a test site where this was breaking so verified the existing issue and also confirmed this branch does indeed fix.  I like this approach myself, but would be happy to review the other as well if you would like.

**Comment by aduth** [comment]
Removed the now-unused `getSitePostsHierarchyForQueryIgnoringPage` in c6e42717e8ed8081c6e90761ae5fd2a87e349f02.

Many fewer syllables will be uttered from this day forth.

File: client/my-sites/post-selector/selector.jsx (hunk 2 above)
Comment (aduth) [inline client/my-sites/post-selector/selector.jsx]: Confirmed that `setItemRef` is called on later `renderItem` (almost excessively so).
