### PR TITLE
Purchases: Clear site plans after a product is cancelled

### LINKED ISSUE #4518: Purchases: Clear site plans when user cancels
When the user has a domain or a Premium plan, we offer a discount on plans. If the user cancels their Premium plan, or domain, we keep showing this discount on /plans until the user refreshes. We should clear the site plans at this point to ensure the data isn't stale.

Steps to reproduce:
1. Purchase a domain
2. Visit `/plans/:site` and assert that you see a discount on Premium and Business
3. Cancel the domain
4. Visit `/plans/:site` and assert that you still see the discount on Premium and Business
5. Reload your browser and assert that you no longer see the discount

### PR DESCRIPTION
**Pull request by scruffian**
This pull request fixes #4518 by clearing the site plans when a user cancels a product.

The problem with this solution is it means the logic to clear the site plans has to live in the controller not in the action, but I couldn't find another way.
 
#### Testing instructions

1. Run `git checkout fix/4518-clear-site-plans-after-cancellation` and start your server
1. Purchase a domain
2. Visit /plans/:site and assert that you see a discount on Premium and Business
3. Cancel the domain
4. Visit /plans/:site and assert that you no longer see the discount

#### Reviews

- [x] Code
- [x] Product

### CODE REVIEW

**Comment by Tug** [comment]
Code :+1:

**Comment by Tug** [comment]
It did not refresh the list of sitePlans in my case and I was still seeing the discount. I'm trying to debug this.

File: client/lib/upgrades/actions/purchases.js [hunk 1]
```diff
@@ -66,6 +68,10 @@ function clearPurchases() {
 	} );
 }
 
+function clearSitePlans( siteId ) {
+	Dispatcher.handleViewAction( clearSitePlansAction( siteId ) );
```
Comment (Tug) [inline client/lib/upgrades/actions/purchases.js]: I think we have to use `context.store.dispatch` instead of this, but I don't think this can be done from a library which does not have access to the global redux store.

**Comment by Tug** [comment]
Product and Code :+1:
