### PR TITLE
Flaky E2E: reorganize URL extraction logic in `EditorPage.publish`.

### LINKED ISSUE #72586: Flaky E2E: Publish post
### Spec file

specs/onboarding/ftme__write.ts

### TeamCity ID

9367716

### Logs

```
Error: No published article URL found in response.
at EditorPage.publish (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/editor-page.ts:661:10)
    at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/onboarding/ftme__write.ts:122:4)
```

### PR DESCRIPTION
**Pull request by worldomonation**
#### Proposed Changes

This PR restructures the changes introduced in #72112.

Key changes:
- remove the initial exception throwing as the second check should suffice.
- race both `waitForResponse` calls (Simple and Atomic request endpoints) in situations that are not clearly one or the other, such as signing up for a new Business site.

Context:
I believe the `Promise.all` and request interception construct I added in #72112 was causing, on some occasions, to either a) match on the wrong request, or; b) not start the `waitForResponse` in time.

I tried to handle the scenario in a) by racing the two possible requests instead in a `Promise.race` construct.
The scenario in b) is a bit trickier to address, as the number of clicks to actually trigger the request to the post publish endpoint differs depending on whether the post is being edited, or it is a new post being published.

#### Testing Instructions

Ensure the following build configurations are passing:
  - [x] Gutenberg E2E (desktop)
  - [x] Gutenberg E2E (mobile)
  - [x] Calypso E2E (desktop)
  - [x] Calypso E2E (mobile)
  - [x] Pre-Release E2E

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Closes #72586.

### CODE REVIEW

**Comment by youbrokesomething** [comment]
I can't get an entire group of tests to pass, but I don't think that's related to these changes. Because a single test fails each time, and it's a different test each time, the failures I'm seeing might be flake fixed in some of the other PRs. We should merge those changes first, rebase, and then try testing this pr again.

**Comment by worldomonation** [comment]
> I can't get an entire group of tests to pass, but I don't think that's related to these changes. Because a single test fails each time, and it's a different test each time, the failures I'm seeing might be flake fixed in some of the other PRs. We should merge those changes first, rebase, and then try testing this pr again.

Yeah, it sounds like there are failures addressed by peer PRs to this one that's preventing a completely green run. I'll rebase once all the approved PRs are merged.

File: packages/calypso-e2e/src/lib/pages/editor-page.ts [hunk 1]
```diff
@@ -642,11 +631,14 @@ export class EditorPage {
...
-		if ( ! response ) {
-			throw new Error( 'No response received from `publish` method.' );
-		}
+		const [ response ] = await Promise.all( [
+			// First URL matches Atomic requests while the second matches Simple requests.
+			Promise.race( [
+				this.page.waitForResponse( /v2\/(posts|pages)\/[\d]+/ ),
+				this.page.waitForResponse( /.*v2\/sites\/[\d]+\/(posts|pages)\/[\d]+.*/ ),
+			] ),
+			actionsArray,
```
Comment (dpasque) [inline packages/calypso-e2e/src/lib/pages/editor-page.ts]: **Suggestion (blocking)**: I believe `actionsArray` here needs to be spread, right? We want to wait for all the items in that array, so we need to bring those items to the top level array in the `Promise.all` call.

e.g. `...actionsArray`

**Review by dpasque — APPROVED** [review]
One fix we should make first, but otherwise the changes LGTM! 👍

File: packages/calypso-e2e/src/lib/pages/editor-page.ts (hunk 1 above)
Comment (worldomonation) [reply packages/calypso-e2e/src/lib/pages/editor-page.ts]: Interesting how it seemed to work just fine without spreading...I thought multiple arrays inside a `Promise.all` would get treated as top level. 

In any case, made the change in e97b1e2bfe604ae56f47d0a725e2c9e6a9f39d99.
