### PR TITLE
Site Settings SEO: Fix for Receiving New Props and Dirty State for Fields

### LINKED ISSUE #5612: Site Settings: SEO: form should be inactive while loading
The other settings pages disable the form elements and submit buttons while the page is loading, but the SEO settings page is not doing that. This is particularly noticeable on a private or hidden site where I can place my cursor in a text area and start typing until the settings load and the form is disabled.

cc @roundhill

### PR DESCRIPTION
**Pull request by roundhill**
Previously, `componentWillReceiveProps` was blocking any new data from loading unless the site changed. This removes that check and also adds tracking for 'dirty' form fields, so that user's changes don't get overwritten when the props update.

I also moved each verification code to be its own prop instead of in an object, so that it would be easier to use with `omit`.

It now works a lot like `form-base.js`, but without using the `dirtyLinkedState` mixin, which we couldn't use in this component because of the error checking and array-based data structure for the SEO settings api.

This also includes a fix #5612 so that the form will be disabled while settings are being fetched.

**To Test**: Load `/settings/seo` directly, you should see the form disabled for a second and then load the latest settings from the API.

### CODE REVIEW

**Comment by southp** [comment]
Tested and worked on my side!

However, I personally don't see the specific benefit of breaking `verificationServicesCodes` into separate props, except that a flat structure often leads to easier maintainable code. It could be that I am still very new to the code base, though 😅 . Could you help me understand more about the following?

1. Why it makes `omit()` easier?
1. In the function [submitSeoForm()](https://github.com/Automattic/wp-calypso/pull/5670/files#diff-96df6bb8200c5c2e0fadba77e5deeba5R154), it looks like we will still construct the same structure back. Wouldn't it better to let it stay that way in the first place?

Thanks 😄

**Comment by roundhill** [comment]
Thanks for taking a look!

> Why it makes omit() easier?
If I used `omit()` with the old `verificationServicesCodes` object, it would cause the omitted entries to be removed, but because that state would update it would cause the omitted values to be lost on the form. That is why I separated them out and rebuilt the object when saving the form. Maybe there's an easier way that I'm missing but this seemed to be the easiest solution. Thanks!

File: client/my-sites/site-settings/form-seo.jsx [hunk 1]
```diff
@@ -89,44 +88,57 @@ export const SeoForm = React.createClass( {
...
+
+		this.setState( nextState );
 	},
 
 	handleMetaChange( event ) {
 		const seoMetaDescription = event.target.value;
 		// Don't allow html tags in the input field
 		const hasHtmlTagError = anyHtmlTag.test( seoMetaDescription );
 
+		let dirtyFields = this.state.dirtyFields || [];
```
Comment (rralian) [inline client/my-sites/site-settings/form-seo.jsx]: You never reassign `dirtyFields`, so it could be a constant with destructuring and a default, like this:
```js
const { dirtyFields = [] } = this.state;
```

File: client/my-sites/site-settings/form-seo.jsx [hunk 2]
```diff
@@ -320,12 +329,12 @@ export const SeoForm = React.createClass( {
...
 									name="verification_code_google"
 									type="text"
-									value={ googleTag }
+									value={ googleCode }
 									id="verification_code_google"
 									disabled={ isDisabled }
 									isError={ hasError( 'google' ) }
 									placeholder={ getMetaTag( 'google', placeholderTagContent ) }
-									onChange={ event => this.handleVerificationCodeChange( event, 'google' ) } />
+									onChange={ event => this.handleVerificationCodeChange( event, 'googleCode' ) } />
```
Comment (rralian) [inline client/my-sites/site-settings/form-seo.jsx]: This is a minor thing and babel complains about it, but you're not supposed to use lambdas like this in jsx, because it means you are creating a new function each time the snippet gets rendered which degrades rendering performance. Here you're doing it to pass in the string "googleCode" into the verification function. But you could just read that from the event if you used "googleCode" as the input's name (and of course updated the formlabel accordingly). Then this would just be:
```js
onChange= { this.handlerVerificationCodeChange }
```

**Comment by rralian** [comment]
Couple of notes... not blockers, but would be good to update. Otherwise :shipit:
