### PR TITLE
Editor: Fix jumping of post type label

### LINKED ISSUE #10368: Editor: Post type label not centered
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post
2. Select a site
3. Change author (also usually evident in transitioning between placeholder Author selector and loaded state)

#### What I expected

Post type label should remain centered (i.e. "New Post")

#### What happened instead

Post type label adjusts left and right depending on width of author element.

#### Browser / OS version

macOS Sierra Version 10.12.2
Chrome Version 55.0.2883.95 (64-bit)

#### Screenshot / Video

push

#### Context / Source

Suspect related to #5987 (likely need to adjust some flex properties to avoid shrink/grow), cc @DanReyLop @alisterscott @folletto

### PR DESCRIPTION
**Pull request by vvasilev-**
This PR closes #10368.

**Before**
ae573ae0-d102-11e6-9b4d-72df0138be13

**After**
mfaxkcvxt3

**Testing Instructions**

1. Navigate to [/post](http://calypso.localhost:3000/post)
2. Select a site
3. Change the author 

/cc @aduth, @DanReyLop

### CODE REVIEW

File: client/post-editor/editor-action-bar/index.jsx [hunk 1]
```diff
@@ -67,7 +67,7 @@ export default React.createClass( {
 
 		return (
 			<div className="editor-action-bar">
-				<div className="editor-action-bar__first-group">
+				<div className="editor-action-bar__cell editor-action-bar__cell-left">
```
Comment (aduth) [inline client/post-editor/editor-action-bar/index.jsx]: The column-specific classnames seem to fall well under our concept of a modifier:

https://github.com/Automattic/wp-calypso/blob/master/docs/coding-guidelines/css.md#csssass-coding-guidelines

In other words, I think it's reasonable to change them to apply as extensions of the base class:

```scss
.editor-action-bar__cell {
	width: 33%;

	&.is-center {
		text-align: center;
	}

	&.is-right {
		text-align: right;
	}
}
```

File: client/post-editor/editor-action-bar/style.scss [hunk 2]
```diff
@@ -13,6 +13,18 @@
 	}
 }
 
+.editor-action-bar__cell {
+	width: 33%;
```
Comment (aduth) [inline client/post-editor/editor-action-bar/style.scss]: I think rather than explicitly assigning width as thirds for each cell, if our intent is to grant equal width to each cell, we could leverage Flexbox, i.e. `flex: 1`.

Comment (aduth) [inline client/post-editor/editor-action-bar/style.scss]: I stumbled upon this StackOverflow question which appears to pose the same problem we're encountering:

http://stackoverflow.com/questions/32378953/how-can-you-keep-the-center-box-centered-in-a-flex-box-layout

I actually quite like [one of the answers](http://stackoverflow.com/a/37203728) which advocates applying 50% width to left and right cells with `flex-shrink: 1`, then `flex-shrink: 0` to the center column. This way the left and right columns can grow as much as needed while ensuring that the center is kept centered and never collapses.

File: client/post-editor/editor-action-bar/index.jsx (hunk 1 above)
Comment (vvasilev-) [inline client/post-editor/editor-action-bar/index.jsx]: I wasnt' sure about the modifiers, but I will fix them to follow the coding guidelines for CSS. 😄

**Comment by vvasilev-** [comment]
I made the changes that were requested, so now everything should be fine. 😄 

/cc @aduth

**Comment by aduth** [comment]
Ah, was looking great in all browsers, but then found a visual regression in IE11:

`master`|`vvasilev-:fix/10368-post-type-label-not-centered`
---|---
Before|After

**Comment by aduth** [comment]
Oh, and since I shouldn't assume what OS you're using, if you're willing to download a Virtual Machine, I personally use VirtualBox and official Microsoft VMs to run IE11 (on their Win10 VM).

https://www.virtualbox.org/wiki/VirtualBox
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

Otherwise there's a free trial available for BrowserStack: https://www.browserstack.com/

File: client/post-editor/editor-action-bar/style.scss [hunk 3]
```diff
@@ -13,6 +11,24 @@
 	}
 }
 
+.editor-action-bar__cell {
+	&.is-left,
+	&.is-right {
+		display: flex;
+		flex-shrink: 1;
+		width: 50%;
```
Comment (aduth) [inline client/post-editor/editor-action-bar/style.scss]: Actually, in my testing, the solution for IE11 is to change this from `width: 50%;` to `flex-basis: 50%;` . If you can make that change, I think we should be good to go.

**Comment by vvasilev-** [comment]
Hey @aduth,

Thanks for the helpful feedback in this PR.
Sorry about the regression, somehow I missed it. The problem under IE11 is fixed, also I tested everything again so we should be good to go. 😄 

ie11
