### PR TITLE
Fix `Need more storage?` link on Hosting Overview page

### LINKED ISSUE #94670: Hosting Overview: 'Need more storage?' is not a hyperlink
### Quick summary

Unlike all the other blue hyperlinks on the Hosting Overview page, the `Need more storage?` is not a working link.

Screenshot on 2024-09-18 at 15:16:58

When I look at the code responsible for `Need more storage?` at https://github.com/Automattic/wp-calypso/blob/9db92b03c1ef48744601224b37f5cc61e0a77d4d/client/hosting/overview/components/plan-card.tsx#L307-L311 I can see there is a `<span>` and there is no `<a>` with a `href=`.

### Steps to reproduce

1. Navigate to `https://wordpress.com/overview/SITE_URL` on any of Atomic sites
2. Hover over or click `Need more storage?`

### What you expected to happen

Be able to click and navigate to `https://wordpress.com/add-ons/SITE_URL`

### What actually happened

Nothing. 

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

FYI: I know @Automattic/letero has recently worked on Hosting Overview refinements pcYYuD-1Pw-p2

### PR DESCRIPTION
**Pull request by fredrikekelund**
Fixes https://github.com/Automattic/wp-calypso/issues/94670
Related to https://github.com/Automattic/wp-calypso/pull/94144

## Proposed Changes

On the Hosting Overview page, the plan storage widget is sometimes a div and sometimes an anchor. The `Need more storage?` text in the footer of that widget was previously always a link, which is wrong since we don't want nested links. https://github.com/Automattic/wp-calypso/pull/94144 sought to fix this but made it so `Need more storage?` is never a link instead. This PR fixes that.

I also took the opportunity to convert `client/blocks/plan-storage/index.js` to Typescript.

## Why are these changes being made?

Because we don't want nested anchors (since that's not valid HTML).

## Testing Instructions

1. Have an Atomic site without storage addons (that's not enrolled in A4A)
2. Navigate to `/overview/:site_slug`
3. Ensure that `Need more storage?` is a clickable link
4. Have a free site without storage addons
5. Navigate to `/overview/:site_slug`
6. Ensure that `Need more storage?` is not a link

### CODE REVIEW

File: client/hosting/overview/components/plan-card.tsx [hunk 1]
```diff
@@ -195,6 +195,30 @@ const PricingSection: FC = () => {
 	);
 };
 
+function PlanStorageFooter( { children }: PropsWithChildren< unknown > ) {
```
Comment (nightnei) [inline client/hosting/overview/components/plan-card.tsx]: Hm, looks like we don't need it
```suggestion
function PlanStorageFooter( { children }: PropsWithChildren ) {
```

**Review by nightnei — APPROVED** [review]
LGTM and works as expected 👍
Screenshot 2024-09-19 at 11 45 00
Screenshot 2024-09-19 at 11 45 26
