### PR TITLE
Theme bundle: Add Business Plan to cart when theme has WooCommerce

### LINKED ISSUE #68976: Theme Bundling: Wrong plan is added to the cart
On onboarding, if you pick a theme bundled with WooCommerce, you get the Upgrade Modal:

image

If you click on `Upgrade Plan`, Premium Plan is added to the cart instead of the Business Plan.

image

*Relevant flags: `themes/plugin-bundling,signup/seller-upgrade-modal`

### PR DESCRIPTION
**Pull request by nelsonec87**
#### Proposed Changes

* When a theme bundled with WooCommerce is chosen, add Business Plan to the cart instead of Premium Plan.

#### Testing Instructions

* Create a new site using /start
* Enable flags: `themes/plugin-bundling,signup/seller-upgrade-modal`
* Choose the theme Thriving Artist
* Client on "Unlock theme"
* Click on "Upgrade Plan"
* Check that Business Plan was added to the cart

image

Closes #68976

### CODE REVIEW

File: client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx [hunk 1]
```diff
@@ -290,7 +290,16 @@ const UnifiedDesignPickerStep: Step = ( { navigation, flow } ) => {
 			} );
 		}
 
-		const plan = isEligibleForProPlan && isEnabled( 'plans/pro-plan' ) ? 'pro' : 'premium';
+		const themeHasWooCommerce = selectedDesign?.software_sets?.find(
+			( set ) => set.slug === 'woo-on-plans'
+		);
```
Comment (daledupreez) [inline client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx:295]: Minor thought: in the long term, we're likely going to want to abstract this check out into a helper function. (I don't think we need to do this now.) e.g.
```
const designRequiresPlugins = ( selectedDesign ) => {
  if ( ! selectedDesign.software_sets ) {
    return false;
  }

  const softwareSetWithPlugins = selectedDesign.software_sets.find(
    ( set ) => [ 'woo-on-plans' /* other sets? */ ].includes( set.slug )
  );

  return softwareSetWithPlugins !== undefined;
};

const themeRequiresPlugins = designRequiresPlugins( selectedDesign );

**Review by daledupreez — APPROVED** [review]
I've tested and this LGTM! During my testing I noticed that we didn't show the correct price for the plan in the modal, but I believe that is most likely because this branch doesn't yet include the fix in https://github.com/Automattic/wp-calypso/pull/68936.

Screenshot 2022-10-13 at 12 11 16
