### PR TITLE
Checkout: Thank You: Check for the domain credit when displaying message

### LINKED ISSUE #4040: Post Checkout: don't offer domain credit when it's already been used.
When a user purchases a plan we show them the following message on the post checkout screen:
screen shot 2016-03-15 at 10 28 58

The problem is that we still show this message in the case where a user has already purchased a domain, which becomes included in the plan when they purchase it. In this case the user has already used the domain credit, so this message is incorrect.

Steps to reproduce:
1. Start a new site with a free plan
2. Purchase a domain
3. Purchase a plan for the site - ensure that you get the discount
4. Assert that the thank you page contains the "A free domain is included in your plan" message.

### PR DESCRIPTION
**Pull request by drewblaisdell**
Fixes #4040.

This PR updates the thank you page to hide this message when the user has already used their domain credit:

screen shot 2016-03-15 at 10 28 58

**Testing**
*With the 'Get your custom domain' message*
- Visit `/plans/:site` for a site with no plan or domains.
- Add the premium or business plan to your cart.
- Complete the checkout process for the plan.
- Assert that the thank you page includes the 'Get your custom domain' message.

*Without the 'Get your custom domain' message*
- Visit `/domains/add/:site` for a site with no plan or domains.
- Add a domain to your cart.
- Purchase the domain.
- Visit `/plans/:site`.
- Add the premium or business plan to your cart.
- Complete the checkout process for the plan.
- Assert that the thank you page does not include the 'Get your custom domain' message.

- [x] Code review
- [x] Product review

### CODE REVIEW

File: client/my-sites/upgrades/checkout-thank-you/index.jsx [hunk 1]
```diff
@@ -82,30 +86,24 @@ const CheckoutThankYou = React.createClass( {
...
 
-	refreshSitesAndSitePlansIfPlanPurchased() {
-		if ( this.props.receipt.hasLoadedFromServer && this.hasPlanOrDomainRegistration() ) {
-			// Refresh selected site plans if the user just purchased a plan
+		if ( ! this.props.receipt.hasLoadedFromServer && nextProps.receipt.hasLoadedFromServer && this.hasPlanOrDomainRegistration( nextProps ) ) {
 			this.props.refreshSitePlans( this.props.selectedSite.ID );
-
-			// Refresh the list of sites to update the `site.plan` property
-			// needed to display the plan name on the right of the `Plans` menu item
-			Dispatcher.handleViewAction( {
```
Comment (drewblaisdell) [inline client/my-sites/upgrades/checkout-thank-you/index.jsx]: This isn't needed anymore, because we update `sites-list` from the checkout action [here](https://github.com/Automattic/wp-calypso/blob/master/client/lib/sites-list/index.js#L34).

**Comment by spncrb** [comment]
Product :+1: 

But maybe found a bug - will find/open the issue tomorrow...

File: client/my-sites/upgrades/checkout-thank-you/business-plan-details.jsx [hunk 2]
```diff
@@ -7,26 +7,31 @@ import React from 'react';
  * Internal dependencies
  */
 import i18n from 'lib/mixins/i18n';
+import { isBusiness } from 'lib/products-values';
 import PurchaseDetail from 'components/purchase-detail';
 
-const BusinessPlanDetails = ( { selectedSite } ) => {
+const BusinessPlanDetails = ( { selectedSite, sitePlans } ) => {
+	const plan = find( sitePlans.data, isBusiness );
```
Comment (stephanethomas) [inline client/my-sites/upgrades/checkout-thank-you/business-plan-details.jsx]: We should add an import for Lodash's `find()`.

File: client/my-sites/upgrades/checkout-thank-you/business-plan-details.jsx [hunk 3]
```diff
@@ -7,26 +7,31 @@ import React from 'react';
  * Internal dependencies
  */
 import i18n from 'lib/mixins/i18n';
+import { isBusiness } from 'lib/products-values';
 import PurchaseDetail from 'components/purchase-detail';
 
-const BusinessPlanDetails = ( { selectedSite } ) => {
+const BusinessPlanDetails = ( { selectedSite, sitePlans } ) => {
```
Comment (stephanethomas) [inline client/my-sites/upgrades/checkout-thank-you/business-plan-details.jsx]: We should add `sitePlans` to the prop types.

**Comment by scruffian** [comment]
@stephanethomas thanks for the review. I have addressed your comments and added a new commit...

**Comment by stephanethomas** [comment]
Great idea factorizing this code. Code looks good!

**Comment by stephanethomas** [comment]
Tested and works fine.

File: client/my-sites/upgrades/checkout-thank-you/business-plan-details.jsx (hunk 2 above)
Comment (drewblaisdell) [inline client/my-sites/upgrades/checkout-thank-you/business-plan-details.jsx]: Thanks for catching this - I think the linter/bundler miss this because of the presence of `window.find`, so I've missed this a couple times.

Comment (stephanethomas) [inline client/my-sites/upgrades/checkout-thank-you/business-plan-details.jsx]: No problem. Last time it was me who missed that import :).
