### PR TITLE
Connections: Fix keyring user label when no ID

### LINKED ISSUE #54188: Connections: Sharing / Keyring connections displaying that it was connected by incorrect user
Recently, we received a report that a WordPress.com on Atomic site was displaying that legitimate Google Photos and Google My Business connections were connected by the incorrect user.

After review, the user it claimed to have been connected by was a local customer without any Jetpack connection to the site and no admin privileges.  We also confirmed that the actual site owner made the original connections. 

It seems that, at least for WoA sites, the user ID can sometimes be incorrect when checked via https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/marketing/connections/connection.jsx#L250

For a11ns, please see the internal report for specific examples and findings: p9F6qB-78r-p2

cc: @tyxla 

### Steps to reproduce the behavior

We haven't reproduced the behavior consistently yet.

Here are the steps we believe would be required.

1. Connect a WordPress.com on Atomic site to Google Photos / Google My Business under Tools > Marketing > Connections
2. Create some non-WPCOM local users without Jetpack connections.
3. Check Tools > Marketing > Connections and inspect the "Connected By `username`" for changes.

#### What I expected to happen

To display the proper user account that made the connection.

#### What actually happened

An incorrect user might be displayed.

### Context

Atomic request report. p9F6qB-78r-p2

#### Does this happen on simple or atomic sites or both?

Unsure. Initial report is on Atomic.

#### Is there any console output or error text?

No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Low but causes security concerns for users.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

Unsure.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Please see the internal request for a specific example, p9F6qB-78r-p2

image

### PR DESCRIPTION
**Pull request by tyxla**
#### Changes proposed in this Pull Request

This PR fixes the instance when we don't have a keyring user ID for a connection, but we try to guess the owner by it anyway. In that case, we should just bail and not try to look for the connection owner. 

See p9F6qB-78r-p2 for more details.

Fixes #54188.

#### Testing instructions

Verify connections in `/marketing/connections/:site` still work well when expanded.

### CODE REVIEW

File: client/my-sites/marketing/connections/connection.jsx [hunk 1]
```diff
@@ -239,6 +239,10 @@ class SharingConnection extends Component {
 
 const SharingConnectionKeyringUserLabel = localize(
 	( { siteId, keyringUserId, translate, userId } ) => {
+		if ( ! keyringUserId ) {
```
Comment (tyxla) [inline client/my-sites/marketing/connections/connection.jsx:242]: Without this check, we'll end up with all users from the site and will pick the first one from the list, which is completely incorrect.

**Review by WunderBart — APPROVED** [review]
> Verify connections in /marketing/connections/:site still work well when expanded.

Done that, all seems to be working well! 🎉 

Screenshot 2021-07-01 at 14 56 14
