### PR TITLE
Plans Redesign: Fix compare link on my plan page

### LINKED ISSUE #6675: Plans Redesign: Update link on my-plans
With the new plans redesign flag enabled `ENABLE_FEATURES=manage/plan-features make run`, update the following link on the `http://calypso.localhost:3000/plans/my-plan/:mysite:` to point at `http://calypso.localhost:3000/plans/:mysite:`

screen shot 2016-07-11 at 9 50 10 am

### PR DESCRIPTION
**Pull request by lamosty**
Fixes #6675. When plan features is enabled and user navigates to the `my-plan` page, there is a link on the bottom to compare plans. Let's point it to `/plans/:site_slug` as `/plans/compare` no longer exists.

## Testing Instructions

1. Run Calypso with `ENABLE_FEATURES=manage/plan-features make run`;
2. Go to `http://calypso.localhost:3000/plans/my-plan/:mysite:`;
3. Scroll to the bottom of the page and click on "Missing some features..." link;
4. Are you redirected to `/plans/:mysite`?

cc @gwwar @rralian 

Test live: https://calypso.live/?branch=fix/compare-link-my-plan-page

### CODE REVIEW

**Comment by gwwar** [comment]
Don't forget to add a needs review or in progress label :)

File: client/my-sites/plans/current-plan/main.jsx [hunk 1]
```diff
@@ -140,7 +142,11 @@ const PlanDetailsComponent = React.createClass( {
 						isPlaceholder={ false } />
 				</Card>
 				{ selectedSite &&
-					<Card href={ '/plans/compare/' + selectedSite.slug }>
+					<Card
+						href={
+							( showPlanFeatures ? '/plans/' : '/plans/compare/' ) + selectedSite.slug
```
Comment (gwwar) [inline client/my-sites/plans/current-plan/main.jsx]: Minor, but I'd prefer string interpolation here to avoid potential bugs with concatenation. 
```
showPlanFeatures ? `/plans/${ selectedSite.slug }` : `/plans/compare/${ selectedSite.slug }`
```

**Comment by gwwar** [comment]
👍 Looks good to me

File: client/my-sites/plans/current-plan/main.jsx (hunk 1 above)
Comment (lamosty) [inline client/my-sites/plans/current-plan/main.jsx]: This is prettyyy. Thanks!
