### PR TITLE
Typo Fix: "jetpack" not capitalized in error message

### LINKED ISSUE #25320: Typo: "jetpack" not capitalized in error message
When visiting [this URL](https://wordpress.com/plugins/setup) and not having any sites with Jetpack activated, this error message is displayed:

"Oh no! You need to select a jetpack site to be able to setup your plan"

https://github.com/Automattic/wp-calypso/blob/7b91038e6b42d9fc63722cdc051d76e95e5ba698/client/my-sites/plugins/jetpack-plugins-setup/index.jsx#L195

### PR DESCRIPTION
**Pull request by arnabwahid**
Resolves #25320

Use of `Jetpack` instead of `jetpack` in line 195 of `index.jsx`

cc @tyxla

### CODE REVIEW

File: client/my-sites/plugins/jetpack-plugins-setup/index.jsx [hunk 1]
```diff
@@ -192,7 +192,7 @@ class PlansSetup extends React.Component {
 			<JetpackManageErrorPage
 				siteId={ this.props.siteId }
 				title={ this.props.translate(
-					'Oh no! You need to select a jetpack site to be able to setup your plan'
+					'Oh no! You need to select a Jetpack site to be able to setup your plan'
```
Comment (a8ci18n) [inline client/my-sites/plugins/jetpack-plugins-setup/index.jsx]: :ok: This change is safe, we'll keep the existing 20 translations.
