### PR TITLE
New Onboarding: Fix eCommerce plan not being recommended

### LINKED ISSUE #49357: Gutenboarding: selecting Store feature should trigger suggestion of Business or eCommerce plans
### Steps to reproduce the behavior

Prereq. User language is set to English.
Prereq. User is logged in.

1. Initiate Gutenboarding.
2. Select any domain.
3. Select any layout.
4. Select any font.
5. In the features page, select `Store`.
6. Click next.

#### What I expected to happen
Since Store is only supported with Business or eCommerce plans, those plans should be suggested first.

#### What actually happened
Premium plan is suggested instead. Users whom do not inspect the details may wonder why they cannot engage in ecommerce.

### Context
User scenario manual testing.

#### Browser / OS version
OS: macOS Catalina 10.15.7
Browser: Firefox Nightly 86.0a1

#### Is this specific to the applied theme? Which one?
N/A

#### Does this happen on simple or atomic sites or both?
N/A

#### Is there any console output or error text?
N/A

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Minor - irritant and confusion for user.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/6549265/106043725-acc54300-6093-11eb-954a-10e5a77b0e85.mov

### LINKED ISSUE #49452: Focused Launch: monthly plan from cart is not pre-selected
### Steps to reproduce the behavior

1. Create a site from `/start`
2. Pick a monthly paid plan but don't purchase it
3. Go to editor and add `?flags=create/focused-launch-flow` to URL
4. Click Launch to open Focused Launch flow

#### What I expected to happen
The plan from cart should be pre-selected

#### Video
https://cloudup.com/cn1ER7o-64V

### PR DESCRIPTION
**Pull request by razvanpapadopol**
#### Changes proposed in this Pull Request
* Fix getting a recommended plan (eCommerce) when selecting "Store" feature.
* Fix plan pre-selection in Focused launch for monthly plans.

#### Technical Changes
* `TIMELESS_*` slugs are now all lowercase. The reported bug is because the [locally defined slug](https://github.com/Automattic/wp-calypso/pull/48790/files#diff-c442fdac5b918460aacdcf99f45d7e5306f96c8628dd538905f789ea6fcc8c7dR21) is not matching `nonlocalized_short_name` for eCommerce.
* `plansSlugs` is the list of all supported plans defined in `TIMELESS_*` slugs
* Remove the hardcoded `plansPaths` list
* `isPlanProduct` utility function from launch package is now using the complete list of `plansProductSlugs`

#### Testing instructions
* Go to `/new` and advance through the flow selecting Store feature => eCommerce plan should be recommended
* Create a site on `/start` and choose a monthly plan and leave it in cart => open Focused launch and plan should be pre-selected in Summary View (Demo: https://cloudup.com/c1ouW7Yp5le). Caveat: prices won't be correct before #49257 gets fixed.

Fixes #49357
Fixes #49452

### CODE REVIEW

File: packages/launch/src/focused-launch/plan-details/index.tsx [hunk 1]
```diff
@@ -65,15 +65,15 @@ const PlanDetails: React.FunctionComponent = () => {
...
+						free: __( 'Best for getting started', __i18n_text_domain__ ) as string,
+						business: __( 'Best for small businesses', __i18n_text_domain__ ) as string,
 					} }
 					showPlanTaglines
 					popularBadgeVariation="NEXT_TO_NAME"
 					disabledPlans={
 						hasPaidDomain
 							? {
-									[ 'Free' ]: __( 'Unavailable with domain', __i18n_text_domain__ ),
+									[ 'free' ]: __( 'Unavailable with domain', __i18n_text_domain__ ),
```
Comment (ciampo) [inline packages/launch/src/focused-launch/plan-details/index.tsx]: Nit: can we make it `free` instead of `[ 'free' ]`, like it already is on lines 68/69 above?

File: packages/launch/src/utils.ts [hunk 2]
```diff
@@ -64,13 +65,5 @@ export const isDomainProduct = ( item: ResponseCartProduct ): boolean => {
...
-	return (
-		[
-			PlansStore.PLAN_FREE,
-			PlansStore.PLAN_PERSONAL,
-			PlansStore.PLAN_PREMIUM,
-			PlansStore.PLAN_BUSINESS,
-			PlansStore.PLAN_ECOMMERCE,
-		].indexOf( item.product_slug ) > -1
-	);
+	return PlansStore.plansProductSlugs.indexOf( item.product_slug as Plans.StorePlanSlug ) > -1;
```
Comment (ciampo) [inline packages/launch/src/utils.ts:68]: Neat

**Review by ciampo — APPROVED** [review]
Just left a [small nit](https://github.com/Automattic/wp-calypso/pull/49426#discussion_r566739769), but this LGTM 


> Go to /new and advance through the flow selecting Store feature => eCommerce plan should be recommended

Tests well as per instructions:

Screenshot 2021-01-29 at 11 32 46

> Create a site on /start and choose a monthly plan and leave it in cart => open Focused launch and plan should be pre-selected in Summary View (Demo: https://cloudup.com/c1ouW7Yp5le). Caveat: prices won't be correct before #49257 gets fixed.

This also tests as per instructions

Screenshot 2021-01-29 at 11 39 33
