### PR TITLE
Hide post title in Gutenberg depending on theme mod.

### LINKED ISSUE #37509: Homepage templates: Home page title inconsistent
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start
2. Create a new site
3. Edit the home page and you see this:
Screenshot 2019-11-12 at 12 44 49
4. Now preview the site and you see this:
Screenshot 2019-11-12 at 12 45 03

#### What I expected
The page titles are different

#### What happened instead
They should be the same

### LINKED ISSUE #40410: Hide the page title input in your homepage is your theme is going to hide it
When you are editing your home page, you get the input for the page title in every case. Even if the theme is set up to hide the page title on the home page of the site. 
This creates confusion: The user can enter a new title there, but that doesn't affect the front-end of the site at all. 

Let's hide the page title input when the user is editing their homepage and the current theme is set to ignore the title.

### PR DESCRIPTION
**Pull request by noahtallen**
### Changes proposed in this Pull Request
1. Add a "common" package to the FSE plugin for small bits of code that don't fit any of the main sub-features. This code is always executed.
2. Add the `hide-homepage-title` class to the body if editing the homepage in Gutenberg and if the theme mod is active.
3. Add style to not display the title in Gutenberg if the above class exists.

### FAQ:
- _Why not put this in wpcom-block-editor?_ That app isn't a WordPress plugin with php files that can be loaded wherever it is installed. Since we need to run php on simple and Atomic sites, the FSE is a good fit. I didn't want to have to update simple _and_ wpcomsh to support this on Atomic since it is harder to maintain. 
- _Why not put this in a different FSE sub-feature?_ It didn't seem to fit anything we had. Plus, it didn't make sense to add a "hide homepage title" subfeature since it's only like 10loc outside of the bootstrapping.
- _Why is this not in the theme codebase?_ We need to fix this issue for any theme which supports the homepage title mod, which includes 2019, 2020, and all Varia child themes. And probably some others. Unfortunately, none of those themes added support for hiding the title in the editor. If we wanted to do that, we'd have to add this identical code to _every single theme_ and then deploy them. That's a huge effort -- and since this is a Gutenberg classname, it's prone to get out of date. So to fix it, we'd have to then update all of those themes again. That's not worth it. Having this in a single place makes a ton of sense. Since the themes take care of rendering their own front end and homepages, they already support the front-end styles for this theme mod. Think of this code as "editor support" for that theme mod. Now, any theme that supports the mod will work correctly in the editor.
- _Doesn't Varia add this classname to the body already?_ Yes! However, it doesn't have css hiding the editor post title. In fact, this php code is copied from the Varia implementation.

### Testing instructions
1. Sync this to your sandbox.
2. Activate a Varia child theme.
3. Edit the homepage in Gutenberg. The post title should not be visible.
4. Activate the 2020 theme.
5. Edit the homepage in Gutenberg. The post title _should_ be visible. (It is visible since 2020 does not hide the homepage title by default until you change the setting.)
6. Go to the customizer, under "Homepage settings" and check "Hide homepage". Publish the changes.
7. Go back to the homepage editor. The post title should not be visible any more.
8. Make sure the homepage title is still hidden on the front end.
9. Make sure non-homepage post/page titles are still visible in the editor.

Fixes #37509, resolves #40410

### CODE REVIEW

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php [hunk 1]
```diff
@@ -145,6 +145,16 @@ function() {
 	}
 );
 
+/**
+ * Load common module.
+ */
+add_action(
+	'plugins_loaded',
+	function() {
```
Comment (vindl) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php]: I just now notice that there is already an existing pattern here of using anonymous functions for actions in this file. I think this should be avoided for a couple of reasons: `remove_action` can't be used if needed to remove these actions from other places, it's not a common WP core coding convention, and iirc it can make error log harder to read and track down.

File: apps/full-site-editing/full-site-editing-plugin/common/index.scss [hunk 2]
```diff
@@ -0,0 +1,5 @@
+body.hide-homepage-title {
+	.editor-post-title {
+		display: none;
+	}
+}
```
Comment (vindl) [inline apps/full-site-editing/full-site-editing-plugin/common/index.scss]: Missing new line. :)

File: apps/full-site-editing/full-site-editing-plugin/common/index.php [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+ *
+ * @param string $classes Classes for the body element.
+ * @return string
+ */
+function admin_body_classes( $classes ) {
+	global $post;
+	$is_block_editor_screen = ( function_exists( 'get_current_screen' ) && get_current_screen() && get_current_screen()->is_block_editor() );
+	$hide                   = get_theme_mod( 'hide_front_page_title', false );
+	$front_page             = (int) get_option( 'page_on_front' );
+	$id                     = $post->ID;
```
Comment (vindl) [inline apps/full-site-editing/full-site-editing-plugin/common/index.php]: We can drop this variable since it's declared here but not reused later.

File: apps/full-site-editing/full-site-editing-plugin/common/index.php [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+/**
+ * Adds custom classes to the admin body classes.
+ *
+ * @param string $classes Classes for the body element.
+ * @return string
+ */
+function admin_body_classes( $classes ) {
+	global $post;
+	$is_block_editor_screen = ( function_exists( 'get_current_screen' ) && get_current_screen() && get_current_screen()->is_block_editor() );
+	$hide                   = get_theme_mod( 'hide_front_page_title', false );
```
Comment (vindl) [inline apps/full-site-editing/full-site-editing-plugin/common/index.php]: I think we should use a more verbose and readable name here:

```suggestion
	$is_page_title_hidden  = ( true === get_theme_mod( 'hide_front_page_title', false ) );
```

File: apps/full-site-editing/full-site-editing-plugin/common/index.php [hunk 5]
```diff
@@ -0,0 +1,55 @@
...
+	$front_page             = (int) get_option( 'page_on_front' );
```
Comment (vindl) [inline apps/full-site-editing/full-site-editing-plugin/common/index.php]:
```suggestion
	$is_front_page = ( $post->ID === (int) get_option( 'page_on_front' ) );
```

**Comment by noahtallen** [comment]
Alright, those concerns should be resolved. I also removed anonymous functions from some other sub-module init functions, and I did a thorough readme update to bring it into 2020.

File: apps/full-site-editing/README.md [hunk 6]
```diff
@@ -67,25 +46,44 @@ The output is:
 
 You can also build one of the Plugins separately by appending the plugin slug onto the `build` portion of the command. eg:
 
-```
-// Builds the `posts-list-block` Plugin only
-npx lerna run build:posts-list-block --scope='@automattic/full-site-editing'`
+```sh
+# Builds the `posts-list-block` Plugin only
+npx lerna run build:posts-list-block --scope='@automattic/full-site-editing' --stream`
```
Comment (vindl) [inline apps/full-site-editing/README.md]: 🎉

File: apps/full-site-editing/full-site-editing-plugin/common/index.php [hunk 7]
```diff
@@ -0,0 +1,63 @@
...
+/**
+ * Adds custom classes to the admin body classes.
+ *
+ * @param string $classes Classes for the body element.
+ * @return string
+ */
+function admin_body_classes( $classes ) {
+	global $post;
+	$hide_homepage_title = (bool) get_theme_mod( 'hide_front_page_title', false );
+	$is_homepage         = ( (int) get_option( 'page_on_front' ) === $post->ID );
```
Comment (obenland) [inline apps/full-site-editing/full-site-editing-plugin/common/index.php:29]: `$post` is not always available, like outside the Editor. Is returning early an option when `is_block_editor_screen()` returns false?

Comment (noahtallen) [reply apps/full-site-editing/full-site-editing-plugin/common/index.php:29]: @obenland this bug should be fixed in master: https://github.com/Automattic/wp-calypso/blob/e6dd1eb093b6b6e772362b97982d3edf34ae9b9a/apps/full-site-editing/full-site-editing-plugin/common/index.php#L30-L32

Comment (noahtallen) [reply apps/full-site-editing/full-site-editing-plugin/common/index.php:29]: caught it after this PR was merged, unfortunately
