### PR TITLE
Try adding e2e tests for gutenberg tracking

### LINKED ISSUE #41189: (5P) Editor tracking implementation is brittle and subject to breakage
We have an anonymous tracking system on the Block Editor on Dotcom (see `PCYsg-nrf-p2`).

Currently, the implementation of this system (necessarily) relies on a few unstable APIs including:

* features marked as "experimental" in Gutenberg Core.
* Gutenberg HTML markup - which is not considered a public API for the Editor.

This makes the tracking susceptible to subtle breakages leading to data loss for our status.

For example, recently tracking of "no results" in the block inserter/picker was broken because of a regression in a Gutenberg which caused some DOM elements to go missing. This was only picked up by chance as there was no warning that things were broken.

We need to 

* find a way to catch changes in Gutenberg which cause tracking regressions.
* find a way to notify stakeholders when Block tracking is failing for a given event. 

I propose the following solutions:

1. Add a suite of automated e2e tests, which verify tracking events against given versions of Gutenberg.
2. Add a notification mechanic which would fire on Production if a given event tracking starts to fail. This might be some kind of dashboard or a system which fires off alerts when the number of failed alerts reaches a given threshold (do we have anything like this already available?). See `paYJgx-CC-p2#comment-818` for more on this.

### Justification

Whilst this may require a lot of work, the alternative is that our tracking events will continue to fail silently. This will cost us data loss and broken statistics. Given how important some of these stats are for making decisions on priorities, it feels like a sound investment of time.

cc @davemart-in

### PR DESCRIPTION
**Pull request by getdave**
**Important:** if you haven't already, you should probably read: `paYJgx-Es-p2`.

This PR aims to address part of https://github.com/Automattic/wp-calypso/issues/41189. Namely **it aims to validate that all Block Editor tracking events are firing correctly for a given version of Gutenberg**. 

This should help avoid regressions in tracking upon updates to the Gutenberg Plugin on Dotcom.

To do this we are using [the existing Calypso e2e framework](https://github.com/Automattic/wp-calypso/blob/6823c601c858437a481178a63c0668c2b30b7788/test/e2e/README.md). The aim is to simulate the current manual process of verifying that tracking events fire for a given action within the Block Editor. This goes something like:

* Log in to the `/wp-admin` version of the test site (_not_ Calypso).
* Start a new Page in Gutenberg.
* Set a debug line in the console.
* Grab the logs and assert on the results.

However...the Tracks implementation will not fire events to the console on the e2e environment. For this reason we don't use the console output to verify events have fired. Instead on e2e environments [we create a global on the `window`](https://github.com/Automattic/wp-calypso/pull/41329/files#diff-ec49cb03bc5b2ce3c5cc924e5d2222f9R24) into which are [pushed all the events that are tracked just before they are sent to tracks](https://github.com/Automattic/wp-calypso/pull/41329/files#diff-ec49cb03bc5b2ce3c5cc924e5d2222f9R84). We can then [interrogate this global from the e2e test runner](https://github.com/Automattic/wp-calypso/pull/41329/files#diff-be8dda0cd6079f0f0d748361f4857a88R75) and [assert on the contents to verify particular events were fired](https://github.com/Automattic/wp-calypso/pull/41329/files#diff-be8dda0cd6079f0f0d748361f4857a88R78).

It's hacky, but it's probably the best of the options available. Moreover, it is far better than having no test coverage.

#### Current limitations

Please note that this is currently ~a proof of concept~ only adding a single assertion - that the `wpcom_block_inserted` event is being fired correctly. That's checking against that event only - there are many more! Once approved the test suite will be augmented to ensure it captures _**all**_ track events types. Moreover, documentation will be produced. This is an incremental step.

#### Did you consider using Redux?

@retrofox has mentioned that we could consider using a Redux store to hold all tracking events and then interrogate this Redux store to check which events have fired. However, this would be a lesser option, given that this would still leave us open to errors as there is a still a requirement that Redux actions are mapped correctly to Tracks events. Therefore, the best and most resilience and robust way to assert events are fired is that used in this PR.

Fixes https://github.com/Automattic/wp-calypso/issues/41189.

## Changes proposed in this Pull Request

* ~Adds a new global to the `window` in the WPCom Block Editor tracking library on e2e environments in order to capture fired events for the purposes of e2e test assertions.~ handled in  https://github.com/Automattic/wp-calypso/pull/44865
* Adds e2e test suite to check that events being tracked in the Dotcom Block Editor will fire correctly for a given version of Gutenberg.
* Asserts that the `wpcom_block_inserted` event is tracked correctly. It's only this event for now.

## Testing instructions

This is ~hard~ really easy now that D48009-co is merged. I'm ~sorry~ not sorry anymore...

### Setup
* Checkout this PR branch!
* Start Calypso locally - from the root dir run `yarn && yarn start`. Wait until booted.

### Configure e2e tests

* Configure the Calypso local e2e testing environment [as per the docs](https://github.com/Automattic/wp-calypso/blob/6823c601c858437a481178a63c0668c2b30b7788/test/e2e/README.md). 
* Setup to run against Gutenberg "Edge" by adding `export GUTENBERG_EDGE=true` to your `~/.zshrc` (don't forget to `source ~/.zshrc` to reload).

### Running
* Go to the `test/e2e` directory on your local machine.
* Run `./node_modules/.bin/mocha specs/wp-calypso-gutenberg-editor-tracking-spec.js`
* You should see the remotely controlled test browser popup and run through the testing steps. If everything works then you could see something like.
* The key is asserting that the test was able to:
    - pick up on the `window._e2eEventsStack` global.
    - assert that the `wpcom_block_inserted` was fired the requisite number of times for the insertion of the Columns (twice) and Headings (once) blocks.

Screenshot 2020-08-19 at 13 12 49

## Todo

The following items are outstanding on this PR:

- [x] Remove fix to allow `core/heading` block to be inserted into the editor once https://github.com/Automattic/wp-calypso/pull/44862 is merged.
- [x] Remove unnecessary addition of Columns block in `test/e2e/lib/gutenberg/gutenberg-editor-component.js`. Simplifies the PR.
- [x] Remove changes to Block editor tracking library once https://github.com/Automattic/wp-calypso/pull/44865 is merged.
- [x] Add test helper to reset the `eventsStack` after each `step`. This way we'll have a clean stack for each assertion we need to run.
- [x] Update assertions to check the entire `eventsStack` rather than a particular index. See https://github.com/Automattic/wp-calypso/pull/41329/files#r414621150

### CODE REVIEW

**Comment by getdave** [comment]
## Next Steps

* Work out how to build block editor using `yarn` so we can serve "dev" version over Sandbox for development.
* Add special testing only tracks object on window in tracking library to collect tracking events.
* Access the special testing object within the e2e test and assert the recent values added onto it.

**Comment by retrofox** [comment]
@getdave I've added a couple of commits. They add an E2E events stack. Provably we can use this object when E2E runs, and pick up the latest 20 events from there.

I've added two helper functions: `isE2ETest()` and `isSanboxed()`.
For the first one, I've copied the code from other libraries. Could you confirm if it works when you run the tests?
The second one is experimental and we need to define the `_is_sandboxed` globally in a similar way that we defined `_currentSiteId`, `_currentSiteType`, etc.

The following picture shows how we are populating the E2E stack:

Screen Shot 2020-04-23 at 11 46 06 AM

You should be able to access to this stack through of the `_e2eEventsStack` global var.

**Comment by getdave** [comment]
Perfect! Thanks you so much for this. I'll amend the e2e test to read the results. I'm just writing up the proposal in a p2 which I'll publish asap.

File: apps/wpcom-block-editor/src/wpcom/features/tracking/track-record-event.js [hunk 1]
```diff
@@ -5,13 +5,25 @@
...
 const tracksDebug = debug( 'wpcom-block-editor:analytics:tracks' );
+const e2ETracksDebug = debug( 'wpcom-block-editor:e2e' );
 
 // In case Tracks hasn't loaded.
 if ( typeof window !== 'undefined' ) {
 	window._tkq = window._tkq || [];
 }
 
+const E2E_STACK_SIZE = 20;
+if ( isSandboxed() || isE2ETest() ) {
```
Comment (retrofox) [inline apps/wpcom-block-editor/src/wpcom/features/tracking/track-record-event.js:22]: I think we should remove the `isSandboxed()` here. I left it here just for testing purposes. However, it won't work either since it tries to read a global variable that hasn't been added to the source code (dotcom).

```suggestion
if ( isE2ETest() ) {
```

File: apps/wpcom-block-editor/src/wpcom/features/tracking/track-record-event.js [hunk 2]
```diff
@@ -60,5 +72,24 @@ export default ( eventName, eventProperties ) => {
 
 	tracksDebug( 'Recording event %o with actual props %o', eventName, eventProperties );
 
-	window._tkq.push( [ 'recordEvent', eventName, eventProperties ] );
+	const record = [ 'recordEvent', eventName, eventProperties ];
+
+	if ( isSandboxed() || isE2ETest() ) {
```
Comment (retrofox) [inline apps/wpcom-block-editor/src/wpcom/features/tracking/track-record-event.js:77]:
```suggestion
	if ( isE2ETest() ) {
```

File: test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js [hunk 3]
```diff
@@ -0,0 +1,95 @@
...
+				eventsStack[ 0 ][ 0 ] === 'wpcom_block_inserted',
+				true,
+				`"wpcom_block_inserted" failed for ${ eventsStack[ 0 ][ 1 ].block_name }`
+			);
+
+			assert.strictEqual(
+				eventsStack[ 0 ][ 1 ].block_name === 'core/columns',
+				true,
+				`Failed to track "block_name" property for "wpcom_block_inserted" event`
+			);
```
Comment (marekhrabe) [inline test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js:88]: I think it would be more future-proof to check through all logged events in `eventsStack` instead of checking only one item at a set index. If some other (semi- or unrelated) tracking is ever added, it might shift things up or down in the array and we will get a false negative from this test, despite all things still being tracked.

Comment (getdave) [reply test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js:88]: Yep good idea. Thanks.

You will also notice that you can add `step` to break up each part of a large `describe` block. I thought maybe we should clear the `eventsStack` (from the e2e tests) after each `step` so that we know when we search the entire stack we aren't going to get false positives from stale events trigger by previous (unrelated) test. Make sense?

File: apps/wpcom-block-editor/src/wpcom/features/tracking/track-record-event.js (hunk 1 above)
Comment (getdave) [reply apps/wpcom-block-editor/src/wpcom/features/tracking/track-record-event.js:22]: Agreed.

File: test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js (hunk 3 above)
Comment (marekhrabe) [reply test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js:88]: Yes, the cleanup woud be required in this case. Perfect point I have missed!

Comment (getdave) [reply test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js]: Done!

**Comment by getdave** [comment]
The e2e tests added in this PR won't pass until the Phab diff from [this PR](https://github.com/Automattic/wp-calypso/pull/44865) is merged and deployed.

**Comment by getdave** [comment]
@bsessions85 Could you advise on:

- how I can get these tests to run automatically against Gutenberg Edge and standard Gutenberg?
- anything else I need to do to get these tests to run automatically on CI?

Much appreciated.

**Comment by bsessions85** [comment]
@getdave Currently the only way is to do like you did with the labels. If you're wanting to run them both all the time then we'll need to come up with a strategy and a way to support that.

**Comment by getdave** [comment]
> @getdave Currently the only way is to do like you did with the labels. If you're wanting to run them both all the time then we'll need to come up with a strategy and a way to support that.

Ah right I see. Thanks for clarifying.

The goal is to ensure that when @Automattic/good-mountain start testing the next ("edge") version of Gutenberg they can ensure that the tracking won't break. Perhaps then simply by adding the `[Status] Needs e2e Testing Gutenberg Edge` that will happen? For all other PRs I assume the tests will just run "as is"? Perhaps that covers our use case 🤔

**Comment by bsessions85** [comment]
@getdave Yes, just adding the edge label when making Gutenberg updates will do the trick

File: test/e2e/lib/components/sidebar-component.js [hunk 4]
```diff
@@ -55,6 +55,13 @@ export default class SidebarComponent extends AsyncBaseContainer {
 		); // TODO: data-tip-target target is missing
 	}
 
+	async selectWPAdmin() {
+		return await driverHelper.clickWhenClickable(
+			this.driver,
+			By.css( '.menu-link-text[data-e2e-sidebar="WP Admin"]' )
+		); // TODO: data-tip-target target is missing
```
Comment (jeryj) [inline test/e2e/lib/components/sidebar-component.js:62]: Looking through the code for this, it seems like `this._scrollToAndClickMenuItem()` that would use the `data-tip-target` is a lot more robust. We have been using `selectThemes` in the inline help e2e tests and I've noticed it being flakey.

File: test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js [hunk 5]
```diff
@@ -0,0 +1,116 @@
...
+		( [ eventName, eventData ] ) => event === eventName && eventData.block_name === block
+	);
+}
+
+function getTotalEventsFiredForBlock( eventsStack, event, block ) {
+	return getEventsFiredForBlock( eventsStack, event, block ).length;
+}
+
+describe( `[${ host }] Calypso Gutenberg Tracking: (${ screenSize })`, function () {
+	this.timeout( mochaTimeOut );
```
Comment (jeryj) [inline test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js:50]: Why is `this.timeout( mochaTimeOut );` necessary?

File: test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js [hunk 6]
```diff
@@ -0,0 +1,116 @@
...
+
+	describe( 'Tracking: @parallel', function () {
+		// Create image file for upload
+		before( async function () {} );
```
Comment (jeryj) [inline test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js:54]: Probably don't need this comment and empty function?

File: test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js [hunk 7]
```diff
@@ -0,0 +1,116 @@
...
+
+		step( 'Can log in to WPAdmin and create new Post', async function () {
+			this.loginFlow = new LoginFlow( driver, gutenbergUser );
+			if ( host !== 'WPCOM' ) {
+				this.loginFlow = new LoginFlow( driver );
+			}
+			// await this.loginFlow.loginAndStartNewPage();
```
Comment (jeryj) [inline test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js:61]: I'm guessing this and [`loginAndStartNewPost` function](https://github.com/Automattic/wp-calypso/blob/eed5c383d86a89c04b96300d5de856457fb03d96/test/e2e/lib/flows/login-flow.js#L103) don't work since you have to do the stuff from `wp-admin`? 

If that's all the case, maybe remove this commented out line?

File: test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js [hunk 8]
```diff
@@ -0,0 +1,116 @@
...
+			const windows = await driver.getAllWindowHandles();
+
+			await driver.switchTo().window( windows[ 1 ] );
+
+			const wpadminSidebarComponent = await WPAdminSidebar.Expect( driver );
+			await wpadminSidebarComponent.selectNewPost();
+		} );
+
+		step( 'Test for presence of e2e specific tracking events stack on global', async function () {
+			const gEditorComponent = await GutenbergEditorComponent.Expect( driver, 'wp-admin' );
```
Comment (jeryj) [inline test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js:78]: I feel like I remember it being standard to _not_ use shortened variables like `g` for `Gutenberg`?

File: test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js [hunk 9]
```diff
@@ -0,0 +1,116 @@
...
+			//Loop through until we find a new window handle
+			const windows = await driver.getAllWindowHandles();
+
+			await driver.switchTo().window( windows[ 1 ] );
+
+			const wpadminSidebarComponent = await WPAdminSidebar.Expect( driver );
+			await wpadminSidebarComponent.selectNewPost();
+		} );
+
+		step( 'Test for presence of e2e specific tracking events stack on global', async function () {
```
Comment (jeryj) [inline test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js:77]: This phrasing is a little odd since we know it's a Test already. The other steps describe what it's testing without using Test. Maybe something along the lines of "e2e specific tracking events stack on global are present"?

File: test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js [hunk 10]
```diff
@@ -0,0 +1,116 @@
...
+			const gEditorComponent = await GutenbergEditorComponent.Expect( driver, 'wp-admin' );
+			const eventsStack = await driver.executeScript( `return window._e2eEventsStack;` );
+			// Check evaluates to truthy
+			assert( eventsStack, 'tracking events stack missing from window._e2eEventsStack' );
```
Comment (jeryj) [inline test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js:81]: Not sure if there's a standard, but I expected this to start with a capital letter.

File: test/e2e/lib/components/sidebar-component.js (hunk 4 above)
Comment (jeryj) [reply test/e2e/lib/components/sidebar-component.js:62]: Ran this a couple times and it would fail around this sidebar selection sometimes.

File: test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js [hunk 11]
```diff
@@ -0,0 +1,116 @@
...
+				getTotalEventsFiredForBlock( eventsStack, 'wpcom_block_inserted', 'core/columns' ),
+				2,
+				`"wpcom_block_inserted" editor tracking event failed to fire twice for core/columns`
+			);
+
+			assert.strictEqual(
+				getTotalEventsFiredForBlock( eventsStack, 'wpcom_block_inserted', 'core/heading' ),
+				1,
+				`"wpcom_block_inserted" editor tracking event failed to fire for core/heading`
+			);
```
Comment (jeryj) [inline test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js:107]: Minor: I expected this block to be above the Columns check since the header is initially added before the columns above.

**Review by jeryj — CHANGES_REQUESTED** [review]
This runs successfully for me locally on both Gutenberg and Gutenberg Edge 🙌🏻 The tests are easy to read through and make a lot of sense to me. I left a lot of minor cleanup comments.

File: test/e2e/lib/components/sidebar-component.js (hunk 4 above)
Comment (getdave) [reply test/e2e/lib/components/sidebar-component.js:62]: Great spot. This is super flaky whereas the scroll to method is much more robust. I've updated the code to include the data-tip-target necessary to utilise this method and removed the previous change.

File: test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js (hunk 5 above)
Comment (getdave) [reply test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js:50]: I actually don't know but if you remove it everything breaks. It's the same for all the Gutenberg editor tracking files.

@bsessions85 can you shed light on this at all?

File: test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js (hunk 8 above)
Comment (getdave) [reply test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js:78]: It matches other Gutenberg Editor spec files.

File: test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js (hunk 9 above)
Comment (getdave) [reply test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js:77]: Reworded to avoid the term "test" in the `step` description

File: test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js (hunk 10 above)
Comment (getdave) [reply test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js:81]: Not sure exactly which bit this refers to. I sentence cased the error message in `assert`.

File: test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js (hunk 11 above)
Comment (getdave) [reply test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js:107]: Good point. Updated.

**Review by jeryj — APPROVED** [review]
Thanks for all the updates! 🚢

**Comment by getdave** [comment]
All e2e tests seem unrelated. I think we can merge. Do you agree @jeryj and @cpapazoglou ?

cc @bsessions85 ?

**Comment by jeryj** [comment]
@getdave Most of the errors are not related, but I did see this one that is failing from the e2e tests added in this PR:
- https://app.circleci.com/pipelines/github/Automattic/wp-e2e-tests-for-branches/35250/workflows/a060bcfa-ad1d-4667-aa73-49972d0cbd30/jobs/95460: **Can log in to WPAdmin and create new Post - [WPCOM] Calypso Gutenberg Tracking: (desktop) Tracking: @parallel**

I had that one flake on me once locally. It passed every other time no problem.

**Comment by getdave** [comment]
> @getdave Most of the errors are not related, but I did see this one that is failing from the e2e tests added in this PR:
> 
> * https://app.circleci.com/pipelines/github/Automattic/wp-e2e-tests-for-branches/35250/workflows/a060bcfa-ad1d-4667-aa73-49972d0cbd30/jobs/95460: **Can log in to WPAdmin and create new Post - [WPCOM] Calypso Gutenberg Tracking: (desktop) Tracking: @parallel**
> 
> I had that one flake on me once locally. It passed every other time no problem.

That tests is running on Horizon. If you check Horizon you'll notice that the `li[data-tip-target="wpadmin"] ` does not exist. That's because that change is in this PR so it's not yet on Horizon. So I think that's a legit failure if you follow?

**Comment by getdave** [comment]
@bsessions85 Could you possibly verify that the failing tests are not related to this PR. 

The only exception to that is what I said [here about the failing Horizon tests](https://github.com/Automattic/wp-calypso/pull/41329#issuecomment-677677357).

**Comment by getdave** [comment]
All test failures are unrelated to this PR:

* `ci/wp-e2e-tests-horizon-full-desktop` - expected to fail as the change in this PR isn't available on Horizon until deployed.
* `ci/wp-e2e-tests-horizon-full-mobile` - expected to fail as the change in this PR isn't available on Horizon until deployed.
* `ci/wp-e2e-tests-full-mobile-edge` - failures unrelated to this PR. Also it's the bleeding Edge Gutenberg suite so not in Production.

On this basis, I"m going to merge this PR as everything else is passing.
