### PR TITLE
Log snag errors to logstash

### LINKED ISSUE #60318: Woo Installer: User saw "We've hit a snag" error
### Quick summary

See: p1642572097155400-slack-C02DQP0FP
The user saw [the "We've hit a snag" error](https://d.pr/i/nW6hSB) when going through the Woo installer flow.

What we know:
- The user previously had WooCommerce installed
- Deactivating all plugins didn't resolve the issue.
- Manually installing WooCommerce did resolve the issue, but skipped the installer.

### Steps to reproduce

TBD

### What you expected to happen

The flow should recover.

### What actually happened

An error was shown.

### PR DESCRIPTION
**Pull request by lsl**
#### Changes proposed in this Pull Request

* Adds snag errors to calypso logs

#### Testing instructions

* Generate a snag error (reducing the [install timeout](https://github.com/Automattic/wp-calypso/blob/5930fddf6751a4dc4ef96d6c15f00d6a0d0d9924/client/signup/steps/woocommerce-install/transfer/install-plugins.tsx#L18) and commenting out the [status request](https://github.com/Automattic/wp-calypso/blob/5930fddf6751a4dc4ef96d6c15f00d6a0d0d9924/client/signup/steps/woocommerce-install/transfer/install-plugins.tsx#L50) is one way to do this.
* Watch kibana for the error to be logged.

Screenshot 2022-02-03 at 16-01-54 Discover - Elastic

Related to #60318

### CODE REVIEW

File: client/signup/steps/woocommerce-install/transfer/index.tsx [hunk 1]
```diff
@@ -57,6 +57,7 @@ export default function Transfer( props: WooCommerceInstallProps ): ReactElement
 			},
 			properties: {
```
Comment (Rolilink) [inline client/signup/steps/woocommerce-install/transfer/index.tsx]: p1643922102061369/1643906250.237759-slack-C029UPVMGTW while pairing @allilevine and I where discussing about having a way to query on kibana through the `calypso_woocommerce_dashboard_snag_error` type. I think is really good idea to have it as a queryable field to see trends and how new changes affect those trends. Also adding `action` will help us to have do more "fine-grained" queries if we need to.

**Review by Rolilink — APPROVED** [review]

File: client/signup/steps/woocommerce-install/transfer/index.tsx (hunk 1 above)
Comment (obenland) [reply client/signup/steps/woocommerce-install/transfer/index.tsx]: Should all of `extra` be in `properties`?

Comment (Rolilink) [reply client/signup/steps/woocommerce-install/transfer/index.tsx]: makes sense! except message since we have it on line 47!

File: client/signup/steps/woocommerce-install/transfer/index.tsx [hunk 2]
```diff
@@ -39,6 +41,28 @@ export default function Transfer( props: WooCommerceInstallProps ): ReactElement
...
+			severity: config( 'env_id' ) === 'production' ? 'error' : 'debug',
+			blog_id: siteId,
+			extra: {
+				env: config( 'env_id' ),
+				type: 'calypso_woocommerce_dashboard_snag_error',
+				action: failureInfo.type,
+				site: domain,
+				code: failureInfo.code,
+				message: failureInfo.error,
+			},
```
Comment (lsl) [inline client/signup/steps/woocommerce-install/transfer/index.tsx]:
```suggestion
```

**Comment by lsl** [comment]
Rebased, node update
