### PR TITLE
Clear 'unknown attribute' errors in Calypso packages where it is safe to do so

### LINKED ISSUE #60677: [Bug]: wrong parameters name
### Quick summary

In a JSX svg a `fill-rule` property must be written as `fillRule`. See https://github.com/Automattic/wp-calypso/blob/trunk/client/blocks/login/two-factor-authentication/push-notification-illustration.jsx#L39-L58

### Steps to reproduce

1. Visit /log-in/push
2. Check the JS console

### What you expected to happen

1. The JS console to not print an error

### What actually happened

1. The JS console print an error

### Context

_No response_

### Browser

_No response_

### Simple/Atomic

_No response_

### Other notes

_No response_

### Reproducibility

Consistent

### Severity

_No response_

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by mpkelly**
Fixes #60677

Related to #64984

#### Proposed Changes

Run the 'unknown attribute' check in WebStorm and apply fixes, where it looks safe to do so. 

The changes mainly fall into two categories: using DOM name instead of JSX name, e.g. `class` instead of `className` or using the wrong case e.g. `fill-rule` instead of `fillRule` as in #60677 which lead to this PR. 

In addition, the `href` attribute was also removed from **client/components/post-schedule/docs/example.jsx**, where it is invalid and isn't referenced in the file or by the component (copy/paste error assumed).

#### Testing Instructions

As well as the automated tests, it should be enough to review the changes one by one. Functionally nothing has changed except the errors mentioned above are now gone. Before this change you would see a message in the log like this:

image

### CODE REVIEW

File: client/components/post-schedule/docs/example.jsx [hunk 1]
```diff
@@ -169,7 +169,6 @@ const PostScheduleExample = localize(
 											position: 'relative',
 										} }
 										onClick={ this.clearState.bind( this, 'timezone' ) }
-										href="#"
```
Comment (daledupreez) [inline client/components/post-schedule/docs/example.jsx:172]: Good catch on this! And thanks for calling it out in the PR description.

I am guessing this stems from the availability of the `href` attribute on the [Calypso Button component](https://wpcalypso.wordpress.com/devdocs/design/button).

File: client/components/web-preview/content.jsx [hunk 2]
```diff
@@ -383,7 +383,7 @@ export default class WebPreviewContent extends Component {
 								src="about:blank"
 								onLoad={ () => this.setLoaded( 'iframe-onload' ) }
 								title={ this.props.iframeTitle || translate( 'Preview' ) }
-								fetchpriority={ fetchPriority ? fetchPriority : undefined }
+								fetchPriority={ fetchPriority ? fetchPriority : undefined }
```
Comment (daledupreez) [inline client/components/web-preview/content.jsx:386]: Does this usage give a warning? Based on MDN, the [iframe element's `fetchpriority` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-fetchpriority) is all lower case, and I don't see `fetchpriority` referenced in the React repo (using [this case-insensitive search](https://github.com/facebook/react/search?q=fetchpriority).

**Review by daledupreez — COMMENTED** [review]
Thanks for splitting this out of the previous PR! 💖

Everything looks good with the exception of the change to `fetchpriority`. I _think_ we may need to keep it in lower-case `fetchpriority`, but we can definitely ship everything else. Maybe take a quick look into that question, and if you can't resolve it quickly, drop that change from this PR so we can handle it separately?

File: client/components/web-preview/content.jsx (hunk 2 above)
Comment (mpkelly) [reply client/components/web-preview/content.jsx:386]: it's lowercase in the DOM but as a JSX attribute, it would be camel-case like the others. It's still an experimental attribute which is why it's not in the React repo. React does output it as lowercase though. 

image

So the argument for making this change is that if `fetchpriority` becomes standard our code will be correct and the case is consistent with other JSX attributes. We also don't break anything as a result of making the change now.

File: client/components/post-schedule/docs/example.jsx (hunk 1 above)
Comment (mpkelly) [reply client/components/post-schedule/docs/example.jsx:172]: Ah, good to know. I think this type of link usage is seen as an anti-pattern these days anyway. Example:

https://a11y-solutions.stevenwoodson.com/solutions/navigation/link-anti-patterns/

File: client/components/web-preview/content.jsx (hunk 2 above)
Comment (daledupreez) [reply client/components/web-preview/content.jsx:386]: Thanks for confirming! I wasn't able to work out how this specific case gets handled in the UI -- I wanted to make sure the attribute won't get transformed to `fetch-priority` due to the camel case usage.

**Review by daledupreez — APPROVED** [review]
Looks good to me!

Thanks for clarifying the question around `fetchpriority`.

File: client/components/web-preview/content.jsx (hunk 2 above)
Comment (creativecoder) [reply client/components/web-preview/content.jsx:386]: @mpkelly It looks like this now throws a warning for `fetchPriority`. Here's what I'm seeing currently on trunk:

- Using the development version of Calypso (build it locally using `yarn start`) so you can see the React warnings
- Visit `/view/{site}`
- I now see the following warning in the JS console

```
Warning: React does not recognize the `fetchPriority` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `fetchpriority` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

Comment (mpkelly) [reply client/components/web-preview/content.jsx:386]: Hi @creativecoder , yes, this attribute is not officially supported, so React still outputs a warning regardless. What I did was change the case to match the JSX convention. If this attribute ever does become official then this warning will go away. I verified that React converts from camel to lower even for unknown attributes.

Comment (creativecoder) [reply client/components/web-preview/content.jsx:386]: If I revert `fetchPriority=` to `fetchpriority=`, the console warning goes away.

So what's the advantage of using `fetchPriority=`? If it's being converted to `fetchpriority` anyway, isn't it better to not have the distraction of the console warning?

Comment (mpkelly) [reply client/components/web-preview/content.jsx:386]: >So what's the advantage of using fetchPriority=? If it's being converted to fetchpriority anyway, isn't it better to not have the distraction of the console warning?

Yeah, the goal was to clear console warnings, so I don't think this should have been included 😃 .There are [three locations where we use camel-case](https://github.com/Automattic/wp-calypso/search?q=fetchPriority), including this one, so maybe a small PR could be made to clear those. If you think it's worth it then I will do that tomorrow.

Comment (creativecoder) [reply client/components/web-preview/content.jsx:386]: It's easy enough to address, so it does seem worth fixing! https://github.com/Automattic/wp-calypso/pull/66070
