### PR TITLE
fix viewport controlls being hidden on resize

### LINKED ISSUE #66161: Unified design picker: Device switcher disappears when resizing the browser
## Description
As the user resize the browser window, the device switcher component disappears and reappears. See video: https://video.wordpress.com/v/bjz57K8F

## Acceptance
- [x] The device switcher component should always show when in desktop view.
- [x] The device switcher component should not show when in mobile view.

### PR DESCRIPTION
**Pull request by roo2**
fixes https://github.com/Automattic/wp-calypso/issues/66161

I added a console.log() line in the render method, and saw that render was not being triggered on browser resize.

By setting `state.viewport` whenever the preview is resized, we force it to be re-rendered and recalculate the `isWithinBreakpoint` function which determines whether to show the device viewport switcher on https://github.com/Automattic/wp-calypso/blob/trunk/client/components/web-preview/content.jsx#L352

I think that we could use the subscribeIsWithinBreakpoint functions as we have done in other places, but this way is also simple and works for the entire page using the existing event, although I see it's a bit indirect/magical 🤷.

### Testing instructions

Open the preview on the UDP, resize the page between mobile and desktop as shown in https://github.com/Automattic/wp-calypso/issues/66161, the device selector controls should now always re-appear in desktop mode.

### CODE REVIEW

**Comment by taipeicoder** [comment]
I wonder if we can simplify this by just removing the `isWithinBreakpoint` and use CSS to force hide it in mobile resolution instead?

**Comment by arthur791004** [comment]
> I wonder if we can simplify this by just removing the isWithinBreakpoint and use CSS to force hide it in mobile resolution instead?

Yes, I agree that using CSS is more simple in this case. Or we can also change to use `subscribeIsWithinBreakpoint`. I'm okay with both as it's better than the current way that is a bit indirect/magical 😂

**Comment by roo2** [comment]
@taipeicoder I think a CSS solution is tricky here because it is to hide the ToolbarComponent which is passed in as a prop and doesn't have any guaranteed class names for CSS to reference.

I think in this case it will be easier to use `subscribeIsWithinBreakpoint` so I'll have a look into that, yes ok you're right @arthur791004 it is too magical as I've implemented it now 😂

**Comment by arthur791004** [comment]
> I think a CSS solution is tricky here because it is to hide the ToolbarComponent which is passed in as a prop and doesn't have any guaranteed class names for CSS to reference.

Oh yes, that makes sense to me. That said, both `showDeviceSwitcher` and `showUrl` are from props, we might probably just need to handle the default Toolbar component if we want to use the CSS solution.

File: client/components/web-preview/content.jsx [hunk 1]
```diff
@@ -349,7 +355,7 @@ export default class WebPreviewContent extends Component {
 					{ ...this.props }
 					showExternal={ this.props.previewUrl ? this.props.showExternal : false }
 					showEditHeaderLink={ this.props.showEditHeaderLink }
-					showDeviceSwitcher={ this.props.showDeviceSwitcher && isWithinBreakpoint( '>660px' ) }
+					showDeviceSwitcher={ this.props.showDeviceSwitcher && ! this.state.isMobile }
```
Comment (arthur791004) [inline client/components/web-preview/content.jsx:358]: Do you think we also need to handle `showUrl`? But it's not a blocker for this PR 🙂

**Review by arthur791004 — APPROVED** [review]
👍

File: client/components/web-preview/content.jsx (hunk 1 above)
Comment (roo2) [reply client/components/web-preview/content.jsx:358]: I don't know, really anywhere we use isWithinBreakpoint we could see this issue. I did explore that but it didn't seem to be having any effect in the current static DP or in the unified DP, it looks like the URL is always shown (expect when it's hidden by CSS on mobile) 🤷 .

Comment (arthur791004) [reply client/components/web-preview/content.jsx:358]: 👌
