### PR TITLE
Editor: Revisions: Decode HTML entities in diff viewer

### LINKED ISSUE #17448: Editor: Revisions: Properly render HTML entities
#### Steps to reproduce
1. Starting at URL: `/post/:postId`
2. Go to Status → Revisions from Editor sidebar
3. Pick a revision

screen shot 2017-08-23 at 01 00 48

I expected to see those &#8217 as apostrophes, which is how I see them in the Editor if I load the revision, or on the front-end if I preview the post.

### PR DESCRIPTION
**Pull request by mcsf**
Fixes #17448 

(ignore the incorrect branch name; too late now ¯\\_(ツ)_/¯)

### CODE REVIEW

**Comment by mcsf** [comment]
@blowery, touching `lib/post-normalizer/rule-decode-entities` was the necessary extra step to make this work for Post Revisions (p8F0Ux-yD-p2). Are there issues you can anticipate with this change? If there are, we could consider forking this to a separate normalizer just for revisions, but limiting duplication is always a goal.

**Comment by mcsf** [comment]
I believe Ben is away; maybe @samouri?

**Comment by samouri** [comment]
@mcsf I believe this would cause issues for Reader's full-post view.  We use [dangerouslySetInnerHtml](https://github.com/Automattic/wp-calypso/blob/4bfa977188f5dc6c704044274a4804d0b1405326/client/blocks/reader-full-post/index.jsx#L377) and so things are decoded by the browser for us.  If you decoded it beforehand then things may get interpreted as html keywords instead of as plaintext.

**Comment by mcsf** [comment]
That makes sense; thanks, @samouri.

@bperson, let me know if you have objections, otherwise I think I'll

>  If there are [anticipated issues], we could consider forking this to a separate normalizer just for revisions

**Comment by bperson** [comment]
@mcsf no objection here

File: client/state/selectors/utils/revisions/index.js [hunk 1]
```diff
@@ -7,35 +7,34 @@ import { cloneDeep, get, identity } from 'lodash';
...
+	return author
+		? { ...revision, author }
+		: revision;
+};
 
-	return {
-		...revision,
-		author,
-	};
+export function hydrateRevision( state, revision ) {
```
Comment (bperson) [inline client/state/selectors/utils/revisions/index.js]: that `runMaybe` is a pretty neat trick :) 

Only change I see is `hydrateRevision` will return `null` instead of `revision` if it's `false`-y. Given its current usage - in the selectors -, it would mean we have loaded `false`-y revisions in the state in the first place. There is no test for that behaviour since we're entering defensive programming territory and unit tests can pile up really fast :D

Comment (mcsf) [reply client/state/selectors/utils/revisions/index.js]: Yeah, I expected that if we ever step into `if ( ! revision )` then we most likely just have a `null` that got in there somehow — since we expect an object, which is always truthy, can we just establish that we should discard anything else?

Comment (mcsf) [reply client/state/selectors/utils/revisions/index.js]: (if not, we can make this equivalent to pre-refactor code by appending `|| revision` to the `runMaybe( … )` call)

Comment (bperson) [reply client/state/selectors/utils/revisions/index.js]: oh no, I think it's probably better to have it consistently return `null` in the long run, it makes for a more predictable interface :)

Sorry, I should have made it clearer that It's just something to keep in mind in case some dirty state gets in as there is nothing to defend against it in the [reducer](https://github.com/Automattic/wp-calypso/blob/2baa22cebd9c76a853b8e413b65a0ed2d9df0322/client/state/posts/revisions/reducer.js#L39) or in the [data layer](https://github.com/Automattic/wp-calypso/blob/2baa22cebd9c76a853b8e413b65a0ed2d9df0322/client/state/data-layer/wpcom/posts/revisions/index.js#L28)

File: client/lib/post-normalizer/rule-decode-entities.js [hunk 2]
```diff
@@ -11,8 +11,10 @@ import { forEach, forOwn } from 'lodash';
 import { decodeEntities as decode } from 'lib/formatting';
 import safeImageURL from 'lib/safe-image-url';
 
-export default function decodeEntities( post ) {
-	forEach( [ 'excerpt', 'title', 'site_name' ], function( prop ) {
+const DEFAULT_FIELDS = [ 'excerpt', 'title', 'site_name' ];
+
+export default function decodeEntities( post, fields = DEFAULT_FIELDS ) {
+	forEach( fields, function( prop ) {
```
Comment (bisko) [inline client/lib/post-normalizer/rule-decode-entities.js]: This probably can be done a bit better with updated syntax. Something like:

```
fields.forEach( ( prop ) => {
```
