### PR TITLE
Stepper: Fix domains step persistence

### LINKED ISSUE #97176: Stepper: Mobile doesn't show selected domain near the bottom when back from Plans
Start | Stepper

Image

This happens when coming back from Plans

### PR DESCRIPTION
**Pull request by alshakero**
Fixes: https://github.com/Automattic/wp-calypso/issues/97176

## Proposed Changes

- This simplifies the persistence logic of the Unified Domains step and copies over the one in the Unified Plans step.
- It records the `providedDependencies` when submitted by the domain step, rather than the `signupDependencies`. 

## Why are these changes being made?
- So that coming back to the domain step, when picking a free domain, keeps that domain picked during the whole session.
- The persistence of the paid domain, on the other hand, is handled by the cart. 

## Testing Instructions
- Go to /setup/onboarding.
- Pick a free domain.
- Go to plans.
- Go back.
- The free domain should remain picked.

### CODE REVIEW

File: client/landing/stepper/declarative-flow/internals/steps-repository/unified-domains/index.tsx [hunk 1]
```diff
@@ -80,33 +80,32 @@ const RenderDomainsStepConnect = connect(
...
 			<RenderDomainsStepConnect
 				{ ...props }
 				{ ...managedSiteFlowProps }
 				page={ ( url: string ) => window.location.assign( url ) }
-				saveSignupStep={ updateSignupStepState }
-				submitSignupStep={ updateSignupStepState }
+				saveSignupStep={ ( step: ProvidedDependencies ) => {
+					setStepState( ( mostRecentState = { ...stepState, ...step } ) );
+				} }
+				submitSignupStep={ ( _, step: ProvidedDependencies ) => {
```
Comment (alshakero) [inline client/landing/stepper/declarative-flow/internals/steps-repository/unified-domains/index.tsx]: the `_` is the main change here. To pick up the second param instead of the first.

**Review by escapemanuele — APPROVED** [review]
Tested and it works great!
