### PR TITLE
Plugins: Display live chat support only for annual plans

### LINKED ISSUE #61365: [Bug]: Plugins should display Live chat support only for annual plans
### Quick summary

Currently, plugins display `Live Chat Support` depending on the billing period _of the plugin_ while it should depend on the billing period _of the plan_

That was done as part 
- #61212

### Steps to reproduce

1. In a site with a monthly Business plan, 
2. Go to Plugins and select a paid plugin
2. Select Annually period for the plugin

### What you expected to happen

There should not be any message indicating `Live chat support 24x7` as the plan is Monthly billed.

### What actually happened

The Plugin details include `Live chat support 24x7` 
image

### Simple/Atomic

Atomic

### Reproducibility

Consistent

### PR DESCRIPTION
**Pull request by epeicher**
The live chat support message when purchasing a plugin will only be
displayed for annual plans regardless of the billing period of the
plugin.

#### Changes proposed in this Pull Request

* Displays `Live chat support` message only for annual plans
* For monthly plans is displayed the message `Unlimited email support`

|Before | After|
|-------|------|
|CleanShot 2022-02-22 at 18 06 04@2x|CleanShot 2022-02-22 at 18 14 24@2x|
|CleanShot 2022-02-22 at 18 07 17@2x|CleanShot 2022-02-22 at 18 16 35@2x|
|CleanShot 2022-02-22 at 18 11 04@2x|CleanShot 2022-02-22 at 18 17 47@2x|
|CleanShot 2022-02-22 at 18 12 09@2x|CleanShot 2022-02-22 at 18 18 36@2x|

##### Scenario 1
* In a site with either Annual Business or eCommerce plan which is paid **Monthly**
* Add a paid plugin
* Select Monthly billing for the plugin
  * The details of the Purchase and the Support details on the right should include `Unlimited email support`
* Select Annually billing for the plugin
  * The details of the Purchase and the Support details on the right should include `Unlimited email support`

##### Scenario 2
* In a site with either Annual Business or eCommerce plan which is paid **Annually**
* Add a paid plugin
* Select Monthly billing for the plugin
  * The details of the Purchase and the Support details on the right should include `Live chat support 24x7` 
* Select Annually billing for the plugin
  * The details of the Purchase and the Support details on the right should include `Live chat support 24x7`

##### Screenshots
|Monthly Plan|Annual Plan|
|---|---|
|CleanShot 2022-02-23 at 09 12 51@2x|CleanShot 2022-02-23 at 09 10 56@2x|

Fixes #61365

### CODE REVIEW

File: client/my-sites/plugins/plugin-details-CTA/usps.tsx [hunk 1]
```diff
@@ -48,6 +50,12 @@ const USPS: React.FC< Props > = ( {
 
 	const isAnnualPeriod = billingPeriod === IntervalLength.ANNUALLY;
 
+	const selectedSiteId = useSelector( getSelectedSiteId );
+	const currentPlan = useSelector( ( state ) =>
+		selectedSiteId ? getCurrentPlan( state, selectedSiteId ) : undefined
```
Comment (cpapazoglou) [inline client/my-sites/plugins/plugin-details-CTA/usps.tsx]:
```suggestion
		selectedSiteId && getCurrentPlan( state, selectedSiteId )
```

would that work?

File: client/my-sites/plugins/plugin-details-sidebar/index.jsx [hunk 2]
```diff
@@ -19,8 +20,12 @@ const PluginDetailsSidebar = ( {
 	},
 } ) => {
 	const translate = useTranslate();
-	const billingPeriod = useSelector( getBillingInterval );
-	const isAnnualPeriod = billingPeriod === IntervalLength.ANNUALLY;
+
+	const selectedSiteId = useSelector( getSelectedSiteId );
+	const currentPlan = useSelector( ( state ) =>
+		selectedSiteId ? getCurrentPlan( state, selectedSiteId ) : undefined
```
Comment (cpapazoglou) [inline client/my-sites/plugins/plugin-details-sidebar/index.jsx]:
```suggestion
		selectedSiteId && getCurrentPlan( state, selectedSiteId )
```

would that work?

**Review by cpapazoglou — CHANGES_REQUESTED** [review]
The scenarios work as expected but there is one more scenario that we need to take care of:

On site plans that need to be upgraded to business (free, personal, premium) then we will need to check against the billing plan interval if the the current plan is monthly cause that is used to add the correct billing interval of a business to cart.

- If current plan is annual, then users cannot upgrade to monthly busines
- if current plan is monthly, then users can upgrade to monthly business. In that case we shouldn't get Live chat support cause a monthly business plan will get added

CleanShot 2022-02-24 at 13 20 52@2x

**Comment by epeicher** [comment]
Additional changes to cope with upgrades are described in the screenshots below. 

@cpapazoglou could you please confirm if those scenarios work as expected?

|Plan Period|Plugin Monthly | Plugin Annually|
|-------|-------|------|
|Annual|CleanShot 2022-02-25 at 11 45 27@2x|CleanShot 2022-02-25 at 11 46 24@2x|
|Monthly|CleanShot 2022-02-25 at 11 54 42@2x|CleanShot 2022-02-25 at 11 55 42@2x|

⚠️ **Please note** that in the scenario with current plan as Annual, even though the Monthly plugin option is displayed (top-left screenshot above), when clicking on `Purchase and activate` button, only the Annual plan is displayed:
CleanShot 2022-02-25 at 11 59 37@2x

**Review by gcsecsey — CHANGES_REQUESTED** [review]
I've tested the scenarios described, and found some which aren't working as expected yet:

When testing **Scenario 1** with a monthly billed business plan, the CTA and sidebar USPs show different values:
image

Similarly, when testing with a **Free plan**:
image

This is most likely because the sidebar doesn't yet take into account the `shouldUpgrade` flag.

**Comment by gcsecsey** [comment]
I've pushed some proposed changes, to use the same logic in both places. Moreover, I think we could move this logic into a selector (eg. under `state/marketplace/selectors`), which would make it more easy and robust to use this logic.

@epeicher what do you think? Let me know if I can help! 🙂

**Comment by epeicher** [comment]
> I've pushed some proposed changes, to use the same logic in both places. Moreover, I think we could move this logic into a selector (eg. under `state/marketplace/selectors`), which would make it more easy and robust to use this logic.
> 
> @epeicher what do you think? Let me know if I can help! 🙂

Thank you very much @gcsecsey! Also, the idea of a common selector sounds great, I will work on it

**Review by gcsecsey — APPROVED** [review]
I've tested all scnearios again, LGTM!

I only have one small proposal, I think the `isAnnualPeriod` is no longer needed, as `isAnnualPlan` has the same value.

File: client/my-sites/plugins/plugin-details-CTA/usps.tsx [hunk 3]
```diff
@@ -46,8 +47,9 @@ const USPS: React.FC< Props > = ( {
 } ) => {
 	const translate = useTranslate();
 
-	const isAnnualPeriod = billingPeriod === IntervalLength.ANNUALLY;
+	const isAnnualPlan = useSelector( isAnnualPlanOrUpgradeableAnnualPeriod );
 
+	const isAnnualPeriod = billingPeriod === IntervalLength.ANNUALLY;
 	const planDisplayCost = useSelector( ( state ) =>
 		getProductDisplayCost( state, isAnnualPeriod ? PLAN_BUSINESS : PLAN_BUSINESS_MONTHLY )
```
Comment (gcsecsey) [inline client/my-sites/plugins/plugin-details-CTA/usps.tsx:54]:
```suggestion
	const isAnnualPlan = useSelector( isAnnualPlanOrUpgradeableAnnualPeriod );

	const planDisplayCost = useSelector( ( state ) =>
		getProductDisplayCost( state, isAnnualPlan ? PLAN_BUSINESS : PLAN_BUSINESS_MONTHLY )
```

Comment (epeicher) [reply client/my-sites/plugins/plugin-details-CTA/usps.tsx:54]: We would be changing previous logic in that case because `isAnnualPeriod` contains the billing period selected when purchasing a _plugin_ while the new `isAnnualPlan` contains logic related to the _plan_ selected by the user. 

In other words, there is a scenario where `isAnnualPeriod` could be `true` while `isAnnualPlan` could be `false`. For example, if the user has a _Business Monthly_ plan but selects _Annual_ billing period when purchasing the plugin.

Comment (gcsecsey) [reply client/my-sites/plugins/plugin-details-CTA/usps.tsx:54]: That's a good point! My thinking was that the new selector kind of excludes this scenario, because we return either `isAnnualPeriod` or `isAnnualPlan` based on the value of `shouldUpgrade`.

As the only place it's then used is also guarded with `shouldUpgrade`, I'm good with going forward with either version! 🎉 🚢

Comment (epeicher) [reply client/my-sites/plugins/plugin-details-CTA/usps.tsx:54]: That is totally correct! Although, in this scenario, I would prefer to leave the current version for `planDisplayCost` because it reflects a more specific condition. So if you are happy with the current version, I will go ahead and merge the issue.

Thanks for your comments!
