### PR TITLE
Connect sidebar to redux to receive site prop when available

### LINKED ISSUE #14021: WooCommerce: Store Sidebar fails to render after fresh start
#### Steps to reproduce
1. Starting at URL: calypso.localhost:3000/store/products/{site}/add
2. localStorage.clear();
3. indexedDB.deleteDatabase( 'calypso' );
4. refresh
5. store sidebar will fail to render

#### What I expected

Store sidebar should render

#### What happened instead

It doesn't

#### Browser / OS version

N/A

#### Screenshot / Video

N/A

### PR DESCRIPTION
**Pull request by allendav**
Fixes #14021 

To test, 

Starting at URL: calypso.localhost:3000/store/products/{site}/add
localStorage.clear();
indexedDB.deleteDatabase( 'calypso' );
refresh
store sidebar will fail to render initially
ensure sidebar does eventually render after a few seconds (when site id becomes available)

@kellychoffman - thoughts on what we should display while waiting for a site id?

cc @coderkevin

### CODE REVIEW

**Comment by coderkevin** [comment]
@allendav The Calypso docs say we should try to display as much as possible, so maybe disabled menu items?

File: client/extensions/woocommerce/store-sidebar/index.js [hunk 1]
```diff
@@ -118,3 +123,17 @@ export default class StoreSidebar extends Component {
 		);
 	}
 }
+
+function mapStateToProps( state ) {
+	const currentUser = getCurrentUser( state );
+	const selectedSiteId = getSelectedSiteId( state );
+	const isSingleSite = !! selectedSiteId || currentUser.site_count === 1;
+	const siteId = selectedSiteId || ( isSingleSite && getPrimarySiteId( state ) ) || null;
+	const site = getSite( state, siteId );
```
Comment (coderkevin) [inline client/extensions/woocommerce/store-sidebar/index.js]: I wonder if we shouldn't think about putting this information at the base of our app, in order to keep the sidebar in sync with the content...

Comment (allendav) [inline client/extensions/woocommerce/store-sidebar/index.js]: Good idea - done (at least for the sidebar) in https://github.com/Automattic/wp-calypso/pull/14022/commits/2db9bb49f7dd460b832fee14dc3dadb9f7bd27fc

**Comment by allendav** [comment]
@coderkevin wrote:

> @allendav The Calypso docs say we should try to display as much as possible, so maybe disabled menu items?

Agreed! Added disabled-ness in https://github.com/Automattic/wp-calypso/pull/14022/commits/2db9bb49f7dd460b832fee14dc3dadb9f7bd27fc

@jameskoster - please take a look at the styles I added for disabled-ness and let me know what you think - to see the disabled styles, follow the instructions at the top of this pull request

**Comment by jameskoster** [comment]
Committed a change to use the placeholder animation seen in other areas of Calypso while 'waiting'.

fading

The only downside to this is the awkward gap beneath the menu where the background is different. So perhaps we apply the `disabled` class to the main sidebar wrapper instead?

File: client/extensions/woocommerce/index.js [hunk 2]
```diff
@@ -151,15 +155,23 @@ function addStorePage( storePage, storeNavigation ) {
 	} );
 }
 
-function createStoreNavigation( context, next ) {
-	const state = context.store.getState();
-	const selectedSite = getSelectedSite( state );
+function mapStateToProps( state ) {
+	const currentUser = getCurrentUser( state );
+	const selectedSiteId = getSelectedSiteId( state );
+	const isSingleSite = !! selectedSiteId || currentUser.site_count === 1;
```
Comment (belcherj) [inline client/extensions/woocommerce/index.js]: the logic of this and the next line is pretty complex.  Not sure how to make it better but took me a minute to reason through it.

**Comment by jameskoster** [comment]
Been thinking about the disabled state some more and chatted with Kelly. 

Now considering the best approach to be using the placeholder animation, but use block placeholders as well, opposed to the actual text / icon. Kind of like what happens in the Reader;

reader

**Comment by allendav** [comment]
@jameskoster - please take a look now - all placeholder-y goodness

File: client/extensions/woocommerce/index.js (hunk 2 above)
Comment (allendav) [inline client/extensions/woocommerce/index.js]: Yeah, its unfortunately standard fare to make sure we are looking at just one site

Comment (justinshreve) [inline client/extensions/woocommerce/index.js]: Maybe worth creating a new selector or helper function so both this and [and the sidebar code](https://github.com/Automattic/wp-calypso/blob/cafb1a709743d0f4f589def09943373ec53513ba/client/my-sites/sidebar/sidebar.jsx#L599) could take use of it?

**Comment by justinshreve** [comment]
I dig the updated placeholder.

**Comment by kellychoffman** [comment]
Loading animation looks slick! :shipit:

File: client/extensions/woocommerce/index.js (hunk 2 above)
Comment (allendav) [inline client/extensions/woocommerce/index.js]: Hey @justinshreve - good idea - I simplified it a bit in https://github.com/Automattic/wp-calypso/pull/14022/commits/05d496a23240468072a9f63f7b4fd431992c9203

**Comment by allendav** [comment]
@justinshreve @belcherj - good to go?

File: client/layout/sidebar/item.jsx [hunk 3]
```diff
@@ -37,7 +38,10 @@ export default React.createClass( {
 
 	render() {
 		const isExternalLink = isExternal( this.props.link );
-		const classes = classnames( this.props.className, { selected: this.props.selected } );
+		const classes = classnames( 'sidebar__item', this.props.className, {
```
Comment (justinshreve) [inline client/layout/sidebar/item.jsx]: Minor and optional but since this `render()` method uses quite a few props (and some more then once like `link`) it might be worth destructuring above so `this.props` doesn't need repeated so many times.

File: client/layout/sidebar/item.jsx [hunk 4]
```diff
@@ -37,7 +38,10 @@ export default React.createClass( {
...
+			'is-placeholder': this.props.isPlaceholder,
+			selected: this.props.selected
```
Comment (justinshreve) [inline client/layout/sidebar/item.jsx]: Should include a trailing comma.

File: client/state/current-user/selectors.js [hunk 5]
```diff
@@ -44,6 +44,21 @@ export function getCurrentUserLocale( state ) {
...
+ * @param  {Object}  state  Global state tree
+ * @return {?Number}        Current user site count
+ */
+export function getCurrentUserSiteCount( state ) {
+	const user = getCurrentUser( state );
+	if ( ! user ) {
+		return null;
+	}
+
+	return user.site_count || null;
```
Comment (justinshreve) [inline client/state/current-user/selectors.js]: If we have a valid user but they actually don't have any sites (user only account), wouldn't `0` make more sense here?

**Comment by justinshreve** [comment]
Tested again and works. I did notice that it will load the sidebar on a non-WooCommerce site with all the links (Add Product, etc). Maybe in a future PR we could just show some links that would lead people to the store setup flow so they could learn more?

File: client/layout/sidebar/item.jsx (hunk 3 above)
Comment (allendav) [inline client/layout/sidebar/item.jsx]: Agreed! Fixed in https://github.com/Automattic/wp-calypso/pull/14022/commits/ef650dfd7aae2ba7ec9df10dc3bcc3f09e067143

File: client/layout/sidebar/item.jsx (hunk 4 above)
Comment (allendav) [inline client/layout/sidebar/item.jsx]: Agreed! Fixed in https://github.com/Automattic/wp-calypso/pull/14022/commits/ef650dfd7aae2ba7ec9df10dc3bcc3f09e067143 - also switched to using property shorthand

File: client/state/current-user/selectors.js (hunk 5 above)
Comment (allendav) [inline client/state/current-user/selectors.js]: Agreed! Fixed in https://github.com/Automattic/wp-calypso/pull/14022/commits/ef650dfd7aae2ba7ec9df10dc3bcc3f09e067143

**Comment by allendav** [comment]
@justinshreve wrote:

> I did notice that it will load the sidebar on a non-WooCommerce site with all the links (Add Product, etc). Maybe in a future PR we could just show some links that would lead people to the store setup flow so they could learn more?

Yep - there is a separate issue for a "this site doesn't have woocommerce (yet)"

**Comment by justinshreve** [comment]
🚢

File: client/extensions/woocommerce/index.js [hunk 6]
```diff
@@ -151,15 +155,23 @@ function addStorePage( storePage, storeNavigation ) {
...
 
-function createStoreNavigation( context, next ) {
-	const state = context.store.getState();
-	const selectedSite = getSelectedSite( state );
+function mapStateToProps( state ) {
+	let siteId = getSelectedSiteId( state );
+	if ( ! siteId && ( 1 === getCurrentUserSiteCount( state ) ) ) {
+		siteId = getPrimarySiteId( state );
+	}
+	const site = getSite( state, siteId );
```
Comment (coderkevin) [inline client/extensions/woocommerce/index.js]: If this is going to be the way the sidebar always gets the siteId, maybe we should standardize a selector on it so we get the same one. (If we don't do this, we'll end up with a populated sidebar and vacant pages)

File: client/extensions/woocommerce/index.js [hunk 7]
```diff
@@ -151,15 +155,23 @@ function addStorePage( storePage, storeNavigation ) {
...
+	return {
+		site
+	};
+}
+
+function createStoreNavigation( context, next ) {
 	renderWithReduxStore(
 		React.createElement(
-			StoreSidebar, {
+			connect( mapStateToProps )( StoreSidebar ), {
```
Comment (coderkevin) [inline client/extensions/woocommerce/index.js]: I don't know that I've ever seen HOC functions used inside of `createElement()` like this. Not sure how I feel about it.

File: client/extensions/woocommerce/store-sidebar/store-ground-control.js [hunk 8]
```diff
@@ -27,7 +29,7 @@ const StoreGroundControl = ( { site, translate } ) => {
 			<div className="store-sidebar__ground-control-site">
 				<Site
 					compact
-					site={ site }
+					site={ isPlaceholder ? null : site }
```
Comment (coderkevin) [inline client/extensions/woocommerce/store-sidebar/store-ground-control.js]: If `site === null` when it's a placeholder, you wouldn't have to have this ternary.

File: client/state/current-user/selectors.js (hunk 5 above)
Comment (coderkevin) [inline client/state/current-user/selectors.js]: Is that even possible? A site is created for a user by default on WPCOM.

File: client/extensions/woocommerce/index.js (hunk 7 above)
Comment (allendav) [inline client/extensions/woocommerce/index.js]: Um I did this because I thought you had a good suggestion here:

 https://github.com/Automattic/wp-calypso/pull/14022#discussion_r116342627

In order to pass the site into the sidebar as a prop, and have that prop come from state (and thereby keep the sidebar "in sync", is this not the only way?

File: client/extensions/woocommerce/index.js (hunk 6 above)
Comment (allendav) [inline client/extensions/woocommerce/index.js]: Agreed - I've added the selector in https://github.com/Automattic/wp-calypso/pull/14022/commits/3c0ec04fc96a5d46464a6d123899c97b94c4878a

File: client/extensions/woocommerce/store-sidebar/store-ground-control.js (hunk 8 above)
Comment (allendav) [inline client/extensions/woocommerce/store-sidebar/store-ground-control.js]: Agreed. Fixed in https://github.com/Automattic/wp-calypso/pull/14022/commits/d31a67e864813f2aec6b237bd9de6f28c27c9a3f

**Comment by allendav** [comment]
@belcherj @coderkevin - please approve and then i'll merge this bad boy

File: client/extensions/woocommerce/index.js (hunk 7 above)
Comment (coderkevin) [inline client/extensions/woocommerce/index.js]: It was more the syntax of it. Having it all in one very long line of code. That's all.
When it's all strung together like this, it's easier to miss something while reading it. At least it's that way for me.

Comment (coderkevin) [inline client/extensions/woocommerce/index.js]: On a closer look here, I think I'd recommend that the `connect()` statement be moved to `store-sidebar/index.js` as that's the way we normally use it. We just wrap it in `connect()` before we export.

**Comment by allendav** [comment]
@coderkevin - state is connected to props in the sidebar module itself again - let me know if this is good to go - https://github.com/Automattic/wp-calypso/pull/14022/commits/57501ef4662e51dec3431a8778c6a7c588560785

File: client/extensions/woocommerce/index.js (hunk 7 above)
Comment (allendav) [inline client/extensions/woocommerce/index.js]: Fixed in https://github.com/Automattic/wp-calypso/pull/14022/commits/57501ef4662e51dec3431a8778c6a7c588560785

**Comment by allendav** [comment]
Squashed

File: client/layout/sidebar/item.jsx [hunk 9]
```diff
@@ -37,31 +36,26 @@ export default React.createClass( {
 	},
 
 	render() {
-		const { className, children, icon, isPlaceholder, label, link,
-			onNavigate, postType, selected, tipTarget } = this.props;
```
Comment (coderkevin) [inline client/layout/sidebar/item.jsx]: Just curious why you removed this destructuring line in favor of repeating `this.props` several times below?

Comment (allendav) [inline client/layout/sidebar/item.jsx]: I was putting the file back the way it exists on master
