### PR TITLE
E2E: fix permafailing step in Block Widgets spec.

### LINKED ISSUE #59930: Flaky E2E: Navigate to the Block Widgets Editor
### Spec file

wp-widgets__spec.ts

### TeamCity ID

7220861

### Logs

```
page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "text=/Customi[s|z]ing ▸ Widgets/" to be visible
============================================================
at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-widgets__spec.ts:38:34)
```

image

### PR DESCRIPTION
**Pull request by worldomonation**
#### Changes proposed in this Pull Request

This PR corrects the permanently failing step in the Block Widgets spec for WPCOM Gutenberg build.

Key changes:
- create new component class, `BlockWidgetEditorComponent`.
- implement method to dismiss any modals or tours that appear when the BlockWidgetEditorComponent is loaded.

#### Testing instructions

Check the WPCOM Gutenberg Playwright builds (mobile, desktop) and ensure that:
- [x] Block Widget test is not failing;

Related to https://github.com/Automattic/wp-calypso/issues/59930

### CODE REVIEW

**Comment by worldomonation** [comment]
Verified that Block Widget spec is no longer permafailing in the WPCOM Gutenberg Playwright build:

Desktop
image

Mobile
image

Note that I have skipped the last two steps due to https://github.com/Automattic/wp-calypso/issues/59960.

File: test/e2e/specs/specs-wpcom/wp-widgets__spec.ts [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+	setupHooks,
+	TestAccount,
+	BlockWidgetEditorComponent,
+	skipDescribeIf,
+} from '@automattic/calypso-e2e';
+import { Page } from 'playwright';
+
+const accountName = BrowserHelper.targetGutenbergEdge()
+	? 'gutenbergSimpleSiteEdgeUser'
+	: 'gutenbergSimpleSiteUser';
```
Comment (fullofcaffeine) [inline test/e2e/specs/specs-wpcom/wp-widgets__spec.ts:18]: If my memory doesn't fail, we recently changed those users due to problems related to the nux dialogs, no?

**Review by fullofcaffeine — APPROVED** [review]
Left a small question, but LGTM!

File: test/e2e/specs/specs-wpcom/wp-widgets__spec.ts (hunk 1 above)
Comment (worldomonation) [reply test/e2e/specs/specs-wpcom/wp-widgets__spec.ts:18]: You are correct, for Calypso tests I switched it over to `simpleSitePersonalPlanUser`. 

Sadly it turns out the nux dialog is an ongoing issue with basically all test accounts that touch the editor in some form or another, so it wasn't the solution I had hoped it would be. We have an ongoing issue at https://github.com/Automattic/wp-calypso/issues/57660. @WunderBart and I iterated and ended up with an approach that forcibly closes the Welcome Tour 100% of the time in the editor.

I'll keep the user as is for now, as the test appears to pass as expected. At _some point_ I plan to do a secrets file clean sweep.
