### PR TITLE
Nav-unification: navigating on mobile:

### LINKED ISSUE #48182: Nav Unification: Smaller Viewport: How to Switch Sites?
#### Steps to reproduce

1. Reduce screen size to 600px or less
2. Click on Reader, then Click on My SItes (brings you to the default site)

#### What I expected

An indicator that I could click on My Sites to switch sites, or a Switch Sites menu option. 

#### What happened instead

No indication of the fact I could switch sites. Although clicking on "My Sites" did bring up the site switcher, on the full desktop view there is an arrow indicating an option. 

#### Browser / OS version

MacOS Catalina v 10.15.7/ Chrome v. Version 86.0.4240.198

#### Screenshot / Video

https://user-images.githubusercontent.com/1398304/103698869-de486400-4f56-11eb-917e-e5644ad6702d.mov

#### Context / Source

#manual-testing

### PR DESCRIPTION
**Pull request by cpapazoglou**
#### Changes proposed in this Pull Request

* when switching to a section, also open and focus on the sidebar.
* support having the sidebar open when having `openSidebar=true` in the querystring.

#### Testing instructions

- enable nav-unification ( paYJgx-1af-p2#testing-simple-sites) 
 
Case 1
* switch to a breakpoint `<660px`
* clicking either "My Sites", "Reader", or "Me" should redirect to that section with the sidebar opened

Case 2
* switch to a breakpoint `<660px`
  * load `http://calypso.localhost:3000/home/[DOMAIN]?openSidebar=true` or `http://calypso.localhost:3000/read?openSidebar=true` or `http://calypso.localhost:3000/me?openSidebar=true`. The correct section should load, with the sidebar opened.
  * load `http://calypso.localhost:3000/home/[DOMAIN]?openSidebar`. The My Sites section should open with sidebar closed.
  * load `http://calypso.localhost:3000/home/[DOMAIN]?test=test&openSidebar=true`. The My Sites section should open with sidebar opened.
* no console errors should appear throughout the tests.

Fixes #48182 partially. There will be a Jetpack PR that will append `?openSidebar=true` to "Reader" and "Me" links in the masterbar.

### CODE REVIEW

File: client/layout/masterbar/logged-in.jsx [hunk 1]
```diff
@@ -1,6 +1,7 @@
 /**
  * External dependencies
  */
+import qs from 'qs';
```
Comment (frontdevde) [inline client/layout/masterbar/logged-in.jsx]: We might want to consider only importing the method we need: `import { parse } from 'qs';`.

File: client/layout/masterbar/logged-in.jsx [hunk 2]
```diff
@@ -53,13 +54,22 @@ class MasterbarLoggedIn extends React.Component {
...
+	}
+
 	clickMySites = () => {
 		this.props.recordTracksEvent( 'calypso_masterbar_my_sites_clicked' );
 		if ( ! config.isEnabled( 'nav-unification' ) ) {
 			this.props.setNextLayoutFocus( 'sidebar' );
 		} else if ( 'sites' !== this.props.section || 'sidebar' === this.props.currentLayoutFocus ) {
 			// when my-sites is not focused or sidebar is open, focus to my-sites' content. Else, open my-sites' sidebar.
 			this.props.setNextLayoutFocus( 'content' );
+			this.props.setNextLayoutFocus( 'sidebar' );
```
Comment (frontdevde) [inline client/layout/masterbar/logged-in.jsx]: We now have three different conditionals that all end up setting the layout focus to the sidebar. Can we simplify this?

File: client/layout/masterbar/logged-in.jsx [hunk 3]
```diff
@@ -107,6 +117,7 @@ class MasterbarLoggedIn extends React.Component {
 		} else if ( 'reader' !== this.props.section || 'sidebar' === this.props.currentLayoutFocus ) {
 			// when reader is not focused or sidebar is open, focus to reader's content. Else, open reader's sidebar.
 			this.props.setNextLayoutFocus( 'content' );
+			this.props.setNextLayoutFocus( 'sidebar' );
```
Comment (frontdevde) [inline client/layout/masterbar/logged-in.jsx]: Can we remove the layout focus on `content` if we set it to `sidebar` anyway?

**Review by frontdevde — CHANGES_REQUESTED** [review]
Thanks for working on this, @cpapazoglou!

I tested as per your testing instructions and can confirm that it works as described.

That said, I'm not certain the resulting user experience is ideal. From a user's perspective I would've assumed that clicking one of the top level menu items a second time, would result in the sidebar going away. Currently there seems to be no way for the user to see the default content for the items without them selecting something in the sidebar menu. 

> It would be great to test it out to make sure it feels right.

@sfougnier in https://github.com/Automattic/wp-calypso/issues/48182#issuecomment-758740537 you suggested that it'd be nice to test this. Could you take this PR for a spin with the above in mind and see how it feels from a design perspective? Thank you!

File: client/layout/masterbar/logged-in.jsx (hunk 1 above)
Comment (cpapazoglou) [reply client/layout/masterbar/logged-in.jsx]: Good point, fixed!

File: client/layout/masterbar/logged-in.jsx (hunk 2 above)
Comment (cpapazoglou) [reply client/layout/masterbar/logged-in.jsx]: Sadly, I haven't found a way to simplify them. Bare in mind that 'nav-unification' condition will be gone in some months. I have though, dried up the code here f82036e.

File: client/layout/masterbar/logged-in.jsx (hunk 3 above)
Comment (cpapazoglou) [reply client/layout/masterbar/logged-in.jsx]: Could point, removed.

**Comment by ghost** [comment]
Took a look and agreed with @frontdevde's feedback to make the icon toggle the corresponding menu open and closed. I reviewed that update @cpapazoglou made and it looks good to go!

**Review by frontdevde — APPROVED** [review]
Thanks for iterating on this and improving the user experience, @cpapazoglou! 👏
Thanks for taking a look from a design perspective, @sfougnier! 🙌

LGTM! 👍
