### PR TITLE
Move the "Go to my site" button after the content

### LINKED ISSUE #39127: Domain mapping: Move "Go to my site" button beneath the mapping instructions
On smaller screens the actual domain mapping instructions may be beneath the fold and/or the user may be distracted by the "Go to my site" button and ignore them completely. 

I order to add clarity and reduce support tickets related to domain mapping we should consider moving the "Go to My Site" button to the very bottom of the page and "force" users to scroll past these instructions in the hope that they will read them.

#### Steps to reproduce
1. Register a new site and sign up a for a plan.
2. Choose the "Domain mapping" option and enter a domain name.
3. Notice how the "Go to my site" button is shown above the domain mapping instructions.

#### Suggestion
Move this button beneath the domain mapping instructions.

#### Browser / OS version
MacOS 10.13.6 (17G2307)
Google Chrome 79.0.3945.88

#### Context / Source
#reallife #dogfooding

### PR DESCRIPTION
**Pull request by millerf**
#### Changes proposed in this Pull Request

* Move "Go to my site" button to the bottom in order to add some more importance to the rest of the page content. 

I used `props.children` of `CheckoutThankYouHeader`. I am not sure if this is the best approach, but it is definitely the simplest...

#### Testing instructions

* Link website to your own domain

Fixes #39127

Before:
Screenshot 2020-02-15 at 13 14 02

After:
Screenshot 2020-02-15 at 13 13 08

### CODE REVIEW

**Comment by millerf** [comment]
@gwwar  Can you help me land this one?

**Comment by gwwar** [comment]
We can help review 👍

**Comment by jancavan** [comment]
👍 on moving the button. I think the padding can be improved so there isn't too much white space similar to this quick mockup:

Screen Shot 2020-04-01 at 2 28 31 PM

Thanks @millerf.

**Comment by millerf** [comment]
@jancavan Unfortunately I cannot test anymore as I have no credits on the account 💵 ...

**Comment by gwwar** [comment]
@jancavan if you're okay with the change here, we can land this first and then we can follow up with the spacing in another PR.

**Comment by millerf** [comment]
I think the spacing is from this line:

https://github.com/millerf/wp-calypso/blob/update/got-to-my-site-button-move/client/my-sites/checkout/checkout-thank-you/style.scss#L91

If you feel like changing it while you are testing....

**Comment by jancavan** [comment]
> if you're okay with the change here, we can land this first and then we can follow up with the spacing in another PR.

Ok, we can handle separately.

**Comment by jancavan** [comment]
LGTM

**Comment by gwwar** [comment]
Let me verify against the other thank you pages. It's all one big component 👍

**Comment by gwwar** [comment]
I'm actually having a lot of trouble hitting this particular thank you page. I did spot check some of the other ones and didn't note any regressions so far. Codewise I think this change is okay to allow rendering of children.

@mmtr  do you mind helping test? I think this is safe but am a little wary of landing near end of day.

**Comment by mmtr** [comment]
Yeah, the checkout thank you component is quite big. I think we need to check [all these purchases](https://github.com/Automattic/wp-calypso/blob/bdd2dd352466b4161350107c0dec9ea4a6a7a423/client/my-sites/checkout/checkout-thank-you/index.jsx#L501-L537) and verify the button looks good in all of them when placed at the bottom.

Let's parallelize the work by updating the list below as we test:

- [ ] Failed purchases.
- [ ] Jetpack plan.
- [ ] Blogger plan.
- [ ] Personal plan.
- [ ] Premium plan.
- [ ] Business plan.
- [ ] eCommerce plan.
- [ ] Domain registration.
- [ ] Google Apps.
- [ ] Domain mapping.
- [ ] Site redirect.
- [ ] Domain transfer.
- [ ] Charge back.
- [ ] Guided transfer.

File: client/my-sites/checkout/checkout-thank-you/index.jsx [hunk 1]
```diff
@@ -592,42 +592,44 @@ export class CheckoutThankYou extends React.Component {
...
-					hasFailedPurchases={ hasFailedPurchases }
-					siteUnlaunchedBeforeUpgrade={ siteUnlaunchedBeforeUpgrade }
-					upgradeIntent={ upgradeIntent }
-					primaryCta={ this.primaryCta }
-					displayMode={ displayMode }
-				/>
-
-				{ ! isSimplified && primaryPurchase && (
-					<CheckoutThankYouFeaturesHeader
+				{
```
Comment (mmtr) [inline client/my-sites/checkout/checkout-thank-you/index.jsx:595]: Minor: This opening curly bracket it is not needed.

File: client/my-sites/checkout/checkout-thank-you/index.jsx [hunk 2]
```diff
@@ -592,42 +592,44 @@ export class CheckoutThankYou extends React.Component {
...
+									isRootDomainWithUs={ isRootDomainWithUs }
+									registrarSupportUrl={ registrarSupportUrl }
+									selectedSite={ selectedSite }
+									selectedFeature={ getFeatureByKey( this.props.selectedFeature ) }
+									sitePlans={ sitePlans }
+								/>
+							</div>
+						) }
+					</CheckoutThankYouHeader>
+				}
```
Comment (mmtr) [inline client/my-sites/checkout/checkout-thank-you/index.jsx:632]: Minor: This closing curly bracket it is not needed.

**Comment by mmtr** [comment]
@millerf can you rebase this branch? I'm sure most of the failing tests should fix themselves after that.

**Comment by millerf** [comment]
@mmtr I removed the unnecessary braces and rebased. I didn't touch the margin as I couldn't really test anything in local. It should be good to land.

**Comment by gwwar** [comment]
Leaving a reminder for me or @kwight to land this tomorrow

**Comment by gwwar** [comment]
Thanks @millerf! 💖

**Comment by daledupreez** [comment]
Thanks, @lancewillett, @gwwar and @mmtr for getting this change reviewed and landed!

Also, a huge thank you to @millerf for the PR and your patience!
