### PR TITLE
Reader: Fix issue with blinking posts

### LINKED ISSUE #54866: Reader: Post position & content blinking due to "is-placeholder" class being added/removed
### Steps to reproduce the behavior

1. https://wordpress.com/read/feeds/12328231
2. Look at the way some posts in the feed are blinking

### Context
4168821-zen

#### Is this specific to the applied theme? Which one?
N/A

#### Does this happen on simple or atomic sites or both?
This is an AT Site.

#### Is there any console output or error text?
Nothing relevant, but I can see that the CSS class name "is-placeholder" would get added and removed from the "blinking" post.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Only affecting this feed/site.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
I can reproduce this when using the Reader to visit this specific site both from my account and the user's account, but I have not seen it affecting other feeds.

#### Screenshot / Video:

Screen Capture on 2021-07-25 at 09-12-35

### PR DESCRIPTION
**Pull request by taipeicoder**
Fixes https://github.com/Automattic/wp-calypso/issues/54866

## Proposed Changes

In the Redux store, reader posts are stored in a map object using the post global ID as key. There are cases where global IDs will collide for the same post available in multiple environments. For instance, compare these posts [A](https://public-api.wordpress.com/rest/v1.2/read/feed/152308815/posts/5123943941) and [B](https://public-api.wordpress.com/rest/v1.2/read/feed/152308815/posts/5139449448). Notice that they are the same payload except for the domain and `feed_item_ID`.

This creates an issue in the reader UI where it displays both posts, but they are endlessly being queried since each one ends up overriding the other in the Redux store. Why? Because every time post A makes a query, the Redux store saves the payload of post A and overrides the one of post B. Then post B needs to make a query since it's no longer available in the Redux store, and ends up overriding the payload of post A.

This PR solves this issue by creating a `feed_item_IDs` to track all feed items that have the same global ID. This way, when doing post lookup, we create additional lookup map entries for all the feed_item_IDs that the post has. Note that this fix is only for the reader UI, it doesn't address what I think it's the root problem which is (1) global IDs should be unique and (2) same post shouldn't be shown twice.

Before:

https://github.com/Automattic/wp-calypso/assets/797888/1a9e0e59-d4d0-4577-9105-f477884147fe

After:

https://github.com/Automattic/wp-calypso/assets/797888/7d684e24-c22a-4958-bf9c-414c8ea433e8

## Testing Instructions

Not sure how to reproduce this issue, but definitely ensure that the change makes sense and doesn't introduce any regression.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/state/reader/posts/reducer.js [hunk 1]
```diff
@@ -20,7 +20,19 @@ export function items( state = {}, action ) {
...
 		case READER_POSTS_RECEIVE:
 			const posts = action.posts || action.payload.posts;
-			return { ...state, ...keyBy( posts, 'global_ID' ) };
+			const postsByDedupedGlobalId = {};
+
+			// Assign a new key in case of global_ID collision.
+			for ( const [ globalId, post ] of Object.entries( keyBy( posts, 'global_ID' ) ) ) {
+				let key = globalId;
+				if ( state[ globalId ] && state[ globalId ].feed_item_ID !== post.feed_item_ID ) {
+					key = `${ globalId }-${ post.feed_item_ID }`;
```
Comment (Addison-Stavlo) [inline client/state/reader/posts/reducer.js]: Instead of looping to find a collision and assigning a different key if there is one,  would it make sense to just change the original key to something like this in the first place?

**Review by Addison-Stavlo — APPROVED** [review]
Thank you for looking into this Griffith!

Unfortunately I cannot repro the flickering part. But the issue you identified and corresponding fix make sense!

I smoke tested the reader and all seems well.

Minor thought - should we change what we use for the original key instead of specifically looking for collisions?

File: client/state/reader/posts/reducer.js [hunk 2]
```diff
@@ -20,7 +20,19 @@ export function items( state = {}, action ) {
...
+				}
+
+				postsByDedupedGlobalId[ key ] = post;
```
Comment (arthur791004) [inline client/state/reader/posts/reducer.js]: Does it affect the `seen` feature below as it seems to use the `global_ID` to mark whether the post is seen or not 🤔

File: client/state/reader/posts/reducer.js (hunk 1 above)
Comment (taipeicoder) [reply client/state/reader/posts/reducer.js]: @Addison-Stavlo that's a good point! As @arthur791004 pointed out in the comment below, we might not be able to mutate the key without consequences... let me think of another approach.

File: client/state/reader/posts/reducer.js (hunk 2 above)
Comment (taipeicoder) [reply client/state/reader/posts/reducer.js]: Good point... let me think of another approach.

**Comment by taipeicoder** [comment]
@Addison-Stavlo @arthur791004 I'm proposing another approach that doesn't modify the global ID, please take a look and let me know what you think!

**Review by arthur791004 — APPROVED** [review]
Looks good 👍

File: client/state/reader/posts/reducer.js [hunk 3]
```diff
@@ -20,7 +20,25 @@ export function items( state = {}, action ) {
 	switch ( action.type ) {
 		case READER_POSTS_RECEIVE:
 			const posts = action.posts || action.payload.posts;
-			return { ...state, ...keyBy( posts, 'global_ID' ) };
+			const postsByKey = {};
+
+			// Keep track of all the feed_item_ID that have the same global_ID.
+			// See: https://github.com/Automattic/wp-calypso/pull/88408
+			posts.map( ( post ) => {
```
Comment (Addison-Stavlo) [inline client/state/reader/posts/reducer.js]: Is there a specific reason we are using `.map` here (as well as in the file below) ?

In both instances we never use the mapped array result, nor do the callbacks give any mapped values. Would it make sense to use `forEach` ?

**Review by Addison-Stavlo — COMMENTED** [review]
In general this seems reasonable. Pinging @roo2 and @eoigal as potential reviewers as well, in case they have more insight with some of these items.

File: client/state/reader/posts/reducer.js (hunk 3 above)
Comment (taipeicoder) [reply client/state/reader/posts/reducer.js]: Good catch! Yes `forEach` is more appropriate here.

**Comment by taipeicoder** [comment]
> In general this seems reasonable. Pinging @roo2 and @eoigal as potential reviewers as well, in case they have more insight with some of these items.

One concern is about the performance impact, especially in the post lookup. That said, duplication of global_ID seems rare enough for it to not be a worry.
