### PR TITLE
Fixed the navigation not opening on mobile for the Calypso settings pages

### LINKED ISSUE #54068: Nav Unification: menu not appearing on mobile for some Calypso pages
The issue is reproduced on mobile resolutions, for the following Calypso sections:
- Settings > Discussion
- Settings > Performance
- Settings > Writing
- Settings > Jetpack (on Atomic)
- Posts > Tags (Calypso)
- Posts > Categories (Calypso)

### Steps to reproduce the behavior

1. Go to WordPress.com and select a site.
2. Switch your browser to a mobile resolution (from DevTools select a mobile device).
3. Click on the WordPress logo from masterbar to open the navigation.
4. Go to the Settings menu and click on `Discussion`.
5. You'll be redirected to the Calypso page. 
6. Click again on the WordPress icon in the menubar.

#### What I expected to happen
The navigation should appear so that the user can navigate to another section.

#### What actually happened
Nothing happens. The user is stuck on the page. Furthermore, if the user is on Chrome Android, the native browser back button is also not working.

#### Is this specific to the applied theme? Which one?
No
#### Does this happen on simple or atomic sites or both?
Both
#### Is there any console output or error text?
No
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Both Atomic and Simple sites on mobile viewports.

### PR DESCRIPTION
**Pull request by BogdanUngureanu**
Fixes the issue on mobile devices that prevents the users to open the navigation menu on several pages.

#### Changes proposed in this Pull Request

* Moved the `settings/*` paths from `sections.js` into the site-settings module.
* Changed the My Sites element to a button/a dynamically depending on whether it gets a URL or not.

#### Testing instructions
- Use Calypso live or checkout this branch on your local Calypso environment.
- Resize the browser size to a mobile resolution.
- Go to the following URLs and check that the menu opens and closes on the following sections:
- Settings > Discussion  (Calypso)
- Settings > Performance  (Calypso)
- Settings > Writing  (Calypso)
- Settings > Jetpack (on Atomic)
- Posts > Tags (Calypso)
- Posts > Categories (Calypso)

Fixes https://github.com/Automattic/wp-calypso/issues/54068

### CODE REVIEW

File: client/sections.js [hunk 1]
```diff
@@ -134,36 +134,6 @@ const sections = [
 		module: 'calypso/my-sites/posts',
 		group: 'sites',
 	},
-	{
```
Comment (BogdanUngureanu) [inline client/sections.js:137]: These paths have been moved directly in the site-settings module in order to avoid triggering the section-middleware twice. The main issue was that the generic `/settings` path was converted to a regex that conflicted with the other settings specific pages (e.g. settings/writing). 

When that happened, the `sections-middleware.js` was called twice when the navigation was opened. Because of this, the navigation toggled (with an redux action, as it should) and immediately un-toggled (because the middleware was fired a second time, which in turned triggered the redux action once again).

However, while this implementation works on my environment, my main concern is if there are any sizeable performance effects we should be aware of because we've moved these paths into the site-settings module, instead of loading them asynchronously individually (from my understanding, that's what we did before this change).

File: client/layout/masterbar/item.jsx [hunk 2]
```diff
@@ -36,30 +37,43 @@ class MasterbarItem extends Component {
...
+		const attributes = {
+			'data-tip-target': this.props.tipTarget,
+			onClick: this.props.onClick,
+			title: this.props.tooltip,
+			className: itemClasses,
+			onTouchStart: this.preload,
+			onMouseEnter: this.preload,
+		};
+
+		if ( this.props.url ) {
```
Comment (tjcafferkey) [inline client/layout/masterbar/item.jsx:67]: Changed to a `button` element depending on whether a `url` was available. In some cases `url` will be `''` and in other cases an incorrect URL is getting set when one doesn't exist, by some other method (Possibly `page`? But cant be sure) [see here](https://github.com/Automattic/wp-calypso/blob/trunk/client/layout/masterbar/logged-in.jsx#L194-L196)

File: client/layout/masterbar/logged-in.jsx [hunk 3]
```diff
@@ -94,6 +94,7 @@ class MasterbarLoggedIn extends React.Component {
 	clickMySites = () => {
 		this.props.recordTracksEvent( 'calypso_masterbar_my_sites_clicked' );
 		this.handleLayoutFocus( 'sites' );
+		this.props.activateNextLayoutFocus();
```
Comment (tjcafferkey) [inline client/layout/masterbar/logged-in.jsx:97]: This is because the `activateNextLayoutFocus` action runs on route change in `sections-middleware.js` but in some cases there isn't a URL for the route to change to (see [previous comment](https://github.com/Automattic/wp-calypso/pull/54203#discussion_r662193654)). See this in action [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/sections-middleware.js#L26)

File: test/e2e/lib/components/sidebar-component.js [hunk 4]
```diff
@@ -200,7 +200,7 @@ export default class SidebarComponent extends AsyncBaseContainer {
 		const isOpen = await driverHelper.isElementLocated( this.driver, openSidebarLocator );
 
 		if ( ! isOpen ) {
-			const mySitesButtonLocator = By.css( 'a[data-tip-target="my-sites"]' );
```
Comment (tjcafferkey) [inline test/e2e/lib/components/sidebar-component.js:203]: Changed this because it isn't always going to be a `</a>` since this PR changes the element based on whether it's given a URL prop.

File: client/sections.js (hunk 1 above)
Comment (cpapazoglou) [reply client/sections.js:137]: The changes test well for me but I am worried of the changes we introduce here. 

> The main issue was that the generic /settings path was converted to a regex that conflicted with the other settings specific pages (e.g. settings/writing).

Could we maybe fix this which seems like the root of the problem?

Comment (BogdanUngureanu) [reply client/sections.js:137]: Unfortunately I think that would be higher impact change since the regex pattern is automatically generated by a [generic helper function](https://github.com/Automattic/wp-calypso/blob/trunk/client/utils.js) that's used on all paths in Calypso. I think in theory we could make something more configurable, but that would be a bit out of scope and personally I think would be a bit risky. 

From a functional perspective, in the worse case scenario, this approach would affect only the routes we've extracted, which are known.

**Comment by BogdanUngureanu** [comment]
@Automattic/team-calypso If you have the capacity do you think you could review this since it's high impact change? Due to our unfamiliarity with this part of the codebase we would prefer a second opinion.
If you're not the most appropriate team for this then apologies, please could you point me in the right direction if possible.

File: client/sections.js (hunk 1 above)
Comment (cpapazoglou) [reply client/sections.js:137]: The problem seems to be that
`activateSection()` runs twice
https://github.com/Automattic/wp-calypso/blob/ed3e91545e431da92beeffcbe80289eadde067c0/client/sections-middleware.js#L24

because this regex
`return new RegExp( '^' + path + '(/.*)?$' );`
https://github.com/Automattic/wp-calypso/blob/60069449be91a6618d3d250fa9ccff8be2248b31/client/utils.js#L8 

makes eg `/settings/discussion` also match `/settings`. 

The problem didn't appear in the past cause these menus were in a secondary navigation so accessing them wouldn't require to open the sidebar. We have removed the secondary navigation here https://github.com/Automattic/wp-calypso/pull/53824

Comment (cpapazoglou) [reply client/sections.js:137]: I probably echo your discoveries, disregard in that case. I am just keeping notes.

Comment (BogdanUngureanu) [reply client/sections.js:137]: That's correct, thanks for the additional comment. 
> The problem didn't appear in the past cause these menus were in a secondary navigation so accessing them wouldn't require to open the sidebar

I don't think the change was introduced in there, I think it was present before this was introduced (that PR doesn't include any changes on how we do the routing). I think before the change the issue wasn't as visible as is now, since the menus were in a subsection (and possible reproducing only by refreshing the page?).

Also, the issue was also present in Posts > Categories and Posts > Tags.

Comment (cpapazoglou) [reply client/sections.js:137]: Switching the `'/settings'` path to `'/settings/general'` in `client/sections.js` works well for me regarding the mobile menu opening. And anyway `settings` did redirect to `settings/general` already.

BUT, whenever I open the menu I get redirected to the initial screen I booted the app. I suppose this is fixed with the part 2 of this fix?

File: client/sections.js [hunk 5]
```diff
@@ -134,36 +134,6 @@ const sections = [
...
-	},
-	{
-		name: 'settings-jetpack',
-		paths: [ '/settings/jetpack' ],
-		module: 'calypso/my-sites/site-settings/settings-jetpack',
-		group: 'sites',
-	},
 	{
 		name: 'settings',
 		paths: [ '/settings' ],
```
Comment (cpapazoglou) [inline client/sections.js:139]:
```suggestion
		paths: [ '/settings/general' ],
```

File: client/sections.js (hunk 1 above)
Comment (BogdanUngureanu) [reply client/sections.js:137]: > Switching the '/settings' path to '/settings/general' in client/sections.js works well for me regarding the mobile menu opening. And anyway settings did redirect to settings/general already.

That's what we initially did, but Miguel pointed out that doing so we'll break the current behaviours:
- A user going to wordpress.com/settings/ (note the missing domain) will redirect the user to the site selection component where they'll choose which site they'll be redirected to.
- A user going to wordpress.com/settings/writing (or any other submenu like security, jetpack, performance, etc) will also have to be redirected to the site selection component.

>  BUT, whenever I open the menu I get redirected to the initial screen I booted the app. I suppose this is fixed with the part 2 of this fix?

Yup, that's correct.

File: client/layout/masterbar/item.jsx (hunk 2 above)
Comment (cpapazoglou) [reply client/layout/masterbar/item.jsx:67]: Thanks for refactoring this!

File: client/layout/masterbar/logged-in.jsx (hunk 3 above)
Comment (cpapazoglou) [reply client/layout/masterbar/logged-in.jsx:97]: The URL is set here 
https://github.com/Automattic/wp-calypso/blob/f798ce57dbcf909766de015b2ed43d54aefee616/client/layout/masterbar/logged-in.jsx#L195-L197

it is set to `mySitesUrl = ''` as a workaround so that we avoid changing URL when for example you are in `/settings` and you try opening the sidebar (applicable only when in `my-sites` section). 

I am not sure whether this change is needed. Can you elaborate?

Comment (BogdanUngureanu) [reply client/layout/masterbar/logged-in.jsx:97]: Hmmm... this is still needed because in the Item component we are checking to see if the url is empty or not, in order to determine if we should display a button or a link. We could move it of course, but maybe we should keep the Item component decoupled of this condition? 🤔

File: client/sections.js (hunk 1 above)
Comment (cpapazoglou) [reply client/sections.js:137]: > A user going to wordpress.com/settings/ (note the missing domain) will redirect the user to the site selection component where they'll choose which site they'll be redirected to.

This would need to be `wordpress.com/settings/general` or we can add a redirect.

> A user going to wordpress.com/settings/writing (or any other submenu like security, jetpack, performance, etc) will also have to be redirected to the site selection component.

This is fixed by doing the same as `/settings/podcasting/:site_id` where a `/settings/podcasting` is also declared here 
https://github.com/Automattic/wp-calypso/blob/28810f1dd55bb7cb25b38cebf3cfb1488e580b04/client/my-sites/site-settings/settings-writing/index.js#L39-L49

The way that currently actually works in production is very interesting, I would say that it works by accident due to that regex.

Removing those `/settings/*` sections would still trigger the `activateSection()` for `/settings` which is something we wouldn't want anyway right?

I may be wrong though, and all the above was intended 😄!

File: client/sections.js (hunk 5 above)
Comment (tjcafferkey) [reply client/sections.js:139]: @cpapazoglou This will not work as by changing that there is no `/settings` catch all route which should render the site picker ([https://wordpress.com/settings/](https://wordpress.com/settings/)). If you add `/settings` as well as `/settings/general` you will still get the exact same bug

File: client/layout/masterbar/logged-in.jsx (hunk 3 above)
Comment (cpapazoglou) [reply client/layout/masterbar/logged-in.jsx:97]: I am not sure we are referring to the same thing Bogdan?
`this.handleLayoutFocus( 'sites' );` is already triggering `setNextLayoutFocus()`. Why do we also need `activateNextLayoutFocus`?

Comment (tjcafferkey) [reply client/layout/masterbar/logged-in.jsx:97]: @cpapazoglou AFAIK there is a difference between between _setting_ the next layout focus and _activating_ the next layout focus.

By setting it I believe you are making sure that when it's next activated (which is what we want to do, to toggle the sidebar) that it's readily set the value in advance.

Usually the set value is activated on route change [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/sections-middleware.js#L26) but because there isn't _always_ going to be a route change (because we removed the empty anchor href - it was being pre-populated with an incorrect URL at times, see [here](https://github.com/Automattic/wp-calypso/pull/54203#discussion_r662193654)) we activated the next layout focus here.

You can confirm this by commenting out `this.props.activateNextLayoutFocus();` and trying it in action on mobile.

**Review by tyxla — COMMENTED** [review]
I'm not sure I understand why we're merging the settings sections into one single section again, but this feels like a performance regression. We previously had those split to separate sections because a lot is going on in all of them and code splitting is beneficial for performance. Could you please elaborate on that change?

**Comment by BogdanUngureanu** [comment]
Hi @tyxla, thanks for responding. 

We've moved the settings sections in one place [because there was a conflict between the `/settings` ](https://github.com/Automattic/wp-calypso/pull/54203#discussion_r662103478)path defined in [sections.js ](https://github.com/Automattic/wp-calypso/blob/trunk/client/sections.js#L138)and the other specific sections (e.g. `settings/writing` path) that triggered the [sections-middleware.js](https://github.com/Automattic/wp-calypso/blob/trunk/client/sections-middleware.js#L60) multiple times because the regex pattern (generated by the [pathToRegExp](https://github.com/Automattic/wp-calypso/blob/trunk/client/utils.js#L3) helper function) was matched on /settings and also on the specific path when users were on pages like wordpress.com/settings/writing/:site-url. 

Because of this, the Redux action `LAYOUT_NEXT_FOCUS_ACTIVATE` was dispatched twice (toggling and untoggling the sidebar). 

We had performance concerns as well but we thought that this approach was the safest when comparing the alternatives we've considered. Of course, any alternatives are also welcomed. :)

**Review by tyxla — COMMENTED** [review]
Thanks for explaining, I see now.

I'm not particularly happy with the solution, though, it doesn't seem like we're fixing it in the root, but we're working around the problem. An ideal solution would be in the section middleware where we wouldn't allow for multiple sections to be handled at the same route - it could be implemented as an option in the section definition that we could enable specifically for the settings. That will allow us to avoid breaking any sections that currently rely on the present section middleware behavior.

**Comment by BogdanUngureanu** [comment]
@tyxla, I fully agree with you, it's not a perfect solution but it solves a high impact bug on mobile we currently have on production: the users are not able to open the navigation on several pages, and if they click multiple times on the nav unification icon, browser's native back button won't also work.

To move this forward, I think we could merge this PR and continue with a generic solution in a separate PR. I've created a [follow-up task](https://github.com/Automattic/wp-calypso/issues/54239) that proposes to handle the root cause (based on your feedback, thanks!) and I've also moved it on our iteration board.

Is this something that you can agree with?

**Comment by tyxla** [comment]
> @tyxla, I fully agree with you, it's not a perfect solution but it solves a high impact bug on mobile we currently have on production: the users are not able to open the navigation on several pages, and if they click multiple times on the nav unification icon, browser's native back button won't also work.
> 
> To move this forward, I think we could merge this PR and continue with a generic solution in a separate PR. I've created a [follow-up task](https://github.com/Automattic/wp-calypso/issues/54239) that proposes to handle the root cause (based on your feedback, thanks!) and I've also moved it on our iteration board.
> 
> Is this something that you can agree with?

Sure! As long as we address this in the root and revert the settings to multiple sections in the short term, that sounds good to me 👍

**Review by tjcafferkey — APPROVED** [review]
