### PR TITLE
Reader: fix Following intro banner

### LINKED ISSUE #47984: Reader: intro banner is no longer shown to new users
#### Steps to reproduce

1. Starting at URL: http://wordpress.com/start/reader
2. Sign up for a new account
3. Navigate to Reader at /read
4. Notice there is no intro banner displayed

#### What I expected

Intro banner displayed at the top of the Followed Sites stream.

#### What happened instead

Banner is missing.

This may be a regression related to the launch of voting banners recently.

#### Screenshot / Video

image

#### Context / Source

@sirino wrote about the new user experience in p5PDj3-4WY-p2.

### PR DESCRIPTION
**Pull request by bluefuton**
#### Changes proposed in this Pull Request

In p5PDj3-4WY-p2 we noticed that the Reader following intro banner was not being displayed for new users. This PR restores it.

Fixes #47984.

Screen Shot 2020-12-07 at 15 40 18

#### Testing instructions

1. Sign up as a brand new user (http://calypso.localhost:3000/start/reader is nice and quick). 
2. Ensure that you're shown the Reader intro banner pictured above at http://calypso.localhost:3000/read.
3. Ensure that you can dismiss the intro banner using the 'x' icon.

### CODE REVIEW

File: client/reader/following/main.jsx [hunk 1]
```diff
@@ -54,16 +53,14 @@ const FollowingStream = ( props ) => {
...
-	const voteBanner = <FollowingVoteBanner />;
 	const markAllAsSeen = ( feedsInfo ) => {
 		const { feedIds, feedUrls } = feedsInfo;
 		dispatch( requestMarkAllAsSeen( { identifier: SECTION_FOLLOWING, feedIds, feedUrls } ) );
 	};
-
 	/* eslint-disable wpcalypso/jsx-classname-namespace */
 	return (
 		<Stream { ...props }>
-			{ voteBanner ? voteBanner : <FollowingIntro /> }
```
Comment (bluefuton) [inline client/reader/following/main.jsx:66]: This logic didn't work, because `voteBanner` didn't contain the rendered output of the component.

**Review by jsnmoon — APPROVED** [review]
Tests as described 👍
