### PR TITLE
Editor: Always focus title field on new draft

### LINKED ISSUE #1622: Editor: title is not autofocused for new posts started from wtihin the editor
Steps to reproduce:

1. Open any post
1. Click the pencil icon in the top toolbar
1. Select a blog if prompted
1. Once a new post has been started, check to see if the title field is autofocused

<strong>Result:</strong> the title field is not autofocused if you start a new post from within the editor. ([8s](https://cloudup.com/cvGxHSWzRMV))

/hat tip @kriskarkoski for the original report

### PR DESCRIPTION
**Pull request by timmyc**
Fixes #1622 

When you first open the editor via the pencil or add in a site sidebar, the title field is focused and ready to receive a witty post title.  Once within the editor though, any action that results in another new post - the title field is not auto focused.  This branch aims to focus the title field on all new drafts - regardless of how one arrives at that new draft ( only on non-mobile viewports ).

__To Test__
- Open up the editor via the pencil in the masterbar 
- Note the title field will be focused on a desktop viewport sized browser
- Expand your draft drawer, load in a draft post - or load an existing published post
- Note the title field does not focus
- Now click the pencil again, select a site if applicable
- Once the new post loads, note that the title field is again focused

### CODE REVIEW

File: client/post-editor/editor-title/index.jsx [hunk 1]
```diff
@@ -4,6 +4,7 @@
 import React, { PropTypes } from 'react';
 import classNames from 'classnames';
 import omit from 'lodash/object/omit';
+import ReactDOM from 'react-dom';
```
Comment (aduth) [inline client/post-editor/editor-title/index.jsx]: I have a feeling this will become an ongoing battle ( :smile: ), but per our naming conventions, this should be `ReactDom` ([reference](https://github.com/Automattic/wp-calypso/blob/master/docs/coding-guidelines/javascript.md#naming-conventions)).

File: client/post-editor/editor-title/index.jsx [hunk 2]
```diff
@@ -40,6 +41,23 @@ export default React.createClass( {
...
+		}
+
+		// If next post is new, or the next site is different, focus title
+		if ( nextProps.isNew && ! this.props.isNew ||
+			( nextProps.isNew && ( this.props.site && nextProps.site ) && ( this.props.site.ID !== nextProps.site.ID ) )
+		) {
+			this.setState( {
+				isFocused: true
+			}, () => {
+				ReactDOM.findDOMNode( this.refs.titleInput ).focus();
```
Comment (aduth) [inline client/post-editor/editor-title/index.jsx]: Do you think it'd be useful to add a `focus` method to `<FormTextInput />` so that it's easier to call as `this.refs.titleInput.focus();` ?

File: client/post-editor/editor-title/index.jsx (hunk 1 above)
Comment (timmyc) [inline client/post-editor/editor-title/index.jsx]: I may or may not have done this on purpose :trollface: - well it is what the deprecation notice told me to use in the console :laughing:

File: client/post-editor/editor-title/index.jsx (hunk 2 above)
Comment (timmyc) [inline client/post-editor/editor-title/index.jsx]: Seems like a worthy addition - I will add that in.

**Comment by timmyc** [comment]
@aduth added `focus()` to `<FormTextInput/>` in cc8981c - also took the opportunity to cleanup the component a bit, _and_ used `ReactDom`.

File: client/components/forms/form-text-input/index.jsx [hunk 3]
```diff
@@ -19,25 +19,31 @@ module.exports = React.createClass( {
...
 
-	render: function() {
-		var otherProps = omit( this.props, [ 'className', 'type' ] ),
-			classes = classNames( {
-				'form-text-input': true,
-				'is-error': this.props.isError,
-				'is-valid': this.props.isValid
-			} );
+	focus() {
+		ReactDom.findDOMNode( this.refs.textField ).focus();
```
Comment (aduth) [inline client/components/forms/form-text-input/index.jsx]: Part of the benefit of moving `focus` to `<FormTextInput />` is that now you have access to the "raw" DOM element, so you no longer need `findDOMNode`. Here, `this.refs.textField` is the a reference to the DOM node itself, so this can simply be `this.refs.textField.focus()` and you can drop the `react-dom` dependency.

File: client/components/forms/form-text-input/index.jsx [hunk 4]
```diff
@@ -1,16 +1,16 @@
 /**
  * External dependencies
  */
-var React = require( 'react/addons' ),
-	classnames = require( 'classnames' ),
-	omit = require( 'lodash/object/omit' ),
-	classNames = require( 'classnames' );
+import React from 'react/addons';
```
Comment (aduth) [inline client/components/forms/form-text-input/index.jsx]: This module doesn't use addons. Can we remove this `/addons` suffix while we're already here?

**Comment by timmyc** [comment]
Thanks @aduth - updated.

File: client/components/forms/form-text-input/index.jsx [hunk 5]
```diff
@@ -19,25 +18,31 @@ module.exports = React.createClass( {
...
-				'form-text-input': true,
-				'is-error': this.props.isError,
-				'is-valid': this.props.isValid
-			} );
+	focus() {
+		this.refs.textField.focus();
+	},
+
+	render() {
+		const otherProps = omit( this.props, [ 'className', 'type', 'ref' ] );
```
Comment (aduth) [inline client/components/forms/form-text-input/index.jsx]: I think you could have left `ref` out, since I don't think `ref` is passed as a prop even when assigned in a parent component, and because you override it after applying the spread properties to the `<input >` element. In fact, this whole omit statement could be left out altogether -

`<input { ...this.props } ref="textField" type={ type } className={ classes } />`

It's a small detail, so not to hold up merge.

File: client/post-editor/editor-title/index.jsx [hunk 6]
```diff
@@ -40,6 +40,23 @@ export default React.createClass( {
...
+
+		// If next post is new, or the next site is different, focus title
+		if ( nextProps.isNew && ! this.props.isNew ||
+			( nextProps.isNew && ( this.props.site && nextProps.site ) && ( this.props.site.ID !== nextProps.site.ID ) )
+		) {
+			this.setState( {
+				isFocused: true
+			}, () => {
+				this.refs.titleInput.focus();
+			} )
```
Comment (aduth) [inline client/post-editor/editor-title/index.jsx]: Missing semi-colon.

File: client/components/forms/form-text-input/index.jsx [hunk 7]
```diff
@@ -19,25 +18,31 @@ module.exports = React.createClass( {
...
+		const { className, type, selectOnFocus } = this.props;
+		const classes = classNames( {
```
Comment (aduth) [inline client/components/forms/form-text-input/index.jsx]: Could probably include `className` in this `classNames` call to avoid the need to call it a second time below. This is legacy but figured worth pointing out.

**Comment by aduth** [comment]
Minor details be minor details. This works well in my testing :+1:

**Comment by lancewillett** [comment]
Needs refresh.

**Comment by kellychoffman** [comment]
:+1: Nice. Looks good.
