### PR TITLE
Signup: don't use page.js for external URLs on signup completion redirects

### LINKED ISSUE #25886: Signup: Unable to proceed at last step
This issue is not reproducible each time, here are approximate steps:
1. Sign up at wordpress.com/start
2. Go through signup (I chose porfolio, a .wp.com address, and a free plan)
3. See message that things are being set up in the background
4. See button that asks me to continue
5. See that button doesn't work, and see this error message:
```
Uncaught DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'https://valtest20180705.wordpress.com/' cannot be created in a document with origin 'https://wordpress.com' and URL 'https://wordpress.com/start/user'.
```
Apologies, I don't have screenshots or more detailed info!

This is not reproducible every time I sign up, maybe it's an A/B test?

@gwwar is thinking maybe we're using page.js instead of a normal link.

### PR DESCRIPTION
**Pull request by mattwiebe**
page.js is for internal navigation via `window.location.pushState` and although it will fall back to `window.location.href` in [some unhandled situations](https://github.com/visionmedia/page.js/blob/043e68cfdea0c8adec24c4e719c4af2c956b96e0/index.js#L393), there appear to be edge cases where it tries to push an external URL into the `pushState` stack, producing errors as seen in #25886 and way back in #908

This will simply test for an `^https?://` prefix on a redirect destination URL and call `window.location.href` to navigate to it, bypassing page.js.

Fixes #25886

## To Test

This one is difficult to test, since the issue would only appear sporadically. I have not yet been able to duplicate the reported issue, but I am confident that this will fix it (it is the code path taken in my testing with a new site signup) and will also have the benefit that even a false positive taking the new code path here would still navigate to the desired location, albeit with a full reload.

### CODE REVIEW

File: client/signup/main.jsx [hunk 1]
```diff
@@ -316,6 +316,11 @@ class Signup extends React.Component {
 		}
 
 		if ( userIsLoggedIn ) {
+			// don't use page.js for external URLs (eg redirect to new site after signup)
+			if ( /https?:\/\//.test( destination ) ) {
```
Comment (taggon) [inline client/signup/main.jsx]: A little suggestion: Can you add `^` before `http` to make sure the destination is an external URL?

Comment (mattwiebe) [reply client/signup/main.jsx]: Great catch, I swear I had it in there before. ¯\_(ツ)_/¯

**Comment by alisterscott** [comment]
The e2e tests are just failing as this PR is out of date with changes on master - but no problem for this PR 👍

**Comment by taggon** [comment]
LGTM 👍
