### PR TITLE
Stats: Fix labels (x-axis) offsets related to bar charts

### LINKED ISSUE #73589: Stats: Labels (x-axis) in Years/Weeks/Months view are rendered with an offset in relation to the bars
### Quick summary

image

I think this happens on wide layouts only
* Resizing the window fixes the issue.

To reproduce:

### Steps to reproduce

* Visit the stats page for a site. 
* Click Years
* Reload the page
* Confirm the labels are not aligned to the bars

### What you expected to happen

To not have the bars offset to their labels

image

### What actually happened

~Labels are rendered properly, but bars aren't~

Edit: apparently bars are rendered properly and not labels.

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement. Resizing the Window works

### Platform (Simple and/or Atomic)

Simple, Self-hosted

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by dognose24**
Related to #73589

## Proposed Changes

* Remove the usage of `useCallback` on `handleYAxisSizeChange` to keep the y-axis refreshed with the chart re-rendering, which prevents stopping updating states for drawing the chart.

## Testing Instructions

* Spin up this change with the Calypso Live link.
* Navigate to the Stats `Traffic` page.
* Change the date period to `Years`.
* Ensure the chart x-axis labels are aligned with corresponding bar charts.
* Reload the page plenty of times to ensure the x-axis offsets no longer appear.

|Before (intermittently)|After|
|-|-|
|截圖 2023-02-22 下午11 08 39|截圖 2023-02-22 下午11 10 55|

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by oskosk** [comment]
Thanks @dognose24 . This seems to fix the offset issue, but I perceive a weird flicker on load, that's not present in turnk

### This branch. The first two bars on the left flicker


https://user-images.githubusercontent.com/746152/220670910-ee3921cd-0a97-4e8d-85a7-24260e5d5778.mov




### Trunk

https://user-images.githubusercontent.com/746152/220670545-414974df-1459-43e3-91b9-4d9b701ace2d.mov

**Comment by dognose24** [comment]
@oskosk Thanks for the review!

> perceive a weird flicker on load

I think the flicker comes from the first time of chart rendering to [set the scaleY to 100% for the start animation](https://github.com/Automattic/wp-calypso/blob/trunk/client/components/chart/style.scss#L158-L164).

> that's not present in trunk

In my observation, the phenomenon is _intermittent_. The chart drawing with the original implementation is not stable. Sometimes the chart is drew by thorough rendering from the parent component to the chart component, but occasionally it is updated with the state changes inside the chart component.

##### Trunk
https://user-images.githubusercontent.com/6869813/220692617-fd6b15a5-493e-4206-b9da-435a125f192e.mov

File: client/components/chart/index.jsx [hunk 1]
```diff
@@ -72,15 +71,16 @@ function Chart( {
 		}
 	}, [] );
 
-	const handleYAxisSizeChange = useCallback( ( contentRect ) => {
+	// Prevent using `useCallback` to keep the Y-Axis refresh via useEffect of `useWindowResizeCallback` with re-rendering.
```
Comment (jsnmoon) [inline client/components/chart/index.jsx]:
```suggestion
```
We probably don't need this comment since `useCallback` no longer exists here. In fact, having this comment could confuse new contributors who may have the context of this change.

**Review by jsnmoon — APPROVED** [review]
This appears to fix https://github.com/Automattic/wp-calypso/issues/73589 and is ready to ship.

The flickering bug is a pre-existing issue and can be tackled in a separate PR; @dognose24, could you spin up an issue to track (and fix) the chart flicker bug?

**Comment by dognose24** [comment]
> The flickering bug is a pre-existing issue and can be tackled in a separate PR; @dognose24, could you spin up an issue to track (and fix) the chart flicker bug?

Sure, the tracking issue is here: https://github.com/Automattic/wp-calypso/issues/73699.

**Comment by oskosk** [comment]
Thanks folks!
