### PR TITLE
Domain Picker: Fix unit tests for traintracks events

### LINKED ISSUE #42638: Domain Picker: make tests work again
### Why
For countless reasons, we want to have the confidence that our code works in the way we, developers, intended. Having unit tests is one of the options to build that. 

### What

We'd lost the tests for the package. I've added changes to ensure the tests run in the package, but they seem to break with `ReferenceError: regeneratorRuntime is not defined`.

I've reverted that change (d26e225c928152d05a5ce39b406d600a1de881ff) and we can work to restore the tests in a follow-up.

_Originally posted by @sirreal in https://github.com/Automattic/wp-calypso/pull/42409#issuecomment-633638142_

### A/C
* [ ] All unit tests for traintracks events are enabled
* [ ] All unit tests pass

### PR DESCRIPTION
**Pull request by StefanNieuwenhuis**
#### Changes proposed in this Pull Request

In this Pull Request, we re-enabled unit tests for the `<SuggestionItem/>` component. Mind that we only enabled/polished them and we haven't considered the added value (unit vs. integration vs. e2e tests).

#### Testing instructions

* Checkout this branch.
* Run `yarn && yarn test-packages packages/domain-picker --verbose`.
* Confirm that:
  * [ ] All  tests from `packages/domain-picker/test/suggestion-item.tsx` either pass or skipped (see #51268)

Screenshot 2021-03-22 at 11 45 45

Fixes #42638

### CODE REVIEW

File: packages/domain-picker/test/suggestion-item.tsx [hunk 1]
```diff
@@ -15,24 +16,19 @@ import { render, fireEvent, screen } from '@testing-library/react';
...
-/**
- * disabled the below test suite as these tests have been unmaintained whilst the codebase has moved on
- * and have now become stale. A separate task will be raised to fixed them. See https://github.com/Automattic/wp-calypso/issues/45501
- */
+const renderComponent = ( props = {} ): RenderResult =>
+	render( <SuggestionItem { ...MOCK_PROPS } { ...props } /> );
 
-beforeAll( () => {
-	// eslint-disable-next-line @typescript-eslint/no-explicit-any
-	// ( window as any ).configData = require( '../../../../../../config/test.json' );
```
Comment (StefanNieuwenhuis) [inline packages/domain-picker/test/suggestion-item.tsx]: I removed it since:
1. the path is invalid.
2. it's not required for the tests to run and pass.

File: packages/domain-picker/test/suggestion-item.tsx [hunk 2]
```diff
@@ -15,208 +16,53 @@ import { render, fireEvent, screen } from '@testing-library/react';
...
-			const { rerender } = render( <SuggestionItem { ...props } /> );
+		it( 'should not send a render event when re-rendered with the same props', async () => {
+			const { rerender } = renderComponent();
 
-			recordAnalytics.mockClear();
-
-			rerender( <SuggestionItem { ...props } /> );
-
-			expect( recordAnalytics ).not.toHaveBeenCalled();
+			rerender( <SuggestionItem { ...MOCK_PROPS } /> );
```
Comment (StefanNieuwenhuis) [inline packages/domain-picker/test/suggestion-item.tsx]: This isn't the most beautiful solution but it works.

File: packages/domain-picker/test/suggestion-item.tsx [hunk 3]
```diff
@@ -15,271 +16,62 @@ import { render, fireEvent, screen } from '@testing-library/react';
...
+		it( 'should send an interact event when selected', async () => {
+			renderComponent();
+
+			fireEvent.click( screen.getByRole( 'button' ) );
+
+			expect( MOCK_PROPS.onSelect ).toHaveBeenCalledWith( MOCK_PROPS.domain );
 			} );
 		} );
-
-		it( "doesn't send interact event when deselected", async () => {
```
Comment (StefanNieuwenhuis) [inline packages/domain-picker/test/suggestion-item.tsx]: This test is deleted since this is not how the UI works anymore. See p1616151898022300-slack-C0KDTA48Y

File: packages/domain-picker/test/suggestion-item.tsx [hunk 4]
```diff
@@ -15,293 +16,76 @@ import { render, fireEvent, screen } from '@testing-library/react';
...
 
 describe( 'check conditional elements render correctly', () => {
-	it( 'renders info tooltip for domains that require HSTS', async () => {
-		const testRequiredProps = {
-			domain: 'testdomain.com',
-			cost: '€12.00',
-			railcarId: 'id',
-		};
+	/**
+	 * TODO: Enable & Fix InfoTooltip tests when [#51175](https://github.com/Automattic/wp-calypso/issues/51175) is fixed
```
Comment (StefanNieuwenhuis) [inline packages/domain-picker/test/suggestion-item.tsx]: Addressed here https://github.com/Automattic/wp-calypso/issues/51268

File: packages/domain-picker/test/suggestion-item.tsx [hunk 5]
```diff
@@ -336,68 +120,31 @@ describe( 'check conditional elements render correctly', () => {
...
-		};
-
-		render(
-			<SuggestionItem { ...testRequiredProps } onSelect={ jest.fn() } onRender={ jest.fn() } />
-		);
+	it( 'should render the cost if given prop of cost with a value', async () => {
+		renderComponent( { cost: '€12.00' } );
 
-		expect( screen.queryByText( /Renews at: €12.00/i ) ).toBeTruthy();
+		expect( screen.getByText( /Renews at: €12.00/i ) ).toBeInTheDocument();
```
Comment (StefanNieuwenhuis) [inline packages/domain-picker/test/suggestion-item.tsx]: `queryBy*` should only be used while checking for non-existing elements (see: https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#using-query-variants-for-anything-except-checking-for-non-existence)

File: packages/domain-picker/test/suggestion-item.tsx [hunk 6]
```diff
@@ -15,293 +16,76 @@ import { render, fireEvent, screen } from '@testing-library/react';
...
- */
+const renderComponent = ( props = {} ): RenderResult =>
+	render( <SuggestionItem { ...MOCK_PROPS } { ...props } /> );
 
-beforeAll( () => {
-	// eslint-disable-next-line @typescript-eslint/no-explicit-any
-	// ( window as any ).configData = require( '../../../../../../config/test.json' );
-} );
+describe( 'traintracks events', () => {
+	afterEach( () => {
```
Comment (ciampo) [inline packages/domain-picker/test/suggestion-item.tsx]: Any reasons why you chose `afterEach` instead of `beforeEach`?

File: packages/domain-picker/test/suggestion-item.tsx [hunk 7]
```diff
@@ -15,293 +16,76 @@ import { render, fireEvent, screen } from '@testing-library/react';
...
-			recordAnalytics.mockClear();
+			expect( MOCK_PROPS.onRender ).toHaveBeenCalledTimes( 1 );
+		} );
 
-			rerender( <SuggestionItem { ...props } /> );
+		it( 'should not send a render event when re-rendered with the same props', async () => {
+			const { rerender } = renderComponent();
 
-			expect( recordAnalytics ).not.toHaveBeenCalled();
+			rerender( <SuggestionItem { ...MOCK_PROPS } /> );
```
Comment (ciampo) [inline packages/domain-picker/test/suggestion-item.tsx]: I think the test would be more explicit if re-written like this:

1. Render component first time
2. Clear `onRender` mock
3. Re-render with same props
4. Check that `onRender` hasn't been called (`not.toHaveBeenCalled()`)

File: packages/domain-picker/test/suggestion-item.tsx [hunk 8]
```diff
@@ -15,293 +16,76 @@ import { render, fireEvent, screen } from '@testing-library/react';
...
-			expect( recordAnalytics ).toHaveBeenCalledTimes( 2 );
-			expect( recordAnalytics ).toHaveBeenLastCalledWith(
-				expect.objectContaining( {
-					railcarId: 'id2',
-					result: 'example2.com',
-					trainTracksType: 'render',
-					uiPosition: 2,
-				} )
-			);
+			expect( updatedProps.onRender ).toHaveBeenCalledTimes( 1 );
```
Comment (ciampo) [inline packages/domain-picker/test/suggestion-item.tsx]: Same comment as https://github.com/Automattic/wp-calypso/pull/51177/files#r599343262

I would clear the mock before the re-render, and check that the mock was not called.

File: packages/domain-picker/test/suggestion-item.tsx [hunk 9]
```diff
@@ -15,293 +16,76 @@ import { render, fireEvent, screen } from '@testing-library/react';
...
-				rerender( <SuggestionItem { ...props } /> );
-
-				expect( recordAnalytics ).not.toHaveBeenCalled();
-			} );
+		it( 'should send a render event when domain name and railcarId changes', async () => {
+			const { rerender } = renderComponent();
+			const updatedProps = { ...MOCK_PROPS, domain: 'example1.com', railcarId: 'id1' };
+			rerender( <SuggestionItem { ...updatedProps } /> );
+
+			expect( updatedProps.onRender ).toHaveBeenCalledTimes( 2 );
```
Comment (ciampo) [inline packages/domain-picker/test/suggestion-item.tsx]: I would look into making this check more explicit — for example making sure that the second `onRender` call happened only after the re-render.

File: packages/domain-picker/test/suggestion-item.tsx [hunk 10]
```diff
@@ -15,293 +16,76 @@ import { render, fireEvent, screen } from '@testing-library/react';
...
-				getByLabelText( ( content, element ) => element.textContent === 'example.com' )
-			);
-
-			expect( recordAnalytics ).toHaveBeenCalledWith( {
-				trainTracksType: 'interact',
-				action: 'domain_selected',
-				railcarId,
-			} );
-		} );
+		it( 'should send an interact event when selected', async () => {
```
Comment (ciampo) [inline packages/domain-picker/test/suggestion-item.tsx]: How do we deal with different item types? Since this is a unit test, should we write tests for all types?

It may make sense to add this part to the tests after we re-work the semantics of this Component, so we should probably add a follow-up issue

File: packages/domain-picker/test/suggestion-item.tsx [hunk 11]
```diff
@@ -15,293 +16,76 @@ import { render, fireEvent, screen } from '@testing-library/react';
...
-					trainTracksType: 'interact',
-				} )
-			);
+			expect( MOCK_PROPS.onSelect ).toHaveBeenCalledWith( MOCK_PROPS.domain );
 		} );
 	} );
 } );
-/* eslint-enable */
 
 describe( 'check conditional elements render correctly', () => {
```
Comment (ciampo) [inline packages/domain-picker/test/suggestion-item.tsx]: in line with the rest of the file, this describe call could be renamed `conditional elements` ?

File: packages/domain-picker/test/suggestion-item.tsx [hunk 12]
```diff
@@ -336,114 +120,61 @@ describe( 'check conditional elements render correctly', () => {
...
 
-	it( 'renders recommendation badge if given prop isRecommended true', async () => {
-		const testRequiredProps = {
-			domain: 'testdomain.com',
-			cost: '€12.00',
-			railcarId: 'id',
-			isRecommended: true,
-		};
+	it( 'should render a recommendation badge if given prop isRecommended true', async () => {
+		renderComponent( { cost: '€12.00', isRecommended: true } );
```
Comment (ciampo) [inline packages/domain-picker/test/suggestion-item.tsx]: Is the `cost` property necessary here?

File: packages/domain-picker/test/suggestion-item.tsx [hunk 13]
```diff
@@ -336,114 +120,61 @@ describe( 'check conditional elements render correctly', () => {
...
+	it( 'should not render the recommendation badge if is given prop isRecommended false', async () => {
+		renderComponent( { cost: '€12.00', isRecommended: false } );
 
-		// use `queryBy` to avoid throwing an error with `getBy`
-		expect( screen.queryByText( /Recommended/i ) ).toBeFalsy();
+		expect( screen.queryByText( /Recommended/i ) ).not.toBeInTheDocument();
 	} );
 } );
 
 describe( 'test that suggested items are rendered correctly based on availability', () => {
```
Comment (ciampo) [inline packages/domain-picker/test/suggestion-item.tsx]: Maybe rename to `domain availability` or something similar?

File: packages/domain-picker/test/suggestion-item.tsx [hunk 14]
```diff
@@ -336,114 +120,61 @@ describe( 'check conditional elements render correctly', () => {
...
 		// we have to test for the domain and the TLD separately because they get split in the component
-		expect( screen.queryByText( /testdomain/i ) ).toBeTruthy();
-		expect( screen.queryAllByText( /.com/i ) ).toBeTruthy();
 
-		expect( screen.queryByText( /Unavailable/i ) ).toBeTruthy();
-		expect( screen.queryByText( /Recommended/i ) ).toBeFalsy();
-		expect( screen.queryByRole( 'button' )?.getAttribute( 'disabled' ) ).not.toBe( null );
+		const [ domain, tld ] = MOCK_PROPS.domain.split( '.' );
+		expect( screen.getByText( new RegExp( domain, 'i' ) ) ).toBeInTheDocument();
+		expect( screen.getByText( new RegExp( tld, 'i' ) ) ).toBeInTheDocument();
```
Comment (ciampo) [inline packages/domain-picker/test/suggestion-item.tsx]: Neat 🥃

File: packages/domain-picker/test/suggestion-item.tsx [hunk 15]
```diff
@@ -336,114 +120,61 @@ describe( 'check conditional elements render correctly', () => {
...
-		);
+		renderComponent( { cost: '€12.00', isRecommended: true, isUnavailable: false } );
 
 		// we have to test for the domain and the TLD separately because they get split in the component
-		expect( screen.queryByText( /testdomain/i ) ).toBeTruthy();
-		expect( screen.queryAllByText( /.com/i ) ).toBeTruthy();
+		const [ domain, tld ] = MOCK_PROPS.domain.split( '.' );
+
+		expect( screen.getByText( new RegExp( domain, 'i' ) ) ).toBeInTheDocument();
+		expect( screen.getByText( new RegExp( `${ tld }$`, 'i' ) ) ).toBeInTheDocument();
```
Comment (ciampo) [inline packages/domain-picker/test/suggestion-item.tsx]: (nit) compared to the [same check in the previous test:](https://github.com/Automattic/wp-calypso/pull/51177/files#r599352424)

- There's an empty line before the first `expect`
- The `tld` check also checks for the "end of the expression" (`$`) — this check is not present in the previous test

File: packages/domain-picker/test/suggestion-item.tsx (hunk 6 above)
Comment (StefanNieuwenhuis) [reply packages/domain-picker/test/suggestion-item.tsx]: What we want to achieve is to clear the mocks between assertions and for that it doesn't matter if it happens before or after. It just made more sense to me to clean up the mocks after :)

File: packages/domain-picker/test/suggestion-item.tsx (hunk 10 above)
Comment (StefanNieuwenhuis) [reply packages/domain-picker/test/suggestion-item.tsx]: We currently have three options: `button`, `row` & `radio` and I think that we should cover all scenarios (either with unit or integration tests). I think that we can include it in the A/C of #51175. WDYT?

File: packages/domain-picker/test/suggestion-item.tsx (hunk 6 above)
Comment (ciampo) [reply packages/domain-picker/test/suggestion-item.tsx]: I thought so, but I thought I'd ask anyway. Thank you!

File: packages/domain-picker/test/suggestion-item.tsx (hunk 10 above)
Comment (ciampo) [reply packages/domain-picker/test/suggestion-item.tsx]: Sounds good to me, let's include them in #51175

File: packages/domain-picker/test/suggestion-item.tsx (hunk 15 above)
Comment (StefanNieuwenhuis) [reply packages/domain-picker/test/suggestion-item.tsx]: Good one. I've added the "end of the expression" (`$`) since "Re**com**mended" matches too. I agree that it's better to be more specific and concise so I've added the empty line and the `$`.

File: packages/domain-picker/test/suggestion-item.tsx (hunk 12 above)
Comment (StefanNieuwenhuis) [reply packages/domain-picker/test/suggestion-item.tsx]: Nope. I removed it :)

File: packages/domain-picker/test/suggestion-item.tsx (hunk 10 above)
Comment (StefanNieuwenhuis) [reply packages/domain-picker/test/suggestion-item.tsx]: I've updated the A/C.

**Review by ciampo — APPROVED** [review]
LGTM!

[As agreed](https://github.com/Automattic/wp-calypso/pull/51235#discussion_r599570327), let's wait for #51177 to be merged first, and then rebase on top of `trunk` before merging this PR.

Rebasing will also update this PR to  use `node v14.x` — so, after rebasing, could you make sure that everything builds fine and tests are still passing? Thank you!

File: packages/domain-picker/test/suggestion-item.tsx [hunk 16]
```diff
@@ -15,293 +16,82 @@ import { render, fireEvent, screen } from '@testing-library/react';
...
-	supports_privacy: true,
-	vendor: 'vendor',
-	cost: '€15.00',
-	product_id: 1234,
-	product_slug: '1234',
+const MOCK_PROPS = {
+	railcarId: 'id',
+	domain: 'example.com',
+	onSelect: jest.fn(),
+	onRender: jest.fn(),
```
Comment (ciampo) [inline packages/domain-picker/test/suggestion-item.tsx]: Once rebased, please [refactor mock data as agreed](https://github.com/Automattic/wp-calypso/pull/51235#discussion_r599568380)
