### PR TITLE
Fix track event flow name in signup page in sensei flow, update step name of launch

### LINKED ISSUE #84153: Preserve flow property in account step of Sensei onboarding flow
### Quick summary

When clicking the _Continue_ button on the [setup step](http://calypso.localhost:3000/setup/sensei/senseiSetup) as a  logged out user, the following Tracks events are logged:
- `calypso_signup_start`
- `calypso_signup_step_start`

They both have a `flow` property with a value of `account`. The value should actually be set to `sensei`, not `account`.

Also, it would appear that [the launch step is using an incorrect `stepName`](https://github.com/Automattic/wp-calypso/blob/a7c2207d0929c98991013206153a6277e747a6a1/client/landing/stepper/declarative-flow/internals/steps-repository/sensei-launch/index.tsx#L90). I would expect it to be `senseiLaunch` to match the other Sensei steps, but I'm not sure how `stepName` is used. We should investigate and update it if necessary.

### Steps to reproduce

1. Add a debugging step at https://github.com/Automattic/wp-calypso/blob/a7c2207d0929c98991013206153a6277e747a6a1/client/lib/analytics/tracks.js#L11
2. Start at http://calypso.localhost:3000/setup/sensei/senseiSetup.
3. Enter a _Site name_ and click _Continue_.
4. Output the `eventName` and `eventProperties` to the console when the debugger is triggered.
5. Notice that `flow` is set to `account` instead of `sensei`:

Screenshot 2023-11-13 at 3 37 15 PM

### What you expected to happen

The events to be logged with `flow` set to `sensei`.

### What actually happened

The events were logged with `flow` set to `account`.

### Impact

Some (< 50%)

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by Imran92**
Related to https://github.com/Automattic/wp-calypso/issues/84153

## Proposed Changes

* When user is not logged in and clicks continue in senseiSetup page (`http://calypso.localhost:3000/setup/sensei/sensei-setup`), user is taken to the signup/login page. Even though they were sent there from sensei, the events get logged with flow value 'account', we've fixed that here
* Updated sensei-launch step's stepName because it was saying senseiSetup, it shouldn't have any other implication than in the event log https://github.com/Automattic/wp-calypso/pull/84191/commits/d6c14db2cc1edfead65d5ad9117b91425ca3b87f

## Testing Instructions

1. Add a debugging step at https://github.com/Automattic/wp-calypso/blob/a7c2207d0929c98991013206153a6277e747a6a1/client/lib/analytics/tracks.js#L11
2. Start at http://calypso.localhost:3000/setup/sensei/senseiSetup.
3. Enter a _Site name_ and click _Continue_.
4. Output the `eventName` and `eventProperties` to the console when the debugger is triggered.
5. Make sure that `flow` is set to `senesi`, not `account` as it says in the issue.
6. ------ For steps related changes ------
7. Complete the whole flow, meaning all the steps of onboarding. Make sure everything is working as expected

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: client/signup/main.jsx [hunk 1]
```diff
@@ -345,6 +346,7 @@ class Signup extends Component {
 			intent: get( signupDependencies, 'intent' ),
 			starting_point: get( signupDependencies, 'startingPoint' ),
 			is_in_hosting_flow: hostingFlow,
+			...( mainFlowName ? { flow: mainFlowName } : {} ),
```
Comment (renatho) [inline client/signup/main.jsx]: Maybe I'm missing something, but could we use the `queryObject?.flow` here instead of passing a new prop to the component?

**Review by renatho — CHANGES_REQUESTED** [review]
Hey @Imran92!

I was checking about the kebab case change and I faced this file: `packages/onboarding/src/flow-progress/use-flow-progress.ts`. I think we have the majority of flows using the steps with camel case. One example: `/setup/link-in-bio/linkInBioSetup`. We also have some with kebab, but it seems it's the minority. So given that we already have a mix, I'd vote do not change and avoid issues with other systems pointing to a specific URL. WDYT?

File: client/landing/stepper/declarative-flow/sensei.ts [hunk 2]
```diff
@@ -18,9 +18,9 @@ import { AssertConditionState, Flow } from './internals/types';
 import './internals/sensei.scss';
 
 function getStartUrl( step: string, locale: string ) {
-	return locale && locale !== 'en'
-		? `/start/account/user/${ locale }?redirect_to=/setup/${ SENSEI_FLOW }/${ step }`
-		: `/start/account/user?redirect_to=/setup/${ SENSEI_FLOW }/${ step }`;
+	const localeUrlPart = locale && locale !== 'en' ? `/${ locale }` : '';
+
+	return `/start/account/user/${ localeUrlPart }?redirect_to=/setup/${ SENSEI_FLOW }/${ step }&flow=${ SENSEI_FLOW }`;
```
Comment (donnapep) [inline client/landing/stepper/declarative-flow/sensei.ts]: It looks like we'll have a double slash in this URL when there's a non-English locale.

**Comment by Imran92** [comment]
> I was checking about the kebab case change and I faced this file: `packages/onboarding/src/flow-progress/use-flow-progress.ts`. I think we have the majority of flows using the steps with camel case. One example: `/setup/link-in-bio/linkInBioSetup`. We also have some with kebab, but it seems it's the minority. So given that we already have a mix, I'd vote do not change and avoid issues with other systems pointing to a specific URL. WDYT?

Hey @renatho 👋 Thanks for checking it.

Acutally I checked many places with steps, and looks like there's almost an equal level of usage of both camel case and kebab case. I did some searching with some regex, for example, `stepName.*-, stepName(?!.*-).*$,stepName[^A-Z]*$,stepName.*[A-Z].*$` to get a clear idea, also the usage of `StepComponent` component.

Also, when logging the stepName, I see that it's converted to kebab case if it isn't https://github.com/Automattic/wp-calypso/blob/c363fd6c1b5ba5d560328661796552addf11e026/client/landing/stepper/declarative-flow/internals/index.tsx#L172

I was already concerned with the URL changes as I've mentioned in the PR body. Now after discussing with you, I think it's better to leave it as it is. I've reverted it here https://github.com/Automattic/wp-calypso/pull/84191/commits/7ae73dc004e65a12a5b8db654e92de0817c437b2

File: client/signup/main.jsx (hunk 1 above)
Comment (Imran92) [reply client/signup/main.jsx]: Thanks, I've updated it here https://github.com/Automattic/wp-calypso/pull/84191/commits/0b9c51ca07ca23e1f360ca1a4c3485822fb291b8

File: client/landing/stepper/declarative-flow/sensei.ts (hunk 2 above)
Comment (Imran92) [reply client/landing/stepper/declarative-flow/sensei.ts]: Thanks! I've updated it here https://github.com/Automattic/wp-calypso/pull/84191/commits/a536ddf58667200016a0b9f9ef765fd001449cf0.

**Review by renatho — APPROVED** [review]
Thank you, @Imran92! Looks good and works well!
