### PR TITLE
After switching theme, fetch latest site front page options

### LINKED ISSUE #79511: After changing theme, sometimes the Pages list shows the wrong homepage settings and/or spinning loaders
### Quick summary

Some themes (currently, the ones with the `auto-loading-homepage` tag) will update the "Your homepage displays" setting to a new page upon activation. However, this new value is sometimes not reflected in the Pages page.

@Automattic/lego 

### Steps to reproduce

1. Create a new site.
1. Skip the Design Picker theme selection, which will set the theme of your site to TT3.
1. Then, activate Meraki theme (or any theme in https://wordpress.com/themes/filter/auto-loading-homepage).
1. Go to Pages in the left sidebar.

### What you expected to happen

It should look like this:

image

### What actually happened

It looks like this instead:

image

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

Refreshing the page again multiple times and/or go to other pages, will sometimes fix the issue.

### PR DESCRIPTION
**Pull request by fushar**
Related to:

- #79511

## Proposed Changes

Switching to certain themes might update the front page options (aka "Your homepage displays" settings). This PR adds `<QuerySiteSettings/>` to the component that shows Pages page.

Unfortunately, somehow `receiveSiteSettings()` does not update incoming site options to the Redux store; so this PR also explicitly updates the front page options to the Redux store.

## Testing Instructions

1. Create a new site.
1. Skip the Design Picker theme selection, which will set the theme of your site to TT3.
1. Then, activate Meraki theme (or any theme in https://wordpress.com/themes/filter/auto-loading-homepage).
1. (Don't refresh the page) Go to Pages in the left sidebar.
1. Verify that you see this:

image

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: client/state/site-settings/actions.js [hunk 1]
```diff
@@ -68,6 +68,7 @@ export function requestSiteSettings( siteId ) {
 				};
 
 				dispatch( receiveSiteSettings( siteId, savedSettings ) );
+				dispatch( receiveSiteOptions( siteId, savedSettings ) );
```
Comment (arthur791004) [inline client/state/site-settings/actions.js:71]: Not a blocker, but how about dispatching `receiveSiteFrontPage` here directly? Is there any consideration here 🤔

File: client/my-sites/pages/page-list.jsx [hunk 2]
```diff
@@ -461,6 +462,7 @@ export default class PageList extends Component {
 		return (
 			<div>
 				<QueryPosts siteId={ siteId } query={ { ...query, page } } />
+				<QuerySiteSettings siteId={ siteId } />
```
Comment (okmttdhr) [inline client/my-sites/pages/page-list.jsx]: badge

I'm wondering if we can update the redux store of site settings when a user finish theme-switching (rather than when they come to the Pages page). My concern is about whether we will need to make similar changes elsewhere.

**Review by okmttdhr — APPROVED** [review]
I left a non-blocking comment, but LGTM! Thank you for working on this!

**Review by arthur791004 — APPROVED** [review]
Tested and it works as expected 🎉

File: client/my-sites/pages/page-list.jsx (hunk 2 above)
Comment (arthur791004) [reply client/my-sites/pages/page-list.jsx]: Sounds good! It might be better to request site settings after the theme switch 👍

Another way is to let `theme-setup` endpoint return the related site options so we can simply update the local data.

File: client/state/site-settings/actions.js (hunk 1 above)
Comment (fushar) [reply client/state/site-settings/actions.js:71]: 1. So that the "concerns" are "symmetric" here -- settings and options.
2. Maybe in the future people will include other options; this way they can just add it inside `receiveSiteOptions()`

😄 What do you think?

File: client/my-sites/pages/page-list.jsx (hunk 2 above)
Comment (fushar) [reply client/my-sites/pages/page-list.jsx]: Previously I thought about that but then what's the purpose of `QuerySiteSettings`? Why did we create that?

I think the "client" of any site settings / options should be responsible to fetch the latest value of the settings/options that they need. Here, the Pages page needs the latest value of the front page options, so it needs to fetch them using `QuerySiteSettings`.

What do you think?

Comment (okmttdhr) [reply client/my-sites/pages/page-list.jsx]: I don't think the way it's implemented will matter that much, so I'm starting to feel that it would be fine to address this at another time. 🙇  But I comment in an idealistic sense. ⭐ 

I think a component like `QuerySiteSettings` is for data encapsulation so that each component can manage its own data in a reliable way.

Perhaps we could consider a hybrid approach: Whenever a setting is updated (like the theme-switching), we could update the Redux store, and also trigger a local data refresh on each component (fetching in the background might be better). In this way, overall efficiency is improved, but components are still responsible for their own data. I think this kind of pattern is often seen in a project using GraphQL.

Comment (fushar) [reply client/my-sites/pages/page-list.jsx]: Thanks @arthur791004  & @okmttdhr for your reviews!

After reading your comments and contemplating, I've found a more appropriate place to put this logic. Could you check again? 🙏

Comment (okmttdhr) [reply client/my-sites/pages/page-list.jsx]: Looks good to me! Thank you for your time 🚀

File: client/state/site-settings/actions.js (hunk 1 above)
Comment (arthur791004) [reply client/state/site-settings/actions.js:71]: 👍

**Review by arthur791004 — APPROVED** [review]
Yep, requesting site settings after the activation looks better 👍
