### PR TITLE
Playwright: instruct CommentsComponent.publishComment to wait until everything has loaded.

### LINKED ISSUE #54701: Playwright: CommentsComponent.postComment is flaky
### Details

Logs:
```
page.click: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "input:has-text("Post Comment")"
  selector resolved to hidden <input name="submit" type="submit" id="comment-submit" …/>
attempting click action
  waiting for element to be visible, enabled and stable
element is not visible - waiting...
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
Error:
at Object.captureStackTrace (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/utils/stackTrace.js:50:19)
at Connection.sendMessageToServer (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/connection.js:65:48)
at Proxy.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/channelOwner.js:64:61)
at /home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/frame.js:284:34
at Frame._wrapApiCall (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/channelOwner.js:77:34)
at Frame.click (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/frame.js:283:21)
at /home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/page.js:457:60
at Page._attributeToPage (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/page.js:238:20)
at Page.click (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/page.js:457:21)
at CommentsComponent.postComment (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/comments-component.ts:33:19)
at Object.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-likes__comment-spec.js:92:4)
```

### Checklist

_No response_

### Related

_No response_

### PR DESCRIPTION
**Pull request by worldomonation**
#### Changes proposed in this Pull Request

This PR proposes to add a `this.page.waitForLoadState('networkidle')` call to the `CommentsComponent.postComment` method.

Background Details:
In #54006 a call was added to first click on the comment text area prior to entering the comment text.
This was for two reasons:
- better simulate user behavior.
- expose the Post Comment button.

However, this was not enough as intermittent failures of this method continued to crop up.

After observing the video recording it was noted that `postComment` method would execute immediately once the text area appeared, and this took place before rest of the page was loaded (including some scripts). Based on the timing of the `postComment`, intermittently the text area would be clicked on too fast, resulting in the `Post Comment` button never appearing.

This behavior was reproduced locally by throttling the network to 2G speeds then loading a published post page. Once the text area appeared, it was clicked and text entered. It took only 1 attempt to reproduce this behavior.

#### Testing instructions

TeamCity
- there should be no failure of anything related to comments.

Related
#54701

### CODE REVIEW

**Comment by kwight** [comment]
> there should be no failure of anything related to comments.

No failures at all. 😃

**Review by kwight — APPROVED** [review]

File: packages/calypso-e2e/src/lib/components/comments-component.ts [hunk 1]
```diff
@@ -28,6 +28,7 @@ export class CommentsComponent extends BaseContainer {
 	async postComment( comment: string ): Promise< void > {
 		// To simulate user action first click on the field. This also exposes the
 		// submit comment button.
+		await this.page.waitForLoadState( 'load' );
```
Comment (dpasque) [inline packages/calypso-e2e/src/lib/components/comments-component.ts]: This change looks good, but I wanted to ask a quick design question (mostly for my own clarification!)

In general, do we want to defer `load` waiting downstream to the loaded POM classes, or keep it upstream next to the navigation?

So in this case, the alternative would be updating `PublishedPostsListPage.visitPost` to add the `this.page.waitForLoadState()` and the navigation/click promises resolve.

I think both options are great, I figured I should clarify which approach we wanted to do because I don't think we have that documented anywhere, and then we can replicate that throughout!

**Review by dpasque — COMMENTED** [review]
Change looks good, just wanted to double check one design thing for future changes!

File: packages/calypso-e2e/src/lib/components/comments-component.ts (hunk 1 above)
Comment (worldomonation) [reply packages/calypso-e2e/src/lib/components/comments-component.ts]: Ah yes, good question - the answer is that there isn't a specific standard for this within our repo.

Part of the reason for the `BaseContainer` and the presence of a default selector to wait on was to achieve more reliable timing. Through a series of reviews and discussions, Bart and I agreed that it was not the best practice as:
1. POM is now reliant on a CSS class not changing;
2. POM could be waiting unnecessarily if the default wait is too safe.

If I recall correctly we agreed in principle that it would be a better approach to have each class method do a cursory check on the state of the page/component before performing actions, but this isn't always followed. Many of these objects (including more recent ones I've written) have methods that jump straight into its actions without first performing any checks.

I think it's a style question. With Playwright's auto-wait, our POMs should be able to fire off action after another and the auto-wait takes care of that for us. In reality though, because of the way calypso has grown over the years, not everything is as consistent as it should be.

My take? I think having additional waits and checks before actions would be beneficial, personally. The default choices in Playwright are good but does not cover all cases and the automatic waits aren't always bulletproof with our product.

**Review by dpasque — APPROVED** [review]
