### PR TITLE
Playwright: click on the View Post button on post-publish panel instead of snackbar.

### LINKED ISSUE #54618: Playwright: publish and visit post is flaky
### Details

The `GutenbergEditorPage.publish` method, when `visit = true` the click action locates the toast and tries to click on the link. This is unreliable.

TeamCity run: 6424429

Logs:
```
page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "iframe.post-likes-widget" to be visible
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
Error:
at Object.captureStackTrace (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/utils/stackTrace.js:50:19)
at Connection.sendMessageToServer (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/connection.js:65:48)
at Proxy.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/channelOwner.js:64:61)
at /home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/frame.js:207:42
at Frame._wrapApiCall (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/channelOwner.js:77:34)
at Frame.waitForSelector (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/frame.js:202:21)
at /home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/page.js:248:60
at Page._attributeToPage (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/page.js:238:20)
at Page.waitForSelector (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/page.js:248:21)
at PublishedPostPage._click (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/published/published-post-page.ts:34:42)
at PublishedPostPage.likePost (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/published/published-post-page.ts:54:14)
at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-likes__post-spec.js:55:28)

```

### Checklist

- [ ] ensure GutenbergEditorPage.publish locates the post-publish panel's `View Post` button.

### Related

_No response_

### PR DESCRIPTION
**Pull request by worldomonation**
#### Changes proposed in this Pull Request

This PR proposes to change the element that is clicked on as part of the `GutenbergEditorPage.publish` process.

Changes:
- use the post-publish panel's `View Post` button instead of the `View Post` link in the snackbar.
- return the published article's URL by default to the caller, to be used in assertions.
- add an assertion to the `test/e2e/specs/specs-playwright/wp-likes__post-spec.js` spec to assert on the returned article URL.

Background Details:

Currently, the `publish` process of an article results in the page object locating and clicking on the floating snackbar that appears post-publish for approximately 5 seconds. This has led to a couple of issues when running E2E tests:
1. the snackbar is still animating when Playwright clicks.
2. the snackbar is gone by the time the click event occurs.

Both scenarios result in non-navigation and therefore failed tests.

Instead, the `View Post` link on the post-publish panel is to be used to navigate to the published article.
While this has its own issues (eg. post-publish panel being auto-dismissed due to a bug) this is more in line with expected user behavior.

#### Testing instructions

TeamCity
- ensure tests do not fail due to publish process.

Related to #

### CODE REVIEW

File: packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts [hunk 1]
```diff
@@ -149,13 +148,18 @@ export class GutenbergEditorPage extends BaseContainer {
 	 * @param {boolean} visit Whether to then visit the page.
 	 * @returns {Promise<void} No return value.
 	 */
-	async publish( { visit = false }: { visit?: boolean } ): Promise< void > {
+	async publish( { visit = false }: { visit?: boolean } = {} ): Promise< string > {
 		await this.frame.click( `${ selectors.editPostHeader } >> text=Publish` );
 		await this.frame.click( `${ selectors.publishPanel } >> text=Publish` );
+		const viewPublishedArticleButton = await this.frame.waitForSelector(
+			`${ selectors.publishPanel } a:has-text("View")`
```
Comment (bsessions85) [inline packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts]: Can we make this a variable so we're not having to use the same thing in line 173?

Comment (worldomonation) [reply packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts]: Gotcha, will push up a revised commit.

**Review by bsessions85 — APPROVED** [review]
🚀
