### PR TITLE
Layout: More closely tie is-iframe classname to the state

### LINKED ISSUE #35305: Scrolling is broken occasionally
#34829 ## Steps to reproduce
N/A happens periodically when I was blogging and looking a list of my blog posts, but a screen refresh causes it to go away.

#### What I expected
I expected to be able to scroll, but I can't.

#### Steps to reproduce

Approach 1:

1. Open the block editor: https://wordpress.com/block-editor/post/
2. Select a site to create a new post.
3. Click the back arrow in the top left to exit the editor.
4. Try to scroll the posts list, or navigate to another Calypso screen and try to scroll. Notice that it doesn't scroll.
5. Refresh the page. Notice that it scrolls now.
6. Click the Write button in the master to open the block editor again.
7. Click the back arrow in the top left to exit the editor.
8. Try to scroll the posts list. Notice that it scrolls now.

Approach 2:

1. Select one of my posts in the Reader
2. Edit the post from the Reader view
3. Update the post
4. I am unable to scroll on any page in Calypso until I refresh.

In both cases, the `is-iframe` class is added to the `html` tag and isn't removed after closing the block editor. This CSS disables scrolling when that class is present:

https://github.com/Automattic/wp-calypso/blob/39efb82641b89aec78018435e5c13fafda1b1610/client/gutenberg/editor/style.scss#L81-L83

#### Browser / OS version
Latest chrome running on a mac.

### PR DESCRIPTION
**Pull request by jblz**
#### Changes proposed in this Pull Request

* New selector `isIframeForHtmlElement`
* New memoized functional component `HtmlIsIframeClassname` which `useSelect`s the new selector & has a side effect of toggling the presence of the `is-iframe` class on the `html` node.
* Mount the component in the `Layout` render

##### Repro case 1 from the issue:

* Open the block editor: https://wordpress.com/block-editor/post/
  * You should be able to scroll the site picker (It's helpful to use a test user with a lot of sites so you can scroll)
* Select a site to create a new post (It's helpful to choose a site which has a lot of posts that you've authored)
* Click the back arrow in the top left to exit the editor.
  * You should be able to scroll the posts list
* Navigate to other Calypso screens
  * You should be able to scroll

##### Repro case 2 from the issue:

* Select one of your posts in the Reader
* Edit the post from the Reader view
* Update the post
* You should be able to scroll as expected.

##### Confirm the new component updates appropriately:

~~Enter the following in your dev console: `localStorage.setItem('debug', 'calypso:layout:html-is-iframe-classname' )` Repeat the above tests cases & monitor the debug output.~~ (Debug statements removed before merging -- revert 6b0fed7 if you'd like to add them back)

Fixes #35305

### CODE REVIEW

File: client/layout/html-is-iframe-classname.tsx [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+import debugFactory from 'debug';
+
+/**
+ * Internal dependencies
+ */
+import isIframeForHtmlElement from 'state/selectors/is-iframe-for-html-element';
+
+const debug = debugFactory( 'calypso:layout:html-is-iframe-classname' );
+
+const HtmlIsIframeClassname = memo( () => {
```
Comment (jsnajdr) [inline client/layout/html-is-iframe-classname.tsx]: Instead of `memo`, I'd add a dependency parameter to `useEffect`:
```js
const HtmlIsIframeClassname = () => {
  const isIframe = useSelector( isIframeForHtmlElement );
  useEffect( () => {
    // add and remove classes
  }, [ isIframe ] );

  return null;
}
```
That's a more common way to run an effect only when something (i.e., `isIframe` value) changes and do nothing otherwise. `memo` should also work 100%, but it's not exactly the ideal intended usage of it.

File: client/layout/html-is-iframe-classname.tsx [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+		} else {
+			debug( 'removing is-iframe' );
+			htmlNode.classList.remove( 'is-iframe' );
+		}
+	} );
+
+	return null;
+} );
+
+export default typeof document === 'object' ? HtmlIsIframeClassname : () => null;
```
Comment (jsnajdr) [inline client/layout/html-is-iframe-classname.tsx]: You can just export `HtmlIsIframeClassname` without guarding for `document`. As the `document` is touched only in `useEffect`, the component is SSR-safe anyway. The Node.js server will never run the `useEffect` handler.

**Review by jsnajdr — APPROVED** [review]
Looks good. I made two review comments, but they are not blockers -- rather from the "this code could be more beautiful" department.

Did you also intend to make any `client/document/index.js` changes? I don't immediately see a need for that: server will add `html.is-iframe` if the initial requested section is `gutenberg-editor`, and then the client-side React code will take care of correctly adding/removing the class name on any navigation.

**Review by noahtallen — APPROVED** [review]
Beautiful! I compared this with the behavior on `master` and it's amazing how huge an improvement this makes to the UX despite being a small change.

File: client/state/selectors/is-iframe-for-html-element.js [hunk 3]
```diff
@@ -0,0 +1,9 @@
+/**
+ * Internal dependencies
+ */
+import getSelectedSiteId from 'state/ui/selectors/get-selected-site-id';
+import getSectionName from 'state/ui/selectors/get-section-name';
+
+const isIframeForHtmlElement = state =>
+	!! ( getSelectedSiteId( state ) && getSectionName( state ) === 'gutenberg-editor' );
```
Comment (vindl) [inline client/state/selectors/is-iframe-for-html-element.js]: Would it make sense to include `customizer` here in addition to `gutenberg-editor` for consistency?

**Review by vindl — APPROVED** [review]
Works well for me! :shipit: Thanks for fixing this @jblz!

File: client/layout/html-is-iframe-classname.tsx [hunk 4]
```diff
@@ -0,0 +1,38 @@
...
+		}
+
+		if ( isIframe ) {
+			debug( 'adding is-iframe' );
+			htmlNode.classList.add( 'is-iframe' );
+		} else {
+			debug( 'removing is-iframe' );
+			htmlNode.classList.remove( 'is-iframe' );
+		}
+	} );
```
Comment (jsnajdr) [inline client/layout/html-is-iframe-classname.tsx]: There's one more important thing that should go into the `useEffect` here: return an "unmount" callback that removes the `is-iframe` classname when the `HtmlIsIframeClassname` is unmounted:
```js
return () => htmlNode.classList.remove( 'is-iframe' )
```
If you don't do this, bugs like the one fixed in #36424 will happen.

File: client/state/selectors/is-iframe-for-html-element.js (hunk 3 above)
Comment (jblz) [reply client/state/selectors/is-iframe-for-html-element.js]: @vindl happy to...  Where is that set presently?

Comment (jblz) [reply client/state/selectors/is-iframe-for-html-element.js]: I'm seeing these:
* https://github.com/Automattic/wp-calypso/blob/dc7ee470968f9137e19fb3a57f7a8c86d7fe4b05/client/gutenberg/editor/calypsoify-iframe.tsx#L595
* https://github.com/Automattic/wp-calypso/blob/b49fc5f9c943b3b30987ed135a964d40146be587/client/my-sites/customize/main.jsx#L336

...but they're setting the `is-iframe` class on the "main" `<div>` -- not the `<html>` node, so, unless I'm missing something, it's semantically different enough, I'd like to not conflate them.

**Comment by jblz** [comment]
Thanks for the beautification & bug blocking, @jsnajdr -- fixed up!

File: client/state/selectors/is-iframe-for-html-element.js (hunk 3 above)
Comment (vindl) [reply client/state/selectors/is-iframe-for-html-element.js]: It works in the same way so I was expecting to see it in the document layout, however it's only present here in the Customizer case: 🤔 

https://github.com/Automattic/wp-calypso/blob/b49fc5f9c943b3b30987ed135a964d40146be587/client/my-sites/customize/main.jsx#L336

In any case, it's not something I'd block this fix on.

**Comment by rickybanister** [comment]
Thanks @jblz !!!
