### PR TITLE
Gutenboarding: redirect to editor after emptying checkout cart 

### LINKED ISSUE #41652: Gutenboarding: redirect to editor after emptying checkout cart
## Description

At the moment, when a user clears their cart, [we redirect them back to plans](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/checkout/checkout/index.jsx#L314)

checkout-redirect

For Gutenboarding `prelaunch` and `new-launch` (previously known as _Frankenflow_) flows, when a user empties their cart we could return them to the editor.

It looks like [we're passing down information to Checkout when arriving from a Gutenboarding flow](https://github.com/Automattic/wp-calypso/blob/2e2bdda/client/my-sites/checkout/checkout-system-decider.js#L93).

We could pass those props down and update `redirectIfEmptyCart()` to behave accordingly?

First identified in https://github.com/Automattic/wp-calypso/pull/41205

## Steps to reproduce

1. From `/new` select a paid domain
2. Create a site and head to checkout
3. Empty your cart
4. You're taken to Calypso plans

Also

1. From `/new` create a free site and head over to the editor
2. Click on Update to launch your site
3. Select a paid plan
4. Empty your cart
5. You're taken to Calypso plans

### PR DESCRIPTION
**Pull request by ramonjd**
## Changes proposed in this Pull Request

Here we pass down `returnToBlockEditor` to `<Checkout />` so we can redirect back to the block editor if the cart is empty for in Gutenboarding flows.

redirect-from-cart-new-flow

I'm open to alternatives for `returnToBlockEditor`.

## Testing instructions

1. From /new select a paid domain, create a site and head to checkout
2. Now empty your cart
3. You should be taken to the editor, where your new home page will be laid out bare before you, ready to succumb to your editing desires
4. Now that you're in the editor, click on **Launch** to launch your site Screen Shot 2020-04-30 at 8 05 12 pm
5. Select a paid plan and let yourself be carried away to checkout
6. Empty your cart again.
7. Once again, you'll land on the editor, face to face with your sultry homepage, who pines for new content.

Fixes #41652

### CODE REVIEW

File: client/my-sites/checkout/checkout/index.jsx [hunk 1]
```diff
@@ -343,6 +344,11 @@ export class Checkout extends React.Component {
 
 		let redirectTo = '/plans/';
 
+		if ( returnToBlockEditor ) {
+			page.redirect( `/block-editor/page/${ selectedSiteSlug }/home` );
+			return true;
+		}
```
Comment (p-jackson) [inline client/my-sites/checkout/checkout/index.jsx:350]: I'm wondering whether this branch should go _after_ the `if ( this.state.previousCare )` branch. I don't know what a "previous cart" is, but maybe there's a way of having nested carts? In which case it'd make sense for the user to back their way out of all the carts before finally emptying their last cart and being returned to the block editor.

But I don't know how it all works @niranjan-uma-shankar do you know what the `previousCart` state is for in this component?

Comment (ramonjd) [reply client/my-sites/checkout/checkout/index.jsx:350]: Oh, that's a good question. 

As far as I can see, [getExitCheckoutUrl](https://github.com/Automattic/wp-calypso/blob/master/client/lib/checkout/index.js#L71) checks what you had in your cart and redirects you to a related page, e.g., if `hasDomainMapping( cart )` then go to  `'/domains/add/mapping/'`.

So in this case we're _kinda_ doing the same thing, only outside of the method. I think.

Comment (niranjan-uma-shankar) [reply client/my-sites/checkout/checkout/index.jsx:350]: I haven't used previousCart before but from what I gather, it looks like the cart state from just before the cart was emptied. So at the point the cart is emptied, `this.props.cart`'s `product` prop is empty and `previousCart`'s product prop is used to determine the redirect destination(like in the example Ramon gave above). 

I think there's no harm in keeping the block-editor redirect where it is, but from keeping in line with the style maintained in that function, we could set the `redirectTo` value instead of using page.redirect in the if(returnToBlockEditor) block. We could also remove this `if` block and use `getExitCheckoutUrl`. 

Should this redirect work on the new checkout flow too? Or is that excluded for Gutenboarding? (maybe we have to change [here](https://github.com/Automattic/wp-calypso/blob/8c6ff289fc0b2750b4a22c1e0f266746e3b99fea/client/my-sites/checkout/composite-checkout/composite-checkout.js#L418) for the new checkout flow but I'm not entirely sure.)

Comment (ramonjd) [reply client/my-sites/checkout/checkout/index.jsx:350]: > I think there's no harm in keeping the block-editor redirect where it is, but from keeping in line with the style maintained in that function, we could set the redirectTo value instead of using page.redirect in the
if ( returnToBlockEditor ) { ... } block. We could also remove this if block and move things to getExitCheckoutUrl(in which case I think we don't need to check if previousCart exists). These are minor issues, so up to you if you'd like to do it.

Thanks! I'll make those changes. Good tips.

> Should this redirect work on the new checkout flow too? Or is that excluded for Gutenboarding? 

Another good question! 

I don't see anywhere in `shouldShowCompositeCheckout` that would [preclude Gutenboarding](shouldShowCompositeCheckout).

Is the new checkout live and working? I can't get it to load when I activate the A/B test, make my site USD and all the other conditions.

Maybe that can be another task.
