### PR TITLE
Checklist: Disable ChecklistBanner for Jetpack and Atomic sites

### LINKED ISSUE #26870: Checklist: View your checklist link broken for Jetpack site
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/eric.blog
2. Click "View your checklist" in checklist banner
3. Land on https://wordpress.com/checklist/eric.blog and observe "Checklist not available for this site"

#### What I expected

For the "View your checklist" link to work

OR

To not see the banner since my site is old and has a name and description.

#### What happened instead

The opposite of that.

#### Browser / OS version

Chrome Version 68.0.3440.106 (Official Build) (64-bit) on Mac

#### Screenshot / Video

screen shot 2018-08-24 at 8 33 38 am

screen shot 2018-08-24 at 8 33 40 am

### PR DESCRIPTION
**Pull request by sirreal**
The Checklist banner on the stats page should not be shown (with an inaccurate list of tasks) for Jetpack or Atomic sites.

Hide the banner for those sites.

Fixes #26870

This was likely introduced by #26721 where [an equality check to hide the banner always fails](https://github.com/Automattic/wp-calypso/pull/26721/files#diff-435657f5f9b9c272e276134ceda0644dL104) for Jetpack sites (props @ockham)

## Testing
1. Visit stats for a site that should have the banner (simple) and verify the banner is present.
1. Visit stats for a site that should not show the banner (Atomic, Jetpack) and verify that the banner is not present.

### CODE REVIEW

File: client/my-sites/stats/site.jsx [hunk 1]
```diff
@@ -264,6 +267,7 @@ export default connect(
 				siteId
 			),
 			siteId,
+			showChecklistBanner: ! isAtomicSite( state, siteId ) && ! isJetpack,
```
Comment (ockham) [inline client/my-sites/stats/site.jsx]: `isAtomicSite` is a true subset of `isJetpack`, isn't it? Meaning we could only use `isJetpack` as the criterion?

Comment (sirreal) [reply client/my-sites/stats/site.jsx]: For now, that's true and this is redundant. However, the cost is _extremely low_, and I like forcing future devs to consider Atomic.
