### PR TITLE
New Onboarding: Fix language path related issues

### LINKED ISSUE #48197: Onboarding: switching language leaves the incorrect language slug in the url
#### Steps to reproduce

1. Starting at URL: `/new/es?flags=gutenboarding/language-picker`
2. Use language picker to switch to something non-Spanish

#### What I expected
The `/es` slug in the url should either disappear or switch to the language I just selected. Ideally if the user refreshes the page they should keep their language selection, so the easiest way to do that might be to change the slug in the url to match their selection. 

#### What happened instead
The `/es` slug in the url is still their so the url no longer matches the reality of the page I'm on. If I refresh it switches the language on me :(

#### Screenshot / Video
Dec-10-2020 16-14-43

### LINKED ISSUE #48198: Onboarding: opening the language picker sometimes jumps the user back to the start of onboarding
#### Steps to reproduce

1. Starting at URL: `/new/es?flags=gutenboarding/language-picker`
2. Skip setting a site title
3. Attempt to open the language picker

#### What I expected
Language picker modal opens

#### What happened instead
I'm jumped back to the start of onboarding and the `/es` fragment has disappeared from the url (although the UI language is still Spanish)

#### Screenshot / Video
Dec-10-2020 16-20-46

### PR DESCRIPTION
**Pull request by razvanpapadopol**
#### Changes proposed in this Pull Request
* Fix Language picker redirecting to the Gutenboarding base path.
* Fix language param not being updated in path after making a selection in Language modal.
* Import `languages` from `@automattic/languages` remove Calypso `/lib` dependency.
* Enable `gutenboarding/language-picker` feature flag in development and horizon for testing.

#### Testing instructions
1. Starting at URL: [/new/es?flags=gutenboarding/language-picker](https://hash-60980ae88e9789254b6bde72a4d182e431ac497c.calypso.live/new/es?flags=gutenboarding/language-picker)
2. Skip setting a site title
3. Open the language picker => URL pathname should become `/new/language-modal/es`
4. Choose another language => when the language modal closes, pathname should be `new/{PREVIOUS_STEP}/{NEW_LOCALE}`

*Note that full translation of the page doesn't happen instantly, except when loading EN.

Fixes #48197
Fixes #48198

### CODE REVIEW

File: client/landing/gutenboarding/hooks/use-previous.ts [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+ * External dependencies
+ */
+import { useEffect, useRef } from '@wordpress/element';
+
+/**
+ * Custom hook to provide the previous value of state or props in a functional component
+ *
+ * see https://reactjs.org/docs/hooks-faq.html#how-to-get-the-previous-props-or-state
+ *
+ * @param  {any}  value state or prop value for which previous value is required
```
Comment (p-jackson) [inline client/landing/gutenboarding/hooks/use-previous.ts]: These `{any}` parts of jsdoc aren't needed since we're using TypeScript, and I think they should be removed because `value` _isn't_ an `any`, it's a `T`

File: client/landing/gutenboarding/hooks/use-previous.ts [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+ * @returns {any}  previous value of requested state or prop value
+ */
+export function usePrevious< T >( value: T ): T {
+	const ref = useRef< T >();
+
+	useEffect( () => {
+		ref.current = value;
+	}, [ value ] );
+
+	return ref.current as T;
```
Comment (p-jackson) [inline client/landing/gutenboarding/hooks/use-previous.ts]: 🤔 I feel like we shouldn't need this type cast. Shouldn't the `usePrevious` hook return `T | undefined`? It feels like the first time this hook is used it'll return `undefined` right? Since there is no previous value. And in that case we wouldn't need the `as T` to cast away the `undefined` type.

File: client/landing/gutenboarding/onboarding-block/language/index.tsx [hunk 3]
```diff
@@ -38,10 +44,16 @@ const LanguageStep: React.FunctionComponent = () => {
...
+	const staticPreviousStep = React.useRef( previousStep );
+
 	const history = useHistory();
+	const makePath = usePath();
 
-	const goBack = () => {
-		history.goBack();
+	const goBack = ( lang = '' ) => {
+		staticPreviousStep.current
+			? history.replace( makePath( Step[ staticPreviousStep.current ], lang ) )
```
Comment (p-jackson) [inline client/landing/gutenboarding/onboarding-block/language/index.tsx]: Should this be a `history.push` instead so that it behaves more like a regular navigation? We're treating the language modal more like a step in the flow than just a temporary modal. We change the route and everything when we navigate to it. So it feels like in that case it deserves it's own entry in the history.

Comment (p-jackson) [reply client/landing/gutenboarding/onboarding-block/language/index.tsx]: Ah now that I think about it, since we're treating this as page navigation, the language buttons would all be wrapped in `<a href="">` and _that's_ what would cause the history to be "pushed". But that's all inside the language picker so we can't really change it to use a real link.

I find the fact that the language picker isn't treated like a modal (i.e. has an "X" button instead of a "back" button, and it wouldn't update the browser url) makes it feel a bit clumsy. But that's a bigger change than we should address in this PR. Just treat this as grumbling :)

**Review by p-jackson — APPROVED** [review]
Good idea enabling it for testing in development and horizon. Best to just start getting this thing in front of more people.

I've got a few nit picks, but this is good to go really. Looks like most of the problem was just not calling `makePath()` in the appropriate places! Certainly fixes the issues I found. I'm happy to approve.
