### PR TITLE
Fix UI issues on Use my Domain screen

### LINKED ISSUE #100237: Transfer domain:  'Transfer or Connect' screen has multiple UI bugs
## Where

1. Create a new site
2. On the /domains step, select the option 'Use a domain I own'
3. Add a valid domain

## Problem

When selecting the Domain transfer option during onboarding, users will see a screen that have multiple UI bugs and things that need to be fixed.

Image

Image

Image

## Solution

- The white background should be removed from the content area.
- CTA should not truncate but stay in one line
- The sections should not swap depending the URL you add, they should always follow the same order.
- ~~Green should be updated to `Green 80` and `Green 5` for the background~~ Not needed, values are already correct.
- We could also remove the illustrations alltogether.

### PR DESCRIPTION
**Pull request by tellthemachines**
Related to #100237

## Proposed Changes

* Removes background color from `domain-transfer-or-connect__content` card component.
* Changes `badge--info-green` color and background color.
* Prevents "Purchase a plan" button text from wrapping (this should work with whatever length because the text before it is adaptable)

Screenshot 2025-03-05 at 3 32 04 pm

The one thing I'm not 100% is the order of the sections but I've requested clarification in the issue.

## Why are these changes being made?

*

## Testing Instructions

* Set up a new site and, at the "Choose your domains" step, select "use a domain I own". Make sure to input an existing domain.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by tellthemachines** [comment]
I've updated this PR with the latest from the issue. The only thing I haven't done is the optional remove the illustrations because I think they're rather cute!

File: client/components/domains/use-my-domain/utilities/get-option-info.js [hunk 1]
```diff
@@ -249,9 +249,5 @@ export function getOptionInfo( {
 
 	connectContent.primary = ! transferContent?.primary;
 
-	if ( transferContent?.primary ) {
-		return [ transferContent, connectContent ];
-	}
-
-	return [ { ...connectContent, primary: true }, transferContent ];
+	return [ transferContent, connectContent ];
```
Comment (ramonjd) [inline client/components/domains/use-my-domain/utilities/get-option-info.js:252]: Is this to prevent the sections from reordering? Transfer appears to me be worthy of first place, but I'll defer to whatever advice you've sought.

File: client/components/domains/use-my-domain/transfer-or-connect/style.scss [hunk 2]
```diff
@@ -166,6 +171,7 @@
 				.button {
 					padding: 8px 39px;
 					flex-grow: 1;
+					white-space: nowrap;
```
Comment (ramonjd) [inline client/components/domains/use-my-domain/transfer-or-connect/style.scss:174]: > Prevents "Purchase a plan" button text from wrapping (this should work with whatever length because the text before it is adaptable)

Also affects the blue Select button. 

Screenshot 2025-03-12 at 11 43 21 am

Not an issue, and good for consistency, just saying!

**Review by ramonjd — COMMENTED** [review]
LGTM so far!

### Before

Screenshot 2025-03-12 at 11 39 09 am

### After

Screenshot 2025-03-12 at 11 40 59 am

I wasn't sure whether the illustrations were going to be removed as well per https://github.com/Automattic/wp-calypso/issues/100237

File: client/components/domains/use-my-domain/utilities/get-option-info.js (hunk 1 above)
Comment (tellthemachines) [reply client/components/domains/use-my-domain/utilities/get-option-info.js:252]: [This](https://github.com/Automattic/wp-calypso/issues/100237#issuecomment-2713212536) is the advice!

**Comment by tellthemachines** [comment]
> I wasn't sure whether the illustrations were going to be removed as well per #100237

I read that as optional and decided to leave them in for now. We can always remove them later. Unless @nuriapenya would rather we did it? But with the order of the items not switching, it might not be so much of an issue.

**Comment by ramonjd** [comment]
> We can always remove them later.

SGTM!

**Review by ramonjd — APPROVED** [review]
I'll give @nuriapenya the final word, but from my perspective things are working/looking as described.

🍺

**Review by tyxla — APPROVED** [review]
This one tests well and looks good to me 👍
