### PR TITLE
Media: Clear selected media when leaving library

### LINKED ISSUE #12235: Editor: Show which image is selected as Featured Image
When a Featured Image is added to a post it is not clear which image is being used. Oftentimes, a user will upload multiple versions of an image (say a logo) and will want to switch the image they chose. It is not clear which image is selected as the featured image once you click the image in the editor.

#### Steps to reproduce
1. Starting at URL: wordpress.com/post
2. Add a Featured Image from the sidebar
3. Decide you don't like the way it looks and want to change....click the current image in the sidebar.
4. Editor opens but the image is not "checked" to say which one is currently used.

#### What I expected
The currently used image should be first on the list and checked, indicating it is the current featured image. Something like this:
screen shot 2017-03-16 at 11 10 42 am

#### What happened instead
The editor comes up without the image selected, so if you want to edit the image and have mulitples uploaded, you don't know which image is selected. Here's how it looks when you click in:
screen shot 2017-03-16 at 11 12 28 am

#user-report in a live chat. A user had multiple images that were similar uploaded and didn't like the way the current one looked on their home page. They decided to switch to a different version of the image, but didn't know which image was currently selected.

### PR DESCRIPTION
**Pull request by jeremeylduvall**
As described in #12109, if you're currently in the Media Library with selected items, leave to open a new post, and then try to add media to that post, you'll see the same selected items. This PR adds `MediaActions.setLibrarySelectedItems( this.props.site.ID, [] );` when the Media Library component clearing the selected items so this no longer occurs. This is similar to how we handle it in the post editor ([#](https://github.com/Automattic/wp-calypso/blob/master/client/post-editor/media-modal/index.jsx#L113)).

This is also an attempt to resolve #12235. Currently, if you set a featured image for a post then open the featured image media modal, the current featured image is not selected. This can create confusion if you have a lot of media items or multiple versions of the same image. This first attempt does the following:

- Render `MediaListData` in the Editor Drawer to have access to the media items for the existing site.
- Search for the featured image for the post. If it exists, using `MediaActions.setLibrarySelectedItems` to set the featured image as selected when the modal opens.

## To test
#12109
1. Load this branch and start on http://calypso.localhost:3000/media/. 
2. Select some images in the media library.
3. Click "Add" next to Posts to start a new post.
4. Click the + icon to add an image to your new posts. Notice that the previously selected images are no longer selected.

#12235
1. Load this branch and then start a new post at http://calypso.localhost:3000/post/
2. Set a featured image for your post.
3. Once you set a featured image, click on the image again to open the media modal. The existing featured image should be selected currently.

## GIF
Clearing selected images
selectedmedia

Featured image
featured

### CODE REVIEW

**Comment by gwwar** [comment]
@jeremeylduvall Do you mind pulling this out into one PR per issue? Both should be quick to review

File: client/post-editor/editor-drawer/featured-image.jsx [hunk 1]
```diff
@@ -41,11 +42,13 @@ class EditorDrawerFeaturedImage extends Component {
 					empty={ ! site || ! post || ! getFeaturedImageId( post ) }
 					onClick={ this.startSelecting }
 					onRemove={ this.removeImage }>
-					<FeaturedImage
-						selecting={ this.state.isSelecting }
-						onImageSelected={ this.endSelecting }
-						site={ site }
-						post={ post } />
+					<MediaListData siteId={ this.props.site.ID }>
```
Comment (gwwar) [inline client/post-editor/editor-drawer/featured-image.jsx]: @youknowriad or @iseulde is it safe to use `QueryMedia`? Or is this more appropriate?

File: client/post-editor/editor-featured-image/index.jsx [hunk 2]
```diff
@@ -41,6 +43,13 @@ export default React.createClass( {
 	},
 
 	showMediaModal() {
+		const featuredImage = PostUtils.getFeaturedImageId( this.props.post );
```
Comment (gwwar) [inline client/post-editor/editor-featured-image/index.jsx]: For naming about `featuredImageId` or `id`.

File: client/post-editor/editor-featured-image/index.jsx [hunk 3]
```diff
@@ -41,6 +43,13 @@ export default React.createClass( {
...
+		
+		if ( featuredImage ) {
+			const selectFeaturedImage = filter( this.props.media, { ID: featuredImage } );
```
Comment (gwwar) [inline client/post-editor/editor-featured-image/index.jsx]: Maybe `filteredItems` here so we know this is an array.

File: client/my-sites/media-library/index.jsx [hunk 4]
```diff
@@ -60,6 +60,7 @@ module.exports = React.createClass( {
 
 	componentWillUnmount: function() {
 		delete this.onSearch;
+		MediaActions.setLibrarySelectedItems( this.props.site.ID, [] );
```
Comment (gwwar) [inline client/my-sites/media-library/index.jsx]: This breaks any gallery creation, since the selection is cleared when we go away from list view.
screen shot 2017-03-24 at 12 24 38 pm

File: client/post-editor/editor-drawer/featured-image.jsx (hunk 1 above)
Comment (youknowriad) [inline client/post-editor/editor-drawer/featured-image.jsx]: Yep, It is, I've already used it in Stats. I think it should be fine to use. The only issue we could have is if we're expecting the Flux Store to be filled with the media somewhere on the underlying component.

**Comment by jeremeylduvall** [comment]
Separated a piece of this for highlighting the selected featured image in #12590. I'll work on a different approach for clearing the media selection here.

**Comment by jeremeylduvall** [comment]
@gwwar that regression should now be fixed. I went with a different approach. Instead of clearing the selected media items when the library unmounts, we clear them when the post editor media modal mounts. You should expect the following behavior:

- In `/media`, select some items. Load the post editor. Try to add some images to a post. You will not see any items pre-selected from `/media`.
- Try to create a gallery in a post. This should work as expected. When you continue on to the gallery preview, you'll see the selected items. If you go back to the Media Library, the images will still be selected. If you edit an existing gallery, you'll see the existing items selected.
- If you setup a post with a gallery, save the post, then reload and go to edit the gallery, you should see the correct items selected. This is why I'm comparing `view !== ModalViews.GALLERY`.

One follow-up question:
- In `/media`, select some items. Go visit your stats page. Then, come back to `/media`. You should still see the same items selected since you haven't loaded the post editor media modal (anytime you load the editor). Is this expected or would you expect it to be cleared out?

Here's a GIF of the various flows:

selectedmedia

**Comment by gwwar** [comment]
@jeremeylduvall if this one is ready for another 👀  don't forget to add a `needs review` label to the PR

**Comment by jeremeylduvall** [comment]
Thanks @gwwar. Completely spaced. It's ready for a set of eyes. I did have a question listed above:

> In /media, select some items. Go visit your stats page. Then, come back to /media. You should still see the same items selected since you haven't loaded the post editor media modal (anytime you load the editor). Is this expected or would you expect it to be cleared out?

I couldn't decide if that was expected or not.

File: client/post-editor/media-modal/index.jsx [hunk 5]
```diff
@@ -108,6 +109,14 @@ export class EditorMediaModal extends Component {
 		this.statsTracking = {};
 	}
 
+	componentWillMount() {
+		const { view, mediaLibrarySelectedItems, site } = this.props;
+
+		if ( ! isEmpty( mediaLibrarySelectedItems ) && view !== ModalViews.GALLERY ) {
```
Comment (gwwar) [inline client/post-editor/media-modal/index.jsx]: Do we only want this to occur for the list view?
```jsx
if ( ! isEmpty( mediaLibrarySelectedItems ) && view === ModalViews.LIST ) {
```

**Comment by gwwar** [comment]
> I couldn't decide if that was expected or not.

I think the media section behavior is OK. We can always update that later.

**Comment by alisterscott** [comment]
I ran the media e2e spec against this PR (desktop and mobile) and all tests passed.
