### PR TITLE
Help Center: Add chat scroll position management

### LINKED ISSUE #97928: Help Center: Clicking on Related Guides and back does not remember the place
### What

Image

When a user clicks on an article, and then back, it is brought back to the chat, but in the wrong position.

### Why

It would be nice to bring the user back to the same place.

### PR DESCRIPTION
**Pull request by agrullon95**
Fixes https://github.com/Automattic/wp-calypso/issues/97928

## Proposed Changes

* Add chat scroll position management when navigating back to the Odie chat.

https://github.com/user-attachments/assets/360c9976-4e79-4784-8947-186e9a0f7bd9

## Why are these changes being made?

*

## Testing Instructions

* Checkout branch or use live link.
* Open the help center, open a new chat, send a message such as `how do I update my site icon`, scroll down and open a link from the `Related Guides` section.
* Click the back button and verify the chat scrolls back down to its previous position before you clicked on the `Related Guide` link.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: packages/odie-client/src/components/message/messages-container.tsx [hunk 1]
```diff
@@ -57,8 +61,51 @@ export const MessagesContainer = ( { currentUser }: ChatMessagesProps ) => {
...
+	const navType: NavigationType = useNavigationType();
+
+	const { odieChatScrollPosition } = useSelect( ( select ) => {
+		const helpCenterSelect: HelpCenterSelect = select( HELP_CENTER_STORE );
+		return {
+			odieChatScrollPosition: helpCenterSelect.getOdieChatScrollPosition(),
+		};
+	}, [] );
+
+	const shouldAutoScroll = false;
```
Comment (agrullon95) [inline packages/odie-client/src/components/message/messages-container.tsx]: Hardcoded value for testing

**Review by escapemanuele — APPROVED** [review]
LGTM!

**Comment by escapemanuele** [comment]
Is this good to go @agrullon95 ?
