### PR TITLE
Gutenberg: Add WP.com shortlinks extension

### LINKED ISSUE #29221: Gutenberg: Shortlink section missing from editor sidebar
#### Steps to reproduce 

- Start with a WordPress.com site and opt-in for the new WordPress Editor, start and https://wpcalypso.wordpress.com/block-editor/post/ (if you choose this, skip the second step)
- Click `Add` next to `Blog posts`/`Site pages` 
- Publish a post

#### What is expected 

A shortlink is shown on the sidebar, after publishing it. It's shown on the Calypso editor. This can be seen under the `Sharing` section.

screenshot 2018-12-07 at 14 34 19

#### What happens instead 

No shortlink section seen, either on Gutenberg in Calypso, or Gutenberg in wp-admin

screenshot 2018-12-07 at 14 33 28
screenshot 2018-12-07 at 14 32 54

### PR DESCRIPTION
**Pull request by tyxla**
Fixes https://github.com/Automattic/jetpack/issues/10925
Fixes #29221

In the WP.com old editor, we used to have the shortlinks handy in the sidebar. We don't have them in Gutenberg, and they can sometimes be a very handy feature. This PR creates the UI for the WP.com shortlinks, adds it to the Jetpack sidebar and registers it as a beta extension. 

For inspiration of how it looks and works, we're borrowing from the legacy Calypso editor sidebar:

Also, see the corresponding Jetpack PR that's necessary for this to work: https://github.com/Automattic/jetpack/pull/10981

#### Changes proposed in this Pull Request

* Create a new panel in the Jetpack sidebar for displaying WP.com shortlinks
* Add WP.com shortlinks in the list of Jetpack beta extensions

#### Preview

Positioning in the Jetpack sidebar:

How it looks:

Focusing the field autoselects the shortlink:

#### Testing instructions

* Spin up a new JN site with this branch and the `update/shortlinks-rest-api-gutenberg` Jetpack branch from this link: https://jurassic.ninja/create?shortlived&jetpack-beta&gutenpack&branch=update/shortlinks-rest-api-gutenberg&calypsobranch=add/jetpack-gutenberg-shortlinks
* Connect the site and activate all recommended features.
* Start writing a post.
* Save the post.
* Click the Jetpack icon in the sidebar.
* Verify you can see the Shortlink panel, with a shortlink in it.
* Focus the shortlink field by clicking in it.
* Verify the link gets autoselected so it can be copied easily.

#### Notes

I'm marking this as low priority, as it isn't super important to have. In the same time, I think it's handy to have it, and it's straightforward enough so we could have it ready for the next Jetpack version.

### CODE REVIEW

**Comment by simison** [comment]
Seems like a perfect case for clipboard component from Calypso, but at the same time I wouldn't complicate something that already works.

https://wpcalypso.wordpress.com/devdocs/client/components/forms/clipboard-button/README.md

**Comment by tyxla** [comment]
> Seems like a perfect case for clipboard component from Calypso, but at the same time I wouldn't complicate something that already works.

Yeah, I thought that for the first iteration we could keep it simple and do what we already were doing in Calypso. Will wait for some design feedback to confirm that decision though.

File: client/gutenberg/extensions/shortlinks/panel.js [hunk 1]
```diff
@@ -0,0 +1,39 @@
+/** @format */
```
Comment (simison) [inline client/gutenberg/extensions/shortlinks/panel.js]: We can drop Prettier pragmas since https://github.com/Automattic/wp-calypso/pull/29403

Comment (tyxla) [reply client/gutenberg/extensions/shortlinks/panel.js]: 👍 Good point, removed in https://github.com/Automattic/wp-calypso/pull/29475/commits/1e3979b42c6a321f7cbe114ff47347f9c203f690

**Comment by MichaelArestad** [comment]
Nice!

My initial instinct would be to enhance the Gutenberg interface like this:
image

However, I suspect that not only will the permalink location be changing, but we also face the problem of folks not knowing where shortlinks come from. I think what you came up with is a great start. My suggestions would be to indeed add the clipboard component next to what you're already displaying. I can't tell from the docs, but if it adds a button with an icon next to the link, it'll look great. I would appreciate you taking a stab at adding the clipboard functionality.

**Comment by tyxla** [comment]
Thank you, folks!

> My suggestions would be to indeed add the clipboard component next to what you're already displaying. I can't tell from the docs, but if it adds a button with an icon next to the link, it'll look great. I would appreciate you taking a stab at adding the clipboard functionality.

Sounds like something that would make sense to be explored in another PR. Will merge this one, and will explore using a clipboard button next to the link. Stay tuned!

**Comment by tyxla** [comment]
@MichaelArestad @simison: I've fiddled with adding the copy button, here's a PR: #29556
