### PR TITLE
Don't autocapitalize username input.

### LINKED ISSUE #4106: People: keyboard should not default to uppercase when adding new users on mobile devices
#### Steps to reproduce
1. Go to add a new user either on Android or iOS at people/new/$site
2. Type in your first username
3. See that the first letter is automatically capitalized:

Android:
capitalized-first-letter-android

iOS:
capitalized-first-letter-ios

4. After typing the first username, start to type the second username and see that it will also be capitalized automatically on Android (but not iOS):

Android:
capitalize-second-word-android

iOS:
not-capitalize-second-word-ios

#### What I expected
I expected to type and see lowercase letters. Both emails and usernames are not generally capitalized.

### PR DESCRIPTION
**Pull request by obenland**
The `autocapitalize` attribute should help prevent iOS from
automatically capitalizing usernames. See
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-aut
ocapitalize

This only spreads props in `TokenInput` and maintains the whitelist in
`TokenField`. Would love to hear feedback on the approach, anything I
can do better or differently?

/@aduth @gwwar

Fixes #4106.

Test live: https://calypso.live/?branch=fix/uppercase-username

### CODE REVIEW

**Comment by gwwar** [comment]
Interesting the attribute is non-standard but it seems like this should fix the issue for the browsers that do support this. (Seems to work on a real Nexus 5, Chrome/FF). I would also suggest turning off autocomplete for this input field `autocomplete="off"` to avoid any frustration with entering in a username or email.

File: client/components/token-field/index.jsx [hunk 1]
```diff
@@ -183,6 +183,12 @@ var TokenField = React.createClass( {
 			} );
 		}
 
+		if ( autoCapitalize ) {
+			Object.assign( props, {
+				autoCapitalize: autoCapitalize
+			} );
```
Comment (gwwar) [inline client/components/token-field/index.jsx]: Optional, but we can add a little [sugar](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator) and do:
```javascript
props = { ...props, autoCapitalize };
```

File: client/components/token-field/token-input.jsx [hunk 2]
```diff
@@ -24,14 +25,14 @@ var TokenInput = React.createClass( {
 	mixins: [ PureRenderMixin ],
 
 	render: function() {
+		const props = omit( this.props, 'onChange' );
```
Comment (gwwar) [inline client/components/token-field/token-input.jsx]: Maybe try:
```javascript
const props = { ...this.props, onChange: this._onChange };
```

And then remove the `onChange={ this._onChange }`

File: client/components/token-field/index.jsx (hunk 1 above)
Comment (aduth) [inline client/components/token-field/index.jsx]: >Optional, but we can add a little sugar and do:

There's also a critical difference between the two that makes @gwwar's suggestion preferable, which is that the object spread syntax assigns values into a new object. In the original code, `Object.assign` will mutate props directly, which could have unintended consequences. If kept with current syntax, you'd want to pass an empty object as the first argument so that `props` is not mutated.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

**Comment by gwwar** [comment]
Nice work @obenland I think your approach here is good, we just need to be on the lookout for any extra props that are passed to the component, but aren't valid input attributes. This is mostly harmless, but it's particularly annoying since we'll get warnings like we see in #7413

**Comment by gwwar** [comment]
👍  Took a quick glance at `TokenInput`, and I think we're ok with passing in all props. I don't see any React warnings in dev either.

**Comment by gwwar** [comment]
While we're in here, let's also update the `autocomplete="off"`. This should be good to 🚢  after we  do this.

File: client/components/token-field/index.jsx (hunk 1 above)
Comment (gwwar) [inline client/components/token-field/index.jsx]: Ah right, nice eye. The equivalent is actually the following if we don't want to mutate props.
```
Object.assign( {}, props, { autoCapitalize: autoCapitalize } );
```

Comment (obenland) [inline client/components/token-field/index.jsx]: Yeah, I was wondering about that. Line 181 did it that way and so I thought I'd stay consistent. We should probably update that too.

**Comment by gwwar** [comment]
👍  Looks great @obenland! Chrome appears to be ignoring the `autocomplete` but it should still be useful for other browsers.

**Comment by gwwar** [comment]
congrats

Congrats on the first Calypso deploy!
