### PR TITLE
Bugfix: Retrieve installed plugins information when not available in cache

### LINKED ISSUE #60704: `Installed on * site(s)` bug
> I think all sites view for the plugins states incorrect Installed on * site(s) label for me. e.g. the bookings plugin is installed on 3 of my sites but on plugins screen it states Installed on 1 site  and if go to plugin details then I get Installed on 1 site . Moreover, one of my site which has plugin installed that shows under Available on. Upon, further investigation I found that, this info is retrieved using cache info available in redux store for given user. If you delete indexed db then it will display that plugin is available on all sites and it's installed on none.

Related convo p1643686380322949-slack-C02JPCHEKDY

### PR DESCRIPTION
**Pull request by WBerredo**
### Changes proposed in this Pull Request

* Add plugin query to Plugin Details page for direct accesses
* Use the current sites instead of the previous to retrieve plugin info

### Testing instructions
**Browser Plugins**
* Go to `plugins` page, without a selected site
* Clear the indexed DB from your browser
* Reload the page and check if the `Installed on * sites`  is properly shown`

**Plugin Details**
* Click on a plugin to go to the Plugin Details page
* Clear the indexed DB from your browser
* Reload the page and check if the `Installed on` area is properly shown
---

Fixes #60704

### CODE REVIEW

**Review by cpapazoglou — CHANGES_REQUESTED** [review]
While the changes make sense and work for me when testing, I did notice that in a site specific details page we are making duplicate requests to the plugins endpoint on this branch

SS 2022-02-01 at 17 09 27

**Comment by WBerredo** [comment]
Thanks for catching this @cpapazoglou.

The empty array check was fixed in this commit https://github.com/Automattic/wp-calypso/pull/60707/commits/063907acefb3ab16a3253035ec0e57399bacb1b6

File: client/components/data/query-jetpack-plugins/index.jsx [hunk 1]
```diff
@@ -15,7 +15,7 @@ class QueryJetpackPlugins extends Component {
 	};
 
 	componentDidMount() {
-		if ( this.props.siteIds && ! this.props.isRequestingForSites ) {
+		if ( this.props.siteIds.length && ! this.props.isRequestingForSites ) {
```
Comment (cpapazoglou) [inline client/components/data/query-jetpack-plugins/index.jsx]: Since `siteIds` is optional should we use `this.props.siteIds?.length`?

File: client/my-sites/plugins/plugin-details.jsx [hunk 2]
```diff
@@ -226,6 +227,7 @@ function PluginDetails( props ) {
 			<SidebarNavigation />
 			<QueryEligibility siteId={ selectedSite?.ID } />
 			<QueryProductsList persist />
+			<QueryJetpackPlugins siteIds={ siteIds } />
```
Comment (cpapazoglou) [inline client/my-sites/plugins/plugin-details.jsx]: Let's conditionally query the plugin only if  `isJetpack === true` (atomic or self hosted).

File: client/components/data/query-jetpack-plugins/index.jsx (hunk 1 above)
Comment (cpapazoglou) [reply client/components/data/query-jetpack-plugins/index.jsx]: BTW, I am still getting two `https://public-api.wordpress.com/rest/v1.1/sites/[SiteId]/plugins` requests

Comment (WBerredo) [reply client/components/data/query-jetpack-plugins/index.jsx]: > Since siteIds is optional should we use this.props.siteIds?.length?

I was considering it as required given the propTypes:
```js
siteIds: PropTypes.arrayOf(
  PropTypes.oneOfType( [ PropTypes.string, PropTypes.number ] ).isRequired
).isRequired,
```

But figured out the previous version would not be a problem as the empty array would go to a `map` later down the line and **do nothing**.

> I am still getting two https://public-api.wordpress.com/rest/v1.1/sites/[SiteId]/plugins requests

I just found the actual problem.

1. When you don't have a selected site, this page is not firing any requests. After my change, it is firing only once. 
1. When you have a selected site, the page is already firing this request. After my change, it is firing twice.


I need to figure out where this first request for the selected site is being made, to assess how to best approach it.

Comment (WBerredo) [reply client/components/data/query-jetpack-plugins/index.jsx]: here the query is made only for the current site: https://github.com/Automattic/wp-calypso/blob/d3189b2d6fd95ec3c281f6f99be6112f60d5a256/client/my-sites/sidebar-unified/use-site-menu-items.js#L26-L33

Comment (cpapazoglou) [reply client/components/data/query-jetpack-plugins/index.jsx]: I think we can remove it from there and let each page / implementation decide if they want to fetch the plugins?

Comment (WBerredo) [reply client/components/data/query-jetpack-plugins/index.jsx]: I created another PR doing everything on the `use-site-menu-items`. What do you think?

PR: #60778

Comment (cpapazoglou) [reply client/components/data/query-jetpack-plugins/index.jsx]: I believe that `use-site-menu-items` shouldn't be fetching the plugins. For example, why users navigating to **Media** or **Home** would need the plugins? The addition of `dispatch( fetchPlugins( [ selectedSiteId ] ) ); ` to `use-site-menu-items` seems like a workaround that we need to avoid. 

Any page needing the site plugins should really use `<QueryJetpackPlugins siteIds={ siteIds } />` or something equivalent.

Comment (WBerredo) [reply client/components/data/query-jetpack-plugins/index.jsx]: Agreed, the fetch was removed from `use-menu-items` on https://github.com/Automattic/wp-calypso/pull/60707/commits/d071c4e7d7c0f2d32981409670e36c75c74f784f

File: client/my-sites/plugins/plugin-details.jsx (hunk 2 above)
Comment (WBerredo) [reply client/my-sites/plugins/plugin-details.jsx]: I don't think it is needed as the `siteIds` values come from the `getSelectedOrAllSitesWithPlugins` which already validates if it is jetpack or not. 

https://github.com/Automattic/wp-calypso/blob/d071c4e7d7c0f2d32981409670e36c75c74f784f/client/state/selectors/get-selected-or-all-sites-with-plugins.js#L16-L23

**Review by cpapazoglou — APPROVED** [review]
LGTM! Thanks for bearing with me and resolving all feedback!
