### PR TITLE
Editor: Restore Flux actions to post editor on visiblity change

### LINKED ISSUE #16898: Editor: Post visibility setting doesn't save when trying to change from private
Discovered in a live chat today, when you have a post that has been set to "private", you can not successfully change it's visibility back to public or password-protected. It will not let you select "Public" at all. It will let you select "Password Protected", however after updating you'll discover the change wasn't actually saved. If you attempt to refresh the page you'll see browser alerts saying you have unsaved changes, suggesting that nothing actually was saved.

post-visibilty-bug-video

**Steps to reproduce**
1. Open up any post on a test site, or create one and set the post visibility to "Private". Then Update/Publish.
2. Then try to change that setting to either Public or Password-Protected. Then Update.
3. View the post to see if it actually has been changed from private.

**Browser / OS version**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

cc @mattsherman who I see last made updates (3 days ago) to the post-visibility code in #16710

### PR DESCRIPTION
**Pull request by jeremeylduvall**
This restores some necessary Flux actions to the Post Editor when changing from private to a public or password protected post. Since changing a post to privately published automatically changes the status to "private," we need to update the status back to either "draft" or "publish" when changing to another visibility.

## To test
1. Open a new post at http://calypso.localhost:3000/post/
2. Change the post to "Private." It will get published right away.
3. Try to change it back to "Public." Notice the change is accepted now.

## GIF
visibility

Fixes #16898 and #16822

### CODE REVIEW

File: client/post-editor/editor-visibility/index.jsx [hunk 1]
```diff
@@ -189,6 +189,8 @@ const EditorVisibility = React.createClass( {
 	updateVisibility( newVisibility ) {
 		const { siteId, postId } = this.props;
 		let reduxPostEdits;
+		const defaultVisibility = 'draft' === this.props.status ? 'draft' : 'publish';
+		const postEdits = { status: defaultVisibility };
```
Comment (mattsherman) [inline client/post-editor/editor-visibility/index.jsx]: This needs a comment. Because I didn't understand what the code was doing when it was originally in here, thought we had regression-tested the related parts of product to confirm things were still working, and thought this was just old code that could be removed. I don't want to see somebody else make the same mistake again!

It would be better to also rework the code to make it clear that it is handling the case from private -> public/password.

Even better, let's consolidate these additions to a single function called from this one.

**Comment by mikeshelton1503** [comment]
Tested and works as expected 👍

**Comment by jeremeylduvall** [comment]
Thanks @mattsherman! I pulled the action out into a separate function call and added a note to clarify. Let me know what you think!

**Comment by mattsherman** [comment]
Thanks for refactoring -- much more clear now! Tested and works as expected. 👍

**Comment by alisterscott** [comment]
Thanks for the quick fix 👍
