### PR TITLE
Stepper: Use siteId or siteSlug for exitFlow redirects

### LINKED ISSUE #64054: [Bug]: Redirects from Intent screen (Stepper) fail when using a custom domain
### Quick summary

After purchasing a custom domain and landing on the Stepper Intent screen, the following actions do not complete successfully:
* Network request to set intent (`setIntentOnSite`)
* Clicking on the Write intent and then clicking on then on "Draft First Post"
* Clicking on "Let our experts create your dream site."
* possibly more...

After purchasing a domain, the URL of the Intent screen is `/setup/intent?siteId=<site id>`. All the above redirects attempt to navigate to URLs using the `siteSlug` query parameter, which is `null`.

### Steps to reproduce

1. Go to https://worpress.com/start
2. Choose a paid domain.
3. Choose any paid plan.
4. After checkout, on the Intent screen, select the "Write" intent.
5. After filling in the site title, click on "Draft First Post".
6. You are redirected to https://wordpress.com/post?site=null

### What you expected to happen

These redirects work correctly, using the `siteId` instead of the `siteSlug` when the `siteSlug` is not available.

### What actually happened

The URLs have `null` in the `siteSlug` param.

### Context

_No response_

### Browser

_No response_

### Simple/Atomic

_No response_

### Other notes

_No response_

### Reproducibility

Consistent

### Severity

_No response_

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by aneeshd16**
#### Changes proposed in this Pull Request

When exiting any of the flows using `exitFlow`, we use the `siteSlug` query parameter in the redirect URLs. However, when coming to the intent screen after purchasing a custom domain, the `siteId` is used in the query params instead of the `siteSlug`. Due to this, the redirects from `exitFlow` work incorrectly. See #64054 for more details.

#### Testing instructions

- Go to `/setup/intent?siteId=<site id>`
- Select the "Write" intent.
- After filling in the site title, click on "Draft First Post".
- You should be redirected to https://wordpress.com/post/<site slug>
- 

Fixes #64054

### CODE REVIEW

File: client/landing/stepper/declarative-flow/site-setup-flow.ts [hunk 1]
```diff
@@ -57,15 +57,13 @@ export const siteSetupFlow: Flow = {
...
 		const startingPoint = useSelect( ( select ) => select( ONBOARD_STORE ).getStartingPoint() );
-		const siteSlug = useSiteSlugParam();
-		const siteId = useSelect(
-			( select ) => siteSlug && select( SITE_STORE ).getSiteIdBySlug( siteSlug )
-		);
+		const site = useSite();
+		const siteSlug = site ? new URL( site.URL ).host : null;
 		const adminUrl = useSelect(
-			( select ) => siteSlug && select( SITE_STORE ).getSiteOption( siteId as number, 'admin_url' )
+			( select ) => site && select( SITE_STORE ).getSiteOption( site.ID as number, 'admin_url' )
```
Comment (alshakero) [inline client/landing/stepper/declarative-flow/site-setup-flow.ts]: Since you checked the `site` before calling select, ID is a number for sure.

```suggestion
			( select ) => site && select( SITE_STORE ).getSiteOption( site.ID, 'admin_url' )
```

**Review by alshakero — APPROVED** [review]
LGTM!
