### PR TITLE
Image Editor: window.onResize for crop box

### LINKED ISSUE #7983: Image Editor: Crop box can become misaligned if you resize the browser window
#### Steps to reproduce
1. Start editing an image
2. Resize the browser window
3. Observe that the cropping outline doesn't resize properly:

screen shot 2016-09-08 at 3 37 16 pm

Observed in Chrome on macOS Sierra

### PR DESCRIPTION
**Pull request by artpi**
Fixes #7983

Adds `window.onResize` event to align crop box to content.

## Testing

- Start editing an image
- Resize the browser window
- Observe that crop box stays aligned

CC @lamosty @rralian @gwwar

### CODE REVIEW

**Comment by lamosty** [comment]
This fixes the issue, great work!

LGTM :shipit:

File: client/post-editor/media-modal/image-editor/image-editor-canvas.jsx [hunk 1]
```diff
@@ -97,12 +100,22 @@ const MediaModalImageEditorCanvas = React.createClass( {
 
 		this.drawImage();
 		this.updateCanvasPosition();
+		this.onWindowResize = throttle( this.updateCanvasPosition, 200 );
+		if ( window ) {
```
Comment (gwwar) [inline client/post-editor/media-modal/image-editor/image-editor-canvas.jsx]: This will throw an error if window isn't defined. If we'd like to do a check a safer one would be:

```javascript
if ( typeof window !== 'undefined' )
```

Comment (lamosty) [inline client/post-editor/media-modal/image-editor/image-editor-canvas.jsx]: Oh, great catch. Sorry it slipped me.. `window` is just a variable like any other and we can't test whether it's defined or not like we check for falsey value. Good to know.
