### PR TITLE
State: Make JPO data layer save more optimistic

### LINKED ISSUE #21868: JPO: remove form fields after deleting corresponding JP options.
Data fetched from the .org site fails to be updated in Calypso when we delete it. 

#### Steps to reproduce
1. follow the instructions on https://github.com/Automattic/jetpack/pull/8426
2. input text in the site title field, click Next Step
3. on your sandbox run `wp option delete blogname `
4. go back to the Site Title step

#### What I expected
Empty Site Title field. 

#### What happened instead
The data in the field is still present.

Note: occurring both forms (Site Title and Business Address steps) and all fields.

### PR DESCRIPTION
**Pull request by tyxla**
We're providing an optimistic UI for the JPO flows, and that is nice. However, our saving in the data layer isn't declared as optimistically as the UI would assume it should be. 

Currently, when saving settings, we'll accept those settings as valid only when the request is successful. This causes inconsistencies, as described by #21868 and particularly the case that @ockham has described. Fixes #21868.

This PR updates our saving data layer to be a little more optimistic, updating the settings immediately. In other words, settings are being updated immediately, and we don't need to wait for the request to complete in order to update the UI.

To test:
* Checkout this branch
* In the 'Site Title' step, make sure you have something saved in the description field.
* Change the description.
* Click the 'Next Step' CTA.
* Click 'Back' quickly.
* Verify the new content is displayed in the description field, and not the previous one.

### CODE REVIEW

**Comment by ockham** [comment]
Noting here that we should also test this with WooCommerce installation: We need to verify that the spinner on the summary page is still shown during installation (and then changed into a checkmark), since that behavior relies on the data-layer's `isRequesting` introspection feature, which IIRC didn't work if the [success callback was set to `noop`](https://github.com/Automattic/wp-calypso/pull/22131/files#diff-2bc1b67d0ef2a5e01eb95b99c58e1c62R124).

**Comment by ockham** [comment]
> Noting here that we should also test this with WooCommerce installation: We need to verify that the spinner on the summary page is still shown during installation (and then changed into a checkmark), since that behavior relies on the data-layer's `isRequesting` introspection feature, which IIRC didn't work if the [success callback was set to `noop`](https://github.com/Automattic/wp-calypso/pull/22131/files#diff-2bc1b67d0ef2a5e01eb95b99c58e1c62R124). 

Just tested. The spinner keeps spinning, even tho WooCommerce is successfully installed. That's a regression that's likely going to go unnoticed if we don't fix it as part of this PR I'm afraid :slightly_frowning_face:

**Comment by ockham** [comment]
> That's a regression that's likely going to go unnoticed if we don't fix it as part of this PR I'm afraid slightly_frowning_face

Ideally we'll add a unit test to guard against that :thinking:

**Comment by tyxla** [comment]
Good catch @ockham!

Looks like the data layer request tracker relies on actions dispatched in order to make any updates to the status of a tracked request (which of course makes complete sense).

So we could hack the data layer request tracker to work with `noop`s, but that doesn't sound right. This leaves us with the only remaining option of having a separate generic save success action, which would be used essentially for the request tracker to properly mark the request as completed.

Updated the PR to contain that solution; feel free to have another look.

File: client/state/jetpack-onboarding/actions.js [hunk 1]
```diff
@@ -37,6 +38,12 @@ export const saveJetpackOnboardingSettings = ( siteId, settings ) => ( {
 	},
 } );
 
+export const saveJetpackOnboardingSettingsSuccess = ( siteId, settings ) => ( {
```
Comment (ockham) [inline client/state/jetpack-onboarding/actions.js]: Maybe add a comment above this method that explains [why it is needed](https://github.com/Automattic/wp-calypso/pull/22131#issuecomment-363132972) even tho it doesn't seem to do anything, so people (e.g. future me) aren't tempted to _Rip it All Out™️_

Comment (tyxla) [reply client/state/jetpack-onboarding/actions.js]: Done in https://github.com/Automattic/wp-calypso/pull/22131/commits/baf9ca00995fdd7fb03b8bf0146f5d06e756b50b - let me know if that looks good.

File: client/state/data-layer/wpcom/jetpack-onboarding/index.js [hunk 2]
```diff
@@ -104,10 +109,12 @@ export const saveJetpackOnboardingSettings = ( { dispatch, getState }, action )
...
 };
 
-/* Store onboarding settings in Redux state */
-export const storeJetpackOnboardingSettings = ( { dispatch }, { settings, siteId } ) => {
-	dispatch( updateJetpackOnboardingSettings( siteId, settings ) );
-};
+// Although we don't use the save success action in any of the reducers,
+// we need to dispatch some action in order to signal to the data layer that
+// the save request has finished. Tracking those requests is necessary for
+// displaying an up to date progress for some steps.
```
Comment (ockham) [inline client/state/data-layer/wpcom/jetpack-onboarding/index.js]: Maybe `[...] progress indicator [...]`

File: client/state/jetpack-onboarding/actions.js (hunk 1 above)
Comment (ockham) [reply client/state/jetpack-onboarding/actions.js]: Looks great! Maybe say `progress indicator` instead of just `progress`.

File: client/state/data-layer/wpcom/jetpack-onboarding/index.js (hunk 2 above)
Comment (tyxla) [reply client/state/data-layer/wpcom/jetpack-onboarding/index.js]: 👍  even better - 6d5f07415d
