### PR TITLE
Gutenframe: handle post lock actions.

### LINKED ISSUE #30859: Gutenframe: post lock actions won't open in iframe
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/block-editor/post
2. Create a new post and publish it.
3. Continue editing the above post.
4. In an incognito session, log in with a different test account that has editor privileges on the same test site.
5. Try to edit the post created in step 2.
6. You should see the following post lock options:

screenshot 2019-02-18 at 14 39 33

7. Clicking on `All Posts` or `Take Over` will result in the following error:

`Refused to display 'https://example.wordpress.com/wp-admin/edit.php?post_type=post' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

### PR DESCRIPTION
**Pull request by rodrigoi**
#### Changes proposed in this Pull Request

This PR adds the handling of the _All Posts_ action from the Gutenframe, when a post is locked for editing or when editing has been taken over by another user.

| Post Locked | Post Takeover |
| - | - |
| screen shot 2019-02-26 at 02 35 11 | screen shot 2019-02-26 at 02 35 59 |

The heavy lifting to handle these actions is done on the Gutenframe by D24835-code.

#### Testing instructions

To test this action you'll need a test site with two users, and either two different browsers or the same browser on a regular and an incognito sessions.

Sandbox the site and apply this patch: D24835-code. Edit the same post on both browsers. On the second browser, you should see the _This post is already being edited._ dialog.

screen shot 2019-02-26 at 13 15 50

Click on the _All Posts_ button. You should be redirected to the _Published_ tab of the list of posts. This should work for all posts types.

If you click the _Take Over_ button, switch to the first browser (where you were editing the post) and after a few seconds the you should the the _Someone else has taken over this post._ dialog.

screen shot 2019-02-26 at 13 33 12

If you click on the _All Posts_ button, you should be redirected again to the list of posts page with the correct post type.

Fixes #30859

### CODE REVIEW

File: client/state/selectors/get-post-type-all-posts-url.js [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+export const getPostTypeAllPostsUrl = ( state, postType ) => {
+	const siteId = getSelectedSiteId( state );
+	const siteSlug = getSiteSlug( state, siteId );
+	const isJetpack = isJetpackSite( state, siteId );
+	const isSingleUSer = isSingleUserSite( state, siteId );
+
+	const postTypeUrl = get( { page: 'pages', post: 'posts' }, postType, `types/${ postType }` );
+
+	if ( postType === 'post' && ! isJetpack && ! isSingleUSer ) {
+		return `/${ postTypeUrl }/my/${ siteSlug }`;
```
Comment (mmtr) [inline client/state/selectors/get-post-type-all-posts-url.js]: Any reason why this is redirecting to all _my_ posts and not to all the posts from everyone? Since the button label is "All posts" I expected to see all the posts as we do in WP Admin.

Comment (rodrigoi) [reply client/state/selectors/get-post-type-all-posts-url.js]: This is replicating the behaviour of the sidebar and of other selectors of the same type. The reason may as well be historical.
