### PR TITLE
Login: Move error messages to the API

### LINKED ISSUE #15476: Login: Move error messages to the API
We should move error messages from all login actions in the API. Currently, the login endpoints are designed to only return an error code whereas almost most of our REST API endpoints return an error message as well. As such, we have to maintain a [mapping between codes and messages](https://github.com/Automattic/wp-calypso/blob/e9000c464dc7522e81bc8a6102a2d66b8d16f716/client/state/login/actions.js#L39-L57) client-side.

I mentioned that problem up some time ago (see p1496902913038870-amber-dev), and I'm not entirely sure why we chose that path. As I said, maintaining that list in Calypso is not scalable, as it doesn't work for other client apps and it's easy to forget to add a message for any new code.

I'm bringing it up again because it only creates more and more problems as https://github.com/Automattic/wp-calypso/issues/15237 or the following error code (that has not any translation yet) can testify:

screenshot

### PR DESCRIPTION
**Pull request by pento**
This pull request fixes #15476 by retrieving error messages from the API, instead of storing them in Calypso.

This is a repeat of the previously reverted #15485.

#### Testing instructions

1. Run `git checkout fix/15476-login-messages-from-api-second-attempt` and start your server, or open a [live branch](https://calypso.live/log-in?branch=fix/15476-login-messages-from-api-second-attempt)
2. Sandbox wordpress.com, and any localised domains you want to test. Ie, fr.wordpress.com, es.wordpress.com.
3. Open the [`Log In` page](http://calypso.localhost:3000/log-in)
4. Check appropriate error messages display throughout the login process.
5. Check that the error messages are translated correctly when using a different locale.
6. Apply D6126 to your sandbox.
7. Repeat steps 3-5, ensuring you get the same messages.

#### Additional Notes

~~This was previously reverted due to wordpress.com not being recognised as a valid CORS domain. D6692 will need to be deployed before this PR is merged.~~

D6692 has been deployed.

#### Deploy Notes

1. ~~D6692 must be deployed first.~~
2. This PR can then be merged and deployed.
3. Wait 24+ hours, to ensure everyone currently on the login page is using this code, rather than an older version.
4. Deploy D6126.
5. Merge and deploy #16738.

#### Reviews

- [ ] Code

### CODE REVIEW

File: client/state/login/actions.js [hunk 1]
```diff
@@ -93,14 +95,22 @@ const errorFields = {
 	invalid_username: 'usernameOrEmail',
 };
 
+function getLocalizedLoginURL( action ) {
+	if ( 'en' === i18nUtils.getLocaleSlug() ) {
+		return 'https://wordpress.com/wp-login.php?action=' + action;
+	}
+
+	return 'https://' + i18nUtils.getLocaleSlug() + '.wordpress.com/wp-login.php?action=' + action;
+}
```
Comment (stephanethomas) [inline client/state/login/actions.js]: We can simplify this function a bit by taking advantage of the [`addLocaleToWpcomUrl()` helper](https://github.com/Automattic/wp-calypso/blob/c5980f62c134411981506cfedc642b6c0fab7e53/client/lib/i18n-utils/utils.js#L72-L78).

File: client/state/login/actions.js [hunk 2]
```diff
@@ -111,7 +121,14 @@ function getErrorFromHTTPError( httpError ) {
 		};
 	}
 
-	const code = get( httpError, 'response.body.data.errors[0]' );
+	code = get( httpError, 'response.body.data.errors.code' );
+	if ( code ) {
+		message = get( httpError, 'response.body.data.errors.message' );
+	} else {
+		// TODO: Remove when we're done with the fallback.
+		code = get( httpError, 'response.body.data.errors[0]', false );
```
Comment (stephanethomas) [inline client/state/login/actions.js]: Why do we set `code` to `false` when it cannot be found now?

I would rather remove that default value to keep the former behavior as otherwise `false` will appear in our stats (we indeed bump each error code encountered), which is less explicit than `undefined`.

File: client/state/login/actions.js [hunk 3]
```diff
@@ -93,14 +95,22 @@ const errorFields = {
...
+
 /**
  * Retrieves the first error message from the specified HTTP error.
  *
  * @param {Object} httpError HTTP error
  * @returns {{code: string?, message: string, field: string}} an error message and the id of the corresponding field, if not global
  */
 function getErrorFromHTTPError( httpError ) {
-	let message;
+	let message, code;
```
Comment (stephanethomas) [inline client/state/login/actions.js]: Super minor but we don't really have to declare `code` here. This can happen when we actually use it:

```
let code = get( httpError, 'response.body.data.errors.code' );
```

**Comment by yurynix** [comment]
I think we're missing the [polling of 2FA](https://github.com/Automattic/wp-calypso/blob/master/client/state/data-layer/wpcom/login-2fa/index.js#L37) localization here.

**Comment by yurynix** [comment]
Also what about magic login [here](https://github.com/Automattic/wp-calypso/blob/a9122c750e3e2a02018668fcf77d474b5ec57f11/client/state/login/magic-login/constants.js#L1) and this [lost password link here](https://github.com/Automattic/wp-calypso/blob/a70587157b33783ba4d5e0e4a1e136680d459d51/client/auth/login.jsx#L30) ?

File: client/state/login/actions.js (hunk 3 above)
Comment (pento) [inline client/state/login/actions.js]: 👍🏻

File: client/state/login/actions.js (hunk 2 above)
Comment (pento) [inline client/state/login/actions.js]: Good catch, I'll fix it up.

**Comment by pento** [comment]
I fixed the 2FA polling and lost password link.

That magic login endpoint doesn't return error messages, though the public-api endpoint that requests the email does. @jblz, are you okay with 2907004 for translating that message?

**Comment by pento** [comment]
Mildly interesting side note: putting an invalid email address (ie, a value without an `@`) into the magic login email form triggers the in-browser validation. The error messages for that validation are localised by browser default language, not by page language. It took a little bit of investigation to figure out what was going on. 🙂

File: client/lib/wpcom-undocumented/lib/undocumented.js [hunk 4]
```diff
@@ -1605,6 +1605,10 @@ Undocumented.prototype.validateNewUser = function( data, fn ) {
  */
 Undocumented.prototype.requestMagicLoginEmail = function( data, fn ) {
 	restrictByOauthKeys( data );
+
+	data.locale = i18n.getLocaleSlug();
```
Comment (yurynix) [inline client/lib/wpcom-undocumented/lib/undocumented.js]: I wondered what that returns for `en` locale, but @Tug said it should return `en` because of [this](https://github.com/Automattic/wp-calypso/blob/master/client/boot/common.js#L153).

**Comment by yurynix** [comment]
Code looks good , LGTM 👍
