### PR TITLE
Fix placeholders in /plans/compare

### LINKED ISSUE #4125: Plans: loading state in /plans/compare
We probably need placeholders or a better loading state for `/plans/compare`. This is what it looks like now:

domain

### PR DESCRIPTION
**Pull request by lamosty**
Fixes #4125.

## Testing Instructions

1. Navigate to http://calypso.localhost:3000/plans;
2. In Calypso, clear localStorage and IndexedDB so we don't have any cached data;
3. Throttle your Internet connection speed in the Network tab as shown on the screenshot below;
4. Click on Compare Plans link and verify that there are loading placeholders.

selection_063

## Screenshots

selection_076

cc @fabianapsimoes @hafizrahman @gwwar

Test live: https://calypso.live/?branch=fix/plans-compare-is-data-loading

### CODE REVIEW

File: client/components/plans/plans-compare/index.jsx [hunk 1]
```diff
@@ -74,6 +73,13 @@ const wordAdsFeature = {
 const PlansCompare = React.createClass( {
 	mixins: [ observe( 'features' ) ],
 
+	componentWillMount() {
+		this.setFreePlan = () => this.setPlan( 'free' );
+		this.setPersonalPlan = () => this.setPlan( 'personal' );
+		this.setPremiumPlan = () => this.setPlan( 'premium' );
+		this.setBusinessPlan = () => this.setPlan( 'business' );
```
Comment (lamosty) [inline client/components/plans/plans-compare/index.jsx]: I need this so that I don't create new fns each time a component is rendered (ie don't use `bind` or arrow fns). I wonder, isn't there a nicer way to accomplish the same?

File: client/components/plans/plans-compare/index.jsx [hunk 2]
```diff
@@ -123,7 +129,9 @@ const PlansCompare = React.createClass( {
 	},
 
 	isDataLoading() {
-		if ( ! this.props.features.get() ) {
+		const planFeatures = this.props.features.get();
+
+		if ( ! planFeatures || isEmpty( planFeatures ) ) {
```
Comment (lamosty) [inline client/components/plans/plans-compare/index.jsx]: This is the culprit of the issue. `this.props.features.get()` returns an empty array if the store doesn't return any data. Therefore, this condition was never `true` and therefore the placeholders were not showing.

File: client/components/plans/plans-compare/index.jsx (hunk 1 above)
Comment (gwwar) [inline client/components/plans/plans-compare/index.jsx]: What's preventing us from just defining these as class methods? eg
```
setFreePlan() {
   this.setPlan( 'free' );
}
```

**Comment by gwwar** [comment]
👍 Good to ship after cleaning up the setXPlan definitions.

File: client/components/plans/plans-compare/index.jsx (hunk 1 above)
Comment (lamosty) [inline client/components/plans/plans-compare/index.jsx]: Nothing but doesn't this take less space and is nicer? :D

Comment (gwwar) [inline client/components/plans/plans-compare/index.jsx]: But if we move these, we won't need the `componentWillMount` hook ;)

Comment (lamosty) [inline client/components/plans/plans-compare/index.jsx]: Riiight. :)

**Comment by lamosty** [comment]
Thanks for the review @gwwar. I updated the code according to your suggestions. Is it alright?

**Comment by gwwar** [comment]
:shipit:
