### PR TITLE
Themes: fix issue with missing title mobile viewport

### LINKED ISSUE #7008: Sidebar: Navigation header on mobile missing title for Themes
#### Steps to reproduce
1. With the browser set to a mobile screen width, navigate to https://wordpress.com/stats/insights/example.wordpress.com
2. Notice that the header says "Stats"
3. Click the back arrow and navigate to Themes
4. Notice that the header still says "Stats"

#### What I expected
The header to say "Themes", or something to that effect

#### What happened instead
The header isn't updated, and reflects the previous menu selection

#### Browser / OS version
OSX Chrome / Firefox

#### Screenshot / Video
wp-calypso-themes-nav

#### Context / Source
#manual-testing

### PR DESCRIPTION
**Pull request by timmyc**
Fixes #7008 - the themes controller currently is not calling `setTitle` which is what powers the title seen on mobile viewports - which results in the title from the previous controller or `setTitle` call being shown:

__Before__
themes_ _sketchytimmy_ _wordpress_com_and_custom_content_types_ _jetpack_for_wordpress

__After__
themes_ _wordpress_com_and_comparing_master___fix_themes_missing-title_ _automattic_wp-calypso

__To Test__
- Adjust your viewport so the mobile breakpoint comes into affect
- Click themes in the sidebar from 'My Sites', verify the correct title is shown

Test live: https://calypso.live/?branch=fix/themes/missing-title

### CODE REVIEW

**Comment by aduth** [comment]
We should avoid `screen-title/actions` if possible. The [`setDocumentHeadTitle` Redux action creator](https://github.com/Automattic/wp-calypso/blob/93392f4d3c25673145cef2ab2918c92d467b0e75/client/state/document-head/actions.js#L11-L23) should work just as well, or even the [`<DocumentHead />` component](https://github.com/Automattic/wp-calypso/tree/master/client/components/data/document-head) if you can fit it in without too much trouble (eases eventual transition to a single render tree).

**Comment by timmyc** [comment]
Tried `setDocumentHeadTitle` and got the warning ssr warning:

`PragmaChecker: ./main, dependency state/document-head/actions is not /** @ssr-ready **/`

**Comment by aduth** [comment]
Should be fine to add the pragma.

https://github.com/Automattic/wp-calypso/blob/12a27beda288923d5186807f1157f04389f54c06/docs/server-side-rendering.md#marking-your-code-as-compatible-with-server-side-rendering

**Comment by aduth** [comment]
There's a `documentHead` middleware that will cause an update to `document.title` (via the `lib/screen-title` actions currently), but is only present in the browser:

https://github.com/Automattic/wp-calypso/blob/93392f4/client/state/index.js#L84-L90

**Comment by timmyc** [comment]
@aduth - I followed through and tried using `setDocumentHeadTitle` but that doesn't seem to fix the issue.  From what I can see in [`<SidebarNavigation/>`](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/sidebar-navigation/sidebar-navigation.jsx#L20) the title attribute is being pulled from a `site` object in `lib/sites-list` - thus needing the flux action solution outlined in c24f951

**Comment by aduth** [comment]
The title is being passed via the `<TitleData />` component, which reads from the Flux store, but the Redux actions should be updating the Flux state under the hood via the middleware.

File: client/my-sites/themes/controller.jsx [hunk 1]
```diff
@@ -58,6 +59,9 @@ export function singleSite( context, next ) {
 		window.scrollTo( 0, 0 );
 	}
 
+	// Set title
+	titleActions.setTitle( i18n.translate( 'Themes', { textOnly: true } ) );
```
Comment (aduth) [inline client/my-sites/themes/controller.jsx]: You can reuse `props.title` here and below instead of calling `translate` again.

**Comment by aduth** [comment]
cc @ockham

**Comment by ockham** [comment]
Thanks for [cc'ing](http://xkcd.com/1713/).

I only had a very quick glance, but please note that we're currently using the `Head` component in a couple of places to set `title` and some `meta` tags on the server side for SEO purposes, so I hope that won't collide with what this PR does? However, if we can replace `Head` with `DocumentHead` already (even though the latter still invokes the Flux dispatcher for some side effects), I'd be more than happy!

Will take a closer look on Monday.

**Comment by ockham** [comment]
Actually, nothing really to add to what @aduth said. :-) I.e. I'd love if we could use `DocumentHead` (even if we also still keep `Head` around for the time being -- we'll be able to merge them more easily this way, and hopefully quite soon).

**Comment by timmyc** [comment]
Okay took the `<DocumentHead />` approach in 49a685a - it appears I can not fully replace `<Head />` since that is rendering the child theme elements, but the implemented fix does solve the original issue.

**Comment by ockham** [comment]
Looks good, and tests well!

:ship:

File: client/my-sites/themes/controller.jsx [hunk 2]
```diff
@@ -24,6 +30,7 @@ function makeElement( ThemesComponent, Head, store, props ) {
 			canonicalUrl={ props.canonicalUrl }
 			image={ props.image }
 			tier={ props.tier || 'all' }>
+			<DocumentHead title={ BASE_TITLE } />
```
Comment (ockham) [inline client/my-sites/themes/controller.jsx]: Oops, should've just used `props.title` here instead of the `const`. Oh well, didn't spot it when reviewing either. Will fix as part of #7224.

Comment (timmyc) [inline client/my-sites/themes/controller.jsx]: I did have it set to `props.title` initially, but in the mobile viewport things looked a bit strange with "Themes - SITENAME.wordpress.com".  Based off the patterns elsewhere in calypso ([#](https://github.com/Automattic/wp-calypso/blob/master/client/me/controller.js#L43), [#](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/stats/controller.js#L132) ) I opted for the section name - but feel free to change it up!

Comment (ockham) [inline client/my-sites/themes/controller.jsx]: Yep, you're right. I think with #7224 I'll be able to sort that out tho!
