### PR TITLE
Preview IFrame - Add fall back to opening preview in full window if iframe load fails

### LINKED ISSUE #36824: Previews: Some Jetpack site modal previews may fail with connection errors. [5]
Some Jetpack site modal previews may fail with connection errors. This doesn't seem to happen with all JP sites, and doesn't happen with simple sites.

2019-10-16_at_11 11_am

### PR DESCRIPTION
**Pull request by glendaviesnz**
#### Changes proposed in this Pull Request

If load of preview content into iframe fails due to cross origin issues, eg. if a Jetpack site is setting X-Frame-Options to same-origin at the web server level, then load preview in new tab instead

#### Testing instructions

*  Create a standard Jurassic Ninja site and connect it to your WordPress.com account.
* Activate the Hello Dolly plugin, and with the Plugin Editor, add this line to it: `add_action( 'init', 'send_frame_options_header', 99 );`
* Open View Post for the Hello World post on your local Calypso install on `master`, and see the sad browser header failure.
* Switch to this branch.
* Open the same View Post, and see the preview load in a new tab.

Before:

before-preview

After:

after-preview

Fixes #36824

### CODE REVIEW

File: client/gutenberg/editor/calypsoify-iframe.tsx [hunk 1]
```diff
@@ -114,6 +114,7 @@ class CalypsoifyIframe extends Component< Props & ConnectedProps & ProtectedForm
 	mediaSelectPort: MessagePort | null = null;
 	revisionsPort: MessagePort | null = null;
 	templatePorts: [ T.PostId, MessagePort ][] = [];
+	successfullIframeLoad = false;
```
Comment (kwight) [inline client/gutenberg/editor/calypsoify-iframe.tsx]: Minor spelling: should be `successfulIframeLoad`.

**Comment by kwight** [comment]
> To test you will need a jetpack site that is setting X-Frame-Options header on the page preview and editor pages - will try and put together some simple instructions to replicate this state tomorrow

I'm thinking we should be able to use this calypso.live branch with a JN site (both sites need to have SSL certs I believe?), and upload a plugin that calls `send_frame_options_header()` at a late point.

File: client/components/web-preview/content.jsx [hunk 2]
```diff
@@ -279,7 +286,7 @@ export class WebPreviewContent extends Component {
 							ref={ this.setIframeInstance }
 							className="web-preview__frame"
 							src="about:blank"
-							onLoad={ this.setLoaded }
+							onLoad={ this.setIframeLoaded }
```
Comment (gwwar) [inline client/components/web-preview/content.jsx]: Careful, we're not attaching `this.setLoaded`! Would recommend not attaching directly and have this as part of the error case for `setLoaded`

Comment (glendaviesnz) [reply client/components/web-preview/content.jsx]: yeh, thanks for the reminder, this was a temporary change to verify the approach worked, lots of stuff happening in this.setLoaded - but there is a bit of a chicken & egg thing going on between that, which is also triggered by the iframe child messaging, and the iframe onload event, so I need to spend a bit of time working out how to handle this without introducing unexpected race conditions, etc.

**Comment by kwight** [comment]
I've updated the description to include testing instructions. We were overthinking the SSL aspect; it's only necessary that the iframed content is SSL, not the parent – so a JN site iframed by a local Calypso dev environment works for our needs. For the headers, adding one line to the existing Hello Dolly plugin gives us what we need.

**Comment by kwight** [comment]
Hm, interesting. With my little Hello Dolly hack, I can't get this to fail – the preview always loads successfully, and the check in `setIframeLoaded` doesn't fail (but I definitely get sad browser when trying to edit by Gutenframe).

**Comment by kwight** [comment]
> With my little Hello Dolly hack, I can't get this to fail

Ah, I had it hooked to `admin_init`, instead of `init` to affect front-end loads (instructions are updated).

Great work @glendaviesnz – I can turn this solution on and off by switching between `master` and this branch now. If I understand correctly, this POC now needs to be worked into the existing `setLoaded`?

**Comment by kwight** [comment]
One thing to note is that at least Chrome won't allow the new tab to open right away, we need to allow popups in the toolbar first (not sure what causes the popup?).

File: client/components/web-preview/content.jsx (hunk 2 above)
Comment (glendaviesnz) [reply client/components/web-preview/content.jsx]: I have merged the iFrame loaded check back into setLoaded now. I just need to try and work out how to best test each of the branches in setLoaded to make sure my additional logic hasn't broken something.

**Comment by glendaviesnz** [comment]
> One thing to note is that at least Chrome won't allow the new tab to open right away

It isn't blocking for me, but maybe I enabled it for the site in earlier testing - will investigate.

**Comment by glendaviesnz** [comment]
> If I understand correctly, this POC now needs to be worked into the existing `setLoaded`?

Yep, correctly understood, and it is worked back into setLoaded now - just working now on how we can best test all the preview cases.

**Comment by gwwar** [comment]
Another option would be adding the external links directly from the post-list/ We might need to have one bad case initially or subpar behavior, until we can set some state.

Screen Shot 2019-10-23 at 5 13 53 PM

Might be a clue on what is previewable/not https://github.com/Automattic/wp-calypso/blob/4e90aaea27f94203aefde6907fc94250f38e154f/client/my-sites/post-type-list/post-actions-ellipsis-menu/view.jsx#L45

https://github.com/Automattic/wp-calypso/blob/4e90aaea27f94203aefde6907fc94250f38e154f/client/state/sites/selectors/is-site-previewable.js

Since we have the concept of a previewable/not-previewable site, it might be worth exploring if we should expand logic in https://github.com/Automattic/wp-calypso/blob/4e90aaea27f94203aefde6907fc94250f38e154f/client/state/sites/selectors/is-site-previewable.js to account for potential failures. Say a user adds new X-Frame options/configuration settings outside of WordPress. 

We don't have a way to detect this on the site object, but we can at least try to gracefully fallback to a better user experience. For example the https://martinfowler.com/bliki/CircuitBreaker.html pattern might be a good fit here, when we detect a bad preview, we go into the closed state and always display external links, until we meet some condition (like waiting a few days) and test to see if the previews work on the next user preview interaction. This might be overkill, but may be interesting to investigate in a timebox.

**Comment by glendaviesnz** [comment]
Have updated the PR to handle both the page preview and the site preview - for site preview it should now redirect to the site in the same window rather than opening a new window, in the same way as when ! isPreviewable 

I did play around with saving disabled preview to state if a preview fails, but didn't have time to get it finalised (and not 100% sure if I have the state stuff set up properly), so didn't push to this PR in case we want to merge this simple fix first and follow up with the more complex option. 

The state change option is on this branch if someone wants to have a play and refine it some more https://github.com/Automattic/wp-calypso/compare/fix/iframe-load-failure-save-preview-state. One issue I noticed is that for the site preview on that branch is you can end up in a bit of a redirect loop if you click back button after being redirected to site.

**Comment by gwwar** [comment]
As a minor side note, in your `fix/iframe-load-failure-save-preview-state` branch, it's not necessary to wrap the new reducer in `withoutPersistence`. The custom `combineReducers` in `state/utils` does this for us. (Persistence is opt-in).

**Comment by gwwar** [comment]
@glendaviesnz maybe try rebasing to see if the test errors clear up. Some of the failures look unrelated `Timed out waiting for element with css selector of '.editor-simple-payments-modal__form #title' to be clearable`.

Do you need folks to take another 👀 at changes here before 🚢 it?

**Comment by glendaviesnz** [comment]
> Do you need folks to take another 👀 at changes here before 🚢 it?

It is just back to exactly the same code that was reviewed before the broken rebase so I don't think it needs another review. Just trying to double check on IE11 first as it apparently handles iframe onload differently.

**Comment by glendaviesnz** [comment]
Added in a check for 'about:blank' as the preview url which prevents the preview from failing in the editor context - we don't need to worry about checking in this context because https://github.com/Automattic/wp-calypso/pull/36977 will cause an sites blocked due to cross origin to redirect to wp-admin for block editor
