### PR TITLE
Gutenlypso: Keep changes when opting-out

### LINKED ISSUE #29216: Gutenberg in Calypso: switching back to classic Calypso editor doesn't show changes
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/post/ using classic editor
2. Enter title and text and save draft
3. Switch to new editor within Calypso
4. Draft displayed
5. Make some updates
6. Switch back to classic editor

#### What I expected

Changes displayed immediately in classic editor - like it does when using wp-admin

#### What happened instead

Old contents displayed due to no page refresh

#### Browser / OS version

Chrome 70 on macOS

#### Screenshot / Video

Calypso Gutenberg ❌ 

classic editor and calypso

Calypsofy wp-admin ✅ 

classic editor and wp-admin

### PR DESCRIPTION
**Pull request by Copons**
#### Changes proposed in this Pull Request

* Prevent losing changes when opting-out of Gutenberg.

This PR uses two different logics for technical reasons:
- Opting out via the Gutenberg's More menu: checks if the editor is dirty, and triggers a save/autosave as needed before redirecting.
- Opting out via the Inline Help: this doesn't necessarily have access to the Gutenberg store, so instead of creating a complicated infrastructure, I chose to simply show a confirm alert implicitly prompting to save before opting out.

#### Testing instructions

* Open Gutenberg at `/block-editor`.
* Make some changes to the post.
* Open the More menu (ellipsis icon in the top-right corner), and click on Switch to Classic Editor.
* You can observe that a save or autosave call appears in the brower's dev tools Network tab.
* The changes show up correctly in the Classic editor (it will likely ask to restore a newer version of the post).
* Opt back in to Gutenberg.
* Open the Inline Help (question mark icon in the bottom-right corner), and click on Switch to Classic Editor.
* Make sure an "Are you sure?" confirm dialog interrupts the opt-out flow.

Fixes #29216

### CODE REVIEW

**Comment by kwight** [comment]
I saw a correct `POST` operation on clicking the menu item, but that post didn't load when the Calypso editor came up. I tested by opening `/block-editor/post/:site`, then adding a title, and clicked the menu item before any autosave happened.

The second part, I got the "Are you sure?" alert properly (but no dirty content on reload, as expected).

**Comment by Copons** [comment]
Thanks for the review @kwight.
I think I accidentally reverted some changes yesterday when I was cleaning this up before the push.

Basically, the autosave works fine, but the opt-out redirects before the new editor route obtains the post ID, and so, instead of landing on `/post/:site/:draftId` that would contain the changes, lands on `/post/:site` which of course doesn't contain anything at all.

In 52ff22a I've changed how we build the `classicEditorRoute` so that, if the post `isDraft && isDirty`, it also adds the postId (which is generated behind the scenes immediately when opening `/block-editor/post/:site`).

File: client/blocks/inline-help/popover.jsx [hunk 1]
```diff
@@ -119,13 +120,23 @@ class InlineHelpPopover extends Component {
...
 
 	switchToClassicEditor = () => {
-		const { siteId, optOut, classicUrl } = this.props;
-		optOut( siteId, classicUrl );
+		const { siteId, onClose, optOut, classicUrl } = this.props;
+
+		const proceed =
+			typeof window !== 'undefined'
+				? window.confirm( __( 'Are you sure you wish to leave this page?' ) )
+				: true;
```
Comment (dmsnell) [inline client/blocks/inline-help/popover.jsx]: nice ternary, but in this case we can also use a simpler form…

```js
const proceed = typeof window === 'undefined' || window.confirm( … );
```

just noting because the ternary is maybe more complexity than we need to debug here 😉
