### PR TITLE
Return availability message for empty domain suggestions result set.

### LINKED ISSUE #26682: Domains: Missing suggestions & error message for some domain names
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains/add/<yourwebsite> (My Site -> Domain -> Add)
2. Enter `wordpress-ninja.com`, or one of the shorter failing domains mentioned below
3. Notice that there is no error message, and no suggestions. You may notice that the trademark error message flashes for a moment before disappearing.
4. Contrast with minor variations, like `wwordpress-ninja.com` or `wordpress-ninjaa.com` that show both error message and suggestions

#### Browser / OS version
Chrome/OSX

#### Screenshot / Video

domain_search_ _site_title_ _wordpress_com

cursor_and_domain_search_ _site_title_ _wordpress_com

#### Context / Source

I think this is about the hyphen somehow fouling up the suggestions. I've fiddled about a bit trying to get simpler failure cases, and I was able to find `ninja-`/`-ninja`, `-co`/`co-`, and `ass-`/`-ass`

Notably, `ninja-.com` & `ninja-.co` fail, but `ninja-.c` works. Also, `n-`, `ni-`, `nin-` and `ninj-` all work fine, `ninja-` and `ninjas-` both fail, but `ninjaa-` is ok.

When the message and suggestions disappear, we get an error back from the `suggestions` endpoint: `{"code":400,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"empty_results","message":"No available domains for that search."}}`

I think we're filtering out the trademarked term and the tld, and then if we're left with a hypen at the beginning or end, some words will cause an error in our suggestions code.

### PR DESCRIPTION
**Pull request by delputnam**
#### Changes proposed in this Pull Request

* Currently, we don't show a notice when a domain name search generates an empty result set. This PR adds an error notice for this situation.

#### Testing instructions
* Try searching for a domain with a blacklisted string.
* Make sure the correct notice is shown.

* Hack the back end suggestions endpoint so that it returns an error with `empty_results`.
* Try searching for a domain without a blacklisted string.
* Make sure that the empty notice is shown.

* Try searching for a domain with a blacklisted string.
* Make sure that both notices are shown.

Fixes #26682

### CODE REVIEW

File: client/lib/domains/registration/availability-messages.js [hunk 1]
```diff
@@ -198,11 +198,16 @@ function getAvailabilityNotice( domain, error, errorData ) {
...
 		case domainAvailability.TLD_NOT_SUPPORTED_TEMPORARILY:
 		case domainAvailability.UNKNOWN:
-		case domainAvailability.EMPTY_RESULTS:
 			// unavailable domains are displayed in the search results, not as a notice OR
 			// domain registrations are closed, in which case it is handled in parent
 			break;
 
+		case domainAvailability.EMPTY_RESULTS:
+			message = translate(
+				"Sorry, we weren't able to generate any domain name suggestions for that serach term. Please try a different set of keywords."
```
Comment (aidvu) [inline client/lib/domains/registration/availability-messages.js]: `serach` 😛

File: client/lib/domains/registration/availability-messages.js [hunk 2]
```diff
@@ -198,11 +198,16 @@ function getAvailabilityNotice( domain, error, errorData ) {
 		case domainAvailability.TLD_NOT_SUPPORTED:
 		case domainAvailability.TLD_NOT_SUPPORTED_TEMPORARILY:
 		case domainAvailability.UNKNOWN:
-		case domainAvailability.EMPTY_RESULTS:
```
Comment (aidvu) [inline client/lib/domains/registration/availability-messages.js]: Hmm, we should probably test all the possible cases. Don't recall why this was here.

Comment (delputnam) [reply client/lib/domains/registration/availability-messages.js]: At this point, I believe that the only reason we would get empty results is because the query we send to the suggestion engine is empty or invalid after sanitization.

Comment (aidvu) [reply client/lib/domains/registration/availability-messages.js]: I recall now. If both the availability and the suggestions return an error, they quickly switch between the two. :) So we will show the trademark first for availability, then switch to `EMPTY_RESULTS`. Bah, I hate these cases where we handle two data sources and handle them as one.

Comment (aidvu) [reply client/lib/domains/registration/availability-messages.js]: Example:

- Force the suggestion endpoint to return the empty results error
- Incognito window
- /start/domain
- Search for wordpress-ninja.com
- See what happens.

**Comment by klimeryk** [comment]
According to the PR's description, I should see two notices if I search for something that has a blacklisted string _and_ yields no results. However, I'm only seeing one notice:
screen shot 2018-10-25 at 17 56 43

(did not even have to hack the backend to get this error)

Same in Domain Management. It's a normal, test user. Is there something I'm missing?
