### PR TITLE
Fix action buttons in conversations tab

### LINKED ISSUE #78677: Reader: In the Conversations sections, clicking on "Read more" or "Reply" to a comment, opens the post instead.
### Quick summary

Using the reader, in the conversations section, when clicking the Reply button to reply to a comment, it opens the post instead of showing a reply box as it used to. 
If there is a long comment, only the beginning is shown with the text "Read more" link that should expand the text, but instead the post is opened. If you go back to the post, you can see that the text expanded after the fact.

### Steps to reproduce

1. Open the reader.
2. Follow a conversation with long replies to other comments.
3. Go to the Conversations section.
4. Find the conversation with the shortened comments with the link "Read more"
5. Click on "Read More", or click to "Reply".

### What you expected to happen

When clicking "Read more" the comment should expand so you can read the entire comment.
When clicking "Reply" a comment box should appear allowing you to directly reply to the comment from there.

### What actually happened

In both cases, the whole post opens in the reader. 
You would then have to find the comment again so you can read it or reply to it, which can be hard when there are a lot of comments.

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Reported in 6460487-zen

When you click anywhere in the text of a comment, the post opens which seems related to this behavior.
If you highlight a text from a comment, you can click the Reply or Read More button, and the expected behavior occurs.

https://github.com/Automattic/wp-calypso/assets/46269032/008a1fc0-b5ab-4a46-b869-663a5534cf40

### PR DESCRIPTION
**Pull request by roo2**
Fixes https://github.com/Automattic/wp-calypso/issues/78677

The [handleCardClick](https://github.com/Automattic/wp-calypso/blob/trunk/client/blocks/reader-post-card/index.jsx#L63) event handler on the card was overwriting the button click events, this change prevents that.

### Testing instructions
Screen Shot 2023-08-15 at 2 37 08 pm

On the `/conversations` page, test the action buttons
* Read More
* Reply
* Cancel Reply
* Reblog
* Like/Unlike

### CODE REVIEW

**Review by Addison-Stavlo — APPROVED** [review]
Works as advertised!

nit pick - One thought is should we add the preventDefault functionality to the original functions themselves? I always feel slightly weird passing anonymous functions into other components as props since they will always look like new values on rerenders, but probably not a big deal here.

Discussion outside this PR and just looking closer at conversations - it feels weird that clicking anywhere around the comments fires the card click fn that opens the post. Mis-clicking just outside of "cancel reply" for example opens the post. I wonder if we should leave the card click to the top post section of the card itself and not in the conversation section. Thoughts?

**Comment by roo2** [comment]
Good idea @Addison-Stavlo I changed this to a simpler fix that filters out the whole comment section

File: client/blocks/reader-post-card/index.jsx [hunk 1]
```diff
@@ -88,6 +88,11 @@ class ReaderPostCard extends Component {
 			return;
 		}
 
+		// ignore clicks on comments
+		if ( closest( event.target, '.conversations__comment-list', rootNode ) ) {
+			return;
+		}
```
Comment (Addison-Stavlo) [inline client/blocks/reader-post-card/index.jsx:94]: Oh very nice! Il have to adopt this type of approach for the inline-comments as well.

**Review by Addison-Stavlo — APPROVED** [review]
Works great, nice approach and im liking that the comments section doesn't trigger the post card click event at all!

**Review by davemart-in — APPROVED** [review]
LGTM!
