### PR TITLE
WooExpress: Added custom copy in plugins page for trial plan

### LINKED ISSUE #73430: Task: improve UX in WPCOM Marketplace for users on the eCommerce trial
### Details

As a result of us landing Automattic/wpcomsh#1252 and D101197-code, users with free trial sites are now seeing incorrect nudges and flows to upgrade.

We need to update the UX to at least show a correct message and update the CTA so the flow adds the correct plan to the cart.

Designs: oRIYBgxHeLDtlVrTjINlxf-fi-1090%3A45803&t=tw2LTpEeBwGwWucV-0

### Checklist

- [ ] Users should see an appropriate banner message in the WPCOM Marketplace UI (`/plugins/:siteSlug`)
- [ ] The CTA for the banner should drop us into checkout with the eCommerce monthly plan

### Related

_No response_

### PR DESCRIPTION
**Pull request by nelsonec87**
Closes https://github.com/Automattic/wp-calypso/issues/73430

## Proposed Changes

* Changed Upgrade nudge copy for eCommerce trial plan sites
* Changed the cta to add the eCommerce plan to the cart.

## Testing Instructions

* Open the plugins page (`/plugins/<site-slug>`) of a trial site
* Check the banner copy
* Click on the CTA and confirm it adds the eCommerce monthly plan to the cart.

Before:

image

After:

image

### CODE REVIEW

File: client/my-sites/plugins/plugins-discovery-page/upgrade-nudge.jsx [hunk 1]
```diff
@@ -26,6 +28,7 @@ import { getSelectedSite } from 'calypso/state/ui/selectors';
 const UpgradeNudge = ( { siteSlug, paidPlugins } ) => {
 	const selectedSite = useSelector( getSelectedSite );
 	const sitePlan = useSelector( ( state ) => getSitePlan( state, selectedSite?.ID ) );
+	const isEcommerceTrial = sitePlan?.product_slug === PLAN_ECOMMERCE_TRIAL_MONTHLY;
```
Comment (daledupreez) [inline client/my-sites/plugins/plugins-discovery-page/upgrade-nudge.jsx:31]: Nit: it would probably be good to implement an `isEcommerceTrial()` helper function in `calypso-products`, but that doesn't block this PR, as it was already missing.

File: client/my-sites/plugins/plugins-discovery-page/upgrade-nudge.jsx [hunk 2]
```diff
@@ -114,6 +117,22 @@ const UpgradeNudge = ( { siteSlug, paidPlugins } ) => {
...
+		return (
+			<UpsellNudge
+				event="calypso_plugins_browser_upgrade_nudge"
+				className="plugins-discovery-page__upsell"
+				callToAction={ translate( 'Upgrade now' ) }
+				icon="notice-outline"
+				showIcon={ true }
+				href={ `/checkout/${ siteSlug }/${ PLAN_ECOMMERCE_MONTHLY }` }
+				feature={ FEATURE_INSTALL_PLUGINS }
+				plan={ plan }
```
Comment (daledupreez) [inline client/my-sites/plugins/plugins-discovery-page/upgrade-nudge.jsx]: Is this the eCommerce plan? If not, I think we should fix it so the nudge and it's tracking logic isn't disrupted.

**Review by daledupreez — COMMENTED** [review]
Overall, this is working as described, but I am concerned about the `plan` argument not being the value expect, so I think we should fix that.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7827201

Thank you @nelsonec87 for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7827201).
