### PR TITLE
Gutenberg: Disable NUX tour tooltips

### LINKED ISSUE #32472: Gutenberg: Turn off core Welcome Tips [1]
Currently the Tips ("Welcome to the wonderful world of blocks!") shows up every time I visit the block editor on a new site.

Related: https://github.com/WordPress/gutenberg/issues/15105, but there's no reason we can't fix it on WPCOM in the meantime.

#### Steps to reproduce
1. Go to a site you haven't used Gutenberg on before and add or edit a post.
2. Switch to the block editor if necessary / prompted.
3. Note that this tip appears, no matter how many times you've seen it in the past:
  
Screen Shot 2019-04-22 at 9 36 25 AM

#### What I expected

1. This should show up once per user, not per site or per browser cache.

#### What happened instead

1. It is stored in localStorage on a per-site basis so it shows up repeatedly if you have multiple sites or if you clear your browser cache.

For now let's turn off these welcome tips for everyone on WordPress.com

#### Browser / OS version

OSX/Firefox

#### Context / Source

#dogfooding a12s discussed this in Slack.

### PR DESCRIPTION
**Pull request by codebykat**
#### Changes proposed in this Pull Request

Disable "Welcome to the Wonderful World of Blocks!" tooltip / guided tour.

#### Testing instructions

* Visit the block editor on a new site (one on which you have not previously opened it) or on a browser after clearing localStorage cache
* The "Welcome to the Wonderful World of Blocks!" tooltip should not appear
* Will fix #32472 

Please see: PCYsg-l4k-p2 for additional testing steps

### CODE REVIEW

**Comment by codebykat** [comment]
I thought this wasn't working, but after some investigation, I now think I may not know how to build/test it :/ TBD

Alternatives as I understand them are:
1. make it a full component with `withDispatch` as in https://github.com/WordPress/gutenberg/blob/5c34f2fe327035784c1728572c9d281c9cb53147/packages/edit-post/src/components/options-modal/options/enable-tips.js
2. make this a script instead of a component, like switch-to-classic.js, and use `window.wp.data.dispatch( 'core/nux' ).disableTips()` and make this a script instead of a component

File: apps/wpcom-block-editor/src/common/disable-nux-tour.js [hunk 1]
```diff
@@ -0,0 +1,6 @@
+/**
+ * External dependencies
+ */
+import { dispatch } from '@wordpress/data';
+
+dispatch( 'core/nux' ).disableTips();
```
Comment (gwwar) [inline apps/wpcom-block-editor/src/common/disable-nux-tour.js]: We'll likely run into timing issues here if we call this on script load.

Comment (gwwar) [reply apps/wpcom-block-editor/src/common/disable-nux-tour.js]: @youknowriad  @aduth @ellatrix 

We're trying to disable tips on editor load. Is the above okay, or do we need to guard against the store loaded check with something like:

```js
import { select, subscribe, dispatch } from '@wordpress/data';

const unsubscribe = subscribe( () => {
	const nuxInitialized = select( 'core/nux' ) !== undefined;
	if ( ! nuxInitialized ) {
		return;
	}
	unsubscribe();
	dispatch( 'core/nux' ).disableTips();
} );
```

**Comment by gwwar** [comment]
Overall I think this was working for me while sandboxed Kat! Let's see what folks answer in https://github.com/Automattic/wp-calypso/pull/33223#discussion_r286652043 before shipping, but this looks pretty close!

File: apps/wpcom-block-editor/src/common/disable-nux-tour.js (hunk 1 above)
Comment (aduth) [reply apps/wpcom-block-editor/src/common/disable-nux-tour.js]: If possible, you should define a dependency on the `@wordpress/nux` module. Doing so should ensure the store is registered.

This is how it's done in the editor:

https://github.com/WordPress/gutenberg/blob/f1bbc004734ea157dd72ed5bf1f808c10efc0e84/packages/editor/src/index.js#L8

The NUX store is registered as a side effect of the module load:

https://github.com/WordPress/gutenberg/blob/f1bbc004734ea157dd72ed5bf1f808c10efc0e84/packages/nux/src/index.js#L4
https://github.com/WordPress/gutenberg/blob/f1bbc004734ea157dd72ed5bf1f808c10efc0e84/packages/nux/src/store/index.js#L13

Comment (gwwar) [reply apps/wpcom-block-editor/src/common/disable-nux-tour.js]: Ah so it'd look like:

```jsx
import { dispatch } from '@wordpress/data';
import '@wordpress/nux'; //ensure nux store loads

dispatch( 'core/nux' ).disableTips();
```

Did we previously run into trouble with store loading/versioning @mmtr @jsnajdr ?

Comment (gwwar) [reply apps/wpcom-block-editor/src/common/disable-nux-tour.js]: I guess to add to that @aduth assuming we don't accidentally pull in multiple versions of the nux package, is it safe to import the nux package more than once in different files?

**Comment by codebykat** [comment]
Updated with nux import -- but I had to bypass the linter because I got:

`5:1  error  '@wordpress/nux' should be listed in the project's dependencies. Run 'npm i -S @wordpress/nux' to add it  import/no-extraneous-dependencies`

Even after running the suggested command, which also generated a lot of (unrelated?) changes to shrinkwrap, which I'm not sure if I should check in. :/

File: apps/wpcom-block-editor/src/common/disable-nux-tour.js (hunk 1 above)
Comment (mmtr) [reply apps/wpcom-block-editor/src/common/disable-nux-tour.js]: Good point @gwwar. I think `registerStore` should check the name is not used by other store. Maybe it's already doing that, but I'd try to avoid multiple imports just in case. If we ever need this import in another file, we should move it to a file that is higher in the hierarchy (like `common/index.js`)

Comment (mmtr) [reply apps/wpcom-block-editor/src/common/disable-nux-tour.js]: Anyway, since this package is intended to be loaded in a WordPress environment, we generate the builds with `@automattic/calypso-build` and the [`--env.WP` option](https://github.com/Automattic/wp-calypso/blob/12e94e5f7e30a7871fdce0f2c9eff689e339c440/apps/wpcom-block-editor/package.json#L19) that externalizes all the `@wordpress/<package-name>` dependencies.

So when we create the WP.com patch that updates the build, we need to make sure to add the `wp-nux` dependency when enqueuing the script (see `gutenberg-wpcom/index.php#L69`).

**Comment by codebykat** [comment]
WPCOM diff: D28629-code

**Comment by codebykat** [comment]
I was able to build and test this on my sandbox and it is working for me! My reading of the comments above is that adding a guard is seemingly not necessary, so unless someone contradicts that I think we're good to go.

File: apps/wpcom-block-editor/src/common/disable-nux-tour.js (hunk 1 above)
Comment (aduth) [reply apps/wpcom-block-editor/src/common/disable-nux-tour.js]: > I guess to add to that @aduth assuming we don't accidentally pull in multiple versions of the nux package, is it safe to import the nux package more than once in different files?

I think it should be fine. Ultimately it depends on the guarantees offered by the build tool. Unsure if factors like [scope hoisting](https://medium.com/webpack/brief-introduction-to-scope-hoisting-in-webpack-8435084c171f) come in to play. I expect Webpack tries to ensure the code is only run once.

While it doesn't help your immediate need, there's some early efforts to expose the underlying store configurations for some (but not all, including NUX) stores ([example](https://github.com/WordPress/gutenberg/blob/514e61298d5c056ef6ec4d3859b959dc46735dec/packages/block-editor/src/store/index.js#L20-L25)). I don't think there'd be an objection to just applying this pattern for all stores, and sooner than later.

File: apps/wpcom-block-editor/src/common/disable-nux-tour.js [hunk 2]
```diff
@@ -0,0 +1,7 @@
+/**
+ * External dependencies
+ */
+import { dispatch } from '@wordpress/data';
+import '@wordpress/nux'; //ensure nux store loads
+
+dispatch( 'core/nux' ).disableTips();
```
Comment (kwight) [inline apps/wpcom-block-editor/src/common/disable-nux-tour.js]: Do we want to disable all tips (as we're doing here), or just mark the "wonderful world of blocks" tip as dismissed?

Comment (kwight) [reply apps/wpcom-block-editor/src/common/disable-nux-tour.js]: If we do want the former, should we also remove the ellipsis menu > Options > Enable Tooltips option, since it's odd to be able to go in and enable it, then have the next page load remove it again with no explanation.

Screen Shot 2019-05-23 at 12 32 23 PM

Comment (gwwar) [reply apps/wpcom-block-editor/src/common/disable-nux-tour.js]: I think it's okay to leave this for now. Clicking on Enable Tips will re-display tips on the current load. If it's confusing we can remove it in a follow up.

Comment (codebykat) [reply apps/wpcom-block-editor/src/common/disable-nux-tour.js]: Yeah I left it re-enable-able on purpose... in case someone wants to go through the tour manually, they can do that. It won't persist but I think that's okay.
