### PR TITLE
Signup: Domains: Prefill domain mapping with the last searched domain

### LINKED ISSUE #2442: Domain Mapping: automatically fill if coming from a search for an existing domain
Raised by @fabianapsimoes 

Steps to reproduce:

- Visit `/start/domain` and enter an existing domain
- Click the Map it button (not the link in the yellow banner)
- The Domain Mapping page will open with an empty field.

I understand that, ideally, users would use the Map It link instead of the button. But for those who missed it, it'd be easier if after searching for an existing domain the Domain Mapping field was pre-filled with that domain.

### PR DESCRIPTION
**Pull request by klimeryk**
Pre-fill the domain mapping input field with the last searched domain.
This should be tested in both the signup flow and in an already existing site, on the Domains page.

Fixes #2442

/cc @aidvu @umurkontaci

### CODE REVIEW

File: client/my-sites/upgrades/index.js [hunk 1]
```diff
@@ -193,7 +193,7 @@ module.exports = function() {
 			upgradesController.googleAppsWithRegistration
 		);
 
-		page( '/domains/add/mapping/:domain',
+		page( '/domains/add/mapping/:initial_query?/:domain',
```
Comment (umurkontaci) [inline client/my-sites/upgrades/index.js]: I think using querystring is a better fit than changing the route.

File: client/components/domains/map-domain-step/index.jsx [hunk 2]
```diff
@@ -20,16 +20,17 @@ var MapDomainStep = React.createClass( {
 
 	propTypes: {
 		products: React.PropTypes.object.isRequired,
+		initialQuery: React.PropTypes.string,
 		analyticsSection: React.PropTypes.string.isRequired
 	},
 
 	getInitialState: function() {
-		return { searchQuery: '' };
+		return { searchQuery: this.props.initialQuery };
```
Comment (umurkontaci) [inline client/components/domains/map-domain-step/index.jsx]: What do you think of removing the `searchQuery` state completely and using a query prop that is coming from the URL? When a change happens, you change the URL and the changes propagate downwards.

There's a similar example in https://github.com/Automattic/wp-calypso/blob/master/client/devdocs/main.jsx .

File: client/components/domains/map-domain-step/index.jsx [hunk 3]
```diff
@@ -20,16 +20,17 @@ var MapDomainStep = React.createClass( {
...
 	},
 
 	componentWillMount: function() {
 		if ( this.props.initialState ) {
-			this.setState( this.props.initialState );
+			this.setState( Object.assign( {}, this.props.initialState, this.getInitialState() ) );
```
Comment (umurkontaci) [inline client/components/domains/map-domain-step/index.jsx]: This seems... backwards.

Why do we have to get an `initialState` from the props and then set that to the state itself using `setState`?

I know that you didn't started it but I'd love to get rid of it. If it's easy.

File: client/components/domains/register-domain-step/index.jsx [hunk 4]
```diff
@@ -384,14 +384,17 @@ var RegisterDomainStep = React.createClass( {
 	},
 
 	goToMapDomainStep: function( event ) {
-		event.preventDefault();
+		const query = this.state.lastQuery.trim();
+		let mapDomainPath = `${this.props.basePath}/mapping`;
```
Comment (umurkontaci) [inline client/components/domains/register-domain-step/index.jsx]: Again, using the querystring can simplify this piece below.

**Comment by umurkontaci** [comment]
Couple of things I've noticed, none of these these are regressions, but if they're easy to fix, we might as well fix them in this PR or create new issues to track them if you like.

1. The `map it` link inside the notice has no underline, and consequently very hard to distinguish given the small size of the font and the small difference in the font-weight.
2. Once you click `Map It`, the field does not autofocus.

Works as advertised. :+1:

File: client/my-sites/upgrades/index.js (hunk 1 above)
Comment (stephanethomas) [inline client/my-sites/upgrades/index.js]: By the way url placeholders should be camel cased (i.e. `:initalQuery`).

File: client/components/domains/map-domain-step/index.jsx (hunk 3 above)
Comment (klimeryk) [inline client/components/domains/map-domain-step/index.jsx]: That's how the previously saved flow in signup is handled - I scratched my head around this too, but it's too big to fix here :/

File: client/components/domains/map-domain-step/index.jsx (hunk 2 above)
Comment (klimeryk) [inline client/components/domains/map-domain-step/index.jsx]: I really like the idea! Seems like the proper React way to handle this case.
Unfortunately, the way signup is written now, the state is saved [when the component is unmounted](https://github.com/Automattic/wp-calypso/blob/fix/autofill-domain-mapping/client/components/domains/map-domain-step/index.jsx#L47-L51) (and restored when needed later). This makes it necessary to keep the search query in state either way :/ We could still do it your way - but it would make it ambiguous where the query should be (in state or props) and would add additional complexity.

File: client/my-sites/upgrades/index.js (hunk 1 above)
Comment (klimeryk) [inline client/my-sites/upgrades/index.js]: Thanks for the info, @stephanethomas, for some reason I thought it was snake_case. I'll keep it in mind in the future :+1:

File: client/components/domains/map-domain-step/index.jsx (hunk 2 above)
Comment (umurkontaci) [inline client/components/domains/map-domain-step/index.jsx]: Do you know when and where we need to restore the state?

**Comment by klimeryk** [comment]
Thanks @umurkontaci for the idea about querystring! :+1: You're absolutely right, that's definitely the proper way to do it, I don't know why I hadn't thought of it :blush: 

> The map it link inside the notice has no underline, and consequently very hard to distinguish given the small size of the font and the small difference in the font-weight.

Chrome:
screen shot 2016-03-25 at 03 01 22
Safari:
screen shot 2016-03-25 at 03 08 11

Looking at the CSS styles, I'm actually not sure why it _has_ an underline on Chrome :laughing: @breezyskies, could you please shed some light on which version is the correct one - the one with the underline or without? And what do you think about @umurkontaci's suggestion about adding the underline if it's not there now? Or maybe we should put the "map it" link as [a notice action](https://wpcalypso.wordpress.com/devdocs/design/notices)? (see the second to last example, the one with `Update`)

> Once you click Map It, the field does not autofocus.

Good suggestion, fixed :+1:

File: client/components/domains/map-domain-step/index.jsx (hunk 2 above)
Comment (klimeryk) [inline client/components/domains/map-domain-step/index.jsx]: Your guess is as good as mine :) I don't want to assume anything, so maybe @fabianapsimoes could shed some light here.
Can you tell us why it's needed to store the state (in stores) of the steps during signup? Is it just for navigating forward <=> backward (and, of course, submitting in the end) or is it something else?

**Comment by umurkontaci** [comment]
> Or maybe we should put the "map it" link as a notice action? (see the second to last example, the one with Update)

:+1:

**Comment by breezyskies** [comment]
> Looking at the CSS styles, I'm actually not sure why it has an underline on Chrome :laughing: @breezyskies, could you please shed some light on which version is the correct one - the one with the underline or without? 

The underline is correct, to make it clear that it's a link.

>  Or maybe we should put the "map it" link as a notice action?

I wouldn't do this. The last change we made to this was to have the option available but tone it down due to reports that users were mapping domains they didn't really own. It's a lot more likely the domain is just taken by someone else than that the user owns it and can map it.

**Comment by klimeryk** [comment]
Thank you, @breezyskies, for the comment. I've investigated the issue further and filled [a new issue](4321) for this, as it seems there's a hack involved I'm not qualified enough in CSS to touch ;)

@umurkontaci, please look at this again - but please keep the issues and comments to the ones related to the changes in this PR. The signup code has been written the way it was, for better or for worse, I'm not the one to judge, I have no idea what were the use cases that had to be handled. So if you have issues or comments regarding its design, it's best to address them in another issue or on Slack :) I'm really grateful for your comments, I just don't want to derail this PR further :)

File: client/components/domains/map-domain-step/index.jsx (hunk 2 above)
Comment (scruffian) [inline client/components/domains/map-domain-step/index.jsx]: We also store data in the state so that the signup can be resumed from local storage.

**Comment by umurkontaci** [comment]
> @umurkontaci, please look at this again - but please keep the issues and comments to the ones related to the changes in this PR. The signup code has been written the way it was, for better or for worse, I'm not the one to judge, I have no idea what were the use cases that had to be handled. So if you have issues or comments regarding its design, it's best to address them in another issue or on Slack :) I'm really grateful for your comments, I just don't want to derail this PR further :)

Do you think this PR got derailed? I only had one comment that was out of scope and asked whether it was easy to fix.

My only concern was the approach here, but that was also limited by the state saving feature of signup flow. So, no further objections. :shipit:

**Comment by klimeryk** [comment]
Sorry if that sounded harsh - that was not my intention :) You are right - there was only that one comment, I just didn't think it was the right place to discuss it. I had looked through other signup code to trace the reason for `initialState` and noticed it was a common pattern so I acknowledged it as-is.
Anyway, as usual, thanks for the review and comments! :bow:
