### PR TITLE
Site Settings: refactor and update support links

### LINKED ISSUE #59977: Update Doc Links on Settings > Writing
### Quick summary

There are several "Learn more" links under Settings > Writing on both simple and atomic sites. It would be more helpful to link to the WordPress.com doc because this contains information specific to a .com website.

### Steps to reproduce

1. Go to Settings > Writing 
2. Click the (i) icon next to the various settings
3. Note that most of the Learn more links lead to a doc on Jetpack.com

image

### What you expected to happen

I expected to be taken to a WordPress.com help resource. Here are the relevant WordPress.com doc links:

* LaTeX markup language: https://wordpress.com/support/latex/
* Shortcodes: https://wordpress.com/support/shortcodes/
* Testimonials: https://wordpress.com/support/testimonials/
* Portfolios: https://wordpress.com/support/portfolios
* Infinite Scroll: https://wordpress.com/support/infinite-scroll/ (atomic only)
* Custom CSS panel: https://wordpress.com/support/custom-css/
* Widget visibility: https://wordpress.com/support/widgets/#widget-visibility
* Post by email: https://wordpress.com/support/post-by-email

"Privacy information" does not seem relevant to .com sites, but we can check on that.

### What actually happened

I arrived at a Jetpack doc for self-hosted sites.

### Context

_No response_

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

_No response_

### Browser, operating system and other notes

_No response_

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by arcangelini**
## Changes proposed in this Pull Request
This started out as a simple PR to update the links to the support guide links and during the process, I decided to refactor a few things and make it a little cleaner and more uniform. Here are the major changes I made:
Markup 2022-02-16 at 20 25 07

#### Main Index
* Moved section headings within the appropriate components
* Removed unused props
* Added `siteIsAutomatedTransfer` prop to the sections that needed to provide the different support links based on that context.

#### Composing section
* Removed unnecessary connect to the store
* Removed unused props
* Added section header
* Changed `Latex` and `Shortcodes` components from class components to functions
* Updated support links
Markup 2022-02-16 at 20 30 35

#### Content Types
* Extrapolated each fieldset into a component `BlogPosts`, `Testimonials`, and `Portfolios`.
* I tried to convert the index from a class to a function but was not successful with the autosave/update feature so I left this as a class.
* Updated support links
Markup 2022-02-16 at 20 31 05

#### Masterbar (only in self-hosted Jetpack sites)
* Added section header

#### Media (only in self-hosted Jetpack sites)
* Added section header

#### Publishing Tools
* Updated support links
* Replaced the generic HTML elements with the standardized Form components to make things consistent
* Adjusted section header
Markup 2022-02-16 at 20 32 00

#### Theme Enhancements
* Changed from class to function component
* Removed unused props
* Updated support links
Markup 2022-02-16 at 20 29 05

#### Widgets
* Removed unused props
* Changed from class to function component

## Testing instructions
* Pull branch and launch calypso with `yarn start`
* Go to Settings ⇢ Writing
* Adjust all settings and options and verify they update correctly
* Visually inspect for errors (there are slight variations due to the update to match styling)
* Click the `( i )` and make sure the link goes to Jetpack links on JPOP only sites and WPCOM for Simple and AT sites
* Repeat this process with each version - Simple, AT, and JPOP site
* I tested side-by-side with the live version. After a change in my test environment, I would refresh my live version to make sure the changes applied to the site settings.

Fixes #59977

### CODE REVIEW

File: client/my-sites/site-settings/theme-enhancements.jsx [hunk 1]
```diff
@@ -1,197 +1,163 @@
...
-							<hr />
-							{ this.renderCustomCSSSettings() }
-						</Fragment>
-					) : (
-						this.renderSimpleSiteInfiniteScrollSettings()
+					<RadioOptions />
+					<hr />
+					<SupportInfo
+						text={ translate(
+							"Adds names for CSS preprocessor use, disabling the theme's CSS, or custom image width."
```
Comment (a8ci18n) [inline client/my-sites/site-settings/theme-enhancements.jsx:89]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **19** times:
`translate( 'Adds options for CSS preprocessor use, disabling the theme's CSS, or custom image width.' )` *ES Score: 10*

**Comment by arcangelini** [comment]
Fixed a typo I noticed in a couple of the URLs and rebased it to fix all TeamCity tests. 🤞

File: client/my-sites/site-settings/custom-content-types/portfolios.jsx [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+		<FormFieldset>
+			<SupportInfo
+				text={ translate(
+					'Adds the Portfolio custom post type, allowing you to ' +
+						'manage and showcase projects on your site.'
+				) }
+				link={
+					isAtomic
+						? 'https://wordpress.com/support/portfolios/'
+						: 'https://jetpack.com/support/custom-content-types/#portfolios'
```
Comment (alshakero) [inline client/my-sites/site-settings/custom-content-types/portfolios.jsx]: This link seems incorrect, because `#privacy` will be added to it it will look like this: `#portfolios#privacy`.

File: client/my-sites/site-settings/composing/markdown.jsx [hunk 3]
```diff
@@ -21,10 +21,11 @@ const Markdown = ( { fields, handleToggle, isRequestingSettings, isSavingSetting
 					'Use Markdown syntax to compose content with links, lists, and other styles. This setting enables Markdown in the Classic Editor as well as within a Classic Editor block.'
 				) }
 				link={
-					isJetpack && ! isAtomic
+					siteIsJetpack && ! isAtomic
```
Comment (alshakero) [inline client/my-sites/site-settings/composing/markdown.jsx:24]: I'm not sure about this condition. The markdown info has an incorrect privacy link on simple sites.

**Review by alshakero — CHANGES_REQUESTED** [review]
Wow nice refactor!

So, I reviewed this. It's a good example of a PR that is pretty hard to review. If you remember us discussing hard reviews, I mentioned migrating to TypeScript as an example of a tough review because it makes git diffing completely useless; git can't tell which line is which, so it just renders two big code blocks; green and red.

Moving components from class to function is quite the similar in that sense. It's pretty hard for me to tell apart the logic changes against the janitorial changes.

Janitorial changes should be in their own dummy PR, zero logic change, just doing the single janitorial task; this way I don't review line by line, and I'd trust the author didn't engineer anything new. 

Found two tiny issues.

**Comment by arcangelini** [comment]
Thanks @alshakero for the tips and patience in reviewing this. I think I have a much better understanding of how to avoid this moving forward and will try to keep this more concise.

I updated the logic and tested every link on a JPOP, Atomic, and Simple site to make sure it all lines up. Everything should be correct now.

**Review by alshakero — APPROVED** [review]
LGTM now.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7180711

Thank you @arcangelini for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7180711).
