### PR TITLE
Site Setup:  Support community themes 

### LINKED ISSUE #97248: Community themes: with-theme onboarding flow is broken
### Quick summary

The onboarding flow for Community themes is currently broken. I've found two related issues:
1. It displays all plans in the plans page, not just the required ones (business and ecommerce). This means that users coming from the Logged out ThemeShowcase (https://WordPress.com/themes), after they sign up, they are able to select an incompatible plan with their theme.

2. No matter what plan I select, the onboarding gets stuck in setup/site-setup/processing with a JS error - selecting a compatible plan (Business), will still redirect to a loading screen - without the theme being installed on their site.

### Steps to reproduce

1. Open incognito
2. Go to https://WordPress.com/themes
3. Search for Astra
4. Click pick this design
5. Signup/login
6. Create a new site
7. Notice that all plans are displayed, including "Free", "Personal", "Premium" - giving the users the impression that they're able to use Astra with a non-business plan
8. Select free/Business/etc
9. Notice that you're stuck in a loading screen in setup/site-setup/processing

### What you expected to happen

- I should get only Business and eCommerce plans since those are the only ones compatible with a community theme
- The onboarding shouldn't get stuck

### What actually happened

I don't get the Community theme installed.

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by gabrielcaires**
Closes the  #97248

## Proposed Changes
* Map the theme_type param community to "dot-org"

## Why are these changes being made?
* The current theme selection uses "community" as dot-org theme, and the flow is expecting "dot-org." This mismatching is causing flow to crash and blocking the user to continue. 

## Testing Instructions

* Open an anonymous tab. 
* Go to [calypso live url]/themes)
* Search and select the `astro` theme
* Create a user or log in on WordPress.com
* Select a domain.
* Check if the plan page is not displaying the plans Free, Personal and Premium
* Select the Business plan.
* Check if you can finish the flow.
* Check if you can see a screen asking for install the astra theme

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/signup/steps/plans-theme-preselected/helper/index.ts [hunk 1]
```diff
@@ -0,0 +1,38 @@
+import {
+	MARKETPLACE_THEME,
+	DOT_ORG_THEME,
```
Comment (BogdanUngureanu) [inline client/signup/steps/plans-theme-preselected/helper/index.ts]: A community theme and a DOT_ORG_THEME should mean the same thing - a theme that's pulled from WordPress.org. Is this duplicate naming necessary, is there something we can do to avoid it? :)

Comment (gabrielcaires) [reply client/signup/steps/plans-theme-preselected/helper/index.ts]: Are you suggesting removing the DOT_ORG_THEME checking?

I saw we don't have a reference to `DOT_ORG` on the endpoint we are using to pull the theme list, but I am not sure if there is any other entry point the user can use to access the `copy-site` flow that is using "dot-org" instead of "community."

Since it is a blocker issue, I think we can investigate it better in another task.

**Comment by BogdanUngureanu** [comment]
Hi @gabrielcaires, thanks for the fix! :) 

I did a quick test and it seems that the flow is still broken after checkout, and I get an JS error on this page:
```
https://container-eloquent-mccarthy.calypso.live/setup/site-setup/processing?siteSlug=bogdanu91test9.wordpress.com&theme=astra&notice=purchase-success&categories=blog
```

Are you planning a separate fix for this scenario? :)

**Comment by BogdanUngureanu** [comment]
I also looked a bit more into the issue and it seems that the problem comes from the theme_type parameter we pass to the Signup URL.

If I test the flow on production by setting the theme type to `dot-org`, the theme gets installed on the site: https://wordpress.com/start/with-theme?ref=calypshowcase&theme=astra&theme_type=dot-org&intervalType=yearly

For some reason, we've changed it to `community`. I'm pretty sure it was set to `dot-org` in the past.

**Comment by BogdanUngureanu** [comment]
@gabrielcaires I think this can be easily fixed by adding a new `case` in this switch for DOT_ORG.

https://gist.github.com/BogdanUngureanu/277bc216436d2c7a8822aac2f3737f5c#file-get-theme-signup-url-js-L35

Basically, instead of defaulting to `community`, we should set it to `dot-org`.

**Comment by gabrielcaires** [comment]
@BogdanUngureanu Thanks for your suggestion.
 I agree we could fix it by renaming the community to dot-org, but I found other references to the community string as theme_type/tier.
 
Considering it, I thought about really supporting the community type via [these changes](https://github.com/Automattic/wp-calypso/pull/97276/commits/069d7a1a05e477042b4ae0fe1f620c190611de4d) and open a new issue just to check if we can just rename `dot-org` to community and remove the duplication. 

My concern is if we have any other link or flow pointing to this one where the user is already logged in, the issue will happens again. 

What do you think?

**Comment by BogdanUngureanu** [comment]
Hi @gabrielcaires, we won't rename the `community` theme tier to dot-org; theme tiers are not related to `with-theme`, it's a separate concept that was implemented by T-Rex last year in order to support themes on personal plans. 

Before we made [this change](https://github.com/Automattic/wp-calypso/pull/86053/files#diff-fdf13f731417a82fa2074d9e6da330488074bec8e3637623e3fa17ff73b6bfd9R37), the theme_type from /with-theme/ flow was set to `dot-org`. The change in this PR introduced a regression for the with-theme flow since it wasn't implemented to handle the `community` type. 

We just need to fix this regression and use `dot-org` in the query param.

**Comment by gabrielcaires** [comment]
@BogdanUngureanu,  
Thanks for the explanation.
I removed my changes and updated them as you suggested. 0b61e68fa8fd10933de623d86d150e8b4e96908b

**Review by BogdanUngureanu — APPROVED** [review]
Works as expected, thanks!
