### PR TITLE
Login: Only show the 2FA title on the 2FA step

### LINKED ISSUE #14039: Login: Wrong title when redirected from 2FA to Login
Raised by @stephanethomas  in 13987

> when you access the Verification Code page with a 2FA account, if you click the Return link you are redirected back to the Login page. However the title is not updated (or said differently, it has the wrong title):

### PR DESCRIPTION
**Pull request by scruffian**
This pull request fixes #14039 by only showing the "Two Step Authentication" title on the 2FA step.
  
#### Testing instructions
  
1. Run `git checkout fix/14039` and start your server
2. Open the [`Login` page](http://calypso.localhost:3000/)
3. Check that the title is "Log in to your account."
4. Log in with an account with 2FA enabled
5. Check that the page title is "Two-Step Authentication."
6. Click the back button in your browser
3. Check that the title is "Log in to your account."
  
#### Reviews
  
- [x] Code
- [x] Product

### CODE REVIEW

File: client/blocks/login/index.jsx [hunk 1]
```diff
@@ -138,12 +138,16 @@ class Login extends Component {
...
-		const { translate, twoStepNonce } = this.props;
+		const { translate, twoFactorEnabled, twoFactorAuthType } = this.props;
 
 		return (
 			<div>
 				<div className="login__form-header">
-					{ twoStepNonce ? translate( 'Two-Step Authentication' ) : translate( 'Log in to your account.' ) }
+					{
+						twoFactorEnabled && twoFactorAuthType
+							? translate( 'Two-Step Authentication.' )
```
Comment (a8ci18n) [inline client/blocks/login/index.jsx]: Hi! I've found a possible matching string that has already been translated **28** times:
`translate( 'Two Step Authentication Enabled' )` *ES Score: 18*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/fix/14039)

Help me improve these suggestions: react with :thumbsdown: if the suggestion doesn't make any sense, or with :thumbsup: if it's a particularly good one (even if not implemented).

**Comment by fabianapsimoes** [comment]
Product :+1:

**Comment by yurynix** [comment]
Thank you @scruffian  👍  LGTM
