### PR TITLE
Export: Handle Jetpack sites with a message and link to the site's wp-admin

### LINKED ISSUE #77: Export: be defensive when a user is viewing /export and switches to a jetpack site
<strong>Currently:</strong>
We are doing a good job when a user <em>has already selected a jetpack site</em> and attempts to visit /export. In that case we present them with an external link to their jetpack wp-admin/export.php page.

Where we fail is when the user navigates to /export with a wp.com blog and switches their site. We currently don't update the page at all so they see the same options as on a wp.com blog and could attempt an export.

To reproduce:
1. Go to http://calypso.dev:3000/settings/export/ and select a WordPress.com site
2. Click "← Switch Site"
3. Search for and select a Jetpack site

<strong>Expected:</strong>
Plugins has the same issue, but in reverse: a wp.com site shouldn't be able to see plugins (except sites with the WordPress.com Business plan that show ecommerce options there). They've handled it by displaying a wp.com-specific message upon switching sites:

screen shot 2015-11-18 at 12 43 04 pm

We will need to look at plugins and figure out how they're handling this message and do something similar. We'll need a graphic and need to generate a button that points to the appropriate wp-admin/export.php page (and make sure to update that link if they switch sites again to another jetpack site).

We have a very useful EmptyContentComponent that accepts a `title`, a `line`, and an `illustration`. We should just use the `illustration: '/calypso/images/drake/drake-jetpack.svg'` illustration for this since they're jetpack sites.

### PR DESCRIPTION
**Pull request by jordwest**
Jetpack sites currently cannot be exported via Calypso. Normally, clicking the **Export** tab while navigating a Jetpack site in Calypso takes the user to the Jetpack site's wp-admin export page.

However, if the user is already on the export tab and switches to a Jetpack site, the exporter is still displayed. This PR instead displays a message with a link to the Jetpack site's wp-admin export page.

Fixes #77

screen shot 2016-01-14 at 1 47 28 pm

#### How to test
1. Switch to a wordpress.com site
2. Go to http://calypso.localhost:3000/settings/export
3. Switch to a Jetpack site
4. The message shown in the screenshot above should be displayed

### CODE REVIEW

**Comment by dllh** [comment]
Hmm, the code looks good to me but the functionality's not working. I've made sure I've switched to the branch, and I've initiated `make run` fresh to make sure it's not just a stale environment. Is it possible there's some piece that didn't land in the commit that you have in your local environment?

File: client/my-sites/site-settings/section-export.jsx [hunk 1]
```diff
@@ -7,10 +7,25 @@ import { Provider } from 'react-redux';
...
+import i18n from 'lib/mixins/i18n';
 
 export default class SiteSettingsExport extends Component {
 	render() {
+		if ( this.props.site.jetpack ) {
+			return (
+				<EmptyContent
+					illustration="/calypso/images/drake/drake-jetpack.svg"
+					title={ i18n.translate( 'Want to export your site?' ) }
+					line={ i18n.translate( 'Visit your site\'s wp-admin for all your import and export needs.' ) }
```
Comment (dllh) [inline client/my-sites/site-settings/section-export.jsx]: I'm not 100% sure what standards dictate here, but I think that in general we prefer to see `"Visit your site's"` vs. `'Visit your site\'s'` when there's a quote that'll need to be escaped, since it's a little easier on translators to not have to think about the escaping.

Comment (jordwest) [inline client/my-sites/site-settings/section-export.jsx]: I copied this from [import](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/site-settings/section-import.jsx#L207) - that string's text is the same so should we change it there too or leave it as is in both locations?
cc @dmsnell

Comment (dmsnell) [inline client/my-sites/site-settings/section-export.jsx]: Here we should probably use the back tic instead of either quote character.

@jordwest feel free to update it in the import code as well!

**Comment by jordwest** [comment]
Hmm weird. Do you still see the exporter if you directly go to: http://calypso.localhost:3000/settings/export/[jetpack.site.com]?

**Comment by dllh** [comment]
Weird. I deleted my local branch, fetched again, and did `make distclean && make run`, and now it works well. Not sure what was up. I do note one oddity in the layout of the screen at narrow width:

export-artifact

Your work here didn't introduce it, as I see the same thing for import, but for some other screens (e.g. the Pages view when there are no pages), the UI scales more cleanly. Might be good to open an issue for this and see if we can offer a fix. I wouldn't hold this PR up for it, though.

Let's :ship: it.
