### PR TITLE
Logged-in Profiler: Public sites with missing launch status should be able to run performance test

### LINKED ISSUE #96533: Performance Monitoring feature says a site needs to be launched despite it being public already
### Quick summary

I have noticed some scenarios where the performance test tool (wordpress.com/sites/performance) asks users to "Launch" their site to test its performance, despite the site being live already.

This seems to happen in two scenarios:

1. The sites uses A records to connect the domain
2. The site uses Cloudflare

I suspect hat the tool is testing the site's DNS and classifying it as "private" unless the DNS point to WordPress.com's DNS

### Steps to reproduce

1. Set up a site whose domain is connected via A records (or that's using Cloudflare)
2. Make sure the site has been launched and is public
3. Navigate to https://wordpress.com/sites/performance/
4. Notice how performance tests are unavailable and you are directed to launch the site:

> **_Performance statistics are only available for public sites._**
> **_Launch your site to start measuring performance_**

Image

Site: https://losporfiados.com (A records)
Site: https://efe.com (Cloudflare)

### What you expected to happen

Performance tests should work with all domain setups, DNS, A records, or Cloudflare.

### What actually happened

They did not work in some scenarios, see above.

### Impact

All

### Available workarounds?

Yes, difficult to implement

### If the above answer is "Yes...", outline the workaround.

Users can still use the public testing tool at https://wordpress.com/speed-test and even subscribe to results but the current response is confusing and nowhere as convenient. 

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by vykes-mac**
Closes https://github.com/Automattic/wp-calypso/issues/96533

## Proposed Changes
Some sites which are older or have uses external domains may not have the `launch_status` property set. This prevents them from running performance tests. This PR fixes that by also checking if the blog is public when the `launch_status` is missing.

* check if `blog_public=1` when launch status is missing

## Why are these changes being made?

* So that these particular sites can run the test from the sites dashboard

## Testing Instructions

* Ensure you have a site with `launch_status` empty and `public_blog=1` 
* Go to `/sites/performance/siteSlug`
* Verify you are able to run performance test on the site and the `Launch site` CTA is not shown.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/hosting/performance/site-performance.tsx [hunk 1]
```diff
@@ -139,9 +140,13 @@ export const SitePerformance = () => {
...
 	const siteId = site?.ID;
-
+	const { getSiteSetting } = useSiteSettings( site?.slug );
+	const blog_public = getSiteSetting( 'blog_public' );
 	const isSitePublic =
-		site && ! site.is_coming_soon && ! site.is_private && site.launch_status === 'launched';
+		site &&
+		! site.is_coming_soon &&
+		! site.is_private &&
+		( site.launch_status === 'launched' || ( site.launch_status === '' && blog_public === 1 ) );
```
Comment (cpapazoglou) [inline client/hosting/performance/site-performance.tsx]: Isn't `blog_public === 1` enough?

Comment (vykes-mac) [reply client/hosting/performance/site-performance.tsx]: on further testing, you are correct `blog_public` should be enough

**Review by cpapazoglou — APPROVED** [review]
Thanks for looking more into it! Tested it and works well.
