### PR TITLE
Store: Fix orders widget language when there is only 1 new order pending

### LINKED ISSUE #16606: Store dashboard: Order copy on dashboard incorrect for single order
When there's 1 new order, the copy says `orders` instead of `order`. 

screen shot 2017-07-26 at 4 35 42 pm

### PR DESCRIPTION
**Pull request by justinshreve**
Fixes #16606.

This fixes the string so it correctly says "1 new order" or "x new orders" when there is more than one.

To Test:
* Apply this PR.
* Make sure you only have one order set to new/processing.
* Visit `http://calypso.localhost:3000/store/:site` and make sure that you have the "You have new orders" dashboard (not a setup dashboard screen).
* Verify you see the string "1 new order".
* Set an order to processing.
* Verify you see the string "2 new orders".

### CODE REVIEW

File: client/extensions/woocommerce/components/process-orders-widget/index.js [hunk 1]
```diff
@@ -15,12 +15,15 @@ import { getLink } from 'woocommerce/lib/nav-utils';
 const ProcessOrdersWidget = ( { className, site, orders, currency, ordersRevenue, translate } ) => {
 	const classes = classNames( 'card', 'process-orders-widget__container', className );
 	const currencyValue = currency && currency.value || '';
+	const orderCountPhrase = translate( 'New order', 'New orders', {
```
Comment (a8ci18n) [inline client/extensions/woocommerce/components/process-orders-widget/index.js]: Hi! I've found a possible matching string that has already been translated **24** times:
`translate( 'Save New Order' )` *ES Score: 7*

Help me improve these suggestions: react with :thumbsdown: if the suggestion doesn't make any sense, or with :thumbsup: if it's a particularly good one (even if not implemented).
