### PR TITLE
Simple Payments: Fix broken screens from invalid product prices.

### LINKED ISSUE #23213: Simple Payments: screen doesn't load if customer has text data in item price
#### Steps to reproduce

There was a customer support request `1001910-zen` where the customer had text data in some simple payment items price values, in which case the simple payments would no longer load.

Raised the potential data quality issue here: `p3fqKv-5FD-p2`

There is a JavaScript error loading the form:

```
Uncaught TypeError: Cannot read property 'integer' of null
    at ProductListItem.formatPrice (list-item.jsx:83)
    at ProductListItem.render (list-item.jsx:124)
    at finishClassComponent (react-dom.development.js:7873)
    at updateClassComponent (react-dom.development.js:7850)
    at beginWork (react-dom.development.js:8225)
    at performUnitOfWork (react-dom.development.js:10224)
    at workLoop (react-dom.development.js:10288)
    at HTMLUnknownElement.callCallback (react-dom.development.js:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:581)
    at invokeGuardedCallback (react-dom.development.js:438)
```

#### Screenshot / Video

screen shot 2018-03-12 at 9 42 57 am

This is what the "price" showed when I removed all formatting (data now fixed)

form

### PR DESCRIPTION
**Pull request by kwight**
This PR allows us to avoid fatals if invalid prices cause `getCurrencyObject` to return null. It will display the invalid price as `----`, hopefully prompting the user to edit the price. At some point, some users were able to somehow enter strings of text for the price; this is no longer possible, at least with the Simple Payments form validation.

screen shot 2018-03-16 at 4 50 57 pm

It's a very quick, shallow approach to larger issues. The price (and other Simple Payment data) are stored as post meta on their CPT posts, and intentionally stored as `string`s – this is a requirement for the server-side calls to the PayPal API, but problematic once in Calypso (or presumably any other client).

Further PRs that should happen include defining and improving behaviour; I'm thinking that if a product has an invalid price, we should:
* inform the user viewing the product list to go into the ellipsis menu to edit the product's price,
* identify the invalid price in the content editor ("invalid price – please correct"),
* ensure that any products with pricing issues are not displayed on the front-end.

Fixes #23213 .

### CODE REVIEW

File: client/components/tinymce/plugins/simple-payments/dialog/list-item.jsx [hunk 1]
```diff
@@ -40,6 +40,9 @@ class ProductListItem extends Component {
 	handleTrashClick = () => this.props.onTrashClick( this.props.paymentId );
 
 	formatPrice( price, currency = 'USD' ) {
+		if ( isNaN( price ) ) {
```
Comment (gwwar) [inline client/components/tinymce/plugins/simple-payments/dialog/list-item.jsx]: Hmm, can we also add a stat or tracks event here? Maybe [logging to kibana](https://github.com/Automattic/wp-calypso/tree/master/client/lib/catch-js-errors#example) would be a better fit?

**Comment by gwwar** [comment]
If we can add additional logging I think this would be a good first step 👍. @drw158 or @iamtakashi any thoughts on how we might give a better hint? This should hopefully be temporary on the client.

**Comment by alisterscott** [comment]
Thanks for this PR, I tried as SU on a customer with bad data in a payment button and this worked - it showed the --- on the list:

with pr applied

More discussion in `p3fqKv-6th-p2`

**Comment by kwight** [comment]
Ready for review; added logging (with data to identify the problem product), and colored the problematic prices `$alert-red`.

screen shot 2018-03-19 at 2 50 13 pm

**Comment by kwight** [comment]
Rebased to hopefully fix some `wp-desktop` circleci issues (possibly related to https://github.com/Automattic/wp-calypso/pull/23026 which was reverted).

**Comment by alisterscott** [comment]
This worked well in testing with the new formatting:

screen shot 2018-03-20 at 10 51 57 am

**Comment by alisterscott** [comment]
Thanks for the fix @kwight
