### PR TITLE
Upload Plugin: Fix condition to avoid showing error screen

### LINKED ISSUE #96916: After uploading a plugin, there is an error page displayed, and then it disappears
### Quick summary

|Click on Upload | Confirm Warnings| Upload plugin| Transfer starts| Error :warning:|
|-------|------|------|------|------|
| Image  |     Image          |       Image         |     Image         |     Image        |

### Steps to reproduce

1. Start with a Simple site
2. Buy the Business plan
3. Go to plugins and click on Upload
4. Confirm warnings and upload a plugin

### What you expected to happen

There are no errors, and we land on the plugins page

### What actually happened

An error is displayed during a split of a second

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

The error is not reproducible for all sites

Found in p58i-iNH-p2

### PR DESCRIPTION
**Pull request by epeicher**
Resolves https://github.com/Automattic/wp-calypso/issues/96916

## Proposed Changes

* Updates the condition to check that the Upload process has completed, so the error screen is not displayed.

## Why are these changes being made?

* That error screen was displayed unnecessarily

## Testing Instructions

* Apply this patch
* With a Business site selected that is **not** atomic, navigate to plugins, i.e. `/plugins/:siteId`
* Upload a plugin
* Accepts the eligibility warnings if required
* Check the process completes and no intermediate error screen is shown.
- Additionally, access this URL directly for any site and check that the error screen is displayed: `/marketplace/plugin/install/:siteDomain` 

#### After the fix

https://github.com/user-attachments/assets/77bee574-a86d-4b56-975d-e38b71d27523

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by gcsecsey — COMMENTED** [review]
With a newly created business site, I tested uploading the Jetpack Beta plugin. For a brief moment I still got an intermediate screen before I was redirected to the plugins page:

https://github.com/user-attachments/assets/8ef95c12-6dba-48c5-a714-127a316377ab

**Comment by epeicher** [comment]
> With a newly created business site, I tested uploading the Jetpack Beta plugin. For a brief moment I still got an intermediate screen before I was redirected to the plugins page:

Thanks @gcsecsey, it seems there is still a wrong intermediate state there. I will keep investigating this

**Comment by epeicher** [comment]
Ok, I have found the issue, the domain changes from `.wordpress` to `.wpcomstaging` (as expected) so there is some state where the `primaryDomain` is different than the `selectedSite`. I am going to check for alternative options

https://github.com/user-attachments/assets/7f3be557-9587-49ba-8b57-f17b16c97511

**Comment by gcsecsey** [comment]
> Ok, I have found the issue, the domain changes from `.wordpress` to `.wpcomstaging` (as expected) so there is some state where the `primaryDomain` is different than the `selectedSite`. I am going to check for alternative options
> 
>  CleanShot.2025-02-06.at.11.53.39.mp4

Nice sleuthing!

I think we have two ways of going about this:
- When the AT transfer is finished, we could update the `primaryDomain` in state and use the current check
- When we're in the AT transfer flow (`supportsAtomicUpgrade` is set), we could disregard the domain mismatch

Let me know if I can help in finding a solution or testing it! 🙌

File: client/my-sites/marketplace/pages/marketplace-product-install/index.tsx [hunk 1]
```diff
@@ -170,14 +170,22 @@ const MarketplaceProductInstall = ( {
 		}
 	} );
 
+	const { primaryDomain } = useSelector( getPurchaseFlowState );
+
+	const shouldShowNoDirectAccessError =
+		// 1. This is a plugin upload flow (via zip file) and we don't have a primary domain set
+		( isPluginUploadFlow && ! primaryDomain ) ||
```
Comment (cpapazoglou) [inline client/my-sites/marketplace/pages/marketplace-product-install/index.tsx:177]: Do we really care about the `primaryDomain` or can we simplify the logic and avoid showing the error for any `isPluginUploadFlow`?

**Review by cpapazoglou — APPROVED** [review]
Worked fine in my testing!

File: client/my-sites/marketplace/pages/marketplace-product-install/index.tsx (hunk 1 above)
Comment (epeicher) [reply client/my-sites/marketplace/pages/marketplace-product-install/index.tsx:177]: Good point, I added this extra condition in a later commit to show the error screen when the user navigates back or accesses directly to the URL `/marketplace/plugin/install/:siteDomain` because they will get stuck in this screen otherwise: 

CleanShot 2025-02-07 at 13 34 09@2x
