### PR TITLE
Pages: Fix display of no search results and no pages

### LINKED ISSUE #18306: Pages: No search results says nothing published
Pages have inaccurate messaging for empty search results.

#### Steps to reproduce
1. Visit https://wordpress.com/pages
1. Observe that you have some pages.
1. Enter a search with no matches (http://calypso.localhost:3000/pages?s=aQueryThatDoesn%27tMatch)
1. Observe the messaging. It's not correct, you _have_ published pages, they just don't match the search.
1. The same behavior for posts is OK.

#### What I expected

Tell me no pages match my search.

#### What happened instead

I'm told I haven't published any pages!

##### Posts 👍 

posts-good

##### Pages 👎 

pages-bad

#### Context / Source

Discovered will reviewing #18270

### PR DESCRIPTION
**Pull request by danhauk**
This fixes #18306. I also noticed while testing this that all of the `<EmptyContent/>` messages were the same default case. This PR fixes that issue too.

Before | After
------------ | -------------
image | image
image | image

#### Testing

1. Run `git checkout fix/pages-empty-content` or open a [live branch](https://calypso.live/?branch=fix/pages-empty-content)
2. Visit your pages at http://calypso.localhost:3000/pages
3. Enter a search with no matches
4. Assert that you see the proper `No pages match your search ...` message
5. Close the search and switch between Published, Drafts, Scheduled, and Trashed
6. Assert that the messaging changes with each route change

### CODE REVIEW

File: client/my-sites/pages/page-list.jsx [hunk 1]
```diff
@@ -177,29 +178,29 @@ const Pages = localize( React.createClass( {
 			);
 		}
 
-		const { site, siteId, status = 'published' } = this.props;
+		const { site, siteId } = this.props;
```
Comment (sirreal) [inline client/my-sites/pages/page-list.jsx]: NIT: I think it would be clearer to unify the multiple `this.props` destructuring assignments.

Comment (danhauk) [reply client/my-sites/pages/page-list.jsx]: Good catch on that, thanks! I agree. Do you have a recommendation for destructuring `query` at [line 165](https://github.com/Automattic/wp-calypso/pull/18345/files/312160586e17781c85727f59a30671833a826bf6#diff-602dc25e101e23d58d5413716a4074e9R165)? Should I also add `query` to the first assignment and then destructure `query` in the next line rather than `this.props.query`?

**Comment by sirreal** [comment]
I rebased this, `master` had evolved significantly 🙂

File: client/my-sites/pages/page-list.jsx [hunk 2]
```diff
@@ -156,7 +156,8 @@ const Pages = createReactClass( {
 	},
 
 	getNoContentMessage() {
-		const { search, translate } = this.props;
+		const { translate } = this.props;
+		const { search, status = 'published' } = this.props.query;
```
Comment (sirreal) [inline client/my-sites/pages/page-list.jsx]: Thoughts about this:

- We depend on `this.props.query` being an object, otherwise we'll get an error when we try to do this destructuring assignment.
- You mention [in your question](https://github.com/Automattic/wp-calypso/pull/18345/files#r148956867) assigning `query` from `this.props`, then assigning other constants from `query`. I like that approach because if we add a default empty object query, we get some protection:
   ```js
   const noProps = {};
   const { doesntExist = {} } = noProps;
   const { noError } = doesntExist;  // 🎉

  // specifically in this case
  const { query = {}, translate } = this.props;
  const { search, status = 'published' } = query;
  // search === undefined; status === 'published'
   ```
- It would also be nice to add `propTypes` for this:
  ```js
  propTypes: {
    // …
    query: PropTypes.object
  },
  ```
  [You can go pretty bananas with `propTypes`](https://reactjs.org/docs/typechecking-with-proptypes.html#proptypes), describing the shape of the object in great details, but I think just saying we expect an object is sufficient here 🙂

**Comment by danhauk** [comment]
@sirreal Thanks so much for rebasing so I didn't have to, much appreciated. :) And thanks for your input on best way to unify `this.props`. I pushed up a change to do that and also added `propTypes`.

**Comment by sirreal** [comment]
😀  My pleasure, thanks for the fixes!
