### PR TITLE
Design Picker: Add Partner theme to cart based on the current plan

### LINKED ISSUE #87281: Checkout fails when using the DP to buy a partner theme while on an annual starter or explorer plan
### Quick summary

All sites can use the onboarding design picker at any time. Sites with a annual or longer starter or explorer plan can choose a Partner theme in the design picker. A partner theme adds a mandatory upgrade to the monthly Creator plan, but this won't work - we don't allow "upgrades" to a lower length plan.

### Steps to reproduce

1. Get a site on an annual or greater starter or explorer plan
2. Go to https://wordpress.com/setup/site-setup/designSetup?siteSlug=YOURDOMAINHEREDOTCOM
3. Choose a partner theme
4. Press Unlock theme
5. See the dialog that says you're going to be on the creator plan with a monthly price
6. Press Continue
7. If you get a warning about the domain changing press Continue

### What you expected to happen

See a checkout screen with two items: a monthly creator plan and a monthly paid partner theme and be able to checkout

### What actually happened

Empty cart with error messages including "Sorry, that plan is not a valid ugprade from your current plan"
Screenshot 2024-02-07 at 17 43 57

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

The POST to https://public-api.wordpress.com/rest/v1.1/me/shopping-cart/somedigits includes adding a `business-bundle-monthly` product. The response includes an empty product list and two errors with codes `invalid-product-upgrade` and `remove-marketplace-theme`.

Invalid product upgrade probably comes from here: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Snqzva%2Qcyhtvaf%2Sjcpbz%2Qovyyvat%2Sqrsnhyg%2Qfubccvat%2Qpneg%2Qinyvqngbe.cuc%3Se%3Q09or4p97%231673-og which says "This allows a plan upgrade with same or longer term OR a same plan term change (up or down)."

### PR DESCRIPTION
**Pull request by WBerredo**
Fixes https://github.com/Automattic/wp-calypso/issues/87281

## Proposed Changes

On the Design Picker, for Partner Themes, define the billing period of the and plan (if needed) based on the current plan.

The added business plan should have the same billing period as the current plan, if the user doens't have a plan, the monthly version should be added.

## Testing Instructions

**Explorer Plan 3 years**

* Using a site with the above plan, go to the following URL `/setup/site-setup/designSetup?siteSlug=:SITE_URL`
* Select a  Partner theme (look for the `Partner` badge)
* Click to `Unlock Theme`
* A Modal will be shown with the Theme and the Creator Plan displayed. The plan should be triennial and the product should show the monthly version.
* Proceed to the checkout should display those items in the cart.

**Explorer Plan 2 years**

* Using a site with the above plan, go to the following URL `/setup/site-setup/designSetup?siteSlug=:SITE_URL`
* Select a  Partner theme (look for the `Partner` badge)
* Click to `Unlock Theme`
* A Modal will be shown with the Theme and the Creator Plan displayed. The plan should be biennial and the product should show the monthly version.
* Proceed to the checkout should display those items in the cart.

**Explorer Plan yearly**

* Using a site with the above plan, go to the following URL `/setup/site-setup/designSetup?siteSlug=:SITE_URL`
* Select a  Partner theme (look for the `Partner` badge)
* Click to `Unlock Theme`
* A Modal will be shown with the Theme and the Creator Plan displayed. The plan should be annual and the product should show the monthly version.
* Proceed to the checkout should display those items in the cart.

**Explorer Plan monthly**

* Using a site with the above plan, go to the following URL `/setup/site-setup/designSetup?siteSlug=:SITE_URL`
* Select a  Partner theme (look for the `Partner` badge)
* Click to `Unlock Theme`
* A Modal will be shown with the Theme and the Creator Plan displayed. Both should be displayed as monthly.
* Proceed to the checkout should display those items in the cart.

**Creator Plan**

* Using a site with the above plan, go to the following URL `/setup/site-setup/designSetup?siteSlug=:SITE_URL`
* Select a  Partner theme (look for the `Partner` badge)
* Click to `Unlock Theme`
* A Modal will be shown with the Theme.
* Proceed to the checkout should display those items in the cart.

**Free plan** 
* Go to `/start/free`
* You should follow the same flow as before
* Both products should be displayed as monthly on the modal and cart

| Explorer Plan monthly / Free | Explorer Plan yearly | Creator Plan |
| ------------- | ------------- | ------------- |
|CleanShot 2024-02-08 at 16 09 02@2x|CleanShot 2024-02-08 at 16 08 51@2x|CleanShot 2024-02-08 at 16 15 07@2x|

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by cpapazoglou — APPROVED** [review]
Works OK for me, I will defer to @dsas for a potential we might have missed.

File: client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx [hunk 1]
```diff
@@ -469,7 +474,9 @@ const UnifiedDesignPickerStep: Step = ( { navigation, flow, stepName } ) => {
 		if ( themeHasBundle ) {
 			plan = 'business-bundle';
 		} else if ( selectedDesign?.is_externally_managed ) {
-			plan = ! isExternallyManagedThemeAvailable ? PLAN_BUSINESS_MONTHLY : '';
+			const businessPlan =
+				selectedMarketplaceProduct.product_term === 'year' ? PLAN_BUSINESS : PLAN_BUSINESS_MONTHLY;
```
Comment (dsas) [inline client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx]: This works great when the user has a yearly explorer plan, but not when they have a two year explorer plan (or a three year plan)

**Review by dsas — APPROVED** [review]
Really sorry it took so long to review, it completely slipped my mind.

This PR doesn't solve for when the user has a two year explorer plan etc. We can still ship it though, it works for when the user has a one year plan which I assume is the most common case 👍

**Comment by WBerredo** [comment]
I had updated the logic to keep the product always on the monthly version and the Business plan to match with the billing period of the current selected plan.

File: client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx (hunk 1 above)
Comment (WBerredo) [reply client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx]: Yeah, this makes sense, it should be fixed here https://github.com/Automattic/wp-calypso/pull/87312/commits/5235c652e86f54cc28c5d375f672322756397507

**Review by cpapazoglou — APPROVED** [review]
LGTM

**Review by dsas — APPROVED** [review]
Works for me 👍 thanks for sticking with it @WBerredo

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/11602499

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @WBerredo for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/11602499).
