### PR TITLE
Woo Tailored Onboarding: Fix redirect after signup

### LINKED ISSUE #70545: Woo Tailored Onboarding: Creating a new user redirects to /read
If we create a new user through the new Woo flow, we get redirected to `/read` and not to `/setup/ecommerce?flags=signup/tailored-ecommerce`

Steps to reproduce:
* Navigate to `/setup/ecommerce?flags=signup/tailored-ecommerce` on an incognito tab, and make sure you are not logged in.
* Fill in the information to create an account
* Get redirected to `/read` instead of being redirected back to `/setup/ecommerce?flags=signup/tailored-ecommerce`

### PR DESCRIPTION
**Pull request by valterlorran**
#### Proposed Changes

* Fix the redirect after the signup. The user was being redirected to `/setup/storeProfiler?flow=ecommerce` instead of `/setup/ecommerce/storeProfiler` after the checkout.
* I also added the flag on the redirect URL when the current URL contains it.

#### Testing Instructions

* Log out from your account
* Navigate to `setup/ecommerce?flags=signup/tailored-ecommerce`
* Click on "Create your store"
* Go through the signup process
* You should be redirected to `/setup/ecommerce/storeProfiler?flags=signup/tailored-ecommerce`

Closes #70545

### CODE REVIEW

File: client/landing/stepper/declarative-flow/tailored-ecommerce-flow.ts [hunk 1]
```diff
@@ -60,11 +60,16 @@ export const ecommerceFlow: Flow = {
 		const locale = useLocale();
 		const siteSlugParam = useSiteSlugParam();
 		const site = useSite();
+		const flags = new URLSearchParams( window.location.search ).get( 'flags' );
 
 		const getStartUrl = () => {
```
Comment (markbiek) [inline client/landing/stepper/declarative-flow/tailored-ecommerce-flow.ts:65]: I worry this is getting a little hard to read. What if we did something like this instead?

```
const getStartUrl = () => {
	let url =
		locale && locale !== "en"
			? `/start/account/user/${locale}?variationName=${flowName}&redirect_to=/setup/ecommerce/storeProfiler`
			: `/start/account/user?variationName=${flowName}&redirect_to=/setup/ecommerce/storeProfiler`;

	return url + (flags && `?flags=${flags}`);
};
```

Otherwise, it worked as expected!

**Review by markbiek — APPROVED** [review]
LGTM!
