### PR TITLE
fix: override "View Post" behavior for wp-desktop

### LINKED ISSUE #908: Clicking “View Post” after updating a post or page locks the user out of the main UI
#### Steps to reproduce
1. Editor: open a post or page
2. Make a change
3. Click **Update**
4. Click **View post** (snackbar on the lower left)
5. Confirm to be unable to return to the main UI without quitting the app

#### What I expected
Upon clicking "View Post", a new browser window should be opened.

#### What happened instead
The post opened in the app window with no way back to the main UI.

#### App Version / OS version
6.0.0-beta2 - Mac OS 10.13

#### Screenshot / Video
https://cloudup.com/cEcGroUU_Vg

#### Context / Source
https://apptestingo2.wordpress.com/2020/06/11/to-test-wordpress-com-desktop-6-0-0/#comment-5072

#manual-testing #dogfooding

### PR DESCRIPTION
**Pull request by nsakaimbo**
### Description

A bug in the WordPress Desktop app was recently discovered in which clicking `View Post` on a newly updated/published post takes the user out of the Calypso iframe context (since the window location is overriden), leaving the app in an unusable state (all keyboard shortcuts cease to work, and clicking on items in the sidebar panel will take us to a browser, instead of remaining in-app). 

~~I've been trying to override this behavior in this PR, but haven't quite gotten it to work (see comments below). I would appreciate some pointers/suggestions on what I may be missing.~~

**_Update_**: Finally got this working and tested in a wp.com sandbox. ✅ 

Fixes Automattic/wp-desktop#908 (see issue for more details) and pairs with Automattic/wp-desktop#924.

We'd want to override the default behavior wherever "View Post" is available to be clicked, such as the snackbar in the bottom left and under "Publish".

<p align="center">
view-post-publish
</p>

<p align="center">
view-post-snackbar
</p>

### To Reproduce

In the desktop app:

1. Edit an existing post and click "View Post" in the snackbar, OR
2. Publish a draft and click "View Post" when published

_Expected_: Navigate to the published post in an external browser
_Actual_: The published post is displayed by overriding the Electron window's location, and because the iframe context has been lost the user is left in a broken state in-app.

<p align="center">
out-of-calypso-iframe
</p>

### To Test

Using a wp.com sandbox (sandbox the block editor as well as a test site), verify that:

- These changes do not affect the existing behavior of clicking "View Post" after a post is updated or published.
- These changes allow the desktop app as built from Automattic/wp-desktop#924 to open the post's link in an external browser when "View Post" is clicked

### CODE REVIEW

File: apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js [hunk 1]
```diff
@@ -604,10 +607,15 @@ function openLinksInParentFrame() {
 		'.components-snackbar-list .components-snackbar__content a', // View Post link in success snackbar, Gutenberg >=5.9
 		'.post-publish-panel__postpublish .components-panel__body.is-opened a', // Post title link in publish panel
 		'.components-panel__body.is-opened .post-publish-panel__postpublish-buttons a.components-button', // View Post button in publish panel
+		// '.components-snackbar .components-snackbar__content a.components-button', // .components-snackbar__action.is-tertiary
 	].join( ',' );
 	$( '#editor' ).on( 'click', viewPostLinkSelectors, ( e ) => {
 		e.preventDefault();
-		window.open( e.target.href, '_top' );
+		if ( isDesktop ) {
```
Comment (nsakaimbo) [inline apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js:614]: As far as I can tell, this seems to be the correct place to override this behavior (i.e. disable the `window.open` and instead send the desktop app a custom event. However: (1) the default behavior is occurring anyway, and (2) the desktop event is not being sent. 🤔

Comment (nsakaimbo) [reply apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js:614]: 👋 Pinging @mmtr @kwight as I see you might be familiar with this logic in the iframe bridge server, or could perhaps help point me in the right direction?

**Comment by nsakaimbo** [comment]
Also pinging Gutenberg Platform @sirreal, @fullofcaffeine and @WunderBart as I was informed this might be within the scope of the new team's domain?

File: apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js (hunk 1 above)
Comment (mmtr) [reply apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js:614]: @nsakaimbo similarly to FSE, the `wpcom-block-editor` app doesn't run in Calypso. Did you generate a new build and uploaded it to your WP.com sandbox? See PCYsg-l4k-p2.

Also, since this file runs in the WP Admin context and not in Calypso, dispatching a Calypso action here won't have any any effect. In order to communicate with Calypso, you need to send a message through the iframe port communication channel ([see example](https://github.com/Automattic/wp-calypso/blob/7b12ea2ddd42b82852726fd7f452b8cc88cccee3/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js#L476-L484)) and then listen for that message in Calypso so you can dispatch the desired action ([see example](https://github.com/Automattic/wp-calypso/blob/7b12ea2ddd42b82852726fd7f452b8cc88cccee3/client/gutenberg/editor/calypsoify-iframe.tsx#L282-L285)).

Comment (nsakaimbo) [reply apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js:614]: Thanks, @mmtr! To-date, I haven't had reason to use the WP.com sandbox, so this wasn't on my radar. Thanks for the links - will set up a sandbox and proceed accordingly.

To clarify: this means that in order for these changes to take effect, the final code changes must be deployed to both WP.com and Calypso?

Since this file runs in the WP Admin context, will checking for `config.isEnabled( 'desktop` )` within this file work? If not, I'm not sure how to proceed here since the default action (`window.open`) cannot be short-circuited based on environment/context.

Comment (mmtr) [reply apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js:614]: Let me know if you need any help @nsakaimbo!
> this means that in order for these changes to take effect, the final code changes must be deployed to both WP.com and Calypso?

Correct!

> Since this file runs in the WP Admin context, will checking for config.isEnabled( 'desktop ) within this file work?

Nope, you'd need to perform this check in the client listener. Something like:

`iframe-bridge-server.js`
```
calypsoPort.postMessage( 
  { 
    action: 'viewPost',
    payload: {
        postUrl: postUrl,
    },
  },
);
```

`calypsoify-iframe.tsx`
```
if ( 'viewPost' === action ) {
  const { postUrl } = payload;
  config.isEnabled( 'desktop' )
    ? dispatch( notifyDesktopViewPostClicked( postUrl );
    : window.location.href = postUrl;
}
config.isEnabled( 'desktop ) ?
```

Comment (nsakaimbo) [reply apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]: _Update_: the changes you suggested made sense and I went ahead and incorporated them in 4312a43ae1a0366d538eec26cb4774e119e3f4f2. This PR pairs with the changes in the desktop repo [here](https://github.com/Automattic/wp-desktop/compare/fix-view-post-handler).

However I haven't had much luck testing as I've been struggling to get the wp.com sandbox set up (I'm a `wp.com` sandbox noob 😅 ). I was able to follow the instructions to build the block editor and sync with `unison`, however am unclear how to point the desktop app to use the sandbox instead of production.

Comment (nsakaimbo) [reply apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js]: Update: Made some progress and I think I'm most of the way towards sandboxing the block editor correctly: running Calypso from localhost while sandboxing the API as well as `widgets.wp.com`. However the changes don't appear to be working, so I might still be missing something.

**Comment by sirreal** [comment]
> Also pinging Gutenberg Platform … I was informed this might be within the scope of the new team's domain?

Thanks for the ping, I've added this to our project backlog. Strictly speaking, I'd say this is part of our domain or at least close enough and we should be familiar with it 🙂  Practically speaking, we're just booting up the squad and don't have much bandwidth for anything beyond our short term priorities.

It looks like you're in good hands already on this one, but please do ping us in the future with this sort of editor integration issue 👍

**Comment by nsakaimbo** [comment]
@sirreal Thanks for update! Totally understand that your team is only just getting up-and-running. I may reach out down the road for your subject matter expertise as other issues come up, but for now @mmtr has been a great help and I think I'm covered with respect to this issue specifically.

**Comment by nsakaimbo** [comment]
Update: also submitted wp.com Phabricator diff based on this PR (build-wpcom-block-editor build #776963).

**Review by mmtr — APPROVED** [review]
Wonderful work @nsakaimbo! Verified that Calypso continue opening the posts as always and the desktop app send them to the browser.

**Calyspo**

Jun-18-2020 11-18-41

**Desktop**

Jun-18-2020 11-38-50

File: client/gutenberg/editor/calypsoify-iframe.tsx [hunk 2]
```diff
@@ -275,6 +277,13 @@ class CalypsoifyIframe extends Component< Props & ConnectedProps & ProtectedForm
 			this.openPreviewModal( postUrl, ports[ 0 ] );
 		}
 
+		if ( EditorActions.ViewPost === action ) {
+			const { postUrl } = payload;
+			config.isEnabled( 'desktop' )
+				? this.props.notifyDesktopViewPostClicked( postUrl )
+				: window.open( postUrl );
```
Comment (jsnajdr) [inline client/gutenberg/editor/calypsoify-iframe.tsx:284]: This changes behavior of the "View Post" action for the web client. Ther original code called `window.open( url, '_top' )`, opening the post URL in the same tab (i.e., the top parent frame of the `iframe`.

Now, the mere `window.open( url )` will open a new tab.

I like the "open the new tab" behavior better, but if we change it, it should be intentional.

Comment (nsakaimbo) [reply client/gutenberg/editor/calypsoify-iframe.tsx:284]: @jsnajdr Thanks for taking a peek! After consulting/testing with @mmtr, we determined this should be fine. I'm also +1 for opening the post in a new tab - it feels a little bit nicer to not force the user out of their current context. That being said, if we get any feedback to the contrary, it would be trivial to change and happy to do so.
