### PR TITLE
Proxy content via public-api, even when we're on a simple site.

### LINKED ISSUE #87642: Missing media on Simple Sites after the files.wordpress.com > wp-content/uploads path change
# UPDATE May 9, 2024: Read before Reporting

Please investigate the missing image issue you're dealing with before reporting on this thread.

Current escalation thread: p1715271974999929/1715265147.089629-slack-C02FMH4G8

## (Possible) Current Symptoms

* Images can't be seen on Calypso, wp-admin and live site
* Primary domain is set to external name servers, or has only been recently pointed to WP.com (so still propagating)
* Sometimes we can repro, sometimes we can't
* Privacy settings on the site might be set to Coming Soon/Private

_________________________________________________________________
_________________________________________________________________
_________________________________________________________________
_________________________________________________________________
_________________________________________________________________

### Previous Symptoms:

This is exclusive to the issue triggered by the change of the file paths on **Simple Sites** from `files.wordpress.com` to `/wp-content/uploads/`. 

- Images load for users on the media library and the editor, but not on the frontend
- Images load for HEs correctly while proxied
- User report discrepancies between the file paths they can see X what they can't see (`files.wordpress.com` X `/wp-content/uploads/`)

### Updates
- Initial escalation thread: p1708425842573889-slack-C02FMH4G8
- An initial fix was issued around Feb 20
- A second fix for .blog subdomains was issued around March 20.
- New escalation thread: p1711639735891989-slack-C02FMH4G8

_______________________

### Quick summary

I noticed that there are a number of reports of missing images or other media on a number of WordPress.com sites. The sites seem **not to be plugin-enabled** sites. Opening this issue to track reports.

My first encounter of this issue was in 7766785-zen where the user reported that all media save for the most recent two posts are no longer loading, and the relevant media is not displaying in the Media library.

### Steps to reproduce

According to @vinnykaur , we haven't been able to reproduce this on our side. See p1708426096835589-slack-C02FMH4G8

### What you expected to happen

Media should load consistently.

### What actually happened

Media seems to be removed or is not loading for older content.

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Other reports:

- 7766855-zen
- [Photos disappearing – media library problems | WordPress.com Forums](https://wordpress.com/forums/topic/photos-disappearing-media-library-problems/)

### LINKED ISSUE #90972: Images not showing (403 error) on private simple sites with a custom primary domain.
### Quick summary

When a Simple Site is set to private, media images do not show up in Calypso interfaces such as the Media library (or blocks dependent on it like the [Slideshow Block](https://wordpress.com/support/wordpress-editor/blocks/slideshow-block/)) 

Browser console shows;

```
GET https://i0.wp.com/domain.com/wp-content/uploads/2024/04/20240224 181813.jpg?ssl=1&resize=438%2C438 403
(Forbidden)
```

### Steps to reproduce

1. Have a simple site with a custom domain set to private
2. Go to the media library (Calypso) or add a slideshow block and try and choose images
3. The images will not load with a 403 error

### What you expected to happen

Images should show

### What actually happened

Images show a 403 error

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

- Can switch to classic view in media library, but cannot in slideshow block. 
- If you switch back to `.wordpress.com` as primary domain, the images load
- If you make the site public, images load.

### PR DESCRIPTION
**Pull request by devicenull**
Related to #87642

## Proposed Changes

In order to solve #87642, we need to proxy any images in the media area via the public API.

This solves two main cases:
1) Where the primary redirect is not yet pointed to us via DNS
2) Where a service like Cloudflare is in front of the primary redirect, and blocks "hotlinking" images

These cases both used to work fine, as media was served from *.files.wordpress.com regardless of the actual domain being used.  Once this was been moved to use wp-content/uploads (in order to fix issues when third party cookies are blocked), the two cases above (and probably some others we don't know about) stopped working.

~~This will not work until D149138-code is deployed~~ (this has been deployed)

## Testing Instructions

* Open a media library like http://calypso.localhost:3000/media/meltbeforefailure.net
* Verify images appear
* Inspect an image, verify the src is "blob:http://calypso.localhost" instead of a wp-content/uploads URL

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [n/a] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [n/a] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [n/a] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: client/my-sites/media-library/media-file.tsx [hunk 1]
```diff
@@ -55,10 +54,9 @@ const MediaFile: React.FC< MediaFileProps > = function MediaFile( {
 export default connect( ( state: IAppState, { src }: Pick< MediaFileProps, 'src' > ) => {
 	const siteId = getSelectedSiteId( state );
 	const siteSlug = getSelectedSiteSlug( state ) as string;
-	const isAtomic = !! isSiteAutomatedTransfer( state, siteId as number );
-	const isPrivate = !! isPrivateSite( state, siteId ?? 0 );
 	const { filePath, query, isRelativeToSiteRoot } = mediaURLToProxyConfig( src, siteSlug );
-	const useProxy = Boolean( isAtomic && isPrivate && filePath && isRelativeToSiteRoot );
+	const isJetpack = isJetpackSite( state, siteId ?? 0, { treatAtomicAsJetpackSite: false } );
+	const useProxy = Boolean( ! isJetpack && filePath && isRelativeToSiteRoot );
```
Comment (fullofcaffeine) [inline client/my-sites/media-library/media-file.tsx]: Not a huge deal, but I'd say a more idiomatic way of doing this and making sure the return type is always bool would be to:

```js
cost isProxy = ! isJetpack && !! filePath && isRelativeToSiteRoot;
```

This ensures that the value for `filePath` is converted to bool and makes the expression return `bool` as well, without the need to call `Boolean()` over it.

Another point in favor of `!!` in this specific case is that we're isolating the cast to the variable that needs it, as the others are already bool.

File: client/blocks/image-editor/image-editor-canvas.jsx [hunk 2]
```diff
@@ -100,9 +101,9 @@ export class ImageEditorCanvas extends Component {
 	}
 
 	fetchImageBlob( src ) {
-		const { siteSlug, isPrivateAtomic } = this.props;
+		const { siteSlug, isJetpack } = this.props;
 		const { filePath, query, isRelativeToSiteRoot } = mediaURLToProxyConfig( src, siteSlug );
-		const useProxy = isPrivateAtomic && filePath && isRelativeToSiteRoot;
+		const useProxy = ! isJetpack && filePath && isRelativeToSiteRoot;
```
Comment (fullofcaffeine) [inline client/blocks/image-editor/image-editor-canvas.jsx]: For consistency purposes, we should either cast the `filePath` with `!!`  (or `Boolean`) like I'm suggesting [here](https://github.com/Automattic/wp-calypso/pull/90895/files#r1612421024), or the expression return type will be `bool | ".` Functionally it doesn't make a difference as `"` is truthy, but it could cause confusion.

File: client/my-sites/media-library/media-file.tsx (hunk 1 above)
Comment (fullofcaffeine) [reply client/my-sites/media-library/media-file.tsx]: I also see that `isJetpack` is not properly typed, and might be `null`, but that's a problem in the `isJetpackSite` function, not in this line. Again, in practice, it will not matter as `null` would basically equal false(y) and the `!` will make sure to return a `bool` value.

**Comment by fullofcaffeine** [comment]
The changes look simple enough that manual testing might suffice, but I personally would add a unit test for both functions to ensure that we get the right output for each permutation of values.

File: client/blocks/image-editor/image-editor-canvas.jsx [hunk 3]
```diff
@@ -295,6 +296,7 @@ export default connect(
 		const siteSlug = getSelectedSiteSlug( state );
 		const isPrivateAtomic =
 			isPrivateSite( state, siteId ) && isSiteAutomatedTransfer( state, siteId );
+		const isJetpack = isJetpackSite( state, siteId, { treatAtomicAsJetpackSite: false } );
```
Comment (tyxla) [inline client/blocks/image-editor/image-editor-canvas.jsx]: I'd rename this to `isJetpackNotAtomic` or similar for better clarity. It's very easy to confuse with the general "is Jetpack" scenario that is also true for atomic sites.

File: client/blocks/image-editor/image-editor-canvas.jsx [hunk 4]
```diff
@@ -305,6 +307,7 @@ export default connect(
 		return {
 			siteSlug,
 			isPrivateAtomic,
```
Comment (tyxla) [inline client/blocks/image-editor/image-editor-canvas.jsx]: This prop and the related selector can now be removed as unused.

File: client/my-sites/media-library/media-file.tsx [hunk 5]
```diff
@@ -55,10 +54,9 @@ const MediaFile: React.FC< MediaFileProps > = function MediaFile( {
 export default connect( ( state: IAppState, { src }: Pick< MediaFileProps, 'src' > ) => {
 	const siteId = getSelectedSiteId( state );
 	const siteSlug = getSelectedSiteSlug( state ) as string;
-	const isAtomic = !! isSiteAutomatedTransfer( state, siteId as number );
-	const isPrivate = !! isPrivateSite( state, siteId ?? 0 );
 	const { filePath, query, isRelativeToSiteRoot } = mediaURLToProxyConfig( src, siteSlug );
-	const useProxy = Boolean( isAtomic && isPrivate && filePath && isRelativeToSiteRoot );
+	const isJetpack = isJetpackSite( state, siteId ?? 0, { treatAtomicAsJetpackSite: false } );
```
Comment (tyxla) [inline client/my-sites/media-library/media-file.tsx]: Instead of doing `isJetpackSite` for `siteId` of `0`, I'd do (keep in mind also the rename I suggested above): 

```suggestion
	const isJetpackNotAtomic = siteId && isJetpackSite( state, siteId, { treatAtomicAsJetpackSite: false } );
```

**Review by tyxla — COMMENTED** [review]
Just to confirm: we want to proxy content for all sites, just not for non-atomic Jetpack sites?

I agree with Marcelo's feedback and left a few more suggestions. 

I think most of those are minor issues though and this can be shipped after addressing our feedback.

**Comment by devicenull** [comment]
> Just to confirm: we want to proxy content for all sites, just not for non-atomic Jetpack sites?

Correct

**Review by tyxla — APPROVED** [review]
LGTM 👍
