### PR TITLE
Show more than 20 first themes on Jetpack.

### LINKED ISSUE #10896: Themes: Only first 20 uploaded themes shown for Jetpack site
A Jetpack site's themes list endpoint doesn't paginate (in slices of 20, which is our default value for WP.com), so we get all themes at once. Something seems to be broken tho since only the first 20 are ever loaded and displayed. One possible culprit is [this](https://github.com/Automattic/wp-calypso/blob/f1647b8ca23ce8a80bf414842879ef707f46e0c5/client/state/themes/selectors.js#L198-L201), but removing it doesn't fix it, so maybe we aren't even storing all themes we're receiving in our ThemeQueryManager.

### PR DESCRIPTION
**Pull request by budzanowski**
### Info
`QueryManager` internals work based on pagination. This works bad with Jetpack themes endpoint that sends all the themes in one batch and does not care about query number.
Because of that we can increase the number in query for Jetpack sites high enough that `QueryManager` will store all the themes.

### Testing
Jetpack site with more than 20 themes installed is needed. Go to `/design` of that Jetpack site and count themes. 

Fixes #10896

### CODE REVIEW

File: client/my-sites/themes/themes-selection.jsx [hunk 1]
```diff
@@ -180,7 +180,7 @@ const ConnectedThemesSelection = connect(
 			page,
 			tier: config.isEnabled( 'upgrades/premium-themes' ) ? tier : 'free',
 			filter: compact( [ filter, vertical ] ).join( ',' ),
-			number: 20
+			number: isJetpack && ! ( queryWpcom === true ) ? 2000 : 20
```
Comment (seear) [inline client/my-sites/themes/themes-selection.jsx]: What happens if we don't specify a `number`?

Comment (budzanowski) [inline client/my-sites/themes/themes-selection.jsx]: Default value of 20 is used, so it does not help, would be cool though.

Comment (ockham) [inline client/my-sites/themes/themes-selection.jsx]: Can we add an inline comment to remind us that this is a hack, and that a more proper solution would be to add pagination (and search, see https://github.com/Automattic/jetpack/pull/2562 for reference) to the Jetpack endpoint?
