### PR TITLE
Themes Showcase: Stop redirects for site slugs beginning with tier slugs.

### LINKED ISSUE #58704: Redirection to themes page from wp-admin dashboard broken
### Quick summary

On a simple site (not reproducible on Atomic sites), clicking on the "Themes" option from wp-admin dashboard redirects to a broken page.

### Steps to reproduce

- Start with a simple WordPress.com site (any WordPress.com site without third-party themes or plugins installed)
- Visit the wp-admin dashboard page, like wp-admin widgets: domain.com/wp-admin/widgets.php?calypsoify=0 
- Click on "Themes" from the left menu.

### What you expected to happen

Themes page loads fine.

### What actually happened

Redirects to a broken page. In my case, these links:

- https://wordpress.com/themeswpcomarun.wordpress.com
- https://wordpress.com/themeswpcomarunblog.wordpress.com

The redirection is visible on network requests panel of dev tools too:

image

image

### Context

Found by manual testing.

### Simple, Atomic or both?

Simple

### Theme-specific issue?

No.

### Browser, operating system and other notes

- Firefox 94.0.2, MacOS 12.0.1.
- Issue is not visible when starting on a different Calypso page like https://wordpress.com/settings/general, it's happening only on visits from wp-admin dashboard.
- Atomic sites are fine.

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No and the platform is unusable

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by kwight**
As part of removing premium themes from the Theme Showcase, a redirect for `/themes/premium` to `/themes` was added in #56430. Unfortunately, this also captures paths with site slugs that begin with `premium`, `free`, or `type`, like `/themes/premiumsite.wordpress.com`, resulting in a 404 after redirecting to `/themessite.wordpress.com`. This PR updates the regex to only remove the tier when followed by nothing, or only a slash (so no following characters that could represent a site domain).

| Production | PR |
| --- | --- |
| Screen Shot 2021-12-08 at 12 48 26 PM | Screen Shot 2021-12-08 at 12 47 59 PM |

Fixes #58704 .

**Testing Instructions**
* Start Calypso locally.
* In a new tab, open the URL `calypso.localhost:3000/themes/premiumsite.wordpress.com`, and notice it forwards to `calypso.localhost:3000/themessite.wordpress.com` (which 404s).
* Switch to this branch.
* Restart Calypso.
* Open `calypso.localhost:3000/themes/premiumsite.wordpress.com` again in a new tab, and verify the redirect doesn't happen (instead, assuming you don't have that site, the site selector will appear).

### CODE REVIEW

**Comment by kwight** [comment]
@Automattic/team-calypso-platform could I ask someone to look at this for me? I'm not very strong with the whole isomorphic testing stuff, and I want to make sure I'm not missing something here. (The original issue notes that the problem only happens on server routing, not within an already-loaded app instance).

**Review by blackjackkent — DISMISSED** [review]

**Comment by jsnajdr** [comment]
This patch has two regressions:
- for path like `/themes/example.blog/type/premium`, it used to remove the entire `/type/premium` suffix, but now it removes only `/premium`, leaving us with invalid `/themes/example.blog/type` path.
- for path like `/themes/premium/filter/three-columns` it will fail to find the `/premium/` part and to redirect to `/themes/filter/three-columns`.

There are still some other edge cases, although much less probable that site slugs, that will cause wrong redirects:
- `/themes/example.blog/search/free` will redirect to `/themes/example.blog/search`, a route that doesn't exist.
- `/themes/example.blog/filter/free` will redirect to `/themes/example.blog/filter`, also doesn't exist.

A more reliable algorithm would be:
- the tier to remove is always in `ctx.params.tier`, so read it from there
- remove the `/:tier/` infix or `/:tier` suffix, but only if it's not preceded by `search/` or `filter/`
- if the `:tier` is preceded by `type/`, remove that together with the tier

**Comment by andres-blanco** [comment]
I've revamped the algorithm to behave better. This might be easier to test on the calypso.live link generated in the comments above.

File: client/my-sites/themes/controller.jsx [hunk 1]
```diff
@@ -114,8 +114,14 @@ export function redirectToThemeDetails( { res, params: { site, theme, section }
...
-	const redirectUrl = originalUrl.replace( /\/(free|premium|type)/g, '' );
+export function redirectTiers( { res, originalUrl, params: { tier } }, next ) {
+	if ( tier === undefined ) {
+		return next();
+	}
+	const typeTierRegex = new RegExp( `/type/${ tier }$`, 'g' );
+	const tierRegex = new RegExp( `/${ tier }(/|$)`, 'g' );
+
+	const redirectUrl = originalUrl.replace( typeTierRegex, '' ).replace( tierRegex, '' );
 	if ( redirectUrl === originalUrl ) {
```
Comment (fullofcaffeine) [inline client/my-sites/themes/controller.jsx]: I think this will never happen, will it? If it reaches this point, it means the URL has a `tier`, and if it has a tier, then it will get removed by this point, and this condition will never be `true`, as the `redirectUrl` will not contain the `tier` (at least) and will be different from the `originalUrl`. Am I right or am I missing something?

**Comment by fullofcaffeine** [comment]
👋🏻 I had a look at this PR today. First of all, thanks for working on it @kwight and @andres-blanco! 🙇🏻 

I took the freedom to add some unit tests and went the extra mile and tried to expand all relevant routes defined in https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/themes/index.node.js to make sure we aren't missing any edge cases. Currently, 4 tests are failing (see https://gist.github.com/fullofcaffeine/c37a677045e42bb80e18a18b235a6f51) and I'll look at them tomorrow if nobody beats me to it. Hopefully, we'll be able to get this approved by then, too!

File: client/my-sites/themes/controller.jsx (hunk 1 above)
Comment (andres-blanco) [reply client/my-sites/themes/controller.jsx]: You are right, it will never happen. Fixing it!

**Comment by andres-blanco** [comment]
@fullofcaffeine thank you so much for adding the tests! it makes a lot of sense for this kind of issues. 

I've fixed the failing tests and removed the unused condition. If you approve those changes and I am not around, feel free to deploy :)

**Review by fullofcaffeine — APPROVED** [review]
This is testing well!

File: client/my-sites/themes/controller.jsx [hunk 2]
```diff
@@ -114,11 +114,17 @@ export function redirectToThemeDetails( { res, params: { site, theme, section }
...
-export function redirectTiers( { res, originalUrl }, next ) {
-	const redirectUrl = originalUrl.replace( /\/(free|premium|type)/g, '' );
-	if ( redirectUrl === originalUrl ) {
+export function redirectTiers( { res, originalUrl, params: { tier } }, next ) {
+	if ( tier === undefined ) {
 		return next();
 	}
 
+	const typeTierRegex = new RegExp( `/type/${ tier }$`, 'g' );
+	const inlineOrPostfixTierRegex = new RegExp( `(?<=/)${ tier }/|/${ tier }$`, 'g' );
```
Comment (jsnajdr) [inline client/my-sites/themes/controller.jsx:123]: just a little nit: the second regexp can be shortened to `(?<=/)${ tier }(/|$)`, matching both the infix and suffix version at once. Also, neither regexp should need the `g` flag, as there's always at most one match.

Comment (andres-blanco) [reply client/my-sites/themes/controller.jsx:123]: 👋 If the second regexp is shortened then urls like `en/themes/premium` would be rewritten to `en/themes/` instead of `en/themes`. I've added the extra condition to catch the trailing slash.

I will make a PR for removing the `g` flag.

Comment (andres-blanco) [reply client/my-sites/themes/controller.jsx:123]: https://github.com/Automattic/wp-calypso/pull/59676

Comment (jsnajdr) [reply client/my-sites/themes/controller.jsx:123]: You're right, I didn't notice that the `(?<=/)` part is not common for both variants.
