### PR TITLE
Tailored flows: LIB - Limit site logo size to 512px so it fits in localStorage

### LINKED ISSUE #66980: [Bug]: tailored flows: can't upload big image
### Quick summary

Can't upload big images as logo/avatar for link-in-bio and newsletter.

### Steps to reproduce

1. Start newsletter flow https://horizon.wordpress.com/setup/?flow=newsletter
2. Upload big image file as a logo
3. 
    Screenshot 2022-08-25 at 14 27 59

4. Note error at console when pressing continue
5. 
    Screenshot 2022-08-25 at 14 27 20

### What you expected to happen

Big images to work or at least error gracefully.

### What actually happened

UI froze, no way to continue.

How is this stored, are is that storage available in incognito mode?

### Browser

_No response_

### Context

_No response_

### Platform (Simple, Atomic, or both?)

_No response_

### Other notes

_No response_

### Reproducibility

Consistent

### Severity

_No response_

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by alshakero**
#### Proposed Changes

* localStorage is slow and limited, and since we're storing the site icon in it for a while, picking a big image is breaking the site setup step.
* This limits the image width to 512px, and since the aspect ratio is set to 1:1, the height as well. 

#### Testing Instructions

1. Go to /setup?flow=link-in-bio.
2. Pick a large image (maybe a screenshot).
3. Crop a big square out of it.
4. Inspect the icon preview and visit the URL of the image set to it. 
5. It should have 512x512 size.

Fixes #66980

### CODE REVIEW

File: client/blocks/image-editor/image-editor-canvas.jsx [hunk 1]
```diff
@@ -175,7 +178,17 @@ export class ImageEditorCanvas extends Component {
...
+			const scale = widthLimit / croppedWidth;
+			resizedCanvas.width = scale * croppedHeight;
+			resizedCanvas.height = scale * croppedWidth;
+			const resizedContext = resizedCanvas.getContext( '2d' );
+			resizedContext.drawImage( newCanvas, 0, 0, scale * croppedWidth, scale * croppedHeight );
+			canvasToBlob( resizedCanvas, callback, mimeType, 1 );
+		} else {
+			canvasToBlob( newCanvas, callback, mimeType, 1 );
+		}
 	}
```
Comment (alshakero) [inline client/blocks/image-editor/image-editor-canvas.jsx:192]: To avoid complexity, I only introduced width limitation.

**Comment by ebinnion** [comment]
I believe that this will fix #66980

**Comment by heavyweight** [comment]
Screenshot 2022-08-26 at 12 12 48
Finally managed to reproduce the issue on trunk testing the fix now..

**Review by heavyweight — APPROVED** [review]
great stuff!!
