### PR TITLE
Fixed Navigation Header

### LINKED ISSUE #57101: Marketplace: New Plugins page header
### What

Update the Plugins header

### Why

Following the new Marketplace Designs (oU6nEIeiKSg8CayhEtgR6b-fi-6693%3A53273) we will need to update the header components and styles.

- [ ] Styling
- [x] Move search component to header
- [x] Rename "Install Plugin" to "Upload" and add the icon
- [ ] Navigation Breadcrumbs

|Before | After|
|-------|------|
|||

### How

_No response_

### PR DESCRIPTION
**Pull request by cpapazoglou**
#### Changes proposed in this Pull Request

* introduces a new Fixed Navigation Header component.
* uses it in plugin browser

#### Testing instructions

|Before | After|
|-------|------|
|SS 2021-10-28 at 19 08 58|SS 2021-10-28 at 19 08 26|

* Go to `/plugins`
* Inspect that the header:
-- is remaining sticky to the top
-- items are positioned as per designs

Out of scope:
- `font-family`, we need to discuss with the design team whether we are changing the font-family in all pages or only here
- navigation will be handled in https://github.com/Automattic/wp-calypso/pull/57442

Fixes #57101

### CODE REVIEW

File: client/components/fixed-navigation-header/docs/example.jsx [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+
+	render() {
+		return (
+			<Fragment>
+				<FixedNavigationHeader headerText="This is the header." />
+				<FixedNavigationHeader headerText="This is the header with branded font" brandFont />
+			</Fragment>
+		);
+	}
+}
```
Comment (WBerredo) [inline client/components/fixed-navigation-header/docs/example.jsx]: Nitpicking: What do you think about adding this example component as a functional one? Considering this is the path we want to reach in the future.

```js
export default function FixedNavigationHeaderExample () {
	const displayName = 'FormattedHeaderExample'; // do we use this?

	return (
		<Fragment>
			<FixedNavigationHeader headerText="This is the header." />
			<FixedNavigationHeader headerText="This is the header with branded font" brandFont />
		</Fragment>
	);
}

```

File: client/components/fixed-navigation-header/index.tsx [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+const Header = styled.header`
+	position: fixed;
+	z-index: 1;
+	top: var( --masterbar-height );
+	left: var( --sidebar-width-max );
+	width: calc( 100% - var( --sidebar-width-max ) );
+	padding: 0 32px;
+	box-sizing: border-box;
+	border-bottom: 1px solid var( --studio-gray-5 );
+	background-color: #fff;
```
Comment (WBerredo) [inline client/components/fixed-navigation-header/index.tsx]: We do have a variable called ` --studio-white` that could be used here:

```css
background-color: var( --studio-white )
```

File: client/my-sites/plugins/main.jsx [hunk 3]
```diff
@@ -402,29 +401,17 @@ export class PluginsMain extends Component {
...
 				<SidebarNavigation />
-				<div className="plugins__main">
-					<div className="plugins__header">
-						<FormattedHeader
-							brandFont
-							className="plugins__page-heading"
-							headerText={ this.props.translate( 'Plugins' ) }
-							align="left"
-							subHeaderText={ this.props.translate(
-								'Add new functionality and integrations to your site with plugins. {{learnMoreLink}}Learn more{{/learnMoreLink}}.',
```
Comment (WBerredo) [inline client/my-sites/plugins/main.jsx:413]: Question: Won't we have this text anymore on the new layout?

**Review by WBerredo — COMMENTED** [review]
In general, it seems good, well done 🥳

Just added some smaller points to discuss on the review.

File: client/my-sites/plugins/main.jsx (hunk 3 above)
Comment (cpapazoglou) [reply client/my-sites/plugins/main.jsx:413]: Good question ;-), can't find the decision right now but we have discussed with @JanaMW27 that we won't have a subheader description any more.

File: client/components/fixed-navigation-header/index.tsx (hunk 2 above)
Comment (cpapazoglou) [reply client/components/fixed-navigation-header/index.tsx]: Great catch! Fixed in 5f46a81

File: client/components/fixed-navigation-header/docs/example.jsx (hunk 1 above)
Comment (cpapazoglou) [reply client/components/fixed-navigation-header/docs/example.jsx]: oh 🤦 , that was a copy - paste remnant!  Fixed in e3849ba

Re `displayName`, no we shouldn't need it https://reactjs.org/docs/react-component.html#displayname
