### PR TITLE
Fix focusOnHover doesn't work on CopyLink

### LINKED ISSUE #55103: Calyspo Posts: Multiple items highlighted on sub-menu
#### Steps to reproduce

1. Go to My Site (Calypso/Unified nav)
2. Go to Posts section
3. Click on three dots to the right of a certain post (which opens a drop-down sub-menu)
4. Hold cursor over different sub-menu items
5. When going from a couple menu items to others, multiple lines will highlight at the same time (see below)

#### What I expected

Only one sub-menu item is highlighted at a time (the one my cursor is hovering on)

#### What happened instead

When going from "Copy post" -to-> "Copy link" , both sub-menu items end up highlighted simultaneously.

Also when going from "Trash" -to-> "Copy link" , both sub-menu items end up highlighted simultaneously.

#### Browser / OS version

Browser: Version 91.0.4472.164 (Official Build) (x86_64)
OS: Mac Big Sur 11.5

#### Screenshot / Video

https://user-images.githubusercontent.com/37377834/127888439-24b9153e-092c-4e76-a493-38000cd30188.mov

#### Context / Source

If it helps, this was seen on multiple, internal-a8c p2's - but also a test atomic site I have.

### PR DESCRIPTION
**Pull request by arthur791004**
#### Changes proposed in this Pull Request

* `focusOnHover` doesn't work on `CopyLink` component, so if the user is going from copy link to others or from others to copy link, the focus element is the same as the previous one. Therefore, the user will see highlights on multiple items at the same time.

https://user-images.githubusercontent.com/13596067/128664409-e508bc70-03ab-474b-b57d-2145e41faa1f.mov

#### Testing instructions

* Go to My Site (Calypso/Unified nav)
* Go to Posts section
* Click on three dots to the right of a certain post (which opens a drop-down sub-menu)
* Hold cursor over different sub-menu items
* When going from copy link to others or from others to copy link, make sure only one item will highlight at the same time

Close https://github.com/Automattic/wp-calypso/issues/55103

### CODE REVIEW

**Comment by jordesign** [comment]
Can confirm this PR works well for me in Chrome + Safari!

File: client/components/popover/menu-item-clipboard.jsx [hunk 1]
```diff
@@ -1,31 +1,26 @@
...
 import React from 'react';
 import ClipboardButton from 'calypso/components/forms/clipboard-button';
-import Gridicon from 'calypso/components/gridicon';
+import PopoverMenuItem from './menu-item';
 
 const noop = () => {};
 
 function PopoverMenuItemClipboard( {
-	children,
 	className,
```
Comment (roo2) [inline client/components/popover/menu-item-clipboard.jsx:9]: The className property can also be removed, since nowhere currently uses className and it would be passed along to PopoverMenuItem with `...rest` anyway

Comment (roo2) [reply client/components/popover/menu-item-clipboard.jsx:9]: I'd probably leave `children` on as an explicit property just to make it clear that calling code should pass in children.

**Review by roo2 — COMMENTED** [review]
I have a small thing about properties but it looks good and tested well 👍

File: client/components/popover/menu-item-clipboard.jsx (hunk 1 above)
Comment (p-jackson) [reply client/components/popover/menu-item-clipboard.jsx:9]: I was thinking the same thing about how the `children` prop is kinda like documentation for how to use the component.

**Comment by p-jackson** [comment]
The fact that these components change the focus on mouse over is blowing my mind 🤯. It seems pretty hostile to keyboard navigation. If your navigating in one region of the page, and then wiggle your mouse, it could change the whole flow of where you are on the page.

:sigh: Unfortunately the `<PopoverMenuItem>` component is used in so many places, removing that behaviour would be a huge effort to test. For example this usage of the component is explicitly doing something when the focus changes, which means it currently does the thing on hover too. Who knows how many other things would depend on behaviour like this.
https://github.com/automattic/wp-calypso/blob/0d81079343423c020ef44b6729199065a5254d4e/client/my-sites/post-type-list/post-actions-ellipsis-menu/edit.jsx#L30

I guess what I'm saying is that it's regrettable focus is being used like this, but it's probably the right fix for now.

**Comment by p-jackson** [comment]
Ah nuts the git history doesn't provide any clues about why it behaves this way because it was like this when the code was originally committed:
https://github.com/automattic/wp-calypso/blame/7b2f9b292d86f1cde60311759e94ecba0c38499f/client/components/popover/menu-item.jsx#L12

File: client/components/popover/menu-item-clipboard.jsx (hunk 1 above)
Comment (arthur791004) [reply client/components/popover/menu-item-clipboard.jsx:9]: I leave both children and className on as an explicit property and also add children to propTypes!

**Comment by arthur791004** [comment]
@p-jackson Yeah, I agreed and it's not easy to remove now 😞

**Review by roo2 — APPROVED** [review]
LGTM :shipit:

**Review by p-jackson — APPROVED** [review]
