### PR TITLE
Stepper: avoid WSOD when visiting non-existing flows

### LINKED ISSUE #100397: Stepper: WSOD when non-existing flow is specified
## What

To reproduce:

- Visit `/setup/non-existing-flow?siteSlug=[SITE_SLUG]`
- Notice that the browser gets stuck on an empty page, no errors shown

## Why

This was first found in https://github.com/Automattic/wp-calypso/pull/100159#issuecomment-2681713307

In short, this is what's currently happening on `trunk`:

- The Stepper framework parses the flow slug from the URL;
- When the parsed slug can't be matched against an existing flow, [it falls back to the `site-setup` flow](https://github.com/Automattic/wp-calypso/blob/d690cde7d5b830eb2830f156a1eed459999bada6/client/landing/stepper/index.tsx#L61-L65)
  - _NOTE: the window URL is not changed, even if Stepper performs something akin to a redirect_
- If a `siteSlug` (or a `siteId`) is not provided via the query string, [the `site-setup` flow would redirect to home](https://github.com/Automattic/wp-calypso/blob/c84d88e4f87f9db0aae1b0ff4bf75a054c2cb195/client/landing/stepper/declarative-flow/site-setup-flow.ts#L634-L640), but in the case of https://github.com/Automattic/wp-calypso/pull/100159, the `siteSlug` was being provided — which triggered the discovery of this bug;
- [Stepper's internal router](https://github.com/Automattic/wp-calypso/blob/c84d88e4f87f9db0aae1b0ff4bf75a054c2cb195/client/landing/stepper/declarative-flow/internals/index.tsx#L238-L260) can't match the current URL to any of the current flow steps, and therefore the router matches the fallback route
- The fallback route doesn't know that there is a mismatch between the URL and the fallback flow "chosen" by Stepper framework, and therefore [it redirects to the same non-existing flow URL](https://github.com/Automattic/wp-calypso/blob/420e3b8b600b2d4393412e5e60954122fa2e63fa/client/landing/stepper/declarative-flow/internals/components/redirect-to-step/index.tsx#L15-L19), causing the application to be stuck on a WSOD

## Expected behavior / Proposed solution

It feels like this bug has been dormant, and the only reason why it wasn't found earlier is because it can only be triggered when `siteSlug` or `siteId` are provided via the query string, and otherwise `site-setup` redirects to the `home` page.

@alshakero [shared some extra context](https://github.com/Automattic/wp-calypso/pull/100159#issuecomment-2681977859):

> Yes, that behavior is basically a relic of the past. When Stepper started, it only had a single flow, the `site-setup` flow, so [/start redirected to the setup only](https://github.com/Automattic/wp-calypso/blob/9c212119148f81e4a2f099c96f7a5ff726cb18cc/client/signup/config/flows.js#L102) and still does! When we added the ability to add more flows, we added this trick for backwards compat. The intention was to handle the lack of flow, not the wrong flow. That's why you get this WOSD.

Omar also proposed a fix:

- Change the `/start` signup framework to redirect to `/setup/site-setup`
- Change the Stepper framework to redirect to `/setup/onboarding` when the flow slug parsed from the URL doesn't match any of the existing flows.

### PR DESCRIPTION
**Pull request by ciampo**
Fixes https://github.com/Automattic/wp-calypso/issues/100397

## Proposed Changes

* Change the default "destination url" for Signup flows from `/setup` to `/setup/site-setup`
* Change how stepper handles URLs containing a flow slug that doesn't match any existing flows:
  * the fallback flow changes from `/setup/site-setup` to `/setup/onboarding`
  * the navigation to the fallback flow is done with a full page refresh, instead of only rendering the fallback flow without changing the URL of the page

## Why are these changes being made?

- To address the WSOD bug described in https://github.com/Automattic/wp-calypso/issues/100397
- The Signup behavior doesn't really change in practice: redirecting to `/setup` was already causing the `/setup/site-setup` flow to render
- The added redirect in Stepper makes sure that the framework doesn't end up in a state where the URL and the flow being rendered don't match.
- Having the `/setup/onboarding` flow being the fallback flow is more aligned with the recent flows changes.

## Testing Instructions

* Visit the `/start/premium` signup flow. Make sure that, after the flow is completed, the user is correctly redirected to the `/setup/site-setup` flow, as it also happens on `trunk`
* Visit `/setup?siteSlug=[SITE_SLUG]`:
  * On `trunk`, the user is re-directed to the `/setup/site-setup` flow
  * On this PR, the user is re-directed to the `/setup/onboarding` flow
* Visit `/setup/non-existing-flow?siteSlug=[SITE_SLUG]`:
  * On `trunk`, the user sees a WSOD
  * On this PR, the user is re-directed to the `/setup/onboarding` flow
* Visit `/setup/site-setup?siteSlug=[SITE_SLUG]` (or any other valid Stepper flows), and make sure that the flow works as on `trunk`

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by alshakero — APPROVED** [review]
Tested an incorrect flow, a correct flow, and tested /start/premium and everything works great. Thank you!

File: client/landing/stepper/index.tsx [hunk 1]
```diff
@@ -58,16 +59,11 @@ function initializeCalypsoUserStore( reduxStore: any, user: CurrentUser ) {
 	reduxStore.dispatch( setCurrentUser( user ) );
 }
 
-function determineFlow() {
-	const flowNameFromPathName = window.location.pathname.split( '/' )[ 2 ];
```
Comment (ciampo) [inline client/landing/stepper/index.tsx:62]: No need to keep this check, since a similar (but more refined) logic is already being used when invoking `getFlowFromURL`

File: client/landing/stepper/index.tsx [hunk 2]
```diff
@@ -95,14 +91,17 @@ async function main() {
 	}
 
 	const flowName = getFlowFromURL();
-	const siteId = getSiteIdFromURL();
+	const flowLoader = availableFlows[ flowName ];
 
-	if ( ! flowName ) {
-		// Stop the boot process if we can't determine the flow, reducing the number of edge cases
-		return ( window.location.href = `/setup/${ DEFAULT_FLOW }${ window.location.search }` );
+	if ( ! flowLoader ) {
```
Comment (ciampo) [inline client/landing/stepper/index.tsx:96]: Checking `flowLoader` instead of `flowName`, since if `flowName` is empty string or even `null` / `undefined`, `flowLoader` will be `undefined`.

**Comment by tyxla** [comment]
Nice fix!
