### PR TITLE
Editor: Fix tags bug by using correct container for blur event

### LINKED ISSUE #1884: Editor: cannot select tags by clicking on list of previously used tags
After the update to v 1.2.1 a user in 678123-f reported a problem with tag selection in the post editor.

Tags cannot be selected by clicking on the list of previously used tabs using a mouse. Clicking on a tag merely causes the drop-down to collapse without adding the tag.

selecting tags
Adding tags by typing their names still works, though.

I tested this using the Mac version, but the user who reported this happening is using the Windows version.

Initially reported this in https://github.com/Automattic/wp-desktop/issues/28, but @lancewillett pointed out that it might be a Calypso issue, rather than specific to the app.

I confirmed that the problem also exists Chrome 47.0.2526.106 and Safari 9.0.2, but not in Firefox 43.0.1

Possibly related to #1814

### PR DESCRIPTION
**Pull request by nylen**
Fixes #1884, and other strange behavior, which I suspect is also related to the following forum threads:

- https://en.forums.wordpress.com/topic/problem-with-adding-new-tags#post-2517598 (partly)
- https://en.forums.wordpress.com/topic/i-am-not-able-to-add-tags-anymore-what-is-going-on

| Chrome | Safari |
|---|---|
| The tag suggestion list flickers when you select a tag, and sometimes the tag you select doesn't get added. <br />  | The tag suggestion list disappears when you select a tag, and sometimes the tag you select doesn't get added. <br />  |

The reason this code change fixes these issues is that the `blur` event target is usually the text input, but we need to check the entire TokenField container for the `relatedTarget` instead.  Looks like this was changed [here](https://github.com/Automattic/wp-calypso/commit/e511e6fad78e4e0acb489535edcac7ad479f6e15#diff-ace89b667e7bd9a57e091cdd09278e63L129) - cc @aduth.

### To test

- Go to the editor and add tags to posts.
- See if you can reproduce #1884 (failure to add tags via the mouse) or either of the strange behaviors in the recordings above.
- Apply this patch and verify that all your problems go away.

### CODE REVIEW

File: client/components/token-field/index.jsx [hunk 1]
```diff
@@ -81,7 +91,8 @@ var TokenField = React.createClass( {
 					scrollIntoView={ this.state.selectedSuggestionScroll }
 					isExpanded={ this.state.isActive }
 					onHover={ this._onSuggestionHovered }
-					onSelect={ this._onSuggestionSelected } />
+					onSelect={ this._onSuggestionSelected }
+				/>
```
Comment (timmyc) [inline client/components/token-field/index.jsx]: I just had the linter warn me on a branch that the closing tag should be on the same line as the last prop.  This was "new" to me, but figured I'd mention it here too.

**Comment by ralder** [comment]
Also for Firefox and IE11 there need using in _onBlur handler instead `event.relatedTarget` 
```javascript
 var relatedTarget = event.relatedTarget ||
            event.explicitOriginalTarget || // FF
            document.activeElement; // IE11
```

details about it https://github.com/facebook/react/issues/2011

File: client/components/token-field/index.jsx (hunk 1 above)
Comment (aduth) [inline client/components/token-field/index.jsx]: >I just had the linter warn me on a branch that the closing tag should be on the same line as the last prop.

I believe this only applies to self-closing tags, and was added in #1807.

**Comment by aduth** [comment]
I can confirm that `event.target` was indeed the culprit. Using [`event.currentTarget`](https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget) would be an alternative fix, though I think the changes here are more explicit.

Marking as needs changes per linting error.

File: client/components/token-field/index.jsx (hunk 1 above)
Comment (nylen) [inline client/components/token-field/index.jsx]: I'm strongly in favor of putting the `/>` (and even the `>` for tags with children) on the following line, de-indented 1 level:

- Like the `);` and `};` immediately below, it denotes the end of a block
- Easier to rearrange props, like trailing `,` in arrays

We have lots of code in both styles in Calypso.  If we want to do something about this, let's remove that linter rule instead.

**Comment by nylen** [comment]
Thanks for the tip @raider!  I needed to use `event.nativeEvent.explicitOriginalTarget` instead but your suggestion fixes #1814.  This is now ready for review again.

**Comment by nylen** [comment]
Fixed the failing tests - looks like it's due to a React TestUtils bug (reported at facebook/react#5778).

**Comment by aduth** [comment]
Looks good to me :+1: 

Two things to follow-up on:
- Let's not just leave the lint warning, and submit either an issue or pull request to remove the linting rule
- Should tags that are already added not be shown in the available suggestions? Do we have an issue tracking this?

**Comment by nylen** [comment]
- Done at https://github.com/Automattic/wp-calypso/pull/2126.
- I noticed that too but haven't investigated yet - I'll fix it in a separate PR.
