### PR TITLE
Plugin Details: Show all sites on multi-site view

### LINKED ISSUE #83536: Plugin Details Multi-site: List all sites and add an Upgrade to Purchase option
Parent task: https://github.com/Automattic/wp-calypso/issues/81713

### LINKED ISSUE #88730: Plugin Details Multi-site: Add eligibility information for non-atomic sites
Related to https://github.com/Automattic/wp-calypso/pull/88696

Add Eligibility Data when clicking to install plugins on non-atomic sites. On the Plugin Details view for a given site, a modal is displayed with this information. 

We should check a good way to display this considering we already have a modal open for the `Manage Sites` area.

## How to reproduce

* Go to a the Plguins Details Multi-site view: `/plugins/:plugin-slug`
* Click on `Manage Sites`
* Look for a non-atomic site and click on `Upgrade and Activate`

Image

* Currently the user is redirected to the cart, but the user should be warned somehow that the domain will change

### PR DESCRIPTION
**Pull request by WBerredo**
Fixes https://github.com/Automattic/wp-calypso/issues/83536
Fixes https://github.com/Automattic/wp-calypso/issues/88730

## Proposed Changes

Show all sites on the Manage Sites option on the multi-site view. Now even non-atomic sites and sites with plan below than Creator will be shown:

* On cases where the user will not be able to install the plugin directly, the CTA will present the `Go to plugin page`  text. After this redirect, the user should be able to install the plugin as a normal single site installation.
* The atomic sites will be displayed before the non-atomic ones.

CleanShot 2024-04-11 at 14 27 23@2x

## Testing Instructions

**DotOrg Plugins**
* Go to the Plugin Details page for a free plugin without a specified site. Ex: `/plugins/mailpoet`
* Click on `Manage sites`
* Click on `Install` for Business already atomic sites, the installation should be completed.
* Click on `Go to plugin page` and you should be redirected to the plugin page with the site selected, the installation should be completed as well.

**Marketplace Plugins**
* Go to the Plugin Details page for a Marketplace plugin without a specified site. Ex: `/plugins/woocommerce-subscriptions
* Click on `Manage sites`
* Click on `Purchase and activate` and you should be redirected to the cart with the plugin
* Click on `Upgrade and activate` and you should be redirected to the cart with the plugin and the Business Plan.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by epeicher — APPROVED** [review]
I have tested it, and it works as advertised. LGTM! :shipit: 

##### Free plugin
- ✅ Tested on Creator atomic
- ✅ Tested on Creator non-atomic
- ✅ Tested on Explorer non-atomic

##### Marketplace plugin
- ✅ Tested on Creator atomic
- ✅ Tested on Creator non-atomic
- ✅ Tested on Explorer non-atomic

File: client/my-sites/plugins/manage-site-plugins-dialog/index.jsx [hunk 1]
```diff
@@ -21,8 +19,10 @@ export const ManageSitePluginsDialog = ( { isVisible, onClose, plugin } ) => {
 	const sitesWithPlugin = useSelector( ( state ) =>
 		getSiteObjectsWithPlugin( state, siteIds, plugin.slug )
 	);
-	const sitesWithoutPlugin = useSelector( ( state ) =>
-		getSiteObjectsWithoutPlugin( state, siteIds, plugin.slug )
+
+	const sites = useSelector( getSelectedOrAllSites );
```
Comment (Aurorum) [inline client/my-sites/plugins/manage-site-plugins-dialog/index.jsx:23]: May I suggest sorting the list of sites that appear so all Atomic sites appear before Free sites? This is a bit of a nuisance because there's no Search for this dialog, and a user can have a lot of sites, whereas I think most users would be looking first for their Atomic sites. 

Just an idea I had when testing - feel free to ignore if you think it doesn't make sense. :)

**Comment by WBerredo** [comment]
Fixing #88730 on https://github.com/Automattic/wp-calypso/pull/88696/commits/f954cfd4cc9dcb081c9c8936cd90f4dee7951855

File: client/my-sites/plugins/manage-site-plugins-dialog/index.jsx (hunk 1 above)
Comment (WBerredo) [reply client/my-sites/plugins/manage-site-plugins-dialog/index.jsx:23]: Good idea, I have added it here https://github.com/Automattic/wp-calypso/pull/88696/commits/c306c2cf9767b0ef1d29f8e06fc90b08f3e42699

**Review by epeicher — APPROVED** [review]
I like the approach of simply redirecting to the Plugin page to display the Eligibiilty Modal 👍 
I have tested all the scenarios and they work as expected. Changes LGTM! :shipit: 

###### Free plugin
✅ Tested on Creator atomic
✅ Tested on Creator non-atomic
✅ Tested on Explorer non-atomic
 
###### Marketplace plugin
✅ Tested on Creator atomic
✅ Tested on Creator non-atomic
✅ Tested on Explorer non-atomic
