### PR TITLE
Related Post Settings: Add Notice

### LINKED ISSUE #30711: Related posts setting: sync copy with Jetpack
Related posts settings missing note about block editor:

> _The following settings will impact all related posts on your site, except for those you created via the block editor:_

Other small disparity as well and unexpected Jetpack link for wpcom.

See https://github.com/Automattic/jetpack/issues/11021#issuecomment-453205072

### In Jetpack 7.0:

screenshot 2019-02-11 at 23 16 23

image

Links to https://jetpack.com/support/related-posts/

### Currently in Calypso:

screenshot 2019-02-11 at 23 16 59
screenshot 2019-02-11 at 23 17 09

Also links to https://jetpack.com/support/related-posts/ instead of https://en.support.wordpress.com/related-posts/ as I expected.

### PR DESCRIPTION
**Pull request by torres126**
#### Changes proposed in this Pull Request

* ~~Change the link from the Jetpack support document to the dedicated WordPress.com one~~
* Add a copy identical to Jetpack's one about Gutenberg's impact using Form Explanation 

#### Testing instructions

Compare at `/settings/traffic/site` that everything looks as expected. 

fdgsfsgdfsgdgfs

(cc @simison, @tyxla, @eliorivero) 

Fixes #30711

### CODE REVIEW

File: client/my-sites/site-settings/related-posts/index.jsx [hunk 1]
```diff
@@ -40,8 +40,14 @@ const RelatedPosts = ( {
 						text={ translate(
 							'Automatically displays similar content (related posts) at the end of each post.'
 						) }
-						link="https://jetpack.com/support/related-posts/"
+						link="https://en.support.wordpress.com/related-posts/"
 					/>
+					
+					<p className="related-posts__explanation">
```
Comment (thomasguillot) [inline client/my-sites/site-settings/related-posts/index.jsx]: We should be using `FormSettingExplanation` here rather than creating a new class with its own CSS.

E.g.:

https://github.com/Automattic/wp-calypso/blob/859538b6860ab398a7d0851a060637ea46fdc9b5/client/my-sites/site-settings/sitemaps.jsx#L75-L79

Comment (roccotripaldi) [reply client/my-sites/site-settings/related-posts/index.jsx]: Do you know if we still plan to move the SDK to the Jetpack repo?
If that's the case, we may want to refrain from importing any calypso components.

Comment (tyxla) [reply client/my-sites/site-settings/related-posts/index.jsx]: I think we should be fine to use calypso components, this is the settings section and AFAIK we're not publishing it anywhere else yet. It would be different if that was a Gutenberg block for example 😉

Comment (roccotripaldi) [reply client/my-sites/site-settings/related-posts/index.jsx]: thanks for clarifying @tyxla

File: client/my-sites/site-settings/related-posts/index.jsx [hunk 2]
```diff
@@ -40,8 +40,14 @@ const RelatedPosts = ( {
 						text={ translate(
 							'Automatically displays similar content (related posts) at the end of each post.'
 						) }
-						link="https://jetpack.com/support/related-posts/"
+						link="https://en.support.wordpress.com/related-posts/"
```
Comment (tyxla) [inline client/my-sites/site-settings/related-posts/index.jsx]: Hmm, I don't think we should change these links so lightly. While it makes sense to link to the WP.com support doc for WP.com sites, it also makes sense to link to the Jetpack one for Jetpack sites. 

What do you think about conditionally defining the link URL based on the site type? 

Note: let's not forget about properly handling it for atomic sites too 😉

Comment (tyxla) [inline client/my-sites/site-settings/related-posts/index.jsx]: Do we want to hardcode the `en.` locale here? I think we could avoid that.

File: client/my-sites/site-settings/related-posts/index.jsx [hunk 3]
```diff
@@ -40,8 +40,14 @@ const RelatedPosts = ( {
...
 					/>
+					
+					<p className="related-posts__explanation"> 
+						{ translate( 
+							'The following settings will impact all related posts on your site, except for those you created via the block editor:'
```
Comment (tyxla) [inline client/my-sites/site-settings/related-posts/index.jsx]: Did we run `prettier` here? This line seems a bit too long.

File: client/my-sites/site-settings/related-posts/style.scss [hunk 4]
```diff
@@ -1,3 +1,9 @@
+.related-posts__explanation {
```
Comment (tyxla) [inline client/my-sites/site-settings/related-posts/style.scss]: This should be unnecessary if we use `<FormSettingExplanation />`.

File: client/my-sites/site-settings/related-posts/index.jsx (hunk 2 above)
Comment (simison) [reply client/my-sites/site-settings/related-posts/index.jsx]: Yup, `https://support.wordpress.com/related-posts/` seems to work 👍

Comment (simison) [reply client/my-sites/site-settings/related-posts/index.jsx]: While that's a nice feature to have, it might be better for another PR?

The vast majority of anyone looking at this setting will be wpcom customers/sites so if I'd have to pick one, wpcom one seems appropriate?

Comment (tyxla) [reply client/my-sites/site-settings/related-posts/index.jsx]: Well, you said it - it might be better for another PR. Why are we even changing the URL in this PR - isn't this PR supposed to be solely for adding the explanation?

So, I suggest that we do the link change and the corresponding discussion in another PR. This has always led to jetpack, and changing it could use some feedback.

Comment (simison) [reply client/my-sites/site-settings/related-posts/index.jsx]: Certainly! Valid points.

File: client/my-sites/site-settings/related-posts/index.jsx (hunk 3 above)
Comment (scruffian) [reply client/my-sites/site-settings/related-posts/index.jsx]: What do you think about:

"These settings won't apply to related posts added using the block editor."

File: client/my-sites/site-settings/related-posts/index.jsx (hunk 2 above)
Comment (torres126) [reply client/my-sites/site-settings/related-posts/index.jsx]: It was changed in this PR to address that point in the original issue, but agreed that it's a change outside this PR. It's not a huge deal in terms of the information conveyed on that page either. :)

Comment (torres126) [reply client/my-sites/site-settings/related-posts/index.jsx]: Switched link back to current.

File: client/my-sites/site-settings/related-posts/index.jsx (hunk 3 above)
Comment (torres126) [reply client/my-sites/site-settings/related-posts/index.jsx]: Yeah, I feel like that wording is clearer anyway, switched to it.

File: client/my-sites/site-settings/related-posts/index.jsx (hunk 1 above)
Comment (torres126) [reply client/my-sites/site-settings/related-posts/index.jsx]: Nice, didn't know that! Switched to that now and updated the PR description. (I'm assuming it should be beneath the actual settings because that's what it seems to do each time it's used so far)

File: client/my-sites/site-settings/related-posts/index.jsx (hunk 3 above)
Comment (tyxla) [reply client/my-sites/site-settings/related-posts/index.jsx]: Note that if we change this, we'll need to also change it in Jetpack for consistency (cc @jeherve): https://github.com/Automattic/jetpack/blob/14f5c658d035af51538bdeeb43b6c4601111a541/_inc/client/traffic/related-posts.jsx#L71

**Comment by torres126** [comment]
Added a margin (see updated description) and PR at Automattic/jetpack#11342 for that. :+1:

File: client/my-sites/site-settings/related-posts/index.jsx (hunk 3 above)
Comment (jeherve) [reply client/my-sites/site-settings/related-posts/index.jsx]: I've just merged the Jetpack part of this. 👍 	
https://github.com/Automattic/jetpack/pull/11342
