### PR TITLE
ETK: Restrict HEIC image uploads

### LINKED ISSUE #55102: HEIC Image Uploads
### Steps to reproduce the behavior

1. From a Mac computer, go to your iCloud Photo library in a browser
2. Click on some images and use the download icon to download images.
3. Open the folder, images are saved into HEIC format. 
4. Open WordPress.com in a browser to create a new post and add an image block. 
5. Select the option to upload media and use the downloaded HEIC images
6. You'll see an error message in the editor `This image has an empty alt attribute; its file name is IMG_0574.heic`
7. Navigate to the Media Library and the image displays there but in HEIC format

#### What I expected to happen

If the image can't be uploaded, it shouldn't be in the media library. It's also very confusing for users who then end up with multiple images in their media library in HEIC format that cannot be inserted into their posts. 

Using the mobile app, the HEIC files are automatically converted to JPEG making image uploads from iOS devices easy. 

#### What actually happened

The images show in the media library, fail to upload and the process to convert them is quite confusing. It's very time consuming to have to convert manually each image to a different format. 

I have had a number of chats where this comes up and guiding the user on steps to convert image formats is not ideal and something we should either do automatically or block the uploads with a clearer error message. 

### Context

Chat: 30911034-hc

#### Browser / OS version

Any Mac/browser combo will give you the same effect. 

#### Is this specific to the applied theme? Which one?

No

#### Does this happen on simple or atomic sites or both?

Both (HEIC image file type is not supported)

#### Is there any console output or error text?

This image has an empty alt attribute; its file name is IMG_0574.heic

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Makes image uploads very inconvenient for Mac users with HEIC image formats.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Image 2021-08-02 at 4 38 42 pm
Image 2021-08-02 at 4 39 04 pm

### PR DESCRIPTION
**Pull request by sixhours**
#### Changes proposed in this Pull Request

* Prevent users from uploading HEIC images via drag and drop to media areas, patching a bug in Gutenberg (see https://github.com/WordPress/gutenberg/issues/34181)
* Filters `MediaPlaceholder` to check the file type with `onFilesPreUpload`
* This is for Atomic sites, as HEIC uploads fail on drag-and-drop for Simple sites because we don't allow that file format.
* Throwing an error feels extreme 😬 but I'm not sure how to extend the editor to add a Notice component. 

**Before**

Screen Shot 2021-08-20 at 3 38 01 PM

**After**

Screen Shot 2021-08-20 at 3 25 31 PM

Fixes #55102

#### Testing instructions

* [Grab the artifact from this build](https://teamcity.a8c.com/buildConfiguration/calypso_WPComPlugins_EditorToolKit/6593369?) and upload it to your Atomic site as a plugin
* Go to Plugins and Activate this version of the ETK
* Go to the editor and add an Image block; try to drag and drop an HEIC image to the block
* It should return an error message like the above.
* Other types of images should upload without issue.

### CODE REVIEW

**Comment by sixhours** [comment]
Hmm, this works fine on simple sites (if I throw an error before the file type restrictions kick in) but appears to fail on Atomic sites. Will keep plugging away at it.

**Comment by mreishus** [comment]
### Linux (Cannot reproduce)

In linux firefox+chrome, I'm not able to see the original error. Before and after the fix, I see a security message after dragging and dropping an HEIC image.

https://user-images.githubusercontent.com/937354/130296660-83f70388-2b87-4255-a3a3-659d7d430cad.mp4

Using the browser to debug, I see that the image is considered type `image/heif`, and the allowed list only contains `image/heic`, so it is not allowed.




So, there is no problem to begin with in linux. Tried with the fix after and saw the same behavior. Nothing is harmed at least :+1:

**Comment by mreishus** [comment]
### Windows (Does not fix)

On Windows 10, Firefox 91, I am seeing the error both before and after uploading the ETK artifact. Here's a video of me dragging and dropping `sample1.heic` when using the new ETK:

https://user-images.githubusercontent.com/937354/130297235-78ba33a1-25b8-4d15-8301-86371d4b0275.mp4

Strangely enough, when I use the browser's debug tools to check the image type, now it is `""`, or an empty string. (I don't have a screenshot of it, but this same file also appeared as `image/heif` when uploading in linux - I retreived it from https://filesamples.com/formats/heif)
firefox_wyuzEkAXgH
 
Maybe the new ETK code is seeing the same thing and that's why it's not running in this case?

### MacOS X (Unknown)

We'll need someone else to test this.

**Comment by sixhours** [comment]
> Maybe the new ETK code is seeing the same thing and that's why it's not running in this case?

I updated this to include `image/heif` in addition to `image/heic`, but I'm not sure how we'd account for a file that has no type. 🙃

**Comment by blackjackkent** [comment]
@sixhours I tested this on my MacBook. It appears that HEIC files are simply greyed out as an un-uploadable/un-clickable file type during the file selection process, compared to things like JPG which I was able to select:

CleanShot 2021-08-24 at 15 13 34@2x

**Comment by blackjackkent** [comment]
Checked again while dragging and dropping; it chewed for a bit and then gave the error message as expected. (It also kept the file selection picker up; I'm not sure if that's expected or not.)

image

**Comment by sixhours** [comment]
Tried this on Windows 10 using the latest Edge via Browserstack and can confirm I get the same results as @mreishus for Windows, so it only appears to work for Mac because Mac recognizes the format/file type. My next thought is to check the file extension itself.

**Comment by sixhours** [comment]
Screen Shot 2021-08-30 at 12 11 49 PM

Restricting based on the file extension seems to work for Windows since the file type is blank in that case.

File: apps/editing-toolkit/editing-toolkit-plugin/common/disable-heic-images.js [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+		props.onFilesPreUpload = ( files ) => {
+			if ( files ) {
+				const error = __(
+					'HEIC images are not viewable in the editor. Please convert to a JPG, PNG, or GIF and try again.',
+					'full-site-editing'
+				);
+				Object.values( files ).filter( ( file ) => {
+					const filename = file.name;
+					const extension = filename
+						.substring( filename.lastIndexOf( '.' ) + 1, filename.length )
```
Comment (alshakero) [inline apps/editing-toolkit/editing-toolkit-plugin/common/disable-heic-images.js]: Optional: my favorite way to do this is:

```suggestion
					const extension = filename
						.split('.').pop();
```

File: apps/editing-toolkit/editing-toolkit-plugin/common/disable-heic-images.js [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+						.toLowerCase();
+
+					if (
+						'image/heic' === file.type ||
+						'image/heif' === file.type ||
```
Comment (alshakero) [inline apps/editing-toolkit/editing-toolkit-plugin/common/disable-heic-images.js]: Optional: it seems checking the type [is redundant](https://developer.mozilla.org/en-US/docs/Web/API/File/type#:~:text=note%3A%20based%20on%20the%20current%20implementation) if the extension is checked.

File: apps/editing-toolkit/editing-toolkit-plugin/common/disable-heic-images.js [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+
+const DisableHEICImages = createHigherOrderComponent( ( MediaPlaceholder ) => {
+	return ( props ) => {
+		props.onFilesPreUpload = ( files ) => {
+			if ( files ) {
+				const error = __(
+					'HEIC images are not viewable in the editor. Please convert to a JPG, PNG, or GIF and try again.',
+					'full-site-editing'
+				);
+				Object.values( files ).filter( ( file ) => {
```
Comment (alshakero) [inline apps/editing-toolkit/editing-toolkit-plugin/common/disable-heic-images.js]: It seems `forEach` is more appropriate in this case.
```suggestion
				Object.values( files ).forEach( ( file ) => {
```

File: apps/editing-toolkit/editing-toolkit-plugin/common/disable-heic-images.js [hunk 4]
```diff
@@ -0,0 +1,38 @@
...
+						.toLowerCase();
+
+					if (
+						'image/heic' === file.type ||
+						'image/heif' === file.type ||
+						'heic' === extension ||
+						'heif' === extension
+					) {
+						props.onError( error );
+						throw Error( error );
```
Comment (alshakero) [inline apps/editing-toolkit/editing-toolkit-plugin/common/disable-heic-images.js:20]: I'd declare the error string here. Since it's only used here.

**Review by alshakero — COMMENTED** [review]
Since people tested before me, I didn't. I just reviewed the code. Left all cosmetic comments.

If you want me to test, I'd be happy to! Just let me know.

**Review by alshakero — APPROVED** [review]
LGTM! 🚢

**Comment by sixhours** [comment]
I don't think the test failures are a blocker; it's flagging this PR because it has fewer passing tests than the previous build, but those non-passing tests aren't failing, just being ignored. 🤷‍♀️ Hard to say, though, because I've never seen that kind of an error before. 🤔

File: apps/editing-toolkit/editing-toolkit-plugin/common/disable-heic-images.js [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+import { addFilter } from '@wordpress/hooks';
+import { __ } from '@wordpress/i18n';
+
+const DisableHEICImages = createHigherOrderComponent( ( MediaPlaceholder ) => {
+	return ( props ) => {
+		props.onFilesPreUpload = ( files ) => {
+			if ( files ) {
+				Object.values( files ).forEach( ( file ) => {
+					const filename = file.name;
+					const extension = filename.split( '.' ).pop().toLowerCase();
```
Comment (alshakero) [inline apps/editing-toolkit/editing-toolkit-plugin/common/disable-heic-images.js]: It just occurred to me that if someone uploads a file that doesn't have a dot, this will throw, as `pop()` would return undefined.

This might be a fix:
```suggestion
					const extension = filename.split( '.' ).pop()?.toLowerCase();
```

**Review by alshakero — CHANGES_REQUESTED** [review]
Just caught an issue!

**Comment by sixhours** [comment]
Phew, good catch :D

**Review by alshakero — COMMENTED** [review]
LGTM 🚢

**Review by alshakero — APPROVED** [review]

**Comment by sixhours** [comment]
I still can't get the tests to pass, and other ETK PRs don't have the same issue, so I think there might be something about this one. Will see if I can get an e2e tester to take a look before I deploy this.

**Comment by sixhours** [comment]
@dpasque confirmed the errors are related to this PR happening in the midst of test migrations and not specific to these changes. Merging. :)

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6578805

Thank you @sixhours for including a screenshot in the description! This is really helpful for our translators.

**Comment by noahtallen** [comment]
> I still can't get the tests to pass

Unless the code in ETK is imported by the calypso client (which it shouldn't be!), then no ETK code is run in any of the e2e suites. This is because we can't install arbitrary plugin builds on wpcom without actually deploying them. So unfortunately, ETK PRs aren't covered by e2e tests. Which is unfortunate, but it does mean that you should normally be able to ignore them assuming your PR _only_ changes ETK.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6578805).

**Comment by mreishus** [comment]
See p1632392675160800-slack-C02DQP0FP for possible error state
