### PR TITLE
Gutenlypso: Preserve block attributes when updating media

### LINKED ISSUE #29557: Gutenlypso: Opening Media Library Breaks Image Blocks
**Outdated steps: See this [comment](https://github.com/Automattic/wp-calypso/issues/29557#issuecomment-449413040)**

#### Steps to reproduce
1. Starting at URL: https://horizon.wordpress.com/block-editor/post/
2. Write a post and include an Image Block
3. Add a caption or adjust the size slightly
4. Set a Featured Image under "Document" 
5. Preview or Publish post 
6. See issue

#### What I expected

I expected the post to reflect the changes made in the editor, showing the captions and the image sizing. 

#### What happened instead

- The captions were removed in both the editor and the actual post/preview itself 
- Nothing changed regarding image sizing in the editor, but it reverts to full size when publishing or previewing the post

**In the editor (should show captions beneath image):**

fdsgdsgffsddsfg

**In the post:**

gfsdfsdgdfsg

#### Browser / OS version

- Mac OS X 10.6.8 
- Chrome 49

#### Context / Source

Found when writing a post for my own blog (I've experienced this several times before but I wasn't sure how to recreate it until now)

### PR DESCRIPTION
**Pull request by mmtr**
Our custom Media Modal for Gutenlypso relies on `MediaStore.on( 'change' )` for updating the media items when they are edited within the Media Modal itself. 

But the current approach is triggering an undesired effect: it resets the block attributes to default values (using the `mediaCalypsoToGutenberg` utility) causing the previous values to don't be preserved. 

#### Changes proposed in this Pull Request

* Move the current `change` listener out of the Media Modal, so the callback is executed only once per post, instead of once per block.
* Create new class containing the whole logic that updates the media.
* If the media changes, update the needed block attributes without modifying the rest of them.

#### Know issues

This PR doesn't update the media used as featured media for the post or for a simple payment block. A follow-up PR will cover this.

#### Testing instructions

1. Open the block editor at `/block-editor` and select a site under a paid plan (free plans don't allow to edit images in the Media Modal).
2. Insert an image block and click on the "Media Library" button.
3. Select any image from the Media Modal (or upload a new one and select it).
4. Adjust the image size and enter a caption.
5. Repeat steps 2-4 with other media blocks and selecting the same image as selected in step 3: Gallery, Cover, Media & Text, Tiled Gallery.
6. Select any of the current blocks and click on the Pencil icon on its toolbar.
7. Click on the Edit button in the Media Modal and apply some changes to the image (e.g. flip it).
8. Close the Media Modal without inserting the modified image.
9. Make sure that all the media blocks show the modified image.
10. Check the size and the caption of the previous image block are preserved in both the editor and the post preview.

Editor

| Before | After |
| --- | --- |
| image | image |

Preview

| Before | After |
| --- | --- |
| image | image |

Fixes #29557

### CODE REVIEW

**Comment by torres126** [comment]
Just wanted to confirm that this fixes the original issue for me! It also tested well with the Image, Gallery, Inline Image, Cover and Media & Text blocks. :tada:

> This PR doesn't update the media used as featured media for the post or for a simple payment block. A follow-up PR will cover this.

I can't test the Simple Payment block, but for some reason, this PR _does_ fix the issue with Featured Images causing captions and alignments to not be preserved for me.

File: client/gutenberg/editor/utils/media-updater/index.js [hunk 1]
```diff
@@ -0,0 +1,148 @@
...
+					[ url ]: media.URL,
+				} );
+			}
+		}
+
+		updateBlockAttributes( clientId, { [ images ]: updatedImages } );
+	};
+
+	// Block name -> Function that updates the media
+	mediaBocks = {
```
Comment (gwwar) [inline client/gutenberg/editor/utils/media-updater/index.js]: An explicit mapping works in the short term 👍

We may want to chat with @Automattic/luna and core folks, maybe @gziolo @aduth, if there's a way to detect blocks that use images, and maybe provide a decent fallback option

**Comment by gwwar** [comment]
One small corner case we can follow up in, in another PR is that the featured image preview doesn't update if we edit an image in the media modal.

screen shot 2018-12-31 at 4 47 10 pm

File: client/gutenberg/editor/utils/media-updater/index.js (hunk 1 above)
Comment (gziolo) [reply client/gutenberg/editor/utils/media-updater/index.js]: It looks like in core we don't refresh content at all when any change in the media library happens. I tried the following:
- delete an image using media library, images are missing as soon as you refresh the page
- edit an image using media library - only the image in the currently selected block gets updated, however the old image still works properly for other blocks

So, the short answer is we don't have support for it at the moment at all :(

Regarding finding the ways, I don't think it is straightforward because urls are stored as strings in `attributes` section and we simply inline components which handle them. I know that there were some work to strip out image ids when exporting/importing reusable blocks, so maybe @mcsf or @youknowriad would know more how to automate it.

Comment (gwwar) [reply client/gutenberg/editor/utils/media-updater/index.js]: Thanks @gziolo for the extra context. I suppose we'll keep thinking about this for core's use case as well. 🤔Maybe we could build something that could query for block functionality. Say, of an editors registered blocks, which ones involve the media library, and it'd return this list or something similar. Or may return a list of blocks instances that satisfy the feature query. I'm guessing we may have other use cases like that.
