### PR TITLE
Show additional messages on Marketplace installation progress bar when the operation takes long

### LINKED ISSUE #62067: Marketplace: Plugin installation progress bar
The progress bar in plugin installation seems not progressing in Step 2 and goes directly to Step 3. This happens especially when site is transferred to Atomic at that point of time.

**Steps to reproduce:**
- On your simple business site
- Go to plugins
- Pick any free plugin and proceed to installation

**Result:**
The progress bar simulates to step 1 and 2, then it gets stuck to 2 (66.6%?) for some seconds and then suddenly goes to 3. 

**Note:**
This is mostly a problem when sites move from simple to Atomic infrastructure. This process might even take 1 minute (or more in edge cases with sites having a lot of content).

**Suggestion:**
Can we find a silver lining in simulating this progress bar or even notifying the user that the operation is still in progress?

cc: @vinimotaa , @SaxonF 

related convo: pdt2If-6r-p2

### PR DESCRIPTION
**Pull request by WBerredo**
### Description

Change the title of the progress bar steps every 7 seconds on the Marketplace Installation page.
The idea is to show the operation is still progressing even in big flows such as transferring a site to atomic.

Currently, the only messages being used are the step descriptions, after the change, those messages will be changed if one step is taking too long. But it will always return to the actual step description as soon as the process reaches the next step state.

#### Llist of messages
**Step descriptions**
* Uploading plugin 
* Setting up plugin installation
* Installing plugin
* Activating plugin

**Additional messages to be rotated when the actual step is taking too long**
* Connecting the dots
* Still working
* Wheels are in motion
* Working magic

PS: All of those phases are translatable

### Testing instructions
* Go to the installation URL (`/marketplace/{plugin_slug}/install/{site}`) of a plugin which should take a long time.
* Check if every 7 seconds the message is being changed

Example of a flow which usually takes long: Transferring a site to atomic
* From a free site, go to the plugin page
* Click on the CTA (upgrade and activate)
* After the purchase (if needed) you should see the Marketplace Installation page
* Check if every 7 seconds the message is being changed

Kapture 2022-05-26 at 12 06 05

---

Fixes #62067

### CODE REVIEW

**Comment by WBerredo** [comment]
@emmnyc85  we added the messages on the section **Additional messages to be rotated when the actual step is taking too long**, I would like to check with you if the wording is good, if you suggest any adjustments and if you have suggestions for new phrases (it would be awesome) that indicate the flow is still processing.

**Comment by emmnyc85** [comment]
@WBerredo - Thank you. These all look good. No issues

File: client/my-sites/marketplace/pages/marketplace-plugin-install/index.tsx [hunk 1]
```diff
@@ -244,11 +244,26 @@ const MarketplacePluginInstall = ( { productSlug }: MarketplacePluginInstallProp
 		// eslint-disable-next-line react-hooks/exhaustive-deps
 	}, [ pluginActive, automatedTransferStatus ] ); // We need to trigger this hook also when `automatedTransferStatus` changes cause the plugin install is done on the background in that case.
 
-	const steps = [
-		isUploadFlow ? translate( 'Uploading plugin' ) : translate( 'Setting up plugin installation' ),
-		translate( 'Installing plugin' ),
-		translate( 'Activating plugin' ),
-	];
+	const steps = useMemo(
```
Comment (epeicher) [inline client/my-sites/marketplace/pages/marketplace-plugin-install/index.tsx:247]: Is `useMemo` required here? The linter is complaining about `translate` missing in the dependencies array.

**Review by epeicher — APPROVED** [review]
I have tested and works as expected! I have left a question but not important.

File: client/my-sites/marketplace/pages/marketplace-plugin-install/index.tsx (hunk 1 above)
Comment (WBerredo) [reply client/my-sites/marketplace/pages/marketplace-plugin-install/index.tsx:247]: Yes, it is needed because this value is being used as a dependency on the other component and cannot be recreated every time. I'll add `translate` as a dependency.

Comment (WBerredo) [reply client/my-sites/marketplace/pages/marketplace-plugin-install/index.tsx:247]: Updated at https://github.com/Automattic/wp-calypso/pull/64087/commits/785ebedbe944dc66f8248a8f2902be5b5508e207

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7347406

Thank you @WBerredo for including a screenshot in the description! This is really helpful for our translators.

**Comment by WBerredo** [comment]
@jeremyanderberg if you have any suggestions for new messages for **Additional messages to be rotated**, feel free to drop it here.

**Comment by jeremyanderberg** [comment]
@WBerredo These are all great! Another one might be "Putting the pieces together" (like a puzzle). I wonder, too, if we can put motion icons next to each of them? "Connecting the dots" could be a square with 4 points in the corners and a line moving, "Wheels are in motion" could be a little car or just a wheel in motion, "Working magic" could be a swishing wand. Just an idea — if it's a ton of extra work, don't worry about it, but might be a fun little addition.

**Comment by WBerredo** [comment]
> "Putting the pieces together" (like a puzzle)

I like it, I'll be creating a PR with this suggestion. 

And just to reinforce, we are still open to more suggestions, I think it would be nice to have a list with at least 10 phrases.

> if we can put motion icons next to each of them? "Connecting the dots" could be a square with 4 points in the corners and a line moving, "Wheels are in motion" could be a little car or just a wheel in motion, "Working magic" could be a swishing wand.

Whilst I also like this idea, I think it would be a good amount of work to be applied in a flow we want to "avoid", like it would be better to spend more time trying to reduce this time.

**Comment by jeremyanderberg** [comment]
> "Whilst I also like this idea, I think it would be a good amount of work to be applied in a flow we want to "avoid", like it would be better to spend more time trying to reduce this time."

Got it — no problem at all. 

I'll keep thinking about additional phrases and get back to you with a few more by the end of the week!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7347406

Thank you @WBerredo for including a screenshot in the description! This is really helpful for our translators.

**Comment by jeremyanderberg** [comment]
Hi @WBerredo — here's a handful more ideas: 

*Assembling the parts 
*Stacking the building blocks 
*Getting our ducks in a row 
*Initiating countdown 
*Flipping the switches 
*Unlocking potential 
*Gears are turning  

Let me know what you think!

**Comment by WBerredo** [comment]
Follow up created at #64534

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7347406).
