### PR TITLE
Make the copy of the auto-renewal cancellation survey be aware of the product.

### LINKED ISSUE #35224: Marketing survey for domains mentions plans
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/purchases/
2. Select a domain to view its purchase management page.
3. Turn off toggle for the auto-renew

#### What I expected

I expected the survey to mention domains.

#### What happened instead

The survey mentions plans.

#### Screenshot / Video

1. Screen recording - https://cloudup.com/c-BamUMLv1f

2. 

Screenshot 2019-08-08 at 7 26 15 PM

#### Context / Source

This is related to the survey change introduced in https://github.com/Automattic/wp-calypso/pull/35044

### PR DESCRIPTION
**Pull request by southp**
#### Changes proposed in this Pull Request

This PR attempts to resolve #35224, by introducing product-specific terms.

For a plan:
image

For a domain:
image

For anything else we haven't thought of in advance, it defaults to "subscription":
image

#### Testing instructions

1. Disable auto-renewal of a plan subscription and see the plan-specific copy show up.
1. Disable auto-renewal of a domain registration and see the domain-specific copy show up.
1. There doesn't seem to be an obvious way to see the defaults. One way is to hard-code `isPlan()` and `isDomainRegistration()` to always return `false`.

### CODE REVIEW

File: client/components/marketing-survey/cancel-auto-renewal-form/index.jsx [hunk 1]
```diff
@@ -38,14 +39,43 @@ class CancelAutoRenewalForm extends Component {
 
 	radioButtons = {};
 
+	getProductTypeString = () => {
+		const { purchase, translate } = this.props;
+
+		if ( isDomainRegistration( purchase ) ) {
+			/* translators: as in "domain name"*/
+			return translate( 'domain' );
```
Comment (a8ci18n) [inline client/components/marketing-survey/cancel-auto-renewal-form/index.jsx]: Hi! I've found a possible matching string that has already been translated **37** times:
`translate( 'domain', { context: 'noun - someone's domain name'} )` *ES Score: 11*
See 1 additional suggestion in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/cancel-auto-renewal-form-for-domain)

Help me improve these suggestions: react with :thumbsdown: if the suggestion doesn't make any sense, or with :thumbsup: if it's a particularly good one (even if not implemented).

File: client/components/marketing-survey/cancel-auto-renewal-form/index.jsx [hunk 2]
```diff
@@ -38,14 +39,43 @@ class CancelAutoRenewalForm extends Component {
...
+		}
+
+		if ( isPlan( purchase ) ) {
+			/* translators: as in "Premium plan" or "Personal plan"*/
+			return translate( 'plan' );
```
Comment (a8ci18n) [inline client/components/marketing-survey/cancel-auto-renewal-form/index.jsx]: Hi! I've found a possible matching string that has already been translated **60** times:
`translate( 'Plan', { context: 'noun'} )` *ES Score: 8*
See 1 additional suggestion in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/cancel-auto-renewal-form-for-domain)

Help me improve these suggestions: react with :thumbsdown: if the suggestion doesn't make any sense, or with :thumbsup: if it's a particularly good one (even if not implemented).

File: client/components/marketing-survey/cancel-auto-renewal-form/index.jsx [hunk 3]
```diff
@@ -38,14 +39,43 @@ class CancelAutoRenewalForm extends Component {
...
+		}
+
+		return translate( 'subscription' );
```
Comment (a8ci18n) [inline client/components/marketing-survey/cancel-auto-renewal-form/index.jsx]: Hi! I've found a possible matching string that has already been translated **36** times:
`translate( 'subscription', 'block search term' )` *ES Score: 12*
See 1 additional suggestion in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/cancel-auto-renewal-form-for-domain)

Help me improve these suggestions: react with :thumbsdown: if the suggestion doesn't make any sense, or with :thumbsup: if it's a particularly good one (even if not implemented).
