### PR TITLE
Plugin Upload: new flow

### LINKED ISSUE #56792: [Bug]: Installing a plugin not existing to the .org directory through calypso results in a loading screen
### Quick summary

After users upload a plugin in Calypso we redirect them to the Calypso plugin details page. This page retrieves the plugin details from the .org directory. If you try to upload a plugin that doesn't exist in .org directory then you are stuck with a loading screen.

We have discussed this in our pod and suggested that ~~after any manual plugin install users are redirected to WP Admin plugins manage screen `wp-admin/plugins.php` so that they can do further actions (eg enabling it or run through a wizard).~~ we will show to the user a full screen loading page with steps as in the new Marketplace designs. The last (thank you) page will include links relevant to the plugin bought / uploaded. 

Related designs oU6nEIeiKSg8CayhEtgR6b-fi-6452%3A46534

### Steps to reproduce

1. start at https://wordpress.com/plugins/[DOMAIN] of an atomic site
2. click **Install Plugin**
3. upload a premium not .org plugin

### What you expected to happen

I expected to be able to activate the plugin or generally manage it

### What actually happened

image

### Context

_No response_

### Browser

_No response_

### Simple/Atomic

Atomic

### Other notes

_No response_

### Reproducibility

Consistent

### Severity

_No response_

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by cpapazoglou**
#### Changes proposed in this Pull Request
The following changes depend on the `marketplace` feature flag which is `true` in all environments except production

After Users drop a file in the plugin upload dropzone `http://calypso.localhost:3000/plugins/upload`, we redirect them in a flow with a progress bar that eventually leads to a thank you page as depicted in oU6nEIeiKSg8CayhEtgR6b-fi-6559%3A46946 . This new flow also resolves #56792 with not .org plugins being uploaded. 

Notices: 
- I haven't yet moved the domain warning in a modal
- Illustrations might not be final
- Thank you page alterations (like background change) will need to part of another PR

#### Testing instructions

**Before**
https://user-images.githubusercontent.com/12430020/137928110-f9661a41-6fd9-4001-b7ee-b1ae599997ec.mp4

**After**
SS

**With Atomic transfer**
- On a Business Simple Site
- Go to `/plugins/upload/:site`
- Upload a plugin (the site will start transferring on the background)
- After successful installation you should land to thank you page and the plugin should be active 

**Without Atomic transfer**
- On a Business Atomic or Ecommerce Site
- Go to `/plugins/upload/:site`
- Upload a plugin (the site will start transferring on the background)
- After successful installation you should land to thank you page and the plugin should be active 

**With Plugin already existing**
- Try repeating the above steps after successfully installing the same plugin
- You should get an error page 

Fixes #56792

### CODE REVIEW

File: client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx [hunk 1]
```diff
@@ -1,155 +1,102 @@
...
+		sectionKey: 'setup_whats_next',
 		sectionTitle: translate( 'What’s next?' ),
 		nextSteps: [
 			{
-				stepKey: 'yoast_whats_next_plugin_setup',
+				stepKey: 'whats_next_plugin_setup',
 				stepTitle: translate( 'Plugin setup' ),
 				stepDescription: translate(
-					'Get to know Yoast SEO and customize it, so you can hit the ground running.'
+					'Get to know your plugin and customize it, so you can hit the ground running.'
```
Comment (a8ci18n) [inline client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx:50]: :ok: This change will be queued for retranslation. We'll use the existing translations in the meantime.

File: client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx [hunk 2]
```diff
@@ -1,155 +1,102 @@
...
-						primary
-						busy={ isRequestingMenu }
-						// TODO: Menu links are not properly loading on initial request, post transfer so yoastSeoPageUrl will remain empty post transfer
-						// This should be fixed with perhaps a work around to periodically poll for the menu with various domains until it loads
-						// or maybe blocking the user from entering this flow until a domain acquires SSL
-						disabled={ ! yoastSeoPageUrl }
-					>
-						{ translate( 'Get started' ) }
+					<FullWidthButton href={ setupURL } primary busy={ ! plugin }>
+						{ translate( 'Manage plugin' ) }
```
Comment (a8ci18n) [inline client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx:54]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **26** times:
`translate( 'Manage plugins' )` *ES Score: 6*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/plugin_upload_flow)

**Comment by sirbrillig** [comment]
Just an FYI that you can mark this PR as a draft to avoid tagging codeowners or triggering the review status!

**Comment by cpapazoglou** [comment]
@JanaMW27 you might also want to take a look!

**Review by gavande1 — APPROVED** [review]
Great Work Harris! It works as expected. LGTM 👍

File: client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you-YOAST.tsx [hunk 3]
```diff
@@ -0,0 +1,165 @@
...
+	.marketplace-thank-you {
+		margin-top: var( --masterbar-height );
+		img {
+			height: auto;
+		}
+	}
+`;
+
+const MarketplaceThankYouYoast = () => {
+	const [ pollCount, setPollCount ] = useState( 0 );
```
Comment (WBerredo) [inline client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you-YOAST.tsx:34]: Not sure where the `pollCount` value is used. Would you mind explaining what is the goal of this state var?

Comment (WBerredo) [reply client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you-YOAST.tsx:34]: Now I understand this may be the old component that you are replacing, right? Let me know if that is the case.

**Review by WBerredo — APPROVED** [review]
LGTM 🚢

**Comment by cpapazoglou** [comment]
@vajrasar This will be deployed asap behind a feature flag. It will probably go live in the end of our next sprint Nov 5.

File: client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you-YOAST.tsx (hunk 3 above)
Comment (cpapazoglou) [reply client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you-YOAST.tsx:34]: Exactly, I just kept the file for future reference.

File: client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you-YOAST.tsx [hunk 4]
```diff
@@ -0,0 +1,165 @@
...
+		menuItems.find( ( { slug }: { slug: string } ) => slug === 'edit-php' ) ?? {};
+
+	const { url: yoastSeoPageUrl } =
+		menuItems.find( ( { slug }: { slug: string } ) => slug === 'wpseo_dashboard' ) ?? {};
+
+	const translate = useTranslate();
+
+	useEffect( () => {
+		if ( ! postsPageUrl || ! yoastSeoPageUrl ) {
+			selectedSiteId && dispatch( requestAdminMenu( selectedSiteId ) );
```
Comment (mmtr) [inline client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you-YOAST.tsx:59]: Non-blocking: Can this result in an infinite loop of `requestAdminMenu` for cases where either the posts or the Yoast SEO pages are not available (e.g. user without permissions)?

Not sure if that's ever possible (I guess users with access to this component will always have the needed permissions), but I think we can remove this code, since the `useSiteMenuItems` effect above already [requests the admin menu](https://github.com/Automattic/wp-calypso/blob/6826475ab39d92fa34cd3579535f36d0def5ba26/client/my-sites/sidebar-unified/use-site-menu-items.js#L28).

File: client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you-YOAST.tsx [hunk 5]
```diff
@@ -0,0 +1,165 @@
...
+
+	useEffect( () => {
+		if (
+			isPluginInstalledDuringPurchase &&
+			transferStatus !== 'complete' &&
+			! isFetchingTransferStatus
+		) {
+			setTimeout( () => {
+				selectedSiteId && dispatch( fetchAutomatedTransferStatus( selectedSiteId ) );
+				setPollCount( ( c ) => c + 1 );
```
Comment (mmtr) [inline client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you-YOAST.tsx:71]: TIL your can pass a function to set a new state that is computed using the previous state.

File: client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you-YOAST.tsx [hunk 6]
```diff
@@ -0,0 +1,165 @@
...
+	);
+	const menuItems = useSiteMenuItems();
+	const isRequestingMenu = useSelector( getIsRequestingAdminMenu );
+	const { url: postsPageUrl } =
+		menuItems.find( ( { slug }: { slug: string } ) => slug === 'edit-php' ) ?? {};
+
+	const { url: yoastSeoPageUrl } =
+		menuItems.find( ( { slug }: { slug: string } ) => slug === 'wpseo_dashboard' ) ?? {};
+
+	const translate = useTranslate();
```
Comment (mmtr) [inline client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you-YOAST.tsx:55]: Nitpick (non-blocking): I think the equivalent `useI18n` (from `@wordpress/react-i18n`) is now preferred (I remember reading somewhere that we're planning to deprecate the Calypso tools in favor of the Core ones).

File: client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you-YOAST.tsx [hunk 7]
```diff
@@ -0,0 +1,165 @@
...
+					>
+						{ translate( 'Get started' ) }
+					</FullWidthButton>
+				),
+			},
+			{
+				stepKey: 'yoast_whats_next_view_posts',
+				stepTitle: translate( 'Start putting SEO to work' ),
+				stepDescription: translate(
+					"Improve your site's performance and rank higher with a few tips."
```
Comment (mmtr) [inline client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you-YOAST.tsx:118]: Nitpick (non-blocking): It'd be good to consolidate the apostrophes. Here you're using `'` in `Improve your site's`, while a few lines above you're using `’` in `What’s  next?`

File: client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx [hunk 8]
```diff
@@ -1,155 +1,102 @@
...
-		isFetchingTransferStatus,
-		isPluginInstalledDuringPurchase,
-		pollCount,
-		setPollCount,
-		dispatch,
-		transferStatus,
-		selectedSiteId,
-	] );
+const MarketplaceThankYou = ( { productSlug } ): JSX.Element => {
+	const translate = useTranslate();
```
Comment (mmtr) [inline client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx:27]: Nitpick (non-blocking): Same as above, `useI18n` may be preferable.

File: client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx [hunk 9]
```diff
@@ -1,155 +1,102 @@
...
+	const siteId = useSelector( getSelectedSiteId );
+	const siteSlug = useSelector( getSelectedSiteSlug );
+	const plugin = useSelector( ( state ) => getPluginOnSite( state, siteId, productSlug ) );
+	const siteAdminUrl = useSelector( ( state ) => getSiteAdminUrl( state, siteId ) );
 
-	/* TODO: Make all these items product-dependent */
 	const thankYouImage = {
-		alt: 'yoast logo',
-		src: yoastInstalledImage,
+		alt: 'success image',
```
Comment (mmtr) [inline client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx]: If we really want a text here, it should be translatable. However, I think this is just a decorative image as opposed to an informative one, and thus the `alt` property could be changed to simply
```suggestion
		alt: '',
```

File: client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx [hunk 10]
```diff
@@ -1,155 +1,102 @@
...
-						disabled={ ! yoastSeoPageUrl }
-					>
-						{ translate( 'Get started' ) }
+					<FullWidthButton href={ setupURL } primary busy={ ! plugin }>
+						{ translate( 'Manage plugin' ) }
 					</FullWidthButton>
 				),
 			},
 			{
 				stepKey: 'yoast_whats_next_view_posts',
```
Comment (mmtr) [inline client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx]: I think this is now a generic component, so we probably should get rid of the `yoast_` prefix:

```suggestion
				stepKey: 'whats_next_view_posts',
```

File: client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx [hunk 11]
```diff
@@ -1,155 +1,102 @@
...
 				),
 				stepCta: (
-					<FullWidthButton
-						href={ postsPageUrl }
-						busy={ isRequestingMenu }
-						disabled={ ! yoastSeoPageUrl }
-					>
-						{ translate( 'View posts' ) }
+					<FullWidthButton href={ `/plugins/${ siteSlug }` }>
+						{ translate( 'Explore Plugins' ) }
```
Comment (mmtr) [inline client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx]: Is this using a "Title Case" format intentionally instead of the "Sentence case" used everywhere else?

File: client/my-sites/marketplace/components/progressbar/index.tsx [hunk 12]
```diff
@@ -0,0 +1,55 @@
...
+
+	/* translators: %(currentStep)s  Is the current step number, given that steps are set of counting numbers representing each step starting from 1, %(stepCount)s  Is the total number of steps, Eg: Step 1 of 3  */
+	const stepIndication = translate( 'Step %(currentStep)s of %(stepCount)s', {
+		args: { currentStep: currentStep + 1, stepCount: steps.length },
+	} );
+
+	return (
+		<Container>
+			<Title className="progressbar__title wp-brand-font">{ steps[ currentStep ] }</Title>
+			<StyledProgressBar value={ simulatedProgressPercentage } color="#C9356E" compact />
```
Comment (mmtr) [inline client/my-sites/marketplace/components/progressbar/index.tsx]: Is there any way we can avoid hardcoding the color here and use the `--studio-pink` var instead?

Speaking of which, shouldn't this color be based on the current theme set by the user on their personal settings?

File: client/my-sites/marketplace/components/progressbar/index.tsx [hunk 13]
```diff
@@ -0,0 +1,55 @@
...
+const ACCELERATED_INCREMENT = 5;
+
+export default function MarketplaceProgressBar( {
+	steps,
+	currentStep,
+}: {
+	steps: TranslateResult[];
+	currentStep: number;
+} ): JSX.Element {
+	const translate = useTranslate();
```
Comment (mmtr) [inline client/my-sites/marketplace/components/progressbar/index.tsx:27]: Nitpick (non-blocking): Same as above, `useI18n` may be preferable.

File: client/my-sites/marketplace/pages/marketplace-plugin-upload-status/index.tsx [hunk 14]
```diff
@@ -0,0 +1,107 @@
...
+import getPluginUploadProgress from 'calypso/state/selectors/get-plugin-upload-progress';
+import getUploadedPluginId from 'calypso/state/selectors/get-uploaded-plugin-id';
+import isPluginActive from 'calypso/state/selectors/is-plugin-active';
+import isPluginUploadComplete from 'calypso/state/selectors/is-plugin-upload-complete';
+import { getSelectedSiteId, getSelectedSiteSlug } from 'calypso/state/ui/selectors';
+import './style.scss';
+
+const MarketplacePluginUpload = (): JSX.Element => {
+	const [ currentStep, setCurrentStep ] = useState( 0 );
+	const translate = useTranslate();
```
Comment (mmtr) [inline client/my-sites/marketplace/pages/marketplace-plugin-upload-status/index.tsx:27]: Nitpick (non-blocking): Same as above, `useI18n` may be preferable.

File: client/my-sites/marketplace/pages/marketplace-plugin-upload-status/index.tsx [hunk 15]
```diff
@@ -0,0 +1,107 @@
...
+	}, [ pluginUploadComplete, uploadedPlugin, setCurrentStep ] );
+
+	useEffect( () => {
+		if ( pluginActive ) {
+			waitFor( 1 ).then( () =>
+				page( `/marketplace/thank-you/${ uploadedPlugin?.slug }/${ selectedSiteSlug }` )
+			);
+		}
+		// eslint-disable-next-line react-hooks/exhaustive-deps
+	}, [ pluginActive, automatedTransferStatus ] ); // We need to trigger this hook also when automatedTransferStatus changes.
```
Comment (mmtr) [inline client/my-sites/marketplace/pages/marketplace-plugin-upload-status/index.tsx]: Any `automatedTransferStatus` change should trigger it? Not sure how this works. It seems that it doesn't matter whether `automatedTransferStatus` changes or not, since at the end we're only checking if the plugin is active.

File: client/my-sites/marketplace/pages/marketplace-plugin-upload-status/index.tsx [hunk 16]
```diff
@@ -0,0 +1,107 @@
...
+	const steps = [
+		translate( 'Uploading plugin' ),
+		translate( 'Installing plugin' ),
+		translate( 'Activating plugin' ),
+	];
+
+	return (
+		<ThemeProvider theme={ theme }>
+			<PageViewTracker path="/marketplace/product/install/:site" title="Plugins > Installing" />
+			{ siteId ? <QueryJetpackPlugins siteIds={ [ siteId ] } /> : '' }
```
Comment (mmtr) [inline client/my-sites/marketplace/pages/marketplace-plugin-upload-status/index.tsx]: Nitpick (non-blocking): I think this reads better:
```suggestion
			{ siteId && <QueryJetpackPlugins siteIds={ [ siteId ] } /> }
```

File: client/my-sites/marketplace/pages/marketplace-plugin-upload-status/index.tsx (hunk 15 above)
Comment (cpapazoglou) [reply client/my-sites/marketplace/pages/marketplace-plugin-upload-status/index.tsx]: Yes any `automatedTransferStatus` change is needed so that we can then check if the plugin is active. `pluginActive` alone is not enough when transferring the site cause plugin install is happening on the background!

I will add some more comments!

File: client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx (hunk 11 above)
Comment (cpapazoglou) [reply client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx]: Great catch!!!

File: client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx (hunk 10 above)
Comment (cpapazoglou) [reply client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx]: Good catch!

File: client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you-YOAST.tsx (hunk 4 above)
Comment (cpapazoglou) [reply client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you-YOAST.tsx:59]: This file is left in the codebase as a reference, I will avoid fixing anything there for the time being.

File: client/my-sites/marketplace/components/progressbar/index.tsx (hunk 13 above)
Comment (cpapazoglou) [reply client/my-sites/marketplace/components/progressbar/index.tsx:27]: Thanks for suggesting this, I will keep it in mind for future sprints.

File: client/my-sites/marketplace/pages/marketplace-plugin-upload-status/index.tsx (hunk 14 above)
Comment (cpapazoglou) [reply client/my-sites/marketplace/pages/marketplace-plugin-upload-status/index.tsx:27]: Thanks for suggesting this, I will keep it in mind for future sprints.

File: client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx (hunk 8 above)
Comment (cpapazoglou) [reply client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you.tsx:27]: Thanks for suggesting this, I will keep it in mind for future sprints.

File: client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you-YOAST.tsx (hunk 6 above)
Comment (cpapazoglou) [reply client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you-YOAST.tsx:55]: This file is left in the codebase as a reference, I will avoid fixing anything there for the time being.

File: client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you-YOAST.tsx (hunk 7 above)
Comment (cpapazoglou) [reply client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you-YOAST.tsx:118]: This file is left in the codebase as a reference, I will avoid fixing anything there for the time being.

File: client/my-sites/marketplace/components/progressbar/index.tsx (hunk 12 above)
Comment (cpapazoglou) [reply client/my-sites/marketplace/components/progressbar/index.tsx]: Very good point. It seems that leaving `color` empty correctly picks up current theme primary color but doesn't look great for a progress bar in that context

SS 2021-10-22 at 15 38 33

I will default to `--studio-pink-50` for the time being cause it seems more prominent.

cc: @olaolusoga

**Comment by cpapazoglou** [comment]
Thanks for your feedback @mmtr !

**Review by mmtr — APPROVED** [review]

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6875599

Thank you @cpapazoglou for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6875599).
