### PR TITLE
Reader Lists: improve error notices

### LINKED ISSUE #47219: Reader Lists: Cleaner errors
#### Steps to reproduce

1. Get an error in a reader list operation (for example following a list, see #47082).
2. The error shows the HTTP response in a visual notice:

Screenshot 2020-11-07 at 17 48 27

#### What I expected

A more abstract and user-friendly error. If I wasn't a developer I wouldn't know what it meant.

This might be a little bit of a rabbit hole, because there are few more errors like that in `client/state/data-layer/wpcom` :)

### PR DESCRIPTION
**Pull request by bluefuton**
#### Changes proposed in this Pull Request

As @nb notes in https://github.com/Automattic/wp-calypso/issues/47219, Reader lists often hands the API error straight back to the user when something goes wrong.

This PR adds more human-friendly error messages for scenarios where the API request has failed.

I've also removed error notices for list loading and list item loading - these are situations where the user hasn't taken a CRUD action and we should handle problems more quietly with just loading placeholders I think (like loading Reader feeds).

#### Testing instructions

On the development environment, create a new list and make sure the management UI works as expected:

http://calypso.localhost:3000/read/list/new

Fixes #47219.

### CODE REVIEW

File: client/state/data-layer/wpcom/read/lists/index.js [hunk 1]
```diff
@@ -57,11 +58,10 @@ registerHandlers( 'state/data-layer/wpcom/read/lists/index.js', {
 						} ),
 					];
 				}
-				// NOTE: Add better handling for unexpected response format here.
```
Comment (bluefuton) [inline client/state/data-layer/wpcom/read/lists/index.js:60]: Removed this comment because it's a very rare edge case - the API will return a 4xx response if anything goes wrong with list creation and `onError` will handle that.

File: client/state/data-layer/wpcom/read/lists/items/index.js [hunk 2]
```diff
@@ -23,7 +27,7 @@ registerHandlers( 'state/data-layer/wpcom/read/lists/items/index.js', {
 				),
 			onSuccess: ( action, apiResponse ) =>
 				receiveReaderListItems( apiResponse.list_ID, apiResponse.items ),
-			onError: ( action, error ) => errorNotice( String( error ) ),
+			onError: () => noop,
```
Comment (bluefuton) [inline client/state/data-layer/wpcom/read/lists/items/index.js:30]: Doing a `noop` because the linter complains when `onError` is removed altogether.

File: client/state/data-layer/wpcom/read/lists/delete/index.js [hunk 3]
```diff
@@ -35,7 +35,7 @@ registerHandlers( 'state/data-layer/wpcom/read/lists/delete/index.js', {
 					} ),
 				];
 			},
-			onError: () => errorNotice( translate( 'There was a problem deleting the list.' ) ),
+			onError: () => errorNotice( translate( 'Unable to delete list.' ) ),
```
Comment (a8ci18n) [inline client/state/data-layer/wpcom/read/lists/delete/index.js:38]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **29** times:
`translate( 'Unable to delete the list' )` *ES Score: 8*

File: client/state/data-layer/wpcom/read/lists/feeds/delete/index.js [hunk 4]
```diff
@@ -29,7 +29,7 @@ registerHandlers( 'state/data-layer/wpcom/read/lists/feeds/delete/index.js', {
 			onSuccess: successNotice( translate( 'Feed removed from list successfully.' ), {
 				duration: DEFAULT_NOTICE_DURATION,
 			} ),
-			onError: () => errorNotice( translate( 'Unable to remove feed from list' ) ),
+			onError: () => errorNotice( translate( 'Unable to remove feed from list.' ) ),
```
Comment (a8ci18n) [inline client/state/data-layer/wpcom/read/lists/feeds/delete/index.js:32]: :ok: This change will be queued for retranslation. We'll use the existing translations in the meantime.

File: client/state/data-layer/wpcom/read/lists/feeds/new/index.js [hunk 5]
```diff
@@ -45,12 +45,8 @@ registerHandlers( 'state/data-layer/wpcom/read/lists/feeds/new/index.js', {
...
 				];
 			},
-			onError: ( action, error ) => {
-				return errorNotice(
-					translate( 'Could not add feed to list: %(message)s', {
-						args: { message: error?.message },
-					} )
-				);
+			onError: () => {
+				return errorNotice( translate( 'Unable to add feed to list.' ) );
```
Comment (a8ci18n) [inline client/state/data-layer/wpcom/read/lists/feeds/new/index.js:49]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **22** times:
`translate( 'Unable to add feed' )` *ES Score: 6*

File: client/state/data-layer/wpcom/read/lists/index.js [hunk 6]
```diff
@@ -57,11 +58,10 @@ registerHandlers( 'state/data-layer/wpcom/read/lists/index.js', {
...
-				errorNotice( translate( 'List could not be created, please try again later.' ) );
+				errorNotice( translate( 'Unable to create new list.' ) );
```
Comment (a8ci18n) [inline client/state/data-layer/wpcom/read/lists/index.js:61]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **35** times:
`translate( 'Unable to create a new list.' )` *ES Score: 8*

File: client/state/data-layer/wpcom/read/lists/index.js [hunk 7]
```diff
@@ -140,7 +137,7 @@ registerHandlers( 'state/data-layer/wpcom/read/lists/index.js', {
 				} ),
 			],
 			onError: ( action, error ) => [
-				errorNotice( String( error ) ),
+				errorNotice( translate( 'Unable to update list.' ) ),
```
Comment (a8ci18n) [inline client/state/data-layer/wpcom/read/lists/index.js:140]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **28** times:
`translate( 'Unable to update the list' )` *ES Score: 8*

File: client/state/data-layer/wpcom/read/lists/tags/delete/index.js [hunk 8]
```diff
@@ -29,7 +29,7 @@ registerHandlers( 'state/data-layer/wpcom/read/lists/tags/delete/index.js', {
 			onSuccess: successNotice( translate( 'Tag removed from list successfully.' ), {
 				duration: DEFAULT_NOTICE_DURATION,
 			} ),
-			onError: () => errorNotice( translate( 'Unable to remove tag from list' ) ),
+			onError: () => errorNotice( translate( 'Unable to remove tag from list.' ) ),
```
Comment (a8ci18n) [inline client/state/data-layer/wpcom/read/lists/tags/delete/index.js:32]: :ok: This change will be queued for retranslation. We'll use the existing translations in the meantime.

**Review by jsnmoon — APPROVED** [review]

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5209367

Hi @bluefuton, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Unable to delete list.`
- `Unable to add feed to list.`
- `Unable to create new list.`
- `Unable to follow list.`
- `Unable to unfollow list.`
- `Unable to update list.`
- `Unable to add tag to list.`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5209367).
