### PR TITLE
Help: Fix help search placeholders

### LINKED ISSUE #1366: Help: Dummy text appears when hovering over placeholder search results
Steps to reproduce:
1. Visit https://wpcalypso.wordpress.com/help
2. Start searching under "How can we help?"
3. While the search results are loading, hover over the placeholder results

Expected behavior: I expected the placeholder to remain unchanged until the results loaded.

Actual behavior: The background changed to blue and dummy text appeared.

screen shot 2015-12-08 at 1 21 23 pm

### PR DESCRIPTION
**Pull request by omarjackman**
This pull request fixes the bug outlined in #1366.

To fix this I removed the dummy text and disabled clicking of the placeholder so that it no longer opens a new blank tab.

Before:

After:
screen shot 2015-12-09 at 11 40 06 pm

fixes #1366

### CODE REVIEW

File: client/me/help/help-results/item.jsx [hunk 1]
```diff
@@ -13,9 +13,15 @@ module.exports = React.createClass( {
 
 	mixins: [ React.addons.PureRenderMixin ],
 
+	onClick: function( e ) {
```
Comment (mtias) [inline client/me/help/help-results/item.jsx]: we tend to favor the verbose `event` :)

Comment (omarjackman) [inline client/me/help/help-results/item.jsx]: Force of habit, I changed it to `event`

**Comment by dllh** [comment]
I tested this and it works well. The only review comment so far was a minor thing that's been fixed, so I figure let's :ship:. One thing to consider (can be addressed in a future PR if desired): should we remove the hover color until we have results? I looked at a few other things like plugins, but I don't see anything else that has a contrasting hover state quite like what we have here that we could use as a model. The main issue for me here was the dummy text, and that's fixed here.

**Comment by mtias** [comment]
The sites popover has it:

image

Agreed it'd be better without it.

**Comment by mtias** [comment]
@omarjackman mind squashing this as it's a small change?
