### PR TITLE
AddOns: new design for the storage add-ons card

### LINKED ISSUE #95416: Plans Grid: add-on pricing is recalculated unnecessarily dozens of times
### Quick summary

Add-on prices are unnecessarily recalculated dozens of times when invoked as part of the PlansFeaturesMain component

Discovered in https://github.com/Automattic/wp-calypso/pull/95369

### Steps to reproduce

Add logging in the memoized function of `packages/data-stores/src/add-ons/hooks/use-add-on-prices.ts`. Note that the function is invoked repeatedly, even when values haven't updated.

It seems like the `product` or `quantity` dependencies aren't stable? Perhaps object reference / memory address changes?

### What you expected to happen

The price shouldn't be recalculated dozens of times, especially when return values aren't changing

### What actually happened

Unnecessary recalculations

### PR DESCRIPTION
**Pull request by aneeshd16**
Fixes https://github.com/Automattic/martech/issues/3677
Fixes https://github.com/Automattic/wp-calypso/issues/95416

## Proposed Changes

* Updates the design for the storage add-on on the AddOns page. All storage add-on cards are replaced with a single storage card with a dropdown to allow users to select the desired storage. The dropdown values represent additional storage to be added.
* Also fixes the issue described in https://github.com/Automattic/wp-calypso/issues/95416, by memoizing some arrays. More details are in the code comments.

## Why are these changes being made?

* p58i-jlJ-p2

## Testing Instructions

* Go to `/add-ons/<site slug>`.
* Confirm that a single storage add-ons card is present and it matches the design (3De4YM0tRV3Qs691ui6QAW-fi-7996_5289)
image

* Opening the dropdown should show add-on values up to a maximum of 350GB.
image

* Select any add-on from the list. **Note the price mentioned - this should be the same as the price shown on the checkout** page. (Monthly price * 12). Click on the "Buy add-on" button.
* In the following examples, the 200GB add-on has been purchased.
* Go back to `/add-ons/<site slug>`.
* Confirm that the space used is `203GB`. (200GB + 53GB platform default) (The site is on a Business plan)
* Confirm that the dropdown values only contain add-ons till 150GB. (Since the maximum storage possible is 400GB).
* image

* The dropdown and CTA should not be shown if the maximum storage has been purchased.
image

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: packages/data-stores/src/add-ons/add-ons-list.ts [hunk 1]
```diff
@@ -22,85 +22,85 @@ import spaceUpgradeIcon from './icons/space-upgrade';
...
+		addOnSlug: ADD_ON_350GB_STORAGE,
+		productSlug: PRODUCT_1GB_SPACE,
+		featureSlugs: null,
+		icon: spaceUpgradeIcon,
+		quantity: 350,
+		name: i18n.translate( '%d GB Storage', { args: [ 350 ] } ),
+	},
+];
 
+export const getAddOnsList = (): AddOnMeta[] => {
```
Comment (aneeshd16) [inline packages/data-stores/src/add-ons/add-ons-list.ts:103]: This function created a new array on every call. I have moved the array outside the function's scope so that the same reference is passed as the return value.

File: packages/data-stores/src/add-ons/hooks/use-add-on-prices.ts [hunk 2]
```diff
@@ -17,7 +18,10 @@ export const createAddOnPriceKey = ( { productSlug, quantity }: AddOnMeta ) => {
 };
 
 export const useAddOnPrices = ( addOnMetas: AddOnMeta[] ) => {
-	const productSlugs = addOnMetas.map( ( { productSlug } ) => productSlug );
+	const productSlugs = useMemo(
+		() => addOnMetas.map( ( { productSlug } ) => productSlug ),
+		[ addOnMetas ]
+	);
```
Comment (aneeshd16) [inline packages/data-stores/src/add-ons/hooks/use-add-on-prices.ts:24]: `.map` creates a new array on every call. So the `useMemo` function below, which uses `productSlugs` as a dependency, could not memoize the return value since the reference changed on every render.

File: client/my-sites/add-ons/components/storage-add-ons-card.tsx
Comment (aneeshd16) [inline client/my-sites/add-ons/components/storage-add-ons-card.tsx:1]: This component borrows heavily from https://github.com/Automattic/wp-calypso/blob/trunk/packages/plans-grid-next/src/components/shared/storage/components/storage-dropdown.tsx

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17235217

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @aneeshd16 for including a screenshot in the description! This is really helpful for our translators.

**Review by oswian — APPROVED** [review]
Tests well and the code changes LGTM.

**Comment by oswian** [comment]
One thing I just noticed is that the updated version no longer displays '✔️ Purchased', and so the status of this addon feels a little less clear. Particularly because the other addons display a similar 'status' message. Was this intentional?

| PR | Prod |
| -- | -- |
|CleanShot 2025-02-10 at 19 54 02@2x|CleanShot 2025-02-10 at 19 54 05@2x|
