### PR TITLE
Reader: handle full-post 404s more gracefully

### LINKED ISSUE #3860: Reader: handle full-post 404s more gracefully
**Steps to reproduce:**
Visit a non-existent full post link (example: https://wordpress.com/read/feeds/41325786/posts/121321321)

**What I expected:**
A 404 page just like our other pages:
23caa2f4-dfd1-11e5-9ed6-eeef00bb1f56

**What I saw instead:**
A blank page with a blavatar and some text:
screenshot 2016-03-08 11 44 11

If you also happen to be following that site, the same thing is being displayed but with a Following button:
screenshot 2016-03-08 11 45 28

The "Back" arrow is also only partially showing:
screenshot-2016-03-08-11 46 02

Related to https://github.com/Automattic/wp-calypso/issues/3681 and https://github.com/Automattic/wp-calypso/issues/3680.

/cc @bluefuton

### PR DESCRIPTION
**Pull request by lamosty**
Fixes #3860.

## Testing

Visit a non-existent full post link; examples:
- http://calypso.localhost:3000/read/feeds/41325786/posts/121321321
- http://calypso.localhost:3000/read/feeds/41325786/posts/somel3tt3rs

You should see this:

instead of this:
screenshot 2016-03-08 11 44 11

## Todo:

- [ ] Code review.
- [x] Fix `Uncaught TypeError: Cannot read property 'componentDidLeave' of undefined` when closing the full post dialog with the back arrow.
- [x] Apply this 404 handler to other reader screens (e.g.: `blogPost`)

/cc @jancavan

### CODE REVIEW

File: client/reader/controller.js [hunk 1]
```diff
@@ -58,14 +58,11 @@ function trackScrollPage( path, title, category, readerView, pageNum ) {
 
 // Listen for route changes and remove the full post dialog when we navigate away from it
 pageNotifier( function removeFullPostOnLeave( newContext, oldContext ) {
-	if ( ! oldContext ) {
```
Comment (lamosty) [inline client/reader/controller.js]: I removed this check because I think it is redundant and was accidentally left. On line 63, we firstly check if `oldContext` exists before using it.

File: client/reader/controller.js [hunk 2]
```diff
@@ -58,14 +58,11 @@ function trackScrollPage( path, title, category, readerView, pageNum ) {
...
-		return;
-	}
-
 	const fullPostViewRegex = /^\/read\/(blogs|feeds)\/([0-9]+)\/posts\/([0-9]+)$/i;
 
 	if ( ( ! oldContext || oldContext.path.match( fullPostViewRegex ) ) && ! newContext.path.match( fullPostViewRegex ) ) {
 		newContext.store.dispatch( hideReaderFullPost() );
+		removeFullPostDialog();
```
Comment (lamosty) [inline client/reader/controller.js]: I'm adding this line because we need to remove the full post dialog on navigating away from it. When there was no "Stream Not Found" page, it was possible to navigate away from the dialog only through closing it, which called the `removeFullPostDialog` method. But now, user can navigate to other parts of Calypso through (e.g.) sidebar, so we must make sure the full post dialog is always removed, no matter how it is closed.

Also, the comment
> // Listen for route changes and remove the full post dialog when we navigate away from it
has it written in it. :laughing:

File: client/reader/controller.js [hunk 3]
```diff
@@ -296,7 +293,10 @@ module.exports = {
 					onClose: function() {
 						page.back( context.lastRoute || '/' );
 					},
-					onClosed: removeFullPostDialog
+					onClosed: removeFullPostDialog,
+					onPostNotFound: function() {
+						module.exports.sidebar( context, next )
```
Comment (lamosty) [inline client/reader/controller.js]: I don't like this very much, but how else would I display sidebar from within `reader/full-post` component?

File: client/reader/controller.js (hunk 2 above)
Comment (blowery) [inline client/reader/controller.js]: The dispatch on the line above should trigger the full post dialog to close... Is that not working?

**Comment by jancavan** [comment]
@lamosty Looking good! Just slightly off-center though. A quick look at inspect shows me that the `<main>` tag is outside `wp-content` when it should be inside it.

Example: https://wordpress.com/tag/discoverburt

**Comment by lamosty** [comment]
@jancavan thanks! Oh, I see. I figured another way how to do this. What do you think?

@blowery I rebased my last commit and your note is lost, I'm sorry :cry:. You are right about that if I dispatch `hideReaderFullPost()`, the dialog is removed. I just didn't understand the whole flow before (namely that there are animations). Thanks.

**Comment by jancavan** [comment]
@lamosty Nice! It's centered now :+1: 

The 404 only seems to work for http://calypso.localhost:3000/read/feeds/41325786/posts/121321321 and random numbers, but adding a letter in goes back to its previous state:

screenshot 2016-03-15 12 12 21

Can we get it to work for anything that does not exist in `/read/feeds/`? It works for `/read/blogs/`.

**Comment by lamosty** [comment]
I see. Let's see what we can do about that.

Both `/read/blogs/` and `/read/feeds/` show the "Sorry, we can't find that stream.", so that's not an issue. Next, if you go to either `/read/blogs/:blog_id/posts/` or `/read/feeds/:feed_id/posts/`, it will redirect you to `/read/blogs/:blog_id/` and `/read/feeds/feed_id/`, respectively.

So the only place where we should show 404 is `/read/feeds/:feed_id/posts/:post` and `/read/blogs/:blog_id/posts/:post`, whether it contains digits or letters. What do you think?

**Comment by blowery** [comment]
@lamosty can you try this on top of https://github.com/Automattic/wp-calypso/pull/4096 and https://github.com/Automattic/wp-calypso/pull/4094 ?

**Comment by blowery** [comment]
cc @TooTallNate

**Comment by lamosty** [comment]
@blowery Thanks for your help but trying it on top of that PRs doesn't seem to help. I think the problem lies on the API server, specially in the regex matching valid post URls (you metioned `'/read/feed/%s/posts/%d'` on Slack). I can't inspect the code there, but I speculate that it simply returns when that regex is not matched. I think this mainly because when I try to fetch a non-existent post with using only digits as postId, the server replies with no main error code. Instead, it sends back info about the post with `status_code: 404`.

To be honest, I do not know how to proceed with this PR due to the fact that I can't see what's happening on the other side. Or maybe I'm missing something and looking in the wrong place.

### More context/try it yourself/how I test this

I added the following two lines below [this one](https://github.com/Automattic/wp-calypso/blob/master/client/lib/feed-post-store/post-batch-fetcher.js#L72):

```js
console.log('got error: ', error);
console.log('got data: ', data);
```

__Going to http://calypso.localhost:3000/read/feeds/2251751/posts/96367200443a__:


__Going to http://calypso.localhost:3000/read/feeds/2251751/posts/96367200443__:


When I don't receive any post (no entry in the `data` array except `_headers`), the action `RECEIVE_FEED_POST` is not dispatched and the `_state` of the post in `reader/full-post` is always `pending`. That's why we see this:



instead of "Stream not found" 404 error message.

I was thinking that maybe I could dispatch the action manually with a mocked up post with `status_code: 404` when no post arrives from the API server, but I don't like this solution as it might disrupt the natural flow of received posts in `lib/feed-post-store`.

## Proposed solution

Could we simply modify the regex on the API server to match [a-zA-Z0-9] so that it would send a standard response with the post of `status_code: 404` in it? Would it break something/reduce security?

**Comment by blowery** [comment]
I really rather figure out why the 404 isn't coming through the client-side API wrapper. The server is correctly responding with a 404.

**Comment by lamosty** [comment]
@jancavan @blowery Could you review/check the PR again please? :)

**Comment by TooTallNate** [comment]
> I really rather figure out why the 404 isn't coming through the client-side API wrapper. The server is correctly responding with a 404.

I looked into this real quick - indeed the API endpoint correctly returns a 404 status code. The issue appears to be with the use of the "batch" API endpoint; wpcom.js should probably have special handling for that endpoint or a special API for batching requests, so that it can do some post-processing on the batch-body to create proper `WPError` objects on the client-side.

/cc @retrofox

**Comment by lamosty** [comment]
@TooTallNate: I looked into this again and turned out the API endpoint doesn't return 404. The actual url which is sent is this: `/v1.3/batch?http_envelope=1&urls[]=/read/feed/2251751/posts/97005018s`. API returns `200`. You can test it on API console.

However, as @blowery hinted, I added a simple regex check even before the URL is sent. If it doesn't match, it means that either `feed_id`, `post_id` or `blog_id` is not valid (can contain only digits). That solved the problem.

Thanks for looking. :+1:

**Comment by retrofox** [comment]
I think we have two things here: First one is the status code gotten from the `/batch` endpoint response. And the second one is the status code for each url passed through of its parameters.

For instance if you hit to REST-API with `https://public-api.wordpress.com/rest/v1.2/batch` you will get `400` -> `Invalid request input` because you are forgetting pass the `urls` array.

But if you pass, for instance, three urls which two of them are ok and one of them the resource doesn't exist then you should get a status code for each url.

image

However the status code of the `/batch` endpoint should be `200` because the request is rightly done.

**Comment by lamosty** [comment]
@retrofox: I see, but try this .

It produces , no `status_code`. It's probably because the feed post doesn't match a regex as it contains a letter at the end and feed post IDs can contain only digits. Still strange behavior though.

**Comment by retrofox** [comment]
@lamosty yeah, it seems like the `/batch` endpoint isn't handling each url rightly. Maybe the response should be something like ...

```json
{
  "/read/feed/2251751/posts/97005018s": {
    "error": {},
    "statusCode": 404
  }
}
```

but, again, I think the main statusCode should be `2xx`.

**Comment by lamosty** [comment]
@retrofox yes, that's what I was thinking too. It should send `status_code: 404` whether the feed post contains letters or digits or anything not valid and `200` in the response headers. Unfortunately, I don't have access to the API server, so can't really do anything about it there. 

Anyways, thanks for chiming in.

**Comment by TooTallNate** [comment]
The batch API endpoint now gives an object of `{ status_code: 404 }` for non-existing API endpoints, as expected.

File: client/lib/feed-post-store/actions.js [hunk 4]
```diff
@@ -14,7 +14,7 @@ feedPostBatcher = new PostBatcher( {
 	buildUrl: function( postKey ) {
 		return '/read/feed/' + encodeURIComponent( postKey.feedId ) + '/posts/' + encodeURIComponent( postKey.postId );
 	},
-	resultKeyRegex: /\/read\/feed\/(\d+)\/posts\/(\d+)/,
+	resultKeyRegex: /\/read\/feed\/(\w+)\/posts\/(\w+)/,
```
Comment (lamosty) [inline client/lib/feed-post-store/actions.js]: While valid feed/blog ID and feed/blog post ID contains only digits, a user can navigate to feed/blog with letters in its ID, which causes 404 to be shown, but we need to modify the regexp here for that to work.

File: client/lib/feed-post-store/index.js [hunk 5]
```diff
@@ -198,7 +198,7 @@ function receivePostFromPage( newPost ) {
 }
 
 function receivePost( feedId, postId, post ) {
-	if ( post.errors ) {
+	if ( post.errors || post.status_code === 404 ) {
```
Comment (lamosty) [inline client/lib/feed-post-store/index.js]: @TooTallNate:

> The batch API endpoint now gives an object of { status_code: 404 } for non-existing API endpoints, as expected.

That's nice. However, it doesn't give the `errors` object, which is expected. To countermeasure, let's look for just `status_code` as well.

File: client/lib/feed-post-store/post-batch-fetcher.js [hunk 6]
```diff
@@ -88,8 +88,8 @@ assign( PostBatchFetcher.prototype, {
 					return;
 				}
 
-				containerId = +match[ 1 ];
-				postId = +match[ 2 ];
+				containerId = match[ 1 ];
```
Comment (lamosty) [inline client/lib/feed-post-store/post-batch-fetcher.js]: Now that feed/blog ID and feed/blog post ID can also contain letters...

File: client/reader/index.js [hunk 7]
```diff
@@ -46,7 +46,7 @@ module.exports = function() {
 
 		// Feed full post
 		page( '/read/post/feed/:feed_id/:post_id', controller.legacyRedirects );
-		page( '/read/feeds/:feed/posts/:post', updateLastRoute, controller.feedPost );
+		page( '/read/feeds/:feed/posts/:post', updateLastRoute, controller.sidebar, controller.feedPost );
```
Comment (lamosty) [inline client/reader/index.js]: We want to show the sidebar on 404, so we need to render (and hide) it even if it is not a 404.

File: client/lib/feed-post-store/index.js (hunk 5 above)
Comment (blowery) [inline client/lib/feed-post-store/index.js]: @lamosty as long as we're here... can you take a peek at everyone who calls into here and make sure we're never passing null? Or add a `! post` check and bail if the post is null? Right now a null post would blow up this method and throw.

File: client/lib/feed-post-store/index.js [hunk 8]
```diff
@@ -206,7 +206,7 @@ function receivePost( feedId, postId, post ) {
 }
 
 function receiveBlogPost( blogId, postId, post ) {
-	if ( post.errors ) {
+	if ( post.errors || post.status_code === 404 ) {
```
Comment (blowery) [inline client/lib/feed-post-store/index.js]: same here, a falsey check would be appreciated

File: client/lib/feed-post-store/post-batch-fetcher.js (hunk 6 above)
Comment (blowery) [inline client/lib/feed-post-store/post-batch-fetcher.js]: have to be very careful with this one... Maybe check it with `isNumeric` from lodash and convert to a number if true

File: client/reader/full-post/index.jsx [hunk 9]
```diff
@@ -509,7 +513,8 @@ FullPostContainer = React.createClass( {
 	},
 
 	render: function() {
-		var passedProps = omit( this.props, [ 'postId', 'feedId' ] );
+		var passedProps = omit( this.props, [ 'postId', 'feedId' ] ),
```
Comment (blowery) [inline client/reader/full-post/index.jsx]: can these be `const` instead of `var`?

**Comment by blowery** [comment]
Looks good, works well. Few little comments and then I think we're ready to go.

File: client/reader/full-post/index.jsx (hunk 9 above)
Comment (lamosty) [inline client/reader/full-post/index.jsx]: I didn't alter this line, but yeah, they are not assigned again so can be `const`. Hmm, the whole file is written in ES5, not ES6 so should I change these two lines to `const` and leave the other be?

File: client/lib/feed-post-store/post-batch-fetcher.js (hunk 6 above)
Comment (lamosty) [inline client/lib/feed-post-store/post-batch-fetcher.js]: Alright, but why does it have to be numeric?

File: client/lib/feed-post-store/index.js (hunk 5 above)
Comment (lamosty) [inline client/lib/feed-post-store/index.js]: Seems like we are not passing `null`, but just to be sure, I'll do it.

File: client/lib/feed-post-store/post-batch-fetcher.js (hunk 6 above)
Comment (blowery) [inline client/lib/feed-post-store/post-batch-fetcher.js]: because we use it as a key into a map later on. I'd rather not mix numeric and string keys.

Comment (blowery) [inline client/lib/feed-post-store/post-batch-fetcher.js]: I know that sites can be fetched by their slug, but if /where we're doing that, it's more a bug than a feature. We should be storing things by blog ID, never by slug.

Comment (lamosty) [inline client/lib/feed-post-store/post-batch-fetcher.js]: Ah, right. :+1:

Comment (blowery) [inline client/lib/feed-post-store/post-batch-fetcher.js]: Though that's really a concern for the store, not for the batcher. Hrm. Maybe just leave this as is...

File: client/reader/controller.js [hunk 10]
```diff
@@ -306,7 +316,10 @@ module.exports = {
 					onClose: function() {
 						page.back( context.lastRoute || '/' );
 					},
-					onClosed: removeFullPostDialog
+					onClosed: removeFullPostDialog,
+					onPostNotFound: function() {
+						renderPostNotFound( i18n.translate( 'Feed post not found' ) );
```
Comment (blowery) [inline client/reader/controller.js]: these can both be just "Post not found". There's no diff to user if it's a feed post or a blog post.

Comment (lamosty) [inline client/reader/controller.js]: I see, good spot.

**Comment by lancewillett** [comment]
@lamosty @blowery This one looks stalled... :/ but close. Can you guys push it in?

**Comment by lamosty** [comment]
@lancewillett Thanks for bringing this up!

I've rebased the code on top of master and seems to be working. I think the current approach is still valid.

@blowery Could you please test/review it once more?

**Comment by apeatling** [comment]
@blowery reping. If we can't get further review and thumbs up here then we should close this.

**Comment by blowery** [comment]
Code still looks good, testing now

**Comment by apeatling** [comment]
I didn't see that you now have 3 pings in 24 hours. :) Thanks.

**Comment by blowery** [comment]
@apeatling @blowery No worries. :) Merging once tests pass.
