### PR TITLE
Focused-Launch: Fix scroll to top when transitioning between routes

### LINKED ISSUE #47325: Focused Launch: Scroll to top when transitioning between routes.
#### Steps to reproduce

1. Visit `/page/SANDBOXED_UNLAUNCHED_SITE_ID_CREATED_WITH_START.wordpress.com/home?flags=create/focused-launch-flow-calypso`. Focused Launch modal should appear
2. Re-size the window reducing the height so a vertical scrollbar appears.
3. Scroll down as far as you can, but make sure "View all domains" is still visible.
4. Click on the "View all domains" link. The new view is at the same scroll position, cutting off information at the top.

#### What I expected

* That the view we transitioned to (Domains steps in this scenario) started by scrolling to the top.
* I would also expect that when you hit "Go back" it would preserve the scroll position of the summary view

#### What happened instead

* We were partly scrolled down the page, hiding information at the top.

#### Screenshot / Video

* [Video](https://www.loom.com/share/1149c90fcaa24bdeb54e1b0c0f8536f0)

### PR DESCRIPTION
**Pull request by StefanNieuwenhuis**
We want each view in the Focused Launch to scroll to the top when transitioning between routes since information is "hidden" from the user's view when the scrolling position is preserved. This PR introduces a ScrollToTop component that is triggered on every route transition in the Focused Launch. It does the heavy-scroll-to-top-lifting on every route transition by hooking into the react-router-doms features.

#### Changes proposed in this Pull Request

* Every view in the Focused Launch should be scrolled to the top of the page automatically

#### Testing instructions
* Visit `/page/SANDBOXED_UNLAUNCHED_SITE_ID_CREATED_WITH_START.wordpress.com/home?flags=create/focused-launch-flow-calypso`. Focused Launch modal should appear
* Re-size the window reducing the height so a vertical scrollbar appears.
* Scroll down as far as you can, but make sure "View all domains" is still visible.
* Click on the _"View all domains"_ link. The new view is scrolled to the top of the page, showing all information.

Fixes #47325

### CODE REVIEW

File: packages/onboarding/src/scroll-to-top/index.tsx [hunk 1]
```diff
@@ -0,0 +1,17 @@
+/**
+ * External dependencies
+ */
+import * as React from 'react';
+import { useLocation } from 'react-router-dom';
+
+const ScrollToTop: React.FunctionComponent = () => {
+	const { pathname } = useLocation();
+
+	React.useEffect( () => document.querySelector( '.components-modal__content' )?.scrollTo( 0, 0 ), [
```
Comment (tjcafferkey) [inline packages/onboarding/src/scroll-to-top/index.tsx]: Could we pass the selector as a prop in to the component to increase the flexibility of this component?

`<ScrollToTop selector=".components-modal__content" />`

File: packages/onboarding/src/scroll-to-top/test/index.tsx [hunk 2]
```diff
@@ -0,0 +1,30 @@
+/**
```
Comment (tjcafferkey) [inline packages/onboarding/src/scroll-to-top/test/index.tsx:1]: Good to see tests!

File: packages/onboarding/src/scroll-to-top/index.tsx [hunk 3]
```diff
@@ -0,0 +1,17 @@
+/**
+ * External dependencies
+ */
+import * as React from 'react';
+import { useLocation } from 'react-router-dom';
+
+const ScrollToTop: React.FunctionComponent = () => {
```
Comment (tjcafferkey) [inline packages/onboarding/src/scroll-to-top/index.tsx]: Seeing as we only scroll to top for [specific viewports in Gutenboarding](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/index.tsx#L184) I wonder if it would be worth passing in viewports this would apply to (this would default to all viewports) and use the [useViewportMatch](https://github.com/Automattic/wp-calypso/blob/trunk/packages/domain-picker/src/domain-picker/suggestion-item.tsx#L64) hook

`<ScrollToTop viewport={['small', '>']} />`

And then we could use it like so:

`const matchesViewport = viewport ? useViewportMatch( viewport?.join(',') ) : true;`

Just a thought to make it more flexible although we could do this another time as we don't need this feature right now and is a little scope-creep.

Comment (StefanNieuwenhuis) [reply packages/onboarding/src/scroll-to-top/index.tsx]: Hmm, I agree that it's a bit of a scope creep. I've created an issue ([#48161](https://github.com/Automattic/wp-calypso/issues/48161)) for this.

**Review by tjcafferkey — APPROVED** [review]
LGTM 👍🏻

File: packages/onboarding/src/scroll-to-top/index.tsx [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+
+const ScrollToTop: React.FunctionComponent< ScrollToTopProps > = ( { selector } ) => {
+	const { pathname } = useLocation();
+
+	React.useEffect( () => document.querySelector( selector )?.scrollTo( 0, 0 ), [
+		selector,
+		pathname,
+	] );
+
+	return null;
```
Comment (razvanpapadopol) [inline packages/onboarding/src/scroll-to-top/index.tsx:18]: Why aren't we using a custom hook instead of having a component returning `null`?

Comment (tjcafferkey) [reply packages/onboarding/src/scroll-to-top/index.tsx:18]: Good point/spot @razvanpapadopol. @StefanNieuwenhuis could we update this to become a hook?

File: packages/onboarding/src/scroll-to-top/index.tsx [hunk 5]
```diff
@@ -0,0 +1,22 @@
...
+import { useLocation } from 'react-router-dom';
+
+type ScrollToTopProps = {
+	selector: string;
+};
+
+const ScrollToTop: React.FunctionComponent< ScrollToTopProps > = ( { selector } ) => {
+	const { pathname } = useLocation();
+
+	React.useEffect( () => document.querySelector( selector )?.scrollTo( 0, 0 ), [
```
Comment (razvanpapadopol) [inline packages/onboarding/src/scroll-to-top/index.tsx]: While I understand the flexibility of having a prop such as `selector` here, I have two suggestions:
- can we make it optional and when left undefined just use `window.scrollTo()`?
- for greater stability can we use a `ref` instead? ([example](https://levelup.gitconnected.com/react-tips-scroll-to-element-load-fonts-run-setstate-in-sequence-2d73c9f02ae1#d959))

File: packages/onboarding/src/scroll-to-top/test/index.tsx (hunk 2 above)
Comment (yansern) [reply packages/onboarding/src/scroll-to-top/test/index.tsx:1]: +1

File: packages/onboarding/src/scroll-to-top/index.tsx (hunk 4 above)
Comment (StefanNieuwenhuis) [reply packages/onboarding/src/scroll-to-top/index.tsx:18]: We're unable to use a custom hook in the `<Router/>` and in order to comply with best practices, we have to use a component (see [react-router-dom docs](https://reactrouter.com/web/guides/scroll-restoration/scroll-to-top)). 

In other use-cases a hook absolutely makes sense but that's out of scope for this issue.

File: packages/onboarding/src/scroll-to-top/index.tsx (hunk 5 above)
Comment (StefanNieuwenhuis) [reply packages/onboarding/src/scroll-to-top/index.tsx]: > can we make it optional and when left undefined just use `window.scrollTo()`?

Done ✅

> for greater stability can we use a `ref` instead? 

We can use a `ref` but that means that we have to pass it all the way from the parent's parent. We have to convert them to `React.forwardRef()` and I'm unsure what the consequences are. Besides that, we have to wrap the `<Router/>` in `<ScrollToTop/>` which is against best practices (see [react-router docs](https://reactrouter.com/web/guides/scroll-restoration/scroll-to-top)). 

To conclude: It becomes ugly pretty fast and we cannot oversee the consequences. 
We're going for the selector option w/ a fallback to `window.scrollTo()`.

**Review by razvanpapadopol — APPROVED** [review]
🚀
