### PR TITLE
Checkout: Fix errors when removing item from sidebar cart

### LINKED ISSUE #1286: Checkout: Errors when removing item from sidebar cart
> Uncaught TypeError: Cannot read property 'product_name' of undefined

To reproduce:

1. Add an upgrade to your cart for a new site or an existing one. e.g.: visit the plans page for an existing site (https://wordpress.com/plans/example.wordpress.com) and click "Upgrade Now".
2. Click the "x" next to the upgrade in the Checkout page sidebar.
3. The page hangs on a loading screen and errors appear in the console.
4. The error persists upon reloading the Checkout page.

In screenshots:
screen shot 2015-12-04 at 5 50 08 pm

screen shot 2015-12-04 at 5 51 14 pm

screen shot 2015-12-04 at 5 51 52 pm

### PR DESCRIPTION
**Pull request by gziolo**
Fixes #1286.

To reproduce before this change:

1. Add an upgrade to your cart for a new site or an existing one. e.g.: visit the plans page for an existing site (https://wordpress.com/plans/example.wordpress.com) and click "Upgrade Now".
2. Click the "x" next to the upgrade in the Checkout page sidebar.
3. The page hangs on a loading screen and errors appear in the console.
4. The error persists upon reloading the Checkout page.

I was able to reproduce it only when I had **free credit** assigned to my account.

screen shot 2015-12-04 at 5 51 52 pm

### Testing
1. Assign free credits to your account.
2. Try to reproduce this error.

### CODE REVIEW

File: client/my-sites/upgrades/checkout/free-trial-confirmation-box.js [hunk 1]
```diff
@@ -40,8 +42,14 @@ var FreeTrialConfirmationBox = React.createClass( {
...
+		const planProduct = find( this.props.cart.products, isPlan );
+
+		return ( planProduct && planProduct.product_name ) || '';
+	},
+
+	render() {
+		const classSet = classNames( {
 			'credits-payment-box': true,
 			selected: this.props.selected === true
 		} );
```
Comment (gziolo) [inline client/my-sites/upgrades/checkout/free-trial-confirmation-box.js]: Personally I would render null when `this.props.selected` is set to `false`, but I didn't want to touch it in this PR.

File: client/my-sites/upgrades/checkout/free-trial-confirmation-box.js [hunk 2]
```diff
@@ -40,8 +42,14 @@ var FreeTrialConfirmationBox = React.createClass( {
 		);
 	},
 
-	render: function() {
-		var classSet = classNames( {
+	getProductName() {
+		const planProduct = find( this.props.cart.products, isPlan );
+
+		return ( planProduct && planProduct.product_name ) || '';
```
Comment (gziolo) [inline client/my-sites/upgrades/checkout/free-trial-confirmation-box.js]: As far I could see this is the case only when `this.props.selected` is set to `false`;

**Comment by janm6k** [comment]
:+1: I have confirmed this fixes the problem. The amount of free credits has to be lower than the cost of the product to reproduce this.

**Comment by sirbrillig** [comment]
Thanks!
