### PR TITLE
Fix | Disable Restore buttons when one is already in progress

### LINKED ISSUE #61066: Backup: Improve UX, disable all Restore buttons if a restore is ongoing
### Quick summary

When there's an ongoing Restore, `Jetpack > Backup` will still show the option to start a new Restore, which is misleading for users.

It should be like `Jetpack > Activity Log` where all Restore buttons are disabled.

This appears to just be an issue on the front-end. On the back-end, if there's an ongoing restore, a new one won't get started simultaneously. 

Enhancement suggestions for `Jetpack > Backup`, when a restore is ongoing: 

* All Restore button should be disabled (greyed out), just like in Activity Log
* Have the below progress area show automatically
image1

### Steps to reproduce

1. Start a Restore from `Jetpack > Backup` or `Jetpack > Activity Log`
2. Go to `Jetpack > Backup`, then check different backup, the Restore button is active

### What you expected to happen

Restore button should be all disabled (greyed out), just like in Activity Log.

### What actually happened

Restore button is active under `Jetpack > Backup`.

We can click the Restore of any backup, though it looks like the progress bar reflects the current restore ongoing, but it's confusing since the restore date doesn't match (see example in video, restored date is Feb 13, towards end I select a restore for Feb 10) 

https://user-images.githubusercontent.com/15944096/153744044-18c3a401-e45d-4662-85a0-0b4d57caba95.mov

### Context

Just testing around.

Test on self-hosted site, same happens. Will transfer to Jetpack repo.

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

_No response_

### Browser, operating system and other notes

_No response_

### Reproducibility

_No response_

### Severity

_No response_

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by manzoorwanijk**
#### Changes proposed in this Pull Request

* Disable **Restore to this point** buttons when a restore is already in progress.

#### Testing instructions

* Create JN Site and add a back up plan
* Enable Restore by adding SSH/SFTP credentials
* Boot up this PR and goto `http://calypso.localhost:3000/backup/:site`
* Wait for a backup to complete or Queue one using Rewind Debugger
* Restore a back up
* Goto `http://calypso.localhost:3000/backup/:site` again
* Confirm that **Restore to this point** is disabled for the latest backup
* Confirm that **Restore to this point** in all the previous backup actions is disabled

Fixes #61066 / 1164141197617539-as-1201825952025343/f

BEFORE

https://user-images.githubusercontent.com/18226415/153870137-9d3702c8-32b1-4cff-803c-3e6afa1d990a.mov 

AFTER

https://user-images.githubusercontent.com/18226415/153869874-928320c4-4445-44d8-9170-91583666251e.mov

### CODE REVIEW

File: client/components/jetpack/daily-backup-status/action-buttons.jsx [hunk 1]
```diff
@@ -51,7 +53,7 @@ const RestoreButton = ( { disabled, rewindId } ) => {
 			isPrimary
 			className="daily-backup-status__restore-button"
 			href={ href }
-			disabled={ ! canRestore }
+			disabled={ isRestoreDisabled }
```
Comment (vitozev) [inline client/components/jetpack/daily-backup-status/action-buttons.jsx:56]: I think we should make sure that the button isn't clickable by changing the `href` attribute as well? I know this is a problem with the `Button` component itself, but can't we fix it in general by adding `pointer-events: none` to the class responsible for the disabled state of the button / or using attribute selector?

Comment (manzoorwanijk) [reply client/components/jetpack/daily-backup-status/action-buttons.jsx:56]: You can see just above that `href` is set to `undefined` if `isRestoreDisabled` is `true`.

Comment (vitozev) [reply client/components/jetpack/daily-backup-status/action-buttons.jsx:56]: Thanks, I didn't notice that.

**Review by vitozev — APPROVED** [review]
LGTM!
