### PR TITLE
Fix plugin breadcrumb loops

### LINKED ISSUE #67888: Marketplace: New plans page breadcrumbs
Try visiting the plans page through a link [with the flag](https://github.com/Automattic/wp-calypso/pull/67770) enabled then clicking a breadcrumb back to the plugin and then back to install. Looks like a loop, we probably need to reset the state somewhere.

- [ ] This thing doesn't happen:
Screenshot 2022-09-16 at 15-43-14 Plugins Plan Upgrade ‹ Business - Simple Site — WordPress com

### PR DESCRIPTION
**Pull request by DustyReagan**
#### Proposed Changes

This PR aims to prevent breadcrumb loops like the following:

Screenshot 2022-09-16 at 15-43-14 Plugins Plan Upgrade ‹ Business - Simple Site — WordPress com

This is done by updating `BREADCRUMB_APPEND_ITEM` to check if the new item already exists, clear the breadcrumbs back to & including the existing item, & finally add the new item.

This means breadcrumbs should never have duplicate items, and any time we see an existing item, we rollback the breadcrumbs to when it was first introduced.

> **Note**
> Just FYI this PR does not address the breadcrumbs site switching issue.

#### Testing Instructions

> To test with the "plugins-plans-page", enable the config feature flag by
> 
> - Adding `"plugins-plans-page": true,` to `config/development.json`
> - Restart your localhost with `yarn` and `yarn start`

Plugins Plans page loop:
- Try visiting the plans page through a link with the config flag enabled
- then clicking a breadcrumb back to the plugin
- then back to install.

Deep breadcrumbs test:
- On a plan lower than business
- Go to the /plugins page
- Select a category
- Then search for term
- Then select a plugin
- Then try to install and end up on the Plugins Plans page
- Try going back with or without the help of the breadcrumbs

Ensure no regression is introduced with the Activity Log breadcrumb. [see this PR](https://github.com/Automattic/wp-calypso/pull/61044):

- Install mailpoet on your site
- Go to Jetpack -> Activity Log
- Click on MailPoet on the jetpack log
- Check if the breadcrumbs show only one item for MailPoet

Improvise to break the breadcrumbs.

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes? -- I intend to add a new e2e test during 20% time. 😅 
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] ~Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)~
- [ ] ~Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?~

Related to #67888

### CODE REVIEW

**Comment by DustyReagan** [comment]
I found one issue, but I don't think it's directly related to breadcrumbs, though its symptoms are seen using breadcrumbs.

- With "plugins-plans-page" config feature enabled
- On a plan lower than business
- Go to the /plugins page
- Select a category
- Then search for term
- Then select a plugin
- Then try to install and end up on the Plugins Plans page
- Now click on Search results in the breadcrumbs
- The URL changes correctly, but we're still on the Plugins Plans page 🤔 

I think this might be an issue for another PR, but I'm all eye and ears if anyone knows what's going here.

**Comment by lsl** [comment]
@cpapazoglou @claudiucelfilip thoughts?

File: client/my-sites/plugins/plugins-navigation-header/index.jsx [hunk 1]
```diff
@@ -115,34 +115,39 @@ const PluginsNavigationHeader = ( { navigationHeaderRef, categoryName, category,
...
-				label: translate( 'Plugins' ),
-				href: localizePath( `/plugins/${ selectedSite?.slug || '' }` ),
-				id: 'plugins',
-				helpBubble: translate(
-					'Add new functionality and integrations to your site with plugins.'
-				),
-			},
-		];
+		if ( breadcrumbs?.length === 0 || ( ! category && ! search ) ) {
+			dispatch( resetBreadcrumbs() );
```
Comment (DustyReagan) [inline client/my-sites/plugins/plugins-navigation-header/index.jsx:119]: If you go to Jetpack -> Activity Log -> Any Plugin, then use the side menu to click back to Plugins, breadcrumbs?.length > 0, so we need to check that category and search are empty. If they are we can `resetBreadcrumbs()` to start fresh and set 'Plugins' as the root breadcrumb.

**Review by claudiucelfilip — APPROVED** [review]
> I found one issue, but I don't think it's directly related to breadcrumbs, though its symptoms are seen using breadcrumbs.

@DustyReagan It looks like this is caused by a race condition in the Search component.
When you click the `Search Result` item:
1. first, you land on the correct `/plugins/:plugin/:site_id?` route. It detects the keyword and properly [starts rendering](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/plugins/controller.js#L108) the `PluginBrowser` component
2. when it reaches the `Search` component it [detects the keyword](https://github.com/Automattic/wp-calypso/blob/trunk/packages/search/src/search.tsx#L195) and tries to update the URL via [setQueryArgs](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/plugins/search-box-header/index.jsx#L11)
3. this function [uses](https://github.com/Automattic/wp-calypso/blob/trunk/client/lib/query-args/index.ts#L8) `window.location.href` but at this point, this still points to the Plans page
4. we then effectively get redirected back to the Plans page even though the URL now points to

Adding a `setTimeout` around `setQueryArgs` [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/plugins/search-box-header/index.jsx#L11) seems like an effective hack. 
A better way should be to use the `delaySearch` option we can [on the Search](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/plugins/search-box-header/index.jsx#L31) but it's ignored for this flow because `onSearch` is called directly [here](https://github.com/Automattic/wp-calypso/blob/trunk/packages/search/src/search.tsx#L195).

The breadcrumb fix looks good.

File: client/my-sites/plugins/plugins-navigation-header/index.jsx (hunk 1 above)
Comment (cpapazoglou) [reply client/my-sites/plugins/plugins-navigation-header/index.jsx:119]: Should we `resetBreadcrumbs()` as part of visiting any root page? Maybe we can hook this into the controller of those pages?

Comment (DustyReagan) [reply client/my-sites/plugins/plugins-navigation-header/index.jsx:119]: I think that sounds like a good idea. How would feel if we shipped this PR and created a follow up issue for that?

**Comment by lsl** [comment]
> Adding a setTimeout around setQueryArgs [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/plugins/search-box-header/index.jsx#L11) seems like an effective hack.

Can we fix the race condition?

> A better way should be to use the delaySearch option we can [on the Search](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/plugins/search-box-header/index.jsx#L31) but it's ignored for this flow because onSearch is called directly [here](https://github.com/Automattic/wp-calypso/blob/trunk/packages/search/src/search.tsx#L195).

Is delay search compatible with on-enter mode? I recall it had some issues with debouncing in Rolando's original PR but my memory on this is pretty murky.

See https://github.com/Automattic/wp-calypso/pull/62581 / https://github.com/Automattic/wp-calypso/pull/62573

**Comment by claudiucelfilip** [comment]
> Can we fix the race condition?

@lsl What do you think about using `page.current` instead of `location.href` [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/lib/query-args/index.ts#L8).

> Is delay search compatible with on-enter mode?

Good point. We could also just debounce the `useEffect` [search](https://github.com/Automattic/wp-calypso/blob/trunk/packages/search/src/search.tsx#L195) but I see there's a e2e [test](https://github.com/Automattic/wp-calypso/blob/trunk/packages/search/src/test/index.js#L175) right against this behavior.

It seems like addressing the `setQueryArgs` is the safer option.

File: client/my-sites/plugins/plugins-navigation-header/index.jsx (hunk 1 above)
Comment (DustyReagan) [reply client/my-sites/plugins/plugins-navigation-header/index.jsx:119]: Follow up [issue here](https://github.com/Automattic/wp-calypso/issues/68114). I'll have a look at this and e2e tests this 20% cycle. ☺️

**Comment by DustyReagan** [comment]
Thanks, @claudiucelfilip, and @lsl! I created an issue for the search component race condition [here](https://github.com/Automattic/wp-calypso/issues/68115). I'm going to go ahead and merge this PR.

**Comment by lsl** [comment]
Thanks for the new issue @DustyReagan.

> @lsl What do you think about using page.current instead of location.href [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/lib/query-args/index.ts#L8).

Not sure what it does but no concerns.

> Good point. We could also just debounce the useEffect [search](https://github.com/Automattic/wp-calypso/blob/trunk/packages/search/src/search.tsx#L195) but I see there's a e2e [test](https://github.com/Automattic/wp-calypso/blob/trunk/packages/search/src/test/index.js#L175) right against this behavior.

We ran into issues with debounce leading to the onEnter mode. I'm not opposed to changes here but from what I've seen from this so far I'd rather we just didn't use this component at all. Doesn't seem to do much for us since we just want an on enter effect.
