### PR TITLE
On mouse leave do not return early for expanded menus.

### LINKED ISSUE #49110: "Tools" menu items remain expanded after navigating to a different page
#### Steps to reproduce the behavior

1. Go to My Home
2. Hover on Tools
3. Click on Marketing
4. Click on My Home

I could not reproduce this with any other menu item, but an investigation into the cause might give hints on whether other menu items are affected.

#### What I expected to happen
The Tools menu should not be shown since I am not hovering on it.

#### What actually happened
The expanded (on hover) state of the Tools menu was shown.

### Browser / OS version
Chrome Version 87.0.4280.141 (Official Build) (x86_64), macOS Catalina 10.15.6

### Does this happen on simple or atomic sites or both?
Happens on both simple and atomic.
### Is there any console output or error text?
No
### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low
#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
image
Kapture 2021-01-21 at 16 23 04

### PR DESCRIPTION
**Pull request by cpapazoglou**
#### Changes proposed in this Pull Request

* Do not return early for "onLeave" event of expanded menus so that they don't keep hovering after navigating to another menu.

#### Testing instructions

**Before**
* Click any Calypso submenu (like Themes, Marketing, All Posts)
* Click "My Home"
* The menu from step (1) will appear hovered

https://user-images.githubusercontent.com/13387217/105375214-623c5600-5bbd-11eb-8269-83844745264c.mov

**After**
* Click any Calypso submenu (like Themes, Marketing, All Posts)
* Click "My Home"
* The menu from step (1) will **NOT** appear hovered

Fixes #49110

### CODE REVIEW

File: client/layout/sidebar/expandable.jsx [hunk 1]
```diff
@@ -87,7 +87,7 @@ export const ExpandableSidebarMenu = ( {
 	};
 
 	const onLeave = () => {
-		if ( expanded || isTouch || ! config.isEnabled( 'nav-unification' ) ) {
+		if ( isTouch || ! config.isEnabled( 'nav-unification' ) ) {
```
Comment (getdave) [inline client/layout/sidebar/expandable.jsx:90]: I wonder if a small comment here could help explain why the `onLeave` handler is necessary and why the behaviour needs to change for touch devices?

Just some context so that folks don't accidentally re-introduce a bug later. These issues are hard to spot and we don't have any test coverage 😢

**Review by getdave — APPROVED** [review]
I tested this on Calypso live as per the instructions at the reported Issue is no longer in evidence. 👏👏👏👏👏👏
