### PR TITLE
Use switch_theme hook for template part population

### LINKED ISSUE #38056: FSE: Remove Switch to Classic Editor from Help
image

The large button in Help allowing a switch to the Classic Editor feels out of place in the test-fse flow.

### LINKED ISSUE #38305: FSE "is active" status is flakey after activating a different FSE theme
This is an odd bug. Reproduce with the following:

1. Have an FSE site with an FSE theme active.
2. Switch to a different FSE theme which has not been used by this site before.
3. Notice the "Customizer" menu item appears in the menu after activating the theme.
3. Notice that the front end of the site does not have FSE header/footer.
4. Open the page editor.
5. Notice FSE exists there and now also on the front end.

Screen Shot 2019-12-09 at 4 28 22 PM

I threw in a ton of logs to pin down how this happens. Everything is working correctly based off of the "is fse active" property, but it turns out that **FSE is not active** immediately after switching themes from Calypso. Wat.

Specifically, the template part data is not inserted immediately upon switching themes. This means that FSE is not active, since the template part data does not exist. But wait, _how does FSE continue working!?_ The `after_switch_theme` action does not appear to fire until the next time you directly try to access a wp-admin URL. Accessing the front end doesn't work, but when you load `post.php` in the iFrame, it runs the `after_theme_switch` action at that point.

Specifically from the WordPress docs:

> after_switch_theme is triggered on the request immediately following a theme switch.

So it seems that the "next request" is when you open the page editor, not right when we switch themes from Calypso.

I'll try to solve this with `switch_theme`.

### PR DESCRIPTION
**Pull request by noahtallen**
### Changes proposed in this Pull Request
Use `switch_theme` instead of `after_switch_theme` for template part population. The `after_switch_theme` hook runs the callback on the **next request**, which means that population does not happen instantly. As you can imagine, this is problematic since FSE is not active if the template parts do not exist. Without this change there are weird periods where we expect FSE to be active, but it is not (see the bugs this fixes for more details).

### Testing Instructions
1. Load this to your wpcom sandbox and sandbox the API.
2. On a **logged-in** WordPress.com account, go to https://horizon.wordpress.com/start/test-fse. Go through the flow selecting any theme.

#### Update Homepage
1. Once you land in Calypso, wait a few seconds. Make sure that the "Customizer" item in the sidebar does not exist and that it does not suddenly appear after a few seconds.
2. Click the "Update homepage" item from your checklist, going to the page editor.
3. Open the help dialogue and make sure that there is no "switch to classic" button.
4. Open the three dot menu thing and make sure there is no switch to classic entry there either.

Screen Shot 2019-12-09 at 4 57 17 PM

#### Switch Themes
1. Now, go to the themes section in Calypso.
2. Activate a different FSE theme (one that has not been active on this site previously).
3. After it activates, make sure the "Customizer" item does not appear in the sidebar suddenly.
4. Make sure the front end of the website shows the FSE template parts.

Fixes #38305, Fixes #38056

### CODE REVIEW

File: apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php [hunk 1]
```diff
@@ -265,7 +265,7 @@ function populate_wp_template_data() {
 	$template_inserter->insert_default_pages();
 }
 register_activation_hook( __FILE__, __NAMESPACE__ . '\populate_wp_template_data' );
-add_action( 'after_switch_theme', __NAMESPACE__ . '\populate_wp_template_data' );
+add_action( 'switch_theme', __NAMESPACE__ . '\populate_wp_template_data' );
```
Comment (vindl) [inline apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php]: I explored this one initially, and if I recall correctly it's running on each load, as opposed to `after_switch_theme` which runs only on actual switch theme action. Do you foresee any potential problems because of that?

Comment (noahtallen) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php]: During my testing, I did not notice any odd behavior, particularly since we already check to make sure we don't do anything more than once. But I'll test it again today to make sure :)

The problem is that `after_switch_theme` does not happen immediately when you click it -- only upon the next request, which could be several seconds later. This results in the two bugs linked in the PR description.

Do you have ideas for a better solution?

Comment (vindl) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php]: Not at the moment, I was just worried about some consequences of doing this on each load. 

> particularly since we already check to make sure we don't do anything more than once

This flag is set at the end of the process. If we get an error before that it won't be set again and the population will be attempted again on next load. That translates into a couple of more  API requests per each load (due to retries). If everything is working correctly this wont' cause any problems, but if it happens that API request to this endpoint fails for some reason (say we introduce a bug in a commit) we could end up generating too many requests and overloading the API. 🤔 (since it would be attempted on each page view)

Comment (noahtallen) [reply apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php]: I just tested the behavior by adding a log statement to the very beginning of these functions before any checks happen:
1. `populate_wp_template_data` (as you say, we do not want it to run on every request)
2. `dangerously_load_full_site_editing_files` (runs on every request to load the FSE php files)

I verified that item 2 is logging as expected when visiting and editing pages, but item 1 was not logged.

So it shouldn't be running on every request and we should be safe :)
