### PR TITLE
Playwright: make Gutenberg publish and visit post steps more reliable.

### LINKED ISSUE #53834: Playwright: GutenbergEditorPage.publish sometimes unreliable
**Task Details**
`GutenbergEditorPage.publish` with the `visit: true` set is sometimes flakey as the `Promise.all` call doesn't always resolve in the way you would expect.

Look at either beefing up the wait and actions so the navigation failure doesn't occur as often.

Relevant [log](https://teamcity.a8c.com/repository/download/calypso_RunCalypsoPlaywrightE2eDesktopTests/6318775:id/logs.tgz!/logs.tgz!/test/e2e/temp/wpcom-likes-post-desktop-parallel/playwright-1624042491567.log):

```
413 api info => page.waitForNavigation started
413 api info <= frame.click succeeded
413 api info => page.screenshot started
413 api info <= page.screenshot succeeded
413 api info => page.close started
413 api info <= page.waitForNavigation failed
413 api info <= page.close succeeded
```

**Related to**
<-- If there are any other GitHub issue(s) that readers should be aware of, include them here. -->

### PR DESCRIPTION
**Pull request by worldomonation**
#### Changes proposed in this Pull Request

This PR revisits how GutenbergEditorPage.publish is implemented with the goal of making the process more reliable.

In some instances, test cases have failed due to the promises in `Promise.all` resolving prematurely for one reason or another. This causes the Playwright engine to believe it has clicked on the link to navigate to the published post when in fact it has not.

- add an explicit wait for the `spinner` to disappear.
- move the promise for `waitForLoadState` out from `Promise.all`.

#### Testing instructions

TeamCity:
- ensure Playwright E2E tests pass.
- inspect the Playwright E2E task to ensure that any tests involving publish and visit post are not flaking out (including being muted).

### CODE REVIEW

**Review by bsessions85 — APPROVED** [review]
Looks good to me. Muted tests were for log in step, not publish

File: packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts [hunk 1]
```diff
@@ -176,7 +177,7 @@ export class GutenbergEditorPage extends BaseContainer {
 		await this.frame.click( selectors.publishPanelToggle );
 		await this.frame.waitForSelector( selectors.publishPanel );
 		await this.frame.click( selectors.publishButton );
-		await this.frame.waitForSelector( selectors.viewPostButton );
+		await this.frame.waitForSelector( selectors.publishSpinner, { state: 'hidden' } );
```
Comment (WunderBart) [inline packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts]: This should not be necessary as it's not any different from waiting for the publish button to appear. It's also more prone to break the test, as the spinner element is more likely to change and/or appear after this line is called, which would immediately result in a false positive.

Comment (WunderBart) [reply packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts]: Is the change from https://github.com/Automattic/wp-calypso/pull/53835/files#diff-8aeb2361aa173b5616012d0e178c97eee06325bc9dd1b7a9570037ada0238659R195 not sufficient?

File: packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts [hunk 2]
```diff
@@ -189,10 +190,8 @@ export class GutenbergEditorPage extends BaseContainer {
...
 	 */
 	async _visitPublishedEntryFromPublishPane(): Promise< void > {
-		await Promise.all( [
-			this.frame.click( selectors.viewPostButton ),
-			this.page.waitForNavigation(),
-			this.page.waitForLoadState( 'networkidle' ),
-		] );
+		const viewPostButton = await this.frame.waitForSelector( selectors.viewPostButton );
+		await Promise.all( [ this.page.waitForNavigation(), viewPostButton.click() ] );
+		await this.page.waitForLoadState( 'networkidle' );
```
Comment (WunderBart) [inline packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts:195]: Makes sense, as the click would first need to trigger the request 👍

**Review by WunderBart — CHANGES_REQUESTED** [review]

File: packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts (hunk 1 above)
Comment (worldomonation) [reply packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts]: @WunderBart There has been occasional situations where the publish process fails due to timing, so the test step is left hanging. 

I can check if the change at Line 196 is sufficient, although the change there deals with failing to navigate to the published post whereas this change is to address failing to ensure the post was published.

Part of the difficulty is we won't know until it starts running frequently on `trunk` for more data to know if the changes were sufficient. If you feel strongly about the spinner though, we could try a piecemeal approach where this specific change is abandoned and we monitor for flakiness.

Comment (worldomonation) [reply packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts]: Ran it a couple of times with this change and it seems to be doing good, no muted tests (other than HTTP304 issue I am working on)! 👍

File: packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts [hunk 3]
```diff
@@ -189,10 +188,8 @@ export class GutenbergEditorPage extends BaseContainer {
 	 * @returns {Promise<void>} No return value.
 	 */
 	async _visitPublishedEntryFromPublishPane(): Promise< void > {
-		await Promise.all( [
-			this.frame.click( selectors.viewPostButton ),
-			this.page.waitForNavigation(),
-			this.page.waitForLoadState( 'networkidle' ),
-		] );
+		const viewPostButton = await this.frame.waitForSelector( selectors.viewPostButton );
+		await Promise.all( [ this.page.waitForNavigation(), viewPostButton.click() ] );
```
Comment (WunderBart) [inline packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts]: Let's also call the click [directly from the `frame`](https://playwright.dev/docs/api/class-frame#frame-click). The above two lines are an equivalent to:
```suggestion
		await Promise.all( [
			this.page.waitForNavigation(),
			this.frame.click( selectors.viewPostButton ),
		] );
```

Comment (worldomonation) [reply packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts]: Done!

**Review by WunderBart — APPROVED** [review]
🚀
