### PR TITLE
Stats: Display proper labels for x axis

### LINKED ISSUE #35230: Stats: viewing historic stats messes up the bar graph in Day view
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/{site-URL}
2. Take note of how the bar graph displays
3. Modify the URL to view the daily stats for a date that falls before the current range of the bar graph, e.g. by appending `?startDate=2019-06-23`
4. It doesn't happen consistently, so if nothing seems out of the ordinary, try switching to the Week view and back, and/or doing a hard refresh of the stats page after adding the date query.

#### What I expected
For the bar graph to show stats starting from that date, but not otherwise changing.

#### What happened instead
The bar graph greatly expanded the range, i.e. individual day-bars became much narrower, and in some cases the dates became completely jumbled up.

#### Browser / OS version
Replicated in Chrome and Firefox, on the user's site, my own site, and a Jetpack site.

#### Screenshot / Video
Stats page on initial load:
Stats1

Stats page after reloading with the date query:
Stats3

#### Context / Source

Reported via the support forums:

https://en.forums.wordpress.com/topic/stats-history-is-askew-i-e-not-in-order/

### PR DESCRIPTION
**Pull request by krymson24**
#### Changes proposed in this Pull Request

* Previously, despite entering the same startDate parameter in the URL, the x-axis labels would show inconsistent dates. The PR ensures that given the same startDate, the x-axis labels will show consistent date labels.

#### Testing instructions
1. Starting at URL: https://wordpress.com/stats/day/{site-URL}
2. Take note of how the bar graph displays
3. Modify the URL to view the daily stats for a date that falls before the current range of the bar graph, e.g. by appending `?startDate=2019-06-23`
4. Reload the page with the same start date. The x-axis should always read the same after each reload.

**Screenshots**

x-axis labels for August 28
Screen Shot 2020-09-01 at 4 10 16 PM

x-axis labels for August 27
Screen Shot 2020-09-01 at 4 10 27 PM

Fixes #35230

### CODE REVIEW

**Comment by mmtr** [comment]
> Reload the page with the same start date. The x-axis should always read the same after each reload.

I'm not sure I understand what this PR tries to fix. However, I tried replicating the testing instructions and I get inconsistent behavior:

After appending the `startDate` parameter and pressing enter in the browser:

Screen Shot 2020-09-01 at 11 57 19

After reloading the current URL (that contains the `startDate` parameter):

Screen Shot 2020-09-01 at 11 59 03

The data (bars) is not the same, but I think this PR only ensures the labels are always the same, am I right? If so, I guess the fact that the data is different will be solved in a different PR.

**Comment by krymson24** [comment]
@mmtr the consistency here is around the x-axis labels, not the data in the data bars shown, so you're correct! The data consistency will be addressed here: https://github.com/Automattic/wp-calypso/issues/35230

File: client/components/chart/index.jsx [hunk 1]
```diff
@@ -148,8 +166,8 @@ function Chart( {
 				) }
 			</div>
 			{ ! isPlaceholder && (
-				<div className="chart__y-axis">
-					<div className="chart__y-axis-width-fix">{ numberFormat( 100000 ) }</div>
+				<div ref={ yAxisRef } className="chart__y-axis">
+					<div className="chart__y-axis-width-fix">{ numberFormat( 1e5 ) }</div>
```
Comment (kwight) [inline client/components/chart/index.jsx:170]: Is the scientific notation necessary for the fix, or just a choice? If not, it adds a tiny bit of friction when reading, but no biggie – was just curious.

**Comment by kwight** [comment]
Great, works for me 🎉 

Before | After
--- | ---
 |

File: client/components/chart/index.jsx (hunk 1 above)
Comment (krymson24) [reply client/components/chart/index.jsx:170]: Not necessary, just a choice. In my opinion, I find scientific notation easier to parse than counting the number of zeros. Especially if the number of zeros > 3!
