### PR TITLE
Handle transfer out tlds with no locking support

### LINKED ISSUE #14899: Transfers: handle TLDs with no locking support
When going to a domain management page  / transfer / transfer to another registrar, you'll automatically get the following for TLDs without locking:
screen shot 2017-06-08 at 12 28 35

The "Resend" button and the following message are wrong, because we haven't actually send the code.
Clicking on "Resend" does work.

Clicking on "Cancel transfer" does not, because that attempts locking.
screen shot 2017-06-08 at 12 29 51

### PR DESCRIPTION
**Pull request by deBhal**
This PR adds support for TLDs without "Domain Locking" (aka "Name lock", this is the lock that registrars/resellers can alter at any time, _not_ the ICANN 60 one).

Testing:
We want to make sure that we can initiate, cancel and resend the auth code without errors, and that the UI strings make sense.

.fr and .de are the two ccTLDs that we're looking at without domain locking, which would error as reported in #14899, so we want to make sure they work and don't mention locking.

We also want to make sure that other domains work unchanged, with the locking checks.
*PSA*: Initiating the transfer out will disable privacy and locking. Remember to cancel the transfer for any domains you use for testing.

transfer-fr

(.com example in a comment below)

Fixes #14899
See also: D6491-code

### CODE REVIEW

File: client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx [hunk 1]
```diff
@@ -91,19 +112,29 @@ class Unlocked extends React.Component {
...
 		if ( pendingTransfer ) {
 			domainStateMessage = translate( 'Your domain is pending transfer.' );
-		} else if ( hasPrivacyProtection && ! privateDomain ) {
+		} else if ( domainLockingAvailable && hasPrivacyProtection && ! privateDomain ) {
 			domainStateMessage = translate( 'Your domain is unlocked and Privacy Protection has been disabled' +
 				' to prepare for transfer.' );
+		} else if ( domainLockingAvailable ) {
+			domainStateMessage = translate( 'Your domain is unlocked to prepare for transfer.' );
 		}
+		// Otherwise, we can skip this paragraph.
```
Comment (aidvu) [inline client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx]: Confusing comment unless you know what's happening. :)

I'd either remove or do something like `if domain doesn't support locking, it's always unlocked`.

File: client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx [hunk 2]
```diff
@@ -117,7 +148,7 @@ class Unlocked extends React.Component {
 
 				<Card className="transfer-card">
 					<div>
-						<p>{ domainStateMessage }</p>
+						{ domainStateMessage ? <p>{ domainStateMessage }</p> : null }
```
Comment (aidvu) [inline client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx]: You can do `domainStateMessage && <p>{ domainStateMessage }</p>`.

File: client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx (hunk 1 above)
Comment (deBhal) [inline client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx]: What about if we go even more explicit, like `If the domain doesn't support locking don't even mention it, otherwise we'll just confuse the user`?

File: client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx [hunk 3]
```diff
@@ -11,27 +11,53 @@ import Card from 'components/card';
...
+
+		const {
+			pendingTransfer,
+			domainLockingAvailable,
+			hasPrivacyProtection,
+		} = getSelectedDomain( this.props );
+
+		this.state = { submitting: false, canceled: false };
+
+		if ( ! ( pendingTransfer || domainLockingAvailable || hasPrivacyProtection ) ) {
```
Comment (aidvu) [inline client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx]: Unless I'm missing something, I don't think sending the request code right away when landing on the `Transfer Out` page makes sense.

File: client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx [hunk 4]
```diff
@@ -62,72 +73,172 @@ class Unlocked extends React.Component {
...
+
+		if ( domainLockingAvailable && hasPrivacyProtection && ! privateDomain ) {
+			lockStateReport = translate(
+				'Your domain is unlocked and Privacy Protection has been ' +
+				'disabled to prepare for transfer.' );
+		} else if ( domainLockingAvailable ) {
+			lockStateReport =translate( 'Your domain is unlocked to prepare for transfer.' );
+		} else if ( hasPrivacyProtection ) {
+			lockStateReport = translate(
+				'Privacy Protection for your domain has been disabled' +
```
Comment (a8ci18n) [inline client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx]: Hi! I've found a possible matching string that has already been translated **18** times:
`translate( 'Your domain is unlocked and Privacy Protection has been disabled to prepare for transfer.' )` *ES Score: 12*

Help me improve these suggestions: react with :thumbsdown: if the suggestion doesn't make any sense, or with :thumbsup: if it's a particularly good one (even if not implemented).

File: client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx [hunk 5]
```diff
@@ -62,81 +99,193 @@ class Unlocked extends React.Component {
...
-			domainStateMessage = translate( 'Your domain is pending transfer.' );
-		} else if ( hasPrivacyProtection && ! privateDomain ) {
-			domainStateMessage = translate( 'Your domain is unlocked and Privacy Protection has been disabled' +
-				' to prepare for transfer.' );
+		let domainStateMessage;
+		if ( domainLockingAvailable && privacyDisabled ) {
+			domainStateMessage = translate( 'Your domain is unlocked and ' +
+				'Privacy Protection has been disabled to prepare for transfer.' );
+		} else if ( privacyDisabled ) {
+			domainStateMessage = translate( 'Privacy Protection for your ' +
```
Comment (a8ci18n) [inline client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx]: Hi! I've found a possible matching string that has already been translated **18** times:
`translate( 'Your domain is unlocked and Privacy Protection has been disabled to prepare for transfer.' )` *ES Score: 12*

Help me improve these suggestions: react with :thumbsdown: if the suggestion doesn't make any sense, or with :thumbsup: if it's a particularly good one (even if not implemented).

**Comment by deBhal** [comment]
Ok, let's try this again!

This component already has quite a lot of responsibility, so I've done a bit of refactoring to support sending the codes from this page.

I've tried to limit the impact on the existing flow, so I've resisted the urge to to add more copy, particularly around manual transfers and pending domains, but I've tried to create space to add that in future if we decide to.

I've tried to preserve the original appearance, but I did fiddle with the whitespace a little bit to make everything fit together, and added a few strings where they seemed important to the .FR flow.

It seems like the component/flow would benefit from a UX review, some refactoring into more components and some a bunch of tests, but that's a lot of work that's outside the scope of this PR.

Here's the new .FR look, with sans useless cancel button:

transfer-fr

and the .com flow that is hopefully not obviously different from the old one:
transfer-com-after

**Comment by hewsut** [comment]
I can't do a full review right at this moment as I need to stay focused on the renew stuff, but, as we chatted about yesterday--great job balancing the need for ship and code stability! At a glance, it sure looks like a win in the refactoring you've done and yet it also looks like you stopped on the right line to get shipped and avoid a quagmire.

I'll try to circle back at end of day and review so you can launch if nobody else can get to this. 🚀

File: client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx [hunk 6]
```diff
@@ -11,28 +12,64 @@ import Card from 'components/card';
...
-	state = {
-		submitting: false
-	};
+	constructor( props ) {
+		super( props );
+
+		this.state = {
+			submitting: false,
+			// If the domain has any protection, we will must have sent the
+			// request to get to this page.
```
Comment (hewsut) [inline client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx]: This confused me at first until I started poking around up the chain a bit more. Maybe verbiage like this?

```
For protected domains, the preceding `transfer-out/locked` page handles an initial auth code send before the user gets here.
```

File: client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx [hunk 7]
```diff
@@ -62,81 +99,193 @@ class Unlocked extends React.Component {
...
+			domainLockingAvailable,
+			hasPrivacyProtection,
+		} = getSelectedDomain( this.props );
+		return ! domainLockingAvailable && ! hasPrivacyProtection;
+	}
+
+	renderCancelButton( domain ) {
+		const { pendingTransfer } = domain;
+
+		if ( ! pendingTransfer && this.isDomainAlwaysTransferrable() ) {
```
Comment (hewsut) [inline client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx]: Is just `! pendingTransfer` better?

I mean hypothetically if we got here somehow with a domain that does the pending thing and it were not in that invoked state (which seems not possible, but)....  we'd still not want to show the button.  Right?

File: client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx [hunk 8]
```diff
@@ -62,81 +99,193 @@ class Unlocked extends React.Component {
...
+			disabled={ this.state.submitting || ! this.state.sent }
+			compact>{ this.props.translate( 'Cancel Transfer' ) }
+		</Button> );
+	}
+
+	renderSendButton( domain ) {
+		const { translate } = this.props;
+		const { manualTransferRequired } = domain;
+
+		if ( manualTransferRequired && this.state.sent ) {
```
Comment (hewsut) [inline client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx]: Are we restricting manual transfers to sending the code once for a technical reason underlying those TLDs? I'm curious why no resends like other TLDs.

File: client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx [hunk 9]
```diff
@@ -62,81 +99,193 @@ class Unlocked extends React.Component {
...
+		const { sent } = this.state;
+
+		return ( <p>{
+			translate( 'The registry for your domain requires a special process for transfers. ' )
+		} { sent
+			? translate( 'Our Happiness Engineers have been notified about ' +
+				'your transfer request and will be in touch shortly to help ' +
+				'you complete the process.' )
+			: translate( 'Please request an authorization code to notify our ' +
+				'happiness engineers of your intention.' )
```
Comment (hewsut) [inline client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx]: Happiness Engineers should be capitalized here.

**Comment by hewsut** [comment]
I tested .com/.ca behaviors live.  The former was +60 days and seems to work as expected. The latter for me was < 60 days so I couldn't do much...but I got the right message. :)

I tested .com/.ca/.fr in test. Again, < 60 days on ca... but fr obvs could be simulated with its non-lockablilty and it looked good to me! I never received a code but I'm assuming test doesn't send?

File: client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx (hunk 7 above)
Comment (deBhal) [inline client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx]: Maybe I should swap the clauses around.

If it's pending transfer, we always want to show the cancel button, because we can cancel the pending transfer, so `! pendingTransfer`.

Otherwise, cancelling the transfer just means "reinstate privacy and the lock, as appropriate", so for "alwaysTransferrable", that's a null-op, so we should skip the cancel button. Unless there's a pending transfer.

I put the clauses this way around because pending transfer is cheaper, but it's not a meaningful difference, and `this.isDomainAlwaysTransferrable() && ! pendingTransfer` will probably read better - "Skip the cancel button domains that don't need it, unless they're pending"

File: client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx (hunk 8 above)
Comment (deBhal) [inline client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx]: I'm preserving the existing logic here a bit blindly. I know the back end recognizes domains that need happiness intervention, so I'm assuming that we pop an email into the support queue and more emails would be noise at best, with a chance of delaying a response by making the request look newer than it really is.

File: client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx (hunk 7 above)
Comment (hewsut) [inline client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx]: I get `! pendingTransfer` and that makes sense.  But my point is why `this.isDomainAlwaysTransferrable()` at all?

I realize that the only real situation this should happen is for an always transferrable domain. Nonetheless....  for _any_ case that made it here--if some way some how we have a `pendingTransfer`--we'd want to err to show the button, no?

File: client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx (hunk 6 above)
Comment (deBhal) [inline client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx]: Yeah, good call. I've taken your clearer verbiage, and added a mention of transfer-out/index too.

File: client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx (hunk 7 above)
Comment (deBhal) [inline client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx]: Yeah. If there's a pending transfer, the guard will always be false, so we won't bail out early  and we will show the cancel button - always show the button if there's a pending transfer.

It the domain is transferrable, skip the button, but only if there's no pending transfer.

```
> [true, false].forEach(pendingTransfer => [true, false].forEach( isDomainAlwaysTransferrable => console.log( 'pendingTransfer:',pendingTransfer,', isDomainAlwaysTransferrable:',isDomainAlwaysTransferrable, 'bail?', ( ! pendingTransfer && isDomainAlwaysTransferrable ) ) ) )
pendingTransfer: true , isDomainAlwaysTransferrable: true bail? false
pendingTransfer: true , isDomainAlwaysTransferrable: false bail? false
pendingTransfer: false , isDomainAlwaysTransferrable: true bail? true
pendingTransfer: false , isDomainAlwaysTransferrable: false bail? false
```

Would it be clearer to add the extra negations? `if ( ! ( pendingTransfer || ! isDomainAlwaysTransferrable ) ) bail`

Comment (deBhal) [inline client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx]: I know how to make it make sense:
`const showCancelButton = pendingTransfer || ! this.isDomainAlwaysTransferrable();`

**Comment by deBhal** [comment]
> I'm assuming test doesn't send?

I'm not sure, but I've been testing with live domains, and have a _ton_ of emails for .com and .fr :)

**Comment by deBhal** [comment]
As an aside, I noticed that the the locked flow checks for locking but not privacy, so if we add a domain with togglable privacy but no locking, we'll need to fix that.

Luckily, the only domain that describes is `.garden`:
```
$ ack '^(?:[^\t]*\t){11}(Y\tN)' ~/Downloads/OpenSRS\ TLD\ Reference\ Chart\ -\ All\ TLDs.tsv
.garden		nTLD	Nominet	n/a		none	3 to 63	Y	1 to 10 years	2 to 13	Y	N	N	N	Y	N	30 days before expiry	up to expiry	40 days	30 days	1 year added to reg term	Y	N	Y	2	-	
```

**Comment by akirk** [comment]
I can also confirm that the UI works fine for .fr but I never received an e-mail with a code.

**Comment by deBhal** [comment]
I think the missing emails are about the OpenSRS testing system, and that this is there-for good to go.

I've got a lot of emails for my live domain, but when I set up a .fr domain using the store sandbox (which means we're using the OpenSRS test server), I get a success back from the `send_auth` OpenSRS API call, but no email.

File: client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx [hunk 10]
```diff
@@ -11,28 +12,65 @@ import Card from 'components/card';
...
+	 * Wrap setState calls that might occur after unmounting.
+	 *
+	 * When we cancel a transfer, that might update locking or privacy,
+	 * but errors mean we can't know in time - the store gets the information
+	 * before we do.
+	 *
+	 * The recommended solution is cancellable promises, but we don't want to
+	 * cancel these requests if we navigate away, so that won't work for us here.
+	 */
+	setStateIfMounted( ...args ) {
```
Comment (klimeryk) [inline client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx]: Interesting workaround 👍

File: client/lib/domains/assembler.js [hunk 11]
```diff
@@ -23,6 +23,7 @@ function createDomainObjects( dataTransferObject ) {
 		return {
 			autoRenewalMoment: domain.auto_renewal_date && i18n.moment( domain.auto_renewal_date ),
 			currentUserCanManage: domain.current_user_can_manage,
+			domainLockingAvailable: domain.domain_locking_available,
```
Comment (klimeryk) [inline client/lib/domains/assembler.js]: Could you also add this to https://github.com/Automattic/wp-calypso/blob/master/client/state/sites/domains/assembler.js?

File: client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx [hunk 12]
```diff
@@ -11,28 +12,65 @@ import Card from 'components/card';
...
+import { requestTransferCode, cancelTransferRequest } from 'lib/upgrades/actions';
 import notices from 'notices';
 import { displayRequestTransferCodeResponseNotice } from './shared';
 import support from 'lib/url/support';
 
 class Unlocked extends React.Component {
-	state = {
-		submitting: false
-	};
+	constructor( props ) {
```
Comment (klimeryk) [inline client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx]: Why did you add the constructor? You could have just initialized the state as previously.

File: client/lib/domains/assembler.js (hunk 11 above)
Comment (deBhal) [inline client/lib/domains/assembler.js]: Done!

File: client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx (hunk 10 above)
Comment (deBhal) [inline client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx]: Good interesting or bad "interesting"? I don't feel I understand why this pattern is frowned on. I mean, I get that memory leaks are both bad and insidious, but surely errors are worse. Maybe I just don't love promises enough...

Comment (deBhal) [inline client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx]: It occurs to me that if this pattern is generally acceptable we could pull it out into an higher order component.

File: client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx (hunk 5 above)
Comment (deBhal) [inline client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx]: 👎

File: client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx (hunk 12 above)
Comment (deBhal) [inline client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx]: Wow that's cool, thanks!

I thought I needed the constructor to have the props for `this.isDomainAlwaysTransferrable()`, but TIL that ES7 property initializers work the way you'd want them to :D

File: client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx (hunk 10 above)
Comment (klimeryk) [inline client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx]: Definitely good interesting :) Might be worth a post of calypsop2 to get more opinions, but it's something that we should address sooner or later.

File: client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx (hunk 12 above)
Comment (klimeryk) [inline client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx]: Yup, I was also unsure if it'd work, so I tested before commenting to make sure 😅
