### PR TITLE
.org Plans: Fix site slug in plan cancellation survey

### LINKED ISSUE #9200: Jetpack: Cancellation survey should encode URL properly
#### Steps to reproduce
1. Buy a plan for a Jetpack site which is installed in a directory (not at the root of a domain)
2. Go through the process of canceling the plan
3. Observe incorrectly-encoded URL (e.g. we're displaying the slug version, which contains `::`, not a correctly-encoded, real URL, which would change that to `/`).

screen shot 2016-11-07 at 5 04 50 pm

#### Context / Source
#manual-testing

### PR DESCRIPTION
**Pull request by tyxla**
This PR fixes #9200, where the site slug is not properly formatted and displays `::` instead of `/` when the Jetpack site is installed in a subdirectory. 

To test:

* Checkout this branch
* Purchase a plan for a Jetpack site which is installed in a subdirectory
* Go through the process of canceling the plan
* Verify the site slug is displayed with `/` and not with `::` in the "Are you sure you want to remove {PLAN} from {SLUG}" text in the removal step
* Verify the site slug is displayed with `/` and not with `::` in the "{PLAN} was removed from {SLUG}" text in the removal confirmation notice.
* Verify tests of the new `slugToUrl` method pass: ` npm run test-client client/lib/url/test/index.js -- --grep "slugToUrl"`

/cc @beaulebens @johnHackworth

### CODE REVIEW

**Comment by roccotripaldi** [comment]
Code looks solid, and tests are passing.
It took me a moment to find my testing site that is in a sub-folder. Testing now.

**Comment by roccotripaldi** [comment]
LGTM!

File: client/me/purchases/remove-purchase/index.jsx [hunk 1]
```diff
@@ -130,7 +131,7 @@ const RemovePurchase = React.createClass( {
 				notices.success(
 					this.translate( '%(productName)s was removed from {{siteName/}}.', {
 						args: { productName },
-						components: { siteName: <em>{ selectedSite.slug }</em> }
+						components: { siteName: <em>{ slugToUrl( selectedSite.slug ) }</em> }
```
Comment (mtias) [inline client/me/purchases/remove-purchase/index.jsx]: This function is doing exactly the same as the [`domain` attribute](https://github.com/Automattic/wp-calypso/blob/master/client/state/sites/selectors.js#L247) of the site entity, which is what should be used instead.

`selectedSite.domain` instead of `slugToUrl( selectedSite.slug )`.

Comment (tyxla) [inline client/me/purchases/remove-purchase/index.jsx]: Good call, thanks for noticing @mtias :+1: Fixing in #9338.
