### PR TITLE
Playwright: restructure tests to remove non-determinism

### LINKED ISSUE #53903: Playwright: support clearing cookies in mid-test
**Task Details**
Currently, clearing cookies anywhere within a top-level `describe` would cause subsequent tests to fail.

For example, take this structure:

```
describe( top suite )
      describe( test case 1)
             test steps...
             
      describe( test case 2)
             clear cookie
             test steps...

      describe( test case 3)
             test steps...
```

Test steps in `test case 2` and the whole of `test case 3` would end up failing because the cookies have been cleared.

I am not fully certain why this is the case, but it might have to do with the reuse of the same `BrowserContext` for the entire top suite is the problem.

**Related to**
<-- If there are any other GitHub issue(s) that readers should be aware of, include them here. -->

### LINKED ISSUE #53926: Playwright: refactor wp-likes tests to be more deterministic
**Task Details**
Playwright tests under `wp-likes` were one of the first to be migrated, and they suffer from non-determinism.

For instance, the `wp-likes__logged-out-spec.js` suffers from the problem that the pre-existing published post that is selected for testing may be a password protected post, which would not be likeable.

Another example is with `wp-likes__post-spec.js` where an existing post is liked. The same issue happens here.

**Related to**
#53925

### PR DESCRIPTION
**Pull request by worldomonation**
#### Changes proposed in this Pull Request

This PR proposes to remove several tests and restructure others in order to eliminate non-determinism.

Key Changes:
- removal of `Comment and like on an existing post` suite.
- combination of `Like a new post` and `Like post as another user` suite into one flow.

Background Details:

When initially migrating the tests from Selenium to Playwright, I made an effort to expand the scope of features being tested. While this was a good initiative, some tests ended up being non-deterministic leading to flaky tests.

For instance, the `Comment and like on an existing post` suite relies on the test account:
- having at least 1 published post, and;
- the published post is not private or otherwise protected, and;
- the post supports commenting.

These factors introduce a level of uncertainty into specs. Did the test fail because of a conflict? Or is the failure a _real_ regression?

I feel the best course of action at this time is to restructure specs to test a combined flow where the having multiple flows is not warranted to save both testing resources and time but also make subsequent portions of the flow dependent on earlier steps successfully completing.

#### Testing instructions

- [ ] TeamCity should not show failures relating to the Likes tests.

Related to #

### CODE REVIEW

**Comment by worldomonation** [comment]
Oops, still in draft - need to clean up a few things.

File: test/e2e/specs/specs-playwright/wp-likes__post-spec.js [hunk 1]
```diff
@@ -57,33 +62,20 @@ describe( DataHelper.createSuiteTitle( 'Likes (Post)' ), function () {
...
-		} );
 
-		it( 'Unlike post', async function () {
-			await publishedPostPage.unlikePost();
+			const loginFlow = new LoginFlow( page, anotherUser );
+
+			// Clicking the Like button will bring up a new popup.
+			// `loginFromPopup` will observe for a popup event, grab the new popup and
+			// execute the login process on that page.
+			await Promise.all( [ loginFlow.logInFromPopup(), publishedPostPage.likePost() ] );
```
Comment (worldomonation) [inline test/e2e/specs/specs-playwright/wp-likes__post-spec.js:78]: This step is copied entirely over from the now-deleted file `test/e2e/specs/specs-playwright/wp-likes__logged-out-spec.js`.

File: packages/calypso-e2e/src/browser-manager.ts [hunk 2]
```diff
@@ -114,11 +114,31 @@ export async function close(): Promise< void > {
...
+
+	// Navigate to the WordPress.com base URL.
+	await page.goto( config.get( 'calypsoBaseURL' ) );
+	// Clear the GDPR banner cookie.
+	await page.evaluate( 'window.document.cookie = "sensitive_pixel_option=no;";' );
+	// Clear additional cookies.
+	await page.evaluate(
+		'window.document.cookie = "sensitive_pixel_option=no;domain=.wordpress.com;SameSite=None;Secure"'
+	);
+	// Clear cookies to remote login.
```
Comment (dpasque) [inline packages/calypso-e2e/src/browser-manager.ts]: Could you explain a little more what's going on in these lines?

From what I can tell, the goal is to wipe cookies (which is what we do in the end with `browserContext.clearCookies()`). It looks like the goal in these previous steps is mostly to wipe `localstorage` on `r-login.wordpress.com`. 

Is there any reason we can't trim this down to:
```typescript
	await page.goto( 'https://r-login.wordpress.com/' );
	// Clear local storage.
	await page.evaluate( 'localStorage.clear();' );
	// Lastly, clear the cookies using built-in method.
	await browserContext.clearCookies();
	// Previous steps navigated page away from target page. Return page to the original URL.
	await page.goto( currentURL );
```

File: packages/calypso-e2e/src/browser-manager.ts [hunk 3]
```diff
@@ -114,11 +114,31 @@ export async function close(): Promise< void > {
...
 
 /**
- * Given a page, this will clear the cookies for the context to which the page belongs.
+ * Given a page, this will clear all cookies, local storage and reset permissions for the
+ * Browser Context to which the page belongs.
  *
  * @param {Page} page Object representing a page launched by Playwright.
  * @returns {Promise<void>} No return value.
  */
 export async function clearCookies( page: Page ): Promise< void > {
```
Comment (dpasque) [inline packages/calypso-e2e/src/browser-manager.ts]: Optional: but what do you think about instead adding a wrapper function around this function, since this function now technically does more than just clearing cookies?

So this function, `clearCookies` can stay just clearing cookies, and then you make a wrapper function called `resetForNewUserLogin` that does the local storage wipe and calls into `clearCookies`?

I just don't want anyone to call this and miss the `localstorage` side effect if they don't know about it (and don't pay attention to the JSDoc header)

**Review by dpasque — CHANGES_REQUESTED** [review]
Have a couple questions on the browser cookie clearing!

The script updates look really nice - I 100% agree that it is much better to have fewer, more deterministic tests. These flows look really nice, simple, and stable!

File: packages/calypso-e2e/src/browser-manager.ts (hunk 2 above)
Comment (worldomonation) [reply packages/calypso-e2e/src/browser-manager.ts]: I copied this behavior from the existing Selenium suite. This behavior can be found [here](https://github.com/Automattic/wp-calypso/blob/trunk/test/e2e/lib/driver-manager.js#L353-L357), [here](https://github.com/Automattic/wp-calypso/blob/trunk/test/e2e/lib/driver-manager.js#L304-L313) and [here](https://github.com/Automattic/wp-calypso/blob/trunk/test/e2e/lib/driver-manager.js#L319-L343).

I think it may be worth trying to see if what you suggested suffices though.

File: packages/calypso-e2e/src/browser-manager.ts (hunk 3 above)
Comment (worldomonation) [reply packages/calypso-e2e/src/browser-manager.ts]: I think it may be better to rename the method instead, since the `clearCookies` call is a one-liner (assuming the context is available) and I don't anticipate a situation that may require one but not the other.

What do you think about a name like `clearAuthenticationState` to be more in line with the original Selenium call (`ensureNotLoggedIntoSite`)?

File: packages/calypso-e2e/src/browser-manager.ts (hunk 2 above)
Comment (worldomonation) [reply packages/calypso-e2e/src/browser-manager.ts]: You were correct!

File: packages/calypso-e2e/src/browser-manager.ts (hunk 3 above)
Comment (dpasque) [reply packages/calypso-e2e/src/browser-manager.ts]: Oh, I like that! That name sounds nice!!

**Review by dpasque — APPROVED** [review]
I think that new version of the function looks really clean and nice - love it!

LGTM! 🚢
