### PR TITLE
Customer Home: Fix bug with notice not dismissing if option 'never' set

### LINKED ISSUE #42815: My Home: Error when Dismissing Editor Deprecation Notice
#### Steps to reproduce

Clicking the "Dismiss" button on "The new WordPress editor is coming" task doesn't work, even on refresh, and instead causes a console error.

Screenshot 2020-05-29 at 20 34 45

#### What I expected

I'm not even sure if this should be dismissable - it seems like a pretty important notice. I've looked through #41570, and it seems like that it is the intention though, so the dismissing function should work.

#### Browser / OS version

Chrome/83.0.4103.61, Macintosh; Intel Mac OS X 10_14_6

cc @glendaviesnz, @gwwar

### PR DESCRIPTION
**Pull request by glendaviesnz**
#### Changes proposed in this Pull Request

* Fixes issues with withAnalytics dispatch and /skip endpoint param

#### Testing instructions

* Checkout PR in local Calypso dev env
* Go to Customer home that has a notice  'Remind Me' and another that has a 'Dismiss' link (eg. editor deprecation notice)
* Make sure the dismiss option works in both cases

There were two issues here - one with the withAnalytics dispatch that affected all uses of `skipTask` call, and a second issue with the Dismiss link that was setting `reminder` to `never` which was rejected by REST endpoint.

Before:
notice-before

After:
notice-after

Fixes #42815

### CODE REVIEW

File: client/my-sites/customer-home/cards/tasks/task.jsx [hunk 1]
```diff
@@ -85,7 +85,7 @@ const Task = ( {
 					} ),
 					bumpStat( 'calypso_customer_home', 'task_skip' )
 				),
-				dispatch( skipCurrentViewHomeLayout( siteId, reminder ) )
+				skipCurrentViewHomeLayout( siteId, reminder )
```
Comment (gwwar) [inline client/my-sites/customer-home/cards/tasks/task.jsx:88]: Good catch!
