### PR TITLE
Account closure: allow account to be closed if user has only purchased premium themes

### LINKED ISSUE #27014: Me: presence of premium themes should not prevent closure of account
#### Steps to reproduce
Using an account containing a site with a premium theme:

1. Starting at URL: https://wordpress.com/me/account/close

#### What I expected

It is possible to delete the account.

#### What happened instead

screen shot 2018-09-05 at 12 18 25

The copy instructs the user to cancel active purchases before deleting the account, but it is not possible to cancel a premium theme (it's a one-time purchase).
 
#### Context / Source

Reported by a user in 1392647-zen.

When checking whether an account has active purchases, we should probably ignore premium themes.

cc @westi

### PR DESCRIPTION
**Pull request by bluefuton**
Our account closure process currently stops you in your tracks if you have any active purchases, asking you to cancel them first. However, it is not possible to cancel a premium theme. As a result, users whose only purchases are premium themes have been unable to close their accounts.

This PR improves the check for active purchases by excluding premium themes.

It also adds a listing of the premium themes a user will lose access to if they proceed with account closure:

screen shot 2018-09-25 at 15 49 52

...and adds a 'premium theme' list item to the the list of things the user will lose.

screen shot 2018-09-25 at 15 50 01

Fixes #27014.

#### Testing instructions

Visit http://calypso.localhost:3000/me/account/close with accounts that:

- Only have premium themes. Verify that you are shown the premium themes list on the account close page, but you still have the option to proceed with deletion.

screen shot 2018-09-25 at 16 34 00

- Do not have any premium themes or purchases. You should be able to proceed with deletion, and will not see a themes list or 'Premium themes' in the list of things to be deleted.

screen shot 2018-09-25 at 16 33 47

- Have purchases besides premium themes. Verify that you are directed to contact support.

### CODE REVIEW

**Comment by KokkieH** [comment]
> However, it is not possible to cancel a premium theme. As a result, users whose only purchases are premium themes have been unable to close their accounts.

Small clarification - this is specifically a problem for premium themes older than 30 days, i.e. past the refund period. During the refund period a user can cancel and refund a theme from Purchases. 

If a premium theme is still refundable, we should probably still treat it as a blocker to account closure, to make sure the user cancels and receives a refund first.

Tested using these steps:

### Test 1

1. Purchased a premium theme on a new site on a test account using PayPal so there's a refundable transaction
2. Ran the branch locally and visited Purchases - Theme shows cancel and refund option
3. Went to account settings and selected Close Account.

I was able to successfully close the account, despite having a refundable upgrade active on the account, which is not ideal.

### Test 2

1. Purchased a premium theme using credits so the theme won't be refundable
2. With this branch running, visited Purchases and confirmed theme does not show as refundable
3. Went to account settings and selected Close Account.

I was able to successfully close the account - the non-refundable, non-cancellable theme did not block this action.

So the PR is working as intended.

**Comment by bluefuton** [comment]
Thanks for the feedback @KokkieH! Sounds like we should try to add some logic for refundable themes.

I had thought that `is_cancelable` flag on purchases wasn't being populated but perhaps it's because all my test accounts made their purchases using credits.

> Purchased a premium theme on a new site on a test account using PayPal so there's a refundable transaction

Can you share what the process is for doing this on a test account? Is it a real PayPal transaction?

**Comment by bluefuton** [comment]
> Happy to do it again if you'd like a live account and upgrade to test with.

That would be amazing - thank you @KokkieH :)

**Comment by KokkieH** [comment]
Done. Will DM you the account details

File: client/state/selectors/test/has-cancelable-user-purchases.js [hunk 1]
```diff
@@ -0,0 +1,109 @@
...
+			},
+		};
+
+		expect( hasCancelableUserPurchases( state, targetUserId ) ).toBe( false );
+	} );
+
+	test( 'should return false because all of the purchases are themes', () => {
+		const state = {
+			purchases: {
+				data: deepFreeze( [
```
Comment (southp) [inline client/state/selectors/test/has-cancelable-user-purchases.js]: Is there a special reason why this case only `deepFreeze` partly, instead of the whole `state`?

File: client/state/selectors/test/has-cancelable-user-purchases.js [hunk 2]
```diff
@@ -0,0 +1,109 @@
...
+			ID: 3,
+			product_name: 'premium theme',
+			product_slug: 'premium_theme',
+			blog_id: 1337,
+			user_id: targetUserId,
+		},
+	] );
+
+	test( 'should return false because there are no purchases', () => {
+		const state = {
```
Comment (southp) [inline client/state/selectors/test/has-cancelable-user-purchases.js]: For consistency and future proof, how about we `deepFreeze` all the `state` in all test cases like the first one?

File: client/state/purchases/selectors.js [hunk 3]
```diff
@@ -87,7 +86,7 @@ export const getIncludedDomainPurchase = ( state, subscriptionPurchase ) => {
 };
 
 /**
- * Returns a list of Purchases associated with a User from the state using its userId
+ * Does the user have any current purchases?
```
Comment (southp) [inline client/state/purchases/selectors.js]: Clear and concise. Kudos +++++

**Comment by KokkieH** [comment]
Just adding, it would be great if #17012 could be addressed at the same time, that is, to also allow a site with a non-refundable premium theme to be deleted on its own (with applicable warnings, perhaps), without account closure.

**Comment by bluefuton** [comment]
> Just adding, it would be great if #17012 could be addressed at the same time, that is, to also allow a site with a non-refundable premium theme to be deleted on its own (with applicable warnings, perhaps), without account closure.

@KokkieH I had my eye on that one too! I've laid the groundwork for fixing it in this PR and we can address it in a followup.

**Comment by KokkieH** [comment]
I tried the same testing steps as above, and in scenario 1 with a purchased, refundable theme it now directs me to Purchases first to cancel the theme.

In scenario 2 with a theme purchased with credits it, it now also again directs me to Purchases and I cannot in fact close the account. However, that might be a limitation to do with using credits to buy the theme - technically the theme is in the refund period so, depending on how you check for cancellable purchases this might be expected behaviour. Unfortunately I don't have a real un-cancellable theme to test with :)

**Comment by bluefuton** [comment]
Thanks for testing again @KokkieH! In your scenario 2 test, does the account have any other purchases? Could you DM me the account name?

I just signed up for a fresh test account, purchased a theme using credits and then was able to close the account:

screen shot 2018-10-16 at 12 38 59

**Comment by KokkieH** [comment]
The theme with credits was bought on the same site that previously had a theme purchased via PayPal.

Tested with an account with no prior upgrades, and there I'm able to close the account as expected without cancelling the theme.

**Comment by bluefuton** [comment]
@kokkieh thanks! Looks like the Photo Blog theme purchased on that account is still eligible for refund, so I think Account Closure is behaving as it should:

screen shot 2018-10-17 at 10 14 45
screen shot 2018-10-17 at 10 14 38

**Comment by KokkieH** [comment]
It was purchased with credits, though, so not sure how it's refundable. But that's a separate issue form this PR, yes.
