### PR TITLE
Bug Fix: Scroll to top of page when link is clicked

### LINKED ISSUE #24337: Devdocs: components loading at weird scroll positions when visiting from component library
#### Steps to reproduce
1. Visit https://wpcalypso.wordpress.com/devdocs/design
2. Scroll down the page to the pop over component and click on the title
3. Notice where on the screen you are dropped
4. Copy and paste URL into a new tab, notice it appears at the top of the screen

#### What I expected
I expect to load the component screens at the top

#### What happened instead
When I visit a component screen from the library, in some cases it loads the screen half way down or the bottom

#### Browser / OS version
Chrome

#### Screenshot / Video
scroll

#### Context / Source
Working on a personal project I ran into a similar issue where the component would maintain the scroll position of the previous component on route change.

### PR DESCRIPTION
**Pull request by Dillweed5446**
#### Changes proposed in this Pull Request
Added autoscroll function to onClick and onKeyPress events.  Specifically, the issue pointed out that the component link would render at the bottom of the documentation page. I noticed that the same thing happened with other components within the parent, so I added a function that would cause the links to render at the top of the documentation page.
*

#### Testing instructions

Go to : https://wpcalypso.wordpress.com/devdocs/design , scroll down to to view Popover docs (or any other link on the bottom half of the page). The documentation for Popover should be scrolled to the top of the page after following the link.

*

Fixes #24337

### CODE REVIEW

**Comment by Dillweed5446** [comment]
@fditrapani - I finally got the dev environment working (switched from Windows 10 OS to Ubuntu.  Fixed all of my issues!).  I was finally able to mess around with this bug and figure out the proper implementation for the fix.

**Comment by Dillweed5446** [comment]
Bug fix for issue #24337

**Comment by Dillweed5446** [comment]
Awesome, thank you!

File: client/devdocs/design/search-collection.jsx [hunk 1]
```diff
@@ -112,12 +116,14 @@ const Collection = ( {
 
 	return (
 		<div className="design__collection">
-			{ showCounter > 1 && filter && (
-				<div className="design__instance-links">
-					<span className="design__instance-links-label">Results:</span>
-					{ summary }
-				</div>
-			) }
+			<button onClick={ scroll() } onKeyPress={ scroll() }>
```
Comment (michaeldcain) [inline client/devdocs/design/search-collection.jsx:119]: It seems like the fix is actually working as an unintended result of React rendering. There are two things that need to be fixed here:

First, this button is wrapping the component that renders the search suggestions (once, at the top of the page), not the individual example components on the page, which are set as [an array of `examples` here](https://github.com/Automattic/wp-calypso/pull/44330/files#diff-3d6cda4b838f1af02b0276588d0daf5aL65) and [looped through here](https://github.com/Automattic/wp-calypso/pull/44330/files#diff-3d6cda4b838f1af02b0276588d0daf5aL126). I believe you'd want to wrap [the return here](https://github.com/Automattic/wp-calypso/pull/44330/files#diff-3d6cda4b838f1af02b0276588d0daf5aL104) (or just add the handlers to the wrapper div). You can see where it's rendered by searching for the `design__collection` class in the source.

Second, [the event handling syntax in React is a little different than HTML](https://reactjs.org/docs/handling-events.html). Using `scroll()` (with the parentheses) in a handler in JSX actually calls the function every time the component is rendered. This is why the the patch still "works". Those components are re-rendered when the link in one of the examples is clicked, and thus, `scroll` fires. If you were to add a `console.log( 'scroll' )` to the `scroll` function, you'll see that it fires immediately when the page loads (and any time _any_ element on the screen that causes a re-render is clicked).

Comment (Dillweed5446) [reply client/devdocs/design/search-collection.jsx]: Thank you for the feedback @michaeldcain!  I made the recommended fixes.  The linter wouldn't allow me to add an event handler to the div tag, so I added the button tag to make it happy.  :smile:  I also added the Fix #24337 to the original commit message as you recommended.  Thank you for your guidance.

File: client/devdocs/design/search-collection.jsx [hunk 2]
```diff
@@ -102,10 +106,12 @@ const Collection = ( {
 
 		return (
 			<div>
-				<DocsExampleWrapper name={ exampleName } unique={ !! component } url={ exampleLink }>
-					{ example }
-				</DocsExampleWrapper>
-				{ component && <ReadmeViewer readmeFilePath={ readmeFilePath } /> }
+				<button onClick={ scroll } onKeyPress={ scroll }>
```
Comment (michaeldcain) [inline client/devdocs/design/search-collection.jsx:109]: Buttons shouldn't contain interactive children, so I don't think we should wrap it with a button (and as you note, divs will throw a linting error). In addition to console errors, this would also apply new styles to the children:

Master | Branch
------------ | -------------
before | after


In testing production, I noticed that _only_ the header of `DocsExampleWrapper` should link to the individual page. As such, we could add a new `onClick` prop to `DocsExampleWrapper`, pass `scroll` to it in `Collection`, and then pass it to `renderTitle()`. Do you want to give that a try?

Comment (Dillweed5446) [reply client/devdocs/design/search-collection.jsx:109]: Yeah, for sure!  I'll try this out now.

File: client/devdocs/docs-example/wrapper.jsx [hunk 3]
```diff
@@ -24,6 +26,7 @@ class DocsExampleWrapper extends Component {
 		name: PropTypes.string.isRequired,
 		unique: PropTypes.bool,
 		url: PropTypes.string.isRequired,
+		pageScroll: PropTypes.func.isRequired,
```
Comment (michaeldcain) [inline client/devdocs/docs-example/wrapper.jsx:29]: I don't think there's a need to make this required.

File: client/devdocs/design/search-collection.jsx [hunk 4]
```diff
@@ -102,7 +106,12 @@ const Collection = ( {
 
 		return (
 			<div>
-				<DocsExampleWrapper name={ exampleName } unique={ !! component } url={ exampleLink }>
+				<DocsExampleWrapper
+					name={ exampleName }
+					unique={ !! component }
+					url={ exampleLink }
+					pageScroll={ scroll }
```
Comment (michaeldcain) [inline client/devdocs/design/search-collection.jsx:113]: I think the prop's name should be more descriptive of how it applies to the component, not what the passed method does. Can you name the prop `onTitleClick`

**Comment by Dillweed5446** [comment]
No worries!  Happy to help.  I've learned a lot through this process.  Thank you.

File: client/devdocs/docs-example/wrapper.jsx [hunk 5]
```diff
@@ -26,7 +26,6 @@ class DocsExampleWrapper extends Component {
 		name: PropTypes.string.isRequired,
 		unique: PropTypes.bool,
 		url: PropTypes.string.isRequired,
-		pageScroll: PropTypes.func.isRequired,
```
Comment (michaeldcain) [inline client/devdocs/docs-example/wrapper.jsx]: Sorry, still need the `propType` definition, just not the `isRequired` :)

Comment (Dillweed5446) [reply client/devdocs/docs-example/wrapper.jsx]: Haha, of course!
