### PR TITLE
TinyMCE: Update empty paragraph regex to match core.

### LINKED ISSUE #9265: Calypso: Failing page edit screen for specific page/user
#### Steps to reproduce
This is a localised bug to a specific site and page: 2908969-t

I can confirm the issue on the original site. I tried using the same content on a test site and didn’t experience the issue.

#### What I expected
Clicking edit on the page in Calypso would load the page content for editing.

#### What happened instead
Page content does not load, nothing is clickable and the browser tab eventually crashes.

#### Browser / OS version
Chrome Version 54.0.2840.87
OS X 10.10.5

#### Screenshot / Video
edit

#### Context / Source

#manual-testing, #user-report

### PR DESCRIPTION
**Pull request by timmyc**
Fixes #9265

There is some logic in the TinyMCE `wpcom` plugin that replaces empty paragraphs on `BeforeSetContent` - this was causing an endless loop for various special strings, one of which was reported in #9265, but was also reported at https://core.trac.wordpress.org/ticket/35890 and fixed in https://core.trac.wordpress.org/changeset/36597.  This branch takes the core fix, and updates the calypso version of this logic.

__To Test__
The easiest way to test this out is to login as the user in 2908969-t, and edit the page in question.  If you do so on production first, you will note that your browser tab will eventually crash.  Then test this branch locally and note the page will load in the editor - albeit a bit slowly as there are over 25k words in the post.

hat tip to @azaozz to the original fix in core!

### CODE REVIEW

**Comment by azaozz** [comment]
FYI: This was changed/fixed again in core in 4.7: https://core.trac.wordpress.org/changeset/39204.

**Comment by dmsnell** [comment]
nice citation @azaozz - backtracking is a killer!

we should be extremely skeptical of any `RegExp` that has both _alternation_ and _unbounded quantification_ such as `(a|b)+` due to it forcing the engine to compile an exponentially-expensive algorithm.

File: client/components/tinymce/plugins/wpcom/plugin.js [hunk 1]
```diff
@@ -289,10 +289,15 @@ function wpcomPlugin( editor ) {
 
 	// Remove spaces from empty paragraphs.
 	editor.on( 'BeforeSetContent', function( event ) {
-		var paragraph = tinymce.Env.webkit ? '<p><br /></p>' : '<p></p>';
-
 		if ( event.content ) {
-			event.content = event.content.replace( /<p>(?:&nbsp;|\u00a0|\uFEFF|\s)+<\/p>/gi, paragraph );
+			var paragraph = tinymce.Env.webkit ? '<p><br /></p>' : '<p></p>';
```
Comment (dmsnell) [inline client/components/tinymce/plugins/wpcom/plugin.js]: This is an interesting move because as a `var` it still gets hoisted up to where it was originally defined. @timmyc do you think it would be worth recreating this as a `const` given that it has been moved inside the `if` block?

(hint: according to our style guide we don't declare `var` bindings below the top of a function definition for this very reason)

File: client/components/tinymce/plugins/wpcom/plugin.js [hunk 2]
```diff
@@ -289,10 +289,15 @@ function wpcomPlugin( editor ) {
...
+
+			event.content = event.content.replace( /<p>([^<>]+)<\/p>/gi, function( tag, text ) {
```
Comment (dmsnell) [inline client/components/tinymce/plugins/wpcom/plugin.js]: I'm trying to understand what is the goal of this `RegExp`. Here is what I am guessing:

 - Only match `<p>` tags with no attributes such as `class` or `style` or anything else.
 - Find any content between these `<p>` tags excluding the angle brackets.
   - If that content is nothing but whitespace characters, replace the inner content with the predefined empty paragraph markup.

Further question, is the goal to transform `<p>&nbsp;</p>` into `<p><p></p></p>`?

File: client/components/tinymce/plugins/wpcom/plugin.js [hunk 3]
```diff
@@ -289,10 +289,15 @@ function wpcomPlugin( editor ) {
...
+				if ( /^(&nbsp;|\s|\u00a0|\ufeff)+$/i.test( text ) ) {
```
Comment (dmsnell) [inline client/components/tinymce/plugins/wpcom/plugin.js]: of note, `\s` already matches `\u00a0` and `\ufeff`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#special-white-space

**Comment by dmsnell** [comment]
For kicks and giggles I wondered what it would look like to use [my favorite parser generator](http://pegjs.org) and try to reproduce the desired behavior here.

the [interactive editor](http://peg.arcanis.fr/1wE8aR/1/) is a good place to play with it. the generated code is pretty big: 547 lines unminified, 4500 bytes uglified, and

**Comment by timmyc** [comment]
@azaozz thanks for the link on the latest update to this logic.  

@dmsnell thanks also for your feedback - your regex mastery always amazes me.  This particular TinyMCE plugin is really meant to mirror what is in core as closely as possible, as noted at the [top of the file](https://github.com/Automattic/wp-calypso/blob/master/client/components/tinymce/plugins/wpcom/plugin.js#L2).  Unfortunately with nobody really focusing on editor maintenance, known bugs with the logic - and their subsequent fixes don't often make it back into calypso ( as seen here ).

In the spirit of trying to keep the logic as close to core as possible, I have used the updated regex from https://core.trac.wordpress.org/changeset/39204 in 8b6cf5b - but I did extract it to a utility function with some tests.  I hope this is a good common ground between staying as close to core as possible, but adhering to calypso standards too.

File: client/components/tinymce/plugins/wpcom/wpcom-utils.js [hunk 4]
```diff
@@ -0,0 +1,18 @@
+/**
+ * Removes empty spaces from empty paragraphs
+ * This logic is borrowed from core's TinyMCE Plugin
+ *
+ * @see https://core.trac.wordpress.org/browser/trunk/src/wp-includes/js/tinymce/plugins/wordpress/plugin.js#L133
```
Comment (dmsnell) [inline client/components/tinymce/plugins/wpcom/wpcom-utils.js]: nice! although this reference will lose sync because it links to `trunk`. it might be useful to link to the commit that introduced this fix - even more context and an _always-valid_ link

File: client/components/tinymce/plugins/wpcom/wpcom-utils.js [hunk 5]
```diff
@@ -0,0 +1,18 @@
...
+ *
+ * @param  {String}   content TinyMCE Editor content
+ * @return {String}           Content with strings removed from empty paragraphs
+ */
+export function removeEmptySpacesInParagraphs( content ) {
+	return content.replace( /<p>([^<>]+)<\/p>/gi, function( tag, text ) {
```
Comment (dmsnell) [inline client/components/tinymce/plugins/wpcom/wpcom-utils.js]: @azaozz do you know what the purpose of the `[^<>]` part is for? What are we trying to match specifically? I think it works fine, but the `>` jumps out at me.

File: client/components/tinymce/plugins/wpcom/test/utils.js [hunk 6]
```diff
@@ -0,0 +1,45 @@
...
+
+describe( 'remove empty spaces in paragraphs', () => {
+	it( 'should not modify paragraphs with content', () => {
+		const content = '<p>Chicken &amp; Ribs</p>';
+
+		assert.equal( content, removeEmptySpacesInParagraphs( content ) );
+	} );
+
+	it( 'should remove &nbsp; from empty paragraphs', () => {
+		const content = '<p>&nbsp;</p>';
```
Comment (dmsnell) [inline client/components/tinymce/plugins/wpcom/test/utils.js]: What should happen when we have `<p><p>&nbsp;</p></p>`?

I don't think it's a blocker here (obviously since you're updating to match core and fixing a bug not trying to change behavior) in this situation we end up empty paragraphs again. I guess it doesn't matter much plus they are nested so in our perspective they are intentional?

**Comment by dmsnell** [comment]
> I hope this is a good common ground between staying as close to core as possible, but adhering to calypso standards too.

a great choice @timmyc! thanks much.

although I left a few more comments I'm approving the review. please take it as you will. I think the tests you wrote add significant clarity to why the code is as it is.

File: client/components/tinymce/plugins/wpcom/wpcom-utils.js [hunk 7]
```diff
@@ -2,7 +2,7 @@
  * Removes empty spaces from empty paragraphs
  * This logic is borrowed from core's TinyMCE Plugin
  *
- * @see https://core.trac.wordpress.org/browser/trunk/src/wp-includes/js/tinymce/plugins/wordpress/plugin.js#L133
+ * @see https://core.trac.wordpress.org/changeset/39204
```
Comment (dmsnell) [inline client/components/tinymce/plugins/wpcom/wpcom-utils.js]: 👍

File: client/components/tinymce/plugins/wpcom/wpcom-utils.js (hunk 5 above)
Comment (azaozz) [inline client/components/tinymce/plugins/wpcom/wpcom-utils.js]: That bit has changed several times over the last three years... Seems the purpose is to exclude nested tags, so `[^<]+` should be enough.

File: client/components/tinymce/plugins/wpcom/test/utils.js (hunk 6 above)
Comment (azaozz) [inline client/components/tinymce/plugins/wpcom/test/utils.js]: Yeah, don't think the behavior should change for broken HTML. `<p><p>&nbsp;</p></p>` will be replaced with `<p><p><br></p></p>` which in the editor DOM will become `<p></p><p><br></p><p></p>` (the closing `</p>` is optional, so the first paragraph is valid, the second is valid too, and the browser will insert the third `<p>` as "fix").

Comment (dmsnell) [inline client/components/tinymce/plugins/wpcom/test/utils.js]: interesting. thanks for the explanation!

File: client/components/tinymce/plugins/wpcom/wpcom-utils.js (hunk 5 above)
Comment (dmsnell) [inline client/components/tinymce/plugins/wpcom/wpcom-utils.js]: puzzling. thanks again for sharing the history here. I can't think of any situation which would have a `>` before a `<`

**Comment by azaozz** [comment]
Looking at this bit of code again, perhaps we should be removing these white space chars (and entities) in the DOM after the post content is loaded. It could be slower, but a lot "cleaner".
