### PR TITLE
Editor: Fix date issues in EditPostStatus

### LINKED ISSUE #10297: Editor: Date picker doesn't pick
#### Steps to reproduce
1. Starting at URL: wordpress.com/post
2. Try to pick a new date - notice the date picker doesn't close when you click a date
3. Publish the post today
4. Edit it again - still doesn't choose a different date

With enough clicking around, you can sometimes get a date change, but very very inconsistently.

You also cannot change the time - text input doesn't alter anything.

No console errors to note.

#### What I expected
To be able to choose a new publish date with a click

#### What happened instead
Nothing

#### Browser / OS version
Mac 10.12.2/Chrome/FF/Desktop/Safari

#### Screenshot
2016brokencalendar

#### Context / Source
#user-report #live-chat

### PR DESCRIPTION
**Pull request by timmyc**
This branch seeks to fix an issue with the `<EditPostStatus />` component that currently prevents the date picker from working ( fixes #10297 ).  I spent some time trying to figure out _when_ this stopped working, but wasn't able to find the exact point in time yet, I think it maybe related to #8539.

Turns out the instance of the `PostSchedule` inside `EditPostStatus` was using `this.props.post.date` as the value to display within the post scheduler.  The problem is that `this.props.post` for the component is being populated by edits in the redux state tree [[#](https://github.com/Automattic/wp-calypso/blob/master/client/post-editor/edit-post-status/index.jsx#L253)], whereas the action for modifying the post's date is being tracked in the flux `post-edit-store` [[#](https://github.com/Automattic/wp-calypso/blob/master/client/post-editor/editor-ground-control/index.jsx#L127)].

The same issue is also affecting the date display inside of `EditPostStatus` - since it too currently is using the date from the redux edits object:

new_post_ _testingtimmy2_wordpress_com_ _wordpress_com

I took a shortcut to fix the bug in this branch by passing in the `post.date` as a prop to `EditPostStatus`, but in a follow-up PR I'd like to make `EditorGroundControl` a `connect`ed component, and move the date tracking into the redux state.  There is much logic around the editor that keys off of the date to change verbiage/iconography for scheduled posts though, so that will be a bit of an involved PR.

Worth noting, using the post scheduler instance to the right of the Publish button works fine - this is perhaps why the issue has gone unnoticed:

new_post_ _testingtimmy2_wordpress_com_ _wordpress_com

__To Test__
- Open a new post in the editor
- In the sidebar, click the cog icon to expand the `EditPostStatus` component
- Click on the date label to expose the `PostSchedule` popover
- Select a date other than today, verify the date is highlighted on the calendar, and the date label changes
- Additionally launch the `PostSchedule` via the button next to the Publish button, verify the same steps work as expected.

Worth noting there is still some logic that toggles the "Future" label vs clock gridicon that is based upon the `this.props.savedPost`.  So that will not update until you save the post which I found a bit confusing too.

### CODE REVIEW

File: client/post-editor/editor-ground-control/index.jsx [hunk 1]
```diff
@@ -312,6 +312,9 @@ export default React.createClass( {
 	},
 
 	render: function() {
+		const postDate = this.props.post && this.props.post.date
```
Comment (youknowriad) [inline client/post-editor/editor-ground-control/index.jsx]: Maybe worth adding a comment to avoid dropping it before reduxifying date updates?
