### PR TITLE
E2E: fix post publishing in mobile viewport

### LINKED ISSUE #90564: E2E: fix post publishing in mobile viewport

### PR DESCRIPTION
**Pull request by olaseni**
Fix the editor basic flow in mobiles where the a post is not clicked/published.

We address this by waiting for the publish button to be attached to the DOM.

This is currently breaking some nightly e2e tests for Gutenberg. This change modifies the e2e's expectations to fit the new realities.

```

======= Failed test run #1 ==========
  Error: expect(received).toStrictEqual(expected) // deep equality
  
  Expected: "https://e2eflowtestingsimplepersonal.wordpress.com/2024/05/10/29-mindless-chipmunks-beg-fiercely/"
  Received: "https://e2eflowtestingsimplepersonal.wordpress.com/?p=1975720
  at Object.toStrictEqual (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/editor/editor__post-basic-flow.ts:207:32)
======= Failed test run #2 ==========
  Error: expect(received).toStrictEqual(expected) // deep equality
  
  Expected: "https://e2eflowtestingsimplepersonal.wordpress.com/2024/05/10/23-jazzy-ducks-sing-equally/"
  Received: "https://e2eflowtestingsimplepersonal.wordpress.com/?p=1975757
  at Object.toStrictEqual (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/editor/editor__post-basic-flow.ts:207:32)

```

Testing instructions
---

[Running e2e tests for Calypso](https://github.com/Automattic/wp-calypso/tree/trunk/test/e2e)

Run the editor schedule flow e2e edge tests, which was failing before this fix:

```bash
cd test/e2e
yarn jest --clearCache && yarn build  # clear build cache before each run


yarn jest specs/editor/editor__post-basic-flow.ts  
VIEWPORT_NAME=mobile yarn jest specs/editor/editor__post-basic-flow.ts 
```

### CODE REVIEW

File: packages/calypso-e2e/src/lib/components/editor-toolbar-component.ts [hunk 1]
```diff
@@ -253,15 +253,15 @@ export class EditorToolbarComponent {
 	/* Publish and unpublish */
 
 	/**
-	 * Returns the text present for the save/publish button.
+	 * Waits for the save/publish button.
 	 *
 	 * @returns {Promise<string>} String found on the button.
 	 */
-	async getPublishButtonText(): Promise< string > {
```
Comment (nightnei) [inline packages/calypso-e2e/src/lib/components/editor-toolbar-component.ts:260]: Oh, it looks like we indeed didn't use this method before, did we?

**Review by nightnei — APPROVED** [review]
LGTM 👍

File: packages/calypso-e2e/src/lib/components/editor-toolbar-component.ts (hunk 1 above)
Comment (olaseni) [reply packages/calypso-e2e/src/lib/components/editor-toolbar-component.ts:260]: Nope. I think I stopped using it a while ago, and forgot to clean up.
