### PR TITLE
AT E2E: fix selector for `Instagram` block in editor and published state.

### LINKED ISSUE #77190: Flaky E2E: Expected content is in published post / Configure the block (Instagram Block)
### Spec file

pecs/blocks/blocks__core-jetpack-extended.ts

### TeamCity ID

10053778

### Logs

```
locator.waitFor: Timeout 20000ms exceeded.
=========================== logs ===========================
waiting for frameLocator('iframe.instagram-media').locator('text=woocommerce').first() to be visible
============================================================
at InstagramBlockFlow.validateAfterPublish (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/blocks/block-flows/instagram.ts:70:33)
    at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/blocks/shared/block-smoke-testing.ts:90:23)
    at Promise.then.completed (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:391:28)
    at callAsyncCircusFn (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:316:10)
    at _callCircusTest (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:218:40)
    at _runTest (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:155:3)
    at _runTestsForDescribeBlock (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:66:9)
    at _runTestsForDescribeBlock (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at _runTestsForDescribeBlock (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at run (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:170:21)
    at jestAdapter (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:82:19)
    at runTestInternal (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:389:16)
    at runTest (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:475:34)
```

### PR DESCRIPTION
**Pull request by worldomonation**
Fixes https://github.com/Automattic/wp-calypso/issues/77190.

## Proposed Changes

This PR updates the selector used for the Instagram block in both editor and published state, to work with Simple and AT sites.

Key changes:
- narrow the selector in the editor canvas.
- narrow the selector in the published state.

## Testing Instructions

Passes on both AT and Simple runs locally.

**AT**
```
➜  ~/workspace/wp-calypso-third git:(trunk) ✗ TEST_ON_ATOMIC=true yarn workspace wp-e2e-tests test -- test/e2e/specs/blocks/blocks__core-jetpack-extended.ts
 PASS  specs/blocks/blocks__core-jetpack-extended.ts (24.217 s)
  Blocks: Jetpack Extended Core Blocks
    ✓ Go to the new post page (13795 ms)
    Add and configure blocks in the editor
      ✓ Instagram: Add the block from the sidebar (3128 ms)
      ✓ Instagram: Configure the block (891 ms)
      ✓ Instagram: There are no block warnings or errors in the editor (3 ms)
      ✓ Twitter: Add the block from the sidebar (1029 ms)
      ✓ Twitter: Configure the block (387 ms)
      ✓ Twitter: There are no block warnings or errors in the editor (3 ms)
    Publishing the post
      ✓ Publish and visit post (1954 ms)
    Validating blocks in published post.
      ✓ Instagram: Expected content is in published post (13 ms)
      ✓ Twitter: Expected content is in published post (212 ms)

Test Suites: 1 passed, 1 total
Tests:       10 passed, 10 total
Snapshots:   0 total
Time:        24.422 s
Ran all test suites matching /test\/e2e\/specs\/blocks\/blocks__core-jetpack-extended.ts/i.
```

**Simple**
```
➜  ~/workspace/wp-calypso-third git:(trunk) ✗ TEST_ON_ATOMIC=false yarn workspace wp-e2e-tests test -- test/e2e/specs/blocks/blocks__core-jetpack-extended.ts
 PASS  specs/blocks/blocks__core-jetpack-extended.ts (20.582 s)
  Blocks: Jetpack Extended Core Blocks
    ✓ Go to the new post page (4927 ms)
    Add and configure blocks in the editor
      ✓ Instagram: Add the block from the sidebar (3549 ms)
      ✓ Instagram: Configure the block (459 ms)
      ✓ Instagram: There are no block warnings or errors in the editor (4 ms)
      ✓ Twitter: Add the block from the sidebar (1930 ms)
      ✓ Twitter: Configure the block (470 ms)
      ✓ Twitter: There are no block warnings or errors in the editor (4 ms)
    Publishing the post
      ✓ Publish and visit post (6072 ms)
    Validating blocks in published post.
      ✓ Instagram: Expected content is in published post (8 ms)
      ✓ Twitter: Expected content is in published post (259 ms)

Test Suites: 1 passed, 1 total
Tests:       10 passed, 10 total
Snapshots:   0 total
Time:        20.78 s, estimated 22 s
Ran all test suites matching /test\/e2e\/specs\/blocks\/blocks__core-jetpack-extended.ts/i.
```

Ensure the following build configurations are passing:
  - [x] Gutenberg E2E Simple production (desktop)
  - [x] Gutenberg E2E Atomic production (desktop)
  - [x] Gutenberg E2E Simple edge (desktop)

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

File: packages/calypso-e2e/src/lib/blocks/block-flows/instagram.ts [hunk 1]
```diff
@@ -36,16 +35,12 @@ export class InstagramBlockFlow implements BlockFlow {
...
-				.getByRole( 'document', { name: 'Block: Embed' } )
-				.getByRole( 'button', { name: 'Embed' } )
-				.click();
-		}
+		await editorCanvas
+			.getByRole( 'document', { name: 'Block: Embed' } )
+			.getByRole( 'button', {
+				name: 'Embed',
+			} )
+			.click();
```
Comment (worldomonation) [inline packages/calypso-e2e/src/lib/blocks/block-flows/instagram.ts:43]: I've verified that this selector works for both AT and Simple, on Gutenberg Production and Edge.

File: packages/calypso-e2e/src/lib/blocks/block-flows/instagram.ts [hunk 2]
```diff
@@ -57,6 +52,11 @@ export class InstagramBlockFlow implements BlockFlow {
 	 */
 	async validateAfterPublish( context: PublishedPostContext ): Promise< void > {
 		// await context.page.pause();
-		await context.page.locator( '.wp-block-embed-instagram' ).waitFor();
+		await context.page
+			.getByRole( 'figure' )
+			.filter( {
+				hasText: 'View this post on Instagram',
+			} )
+			.waitFor();
```
Comment (worldomonation) [inline packages/calypso-e2e/src/lib/blocks/block-flows/instagram.ts]: The previous selector was matching on two elements (somehow).

File: packages/calypso-e2e/src/lib/blocks/block-flows/instagram.ts [hunk 3]
```diff
@@ -56,7 +51,11 @@ export class InstagramBlockFlow implements BlockFlow {
...
 	 */
 	async validateAfterPublish( context: PublishedPostContext ): Promise< void > {
-		// await context.page.pause();
-		await context.page.locator( '.wp-block-embed-instagram' ).waitFor();
+		await context.page
+			.getByRole( 'figure' )
+			.filter( {
+				hasText: 'View this post on Instagram',
+			} )
+			.waitFor();
```
Comment (WunderBart) [inline packages/calypso-e2e/src/lib/blocks/block-flows/instagram.ts]: Would this work as well?
```suggestion
		await context.page
			.getByText( 'View this post on Instagram' )
			.waitFor();
```

**Review by WunderBart — APPROVED** [review]
🚢

File: packages/calypso-e2e/src/lib/blocks/block-flows/instagram.ts (hunk 2 above)
Comment (WunderBart) [reply packages/calypso-e2e/src/lib/blocks/block-flows/instagram.ts]: Possibly due to proxxied content?

File: packages/calypso-e2e/src/lib/blocks/block-flows/instagram.ts (hunk 3 above)
Comment (worldomonation) [reply packages/calypso-e2e/src/lib/blocks/block-flows/instagram.ts]: I don't see why it wouldn't work - let me give it a try.

Comment (worldomonation) [reply packages/calypso-e2e/src/lib/blocks/block-flows/instagram.ts]: Seems to work locally with proxy on and off. 

Triggering a Gutenberg build in CI to make sure it works there too.
