### PR TITLE
Signup: Reset `submitting` state when API returns `invalid_password`

### LINKED ISSUE #69749: Weak password banner disables ability to edit password on signup form
## Description

I just ran into a critical bug trying to create a new [WP.com](http://wp.com/) site. I just tossed in a random assortment of characters as a password (`passjdks`) and saw this banner alert, but the form fields became disabled, so I couldn't actually change my password. 

CleanShot 2022-11-03 at 11 16 41@2x

I went through the flow again and recorded a video, just to make sure I could reproduce the issue.

https://user-images.githubusercontent.com/5634774/199762556-edc778dd-5dab-4f3c-ab42-b6d9520fa2b8.mp4

## Expected

That I'd be able to update my password

## Actual

The form fields became disabled, so I couldn't edit my password.

## Steps to reproduce

1. Open incognito tab
2. Go to [https://wordpress.com/start/](https://wordpress.com/start/)
3. Put in an email, username and weak password ( I used: passjdks)

## Setup

Mac Monterey 12.6
Chrome Version 106.0.5249.119 (Official Build) (arm64)

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes https://github.com/Automattic/wp-calypso/issues/69749

Discussion in p1667488915693849-slack-C029GN3KD

## Proposed Changes

Deliberately uses `UNSAFE_componentWillReceiveProps` on the `<SignupForm>` component to set `this.setState( { submitting: false } );` when the `users/new` endpoint returns an `invalid_password` error. Notably, there's some client-side validation for the password, but `passjdks` slips past that to cause an API error.

Ideally, `<SignupForm>` wouldn't use `submitting` state that's dependent on props, but that's a refactor for another time.

### Before

CleanShot 2022-11-03 at 10 03 39

### After

CleanShot 2022-11-03 at 10 00 31

## Testing Instructions

1. Navigate to `/start/user`.
2. Enter a email address and username that aren't associated with a WordPress.com user.
3. Enter `passjdks` as the password.
4. Submit the form.
5. Observe the form become editable again once the error displays.

### CODE REVIEW

File: client/blocks/signup-form/index.jsx [hunk 1]
```diff
@@ -163,6 +163,14 @@ class SignupForm extends Component {
 		this.maybeRedirectToSocialConnect();
 	}
 
+	UNSAFE_componentWillReceiveProps( nextProps ) {
+		if ( this.props.step?.status === 'processing' && nextProps.step?.status === 'invalid' ) {
```
Comment (danielbachhuber) [inline client/blocks/signup-form/index.jsx:167]: I'm not 100% confident these statuses proceed in a linear manner, but this is what appeared to happen in my testing:

image

```
diff --git a/client/blocks/signup-form/index.jsx b/client/blocks/signup-form/index.jsx
index 1e30e4649d..f70c7774f4 100644
--- a/client/blocks/signup-form/index.jsx
+++ b/client/blocks/signup-form/index.jsx
@@ -164,6 +164,7 @@ class SignupForm extends Component {
 	}
 
 	UNSAFE_componentWillReceiveProps( nextProps ) {
+		console.log( this.props.step?.status, nextProps.step?.status );
 		if ( this.props.step?.status === 'processing' && nextProps.step?.status === 'invalid' ) {
 			this.setState( {
 				submitting: false,

```

Comment (zaguiini) [reply client/blocks/signup-form/index.jsx:167]: Is it necessary to check if the current status is processing? We know for sure that the user is not `submitting` if the status is invalid.

Is using [`getDerivedStateFromProps`](https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops) a good idea in this case? Example:

```ts
static getDerivedStateFromProps( props ) {
    if( props.step?.status === 'invalid' ) {
      return {
        submitting: false
      }
    }

    return null
}
```

My main question is: why do we need to imperatively mutate the state here? Why? What kind of blind case are we hitting that isn't covered by our state management yet? I think answering this question will likely lead to a better fix than this attempt at patching the existing flow.

**Comment by vykes-mac** [comment]
This looks like a quick and dirty fix due to critical nature but will need revisiting.

File: client/blocks/signup-form/index.jsx (hunk 1 above)
Comment (danielbachhuber) [reply client/blocks/signup-form/index.jsx:167]: > Is it necessary to check if the current status is processing? We know for sure that the user is not `submitting` if the status is invalid.

@zaguiini I don't think it's _necessary_. But, it would limit the context in which this change is applied, which makes me feel more confident about not causing some other bug.

> Is using [`getDerivedStateFromProps`](https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops) a good idea in this case? Example:

I considered it after reviewing the docs. However, I determined `UNSAFE_componentWillReceiveProps` to be a more "correct" fix because we shouldn't be managing state in this component anyway. `UNSAFE_componentWillReceiveProps` more clearly calls out that this is problematic.

> My main question is: why do we need to imperatively mutate the state here? Why? What kind of blind case are we hitting that isn't covered by our state management yet? I think answering this question will likely lead to a better fix than this attempt at patching the existing flow.

My concern with a "better fix" is that it will likely touch more code paths, which then leads to greater likelihood of breakage. I don't think the risks associated with refactoring are worth it, at the moment.

Comment (zaguiini) [reply client/blocks/signup-form/index.jsx:167]: >because we shouldn't be managing state in this component anyway.

Not really sure about this statement in specific. This component has different pieces of state that are, indeed, derived from the props, so it looks like the perfect match 🤔 Also, using `getDerivedStateFromProps` will skip re-rendering (as it happens when you call `setState` inside `componentWillReceiveProps`) so I do think it's a better option, and the lifecycle is going to be used as it's meant to be so it doesn't look inadequate at all.

>I don't think the risks associated with refactoring are worth it, at the moment.

That's also true. Let's ship this fix first, with your proposal or mine, then properly fix the issue as a follow-up.

Comment (p-jackson) [reply client/blocks/signup-form/index.jsx:167]: > then properly fix the issue as a follow-up.

These things have a tendency to be left the way they are for quite a long time, so I'd personally go with the `getDerivedStateFromProps` solution. It isn't quite as surgical but it's worked perfectly in my testing and doesn't add yet more `UNSAFE_` methods to clean up later.

**Review by p-jackson — APPROVED** [review]
This component is referenced in some other signup flows so I've tested there too.

It's referenced in Jetpack Connect code, but it doesn't seem to be utilised in any user-accessible flow. If the user doesn't have a wpcom account when going through Jetpack Connect then they are taken through the magic-email-link signup flow.

It's also reference in the P2 invite flow. If you have a P2 workspace you can create an invite link.
CleanShot 2022-11-04 at 11 55 17@2x
The issue wasn't reproducible in this flow though. And this PR doesn't introduce any issues.

Approving because I've tested and it fixes the issue. But as noted above I think the `getDerivedStateFromProps` fix would be better.

File: client/blocks/signup-form/index.jsx (hunk 1 above)
Comment (danielbachhuber) [reply client/blocks/signup-form/index.jsx:167]: @zaguiini @p-jackson Looking at this further, one side effect of `getDerivedStateFromProps()` is that the form would stay in a `submitting=false` state for several cycles until the step status changed again (as it will continue to remain `invalid` while the user completes the form).

I'd like to keep `UNSAFE_componentWillReceiveProps` because it's really the _transition_ from `processing` to `invalid` that we care about. When this event happens, we want to set `submitting=false` and be done with it. `getDerivedStateFromProps` doesn't support explicitly hooking into that transition.
