### PR TITLE
Devdocs: Fix page change lag in devdocs (fix #22756)

### LINKED ISSUE #22756: Framework: Changing between loaded Devdocs pages lags
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/devdocs/design
2. Navigate to the blocks page (http://calypso.localhost:3000/devdocs/blocks)
3. Click the UI Components link to load that page again
4. Wait a few seconds to a screen with no loading indicator while hundreds of components are loaded

#### What I expected
Components are lazy rendered or an interstitial loading screen is displayed.

#### What happened instead
The page loads but no screen/indicator is given and it seems like nothing is happening.

This is more apparent after #20690 because the first time the page loads we show a placeholder page as the components are asynchronously loaded.

### PR DESCRIPTION
**Pull request by tofumatt**
This aims to fix #22756 by reducing the delay in page changes on the devdocs pages. Especially `/devdocs/blocks` and `/devdocs/design`.

------

Originally posted in #22756:

I talked to @nb about this but it seems the main issue is around the (very large) number of components mounted inside these pages (`/devdocs/blocks` and `/devdocs/design`). Pagination through the components wouldn't be a good UX so continuing to load all of the examples on the page is what I aimed to keep.

First off I tried using something like [`react-virtualized`](https://github.com/bvaughn/react-virtualized) to load only the content on screen but because the components are of varying heights that lead to only a ~10-20% reduction in mounting time and a worse scrolling UX. It also meant the entire page would never be mounted at once so in-browser "find" UX was ruined.

Using [`react-lazily-render`](https://github.com/jameslnewell/react-lazily-render) turned out to work much better, and using it means we can load the first X number of components immediately (basically enough to fill the viewport) so the component mounts in a fraction of the time it did in the past (for reference, it mounts faster using React development environment with the change than it currently does in production with the old "mount everything at once" approach). We can then load the rest of the components either: onScroll or after a few seconds with a timeout. The underlying code used is a bit gnarly but the API of the Devdocs `Collection` remains the same with the heavy-lifting/lazy-loading happening transparently, so this approach will scale if more components/pages are added.

### CODE REVIEW

**Comment by tofumatt** [comment]
I should point out that I tested this locally on my MacBook (mid-2017, 1.4 GHz Intel Core i7) in Firefox Developer Edition, Chrome release, and Safari on MacOS and saw what I felt to be a noticeable performance increase. I didn't script a performance benchmark test but running the profiler in Firefox and Chrome saw a least a full second decrease in page load time switching between pages.

This is obviously anecdotal so I'd love a more comprehensive perf test (I could script one if there aren't any easily accessible tools to do one) and/or other developers eyes on this one.

This is what a few tests in Firefox yielded:

### Current Devdocs

`render()` time (Promise callback) | Click + `render()` total time
---------------------------------- | -----------------------------
3,122ms                            | 3,385ms
1,821ms                            | 1,940ms
1,775ms                            | 1,915ms

### Lazy render implementation

`render()` time (Promise callback) | Click + `render()` total time
---------------------------------- | -----------------------------
539ms                              | 800ms
384ms                              | 600ms
300ms                              | 580ms

File: client/devdocs/design/search-collection.jsx [hunk 1]
```diff
@@ -31,49 +34,100 @@ const shouldShowInstance = ( example, filter, component ) => {
...
+					The entire list of examples for `/devdocs/blocks` and
+					`/devdocs/design` takes a long time to mount, even when
+					loaded, so we render just the first few components so
+					the page change feels faster. The rest of the components
+					are loaded either once scrolled to or in a few seconds
+					after `componentDidMount()` is called.
+				*/ }
+				{ examples.slice( 0, examplesToMount ) }
+
+				<LazyRender ref={ this._setLazyRenderRef }>
```
Comment (tofumatt) [inline client/devdocs/design/search-collection.jsx]: This could well be a useful component type to have abstracted if we have other large pages that could be progressively mounted. There's also a few creative solutions we could take to split the sections into smaller chunks than just "the first seven" and the "all the rest" but I started with this to see what people thought of the approach. It ends up *feeling* a lot faster even if technically the component is a bit more complicated under the hood.

Comment (tofumatt) [reply client/devdocs/design/search-collection.jsx]: If this approach is cool with people it might be worth adding that actually, as the smaller DOM changes should feel more performant and not thrash the browser as much. I can probably add it without too much fuss.

File: client/devdocs/design/search-collection.jsx [hunk 2]
```diff
@@ -31,49 +34,106 @@ const shouldShowInstance = ( example, filter, component ) => {
...
+					loaded, so we render just the first few components so
+					the page change feels faster. The rest of the components
+					are loaded either once scrolled to or in a few seconds
+					after `componentDidMount()` is called.
+				*/ }
+				{ examples.length <= examplesToMount ? (
+					examples
+				) : (
+					<React.Fragment>
+						{ examples.slice( 0, examplesToMount ) }
```
Comment (tofumatt) [inline client/devdocs/design/search-collection.jsx]: This could well be a useful component type to have abstracted if we have other large pages that could be progressively mounted. There's also a few creative solutions we could take to split the sections into smaller chunks than just "the first seven" and the "all the rest" but I started with this to see what people thought of the approach. It ends up *feeling* a lot faster even if technically the component is a bit more complicated under the hood.

Comment (tofumatt) [reply client/devdocs/design/search-collection.jsx]: If this approach is cool with people it might be worth adding that actually, as the smaller DOM changes should feel more performant and not thrash the browser as much. I can probably add it without too much fuss.

File: client/devdocs/design/search-collection.jsx [hunk 3]
```diff
@@ -31,49 +34,106 @@ const shouldShowInstance = ( example, filter, component ) => {
...
+		filter: PropTypes.string,
+		section: PropTypes.string,
+	};
+
+	static defaultProps = {
+		examplesToMount: 7,
+		section: 'design',
+	};
+
+	_setLazyRenderRef = ref => {
```
Comment (nb) [inline client/devdocs/design/search-collection.jsx]: We usually try to avoid underscore-prefixed names – they don't bring too much meaning.

File: client/devdocs/design/search-collection.jsx [hunk 4]
```diff
@@ -31,49 +34,106 @@ const shouldShowInstance = ( example, filter, component ) => {
...
+		this._lazyRender = ref;
+	};
+
+	componentDidMount = () => {
+		this._lazyRenderTimeout = setTimeout( () => {
+			// HACK: Reach into the <LazyRender> component and force all
+			// examples to be mounted after a few seconds of the component
+			// being mounted. This means if the user loads the page and
+			// changes context the rest of the content won't wait to load
+			// until they scroll down.
```
Comment (nb) [inline client/devdocs/design/search-collection.jsx]: I am not sure I understand the trade-off here – is the hack (good job at dissecting how the lazy render component works) worth the wait once we change the context? Also, what are some UX scenarios when somebody changes the context, I am failing to imagine that.

File: client/devdocs/design/search-collection.jsx (hunk 2 above)
Comment (nb) [reply client/devdocs/design/search-collection.jsx]: This starts to sounds more and more like infinite scroll, or am I missing something?

**Comment by tofumatt** [comment]
Regarding removing existing rendered elements–I tried that with `react-virtualized` but it didn't work great. Here are the issues:

1. example components are variable height, so you still need to render them off-screen to calculate height on initial render so the scrolling works well. This means initial render is actually not much faster–sometimes it saves `~300ms`, but adds a lot of complexity to the render
2. the scrolling experience is diminished then and scrolling itself becomes a lot slower because we're managing which components are rendered and which aren't based on scroll events. These are debounced so it actually takes some time to catch up to the scroll, making the page feel slow
3. removing elements from the page means in-browser find is not longer usable. This is a minor point.

----

Ultimately, this is sort of an infinite scroll solution but with an added background load of the rest of the content (which is known and not remotely-fetched) using the `setTimeout`. The result is clicking on the page feels fast and switch between pages is fast. But we aren't forcing the user to scroll many times to load all content... I actually tried that approach by wrapping *every* `<DocsExampleWrapper>` in `<LazyRender>` but it made scrolling down really annoying... I can attach a screencast if you like. This solution means provides two user stories, basically:

### User sees placeholder scrolling
1. Click "Blocks" or "Design"
2. Page loads quickly with first few elements
3. User instantly starts scrolling to bottom
4. Placeholders appear while rest of components are mounted (this takes about 1-2s)
5. Components are all mounted and page is fully ready

### User doesn't see placeholders
1. Click "Blocks" or "Design"
2. Page loads quickly with first few elements
3. User doesn't interact with page right away, reads the first few components, or otherwise does something else
4. `setTimeout` fires after 2s and loads rest of page in ~1-2s
5. Components are all mounted and page is fully ready, entirely transparent to the user but without the initial render lag

Hope that makes sense 😄

File: client/devdocs/design/search-collection.jsx (hunk 4 above)
Comment (tofumatt) [reply client/devdocs/design/search-collection.jsx]: I guess I should clarify the comment, it's not even changing contexts (switching tabs, changing apps, etc.), but simply *not* scrolling down past the first "X" number of elements within the first few seconds. If the user loads the page and reads a few components, then scrolls down, this could fire. It could be that it's too generous and a timeout of something like `400ms` is more appropriate though.

It basically means if the page isn't scrolled past the loaded content right away we load the rest in the background, transparent to the user, so they aren't left waiting later when we can just load it now.

File: client/devdocs/design/search-collection.jsx (hunk 2 above)
Comment (tofumatt) [reply client/devdocs/design/search-collection.jsx]: It is in a sense, but it's specific to rendering existing content (large amounts of it), rather than waiting on content to load based on an asynchronous action like an API request.

Comment (tofumatt) [reply client/devdocs/design/search-collection.jsx]: It could be that we don't want to bother with the scrolling and simply load more content after the timeout so the render is gradual (which thanks to React's virtual DOM diffing actually thrashes less than loading everything at once).

It's sort of hacky but it definitely thrashes less and *feels* more immediate.

**Comment by tofumatt** [comment]
Hey @nb, I've made a few changes to how this works. The original was more like an infinite scroll in that it waited a few seconds before just automatically mounting the rest of the components. Turns out we could wait a lot less time and still get the desired effect, with an added benefit of the re-render being nearly totally transparent to most users.

I also removed the hack/proof-of-concept approach of digging into the child component's `setState` call from the parent and just made a `DelayRender` component that loads after a set amount of time.

This seems like an odd patch I'll admit looking at it, but the solution definitely improves responsiveness of the page. This new one feels less like infinite scroll as the component simply mounts the rest of the components after 20ms, but this makes a notable difference especially in dev mode.
