### PR TITLE
Preserve sidebar collapse state after switching site

### LINKED ISSUE #47019: Transition from the site-switcher back to the menu animation
After merging #46689 we just need to make the transition from the site-switcher back to the menu smoother by hiding the overflowing menu till transition is over

This is what is happening currently:
SS 2020-11-02 at 15 45 28

_Originally posted by @cpapazoglou in https://github.com/Automattic/wp-calypso/issues/46643#issuecomment-720481954_

### LINKED ISSUE #52261: Nav Unification: Collapse State Not Preserved After Switching Site
### Steps to reproduce the behavior

1. Go to https://wordpress.com/home and pick any site you have
2. Click on `Collapse menu ` at the bottom of the left sidebar
3. Click `Switch Site` and pick another site
4. Click `Switch Site`again and select the previous site again
5. See the sidebar uncollapsed

#### What I expected to happen

See the sidebar collapsed

#### What actually happened

Sidebar uncollapsed

### Context

Manual testing after user's report in 3934837-zd-woothemes who wanted to have the sidebar consistently collapsed but could not.
#### Browser / OS version
Chrome 89 on macOS
#### Is this specific to the applied theme? Which one?
No
#### Does this happen on simple or atomic sites or both?
Both
#### Is there any console output or error text?
No
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low
#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/39308239/115953258-069ea300-a4f3-11eb-8f37-81d40e3bc09c.mov

https://user-images.githubusercontent.com/39308239/115953290-3baaf580-a4f3-11eb-9deb-42eb827f2926.mov

### PR DESCRIPTION
**Pull request by mmtr**
#### Changes proposed in this Pull Request

Preserves the collapse state of the sidebar when a user switches to a different site. This exposed more prominently the styling issue during the sliding transition described in https://github.com/Automattic/wp-calypso/issues/47019, so this PR also tries to fix that by changing the overflowing styles once the CSS animation finishes.

#### Testing instructions

* Open Calypso.
* Click on "Collapse menu".
* Make sure the sidebar has been collapsed.
* Click on "Switch site".
* Make sure the sidebar has been expanded.
* Pick a different site.
* Make sure the sidebar is now collapsed.

Fixes https://github.com/Automattic/wp-calypso/issues/52261
Fixes https://github.com/Automattic/wp-calypso/issues/47019

### CODE REVIEW

**Review by cpapazoglou — APPROVED** [review]
Thanks @mmtr for working on this! That's a very clever solution!

I tested this and works great 🎉!

On the meantime though, it has exposed an other issue from the past https://github.com/Automattic/wp-calypso/issues/47019 which now is more obvious when the sidebar is collapsed. How would you feel removing the transition here 
https://github.com/Automattic/wp-calypso/blob/0c1176ddf16227307480fa4852e47cfe089bf181/client/layout/style.scss#L18

I am approving this, anyway!

**Comment by mmtr** [comment]
> On the meantime though, it has exposed an other issue from the past #47019 which now is more obvious when the sidebar is collapsed. 

Thanks for pointing that out! I also noted it and wondered where the animation was coming from. Will try to fix it.

**Comment by mmtr** [comment]
> How would you feel removing the transition here

I had to keep it because if affected the navigation on mobile viewports. In cd81cb3 I opted for applying the overflow styles via JS after the CSS transition finishes which was the underlying issues since `overflow` is not an animatable CSS property.

File: client/layout/index.jsx [hunk 1]
```diff
@@ -87,6 +87,33 @@ function SidebarScrollSynchronizer( { enabled } ) {
...
+
+	React.useEffect( () => {
+		if ( layoutFocus !== 'sites' ) {
+			// Since `overflow` isn't an animated CSS property, we need to set it
+			// after the CSS transition of the layout elements finishes.
+			// @see https://github.com/Automattic/wp-calypso/blob/0c1176ddf16227307480fa4852e47cfe089bf181/client/layout/style.scss#L18
+			// @see https://github.com/Automattic/wp-calypso/issues/47019
+			setTimeout( () => {
+				setSidebarOverflowClass( true );
+			}, 500 );
```
Comment (cpapazoglou) [inline client/layout/index.jsx:110]: Can we align the timing `500` closer to the transition `150`?

**Review by cpapazoglou — APPROVED** [review]
This works great now! Thanks for revisiting! I just left an ultra minor comment.

File: client/layout/index.jsx (hunk 1 above)
Comment (mmtr) [reply client/layout/index.jsx:110]: I tried it, but it seems that the transition doesn't start immediately after the current layout focus changes from `sites` to `sidebar`. When the timeout is set to `150`, the `overflow` property is applied before the transition finishes.

I guess there is either a component async loaded or an async API request that is delaying the start of the sidebar rendering. I couldn't identify where is happening that, so finally opted for extending the timeout. Going to add a comment clarifying that.

**Comment by BogdanUngureanu** [comment]
Works for me as well, but I've found this small unrelated issue:

https://user-images.githubusercontent.com/995955/116520889-fb28ee80-a8db-11eb-8648-5df7f0928198.mov

**Comment by mmtr** [comment]
> I've found this small unrelated issue:

Good catch, seems a side effect of #47019. Wondering if entirely disabling the sliding animation when the sidebar is collapsed can avoid all these issues. Will take a quick look at that before merging.

**Comment by mmtr** [comment]
> Good catch, seems a side effect of #47019. Wondering if entirely disabling the sliding animation when the sidebar is collapsed can avoid all these issues. Will take a quick look at that before merging.

This should be addressed now. Can I get a quick confidence check before merging?

**Comment by BogdanUngureanu** [comment]
Works great now! 🎉 

One question though, should the nav also collapse for JP sites even though they are not part of nav-unification rollout? 🤔

**Comment by mmtr** [comment]
> One question though, should the nav also collapse for JP sites even though they are not part of nav-unification rollout? 🤔

No, because the collapse/expand buttons are only visible in the new unified menu.
