### PR TITLE
Fix: Post checkout flow broken

### LINKED ISSUE #36290: Signup/Checkout: User is redirected to plans page instead of the checklist
One of e2e tests is failing — after sign up, Plans page is displayed instead Checklist:

slack-imgs

Test name: Sign up for a site on a personal paid plan coming in via /create as personal flow in GBP currency @parallel
CircleCI execution: https://circleci.com/gh/Automattic/wp-calypso/432731
You can find screenshot/video in Artifacts tab > Container 1 > tmp > artifacts > screenshots > screenshots

### PR DESCRIPTION
**Pull request by niranjan-uma-shankar**
#### Changes proposed in this Pull Request

* When going through the signup flow, post checkout gives a JS error:

Screenshot 2019-10-04 at 2 43 21 PM

This leads to:
1. Post checkout upsell nudges not being shown
2. Post checkout redirect to /plans instead of customer home page.

* This bug is related to the changes made in https://github.com/Automattic/wp-calypso/pull/35757
* The bug occurs because the state variable `this.state.shouldDisplaySiteCreatedNotice` in [this line](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/checkout/checkout/checkout-container.jsx#L77) does not get reset when the upsell offer nudge reloads the `<CheckoutContainer>` component [here](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/checkout/controller.jsx#L159), retaining its `true` value when in fact it should be `false`. As a result, `<SignupSiteCreatedNotice>` component is mounted [here](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/checkout/checkout/checkout-container.jsx#L79) with a null `this.props.selectedSite` value.

#### Testing instructions

* Go through the signup flow and add a Personal plan to cart
* Complete checkout and verify that the Quick Start session upsell is shown
* Clicking Yes(and completing payment) or No on the upsell nudge should take you to the checklist
* Repeat with a Business plan in cart. Verify that post checkout no upsell nudge is shown and that you're taken to checklist.

Fixes https://github.com/Automattic/wp-calypso/issues/36290

### CODE REVIEW

File: client/my-sites/checkout/controller.jsx [hunk 1]
```diff
@@ -160,6 +160,7 @@ export function upsellNudge( context, next ) {
 			shouldShowCart={ false }
 			clearTransaction={ true }
 			purchaseId={ Number( receiptId ) }
+			isComingFromSignup={ !! context.query.signup }
```
Comment (michaeldcain) [inline client/my-sites/checkout/controller.jsx]: Unrelated to this fix - can we use this prop to log purchases from Signup (vs. purchases from later in the user experience)?

**Review by p-jackson — DISMISSED** [review]
Nice tracking down of the root cause of the bug! It seems to me that deriving state from props like this always causes bugs! 🐛 

If this fixes #36290 then can we **re-enable the test described here**? https://github.com/Automattic/wp-calypso/issues/36290#issuecomment-535028460

I don't think calling `setState` inside `sCU` is the right thing to do and I was trying to think how this bug could be fixed without using the `sCU` method at all.

I don't think we actually need to use derived state i.e. `shouldDisplaySiteCreatedNotice` doesn't need to be state. We can just check the props directly whenever we need them. What do you think about this approach? https://gist.github.com/p-jackson/1b09c98fb70b646754cda6f9460c03b3

In this patch, checking for `this.props.selectedSite` in `shouldDisplaySiteCreatedNotice()` is what fixes the bug you discovered.

File: client/my-sites/checkout/checkout/checkout-container.jsx [hunk 2]
```diff
@@ -50,6 +50,15 @@ class CheckoutContainer extends React.Component {
 		}
 	}
 
+	shouldComponentUpdate( nextProps ) {
+		if ( this.props.isComingFromSignup !== nextProps.isComingFromSignup ) {
+			this.setState( { shouldDisplaySiteCreatedNotice: nextProps.isComingFromSignup } );
```
[the remark this answers is not in the document]
Comment (niranjan-uma-shankar) [reply client/my-sites/checkout/checkout/checkout-container.jsx]: Great suggestion, fixed in [fe0537e](https://github.com/Automattic/wp-calypso/pull/36538/commits/fe0537e2603c85adb12aa5a8e5f2ffdda63b7cc5)

File: client/my-sites/checkout/controller.jsx (hunk 1 above)
Comment (niranjan-uma-shankar) [reply client/my-sites/checkout/controller.jsx]: I don't think so. This prop will also be true when going through the site launch flow for a private site, and also when going through the flow via "Add new site". So, purchases made here will not reflect a signup purchase.

Comment (niranjan-uma-shankar) [reply client/my-sites/checkout/controller.jsx]: If we want to include post-checkout upsell purchases(Quick Start session/GSuite) as purchases from Signup, then we need to carry over the prop to the upsell nudge URLs. We would still have the issue of having to disambiguate purchases made during the launch flow.

Comment (michaeldcain) [reply client/my-sites/checkout/controller.jsx]: > This prop will also be true when going through the site launch flow for a private site, and also when going through the flow via "Add new site". So, purchases made here will not reflect a signup purchase.

I would consider 'going through the flow via "Add new site"' as a Signup purchase (a user is creating a new site), but you're right about the launch flow purchases - those are definitely different.

Thanks for the explanation!

File: client/my-sites/checkout/checkout/checkout-container.jsx [hunk 3]
```diff
@@ -56,7 +56,6 @@ class CheckoutContainer extends React.Component {
 	shouldDisplaySiteCreatedNotice() {
 		return (
 			this.props.isComingFromSignup &&
-			this.props.selectedSite &&
```
Comment (p-jackson) [inline client/my-sites/checkout/checkout/checkout-container.jsx]: Good call, I didn't notice how `''` was being passed as the default parameter to `isSiteCreatedDateNew`

**Review by p-jackson — APPROVED** [review]
Failing tests look like this issue: p1570436558052400-slack-C1A1EKDGQ

Thanks for the changes, lgtm!
