### PR TITLE
Advanced SEO: Social Preview Fixes

### LINKED ISSUE #7784: Advanced SEO: Missing Titles and html entities
In the advanced seo preview, Characters like `&nbsp;` are showing up, and titles are missing if you haven't set a custom title format.

screen_shot_2016-08-31_at_11 03 46_480

### PR DESCRIPTION
**Pull request by roundhill**
Fixes #7784

**To test**
*  Preview a post in the SEO pane, without ever setting a custom title format. You should see the post title for all previews (Google, Facebook, etc)
*  Preview a post that has a custom title format set, the custom format should show on all of the previews _except_ the ReaderPreview.
*  Add a `&nbsp;` entity to a post, you should not see it any of the previews.

cc @dmsnell 

Test live: https://calypso.live/?branch=fix/7784-advanced-seo-titles

### CODE REVIEW

File: client/lib/post-normalizer/rule-create-better-excerpt.js [hunk 1]
```diff
@@ -55,7 +55,8 @@ export function formatExcerpt( content ) {
 		}
 	} );
 
-	const betterExcerpt = trim( dom.innerHTML );
+	// trim and replace &nbsp; entities
+	const betterExcerpt = trim( dom.innerHTML.replace( /&nbsp;/g, '' ) );
```
Comment (dmsnell) [inline client/lib/post-normalizer/rule-create-better-excerpt.js]: @roundhill did you mean to replace `&nbsp;` with `' '` instead of `''`? It looks from this diff like we're eliminating the whitespace instead of replacing it.

Comment (roundhill) [inline client/lib/post-normalizer/rule-create-better-excerpt.js]: oh, yes! Oopsie.

**Comment by dmsnell** [comment]
:shipit:
