### PR TITLE
Editor: Add missing translations

### LINKED ISSUE #8307: Editor: Untranslated tooltips for editor icons
#### Steps to reproduce
1. Change to a non-english language http://calypso.localhost:3000/me/account
2. Start editing a post http://calypso.localhost:3000/post/
3. Hover over the icon tooltips, and notice that many tooltips are untranslated (e.g. `Insert/edit link`, `Toggle Advanced`, `Horizontal Line`, `Text Color`, `Paste as text`, `Special characters`, `Keyboard Shortcuts` )

These strings are translated in GlotPress (e.g. [gp `Insert/edit link`](https://translate.wordpress.com/projects/wpcom/es/default/?filters%5Bterm%5D=Insert%2Fedit+link&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc), so they should be translated in the UI

editar_entrada_ _julesauspremiumtest_ _wordpress_com

#manual-testing

### PR DESCRIPTION
**Pull request by deBhal**
This PR Fixes #8307, along with a couple of other issues I noticed along the way.

There were 3 different problems:

1.  We were missing several translations for TinyMCE's internal strings
2. We were missing some translate wrappers around strings in our TinyMCE plugins
3. We were missing translate wrappers around some strings that we were using to build the contact form

Oh, and I fixed a pair of ellipses while I was in there, because that's my idea of fun :)

### Testing
`Insert/edit link` and `Keyboard Shortcuts` should be fixed immediately, as they're already in the translations we're serving.

For verifying the rest, we need to check:
1. That the strings will get translated: Compare the `calypso-strings.pot` generated by `make translate` before and after the change, and verify that the missing strings are added (this includes `Toggle Advanced`, `Horizontal line`, `Text Color`, `Paste as text`, `Special characters`) .
2. That the translations will be used: This is a bit tricky.  The easiest way is probably to edit the strings where the translate calls are occurring (say, by appending '(yay!)' onto them) and verifying that these are the strings that TinyMCE is using for the tooltips in question.

The ideal test is to circle back the day after the change is deployed and verify that the strings are translated. Most of the translations are already in GlotPress, and just not included in the calypso translations bundle, but `Toggle Advanced` will need to go out to translators before the translations go up.

cc @rodrigoi

### CODE REVIEW

File: client/components/tinymce/i18n.js [hunk 1]
```diff
@@ -5,6 +5,7 @@ const i18n = require( 'i18n-calypso' );
 
 /**
  * @see wp_mce_translation() in src/wp-includes/class-wp-editor.php from WordPress
+ * In short, TinyMCE uses these strings to translate it's internal strings
```
Comment (yoavf) [inline client/components/tinymce/i18n.js]: s/it's/its

File: client/components/tinymce/plugins/wpcom/plugin.js [hunk 2]
```diff
@@ -134,39 +135,39 @@ function wpcomPlugin( editor ) {
...
-		tooltip: 'Insert Read More tag',
+		tooltip: translate( 'Insert Read More tag' ),
 		onclick: function() {
 			editor.execCommand( 'WP_More', 'more' );
 		}
 	} );
 
 	editor.addButton( 'wp_page', {
-		tooltip: 'Page break',
+		tooltip: translate(  'Page break' ),
```
Comment (yoavf) [inline client/components/tinymce/plugins/wpcom/plugin.js]: double space

File: client/components/tinymce/plugins/wpcom/plugin.js [hunk 3]
```diff
@@ -134,39 +135,39 @@ function wpcomPlugin( editor ) {
...
 		onclick: function() {
 			editor.execCommand( 'WP_More', 'nextpage' );
 		}
 	} );
 
 	editor.addButton( 'wp_help', {
-		tooltip: 'Keyboard Shortcuts',
+		tooltip: translate(  'Keyboard Shortcuts' ),
```
Comment (yoavf) [inline client/components/tinymce/plugins/wpcom/plugin.js]: double space

File: client/components/tinymce/plugins/wpcom/plugin.js [hunk 4]
```diff
@@ -32,7 +32,7 @@ function wpcomPlugin( editor ) {
 
 		if ( event.content ) {
 			if ( event.content.indexOf( '<!--more' ) !== -1 ) {
-				title = __( 'Read more...' );
```
Comment (aduth) [inline client/components/tinymce/plugins/wpcom/plugin.js]: This should be removed from `client/components/tinymce/i18n` if we're switching to `i18n-calypso`.

File: client/state/ui/editor/contact-form/constants.js [hunk 5]
```diff
@@ -11,15 +13,29 @@ export const CONTACT_FORM_FIELD_TYPES = {
...
 export const CONTACT_FORM_DEFAULT = {
 	fields: [
-		{ label: 'Name', type: CONTACT_FORM_FIELD_TYPES.name, required: true },
-		{ label: 'Email', type: CONTACT_FORM_FIELD_TYPES.email, required: true },
-		{ label: 'Website', type: CONTACT_FORM_FIELD_TYPES.website },
-		{ label: 'Comment', type: CONTACT_FORM_FIELD_TYPES.textarea, required: true }
+		{
+			label: translate( 'Name' ),
+			type: CONTACT_FORM_FIELD_TYPES.name,
+			required: true },
```
Comment (aduth) [inline client/state/ui/editor/contact-form/constants.js]: Closing `},` should be on following line.

File: client/state/ui/editor/contact-form/constants.js [hunk 6]
```diff
@@ -1,3 +1,5 @@
+import { translate } from 'i18n-calypso';
```
Comment (aduth) [inline client/state/ui/editor/contact-form/constants.js]: Can we add `External dependencies` docblock here?

File: client/components/tinymce/plugins/wpcom/plugin.js (hunk 4 above)
Comment (deBhal) [inline client/components/tinymce/plugins/wpcom/plugin.js]: That's a great point, and I've pulled 'Read more' out of i18n.js.

While we're on the topic, I'd like to check that using `i18n-calypso` makes sense from the perspective of someone with more investment in TinyMCE. `i18n-calypso` seems easier to me, but  I'm not sure what our reasons are/were for including `i18n.js`, and I wouldn't want to unilaterally reverse a thought out decision.

**Comment by deBhal** [comment]
Wow, the tinymce wpcom plugin has eslint disabled :( [line 19](https://github.com/Automattic/wp-calypso/blob/bac44c504f95452360998438f5c662862f5a562e/client/components/tinymce/plugins/wpcom/plugin.js#L19).
> /* eslint-disable */

File: client/state/ui/editor/contact-form/constants.js (hunk 6 above)
Comment (deBhal) [inline client/state/ui/editor/contact-form/constants.js]: 👍

**Comment by deBhal** [comment]
Looks like github's new review tool has nixed the automatic hiding of changed code, which is a shame, but I've fixed all the feedback, and a couple of other style issues that eslint reported once I realized that it was being silenced.

I started fixing the other style issues in `tinymce/plugins/wpcom/plugin.js` before I realized that we've adapted it from .org code.  I've got the branch locally, but I don't know if it makes sense to finish and push it.  How often do we merge in upstream changes to this file?  Is complying with the coding standard going to do more harm than good?

File: client/state/ui/editor/contact-form/constants.js (hunk 5 above)
Comment (deBhal) [inline client/state/ui/editor/contact-form/constants.js]: Done.

File: client/components/tinymce/plugins/wpcom/plugin.js (hunk 3 above)
Comment (deBhal) [inline client/components/tinymce/plugins/wpcom/plugin.js]: Fixed

File: client/components/tinymce/i18n.js (hunk 1 above)
Comment (deBhal) [inline client/components/tinymce/i18n.js]: Fixed

File: client/components/tinymce/plugins/wpcom/plugin.js (hunk 4 above)
Comment (aduth) [inline client/components/tinymce/plugins/wpcom/plugin.js]: >While we're on the topic, I'd like to check that using `i18n-calypso` makes sense from the perspective of someone with more investment in TinyMCE. `i18n-calypso` seems easier to me, but  I'm not sure what our reasons are/were for including `i18n.js`, and I wouldn't want to unilaterally reverse a thought out decision.

Related: 8742-gh-calypso-pre-oss

My memory is fuzzy, so I'm not exactly sure why we chose to create the separate `i18n.js` file instead of calling on `i18n-calypso` directly. One possible explanation is that it could simplify any upstream WordPress patches or plugins we'd want to make? I dunno, more I look at it, more it seems we should remove `i18n.js` altogether since it adds complexity to the `<TinyMCE />` component too (separate language initialization, workarounds to avoid requesting a localization file).

**Comment by aduth** [comment]
>Wow, the tinymce wpcom plugin has eslint disabled :( [line 19](https://github.com/Automattic/wp-calypso/blob/bac44c504f95452360998438f5c662862f5a562e/client/components/tinymce/plugins/wpcom/plugin.js#L19).

Yeah, I believe this was because we'd forked the plugin from WordPress core, and that it'd become a pain to continue keeping formatting in sync if we were to continue bringing in changes.

File: client/components/tinymce/plugins/wpcom/plugin.js (hunk 2 above)
Comment (deBhal) [inline client/components/tinymce/plugins/wpcom/plugin.js]: Fixed

**Comment by deBhal** [comment]
That makes sense.  I'll kill my branch with the style fixes.

As for this PR, I've fixed all the suggestions.  Good to merge?

**Comment by aduth** [comment]
LGTM 👍
