### PR TITLE
Checkout: Add loading state

### LINKED ISSUE #2353: Checkout: add progress indicator while payment is processed
Steps to reproduce:
1. Go to https://wordpress.com/ > My Sites > Plan
2. Click an "Upgrade now" button
3. Enter payment information or use credits to make a purchase
4. Watch carefully how purchase progress is indicated

<strong>Result:</strong> when checking out we display a "Submitting payment" message and the button text changes to "Completing you purchase," but both are fixed text and not a visual indication that the payment is still processing:

screen shot 2016-01-11 at mon jan 11 6 12 39 pm

/hat tip @kriskarkoski for the original report

Comment from @mikeshelton1503

> Ok here's a concept to really clean up the purchase processing experience. Here's what I think we should do:
> - Remove the blue notice at the top of the screen. It's pointless.
> - Add a transparent overlay (rgba 0,0,0,0.9) over the payment details portion of the screen once the pay button has been clicked/tapped.
> - Add a progress indicator along with the copy "Processing Payment" while the payment is processing.
> - Once the payment has been accepted, replace progress indicator with a checkmark icon and change the copy to "Purchase Complete".
> - After the "Purchase Complete" message displays for 1-2 seconds, fade out the checkout and fade in the Thank You page.

Comment from @breezyskies

> This looks really good Mike. 
> 
> In general we are avoiding spinners in Calypso, but I think this is a place where it makes sense:
> - The payment processing takes much longer than almost all of our other form submissions (this can be improved in itself, but it's still going to be a small wait compared to a normal form being saved).
> - Skeletons don't make sense here. There's no content loading on this page, and we shouldn't take them to the next step until we know the payment went through (i.e. there are no errors on this page to show).
> - The lack of animation in the current version of this form submission makes it seem like something got "stuck" when there's a wait -- the spinner at least gives a perception that something is happening behind the scenes (and as you mentioned, it could also be a progress indicator instead of just a spinner). 
> 
> The fade in to the thank you page is also much less abrupt in a situation where it really matters (during sensitive payment flows).

Comment from @mikeshelton1503

> Well said. Yes, ideally it will be a progress indicator that shows accurate progress (the prototyping software I used made it difficult to show a true progress indicator so ignore that).

Related: https://github.com/Automattic/wp-calypso/issues/221

### PR DESCRIPTION
**Pull request by scruffian**
This pull request fixes #2353 by adding a progress bar to the checkout form. This was an issue that was brought up in several usability tests for /domains.
 
checkout

The state of the progress bar is entirely artificial, which is not an ideal solution, but the perception of the users should be that their transaction is progressing.

#### Testing instructions
  
1. Run `git checkout add/checkout-loading-state` and start your server, or open a [live branch](https://delphin.live/?branch=add/checkout-loading-state)
2. Open the Calypso and add a plan to the cart
3. Make a payment and check that instead of the "Submitting payment" notice you see a progress bar
  
#### Reviews
  
- [x] Code
- [x] Product

@Automattic/sdev-feed

### CODE REVIEW

File: client/my-sites/upgrades/checkout/credit-card-payment-box.jsx [hunk 1]
```diff
@@ -33,17 +90,60 @@ var CreditCardPaymentBox = React.createClass( {
 		this.props.onToggle( 'paypal' );
 	},
 
-	content: function() {
-		var cart = this.props.cart;
+	progressBar: function() {
+		return (
+			<div className="credit-card-payment-box__progress-bar">
+				{ this.translate( 'Processing payment…' ) }
```
Comment (a8ci18n) [inline client/my-sites/upgrades/checkout/credit-card-payment-box.jsx]: Hi! I've found a possible matching string that has already been translated **37** times:
`translate( 'Error processing payment' )` *ES Score: 9*
See 1 additional suggestion in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/add/checkout-loading-state)

Help me improve these suggestions: react with :thumbsdown: if the suggestion doesn't make any sense, or with :thumbsup: if it's a particularly good one (even if not implemented).

File: client/my-sites/upgrades/checkout/style.scss [hunk 2]
```diff
@@ -926,3 +926,10 @@
 		transform: translateZ(0) scale(1);
 	}
 }
+
+.credit-card-payment-box__progress-bar {
+	color: grey;
```
Comment (drw158) [inline client/my-sites/upgrades/checkout/style.scss]: This should be either $gray or $gray-text-min. $gray-text-min will make the text an accessible contrast.

**Comment by mikeshelton1503** [comment]
@scruffian Thanks for  jumping on this. A much needed fix!

There are some issues when a processing error occurs.

screen shot 2017-03-27 at 1 03 25 pm

The processing animation should stop and disappear when an error occurs. As discussed in Slack it'd be ideal to have the processing animation an the error be part of the same feedback system but that's for a later iteration.

**Comment by scruffian** [comment]
@mikeshelton1503 thanks for catching that. I have fixed the problem, so this is ready for another review.

**Comment by mikeshelton1503** [comment]
@scruffian This looks good. I confirme that issue has been resolved.

I also made a small design tweak to small screens:

Before | After
---------- | ----------
image | image

The only other thing I'm wondering about is whether we should have a "cancel" action. The previous floating notice did allow you to cancel the transaction by clicking the "X" (I think, right?).

**Comment by scruffian** [comment]
> The previous floating notice did allow you to cancel the transaction by clicking the "X" (I think, right?).

No, the X just closed the notice but it didn't cancel the transaction...

**Comment by mikeshelton1503** [comment]
Product 👍

File: client/my-sites/upgrades/checkout/credit-card-payment-box.jsx [hunk 3]
```diff
@@ -12,17 +13,69 @@ var PayButton = require( './pay-button' ),
...
+			this.timer = setInterval( this.tick, 100 );
+		}
+	},
+
+	componentWillUnmount: function() {
+		clearInterval( this.timer );
+	},
+
+	tick: function() {
+		const elasped = this.state.elapsed + 1 / 200 * ( 100 - this.state.elapsed );
```
Comment (drewblaisdell) [inline client/my-sites/upgrades/checkout/credit-card-payment-box.jsx]: I think a comment like `// increase the progress bar by 0.5% of the remaining progress` or something might be helpful here for future readers.

File: client/my-sites/upgrades/checkout/credit-card-payment-box.jsx [hunk 4]
```diff
@@ -12,17 +13,69 @@ var PayButton = require( './pay-button' ),
...
+		this.setState( {
+			elapsed: elasped
```
Comment (drewblaisdell) [inline client/my-sites/upgrades/checkout/credit-card-payment-box.jsx]: `elapsed` makes me think that this would contain a value that has something to do with time, but it contains a percentage representing the width of the progress bar. What do you think about:

- Renaming this to `progress`.
- Removing the existing `progress` method and calling `Math.round` in `render()`?

File: client/my-sites/upgrades/checkout/credit-card-payment-box.jsx [hunk 5]
```diff
@@ -12,17 +13,69 @@ var PayButton = require( './pay-button' ),
...
 	getInitialState: function() {
-		return { previousCart: null };
+		return {
+			elapsed: 0,
+			previousCart: null
+		};
+	},
+
+	componentWillReceiveProps: function( nextProps ) {
+		if ( nextProps.transactionStep && this.submitting( nextProps.transactionStep ) ) {
```
Comment (drewblaisdell) [inline client/my-sites/upgrades/checkout/credit-card-payment-box.jsx]: It probably doesn't affect the behavior of `this.timer`, but I believe that we will create the timer unnecessarily here, as this will fire multiple times for values of `nextProps.transactionStep` that return true from `this.submitting`. We can prevent this by comparing the existing `transactionStep` to the next one.

**Comment by drewblaisdell** [comment]
I added a couple commits to address my notes. If you're cool with those changes, the code :+1:.

File: client/my-sites/upgrades/checkout/credit-card-payment-box.jsx (hunk 1 above)
Comment (yoavf) [inline client/my-sites/upgrades/checkout/credit-card-payment-box.jsx]: The other suggestion is pretty good: `Processing your payment...`

**Comment by scruffian** [comment]
Thanks for the fixed @drewblaisdell, LGTM
