### PR TITLE
Purchases: Fix styling of chat button in auto-renwal dialog

### LINKED ISSUE #78379: Domain auto renewal styling overflow
### Quick summary

When a domain is purchased, and a user clicks to disable renewal, the popup has some styling/overflow issues

### Steps to reproduce

1. Purchase a domain
2. Once it's activated, disable renewal

### What you expected to happen

You'll be greeted by this popup , where `need help` is over the CTA buttons

Monosnap Domains ‹ WC Pay Safe Mode Test — WordPress com 2023-06-15 13-09-49

### What actually happened

...

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by klimeryk**
Fixes #78379

Regression possibly introduced in #78173.

## Proposed Changes

* Ensure the `PrecancellationChatButton` has the correct, inline styles applied to it.

## Testing Instructions

The easiest is to hack the `auto-renew-disabling-dialog` like this:

```
diff --git a/client/me/purchases/manage-purchase/auto-renew-toggle/auto-renew-disabling-dialog/index.jsx b/client/me/purchases/manage-purchase/auto-renew-toggle/auto-renew-disabling-dialog/index.jsx
index 29f7f1bc61..c323106982 100644
--- a/client/me/purchases/manage-purchase/auto-renew-toggle/auto-renew-disabling-dialog/index.jsx
+++ b/client/me/purchases/manage-purchase/auto-renew-toggle/auto-renew-disabling-dialog/index.jsx
@@ -293,6 +293,7 @@ class AutoRenewDisablingDialog extends Component {
        render() {
                switch ( this.state.dialogType ) {
                        case DIALOG.GENERAL:
+                               return this.renderSurvey();
                                return this.renderGeneralDialog();
                        case DIALOG.ATOMIC:
                                return this.renderAtomicFollowUpDialog();
```

That way click on the `ON` link here on a purchase with auto-renew enabled will trigger the dialog:

Screenshot 2023-06-19 at 15 17 40

The chat button should display properly in the dialog:

Screenshot 2023-06-19 at 15 17 12

Make sure to test the cases from #78173 as well.

### CODE REVIEW

File: client/components/chat-button/index.tsx [hunk 1]
```diff
@@ -6,21 +6,18 @@ import { useI18n } from '@wordpress/react-i18n';
 import classnames from 'classnames';
 import type { MessagingGroup } from '@automattic/help-center/src/hooks/use-messaging-availability';
 import type { FC } from 'react';
-import './style.scss';
```
Comment (klimeryk) [inline client/components/chat-button/index.tsx:9]: This is unrelated to the issue at hand, I'm just removing these styles as they are useless since https://github.com/Automattic/wp-calypso/pull/78173 and not working with this component anyway.

**Review by AtrumGeost — APPROVED** [review]
Looking good!
I ran a test with the auto-renew dialog and with the cases mentioned in #78173. All worked as expected 👍
