### PR TITLE
Launchpad: Find the best domain to use for iFrame and for sidebar domain container

### LINKED ISSUE #68488: LaunchPad - support showing chosen custom domains
Identified via p2 - pbAok1-3fx-p2#comment-5543

The launchpad's domains section does not show the custom domains chosen, but only the free wordpress.com versions. We need to ensure this properly shows custom domains. The issue right now is that the custom domain is still pending, not entirely set up and not registered as the primary domain for the site yet. This takes time, and we need to find a way to make the domain preview window reflect the domain chosen by the user while this is in process.

Screen Shot 2022-09-30 at 9 00 15 AM

### To reproduce
* Create a newsletter or link-in-bio site
* Pick a plan and create a custom domain
* visit the launchpad and notice the free wordpress domain is being shown instead of the custom.

### LINKED ISSUE #68519: LaunchPad - Site preview to handle insecure domains
There is a timeframe in the domain transfer process where a custom domain is set as the primary domain but not fully resolved to be https. This can take a few minutes to a couple hours depending, and is longer with certain types of domains such as .blog.

When in this state, if the we load the launchpad there is an error when the insecure url loads in the preview. On chrome the entire launchpad turns into this:

image

We need to find a way to prevent this from happening.

### PR DESCRIPTION
**Pull request by agrullon95**
#### Proposed Changes

We want to find the best domain to use for the iFrame and for the sidebar domain container.

For the iFrame the best domain will always be the `.wordpress.com` because it will have a SSL certificate at all times so it won't cause an error when trying to load the iFrame (as opposed to trying to load a recently purchase domain that does have not have SSL certificates ready thus making it insecure). If the `.wordpress.com` domain doesn't exist for some reason (technically very unlikely but just in case), as a safety fallback we are choosing the most recently registered domain name for that site.

For the sidebar domain container, the best domain will always be the most recently registered domain name for that site (the custom domain when the user has purchased a custom domain) because that will be the domain that the user would expect to see. If there's no custom domain we are choosing the `.wordpress.com` domain

#### Testing Instructions

Custom domains:

1. Start a new newsletter flow or link-in-bio flow and create a site with a custom domain
2. Once you arrive at the Launchpad screen you should see that in the sidebar domain container we see the custom domain (even though you may have the `.wordpress.com` domain in the `siteSlug` param)
3. The iFrame should load correctly because it will use the `.wordpress.com` domain instead of a custom domain (which will most likely be lacking an SSL cert at this point)
4. Start a new newsletter flow or link-in-bio flow WITHOUT creating a custom domain
5. Once you arrive at the Launchpad screen you should see that in the sidebar domain container we see the `.wordpress.com` domain since no custom domain is found
6. Ensure links that navigate away from the Launchpad are redirecting to the correct pages (`Go to Admin` and checklist items)

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Fixes #68519 
Fixes #68488

### CODE REVIEW

File: client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx [hunk 1]
```diff
@@ -9,11 +13,47 @@ type StepContentProps = {
 	goToStep?: NavigationControls[ 'goToStep' ];
 };
 
-const StepContent = ( { siteSlug, submit, goNext, goToStep }: StepContentProps ) => (
-	<div className="launchpad__content">
-		<Sidebar siteSlug={ siteSlug } submit={ submit } goNext={ goNext } goToStep={ goToStep } />
-		<LaunchpadSitePreview siteSlug={ siteSlug } />
-	</div>
-);
+function sortByRegistrationDateCompareFunction(
```
Comment (jeyip) [inline client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx]: `NB`: I think we can shorten this name to `sortByRegistrationDate`. Sorting already implies comparison, and we can assume it's a function based on surrounding syntax

File: client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx [hunk 2]
```diff
@@ -9,11 +13,47 @@ type StepContentProps = {
...
+	firstDomainObject: ResponseDomain,
+	secondDomainObject: ResponseDomain
+) {
+	if ( firstDomainObject.registrationDate > secondDomainObject.registrationDate ) {
```
Comment (jeyip) [inline client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx]: `NB`: Totally an opinion, but we can probably clean up the names to make the function easier to read. Something like this:

```javascript
function sortByRegistrationDate(
	domainObjectA: ResponseDomain,
	domainObjectB: ResponseDomain
) {
	const registrationDateA = domainObjectA.registrationDate;
	const registrationDateB = domainObjectB.registrationDate;

	if ( registrationDateA > registrationDateB ) {
		return -1;
	} else if ( registrationDateA < registrationDateB ) {
		return 1;
	}
	return 1;
}
```

File: client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx [hunk 3]
```diff
@@ -9,11 +13,47 @@ type StepContentProps = {
...
+		.filter( ( domain ) => ! domain.isWPCOMDomain )
+		.sort( sortByRegistrationDateCompareFunction );
+
+	const wpcomDomains = domains.filter( ( domain ) => domain.isWPCOMDomain );
+
+	const sidebarURL = nonWpcomDomains?.length
+		? nonWpcomDomains[ 0 ]?.domain
+		: wpcomDomains[ 0 ]?.domain;
+
+	const iFrameURL = wpcomDomains.length ? wpcomDomains[ 0 ]?.domain : nonWpcomDomains[ 0 ]?.domain;
```
Comment (jeyip) [inline client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx:41]: From the way things are coded with the null propagation operators, it appears as if iframeURL and sidebarURL may return `undefined`? Should we have a graceful fallback for either case?

File: client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx (hunk 1 above)
Comment (sharpirate) [reply client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx]: I agree, updated the PR

File: client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx (hunk 2 above)
Comment (sharpirate) [reply client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx]: I agree, updated the PR

File: client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx (hunk 3 above)
Comment (sharpirate) [reply client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx:41]: Yeah, we were discussing that with Anthony but we thought that this would be more of a business/design decision because we need to know what will happen to the UI when there's no iFrame/sidebar domain... For example we might need to add a loading state for the sidebar domain container because it just stays empty while the domain is being fetched

Comment (sharpirate) [reply client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx:41]: And since we are assuming both of those could not exist we need to know what will happen to the UI. But if this is such a unlikely scenario I guess we can just conditionally render the sidebar domain container and the iFrame preview to only render if there's a domain (which should be always the case)

Comment (jeyip) [reply client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx:41]: > we need to know what will happen to the UI when there's no iFrame/sidebar domain... For example we might need to add a loading state for the sidebar domain container because it just stays empty while the domain is being fetched

Wondering if @nuriapenya has thoughts

File: client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx [hunk 4]
```diff
@@ -9,11 +13,47 @@ type StepContentProps = {
...
+		.filter( ( domain ) => ! domain.isWPCOMDomain )
+		.sort( sortByRegistrationDate );
+
+	const wpcomDomains = domains.filter( ( domain ) => domain.isWPCOMDomain );
+
+	const sidebarURL = nonWpcomDomains?.length
+		? nonWpcomDomains[ 0 ]?.domain
+		: wpcomDomains[ 0 ]?.domain;
+
+	const iFrameURL = wpcomDomains.length ? wpcomDomains[ 0 ]?.domain : nonWpcomDomains[ 0 ]?.domain;
```
Comment (jeyip) [inline client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx:41]: I'm wondering if there's ever a situation where we don't have access to a wpcom domain from Calypso 🤔

File: client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx [hunk 5]
```diff
@@ -9,11 +13,47 @@ type StepContentProps = {
 	goToStep?: NavigationControls[ 'goToStep' ];
 };
 
-const StepContent = ( { siteSlug, submit, goNext, goToStep }: StepContentProps ) => (
-	<div className="launchpad__content">
-		<Sidebar siteSlug={ siteSlug } submit={ submit } goNext={ goNext } goToStep={ goToStep } />
-		<LaunchpadSitePreview siteSlug={ siteSlug } />
-	</div>
-);
+function sortByRegistrationDate( domainObjectA: ResponseDomain, domainObjectB: ResponseDomain ) {
```
Comment (edanzer) [inline client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx:16]: To confirm, the idea here is that the most recently registered domain is the one we want. So we fetch all domains a user has registered, and pick the most recent. Seems likely this will work.

I guess there's no way to directly get the domain that was registered during the current onboarding flow? I might have thought that was saved somehow during the earlier onboarding screens, and then accessible to us.

File: client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx [hunk 6]
```diff
@@ -9,11 +13,47 @@ type StepContentProps = {
...
+	const registrationDateA = domainObjectA.registrationDate;
+	const registrationDateB = domainObjectB.registrationDate;
+
+	if ( registrationDateA > registrationDateB ) {
+		return -1;
+	} else if ( registrationDateA < registrationDateB ) {
```
Comment (edanzer) [inline client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx]: Is this else if needed? Seems like if the first condition is false, we always return 1, so you could remove this else if and just go with the final return 1; statement. 

Not sure if this would be clearer, but we could (I think) simplify body of function to something like:
`return domainObjectA.registrationDate > domainObjectb.registrationDate ? -1 : 1;`

File: client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx [hunk 7]
```diff
@@ -9,11 +13,47 @@ type StepContentProps = {
...
+
+	const domains = allDomains.map( createSiteDomainObject );
+
+	// Filter custom domains and sort by registration date.
+	// We want the first domain object to be the most recently registered domain
+	const nonWpcomDomains = domains
+		.filter( ( domain ) => ! domain.isWPCOMDomain )
+		.sort( sortByRegistrationDate );
+
+	const wpcomDomains = domains.filter( ( domain ) => domain.isWPCOMDomain );
```
Comment (edanzer) [inline client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx:35]: Would this also need to be sorted (like nonWpcomdomains) to ensure you're getting the most recent *.wordpress.com domain?

File: client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx [hunk 8]
```diff
@@ -9,11 +13,47 @@ type StepContentProps = {
...
+
+	const sidebarURL = nonWpcomDomains?.length
+		? nonWpcomDomains[ 0 ]?.domain
+		: wpcomDomains[ 0 ]?.domain;
+
+	const iFrameURL = wpcomDomains.length ? wpcomDomains[ 0 ]?.domain : nonWpcomDomains[ 0 ]?.domain;
+
+	return (
+		<div className="launchpad__content">
+			<Sidebar siteSlug={ sidebarURL } submit={ submit } goNext={ goNext } goToStep={ goToStep } />
```
Comment (Addison-Stavlo) [inline client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx]: Using `sidebarURL` for the `siteSlug` prop of the entire sidebar may have some side-effects, such as what @edanzer noted in slack. p1665514707670979/1665513799.968999-slack-CHN6J22MP

It seems the Sidebar component still uses this siteSlug for other things than just the domain previewed to the user above the checklist, such as the URL for writing new posts.

File: client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx (hunk 7 above)
Comment (edanzer) [reply client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx:35]: Also wondering... would it be worth reducing the number of steps here by using something [lodash partition](https://lodash.com/docs/4.17.15#partition) to create the wp and non-wp domain lists at once? Can see it in use in Calypso [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/state/selectors/get-sites.js).

No strong feelings on my side on this though.

File: client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx (hunk 8 above)
Comment (agrullon95) [reply client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx]: I will revert the `siteSlug` prop changes and add an additional prop for the sidebar URL.

File: client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx (hunk 5 above)
Comment (agrullon95) [reply client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx:16]: > To confirm, the idea here is that the most recently registered domain is the one we want. So we fetch all domains a user has registered, and pick the most recent. Seems likely this will work.

Correct. If the user purchased a domain, then we will use the most recently registered domain.

> I guess there's no way to directly get the domain that was registered during the current onboarding flow? I might have thought that was saved somehow during the earlier onboarding screens, and then accessible to us.

There is a way to pass the domain through the onboarding screens, but that won't solve the site preview issue because we will not be able to load the preview based on that URL/slug if the newly purchased custom domain is not completely resolved (SSL certificates). It would also require more changes across the codebase (change stepper flow redirection URLs and checkout flow redirection if the user cancels out of the checkout process). We figured it would be best to use the domain endpoint to fetch the wp & non wp domains to solve the site preview iframe loading issue and at the same time fix the sidebar URL using the same response data.

File: client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx (hunk 7 above)
Comment (agrullon95) [reply client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx:35]: > Would this also need to be sorted (like nonWpcomdomains) to ensure you're getting the most recent *.wordpress.com domain?

Based on the /domains API, we are only receiving a single WP domain in the response.
p1665517041555449/1665513799.968999-slack-CHN6J22MP

File: client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx (hunk 3 above)
Comment (agrullon95) [reply client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/step-content.tsx:41]: We discussed this during our team meeting and decided it isn't worth looking into as much right now since it's not a likely situation if the user is going through the normal flow.

**Review by sharpirate — APPROVED** [review]
Changes look good. I've just retested this:

✅ Sidebar shows the custom domain in the URL preview
✅ iFrame is loading correctly
✅ Clicking on "Write your first post" no longer shows the "Choose a site" screen

**Comment by edanzer** [comment]
I've tested again following recent changes, and this still tests correctly for me.
 - [x] I see custom domain in the sidebar if one has been selected, otherwise *.wordpress.com domain
 - [x] Launchpad preview loads correctly with and without custom domain
 - [x] Launchpad links work correctly with and without custom domain

**Review by edanzer — APPROVED** [review]

File: client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/index.tsx [hunk 9]
```diff
@@ -15,10 +16,16 @@ import { setStore } from 'calypso/state/redux-store';
 import Launchpad from '../index';
 import { buildSiteDetails, defaultSiteDetails } from './lib/fixtures';
 
+const mockUseQuery = () => () => ( { isLoading: true, data: null } );
```
Comment (jeyip) [inline client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/index.tsx]: Two things:

- Could we inline this implementation inside the `jest.mock` invocation? From what I can tell, it looks like we don't need to call `.mockImplementation` on L76.

```javascript
jest.mock( 'react-query', () => ( {
	useQuery: () => ( { isLoading: true, data: null } ),
} ) );
```

- Totally non-blocking, but mocking in this fashion replaces the _entire_ `react-query` library for the duration of this test suite. To only mock part of it, we would write the function like so:

```javascript
jest.mock( 'react-query', () => {
  const actualReactQuery = jest.requireActual('react-query')
  return {
    ...actualReactQuery
	useQuery: () => ( { isLoading: true, data: null } ),
  }
) );
```

File: client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/sidebar.tsx [hunk 10]
```diff
@@ -10,11 +10,13 @@ import { MemoryRouter } from 'react-router-dom';
 import Sidebar from '../sidebar';
 import { defaultSiteDetails, buildSiteDetails } from './lib/fixtures';
 
+const sidebarURL = 'https://testlinkinbio.wordpress.com';
```
Comment (jeyip) [inline client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/sidebar.tsx]: Since the url displayed in the browser is no longer derived from siteSlug, but sidebarURL instead, could we update the `displays the current site url` test to reflect the new expectations?

Comment (agrullon95) [reply client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/sidebar.tsx]: The test case handles the changes from siteSlug to sidebarURL. The result is the same since both variables were returning a URL.

image

Comment (jeyip) [reply client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/sidebar.tsx]: > The result is the same since both variables were returning a URL.

siteSlug and sidebarURL might return the same value, but the expectations in the test are misleading because, ultimately, the url that's displayed in the sidebar depends on the sidebarURL prop, not siteSlug.

Maybe I'm missing something, but we're currently creating expectations that reference elements of the siteSlug ( Ex. L62 ), not the sidebarURL

Comment (jeyip) [reply client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/sidebar.tsx]: I haven't tested this, but the new test would look something like the following

```javascript
it( 'displays the current site url', () => {
    renderSidebar( props );

    // For htttps://test.domain.com, returns test.domain.com
    const hostname = new URL(sidebarURL).hostname;
    const renderedUrl = screen.getByText( ( content ) => content.includes( hostname ) );
    expect( renderedUrl ).toBeVisible();
} );
```

File: client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/index.tsx [hunk 11]
```diff
@@ -16,14 +15,24 @@ import { setStore } from 'calypso/state/redux-store';
...
 
-const mockUseQuery = () => () => ( { isLoading: true, data: null } );
-
 jest.mock( '../launchpad-site-preview', () => () => {
 	return <div></div>;
 } );
 
 jest.mock( 'react-query', () => ( {
-	useQuery: jest.fn(),
+	useQuery: () => ( { isLoading: true, data: null } ),
```
Comment (jeyip) [inline client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/index.tsx]: `NB`: Do we still need to mock this if we're mocking `useGetDomainsQuery`?

**Review by jeyip — APPROVED** [review]

File: client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/index.tsx (hunk 11 above)
Comment (agrullon95) [reply client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/test/index.tsx]: Good catch. Its not needed anymore.
