### PR TITLE
Playwright: additional sidebar reliability tweaks

### LINKED ISSUE #54614: Playwright: flaky behavior when clicking sidebar menu items as Atomic user.
### Details

Logs:
```
elementHandle.click: Element is not attached to the DOM
=========================== logs ===========================
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
Error:
at Object.captureStackTrace (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/utils/stackTrace.js:50:19)
at Connection.sendMessageToServer (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/connection.js:65:48)
at Proxy.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/channelOwner.js:64:61)
at /home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/elementHandle.js:142:34
at ElementHandle._wrapApiCall (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/channelOwner.js:77:34)
at ElementHandle.click (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/elementHandle.js:141:21)
at SidebarComponent._click (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/sidebar-component.ts:147:23)
at SidebarComponent.gotoMenu (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/sidebar-component.ts:84:4)
at Object.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-media__edit-spec.js:31:5)
```

Playwright logs:
```
2021-07-15T14:34:33.444Z 487 api info: => browserContext.newPage started
2021-07-15T14:34:33.540Z 487 api info: <= browserContext.newPage succeeded
2021-07-15T14:34:33.541Z 487 api info: => page.goto started
2021-07-15T14:34:34.290Z 487 api info: <= page.goto succeeded
2021-07-15T14:34:34.328Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:34.569Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:34.570Z 487 api info: => page.waitForLoadState started
2021-07-15T14:34:35.421Z 487 api info: <= page.waitForLoadState succeeded
2021-07-15T14:34:35.421Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:35.436Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:35.437Z 487 api info: => elementHandle.waitForElementState started
2021-07-15T14:34:35.460Z 487 api info: <= elementHandle.waitForElementState succeeded
2021-07-15T14:34:35.461Z 487 api info: => page.$ started
2021-07-15T14:34:35.464Z 487 api info: <= page.$ succeeded
2021-07-15T14:34:35.464Z 487 api info: => page.fill started
2021-07-15T14:34:35.487Z 487 api info: <= page.fill succeeded
2021-07-15T14:34:35.506Z 487 api info: => page.fill started
2021-07-15T14:34:35.686Z 487 api info: <= page.fill succeeded
2021-07-15T14:34:35.703Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:40.535Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:40.539Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:40.839Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:40.840Z 487 api info: => elementHandle.waitForElementState started
2021-07-15T14:34:40.897Z 487 api info: <= elementHandle.waitForElementState succeeded
2021-07-15T14:34:40.899Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:41.009Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:41.010Z 487 api info: => page.evaluate started
2021-07-15T14:34:41.027Z 487 api info: <= page.evaluate succeeded
2021-07-15T14:34:41.027Z 487 api info: => elementHandle.click started
2021-07-15T14:34:41.301Z 487 api info: <= elementHandle.click succeeded
2021-07-15T14:34:41.302Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:41.721Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:41.722Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:42.220Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:42.221Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:42.245Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:42.245Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:42.387Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:42.388Z 487 api info: => elementHandle.getAttribute started
2021-07-15T14:34:42.786Z 487 api info: <= elementHandle.getAttribute succeeded
2021-07-15T14:34:42.786Z 487 api info: => page.click started
2021-07-15T14:34:43.615Z 487 api info: <= page.click succeeded
2021-07-15T14:34:43.615Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:47.641Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:47.642Z 487 api info: => elementHandle.waitForElementState started
2021-07-15T14:34:47.695Z 487 api info: <= elementHandle.waitForElementState succeeded
2021-07-15T14:34:47.696Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:47.712Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:47.713Z 487 api info: => elementHandle.click started
2021-07-15T14:34:47.816Z 487 api info: <= elementHandle.click succeeded
2021-07-15T14:34:47.817Z 487 api info: => page.waitForFunction started
2021-07-15T14:34:47.840Z 487 api info: <= page.waitForFunction succeeded
2021-07-15T14:34:47.842Z 487 api info: => page.click started
2021-07-15T14:34:48.091Z 487 api info: <= page.click succeeded
2021-07-15T14:34:48.091Z 487 api info: => page.click started
2021-07-15T14:34:48.430Z 487 api info: <= page.click succeeded
2021-07-15T14:34:48.432Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:48.735Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:48.736Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:48.776Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:48.777Z 487 api info: => page.click started
2021-07-15T14:34:48.952Z 487 api info: <= page.click succeeded
2021-07-15T14:34:48.952Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:49.000Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:49.000Z 487 api info: => elementHandle.waitForElementState started
2021-07-15T14:34:49.001Z 487 api info: => page.waitForFunction started
2021-07-15T14:34:49.024Z 487 api info: <= page.waitForFunction succeeded
2021-07-15T14:34:49.025Z 487 api info: <= elementHandle.waitForElementState succeeded
2021-07-15T14:34:49.033Z 487 api info: => page.click started
2021-07-15T14:34:49.177Z 487 api info: <= page.click succeeded
2021-07-15T14:34:49.177Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:49.231Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:49.232Z 487 api info: => page.goto started
2021-07-15T14:34:49.607Z 487 api info: <= page.goto succeeded
2021-07-15T14:34:49.609Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:49.653Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:49.656Z 487 api info: => page.waitForLoadState started
2021-07-15T14:34:50.841Z 487 api info: <= page.waitForLoadState succeeded
2021-07-15T14:34:50.842Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:50.866Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:50.866Z 487 api info: => elementHandle.waitForElementState started
2021-07-15T14:34:50.961Z 487 api info: <= elementHandle.waitForElementState succeeded
2021-07-15T14:34:50.961Z 487 api info: => page.$ started
2021-07-15T14:34:51.001Z 487 api info: <= page.$ succeeded
2021-07-15T14:34:51.005Z 487 api info: => page.click started
2021-07-15T14:34:51.295Z 487 api info: <= page.click succeeded
2021-07-15T14:34:51.295Z 487 api info: => page.fill started
2021-07-15T14:34:51.401Z 487 api info: <= page.fill succeeded
2021-07-15T14:34:51.423Z 487 api info: => page.fill started
2021-07-15T14:34:51.638Z 487 api info: <= page.fill succeeded
2021-07-15T14:34:51.647Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:54.937Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:54.937Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:55.154Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:55.154Z 487 api info: => elementHandle.waitForElementState started
2021-07-15T14:34:55.217Z 487 api info: <= elementHandle.waitForElementState succeeded
2021-07-15T14:34:55.218Z 487 api info: => page.waitForSelector started
2021-07-15T14:34:55.265Z 487 api info: <= page.waitForSelector succeeded
2021-07-15T14:34:55.266Z 487 api info: => page.evaluate started
2021-07-15T14:34:55.273Z 487 api info: <= page.evaluate succeeded
2021-07-15T14:34:55.274Z 487 api info: => elementHandle.click started
2021-07-15T14:34:55.450Z 487 api info: <= elementHandle.click failed
2021-07-15T14:34:55.452Z 487 api info: => page.screenshot started
2021-07-15T14:34:55.671Z 487 api info: <= page.screenshot succeeded
2021-07-15T14:34:55.672Z 487 api info: => page.close started
2021-07-15T14:34:55.707Z 487 api info: <= page.close succeeded

```

### Checklist

- [ ]
- [ ]

### Related

_No response_

### PR DESCRIPTION
**Pull request by worldomonation**
#### Changes proposed in this Pull Request

This PR proposes additional reliability tweaks for sidebar interaction.

Key changes:
- check for the `boundingBox` of the Current Site card (at top of the sidebar) to remain stable prior to executing the click action on a sidebar element.

Background details:

After #54666 and #54745 it was hoped that sidebar interaction with (mostly) Atomic sites would be reliable. However, there are still fairly regular intermittent flakiness resulting from inability to reliable click on the menu item. 

I dug deeper and have come to the conclusion that the `_click` method will need to wait for sidebar elements to be stable prior to any clicks occurring. This can be dealt with in one of many ways, all of which have downsides:

- a hardcoded wait
- wait for `networkidle`
- force clicking using `dispatchEvent`

#### Testing instructions

- [ ] run Desktop Playwright E2E task at least 20 times repeatedly and ensure no failure resulting from sidebar interaction.
- [ ] run Mobile Playwright E2E task at least 20 times repeatedly and ensure no failure resulting from sidebar interaction.

Related to #54614

### CODE REVIEW

**Comment by worldomonation** [comment]
@dpasque @WunderBart I am requesting some ideas here.

Background: atomic sidebar continues to be a problem, causing intermittent failures.
I am 95% sure this is due to the sidebar menu items continuing to shift even though the `load` event has fired from Playwright's perspective.

I made some changes to check whether the promotions/upgrade/notification card in the sidebar (image attached) is stable prior to proceeding. Unfortunately I was able to trigger a failure in [Build Number 1031](https://teamcity.a8c.com/buildConfiguration/calypso_RunCalypsoPlaywrightE2eDesktopTests/6494822), so I am back to square one - only took about 15 consecutive runs before the failure occurred.

The simplest solution is to wait for `networkidle` to fire. However, this is unacceptable as on Simple sites the event only fires after 30s whereas on Atomic sites the event fires within 2s. The excessive wait time for Simple sites would make this unworkable.

Approaches that I think should be reconsidered:

- dispatching event to click on element forcibly using `dispatchEvent`.
- a simple timeout.

Here is where I am asking for some ideas: is there a non-timeout way to ensure that all DOM elements in a subtree is loaded, consistent and not moving? Perhaps checking the bounding box repeatedly until it has not moved?

Screen Shot 2021-07-28 at 5 04 09 PM

**Comment by WunderBart** [comment]
> Background: atomic sidebar continues to be a problem, causing intermittent failures.
I am 95% sure this is due to the sidebar menu items continuing to shift even though the load event has fired from Playwright's perspective.

I think the reason that the subitem click is missed might be that we're not waiting for the target submenu to be open, but just for **any** submenu to be open: https://github.com/Automattic/wp-calypso/blob/cec865377bc7e94bb728df7d678c4aa218d46274/packages/calypso-e2e/src/lib/components/sidebar-component.ts#L95
Waiting for a specific submenu should help because **some** submenu is always open (e.g. after logging in, the `My Home` submenu is open), meaning that this check currently lets the execution literally pass through instantly. "But the Playwright's `click` waits for the submenu item to be visible anyway" you might think, but the submenu is actually tricky in this case, because it's revealed instantly on item hover, possibly confusing the `click` position even more:

Screenshot 2021-07-29 at 14 45 48

---

I spent some time trying to rethink the `gotoMenu` method and make it more robust (incl. the fix for the above), and this is what I've come up with:

```js
async navigate( item, subitem ) {
	const linkItemClass = `sidebar__menu-link-text`;
	const expandableItemClass = `sidebar__expandable-title`;
	const linkItemSelector = `.${ linkItemClass }:has-text(${ item })`;
	const expandableItemSelector = `.${ expandableItemClass }:has-text(${ item })`;

	const itemElement = await Promise.race( [
		this.page.waitForSelector( linkItemSelector ),
		this.page.waitForSelector( expandableItemSelector ),
	] );

	const isLinkItem = await itemElement
		.getAttribute( 'class' )
		.then( ( className ) => className.includes( linkItemClass ) );

	if ( isLinkItem ) {
		return await Promise.all( [ this.page.waitForNavigation(), itemElement.click() ] );
	}

	// Begin handling expandable item
	const expandedMenuSelector = `*css=.sidebar__menu.is-toggle-open >> ${ expandableItemSelector }`;
	let expandedMenuElement = await this.page.$( expandedMenuSelector );

	if ( ! expandedMenuElement ) {
		// Click to open item menu if it's not yet expanded. It also triggers navigation event as it
		// redirects to the first subitem page on click.
		await Promise.all( [ this.page.waitForNavigation(), itemElement.click() ] );
	}

	if ( subitem ) {
		expandedMenuElement = await this.page.waitForSelector( expandedMenuSelector );
		const subitemSelector = `.sidebar__menu-link-text:has-text(${ subitem })`;

		await Promise.all( [
			this.page.waitForNavigation(),
			expandedMenuElement.click( subitemSelector ),
		] );
	}
}
```

A few comments on the above:
- Changed name to `navigate` as I think it shows the intent better.
- Added `expanded` state handling and made the `item` prop required, as it improves the overall readability - IMO it's better to always specify the parent of the subitem we want to navigate to, e.g. 
   ```js
   await sidebarComponent.navigate( 'Appearance', 'Themes' )`;
   ```
- Added `navigation` event handlers to each click because, regardless of the type, they all seem to redirect.

What do you think? Sorry for not making the example in TS - I'm not yet that familiar with it.

**Comment by dpasque** [comment]
> is there a non-timeout way to ensure that all DOM elements in a subtree is loaded, consistent and not moving? Perhaps checking the bounding box repeatedly until it has not moved?

So I've spent a long time watching the DOM change in the sidebar on an atomic site, and it seems like this is the order of what happens:

1. The shell of the sidebar gets created: `<div id="secondary" class="layout__secondary" role="navigation">` -- this remains static throughout the entire loading process
2. A first version of the sidebar gets created: `<ul role="presentation" class="sidebar has-regions" data-tip-target="sidebar">` -- this has only the original basic menu items, i.e., everything apart from what comes from plugins. This does _not_ remain static, it is detached and replaced by a new sidebar...
3. The mostly final version of the sidebar gets created. The parent element looks exactly the same (`<ul role="presentation" class="sidebar has-regions" data-tip-target="sidebar">`), but it is a new node that is attached in the DOM to replace the old one.  This final version has all the menus from different plugins.
4. If you have a free domain available, that banner will pop in on the top of the sidebar. This does _not_ detach the parent sidebar, or any of the other elements, from the DOM. They all stay intact! However, they do shift down slightly on the page.

This gives me a few ideas, in order of which I think might be most stable over time:
1. We just do a `waitForSelector` on a sidebar menu item that loads last in atomic sites, like Yoast SEO. This means we would have to have some conditional logic in the sidebar component based on the type of site we're interacting with, but I think that's a fair tradeoff for cleanliness in selectors and stability, etc...
2. We could look for the number of children in the sidebar element. We could do some kind of `$eval` function on `page`, and make sure it either doesn't change on a certain loop, or wait until it is > the number of elements in the starting sidebar. So, in really rough code format...

```typescript
await page.waitForSelector('.sidebar'); // make sure we have the first version
for (let i: number; i < retry amount; i++) {
    const numOfChildren = await page.$eval('.sidebar', sidebar => sidebar.childElementCount);
    if (numOfChildren >= expectedFinalCount) {
         break;
    }
}
```

3.  We could hook onto that shell element and check it's innerHTML on a timed loop until it stops changing

**Comment by dpasque** [comment]
Oh, wait, nevermind, do what Bart said haha 😆 . That's much simpler if that's what is going wrong!!

That would make a lot of sense too, because the whole point of using `page.click()` is that it should be able to handle things getting detached and retrying, so I was kind of surprised this was breaking with your recent changes if it is just the menu items moving around!

**Comment by worldomonation** [comment]
I tried running a stress test with @WunderBart's suggested code:

```
for x in {1..100}; do xvfb-run yarn jest --reporters=jest-teamcity --reporters=default --testNamePattern @parallel --maxWorkers=%E2E_WORKERS% specs/specs-playwright/wp-media__edit-spec.js; done
```

Where the test spec `wp-media__edit-spec.js` was truncated to navigate to to `Media` and ensure the gallery loaded.

It was running quite well for some time (~8min20s) but eventually it encountered the same issue. See the logs here:
https://teamcity.a8c.com/buildConfiguration/calypso_RunCalypsoPlaywrightE2eDesktopTests/6501709?buildTab=log&focusLine=8093&linesState=286#%2Fscreenshots. 

I think the general suggestions made by Bart are applicable for any solution that ends up being used however, especially these:
- Added expanded state handling and made the item prop required, as it improves the overall readability
- Added navigation event handlers to each click because, regardless of the type, they all seem to redirect

I'll give Dan's suggestions a try while incorporating the suggestions by Bart.

**Comment by worldomonation** [comment]
Checking the length of the resulting DOM does not appear to be a solution either, as evidenced by the following log:

```
pw:api waiting for selector ".sidebar > li span:has-text("Media"):visible" to be visible +11ms
  console.log
    length same at 20 === 20

      at Timeout._onTimeout (../../packages/calypso-e2e/src/lib/components/sidebar-component.ts:108:14)
          at runMicrotasks (<anonymous>)

  console.log
    length not same

      at Timeout._onTimeout (../../packages/calypso-e2e/src/lib/components/sidebar-component.ts:111:13)
          at runMicrotasks (<anonymous>)

  pw:api <= page.$$ succeeded +50ms
  pw:api => page.$$ started +22ms
  pw:api   selector resolved to visible <span data-e2e-sidebar="Media" class="sidebar__menu-li…>Media</span> +23ms
  pw:api => page.$$ started +68ms
  console.log
    length not same

      at Timeout._onTimeout (../../packages/calypso-e2e/src/lib/components/sidebar-component.ts:111:13)
          at runMicrotasks (<anonymous>)

  pw:api <= page.$$ succeeded +57ms
  pw:api => page.$$ started +22ms
  pw:api <= page.$$ succeeded +57ms
  pw:api => page.$$ started +20ms
  console.log
    length same at 22 === 22

      at Timeout._onTimeout (../../packages/calypso-e2e/src/lib/components/sidebar-component.ts:108:14)
          at runMicrotasks (<anonymous>)

  console.log
    length not same

      at Timeout._onTimeout (../../packages/calypso-e2e/src/lib/components/sidebar-component.ts:111:13)
          at runMicrotasks (<anonymous>)

  console.log
    length not same

      at Timeout._onTimeout (../../packages/calypso-e2e/src/lib/components/sidebar-component.ts:111:13)
          at runMicrotasks (<anonymous>)

  pw:api <= page.$$ succeeded +49ms
  pw:api <= page.waitForSelector succeeded +27ms
  pw:api => page.evaluate started +1ms
  pw:api => page.$$ started +7ms
  console.log
    length same at 28 === 28

      at Timeout._onTimeout (../../packages/calypso-e2e/src/lib/components/sidebar-component.ts:108:14)
          at runMicrotasks (<anonymous>)
```

I think either the following should be done:

1. a predefined `waitForTimeout`.
2. require in the parameter to `SidebarComponent.gotoMenu` the type of site we're working with, then switch the `waitForLoadState` state based on the param.
3. try waiting for an element that is known to be found in atomic sites with a `waitForSelector` and custom timeout of 3000ms. 

I prefer the 1. due to its simplicity even though I am rather against the use of predefined timeouts. I think it would be better to move the project forward than to bikeshed on this - an additional 250-500ms before interacting with the sidebar would be time well spent, in my opinion.

**Comment by worldomonation** [comment]
I think I have a solution.

In the most recent revision I have used the `boundingBox` method to compare the size of the box, interspersed with an arbitrary delay of 250ms:

```
	private async _waitUntilMenuItemsLoaded(): Promise< void > {
		return await new Promise( async ( resolve, reject ) => {
			let loaded = false;
			while ( ! loaded ) {
				let elementHandle = await this.page.waitForSelector( selectors.currentSite );
				let startingBoundingBox = await elementHandle.boundingBox();
				await new Promise( ( resolve ) => setTimeout( resolve, 250 ) );
				let currentBoundingBox = await elementHandle.boundingBox();
				console.log( startingBoundingBox );
				console.log( currentBoundingBox );
				if ( startingBoundingBox!.height === currentBoundingBox!.height ) {
					loaded = true;
					resolve();
				}
			}
```

I'm sure there's room for improvement syntactically and stylistically, but the important thing is that this survived the 100-iteration loop of:

```
:08:45     [WPCOM] Media: Edit Media: (desktop) @parallel

20:08:45       Edit Image (Simple)

20:08:45         ✓ Log In (3258 ms)

20:08:45         ✓ Navigate to Media (3987 ms)

20:08:45         ✓ See media gallery (356 ms)

20:08:45       Edit Image (Atomic)

20:08:45         ✓ Log In (1801 ms)

20:08:45         ✓ Navigate to Media (3288 ms)

20:08:45         ✓ See media gallery (257 ms)
```

I have some debug messages printing that shows what the bounding box at various points are:

```
    console.log

20:08:45       { x: 0, y: 32, width: 272, height: 56 }

20:08:45   

20:08:45         at ../../packages/calypso-e2e/src/lib/components/sidebar-component.ts:112:13

20:08:45   

20:08:45     console.log

20:08:45       { x: 0, y: 32, width: 272, height: 168 }

20:08:45   

20:08:45         at ../../packages/calypso-e2e/src/lib/components/sidebar-component.ts:113:13

20:08:45       { x: 0, y: 32, width: 272, height: 168 }

20:08:45   

20:08:45         at ../../packages/calypso-e2e/src/lib/components/sidebar-component.ts:112:13

20:08:45   

20:08:45     console.log

20:08:45       { x: 0, y: 32, width: 272, height: 168 }

20:08:45   

20:08:45         at ../../packages/calypso-e2e/src/lib/components/sidebar-component.ts:113:13
```

The only reason why the test runs appear as failed is because the 100-iteration loop takes longer than the maximum allowed time for the job of 20minutes.

Check it out here: [run 1](https://teamcity.a8c.com/buildConfiguration/calypso_RunCalypsoPlaywrightE2eDesktopTests/6503897?focusLine=0) [run 2](https://teamcity.a8c.com/buildConfiguration/calypso_RunCalypsoPlaywrightE2eDesktopTests/6504441?focusLine=0)

File: packages/calypso-e2e/src/lib/components/sidebar-component.ts [hunk 1]
```diff
@@ -64,30 +57,33 @@ export class SidebarComponent extends BaseContainer {
 	 * @param {string} param0.subitem Plaintext representation of the child level heading.
 	 * @returns {Promise<void>} No return value.
 	 */
-	async gotoMenu( { item, subitem }: { item?: string; subitem?: string } ): Promise< void > {
+	async gotoMenu( { item, subitem }: { item: string; subitem?: string } ): Promise< void > {
```
Comment (worldomonation) [inline packages/calypso-e2e/src/lib/components/sidebar-component.ts:60]: I'm still open to changing this method's name to `navigate`.

File: packages/calypso-e2e/src/lib/components/sidebar-component.ts [hunk 2]
```diff
@@ -99,6 +95,41 @@ export class SidebarComponent extends BaseContainer {
...
+	 * 	2. First version of the sidebar gets created and has only the original basic menu items.
+	 * 	3. The mostly final version of the sidebar gets created. The parent element looks exactly the same
+	 * 		but it is a new node that is attached in the DOM to replace the old one. This final version has
+	 * 		all the menus from different plugins.
+	 *	4. Offers and notices are loaded in a banner that pop in on the top of the sidebar. This does not
+	 *		detach the parent sidebar, or any of the other elements, from the DOM. However, they do shift
+	 *		down slightly on the page.
+	 *
+	 * The bounding box of the Current Site card is one of the last elements to stabilize in the loading
+	 * process and its stability is a good indicator of the page stability.
```
Comment (worldomonation) [inline packages/calypso-e2e/src/lib/components/sidebar-component.ts]: I've borrowed and simplified @dpasque 's findings from [this comment](https://github.com/Automattic/wp-calypso/pull/54987#issuecomment-889230498) for the docstring.

**Comment by dpasque** [comment]
Wahoo, hurray for results! 😄 

So, it's hard to argue with results, but wanted to throw a couple things out there as a "devil's advocate" just to be sure. I see a couple things that might potentially be tricky over time...
1. This current implementation couples itself to the "my sites" card on the sidebar menu getting shifted, but that seems like could a) change over time (if we no longer have a free domain), and b) could have the lifecycle change over time such that it is finished updating before the other menu items are
2. It actually may not work when the network is slow and lags, because if the gap between the updates happens to be be longer than the timeout in the loop, we may think we're done updating when we are not.

That being said, there's something to "if it ain't broke, don't fix it" 😆 

But, of the options you mentioned earlier, both...
>require in the parameter to SidebarComponent.gotoMenu the type of site we're working with, then switch the waitForLoadState state based on the param.
>try waiting for an element that is known to be found in atomic sites with a waitForSelector and custom timeout of 3000ms.

... seem like really solid options actually! And they both seem like they would weather the test of time well!

**Comment by worldomonation** [comment]
@dpasque Good points, thanks for raising possible counterpoints.

I still suspect the `boundngBox` approach is quite robust. 
For one of my atomic site I removed the free domain offer and it appears the the boundingBox for the `currentSiteCard` will remain static in that case, so this proposed logic will pass on the first attempt. By the time this logic has waited 250ms, rest of the sidebar would already have been loaded by then, so all this really does is insert 250ms into the execution time.

To be sure, in the 100-iteration loops I ran last night the task involved Log In -> Select Media -> Verify Media Gallery for both Simple and Atomic sites, so I think I've taken both scenarios into account. 

What we can also try is to remove the free domain offer for the testing account, run the 100-iteration against it to fully verify whether this can handle all scenarios:

- Simple
- Atomic w/no offer (static current site card)
- Atomic w/offer (shifting current site card)

**Comment by worldomonation** [comment]
Started another 100-iteration run with the atomic test site's `free domain available` and `domain expired` notice disabled.

https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Playwright_desktop/6509079

Edit: looks like it was able to successfully time out at 20minutes!

image

**Comment by dpasque** [comment]
> To be sure, in the 100-iteration loops I ran last night the task involved Log In -> Select Media -> Verify Media Gallery for both Simple and Atomic sites, so I think I've taken both scenarios into account.

Sounds good! It seems like this approach continues to demonstrate it's reliability, so I think we can definitely run with this for now and revisit if we need to in the future.

I did want to clarify one of the points/questions from above - do you think we need to do anything to handle the case when updating the sidebar takes _longer_ than 250ms? So in that case, the bounding rectangle would stay the same for the first loop and thus continue, but could then update later. In that case, I'm less worried about slowing down other tests, but more about having a false positive.

It sounds like that hasn't been a problem so far in any of the iterations, but I know I definitely have times i pull up a webpage and it just goes so slow for one time, and it might be potentially worthwhile to get in front of it.

But again, I think that also is something we can wait on for now and see if it actually becomes a problem!

**Comment by worldomonation** [comment]
> I did want to clarify one of the points/questions from above - do you think we need to do anything to handle the case when updating the sidebar takes _longer_ than 250ms? So in that case, the bounding rectangle would stay the same for the first loop and thus continue, but could then update later. In that case, I'm less worried about slowing down other tests, but more about having a false positive.

That is true and it's something I've run into while developing locally. I have tried various values and found that sub-30ms is too short and allows this to happen. 250ms is a rather long time, but it almost all but guarantees that sidebar has settled.

I've run _yet_ another iteration of the stress test, this time with a 50ms polling interval and turns out it's also sufficient to prevent false positive seeing that it survived 20 minutes without failing:

https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Playwright_desktop/6509362?buildTab=changes

I do think a polling interval of somewhere in the 100ms range would be best suited though; no point going too aggressive and ending up with intermittent failures just to save tens of milliseconds.

**Comment by WunderBart** [comment]
> I tried running a stress test with @WunderBart's suggested code. (...) It was running quite well for some time (~8min20s) but eventually it encountered the same issue

That's some really nasty race condition then! 😤 (BTW, found this while googling for some info https://github.com/microsoft/playwright/issues/6238 - might be worth subscribing to.)

> > To be sure, in the 100-iteration loops I ran last night the task involved Log In -> Select Media -> Verify Media Gallery for both Simple and Atomic sites, so I think I've taken both scenarios into account.
> 
> Sounds good! It seems like this approach continues to demonstrate it's reliability, so I think we can definitely run with this for now and revisit if we need to in the future.

I agree with @dpasque, although I have one more idea here: It occurred to me that it's also possible for the end-user to misclick because of how lazy-loaded this menu is (happened to me while doing some manual testing). If we adopt this perspective, it means that our current `gotoMenu` method is not only working well as is but is also revealing a potential UX issue where a user needs to correct his navigation target after misclicking. Having said that, that issue might take some time to be addressed (or won't be addressed at all because of really low severity), so we need to focus on the part where the user re-navigates to reach the expected location. In practice, to simulate this behavior we'd need to do 2 more things in the `gotoMenu` method:
1. When the `item -> subitem` clicks are done, check if the expected item is `.selected` (that class is added to the item wrapper), and
2. if it isn't, keep calling the `gotoMenu` again with the same args (e.g. via a recursive call) until it is (or the test times out).

It might sound like we're trying to do a retry that we lost with moving to Jest, but this one is action-targeted, and in my experience, it covers exactly what can happen when a user operates our side nav. What do you think?

**Comment by worldomonation** [comment]
> If we adopt this perspective, it means that our current `gotoMenu` method is not only working well as is but is also revealing a potential UX issue where a user needs to correct his navigation target after misclicking. 

You know, I hadn't thought about it that way, but you are totally right! It is indeed sub-optimal UX for a notice to shift elements so critical to the overall experience.

> we need to focus on the part where the user re-navigates to reach the expected location. In practice, to simulate this behavior we'd need to do 2 more things in the `gotoMenu` method:
>     1. When the `item -> subitem` clicks are done, check if the expected item is `.selected` (that class is added to the item wrapper), and
>     2. if it isn't, keep calling the `gotoMenu` again with the same args (e.g. via a recursive call) until it is (or the test times out).

You know, this is why I appreciate iterating on issues with both you and @dpasque since it's a perspective I hadn't thought about.

I spent today thinking about what your suggestion here might entail, and I think it may possibly be more difficult than the current `boundingBox` implementation because the sidebar isn't standardized in how it denotes being selected:

- some menus receive the `.selected` class.
- some menus receive the `.is-toggle-open` class.

The structure of the elements are all over the place too, with some appending the class to `sidebar > li` and others at `sidebar > li > ul`.

This isn't even taking into account the WPAdmin version of the sidebar yet. 

I personally think we should go ahead with the `boundingBox` approach first, and see if it works well that we can consider the sidebar to be 'stable'. In the meantime I will file a UX bug on the shifting behavior and hopefully we'll have it addressed at some point.

How is this for a course of action? If agreed, I can mark this PR as ready to review after removing the testing bits.

**Comment by worldomonation** [comment]
I tried some other approaches, but could not make them work.

Notably, I think it is possible to implement something similar to what Bart is suggesting with either `setInterval` or `setTimeout`, but I could not get it to work unfortunately even though I was quite close.

**Comment by dpasque** [comment]
> I personally think we should go ahead with the boundingBox approach first, and see if it works well that we can consider the sidebar to be 'stable'. In the meantime I will file a UX bug on the shifting behavior and hopefully we'll have it addressed at some point.
>
> How is this for a course of action? If agreed, I can mark this PR as ready to review after removing the testing bits.

I'm personally good with this! I have a suspicion this sidebar might be an overtime sticking point in general... But I think these changes leave us in a better spot, and hopefully coupled with a fix to that playwright issue we'll be good for a while! We can revisit later as needed.

Thanks for all your hard work and investigation into this, I know it was a lot!

**Comment by WunderBart** [comment]
> I tried some other approaches, but could not make them work.
> 
> Notably, I think it is possible to implement something similar to what Bart is suggesting with either `setInterval` or `setTimeout`, but I could not get it to work unfortunately even though I was quite close.

What if we do something like this:

```js
async function gotoMenu( { item, subitem } ) {
  // Click target (sub)item as we did, no changes in the logic here.
  // At the end, let's add a check for the expected (sub)item and then:

  if ( isExpectedItemActive ) {
    return await this.gotoMenu( { item, subitem } );
  }
}
```

In the case of an endless loop, this should timeout when the global timeout value is reached. How does that sound?

**Comment by worldomonation** [comment]
I made your suggested changes @WunderBart in another branch and ran the stress test - looks like [no dice](https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Playwright_mobile/6550447?focusLine=0).

I've taken bit of a break from this task, as it was driving me up the wall. I will return to this task maybe later this week.

**Comment by WunderBart** [comment]
> I made your suggested changes @WunderBart in another branch and ran the stress test - looks like no dice.
> 
> I've taken bit of a break from this task, as it was driving me up the wall. I will return to this task maybe later this week.

Ugh, sorry to hear that! Thanks for trying all the different angles 🙇. I know how frustrating it can get! I might have a couple more ideas here - will try to run some stress tests myself later this week 🤞

File: packages/calypso-e2e/src/lib/components/sidebar-component.ts [hunk 3]
```diff
@@ -40,64 +33,51 @@ export class SidebarComponent {
...
-			// If there is a subheading, by definition the expanded menu element will always be present.
-			await sidebar.waitForSelector( selectors.expandedMenu );
-			// Explicitly select only the child headings and combine with the text matching engine.
-			// This works better than using CSS pseudo-classes like `:has-text` or `:text-matches` for text
-			// matching.
-			selector = `${ selectors.subheading } >> text="${ subitem }"`;
-			await this._click( selector );
+			await Promise.all( [
+				this.page.waitForNavigation(),
+				this.page.click( `${ itemSelector } >> text="${ subitem }"` ),
```
Comment (worldomonation) [inline packages/calypso-e2e/src/lib/components/sidebar-component.ts]: I've noticed that you're using the `page.click` methods now - does this mean the helper method `_click` isn't used anymore?

File: packages/calypso-e2e/src/lib/components/sidebar-component.ts [hunk 4]
```diff
@@ -40,64 +33,51 @@ export class SidebarComponent {
...
+		 */
+		try {
+			const selectedItemSelector = `.sidebar .selected >> text="${ subitem || item }"`;
+			await this.page.waitForSelector( selectedItemSelector, {
+				timeout: 3000,
+			} );
+			return;
+		} catch {
+			await this.page.reload();
+			return this.gotoMenu( { item, subitem } );
```
Comment (worldomonation) [inline packages/calypso-e2e/src/lib/components/sidebar-component.ts]: I'm curious if this would ever cause either a stack overflow or never ending recursion.

My guess is that `jestTimeoutMS` config value would take over and terminate any errant instances.

File: packages/calypso-e2e/src/lib/components/sidebar-component.ts (hunk 3 above)
Comment (WunderBart) [reply packages/calypso-e2e/src/lib/components/sidebar-component.ts]: Good question. That method was important mostly for the custom scroll-to-item behavior, and I'm not sure if we still need it. I'll run some checks on that and verify.

File: packages/calypso-e2e/src/lib/components/sidebar-component.ts (hunk 4 above)
Comment (WunderBart) [reply packages/calypso-e2e/src/lib/components/sidebar-component.ts]: > My guess is that jestTimeoutMS config value would take over and terminate any errant instances.

I was kinda betting on that. I think, even when looping indefinitely, it will be stopped by the global timeout value. We can also define a limited number of retries if that would make more sense? We could also throw a better error then, so probably that does make more sense.

Comment (WunderBart) [reply packages/calypso-e2e/src/lib/components/sidebar-component.ts]: Added in https://github.com/Automattic/wp-calypso/pull/54987/commits/1c9b5de9df308e038774a7c08cd0c872263296b9

File: packages/calypso-e2e/src/lib/components/sidebar-component.ts (hunk 3 above)
Comment (WunderBart) [reply packages/calypso-e2e/src/lib/components/sidebar-component.ts]: Yep, that one was still needed. Tweaked it a bit and added back in https://github.com/Automattic/wp-calypso/pull/54987/commits/6c7f9f45e493a1779e612c04bf052280d1b15d91.

**Comment by worldomonation** [comment]
Latest changes look good! We also discussed offline that Bart ran the following stress tests:

```
			await sidebarComponent.navigate( 'Settings', 'Hosting Configuration' );
			await sidebarComponent.navigate( 'Beta Testing' );
			await sidebarComponent.navigate( 'My Home' );
			await sidebarComponent.navigate( 'Beta Testing' );
			await sidebarComponent.navigate( 'Upgrades', 'Purchases' );
			await sidebarComponent.navigate( 'Settings', 'General' );
			await sidebarComponent.navigate( 'Comments' );
```

and the changes stood up to that. Bravo!

File: packages/calypso-e2e/src/lib/components/sidebar-component.ts [hunk 5]
```diff
@@ -37,119 +21,107 @@ export class SidebarComponent {
...
+			return;
+		} catch {
+			if ( this.gotoItemRetryCount === 0 ) {
+				const itemPath = subitem ? `${ item } > ${ subitem }` : item;
+				throw new Error( `Couldn't navigate to ${ itemPath }: Expected (sub)item was not active.` );
+			}
+			this.gotoItemRetryCount -= 1;
+			await this.page.reload();
+			return this.navigate( item, subitem );
+		}
```
Comment (dpasque) [inline packages/calypso-e2e/src/lib/components/sidebar-component.ts:88]: This is definitely not a required comment, but is there any reason we can't just do this in a loop instead of involving class state and recursion?

In the current state, each class instance has a fixed number of retries before they are "used up". This means that if someone made one instance of this class in a test script, but did a couple of navigations using that same sidebar, the later navigations may not have retries baked in.

Doing this in a loop instead would make each navigation attempt have the same number of retries!

**Review by dpasque — APPROVED** [review]
Approving with the optional refactoring suggestion!

File: packages/calypso-e2e/src/lib/components/sidebar-component.ts (hunk 5 above)
Comment (WunderBart) [reply packages/calypso-e2e/src/lib/components/sidebar-component.ts:88]: Ah, great point, @dpasque! 🙌 I'm going to address this in a follow-up PR right away. Thanks!

**Comment by worldomonation** [comment]
Finally, thanks for pushing this through @WunderBart !
